### ISSUE TITLE
[Bug] [GTK] MasterDetailPage Icon Doesn't Render Unless Lazy Loaded

### ISSUE THREAD

**Issue by SkyeHoefling** [xamarin/Xamarin.Forms#10002]
### Description
When rendering a `MasterDetailPage` for GTK it does not render correctly unless the `Detail` page is populated after the `Appearing` event. This introduces lack of feature parity between `MasterDetailPage` on iOS/Android vs GTK

### Steps to Reproduce

1. Open provided sample project on linux and run project
2. Run App

The reproduction steps should work on MacOS and Windows but this problem was only tested on WSL Ubuntu

### Expected Behavior
* The menu icon to appear

### Actual Behavior
* The menu icon doesn't appear, if you hover the mouse over to where it would appear you will see a button

### Basic Information

- Version with issue:
- Last known good version:
- IDE: monodevelop 7.8.4 (build 2) on WSL Ubuntu
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  N/A
  - GTK: 2.12.0.0
- Android Support Library Version: 
- Nuget Packages:
  - Xamarin.Forms: 4.5.0.356
  - Xamarin.Forms.Platform.GTK: 4.5.0.356
  - OpenTK: 3.0.1
- Affected Devices:

### Screenshots
**Not Working**
![image](https://user-images.githubusercontent.com/17751436/76902479-719e9480-6872-11ea-90b7-92c3c7bcd430.png)

**Work around applied**
![image](https://user-images.githubusercontent.com/17751436/76903710-e1ae1a00-6874-11ea-828c-267bb6f6302a.png)

### Reproduction Link
[MasterDetailBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4345975/MasterDetailBug.zip)

### Workaround
If you uncomment the code in
* `MasterDetailPage.xaml.cs`

This will resolve the problem. It appears that there is an order of operation error happening and the Detail section of the Master Detail needs to be updated after the `Appearing` event is fired

Below is a code snippet for the MasterDetail Usage. When the commented out code is uncommented the icon appears correctly
```c#
using Xamarin.Forms;

namespace MasterDetailBug.Views
{
	public partial class MasterDetailPage : Xamarin.Forms.MasterDetailPage
	{
		public MasterDetailPage()
		{
			InitializeComponent();
		}

		protected override void OnAppearing()
		{
			base.OnAppearing();

			/*if (Application.Current.MainPage is Views.MasterDetailPage masterPage)
			{
				var mainPage = new MainPage();
				var navigationPage = new CustomNavigationPage(mainPage);
				masterPage.Detail = navigationPage;
			}*/
		}
	}
}
```

**Comment by Graveen** [comment]
Thank you. Where can i apply your bugfix ? Although i have all references, it claims "InitializeComponents" is not reachable.

**Comment by Graveen** [comment]
When i use the Movies GTK example, it works, with Xamarin Forms 3.1. Btw it is broken with recent versions.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
