### ISSUE TITLE
Support for Right To Left Layout for Right To Left Languages

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/Xamarin.Forms#10005]
## Summary
Add Full Support for **Right To Left Layout for Right To Left Languages** Like Arabic, Ebri , Persian

## API Changes
Add Full Support for Right To Left Layout for languages Like Arabic,Ebri , Persian(Right To Left Languages) to Views ,Pages,....
Currently many Views Lacks Right To Left layout(Like Shell (humberger icon and it's page direction)) or doesn't support it completely (Like CollectionView , ...).

## Intended Use Case
in **Right To Left Languages** and Cultures , element are arranged in right to left direction.
**Adding Full Support For Right To Left Layout causes to use XAMARIN FORMS in Right TO Left Languages and Cultures.**
I migrated from Delphi /Firemonkey to Xamarin Forms  due to lack of this feature (Right To Left Layout support) in Delphi/Firwmonkey, but I noticed XAMARIN FORMS doesn't fully support Right To Left languages. I think if you don't Add this feature for all Views, you will Lose a vast market of Developers.
Thank You.

**Comment by jfversluis** [comment]
Thanks for the suggestion @hamiddd1980 are there any specific cases where you could not get it to work? We have [RTL support out of the box](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left). There are [some issues](https://github.com/xamarin/Xamarin.Forms/issues?q=is%3Aissue+is%3Aopen+label%3Aa%2Frtl+) open, but I think generally speaking we should have support for it.

If you have some specific control or scenario where it is missing then please add to one of the open issues or open a new one.
