### ISSUE TITLE
[Bug] [GTK] MasterDetail Icon Mouse Hover Displays Underlying Button

### ISSUE THREAD

**Issue by SkyeHoefling** [xamarin/Xamarin.Forms#10003]
### Description
When using a `MasterDetailPage` on GTK the Icon renders the same behaviors as the `Button` when the mouse hovers over the control. This may not always be the most desired effect, especially true if you want your Master Detail Hamburger Icon to match the same UI behaviors as iOS/Android/UWP

### Steps to Reproduce

1. Open project and debug GTK project (this was all done on WSL Ubuntu)
2. Hover mouse over the hamburger icon

The same behavior should occur on MacOS but it was not tested

### Expected Behavior
I expected the button hover effect to be disabled

### Actual Behavior
When the user hovers the mouse over the icon, it renders the `Button` hover effect native to GTK.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: monodevelop 7.8.4 (build 2) on WSL Ubuntu
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  N/A
  - GTK: 2.12.0.0
- Android Support Library Version: 
- Nuget Packages:
  - Xamarin.Forms: 4.5.0.356
  - Xamarin.Forms.Platform.GTK: 4.5.0.356
  - OpenTK: 3.0.1
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/17751436/76906107-ac57fb00-6879-11ea-9a82-18c6d3c2c2ef.png)

### Reproduction Link
[MasterDetailBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4346029/MasterDetailBug.zip)

### Workaround
No workaround investigated. I think we could disable the button hover effect in the renderer. Maybe a more permanent solution would be exposing some attached property for `ToolButton` that is used in the custom control for MasterDetailPage in GTK

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
