### ISSUE TITLE
[Bug, UWP]   IndicatorCodeGallery - I can't get to the last item.

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#10019]
### Description
 IndicatorCodeGallery - I can't get to the last item. I scroll my mouse wheel and it just gets stuck on the 4th item. Also removing items seems to kind of break it

Carousel XAML - If you click the arrows really fast they stop working

https://xamarinhq.slack.com/archives/CF98LQ1L3/p1584553458168500

**Comment by rmarinho** [comment]
Using PeekAreaInsets fails on UWP.
