### ISSUE TITLE
Frame animation issue/inconsistency in latest version of Forms/Xamarin iOS

### ISSUE THREAD

**Issue by brad302** [xamarin/Xamarin.Forms#10024]
I'm having an issue where the latest version (not sure how back it was introduced but was working on Xamarin.iOS 12.14) has introduced an issue with animating a frame to screen when using a combination of TranslateTo and RotateYTo.

I've narrowed the issue down to when HasShadow="True".  If the frame is not showing a shadow, the animation works correctly.  If the frame is showing a shadow, the animation goes all skewif with the part of the view that looks to be the shadow.

You can see the behaviour specifically in this github repo and there are two videos showing the behaviour so at least you don't need to pull down the repo to see ...

https://github.com/brad302/Xamarin/tree/master/FrameIssue

Keen to get the Xamarin teams views on this.  It's not a showstopper but it is annoying, the shadow formed part of the effect, especially given it's meant to look like it's floating on top of the window and this was working previously.

**Comment by jfversluis** [comment]
Related to #9990, #9774, #8567 and possibly more. Introduced by #7518.

**Comment by haavamoa** [comment]
Hello, I think we I found a bug that is related to this. We have an library that provides a sheet control that has a grayed out overlay. That overlay is `Frame` with a shadow.

This is how it should look:

![frame_shadowbug_fixed](https://user-images.githubusercontent.com/2527084/79017581-ffb82300-7b71-11ea-9418-e1911fdec920.gif)


After upgrading to Xamarin.Forms 4.5.617 we suddenly got this:

![frame_shadowbug_ios](https://user-images.githubusercontent.com/2527084/79017405-85879e80-7b71-11ea-9825-4860180c564d.gif)

I fixed the issue by setting the `HasShadow` property to `false` on that overlay `Frame` and everything was working again. (Fortunately it was a mistake that we had the `HasShadow` property set to `true`, as we don't really need to have a shadow).

You can use our repository to reproduce the bug by:
- Clone at [this](https://github.com/DIPSAS/DIPS.Xamarin.UI/tree/9fbe4d39f355adda0d21a798d6cc0d19d8881918) point in time.
- Upgrade the entire project to Xamarin.Forms 4.5.617.
- Start the `DIPS.Xamarin.UI.Samples.iOS`.
    - Navigate: `Controls` > `Sheet`.
    - Click `Open sheet` at bottom of the page.
