### ISSUE TITLE
[Bug] CarrouselView inside Tabbed page App the IndicatorView is not showing the current position when you move between tabs

### ISSUE THREAD

**Issue by gatsbys** [xamarin/Xamarin.Forms#10026]
# Description

I have a tabbed based app with 5 tab pages.
The Carousel View and its indicator are on the first page. 
When the app starts both CarouselView and Indicator are working as expected, when you swipe then the indicator shows you the curren position.

When you go to another tab and go back again to the tab that has the Carousel and start swiping between items the Indicator does not show the correct position it shows you always like you are on the first item but you are not.

### Steps to Reproduce

1. Tabbed App, swipe on the carousel to the 2nd or 3rd item.
2. Go to another tab and go back again to the carousel tab
3. Swipe and see the behavior, the indicator is always on the first item
4. If after moving to second or third item you go back to the first then all start working as expected.

### Expected Behavior
When you move between tabs the Indicator show the current position of your carousel.

### Actual Behavior
When you move between tabs you need to swipe your carousel to different item and go back again to first, then Indicator start working again.

**### On iOS, when you move between pages, de Carousel stores the position and all is working as expected.**

### Basic Information

- Version with issue: Xamarin.Forms 4.5.0.396
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  Working as expected
  - Android: 9.0 
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![Error Tab Page](https://user-images.githubusercontent.com/7467328/77090312-3e413e80-6a07-11ea-9654-f7cc107533e8.gif)

### Workaround

On [MyPage].xaml.cs , I am handling the CurrentItemChanged and saving the current object on a private variable, then on the OnAppearing event of the page I am setting it back to the [myCarrousel].CurrentItem.

**Comment by jfversluis** [comment]
Hey @gatsbys thank you for taking the time to write this great bug report! Would you happen to have a small reproduction project that shows this issue by any chance?

**Comment by gatsbys** [comment]
Hi @jfversluis !
Thank you too!

I will try to provide a repro project but as far I am seeing right now I think the issue is related in the way Android TabbedPage in handling `android:TabbedPage.OffscreenPageLimit `

If I increase the OffscreenPageLimit to >= my App Tab number pages the issue is not repro. The Carousel saves the state between Tab changes!

![image](https://user-images.githubusercontent.com/7467328/77093232-ff14ec80-6a0a-11ea-931a-a04e4c3c221d.png)

Maybe would be great to add this to the docs?  What do you think? Have you seen that before?

Thanks!

**Comment by samhouts** [comment]
@gatsbys Yes, it's expected that the TabbedPage on Android only holds a certain number of pages in memory. The inactive pages are disposed for performance benefits. You can prevent them from being disposed by increasing the OffscreenPageLimit as you've done. Thanks!
