### ISSUE TITLE
[Bug] [Android, UWP] ListView item with checkbox and label not rendered properly

### ISSUE THREAD

**Issue by Chansardrake** [xamarin/Xamarin.Forms#10037]
### Description
Label inside ListView item is cropped when label and checkbox used.

Code Snippet : 
```
<ListView
Margin="10" BackgroundColor="LightBlue" HasUnevenRows="True"
ItemsSource="{Binding BookInfo}">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Grid
                Padding="5"
                HorizontalOptions="FillAndExpand"
                ColumnSpacing="10">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto"/>
                        <RowDefinition Height="Auto"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto"/>
                        <ColumnDefinition Width="Auto"/>
                    </Grid.ColumnDefinitions>
                    <CheckBox Grid.Column="0"/>
                    <Label
                    Grid.Row="0" Grid.RowSpan="2"
                    Grid.Column="1"
                    Text="{Binding BookName}" 
                    TextColor="White"
                    FontAttributes="Bold"
                    FontSize="20"
                    LineBreakMode="WordWrap"/>
                </Grid>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

### Steps to Reproduce

1. Run the attached sample in Android and UWP

### Expected Behavior
Label should render properly without cropping
### Actual Behavior
Label is cropped
### Basic Information

- Version with issue: 4.5.0.356
- IDE: Visual Studio 2017

### Screenshots

![Screenshot_20200320-162332](https://user-images.githubusercontent.com/21023069/77166534-6f3e7380-6ada-11ea-91b7-4e92c28b4d1e.png)

**Sample Link:** [Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/ListViewIssue1913192767.zip)

**Comment by jfversluis** [comment]
Hey there @Chansardrake thanks for the report.

I have taken a look at your sample and I noticed that you are using a `Grid` with rows in your cell, while the rows are not actually used.

I have changed the XAML in your MainPage.xaml to this

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:GettingStarted;assembly=GettingStarted"
             x:Class="GettingStarted.MainPage">

    <ContentPage.BindingContext>
        <local:BookInfoRepository />
    </ContentPage.BindingContext>

    <ListView
        Margin="10" BackgroundColor="LightBlue" HasUnevenRows="True"
        ItemsSource="{Binding BookInfo}">
        <ListView.ItemTemplate>
            <DataTemplate>
                <ViewCell>
                    <Grid
                        AutomationId="1"
                        Padding="5"
                        HorizontalOptions="FillAndExpand"
                        ColumnSpacing="10">
                        <!-- Removed RowDefinitions here -->
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto"/>
                            <ColumnDefinition Width="*"/>
                        </Grid.ColumnDefinitions>
                        <CheckBox Grid.Column="0"/>
                        <Label
                            <!-- Removed Grid.Row="0" Grid.RowSpan="2" -->
                            Grid.Column="1"
                            Text="{Binding BookName}" 
                            TextColor="White"
                            FontAttributes="Bold"
                            FontSize="20"
                            LineBreakMode="WordWrap"/>
                    </Grid>
                </ViewCell>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</ContentPage>
```

Now the layout shows fine.

![image](https://user-images.githubusercontent.com/939291/77175296-b3257e80-6ac2-11ea-9623-730290aa43f1.png)

Closing this issue for now, if you think you are still running into a bug, please let me know

**Comment by Chansardrake** [comment]
> Hey there @Chansardrake thanks for the report.
> 
> I have taken a look at your sample and I noticed that you are using a `Grid` with rows in your cell, while the rows are not actually used.
> 
> I have changed the XAML in your MainPage.xaml to this
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
>              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
>              xmlns:local="clr-namespace:GettingStarted;assembly=GettingStarted"
>              x:Class="GettingStarted.MainPage">
> 
>     <ContentPage.BindingContext>
>         <local:BookInfoRepository />
>     </ContentPage.BindingContext>
> 
>     <ListView
>         Margin="10" BackgroundColor="LightBlue" HasUnevenRows="True"
>         ItemsSource="{Binding BookInfo}">
>         <ListView.ItemTemplate>
>             <DataTemplate>
>                 <ViewCell>
>                     <Grid
>                         AutomationId="1"
>                         Padding="5"
>                         HorizontalOptions="FillAndExpand"
>                         ColumnSpacing="10">
>                         
>                         <Grid.ColumnDefinitions>
>                             <ColumnDefinition Width="Auto"/>
>                             <ColumnDefinition Width="*"/>
>                         </Grid.ColumnDefinitions>
>                         <CheckBox Grid.Column="0"/>
>                         <Label
>                             
>                             Grid.Column="1"
>                             Text="{Binding BookName}" 
>                             TextColor="White"
>                             FontAttributes="Bold"
>                             FontSize="20"
>                             LineBreakMode="WordWrap"/>
>                     </Grid>
>                 </ViewCell>
>             </DataTemplate>
>         </ListView.ItemTemplate>
>     </ListView>
> </ContentPage>
> ```
> 
> Now the layout shows fine.
> 
> ![image](https://user-images.githubusercontent.com/939291/77175296-b3257e80-6ac2-11ea-9623-730290aa43f1.png)
> 
> Closing this issue for now, if you think you are still running into a bug, please let me know

Hi @jfversluis thanks for the update.
I need the checkbox to be in first row even thought the label content is large.
Thanks.

**Comment by jfversluis** [comment]
I think you can achieve that by using the [`VerticalOptions`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options) property on the `CheckBox`
