### ISSUE TITLE
[Bug] System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.'

### ISSUE THREAD

**Issue by easoftwaresanderson** [xamarin/Xamarin.Forms#10031]
### Description
I have been sporadic crashes on Android  where I get System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.'
It happen when a start a faster navigation between pages (using prism navigation), when I tapped one item in listView, I open another page with other listView with items chosen before. So I'm used open and click in a button to back navigation quickly.
In 3 or 4 times doing it crash happen.

### Steps to Reproduce

1.  Open on page with ListView Items , choose one Item 
2.  Navigate to another page with other items and choose one
3.  Navigate to a 3º page with items chosen
4 - Click on button back , or use one button to back navigation
5 - Repeat this steps quickly 3 or 4 times or until crash happen
 
### Expected Behavior
No message crash 
### Actual Behavior
Crashes for customers and end users
### Basic Information

- Version with issue: 4.6.0.379-pre1
- Last known good version: 4.5 in Visual Studio 2019 16.4
- IDE: in Visual Studio 2019 16.5
- Platform Target Frameworks: 
  - iOS: N/A
  - Android:  5.1 to 9
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: 
    Com.OneSignal" Version="3.7.2
    Microsoft.AppCenter.Analytics" Version="3.0.0"
    Microsoft.AppCenter.Crashes" Version="3.0.0"
    Microsoft.Azure.DocumentDB.Core" Version="2.9.4"
    Plugin.Permissions" Version="3.0.0.12" 
    Prism.Unity.Forms" Version="7.0.0.396" 
    Rg.Plugins.Popup" Version="1.2.0.223" 
    Xam.Plugin.Connectivity" Version="3.2.0" 
    Xam.Plugin.Media" Version="4.0.1.5" 
    Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" 
    Xam.Plugins.Messaging" Version="5.2.0" 
    Xamarin.Essentials" Version="1.5.0" 
    Xamarin.Forms" Version="4.6.0.379-pre1" 
    Xamarin.Forms.Maps" Version="4.5.0.356" 
    XamarinForms.CardView" Version="1.1.1.5" 
- Affected Devices:
Android 8.0 Api 26

### Screenshots
![image](https://user-images.githubusercontent.com/40809443/77108047-56fa2600-6a00-11ea-97cd-ef5538d80048.png)

### Workaround
No known workarounds currently.

**Comment by jfversluis** [comment]
Hey @easoftwaresanderson thanks for the report! Would you be able to add a small reproduction project for this or at least the full stack trace would be super helpful.

Thanks!

**Comment by easoftwaresanderson** [comment]
> Hey @easoftwaresanderson thanks for the report! Would you be able to add a small reproduction project for this or at least the full stack trace would be super helpful.
> 
> Thanks!
I'm not able to do this small project now. How can I get full stack trace? 
I'm using try catch around the code navigation, but I don't get any exception.

**Comment by easoftwaresanderson** [comment]
> Hey @easoftwaresanderson thanks for the report! Would you be able to add a small reproduction project for this or at least the full stack trace would be super helpful.
> 
> Thanks!

I'm not able to do this small project now. But I'll try asap . 
How can I get full stack trace? 
I'm using try catch around the code navigation, but I don't get any exception.

Thanks for your response.

**Comment by jfversluis** [comment]
That would be great! 

For the stack trace; when you hit the exception like in the screenshot, just click the "continue debug" button, so the play button and check the application output pane. The full stack trace should be in there. It will start with the message you posted here: "System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.'" and after that lists all the methods that this error message was bubbled up from. Does that make sense?

**Comment by rezamohamed** [comment]
I have the same issue, I am simply adding a FacebookButtonLoginRenderer to Android based on this tutorial https://evgenyzborovsky.com/2018/03/09/using-native-facebook-login-button-in-xamarin-forms/ From what I found on the web, I added a try, catch, but the error still shows up on the error list (image below).

The exception is: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Xamarin.Facebook.Login.Widget.LoginButton'

For reference:
Xamarin.Forms v4.5.0.396
Debugging to Android Emulator 9.0 API 28
Visual Studio 2019 v16.5.0

![image](https://user-images.githubusercontent.com/18199852/77219838-90698900-6b07-11ea-9873-377d88f8f323.png)

**Comment by PureWeen** [comment]
it's hard to know without a stack trace but I'm guessing this is caused by this override

https://github.com/xamarin/Xamarin.Forms/blob/954cc8b0f174f179fd3395b4b1f257201f9701af/Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs#L70

Which we fixed here
https://github.com/xamarin/Xamarin.Forms/commit/239ba5046acc37259f3135bc33dd1b27bf72c8f3#diff-73413fddc3cbc5833a45ef04800f3f68L29

But it's really hard to know without a complete stack trace

**Comment by PureWeen** [comment]
If you set this flag
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers#backwards-compatibility

do you still get the same exception?

**Comment by easoftwaresanderson** [comment]
> If you set this flag
> https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers#backwards-compatibility
> 
> do you still get the same exception?

Yes, I get the same exception. This one was with the flag set.

**Comment by PureWeen** [comment]
@easoftwaresanderson sounds good

Without a full stack trace though we might only be lucky to address your use case.

This type of exception is basically the same as an NRE exception. Without a full stack trace it's hard to know what specific path is causing yours

**Comment by easoftwaresanderson** [comment]
Here my stack trace , sorry not send  it before.
 
>	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#
 	0x1F in Xamarin.Forms.Platform.Android.Platform.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1332,4	C#
 	0x3 in Xamarin.Forms.Forms.AndroidPlatformServices.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Forms.cs:855,5	C#
 	0x2D in Xamarin.Forms.VisualElement.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:787,4	C#
 	0x13 in Xamarin.Forms.Image.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\Image.cs:74,4	C#
 	0x3 in Xamarin.Forms.VisualElement.OnMeasure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:770,4	C#
 	0x56 in Xamarin.Forms.VisualElement.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:646,4	C#
 	0x57 in Xamarin.Forms.VisualElement.Measure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:704,4	C#
 	0x120 in Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:166,5	C#
 	0x152 in Xamarin.Forms.Grid.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:49,5	C#
 	0x160 in Xamarin.Forms.Layout.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266,4	C#
 	0x10 in Xamarin.Forms.Layout.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224,4	C#
 	0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:792,4	C#
 	0x60 in Xamarin.Forms.Layout.ResolveLayoutChanges at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392,6	C#

**Comment by easoftwaresanderson** [comment]
> @easoftwaresanderson sounds good
> 
> Without a full stack trace though we might only be lucky to address your use case.
> 
> This type of exception is basically the same as an NRE exception. Without a full stack trace it's hard to know what specific path is causing yours

Here my stack trace , sorry not send it before.

0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4 C#
0x1F in Xamarin.Forms.Platform.Android.Platform.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1332,4 C#
0x3 in Xamarin.Forms.Forms.AndroidPlatformServices.GetNativeSize at D:\a\1\s\Xamarin.Forms.Platform.Android\Forms.cs:855,5 C#
0x2D in Xamarin.Forms.VisualElement.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:787,4 C#
0x13 in Xamarin.Forms.Image.OnSizeRequest at D:\a\1\s\Xamarin.Forms.Core\Image.cs:74,4 C#
0x3 in Xamarin.Forms.VisualElement.OnMeasure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:770,4 C#
0x56 in Xamarin.Forms.VisualElement.GetSizeRequest at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:646,4 C#
0x57 in Xamarin.Forms.VisualElement.Measure at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:704,4 C#
0x120 in Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:166,5 C#
0x152 in Xamarin.Forms.Grid.LayoutChildren at D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:49,5 C#
0x160 in Xamarin.Forms.Layout.UpdateChildrenLayout at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266,4 C#
0x10 in Xamarin.Forms.Layout.OnSizeAllocated at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224,4 C#
0x3 in Xamarin.Forms.VisualElement.SizeAllocated at D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:792,4 C#
0x60 in Xamarin.Forms.Layout.ResolveLayoutChanges at D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392,6 C#

**Comment by kgouraw** [comment]
I am using Xamarin.Forms Material Visual for some of the controls, and below flag fixes my issue as a work around for now.
Forms.SetFlags("UseLegacyRenderers");
(https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers#backwards-compatibility)

**Comment by easoftwaresanderson** [comment]
> I am using Xamarin.Forms Material Visual for some of the controls, and below flag fixes my issue as a work around for now.
> Forms.SetFlags("UseLegacyRenderers");
> (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers#backwards-compatibility)

Thank you 

I had done setting this flag, but unfortunately I didn't succeed.

I decreased the navigation of pages to get around the issue, so I managed to make it functional and published an alpha version for test users. In the tests I get in App Center >> Diagnostics >> Issues the following related crash is occurring 
 
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.get_Context ()
Platform.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint)
Forms+AndroidPlatformServices.GetNativeSize (Xamarin.Forms.VisualElement view, System.Double widthConstraint, System.Double heightConstraint)
VisualElement.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
Image.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region)
Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
Layout.UpdateChildrenLayout ()
Layout.OnSizeAllocated (System.Double width, System.Double height)
VisualElement.SizeAllocated (System.Double width, System.Double height)
Layout.ResolveLayoutChanges ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.60(intptr,intptr)

**Comment by actopozipc** [comment]
I might be wrong, but this exception might be related to the back button and not to a specific view. Ive got the same exception with Android.Webview on the starting page if I exit through the back button and open the app again. Sometimes I need to do this a few times in order to reproduce.   
I also tried reproducing the bug through lockscreen, but it did not succeed.  

Maybe overwriting the back-button in some way leads to an workaround.

**Comment by actopozipc** [comment]
I might have found a workaround, althrough Im not sure if this is healthy for the garbage collector:  
1. Create a custom renderer for the View that throws the exception
2.
```
 protected override void Dispose(bool disposing)
        {
            return;
        }
```

**Comment by crs2m5smith** [comment]
the above workaround did not work for me, setting Dispose to return still causes exception

**Comment by multitracks** [comment]
We are seeing this as well. Bummer about to release on Android and we are running into a 5 month old bug.

**Comment by actopozipc** [comment]
> 
> 
> the above workaround did not work for me, setting Dispose to return still causes exception

Did you put it into a custom renderer? Is there any other code in your overrided method? If so, can I see your code?
Anyway, I hate this solution, because not disposing leads to a massive usage of RAM

**Comment by kgouraw** [comment]
I checked on Xamarin Forms 4.7.0.1351, and it's reproducible over there. @samhouts, how soon could we get the next update of SF 4.7 (5.0.0) with this fix?

**Comment by kgouraw** [comment]
I have found a work around for it with XF 4.7 by reseting the ItemSource of collection-view.
This has been also addressed with upcoming Xamarin Forms 5.0.0, check pre-release notes.
https://github.com/xamarin/Xamarin.Forms/issues/10801

**Comment by AswinPG** [comment]
I am also facing the same issue but on navigating back from a hybrid webview - https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview


System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'Android.Webkit.WebView'.'

**Comment by n8water** [comment]
I get a similar message in an app using Shell. 
This exception is thrown when I navigate from any other page to the Mainpage, where most of the action should happen.

[AppCenterCrashes] Unhandled Exception from source = AndroidEnvironment
[AppCenterCrashes] System.ObjectDisposedException: Cannot access a disposed object.
[AppCenterCrashes] Object name: 'Xamarin.Forms.Platform.Android.ImageButtonRenderer'.
[AppCenterCrashes]   at Java.Interop.JniPeerMembers.AssertSelf(Java.Interop.IJavaPeerable self) [0x00029] in < 94b04e1756104d1fa1d144932ae2720c >:0
 [AppCenterCrashes]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)[0x00000] in <94b04e1756104d1fa1d144932ae2720c>:0 
[AppCenterCrashes] at Android.Widget.ImageView.ClearColorFilter ()[0x00000] in /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.Widget.ImageView.cs:867 
[AppCenterCrashes] at Xamarin.CommunityToolkit.Android.Effects.IconTintColorEffectRouter.ClearTintColor ()[0x0001c] in <08abc6c084af4622851290c7f2f974ff>:0 
[AppCenterCrashes] at Xamarin.CommunityToolkit.Android.Effects.IconTintColorEffectRouter.OnDetached ()[0x00000] in <08abc6c084af4622851290c7f2f974ff>:0 
[AppCenterCrashes] at Xamarin.Forms.Effect.SendDetached ()[0x00009] in D:\a\1\s\Xamarin.Forms.Core\Effect.cs:62 
[AppCenterCrashes] at Xamarin.Forms.PlatformEffect`2[TContainer, TControl].SendDetached ()[0x00000] in D:\a\1\s\Xamarin.Forms.Core\PlatformEffect.cs:23 
[AppCenterCrashes] at Xamarin.Forms.RoutingEffect.SendDetached ()[0x00000] in D:\a\1\s\Xamarin.Forms.Core\RoutingEffect.cs:34 
[AppCenterCrashes] at Xamarin.Forms.Element.set_EffectControlProvider (Xamarin.Forms.IEffectControlProvider value)[0x0002e] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:230 
[AppCenterCrashes] at Xamarin.Forms.Internals.EffectUtilities.RegisterEffectControlProvider (Xamarin.Forms.IEffectControlProvider self, Xamarin.Forms.IElementController oldElement, Xamarin.Forms.IElementController newElement)[0x0001a] in D:\a\1\s\Xamarin.Forms.Core\Internals\EffectUtilities.cs:16 
[AppCenterCrashes] at Xamarin.Forms.Platform.Android.FastRenderers.VisualElementRenderer.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e)[0x0005c] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\VisualElementRenderer.cs:102 
[AppCenterCrashes] at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs].invoke_void_object_TEventArgs(object, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs)
[AppCenterCrashes]   at Xamarin.Forms.Platform.Android.ImageButtonRenderer.Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement(Xamarin.Forms.VisualElement element) [0x000dd] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\ImageButtonRenderer.cs:192
[AppCenterCrashes]   at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild(Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameC04-02 09:20:00.490 E/AppCenterCrashes(32503):   at Xamarin.Forms.Platform.Android.Platform.CreateRenderer(Xamarin.Forms.VisualElement element, Android.Content.Context context) [0x0003e] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:358
[AppCenterCrashes]   at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement(Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00163] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:351
[AppCenterCrashes]   at Xamarin.Forms.Platform.Android.VisualElementPackager.Load() [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:112
[AppCenterCrashes]   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetPackager (Xamarin.Forms.Platform.Android.VisualElementPackager packager)[0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:481 
[AppCenterCrashes] at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element)[0x000e8] in D:\a\1\s\Xa
The thread 0x1c has exited with code 0 (0x0).
Thread finished: < Thread Pool > #28
[Mono] Requesting loading reference 5(of 6) of Microsoft.AppCenter.Crashes.dll
[Mono] Loading reference 5 of Microsoft.AppCenter.Crashes.dll asmctx DEFAULT, looking for System.Core, Version= 2.0.5.0, Culture= neutral, PublicKeyToken= 7cec85d7bea7798e
[Mono] Assembly Ref addref Microsoft.AppCenter.Crashes[0xd9a280c0] -> System.Core[0xbcae8280]: 12
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_throw'.
[Mono] Probing 'java_interop_jnienv_throw'.
[Mono] Found as 'java_interop_jnienv_throw'.
* *System.ObjectDisposedException:**'Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.ImageButtonRenderer'.'

**Comment by n8water** [comment]
I had a similar issue with navigation in xamarin forms shell, could solve it by updating Xamarin.Essentials, Xamarin.CommunityToolkit and Xamarin.Forms.

**Comment by AswinPG** [comment]
> I am also facing the same issue but on navigating back from a hybrid webview - https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview
> 
> System.ObjectDisposedException: 'Cannot access a disposed object.
> Object name: 'Android.Webkit.WebView'.'

This was a mistake from my side. The website was calling a function after xamarin forms disposed the webview

**Comment by avksp** [comment]
> I had a similar issue with navigation in xamarin forms shell, could solve it by updating Xamarin.Essentials, Xamarin.CommunityToolkit and Xamarin.Forms.

I updated Xamarin.Essentials (1.61.1), Xamarin.Forms (5.0.0.2012). But the problem still hasn't gone away.

**Comment by kiran-nel** [comment]
I am facing same issue "System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'." 

Im using Xamarin 4.8 and Xamarin.Essentials (1.61.1) .
any solution.?

**Comment by Tim-Rossiter** [comment]
Also receiving the error. 
Xamarin Forms, Prism, Custom Renderer for Android following Microsoft docs w/back navigation
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview
https://docs.microsoft.com/en-us/answers/questions/403328/hybridwebview-cangoback-amp-goback-using-mvvm.html
```
Cannot access a disposed object.
Object name: 'Android.Webkit.WebView'.
```

**Comment by minaairsupport** [comment]
I am having the same issue 
`Forms.SetFlags("UseLegacyRenderers");`
tried pass source by viewmodel 
dosent work for me as well

my Xamarin.Forms 5..0.0.2196

anyone found a walkaround

**Comment by kgouraw** [comment]
> I am having the same issue `Forms.SetFlags("UseLegacyRenderers");` tried pass source by viewmodel dosent work for me as well
> 
> my Xamarin.Forms 5..0.0.2196
> 
> anyone found a walkaround

I have handled by resetting the Collections in the catch.

**Comment by minaairsupport** [comment]
sorry could you give me an example for how resetting the collection

**Comment by kgouraw** [comment]
> sorry could you give me an example for how resetting the collection

Reset the binding ObservableCollection by clearing and initializing it again.
    ```
   public void Reset(IEnumerable<T> range)
        {
            this.Items.Clear();
            if (range != null)
            {
                AddRange(range);
            }
        }
```

**Comment by jfversluis** [comment]
For whoever that might still be watching this, I have opened a PR (#14933) for this with hopefully something that should fix this. Would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!
