### ISSUE TITLE
[Enhancement] xmlns design schema to support BindingContext for Intellisense

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#10045]
## Summary
Currently we have the following design schema support in Xamarin Forms

```xaml
<ContentPage
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    mc:Ignorable="d">
```

However, some folks are used to the Blend approach

```xaml
<ContentPage
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:vm="clr-My.App.ViewModels;assembly=My.App"
    d:DataContext="{d:DesignInstance d:Type=vm:MyViewModel, IsDesignTimeCreatable=True}"
    mc:Ignorable="d">
```
the difference between these two is that we can get automatic intellisense from the blend approach because it supports us defining the `d:DataContext`, which the 2014/forms/design namespace does not.

I'm wondering if the forms design schema can give us a `d:BindingContext` solution similar to Blend?

## API Changes
```xaml
<ContentPage
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:vm="clr-My.App.ViewModels;assembly=My.App"
    d:BindingContext="{d:DesignInstance d:Type=vm:MyViewModel, IsDesignTimeCreatable=True}"
    mc:Ignorable="d">
```

## Intended Use Case
We'd like to be able to see viewmodel intellisense in our bindings

<img width="677" alt="Screen Shot 2020-03-20 at 2 23 12 PM" src="https://user-images.githubusercontent.com/471626/77207335-5a4fe900-6ab6-11ea-84d2-eaabb071c7e6.png">

**Comment by ChaseFlorell** [comment]
So after a conversation with Norman Mackay on Twitter, he directed me to `x:DataType`.
I think this is a great approach as well, but it does mean that you have to do a lot of additional work in order to get it working. The one thing I noticed right away is that bindings inside a DataTemplate on a CollectionView failed because it was looking at the wrong DataType (Could not find Property x), so I had to add another `x:DataType` inside the collection view.

This could get tedious after a while.

**Comment by Syed-Esqimo** [comment]
> This could get tedious after a while, and therefore I still think this feature request is valid in that it's a quick win in getting intellisense support.

So why is this closed?

**Comment by ChaseFlorell** [comment]
> So why is this closed?

I closed it. x:DataType will do what you need for intellisense. 
Between x:DataType and     xmlns:d="http://xamarin.com/schemas/2014/forms/design", you should have everything you need.

I don't know why they didn't want to support blend, but I'm sure they have more important things to worry about.
