### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thales-man** [xamarin/Xamarin.Forms#10043]
#9324 
# Description
forms upgrade (4.5.396)

### Steps to Reproduce
upgrade the nuget package and build

### Expected Behavior
should work
### Actual Behavior
doesn't

### Basic Information
now get 212 instances this error

/Users/blah/Projects/Framework4/Platforms/iOS/CSC: Error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/blah/.nuget/packages/tiny.framework.application/2.0.0/lib/netstandard2.0/System.Xml.XmlSerializer.dll' and '/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Facades/System.Xml.XmlSerializer.dll'. Remove one of the duplicate references. (CS1703) 

Version with issue:
see above
Last known good version:
not sure, project now hacked to buggery trying to get yet another brittle xamarin delivery fixed...

IDE:
VS for Mac (8.4.8 build 2)

Platform Target Frameworks:
iOS, Android and macOS

Nuget Packages:
Xamarin forms and local nuget package for product using net standard api 2.0 (was 2.1 but had to step it back, not Xamarin / Mac OS compatible?)

### Workaround
none

**Comment by thales-man** [comment]
further to this:
created a new IOS project to solution => build ok
added net standard 2 project to IOS project = > build ok
added Xamarin forms to IOS project in solution = > boom!

the net 2 standard project references Xamarin Forms as it contains generic use items for platform specific distribution.

more examples of errors now given:
/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3243: No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily. (MSB3243) ({my test library})

/Users/blah/Projects/{my library path}/CSC: Error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/blah/.nuget/packages/{my library path}/2.0.0/lib/netstandard2.0/System.Xml.XmlSerializer.dll' and '/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/lib/mono/Xamarin.iOS/Facades/System.Xml.XmlSerializer.dll'. Remove one of the duplicate references. (CS1703) ({my test library})

**Comment by jfversluis** [comment]
I'm sorry this is happening @thales-man! From which version did you upgrade? Did you remove the bin and obj folders from the filesystem and did a full rebuild?

I see [this older issue](https://github.com/xamarin/Xamarin.Forms/issues/1380) that somewhat describes the same issue, maybe that gives you a hint as to what is going on.

**Comment by thales-man** [comment]
Hi
Sorry, I don’t know which version I upgraded from; otherwise i would have put it in the initial info. I appreciate it’s somewhat remiss of me; but I know of expect these things to work so i don’t tend to keep track. I really should know better now.

Also, what exactly would be the relevance of knowing? I created a brand new project and step by step integrated it into the solution and it failed. This is listed as an addition comment.

Colin :)

**Comment by PureWeen** [comment]
@thales-man 

Can you zip up the project you are creating here
```
further to this:
created a new IOS project to solution => build ok
added net standard 2 project to IOS project = > build ok
added Xamarin forms to IOS project in solution = > boom!
```

I tested this on VS Mac 8.5 and it worked fine for me..

Maybe something got messed up with your install? 

You can try uninstalling everything completely and reinstalling
https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019

Which might fix?

**Comment by thales-man** [comment]
hi shane, 

thanks for the offer of assistance; but it is not installation issues. this environment is in use many hours of the day building a range of dot net core and net standard projects deployed to azure and aws platforms.
 
update:
ran updater on MS for Mac version now 8.5.3183
updated Xamarin forms packs to 4.5.0.495

hacked the android project and removed 32 'duplicated' net standard 2 library references
no actual codes changes made at all.

errors reduced from 212 to 2.

the remaining errors are on a 'modern' macOS project and these are build cyclic errors concerning the location of the 'hash set'. see below:

/Users/{blah user}/Projects/{blah component path}.cs(33,33): Error CS0731: The type forwarder for type 'System.Collections.Generic.HashSet`1' in assembly 'netstandard' causes a cycle (CS0731) ({blah})

if I unload this project and remove it from the nu-get project, the solution builds. however I have had several build failures around the nu-get project itself, when it moans about net standard 1.5 projects (or higher) not being compatible with framework 4.8. these are intermittent and are clearly more build issues.

now this is using a number of projects I wanted to deploy in a pack, directly in this solution. if I remove those projects and refer to the pack built out of those same projects a solution build issues 192 build errors similar to those registered in the initial bug. so there is clearly an issue with package references, and build dependencies. it is possible that the whole list is caused by this 'cyclic' reference issue in the macOS part of the nu-get pack; if I get more time I'll try removing it and conducting a test build using a pack with it missing.

the file lock and duplicate processes running error during android builds has gone (yay!)

Colin :)

**Comment by PureWeen** [comment]
@thales-man without a repro it's a little hard to help or guide

From your descriptions the best I can figure is that there are conflicting types and possibly old things just left over

i.e.

> hacked the android project and removed 32 'duplicated' net standard 2 library references

I've tested new projects with the steps you've given and they all work fine for me. 


> /Users/{blah user}/Projects/{blah component path}.cs(33,33): Error CS0731: The type forwarder for type 'System.Collections.Generic.HashSet`1' in assembly 'netstandard' causes a cycle (CS0731) ({blah})

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0731

Makes it sound like there are competing metadata elements or an old one that's influencing new bits

**Comment by thales-man** [comment]
This is not something you can fix, it’s to do with linking, binding and package referencing which is Visual studio now and not specifically Xamarin; it’s just that’s it’s always Xamarin that breaks. So the teams probably should get together and chat about it...
