### ISSUE TITLE
[Bug] Custom Font for displaying font icon no effect on iOS Platforms

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#10052]
The preview feature displaying font icon sample here:
[SampleApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4367020/SampleApp.zip)
1.Run the sample to deploy to android device → Normal
2.Run the sample to deploy to iOS device → No effect

The traditional normal displaying font icon sample here:
https://github.com/jingliancui/XamarinFormsFontAwesomeSample

**Comment by PureWeen** [comment]
This should be fixed with an upcoming release

https://github.com/xamarin/Xamarin.Forms/pull/9194
