### ISSUE TITLE
[Bug] Animation broken again in Android. Possibly related to #7291

### ISSUE THREAD

**Issue by mdbill** [xamarin/Xamarin.Forms#10061]
### Description

Similar to #7291, I'm translating and rotating a button and it's becomes partially obscured.  Unlike before where the bug made it so nothing showed.
It's hard to explain. but works fine up until 4.4.0.001477

### Basic Information

- Versions with issue: 4.4.0.991477 thru 4.5.xxxx
- Last known good version: 4.4.0.991265
- IDE:
- Platform Target Frameworks: 
  - iOS:  didn't try this
  - Android: 28.0.03 and 
  - UWP:  works fine

**Comment by hartez** [comment]
@mdbill Are you seeing the problem described in #9802?

**Comment by mdbill** [comment]
> @mdbill Are you seeing the problem described in #9802?

Looks like the same problem.

**Comment by mdbill** [comment]
Still broken in 4.5.0.495

**Comment by PureWeen** [comment]
Closing as duplicate
Marked other issue as regression
