### ISSUE TITLE
[Bug] Binding to StreamImageSource doesn't work

### ISSUE THREAD

**Issue by SymxnCreator** [xamarin/Xamarin.Forms#10062]
### Description

Hi there,

There is an error with the StreamImageSource.

The following scenario exists:
In XAML there is an image control. Its source property binds to a property in the ViewModel of type ImageSource.

We then create another ImageSource variable, name it streamImage, for example, and assign it a image using the FromStream method.

If we now assign the streamImage variable to the property in the ViewModel, the binding does not work. No picture is shown.

XAML:

        <Image Grid.Row="0"
                Source="{Binding Image, Mode=OneWay}"
                Aspect="AspectFill"></Image>

ViewModel:

        private ImageSource _image;

        public ImageSource Image
        {
            get { return _image; }
            set { SetProperty(ref _image, value); }
        }

        public ViewModel()
        {
            ImageSource streamImage = ImageSource.FromStream(() =>
            {
                // Before returning you must convert a image to stream
                return streamOfImage;
            });

            // The allocation works but no image is displayed
            Image = streamImage;
        }

This error only occurs with StreamImageSource.

### Steps to Reproduce

1. Create a page with a Image control inside.
2. Bind the Source property of the image to an property in ViewModel.
3. Create a ViewModel.
4. Create a ImageSource variable an set it's source with the FromStream method.
5. Assign the variable to the property in the ViewModel.
6. Run the app.

### Expected Behavior

The image is displayed.

### Actual Behavior

The image isn't displayed.

### Basic Information

- Version with issue: 4.5
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@SymxnCreator can you attach a repro? I tested this locally and it works fine for me

There's a bug in older versions of 4.5 so possibly this is fixed for you if you try 4.6? or the latest 4.5?

**Comment by SymxnCreator** [comment]
Hello,

I have now installed a higher 4.5 version and now it works.
I don't know if it was my fault, if the early 4.5 version had a bug or if it was something else.

If you hadn't contacted me, I wouldn't have tried it again.
Thank you so much!
