### ISSUE TITLE
[Bug] Navigation.RemovePage loses context

### ISSUE THREAD

**Issue by lsaudon** [xamarin/Xamarin.Forms#10076]
### Description

When remove all page except one or two. View loses context.

### Steps to Reproduce

1. Push pages
2. Remove all pages except one

```csharp
for (int i = NavigationStack.Count - 1; i > 0; i--)
{
    Navigation.RemovePage(NavigationStack[i]);
}
```

### Expected Behavior

![Screenshot_1585072220](https://user-images.githubusercontent.com/25029876/77459679-61e9f780-6e00-11ea-9df1-54b1116c88d1.png)

### Actual Behavior

![Screenshot_1585072248](https://user-images.githubusercontent.com/25029876/77459713-6e6e5000-6e00-11ea-867c-ed75084cf8e7.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS: Not tried 
  - Android: API 28  
  - UWP: Not tried   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.5.0.396
- Affected Devices: Tried on emulator Nexus 5x

### Screenshots

See Expected Behavior and Actual Behavior

### Reproduction Link
https://github.com/PureWeen/Xamarin.Forms.Sandbox/tree/issue_10076

**Comment by lsaudon** [comment]
An ugly solution.
```csharp
for (int i = NavigationStack.Count - 2; i > 0; i--)
{
    Navigation.RemovePage(NavigationStack[i]);
}
Navigation.RemovePage(NavigationStack[NavigationStack.Count - 1]);
```

**Comment by PureWeen** [comment]
breaks shell and navigationpage
