### ISSUE TITLE
[Bug] SVG image is not loading in Tabbed Page Tab bar 

### ISSUE THREAD

**Issue by dinesh4official** [xamarin/Xamarin.Forms#10071]
Hi Team,

Hope everyone is well and safe at home !!!

### Description

I am trying to load the SVG image in Tabbedpage tab icon in bottom bar placement. But it is not rendering in View. I have tried in both top and bottom bar view but no result. 

Additionally, I have also tried in custom tabbed page renderer as per below Xamarin guidelines using GetIconDrawable and still no positive result.

https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page

### Code Snippet
` <TabbedPage.Children>
        <views:ItemsPage IconImageSource="actionimagebutton.svg">
        </views:ItemsPage>
        <views:AboutPage >
            <views:AboutPage.IconImageSource>
                <FileImageSource File="xamarin_logo.png">
                </FileImageSource>
            </views:AboutPage.IconImageSource>
        </views:AboutPage>
    </TabbedPage.Children>`

### Steps to Reproduce

1. Run the attached sample in Android platform.
2. See the SVG image is not loaded for the first tab. (issue)

### Expected Behavior

- Should render the SVG image as per the guidelines. 

### Actual Behavior

- SVG image is not rendering in View.

- Version with issue: Xamarin Forms v4.0 to latest v4.5.0.396
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - Android: All version  

### Screenshots

![TabSVG](https://user-images.githubusercontent.com/57437264/77433294-39183100-6e05-11ea-8805-e1342a436d7b.png)

### Reproduction Link

[SVGTab.zip](https://github.com/xamarin/Xamarin.Forms/files/4375588/SVGTab.zip)

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/8078
