### ISSUE TITLE
Can't access AppInfo.RequestedTheme

### ISSUE THREAD

**Issue by breitburg** [xamarin/Xamarin.Forms#10088]
I followed [this](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/dark-mode) documentation, but the exception appeared on both Android and iOS.

![](https://i.imgur.com/GzSIT2P.png)

`ApplyTheme` code:

```csharp
public static void ApplyTheme()
{
  if (AppInfo.RequestedTheme == AppTheme.Dark)
    App.Current.Resources = new LightTheme();
  else
    App.Current.Resources = new DarkTheme();
}
```

**Comment by PureWeen** [comment]
@breitburg 

Log essentials bugs here
https://github.com/xamarin/Essentials

also that type of error comes up when you have nugets out of sync

- make sure all your essentials/xf libraries are the same version
- delete obj/bin directories
- try again

if still seeing the issue post over in Essentials
