### ISSUE TITLE
[Bug] SwipeView.RightItems Label is Missing/Hidden Due to Bad Alignment

### ISSUE THREAD

**Issue by arunr14** [xamarin/Xamarin.Forms#10086]
### Description
On Forms 4.6 pre 1 , when using a SwipeView.RighItems in mode "Execute", the "Text" field is pushed all the way to the left and becomes hidden until the very end of the swipe.
### Steps to Reproduce

1. Use a swipe view inside a list view 

2.
```
<ListView IsVisible="{Binding IsLoading, Converter={StaticResource InvertBool}}" HorizontalOptions="FillAndExpand"
			ItemsSource="{Binding GroupedHomogeneousThingsCollections}"  SelectedItem="{Binding SelectedHomogeneousThingsCollection, Mode=TwoWay}" ItemSelected="OnItemSelectedOrDeselected"
			HasUnevenRows="true" IsGroupingEnabled="true" GroupDisplayBinding="{Binding Key}"
			IsPullToRefreshEnabled="True" RefreshCommand="{Binding RefreshCommand}" IsRefreshing="{Binding IsRefreshing, Mode=TwoWay}">
            <ListView.GroupHeaderTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Padding="10,10,10,10" HorizontalOptions="FillAndExpand" BackgroundColor="{DynamicResource ChaldalOrange}">
                            <Label Style="{DynamicResource MediumAndBoldLabelStyle}" Text="{Binding Key}" HorizontalOptions="CenterAndExpand" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.GroupHeaderTemplate>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <SwipeView>
                            <SwipeView.LeftItems>
                                <SwipeItems Mode="Execute" SwipeBehaviorOnInvoked="Close">
                                    <SwipeItem Text="Report All Picked"
                                               BackgroundColor="Green"
                                               Invoked="AllPicked_Invoked"
                                               CommandParameter="{Binding .}"/>
                                </SwipeItems>
                            </SwipeView.LeftItems>
                            <SwipeView.RightItems>
                                <SwipeItems Mode="Execute" SwipeBehaviorOnInvoked="Close">
                                    <SwipeItem Text="Report All Missing"
                                               BackgroundColor="Red"
                                               Invoked="AllPicked_Invoked"
                                               CommandParameter="{Binding .}"/>
                                </SwipeItems>
                            </SwipeView.RightItems>
                            <StackLayout Padding="10,10,10,5" Spacing="5" Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                                <StackLayout HorizontalOptions="Start" WidthRequest="50">
                                    <Label VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand" Style="{DynamicResource LargeAndBoldLabelStyle}" Text="{Binding Things.Count}"/>
                                </StackLayout>
                                <Image HeightRequest="50" WidthRequest="50" Source="{Binding ProductVariant.ImageUrl}"/>
                                <StackLayout HorizontalOptions="StartAndExpand" WidthRequest="180">
                                    <Label Text="{Binding ProductVariant.Name}" Style="{DynamicResource SmallLabelStyle}" VerticalOptions="Fill"/>
                                    <Label Text="{Binding Location}" Style="{DynamicResource MediumAndBoldLabelStyle}" VerticalOptions="Start"/>
                                </StackLayout>
                                <StackLayout HorizontalOptions="EndAndExpand" WidthRequest="60">
                                    <Label Style="{DynamicResource SmallGrayedLabelStyle}" HorizontalTextAlignment="Center" Text="{Binding ProductVariant.ProductVariantId, StringFormat=PV ID:&#x0a;\{0\}}" HorizontalOptions="CenterAndExpand"/>
                                    <Label Style="{DynamicResource LargeTappableLabelStyle}" Text="" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand"/>
                                </StackLayout>
                            </StackLayout>
                        </SwipeView>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

3. 

### Expected Behavior
The text for SwipeItems.Leftview is displayed in the correct location, and I expect a similar behaviour for SwipeItems.RightView where the text/label is visible as soon as your start swiping

![Screenshot_20200325-123450](https://user-images.githubusercontent.com/8968047/77578701-3dd8f580-6e96-11ea-85be-31ff83a1b97a.png)

### Actual Behavior
![Screenshot_20200325-123512](https://user-images.githubusercontent.com/8968047/77578706-40d3e600-6e96-11ea-86de-a8b8a3663cc1.png)

### Basic Information

- Version with issue: 4.6.0.379-pre1
- Last known good version: 4.5 
- IDE: Visual Studio 2019 (16.4.5)
- Platform Target Frameworks: 
  - Android:  Android 9.0 Api level 28

- Affected Devices: Pixel 3

**Comment by jsuarezruiz** [comment]
Currently, the SwipeItem size is different based on the Mode.
- Reveal: A default width is applied to the SwipeItem, and in the case of SwipeItemView the same happens unless a WidthRequest is set.
- Execute: The width of the SwipeItem is the width of the SwipeView. If there are multiple elements, each element takes the proportional width.

Example:
![issue10086](https://user-images.githubusercontent.com/6755973/77738008-5a4c6d80-700f-11ea-823e-2166f68d7ba8.gif)

This example uses transparency in the content of the SwipeView to get a better view of everything.

In the case of Reveal, the command is executed if swipe more than 60% of the width of the SwipeItem.

Would you like to have the same size in both modes?

**Comment by arunr14** [comment]
> In the case of Reveal, the command is executed if swipe more than 60% of the width of the SwipeItem.

Sorry , I am confused here , I thought in "Reveal" I would have to tap on the text after it is revealed for it to execute? 

> Would you like to have the same size in both modes?
Intuitively I expect to see the text as soon as I start swiping so I know what action I am performing. 
 
Also it seems this behavior changed between 4.5 and 4.6 ?

**Comment by Seuleuzeuh** [comment]
I'm facing the same "issue". I'm using the Execute mode and with a small text you don't understand what the action does until a long swipe. 
What i was expected : 
- container take all the space (ie like the actual behavior) for settings the background color (in the your example @jsuarezruiz red color)
- the content (ie text & icon) align to the corresponding collection filled (RightItems => Right, LeftItems => Left, etc...)

Maybe with a "ContentAligment" property ?

**Comment by jsuarezruiz** [comment]
@arunr14 I sent a PR https://github.com/xamarin/Xamarin.Forms/pull/12735 adding a sample using the Threshold property to modify the SwipeView behavior. Could you take a look to the sample?, solve your issue?.
