### ISSUE TITLE
[Enhancement] VisualState Actions 

### ISSUE THREAD

**Issue by Glabenwitt** [xamarin/Xamarin.Forms#10087]
## Summary
Add the ability to exectute actions when a VisualState is applied. (Similar to EventTrigger but for VisualState)

## API Changes

I think of adding a list of actions on the VisualState class in order to execute them when a state is applied.
In the same way than EventTrigger, it can be either a SealedList of TriggerAction.

Here is a example of what i'm thinking :
```xaml
<Style TargetType="Entry">
    <Setter Property="BackgroundColor" Value="White" />
    <Setter Property="VisualStateManager.VisualStateGroups">
        <VisualStateGroup x:Name="ValidState">
            <VisualState x:Name="Invalid">
                <VisualState.Setters>
                    <Setter Property="BackgroundColor" Value="Red" />
                </VisualState.Setters>
                <VisualState.Actions>
                    <animations:ShakeAnimationAction />
                </VisualState.Actions>
            </VisualState>
        </VisualStateGroup>
    </Setter>
</Style>
```

I was thinking of a new class for actions like VisualStateAction but it break compatibility with existing actions created for triggers.

## Intended Use Case
I had this idea when I wanted to trigger an animation when a state changed.

**Comment by hartez** [comment]
> I had this idea when I wanted to trigger an animation when a state changed.

We actually have a spec open specifically for storyboard animations on a visual state change: https://github.com/xamarin/Xamarin.Forms/issues/4233

**Comment by PureWeen** [comment]
Closing this now in favor of Storyboard Animations
