### ISSUE TITLE
[Bug] Cannot pair and build project from MacOS to Visual Studio WIndows after upgrade MacOS

### ISSUE THREAD

**Issue by KSYMEK** [xamarin/Xamarin.Forms#10080]
After upgrade MacOS Catalina from version 10.15.3 to 10.15.4 on Macbook Pro 2018, I cannot pair my PC (Windows 1909) to previously mentioned Macbook. Issue can be also related to the newest version of XCode but I am not sure. After that I tried to update Xamarin from Visual Studio on my PC to latest version and I also tried doing it on my Mac.

Error: Xamarin.Messaging.Integration.State.ServerStateContext|Error|0|An error occurred while trying to start the Broker...

**Comment by hartez** [comment]
After updating to the newest XCode, did you open XCode? Sometimes you have to run it once so it can install additional components.

**Comment by KSYMEK** [comment]
Yes I tried it, I forgot to mention it.

**Comment by SpongeDude** [comment]
Same issue here : /

**Comment by haavamoa** [comment]
Have you tried upgrading VS today?

I notice a pair to mac issue resolved in the latest VS. 
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.5.1

**Comment by adamswallows** [comment]
Same issue after upgrading to MacOS Catalina - 10.15.4 and Xcode 11.4.

Opened Xcode and when prompted, installed the necessary components.

VS Professional 16.5.1 is unable to pair.

**Comment by haavamoa** [comment]
Maybe leaving a comment in that last link can help you out? I mean they claim to have solved it.

**Comment by mauroa** [comment]
Hi everyone. 
From macOS 10.15.4, there was an update on OpenSSH which is breaking our SSH layer, so we crash when trying to copy the Mac Agent files over SCP to the Mac. That causes the connection to never complete.
We've already fixed it and the fix will be available on the next VS 16.6 P2 and also on the next 16.5 Service Release.
I'm closing this issue since it's fixed and pending to be released.
Thanks.

**Comment by solomonfried** [comment]
Is there a schedule as to when VS 16.5 with this fix will be released?

**Comment by thomasgalliker** [comment]
@mauroa this sounds promising, thanks. Do you already know in which VS release the fix will be available? I can't find it on the release notes of 16.6 P2 nor is there any 16.5 service release announced. I'm on VS 16.5.1 and would do everything to get the dev team rolling again...
