### ISSUE TITLE
[Bug] Android build has issues on android emulator after updating to vs 16.5.0

### ISSUE THREAD

**Issue by akatsukle** [xamarin/Xamarin.Forms#10082]
### Description

Since updating to vs 16.5.0, running on the emulator no longer works correctly. 
The SynchronizationContext apparently sometimes enters in a deadlock state. 
In my case the issue occurs about 90% of the time.
This only happens during the first call to Navigation.PushAsync. If this call returns then, every subsequent call will work as expected.

I could not reproduce this issue on a fresh project.
I could not reproduce this issue when running on a real device.

Edit: this also happens on real device although it is very uncommon.

### Steps to Reproduce

On a page executing the following code does not work as expected:
```C#
if (Thread.CurrentThread.ManagedThreadId != 1)
    throw new InvalidOperationException();

Globals.Logger.Debug("I can log"); // this works
await Task.Delay(100); // this also works

try
{
    Task navigationTask = Navigation.PushAsync(new AccountManagementPage(new AccountManagementMainViewModel()));
    Task delayTask = Task.Delay(3000);
    if (await Task.WhenAny(navigationTask, delayTask) == delayTask)
    {
        // this is never executed
        Globals.Logger.Debug("NavigationUtils.Navigate has failed");
        return;
    }

    // this is never executed either
    Globals.Logger.Debug("NavigationUtils.Navigate has completed");
}
catch (Exception e)
{
    // this is never executed either
    Globals.Logger.Debug($"Something has gone very wrong: {e}");
}
finally
{
    // this is never executed either
    Globals.Logger.Debug($"NavigationUtils.Navigate Finally");
}
```

The log never shows up, breakpoints are never hit.

### Expected Behavior

The await calls returns and the page changes.

### Actual Behavior

The await calls never returns and the page never changes.

### Basic Information

- Version with issue: vs 16.5
- Last known good version: vs 16.4
- IDE: vs 16.5.0
- Affected Devices: Android Emulator
- OS: Windows 10 without hyper-V

I am sorry for the sloppy bug report, I am aware that this is probably not enough to pinpoint the issue. I am opening so that others can also contribute to this issue should they have similar issues.
I can execute test code, provide logs or more information as requested.
I will keep this updated if I have more information.

**Comment by akatsukle** [comment]
A quick update:
The issue also manifests on a real device, although very rarely.
I didn't have any issue yet with a release build.

**Comment by PureWeen** [comment]
@akatsukle this is a tricky one

I tested your basic code in a repro and it works for me... If I were to venture a guess I would guess that something here

```
Navigation.PushAsync(new AccountManagementPage(new AccountManagementMainViewModel()));
```

is locking the UI thread? Something in that VM or that Page? 

if you change that to just a ContentPage does it work?

If you click PAUSE on the debugger can you see what the threads are doing?

**Comment by akatsukle** [comment]
I replaced 
```
Navigation.PushAsync(new AccountManagementPage(new AccountManagementMainViewModel()));
```
by 
```
ContentPage page = new AccountManagementPage(new AccountManagementMainViewModel());
Globals.Logger.Debug("Page was succesfully constructed"); // this works
Navigation.PushAsync(page);
```
and the failing call is still the PushAsync.

> is locking the UI thread? Something in that VM or that Page?
Not to my knowledge, but I might of course be missing something.

> if you change that to just a ContentPage does it work?
> If you click PAUSE on the debugger can you see what the threads are doing?
Thank you for the suggestions. It actually seems that my issue is related to FFImageLoading.
Something as simple as 
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:ff="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="MyNs.TestPage">
    <ScrollView>
        <StackLayout>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon1.png" DownsampleHeight="120" VerticalOptions="Center"/>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon2.png" DownsampleHeight="120" VerticalOptions="Center"/>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon3.png" DownsampleHeight="120" VerticalOptions="Center"/>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon4.png" DownsampleHeight="120" VerticalOptions="Center"/>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon5.png" DownsampleHeight="120" VerticalOptions="Center"/>
            <ff:CachedImage WidthRequest="40" HeightRequest="40" Aspect="AspectFit" Source="icon6.png" DownsampleHeight="120" VerticalOptions="Center"/>
        </StackLayout>
    </ScrollView>
</ContentPage>
```
fails more than half of the time.

While I still believe this issue is due to the vs update, I guess that since not directly linked to Xamarin.Forms, this issue can be closed.
For the record here is where the thread is usually blocking:
![image](https://user-images.githubusercontent.com/8066261/77600257-ada8b800-6f4a-11ea-87a4-ba2f40c19cca.png)

**Comment by PureWeen** [comment]
What I meant was to replace the call with 

```
Navigation.PushAsync(new ContentPage);
```

And see if that fixes it.

I'd open up an issue with FFImageLoading and we can see what they think

**Comment by akatsukle** [comment]
Thank you for your time.

> What I meant was to replace the call with `Navigation.PushAsync(new ContentPage);`

Yes this is what I did, and that does indeed fixes it.
When the content page contains `ff:CachedImage` it doesn't work anymore though and the thread is stuck in the following part of the code:

```
if (stream == null)
	return null;

var lengthSupported = true;

try
{
	var length = stream.Length; // << here
}
catch (NotSupportedException)
{
	lengthSupported = false;
}
```

I will crosspost on FFImageLoading.

**Comment by akatsukle** [comment]
It appears that the solution in the end, was not to delete the bin/obj folders, but the .vs folder in the solution...or at least that is the only thing in what I tried that makes sense.
