### ISSUE TITLE
[Bug] CollectionView Header, EmptyView And GridItemsLayout

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#10085]
Description
When I use a CollectionView with Header and EmptyView with GridItemsLayout, 
the design looks bad, I think GridItemsLayout should only affect ItemTemplate and not the CollectionView object.

Steps to Reproduce

```
<CollectionView ItemsSource="{Binding lists}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" Span="3" />
                </CollectionView.ItemsLayout>
      <CollectionView.EmptyView>
                    <StackLayout>
                        <Label Text="No data!"
                       Margin="10,25,10,10"
                       FontAttributes="Bold"
                       FontSize="18"
                       HorizontalOptions="Fill"
                       HorizontalTextAlignment="Center" />
                    </StackLayout>
                </CollectionView.EmptyView>
    <CollectionView.Header>
        <StackLayout>
            <Label Text="Header"
                FontSize="Medium"
                HorizontalOptions="Center"/>
        </StackLayout>
    </CollectionView.Header>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Label Text="{Binding .}"/>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

Expected Behavior
GridItemsLayout should not affect Header, EmptyView or Footer, only ItemTemplate.

Actual Behavior
GridItemsLayout affect Header, EmptyView, Footer and ItemTemplate.

Basic Information
Version with issue: vs 16.5
IDE: vs 16.5.0
Affected Devices: Android Emulator
OS: Windows 10 without hyper-V

if we remove GridItemsLayout everything works fine

**Comment by hartez** [comment]
@angelru Can you post some screenshots so we can see the layout you are getting?

**Comment by angelru** [comment]
With GridItemsLayout:
![Sin título](https://user-images.githubusercontent.com/11645585/77646529-ff5e3c00-6f64-11ea-8363-617c4fcbd3c6.png)

Without GridItemsLayout
![Sin título1](https://user-images.githubusercontent.com/11645585/77646574-13a23900-6f65-11ea-81e7-71485c64567e.png)

GridItemsLayout should not affect Header, EmptyView or Footer, only ItemTemplate.

@hartez @PureWeen

**Comment by jsuarezruiz** [comment]
Attached repro sample.
[Issue10085.zip](https://github.com/xamarin/Xamarin.Forms/files/4503848/Issue10085.zip)

![cv-layout-issue-small](https://user-images.githubusercontent.com/6755973/79759359-e146ea00-831e-11ea-8ea1-6449de14aeb4.gif)

**Comment by angelru** [comment]
Any updates?

**Comment by angelru** [comment]
ping

**Comment by Colinkl** [comment]
Any workaround is available?
