### ISSUE TITLE
[Enhancement] Notch mode on Xamarin Forms!

### ISSUE THREAD

**Issue by felipebaltazar** [xamarin/Xamarin.Forms#10090]
## Summary
Since Android and IOS has a notch space and works with some "safe area", Xamarin forms can provide it for use it at the page level

## API Changes

NochMode Page.NotchMode { get; set; } //Bindable Property

The NotchMode API will change native notch space behavior

## Intended Use Case
Unify the notch configuration for android and IOS

**Comment by felipebaltazar** [comment]
I've created a PR with this suggestion:

https://github.com/xamarin/Xamarin.Forms/pull/10047

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
