### ISSUE TITLE
[Bug] Button wrong calculates size on Android in 4.5.0.495

### ISSUE THREAD

**Issue by PetrVobornik** [xamarin/Xamarin.Forms#10102]
### Description
Button wrong calculates size (horizontal and vertical too) by his Text on Android when I change FontSize to Medium in version 4.5.0.495. In previous version 4.5.0.396 it works fine. No other changes in XAML and code behind are here, only XF update.

Tested on Android 10.0 (API 29) emulator.

![image](https://user-images.githubusercontent.com/11021768/77684448-4ca8d080-6f9a-11ea-8953-f86d897d0d2d.png)

**Comment by PureWeen** [comment]
@PetrVobornik can you attach a repro please?

**Comment by hemawst** [comment]
I have a very similar problem. I have a content page with a control template. In the template there are buttons with static resource styles. In version 4.5.0.396 everything works great, but in version 4.5.0.495 the size of the buttons is calculated incorrectly. All text content of the buttons are cut off. All horizontal options do not work, only when I set the property widthrequest does the size of the buttons change

**Comment by PetrVobornik** [comment]
Code of the page from the screen is following. I change only version of XF several times back and forth with the same effect: 4.5.0.396 is OK, 4.5.0.495 buttons are bad. Not only here, but in whole application, where I change FontSize.

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:local="clr-namespace:Pocty"
                 x:Class="Pocty.MainPage"
                 xmlns:tra="clr-namespace:Pocty;assembly=Pocty"
                 Title="{tra:ResEx Text=MainPage_Title}">

        <Grid>
            <Image Source="back.jpg" HorizontalOptions="Fill" VerticalOptions="Fill" Aspect="AspectFill" Opacity="0.5" />
            <ScrollView>
                <Grid>
                    <StackLayout HorizontalOptions="Center" VerticalOptions="Center" Spacing="15">
                        <Image Source="icon_main.png" WidthRequest="64" HeightRequest="64" Aspect="AspectFit" />
                        <Button x:Name="btnStart" Clicked="BtnStart_Clicked" Text="{tra:ResEx Text=MainPage_btnStart}" BackgroundColor="#4CAF50" FontSize="Medium" CornerRadius="5" TextColor="White" BorderWidth="1" BorderColor="#265728" Padding="10,5" />
                        <Button x:Name="btnSettings" Clicked="BtnSettings_Clicked" Text="{tra:ResEx Text=MainPage_btnSettings}" BackgroundColor="#428BCA" FontSize="Medium" CornerRadius="5" TextColor="White" BorderWidth="1" BorderColor="#214565" Padding="10,5" />
                        <Button x:Name="btnLoad" Clicked="BtnLoad_Clicked" Text="{tra:ResEx Text=MainPage_btnLoad}" BackgroundColor="#FF5722" FontSize="Medium" CornerRadius="5" TextColor="White" BorderWidth="1" BorderColor="#7F2B11" Padding="10,5" />
                        <Button x:Name="btnAbout" Clicked="BtnAbout_Clicked" Text="{tra:ResEx Text=MainPage_btnAbout}" BackgroundColor="#673AB7" FontSize="Medium" CornerRadius="5" TextColor="White" BorderWidth="1" BorderColor="#331D5B" Padding="10,5" />
                    </StackLayout>
                </Grid>
            </ScrollView>
        </Grid>
    </ContentPage>

**Comment by pmahend1** [comment]
@PetrVobornik Does it happen when you remove `ScrollView` as well?
I am also seeing weird issues when ScrollView is used. #10104

**Comment by PureWeen** [comment]
Here's a screen shoft of the xaml on 396 vs 495

If someone can provide a repro that would be helpful

![image](https://user-images.githubusercontent.com/5375137/77801659-e1fda080-703e-11ea-893b-09dc94cc242c.png)

**Comment by PetrVobornik** [comment]
Its on Android 10.0?

**Comment by PureWeen** [comment]
@PetrVobornik yea I tested on an API 29 emulator and building with API 29


If you have a repro you could attach that would be helpful. The layouts with android buttons can be a bit quirky and super situational specific

**Comment by PetrVobornik** [comment]
I tried it on the new blank project and it works fine. Then I tried other project differences and the buttons change its sizes to wrong when I add NavigationPage to the App class.

    MainPage = new NavigationPage(new MainPage());

I'm attaching this new project where are wrong buttons:
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4397872/App1.zip)

**Comment by PetrVobornik** [comment]
And here is configuration of my emulator if it's relevant:
![image](https://user-images.githubusercontent.com/11021768/77833922-26716500-7141-11ea-8b2c-6b4683bdab3b.png)

**Comment by hemawst** [comment]
In my case it makes no difference whether I use a navigation page or not and removing the scroll pane has no effect. Simply setting Setter Property = "WidthRequest" Value = "xxx" changes the size of the buttons. (Android versions: Emulator 7.1, manifest target version 8.1, project target version 9.0)

**Comment by PetrVobornik** [comment]
Buttons looks identical when I remove the ScrollView. But when SW is here, then I see after launch a scroll bar on buttons with wrong wrapping for a few seconds. Yes, I can set WidthRequest, but I'm using localization and texts are variouselly long. And on UWP are another sizes too. This is not all bad buttons in my app. And the height is wrong calculated too.

**Comment by hemawst** [comment]
I saw this morning that there is a new version 4.5.0.530. I tried this version and now the problem with the display of the buttons seems to be solved at first glance.
Version 4.5.0.530 has a new problem for this. I get a new one
Error message: Navigation.PushAsync (new Page1 ()). The message is "System.InvalidOperationException: PushAsync is not supported globally on Android, please use a NavigationPage. at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.INavigation.PushAsync"

I changed the code in the App.xaml.cs.
MainPage = new MainPage ();
to
MainPage = new NavigationPage (new MainPage ());
Then the error is gone, but the problem with the representation of the buttons occurs again now.

**Comment by PetrVobornik** [comment]
I tried the new version 4.5.0.530 but the problem with buttons persists.
Did you manage to simulate it with the uploaded project?

**Comment by hemawst** [comment]
No, I've only tried my own project so far. But as I said, with the new version 4.5.0.530 I still have the problem with the buttons after I have removed the new error message.

I am only surprised that we are apparently the only ones who have this button problem with existing projects.

**Comment by nwilliams** [comment]
> 
> 
> No, I've only tried my own project so far. But as I said, with the new version 4.5.0.530 I still have the problem with the buttons after I have removed the new error message.
> 
> I am only surprised that we are apparently the only ones who have this button problem with existing projects.

You are not alone -- I'm seeing this behavior as well. I've rolled back to 4.5.0.396 for the time being since I'm also using localized text for all of my buttons and cannot use a fixed width.

One thing I did notice during my testing is that if you have an ImageSource set on the button, the width is correctly calculated. Not a good solution, but may be an acceptable workaround for some people.

**Comment by vincentcastagna** [comment]
Hello.

Same issue here after upgrading to latest. 

No prob at all for buttons that lives in a simple layout (one stacklayout) but when the layout is more complex, like nested stacklayouts inside a parent grid, button size calculation is as shown on the screenshot of this issue.  

One interessting thing is that when refreshing the page with HotReload, the calculation seems good.

**Comment by frarteaga** [comment]
Same issue with 4.5.0.530. 
![imagen](https://user-images.githubusercontent.com/18072082/78986899-60a41480-7afa-11ea-8752-b5746c3cce45.png)
Also using localized strings.
Should look like this: 
![imagen](https://user-images.githubusercontent.com/18072082/78987125-17a09000-7afb-11ea-99c8-0c3ee84813f3.png)

**Comment by frarteaga** [comment]
I just tried with the new version 4.5.0.617 and the issue remains.

**Comment by vincentcastagna** [comment]
Best workaround today for me was to use LegacyRenderers which solve the prob in my entire app :             

`Forms.SetFlags("UseLegacyRenderers");`

**Comment by nwilliams** [comment]
> 
> 
> Best workaround today for me was to use LegacyRenderers which solve the prob in my entire app :
> 
> `Forms.SetFlags("UseLegacyRenderers");`

Unfortunately, this doesn't work with the Material visual.

Hopefully we'll get a proper fix soon.
