### ISSUE TITLE
[Bug] ITMS-90809: Deprecated API 

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#10105]
Compiling with the latest Visual Studio for Mac and Xamarin.iOS Version still results in Deprecated API use. I do not use the UIWebView in my code and my only external libraries are Xamarin.Forms and Xamarin.Essentials. 

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

Because we cannot update our apps anymore with this from April, it is absolut neccessary that this gets fixed - espacially because we already have this for years again...

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/9823
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
