### ISSUE TITLE
[Bug] Entry control kills app when HOME is pressed

### ISSUE THREAD

**Issue by mjfreelancing** [xamarin/Xamarin.Forms#10106]
### Description
I don't know if this issue is an emulator issue, or XF issue. I only have Android so cannot eliminate variables. The sample app provided has a blank page with an Entry control. When the control has focus and the HOME key is pressed the application silently disappears. No error / exception is provided.

### Steps to Reproduce

1. Click an Entry control so it receives focus
2. Press the HOME key
3. The application silently disappears (in the emulator at least)

### Expected Behavior
The application should not disappear

### Actual Behavior
The application disappears

### Basic Information
A long mouse press selects the text and behaves as expected. I'm unable to determine if this is an emulator issue, so reporting for further investigation.

- Version with issue: I tested 4.4.0.991265 and 4.5.0.495 only
- Last known good version: Unknown
- IDE: VS 2019 Windows
- Platform Target Frameworks: 
  - Android:  
- Affected Devices: Android Emulator (Pixel 3XL Pie 9.0 API 28)

### Reproduction Link
[EntryCrashesApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4393979/EntryCrashesApp.zip)

### Workaround
Don't press the HOME key

**Comment by PureWeen** [comment]
@mjfreelancing can you make a GIF

I'm not really following the issue

**Comment by mjfreelancing** [comment]
Hmmm, insert emabarssment emoji here. I only just discovered the HOME key is a keyboard shortcut on the android emulator to send the app to the background.

My original issue occurred when I wanted to delete all text in an Entry control so I SHIFT+HOME and the app disappeared. I mistakenly thought this was a crash.
