### ISSUE TITLE
[Bug] On iOS "Done" text in Editor is not translated

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#10107]
![Screenshot 2020-03-27 at 16 04 19](https://user-images.githubusercontent.com/17653648/77770275-4885bd00-7045-11ea-8722-937af9a3c39e.png)

As you can see there is a "Done" text even though the language on my iPhone is set to German.

### Steps to Reproduce

1. Run this project on iOS
[IosEntryDone.zip](https://github.com/xamarin/Xamarin.Forms/files/4394297/IosEntryDone.zip)

2. Set the language on your iPhone to German.
3. Click on the Editor
4. As you can see the text is "Done". It is not translated to German. 

### Expected Behavior
"Done" text should be translated to German.

### Actual Behavior
"Done" text is not translated to German.

### Basic Information

- Version with issue: 4.5.0.495
- IDE: Visual Studio for Mac 8.4.8 (build 2)
- Platform Target Frameworks: 
  - iOS:  13.3

**Comment by PureWeen** [comment]
@Mikilll94 can you check out

https://github.com/xamarin/xamarin-forms-samples/tree/master/TodoLocalizedRTL

I tested the sample there and when I switched to Spanish the buttons all get translated

**Comment by jfversluis** [comment]
I think you might be running into this: https://blog.verslu.is/xamarin/xamarin-forms-xamarin/localization-default-ios-controls/

You will need to add the languages you want to support in your `info.plist` file. I.e.: 

```xml
<key>CFBundleLocalizations</key>
<array>
	<string>en</string>
	<string>nl</string>
</array>
```

This will translate the built-in controls to Dutch if the device is set to Dutch. You should add all the languages you want to support in there.

**Comment by Mikilll94** [comment]
@jfversluis 
Thanks. That solved my my problem. I didn't have this `CFBundleLocalizations` key in my Info.plist.
