### ISSUE TITLE
[Bug] Rendering glitch when translating views

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10118]
Hi.

There seems to be a rendering glitch happening when views are translated, that leaves a copy of the view on screen when the view is translated so that it gets close to the edges of the screen.

Please see the following video:
[https://streamable.com/evs8u](https://streamable.com/evs8u)

The red box is a Frame with a red background, with a pan handler that translates it according to drag delta. Any time the box gets close to intersecting the borders of the screen it leaves a garbage copy of itself at that position. I was planning on making a draggable pane but this seems to effectively prevent that idea.

The code for the translation is simply:
```
        private double previousDeltaY;

        private void PanUpdated(object sender, PanUpdatedEventArgs e)
        {
            switch (e.StatusType)
            {
                case GestureStatus.Running:
                    var deltaY = e.TotalY - this.previousDeltaY;
                    this.TranslationY += deltaY;

                    this.previousDeltaY = e.TotalY;
                    break;

                case GestureStatus.Completed:
                    this.previousDeltaY = 0;
                    break;
            }
        }
```

One interesting tidbit is that once the garbage clone gets rendered, it "steals" the shadow from original Frame. In other words; the red Frame has a shadow and as soon as the garbage clone appears, the shadow is rendered only in the garbage clone and the "real" frame no longer shows a shadow. This is visible in the video if close attention is paid to it.

This happens at least on iOS (haven't tested Android) and I'm using the latest preview version 4.6.0.494-pre2. I _think_ this may have gotten broken quite recently because I was toying with the idea a couple of weeks ago and didn't see the problem.

**Comment by Tommigun1980** [comment]
FWIW I found a workaround - everything renders fine if the panned view is a layout, and the Frame is added into it. If the panned view itself is a frame, the above rendering error happens.

**Comment by kingces95** [comment]
Will close this out. If someone bumps into this and the work around in insufficient we'll revisit.
