### ISSUE TITLE
[Bug] IconImageSource in a SwipeItem is rendered incorrectly

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10113]
Hi.

Adding an image via IconImageSource to a SwipeItem breaks its rendering. Using only text renders the swipe items fine, but adding an IconImageSource makes it render the button as tall as the view in which it resides is. I have only tested this on iOS, don't know if it happens on Android as well.

I'm using the latest preview version 4.6.0.494-pre2.

**Comment by jfversluis** [comment]
Would you be able to add a little more information? Maybe a screenshot or ideally a small reproduction project to make this issue a bit clearer?

**Comment by Tommigun1980** [comment]
> Would you be able to add a little more information? Maybe a screenshot or ideally a small reproduction project to make this issue a bit clearer?

This is how it looks with just a label:
<img width="266" alt="Screenshot 2020-03-28 at 17 33 18" src="https://user-images.githubusercontent.com/60286968/77827029-0ed3b580-711c-11ea-8ea7-5a6425923b29.png">

This is what it looks like when an image is added:
<img width="266" alt="Screenshot 2020-03-28 at 17 45 10" src="https://user-images.githubusercontent.com/60286968/77827040-198e4a80-711c-11ea-9b43-eb3c98f36ab0.png">

If I modify the swipe view's *contents* a bit, then the swipe item won't be stretched vertically (albeit the text doesn't show up and the icon is not entered):
<img width="282" alt="Screenshot 2020-03-28 at 17 41 54" src="https://user-images.githubusercontent.com/60286968/77827062-3cb8fa00-711c-11ea-8de2-1eb13609829a.png">

In all cases the swipe view is an item template in a collection view (or a Grial repeater), where the swipe view's contents is a grid. If the row height is Auto, the swipe items get stretched when they have an image. If the row height is fixed, they don't get stretched. Hope this helps.
