### ISSUE TITLE
[Bug] IndicatorView Binding of list Not available in IndicatorTemplate / DataTemplate or no way to get the index of each DataTemplate

### ISSUE THREAD

**Issue by avildark** [xamarin/Xamarin.Forms#10117]
### Description
I try to implement custom label for each page in a IndicatorView .
This indicator is connected to à CarrousselView with the last metho( indicator field in carrouselView).
I use the itemSource from Carousselview and a list of Monkey are defined and used in CarousselView.

Is it possible to get the item for each Label in order to use Monkeys[Item].Name ?

### Steps to Reproduce

1. Use sample : https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/IndicatorViewDemos
class

2. fo to XAML file TemplateIndicatorViewPage.xaml and replace this for IndicatorView
` <Frame VerticalOptions="Center" CornerRadius="30" BackgroundColor="#202020"   Margin="22">

            <IndicatorView x:Name="indicatorView" VerticalOptions="CenterAndExpand"
                       IndicatorColor="#202020"
                       SelectedIndicatorColor="#6EB4CD"
                       HorizontalOptions="CenterAndExpand"
                       MaximumVisible="4" 
                       >

                <IndicatorView.IndicatorTemplate >
                    <DataTemplate>
                        <Label x:Name="labeltext" Text="{Name }" FontAttributes="Bold" FontSize="15" TextColor="White"  />
                    </DataTemplate>
                </IndicatorView.IndicatorTemplate>
            </IndicatorView>
        </Frame>`
3. try to replace Name to Binding Monkeys[0].Name 

### Expected Behavior
By Use Name, i must to have this (its a picture Modified by Paint)
![image](https://user-images.githubusercontent.com/4396726/77825957-d678ab00-710c-11ea-94e6-6246bf547969.png)

### Actual Behavior
I try to use the same in indicatorView but it doesnt work
![image](https://user-images.githubusercontent.com/4396726/77825711-70d7ef00-710b-11ea-9db7-b0001f1e388b.png)

I have tried another solution because when use Monkeys[0].Name, i have a result but its the same for all indicator because i dont find index
![image](https://user-images.githubusercontent.com/4396726/77825738-9664f880-710b-11ea-816b-69c43035ee8e.png)

### Basic Information
Use the project CarouselViewDemos From official Xamarin Forms
Documentation : https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview#feedback

- Version with issue:
- Last known good version:
- IDE: Windows 10 - Visual Studio 2019 Professionnal 16.4.6
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Android 9.0 (Pie)
 - Xamarin.Forms.4.6.0.494-pre2

### Screenshots

![image](https://user-images.githubusercontent.com/4396726/77825957-d678ab00-710c-11ea-94e6-6246bf547969.png)
![image](https://user-images.githubusercontent.com/4396726/77825738-9664f880-710b-11ea-816b-69c43035ee8e.png)
![image](https://user-images.githubusercontent.com/4396726/77825738-9664f880-710b-11ea-816b-69c43035ee8e.png)

### Reproduction Link

Not Yet

### Workaround

I dont find any solution for the moment

### Possible Solution 1
Find a way to use index in DataTemplate 

### Possible Solution 2
Find a way to generate incremental value in order to replace Index, with Counter like
We Can use Monkeys[Counter].Name like this.

The solutions can be like as patrickhacens suggest in #9597

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
