### ISSUE TITLE
CollectionView EmptyView doesn't show up on UWP HorizontalList

### ISSUE THREAD

**Issue by nirbil** [xamarin/Xamarin.Forms#10110]
CollectionView's EmptyView on UWP doesn't show up on different scenarios.

As described [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview) the empty view can be of several types:

> EmptyView, of type object, the string, binding, or view that will be displayed when the ItemsSource property is null, or when the collection specified by the ItemsSource property is null or empty. The default value is null.

Reproducible scenarios:
1. Create a CollectionView without items and set ItemsLayout to HorizontalList and set EmptyView to some string
2. Create a CollectionView without items and set ItemsLayout to HorizontalList or VerticalList and set EmptyView to some view

Expected behavior:
The EmptyView will be rendered whether from the supplied string or the supplied view

Actual behavior:
The EmptyView is not shown

On Android it works as expected, did not test on iOS.
Tested using latest platform versions.

I've attached a reproduction project showing correct behavior on Android VS incorrect on UWP.
[UWPEmptyCollectionViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4434170/UWPEmptyCollectionViewBug.zip)

**Comment by jfversluis** [comment]
Hi @nirbil thanks for the report. Would you mind using the bug report template? 

We are missing a lot of information right now. It would be nice to see some relevant code, to know what version of Forms you are using, what version of UWP you are targetting, did you try this on iOS and/or Android as well? And it would be particularly awesome if you could attach a small reproduction project to show the issue.

Thanks

**Comment by samhouts** [comment]
Repro attached to ticket, please retriage.
