### ISSUE TITLE
[Bug] TabBar appears on iOS even if TabBarIsVisible is set to False on Shell app

### ISSUE THREAD

**Issue by Josecanalla** [xamarin/Xamarin.Forms#10126]
### Description
I create a new Xamarin.Forms Shell app. I set in the AppShell.xaml attribute Shell.TabBarIsVisible="False". Then if I run the app on iOS or Android, the bottom TabBar is not visible.
But then I added a MenuItem to AppShell, which executes a Command, which add a new ShellContent page to the FlyoutItem object. When I press this new MenuItem on iOS, the TabBar is now visible. And it disappears if I press any button on the TabBar.

On Android, it works OK, the TabBar remains invisible.

### Steps to Reproduce

1. Run app on iOS
2. Open left-side Flyout
3. Press "Add flyout item"
4. The TabBar is now visible

### Expected Behavior
The TabBar remains invisible when press "Add flyout item"

### Actual Behavior
The TabBar appears when press "Add flyout item"

### Basic Information

- Version with issue: I try with Xamarin.Forms 4.4.0.991265 , 4.5.0.495 and 4.6.0.494-pre2 
- Last known good version: N/A
- IDE: Visual Studio for Mac 8.5 build 3183
- Platform Target Frameworks: 
  - iOS:  13.4
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Essentials 1.3.1
- Affected Devices: iPhone 11 Simulator iOS 13.4

### Screenshots

![image](https://user-images.githubusercontent.com/11679401/77859488-2a07f900-71e0-11ea-9ea8-98033f85edb7.png)

![image](https://user-images.githubusercontent.com/11679401/77859491-32603400-71e0-11ea-8272-3479394607fb.png)

### Reproduction Link

Here is the app: [ExampleApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4399713/ExampleApp.zip)

### Workaround

My workaround is to adding MenuItem instead of FlyoutItem.

**Comment by kingces95** [comment]
Reproduces as described. 
Why are we adding tabs to a hidden tabBar?

**Comment by Josecanalla** [comment]
@kingces95 if the question is for me, I want to add flyout items only to the side menu and not to the tabBar.

**Comment by begreal** [comment]
i have a workaround for this issue. remove the title of the ShellContent and Create a CustomShellRenderer to set the Tabbar Size to 0

refer to the link here:
https://forums.xamarin.com/discussion/169894/how-to-change-shell-height-of-flyout-items-at-the-bottom-of-the-page

**Comment by AbhijeetChowdhury92** [comment]
Hi,

This issue re-appeared in the latest version v4.8.0.1821.

**Comment by flaubertagu** [comment]
> Reproduces as described. Why are we adding tabs to a hidden tabBar?

Because the design of the dev is the design of the dev.
Why adding IsVisible for it to not work?
