### ISSUE TITLE
[Bug] ToolbarItems of ControlTemplated Pages do not inherit the page´s BindingContext (Sometimes))

### ISSUE THREAD

**Issue by ahmedalejo** [xamarin/Xamarin.Forms#10121]
Previously reported here https://github.com/PrismLibrary/Prism/issues/1399
by @whiskeyboy9 _on Mar 15, 2018_

> Somewhat Qouted

Description
Hello.

Basic Setup: I want to have a `Xamarin.Forms.ToolbarItem` and a `Xamarin.Forms.ControlTemplate` in a ContentPage with a ViewModel. The `ToolbarItem` has a Command which should be executed on Tap.

Problem: The `ToolbarItem.Command` has a Binding to the `ViewModel.Command` which does not work.
When I start and click on the `ToolbarItem `it does not work.

Can someone tell me if I am missing something here, or if this is a real issue?
I am not very experienced with Bug reports so if I need to add/change something please tell me.

### Steps to Reproduce

1. Create .net standard Project with Prism.Template
2. Choose Android Project for execution
3. Create a new Page with new Item Prism Content Page
4. Navigate at startup to that page
    `App.xaml.cs`
    ```csharp 
    await NavigationService.NavigateAsync("NavigationPage/DummyPage");
    ```
5. Insert the Code
**DummTestPage**

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="Views.DummyPage">
    <ContentPage.ControlTemplate>
        <ControlTemplate>
            <StackLayout>
                <Label>I TEST ControlTemplate</Label>
                <ContentPresenter />
            </StackLayout>
        </ControlTemplate>
    </ContentPage.ControlTemplate>
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="A" Clicked="MenuItem_OnClicked" Command="{Binding ToolbarTappedCommand}"></ToolbarItem>
    </ContentPage.ToolbarItems>
    <StackLayout>
        <Label FontSize="28">I AM AN EMPTY PAGE</Label>
    </StackLayout>
</ContentPage>
```
**DummTestPage.cs**

```csharp
    public partial class DummyPage : ContentPage
    {
        public DummyPage() => InitializeComponent();

        private void MenuItem_OnClicked(object sender, EventArgs e) { }
    }
```
**DummyPageViewModel**

```csharp
    public class DummyPageViewModel : BindableBase
    {
        public DummyPageViewModel() =>
            ToolbarTappedCommand = new NewCommand();

        public ICommand ToolbarTappedCommand { get; set; }
    }

    public class NewCommand : ICommand
    {
        public event EventHandler CanExecuteChanged;

        public bool CanExecute(object parameter) =>  true;

        public void Execute(object parameter) { }
    }
```

6. **Set a Breakpoint to**
    NewCommand.CanExecute
    NewCommand.Execute
    MenuItem_OnClicked
7. **Execute Program**

### Expected Behavior

- Execute NewCommand.CanExecute on startup
- Execute NewCommand.Execute on Tap
- Execute MenuItem_OnClicked on Tap

### Actual Behavior

- Execute MenuItem_OnClicked on Tap

### Basic Information
Version with issue: Prism Template Pack 2.0.8 | Prism.Unit.Forms 7.0.0.362
Last known good version:
Xamarin.Forms version: 2.4.0.280555
IDE: VS17 15.6.1
Screenshots
Reproduction Link
What exactly do i need to do here?

### Solutions
1. **Removing the lines in the XAML**
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
Everything works as expected now
2. **Removing the ControlTemplate in the XAML**
```xaml
    <ContentPage.ControlTemplate>
        <ControlTemplate>
            <StackLayout>
                 <Label>I TEST ControlTemplate</Label>
                <ContentPresenter />
            </StackLayout>
        </ControlTemplate>
    </ContentPage.ControlTemplate>
```
Works but you don´t have a controlTemplate now :(
3. **Switching ControlTemplate and ToolbarItems**
```xaml
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="A" Clicked="MenuItem_OnClicked" Command="{Binding ToolbarTappedCommand}"></ToolbarItem>
    </ContentPage.ToolbarItems>
    <ContentPage.ControlTemplate>
        <ControlTemplate>
            <StackLayout>
                <Label>I TEST ControlTemplate</Label>
                <ContentPresenter />
            </StackLayout>
        </ControlTemplate>
    </ContentPage.ControlTemplate>
```
CanExecute is not called at beginning
And if you set the ControlTemplate as `StaticRessouce `(which is what I like to do) this does not work
`ControlTemplate="{StaticResource BaseControlTemplate}"`

Tags
Xamarin.Froms ControlTemplate ToolbarItem Binding not working

**Comment by kingces95** [comment]
Thanks for your report. Could you attach a zipped reproduction of the issue to the bug?

**Comment by samhouts** [comment]
@ahmedalejo Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by JordiCasas** [comment]
This is still an issue today. I think the issue is that the binding context is not set correctly when the `ContentPage `is shown in as the `ContentPresenter `of a `ControlTemplate`. If you use `TemplatedBinding` you'll get a Binding error in the debug output pointing to the `ContentPage`. Considering that, a workaround is to set the source of the binding to the current `ContentPage` and use its `BindingContext` (probably your ViewModel).

```<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
             prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="Views.DummyPage"

            x:Name="PageName"> <!-- Set the name of the page so we can reference it in the binding -->

    <ContentPage.ControlTemplate>
        <ControlTemplate>
            <StackLayout>
                <Label>I TEST ControlTemplate</Label>
                <ContentPresenter />
            </StackLayout>
        </ControlTemplate>
    </ContentPage.ControlTemplate>
    <ContentPage.ToolbarItems>

         <!-- Note the setting of the source of the binding (the page itself) and how we tell the binding to use its BindnigContext (your ViewModel)-->
        <ToolbarItem Text="A" Clicked="MenuItem_OnClicked" Command="{Binding BindingContext.ToolbarTappedCommand, Source={x:Reference PageName}}"/>
    
</ContentPage.ToolbarItems>
    <StackLayout>
        <Label FontSize="28">I AM AN EMPTY PAGE</Label>
    </StackLayout>
</ContentPage>```

This will work, but it forces you to add always the name of the page and the source to the binding every time you want a toolbar item... Would be nice if this issue could be revisited. Maybe in MAUI this won't be an issue...
