### ISSUE TITLE
[Bug] [Shell] Locked Flyout disappears when same item pressed twice

### ISSUE THREAD

**Issue by aharwood2** [xamarin/Xamarin.Forms#10133]
### Description
I'm using a shell flyout set to `FlyoutIsPresented = true` and `FlyoutBehavior = Locked` to implement a two-pane layout -- a permanently displayed menu on the left and page content on the right. However, a double-tap on a item hides the flyout (which cannot then be opened again). Additionally, if the currently selected item is tapped a second time, the same behavior is observed.    

Cannot test this on iOS at present due to [this other issue](https://github.com/xamarin/Xamarin.Forms/issues/8308).    

Not tested on UWP.   

This may be related to / fixed by [this PR](https://github.com/xamarin/Xamarin.Forms/pull/9719).

### Steps to Reproduce

1. Create a new solution using the Xamarin.Forms.Shell template.
2. Remove the Tabbar content and replace with FlyoutItem content.
3. Add Shell.FlyoutIsPresented and Shell.FlyoutBehavior (true and locked respectively) to the BaseStyle.
4. Change child style TargetType to ShellItem
5. Install and open app and observe permanent open flyout and right-hand content page as expected.
6. Select the same item in the menu twice, or double tap an item.
7. Flyout disappears and leaves a dirty UI behind.

### Expected Behavior
The flyout should remain on the screen and not transition to the disappeared state.

### Actual Behavior
The flyout disappears with animation and leaves a dirty UI "hole" where it should have been,

### Basic Information

- Version with issue: Xamarin.Forms 4.5.0.495
- Last known good version: Unknown
- IDE: VS 2019 16.5.1
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: 9.0 / API Level 28
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials, NETStandard.Library
- Affected Devices: Google Pixel C + API 27 + 28 Emulators

### Screenshots
![Screenshot_20200330-125527](https://user-images.githubusercontent.com/8614261/77909794-dbad3580-7285-11ea-82dd-4529e4a36fd4.png)

### Reproduction Link
[Reproduction repo](https://github.com/aharwood2/Xamarin.Forms.Shell.FlyoutLockedIssue)

### Workaround
None

**Comment by aharwood2** [comment]
I notice that if I set the properties after `InitializeComponent()` in the AppShell ctor, I get the expected behaviour. Perhaps this issues is related to how the styling is applied from the XAML?

```
public AppShell()
{
    InitializeComponent();
    FlyoutBehavior = FlyoutBehavior.Locked;
    FlyoutIsPresented = true;
}
```

**Comment by kingces95** [comment]
Reproduces as described on android.

**Comment by PureWeen** [comment]
duplicate 
https://github.com/xamarin/Xamarin.Forms/issues/9440

**Comment by aharwood2** [comment]
Thank you Xamarin team for working on this bug. You have a great product here -- we love it! ❤️
