### ISSUE TITLE
[Enhancement] Enable greater control over keyboard behavior without platform-specific code

### ISSUE THREAD

**Issue by mikeparker104** [xamarin/Xamarin.Forms#10135]
## Summary
The following requirements can be addressed using custom platform-specific code:

1. [Having the content area move up (and resize) to accommodate the soft keyboard](https://github.com/dotnet/maui/issues/11979)
2. [Having the return/send key (on the soft keyboard) invoke the return command without having the keyboard dismissed as a result](https://github.com/dotnet/maui/issues/12003)
   - The reason this happens on XF is due to the code we have that auto closes the keyboard when you tap outside of an entry. By default on iOS/Android if you click a Button the keyboard will not close. 
3. Preventing specific UI elements from taking focus from an Entry while still invoking their touch-related events/commands e.g. button click
   - Same comment here as the previous issue. This only happens because of the side effect behavior that we have implemented where it will close the keyboard automatically if you click outside of an entry field
4. [Ability to dismiss the keyboard by dragging downwards](https://github.com/dotnet/maui/issues/11983)

Indicative user experience:

<p>
<img src="https://raw.githubusercontent.com/mikeparker104/xf_chat/master/readme_illustrations/android_chat_experience.gif" alt="Indicative chat experience for Android" height="300" style="display:inline-block;" />

<img src="https://raw.githubusercontent.com/mikeparker104/xf_chat/master/readme_illustrations/ios_chat_experience.gif" alt="Indicative chat experience for iOS" height="300" style="display:inline-block;" />
</p>

Being able to achieve this using only Xamarin.Forms components would be ideal.

## API Changes

This could potentially be addressed by providing general purpose cross-platform APIs surfacing the necessary values and events. For example, providing a bindable property for the current height of the keyboard and exposing events to indicate when various states change. In certain situations, such as point 3, having the option to indicate that a given event has been handled in order to prevent it from propagating further might be needed.

To further reduce the amount of custom logic required, the requisite configuration might be applied by exposing additional properties on specific components or perhaps through attached properties where it makes sense. 

The following are indicative configurations to demonstrate the intent:

1. **KeyboardLayout (applies to a ContentPage)**

- Default: the current behavior i.e. keyboard overlaps content when presented
- Resize: content area resizes to accommodate the keyboard

2. **ReturnMode (applies to components that display the keyboard when focused e.g. Entry)**
- Default: the current behavior i.e. keyboard is dismissed when the return key is tapped and touch-related events/commands are raised/invoked e.g. ReturnCommand on an Entry
- Sticky: the keyboard is not dismissed but the touch-related events/commands are still raised

3. **KeyboardDismissMode (applies to any UI element)**

- Default: the current behavior i.e. tapping on a UI element (that takes focus) dismisses the keyboard. Any touch-based events/commands are raised on that UI element
- Sticky: the touch-based events/commands are still raised but the UI element does not receive focus and the keyboard is not dismissed as a result

4. **DismissKeyboardOnDrag (applies to scrollable content e.g. ScrollView, ListView, etc.)**

- False (default): the current behavior i.e. dragging/scrolling the content has no impact 
- True: any dragging/scrolling of the content results in the keyboard getting dismissed for Android. On iOS, the user would have to drag the keyboard out of view to achieve the same outcome (uses KeyboardDismissMode.Interactive)

Indicative XAML markup:

```xaml
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Title="Chat"
    KeyboardLayout=”Resize”
    x:Class="ChatDemo.MainPage">
 
    <Grid>
 
            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>
 
            <ScrollView DismissKeyboardOnDrag=”True”>
                <StackLayout BindableLayout.ItemsSource="{Binding Messages}" BindableLayout.ItemTemplate="{StaticResource ItemDataTemplate}" />
            </ScrollView>
 
            <StackLayout Orientation="Horizontal" Grid.Row="1">
                <Entry Keyboard="Chat" 
                             ReturnMode=”Sticky” 
                             HorizontalOptions="FillAndExpand" 
                             HeightRequest="40" 
                             Placeholder="Text Message" 
                             ReturnCommand="{Binding TapCommand}" 
                             ReturnType="Send" />
                <Button ContentPage.KeyboardDismissMode=”Sticky” 
                               BackgroundColor="Transparent" 
                               Command="{Binding TapCommand}" 
                               Text="Send" 
                               VerticalOptions="Center" />
            </StackLayout>
 
        </Grid>
 
</ContentPage>
```

## Intended Use Case
These behaviours are commonly associated with chat-based experiences including the default text messaging applications that ship with the OS itself.

**Comment by APopatanasov** [comment]
I believe such an enhancement will be a great addition to the framework. Currently, Xamarin.Forms lucks of API that provides the ability to control the keyboard and focus behavior. 

I believe the third requirement is very important. Currently, Xamarin.Forms alters the default focus behavior of the EditText and UITextField. Both controls in the native world does not loose their focus when we are tapping outside them or when for example a Button gets pressed. 

That is behavior introduced by Forms, both on [Android](https://github.com/xamarin/Xamarin.Forms/blob/2a6f69df24915f5f8936912d459983b2bf1f419c/Xamarin.Forms.Platform.Android/PlatformRenderer.cs#L65) and [iOS](https://github.com/xamarin/Xamarin.Forms/blob/2a6f69df24915f5f8936912d459983b2bf1f419c/Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs#L234). Changing the native behavior according to me is not a good approach. At least on both frameworks some API should be introduced that will allow the developers to choose whether to make the control loose focus or preserve it.

**Comment by sreerajPR** [comment]
For the third requirement, there is a platform-specific API in iOS `CanBecomeFirstResponder `. When this property is Set on any View (for example a Send Button in a chat application), it will not dismiss an already opened keyboard by an Entry or Editor. 

For a similar experience in Android, I have created a [Pull Request](https://github.com/xamarin/Xamarin.Forms/pull/11191), which will add a platform-specific API in Android `DismissKeyboardOnOutsideTap`.  When this property is set as `False` (this property defaults to `True`), on any Entry or Editor, the keyboard attached to this control will not be dismissed on tapping anywhere else. So this will give much finer control to the developer to implement his own logic on when all keyboards should be dismissed.

Looking forward to this PR getting approved so that I can use it in an existing Xamarin.Forms chat application.

**Comment by BenBtg** [comment]
I'm working with a customer who has raised issues with inconsistent behaviour with this exact feature in MAUI

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

I think this is already being looked at in great detail for .NET MAUI. Thanks!
