### ISSUE TITLE
[Bug] Absolute layout with proportional dimensions and AutoSize don't work

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10142]
Hi.

If you have a view inside an absolute layout and use proportional dimensions and set the width or height to AutoSize, nothing gets drawn.

 ```
           <Frame
                AbsoluteLayout.LayoutFlags="PositionProportional"
                AbsoluteLayout.LayoutBounds="0.5, 1, AutoSize, AutoSize" />
```
works, but

```
            <Frame
                AbsoluteLayout.LayoutFlags="All"
                AbsoluteLayout.LayoutBounds="0.5, 1, AutoSize, AutoSize" />
```
doesn't. Shouldn't auto sized relational dimensions be valid; an automatic size is an automatic size no matter whether the layout is proportional or absolute.

I'm using Xamarin.Forms 4.6.0.494-pre2.
Thanks.

**Comment by kingces95** [comment]
Could you please attached your zipped reproduction with a few screenshots? Thanks.

**Comment by samhouts** [comment]
@Tommigun1980 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Tommigun1980** [comment]
It is affecting me, but I don't feel like putting the above code in a zip for you.
