### ISSUE TITLE
[Enhancement] Entry with ErrorText

### ISSUE THREAD

**Issue by lsaudon** [xamarin/Xamarin.Forms#10143]
## Summary
Entry with ErrorText

## API Changes

Add ErrorText Property in Entry API

```csharp
var entry = new Entry();
entry.ErrorText = "Error message";
```
![image](https://user-images.githubusercontent.com/25029876/77998935-25535a00-7332-11ea-8ecd-140c81e58665.png)

## Intended Use Case
When doing field validation, so that the keyboard does not cover the ErrorText field.

**Comment by Vroomer** [comment]
It would be great if you can bring Entry to the same level of functionality as Android Material. It's one of the most used control and it lacks fairly basic functions.
