### ISSUE TITLE
[Enhancement] Implement an event to detect scroll begin and end for CarouselView

### ISSUE THREAD

**Issue by petro2050** [xamarin/Xamarin.Forms#10157]
## Summary
The current `Scrolled` event sends scroll parameters, but there is no way to get a notification when scrolling begins and ends. Having such notifications is crucial because we can pause animations before scrolling begins and start them after it ends. When animations continue during scrolling, UI stutter happens, and it's not very pleasing.

## API Changes

A possible API would be to create a `ScrollStateChanged` event and send enums for each state.

**Comment by chaoyebugao** [comment]
I expect this too...

**Comment by Alicg** [comment]
Is there any existing workaround for detecting whether scrolling is active (started and not released)?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
