### ISSUE TITLE
Styles: Style TargetType Xamarin.Forms.Label is not compatible with element target type Xamarin.Forms.Span

### ISSUE THREAD

**Issue by vravindranath** [xamarin/Xamarin.Forms#10167]
When running application we are getting the following text in application output
Styles: Style TargetType Xamarin.Forms.Label is not compatible with element target type Xamarin.Forms.Span

### Steps to Reproduce

1. Xamarin Forms version4.5.0.396
2. xamarin forms app with label binding using span
3.

**Comment by kingces95** [comment]
Please attach a zipped reproduction.

**Comment by samhouts** [comment]
@vravindranath Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by samhouts** [comment]
@vravindranath This is expected. Span and Label are not the same TargetType. You need to define a different style for each. https://github.com/xamarin/Xamarin.Forms/pull/7495

**Comment by liveinvarun** [comment]
@samhouts thanks for the update.
