### ISSUE TITLE
[Enhancement] Navigation bar renderer!

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#10173]
## Question
Is it possible to create custom renderer for navigation header ?

**Comment by samhouts** [comment]
@AlexAba There are some tutorials online (https://www.xamboy.com/2017/12/06/navigation-bar-customization-in-xamarin-forms/, for example). You can also try the NavigationBar.TitleView. This sort of question is best suited for the [forums](https://forums.xamarin.com/) or StackOverflow. Thanks!
