### ISSUE TITLE
[Bug] Issues setting the initial position on a CarouselView to a non-zero value

### ISSUE THREAD

**Issue by alaneich** [xamarin/Xamarin.Forms#10170]
### Description
I have a CarouselView which I need to initially show one of the items and I want the CarouselView to go directly to this item and not show any other item or do any animation to the desired item.  Everything works fine when the first item is initially shown and this was working in v4.4.0.  With v4.5.0-sr2, I get the following results.

When setting the desired position in the page's constructor on Android, the first item will be shown and then scrolls with animation to the desired item even with IsScrollAnimated set to false.  On iOS, the first item will be shown and it will not go to the desired item even though the position is set correctly.

I also tried setting the position in the OnAppearing method although this is less desirable since I only want to do this the first time the screen is shown.  On Android, the correct item does show but changing the position before any swiping does not work (the item in the CarouselView does not change even though the Position property changes and the change event occurs).  After swiping to the next or previous item, changing the position works correctly.  On iOS, the first item shows briefly before switching to the correct item (no animation with IsScrollAnimated set to false). 

### Steps to Reproduce

1. Run the attached project: [CarouselTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4415834/CarouselTest.zip)
2. The first button will go to a page with a CarouselView and sets the position to the 4th item using the constructor.  The second button will do the same except using the OnAppearing method.  
3. At the bottom is the current position of the CarouselView and buttons to increment and decrement the position.

### Expected Behavior
The CarouselView should be able to initially go directly to an item (with no animation) and changing the position should always work. 

### Actual Behavior
See the description.

### Basic Information

- Version with issue: 4.5.0.495
- Last known good version: 4.4.0.991265
- IDE: Visual Studio 15.9
- Platform Target Frameworks: 
  - iOS:  12.4
  - Android: 9.1.7.0

**Comment by kingces95** [comment]
Reproduces as described.

**Comment by sasa-bobic** [comment]
[iOS]:
In CarouselViewController (https://github.com/xamarin/Xamarin.Forms/blob/4.5.0/Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs)

When UpdateInitialPosition() calls ScrollToPosition(), the Carousel.Position property is already set to same value so ScrollToPosition() doesn't call Carousel.ScrollTo().

---

This workaround works for me (at least in simulator, haven't tested much):

`    public class AppCarouselViewRenderer : CarouselViewRenderer
    {
        protected override CarouselViewController CreateController(CarouselView newElement, ItemsViewLayout layout)
            => new AppCarouselViewController(newElement, layout);
    }

    public class AppCarouselViewController : CarouselViewController
    {
        public AppCarouselViewController(CarouselView itemsView, ItemsViewLayout layout) : base(itemsView, layout)
        {
        }

        public override void ViewWillLayoutSubviews()
        {
            base.ViewWillLayoutSubviews();

            UpdateInitialPosition();
        }

        bool _initialPositionUpdated;
        void UpdateInitialPosition()
        {
            if (_initialPositionUpdated)
                return;

            _initialPositionUpdated = true;

            if (Carousel.CurrentItem != null)
            {
                int position = (Carousel.ItemsSource as IList)?.IndexOf(Carousel.CurrentItem) ?? 0;

                Carousel.ScrollTo(position, position: ScrollToPosition.Center, animate: Carousel.AnimateCurrentItemChanges);
            }
        }
    }`

**Comment by Juansero29** [comment]
I also have this behavior on the app I'm working on. Can confirm it's exclusive to iOS.

**Comment by Juansero29** [comment]
Any updates on this bug? I'm also experiencing this, had to come back to an earlier version of Xamarin Forms for this to stop

**Comment by ngreen-asli** [comment]
This does not seem to be resolved for iOS as if I bind the position and the position is anything other than 0, the Carousel still only positions to the first item on iOS but it positions to the correct item in Android

**Comment by rmarinho** [comment]
@Juansero29 can you try this nuget packages

[release.zip](https://github.com/xamarin/Xamarin.Forms/files/4610819/release.zip)

**Comment by smalgin** [comment]
Also, first time changing the position doesn't work. When you swipe right, left and then hit Next button to increase position counter, it works. Just FYI. It used to work before latest upgrade.

**Comment by rmarinho** [comment]
@smalgin tested with what package?

**Comment by alaneich** [comment]
I tested my application with v4.6.0-sr1 and found the following issues:
On Android, setting the position does not always change the item displayed after the CarouselView first appears.  This only occurs when the initial position is zero when set in the constructor.  It always occurs when the position is set in onAppearing.  Swiping will get it back working.  This sounds like the issue @smalgin described.

On iOS, there are no issues when setting the position in the constructor, but the issue described in this issue still exist if the position is set in onAppearing.

Since my app is going to set the initial position in the constructor, the Android issue is a problem I need fixed.  Do I need to create a new issue for this?

**Comment by smalgin** [comment]
@alaneich, you are absolutely correct. This is the issue.

**Comment by alaneich** [comment]
I just retested my application with v4.6.0-sr3 and found that setting the position now works after the CarouselView first appears when setting the initial position in the constructor on Android.

**Comment by rmarinho** [comment]
@smalgin can you check if fixes the issue for you also? 
Thanks

**Comment by smalgin** [comment]
I'll try today.

**Comment by smalgin** [comment]
Is the fix in any of these? I don't know where to get 4.6.0-sr3

![image](https://user-images.githubusercontent.com/8367800/83976195-6d03de00-a8ad-11ea-94f2-77fdda74e272.png)
