### ISSUE TITLE
[Android]Border not in view when we set the device density is in float value

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#10172]
### Description

Greetings, 

We have noticed a border is not in view when my device density is in float value. In my sample application, I have loaded certain elements inside a container which is inherited from Layout<View>. The child elements inside is container is inherited from ContentView which has label as child contents. I had layout the child elements inside the container based on the screen size and applied white color for them accordingly. And write the custom renderer for ContentView and draw the border using canvas. It is working fine when the device density is in round value. But if density is in float value some of my border is not In view.

protected override void OnDraw(Canvas canvas)
{
    base.OnDraw(canvas);
    var paint = new Paint(PaintFlags.AntiAlias | PaintFlags.LinearText);
    paint.Color = Android.Graphics.Color.Red;
    canvas.DrawLine(0, (float)(this.Height - 0.5), (float)this.Width, (float)(this.Height), paint);
}

I have use Samsung S8+ device for testing. In that, we can change the screen resolution. If I set the WQHD it will working fine. otherwise some of my border is not drawn. Please refer the attached screen shots for reference.

### Steps to Reproduce

1. Run the Attached sample in Samsung S8+ device.
2.  Set the Screen resolution as FHD or HD

### Expected Behavior
Need to draw all borders.
### Actual Behavior
Some of the borders is not drawn.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android:  
- Nuget Packages: All version of xamarin.
- Affected Devices:  Samsung S8+ device.

### Screenshots
**HD**

![HD](https://user-images.githubusercontent.com/35529145/78156552-95f69580-745c-11ea-9046-6bef8468bf79.jpg)

**FHD**
![FHD](https://user-images.githubusercontent.com/35529145/78156500-82e3c580-745c-11ea-9a34-273cfb43d0d8.jpg)

**WQHD**
![WQHD](https://user-images.githubusercontent.com/35529145/78156522-88411000-745c-11ea-9d06-95c4cb1258f9.jpg)

### Reproduction Link
[BorderIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4416212/BorderIssue.zip)

**Comment by kingces95** [comment]
Hm, they render for me. This is gonna be challenging as it's device specific. But first, can you reproduce this issue without a custom renderer. Custom renderers "void the warranty" on XF.

**Comment by jsuarezruiz** [comment]
Some recommendations:

- Use `PaintFlags.AntiAlias`.
- You can use `StrokeWidth` to define the height of the line.
- You can use StrokeWidth dependent on density (StrokeWidth / `Resources.DisplayMetrics.Density`).

This way you can always render the line independent of the device.

**Comment by Sivaraman761** [comment]
Hi @jsuarezruiz 

I have tried your recommendations to overcome the issue. But unfortunately, it’s not working. In my same I have set the PaintFlags.AntiAlias and set the StrokeWidth and my StrokeWidth dependents on my device density. But it’s not working. I have modified the same with you recommend codes. Please refer to the sample. It does not work in FHD or HD resolution. 

![FHD](https://user-images.githubusercontent.com/35529145/82866723-19a59d80-9f47-11ea-9308-46bf60fa634f.jpg)
![HD](https://user-images.githubusercontent.com/35529145/82866727-1b6f6100-9f47-11ea-8b20-87cba27e9045.jpg)

[BorderIssue (2).zip](https://github.com/xamarin/Xamarin.Forms/files/4680222/BorderIssue.2.zip)

**Comment by hartez** [comment]
Give this a try:

```

protected override void OnDraw(Canvas canvas)
{
    base.OnDraw(canvas);

    int deviceIndependentStrokeWidth = 1;
    float strokeWidth = TypedValue.ApplyDimension(ComplexUnitType.Dip, deviceIndependentStrokeWidth, Resources.DisplayMetrics);

    var paint = new Paint
    {
        Color = Android.Graphics.Color.Red,
        StrokeWidth = strokeWidth
    };

    var lineY = Height - paint.StrokeWidth;

    canvas.DrawLine(0, lineY, Width, lineY, paint);
}
```

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
