### ISSUE TITLE
[BUG] java.net.ProtocolException on MediaElement

### ISSUE THREAD

**Issue by agbeltran9** [xamarin/Xamarin.Forms#10177]
### Description

Media element not reproduce this URL "https://gol2soul.blob.core.windows.net/agbggmailcom/sports-representative-video-637212595398907890.mp4" and output appears this message

04-01 19:30:56.245 W/MediaHTTPConnection(28672): readAt 548122 / 32768 => java.net.ProtocolException
04-01 19:30:56.943 W/MediaHTTPConnection(28672): readAt 548122 / 32768 => java.net.ProtocolException
04-01 19:30:58.916 W/MediaHTTPConnection(28672): readAt 548122 / 32768 => java.net.ProtocolException
04-01 19:30:59.279 W/MediaHTTPConnection(28672): readAt 548122 / 32768 => java.net.ProtocolException

### Steps to Reproduce

1. set media element source https://gol2soul.blob.core.windows.net/agbggmailcom/sports-representative-video-637212595398907890.mp4
2. try to play on android
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 Community
- Platform Target Frameworks: 

  - Android: API 24

**Comment by kingces95** [comment]
Please attach a zipped reproduction.

**Comment by samhouts** [comment]
@agbeltran9 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by DavidAsish** [comment]
I still see this issue. We are getting this 

[MediaHTTPConnection] readAt 1018160 / 32768 => java.net.ProtocolException - In Application Output. 

Audio files of type Mp3 stored in remote location. 

Target Framework is Android 9. Its recreating on Device. 
Device is on Android 10 Version. Samsung Galaxy Note 10.

**Comment by MaxJadav** [comment]
I am also facing this issue. Video not start playing. Any solution?  @DavidAsish  @samhouts  @kingces95 
W/MediaHTTPConnection: readAt 941117 / 32768 => java.net.ProtocolException
W/MediaHTTPConnection: readAt 215988 / 32768 => java.net.ProtocolException
W/MediaHTTPConnection: readAt 941117 / 32768 => java.net.ProtocolException
W/MediaHTTPConnection: readAt 215988 / 32768 => java.net.ProtocolException
