### ISSUE TITLE
[Bug] Docs incorrect for CollectionView.InvalidateMeasure()?

### ISSUE THREAD

**Issue by robertmiles3** [xamarin/Xamarin.Forms#10180]
### Description

I have a search page using a `CollectionView`, and I am seeing some weird visual heights on my cells whenever the results list changes. However, as soon as a I scroll the `CollectionView` things get redrawn and are fine. As such, I wanted to try and invalidate the `CollectionView` after a search. According to the latest docs [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.collectionview?view=xamarin-forms), `CollectionView` is supposed to have `InvalidateMeasure()` which I was going to use for this. But, it doesn't seem to be available. Am I just missing something stupid or are the docs incorrect?

### Steps to Reproduce

1. Have a `CollectionView` on a XAML page and try to write `CollectionView.InvalidateMeasure()` in the code-behind.

### Expected Behavior

Be able to call `CollectionView.InvalidateMeasure()`.

### Actual Behavior

`InvalidateMeasure()` is not available.

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: ??
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  13.14.1.39
- Nuget Packages: Xamarin.Forms 4.5.0.530

### Screenshots

![image](https://user-images.githubusercontent.com/944302/78224733-b90f5c80-74d1-11ea-9b51-ff97d96428d4.png)

![image](https://user-images.githubusercontent.com/944302/78224721-b3197b80-74d1-11ea-8327-be7ca57b3f30.png)

**Comment by kingces95** [comment]
Could you please attach a zipped reproduction with screenshots?

**Comment by robertmiles3** [comment]
Here's a repro (brand new app from template in VS for Mac). Just to show the issue, I added `ItemsCollectionView.InvalidateMeasure();` to `ItemsPage.OnAppearing` in `ItemsPage.xaml.cs`.

[CollectionViewInvalidate.zip](https://github.com/xamarin/Xamarin.Forms/files/4431139/CollectionViewInvalidate.zip)

Screenshot:
![image](https://user-images.githubusercontent.com/944302/78424437-23f99880-7676-11ea-8337-d410f0f48c2d.png)

**Comment by Phenek** [comment]
I did not see your repro,
But if you got some weird height!
It could be because of your cell.

You need to use a calculable height on your cell.
That why you don’t have to use for example a Grid with GridUnit .Star or .Auto (or it must be fixed)

**Comment by samhouts** [comment]
@robertmiles3 That is a protected virtual method. You can't access it like that. :) https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.invalidatemeasure?view=xamarin-forms#Xamarin_Forms_VisualElement_InvalidateMeasure
