### ISSUE TITLE
[Bug] WPF out of memory exception due to endless loop in LabelRenderer

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#10192]
### Description

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/TextBlockExtensions.cs

At
`public static void RecalculateSpanPositions(this TextBlock control, Label element, IList<double> inlineHeights)`
there's an assignment of default line height:
`var defaultLineHeight = inlineHeights[i];`
and further there's a **while** loop which may become infinite if the **defaultLineHeight** happens to be 0 (and few other conditions in the loop come together).
```
while (yaxis < endRect.Bottom)
{
```
```
  else if (yaxis != endRect.Top) // Middle Line(s)
  {
    lineHeight = defaultLineHeight;
  }
```
```
  yaxis += lineHeight;
}
```

### Steps to Reproduce

No specific steps or root cause found, the issue started appearing on 1909 version of Windows 10 quite regularly, might have happened before. Here's the repo and binary with reproducible issue (just start a test on any drive):
https://github.com/maxim-saplin/CrossPlatformDiskTest
https://github.com/maxim-saplin/CrossPlatformDiskTest/releases/download/2.3.0/CPDT.exe.zip

### Expected Behavior
No app crash due to OutOfMemoryException 

### Actual Behavior
OutOfMemoryException

### Basic Information
XF 4.5.0.530
Windows 10 1909
.NET Framework 4.8

### Screenshots

![image](https://user-images.githubusercontent.com/7947027/78346323-918ac380-75a7-11ea-9dbc-71661fa1dc96.png)

![image](https://user-images.githubusercontent.com/7947027/78346425-b54e0980-75a7-11ea-9fc1-22cd0476db03.png)

### Workaround

Copy past LabelRenderer, and TextBlockExtensions, AlignmentExtensions and FontExtensions from XF sources. Rename LabelRenderer to CustomLabelRenderer, fix all the using's and references and make it compile. Export the CustomerLabelRenderer making it replace the original XF renderer. In TextBlockExtensions add check for 0 value of **defaultLineHeight**:

```
var defaultLineHeight = inlineHeights[i];
if (defaultLineHeight == 0) defaultLineHeight = 19.5;
```

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
