### ISSUE TITLE
[Question] How to setup binding path in code instead of XAML?

### ISSUE THREAD

**Issue by pstricks-fans** [xamarin/Xamarin.Forms#10194]
This is not a feature request but  just a question.

# Base View Model

```
public class ViewModelBase : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    protected bool SetProperty<T>(ref T field, T value, [CallerMemberName] string propertyName = null)
    {
        if (EqualityComparer<T>.Default.Equals(field, value)) return false;
        field = value;
        OnPropertyChanged(propertyName);
        return true;
    }

    private void OnPropertyChanged(string propertyName)
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

}
```

# View Model

```
public class DateTimeViewModel : ViewModelBase
{
    public DateTimeViewModel()
    {
        Device.StartTimer(TimeSpan.FromMilliseconds(15),
            () =>
            {
                DateTime = DateTime.Now;
                Counter++;
                return true;
            }
        );
    }

    private DateTime dateTime = DateTime.Now;

    public DateTime DateTime
    {
        get => dateTime;
        private set => SetProperty(ref dateTime, value);
    }
}
```

# MyPage 

It has been trimmed for the sake of simplicity.

    <ContentPage.Resources>
        <ResourceDictionary>
            <toolkit:DateTimeViewModel x:Key="dateTimeViewModel"/>
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout >
        <StackLayout.BindingContext>
            <Binding Path="DateTime">
                <Binding.Source>
                    <toolkit:DateTimeViewModel/>
                </Binding.Source>
            </Binding>
        </StackLayout.BindingContext>
        <Label Text="{Binding Hour,StringFormat='The hours are {0}'}" />
        <Label Text="{Binding Minute,StringFormat='The minutes are {0}'}" />
        <Label Text="{Binding Second,StringFormat='The seconds are {0}'}" />
    </StackLayout>

where `xmlns:toolkit="clr-namespace:Toolkit;assembly=Toolkit"`.

# Question

Only for learning purposes, I want to remove 

    <ContentPage.Resources>
        <ResourceDictionary>
            <toolkit:DateTimeViewModel x:Key="dateTimeViewModel"/>
        </ResourceDictionary>
    </ContentPage.Resources>

        <StackLayout.BindingContext>
            <Binding Path="DateTime">
                <Binding.Source>
                    <toolkit:DateTimeViewModel/>
                </Binding.Source>
            </Binding>
        </StackLayout.BindingContext>

and to reimplement them  in code.

My attempt in the `MyPage` constructor as follows results in the application crashes at runtime.

          BindingContext = new DateTimeViewModel();
          this.SetBinding(Label.TextProperty, new Binding() { Path = "DateTime" });

What is the correct way to set the binding path?

**Comment by solomonfried** [comment]
I would think that 
BindingContext = new DateTimeViewModel().DateTime should do the trick

If you are looking for a general way to mimic the Xaml feature of {Binding Source=…}
it is done like this. 
(I am using nameof instead of hardcoding "DateTime")

var myVM = new DateTimeViewModel();
var itemSourceBinding = new Binding(nameof(myVM.DateTime), source: myVM );
this.SetBinding(Label.TextProperty,itemSourceBinding );

**Comment by pstricks-fans** [comment]
@solomonfried : both do not work.

**Comment by solomonfried** [comment]
I may have missed what you are trying to accomplish, but the code I provided is taken straight out of my application.
I am not sure what you mean by "do not work". Assuming your DateTime property is sending ProperyChanged events. Is the Label Showing anything???  How are you changing the DateTime in the underlying ViewModel?

In my application, this is the actual code with the controls I am using.
I am setting the ItemsSource Propertyt of a chart to the ItemsSource Property  of another control

```
   var columnSeries = new ColumnSeries()
            {
                XBindingPath = nameof(StudentHomeworkModel.RecordedOn),
                YBindingPath = nameof(StudentHomeworkModel.CompletnessScore),
                Width = 2
            };
var itemSourceBinding = new Binding(nameof(ChartSeries.ItemsSource), source: myListViewControl);
columnSeries.SetBinding(ChartSeries.ItemsSourceProperty, itemSourceBinding);
```

So this code sets the ItemsSource of a Column Chart to the ItemsSource of a list of Data showing on the screen. (whenever the list changes, the Chart changes)

**Comment by pstricks-fans** [comment]
@solomonfried : I see. You did not read my code. Thank you.
