### ISSUE TITLE
[Enhancement] Designer file support for Font assets

### ISSUE THREAD

**Issue by matthewrdev** [xamarin/Xamarin.Forms#10205]
## Summary

With the addition of the [new EmbeddedFonts feature](https://devblogs.microsoft.com/xamarin/embedded-fonts-xamarin-forms/), I'd like to propose automatically generating a `.Designer` code-behind file that exposes the font asset to Xamarin.Forms.

Additionally, if the font asset has named glyphs, the designer file would also contain a helper class that exposes all glyph character codes as named constants:

```
using System;
using Xamarin.Forms;

[assembly: ExportFont("FontAwesomeSolid.ttf")]

namespace FontDesignerClassSample.Fonts
{
    /// <summary/>
    /// A helper class that provides named properties for all glyphs in Font Awesome 5 Pro Solid.
    /// <para/>
    /// <summary/>
    public class FontAwesomeSolid
    {
        public const string Abacus = "\uf640";
        public const string Acorn = "\uf6ae";
        public const string Ad = "\uf641";
    
        // ...
    }
}
```

**Example**
![image](https://user-images.githubusercontent.com/3260473/78407416-1c22ff80-7648-11ea-8887-c5d3185e0bb6.png)

I would be happy to open source the font component that accomplishes this from MFractor. [Please see this article for an example.](https://docs.mfractor.com/fonts/generate-font-character-code-class/)

Please see attached solution that demonstrates this proposal.

[FontDesignerClassSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4430098/FontDesignerClassSample.zip)

## API Changes

This would require the addition of an MSBuild task or tool that automatically create a designer file for an embedded resource that is a `.ttf` or `.otf` file.

## Intended Use Case
This has several intended use cases to improve readability and maintainability of users codebases plus enable future features like a Glyph markup extension.

### Improve Code Readability
A font asset designer file would encourage developers to use named constants over unicode characters to reference fonts icons:

**Example**
`label.Text = "/uf00c";` vs `label.Text = Fonts.FontAwesomeSolid.Check;`

It is obvious that the icon is a check from FontAwesome, making the code cleaner, more readable and more maintainable.

### Glyph Discoverability

A glyph designer class surfaces all glyphs available in a given font and allows developers to discover the available glyphs without opening the font in a viewer, Googling it or referring to the fonts original location/guide.

### Future Markup Extension Support

Having a named constants class will also enable future features such as a glyph markup extension that allows users to reference icons by name:

`<Label FontFamily="FontAwesomeSolid" Text="{Glyph Monkey}"/>`

### Tooling Support

Additionally, a designer file allows tools (like MFractor) to provide IntelliSense for glyphs and analysis for glyph references that do not exist.

**Comment by jfversluis** [comment]
Great and detailed write up @matthewrdev ! Sorry we never got around to it... If you still see any room for improvement here for .NET MAUI, please open a discussion and/or feature request there and I'll promise we'll do better :)

Thanks!
