### ISSUE TITLE
Material Visual uses deprecated UIWebView

### ISSUE THREAD

**Issue by DanielGlick45** [xamarin/Xamarin.Forms#10201]
### Steps to Reproduce

1. Add Xamarin.Forms.Visual.Material nuget package to iOS project
2. Submit a build to iOS AppStore

### Expected Behavior
1. Build should go through without any issues

### Actual Behavior
![image](https://user-images.githubusercontent.com/25595425/78381245-16271300-75a3-11ea-8ba8-af1c6dbd576b.png)

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: N/A
- IDE: Visual Studio For Mac
- Platform Target Frameworks:
  - iOS: 13.2
- Nuget Packages: Xamarin.Forms.Visual.Material
- Affected Devices: 

### Workaround
Remove the nuget package... ;)

**Comment by PureWeen** [comment]
This will be resolved with the latest 4.6

https://github.com/xamarin/Xamarin.Forms/pull/9053

**Comment by jfversluis** [comment]
As a workaround for now you can manually install the latest Xamarin.iOS.MaterialComponents package as also indicated here: https://github.com/xamarin/Xamarin.Forms/issues/9823#issuecomment-594599608
