### ISSUE TITLE
[Bug] Image Source does not work for GTK native images 

### ISSUE THREAD

**Issue by B-Simms** [xamarin/Xamarin.Forms#10212]
### Description
When creating an Image within a page in a cross-platform project that includes a GTK build, setting the Source to a ".png" file path (as a string) in the GTK root directory  does not result in the rendering of said image. I've also tried adding a specified "Assets" folder to the GTK project and specifying the path using OnPlatform with the same results.   

### Steps to Reproduce

1. Add a png ("sample.png") to the "drawables" folder in the Android project.
2. Add a png ("sample.png") to the root folder of the GTK project.
3. Create an Image on a ContentPage in the main project, set "Source=sample.png".

### Expected Behavior
Image renders for both Android and GTK builds

### Actual Behavior
Image renders on Android build but not on GTK build

### Basic Information

- IDE: Visual Studio 16.3.5
- Nuget Packages: Xamarin.Forms.Platform.GTK version=4.3.0.947036 
- Affected Devices: Linux device

**Comment by yurkinh** [comment]
@B-Simms  Could you provide some repro sample?

**Comment by B-Simms** [comment]
I'll try to put something together that replicates the project's settings. I can't share the actual project as it's under NDA, but I'll try to come up with something this afternoon.

**Comment by VladislavAntonyuk** [comment]
Set png file properties to copy to output directory

**Comment by jfversluis** [comment]
No repro and no response so I guess this is resolved by now :)
