### ISSUE TITLE
[Bug] Hot reload works incorrectly for buttons with long text on Android

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#10210]
### Description

The bug is shown on the GIF below:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17653648/78503693-85019900-7768-11ea-908e-eac32ef13f46.gif)

After Hot Reload the button resizes incorrectly splitting the text into multiple lines.

### Steps to Reproduce

1. Run this project.
[ButtonWidthAndroid.zip](https://github.com/xamarin/Xamarin.Forms/files/4434286/ButtonWidthAndroid.zip)
2. Change the text of the button.
3. After Hot Reload the button resizes incorrectly.

### Expected Behavior
The button should resize correctly.

### Actual Behavior
The button resizes incorrectly.

### Basic Information

- Version with issue: 4.5.0.530
- IDE: Visual Studio for Mac 8.4.8
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by vincentcastagna** [comment]
Think this is duplicate and/or related to https://github.com/xamarin/Xamarin.Forms/issues/10102

**Comment by rmarinho** [comment]
duplicated of #10102
