### ISSUE TITLE
Disaster! VS is ruining y Xamarin Form or the other way!

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#10219]
Hi,

Since the past upgrade of VS and Xamarin Form, when my VS forced to close due to battery problem or windows shutdown then my Android, iOS and UWP and unloaded and cannot reload it.

my csproj becomes empty

and my csproj.user is like this:

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <SelectedDevice>my_pixel_xl</SelectedDevice>
    <DefaultDevice>my_pixel_xl</DefaultDevice>
  </PropertyGroup>
</Project>

```

**Comment by samhouts** [comment]
@jrahma Please report this via Visual Studio send feedback. Thanks!
