### ISSUE TITLE
[Bug] .Net Foundation link in README gives 404

### ISSUE THREAD

**Issue by paul-charlton** [xamarin/Xamarin.Forms#10215]
### Description
In the readme.md file, the link to .NET Foundation (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) under coding style is dead and goes to 404.

### Steps to Reproduce
Click the link

**Comment by jfversluis** [comment]
Thanks for letting us know! Opened a PR to fix it :)
