### ISSUE TITLE
[Bug] [iOS] Null Reference Exception Refresh View v4.6.0 pre 3

### ISSUE THREAD

**Issue by dsdilpreet** [xamarin/Xamarin.Forms#10213]
### Description
Application crashes if the XAML (page) contains refresh view on iOS12.4 devices and simulators. The problem does not seem to be there when using iOS 13.4 or Android

### Steps to Reproduce

1. Open the attached project in Visual Studio 2019
2. Run it on iOS v12.4 simulator
3. The application should crash at launch time

### Expected Behavior
Application should not crash

### Actual Behavior
App crashes on page if `<RefreshView>` is used on that page on iOS v12.4

### Basic Information

- Version with issue: 4.6.0.529-pre3
- Last known good version: 4.5.0.396
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  12.4

- Affected Devices:
iPhone 6

### Screenshots

![image](https://user-images.githubusercontent.com/11010830/78514362-0444aa80-7805-11ea-8de9-8f7857ca40a8.png)

### Reproduction Link

https://github.com/dsdilpreet/Xamarin_Forms___RefreshView_Demo_Problem_Version

**Comment by rmarinho** [comment]
HI, this is fixed in pre4, we are releasing this week.
