### ISSUE TITLE
[Bug] Expander + CollectionView: Expander content keeps reopening

### ISSUE THREAD

**Issue by Reveon** [xamarin/Xamarin.Forms#10229]
### Description
While playing around with the new Expander control in the CollectionView I found an issue where the item keeps reopen when IsExpanded property is set to true. 

### Steps to Reproduce

1. Run the repro sample
2. Expand one item and scroll down and up back to the expanded item.

### Expected Behavior
Items should respect "IsExpanded" property and should stay in an open state even when scrolled off the screen and then back.

### Actual Behavior
Expanded item is being reopend when scrolled off the screen and then back to it.

### Basic Information

- Version with issue: 4.7.0.578 nightly
- Last known good version: -
- IDE: VS 2019 15.5.2
- Platform Target Frameworks: 
  - Android: Android 10 emulator

### Screenshots

When an item is expanded and then the list is scrolled down and then back to the item that was expanded then this item is being reopened.

![itemreopens](https://user-images.githubusercontent.com/29383312/78601137-88724e80-7854-11ea-8c7d-39a4ee52cd07.gif)

### Reproduction Link

[ExpanderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4440579/ExpanderTest.zip)

**Comment by AndreiMisiukevich** [comment]
On **iOS** is even worse.

![Apr-08-2020 00-25-41](https://user-images.githubusercontent.com/10124814/78721073-88934c80-792f-11ea-8cc0-31d33cbb0749.gif)
