### ISSUE TITLE
[Enhancement] CarouselView: Option to set the number of pre rendered itens

### ISSUE THREAD

**Issue by movisis** [xamarin/Xamarin.Forms#10225]
## Summary
If no PeekAreaInsets is defined, the carousel only renders on item at a time.
If one have a carousel of images, the loading from the internet only occurs when the user starts swiping.
It should have a way to tell how many itens, in advance, it should load in memory, so it would be smoother to the user to swipe, and no loading.

I'm also using carouselView to slide between 4 content views.
Each one has its own controls and logical stuff.
I would also use this feature here, where it would make all views load in memory, so the transition would be very smooth.

In android, the component ViewPager has a property called: setOffscreenPageLimit(5);
There, I can achieve this behavior.

## API Changes

Create a property to tell how many itens could be pre-rendered.
So, when we have a few itens, all of them could be loaded once, so, sliding would be very smooth.

int OffScreenLimit = 0;
    var carousel = new Xamarin.Forms.CarouselView ();
    carousel.OffScreenLimit = 3; // new API
## Intended Use Case
One simple case would be to load in advance photos from the internet.
When set to 3, the current image + next 3 would be already loaded.
When swiping to the next one, the next picture would be loaded.

In a collection of views, they would be pre-rendered for smooth experience.

**Comment by rmarinho** [comment]
Hi, i understand the request, but you could do a Service that grabs those images and cache them. When you will need to grab the image they are already on your own control.

**Comment by movisis** [comment]
Hi.

You're right. Considering only the image part, I could do it ,as you said.
But I'm also using carouselView, to swipe between a collection of some "ContentView"'s.

Each one, when rendered for the first time, take a time to get ready.
So, even If I get the images in advance, still won't be smooth enough.

If I set some peek area inset, The visible item and the next one get ready from the start.
But sometimes one doesn't want that margin or showing partial itens.

If there was this option, I guess it would be much easier for developers. 
And it isn't something I created. It is based on a process that already works in android.
I know that we can't compare everything, because of different ways each system works to render stuff.

But I think it would be a major upgrade, since a lot of people could take advantage of it.

Just to explain better why I'm using carousel, for a collection of content views:
- I'm using it to have a similar experience the tabbed page has, but not for the main page.
In one point of the app, the user can slide between those contentViews. 
Each one with their own components and rules.
How I did it:

`public class Rotator
    {
        public class ViewItem
        {
            public View src { get; set; }
            public int position { get; set; }
        }

        public class ViewItemTemplateSelector : DataTemplateSelector
        {
            private List<DataTemplate> templates = new List<DataTemplate>();

            public ViewItemTemplateSelector(List<ViewItem> views)
            {
                foreach (var item in views)
                {
                    DataTemplate template = new DataTemplate(() =>
                    {
                        return item.src;
                    });
                    templates.Add(template);
                }
            }

            protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
            {
                ViewItem v = (ViewItem)item;
                return templates[v.position];
            }
        }

        public Xamarin.Forms.CarouselView carousel;
        private List<ViewItem> views;

        public Rotator(List<ViewItem> _views)
        {
            views = _views;

            carousel = new Xamarin.Forms.CarouselView();

            int x = -1;
            foreach (var item in views)
            {
                x++;
                item.position = x;
            }

            carousel.ItemTemplate = new ViewItemTemplateSelector(views);
            carousel.ItemsSource = views;
        }
    }`

How to use it?
`.          //Initializing the collection
            List<Rotator.ViewItem> views = new List<Rotator.ViewItem>();

            //adding contentViews
            views.Add(new Rotator.ViewItem() { src = listaAge } );
            views.Add(new Rotator.ViewItem() { src = gestaoOficina });

            //intantiate
            Rotator rotator = new Rotator(views);
            //adding the content to the mainView
            gridContent.Children.Add(rotator.carousel);`

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
