### ISSUE TITLE
[Bug] Forms app no longer recognizes taps on controls after Visual Studio upgrade

### ISSUE THREAD

**Issue by JohnLivermore** [xamarin/Xamarin.Forms#10220]
### Description

I just upgraded VS to 16.5.2.  This then necessitated a need to upgrade my MacOS to the latest version (Catalina) with XCode 11.4.  Now when I run the simulators, I get no response from tapping a collection view list item nor a tap gesture recognizer on a label.  Buttons seem to work.

I upgraded XF to 4.5.0.530 from 4.4, and that has not solved the issue.

Here is my setup.  

![image](https://user-images.githubusercontent.com/1489667/78564717-7b1c7c00-77e2-11ea-8442-c1737cecd9c7.png)

### Steps to Reproduce

1. Install VS 16.5.2 with Mac Catalina and XCode 11.4.

**Comment by rmarinho** [comment]
duplicated #10162
