### ISSUE TITLE
[Bug] Expander + CollectionView: padding and margin issues

### ISSUE THREAD

**Issue by Reveon** [xamarin/Xamarin.Forms#10230]
### Description
While playing around with the new Expander control in the CollectionView I found out that when there is padding or margin set on the first item inside DataTemplate some issues appear.

Xaml example:
```                   
<Expander.ContentTemplate>
       <DataTemplate>
             <Grid Padding="40">
                 .....
             </Grid>
       </DataTemplate>
</Expander.ContentTemplate>
```

### Steps to Reproduce

1. Run attached repro sample
2. Add different values for Padding or Margin for the first item in DataTemplate and see issues described bellow

### Expected Behavior
Padding or margin do not affect animation or height of the expander content when the Expander is used in the CollectionView

### Actual Behavior
Padding and margin values have an impact on animation and expander item height in CollectionView 

### Basic Information

- Version with issue: 4.7.0.578 nightly
- Last known good version: -
- IDE: VS 2019 15.5.2
- Platform Target Frameworks:
  - Android: Android 10 emulator

### Screenshots
1) When an item is expanded and then the list is scrolled down and then back to the item that was expanded then the previously opened item is now being "reopened #10229 " and has different height. It seems to be a random value in the range of provided padding or margin.

![item_random_height](https://user-images.githubusercontent.com/29383312/78603014-af7e4f80-7857-11ea-880d-d431ef31e4e1.gif)

2) Expand and Collapse animations are being cut off. Again the value of padding or margin has direct impact on that.

![ExpCollView_AnimationPaddingSkip](https://user-images.githubusercontent.com/29383312/78603200-fc622600-7857-11ea-90b4-402a79749e33.gif)

3) When an item is expanded then random items are being opened and closed while quickly scrolling the list. This happens only if there is padding or margin
![items randomly opening](https://user-images.githubusercontent.com/29383312/78603383-55ca5500-7858-11ea-90b5-59f58d24abbf.gif)

### Reproduction Link
[ExpanderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4440697/ExpanderTest.zip)

**Comment by Huaba93** [comment]
There are some measurement problems of the CollectionView.
I haven't tested it, but wrapping the Expander with a ContentView could might be a workaround for the moment. 

Do you see the same behaviour using a BindableLayout?

**Comment by Reveon** [comment]
Bindable layout does not randomly open or reopen items but I still see animation cut off when I set Padding. 
Wrapping the Expander with a ContentView helped with the animation cut off for both BindableLayout and CollectionView but other issues are still present for CollectionView.

**Comment by AndreiMisiukevich** [comment]
Hm, I think we can keep internal ContentView if it helps

**Comment by pmahend1** [comment]
I have similar issue had raised here https://github.com/AndreiMisiukevich/ExpandableView/issues/36

**Comment by Reveon** [comment]
@AndreiMisiukevich  I tested 4.6.0.616-pre4 which includes your fix for Expander Content reopeing and it works fine now. Thanks, this control is an awesome addition to Xamarin.Forms. 

As for the random height - I did some more testing and it is happening also when opening other items in CollectionView.

But I think that your last PR #10283  might fix these 
```
                    <Expander.ContentTemplate>
                        <DataTemplate>
                            <ContentView>
                                <StackLayout BackgroundColor="LightCoral"
                                             HeightRequest="200">

                                    <Label BackgroundColor="Green"
                                           HeightRequest="100"
                                           Text="{Binding ID}" />
                                </StackLayout>
                            </ContentView>
                        </DataTemplate>
                    </Expander.ContentTemplate>
```
Random height issues (no padding or margin, just HeightRequest):

![RandomHeight2](https://user-images.githubusercontent.com/29383312/78978628-70cbec00-7b1a-11ea-90dc-388ace2904cb.gif)

And some other example with padding

![ExpanderRandomHeight](https://user-images.githubusercontent.com/29383312/78979018-44649f80-7b1b-11ea-8034-9870694f3e27.gif)

**Comment by Reveon** [comment]
Also I noticed that sometimes there is flickering when an item is expaning. In this case I don't think that Padding or margin has an impact on this, because it is happeing even when there is padding or margin. And sometimes it seems that the Animation is skipped. Again I see all this only in CollectionView.

```
                    <Expander.ContentTemplate>
                        <DataTemplate>
                            <ContentView>
                                <StackLayout BackgroundColor="LightCoral">
                                    <Label Margin="20"
                                           BackgroundColor="Green"
                                           Text="{Binding ID}" />
                                </StackLayout>
                            </ContentView>
                        </DataTemplate>
                    </Expander.ContentTemplate>
```
![Flickering](https://user-images.githubusercontent.com/29383312/78979933-24ce7680-7b1d-11ea-8e2f-f7d831cbe4f5.gif)
