### ISSUE TITLE
[Bug] Embedded Fonts not rendering with FontImageSource in iOS

### ISSUE THREAD

**Issue by jjchiw** [xamarin/Xamarin.Forms#10248]
### Description

Using Embedded Fonts to be used as FontImageSource

```
<Image>
  <Image.Source>
    <FontImageSource
      FontFamily="FontAwesome"
      Glyph="&#xf584;"
      Color="Black" />
  </Image.Source>
</Image>
```

### Expected Behavior

The FontIcon should be displayed

### Actual Behavior

The FontIcon doesn't display correctly in iOS

### Basic Information

- Version with issue: 4.5.0.530
- Platform Target Frameworks:
  - iOS:  13.4
- Nuget Packages:
  - Xamarin.Forms 4.5.0.530
- Affected Devices:
  - iOS

### Screenshots

![image](https://user-images.githubusercontent.com/642319/78723445-b9718280-792b-11ea-9279-96b02e9b4a00.png)

### Reproduction Link

https://github.com/jjchiw/EmbeddedFontsSample/tree/test/embedded_font_as_font_image_source

**Comment by jfversluis** [comment]
Hey there, thanks for the report! Looks like this might be the same as #10226.

Could you maybe pull down the NuGet from the PR that is linked in that issue and see if that fixes this for you?

**Comment by jjchiw** [comment]
Not really sure how to pull down de NuGet from the PR :/

I added the nuget repo of nightly builds 

(4.7.0.597-nightly)
![image](https://user-images.githubusercontent.com/642319/78727581-51c03500-7935-11ea-947a-5783cc06dbf2.png)

(4.6.0.369-nightly)
![image](https://user-images.githubusercontent.com/642319/78727660-8e8c2c00-7935-11ea-89ca-f71f86fd27c3.png)

And it's not the same issue, I downloaded the Sample Project to reproduce from https://github.com/xamarin/Xamarin.Forms/issues/10226 and it's not using FontImageSource in all the samples

**Comment by jfversluis** [comment]
Downloaded the fix from the referenced PR but that does not fix this issue unfortunately.

**Comment by wagenheimer** [comment]
I also wasn't able to use Embedded Fonts with FontImageSource on Android.
It fails with error "java.lang.IllegalArgumentException: width and height must be > 0"

It works OK for texts on labels.

**Comment by dhindrik** [comment]
For me it is working if I also add a label on the same page that uses the embedded font:
![Screen Recording 2020-04-20 at 13 53 07](https://user-images.githubusercontent.com/6691971/79749779-126bee00-8310-11ea-8415-42044f5e9aa4.gif)

My code can be found here: https://github.com/dhindrik/EmbeddedFontsBug

**Comment by Csaba8472** [comment]
Hello, I tried XF 4.6 pre-4 and it doesn't solve the issue. What I'm trying to do is to set FontImageSource as Tab.Icon. The interesting thing is if hot reload reloads the view the correct icon is shown.

**Comment by WebDucer** [comment]
I have the same problem on iOS. The font icons works in Labels, but not as FontImageSource (tested in ToolbarItem, Image and SfButton from Syncfusion). Android works without problems.

Used:
- XF 4.6.0.726
- XF.Essentials 1.5.3
- Syncfusion 18.1.0.48

**Comment by stefancvetkovic** [comment]
Hi to all,
I have problem with my hamburger menu (ShellContent) as @wagenheimer described. Label is ok, but ShellContent shows just blank space?

**Comment by ricavir11** [comment]
I'm having same issue on iOS devices for tabbedpage icons.
I've tested with XF 4.6.0.847 and XF 4.7.0.1080.
![image](https://user-images.githubusercontent.com/25507232/87320797-ac1bf380-c52b-11ea-9d61-639de47cf5c3.png)

Android devices are Ok :
![image](https://user-images.githubusercontent.com/25507232/87320836-ba6a0f80-c52b-11ea-9021-7a0da686f187.png)

@samhouts : can you please fix this issue ?

**Comment by ricavir11** [comment]
@samhouts : would it be possible to have a fix for 4.8.0 milestone ?

**Comment by ricavir11** [comment]
> I'm having same issue on iOS devices for tabbedpage icons.
> I've tested with XF 4.6.0.847 and XF 4.7.0.1080.
> ![image](https://user-images.githubusercontent.com/25507232/87320797-ac1bf380-c52b-11ea-9d61-639de47cf5c3.png)
> 
> Android devices are Ok :
> ![image](https://user-images.githubusercontent.com/25507232/87320836-ba6a0f80-c52b-11ea-9021-7a0da686f187.png)
> 
> @samhouts : can you please fix this issue ?

I've found a workaround :
- Add your font file in your shared project as embedded ressource

- Register your font in your app.xaml : 
`[assembly: ExportFont("iconize-fontawesome-solid.ttf", Alias = "FontAwesomeSolid")]`

- Then set your icon in your XAML or C# file : example below for a tab icon in C#
`menu.IconImageSource = new FontImageSource { FontFamily = "FontAwesomeSolid", Glyph = "\uf0c9", Size = 25 };`

**Comment by rachelkang** [comment]
Closing now as this is no longer an issue! It's been fixed in later versions of XF so please update if you haven't already :)
