### ISSUE TITLE
CollectionView Enhancement for ScrollTo: Bindable ScrollTo

### ISSUE THREAD

**Issue by koddek** [xamarin/Xamarin.Forms#10254]
## Summary
In CollectionView, I want to be able to bind to "ScrollTo", so that when the view loads the ItemSource, it automatically scrolls to the bounded item.

## API Changes

These properties would be needed on the CollectionView (Or something similiar)

```csharp
public object ScrollToItem { get; set; }
public int ScrollToIndex { get; set; }
public ScrollToPosition ScrollToPosition { get; set; }
```
## Intended Use Case
```xaml
< CollectionView ScrollToItem="{Binding Item}" ScrollToPosition="{Binding Position}" .. />
< CollectionView ScrollToItem="{Binding Item}" ScrollToPosition="Center|End|MakeVisible|Start" .. />   

< CollectionView ScrollToIndex="{Binding Index}" .. />   
< CollectionView ScrollToIndex="5" .. />
```
---
Update:
## Even better name, which is closer to what's already in the api.
```cs
public object KeepItemInView { get; set; }
public int KeepItemAtIndexInView { get; set; }
public ScrollToPosition ScrollToPosition { get; set; }
```
## Usage
```xaml
<CollectionView KeepItemInView="{Binding Item}" ScrollToPosition="{Binding Position}" .. />
<CollectionView KeepItemAtIndexInView="35" ScrollToPosition="Center" .. />
```

**Comment by rmarinho** [comment]
On CarouselVIew you can bind to a Position, do you think that will would help you with what you need?

**Comment by koddek** [comment]
> On CarouselVIew you can bind to a Position, do you think that will would help you with what you need?

I don't think so. 
I have a Page with a CollectionView of items that I want to load. I want to set the item that I want to be centered on screen from my ViewModel, so when the page is loaded, the item is displayed in the center of the screen. (or just make the item visible on-screen)

**Comment by koddek** [comment]
## My hacky attempt at a custom CollectionView to display the wanted functionality.
For this to work the way I want, I first go to the page with the CollectionView and await its return, then set the ScrollToItem/ScrollToIndex property.

```cs
public class CollectionViewEx : CollectionView
{
    public static readonly BindableProperty ScrollToItemProperty =
        BindableProperty.Create(
            nameof(ScrollToItem),
            typeof(object),
            typeof(CollectionViewEx),
            default);

    public static readonly BindableProperty ScrollToIndexProperty =
        BindableProperty.Create(
            nameof(ScrollToIndex),
            typeof(int),
            typeof(CollectionViewEx),
            default);

    public static readonly BindableProperty ScrollToSereenPositionProperty =
        BindableProperty.Create(
            nameof(ScrollToSereenPosition),
            typeof(ScrollToPosition),
            typeof(CollectionViewEx),
            default);

    public object ScrollToItem
    {
        get => GetValue(ScrollToItemProperty);
        set => SetValue(ScrollToItemProperty, value);
    }

    public int ScrollToIndex
    {
        get => (int)GetValue(ScrollToIndexProperty);
        set => SetValue(ScrollToIndexProperty, value);
    }

    public ScrollToPosition ScrollToSereenPosition
    {
        get => (ScrollToPosition)GetValue(ScrollToSereenPositionProperty);
        set => SetValue(ScrollToSereenPositionProperty, value);
    }

    protected override void OnPropertyChanged(string? propertyName = null)
    {
        base.OnPropertyChanged(propertyName);

        if (propertyName is nameof(ScrollToItem))
        {
            SelectedItem = ScrollToItem;
        }
        else if (propertyName is nameof(ScrollToIndex) && (List<object>)ItemsSource is { } items)
        {
            SelectedItem = items[ScrollToIndex];
        }

        if (SelectedItem is { })
            ScrollTo(SelectedItem, position: ScrollToSereenPosition, animate: false);
    }
}
```

**Comment by rmarinho** [comment]
Like you have showed here , it seems a user can implement this with just a little bit of code, we don't think at this feature will be super useful to add to the control because we have the ScrollTo method, there's no much people asking for it.

**Comment by g4mb10r** [comment]
I would like this feature, please!

**Comment by koddek** [comment]
> Like you have showed here , it seems a user can implement this with just a little bit of code, we don't think at this feature will be super useful to add to the control because we have the ScrollTo method, there's no much people asking for it.

OK, I understand. Well the code I wrote here feels hacky/bad, maybe can someone show a better way to enable binding to ScrollTo from your ViewModel?

**Comment by koddek** [comment]
> because we have the ScrollTo method,

That's the whole reason I asked for the feature in the first place, it is because the ScrollTo method has to be used from the View's code-behind. Most people want to do all their logic in the ViewModel. There's no easy way to reference the CollectionView (or any View) from the ViewModel to allow access to the ScrollTo method.

It would be nice to be able to reference the controls with names from the ViewModel just like you can from the code-behind. Like if I named a control ``x:Name="peopleCollectionView"`` be able to call ``peopleCollectionView.ScrollTo`` inside the ViewModel. This would allow so many possibilities.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
