### ISSUE TITLE
Labelcolor doesn't work with MacOS [Bug] 

### ISSUE THREAD

**Issue by linuskirschbaum** [xamarin/Xamarin.Forms#10256]
Not all labels adopt the text color when debugging. As soon as you change something on a label with a live reload, everything will be correct again. 

Plattform: MacOS 
IDE: VS for Mac 

![Bildschirmfoto 2020-04-08 um 11 00 52](https://user-images.githubusercontent.com/61834268/78765561-74c80480-7988-11ea-8f79-305bc37c7f65.png)

![Bildschirmfoto 2020-04-08 um 11 00 09](https://user-images.githubusercontent.com/61834268/78765535-6da0f680-7988-11ea-9c77-51425945f10e.png)

**Comment by rmarinho** [comment]
Hi @linuskirschbaum  can you please give us  more information, we do provide a Issue template so you can specify things like version, ide etc.. 
Please provide also a small repo that could helps more easily identify the problem.

Thanks

**Comment by linuskirschbaum** [comment]
I created a new project for Git and pasted the page with copy past. Unfortunately, the error is no longer there, although everything is the same .... In both projects are the nugets up to date and accordingly the same version.

**Comment by linuskirschbaum** [comment]
The problem is that the bug cannot be solved in the right project and the bug is still there.
