### ISSUE TITLE
[Bug] TimePicker TextColor not working on Android

### ISSUE THREAD

**Issue by gmwilhelm** [xamarin/Xamarin.Forms#10257]
### Description

If a TextColor is specified for a normal, nonmaterial TimePicker the text color is not set.
If the TimePicker is enabled, the color is always black.
If it is disabled, it is always grey.

### Steps to Reproduce

 Define a TimePicker in Xaml:

```
<TimePicker
  IsEnabled="True"
  Time="{Binding TerminZeit}" 
  BackgroundColor="AliceBlue"
  TextColor="Blue">
  <TimePicker.Format>HH:mm</TimePicker.Format>
</TimePicker>
```

### Expected Behavior

Both BackgroundColor and TextColor should be set.

### Actual Behavior

The TextColor is not set.
If the TimePicker is enabled, the color is always black.
If it is disabled, it is always grey.

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: unknown
- IDE:
- Platform Target Frameworks: 
  - Android: TargetSDK 28
- Nuget Packages: Xamarin.Forms 4.5.0.530
- Affected Devices: Android

### Screenshots

![timepicker](https://user-images.githubusercontent.com/14111141/78770927-9e385e80-798f-11ea-904f-dd2318227ad4.PNG)

The screenshot shows a disabled datepicker with the TextColor set to blue and an enabled TimePicker with a working BackgroundColor (AliceBlue) and a non-working TextColor (Blue)

**Comment by rmarinho** [comment]
Hi, i can reproduce this issue, i used this code :

```
<StackLayout>
        <TimePicker
            IsEnabled="False"
            Time="{Binding TerminTime}" 
            BackgroundColor="AliceBlue"
            TextColor="Blue">
            <TimePicker.Format>HH:mm</TimePicker.Format>
        </TimePicker>

        <TimePicker
            IsEnabled="True"
            Time="{Binding TerminTime}" 
            BackgroundColor="AliceBlue"
            TextColor="Blue">
        <TimePicker.Format>HH:mm</TimePicker.Format>
    </TimePicker>
    </StackLayout>
```

![image](https://user-images.githubusercontent.com/1235097/78809921-8b3d8280-79bf-11ea-8492-a7982689a81f.png)

**Comment by gmwilhelm** [comment]
Turns out i had a custom renderer for the TimePicker on Android, although i can't remember why i added it. 

After removing the custom renderer all works as expected.
