### ISSUE TITLE
[Bug] UWP - Editor needs focus for text to be visible within a ScrollView

### ISSUE THREAD

**Issue by apolloLegends** [xamarin/Xamarin.Forms#10266]
### Description
UWP Editor now needs to have focus to see text.

### Steps to Reproduce

1.  Launch attached project for UWP and note the missing text
2.  Launch the attached project for iOS/Android and note the text is visible

### Expected Behavior
The Entry text "This is shown if using Xamarin Forms 4.2.0.910310" is shown under the label 
![image](https://user-images.githubusercontent.com/34690463/78815531-6684e300-799e-11ea-8866-33eab7143a7a.png)

### Actual Behavior
UWP
The Entry control does not show any text until the user focuses on the control

![image](https://user-images.githubusercontent.com/34690463/78815398-38070800-799e-11ea-890e-d065e2c15989.png)

iOS and Android displays the text.

### Basic Information

- Version with issue: 4.3.0.908675, 4.5.0.530 (most likely anything > 4.2.0.910310 but didn't check them all)
- Last known good version: 4.2.0.910310
- IDE: Visual Studio 2019 For Windows
- Platform Target Frameworks: 
  - iOS:  Deployment Target is 8.0
  - Android: 9.0
  - UWP:  16299 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials 1.3.1, .NET StandardLibrary 2.0.3
- Affected Devices: 

### Workaround

Do not wrap the Entry control within a ScrollView.

**Comment by apolloLegends** [comment]
Whoops forgot to upload project.
[EditorNowNeedsFocusToSeeText.zip](https://github.com/xamarin/Xamarin.Forms/files/4451987/EditorNowNeedsFocusToSeeText.zip)

Also note, this appears similar to https://github.com/xamarin/Xamarin.Forms/issues/10137

**Comment by rmarinho** [comment]
duplicated #10137
