### ISSUE TITLE
[Enhancement] Use MasterDetailPages inside TabbedPages.

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#10262]
## Summary
I have a mobile app which uses a TabbedPage as the top-level navigation, and want to now optimise the use of extra space inside the tabs when viewed on desktop and tablet by using MasterDetailPages (in Split mode) inside the tabs exactly like the layout [here](https://stackoverflow.com/questions/54430692/implement-a-master-detail-page-inside-a-tabbed-page-in-xamarin-forms-with-prism?) Something like:
`//TabbedPage/MasterDetailPageforTab1`
`//TabbedPage/MasterDetailPageforTab2`
`//TabbedPage/MasterDetailPageforTab3` 

But according to the Xamarin [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page)
 "A MasterDetailPage is designed to be a root page, and using it as a child page in other page types could result in unexpected and inconsistent behaviour." 

I tried it anyway and it seems to work so far, but I don't want to go against the recommendation in the docs. I'm not clear from the docs if this is not fully supported, or not recommended from a design perspective or both. 

## Intended Use Case
For apps that use Tabs for their top-level navigation but want to optimise the use of space within each tab on Desktop and tablet.

**Comment by samhouts** [comment]
@HelenMamalaki Have you tried Shell? It might give you the layout you need, and it's definitely supported!

**Comment by ahoefling** [comment]
I can confirm that this does work both for MasterDetail/Tabbed Pages approach and Xamarin.Forms Shell. We have been using this technique since shell was initially released last year.

**Comment by HelenMamalaki** [comment]
@samhouts @ahoefling Thank you for your quick replies and suggestions. Unfortunately I am using Prism and it doesn't look like it supports Shell. But regardless the Shell documentation says that "The flyout is the root menu for a Shell application...with the next level of navigation being the tabbed bar", which sounds like the same problem of the MasterDetailPage can only ever be a root page? I want a different (splitview/ dual page layout) for each tab, so the Tabs must be the root page like TabbedPage/MasterDetailPageforTab1 | TabbedPage/MasterDetailPageforTab2

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
