### ISSUE TITLE
RowDefinition's Opacity

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#10267]
Hi,

Please add Opacity to the RowDefinition

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by GalaxiaGuy** [comment]
I assume the intention is for this to apply to elements assigned to that row? What would you expect to happen to elements that span several rows?

**Comment by rmarinho** [comment]
Hi we don't think this is a feature that we want to add. Seems a user can easily implement this and is not a feature that is not requested by a lot of users.
