### ISSUE TITLE
[Bug] Icons are not showing when bundling assemblies into native code (Android)

### ISSUE THREAD

**Issue by ManuLin** [xamarin/Xamarin.Forms#10260]
### Description

We are developing a Xamarin.Forms application and are facing the following issue on Android: When deploying the application in release mode with the "BundleAssemblies" setting set to "true", all icons in our application (e.g., tool bar item icons, button icons) disappear. I am not entirely sure, but somehow this issue seems to be related to the AndroidX packages required for building, as we didn't experience this issue with previous releases (e.g. Xamarin.Forms 4.2.0.848062). I have also attached a simple sample app to reproduce this issue for further investigation. Any help appreciated.

### Steps to Reproduce

1. Define a button, an image or a toolbar item in XAML

     `<ToolbarItem Text="Add" IconImageSource="icon.png" Order="Primary" Priority="0" />`
     `<Button Text="Test" TextColor="White" BackgroundColor="DarkGray" ImageSource="icon.png"/>`
    `<Image WidthRequest="30" HeightRequest="30"  Source="icon.png"/>`

2. Deploy the application with the following release settings:

![Capture](https://user-images.githubusercontent.com/18525713/78780369-c4192f80-799e-11ea-8e2e-07ec4fbcaae0.PNG)

### Expected Behavior

All elements should display the specified icon source.

### Actual Behavior

All elements show only the specified text (or nothing, in case of the image).

### Basic Information

- Version with issue: 4.5.0.530 (but it appears also in 4.4.*)
- Last known good version: 4.2.0.848062
- IDE: Visual Studio Enterprise 2019, Version 16.5.3
- Platform Target Frameworks: 
  - Android: 10.0 
- Android Support Library Version: 

### Screenshots

[
![Screenshot_20200408_132931_com companyname xfsample](https://user-images.githubusercontent.com/18525713/78779980-33daea80-799e-11ea-8cd2-477a474b3257.jpg)
![Screenshot_20200408_133125_com companyname xfsample](https://user-images.githubusercontent.com/18525713/78779982-34738100-799e-11ea-8135-1d2c5c9039ec.jpg)
](url)

### Reproduction Link

[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/4450213/Sample.zip)

### Workaround

Setting the "BundleAssemblies" setting to false resolves the issue.

**Comment by rmarinho** [comment]
Seems this a duplicated of #9900
