### ISSUE TITLE
Xamarin.Forms Designer IOS and Android Problem

### ISSUE THREAD

**Issue by lpolec** [xamarin/Xamarin.Forms#10272]
### Description
After update VS 2019 from 16.5.2 to 16.5.3, there has some error with the designer occurred.
Testing the same project on Visual Studio 2019 for MAC, version 8.5.2 designer works properly.

### Steps to Reproduce

1. Turn VS 2019,
2. Open Xamarin Forms Project
3. Open the XAML file with view definition then turn the split view in order to see the visual side of Your code.

### Actual Behavior
Error attached

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019 16.5.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/29781333/78864232-84545580-7a3b-11ea-89d0-600cf8c1cfc4.png)

**Comment by rmarinho** [comment]
Hi @lpolec can you give us  a simple repo ?

Does this happen even after building 1 time the project?

**Comment by lpolec** [comment]
I tried to build and rebuild my project and clean as well. Still getting the same error.

**Comment by lpolec** [comment]
I found some bug in my project configuration. Sorry for that.
