### ISSUE TITLE
[Enhancement] Add StyleClass for Span styling

### ISSUE THREAD

**Issue by koddek** [xamarin/Xamarin.Forms#10277]
## Summary
I would like to style my spans using StyleClass instead of the old x:Key way.
As it stands Span does not support StyleClass.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
