### ISSUE TITLE
[Bug] Delete requests fails using Xamarin.forms, succeed on Console App (using the same code)

### ISSUE THREAD

**Issue by rotem-tal** [xamarin/Xamarin.Forms#10273]
### Description
Using REST API to communicate with an online server, the DELETE requests are failing (400 bad request) on a Xamarin.forms app (tested on android simulator and device), but the exact same code succeeds when running on a C# Console App.
Other REST requests (POST and GET) are working as expected (both on the Xamarin and console app)
I've created an example database to demonstrate this bug, the attached code is designed to delete the first entry in the database, the code would automatically create new entries if the database is empty, the request link is hard codded (string variable named dbLink)

### Steps to Reproduce
Note: The attached files contain only modified code, the unmodified auto created (by the IDE) files and code was omitted

1. Create a new Xamarin.forms mobile app (blank template) and a new C# Console App (.NET core)
2. Place the downloaded code files in their respective folders, replacing the auto generated files (MainPage.xaml.cs to the Xamarin project, Program.cs to the Console App project)
3. Change the namespace on both code files to match your own (expected namespaces: App1 (xamarin), ConsoleApp (Console App))
4. Build&Run

### Expected Behavior
OK response code (Displayed as alert on xamarin, printed to console on the console app)
### Actual Behavior
BadRequest displayed on the alert on xamarin
OK printed on console
### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: N/A
- IDE: Visual Studio 2019 for Windows
- Platform Target Frameworks: 
  - Android: 9.0 
- Nuget Packages: Newtonsoft.Json (both)
Nito.AsyncEx (Console App only, required to run an async function from Main)
- Affected Devices: Android

### Reproduction Link

[XamarinBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4454993/XamarinBug.zip)

### Workaround

Delete by any other way (manually, console app etc)

**Comment by samhouts** [comment]
@rotem-tal Xamarin.Forms doesn't affect your HttpClient requests at all, but https://github.com/mono/mono might.

Inspect the requests made to your endpoint via console and compare to the requests from your app to see what the difference may be. It could be that you're missing a required header or the json is not formatted how you might expect.

If you're still experiencing this issue, you can try asking your question on StackOverflow or, if you suspect a bug, try the mono GitHub. Thanks!
