### ISSUE TITLE
[Enhancement] DatePicker to have Place Holder Text

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10270]
## Summary
As a Xamrain forms Developer it would be expected that I could place PlaceHolder text within the textbox element of the date selector at present the user is presented with an empty date picker and thus it requires an extra label control.

This would work like existing xamrain forms controls where it would be shown as ghost text until the user has selected a value and erase itself.

**Actual Behaviour**

At present you have to add a label control to be able to give a description.
```
<Label x:Name="labelFor" Text="Please select Date"></Label>
<DatePicker MinimumDate="{Binding MinDate}"
            MaximumDate="{Binding MaxDate}" />
```

**Expected Result**
```
<DatePicker MinimumDate="{Binding MinDate}"
            MaximumDate="{Binding MaxDate}"        
            PlaceHolderText="Please select Date"  />
```

**Additionally**
I was thinking more on this and would be good also if we had a razor helper tag that would be in the form off.

`<PlaceHolder x:Name="plHolder" For-Control="ControlName" Text="Please select value" />
`
This would just simply be a string value property that would allow the user to set a place holder value for any xaml control that it supports.

**Comment by davidbuckleyni** [comment]
@rmarinho Could I do this feature myself and submit a pull request for it would be a good entry for me I think.

**Comment by rmarinho** [comment]
Sure @davidbuckleyni if you can, please add

PlaceHolder and PlaceHolderColor to be similar to other controls

**Comment by davidbuckleyni** [comment]
@rmarinho do we just work off stable or just last pre release version.

**Comment by rmarinho** [comment]
New features go on master

**Comment by davidbuckleyni** [comment]
Is their documentation on branch naming policy you can share with me ? @rmarinho perhaps a document link.

**Comment by davidbuckleyni** [comment]
I didn’t close this this should be re opened.

**Comment by davidbuckleyni** [comment]
@PureWeen This is the pull request for the above 

https://github.com/xamarin/Xamarin.Forms/pull/10741

Can you assign someone to review please as I see the person gets automatically assigned not been active since the 11 of the month.

**Comment by davidbuckleyni** [comment]
Can someone have a test with this having a few issues cause the date picker doesnt have the hint field having to clear the text field but some odd quirks happening @PureWeen @samhouts  just need a few pointers in right direction. The ios version kinda works can show you want im aiming for.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
