### ISSUE TITLE
Issues when updating to AndroidX with nuget packages

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#10275]
### Description
There seems to be a dependency conflict between xamarin.forms.maps and nuget packages referencing android support libraries (pre AndroidX). I've tried following the instructions and installing specific supportlibraries directly, but nuget fails because other support libraries are also conflicting. I can't get it to work. I'm trying to have this project include the following nuget packages:

Xamarin.Forms 4.5.0.530
Xamarin.Forms.Maps 4.5.0.530
Xamarin.Auth 1.7.0
InTheHand.Forms 1.0.2019.118

There doesn't seem to be a way to make this work while the target framework for android is androidQ. Using a target framework below Q seems to work fine

### Steps to Reproduce

1. Open the attached example project
2. See the error

### Expected Behavior
No version conflicts in support libraries

### Actual Behavior
Version conflicts
![image](https://user-images.githubusercontent.com/7567114/78888423-dd36e480-7a61-11ea-8da3-09fee52db179.png)

### Basic Information

- Version with issue: 4.5.0.530
- Last known good version: any version pre 4.5 or targeting android before Q
- IDE: Visual studio 2019 16.5.2
- Platform Target Frameworks: 
  - Android: Android Q
- Nuget Packages: Xamarin.Forms.Maps and Xamarin.Auth

### Reproduction Link
[ReferenceIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4455751/ReferenceIssue.zip)

**Comment by rmarinho** [comment]
HI, i just tried this on my machine, and i was able to open project and run on my phone without issues.

Did you make sure you cleaned your bin/obj folders just to make sure.

**Comment by rmarinho** [comment]
Oh i m on VS 16.5.3 can you also update that to see if it helps. 

Thanks

**Comment by PaulVrugt** [comment]
@rmarinho I've updated visual studio, same result.

Just to be clear, I'm also able to build and run the code, but the nuget restore fails due to the version conflicts:

NU1107: Version conflict detected for Xamarin.Android.Support.Collections. Install/reference Xamarin.Android.Support.Collections 28.0.0.3 directly to project ReferenceIssue.Android to resolve this issue. 
 ReferenceIssue.Android -> ReferenceIssue -> Xamarin.Forms.Maps 4.5.0.530 -> Xamarin.Android.Support.v4 28.0.0.3 -> Xamarin.Android.Support.Media.Compat 28.0.0.3 -> Xamarin.Android.Support.VersionedParcelable 28.0.0.3 -> Xamarin.Android.Support.Collections (= 28.0.0.3) 
 ReferenceIssue.Android -> ReferenceIssue -> Xamarin.Auth 1.7.0 -> Xamarin.Android.Support.CustomTabs 28.0.0.1 -> Xamarin.Android.Support.Collections (= 28.0.0.1).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.

Does the nuget restore work correctly for you?

Might this be a nuget version issue?

**Comment by jcmanke** [comment]
If you upgrade Xamarin.Android.Support.CustomTabs to 28.0.0.3 the conflict for Collections should resolve itself.

**Comment by PaulVrugt** [comment]
@jcmanke I'm not referencing any version of customtabs. When I try to include the customtabs package, it fails, and it starts complaining about other support library packages that are missing

**Comment by PaulVrugt** [comment]
It seems https://github.com/xamarin/Xamarin.Forms/issues/9755 might be related or the same issue?

**Comment by jcmanke** [comment]
@PaulVrugt It's right there in your error message. Xamarin.Forms.Maps is dependent on version 28.0.0.3 of the support libraries and Xamarin.Auth is dependent on CustomTabs version 28.0.0.1. You need to make sure any and all support libraries you're referencing, implicitly or explicitly, are on the same version, which is not currently the case.

Unfortunately, Maps is stuck referencing the support libraries because the Xamarin wrappers for Google Play Services are lagging behind on version 16.1.0, when they migrated to AndroidX in version 17 which was released in June 2019.

**Comment by PaulVrugt** [comment]
@jcmanke I understand that. 

What I didn't understand is why this was not an issue before the combination XF 4.5 and targeting Android Q. 

However, after checking the dependencies, it turns out that XF Maps 4.5 requires Xamarin.Android.Support.V4 for android Q (10), while it doesn't for android P (9). This is what is causing the different dependency chain when targeting android Q, and what starts the issue. Is there any workaround around this issue? Or are we stuck targeting android P until either Xamarin.Forms.Maps or Xamarin.Auth is updated? And would this means nobody including these two packages is able to migrate to Android Q?

**Comment by jcmanke** [comment]
@PaulVrugt The Android 9 version of Maps is also dependent on Support.v4 28.0.0.3 indirectly through its other support library dependencies. My guess is that the explicit reference for Android 10 was added because despite the replacement of the other support libraries with AndroidX, Xamarin.GooglePlayServices.Basement is still dependent on Support.v4 28.0.0.1.

I wouldn't count on an update to Xamarin.Auth since the repo hasn't been updated in 9 months.

**Comment by PaulVrugt** [comment]
@jcmanke so does that mean I am stuck at android 9 or XF4.4 now?

**Comment by jcmanke** [comment]
@PaulVrugt Last week I was able to upgrade an app that targets Android 10 to Forms 4.5.0. This app uses Firebase which is dependent on Google Play Services so I had some similar struggles. I had to explicitly reference these AndroidX packages to get Xamarin's AndroidX migration tool, and thus my automated build, to work:

- Xamarin.AndroidX.Migration 1.0.1
- Xamarin.AndroidX.Browser 1.0.0
- Xamarin.AndroidX.Legacy.Support.V4 1.0.0
- Xamarin.AndroidX.Lifecycle.LiveData 2.2.0
- Xamarin.Google.Android.Material 1.0.0

**Comment by PaulVrugt** [comment]
I've tried it, but adding the packages you mentioned doesn't help. I guess that I'm stuck until xamarin.forms.maps doesn't include the support libraries anymore

**Comment by PureWeen** [comment]
@PaulVrugt 

1) I would recommend removing Xamarin.Auth it's most likely never going to get updated and to use https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios instead

2) 

Looking at the nuget transitive resolution path
```
ReferenceIssue.Android -> ReferenceIssue -> Xamarin.Auth 1.7.0 -> Xamarin.Android.Support.CustomTabs 28.0.0.1 -> Xamarin.Android.Support.Collections (= 28.0.0.1).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
```

The head needs to be cut off is `CustomTabs`

I added CustomTabs to your android project

```

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.5.0.530" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.2" />
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.3" />
  </ItemGroup>
```

After doing that there are no longer any nuget restore error messages and the app compiles and runs
