### ISSUE TITLE
[Enhancement] Validation Tags Xmarian forms 

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10280]
## Summary
At present there is only model time support for validation it would be good if their was a way to have a validation xaml component much like asp.net validation groups and components.

## API Changes
A Razor tag helper to allow the validation of the front end.

<Validator X:Name="valIdationMessage" Text="This Control is Requried" ValidationType=VlidationEnum.IsRequed Vlaidation-For="txtBox1" ValidationGroup="Regstration"  />

**Actual Beavhour**

At present in order to do validation one must do this at the model level it would be good to be able to do this at the xaml level as well protecting both the front end and the back end from injection attacks.
 
**1. Validation**
This Control would be placed a the top of the xaml tree and allow for the controls messages to be outputted verbose This should be in the form of 

`<Validator ID="RequiredFieldValidator" ErrorMessage=" TextBox3 should not be blank" ControlToValidate="TextBox3" ValidationGroup="ValGroup" />`
`
<Validator ID="DateRangeValidator" ErrorMessage="Date Should be between" ControlToValidate="TextBox3" ValidationGroup="ValGroup" ValidType=ComparisonEnum.Date />`

` <Validator ID="RangeValidator" ErrorMessage="Date Should be between" ControlToValidate="TextBox1"  SecondControlToValidate="TextBox2"  ValidationGroup="ValGroup" Value1=1 Value2=10  ValidType=RangeEnum />`

`**Where**
**RangeEnum
Less Than <
Greater Than >
IsEqualTo =
IsNotEqualTo !=**

<Validator ID="RangeValidator" ErrorMessage="Passswords Should Match" ControlToValidate="TextBox1"  SecondControlToValidate="TextBox2"  ValidationGroup="ValGroup" Value1=1 Value2=10  ValidType=MatchEnum/>

 **Where** 
**MatchEenum.IsEqual
MatchEenum.NotEqual**

2. **Message and Display**

`<ValidationGroup x:Name="lblValidationGroup" GroupName="ValGroup" ValMessage="Please correct the following errors:">`

Validation group would be used in the above control to allow for the displaying of the error messages anywhere on the forms applications this could also be in another for example a notifications popup.

**Comment by AmrAlSayed0** [comment]
Related issue #5524

**Comment by davidbuckleyni** [comment]
> Related issue #5524

This is not really the same that other issues deals with only the styling of controls in relation to this this is a way to show the messages in a managed way.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
