### ISSUE TITLE
[Bug] Button sized incorrectly on Android

### ISSUE THREAD

**Issue by KrisVandermotten** [xamarin/Xamarin.Forms#10290]
### Description

Starting with Xamarin.Forms version 4.4.0.991864, buttons are sized incorrectly on Android.

### Steps to Reproduce

1. Create a new, empty Xamarin Forms application
2. Modify the content of MainPage.xaml as indicated below
3. Use Xamarin.Forms version 4.4.0.991864 or later
4. Run the app on Android

MainPage.xaml:

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:d="http://xamarin.com/schemas/2014/forms/design"
                 xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                 mc:Ignorable="d"
                 x:Class="ButtonBug.MainPage"
                 BackgroundColor="Black">

        <StackLayout>
            <Button
                BackgroundColor="White"
                TextColor="Black"
                CornerRadius="10"
                Padding="20,10"
                FontSize="Medium"
                Margin="20"
                Text="blah bl blah" 
                HorizontalOptions="Center"
                VerticalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage>

### Expected Behavior

![image](https://user-images.githubusercontent.com/273237/78988633-d4addf00-7b31-11ea-87a1-ca2c8ce2f460.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/273237/78988437-33bf2400-7b31-11ea-842c-5337cf54c81e.png)

### Basic Information

- Version with issue: 4.4.0.991864 and later
- Last known good version: 4.4.0.991757
- Platform Target Frameworks:
  - Android: Android 9.0 (Pie)

The issue is visible in the Visual Studio designer, as well as on several physical devices.

### Workaround

No workaround was found.

**Comment by vincentcastagna** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/10102 

To help XF teams, please search if an existing issue is not already filled in ...

**Comment by KrisVandermotten** [comment]
@vincentcastagna That doesn't seem to be the same issue, although they might be related. That issue is about a difference in behavior between version 4.5.0.369 and 4.5.0.494. This issue is about a difference in behavior between 4.4.0.991757 and 4.4.0.991864.
