### ISSUE TITLE
IconImageSource missing features

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10295]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/977786/iconimagesource-missing-features.html)._

---
In a &lt;Shell&gt; the &lt;MenuItem&gt; can have an icon. It has a deprecated field “Icon” and the replacement “IconImageSource”. The problem is the new field is missing some functionality of the old field.

Specifically, for the “Icon” field, you can either specific an icon filename, or glyph. For example, you could do:
&lt;MenuItem Text=“Foo” Icon=&quot;&#128683;&quot; /&gt;

With the new “IconImageSource” this does not work.

---
#### Visual Studio Feedback System on 4/6/2020, 08:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by VladislavAntonyuk** [comment]
You have to create a template for menu item where you can bind iconImageSource value to label text for example.

**Comment by Qythyx** [comment]
Right, that's the bug I'm reporting. It works for binding to Icon, but not when binding to IconImageSource. My template is below. If the first label binds to Icon (and I set the Icon value in the MenuItem) then it works. If I use IconImageSource for both then no icon is shown.

```csharp
	<Shell.MenuItemTemplate>
		<DataTemplate>
			<StackLayout Spacing="0"
						 Style="{DynamicResource StackVerticalNoPadding}">
				<StackLayout Margin="0,10"
							 Padding="{DynamicResource MinimalLeftRight}"
							 Style="{DynamicResource StackHorizontalNoPadding}"
							 VerticalOptions="CenterAndExpand">
					<Label Style="{DynamicResource LabelBody}"
						   Text="{Binding IconImageSource}" />
					<Label Style="{DynamicResource LabelBody}"
						   Text="{Binding Text}" />
				</StackLayout>
				<BoxView BackgroundColor="Black"
						 HeightRequest="1" />
			</StackLayout>
		</DataTemplate>
	</Shell.MenuItemTemplate>
```

**Comment by VladislavAntonyuk** [comment]
```
<DataTemplate x:Key="MenuTemplate">
                <StackLayout
                    Padding="2.5"
                    HorizontalOptions="FillAndExpand"
                    Orientation="Horizontal">
                    <Label
                        Margin="10"
                        FontFamily="FontAwesomeSolid"
                        Text="{Binding Icon}"
                        VerticalOptions="Center"
                        VerticalTextAlignment="Center" />
                    <Label
                        Text="{Binding Text}"
                        VerticalOptions="Center"
                        VerticalTextAlignment="Center" />
                </StackLayout>
            </DataTemplate>
```
```
<MenuItem
        IconImageSource="&#xf188;"
        Text="123" />
```

**Comment by Qythyx** [comment]
You're right that works, thanks. I had assumed I should bind to the `ItemImageSource`. At least the docs should be improved.

**Comment by samhouts** [comment]
Thanks, we'll consider updating the docs.
