### ISSUE TITLE
[Bug] CarouselView needs to check IsScrollAnimated/AnimateCurrentItemChanges/AnimatePositionChanges on UpdateItemSpacing also

### ISSUE THREAD

**Issue by goedware** [xamarin/Xamarin.Forms#10291]
https://github.com/xamarin/Xamarin.Forms/blob/8a458aebef77d6a7b2614cfdb1b3aaadd3396015/Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs#L134

The CarouselView method `UpdateItemSpacing` on Android uses the `ScrollTo` method, but it uses in contrary to the other `ScrollTo` methods not the `AnimateCurrentItemChanges/AnimatePositionChanges` value:
**`animate: Carousel.AnimateCurrentItemChanges`**

I think it needs to use that value here in this methods also.

If you have `IsScrollAnimated `is False and set the initial position on the CarouselView, the CarouselView animates the scroll to this position. If I override the `UpdateItemSpacing `method in a CustomRenderer and do just a single return. The CarouselView inits on the correct position without any animation.

**Comment by jsuarezruiz** [comment]
Thanks for the feedback @goedware.
