### ISSUE TITLE
problems with Buttons in Android

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10294]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/978000/problems-with-buttons-in-android.html)._

---
I described this problem at https://forums.xamarin.com/discussion/180400/android-button-rendering-problems/, but here’s a summary:

Buttons in Android do not render very well by default. They won’t show up at all if I set CornerRadius to anything other than zero. They also will have a fixed width, which causes longer text to wrap such that the button becomes multi-line. Both of these problems are easily fixed by adding a simple CustomButtonRenderer to Android (as described in the link above), but this should not be necessary.

The other problem is that Buttons show an odd short grey bar in the bottom of the button. This bar shows up for about 2 seconds, and then automatically fades away. Unfortunately, it is displayed again under some conditions. I’m not sure exactly what those conditions are.

In my case I have a Label in the same page as my Button. In my viewmodel, I am changing the text of that label every second via a timer that changes the property that label is bound to and then invoking the PropertyChanged event. Every time this happens the grey bar shows up again in the Button. Since that bar is shown for more than 1 second this means it is persistently shown.

I want to emphasize that the Label I’m updating has not direct connection to the Button. It’s very strange that updating the Label has any affect on the Button.

---
#### Visual Studio Feedback System on 4/6/2020, 11:37 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by giuseppenovielli** [comment]
Ok, @samhouts, i create a simply project, that show this problem:

- short grey bar, show on button

Run on Android 10, when scrool collectionview, you can show this gray bar, that disappear after 2 seconds, on every single button.

Please fix this issue!!
Thank you very much!!


![Screenshot_1587231230](https://user-images.githubusercontent.com/42063890/79644816-a2dcee00-81ab-11ea-8053-ce68db564e20.png)


[](url)
[ButtonProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/4497151/ButtonProblem.zip)

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample!. The issue is related with CollectionView and happens with other Views (Labels, etc). Seems to be the same issue as https://github.com/xamarin/Xamarin.Forms/issues/7281

**Comment by giuseppenovielli** [comment]
yes @jsuarezruiz, i confirm, that this issues, sometimes appear also with Labels!

Thanks!!
