### ISSUE TITLE
[Bug]Setting CurrentItem in AppShell.xaml throw exception 

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#10308]
### Description
I have a scenario in which the login status of the user is checked in App.xaml.cs. If the user is loggedIn, the app needs to show different pages according to the user role. Else the user is presented with LoginPage. The simple way to do this is sending a string indicating the page that needs to be presented to the user to AppShell.Xaml.cs. Now in switch case in AppShell Constructor setting the CurrentItem. 
But trying to set CurrentItem throws NullReferenceException. 

### Steps to Reproduce
Try to set CurrentItem in AppShell.Xaml.cs programmatically.  

### Expected Behavior
The CurrentItem should be set and page  presented to  the user.
### Actual Behavior
The Systeml.NullReferenceException is thrown and the app crashes
### Basic Information

- Version with issue:Xamarin.Forms 4.5.0.617

- Affected Devices:

### Reproduction Link
[ShellNavigationSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4466218/ShellNavigationSample.zip)

**Comment by PureWeen** [comment]
@HobDev !!

This is a great one for us to fix!! 

This should hopefully be released with 4.6.0 or at least 4.6.0 SR1
https://github.com/xamarin/Xamarin.Forms/pull/10418

Thank you for all the great Shell comments and issues

**Comment by HobDev** [comment]
@PureWeen Shell is so awesome. Developer just need to declare the App Structure. All the underlying code is taken care by the Xamarin Framework. 
I wish this will be fixed in 4.6.0. Than I can use it in my project soon.

**Comment by HobDev** [comment]
Wow! it's done. **Hooray**
