### ISSUE TITLE
[Bug] [Android] Pre-release version of Xamarin Forms forgets cookies

### ISSUE THREAD

**Issue by steverichey** [xamarin/Xamarin.Forms#10318]
### Description

We have an application that presents content in web views within the application. We authenticate requests for content using a cookie. As of the latest pre-release for Xamarin Forms (which we are using for various other bug fixes) we have noticed that this authentication cookie will vanish when loading content. This appears to be the result of changes in [this](https://github.com/xamarin/Xamarin.Forms/pull/8169/files) pull request.

### Steps to Reproduce

1. Send a JWT to a server endpoint to retrieve an authentication cookie
2. Attempt to load content requiring authentication using this cookie

### Expected Behavior

Content loads as normal, as the user has a valid session cookie.

### Actual Behavior

The user is redirected to the login screen, as no valid session cookie exists.

### Basic Information

- Version with issue: 4.6.0.529-pre3
- Last known good version: I believe we were using 4.5 with no issue
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28

### Reproduction Link

Providing a reproduction project would be challenging, as you would need a server, authentication, a webview, and so on.

### Workaround

No known workaround as yet.

**Comment by steverichey** [comment]
It might be nice if this was opt-in behavior, since it will change things pretty drastically for applications like ours that depend on native cookie storage. If that would be considered beneficial, I can open a pull request for it.

**Comment by samhouts** [comment]
#8169

**Comment by samhouts** [comment]
@steverichey Sure, we'd love a pull request! Thanks!

**Comment by absinghal** [comment]
Finding this behaviour in 4.6.0.8 - setting the Cookies property but the count property always returns 0 even on web page that sets cookies.
