### ISSUE TITLE
[Bug] [Android] SwipeView takes focus on ListView Item and makes it hard to scroll on device

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#10313]
### Description
This does not replicate on an emulator, but only on a physical device. When I added swipe items on the left/right on the ListViewItemTemplate and deployed to my device it was really hard to actually scroll the list. IT looks like the SwipeItem is taking focus when trying to scroll the list item. 

This is only on Android. iOS looks good.

### Steps to Reproduce

See reproduction project: https://github.com/jamesmontemagno/app-ac-islandtracker deploy to device, go to friends view, and try to scroll.

### Expected Behavior

Should be able to scroll and the SwipeItem under it shouldn't become active until swipe has happened.

### Actual Behavior
Seems like swipeitem is taking control which is making scrolling hard.

### Basic Information

- Version with issue: 4.6.0.616-pre4
- Last known good version: ?
- IDE: VS/VSM 16.5/8.5
- Platform Target Frameworks: 
  - Android: Compile 9.0. 
- Android Support Library Version: Support libraries 28.0.0.3
- Affected Devices: On device 10.0 Pixel 2XL

### Reproduction Link

https://github.com/jamesmontemagno/app-ac-islandtracker

### Workaround

Would be open... maybe i need to try to shrink down the swipeitem? Open to suggestions.

**Comment by jamesmontemagno** [comment]
Quick update here. I had a swipe item on left and right and that is when this showed up. This happened in both ListView & CollectionView.

When I removed the left one it seemed to work good.

**Comment by gresolio** [comment]
I would like to note, that disabling the swiping by setting SwipeView IsEnabled property to false, currently prevents parent CollectionView to scroll.

This is not the most expected behavior, it would be nice to be able to control swiping without prohibiting parent scrolling.
