### ISSUE TITLE
[Bug] iOS Linker Behavior Breaks Shell Navigation with Back Button

### ISSUE THREAD

**Issue by nwilliams** [xamarin/Xamarin.Forms#10317]
### Description
After making the necessary changes to prevent App Store rejection for having references to the deprecated UIWebView (updating Linker Behavior and Additional mtouch arguments), navigation using GoToAsync in conjunction with a QueryProperty no longer works after using the back button in the navigation bar -- using the swipe gesture (iOS 10+) or the tab bar to go back does not break navigation. 
### Steps to Reproduce

1. Download and extract the SampleShell solution
2. Build and run the SampleShell.iOS project
3. Tap on an item in the list to navigate to the item detail page
4. Tap the "< Browse" link in the navigation bar to return to the items page
5. Tapping on items in the list view no longer navigate to the detail page

### Expected Behavior
Navigation continues to work as it does when navigating back through means other than clicking the back button.
### Actual Behavior
Navigation stops working.
### Basic Information

- Version with issue: 4.5.0.617
- Last known good version: N/A
- IDE: Visual Studio Enterprise 2019, Version 16.5.3
- Platform Target Frameworks: 
  - iOS: 13.16.0.13 
  - Android: N/A 
  - UWP: N/A  
- Android Support Library Version: N/A
- Nuget Packages: 
- Affected Devices: iPhone 8 and various iPhone simulators

### Reproduction Link
Attached is a modified version of the out-of-the-box Xamarin.Forms sample that comes with Visual Studio. The call to GoToAsync is at Views/ItemsPage.xaml.cs:29.

[ShellSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4471728/ShellSample.zip)

**Comment by nwilliams** [comment]
Our app is going into UAT tomorrow and this bug is going to cause major issues for our iOS user base. Is there any way to increase visibility of this issue within the Xamarin development team?

**Comment by PureWeen** [comment]
fixed by https://github.com/xamarin/Xamarin.Forms/pull/10371
