### ISSUE TITLE
[Bug] [iOS] Opacity on Frame behavior change in 4.5

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#10333]
### Description

In Xamarin.Forms 4.4, with some controls in an AbsoluteLayout, and a Frame in the AbsoluteLayout set to cover all the controls (i.e. not include the controls in the Frame's content, but rather just position the Frame to cover the controls), if the background color is set to black and the opacity set to, say, 0.25, then the covered controls, as well as the background color of the AbsoluteLayout will dim. 

In Xamarin.Forms >= 4.5, doing the same causes a Label to not show through at all, and also the background color of the absolute layout does not show through, as if there was no Opacity set, or Opacity = 1... but only where the Frame covers a Label or directly covers the AbsoluteLayout. All of the other controls in the layout get dimmed as expected.

### Notes

It seems to me that using a Frame to do this dimming might not be the best approach, as a Frame is intended to contain controls, not cover them, so that a shadow and/or border can be added to a View or Layout. A BoxView would seem to be a better fit to cover and dim other views, and a BoxView works as expected. 

So this may not be a bug, but reporting it as such as the behavior is different between XF 4.4 and 4.5 and also between iOS and Android (did not test UWP).

### Steps to Reproduce

1.  Open the attached test project and deploy to an iOS simulator (tested on iPhone 11 iOS 13.4)

### Expected Behavior
The first visible control should be a Label with text "Can you see this Label? Am I dimmed?", and the background color, green, of the AbsoluteLayout should show through a bit. 

### Actual Behavior
The first visible control is a Button with text "Can you see this button? Am I dimmed?", and the green background color of the AbsoluteLayout does not show through at all. The Label and the background color of the AbsoluteLayout are covered by solid black with no transparency. 

### Basic Information

- Version with issue: tested 4.5.0.617, 4.6.0.616-pre4, and 4.7.0.620-nightly
- Last known good version: 4.4.0.991864
- IDE: Visual Studio 2019 16.5.3
- Platform Target Frameworks: 
  - iOS:  13.4
  
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials

### Screenshots
Expected:
![FrameOpacityExpected](https://user-images.githubusercontent.com/4606509/79271103-f57c7a00-7e3a-11ea-9bb0-311dd611a16d.png)

Actual:
![FrameOpacityActual](https://user-images.githubusercontent.com/4606509/79271122-fd3c1e80-7e3a-11ea-914f-94d7f97ecf88.png)

### Reproduction Link

[TestOpacityXF.zip](https://github.com/xamarin/Xamarin.Forms/files/4477619/TestOpacityXF.zip)

### Workaround

Use a BoxView rather than a Frame.

**Comment by Jared-Aus** [comment]
I can confirm that v4.5 broke opacity for Frames. In my case I was able to get it working again by setting HasShadow="False".
