### ISSUE TITLE
 [BUG] Trying to set custom font size for label 

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10335]
As a Developer I should be able to set a custom font size for my label control the following. The folowing does display the text but it should be a digital font,

Actual Result:
The font is displayed but when you set a font size of higher than 30 it appears to crash and displays the default system font.

Expected Result:

You should be able to display the font no matter what the size of the font size attribute however this doesn't appear to be case and defaults back to the standard font.

Here is the Actual Result 

```

 
  <Label HorizontalOptions="StartAndExpand"
     FontFamily="digitial" >                                   
    <Label.FormattedText>
     <FormattedString>
    <Span Text="Speed: " TextColor="White"/>
      <Span Text="6 miles" FontFamily="digital" FontSize="30" TextColor="White"></Span>
    </FormattedString>
      </Label.FormattedText>
  </Label>
```

WorkAround

You can use FontSize="Large" and that would let it render but its still to small to make out ?
```

 
  <Label HorizontalOptions="StartAndExpand"
     FontFamily="digitial" >                                   
    <Label.FormattedText>
     <FormattedString>
    <Span Text="Speed: " TextColor="White"/>
      <Span Text="6 miles" FontFamily="digital" FontSize="Large" TextColor="White"></Span>
    </FormattedString>
      </Label.FormattedText>
  </Label>
```
![bugxamforms](https://user-images.githubusercontent.com/5619229/79287811-e0e0c600-7ebc-11ea-8bb2-d425efa18a89.png)

**Comment by samhouts** [comment]
@davidbuckleyni  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by davidbuckleyni** [comment]
Hi @samhouts  if you look at RunningPage.xaml in

https://github.com/davidbuckleyni/WellBeingMaster 

There a variable called lblSpeed if you change the font size to 30 it no longer displays the font as segmented it could well be the font but looks like a bug in Xamarin to me.

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample @davidbuckleyni. I'm not sure if the attached sample is the correct one (lblSpeed doesn't exist). I have tried to reproduce the issue without success:

![issue-fontsize](https://user-images.githubusercontent.com/6755973/79841319-8a412380-83b7-11ea-8a3e-a6f60e7ed701.gif)

**Comment by samhouts** [comment]
@davidbuckleyni Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
