### ISSUE TITLE
[Bug]iOS Renderer NavigationBar.ShadowImage = new UIImage() not remove shadow line after xamarin.forms 4.5

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#10337]
### Description

 After updating xamarin.forms to 4.5 version. The previous renderer code : `NavigationBar.ShadowImage = new UIImage() ` not working now .

### Steps to Reproduce

1. Create a renderer code as follow : 

```
[assembly: ExportRenderer(typeof(NavigationPage), typeof(CustomNavigationRenderer))]
namespace AppFrameRenderer.iOS
{
    public class CustomNavigationRenderer: NavigationRenderer
    {
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            NavigationBar.ShadowImage = new UIImage();
        }
    }
}
```
2. Then no effects in iOS simulator device .
3. 

### Expected Behavior

![iosgif](https://user-images.githubusercontent.com/7145819/79289915-3dfc6c00-7efd-11ea-9fcc-04ec23015f44.gif)

### Actual Behavior
![iosgif](https://user-images.githubusercontent.com/7145819/79290569-0989af80-7eff-11ea-8937-37e66c93a7e7.gif)

### Basic Information

- Version with issue:
- Last known good version: Xamarin Forms 4.4.0.991864
- IDE: Visual Studio 2019 16.5.2
- Platform Target Frameworks: 
  - iOS:  13.4
- Nuget Packages: Xamarin Forms 4.5.0.617

### Reproduction Link

https://stackoverflow.com/questions/61218265/navigationbar-shadowimage-new-uiimage-not-remove-shadow-line-after-xamarin-f

### Workaround

Downgrade to Xamarin Forms 4.4

**Comment by Khrimm** [comment]
I can confirm the issue on iOS 13.4 with XF 4.5.0.617

**Comment by diasleo98** [comment]
@samhouts is this issue resolved?
