### ISSUE TITLE
[Enhancement] Make Xamarin forms / blazor & CsharpMarukup integration better

### ISSUE THREAD

**Issue by ysmoradi** [xamarin/Xamarin.Forms#10331]
## Summary
There is a type converter that makes it easy to set properties of controls in XAML.
For example, we can write
```xml
<Frame Padding="2,2,4,4" />
```
At background it uses ThicknessTypeConverter class to creates an instance of Thickness from the provided string.
In blazor, we can't do the same thing )-:
So, we've to write
```xml
<Frame Padding="new Thickness(2,2,4,4)" />
```
It makes converting xaml pages to blazor pages too hard! For example, how many of us know what's going on when we write followings in xaml:

```xml
<Button BackgroundColor="#224422" />
```

Of course, it does something! The logic of ColorTypeConverter is about 300 lines of codes!

The good news is that we can provide "almost" the same functionality in blazor too!

If we use C# implicit overload feature as followings:

```cs
public struct Color
{
...
	private static readonly ColorTypeConverter _converter = new ColorTypeConverter();
	public static implicit operator Color(string str)
	{
		return (Color)_converter.ConvertFromInvariantString(str);
	}
...
}
```

in blazor codes, we can write followings:

```xml
<Button BackgroundColor="#224422" />
```

This is also useful for [C# markup extensions](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.6/4.6.0-pre1#c-markup-extensions)!

## API Changes

I'd recommend adding an implicit operator to followings:

```
Thickness
Size
Rectangle
Point
Keyboard
ImageSource
GridLength
Font
FlexBasis
CornerRadius
Constraint
```

I'd like to submit a PR if you're happy with the idea!

**Comment by ysmoradi** [comment]
Ping!

**Comment by jfversluis** [comment]
The Markup Extensions are now part of the Xamarin COmmunity Toolkit and .NET MAUI Community Toolkit and better Blazor support is coming with .NET MAUI. If you have any more suggestions around these areas, please open issues on the appropriate repository! Thanks!

**Comment by ysmoradi** [comment]
> The Markup Extensions are now part of the Xamarin COmmunity Toolkit and .NET MAUI Community Toolkit and better Blazor support is coming with .NET MAUI. If you have any more suggestions around these areas, please open issues on the appropriate repository! Thanks!

It doesn't make sense at all! I've requested changes in classes that are located in the xamarin forms repository!

If (for example) xamarin forms color had implicit cast to a string, it would become in handy for developers who are using cs-markup extensions or Microsoft.MobileBlazorBindings.Templates.

Anyway, forget it. At the moment I'm using neither Microsoft.MobileBlazorBindings.Templates nor cs markup extensions.

**Comment by jfversluis** [comment]
Sorry if I misunderstood, even if that was the case, this still won't be happening as Xamarin.Forms is now in maintenance mode and we are not adding any new APIs or changing existing ones as much as possible. If you still would like to see improvements, please open an issue on the .NET MAUI repository, thanks!
