### ISSUE TITLE
[Enhancement] OffColor to Switch

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#10341]
## Summary
Make it possible to set OffColor for a Switch

## API Changes
**Properties to Add:**

- OffColor:Color

**Fields to Add:**

- OffColorProperty:BindableProperty

## Intended Use Case
To set the color of Switch when the Switch not is toggled. The default color could be hard to see if the background color is similar.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
