### ISSUE TITLE
[Enhancement] Add ItemTapped event to CollectionView

### ISSUE THREAD

**Issue by IngweLand** [xamarin/Xamarin.Forms#10342]
## Summary
There are scenarios, when it's necessary to get the tapped event on already selected item. Deselecting the item programmatically after it has been selected by the user might not work in all cases, for example, when you need to preserve currently selected item visually.
 
## API Changes

Should be similar to what ListView currently has. Ideally, with corresponding command and command parameter.

## Intended Use Case

ItemTapped event can be useful in many situations when you need to process user interaction with the already selected item. One of such a case is side menu, when tapping on selected item should still close it.

**Comment by PontusMagnusson** [comment]
Will this event trigger even if  `SelectionMode="None"`? To me it would make sense, since you can still tap items without selecting them.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
