### ISSUE TITLE
[Bug] Cannot change shadow appearance on Frame from version 4.5.x

### ISSUE THREAD

**Issue by badstorm** [xamarin/Xamarin.Forms#10348]
### Description
In my custom render I have this settings for change the appearance of the shadow in iOS
```
protected override void OnElementChanged(ElementChangedEventArgs<Frame> e)
{
    base.OnElementChanged(e);
    Layer.ShadowRadius = 10f;
    Layer.ShadowColor = UIColor.Black.CGColor;
    Layer.ShadowOffset = new CGSize(0,10);
    Layer.ShadowOpacity = 0.16f;
}
```

but from Xamarin Forms 4.5.x not works anymore.

What I see is that in the [FrameRenderer](https://github.com/xamarin/Xamarin.Forms/blob/4.5.0/Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs) was added a new ShadowView that in not accessible from the custom renderer.

### Workaround

In The [FrameRender](https://github.com/xamarin/Xamarin.Forms/blob/4.5.0/Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs) add a public function like this for access the ShadowView::
```
public ShadowView InnerShadowView
{
   get => _shadowView;
}
```
So in the custom renderer I can do:
```
protected override void OnElementChanged(ElementChangedEventArgs<Frame> e)
{
    base.OnElementChanged(e);
    InnerShadowView.Layer.ShadowRadius = 10f;
    InnerShadowView.Layer.ShadowColor = UIColor.Black.CGColor;
    InnerShadowView.Layer.ShadowOffset = new CGSize(0,10);
    InnerShadowView.Layer.ShadowOpacity = 0.16f;
}
```

**Comment by samhouts** [comment]
related to #7518

**Comment by jfversluis** [comment]
Added reproduction here (note; uses a local nupkg file so will probably fail to restore that) and tried with the NuGet resulting from #10469. Works as expected.

With the fix from the afore mentioned PR it is likely that all renderers should work as before.

[Repro10348.zip](https://github.com/xamarin/Xamarin.Forms/files/4561465/Repro10348.zip)
