### ISSUE TITLE
[Bug] WPF.Maps should not use GeoCoordinateWatcher.StatusChanged

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#10349]
# Description

Per https://github.com/dotnet/dotnet-api-docs/issues/4003, this API should be updated to use the CAM API.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
