### ISSUE TITLE
[Enhancement] Support GTK3 for Xamarin.Forms

### ISSUE THREAD

**Issue by trampster** [xamarin/Xamarin.Forms#10354]
## Summary
Provide a Xamarin.GTK3 along side or as a replacement for the existing Xamarin.GTK which uses GTK2.

GTK2 is very old, GTK sharp 3 on the other hand is actively community maintained and used by Eto.Froms and Avalonia on linux.

GTK Sharp 2 does not support .net core and given that MonoDevelop 8 drops linux support, going forward vscode with dotnet core/.net 5 will be the only option. 

GTK3 is a much more modern toolkit and adds support for many new widget.

GTK Sharp 3 is also available as a nuget package unlike GTK Sharp2. Which makes development/setup easier.

## API Changes
None

## Intended Use Case
The intended use case would be on Linux using dotnet core/.net 5 , developed with vscode and standard dotnet tooling, including dotnet new, dotnet build and dotnet run

**Comment by TheForgetTime** [comment]
https://gitee.com/n__n/Xamarin.Forms.Platform.GTK3.git

A gtk3 backend that only implements stacklayout, button and label.
This project is only used to learn the Xamarin.Forms platformization process, not for production environment

**Comment by jfversluis** [comment]
I think I just closed another issue like this one with a more detailed explanation, thanks for the suggestion! But closing this one for now.

See #3374
