### ISSUE TITLE
[Enhancement] Fluent design visual 

### ISSUE THREAD

**Issue by djordje200179** [xamarin/Xamarin.Forms#10352]
## Summary
As we all know, now you can use material components in Xamarin for Android and iOS, but that isn't supported for UWP. Therefore it would be nice to support Fluent design in same way as Material is supported. 

## API Changes
New class called Fluent, which implements `IVisual`, should be created.
Controls should look like those in UWP (same thing that Uno Platform does), and potentionaly this class should also change how certain controls look: Button, MasterDetail... (all controls that support Acrylic, reveal highlight...) 

## Intended Use Case
It would be nice if Fluent design is supported on Android and iOS (and of course UWP), and developers could then have WinUI-like components on all platforms.

**Comment by BurkusCat** [comment]
I would be interested in implementing this. I personally think UWP only would be best for a first release and other platforms could have custom implementations added later down the line if desired.

If you have a button, you could then have a great looking "Visual" on all three major platforms.
`<Setter Property="Visual" Value="{OnPlatform iOS=Material, Android=Material, UWP=Fluent}" />`

Fluent Visual I think should cover the following controls:
- Button (I think most buttons in Android/iOS *should be* Material, Fluent guidelines mean that the effects *can* be applied to a button but shouldn't be used for every button. I think this is fine as users can apply `Visual="Fluent"` to an entire page then add `Visual="Default"` to any buttons they don't want having it).
- MasterDetailPage - This would use the acrylic effect. The acrylic effect can have two background backdrop sources. Either the host backdrop (the content behind the app) or the backdrop (content behind the master page in the app). How would this be configured when you can only select `Visual="Fluent"`? There is lots of configurations for tints, luminosity, opacity etc. for both reveal background, reveal border, and acyrlic. However, I think most of these should be set to sensible defaults. I believe Material visual uses sensible defaults? If the user wants to override they can make their own Material renderers?
- AppBar/CommandBar/NavigationBar
- Grids
- ListView/CollectionView
- Picker is a maybe? The Windows 10 settings app has some reveal effects for their ComboBoxes.
- I feel like there should be a generic, catch-all rectangle control with the border effects, the hover light effects, and the ripple effects on-click. Should this be Frame? This way the user can construct "cards" etc. using Frame as a starting point.

**Comment by memeplex** [comment]
What will be the relationship between this and the native components that are being developed as part of the Fluent initiative, if any? I know it's still in an early stage, but there are some native fluent components already in place.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
