### ISSUE TITLE
[Enhancement] Make ExportFont working from inside referenced .NET Standard lib

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#10361]
## Summary
The current doc suggests that custom font must be embedded to a share project. https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts

If the shared project references a .NET Standard assembly with font embedded there (and exported via ExportFont), the font won't work. This scenario is helpful for custom controls in separate libs which might have their own embedded fonts.
Also there's no consistent set of font across platforms, making fonts exportable can make it possible creating a separate lib with a set of fonts which can be made universal for all platforms.

**Comment by jfversluis** [comment]
I think you're interpreting "shared project" wrong. With shared project in this case we mean the .NET Standard library. I don't think we are writing about shared project since a long time :)

Does that help? If not, would you be able to provide a little reproduction project with some more info that makes clear what you mean?

**Comment by maxim-saplin** [comment]
To be clear...
(1) Native Project (Android) -  references (2) XF UI project (.NET Standard Lib) - which in turn references (3) another lib 

If you embed a font inside (2) and export it via ExportFont attribute, all is good. If you do the same in (3) the font does not get applied.

**Comment by maxim-saplin** [comment]
https://stackoverflow.com/questions/61197238/adding-embedded-fonts-to-different-assembly-in-xamarin-forms-4-5 - someone else asked about that capability on stackoverflow

**Comment by jfversluis** [comment]
Ah gotcha, ok!

Just verified that indeed doesn't work

**Comment by VladislavAntonyuk** [comment]
It works in my solution for Android. There is an issue with iOS, if font size is greater than 28

**Comment by maxim-saplin** [comment]
> It works in my solution for Android. There is an issue with iOS, if font size is greater than 28.
> I have such structure:
> Android (1)-UI xaml(2)-ViewModel(3)-Services/Models(4)
> 
> Lib(3) contains Embedded resources and assembly info (I use font awesome with aliases)
> In Lib(2) I just use it like FontFamily="FontAwesomeBrands"

Doesn't work for me. Checked once again. Only works with UI lib

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by wollac11** [comment]
I also had this issue but found that it works as long as you make sure you are compiling the AssemblyInfo file in the shared library (or whichever class contains your ExportFont attribute(s)). If your library project has multiple targets there is a fair chance you have EnableDefaultCompileItems turned off and thus need to explicitly add a Compile line to your csproj, like so:
`<Compile Include="Properties\AssemblyInfo.cs" />`
