### ISSUE TITLE
[Bug] Disabling the Expander doesn't change its visual appearance

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10362]
### Description

Disabling an `Expander` (`IsEnabled="false"`) doesn't change its visual appearance. Therefore, an enabled `Expander` looks identical to a disabled `Expander`.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the basic expander page (first page in the table).

### Expected Behavior

The second `Expander` is disabled and so should be greyed out.

### Actual Behavior

The two `Expanders` look identical, despite the second one being disabled.

### Basic Information

- Version with issue: 4.6-pre4
- IDE: VSMac 8.5.3
- Platform Target Frameworks: 
  - iOS:  13.4
  - Android: API 28 

### Screenshots

![Simulator Screen Shot - iPhone X - 2020-04-17 at 12 25 52](https://user-images.githubusercontent.com/8092460/79564970-97080380-80a7-11ea-9150-97a9689239ed.png)

### Reproduction Link

[ExpanderDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4492604/ExpanderDemos.zip)

**Comment by samhouts** [comment]
@AndreiMisiukevich FYI :)

**Comment by AndreiMisiukevich** [comment]
Just curious whether ListView/CollectionView/CarouselView/IndicatorView changes its visual appearance if we set **IsEnabled** to **False** there.

I lean towards saying it's not a bug. IsEnabled just should prevent "tap to expand" flow.

Your thoughts @davidbritch @samhouts @davidortinau @jfversluis @PureWeen ?

**Comment by Tommigun1980** [comment]
Far more important would be to add support for an icon that denotes the expander's expansion state. Would you ever know that the element in the screenshot was tappable if it didn't contain a two line paragraph telling you it can be interacted with?

There doesn't seem to exist a way of doing it with XAML only, which makes it a pretty useless component imho. Suggestion would be to add states for the Header area, one for Normal, one for Expanded, and if you need it, one for disabled.

Thanks.

**Comment by AndreiMisiukevich** [comment]
> Far more important would be to add support for an icon that denotes the expander's expansion state. **Would you ever know that the element in the screenshot was tappable if it didn't contain a two line paragraph telling you it can be interacted with**?
> 
> There doesn't seem to exist a way of doing it with XAML only, which makes the expander a pretty useless component imho. Suggestion would be to add states to the Header area; one for Normal, one for Expanded (and if you need it, one for disabled), where the developer can add whatever elements he needs. Currently only one header state exists.
> 
> Thanks.

Why? Such possibility exists (Adding Image with trigger)

**Comment by AndreiMisiukevich** [comment]
> **Would you ever know that the element in the screenshot was tappable if it didn't contain a two line paragraph telling you it can be interacted with**?

How do we realize that any other buttons/layouts-wit-tap-gesture are tappable?

**Comment by AndreiMisiukevich** [comment]
@samhouts can you confirm that we want to have a different visual appearance for "disabled" control?(grayed out). Otherwise, this issue can be closed.
