### ISSUE TITLE
[Android] Direct painting on canvas not shown in Xamarin.Forms XAML Previewer 

### ISSUE THREAD

**Issue by sheiksyedm** [xamarin/Xamarin.Forms#10364]
### Description
We have created a custom control that paint gradient colors. But it not shown in Xaml previewer even set DesignTimeVisible is true. 
``` XAML
<Grid>
        <local:CustomView />
    </Grid>
```
```C#
   [DesignTimeVisible(true)]
    public class CustomView : View
    {

    }
```
### Android renderer

```C#
public class CustomViewRenderer : ViewRenderer
    {
        public CustomViewRenderer(Context context) : base(context)
        {
            this.SetWillNotDraw(false);
        }
        protected override void OnDraw(Canvas canvas)
        {
            Paint paint = new Paint();
            this.ClipBounds = new Rect(0, 0, Width, Height);
            int[] colors = new int[2] { Color.Red, Color.Green };
            float[] offsets = new float[2] { 0, 1 };
            LinearGradient gradient = new LinearGradient(0, 0, this.Width, this.Height, colors, offsets, Shader.TileMode.Clamp);
            paint.SetShader(gradient);
            canvas.Save();
            canvas.DrawPaint(paint);
            canvas.Restore();
            base.OnDraw(canvas);
        }
    }
```
### Expected Behavior
In XAML previewer, gradient color will be shown as similarly shown in device output.  
### Actual Behavior
In previewer gradient color not shown, only blank screen shown.  But running in the device it works fine. 
### Basic Information

- XF version: 4.3
- IDE: VS 2019 Enterprise edition 16.4.3 (windows)

### Screenshots
![image](https://user-images.githubusercontent.com/23059975/79570261-bec29000-80d6-11ea-8310-7657aec4f9e0.png)

> VS bug [#1106696](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1106696)

**Comment by jsuarezruiz** [comment]
Attached repro sample: [Issue10364.zip](https://github.com/xamarin/Xamarin.Forms/files/4502903/Issue10364.zip)
<img width="1357" alt="Captura de pantalla 2020-04-20 a las 12 42 04" src="https://user-images.githubusercontent.com/6755973/79743570-15151600-8305-11ea-97c1-d4f2cd26f7e7.png">

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi Team, Is anyone looking on this

**Comment by HemalathaMarikuma-syncfusion** [comment]
Hi Team, any update please

**Comment by paymicro** [comment]
`Canvas.DrawPaint` is not supported by the previewer.  
Need to use similar `Canvas.DrawRect(ClipBounds, paint);`
```
            if (DesignMode.IsDesignModeEnabled)
                canvas.DrawRect(ClipBounds, paint);
            else
                canvas.DrawPaint(paint);
```
![image](https://user-images.githubusercontent.com/27482193/83068042-51f4cb00-a070-11ea-8941-c02ee28c8332.png)
![image](https://user-images.githubusercontent.com/27482193/83068234-aef08100-a070-11ea-8ca1-0748e93ca1a5.png)
