### ISSUE TITLE
Implement ExportFont functionality on macOS

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#10360]
### Steps to Reproduce

1. Add custom font to shared project as described here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts
2. Check it is working on iOS and Android

### Expected Behavior

On macOS it is working also

### Actual Behavior

 It is not working on macOS

### Basic Information

XF 4.5.0.617

**Comment by jfversluis** [comment]
The feature was implemented for iOS, Android and UWP. I'll turn this into a feature request for now.

**Comment by maxim-saplin** [comment]
Thanks. Can WPF be added as well?
