### ISSUE TITLE
[Bug] iOS CollectionView not showing any content when using a ContentView inside

### ISSUE THREAD

**Issue by JMNewsome** [xamarin/Xamarin.Forms#10378]
### Description
When using a CollectionView in iOS with the template set to use a ContentView that has the content parameter bound to a view, the screen does not display any content. To fix this I found that HotReload (just re-saving the XAML) will fix this issue and also if you add a button to toggle the BindingContext on and off it will cause it to show content as expected

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Content shows as expected displaying all of the bounded views as necessary

### Actual Behavior
Empty screen

### Basic Information

- Version with issue: 4.5.x
- Last known good version: N/A
- IDE: Visual Studio 2019 Community Edition
- Platform Target Frameworks: 
  - iOS:  
- Nuget Packages:
- Affected Devices: All iOS Devices

### Reproduction Link

XAML Code 
`				<CollectionView ItemsSource="{Binding Data}" SelectionMode="None" ItemSizingStrategy="MeasureAllItems">
					<CollectionView.ItemTemplate>
						<DataTemplate>
							<ContentView Content="{Binding .}"/>
						</DataTemplate>
					</CollectionView.ItemTemplate>
				</CollectionView>`

Hack "Fix" for collection void, or any other way you choose fit to toggle the BindingContext
`		void HACK_iOS_Collectionview_Fix()
		{
			//iOS has a problem with the collection view that this apparently causes it to render as needed
			var tempBindingContext = BindingContext;
			Device.StartTimer(TimeSpan.FromMilliseconds(100), () =>
			{
				BindingContext = null;
				Device.StartTimer(TimeSpan.FromMilliseconds(100), () =>
				{
					BindingContext = tempBindingContext;
					Device.StartTimer(TimeSpan.FromMilliseconds(100), () =>
					{
						BindingContext = null;
						Device.StartTimer(TimeSpan.FromMilliseconds(100), () =>
						{
							BindingContext = tempBindingContext;
							return false;
						});
						return false;
					});
					return false;
				});
				return false;
			});
		}`

### Workaround
To fix this I found that HotReload (just re-saving the XAML) will fix this issue and also if you add a button to toggle the BindingContext on and off it will cause it to show content as expected

**Comment by jsuarezruiz** [comment]
@JMNewsome I would like to debug and review this case. Could you attach a reproduction sample (zip)?

**Comment by JMNewsome** [comment]
What is the best way to format the reproduction sample, just a new project demonstrating it wrapped in a zip?

**Comment by samhouts** [comment]
@JMNewsome Yes, please!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Tally2014** [comment]
I have the same issue, Collectionview works fine on Android but on IOS it doesn't show untill i change on my XAML code for hot restart
