### ISSUE TITLE
[Bug] ContentPresenter's Content's BindingContext is null

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#10376]
### Description

Using a ContentPresenter and setting its Content to anything that uses the binding context doesn't work, as the Content in ContentPresenter doesn't get its BindingContext set.

Example:

See https://github.com/xamarin/Xamarin.Forms/issues/10374 for example of MyViewWithContentPresenter - ie it's just a content view with a content presenter.

```xaml
<ContentPage ...>
    <ContentPage.BindingContext>
        <vm:MyViewModel />
    </ContentPage.BindingContext>

    <ContentPage.Content>
        <MyViewWithContentPresenter>
            <!-- Error: BindingContext is null here -->
            <CollectionView ItemsSource="{Binding MyItems}">
        </MyViewWithContentPresenter>
    </ContentPage.Content>
</ContentPage>
```

The error is that the CollectionView's BindingContext is null, hence for example the collection view doesn't work.

### Expected Behavior

BindingContext should be set for the content in a ContentPresenter.

### Actual Behavior

BindingContext is null for the content in a ContentPresenter.

### Basic Information

- Version with issue:
- Xamarin.Forms: 4.6.0.616-pre4
- IDE: VS For Mac 8.6 Preview, build 4243

### Workaround

Naive workaround (not 100% as it will overwrite any manual bindings):

```c#
        protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();

            // MyContent gets assigned as the Content property in a ContentPresenter
            if (this.MyContent != null)
                this.MyContent.BindingContext = this.BindingContext;
        }
```

More involved workaround utilising hidden BindableObject.SetInheritedBindingContext method, also incorporating workarounds for https://github.com/xamarin/Xamarin.Forms/issues/10374:

```c#
        // add a propertyChanged to the content property:
        public static readonly BindableProperty ViewContentProperty = BindableProperty.Create(
            nameof(ViewContent), typeof(View), typeof(ActivityIndicatorView), propertyChanged: OnViewContentPropertyChanged);

...

        // HACK #10374 + #10376!
        private static void OnViewContentPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            if (newValue != oldValue)
                ((ActivityIndicatorView)bindable).ReassignContentPresenterAndPropagateBindingContext();
        }

        public MyViewWithContentPresenter()
        {
            InitializeComponent();

            // HACK #10374! content presenter's content is null if it's assigned when view is not drawn. TODO: REMOVEME once Xamarin fixes this
            this.SizeChanged += (object sender, EventArgs args) => this.ResetIfParentChanged();
        }

        // HACK #10376!
        protected override void OnBindingContextChanged()
        {
            base.OnBindingContextChanged();

            this.PropagateBindingContext();
        }

        // HACK #10374! content presenter's content is null if it's assigned when view is not drawn. TODO: REMOVEME once Xamarin fixes this
        private void ResetIfParentChanged()
        {
            if (this.Parent != this.previousParent)
            {
                this.previousParent = this.Parent;
                this.ReassignContentPresenterAndPropagateBindingContext();
            }
        }

        // HACK #10374 + #10376!
        private void ReassignContentPresenterAndPropagateBindingContext()
        {
            this.contentPresenter.Content = this.ViewContent;

            this.PropagateBindingContext();
        }

        // HACK #10376!
        private void PropagateBindingContext()
        {
            if (this.ViewContent != null)
                BindableObject.SetInheritedBindingContext(this.ViewContent, this.BindingContext);
        }
```

I have now tens of lines of code with workarounds for different problems even resorting to internal APIs, when _all I want to do is to display some content via a ContentPresenter._ I'm probably doing something horribly wrong here.
Thanks.

**Comment by Tommigun1980** [comment]
I noticed the same thing happens for other things also, such as children assigned to layouts inside a custom view, so this is not confined to a ContentPresenter only.

**Comment by rmarinho** [comment]
You shouldn't set the content directly to the ContentPresenter.  

_The ContentPresenter should be placed in a control template to mark where content to be displayed by the templated custom control or templated page will appear._ 

please check this Documentation 
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-template#substitute-content-into-a-contentpresenter
