### ISSUE TITLE
[Enhancement] Context Flyout

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10372]
## Summary
can we expect a simplified (using it in xaml) of this POPUP MENU?
 i saw it in many native apps and it's a very handy feature!!!

## API Changes
All you need is here 👇
https://github.com/SKLn-Rad/Xam.Plugin.PopupMenu

## Example Screenshot
i used it in my playground app and it works fine but not customizable (like background and text color or icon for items , etc) and haven't sub menu! plus NOT works in UWP Release mode 

![Screenshot (479)_LI](https://user-images.githubusercontent.com/42671084/79636536-a5304f80-818d-11ea-9d37-ad83d5cbed20.jpg)

## Platforms 
Core/XAML 
iOS
Android
UWP

**Comment by jsuarezruiz** [comment]
Thanks for the proposal @mhrastegary77. Could you take a look at this enhancement https://github.com/xamarin/Xamarin.Forms/issues/1778, would it be similar (be able to create popups with any content) or to be able to create PopupMenu (similar to https://developer.android.com/reference/android/widget/PopupMenu)?

**Comment by mhrastegary77** [comment]
Hi @jsuarezruiz thanks for reading my proposal! i looked at that enhancement , that enhancement was something like content dialog in UWP (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-18362)  but what I'm saying is a little bit different than that , it's like menu flyout in uwp (https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyout?view=winrt-18362)

**Comment by mhrastegary77** [comment]
Move to xamarin community toolkit [1098](https://github.com/xamarin/XamarinCommunityToolkit/issues/1098)
