### ISSUE TITLE
[Bug] Issue Building Source Could not find SDK "WindowsMobile, Version=10.0.18362.0".

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10385]
I am getting the following error when building the source of xamrain forms. However When I look at the additional options in the visual studio community install it shows that the component is installed.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3774	Could not find SDK "WindowsMobile, Version=10.0.18362.0".	Xamarin.Forms.Maps.UWP	D:\Program Files (x86)\Microsoft Visual Studio\2019\CommunityN\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2348	

![image](https://user-images.githubusercontent.com/5619229/79762723-076a8b00-831b-11ea-936c-bbd3b36bd546.png)

**Comment by jsuarezruiz** [comment]
I noticed that you are not using driver C. I remember a related issue.
To fix this issue, just copy the folder [Windows Kit Root Dir]\10\Extension SDKs\WindowsMobile(For e.g., D:\Windows Kits\10\Extension SDKs\WindowsMobile) to C:\Program Files (x86)\Windows Kits\10\Extension SDKs\. Should solve all of the missing WindowMobile issues.

Note the registered WindowsMobile lib location(after installing VS 2017) is in
"C:\Program Files (x86)\Windows Kits\10\Extension SDKs\WindowsMobile\10.0.18362.0" which currently will not be redirected to the path you install Windows SDK. So you have to manually copy those files to the path stated above.

Hope will fix your issue!.

**Comment by davidbuckleyni** [comment]
Hi @samhouts  that got me passed the windows 10 mobile error but now having a uap missing error. I am doing a enhancement to the date picker and would like to get this up and running thanks.

![image](https://user-images.githubusercontent.com/5619229/79824568-72a17500-838e-11ea-88e6-bebe5c945836.png)

**Comment by jsuarezruiz** [comment]
Could you open the Visual Studio Installer and verify the installed Windows 10 SDKs?

<img width="457" alt="Captura de pantalla 2020-04-21 a las 13 04 13" src="https://user-images.githubusercontent.com/6755973/79859068-b4530f80-83d0-11ea-9ce2-3f1619112d95.png">

**Comment by davidbuckleyni** [comment]
Yes it’s their In the list I’m installing 2015 and 2017 see if that fixes it even though I had 2019 installed.

**Comment by davidbuckleyni** [comment]
I @jsuarezruiz I was missing a coouple but their still seems to be one missing I persume that will be the one installs with visual studio 2017?

![image](https://user-images.githubusercontent.com/5619229/79860807-3e987500-83cb-11ea-9465-3d67ec2bf516.png)

**Comment by davidbuckleyni** [comment]
This is really annoying me still saying its installed.

![image](https://user-images.githubusercontent.com/5619229/79861568-853a9f00-83cc-11ea-9bda-73449dd376a8.png)

**Comment by davidbuckleyni** [comment]
@jsuarezruiz any more info on this still having the issue and it is installed. Have verified that.

**Comment by davidbuckleyni** [comment]
I even have clicked here and it tells me its installed by the visual studio own installer

![image](https://user-images.githubusercontent.com/5619229/80920801-1107e000-8d6a-11ea-9f92-1d8ac229c7e9.png)

**Comment by samhouts** [comment]
@davidbuckleyni Can you please report this via Visual Studio Send Feedback? Thanks!

**Comment by davidbuckleyni** [comment]
Why how is this to do with visual studio this is to do with xamrian forms build not working nothing to do with visual studio.

**Comment by samhouts** [comment]
Visual Studio is unable to recognize the installation, correct?

**Comment by PureWeen** [comment]
The projects are just default UWP projects
If those projects aren't compiling because VS can't install the right sdk that's a Visual Studio issue

It looks like you are on a preview build and the installer isn't working with Visual Studio. We don't have any control over that behavior. But it is a useful issue for the Visual Studio team to know about
