### ISSUE TITLE
[Bug] Styling issues with FlyoutItem classes

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#10382]
### Description

I'm using the new classes to style the FlyoutItem menu items.

* FlyoutItemLabelStyle
* FlyoutItemImageStyle
* FlyoutItemGridStyle

Few issues:

* Label doesn't update according to state changes, such as Selected, while the background does
* Cannot style the color of the icons - I'm using `FontImageSource` and only want to change the color 
* Cannot use a custom style class to chain them on FlyoutItems as shown in the PR #9886 

Please support propagation of states to children or provide a similar solution to style all the elements of the flyout item templates and menu items.

### Basic Information

- Version with issue: 4.6-pre4
- Platform Target Frameworks:
  - iOS: 13.2
### Reproduction Link

https://github.com/davidortinau/FlyMe/blob/bug/flyout-styling/FlyMe/FlyMe/AppShell.xaml#L14

### Workaround

I suppose I could create my own template putting the VSM on the layout and use the new Target property to update all elements of the template.

**Comment by dishantmshah** [comment]
@davidortinau I am still able to reproduce this issue in Android with the latest version of Xamarin.Forms.

FlyoutItemGridStyle class is not updating any of the mentioned styles. Even settings Selected item BackgroundColor via VSM is not working.

Version Details:

Xamarin.Forms - 4.6.0.772
Xamarin.Android - 9.2.3.0
Visual Studio - 8.3.1 (build 18)

**Comment by PureWeen** [comment]
@dishantmshah FlyoutItemGridStyle was renamed to FlyoutItemLayoutStyle

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#flyoutitem-and-menuitem-style-classes
