### ISSUE TITLE
[Bug] Unable to support AppTheme and user preference at same time

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#10395]
### Description

Consider this scenario:

![image](https://user-images.githubusercontent.com/41873/79789011-295e1080-830f-11ea-8863-c364da998420.png)

In this case as a user I can choose to let my app opt-in to OS changes as they occur, or to control dark and light myself.

Note these choices in this UI are mutually exclusive. As soon as I choose to toggle the dark mode, I've opted out of OS changes (aka device settings).

![image](https://user-images.githubusercontent.com/41873/79789240-82c63f80-830f-11ea-8d94-886b46371842.png)

Similarly if I opt-in to "use device settings" then I can no longer manually set the dark mode on or off.

Currently I see these problems:

* cannot opt out of OS theme changes
* cannot manually set user preferred theme

I propose adding:

```csharp
public enum AppTheme
	{
		Unspecified,
		Light,
		Dark
	}
```

Then `OSAppTheme` is that type, but it can be shared by a new type below.

```csharp
public bool Application.UseOSAppTheme { get; set; } = true;
```

When `OSAppTheme` changes are requested by the OS, this bool should be checked before triggering any changes.

```csharp
public AppTheme UserAppTheme {get; set; }
```

Some variable to store the user chosen preference. Perhaps OSTheme is a new common type. Then when the user chooses to toggle their app theme between dark and light modes, they can use an API like:

```csharp
App.Current.UserAppTheme = AppTheme.Dark;
```

This I think also makes more sense with the other naming of `AppThemeColor` and `OnAppTheme` which can be used both for OS theme changes and user theme changes.

**Comment by MuleaneEve** [comment]
What's the expected behavior in the following scenario?
```C#
UseOSAppTheme = false;
UserAppTheme = AppTheme.Unspecified;
```

**Comment by varyamereon** [comment]
This is definitely an issue on older versions of Android too where there is no general settings option to set Dark mode therefore using the default implementation limits the app to Light mode. @davidortinau's suggestion would make it possible for Android users to choose between themes too.
