### ISSUE TITLE
[Bug] Xamarin.Forms don't show image

### ISSUE THREAD

**Issue by pulmuone** [xamarin/Xamarin.Forms#10398]
### Description
Xamarin.Forms (Android) don't show image. (Release Mode)
Android Option checked -> [V]Bundle assemblies into native code.

Android Compile using Android version : Android 10.0(Q)
Android Target Android Version : Android 10.0(Q)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019 (win) Enterprise verison 16.5.4
- Platform Target Frameworks: 
  - Android: Android SDK 10.0
- Nuget Packages: Xamarin.forms 4.5.0.617  ~ 4.6.0.616-pre4
- Affected Devices:
 Samsung SM-G986N (Android 10.0)

### Reproduction Link
Test source code.
https://github.com/pulmuone/App6

**Comment by PureWeen** [comment]
duplicate
https://github.com/xamarin/Xamarin.Forms/issues/9900#issuecomment-601610100

**Comment by pulmuone** [comment]
I want to enable  bundle assemblies into native code option .
