### ISSUE TITLE
[Bug] iOS doesn't update AppThemeColor when appearing is toggled

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#10391]
### Description

I created a color, assigned it to a page with DynamicResource, and ran the app. Then I toggle the iOS simulator appearance mode between Light and Dark, but this color doesn't change. 

```xaml
<AppThemeColor x:Key="BackgroundColor"
                Dark="#FFFFFF" 
                Light="#FF3300"/>
```

```xaml
BackgroundColor="{DynamicResource BackgroundColor}"
```

### Expected Behavior

The specified theme colors are displayed according to the OS theme change, and update at runtime.

### Actual Behavior

The color is correct only at cold start and does not update as the OS notifies the app of theme updates.

### Basic Information

- Version with issue: 4.6.0.655
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  13.4
  - Android: 9 and 10 (didn't test this time, but have observed the same problem)

### Workaround

Don't use this new api and instead use DynamicResource along with platform implementations.

**Comment by jsuarezruiz** [comment]
I can reproduce the same on iOS 13.4.

**Comment by MitchBomcanhao** [comment]
is that related to PR https://github.com/xamarin/Xamarin.Forms/pull/10327 ?
> "With this change the UI no long automatically updates when the OS theme is changed"

**Comment by bjkramer0926** [comment]
I'm running 4.6.0.726 and appear to still be having this issue.

**Comment by jfversluis** [comment]
Hey @bjkramer0926 unfortunately this just missed that 4.6 version. This should work in the next 4.6 service release. If not, please open a new issue :)

**Comment by RaduPoenaru** [comment]
I'm having this exact issue also in 4.6.800

SystemsThemeDemo, colors are not updated in iOS for any page in the stack. Only newly created pages will benefit from the new colors. 
On Android the colors are updated , but app gets a reset to main activity.

**Comment by bjkramer0926** [comment]
still not functioning
