### ISSUE TITLE
[Bug] Image from stream is returning Black.

### ISSUE THREAD

**Issue by orlandommb** [xamarin/Xamarin.Forms#10403]
### Description

Code to load the image to assign it to ImageSource.FromStream

            await CrossMedia.Current.Initialize();

            try
            {
                var result = await DisplayActionSheet("Imagen de Usuario", "Cancelar", null, "Elegir de la Galeria", "Tomar Camara");

                if (result == "Elegir de la Galeria")
                {
                    if (!CrossMedia.Current.IsPickPhotoSupported)
                    {
                        await DisplayAlert("No PickPhoto", ":( No PickPhoto available.", "OK");
                        return;
                    }

                    _mediaFile = await CrossMedia.Current.PickPhotoAsync();

                    if (_mediaFile == null)
                        return;

                    UserImage.Source = ImageSource.FromStream(() =>
                    {
                        return _mediaFile.GetStream();
                    });

                }
                else if (result == "Tomar Camara")
                {
                    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                    {
                        await DisplayAlert("No Camera", ":( No camera available.", "OK");
                        return;
                    }

                    _mediaFile = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                    {
                        Directory = "Sample",
                        Name = "myImage.jpg"
                    });

                    if (_mediaFile == null)
                        return;

                    UserImage.Source = ImageSource.FromStream(() =>
                    {
                        return _mediaFile.GetStream();
                    });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

Results in a Black Square

### Steps to Reproduce

1. Create Image File with James Montemagno Xam.Plugin.Media
2. Create Image control in Xamarin.Forms 4.5.0.617
3. Assign Source From Stream "ImageFile.GetStream()"

### Expected Behavior
Display Image
### Actual Behavior
Displays a Black Square
### Basic Information

- Version with issue: Xamarin.Forms 4.5.0.617

- Last known good version:
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
Xam.Plugin.Media Version 5.0.1
- Affected Devices:
iOS Simulator 13.4
### Screenshots

![Simulator Screen Shot - iPhone 11 - 2020-04-21 at 14 17 04](https://user-images.githubusercontent.com/12052916/79900436-38f75b00-83dc-11ea-9926-006088205818.png)

### Workaround

Downgrade to Xamarin.Forms 4.5.0.530 version and use Xam.Plugin.Media Version 4.0.1.5

**Comment by jsuarezruiz** [comment]
Attached a reproduction sample based on the suggested code and versions:
[Issue10403.zip](https://github.com/xamarin/Xamarin.Forms/files/4515498/Issue10403.zip)

![issue10403](https://user-images.githubusercontent.com/6755973/79971566-bf6f7380-8494-11ea-923a-cb82a87ed2ec.gif)

It seems to work fine although I would like to do more tests. In which version of Xamarin.Forms is where have you started having problems? What was the latest version that worked correctly?

**Comment by orlandommb** [comment]
Following your comment I've updated to the latest nugget packages, XF version 4.5.0.617 and Xam.Plugin.Media version 5.0.1 and still get the same error, it was working fine when I downgraded to Xamarin.Forms 4.5.0.530 version and Xam.Plugin.Media Version 4.0.1.5

**Comment by orlandommb** [comment]
[Link to project page UsuarioMaestro.cs](https://github.com/orlandommb/AlphaSoftPOS/blob/Orlando/AlphaSoftPOSApp/AlphaSoftPOSApp/View/UsuarioMaestro.xaml.cs)

[Link to project page UsuarioMaestro.xam](https://github.com/orlandommb/AlphaSoftPOS/blob/Orlando/AlphaSoftPOSApp/AlphaSoftPOSApp/View/UsuarioMaestro.xaml)

Maybe this can help.

**Comment by jsuarezruiz** [comment]
@orlandommb I have done more tests. The summary:
- Using Xam.Plugin.Media 5.0.1 with Xamarin.Forms 4.5.0.617 works fine the first time we get an image. Successive times we obtain the black image.
- Using Xam.Plugin.Media 4.0.1.5 with Xamarin.Forms 4.5.0.617 works fine always.

It seems to be an issue in latest Xam.Plugin.Media. Could you test this?.

**Comment by orlandommb** [comment]
@jsuarezruiz On my tests it never works using Xam.Plugin.Media 5.0.1 with Xamarin.Forms 4.5.0.617, latest Xamarin's version with last version of Xam.Plugin.Media 4.0.1.5 works great, indeed looks like a Xam.Plugin.Media issue, sorry for the waste of time ...

**Comment by Brayanhenaor** [comment]
I have the same problem with 5.0.1 version
