### ISSUE TITLE
Cannot access a disposed object. Object name: 'GroupableItemsViewController`1' only in iOS

### ISSUE THREAD

**Issue by ramalingeswarakki** [xamarin/Xamarin.Forms#10409]
### Description
When we try to add more 1 item in collection view, its giving error as cannot access disposed object specific to iOS
### Steps to Reproduce

1.  Create collection view
2. Bind items
3. Selection mode multiple

### Expected Behavior
Add all items 
### Actual Behavior
Adding only 1 item
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Mac VS 
- Platform Target Frameworks: 
  - iOS:  Only in iOS
<img width="1006" alt="Screenshot 2020-04-22 at 9 48 02 AM" src="https://user-images.githubusercontent.com/17778243/79940257-d3a87600-847e-11ea-912d-1a8f5b9dbd3a.png">

Forms 
<img width="209" alt="Screenshot 2020-04-22 at 9 52 18 AM" src="https://user-images.githubusercontent.com/17778243/79940303-fc307000-847e-11ea-9791-9773adc577b1.png">

### Workaround

 <CollectionView BackgroundColor="White" Scrolled="listView_Scrolled" 
                             
                              SelectionMode="Multiple" 
                             VerticalOptions="FillAndExpand" HorizontalOptions="StartAndExpand"  x:Name="listView">
                <CollectionView.ItemTemplate>
                            <DataTemplate>
                                
                                         <StackLayout HeightRequest="40"
                                                      Orientation="Horizontal"
                                                      VerticalOptions="StartAndExpand" >
                         <Label LineBreakMode="WordWrap"  Margin="5,0,0,0" x:Name="CriteriaName" TextColor="Black"
                               VerticalOptions="Center" HorizontalOptions="StartAndExpand"
                       FontSize="Small" Text="{Binding picklistValue}" VerticalTextAlignment="Center"/>           
                          </StackLayout>
                            </DataTemplate>
                </CollectionView.ItemTemplate>
           </CollectionView>

**Comment by jsuarezruiz** [comment]
@ramalingeswarakki I have tried to replicate the issue and created this sample:
[Issue10409.zip](https://github.com/xamarin/Xamarin.Forms/files/4514195/Issue10409.zip)
Cannot reproduce it. I have used the code from this issue with Xamarin.Forms 4.5.0.617. Could you  take a look if something is missing in this sample or attach a reproduction sample?.

**Comment by samhouts** [comment]
@ramalingeswarakki Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
