### ISSUE TITLE
[Enhancement] Shell.Current.GoToAsync could return a message (Success, Failed, or throw an exception) 

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#10410]
## Summary
A wrong formatted path just won't be executed. So that we have to search manually for the reason. We Can't even check for success of failed. It would be great if we could get some feedback from GoToAsync. 

Throwing an exception would be very helpful.

## API Changes
bool success = Shell.Current.GoToAsync("path"); // throw an exception if something goes wrong.

A method "Shell.ValidateUri(string uri)" would be great. That could return "WrongParameter", "Valid", "Invalid path at position xyz", and so on.

## Intended Use Case
If successfully executed return true. If not executed return false. If an error accrued throw an exception.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
