### ISSUE TITLE
[Bug] [UWP] - !!SERIOUS MEMORYLEAK!!! PageRenderer.Dispose does not free resources

### ISSUE THREAD

**Issue by gentledepp** [xamarin/Xamarin.Forms#10423]
### Steps to Reproduce

1. Start Xamarin.Forms UWP app and navigate to ANY page
2. Navigate back and run GC.Collect() (Or use dotMemory for profiling)
3. You will see, that the PageRenderer and the Page are still in memory

### Expected Behavior

Resources should become garbage collected

### Actual Behavior

Does not free memory

### Basic Information

- Version with issue: 4.4.0
- Last known good version: (no idea)
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP: irrelevant  
- Nuget Packages: irrelevant
- Affected Devices: all UWP devices...

### Workaround

This is the code of `Xamarin.Forms.Platform.UWP.PageRenderer.Dispose()`

```csharp

		protected override void Dispose(bool disposing)
		{
			if (!disposing || _disposed)
				return;

			_disposed = true;

			if (Element != null)
			{
				ReadOnlyCollection<Element> children = ((IElementController)Element).LogicalChildren;
				for (var i = 0; i < children.Count; i++)
				{
					var visualChild = children[i] as VisualElement;
					visualChild?.Cleanup();
				}
				Element?.SendDisappearing();
			}

			base.Dispose(); // the main culprit!
		}
```

because `base.Dispose()` is called, the code of `Xamarin.Forms.Platform.UWP.PageRenderer.VisualElementRenderer`
it - in turn - will invoke the overload that takes a bool:
```csharp
public void Dispose()
		{
                        /// !!! BECAUSE this is a protected virutal void Dispose(bool d) method
                        /// which is overwritten in PageRenderer,
                        /// the Dispose(bool b) method of VisualElementRenderer is NEVER executed!!!!!  
			Dispose(true); 
			GC.SuppressFinalize(this);
		}
```
What the flow should be:
1. `PageRenderer.Dispose(true)` is called
2. `VisualElementRenderer.Dispose(true)` is called

What actually happens
1. `PageRenderer.Dispose(true)` is called
2. `PageRenderer` forwards to `base.Dispose()` (`VisualElementRenderer.Dispose()`))
3. `VisualElementRenderer.Dispose()` calls `VisualElementRenderer.Dispose(true)`, but because that is overwritten by `PageRenderer`, instead, `PageRenderer.Dispose(true)` is called again.

`VisualElementRenderer.Dispose(true)` is NEVER CALLED!!!

This is the obvious fix:

```csharp

		protected override void Dispose(bool disposing)
		{
			if (!disposing || _disposed)
				return;

			_disposed = true;

			if (Element != null)
			{
				ReadOnlyCollection<Element> children = ((IElementController)Element).LogicalChildren;
				for (var i = 0; i < children.Count; i++)
				{
					var visualChild = children[i] as VisualElement;
					visualChild?.Cleanup();
				}
				Element?.SendDisappearing();
                                // additional memoryleaks: Eventhandlers are not unsubscribed from!!
				Unloaded -= OnUnloaded;
				Loaded -= OnLoaded;
			}

                        // Forward to the correct method! 🚀
			base.Dispose(disposing);
		}

´´´

You should really really fix that. This is a game stopper unfortunately

**Comment by gentledepp** [comment]
@BrayanKhosravian  @bruzkovsky  fyi

**Comment by nbevans** [comment]
You absolute legend for finding all these UWP bugs!

**Comment by gentledepp** [comment]
Well... don't be too happy. There is still some serious memory leaks, but we are currently not sure if they are within Xamarin.Forms for UWP or our own app
