### ISSUE TITLE
[Bug][iOS] NavigationPage.HideNavigationBarSeparator="true" doesn't work on iOS 13.4

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10438]
### Description

On previous versions of iOS it was possible to hide the navigation bar separator using the `NavigationPage.HideNavigationBarSeparator` platform-specific. However, this doesn't work on iOS 13.4.

### Steps to Reproduce

1. Run the attached sample on iOS.
2. Browse to the NavigationPage NavigationBarSeparator.

### Expected Behavior

Navigation bar separator is hidden.

### Actual Behavior

Navigation bar separator is displayed.

### Basic Information

- Version with issue: 4.5.0.396
- Last known good version: No idea.
- IDE: VSMac 8.5.4 
- Platform Target Frameworks:
  - iOS:  13.4

### Screenshots

iOS 13 result:

![Simulator Screen Shot - iPhone 11 - 2020-04-24 at 12 23 46](https://user-images.githubusercontent.com/8092460/80208615-7fd99080-8628-11ea-9af1-27ed1fe4d6d1.png)

Correct image (from our docs):

![navigationpage-hideseparatorbar](https://user-images.githubusercontent.com/8092460/80208584-6df7ed80-8628-11ea-8842-84c8d59bb0d8.png)

### Reproduction Link

[PlatformSpecifics.zip](https://github.com/xamarin/Xamarin.Forms/files/4528610/PlatformSpecifics.zip)

**Comment by krisurnok** [comment]
bug is not fixed in the version 
4.6.0.726

**Comment by Khrimm** [comment]
Not fixed in 4.5.0.725....

**Comment by davidbritch** [comment]
Hi @krisurnok and @Khrimm 

I've created a new issue (https://github.com/xamarin/Xamarin.Forms/issues/10578) that has more precise repro steps for it not working, and a temporary workaround.
