### ISSUE TITLE
[Bug] Implementing Radio Button Error Using Pre Build. 

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10430]
I am trying to use the radio button brought in 4.6.0.616-pre4 for a test purposes.

I have the following in my xaml 
 

```
 <RadioButton x:Name="rbKm" Text="Kmh" GroupName="test" />
 <RadioButton x:Name="rbMiles"  Text="Miles" GroupName="test" />
```

But I got the following exception is their an experimental flag that I am missing I am using visual studio for Mac.

Error:
Could not load type of field 'wellbeingmaster.Views.RunningPaige:rbKm' (2) due to: Could not resolve type with token 0100005e from typeref (expected class 'Xamarin.Forms.RadioButton' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null type:Xamarin.Forms.RadioButton member:(null)
                                    

Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.5.4 (build 12)
Installation UUID: 8be889b4-ffe3-4f2d-adb8-26e2acc99f0b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 610000101

=== Mono Framework MDK ===

Runtime:
	Mono 6.10.0.101 (2019-12/6f0bf73005d) (64-bit)
	Package version: 610000101

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Version: 3.1.200
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	2.1.17
	2.1.16

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.4 (16134)
Build 11E146

=== Xamarin.Mac ===

Version: 6.16.0.13 (Visual Studio Community)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:18-0400

=== Xamarin.iOS ===

Version: 13.16.0.13 (Visual Studio Community)
Hash: b75deaf82
Branch: d16-5-xcode11.4
Build date: 2020-04-01 21:33:19-0400

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/davidbuckley/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/davidbuckley/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-15 20:49:08 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-04-15 20:49:28 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 805040012
Git revision: 7642369422103e19b0b8d29ddc211abf2fd32607
Build date: 2020-04-16 08:55:15-04
Build branch: release-8.5
Xamarin extensions: 7642369422103e19b0b8d29ddc211abf2fd32607

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by jfversluis** [comment]
That's because RadioButton is under the experimental flag right now :) 

More info is here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags

Basically what you need to do is add the flag during app startup. I see the doc doesn't mention RadioButton yet, the correct flag for that is `RadioButton_Experimental`

I'm going to assume this helps you and close the issue. If not, feel free to reach out.

Thanks!

**Comment by jfversluis** [comment]
Hello again @davidbuckleyni!

It was brought to my attention that the experimental flag might not be in there for pre4, but it will be for stable. So, you will need to use that flag in the future. I think I misinterpreted your line about the experimental flag. Sorry about that.

The exception message looks like the kind of message that occurs when nuget package versions are misaligned. Could you make sure that the versions on all of your projects are aligned and you did a full clean and rebuild?

**Comment by davidbuckleyni** [comment]
Yeah I’ll do that in the morning.  Thanks I’ll report back.

**Comment by samhouts** [comment]
@davidbuckleyni Any luck? Thanks!

**Comment by davidbuckleyni** [comment]
Yeah the radio button fine thanks sorry for not closing before now
