### ISSUE TITLE
LineBreakMode Property on Entry

### ISSUE THREAD

**Issue by themronion** [xamarin/Xamarin.Forms#10435]
## Summary
It appears that an entry control doesn't have a linebreakmode property, but it is very useful. A photo with an intended use case is bellow. Trying to achieve this result with custom renderers didn't give me a satisfactory result.

## API Changes
    var entry = new Entry();
    entry.LineBreakMode = LineBreakMode.MiddleTruncation; // and other options

## Intended Use Case
![photo_2020-04-23_10-32-42](https://user-images.githubusercontent.com/52563426/80192992-b8756c00-8620-11ea-8e5b-7194e3434c15.jpg)

**Comment by themronion** [comment]
If there is now any way to achieve this - help would be appreciated

**Comment by BeranekCZ** [comment]
LineBreakMode (3 dots) for Placeholder would be nice too :-)

**Comment by themronion** [comment]
@BeranekCZ Indeed... As a workaround for now the only solution is to place a label on top of the entry with the needed LineBreakMode and to show it when entry is not focused and hide it when entry is focused

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
