### ISSUE TITLE
[Bug] Expander - Animation cut off when Spacing is used

### ISSUE THREAD

**Issue by Reveon** [xamarin/Xamarin.Forms#10449]
### Description
Collapse and Expand animation are being cut off when "Spacing" property has a value.

I tested it in CollectionView, ListView, BindableLayout and a simple grid and the animation is skipped in all of them. All of them are also in the repro sample for easier testing.

It seems that the Spacing just moves down the content by the value in the Spacing property and just leaves an empty space between the Content and Header. I do not see any use case for this but maybe I am missing something.

![Spacing](https://user-images.githubusercontent.com/29383312/80253814-45004880-867a-11ea-97b1-23c0e8c41b61.png)

### Steps to Reproduce

1. Run the repro sample
2. Expand and Collapse any item

### Expected Behavior
Animation should not be skipped when spacing is set.

### Actual Behavior
Expand and Collapase animation skip the spacing.

### Basic Information

- Version with issue: 4.7.0.688-nightly
- Last known good version:
- IDE: VS 16.5.4
- Platform Target Frameworks: 
  - Android: Android 10 emulator

### Screenshots

Example from CollectionView

![ExpanderSpacingAnimationCutOff](https://user-images.githubusercontent.com/29383312/80254052-bdffa000-867a-11ea-9c0c-38f5a86993ef.gif)

### Reproduction Link

[ExpanderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4531370/ExpanderTest.zip)

**Comment by AndreiMisiukevich** [comment]
@Reveon I agree. It is pointless. This property should be removed.

**Comment by AndreiMisiukevich** [comment]
@samhouts can be closed :)

**Comment by samhouts** [comment]
closed by #10460
