### ISSUE TITLE
[Bug] Mono.Cecil.ModuleDefinition.ReadSymbols when building Solution

### ISSUE THREAD

**Issue by banditoth** [xamarin/Xamarin.Forms#10441]
### Description

When building Xamarin Forms application the following error shows up in debug mode:
Program type already present: android.support.customtabs.ICustomTabsCallback$Stub$Proxy		

And in release mode:

Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(String source, String destination)
   at Xamarin.AndroidX.Migration.CecilMigrator.Migrate(IEnumerable`1 assemblies)
   at Xamarin.AndroidX.Migration.BuildTasks.CecilfyFiles.Execute()		

### Basic Information

- Version with issue: 4.6.0.616-pre4 , also with 4.5
- Last known good version: 4.3
- IDE:  Visual Studio Community 2019 / VisualStudio.16.Release/16.5.4+30011.22
Full Info
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

ASP.NET and Web Tools 2019   16.5.236.49856
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.5.236.49856
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.5.236.49856
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.5.236.49856
Azure Functions and Web Jobs Tools

C# Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30207.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.5.514 (c4f36a9)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

T4 Toolbox   15.0.0.0
Extends code generation capabilities of Text Templates.

TypeScript Tools   16.0.20225.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.5.0-beta4-20153-05+20b9af913f1b8ce0a62f72bea9e75e4aa3cf6b0e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.8.0.0 for F# 4.7   16.5.0-beta.20181.6+85af456066acd4e76d2bc7821b44a325e46f2fca
Microsoft Visual F# Tools 10.8.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.5.000.533 (d16-5@9152e1b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.5.49 (0904f41)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c0c5c78
    Java.Interop: xamarin/java.interop/d16-5@fc18c54
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.16.0.13 (b75deaf)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by banditoth** [comment]
Installed packages:
`PM> Get-Package

Id                                  Versions                                 ProjectName                                                                               
--                                  --------                                 -----------                                                                               
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.PassengerApp                                                 
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.PassengerApp                                                 
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.PassengerApp                                                 
Plugin.FacebookClient               {2.2.1}                                  NAMESPACE.PassengerApp                                                 
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.PassengerApp                                                 
NETStandard.Library                 {2.0.3}                                  NAMESPACE.PassengerApp                                                 
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.PassengerApp                                                 
sqlite-net-pcl                      {1.7.302-beta}                           NAMESPACE.PassengerApp                                                 
NETStandard.Library                 {2.0.3}                                  NAMESPACE.PassengerApp.iOS                                             
Plugin.FacebookClient               {2.2.1}                                  NAMESPACE.PassengerApp.iOS                                             
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.PassengerApp.iOS                                             
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.PassengerApp.iOS                                             
sqlite-net-pcl                      {1.7.302-beta}                           NAMESPACE.PassengerApp.iOS                                             
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.PassengerApp.iOS                                             
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.PassengerApp.iOS                                             
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.PassengerApp.iOS                                             
NETStandard.Library                 {2.0.3}                                  NAMESPACE.PassengerApp.Android                                         
Plugin.CurrentActivity              {2.1.0.4}                                NAMESPACE.PassengerApp.Android                                         
Plugin.FacebookClient               {2.2.1}                                  NAMESPACE.PassengerApp.Android                                         
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.PassengerApp.Android                                         
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.PassengerApp.Android                                         
sqlite-net-pcl                      {1.7.302-beta}                           NAMESPACE.PassengerApp.Android                                         
Xamarin.AndroidX.MediaRouter        {1.1.0}                                  NAMESPACE.PassengerApp.Android                                         
Xamarin.AndroidX.Migration          {1.0.4}                                  NAMESPACE.PassengerApp.Android                                         
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.Design      {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.v7.AppCo... {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.v4          {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.v7.CardView {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.v7.Media... {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.Core.Utils  {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Android.Support.CustomTabs  {28.0.0.3}                               NAMESPACE.PassengerApp.Android                                         
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.PassengerApp.Android                                         
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.PassengerApp.Android                                         
NETStandard.Library                 {2.0.3}                                  NAMESPACE.iOSBindings                                                  
NETStandard.Library                 {2.0.3}                                  NAMESPACE.AndroidBindings                                              
Xamarin.AndroidX.MediaRouter        {1.1.0}                                  NAMESPACE.AndroidBindings                                              
NETStandard.Library                 {2.0.3}                                  NAMESPACE.AndroidCommon                                                
Plugin.CurrentActivity              {2.1.0.4}                                NAMESPACE.AndroidCommon                                                
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.AndroidCommon                                                
Xamarin.AndroidX.MediaRouter        {1.1.0}                                  NAMESPACE.AndroidCommon                                                
Xamarin.AndroidX.Migration          {1.0.4}                                  NAMESPACE.AndroidCommon                                                
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.AndroidCommon                                                
NETStandard.Library                 {2.0.3}                                  NAMESPACE.iOSCommon                                                    
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.iOSCommon                                                    
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.iOSCommon                                                    
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.Common                                                       
Plugin.Multilingual                 {1.1.6-beta}                             NAMESPACE.Common                                                       
Xamarin.FFImageLoading.Forms        {2.4.11.982}                             NAMESPACE.Common                                                       
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.Common                                                       
Microsoft.AspNet.SignalR.Client     {2.4.1}                                  NAMESPACE.Common                                                       
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.Common                                                       
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.Common                                                       
NETStandard.Library                 {2.0.3}                                  NAMESPACE.Common                                                       
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.Common                                                       
sqlite-net-pcl                      {1.7.302-beta}                           NAMESPACE.Common                                                       
NETStandard.Library                 {2.0.3}                                  NAMESPACE.DriverApp.iOS                                                
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.DriverApp.iOS                                                
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.DriverApp.iOS                                                
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.DriverApp.iOS                                                
Plugin.Multilingual                 {1.1.6-beta}                             NAMESPACE.DriverApp.iOS                                                
Xamarin.FFImageLoading.Forms        {2.4.11.982}                             NAMESPACE.DriverApp.iOS                                                
ExpandableView                      {1.0.10}                                 NAMESPACE.DriverApp.iOS                                                
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.DriverApp.iOS                                                
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.DriverApp.iOS                                                
Xamarin.Google.iOS.Maps             {3.7.0.1}                                NAMESPACE.DriverApp.iOS                                                
Xamarin.Build.Download              {0.10.0}                                 NAMESPACE.DriverApp.iOS                                                
Xamarin.Google.Maps.Utils           {1.0.0}                                  NAMESPACE.DriverApp.iOS                                                
NETStandard.Library                 {2.0.3}                                  NAMESPACE.DriverApp.Android                                            
Plugin.CurrentActivity              {2.1.0.4}                                NAMESPACE.DriverApp.Android                                            
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.DriverApp.Android                                            
Xamarin.AndroidX.MediaRouter        {1.1.0}                                  NAMESPACE.DriverApp.Android                                            
Xamarin.AndroidX.Migration          {1.0.4}                                  NAMESPACE.DriverApp.Android                                            
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.Design      {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.v7.AppCo... {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.v4          {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.v7.CardView {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.v7.Media... {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.Core.Utils  {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Android.Support.CustomTabs  {28.0.0.3}                               NAMESPACE.DriverApp.Android                                            
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.DriverApp.Android                                            
Plugin.Multilingual                 {1.1.6-beta}                             NAMESPACE.DriverApp.Android                                            
Xamarin.FFImageLoading.Forms        {2.4.11.982}                             NAMESPACE.DriverApp.Android                                            
ExpandableView                      {1.0.10}                                 NAMESPACE.DriverApp.Android                                            
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.DriverApp.Android                                            
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.DriverApp.Android                                            
Xamarin.GooglePlayServices.Location {71.1600.0}                              NAMESPACE.DriverApp.Android                                            
Xamarin.Google.Maps.Utils           {1.0.0}                                  NAMESPACE.DriverApp.Android                                            
Xamarin.Build.Download              {0.10.0}                                 NAMESPACE.DriverApp.Android                                            
Xamarin.Build.Download              {0.10.0}                                 NAMESPACE.DriverApp                                                    
Xam.Plugin.SimpleAudioPlayer        {1.4.0}                                  NAMESPACE.DriverApp                                                    
Plugin.FirebasePushNotification     {3.2.9-beta}                             NAMESPACE.DriverApp                                                    
Plugin.Multilingual                 {1.1.6-beta}                             NAMESPACE.DriverApp                                                    
Plugin.Permissions                  {6.0.1}                                  NAMESPACE.DriverApp                                                    
Microsoft.AspNet.SignalR.Client     {2.4.1}                                  NAMESPACE.DriverApp                                                    
Xamarin.Forms.Maps                  {4.6.0.616-pre4}                         NAMESPACE.DriverApp                                                    
ExpandableView                      {1.0.10}                                 NAMESPACE.DriverApp                                                    
Xamarin.Essentials                  {1.5.3}                                  NAMESPACE.DriverApp                                                    
NETStandard.Library                 {2.0.3}                                  NAMESPACE.DriverApp                                                    
Xamarin.Forms                       {4.6.0.616-pre4}                         NAMESPACE.DriverApp    `

**Comment by banditoth** [comment]
Any update on this? From 30 of April, apple will stop accepting UIWebView implementation, and cant update NuGet..

**Comment by mattleibow** [comment]
Might be: https://github.com/xamarin/AndroidX/issues/8

**Comment by banditoth** [comment]
> 
> 
> Might be: [xamarin/AndroidX#8](https://github.com/xamarin/AndroidX/issues/8)

It might be, but I do not use Dotfuscator

**Comment by banditoth** [comment]
Full Build log available here:
[monocecilexceptionbuildlog.txt](https://github.com/xamarin/Xamarin.Forms/files/4547536/monocecilexceptionbuildlog.txt)

**Comment by banditoth** [comment]
Same error when upgrading AnroidX up to xamarin.androidx.migration\1.0.5

**Comment by mattleibow** [comment]
Working on a fix : https://github.com/xamarin/AndroidX/pull/98

**Comment by banditoth** [comment]
> 
> 
> Working on a fix : [xamarin/AndroidX#98](https://github.com/xamarin/AndroidX/pull/98)

I saw you have closed the ticket on AndroidX repository. Is it available in NuGet?

**Comment by mattleibow** [comment]
@banditoth I see you closed this issue. Is this because the new nuget fixes the issue?
