### ISSUE TITLE
[Enhancement] Ability to get musicProperties from MediaElement

### ISSUE THREAD

**Issue by teohumeau** [xamarin/Xamarin.Forms#10452]
There is actually no way to get mediaProperties from a MediaElement.
It could be great to add a feature similar to this one :
https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.FileProperties.MusicProperties

Metadata from file or stream could be retrieve like this :
`var musicProperties = await mediaElement.GetMediaPropertiesAsync();`

**Comment by jfversluis** [comment]
Thanks for the suggestion! `MediaElement` moved to the Xamarin Community Toolkit so you might want to move the feature request there if that's still something you're interested in, thanks!
