### ISSUE TITLE
[Bug] VisualStateManager in CarouselView is only applied to first element.

### ISSUE THREAD

**Issue by muhaym** [xamarin/Xamarin.Forms#10462]
### Description
VisualStateManager inside Carousel View is only applied to Root Element in DataTemplate, not to the children or multiple items.
### Steps to Reproduce

1. Create a Blank CarouselView
2. Inside Item Template Create a Grid, Inside Grid, Add Two Label
3. Apply VSM for each Label for all VisualStates of Carousel

### Expected Behavior
Styles should be applied to all controls which have VSM
### Actual Behavior
Styles only applied if VSM is used with Root Element inside DataTemplate

### Basic Information

- Version with issue: 4.5.0.657 
- Last known good version: NIL
- IDE: VS 2019
- Platform Target Frameworks: Android, iOS (Not Tested in Others)
  - iOS:  13
  - Android: 10

### Reproduction Link
github.com/muhaym/ReproVSMCarousel

### Workaround
No usable workarounds found yet.

**Comment by hartez** [comment]
As you've observed, the VisualStateManager only applies the states to the root element of a DataTemplate in a CollectionView. If you want to affect controls deeper in the DataTemplate's hierarchy, you can use the `TargetName` property in your `VisualState.Setters` collection. For example, to set the `TextColor` property on the `Label` in your `Grid`, you can change you `ItemTemplate` to something like this:

```
<CarouselView.ItemTemplate>
    <DataTemplate>
        <Grid HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">
            <VisualStateManager.VisualStateGroups>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="CurrentItem">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="Green" />
							<Setter TargetName="MyLabel"
									Property="Label.TextColor"
                                    Value="Yellow" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="PreviousItem">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="Blue" />
							<Setter TargetName="MyLabel"
									Property="Label.TextColor"
                                    Value="Red" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="NextItem">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="Blue" />
							<Setter TargetName="MyLabel"
									Property="Label.TextColor"
                                    Value="Red" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="DefaultState">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="Blue" />
							<Setter TargetName="MyLabel"
									Property="Label.TextColor"
                                    Value="Red" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateManager.VisualStateGroups>
            <Label x:Name="MyLabel" Text="{Binding .}"
                    VerticalOptions="Center"
                    HorizontalOptions="Center">
            </Label>
        </Grid>
    </DataTemplate>
</CarouselView.ItemTemplate>
```

Check out the [Microsoft docs on TargetName](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager#set-state-on-multiple-elements) or this article by @jfversluis: https://devblogs.microsoft.com/xamarin/visual-state-manager/
