### ISSUE TITLE
[Enhancement] Make ToTypeFace extension public

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#10476]
## Summary

The current ToTypeFace extension that performs the appropriate lookups for natively bundled assets and dynamically loaded fonts shipped with as Embedded Fonts. This API however is currently internal. It is a useful API when creating custom controls and should be given public visibility. 

https://github.com/xamarin/Xamarin.Forms/blob/e862b7830569fef05165f2239c570347e9be1969/Xamarin.Forms.Platform.Android/Renderers/FontExtensions.cs#L44-L58

## API Changes

Change ToTypeFace extension from internal to public

## Intended Use Case

When working with custom controls that may be generating resources from custom fonts, this would be highly useful to be able to get the appropriate font resource and take advantage of the built in loading and caching of Embedded Fonts.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
