### ISSUE TITLE
[Bug] CollectionView Header Controls with Commands Don't work when EmptyView is Visible

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#10477]
### Description

When you have a collectionview with a header with a button (or other elements) that have events/commands and put in an empty view in (and it is visible) the events dont' fire.

### Steps to Reproduce

1. See repro and screenshots

### Expected Behavior

Events in header should still fire

### Actual Behavior

They don't currently fire :(

### Basic Information

- Version with issue: 4.6.-pre4
- Last known good version: ?
- IDE: VS 2019 16.5
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Android 9 tested
  - UWP:  Not Tested
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

### Screenshots
![Untitled Project](https://user-images.githubusercontent.com/1676321/80406051-53b44e80-8878-11ea-9e48-2d0cefc92ff5.gif)

### Reproduction Link

[App14.zip](https://github.com/xamarin/Xamarin.Forms/files/4541302/App14.zip)

### Workaround

Don't' use emptyview

**Comment by hartez** [comment]
If I set the Command on the button directly (rather than using binding), it works fine. It looks like the EmptyView is messing with the header's BindingContext.

**Comment by jamesmontemagno** [comment]
interesting..... do you think I should set the bindingcontext manually somehow?

**Comment by jsuarezruiz** [comment]
@jamesmontemagno Thanks for the reproduction sample. This PR will fix this issue: https://github.com/xamarin/Xamarin.Forms/pull/10705
