### ISSUE TITLE
[macOS] CSS styling not applied to non-main window (but XAML styling is?)

### ISSUE THREAD

**Issue by chucker** [xamarin/Xamarin.Forms#10484]
### Description

I have an Xamarin.Forms Mac app that makes use of multiple windows (for example, Preferences is its own window). That is, the XAML pages do not share the same `NSWindow` frame as the main window.

Now I'd like to use CSS styles. However, they only seem to be applied to whatever instance is assigned to `FormsApplicationDelegate`'s `MainWindow`. When using XAML styling, applying styles to all windows appears to work.

### Steps to Reproduce

Create a Xamarin.Forms app with a macOS app. I followed the https://mindofai.github.io/Creating-Native-macOS-Apps-with-Xamarin.Forms/ tutorial.

Create a dependency service to open additional windows, such as described here: https://forums.xamarin.com/discussion/comment/347683/#Comment_347683

In the shared project, have an interface of this service:

```csharp
public interface IShowNewWindow
{
    void ShowSecondWindow(XamarinCssTestApp.MainPage mainPage);
}
```

In the macOS project, implement it as follows:

```csharp
using AppKit;
using CoreFoundation;
using CoreGraphics;
using Xamarin.Forms.Platform.MacOS;
using XamarinCssTestApp;
using XamarinCssTestApp.macOS;

public class ShowNewWindow : IShowNewWindow
{
    public void ShowSecondWindow(MainPage mainPage)
    {
        var window = new NSWindow
        {
            BackingType = NSBackingStore.Buffered,
            Level = NSWindowLevel.Normal,
            StyleMask = NSWindowStyle.Closable | NSWindowStyle.Titled,
            TitleVisibility = NSWindowTitleVisibility.Hidden
        };

        window.SetFrame(new CGRect(200, 200, 800, 600), true, true);
        window.Center();

        var page = new MainPage();
        NSViewController controller = page.CreateViewController();
        window.ContentView = controller.View;

        NSWindowController windowController = new NSWindowController(window);
        windowController.ShowWindow(null);
    }
}
```

Register it in the macOS `AppDelegate` constructor:

```csharp
        public AppDelegate()
        {
            DependencyService.Register<IShowNewWindow, ShowNewWindow>();

            [..]
        }
```

Change `MainPage.xaml` such that it has two labels and a button:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:d="http://xamarin.com/schemas/2014/forms/design" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d" x:Class="XamarinCssTestApp.MainPage">

    <ContentPage.Resources>
        <Style TargetType="Label">
            <Setter Property="TextColor" Value="Green" />
        </Style>
    </ContentPage.Resources>

    <StackLayout Orientation="Vertical">
        <!-- Place new controls here -->
        <Label StyleClass="myClass" Text="Red from CSS" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" />

        <Label Text="Green from XAML" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" />

        <Button Clicked="Button_Clicked" Text="Show Another Window" />
    </StackLayout>
</ContentPage>
```

…and have that button call our dependency service:

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace XamarinCssTestApp
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        void Button_Clicked(System.Object sender, System.EventArgs e)
        {
            DependencyService.Get<IShowNewWindow>().ShowSecondWindow(this);
        }
    }
}
```

3. Add a stylesheet `AppStylesheet.css`, which looks as follows:

```css
label.myClass {
    color: red;
}
```

Apply this stylesheet app-wide by changing `App.xaml` as follows:

```
<?xml version="1.0" encoding="utf-8"?>
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:d="http://xamarin.com/schemas/2014/forms/design" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d" x:Class="XamarinCssTestApp.App">
    <Application.Resources>
        <StyleSheet Source="AppStylesheet.css" />
    </Application.Resources>
</Application>
```

### Expected Behavior

When launching the app, the first label should be red, and the second should be green: the XAML applies green to all labels, but CSS applies red to labels that have the class `myClass`.

When clicking the button, this should apply to secondary windows as well.

### Actual Behavior

This works for the initial window. Subsequent windows seem to _only_ apply XAML styling.

### Basic Information

- Version with issue: Xamarin.Forms.4.5.0.657
- Last known good version: n/a
- IDE: VS4Mac 8.6.0.4274
- Platform Target Frameworks: 
  - mac: Xamarin.Mac Modern
  - other (I haven't tried other platforms; it's possible this CSS issue applies elsewhere as well)

### Screenshots

![Screen Shot 2020-04-28 at 08 57 28](https://user-images.githubusercontent.com/20194/80456709-5bcec580-892e-11ea-9111-43b77a5361c7.png)

### Reproduction Link

[XamarinCssTestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4543856/XamarinCssTestApp.zip)

### Workaround

XAML styling seems to work fine.

**Comment by hartez** [comment]
As a temporary workaround, you can also apply a stylesheet at the page level in your ContentPage.Resources - this will work even with pages in your additional windows: 

```
    <ContentPage.Resources>
        <StyleSheet Source="Stylesheet.css" />
    </ContentPage.Resources>
```

**Comment by chucker** [comment]
@hartez: could've sworn I had tried that but, yup, that helps!

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
