### ISSUE TITLE
[Bug] CollectionView Grouping There are blank lines

### ISSUE THREAD

**Issue by kangigocc** [xamarin/Xamarin.Forms#10487]
`                <Frame Grid.Row="1" Grid.Column="0" Grid.ColumnSpan="2" BorderColor="#337ab7" Padding="8">                     
                    <RefreshView IsRefreshing="{Binding IsBusy, Mode=TwoWay}" Command="{Binding LoadItemsCommand}">
                        <CollectionView VerticalScrollBarVisibility="Always" ItemsSource="{Binding Items}" IsGrouped="true">
![Screenshot_1588060765](https://user-images.githubusercontent.com/40585735/80462931-03b5b480-896a-11ea-9e39-53d2a7752cbf.png)
![Screenshot_1588060787](https://user-images.githubusercontent.com/40585735/80462941-07493b80-896a-11ea-9304-f7141e6a189f.png)

                            <CollectionView.ItemTemplate>
                                <DataTemplate>
                                    <Grid>
                                        <Grid.ColumnDefinitions>
                                            <ColumnDefinition Width="40"></ColumnDefinition>
                                            <ColumnDefinition></ColumnDefinition>
                                        </Grid.ColumnDefinitions>
                                        <CheckBox Grid.Column="0" VerticalOptions="Center" />
                                        <Label Grid.Column="1" VerticalOptions="Center" Text="{Binding Topics}"/>
                                    </Grid>
                                </DataTemplate>
                            </CollectionView.ItemTemplate>

                            <CollectionView.GroupHeaderTemplate>
                                <DataTemplate>
                                    <StackLayout>
                                        <Label Text="{Binding Name}" FontSize="Title" FontAttributes="Bold" HorizontalTextAlignment="Center"  VerticalTextAlignment="Center"/>
                                        <BoxView Color="Gray" HeightRequest="2" HorizontalOptions="Fill" />
                                    </StackLayout>
                                </DataTemplate>
                            </CollectionView.GroupHeaderTemplate>
                        </CollectionView>
                    </RefreshView>
                </Frame>`

**Comment by hartez** [comment]
Can you add a description or sketch of what you expect the layout to look like?

**Comment by samhouts** [comment]
@kangigocc  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
