### ISSUE TITLE
Issue 9686 crashes on iOS 10 -  Exception in Grouped CollectionView

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#10499]
### Description

Issue 9686 crashes against an iOS 10 device on branch 4.6

### Steps to Reproduce

1. Run Issue 9686 from the gallery on an iPhone 7 Plus iOS 10 device

### Expected Behavior
Doesn't crash

### Actual Behavior
Crashes

**Comment by velocitysystems** [comment]
Thanks for reporting this @PureWeen. Is this the same as #9065?

Given the documentation lists iOS 9 as the [minimum supported version](https://docs.microsoft.com/en-us/xamarin/get-started/supported-platforms?tabs=macos), this really needs to be addressed urgently. Please note, I originally reported this issue in January and it was tagged as a a high-priority bug for iOS.

**Comment by hartez** [comment]
This was fixed by commit https://github.com/xamarin/Xamarin.Forms/commit/173803da4748e19e839a62ef50a0f220367db53e
