### ISSUE TITLE
[Bug] [macOS] button click not being fired when inside a content view with a TapGestureRecognizer registration

### ISSUE THREAD

**Issue by kevcrooks** [xamarin/Xamarin.Forms#10491]
Tapped event on a ContentView is overriding a click event on a button sub-element

We have a ContentView which contains a TapGestureRecognizer registration, and inside the view we have a StackLayout containing a Button with a click event.

We expect that clicking on the button will cause the button click action to happen, but instead the ContentView tapped registration is being called.

We were previously using 4.5.0.356 where the click event was working correctly. Versions since 4.5.0.396 appear not to be working. 

Is there a fix or a work-around for this in the meantime, as we need to update for other reasons?

This is only happening on macOS - other platforms appear to be unaffected.

One workaround we have found is that if the main application window is not the active one at the time of the click, then the click event works correctly. But if the window is active, then the tapped registration is called instead.

**Comment by henrikweimenhog** [comment]
Maybe related? I have a Button inside a custom repeater with a command that stopped working (just like labels tap behaviour did earlier this month). 
This worked before (I've got all the bindingcontext working fine) and if I switch my button for a label it works.

**Comment by hartez** [comment]
Definitely no click event on 4.6; on 4.5, _both_ the click and the tap gesture are firing.

**Comment by DancesWithDingo** [comment]
To reproduce this issue, create a ContentPage and add this:

    <StackLayout>
        <StackLayout.GestureRecognizers>
            <TapGestureRecognizer Tapped="TapAndButtonHandler"/>
        </StackLayout.GestureRecognizers>

        <StackLayout>
            <Label Text="Label text"/>
            <Button Text="Test" Clicked="TapAndButtonHandler"/>
        </StackLayout>
    </StackLayout>

Add the handler to the code-behind.
        void TapAndButtonHandler(object sender, System.EventArgs e) {
            System.Console.WriteLine($"Boom! ({sender})");
        }

On iOS, Android and UWP, this works as expected, with both the gesture recognizer and the button calling the handler method.

On macOS, the TapGestureRecognizer eats tap events before they can be consumed by the button.

I have found no workaround.

**Comment by kevcrooks** [comment]
@samhouts can I check if there's an update on a fix and/or workaround for this issue?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!

**Comment by kevcrooks** [comment]
Can I say it's quite frustrating to put in the work to report these issues, and provide a clear way to reproduce - only to have it completely ignored and closed with a stock response after a year or two. Doesn't really motivate people to provide clear bug reports going forward...

> Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
