### ISSUE TITLE
[Bug] In iOS dark mode, Editor is having text in black on black background.

### ISSUE THREAD

**Issue by zijianhuang** [xamarin/Xamarin.Forms#10490]
### Description

As of Xamarin.Forms 4.5.0.657, Entry is working well with dark mode of iOS, however, Editor is not good: while the placehoder is in light gray text on black ground, however when you type something, the text is in black color apparently.

### Steps to Reproduce

1.  In VS 2019, create a Xamarin Forms project with the MasterDetails template.
2. Run the app in dark mode of iPhone/iPad simulator or real device.
3. Add a new item which description is with Editor

### Expected Behavior

Similar rendering like Entry with gray white text on black background.

### Actual Behavior

Black text on black background

### Workaround

Explicitly define black text and white background for Entry and Editor.

Related to https://github.com/xamarin/Xamarin.Forms/issues/9804

**Comment by hartez** [comment]
This is fixed in 4.6.0.726.
