### ISSUE TITLE
[Bug] ios 10, CollectionView with Grouping and GridItemsLayout Freeze then crash

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/Xamarin.Forms#10503]
### Description
We have a collectionview, with grouped element and ItemSizingStrategy at "MeasureAllItems" since it's mandatory for preventing another crash (#9065 ) and the CollectionView.ItemsLayout is a GridItemsLayout.

On iOS 10.3, on a tablet, if a minimal size changed append to the CollectionView, the app will freeze, the Application Output wil loop this message :
`The behavior of the UICollectionViewFlowLayout is not defined because:
the item width must be less than the width of the UICollectionView minus the section insets left and right values, minus the content insets left and right values.
Please check the values returned by the delegate.
The relevant UICollectionViewFlowLayout instance is <Xamarin_Forms_Platform_iOS_GridViewLayout: 0x7fba83e28800>, and it is attached to <UICollectionView: 0x7fba854a0600; frame = (0 0; 1024 1366); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x60800004ccc0>; layer = <CALayer: 0x608000c2c800>; contentOffset: {0, 0}; contentSize: {1024, 2340}> collection view layout: <Xamarin_Forms_Platform_iOS_GridViewLayout: 0x7fba83e28800>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.`

###To Reproduce
Take the sample.
 Launch the app on an tablet.
 Tap the home button.
 You will see the message on the Application ouput and the app will freeze.
 (For the information i have this case on my professional app at the appearing of the view)

### Basic Information

- Version with issue: 4.5.0.657
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  9.3
- Affected Devices: for the exemple Ipad Pro 12.9 inch (2nd generation) ios 10.3

### Reproduction Link

[testGrid.zip](https://github.com/xamarin/Xamarin.Forms/files/4550929/testGrid.zip)

**Comment by samhouts** [comment]
closed by #10622
