### ISSUE TITLE
XAML AutomatioId NOT working in UI Tests

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10508]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1004269/xaml-automatioid-not-working-in-ui-tests.html)._

---
I have AutomationId values set on several buttons on my main menu screen.
I have attached a screen grab of a portion of my xaml code.
When I run Repl and do the tree command, there are only a couple of elements listed with the Label set - NOT all of the buttons are listed with a Label.
Only the ones that DO have a Label listed are findable to my UI Tests.
The ones that do NOT show up with a Label in the Repl tree cause a time-out with the message that they are not found.
It seems very strange to me that only SOME of the elements that I set an AutomationId on actually show up with that Label in the Repl tree.

---
#### Visual Studio Feedback System on 4/23/2020, 08:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### terence.pfaff on 4/25/2020, 08:02 AM: 

I spoke too soon. Upgrading my Xamarin.Forms did NOT fix the problem.<br>There are still AutomationId values MISSING from the Repl tree.<br>Only SOME of my AutomationId values are being shown in the Repl.<br>It seems like Xamarin is not consistently passing ALL of the AutomationId values along to the Repl.

---
#### terence.pfaff solved on 4/24/2020, 07:12 AM, 0 votes: 

<p>Hi Everyone:</p><p>I got this fixed!</p><p>All I had to do was upgrade from Xamarin.Forms version 4.5.0.530 to version 4.5.0.657 on all the projects in my solution.</p>

**Comment by pfafft33** [comment]
![GraphPage_XAML_20200430](https://user-images.githubusercontent.com/47510341/80757056-2d511600-8af9-11ea-87b2-6b4d6e95a6ba.PNG)
![GraphPage_Repl_20200430](https://user-images.githubusercontent.com/47510341/80757088-3641e780-8af9-11ea-910a-ab1fb62a874d.PNG)

**Comment by pfafft33** [comment]
In the screen shots that I just attached, you can see in the XAML that 2 of the buttons have a value set for AutomationId. However, in the Repl, these values do NOT show up.
