### ISSUE TITLE
[Bug] CollectionView - error updating grouped collection

### ISSUE THREAD

**Issue by alex-relov** [xamarin/Xamarin.Forms#10502]
### Description
I have a Xamarin.Forms project that has a CollectionView, where IsGrouped=true that is bound to an ObservableCollection. If I call Clear() on the ObservableCollection and then call Add() to add an item I get the exception.
### Steps to Reproduce

1. Open the attached sample code.
2. Run the app on a simulator.
3. Click the button that says "Click to Clear and add"

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 13.4 iPhone 11 Simulator
- Android Support Library Version: 
- Nuget Packages:
XF 4.5.0.657
- Affected Devices:

### Reproduction Link

https://github.com/alex-relov/CollectionViewBug

### Exception
Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of sections.  The number of sections contained in the collection view after the update (1) must be equal to the number of sections contained in the collection view before the update (1), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted).
Native stack trace:
	0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e39c88 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff258a3cd2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff483919cb -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 17595
	5   UIKitCore                           0x00007fff4838ca49 -[UICollectionView _updateSections:updateAction:] + 445
	6   UIKitCore                           0x00007fff4838cb65 -[UICollectionView insertSections:] + 64
	7   CollectionViewBug.iOS               0x0000000102656139 xamarin_dyn_objc_msgSend + 217
	8   ???                                 0x0000000108fac250 0x0 + 4445618768
'

**Comment by hartez** [comment]
This is fixed by #9911, so it will be in the next release.
