### ISSUE TITLE
[Enhancement] Custom characters instead of dots when IsPassword poperty is enabled on Entry

### ISSUE THREAD

**Issue by themronion** [xamarin/Xamarin.Forms#10506]
## Summary
There is a situation when you need to show something else instead of dots in an entry in password mode
## API Changes
I suppose it must be something like this:
var entry = new Entry().
enrty.IsPassword = true;
entry.PasswordChar = '*';

## Intended Use Case
![Android - 24](https://user-images.githubusercontent.com/52563426/80616500-a5f89980-8a49-11ea-92ff-2b3326b21be2.png)

**Comment by hartez** [comment]
This would be pretty trivial to implement for UWP. Not sure about iOS and Android.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
