### ISSUE TITLE
[Enhancement] Control the scroll speed of CarouselView 

### ISSUE THREAD

**Issue by neville-nazerane** [xamarin/Xamarin.Forms#10516]
## Summary

When using the `ScrollTo` function of the `CarouselView`, it would be handy to have an additional parameter that helps control the speed of the animation. This could be something similar to the  `rate` parameter in the `Animate` function.

## API Changes

Under `CarouselView`, there are currently two `ScrollTo` overloads

    public void ScrollTo(object item, object group = null, ScrollToPosition position = ScrollToPosition.MakeVisible, bool animate = true, uint rate = 16);

    public void ScrollTo(int index, int groupIndex = -1, ScrollToPosition position = ScrollToPosition.MakeVisible, bool animate = true, uint rate = 16);

## Intended Use Case

Control the speed at which the carousel scrolls programmatically to enhance user experience.

**Comment by rubiomiguel06** [comment]
Did anyone manage to have a similar effect with the current Xamarin Forms Carousel View? I would like to have this behavior, but it doesn't look like this enhancement will happen any time soon.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
