### ISSUE TITLE
[Enhancement] RatingBar in Xamarin.Forms

### ISSUE THREAD

**Issue by saiyamjain143** [xamarin/Xamarin.Forms#10522]
https://developer.android.com/reference/android/widget/RatingBar
![image](https://user-images.githubusercontent.com/31028359/80710687-cc333d80-8b0c-11ea-80a3-5f65a2a7f2e9.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
