### ISSUE TITLE
[Bug] TapGestureRecognizer not working with Spans on iOS when text in the span is multiline

### ISSUE THREAD

**Issue by abdelbena** [xamarin/Xamarin.Forms#10520]
### Description
Having a Label with a span that has multi-line text with TapGestureRecognizers not working on iOS.
### Steps to Reproduce

1. Add the next Label to MainPage.xaml:
```
<Label WidthRequest="100"
    VerticalTextAlignment="Center"
    HorizontalTextAlignment="Center">
    <Label.FormattedText>
        <FormattedString>
            <Span Text="Long text about how we respect your privacy but you should actually check  Long text about how we respect your privacy but you should actually check " TextColor="Blue">
                <Span.GestureRecognizers>
                    <TapGestureRecognizer Tapped="Tap_EventHandler" />
                </Span.GestureRecognizers>
            </Span>
        </FormattedString>
    </Label.FormattedText>
</Label>
```
2. Add EventHandler Tap_EventHandler

### Expected Behavior
When the user tap on the span the action described in the EventHandler should happen.
### Actual Behavior
When the user tap on the span the action described in the EventHandler never happen.
### Basic Information

- Version with issue: 4.6.0.726

**Comment by hartez** [comment]
Also not working on Android.

**Comment by hartez** [comment]
[_10520 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4560470/_10520.Repro.zip)
