### ISSUE TITLE
[Bug] Windows opened in a webview with window.open are not closed when close() is executed.

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#10525]
### Description
I am displaying in a webview a page that contains an info button which opens a secondary window using window.open.  The info window contains a button with an id of ClosePopup which executes a close():

            $("#closePopup").on("click touchstart", function () {
                close();
            });
On both android and iOS in a browser, opening the info window opens a second full-view tab, and tapping on the close icon closes the tab and returns the user to the previous page.
In the app, opening the info window replaces the content in the webview with the info content, and tapping the close window does nothing.  On Android I can tap the hardware back button to return to the previous page, but iOS offers no functionality and this is not an acceptable work around.  What I would expect is that the webview would return the user to the previous page when the close() is executed.

I am not able to take the time to create an example app at the moment, but will when I get a work around to this in place, if it is needed.

### Steps to Reproduce

1. Create a webpage that uses window.open to open a second page.  On the second page create a button and wire it up to do a javascript close() when tapped.
2. Open the initial webpage in a webview, then open the second page.
3. tap the close button, you are not returned to the first page as you should be.

### Expected Behavior
The page opened using window.open closes.

### Actual Behavior
Nothing

### Basic Information

- Version with issue:
- Last known good version: NA
- IDE: VS 16.5.4
- Platform Target Frameworks: 
  - iOS:  13.16.0.13
  - Android: 10.2.0.100

**Comment by rmarinho** [comment]
hi @czuck thanks for your report. The WebView is not a full featured "browser app" it  was designed to show web pages and navigating between pages. What you are requesting is basic multiple window management. I think we consider this a enhancement  to our current control. 

Thanks

**Comment by czuck** [comment]
As a work around, I first tried injecting javascript into the webview to do a back when the close button is clicked.  This worked, however the initial webpages were managed with ajax but window.open isn't so I lost my backstack.
My next attempt was to make a JQuery Mobile popup with an iframe and put the page in there instead of using window.open.  That appears to give me the functionality I need so that's the work around I'm going with for now.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
