### ISSUE TITLE
[Bug] NRE loading image in ImageCell

### ISSUE THREAD

**Issue by Azlon** [xamarin/Xamarin.Forms#10533]
### Description
ImageCell throwing nullreference exception on Android.

### Steps to Reproduce

1.  Use ImageCell in Listview/ TableView DataTemplate
2.  Set ImageSource URI (in codebehind, xaml), Detail and Text properties.
3.  Load 

### Expected Behavior
Image loads next to the Detail / Text elements as a ImageCell would behave.
### Actual Behavior
Crashes on nullreference exception

### Basic Information
Image file linked properly in Android project (as tested with a normal Image control)

Stacktrace
 
  at Xamarin.Forms.Platform.Android.ImageViewExtensions.UpdateBitmap (Android.Widget.ImageView imageView, Xamarin.Forms.IImageElement newView, Xamarin.Forms.IImageElement previousView, Xamarin.Forms.ImageSource newImageSource, Xamarin.Forms.ImageSource previousImageSource) [0x000f8] in D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\ImageViewExtensions.cs:49 

### Xaml

` <StackLayout>
            <SearchBar Placeholder="Search user"></SearchBar>
            <TableView>
                <TableRoot>
                    <TableSection>
                        <ImageCell ImageSource="avatar.png" Detail="User description" Text="Username">
                        </ImageCell>
                    </TableSection>
                </TableRoot>
            </TableView>
        </StackLayout>`

**Comment by hartez** [comment]
@Azlon Try updating Forms to 4.6 - that should fix this issue.
