### ISSUE TITLE
[Bug] [UWP] CollectionView items have left/right padding only on UWP

### ISSUE THREAD

**Issue by DuncWatts** [xamarin/Xamarin.Forms#10547]
### Description
When using a CollectionView on UWP the items have a margin of 12px on the left and right rather than going to the edge of the control.  On Android and iOS there is no margin.

### Steps to Reproduce

1. Add CollectionView with DataTemplate containing a solid background
2. Run on UWP

### Expected Behavior
The solid background goes to the edge of the control

### Actual Behavior
The solid background does not go to the edge of the control.

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: Unknown
- IDE: VS2019 16.5.4
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10
  - UWP:  Target 1903

### Screenshots

UWP:
![image](https://user-images.githubusercontent.com/23555469/80866785-931fd800-8c88-11ea-9ee5-520b9d6e597c.png)

Android:
![image](https://user-images.githubusercontent.com/23555469/80866837-e003ae80-8c88-11ea-80ed-7752dd670096.png)

**Comment by hartez** [comment]
@StephaneDelcroix looks like a bug to me.

**Comment by rmarinho** [comment]
This is because of the ListStyle default style irc i fixed this for CarouselView
