### ISSUE TITLE
[Bug] Experimental flag doesn't work if the RadioButton is in the startup page

### ISSUE THREAD

**Issue by BurkusCat** [xamarin/Xamarin.Forms#10546]
### Description
I've only tested this on Android but when I tried to use the RadioButton experimental flag for Android it did not work when the RadioButton was on the first page of the app that started up. I am using Prism if it makes a difference.

I set my flags like I do for other experiments:
```
            Xamarin.Forms.Forms.SetFlags("SwipeView_Experimental");
            Xamarin.Forms.Forms.SetFlags("CarouselView_Experimental");
            Xamarin.Forms.Forms.SetFlags("RadioButton_Experimental");
            Xamarin.Forms.Forms.SetFlags("IndicatorView_Experimental");
```

### Steps to Reproduce

1. Add RadioButton_Experimental flag to `MainActivity.cs`
2. Add a RadioButton to the first page of your (prism) app

### Expected Behavior
App launches with Radio button showing on first page.

### Actual Behavior
You get the error message that RadioButton_Experimental flag should be used if you are using the experimental control

### Basic Information

- Version with issue: 4.6
- Last known good version: N/A
- IDE: Visual Studio 16.5.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Prism
- Affected Devices: Pixel 2

### Workaround

Workaround was to set it in the Shared project `app.xaml.cs`. Then it fixed my issue:
```
        public App() : this(null)
        {
            Device.SetFlags(new[]
            {
                "SwipeView_Experimental",
                "CarouselView_Experimental",
                "RadioButton_Experimental",
                "IndicatorView_Experimental",
            });
        }
```

**Comment by BurkusCat** [comment]
I won't be able to spend time on creating a reproduction project. I thought my workaround may help some people.

Potentially an easy fix would be to update all the documentation to use that method of setting experimental flags? It is easier too as you only have to do it once in your shared project.

**Comment by StephaneDelcroix** [comment]
flags should be set prior to Forms.Init(), or whatever invokes that in Prism. As you can't provide a repro, I'm closing this. thanks

**Comment by mohamadayash** [comment]
I have the same problem 
![image](https://user-images.githubusercontent.com/11196273/98921057-87d02380-24d9-11eb-8f1a-ef3f23bb59da.png)
