### ISSUE TITLE
[Bug] CheckBox throws System.Reflection.TargetInvocationException in Android

### ISSUE THREAD

**Issue by pldeschamps** [xamarin/Xamarin.Forms#10543]
### Description
CheckBox throws exception on Android and not on UWP
### Steps to Reproduce

1.  Android Xamarin.Forms Project
2.  create a XAML Page
3.  Add a CheckBox

### Expected Behavior
The CheckBox should appear

### Actual Behavior
System.Reflection.TargetInvocationException

### Basic Information

- Version with issue: Xamarin.Forms v4.6.0.726 and v4.5.0.
- Last known good version:
- IDE: VS19
- Platform Target Frameworks: 
  - Android:
    - Emulator: 8.0, API 26
    - Phone: Android 9.0
  - UWP:  16299, (OK!)

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Android Emulator and device ANE-LX1

### Screenshots

<img width="637" alt="checkbox" src="https://user-images.githubusercontent.com/18527288/80858975-9f427000-8c5d-11ea-9a05-b03f17158429.png">
<img width="640" alt="checkboxUWPok" src="https://user-images.githubusercontent.com/18527288/80858979-ab2e3200-8c5d-11ea-8618-0de37da58321.png">

### Workaround
Updated Xamarin.Forms from 4.5.0 to 4.6.0

**Comment by pldeschamps** [comment]
CheckBox works on Android in a minimal project. So I have to find out what is rising the exception in my current Android project.

**Comment by StephaneDelcroix** [comment]
please do so, and attach the minimal reproduction code that triggers the issue

**Comment by StephaneDelcroix** [comment]
a full stack trace might be useful too (not a screenshot of your ide)

**Comment by pldeschamps** [comment]
To solve it:
- First create a styles.xml file in the Android project if it does not exist in Resources/values/styles.xml:
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
  <style name="MainTheme" parent="MainTheme.Base">
  </style>
  <!-- Base theme applied no matter what API -->
  <style name="MainTheme.Base" parent="Theme.AppCompat.Light.DarkActionBar">
  </style>
  <style name="AppCompatDialogStyle" parent="Theme.AppCompat.Light.Dialog">
  </style>
</resources>
```
- second add a Theme in MainActivity.cs if it is not done:
```
using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.OS;
using Xamarin.Forms.Internals;

namespace Almicantarat.Droid
{
	[Activity (Label = "Almicantarat", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsApplicationActivity
	{
		protected override void OnCreate (Bundle bundle)
		{
			base.OnCreate (bundle);
            Xamarin.Essentials.Platform.Init(this, bundle);
			Registrar.Registered.Register(typeof(Xamarin.Forms.CheckBox), typeof(Xamarin.Forms.Platform.Android.CheckBoxRenderer));

			global::Xamarin.Forms.Forms.Init (this, bundle);
            LoadApplication(new AlmicantaratXF.Views.App ());
        }
    }
}
```
- Third, if bug add this line to the MainActivity.cs:
https://github.com/xamarin/Xamarin.Forms/issues/6856#issuecomment-510998331
```
			Registrar.Registered.Register(typeof(Xamarin.Forms.CheckBox), typeof(Xamarin.Forms.Platform.Android.CheckBoxRenderer));
```
