### ISSUE TITLE
[WPF] Entry.Cursor Position not changing

### ISSUE THREAD

**Issue by tessarolli** [xamarin/Xamarin.Forms#10548]
### Description
On wpf, it feels like Cursor Position property is not implemented

### Steps to Reproduce
1.  Add an Entry to a Xamarin Forms ContentPage and set some text to it
2.  From CodeBehind, try to change cursorposition
3. It'll be 0, and if you change it nothing happens

### Basic Information
It's working on UWP.
Xamarin.Forms 4.5.0.617
Xamarin.Forms.Platform.WPF 4.4.0.991864

**Comment by Happypig375** [comment]
This is an instance of #7229 on WPF.

**Comment by tessarolli** [comment]
I've come up with a workaround for this issue.

Add a new CustomRenderer on WPF project, and paste this code:

`using System.ComponentModel;
using YourProject.WPF.Renderer;
using Xamarin.Forms;
using Xamarin.Forms.Platform.WPF;

[assembly: ExportRenderer(typeof(Entry), typeof(CustomEntryRenderer))]
namespace YourProject.WPF.Renderer
{
    public class CustomEntryRenderer : EntryRenderer
    {
        Entry instance;

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            if (Control != null && instance != null && e.PropertyName == "CursorPosition")
            {
                if (Control.CaretIndex != instance.CursorPosition)
                    Control.CaretIndex = instance.CursorPosition;
            }

        }

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                instance = e.NewElement;
                Control.SelectionChanged += Control_SelectionChanged;
            }

        }

        private void Control_SelectionChanged(object sender, System.Windows.RoutedEventArgs e)
        {
            if (Control != null && instance != null)
                instance.CursorPosition = Control.CaretIndex;
        }

        protected override void Dispose(bool disposing)
        {
            Control.SelectionChanged -= Control_SelectionChanged;

            instance = null;

            base.Dispose(disposing);
        }


    }
}`

**Comment by StephaneDelcroix** [comment]
CursorPosition is indeed not implemented on WPF yet. Feel free to provide a pull-request
