### ISSUE TITLE
Please Support  Xamarin.Forms.Visual.Material for UWP

### ISSUE THREAD

**Issue by samitdesai** [xamarin/Xamarin.Forms#10555]
Description
We are using Xamarin Forms for our cross-platform application development which include iOS, android and UWP. It would be great if the application looks identical in all the 3 platforms.
﻿
After reading below the blog and
https://devblogs.microsoft.com/xamarin/xamarin-forms-4-6/
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual

Is there any plan to support material design support for UWP?.

For UWP and Wpf stand alone project "materialdesigninxaml" library all ready exist,
http://materialdesigninxaml.net/

Is there is a way we can integrate this library with xamarin.Form.

Below is the issue track in the materialdesigninxaml library, is there is a hope or the possibility xamarin team can help look into this project and integrate it with xamarin Form
MaterialDesignInXAML/MaterialDesignInXamlToolkit#381

Or any 3rd party library available which support material visual support for UWP?

Expected Behavior
It would be great if the application looks identical in all the 3 platforms.

Basic Information
Platform Target Frameworks:
UWP:

**Comment by brianro** [comment]
+UpVote

**Comment by hbraasch** [comment]
+UpVote

**Comment by Samit-BTE** [comment]
https://www.syncfusion.com/feedback/15616/provide-a-ripple-effect-animation-on-button-click-in-uwp-platform 

even 3rd party library fail to provide support for this, hope Xamarin team fix this issue for Xamarin UWP developers.

**Comment by brianro** [comment]
@samhouts Do you have a plan for supporting UWP in Xamarin and including material design or do you have a different technical path we should be following?

**Comment by nicolgit** [comment]
please add material design on UWP, the app looks so *different* from the android and ios ones...

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the .NET MAUI repo and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
