### ISSUE TITLE
[Enhancement] Listview MenuItem icon for UWP

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10556]
## Summary
i think UWP deserves it ! and i don't think there is a limitation or problem for that, UWP ContextMenu supports icons.
and please show the menu where we Right clicked, not only center.

## Platform
UWP

**Comment by EmilAlipiev** [comment]
Good idea but xamarin forms is cross platform and this is not suitable for mobiles. It can be probably implemented using custom renderer.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
