### ISSUE TITLE
[Bug] CollectionView and iOS 9.3.5

### ISSUE THREAD

**Issue by Maxima078** [xamarin/Xamarin.Forms#10567]
# Description
Some users using iOS 9.3.5 are facing app crashing when CollectionView is updated.
Is CollectionView supposed to works with iOS 9.X?

### Steps to Reproduce

1. Bind ItemsSource of CollectionView to an ObservableCollection
2. Modify this collection and notify the view

### Expected Behavior
Items are displayed
### Actual Behavior
The app crash
### Basic Information
Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x19bed260> {length = 2, path = 1 - 0}
- Version with issue: Xamarin.forms 4.4.0.99
- Platform Target Frameworks:
  - iOS:  9.3.5
- Affected Devices: iPad 2 at least

### Reproduction Link

Unfortunately I cannot reproduce this issue since I do not have any iOS 9.3.5 device. I cannot use simulator since XCode oldest iOS version is 10.X

**Comment by StephaneDelcroix** [comment]
could you please provide a sample repro app, and a stack trace of the crash ?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by CleverSoftwarePoland** [comment]
I can reproduce the problem on iPod with 9.3.5.
CollectionView will crash when you set ItemSizingStrategy to MeasureAllItems 
This is my sample view:

<CollectionView 
                ItemsSource="{Binding VehicleCollection}" 
                SelectionMode="Single" 
                SelectedItem="{Binding SelectedVehicle, Mode=TwoWay}" 
                BackgroundColor="Transparent" 
                Margin="10,10,10,0" ItemSizingStrategy="MeasureAllItems">
                    <CollectionView.ItemsLayout>
                        <GridItemsLayout x:Name="gdLayout" Orientation="Vertical" HorizontalItemSpacing="10" VerticalItemSpacing="10" Span="2" />
                    </CollectionView.ItemsLayout>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <Grid BackgroundColor="Transparent"  >
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="130"/>
                                </Grid.RowDefinitions>
                            </Grid>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
     </CollectionView>

**Comment by idrish-rishabhsoft** [comment]
Any fix? We are struggling with same problem.

**Comment by hartez** [comment]
@CleverSoftwarePoland or @idrish-rishabhsoft - can you give us any more information? Some complete markup for your CollectionView? Are you still encountering this problem with the latest version of Forms (4.7)?

**Comment by iducool** [comment]
Xamarin Forms version : 4.8.0.1269
Here is a snippet [From code behind we are attaching data source based on respose of service], 
```
<CollectionView
                    x:Name="CvCategories"
                    SelectionMode="Single"
                    SelectionChanged="CvCategories_SelectionChanged">
                    <CollectionView.ItemsLayout>
                        <GridItemsLayout
                            Orientation="Vertical"
                            Span="2"></GridItemsLayout>
                    </CollectionView.ItemsLayout>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <StackLayout
                                Orientation="Vertical">
                                <Frame
                                    Margin="5, 10, 5, 0"
                                    Padding="0"
                                    CornerRadius="20"
                                    IsClippedToBounds="True"
                                    BackgroundColor="Transparent">
                                    <StackLayout>
                                        <Image
                                            Source="{Binding Path=ImageUri}"
                                            Aspect="AspectFill"
                                            HorizontalOptions="Center"
                                            VerticalOptions="Center" />
                                        <Label
                                            Margin="0, -8, 0, 0"
                                            HorizontalOptions="FillAndExpand"
                                            VerticalOptions="End"
                                            HeightRequest="40"
                                            VerticalTextAlignment="Center"
                                            HorizontalTextAlignment="Center"
                                            Text="{Binding Path=name}"
                                            BackgroundColor="#99C679"
                                            FontAttributes="Bold"
                                            Style="{StaticResource CategoriesNameStyle}" />
                                    </StackLayout>
                                </Frame>
                            </StackLayout>
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
```

**Comment by iducool** [comment]
@hartez Do you need anything else to look into issue. Please note that "idrish-rishabhsoft" belongs to me only.

**Comment by rmarinho** [comment]
@iducool  do you mind update a small sample? it would be easier for us to try reproduce and find the issue.

**Comment by rmarinho** [comment]
I tried to reproduce using this sample, can you tell me what's missing to reproduce it ..

[XFCollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/5256430/XFCollectionView.zip)

**Comment by CleverSoftwarePoland** [comment]
This problem is only related to older phones with iOS 9.3.5 and last time i was testing it it was crashing every time no matter what you did and bug was related to "ItemSizingStrategy set to MeasureAllItems"

**Comment by rmarinho** [comment]
@CleverSoftwarePoland  can you reproduce using that sample i posted above ?

**Comment by CleverSoftwarePoland** [comment]
> @CleverSoftwarePoland can you reproduce using that sample i posted above ?

Not right now, i don't have test device any more, there is no way to test it on emulator, emulators are not available anymore for this version.

**Comment by samhouts** [comment]
Is anyone else able to reproduce this issue with the [sample](https://github.com/xamarin/Xamarin.Forms/issues/10567#issuecomment-696194403)?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by maximusfatigue** [comment]
I can confirm this is happy with out production app,  reports from a client with a number of ipad 2 devices are crashing.

**Comment by Jouna77** [comment]
Still getting this on iOS 9.3.6

**Comment by Jouna77** [comment]
> I can reproduce the problem on iPod with 9.3.5.
> CollectionView will crash when you set ItemSizingStrategy to MeasureAllItems
> This is my sample view:
> 
> 
> <CollectionView.ItemsLayout>
> 
> </CollectionView.ItemsLayout>
> <CollectionView.ItemTemplate>
> 
> 
> <Grid.RowDefinitions>
> 
> </Grid.RowDefinitions>
> 
> 
> </CollectionView.ItemTemplate>

I tried setting ItemSizingStrategy  to MeasureFirstItem but it still crashes

**Comment by maximusfatigue** [comment]
I am also getting this on ipad 2.

**Comment by quintanalexis1989** [comment]
Why this bug are closed? I am also getting this issue on iPhone 6 with 12.4.9 iOS version

**Comment by jaurestchoffo** [comment]
Why this bug are closed? I am also getting this issue on iPhone 6 with 12.5 iOS version
