### ISSUE TITLE
[Enhancement] BackButtonBehavior allow both TextOverride and Iconoverride on Android

### ISSUE THREAD

**Issue by ymebrugts** [xamarin/Xamarin.Forms#10560]
## Summary
When using Shell.SetBackButtonBehavior Iconoverride and Textoverride it currently only shows the overriden icon. Showing both should be made possible for android just like iOS. The new design direction is similar looking apps so I'd like to be able to make it look the same.  
## API Changes

The syntax stays the same but this currently does not show text on android:

`Shell.SetBackButtonBehavior(this, new BackButtonBehavior { TextOverride = "Back", IconOverride = 
     new FontImageSource() { FontFamily = fontFamily.ToString(), Glyph = "\uf12c" } });
`

## Intended Use Case
Same look on both iOS and Android

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
