### ISSUE TITLE
[Bug] SwipeView Open methods does not work for RightItems

### ISSUE THREAD

**Issue by mariaszek9003** [xamarin/Xamarin.Forms#10563]
Open method for SwipeView doesn't work for RightItems, it works for left items but not for right. Tested on Android and iOS.

### Steps to Reproduce

1. Add SwipeView to ViewPage
2. Add RightItems to that SwipeView
3. Invoke Open(OpenSwipeItem.RightItems) method on that SwipeView

### Expected Behavior
Open method should open view and reveal right items.

### Actual Behavior
Open method does nothing

### Basic Information
- Xamarin Forms: 4.6.0.726
- IDE: Visual Studio for Mac, ver 8.5.4 (build 12)
- Xcode ver 11.4.1

### Reproduction Link
https://github.com/mariaszek9003/SwipeViewTest
or you can either test it on your own SwipeView demo repository, just use right items instead of left on SwipeViewProgrammaticPage: https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SwipeViewDemos

**Comment by jsuarezruiz** [comment]
Thanks for the reproduction sample @mariaszek9003.

**Comment by haavamoa** [comment]
I tested the same but with `TopItems` and that did not work either. :(

**Comment by WilliamWatterson86** [comment]
Have the same issue here - as a work around I rotated my swipeview by 180.  And then rotated the items by another 180.  Seems to work OK for now but not ideal.

**Comment by Rothanan** [comment]
SwipeView.Open() is not working at all.

**Comment by jsuarezruiz** [comment]
@WilliamWatterson86 and @Rothanan Could you try using the NuGet from https://github.com/xamarin/Xamarin.Forms/pull/10575?

**Comment by Rothanan** [comment]
Im Sorry, I tought this was an UWP Topic, I'm having trouble with this in UWP.

The solution tou mentioned doesnt fiz It for UWP.

**Comment by Only-Xam** [comment]
[UWP] SwipeView.Open() is still not working with latest available version Xamarin.Forms.5.0.0.1558-pre3
