### ISSUE TITLE
[Bug] PageRenderer forces EndEditing on iOS

### ISSUE THREAD

**Issue by jefffhaynes** [xamarin/Xamarin.Forms#10577]
### Description
In the PageRenderer, a tap recognizer is injected that is nearly impossible to cancel without removing.

https://github.com/xamarin/Xamarin.Forms/blob/5062f533715e629eb572e5ed8a03388ed05a1d47/Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs#L234

This causes editing to end on any active text fields, whether that was the intended behavior or not.  It is unclear why the framework is assuming this behavior.

### Workaround

It is possible to create a custom page renderer and remove the tap:

```
var nativeGestureRecognizer = NativeView.GestureRecognizers.FirstOrDefault();
if (nativeGestureRecognizer != null)
{
    NativeView.RemoveGestureRecognizer(nativeGestureRecognizer);
}
```

**Comment by StephaneDelcroix** [comment]
what would you propose as api for changing this behavior ?

**Comment by jefffhaynes** [comment]
Good question.  Obviously it's tough because it would be really nice to remove it but I can see that potentially breaking existing behavior.  It doesn't apply to Android or UWP so it would be weird to add a nonspecific property at the control level (and I personally don't find the platform-specific properties to be very discoverable).  It may be the case that implementors are left having to override the renderer and the only thing to do is make that more straightforward.

If that's the answer, I would say simply move the gesture setup into it's own virtual method.  Unfortunately, an overall lack of control inversion throughout the framework makes that awkward, since it's never obvious when a base method needs to be called.  The lack of a template method pattern in the renderers is a constant source of pain and deviates in design from most other MS frameworks.  I realize the intent was to stay true to the native API but when coupled with a bunch of functionality being inserted behind the scenes it sort of creates a worst-of-both-worlds situation.  Anyway, I digress...

The best option may be something like a virtual property on the page renderer that can be overridden, but I would defer to the team in terms of what would most closely match existing patterns.

Or you could simply take it out and see what happens :)

If nothing else I hope things like this will give pause in the future when considering "adding value" behind the scenes.  Personally I think Xamarin should stick to platform abstraction and save us having to guess what extra things have been added between the app and the platform.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
