### ISSUE TITLE
[Bug][iOS] NavigationPage.HideNavigationBarSeparator="true" doesn't work from XAML

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10578]
### Description

On previous versions of iOS it was possible to hide the navigation bar separator, using XAML, with the `NavigationPage.HideNavigationBarSeparator` platform-specific. However, this doesn't work on iOS 13.4.

This issue was previously reported in #10438 and found not to be a problem. After further investigation I can be more precise about the exact issue:

1. The platform-specific doesn't work at all from XAML (I've tried setting `NavigationPage.HideNavigationBarSeparator="true"` on both a `NavigationPage` instance and a `ContentPage` instance. Neither results in the separator being hidden.
1. The platform-specific works from C#, provided that it's not also been set from XAML. When it has been set in XAML, it can be coaxed back into life from C# with specific repro steps (see below).

### Steps to Reproduce

1. Run the attached sample on iOS 13.4.

### Expected Behavior

Navigation bar separator is hidden by default, and the hide/show buttons work.

### Actual Behavior

The sample as provided:

- Navigation bar separator is shown.
- Hide button has no effect. However, pressing the Show button (which produces no visual change) then the Hide button results in the navigation bar separator being hidden.

The sample when `ios:NavigationPage.HideNavigationBarSeparator="True"` is removed from **MyNavigationPage.xaml**:

- Navigation bar separator hides/shows as expected (from C#).

### Basic Information

- Version with issue: 4.6.0.726
- IDE: VSMac 8.5.4
- Platform Target Frameworks: 
  - iOS:  13.4

### Reproduction Link

[test.zip](https://github.com/xamarin/Xamarin.Forms/files/4581264/test.zip)
### Workaround

This platform-specific works fine from C#, provided that it's not set from XAML first.

**Comment by idchlife** [comment]
Hello! Thank you for repro!

I honestly don't understand how this works.

Using version 4.6.0.726 of Xamarin.Forms, I'm using Tabbed Page.

I cannot use .MainPage in TabbedPage so I created subclass of NavigationPage:

```csharp
  public class NoBarSeparatorNavigationPage : Xamarin.Forms.NavigationPage {
    public NoBarSeparatorNavigationPage(Xamarin.Forms.Page page) : base(page) {
    }

    protected override void OnAppearing() {
      Debug.WriteLine("Hiding navigation bar");
      On<iOS>().SetHideNavigationBarSeparator(true);
      base.OnAppearing();
    }
  }
```

I use it in MainPage.xaml file instead of <NavigationPage> to store pages inside Tabbed Page

I'm using OnAppearing because constructor call to hide separator does not even work.

Unfortunately it hides separator, makes background of navigation bar somewhat... grayish?
Also it would reappear again when switching tabs in Tabbed Page layout.

<img width="363" alt="изображение" src="https://user-images.githubusercontent.com/4563032/81100812-d93d9b80-8f15-11ea-87e1-817266952505.png">

**Comment by idchlife** [comment]
I hope this may be of help:

No code like:

```csharp
 var bar = NavigationBar;

      bar.Translucent = true;
      bar.StandardAppearance.ShadowColor = UIColor.Clear;
      bar.StandardAppearance.ShadowImage = new UIImage();
```

works in ViewDidLoad in custom renderer for NavigationPage, when used in Tabbed Page.

BUT

it works flawlessly in ViewWillAppear method

**Comment by AaronBastian** [comment]
I am having an identical issue here as well. The only persistent resolution for me was the custom renderer.

**Comment by idchlife** [comment]
@AaronBastian please share your solution, because my tries with custom renderer were unhelpful, since when I changed translucent or background color - separator returned by some code inside Xamarin Forms

**Comment by AaronBastian** [comment]
@idchlife my solution was as follows:
`
       public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            UINavigationBar.Appearance.TintColor = UIColor.White;
        }

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
            var bar = NavigationBar;
            bar.StandardAppearance.ShadowColor = UIColor.Clear;
            bar.StandardAppearance.ShadowImage = new UIImage();
        }
`
I did NOT keep my changes to the XAML because they were completely ineffective. The renderer was my only solution.

**Comment by Domik234** [comment]
Hey,
I used this temporary fix for 4.5.356 and newer (for those, who found this issue and cannot solve it). It isn't best way to do it, but works.
```
[assembly: ExportRenderer(typeof(**NavigationPage/CustomNavigationPage**), typeof(NoLineNavigationPageRenderer))]
namespace MyLibrary.Renderers
{
    public class NoLineNavigationPageRenderer : NavigationRenderer
    {

        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            if (Element is Xamarin.Forms.NavigationPage navigationPage)
            {
                //iOS older version fix
                NavigationBar.SetBackgroundImage(new UIKit.UIImage(), UIKit.UIBarMetrics.Default);
                NavigationBar.ShadowImage = new UIKit.UIImage();
                NavigationBar.ClipsToBounds = true;
                try //Newest iOS version fix - trycatch isn't optimal
                {
                    NavigationBar.ScrollEdgeAppearance.ShadowImage = new UIKit.UIImage();
                    NavigationBar.ScrollEdgeAppearance.ShadowColor = null;
                }
                catch (Exception) { }
            }
        }
    }
}
```

**Comment by acuntex** [comment]
@davidbritch Did it ever work on a ContentPage instance?

I can't see code in the current NavigationRenderer that makes me believe otherwise.

**Comment by pwillies** [comment]
@pauldipietro @jsuarezruiz @samhouts @StephaneDelcroix @davidbritch Hi XF Team, This is on our priority list. Also something visual, but it's a regression that can be seen on most views in our app.

**Comment by jsuarezruiz** [comment]
Tested with Xamarin.Forms 5.0-pre NuGet package and in the 5.0 branch and the issue seems to be fixed.

**Comment by Dmbandit** [comment]
Guys there is still a slight issue with the iOS NavigationBarSeparator. The previous issues are fixed but, when you are on a page where the NavigationBarSeparator is hidden, put the app into the background and bring it back to the foreground again, the NavigationBarSeparator isn't hidden anymore. Putting the hide code into OnAppearing doesn't make any difference. I have replicated this on both iOS 14.2 and iOS 14.3.

**Comment by Domik234** [comment]
> Guys there is still a slight issue with the iOS NavigationBarSeparator. The previous issues are fixed but, when you are on a page where the NavigationBarSeparator is hidden, put the app into the background and bring it back to the foreground again, the NavigationBarSeparator isn't hidden anymore. Putting the hide code into OnAppearing doesn't make any difference. I have replicated this on both iOS 14.2 and iOS 14.3.

Putting the app into the background and then to foreground back works for me and separator is hidden, but switching between light and dark mode makes it visible. 
* Tested on iPhone XS, iOS 14.2
* VS19 16.8.4
* Xamarin.iOS 14.8.0.3
* Xamarin.Forms 5.0.0.1874

**Comment by idchlife** [comment]
This is so strange... Why does this bug still here? I mean the bug persists even on Swift side? I saw a lot of stackoverflow posts with question how to hide separator in Swift and many of them stops working at some point.
Weird.

I hope it can be resolved in some way in Xamarin Forms

**Comment by keithhol** [comment]
@samhouts @jsuarezruiz @davidbritch 

Can this issue be re-opened (or a new one created) so the highlighted bugs above can be resolved?
