### ISSUE TITLE
[Bug] WPF ModalPage's NavigationBar is missing

### ISSUE THREAD

**Issue by mhrastegari** [xamarin/Xamarin.Forms#10576]
### Description
There is no NavigationBar in WPF's modal page!

### Steps to Reproduce
1. Create a ContentPage
2. Open it as a ModalPage

### Basic Information
- Version with issue: 4.6
- Last known good version: unknown
- IDE: Visual studio 16.5.4
- Platform: WPF

### Screenshots
WPF without NavigationBar on the left / UWP with NavigationBar on the right

![Screenshot (596)](https://user-images.githubusercontent.com/42671084/81062585-7800d280-8eeb-11ea-8048-d93556b15758.png)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
