### ISSUE TITLE
[Enhancement] Implementing DisplayPromptAsync for GTK Platform

### ISSUE THREAD

**Issue by Grayhead1** [xamarin/Xamarin.Forms#10579]
## Summary
I don't know if it's an oversight, I didn't find any explanation about the lack of the DisplayPromptAsync feature in Xamarin.Forms.Platform.GTK.

## Intended Use Case
Being able to use a prompt message in GTK projects and for multiplatform projects to keep a certain consistency in the shared code base.

**Comment by jfversluis** [comment]
I don't think this won't be happening for Xamarin.Forms anymore unless someone will provide us with a PR to implement it. Thanks for your suggestion!
