### ISSUE TITLE
[Bug] WPF MasterDetail page doesnt render correctly, unless forcing a Window Measure

### ISSUE THREAD

**Issue by tessarolli** [xamarin/Xamarin.Forms#10584]
### Description
When i change the content page currently displayed on Master or Details page of MasterDetailPage, the new content is not displayed correctly, unless i force a redraw/measure/whatever its called on the container window, by re-dimensioning it (either a restore/maximize or a simple drag to change the window size)
 
### Steps to Reproduce
1. Add a master details page to your project 
2. Add some ContentPage to Master and Detail
3. Set Application.Current.MainPage to this MasterDetailsPage
4. Observe the page not beeing rendered correctly on the window
5. Do any redimensioning on the window, and observe the page showing up correctly!

### Basic Information
- Version with issue: 4.5 and upwards
- Last known good version: 4.4.0.991864

**Comment by tessarolli** [comment]
I've created a small reproduction project.

To test it, simply build and run, and try clicking Page 1 or Page 2 buttons to change MasterPage.DetailPage property
It'll not render properly, but if you change IsPresented, or resize window, or minimize/restore, it'll render.
Same goes for the MasterPageProperty.

I've wasted this whole morning debugging WPF source, trying to find the problem, but i couldn't..

Last working version was 4.4.*


[MasterPage_Bug_Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4616224/MasterPage_Bug_Repro.zip)

**Comment by Masterofdesasta** [comment]
Are there any plans to fix this bug?

**Comment by tessarolli** [comment]
By switching to FlyoutPage this bug still happens

Should we start the birthday party preparations?

Come on guys, we are still using version 4.4 because of it

Please fix. 
I couldn't.. I've tried...

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
