### ISSUE TITLE
[Bug][iOS] CollectionView stops updating after its cleared

### ISSUE THREAD

**Issue by jvlppm** [xamarin/Xamarin.Forms#10597]
### Description

CollectionView stops updating after its ItemsSource (ObservableCollection) gets empty.

### Steps to Reproduce

1. Create a CollectionView with its ItemsSource bound to an ObservableCollection
2. During runtime, add items to the collection
3. Remove all items (one by one)
4. Add an item to the list

### Expected Behavior

Items get removed from view, and then a new one appears on screen.

### Actual Behavior

Items get removed from view, and then new items don't show up.

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: 4.5.0.725
- IDE: Visual Studio for Mac (Community)
- Platform Target Frameworks:
  - iOS: 12.4.6, 13.4.1
### Reproduction Link

[EmptyCollectionBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4590310/EmptyCollectionBug.zip)

### Workaround

Using Clear before adding new items makes other errors popup, working around these issues are like crossing a mine field.

Reverting back to Xamarin.Forms 4.5.0.725 seems to fix it.

**Comment by jvlppm** [comment]
After building with master I could not reproduce this issue and this seems to be fixed already.
I'm using the nightly nuget package build now and it is working as expected.

**Comment by StephaneDelcroix** [comment]
let's close it then.
