### ISSUE TITLE
When clicking in the editText within the ListView Header, the FocusChange is called thrice.

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/Xamarin.Forms#10591]
### Description

When clicking in the editText within the ListView Header, the FocusChange is called thrice.

### Steps to Reproduce

1.  Focus the EditText in ListView Header.
2.  The breakpoint in FocusChange is invoked thrice.

### Expected Behavior

FocusChange should invoke only once.

### Actual Behavior
FocusChange is invoked thrice.

### Basic Information
  - Android: 8.1.0 (Moto G5)

The same issue is not reproduced in the Samsung S8 device.

### Reproduction Link
[SampleinXamarinAndroid.zip](https://github.com/xamarin/Xamarin.Forms/files/4586717/SampleinXamarinAndroid.zip)

**Comment by StephaneDelcroix** [comment]
that can happen

**Comment by RabhiaBehamK** [comment]
Is there any update?

**Comment by RabhiaBehamK** [comment]
Is there any update?

**Comment by RabhiaBehamK** [comment]
Can you please check this with a high priority?

**Comment by PureWeen** [comment]
@RabhiaBehamK 

Looking at your sample this is just a native android sample not a Xamarin.Forms related issue

This is a better question for StackOverflow because it's a "By design" android behavior and not something we have any control over
