### ISSUE TITLE
[Enhancement] UWP : Support Acrylic material from App.xaml

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10594]
## Summary
I know there is some requested Fluent design visual for Xamarin.Forms(for all platforms),
but i think my request would be easier to implement! because it's just for UWP.

## Example
For example set the specific background for UWP's NavigationBar(CommandBar) from the App.xaml in the UWP Project :
```
<Application
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:uwp="using:Xamarin.Forms.Platform.UWP">
    <Application.Resources>
        <ResourceDictionary>
            <AcrylicBrush x:Key="CustomInAppAcrylicBrush"
                          BackgroundSource="HostBackdrop"
                          TintOpacity="0.1" TintColor="{ThemeResource SystemChromeMediumLowColor}"
                          FallbackColor="{ThemeResource SystemChromeMediumLowColor}"/>
             <Style TargetType="uwp:FormsCommandBar">
                <Setter Property="DefaultLabelPosition" Value="Right"/>
                <Setter Property="Height" Value="48"/>

         <!-- At this moment it breaks the App -->
                <Setter Property="Background" Value="{CustomResource CustomInAppAcrylicBrush}"/>
       
             </Style>
            <x:Double x:Key="AppBarThemeCompact">48</x:Double>
        </ResourceDictionary>
    </Application.Resources>
</Application>

```
## Platform 
UWP

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
