### ISSUE TITLE
CustomRender button inside of collectionview [Bug] 

### ISSUE THREAD

**Issue by JohnTraDolta** [xamarin/Xamarin.Forms#10596]
### Description
I have made a custom render and put it inside a collection view 

it seams like the button is blocking the SelectionChangedCommand 

this does only happen when i put my CustomButton logic inside the OnTouchEvent with the MotionEventActions.Up.

Can't put it inside of MotionEventActions.Down, becuase then it triggers when i am sliding 

### Steps to Reproduce
https://github.com/JohnTraDolta/LottoApp

1. Pull and run the project 
2. Press a button with a number

### Expected Behavior
The buttons number should register inside the white frame

### Actual Behavior
the button activates and does not registrer inside the white fram

### Reproduction Link

https://github.com/JohnTraDolta/LottoApp

### Workaround
1. Move logic from MotionEventActions.Up to MotionEventActions.Down - this is introducing a new problem (Don´t want the button to activate without registering)

**Comment by rmarinho** [comment]
Hi, why don't you do the this on the forms side with VisualStates? For example adding a tab to a border with a label inside? 

Why the need of a custom renderer ?

**Comment by JohnTraDolta** [comment]
I don't actually have a clue, seams a lot easier. I'm having a hard time to figure out when to use custom renderers and when not - but anyways thanks will try to refractor it.

**Comment by hartez** [comment]
This fundamentally won't work - you're processing the motion events at the level of your custom renderer, which means that the underlying item in the RecyclerView will never receive them to interpret them as a selection. 

You could do some complicated work in a custom renderer (using OnInterceptTouchEvent) to make this work, but a much easier option would be to add a TapGesture to your NumberButton View with a Command which updates the SelectedItems collection of you view model.
