### ISSUE TITLE
[Bug] [Regression] [UWP] Animation on Boxview broken 4.6.0.726 (works in 4.5.0.725)

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#10590]
### Description
Sample contains an animation that expands and fades up the opacity of a boxview. In 4.5.0.725 this worked but after upgrading to 4.6.0.726 this no longer works

I have only tested on uwp so far

### Steps to Reproduce

1.  Open sample on uwp
2. click "Change Colour" button
3. bug - see nothing happens
4. downgrade Xamarin.Forms to 4.5.0.725 and replicate steps, see animation works

### Expected Behavior
animation works

### Actual Behavior
animation doesnt work

### Reproduction Link
[Animations.zip](https://github.com/xamarin/Xamarin.Forms/files/4586231/Animations.zip)

**Comment by bmacombe** [comment]
I suspect #10540 will fix this, the reproduction looks like it is using the color property

**Comment by JKennedy24** [comment]
@bmacombe I think you're probably right

**Comment by JKennedy24** [comment]
Fixed by 4.6.0.772 (probably the fix that was linked in the comments)
