### ISSUE TITLE
Problems with [QueryProperty] in Shell Navigation

### ISSUE THREAD

**Issue by pfafft33** [xamarin/Xamarin.Forms#10607]
### Description
I can't get [QueryProperty] to pass a Json-serialized instance of an object to my page.

### Steps to Reproduce
I have included screen shots of the calling page, the target page, and the results of the Json serialization.

### Expected Behavior
I expect that the shell navigation call will pass the Json in the QueryProperty myAppParameter, to the Parameters page where it will be deserialized into the _myMedLemnApp object instance.

### Actual Behavior
I have set breakpoints and stepped through the code to determine that the Json IS getting produced in the calling page (EquationLibPage). However, when the code gets to the constructor for the target page (ParametersPage), the receiving property (strMedLemnApp) is NULL.
It seems like the QueryProperty just isn't being passed to the target page.

![QueryProperty Issue 20200507 - EqLib](https://user-images.githubusercontent.com/47510341/81313522-94b51b80-904d-11ea-8eb1-722d1ca540be.PNG)

![QueryProperty Issue 20200507 - ParamPage](https://user-images.githubusercontent.com/47510341/81313650-c332f680-904d-11ea-9091-c4bdc994affb.PNG)

[TAP Json myMedLemnApp.txt](https://github.com/xamarin/Xamarin.Forms/files/4593924/TAP.Json.myMedLemnApp.txt)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
I have attached 3 screenshots. One to show the code of the calling page (EquationLibPage). One to show the code of the target page (ParametersPage). And, one to show the Json of the serialized object instance.

**Comment by StephaneDelcroix** [comment]
the purpose of queryattributes is to pass small IDs that you will use to retrieve info from your local storage implementation, not passing serialized object.

but that should work

could you provide a small repro project ? thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by syedhoque89** [comment]
>the purpose of queryattributes is to pass small IDs that you will use to retrieve info from your local storage implementation, not passing serialized object.

Ok so how do we pass an object here? Consider this:

You fetch data over the internet and display in a `CollectionView`. The fetched data already contains lets say `Name` and `Details`. On `CollectionView` we only display name and when user taps `Name` we navigate to `Details` view and want to display details. It'd be super easier if we can just pass the selected Item as a param when we navigate using await `Shell.Current.GoToAsync(..)` But according to the quote above are you suggesting we just pass the `Name` to the `Details` page, fetch the data again (regardless if we are to cache it locally it seems it'd be a waste to summon the data twice) and fileter down by the `Name` ?? This is silly

**Comment by pictos** [comment]
@syedhoque89 you can create a `ShellNavigationService` for that, here's a [sample](https://github.com/pictos/ShellPresentation/tree/xamarin_assemble) and if you want you can see my talk about it [here ](https://youtu.be/JQG04O9tfV8)

**Comment by syedhoque89** [comment]
Thanks @pictos ! Thats very helpful. However, I still dont understand why this fucntionality is not provided out of the box and we have to go whacking in our hacks.

**Comment by pictos** [comment]
@syedhoque89 isn't a hack, even with NavigationPage is normal for you to create a navigation service to use. There is an open proposal for Shell to support passing objects in the GoToAsync, but I don't think that will be on XF 5.0. You can check the proposal here #6848
