### ISSUE TITLE
[Bug] On iOS when switched to dark mode the ImageButton is not updated

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#10609]
### Description
When switched to dark the `ImageButton` control is not updated although I have provided images for light and dark mode.

This was theoretically "fixed" in #8495 but this is still not working.

### Steps to Reproduce

1. Run this project on iOS.
[DarkModeTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4595153/DarkModeTest.zip)
2. Switch to dark mode.
3. As you can the see is not updated.

### Expected Behavior
The icon should update to the dark version.

### Actual Behavior
The icon is not updated at runtime. It updates only if I close the app and relaunch it.

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: none, this has never worked
- IDE: VS for Mac 8.5.4 (build 12)
- Platform Target Frameworks: 
  - iOS:  13.4

**Comment by StephaneDelcroix** [comment]
#10442 should fix your issue.

**Comment by StephaneDelcroix** [comment]
could you please test ? thanks

**Comment by Mikilll94** [comment]
@StephaneDelcroix 
I have checked the latest nightly (4.7.0.760-nightly), but I cannot test if this bug was fixed, because of another bug.

When I am leaving the app (not closing, but just leaving), the app crashes:
```
System.ArgumentNullException has been thrown
value cannot be null
```
in Main.cs

**Comment by PureWeen** [comment]
@Mikilll94 can you test with the latest version? That ArgumentNullException should be fixed now

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
