### ISSUE TITLE
Resharper: Can not resolve symbol RelativeSource RelativeSourceExtension

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10605]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1008433/resharper-can-not-resolve-symbol-relativesource-re.html)._

---
### Sample

[sample] (https://github.com/xamarin/xamarin-forms-samples/tree/master/DataBindingDemos)

### Description

Hi all. 

I have a problem and suppose many of the others have this issue too. I just downloaded the xamarin forms official  sample and tried to debug it. Everything works fine except recognizing extension properties like "RelativeSource" or "AncestorType" by Resharper.

My Resharper does not recognize 'RelativeSource' telling me that "Can not resolve symbol RelativeSource RelativeSourceExtension". I have tried to update the Resharper but it did not help me. The Resharper works fine when I create custom markup extension (does not matter the content inside the extension. The properties which I define inside extension class are recognizable by Resharper). So any ideas how can I solve this? 

### Steps to Reproduce

1. Open app 
2. Go to RelativeSourceSelfPage.xaml
3. Check BoxView Control

### Expected Behavior

"{Binding Source={RelativeSource Self}, Path=WidthRequest}" should be recognizable by Resharper

### Actual Behavior

The RelativeSource is not recognizable by Resharper

### Information

- IDE and IDE version: Microsoft Visual Studio Community 2019 Version 16.5.1 
- Resharper version: 2019.3.4

---
#### Visual Studio Feedback System on 4/27/2020, 05:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Vardan Sargsyan on 5/1/2020, 00:18 AM: 

<p>thank you !</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
RelativeSource is quite new in XF, reshaper probably do not support it yet. please file an issue there, we have no relation with reshaper.
