### ISSUE TITLE
Unwanted white space in Xamarin.Android WebView 

### ISSUE THREAD

**Issue by androidmads** [xamarin/Xamarin.Forms#10602]
### Description
I have created a Web View control for Xamarin.Forms using Android View Renderer as recommended in the link [https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/customrenderers-hybridwebview/](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/customrenderers-hybridwebview/). It is working fine for Xamarin.Forms Version 3.1 and facing issue in Xamarin.Forms 4.4. Below screenshots for reference.

<img src="https://github.com/androidmads/Images/blob/master/Screenshot_2020-05-07-20-51-30.png?raw=true"/>

### Expected Behavior
Webview content should be in full screen
### Actual Behavior
White Space is displaying and varies based on the screen control's space occupation
### Basic Information

- Version with issue: Xamarin.Forms 4.5
- Last known good version: Xamarin.Forms 3.1
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: 10.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img src="https://github.com/androidmads/Images/blob/master/Screenshot_2020-05-07-20-51-30.png?raw=true"/>
<img src="https://github.com/androidmads/Images/blob/master/Screenshot_2020-05-07-20-51-37.png?raw=true"/>

**Comment by StephaneDelcroix** [comment]
please provide a repro project. also, your images are 404'ing

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
