### ISSUE TITLE
[Enhancement] Grouping For Multiple Shell FlyoutItems

### ISSUE THREAD

**Issue by ChevronTango** [xamarin/Xamarin.Forms#10603]
## Summary
I'd like there to be a way to group multiple FlyoutItem's in a Shell so they display with dividers between them and the other Menu Items.

## Description
Currently the only way to group Items together is to use a single FlyoutItem and mark it's `FlyoutDisplayOptions="AsMultipleItems"` however if you are using a FlyoutItem as a `AsSingleItem`, perhaps to take advantage of the tabbing, there is no way to customise the display of the elements within the Shell menu to "group" them together with a nice divider to separate them. Either the ability to add a Divider element into the shell or group elements together so they can be added or subtracted in code behind would work well here.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
