### ISSUE TITLE
ContentView not honouring VM propeties

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10606]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1012012/contentview-not-honouring-vm-propeties.html)._

---
I have a forms project (targets android and iOS). It uses mvvmlight for the mvvm bits.

The main project has a ContentPage which then adds contentviews as and when required. The main coteent page has a gridview at the bottom of the layout which the user clicks. The code behind has an PropertyChanged method which intercepts a change in a property int the main VM that adds the ContentView.

The ContentView calls a couple of methods to set up values.

If I click something though on the ContentView, the MainViewModel is alerted rather than the ViewModel the BindingContext on the ContentView says to use.

The View the ViewModel is associated with rather than the VM the main ContentPage is bound to should be used.

Using Xam.Forms 4.5.0.657. Testting on Samsung S8 (Android 9)

---
#### Visual Studio Feedback System on 4/29/2020, 10:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
