### ISSUE TITLE
[Bug] MessagingCenter.Subscribe causes Unhandled Exception in a UWp Project,that is running in release mode

### ISSUE THREAD

**Issue by Martin-Stein** [xamarin/Xamarin.Forms#10600]
HI,

I have a UWP-Project that should send keyboard events from the form to a Entry object.
It works fine , as long I run the project in debug mode. when I compile and run it in release mode I receive this error message
![2020-05-07 13_47_08-Window](https://user-images.githubusercontent.com/32069131/81291145-912f8d80-9069-11ea-97a9-e917575dc39e.png)

All components are up to date.

Here is my code:

in UWP App.Xaml.cs

 protected async  override void OnLaunched(LaunchActivatedEventArgs e)
        {
...
Xamarin.Forms.Forms.Init(e); 
...
 Window.Current.Activate();
 Windows.UI.Core.CoreWindow.GetForCurrentThread().KeyDown += App_KeyDown;
…
}

 private void App_KeyDown(Windows.UI.Core.CoreWindow sender, Windows.UI.Core.KeyEventArgs args)
        {
            Xamarin.Forms.MessagingCenter.Send<IKeyboardListener, string>(this, "KeyboardListener", args.VirtualKey.ToString());
        }

in my shared code: MainPage.xaml.cs:
 public MainPage()
        {
            
            InitializeComponent();

            MessagingCenter.Subscribe<IKeyboardListener, string>(this, "KeyboardListener", (sender,args) =>
            {
if(args =="Enter")
LblCustNumber_Completed(entryCustNumber, null);
else
{
case "Number1":
                //        case "NumberPad1":
                //            entryCustNumber.Text += "1";
                //            break;
…
}
}

Thanks,

Martin

**Comment by StephaneDelcroix** [comment]
could you please provide a (non-translated) stack trace, a repro project, and some more information, as requested by the template.

I'm not even sure I understand your issue...

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
