### ISSUE TITLE
[Bug] [iOS] Group header in xamarin forms list view isn't visible in release mode

### ISSUE THREAD

**Issue by LeonardoPatti** [xamarin/Xamarin.Forms#10616]
I have a list view with group header that isn't visible in release mode, just in debug mode.
I'm using a GroupHeaderTemplate to define the view

**Comment by RyanKindley** [comment]
@LeonardoPatti it happens the same for Android.
I found out it is caused by the linker: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker
If you set up "Link SDK Assemblies" the group headers disappear.
If you set up "Don't Link" they appear again, but the resulting app size is huge in comparison.

I am trying to figure out how use the linking without having the Group Headers gone.

**Comment by RyanKindley** [comment]
I don't take the merits, found the solution here: https://xamarin.github.io/bugzilla-archives/56/56250/bug.html

Steps:
1. Create a xml file in the root of the IOS or Android project, name can be any, but I called it "LinkDescription.xml".
2. Right click the file and in Build Action, select LinkDescription.
3. Write this in the file.

<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="System.Core">
    <type fullname="IGrouping*">
      <method name="get_Key" />
    </type>
  </assembly>
</linker>

**Comment by rmarinho** [comment]
Hi @LeonardoPatti can you please share a small reproduction of the issue? 

Thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jhonata0302** [comment]
[https://github.com/xamarin/Xamarin.Forms/issues/5377#issuecomment-1212220973](resolution)

**Comment by radoczsandor** [comment]
Hello!

I had the same issue with the group header on Android and tried @RyanKindley's solution, but nothing really happened.

So I created another Grouping that now has no problem to render the header, it's simple:

`public class MyGrouping<K, T> : ObservableCollection<T>
	{
		public K Key { get; private set; }

		public MyGrouping(K key, IEnumerable<T> items)
		{
			Key = key;
			foreach (var item in items)
				this.Items.Add(item);
		}
	}`
