### ISSUE TITLE
[Bug] Secondary ToolbarItem text color is white on Android

### ISSUE THREAD

**Issue by karlp11** [xamarin/Xamarin.Forms#10617]
### Description
When updagrading a Shell project to Xamarin.Forms v4.6.0.726, secondary ToolbarItem text color become white. 
As the background is also white, it is impossible to read the ToolbarItem text.

### Steps to Reproduce
1. Create a new Xamarin.Forms project with Shell Template (Xamarin.Forms v4.4.0.991265 is used by default).
2. In AboutPage, add a ToolbarItem like this:
```
	<ContentPage.ToolbarItems>
        	<ToolbarItem Text="Test" Order="Secondary" />
    	</ContentPage.ToolbarItems>
```
3. Deploy the app in Android and go check the created ToolbarItem : black text on white background.
4. Update Xamarin.Forms to v4.6.0.726.
5. Deploy the app in Android and go check the created ToolbarItem : white text on white background.

### Expected Behavior
Secondary ToolbarItem text is black on white background.

### Actual Behavior
Secondary ToolbarItem text is white on white background.

### Basic Information

- Version with issue: v4.6.0.726.
- Last known good version: v4.5.0.725
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by thisismyself** [comment]
@karlp11 Did you find any workaround for this issue?

**Comment by karlp11** [comment]
@thisismyself No work around: I'm waiting the fix.

**Comment by a4anu10** [comment]
Same here, Any workaround for this issue?

**Comment by RamiroGuasti** [comment]
I hope a solution soon. In my apps the 'toolbaritems' can't be seen.

![imagen](https://user-images.githubusercontent.com/52539675/83145792-bdb85180-a0cb-11ea-987c-c9f2f024ceb6.png)
![imagen](https://user-images.githubusercontent.com/52539675/83145866-d7f22f80-a0cb-11ea-8267-da9a04d22b7d.png)

**Comment by thisismyself** [comment]
Thanks for fixing! It works again.

**Comment by kefyru** [comment]
<img width="314" alt="Снимок экрана 2020-07-20 в 15 59 36" src="https://user-images.githubusercontent.com/29143718/87940311-14c21d80-caa2-11ea-9b70-7b67baef7c39.png">
<img width="347" alt="Снимок экрана 2020-07-20 в 15 59 44" src="https://user-images.githubusercontent.com/29143718/87940314-168be100-caa2-11ea-87e7-a19759bb576d.png">

On IOS BarTextColor applies to all ToolbarItems.
But on Android it applies only to BackButton, and all other ToolbarItems stays white.

**Comment by James3UK** [comment]
@kefyru i think you would be better to log a separate issue as this is closed and not the same. Reference back to this one if you think it is related.
