### ISSUE TITLE
[Bug]  When compiling a new version of the cloned repo the follow

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10621]
When Attempting to build the full source for the forked project i get the following errors. When Compiling XamrianForms.sln file

1
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\GitHub\XamrainForms\Xamarin.Forms.Material.Android\bin\Debug\monoandroid10.0\ref\Xamarin.Forms.Material.dll' could not be found	Xamarin.Forms.ControlGallery.Android	C:\GitHub\XamrainForms\Xamarin.Forms.ControlGallery.Android\CSC	1	Active

2Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2260	style attribute 'attr/colorAccent (aka Xamarin.Forms.Platform.Android:attr/colorAccent)' not found.	Xamarin.Forms.Platform.Android	C:\GitHub\XamrainForms\Xamarin.Forms.Platform.Android\Resources\values\styles.xml	4	
[BuildForGithub.zip](https://github.com/xamarin/Xamarin.Forms/files/4601503/BuildForGithub.zip)

3.Severity	Code	Description	Project	File	Line	Suppression State
Error	APT2260	resource style/Theme.AppCompat.DayNight.DarkActionBar (aka Xamarin.Forms.Platform.Android:style/Theme.AppCompat.DayNight.DarkActionBar) not found.	Xamarin.Forms.Platform.Android	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Aapt2.targets	160	

There are a few more like number 3. but I have not been able to find a way around these to fix the build.

**Comment by PureWeen** [comment]
@davidbuckleyni Can you try updating your fork? 

We made a few changes that should make all this work better for you now

I checked your fork and it's older than the changes we made

**Comment by davidbuckleyni** [comment]
> @davidbuckleyni Can you try updating your fork? 
> 
> 
> 
> We made a few changes that should make all this work better for you now
> 
> 
> 
> I checked your fork and it's older than the changes we made

Yes question how do I do that. And that is great thanks for that 
Much appreciated as want to work on the project more ur a great team

**Comment by PureWeen** [comment]
Try this @davidbuckleyni 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by davidbuckleyni** [comment]
Thank u will update u tommrow what is the review process whom should I tag in the pull request once I get it working :-)

Is their a process documentation for pull request submission and what labels to place on it.

**Comment by PureWeen** [comment]
Just create the pull request and we'll add the labels and assign someone to it :-)

**Comment by PureWeen** [comment]
@davidbuckleyni check the video here for an example of creating a UI test
https://www.youtube.com/watch?v=RXRh66yxCQY

Don't let the UI test bog you down though. If you have trouble creating a UI test but you have a fix just check in the fix and we can help with the UI test

**Comment by davidbuckleyni** [comment]
@PureWeen thanks I have a Mac so shouldn’t be an issue :-)     Gerald was saying I don’t have to worry about tizen and uwp that’s something u guys would take care of aye

Also how do I add xamrain as a reference when it’s in build state and not nuget state so I can test it in the application later that I ain’t broke anything ?

**Comment by PureWeen** [comment]
There's not a great way to do that on vsmac. You have to create nugets on windows currently

Once you create the PR we can trigger a build which will have nugets you can test

**Comment by davidbuckleyni** [comment]
> There's not a great way to do that on vsmac. You have to create nugets on windows currently
> 
> 
> 
> Once you create the PR we can trigger a build which will have nugets you can test

Ok I just like being able to test code before saying it’s ready and pushing it is their no way to test it locally.

**Comment by PureWeen** [comment]
Your best way to test locally is to use the Control Gallery

you can create your test condition in there to see if it works

**Comment by davidbuckleyni** [comment]
> Your best way to test locally is to use the Control Gallery
> 
> 
> 
> you can create your test condition in there to see if it works

Ok so just build the control gallarry project and the change should just show up what dll do I reference then ? In my forms project

**Comment by davidbuckleyni** [comment]
> Your best way to test locally is to use the Control Gallery
> 
> 
> 
> you can create your test condition in there to see if it works

@PureWeen ano with build u guys are super busy when it’s over could someone walk me thru it on a teams call or something

**Comment by davidbuckleyni** [comment]
@PureWeen that is a far better test the only project now complains is the IOS ui tests Control I presume I need to have a mac connected for that to build ? I have a mac mini.

But far far less errors than what i was getting before.


But its saying ios is not compatible with net47 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\GitHub\XamFormsBuild\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	


![image](https://user-images.githubusercontent.com/5619229/82152240-cef59880-9857-11ea-8ef2-91c348d96c37.png)

**Comment by davidbuckleyni** [comment]
@PureWeen Also do i create a new branch when I do my pull request it didnt explain that well in the video ?

**Comment by PureWeen** [comment]
@davidbuckleyni yea :-/ those errors are just there 😢   We have an open issue with Visual Studio to fix those. They don't actually stop you from compiling and running stuff.

>  Also do i create a new branch when I do my pull request it didnt explain that well in the video ?


It's usually easier to create a new branch just so your local master can stay consistent with our master

**Comment by davidbuckleyni** [comment]
Thanks but the way you said about tesitng in the control gallery project is that not that one ? @PureWeen

**Comment by davidbuckleyni** [comment]
@PureWeen  i noticed this has now been assgiend to someone else by the looks through another item ?.

https://github.com/xamarin/Xamarin.Forms/issues/9673

And my issue for the place holder appears to be off the open issues ?

**Comment by PureWeen** [comment]
No those are the unit test projects. The error is saying it can't add the CG project as a reference not that the CG project isn't compiling

It doesn't look like that issue is assigned to anyone else. I assigned it to myself for now so it doesn't get closed or overlapping work doesn't happen

**Comment by davidbuckleyni** [comment]
@PureWeen I submitted a pull request there so we just have to see if it gets approval. But as exp I no ur first pull request will always be changes thanks.

**Comment by davidbuckleyni** [comment]
@PureWeen thanks for working on those bugs it’s appreciated I no I reached out to David pm manager I guess he reached out to u so just want to say thanks been wanting to contribute for a while now I can :-).

**Comment by davidbuckleyni** [comment]
They where on that YouTube video so been with that team since 2019 lol
