### ISSUE TITLE
[Bug] AppShell app secondary toolbar items appear as a white rectangle when viewed on Android.

### ISSUE THREAD

**Issue by davefxy** [xamarin/Xamarin.Forms#10629]
[Bug] AppShell app secondary toolbar items appear as a white rectangle when viewed on Android.
### Description
Toolbar secondary items are not displayed when selecting the 3 dot indicator on the toolbar. Instead you see a blank white rectangle, no text, no icon. The non AppShell version of app works fine on an Android.
### Steps to Reproduce
1.  Create an Android AppShell App.
2. Add a toolbar with primary and secondary toolbar items.

### Expected Behavior
Select secondary toolbar item display and view secondary toolbar items
### Actual Behavior
Select secondary toolbar item display. You see a white rectangle.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 Community v 16.5.4 on Windows PC
- Platform Target Frameworks: 
- Android: v 7.0
- Android Support Library Version:  9 (pie)
- Nuget Packages: 4.6....
- Affected Devices:
Android SM-T810  (Android 7.0 - API 24)
### Screenshots
[ToolbarItemAppShellDemo.zip]

### Reproduction Link
(https://github.com/xamarin/Xamarin.Forms/files/4603474/ToolbarItemAppShellDemo.zip)
Created an AppShell mobile app. Cloned pages from ToolBarItemsDemo sample.

**Comment by PureWeen** [comment]
duplicate 
https://github.com/xamarin/Xamarin.Forms/issues/10617

fixed here
https://github.com/xamarin/Xamarin.Forms/pull/10619
