### ISSUE TITLE
[Bug] iOS App Store Rejecting Forms Apps due to ITMS-90809

### ISSUE THREAD

**Issue by BenBtg** [xamarin/Xamarin.Forms#10639]
### Steps to Reproduce

1. Create a new Forms Shell App
2. Register App ID 
3. Upload to store using Transporter

### Expected Behavior
App is accepted in to store and appears in list of available builds

### Actual Behavior
App is rejected with the following email message
"ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview). "

### Workaround
Workaround described in this closed issue https://github.com/xamarin/Xamarin.Forms/issues/7323
 (when the issue only caused a warning) is to add an experimental flag "--optimize=experimental-xforms-product-type" into additional mtouch arguments.

This should now be default behaviour as the issue now causes the app to be rejected and most developers would not know about this flag.

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-macios/pull/8425
