### ISSUE TITLE
Images not rendered in Release Mode on Android with Bundle into native code [Bug] 

### ISSUE THREAD

**Issue by AntvissMedia** [xamarin/Xamarin.Forms#10631]
### Description
After upgrading the project to Xamarin Forms 4.6, images are no longer rendered on Android in Release Mode. They render ok in Debug Mode.

In my original project I had a lot of moving parts so troubleshooting that would have been a bit of a nightmare. So after a few hours I decided to start a new blank project and take it a step at a time.

To my surprise, it happened with the default NuGet packages. So a regular new project from Visual Studio with the standard assets and files has this issue.

### Steps to Reproduce

1. Create a project (Master-Detail in my case as i know it comes with images by default)
2. Update the target framework to **Android 10.0 (Q)** and set **Bundle assemblies into native code** to _true_
3. Upgrade the default NuGet packages to their latest stable versions (Xamarin.Essentials v1.5.3.1 and Xamarin.Forms v4.6.9.726)
4. Build and run the app in an emulator or physical device in **Release - Any CPU** with the default settings
5. App builds, runs but if you go to the About page, the Xamarin image is not rendered.

### Expected Behavior
All images render as normal

### Actual Behavior
Images do not show. It's as if the image resource itself is missing

### Basic Information

- Version with issue:
- Last known good version: Xamarin Forms 4.4
- IDE: Microsoft Visual Studio Enterprise 2019
    - Version 16.5.4
    - VisualStudio.16.Release/16.5.4+30011.22
    - Microsoft .NET Framework
        - Version 4.8.03752

- Platform Target Frameworks: 
   - Android: 10.2.0.100 (d16-5/988c811)
- Android Support Library Version: Android X
- Nuget Packages: Xamarin.Essentials v1.5.3.1 and Xamarin.Forms v4.6.9.72
- Affected Devices: Doesn't seem to matter.

### Screenshots

![Capture](https://user-images.githubusercontent.com/48839721/81483624-832f6780-9237-11ea-99f5-ca14211c6f1b.PNG)

### Reproduction Link

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{50206F4D-659A-41EE-A3A5-828A2BD9597D}</ProjectGuid>
    <ProjectTypeGuids>{EFBA0AD7-5A72-4C68-AF49-83D382785DCF};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <TemplateGuid>{9AA2D3C6-3393-45F1-8E7C-5A9901728795}</TemplateGuid>
    <OutputType>Library</OutputType>
    <RootNamespace>App3.Droid</RootNamespace>
    <AssemblyName>App3.Android</AssemblyName>
    <Deterministic>True</Deterministic>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
    <AndroidUseLatestPlatformSdk>false</AndroidUseLatestPlatformSdk>
    <TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidUseAapt2>true</AndroidUseAapt2>
    <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
    <NuGetPackageImportStamp>
    </NuGetPackageImportStamp>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug</OutputPath>
    <DefineConstants>DEBUG;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidLinkMode>None</AndroidLinkMode>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
    <AndroidSupportedAbis>armeabi-v7a;x86;arm64-v8a</AndroidSupportedAbis>
    <BundleAssemblies>true</BundleAssemblies>
    <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Android" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Numerics.Vectors" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.6.0.726" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="MainActivity.cs" />
    <Compile Include="Resources\Resource.designer.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\AboutResources.txt" />
    <None Include="Assets\AboutAssets.txt" />
    <None Include="Properties\AndroidManifest.xml" />
  </ItemGroup>
  <ItemGroup>
    <AndroidResource Include="Resources\layout\Tabbar.xml" />
    <AndroidResource Include="Resources\layout\Toolbar.xml" />
    <AndroidResource Include="Resources\values\styles.xml" />
    <AndroidResource Include="Resources\values\colors.xml" />
    <AndroidResource Include="Resources\mipmap-anydpi-v26\icon.xml" />
    <AndroidResource Include="Resources\mipmap-anydpi-v26\icon_round.xml" />
    <AndroidResource Include="Resources\mipmap-hdpi\icon.png" />
    <AndroidResource Include="Resources\mipmap-hdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\icon.png" />
    <AndroidResource Include="Resources\mipmap-mdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\icon.png" />
    <AndroidResource Include="Resources\mipmap-xhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\icon.png" />
    <AndroidResource Include="Resources\mipmap-xxhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\icon.png" />
    <AndroidResource Include="Resources\mipmap-xxxhdpi\launcher_foreground.png" />
    <AndroidResource Include="Resources\drawable\xamarin_logo.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\App3\App3.csproj">
      <Project>{ECE97A0B-CB73-4CEB-9117-79BD73F61B0B}</Project>
      <Name>App3</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\Android\Xamarin.Android.CSharp.targets" />
</Project>
```

**Comment by ia5634** [comment]
Confirmed. Possible duplicate of: https://github.com/xamarin/Xamarin.Forms/issues/9900

The same problem is here. It occured when I updated Xamarin.Forms from nuget.

Current Xamarin.Forms version is v4.6.0.726. It's definetely related to new versions (I think it began with v4.5). There was no problem while using an old version (cant remember old version number :/)

What I tested;
When "target framework is 10" and "bundle assemblies... = true" => problem
When "target framework is 10" and "bundle assemblies... = false" => not problem

When "target framework is 9" and "bundle assembliies... = true" => not problem
When "target framework is 9" and "bundle assemblies... = false" => not problem

**Comment by AntvissMedia** [comment]
> Confirmed. Possible duplicate of: #9900
> 
> The same problem is here. It occured when I updated Xamarin.Forms from nuget.
> 
> Current Xamarin.Forms version is v4.6.0.726. It's definetely related to new versions (I think it began with v4.5). There was no problem while using an old version (cant remember old version number :/)
> 
> What I tested;
> When "target framework is 10" and "bundle assemblies... = true" => problem
> When "target framework is 10" and "bundle assemblies... = false" => not problem
> 
> When "target framework is 9" and "bundle assembliies... = true" => not problem
> When "target framework is 9" and "bundle assemblies... = false" => not problem

**Comment by AntvissMedia** [comment]
Definitely looks like it's duplicate of #9900 . Hopefully the info I added here will help resolve this quicker.
