### ISSUE TITLE
Implement Application.Quit() for iOS, Android and UWP

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#10636]
## Summary
Implement Application.Quit() for iOS, Android and UWP. Currently only macOS, GTK and WPF are supported.

## Platform code

For platform equivalents of `Xamarin.Forms.Application.Current.Quit()`,
iOS: `System.Threading.Thread.CurrentThread.Abort()`
Android: `Android.OS.Process.KillProcess(Android.OS.Process.MyPid())`
UWP: `Windows.UI.Xaml.Application.Current.Exit()`

## Intended Use Case
Terminating the application.

**Comment by AndreiMisiukevich** [comment]
@Happypig375 Hi, it doesn't make sense at least for iOS

https://developer.apple.com/library/archive/qa/qa1561/_index.html

You will get a rejection from AppStore if implement this feature and they find it during the review

**Comment by Happypig375** [comment]
In my app, there is a quit button on the home page that does exactly this but still got successfully reviewed.

**Comment by MitchBomcanhao** [comment]
> In my app, there is a quit button on the home page that does exactly this but still got successfully reviewed.

From experience, Apple has failed an app update for something that had been there for years - they just hadn't noticed it. Doesn't mean it is right.

Terminating apps is generally bad practice which is why they will fail it. 
What real world benefit do you get from it? there are tons of drawbacks.

**Comment by hammondreg** [comment]
@MitchBomcanhao  Yes - agreed - terminating apps from WITHIN themselves is self-defeating; when an app detects a catastrophic event such as network failure it should just 'tread water' until the catastrophe resolves itself.  However I believe @Happypig375 is requesting a feature which is available in WPF whereby an event is triggered when the app is terminated from WITHOUT.  I have a WPF which does exactly this and it uses this event to send a last-gasp "Goodbye" message to a passive recipient.  So... I can do this with a WPF app on Windows 10, but I can't do this with Xamarin Forms UWP also on Windows 10.  It would be extremely useful to have such a feature.

**Comment by a-einstein** [comment]
I just called this 'functionality' to enable the user a direct way of exiting the application on a fatal error message. It didn't work.

Apparently this is defined, but not implemented. That's just confusing, wasting programmers' time and silly. 

Either implement it or remove the definition.

**Comment by TylerDM** [comment]
We just ran into this one.  Seems like Xamarin Forms should throw something like PlatformNotSupportedException on platforms which don't support this.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
