### ISSUE TITLE
[Bug] Can't add new item from Xamarin Forms category in shared projects

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Xamarin.Forms#10633]
### Description
Selecting Add New Item in a Shared Project will no longer show Xamarin.Forms item templates.  The category is completely missing, even though they're available from Class Library projects (the new default for shared code with Xamarin.Forms project templates).

### Steps to Reproduce

1. Open a Xamarin.Forms project based on an older project template that used a Shared Project for shared code.  Alternatively, create a new project from a current Xamarin.Forms project template and add a Shared Project using Add->New Project...
2. Right-click anywhere in the shared project, select Add->New Item...
3. Check categories listed under Installed->Visual C# Items on left side.

### Expected Behavior
Should have Xamarin.Forms category listed, like it used to (and like it still does for Class Library projects).

### Actual Behavior
Xamarin.Forms category is missing, and there's no way to access Xamarin.Forms item templates.

### Basic Information

- Version with issue: Xamarin 16.5.000.533
- Last known good version: Unknown
- IDE: Visual Studio 2019 16.5.4
- Platform Target Frameworks:
  - iOS:  13.16.0.13
  - Android: 10.2.100 
- Extensions: Xamarin Templates 16.5.49

### Workaround

Tried copying templates to user item templates, but that had no effect other than to double the entries when the Xamarin.Forms category is shown.

**Comment by PureWeen** [comment]
Shared projects aren't really fully supported in Visual Studio anymore

If you'd like these features back I'd log an issue here
https://developercommunity.visualstudio.com/

**Comment by Magendanz** [comment]
So we're just supposed to go convert all our old projects based on the Xamarin.Forms templates to class libraries now in order to maintain them?  That's a royal PITA!

**Comment by Magendanz** [comment]
You seriously need to update your online documentation to show that Shared Projects are now deprecated like PCLs.

https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/
https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/code-sharing
https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/shared-projects
