### ISSUE TITLE
[Bug] Android 4.1 Exception (Target: Ouya) - Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;'

### ISSUE THREAD

**Issue by frogcrush** [xamarin/Xamarin.Forms#10634]
### Description
When trying to run a newly created blank application on an Ouya (Android 4.1 - API 16) an exception occurs before the UI can be loaded. 

`Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;'`

### Steps to Reproduce

1. Create new Xamarin.Forms Android application
2. Run application on Android 4.1 device
3. Experience crash

### Expected Behavior
Application will launch
### Actual Behavior
A white screen is shown and then the application throws an exception.
### Basic Information

- Version with issue: 4.6.726
- Last known good version: unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: min 4.0, 4.1 tested; target 9 and 10
- Affected Devices: Ouya

**Comment by rmarinho** [comment]
Hi @frogcrush , forms applications can be written for the following operating systems: iOS 9 or higher. Android 4.4 (API 19) or higher (more details). However, Android 5.0 (API 21) is recommended as the minimum API. 

thanks

**Comment by edujgomes5** [comment]
Tenho um problema semelhante a este. Criei um projeto do zero ele funciona, o projeto que já tenho publicado na playstore, quando tento debugar ele, ele quebra logo após a tela de splash. Tenho outros dois projetos aqui que tem o mesmo problema quando coloco a api minima para API 17.

**Comment by rmarinho** [comment]
@edujgomes5 Xamarin.Forms só suporta API19 para cima. 

Obrigado

**Comment by edujgomes5** [comment]
> @edujgomes5 Xamarin.Forms só suporta API19 para cima.
> 
> Obrigado

Discordo, porque se eu crio um projeto vazio e instalo os pacotes que tenho no outro ele executa normalmente no tablet que tenho na versão 4.2.2; Preciso entender o que esta acontecendo no outro projeto pra não ter que fazer ele todo do zero.
