### ISSUE TITLE
Request Help 

### ISSUE THREAD

**Issue by prom3theu5** [xamarin/Xamarin.Forms#10651]
Viewmodels in Shell applications seem to be singleton fore the lifetime of the shell that the pages are run in.

In the login flow (where you have  separate shell for login, and navigate to a new shell instance which contains your flyout menu etc), how do you handle logout - in regards to Messaging Center unsubscriptions in viewmodels?

I can currently logout, but when I log back in the viewmodels get recreated, which results in dual subbscriptions

**Comment by PureWeen** [comment]
You don't need to swap out the page. You should be able to do this all with one shell

Check the sample here for details
https://github.com/PureWeen/ShellTemplate
