### ISSUE TITLE
[Enhancement] Gestures should be able to propagate 

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#10667]
## Summary
Need to be able Tap (or any other gesture) two views on top of each other. The propagation must be configurable On/Off where On is the default value.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
