### ISSUE TITLE
[Bug] PopAsync throw ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#10666]
### Description
When I try to partially clear the navigation stack using the code below the method `await Navigation.PopAsync(false)` throw ArgumentOutOfRangeException.

The `lastPage` variable has type of Page and store the page to which you need to return.

The main idea of the method `GoBack()` similar to `Navigation.PopToRootAsync()`, but instead of root page you need to return to `lastPage`.

### Example 
        protected async Task GoBack()
        {
            int indexToRemove = Navigation.NavigationStack.IndexOf(lastPage) + 1;

            while (indexToRemove != Navigation.NavigationStack.Count - 1)
            {
                Page toRemove = Navigation.NavigationStack[indexToRemove];
                Navigation.RemovePage(toRemove);
            }
            await Navigation.PopAsync(false);
        }

**Comment by VladislavAntonyuk** [comment]
check your navigation stack before PopAsync:
```
if (Navigation.NavigationStack.Count>0)
    await Navigation.PopAsync(false);
```

**Comment by AlexAba** [comment]
I guess the problem is not in NavigationStack emptiness. 

 At the start `NavigationStack.Count` is equal to 3. `lastPage` has index 0 so `indexToRemove` has value 1. 

When `Page toRemove = Navigation.NavigationStack[indexToRemove]; Navigation.RemovePage(toRemove);` will evoked `NavigationStack.Count` will be equal to 2. 

So `indexToRemove != Navigation.NavigationStack.Count - 1` give us false, because `indexToRemove` has value 1 and `Navigation.NavigationStack.Count - 1` equal to 1 too.

As a result, when `await Navigation.PopAsync(false);` will be executing `NavigationStack` will has 2 items.

**Comment by PureWeen** [comment]
@AlexAba can you attach a repro?

**Comment by MarMarIV** [comment]
I have same problem with PopAsync and ArgumentOutOfRangeException

As MainPage, i have NavigationPage with root page (Page1):
 - PushAsync Page2
 - PushAsync Page3
 - PopAsync //Page3 pop successful
 - PopAsync //throws ArgumentOutOfRangeException

`Parameter name: index

06-09 05:46:03.195 E/mono-rt (24614): [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
06-09 05:46:03.195 E/mono-rt (24614): Parameter name: index
06-09 05:46:03.195 E/mono-rt (24614):   at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in /Users/builder/jenkins/workspace/archive-mono/2019-10/android/release/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:161 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.GetFragment (Xamarin.Forms.Page page, System.Boolean removed, System.Boolean popToRoot) [0x00003] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:911 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot) [0x0001a] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:814 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPopViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00017] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:629 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.PopViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:168 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPopped (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:610 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.NavigationPage.Xamarin.Forms.INavigationPageController.RemoveAsyncInner (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean fast) [0x0004c] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:342 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.NavigationPage.PopAsyncInner (System.Boolean animated, System.Boolean fast) [0x0004c] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:325 
06-09 05:46:03.195 E/mono-rt (24614):   at Xamarin.Forms.NavigationPage.PopAsync (System.Boolean animated) [0x00143] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:202 `


I will try to create sample project with problem
