### ISSUE TITLE
[Bug] Picker Title/Placeholder Font

### ISSUE THREAD

**Issue by Darlingtone** [xamarin/Xamarin.Forms#10670]
### Description
When I set the Visual of Picker to Material the Title/Placeholder Font is different from the Font when an item is picked, I believe the Font of the Placeholder/Title should be the same as the Font det for the picker control just like Entry

### Steps to Reproduce

1. Change the Visual of a picker control or the parent page to Material 
2. Change the FontFamily of the Picker Control in XAML
3. Run, not the font before selecting an item and the font after selecting an item

### Expected Behavior
The FontFamily of the Placeholder should be same as the FontFamily set for the control

### Actual Behavior
The placeholder font is different from the font set for the control

### Basic Information
Xamarin.Forms **v4.6.0.726**
Xamarin.Forms.Visual.Material **v4.6.0.726**

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
