### ISSUE TITLE
[Bug] ListView RefreshCommand does not fire if inside a TabbedPage

### ISSUE THREAD

**Issue by jjohnnyl** [xamarin/Xamarin.Forms#10683]
### Description
ListView RefreshCommand does not trigger when pulled it's inside a TabbedPage, but if the same ListView is not in tabbed page it does trigger.

### Steps to Reproduce

1. Wrap Content Page which contains the ListView in a Navigation Page and place inside TabbedPage
2. Bind Listview RefreshCommand to DelegateCommand in ViewModel
3. DelegateCommand does not trigger inside ViewModel
 

### Expected Behavior
It should trigger the DelegateCommand it is binded to when pulling on the ListView

### Actual Behavior
Does not trigger DelegateCommand

### Basic Information

- Version with issue: Xamarin Forms 4.6.0.726 and Prism 7.2.0.1422
- Last known good version: ?
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.1

**Comment by jjohnnyl** [comment]
Just adding some more information, the NavigationPage wrapping the ContentPage had large titles enabled:

 xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
            ios:NavigationPage.PrefersLargeTitles="true"

Removing this fixed the issue, so it seems to be related with the large titles.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
