### ISSUE TITLE
Expander control does not work with Hot Reload and disappears

### ISSUE THREAD

**Issue by tusharvaja** [xamarin/Xamarin.Forms#10685]
### Description
I am using expander control with experimental flag. Currently when i change expander control details in xaml file and save it with hot reload, my emulator does not any reflect UI changes. Also expander control disappears. 

### Steps to Reproduce
1. Add exander control
2. Runt he project -> Android Emulator -> Hot Reload ON
3. Change the xaml  of details in exapnder 
4. Save 
5. Expander control disappears from UI
6. Redeploying app, works with changes. 

### Expected Behavior
On Save, Hot Reload should update UI for expander control

### Actual Behavior
On Save, Hot Reload does not work for expander control, and control goes away. 

### Basic Information
Xamarin Forms Version - 4.6.0.726
Xamarin Essential Version - 1.5.3.2

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

> VS bug [#1124310](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1124310)

**Comment by PureWeen** [comment]
@tusharvaja  can you attach a repro so I can see what you're changing?

I tested this locally and the only thing I noticed is that if the control is expanded then when you change something it collapses but the control itself doesn't disappear


Are you making sure to set the "Expander_Experimental" flag?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
