### ISSUE TITLE
[Bug] Inconsistent behavior of WebView Navigated event

### ISSUE THREAD

**Issue by vividos** [xamarin/Xamarin.Forms#10688]
## Description

I see inconsistent behavior of sending or not sending the `Navigated` event of the `WebView` control. I tried several cases:

Case 1: UWP app with `HtmlWebViewSource`: `Navigated` is not sent
Case 2: UWP app with `UrlWebViewSource`: `Navigated` is sent
Case 3: Android app with `HtmlWebViewSource` and no or default `BaseUrl` set: `Navigated` is not sent
Case 4: Android app with `HtmlWebViewSource` and custom BaseUrl set: `Navigated` is sent(!)
Case 5: Android app with `UrlWebViewSource`: `Navigated` is sent

iOS platform wasn't tested.

I checked the official documentation on WebView and didn't find any mention of the `Navigated` event behaving that way:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows

### Steps to Reproduce

1. Create a new Xamarin.Forms "Mobile App" project using VS 2019 16.5.5, Android and UWP platforms
2. Update all NuGet packages, especially Forms, to 4.6.0.726
3. Add the following markup to the Forms project's MainPage.xaml:
```
        <!-- Place new controls here -->
        <WebView x:Name="myWebView"
                 WidthRequest="400" HeightRequest="400" />
````
4. Add the following code to the MainPage.xaml.cs:
```
        public MainPage()
        {
            this.InitializeComponent();
            this.myWebView.Navigated += this.MyWebView_Navigated;
            this.myWebView.Source = new HtmlWebViewSource
            {
                BaseUrl = "file:///android_asset/",
                Html = "<h1>Hello World!</h1>"
            };
            //this.myWebView.Source = new UrlWebViewSource { Url = "https://www.xamarin.com/" };
        }

        private void MyWebView_Navigated(object sender, WebNavigatedEventArgs e)
        {
            Debug.WriteLine("Navigated! " + e.NavigationEvent.ToString());
        }
```

Based on which case you're after, comment out BaseUrl (Case 1 and 3), or add a subfolder to the default path, e.g:
`BaseUrl = "file:///android_asset/subfolder/",` (for Case 4). Cases 2 and 5 are using `UrlWebViewSource` instead of `HtmlWebViewSource`.

These inconsistency makes it hard to develop platform independent features against `WebView` and one must often resort to use custom renderers when there is no real need to.

The inconsistencies come from these code places:

Android:
https://github.com/xamarin/Xamarin.Forms/blob/9b9db3383077f479243f84f09ffb3e9da22914f7/Xamarin.Forms.Platform.Android/Renderers/FormsWebViewClient.cs#L61

The default `FormsWebViewClient` filters out the default Android base path, but not custom base paths.

UWP:
https://github.com/xamarin/Xamarin.Forms/blob/9b9db3383077f479243f84f09ffb3e9da22914f7/Xamarin.Forms.Platform.UAP/WebViewRenderer.cs#L315

The `OnNavigationCompleted` handler gets a null Url when the web view is initialized from a `HtmlWebViewSource`.

### Expected Behavior

The behaviour of the `Navigated` event should be consistent. As I don't like to write custom renderers, I would be glad if the `Navigated` event is sent regardless of the type of the `Source`. I know that this is a breaking change (for existing projects that don't expect to get the `Navigated` event when they didn't get it before). 

### Actual Behavior

See the description of the Cases, above.

### Basic Information

- Version with issue: Forms 4.6.0.726
- Last known good version: none
- IDE: VS 2019 16.5.5
- Platform Target Frameworks: 
  - Android: 10.0
  - UWP:  16299
- Android Support Library Version: N/A
- Nuget Packages: 4.6.0.726
- Affected Devices: any

### Workaround

A workaround would be to write a custom renderer for `WebView` that send the `Navigated` event regardless of the case.

**Comment by PureWeen** [comment]
Duplicate 
https://github.com/xamarin/Xamarin.Forms/issues/10350#issuecomment-616629755

**Comment by JaixTim** [comment]
@PureWeen This is a different issue from #10350 - that one focuses on the iOS implementation where as this is dealing with the Android and UWP implementations.

@vividos Thanks for pointing out the need to set the BaseURL to something other than the default - that has been enough of a work around for our situation to get the Navigated event to fire on Android.
