### ISSUE TITLE
share Authentication access token for all web requests

### ISSUE THREAD

**Issue by ehsangfl** [xamarin/Xamarin.Forms#10687]
In authenication base application, every request to server need access token.

In other platforms ( silverlight, javascript .... ), the access token send throw each request automatically.

but In xamarin platform,this must be done manually. there is no problem with httpclient or webclient  requests, and I can add header to requests.

In some controls like image control, there is no way to send access token,
for example, in a store app with thousands of products, and each product have multiple image, we could load images from database with 
## XAML Example
`<image Source="Http//domainname/downloade.ashx?ID=productID"/>`

in this example, image control does not have way to send access token to server, and request rejected by server for authentication issue.

in this scenario, we must load image from server manually and load it to memorystream, then display memorystream. 
as a result,there is more code, slow app,no cache .....

Is it possible to add a way to pass access token automatically.

# Difficulty : [medium]

**Comment by tal-athena** [comment]
I have same problem,
Is this issue solving?
Can I get the resolved image control on next release?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
