### ISSUE TITLE
[Enhancement] Material motion for Xamarin

### ISSUE THREAD

**Issue by saiyamjain143** [xamarin/Xamarin.Forms#10695]
## Summary
Material motion is a set of transition patterns that help users understand and navigate an app.
These are some examples.

Container transform
Shared axis
Fade through
Fade

For more refer: https://pub.dev/packages/animations

Copied from Flutter and would love to see in Xamarin.

**Comment by MarvinFrankenfeld** [comment]
@jsuarezruiz , any news on this?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
