### ISSUE TITLE
[Bug] ViewExtensions.CancelAnimations is not cancelling animations

### ISSUE THREAD

**Issue by munkii** [xamarin/Xamarin.Forms#10706]
### Description
I have an animation that I am "starting" with `Animation.Commit` and then trying to stop with `ViewExtensions.CancelAnimations(view)`. This is not cancelling the animation

I am need to trigger the start and stop of the Animation off of a ViewModel property

### Steps to Reproduce

1. Create Animation
`var throbAnimation = new Animation(v => this.MyLabel.Scale = v, 1, 2);`
2. Connect Label to a TriggerAction
```
public class StartAnimationAction : TriggerAction<VisualElement>
{
    public Animation Animation { set; get; }

    protected override void Invoke(VisualElement view)
    {
        this.Animation.Commit(view, "ScaleIt", length: 30000, easing: Easing.Linear,
                finished: (v, c) => view.Scale = 1, repeat: () => false);
    }
}
```
3. As you can see from the `Invoke` method that Action will start the animation and it does. This is the Trigger markup
```
<Label x:Name="MyLabel" Text="{StaticResource ClinicalServicesIconText}">
 <Label.Triggers>
     <DataTrigger TargetType="Label" Binding="{Binding IsSyncing}" Value="True">
         <DataTrigger.EnterActions>
             <settings:StartAnimationAction x:Name="StartAnimation"/>
         </DataTrigger.EnterActions>
         <DataTrigger.ExitActions>
             <settings:StopAnimationAction/>
         </DataTrigger.ExitActions>
     </DataTrigger>
 </Label.Triggers>
 </Label>

```
4. In the StopAnimationAction I want to cancel the animation. The only way I can see that can be done is with ViewExtensions.CancelAnimations . Here is the code for StopAnimationAction

```
   public class StopAnimationAction : TriggerAction<VisualElement>
    {
        protected override void Invoke(VisualElement view)
        {
            ViewExtensions.CancelAnimations(view);
        }
    }

```
### Expected Behavior
The animation should stop
### Actual Behavior
The animation continues
### Basic Information

- Version with issue:
- Last known good version:Xamarin 16.5.000, Xamarin Forms 4.4
IDE:
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment]
@munkii I have created a sample:
[Issue10706.zip](https://github.com/xamarin/Xamarin.Forms/files/4735284/Issue10706.zip)

But cannot reproduce the issue:
![issue10706](https://user-images.githubusercontent.com/6755973/83863696-fd161c00-a723-11ea-9689-ffdcf792c4c0.gif)
Could you take a look to the attached sample or attach a sample where reproduce the issue?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
