### ISSUE TITLE
[Enhancement] When using a SwipeView within a ListView,  an option to allow a swiped item to auto close when another item is being swiped would be useful.

### ISSUE THREAD

**Issue by marioantoniou** [xamarin/Xamarin.Forms#10709]
## Summary
When using a SwipeView within a ListView,  an option to allow a swiped item to auto close when another item is being swiped would be useful. Therefore only 1 visible swipe menu per ListView.

## Intended Use Case
Only allow one row in a ListView to have an SwipeView menu open at any one time, so the behavior is similar to  "ViewCell.ContextActions"

**Comment by jsuarezruiz** [comment]
@marioantoniou Thanks for the enhancement. I have created a PR https://github.com/xamarin/Xamarin.Forms/pull/10756 adding a new property to the SwipeView to allow this behavior. If you can take a look at it, would be great to have your feedback and know if it covers what you would like to have.

**Comment by jcg122562** [comment]
Hi How can I get this AutoClose update?  My version of Xamarin is 4.7.0.1142.
Thank you.

**Comment by jfversluis** [comment]
We won't be adding this to Forms anymore unfortunately. I very much like it though! Hopefully we can get this to .NET MAUI soon
