### ISSUE TITLE
[Bug] [Android] Editor Focusing is not smooth, the keyboard disappears then appears

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#10703]
### Description
Android Editor focusing is not smooth, when we call Focus( ) the keyboard will blink, it will disappear and then appear again. All I want is to keep the keyboard open when I click a button to send message so I can keep typing. while it works, but the UI is jumping up and down because of that keyboard disappearing then appearing whenever I call Focus( ).

The main problem is that, an Edit shouldn't lose focus when we click a button. just like most chat apps do! I am surprised I am reporting this in 2020 to be honest!

### Steps to Reproduce
1. Run the solution attached, nothing special in there just 4 lines of Xaml.
2. Tap the button, it may not appear from the first time but few taps will let you see it
3. If you are using an emulator don't use the mouse to click the button, the mouse will not reproduce the bug

### Expected Behavior
Keyboard to keep open

### Actual Behavior
Keyboard will close then open

### Workaround
Here is the workaroud that will help you understand the issue [Original Post Here](https://forums.xamarin.com/discussion/56523/entry-cell-loses-focus-on-button-press-in-android-but-not-ios-work-around)

```csharp
public static class AndroidFlags
    {
        public static bool IgnoreFocusChanges { get; internal set; }
    }
```

In my XF page:
```csharp
 void Editor_Focused(object sender, FocusEventArgs e)
        {
            AndroidFlags.IgnoreFocusChanges = true;
        }

void Editor_Unfocused(object sender, FocusEventArgs e)
        {
            AndroidFlags.IgnoreFocusChanges = false;
        }
protected override void OnDisappearing()
        {
            AndroidFlags.IgnoreFocusChanges = false;
            base.OnDisappearing();
        }
```

In Android MainActivity
```csharp
 public override View CurrentFocus
        {
            get
            {
                if (AndroidFlags.IgnoreFocusChanges)
                {
                    return null;
                }

                return base.CurrentFocus;
            }
        }
```

[EditorFocusTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4633876/EditorFocusTest.zip)

**Comment by lazmeister** [comment]
We found the UI to jitter up and down when having editor in scrollview.

**Comment by lazmeister** [comment]
I forgot to note most of the issues are in Android 9 for us, have you tested different Android versions @MhAllan ?

**Comment by MhAllan** [comment]
@lazmeister 

1- The Editor is not inside ScrollView. I did all possible trick regarding UI
2- I Tested in Android 9 and on Samsung device and Pixel emulator

The problem is that whenever you tap something or click a button the Editor will dismiss the keyboard before calling "ClearFocus" of Android.Views.ViewGroup of Mono.

**Comment by divyesh008** [comment]
**Android CustomEditorRenderer**

```
protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
{
    base.OnElementChanged(e);
    if (Control != null)
    {
        Control.FocusChange += (sender, eh) =>
        {
            if (eh.HasFocus)
            {
                Device.BeginInvokeOnMainThread(() =>
                {
                    var imm = (InputMethodManager)Control.Context.GetSystemService(Context.InputMethodService);
                    imm.HideSoftInputFromWindow(Control.WindowToken, HideSoftInputFlags.None);
                });
            }
        };
    }
}
```

**Comment by sreerajPR** [comment]
@divyesh008 This code will just dismiss the keyboard whenever Entry gains focus from other Views. Doesn't help the scenario explained in Issue Description.

**Comment by divyesh008** [comment]
> @divyesh008 This code will just dismiss the keyboard whenever Entry gains focus from other Views. Doesn't help the scenario explained in Issue Description.

Can you try this:
` Xamarin.Forms.Application.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.AdjustPan)`

**Comment by jfversluis** [comment]
There was a PR for this, but it will require new APIs that we won't be adding to Forms anymore at this time. As a result I will close this for now. Have a look at .NET MAUI to see if this is still an issue and if it is, open an issue/feature request there. Thanks!
