### ISSUE TITLE
I want to underline one word from the label text. How to do this???? Please help

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10700]
### Description
Am new to xamarin platform I want to underline one word from the label text. How to do this???? Please help
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LoGA80** [comment]
Istead of Text property use the FormattedText property and Spans, like this:

```
<Label>
<Label.FormattedText>
<FormattedString>
<Span Text="Normal text with one " />
<Span Text="underlined" TextDecorations="Underline" />
<Span Text=" word." />
</Label.FormattedText>
</Label>
```

**Comment by jsuarezruiz** [comment]
@LoGA80 answer is correct. It is amazing to see the community helping each other. Thanks.
