### ISSUE TITLE
[Bug] The "Month segment" of DatePicker show too wide in languages other than English (only on UWP)

### ISSUE THREAD

**Issue by SunshineSpring666** [xamarin/Xamarin.Forms#10701]
### Description
The "Month segment" of DatePicker is expected to display words like "January", "February" and so on. These words need wide space in English but not in some other "character-based" language, e.g., Chinese, Japanese, etc.. In these languages, the DatePicker doesn't auto-adapt according the space needed. Instead, it shows jusd as wide as it is in English, leaving a large empty gap in-between.
The bug only exists on UWP platform. On Android and iOS, it's normal.

### Steps to Reproduce
1. Create a DatePicker in XAML.
2. Set the app's language to Chinese or Japanese.
3. Build and Run.

### Expected Behavior
The DatePicker's "Month segment" is expected to be shown as the space needed in different languages on UWP, just like the corresponding control on Android and iOS.

### Actual Behavior
Same width is shown, leaving a large empty space inside the control.

### Basic Information
- Version with issue:
All recent relases and latest pre-release of Xamarin.Forms.
- Last known good version: Not known.
- IDE: Visual Studio 2019 16.5.5
- Platform Target Frameworks: 
  - UWP: both release18362 and Insider-preview19616
- Nuget Packages: Xamarin.Forms 4.6.0
- Affected Devices: PC (UWP on Windows)

### Screenshots
![Annotation 2020-05-15 172620](https://user-images.githubusercontent.com/42401603/82034800-40570f00-96d1-11ea-920a-b23d524df589.png)

### Workaround
Not known.

**Comment by jsuarezruiz** [comment]
In this case use the UWP DatePicker and is the expected behavior in the control. I created an UWP sample using the DatePicker using Japanese:

<img width="758" alt="Captura de pantalla 2020-06-02 a las 10 50 22" src="https://user-images.githubusercontent.com/6755973/83500416-08b4d900-a4bf-11ea-9796-cb0ed7b76b13.png">

You can modify the DatePicker ControlTemplate in UWP to adjust the size, etc. https://docs.microsoft.com/en-us/dotnet/framework/wpf/controls/datepicker-styles-and-templates

**Comment by SunshineSpring666** [comment]
Thanks, I see. I assumed before that the "Month" part will show as the width needed on UWP, without needing to make further customization. Because many other chanracter-based languages (like Chinese and Japanese) don't have long month words like January, February, etc. 
Actually the Android and iOS native controls handles this issue properly.
Thank you for your kindly reply.
