### ISSUE TITLE
Update link in wiki

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#10702]
### Description
On wiki page https://github.com/xamarin/Xamarin.Forms/wiki/How-to-Build-Xamarin.Forms-NuGet the link https://blog.xamarin.com/debugging-xamarin-forms/ is invalid. The correct link is: https://devblogs.microsoft.com/xamarin/debugging-xamarin-forms/

**Comment by jsuarezruiz** [comment]
@AlleSchonWeg Thanks so much for indicating it. I updated the link.
