### ISSUE TITLE
[Bug] Rotating Android device/emulator throws ArgumentNullException

### ISSUE THREAD

**Issue by sjordanGSS** [xamarin/Xamarin.Forms#10712]
### Description

Rotating an Android device running a Xamarin.Forms app causes it to crash with the following exception: 

````
**System.ArgumentNullException:** 'Value cannot be null.
Parameter name: enumerable'

05-15 16:47:48.002 D/Mono    ( 6784): DllImport attempting to load: '/system/lib/liblog.so'.
05-15 16:47:48.003 D/Mono    ( 6784): DllImport loaded library '/system/lib/liblog.so'.
05-15 16:47:48.003 D/Mono    ( 6784): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
05-15 16:47:48.003 D/Mono    ( 6784): Searching for '__android_log_print'.
05-15 16:47:48.003 D/Mono    ( 6784): Probing '__android_log_print'.
05-15 16:47:48.003 D/Mono    ( 6784): Found as '__android_log_print'.
05-15 16:47:48.011 I/MonoDroid( 6784): UNHANDLED EXCEPTION:
05-15 16:47:48.016 I/MonoDroid( 6784): System.ArgumentNullException: Value cannot be null.
05-15 16:47:48.016 I/MonoDroid( 6784): Parameter name: enumerable
05-15 16:47:48.016 I/MonoDroid( 6784):   at Xamarin.Forms.Internals.EnumerableExtensions.IndexOf[T] (System.Collections.Generic.IEnumerable1[T] enumerable, T item) [0x00003] in D:\a\1\s\Xamarin.Forms.Core\EnumerableExtensions.cs:79 
05-15 16:47:48.016 I/MonoDroid( 6784):   at Xamarin.Forms.Application.OnRequestedThemeChanged (Xamarin.Forms.AppThemeChangedEventArgs args) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:172 
05-15 16:47:48.016 I/MonoDroid( 6784):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnConfigurationChanged (Android.Content.Res.Configuration newConfig) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:90 
05-15 16:47:48.016 I/MonoDroid( 6784):   at Android.App.Activity.n_OnConfigurationChanged_Landroid_content_res_Configuration_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_newConfig) [0x00011] in <4ccdb3137d974856b786e1aeebbfbab6>:0 
05-15 16:47:48.016 I/MonoDroid( 6784):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.5(intptr,intptr,intptr)
````

This occurs with Xamarin.Forms 4.6 sr1, but does not occur with Xamarin.Forms 4.4. It has been observed on the default Xamarin.Forms application updated to 4.6 sr1 and on existing applications.

### Steps to Reproduce

1. Create a new blank Xamarin.Forms app
2. Update Xamarin.Forms to 4.6sr1
3. Rotate the device/emulator

### Expected Behavior
app rotates successfully

### Actual Behavior
app crashes

### Basic Information

- Version with issue: 4.6 sr1
- Last known good version: 4.4, interim versions not tested
- IDE: Visual Studio 16.5.4
- Platform Target Frameworks: 
  - Android: 9.0 and 10.0
- Android Support Library Version: observed in applications using no support libraries (no support lib nuget packages installed) and AndroidX support libraries
- Nuget Packages: Xamarin.Forms 4.6.0sr1
Xamarin.Essentials 1.5.3.2
- Affected Devices: observed on devices running Android 5.1, Android 7.0 and Android 10.0

### Workaround

Courtesy of @PureWeen:
> 
>  so it looks like there's a bug if you don't set any experimental flags :-/
> 
> If you just set a flag to anything
> Forms.SetFlags("anything")
> 
> it should fix it for you

**Comment by PureWeen** [comment]
@sjordanGSS so it looks like there's a bug if you don't set any experimental flags :-/ 

If you just set a flag to anything
Forms.SetFlags("anything")

it should fix it for you

**Comment by TTalpey** [comment]
The initial 4.6.0.726 release does not exhibit this issue. The 4.6.0.772 update does.
