### ISSUE TITLE
redirect to new page on button click

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10717]
as am very new to this platform I was unable to find the right way to do this
Tried all the above code but didn't work

 void GetStartedButton_Clicked(object sender, System.EventArgs e)
        {
            Navigation.PushAsync(new PlacesPage());
        }

private async void GetStartedButton_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushAsync(new PlacesPage());
        

void GetStartedButton_Clicked(object sender, System.EventArgs e)
        {
            this.Navigation.PushAsync(new PlacesPage());
        }

**Comment by AlleSchonWeg** [comment]
@Shraddha996 
You Test with android?
Read this: https://stackoverflow.com/questions/50412286/pushasync-not-working-with-contentpage or use Navigation.PushModalAsync();

**Comment by VladislavAntonyuk** [comment]
make sure in App.xaml.cs you set mainpage as navigationPage:
MainPage = new NavigationPage(new MyMainContentPage());

**Comment by Shraddha996** [comment]
thanks, @VladislavAntonyuk  @AlleSchonWeg 
Works!!
