### ISSUE TITLE
[Enhancement] WebView2 for WPF

### ISSUE THREAD

**Issue by tofutim** [xamarin/Xamarin.Forms#10719]
## Summary
The old WebView for WPF looks terrible. Any chance we could update to the new WebView2? Or would there be issues because of Edge requirements? Here is rendering of ruby text in Safari, iOS, Android with Noto Sans Base64 encoded:

![image](https://user-images.githubusercontent.com/157766/82096227-65d61f80-96b5-11ea-8dc2-a19e86753187.png)

and from WPF WebView

![image](https://user-images.githubusercontent.com/157766/82096367-b2b9f600-96b5-11ea-8783-feff9783fa16.png)

well... default Edge has some challenges too, though I think the latest should solve...

## API Changes

Maybe a toggle to switch to WebView2 if user is on an Edge available computer.

## Intended Use Case

For rendering HTML5 in pretty ways.

**Comment by maxim-saplin** [comment]
Totally agree, IE based WebView is very unstable and feature poor

**Comment by maxim-saplin** [comment]
As a workaround one can replace the WebBrowser native control used as standard with WPF WebView (Microsoft.Toolkit.Wpf.UI.Controls.WebView) which is based on modern Edge engine which is way better than old Trident.

It is a pretty straightforward swap in the renderer source code here's the renderer I have come up with: https://github.com/maxim-saplin/xOPS-App/blob/master/Saplin.xOPS.WPF/WebViewRenderer2.cs

In my case it properly displays web site and evals a simple JS.

Known issues:
- WebView stay on top of other controls (same as old version)
- Positioning in single comlum in 2 column Grid leads to artifacts (web view shifted horizontally)
- Doesn't work witin .NET Core 3.1 SelfContained AND PublishTrimmed .exe file

**Comment by tofutim** [comment]
Any chance of making this happen? I see there is new news about WebView2 for WPF become GA in Q4.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by mkosieradzki** [comment]
WebView2 works like a charm in WPF. 

To get it working, you need to: 
- use package versions with `-preview` in name (at least today) (otherwise you will not see proper classes for WPF)
- have either canary version of Microsoft Edge installed or WebView2 runtime installed directly - you can download it here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/ .

BTW. Also looking forward to have WebView2 in WPF version of Xamarin.Forms / MAUI.

**Comment by tofutim** [comment]
Any anyone successfully implement WebView2 into Xamarin Forms? Is WPF still alive?

**Comment by Ruddy2007** [comment]
Very confused about if this is available and supported in Xamarin. Updates?

**Comment by Ruddy2007** [comment]
Any word?

**Comment by furkick** [comment]
Can we please get an update on this matter?

**Comment by RickyYChan** [comment]
> Can we please get an update on this matter?

Maybe this will help!  \:D 
https://stackoverflow.com/questions/65208454/xamarin-wpf-net-5-displaying-webview2

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
