### ISSUE TITLE
[Bug] RadioButton does not change color of button (only text)

### ISSUE THREAD

**Issue by acuntex** [xamarin/Xamarin.Forms#10711]
### Description
On iOS:
When binding the property TextColor of RadioButton, the button and the text get the color of the bound property.
After changing the property only the color of the text changes, the button does not change color.
On Android:
TextColor has no effect on the button, only the text.

### Steps to Reproduce

1. Create a RadioButton in your xaml:
```
<RadioButton GroupName="SomeGroup" TextColor="{Binding TestColor}" Text="Test"></RadioButton>
```
2. In your ViewModel define the property (using MVVMCross in this case, but could be any MVVM Framework):
```
        private Color _testColor = Color.Red;
        public Color TestColor
        {
            get => _testColor;
            set
            {
                if (_testColor == value)
                    return;
                _testColor = value;
                RaisePropertyChanged(() => TestColor);
            }
        }

```
3. Change TestColor, e.g. with a Timer:
```
            Device.StartTimer(new TimeSpan(0, 0, 2), () =>
            {
                Device.BeginInvokeOnMainThread(() =>
                {
                    if (TestColor == Color.Red)
                        TestColor = Color.Aqua;
                    else
                        TestColor = Color.Red;
                });
                return true;
            });
```

### Expected Behavior
On iOS:
Since the button gets colorized initially, the color should be changed when changing the Property TextColor.
On Android:
Same behavior as on iOS

An alternative would be a separate property for the button color.

### Actual Behavior
Only the color of the text changes, the button does not change color

### Basic Information

- Version with issue: 4.6.0.772
- Last known good version: -
- IDE: Rider
- Platform Target Frameworks: 
  - iOS:  13
  - Android: 10
- Nuget Packages:
  - Xamarin.Forms
- Affected Devices:
  - iPhone
  - Android

**Comment by PureWeen** [comment]
What do you think of this solution @acuntex ?

https://github.com/xamarin/Xamarin.Forms/pull/10411

**Comment by acuntex** [comment]
Perfect, thanks!
