### ISSUE TITLE
[Enhancement] Allow CollectionView.ScrollTo to scroll to a group heading

### ISSUE THREAD

**Issue by Red-House-Media** [xamarin/Xamarin.Forms#10721]
Please enhance the ScrollTo method on the CollectionView to scroll to a Group Header when IsGrouped is true.  Thus allowing the collection to scroll and show the group heading. 

As it currently works, when ScrollToPosition.Start is set as the position, the group heading is off screen, giving the user a level of uncertainty as to the group they have scrolled to.

**Comment by syncro-bpierpont** [comment]
This appears to work if the Group is given as the item to scroll to.
I'm not sure if this is intended behavior however.

`var newGroup = new SomeItemGroup(name);`
`ItemGroups.Add(newGroup);`
`collectionView.ScrollTo(newGroup);`

**Comment by Red-House-Media** [comment]
No, it does not appear to work.
If I use the following
_col.ScrollTo(group, position: ScrollToPosition.Start, animate: true); with group as the item
I get
{Java.Lang.IllegalArgumentException: Invalid target position  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <26521a5118b44c858c385715922b9d5d>:0   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <26521a5118b44c858c385715922b9d5d>:0   at Android.Support.V7.Widget.RecyclerView+LayoutManager.StartSmoothScroll (Android.Support.V7.Widget.RecyclerView+SmoothScroller smoothScroller) [0x00031] in <844c913cb32f4510879031be59eb1dce>:0   at Xamarin.Forms.Platform.Android.ScrollHelper.AnimateScrollToPosition (System.Int32 index, Xamarin.Forms.ScrollToPosition scrollToPosition) [0x00029] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ScrollHelper.cs:67   at Xamarin.Forms.Platform.Android.ItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].ScrollTo (Xamarin.Forms.ScrollToRequestEventArgs args) [0x00010] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewRenderer.cs:595   at Xamarin.Forms.Platform.Android.ItemsViewRenderer`3[TItemsView,TAdapter,TItemsViewSource].ScrollToRequested (System.Object sender, Xamarin.Forms.ScrollToRequestEventArgs args) [0x00022] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewRenderer.cs:586   at Xamarin.Forms.ItemsView.OnScrollToRequested (Xamarin.Forms.ScrollToRequestEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Items\ItemsView.cs:210   at Xamarin.Forms.ItemsView.ScrollTo (System.Object item, System.Object group, Xamarin.Forms.ScrollToPosition position, System.Boolean animate) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Items\ItemsView.cs:169   at xxx-xxx my-code  --- End of managed Java.Lang.IllegalArgumentException stack trace ---java.lang.IllegalArgumentException: Invalid target position	at android.support.v7.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:11534)	at android.support.v7.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:8204)	at mono.java.lang.RunnableImplementor.n_run(Native Method)	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)	at android.os.Handler.handleCallback(Handler.java:873)	at android.os.Handler.dispatchMessage(Handler.java:99)	at android.os.Looper.loop(Looper.java:193)	at android.app.ActivityThread.main(ActivityThread.java:6669)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)}

**Comment by demoh2019** [comment]
Any Update?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
