### ISSUE TITLE
[Bug] BackButtonBehavior Command does not execute

### ISSUE THREAD

**Issue by sachinkanadia** [xamarin/Xamarin.Forms#10723]
### Description

On **iOS** when setting the BackButtonBehavior as follows:

```
<Shell.BackButtonBehavior>
        <BackButtonBehavior Command="{Binding BackCommand}"/>
    </Shell.BackButtonBehavior>
```

The command does not execute. The thing is when I set the TextOverride property it does work, but then I loose the default icon. This seems to be a bug. We need the command to execute in any case.

I am using Xamarin Forms Version: 4.6.0.772

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/8546
