### ISSUE TITLE
[Enhancement] Provide an easy way to get the Current Page at Shell

### ISSUE THREAD

**Issue by pictos** [xamarin/Xamarin.Forms#10729]
## Summary

As a developer, I want to get the Current Page presented at the Shell.

## API Changes
Today to have access to Current Page, we need to do a boring code, like this:
```csharp
void OnShellNavigated(object sender, ShellNavigatedEventArgs e)
{
     var page = Shell.CurrentItem.CurrentItem as ShellSection;
     CurrentPage = ((IShellSectionController)page).PresentedPage;
}
```
For this, we just need to expose a Property. Something like:
```csharp
// Shell Side

public Page CurrentPage {get;}  // Read-only property


// using scenario
void OnShellNavigated(object sender, ShellNavigatedEventArgs e)
{
     CurrentPage = Shell.Current.CurrentPage;
}
```

## Intended Use Case
Whit this addition we can easily get the presented page and do some operations on it, for example when we have our NavigationServices implementations, like [this](https://github.com/pictos/ShellPresentation/blob/master/ShellPresentation/ShellPresentation/Services/NavigationService.cs)

**Comment by pictos** [comment]
@PureWeen, can I work on this one? I think that will be pretty simple

**Comment by PureWeen** [comment]
@pictos Yea!!

I think this should be solved by having shell implement `IPageContainer<Page>`

And then exposing that property but not sure of the other nuances with this one :-) 

Need to make sure it works with Modal, etc...

**Comment by pictos** [comment]
@PureWeen , I was thinking to add a Property Page inside the `Shell.cs`. But if you don't like this approach I'll take a look into the `IPageContainer`

**Comment by pictos** [comment]
@PureWeen I did a quick try, keeping the implementation simple as possible, and those bits inside the `Shell.cs` worked*:

`public Page CurrentPage => (CurrentSection as IShellSectionController).PresentedPage;`

Do you think that we can maintain this way or I need to do some verification before return the CurrentPage?

* When the application launch and pass by `OnNavigated` the PresentedPage is null, I'll look at how I can fix that.

**Comment by pictos** [comment]
I'll close this issue since the PR was merged.
