### ISSUE TITLE
unable to solve  this error

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10727]
I installed xamarin.forms.map and xamarin.forms in my project but getting this error

Error---The projects SerenaSpaces.Android is missing Android SDKs required for building. Double-click on this message and follow the prompts to install them.	

and if I double click then one window opens for license agreement and ask to click install but still not get install in my machine

stuck at this point from pas 4 days please help!!!!!

**Comment by VladislavAntonyuk** [comment]
You have to install android sdk or allow VS automatically install it for you

**Comment by PureWeen** [comment]
@Shraddha996 can you use the Visual Studio feedback tool to log your issue? This will gather up the logs needed to address the issue.

In the meantime I'd recommend going via the Visual Studio Installer and adding Xamarin that way.

If you already have xamarin installed you can go to the individual components on the installer to install the android sdks
