### ISSUE TITLE
[Bug] Xamarin.Forms Preview 4.7.0.773 - Pre-1 Fails to Fully Display ContentPages

### ISSUE THREAD

**Issue by alaskanrogue** [xamarin/Xamarin.Forms#10731]
Xamarin.Forms Preview 4.7.0.773 - Pre-1 fails to fully display previously stable ContentPages.

I have created a sizable master layout controller in code that manipulates the XAML of numerous ContentPages. The controller does four different things for all pages other than the main screen:

1. Determines the sizing of the page grids (columns and rows), child UI elements and fonts to be used based on the device and applies the values so there is a common look and feel
2. Creates a master page header
3. Translates the page text to the language of the user
4. Determines the word wrapping based on the language and font to be shown

Until recently everything was working fine. However, I just upgrade two days ago to the preview. Pages are missing UI elements. I have written code to test the scenario where the page is displayed, but the properties of of an element is changed after the page is displayed. I have gone as far as setting the LayoutRoot in the XAML to not visible and resetting it to visible after a ForceLayout with about the same results.

Remembering that I had just upgraded the NuGet, I reversed to the previous version used and the problem disappeared.

**Comment by PureWeen** [comment]
@alaskanrogue can you attach a repro?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
