### ISSUE TITLE
[Bug][Android] CollectionView doesn't scroll to last item when put together with Editor that AutoSizes

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#10732]
### Description
If we have **CollectionView with ItemsUpdatingScrollMode="KeepLastItemInView"** and **Editor with AutoSize="TextChanges"**. 

When you type the editor will grow and cover the last item in the CollectionView, the CollectionView size will change, and CollectionView.Scrolled event will be fired, and ItemsViewScrolledEventArgs.LastVisibleItemIndex shows that last item is not visible (as expected).

**But, in spite of that CollectionView does not scroll to last item**. 

This is same for WindowSoftInputModeAdjust.Resize or WindowSoftInputModeAdjust.Pan

### Steps to Reproduce
* Run the attached solution
* When the Editor is focused Last Item is not shown
* Press Enters to make the Editor grow, the last item of the CollectionView will be hidden by the editor even though Scrolled event and ItemsViewScrolledEventArgs.LastVisibleItemIndex tell that it is hidden and because the mode is ItemsViewScrolledEventArgs.LastVisibleItemIndex the CollectionView must scroll to the end again but it doesn't

### Expected Behavior
The CollectionView to scroll to end to keep showing last item even when Editor grows because it has ItemsUpdatingScrollMode="KeepLastItemInView"

### Actual Behavior
The CollectionView doesn't change its scrolling until new item is added

### Basic Information
*  Android 9 and 10, Pixel simulator and Samsung device
* XF Version: 4.6.0.800

### Workaround
Listen to CollectionView.Scrolled event and CollectionView.SizeChanged events and do fixes there.

```csharp
private void CollectionView_SizeChanged(object sender, EventArgs e)
        {
            var collectionView = (CollectionView)sender;
            if (collectionView.ItemsUpdatingScrollMode == ItemsUpdatingScrollMode.KeepLastItemInView)
            {
                collectionView.ScrollTo(Items.Last(), null, ScrollToPosition.MakeVisible, true);
            }
        }
```

[CollectionViewWithEditor.zip](https://github.com/xamarin/Xamarin.Forms/files/4699915/CollectionViewWithEditor.zip)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by MhAllan** [comment]
@samhouts Updated

**Comment by jsuarezruiz** [comment]
Thanks for the reproduction sample @MhAllan.

**Comment by MhAllan** [comment]
I am thinking if the property is called: ItemsUpdatingScrollMode so it is about scrolling when items update and has nothing to do with scrolling when the collection view size change. so I will close this issue.
