### ISSUE TITLE
[Bug] Xamarin.Forms CarouselView CurrentItem binding doesn't work in v4.6.0.772

### ISSUE THREAD

**Issue by alborozd** [xamarin/Xamarin.Forms#10745]
### Description

CarouselView doesn't change CurrentItem when I change it in viewmodel
Here is xaml:

`
<StackLayout>
    <CarouselView CurrentItem="{Binding Answer}" ItemsSource="{Binding Answers}">
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding Display}"/>
            </DataTemplate>
        </CarouselView.ItemTemplate>
    </CarouselView>
    <Button Text="Next" Command="{Binding OnNext}"/>
</StackLayout>
`

When user clicks the button I want to change CurrentItem of the carousel view

Here is view model:

`
public class MyViewModel : INotifyPropertyChanged {
    private List<Answer> _answers;
    private Answer _answer;
    private int _index = 0;

    public MyViewModel()
    {
        Answers = new List<Answer>()
        {
            new Answer("Ans1"),
            new Answer("Ans2"),
            new Answer("Ans3"),
        };
        Answer = Answers[_index];
        OnNext = new Command(() =>
        {
            _index++;
            Answer = Answers[_index];
        });
    }
    public List<Answer> Answers
    {
        get { return _answers; }
        set
        {
            if (_answers != value)
            {
                _answers = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Answers)));
            }
        }
    }
    public Answer Answer
    {
        get { return _answer; }
        set
        {
            if (_answer != value)
            {
                _answer = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Answer)));
            }
        }
    }
    public event PropertyChangedEventHandler PropertyChanged;
    public ICommand OnNext { get; set; } }`

"Answer" is simple class with one string property Display

This code completly works in xamarin.forms 4.4.0.991265, but when I updated XF to 4.6.0.772 it stoped change CurrentItem and carousel doesn't move when I press the button "Next".

The same picture with Position binding. It works in 4.4.0.991265, but not in 4.6.0.772 when I increment position in view model.

I tried it on android emulator: Android 9.0 - API 28

### Steps to Reproduce

1. Change CurrentItem inside view model in Xamarin.Forms 4.6.0.772

### Expected Behavior
Carousel view shows changed CurrentItem

### Actual Behavior
Changed CurrentItem doesn't not appear on carousel view

### Basic Information

- Version with issue: XF 4.6.0.772
- Last known good version: XF 4.4.0.991265
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: Android 9.0 - API 28

### Workaround
Use previous versions of XF

**Comment by VladislavAntonyuk** [comment]
I can add that it works after you swipe between items
