### ISSUE TITLE
[Bug] WebView.Eval crashes on Android

### ISSUE THREAD

**Issue by vividos** [xamarin/Xamarin.Forms#10744]
### Description

I upgraded Xamarin.Forms from 4.6.0.726 to 4.6.0.772, and my app starts to crash. I'm using `WebView.Eval()` to transfer lengthy JavaScript data calls to the WebView. This is the exception and stack trace from AppCenter:

`System.UriFormatException: Invalid URI: The Uri string is too long.`
```
Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind)
System.Uri..ctor (System.String uriString) [0x00014] in <40f246d3e6214581a540496b6a7456a6>:0
WebViewRenderer.SyncNativeCookies (System.String url)
WebViewRenderer.SendNavigatingCanceled (System.String url)
WebViewRenderer.LoadUrl (System.String url)
WebViewRenderer.OnEvalRequested (System.Object sender, Xamarin.Forms.Internals.EvalRequested eventArg)
WebView.Eval (System.String script)
...
```

### Steps to Reproduce

1.  Create a new Mobile App project with a `WebView`
2. Use `WebView.Eval()` to call JavaScript code, prefixed with `javascript:`
3. It may help to send a long JavaScript script, e.g. with a long data array

### Expected Behavior

Should not crash. I think the fix is to not use `new Uri()`here, but instead `Uri.TryParse()`:
https://github.com/xamarin/Xamarin.Forms/blob/9b9db3383077f479243f84f09ffb3e9da22914f7/Xamarin.Forms.Platform.Android/Renderers/WebViewRenderer.cs#L271
I think `SyncNativeCookies()` should just return when a non-parseable URL or one that starts with `javascript:` is encountered.

### Actual Behavior

See above.

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: 4.6.0.772
- IDE: VS 2019 version 16.5.5
- Platform Target Frameworks: 
  - Android 10
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices: Google Nexus 5X

### Workaround

Downgrade to Forms 4.6.0.726

**Comment by jsuarezruiz** [comment]
Could be related with (or be the same) https://github.com/xamarin/Xamarin.Forms/issues/10738?

**Comment by vividos** [comment]
It's not the same exception type and not the same stack trace, so I guess no.

**Comment by nyakaspeter** [comment]
I had a non related issue that forced me to update to 4.6.0.772, so this really hit me in the feels :'( I can confirm that the crash only happens on Android, iOS is fine.

**Comment by vividos** [comment]
`SyncNativeCookies()` can be found in Android, UWP and iOS renderer classes; maybe it's not called on iOS for some other reason.
