### ISSUE TITLE
[Bug] deserialize object issue

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10742]
the above code is for getting value from service

 var u = Task.Run(() => GetURI(new Uri("https://24y10a8b1i.execute-api.us-east-2.amazonaws.com/SSDemo/fn_SS_GetPlaces")));
            u.Wait();
            Console.WriteLine(u.Result);

            string str1 = u.Result.Replace("\"", "");

            **Places[] p1 = JsonConvert.DeserializeObject<Places[]>(u.Result);**
            foreach (Places p in p1)
            {
                string name = p.PlaceName;
                string add = p.Address;

            }
but can't go further from places line and show an error.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].Phone', line 1, position 9.

**Comment by VladislavAntonyuk** [comment]
It is not an issue of Xamarin. Most likely you have invalid Json:
https://www.freeformatter.com/json-validator.html

**Comment by PureWeen** [comment]
I agree with @VladislavAntonyuk 

If you still can't get this to work I would post on StackOverflow
