### ISSUE TITLE
[Bug] Xamarin.Forms 4.6.0.772 fails to find EventHandler with correct signature for Tapped event.

### ISSUE THREAD

**Issue by devthepenguin** [xamarin/Xamarin.Forms#10749]
### Description
Inside Grid Layout TapGestureRecognizer when attached to an image, by **declaring an event handler in .xaml and defining the corresponding code-behind in .xaml.cs fails to link the two correctly**; build errors are encountered and subsequent tap action cannot be performed even after switching to the handler declaration pragmatically.

### Steps to Reproduce

1. Ensure that EventHandler's name in MainPage.xaml.cs name matches the one defined for tap event in MainPage.xaml.

```
<Grid>
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer Tapped="Handle_Tapped" />
                </Grid.GestureRecognizers>

                <Image HorizontalOptions="Center"
                       VerticalOptions="Center"
                       Source="userdev.png" 
                       Aspect="AspectFill" />

                <Image x:Name="pickedImage" HorizontalOptions="Fill"
                       VerticalOptions="Fill" Aspect="AspectFill"/>
</Grid>
```

2. TapGestureRecognizer fails to wire up the corresponding event handler for a Tapped event that seems inherent for Xamarin.Forms versions above 3.1.0

```
async Task Handle_Tapped(object sender, EventArgs e)
        {
            _pickedImage = await CrossMedia.Current.PickPhotoAsync();
            pickedImage.Source = ImageSource.FromFile(_pickedImage.Path);
        }
```

### Expected Behavior
Select an image from the media on tap.
### Actual Behavior
Unable to find a correct handler for tap.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 16.6.0 Preview 6.0
- Platform Target Frameworks:
  - iOS:  13.18.1.31
  - Android: 10.3.0.80
  - UWP: 
- Android Support Library Version:
- Nuget Packages:

1. Xamarin.Forms (4.6.0.772)
2. Xamarin.Essentials (1.5.3.2)
3. Xam.Plugin.Media (5.0.1)

- Affected Devices:

### Screenshots
Build & Deployement logs have been added in the reproduction link.
![xamarin forms4 6_bug_cv2](https://user-images.githubusercontent.com/52373288/82198115-7c7cb080-9919-11ea-9817-840cad634230.png)
![xamarin forms3 1_nobug_cv](https://user-images.githubusercontent.com/52373288/82198144-843c5500-9919-11ea-82c1-5b25a80437f6.png)

### Reproduction Link
[CVSample2.zip](https://github.com/xamarin/Xamarin.Forms/files/4643400/CVSample2.zip)

### Workaround
**Rollback to Xamarin.Forms 3.1.0.697729** 
**No errors are encountered.**

**Comment by PureWeen** [comment]
@devthepenguin your event signature can't return type Task

Change it to this and you should be good
```C#
async void Handle_Tapped(object sender, EventArgs e)
        {
            _pickedImage = await CrossMedia.Current.PickPhotoAsync();
            pickedImage.Source = ImageSource.FromFile(_pickedImage.Path);
        }

```

**Comment by devthepenguin** [comment]
@PureWeen **the return type is alright and changing it to void doesn't work either.** Here is the screenshot for reference, I suggest you reopen this issue since it's concerned with Xamarin.Forms version 4.6.0772, rolling back to 3.1 works fine.
The reason return type is alright is because this sample is from a course by @jfversluis and I faced this issue only because of the latest version of forms.

![xamissue](https://user-images.githubusercontent.com/52373288/82286691-e5b50000-99bb-11ea-9077-64049d11dd5f.png)
