### ISSUE TITLE
[Enhancement] Built in Search Page for iOS and Android

### ISSUE THREAD

**Issue by james1301** [xamarin/Xamarin.Forms#10748]
## Summary
Built in Search Page for Android and iOS as they have these built in options. I couldn't see this enhancement anywhere. e.g. like the image attached.

![image](https://user-images.githubusercontent.com/17780517/82197597-1aa95000-98f3-11ea-9cc8-ac80735ea1ae.png)

## API Changes

A new page based on ContentPage called SearchPage, which would include all of the Search bar controls properties so could be hooked up in pure Xamarin Forms.

## Intended Use Case
This is standard for iOS and Android platforms now, having a search box not in the header just looks old. A common scenario for the majority of the developers.

**Comment by xamarindevelopervietnam** [comment]
vote

**Comment by PureWeen** [comment]
is this the behavior you'd expect?

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search

**Comment by james1301** [comment]
@PureWeen I have a tabbed application and only one of those tabs wants this search behaviour at present. This seems like it is only if you want the search to appear on all of those screens? Is that correct? Also as my application was prior to the Shell coming out, so I do not have this shell implementation.

It seems a little strange to add it at the shell level for my application as I have 3 tabs, but only one of these wants the search.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
