### ISSUE TITLE
[Bug] Android 10: Line break does not happen on dash/hyphen

### ISSUE THREAD

**Issue by gata-bah** [xamarin/Xamarin.Forms#10743]
### Description
When a Label is too narrow to display its text, which contains a dash, in one line it breaks into a second line. This is expected. On all platforms (iOS and Android <10) this line break happens after the dash in a word (ie Line-Break). On Android 10 the line break happens exactly at the point where the line ends which leads to hard readability and bad UX.

### Steps to Reproduce

1.  Have a Label where a word with a dash breaks into a second line.
2. Line break goes wrong

(See attached sample project)

### Expected Behavior
Line break should happen after dash for better readability.

### Actual Behavior
Line break happens in the middle of a word.

### Basic Information

- Version with issue: 4.6.0.772
- Last known good version: none
- IDE: Visual Studio 2019 16.5.4
- Platform Target Frameworks: 
  - Android: Version 10 
- Affected Devices: Pixel 2 XL, Oneplus 7 Pro, Oneplus 6T

### Screenshots
![image](https://user-images.githubusercontent.com/34481665/82179502-c2685300-98de-11ea-9792-4759ce1fa1f4.png)

### Reproduction Link
[LineBreakingBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4642293/LineBreakingBug.zip)

**Comment by samhouts** [comment]
We probably need to start using [BreakStrategy](https://developer.android.com/reference/android/widget/TextView.html#setBreakStrategy(int)) on API23+.

**Comment by almirvuk** [comment]
@samhouts can you assign this one to me, please :)

**Comment by almirvuk** [comment]
@samhouts, I am exploring all the solutions here and I have a small question... is it ok to solve this by introducing a PlatformConfiguration.AndroidSpecific property for BreakStrategy on Label control for XF? :)

**Comment by almirvuk** [comment]
This should be partly done by [11345](https://github.com/xamarin/Xamarin.Forms/pull/11345)
