### ISSUE TITLE
[Bug] Cannot Set SearchBar.BarTintColor

### ISSUE THREAD

**Issue by james1301** [xamarin/Xamarin.Forms#10757]
### Description

Search is washed out because of the bold header colour. Need to change it's background, but cannot. SearchController.SearchBar.BackgroundColor is not the specific search and BarTintColor does not do anything. 

### Steps to Reproduce

1. Run the sample
2. See that the background is washed out by the bold header colour
3. Attempts to set Search colour do not work

### Expected Behavior

Background of search is changed.

### Actual Behavior

Nothing, cannot change colour. BarTintColor should change it?

### Basic Information

- Version with issue: 4.6
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  13.4
- Nuget Packages: N/A
- Affected Devices: N/A

### Screenshots

![image](https://user-images.githubusercontent.com/17780517/82230384-91f6d800-9923-11ea-9ff1-5516e197ae81.png)

### Reproduction Link

[SearchApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4645074/SearchApp.zip)

### Workaround

Haven't got one.

**Comment by PureWeen** [comment]
@james1301 I'd recommend posting this question to StackoverFlow

UISearchController is a native iOS components that's not something that Xamarin.Forms is influencing. 


So I would just look into how you customize a UISearchController.SearchBar
