### ISSUE TITLE
[Bug] OnDisappearing not called when swipe in TabbedPage

### ISSUE THREAD

**Issue by Nii-co** [xamarin/Xamarin.Forms#10769]
### Description
In Android, an app with TabbedPage, when on page A, swipe to Page B, OnDisappearing() of page A not called, causing OnAppearing() of Page A not called when click system back button and return to Page A. Please see steps to Reproduce in detail. 

### Steps to Reproduce

1. Start Demo project
2. Switching between Browse page and About page by clicking tab, each swich has previous page's OnDisappearing() called and current page's OnAppearing() called.
3. Click Browse page tab, this time swipe to About page, only About page's OnAppearing() was called, Browse page's OnDisappearing() not called.
4. Click system back button, neither About page's OnDisappearing() nor Browse page's OnAppearing() called.

### Expected Behavior
OnDisappearing() of Browse page should be called when swipe from Browse to About, followed with About page's OnAppearing(). Also, when click system back button, OnDisappearing() of About page called followed with Browse page's OnAppearing().
### Actual Behavior
Only OnAppearing() of About page was called when swipe.
### Basic Information

- Version with issue: Xamarin.Forms 4.6.0.800
- Last known good version:
- IDE: VS2019 16.5.5
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: /
- Nuget Packages: /
- Affected Devices:

### Reproduction Link
Minimal project: [TabbedPageSwipe.zip](https://github.com/xamarin/Xamarin.Forms/files/4650624/TabbedPageSwipe.zip)

https://stackoverflow.com/questions/61669868/xamarin-forms-tabbedpage-currentpage-does-not-call-onappearing
### Workaround
Use OnCurrentPageChanged() for things to be done when swich tab pages

**Comment by samhouts** [comment]
The Android ViewPager, which is backing the TabbedPage, keeps a minimum number of pages loaded in memory to keep the UI fast and responsive. OnDisappearing does not get called until the pages are triggered to be removed from memory. It's an odd quirk, but this is expected behavior.
