### ISSUE TITLE
[Bug]  Extra height added to top navigation 

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10760]
I added a tabbed page  in my xamarin project but because of that my top navigation height got increased and I don't know from where I can change it
Also, I want to change the background color of that 
Please help!!!

![WhatsApp Image 2020-05-19 at 12 14 39 AM](https://user-images.githubusercontent.com/39983941/82248732-3e59ae00-9966-11ea-85ad-e38722425b87.jpeg)

**Comment by PureWeen** [comment]
@Shraddha996 can you attach a repro so we can see how you're defining your layout?

**Comment by Shraddha996** [comment]
@PureWeen  thanks for your quick response but ,
right know am manage to remove the extra space from page but am not able to change the background color of the bar please suggest something....

**Comment by samhouts** [comment]
@Shraddha996 You can use `NavigationPage.BarBackgroundColor` on your ContentPages to set the NavigationBar color.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
