### ISSUE TITLE
[Bug] Xamarin.Forms 4.6.0.772 fails to find EventHandler with correct signature for Tapped event.

### ISSUE THREAD

**Issue by devthepenguin** [xamarin/Xamarin.Forms#10764]
Refer #10749 problem persists after making the change asked.
### Description
Inside Grid Layout TapGestureRecognizer when attached to an image, by **declaring an event handler in .xaml and defining the corresponding code-behind in .xaml.cs fails to link the two correctly**; build errors are encountered and subsequent tap action cannot be performed even after switching to the handler declaration pragmatically.

### Steps to Reproduce

1. Ensure that EventHandler's name in MainPage.xaml.cs name matches the one defined for tap event in MainPage.xaml.
```
<Grid>
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer Tapped="Handle_Tapped" />
                </Grid.GestureRecognizers>

                <Image HorizontalOptions="Center"
                       VerticalOptions="Center"
                       Source="userdev.png" 
                       Aspect="AspectFill" />

                <Image x:Name="pickedImage" HorizontalOptions="Fill"
                       VerticalOptions="Fill" Aspect="AspectFill"/>
</Grid>
```
2. @PureWeen I tried changing the return type of handler from Task to void which doesn't work either.
```
async Task Handle_Tapped(object sender, EventArgs e)
        {
            _pickedImage = await CrossMedia.Current.PickPhotoAsync();
            pickedImage.Source = ImageSource.FromFile(_pickedImage.Path);
        }
```
```
async void Handle_Tapped(object sender, EventArgs e)
        {
            _pickedImage = await CrossMedia.Current.PickPhotoAsync();
            pickedImage.Source = ImageSource.FromFile(_pickedImage.Path);
        }
```
![xamissue](https://user-images.githubusercontent.com/52373288/82289497-8c9c9a80-99c2-11ea-94a0-f71ca3627b4a.png)

### Expected Behavior
Select an image from the media on tap.
### Actual Behavior
**Unable to find a correct handler for tap.
Error Persists.**
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 16.6.0 Preview 6.0
- Platform Target Frameworks: 
  - iOS:  13.18.1.31
  - Android: 10.3.0.80 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:

1. Xamarin.Forms (4.6.0.772)
2. Xamarin.Essentials (1.5.3.2)
3. Xam.Plugin.Media (5.0.1)

- Affected Devices:

### Screenshots
![xamarin forms4 6_bug_cv2](https://user-images.githubusercontent.com/52373288/82289469-7db5e800-99c2-11ea-8438-dfc41b9c8ea0.png)
![xamarin forms3 1_nobug_cv](https://user-images.githubusercontent.com/52373288/82289478-83133280-99c2-11ea-8eee-a9d41b8f6fd2.png)

### Reproduction Link
[CVSample2.zip](https://github.com/xamarin/Xamarin.Forms/files/4648454/CVSample2.zip)

### Workaround
**Rollback to Xamarin.Forms 3.1.0.697729
No errors are encountered.**

**Comment by PureWeen** [comment]
Both your events have the wrong return

I changed it to this and it compiles fine

```C#
using Plugin.Media;
using Plugin.Media.Abstractions;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace CVSample2
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        private readonly String azureFunctionURL = "YOUR_URL_HERE";
        private MediaFile _pickedImage;
        private readonly HttpClient _httpClient = new HttpClient();
        public MainPage()
        {
            InitializeComponent();
        }

        async void Handle_Clicked(object sender, System.EventArgs e)
        {
            if (_pickedImage != null)
            {
                var postResult = await _httpClient.PostAsync(azureFunctionURL,
                                      new StreamContent(_pickedImage.GetStreamWithImageRotatedForExternalStorage()));

                var stringResult = await postResult.Content.ReadAsStringAsync();

                if (postResult.IsSuccessStatusCode)
                {
                    await DisplayAlert("Here is what you see", stringResult, "OK");
                }
                else
                {
                    await DisplayAlert("Error", stringResult, "OK");
                }
            }
        }

        async void Handle_Tapped(object sender, EventArgs e)
        {
            _pickedImage = await CrossMedia.Current.PickPhotoAsync();
            pickedImage.Source = ImageSource.FromFile(_pickedImage.Path);
        }
    }
}

```

**Comment by devthepenguin** [comment]
https://www.linkedin.com/learning/building-serverless-xamarin-apps-with-azure/connect-with-the-azure-function
@PureWeen Thanks for the help, it works perfectly fine now! added a reference in the course section for this. Great help.

**Comment by jfversluis** [comment]
Glad it worked and thanks for watching the course @devthepenguin! :)
