### ISSUE TITLE
[Bug] CarouselView on Android does not always fire CurrentItemChanged or PositionChanged when scrolling

### ISSUE THREAD

**Issue by chrisstaley** [xamarin/Xamarin.Forms#10775]
### Description
`CarouselView` will not always fire the `CurrentItemChanged` or `PositionChanged` events when scrolling in certain situations on Android. iOS works as expected. See the attached repro project.

There appears to be a threshold point at which `PeekAreaInsets` can be set beyond which the aforementioned events will not fire. I'm assuming the threshold may have to do with some combination of the rendered item's width, the layout's `ItemSpacing`, and the width of the screen (in pixels). The attached repro project was tested on an emulator based off of the Pixel 3 XL's screen dimensions.

### Steps to Reproduce
1. Run the repro project.
2. Scroll the bottom `CarouselView` back and forth.
3. Note that neither `CurrentItemChanged` nor `PositionChanged` is ever called.

### Expected Behavior
`CurrentItemChanged` and `PositionChanged` should both be called any time the items scroll.

### Basic Information

- Version with issue: 4.6.0.800

### Reproduction Link
[CarouselViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4650985/CarouselViewIssue.zip)

**Comment by rmarinho** [comment]
Hey @chrisstaley can you try this nuget
[Xamarin.Forms.4.6.0.2756.zip](https://github.com/xamarin/Xamarin.Forms/files/4688119/Xamarin.Forms.4.6.0.2756.zip)

**Comment by chrisstaley** [comment]
@rmarinho That appears to have fixed the issue. Thanks!

**Comment by divyesh008** [comment]
I am still facing this same issue in Xamarin.Forms 5.0, means it's not fixed yet.
