### ISSUE TITLE
Custom control, properties, styles and constructors

### ISSUE THREAD

**Issue by OABsoftware** [xamarin/Xamarin.Forms#10779]
### Description
I wrote a custom control that inherits from Frame and has a label as one of its children.
And I added a FontAttributes property to this control, like this:

        public static readonly BindableProperty FontAttributesProperty = BindableProperty.Create(nameof(FontAttributes), typeof(FontAttributes), typeof(MyControl), null, propertyChanged: OnFontAttributesChanged);

        static void OnFontAttributesChanged(BindableObject bindable, object oldValue, object newValue)
        {
            MyControl control = (MyControl)bindable;
            if (control != null && control.mlblText != null)
            {
                control.mlblText.FontAttributes = (FontAttributes)newValue;
            }
        }

        [Xamarin.Forms.TypeConverter(typeof(Xamarin.Forms.FontAttributesConverter))]
        public FontAttributes FontAttributes
        {
            get => (FontAttributes)GetValue(FontAttributesProperty);
            set => SetValue(FontAttributesProperty, value);
        }

Then I defined a style in App.xaml, like this:

        <Style x:Key="MyControlStyle" TargetType="local:MyControl">
            <Setter Property="FontAttributes" Value="Italic" />
        </Style>

And I added the control to one of the pages in my app:

        <local:MyControl Text="Hi there" HeightRequest="44" Style="{StaticResource MyControlStyle}" />

So far, so good. Everything works as expected.
Then I decided that by default all instances of MyControl should show the text in a bold font.
So I changed the constructor to this:

        public MyControl() : base()
        {
            this.FontAttributes = FontAttributes.Bold; // this line was added!

            mlblText = new Label();
            mlblText.FontAttributes = this.FontAttributes;

            this.Content = mlblText;
        }
### Expected Behavior
Since the style is still in place, I'd expect the text to still be shown in italic.

### Actual Behavior
But by adding this line in the constructor, the style now is completely ignored and the text is shown in bold.

### Basic Information
- Version with issue: Xamarin Forms 4.6.0.800
- IDE: Visual Studio Mac 8.5.6
- Platform Target Frameworks:
  - iOS:  12.0
  - Android: 9.0

**Comment by jcmanke** [comment]
The values from the style are applied during the base class constructor. By explicitly setting the property in your constructor, you're overriding the style value. Instead, you should set the default value in `BindableProperty.Create()`

**Comment by OABsoftware** [comment]
Thanks for your response.
In the meantime I indeed changed my custom properties and now set the default value in the BindableProperty.Create().

But what to do with e.g. the Background property (which I don't add myself but is defined by the base class) which I would also like to give a default value (other than the default default one) at the moment of the construction of the control?

And why does a call to the SetValue method block the style from being applied to that property? I don't get that logic.

**Comment by jcmanke** [comment]
Setting the style just goes through and calls SetValue() for all of the properties listed in the Style's Setters. Calling SetValue() again later overrides that. If you set both the Style and FontAttributes in the XAML would you be surprised by the FontAttributes not matching the Style? The trick is just knowing that the style is applied first and then everything else overrides the values set by the style.

BackgroundColor is a bit trickier, but I would probably go for defining a wrapper property and binding the existing property to that.

```
    public static readonly BindableProperty CustomBackgroundProperty = BindableProperty.Create(nameof(CustomBackground), typeof(Color), typeof(MyControl), null, propertyChanged: OnCustomBackgroundChanged);

    static void OnCustomBackgroundChanged(BindableObject bindable, object oldValue, object newValue)
    {
        MyControl control = (MyControl)bindable;
        if (control != null)
        {
            control.BackgroundColor = (Color)newValue;
        }
    }
```

**Comment by OABsoftware** [comment]
But how can the style be applied before the constructor has even finished?

If I remove the added line in the constructor and set a breakpoint in the OnFontAttributesChanged handler, I can see that the style gets applied _after_ the constructor has completed.
What I don't get is why that flow is different when I call SetValue at the beginning of the constructor.
