### ISSUE TITLE
[Bug] xamarin with SQLite and JSON

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#10788]
Is it possible in xamarin to receive data from JSON and store it in the local SQLite database?
Please help!

**Comment by gmwilhelm** [comment]
Yes, it is.

But this is a question that is better handled in the forums at https://forums.xamarin.com/ and not here.

**Comment by devthepenguin** [comment]
Follow this tutorial-
https://docs.microsoft.com/en-us/learn/modules/store-local-data-with-sqlite/

**Comment by samhouts** [comment]
@Shraddha996 Looks like you got a few answers! I'll go ahead and close this now. Thanks!
