### ISSUE TITLE
Please add OpenGLView "Snapshot" method

### ISSUE THREAD

**Issue by pfafft33** [xamarin/Xamarin.Forms#10787]
## Summary
I would like the OpenGLView object to have a method added that captures an image of what is displayed inside of it at that moment in time, and saves it to an appropriate file format (e.g. jpg).

## API Changes
Something like this would be nice:
OpenGLView myOGLV;
myOGLV.Snapshot("path_and_file_name_string");

public void Snapshot(string pathAndFileName)
{
     . . . code to produce the snapshot jpg file
}

## Intended Use Case
I know that the user on an Android phone can do the 3-fingered salute to capture a screen image. However, that method captures the ENTIRE screen. I want to capture JUST what is inside the OpenGLView container. I have an App that plots graphs of very visually stunning equations. I would like my users to be able to save a snapshot of their creation for use as screen backgrounds, or even to print out and hang on the wall as art.

**Comment by MhAllan** [comment]
Should be: public Stream TakeSnapshot( )

**Comment by pfafft33** [comment]
Thank you Mohamad!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
