### ISSUE TITLE
[Bug][EntryRenderer] VerticalTextAlignment.Center of Entry on macOS is not working as expected

### ISSUE THREAD

**Issue by nor0x** [xamarin/Xamarin.Forms#10789]
### Description
Setting the `VerticalTextAlignment` property of an `Entry` has no effect on `macOS` - so vertically centering the text and placeholder of an Entry is not possible. 
### Steps to Reproduce
check out the repro
[https://github.com/nor0x/repro-XF-10789](https://github.com/nor0x/repro-XF-10789)

OR 

1. Create Xamarin.Forms MacOS Project
2. Add Entry
3. Set HeightRequest of Entry (even with default height the text is positioned at the top of the entry)
4. Type Text

### Expected Behavior
Text in an `Entry` should align with the according value of `VerticalTextAlignment`
### Actual Behavior
Text is always position on the top of the `Entry`
### Basic Information

- Version with issue: 4.6.0.800
- IDE:
- Platform Target Frameworks: 
  - macOS:  10.15.4

### Screenshots

##macOS - broken
![image](https://user-images.githubusercontent.com/3210391/82437271-6563cd00-9a97-11ea-97cc-68e24e8b7946.png)

##iOS - working fine
![Simulator Screen Shot - iPhone 11 - 2020-05-20 at 12 40 43](https://user-images.githubusercontent.com/3210391/82437105-2766a900-9a97-11ea-99fc-e09aa7bc0b97.png)

### Reproduction Link

[https://github.com/nor0x/repro-XF-10789](https://github.com/nor0x/repro-XF-10789)

**Comment by jsuarezruiz** [comment]
I have reviewed the code and `VerticalTextAlignment` is not implemented in macOS Entry.

It would be necessary to obtain the `NSRect` (size) of the text and based on that and the size of the entire control, change the position of the text.

**Comment by CMarcher** [comment]
I'm still getting this issue on the latest release - any ETA?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
