### ISSUE TITLE
[Question] How long will Xamarin.Forms be supported after .NET Multi-platform App UI GA

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#10784]
I have a question. Yesterday Microsoft announced [.NET Multi-platform App UI ](https://github.com/dotnet/maui) which is based on Xamarin.Forms. How long will Xamarin.Forms be supported after GA of the new UI lib?

**Comment by jsuarezruiz** [comment]
Hi @MagicAndre1981. The next major version of Xamarin.Forms will around September 2020 and continue to be updated through the release of MAUI with .NET 6 (November 2021). After that, Xamarin.Forms will continue to receive priority servicing for 12 months.

**Comment by MagicAndre1981** [comment]
> After that, Xamarin.Forms will continue to receive priority servicing for 12 months.

what does this mean? Only bugfixes (to allow easier migration to MAUI)?

**Comment by jsuarezruiz** [comment]
Yes, will continue with fixes, answering questions etc.

**Comment by jsuarezruiz** [comment]
Hey @MagicAndre1981  I hope I have answered your question. I'm going to close this issue. However, if you have other questions etc you can open another issue :)

**Comment by MagicAndre1981** [comment]
it is ok, I'll see what happens next year.
