### ISSUE TITLE
[Bug][iOS] No response to system mode changes when resources are in app resource dictionary

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#10790]
### Description

When the resources in my app are in the app-level resource dictionary, the app doesn't respond to the system theme changing (light > dark mode). However, when I move those resources to the page-level resource dictionary, the app does respond to the system theme changing.

### Steps to Reproduce

1. Run the attached sample.
2. Toggle the system mode in the simulator (Features menu > Toggle Appearance).

### Expected Behavior

The app reacts to the system theme change and adjusts its colours accordingly (change from light to dark or vice versa).

### Actual Behavior

The time and icons on the status bar change, but the rest of the app doesn't.

But after commenting out the App.xaml resources, and uncommenting the UserSummaryPage.xaml resources, the app responds to system mode changes.

### Basic Information

- Version with issue: 4.6.0.800
- IDE: VSMac 8.6
- Platform Target Frameworks: 
  - iOS: 13.4

### Screenshots

App when simulator is in light mode:

![Simulator Screen Shot - iPhone 11 - 2020-05-20 at 12 36 37](https://user-images.githubusercontent.com/8092460/82442797-3b5eda80-9a98-11ea-86e0-97f0dda93550.png)

App after toggling simulator to dark mode:

![Simulator Screen Shot - iPhone 11 - 2020-05-20 at 12 36 41](https://user-images.githubusercontent.com/8092460/82442810-4154bb80-9a98-11ea-8335-6f12c2682d42.png)

App after toggling simulator to dark mode, when the resources in App.xaml are commented out, and the resources in UserSummaryPage are uncommented:

![Simulator Screen Shot - iPhone 11 - 2020-05-20 at 12 37 07](https://user-images.githubusercontent.com/8092460/82442847-56c9e580-9a98-11ea-90f1-1293e0abdfa5.png)

### Reproduction Link

[SystemThemesDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4656540/SystemThemesDemo.zip)

### Workaround

Move resources from the app-level resource dictionary to the page-level resource dictionary.

**Comment by MitchBomcanhao** [comment]
Have not tried this yet, but would a better workaround be moving those color styles to a separate resource dictionary that you merge into each page instead of (potentially) having to copy them to each page?

**Comment by davidbritch** [comment]
Closing this, as it's no longer a problem in 4.6-SR4, following the refactoring by @StephaneDelcroix
