### ISSUE TITLE
Forms app crashes giving sigsev

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1027197/forms-app-crashes-giving-sigsev.html)._

---
I have a forms app. When I click on the menu icon, the app crashes. The list is generated in the VM which tells the UI that the list has been updated and to set the ItemsSource to the List. If the list is empty, the view works. If it is populated, the app crashes desppite there being data.

The listview code looks like this

<ListView  x:Name="dataGrid" ItemsSource="{Binding SentPictures}" HasUnevenRows="True" SeparatorVisibility="None" ItemAppearing="ItemAppear">
            <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                        <StackLayout Padding="16,0">
                            <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="3*"/>
                                <ColumnDefinition Width="3*"/>
                                <ColumnDefinition Width="1.5*" />
                                <ColumnDefinition Width="2.5*" />
                            </Grid.ColumnDefinitions>
                            <Label Grid.Column="0" Text="{Binding SentToName}" HorizontalTextAlignment="Start"
                                       VerticalTextAlignment="Center"
                                       Style="{StaticResource label}"/>
                                <Label Grid.Column="1" Text="{Binding FileCreatedString}"
                                       HorizontalTextAlignment="Center" VerticalTextAlignment="Center"
                                       x:Name="date" Style="{StaticResource label}"/>
                                <Label Grid.Column="2" Text="{Binding NumberOfImagesString}"
                                       HorizontalTextAlignment="Center" VerticalTextAlignment="Center"
                                       x:Name="images" Style="{StaticResource label}"/>
                                <CheckBox Grid.Column="3" IsChecked="{Binding SendSucceed}" HorizontalOptions="Center"
                                          HeightRequest="16" WidthRequest="16" x:Name="succeed"
                                          CheckedChanged="TapGestureRecognizer_Tapped" ClassId="{Binding id}"/>
                            </Grid>
                            <Label Text="{Binding ErrorMessage}" HorizontalTextAlignment="Center" 
                                   IsVisible="{Binding Converter={StaticResource Visible}, ConverterParameter=ErrorMessage}"
                                   Style="{StaticResource label}" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>

the converters are not being hit (break points set in the converters). The app uses the Xamarin material nuget package and the converters convert from DateTime to string and int to string. My class also has two properties that does thge same as the converters, but I still get the crash (the code above doesn't use the converters, but does use the two properties in the model)

---
#### Visual Studio Feedback System on 5/12/2020, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marie Shi [MSFT] on 5/12/2020, 08:17 PM: 

<p>Hi Paul,</p>
<p>Thanks for your feedback! From your description in the ticket, it seems not to be a Winforms project, so which project template did you create?</p>
<p>Thanks,<br>
Marie</p>

#### Paul Johnson on 5/13/2020, 01:50 AM: 

<p>Xamarin Forms - can't remember the last time I used WinForms!</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Pinged for Repro

https://developercommunity.visualstudio.com/comments/1044621/view.html

**Comment by nodoid** [comment]
Source code here : https://pastebin.com/bkRDrDx0

If the model has nothing in it, the view works fine. If the view has anything in it - boom! crashes with the throwback attached to the bug report here : https://developercommunity.visualstudio.com/content/problem/1027197/forms-app-crashes-giving-sigsev.htm

Let me know if you need anything else. This happens all the time on droid and iOS and only on this view (the app has other listviews, all work fine)

**Comment by jsuarezruiz** [comment]
@nodoid In order to replicate the same situation and know what is happening, could you add the code used in some Converters, etc. (Example: LanguageConverter, etc) or to attach a small example with the view and the converters, etc?

**Comment by nodoid** [comment]
@jsuarezruiz - let me know if this helps

[Corpserv.zip](https://github.com/xamarin/Xamarin.Forms/files/4716864/Corpserv.zip)

**Comment by nodoid** [comment]
@jsuarezruiz  - I've emailed you the project (sorry, it's commercial and difficult to make a working demo of the issue). Let me know when you need the user/pass

**Comment by jsuarezruiz** [comment]
I understand it and I really appreciate it, I will review it!

**Comment by nodoid** [comment]
Thanks - emailed the user/pass for it to you

**Comment by nodoid** [comment]
I've tested with a CollectionView and get the same crash

**Comment by jsuarezruiz** [comment]
@nodoid I have tested the App you sent me via email.
Commenting the Tapped event logic from the TapGestureRecognizer used in the Template, everything works fine.

![image](https://user-images.githubusercontent.com/6755973/83758359-4017b700-a672-11ea-9528-bcc5b49fdb12.png)

(Edited the screenshot to hide the data)

**Comment by nodoid** [comment]
Further diggng showed the hotreload was causing the debugger to disguise the issue. Once disabled, it showed a NRE inTapGestureRecognizer_Tapped event (line 55)

**Comment by samhouts** [comment]
@nodoid This sounds like the issue was in your code, not Xamarin.Forms, is that correct?

**Comment by nodoid** [comment]
Hi Sam,

Yes - though the debugger wasn't giving anythhing of use, just the sigsev

**Comment by samhouts** [comment]
I'm going to close this issue, but I will reopen the feedback ticket and redirect to the Hot Reload team to see if we can surface exceptions properly. Thanks!!
