### ISSUE TITLE
[Bug] WebView Does not fire Navigating or Open file in Cache

### ISSUE THREAD

**Issue by sehuff** [xamarin/Xamarin.Forms#10796]
### Description
The WebView control in Xamarin.Forms 4.6.0.800 does not open files or even fire the Navigating event for links to files in the local cache on iOS. I don't know when this broke but if you revert back to version 4.3.0.991250 of Xamarin.Forms and clean the project and do a rebuild - it works.

### Steps to Reproduce

I've attached a sample project showing the problem

1. Run sample project 
2. Click Open WebView
3. Click on sample.pdf link - notice nothing happens.
4. click any other link and notice the even fires with a popup.

### Expected Behavior

Navigating event should fire when clicking a link to a file in the cache in WebView

### Actual Behavior

Navigation does not fire when clicking a link in WebView

### Basic Information

- Version with issue: 4.6.0.800
- Last known good version: 4.3.0.991250

[WebViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4657746/WebViewBug.zip)

**Comment by sehuff** [comment]
We've built a custom MSG viewer that uses the WebView control and not being able to link documents is a huge problem for our corporate application - is there an update on this or a workaround?  Thx.

**Comment by samhouts** [comment]
I think this is related to https://github.com/xamarin/Xamarin.Forms/issues/4396#issuecomment-456462108

**Comment by sehuff** [comment]
> I think this is related to [#4396 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/4396#issuecomment-456462108)

How could this be related when that issue was reported in 2018 and as I pointed out this worked on Version 4.3.0.991250.  If you open the sample I provided and rollback Xamarin.Forms to 4.3.0.991250 you'll see it works then.

**Comment by hjharvey-MSFT** [comment]
@samhouts @sehuff 
I don't think this is an issue with Xamarin but a design change between WKWebView and UIWebView. You can find references on StackOverflow from iOS developers that have the same issue. Lucky for you the fix is pretty straight forward.

From your code example you are taking a HTML File, converting it into a Stream and then adding that steam to a HTMLSource. This then results in trying to load a HTML as string. 
The iOS examples I found with similiar issues were trying to load an HTML stream that contains a link to a local file, this would result in the same error you were getting. Their solution was to save the HTML as a local file, then open that local file using LoadFileURL and provide the folder path to grant access. For you, this is unnecessary, you already have the local HTML file which you are opening, modifying, and then saving. 
At this point you can just provide the file path to the webview and allow it to open the file. You will already have access to the PDF's file location.

Here is your fix
```
  public WebView(string file)
        {
            InitializeComponent();
            webView.Source = file;
        }
```

**Comment by hjharvey-MSFT** [comment]
> I think this is related to [#4396 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/4396#issuecomment-456462108)

Yes I agree, this is very likely related as to have access to local content you need to provide access permission to that local resource file.

**Comment by sehuff** [comment]
> @samhouts @sehuff
> I don't think this is an issue with Xamarin but a design change between WKWebView and UIWebView. You can find references on StackOverflow from iOS developers that have the same issue. Lucky for you the fix is pretty straight forward.
> 
> From your code example you are taking a HTML File, converting it into a Stream and then adding that steam to a HTMLSource. This then results in trying to load a HTML as string.
> The iOS examples I found with similiar issues were trying to load an HTML stream that contains a link to a local file, this would result in the same error you were getting. Their solution was to save the HTML as a local file, then open that local file using LoadFileURL and provide the folder path to grant access. For you, this is unnecessary, you already have the local HTML file which you are opening, modifying, and then saving.
> At this point you can just provide the file path to the webview and allow it to open the file. You will already have access to the PDF's file location.
> 
> Here is your fix
> 
> ```
>   public WebView(string file)
>         {
>             InitializeComponent();
>             webView.Source = file;
>         }
> ```

Thank you!  This does take care of the issue!!

**Comment by hjharvey-MSFT** [comment]
> > I think this is related to [#4396 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/4396#issuecomment-456462108)
> 
> How could this be related when that issue was reported in 2018 and as I pointed out this worked on Version 4.3.0.991250. If you open the sample I provided and rollback Xamarin.Forms to 4.3.0.991250 you'll see it works then.

The reason this is an issue now is the change of the underlining control for WebView. Apple will no longer accept apps that contain UIWebView onto their store, So this has forced a change using WKWebView as the default webview for this control and this has been an issue with WKWebView for a long time.
