### ISSUE TITLE
[Bug] Unable to deploy the iOS app with Web View

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#10794]
### Description
When I was trying to upload the ipa to AppStoreConnect, its failing the submission by giving this error.

![image](https://user-images.githubusercontent.com/14989528/82461510-2609a080-9ad8-11ea-9b9d-5fcce30e9582.png)

### Steps to Reproduce

1. Set Flag and linking behaviour
![image](https://user-images.githubusercontent.com/14989528/82461610-420d4200-9ad8-11ea-8ede-93765f3ae63b.png)

2. Deploy the ipa
3. then upload the app-store connect using application loader

### Expected Behavior
Upload the app without issues to AppStoreConnect
![image](https://user-images.githubusercontent.com/14989528/82461830-754fd100-9ad8-11ea-8ec2-bc1e628a85f1.png)

### Actual Behavior
app fails with following error
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

### Basic Information

- Version with issue:  Xamarin.Forms 4.6 *
- Last known good version: N/A
- IDE: VS for Mac 2019 on Azure DevOps
- Platform Target Frameworks: 
  - iOS:  Default
- Android Support Library Version: 

And also I used web view renderer.

![image](https://user-images.githubusercontent.com/14989528/82462222-f14a1900-9ad8-11ea-84ba-bc74d16b3572.png)

**Comment by jsuarezruiz** [comment]
@kgbuddhima Could you take a look to this blog post: https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

![75816341-507b7580-5d95-11ea-84e0-badd6d376cdd-1536x1126](https://user-images.githubusercontent.com/6755973/82465473-9d7f0600-9abf-11ea-96b5-bc3d4b7ba92b.png)

**Comment by kgbuddhima** [comment]
> @kgbuddhima Could you take a look to this blog post: https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
> ?

Yes it as the one that I followed.

**Comment by kgbuddhima** [comment]
> @kgbuddhima Could you take a look to this blog post: https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
> ?

I was able to solve it by modifying the AzureDevOps pipeline

I made following changes
changed Agent to **macOS-10.15**
Set **Xcode version to 11.4.1**
Set **mono version to 6.8.0**
