### ISSUE TITLE
[Bug] Could not create ipa file for distribution of the archive 

### ISSUE THREAD

**Issue by nitro911** [xamarin/Xamarin.Forms#10805]
### Description
Since upgrading to the latest release of Visual Studio (16.6.0), and Xamarin.iOS 13.18.1.31, my IPAs will not generate to distribute.

### Steps to Reproduce

1. Archive app
2. Click Distribute, Upload to Store
3. Wait a bit and error occurs

### Expected Behavior
IPA is upload to store

### Actual Behavior
Error occurs: 

Could not create ipa file for distribution of the archive '<name>'
MessagingRemoteException: An error occurred on client Buildxxx while executing a reply for topic xvs/Build/16.6.0.1055/execute-task/<name>.iOS/xxxCopy
TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception.
PlatformNotSupportException: Operation is not supported on this platform.

App only changed localization content (strings in RESX and .strings file).

### Basic Information

- Version with issue: 16.6.0
- Last known good version: 16.5.4
- IDE: Visual Studio
- Platform Target Frameworks:
  - iOS:  13.18.1.31
- Nuget Packages: AppCenter, Xamarin.Essentials, Xamarin.Forms, Xamarin.Forms.Visual.Material, SuaveControls.FloatingActionButton, Xam.Plugin.Media
- Affected Devices: All

### Screenshots

Text self-explanatory

### Workaround

None

**Comment by ggbarcelos** [comment]
I have similar problem
![Anotação 2020-05-21 091335](https://user-images.githubusercontent.com/17346615/82558140-68b49280-9b43-11ea-8bb3-80bf732abfb0.png)

**Comment by Filipowicz251** [comment]
+1

![obraz](https://user-images.githubusercontent.com/21036476/82691183-cb01b600-9c5d-11ea-8667-0955f73eaf9d.png)

**Comment by jameshowey** [comment]
+1

**Comment by Filipowicz251** [comment]
I did manage to publish the app on MAC. On VS 2019 for Mac, I've changed Release --> Generic Device. And then Archive->Distribute. It works correctly.

Hopefully, it will be a workaround for anybody struggling with this issue, till it is fixed;)

One small catch there. When you are asked to enter app id and password - it is not your apple password - it is app-specific password :) I am being fooled by this feature each and every time :)

https://stackoverflow.com/questions/58112183/publising-failed-we-are-unable-to-create-an-authentication-session

**Comment by burakyigit** [comment]
+1 

everytime when i get an update for microsoft products, i regret my decision.

**Comment by jameshowey** [comment]
I can deploy app by going to mac and uploading from xcode.
- in vs, do not select build ipa in ios app settings
- archive app on windows with vs
- on mac, xcode -> windows -> organizer. You see mirrored archived apps
- select desired build, and click verify
- you will be given an opportunity to update certificates to replace any bogus ones entered in ios signing config
- My first attempt failed because the ios AppIcon hadn't been set in the ios info.plist. The actual pngs were present in the build but hadn't been named in the ios app properties.
- On selecting upload, I was successful, but received an email saying that the build had been rejected because UIKit rendering had been deprecated.
- I rebuilt after applying the Xamarin mtouch setting --optimize=experimental-xforms-product-type in the ios build settings
- success

**Comment by PureWeen** [comment]
Can anyone having this issue use the feedback tool on VS to log a bug please?
https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

That will gather up some logs that will be helpful for the team responsible for this feature

**Comment by Lydecker** [comment]
https://developercommunity.visualstudio.com/content/problem/961282/xamarinios-fails-to-build-with-messagingremoteexce.html

**Comment by tsafadi** [comment]
Same issue here...

**Comment by emaf** [comment]
Hi all, we're tacking this problem here https://developercommunity.visualstudio.com/content/problem/961282/xamarinios-fails-to-build-with-messagingremoteexce.html.

Thanks!

**Comment by amantha** [comment]
Deleting content of \obj and \bin in iOS project helped me !

**Comment by nitro911** [comment]
Great--closed, and no resolution!

**Comment by Lydecker** [comment]
This has now been fixed in the latest VS Release 16.6.1
