### ISSUE TITLE
MSBuild:UpdateDesignTimeXaml code generator crashed

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10802]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1023105/msbuildupdatedesigntimexaml-code-generator-crashed.html)._

---
Solution was reloading and getting “MSBuild:UpdateDesignTimeXaml code generator crashed” logs in the Tool output window.
End result, solution not loaded, needed to close and reopen VS for Mac

---
#### Visual Studio Feedback System on 5/8/2020, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by divyesh008** [comment]
@samhouts I'm also facing same issue after updating xamarin forms packages to latest version. You can reproduce it if you have project with old xamarin.froms update it to latest one and try to build and run in Android device you will get this error.

**Comment by StephaneDelcroix** [comment]
@divyesh008 it is not unexpected to have to clean your solution and/or restart your IDE when you upgrade your nuget packages

**Comment by weeswings** [comment]
I think I'm getting this issue as well, so here's what I've managed to narrow it down to.

When I create a new Blank Forms App, it loads in with 4.5.0.495 as the default package for Xamarin Forms. Everything works normally. As soon as I update Forms to the current stable of 4.7.0.968, UpdateDesignTimeXaml stops working with an "Errors in file generation." message.

I have tried Clean All, restart IDE, rebuild, tried deleting bin/obj folders and restarting, but nothing gets UpdateDesignTimeXaml working again in the solution. Everything builds as expected, it just means you're getting errors throughout the IDE and 

The instant I downgrade to Forms 4.6.0.967, UpdateDesignTimeXaml starts working, no rebuild required.

**Comment by Big-al** [comment]
Im getting this issue as well. I had enabled Hot reload in xamarin, and was deploying from a MacOS device to an IpadOS device. As soon as the deployment startet, i cancelled the process. After this, i was getting the same error, which was fixed by restarting visual studio.
