### ISSUE TITLE
[Bug] XAML Hot Reload, No Source Info for element declared in Data Template

### ISSUE THREAD

**Issue by chabiss** [xamarin/Xamarin.Forms#10803]
[XamarinTest - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/4658904/XamarinTest.-.Copy.zip)

### Steps to Reproduce

1.  Open the attached project which contains a simple ListView with a DataTemplate
2. Run
3. Observe the debug output where the app added a trace to the VisualTreeChangedEventArgs

### Expected Behavior
The Data Template should have full source info for the element declared

### Actual Behavior
The trace below shows that the data template has no source info.    This breaks XAML Hot Reload Incremental support. 

VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
05-20 12:11:54.774 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.775 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
05-20 12:11:54.775 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.788 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
05-20 12:11:54.789 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::

05-20 12:11:54.790 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
05-20 12:11:54.792 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.806 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
05-20 12:11:54.807 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.807 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
05-20 12:11:54.808 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.824 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
05-20 12:11:54.825 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
05-20 12:11:54.826 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
05-20 12:11:54.826 I/mono-stdout(15696): VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=
XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

> VS bug [#1128695](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1128695)

**Comment by jsuarezruiz** [comment]
My trace using Hot Reload with the example is as follows:
```
[zygote] JNI RegisterNativeMethods: attempt to register 0 native methods for crc643f46942d9dd1fff9.CellRenderer_RendererHolder
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:::--> Xamarin.Forms.Label:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:::--> Xamarin.Forms.StackLayout:::
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:::
```

When refreshing, I have a blank screen.
