### ISSUE TITLE
[Bug] BackButtonBehavior Command does not invoke on iOS. 

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#10811]
### Description
The BackButtonBehaviour Command does not invoke on iOS. It works fine on Android. In the sample app go to SecondPage. Than navigate between SecondPage and ThirdPage several times by clicking the button on the contentpage(not BackButton). Finally from SecondPage click BackButton. The BackButton command should be invoked and FirstPage should be presented. Instead the BackButton Command does not invoke and ThirdPage is Presented

### Basic Information

- Version with issue:Xamarin.Forms 4.6.0.800
- Affected Devices:iOS

### Reproduction Link

[ShellBackbuttonIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4662845/ShellBackbuttonIssue.zip)

### Workaround
Push ModalPage and use ImageButton in place of BackButton to navigate.

**Comment by dhindrik** [comment]
It could be related to #7856 and the PR #8951.

**Comment by PureWeen** [comment]
Yea this is one of the scenarios covered by #8951. 

If you're still having problems after that's merged let me know @HobDev
