### ISSUE TITLE
Xamarin Forms Content Page Toolbar Icon will not change iOS

### ISSUE THREAD

**Issue by raymond-dillon** [xamarin/Xamarin.Forms#10813]
### Steps to Reproduce

1. Run the Solution on Android - Click the button at the bottom of the page
2. Icon will change from black to blue.
3. Repeat the process for the iOS Solution - colour will not change

### Expected Behavior

On iOS - the icon should change from black to blue when the button is clicked

### Actual Behavior

Icon is white initially and does not change colour when clicked.

### Basic Information

- Version with issue:
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - iOS:  Deployment Target is 8 (default on a new project)
  - Android: 9.0 
  - UWP:  N/A
- Android Support Library Version: N/A

- Nuget Packages:
- Affected Devices: iOS Devices

### Reproduction Link

Attached

### Workaround

N/A

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/4663743/App2.zip)

**Comment by jsuarezruiz** [comment]
If you try a different icon, you will see that the icon is changing. What happens is that in iOS and Android the behavior is slightly different. While in iOS the icon is being tinted with `BarTextColor`, in Android it is not.

**Comment by jsuarezruiz** [comment]
We could create a Platform Specific in iOS to avoid tint the icon. @raymond-dillon what's your opinion about it?. You can create an enhancement with your idea.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
