### ISSUE TITLE
[Bug]  ListView with HasUnevenRows="True" is leaking memory (items)

### ISSUE THREAD

**Issue by alexeystrakh** [xamarin/Xamarin.Forms#10820]
### Description

ListView with HasUnevenRows="True" somehow retains items bound to the list view in memory even after full data reload. Basically every reload dumps old entries and creates new items, but old items don’t go away. I was troubleshooting it, trying to find, what exactly retains the entries and found one particular line which caused that: HasUnevenRows="True". Having that information I recreated a sample solution and was able to reproduce the issue by adding that line to my simple ListView with a simple data binding to an ObservableCollection. The number of retained items in memory depends on the Grouping flag, if enabled then all items are retained, if disabled, only 1 per each refresh cycle is retained in memory.

### Additional tests

1. CollectionView in a similar scenario does not leak memory (`ItemSizingStrategy= MeasureAllItems`)
2. If a page which holds the listview is closed, then the list view and all items deallocated as well (even leaked)
3. Grouping is not the primary cause of the leak but with that enabled all the items are leaking
4. This memory leak affects iOS only, and no memory leak is happening on Android.

### Steps to Reproduce

1. Launch the sample app with Xamarin Profiler attached (allocations mode)
2. The page will be automatically dumping all bound data and reloading new (10 cycles)
3. In Xamarin Profiler filter to `MyTestItem` class, mark only live objects and observe that no all of them are garbage collected

### Expected Behavior

Only items currently bound to the listview stay in memory

### Actual Behavior

Some of the items are retained in memory. If you enabled grouping then ALL items will be retained.

### Basic Information

- Version with issue: 4.6.0.800
- Last known good version: N/A
- IDE: VS4Mac 8.6.4526
- Platform Target Frameworks: iOS (only)
  - iOS:  13.18.1.31
- Nuget Packages: None
- Affected Devices: All

### Screenshots

<img width="1911" alt="xf listview memoryleak 1" src="https://user-images.githubusercontent.com/3697084/82631629-d1832580-9baa-11ea-8ae9-f984bb4afa74.png">
<img width="1919" alt="xf listview memoryleak" src="https://user-images.githubusercontent.com/3697084/82631635-d516ac80-9baa-11ea-8662-8556dbc9d7f0.png">

### Reproduction Link

The sample project is here (master branch):
https://github.com/alexeystrakh/xamarinforms-listview-memoryleak

There are a few additional tests with grouping enabled in a separate branch:
https://github.com/alexeystrakh/xamarinforms-listview-memoryleak/tree/master-leak-with-grouping

And navigation which frees the ListView:
https://github.com/alexeystrakh/xamarinforms-listview-memoryleak/tree/master-leak-with-navigation

### Workaround

If the page which holds the listview is a root page, there is no workaround, but if the page is a details page, closing that page will let the listview go, which in turn lets all the retained items go.

**Comment by t-johnson** [comment]
Same issue reported as in #6742 ?

**Comment by AlanYost** [comment]
@t-johnson - Is there a way we can expedite the approval of your fix?  The ListView control with variable heights is so critical to us, but your PR has been outstanding for a few months now...

**Comment by t-johnson** [comment]
@AlanYost - sorry, I'm just providing a contribution. If the xamarin team don't feel its the most valuable use of their time to deal with my PRs, theres not a lot I can do.
In this case, I believe ListView is a deprecated control, in favor of CollectionView, so I can understand why this might take a lower priority to other things they're dealing with (eg, MAUI).

**Comment by AlanYost** [comment]
Thanks for the reply Tim - CollectionView is a joke - It leaks immediately you just have to bind to a collection.  We will try to push this through somehow :-)
