### ISSUE TITLE
[Enhancement] UI remoting/isolation

### ISSUE THREAD

**Issue by ldematte** [xamarin/Xamarin.Forms#10828]
## Summary
In order to facilitate sandboxing and isolation, it is a good idea to isolate components in sandboxes. The historic way of doing it in .NET was using AppDomains, but today the preferred way of doing is just using different processes (more portable/.NET core will not support AppDomains).

The problem is: what about components with UI? All plugin-based systems will need to come up with their own way to support "UI remoting", i.e. rendering in the isolated process and then reporting it back to the main process for the actual UI presentation, in a way similar to Edge/Firefox/Chromium.

## API Changes

WPF provided a solution through INativeHandleContract. Unfortunately, it is heavily dependent on remoting. It could be a good idea to provide a similar API based on some other kind of IPC.

## Intended Use Case
Think about this: what would I need to re-implement Chromium tabs-as-processes using .NET Core/Maui?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
