### ISSUE TITLE
[Bug] Empty NavigationStrack at constructor

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#10823]
When I try to use Navigation in constructor of a page it this leads to errors because in constructor NavigationStack is empty

**Comment by samhouts** [comment]
Please use the entire issue template to help us understand the problem. Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by AlexAba** [comment]
Here I use 2 pages to be sure that stack have at least 1 item. At `Page1` I check how many pages the stack has, as you can see in the repro, at `Page1`'s constructor `Navigation.NavigationStack.Count` has value 0, but it is not right because there is 1 page already.

**Comment by samhouts** [comment]
The constructor is too early to check the navigation stack. At that point, the page is unaware of which stack it is in...it has just been created, not pushed to any stack. Can you try moving your logic to OnAppearing instead? Thanks!

**Comment by AlexAba** [comment]
Is it possible to add new event in future update, that will raised only when page created(right after constructor). If use OnAppearing then logic require additional checks.
