### ISSUE TITLE
[Bug] 16.6.000.1055  Xamarin.iOS  PlatformNotSupportedException

### ISSUE THREAD

**Issue by gdidajj** [xamarin/Xamarin.Forms#10829]
Description：
When I use the latest version of Visual Studio 2019 to generate xamarin.ios, it prompts "TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception.
PlatformNotSupportedException: Operation is not supported on this platform."
and Prompt When I use the simulator to generate Failed to find metadata file "...\ iPhoneSimulator \ Debug \ System. EnterpriseServices. Wrapper.DLL"
### Steps to Reproduce
1.  set "debug" "iPhone"
2. build
3.Error: "TypeInitializationException: The type initializer for 'Microsoft.Build.Tasks.Copy' threw an exception. PlatformNotSupportedException: Operation is not supported on this platform."

1.  set "debug" "iPhoneSimulator"
2. build
3.Error:Failed to find metadata file "...\ iPhoneSimulator \ Debug \ System. EnterpriseServices. Wrapper.DLL"
 
### Basic Information

- Version with issue:
- Last known good version:15.x
- IDE:Visual Studio 2019  
- Platform Target Frameworks: Xamarin 16.6.000.1055
 -Xamarin.iOS:13.18.1.31
- Nuget Packages:
- Affected Devices:

**Comment by GiampaoloGabba** [comment]
This is a Visual Studio bug reported 2 months ago in 16.6 beta that they just ignored, shipped the 16.6 to everyone and then fixed immediatly in 16.7 preview, wich will come in months...
https://developercommunity.visualstudio.com/content/problem/961282/xamarinios-fails-to-build-with-messagingremoteexce.html

Why they did this is obscure to me... but here we go...
We have to install the preview or go with VS Mac :(

I hope that someday Xamarin (and MAUI) will be decoupled by the VisualStudio updates, this is a huge pain in the....

**Comment by gdidajj** [comment]
> This is a Visual Studio bug reported 2 months ago in 16.6 beta that they just ignored, shipped the 16.6 to everyone and then fixed immediatly in 16.7 preview, wich will come in months...
> https://developercommunity.visualstudio.com/content/problem/961282/xamarinios-fails-to-build-with-messagingremoteexce.html
> Why they did this is obscure to me... but here we go...
> We have to install the preview or go with VS Mac :(
> I hope that someday Xamarin (and MAUI) will be decoupled by the VisualStudio updates, this is a huge pain in the....

Thank you, it seems that I have to use the 16.7 preview to solve my current problem.

**Comment by samhouts** [comment]
This should be fixed in an upcoming service release for Visual Studio16.6. In the meantime, yes, please use 16.7 Preview if you can. Thank you for your patience!
