### ISSUE TITLE
[Bug] CollectionView does not change from EmptyViewDataTemplate to NonEmptyViewDataTemplate through data template selector from version Xamarin.Forms 4.5

### ISSUE THREAD

**Issue by poliahrameshkumar** [xamarin/Xamarin.Forms#10831]
### Description
We use CollectionView where till the values load, we show Setting up loading indicator. This indicator is present in EmptyViewDataTemplate. For both EmptyView and NonEmptyView DataTemplates we use data template selector. This works in Xamarin.Forms 4.3 version but in 4.5 and 4.6 this is not working. Even after CollectionView ItemsSource is not empty, still EmptyViewDataTemplate only is present in UI and it is not changing to the required DataTemplate even after the ItemsSource becomes nonempty. 
### Steps to Reproduce

1. Create EmptyViewDataTemplate and NonEmptyViewDataTemplate as part of CollectionView with Xamarin.Forms version 4.5 or above
2. Make EmptyViewDataTemplate display first and add values to CollectionView after sometime
3. You can see the DataTemplate is not changing from EmptyView to NonEmptyViewDataTemplate

### Expected Behavior
DataTemplate should change from EmptyView to NonEmptyViewDataTemplate
### Actual Behaviour
DataTemplate is not changing from EmptyView to NonEmptyViewDataTemplate
### Basic Information

- Version with issue: Xamarin.Forms 4.5 and above (Haven't checked 4.4)
- Last known good version: Xamarin.Forms 4.3
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:   11.4
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.5
- Affected Devices: iPad

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jsuarezruiz** [comment]
@poliahrameshkumar Could you share a small project that demonstrates the issue?. If not, don't worry, but I would like to know how do you validate the validation you use in the DataTemplateSelector to change from one template to other one (just to replicate the same case).

**Comment by poliahrameshkumar** [comment]
@jsuarezruiz It is simple. Make the EmptyViewDataTemplate visible by keeping the item source of CollectionView empty. Then you can load few values to CollectionView and check if the DataTemplate changes from EmptyViewDataTemplate to NonEmptyViewDataTemplate. If required, I can create sample tomorrow and attach here.

**Comment by jsuarezruiz** [comment]
@poliahrameshkumar I created a sample:
[Issue10831.zip](https://github.com/xamarin/Xamarin.Forms/files/4734773/Issue10831.zip)

Is working fine on Android and in iOS is failing the first time, when adding successive items, it works correctly.
<img width="854" alt="Captura de pantalla 2020-06-05 a las 10 08 51" src="https://user-images.githubusercontent.com/6755973/83853064-03e96280-a715-11ea-828c-d966e007c268.png">
So, can reproduce the issue, thanks for the feedback.

**Comment by poliahrameshkumar** [comment]
@jsuarezrui I did little research with both my current app and your sample app. 

The issue in sample app starts appearing from Xamarin.Forms 4.3.0.991250. But this issue is not reproducible with latest Xamarin.Forms 4.6.0.847.

The issue in my current app starts only from Xamarin.Forms 4.4.0.991477 and it is still reproducible with latest Xamarin.Forms 4.6.0.847.

So, the issue I am facing is more related to EmptyView and EmptyViewTemplate of CollectionView. The issue sample you created is more specific to ItemTemplate change. 

Both might be related to each other and but still they differ. We can get to know that by the above observation. Anyhow, Thank you for the sample which gave me a workaround to fix the issue.

**Comment by hartez** [comment]
There's a _small_ possibility #13678 fixes this issue.

**Comment by poliahrameshkumar** [comment]
This issue has got fixed in Xamarin.Forms 5.0. Thank you for the support.

**Comment by poliahrameshkumar** [comment]
This issue has got fixed in Xamarin.Forms 5.0. Thank you for the support.
