### ISSUE TITLE
[Bug] some issues with ResourceDictionary

### ISSUE THREAD

**Issue by makeman-p81** [xamarin/Xamarin.Forms#10834]
1. Currentrly the method `bool TryGetValue(string key, out object value)` has right recursive implementation. Please, see
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L262
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L276
but the indexer has not
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L190
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L206

I believe that the indexer should looks like this and be recursive too
```cs
[IndexerName("Item")]
public object this[string key]
{
	get => TryGetValue(key, out var value) // recursive
		? value
		: throw new KeyNotFoundException($"The resource '{key}' is not present in the dictionary.");
	set
	{
		_innerDictionary[key] = value;
		OnValueChanged(key, value);
	}
}
```
to avoid possible unexpected behavior for case
```
if (dictionary.TryGetValue(key, out var value0)) // true
{
    var value1 = dictioany[key]; // key not found exception
}
```
And, of course, WPF and UWP have recursive implementations for ResourceDictionary.

2. MergedDictionaries property has a lazy initializer (possible, to avoid unnecessary allocations)
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L76
But in some cases allocations had been triggered excessively
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L204
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L205
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L244
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L270
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ResourceDictionary.cs#L275

**Comment by StephaneDelcroix** [comment]
Hi @makeman-p81, thanks for this report.

we know about 1/, it has already been reported (and closed). This is an implementation choice, and we can not change that without it being a breaking change. `TryGetValue` and `{StaticResource}` resolutions are recursive, `indexer` is not.

2/ good catch, lemme fix this quick.

**Comment by makeman-p81** [comment]
@StephaneDelcroix , thanks, nice fixes!

About indexer for me there are not obvious breaking changes.
For example I used slightly customized Xamarin.Forms library with recursive indexer and improved Picker control into [this](https://play.google.com/store/apps/details?id=xyz.makeloft.timely) application and seems that it works fine.
