### ISSUE TITLE
[Enhancement] Make ParameterAttribute public

### ISSUE THREAD

**Issue by haavamoa** [xamarin/Xamarin.Forms#10847]
## Summary
Hi, today I had the pleasure of working with `CollectionView`. I wanted to change my layout, so I added the following:
```xml
<CollectionView.ItemsLayout>
    <LinearItemsLayout />
</CollectionView.ItemsLayout>
```
I tried to compile, but it failed with this:
![image](https://user-images.githubusercontent.com/2527084/82873090-4603ee80-9f34-11ea-829f-449df4e71111.png)

And I thought, woaw. This is nice! They can tell my compiler that there is some properties that are are required to be set for my XAML. I want that! <3 

## API Changes

Change `ParameterAttribute` from `internal` to `public`.

## Intended Use Case
I want to create my own shiny controls. Sometimes I do have a couple of properties that I need you to set, and the only way for me to let you know is to throw when you try to use it and haven't set the properties.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
