### ISSUE TITLE
Xamarin - Request Documentation about Binding / Source qualifiers

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10855]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1015539/xamarin-request-documentation-about-binding-source.html)._

---
Would somebody please either point me to documentation that already exists, or please create some documentation that explains the differences among the different Binding / Source qualifiers:

ReturnCommand = "{Binding Source = {QUALIFIER . . .}, Path=. . .}"

where QUALIFIER can be any of the following:
DynamicResource
x:DynamicResource
Reference
x:Reference
RelativeSource
x:RelativeSource
StaticResource
x:StaticResource

I have discovered bits and pieces of explanation sprinkled throughout the documentation for various topics related to Binding, but I have not discovered a discussion about the differences among these QUALIFIER values in one concise place.

Any help would be greatly appreciated!

---
#### Visual Studio Feedback System on 5/4/2020, 01:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Good places to start:
- https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings
- https://devblogs.microsoft.com/xamarin/binding-possibilities-relativesource/

**Comment by samhouts** [comment]
cc @davidbritch

**Comment by davidbritch** [comment]
Also https://docs.microsoft.com/xamarin/xamarin-forms/xaml/markup-extensions/consuming

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
