### ISSUE TITLE
Can't access the AutoPackage in Forms.WPF renderer to stop the layout control child 

### ISSUE THREAD

**Issue by bharathirajauk** [xamarin/Xamarin.Forms#10863]
### Description
I can access AutoPackage property and set false in Forms UWP, Android and iOS renderer class. But in Forms WPF, I can't access this property. So, i can't layout the control's child manually. 
### Steps to Reproduce

Create Forms.WPF Renderer class as like the below code snippet and try to access the AutoPackage property in constuctor

      public CustomControlRenderer()
        {
         //// Can't access the AutoPackage property in Forms.WPF renderer class
            this.AutoPackage = false;
        }

### Expected Behavior

Want to access AutoPackage property and set false.

### Actual Behavior

I want to set false to AutoPackage and layout my control children myself as like Android, iOS and UWP.

### Basic Information

  - Forms WPF

### Screenshots

Not applicable

### Reproduction Link

No

### Workaround

No

**Comment by jsuarezruiz** [comment]
I have verified the code and `AutoPackage` is not implemented in `VisualElementRenderer` in the WPF backend.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
