### ISSUE TITLE
[Bug] iOS - Radio buttons cause the app to crash in AppStore version

### ISSUE THREAD

**Issue by eddie010** [xamarin/Xamarin.Forms#10868]
### Description
When adding radio buttons to my app, the app crashes in the AppStore version. When debugging all is working well, but when publishing to TestFlight the app crashes as soon as a page with radio buttons is opened. Makes me think this has something to do with the Linker behavior.

### Steps to Reproduce

1. Add radio buttons to your app
2. Publish app to TestFlight
3. Navigate in TestFlight version to page with radio buttons

### Expected Behavior
Show radio buttons as designed in XAML

### Actual Behavior
App crashes leaving an error message: SIGABRT: Default constructor not found for type Xamarin.Forms.Platform.iOS.RadioButtonRenderer

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: -
- IDE: VS for Mac 8.6 (build 4520)
- Platform Target Frameworks: 
  - iOS:  13.5
- Affected Devices: 7 and 11 for sure

**Comment by shahzad-1** [comment]
Having the same issue. I've narrowed it down to the following mtouch argument:

` --optimize=experimental-xforms-product-type`

**Comment by samhouts** [comment]
We need to add the preserve attribute to the ctor. Looks like this one got missed.

**Comment by SteveGrixti** [comment]
When will this update be released? Experiencing the same issue :/

**Comment by Dids** [comment]
As Apple is now marking binaries as invalid that use `UIWebView`, meaning every Xamarin.Forms app, being able to use `--optimize=experimental-xforms-product-type` with the experimental features should be a top priority.

Literally can't push to the App Store (or even TestFlight) because without that flag it'll get rejected and with the flag it will just crash.

**Comment by samhouts** [comment]
closed by #11023

**Comment by MujtabaAli** [comment]
any deadline? when can we expect to be able to use radio buttons?

**Comment by Dids** [comment]
Since 4.7.0 just released, I'm assuming this is live now?
