### ISSUE TITLE
XAML is throwing "False" errors

### ISSUE THREAD

**Issue by pfafft33** [xamarin/Xamarin.Forms#10866]
### Description
XAML is throwing "False" errors

### Steps to Reproduce
Not sure exactly how this came about
1. 
2. 
3. 

### Expected Behavior
XAML should not flag "False" errors

### Actual Behavior
As you can see in the screenshot attached, on Line 20, XAML is complaining:
Type converter failed:  Cannot convert "HeaderEqSetNameColor" into Xamarin.Forms.Color

Even though the syntax is IDENTICAL to other lines of code above that are NOT being flagged as errors.

Also, even though these errors are showing up, the App compiles and runs and behaves cleanly.

### Basic Information

- Version with issue:
VS 2019 Community 16.6.0
Xamarin.Forms 4.6.0.772

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![AppXAML False Errors 20200527](https://user-images.githubusercontent.com/47510341/83005272-35a45000-9fd6-11ea-853c-e9d6b54e0867.PNG)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by hartez** [comment]
@pfafft33 After successfully building and deploying the project, do the errors persist? Do they survive closing and reopening the project?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
