### ISSUE TITLE
[Bug] UWP: CollectionView in DetailPage of an item

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10862]
### Description

i added a collectionView in detailPage of my items and when i click on an item of the CollectionView(from mainPage) and navigating to the detail page, nothing shows up till i resize the window.

### Steps to Reproduce

1. CollectionView in a contentPage(mainPage)
2. Add a CollectionView in DetailPage
3. Navigate to the detailPage of item

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: Unknown
- IDE: Visual Studio 16.6
- UWP:  TargetVersion: 10.0.18362.0 TargetMinVersion: 10.0.17763.0

**Comment by jsuarezruiz** [comment]
I musa validate it, but I think this issue could be fixed by https://github.com/xamarin/Xamarin.Forms/pull/10797

**Comment by mhrastegary77** [comment]
i see your pull request now @jsuarezruiz , thank you SO much for that! it's so painful specially when i using gridLayout and Visual states manager to change span in different screen sizes.

**Comment by mhrastegary77** [comment]
@jsuarezruiz  Will this one fixed by your PR too? or should i make another issue for it? :(
![Video_20-05-30_14-22-03](https://user-images.githubusercontent.com/42671084/83326662-1a159f80-a28b-11ea-8c6c-95d81994c318.gif)

**Comment by jsuarezruiz** [comment]
@mhrastegary77  I'm not totally sure about it, would you have a sample to share?. I would be interested to see the Layout, margins, etc.

**Comment by mhrastegary77** [comment]
sure @jsuarezruiz 

[CollectionView10862.zip](https://github.com/xamarin/Xamarin.Forms/files/4712134/CollectionView10862.zip)
