### ISSUE TITLE
[Enhancement] Allow FontImageSource on LoadingPlaceholder/ErrorPlaceholder

### ISSUE THREAD

**Issue by MSiccDev** [xamarin/Xamarin.Forms#10876]
## Summary
allow FontImageSource as well (this is also a local resource)

## API Changes
public API changes => none

internal API changes => in Image.cs, on BindableProperties for placheolders, add FontImageSource to the allowed types.

## Intended Use Case
use FontImageSource instead of local image if desired

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
