### ISSUE TITLE
[Bug] Random Application Freezes.

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Xamarin.Forms#10871]
### Description

Randomly freezes after idle for some time on visual studio debug instance/install or released apk/bundle. I can't find any pattern or cause to the freezes. 

Note: this issue only started occurring when I switched over to Xamarin Shell.

I hope this is enough information to track it down; if not, please let me know and I will do what I can.

### Steps to Reproduce

1. run the app, in debug or release.
2. wait a bit, try to navigate, or interact, and the app doesn't respond.
3. Try again as it doesn't always occur.

### Expected Behavior
Be responsive after inactivity or navigation.

### Actual Behavior
App freezes at random and must be restarted to continue.

### Basic Information

- Version with issue: 4.5+
- Last known good version: 4.x
- IDE: Visual Studio 2019 v16.6.0
- Platform Target Frameworks: 
  - iOS:  13.16.0.13 
  - Android: 10.0  
  - UWP: I don't target this platform.  
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

### Reproduction Link

https://github.com/Jakar510/FlickerTest

### Workaround
none found yet.

**Comment by jsuarezruiz** [comment]
@Jakar510 It happens on Android and iOS? Does it happen on any specific emulator or device?

**Comment by hartez** [comment]
> Note: this issue only started occurring when I switched over to Xamarin Shell.

@Jakar510 The application at your repro link does not appear to use Shell - is there another version somewhere?

**Comment by Jakar510** [comment]
I'll make a new repository tomorrow. Sorry for the delays.

**Comment by Jakar510** [comment]
https://github.com/Jakar510/FreezeTest

**Comment by rmarinho** [comment]
Hey, i tried to reproduce but wasn't able to. 

But i also added these packages because the IDE told me so :)

```
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.1.0.1" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.0.0.1" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.1" />
```

can you add these and try again. Did you also tested in any specific device ?

**Comment by Jakar510** [comment]
I found the issue. It was a background thread causing issues.
