### ISSUE TITLE
[Enhancement] Add 'OnClosing' event to SwipeView

### ISSUE THREAD

**Issue by devcrux** [xamarin/Xamarin.Forms#10872]
## Summary
When using SwipeView there are situations where you might want to handle **OnClosing** for the SwipeView. At the moment there is an **CloseRequested** event which fires when you programmatically close the SwipeView but does not take care of manually swiping to close the SwipeView.

## API Changes
Add 'OnClosing' event to SwipeView

e.g.
private void OnClosing(object sender, EventArgs e)
{
      //Do something before closing
}

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
