### ISSUE TITLE
[Bug] Flyout behavior Disabled - Does not disable Flyout

### ISSUE THREAD

**Issue by MadSam08** [xamarin/Xamarin.Forms#10880]
### Description
In Shell, Flyout behavior : Disabled - Does not actually disable the flyout menu.

A workaround can be done by hiding the top bar but the user can still swipe in from the left side to access the menu.
It appears intended functionality is described as "Disabled – indicates that the flyout can't be opened by the user."

### Steps to Reproduce
Use the latest Xaminals project
FlyoutBehavior="Disabled" to the shell object
Tested on Android 9.0(Pie) Emulator and iOS 13.4 Simulator 
Flyout never gets disabled.

Disabled – indicates that the flyout can't be opened by the user.
Flyout – indicates that the flyout can be opened and closed by the user. This is the default value for the FlyoutBehavior property.
Locked – indicates that the flyout can't be closed by the user, and that it doesn't overlap content.

### Actual Behavior
The flyout is still available to the user and all flyout items are active but the once disabled the flyout menu does not collapse.

### Basic Information
VS 2019 - 16.6.0
Xamarin.Forms - 4.6.0.800
NETStandard.Library 2.0.3

### P.S this is not a duplicate, the issue still exist.

**Comment by jsuarezruiz** [comment]
Everything seems to work in the StoreGallery sample from Core Gallery:
![issue10880](https://user-images.githubusercontent.com/6755973/83394411-d3de4e80-a3f8-11ea-9ac9-7e2fae419cf6.gif)
But, can reproduce the issue in the Xaminals sample.

**Comment by MadSam08** [comment]
@jsuarezruiz can you give me a link to the StoreGallery app, to have a look, in the app that I'm working it's the same behavior as in Xaminals, maybe I did miss something in shell configuration

**Comment by jsuarezruiz** [comment]
You can find the code here https://github.com/xamarin/Xamarin.Forms/blob/5bc4be14ec1a8f9cd6408bfb011e66fb3a710961/Xamarin.Forms.Controls/XamStore/StoreShell.xaml.cs
