### ISSUE TITLE
[Bug] Faster and continuous back button click takes control out of the application_Android

### ISSUE THREAD

**Issue by AJBash** [xamarin/Xamarin.Forms#10889]
### Description
I am working with an application that uses the XFNavigation.
App is having multiple pages, where some pages has to validate for data on back button pressed.
If I tap/click back button at normal speed, OnBackButtonPressed is getting triggered properly.However If I tap/click back button at faster rate (Click back continuously), OnBackButtonPressed , the control goes back and even moves out of the application.

Let say I have Pages of  P1 -> P2 -> P3 -> p4 and have to validate data on P2 every time.
Normal click (takes time between clicks) - From : P4 -> P3 -> P2: Triggering OnBackButtonPressed and moves gently.

Continuous Click (Faster click): From P4 -> P3 -> P2 -> P1 OnBackButtonPressed is triggered and moves out of the application.
### Steps to Reproduce

1. Login to the application
2. Navigates to 4th page (for example)
3. On the faster and continuous clicking of physical back button, the control moves out of the application until Login page

### Expected Behavior
1. OnBackButtonPressed should take time to move back for each back button click
2. It should not move back beyond the logged in page of the application. i.e., it should not move out of the application or it should not reach login page.
### Actual Behavior
1. It is moving back and the control comes out of the application, and reaches the login page
### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Redmi Note4

**Comment by jsuarezruiz** [comment]
Attached a sample:
[Issue10889.zip](https://github.com/xamarin/Xamarin.Forms/files/4735583/Issue10889.zip)

Tried to reproduce the issue but cannot move out of the application before `OnBackButtonPressed` is invoked. Could you take a look to the sample?, are we trying the same situation?

![issue 10889](https://user-images.githubusercontent.com/6755973/83868510-47e76200-a72b-11ea-97d2-0d97d9abd0ad.gif)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Wilson1356** [comment]
Hi, @samhouts, @AJBash, @jsuarezruiz,

I am also facing the same issue which was reported by AJBash in the previous comment. After clicking on the button on the login page I am navigating to the Main Page from the Login Page. I am having my Main Page as tabbed page, therefore, after navigation to the child page from the Main Page (Tabbed Page) and navigating to another page from the child page using a button and if the device hardware back button or the back button in the title bar is clicked fast for multiple times the page is moving to the Login Page even though the OnBackButtonPressed event is provided in the first child page and in the Main Page.

I have uploaded my sample project in the below dropbox link
[Dropbox Link:](https://www.dropbox.com/s/031t2zcl5xi0hv4/TestBackButton.zip?dl=0)
