### ISSUE TITLE
[Enhancement] Configure visibility of Overflow button on UWP ToolbarItems

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#10885]
## Summary
The `overflow/ellipsis/more` button is automatically displayed on UWP when `ToolbarItems` are defined on the `Page`.

In many cases, this is not useful, for example when displaying a close button at top right.

## API Changes
I propose to add a `UWP` platform specific `AttachedProperty` to define the visibility of overflow button.

````cs
public static readonly BindableProperty IsOverflowButtonVisibleProperty = 
  BindableProperty.CreateAttached("IsOverflowButtonVisible", typeof(bool), typeof(Page), true);
````

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
