### ISSUE TITLE
[Bug] macOS Label.Rotation is not working

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#10886]
Setting `Label.Rotation `property has no effect. Animation works though (`Label.RotateTo()`).

**Comment by jsuarezruiz** [comment]
Hi @maxim-saplin. Could you share more information like the Xamarin.Forms version used, etc?.
I have done some tests on Xamarin.Forms 4.7 and cannot reproduce the issue.
![mac-rotation](https://user-images.githubusercontent.com/6755973/83392767-f15de900-a3f5-11ea-88ac-efa9be2d20ce.gif)

Using:
`label.Rotation = value;`

Could you attach a reproduction sample?

**Comment by maxim-saplin** [comment]
Initially tried it on 4.4 (the version that doesn't have font issues https://github.com/xamarin/Xamarin.Forms/issues/10101), also checked it on 4.7 pre 2. 

That's what I get on both 4.4 and 4.7 pre 2:
<img width="492" alt="Screen Shot 2020-06-01 at 12 24 26" src="https://user-images.githubusercontent.com/7947027/83396170-3d178f00-a404-11ea-848e-7858096a2c39.png">

And that's what I get on Android:

![3f653dd7-c27f-4e78-b5f2-8e7ff00e1961](https://user-images.githubusercontent.com/7947027/83396466-b1eac900-a404-11ea-9fd1-7204a9ce0cb4.jpeg)

Here's the code:

```
var label = new Label()
{
    Text = "Dope",
    TextColor = new Color(rand.NextDouble(), rand.NextDouble(), rand.NextDouble()),
    AnchorX = 0.5,
    AnchorY = 0.5,
    Rotation = rand.NextDouble() * 360
};

AbsoluteLayout.SetLayoutFlags(label, AbsoluteLayoutFlags.PositionProportional);
AbsoluteLayout.SetLayoutBounds(label, new Rectangle(rand.NextDouble(), rand.NextDouble(), 80, 24));

absolute.Children.Add(label);
```

**Comment by jsuarezruiz** [comment]
Thanks for the reply. I have done tests with the previous code and I can reproduce the issue.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
