### ISSUE TITLE
[Bug] I have upgrade Xamarin.Forms version to 4.6.0726 and app not working in Android

### ISSUE THREAD

**Issue by divyesh008** [xamarin/Xamarin.Forms#10887]
### Description
Plugin version: 4.1.4

### Steps to Reproduce

1. Upgrade Xamarin.Forms version to 4.6.0.726
2. Upgrade other nugets version accordingly 

### Expected Behavior
-App should work without any issue 

### Actual Behavior
-App crash upon load in Android platform, on iOS it works fine

### Basic Information

- Version with issue: 4.6.0.726
- Last known good version: 4.5.0.356
- IDE: Visual Studio 2019 mac
- Platform Target Frameworks: 
  - iOS:  13.10.0.17
  - Android: 10.0
  -NetStandard.Library 2.0.3

- Nuget Packages: 
 
- Affected Devices:
Android Nexus 6 Api 29 Emulator, Samsung real device Api 9.0, Asus Zenfone 2.0 Api 5.0

### Warnings

> /Users/mac/.nuget/packages/xamarin.build.download/0.9.0/buildTransitive/Xamarin.Build.Download.targets(88,3): warning XBD100: ItemGroup `XamarinBuildDownloadRestoreAssemblyAar` is no longer supported.  If your build is failing, revert to an older Xamarin.Build.Download version, or migrate your packages to use the new `XamarinBuildDownloadAndroidAarLibrary` ItemGroup.  If your build is succeeding it is safe to ignore this warning.
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2680,3): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="Newtonsoft.Json" culture="neutral" publicKeyToken="30ad4fe6b2a6aeed" /><bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" /></dependentAssembly></assemblyBinding>
>     2 Warning(s)
>     0 Error(s)

**Comment by samhouts** [comment]
@divyesh008 Please update to the latest version of 4.6.0.800. Does that resolve the issue? Thank you!

**Comment by divyesh008** [comment]
@samhouts  I have tried to update it to 4.6.0.800 version but i'm getting below error:

> Package Plugin.LocalNotification 5.0.0 is not compatible with netstandard2.0(.NETStandard,Version=v2.0). Package Plugin.LocalNotification 5.0.0 supports:
>   - monoandroid10.0 (MonoAndroid,Version=v10.0)
>   - netstandard2.1 (.NETStandard,Version=v2.1)
>   - xamarinios10 (Xamarin.iOS,Version=v1.0)

**Comment by samhouts** [comment]
@divyesh008 We're not in control of that package. It looks like that package increased its minimum supported version of netstandard. We did not change that.

**Comment by fazil1979** [comment]
@samhouts Yes, It's plugin issue I have got the solution for it, thanks for the replay!

**Comment by divyesh008** [comment]
@samhouts Yes, It's plugin issue I have got the solution for it, thanks for the replay!
