### ISSUE TITLE
[Enhancement] Possibility to set "android:id" from Xamarin.Forms

### ISSUE THREAD

**Issue by acuntex** [xamarin/Xamarin.Forms#10888]
## Summary
While trying to use the Pre-Launch Report by the Google Play Store, I didn't find a reliable way to set the resource names of the username and password entries. According to the documentation "android:id" has to be set for the bot to fill the fields, but unfortunately Xamarin.Forms does not seem to have a built-in way to set these properties.
This could be also used for UI Tests.

## API Changes

    var entry = new Entry();
    entry.ResourceName = "usernameEntry";

## Intended Use Case
It would be possible to use the automatic tests by the Pre-Launch Report as well as enable the possibility to use UI Test Frameworks that rely on "android:id".

**Comment by bcaceiro** [comment]
I've came across the same problem. 

Is there any way, as of the current state, to overcome this issue?

**Comment by GiampaoloGabba** [comment]
You should be able to do it with a simple effect that take as input a string, then assign it as a ResourceName in the platform specific code.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
