### ISSUE TITLE
[Bug] [Android] CollectionView's ItemTemplate, containing Label with LineBreakMode & MaxLines, shows some blinking artifacts

### ISSUE THREAD

**Issue by mduchev** [xamarin/Xamarin.Forms#10892]
### Description
The CollectionView occasionally has some very strange blinking view artefact that is slowly fading away. I tried to pinpoint the exact template that causes it, but can't say for sure. I am uploading a sample project with the minimum template that I managed to shrink it to. The issue happens when we have a Label with LineBreakMode and MaxLines properties. The other wrappers also take a part in it.

### Steps to Reproduce
1. Add a StackLayout with an only child - a CollectionView
2. Add some dummy items to its item sources. The item types doesn't matter. The issue happens when there is no Binding to its items also.
3. Add a very specific item template to it
I am not sure about the exact steps/template. I managed to narrow it down to a CollectionView with a very specific ItemTemplate. Please look at the attached demo project.

The StackLayout wrapper matters. If we have only a CollectionView, the issue doesn't happen. Also, the other stuff also matters - the fixed Height/Width, the Grid.Rows, etc.

### Expected Behavior
The UI will render without any blinking artifacts
### Actual Behavior
The UI renders and there is a blinking view at the end of the Label row that slowly fades away
### Basic Information

- Version with issue: 4.6.0.800
- Last known good version: N/A
- IDE: Rider for macOS & Visual Studio for macOS
- Platform Target Frameworks: 
  - Android: v10

### Screenshots
Here is a running gif of the issue. It happens every time the app goes to foreground. Also, it happens when we rotate the view. Logically, it must happen on each redraw of the UI.

![2020_05_29_16_07_48](https://user-images.githubusercontent.com/8217099/83264509-d9555200-a1c8-11ea-9b43-05c3d148e348.gif)

### Reproduction Link
[DemoCollectionViewBlinking.zip](https://github.com/xamarin/Xamarin.Forms/files/4701941/DemoCollectionViewBlinking.zip)

### Workaround
No workaround for now.

**Comment by samhouts** [comment]
@mduchev Those are little scroll bars. We've got a PR open to fix this soon! Thanks for the report.
