### ISSUE TITLE
[Bug] [Shell] Navigation URL parameter not correctly encoded/decoded

### ISSUE THREAD

**Issue by Jabbah76** [xamarin/Xamarin.Forms#10899]
### Description

Using Xamarin.Forms Shell navigation a URL is not correctly passed from one viewmodel to another viewmodel. Either the source viewmodel is not correctly encoding the URL, or the destination viewmodel is not correctly decoding it.

The :// part of the URL ends up with :/

For example, when you pass **http://www.google.com** to the destination viewmodel, the resulting URL becomes **http:/www.google.com** (with a single slash)

### Steps to Reproduce

Using the following code in the source viewmodel:

```
string url = "http://www.google.com";
await Shell.Current.GoToAsync($"general/showUrl?myUrl={url}");
```

In the destination viewmodel:

```
[QueryProperty("MyUrl", "myUrl")]
public class ShowImageViewModel : BaseViewModel
{
    private string _myUrl;

    public string MyUrl
    {
        get => _myUrl;
        set
        {
            _myUrl = Uri.UnescapeDataString(value);
            OnPropertyChanged("MyUrl");
        }
    }
}
```

Here, _myUrl is http:/www.google.com.

I also tried to escape the URL before passing it, but that doesn't work:

`await Shell.Current.GoToAsync($"general/showUrl?myUrl={Uri.EscapeUriString(url)}");`

### Expected Behavior

Source URL == Destination URL

### Actual Behavior

2 slashes end up as 1 slash when passed.

### Basic Information

- Version with issue: 4.6.0.800
- IDE: Visual Studio MAC
- Platform Target Frameworks: 
  - Android: 9.0 

### Workaround

In destination ViewModel:

`_myUrl = Uri.UnescapeDataString(value).Replace(":/", "://");`

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9449
