### ISSUE TITLE
[Bug] UWP: TitleBar ForgroundColor not changing

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10900]
### Description
in my UWP projects i can't change the color of TitleBar's Text! it's always Black.
and also i tested RGBA too and nothing happend.

### Steps to Reproduce
1. in UWP project>mainpage.xaml.cs> add the following

     var titleBar = ApplicationView.GetForCurrentView().TitleBar;
     titleBar.ForegroundColor = Windows.UI.Colors.White;
 
2. and build the app

### Expected Behavior

TitleBar forground color change.

### Basic Information

- Version with issue: 4.6
- Last known good version: unknown
- IDE: Visual Studio 16.6
- UWP: TargetVersion: 10.0.18362.0 TargetMinVersion: 10.0.17763.0

### Screenshots
![Screenshot (833)_LI](https://user-images.githubusercontent.com/42671084/83323523-9e105d00-a274-11ea-8c0d-01857ba3c806.jpg)

**Comment by jsuarezruiz** [comment]
I have tried to reproduce the issue without success:
<img width="836" alt="Captura de pantalla 2020-06-01 a las 10 07 37" src="https://user-images.githubusercontent.com/6755973/83389005-beb0f200-a3ef-11ea-9eb6-b37f43c29734.png">

Attached the reproduction sample using latest Xamarin.Forms 4.6 version:
[Issue10900.zip](https://github.com/xamarin/Xamarin.Forms/files/4710124/Issue10900.zip)

@mhrastegary77 Could you attach a reproduction sample?

**Comment by mhrastegary77** [comment]
@jsuarezruiz  it seems White color doesn't works for Forground with light kinda colors.
so i think it's a winui issue right? :(

[titleBar10900.zip](https://github.com/xamarin/Xamarin.Forms/files/4710293/titleBar10900.zip)

**Comment by jsuarezruiz** [comment]
Something like `Color.FromArgb(255, 254, 254, 254)` must work.

**Comment by mhrastegary77** [comment]
Thanks it worked ❤
