### ISSUE TITLE
[Enhancement] Make TableSection color more customizable

### ISSUE THREAD

**Issue by holecekp** [xamarin/Xamarin.Forms#10903]
## Summary
TableSection color cannot be easily customized from Xamarin.Forms. On Android, a text and a line is rendered for TableSection. There are currently two possibilities how to change their color. This is important for the dark theme support:

1. Modify **colorAccent** in the _Resources/values/styles.xml_ file in the Android project. This changes appearance of both the text and the line. It would be possible to create _values-night_ folder, and specify there the color for the dark mode, but a great disadvantage is that colorAccent is used for other controls, too. So it is impossible to change the appearance only for TableSection without changing color also for other controls.

2. Set **TableSection.TextColor** in the Xamarin project. However, this changes color only for the text. The color of the line underneath it remains the same as it can be seen in the following image:
![TableSectionColor](https://user-images.githubusercontent.com/24872113/83334328-f744b480-a2a5-11ea-9d9b-284e88d1e20e.png)

Another disadvantage of TableSection.TextColor is that **it cannot be used with DynamicResource** and it is therefore **useless when the color is defined with AppThemeColor**.

For example this code will work, but if you replace StaticResource  with DynamicResource in it, there will be no error but the color will be ignored.:

```xml
    <ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="tableSectionColor">#2196F3</Color>
        </ResourceDictionary>
    </ContentPage.Resources>

    <TableView Intent="Settings">
        <TableRoot>
            <TableSection Title="Ring" TextColor="{StaticResource tableSectionColor}">
                <SwitchCell Text="New Voice Mail" />
                <SwitchCell Text="New Mail" On="true" />
            </TableSection>
        </TableRoot>
    </TableView>
```

## Proposed enhancement
TableSection.TextColor should change the color not only for the text but also for the line. Alternatively, a new property (e.g. UnderlineColor) can be added for the color of the line. The colors should support DynamicResource.

## Intended Use Case
Setting color for TableSection is important for the dark mode implementation.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
