### ISSUE TITLE
[Bug] UWP DatePicker andTimePicker Focus() function does not open the popup to set the date/time

### ISSUE THREAD

**Issue by vchelaru** [xamarin/Xamarin.Forms#10909]
### Description

Calling DatePickerInstance.Focus() or TimePickerInstance.Focus() does not open the DatePicker or TimePicker "popup" UI for picking date or time on UWP, but it should. This seems to be a UWP-specific problem.

### Steps to Reproduce

1. Create a UWP Xamarin.Forms project
2. Add a DatePicker, a TimePicker, and a Button
3. On the Button.Clicked event, add code to call `Focus()` on the DatePicker and TimePicker

### Expected Behavior

The DatePicker and TimePicker UI should pop up, allowing the user to pick date and time.

### Actual Behavior

On UWP, the DatePicker and TimePicker do not expand. On Android they do.

### Basic Information

- Version with issue: Xamarin.Forms UWP 4.4.0.991640
- Last known good version: Unknown
- IDE: Visual Studio 2019 (16.4.2)
- Platform Target Frameworks: 
  - Android: Xamarin.Android SDK 10.1.1.0 targeting Android 9.0 (API 28) - works correctly here 
  - UWP:  Target version Windows 10, version 1803 (build 17134) 
- Nuget Packages:
Xamarin.Forms 4.4.0.991640
- Affected Devices:

### Workaround

I could not figure out a work-around for this. Fortunately our production version of the app is not currently using UWP, so the Android solution works.

**Comment by jsuarezruiz** [comment]
@vchelaru Thanks for the issue description. This PR https://github.com/xamarin/Xamarin.Forms/pull/10916 will fix this issue.

![fix10909](https://user-images.githubusercontent.com/6755973/83418848-84157c80-a424-11ea-8759-d249e1f43ea2.gif)

**Comment by johnshardman** [comment]
Surely this should be optional behavior on UWP? I would argue that it's not standard behavior on Windows platforms, and that is more important to users of apps on Windows than consistency with Android & iOS. Make it optional please so that the developer can decide based on scenario & user expectation.
