### ISSUE TITLE
[Bug] Collection View When Orientation Changes

### ISSUE THREAD

**Issue by jorgemht** [xamarin/Xamarin.Forms#10902]
### Description

In Android when you change the orientation of the screen from vertical to horizontal, the elements of the view collection stays in the middle of the screen. In iOS there is no problem.

### Steps to Reproduce

1. Project>yourpage.xaml> add the following

        <CollectionView Margin="20,0" d:ItemsSource="{Binding Monkeys}">
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Baboon</x:String>
                    <x:String>Capuchin Monkey</x:String>
                    <x:String>Blue Monkey</x:String>
                    <x:String>Squirrel Monkey</x:String>
                    <x:String>Golden Lion Tamarin</x:String>
                    <x:String>Howler Monkey</x:String>
                    <x:String>Japanese Macaque</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
            <CollectionView.ItemsLayout>
                <LinearItemsLayout ItemSpacing="20" Orientation="Vertical" />
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate>

                    <Frame
                        Margin="20"
                        BorderColor="DarkGray"
                        CornerRadius="5"
                        HasShadow="True"
                        HeightRequest="300"
                        HorizontalOptions="Center"
                        VerticalOptions="CenterAndExpand">
                        <StackLayout>

                            <Label
                                FontAttributes="Bold"
                                FontSize="Large"
                                HorizontalOptions="Center"
                                Text="-------------"
                                VerticalOptions="Center" />

                        </StackLayout>
                    </Frame>

                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

### Expected Behavior

![Screenshot_20200530-171524](https://user-images.githubusercontent.com/6632773/83332401-4d602a80-a29b-11ea-9809-eca03e249e46.jpg)

**Change orientation**

![Screenshot_20200530-172856](https://user-images.githubusercontent.com/6632773/83332373-2e619880-a29b-11ea-9124-193f984b7835.jpg)

### Actual Behavior

![Screenshot_20200530-171524](https://user-images.githubusercontent.com/6632773/83332401-4d602a80-a29b-11ea-9809-eca03e249e46.jpg)

**Change orientation**

![Screenshot_20200530-171506](https://user-images.githubusercontent.com/6632773/83332346-007c5400-a29b-11ea-834d-461900362378.jpg)

### Basic Information

- Version with issue: 4.6
- Last known good version: unknown
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android:  TargetVersion: 10(API Level29 - Q) TargetMinVersion: 7.0 (Nougat)

### Workaround

Change          

          <CollectionView.ItemsLayout>
                <LinearItemsLayout ItemSpacing="20" Orientation="Vertical" />
         </CollectionView.ItemsLayout>

To

          <CollectionView.ItemsLayout>
                <GridItemsLayout
                        HorizontalItemSpacing="10"
                        Orientation="Vertical"
                        Span="1"
                        VerticalItemSpacing="20" />
          </CollectionView.ItemsLayout>

**Comment by jsuarezruiz** [comment]
Attached a sample with the issue code:
[Issue10902.zip](https://github.com/xamarin/Xamarin.Forms/files/4716462/Issue10902.zip)

@jorgemht I have done some tests and cannot reproduce the issue.
![issue10902](https://user-images.githubusercontent.com/6755973/83509747-381e1280-a4cc-11ea-87f4-13f8e8162a58.gif)

Could you take a look at the attached sample?, does it happen on any specific device?

**Comment by jorgemht** [comment]
It may be due to something in my project. I can not replicate what happens to me. Thanks for answering.
