### ISSUE TITLE
Xamarin.Forms MacOS - VisualElement.Scale doesn't change is bounds if placed in AbsoluteLayout

### ISSUE THREAD

**Issue by sady4850** [xamarin/Xamarin.Forms#10918]
### Description
After scaling down a VisualElement (in the attached example it is Button, but is replicable with other elements, i.e. BoxView) continues to handle clicks, taps from the original bounds.

```
private void Button_OnClicked(object sender, EventArgs e)
{
    Button1.Scale *= 0.8;
}
```

### Basic Information
- Platform Target Frameworks: Xamarin Mac
It works on iOS, Android

- Nuget Packages: Xamarin.Forms 4.8.0.1269

### Screenshots

<img width="374" alt="image" src="https://user-images.githubusercontent.com/13216814/83435685-542aa100-a445-11ea-8ab9-764aaa544de3.png">

### Reproduction Link

[ScalingIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4712601/ScalingIssue.zip)

**Comment by sady4850** [comment]
Is where a way to workaround the issue of guys ?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
