### ISSUE TITLE
SwipeView inside the tabbed page problem

### ISSUE THREAD

**Issue by fkbeys** [xamarin/Xamarin.Forms#10913]
### Description
Inside a tabbed page, if i define a swipeview. Buttom and Up items are working, but left or right doesnt work. 

### Steps to Reproduce

1. Lets suppose we have a tabbed page, and inside that tabbed , 2 contentpages A and B in sequence.
2.  In Contentpage B ,if i define an swipeview. Right item doesnt work.
3. On the other hand, in ContentPage A if i define an swipeitem. Left should be worked. But it doesnt work.
At first, the swipeview items 5% reveals, then disappears. 

### Expected Behavior
It s expected to work in the first and last of the tabbed page. In first page of a tabbed page, the left swipe item , and  in the last page, the right swipe item  should be working...
i made a little video to illustrate better my opinion
https://www.youtube.com/watch?v=ybKtuNOxcx4
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

i made a little video to illustrate better my opinion
https://www.youtube.com/watch?v=ybKtuNOxcx4

### Reproduction Link

> VS bug [#1133909](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1133909)

**Comment by jsuarezruiz** [comment]
Attached a sample:
[Issue10913.zip](https://github.com/xamarin/Xamarin.Forms/files/4716665/Issue10913.zip)

I have done several tests mainly on Android where from the video I see is the issue. I cannot reproduce the issue seen in the video.

![issue10913](https://user-images.githubusercontent.com/6755973/83512983-533f5100-a4d1-11ea-92aa-69118d0d4d73.gif)

Could you share some extra information, please? the issue happens on a specific emulator or device? What version of Android do you use? etc

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
