### ISSUE TITLE
Xamarin.Forms android child controls don't render

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10920]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1054966/xamarinforms-android-child-controls-dont-render.html)._

---
Since Xam Form 4.5 there was a bug introduced that child controls inside of grids or buttons sometimes do not render right away when you first instantiate the view, but if you leave view and come back then they appear. The problem was fixed in iOS but still seems to be in Android version even with Xam Forms 4.6
We have two cases in our current app. Both iOS and Android versions are attached for the same view.
The first time you come to the tab, the child controls are just missing from the view. If you click off the tab and come back - then they appear. Its on both a button and Picker child controls/

---
#### tag.guillory on 5/28/2020, 02:12 PM: 

(private comment, text removed)
#### Visual Studio Feedback System on 5/29/2020, 02:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### tag.guillory on 5/29/2020, 06:35 AM: 

(private comment, text removed)
#### tag.guillory on 5/29/2020, 07:21 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
oops, did not mean to close!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by VWilcox2000** [comment]
Have experienced this same behavior to extreme frustration.  I have a fairly complex form with nested stack panels, and I change IsVisible for children to get the one I want shown.  The first time I add buttons to it, they render.  After clearing children and adding more buttons, they are invisible.  This is not consistent, but can vary as I change overall form structure.  Possibly related to this, buttons will stop firing clicked event as well.  I added a dummy button with 0 height and 0 opacity elsewhere in the form, and the click events started firing again.  This behavior persisted after upgrading to 4.8.  Enumerating up the tree and forcing layouts had no effect.  The buttons and container have valid areas allocated, but the Android renderer seems to not be assigned.  The form is kind of big, and simplifying it probably makes the issue disappear, but if you like, I can send the xaml to whatever email.
