### ISSUE TITLE
Xamarin.Forms.Map.VisibleRegion.LongitudeDegrees returns 180 if the view spans the international dateline

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10922]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1055314/xamarinformsmapvisibleregionlongitudedegrees-retur.html)._

---
Xamarin.Forms.Map.VisibleRegion.LongitudeDegrees always returns 180 degrees if the map view spans the international dateline, instead of the proper value based on the zoom level. To reproduce, just inspect the VisibleRegion.LongitudeDegrees element in the debugger when the view is on the dateline. There is a similar issue when spanning the equator - a value of 90 degrees is returned.

---
#### Visual Studio Feedback System on 5/29/2020, 01:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
