### ISSUE TITLE
[Bug] UIColor.UIColor(CoreImage.CIColor) constructor causes segfault on iOS 13.5

### ISSUE THREAD

**Issue by cjbush** [xamarin/Xamarin.Forms#10927]
### Description
Using the UIColor constructor that accepts a CoreImage.CIColor as a parameter to set the TextColor of a UITextField crashes the app with a segmentation fault in iOS 13.5. This only seems to affect setting the TextColor in a UITextField. BackgroundColor seems to work fine.

### Steps to Reproduce

1. Create a custom control that extends Entry. Create a custom EntryRenderer in the iOS project, and set the Control.TextColor = new UIColor(CoreImage.CIColor.WhiteColor);
2. Add your custom entry control to the main page of the app
3. Launch the app

### Expected Behavior
App runs fine, custom control has white font

### Actual Behavior
App crashes. System logs indicate a segmentation fault

### Basic Information

- Version with issue: 4.6.0.800
- Last known good version:
- IDE: Visual Studio 16.6.0
- Platform Target Frameworks: 
  - iOS:  13.5
- Nuget Packages:
  - Xamarin.Forms 3.6.0.800
  - Xamarin.Essentials 1.5.3.2
- Affected Devices:
  - Just ran on simulator

### Reproduction Link

[Reproduction Repo](https://github.com/cjbush/XamarinTextColorBugDemo)

### Workaround

Set the TextColor to UIColor.White instead.

**Comment by cjbush** [comment]
The critical bit is [here](https://github.com/cjbush/XamarinTextColorBugDemo/blob/master/App1/App1.iOS/Custom/CustomEntry.cs)

**Comment by PureWeen** [comment]
@cjbush are you updated to the latest version of xcode on your mac?

Can you post the exception? I tested your sample and didn't see any issues

**Comment by cjbush** [comment]
Hey @PureWeen, thanks for getting back so quickly. I'm running XCode 11.5 fresh from the App Store, so it should be the latest update. Consulting with our support team, it sounds like this was actually happening for 13.4+ users as well, not just 13.5, but our app is definitely crashing in production without that change. It's weird that the sample isn't crashing for you. There's not a .NET exception, but it actually kills the app with a crash dump. I can post that if it'd be helpful. I just need to track it down on my Mac and strip out any proprietary stuff.

**Comment by jsuarezruiz** [comment]
Using:
`Control.TextColor = new UIColor(CoreImage.CIColor.WhiteColor);`
Can reproduce the issue in iOS 13.5.

**Comment by dalexsoto** [comment]
Hello Friends I was able to reproduce this bug in Xamarin.iOS (without forms)

```csharp
partial void ChangeColor (UIButton sender)
{
    var color = new UIColor(CIColor.BlueColor);
    //var color = new UIColor(GetRandomCIColor ());
    //var color = GetRandomUIColor();

    TextField.TextColor = color;

    if (TextField.IsFirstResponder)
        TextField.ResignFirstResponder();
}

static readonly Random rand = new Random();
public static UIColor GetRandomUIColor() => UIColor.FromHSB(rand.Next(255) / 255.0f, 1, 1);
public static CIColor GetRandomCIColor() => CIColor.FromRgb(rand.Next(255) / 255.0f, rand.Next(255) / 255.0f, rand.Next(255) / 255.0f);
```

And as described this only happens when the `UIColor` is created from a `CIColor` object, but this can also be reproduced in Objective-C and Xcode 11.5 as shown below.

```objective-c
- (IBAction)changeColor:(UIButton *)sender {
    
//  UIColor * color = UIColor.blueColor;
    UIColor * color = [UIColor colorWithCIColor:CIColor.blueColor];
    
    _textField.textColor = color;
    if (_textField.isFirstResponder) {
        [_textField resignFirstResponder];
    }
}
```

So this is not a bug in Xamarin.Forms nor Xamarin.iOS but in the iOS SDK itself.

**Comment by cjbush** [comment]
Thanks for investigating that @dalexsoto! I wasn't sure which side it was on. At the very least I hoped that by filing a bug here on it, someone else might be able to find the answer faster and not waste the hours I spent figuring out where the offending line of code was. It's a very random place for a segfault :)

**Comment by dalexsoto** [comment]
NP and yes I agree, this one is on the really unexpected spectrum...

**Comment by cjbush** [comment]
I went ahead and filed a report on Apple's Feedback Assistant as well, since the issue appears to be in their SDK.

**Comment by PureWeen** [comment]
Thank you for tracking this down @dalexsoto !!!
