### ISSUE TITLE
Xamarin.Forms MacOS - It is not possible to position element outside AbsoluteLayout's bottom

### ISSUE THREAD

**Issue by sady4850** [xamarin/Xamarin.Forms#10936]
### Description

When element's bottom is set to be larger than absoluteLayout's bottom the element is supposed to be visually clipped. Is doesn't happen.

### Basic Information

 - Platform Target Frameworks: Xamarin Mac
It works on iOS, Android

- Nuget Packages: Nuget Packages: Xamarin.Forms 4.7.0.813-pre2

### Reproduction Link

[AbsoluteLayoutIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4719150/AbsoluteLayoutIssue.zip)

**Comment by jsuarezruiz** [comment]
Testing with the latest 4.7 branch, I get the same result on Android, iOS and macOS.
![issue-10936](https://user-images.githubusercontent.com/6755973/83733962-9d9a0c80-a64e-11ea-9e0f-a14f4de03aa6.gif)
Could you add a screenshot of your result?

**Comment by sady4850** [comment]
Sure
![Screen Recording 2020-06-04 at 13 56 55](https://user-images.githubusercontent.com/13216814/83749520-81a56380-a66c-11ea-9153-570a8cbafb26.gif)

**Comment by sady4850** [comment]
@jsuarezruiz Did you have a chance to verify the issue ? Do I need to provide any additional info ?

**Comment by hartez** [comment]
@sady4850 I'm not sure what your ultimate goal is, but you _might_ be able to work around this using a Y Transform.

**Comment by sady4850** [comment]
@hartez thanks for suggestion. Indeed it works but where is another problem - selection rect is not translated with the item. Looks like a variation of #10918. 

Tested with Xamarin.Forms 4.7.0.937-pre4
![translation](https://user-images.githubusercontent.com/13216814/84567247-0cc6dd80-ad80-11ea-81b4-74d80ec375ff.gif)
