### ISSUE TITLE
[Enhancement] Update linter to warn when using "Xamarin" in namespace

### ISSUE THREAD

**Issue by InnerScript** [xamarin/Xamarin.Forms#10939]
## Summary
When using "Xamarin" in a custom namespace as a part of the core app namespace, it will break an entire project without indication as to root cause. Simply the error: "Error CS0234 The type or namespace name 'Forms' does not exist in the namespace 'MyApp.Xamarin'"

Adding any classes with "Xamarin" as a sub-part of the app namespace will break all .xaml file builds.

**Example:**
Create a new Xamarin project, with the namespace "MyApp"

namespace MyApp.Xamarin.Testing {
   public class TestClass() {}
}

**NOTE:** This seems to only apply when "MyApp" is the root namespace for the Xamarin project. It does not seem to apply for custom namespaces such as MyBizName.Xamarin in the same "MyApp" project, but I feel the warning should still apply.

## API Changes

When using "Xamarin" as any part of the app's namespace, the linter should highlight the word "Xamarin" and the Error List should contain a message along the lines of: **"You may not use the reserved keyword 'Xamarin' as part of a namespace"** 

## Intended Use Case
The linter update will save people hours of debugging, as the errors that result do not indicate the actual issue. The errors indicate times when Xamarin must be reinstalled into the project to "clean".

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
