### ISSUE TITLE
[Bug] iOS CellView BindingContextChanged Event -> Null Reference Within ContextActions Clear()

### ISSUE THREAD

**Issue by ncosentino** [xamarin/Xamarin.Forms#10934]
### Description

On iOS (Does not seem to happen on Android with the exact same control setup), there is a situation where a CellView's binding context is changing, but I have reason to believe the CellView is being recycled or something like that. The result is that when I have code in the CellView's event handler for binding context being changed, it crashes when I try to clear the ContextActions observable collection. The collection itself does not appear to be null, but something within the Clear() call is causing the issue.

### Steps to Reproduce

1. Create a list view with an event handler for the cell view's binding context being changed
2. In the event handler, manipulate the cell view's context actions collection (including clearing it)
3. In the app, re-populate the collection of the list view items when you navigate to the page with the list view being described
4. It's not consistent, but continuing to navigate to/from this page that does the regeneration of the list view items will sometimes cause the below stack to appear.

### Expected Behavior

Make it work like how the Android side of things does (i.e. not crash)! Okay, that's not helpful, I know :) Either not trigger the binding context changing (if the cell view in question is actually being destroyed or something) or allow it to trigger but handle why that observable collection has a null reference exception properly.

### Actual Behavior

Crashes on iOS. No issues at all on Android.

### Basic Information

- Version with issue: Xamarin.Forms 4.6.0.800
- Last known good version: ...
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS: Deployment Target 12.0   
  - Android: Android 9, API 28  
  - UWP: Not using.   
- Android Support Library Version: 
- Nuget Packages:
  - Autofac, Version=5.1.2
  - Humanizer, Version=2.7.9
  - MLToolkit.Forms.SwipeCardView, Version=2.1.0
  - Rg.Plugins.Popup, Version=2.0.0.2
  - System.ComponentModel.Annotations, Version=4.7.0
  - System.Linq.Async, Version=4.1.1
  - Xam.Plugins.Forms.ImageCircle, Version=3.0.0.5
  - Xamarin.Auth, Version=1.7.0
  - Xamarin.Forms, Version=4.6.0.800  
  - Xamarin.Essentials, Version=1.5.3.2
  - Newtonsoft.Json, Version=12.0.3
  - Xamarin.Forms.InputKit, Version=3.2.2
  - Xamarin.Forms.Maps, Version=4.6.0.800
- Affected Devices:

### Stack Trace

`EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
Xamarin_Forms_Platform_iOS_ContextActionsCell_OnCellPropertyChanged_object_System_ComponentModel_PropertyChangedEventArgs + 475 (ContextActionCell.cs:475)
Xamarin_Forms_Platform_iOS_ContextActionsCell_OnCellPropertyChanged_object_System_ComponentModel_PropertyChangedEventArgs + 473 (ContextActionCell.cs:473)
wrapper_delegate_invoke__Module_invoke_void_object_PropertyChangedEventArgs_object_System_ComponentModel_PropertyChangedEventArgs + 11299884
Xamarin_Forms_BindableObject_OnPropertyChanged_string + 229 (BindableObject.cs:229)
Xamarin_Forms_Element_OnPropertyChanged_string + 354 (Element.cs:354)
Xamarin_Forms_Cell_OnContextActionsChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 228 (Cell.cs:228)
System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 264 (ObservableCollection.cs:264)
System_Collections_ObjectModel_ObservableCollection_1_T_REF_OnCollectionReset + 363 (ObservableCollection.cs:363)
System_Collections_ObjectModel_ObservableCollection_1_T_REF_ClearItems + 167 (ObservableCollection.cs:167)
System_Collections_ObjectModel_Collection_1_T_REF_Clear + 3343036
My_App_Bundle_MyControl_ViewCell_BindingContextChanged_object_System_EventArgs + 64 (SessionsPage.xaml.cs:64)
Xamarin_Forms_BindableObject_OnBindingContextChanged + 218 (BindableObject.cs:218)
Xamarin_Forms_Element_OnBindingContextChanged + 318 (Element.cs:318)
Xamarin_Forms_Cell_OnBindingContextChanged + 158 (Cell.cs:158)
Xamarin_Forms_BindableObject_BindingContextPropertyChanged_Xamarin_Forms_BindableObject_object_object + 501 (BindableObject.cs:501)
Xamarin_Forms_BindableObject_SetValueActual_Xamarin_Forms_BindableProperty_Xamarin_Forms_BindableObject_BindablePropertyContext_object_bool_Xamarin_Forms_Internals_SetValueFlags_bool + 463 (BindableObject.cs:463)
Xamarin_Forms_BindableObject_SetValueCore_Xamarin_Forms_BindableProperty_object_Xamarin_Forms_Internals_SetValueFlags_Xamarin_Forms_BindableObject_SetValuePrivateFlags + 399 (BindableObject.cs:399)
Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object_bool_bool + 336 (BindableObject.cs:336)
Xamarin_Forms_BindableObject_SetValue_Xamarin_Forms_BindableProperty_object + 311 (BindableObject.cs:311)
Xamarin_Forms_BindableObject_set_BindingContext_object + 41 (BindableObject.cs:41)
Xamarin_Forms_Internals_TemplatedItemsList_2__UnhookItemd__154_TView_REF_TItem_REF_MoveNext + 1207 (TemplatedItemsList.cs:1207)
System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_InvokeMoveNext_object + 2548744
System_Threading_ExecutionContext_RunInternal_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 2045960
System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 2045448
System_Runtime_CompilerServices_AsyncMethodBuilderCore_MoveNextRunner_Run + 2548420
System_Threading_Tasks_SynchronizationContextAwaitTaskContinuation__c___cctorb__7_0_object + 2165220
Foundation_NSAsyncSynchronizationContextDispatcher_Apply + 178 (NSAction.cs:178)
wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 4696284
mono_jit_runtime_invoke + 3164 (mini-runtime.c:3164)
mono_runtime_invoke_checked + 3044 (object.c:3044)
mono_runtime_invoke + 3099 (object.c:3099)
native_to_managed_trampoline_13(objc_object*, objc_selector*, _MonoMethod**, unsigned int) + 712 (registrar.m:712)
-[__MonoMac_NSAsyncSynchronizationContextDispatcher xamarinApplySelector] + 7028 (registrar.m:7028)
__NSThreadPerformPerform + 184
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
__CFRunLoopDoSource0 + 80
__CFRunLoopDoSources0 + 184
__CFRunLoopRun + 788
CFRunLoopRunSpecific + 424
GSEventRunModal + 160
UIApplicationMain + 1932
wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 17479288
UIKit_UIApplication_Main_string___intptr_intptr + 86 (UIApplication.cs:86)
UIKit_UIApplication_Main_string___string_string + 66 (UIApplication.cs:66)
My_App_Bundle_iOS_Application_Main_string__ + 1 (<unknown>:1)
wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 4696284
mono_jit_runtime_invoke + 3164 (mini-runtime.c:3164)
mono_runtime_invoke_checked + 3044 (object.c:3044)
mono_runtime_exec_main_checked + 5167 (object.c:5167)
mono_jit_exec + 1322 (driver.c:1322)
xamarin_main + 484 (monotouch-main.m:484)
main + 152 (main.m:152)
start + 4`

### Reproduction Link

... I want to try getting a small project put together that can repro this.

### Workaround

I have a big ol' try catch block around this event handler's body... But it feels quite wrong. I also see the crash come up in Firebase for me still, which makes me wonder if release mode of this is not allowing me to catch the exception as I might have expected.

**Comment by jsuarezruiz** [comment]
@ncosentino Would you have a small reproduction sample to attach?. Especially I would be interested to see how the list is repopulated, etc.

**Comment by hartez** [comment]
Looks like line 475 of ContextActionCell.cs is missing a null check on `_cell`.
