### ISSUE TITLE
[Enhancement] UWP replace Progressbar with ProgressRing for ActivityIndicatorRenderer

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#10949]
## Summary
ActivityIndicatorRenderer is inheriting UWP Progressbar which should be better ProgressRing.
ProgressBarRenderer is also inheriting  UWP Progressbar which duplication. We need ProgressRing as activity indicator.

## API Changes

Change UWP ActivityIndicatorRenderer 
  
## Intended Use Case
ProgressRing has better visibility than Progress element

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/progress-controls

**Comment by YZahringer** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/10485?

**Comment by jsuarezruiz** [comment]
@EmilAlipiev Thanks so much for the enhancement description. It seems to be the same as https://github.com/xamarin/Xamarin.Forms/issues/10485. Could you take a look to it?. It would be great to group both proposals in a single one as complete and solid as possible.

**Comment by EmilAlipiev** [comment]
@jsuarezruiz yesterday i have implemented and by mistake pushed with other PR. I am trying to cherry pick into another branch best way to separate PRs.

**Comment by EmilAlipiev** [comment]
oh it looks like my commit was already merged into master.  Do i have to do something here?
Any advise? this commits works with ProgressRing. I have a test case for issue also. you can pull and test it. 
https://github.com/xamarin/Xamarin.Forms/pull/10316/commits/cb77488874180e407270fb0da58040e8d9fa5874
