### ISSUE TITLE
[Bug] [iOS] Animating Frame with Shadow Enabled 

### ISSUE THREAD

**Issue by darrabam** [xamarin/Xamarin.Forms#10943]
### Description
Animating (LayoutTo function) a frame with shadow=True results in a frame being stuck in place while another object (duplicate) gets displayed. It's a strange bug that only happens on iOS. Note that I'm not using any custom renders and the sample provided is based on the VS 2019 blank project. 
This bug seems to be introduced in XF 4.5+, as I tested it on the latest 4.4 which doesn't have this issue. 

Please see the animation below. 

- Green: frame with shadow=false
- Red: frame with shadow=true

### Steps to Reproduce
Run the provided simple program. 

![image](https://user-images.githubusercontent.com/33980667/83649738-36357b80-a5c0-11ea-8c80-a7d202f509b0.png)

![image](https://user-images.githubusercontent.com/33980667/83649806-4a797880-a5c0-11ea-87ca-2218e223eeca.png)

### Expected Behavior
The frame (with its shadow) should animate/move when clicked. 

### Actual Behavior
The frame with shadow is stuck in place, while another object emerges. 

### Basic Information

Last known good version: 
4.4.0.991265

IDE: Microsoft Visual Studio Community 2019 (Version 16.5.4)

Platform Target Frameworks: iOS (13.5)

Nuget Packages:
Xamarin.Forms 4.6.0.8
Xamarin.Essentials 1.5.3.2

### Screenshots

![AnimatingFramewithShadowEnabled](https://user-images.githubusercontent.com/33980667/83655733-66cce380-a5c7-11ea-84c5-dc21b88d0b80.gif)

### Reproduction Link

https://github.com/darrabam/AnimatingShadowFrameBug

### Workaround
None.

**Comment by jsuarezruiz** [comment]
@darrabam Tested with Xamarin.Forms 4.7 where the issue seems fixed. Could you try it?

**Comment by darrabam** [comment]
@jsuarezruiz Confirmed! This is fixed in 4.7.0.968.
