### ISSUE TITLE
[Bug] CarouselView in version 4.6.0.800 of Xamarin.Forms does not change position of itemsource on Android but works on iOS

### ISSUE THREAD

**Issue by nichojo89** [xamarin/Xamarin.Forms#10950]
### Description
Version 4.6.0.800 of Xamarin.Forms does not change position when setting "position" value from binding for Android but does work on iOS. This issue was resolved when I downgraded from 4.6.0.800 to 4.6.0.726. You can change position using HotReload and see carousel switch items but when coming from binding it did not work
### Steps to Reproduce
Create a CarouselView binded to an itemsource
observe when Position property changes from binding this switches items on iOS & does not on Android.
You can manually set Position in xaml and use hotreload to verify this should be working. This will work on iOS & not Andorid.

### Expected Behavior
CarouselView should switch to next item in itemsource when Position property of CarouselView is changed from a binding.
### Actual Behavior
On Android Pixel sim it does not switch when changed from binding but it does switch when changed in HotReload
### Basic Information

- Version with issue:
4.6.0.800
- Last known good version:
4.6.0.726
- IDE:
Visual Studio
- Platform Target Frameworks: 
  - Android: Pie api lvl 29
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Google Pixel 2
### Workaround
downgraded to 4.6.0.726

**Comment by VladislavAntonyuk** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/10850
https://github.com/xamarin/Xamarin.Forms/pull/10838
It will be fixed in the next release

**Comment by jsuarezruiz** [comment]
I have created a sample using `CarouselView` binded to an `ObservableCollection`.
[Issue10928.zip](https://github.com/xamarin/Xamarin.Forms/files/4730525/Issue10928.zip)
Then, changing the Position using an Int property binded:

[Issue10928.zip](https://github.com/xamarin/Xamarin.Forms/files/4730538/Issue10928.zip)
Works on iOS

![issue10950-2](https://user-images.githubusercontent.com/6755973/83767170-96d6be00-a67d-11ea-9c6f-08f3db3630f1.gif)
While on Android, works but after change the position doing swipe.

Could be fixed by #10838. @rmarinho What do you think?

**Comment by rmarinho** [comment]
@jsuarezruiz did you test with the next sr ? I think i got a fix in for it 

https://dev.azure.com/devdiv/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=689932

**Comment by Only-Xam** [comment]
Please note that **[UWP] Carouselview + Indicator** also not working as expected on UWP. If we add auto scroll logic, then auto scroll only work during first cycle, when last position or last item is reset to zero, there onward CarouselView scroll  gets stuck. if needed, new Bug can be created.

Note: Tested both cases described below on Android Emulator and CarouselView is working fine on Android.

Xamarin Forms Version - 4.6.0.847

**Case 1**: Auto scroll logic is added in xaml.cs file. In this case when Position is set to 0 after reaching last index, Indicator is switched to Position 0 too, but item shown in carousel is actually the item number 3 (considering index starts with 0) and not item indexed 0. Also, there onward Indicator Position continue to move but Carousel freezes. 

        private void Timer_Elapsed(object sender, ElapsedEventArgs e)
        {
            Device.BeginInvokeOnMainThread(() =>
            {

                if (carouselView.Position < mvm.Monkeys.Count() - 1)
                    carouselView.Position += 1;
               
                else
                   carouselView.Position = 0;
           }
        }
![Carousel_Indicator](https://user-images.githubusercontent.com/66119201/83961359-d8a57580-a8c4-11ea-9836-f8aed169d59b.gif)

**Case 2:** Added auto scoll logic in ViewModel.cs file. In this case, when last indexed item is reached IndicatorView freezes at last index, but carouselview switch to item indexed 3 and then freezes (considering in total there are 5 items in the carouselview).

            if (Monkeys.Count > 0)
            {
                CurrentMonkey = Monkeys[0];

                _slideShowTimer.Elapsed += (o, a) =>
                {
                    var currentIdx = Monkeys.IndexOf(CurrentMonkey);

                    if (currentIdx == Monkeys.Count - 1)
                        CurrentMonkey = Monkeys[0];

                    else
                        CurrentMonkey = Monkeys[currentIdx + 1];
                };
          }
![Carousel_Inidicator_Case_2](https://user-images.githubusercontent.com/66119201/83961669-f922ff00-a8c7-11ea-824a-ba7e76a0d432.gif)

**Comment by rodrigojuarez** [comment]
@jsuarezruiz I don't know if this is related to this bug, but in Android when I set the position programmatically the first time it doesn't set the CurrentItem, but it works the second time without using swipe first. I created a project to test this https://github.com/XamEsp/CarouselPositionIssue.
I'm using Xamarin.Forms 4.6.0.847

![2020-06-15_20-05-45](https://user-images.githubusercontent.com/788727/84714415-fa959c80-af43-11ea-849f-fd2bfa838919.gif)

Notice that when I tap for the first time on C, the position at the bottom changes, but the current item didn't update

**Comment by Only-Xam** [comment]
[UWP] Carouselview + Indicator : CarouselView is completely broken in Xamarin Forms 4.7.0.1179. Only IndicatorView changes position but CarouselView items do not change.

**Comment by rmarinho** [comment]
This seems to be fixed on 4.8.0 latest release and 5.0.0

**Comment by rodrigojuarez** [comment]
The issue I reported in a comment in this bug (in Android when I set the position programmatically the first time it doesn't set the CurrentItem) is still happening for me. Tested on Android Xamarin.Forms 4.8.0.1560
You have a repo with my code at https://github.com/XamEsp/CarouselPositionIssue

**Comment by Only-Xam** [comment]
[**UWP**] - CarouselView autoScroll logic specified above my be earlier is still not working on **XF 5.0.0.1558-pre3**. Even if we increase the **CarouselView.Position** property, Carousel is moved from 0 to 1 and then again back to 0.
Similarly if we manually scroll to last (using mouse), then it will stuck between second last and last position.

**Note**: It is working fine on Android. Also newly added Loop property is working fine on UWP as well.

**Comment by DRAirey1** [comment]
This is still an issue in UWP 5.0.x. The Carousel is very buggy and bounces from one item when setting the position programmatically to the next without any apparent logic.

**Comment by DRAirey1** [comment]
Possible Work Around: disabling the scroll animation seems to fix the problem, at least for UWP.
