### ISSUE TITLE
Commented out xamarin page code still used

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10956]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1035171/commented-out-xamarin-page-code-still-used.html)._

---
Accidentaly noticed this but if you comment our XAML page code which was of different class type like MasterDetailPage and put in a ContentPage at the bottom underneath the commented out code for some reason Visual Studio still generated a partial class of MasterDetail and not of ContentPage class type?

---
#### Visual Studio Feedback System on 5/18/2020, 03:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
In Visual Studio for Windows or macOS?, which version? I have tested in Visual Studio for macOS 8.6.2 and the behavior seems to be correct.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
