### ISSUE TITLE
Repeatedly: The type or namespace name 'Forms' could not be found in 'Xamarin' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#10957]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1057201/repeatedly-the-type-or-namespace-name-forms-could.html)._

---
<p>I have been getting this message on Visual Studio 2019 for PC (16.5).  I am clearing it by removing and re-adding the Xamarin.Forms nuget package.  But, it seems to happen so often now it is impeding my work.  For this and other reasons, today I switch to VS for Mac (8.6.1), and I was shocked that it happens here too.</p> <p>I am in the habit of what someone has called the bin/obj dance (deleting those directories to get a fresh build).    I am (of course), using Xamarin.Forms, currently only for iOS.  I am using the &quot;shared project&quot; approach instead of .NET Shared Library.</p> <p>So, is it just me?  Is there something I can do different?  I have &quot;Nuget&quot; set for &quot;Automatically restore packages when opening a solution&quot;.  Just FYI, this &quot;works&quot; without trouble most of the time, but then gets into this &quot;mood&quot; where it constantly needs attention.</p>

---
#### Visual Studio Feedback System on 6/1/2020, 02:16 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
Shared Assets Projects is no longer the recommended way to work in either VS or with Xamarin.Forms.
We would gladly help you if:
- you can reproduce that in a net standard project, normal project, or using multitargetting
- you provide more information, like VS versions, and a reproduction project

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
