### ISSUE TITLE
[Enhancement] Consolidate type of corner radius properties between all supporting controls

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Xamarin.Forms#10954]
It would be great to have corner radius properties of one type e.g, typeof(CornerRadius), because when you create converter to convert, for example, height to corner radius you have to add extra logic to handle different types of corner radius in different controls such as Frame, BoxView, ImageButton, Button.
Frame`s CR is float; BoxView`s is CornerRadius; ImageButton`s and Button`s CR is int.
Also, it would be great to have possibility to change borderwidth of Frame control

**Comment by jfversluis** [comment]
Thanks for the suggestion here! I think a lot of effort went into .NET MAUI to make this happen, for now we'll leave it in Xamarin.Forms as it is to not make any breaking changes.

If you still feel there is room for improvement in .NET MAUI, please make sure to open an issue there with all the details.
