### ISSUE TITLE
[Bug] Source build error: AppTheme Xaml issue

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#10968]
### Description
Xamarin.Forms.Xaml.XamlParseException: 'Position 18:20. StaticResource not found for key MyColor'

### Steps to Reproduce

1. Run Gallery app
2. Search appTheme
3. run AppTheme XAML

### Basic Information

- Version with issue: master

**Comment by jsuarezruiz** [comment]
Right. `MyColor` was:
`<AppThemeColor x:Key="MyColor" Light="HotPink" Dark="Yellow" />`
And now, this has changed. We will fix this!.

**Comment by VladislavAntonyuk** [comment]
@jsuarezruiz what is the correct way to set color now?
this commit (https://github.com/xamarin/Xamarin.Forms/commit/b6e323d1576c0f6746ad9f4c7b77fe3f5af8e44d) removed a way to set color depends on color.
previously I set 
```
<AppThemeColor x:Key="MyColor" Dark="..." Light=".." />
<Style
        x:Key="Style1"
        TargetType="{x:Type Label}">
        <Setter Property="BackgroundColor" Value="{DynamicResource MyColor}" />
    </Style>
<Style
        x:Key="Style2"
        TargetType="{x:Type Button}">
        <Setter Property="BackgroundColor" Value="{DynamicResource MyColor}" />
    </Style>
```

**Comment by StephaneDelcroix** [comment]
@VladislavAntonyuk, yes, we believe the latter is more semantically correct, and it's also cheaper to trigger when the theme changes
