### ISSUE TITLE
[Enhancement] iOS: ListView Context Menu!

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#10964]
## Summary
Since SwipeView came out shouldn't ContextMenu be different than that? and be more like the Native one?
also with [this](https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/) the UX of all platforms can be like each other (like Android and UWP with holding on the items menu shows up),
plus the current context menu Ui on ios is kinda limited to the width of list and doesn't support icons.

## API Changes
even in the apple docs this is the real context menu 👇
https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

## ScreenShot
Before:
![OldContextMenu](https://user-images.githubusercontent.com/42671084/83852305-d5758280-a728-11ea-903a-4e04e11c751b.jpg)

After:
![NewContextMenu](https://user-images.githubusercontent.com/42671084/83852321-dad2cd00-a728-11ea-9395-cc1e445ea0ad.jpg)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
