### ISSUE TITLE
[ENHANCEMENT] Allow specifying a custom HttpClient to be used by Xamarin.Forms

### ISSUE THREAD

**Issue by ahmedalejo** [xamarin/Xamarin.Forms#10972]
On Android AndroidPlatformServices used for loading streams from Uris uses a HttpClient which a new instance is created for every time resource needed.

Allowing to specify a custom HttpClient would enable numerous benefits:
- Security: 
  - Alowing custom ssl certificate validation for media resources(which should be within the scope of Xamarin.Forms)
  - Alowing proxy configurationon
  - With a DelegatingHandler monitor every traffic from your application
  - Alowing proxy configuration
  - Authenticated access to remote resources for gif, video or any other media asset that is support,
- Perfomance: 
  - Would allow caching of resource via a DelegatingHandler  and using a custo
  - Url re-writes to local cdn for remote assets during development.

The list goes on, just think of the benefits of a DelegatingHandler and you can add it to the list.

This isn´t specific to Android and should be considered as a whole.
## Reference
https://github.com/xamarin/Xamarin.Forms/blob/5062f533715e629eb572e5ed8a03388ed05a1d47/Xamarin.Forms.Platform.Android/Forms.cs#L617
https://github.com/xamarin/Xamarin.Forms/blob/5062f533715e629eb572e5ed8a03388ed05a1d47/Xamarin.Forms.Platform.Android/Forms.cs#L817-L827

**obs:** created a request for maui https://github.com/dotnet/maui/issues/142

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
