### ISSUE TITLE
[Enhancement] SwipeView add SwipeRequested event

### ISSUE THREAD

**Issue by koddek** [xamarin/Xamarin.Forms#10988]
Add the ability to do something before SwipeStarted is triggered. It would make something like this possible:
```cs
void OnSwipeRequested(sender, args)
{
    if(somecondition) // for some reason I can't swipe a certain direction
        SwipeView.IsEnabled = false; // disable (don't open) the swipe view because I swiped that direction
    else
        SwipeView.IsEnabled = true; // enable (open)  the swipe view if I can swipe that direction
}
```
This is especially useful when swipe mode is set to Execute.
p.s. I noticed that the API has an OpenRequested event but for some reason, it does not work.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
