### ISSUE TITLE
[Bug] GooglePlay WebView local page is miss

### ISSUE THREAD

**Issue by samchenws** [xamarin/Xamarin.Forms#10983]
### Description
My android app can open local HTML, but when it is published to Google Play, no file can be found.
### Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/37535153/84002233-b120dc80-a99a-11ea-808a-981d52b1c835.png)

2. 
![image](https://user-images.githubusercontent.com/37535153/84002315-d0b80500-a99a-11ea-9c06-e0d3e0cc9a52.png)

3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
@samchenws Are you storing the HTML file as an embedded resource?

**Comment by samchenws** [comment]
There is a problem with the Xamarin demo. file:/// It's wrong.
