### ISSUE TITLE
[Spec, WIP]  AutomationProperties AccessibilityLeafFlags

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#10986]
# AutomationProperties Grouping and Behavior

The API's discussed here are currently just a spike of behavior that we want. These should all be reconciled against the AutomationProperties that are part of UWP and we should reuse naming/behavior from there wherever we can

## AccessibilityLeafHint
With accessibility you need the ability to have more control over the grouping behavior of AccessibilityBranches

For example given the following layout

```XAML
<StackLayout 
     AutomationProperties.HelpText="Read Me" 
     AutomationProperties.AccessibilityLeafHint="RemoveChildren" >
     <Label Text="internal text" />
     <Image x:Name="childImage" />
</StackLayout>
```

The app developer will want to provide a single help text to be read on the StackLayout and for the rest of the inner elements not to participate in the accessibility process

```C#
public enum AccessibilityLeafHint
{
     Default, // act normal
     Remove, // remove this node and all of the children
     RemoveChildren, //keep this node but remove children
     Keep, // if this is being removed by a parent hint then add this node (without children) back onto the tree
     KeepWithChildren // if this is being removed by a parent hint then add this node and all my children back in
}
```

# API

```C#
public class AutomationProperties
{
       public AccessibilityLeafHint AccessibilityLeafHint //Attached Property
}
```

## Accessibility Interaction 

Provide the ability to indicate what will trigger an element 

# API

```C#

[Flags]
public enum AccessibilityInteraction
{
     Default,
     SingleTap,
     LongPress
}
```

```C#
public class AutomationProperties
{
       public AccessibilityInteraction AccessibilityInteraction  //Attached Property
}
```

## Accessibility Checkability

This will cause an element to act like a switch or a checkbox with regards to accessibility. 

```C#
public class AutomationProperties
{
       public bool AccessibilityIsChecked  //Attached Property
       public bool AccessibilityIsCheckable //Attached Property
}
```

# Scenarios

// TODO

## XAML Example
```XAML
<StackLayout 
     AutomationProperties.HelpText="Read Me" 
     AutomationProperties.AccessibilityLeafHint="RemoveChildren" >
     <Label Text="internal text" />
     <Image x:Name="childImage" AutomationProperties.AccessibilityLeafHint="RemoveChildren"   />
</StackLayout>
```

# Difficulty : high

**Comment by jfversluis** [comment]
Enhancement that won't be happening for Forms anymore and hopefully we caught this in the Toolkit and/or .NET MAUI? @rachelkang tag for awareness? Thanks!
