### ISSUE TITLE
[Enhancement] Double Flyover in Shell

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#10991]
## Summary
Some applications like grinder have the ability to use two flyovers for their menu system this would be a great addition to shell. Its not really RTL support as its two flyovers in the same app shell. But only one of the flyovers can be open at the one time.

By flyover I mean the ability to swipe to the left and the right side of menus an example of this can be seen in the screen shot below only used for reference please deleted if not allowed.

The user can either swipe to the left or right to open the menu flyovers or else click a custom icon such as settings or profile image

Left Menu

 
![image0](https://user-images.githubusercontent.com/5619229/84140266-3ebb0580-aa49-11ea-88ab-0db152e00281.png) ( Left Flyover)
![image1](https://user-images.githubusercontent.com/5619229/84140269-3fec3280-aa49-11ea-823f-7394f4b114a3.png) (Right Flyover)

As you can see the left side is the full size of the layout and the right side is as well thus it actually moves the app bar

## API Changes
I would imagine from the development end point this could be as simple as having a Position attribute in the flyout to control it 

e.g.

public Enum FlyoutPosition
Left =0,
Right =1,
Both =2,

When Both is selected the xaml mark up could have to xaml elements for example
I imagine that we have an element as such 

     // This header appears at the top of the Flyout.
     <Shell.FlyoutHeaderTemplate x:HeaderDirection=FlyoutPosition.Left>
        <DataTemplate>
            <Grid>ContentHere</Grid>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>

    // ItemTemplate is for ShellItems as displayed in a Flyout
    <Shell.ItemTemplate>
        <DataTemplate>
            <ContentView>
                Bindable Properties: Title, Icon
            </ContentView>
        </DataTemplate>
    </Shell.ItemTemplate>

    // MenuItemTemplate is for MenuItems as displayed in a Flyout
    <Shell.MenuItemTemplate>
        <DataTemplate>
            <ContentView>
                Bindable Properties: Text, Icon
            </ContentView>
        </DataTemplate>
    </Shell.MenuItemTemplate>

Right Menu

    <Shell.FlyoutHeaderTemplate x:HeaderDirection=FlyoutPosition.Right>
        <DataTemplate>
            <Grid>ContentHere</Grid>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>

    // ItemTemplate is for ShellItems as displayed in a Flyout
    <Shell.ItemTemplate>
        <DataTemplate>
            <ContentView>
                Bindable Properties: Title, Icon
            </ContentView>
        </DataTemplate>
    </Shell.ItemTemplate>

    // MenuItemTemplate is for MenuItems as displayed in a Flyout
    <Shell.MenuItemTemplate>
        <DataTemplate>
            <ContentView>
                Bindable Properties: Text, Icon
            </ContentView>
        </DataTemplate>
    </Shell.MenuItemTemplate>

**Comment by PureWeen** [comment]
Hey @davidbuckleyni really like where you're going with this!

We're in the midst of getting some releases out so haven't had  time to digest your questions here or on date picker but just wanted to let you know it's on my radar


I have a PR here for some shell improvements that line up a little bit with what you have here

https://github.com/xamarin/Xamarin.Forms/issues/10804

**Comment by davidbuckleyni** [comment]
Hey @PureWeen that's great I just thought it would be good idea its used in plenty of apps like Uber Eats, I no you guys where extremely busy cause of Build etc. Just think a double flyover would be cool to show the power of xamrain off.

**Comment by davidbuckleyni** [comment]
@PureWeen  and yes I seen that PR before makes totally since the layout of shell can be extremely confusing.

**Comment by Jakar510** [comment]
+1

**Comment by AmerBakeer** [comment]
+1
This will be great

**Comment by oscarjaergren** [comment]
1+ This is great

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by davidbuckleyni** [comment]
https://github.com/dotnet/maui/issues/9674 This is the new feature request on the maui repo get votting peeps @jfversluis
