### ISSUE TITLE
[Bug] Carousel sticks with one image and refuses to load others

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#10994]
### Description
So I have carousel of carousels. It is hard to explain, feel free to try the attached solution directly it will show you what I want to explain as it is automated.

for this description I will use pseudo algorithm lang:

let Images a collection of urls
let Items is a collection of Images
let X a carousel for Items
let Yi a carousel for (Items[i].Images) where Yi swipe is turned off
let X at item 0 => display Y0 which is showing Items[0].Image[0]
press button to scroll Y0 programatically (setting Y0.Position)
button => Y0 hows Items[0].Image[1];
button => Y0 shows Items[0].Image[2];

swipe X until Item 10 => display Y10 which shows Items[10].Image[0];
swipe X back to item 0 => display Y0 which shows Item[0].Image[2];

button => Y0 stick with the last image it was showing, and even though the carousel can see the image url is different which means it is scrolling, but the image is not loaded.

### Steps to Reproduce
* Run the solution it is semi automated
* You need to use your eye, the solution doesn't know when the error is generated and will keep looping
* it might not happen at first try, try different values and different delay values, also try stop and start again
* It is not about first item only, it could be any item
* I only tested on Android

### Expected Behavior
When we go back to first item we must see different as the carousel scrolls.
So when the app shows Item[0].Image[0] the background image must different from it when showing Item[0].Image[1]

### Actual Behavior
The carousel of the first item sticks with one image and refuses to load others
So all images: Item[0].Image[0] and Item[0].Image[1] and Item[0].Image[2] .. etc show same background

### Basic Information
XF 4.6.0.847
Android 9 and 10, Pixel Eimulator and Samsung Device

[CarouselOfCarousels.zip](https://github.com/xamarin/Xamarin.Forms/files/4752788/CarouselOfCarousels.zip)

**Comment by rmarinho** [comment]
Seems the second  or third time you change Item[0].Images[2] it works

**Comment by rmarinho** [comment]
This is fixed on 5.0.0-pre3
