### ISSUE TITLE
[Enhancement] Make method "Clone" in Xamarin.Forms.BindingBase public.

### ISSUE THREAD

**Issue by Pentadome** [xamarin/Xamarin.Forms#10990]
## Summary
A binding can only be used once. Therefore, you sometimes need to clone a binding yourself. You can literally copy and paste the source code of the Binding.Clone method and make it an extension method and it will work fine. Personally I don't see why this can't be a public method.

## API Changes

From
``` C#
internal abstract BindingBase Clone();
```
To
``` C#
public abstract BindingBase Clone();
```

## Intended Use Case
Set bindings which have already been defined before.

**Comment by McBrideMusings** [comment]
I'd like this too, as best as I can tell I can't make more complex MarkupExtensions because I can't override Clone() and mimic the way AppThemeBinding works. I've tried to make an OnOrientation binding that works the same way but I'm stuck at this point.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
