### ISSUE TITLE
[INFO] Can't find IsVisible to ShellItem

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#11005]
Hi,
I was waiting for the release of the property in question.
Today I saw that it was released in version 4.5.0.
I updated my project to the latest version (4.6.0.847) but the IsVisible property is not yet present.

The request can be found at this address and has been closed and therefore implemented.
https://github.com/xamarin/Xamarin.Forms/pull/7847

Can anyone give me any explanations about it?

Thank you.

**Comment by hartez** [comment]
PR #7847 was _closed_, but not _merged_. So this feature has not yet been implemented. You'll want to keep an eye on #10980. 

Sorry for the confusion.
