### ISSUE TITLE
[Enhancement] RigthClickGestureRecognizer 

### ISSUE THREAD

**Issue by jvakos** [xamarin/Xamarin.Forms#11003]
## Summary
Having TapGestureRecognizer in UWP & macOS is not enough. On these platforms we can use a mouse that has (at least 2 buttons) so a rigth click for these platforms is a must.

## API Changes
A new gesture recognizer (like TapGestureRecognizer) e.g RigthClickGestureRecognizer with a Command and a CommandParameter
`
<RigthClickGestureRecognizer Command="" CommandParameter="" />
`
## Intended Use Case

- Show a popup on user rigth click (most common)
-Copy a text on rigth click

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
