### ISSUE TITLE
[Enhancement] allow to use custom Picker Popup logic

### ISSUE THREAD

**Issue by makeman-p81** [xamarin/Xamarin.Forms#11007]
## Summary
I work under a Xamarin Forms based app with enhanced Picker Popup.
But forced to use the slightly customized and recompiled library because I don't find another ways to achieve desirable behavior.
You may see modified Picker Popups on screenshots or even download the app to check how it works
https://play.google.com/store/apps/details?id=xyz.makeloft.timely

## API Changes
The main idea of the improvement to add Handleably Click event into Picker class and event args with Handled property flag. So, then we may use Picker as

```
<Picker Click="OnPickerClick" />
```

```cs
void OnPickerClick(object sender, ClickEventArgs args)
{
    args.Handled = true; // don't show Native Picker Popup
    // may show Custom Popup and do another logic with selections
}
```
It will be very nice to add similar possibility into the library.
Now for me it is a valuable reason to use customized builds.

Moreover it is very simple to implement into PickerRenderers
```cs
		void IPickerRenderer.OnClick()
		{
			Picker model = Element;

			if (model.IsClickHandledByUser())
				return;
```
```cs
	//public class View : VisualElement, IViewController, IGestureController
        public class Picker : View
	{
		public event EventHandler<ClickEventArgs> Click;

		public bool IsClickHandledByUser()
		{
			var args = new ClickEventArgs(this);
			Click?.Invoke(this, args);
			return args.Handled;
		}
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
