### ISSUE TITLE
[Enhancement] RadioButton ControlTemplate?

### ISSUE THREAD

**Issue by LegendaryB** [xamarin/Xamarin.Forms#11013]
## Summary
In my current project we need radio button functionality but don't want to use the default style / template. Currently there is no possibility to set for example a ControlTemplate or similiar.

## Intended Use Case
Changing the template of the radio button while maintaining its core functionality

**Comment by jfversluis** [comment]
I think this is already implemented for `RadioButton`? Closing this one!
