### ISSUE TITLE
[Enhancement] Make Xamarin.Forms.Device.SetFlags Browsable

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#11038]
## Summary
Currently, the documentation says you need to set flags in each platform. This is tedious as I need all the features in all my apps. You can use SetFlags as part of Device, but it isn't browsable :(
[EditorBrowsable (EditorBrowsableState.Never)]

## API Changes

Remove this flag :)

## Intended Use Case
Make it easier to set flags.

**Comment by PureWeen** [comment]
We should also make all the platform specific ones just call into this method

Right now ios and android work differently with settings flags... It's confusing

**Comment by jfversluis** [comment]
I think this was addressed already at some point to not need all the platform specific ones? And the usefulness of this isn't that much anymore at this point in time I guess.
