### ISSUE TITLE
[Bug] Regression in 4.7-pre4: Frames are broken

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11031]
### Description

Xamarin.Forms 4.7-pre4 breaks frames by removing clipping from them, making the background color bleed to fill the control's dimensions. Frames do work in 4.7-pre3. Edit: This happens on iOS only.

Pre-3:
<img width="181" alt="Pre-3" src="https://user-images.githubusercontent.com/60286968/84521841-48a96680-acde-11ea-8bac-9702ed21022d.png">

Pre-4:
<img width="176" alt="Pre-4" src="https://user-images.githubusercontent.com/60286968/84521853-4fd07480-acde-11ea-960e-91302434f195.png">

### Steps to Reproduce

The following snippet will work in pre-3 but not in pre-4.
```xaml
                <Frame BackgroundColor="Red" BorderColor="Blue" CornerRadius="20">
                    <Label HorizontalTextAlignment="Center" Text="HELLO" />
                </Frame>
```

Adding IsClippedToBounds="True" makes no difference.

- Version with issue: 4.7.0.937-pre4
- Last known good version: 4.7.0.848-pre3
- IDE: VS For Mac 8.7 Preview, build 1077

**Comment by hartez** [comment]
@Tommigun1980 Which platform are you seeing this on?

**Comment by Tommigun1980** [comment]
> @Tommigun1980 Which platform are you seeing this on?

Sorry for forgetting to mention this -- this happens on iOS. I have tested iOS and Android, where the latter is fine.

**Comment by jsuarezruiz** [comment]
@hartez Is happening on iOS. 
@Tommigun1980 It is not related to Shapes/Path/Clip, I just sent the fix here https://github.com/xamarin/Xamarin.Forms/pull/11032https://github.com/xamarin/Xamarin.Forms/pull/11032. We have tests that should detect if there are problems with CornerRadius, colors, etc. in this case. We are reviewing what has happened this time to avoid it in the future.

**Comment by Tommigun1980** [comment]
> @hartez Is happening on iOS.
> @Tommigun1980 It is not related to Shapes/Path/Clip, I just sent the fix here #11032. We have tests that should detect if there are problems with CornerRadius, colors, etc. in this case. We are reviewing what has happened this time to avoid it in the future.

Thank you for the very rapid fix and the explanation. I was worried that such a big feature could have broken this but I was in the wrong, sorry for that. I am really looking forward to using the new shapes API once this issue is fixed!

**Comment by jsuarezruiz** [comment]
Thanks to you for reporting the issue.

**Comment by Tommigun1980** [comment]
Thanks for fixing this. Just wanted to bring to your attention that I think there's still an error in the test at https://github.com/xamarin/Xamarin.Forms/commit/b54d3768b5e6988d6861e1dc8da6f1c3be1da7c2#r39898750.

Thanks.
