### ISSUE TITLE
[Enhancement] Shapes/Paths need CSS support

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#11034]
## Summary

Need to be able to style Shapes with CSS!

## API Changes

none; just add the css attributes!

## Intended Use Case

glorious designs

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
