### ISSUE TITLE
Xamarin Project with grial theme , dos it coz permission issue when internal sharing on Play store ? 

### ISSUE THREAD

**Issue by ShamineDsouza** [xamarin/Xamarin.Forms#11049]
Hi ,

I have implemented grial in my project and have almost completed development .
However , we need to do internal testing before proceeding . However I have been getting permission issue when trying the internal sharing uploading of google play store

Description
I am trying to load the .apk in the internal sharing link provided by google play store for organizational testing .

Can I do internal sharing on google playstore with grial in development mode ?

Basic Information
Xamarin

Screenshots
![image](https://user-images.githubusercontent.com/25946929/84641499-c4d0c380-af03-11ea-90dc-fc0a1aa05d26.png)

**Comment by StephaneDelcroix** [comment]
@ShamineDsouza you should reach out to the Grial guys, there's very little we can do at this time.
