### ISSUE TITLE
[Enhancement] Font properties on SwipeItem

### ISSUE THREAD

**Issue by Inrego** [xamarin/Xamarin.Forms#11041]
## Summary
Please allow customization of the font on SwipeItem. On one hand, Xamarin Forms is trying to be friendly to custom font users, but on the other hand, many of the default elements in Xamarin Forms do not allow changing the font (looking at you, NavigationPage toolbar and TabbedPage). Please don't introduce new elements with text, where we can't change the font.

Alternatively, being able to use our own views/data-templates in the SwipeItems would be really cool. That way, we could also use SVG icons etc.

## API Changes

`<SwipeItem FontFamily="MyCoolCustomFont" TextColor="{DynamicResource PrettyCustomColor}" />`

## Intended Use Case
To keep the proper look and feel of an app. When generally using a custom font in an app, it looks like amateur hour when another font suddenly shows up in.

**Comment by Inrego** [comment]
I'm not sure since I didn't test it. But if there's a mask on the icon, like on tabbed bar, maybe we'd like to be able to specify mask color, or remove the mask altogether.

**Comment by darrabam** [comment]
imo, SwipeItem as it is lakes so many customizations ... but luckily we have SwipeItemView which provides all the flexibility and customization that you can think of.

**Comment by Inrego** [comment]
> but luckily we have SwipeItemView which provides all the flexibility and customization that you can think of.  

I missed that! Maybe I can still use it then.

**Comment by BillyMartin1964** [comment]
I'm using FontIcons and can't change the size or color of them in the SwipeView. All I've been able to change is the BackgroundColor

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
