### ISSUE TITLE
[Bug] Xamarin.Forms Nuget Packages

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#11054]
Hi,
the latest SR packages from here: https://github.com/xamarin/Xamarin.Forms/releases
are not listed on nuget (https://www.nuget.org/packages/Xamarin.Forms). Is there a problem with nuget upload?

**Comment by samhouts** [comment]
4.6.0.847 is the latest service release package, and it is available on [NuGet](https://www.nuget.org/packages/Xamarin.Forms/4.6.0.847). Thanks!
