### ISSUE TITLE
[Enhancement] VisibleViews property for CollectionView

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#11057]
## Summary
It would be nice to have the VisibleViews property on CollectionView, like on CarouselView.

It's interesting to have it when you have to load data specifically to visible items only, or update visible items informations in real times.

## API Changes

VisibleViews property is an ObservableCollection that contains the currently displayed templated views
````
public static readonly BindableProperty VisibleViewsProperty = VisibleViewsPropertyKey.BindableProperty;

public ObservableCollection<View> VisibleViews => (ObservableCollection<View>)GetValue(VisibleViewsProperty);
````

## Implementation

The CarouselView implementation of VisibleViews is a good example.

Forms Part => [CarouselView.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Items/CarouselView.cs)

Droid Part => [CarouselViewRenderer.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs)

iOS Part => [CarouselViewController.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewController.cs)

Let me know, if you interesting?

Regards,

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
