### ISSUE TITLE
[Bug][Android] Shapes: Moving spiral demo doesn't animate on Android 

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11052]
### Description

Shapes is fantastic, and in great shape for an experimental feature. However, I have a spiral drawing that should animate. It works fine on iOS and UWP, but it doesn't animate on UWP. I've already made @jsuarezruiz aware of this.

### Steps to Reproduce

1. Run attached the sample.
2. Browse to the Moving spiral demo page.

### Expected Behavior

Spiral draws and animates on Android.

### Actual Behavior

Spiral draws but doesn't animate on Android.

### Basic Information

- Version with issue: 4.7-pre4
- IDE: VSMac 8.6.3
- Platform Target Frameworks:
  - Android: API 28
### Screenshots

I'm not bothering to create an animated GIF, as I know that @jsuarezruiz has already fixed this.

### Reproduction Link

[ShapesDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4779283/ShapesDemos.zip)

**Comment by jsuarezruiz** [comment]
Nice sample. The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/11046

![animate-shape](https://user-images.githubusercontent.com/6755973/84642840-56890280-aefd-11ea-8fda-1b5db5cb2fc4.gif)

**Comment by samhouts** [comment]
closed by #11046
