### ISSUE TITLE
[Bug] RemainingItemsThresholdReachedCommand

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#11060]
### Description

RemainingItemsThresholdReachedCommand is executed at startup when CollectionView has header and footer without scrolling.

```
 <CollectionView ItemsSource="{Binding Items}"
                            SelectionMode="Single"
                            SelectedItem="{Binding SelectedItem, Mode=TwoWay}"
                            ItemSizingStrategy="MeasureFirstItem"
                            RemainingItemsThreshold="{Binding ItemsThreshold}"
                            RemainingItemsThresholdReachedCommand="{Binding 
 LoadMoreItemsThresholdCommand}"
                            VerticalScrollBarVisibility="Never">

                <CollectionView.Header>
                   <Label Text="Header" />
                </CollectionView.Header>

                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Label Text="{Binding Text}" />
                    </DataTemplate>
                </CollectionView.ItemTemplate>

                  <CollectionView.Footer>
                       <Label Text="Footer" />
                </CollectionView.Footer>

            </CollectionView>
```

### Expected Behavior

RemainingItemsThresholdReachedCommand should only be called when RemainingItemsThreshold is reached

### Actual Behavior

RemainingItemsThresholdReachedCommand is executed at startup when CollectionView has header and footer without scrolling.

### Basic Information

- Version with issue: 4.7
- IDE: Visual Studio 2019 16.6.2
- Platform Target Frameworks:
  - Android: 9
- Affected Devices: Xiaomi Mi6
-iOS: not tested

**Comment by angelru** [comment]
Any updates????

**Comment by angelru** [comment]
any updates? It is critical in my application

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by angelru** [comment]
Sorry, I realized it's not this

**Comment by angelru** [comment]
@samhouts 
[Example.zip](https://github.com/xamarin/Xamarin.Forms/files/4843040/Example.zip)

**Comment by angelru** [comment]
I have verified that it also happens to me with this library without header [CloudFirestore](https://github.com/f-miyu/Plugin.CloudFirestore)

**Comment by angelru** [comment]
I have found that if for example RemainingItemsThreshold has a value of 5 and I get 7 items it also runs, shouldn't it run when I scroll and item 5 is visible?

**Comment by angelru** [comment]
any updates?

**Comment by angelru** [comment]
any updates??

**Comment by 851265601** [comment]
+1

**Comment by angelru** [comment]
Here post again
https://docs.microsoft.com/en-us/answers/questions/209921/collectionview-and-remainingitemsthresholdreachedc.html

**Comment by unamed000** [comment]
Any updates? I'm having the same issue
