### ISSUE TITLE
[Bug] CharacterSpacing with ContentLayout doesn't respect ContentLayout spacing.

### ISSUE THREAD

**Issue by sshere** [xamarin/Xamarin.Forms#11066]
### Steps to Reproduce

1. Create a button in your Xaml: `<Button` CharacterSpacing="1" ImageSource="ImageFilePath" ContentLayout="Left,10">` and be sure to replace the _ImageFilePath_ with a local image.

### Expected Behavior

- The text should expand and the character spacing should be respectful of the defined spacing.
- The image should have a spacing of 10 between the image and the text. 

### Actual Behavior
- The text does expand and the character spacing is respectful of the defined spacing.
- The image loses the spacing between the image and the text.

### Basic Information
- Adding more spacing to the second parameter of ContentLayout does not make a difference.
- We have tracked down the problem to the CharacterSpacing property, and removing the property will show the correct spacing.

- Version with issue: 4.6.0.800+474-sha.e9e985cb8-azdo.3734898
- Last known good version: Unknown
- IDE: Microsoft Visual Studio Enterprise 2019
- Platform Target Frameworks: 
  - iOS:  13.5
  - Android: Not Tested 
  - UWP:  Not Tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone 11 Pro Max Simulator

### Screenshots

https://kutt.it/rEZkhS
https://kutt.it/MFaQgc
https://kutt.it/dKFoOq

### Reproduction Link
None.

### Workaround
None

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sshere** [comment]
git@github.com:exquisitesoftware/Xamarin.Forms.Issue.11066.11077.git

**Comment by rmarinho** [comment]
Duplicate #11067
