### ISSUE TITLE
[Bug] SKCanvas images not rendering correctly in CollectionView

### ISSUE THREAD

**Issue by Stuart88** [xamarin/Xamarin.Forms#11064]
### Description

SKCanvas objects render incorrectly in the last couple of cells of a larger `CollectionView`

The images are LaTex equations created via the [CSharpMath Latex](https://github.com/verybadcat/CSharpMath#3-csharpmathforms) library, which utilises SkiaSharp to turn LaTex equation string into an `SKCanvasView` object. 

So `SKCanvasView` is what the CollectionView is having problems with, I believe.

If I use a `ListView` instead, the issue does not occur.

### Steps to Reproduce

1.  Bind `CollectionView` to large list of items where one of the bindings is to an `SKCanvasView`  (or more specifically a `MathView` from the `CSharpMath.Forms` library)
2. View page containing the list of items
3. Scroll to end of list

### Expected Behavior

Items rendered correctly

### Actual Behavior

Last item(s) of list show repeat of first item(s)

### Information

- Version with issue: 4.6.0.847 (latest)
- Last known good version: Unknown
- IDE: VS2019
- Platform Target Frameworks: Net Standard 2.0
  - Android:  9.0
- Nuget Packages: CSharpMath.Forms  0.4.2

### Screenshots

![image](https://user-images.githubusercontent.com/23031872/84693606-ab4d6d00-af3f-11ea-9a63-1cf756fbc9b1.png)

![image](https://user-images.githubusercontent.com/23031872/84693720-d768ee00-af3f-11ea-9564-162237a311f1.png)

![image](https://user-images.githubusercontent.com/23031872/84695404-afc75500-af42-11ea-93df-67d66c010d6f.png)

### Reproduction Link

The following branch can be built to see the issue in action 

https://github.com/Stuart88/pure-physicist/tree/wip/collection-view-problem

To locate the issue in the app (Android), navigate to:
Menu -> Topics -> Classical Mechanics -> Equations

Relevant files:

XAML page containing the `CollectionView`
https://github.com/Stuart88/pure-physicist/blob/wip/collection-view-problem/PurePhysicist/PurePhysicist/Views/Topics/EquationsViewBase.xaml

Code-behind 
https://github.com/Stuart88/pure-physicist/blob/wip/collection-view-problem/PurePhysicist/PurePhysicist/Views/Topics/EquationsViewBase.xaml.cs

### Workaround

Currently using ListView instead

**Comment by samhouts** [comment]
First, nice app! 

Second, I strongly suspect you're hitting the same problem that is described here: https://github.com/xamarin/Xamarin.Forms/issues/9200#issuecomment-643822589

ListView is not as good as CollectionView is at virtualization. That's good because your app will be much more responsive. The tradeoff is that you need to be explicit about the bindings for complex templates.
