### ISSUE TITLE
[Bug] Visual Studio version >=16.5.x breaks Nuget packages

### ISSUE THREAD

**Issue by devcssbet** [xamarin/Xamarin.Forms#11073]
### Description
E.g. if I use a custom renderer it’s not being called/triggerered at all - only when the nuget is unpackaged and integrated within the project, under local namespace which kind of kills the main purpose of the nuget system. All in all the project becomes incomplete without the underlying packages compiled along its side.

### Steps to Reproduce

1. Open the project attached
2. Apply the nuget Tk.CustomMap if necessary (reinstall it)
3. Put a breakpoint on the customrenderer's class constructor

### Expected Behavior
Constructor is being hit as is the rest of the class

### Actual Behavior
Constructor is not being hit thereby making the class invisible/uncompiled within the  project

### Basic Information

- Version with issue: all of them after 16.4.x including 16.5.x and 16.6.x
- Last known good version:  16.4.10
[CustomMapRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/4786207/CustomMapRenderer.zip)

- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: 9 Pie, 10 Q 
- Android Support Library Version: 
- Nuget Packages: TK.CustomMap, Xamarin.Forms.GoogleMaps

### Workaround
Reverting to Visual Studio 16.4.x versions of IDE

**Comment by samhouts** [comment]
1. Change your `CustomMap` to inherit from `TKCustomMap`.
2. Reference your `CustomMap` from your xaml instead of the `TKCustomMap`
3. Change your `Export` attribute to target `CustomMap` instead of `TKCustomMap`.

When it comes to renderer registration, the last registration wins. In this case, TKCustomMap's Init method is registering its renderer last, so any instance of TKCustomMap is going to get its TKCustomMapRenderer. The above changes will make the `CustomMap` registration more specific so it can override it.

I don't know why it would have worked before; perhaps a race condition? Fluke? In any case, this should resolve your problem.

Thanks!

**Comment by devcssbet** [comment]
> 
> 
>     1. Change your `CustomMap` to inherit from `TKCustomMap`.
> 
>     2. Reference your `CustomMap` from your xaml instead of the `TKCustomMap`
> 
>     3. Change your `Export` attribute to target `CustomMap` instead of `TKCustomMap`.
> 
> 
> When it comes to renderer registration, the last registration wins. In this case, TKCustomMap's Init method is registering its renderer last, so any instance of TKCustomMap is going to get its TKCustomMapRenderer. The above changes will make the `CustomMap` registration more specific so it can override it.
> 
> I don't know why it would have worked before; perhaps a race condition? Fluke? In any case, this should resolve your problem.
> 
> Thanks!

In which version have you tested the above ?

**Comment by samhouts** [comment]
[CustomMapRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/4948895/CustomMapRenderer.zip)
Version 16.6.1

The exception in the custom renderer's constructor should throw if it worked, just in case you didn't set your breakpoint.

**Comment by devcssbet** [comment]
Hey Sam,

It's not just about loading the ctor in regards to the problem. You may get it to work when we change for the indirect type (CustomMap)
but nuget does not load then, no matter the inheritance.

Renderer handler type must be of the type TKCustomMap otherwise it throws an exception System.ArgumentException(element is not of the type TK etc.) so no nuget - no forwards : ( .

Version 16.4.11 (latest baseline 16.4.x) still loads the base type thus app perfectly fine, ctor is being hit and renderer does its work as expected.

What is your opinion ?

________________________________
