### ISSUE TITLE
[Bug] [Android] Entry MaterialEntryRenderer BoxBackgroundMode not working

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#11082]
### Description

I am trying to create custom renderer from the material renderer of Entry, trying to remove the terribly designed underline. So anything you could imagine or find online, from setting background to null to pain background drawable, .. etc .. all is not going to work. 

The only thing that has effect is `SetBoxBackgroundMode` but it is not working properly

### Steps to Reproduce
```csharp
public class CustomEntryRenderer : MaterialEntryRenderer
    {
        public CustomEntryRenderer(Context context) : base(context)
        {
        }
        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if(Control != null)
            {
                Control.SetBoxBackgroundMode(0);
            }
        }
    }
```

### Expected Behavior
To change entry border line

### Actual Behavior
setting it to zero, supposed to remove borders, it does nothing
setting it to 1, supposed to set the underline, it is there all the time without this setting
setting it to 2, supposed to make outlined, it outline the left, top, right sides and leaves the bottom not underlined

### Basic Information
XF 4.6.0.847
Android 9 and 10

**Comment by Mikilll94** [comment]
I also have this problem. I just want to have a **regular** entry from Material Design, NOT **filled**.

![Screenshot 2020-06-18 at 20 52 57](https://user-images.githubusercontent.com/17653648/85060656-e4871680-b1a5-11ea-9116-f247d26c7947.png)

**Comment by johnbmangold** [comment]
@Mikilll94 

if you use ```Control.SetBoxBackgroundMode(Google.Android.Material.TextField.TextInputLayout.BoxBackgroundNone);``` it'll give you the look you're going for.
