### ISSUE TITLE
[Bug] CarouselView should not animate an initial Position on Android

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#11081]
### Description

On Android, setting Position of a CarouselView in XAML, or in a page constructor in C#, causes it to be animated to that position. This does not occur on iOS.

If I'm reading the code correctly, line 305 in UpdateInitialPosition() in the Android CarouselViewRenderer.cs [Android] should change from

`Carousel.ScrollTo(_oldPosition, position: Xamarin.Forms.ScrollToPosition.Center, animate: Carousel.AnimatePositionChanges)`

`Carousel.ScrollTo(_oldPosition, position: Xamarin.Forms.ScrollToPosition.Center, animate: false)`

### Expected Behavior

CarouselView should be initialized to show the assigned position without animation.

### Actual Behavior

CarouselView cycles through all prior positions before reaching the initial position.

### Basic Information

- Version with issue: 4.6.0.967
- Last known good version: n/a
- IDE: VS 2019 16.6.2
- Platform Target Frameworks:
  - iOS: 13.0
  - Android: 9.0, 10.0
- Affected Devices: Android

### Reproduction Link

[CarouselBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4790553/CarouselBug.zip)

### Workaround

None

**Comment by smalgin** [comment]
Confirmed - still exists with latest stable. Will await resolution :)
