### ISSUE TITLE
[Enhancement] CollectionView SelectionMode.Tap

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#11093]
## Summary
Add a new `Tap` item to the `SelectionMode` enum. This would result in the CollectionView triggering the `SelectionChangedCommand` with the given value and immediately null out the Selected item _without_ triggering the `SelectionChangedCommand` a second time (ie: it would suppress the command when setting it back to null).

## API Changes
```csharp
  /// <summary>To be added.</summary>
  /// <remarks>To be added.</remarks>
  public enum SelectionMode
  {
    /// <summary>To be added.</summary>
    None,
    /// <summary>To be added.</summary>
    Single,
    /// <summary>To be added.</summary>
    Multiple,
    /// <summary>To be added.</summary>
    Tap,
  }
```

```xaml
<CollectionView SelectionMode="Tap" 
                Command="{Binding ShowDetailsCommand}" />
```

The VisualStateManager should also add a `"Pressed"` state to the ItemTemplate Content.

## Intended Use Case
A common use of a CollectionView is to `Tap` an item in order to invoke a command and immediately clear the selected item. Think about navigating to a details page of an item in the list.

The way it is now, if we use `SelectionMode.Single`, we get the desired background color effect on the CollectionView and we can navigate to the details, but upon returning to the list, the item is still selected and cannot be selected again. We would need to null out the `SelectedItem` which in turn results in the invocation of the `SelectionChangedCommand` passing in a null parameter. This is not desirable.

Our alternative is to set `SelectionMode.None`and  put a TapGestureRecognizer within the DataTemplate and use a relative source binding. This is also not desirable since we lose the platform specific selection effect (think Ripple on Android).

With one ore item on the enum, we could select an item and have it immediately cleared of it's selection. This would give us best of both worlds for the background effect being shown and the selected item being cleared.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
