### ISSUE TITLE
[Bug] App works slower after update from 4.6.0.847 to 967

### ISSUE THREAD

**Issue by RadoslawKubas** [xamarin/Xamarin.Forms#11092]
### Description
I noticed that iOS app start to work slower after this update. Same code, just Xamarin updated from 4.6.0.847 to 4.6.0.976. It is visible on old devices (like iPhone 6), especially during switching tabs in TabbedPage. It seems like pages are rendered/prepared much slower and when you want to switch very fast between 2 pages, there is a visible lag from time to time.

### Steps to Reproduce

1. Upate Xamarin to 4.6.0.976.
2. Build
3. Check on old iPhone.

### Expected Behavior

Works same fast in version 4.6.0.847.

### Actual Behavior

Works visibly slower.

### Basic Information

- Version with issue: 4.6.0.976
- Last known good version: 4.6.0.847
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  13.18

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by RadoslawKubas** [comment]
I tried to create an example but I have a problem reproducing the issue in a small project and it seems to disappear in version 4.7. I will investigate it more, if and update information, but for now I believe issue can be closed.

**Comment by samhouts** [comment]
Thank you! Let us know if the situation changes.
