### ISSUE TITLE
[Bug] UWP: PopAsync causes a crash when called from a CollectionView.SelectionChanged event

### ISSUE THREAD

**Issue by JogyBlack** [xamarin/Xamarin.Forms#11090]
### Description
In latest releases of Xamarin.Forms, calling Navigation.PopAsync() from a CollectionView.SelectionChanged handler causes a crash in UWP projects.
Same code works fine with Android.

### Steps to Reproduce

1. Create a simple Xamarin.Forms navigation application with two pages. 
2. The main page contains a button to navigate to the second page.
3. The second page contains a CollectionView with several elements, and a SelectionChanged handler. In the SelectionChanged handler call Navigation.PopAsync to return to the main page.

### Expected Behavior
The user is navigated back to the main page.

### Actual Behavior
Unhandled exception: "Object reference not set to an instance of an object."
   at Xamarin.Forms.Platform.UWP.SelectableItemsViewRenderer`1.UpdateFormsSingleSelection()
   at Xamarin.Forms.Platform.UWP.SelectableItemsViewRenderer`1.UpdateFormsSelection()
   at Xamarin.Forms.Platform.UWP.SelectableItemsViewRenderer`1.NativeSelectionChanged(Object sender, SelectionChangedEventArgs args)

### Basic Information

- Version with issue: 4.6.0.967
- Last known good version: 4.4.0.991864
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP: 16299
- Affected Devices: Windows Desktop

### Reproduction Link
Sample project to demonstrate the problem:
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4793306/App1.zip)

### Workaround

Instead of handling SelectionChanged, use a TapGestureRecognizer for the items in the CollectionView and call PopAsync() there.

**Comment by JogyBlack** [comment]
Note: still happens with the just released Xamarin.Forms 4.7.0.968

**Comment by mattleibow** [comment]
Just tried this with 4.8.0.1364 and it just happened.
