### ISSUE TITLE
AppTheme needs a manual option

### ISSUE THREAD

**Issue by xeg12** [xamarin/Xamarin.Forms#11104]
AppTheme currently just changes based on the OS theme, 

Many apps give the choice of system theme or manual light / dark theme in their settings, so the option to manually choose light or dark theme would enable this.

**Comment by davidortinau** [comment]
You can do this today by setting the UserAppTheme.

```
Application.Current.UserAppTheme = OSAppTheme.Dark;
```

https://github.com/davidortinau/Xappy/blob/master/Xappy/Xappy/Content/Settings/SettingsViewModel.cs#L24

Then to change it back to responding to OS themes you set it to `OSAppTheme.Unspecified`.

https://github.com/davidortinau/Xappy/blob/master/Xappy/Xappy/Content/Settings/SettingsViewModel.cs#L119
