### ISSUE TITLE
[Bug] Shell keeps showing menu button in navbar instead of back button in 4.7

### ISSUE THREAD

**Issue by jtorvald** [xamarin/Xamarin.Forms#11102]
### Description
My code in 4.5 and 4.6 worked fine, but now after upgrading to 4.7 the back button does not show when navigating to a page (iOS). It keeps showing the menu icon (hamburger for the flyout) on every page. 

This is probably a terrible bug report because I can't share screenshots/code and can not reproduce it in a new solution with Xamarin Forms 4.7.

Just wanted to file it and I'm hoping that someone can point me in the right direction on how to debug this. Downgrading to 4.6 makes the issue go away.

### Steps to Reproduce

I tried to create an example project but there it seems to work

### Expected Behavior

Show back on navigating to a page with Shell.Current.GoToAsync or Navigation.PushAsync

### Actual Behavior

Shows flyout menu icon

### Basic Information

- Version with issue: 4.7
- Last known good version: 4.6

**Comment by PureWeen** [comment]
@jtorvald are you using BackButtonBehavior on any of your pages?

**Comment by jtorvald** [comment]
@PureWeen yeah in two login pages but they are not 'hit' in the flow since I'm already logged in and I load a different AppShell on start for logged in users.

**Comment by PureWeen** [comment]
@jtorvald can you post your XAML file with shell?

How do you initialize Shell?
Can you post the code you are using to navigate ?

**Comment by PureWeen** [comment]
@jtorvald I'm going to mark this one fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/11264

Once that's merged if you're still seeing the issue please let me know

**Comment by jtorvald** [comment]
@PureWeen thanks. Sorry but I didn't have time to supply the requested info yet. It's also not urgent so I will await the new fix and let you know with more details in case it doesn't fix it. Thanks for you time looking into this.

**Comment by PureWeen** [comment]
@jtorvald 

Here are the nugets from this PR if you'd like to test
https://dev.azure.com/xamarin/public/_build/results?buildId=21694&view=artifacts&type=publishedArtifacts

**Comment by jtorvald** [comment]
@PureWeen I figured it out: I had FlyoutIcon="hamburger.png". I've been developing this app for a while and in the previous xamarin forms versions it was not an issue. Now apparently it is for some reason. Since I'm happy with the default icon I can just remove the attribute, but just wanted to update this issue here with the cause. Not sure if that is expected behavior or not.

**Comment by PureWeen** [comment]
@jtorvald Aw ok yea I'd say that's a bug

Thank you for checking back in!!

**Comment by gresolio** [comment]
After upgrading to 4.7.0.1179, shell back button icon disappeared in all views, which previously worked just fine with following options:
```
Shell.TabBarIsVisible="false"
Shell.FlyoutBehavior="Disabled"
```

Downgrading to 4.7.0.1142 fixes this rather unpleasant issue.

I read the Release Notes 4.7.0.1179 and found the back button is mentioned here.
Is this expected behaviour? (and we should update our project to work with the new version of Xamarin.Forms). Or is it a bug?

**Comment by PureWeen** [comment]
@gresolio that will be fixed by the next PR
