### ISSUE TITLE
[Bug] Simplified RowDefinitions and ColumnDefinitions syntax is not working

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#11105]
### Description
Simplified RowDefinitions and ColumnDefinitions syntax is not working, it fails at compile time with error:

**Object of type 'System.String' cannot be converted to type 'Xamarin.Forms.ColumnDefinition'**

### Steps to Reproduce
copy this line anywhere and that's it
```csharp
<Grid ColumnDefinitions="10*, 90*" />
```

### Expected Behavior
Code to compile and Grid to create columns and rows according to the simplified description in string.

### Actual Behavior
Compile error **Object of type 'System.String' cannot be converted to type 'Xamarin.Forms.ColumnDefinition'**

### Basic Information
XF 4.6.0.847
VS 16.6.2
### Workaround
Don't use the simplified definition

**Comment by jfversluis** [comment]
If the Xamarin.Forms version that you mention is correct then that is your problem.

This is supported from Forms 4.7 and up

**Comment by jsuarezruiz** [comment]
@MhAllan Could you update to Xamarin.Forms 4.7 and test it again?

**Comment by MhAllan** [comment]
I didn't know there was a new release, still, sorry to tell you, it is not working but with runtime error this time on XF 4.7

![Capture](https://user-images.githubusercontent.com/13087546/85037488-c54db080-b1c8-11ea-9744-d5be07ed2021.PNG)

**Comment by MhAllan** [comment]
Works fine on 4.7
