### ISSUE TITLE
[Bug] [WPF] PickerRenderer 

### ISSUE THREAD

**Issue by CometSL9** [xamarin/Xamarin.Forms#11100]
### Description
When executing a Xamarin WPF project, the new XF Version 4.7.0.968, the PickerRenderer throws an InvalidCastException:
"Unable to cast object of type 'System.Windows.Controls.Grid' to type 'System.Windows.Controls.Border'."

StackTrace:
   bei Xamarin.Forms.Platform.WPF.PickerRenderer.UpdateBackgroundColor()
   bei Xamarin.Forms.Platform.WPF.PickerRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bei System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bei System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bei MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bei System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bei System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bei System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bei System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei System.Windows.Application.Run()
   bei EFRAS.GUI.WPF.Program.Main() in C:\(deleted)\Program.cs: Line16

### Steps to Reproduce

1. Create a Xamarin.Forms project and a Xamarin.WPF project referencing it.
2. In the Main Page, include a Picker.
3. Run the WPF project.

### Expected Behavior
No Exception.

### Actual Behavior
Exception is thrown.

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: 4.6.0.967
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - WPF: 
- Nuget Packages: 4.7.0.968

**Comment by samhouts** [comment]
Probably caused by Shapes. cc @jsuarezruiz

**Comment by jsuarezruiz** [comment]
I have been testing with an example (using 4.7.0.968) and with the 4.7.0 branch but cannot reproduce the issue.
[Issue11100.zip](https://github.com/xamarin/Xamarin.Forms/files/4844509/Issue11100.zip)

![Issue11100](https://user-images.githubusercontent.com/6755973/85988546-79341480-b9ef-11ea-953d-042d51305a01.gif)

@CometSL9 Is there something missing in the example?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by domyd** [comment]
I'm getting the same exception. This happens when the WPF `ComboBox`'s `ControlTemplate` is overridden, for example when using the [MaterialDesignInXamlToolkit](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) library. The origin appears to be [this change](https://github.com/xamarin/Xamarin.Forms/commit/3265962360c191c97da084209898eed652602808#diff-56d4c61a92fc06477c7af3d35c6edbae) from #9843, which assumes that the `PART_EditableTextBox` is always surrounded by a `Border`. That's not the case with the template that comes with the MaterialDesignInXamlToolkit library, for example.

I don't think that assumption should be in the base `PickerRenderer`, or at the very least should be easily overridable (make `UpdateBackgroundColor()` virtual?). Surely there must be a better way that doesn't interfere with third party styling libraries?

For anyone that's currently running into this issue, I've implemented a _very_ dirty workaround in my custom renderer:
```cs
public class MaterialDesignPickerRenderer : PickerRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
    {
        base.OnElementChanged(e);

        // prevent the base renderer's OnControlLoaded from firing and crashing
        Control.RemoveRoutedEventHandlers(
            ComboBox.LoadedEvent,
            h => h.Handler.Method.Name == "OnControlLoaded");
        Control.Loaded += OnControlLoaded;
    }

    private void OnControlLoaded(object sender, RoutedEventArgs e)
    {
        UpdateBackgroundColor();
    }

    private void UpdateBackgroundColor()
    {
        var bgBrush = Element.BackgroundColor.ToBrush();

        if (Control.Template?.FindName("PART_Popup", Control) is ComboBoxPopup element)
        {
            element.Background = bgBrush;
        }
    }

    protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName != Picker.BackgroundColorProperty.PropertyName)
        {
            base.OnElementPropertyChanged(sender, e);
        }

        if (e.PropertyName == Picker.TitleProperty.PropertyName)
        {
            SetTitle();
        }
        else if (e.PropertyName == Picker.BackgroundColorProperty.PropertyName)
        {
            UpdateBackgroundColor();
        }
    }
}

public static class WindowsControlMixins
{
    // Removes all event handlers subscribed to the specified routed event from the specified element.
    // Adapted from https://stackoverflow.com/a/12618521/1198245.
    public static void RemoveRoutedEventHandlers(
        this UIElement element,
        RoutedEvent routedEvent,
        Func<RoutedEventHandlerInfo, bool> handlerFilter = null)
    {
        handlerFilter ??= (_ => true);

        var eventHandlersStoreProperty = typeof(UIElement).GetProperty(
            "EventHandlersStore", BindingFlags.Instance | BindingFlags.NonPublic);
        object eventHandlersStore = eventHandlersStoreProperty.GetValue(element, null);

        if (eventHandlersStore == null)
            return;

        var getRoutedEventHandlers = eventHandlersStore.GetType().GetMethod(
            "GetRoutedEventHandlers", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        var routedEventHandlers = (RoutedEventHandlerInfo[])getRoutedEventHandlers.Invoke(
            eventHandlersStore, new object[] { routedEvent });

        foreach (var routedEventHandler in routedEventHandlers.Where(handlerFilter))
            element.RemoveHandler(routedEvent, routedEventHandler.Handler);
    }
}
```
