### ISSUE TITLE
[Bug] Random crashes VisualElementTracker.UpdateClip

### ISSUE THREAD

**Issue by Codelisk** [xamarin/Xamarin.Forms#11118]
### Description
Random crashes on Ios.

Unfortunately i am not able to elaborate more on the issue.

### Steps to Reproduce

1.  Start ios version with Xamarin.Forms nighly build 4.8.0.979
2.  Change pages or press elements fast
3.  App crashes randomly with exception mentioned in the picture below

### Expected Behavior
No crashes
### Actual Behavior
Crashes
### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forms nighly build 4.8.0.908
- IDE:
- Platform Target Frameworks: 
  - iOS:  X
  - Android: 
  - UWP:  
- Android Support Library Version: Android X all latest versions except google.Material
- Nuget Packages:
- Affected Devices: Iphone XS

### Screenshots

![image](https://user-images.githubusercontent.com/51824173/85065647-d3420800-b1ad-11ea-89a6-aee01914fa17.png)

### Workaround

Use Xamarin.Forms nighly build 4.8.0.908

**Comment by stefanbogaard86** [comment]
Experiencing the same issue on iOS after updating from xamarin.forms 4.7.0.813-pre2 to 4.7.0.968

**Comment by yungtofu** [comment]
Had the same issue on iOS after updating from xamarin.forms 4.6.0.847 to 4.7.0.968

**Comment by Jacko1394** [comment]
I have this issue also, after updating Forms to 4.7.0.968

`System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.iOS.VisualElementTracker.UpdateClip () [0x00072] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementTracker.cs:413 
  at Xamarin.Forms.Platform.iOS.VisualElementTracker.UpdateNativeControl () [0x0006c] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementTracker.cs:386 
  at Xamarin.Forms.Platform.iOS.VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x001df] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementTracker.cs:115`

**Comment by rasel-tr** [comment]
VisualElementTracker.UpdateClip ()
SIGABRT: Object reference not set to an instance of an object

Stack:
VisualElementTracker.UpdateClip ()
VisualElementTracker.UpdateNativeControl ()
VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess)
BindableObject.SetValue (Xamarin.Forms.BindablePropertyKey propertyKey, System.Object value)
VisualElement.set_Width (System.Double value)
VisualElement.SetSize (System.Double width, System.Double height)
VisualElement.set_Bounds (Xamarin.Forms.Rectangle value)
VisualElement.Layout (Xamarin.Forms.Rectangle bounds)
Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region)
TemplatedView.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
SfBorder.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
Layout.UpdateChildrenLayout ()
Layout.OnSizeAllocated (System.Double width, System.Double height)
VisualElement.SizeAllocated (System.Double width, System.Double height)
VisualElement.SetSize (System.Double width, System.Double height)
VisualElement.set_Bounds (Xamarin.Forms.Rectangle value)
VisualElement.Layout (Xamarin.Forms.Rectangle bounds)
Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region)
Grid.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
Layout.UpdateChildrenLayout ()
Layout.OnSizeAllocated (System.Double width, System.Double height)
VisualElement.SizeAllocated (System.Double width, System.Double height)
Layout.ResolveLayoutChanges ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
