### ISSUE TITLE
Errors while building Xamarin.Forms app for iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11116]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1074627/errors-while-building-xamarinforms-app-for-ios.html)._

---
After upgrading from Xamarin.Forms 3.6.0 to 4.6.0 I have this issue from time to time: app doesn’t build and VS for Mac spits out these errors on the screenshot. I need to clean the bin and obj folder and restart VS, then app builds fine. I am using Xamarin.Forms 4.6.0.772, but I tried 4.6.0.847 and nothing changed

---
#### Fedoryaka Maxim on 6/11/2020, 01:01 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 6/11/2020, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
having to clean and restart the IDE when updating the NuGet is not unexpected, and even welcomed.
