### ISSUE TITLE
[Enhancement] Set the current user theme with default OS colors

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#11119]
## Summary
I thought my code was wrong, but it took me a while to figure out this **Application.UserAppTheme** property only works with setting some styles(AppThemeBinding) for controls and layouts in Xaml.

## Intended Use Case
if we could Set the current user theme with default OS colors that would be really nice and saves our time to set Dark and Light colors for all controls and layouts.

**Comment by StephaneDelcroix** [comment]
you might want to refine your proposal a bit further

**Comment by mhrastegary77** [comment]
@StephaneDelcroix Better? 👀 sorry i,m still new.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
