### ISSUE TITLE
[Bug] WebView Embedded video allowfullscreen does not work

### ISSUE THREAD

**Issue by dpuckett** [xamarin/Xamarin.Forms#11134]
### Description
When embedding a video, e.g: from YouTube, into the HtmlWebViewSource mark up for a WebView, it is not possible to view the video full screen.

### Steps to Reproduce

1. Create page with a WebView
2. Set HtmlWebViewSource similar to:
`<iframe width="560" height="315" src="https://www.youtube.com/embed/MTLp14MKDDU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

3. View in Android simulator

### Expected Behavior
WebView displays with an embedded youtube iFrame where the "Full screen" button is enabled as an option

### Actual Behavior
WebView displays with an embedded youtube iFrame where the "Full screen" button is NOT enabled as an option

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: n/a
- IDE: VS 2019

![EmbeddedYoutubeNoFullScreen](https://user-images.githubusercontent.com/5477570/85144903-b6f0aa80-b243-11ea-8100-818b2f56614e.png)

**Comment by rmarinho** [comment]
Hi this is not related with Xamarin.Forms you should check with YouTube.

https://support.google.com/youtube/answer/72689?visit_id=637291354625944944-1479388628&rd=1

> If full screen mode isn't working
> If you’re watching videos on websites other than YouTube, the option to use full screen mode may be turned off.

**Comment by ryano-xmplify** [comment]
Not a YouTube issue. I get the same behaviour with embedded vimeo.
IOS behaves as expected.

Issue with Android webview not handling the incoming fullscreen custom view.
Its been an issue for years, Forcing developers to write their own WebChromClient each time to implement OnShowCustomView and OnHideCustomView. eg...

[https://stackoverflow.com/questions/50101902/webview-and-iframe-video-full-screen-issue](https://stackoverflow.com/questions/50101902/webview-and-iframe-video-full-screen-issue)

Can something be done in Xamarin to help better support this cross platform?

**Comment by tekmun** [comment]
I am using .Net MAUI. I subclass WebChromeClient and override OnShowCustomView and OnHideCustomView. But these functions are not called at all when I clicked on YouTube fullscreen icon.
In https://stackoverflow.com/questions/50101902/webview-and-iframe-video-full-screen-issue, how do you get the linearlayout and contentlayout?
