### ISSUE TITLE
[Bug] UWP - Path object resized to zero height or width crashes ShapeRenderer

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#11137]
### Description
A path object squashed to a zero height or width will crash the application.

### Steps to Reproduce

1. Add a Path object to a xaml page, give it a nice big margin so that when you resize the app window it'll force the rendered shape to be very small
2. Launch the app and get to the page with the Path object
3. Resize the page in either horizontal or vertical directions to squash the path object width or height to be zero.

### Expected Behavior
Item is no longer visible.
### Actual Behavior
App crashes with a "Value does not fall within the expected range." argument exception in UWP ShapeRenderer, methods UpdateWidth or UpdateHeight
### Basic Information

- Version with issue: 4.7.0
- Last known good version: n/a
- IDE: VS 16.6.2
- Platform Target Frameworks: 
  - iOS: not tested
  - Android: not tested
  - UWP:  18362

**Comment by MitchBomcanhao** [comment]
If you want to make it fail instantly, just add a margin that is so big that the item fails to render without any user action.

**Comment by samhouts** [comment]
closed by #11139
