### ISSUE TITLE
[Bug] Cannot use ToolbarItems along with Flyout in a Shell

### ISSUE THREAD

**Issue by shults-s** [xamarin/Xamarin.Forms#11145]
### Description
Currently, we cannot use ```ToolbarItems``` together with ```Flyout``` in the ```Shell``` layout at the same time.

### Steps to Reproduce
1. Create ```Xamarin.Forms.Shell``` page with name ```AppShell``` and another ```ContentPage``` named ```TestPage```.
2. In the XAML file of the ```AppShell``` write:
```
<Shell.ToolbarItems>
    <ToolbarItem Priority="1" Order="Primary" Text="Item1" />
    <ToolbarItem Priority="2" Order="Primary" Text="Item2" />
    <ToolbarItem Priority="3" Order="Primary" Text="Item3" />
</Shell.ToolbarItems>
```
3. In the default ```App.xaml.cs``` write:
```
public App()
{
    InitializeComponent();

    MainPage = new AppShell()
    {
        CurrentItem = new TestPage()
    };
}
```

### Expected Behavior
![Expected Behavior](https://user-images.githubusercontent.com/7778592/85211833-a29cd280-b355-11ea-8529-92b065289511.png)

### Actual Behavior
![Actual Behavior](https://user-images.githubusercontent.com/7778592/85211844-bba58380-b355-11ea-8b61-5b42cb419868.png)

### Basic Information
- Version with issue: Xamarin 16.6.000.1061
- IDE: Microsoft Visual Studio 2019 16.6.2
- Platform Target Frameworks:
  - Android: Xamarin.Android SDK 10.3.1.4
  - iOS: Xamarin.iOS and Xamarin.Mac SDK 13.18.2.1

The [Xamarin Forums](https://forums.xamarin.com/discussion/comment/387538/#Comment_387538) says that ```ToolbarItems``` only work in a ```ContentPage```, but not in a ```Shell```. However, both Android and iOS allow this behavior to be implemented.

**Comment by rmarinho** [comment]
Duplicated of #6453
