### ISSUE TITLE
XAML Hot Reload need VisualTreeHelper.GetChildren and VisualTreeHelper.GetChild

### ISSUE THREAD

**Issue by chabiss** [xamarin/Xamarin.Forms#11144]
## Summary
XAML Hot Reload needs a *very* reliable way to get the Live Visual Tree of a running application at any given point.  WPF and UWP provides those API as part of https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchild?view=netcore-3.1

## API Changes
XAML Hot Reload need at the minimum 

- https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchild?view=netcore-3.1
- https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.visualtreehelper.getchildrencount?view=netcore-3.1

Below is an example how those API are consumed.  

```csharp
// Enumerate all the descendants of the visual object.
static public void EnumVisual(Visual myVisual)

{
    for (int i = 0; i < VisualTreeHelper.GetChildrenCount(myVisual); i++)
    {
        // Retrieve child visual at specified index value.
        Visual childVisual = (Visual)VisualTreeHelper.GetChild(myVisual, i);

        // Do processing of the child visual object.

        // Enumerate children of the child visual object.
        EnumVisual(childVisual);
    }
}
```

## Intended Use Case
This is critical for XAML Hot Reload with incremental changes to work properly.

**Comment by StephaneDelcroix** [comment]
Hey @chabiss,

When we parent children, we send (or we're suppose to (see #11143)) VTChanged events, and that should allow you to keep a live image of what's going on in, say, a ConditionalWeakTable or something.

If there's something preventing you from doing that accounting, I can track those in XF (while debugger is attached, etc, etc, ...) but would prefer not to (to avoid potential leaks in all the cases where HR is not plugged in)

**Comment by chabiss** [comment]
Hey @StephaneDelcroix, 

The more I've looked at the https://github.com/xamarin/babyshark/blob/master/Source/Xamarin.HotReload.Forms/VisualTreeService/VisualTree/FormsVisualDiagnostics.cs#L73
the more I've realized that Tim tried to get around some really nasty VisualTreeChangesEvent.  I've filed 
https://github.com/xamarin/Xamarin.Forms/issues/11334
https://github.com/xamarin/Xamarin.Forms/issues/11335
In order to keep a live image of what's going, it's important that the Events being fires are accurate.
