### ISSUE TITLE
No more VisualTreeChangeEvent for element in the page

### ISSUE THREAD

**Issue by chabiss** [xamarin/Xamarin.Forms#11143]
### Steps to Reproduce

1. Open the attached project which contains a simple ListView with a DataTemplate
[XamarinTest.-.Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/4808488/XamarinTest.-.Copy.zip)
2. Run
3. Observe the debug output where the app added a trace to the VisualTreeChangedEventArgs

### Expected Behavior
There should be VisualTreeChangeEvents for StackLayout at line 23, the Label at line 25 and the ListView at line 28
### Actual Behavior
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:MainPage.xaml;assembly=XamarinTest:14:22--> Xamarin.Forms.Label:MainPage.xaml;assembly=XamarinTest:15:26
VisualTreeChangeEventArgs Add:Xamarin.Forms.StackLayout:MainPage.xaml;assembly=XamarinTest:14:22--> Xamarin.Forms.Label:MainPage.xaml;assembly=XamarinTest:16:26
VisualTreeChangeEventArgs Add:Xamarin.Forms.ViewCell:MainPage.xaml;assembly=XamarinTest:13:18--> Xamarin.Forms.StackLayout:MainPage.xaml;assembly=XamarinTest:14:22
VisualTreeChangeEventArgs Add:Xamarin.Forms.ListView:MainPage.xaml;assembly=XamarinTest:28:10--> Xamarin.Forms.ViewCell:MainPage.xaml;assembly=XamarinTest:13:18

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: Unknown

- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
@chabiss :

```csharp
            MainPage = new MainPage();

            Xamarin.Forms.Xaml.Diagnostics.VisualDiagnostics.VisualTreeChanged += VisualDiagnostics_VisualTreeChanged;
```

The reason why you don't get elements at the page level, is because you subscribe to the event AFTER the page has been created.
