### ISSUE TITLE
[Bug] Grid ColumnDefinition type-converter doesn't work (Value cannot be null)

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/Xamarin.Forms#11148]
### Description
According to [this page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid), both of these code snippets should behave identically:

```
<Grid>
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="Auto"/>
    <ColumnDefinition Width="*"/>
    <ColumnDefinition Width="Auto"/>
  </Grid.ColumnDefinitions>
  ...
</Grid>
```

```
<Grid ColumnDefinitions="Auto,*,Auto">
  ...
</Grid>
```

### Expected Behavior
Both syntax forms behave identically

### Actual Behavior
Using `XamlCompilationOptions.Compile`, the string version gives a compile-time error, `Value cannot be null`

Using `XamlCompilationOptions.Skip`, there is no error at compile-time or runtime, but the column definitions are not applied (the code has no effect whatsoever).

Additionally, if you attempt to use the string version in an XAML `Style`, you instead get the following error at runtime _(when using `XamlCompilationOptions.Compile`)_:
`System.ArgumentException: 'Value is an invalid value for ColumnDefinitions`

Using a `Style` + `XamlCompilationOptions.Skip`, there is again no error but the column definitions are still not applied.

### Basic Information

- Version with issue: Xamarin.Forms 4.6.0.967
- Last known good version: n/a
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: Targeting 9.0
- Android Support Library Version: 28.0.0.3

### Workaround

Use the first version.  Can't use styles, so need to copy+paste everywhere 😢

**Comment by VladislavAntonyuk** [comment]
Please attach reproduction project

**Comment by jfversluis** [comment]
This feature is only available from version 4.7 and up. Your report seems to note that you’re using 4.6, if you upgrade it should work fine ;)

**Comment by BlueRaja** [comment]
Ah, I didn't realize the feature was so new. I had to downgrade since 4.7 is [literally unusable right now](https://github.com/xamarin/Xamarin.Forms/issues/11101).

As soon as 4.7 is usable, I will test and either close this or report back here.

**Comment by jfversluis** [comment]
What makes it not useable for you right now?

**Comment by BlueRaja** [comment]
@jfversluis See linked issue. It was fixed earlier today, but the fix has not been published yet.

**Comment by jfversluis** [comment]
Gotcha. I see a fix for that is already in place so should be resolved soon

**Comment by StephaneDelcroix** [comment]
closing. please reopen if the bug exists in 4.7

**Comment by BlueRaja** [comment]
Confirmed that this feature is now working in 4.7

**Comment by jfversluis** [comment]
Great! Thanks for letting us know @BlueRaja and good luck removing all that extra XAML code now! :D
