### ISSUE TITLE
[Bug]  App rejected Deprecated Api Usage UIWebview

### ISSUE THREAD

**Issue by bakhti346** [xamarin/Xamarin.Forms#11146]
### Description
The Apple store build got rejected because the Deprecated Api Usage UIWebview. I have tried every step to get rid of this issue available in the documentations or forums but the issue still persist.
### Steps to Reproduce

1. Create A new Xamarin forms project.
2. Add the mtouch arguments (--optimize=experimental-xforms-product-type --warn-on-type-ref=UIKit.UIWebView) with link sdks only behavior.
3. Try build myapp.ios

### Expected Behavior
There must be no warning.
### Actual Behavior
It shows me 2 warnings (MT1502 and MT1503)
### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: N/A
- IDE: Visualstudio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:Xamarin.Forms
- Affected Devices: N/ A

**Comment by angelru** [comment]
The same issue...

**Comment by jfversluis** [comment]
Hi there @bakhti346 and @angelru sorry for the bit of a wait and that it doesn't seem to work for you.

When you say "I have tried every step to get rid of this issue available in the documentations or forums but the issue still persist." could you be more specific on what you've tried exactly?

I feel this comment kind of sums up the current things you can try: https://github.com/xamarin/Xamarin.Forms/issues/10739#issuecomment-630049076

Especially the output of the grep command I would bee interested in and, if possible, the contents of your iOS csproj file contents. If you can't share them publicly please find my email on my GitHub profile and email them to me.

We've been able to solve each case so far, so I'm confident that the solution works, you just need to have a couple of bits in the right place. I'll be happy to help you with that!

**Comment by angelru** [comment]
Hello, @jfversluis 

everything is fixed ... with the linker in all my app is blocked, with only sdk it works fine ... although I had to add a series of permissions that my app does not need (apple warnings), the strange thing is that I have all the updated nugets and the latest version of xamarin forms.

**Comment by jfversluis** [comment]
OK Great to see everything worked out!

@bakhti346 how about yours?

**Comment by bakhti346** [comment]
@jfversluis I have shared the details from my project to you via email. Can you please point me in the right direction if I am doing something wrong? Thanks for the help in advance.

**Comment by PureWeen** [comment]
@jfversluis poke

If you're busy moving and shaking up the world let me know or forward me the email!

**Comment by jfversluis** [comment]
O gosh this is embarrassing. I've had a number of emails from different people about this same subject. I think I fixed most... 

Let's close this one. I'll be sure to follow up on all email threads. 

Thanks!
