### ISSUE TITLE
[Enhancement] <LongClickGestureRecognizer>

### ISSUE THREAD

**Issue by Informatheus** [xamarin/Xamarin.Forms#11141]
## Summary
Every day hundreds of developers spend hours trying to implement in their applications a simple functionality that is one of the most intuitive in a mobile application, but that in Xamarin is a nightmare.

## API Changes

I have in mind 2 solutions so that the developer can simply and natively implement a long click:
- The first and most obvious is **< LongClickGestureRecognizer >**, which would work in a similar way to **< TapGestureRecognizer >**.
- The second is, if the **ContextActions** has only one single **MenuItem**, there is a flag to trigger the **Command** right after the long click, without showing the only option for the user to click.

## Intended Use Case
In any situation where a long click provides some response to the user, which is not possible today without workarounds like external libs, dependency injection, etc.

**Comment by samhouts** [comment]
Duplicate of #3480
