### ISSUE TITLE
[Enhancement] Support corner radius on RectangleGeometry

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#11151]
## Summary
Support of corner radius on `RectangleGeometry` would be useful to create rounded corners.

This is already supported on [Rectangle](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/rectangle) shape.

## API Changes
Add `CornerRadius CornerRadius { get; set; }` on `RectangleGeometry`.

## Intended Use Case
Define `Clip` of `View` with rounded corners. Related to #1754

**Comment by StephaneDelcroix** [comment]
I'd prefer having CornerRadius property defined, and being able to style all 4 corners differently
