### ISSUE TITLE
[Enhancement] Allow pixel rounding configuration

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#11152]
## Summary
Allow configuration to determines whether rendering for the object and its visual subtree should use rounding behavior that aligns rendering to whole pixels. Same as [UIElement.UseLayoutRounding](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.uselayoutrounding)

## API Changes
Add `bool UseLayoutRounding` property to `VisualElement`

## Intended Use Case
Render `Pixel Perfect` visual elements. This is especially relevant for `Shapes` and `Icons`.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
