### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lwg-jmarciniak** [xamarin/Xamarin.Forms#11167]
### Description

System.IO.Path does not correctly parse file paths passed to a function using the `[CallerFilePath]` attribute when the app is compiled on Microsoft Windows and running on Android.

### Steps to Reproduce

1. create a function that takes advantage of the `System.Runtime.CompilerServices` and includes parameters for the calling function/file/line attributes.  Here is the function I am using in my code to test this issue.
```
public virtual void LogUIEvent(string evt, 
	[CallerMemberName] string callerName = "", 
	[CallerFilePath] string callerPath = "", 
	[CallerLineNumber] int callerLine = 0, 
	bool fromBase = false, 
	params (string Key, string Value)[] parameters)
{
	var sep1 = Path.DirectorySeparatorChar;
	var sep2 = Path.AltDirectorySeparatorChar;
	var tmp1 = Path.GetExtension(callerPath);
	var tmp2 = Path.GetFileNameWithoutExtension(callerPath);
	var fname = Path.GetFileName(callerPath);
	var evtString = $"[{evt}] in {callerName} at {fname}:{callerLine}";
	var callerNameSuffix = fromBase ? ":ViewModelBase" : "";
	Log.Write(evtString, $"{this.GetType().Name}{callerNameSuffix}", parameters);
}
```
2. run the app on android in the debugger and break in this function
3. inspect the values of sep1 and sep2 and you will see that both the separator and the alt separator are set to '/' on android (which makes the "alt" variation useless in this scenario)

### Expected Behavior
The result of the call to `Path.GetFileName()` function should only return the file name and extension.
### Actual Behavior
The `fname` variable contains the full path to the source file containing the calling function.
### Basic Information

- Version with issue: current
- Last known good version: unknown
- IDE: VS2019 Community on Windows 10
- Platform Target Frameworks: 
  - iOS:  11.5
  - Android: Compiling for 10.0 (API level 29), running on device with 8.0 (API 26)
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

To get around this issue for now, I added code to manually parse the file name.

**Comment by hartez** [comment]
> 2\. inspect the values of sep1 and sep2 and you will see that both the separator and the alt separator are set to '/' on android (which makes the "alt" variation useless in this scenario)

This is the expected behavior on Android; Android only has one valid path separator (as do any Linux/Unix variants). The "alt" property exists because Windows uses "\" as the directory separator character but can handle paths which use "/" (which is the alt version for Windows).

**Comment by lwg-jmarciniak** [comment]
I totally understand that on *nix systems, that "/" is the only valid separator, but when paths are supplied by the compiler services, those paths may often be based on a windows file system, NOT a *nix file system.  Understand the paths I am trying to parse are *not* file paths on the device, they are source code file paths and are used for troubleshooting.

**Comment by hartez** [comment]
@lwg-jmarciniak I see what you're saying - yes, this is a known issue with GetFileName when used across platforms. See https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfilename?view=netstandard-2.1 (the Remarks section at the bottom).

**Comment by lwg-jmarciniak** [comment]
@hartez thanks for the info... I did see that remark earlier, but I guess I just wasn't expecting it to occur in the compiler services... Since the IO functions on Windows *can* parse *nix file paths, maybe it would make sense for them to transform "\" separators to "/" for purposes of the [CallerFilePath] attribute.  That way, even cross compiled apps can take advantage of the path parsing if desired.  For now I will simply keep the code I have that replaces "\" with "/" prior to the GetFileName() call.  Please feel free to close this issue if desired (or turn it into a feature/change request).
