### ISSUE TITLE
[Bug] [Android] SelectedItem disappeared when adding custom ListView inside ScrollView

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#11164]
### Description

We have custom ListView control, when adding our ListView inside ScrollView the SelectedItem with SelectedItemTemplate is disappeared. The same works fine without ScrollView. The reported issue is a break in XF version **4.1.0.618606**. The occurs in Android only.

### Steps to Reproduce

1. Run the sample in Android platform.
2. Select an item.
3. **Note**: SelectedItem is disappeared.

### Expected Behavior
SelectedItem should render in Android.

### Actual Behavior
SelectedItem is disappeared.

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version: 4.1.0.581479
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/60344234/85284190-65972400-b4ac-11ea-96f4-cd0a863ae08c.png)

### Reproduction Link
[IssueSample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/IssueSample-1365090137)

### Workaround

Loading our ListView without ScrollView works fine.

**Comment by rmarinho** [comment]
Hi, looking at the sample the issue seems to be related with Syncfusion Listview, if i use our normal ListView it seems to work fine . 
But also it's not a good practice to put the ListView inside a ScrollView

```
 <ContentPage.Content>
        <ScrollView>
            <ListView x:Name="listView" RowHeight="60"  ItemsSource="{Binding ContactsInfo}">
                <ListView.ItemTemplate >
                    <DataTemplate>
                        <ViewCell>
                            <sfborder:SfBorder BorderColor="Red" BorderWidth="1">
                                <Grid x:Name="grid">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="70" />
                                        <ColumnDefinition Width="*" />
                                    </Grid.ColumnDefinitions>
                                    <Image Source="{Binding ContactImage}" VerticalOptions="Center" HorizontalOptions="Center" HeightRequest="50" WidthRequest="50"/>
                                    <Grid Grid.Column="1" RowSpacing="1" Padding="10,0,0,0" VerticalOptions="Center">
                                        <Label LineBreakMode="NoWrap" TextColor="#474747" Text="{Binding ContactName}"/>
                                        <Label Grid.Row="1" Grid.Column="0" TextColor="#474747" LineBreakMode="NoWrap" Text="{Binding ContactNumber}"/>
                                    </Grid>
                                </Grid>
                            </sfborder:SfBorder>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </ScrollView>
    </ContentPage.Content>
```

**Comment by syncsiva** [comment]
@rmarinho 
1. This issue occurs when using SelectedItemTemplate feature in SfListView where SfListView allows to define separate template for selected item. 
2. Also, It was worked till 4.1.0.581479 version and breaking after 4.1.0.618606 without any changes in sample. 
Version with issue: 4.1.0.618606
Last known good version: 4.1.0.581479
