### ISSUE TITLE
Scrolling in collectionview clears Picker selected value

### ISSUE THREAD

**Issue by programmingworld1** [xamarin/Xamarin.Forms#11163]
### Description
I have a contentpage within it a collectionview. The collectionview chooses a datatemplate based on a datatemplateselector. One of those datatemplates has a picker. When I set a picker value and after that scroll through the list and scroll back again, the picker value is removed. 

### Steps to Reproduce

1. Make a collectionview that chooses a datatemplate based on a datatemplateselector
2. Add enough items to the collectionview so you can scroll a couple of pages long
3. One of the datatemplates should make use of a picker

### Expected Behavior
After setting the picker value, scrolling through the list and back, that shouldn't delete the picker value. 

### Actual Behavior
Picker value gets removed after scrolling down and back up to the picker.

### Basic Information

- Version with issue: 4.5.0.6
- Last known good version:
- IDE: VS
- Platform Target Frameworks: 
  - Android: 9 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
```
<ContentPage.Resources>
    <converters:CheckListBoolToRequiredStarStringSymbolConverter  x:Key="BoolToStringSymbolConverter"/>

    <DataTemplate x:Key="NumberFieldDataTemplate">
        <StackLayout>
            <StackLayout Padding="5">
                <Label Text="{Binding ., Converter={StaticResource BoolToStringSymbolConverter}}"></Label>
                                <Picker x:Name="picker" SelectedItem="{Binding Value}">
                    <Picker.ItemsSource>
                        <x:Array Type="{x:Type x:String}">
                            <extensions:Translate Text="checklist_picker_yes"/>
                            <extensions:Translate Text="checklist_picker_no"/>
                        </x:Array>
                    </Picker.ItemsSource>
                </Picker>
            </StackLayout>
            <BoxView HeightRequest="1" BackgroundColor="DarkGray" />
        </StackLayout>
    </DataTemplate>

    <checklist:CheckListEditFieldDataTemplateSelector x:Key="TemplateSelector"         
                                                     NumberField="{StaticResource NumberFieldDataTemplate}"/>
</ContentPage.Resources>

<StackLayout>
    <CollectionView x:Name="_collectionView"
                        ItemsSource="{Binding CheckListItems}" 
                        SelectionMode="None"
                        ItemTemplate="{StaticResource TemplateSelector}">
        <CollectionView.ItemsLayout>
            <LinearItemsLayout Orientation="Vertical" ItemSpacing="5" />
        </CollectionView.ItemsLayout>
    </CollectionView>
</StackLayout>
```

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Richard-Dufour** [comment]
You guys are so quick at closing tickets and calling them "Done". Its almost 2024 and this bug is still there.
