### ISSUE TITLE
MSBuild failures

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11175]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/idea/1089028/msbuild-failures.html)._

---
[regression] [worked-in:16.4.0 Preview 3]
I am randomly getting the error 'Child node "6" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\andrew.cope\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.'.

Here's what a typical MSBuild failure file looks like:

UNHANDLED EXCEPTIONS FROM PROCESS 12468:
=====================
12/11/2019 13:51:52
System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.BeginWaitForConnection(AsyncCallback callback, Object state)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.PacketPumpProc()
===================

---
#### Andrew Cope on 11/12/2019, 06:24 AM: 

<p>Looks like it's permanently broken now. All I did was change branches and attempt a rebuild. I'm reverting to the release version of 2019 to try and get some work done :-/</p>

#### Visual Studio Feedback System on 11/13/2019, 02:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 12/2/2019, 01:19 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Andrew Cope on 12/3/2019, 00:06 AM: 

<p>Just to confirm that we've seen this several times now as we've begun to adopt .Net Core throughout our code base. I got it a couple of days ago with the latest preview of vs 2019.</p>

#### nmytelka [MSFT] on 12/9/2019, 04:52 PM: 

<p>Hi @<a target='_blank' href="https://developercommunity.visualstudio.com/users/52800/AndrewCope.html">Andrew Cope</a>,</p>
<p>I don’t have enough information to be able to diagnose your problem. Would you mind either providing steps by which I could reproduce your problem (including a project to run them on)? If that isn’t possible, could you send the trace from MSBUILDDEBUGCOMM? Thanks!</p>
<p>To capture a trace from MSBUILDDEBUGCOMM, set MSBUILDDEBUGCOMM (an environment variable) to 1, set MSBUILDDEBUGPATH to a folder, and run your scenario. The relevant traces should appear in the folder; upload all of those and a diag build log.</p>
<p>Use these instructions to respond to More Info requests from Visual Studio: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a>.</p>

#### nmytelka [MSFT] on 12/9/2019, 05:04 PM: 

<p>Hi @<a target='_blank' href="https://developercommunity.visualstudio.com/users/52800/AndrewCope.html">Andrew Cope</a>,</p>
<p>I don’t have enough information to be able to diagnose your problem. Would you mind either providing steps by which I could reproduce your problem (including a project to run them on)? If that isn’t possible, could you send the trace from MSBUILDDEBUGCOMM? Thanks!</p>
<p>To capture a trace from MSBUILDDEBUGCOMM, set MSBUILDDEBUGCOMM (an environment variable) to 1, set MSBUILDDEBUGPATH to a folder, and run your scenario. The relevant traces should appear in the folder; upload all of those and a diag build log.</p>
<p>Use these instructions to respond to More Info requests from Visual Studio: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a>.</p>

#### Visual Studio Feedback System on 12/17/2019, 06:01 PM: 

We will close this report in 7 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.
#### Andrew Cope on 12/18/2019, 00:48 AM: 

(private comment, text removed)
#### Visual Studio Feedback System on 12/19/2019, 02:39 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Michael Litwak on 1/23/2020, 00:45 PM: 

(private comment, text removed)
#### nmytelka [MSFT] on 1/24/2020, 02:25 PM: 

<p>Sorry if my first request for more information wasn’t clear and for the delay in responding.    We would like to see a diagnostic build log from the same build as the full folder of comm traces in order to correlate build activity with the crash logging. You can capture a build log by appending the <code>-fileloggerparameters:v=diag</code> switch to the command line that failed. Thank you!</p>

#### Andrew Cope on 1/27/2020, 01:09 AM: 

(private comment, text removed)
#### nmytelka [MSFT] on 1/28/2020, 09:12 AM: 

<p>This is poor error reporting from MSBuild, so I created an issue <a target='_blank' href="https://github.com/microsoft/msbuild/issues/5085">here</a>.</p>
<p>We think that the underlying issue is this case is that the XamlCTask isn’t finishing, so I’m reassigning it to Xamarin to investigate. The same symptoms could arise if another task doesn’t complete properly, so if you notice a similar but different problem, file a separate feedback item.</p>
<p>Thanks @<a target='_blank' href="https://developercommunity.visualstudio.com/users/52800/AndrewCope.html">Andrew Cope</a> for bringing this to our attention!</p>

**Comment by StephaneDelcroix** [comment]
Could you please attach a project triggering this build issue ? we can't investigate without one...

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
