### ISSUE TITLE
Editor behaves not as expected in XF 4.7.0.968

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11178]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1086921/editor-behaves-not-as-expected-in-xf-470968.html)._

---
I'm filling Editor with text programmatically. 
On XF 4.4.0.991537 editor was automatically scrolling to bottom to show last line.
Now, with  XF 4.7.0.968:
On Android - editor not scrolling to bottom  to show last line.
On iOS (iPADOS 13.5.1) - editor not scrolling to bottom and in addition editor not scrolling at all. I have to put editor inside scrollview to make it scrollable.

---
#### Visual Studio Feedback System on 6/22/2020, 01:06 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Might be the same as https://github.com/xamarin/Xamarin.Forms/issues/10690

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by JuanuMusic** [comment]
Hi! I'm actually having this issue in Xamarin Forms 4.8.
I'm attaching an example where I create an editor that has constraints for the Max and Min Height (the proposed on #11917 ):

The example captures the issue well:
- There is a button that adds text programmatically and then sets the focus on the Editor
**Android:** The editor focuses correctly and scrolls to where the caret is
**iOS**: The editor focuses correctly but doesn't scroll to the caret position until the user starts typing.

[GrowingEditor.zip](https://github.com/xamarin/Xamarin.Forms/files/5247491/GrowingEditor.zip)
