### ISSUE TITLE
Device.Idiom for Android misleading in XF 4.7.0.968

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11177]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1086796/deviceidiom-for-android-misleading-in-xf-470968.html)._

---
After update to XF 4.7.0.968 on Android phone "Xiaomi Mi9 Lite" result of Device.Idiom returns "TV"  !
On XF 4.4.0.991537 result was proper = "Phone".

---
#### Visual Studio Feedback System on 6/22/2020, 01:10 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kcrg** [comment]
I think it's duplicate #11166

**Comment by samhouts** [comment]
Duplicate of #11166
