### ISSUE TITLE
[Bug] FontImageSource doesn't use color from ResourceDictionary

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#11186]
### Steps to Reproduce

1. Create ImageButton with FontImageSource
```
<ImageButton>
                <ImageButton.Source>
                    <FontImageSource
                        FontFamily="FontAwesomeSolid"
                        Glyph="&#xf055;"
                        Size="60" />
                </ImageButton.Source>
            </ImageButton>
```
2. Create Resource dictionary
```
<Style ApplyToDerivedTypes="True" TargetType="{x:Type FontImageSource}">
        <Setter Property="Color" Value="{AppThemeBinding Dark={StaticResource DarkTextColor},
                                                         Light={StaticResource LightTextColor}}" />
    </Style>
```
3. Toggle appearance

### Expected Behavior
FontImageSource Color changed

### Actual Behavior
FontImageSource color remains the same

### Basic Information

- Version with issue: 4.8.0.1017-nigntly
- Reproduced on both Android and iOS
### Workaround

if I restart the app, it loads correct color.

**Comment by StephaneDelcroix** [comment]
Are you sure about your sample ? implicit styles, if I recall correctly, only apply to VisualElements, and FontImageSource does not inherit from VE...

could you please attach a small contained sample showcasing the problem ? thanks

**Comment by VladislavAntonyuk** [comment]
@StephaneDelcroix Verified on Android
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4886166/App1.zip)

**Comment by StephaneDelcroix** [comment]
If you replace the Value in you style setter by a static one (say 'HotPink') the value isn't applied either, because implicit styles do not apply to non-VisualElement.

you can open a enhancement request with a basic spec, and examples, for this if you need this feature. in the meantime, I'm closing the bug

**Comment by VladislavAntonyuk** [comment]
@StephaneDelcroix , so this code is not correct, because FontImageSource is not VisualElement:
```
<Style ApplyToDerivedTypes="True" TargetType="{x:Type FontImageSource}">
        <Setter Property="Color" Value="{AppThemeBinding Dark={StaticResource DarkTextColor},
                                                         Light={StaticResource LightTextColor}}" />
    </Style>
```
