### ISSUE TITLE
[Bug] ScrollViewRenderer HorizontalFadingEdgeEnabled ignored on horizontal ScrollView orientation

### ISSUE THREAD

**Issue by lukashaertel** [xamarin/Xamarin.Forms#11185]
### Description

Setting `HorizontalFadingEdgeEnabled` in a `ScrollViewRenderer` does not produce the expected result of fading the left and right edges on overflowing content. After looking into the source code, it appears that a second view is created for horizontal scroll behavior. The flags for controlling edge fading are not delegated to that view.

### Steps to Reproduce

1. Set a custom renderer for the `ScrollView`
2. Set the `HorizontalFadingEdgeEnabled` to `true` and invoke `SetFadingEdgeLength` on element and orientation change 

### Expected Behavior
Left and right edge of the scrolled content should be faded out, if there is more content to scroll to.

### Actual Behavior
The default look is still present. No edges are faded.

### Basic Information

- Version with issue: 4.6.0.800

### Workaround

Overriding `AddView` in the renderer to intercept the actually used `AHorizontalScrollView` and setting the fading edge properties on that view resulted in the correct behavior of fading left and right edges.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by lukashaertel** [comment]
Project to reproduce the bug:

[hscrollfade.zip](https://github.com/xamarin/Xamarin.Forms/files/4844945/hscrollfade.zip)

**Comment by rmarinho** [comment]
Thanks made a fix for it #11287
