### ISSUE TITLE
AutoSize for the CollectionView

### ISSUE THREAD

**Issue by Hummel37** [xamarin/Xamarin.Forms#11181]
It would be nice if there is a way to auto size the collectionview to fit its elements.

**Comment by EmilAlipiev** [comment]
what do you want to autosize here? do you want to autosize width and height or layoutitems? you are probably looking for similar to Flexlayout

**Comment by Hummel37** [comment]
The height of the listview, the height is actually the screenheight so that you can't put something else under the listview

**Comment by RGBPlaza** [comment]
This is *really* important, I have absolutely no idea how it's been so long since `CollectionView` was introduced without this being done yet. Personally I'd describe this issue as a pretty urgent bug fix.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
