### ISSUE TITLE
[Bug] Java.Interop.JavaLocationException Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.

### ISSUE THREAD

**Issue by easoftwaresanderson** [xamarin/Xamarin.Forms#11182]
### Description
I have one listview and when my customer choose one item,  I open one Rg.Plugins.Popup. In 
this one I have imagebuttons, It work fine for one or two items , and in others I have this crash.

### Steps to Reproduce

1.  Open on page with ListView Items , choose one Item
2.  Open one Rg.Plugins.Popup
 with imagebuttons to change Amount and others info ( I'm used tapped on listview with on messagingCenter to send item to ViewModel ) MVVM Prism
3.  One or two items work fine, in others the app crash with this message

### Expected Behavior
No message crash
### Actual Behavior
Crashes for customers and end users
[report-2518093882493709999-d7cb50f8-fe69-46cc-b4f3-e5c4a1f07723.txt](https://github.com/xamarin/Xamarin.Forms/files/4820323/report-2518093882493709999-d7cb50f8-fe69-46cc-b4f3-e5c4a1f07723.txt)
### Basic Information
Version with issue:  4.4.0.991864
IDE: in Visual Studio 2019 Version 16.5.4
Platform Target Frameworks:
iOS: N/A
Android: 4.1 to 9
UWP: N/A
Android Support Library Version:
Nuget Packages:

-     <PackageReference Include="Microsoft.AppCenter.Analytics" Version="3.1.0" />
-     <PackageReference Include="Microsoft.AppCenter.Crashes" Version="3.1.0" />
-     <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.10.1" />
-     <PackageReference Include="Prism.Unity.Forms" Version="7.0.0.396" />
-     <PackageReference Include="Rg.Plugins.Popup" Version="1.2.0.223" />
-     <PackageReference Include="Xam.Plugin.Connectivity" Version="3.2.0" />
-     <PackageReference Include="Xam.Plugin.Media" Version="4.0.1.5" />
-     <PackageReference Include="Xam.Plugins.Messaging" Version="5.2.0" />
-     <PackageReference Include="Xamarin.Essentials" Version="1.5.2" />
-     <PackageReference Include="Xamarin.Forms" Version="4.4.0.991864" />
-     <PackageReference Include="Xamarin.Forms.BehaviorValidationPack" Version="1.1.0" />

Affected Devices:
Android 8.0.0 Galaxy J5 Prime
### Screenshots
I don't have any screen, default crash of Android
### Workaround
No known workarounds currently.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
