### ISSUE TITLE
[Bug] Release Notes for 4.7 missing navigation

### ISSUE THREAD

**Issue by Gakk** [xamarin/Xamarin.Forms#11202]
### Description

The page with release notes for Xamarin Forms 4.7 is missing a navigation element in the menu, making it inaccessible:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.7/4.7.0

### Steps to Reproduce

1. Navigate to: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/
2. Showing latest release to be "Xamarin Forms 4.6", even though 4.7 has been available on NuGet since June 17th.
3. Opening navigation element "Xamarin.Forms 4.7" only reveals release notes for -pre1 to -pre4.
4. Navigate directly to: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.7/4.7.0
5. This page does not open a navigation item in the navigation menu.

### Expected Behavior

Release notes for 4.7 should be visible in navigation menu.

### Actual Behavior

Release notes for 4.7 is only available by Googling, no direct link.

### Screenshots

![image](https://user-images.githubusercontent.com/5013909/85723678-c2385000-b6f3-11ea-9ef0-e8fcd56c79a7.png)

### Reproduction Link

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.7/4.7.0

### Workaround

Google "Xamarin Forms 4.7 Release Notes"

**Comment by samhouts** [comment]
This is resolved. Thank you!
