### ISSUE TITLE
[Enhancement] Github discussions

### ISSUE THREAD

**Issue by Reveon** [xamarin/Xamarin.Forms#11208]
Would it be possible to open github discussions for all Xamarin repos (Forms,Essentials,Maui,Xamarin.Android and iOS) ? They are already opened in aspnet and efcore and it looks like a better place for people who only have a question. And I think it might also clear up issues a little bit as you can move "issues" that really are not issues to discussions.

**Comment by davidortinau** [comment]
I wish. It's not yet available on this repo. We'll continue to pursue it though.
