### ISSUE TITLE
[Bug] [iOS][SwipeView] Swipe view not handling tap gesture events until swiped

### ISSUE THREAD

**Issue by dwightbennett** [xamarin/Xamarin.Forms#11209]
### Description
On iOS when i use a Swipe view for a Data Template in a Collection view, If i add a Tap Gesture to the swipe view's content ,the tap gesture will not fire until i swipe the view.  It does fire if i tap on content in the view, for example a label or box view. 
### Steps to Reproduce

1. Place a Swipe view in a collection view
2. Add a swipe item
3. Add a view to the content of the Swipe view
4. Add a Tap Gesture recognizer to the Content
5. Tap on empty space in the cell

### Expected Behavior
The Tap gesture Tapped event or command should fire
### Actual Behavior
The tapped gesture event or command doesn't fire unless you tap on content or swipe the view first.
### Basic Information

- Version with issue:
- Last known good version: ? Swipe view is still experimental
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS: 13.4
- Nuget Packages: Xamarin.Forms 4.7.0.968
- Affected Devices:
Apple Phones, did not test tablets
### Screenshots
![swipeview](https://user-images.githubusercontent.com/44422679/85798304-7d63e780-b6fa-11ea-895a-ca5ed466122d.gif)

### Reproduction Link
[Example Project](https://1drv.ms/u/s!Aixp5FAuhbJigjOO9Wto5Kv59dIU?e=tTFGEW)

### Workaround
There is a work around for now.  If you place a transparent BoxView on top of your content, you can still tap the swipe view and the events will fire.

**Comment by thomasgalliker** [comment]
Same issue here with Xamarin.Forms 4.7.0.1142.
