### ISSUE TITLE
[Enhancement] x:OnRotation markup

### ISSUE THREAD

**Issue by globodemic** [xamarin/Xamarin.Forms#11213]
## Summary
It would be great if Xamarin has markup like => {x:OnRotation Landscape=Vertical, Portrait=Horizontal}, to react the phone rotation.

## API Changes
Need an internal OnRotated event, but my temp solution is :
-Have a BaseContentPage with Rotated event and when OnSizeAllocated changed invoke the Rotated event with OrientationArgs
-custom markup will get the BaseContentPage.Rotated event and subscribe on it
-when orientation changed the event fired and changed the layout

Example:

1. STEP  BaseContentPage#
 public abstract class BaseContentPage : ContentPage
{
	
	public event EventHandler<OrientationArgs> Rotated;
         
        protected override void OnSizeAllocated( double width, double height )
		{
			base.OnSizeAllocated( width, height ); //must be called

			if( this.width != width || this.height != height )
			{
				this.width = width;
				this.height = height;

				UpdateLayout();
			}			
		}

		private void UpdateLayout()
		{
			if( width > height )
				Rotated?.Invoke( this, new OrientationArgs( OrientationArgs.Orientations.Landscape ) );
			else
				Rotated?.Invoke( this, new OrientationArgs( OrientationArgs.Orientations.Portrait ) );
		}

}

2. STEP Custom EventArgs#
public class OrientationArgs : EventArgs
	{
		public enum Orientations
		{
			Landscape,
			Portrait
		}
		public Orientations Orientation {get;}

		public OrientationArgs( Orientations orientation)
		{
			this.Orientation = orientation;
		}
	}
3. STEP Custom markupextension#
/// <summary>For Detecting Rotation</summary>	
	[ContentProperty( "Default" )]
	public class OnRotationExtension<T> :BindableObject, IMarkupExtension<T> 
	{
		#region Bindable Properties
		public static readonly BindableProperty PortraitProperty = BindableProperty.Create( nameof( Portrait ), typeof( object ), typeof( OnRotationExtension<T> ), default(object), BindingMode.OneWay );
		public static readonly BindableProperty LandscapeProperty = BindableProperty.Create( nameof( Landscape ), typeof( object ), typeof( OnRotationExtension<T> ), default(object), BindingMode.OneWay );
		#endregion
		#region Public Properties
		public object Portrait
		{
			get => GetValue( PortraitProperty );
			set => SetValue( PortraitProperty, value );
		}
		public object Landscape
		{
			get => GetValue( LandscapeProperty );
			set => SetValue( LandscapeProperty, value );
		}
		#endregion
		#region Private Properties
		private BaseContentPage baseContentPage;
		private GridLengthTypeConverter converter = new GridLengthTypeConverter();
		
		#endregion
		#region Methods
		public T ProvideValue( IServiceProvider serviceProvider )
		{
			if( Portrait is null || Landscape is null )
			{
				IXmlLineInfoProvider lineInfoProvider = serviceProvider.GetService( typeof( IXmlLineInfoProvider ) ) as IXmlLineInfoProvider;
				IXmlLineInfo lineInfo = (lineInfoProvider != null) ? lineInfoProvider.XmlLineInfo : new XmlLineInfo();
				throw new XamlParseException( "OnRotationExtension requires Portrait  or Landscape property to be set", lineInfo );
			}

			IProvideValueTarget provideValueTarget = serviceProvider.GetService( typeof( IProvideValueTarget ) ) as IProvideValueTarget;

			EventHandler<OrientationArgs> handler = ( s, e ) => {
				BindableObject targetObject = provideValueTarget.TargetObject as BindableObject;
				T result = GetValue( e.Orientation );
				if(provideValueTarget.TargetProperty is BindableProperty bindableProperty )
					targetObject?.SetValue( bindableProperty, result );
			};

			if(baseContentPage is null )
			{
				PropertyInfo cachedPropertyInfo = provideValueTarget.GetType().GetProperty( "Xamarin.Forms.Xaml.IProvideParentValues.ParentObjects", BindingFlags.NonPublic | BindingFlags.Instance );
				if( cachedPropertyInfo != null )
				{
					IEnumerable<object> parentObjects = cachedPropertyInfo.GetValue( provideValueTarget ) as IEnumerable<object>;
					if( parentObjects == null )
						throw new ArgumentException( "Unable to access parent objects" );

					foreach( object target in parentObjects )
					{
						if( target is BaseContentPage page )
						{
							baseContentPage = page;							
							break;
						}
					}
				}
			}
			
			baseContentPage.Rotated -= handler;
			baseContentPage.Rotated += handler;
			return GetValue( DeviceDisplay.MainDisplayInfo.Orientation == DisplayOrientation.Landscape ? Orientations.Landscape : Orientations.Portrait );
		}

		

		object IMarkupExtension.ProvideValue( IServiceProvider serviceProvider ) => (this as IMarkupExtension).ProvideValue( serviceProvider );

		public T GetValue( Orientations  orientation )
		{
			object value = orientation == Orientations.Landscape ? Landscape : Portrait;

			//StackLayout - Horizontal, Vertical etc.
			if( typeof( T ).IsEnum )
				return ( T )Enum.Parse( typeof( T ), value as string );

			//Grid - GridLength, Double
			else if( typeof( T ).IsValueType )
			{
				//Double value
				double doubleResult = 0d;
				if( Double.TryParse(value as string, out doubleResult ) )
					return ( T )( object )doubleResult;
				//GridLenght
				return ( T )converter.ConvertFromInvariantString( value as string );
			}

			return default( T );
		}		
		#endregion
		
		
	}
4. STEP HOW IT WORKS#
<Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition>
                        <ColumnDefinition.Width>
                            <markup:OnRotation x:TypeArguments="xf:GridLength">
                                <markup:OnRotation.Portrait>
                                    <OnIdiom Phone="0" Tablet="3*" />
                                </markup:OnRotation.Portrait>
                                <markup:OnRotation.Landscape>
                                    <OnIdiom Phone="0" Tablet="4*" />
                                </markup:OnRotation.Landscape>
                            </markup:OnRotation>
                        </ColumnDefinition.Width>
                    </ColumnDefinition>
                </Grid.ColumnDefinitions>
</Grid>

## Intended Use Case
EXAMPLE 2# GRID
<Grid>    
<Grid.ColumnDefinitions>
    <ColumnDefinition Width="{x:OnRotation 
Landscape={ OnIdiom Phone= {OnPlatform iOS=*, Android=*, UWP=100 }, Tablet= {OnPlatform iOS=*, Android=*, UWP=200}},
Portrait={ OnIdiom Phone= {OnPlatform iOS=*, Android=*, UWP=100 }, Tablet= {OnPlatform iOS=*, Android=*, UWP=200}}}">
    </ColumnDefinition>
</Grid.ColumnDefinitions>
</Grid>

EXAMPLE 2# STACKLAYOUT
 <StackLayout Orientation={x:OnRotation Landscape="Horizontal", Portrait="Vertical"}></StackLayout>

EXAMPLE 3# Image
<Image Source="waterfront.jpg" WidthRequest={x:OnRotation Landscape="300" Portrait="100"} />

**Comment by StephaneDelcroix** [comment]
The solution for this right now is to use VSM.

We're thinking about bringing the capability to our CSS story using media selectors.

A markup will likely be part of the story, but with a larger scope, including this, app theme, and other device dependent changes

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
