### ISSUE TITLE
[Enhancement] [TimePicker] Allow TimePicker to set 12/24 hour time on all platforms

### ISSUE THREAD

**Issue by varyamereon** [xamarin/Xamarin.Forms#11215]
## Summary

Currently the TimePicker will show in either 12 or 24 hour time based on the user's settings. The only exception is in Android when the Format is specifically set to 'HH:mm' in which case it will show in 24 hour time. It would be useful to have a property to set this value so it is consistent on all platforms.

## API Changes

Currently only Android supports showing 24 hour time via the method above. I propose introducing a boolean property to TimePicker called Is24Hour that would force the control to show as 24 hour time on all platforms. This is similar to the way TimePicker works on [Android](https://developer.android.com/reference/android/widget/TimePicker#is24HourView()) and [UWP](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.timepicker.clockidentifier?view=winrt-19041) already.

## Intended Use Case

There are certain industries, such as the aviation industry which I develop apps for, that exclusively use 24 hour time as this is the officially recognised format.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
