### ISSUE TITLE
Renaming `master` to `main`

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#11210]
### IMPORTANT!

We are renaming the `master` branch to `main`. Please target any new feature work to the `main` branch from now on. You may need to update your forks!

**Comment by pictos** [comment]
@samhouts, will this affect open PRs?

**Comment by samhouts** [comment]
@pictos I have just gone through every open PR and retargeted to either 4.80 or main as appropriate. Hopefully, this will prevent any issues!!!

**Comment by VladislavAntonyuk** [comment]
@samhouts just a curiosity, what is the reason/benefits of the rename? the "develop" is more informative, isn't it?

**Comment by StephaneDelcroix** [comment]
next: drop the old `master` branch to avoid people targeting it

**Comment by PawKanarek** [comment]
Pls change MasterDetailPage also, because I feel offended by word "Master", even if there is no logical connection to slavery.

**Comment by samhouts** [comment]
Branch is renamed, default is now main, all PRs are retargeted, master is deleted. Thanks!
