### ISSUE TITLE
[Enhancement] Add more descriptive exception for relative navigation with passed data included 

### ISSUE THREAD

**Issue by Nerves82** [xamarin/Xamarin.Forms#11220]
## Summary
When attempting to use relative navigation while also passing data, the exception is thrown.

` Relative routing to shell elements is currently not supported. Try prefixing your uri with ///:`

A more descriptive exception needs to be thrown to indicate the proper cause of the exception

`Relative routing does not support passing date. Use absolute routing to enable passing data.`

## API Changes

This change would need to take place in ShellUriHandler.cs
`internal static List<RouteRequestBuilder> GenerateRoutePaths(Shell shell, Uri request, Uri originalRequest, bool enableRelativeShellRoutes)`

The current exception that is thrown when passing data with relative routing is thrown on line 173 of the above method. 

			if (!relativeMatch)
			{
				for (int i = 0; i < routeKeys.Length; i++)
				{
					var route = routeKeys[i];
					var uri = ConvertToStandardFormat(shell, CreateUri(route));
					if (uri.Equals(request))
					{
						throw new Exception($"Global routes currently cannot be the only page on the stack, so absolute routing to global routes is not supported. For now, just navigate to: {originalRequest.OriginalString.Replace("//", "")}");
						//var builder = new RouteRequestBuilder(route, route, null, segments);
						//return new List<RouteRequestBuilder> { builder };
					}
				}
			}

**Comment by PureWeen** [comment]
This is a bug if this is true

Can you attach a repro?
