### ISSUE TITLE
[Bug] UWP ScrollView touch not reflecting the current position

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#11226]
### Description

The touch stays at the original position even after scrolling (UWP only)

### Basic Information

- Version with issue: XF 4.7.0.968
- Last known good version: XF 4.6.0.967

This bug is a bummer and should not happen in an official release!

**Comment by jsuarezruiz** [comment]
This issue must have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/11207

**Comment by EmilAlipiev** [comment]
@jsuarezruiz any ETA for this one? can we get at least a pre release package to test?

**Comment by vardansargsyan92** [comment]
Hi guys.

Any news about this issue?

**Comment by EmilAlipiev** [comment]
it seems to be fixed with the today's update. can you please test your case also? for me looks fine

**Comment by vardansargsyan92** [comment]
@EmilAlipiev  unfortunately this is not working for my case. The scenario is the following. Suppose we have several entries, labels inside the scroll view. When the page is loaded and I scroll down and then tap on any child ("Nonfocusable itself" like a label) the scroll goes up. I have created a bug [report](https://github.com/xamarin/Xamarin.Forms/issues/11258).

**Comment by mknotzer** [comment]
the focus bug is only partly fixed, clicking on a label moves the focus to the top entry

**Comment by samhouts** [comment]
closed by #11207

**Comment by mknotzer** [comment]
any news about this issue? the focus still moves to the first focusable element (ScrollBar moves up) when clicking on a label as example

**Comment by mknotzer** [comment]
work around here https://github.com/xamarin/Xamarin.Forms/issues/5652#issuecomment-763886698

**Comment by vardansargsyan92** [comment]
Hi @mknotzer. Just use the renderer until fix. That works fine for me.
