### ISSUE TITLE
[Bug] Packaging GTK# application problem

### ISSUE THREAD

**Issue by zejtin** [xamarin/Xamarin.Forms#11225]
### Description

I've followed this tutorial here for adding GTK to Xamarin.Forms project:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/gtk?tabs=windows

GTK# works nicely on Mac, Windows and Linux. The problem I have is with Publishing/Packaging application on Linux using latest MonoDevelop - it fails every time

### Steps to Reproduce

1. Go to MonoDevelop on Linux
2. Right click the GTK# project => Tools => Create Package
3. Archive of Binaries
4. Select project and set build to Linux Release and archive tar.gz 

### Expected Behavior

Generate tar.gz package

### Actual Behavior

Package creation failed

### Basic Information

- Version with issue: 4.4.0
- IDE: MonoDevelop 7.8.4

**Comment by jsuarezruiz** [comment]
@zejtin Could you share more information about how are you packing it?.
I have done some tests using MonoDevelop 7.8.4:

<img width="1280" alt="tipcalc-linux" src="https://user-images.githubusercontent.com/6755973/86358447-c1616a00-bc6f-11ea-89b8-78198c4b31d4.png">

<img width="1278" alt="tipcalc-package" src="https://user-images.githubusercontent.com/6755973/86358430-bc041f80-bc6f-11ea-9057-1f9ff32be009.png">

**Comment by zejtin** [comment]
Sure thing, here are the steps:

![Screenshot 2020-07-04 at 08 19 33](https://user-images.githubusercontent.com/18098346/86506439-a6a60700-bdcf-11ea-9e98-3905637099d7.png)

![Screenshot 2020-07-04 at 08 19 40](https://user-images.githubusercontent.com/18098346/86506445-b1609c00-bdcf-11ea-8b54-644396d4627a.png)

![Screenshot 2020-07-04 at 08 20 31](https://user-images.githubusercontent.com/18098346/86506450-baea0400-bdcf-11ea-9103-a765ca1b9c2c.png)

![Screenshot 2020-07-04 at 08 21 54](https://user-images.githubusercontent.com/18098346/86506462-cc331080-bdcf-11ea-8f8b-bdd875485f6b.png)

**Comment by zejtin** [comment]
Just to add that the **Archive of Sources** works for me, but I am not looking for this, I'm looking for a way to publish application for further distribution, which I presume is **Archive of Binaries** but I might be wrong?

**Comment by knocte** [comment]
I think this is a MonoDevelop bug, not a Xamarin.Forms bug.

**Comment by zejtin** [comment]
Is there a way to do this packaging manually?

**Comment by knocte** [comment]
of course? just use the command line

**Comment by zejtin** [comment]
But what commands should be executed, do you have some link for reference? Is it possible to make deb/rpm files beside tar.gz?

**Comment by knocte** [comment]
Honestly speaking: welcome to the vast world of app packaging. Creating tar.gz via command line is easy; creating deb/rpms is not that easy (although many tools alleviate the pain, such as https://github.com/jordansissel/fpm ), but these days I wouldn't ever bother with that, the new way of packaging stuff (that is modern, cross-distro and secure via sandbox) is to use snap or flatpak. For an example of how to package mono apps with snap, take a look at this: https://gitlab.com/nblockchain/geewallet/-/blob/frontend/scripts/snap_build.sh ; for an example of how to package a mono app with flatpak, look for SparkleShare.

**Comment by zejtin** [comment]
Thank you very much for the links and detailed explanation! I'll let you know how it went :) 

Btw I've opened issue on monodevelop for this bug if anyone stumbles upon this https://github.com/mono/monodevelop/issues/9643

**Comment by knocte** [comment]
> Btw I've opened issue on monodevelop

Great, you can close this issue then.
