### ISSUE TITLE
[Bug] UWP ListView Exception with Rg.Plugins.Popup

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#11221]
### Description

assigning data to a ListView in a PopupPage in the constructor causes an exception (UWP only)

`
public MyPopup()
{
    InitializeComponent();

    xListView.ItemsSource = myList; // Exception

    Task.Run(async () =>
    {
        await Task.Delay(1000);

        Device.BeginInvokeOnMainThread(() => xListView.ItemsSource = myList); // ok
    });
}
`

### Basic Information

- Version with issue: XF 4.7.0.968
- Nuget Packages: Rg.Plugins.Popup 2.0.0.3

System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)
   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.MeasureOverride(Size availableSize)
   at Windows.UI.Xaml.UIElement.Measure(Size availableSize)

**Comment by EmilAlipiev** [comment]
was that working with earlier versions of XF?

**Comment by rmarinho** [comment]
Can you please provide a sample for us to look at . 

Thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by mknotzer** [comment]
@samhouts: I finally found the bug: RowHeight="40" without HasUnevenRows="True"

**Comment by mknotzer** [comment]
please reopen the issue and fix it (UWP only)

**Comment by mknotzer** [comment]
@pauldipietro, @samhouts: please reopen the issue

**Comment by mknotzer** [comment]
@rmarinho please check my update, the bug is easy to reproduce
