### ISSUE TITLE
[Bug] AbsoluteLayout SetLayoutBounds and SetLayoutFlags giving wrong result

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#11234]
### Description

If we set AbsoluteLayout bounds proportionally for X and Width, we get wrong result. 

let's say we want to set bounds for a frame, so that X is 0.1 and Width is 0.8 (leaving 0.1 from the right side)

In the screenshot, the Red frame is the wrong one, and Blue frame is the right one

<img src="https://user-images.githubusercontent.com/13087546/85949828-50366400-b99c-11ea-8d66-dd660c937244.PNG" width="200" height="350">

The Red is the result of this code

```csharp
AbsoluteLayout.SetLayoutBounds(frame, new Rectangle(0.1, 0, 0.8, 1));
AbsoluteLayout.SetLayoutFlags(frame, AbsoluteLayoutFlags.All);
```

While Blue is the result of our own calculations
```csharp
var frame = new Frame { BackgroundColor = Color.Blue };
var w = 0.8 * NonProportional.Width;
var x = (NonProportional.Width - w) / 2;
var y = 0;
var h = NonProportional.Height;

AbsoluteLayout.SetLayoutBounds(frame, new Rectangle(x, y, w, h));
AbsoluteLayout.SetLayoutFlags(frame, AbsoluteLayoutFlags.None);
```

### Steps to Reproduce

* Run attached solution, just that.

### Expected Behavior
To have Frame's in the centre of screen with width = 0.8 * AbsoluteLayout.Width and with margins of 0.1 * AbsoluteLayout.Width from left and right.

### Actual Behavior
Weird result, as shown in Red frame in screenshot

### Basic Information
XF 4.7.0.968
Android 9 and 10

### Workaround
Don't use Proportional bounds, calculate it yourself.

[AbsoluteLayoutTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4842403/AbsoluteLayoutTest.zip)

**Comment by rmarinho** [comment]
You really want is 
`AbsoluteLayout.SetLayoutBounds(frame, new Rectangle(0.5, 0, 0.8, 1));`

The X position you want is centered

**Comment by MhAllan** [comment]
@rmarinho , Then the resulting X will not be centre, in that case the question becomes: how can I draw something where X is at the centre?

**Comment by MhAllan** [comment]
@rmarinho Thanks, that is weird design though!
