### ISSUE TITLE
[Bug] No Flags needed for CarouselView

### ISSUE THREAD

**Issue by joshuangfraedom** [xamarin/Xamarin.Forms#11236]
### Description

I am able to use CarouselView without the application throwing an InvalidOperationException. Looks like this [merge](https://github.com/xamarin/Xamarin.Forms/commit/87d720c71ec1c8f8fea2daf2105ba4b6689d71f1#diff-a838fddaa0fe09f722bf5328649e51ac) removed the need for the flag as a result of this [PR](https://github.com/xamarin/Xamarin.Forms/pull/7465/files) however [MS documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/) still lists the control as being in preview.

### Steps to Reproduce

1. Create a forms project and add a carouselview, without adding any forms flags.

### Expected Behavior

1. An InvalidOperationException is thrown when running the application. 

### Actual Behavior

User can use the CarouselView

### Basic Information

- Version with issue: 4.4+ I think
- Last known good version: -

**Comment by jsuarezruiz** [comment]
We recover the expected behavior with this PR: https://github.com/xamarin/Xamarin.Forms/pull/11189

**Comment by rmarinho** [comment]
We removed all flags on 5.0.0
