### ISSUE TITLE
[Bug] BackButtonBehavior no longer displays on the first routed page in 4.7

### ISSUE THREAD

**Issue by Welchen** [xamarin/Xamarin.Forms#11244]
### Description
BackButtonBehavior no longer displays a button on the initial routed to page of the application  in 4.7.0.968. Reverting to 4.6.0.967 and below and it will show up.

After login our app shows the main page of the application. On this page we use the BackButtonBehavior override to add a sign out icon to return the user to back to the login page. With 4.7 our Signout button no longer is visible.  The Login page and Main page are in two different ShellItems on the AppShell.xaml

### Steps to Reproduce

1.  AppShell.xaml 
```
    <ShellItem Route="Login">
        <ShellContent ContentTemplate="{DataTemplate local:LoginPage}" />
    </ShellItem>

    <ShellItem Route="Main">
        <ShellContent ContentTemplate="{DataTemplate local:MainPage}" />
    </ShellItem>
```
2. LoginViewModel.cs
`await Shell.Current.GoToAsync("//Main");`

3. MainPage.xaml 
```
    <Shell.BackButtonBehavior>
        <BackButtonBehavior Command="{Binding LogoutCommand}"
            IconOverride="{FontImage FontFamily={StaticResource FontAwesomeSolid}, 
                Glyph={x:Static utils:FontAwesomeSolid.SignOutAlt}, 
                Size=20}"/>
    </Shell.BackButtonBehavior>
```

### Expected Behavior
Sign Out button (Icon replaces the back button icon) should show in the top left corner on the tool bar on the first and all routed to pages.

### Actual Behavior
Sign Out button does not show up on the first routed to page but does show up on the rest. 

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: 4.6.0.967
- IDE: Visual Studio 2019 Professional 16.6.2
- Platform Target Frameworks: 
  - iOS:  Default (13.5)
- Affected Devices: iPad Mini 4 (13.1.3)

### Screenshots

4.6

![46](https://user-images.githubusercontent.com/5358349/86061772-fb8ef980-ba2c-11ea-84f7-c04548042948.jpg)

4.7

![47](https://user-images.githubusercontent.com/5358349/86061788-02b60780-ba2d-11ea-8b97-2e950fd4d321.jpg)

### Sample 

[Xamarin Project that reproduces the error](https://1drv.ms/u/s!AuhmQT044pVwbppKXC1VghX_0yk?e=1v71GT)

**Comment by PureWeen** [comment]
@Welchen are you only seeing this on an iPAD?

If you don't use a FontImage but just use a local image or text does it replace?

Do you see any error messages in your application output about not being able to load the icon?

**Comment by Welchen** [comment]
@PureWeen This application is only built for iPad so haven't tried any other devices. 

I changed out the IconOverride for TextOverride and didn't see any text shown. 

No error messages. 

I tried a different FontImage into the Override and that didn't work either.  We use FontImage all over the product, the Fingerprint on the right of the supplied images are FontImage and show that it is still working.

**Comment by Welchen** [comment]
@PureWeen I added a link to my Issue that has a sample that I created.  The sample uses text instead of icons and reproduces the issue.  I also tested it against iPhone and iPad and both show the problem. Changing the Xamarin.Forms nuget package back to the newest 4.6.0 will show how it previously worked.
