### ISSUE TITLE
[Bug] UpdateToolbarItemIcons in ShellToolbarTracker on Android doesn't get called.

### ISSUE THREAD

**Issue by Trivias91** [xamarin/Xamarin.Forms#11242]
### Description

Overriding the UpdateToolbarItemIcons in ShellToolbarTracker on Android does nothing because its never called.  The issue seems to be that on line 514 of the ShellToolbarTracker in the UpdateToolbarItems method. The call to toolbar.UpdateMenuItems is not passed the UpdateToolbarItemIcons method so it uses the function inside ToolbarExtension instead of anything overridden inside of ShellToolbarTracker.

### Steps to Reproduce
Override the UpdateToolbarItemIcons in ShellToolbarTracker on Android using a custom renderer.
### Expected Behavior
Overriding UpdateToolbarItemIcons allows you to modify the toolbar icon
### Actual Behavior
It is never called.
### Basic Information

- Version with issue: I'm using XF 4.5 in my project, but the problematic code still seems to be there in later versions.
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - Android: 9.0
- Affected Devices:  All Android

**Comment by PureWeen** [comment]
@Trivias91 are you referring to `UpdateToolbarItems` ?

**Comment by Trivias91** [comment]
@PureWeen Yes, I believe the problem is in `UpdateToolbarItems`.  The actual problem is that `UpdateToolbarItemIcons`  is never used so you can't override it to modify the icons, but it seems like `UpdateToolbarItems` is where it should be used.

**Comment by PureWeen** [comment]
Can you send me a link to `UpdateToolbarItemIcons`? I'm not finding anything in the code base with that name

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
