### ISSUE TITLE
[Bug] SwipeView on UWP Executes Command Twice

### ISSUE THREAD

**Issue by tdoell** [xamarin/Xamarin.Forms#11251]
### Description
When using SwipeView on UWP and a SwipeItem `Command` is executed, the `Command` is executed twice.

### Steps to Reproduce

1. Run Xamarin.Forms UWP app
2. Swipe from right->left (touchscreen monitor only...)
3. If `SwipeItems.Mode` is set to **Reveal**, tap cell, other wise swiping across should executed command
4. `Debug.WriteLine` in Command is printed **twice**

### Expected Behavior
SwipeItem `Command` is executed **once** when Mode is set to **Reveal** or **Execute**

### Actual Behavior
SwipeItem `Command` is executed **twice** when Mode is set to **Reveal** or **Execute**

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP: 16288  
- Affected Devices: UWP

### Reproduction Link

[SwipeViewMultipleExecuteUWP.zip](https://github.com/xamarin/Xamarin.Forms/files/4853954/SwipeViewMultipleExecuteUWP.zip)

### Workaround

One of the multiple ways to work around this issue is to ignore a second execution of the command during a certain time interval, but this is not an ideal solution.

**Comment by samhouts** [comment]
closed by #11323
