### ISSUE TITLE
Button events Press and Release are unusable on Xamarin.Forms for iOS 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11267]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1091669/button-events-press-and-release-are-unusable-on-xa.html)._

---
Xamarin.Forms 4.7.0.968.
Button Press event on iOS (iPadOs 13.5.1) is raizing too late, actually together with Release event .
That is unacceptable. 

According to Xamarin.Forms documentation that should be two separate events.
There are no special comments that these events are not working properly on iOS.

On Android Press and Release are working fine.

---
#### Visual Studio Feedback System on 6/27/2020, 07:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
