### ISSUE TITLE
Xamarin forms UWP project click event does not take into account scroll position

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11268]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1092778/xamarin-forms-uwp-project-click-event-does-not-tak.html)._

---
This is a very serious problem preventing me from updating my app in the UWP store.
Introduced probably when updating XF or Visual Studio
Only present on UWP, android still works fine.

Reproduction:
- start with a view that has a scrollcontainer and a clickable item
- scroll down
- click in the ui
- the click does not register on position of the mouse pointer, but on the location of the mouse pointer where it would have been when you have scrolled all the way to the top. (so, the click is not taking into account the delta Y of the scrolling).

I added a screen recording wich visualises the problem better that the text above.
I also added a vs recording (just so you have my system details)

This happens on multiple screens in my app. The simplest one is this one:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage  xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="BB.App.ViewModels.InitialSetupView"       
             xmlns:yummy="clr-namespace:Xamarin.Forms.PancakeView;assembly=Xamarin.Forms.PancakeView"
             xmlns:viewModels="clr-namespace:BB.App.ViewModels;assembly=BB.App"
             NavigationPage.HasNavigationBar="False"
              xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
                            ios:Page.UseSafeArea="True"
              >
    <ScrollView Orientation="Vertical" >
        <Grid >
            <StackLayout VerticalOptions="Center" HorizontalOptions="Center" WidthRequest="600" Margin="20">
                
                <viewModels:BBHeaderView BindingContext="{Binding BBHeaderViewModel}" ></viewModels:BBHeaderView>
                <Label  FontSize="Medium" Text="Welkom bij BookaBooka, dé prentenboeken voorlees app. Met BookaBooka heb je een bibliotheek aan prentenboeken tot je beschikking op je telefoon, tablet en computer (ook offline). Lees voor aan je kinderen, of besteed het voorlezen even uit aan een van de voorleesstemmen. Voordat je aan de slag gaat met BookaBooka vragen we je aandacht voor de volgende onderwerpen:" />

                <Label  FontSize="Large" FontAttributes="Bold" Text="Copyright" ></Label>
                <Label  FontSize="Medium" Text="BookaBooka toont auteursrechtelijk beschermd materiaal. Het is niet toegestaan om beeldmateriaal of teksten ergens anders te gebruiken dan binnen BookaBooka." />

                <Label  FontSize="Large"  FontAttributes="Bold" Text="Jouw data"/>
                <Label  FontSize="Medium">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="BookaBooka hecht waarde aan de privacy van jou en je kinderen. We verzamelen een minimale hoeveelheid gebruiksgegevens om inzicht te krijgen in hoe de app gebruikt wordt zodat we BookaBooka kunnen verbeteren. Ook verzamelen we gegevens over leesgedrag zodat we de rechthebbenden van het materiaal naar rato van leesgedrag uit kunnen betalen. De verzamelde gegevens zullen we niet delen met derden. Lees er meer over in "/>
                            <Span Text="onze privacy policy" TextDecorations="Underline">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapUrlCommand}" CommandParameter="https://www.brainbro.nl/privacy" />
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text="."/>
                        </FormattedString>
                    </Label.FormattedText>
                </Label>
                <Label  FontSize="Large" FontAttributes="Bold" Text="Vragen"/>

                <Label  FontSize="Medium">
                    <Label.FormattedText>
                        <FormattedString>
                            <Span Text="Heb je een vraag? We helpen je graag. Stuur een mailtje naar "/>
                            <Span Text="****@yyy" TextDecorations="Underline">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding TapUrlCommand}" CommandParameter="mailto://****@yyy" />
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text=" of gebruik het feedback formulier in BookaBooka."/>
                        </FormattedString>
                    </Label.FormattedText>
                </Label>
                <StackLayout Orientation="Horizontal" HorizontalOptions="Center" Padding="0,20,0,10">
                    <CheckBox HeightRequest="25" WidthRequest="25" Color="#71c4fe" IsChecked="{Binding UserAgreedWithPrivacyStatement}"></CheckBox>
                    <Label  Text="Ik ga akkoord" FontSize="Large" FontAttributes="Bold">
                        <Label.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding SwitchUserAgreedWithPrivacyStatementCommand}"></TapGestureRecognizer>
                        </Label.GestureRecognizers>
                    </Label>
                </StackLayout>
                <Grid>
                    <yummy:PancakeView Style="{StaticResource InactiveButtonPancake}"  IsVisible="{Binding DisabledButtonVisible}">
                        <Label HorizontalOptions="Center" VerticalOptions="Center" TextColor="White" Text="Verder gaan" FontSize="Large" ></Label>
                    </yummy:PancakeView>
                    <yummy:PancakeView Style="{StaticResource ActiveButtonPancake}" IsVisible="{Binding EnabledButtonVisible}">
                        <yummy:PancakeView.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding TapEnabledAgreeButtonCommand}"></TapGestureRecognizer>
                        </yummy:PancakeView.GestureRecognizers>
                        <Label HorizontalOptions="Center" VerticalOptions="Center" TextColor="Black" Text="Verder gaan" FontSize="Large" ></Label>
                    </yummy:PancakeView>
                </Grid>
            </StackLayout>
        </Grid>
    </ScrollView>

</ContentPage>

---
#### Visual Studio Feedback System on 6/27/2020, 08:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
This might be a duplicate of #11106. Please try the latest version of 4.7.0.1080 published today.

**Comment by sjorsmiltenburg** [comment]
I confirm that upgrading to .1080 fixed my problem

**Comment by samhouts** [comment]
Duplicate of #11106
