### ISSUE TITLE
[Bug] ControlTemplate Causes crash on Android and iOS when resources are defined in child

### ISSUE THREAD

**Issue by ymebrugts** [xamarin/Xamarin.Forms#11260]
### Description
When using a Controltemplate in a Parent child relationship the Keys in the parent are no longer found by the child when defining resources in the child, resulting in a crash.

I think this is a bug? 

### Steps to Reproduce

1. ContentPage base class with controltemplate
2. Child in xaml ControlTemplate="{StaticResource CrashTemplate}"
3. Child implement resources
4. Crash on iOS and Android

### Expected Behavior
Key found and loads ControlTemplate.

### Actual Behavior
![devenv_X1ivlMcuda](https://user-images.githubusercontent.com/36673314/86249617-d1197980-bbaf-11ea-8172-c5377f8ccd34.png)
Crash
### Basic Information

- Version with issue: 4.7
- Platform Target Frameworks: 
  - iOS:  13
  - Android: 10

### Reproduction Link
[ControlTemplateCrashRepo.zip](https://github.com/xamarin/Xamarin.Forms/files/4858559/ControlTemplateCrashRepo.zip)

**Comment by ymebrugts** [comment]
Was anybody able to reproduce this? I'm wondering if this is a bug or if this is a quirk that you can work around.

**Comment by StephaneDelcroix** [comment]
Short story: not a bug.

You're setting some resources in BasePage, then in LastPage you OVERRIDE the Resources property. At that time, indeed, the CrashTemplate is gone, and nowhere to be found.

This is one of the reason why the concept of Xaml basepage is usually a bad idea, and should be replaced by ControlTemplate. You could fix your code by defining the template at the app or shell level
