### ISSUE TITLE
Xamarin.Form style:ListItemDetailTextStyle  not dapting to darkmode on iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11269]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1094487/xamarinform-stylelistitemdetailtextstyle-not-dapti.html)._

---
In a Xamarin.Forms project.

When using a ListView, I use the style: style:ListItemDetailTextStyle  

The code looks lke : 
       <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Padding="10">
                            <Label Text="{Binding Description}" 
                                LineBreakMode="NoWrap"
                                Style="{DynamicResource ListItemDetailTextStyle}"
                                FontSize="16" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>

However the text commes out black. It's finewhen dark mode is't activated, but when darkmode is activated it would be nice for it to turn the text white

---
#### Visual Studio Feedback System on 6/29/2020, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by scarrier92** [comment]
The master-detail app template in visual studio 2019 is a good example of it

**Comment by rmarinho** [comment]
Do you mind post some screenshots to help us understand better the issue? 

Also the code you posted for the ItemTemplate  is empty

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
