### ISSUE TITLE
>	PaymentTest.UWP.exe! PaymentTest.UWP.App.InitializeComponent.AnonymousMethod__5_0(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) Line 53	C #

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11265]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1090795/-paymenttestuwpexepaymenttestuwpappinitializecompo.html)._

---
[regression] [worked-in:16.7.0 preview 2]
I have recently created a Xamarin forms Mater Details app using Version 2019 and it was working with the 16.7.2 preview.

However using the 16.7.0 preview 3, the UWP app dies on starting with an exception

Message	"Method not found: 'Windows.UI.Composition.CompositionGeometricClip Windows.UI.Composition.Compositor.CreateGeometricClip(Windows.UI.Composition.CompositionGeometry)'."	string

The call stack is 

PaymentTest.UWP.exe! PaymentTest.UWP.App.InitializeComponent.AnonymousMethod__5_0(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) Line 53	C#

The android build of the app is Fine.

---
#### Pat Moran on 6/27/2020, 08:01 AM: 

<p>I have now tried the app using VS 16.7.0 Preview 3.1.</p><p>The problemoccurs when I use Xamarin.Forms 4.7.0.968.</p><p>It works as expected using Xamarin.Forms 4.6.0.967</p>

#### Visual Studio Feedback System on 6/27/2020, 11:08 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
closed by #11271
