### ISSUE TITLE
[Bug] XF for Mac: Nested elements with tap gestures, both fire when inner view is tapped

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#11273]
### Description
Given nested elements with tap gestures, both fire when inner view is tapped
### Steps to Reproduce

Add a stack layout with a tap gesture.
Add a view to the stack layout with a tap gesture.

Run.

Click the inner view. Both tap gestures trigger. This works for on iOS and Android.

### Expected Behavior
Only the inner tap gesture should trigger.

### Actual Behavior
Both tap gestures trigger.

### Basic Information

- Version with issue: XF 4.5.0.657 and above (also tried with 4.7.0.1080, same issue)

- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround
None

**Comment by JohnHDev** [comment]
@samhouts thought you might appreciate a demo for this as well. :)

[XF4iOSAndroidMacDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4866195/XF4iOSAndroidMacDemo.zip)

Run the Mac project
Tap the blue area, frame2 goes to console.
Tap the red area, frame1 and frame 2 both go to console.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
