### ISSUE TITLE
I updated to 4.6 and now iOS does not apply styles, colors and fonts to labels.

### ISSUE THREAD

**Issue by ArvindSJoshi** [xamarin/Xamarin.Forms#11275]
### Description
After updating to 4.6 my labels don't work properly in iOS.

If I have a label with Style="{StaticResource Blue1_Font16_Book}" and Text="{helpers:StringResource lblTimeCardSummaryGuideHint}" the style is not applied. It also does not work if the text is hardcoded. (StringResource is a markup extension that returns the value for the key passed to it.)

However, if the label is changed as follows: Style="{StaticResource Blue1_Font16_Book}" Text="{Binding lblTimeCardSummaryGuideHint}" />" the style is applied.

### Steps to Reproduce

1. Create a content page and add a Label with hardcoded text value.
2. Assign a text color, font family and font size.
3. Add another label where the text value is bound to a variable in VM.
3. Load the page.

### Expected Behavior
Both labels should display based on style elements.

### Actual Behavior
The label with hardcoded values ignores the style elements.
The label with bound values correctly displays the style elements.

### Basic Information

- Version with issue: > Xamarin Forms 4.5
- Last known good version: Xamarin Forms 4.4

- IDE: Visual Studio 2019 for Mac
Visual Studio Community 2019 for Mac
Version 8.4.8 (build 2)

- Platform Target Frameworks: 
  - iOS:  13.14
Xamarin.iOS
Version: 13.14.1.24 (Visual Studio Community)
Build date: 2020-01-28 19:38:52-0500

  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/12858464/86293733-da5b1400-bbb8-11ea-9e8a-a1d989124af5.png)
![image](https://user-images.githubusercontent.com/12858464/86293760-e646d600-bbb8-11ea-8484-f9e97f82569a.png)

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by StephaneDelcroix** [comment]
> Thanks for this report.
> 
> Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

@ArvindSJoshi we're still waiting for a reproduction of the bug

**Comment by ArvindSJoshi** [comment]
This issue has to do with Pendo SDK. Pendo SDK version we have does not work perfectly with more recent versions of Xamarin Forms. They have provided us a solution.
