### ISSUE TITLE
[Enhancement] Add Android platform specific to disable IncludeFontPadding

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11277]
### Description

i have this label wit below style

```
 <Style
                x:Key="ActiveNumberIndicator" 
                TargetType="Label">                
                <Setter Property="TextColor" Value="#FF000000" />
                <Setter Property="HeightRequest" Value="40"/>
                <Setter Property="FontSize" Value="40"/>
                <Setter Property="FontAttributes" Value="Bold"/>
                <Setter Property="WidthRequest" Value="71"/>
                <Setter Property="VerticalOptions" Value="Start"/>
                <Setter Property="LineBreakMode" Value="WordWrap"/>  
                <Setter Property="HorizontalOptions" Value="End"/>
                <Setter Property="HorizontalTextAlignment" Value="End"/>
                <Setter Property="VerticalTextAlignment" Value="Start"/>
                <Setter Property="BackgroundColor" Value="Yellow"/>
            </Style>

 <Label  Text="12"
                         Style="{StaticResource ActiveNumberIndicator}"/>
             
```

height and fontsize are both 40. so i expect that 12 number should be displayed or fit automatically. First I didnt use VerticalTextAlignment at all and result was as below on Android

![image](https://user-images.githubusercontent.com/10422347/86308460-90eee100-bc19-11ea-9915-34de9c47d4a8.png)

You can see from the backgroundcolor, text doesnt start vertically. I tried to apply VerticalTextAlignment = Start. it doesnt have any affect

On UWP it works fine as expected. I didnt test on IOS.
![image](https://user-images.githubusercontent.com/10422347/86308396-63099c80-bc19-11ea-8e32-776103f237ff.png)

### Steps to Reproduce

1. Use the code above
2. 
3. 

 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
   - Android: 9 and 10 
- Android Support Library Version: 
- Nuget Packages: XF 4.7

**Comment by rmarinho** [comment]
The values for HeightRequest is not the same as FontSize .

If you remove HeightRequest from the style it should work as expected.

**Comment by rmarinho** [comment]
Can you tell us if removing the HeightRequest  works for you ? 

Thanks

**Comment by EmilAlipiev** [comment]
it solves the problem of truncating the text vertically but it still doesnt solve the actual problem. Although I set    `<Setter Property="VerticalOptions" Value="Start"/>`
text is vertically in the Center of the label. 

![image](https://user-images.githubusercontent.com/10422347/86496884-88181f80-bd7f-11ea-8b6b-4dcbf11128fc.png)

**Comment by PureWeen** [comment]
@EmilAlipiev This is an interesting one. So the problem here is that android by default includes a font padding `includeFontPadding` which is what causes the font to offset outside of that container 

You can create a custom renderer to disable this on the labels. 

```
[assembly: ExportRenderer(typeof(Label), typeof(CustomLabelRenderer))]
namespace aawefwef.Droid
{
    public class CustomLabelRenderer : LabelRenderer
    {
        public CustomLabelRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
        {
            base.OnElementChanged(e);

            Control.SetIncludeFontPadding(false);
        }
    }
}
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
