### ISSUE TITLE
[Bug] Page left in stack?

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Xamarin.Forms#11281]
### Description

If we are 

1. on page A (ctor called) in shell and we

1. navigate to page B (ctor called) using absolute route (//B)

1. then again to A (ctor not called) with (//A)

Constructor of page A is called only once. Why is that? 
I would assume that when navigating with absolute route all of the pages before would be disposed. Especially since if we try to go back we won't go to previous page but instead the app will close (talking about physical back button on android)

Can't find anything about this behaviour in docs so just wanted to get some clarification.

Thanks

**Comment by PureWeen** [comment]
@domagojmedo 

I have an issue here to start addressing this
https://github.com/xamarin/Xamarin.Forms/issues/6855#issuecomment-591721930

When you  navigate between different ShellContents the pages dispose. The renderers dispose but the Page stays instantiated on the ShellContent

You can use OnAppearing to fire logic when a contentpage is coming back into view for a user

There are a lot of different permutations here of what people could want as you navigate around shell routes so we'll need a way to articulate
