### ISSUE TITLE
DynamicResource not working in  Xamarin Forms Switch

### ISSUE THREAD

**Issue by AnandRaj32** [xamarin/Xamarin.Forms#11284]
### Description

When setting color through DynamicResource markup extension in AppThemeBinding for Switch, makes the appearance doesn't match the provided color. In the case of  StaticResource, it is working fine.

### Steps to Reproduce

1. Run the Sample and you can see the output.

### Expected Behavior

Color should change based on the provided values.

### Actual Behavior

Color does not match with the provided values.

### Basic Information

- Version with issue: 4.7.0.968
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  iOS Simulator version 13.3
  - Android: Android OS Version 10

### Reproduction Link

[Themes.zip](https://github.com/xamarin/Xamarin.Forms/files/4864610/Themes.zip)

**Comment by rmarinho** [comment]
I m having troubles getting this to build , is it using synfusion ? 

```
Failed to resolve assembly: 'Syncfusion.Core.XForms, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'	MarkupExtensions	C:\Samples\Themes\MarkupExtensions\MarkupExtensions\App.xaml	
```

**Comment by StephaneDelcroix** [comment]
DynamicResource can only be applied to BindableProperties, and AppThemeBinding Light and Dark are not bindable. This is not supposed to work, and will probably never. I'm sure there's a way to express your styles in a way that doesn't require using AppThemeBinding to a DynamicResource...
