### ISSUE TITLE
[Bug] Fix the ContolGallery for UWP

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11288]
### Description

I am getting error on Ellipse not found on EllipseGallery. I dont get how can something can be merged with an error.
I have deleted code on this page to see if it is working. this time it crashes on run time with the below exception message.
I dont understand which file this should be

`Failed to assign to property 'Windows.UI.Xaml.ResourceDictionary.Source' because the type 'Windows.Foundation.String' cannot be assigned to the type 'Windows.Foundation.Uri'. [Line: 10 Position: 25]`

**Comment by hartez** [comment]
Have you tried doing a `git clean -fxd` before building the Gallery?

**Comment by samhouts** [comment]
Yep, I had this yesterday on VS Mac. `git clean -fdx` worked for me.

**Comment by EmilAlipiev** [comment]
@hartez thanks. this fixed first problem with Elipse but crash is still there. After cleaning rebuilding restarting VS, crash persists

![image](https://user-images.githubusercontent.com/10422347/86389270-5b3c0d80-bc96-11ea-842d-dfc2a3cd2c98.png)

**Comment by EmilAlipiev** [comment]
I am guessing that it has something to do with App.xaml of UWP project with line Resources.xbf.
Although i executed /.create-stubs.bat to create those, yet exception persists


```
	<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.MergedDictionaries>
				<ResourceDictionary Source="ms-appx:///Xamarin.Forms.Platform.UAP/Resources.xbf" />
			</ResourceDictionary.MergedDictionaries>
		</ResourceDictionary>
	</Application.Resources>

```

**Comment by rmarinho** [comment]
What branch are you using ? 

Is this happening just  opening the sln on VS windows and run the gallery? Or you are using scripts?

**Comment by EmilAlipiev** [comment]
no when i run it in debug mode on uwp. i get every time this crash on the image

**Comment by rmarinho** [comment]
I just tested again, i checkout main, and open vs2019, and control gallery builds fine.

![image](https://user-images.githubusercontent.com/1235097/86475719-1a4b0400-bd3d-11ea-962d-58f504d5386f.png)

**Comment by EmilAlipiev** [comment]
it seems that something went wrong with my local source code. i have just deleted all my clone and recloned it and it worked fine. thanks for pointing out and sorry for bothering :)
