### ISSUE TITLE
AppShell SetTabBarIsVisible behaviour is overwritten during navigation 

### ISSUE THREAD

**Issue by DaveBrickley** [xamarin/Xamarin.Forms#11296]
# Description

Having chosen to hide the tab using the above property, I noticed a repeatable use case in which it is presented back to the user

### Steps to Reproduce

1. Using this example project as reference https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals
2. In the Init method for AppShell, add the line SetTabBarIsVisible(this,false)
3. Run the app and note that the tab bar is hidden
4. Select Monkeys, navigate to three of four of the child pages of this list
5. Open the flyout and choose the About option (it must be this one as it's a ShellContent item that exists outside of the FlyoutItem grouping in the example)
6. Return to Monkeys, note that the tab is now visible at the foot of the page

### Expected Behavior

Having chosen for the tab bar to be invisible, it should never be visible to the user 

### Actual Behavior

If you navigate in the correct sequence defined in the steps above (note the importance of building up a navigation stack of pages from within a FlyOut item, then selecting an option outside the FlyoutItem, then returning to it) the tab bar reverts to visible

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: n/a
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  13.5

- Affected Devices: iOS simulator

### Reproduction Link

Here is a video demonstrating the issue
https://youtu.be/kTm_rLfab6A

### Workaround

No, it makes no difference if you add the method to OnAppearing rather than just Init

**Comment by rmarinho** [comment]
Same issue even using 5.0.0 nightly

**Comment by rmarinho** [comment]
This was fixed on #11243 you can grab a 4.7.0.1080 that has this fix
