### ISSUE TITLE
[Bug] Global shell route gets stuck on navigation stack when replacing stack and returning to it later

### ISSUE THREAD

**Issue by vincent-vm** [xamarin/Xamarin.Forms#11293]
### Description

When navigating away from a global route, then returning to a visual hierarchy route that the global route was sitting on top of, the routing system gets shunted to the global route rather than the requested route.

### Steps to Reproduce

1. Set up two regular ShellContents for routes "page1" and "page3" in the visual hierarchy in AppShell.xaml
2. Set up page2 as a global route through Routing.RegisterRoute("page2") in AppShell code behind
3. Set Shell.PresentationMode="Animated" on all pages (none are modal)
3. Let page1 be the first ShellContent in the visual hierarchy, and observe page1 opening when the app starts
4. Press a button on page1 that calls GoToAsync("//page1/page2") and observe page2 opening "on top" of page1, with a back button in the nav bar to take you back to page1 if needed
5. Press a button on page2 that calls GoToAsync("//page3") and observe ending up on page3
6. Press a button on page3 that calls GoToAsync("//page1") and observe ending up on page2 (not page1)

### Expected Behavior

Calling GoToAsync("//page1") should route me to "//page1"

### Actual Behavior

Calling GoToAsync("//page1") actually takes me to "//page1/page2"

### Further Details

My understanding is that when I navigate to //page3 from //page1/page2 the whole navigation stack is removed. Similarly the call to //page1 should again remove the previous navigation stack. In fact, it seems to have returned to the original stack with page2 still sitting on top.

I've overridden OnNavigating and OnNavigated to print out the destination/current route. You can see the router getting confused somewhere in between the two, as OnNavigating prints out "//page1" but by the time we get to OnNavigated it says "//page1/page2".

### Basic Information

- Version with issue: 4.7.0.1080
- IDE: VS2019
- Platform Target Frameworks:
  - iOS:  13
  - Android: 10

### Reproduction Link

Very basic solution with the 3 pages in that demonstrates the problem:
[RoutingBugRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4866893/RoutingBugRepro.zip)

### Workaround

There's a few workarounds, but none of them desirable:
1. Make page2 modal and the problem does not occur. Unfortunately, I don't want page2 to be modal and would like the navbar and back button on page2.
2. Calling GoToAsync("//page1") twice in a row does properly take me to //page1, but you can see the double transition (page3 transitioning to page 2, then page2 to page1).
3. When going from page2 to page3 you can do GoToAsync("..") then GoToAsync("//page3"), which prevents the problem later, but again you can see the double transition when going from page2 to page3 (through page1).

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/6855#issuecomment-591721930
