### ISSUE TITLE
[Bug]  IsClippedToBounds not clipping Image when inside a Frame

### ISSUE THREAD

**Issue by CarrotSolutions** [xamarin/Xamarin.Forms#11291]
### Description
Place any image inside a frame and use IsClippedToBounds.  The image is not clipped.  In the latest release 4.7.0.1080, you fixed the background color clipped (GitHub #11031) but not the image clipped.  

### Steps to Reproduce
1.  Put in XAML file

                <Frame
                    Margin="0,5,0,0"
                    Padding="0"
                    BorderColor="Red"
                    CornerRadius="50"
                    HasShadow="False"
                    HeightRequest="100"
                    HorizontalOptions="Center"
                    IsClippedToBounds="True"
                    VerticalOptions="Center"
                    WidthRequest="100">
                    <Image
                        Margin="0"
                        Aspect="AspectFill"
                        HeightRequest="100"
                        HorizontalOptions="Center"
                        Source="dog.png"
                        VerticalOptions="Start"
                        WidthRequest="100" />
                </Frame>

### Expected Behavior
Image is clipped

### Actual Behavior
Image is not clipped 

### Basic Information
VS 2019 Xam 4.7.0.1080

**Comment by jsuarezruiz** [comment]
@CarrotSolutions This issue is the same as #11091. Will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/11129
I have included a test to validate your case:
<img width="391" alt="Issue11291" src="https://user-images.githubusercontent.com/6755973/86453459-18be1380-bd1e-11ea-9b88-c6ff1570b7e8.png">

**Comment by sameermdkhan** [comment]
We also faced the same issue. We temporarily fixed using the new Image.Clip feature in Xamarin 4.7 as follows
    <Image Aspect="AspectFill"
           HeightRequest="100"
           WidthRequest="100">
        <Image.Clip>
            <EllipseGeometry Center="50,50" RadiusX="50" RadiusY="50"/>
        </Image.Clip>
    </Image>

**Comment by sameermdkhan** [comment]
We also faced similar issue after upgrading to Xamarin Forms 4.7. We fixed it using new Image.Clip feature introduced in 4.7 as follows (which is much shorter & simpler than earlier approach of using Frames)
![image](https://user-images.githubusercontent.com/56313042/86851704-0999e580-c0d1-11ea-8e36-590a41b80ff5.png)

**Comment by CarrotSolutions** [comment]
Unfortunately you cannot add a border to the Image with Image.Clip without a couple of workarounds.  Hence why we need the frame to work properly.

**Comment by samhouts** [comment]
closed by  #11129
