### ISSUE TITLE
[Build] Cannot debug my nuget package

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/Xamarin.Forms#11294]
### Description
Cannot debug my nuget package

### Steps to Reproduce

1. follow https://devblogs.microsoft.com/xamarin/debugging-xamarin-forms/ build source and get Xamarin.Forms.xx.nupkg,
source version : Xamarin.Forms-release-4.2.0-rc1;
nuget version : 5.0.2;
visual studio version:Visual Studio Professional 2017 15.9.2
pack command : nuget.exe pack Xamarin.Forms.nuspec -properties configuration=debug;platform=anycpu -Version 9.9.2.1000
2. use in project and debug,cannot into source:
![image](https://user-images.githubusercontent.com/1481403/86426293-e3172b80-bd19-11ea-8dd0-c27dc7d48da4.png)

3. I Have unchecked follow project in vs2017:
![image](https://user-images.githubusercontent.com/1481403/86426416-36897980-bd1a-11ea-93e0-f12a1d8ca75d.png)

4.nuget cache:
![image](https://user-images.githubusercontent.com/1481403/86426627-b7e10c00-bd1a-11ea-8cf8-4663d22f1821.png)

### Expected Behavior
can step into xamarin forms core source

**Comment by VladislavAntonyuk** [comment]
have you enabled debugging option in Visual Studio?

**Comment by rmarinho** [comment]
Hi @llzz19851985 that post is a bit old , i think that might not be as updated as we want. 

can you take a look at @PureWeen 's blog that as some tips for debugging Xamarin:Forms and tells how that went? 

https://shaneneuville.com/

thanks

**Comment by llzz19851985** [comment]
@rmarinho OK，I will try,thanks!

**Comment by llzz19851985** [comment]
@rmarinho It works ,thank you very much,it save me a lot of time! 
by the way,is there a document to explaining how this work ?
thank you !
