### ISSUE TITLE
[Bug] Shell Tab Icons Not Rendered On Load

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#11309]
### Description

When the application is first loaded, the icons on a Shell's tab's do not appear.  Selecting a tab will make them appear.

### Steps to Reproduce

1. Download the [Xanimals source](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals) to use as an **example**.
2. Run the application.  (Tested on UWP and Android)
3. The icons will be blank.
4. Select the Monkeys tab.
5. Tab icons will render.

### Expected Behavior

Icons should be visible on initial load.

### Actual Behavior

Icons are not visible until you change views.

### Basic Information

- Version with issue: 4.7.0.968
- Last known good version: unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 9.0
  - UWP:  18362

### Screenshots

Initial load.
![image](https://user-images.githubusercontent.com/4465616/86500952-77a17e00-bd5a-11ea-9625-f083aa2b2633.png)

After switching views.
![image](https://user-images.githubusercontent.com/4465616/86500966-825c1300-bd5a-11ea-85ae-204280ee5cf3.png)

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

**Comment by PureWeen** [comment]
@scottkuhl what are the specs on the device you are testing? API Level etc... ?

I tested the Xaminals sample locally and for me the icons load fine on initial load
I tested on an API 29 and API 23 device

**Comment by scottkuhl** [comment]
I think you are onto my problem.  I was testing on a Pixel 3a until it died.  Now I have been using the latest Surface Duo Emulator and that is where the problem is.

I wondered how such an important feature could have slipped through the cracks.  This explains it.

Thanks for your help, I'll close the ticket and start a hunt for a new Android device.
