### ISSUE TITLE
[Enhancement] Navigation - Insert modal into the modal stack, just like InsertPageBefore for the navigation stack

### ISSUE THREAD

**Issue by bruzkovsky** [xamarin/Xamarin.Forms#11302]
## Summary
I want to insert a modal before the currently shown modal, so that when I go back, I land on the inserted modal.

## API Changes

To achieve this, I'd like to have an additional method on the `INavigation` interface like this:

```c#
var topModal = Navigation.ModalStack.Last();
Navigation.InsertModalBefore(new MyModalPage(), topModal);
```

**Comment by bruzkovsky** [comment]
I started on implementing this and already got some good results on android, using this code...
```c#
var topmostModal = CreatePage("I am the topmost modal!");
await Navigation.PushModalAsync(topmostModal);
Navigation.InsertModalBefore(CreatePage("I am wedged in-between!"), topmostModal);
```
...results in this:
![xf-11302-insert-modal-before](https://user-images.githubusercontent.com/10390959/86580528-23c3ae80-bf7f-11ea-81e1-2eb3dea3e6f0.gif)

So far, so good. iOS seems a bit more tricky but I will elaborate on that later. Can anyone tell me if it is possible to present a UIViewController "behind" an already presented one?

**Comment by bruzkovsky** [comment]
On iOS, I get the following message when I try to present the modal from the initial `UIViewController` while the other modal is already presented "above".

```
Warning: Attempt to present <Xamarin_Forms_Platform_iOS_ModalWrapper: 0x108240710> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x1188556d0> whose view is not in the window hierarchy!
```

Note how it says "window hierarchy" and not "on top". So maybe the view gets kicked out of the hierarchy? The first modal was presented fine from `<Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x1188556d0>`.

Is there someone experienced with the iOS window hierarchy who can help me out?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
