### ISSUE TITLE
[Bug] TabbedPage on Android: Bottom navigation with more than 5 entries causes IndexOutOfBoundsException on clearing

### ISSUE THREAD

**Issue by DDHSchmidt** [xamarin/Xamarin.Forms#11301]
### Description
Tabbed navigation page under Android throws an exception, when the following prerequisites happen:

- Use tabbed navigation
- Use more than 5 Content pages
- Place tab navigation at bottom via attribute android:TabbedPage.ToolbarPlacement="Bottom" (Causes "More" button to appear)

When you try to clear the pages again (e.g.: In a logout scenario), the app crases with an IndexOutOfBoundsException

### Steps to Reproduce

1. Use tabbed navigation
2. Use more than 5 Content pages
3. Place tab navigation at bottom via attribute android:TabbedPage.ToolbarPlacement="Bottom" (Causes "More" button to appear)
4. Clear the 6+ Content pages from the TabbedPages's ItemsSource

### Expected Behavior
All of the content pages are removed

### Actual Behavior
Application throws IndexOutOfBoundsException

### Basic Information

- Version with issue: 4.7.0.1080
- Last known good version: -
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: Tested against 9.0

### Reproduction Link
I threw together a small repro project: [AndroidTabbedPagesException.zip](https://github.com/xamarin/Xamarin.Forms/files/4869586/AndroidTabbedPagesException.zip)

On the "Login page" you can determine how many content pages you want to create (1-6).
Afterwards you can logout, which will clear all content pages from the TabbedPage.
Anything below 6 will work fine, but if you choose 6 Content pages, the bug will be triggered on logout.

**Comment by rmarinho** [comment]
Same issue even using 5.0.0 nightly
