### ISSUE TITLE
[Enhancement] Add ToolTip and ToolTipPlacement properties

### ISSUE THREAD

**Issue by Symxn** [xamarin/Xamarin.Forms#11306]
## Summary
In Xamarin.Forms it is not yet possible to display ToolTips. These are small labels with information for the user, which are displayed when the user presses a view for a short time.

## API Changes

- Add a property named **ToolTip** of type string and add it to _VisualElement_ class.
- Add a property named **ToolTipPlacement** of type ToolTipPlacement and add it to _VisualElement_ class.
- Add an enum named **ToolTipPlacement**:

```
    public enum ToolTipPlacement
    {
        Below = 0,
        Above = 1,
        Left = 2,
        Right = 3,
        TopLeft = 4,
        TopRight = 5,
        BottomLeft = 6,
        BottomRight = 7
    }
```

- Add platform specific implementations.

## Examples

    <BoxView ToolTip="More options"
             ToolTipPlacement="Below"></BoxView>

_or_

    <ImageButton Source="Mail.png"
                 BackgroundColor="Pink"
                 ToolTip="Send an email"
                 ToolTipPlacement="Above"></ImageButton>

**Result:**

![ToolTip](https://user-images.githubusercontent.com/37656980/86495662-9879cb80-bd7a-11ea-848c-0991c20509fe.png)

**Comment by mhrastegary77** [comment]
Geate proposal, i think you should move this to .net maui 🤔

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

I see something is already opened for .NET MAUI so be sure to add your upvote there if this is still important to you!
