### ISSUE TITLE
[Enhancement] Image control shouldn't try to load any image when Source is null or empty.

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#11308]
## Summary
Image controls with invalid file names slow down execution of a program (at least in Android, debug mode); I presume exceptions are thrown, also debug log output is generated.

## API Changes

When an Image control's Source is empty/null/whitespace, or otherwise not a proper path string, the control should not attempt to load a file using it.

## Intended Use Case
e.g. Include an optional image in a user control that is displayed repeatedly, such that there is no impact on performance if no source is provided,

**Comment by BioTurboNick** [comment]
Should this be closed as unplanned at this point?

**Comment by jfversluis** [comment]
You're absolutely right @BioTurboNick ! Thanks!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
