### ISSUE TITLE
[Bug] How to create custom switch

### ISSUE THREAD

**Issue by Shraddha996** [xamarin/Xamarin.Forms#11313]
Hello,
As am new to this platform I have no idea how to create a custom switch with text on it like this
![2](https://user-images.githubusercontent.com/39983941/86505740-2e970b80-bde6-11ea-9b90-68edda710688.PNG)

Please Help!!!!!

**Comment by EmilAlipiev** [comment]
please dont ask such questions here. it is to report bugs and enhancement not to learn xamarin.forms. go to [ Xamarin.forum](https://forums.xamarin.com/)  to ask your questions.

**Comment by StephaneDelcroix** [comment]
https://github.com/xamarin/Xamarin.Forms/discussions/11305
