### ISSUE TITLE
Please remove this line as MediaElement:PlayedToEnd event is triggered twice

### ISSUE THREAD

**Issue by justinlee0516** [xamarin/Xamarin.Forms#11315]
Please remove this line as MediaElement:PlayedToEnd event is triggered twice.

https://github.com/xamarin/Xamarin.Forms/blob/f11d0993545f71668a62f46dab4223664ce17063/Xamarin.Forms.Platform.iOS/Renderers/MediaElementRenderer.cs#L29

**Comment by samhouts** [comment]
closed by #11360
