### ISSUE TITLE
[Bug] 4.7 Embedded ttf resource doesn't work in C# code

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11310]
### Description

When I try to use below xaml code as C# code it is not working. Please find the attached repro.
Assembly[assembly: ExportFont("FontIcons.ttf", Alias = "FontIcons")]

I am using XF 4.7 and ttf is embeddedresource
```

    <ContentPage.ToolbarItems>
        <ToolbarItem >
            <ToolbarItem.IconImageSource>
                <FontImageSource Glyph="&#xe700;"
                                 Color="Orange"
                                 FontFamily="FontIcons"
                                 Size="44" />
            </ToolbarItem.IconImageSource>
        </ToolbarItem>
    </ContentPage.ToolbarItems>

```
C# 

```
 var toolBarItem = new ToolbarItem
            { 
                Order = ToolbarItemOrder.Primary,
                IconImageSource = new FontImageSource(){
                    Glyph = "&#xe700;",
                    Color = Color.Yellow,
                    FontFamily = "FontIcons",
                    Size =   44
                }
            };

```
### Steps to Reproduce

1. Run the project in Android
2. Main page has exaclty 2 ToolbarItem defined. 1 in xaml 1 in c# code behind. Xaml displays the icon from ttf, C# displays the code as text

### Expected Behavior
C# displays also the code
### Actual Behavior
Displays text 
### Basic Information

 
- Platform Target Frameworks: 
 
  - Android: 9 or 10 
- Nuget Packages: XF 4.7 latest
 
 
### Reproduction Link

[FontEmbedded 2.zip](https://github.com/xamarin/Xamarin.Forms/files/4871874/FontEmbedded.2.zip)

**Comment by PureWeen** [comment]
@EmilAlipiev specify the glyph like this in code

` Glyph = "\ue700;",`

and that should work
