### ISSUE TITLE
[Regression] CollectionView NSRangeException

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#11311]
### Description

In Xamarin.Forms v4.7.0.1080 and v4.7.0.968, on iOS, an `NSRangeException` is thrown when a `CollectionView.ItemSource` is updated:

> Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array

### Steps to Reproduce

1. Download / clone this repo: https://github.com/brminnick/CollectionViewBoundsExceptionRepro
2. In Visual Studio, open `CollectionViewBoundsExceptionRepro.sln`
3. In Visual Studio, buld/deploy `CollectionViewBoundsExceptionRepro.iOS` to an iOS Simulator or Device 
4. Confirm `NSRangeException` is thrown on launch

### Expected Behavior

CollectionView.ItemSource should update without throwing an Exception

### Actual Behavior

CollectionView.ItemSource throws `NSRangeException`

### Basic Information

- Version with issue: Confirmed on v4.7.0.1080 and v4.7.0.968
- Last known good version: v4.7.0.937-pre4
- Platform Target Frameworks: 
  - iOS:  13.20.1.18

### Screenshots

![](https://user-images.githubusercontent.com/13558917/86501165-3f467380-bd4b-11ea-9ca6-506a162cac47.gif)

### Reproduction Link

https://github.com/brminnick/CollectionViewBoundsExceptionRepro

#### Option #1. Downgrade Xamarin.Forms

Downgrade to Xamarin.Forms v4.7.0.937-pre4

#### Option #2. Remove CollectionView.Footer

Set `CollectionView.Footer = null`

1. In `CollectionViewPage.cs`, change `Footer = new BoxView { BackgroundColor = Color.Red, HeightRequest = 53 }` to `Footer = null`

https://github.com/brminnick/CollectionViewBoundsExceptionRepro/blob/8a6636d7af57f289113e800cfa0d0160cad78d6d/Src/CollectionViewBoundsExceptionRepro/CollectionViewPage.cs#L17

#### Option #3. Replace `IEnumerable<int>` with `ObservableCollection<int>`

1. In `CollectionViewModel.cs`, remove `public IEnumerable<int> ScoreCollectionList`
2. In `CollectionViewModel.cs`, remove `IEnumerable<int>? _scoreCollectionList;`
3. In `CollectionViewModel.cs`, add `public ObservableCollection<int> ScoreCollectionList { get; } = new ObservableCollection<int>()`
4. In `CollectionViewModel.cs`, in `ExecuteRefreshCommand` refactor logic for `ObservableCollection` : 

Replace this code:

```csharp
void ExecuteRefreshCommand()
{
    ScoreCollectionList = Enumerable.Range(0, 100).ToList();
    IsRefreshing = false;
}
```

with this code:

```csharp
void ExecuteRefreshCommand()
{
    foreach (var number in Enumerable.Range(0, 100))
        ScoreCollectionList.Add(number);

    IsRefreshing = false;
}
```

**Comment by mchlkoval** [comment]
I am on older xamarin version (can't just update it for now, version 4.3 iirc) and I too run into this error; however for me it is part of a ViewCell used in a data template selector; it looks like it holds onto an old reference of a view cell, and when we try to select a list view with multiple items, compared to when a previous one we just interacted with has less items we get that exception thrown.
