### ISSUE TITLE
Shell inside navigation page is not working on Android

### ISSUE THREAD

**Issue by prabakaranr** [xamarin/Xamarin.Forms#11322]
### Description
Blank page on Android if the shell is wrapped inside Navigation page.

### Steps to Reproduce

1. Run the attached sample on Android

### Expected Behavior
It should show the "Welcome to Xamarin.Forms!" text as like iOS.

### Actual Behavior
Blank screen

### Basic Information

- Version with issue: 4.5.0.495
- IDE: Visual Studio for Mac

[ShellTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4877872/ShellTest.zip)

**Comment by PureWeen** [comment]
This isn't currently a supported scenario on Shell 

What are you trying to achieve?

**Comment by prabakaranr** [comment]
I wanted to have a page that is always not visible on the screen, also it should not be visible either on bottom tabs or navigation drawer. I should be able to navigate to that page using any of the page which is hosted in Shell and navigate back to the respective Shell page.

**Comment by PureWeen** [comment]
@prabakaranr can you do thiss?

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#register-routes

**Comment by prabakaranr** [comment]
It works, I thought the page should be added to Shell UI hierarchy to navigate using routes. Thanks.

**Comment by jpozo20** [comment]
@PureWeen you say this behaviour is not supported, but it seems to be working fine on iOS. 

In my case, in Android it looks the animation is starting when moving to the shell but then it stays stuck. The weird thing is, for now, it's working fine in iOS.
