### ISSUE TITLE
[Enhancement] CollectionView ItemsLayout support for multiple layouts for grouping data

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#11325]
## Summary
Requesting support for multiple layouts for grouping data for solving such of issue when there two ways for rendering the items, vertically and horizontally 

e.g.

![image](https://user-images.githubusercontent.com/7360803/86591879-b02b9c80-bf92-11ea-8bcf-25dea90b1ae5.png)

Doing such of scrolling is really hard, so needed to add the ability to do it in much easier way.

**Comment by EmilAlipiev** [comment]
that will be nice to have but pretty hard to achieve I believe. Looking into the existing problems. we cant even properly have a single horizontal collectionview. Even this one has a lot of bugs, i think that this you can dream not soon :) 
Workaround it of course using CollectionView inside collectionview. I have seen in some of the Twitch video of James earlier. he had this view with 2 collectionview.

**Comment by AhmedAbuelnour** [comment]
@EislerDavid Actually I did it by using Stacklayout and BindableLayout it worked so fast,  I tried nested CollectionView but it was too bad in rendering it was too slow.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
