### ISSUE TITLE
[Bug] [Android] RequestedThemeChanged not called

### ISSUE THREAD

**Issue by miko1258** [xamarin/Xamarin.Forms#11330]
### Description

Hello, I can't get RequestedThemeChanged event to work on Android. On iOS works perfectly.

### Steps to Reproduce

1. Download SystemThemesDemo application
2. Add following code in contructor of the App class:
```
Application.Current.RequestedThemeChanged += (s, a) =>
            {
                // Respond to the theme change
                Console.WriteLine("Theme changed");
            };
```
3. Run application and change theme to dark/light in settings

### Expected Behavior

Application UI change and RequestedThemeChanged call

### Actual Behavior

Application UI change but RequestedThemeChanged is not called

### Basic Information

- Version with issue: 5.0.0.1105-nightly, 4.8.0.1045-nightly, 4.7.0.1080
- Last known good version:
- IDE: Visual Studio 2019 16.6.3
- Platform Target Frameworks:
  - iOS: -
  - Android: 10.0 API 29
  - UWP: -
- Android Support Library Version: -
- Nuget Packages: Xamarin.Forms
- Affected Devices: Samsung Galaxy S20+ 5G, Android x86 simulator

**Comment by jfversluis** [comment]
Above your `MainActivity` in the Android project, what type of ConfigChanges does it handle? Can you maybe paste the full attribute here? 

Or even better, a small reproduction sample that shows this problem

**Comment by miko1258** [comment]
It's app from master branch of xamarin-forms-samples. I only added event subscription.
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SystemThemesDemo

**Comment by miko1258** [comment]
Indeed this sample is missing proper attribute. Maybe it will be more clear if such information will be present in https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes#react-to-theme-changes

**Comment by jfversluis** [comment]
Very good point @miko1258 I'll see to it that we add it to the docs. Thanks!

**Comment by mike-rowley** [comment]
What is the magic fix for this issue?  I seem to be having the exact same issue, sample triggers RequestedThemeChanged on IOS but not Android.

**Comment by jfversluis** [comment]
I've created a PR on the docs page with this description:

> In order to respond to theme changes on Android, make sure that you include the `ConfigChanges.UiMode` flag in the `Activity` attribute. You can find this in your `MainActivity.cs` file of your Android project. I.e.: `[Activity(..., ConfigurationChanges = ... | ConfigChanges.UiMode)]`

Could you tell me if that's clear to you? :)

**Comment by miko1258** [comment]
@jfversluis Yes, I believe that will be clear for everyone. Thank you :)

**Comment by mike-rowley** [comment]
Thanks @jfversluis looks good to me as well!

**Comment by MagicAndre1981** [comment]
Even with `ConfigChanges.UiMode` the Event is not triggered

**Comment by MagicAndre1981** [comment]
ok, found my cause, I was still targeting API 28, but I can't upgrade to API 29/30 due to used components that are not AndroidX compatible

**Comment by ericbrunner** [comment]
I ha e tbe same issue on Android. RequestedThemeChanged is not invoked. UiMode is set

**Comment by MagicAndre1981** [comment]
check my reply @ericbrunner Which API do you target? With API 30 and VS2019 it works.

**Comment by ericbrunner** [comment]
@MagicAndre1981 @jfversluis It only works with API Level >= 30 ?

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 @jfversluis It only works with API Level >= 30 ?

you need to target at least API29-Android 10/Q as [written in the docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes):

> **The following requirements must be met for Xamarin.Forms to respond to a system theme change:**
> Xamarin.Forms 4.6.0.967 or greater.
> **Android 10 (API 29) or greater.**

**Comment by ericbrunner** [comment]
@MagicAndre1981 @jfversluis After investiation when the System Theme Change is triggered I now know why I the event is not triggered. That statement

```
			if (UserAppTheme != OSAppTheme.Unspecified)
				return;
```

prevents the event from being raise if UserTheme is already set to e.g. OsTheme.Light.

Application.cs

```
		[EditorBrowsable(EditorBrowsableState.Never)]
		public void TriggerThemeChanged(AppThemeChangedEventArgs args)
		{
			if (UserAppTheme != OSAppTheme.Unspecified)
				return;
			TriggerThemeChangedActual(args);
		}
```
and I set the Application.Current.UserTheme inside the event handler.
![image](https://user-images.githubusercontent.com/6480047/134765516-4b95775a-3f49-4069-aa66-f849308c28a6.png)
Ok I will not set UserAppTheme anymore!

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 @jfversluis After investiation when the System Theme Change is triggered I found out why the event is not triggered. That statement
> 
> ```
> 			if (UserAppTheme != OSAppTheme.Unspecified)
> 				return;
> ```
> 
> prevents the event from being raise if `Application.Current.UserAppTheme` is already set to e.g. `OSAppTheme.Light`
> 

ok, create a new issue "**RequestedThemeChanged not called if Application.Current.UserAppTheme is set**" and submit a PR with a fix for this. I never set `UserAppTheme` so I didn't noticed this.

**Comment by jl-memosoft** [comment]
Removing Application.Current.UserAppTheme also fixed my problem. It is now invoked every time when change the emulator
s display mode. Thanks @ericbrunner 

@jfversluis , maybe this needs to be added to the docs as caution? Thanks :)
