### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by guilhermereisti** [xamarin/Xamarin.Forms#11347]
### Description
ListView ItemSelected | ItemTapped is not fired when there is a ViewCell with a component with GestureRecognizer.

### Steps to Reproduce
Sample:
ListView with a label with gesture recognizer:

```
<Label Text="{Binding UrlHospedagem}" TextColor="#404041" FontSize="13" MaxLines="1" LineBreakMode="TailTruncation" FontFamily="khula-regular"
                        HorizontalOptions="StartAndExpand" VerticalOptions="Center">
                        <Label.GestureRecognizers>
                            <TapGestureRecognizer Tapped="TapUrl_Tapped" NumberOfTapsRequired="1" />
                        </Label.GestureRecognizers>
                    </Label>
```

### Expected Behavior
If we click in any item in the list, the event ItemSelected or ItemTapped should be fired.

### Actual Behavior
The event ItemSelected or ItemTapped it is not firing.

### Basic Information

- Version with issue: XF 4.7.0.1080
- Last known good version: 
- IDE: Visual Studio for Mac
- Platform Target Frameworks: Android
  - iOS:  Working
  - Android: Not working
  - UWP:  Working
- Nuget Packages: XF 4.7.0.1080
- Affected Devices: Any android

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/2180
