### ISSUE TITLE
[Bug] GTK# sandwich menu is not visible by default with Forms 4.7

### ISSUE THREAD

**Issue by Graveen** [xamarin/Xamarin.Forms#11342]
### Description
With GTK, the sandwich menu is not appearing after Xamarin.Forms upgrade.

### Steps to Reproduce

1. Use Movie sample : https://github.com/jsuarezruiz/xamarin-forms-gtk-movies-sample
2. Run Movie.GTK, it works correctly (default: Xamarin.Forms 3.1.x)
3. Update to Xamarin.Forms 4.7 via Nuget
4. Run Movie.GTk: sandwich top left icon is missing

### Expected Behavior
Menu icon visible

### Actual Behavior
Menu icon invisible

**Comment by Graveen** [comment]
Seems a duplicate of #10002

**Comment by PureWeen** [comment]
Agreed @Graveen closing this one for now
