### ISSUE TITLE
[Bug] SwipeView stopped working in Xamarin.Forms version 4.6.0.1073

### ISSUE THREAD

**Issue by KaeTar** [xamarin/Xamarin.Forms#11349]
### Description
A bug was introduced in version 4.6.0.1073 that causes swipeview to stop allowing swipe to happen.  The output view displays a bunch of this error:
"[0:] Failed to resolve SwipeViewRenderer: Resolution failed with error: Cannot create an instance of Android.Content.Context because it is an abstract class"
If I revert back to 4.6.0.967 all works fine.

### Steps to Reproduce

1. Create an xamarin.forms app with a form that has a swipeview on it and several swipe items on both sides
2. Set the Xamarin.Forms version to 4.6.0.1073 or higher
3. run app and notice that you can not swipe right or left, also notice errors in the output window saying:
[0:] Failed to resolve SwipeViewRenderer: Resolution failed with error: Cannot create an instance of Android.Content.Context because it is an abstract class

### Expected Behavior
Expected swiping left or right to work 
### Actual Behavior
Swiping does not work at all
### Basic Information

- Version with issue: 4.6.0.1073 or higher
- Last known good version: 4.6.0.967
- IDE: Visual Studio Enterprise 2019
- Platform Target Frameworks: 
  - iOS:  na
  - Android: 9.0 Pie
  - UWP:  na
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment]
I have created a sample using Xamarin.Forms 4.6.0.1073 and tried the SwipeView:
[Issue11349.zip](https://github.com/xamarin/Xamarin.Forms/files/4889558/Issue11349.zip
But cannot reproduce the issue:
<img width="2455" alt="Captura de pantalla 2020-07-08 a las 10 45 09" src="https://user-images.githubusercontent.com/6755973/86897827-39181480-c108-11ea-8fc3-723f5ea932c2.png">
Could you attach a reproduction sample?

**Comment by ccsousa01** [comment]
Same issue here only occurs on Android after updating Xamarin.Forms in Nuget from 4.7.0.968 to 4.7.0.1179.  My view tree structure is as so...

 ` <StackLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
                <RefreshView IsRefreshing="{Binding IsBusy, Mode=TwoWay}" Command="{Binding LoadAppCommand}">
                    <CollectionView x:Name="ItemsCollectionView" ItemsSource="{Binding AppList}" RemainingItemsThreshold="0" 
                      RemainingItemsThresholdReachedCommand="{Binding LoadRemainingAppCommand}">
                        <CollectionView.ItemTemplate>
                            <DataTemplate>
                                <SwipeView>
                                    <SwipeView.RightItems>
                                        <SwipeItems Mode="Reveal" SwipeBehaviorOnInvoked="RemainOpen">
                                            <SwipeItemView Invoked="SwipeItem_ApproveInvoked" CommandParameter="{Binding ID}"   
                                              HeightRequest="90" WidthRequest="90">  
                                                   .... 
                                    <SwipeView.Content>
                                        <FlexLayout JustifyContent="Start"> ....`

**Comment by PureWeen** [comment]
@jsuarezruiz
