### ISSUE TITLE
Ability to set AppThemeBinding on Styles in code

### ISSUE THREAD

**Issue by MariovanZeist** [xamarin/Xamarin.Forms#11341]
## Summary
I would like to set AppThemeBinding on Styles in code instead of being forced to use XAML

## API Changes
It would require making the AppThemeBinding class public ( again)

e.g.

## Intended Use Case
I am using Code to set a lot of options and styling. In the previous version, AppThemeColor was a public class and I could use it to populate my Setters. In the latest release, this option has been removed as AppThemeColor became AppThemeBinding and made private

If you have another way to set the Application Theme color on Styles in code I would be happy to use that, but perusing the source I couldn't find an obvious supported way.

I have a (hopefully very temporary) workaround now by using reflection to create the class and set its properties, and that works for now. But I would rather use a supported way instead of hacking it.

**Comment by jfversluis** [comment]
I think you're supposed to use the extension methods for that as described [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes#extension-methods). 

Would that be enough for your use-case? If not, why not?

Thanks! :)

**Comment by MariovanZeist** [comment]
The extension methods are great when you have concrete instances of VisualElements etc.
But they won't work when you are defining Styles in code.

Indeed you can define styles in Xaml (like the documentation says)

```
<Style x:Key="ButtonStyle" TargetType="Button">
    <Setter Property="BackgroundColor"
        Value="{AppThemeBinding Light={StaticResource LightPrimaryColor}, Dark={StaticResource DarkPrimaryColor}}" />
    <Setter Property="TextColor"
         Value="{AppThemeBinding Light={StaticResource LightSecondaryColor}, Dark={StaticResource DarkSecondaryColor}}" />
</Style>
```
But there is no equivalent of doing this in code.

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by Jinyeob** [comment]
You can do like this:
```csharp
var t = new Xamarin.Forms.Xaml.AppThemeBindingExtension();
  t.Light = lightColor;
 t.Dark = darkColor;
```
and then,

```csharp
new Setter
{
          Property = VisualElement.BackgroundColorProperty,
          Value = t
}
```

**Comment by Cfun1** [comment]
I think this will be useful and even more practical in some cases than adding a VSM

Use Case: Whenever you have a color property defined in an implicit style using AppThemeBinding, but you are changing it from the code upon some logic, if the condition is not satisfied anymore you want to set it back to a `AppThemeBinding` settings.
```
entry.TextColor = someCondition ? Color.Red : 
                                  new AppThemeBinding() { Dark= Color.White, Light= Color.Black };
```

**Comment by bigabdoul** [comment]
@MariovanZeist use AppThemeBindingExtension instead of AppThemeBinding:
```C#
var style = new Style(typeof(Page))
{
    Setters = { new Setter { Property = VisualElement.BackgroundColorProperty, Value = new Xamarin.Forms.Xaml.AppThemeBindingExtension { Dark = Color.Red, Light = Color.Blue } } }
};
```

**Comment by danielftz** [comment]
> @MariovanZeist use AppThemeBindingExtension instead of AppThemeBinding:
> 
> ```cs
> var style = new Style(typeof(Page))
> {
>     Setters = { new Setter { Property = VisualElement.BackgroundColorProperty, Value = new Xamarin.Forms.Xaml.AppThemeBindingExtension { Dark = Color.Red, Light = Color.Blue } } }
> };
> ```

I have tried this, however it does not work, as the background color stays default. I have tried both directly assigning the style property:
> labe.Style = new Style(typeof(Page))
> {
>     Setters = { new Setter { Property = VisualElement.BackgroundColorProperty, Value = new Xamarin.Forms.Xaml.AppThemeBindingExtension { Dark = Color.Red, Light = Color.Blue } } }

or with binding. Do you have an example of this working? Thank you.

**Comment by MariovanZeist** [comment]
@danielftz 
It has been a while since I did some Xamarin work, 
but this is what I created. (this is code from 1 1/2 years ago, so no guarantees)

I add colors in the ``SetColorResources`` function, and use the ``SetColor`` and ``SetBackgroundColor``
functions to Set the Themebinding.

Hope this helps

```cs
	public static class AppColors
	{

		private static IDictionary<string, ThemeColors> _themeColors = new Dictionary<string, ThemeColors>();

		private static void Add(this ResourceDictionary resourceDictionary, string resource, Color dark, Color light)
		{
			resourceDictionary.Add(resource, CreateAppThemeBinding(light, dark));
			_themeColors.Add(resource, new ThemeColors(light, dark));
		}

		static readonly PropertyInfo _lightProperty;
		static readonly PropertyInfo _darkProperty;
		static readonly Type _appThemeBindingType;

		static AppColors()
		{
			_appThemeBindingType = typeof(Page).Assembly.GetType("Xamarin.Forms.AppThemeBinding");
			_lightProperty = _appThemeBindingType.GetProperty("Light");
			_darkProperty = _appThemeBindingType.GetProperty("Dark");
		}

		private static object CreateAppThemeBinding(Color light, Color dark)
		{
			var obj = Activator.CreateInstance(_appThemeBindingType);
			_lightProperty.SetValue(obj, light);
			_darkProperty.SetValue(obj, dark);
			return obj;
		}



		public static void SetColorResources(ResourceDictionary resources)
		{
			resources.Add(BackGroundColor, DarkModeBackGroundColor, LightModeBackGroundColor);
			resources.Add(AppColor, DarkModeAppColor, LightModeAppColor);
			resources.Add(TabBarBackGroundColor, DarkModeTabBackgroundColor, Color.White);
			resources.Add(TextColor, Color.White, Color.Black);
			resources.Add(CardColor, DarkModeCardColor, Color.White);
			resources.Add(CardTitleColor, DarkModeCardTitleColor, LightModeCardTitleColor);
			resources.Add(CardTitleTextColor, Color.White, Color.White);
			resources.Add(PrimaryColor, DarkModePrimaryColor, LightModePrimaryColor);
			resources.Add(PrimaryVariantColor, DarkModePrimaryVariantColor, LightModePrimaryVariantColor);
			resources.Add(AccentColor, DarkModeAccentColor, LightModeAccentColor);
			resources.Add(LinkColor, DarkModeAccentColor, LightModeAccentColor);


			resources.Add(HeaderColor, DarkModeHeaderColor, Color.Black);
			resources.Add(HeaderTextColor, Color.Gray, Color.White);
			resources.Add(PlaceholderColor, DarkModePlaceholderColor, Color.Gray);
		}

		public static void SetBackgroundColor(this Element visualElement, string colorName)
		{
			SetColor(visualElement, VisualElement.BackgroundColorProperty, colorName);
		}

		public static void SetColor(this Element visualElement, BindableProperty property, string colorName)
		{
			var color = _themeColors[colorName];
			visualElement.SetAppThemeColor(property, color.Light, color.Dark);
		}


		class ThemeColors
		{
			public Color Dark { get; }
			public Color Light { get; }
			public ThemeColors(Color light, Color dark)
			{
				Dark = dark;
				Light = light;
			}
		}
	}
```

**Comment by LeoJHarris** [comment]
@StephaneDelcroix @PureWeen any chance this can get looked at. At this point in time there is no way to define AppThemeBinding on styles which is a bit problematic, color properties are not honored. 

Simple case scenario will not apply the correct styles:
```csharp
<Style x:Key="BasePageVariant2Style"
           TargetType="Page">
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={DynamicResource LightLightOffGrayPageBackgroundColor},
                Dark={DynamicResource DarkLightOffGrayPageBackgroundColor}}" />
    </Style>
```

**Comment by StephaneDelcroix** [comment]
@LeoJHarris doesn't look like the same issue reported by the OP (but looks similar to https://github.com/dotnet/maui/issues/5044)

**Comment by StephaneDelcroix** [comment]
provided that we `seal` it, we could make AppThemeBinding public, but AppThemeBinding is there mostly to support Xaml scenarios, and if you don't use Xaml at all, you probably should use something else than this to switch themes...

**Comment by jfversluis** [comment]
This is unlikely to still happen in Xamarin.Forms. Please open something on the .NET MAUI repo if this is still not working there or see if there is already an issue for it. Thank you!
