### ISSUE TITLE
[Bug] Xamarin UITest EnterText() Method for Android API 29

### ISSUE THREAD

**Issue by CorentinRobertSmood** [xamarin/Xamarin.Forms#11356]
### Description

I Want to use the UI Test method app.EnterText(), the keyboard appear and nothing writing in the entry text.
The test not failed but nothing writing.

### Steps to Reproduce

1. Make a UI Test project
2. Create app with entry, launch test with an Android API level 29
3. Use the method app.EnterText(query,string)

### Basic Information

- Target framework : netstandard2.0
- Last known good version:
Android API Level 28 or before

- IDE:

JetBrains Rider 2020.1.3
Build #RD-201.7846.1, built on May 15, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
.NET Core 3.1.3
macOS 10.15.5

Platform Target Frameworks: 
- Android : Android API Level 29
- Android SDK Platform-Tools : 30.0.3
- Android Emulator : 30.0.12
- Nuget Packages: 

Xamarin.UITest 3.0.7
NUnit 2.6.4

- Affected Devices:
Simulators and Physical devices

**Comment by PureWeen** [comment]
https://github.com/microsoft/appcenter/issues/1451
