### ISSUE TITLE
[Bug] UiTest app.Device.SetLocation()

### ISSUE THREAD

**Issue by CorentinRobertSmood** [xamarin/Xamarin.Forms#11354]
### Description

In my UI test project, i want to set the location with lat/long values.

### Steps to Reproduce

1. Implements map in your app
2. Make project UI Test
3. Try to SetLocation in UItest with method app.Device.SetLocation(Lat,Long)

Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Unable to set location

ExitCode: 4

		-d,--device-id	<device-identifier>	iOS Simulator GUID, physical device ID, or an alias
	set-location <latitude,longitude>
**Expected lat,lng: Got 46,2126,6,146**     <-- I Think the problem is the comma replace by dot for the double value

In the Log File 

The problem come to two lines :
07-07-2020 17:13:19.183 +02:00 - 130933 - Running: /var/folders/f2/ywlyzhy11zl6kchn4v9yr1lh0000gp/T/xdb/DeviceAgent.iOS.Dependencies/61c24de76e863efd7a55753fb8d2f091/bin/iOSDeviceManager set-location 46,2126,6,146 -d 0ED634B8-9BC1-4616-9600-8785A3DDE20F
07-07-2020 17:13:25.192 +02:00 - 136942 - Exit code '4' received from '/var/folders/f2/ywlyzhy11zl6kchn4v9yr1lh0000gp/T/xdb/DeviceAgent.iOS.Dependencies/61c24de76e863efd7a55753fb8d2f091/bin/iOSDeviceManager set-location 46,2126,6,146 -d 0ED634B8-9BC1-4616-9600-8785A3DDE20F'

**When i replace** 

'/var/folders/f2/ywlyzhy11zl6kchn4v9yr1lh0000gp/T/xdb/DeviceAgent.iOS.Dependencies/61c24de76e863efd7a55753fb8d2f091/bin/iOSDeviceManager set-location **46,2126,6,146** -d 0ED634B8-9BC1-4616-9600-8785A3DDE20F'

**By**

'/var/folders/f2/ywlyzhy11zl6kchn4v9yr1lh0000gp/T/xdb/DeviceAgent.iOS.Dependencies/61c24de76e863efd7a55753fb8d2f091/bin/iOSDeviceManager set-location **46.2126,6.146** -d 0ED634B8-9BC1-4616-9600-8785A3DDE20F'

**It's work !!!**

### Basic Information

- Version with issue: 
- Last known good version: First time to use this method
- IDE: 
JetBrains Rider 2020.1.3
Build #RD-201.7846.1, built on May 15, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
.NET Core 3.1.3
macOS 10.15.5

- Platform Target Frameworks: 
  - iOS:  iOS 13.5 
  - Android: Android API level 28 - 29 - 30

- Target framework : netstandard2.0

- Nuget Packages: 

- Xamarin.TestCloud.Agent 0.21.9
- Xamarin.Forms 4.7.968 
- NUnit 2.6.4
- Xamarin.UITest 3.0.7
- Xamarin.Essentials 1.5.3.2

- Affected Devices:
Tested on 
Simulators Iphone 11 Pro Max and simulator Nexus 5X API 29
Physical device Iphone 6 and Huawei Mate 20 Android 10

**Comment by PureWeen** [comment]
@CorentinRobertSmood can you log your issue over here?
https://github.com/microsoft/appcenter

**Comment by CorentinRobertSmood** [comment]
@PureWeen Okay no problem thanks for all.
