### ISSUE TITLE
[Bug]  UWP Bugzilla46458.GridIsEnabled regressed on 4.7..0

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#11352]
### Description

Run Bugzilla46458.GridIsEnabled on 4.6.0 and it passes run it on 4.7.0 and it fails

### Steps to Reproduce

Run Bugzilla46458.GridIsEnabled on 4.6.0 and it passes run it on 4.7.0 and it fails

### Expected Behavior
- Bugzilla46458.GridIsEnabled passees

### Actual Behavior
- Bugzilla46458.GridIsEnabled fails

### Basic Information

- Version with issue: 4.7.0

**Comment by samhouts** [comment]
closed by #11350
