### ISSUE TITLE
Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11366]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1104341/cannot-resolve-assembly-or-windows-metadata-file-t-1.html)._

---
i created a new project of xamarin form and when  copiling i got this error please help me to solve i am new in xamarin

---
#### Feedback Bot on 7/6/2020, 11:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Possibly related to https://github.com/xamarin/Xamarin.Forms/issues/4280

**Comment by jsuarezruiz** [comment]
@samhouts can we have an associated reproduction sample?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
