### ISSUE TITLE
[Bug] Xamarin.Forms.Platform.WPF ToolbarItems  not showing up

### ISSUE THREAD

**Issue by SamuelCarrier** [xamarin/Xamarin.Forms#11367]
### Description
ToolbarItems not showing up in wpf in some content page only

### Steps to Reproduce

1.  

From one toolbar button in content page (1st) I navigate to annother content page (2nd) l

1st content page xaml :
```
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="+" Clicked="AddItem_Clicked" Order="Primary" Priority="0"  />
    </ContentPage.ToolbarItems>
```
1st content page code behid:
```
        async void AddItem_Clicked(object sender, EventArgs e)
        {
            await Navigation.PushModalAsync(new Xamarin.Forms.NavigationPage(new CircuitPage(viewModel)));
        }
```

When I click on Add my 2nd page opens normally but without the toolbarItems

my 2nd page xaml:
  ```
<ContentPage.ToolbarItems>
        <ToolbarItem Text="Ok" Clicked="Save_Clicked"  Order="Primary"/>
    </ContentPage.ToolbarItems>
```

and code behind : 

```
        async void Save_Clicked(object sender, EventArgs e)
        {
            if (!ModeModif)
            {
                MessagingCenter.Send(this, "AddItem", Circuit);
            }
            await Navigation.PopModalAsync();
        }
```

### Expected Behavior
I would expect a button on top right with the label OK
### Actual Behavior
The page shows up but thetool bar button is not there

### Basic Information

- Version with issue: Xamarin.Forms.Platform.WPF 4.7.0.1080
- Last known good version:
- IDE: Visual studio 2019
- Platform Target Frameworks: 
    -WPF 4.7.0.1080
- Nuget Packages: Xamarin.Forms.Platform.WPF 4.7.0.1080
- Affected Devices: Desktop windows

### Screenshots
1st page:
![image](https://user-images.githubusercontent.com/5870937/86939557-babf7080-c10f-11ea-89c5-5b9f3f771d8e.png)

2nd page with the issue :
![image](https://user-images.githubusercontent.com/5870937/86939499-a67b7380-c10f-11ea-85b1-066839965d7e.png)

### Workaround
 No i addend a normal button instead of a toolbaritem

**Comment by VladislavAntonyuk** [comment]
You open modal page instead of simple page
Use PushNavigationAdync

**Comment by SamuelCarrier** [comment]
Will try but it does work in IOS and UWP. It's weird that it dosen't work in wpf (My opinion)
