### ISSUE TITLE
[Bug] [UWP] DisplayAlert renders all controls disabled on a page

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11363]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1096956/bug-uwp-displayalert-renders-all-controls-disabled.html)._

---
https://www.gitmemory.com/issue/xamarin/Xamarin.Forms/9756/592172437

I upgraded to xamarin 4.7.0.968 three weeks ago and ran into this problem on VS2019 community edition.
Installed last updates today, problem persists. 
Disabled DisplayAlert -> no problem.

Dont you proces these bugs anymore for UWP?

---
#### Visual Studio Feedback System on 7/1/2020, 01:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bmacombe** [comment]
likely a duplicate of #9606

**Comment by PureWeen** [comment]
duplicate of #9606
