### ISSUE TITLE
[Bug] Frame Hide is not working for iPad

### ISSUE THREAD

**Issue by umerfarooqy** [xamarin/Xamarin.Forms#11376]
### Description
For iPad unable to hide frame once it is visible Frame.IsVisible = false not working
### Basic Information

- Version with issue: 4.5.0.356
- Last known good version:
- IDE:  VS Mac 8.6.5
- Platform Target Frameworks: 
  - iOS:  13.18.2.1
- Affected Devices: All iPad
 Devices
### Screenshots

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-07-09 at 10 28 46](https://user-images.githubusercontent.com/43748313/87000641-0422c500-c1cf-11ea-8853-226c36ad17be.png)

**Comment by KoenMat** [comment]
I had the same problem. I solved it by setting "HasShadow = false". See issues #9782 and #9892

**Comment by PureWeen** [comment]
@umerfarooqy can you try the latest 4.7 release? I tested there and I'm not seeing the issue anymore

**Comment by umerfarooqy** [comment]
@PureWeen  yes in the latest release this issue is fixed 4.7
