### ISSUE TITLE
[Enhancement] Create TabbedView

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11373]
## Summary

Why dont we get a tabbedView instead of tabbedpage or additionally? TabbedPageRenderer for UWP inherits Pivot control in UWP which is a view not a page. Same for Android ViewPager is a view as well. I am not sure about IOS if UITabBar or there is another one can be used. It should be relatively easy to implement a tabview instead of implementing a multipage but like multiview etc.

## API Changes

Tbd

 ## Intended Use Case

TabbedView as contentview inside a simple contentpage or navigationpage

**Comment by samhouts** [comment]
You mean like......THIS?? https://github.com/dotnet/maui/issues/151 :D

**Comment by EmilAlipiev** [comment]
@samhouts  yes, yes exactly :) can we get that also in xamarin.forms? it will be awesome.

**Comment by EmilAlipiev** [comment]
ok so i see the comment from David here https://github.com/xamarin/Xamarin.Forms/issues/10773
Does he mean that there is XamarinCommunityToolkit which is available over nightly feed and there i can find Tabview? XamarinCommunityToolkit idea sounds awesome indeed.

**Comment by samhouts** [comment]
Yep, we're planning to include it in https://github.com/xamarin/XamarinCommunityToolkit.

**Comment by samhouts** [comment]
Duplicate of #10773
