### ISSUE TITLE
[Enhancement] Grid definitions in controls

### ISSUE THREAD

**Issue by proinfocus** [xamarin/Xamarin.Forms#11389]
## Summary
Simplify the grid definitions in controls

## API Changes / Additions

eg:
**Existing**
```
<Grid>
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="*" />
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="*" />
  </Grid.ColumnDefinitions>
  <Grid.RowDefinitions>
    <RowDefinition Height="*" />
    <RowDefinition Height="Auto" />
    <RowDefinition Height="*" />
  </Grid.RowDefinitions>
    <Label Grid.Column="0" Grid.Row="0" Text="ABC" />
    <Label Grid.Column="0" Grid.Row="0" Grid.Colspan="2" Text="ABC" />
    <Label Grid.Column="0" Grid.Row="0" Grid.Colspan="2" Grid.Rowspan="2" Text="ABC" />
</Grid>
```

**Proposed**
```
<Grid>
  <Grid.ColumnDefinitions>
    <ColumnDefinition Width="*" />
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="*" />
  </Grid.ColumnDefinitions>
  <Grid.RowDefinitions>
    <RowDefinition Height="*" />
    <RowDefinition Height="Auto" />
    <RowDefinition Height="*" />
  </Grid.RowDefinitions>
    <Label Grid.Cell="0,0" Text="ABC" />
    <Label Grid.Cell="0,0,2" Text="ABC" />
    <Label Grid.Cell="0,0,2,2" Text="ABC" />
</Grid>
```
Replacing **Column, Row, Colspan** and **Rowspan** with **Cell** would make the code elegant and compact within grids. This will also help in changing the position more swiftly with less code.

## Intended Use Case
Grid is used almost in every page/view in Xamarin.Forms and the controls used within the grid gets too complex just with the addition of column, row, colspan and rowspans. The proposed change is quite similar to what the recent definition compacting has been done by the team and this will extend to the children within the grid and make the code far more simple and compact.

**Comment by proinfocus** [comment]
or like this:

```
<Label Grid.At="0,0" Text="ABC" />
<Label Grid.At="0,0,2" Text="ABC" />
<Label Grid.At="0,0,2,2" Text="ABC" />
```

**Comment by StephaneDelcroix** [comment]
you know that you can already express Col and RowDefs in a more elegant way than what you're using, right ?

**Comment by proinfocus** [comment]
> you know that you can already express Col and RowDefs in a more elegant way than what you're using, right ?

Yes, I know that. I am proposing compacting of attached properties of Grid, like Grid.Column, Grid.Row, Grid.Colspan and Grid.Rowspan to Grid.Cell or Grid.At
