### ISSUE TITLE
SwipeView active swiping state when finger resting on it too long without any swipe movement[Bug] 

### ISSUE THREAD

**Issue by Strypper** [xamarin/Xamarin.Forms#11384]
### Description
Resting finger on swipeview too long will active it swiping state this is really bad because when implement it inside a listview, swiping state actived will not let listview scroll, and we end up have touch or flick the listview really fast in order to make it scroll but not fall to the swiping state
### Steps to Reproduce

1.  Put the swipeview inside the listview
2. Rest finger on the listiview viewcell
3. Scroll up and down

### Expected Behavior
List must be scroll
### Actual Behavior
ListView could't scroll because the swipe up down missunderstand as swipe right or left from the swipeview
### Basic Information

- Version with issue: Xamarin Form 4.7
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: Android 10

**Comment by jsuarezruiz** [comment]
I have been doing some tests using the 4.7 branch and I think I cannot reproduce the same behavior, I can scroll even resting the finger in a cell for a while.

![sw-scroll-issue](https://user-images.githubusercontent.com/6755973/87410012-11bcbe00-c5c6-11ea-9284-a6f97b39b359.gif)

What version of Xamarin.Forms 4.7 are you using?

**Comment by Strypper** [comment]
Thanks for the reply I will hook it up and record back for you

**Comment by jsuarezruiz** [comment]
@Strypper Yes, the previous gif is from OnePlus 6 device. Tried touching the screen and with mouse from the computer (using https://github.com/Genymobile/scrcpy).

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
