### ISSUE TITLE
There is still another scroll indicator inside Listview even when we use VerticalScrollBarVisibility="Never"[Bug] 

### ISSUE THREAD

**Issue by Strypper** [xamarin/Xamarin.Forms#11387]
We need to remove this unnecessary scrollbar because as I animate when scrolling, this completely screw up the scroll position
Device happen: Android
IOS ? Haven't tested yet

**Comment by PureWeen** [comment]
@Strypper can you attach a repro? I ran a few tests with `VerticalScrollBarVisibility` and I'm not seeing it on the control

**Comment by Strypper** [comment]
> @Strypper can you attach a repro? I ran a few tests with `VerticalScrollBarVisibility` and I'm not seeing it on the control

![107494522_1301548376714965_9070658815527639564_n](https://user-images.githubusercontent.com/32596308/87217748-e7c18c80-c376-11ea-9dd9-6af6b0567962.jpg)
Yes there are, please test it on the listview and on Android

**Comment by eddie010** [comment]
Is it possible you have the ListView inside of a ScrollView?

**Comment by Strypper** [comment]
> Is it possible you have the ListView inside of a ScrollView?

No this is just only the listview

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Strypper** [comment]
> Can you please attach a small project that demonstrates this issue? Thanks!

![image](https://user-images.githubusercontent.com/32596308/89732898-f4232d00-da7b-11ea-8b5d-8cd163f5386d.png)
hello sorry for the slow respond I unfortunately my boss refuse to make the github repo public so here is a screenshoot of the list I'm using
![image](https://user-images.githubusercontent.com/32596308/89732907-08ffc080-da7c-11ea-9e0a-67e05ec1b2a4.png)

**Comment by rmarinho** [comment]
Hi @Strypper  i did some testing ,and its working for us seems  we will really need a sample to investigate this further. 

Thanks.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
