### ISSUE TITLE
[Enhancement] Make ParameterAttribute public

### ISSUE THREAD

**Issue by mattiascibien** [xamarin/Xamarin.Forms#11388]
## Summary
Make the Parameter attribute public in order to let custom controls develpers to access the constructor parameters inside Xaml. I had a real case where this was needed and had to rely on a hacky solution like https://stackoverflow.com/questions/46188243/how-to-define-an-constructor-argument-accessible-from-xaml.

**Comment by StephaneDelcroix** [comment]
Duplicate of #10847
