### ISSUE TITLE
[Enhancement] Path: Add geometry/pathFigure level paint options

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#11398]
## Summary

Currently the paint (color, fill, stroke) for a PathView can only be set for the complete PathView. To allow for more complex drawings, like charts, defining different paints for the geometries/figures the PathView consists of would be required.
Here is an example from the [Microcharts ](https://github.com/dotnet-ad/Microcharts) library of this use case:
![image](https://github.com/dotnet-ad/Microcharts/blob/master/Documentation/images/Gallery.png?raw=true)

## API Changes

Add all paint properties to Geometry and PathFigure. If the paint is not defined for a part of the drawing, use the parent definition. 
```
public class Geometry {
        public Brush Fill  { get; set; }
        public Brush Stroke  { get; set; }
        public double StrokeThickness  { get; set; }
        public DoubleCollection StrokeDashArray  { get; set; }
        public double StrokeDashOffset  { get; set; }
        public PenLineCap StrokeLineCap  { get; set; }
        public PenLineJoin StrokeLineJoin { get; set; }
}
```
```
public class PathFigure {
       public Brush Fill  { get; set; }
        public Brush Stroke  { get; set; }
        public double StrokeThickness  { get; set; }
        public DoubleCollection StrokeDashArray  { get; set; }
        public double StrokeDashOffset  { get; set; }
        public PenLineCap StrokeLineCap  { get; set; }
        public PenLineJoin StrokeLineJoin { get; set; }
}
```
## Intended Use Case
* Complex drawings that consist of different geometries that must be visibily different, for example Charts

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
