### ISSUE TITLE
[Bug] BoxView's that appear after Button have slight shadow on Android

### ISSUE THREAD

**Issue by cabal95** [xamarin/Xamarin.Forms#11396]
### Description

This one is really hard to see. I'm honestly not sure how the person who reported it to me even noticed it. But if you have a StackLayout that contains a sequence of BoxViews and a Button, any BoxView elements that follow the Button have a slight shadow to them. This may be related to #7218, but they are talking about Frame's and we are talking about BoxViews and Buttons.

This happens on both emulators as well as physical devices. As far as we can tell, it does not happen on iOS.

As you can see in the screenshots below, the first two lines look normal. But the last two lines (below the button) have a slight shadow. Because it is very hard to see I have also included a highly zoomed in area of two of the lines to see the difference.

### Steps to Reproduce

```xml
    <StackLayout Padding="10">
        <Label Text="Line 1" />
        <BoxView HeightRequest="5" BackgroundColor="Red" />

        <Label Text="Line 2" />
        <BoxView HeightRequest="5" BackgroundColor="Red" />

        <Button Text="Hello" />

        <Label Text="Line 3" />
        <BoxView HeightRequest="5" BackgroundColor="Red" />

        <Label Text="Line 4" />
        <BoxView HeightRequest="5" BackgroundColor="Red" />
    </StackLayout>
```

### Expected Behavior

Lines should have no shadow (or at the very least be the same above and below the button).

### Actual Behavior

Some lines have shadow, some do not.

### Basic Information

- Version with issue: 4.5.0.495
- Last known good version: n/a
- IDE: Visual Studio Community 16.6.3
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS.Dll version 13.18.2.1
  - Android: Target Framework 9.0
  - UWP:  n/a
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android Moto g7, Android Emulator

### Screenshots

<img width="452" alt="Sample" src="https://user-images.githubusercontent.com/1119863/87176543-1feda000-c28f-11ea-87df-e0b52728f049.png">

<img width="813" alt="Line 1" src="https://user-images.githubusercontent.com/1119863/87176570-254aea80-c28f-11ea-8547-64ca11c171f6.png">

<img width="837" alt="Line 3" src="https://user-images.githubusercontent.com/1119863/87176580-2845db00-c28f-11ea-96e0-c5f37b789409.png">

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/4904323/App2.zip)

**Comment by PureWeen** [comment]
@cabal95 I'm going to close this one as duplicate. The code that handles the elevation is generally applied across the layout so the same thing causes that issue as this one

**Comment by cabal95** [comment]
@PureWeen Sounds good, thanks  for commenting!

**Comment by PureWeen** [comment]
@cabal95 Not an ideal fix but if you set the elevation of the elements to zero https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visualelement-elevation it will remove the shadow

You can also place the Button inside a Stacklayout/frame which will fix

**Comment by tompi** [comment]
Whoa, this was strange, just got bit by this and lost an hour of my life ;-)

@PureWeen Can confirm this bug is still present in XF 5.0..2337 

Solved it by nesting my shadow element in an extra layout :(

**Comment by adesypri** [comment]
> @cabal95 Not an ideal fix but if you set the elevation of the elements to zero https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visualelement-elevation it will remove the shadow
> 
> You can also place the Button inside a Stacklayout/frame which will fix

This does not work when I need the element to be on top of other elements (eg to partially hide them).

I can also confirm that this happens with BoxView, but not with Frame, or not when the BoxView is inside another layout as others before me have said
