### ISSUE TITLE
[Bug] _2489CustomRenderer overriding PageRenderer in Control Gallery 

### ISSUE THREAD

**Issue by bmacombe** [xamarin/Xamarin.Forms#11391]
### Description

A new PageRenderer is used for all Pages in the Control Gallery working off 4.8 branch

### Expected Behavior
PageRenderer is the renderer used for a Page

### Actual Behavior
_2489CustomRenderer is the renderer used for a Page

@jsuarezruiz Was this intended?  I was stepping through the rendering code looking at 10977 and it just threw me for a sec when that renderer showed up.  I don't see that it would harm anything, just confused me for a min.

**Comment by bmacombe** [comment]
If it was intended, just close and no worries!

**Comment by PureWeen** [comment]
@bmacombe I think it's been like that for some time from this PR

https://github.com/xamarin/Xamarin.Forms/pull/2519/files

**Comment by bmacombe** [comment]
I might have looked up the history wrong then...nbd...I was just stepping through some code and wasn't expecting that page renderer

**Comment by PureWeen** [comment]
Yea I'm not super clear on the need to have that everywhere

I'll ping @samhouts and she can respond next week !

**Comment by samhouts** [comment]
Yeah, no, that's normal. There's a debug message in the output that lets you know it's happening. It shouldn't cause any problems. :)
