### ISSUE TITLE
[Enhancement] Adding Text attribute for Checkbox

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#11399]
## Summary
Adding Text attribute for checkbox it is really handy 

<Checkbox Text ="Check Me" />

![image](https://user-images.githubusercontent.com/7360803/87183798-1b54d600-c2e7-11ea-88d0-551bd5a58c30.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
