### ISSUE TITLE
[Bug] Xamarin IOS UIPickerView issue with Appium Inspector

### ISSUE THREAD

**Issue by srikcgaa2** [xamarin/Xamarin.Forms#11392]
### Description

Loading the UIPickerView in Appium Inspector does not load the XML page source.  This issue works with Xamarin.Forms 3.5 but not working with Xamarin.Forms 4.5 (may be even older version but not checked) as well as in the latest 4.7.0.1080
### Steps to Reproduce

1. Extract and open the attached file ([PickerView-4.7.zip](https://github.com/xamarin/Xamarin.Forms/files/4903413/PickerView-4.7.zip))
2. Launch on iPhone 11 - 13.5 Simulator
3. Launch Appium Desktop and Start Inspector Session

### Expected Behavior
XML Dump of the page should be loaded ([PickerDump.xml.zip](https://github.com/xamarin/Xamarin.Forms/files/4903457/PickerDump.xml.zip))

### Actual Behavior
- Appium Desktop Inspector is unable to load the XML dump.
- If I run the Xamarin.IOS app in Debug mode on iPhone 11 13.5 Simulator, the following line appears continuously in the Application Output window of Visual Studio for Mac

`[AXAppAccessibility] Could not find my mock parent, most likely I am stale.`

The above steps work with Xamarin.Forms 3.5 ([PickerView 3.5.zip](https://github.com/xamarin/Xamarin.Forms/files/4903412/PickerView.3.5.zip))

### Basic Information

- Version with issue: 4.5.0.495
- Last known good version: Xamarin.Forms 3.5.0.169047
- IDE: Visual Studio for Mac 8.6.5 (Enterprise)
- Platform Target Frameworks: 
  - iOS:  13.18.2.1 (Visual Studio Enterprise)
- Nuget Packages:
Xamarin.Forms
- Affected Devices:
iOS 13.5
- Appium versions
App Version: 1.17.1-1
Electron: 7.2.4
Node.js: 12.8.1

- Appium Desired Capability Set
```
{
  "automationName": "XCUITest",
  "platformName": "iOS",
  "platformVersion": "13.5",
  "deviceName": "iPhone 11",
  "fullReset": false,
  "noReset": true
}
```

### Workaround

Downgrade to Xamarin.Forms 3.5.0

**Comment by PureWeen** [comment]
This should be fixed by this PR
https://github.com/xamarin/Xamarin.Forms/pull/11077

The nuget for this Issue is here
https://dev.azure.com/xamarin/public/_build/results?buildId=21211&view=artifacts&type=publishedArtifacts

If you want to test and let me know

**Comment by srikcgaa2** [comment]
@PureWeen Thanks for the build.  I did a quick test by upgrading the NuGet with the version provided and it seems to be fixing the issue reported.  This was a sample app created using the controls and renderers used in one of our actual application.  Will do more test on that app as well.  But this is great progress.  Thanks a lot.

**Comment by srikcgaa2** [comment]
@PureWeen, @samhouts  After several tests with our app, this seems to be working pretty well and fixes most of the issues that were not working after we upgraded to 4.x.  Also, the performance has improved significantly as well on several of the pages, in the order of 8 to 10 times faster with this upgrade.  

Any idea, when this change will be available in an official release?  Will it be part of the Sprint 173 release coming up next?
