### ISSUE TITLE
[Enhancement] Shapes: Add text geometry

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#11397]
## Summary

A common drawing operation in drawing frameworks like Skia is to draw text. This allows to embed text directly into the drawing without having to layer views. Additionally the text can be measured to allow for further drawing calculations.

## API Changes

Add text geometry
```
public class TextGeometry : Geometry
{
    public string Text{ get; set; }
    public string FontSize { get; set; }
    public string FontFamily { get; set; }
    public string FontAttributes { get; set; }
}
```

Add text size measurement:
```
public class TextGeometryHelper
{
    public Rectangle MeasureText(this TextGeometry textGeometry);
}
```

## Intended Use Case
* Embedding text directly in drawings without having to use additional views to add Labels.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
