### ISSUE TITLE
[Bug] [Shell] There is no way to hide the back button

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#11404]
### Description

That's is, there is no way to hide the back button. and I don't understand why you went to implement BackButtonBehavior "IsEnabled"  and ignored "IsVisible" when most (maybe all) people don't want "IsEnabled" but "IsVisible"

**Comment by vniehues** [comment]
Any update on this?

**Comment by zehguilherme** [comment]
Any update?

**Comment by 420tech** [comment]
Any update?

**Comment by antjazldev** [comment]
Update ?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
