### ISSUE TITLE
[Bug] [Android] Black diagonal color shown when applying LinearGradient 

### ISSUE THREAD

**Issue by sheiksyedm** [xamarin/Xamarin.Forms#11408]
### Description

We have created the custom control to draw the linear gradient using the below code. When running it on some android devices such as HUAWEI PRO, Samsung S7,  the black diagonal border shown. 
``` XAML
<Grid>
        <local:CustomView />
    </Grid>
```
```C#
   [DesignTimeVisible(true)]
    public class CustomView : View
    {

    }
```
### Android renderer

```C#
public class CustomViewRenderer : ViewRenderer
    {
        public CustomViewRenderer(Context context) : base(context)
        {
            this.SetWillNotDraw(false);
        }
        protected override void OnDraw(Canvas canvas)
        {
            Paint paint = new Paint();
            this.ClipBounds = new Rect(0, 0, Width, Height);
            int[] colors = new int[4] { Android.Graphics.Color.Argb(255, 255, 153, 85), Android.Graphics.Color.Argb(255, 255, 153, 85), Android.Graphics.Color.Argb(255, 255, 153, 85), Android.Graphics.Color.Argb(255,255,153,85) };
            float[] offsets = new float[4] { 0,0.5f,0.5f, 1 };
            LinearGradient gradient = new LinearGradient(0, 0, this.Width, this.Height, colors, offsets, Shader.TileMode.Clamp);
            paint.SetShader(gradient);
            canvas.Save();
            canvas.DrawPaint(paint);
            canvas.Restore();
            base.OnDraw(canvas);
        }
    }
```

### Expected Behavior
The black border will not occur in this case. 

### Actual Behavior
The black border has occurred when using these offsets and colors.  

### Basic Information

- XF version: 4.7
- IDE: VS 2019 Enterprise edition 16.4.3 (windows)

### Screenshots
![image](https://user-images.githubusercontent.com/23059975/87240643-e193e480-c438-11ea-9576-8071677323fe.png)

### Reproduction Link

[sample](https://github.com/sheiksyedm/Samples/raw/master/GradientIssue%20(2).zip)

**Comment by hartez** [comment]
1. This forum is for bugs in Xamarin.Forms. This is not a Xamarin.Forms bug. It's not even a bug - you're just using the LinearGradient constructor wrong. This forum is not for us to help you debug your completely custom Android code. 

2. You're telling Android to apply a gradient, but two of your positions are the same value:

`float[] offsets = new float[4] { 0,0.5f,0.5f, 1 };`

You're asking it to gradually change from one color to another color over the space of 0% of the distance; this is why you are getting a black line. Change the second `0.5f` to literally any value between 0.5 and 1, and the black line will go away.
