### ISSUE TITLE
[Bug] AppThemeColor is missing

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#11414]
### Description

Hi,
I have update to the latest version form the version 4.6.0.847 and the AppThemeColor is gone.
I need to convert this code in my resources.xaml otherwise my application doesn't compile:

`<AppThemeColor x:Key="Tema_Bianco" Light="{StaticResource Bianco}" Dark="{StaticResource Bianco}" /> <AppThemeColor x:Key="Tema_Nero" Light="{StaticResource Nero}" Dark="{StaticResource Nero}" /> <AppThemeColor x:Key="Tema_ShellHeaderFooter" Light="{StaticResource GrigioChiaro}" Dark="{StaticResource GrigioChiaro}" /> <AppThemeColor x:Key="Tema_Testo" Light="{StaticResource Nero}" Dark="{StaticResource Nero}" /> <AppThemeColor x:Key="Tema_ModaliFooter" Light="{StaticResource Bianco}" Dark="{StaticResource Bianco}" /> <AppThemeColor x:Key="Tema_ButtonDisabled" Light="{StaticResource Nero}" Dark="{StaticResource Nero}"/>`

How can i solve this?

Thank you.

### Basic Information

- Version with issue: 4.7.0.1080
- Last known good version: 4.6.0.847 
- IDE: VS for Mac
- Platform Target Frameworks: All

**Comment by holecekp** [comment]
Hello. AppThemeColor has been removed and replaced by AppThemeBinding. You can see more information on how to use it here:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes

From my own experience, I must warn you that the migration is not as easy as it seems. You cannot just replace all occurrences of AppThemeColor with AppThemeBinding. It is used in a different way. Also, some things that were possible with AppThemeBinding are not possible now. I encountered multiple problems and I am not still done yet. Consider waiting with the XF update if you do not need it urgently.

**Comment by Raystorm7** [comment]
Hi @holecekp thank you for the reply!

I'm trying to migrate but I think that I will stay with the older version.

For sample I can't migrate the code in my first post, I need to replace all `Color={StaticResource Tema_Bianco}` with AppThemeBinding pattern.

This is too "time expensive" for my team leader.

There is some planning for fix the `AppThemeBinding` functionalities?

**Comment by jsuarezruiz** [comment]
Yes, we are fixing issues. You can see a list of issues and PRs related to AppTheme here https://github.com/xamarin/Xamarin.Forms/labels/a%2Fdarkmode

**Comment by Raystorm7** [comment]
> Yes, we are fixing issues. You can see a list of issues and PRs related to AppTheme here https://github.com/xamarin/Xamarin.Forms/labels/a%2Fdarkmode

Ok thank you!
