### ISSUE TITLE
[Bug] Unable to preview XAML pages in Xamarin.Forms via iOS previewer on Windows 10.

### ISSUE THREAD

**Issue by meJevin** [xamarin/Xamarin.Forms#11424]
### Description

Unable to preview XAML pages in Xamarin.Forms via iOS previewer on Windows 10.

### Steps to Reproduce

1. Open Visual Studio
2. Create a blank Xamarin.Forms project
3. Connect to mac
4. Open any XAML page and choose iOS preveiwer

### Expected Behavior

XAML Renders properly and shows in the iOS previewer

### Actual Behavior

Above the previewer there is an error message 'An exception occurred while rendering the control'.

Upon expanding, it says:
System.IO.FileNotFoundException was thrown
Could not load the file 'Xamarin.Forms.Platform.iOS'

And then there's a call stack which drills down to:
`MonoTouch.Design.Server.XamlToPng.RenderOneXaml(MonoTouch.Design.XamlRenderContext contet, MonoTouch.Design.XamlFormFactor formFactor) in /Users/runner/runners..../Xamarin.Designer.iOS/MonoTouch.Design.Server/XamlViewer/XamlToPng.cs:67`

![image](https://user-images.githubusercontent.com/16974717/87391313-2e9bc600-c5b3-11ea-841e-6af3c913f16c.png)

### Basic Information

- Version with issue: 4.7.0.1080+439-sha.67ad4cfe9-azdo.3855729
- Last known good version: Unknown
- IDE: Visual Studio 19 (16.6.3)
- Platform Target Frameworks: 
  - iOS:  8.0
- Nuget Packages: NetStandard.Library (2.0.3), Xamarin.Essentials (1.5.3.2), Xamarin.Forms (4.7.0.1080)
- Affected Devices: Unknown

I'm connected from my Windows PC to a Mac Mini, which has:

- macOS Catalina 10.15.5
- Xcode 11.5
- Visual Studio for Mac
- Simulators and WiFi connection to my device work

My Windows PC has:
- Windows Version 10.0.18362 Build 18362
- Visual Studio 19 (16.6.3)
  - ASP.NET and web development
  - Azure development
  - .NET desktop development
  - Mobile development with .NET
  -.NET Core cross-platform development

### Screenshots

![image](https://user-images.githubusercontent.com/16974717/87391772-05c80080-c5b4-11ea-9b35-e8b7e7eb321a.png)

### Reproduction Link

N/A

### Workaround

Unknown

### Info

If any more information is required about the OS, devices, SDKs I'm using, I will gladly provide it

> VS bug [#1155866](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1155866)

**Comment by jsuarezruiz** [comment]
Although sometimes it works for me as expected, I have managed to reproduce the problem:

<img width="1296" alt="Captura de pantalla 2020-07-14 a las 9 58 19" src="https://user-images.githubusercontent.com/6755973/87400084-a0c2d980-c5b8-11ea-916e-d37958c910f2.png">

<img width="499" alt="Captura de pantalla 2020-07-14 a las 10 01 02" src="https://user-images.githubusercontent.com/6755973/87400344-f7c8ae80-c5b8-11ea-9efa-e1778f54856a.png">

**Comment by meJevin** [comment]
@jsuarezruiz, yup, that's the one. I'm wondering what could be causing the problem exactly.

**Comment by meJevin** [comment]
I also want to mention that I haven't been able to get the previewer to work as expected a single time so far. I've restarted Visual Studio, reconnected to Mac, created new projects, no luck so far.
