### ISSUE TITLE
[Bug] [iOS] Button stays in Pressed state if the touch-up event occurs outside

### ISSUE THREAD

**Issue by hichamboushaba** [xamarin/Xamarin.Forms#11430]
### Description
If you tap a button, then drag your finger outside it, then the button will stay in the "Pressed" state.

### Steps to Reproduce

1. Tap a button
2. Drag your finger outside the button
3. Lift up your finger

### Expected Behavior
The button will go to the state "Normal"

### Actual Behavior
The button will stay in the state "Pressed"

### Basic Information

- Version with issue: 4.7.0.1080

The cause is clear from the ButtonRenderer, we only listen to the `TouchUpInside` event, so `SendReleased` is not called when `TouchUpOutside` occurs.
As a workaround I'm using this Renderer in my project:

``` C#
    public class ButtonRenderer : Xamarin.Forms.Platform.iOS.ButtonRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null)
            {
                Control.TouchUpOutside += OnTouchUpOutside;
            }
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            if (!disposing) return;

            if (Control != null)
            {
                Control.TouchUpOutside -= OnTouchUpOutside;
            }
        }

        private void OnTouchUpOutside(object sender, EventArgs e)
        {
            Element?.SendReleased();
        }
```

**Comment by ChristopherStephan** [comment]
According to the release notes this issue is fixed in 4.8.0.1269 (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.8/4.8.0-pre3#issues-fixed) - which is a wrong information. By updating Xamarin.Forms to 4.8.0.1687 we could confirm that this bug is fixed.
