### ISSUE TITLE
[Enhancement] Improve ColumnDefinitions/RowDefinitions markup using OnIdiom and OnPlatform

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11439]
## Summary
xamarin.forms  4.7 ColumnDefinitions and RowDefinitions markup doesnt allow using OnIdiom and OnPlatform. I am getting error as below.
I am not sure if it is bug or Enhancement. I guess that it wasn't implemented at all. that's why I marked as enhancement 

![image](https://user-images.githubusercontent.com/10422347/87528556-f4ebbd80-c68d-11ea-93d2-254643e1dfd4.png)

**Comment by jsuarezruiz** [comment]
@StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
this isn't a valid xaml syntax. markup expression are resolved as property values, not as list elements
