### ISSUE TITLE
[Bug] MacOS this.Platform.DidAppear() causes NullReferenceException

### ISSUE THREAD

**Issue by kefyru** [xamarin/Xamarin.Forms#11440]
### Description
Starting mac app with a single empty page crashes with exception

System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.MacOS.PlatformRenderer.ViewDidAppear () [0x00006] in <80383802214540fe948b297f6790b923>:0 

Debugging:

in internal class PlatformRenderer:

internal PlatformRenderer(Xamarin.Forms.Platform.MacOS.Platform platform)
    {
      this.Platform = platform; // here sets some value
      this.View = new NSView(NSApplication.SharedApplication.Windows[0].Frame);
      this._platformNavigation = new PlatformNavigation(this);
    }

public override void ViewDidAppear()
    {
      this.Platform.DidAppear(); // here this.Platform is null
      base.ViewDidAppear();
    }

I could not find where this.Platform sets to null.

on iOS an Android everything is ok.

### Steps to Reproduce

1. Create new Mac app project in existing Xamarin Forms solution
2. Make changes as described in doc: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac
3. Run

### Expected Behavior
run app with simple page

### Actual Behavior
crushes with nullreferenceexception

### Basic Information

- Version with issue: 4.7.0.1080
- IDE: Rider 2020.1
- Platform Target Frameworks: Xamarin.Mac v2.0

**Comment by kefyru** [comment]
<img width="1026" alt="Снимок экрана 2020-07-15 в 13 24 18" src="https://user-images.githubusercontent.com/29143718/87534408-a561bd80-c69e-11ea-8f04-32dbc1468eaa.png">

Page renders as expected

**Comment by jsuarezruiz** [comment]
I have created a sample using 4.7.0.1080 but cannot reproduce the crash:
[Issue11440.zip](https://github.com/xamarin/Xamarin.Forms/files/4924696/Issue11440.zip)

Could you take a look to the sample or attach a sample where reproduce the issue?

**Comment by kefyru** [comment]
Thinking its skiasharp library problem.

**Comment by kefyru** [comment]
[mybgt2-master.zip](https://github.com/xamarin/Xamarin.Forms/files/4932308/mybgt2-master.zip)

Empty project works ok, but in my project i have problems...

**Comment by kefyru** [comment]
I think i found the problem... It's something with ui thread... on ios and android works good, but on mac strange behaviour.. I will check deeply.

Thanks.

**Comment by jlewicki-nevo** [comment]
I ran into this problem as well. 

The crash seems to be related to assigning a new value for Application.MainWindow in an OnStart Application.OnStart override.  If the sample project provided by @jsuarezruiz is changed simply by adding to App.xaml.cs the following:

`protected override void OnStart()
        {
            MainPage = new MainPage();
        }
`
the crash occurs.  This crash not happen on other platforms.

In the app I am working on, I think I can work around this by assigning a NavigationPage as the MainPage in the App constructor, and then in OnStart I will push another page onto the navigation stack, as opposed to assigning a new page as I am currently doing (and subsequently crashing on iOS).
