### ISSUE TITLE
[Enhancement] Button with rich text

### ISSUE THREAD

**Issue by opcodewriter** [xamarin/Xamarin.Forms#11444]
## Summary

Make it possible to have Button with rich text.

For this, add to Button the same `FormattedText` property which Label has it.

This should be fairly easy to add by the Xamarin Forms team.

## API Changes
 
```
  var button = new Button ();
  button.FormattedText = ...;// Similar to Label
```

**Comment by Axemasta** [comment]
I would appreciate this, using a custom renender at the moment. Would PR's be accepted?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
