### ISSUE TITLE
[Bug] Can't set different corner radius for boxview on different platforms

### ISSUE THREAD

**Issue by themronion** [xamarin/Xamarin.Forms#11443]
### Steps to Reproduce
Put this code 
`<BoxView HorizontalOptions="Center" VerticalOptions="End" CornerRadius="2" Color="#C4C4C4" HeightRequest="4" WidthRequest="40" Margin="0">
                        <BoxView.CornerRadius>
                            <OnPlatform x:TypeArguments="x:Double">
                                <On Platform="Android" Value="25"/>
                                <On Platform="UWP" Value="2" />
                                <On Platform="iOS" Value="2"/>
                            </OnPlatform>
                        </BoxView.CornerRadius>
                    </BoxView>`

### Expected Behavior
Corner Radius changes
### Actual Behavior
Error during the building proccess of shared project: No property, BindableProperty, or event found for "CornerRadius", or mismatching type between value and property
### Basic Information

-Latest Forms, latest visual studio.

**Comment by jsuarezruiz** [comment]
@themronion The CornerRadius property in the BoxView is not a double type, it is a CornerRadius (a struct that allows to set the radius of each corner).

**Comment by themronion** [comment]
ah, i see now. Thanks) Closing issue
