### ISSUE TITLE
[Bug] Styles stop working in a new window consisting of a NavigationPage on Xamarin.Forms for Mac

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#11459]
### Description
Styles stop working in a new window consisting of a NavigationPage on Xamarin.Forms for Mac

### Steps to Reproduce

1. Run the attached example with the Mac project set as startup
2. Tap the New Window button
3. Tap the Push Me button on the new window to push another page

### Expected Behavior
The New Window button text is black on the new window NavigationPage

### Actual Behavior
Should be red as per the style defined

### Basic Information

- Version with issue: 4.7
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[XF4iOSAndroidMacDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4933478/XF4iOSAndroidMacDemo.zip)

### Workaround
None

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
