### ISSUE TITLE
[Bug] ImageReader.GetImage() crash

### ISSUE THREAD

**Issue by r-work** [xamarin/Xamarin.Forms#11453]
### Description

Trying to take a screenshot using MediaProjection, to acquire the image I'm using ImageReader and it crashes when calling ImageReader.GetImage().

### Steps to Reproduce

Consider the following snippet:

```c#
public static void CreateMediaProjection(int result, Intent data)
{
     _resutltData = data;

    _mediaProjection = _projectionManager.GetMediaProjection(result, _resutltData);
    _imgReader = ImageReader.NewInstance(_width, _height, ImageFormatType.Jpeg, 5);
    _imgReader.SetOnImageAvailableListener(new ImageAvailableListener(), null);
    _virtualDisplay = _mediaProjection.CreateVirtualDisplay("ScreenCapture", _width, _height, _density, (DisplayFlags)VirtualDisplayFlags.AutoMirror, _imgReader.Surface, null, null);
}

public class ImageAvailableListener : Java.Lang.Object, ImageReader.IOnImageAvailableListener
{
     public void OnImageAvailable(ImageReader reader)
     {
          var img = _imgReader.AcquireLatestImage();
          var planes = img.GetPlanes(); // <- it crashes here
     }
}
```

### Expected Behavior
Continue on.
### Actual Behavior
App crashes and debugger stops without breaking.
### Basic Information
- IDE: VS 2019 (16.7.0 Preview 4.0)
- Platform Target Frameworks: 
  - Android: Android 10.0
  - XF 4.7.0.1142

### Reproduction Link

The following contains "minimal" repro code, file of interest is **AndroidScreenShotService.cs** and it crashes at line 67.
https://github.com/r-work/XamarinCrash

**Comment by jsuarezruiz** [comment]
Reading the logs (Logcat): 

```
2020-07-16 16:05:46.270 29251-29251/com.companyname.xamarincrash A/AndroidMediaUtils: RGBA override BLOB format buffer should have height == width
    
    --------- beginning of crash
2020-07-16 16:05:46.270 29251-29251/com.companyname.xamarincrash A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 29251 (me.xamarincrash), pid 29251 (me.xamarincrash)
2020-07-16 16:05:46.289 29369-29369/? I/crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
2020-07-16 16:05:46.289 1490-1490/? I//system/bin/tombstoned: received crash request for pid 29251
2020-07-16 16:05:46.290 29369-29369/? I/crash_dump32: performing dump of process 29251 (target tid = 29251)
```

Could you try it changing the height/width parameters?.

**Comment by r-work** [comment]
Seems to be working now.
I think my mistake was using width and height from **Xamarin.Essentials.DeviceDisplay.MainDisplayInfo**

Now I get the display width and height like below:

```c#
var metrics = new DisplayMetrics();
Xamarin.Essentials.Platform.CurrentActivity.WindowManager.DefaultDisplay.GetMetrics(metrics);

var width = metrics.WidthPixels;
var height = metrics.HeightPixels;
```

Thanks for the quick reply.

**Comment by Nishain** [comment]
Hello, I am also getting the error  `RGBA override BLOB format buffer should have height == width` and setting the both height and width with same equal value resolved it. I get the dimensions by `getResources().getDisplayMetrics().heightPixels` in `JPEG` format.
I noticed this error occurred by calling `image.getPlanes()`. But I want height and width to be different value, anyone has a suggestion to achieve this while avoiding this error?
