### ISSUE TITLE
Building a signed apk errors after installing build tools 30.0.0 or later

### ISSUE THREAD

**Issue by sk1llsh0t** [xamarin/Xamarin.Forms#11454]
### Description
After installing build tools 30.0.x, i get this error when trying to build an apk. I am using adoptopenjdk8 (1.8.0.252)

ApkSignerTool has been compiled by a more recent version of the Java Runtime(class version 53)

I can build my android studio apps just fine with build tools 30.0.0 (or 30.0.1). It is just in VS Xamarin that i get this error.

### Steps to Reproduce

1. Install build tools 30.0.0 or 30.0.1 
2. I try to sign and generate an apk 
3. error occurs

### Expected Behavior
It should build an apk without error

### Actual Behavior
No apk is generated and i get the error listed in the description above

### Basic Information

- Version with issue: build tools v30.0.0 and later
- Last known good version: build tools v29.0.3
- IDE: VS 2019 for Mac (v. 8.6.5)
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 29 (Android 10)
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment]
I think this issue is the same as: https://developercommunity.visualstudio.com/content/problem/1086793/我用xamarin-开发android-后进行打包发布apk但升级后打包报密码错误.html
There is a fix in Preview version.

**Comment by sk1llsh0t** [comment]
Could you provide a specific version # this fix will come in? (mac and windows specific version)

**Comment by MagicAndre1981** [comment]
@sk1llsh0t 

here is it explained a bit:

https://github.com/xamarin/xamarin-android/releases#bindings-for-android-11-beta-11003

**Comment by PureWeen** [comment]
Closing for now. Let me know if the link @MagicAndre1981 provided for you doesn't work @sk1llsh0t
