### ISSUE TITLE
[Enhancement] Top Tabs on any page instead of assigning them to a BottomTabBarItem (TabBar)

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#11457]
The **structure** for adding top **Tabs** is currently **fixed**. 
- Shell
  - FlyoutItem // BurgerMenu - optional
    - TabBar // BottomTabBar - optional
      - **Tab** // TopTabBar - optional - This is the target for this ticket
        - ShellContent // Wraps a ContentPage - optional
          - ContentPage

We would like to have the following scenario.
- Shell
    - TabBar // BottomTabBar - Route = TabBarItem1
        - ShellContent 
          - ContentPage // Route = Page1
Then navigating to TabBarItem1/Page1/Page2/Page3 (using await Shell.Current.GoToAsync). **Page3 should have Tabs** (TopTabBar). To my knowledge this is currently not possible. A Tab can only be declared as a child of an item of TabBar (BottomTabBar).

Thanks for your effort and I'm thankful for every idea :-)

![Screenshot 2020-07-16 at 13 21 56](https://user-images.githubusercontent.com/61872738/87665498-5469cc00-c767-11ea-9192-489256ff6f4b.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
