### ISSUE TITLE
[Bug] Concurrency issue on BindableObject internal Dictionary 

### ISSUE THREAD

**Issue by AlfonChitoSalano** [xamarin/Xamarin.Forms#11452]
### Description
We catch an issue in the AppCenter with our Live App. We have CollectionView with template inside the itemtemplate which works well. However, we are getting this issue "System.IndexOutOfRangeException: Index was outside the bounds of the array." in our live app and the stack trace said it is getting the property value in the BindableObject.cs in Xamarin Forms core class.

Xaml. (attached)
[XAML.txt](https://github.com/xamarin/Xamarin.Forms/files/4931409/XAML.txt)

Root Cause of Issue.
BindableObject.cs 
Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value)
BindableObject.IsSet (Xamarin.Forms.BindableProperty targetProperty)
BaseShellItem.Propagate (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject from, Xamarin.Forms.BindableObject to, System.Boolean onlyToImplicit)

### Steps to Reproduce
NA. Live AppCenter reporting.

### Expected Behavior
Should have no issue reported to the AppCenter with regards to binding item template.

### Actual Behavior
Issue has been reported in the AppCenter Logs.

### Basic Information
- Version with issue: XF 4.6.0.967
- Platform Target Frameworks: 
  - Android: 10.3.1.4
- Android Support Library Version: 28.0.0.3
- Affected Devices: Android
Logs.
```
Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value)
BindableObject.IsSet (Xamarin.Forms.BindableProperty targetProperty)
BaseShellItem.Propagate (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject from, Xamarin.Forms.BindableObject to, System.Boolean onlyToImplicit)
BaseShellItem.PropagateFromParent (Xamarin.Forms.BindableProperty property, Xamarin.Forms.Element me)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
PropertyPropagationExtensions.PropagatePropertyChanged (System.String propertyName, Xamarin.Forms.Element element, System.Collections.IEnumerable children)
IPropertyPropagationController.PropagatePropertyChanged (System.String propertyName)
Element.OnParentSet ()
NavigableElement.OnParentSet ()
Element.set_Parent (Xamarin.Forms.Element value)
Element.OnChildAdded (Xamarin.Forms.Element child)
VisualElement.OnChildAdded (Xamarin.Forms.Element child)
Layout.OnInternalAdded (Xamarin.Forms.View view)
Layout.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index)
ObservableCollection`1[T].InsertItem (System.Int32 index, T item)
Collection`1[T].Add (T item)
TemplateUtilities.OnContentChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value)
```

### What I found out
IMHO, Upon reading the code from the stack trace, I think that this is a concurrency issue of for Dictionary in this line of code https://github.com/xamarin/Xamarin.Forms/blob/main/Xamarin.Forms.Core/BindableObject.cs line 519. I know that the Dictionary is not a thread safe and this will fail. I also found out somewhat similar issue failing in Dictionary here https://github.com/xamarin/Xamarin.Forms/issues/9402. 

Would you be able to have a look to this issue and to somewhat similar issues https://github.com/xamarin/Xamarin.Forms/issues/9402 and https://github.com/xamarin/Xamarin.Forms/pull/9524/files?

**Comment by jsuarezruiz** [comment]
@AlfonChitoSalano The logs are from Android, does not happen to you on iOS?, do you know under what conditions it happens? (to try to replicate the issue with a sample).

Mnn, I think we can handle this cases using lock with Dictionary.

**Comment by thisisthekap** [comment]
Imho this could be accomplished similar to https://github.com/xamarin/Xamarin.Forms/pull/9524.

**Comment by AlfonChitoSalano** [comment]
> 
> 
> @AlfonChitoSalano The logs are from Android, does not happen to you on iOS?, do you know under what conditions it happens? (to try to replicate the issue with a sample).
> 
> Mnn, I think we can handle this cases using lock with Dictionary.

Good question. Yes it is from Android. I am not sure if it happens to iOS, but imho it will happen as well in iOS. Since these logs are caught via our live app with the live users, from my point of view I believe users are scrolling up and down to our collectionview which has caused the dictionary to get "System.IndexOutOfRangeException: Index was outside the bounds of the array." with the stack trace above. I did my homework, already and read the code, I believe because Dictionary is not thread safe then it fails with concurrent usage.

**Comment by hartez** [comment]
@AlfonChitoSalano Are you adding/removing items to/from your collection from a background thread?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
