### ISSUE TITLE
[Bug] TabIndex broken on a page pushed onto a NavigationPage in a new window on Xamarin.Forms for Mac

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#11460]
### Description
TabIndex broken on a page pushed onto a NavigationPage in a new window on Xamarin.Forms for Mac

### Steps to Reproduce

1. Unzip and run the attached example with the Mac project set to startup
2. Tap the New Window button
3. Tap the Push Me button on the new window
4. Select the first entry
5. Press tab

### Expected Behavior
The next entry as defined by the TabIndex should be selected

### Actual Behavior
The current entry remains focused and the text within the entry is selected

### Basic Information

- Version with issue: 4.7
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[XF4iOSAndroidMacDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/4933494/XF4iOSAndroidMacDemo.zip)

### Workaround
None

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
