### ISSUE TITLE
UWP - AppThemeBinding in extra resource file.

### ISSUE THREAD

**Issue by IvanDemjanovic** [xamarin/Xamarin.Forms#11466]
### Description
`<AppThemeBinding>` defined in extra theme.xaml file is finished on UWP with error.
On Android it works  without error.

### Steps to Reproduce

1. Xamarin setting with experimental flags in App.xaml.cs (for all platforms)

![image](https://user-images.githubusercontent.com/51379429/87780521-2e0f6380-c82f-11ea-810c-abb07287aa04.png)

2. extra Resources/Theme.xaml file 

![image](https://user-images.githubusercontent.com/51379429/87775387-4dee5980-c826-11ea-8167-be86a7bbd107.png)

3. Xamarin App.xaml with reference on theme.xaml (intended for all platforms and, all pages)

![image](https://user-images.githubusercontent.com/51379429/87775449-69596480-c826-11ea-88d7-a9507bc6a7d1.png)

4. Testing page.xaml

![image](https://user-images.githubusercontent.com/51379429/87777230-6c098900-c829-11ea-9198-fd7b930820aa.png)

5. On UWP it finish with this error (without specify more precisely point of error source)

![image](https://user-images.githubusercontent.com/51379429/87774769-4d08f800-c825-11ea-9b5f-de732548a125.png)

- Version with issue: 4.7.0.1080
- Last known good version: ??
- IDE: Visual Studio 2019 16.16.3
- Platform Target Frameworks: 
  - Android: works without error 
  - UWP:  16299 ... 18362
- Nuget Packages:
  Xamarin.Forms   4.7.0.1080
- Affected Devices: PC

**Comment by StephaneDelcroix** [comment]
AppThemeBinding are Bindings, can't be shared by instance. also `{AppThemeBinding {StaticResource abinding}}` has no meaning at all. AppThemeBindingExtension has no ContentProperty, and no property of AppThemeBindingExtension is of type AppThemeBinding

**Comment by StephaneDelcroix** [comment]
> On Android it works without error.

looks suspicious
