### ISSUE TITLE
[Enhancement] ImageBrush

### ISSUE THREAD

**Issue by opcodewriter** [xamarin/Xamarin.Forms#11463]
## Summary

@jsuarezruiz I can't wait to use the brushes, do you plan to include an `ImageBrush` too? 
Sometimes using an image is still needed as recreating it by solid/gradient brush is impossible. 
An `Image` view won't work if you need to set a complex background image for a `Button`.

## API Changes

```
public class ImageBrush : Brush 
{ 
     public ImageSource Source { get; set; }
}
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
