### ISSUE TITLE
[Bug] awaited PushAsync not exiting, un-awaited PushAsync page not appearing on iOS when coinciding with UIAlertController call

### ISSUE THREAD

**Issue by goiditdev** [xamarin/Xamarin.Forms#11475]
### Description
We discovered by accident in a Xamarin.Forms project when running on iOS and using ACR.UserDialogs' Alert call, immediately followed by pushing a new modeless page to the navigation stack, that page does not appear. 
When debugging it in more detail, here is what we found, but we are not clear why that happens, specifically.
ACR.UserDialogs uses UIAlertController to create the alert. This call exits immediately, before the dialog actually appears.
What it uses is:
`
var alert = UIAlertController.Create(config.Title ?? String.Empty, config.Message, UIAlertControllerStyle.Alert);
alert.AddAction(UIAlertAction.Create(config.OkText, UIAlertActionStyle.Default, x => config.OnAction?.Invoke()));
return alert;
`
(from https://github.com/aritchie/userdialogs, in /src/Acr.UserDialogs/Platforms/ios/UserDialogsImpl.cs)

On Android, the page appears as expected. This issue is iOS-related, and specific to a call to the UIAlertController to make a UIAlert appear just prior to pushing a page onto the navigation stack.

### Steps to Reproduce

Scenario 1: 
1. a call to Alert()
2. followed by an awaited call to PushAsync for a new page

Result:
The awaited call never returns. The page never appears.

Scenario 2:
1. a call to Alert()
2. followed by a call to PushAsync without the await

Result:
The PushAsync call returns. An inspection of the NavigationStack shows the new page as the last element. But the page still never appears.

Scenario 3:
1. We change the Alert call to an awaited AlertAsync call. This waits out the appearance of the alert and the user action to close it
2. Both an awaited pushasync and a pushasync without an await return successfully and the page appears as expected.

### Expected Behavior
We would like scenarios 1 and 2 to behave like scenario 2: The PushAsync call should return and the page should appear, even if there is an alert occurring at the same time. On android, that is the behavior we get, but the Alert implementation there is different from the one for iOS. So underneath it is the question of what the UIAlert does that prevents the page from appearing or the push from succeeding and being stuck indefinitely.

### Actual Behavior
For scenarios 1 and 2 the page does not appear. For scenario 1, the task for PushAsync never ends and so the await is stuck, seemingly indefinitely.

### Basic Information

- Version with issue: testing on 4.7 and 4.6
- Last known good version: not sure
- IDE: Visual Studio for MAC, currently on 8.6.5
- Platform Target Frameworks: 
  - iOS:  observed for minimum iOS version 8 and 10, not tested for others
  - Android: target sdk 28
- Nuget Packages: ACR.Userdialogs
- Affected Devices: verified on simulators for iOS and android, as well as different devices. occurs on all tested iOS devices

### Reproduction Link
We created a repro project, available here: https://github.com/goiditdev/pushasync_test

### Workaround
Scenario 3 is our current workaround. But since we do not know if there are other cases where such a collision occurs, we'd really like to at least understand why this happens in the first place.

**Comment by hartez** [comment]
I'd suggest posting an issue at https://github.com/aritchie/userdialogs/issues since this is a problem with that library.
