### ISSUE TITLE
RefreshView using along with Busy Indicator

### ISSUE THREAD

**Issue by JunkyXL86** [xamarin/Xamarin.Forms#11470]
I migrated from James' Refractored PullToRefreshLayout to XF RefreshView only to encounter that my data loading process is fired twice.
This is because (and that's why I need your support on how to deal with it) I set IsBusy = true when I start loading data. I bound this property to the IsRefreshing property of the PullToRefreshLayout to make the busy indicator show up.
When I pulled down, the RefreshCommand was fired. Then I called my data loading mechanism which set IsBusy = true which in turn ensured to show up the busy indicator.

Now with XF RefreshView the Command is fired additionally whenever I set IsBusy = true which calls LoadData() a second time.
To avoid this I need to unbind the IsRefreshing property. Downside is that the busy indicator doesn't show up any more when I manually call LoadData() (when navigated to the page). So how do I bring up the busy indicator without invoking the command?

I also think that a property should not lead to firing a command. That was a bit unexpected and took me a while to figure out.

> Related to this Issue, i think setting IsRefreshing=true should not fire the command.
> 
> In my opinion, pull gesture should simply fire the refresh command and let the command the responsibility to set some property you can bind to IsRefreshing,  true at the beginning and false at the end.
> 
> I think this way is more flexible, and is simplest to use the same command both for pull to refresh an , as for example, to load data when a page is presented.
> 

_Originally posted by @FranVillaVainilla in https://github.com/xamarin/Xamarin.Forms/issues/7803#issuecomment-549953942_

**Comment by Craigium** [comment]
I've been dealing with this exact issue recently when converting a ListView to CollectionView with RefreshView.
As far as I am aware, setting the ListView IsRefreshing property to true does not trigger the command, and just shows the activity indicator.

Would be nice if the RefreshView could behave in the same way, or have an option to trigger the activity indicator separately for times when the data is refreshed via another action (e.g. selecting a value from a Picker control that causes a new data request to be sent).

**Comment by DennisWelu** [comment]
The rationale by @PureWeen is here: https://github.com/xamarin/Xamarin.Forms/issues/7803#issuecomment-549964605. Duly noted, consistency is nice, but the effort for consistency here has side effects including limitations in flexibility. First, from an API design standpoint I 'feel' like I want to call a method not just change the state of an object. State in this context seems more appropriate to cascade up to the UI level to be reflected to the user - like the previous ListView handled it.

More importantly, separating the method and the state of "refreshing" gives you flexibility in implementation. I can call the method behind the Command directly in my ViewModel implementation if need be, and the method can decide when the view should reflect the "refreshing" state. Maybe it needs to short circuit out and "do nothing" - so don't start the indicator spinning. What if I'm using the Refresh method with an optional parameter in the ViewModel? This is a true story... :-) I have a Refresh method that does both filtering and sorting of a dataset. The filtering is expensive/can take time, the sorting is much less so. So there are cases where other actions in the view may trigger a re-sort and I don't want all that filtering to happen. In those cases I'm calling Refresh directly with an optional parameter. Can I work around it? Not completely, I think. I can still call the Refresh directly when needed but there is no way to have it indicate that it is currently "refreshing". It also feels wrong to set IsRefreshing to True and have to rely on the binding to some UI control to re-enter the ViewModel via the bound Command.

**Comment by PureWeen** [comment]
@JunkyXL86 I don't quite follow this effect

> Now with XF RefreshView the Command is fired additionally whenever I set IsBusy = true which calls LoadData() a second time.

If you're setting IsBusy to true from the Command that's fired from pull too fresh than it should be a noop because IsRefreshing should already be set to true. So there's either a bug here or I'm just not understanding what you're describing here

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
