### ISSUE TITLE
[Bug] Pages created by Shell.Current.GoToAsync are not re-used or disposed of

### ISSUE THREAD

**Issue by nwilliams** [xamarin/Xamarin.Forms#11476]
### Description
`Shell.Current.GoToAsync` creates a new instance of the requested page every time it's called and that new instance appears to reside in memory indefinitely. Aside from the implied memory leak, this also causes problems when the page is a subscriber via the `MessengingCenter`. In the attached example, I'm using the `MessagingCenter` to handle navigation in the app (also using `Shell.Current.GoToAsync`) based on commands in the view-model. If you add a breakpoint to line 23 of ItemDetailPage.xaml.cs you can see that the callback is invoked once for every "Item Detail" page that has been opened.

### Steps to Reproduce

1. Run the attached solution
2. Click on an item in the list to open the Item Detail page
3. Click the "Get Metadata" button
4. Navigate back to the root page
5. Open another Item Detail page and click on "Get Metadata"
6. Observe that an additional "metadata" page has been added to the navigation stack for each Item Detail page visited

### Expected Behavior
Pages created by `Shell.Current.GoToAsync` are either re-used or properly disposed of.

### Actual Behavior
`Shell.Current.GoToAsync` creates a new page for every invocation and that page resides in memory indefinitely.

### Basic Information

- Version with issue: 4.6.0.847
- Last known good version: N/A
- IDE: Visual Studio 16.6.4
- Platform Target Frameworks: 
  - iOS:   13
  - Android:  10
 

- Affected Devices: All

### Screenshots

![PagePersistenceIssue_resize](https://user-images.githubusercontent.com/204802/87826726-a3326700-c836-11ea-8ef2-85a3a15043e9.gif)

### Reproduction Link

[ShellPagePersistence.zip](https://github.com/xamarin/Xamarin.Forms/files/4940051/ShellPagePersistence.zip)

**Comment by nwilliams** [comment]
I've also tested with the latest stable release (4.7.0.1142) and the issue is still present.

**Comment by PureWeen** [comment]
@nwilliams I took a look at your sample and I'm pretty sure that this

> page resides in memory indefinitely.

Happens because of the Messaging Subscriber 

The Messaging Subscriber is going to retain a copy of your Page forever. You need to unsubscribe from it. 
I would subscribe in OnAppearing and Unsubscribe in OnDisappearing

I realize it creates a new page every time but this is something that's not really a bug. A lot of people want it to recreate every time and other people don't so what we more need is a way to let the user express what they want to achieve

**Comment by nwilliams** [comment]
@PureWeen

That's not what the documentation for the MessagingCenter says:

> Internally, the MessagingCenter class uses weak references. This means that it will not keep objects alive, and will allow them to be garbage collected. Therefore, it should only be necessary to unsubscribe from a message when a class no longer wishes to receive the message.


https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center

**Comment by PureWeen** [comment]
Yea but it's not going to be GC'd instantly you can't count on that WeakReference getting removed the instant the page is popped. It's just going to linger around until the GC runs and cleans up the reference.

In ItemsPage if you add the following code

```C#
        protected async override void OnAppearing()
        {
            base.OnAppearing();

            if (viewModel.Items.Count == 0)
            {
                viewModel.IsBusy = true;
            }

            await Task.Delay(1000); // Ensure the pop operation is done
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
            GC.WaitForPendingFinalizers();
        }
```

You'll notice the subscriber stops getting called

**Comment by nwilliams** [comment]
@PureWeen, thank you for the feedback. I was expecting the pages to immediately get disposed of or be re-used on subsequent calls to `GoToAsync` but that was apparently a misunderstanding on my part. Unfortunately, I can't leverage `OnAppearing` and `OnDisappearing` to handle message subscriptions in my application since the message sender is a modal page that gets opened from the page with the subscription. I'll have to experiment a bit to see if I can find a working solution, but in the meantime I'll go ahead and close this issue. I'd rather not call any methods on the garbage collector directly, but the code sample you provided may end up being the easiest path forward.

Thanks again.

**Comment by PureWeen** [comment]
@nwilliams is there any reason you're registering this inside the constructor on the page?

Can you just register it from somewhere that's initialized once? Like on app.xaml or appshell.xaml?

**Comment by PureWeen** [comment]
@nwilliams you can also register your own RouteFactory with register routes to manage global routes


```C#
 public partial class AppShell : Xamarin.Forms.Shell
    {
        public AppShell()
        {
            InitializeComponent();

            Routing.RegisterRoute("item-detail", new CustomFactory(typeof(ItemDetailPage)));
            Routing.RegisterRoute("metadata", typeof(MetadataPage));
        }
    }

    public class CustomFactory : RouteFactory
    {
        Type type;

        public CustomFactory(Type type)
        {
            this.type = type;
        }

        public override Element GetOrCreate()
        {
            throw new System.NotImplementedException();
        }
    }
```

**Comment by nwilliams** [comment]
@PureWeen, excellent suggestions -- I've never used a custom route factory so the thought never occurred to me. For the sake of simplicity I'll probably just move the problematic subscription to my AppShell code for now.

**Comment by PureWeen** [comment]
@nwilliams awesome!!

Yea you definitely don't want to trigger the GC yourself

My only suggestion would be if you're initializing it inside AppShell maybe do it as part of a static class or using a static property so you only init once.

Mainly for cases like android where if you background the app sometimes the AppShell will reinitialize

**Comment by kraeg75** [comment]
This makes very little sense.  If Page1 goes to Page2 and Page2 goes to Page3, then Shell.Current.GoToAsync(".."); goes back to a **new** instance of Page2 it all falls apart when you consider Page2's QueryProperty attribute.  Whatever value was fed to Page2 by Page1 has fallen out of context and is no longer available when Page3 navigates back to Page2.

**Comment by PureWeen** [comment]
> has fallen out of context and is no longer available when Page3 navigates back to Page2.

Can you test this on the latest 5.0 pre3?

**Comment by kraeg75** [comment]
@PureWeen  Application fails almost immediately.  On InitializeComponent on App class.

System.MissingMethodException: 'Method not found: bool Xamarin.Forms.Internals.ResourceLoader.get_IsEnabled()'

**Comment by PureWeen** [comment]
@kraeg75 make sure all your projects updated and if they did then delete out your bin/obj folders and see if that fixes

**Comment by kraeg75** [comment]
Hi @PureWeen.  I tried deleting all of the bin & obj folders, but this totally broke the build.  I do this all the time in my general .NET solutions, but Xamarin.Forms just doesn't like it.  Anyway, I managed to get everything working again with v5.0 pre3, but it behaves exactly as it did before.  Once I pop Page3 off the stack, I end up with a **new** instance of Page2 with null values pumped into its QueryProperty attibute.

The best I've been able to do is change the field fed by the QueryProperty to a static and ensure any existing value is not overwritten by null.

**Comment by kraeg75** [comment]
@PureWeen Okay, that's weird. The first time around it creates a new instance of Page2 when Page3 is popped, but after that Page2 gets reused.  I can go in and out of Page3 as many times as I like and end up back on the same instance of Page2.

**Comment by DaveBrickley** [comment]
I have this problem too. What I am unable to understand is how I can use Shell.Navigation.GoToAsync with a named global version of the template I wish to reuse? I figured if I declared that at the outset I could reuse it but I can't see any syntax which would allow me to do so?
