### ISSUE TITLE
# TimePicker Inconsistencies

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#11471]
# TimePicker Inconsistencies 

### Android 

On Android, it operates normally when the format string is "HH:mm". Both the picker and display on the TimePicker change to a 24-hour or 12-hour clock. The *Format* property also overrides the device settings if set. However, if the time format string has "HH" but isn't "HH:mm," then the display and picker have different formats. More specifically, the display is 24-hour while the picker is 12-hour.

### iOS 

On iOS, the *Format* property only changes the display of the TimePicker while the picker widget always maintains the device’s default culture. Thus, if the *Format* property is specified to be different than the operating system time format, the display and picker aren’t consistent.  

iOS also has two separate settings for region and language. However, if the region and language settings are set separately, then the TimePicker display and picker have different formats. For example, if the language is English and the region is France, then the picker is 24-hour while the display is 12-hour. 

### UWP 

Finally, on UWP, the TimePicker’s current *Format* property does not have any effect on the TimePicker on UWP. 

This bugfix will allow developers to get consistent default behaviour of the display and picker, as well as specify a *Format* property that will change both the display and picker widget accurately on all platforms. 

### Android Format

_Phone region: US, Format = "HH:m"_
<img src="https://user-images.githubusercontent.com/66331238/87083678-9daf9e00-c1f2-11ea-850d-313836a7f8c0.png" height="500"> 

### iOS Format 

_Phone region: US, Format = "HH:mm"_ 
<img src="https://user-images.githubusercontent.com/66331238/86801911-1dded380-c03a-11ea-8341-f72f80cf46d4.png" height="500"> 

### iOS Region vs. Language 

<img src="https://user-images.githubusercontent.com/66331238/86801970-2b945900-c03a-11ea-91d8-cc314ed3a3f2.png" height="500"> <img src="https://user-images.githubusercontent.com/66331238/86801978-2df6b300-c03a-11ea-9f87-08851ee20580.png" height="500">

### UWP 

_Format = "HH:mm"_
<img src="https://user-images.githubusercontent.com/66331238/86802099-46ff6400-c03a-11ea-8fc6-e0df89ec2430.png" height="300"> <img src="https://user-images.githubusercontent.com/66331238/86802082-4535a080-c03a-11ea-81c7-0baaa03d9442.png" height="300">

**_NOTE: [Here is a demo repo](https://github.com/memu8/DateTimeFormatTester) that illustrates what the format string changes on the TimePicker. Running this repo will show you what is happening in real time._**

## Implementation: 

We will parse the *Format* property, determine the clock type (12-hour or 24-hour), and then update the both the display and picker on the TimePicker (TimePicker Widget on Android, UITimePicker for iOS, and TimePicker ClockIdentifier on UWP) to use that clock. 

## Expected Result: 

If the region and language are set differently, then the TimePicker’s default format should follow the region’s cultural format. Both the display and the picker should stay consistent with the region’s default. 

If the *Format* property is set and the hour string in the TimePicker *Format* property is “HH,” then regardless of the device’s culture settings, both the TimePicker display and picker will both be in 24-hour. Similarly, if the hour string is “hh,” then both the TimePicker display and picker will both be in 12-hour. 

_If the Format property starts with “HH” (ex. “HH:mm” or “HH:mm tt”), then the expected result is a 24-hour clock display and picker regardless of device culture._

<img src="https://user-images.githubusercontent.com/66331238/86802187-5da5bb00-c03a-11ea-8316-b0ba01e5f51d.png" height="500">

_If the Format property starts with “hh” (ex. “hh:mm” or “hh tt”), then the expected result is a 12-hour clock display and picker regardless of device culture._

<img src="https://user-images.githubusercontent.com/66331238/86802219-66968c80-c03a-11ea-88b6-2981f4f49648.png" height="500">

## Example Usage: 

If the region and language are set differently, then the TimePicker’s default format should follow the region’s cultural format. Both the display and the picker should stay consistent with the region’s default. However, if the *Format* property is set, then it should override the region’s default. 

### Android and iOS Format: 

We are changing the effects of the *Format* property on the picker. There could be a potential issue if a developer wants the format of the display and the picker to be different. For example, if they deliberately wanted the display to be in 24-hour while the picker to be in 12-hour. Otherwise, there should be no significant changes that need to be made. 

### iOS Region vs. Language: 

We are changing the effects of the region and language on the TimePicker display format. There could be a potential issue if a developer wants the format of the display and the picker to be different. For example, if they deliberately wanted the display to follow language formatting while the picker to follows region formatting. Otherwise, there should be no significant changes that need to be made. 

### UWP: 

Since we are adding a feature and making the *Format* property accurately affect UWP TimePickers, there should be no compatibility problems. The only issue is if developers wanted the format string on TimePickers to not affect UWP applications.

_Originally posted by @memu8 in https://github.com/xamarin/Xamarin.Forms/discussions/11331_

**Comment by brigosx** [comment]
Hi to all,

I know that this issue is closed but I still face issues with iOS time picker. I have Xamarin Forms V5.0.0.2578 and applied custom renderers for both iOS and Android devices. For iOS devices (v 16.1 and greater) the time settings of the device overrides the format property (set to "HH:mm") and the custom renderer which has a code like the following one:

```
protected override void OnElementChanged(ElementChangedEventArgs<TimePicker> e)
{
	base.OnElementChanged(e);
        if (Control != null)
        {
            var timePicker = (UIDatePicker)Control.InputView;
            timePicker.Locale = new NSLocale("no_nb");
        }
}
```
The expected behavior would be to display the time view in 24 hours mode regardless of the device settings. It works fine in iOS simulator and Android devices.
