### ISSUE TITLE
[Bug] Frame VisualState Selected/Focused not working

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#11487]
# Description
We have a custom Button where the root element is of type Frame (Xamarin.Forms.Frame). We would like to change the BackgroundColor of this custom Button when it gets selected (like a pressed mode) -> the selected color should be applied for as long as the button gets pressed. 

### Steps to Reproduce

1. Have a Frame as your root element and add a VisualState for Selected and Focused
```XAML
<Frame Style="{StaticResource MyFrameStyle}"> 
    <!-- some ui here -->
</Frame/>

<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                    x:Class="Miele.Libraries.UiComponents.Atoms.Styles.FrameStyles">
    <Style x:Key="DisabledFrame" TargetType="Frame">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Disabled">
                        <VisualState.Setters>
                            <Setter Property="Opacity" Value="0.5" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Focused">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="LightSkyBlue" />
                            <Setter Property="Opacity" Value="0.5" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Selected">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="LightSkyBlue" />
                            <Setter Property="Opacity" Value="0.5" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Normal">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="{DynamicResource BackgroundSecondary}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>
</ResourceDictionary>
```
2. Start your app and select the created Button.

### Expected Behavior
BackgroundColor doesn't get changed on selcted. 
I've also tried to use the Focused and Unfocused events. But those aren't fired. Which is strange to me. 

### Actual Behavior
BackgroundColor should change when the custom Button gets selected.

### Basic Information

- Version with issue: Xamarin Forms 4.5.0.396
- Last known good version: -
- IDE: Rider / VisualStudio for Mac
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 9.0
- Android Support Library Version: AndroidX

### Workaround
No known workaround

**Comment by hartez** [comment]
@MaxFmi Are you setting the visual state in the code for your custom button? If so, how are you doing that?

**Comment by MaxFmi** [comment]
@hartez Nope, there is nothing written in code regarding the Selected/Focused state. The VisualStateManager shown in this issue is everything I've written.

**Comment by PureWeen** [comment]
@MaxFmi I don't quite follow your description as it relates to the sample

> We have a custom Button where the root element is of type Frame (Xamarin.Forms.Frame). We would like to change the BackgroundColor of this custom Button when it gets selected (like a pressed mode) -> the selected color should be applied for as long as the button gets pressed.

The visual state you've specified gets applied to the Frame so it's not going to style any of the buttons inside the frame it's only going to effect the frame itself

Visual State Groups don't propagate to the children

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Cvijo** [comment]
I have the same issue, even if you said it wont propagate to children my focused event never got called and I change border color so this should work on frame
