### ISSUE TITLE
[Enhancement] Need to aspect uniform on view clips

### ISSUE THREAD

**Issue by samt1925** [xamarin/Xamarin.Forms#11482]
## Summary
Cant aspect the clip of view from pathgeometry figures.

## API Changes

`     <yummy:PancakeView HorizontalOptions="FillAndExpand" BorderGradientAngle="45" VerticalOptions="FillAndExpand">
                    <yummy:PancakeView.Clip>
                        <PathGeometry Figures="M285.257,35.528c58.743,0.286,106.294,47.836,106.58,106.58
		c0,107.624-195.918,214.204-195.918,214.204S0,248.165,0,142.108c0-58.862,47.717-106.58,106.58-106.58l0,0
		c36.032-0.281,69.718,17.842,89.339,48.065C215.674,53.517,249.273,35.441,285.257,35.528z" >
                        </PathGeometry>
                    </yummy:PancakeView.Clip>
                    <yummy:PancakeView.BackgroundGradientStops>
                        <yummy:GradientStopCollection>
                            <yummy:GradientStop Color="#FF0000" Offset="0" />
                            <yummy:GradientStop Color="#00FF00" Offset="0.5" />
                            <yummy:GradientStop Color="#0000FF" Offset="1" />
                        </yummy:GradientStopCollection>
                    </yummy:PancakeView.BackgroundGradientStops>
                </yummy:PancakeView>`

Need to set aspect as uniform for the clip path for control to size of it.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
