### ISSUE TITLE
[Bug] Xamarin Forms Maps reload on navigating page

### ISSUE THREAD

**Issue by SnapADrag0n** [xamarin/Xamarin.Forms#11488]
### Description
Xamarin Forms Maps reload and move to **LastMoveToRegion** every time on navigating a page, even after using an existing instance of page:
`Detail = new NavigationPage(mapInstance);`

This also clears any marked pins on map, so it is not just Maps moving but a complete reload as I understand it.
### Steps to Reproduce

1. Instantiate and store page reference in **mapInstance**
2. Navigate to page and move map using **MoveToRegion()**
3. Now, move map manually and switch to some other page
4. Navigate back to the map page using the stored page reference - _At this point, you will notice that map has reloaded and moved_

### Expected Behavior
Map should resume in its last location, zoom and pins
### Actual Behavior
Map reloads
### Basic Information

- Version with issue: Xamarin.Forms V4.5.0.657, Xamarin.Forms.Maps V4.5.0.657
- IDE: Visual Studio 2019 V16.6.3
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.3
- Affected Devices: Samsung Galaxy A5 (Possibly all)

### Screenshots

![Map Reload Issue](https://us.v-cdn.net/5019960/uploads/editor/k3/45p269rladzv.gif)

### Reproduction Link

https://github.com/SnapADrag0n/Recentering-MapNavigation

**Comment by SergioJoel98** [comment]
As a workaround you could save the last known location using Xamarin.Essentials.Preferences on the call to OnDisappearing() and then retrieve them on the call to OnAppearing() to add them to the Maps control if they aren't null.

**Comment by SnapADrag0n** [comment]
> As a workaround you could save the last known location using Xamarin.Essentials.Preferences on the call to OnDisappearing() and then retrieve them on the call to OnAppearing() to add them to the Maps control if they aren't null.

I had considered it already but I have complex logic written on Appearing, Disappearing, Map Move etc, so I don't want to be messing with all of them with this workaround.

**Comment by hartez** [comment]
> Xamarin Forms Maps reload and move to LastMoveToRegion every time on navigating a page, even after using an existing instance 

Unfortunately, yes - the map will show the default location on load by default. It still remembers your last viewed region, it just doesn't move the camera to that region unless you tell it to. Modifying this behavior would be a breaking change, so for now you'll just have to use the workaround of moving to the region when the page loads. Adding the following to your `MapsPage` constructor should cover it:

```
Appearing += (sender, args) => {
    if (customMap.VisibleRegion != null)
    {
        customMap.MoveToRegion(customMap.VisibleRegion);
    }
```

> This also clears any marked pins on map, so it is not just Maps moving but a complete reload as I understand it.

The pins are not cleared. They _will_ show up when you navigate back to the page. You repro project doesn't seem to have any place where it adds pins; but you can easily add them and see this behavior. In your `MapsPage` constructor, just add

```
customMap.MapClicked += (sender, args) => {
    customMap.Pins.Add(new Xamarin.Forms.Maps.Pin() { Position = args.Position, Label = "pin" });
};
```

and you'll get a pin set anywhere you click on the map. If you navigate away and back, you'll see that the pins are still there:


![maps2](https://user-images.githubusercontent.com/538025/88566533-62371100-cff3-11ea-9212-5f346661cb64.gif)
