### ISSUE TITLE
[Bug] 4.8-pre1: TextTransform not implemented on several controls

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11499]
### Description

If you take a look through the files for the text transform [PR](https://github.com/xamarin/Xamarin.Forms/pull/3690), the `TextTransform` property has been implemented on the following controls (in Xamarin.Forms.Core):

- Button
- DatePicker
- InputView (hence Editor, Entry, SearchBar)
- Label
- Picker
- SearchHandler
- Span
- TimePicker

These are the controls that implement `ITextElement`, which provides the `TextTransform` property.

However, `TextTransform` doesn't work on:

- Span
- Picker
- DatePicker
- TimePicker

It's obvious from the changes in the PR that it won't work on at least the three Picker controls.

I think that [Issue3667](https://github.com/paymicro/Xamarin.Forms/blob/499f07a05e3da9870a58e5dc863bbe25f8ca6761/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue3667.cs) needs extending to include a test for Span. Then decisions need to be made about the Picker controls.

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

Text displayed by each control should be in upper case (aside from TimePicker, which should be lowercase). 

### Actual Behavior

Text isn't uppercase for the Span, or three Picker controls.

### Basic Information

- Version with issue: 4.8-pre1
- IDE: VSMac 8.6.6
- Platform Target Frameworks: 
  - iOS: 13.6
  - Android: API 28

### Screenshots

iOS:

![Simulator Screen Shot - iPhone 11 - 2020-07-21 at 13 23 14](https://user-images.githubusercontent.com/8092460/88056597-bad05f00-cb58-11ea-80d5-9ce008758fae.png)

Android:

![Screenshot_1595334256](https://user-images.githubusercontent.com/8092460/88056611-bdcb4f80-cb58-11ea-9aad-1eb3ac5716cc.png)

### Reproduction Link

[Disaster.zip](https://github.com/xamarin/Xamarin.Forms/files/4953568/Disaster.zip)

**Comment by davidbritch** [comment]
In addition, when `Entry` and `Editor` use an uppercase text transform, any additional characters entered (beyond those initially set) will be in uppercase. However, the same can't be said for `SearchBar` on iOS (Android is fine), where entered characters are as per your keyboard setting, rather than as per the `TextTransform` value.

**Comment by NunoBem** [comment]
Should this be in a XF service release @jfversluis ?

**Comment by jfversluis** [comment]
It probably should! I'm going to be honest though, not sure how high this would rank in terms of priority right now. If you're up for it you could give a shot at fixing it?

**Comment by NunoBem** [comment]
> It probably should! I'm going to be honest though, not sure how high this would rank in terms of priority right now. If you're up for it you could give a shot at fixing it?

Would be a first for me! Feeling very "noob" but will search how to contribute.

**Comment by jfversluis** [comment]
@NunoBem let's make it a 2022 goal ;) Let me know if you need anything

**Comment by jfversluis** [comment]
Hey @NunoBem for .NET MAUI we have decided not to implement this for Picker anymore as there is confusion around the APIs. Therefore it also doesn't make a lot of sense to implement this in Xamarin.Forms anymore. Closing this one. But let me know if you want to contribute somewhere else, we'll find something!

**Comment by NunoBem** [comment]
> Hey @NunoBem for .NET MAUI we have decided not to implement this for Picker anymore as there is confusion around the APIs. Therefore it also doesn't make a lot of sense to implement this in Xamarin.Forms anymore. Closing this one. But let me know if you want to contribute somewhere else, we'll find something!

Hey @jfversluis so this applies to all the Pickers? How about the Label Span? 

> However, TextTransform doesn't work on:
> 
> Span
> Picker
> DatePicker
> TimePicker
