### ISSUE TITLE
Cannot reload Image.Source from stream

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11495]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1110285/cannot-reload-imagesource-from-stream.html)._

---
<p>I have and Image that gets added on an AbsoluteLayout on runtime. The Image.Source is from a MemoryStream:</p><pre> System.IO.MemoryStream pictureBytes = new System.IO.MemoryStream(rowType.Picture);
 //(rowType.Picture is a BLOB field on a SQLite table 
 Image deviceImage = new Image();
 deviceImage.Source = ImageSource.FromStream(() =&gt; pictureBytes);
 AbsoluteLayout.SetLayoutBounds(deviceImage, new Rectangle(0, 0, RowDevice.Width, RowDevice.Height));
 thisAbsoluteLayout.Children.Add(deviceImage);
 </pre><p>This code always worked fine but recently (possibly since last updated Xamarin.Forms 4.7.0.1080) I am having an issue.</p> <p>Now the ImageSource still loads fine but it I minimize the window (suspend) and then restore it (resume) the picture disappear.</p> <p>I get this error message in the Output in Visual Studio:</p><p>Image loading: Image load failed: System.NotSupportedException: Cannot use the specified Stream as a Windows Runtime IRandomAccessStream because this Stream does not support seeking.
   at System.IO.WindowsRuntimeStreamExtensions.AsRandomAccessStream(Stream stream)
   at Xamarin.Forms.Platform.UWP.StreamImageSourceHandler.LoadImageAsync(ImageSource imagesource, CancellationToken cancellationToken)
   at Xamarin.Forms.Platform.UWP.ImageExtensions.ToWindowsImageSourceAsync(ImageSource source, CancellationToken cancellationToken)</p><p></p><p>Looks to me like when the app is suspended the pictures get unloaded (free up memory?) but then the runtime cannot find them anymore.</p>

---
#### Feedback Bot on 7/12/2020, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sude22** [comment]
I can confirm this issue with 4.7.0.1179

**Comment by samhouts** [comment]
@sude22 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sude22** [comment]
@samhouts Sorry, I created a small project, but the error is not reproducible :(

**Comment by rmarinho** [comment]
Thanks please reopen when you can reproduce the issue.

**Comment by Realgigabyte** [comment]
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/5262948/App1.zip)

Hi, I created a sample app that reproduce the issue.
Please run the UWP project. Database should copy by itself and you will see an icon loaded from the database.
When the app is suspended and resumed the icon disappear (error described above).

**Comment by Realgigabyte** [comment]
> Thanks please reopen when you can reproduce the issue.

I posted a sample project in comment. Can the issue be reopened?

**Comment by sude22** [comment]
I would also vote for reopen this issue.

**Comment by rrodriguez-consulting** [comment]
I have the same problem

**Comment by sude22** [comment]
@rmarinho @samhouts Since there is a small project that demonstrates the issue, could you please reopen this bug?

**Comment by Realgigabyte** [comment]
Hi,

this is still not working. Is anybody monitoring this thread or would be better to open a new one?

**Comment by tstrickler4** [comment]
I noticed the description for FromStream says "The delegate provided to stream must return a new stream on every invocation." With that in mind, I was able to get mine working by moving the MemoryStream directly into the FromStream function, going from this:

    var stream = new MemoryStream(bytes);
    var imgSource = ImageSource.FromStream(() => stream);

to this:

    var imgSource = ImageSource.FromStream(() => new MemoryStream(bytes));

**Comment by sude22** [comment]
@tstrickler4 : Thank you very much for that hint. 
For my defense, in the [docs ](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.imagesource.fromstream?view=xamarin-forms)it is not mentioned that it has to be a new memorystream.

Your solution is working for me, too.

**Comment by Realgigabyte** [comment]
@tstrickler4 Thank you very much! This works perfectly now.

**Comment by tstrickler4** [comment]
@sude22 @Realgigabyte Glad I could help!

**Comment by mrobraven** [comment]
In some cases (IE where the MemoryStream is used elsewhere) the above solution won't work

**Comment by 21r8390** [comment]
If you make something with the stream before or after, the ImageSource doesn't load it. Even if you copy it to a new stream. Please fix that!

My Method:
`

	private async Task<string> LoadImgAndBase64()
	{
		FileResult img = await MediaPicker.PickPhotoAsync();

		Stream stream = await img.OpenReadAsync();
		ImageSource imgSrc = ImageSource.FromStream(() => stream); //Doesn't load stream

		string base64 = string.Empty;
		using (var ms = new MemoryStream())
		{
			await stream.CopyToAsync(ms);
			base64 = Convert.ToBase64String(ms.ToArray());
		}

		return base64;
	}
`
