### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Forms#11503]
Xamarin Forms 4.7.xxx
Visual Studio 2019 16.6.4

Building an app for iOS and uploading the IPA to the app store still works but I keep getting this email:

> Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.

The thing is that I am not using any web view...please advise? Thank you.

**Comment by PureWeen** [comment]
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
