### ISSUE TITLE
[Bug] UWP Shell Crashes in Xamarin Forms 4.7

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#11505]
### Description

After upgrading a very basic test app from Xamarin Forms 4.5 to 4.7, the Shell now crashes on start.

```
Invalid pointer

Cannot find a resource with the given key: ShellNavigationView.
```

### Steps to Reproduce

1. Create a new Blank Xamarin Forms app with UWP support.
2. Enable experimental shell support in the UWP project.
3. Follow this steps in the sample: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/create
4. Run the UWP project.

### Basic Information

- Version with issue: 4.7.0.1142
- Last known good version: 4.5.0.495
- IDE: Visual Studio 2019 Version 16.6.5
- Platform Target Frameworks: 
  - UWP:  17763 
- Nuget Packages:

    <PackageReference Include="Xamarin.Forms" Version="4.5.0.495" />
    <PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform" Version="6.1.9"/>
    <PackageReference Include="Xamarin.Essentials" Version="1.3.1" />

### Reproduction Link

https://github.com/scottkuhl/Xamarin-Forms-UWP-Shell-Bug

**Comment by PureWeen** [comment]
@scottkuhl If you set your target to `18362` does that fix?

**Comment by scottkuhl** [comment]
Yes, that does fix the issue.  Is 1903 a requirement for Shell on Windows?  Or this is just a bug?

**Comment by PureWeen** [comment]
@scottkuhl I would say it's a bug

The NavigationView that shell is based on works on `version 1809 (SDK 17763)` so it should work with the target frameworks you've specified

**Comment by ksang77** [comment]
having the same issue on UWP startup after i upgraded xamarin form from 3.4.0.1008975 to 4.8.0.1269, unfortunately VS2017 forced the UWP project to use 17763 even i changed to 18362 by editing the project file backdoor.
