### ISSUE TITLE
[Bug] UWP CarouselView change displayed image via mouse scroll not working since 4.6.0.967

### ISSUE THREAD

**Issue by janduldhardt** [xamarin/Xamarin.Forms#11506]
### Description
After updating the Xamarin.Forms nuget from 4.6.0.800 to 4.6.0.967 it is not possible to change the current image on the CarouselView in UWP. Tested also with prelease of 4.8.01143-pre1 and not working.

### Steps to Reproduce

1.  Implement CarouselView on page.
2.  Populate CarouselView via ImageSource and data binding in ViewModel
3.  Open the application and page with the CarouselView with more than 1 image and try to change the image with scrolling the mouse wheel.

### Expected Behavior
Scrolling the mouse wheels changes the displayed picture.

### Actual Behavior
Scrolling the mouse wheel has no effect, current displayed image never changes.

### Basic Information

- Version with issue: 4.6.0.967
- Last known good version: 4.6.0.800
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  18362
- Nuget Packages: Xamarin.Forms
- Affected Devices:

### Reproduction Link

If needed I can create a sample

### Workaround
No workaround

**Comment by hartez** [comment]
Can confirm.

**Comment by hartez** [comment]
[_11506 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4976860/_11506.Repro.zip)

**Comment by EmilAlipiev** [comment]
is this not related and fixing this issue? https://github.com/xamarin/Xamarin.Forms/pull/11629
Can you try using 4.8?

**Comment by TaiPhamDuc** [comment]
This problem still happened to me on version 4.8.0

**Comment by rmarinho** [comment]
This should be fixed on next 4.8.0 service release  and 5.0.0
