### ISSUE TITLE
[Bug] FlyoutBehavior.Disabled removes back-button from navbar in 4.7sr3

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/Xamarin.Forms#11523]
### Description
Just after updating to 4.7 sr3, the back-button in the navbar (when a page is pushed via Navigation.PushAsync) disappears if FlyoutBehavior is set to Disabled. This was not the case with previous versions.

### Steps to Reproduce

Set Shell.Current.FlyoutBehavior = FlyoutBehavior.Disabled; in the OnAppearing

### Expected Behavior
FlyoutBehavior.Disabled should disable the flyout to be shown when the user swipes right but not disable the back button in the navbar.

### Basic Information

- Version with issue: 4.7 sr3
- Last known good version: 4.7 sr2
- Platform Target Frameworks: 
  - Android: Android 9 / 10

**Comment by PureWeen** [comment]
Thank you for the report @inimirpaz this should be fixed in the next 4.7 SR

https://github.com/xamarin/Xamarin.Forms/pull/11526
