### ISSUE TITLE
[Enhancement] Allow text control TextChanged event to coerce the new value.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms#11524]
## Summary

When the text in an `Entry` changes, business requirements may dictate coercing it from an invalid value to a valid value, or at least refusing the input. This is possible inside `Entry` itself because `BindableProperty` provides coercion *and* its change handler provides both the previous value and the new value.

The `TextChanged` event should allow handlers to manipulate the new value and provide a coerced new value without reentrancy. 

## API Changes

The `TextChangedEventArgs` type already provides the `NewTextValue` and `OldTextValue` properties. This feature could be facilitated by making `NewTextValue` a writable property. If, after raising the event, `NewTextValue` has changed, the `Entry`'s text should adopt that value without raising another change event.

(I do hesitate at declaring the above "simple". If a "late" event handler modfies the value to something an "early" event handler would consider invalid, things get weird. Perhaps I should be asking for some kind of more strict `NumericEntry` instead.)

## Intended Use Case

In my applications, I often need to make a text input that requires specific inputs, such as integers within a range. My requirements usually ask me to ensure if a user types an invalid string, such as "1234a", I coerce that value back to a valid value such as "1234". 

This can be done by handling the `TextChanged` event, but avoiding infinite loops due to reentrant event handlers is often difficult. A basic use case might look like:

    void WhenTextChanges(object sender, EventArgs e)
    {
        if (!int.TryParse(theEntry.Text, out int value))
        {
            theEntry.Text = EntryMinimum.ToString();
        }
    }

Since this event handler sets the `Text` property, it causes other handlers to be raised again and for bindings to update. I've found many scenarios where the old value lingers and raises the event again, causing an infinite reentrant loop. (This seems particularly true of bindings.) 

(A numeric keyboard only goes so far: users can still paste incorrect values into the Entry.)

In WPF, I'd derive from `Entry` and use `DependencyProperty.AddOwner()` to set a new coercion handler for the `Text` property. Xamarin Forms lacks this functionality. Aside from writing a custom renderer and trying to recreate Entry, I don't see another clear way to implement this use case.

Another situation that comes to mind is auto-formatting values for the user. Suppose a field expects a US phone number. The user could type "5551234567" and that could render as "(5)", "(55)", "(555)", "(555) 1  -" etc. as they type. This is difficult to achieve while maintaining appropriate cursor location as is.

**Comment by AmrAlSayed0** [comment]
I usually just do this
```csharp
if(!theEntry._isChangingTextProperty)
{
    if (!int.TryParse(theEntry.Text, out int value))
    {
        theEntry._isChangingTextProperty = true;
        theEntry.Text = EntryMinimum.ToString();
        theEntry._isChangingTextProperty = false;
    }
}
```

**Comment by SittenSpynne** [comment]
@AmrAlSayed0 
That's more or less what we've done, looks like I forgot the boolean in the initial code sample. I've *still* had problems with this in scenarios where multiple elements bind to that property. Something about the order of bindings and events causes an infinite loop in really specific cases, but it'd take me a while to try and reproduce those cases.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
