### ISSUE TITLE
[Bug] Using the same Binding value in base property and datatrigger binding scrambles the result

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/Xamarin.Forms#11539]
# Description
I noticed that when the following is at play the output you get is not correct: you bind something (eg Text and TextColor of a Label) to an enum-type public field, using converters to get a compliant value for the given property type in the XAML, then you also add a datatrigger to "override" one of the cases the converters output.
**See sample project in attachments.**

### Steps to Reproduce

1. Have an enum-type field
2. Have converterers for such an enum
3. In the XAML, bind to the enum-type field using the converter (eg. enum-to-text for a label)
4. Also in the XAML, provide a datatrigger that overrides the value for a given value of the enum that would be provided by the converter otherwise.

E.g.
```
        <Label Text="{Binding MyField, Converter={StaticResource TestLabel}}" TextColor="{Binding MyField, Converter={StaticResource TestColor}}" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" />

        <Label Text="{Binding MyField, Converter={StaticResource TestLabel}}" TextColor="{Binding MyField, Converter={StaticResource TestColor}}" HorizontalOptions="Center" VerticalOptions="CenterAndExpand">
            <Label.Triggers>
                <DataTrigger TargetType="Label" Binding="{Binding MyField}" Value="{x:Static this:TestEnum.FIRST}">
                    <Setter Property="TextColor" Value="White" />
                    <Setter Property="Text" Value="OTHER_VALUE" />
                </DataTrigger>
            </Label.Triggers>
        </Label>
```

### Expected Behavior
Get the values provided from the converter(s) as the "base-case", get the overridden value provided from the datatriggers if there are any.

### Actual Behavior
You get mixed results. For instance, you get the correct output for the overridden case, but you get the opposite result for a non-overridden value of the bound property.

### Basic Information

- Version with issue: 4.7
- Last known good version: N/A
- IDE: VS for Mac Pro
- Platform Target Frameworks:
  - iOS: Tested on 13.5.1 / 13.6
  - Android: Tested on 9 and 10

### Workaround

Make proxy public fields in the viewmodel that handles the overriding of the values, one for each property you need to bind (e.g. one for the Text, another for the TextColor, ...)

**SAMPLE PROJECT**
[DataTriggerBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4970568/DataTriggerBug.zip)
Tap on the page to make the viewmodel swap the field between the two enum values.

**Comment by hartez** [comment]
Here is what I _think_ is happening to the second Label:

1. The model value is set to FIRST. The Text and TextColor properties are bound to it, run it through the converters, and end up with the values "First" and "Green".
2. After that, the DataTrigger kicks in; the value FIRST matches its criteria, so the DataTrigger's Setters are applied, and we end up with the values "OTHER_VALUE" and "White". The previous values for those properties, at this point in time, would be "First" and "Green" - i.e., if you unapplied that DataTrigger right now, those are the values which would apply to the Label. 
3. The model value is set to SECOND. The Label's Text and TextColor values get set to "Second" and "Red".
4. Now the DataTrigger kicks in again; the model value no longer matches, so the DataTrigger unapplies itself. The cached values (from when it was initially applied) are "First" and "Green". So those values are applied to the Label.

While this is counter intuitive at first, I'm not sure it's a bug. How should the DataTrigger handle unapplying differently?

**Comment by holecekp** [comment]
I had a similar problem also without value converters. In my case, it was a simple validation for an Entry. There was a DataTrigger which should set red color when the text in the Entry was not valid. This worked well with AppThemeColor and DynamicResource in 4.6. However, AppThemeColor was later replaced by AppThemeBinding in 4.7 and it stopped working. I had to add another DataTrigger for setting the original color back manually. This can be used as a workaround but only for simple cases when the original color is known. I am including a simplified code for the old version with AppThemeColor and the new version with the workaround for AppThemeBinding.

Xamarin.Forms 4.6 (TextColor and ErrorTextColor are AppThemeColors):
```xml
<Entry Text="{Binding Answer, Mode=TwoWay}"
       TextColor="{DynamicResource TextColor}">
    <Entry.Triggers>
       <DataTrigger Binding="{Binding AnswerContainsInvalidCharacters}" Value="True" TargetType="Entry">
           <Setter Property="TextColor" Value="{DynamicResource ErrorTextColor}" />
        </DataTrigger>
    </Entry.Triggers>
</Entry>
```

Xamarin.Forms 4.7 with the workaround:
```xml
<Entry Text="{Binding Answer, Mode=TwoWay}"
       TextColor="{AppThemeBinding Light={StaticResource TextColorLight}, Dark={StaticResource TextColorDark}}">
    <Entry.Triggers>
        <DataTrigger Binding="{Binding AnswerContainsInvalidCharacters}" Value="True" TargetType="Entry">
            <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource ErrorTextColorLight}, Dark={StaticResource ErrorTextColorDark}}" />
         </DataTrigger>

         <!-- The color is not reverted back in 4.7 so I need another DataTrigger to set it back manually -->
         <DataTrigger Binding="{Binding AnswerContainsInvalidCharacters}" Value="False" TargetType="Entry">
             <Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource TextColorLight}, Dark={StaticResource TextColorDark}}" />
        </DataTrigger>
    </Entry.Triggers>
</Entry>
```

**Comment by inimirpaz** [comment]
> Here is what I _think_ is happening to the second Label:
> 
>     1. The model value is set to FIRST. The Text and TextColor properties are bound to it, run it through the converters, and end up with the values "First" and "Green".
> 
>     2. After that, the DataTrigger kicks in; the value FIRST matches its criteria, so the DataTrigger's Setters are applied, and we end up with the values "OTHER_VALUE" and "White". The previous values for those properties, at this point in time, would be "First" and "Green" - i.e., if you unapplied that DataTrigger right now, those are the values which would apply to the Label.
> 
>     3. The model value is set to SECOND. The Label's Text and TextColor values get set to "Second" and "Red".
> 
>     4. Now the DataTrigger kicks in again; the model value no longer matches, so the DataTrigger unapplies itself. The cached values (from when it was initially applied) are "First" and "Green". So those values are applied to the Label.
> 
> 
> While this is counter intuitive at first, I'm not sure it's a bug. How should the DataTrigger handle unapplying differently?

Sorry to answer your question with a question but I think it could better explain my point of view: what would you do if you need to (e.g.):

- Set XAML properties based on a enum-type value binding using a converter
- Override some specific case of the values returned by the converter
?

I have two options (workarounds?): drop the "using a converter" statement, thus using just DataTriggers for each item of the enum in XAML... but that would lead to duplicating in every XAML page that handles the same enum-type values and scarce code maintainability. Or, you could do the enum-to-whatever in the ViewModel with a new exposed field that handles the enum of the model. Or variations of the two options.

How would you handle such a scenario?

**Comment by hartez** [comment]
[Sorry it took me so long to get back to this.]

@inimirpaz To be honest, if I needed that much control for specific cases, I'd probably just put that logic into my view model and be done with it.

But if you're looking to have a generic set of converters which can handle some exceptional cases, it's possible to do it. You just need a way to specify which properties should be using the exceptional cases, and what the values should be for those cases. We can make this work with converter parameters.

First we need something to hold enum/value information; we'll create a class:
```
public class EnumValueOverride
{ 
    public TestEnum TestEnumValue { get; set; }
    public Color Color { get; set; }
    public string Text { get; set; }
}
```

Next we'll update our converters so they understand `EnumValueOverride` as a parameter:

```
public class TestConverterColor : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        var inputValue = (TestEnum)value;

        if (parameter is EnumValueOverride @override) 
        {
            if (inputValue == @override.TestEnumValue) 
            {
                return @override.Color;
            }
        }

        return inputValue switch
		{
			TestEnum.FIRST => Color.Green,
			TestEnum.SECOND => Color.Red,
			_ => throw new NotImplementedException(),
		};
    }
}
```

Now we can create an override value in our XAML page:

```
<ContentPage.Resources>
    <ResourceDictionary>
        <this:TestConverterColor x:Key="TestColor" />
        <this:EnumValueOverride x:Key="FirstOverride" TestEnumValue="FIRST" Color="White" Text="OTHER_VALUE" />
    </ResourceDictionary>
</ContentPage.Resources>
```

And anywhere we want to have this overridden value, we can simply pass it in as a converter parameter:

```
<Label Text="{Binding MyField, Converter={StaticResource TestLabel}, ConverterParameter={StaticResource FirstOverride}}" 
        TextColor="{Binding MyField, Converter={StaticResource TestColor}, ConverterParameter={StaticResource FirstOverride}}" />
```

Now we don't need the data trigger at all - the override information is in the EnumValueOverride. 

Here's an updated version of your example project with this implemented:
[ConverterParameterExample.zip](https://github.com/xamarin/Xamarin.Forms/files/5314991/ConverterParameterExample.zip)

Of course, if you need more flexibility you could create a parameter class with multiple enum values, or make it a Collection; whatever works for the flexibility you need.
