### ISSUE TITLE
[Enhancement] Prioritise bugs based on severity and direct development efforts there

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11538]
Is there any possibility you could change your planning to prioritise fixing crash bugs? Maybe a priority system such as this would help:
1: Crash bugs
2: Internals
3: OS parity
4: Other bugs
5: New features

* Crash bugs: Obvious
* Internals: XAML parser and bindings, converters, lifecycle model etc. There's quite a lot of issues with them currently, such as XAML bindings having to be written differently depending on what is being accessed, converters not properly supporting bindings etc. The core of Xamarin.Forms should be absolutely rock solid as it is the programming model people interact with the most.
* OS parity: Expose any and all OS native controls to Xamarin.Forms. This is the reason people use Xamarin.Forms.
* Other bugs: Annoyances that can be worked around.
* New features: The core should be rock solid before any 'convenience' things are introduced, and often developers would like to develop them in-house anyway, as that is their job.

If crash bugs can't be prioritised, they can't be worked around via hacks or by changing the design, and effort will not be put towards fixing them - what is the recommended way of proceeding? A lot of developers have committed to Xamarin and I have yet to find any official support channel or such where a resolution is guaranteed. It adds a lot of risk as if you run into a blocker there is no guarantees that it will get resolved. Just one example is the crash at https://github.com/xamarin/Xamarin.Forms/issues/6387 that has been open for over a year.

Thank you for considering.

**Comment by jfversluis** [comment]
Thanks for your suggestions, here and in other issues and discussions as well! I love your passion for this project.

We've been discussing this like these in some other issues, so I will close this here for now :)
