### ISSUE TITLE
[Bug] Editor set binding mode as TwoWay often throw ObjectDisposedException

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/Xamarin.Forms#11531]
### Description
set binding mode as TwoWay ,modify viewmodel property when target Editor not show and than throw ObjectDisposedException.

### Expected Behavior
not crash

### Basic Information

- Version with issue:
- Last known good version:4.2.0.778463
- IDE:visual studio 2017 15.9.2
- Platform Target Frameworks: 
  - Android: 8.1 
- Android Support Library Version: 28.0.0.1

### Screenshots

![image](https://user-images.githubusercontent.com/1481403/88355428-1be57600-cd97-11ea-8f24-ea6ff813532d.png)

**Comment by hartez** [comment]
@llzz19851985 On which version of Forms are you currently seeing this problem?

**Comment by llzz19851985** [comment]
@hartez problem version of xamarin is 4.2.0.778463

**Comment by hartez** [comment]
> Last known good version:4.2.0.778463

@llzz19851985 So, 4.2.0.778463 is not a "known good version", then. :) Does this problem persist if you upgrade Xamarin.Forms to the latest stable (4.7)?

**Comment by llzz19851985** [comment]
@hartez because some reason,I cannot update xamarin forms to vetsion 4.7,so I not test.
I overwrite the editor renderer and remove Text binding on Disponse(),so far it does not appear again .

**Comment by PureWeen** [comment]
@llzz19851985 what errors are you seeing when updating to 4.7? 

There have been a lot of fixes in this area between 4.2 and now so I'm hoping updating will resolve for you.

**Comment by llzz19851985** [comment]
@PureWeen sorry, my mistake,I didn’t express it clearly,I can update 4.7 successful,but my product limit android sdk(19) and always use 4.2.0.778463,i do not want update to 4.7,it is risky to my product,so i cannot use xamarin 4.7

**Comment by PureWeen** [comment]
@llzz19851985 4.7/4.8 should support sdk(19) just as well as 4.2

If you're seeing issues there please let us know

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
