### ISSUE TITLE
[Enhancement] Need page appeared and disappeared events

### ISSUE THREAD

**Issue by dgandhi17** [xamarin/Xamarin.Forms#11533]
## Summary
The page appearing event is still too early before even page draws and some time the required rendering of controls won't happen which bounds we might required to alter. Is it possible to have page appeared event which ensure that all controls layouting is done and available to trace all controls bounds and apply logic

## API Changes

We can trigger this event from platform depended on drawing function which once done.

e.g.

For example 

## Intended Use Case
Let's say I want to add tooltip for a control but that logic we can't get it from page appearing, as by this time we might not have controls exact bounds.

**Comment by irinakush** [comment]
Is there a workaround for this for now?

**Comment by isax5** [comment]
I'll like something like this!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
