### ISSUE TITLE
[Bug] Not show backbutton in Shell Tab

### ISSUE THREAD

**Issue by alex-relov** [xamarin/Xamarin.Forms#11535]
### Description
Not show backbutton on children pages in Shell TabBar after upgrading 4.7.0.1179 on android devices.
### Steps to Reproduce

1. Start App on android device
2. Press page1 button

### Expected Behavior
show back button
### Actual Behavior
back button not visible
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: Emulator api 29
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/26199529/88364885-c19be380-cd9d-11ea-8842-9c567728cdca.png)
4.7.0.1179 - back button not visible
![image](https://user-images.githubusercontent.com/26199529/88365057-4981ed80-cd9e-11ea-95d4-cfb79eedf43a.png)
4.7.0.1142 - all ok

### Reproduction Link

https://github.com/alex-relov/TabBarBug

**Comment by PureWeen** [comment]
This should be fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/11526
