### ISSUE TITLE
[Bug] Incorrect cursor behavior in Editor control

### ISSUE THREAD

**Issue by HugoSanchezGarcia** [xamarin/Xamarin.Forms#11544]
Hello everybody,
In our project we have an editor control that loads long texts that our users need to edit.
The problem it's that when you select text in the middle of a phrase or mostly anywhere in the middle of the text, cursor makes weird stuff.

### Steps to Reproduce

Create an entry with long text with paragraphs in xamarin forms, compile for IOS and try to change text in the middle.

### Expected Behavior

Writing exactly where the cursor is with normal behavior.

### Actual Behavior

Not deleting what it's supposed to, writing in wrong places...

### Basic Information

- Version with issue: Xamarin.Forms 4.7.0.1179
- Last known good version: This problem has been always present in IOS, Android seems Ok.

### Videos showing this bug

[Archivo comprimido.zip](https://github.com/xamarin/Xamarin.Forms/files/4971683/Archivo.comprimido.zip)

**Comment by hartez** [comment]
@HugoSanchezGarcia I'm trying to reproduce the issue you're seeing, but so far I've had no luck. Here is my repro attempt:

[_11544 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4974047/_11544.Repro.zip)

Running that on iOS, the Editor behavior doesn't match what's in your video. Is there a detail or setting I'm missing?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
