### ISSUE TITLE
[Bug][Shapes] Shapes demos has some invalid IL code once updated to 4.8-pre2

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11541]
### Description

I've just updated my Shapes demos sample from 4.7 to 4.8-pre2, in order to try Shapes with Brushes. As a result there are `InvalidProgramException`s in two pages.

### Steps to Reproduce

1. Run the attached sample 
2. Browse to the image clipping demo page or path geometry demo page.

### Expected Behavior

Pages load and work as expected.

### Actual Behavior

`InvalidOperationException` on those pages: Invalid IL code

System.InvalidProgramException: Invalid IL code in ShapesDemos.ClipDemoPage:InitializeComponent (): IL_04d6: box       0x01000054

  at ShapesDemos.ClipDemoPage..ctor () [0x00008] in /Users/davidbritch/repos/xamarin-forms-samples/UserInterface/ShapesDemos/ShapesDemos/Views/ClipDemoPage.xaml.cs:9 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936

### Basic Information

- Version with issue: 4.8-pre2
- Last known good version: 4.7
- IDE: VSMac 8.6.7
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: API 28

### Reproduction Link

[ShapesDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4971201/ShapesDemos.zip)

**Comment by StephaneDelcroix** [comment]
I suspect the issue comes from RectTypeConverter inheriting from RectangleTypeConverter, and the Xaml compiler picking the 'wrong' attribute, and the wrong return type, forcing a cast where it's not required

**Comment by IoTFier** [comment]
Hi @StephaneDelcroix ,
I tested the interim nuget package, and it failed for RECT API for the XAML sample that I provided in #11551 / step 3.

System.InvalidOperationException
  Message=The BindableProperty "Width" is readonly.

This was not the case before in the Struct Rectangle that is being replaced with RECT.
That means the fix for #11187  is still not valid

**Comment by StephaneDelcroix** [comment]
@IoTFier this step 3 
<img width="442" alt="image" src="https://user-images.githubusercontent.com/313003/88457678-a5c13c00-ce88-11ea-86e9-c60cb48358c2.png"> ?

**Comment by StephaneDelcroix** [comment]
you meant that `<Rect x:Key="TemplateLayoutBounds" HeightRequest="22" WidthRequest="{x:Static AbsoluteLayout.AutoSize}" X="1" Y="0.5" />`
