### ISSUE TITLE
[Enhancement] Make platform renderers generic

### ISSUE THREAD

**Issue by Inrego** [xamarin/Xamarin.Forms#11540]
## Summary
Use type parameters on platform-specific renderers, so that they're more easily extensible. Just like ViewRenderer has 2 type parameters, the types that implement it should keep these two parameters, but just add constraints on them. I will use the iOS implementation of SliderRender below as an example.

## API Changes
A generic version of SliderRenderer would look like: 

    public class GenericSliderRenderer<TView, TNativeView> : ViewRenderer<TView, TNativeView> where TView : Slider where TNativeView : UISlider

And then the exported renderer (which also means no breaking changes):

    public class SliderRenderer : GenericSliderRenderer<Slider, UISlider>

## Intended Use Case
More easily extend the renderer to use a subclass of the platform control (UISlider in this example).
For example, if we want to change the thickness of a UISlider, we have to extend UISlider and override `TrackRectForBounds` to return another height. In the current implementation of SliderRenderer, it's not really feasible, due to a lot of private fields and functions. So the only way right now, is to copy most if not all code from the `SliderRenderer`, and basically re-implement it. With this enhancement, it's as simple as subclassing the GenericSliderRenderer like so:

    public class MyThicknessAwareSliderRenderer : GenericSliderRenderer<Slider, MyUISlider>

It opens up for much simpler platform customization through subclassing the elements we want to change (which is at the heart of object oriented programming).

**Comment by Inrego** [comment]
I forgot to mention, all the functionality of the slider renderer would be in the GenericSliderRenderer class. So the exported renderer really is nothing more than:

    public class SliderRenderer : GenericSliderRenderer<Slider, UISlider>
    {
    }

**Comment by jfversluis** [comment]
I think some of this has been done for Xamarin.Forms, but nothing much will change in this regard anymore unfortunately. .NET MAUI will implement a completely new architecture that doesn't use renderers, hooray!

Closing this for now, thanks for you suggestion and thinking with us on this!
