### ISSUE TITLE
[Bug] Latest 4.8.0.1187-pre2 with brushes hangs Visual Studio when showing XAML preview

### ISSUE THREAD

**Issue by opcodewriter** [xamarin/Xamarin.Forms#11542]
### Description

With 4.8.0.1187-pre2 in a new XF project,  everytime I try to open the XAML preview (Android) it hangs Visual Studio 2019.
Not sure if it's only when the page has a simple XAML example with brushes.

### Steps to Reproduce

1. Install 4.8.0.1187-pre2  in a new XF project in VS 2019 
2. Add a simple XAML with brush:
```
<Grid>
    <Grid.Background>
        <LinearGradientBrush StartPoint="0.5,0" EndPoint="0.5,1">
            <GradientStop Color="Yellow" Offset="0.0" />
            <GradientStop Color="Red" Offset="0.25" />
            <GradientStop Color="Blue" Offset="0.75" />
            <GradientStop Color="LimeGreen" Offset="1.0" />
        </LinearGradientBrush>
    </Grid.Background>
<Grid>
```
3. Open the XAML and make sure XAML preview (Android) is active

### Expected Behavior

Have XAML preview work in VS 2019

### Basic Information

- Version with issue: 4.8.0.1187-pre2 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

> VS bug [#1162354](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1162354)

**Comment by jsuarezruiz** [comment]
Fixed by https://github.com/xamarin/Xamarin.Forms/pull/11577
