### ISSUE TITLE
[Bug] [Shapes 4.8-pre2] Justice for baby elephant!

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11547]
### Description

I've just updated my Shapes demos sample from 4.7 to 4.8-pre2, in order to try Shapes with Brushes. As a result, Shapes that don't set the Stroke are now defaulting to a black stroke. This seems to be a result of changing the Stroke and Fill properties to be of type Brush, which defaults to Color.Default? To me, it seems like a better user experience is for users to opt into a Stroke colour, rather than having to opt out of the black outline.

### Steps to Reproduce

1. Run the attached sample
2. Browse to the baby elephant page.

### Expected Behavior

Baby elephant looks correct (no black stroke).

### Actual Behavior

Baby elephant looks incorrect due to black stroke on each Path object.

### Basic Information

- Version with issue: 4.8-pre2
- Last known good version: 4.7
- IDE: VSMac 8.6.7
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: API 28

### Screenshots

Baby elephant in 4.7:

![Simulator Screen Shot - iPhone 11 - 2020-07-24 at 15 15 39](https://user-images.githubusercontent.com/8092460/88400759-b1493000-cdc0-11ea-97a2-ce23b6a16fd4.png)

Baby elephant in 4.8-pre2:

![Simulator Screen Shot - iPhone 11 - 2020-07-24 at 10 27 56](https://user-images.githubusercontent.com/8092460/88378596-3ae50780-cd99-11ea-96a0-7c2c71be75b5.png)

### Reproduction Link

[ShapesDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4971201/ShapesDemos.zip)

**Comment by StephaneDelcroix** [comment]
you won the 'best issue title' award
