### ISSUE TITLE
[Spec] Make FontImageExtension Color property bindable

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#11552]
# Make FontImageExtension Color property bindable
Make the `Color` property of `FontImageExtension` bindable so we will be able to use it with `AppThemeBinding`.

# API

## FontImageExtension
`BindableObject` will be added as a base class.
### Properties

| API | Description |
| ------------- | ------------- |
| `ColorProperty` | Will be added so it will be able to bind to `Color`|
| `Color` | Will change so it is backed by `ColorProperty`|

# Scenarios
## XAML Example
```xaml
<Image Source="{FontImage Glyph={x:Statice constants:Icons.Monkey}, Color="{AppThemeBinding Dark={StaticResource DarkTextColor}, Light={StaticResource LightTextColor}}, Size=22, FontFamily='Icons'} />
```

# Backward Compatibility
No breaking changes

# Difficulty: low

**Comment by StephaneDelcroix** [comment]
see my comment on the PR
