### ISSUE TITLE
Crash in Visual Studio with 4.8.0.1187-pre2 [Bug] 

### ISSUE THREAD

**Issue by ichijikuibo** [xamarin/Xamarin.Forms#11557]
### Description
when using 4.8.0.1187-pre2 on Microsoft Visual Studio Community 2019 Version 16.6.5 on my project or a blank project I get a crash when attempting to edit a color hex in Xaml. for example <Color x:Key="NavigationPrimary">#2196F3</Color> in app.xaml,as soon as i click on #2196F3 visual studio hangs then crashes. Also happens in an entry such as BackgroundColor="#FFFFFFFF" in a content page.

### Steps to Reproduce

1.  Open an Xaml file
2.  Click on any color hex

### Expected Behavior
Allow to edit the color hex text

### Actual Behavior
Visual studio hangs then crashes after about 30 seconds

### Basic Information

- Version with issue: 4.8.0.1187-pre2
- Last known good version: 4.8.0.1143-pre1
- IDE: Microsoft Visual Studio Community 2019 Version 16.6.5 
- Nuget Packages: Default nuget packages installed with project updated to latest
- Affected Devices: Windows 10 Desktop

### Workaround

Downgrade to 4.8.0.1143-pre1

**Comment by ichijikuibo** [comment]
Can also be resovled by changing the Default XAML Editor to Default XML Editor in the Xamarin settings.

**Comment by wagenheimer** [comment]
Both Visual Studio for Windows and Mac crashes with the most recent versions and are unusable.
