### ISSUE TITLE
[Bug] Cannot disable buttons text uppercase

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#11556]
### Description
just got updated my project to xamarin.forms 4.8 pre 2 and this style
` <item name="android:textAllCaps">false</item>`
 in android resorces somehow not working anymore! 

### Steps to Reproduce
1. upgrade to xamarin.forms 4.8
2. create a button
3. use textAllCap style item in android resorces

### Expected Behavior
 disable buttons text uppercase

### Actual Behavior
 buttons text still are uppercase

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio 16.6.5 
- Android: 10
- Nuget Packages: Xamarin.Forms 4.8

**Comment by hartez** [comment]
Run this, then update it to 4.8 pre2 and run it again - the uppercase returns.
[_11556 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4977982/_11556.Repro.zip)

**Comment by poliahrameshkumar** [comment]
This problem persists in Xamarin.Forms 4.8.0.1269. Can someone let me know if any workaround is there to fix that? In recent times for last one year or so, I could keep seeing issue like this in each Xamarin.Forms release which stops us to upgrade to latest version. Many issues are there with CarouselView, CollectionView, ImageButton and now in Buttons etc. I don't know how far the QA process is done.

**Comment by mhrastegary77** [comment]
@poliahrameshkumar Exactly :( i can't upgrade our project to 4.8.0.1269 because of this.

**Comment by poliahrameshkumar** [comment]
The below custom renderer fixes the issue for the time being.

using Android.Content;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
[assembly: ExportRenderer(typeof(Button), typeof(CustomButtonRenderer))]
namespace somenamespacename
{
    public class CustomButtonRenderer : ButtonRenderer
    {
        public CustomButtonRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);
            Control.SetAllCaps(false);
        }
    }
}

**Comment by mhrastegary77** [comment]
i was exactly thinking about using a custom renderer :) thank you so much.

**Comment by mhrastegary77** [comment]
just found out the TextTransform property works for buttons too and is a perfect replacement for the old android resorces and custom renderer Workaround :) so our project is now upgraded to 4.8. 🎉

**Comment by developer9969** [comment]
@poliahrameshkumar thanks your fix saved me today! for some reasons the  "  <item name="textAllCaps">false</item> in our style.xml in android no longer works and only the renderer fix it.  

Kind of confused what the behavior should be, as we definitely do not want to be all caps true

thanks again for the fix

**Comment by ananth-more1-gmail** [comment]
Xamarin-Forms-4.8 : We can set Button property TextTransform="None" to fix allcaps-android issue

**Comment by ananth-more1-gmail** [comment]
Xamarin-Forms-4.8 : We can set Button property TextTransform="None" to fix all-caps android issue.

**Comment by BenjaNapo** [comment]
You saved my life guys with TextTransform ❤️

**Comment by housecode** [comment]
@ananth-more1-gmail you saved my day
it works, thanks

**Comment by TonyLugg** [comment]
@ananth-more1-gmail thank you
👍

**Comment by juanlao** [comment]
> Xamarin-Forms-4.8 : We can set Button property TextTransform="None" to fix all-caps android issue.
> 
> Note: This will not work for the button of type Visual="Material".

If I didn't miss a build/clean/rebuild, it works for Visual Material buttons too ^_^

**Comment by akmustafa** [comment]
> Xamarin-Forms-4.8 : We can set Button property TextTransform="None" to fix all-caps android issue.
> 
> Note: This will not work for the button of type Visual="Material".

Thank you

**Comment by rmarinho** [comment]
this should be fixed by  #12170
