### ISSUE TITLE
CollectionView's SelectionChanged/SelectionChangedCommand not recognizing Tap

### ISSUE THREAD

**Issue by state2lake** [xamarin/Xamarin.Forms#11550]
### Description
I recently migrated a ListView to a CollectionView within our application. After the migration, I immediately noticed an issue with the cell inside of the CollectionView.

The setup was relatively straight-forward - as my Bindings for SelectedItem & SelectionChangedCommand to the ViewModel work correctly (kinda) under the tap, hold, drag motion. When I tap on a cell within the CollectionView, nothing happens. When I tap, hold, and then drag the cell within the CollectionView, only then is SelectionChangedCommand Binding invoked. 

This is only happening on iOS - as Android seems to be able to handle the tap. 

I will provide snippets of my code upon request.

### Steps to Reproduce

1. Tap & Hold on Cell
2. Drag right or left
3. SelectionChanged Invoked

### Expected Behavior
1. Tap on Cell
2. SelectionChanged Invoked

### Basic Information

- Version with issue: 4.7
- Last known good version: ?
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  13.4.1
  - Android:  
- Affected Devices: iOS (iPhone & iPad)

**Comment by hartez** [comment]
@state2lake Could you post a repro project? Or share your ItemTemplate and ViewModel? I'm trying to reproduce this issue, but so far selection seems to work fine in a CollectionView on 4.7 on iOS.

**Comment by state2lake** [comment]
<CollectionView
                             HeightRequest="150" 
                             WidthRequest="500"
                             SelectionMode="Single"
                             SelectedItem="{Binding SlectedItem}"
                             ItemsSource="{Binding List}"
                             SelectionChanged="ItemSelected"
                             Footer="{StaticResource EmptyFooterView}">
               <CollectionView.ItemTemplate>
                   <DataTemplate>
                      <SwipeView>
                            <SwipeView.RightItems>
                               <SwipeItems Mode="Reveal"> 
                                  
                                   <SwipeItem
                                              IconImageSource="delete1.png"
                                              BackgroundColor="Red"
                                              Invoked="OnDelete"
                                              IsDestructive="True"
                                              CommandParameter="{Binding .}">
                                        </SwipeItem>
                               </SwipeItems>
                           </SwipeView.RightItems>  


I have ItemSelected bind to the code behind:

        protected async void ItemSelected(object sender, SelectionChangedEventArgs e)
        {
           
            if(e.CurrentSelection[0] is Item item)
            {
              //... calls ViewModel to Navigate to another page
            }
        }

Just as a reminder, this works perfectly fine on Android - as I am allowed to tap the cell to navigate to a different page.

**Comment by state2lake** [comment]
ViewModel:
      
       public Item SlectedItem { get; set; }
       


       public SingleTapCommand <Item> ItemSlectedCommand
        {
            get
            {
                return new SingleTapCommand<Item>(async e =>
                {
                    SlectedItem = (Item) e;
                    await NavToDifferentPage();
                });
            }
        }

**Comment by state2lake** [comment]
@samhouts @hartez

**Comment by PureWeen** [comment]
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5045793/Archive.zip)

@state2lake can you modify the attached sample to demonstrate your issue? 
I tried with your xaml there and for me SelectionChanged fires on android/ios

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by state2lake** [comment]
@PureWeen @samhouts I was able to use your archive code to test the functionality of CollectionView.SelectionChanged. I did not change anything in your XAML and code-behind, I simply placed a BP at the ItemSelected method in the code-behind. On a simulator, I was able to hit the BP on click. On a real device, I was still not able to hit the BP, despite tapping the CollectionView cell item over 100x. This happened on a variety of physical iPhone devices as well as an iPad.

Also, I went ahead and tried out your Archive code on Android to see if I could hit the same BP, and it did. Not sure why this issue is specific to physical iOS devices.

This happened on both XF 4.7 and XF 4.8.0.1534

**Comment by rachelkang** [comment]
Reopening issue as per @state2lake's request

**Comment by rachelkang** [comment]
@state2lake I followed the steps you shared and was able to hit the BP from a physical iPhone device. The BPs can be a bit funky sometimes - if you haven't already, I recommend deleting the /bin and /obj folders, restarting VS, and cleaning and rebuilding the project. If that doesn't work, I'm curious what versions of iOS and which devices you've tried on? I was able to see it working on an iPhone 7, on the most recent version of iOS (14.0.1)

**Comment by state2lake** [comment]
@rachelkang Yes, I have deleted the /bin and /obj folders, restarted VS, and cleaned & rebuilt the project as well. Still no luck. This is happening across several physical devices across my companies team. Regarding myself, I'm building this onto an iPhone 7 v13.4.1 as well as an iPad v13. I have not upgraded to my iOS devices to 14 yet, for other reasons, but will soon test that out eventually as well.

**Comment by PureWeen** [comment]
@state2lake if you put some `Debug.WriteLines` inside the event to you see anything in your output?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
