### ISSUE TITLE
[Bug] masterdetailpage on iPadOS multitasking mode

### ISSUE THREAD

**Issue by 632575987** [xamarin/Xamarin.Forms#11560]
### Description
Mataterdetailpage App runs on ipad multitasking mode can’t show the detailpage.
### Steps to Reproduce

1. Swipe up from the bottom of the screen and drag the app to the right side of the screen
2. The application only displays the list of masters, the details page will not open after clicking or swipe

### Expected Behavior 

I hope that the display status of the master page on each platform and device type can be more reasonable, or the behavior of the master page can be freely controlled

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.6 iPadOS iPad mini5

**Comment by PureWeen** [comment]
duplicate 
https://github.com/xamarin/Xamarin.Forms/issues/2017#issuecomment-554466816
