### ISSUE TITLE
[Bug]System.IO.FileLoadException : 'Could not load file or assembly on UWP

### ISSUE THREAD

**Issue by BovynC** [xamarin/Xamarin.Forms#11570]
### Description

I'm currently working on a Xamarin project available on Android/iOS and UWP.
I encounter an issue on UWP at startup that I can't handle. I've already try to delete bin/obj folder and reset my .nuget folder but
nothing change.  One collegue try to launch the project with the same branch without any changes and he managed to launch 
and use succesfully the app . 

Below the caught exception : 

![Capture](https://user-images.githubusercontent.com/37806521/88530877-4f780880-d002-11ea-8c14-cad13a674134.PNG)

I'm currently targeting Windows 10 build 16299 and min version is Windows 10 build 15063.
Below, the nugget packages used in UWP project : 

![Capture2](https://user-images.githubusercontent.com/37806521/88531798-b4802e00-d003-11ea-954c-88c26571809d.PNG)

Thanks in advance for the help

**Comment by MagicAndre1981** [comment]
change MinVersion to 14393 or to 16299, too.

**Comment by ChristopheBovyn** [comment]
@MagicAndre1981 Thanks for you reply. I tried MinVersion 14393, I still have the same error and with MinVersion 16299 I've an other error "Too manifest validation" (error 80080204).

**Comment by MagicAndre1981** [comment]
replace the old PCL nugets with something newer, they are really old and target old runtimes and don't support new .net standard 2.x

**Comment by ChristopheBovyn** [comment]
The problem here is that one colleague is able to execute the app successfully without any changes and an other one got the same error as me ... Is it possible to be a nugget error in that conditions ?

**Comment by MagicAndre1981** [comment]
which Windows 10 version/build do you both use? do you use the same or a different version?

**Comment by Miiite** [comment]
We use the same parameters regarding the build minVersion and targetVersion. But I don't think we are on the same Windows version for our work machine.

**Comment by Miiite** [comment]
But I'm having trouble understanding how a Windows version (meaning the version of the machine running the project) could have an impact on this kind of errors ?

**Comment by PureWeen** [comment]
@Miiite a mismatch with the sdk and windows version can cause some weirdness

From a command prompt with administrator privileges try running
build.cmd -Target provision
Then on your project set the min to 16299 and the max to 18362 or 19041

You can also check your build output for libraries trying to load that "System" dll 

Usually that exception happens because one of the libraries doesn't have a compatible UWP build so then the incorrect System version loads

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
