### ISSUE TITLE
[Bug][Brushes] LinearGradientBrush diagonal platform differences

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11571]
### Description

I've painted three `LinearGradientBrush` objects in `Frame` objects:

1. Horizontal - from (0,0) to (1,0).
2. Vertical - from (0,0 to (0,1).
3. Diagonal - from (0,0) to (1,1).

All three gradients move from yellow to green.

On iOS, the three gradients are painted correctly.

On Android, the diagonal gradient goes horizontally from green to yellow. Therefore, not only is the colour order wrong, the direction is also wrong.

On UWP, the diagonal gradient is identical to the horizontal gradient.

See the screenshots below.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the linear gradient brush demo page on iOS, Android, and UWP.

### Expected Behavior

Three correct linear gradients - horizontal, vertical, and diagonal. 

### Actual Behavior

Three correct linear gradients on iOS. Diagonal gradients incorrect on Android and UWP.

### Basic Information

- Version with issue: 4.8-pre2
- IDE: VSMac 8.6.7
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: API 28
  - UWP:  10.0.18362.0

### Screenshots

iOS:

![Simulator Screen Shot - iPhone 11 - 2020-07-27 at 10 10 22](https://user-images.githubusercontent.com/8092460/88532625-d629e700-cffc-11ea-8f0b-044ede997288.png)

Android:

![Screenshot_1595841175](https://user-images.githubusercontent.com/8092460/88532641-daee9b00-cffc-11ea-8421-438dae61753a.png)

UWP:

![uwp01](https://user-images.githubusercontent.com/8092460/88532651-df1ab880-cffc-11ea-9369-e5043069f779.PNG)

### Reproduction Link

[BrushesDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/4981355/BrushesDemos.zip)

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by jsuarezruiz** [comment]
I have done tests directly in a native App in UWP and I get the same result:
<img width="1292" alt="Captura de pantalla 2020-08-10 a las 13 26 01" src="https://user-images.githubusercontent.com/6755973/89778061-2466dc00-db0d-11ea-8f95-7d45ab64f264.png">
