### ISSUE TITLE
[Bug] FlexLayout BindableLayout.EmptyView vertical alignment

### ISSUE THREAD

**Issue by r-work** [xamarin/Xamarin.Forms#11578]
### Description
Cannot vertically align the content of the empty view template to the center.
### Steps to Reproduce
Consider the following:
```xaml
        <FlexLayout BindableLayout.ItemsSource="{Binding GalleryItems}" Wrap="Wrap" AlignItems="Start" AlignContent="Start" BackgroundColor="PaleVioletRed">
            <BindableLayout.EmptyView>
                <StackLayout BackgroundColor="AliceBlue" VerticalOptions="Center" HorizontalOptions="Center">
                    <Label HorizontalOptions="Center" VerticalOptions="Center" HorizontalTextAlignment="Center">empty view</Label>
                </StackLayout>
            </BindableLayout.EmptyView>
        </FlexLayout>
```

and the result:
![Screenshot_1595857269](https://user-images.githubusercontent.com/68378520/88548638-4a718400-d017-11ea-9b65-5cf96377e447.png)

and if I put the label in a grid, the result is better but not right:
```xaml
        <FlexLayout BindableLayout.ItemsSource="{Binding GalleryItems}" Wrap="Wrap" AlignItems="Start" AlignContent="Start" BackgroundColor="PaleVioletRed">
            <BindableLayout.EmptyView>
                <StackLayout BackgroundColor="AliceBlue" VerticalOptions="Center" HorizontalOptions="Center">
                    <Grid VerticalOptions="Center">
                        <Label HorizontalOptions="Center" VerticalOptions="Center" HorizontalTextAlignment="Center">empty view</Label>
                    </Grid>
                </StackLayout>
            </BindableLayout.EmptyView>
        </FlexLayout>
```

and the result:
![Screenshot_1595857428](https://user-images.githubusercontent.com/68378520/88548948-a4724980-d017-11ea-9b20-12765be828af.png)

### Expected Behavior

Center content vertically.

### Actual Behavior

Content remaining on top.

### Basic Information

- Version with issue: XF 4.7.0.1179
- IDE: VS 2019 16.7 Preview 5.0
- Platform Target Frameworks: 
  - Android: 10 

### Screenshots
provided above.

**Comment by StephaneDelcroix** [comment]
that's expected with AliugItem and AligContent set to Start. the FlexLayot is doing it's job here, I think. It's unrelated to the EmptyView. You could probably force the Width and HeightRequests of your label to occupy more space
