### ISSUE TITLE
App getting rejected in App Store when using Xamarin.Essentials. Browser

### ISSUE THREAD

**Issue by SharmaNarendra** [xamarin/Xamarin.Forms#11588]
### Description
App getting rejected in App Store when using Xamarin.Essentials. Browser. I have used Essentials library to load a url in my Xamarin.Forms application. The application rejected by the apple store and the reason turned out is Xamarin.Essential component using UIWebview instead of WKWebView.
### Steps to Reproduce

1. Create an xamarin.forms application.
2. Add Xamarin.Essentials from Nuget packages.
3. Load URL using Xamarin.Essential.Browser ' await Browser.OpenAsync(uri, BrowserLaunchMode.SystemPreferred);'
4.Upload the application to Apple store.

### Expected Behavior
Application should not be rejected by apple store.
### Actual Behavior
Application rejected by Apple store.
### Basic Information

- Version with issue:1.5.3.2
- Last known good version:
- IDE: Visual for Mac
- Platform Target Frameworks: 
  - iOS:   13.18.3.2
 - Nuget Packages:Xamarin.Essentials
- Affected Devices:NA

### Screenshots

 
![AppstoreConnect](https://user-images.githubusercontent.com/18699356/88704949-76325e00-d12c-11ea-9c49-bd09b07aba5b.jpeg)

**Comment by jfversluis** [comment]
Why do you believe this is due to Essentials? If so, you probably want to open an issue on their repo :) 

However, I don't think that they are the ones causing this. Have you read [this blog post](https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/) and other links that originate from there?

**Comment by pvg1975** [comment]
First, I want to thank Gerald for his help. You are awesome. 

I don't know if this is related to my problem, but I submitted an app to the App Store for TestFlight 10 days ago and it went thru; then I updated Xcode to Version 11.6 (11E708), VS2019 (for Mac) and Xamarin.Forms on my Mac and when I had to rebuild cause of a typo on a <Label>, I started to get ITMS-90809.

I tried everything in 24 builts now, including deleting the BIN and OBJ folders, I tried with --optimize=experimental-xforms-product-type and also with --optimize=force-rejected-types-removal and --warn-on-type-ref=UIKit.UIWebView -warnaserror:1503 with all posible combinations.

The only Nugets I use are Newtonsoft.Json, Syncfusion and FFImgeLoading which are all ok and updated.

Following Gerald's advice for rolling back Xamarin.Forns, I get an incompatibility error message with Xcode, meaning I gotta stick with 4.7.0.1179

Any help will be appreciated. At this point Im open to any suggestions.

Thanks.

**Comment by pvg1975** [comment]
UPDATE:

I changed the Deployment Target from 8.0 to 9.0 at info.plist and Apple liked the Built. The app was accepted by Apple.

**Comment by jfversluis** [comment]
Thanks for the update @pvg1975, that is really strange though! @SharmaNarendra do you have any more information on the questions I asked? Thank you!

**Comment by PureWeen** [comment]
@SharmaNarendra can you try the latest release of VSMac or Visual studio?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
