### ISSUE TITLE
Adding new bound controls to a Xamarin.Forms iOS CollectionView hides the view of existing bound controls [Bug] 

### ISSUE THREAD

**Issue by cmpalmer66** [xamarin/Xamarin.Forms#11582]
### Description
I have a CollectionView bound to an `ObservableCollection<View>` of views. In my actual application, these are custom controls, but the problem can be illustrated with Labels.

When I add the initial set of controls to the ObservableCollection, they appear in the CollectionView normally, spaced correctly, scrollable, etc. However, when a user action causes another item to be added to the end of the ObservableCollection, the new item appears, but all (or most) of the other items get hidden. Sometimes, one or more of them will appear, or jump around, then disappear when another item is added.

### Steps to Reproduce
1. Create a CollectionView with a ItemTemplate containing a ContentView (also tried Frame) with the Content bound to '.' 
```XML
      <CollectionView x:Name="MyCollectionView">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <ContentView Content="{Binding .}"></ContentView>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
```

2. Add some number of items to an `ObservableCollection<View>` bound to the ItemsSource property of the CollectionView and observe that they display correctly:

```C#
            MyCollectionView.BindingContext = this;
            MyCollectionView.SetBinding(ItemsView.ItemsSourceProperty, nameof(ControlList));

            for (var x = 0; x < 20; x++)
            {
                ControlList.Add(new Label {Text = $"Added at {ControlList.Count}"});
            }
```

3. Append an item to the bound ObservableCollection<View> and the existing items in the CollectionView will disappear, or shrink out of sight

### Expected Behavior
You should be able to add items to the bound collection and have them appear the way they do on UWP and Android versions running the same code

### Actual Behavior
On iOS, items disappear, jump around, or shrink

### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: Unknown
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: 
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://github.com/cmpalmer66/CollectionViewSample

### Workaround

None found yet

**Comment by hartez** [comment]
This issue is fixed in 5.0.0.1931.

(This is probably fixed in the last SR or 4.8.0, but I haven't tested it with that version.)
