### ISSUE TITLE
[Enhancement] Native page transition on Android

### ISSUE THREAD

**Issue by Symxn** [xamarin/Xamarin.Forms#11586]
Currently there is only a hard-coded animation for the page transitions on Android.
Why isn't native animation used on Android?

I am aware that Xamarin.Forms only uses one activity for all pages, but there will definitely be a resource on Android that defines the native page transition. Can't this be applied to the pages?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
