### ISSUE TITLE
[Bug] [UPW] [Shell] System.AccessViolation on launch

### ISSUE THREAD

**Issue by bmacombe** [xamarin/Xamarin.Forms#11589]
### Description
I was testing the repro app from #8814 against a newer version of Forms and I got a System.AccessViolation when I tried against 4.8 Pre 2.  Works fine on the latest 4.7 nugets.

### Steps to Reproduce
Run attach repro

### Basic Information

- Version with issue: 4.8 Pre 2
- Last known good version: 4.7 Stable
  - UWP:   

### Screenshots
 

![image](https://user-images.githubusercontent.com/15127788/88747945-77a45c00-d115-11ea-8be6-0579d4372b65.png)

### Reproduction Link
[TestyMcTestikins.zip](https://github.com/xamarin/Xamarin.Forms/files/4992051/TestyMcTestikins.zip)

**Comment by PureWeen** [comment]
@bmacombe 

Shell only works with 18362 because it's based on Navigation View

If you set your target to 18362 does it work?

**Comment by bmacombe** [comment]
@PureWeen Yeah, that was it. Thanks1
