### ISSUE TITLE
After changing Visual Studio theme, XAML editor remains partially white

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11594]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1123956/after-changing-visual-studio-theme-xaml-editor-rem.html)._

---
Hello,

I noticed after going from the Light theme to the Dark theme, the thin bar on the side of Xamarin Forms XAML editor which is used to switch between the code and preview modes remains white.

Thanks!

---
#### Feedback Bot on 7/24/2020, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
Thanks for this report. unfortunately, this should be targeted at visual studio (or vsmac)
