### ISSUE TITLE
[Bug]  CarouselView Android Can't Scroll Back when Last Item is Reached

### ISSUE THREAD

**Issue by AlfonChitoSalano** [xamarin/Xamarin.Forms#11590]
### Description
The bug is the same as this https://github.com/xamarin/Xamarin.Forms/issues/9020. This was closed however when we checked, the bug still occurs.

### Steps to Reproduce

Same as how to reproduce this https://github.com/xamarin/Xamarin.Forms/issues/9020

### Expected Behavior

When the back button is tapped it should display the correct view, just like the above issue.

### Actual Behavior

Wrong view displayed.

### Basic Information

- Version with issue: XF 4.7.0.1179
- IDE: Visual Studio 2019
  - Android: Xamarin Android SDK 10.3.1.4
- Android Support Library Version: 28.0.0.3

### Screenshots

same as above issue

### Reproduction Link

same as above issue

### Workaround

we forced the carousel to scroll in the xaml.cs like below and it worked

 if (Device.RuntimePlatform == Device.Android)
 {
                explanationCarousel.ScrollTo(explanationCarousel.Position);
 }

**Comment by PureWeen** [comment]
@AlfonChitoSalano can you try on the latest release of 4.8? I tried to reproduce this and wasn't able to reproduce. 

If it's still happening for you can you attach a repro?

**Comment by AlfonChitoSalano** [comment]
> @AlfonChitoSalano can you try on the latest release of 4.8? I tried to reproduce this and wasn't able to reproduce.
> 
> If it's still happening for you can you attach a repro?

Yes it is still an issue. So I could reproduce this by just doing twice or more than swiping from right to left when im at the end of the item. I could still reproduce this even in the 4.8.x version

**Comment by rmarinho** [comment]
@AlfonChitoSalano are you sure you are updating the packages and cleaning ? Can you upload the repro you are using ?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by AlfonChitoSalano** [comment]
> Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

This is fixed testing with new XF version 4.8.0.1534
