### ISSUE TITLE
[Enhancement] Switch has no good way to control the track color

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#11600]
## Summary
It's currently possible to change the thumb color of a Switch using the ThumbColor property.

It's also possible to set the track color using the OnColor property. This works for the on state, but the off state can't be controlled.

## API Changes
I propose adding a TrackColor property, controlled via VisualStateManager, and deprecating the OnColor property.

## Intended Use Case
When theming an app, it's important to be able to change the colors of the default controls. In the case of Switch, a renderer is needed to implement theming. This shouldn't be necessary.

**Comment by mfeingol** [comment]
cc @techduggu

**Comment by techduggu** [comment]
Hi @mfeingol 
Thanks for looping me in and I'd love to help!
I am trying to understand the problem. When you say, 

> OnColor property works for the on state, but the off state can't be controlled

Is it something you're trying to control using VSM?
Because what I see VSM for Switch exists to control off states too. https://github.com/techduggu/Xamarin.Forms/blob/0ff2b42a916acd549272cf8c843025bfe2990f97/Xamarin.Forms.Core/Switch.cs#L52

Also, Do you have any sample project or visual mock-up which is easy to understand the actual vs. expected result?

**Comment by mfeingol** [comment]
I'm theming an app. I've defined the following colors in a ResourceDictionary for the light theme. There are equivalent definitions in a dark theme as well:

```xml
    <Color x:Key="SwitchThumbOnColor">#F0EF5350</Color><!-- Red 400 -->
    <Color x:Key="SwitchThumbOffColor">#7FE0E0E0</Color><!-- Gray 300 modified -->
    <Color x:Key="SwitchTrackOnColor">#FF4081</Color><!-- Pink A200 -->
    <Color x:Key="SwitchTrackOffColor">#212121</Color><!-- Gray 900 -->
```

To translate these to actual instances of a Switch, I add the following:

```xml
    <Style TargetType="Switch" ApplyToDerivedTypes="True">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="On">
                        <VisualState.Setters>
                            <Setter Property="ThumbColor" Value="{DynamicResource SwitchThumbOnColor}" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Off">
                        <VisualState.Setters>
                            <Setter Property="ThumbColor" Value="{DynamicResource SwitchThumbOffColor}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>
```

I'd like to do the same for the track color. However, the only Xamarin.Form.Switch property available that controls it is `OnColor`. If I apply SwitchTrackOnColor/SwitchTrackOffColor to `OnColor` in the VSM style, it works for the On state, but not for the Off state.

If you can't trivially repro this, I'll make a repro project for you. Let me know.

**Comment by techduggu** [comment]
Thanks @mfeingol 
This is good to start with. I will try to repro this tomorrow (as it's midnight for me) and will let you know.
I need to first check if OnColor property (without VSM) behaves the same way or not,  to understand where the problem lies (whether at VSM or native Switch Renderer).

**Comment by techduggu** [comment]
Hi @mfeingol 
I looked into this and was able to reproduce it within Xamarin.Forms actual source repo. But I am facing slowness in my personal laptop and Xamarin.Forms actual repo is taking too much time to build and test further anything. 
I am trying to set up the X.F repo in another machine and will try dig deeper into this.

In the meantime, Can you try `OnColor` property without VSM and try setting track off colour to switch using any event (e.g. Toggled)?

Also, you mentioned in the issue description that a renderer is needed to achieve the theming. So, Do you currently use custom renderer to achieve the track off color? I see we have the trackTint in Android and onTintColor in iOS:

https://developer.android.com/reference/android/widget/Switch
https://developer.apple.com/documentation/uikit/uiswitch

**Comment by mfeingol** [comment]
> Can you try OnColor property without VSM and try setting track off colour to switch using any event (e.g. Toggled)?

Just so I understand, are you suggesting I should try setting `OnColor` when the switch is togged to off? IIRC I already tried that and `OnColor` is only applied when the switch is toggled to on. But I can double-check if you want.

The renderer I'm using to set the track color does the following:

```c#
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using Android.Content;
using Android.OS;

[assembly: ExportRenderer(typeof(Switch), typeof(MyApp.ThemedSwitchRenderer))]
namespace MyApp
{
    public class ThemedSwitchRenderer : SwitchRenderer
    {
        public ThemedSwitchRenderer(Context context) : base(context)
        {
            Singleton<EventService>.Instance.ThemeChanged += this.OnThemeChanged;
        }

        protected override void Dispose(bool disposing)
        {
            if (this.Element != null)
                this.Element.Toggled -= this.Element_Toggled;

            Singleton<EventService>.Instance.ThemeChanged -= this.OnThemeChanged;

            base.Dispose(disposing);
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Switch> e)
        {
            base.OnElementChanged(e);

            if (this.Element != null)
            {
                this.SetThumbColor();
                this.Element.Toggled += this.Element_Toggled;
            }
        }

        void Element_Toggled(object sender, ToggledEventArgs e)
        {
            // This is necessary for proper timing on thumb/track colors
            this.Element.Dispatcher.BeginInvokeOnMainThread(() => this.SetThumbColor());
        }

        void OnThemeChanged(object sender, AppTheme theme)
        {
            this.SetThumbColor();
        }

        void SetThumbColor()
        {
            if (this.Control != null)
            {
                Color trackColor;

                if (this.Element.IsToggled)
                    trackColor = (Color)App.Current.Resources["SwitchTrackOnColor"];
                else
                    trackColor = (Color)App.Current.Resources["SwitchTrackOffColor"];

                if (Build.VERSION.SdkInt >= BuildVersionCodes.Q)
                    this.Control.TrackDrawable.SetColorFilter(new Android.Graphics.BlendModeColorFilter(trackColor.ToAndroid(), Android.Graphics.BlendMode.SrcAtop));
                else
#pragma warning disable 0618
                    this.Control.TrackDrawable.SetColorFilter(trackColor.ToAndroid(), Android.Graphics.PorterDuff.Mode.SrcAtop);
#pragma warning restore 0618
            }
        }
    }
}
```

**Comment by thisismyself** [comment]
Currently I am styling two apps for Dark and Light Mode. In this task, a feature as requested by @mfeingol would be very helpful. 
In the ON state, it is barely visible this is a switch control. An OffColor Property would be highly useful.

OFF state:
![grafik](https://user-images.githubusercontent.com/54321709/104170260-22c57b00-5401-11eb-9e90-bdc7397f2cfd.png)

ON state:
![grafik](https://user-images.githubusercontent.com/54321709/104170594-ae3f0c00-5401-11eb-9dc0-6b05bf2b74d7.png)

    <Switch IsToggled="{Binding IsBlaBlaEnabled}"
            OnColor="GreenYellow"
            ThumbColor="Orange"
            Visual="Default" />

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
