### ISSUE TITLE
[Bug] FlyoutBehavior.Disabled hide the back button when push a new page on Shell

### ISSUE THREAD

**Issue by PTEC3D50** [xamarin/Xamarin.Forms#11608]
### Description
Since the new version of Xamarin.Forms 4.7.0.1179, when you set the FlyoutBehaviour of a Shell on Disabled and push a new Page, there is no back button on the naviguation bar
### Steps to Reproduce

1. Create a new Shell template project
2. Update the version of Xamarin.Forms to 4.7.0.1179
3. Set the FlyoutBehavior of the Shell to FlyoutBehavior.Disabled;
3. Try the app

### Expected Behavior
Showing a back button on the pushed page
### Actual Behavior
Not Showing a back button on the pushed page
### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: 4.7.0.1142
- IDE: Visual Studio 2019 Ver.16.6.4
- Nuget Packages: Xamarin.Forms / Xamarin.Essentials / NETStandard.Library

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/11553 duplicate
