### ISSUE TITLE
[Bug] 1179 breaks back button on Shell.TitleView (android)

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/Xamarin.Forms#11606]
### Description
Upgrading to build 1179 breaks back button on Shell.TitleView

### Steps to Reproduce

1.  clone repo https://github.com/InquisitorJax/Xamarin-Forms-Shell.git
2.  Run the app, and tap the "Navigate To Item Page" button
3.  The item page will open - and you can see an operational back button
4. Update the Forms to build 1179 (latest as of this writing)
5. Follow steps 1 - 3: The back button is now missing

### Expected Behavior
The title view should show the back button
![image](https://user-images.githubusercontent.com/1822976/88923621-4c834f00-d272-11ea-9989-6c54b5a0169e.png)

### Actual Behavior
The back button does not show
![image](https://user-images.githubusercontent.com/1822976/88923642-5442f380-d272-11ea-9d47-e3e027c1620d.png)

### Basic Information

- Version with issue: 4.7.0.1179
- Last known good version: 4.7.0.1142
- IDE: VS Windows
- Platform Target Frameworks: 
  - Android: API 29

**Comment by PureWeen** [comment]
@InquisitorJax this should be fixed with the next 4.7 SR

You can also test with the latest https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds
