### ISSUE TITLE
Consider Support For Right To Left Layout  And It's Requirements In All Visual VIEWS and Elements.

### ISSUE THREAD

**Issue by hamiddd1980** [xamarin/Xamarin.Forms#11605]
## Summary
Hello. While thanking to Xamarin team for their daily efforts to add new features and improvements to Xamarin.Forms ,please kindly notice to the followings:
1-Many features like Shapes , Geometry ,Gradient ,SearchBar ,TabbedPage(Swipe Direction)... don't support Right To Left layout.
2-some of other views and elements support Right To Left layout , but sometimes this support is not complete and you may encounter bugs and problems when you are using these views in Right To Left languages.(for example ShellContent problem in RightToLeft layout in iOS or RelativeLayout, in both Android and iOS)
These problems are discouraging and disappointing and actually  prevents people to use Xamarin in business projects.(multilingual Apps and Cultures with Right To Left Language) 
## API Changes
To Solve this problem , my requests are :
1-consider support for Right To Left Layout  And It's Requirements in each step from Design To Production(concept definition , design , design validation , Test, Production , ...)
2-according to mentioned problem ,consider and evaluate  the effect and correct function of FlowDirection property in all of production steps(specially Design and Test)

## Intended Use Case
Full support for Right To Left Layout is necessary and mandatory for:
- multilingual Apps
- Cultures which use Right To Left Languages.

**Comment by jfversluis** [comment]
I think this has greatly improved in .NET MAUI already so please have a look there!

Unfortunately we won't be able to make things happen for Xamarin.Forms anymore. Thank you for the suggestion!
