### ISSUE TITLE
Unexpected Xamairn.Forms UI behavior when setting Translucency on UINavigationBar for iOS. ListView wrapped in RefreshView does not align itself directly below the navigation bar.

### ISSUE THREAD

**Issue by Ammar-Mheir** [xamarin/Xamarin.Forms#11611]
### Description

Upon creating a navigation page with a Translucent UINavigationBar, if adding a ListView inside of a RefreshView, the ListView items will begin from the very top of the screen rather than aligning itself directly below the navigation bar. When switching out the ListView with a TableView, the UI behaves as expected with the TableView starts just below the NavigationBar which is translucent. (The customer repro project from Github labeled the page exhibiting the issue as TranslucentNavbarWithTableViewAndRefreshView although the Xaml has a ListView inside of a RefreshView, TableViews do not exhibit the issue through my tests)

If translucency was disabled and the ListView is wrapped inside of a RefreshView, the issue does not occur. 

Any other changes made to the type of view inside the Refresh view (or if the RefreshView was even implemented) will cause the issue to not replicate. It seesm that this occurs when the ListView  isinside of a RefreshView and Translucency is enabled on UINavigationBar (through custom renderer).

Additional users are running into this issue here: 

https://stackoverflow.com/questions/62276504/xamarin-views-are-overlapped-by-the-uinavigationbar-when-set-to-be-translucent

### Steps to Reproduce

1- Create new Xamarin.Forms MasterDetail app from template

2- Add new Content page (named ListViewPage) into Views folder with the following Xaml inside <ContentPage.Content> tag:

```
<RefreshView IsRefreshing="{Binding IsRefreshing}"
             Command="{Binding RefreshCommand}">
            <ListView>
                <ListView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>mono</x:String>
                        <x:String>monodroid</x:String>
                        <x:String>monotouch</x:String>
                        <x:String>monorail</x:String>
                        <x:String>monodevelop</x:String>
                    </x:Array>
                </ListView.ItemsSource>
            </ListView>
        </RefreshView>
```
3- Add Menu Item enum to HomeMenuItem.cs and the following code in NavigateFromMenu() method in MainPage.Xaml.cs (So it can be listed as a Menu Item, set the NavigationBarTranslucent property and navigate to it)

```
case (int)MenuItemType.ListViewpage:
                        var navPage = new NavigationPage(new ListViewPage());
                        Xamarin.Forms.PlatformConfiguration.iOSSpecific.NavigationPage.SetIsNavigationBarTranslucent(navPage, true);
                        MenuPages.Add(id, navPage);
                        break;
```

4- Add CustomNavRenderer.cs  to iOS Project with the following code that sets the appearance of the UINavigationBar (setting clear background color and Translucency)

```
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using XFormstest.iOS;
using UIKit;

[assembly: ExportRenderer(typeof(NavigationPage), typeof(CustomNavRenderer))]
namespace XFormstest.iOS
{
    public class CustomNavRenderer : NavigationRenderer
    {
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            if (NavigationBar.Translucent)
            {
                UINavigationBar.Appearance.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
                UINavigationBar.Appearance.ShadowImage = new UIImage();
                UINavigationBar.Appearance.BackgroundColor = UIColor.Clear;
                UINavigationBar.Appearance.Translucent = true;
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }
            base.Dispose(disposing);
        }
    }
}
```

5- Building and deploy to iOS Simulator or device. Navigate to the new ListViewPage we created and observe how the ListView items start at the very top of the screen rather than right below the translucent navigation bar. (The text on the navigation bar is white so it initially looks like there's nothing there but the bar is translucent and the UINavigationBar buttons are also there if you look closely.)

### Expected Behavior

The ListView should align itself to appear below the NavigationBar just like how the TableView aligns itself with the RefreshView and Transluceny.

### Actual Behavior

The ListView starts at the very top of the screen. Being overlapped by the Translucent NavigationBar.

### Basic Information

-Xamarin.Forms latest stable release and pre-release
-Replicated on Xamarin.Forms 4.5 as well
-Visual Studio 16.6.4

## Screenshots

https://stackoverflow.com/questions/62276504/xamarin-views-are-overlapped-by-the-uinavigationbar-when-set-to-be-translucent

**Comment by PureWeen** [comment]
@Ammar-Mheir can you attach a repro? I'm not having much luck reproducing your scenario here

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
