### ISSUE TITLE
Maps Polygon Binding

### ISSUE THREAD

**Issue by fnoomen** [xamarin/Xamarin.Forms#11618]
Hi
I need reduce code fo creating polygon if its possible and also if can make bindable

<maps:Map.MapElements>
        <maps:Polygon StrokeColor="#FF9900"
                        StrokeWidth="8"
                        FillColor="#88FF9900">
            <maps:Polygon.Geopath>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6458676</x:Double>
                        <x:Double>-122.1356007</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6458097</x:Double>
                        <x:Double>-122.142789</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6367593</x:Double>
                        <x:Double>-122.1428104</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6368027</x:Double>
                        <x:Double>-122.1398707</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6380172</x:Double>
                        <x:Double>-122.1376177</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.640663</x:Double>
                        <x:Double>-122.1352359</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6426148</x:Double>
                        <x:Double>-122.1347209</x:Double>
                    </x:Arguments>
                </maps:Position>
                <maps:Position>
                    <x:Arguments>
                        <x:Double>47.6458676</x:Double>
                        <x:Double>-122.1356007</x:Double>
                    </x:Arguments>
                </maps:Position>
            </maps:Polygon.Geopath>
        </maps:Polygon> 
    </maps:Map.MapElements>
change to
maps:Map.MapElements
<maps:Polygon StrokeColor="#FF9900"
StrokeWidth="8"
FillColor="#88FF9900"
Position ="47.6381401 -122.1317367,47.6381473 -122.1350841,47.6382847 -122.1353094,47.6384582 -122.1354703,47.6401136 -122.1360819,47.6403883 -122.1364681,47.6407426 -122.1377019,47.6412558 -122.1404056,47.6414148 -122.1418647,47.6414654 -122.1432702"

  </maps:Polygon> 
    </maps:Map.MapElements>
also if can make is bindable like this
maps:Map.ItemTemplate

<maps:Polygon Position="{Binding Position}"
StrokeColor="#FF9900"
StrokeWidth="8"
FillColor="#88FF9900" />

</maps:Map.ItemTemplate>

Thnaks

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
