### ISSUE TITLE
Xamarin Forms template change to add new mtouch flags and linker settings for iOS

### ISSUE THREAD

**Issue by tschlarman** [xamarin/Xamarin.Forms#11623]
### Description
The XF templates for iOS should be updated to include the new mtouch arguments that strip out unused references. This will help mitigate the UIWebView issue when submitting to the Apple Store. There area lot of references to older preview flags for this on blogs. It would great to put in the proper ones out of the box.

See the discussion: https://github.com/xamarin/xamarin-macios/issues/8814

mtouch flags to add in Release mode:
![image](https://user-images.githubusercontent.com/10763706/89048585-e09df680-d304-11ea-8acf-58b40499c5bf.png)

Linker behavior in Release mode:
![image](https://user-images.githubusercontent.com/10763706/89048653-f9a6a780-d304-11ea-8a25-5dd7f79c8dc9.png)

### Steps to Reproduce
Create a default XF Shell project and see that none of the linker settings or mtouch arguments are set.

### Expected Behavior
Add the flags to the template's release mode for iOS

### Actual Behavior
no flags or linker settings are set.

### Basic Information

- Version with issue: XF 4.7
- Last known good version: none
- IDE: VS2019 (latest) and VS mac (latest)
- Platform Target Frameworks: 
  - iOS:  all

### Screenshots

See above

### Reproduction Link

Create a default XF Shell project and see that none of the linker settings or mtouch arguments are set.

**Comment by PureWeen** [comment]
Closing for now

https://github.com/xamarin/xamarin-macios/issues/8814#issuecomment-668815907
