### ISSUE TITLE
[BUG] Xamarin.Forms TabIndex not working on elements inside of ListView just on iOS

### ISSUE THREAD

**Issue by juanraa** [xamarin/Xamarin.Forms#11626]
### Description
It seems the Tabbing is not working on the elements inside of Listview when the page contains more elements and not only the ListView. 
### Steps to Reproduce

1. Open the sample project
2. Start the tabbing
3. The tabbing never goes into ListView elements even when the elements have accessibility properties. 

### Expected Behavior
The tabbing must work on all elements within ListView and must respect the order.

### Actual Behavior
The tabbing is not working on elements inside of ListView when in the page are more elements.
### Basic Information
This only happens on iOS devices. android is worked as expected
- Version with issue:
- Last known good version:
- IDE: Visual Studio For mac
- Platform Target Frameworks: 
  - iOS: 13.4.1  
  - Android: 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[AccessibilityTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5008409/AccessibilityTest.zip)

**Comment by juanraa** [comment]
Edit: Just happen on Simulator, on a physical device is working good.

**Comment by PureWeen** [comment]
Because this works on a physical device I feel like this isn't a bug

The simulators in general I've found to be a bit quirky with validating accessibility features like this.

@samhouts thoughts?

**Comment by samhouts** [comment]
Yeah, I think it is very unlikely that we're doing something to make it not work on simulator. It's possibly due to how the simulator processes the keyboard input?

**Comment by juanraa** [comment]
Agree with you guys, i will close it.
