### ISSUE TITLE
[Bug] 4.8-pre3 regression with XAML-defined arrays - x:Int32 is no longer of type x:Object

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11620]
Defining an array with mixed types no longer works in pre3; this has worked in all versions up 'til pre3.

```xaml
<x:Array x:Key="myArray" Type="{x:Type x:Object}">
    <x:String>Some string</x:String>
    <x:Int32>69</x:Int32>
    <x:Int32>32</x:Int32>
</x:Array>
```

The error message is 
> Error XFC0009: No property, BindableProperty, or event found for "Items", or mismatching type between value and property. (XFC0009) (MyMapp) XamlC

 and points to the line with the first Int32 declaration. If I remove the ints then it compiles fine. The error happens both with the `Type="{x:Type x:Object}"` type declaration and without type declaration.
The use case is to define options for a picker, where some options are strings and some integers.

**Comment by Tommigun1980** [comment]
Edit!

Seems as the problem is not mixing data types, rather that x:Int32 is no longer treated as being of type x:Object.

The following won't work either:

<x:Array x:Key="myArray" Type="{x:Type x:Object}">
    <x:Int32>69</x:Int32>
</x:Array>

... and gives the same error message.

**Comment by StephaneDelcroix** [comment]
we added additional tests for mismatching types. I'll look into that

**Comment by Tommigun1980** [comment]
> we added additional tests for mismatching types. I'll look into that

Thank you! I changed my code to use strings only and convert them back to appropriate data types via converters, but it's getting a bit unwieldy.
