### ISSUE TITLE
[Bug] Shell.GoToAsync(..., true); not animating on Android?

### ISSUE THREAD

**Issue by RGBPlaza** [xamarin/Xamarin.Forms#11624]
### Description
By default I get a fade page transition on iOS when calling this but on Android it's just cutting from one page to the next, which is making my app feel less fluid than would be preferred. Maybe I'm missing something, perhaps there isn't meant to be any kind of transition like that on Android and I didn't know. Additionally, Shell.PresentationMode seems to have no effect either (although I haven't tested that on iOS).

I assume this is possibly the reason why the Plugin.SharedTransitions library isn't doing anything on these transitions either - which is quite upsetting. The Xamarin Forms default transition and the plugin ones do work for Navigation.PushAsync but that isn't enough anymore, especially since Shell is encouraged (and for good reason). 

### Steps to Reproduce

1. Create an application with two distinct areas within Shell (i.e. ShellContents nested within TabBars) 
2. Navigate using Shell.Current.GoToAsync(..., true); from one ShellContent to another.

### Expected Behavior
Shell navigates from one page to another with a basic transition (I don't know what it is because I haven't seen what it's meant to be!)

### Actual Behavior
Shell cuts from one page to another, leaving the experience feeling disjointed. 

### Basic Information

- Version with issue: Xamarin Forms 4.7.0.1179
- Last known good version: Unknown
- IDE: Visual Studio Community 2019
- Platform Target Frameworks:
  - Android: 10.0, 8.1
- Affected Devices: Nokia 7 Plus, Moto G5

**Comment by PureWeen** [comment]
duplicate 
https://github.com/xamarin/Xamarin.Forms/issues/10638
