### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Metehanma** [xamarin/Xamarin.Forms#11636]
### Description
Navigation GoToAysnc goes to where is described or forwarded. How ever if you select another page from menu. it goes back to page that you came from.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
Thanks for this report. Could you do the extra step of providing a bit more information? With a bug report in this state, there's nothing we can do at all, I'm then closing it. Feel free to reopen or create a new one, with enough information for us to help you.
