### ISSUE TITLE
ReactiveViewCell contents are not updated dynamically

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/Xamarin.Forms#11639]
### Description
ReactiveViewCell contents are not updated dynamically when used like below in ViewModel,

        private readonly ObservableAsPropertyHelper<string> _icon;
        private readonly ObservableAsPropertyHelper<string> _label;

### Steps to Reproduce

1. Run the below sample,
2. Add the Items using Add Button,
3. Click the GetCountries Button,
4. Items are not added in the ListView.

### Expected Behavior

Items should be added to the ListView.

### Actual Behavior

Items are not added in the ListView.

### Basic Information

- NuGet Packages: 4.7
- Affected Devices: All

### Reproduction Link
[ReactiveIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5015433/ReactiveIssue.zip)

### Workaround

Use as a string and it will work,

[ReactiveViewCell.zip](https://github.com/xamarin/Xamarin.Forms/files/5015429/ReactiveViewCell.zip)

**Comment by PureWeen** [comment]
@RabhiaBehamK I don't quite get how you're using WhenAnyValue here

```C#
public CountryViewModel(string icon, string label)
        {
            _icon = icon.WhenAnyValue(x => x)
                        .ToProperty(this, nameof(Icon));

            _label = label.WhenAnyValue(x => x)
                        .ToProperty(this, nameof(Label));
        }
```

icon and label are strings. Most cases I've seen for WhenAnyValue

https://www.reactiveui.net/docs/handbook/when-any/

Are against the VM itself 

```C#
this.WhenAnyValue(x => x.Red, x => x.Green, x => x.Blue, 
                  (r, g, b) => new Color(r, g, b));
```

and used to create composite properties

It this seems like a bug with RxUI I would log an issue over there
https://github.com/reactiveui/ReactiveUI
