### ISSUE TITLE
[Bug] DataPackageOperation enumeration is a Flags enumeration

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#11646]
### Description

The `DataPackageOperation` enumeration, used in drag and drop, defines `None` and `Copy` members. However, this enumeration is also a `Flags` enumeration. It seems unlikely that users will want to combine these members.

**Comment by PureWeen** [comment]
@davidbritch it's currently a flag because there's a `Move` and a `Link` flag coming in the future. 

https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackageoperation?view=winrt-19041
