### ISSUE TITLE
FindByName extention method is not working for the Xaml that we created  other than page [Bug] 

### ISSUE THREAD

**Issue by DharmendarD** [xamarin/Xamarin.Forms#11644]
### Description
We recently updated our application to the latest Xamarin Forms version from v2.5.1. One of the features that were working in an earlier version got broke in the latest version. We are facing crashes in our application because of that. The issue scenario is mentioned below.
  
Say we have a contentview in a page and its content (Stacklayout with 4 entries with different x:Name) is getting assigned dynamically through a style that we declared in the application resource. In code-behind when you try to get one of the entries from the content using its x:Name that you have given XAML. You will get a null value. But for the same was working in v2.5.1

When I dig a little bit deeper, I found the name scope which is used to find element by name, is not getting assigned for the content which is created using Xaml in v4.7. But it is getting assigned in v2.5.1

### Steps to Reproduce

1. Create the style for assigning the content (Stacklayout with 4 entries with different x:Name) to the contentview.
2. Set the style to contentview which is used on your page.
3. In a button-click try to get the one of the entry from the contentview content using its x:Name. 

### Expected Behavior
FindByName should return entry instance.

### Actual Behavior
FindByName returning null value.

### Basic Information

- Version with issue: 4.7
- Last known good version: 2.5.1
- IDE: VS2019
- Platform Target Frameworks: ( Xaml Issue irrelevant to platform )
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: https://www.nuget.org/packages/Xamarin.Forms/4.7.0.1179
- Affected Devices:

### Screenshots
NA

### Reproduction Link

https://github.com/xamarin/Xamarin.Forms/files/5021013/FindByNameBug.zip

### Workaround

Created separate Xaml view for the content that we are using in style. And accessing entry from that custom Xaml view.

**Comment by StephaneDelcroix** [comment]
we fixed some issues with namescope since 2.5, mainly for xaml controls inheriting from each other. if that's it, this isn't a bug, the previous behaviour (that was working for you) was a bug.

but without a code reproduction, I can't tell if this is it, or you found a genuine bug. mould you please attach one (the simplest possible code that triggers the problem) ? thanks

**Comment by DharmendarD** [comment]
> we fixed some issues with namescope since 2.5, mainly for xaml controls inheriting from each other. if that's it, this isn't a bug, the previous behaviour (that was working for you) was a bug.
> 
> but without a code reproduction, I can't tell if this is it, or you found a genuine bug. mould you please attach one (the simplest possible code that triggers the problem) ? thanks

Sure @StephaneDelcroix  will create reproducing sample and share shortly.

**Comment by DharmendarD** [comment]
[FindByNameBug.zip](https://github.com/xamarin/Xamarin.Forms/files/5021013/FindByNameBug.zip)

PFA reproducing sample

**Comment by PureWeen** [comment]
@StephaneDelcroix looks like this is still an issue

**Comment by StephaneDelcroix** [comment]
not a bug. `entry2` isn't in the scope of `contentview`
