### ISSUE TITLE
iOS Pan and Tap Gesture Issues

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#11655]
### Description

This has been an odd one to reproduce consistently. I think there's some bin/obj issues interfering. 

**EDIT:** I can now repro consistently by toggling UseSafeArea. Enabled it's fine. Disabled I get the odd behavior.

Original issue was the Pan gesture works on the Frame, but the tap on the BoxView behind it didn't work. Then the BoxView was working with the Tap, but the Frame wouldn't Pan. I swapped for a Grid which made no difference. I added Material which made no difference (my full app uses Material, so I brought it into the mix).

I also tried with Shell and with NavigationPage. Both exhibited the same odd behaviors.

### Steps to Reproduce

1. Open the bottom drawer via the toolbar item
2. Grab and pan up/down - should not go up farther than the open position. Down 50% it'll spring back to open; otherwise it'll close.
3. Tap the background or the toolbar item to close it

### Expected Behavior

The above all works like that. Android was working fine just now.

### Actual Behavior

On iOS either the pan or the tap won't work and it's inconsistent between builds.

### Basic Information

- Version with issue: 4.6 - 4.8-pre3 have been tried
- Platform Target Frameworks: 
  - iOS: 13.6
  - Android: 28 was fine

### Screenshots

Cannot tap the background which has the tap gesuture. The pan on the Frame works fine: 

https://www.screencast.com/t/a1i3txEPN

Tapping on the Frame dismisses, but that gesture isn't on Frame, it's on the BoxView behind it. 

https://www.screencast.com/t/Me8xHk1iyT

### Reproduction Link

https://github.com/davidortinau/SampleBottomDrawer

**Comment by PureWeen** [comment]
@davidortinau so is the issue that sometimes it gets in a state where clicking the area above the bottom drawer doesn't close it?

is the main branch on that repository still setup to demonstrate the problem? I keep trying to get it into a state where clicking the background won't close the drawer but it keeps working for me

**Comment by davidortinau** [comment]
> is the main branch on that repository still setup to demonstrate the problem?  

@PureWeen no, you need to disable safe area as I describe.

**Comment by jsuarezruiz** [comment]
So, disabling Safe Area, tapping he area above the bottom drawer doesn't work, right?
![issuepangesture](https://user-images.githubusercontent.com/6755973/107221352-ceb7b180-6a13-11eb-8e8b-1f373b6d6784.gif)
Tested on iOS 14.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
