### ISSUE TITLE
Xamarin radio button not working properly

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11659]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1131715/xamarin-radio-button-not-working-properly.html)._

---
<p>I am using a list of radio buttons inside a carousel view. Its like a list of radio inside another list. I am using group name for each list.</p>
<p></p>carousel 1list 1radio1group1radio2group1radio3group1carousel 2list 2radio1group2radio2group2radio3group2carousel 3list 3radio1group3radio2group3radio3group3<p>In this case, radiobuttons are perfectly working in Android, but not working in iOS. </p> <p><b>If I selected a radio in second carousel, same radio get selected in third carousel and not able to change.</b> Sometimes its working fine, sometimes it gets failed.</p>

---
#### Feedback Bot on 7/30/2020, 07:32 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
@hartez

**Comment by ppungpong4200** [comment]
I had this problem too and don't know why.

**Comment by hartez** [comment]
I think some formatting got lost from the original issue, so it's difficult to tell for sure, but I think this is another instance of the problem described in issue #9200. 

Please take a look [my comments there](https://github.com/xamarin/Xamarin.Forms/issues/9200#issuecomment-643822589) - you likely just need to databind your RadioButtons.

If that does not work or I've misunderstood the issue, leave a comment here and I'll reopen this issue.
