### ISSUE TITLE
[Enhancement] Provide better style hook points for material android

### ISSUE THREAD

**Issue by PrimoDev23** [xamarin/Xamarin.Forms#11652]
### Description

After adding a dark theme to my app I wanted to use Material Components.
Before doing this I added some styles for android dialogs in styles.xml that aren't applied anymore after switching to Material.

### Steps to Reproduce

1.  Create a Page and add a Picker
2. Edit styles.xml of Android Project and switch MainTheme parent to "Theme.AppCompat" (For Visual="Default" this will make the Dialog gray-ish)
3. Now add Visual="Material" to the Picker (ofcourse install the NuGet for this first)

Same can be done with a DatePicker, define a style for it in styles.xml and after adding visual="Material" it just ignores your style completely.

### Expected Behavior

Still gray-ish background of the Picker

### Actual Behavior

White background

### Basic Information

- Version with issue: 4.7.0.1239
- Last known good version: -
- IDE: Visual Studio Enterprise 2019
- Platform Target Frameworks: 
  - Android: 10.0
- Nuget Packages: Xamarin.Forms.Visual.Material

### Screenshots

![grafik](https://user-images.githubusercontent.com/46970398/89317831-387a8b80-d67e-11ea-91ee-cf50b5163943.png)
![grafik](https://user-images.githubusercontent.com/46970398/89317842-3fa19980-d67e-11ea-9670-d330b16b66ce.png)

**Comment by PureWeen** [comment]
@PrimoDev23 the material controls are using a ContextThemeWrapper so it's not using that theme. It uses the Theme here https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Material.Android/Resources/values/styles.xml#L9 which gets passed into the Dialog

If you want to effect the material theme you can add this to your style.xml file and then change the parent theme or add other styles to things like adjusting the dialog

```xml
<style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
        <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
        <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
        <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
        <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
        <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
    </style>
```

**Comment by PrimoDev23** [comment]
> @PrimoDev23 the material controls are using a ContextThemeWrapper so it's not using that theme. It uses the Theme here
> 
> https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Material.Android/Resources/values/styles.xml#L9
> which gets passed into the Dialog
> 
> If you want to effect the material theme you can add this to your style.xml file and then change the parent theme or add other styles to things like adjusting the dialog
> 
> ```
> <style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
>         <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
>         <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
>         <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
>         <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
>         <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
>         <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
>     </style>
> ```

Thanks for your quick reply. I just woke up and gonna try this as soon as possible!

**Comment by PrimoDev23** [comment]
So I have tried using Theme.MaterialComponents as my dark theme parent now

What happens is just this
![grafik](https://user-images.githubusercontent.com/46970398/89378860-00625f80-d6f5-11ea-9fd8-bf6cc798b126.png)

So not as expected. Date and Timepicker are also still in white when using this Theme.
The behavior definitely differs from the default behavior where "Theme.AppCompat" is also theming dialogs for a dark theme.

**Comment by PureWeen** [comment]
Can you post your styles.xml file?

You have to literally copy and paste this exact code here

```xml
<style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
        <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
        <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
        <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
        <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
        <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
    </style>
```

into your styles file and modify the parent.

The only way to effect the material components is to create a style called `XamarinFormsMaterialTheme` which will cause the material components to use that instead of the one packaged with material

**Comment by PrimoDev23** [comment]
> Can you post your styles.xml file?
> 
> You have to literally copy and paste this exact code here
> 
> ```
> <style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
>         <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
>         <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
>         <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
>         <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
>         <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
>         <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
>     </style>
> ```
> 
> into your styles file and modify the parent.
> 
> The only way to effect the material components is to create a style called `XamarinFormsMaterialTheme` which will cause the material components to use that instead of the one packaged with material

`<?xml version="1.0" encoding="utf-8" ?>
<resources>

  <style name="MainTheme" parent="MainTheme.Base">
  </style>
  
  <style name="MainTheme.Base" parent="Theme.MaterialComponents.Light.DarkActionBar">
    
    <item name="windowNoTitle">true</item>
    
    <item name="windowActionBar">false</item>
    
    
    <item name="colorPrimary">#d32f2f</item>
    
    <item name="colorPrimaryDark">#ffffff</item>
    
    <item name="colorAccent">#d32f2f</item>
    
    <item name="windowActionModeOverlay">true</item>

    
    
    <item name="alertDialogTheme">@style/AppCompatAlertStyleLight</item>
  </style>
  
  <style name="MainTheme.BaseDark" parent="Theme.MaterialComponents">
    
    <item name="windowNoTitle">true</item>
    
    <item name="windowActionBar">false</item>
    
    
    <item name="colorPrimary">#d32f2f</item>
    
    <item name="colorPrimaryDark">#ffffff</item>
    
    <item name="colorAccent">#d32f2f</item>
    
    <item name="windowActionModeOverlay">true</item>

    
    
    <item name="alertDialogTheme">@style/AppCompatAlertStyleDark</item>
  </style>

  <style name="AppCompatAlertStyleLight" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="colorAccent">#d32f2f</item>
  </style>
  
  <style name="AppCompatAlertStyleDark" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="colorAccent">#d32f2f</item>
    <item name="android:textColorPrimary">#FFFFFF</item>
    <item name="android:background">#272727</item>
  </style>
</resources>
`

This is almost the same version as my current one (I am not at home and haven't pushed latest changes yet).
I am using a DependencyService to change themes with the following line

`MainActivity.Instance.SetTheme(theme == Theme.Light ? Resource.Style.MainTheme_Base : Resource.Style.MainTheme_BaseDark);`

Since I only have issues with the color of dialogs I thought I don't need to explicitly add materialButtonStyle. Is there any specific item name for dialogs so I can modify them?
And if I don't need other styles except dialogs, do I really need to add a style named XamarinFormsMaterialTheme? Shouldn't it be enough to just change MainTheme.Base's parent?

Thanks in advance

**Comment by PureWeen** [comment]
@PrimoDev23 much like appcompat controls requiring an appcompat compatible theme Material controls require a Material related theme.

If you don't apply a Material theme to a material control you'll get an exception that says "A material theme is required to use this control"

the Material controls were largely built with the intention of making them symmetrical between iOS and Android and not wanting the user to have to customize things at the platform level.

So the best fix here would be for us to expose xplat properties to achieve what you want for setting the background on the dialogs. We also need to make the apptheme stuff work at the material level :-/ which still needs to be done

**Comment by PureWeen** [comment]
> And if I don't need other styles except dialogs, do I really need to add a style named XamarinFormsMaterialTheme? Shouldn't it be enough to just change MainTheme.Base's parent?

This is the feature that I changed the title of this issue to. Looking at places to make this easier to hook into so you don't have to provide the entire theme

I think to customize the dialog you would copy the `XamarinFormsMaterialTheme` and then add a 

```xml
<item name="android:alertDialogTheme">@style/MyAlertDialogTheme</item>
    <item name="android:alertDialogStyle">@style/MyAlertDialogStyle</item>
```

But I would need to play with it a bit more to know if those are the hooks to use

**Comment by PrimoDev23** [comment]
> @PrimoDev23 much like appcompat controls requiring an appcompat compatible theme Material controls require a Material related theme.
> 
> If you don't apply a Material theme to a material control you'll get an exception that says "A material theme is required to use this control" so the material controls don't use the `MainTheme.Base` style at all
> 
> the Material controls were largely built with the intention of making them symmetrical between iOS and Android and not wanting the user to have to customize things at the platform level.
> 
> So the best fix here would be for us to expose xplat properties to achieve what you want for setting the background on the dialogs. We also need to make the apptheme stuff work at the material level :-/ which still needs to be done

So there is no way to achieve what I am searching for? I tried the same with a custom renderer but couldn't achieve the same look as default picker Dialog (using a numberpicker)
My current working solution is using appcompat theme which is working fine for dialogs but we all know material is just looking great. Maybe you know how to achieve what I want with a custom renderer? Or isn't that possible?

**Comment by PrimoDev23** [comment]
> > And if I don't need other styles except dialogs, do I really need to add a style named XamarinFormsMaterialTheme? Shouldn't it be enough to just change MainTheme.Base's parent?
> 
> This is the feature that I changed the title of this issue to. Looking at places to make this easier to hook into so you don't have to provide the entire theme
> 
> I think to customize the dialog you would copy the `XamarinFormsMaterialTheme` and then add a
> 
> ```
> <item name="android:alertDialogTheme">@style/MyAlertDialogTheme</item>
>     <item name="android:alertDialogStyle">@style/MyAlertDialogStyle</item>
> ```
> 
> But I would need to play with it a bit more to know if those are the hooks to use

I gonna try to add the whole theme later, if it doesn't work I will just stick to the default visual until there is a way to do this :)

**Comment by PureWeen** [comment]
@PrimoDev23 I tested this real quick and it's not perfect but hopefully it's the right enough direction to get you want you want and you can just play with the themes styles to get it how you want to look

```xml
    <style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
        <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
        <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
        <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
        <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
        <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
        <item name="android:datePickerDialogTheme">@style/MaterialTheme</item>
        <item name="android:alertDialogTheme">@style/MaterialTheme</item>
        <item name="android:alertDialogStyle">@style/MaterialTheme</item>
    </style>

  <style name="MaterialTheme" parent="Theme.MaterialComponents">
        <!-- Add additional customizations here-->
  </style>
```

**Comment by PrimoDev23** [comment]
> ```
> <style name="XamarinFormsMaterialTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
>         <item name="materialButtonStyle">@style/XamarinFormsMaterialButton</item>
>         <item name="materialOutlinedButtonStyle">@style/XamarinFormsMaterialButtonOutlined</item>
>         <item name="materialSliderStyle">@style/XamarinFormsMaterialSlider</item>
>         <item name="materialProgressBarHorizontalStyle">@style/XamarinFormsMaterialProgressBarHorizontal</item>
>         <item name="materialProgressBarCircularStyle">@style/XamarinFormsMaterialProgressBarCircular</item>
>         <item name="materialCheckBoxStyle">@style/XamarinFormsMaterialCheckBox</item>
>         <item name="android:datePickerDialogTheme">@style/MaterialTheme</item>
>         <item name="android:alertDialogTheme">@style/MaterialTheme</item>
>         <item name="android:alertDialogStyle">@style/MaterialTheme</item>
>     </style>
> 
>   <style name="MaterialTheme" parent="Theme.MaterialComponents">
>         
>   </style>
> ```

So I finally figured out how to make it work properly with a dialog in correct color. Now my only problem is, that it uses that dark dialog even with light theme, so i guess a theme change on activity isn't working anymore after loading style "XamarinFormsMaterialTheme".
Looks like this
![grafik](https://user-images.githubusercontent.com/46970398/89458844-03e2fe80-d768-11ea-9fc1-36d5c5583ef1.png)

On non material design, I could just switch Themes with this line while running the app

`MainActivity.Instance.SetTheme(theme == Theme.Light ? Resource.Style.MainTheme_Base : Resource.Style.MainTheme_BaseDark);`

If I use this now just nothing happens and the Theme-switch isnt working properly.
I tried adding a style "XamarinFormsMaterialLightTheme" and renamed the other one into "XamarinFormsMaterialDarkTheme"
If I do this it just uses the Light-Theme again (or no theme probably since it looks like I never touched it)

So can I switch between "XamarinFormsMaterial...Theme" like I could before with the AppCompat parents or isn't that possible currently?

**Comment by thisismyself** [comment]
The AppThemeBinding feature is absolutely great. But issues like this here make styling really annoying, frustrating and just partly usable. It gives Xamarin-haters in managements and tech boards arguments against Xamarin, unfortunately.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
