### ISSUE TITLE
[Bug] Android Shapes drawing Line disappears on page pop and returning back to the page won't draw again

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#11656]
### Steps to Reproduce

1. When I draw a simple line using like code below on contentview inside a contentpage (it could be the problem on contentview)
2. I simply click backbutton to pop the page
3. if I navigate to the page again Line is not drawn. 

```
 <Line
                    x:Name="Line"
                    Stroke="#FF707070"
                    X1="55"
                    X2="150"
                    Y1="90"
                    Y2="120" />
```

 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
 
  - Android:  Android 10
 
- Android Support Library Version: 
- Nuget Packages: XF 4.7 
- Affected Devices: tested on emulator

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by jsuarezruiz** [comment]
@EmilAlipiev Could you attach a reproduction sample?. I have created a test trying to reproduce the problem, but without success.
![issue11656](https://user-images.githubusercontent.com/6755973/89771238-4a39b400-db00-11ea-8b25-479f1017be33.gif)

**Comment by oscarjaergren** [comment]
1+ on this bug, just discovered it in my application

**Comment by RGBPlaza** [comment]
I am having this problem too and my app is very close to release (about 5 days). Would be very nice if this could be solved asap!

**Comment by edmlbox** [comment]
I have the exact same problem with **line** and **ellipsis** and **path** object. When navigating in shell.

**Comment by edmlbox** [comment]
Still an issue. After switching pages in Shell ellipse simply disappears.

**Comment by orimslala** [comment]
Equally hitting this problem. I have round Ellipses in my main page. Noticed it when i integrated the AppShell with tab bar navigation into my app. The issues pops up when i navigate between tabs. once i return back to my main page, the ellipses have already disappeared :-(
