### ISSUE TITLE
[Bug][Android] Two spans on multiline label with TapGestureRecognizer events have an incorrect behavior

### ISSUE THREAD

**Issue by cdognini87** [xamarin/Xamarin.Forms#11650]
### Description
I have two spans on the multiline label with intercepted events. On Android, when i clicked on "second" the first event is also called. This happens if the spans with the events are on the same line as in the Screenshots image
### Steps to Reproduce

1. Run the attached sample.
2. Click on the second span with TapGestureRecognizer (secondStr)
3. The first span TapGestureRecognizer  event is also called

### Expected Behavior
Only the command related to the span clicked is called
### Actual Behavior
If I clicked the "second" span the first span event is also called
### Basic Information

- Version with issue: 4.7.0.1239
- Last known good version: 4.5.0.396
- IDE: VS2019

- Platform Target Frameworks: 
  - Android: API 29

### Screenshots
![Screenshot_2020-08-03-14-48-56](https://user-images.githubusercontent.com/51325713/89300388-68b72f80-d668-11ea-8bc5-8ed52a462259.png)

### Reproduction Link
[AppDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/5022408/AppDemo.zip)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/11650

**Comment by AndreiMisiukevich** [comment]
> duplicate #11650

You reference the same ticket :)

**Comment by PureWeen** [comment]
Ooops

I'll just act like I meant to indicate this one
https://github.com/xamarin/Xamarin.Forms/issues/4143

Maybe I did? Maybe I didn't?
