### ISSUE TITLE
CollectionView's SelectionChanged/SelectionChangedCommand not recognizing Tap

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11658]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1125297/collectionviews-selectionchangedselectionchangedco.html)._

---
<p>Hi All,</p><p></p><p><strong>Issue</strong></p><p>I recently migrated a ListView to a CollectionView within our application. After the migration, I immediately noticed an issue with the cell inside of the CollectionView. </p><p></p><p>The setup was relatively straight-forward - as my Bindings for SelectedItem &amp; SelectionChangedCommand to the ViewModel work correctly (kinda). When I tap on a cell within the CollectionView, nothing happens. When I tap, hold, and then drag the cell within the CollectionView, only then is SelectionChangedCommand Binding invoked. </p><p></p><p><strong>Target Devices</strong></p><p>This is only happening on iOS - as Android seems to be able to handle the tap. </p> <p></p><p><strong>Specs</strong></p><p>Xamarin.Forms v4.7</p><p>iOS 13.4.1</p><p></p><p><b>Additional Comments</b></p><p>Assuming this is a bug related to Xamarin.Forms, I decided to leave my code snippets out, but I can show code upon request.</p> <p></p><p>Thanks!</p>

---
#### Feedback Bot on 7/26/2020, 08:33 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Duplicate
https://github.com/xamarin/Xamarin.Forms/issues/11550
