### ISSUE TITLE
[Bug] Two spans on label have an incorrect behavior

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#11657]
### Description
A Label with two Span.GestureRecognizers has an incorrect behavior.

### Steps to Reproduce

1. create a new xamarin form app;
2. copy the following code to the new app:
     
```
       <StackLayout Margin="20">
        <Label Text="Demo" LineBreakMode="WordWrap"
               HorizontalOptions="Center"
               FontAttributes="Bold" />
        <Label>
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, .... " />
                    <Span Text="first"
                          x:Name="firstStr"
                          TextColor="Blue"
                          TextDecorations="Underline">
                    </Span>
                    <Span Text=" and  " />
                    <Span Text="second"
                          x:Name="secondStr"
                          TextColor="Blue"
                          TextDecorations="Underline">
                    </Span>
                </FormattedString>
            </Label.FormattedText>
        </Label>
      </StackLayout>
```

  the xaml.cs code

```
 firstStr.GestureRecognizers.Add(new TapGestureRecognizer { Command = new Command(async () => await DisplayAlert("Alert", "Command 1 clicked", "OK")) });

secondStr.GestureRecognizers.Add(new TapGestureRecognizer { Command = new Command(async () => await DisplayAlert("Alert", "Command 2 clicked", "OK")) });
```
3. deploy the app to a device;

Note: Remember to let the two spans(Span `first` and span `second` ) in the same line and make sure use code `<Span Text=" and  " />` for span `and`. Only in this case can we reproduce the problem.

### Expected Behavior

Span `first` and span `second` could be work properly.( Click the corresponding span and the corresponding message will pop up.)

### Actual Behavior
 
When we click the span `second`, the  Alert `DisplayAlert("Alert", "Command 1 clicked", "OK")` and  `DisplayAlert("Alert", "Command 2 clicked", "OK")` will been all triggered.

### Screenshots

![0805_1](https://user-images.githubusercontent.com/42464252/89365989-72906f80-d708-11ea-90e9-239db46b1569.gif)

**Comment by carbonete** [comment]
Any news?  this bug is critical for my project.
