### ISSUE TITLE
VisualState.StateTriggers not firing on rotation change

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11660]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1133329/visualstatestatetriggers-not-firing-on-rotation-ch.html)._

---
https://github.com/nodoid/VisualStateGroup

I'm starting to impment a complex UI using the latest Xam.Forms and have tried using the VisualState.StateTriggers to just do something as simple as alter the background colour when I change the orientation. It's not working (stays one colour). The linked GitHub project shows this. I've not tried on iOS but am seeing on Android.

---
#### Feedback Bot on 8/3/2020, 00:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Can you provide more information about the device you are using?
Do you have orientation locked on the device perhaps so it's not actually rotating?

I tested this against your sample and it's working for me

![2020-08-05_12-35-01](https://user-images.githubusercontent.com/5375137/89445147-60b6c880-d718-11ea-9c0e-f9ce76fb7ecc.gif)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
