### ISSUE TITLE
[Enhancement] Consider making RefreshView available with all Layout containers

### ISSUE THREAD

**Issue by glatzert** [xamarin/Xamarin.Forms#11675]
## Summary
Despite it being written on the RefreshView Documentation Page, I just sunk like 3 hours in trying to make a RefreshView work with another container. I think it should not depend on scrollable content, since there's no reason to disallow a StackLayout from being refreshed, if it's not in a ScrollView.

(Also I'd suggest to remove the RefreshView and replace it with an Behavior on either layout or ContentView.)

## API Changes

Sorry - don't know.

## Intended Use Case
Allow RefreshView to be used throughout Xamarin Forms instead of only with the scrollables (especially since nesting ScrollViews is problematic)

**Comment by PureWeen** [comment]
Yea, the main issue here @glatzert is that we are using all the native implementations for refresh controls and all of those (except I think UWP) require a scroll view

There's a really good chance with MAUI that we might move our RefreshControl implementation to using a swipe view which would allow a lot more scenarios like you are indicating here

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/199
