### ISSUE TITLE
[Enhancement] Xamarin.Forms Shell ItemTemplate could inherit BindingContext from Shell

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#11670]
## Summary
As shown [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#define-flyoutitem-appearance) it is possible to define a custom Layout for Shell.ItemTemplate but **only Title and FlyoutIcon are propagated as BindingContext**.

## Intended Use Case

Would be great to inherit the BindingContext from Shell when defining the following
````
<Shell.ItemTemplate>
        <DataTemplate>
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="0.2*" />
                    <ColumnDefinition Width="0.8*" />
                </Grid.ColumnDefinitions>
                <Image Source="{Binding FlyoutIcon}"
                       Margin="5"
                       HeightRequest="45" />
                <Label Grid.Column="1"
                       Text="{Binding Title}"
                       FontAttributes="Italic"
                       VerticalTextAlignment="Center" />
            </Grid>
        </DataTemplate>
    </Shell.ItemTemplate>
````

**Comment by PureWeen** [comment]
The binding context set on the template is the ShellItem itself so if you want to get to the BindingContext then use BindingContext. 

It's similar to control templates how the bindingcontext on the control template is the control itself

```XAML
<Label Grid.Column="1"
                       Text="{Binding BindingContext.Thing}"
                       FontAttributes="Italic"
                       VerticalTextAlignment="Center" />
```

**Comment by MaxFmi** [comment]
Wasn't aware that it's possible to use "**BindingContext.***" in Shell.ItemTemplate like you mentioned in Text="{Binding BindingContext.Thing}"

Thanks for the hint
