### ISSUE TITLE
[Bug] Button command binding interferes with starting value of a IsEnabled attribute binding

### ISSUE THREAD

**Issue by baarhus** [xamarin/Xamarin.Forms#11673]
### Description
When binding a property to the IsEnabled attribute on a button, then binding an ICommand property to the Command attribute, the button will always be enabled on startup. Reversing the order in which they are declared in XAML (command before isenabled) appears to fix the problem.

### Steps to Reproduce

1. Create a button with an IsEnabled binding in XAML
2. Add a Command binding, placer after the IsEnabled attribute, in XAML
3. In code behind of XAML, set the binding context to a ViewModel
4. In that same ViewModel, setup the ICommand property and IsEnabled property that are bound to the UI
5. Set the default value of the backing store for the IsEnabled property to false (suggesting the button should be disabled on startup)
6. Launch the application

### Expected Behavior
The button should start disabled, and respond appropriately to changes on the IsEnabled bound property.

### Actual Behavior
The button starts enabled, but still responds as expected to changes on the IsEnabled bound property.

### Basic Information

- Version with issue: Xamarin.Forms 4.7.0.1239
- Last known good version: Unknown
- IDE: Visual Studio Community 16.6.5
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 10.3.1.4
  - UWP:  N/A
- Android Support Library Version: AndroidX
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials, Newtonsoft.Json, NETStandardLibrary
- Affected Devices: Android Emulator

### Workaround

Placing the Command attribute before the IsEnabled attribute in XAML causes expected behavior.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/2758
