### ISSUE TITLE
[Bug] Bindings: Relative binding self doesn't always work

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11671]
Relative binding self doesn't work when written as such:

```xaml
<?xml version="1.0" encoding="UTF-8"?>
<Frame
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    BindingContext="{RelativeSource Self}"
    x:DataType="xxx:yyy"
    x:Class="My.Class"
    x:Name="theRoot">

    <Frame.Content>
        ...
    </Frame.Content>
</Frame>
```

Replacing it with the following will work normally:

```xaml
BindingContext="{x:Reference theRoot}"
```

Any kinds of special cases where bindings don't work for whatever reason are extreme time sinks as things just don't work and there's no good debugging tools available other than starting to disable stuff until you figure out what's wrong. Given that a lot of this is auto-generated and there's no state visualising tools etc I'd really love it if bindings always worked **consistently** no matter the case.

Thanks!

**Comment by Tommigun1980** [comment]
@StephaneDelcroix Hi, I saw you self-assigned this. I just noticed that even the case which I said work doesn't work consistently.

My control has the following structure:

```
            <Image
                Source="{Binding Image}"
                d:IsVisible="False" />
            
            <Label
                Text="{Binding Text}"
                d:Text="Chip"
                FontFamily="{Binding FontFamily}"
                FontSize="{Binding FontSize}"
                TextColor="{Binding TextColor}"
                VerticalOptions="Center"
                HorizontalOptions="Center"
                VerticalTextAlignment="Center"
                HorizontalTextAlignment="Center" />
```

The image gets always assigned, but the label doesn't get anything assigned, in the case where the control is created from a data template.
For the label to get any values I must do a "..., Source={x:Reference theName}" inside their bindings.

**Comment by rmarinho** [comment]
Hi @Tommigun1980 can you provide a small repro project so we can take a look at this ? 

Thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
