### ISSUE TITLE
after 4.7.0.1142,  navigation doesn't show page on iOS

### ISSUE THREAD

**Issue by rasel-tr** [xamarin/Xamarin.Forms#11685]
First I got a "UpdateClip throws NullReferenceException" on a page after a forms update (#11132). This was resolved with 4.7.0.1142 version. But after that version, I can't open another page on from that page with navigation. I want to open a modal page onto another modal page and it doesn't shown. It doesn't give any errors also. The parent modal page doesn't respond to clicks anymore, like the child page was opened but not visible. This was working before and it is still working on Droid. 

With 4.8.0.1269 version, still same.  I tried to put On<iOS>().SetModalPresentationStyle(UIModalPresentationStyle.FullScreen) on page constructors but doesn't work. 

Anybody else having this problem?

**Comment by PureWeen** [comment]
@rasel-tr can you attach a repro please?

**Comment by rasel-tr** [comment]
> @rasel-tr can you attach a repro please?

Sure, here is a simplified project of this problem. You can test it on simulator. 

[repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5047217/repro.zip)

**Comment by rmarinho** [comment]
Hi @rasel-tr i tried your sample, with 4.60 and 4.7..0.1142 and it also doesn't show the Modal , 

in what version does this works ?

**Comment by rasel-tr** [comment]
Hello @rmarinho, after your message, I tried to re-produce the working behavior with downgrading forms and/or other components and nothing works. May be it is related with iOS SDK versions. 

I'm attaching a new solution that includes the android part. It is working on android without a problem. 

On iOS, It isn't giving an error to help me resolve the situation so I need your help. 

[repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5078070/repro.zip)

**Comment by rasel-tr** [comment]
ListView control tried to update the list on mainthread and the page was created on another thread causing this problem.
