### ISSUE TITLE
[Bug] Open the same WPF application with EmbeddedFont may throw IOException

### ISSUE THREAD

**Issue by lindexi** [xamarin/Xamarin.Forms#11687]
### Steps to Reproduce

1. Create a WPF application that will use EmbeddedFont in startup
2. Build the project and open the application twice

### Expected Behavior

We can use the EmbeddedFont 

### Actual Behavior

Sometime the `Xamarin.Forms.Platform.WPF.EmbeddedFontLoader` will throw IOException, because it will write the same font file.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
