### ISSUE TITLE
[Bug] When I set the ItemSource in the constructor or from XAML the CarouselView/CollectionView isn't rendering

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#11692]
### Description

Run the attached app and you'll see a blank page.
Oddly if you trigger hot reload the content loads, but only if you have full page reload enabled

### Steps to Reproduce

1.  Run the app
2. trigger hot reload
3. data appears

### Expected Behavior
you should see the word "Hello" on startup

### Actual Behavior
You see nothing

### Basic Information

- Version with issue:
- Last known good version: I tried back to 4.3 and same issue there

### Reproduction Link
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5045807/Archive.zip)

### Workaround
Load the data inside OnAppearing

**Comment by hartez** [comment]
@PureWeen  Remove ` x:DataType="vm:StackViewModel"` and it works fine.
