### ISSUE TITLE
[Enhancement] Is there a way to take snapshot for a xamarin view and It is not display

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/Xamarin.Forms#11698]
## Summary
I have a xamarin view and it is not display,I want to get the view snapshot and convert to android bitmap,is there a way to this target?

xamarin version : 4.2.0.778463

**Comment by PureWeen** [comment]
Hey @llzz19851985 apologies but I'm not quite following your question here.

I think you might have better luck getting this answered on StackOverflow

I'm going to move this issue to discussions for now

If you want to convert a forms view to a bitmap I would look at a few of the links here

https://stackoverflow.com/questions/5536066/convert-view-to-bitmap-on-android
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/
