### ISSUE TITLE
[Enhancement] MediaElement feature parity with VLC.

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Xamarin.Forms#11693]
## Summary
Can we get the MediaElement control to have feature parity with [VLC streaming features](https://www.videolan.org/streaming-features.html) and [VLC streaming protocols](https://wiki.videolan.org/Protocols/)?

https://code.videolan.org/videolan/LibVLCSharp/-/issues/379
## API Changes

I don't know the details for what needs to be changed, but the current implementation of the MediaElement control is not usable for streaming video; it can only play local files. I would greatly prefer to use the MediaElement control over VLC as its very seamless integration into a view compared to VLC.

## Intended Use Case
Stream video from virtually any server using any protocol.

**Comment by PureWeen** [comment]
Moved here

https://github.com/dotnet/maui/discussions/202
