### ISSUE TITLE
Erro XLS0503 A value of type 'Label' cannot be added to a collection or dictionary of type 'IList`1'

### ISSUE THREAD

**Issue by RobertoGFilho** [xamarin/Xamarin.Forms#11708]
Xamarin Forms 4.8 show up a error message, when I add label into Stacklayout.

<StackLayout>
	<Label Text="{Binding Name, Mode=OneWay}" />
</StackLayout>

**Comment by ludas96** [comment]
Happens everywhere. Adding a DataTrigger to a Triggers-collection also shows this error.

**Comment by jpacov** [comment]
Also happened to me when updating to Xamarin Forms 4.8.
After cleaning up the solution, then Rebuilding, then closing VS2019, then cleaning and rebuilding again (more or less that order hehe) the issue was gone.

**Comment by rmarinho** [comment]
Hi @RobertoGFilho , @ludas96  and @jpacov , if you clean and restart the IDE does it work for you?

Thanks

**Comment by jpacov** [comment]
For me yes, after cleaning, closing, reopening, rebuilding (not sure which order exactly and how many times) it finally stopped annoying to me.

**Comment by ludas96** [comment]
@rmarinho Yeah, cleaning the solution and restarting the IDE did indeed work.

**Comment by RobertoGFilho** [comment]
Now ! it's ok just update Visual Studio to Version 16.7.1 or latter

**Comment by lywyn** [comment]
I am getting this in 16.7.2 (see image) and also it stops the tab key working with Intellisense.  A mix of clean/rebuild/restart works but then it comes back?
![image](https://user-images.githubusercontent.com/4835688/92498393-7b3a0100-f1f2-11ea-9260-bd5c5adde9b7.png)

**Comment by michelevirgilio** [comment]
Same problem here, with VS 2019 16.7.2

**Comment by cjmurph** [comment]
> Same problem here, with VS 2019 16.7.2

It still did it for me in 16.7.2, but doesn't do it anymore in 16.7.5

**Comment by michelevirgilio** [comment]
Still here with 16.7.5
![image](https://user-images.githubusercontent.com/5950541/95973580-26526180-0e14-11eb-9974-a1a62e47a774.png)

**Comment by RobertoGFilho** [comment]
same here!

**Comment by gimenezfrg** [comment]
same here!

16.7.6

**Comment by danieletas** [comment]
Confirm issue is not fix  
![immagine](https://user-images.githubusercontent.com/11984305/96502069-96684980-1251-11eb-846f-8ff2260680cf.png)
![immagine](https://user-images.githubusercontent.com/11984305/96502111-a718bf80-1251-11eb-9f0e-3f7c02b1759f.png)

**Comment by RobertoGFilho** [comment]
it is not fix

**Comment by iBasisLtd** [comment]
Why is  this closed. Its not fixed and it costing me hours fixing valid xmal.

**Comment by gldfdp** [comment]
Still existing in VS 16.7.6 with Xamarin 16.7.000.456

![image](https://user-images.githubusercontent.com/4867906/96735829-41951200-13bc-11eb-9c00-13621a3c3895.png)

**Comment by mikewiner** [comment]
any status on a fix for this?

**Comment by Cannigor** [comment]
After cleaning and restarting solution i fix it

**Comment by KarthikRajaKalaimani** [comment]
this issue not fixed when attach xamarin source in simple project

**Comment by RAJESHFPB** [comment]
Just add Telerik.XamarinForms.Common.dll and error gone for me.
