### ISSUE TITLE
[Bug] [WPF] ScrollView - ScrollBarVisibility not respected

### ISSUE THREAD

**Issue by plamen-i** [xamarin/Xamarin.Forms#11709]
### Description

Dependent on orientation, respective scrollbar of ScrollView is still visible even ScrollBarVisibility is set to Never.

### Steps to Reproduce

`<ScrollView Orientation="Vertical" VerticalScrollBarVisibility="Never" />`

### Expected Behavior

No vertical scrollbar visible.

### Actual Behavior

Vertical scrollbar is still visible even not needed.

### Basic Information

- Version with issue: XF 4.8.0.1269
- Last known good version: N/A
- IDE: Visual Studio 2019 16.7.0
- Platform Target Frameworks:
  - WPF: .NET Framework 4.6.1
- Android Support Library Version: N/A

### Workaround

When set to Never in XAML as shown above - after UI has been shown switching to Default and then to Never hides the respective scrollbar.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
