### ISSUE TITLE
[Bug] UWP Shell - Toolbar buttons do not work correctly

### ISSUE THREAD

**Issue by JogyBlack** [xamarin/Xamarin.Forms#11706]
### Description

When using Shell in UWP project, the page toolbar items do not display correctly:
1. The Order="Secondary" property has no effect, buttons always display on the primary toolbar.
2. Toolbar icons do not display.

Note that is the same page is used in NavigationPage and not in Shell, the toolbar buttons display correctly.

### Steps to Reproduce

1. Create a default Xamarin.Forms app using Shell.
2. Add UWP project
3. Add toolbar items to the main page:
`  <ContentPage.ToolbarItems>
    <ToolbarItem Text="Add" Clicked="AddItem_Clicked" IconImageSource="tab_feed.png"/>
    <ToolbarItem Text="Secondary" Order="Secondary" IconImageSource="tab_about.png"/>
  </ContentPage.ToolbarItems>`

### Expected Behavior
Only the first button should show in the primary toolbar, along with an icon. 

### Actual Behavior
Both toolbar buttons show in the primary toolbar. They do not display any icon.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: None
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  18362

### Screenshots

<img width="376" alt="Toolbar" src="https://user-images.githubusercontent.com/1275686/89714338-9b0baa00-d952-11ea-8eb6-19254965aaef.png">

### Reproduction Link

[ToolbarTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5045462/ToolbarTest.zip)

**Comment by JogyBlack** [comment]
Regarding the images, in the debug output I see this error:
Error: Converter failed to convert value of type 'Xamarin.Forms.Internals.AsyncValue`1<Windows.UI.Xaml.Media.ImageSource>' to type 'ImageSource'; BindingExpression: Path='IconImageSource' DataItem='Xamarin.Forms.ToolbarItem'; target element is 'Windows.UI.Xaml.Controls.Image' (Name='null'); target property is 'Source' (type 'ImageSource').

**Comment by JogyBlack** [comment]
Looking around in XF code, I found this in the data template "ShellToolbarItemTemplate":
`<Image Source="{Binding IconImageSource, Converter={StaticResource ImageConverter}}" VerticalAlignment="Center" />`

from another place in XF source I see that the correct way to specify the binding is this:
`<Image DataContext="{Binding IconImageSource, Converter={StaticResource ImageConverter}}" Source="{Binding Value}" VerticalAlignment="Center" />`

If I copy the template in my test app, and make this correction, the images now show. But they are too small because there is not enough space for them. Perhaps changing template to put them in different grid columns instead of rows is better. Hre is the full template:

`<DataTemplate x:Key="ShellToolbarItemTemplate">
      <xf:ShellToolbarItemRenderer ToolbarItem="{Binding}" Margin="0" Background="Transparent" BorderThickness="1"
                      IsEnabled="{Binding IsEnabled}" Command="{Binding Command}" CommandParameter="{Binding CommandParameter}">
        <Grid>
          <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"></ColumnDefinition>
            <ColumnDefinition Width="Auto"></ColumnDefinition>
          </Grid.ColumnDefinitions>
          <Image 
				    DataContext="{Binding IconImageSource, Converter={StaticResource ImageConverter}}" Source="{Binding Value}" VerticalAlignment="Center" />
          <TextBlock Grid.Column="1" Foreground="White" VerticalAlignment="Center" Text="{Binding Text}"></TextBlock>
        </Grid>
      </xf:ShellToolbarItemRenderer>
    </DataTemplate>
`

**Comment by holecekp** [comment]
Are there any news on this issue (primary vs. secondary items)? Is there any workaround? I have found that there was a similar problem on Android and it was fixed a year ago (https://github.com/xamarin/Xamarin.Forms/issues/6127).
