### ISSUE TITLE
[Bug] [UWP] Setting the FontFamily crashes a multi-window app

### ISSUE THREAD

**Issue by KPixel** [xamarin/Xamarin.Forms#11705]
### Description

Since #2432, Xamarin.Forms supports creating apps with multiple windows in UWP.
However, if we use the same custom font on these windows, then we get an exception when trying to create the secondary windows.

### Steps to Reproduce

[The Control Gallery already has a multi-window sample](https://github.com/xamarin/Xamarin.Forms/blob/29b92aa1fc2b9d834bb3b95cc224e07d0cc3e9b4/Xamarin.Forms.Controls/CoreGallery.cs#L603), we just need to update it to set a custom FontFamily:

1. Update the content page that is created for these secondary windows:
https://github.com/xamarin/Xamarin.Forms/blob/29b92aa1fc2b9d834bb3b95cc224e07d0cc3e9b4/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs#L88
After this line, add:

```C#
if (Device.RuntimePlatform == Device.UWP)
    layout.Children.Add(new Label { Text = "\xE76E", FontFamily = "Segoe MDL2 Assets", FontSize = 32 });
```

2. Run the Control Gallery app and click on the "Open Secondary Window" button twice.

### Expected Behavior

The app should create as many windows as we want.

### Actual Behavior

The app crashes when we try to create its third window.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: N/A
- IDE: Visual Studio 2019 16.7
- Platform Target Frameworks:
  - UWP:  18362

### Solution

This issue is caused by the fact that fonts are cached; so they end up being shared by all windows (which is not allowed):

https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Platform.UAP/FontExtensions.cs#L14

The solution should be to change that cache to be thread-static:

```C#
[ThreadStatic]
static Dictionary<string, FontFamily> FontFamilies;
```

Then, instantiate it before this line:

https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Platform.UAP/FontExtensions.cs#L96

```C#
if (FontFamilies == null)
    FontFamilies = new Dictionary<string, FontFamily>();
```

That should be enough.

**Comment by KPixel** [comment]
### Another bug (which could go into its own issue if needed)

The secondary window does not resize its `ContentPage`. It stays at the size of the parent window.
For example, you can maximize the Control Gallery app, then create the secondary window, and its content will always be at the size of a maximized window, even if you reduce the size of the window itself (the page's content will be clipped).

I don't know exactly why this happens, but my guess is that it is related to this code:

https://github.com/xamarin/Xamarin.Forms/blob/29b92aa1fc2b9d834bb3b95cc224e07d0cc3e9b4/Xamarin.Forms.Platform.UAP/PageExtensions.cs#L72-L75

My current **workaround** is to update the `SecondaryWindowService`:

https://github.com/xamarin/Xamarin.Forms/blob/29b92aa1fc2b9d834bb3b95cc224e07d0cc3e9b4/Xamarin.Forms.ControlGallery.WindowsUniversal/SecondaryWindowService.cs#L29

Before this line, I added:

```C#
Window.Current.SizeChanged += (sender, args) =>
{
    instance.Layout(new Rectangle(0, 0, args.Size.Width, args.Size.Height));
};
```

With that, the page is resized accordingly.

**Comment by rmarinho** [comment]
Thanks @KPixel , did a PR your recommendations.

**Comment by KPixel** [comment]
Awesome. I will continue the discussion on the PR.
