### ISSUE TITLE
[Bug] Incomplete XAML error

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11711]
I have a huge XAML file with lots of styles and constants.

In one of the styles I had accidentally written this:
```xaml
				<Setter
					Property="HasShadow"
					Value="#False" />
```

The error I got was: "File.xaml: Error: String was not recognized as a valid Boolean. (NameOfProject) XamlC", on the line -1.

I at some point made another error in somewhere there and the error this time was "Error: Object reference not set to an instance of an object (NameOfProject) XamlC", and the line number column was blank. This was caused by me omitting to import an assembly when I moved styles between resource dictionaries.

Goes without saying that this is quite time consuming as it doesn't give the line where the error happens.

Also -- this is probably not related but adding it here for posterity -- when the compilation errors happen, VS also prints tens of old compilation errors I have already fixed, and only restarting VS makes those go away. So it is quite impossible to see exactly what needed to be fixed when the line number is not shown, and you can't even know which error is relevant until VS is restarted. Iirc this was fixed recently so maybe it's a regression?

<img width="1193" alt="Error" src="https://user-images.githubusercontent.com/60286968/89725875-1a65b000-da1d-11ea-994c-1e320e954332.png">
(Project name blanked out)

Thanks.

**Comment by StephaneDelcroix** [comment]
> Also -- this is probably not related but adding it here for posterity -- when the compilation errors happen, VS also prints tens of old compilation errors I have already fixed, and only restarting VS makes those go away. So it is quite impossible to see exactly what needed to be fixed when the line number is not shown, and you can't even know which error is relevant until VS is restarted. Iirc this was fixed recently so maybe it's a regression?

@mgoertz-msft ^^

**Comment by Tommigun1980** [comment]
Oh and I’m using the latest released Xamarin version.

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix I don't think this has anything to do with the language service: Isn't XamlC is a compiler error?
