### ISSUE TITLE
Swipeview Wraped around frame weird behavior when using Material Visuals

### ISSUE THREAD

**Issue by being-yash-t** [xamarin/Xamarin.Forms#11712]
### Description
Weird behavior when use using frame under a swipeview WITH Material Visuals.
[Here are some images](https://drive.google.com/drive/folders/1EcSGJbaFQBdWcjpVGrHG4ykT50NL2Fez?usp=sharing)

### Steps to Reproduce

1. Create a frame
2. Wrap it with a swipe view
3. Run!

### Expected Behavior
Check Image named "expected radius & shadow"

![expected radius   shadow](https://user-images.githubusercontent.com/1235097/89819658-b7226d80-db43-11ea-8465-9a7417c9b4a0.png)

### Actual Behavior
Check Images named 
- Before swiping
- After swiping
- When swiped

### Basic Information

- Version with issue: 4.7
- IDE: VS
- Platform Target Frameworks: 
  - Android: 10

### Screenshots

Before
![Before swiping](https://user-images.githubusercontent.com/1235097/89819661-b7bb0400-db43-11ea-8705-19d36957b467.jpg)

When
![When swiped](https://user-images.githubusercontent.com/1235097/89819656-b5f14080-db43-11ea-82f7-45e07483f967.jpg)

After
![After swiped](https://user-images.githubusercontent.com/1235097/89819666-b8539a80-db43-11ea-9ce0-9216e8f9c75e.jpg)

**Comment by rmarinho** [comment]
![image](https://user-images.githubusercontent.com/1235097/89890690-addce380-dbcb-11ea-81ab-2c74c73cf0b9.png)

I tried to reproduce this issue but wasn't able, can you please provide a small repro with the code for this template.

Thanks

**Comment by being-yash-t** [comment]
Hello @rmarinho 
I just figured it out, I was using material visual in this project and it was applied to everything
```
    <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
                <Setter Property="Visual" Value="Material"/>
    </Style>
```
Note I have ApplyToDerivedTypes as true

So this issue only comes with Material Visuals.
When I set Visual="Default" for the frame, or remove ApplyToDerivedTypes everything is fine.

Got my solution, If you want to close this issue, go ahead or if you guys will commit some changes to 
material visuals lib & want to track progress in here, you can keep updating :)

Thank you. ❤
