### ISSUE TITLE
[Bug] Brushes API - Android's direction is inverted to iOS's

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11715]
iOS:
<img width="85" alt="Screenshot 2020-08-09 at 11 06 24" src="https://user-images.githubusercontent.com/60286968/89729129-59a2f980-da3b-11ea-8c71-de43701437a3.png">

Android:
<img width="96" alt="Screenshot 2020-08-09 at 11 07 43" src="https://user-images.githubusercontent.com/60286968/89729132-66bfe880-da3b-11ea-9334-2c602015ce32.png">

Both use the same brush (Android is lacking a drop shadow due to https://github.com/xamarin/Xamarin.Forms/issues/11714, which is a separate issue):

```xaml
	            <LinearGradientBrush
		            StartPoint="0, 1" EndPoint="1, 0">
		            <GradientStop Color="{StaticResource MyGradientStartColor}" Offset="0.0" />
		            <GradientStop Color="{StaticResource MyGradientEndColor}" Offset="1.0" />
	            </LinearGradientBrush>
```

If the coordinate systems are different between the platforms, could Xamarin mediate them to a common format?

Thanks.

**Comment by jsuarezruiz** [comment]
@Tommigun1980 Could you indicate which View you are using to create the circle? (Frame, BoxView, Shape)

**Comment by Tommigun1980** [comment]
> @Tommigun1980 Could you indicate which View you are using to create the circle? (Frame, BoxView, Shape)

Hi @jsuarezruiz, the filled component is a BoxView.

**Comment by jsuarezruiz** [comment]
I notice that you are using a Frame (for the shadow) and a BoxView reading this issue: https://github.com/xamarin/Xamarin.Forms/issues/11714

**Comment by jsuarezruiz** [comment]
Related with https://github.com/xamarin/Xamarin.Forms/issues/11571
