### ISSUE TITLE
[Bug] CarouselView events are delayed on iOS

### ISSUE THREAD

**Issue by ludas96** [xamarin/Xamarin.Forms#11728]
### Description
When using the CarouselView in order to create a custom TimePicker where the SnapPointsAlignment is set to Center, and SnapPointsType to Mandatory, the selected item is dalyed by one change. 

For example: 
CurrentItem = 16:00
Scroll to 15:00 <- CurrentItem is still 16:00
Scroll to 17:00 <- CurrentItem changes to 15:00
Scroll to 13:00 <- CurrentItem changes to 17:00

This only occurs on iOS.

### Steps to Reproduce

1.  Create a CarouselView with SnapPointsAlignment = Center, SnapPointsType = Mandatory and a few elements.
2.  Scroll to an element
3.  Watch how the current item doesn't change on the actual change.

### Expected Behavior
CurrentItem should be the center item in the list.

### Actual Behavior
CurrentItem is delayed by one scroll.

### Basic Information

- Version with issue:
- Last known good version: ?
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: All

**Comment by rmarinho** [comment]
Hi @ludas96 can you please provide us a simple sample to reproduce the issue. 

Thanks

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
