### ISSUE TITLE
[Bug] XmlnsDefinitionAttribute doesn´t work with[XamlCompilation(XamlCompilationOptions.Compile)]

### ISSUE THREAD

**Issue by ahmedalejo** [xamarin/Xamarin.Forms#11721]
### Description
using the `XmlnsDefinitionAttribute`  fails to compile when `XamlCompilationOptions.Compile` enabled.

The issue is that the attribute has to be defined in the assembly that the controls are defined.
If I have UI libraries like Syncfusion where I have to reference a different namespace for each component.

Since the library doesn´t use the XmlnsDefinitionAttribute I should be able to use `XmlnsDefinitionAttribute.AssemblyName`.
to reference the library.

https://www.syncfusion.com/feedback/7967/shared-namespace-in-xamarin-pacakges

### Steps to Reproduce

1. reference an external library
```csharp
[assembly: XmlnsDefinition(
    xmlNamespace: "http://my.externallibrary.com",
    clrNamespace: "my.externallibrary.components",
    AssemblyName = "my.externallibrary.library.dll")]
```
2. 
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="Openalmz.DonorApp.Features.Donations.NewDonationView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:components="http://my.externallibrary.com">
    <components:View/>
</ContentPage>
```

### Expected Behavior
It should compile without errors

### Actual Behavior
Fails to compile
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0
- Affected Devices:

### Workaround
If possible inherit the component defined in an external assembly and decorated the current assembly with the `XmlnsDefinitionAttribute`

**Comment by StephaneDelcroix** [comment]
we have tests showing that this work. please provide a repro sample

**Comment by ahmedalejo** [comment]
That´s weird. I will try getting a repro until tomorrow.

Meanwhile, do you mind pointing to the test case? that would be very informational.

**Comment by hartez** [comment]
@ahmedalejo What errors are you getting when you try to compile?

**Comment by ahmedalejo** [comment]
Hi, @hartez 

One thing I noticed that wasn't clear was that you had to declare the `XmlnsDefinitionAttribute` in the library containing the controls.
Since the library in which the components I wanted to reference is external and doesn´t use the ´XmlnsDefinitionAttribute´ I thought I should be able to use `XmlnsDefinitionAttribute.AssemblyName`
to reference the library.

I will try to reproduce the error to get the exact message. But it´s basically the usual element not found in the xxx namespace.

**Comment by ahmedalejo** [comment]
Hi, @hartez. I had solved the issue with a workaround and moved forward.

The following seems to work
```csharp
//in: MyCompany.Controls.csproj
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: XmlnsDefinition("http://mycompany.com/schemas/controls", "MyCompany.Controls")]
```
but not the following

```csharp
//in: CustomNamespaceSchemaDemo.csproj
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: XmlnsDefinition(
    "http://mycompany.com/schemas/controls", 
    Na"MyCompany.Controls", 
    AssemblyName: "MyCompany.Controls")]
```

The workaround it to inherit the component and then add an entry of `XmlnsDefinitionAttribute ` in the assembly

**Comment by StephaneDelcroix** [comment]
glad you got something working. AssemblyName require the full AssemblyName, including version, culture, and pub key
