### ISSUE TITLE
[Bug] stringformat error

### ISSUE THREAD

**Issue by Codwy** [xamarin/Xamarin.Forms#11727]
### Description
Using in order to display a double in 2 decimal places only when it different from 0 otherwise remove the floating point and displays as integer.
Note:
Works fine in WPF, despite that intellisense highlights it with the error message:

> Error	XLS0414	The type '' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.

### Steps to Reproduce
1. Use `StringFormat='{}{0:#,0.##}'` in an Entry binded to a double.

### Expected Behavior
The displayed value is formatted as intended. 
### Actual Behavior
- No formatting.
- intellisense highlights it : 
> "expecting ┌" and "The type " was not found verify that you are not missing an assembly reference and that all referenced assemblies have been built".
- No compile or runtime errors, when typing during debugging exception occurred `[0:] Binding: FormatException` without stopping the program.
### Basic Information

- Version with issue: 4.7.0.1260
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages:
  - Xamarin.Essentials 1.5.3.2
  - Xamarin.Forms.Visual.Material 4.7.0.1260

**Comment by StephaneDelcroix** [comment]
I can't reproduce your issue, it even works fine on my test (no runtime log message, no intellisense message). This is the reason why a reproduction projet is requested with a bug report.

As it might be related, make sure to indicate if you're running your app in a non-US locale

**Comment by Codwy** [comment]
The issue was that I was not raising property changed event when values are numerically identical same like 3 and 3.00.
