### ISSUE TITLE
[Bug] Crash: Value cannot be null. Parameter name: descriptor <-- suddenly started crashing without editing code

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11720]
I have been developing my app for months, and today out of the blue the app started crashing on the iOS simulator. I had not changed anything, it just started to happen by itself. The error is:

System.ArgumentNullException:  Value cannot be null. Parameter name: descriptor

Stack trace:

```
  at UIKit.UIFont._FromDescriptor (UIKit.UIFontDescriptor descriptor, System.nfloat pointSize) [0x00003] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.2.2/src/Xamarin.iOS/UIKit/UIFont.g.cs:115 
  at UIKit.UIFont.FromDescriptor (UIKit.UIFontDescriptor descriptor, System.nfloat pointSize) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.20.2.2/src/Xamarin.iOS/UIKit/UIFont.cs:183 
  at Xamarin.Forms.Platform.iOS.FontExtensions._ToNativeFont (System.String family, System.Single size, Xamarin.Forms.FontAttributes attributes) [0x00062] in D:\a\1\s\Xamarin.Forms.Platform.iOS\Extensions\FontExtensions.cs:41
``` 

Happens only on iOS. I had to backtrack almost a month back to find a revision that didn't crash -- even though I have developed this on the same machine. Safe to say is it fails to load some font but that has worked for months.

By binary division of the revisions I was able to find that removing the FontAttributes="Italic" from here fixed it:
```xaml
<Label FontAttributes="Italic" Text="This has started to crash, but has been working until it suddenly stopped" />
```

(The label didn't originally say that, but I simplified it and it still crashes as long as it is using italics).

*But this has been working* - I have seen it running on the screen in the simulator, I have tweaked the layouts, I have also run this on a real device. But out of the sudden I had to remove the italic from a label that I added months back because of the sudden error.

To be clear - All revisions from the last few weeks suddenly started to crash, until I backtracked to that exact line, removed it, and now everything works again.

What could possible cause the simulator to suddenly have trouble with this? I am very very worried right now and lost a lot of time on this -- does anyone have any kind of idea of what could be going on?

Thanks a lot!

**Comment by Tommigun1980** [comment]
Mystery solved! It doesn't actually crash - I had always stopped the simulator assuming it crashed - and the reason it started to suddenly appear is that I had added an exception breakpoint earlier. Apparently it triggers even when outside user code! If I just press continue, then the text renders just fine with italics.

Why would an exception be thrown here when it works just fine? I'll leave this here so you can close it if it's by design, but it is very unexpected that an exception gets thrown when it clearly works just fine.

Thanks.

**Comment by rmarinho** [comment]
Hi @Tommigun1980 i tried to reproduce this issue but i wasn't able. 

[Italic.zip](https://github.com/xamarin/Xamarin.Forms/files/5052115/Italic.zip)

If you can change the sample i used to try to reproduce the issue would be great.

**Comment by Tommigun1980** [comment]
Hi @rmarinho. Please find attached a repro project.

<img width="1270" alt="Screenshot 2020-08-19 at 5 24 19" src="https://user-images.githubusercontent.com/60286968/90584887-4121a480-e1dc-11ea-86ea-48136f4be402.png">

For whatever reason the error is different in the repro project, I didn't dig into it at all, but you still get an error.

Repro steps:
1) Add a new exception catchpoint
2) Run the repro project in iOS simulator

This is what gives the error (please note that both Italic and the font assignment need to be there in order for it to happen):
[Italic.zip](https://github.com/xamarin/Xamarin.Forms/files/5093718/Italic.zip)

**Comment by jsuarezruiz** [comment]
<img width="841" alt="issue-11720" src="https://user-images.githubusercontent.com/6755973/132180841-f89845b7-0b85-41c1-bad2-0068174dd0a6.png">

**Comment by jfversluis** [comment]
I don't think this is a real crash at runtime, just something that happens while debugging. Closing this one, let me know if I misunderstood @Tommigun1980

**Comment by Tommigun1980** [comment]
Hi @jfversluis! Yeah it happens while debugging, but it triggers on exception breakpoint, making it hard to debug an application.
Imho any such exception should be caught internally and not propagate to client code?
