### ISSUE TITLE
[Bug] Labels take too much vertical space with LineBreakMode TailTruncation since Xamarin.Forms 4.8.0

### ISSUE THREAD

**Issue by radioactiveman** [xamarin/Xamarin.Forms#11729]
### Steps to Reproduce

1. Add a label to a collection (`ListView`, `Bindable StackLayout`, ...)
2. Set `LineBreakMode` to `TailTruncation`
3. Set `Text` to a long string which does not fit the screen width

### Expected Behavior
All collection items have the same height. This is the case with Xamarin.Forms until 4.7.0.

### Actual Behavior
Items with too long labels have a heigher height than others. This is a regression in Xamarin.Forms 4.8.0.
It occurs on Android and iOS (UWP not tested).

### Basic Information

- Version with issue: 4.8.0.1269 (latest stable)
- Last known good version: 4.7.0.1260
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS: Default version
  - Android: 9.0

### Screenshots

Xamarin.Forms 4.7.0 (same heights):

![Xamarin-Forms-4 7 0](https://user-images.githubusercontent.com/1301412/89779167-144ffc00-db0f-11ea-85f6-a6c8d786201c.png)

Xamarin.Forms 4.8.0 (different height for second item, causing greater gaps):
![Xamarin-Forms-4 8 0](https://user-images.githubusercontent.com/1301412/89779186-1ade7380-db0f-11ea-8aef-94efb8d7bb97.png)

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/5050591/App1.zip)

**Comment by cmpalmer66** [comment]
I'm not sure if it's related, but I've also seen a bug I'm trying to isolate where, if the label contains nothing but an acronym or a camel-cased word, the word wrapping can get confused and allocate too much vertical space to contain it. In our application, a label such as "MixedCaseWord" or "MAOP" will result in extra vertical space, whereas "Mixed Case Word" or "M A O P" will not.

**Comment by Tommigun1980** [comment]
Hi @cmpalmer66 - could you please check https://github.com/xamarin/Xamarin.Forms/issues/11713 whether that is the bug you are describing? If it is, I don't think it has to do with actual word content, but rather that different text content on different screens would get a line break in different places, and some of them just happen to hit the 'sweet spot' for this bug to appear. Hence I think it is impossible to find something that works on all devices until this gets fixed, in case it is indeed the same issue.

**Comment by cmpalmer66** [comment]
> Hi @cmpalmer66 - could you please check #11713 whether that is the bug you are describing? If it is, I don't think it has to do with actual word content, but rather that different text content on different screens would get a line break in different places, and some of them just happen to hit the 'sweet spot' for this bug to appear. Hence I think it is impossible to find something that works on all devices until this gets fixed, in case it is indeed the same issue.

I think it might be related, but in my case, I'm specifically seeing a problem with WordWrap turned on and short words/text that doesn't wrap. For example, a short string like "The caption" doesn't grab any extra vertical space, but one with an acronym, like "MAOP" is also not wrapping, but has extra space below the label. I need to figure out a demo repo and maybe post it as a separate issue - I'm just guessing that it's related to this issue or #11713.

**Comment by radioactiveman** [comment]
This is probably related to https://github.com/xamarin/Xamarin.Forms/pull/11903. But since there is no new Xamarin.Forms version available yet, I am not able to verify this for now.

**Comment by radioactiveman** [comment]
Closing since this is indeed related to https://github.com/xamarin/Xamarin.Forms/pull/11903 and fixed with Xamarin.Forms 4.8.0.1364.
