### ISSUE TITLE
[Bug] iOS app crashed with Runtime.ThrowNSException (System.IntPtr ns_exception)

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/Xamarin.Forms#11726]
### Description
Our recently released version of iOS app (using Xamarin.Forms) got a crash which seems like something related with a bug of Layout.

The key message for the exception:
SIGABRT: Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread. 

### Steps to Reproduce

1.  N/A (unknown)
2. 
3. 

### Basic Information
Below is the full Stack traces:
Runtime.ThrowNSException (System.IntPtr ns_exception)
Runtime.throw_ns_exception (System.IntPtr exc)
(wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr)
UIView.LayoutSubviews ()
VisualElementRenderer`1[TElement].LayoutSubviews ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr)
CATransaction.Commit ()
CADisplayLinkTicker.StartThread ()
ThreadHelper.ThreadStart_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
ThreadHelper.ThreadStart ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr)
UIView.LayoutSubviews ()
VisualElementRenderer`1[TElement].LayoutSubviews ()
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr)
CATransaction.Commit ()
CADisplayLinkTicker.StartThread ()
ThreadHelper.ThreadStart_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
ThreadHelper.ThreadStart ()

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.5.1
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.6.0.847
- Affected Devices: iPhone XR/iPhone 7 (iOS 13.5.1)

**Comment by rmarinho** [comment]
Hi, thanks for your report but just looking to the stack trace we aren't able to find the source of the issue. Can you upload a simple repro project so we can look at it .

Thanks

**Comment by KevinHu-au** [comment]
Hi @rmarinho, thank you for the responses. As I have no ideas about which page/control cause these exception, I don't know how can I have a simple repo to reproduce the exception.

**Comment by PureWeen** [comment]
> SIGABRT: Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

sounds like you are modifying your layout from a background thread..

Do you have any timers or network calls?

**Comment by KevinHu-au** [comment]
@PureWeen. I do have a timer to draw something on SKCanvasView to show the progress of a user's action. But it is happening on UI thread.

        private void StartRunning()
        {
            sweepAngle = 0.0f;
            progressObs = Observable
                .Interval(TimeSpan.FromMilliseconds(progressInterval))
                .SubOnMainThread(_ => OnProgress());
        }

        private void OnProgress()
        {
            //10,000: means 10 secs will go a complete round.
            sweepAngle += (float)(progressInterval * 360) / 10000;
            if (sweepAngle > 360.0f)
                sweepAngle = 0.0f;

            canvasView.InvalidateSurface();
        }

And the SubOnMainThread is an extension method as below:
        public static IDisposable SubOnMainThread<T>(this IObservable<T> obs, Action<T> onNext)
            => obs
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(onNext);

**Comment by rmarinho** [comment]
So this is more related with Skia and ReactiveUI?

**Comment by KevinHu-au** [comment]
@rmarinho. I am not sure about it. I cannot reproduce the issue from my end, so I cannot 100% sure if it was coming from the page/view

**Comment by KevinHu-au** [comment]
BTW, untill now, only iOS has this issue (happened 4 times since the release last week). Android app is fine so far.

**Comment by jsuarezruiz** [comment]
@KevinHu-au The only `Timer` you use is in the previous code?. Maybe a collection is updated in different threads, etc?

Could you share the logs of the related exceptions that you have had? For example, an attached zip.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by softsan** [comment]
@KevinHu-au  I have the same issue in our appstore app and hard to reproduce. Were you able to find out the root cause?

**Comment by ryanlpoconnell** [comment]
We are also having the issue reported from published Apps out in the wild.  We are unable to reproduce internally.  

A user reporting this has it happen consistently on App launches (following the initial App launch?).
Visually it doesn't get past the launch screen storyboard... but I see the following in the stack.

...```
at CoreAnimation.CATransaction.Commit () <0x102089ac0 + 0x00027> in <16c89537d3e84c9193e31188658ef0ac#e6cde8d498a7dd8981d5fe79bf6544ac>:0
  at Xamarin.Forms.Platform.iOS.CADisplayLinkTicker.StartThread () <0x10240dbb0 + 0x000a3> in <7cbae75e123c467eb27876e5c72d7719#e6cde8d498a7dd8981d5fe79bf6544ac>:0
```
 The odd thing is we have thousands of users that this is not happening to and yet, it seems consistent for a handful of users.

The handful of users are spread across different devices and iOS versions.

Any thoughts?

**Comment by DanielGlick45** [comment]
Any chance we can reopen this issue? We are getting reports on AppCenter of this as well. It seems like the app is put in the background for a long time and the crash happens when returning to the app. All the logs say the app crashes after 7+ hours of up time
