### ISSUE TITLE
[Bug] [iOS] ContentPage in NavigationStack misplaced initially

### ISSUE THREAD

**Issue by planerde** [xamarin/Xamarin.Forms#11723]
### Description
ContentPage in NavigationStack misplaced initially

### Steps to Reproduce

1. Create a new solution from the template 'Shell-Forms App'. This will create a Shell App with Xamarin.Forms 4.6.0.1141 as dependency
2. Start the app in the iOS simulator (I tried 13.6, 13.0 and 12.0), navigate to the "Browse" tab and tap one of the listed entries. This results in a navigation to the ItemDetailPage with correct layout.
3. Upgrade to Xamarin.Forms 4.7 or 4.8 (I tried both) - the iOS and Forms project.
4. Repeater step 2: this time the ItemDetailPage is misplaced under the navigation bar and moved done after a few milliseconds.

### Expected Behavior
The expected behavior is the correct navigation to the subpage as with Xamarin.Forms 4.6

### Actual Behavior
Misplaced ContentPage content for a short time.

### Basic Information

- Version with issue: Xamarin.Forms 4.7 and 4.8
- Last known good version: 4.6.0.11.41
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.0, 13.0, 13.6
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: iOS Simulator

#### Expected Behavior
![Simulator Screen Shot - iPhone 11 - 2020-08-09 at 22 10 26](https://user-images.githubusercontent.com/513312/89740907-59334e80-da8d-11ea-984a-fdc91f146de3.png)

#### Actual Behavior
![Simulator Screen Shot - iPhone 11 - 2020-08-09 at 22 10 42](https://user-images.githubusercontent.com/513312/89740910-5c2e3f00-da8d-11ea-9540-6596a9e861a8.png)

### Workaround

I didn't find a work-a-round for this. In the end I had to downgrade to Xamarin.Forms 4.6.

**Comment by rmarinho** [comment]
yap can confirm moving from 4.6.0 to 4.7.0 i see the issue..

**Comment by PureWeen** [comment]
closed by #11791
