### ISSUE TITLE
Display Alert Not Close when you change Application Current main page

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11739]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1134985/display-alert-not-close-when-you-change-applicatio.html)._

---
<p>bool answer = await DisplayAlert(&quot;Alert&quot;, &quot;Aks Question?&quot;, &quot;Yes&quot;, &quot;No&quot;);
            if (answer)
            {
                
Application.Current.MainPage = new ChooseOptionsPage(lblRepId.Text, _model);
            }
            else
            {
                Application.Current.MainPage = new CustomNavigationView(new MainMenuView());
            }</p><p class="">//</p><p class="">Display Alert Not Closed !!!</p>
</p>

---
#### Mila Zhou [MSFT] on 8/4/2020, 02:58 AM: 

<p>Thank you for your feedback! for us to investigate this further, could you please provide a sample solution that has this problem or some screenshots and more description so that we can conduct further research?</p>
<p>We look forward to hearing from you!</p>

#### Ali Khalaj on 8/9/2020, 10:34 AM: 

<p>Hi Dear Mr Zhou</p><p>i solve it with Rg Plugin Popup and replace it with Display Alert ! and when Navigate to another page disappear it.</p><p>but i suggest add a trigger between navigation page to detect any open Display Alert and if Display Alert has Yes Or No buttons don't allow user to navigate page and if does not has any button disappear it.</p><p>i see this problem when programming a application for customers kiosk ! we see some customers to forget click on exit button and i set a Task.Delay() for 30 seconds if user does not exit automatically navigate to login page, but i saw that display alert not exit and stay on page !</p><p>so i decide to user Rg Plugin Popup but if Microsoft solve this problem i prefer use Display Alert.</p><p>Thank you so much</p>

#### Feedback Bot on 8/9/2020, 07:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rmarinho** [comment]
I trying to reproduce this issue but i wasn't able too. I tried this page on iOS and Android. and after the Display is always closed.

```
public class Newpage : ContentPage
{
	public Newpage()
	{
		var btn = new Button { Text = "Show Alert" };

		btn.Clicked += async (s, e) =>
		{
			bool answer = await DisplayAlert("Alert", "Aks Question?", "Yes", "No");
			if (answer)
			{
				Application.Current.MainPage = new ContentPage();
			}
			else
			{
				Application.Current.MainPage = new ContentPage();
			}
		};
		Content = btn;
	}
}
```

**Comment by AliKhalaj7** [comment]
Yes, when you set Task.Delay() on your page and navigate user to another page DisplayAlert not closed ! but user navigate to another page, i think Microsoft team have to close all alerts if page changed.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
