### ISSUE TITLE
[Bug] UWP CollectionView not displaying content, or including incorrect content

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#11732]
### Description
I've just moved from VS 16.7 preview to the final version, and update my project from forms 4.7 to 4.8.
The CollectionView on UWP is showing a number of issues - probably related to this change:
> - GitHub #9051 - "[Bug] View recycling in CollectionView does not work on UWP" (#11043) 

examples of issues I've seen:
- On app launch, the screen may show a blank space instead of the collectionview or the emptyview.
  - Resizing the app window will then render the content.
  - Removing the EmptyView template seems to avoid this issue.
- CollectionView might show items with content that belongs to different items.
  - My list is grouped and I have 4 different datatemplates.
  - My items have static content that gets updated when BindingContextChanged fires.
  - My items show the wrong datatemplate when this happens, and the content belonging to a different item.
  - If I have a long list of items of different templates, the number of incorrect items is very large.

Sorry in advance - this is not something I'm able to put into a reproduction project just yet, but maybe others have had similar issues and we can try to understand what the issue might be?

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: ?
- IDE: 16.7.0
- Platform Target Frameworks: 
  - UWP:  19041
- Android Support Library Version:

**Comment by rmarinho** [comment]
I uploaded  a simple sample can you change it a little bit to try recreate your issue, as i have it it seems to work. Grouping and EmptyView.

[App9.zip](https://github.com/xamarin/Xamarin.Forms/files/5051646/App9.zip)

**Comment by MitchBomcanhao** [comment]
@rmarinho 
thanks for the small sample, I've tried to adapt it and I think I've got something similar happening.
see repo in https://github.com/MitchBomcanhao/App9 

I've added a data template selector for the collectionview item template.
I've extended the animal class to have a category just to have something easy to pick from when running the data template selector.

It should get a collection item, check if it is a Bear, Dog, Cat, Monkey or Elephant, and provide the relevant data template.
Each template has its own color which makes it easier to spot when things have gone wrong.

this is the view when I finish loading the app
![image](https://user-images.githubusercontent.com/31066938/89809233-30659480-db33-11ea-9f02-245f82405202.png)

When I start scrolling two things happen:
- items start getting the wrong templates as evidenced by the wrong colors being used
- the datatemplateselector starts having trouble because sometimes the item presented to it is NOT an animal, but a list of animals (?). I've put a debugger break for when this happens.
- note that there are footers getting mixed into the middle of the items somehow (?)

![image](https://user-images.githubusercontent.com/31066938/89809373-5e4ad900-db33-11ea-83cd-c9740037e12f.png)

**Comment by MitchBomcanhao** [comment]
If I downgrade the sample app to Xamarin Forms 4.7 the template issues are gone but the group footer issue is still present. 
I don't use the group footer on my own app so I had not noticed it.

**Comment by rmarinho** [comment]
Thanks @MitchBomcanhao

**Comment by cmpalmer66** [comment]
I'm seeing this as well - wrong templates being picked, wrong attributes being bound to the templates, bound values not showing - completely broke our app on UWP, so I had to roll Xamarin.Forms back to 4.7.0.1260.

**Comment by DuncWatts** [comment]
Is there a workaround for the issue of incorrect DataTemplates being selected from the DataTemplateSelector? 

I'm having to completely disable CollectionView on my UWP builds due to this.

**Comment by activa** [comment]
I can confirm that CollectionView on UWP is completely broken since 4.8. For example, when setting a Footer view on a CollectionView, the whole page doesn't render at all until the window is resized (which forces a layout cycle)

**Comment by crackerland** [comment]
Same here. We started seeing this when we upgraded to v5. I can repro this with the simplest implementation - just a flat list without any headers or grouping or anything, and just different colored labels in the DataTemplates.

**Comment by crackerland** [comment]
Here's my very basic repro to show the wrong views being selected from the DataTemplateSelector (the second issue mentioned initially)
[CollectionView_DataTemplateSelector_Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/6064018/CollectionView_DataTemplateSelector_Bug.zip)

**Comment by velocitysystems** [comment]
Same findings as @crackerland and @activa, `CollectionView` really took a dive downward on UWP and needs some urgent bug fixes to resolve these regressions. Can this be prioritised for the next service release of XF 5?

cc: @samhouts @davidortinau

**Comment by velocitysystems** [comment]
@rmarinho Although this is tagged as 4.7, I can confirm this affects the latest version of XF 5.
