### ISSUE TITLE
MarkupExtension not found for AppThemeBinding

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11740]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1140127/markupextension-not-found-for-appthemebinding.html)._

---
I’m trying to perform this demo: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes#appthemebinding-markup-extension

It’s not working.

I noticed after a HMR I get an error.  Why don’t I get that error on the front side?

---
#### Feedback Bot on 8/7/2020, 00:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
what version of XF are you using ?

what do you get ? build time or runtime error ? could you share your sample project ?

**Comment by spottedmahn** [comment]
Hi @StephaneDelcroix 

>what version of XF are you using ?
4.7

>what do you get ? build time or runtime error ?
runtime error after making a change in HMR kicks in

>could you share your sample project ?
I don't but if I can try.  Let's close the issue for now and if I can repro it in a sample project I'll reopen it.  Thanks
