### ISSUE TITLE
[Bug] Android Entry and Picker still let flow direction based on language but not current settings!

### ISSUE THREAD

**Issue by huangjinshe** [xamarin/Xamarin.Forms#11744]
### Description

Android will auto changing the text layout direction based on the current language. If the language direction is RTL, it still show the text from right to left(also the layout will based on that).

### Steps to Reproduce

1. Go to download  [Oybab Trading System](https://github.com/oybab/TradingSystem).
2. Open and Run Android project.
3. Go to "Setting" on the Login page, Change the language to the RTL language.
4. Test the picker which use for change language.(modify the code of picker : `FlowDirection` and `HorizontalOptions`)
5. Return to login page, remove the Admin No Entry, check place holder flow direction.

### Expected Behavior
1.For place holder of Entry, If when we setting the Flow direction to : LTR or default the text should be write from left to right.
2.For picker, FillAndExpand should be let the picker fill in the line , also the content should be write to left to right.
3.For picker, CenterAndExpand should be Expand to current line, but didn't.
### Actual Behavior
1.For place holder of Entry, If when we setting the Flow direction to : LTR or default: the text still from right to left(because of language direction is RTL, but not setting anything for it)
2.For picker, FillAndExpand : display like RTL
3.For picker, CenterAndExpand did not expand the picker.
### Basic Information

- Version with issue:v4.8
- Last known good version:-
- IDE:Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 10

### Screenshots

![001](https://user-images.githubusercontent.com/3822799/89857439-a9fe9080-dbce-11ea-9694-a393552f7264.png)
![002](https://user-images.githubusercontent.com/3822799/89857441-ac60ea80-dbce-11ea-80a1-3bf2dcfc3d97.png)

### Reproduction Link

If you guys need a project support multiple languages and which include language direction LTR and RTL for test, use this: [Oybab Trading System](https://github.com/oybab/TradingSystem)

**Comment by rmarinho** [comment]
Sorry i couldn't run the sample ...

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023: System.IO.DirectoryNotFoundException: Could not find a part of the path 'Y:\NET\TradingSystemX\obj\TradingSystemX.Droid\Debug\90\res\layout\tabbar.xml'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at System.IO.File.Delete(String path)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at Xamarin.Android.Tools.Files.CopyIfChanged(String source, String destination)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at Xamarin.Android.Tasks.CopyIfChanged.RunTask()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1084,2): error XACIC7023:    at Xamarin.Android.Tasks.AndroidTask.Execute()
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

Can you provide a smaller sample? Also the `AndExpand`is for use on the Stacklayout

**Comment by huangjinshe** [comment]
@rmarinho , please before you use [Oybab Trading System](https://github.com/oybab/TradingSystem), read the [Read me](https://github.com/oybab/TradingSystem/blob/master/README.md) file, especially the steps about `Developer`  step No.2:

> For developing more fast, the project setting all bin or obj files created on the Position: Y:(Disk Name) . So you need to download a Ramdisk tools, create a new partition Y:\ . If you don't want to do that it's fine, but you should remove items like: `<BaseIntermediateOutputPath>`, `<OutputPath>`, `<IntermediateOutputPath>` from every .csproj files or Directory.Build.props files under the project.

**Comment by memu8** [comment]
In the Android manifest file, do you have android:supportsRtl set to true?

**Comment by huangjinshe** [comment]
@memu8 , I remember I tried it before few months ago. Remember, currently problem is Android layout automatically display : Right to left.(because the current using language write rule is Right to left).

I hope you could try that project, because it has 3 language, 2 is LTR, 1 is RTL, you could see the problem clearly  .

**Comment by memu8** [comment]
What minimum API are you targeting? If it's after API 17, then in your Android manifest file (https://github.com/oybab/TradingSystem/blob/master/TradingSystemX/TradingSystemX/TradingSystemX.Android/Properties/AndroidManifest.xml) you can set "android:supportsRtl" to true and the issue with entries and pickers should be resolved.

**Comment by huangjinshe** [comment]
@memu8 , Thanks, It worked now.  But `HorizontalOptions="StartAndExpand"` and `HorizontalOptions="CenterAndExpand"` all can't expand the pickers. only `HorizontalOptions="FillAndExpand"` worked.  Is that normal?

**Comment by jsuarezruiz** [comment]
Glad to read that you fixed the issue with RTL. About the different values to align content, do you use them with a Picker?

**Comment by huangjinshe** [comment]
@jsuarezruiz , After I enabled "android:supportsRtl", the Picker can now display on the left side. even the content language is from RTL. so problem solved.  About the Picker Expand not working problem, I will open another Bug report. This can close now.
