### ISSUE TITLE
[Enhancement] Provide Opacity property for brushes

### ISSUE THREAD

**Issue by DoubleDBE** [xamarin/Xamarin.Forms#11745]
In our WPF application we're using gradients with their opacity property set to lower values than 1.

It would be great if we'd have this feature in XF so we can easily port it.

E.g.
```
<LinearGradientBrush StartPoint="0,0" EndPoint="0,0.5" Opacity="0.2">
    <GradientStop Color="White"/>
    <GradientStop Color="#7F6D6A69" Offset="1"/>
</LinearGradientBrush>
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
