### ISSUE TITLE
[Bug] [UWP] ScrollView: Programmatic ScrollTo Change Is No Change On Screen

### ISSUE THREAD

**Issue by OneVideo** [xamarin/Xamarin.Forms#11743]
### Steps to Reproduce

1. Download current production Sample project --> https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-carouselviewdemos/
2. Add a UWP startup project.  Build and launch
3. Test, verify, report
    3a. From the "Scrolling" Group, select "Scroll by index" 
       3a0.  Click Button labelled "SCROLL TO ITEM 6"
       3a1. Observe no change in display of "Baboon"

    3b. From the "Scrolling" Group, select "Scroll by object" 
       3b0.  Click Button labelled "SCROLL TO PROBOSCIS MONKEY"
       3b1. Observe no change in display of "Baboon"

### Expected Behavior
It works as documented
### Actual Behavior
It does not work
### Basic Information

- Version with issue:  Current samples release.  Problem also exists on Xamarin.Forms v4.8.0.1269
- Last known good version: none
- IDE:  Visual Studio 2019 version 16.6.0
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  Target=1903 (18362); Minimum=1809 (17763); Runtime= Windows 10 Pro 1903 Build 18362.959 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
[XFCarouselView.zip](https://github.com/xamarin/Xamarin.Forms/files/5057903/XFCarouselView.zip)

**Comment by rmarinho** [comment]
This one is fixed on the last 4.8.0.1687 and 5.0.0-pre4

**Comment by HendrikDeu** [comment]
> This one is fixed on the last 4.8.0.1687 and 5.0.0-pre4

@rmarinho Thanks for the information. However, this bug ID does not show up in both releases changelog:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.8/4.8.0-sr5
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-pre4
