### ISSUE TITLE
PageRenderer's OnKeyPressEvent ignores A-Z, 0-9 keys on GTK [Bug] 

### ISSUE THREAD

**Issue by Nekliukov** [xamarin/Xamarin.Forms#11756]
### Description
It is unable to catch keys pressing by OnKeyPressEvent on GTK.
Other platforms (WPF, Android) do it successfully.

### Steps to Reproduce

1. Override OnKeyPressEvent in your class derived from PageRenderer
2. Focus any Entry on the page which uses PageRenderer described above
3. Press any non-functional key on the keyboard

### Expected Behavior
Step into OnKeyPressEvent

### Actual Behavior
Ignore OnKeyPressEvent

### Basic Information
The bug does not reproduce with keys such as Ctrl, Shift, Tab, Alt.
Page renderer:

```
using Gdk;
using Project.Linux.CustomRenderers;
using Project.SharedForms.Pages;
using Xamarin.Forms;
using Xamarin.Forms.Platform.GTK.Renderers;

[assembly: ExportRenderer(typeof(SalesPage), typeof(SalesPageRenderer))]
namespace Project.Linux.CustomRenderers
{
  public class SalesPageRenderer: PageRenderer
  {
    protected override bool OnKeyPressEvent(EventKey evnt)
    {
      // Handle pressed key

      return true;
    }
  }
}
```

### Screenshots
Affected versions:
![image](https://user-images.githubusercontent.com/30673836/89965340-410e2b80-dc55-11ea-99f2-f54cab246bb1.png)

**Comment by rmarinho** [comment]
Hi @Nekliukov do you mind upload a small repro project so it can help us reproduce. Is this on Windows or macOS ?

**Comment by Nekliukov** [comment]
Hi, @rmarinho. It' Windows

**Comment by rmarinho** [comment]
```
public class SalesPage : ContentPage
{
	public SalesPage()
	{
		var layout = new StackLayout();
		layout.Children.Add(new Entry { Text = "the entry" });

		layout.Children.Add(new Button { Text = "the btn", BackgroundColor = Color.Red });

		Content = layout;
	}
}

	public class SalesPageRenderer : PageRenderer
	{
		protected override bool OnKeyPressEvent(Gdk.EventKey evnt)
		{
			// Handle pressed key

			return true;
		}
	}
```

So i m not sure this is a bug , sinc the entry gets the keypresses, if you don't have the entry with focus it seems to work fine. 

@jsuarezruiz what's your opinion?

**Comment by rmarinho** [comment]
Ok after some testing i can see that iOS and UWP the events bubble up to the PageRenderer, but for example on ANdroid they dont.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
