### ISSUE TITLE
[Enhancement] Where is my XamlParseException?

### ISSUE THREAD

**Issue by spottedmahn** [xamarin/Xamarin.Forms#11767]
## Summary
When I get a `XamlParseException` it doesn't tell me where, which file is the parse exception on??

![image](https://user-images.githubusercontent.com/14079228/90047765-75f3a000-dca0-11ea-9ca0-9cdefc8cfda0.png)

## API Changes
Include the filename that has the parse exception

## Intended Use Case
Quickly find my problems

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
