### ISSUE TITLE
ios:Page.UseSafeArea="true" makes the content of a page jumping on appearing XF 4.8 [Bug] [IOs] [Shell]

### ISSUE THREAD

**Issue by Sasha111ua** [xamarin/Xamarin.Forms#11777]
### Description
If you use ios:Page.UseSafeArea="true" on a page then content jumps from unsafe area to safe area after page appeared. You basically can see that. On 4.7. works fine.

### Steps to Reproduce

1.  Run project
2. Click on any item of the list
3. When ItemsDeails page appears you see like adjusting of the content layout is happening (jumping effect).

### Expected Behavior
The page appears with content inside safe area

### Actual Behavior
Layout adjustment happens after the page appeared.

### Basic Information

- Version with issue: 4.8.0.12.69
- Last known good version: 4.7.0.968
- IDE:
- Platform Target Frameworks: 
  - iOS: 
- Affected Devices: simulator and device

### Reproduction Link

https://drive.google.com/file/d/1gCgWQ6oAi09EdAkxJk22a_kvnazqU94W/view?usp=sharing

**Comment by rmarinho** [comment]
This is similar to #11723 it seems.

**Comment by Tommigun1980** [comment]
I noticed earlier that reading the safe area rectangle only works in OnAppearing (and not in the constructor as the documents say). I filed a documentation bug report, but maybe the functionality itself has changed in 4.8 and it was accessible in the constructor earlier? That would explain the flipping people see and why some plugins I am using are broken regarding the safe area.

**Comment by rscholey** [comment]
How is it possible the Xamarin team missed something as obvious as this :-(  Makes me feel like it is the users who are the testers and they just release code and hope for the best.   I hope that things can improve but based on the last few years I think it will always be the same.  Poor quality control of new releases and hundreds of unfixed bugs while the devs try to add more and more new features.

**Comment by samhouts** [comment]
closed by #11791
