### ISSUE TITLE
[Bug] Issue loading images

### ISSUE THREAD

**Issue by silasas** [xamarin/Xamarin.Forms#11778]
### Description

I am in trouble to load images.
Some images work, but others not.

I think is firewall or other thing in the remote server. it is blocking the connection...

### Steps to Reproduce

        private List<ProdutoViewModel> produtoViewModels = new List<ProdutoViewModel>
        {
                     new ProdutoViewModel {Nome="Curso de word", UrlImagem= Teste() }

        };

        public static UriImageSource Teste()
        {
            var source = new UriImageSource
            {
                Uri = new Uri("http://www.macoratti.net/Imagens/pessoas/house1.jpg"),
                CachingEnabled = false
            };

            return source;
        }

### Expected Behavior

Load Image

### Actual Behavior

Doesn't load Image

### Basic Information

- Version with issue:

Microsoft Visual Studio Community 2019
Version 16.7.1

Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

### Screenshots

java.io.IOException: Cleartext HTTP traffic to www.macoratti.net not permitted
	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
08-13 22:42:13.059 I/OpenGLRenderer(22772): Davey! duration=978ms; Flags=0, IntendedVsync=13067153224777, Vsync=13067903224747, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=13067915997400, AnimationStart=13067916046000, PerformTraversalsStart=13067916470800, DrawStart=13067918856000, SyncQueued=13067987799800, SyncStart=13068046617600, IssueDrawCommandsStart=13068049853200, SwapBuffers=13068098892000, FrameCompleted=13068191012300, DequeueBufferDuration=340000, QueueBufferDuration=544000, 
[0:] ImageLoaderSourceHandler: Could not retrieve image or image data was invalid: Uri: http://www.macoratti.net/Imagens/pessoas/house1.jpg
[HotReload] (2020-08-13 22:42:11.9): INFO: (LearningApp.Android) (HotReloadAgent) HotReload: Initialized Agent.
[HotReload] (2020-08-13 19:42:16.6): INFO: XAML Hot Reload Connected and Ready.

**Comment by rmarinho** [comment]
Can you upload a small repro please.

Thanks

**Comment by silasas** [comment]
Follow the project to download:

 

https://drive.google.com/file/d/12Oxga1t4CpamKz9kvKWYp7NWEP7HYCbw/view?usp=sharing

 

 

Notice:

 

Url’s are in the DataService.cs

 

------------------------

 

private List<ProdutoViewModel> produtoViewModels = new List<ProdutoViewModel>

        {

            //don't working

            //new ProdutoViewModel {Nome="Técnicas de parcial blonde", UrlImagem="https://www.stelin.azurewebsites.net/assets/imagens/cursoPopular/2020/6/20/blonde.jpg"},

            //new ProdutoViewModel {Nome="Curso de finanças", UrlImagem="https://www.stelin.azurewebsites.net/assets/imagens/cursoPopular/2020/6/20/Financas.jpg"},

            //new ProdutoViewModel {Nome="Curso de VBA", UrlImagem="https://www.stelin.azurewebsites.net/assets/imagens/cursoPopular/2020/6/22/vba.png"},

            //new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://www.stelin.azurewebsites.net/assets/imagens/cursoPopular/2020/6/23/cp-575bcfac-f24c-495f-aa47-55aaf10f59ea-2020623-18-02-502841.jpg"}

 

            //working

            new ProdutoViewModel {Nome="Técnicas de parcial blonde", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/11/15971442475f327cb7449f9_1597144247_3x2_xs.jpg"},

            new ProdutoViewModel {Nome="Curso de finanças", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/12/15972614355f34467bdc31f_1597261435_3x2_xs.jpg"},

            new ProdutoViewModel {Nome="Curso de VBA", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/11/15971795205f33068050991_1597179520_3x2_xs.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem= "https://f.i.uol.com.br/fotografia/2020/08/13/15973505355f35a28743c4c_1597350535_3x2_md.jpg" },

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/05/15966585115f2b134f91a52_1596658511_3x2_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/13/15973607295f35ca5944233_1597360729_3x2_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/13/15973429215f3584c918857_1597342921_3x2_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/13/15973508005f35a390717c3_1597350800_3x2_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/07/24/15956173685f1b3058d3f13_1595617368_5x2_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/08/13/15973316995f3558f3aca4c_1597331699_3x4_md.jpg"},

            new ProdutoViewModel {Nome="Curso de word", UrlImagem="https://f.i.uol.com.br/fotografia/2020/07/30/15961180845f22d4443523d_1596118084_3x2_md.jpg"}

        };

 

 

Best Regards,

Silas

 

 

De: Rui Marinho [mailto:notifications@github.com] 
Enviada em: sexta-feira, 14 de agosto de 2020 07:25
Para: xamarin/Xamarin.Forms
Cc: silasas; Author
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] (#11778)

 

Can you upload a small repro please.

Thanks

**Comment by jsuarezruiz** [comment]
Thanks for the reproduction sample. I have done some test in your sample, but have not found issues loading the images:
<img width="505" alt="Captura de pantalla 2020-08-25 a las 13 04 05" src="https://user-images.githubusercontent.com/6755973/91167700-b279bf80-e6d4-11ea-8f9c-3a396bab4038.png">

Also, I have created a small sample using the image from the previous logs http://www.macoratti.net/Imagens/pessoas/house1.jpg

[Issue11778.zip](https://github.com/xamarin/Xamarin.Forms/files/5123361/Issue11778.zip)

And works without problems:
<img width="505" alt="Captura de pantalla 2020-08-25 a las 13 08 33" src="https://user-images.githubusercontent.com/6755973/91167537-69297000-e6d4-11ea-8b3d-5431e578d6e1.png">

Could you share logs using LogCat?, do you use any special configuration in the manifest related to `networkSecurityConfig`, etc?

**Comment by silasas** [comment]
Ok. Suárez.

I’ll try and I’ll speak to you the result.

 

Thanks for now.

Silas.

 

De: Javier Suárez [mailto:notifications@github.com] 
Enviada em: terça-feira, 25 de agosto de 2020 08:17
Para: xamarin/Xamarin.Forms
Cc: silasas; Author
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Issue loading images (#11778)

 

Thanks for the reproduction sample. I have done some test in your sample, but have not found issues loading the images:
 <https://user-images.githubusercontent.com/6755973/91167700-b279bf80-e6d4-11ea-8f9c-3a396bab4038.png> Captura de pantalla 2020-08-25 a las 13 04 05

Also, I have created a small sample using the image from the previous logs http://www.macoratti.net/Imagens/pessoas/house1.jpg

Issue11778.zip <https://github.com/xamarin/Xamarin.Forms/files/5123361/Issue11778.zip> 

And works without problems:
 <https://user-images.githubusercontent.com/6755973/91167537-69297000-e6d4-11ea-8b3d-5431e578d6e1.png> Captura de pantalla 2020-08-25 a las 13 08 33

Could you share logs using LogCat?, do you use any special configuration in the manifest related to networkSecurityConfig, etc?

**Comment by silasas** [comment]
Hi my friend,

 

In my computer, is not working, including this uri: http://www.macoratti.net/Imagens/pessoas/house1.jpg the same project I sent to you.

Try these uri’s:

 

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/25/cp-8e598974-8d4c-42c7-a0a3-731485eaabe1-2020825-19-20-333098.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-cb9b059b-1e31-49a0-b498-c62a046eb8fb-2020826-18-36-057025.jpg"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-8249734c-6b2b-42ae-b608-a1db9b070d45-2020826-18-42-079629.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-4db0717c-484b-466e-9c48-c6f408b33b99-2020826-18-46-297196.jpg"

 

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-da798339-5544-47e2-b795-2bcd1438048d-2020826-18-51-325262.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-76536911-4afb-486f-a6ed-ba4ac41b1dbf-2020826-18-55-354445.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-fcbfed83-31b9-47cc-bc45-08e4cfa23ab4-2020826-18-59-083260.png"

http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-f0f1e0a1-99cb-4f70-b656-9568f3f4b687-2020826-19-02-174935.png"

 

 

See output window:

 

 



 

De: Javier Suárez [mailto:notifications@github.com] 
Enviada em: terça-feira, 25 de agosto de 2020 08:17
Para: xamarin/Xamarin.Forms
Cc: silasas; Author
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Issue loading images (#11778)

 

Thanks for the reproduction sample. I have done some test in your sample, but have not found issues loading the images:
 <https://user-images.githubusercontent.com/6755973/91167700-b279bf80-e6d4-11ea-8f9c-3a396bab4038.png> Captura de pantalla 2020-08-25 a las 13 04 05

Also, I have created a small sample using the image from the previous logs http://www.macoratti.net/Imagens/pessoas/house1.jpg

Issue11778.zip <https://github.com/xamarin/Xamarin.Forms/files/5123361/Issue11778.zip> 

And works without problems:
 <https://user-images.githubusercontent.com/6755973/91167537-69297000-e6d4-11ea-8b3d-5431e578d6e1.png> Captura de pantalla 2020-08-25 a las 13 08 33

Could you share logs using LogCat?, do you use any special configuration in the manifest related to networkSecurityConfig, etc?

**Comment by silasas** [comment]
Dear Javier, you can see the uri’s working in the Postman perfectly, but in the Visual Studio not.

 

 

 



 

De: Silas [mailto:silasas@gmail.com] 
Enviada em: quarta-feira, 26 de agosto de 2020 21:53
Para: 'xamarin/Xamarin.Forms'; 'xamarin/Xamarin.Forms'
Cc: 'Author'; Silas Anastácio
Assunto: RES: [xamarin/Xamarin.Forms] [Bug] Issue loading images (#11778)

 

Hi my friend,

 

In my computer, is not working, including this uri: http://www.macoratti.net/Imagens/pessoas/house1.jpg the same project I sent to you.

Try these uri’s:

 

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/25/cp-8e598974-8d4c-42c7-a0a3-731485eaabe1-2020825-19-20-333098.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-cb9b059b-1e31-49a0-b498-c62a046eb8fb-2020826-18-36-057025.jpg"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-8249734c-6b2b-42ae-b608-a1db9b070d45-2020826-18-42-079629.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-4db0717c-484b-466e-9c48-c6f408b33b99-2020826-18-46-297196.jpg"

 

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-da798339-5544-47e2-b795-2bcd1438048d-2020826-18-51-325262.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-76536911-4afb-486f-a6ed-ba4ac41b1dbf-2020826-18-55-354445.png"

"http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-fcbfed83-31b9-47cc-bc45-08e4cfa23ab4-2020826-18-59-083260.png"

http://vps24229.publiccloud.com.br/assets/imagens/cursoPopular/2020/8/26/cp-f0f1e0a1-99cb-4f70-b656-9568f3f4b687-2020826-19-02-174935.png"

 

 

See output window:

 

 



 

De: Javier Suárez [mailto:notifications@github.com] 
Enviada em: terça-feira, 25 de agosto de 2020 08:17
Para: xamarin/Xamarin.Forms
Cc: silasas; Author
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Issue loading images (#11778)

 

Thanks for the reproduction sample. I have done some test in your sample, but have not found issues loading the images:
 <https://user-images.githubusercontent.com/6755973/91167700-b279bf80-e6d4-11ea-8f9c-3a396bab4038.png> Captura de pantalla 2020-08-25 a las 13 04 05

Also, I have created a small sample using the image from the previous logs http://www.macoratti.net/Imagens/pessoas/house1.jpg

Issue11778.zip <https://github.com/xamarin/Xamarin.Forms/files/5123361/Issue11778.zip> 

And works without problems:
 <https://user-images.githubusercontent.com/6755973/91167537-69297000-e6d4-11ea-8b3d-5431e578d6e1.png> Captura de pantalla 2020-08-25 a las 13 08 33

Could you share logs using LogCat?, do you use any special configuration in the manifest related to networkSecurityConfig, etc?

**Comment by jsuarezruiz** [comment]
I have created another example using your images:
[Issue117782.zip](https://github.com/xamarin/Xamarin.Forms/files/5141541/Issue117782.zip)

And, works as expected.
<img width="464" alt="Captura de pantalla 2020-08-28 a las 12 16 23" src="https://user-images.githubusercontent.com/6755973/91551520-92dbd480-e92a-11ea-936c-4332a676a9bc.png">

Could you share the logs from Logcat loading the images: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows?

Launch your App, and in Visual Studio > Android > Device Log...

**Comment by silasas** [comment]
Javier, thanks for everything.

I will create a new project to make news tests

 

Yesterday, I changed my manifest file and created a file to configure the network, but didn’t work.

Today, when I opened the visual studio worked…. The project is intermittent.

 

The configuration is equal when I used yesterday… 

Sincerely I don’t understand it, so I’ll make news tests on a new project.

 

You may close this order.

 

Best regards,

Sorry for spend your time.

 

Greetings from Brazil.

 

 



 

 

 

De: Javier Suárez [mailto:notifications@github.com] 
Enviada em: sexta-feira, 28 de agosto de 2020 07:33
Para: xamarin/Xamarin.Forms
Cc: silasas; Author
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Issue loading images (#11778)

 

I have created another example using your images:
Issue117782.zip <https://github.com/xamarin/Xamarin.Forms/files/5141541/Issue117782.zip> 

And, works as expected.
 <https://user-images.githubusercontent.com/6755973/91551520-92dbd480-e92a-11ea-936c-4332a676a9bc.png> Captura de pantalla 2020-08-28 a las 12 16 23

Could you share the logs from Logcat loading the images: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows?

Launch your App, and in Visual Studio > Android > Device Log...
