### ISSUE TITLE
[Bug] Label height incorrect when text wrapping (nested layouts)

### ISSUE THREAD

**Issue by dmariogatto** [xamarin/Xamarin.Forms#11774]
### Description

I have a custom chat list layout. The latest version of Xamarin Forms (4.8.1269) cuts off the last line of wrapped text labels when inside a nested layout. This is only a problem for the chat message that is nested inside a Grid of two columns (one for the profile picture & the other for the actual message).

### Steps to Reproduce

See retry sample.

### Expected Behavior

Layout should be sized to fit the label.

### Actual Behavior

The last line of text is cut off.

### Basic Information

- Version with issue: 4.8.1269
- Last known good version: 4.7.1260

#### 4.7.1260 👍
![Droid 4.7](https://raw.githubusercontent.com/dmariogatto/xforms-issue-labelwrap/master/src/droid_47.png)

#### 4.8.1269 👍
Last line cut off for first chat bubble.
![Droid 4.8](https://raw.githubusercontent.com/dmariogatto/xforms-issue-labelwrap/master/src/droid_48.png)

### Reproduction Link

https://github.com/dmariogatto/xforms-issue-labelwrap

### Workaround

Unknown

**Comment by overzealus** [comment]
Any news on this bug fix?

**Comment by dmariogatto** [comment]
Fixed with #12475. (Xamarin Forms >= 4.8.0.1687)
