### ISSUE TITLE
[Bug] RadioButton not displaying Text property

### ISSUE THREAD

**Issue by ludas96** [xamarin/Xamarin.Forms#11773]
# Description
The RadioButton control is not displaying its Text property even with TextColor set to Black with a White background.

```xaml
<RadioButton GroupName="planning"
             TextColor="Black"
             Text="Test 1" />
<RadioButton GroupName="planning"
             TextColor="Black"
             Text="Test 2" />
<RadioButton GroupName="planning"
             TextColor="Black"
             IsChecked="True"
             Text="Test 3" />

```

### Expected Behavior
Should show the Text next to the circle.

### Actual Behavior
Not showing the text, only showing the circle.

### Basic Information

- Version with issue: 4.8.0
- Last known good version: ?
- IDE: VS 2019

### Screenshots
![test](https://user-images.githubusercontent.com/38467566/90110911-31bed900-dd4e-11ea-9f0f-59811a6bf9fd.png)

**Comment by holecekp** [comment]
This could be the same issue as the one already reported in #11700.

**Comment by ludas96** [comment]
@holecekp Ah.. missed that one. 
Well thats not good then, probably going with InputKit's RadioButton for now. Hopefully it's better with Version 5.0.

**Comment by eramrit78** [comment]
same issue in XF 4.8.0.1364 not resolved
