### ISSUE TITLE
[Bug] Application.Current.Resources["key"] fails but Application.Current.Resources.TryGetValue("key", out var value) works

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#11770]
### Description
When using a merged dictionary to split xaml styles like this (App.xaml), then retrieving a key from it in C# code through the indexer `Application.Current.Resources["key"]`, the key is never found and the indexer throws an exception.

But using `Application.Current.Resources.TryGetValue("key", out var value)` does retrieve the correct value (a Style object).

```
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="WzXam2.App">
    <Application.Resources>

        <ResourceDictionary Source="Xaml\Styles\Core.xaml"/>

    </Application.Resources>
</Application>
```

Example of Core.xaml

```
<?xml version="1.0" encoding="utf-8" ?>
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                    >
    <Style x:Key="DefaultLabelStyle" TargetType="Label">
        <Setter Property="BackgroundColor" Value="Transparent"/>
    </Style>
</ResourceDictionary>
```

### Steps to Reproduce

1. Create a xaml file containing a ResourceDictionary (Core.xaml) and a Style object having a x:Key value of "DefaultLabelStyle".
2. Reference that file in App.xaml
3. In code (after InitializeComponent()), call Application.Current.Resources["DefaultLabelStyle"]

### Expected Behavior

no exception.

### Actual Behavior

It throws an exception.

Calling `Application.Current.Resources.TryGetValue("DefaultLabelStyle", out var value)` instead works as expected.

### Basic Information

- Version with issue: all
- Last known good version: none
- IDE: VS2019 Windows
- Platform Target Frameworks: all

### Workaround

Use Application.Current.Resources.TryGetValue("DefaultLabelStyle", out var value)

**Comment by softlion** [comment]
This issue has been discovered in 2018 and is also reported here
https://forums.xamarin.com/discussion/146001/how-to-get-a-rsource-from-an-mergeddictionary-in-c-code

**Comment by StephaneDelcroix** [comment]
it's not an issue, it's by design. RD are meant to be used mainly from XAML

and we can't change this now, as it would be breaking.

there's an opportunity window to change this when we move to maui though

**Comment by StephaneDelcroix** [comment]
one API walks the parent tree, the other does not

**Comment by softlion** [comment]
@StephaneDelcroix if you look at the code, both are walking the tree. So it should work exactly the same.

**Comment by jcmanke** [comment]
> it's not an issue, it's by design. RD are meant to be used mainly from XAML
> 
> and we can't change this now, as it would be breaking.
> 
> there's an opportunity window to change this when we move to maui though

+1 for changing this in MAUI. Just have the indexing operator call TryGetValue.
