### ISSUE TITLE
[Bug] Xamarin.Forms Shell's Full Screen leads to untouchable to the tab bar menu.

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#11772]
I want to use the safe area in the android like in the ios. like this image:https://us.v-cdn.net/5019960/uploads/editor/ky/brwnjgrb6ip5.png
since android has no such effects.
someone tell me I can use full screen in android.
but in Full screen the tabbar menu can not be touched.
it will tap the system menu directly.

1. create a xamarin.forms shell project
2. custom android to use full screen in MainActivity.cs.
3. open the APP and tap the tab bar menu.

**Comment by mcguu** [comment]
any updates?

**Comment by jsuarezruiz** [comment]
@mcguu I think the origin of your issue is the same as https://github.com/xamarin/Xamarin.Forms/issues/11828, right?
If you are ok, we can group the information in the same issue.

**Comment by mcguu** [comment]
@jsuarezruiz  yes same with #11828

**Comment by mcguu** [comment]
you can close this issue and I will follow 11828

**Comment by mcguu** [comment]
can I know that when will you solve the bug please?

**Comment by samhouts** [comment]
Duplicate of #11828
