### ISSUE TITLE
[Enhancement] Please support bindings in converter parameters

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11786]
Because converter parameters can't use bindings, one is forced to add bindings to the converter itself. This can become unwieldy and you may need several converters with different parameters to do something simple, so it can easily get out of hand. Please consider adding support for bindings in converter parameters to solve this.

Tangentially related is how obscure the syntax becomes with converter bindings, https://github.com/xamarin/Xamarin.Forms/issues/11785, so none of these would be relevant if bindings could be used in parameters.

Thanks.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
