### ISSUE TITLE
[Enhancement] Close DisplayPromptAsync on keyboard ok button press

### ISSUE THREAD

**Issue by FuJa0815** [xamarin/Xamarin.Forms#11787]
## Summary
`DisplayPromptAsync` should close when pressing the keyboard accept button.
Currently the accept button only hides the keyboard.

## API Changes
This feature should be toggable using an optional boolean parameter called `closeOnKeyboardOk` or something like that.

## Intended Use Case
When asking the user for input, the user should be able to accept his input using the accept button on the virtual keyboard.

![grafik](https://user-images.githubusercontent.com/30809803/90272570-e267ce00-de5d-11ea-8d4d-c10fdb27c8db.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
