### ISSUE TITLE
[Bug] Navigate back on pressing the bottom tab

### ISSUE THREAD

**Issue by manikandankTSI155** [xamarin/Xamarin.Forms#11784]
### Description
On android, when using bottom tabs in shell, if I navigate to a new page and then navigate back by using the bottom tab bar, no navigation occurs. I am forced to use the back button.

### Steps to Reproduce

1. Create an app with shell and set up 3 bottom tabs.
2. Push a new page onto the navigation stack using Shell's GoToAsync call
3. Attempt to navigate back by pressing the bottom tab bar button.

### Expected Behavior

Need to navigate back to the previous page

### Actual Behavior

can't able to navigate previous page

### Basic Information

- Version with issue: Xamarin forms 4.6 
- Last known good version: Recently tried with Xamarin 4.8
- IDE: Visual studio 2019 windows and tried latest version in mac
- Platform Target Frameworks: 
  - iOS:  It works fine in iOS devices
  - Android: It happens in all android devices
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
Hi, this feature of popping back on iOS is a native  feature on that OS, it's related with TabController and NAvigationController, your request is a enhancement to Shell so on Android it behaves like iOS.

**Comment by aleksandrsmyk** [comment]
I am experiencing the same issue on Android.

**Comment by samhouts** [comment]
closed by #11791

**Comment by PureWeen** [comment]
Reopened. 

I linked the wrong issue from a PR
