### ISSUE TITLE
[Enhancement] SwipeView should support FontFamily

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#11781]
## Summary
Support of Text/FontAwesome (standard icons) in addition to IconImageSource (individual icons)

## API Changes

New attribute FontFamily

**Comment by DavidStrachanLexacom** [comment]
> ## Summary
> Support of Text/FontAwesome (standard icons) in addition to IconImageSource (individual icons)
> 
> ## API Changes
> New attribute FontFamily

I would second this enhancement request, where trying to minimalize the text in an application due to users changing device font size for accessibility reasons having icons is more desired.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
