### ISSUE TITLE
[Bug] Brushes API - gradient offset does nothing on Android

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11795]
```xaml
        <Setter
            Property="Background">
            <Setter.Value>
	            <LinearGradientBrush
		            StartPoint="0, 1" EndPoint="0.5, 0">
		            <GradientStop Color="{ OnPlatform iOS='Red', Android='Green' }" Offset="0.9" />
		            <GradientStop Color="{ OnPlatform iOS='Green', Android='Red' }" Offset="1.0" />
	            </LinearGradientBrush>
            </Setter.Value>
        </Setter>
```

Deliberately ugly colors to showcase the problem - 'Offset' does nothing on Android.

iOS:
<img width="64" alt="Screenshot 2020-08-15 at 7 02 31" src="https://user-images.githubusercontent.com/60286968/90304913-54bfc900-dec5-11ea-85d6-fbc1ddfd74df.png">

Android:
<img width="93" alt="Screenshot 2020-08-15 at 7 02 41" src="https://user-images.githubusercontent.com/60286968/90304916-59847d00-dec5-11ea-8fd4-0ddc49f5f14a.png">

This is quite bad as I have a very hard time making the Android version look remotely the same as iOS - so please provide a workaround if this takes some time to fix.

Thanks!

**Comment by Tommigun1980** [comment]
I think there's more problems, I stopped using the offset and edited the StartPoint and EndPoint properties instead, and Android still doesn't look remotely the same as iOS.

iOS:
<img width="77" alt="Screenshot 2020-08-15 at 7 11 55" src="https://user-images.githubusercontent.com/60286968/90305029-a3ba2e00-dec6-11ea-87fa-bfbb219440d1.png">

Android:
<img width="96" alt="Screenshot 2020-08-15 at 7 12 02" src="https://user-images.githubusercontent.com/60286968/90305030-a74db500-dec6-11ea-9d64-a86422895b62.png">

(I changed the colors to something more sensible).

**Comment by CARP-Kaiser** [comment]
`<Ellipse StrokeThickness="3"
                         Fill="AliceBlue"
                         WidthRequest="150"
                         HeightRequest="150"
                         HorizontalOptions="Center">
                    <Ellipse.Stroke>
                        <LinearGradientBrush>
                            <LinearGradientBrush.GradientStops>
                                <GradientStop Color="Blue"
                              Offset="0" />
                                <GradientStop Color="Yellow"
                              Offset="{Binding UploadProgress,Mode=TwoWay}" />
                                <GradientStop Color="Red"                              
                              Offset="1.0" />
                            </LinearGradientBrush.GradientStops>
                        </LinearGradientBrush>
                    </Ellipse.Stroke>
                </Ellipse>` 
![image](https://user-images.githubusercontent.com/54409955/96646135-49d44b00-12f1-11eb-943e-dba1c435b00f.png)

**Comment by CARP-Kaiser** [comment]
Binding the offset of the second gradient stop to the viewmodel does not work as intended. The slider value is bound to a float property in the viewmodel that should drive the offset. This is on android.
