### ISSUE TITLE
[Bug] NSInvalidArgumentException when access NSColor.SeparatorColor from MacOS < 10.14

### ISSUE THREAD

**Issue by whitneyschmidt** [xamarin/Xamarin.Forms#11790]
Moving this from xamarin-macios issue https://github.com/xamarin/xamarin-macios/issues/9352 to Forms.

`SeparatorColor` is only available on macOS 10.14 and above (Apple docs), so it would crash if called on a High Sierra machine.

The following Forms code is causing the crash:

```
// Draw border
if (Forms.IsMojaveOrNewer)
NSColor.ControlShadow.SetStroke();
else
NSColor.SeparatorColor.SetStroke();
```

https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Platform.MacOS/Renderers/SliderRenderer.cs#L86

It looks like the bug was introduced in this fix: https://github.com/xamarin/Xamarin.Forms/pull/10582/files

**Comment by whitneyschmidt** [comment]
From @SeRgI1982:

Steps to Reproduce

Create Xamarin Forms app for macOS (Xamarin Forms version: 4.8.0.1269)
Put Slider control to the ContentPage
Run the application on macOS High Sierra (version 10.13.6)
Expected Behavior

Slider should display properly

Actual Behavior

An Exception is thrown:

Exceptions: NSInvalidArgumentException: +[NSColor separatorColor]: unrecognized selector sent to class 0x7fff9461fe78
StackTrace:
at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objs_msgSend(intptr, intptr)
at AppKit.NSColor.get_SeparatorColor() [0x00001] in /Library/Frameworks/Xamarin.Mac.framework/Versions/6.20.2.2/src/Xamarin.Mac/AppKit/NSColor.g.cs:1987
at Xamarin.Forms.Platform.MacOS.c.DrawKnob (CoreGraphics.CGRect knobRect) [ 0x000cb] in <62c0011ebce544aecbb6d12e0413b63d>:0

The app behaves properly on macOS Catalina 10.15.5 but we cannot force our clients to update their own MacOS to the lates version.

Honestly, I have made a workaround for this by commenting this line

https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Xamarin.Forms.Platform.MacOS/Renderers/SliderRenderer.cs#L86

I know that this class belong to Xamarin Forms but I guess that calling

NSColor.SeparatorColor.SetStroke();

shouldn't throw a NSInvalidArgumentException, so the bug is much more deeper (Xamarin.Mac.dll) than in Xamarin.Forms.Platform.macOS.dll

or if this if statement 3 lines above is wrong (because of api changes according to OSX version)

// Draw border
if (Forms.IsMojaveOrNewer)
NSColor.ControlShadow.SetStroke();
else
NSColor.SeparatorColor.SetStroke();

let me know, so I will rise a proper issue in Xamarin.Forms Team

=== Visual Studio Community 2019 for Mac ===

Version 8.7.2 (build 4)
Installation UUID: da0195e3-f48e-46a6-99db-f4e7b1f0a286
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 6.18.0.23 (d16-6 / 088c736)

Package version: 612000090
=== Mono Framework MDK ===

Runtime:
Mono 6.12.0.90 (2020-02/d3daacdaa80) (64-bit)
Package version: 612000090

=== Roslyn (Language Service) ===

3.7.0-6.20371.12+917b9dfae12e3b6cb266a3c062fb20a1e9d5fb06

=== NuGet ===

Version: 5.7.0.6702

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.401/Sdks
SDK Versions:
3.1.401
3.1.302
3.1.301
3.1.300
3.1.202
3.1.200
3.1.102
3.1.101
3.1.100
3.0.101
3.0.100
2.1.701
2.1.700
2.1.505
2.1.302
2.1.301
2.1.4
2.0.3
1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
3.1.7
3.1.6
3.1.5
3.1.4
3.1.2
3.1.1
3.1.0
3.0.1
3.0.0
2.1.21
2.1.20
2.1.19
2.1.18
2.1.17
2.1.16
2.1.15
2.1.14
2.1.13
2.1.12
2.1.11
2.1.9
2.1.2
2.1.1
2.0.5
2.0.3
1.1.2
1.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-7/aca845b
Android SDK: /Users/DevGroup/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
4.4 (API level 19)
5.0 (API level 21)
6.0 (API level 23)
7.0 (API level 24)
7.1 (API level 25)
8.0 (API level 26)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 29.0.2

Build Information:
Mono: 83105ba
Java.Interop: xamarin/java.interop@1f3388a
ProGuard: Guardsquare/proguard@ebe9000
SQLite: xamarin/sqlite@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools@017078f

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/DevGroup/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.7.0.13
Hash: 8380518
Branch: remotes/origin/dev/jmt/d16-7readconfig~2
Build date: 2020-07-23 22:38:02 UTC

=== Android Device Manager ===

Version: 16.7.0.18
Hash: 4b44bc1
Branch: remotes/origin/d16-7
Build date: 2020-07-23 22:38:26 UTC

=== Xamarin Designer ===

Version: 16.7.0.492
Hash: f5afe667d
Branch: remotes/origin/d16-7-vsmac
Build date: 2020-07-10 18:42:54 UTC

=== Apple Developer Tools ===

Xcode 11.6 (16141)
Build 11E708

=== Xamarin.Mac ===

Version: 6.20.2.2 (Visual Studio Community)
Hash: 817b6f7
Branch: d16-7
Build date: 2020-07-18 18:44:59-0400

=== Xamarin.iOS ===

Version: 13.20.2.2 (Visual Studio Community)
Hash: 817b6f7
Branch: d16-7
Build date: 2020-07-18 18:45:00-0400

=== Build Information ===

Release ID: 807020004
Git revision: 6b86e771c92aa2615d2c2a09919bb3d4ccb69a5a
Build date: 2020-08-12 07:16:26-04
Build branch: release-8.7
Xamarin extensions: 6b86e771c92aa2615d2c2a09919bb3d4ccb69a5a

=== Operating System ===

Mac OS X 10.15.5
Darwin 19.5.0 Darwin Kernel Version 19.5.0
Tue May 26 20:41:44 PDT 2020
root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0
XAML Styler 2.0.1
StyleCop Support 1.1.0.4

https://github.com/xamarin/xamarin-macios/files/5073316/XFMacSample.3.zip

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
