### ISSUE TITLE
Xamarin Form v 4.8.0.1269 ScrollView not filling in space 

### ISSUE THREAD

**Issue by dbassioneisdata** [xamarin/Xamarin.Forms#11796]
We update Xamarin.Form from 4.7.0.1260 to 4.8.0.1269 the Scrollview doesn't fill out the screen

Code - 

            EisMainDiv = new StackLayout();
            EisMainDiv.HorizontalOptions = LayoutOptions.FillAndExpand;
            EisMainDiv.VerticalOptions = LayoutOptions.FillAndExpand;
            EisMainDiv.Margin = new Thickness(0, 0, 0, 0);
            EisScroll = new ScrollView();
           EisScroll.Content = EisMainDiv;

First Image is with version 4.7.0.1260 - Screen is filled out
Second Image is with version 4.8.0.1269 - as you can see the scrollview doesn't fill out so you can see the blue area shows up

Same Code!

![Screenshot_1597480390](https://user-images.githubusercontent.com/43245294/90308817-a90c7e00-deb0-11ea-89cd-e1c7f09f38cc.png)

![Screenshot_1597480932](https://user-images.githubusercontent.com/43245294/90308917-c857db00-deb1-11ea-9964-e916059a648c.png)

**Comment by jsuarezruiz** [comment]
This issue seems to be the same or related with https://github.com/xamarin/Xamarin.Forms/issues/11742

**Comment by hartez** [comment]
@dbassioneisdata Is your ScrollView inside of a Grid?

**Comment by dbassioneisdata** [comment]
Here is Menu Example in our project

Menu Example – ContentPage ->StackLayout->Grid -> ScrollView – Grid(This Grid is the portion with Buttons)

![WLMenu2](https://user-images.githubusercontent.com/43245294/91077329-e1c5f900-e60e-11ea-8f84-a0079de89068.png)

Here is the entry screen example

ContentPage ->Grid -> Grid->ScrollView – >StackedLayout - (This is where the entry boxes are in)

![WLEntry2](https://user-images.githubusercontent.com/43245294/91077279-ceb32900-e60e-11ea-9b76-9f107ef4753b.png)

**Comment by hartez** [comment]
@dbassioneisdata Thanks - it looks like you're seeing the same bug as reported in #11835. And it should be fixed by #11903.

**Comment by dbassioneisdata** [comment]
How can I get this new version to test - do I have to build it or is there a way to get it from nuget/

**Comment by samhouts** [comment]
closed by #11903

You can find test packages in https://dev.azure.com/xamarin/public/_build/results?buildId=24833&view=artifacts&type=publishedArtifacts
