### ISSUE TITLE
[Problem] How Use Shell Like Telegram APP?

### ISSUE THREAD

**Issue by DenisHidden** [xamarin/Xamarin.Forms#11804]
[Telegram Tab](http://uupload.ir/files/0dgz_photo_2020-08-16_20-06-04.jpg)

i want like this design but xamarin hide the photo in tabs!

tnx

**Comment by DenisHidden** [comment]
any example code?

**Comment by jsuarezruiz** [comment]
@DenisHidden Do you mean to be able to add badges, etc?

**Comment by DenisHidden** [comment]
hi i want change icon like telegram on tab
profile tab u can see 

how like telegram we can made it?

**Comment by DenisHidden** [comment]
when we put image color will be gone 

like gray and light blue i mean how show real pic...
