### ISSUE TITLE
[Bug] CarouselView Memory Leak

### ISSUE THREAD

**Issue by alaneich** [xamarin/Xamarin.Forms#11817]
### Description
It appears that the CarouselView is leaking memory.  After repeated navigating to a page with a CarouselView, profilers are showing increased memory usage with objects from the views inside the CarouselView remaining in memory.  Below is a screen shot of the Android Studio Profiler after running the repro project.  It shows increases in both the Java and Native memory usage.  It also shows 200 CollectionViewRenderer classes.  CollectionViews are used in the 4 pages of the CarouselView and the repro project displays this CarouselView 50 times and shows all 4 views so 200 CollectionViews are used.  Looks like none are getting collected.  I have only tested with Android so I don't know if this is an issue with iOS.

![CarouselTest - Android Studio profile](https://user-images.githubusercontent.com/61029557/90437702-6dcca380-e098-11ea-8f99-c3eb478e960f.png)

### Steps to Reproduce

1. Run the attached project with a profiler attached: 
[CarouselTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5086470/CarouselTest.zip)

2. The button on the main page will start the test which will go to a page with a CarouselView, show all 4 views, and navigate back to the main page 50 times.  
3. The profiler shows increased memory usage and leaked objects.

### Expected Behavior
Memory usage should not be forever increasing.
 
### Actual Behavior
Memory usage is constantly going up.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: None
- IDE: Visual Studio 15.9
- Platform Target Frameworks: 
  - Android: 9.1.7.0

**Comment by PureWeen** [comment]
Possibly related

https://github.com/xamarin/Xamarin.Forms/issues/11819

**Comment by alaneich** [comment]
Retested using v5.0.0 SR8 and the memory leak was not detected on both Android and iOS.  I suspect that #14882 fixed it for Android.  Closing this issue.
