### ISSUE TITLE
[Enhancement] Add Custom CornerRedius

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/Xamarin.Forms#11810]
Hi Please Add Custom CornerRedius Like Pancake we able to change like CornerRedius="20,30,40,50"

tnx Xamarin Forms!

**Comment by jsuarezruiz** [comment]
@DenisHidden Where would you like to add that option?, in the Frame?, or in all the views?

**Comment by DenisHidden** [comment]
Hello Sir, Frame is Nessery other if have is better but Frame is Important tnx.

**Comment by DenisHidden** [comment]
and please after update some example code for chat design with frame like telegram

Examole : [Telegram Chat](http://uupload.ir/files/11fq_capture.pngl)

**Comment by jfversluis** [comment]
This won't be happening for Forms anymore, but I think this is already implemented in .NET MAUI, yay!
