### ISSUE TITLE
[Bug] CarouselView.VisibleViews property was shared among with all carouselview

### ISSUE THREAD

**Issue by myroot** [xamarin/Xamarin.Forms#11826]
### Description
CarouselView.VisibleViews should be provide for each carouselview, but a same VisibleViews was provided

 According to this line, `new ObservableCollection<View>()` is provided by default value
https://github.com/xamarin/Xamarin.Forms/blob/a8bcaa9a609cfa6f3026775b26ab7adfb4947772/Xamarin.Forms.Core/Items/CarouselView.cs#L29

But according to `GetValue` implementation
https://github.com/xamarin/Xamarin.Forms/blob/a8bcaa9a609cfa6f3026775b26ab7adfb4947772/Xamarin.Forms.Core/BindableObject.cs#L108
It is sharing a static value (property.DefaultValue)

So, all carouselview has a same VisibleViews

### Steps to Reproduce

1.  Create two CarouselView
2.  Compare each VisibleViews 
``` c#
var carouselView = new CarouselView();
var carouselView2 = new CarouselView();
Debug.Assert(carouselView.VisibleViews != carouselView2.VisibleViews);
```

### Expected Behavior
 Should not be same

### Actual Behavior
 Has same instance

### Basic Information
- Version with issue: 4.8.0
- Last known good version: None
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
closed by #11827
