### ISSUE TITLE
[Bug] [MacOS] Tab key does not work on a textbox dynamically added

### ISSUE THREAD

**Issue by RentHQ** [xamarin/Xamarin.Forms#11825]
### Description
If an entry text box is added to a page at run time, when you focus the text box and press tab, nothing happens.  Focus remains on the text box. If there is any text in the text box at the time, that text is selected.  It is almost as if the text box is setting focus to itself after pressing tab.

### Steps to Reproduce
Sample project attached.
1. Run the sample project.
2. Press the Add Text box button.  This will add a new text box Grid.Children.Add(new Entry()).
3. If the new text box gets focus, and the tab key is pressed nothing happens.  Other text boxes on the same page which were not dynamically added work fine.
4. Press the Add Contentview button.  This replaces the whole pages content with a new contentview. e.g. ContentPage.Content = new MyContentView();.  The text boxes on the new content view do not tab correctly.  The date picker on the same view tabs correctly.  Only seems to affect the text box.

### Expected Behavior
When tab key is pressed on a text box, focus moves to the next control, regardless of how the text box was created.

### Actual Behavior
Tab key only works if the text box was included on the page when the application starts.  Any text box added at run time do not behave correctly when tab key is pressed.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version:
- IDE: Visual Studio for Mac 2019
- Platform Target Frameworks: Target platy for is MacOS
  - iOS:  
  - Android: 
  - UWP:  
  - MacOS Mojave Version 10.14.6
- Android Support Library Version: 
- Nuget Packages: NetStandard.Library 2.0.3
- Affected Devices: MacBook Pro Mid 2012. MacOS Mojave Version 10.14.6

### Reproduction Link

[TabKeyIssue_MacOS.zip](https://github.com/xamarin/Xamarin.Forms/files/5088216/TabKeyIssue_MacOS.zip)

### Workaround

I don't know of any.  If any one has any suggestions, I would be keen to know so it can unblock me.
[TabKeyIssue_MacOS.zip](https://github.com/xamarin/Xamarin.Forms/files/5088216/TabKeyIssue_MacOS.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
