### ISSUE TITLE
[Enhancement] Brush support on text

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11839]
It would be awesome if text in labels, buttons etc. would have a Brush property in addition to the existing Color TextColor property.

It would be especially useful with **font icons** as one could add gradients to the otherwise single-colored icons.

Thanks for considering.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
