### ISSUE TITLE
[Bug] ListView margin inside Grid starred row is calculated incorrectly

### ISSUE THREAD

**Issue by miko1258** [xamarin/Xamarin.Forms#11835]
### Description
After upgrade to Xamarin.Forms 4.8 I noticed that some layouts inside grid has incorrect height. Check attached screenshots. 
Probably it was broke in this PR: #11336

### Steps to Reproduce

1. Download zip and run app
2. Change Xamarin version to older and run app again

### Expected Behavior
Grid takes whole available space.

### Actual Behavior
Grid do not expand.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: 4.7.0.1260
- IDE: VisualStudio Professional 
- Platform Target Frameworks:
  - iOS:  13.4
  - Android: 10.0

### Screenshots
4.8:
![4 8](https://user-images.githubusercontent.com/11633736/90533924-69c48280-e179-11ea-9eb9-043d1dcdcdf4.jpg)

4.7:
![4 7](https://user-images.githubusercontent.com/11633736/90533930-6af5af80-e179-11ea-8b23-c2b28fc898c3.jpg)

### Reproduction Link

[GridBug.zip](https://github.com/xamarin/Xamarin.Forms/files/5091367/GridBug.zip)

**Comment by transis2** [comment]
I have the same problem! 
Rollback to XF 4.7 while waiting for fix.

**Comment by jsuarezruiz** [comment]
This issue seems to be the same or related with https://github.com/xamarin/Xamarin.Forms/issues/11742

**Comment by transis2** [comment]
Here we have another margin issue: https://github.com/xamarin/Xamarin.Forms/issues/9750

**Comment by samhouts** [comment]
closed by #11903
