### ISSUE TITLE
[Bug] DragGestureRecognizer in a CollectionView

### ISSUE THREAD

**Issue by LiddiBomb** [xamarin/Xamarin.Forms#11836]
### Description
An item in a CollectionView has a DragGestureRecognizer defined.  The gesture works as expected, but the ICommands do not fire.  The Events fire as expected.

### Steps to Reproduce

1.  Create a CollectionView bound to a ViewModel.
2.  Add a Label in the CollectionView ItemTemplate
3.  Add a DragGestureRecognizer to the Label
4.  Bind DragStartingCommand to an ICommand in the ViewModel

### Expected Behavior
When executing a long press on the Label to start a drag gesture, the DragStartingCommand should fire in the ViewModel

### Actual Behavior
When executing a long press on the Label to start a drag gesture, the DragStartingCommand does not fire.
This behavior is the same for all Commands for the DragGestureRecognizer as well as the DropGestureRecognizer.

Also, if the Drag and/or Drop Events are defined, the Events will fire as expected.

### Basic Information

- Version with issue:  4,8.0.1269
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: iOS, Android
  - iOS:  12.1
  - Android: 9.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by LiddiBomb** [comment]
Here is a modified version of the CollectionView example solution.  Select the only page shown on the main menu, and you can drag the monkey images from one row to another.  Place breaks on the gesture events and commands to see that the events fire, but the commands don't.

[Xamarin_Forms___CollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/5092603/Xamarin_Forms___CollectionView.zip)

**Comment by PureWeen** [comment]
Drag And Drop with CollectionView takes a whole additional layer of native implementations because all of the native lists have custom APIS for this

The implementation for this is incoming!!

I'm going to close this for now as there's already an enhancement here
https://github.com/xamarin/Xamarin.Forms/issues/4676
