### ISSUE TITLE
I expect to get an infinite loop when I implement IValueConverter but there isn't.

### ISSUE THREAD

**Issue by Eliranco7** [xamarin/Xamarin.Forms#11842]
### Description
In converters:
If you change the source, Convert() will be activated
and
If you change the target, ConvertBack() will be activated.

I have an Entry text which is binded in TwoWay mode to a simple string.
In Convert() I add the letter "S" ("for came from Source")
In ConvertBack() I add the letter "T" ("for came from Target").

Now, when I write something in the entry (lets say I write the string "A"), I expect the next phases to occur:
1. The Target was changed, so ConvertBack() should be called, and send the string AT to the source (Because the converter adds "T").
2. Therefore the Source was changed, so Convert() should be called and send the string ATS to the Target (Because the converter adds "S")..
3. Therefore the Target was changed, so ConvertBack() should be called, and send the string ATST to the source.
4. Therefore the Source was changed, so Convert() should be called and send the string ATSTS to the Target.
5. and on and on and on......Endlessly.

Of some reason It doesn't happen.
ConvertBack() is being called, then Convert() is being called and that's it.

Just to make clear, it is not a bug report, it is just something I expect to occur by the converter, and it doesn't.

### Steps to Reproduce

1.
 Write a converter, and override the needed methods this way:
   ```
  public class NiceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            string resultAfterConvert = value as string + "S";
            return resultAfterConvert;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            string resultAfterConvert = value as string + "T";
            return resultAfterConvert;
        }
    }
```

2. Bind a Text in an Entry to a simple string in Two Way Mode using that converter. 

3. Type a character in the entry.
### Expected Behavior

An infinite loop (due to the explanation in the description).

### Actual Behavior
 ConvertBack() is being called, then Convert() is being called and that's it.
### Basic Information

- Version with issue:
- Last known good version:   Xamarin.Forms 4.8.0.1269
- IDE: Visual Studio Community 2019 Version 16.6.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 28 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
The entry renderer is written to avoid loops like this. IIRC, when the renderer sets the value back to the bindable object, it temporarily disables the event handler specifically to avoid this sort of thing.
