### ISSUE TITLE
Xamarin forms master details rtl

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11849]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1151668/xamarin-forms-master-details-rtl.html)._

---
The master detail page when flow direction is RightToLeft and it's in landscape mode the master page shon in the left side not in the right! this is just in landscape.. it is working correctly in the normal vertical mode ♥

---
#### Feedback Bot on 8/17/2020, 01:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we have some more information? What platform? What version of Xamarin.Forms? Etc.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
