### ISSUE TITLE
[Bug] Updating Embedded Font

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#11843]
### Description
If you embed a font via
`[assembly: ExportFont("fontfile.ttf", Alias = "IconFont")]`
all works correctly. But if you you update the fontfile in your project, add a new glyph for example, then the new glyph is not shown. Only the rectangle placeholder.
I only tested with android, but perhaps this problem exists also in ios.

### Expected Behavior

New glyph in updated fontfile should be available.

### Actual Behavior

Label show only the rectangle placeholder.

### Basic Information

- Version with issue: 4.8
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

On Android delete AppData.

**Comment by AlleSchonWeg** [comment]
Somebody knows any better workaround? Because deleting appdate is no good idea if you releasing an app.

**Comment by solomonfried** [comment]
Is there any known workaround? 

Your issue has been open since August. It appears in Triage with “Needs Estimate”.

Have you noticed if the issue occurs with apk bundles? I have been releasing aab. I know that the new font file is in the bundle because it gets installed if the previous version is removed first.

I was hoping there was a way to flag a resource as "always install"

Thanks

**Comment by AlleSchonWeg** [comment]
@samhouts , @rachelkang 
Is it possible to prioritise this issue? Because it blocks us from releasing our app.

**Comment by solomonfried** [comment]
There is a solution to this issue. This worked for me,

The Shared Assembly (where the font resources are included) need to be added to the Forms.Init call in App.xaml.cs in the UWP project.

In the OnLaunched method, before Forms.Init, add the following....

```
protected override void OnLaunched(LaunchActivatedEventArgs e)
 {
            var assembliesToInclude = new List<Assembly>
            {
                // .. what ever you may have now for adding 3rd party controls..
                // Add the Assembly of your applications Shared App.
                 typeof(MySharedApp.App).GetTypeInfo().Assembly
             }

              Forms.Init(e, assembliesToInclude);
              
}
```

Your ExportFont should work like it does on Android and iOS

**Comment by AlleSchonWeg** [comment]
Hi @solomonfried ,

this did not work for my with android (I don't use UWP). I used this:
   ```
     protected override void OnCreate(Bundle savedInstanceState)
        {
			....
			global::Xamarin.Forms.Forms.Init(this, savedInstanceState, typeof(xxx.App).GetTypeInfo().Assembly);
			LoadApplication(new App());
		}
```

and a colleague created a new PR with an additional icon in our custom font. The new icon is not shown. Only reinstalling the app works. Then the icon appears.

**Comment by solomonfried** [comment]
> Hi @solomonfried ,
> 
> this did not work for my with android (I don't use UWP). I used this:
> 
> ```
>   protected override void OnCreate(Bundle savedInstanceState)
>      {
>  		....
>  		global::Xamarin.Forms.Forms.Init(this, savedInstanceState, typeof(xxx.App).GetTypeInfo().Assembly);
>  		LoadApplication(new App());
>  	}
> ```
> 
> and a colleague created a new PR with an additional icon in our custom font. The new icon is not shown. Only reinstalling the app works. Then the icon appears.

My apologies. I confused 2 separate ExportFont issues that I was following.

For the issue of having 2 remove and reinstall the app in order to show glyph changes, have you tried renaming the FontFile? (e.g. add a number to the end) The change the [ExportFont] attribute to reflect the change. I would assume that that would have to create a new Embedded Resource. 

This is not a long term solution, but might get you through releasing your app now.

**Comment by AlleSchonWeg** [comment]
> > Hi @solomonfried ,
> > this did not work for my with android (I don't use UWP). I used this:
> > ```
> >   protected override void OnCreate(Bundle savedInstanceState)
> >      {
> >  		....
> >  		global::Xamarin.Forms.Forms.Init(this, savedInstanceState, typeof(xxx.App).GetTypeInfo().Assembly);
> >  		LoadApplication(new App());
> >  	}
> > ```
> > 
> > 
> > and a colleague created a new PR with an additional icon in our custom font. The new icon is not shown. Only reinstalling the app works. Then the icon appears.
> 
> My apologies. I confused 2 separate ExportFont issues that I was following.
> 
> For the issue of having to remove and reinstall the app in order to show glyph changes, have you tried renaming the FontFile? (e.g. add a number to the end) Then change the [ExportFont] attribute to reflect the change. I would assume that that would have to create a new Embedded Resource which should resolve the issue.
> 
> This is not a long term solution, but might get you through releasing your app now.

Thanks. Renaming the updated fontfile works. I changed the name to fontfile_1.ttf and the attribute to `[assembly: ExportFont("fontfile_1.ttf", Alias = "IconFont")]`. No need to change the alias.

**Comment by tringert** [comment]
Thank you @solomonfried you saved my day! Renaming was the solution!

**Comment by ChristopherStephan** [comment]
Another workaround is to include the font files in the platform projects and mark them as AndroidAsset/BundleResource.

**Comment by juwens** [comment]
I developed this: 

```
public static void DeleteFontCacheIfFontChanged()
{
    var assembly = typeof(App).Assembly;
    var exportFontAttribute = assembly.GetCustomAttributes(typeof(ExportFontAttribute), true).FirstOrDefault() as ExportFontAttribute;
    
    if (exportFontAttribute == null) return;
    
    string? fontFilePath = null;
    if (Device.RuntimePlatform == Device.Android)
    {
        fontFilePath = Path.Combine(Xamarin.Essentials.FileSystem.CacheDirectory, exportFontAttribute.FontFileName);
    }
    else if (Device.RuntimePlatform == Device.UWP)
    {
        fontFilePath = Path.Combine(Xamarin.Essentials.FileSystem.AppDataDirectory, "fonts", exportFontAttribute.FontFileName);
    }
    else if (Device.RuntimePlatform == Device.iOS)
    {
        // TODO
    }
    
    if (fontFilePath == null || !File.Exists(fontFilePath)) return;
    
    var deleteFile = false;
    
    var asmName = assembly.GetName().Name;
    using (var embeddedStream = assembly.GetManifestResourceStream(asmName + ".Resources.Fonts." + exportFontAttribute.FontFileName))
    using (var fileStream = File.OpenRead(fontFilePath))
    {
        var embeddedFontHash = GetHash(embeddedStream);
        var cachedFontHash = GetHash(fileStream);
    
        deleteFile = !embeddedFontHash.SequenceEqual(cachedFontHash);
    }
    
    if (deleteFile)
    {
        Debug.WriteLine($"deleting '{fontFilePath}'");
        File.Delete(fontFilePath);
    }
    
    static byte[] GetHash(Stream stream)
    {
        using (SHA256 hashAlgorithm = SHA256.Create())
        {
            byte[] data = hashAlgorithm.ComputeHash(stream);
            return data;
        }
    }
}
```

**Comment by juwens** [comment]
Any idea for iOS?

**Comment by Seuleuzeuh** [comment]
Thanks @juwens for the workaround, it work greats (for an Android App).

I've adapted it to work with multiple EmbeddedFont.

**Comment by zain442** [comment]
juwens where did you add that code?
