### ISSUE TITLE
Dlls can't be found by the projects that reference it [Xamarin.Forms]

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11847]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1144377/dlls-cant-be-found-by-the-projects-that-reference.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
When I try to build the Xamarin.Forms source code the build can't copy the .dlls into the ref folder, causing a lot of crashes.

To reproduce the error, clone main branch, clean everything and try to build it. A lot off "File of origin: ...\Debug\netstandard2.0\ref\foo.dll" could't be found".

My Visual Studio is in brazilian portuguese.

---
#### Feedback Bot on 8/11/2020, 03:55 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
What version of Xamarin.Forms are you using? If you update to the latest 4.7.0 or 4.8.0, does the problem persist? Thanks!

**Comment by pictos** [comment]
Hey @samhouts, I did this report. This problem occurs when I clone the project and try to build it, for some reason the MSBuild can't copy some dlls into the ref folder. I attached a screenshot in the report and in the Xamarin.Forms discord chat. But if you want, I can upload all screenshots here.

**Comment by jsuarezruiz** [comment]
@pictos I have searched Discord but I have not been able to find the correct images, sorry but, could you attach them here?

**Comment by pictos** [comment]
For sure, @jsuarezruiz here is the image:
![image](https://user-images.githubusercontent.com/20712372/91562595-d1b26000-e913-11ea-9858-491c329b7cbe.png)

This one occurs more often, it's an error in the Material.Android project. Sometimes doing a rebuild works fine other times I need to clean up everything

**Comment by PureWeen** [comment]
From chatting with the Android team it looks like this is an issue with using SDK Extras 

We removed the multi targeted project which should help on 5.0.0. If we keep seeing this issue with SDK Extras we will probably convert back to a Xamarin.Android project until the android sdk extra targets are ready
