### ISSUE TITLE
[Bug] Navigate back using GoToAsync("..") on modal pages

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#11841]
### Description
It's currently not possible to navigate back from a modal page using the syntax GoToAsync("..").

### Steps to Reproduce

1. Define a modal page with: Shell.PresentationMode="ModalAnimated"
2. Navigate to it using Shell.Current.GoToAsync("/MyModalPage");
3. Try to navigate back from MyModalPage using GoToAsync("..")

### Expected Behavior
Should navigate back like the following would: await Shell.Current.Navigation.PopModalAsync();

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 4.7
- Last known good version: -
- IDE: VS for Mac 8.5
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: 10
- Android Support Library Version: AndroidX

### Workaround
````
await Shell.Current.Navigation.PopModalAsync();
````

**Comment by PureWeen** [comment]
@MaxFmi can you provide a repro? and/or test on latest 4.8?

I've attached the "File => New" project from VS 16.8 that uses the navigation you describe and it works fine.
There was an issue with this if you didn't define any routes on your shell that was fixed so perhaps that's the issue you are running into? 

[App7.zip](https://github.com/xamarin/Xamarin.Forms/files/5158505/App7.zip)

**Comment by MaxFmi** [comment]
Thanks for the repo. I will adjust it with the described scenario this week :-)

**Comment by samhouts** [comment]
Thanks, we'll look for it. :)

**Comment by MaxFmi** [comment]
Sry I'm late. Will do that today.

**Comment by MaxFmi** [comment]
A few colleges are navigating to a regular page from the modal page. I just tried this and received the following error message "Shell cannot push a page to the following type: App7.Views.NewItemPage. The visible modal page needs to be a NavigationPage".
The UX guys have declared a few modal pages to separate some App areas visually. In some cases those modal pages navigate to a regular page again (forward navigation by using GoToAsync("anotherRegularPage")). This works fine for many colleges. 
I asked them about how they do that and will come back with an answer. 
But that is not the reason for this GitHub issue. They aren't able to go back from "somePages/modalPage/regularPage" by using GoToAsync("..")

**Comment by PureWeen** [comment]
@MaxFmi can you test with the nugets on this PR

https://dev.azure.com/xamarin/public/_build/results?buildId=26494&view=artifacts&type=publishedArtifacts

See if they act better for you?

**Comment by MaxFmi** [comment]
![Screenshot 2020-09-16 at 16 05 17](https://user-images.githubusercontent.com/61872738/93348384-6da9fa00-f836-11ea-9a65-ea5356efeb77.png)
Should I be able to click on "nuget" to download it? Nothing is happening. 
I never used azure.

**Comment by PureWeen** [comment]
@MaxFmi when you hover there will be three dots

click those

![image](https://user-images.githubusercontent.com/5375137/93350069-79290100-f7f5-11ea-998c-2ee5f3579e13.png)

**Comment by MaxFmi** [comment]
@PureWeen Thanks

**Comment by PureWeen** [comment]
@MaxFmi so the issue in your sample is that you are pushing the modal using the Navigation class instead GotoAsync so shell isn't able to build a URI for where it's at so it doesn't know what ".." means

I've fixed that with the nuget I've sent you which should be fixed on XF 5.0 

I tested your sample against that nuget and with that the ".." navigation works 

Let me know if you see any other issues with the nuget I sent you

**Comment by MaxFmi** [comment]
@PureWeen That sounds great. Thanks for testing. I'll try it in the next couple days.

**Comment by MaxFmi** [comment]
@PureWeen It work a bit strange. Always at the second click (see attached video).
[GoBackBy_GoToAsync(..).mov.zip](https://github.com/xamarin/Xamarin.Forms/files/5253931/GoBackBy_GoToAsync.mov.zip)

**Comment by PureWeen** [comment]
@MaxFmi can you try 5.0 pre3? If you're still seeing an issue can you attach a repro? I tested with the zip here https://github.com/xamarin/Xamarin.Forms/issues/11841#issuecomment-693426569 and the ".." seems to be working alright

**Comment by PureWeen** [comment]
I'm going to close this one for now.

@MaxFmi let me know if you are still seeing this issue with 5.0
