### ISSUE TITLE
[Enhancement] Add FontFamily property to Shell Tabs

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/Xamarin.Forms#11855]
Hello Xamarin Forms.

Why We Cant Set Font Family Into Tabbar?

**Comment by DenisHidden** [comment]
<FlyoutItem  Route="HomePage" x:Name="mytab" Title="صفحه اصلی" Icon="Asli.png">

        <Tab  Route="SabtFile"   Title="File" Icon="ic_save.png">
            <ShellContent>
                <pages:PageSaveEstate></pages:PageSaveEstate>
            </ShellContent>
        </Tab>
 </FlyoutItem>


how i set font family for Titile?! we not have property please add this property on update.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
