### ISSUE TITLE
Xamarin forms, Tabmode="scrollable" tabs not working, API 29 and up

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11850]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1154340/xamarin-forms-tabmodescrollable-tabs-not-working-a.html)._

---
[severity:I'm unable to use this version of Visual Studio]
Xamarin-Forms, Android project, TabMode="Scrollable" tabs in Tabbedpage not working when using API 29 and up. The tabs are all compressed as if they were in TabMode=Fixed.
 All works fine in API 28.

---
#### Feedback Bot on 8/18/2020, 09:23 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
I have created a sample where try to reproduce the issue:
[Issue11850.zip](https://github.com/xamarin/Xamarin.Forms/files/5130788/Issue11850.zip)

But cannot reproduce the issue. Using `TabMode="Scrollable" `works as expected.

<img width="484" alt="Captura de pantalla 2020-08-26 a las 17 09 09" src="https://user-images.githubusercontent.com/6755973/91328027-9bb39580-e7c6-11ea-8e5f-e26d1d1c9d05.png">

Test with API 28 and 29.

Could we have more information or an attached sample where reproduce the issue?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
