### ISSUE TITLE
[Enhancement] ListView Select item Background

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/Xamarin.Forms#11856]
Hello Please Add Property For Select item of listview default is Orange....

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
