### ISSUE TITLE
Android Only Alternative Resource Images Scale Differently Than Default[Bug] 

### ISSUE THREAD

**Issue by CARP-Kaiser** [xamarin/Xamarin.Forms#11854]
### Description
I have a possible xf bug. I have an android app that has alternative image resources that are now scaling incorrectly.
### Steps to Reproduce

1. Have alternative assets in drawable folders of Android project.
2. Build application.
3. Run adhoc with and without alternative resources.

### Expected Behavior
Scaling should be identical.
### Actual Behavior
Alternative resource scaling is different than default scaling.
### Basic Information
The example I will be showing is a menu image from the master page.
- Version with issue: v4.6.0.800
- Last known good version: NA
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
*Acr.UserDialogs 7.1.0.442
*Xamarin.Forms 4.6.0.800

- Affected Devices: 
*Samsung Galaxy S8 
*Samsung Galaxy S20 Ultra

### Screenshots
![image](https://user-images.githubusercontent.com/54409955/90671949-0559ff80-e21b-11ea-8e6f-55e850f84e96.png)

![image](https://user-images.githubusercontent.com/54409955/90672546-e3ad4800-e21b-11ea-953f-a9c4b5a53cfa.png)

![image](https://user-images.githubusercontent.com/54409955/90673148-ea888a80-e21c-11ea-9b04-5ee9046a49f8.png)

![image](https://user-images.githubusercontent.com/54409955/90673397-4b17c780-e21d-11ea-9bd2-87efad5b3688.png)

**Comment by jsuarezruiz** [comment]
@CARP-Kaiser  Could you share a sample where reproduce the issue?.

**Comment by CARP-Kaiser** [comment]
@jsuarezruiz I will attempt to make a dummy project tomorrow.

**Comment by samhouts** [comment]
@CARP-Kaiser Thanks, we'll keep looking for it!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
