### ISSUE TITLE
[Enhancement] SnackBar

### ISSUE THREAD

**Issue by DenisHidden** [xamarin/Xamarin.Forms#11867]
Hello Xamarin Forms!

There Is Any Control of Snackbar Like Material Design in Android? But i want in Xamarin Form?

we have snack bar in xamarin Forms?

**Comment by jsuarezruiz** [comment]
@DenisHidden Thanks for your feedback!. We are going to close this PR to concentrate all the feedback around the idea of having **Snackbar** in #8251. You can add your feedback there!.

**Comment by rmarinho** [comment]
Duplicate #8251
