### ISSUE TITLE
[Bug] TitleView accessibility issue

### ISSUE THREAD

**Issue by jhunterdfly** [xamarin/Xamarin.Forms#11866]
### Description

I'm encountering an Xamarin Forms accessibility issue with setting focus to a custom TitleView on NavigationPages when changing pages within a TabbedPage.

This is on a device (iPhone/Android) with VoiceOver/Talkback modes active and the user is using swipe navigation to move between labels, views, and entries.

### Steps to Reproduce

1. activate VoiceOver/Talkback on the device
2. start app and navigate between tabs
3. observe accessibility focus.

### Expected Behavior

When the user changes from one tabbed page to another we would like the focus to set to a Label contained in the TitleView rather than the original title from the tabbed page.

### Actual Behavior

when the user changes from one tabbed page to another, the focus remains on the tab bar focused on the icon/text for the new page rather than move to the label contained in TitleView.

The Label is contained in a ContentPage NavigationPage TitleView and is named titleLabel.

Calling titleLabel.Focus();  in the pages OnAppearing() call doesn't change the focus, it doesn't appear to have any impact.

If the user taps on the title area, the page's title (but not the TitleView) will accept focus (and articulate the name of the page from Title property) and then swipe left/right between the objects on the content page will navigate correctly.
 
If an object is in focus, then a swipe up will navigate to the Title (and articulate the name of the page) but not to my Label in the title view.

If an object is not in focus, then a swipe up will result in VoiceOver saying "heading not found", (I couldn't find that phrase in my app nor in Xamarin forms source code),

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version:
- IDE: VS Mac / VS 2019
- Platform Target Frameworks: 
  - iOS:  8.0 
  - Android: 6.0 
  - UWP:  not a target
- Android Support Library Version: 
- Nuget Packages:
Xamarin Forms, Prism, FFImageLoading

- Affected Devices:
iPhone Xs Max (13.6)
Android tablet. Samsung SM-T510 (API 28)
et. al.

### Reproduction Link

Reproduction link may be found at:
https://github.com/jhunterdfly/AccessibilityTest

### Workaround

No workarounds found so far,

**Comment by jsuarezruiz** [comment]
Is related with https://github.com/xamarin/Xamarin.Forms/issues/11426

**Comment by rachelkang** [comment]
Hi, @jhunterdfly - Are you still experiencing issues? If so, and if you haven't already, please update to XF5 and then also check out https://github.com/PureWeen/A11YTools. Let us know how it goes!

**Comment by jfversluis** [comment]
No response to our request for more info, so closing this for now.
