### ISSUE TITLE
iOS SearchBarRenderer throws a NullReferenceException when the SearchButton redirects to a new page

### ISSUE THREAD

**Issue by cvergaray** [xamarin/Xamarin.Forms#11865]
### Description
In cases where the iOS SearchBar OnSearchButtonClicked event handler redirects to a different page, the SearchBarRenderer throws a NullReferenceException.
This only happens on iOS.

### Steps to Reproduce

1. Launch provided app
2. Type some text into the search bar
3. Press the "Search" button

### Expected Behavior
When navigating to a new page from within an OnSearchButtonClicked event handler, no exceptions are thrown.

### Actual Behavior
The application crashes when navigating to a new page from within an OnSearchButtonClicked event handler.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: Unknown
- IDE: Visual Studio Enterprise 2019 16.6.5
- Platform Target Frameworks:
  - iOS:  13.20.2.2
- Nuget Packages:
  - NETStandard.Library v2.0.3
  - Xamarin.Forms v4.8.0.1269
- Affected Devices: Suspected all, but tested on iPhone 6, iPhone SE, and iPad Pro

### Reproduction Link

[SearchBarRendererExceptionDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/5105143/SearchBarRendererExceptionDemo.zip)

**Comment by samhouts** [comment]
closed by #11897
