### ISSUE TITLE
Child Elements are not cleared while using the templates of CarouselView.FormsPlugin when Dispose(UWP).

### ISSUE THREAD

**Issue by mugundhan-saravanan** [xamarin/Xamarin.Forms#11878]
### Description

Child Elements of CarouselView.Plugin has not be cleared while navigating to another page

### Steps to Reproduce

1. Check the debugger memory session
2. Take screenshot
3. Click open carousel
4. work on the list view and navigate back 
5. Take screenshot
6. Stop Collection and check the session

Instances are not cleared
### Expected Behavior
Instances must be cleared
### Actual Behavior
Instances are not cleared
### Basic Information

- Version with issue: latest
- Nuget Packages: Xamarin.Forms -4.7.0.1239
- Affected Devices: CarouselView.FormsPlugin - 5.2.0

### Screenshots

![carouselViewPlugin](https://user-images.githubusercontent.com/56623793/90911744-08a9e280-e3f7-11ea-9326-349ebcc1c705.png)

### Reproduction Link

[CarouselView.Plugin.zip](https://github.com/xamarin/Xamarin.Forms/files/5109917/CarouselView.Plugin.zip)

### Workaround

Without using a CarouselView.Plugin or use any other items source control such as CollectionView or normal CarouselView means it children has been cleared, so this have reproduced only in the CarouselView.Plugin https://www.nuget.org/packages/CarouselView.FormsPlugin/

**Comment by jsuarezruiz** [comment]
The issue looks like a CarouselView.FormsPlugin issue, you can open an issue using https://github.com/alexrainman/CarouselView/issues

**Comment by mugundhan-saravanan** [comment]
Opened
https://github.com/alexrainman/CarouselView/issues/581
