### ISSUE TITLE
[Bug] Label MaxLine not updating value after changing from View Model

### ISSUE THREAD

**Issue by viveknegi51288** [xamarin/Xamarin.Forms#11875]
### Steps to Reproduce

1. Create 3 labels with Maxline (with differnt binding as  {Binding MaximumValue)) and 3 buttons(Binding ShowMoreLessCommand}) for each label
2. Bind your view with View Model.
3. Set MaximumValue = 100 on every button . click.

###It should increase the maxline of lable

### Basic Information

- Version with issue: Latest Version of Xamarin (4.8)
- Last known good version: Never tried this 
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  13
  - Android: 29
  - UWP:  Not using
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

Can you please provide a sample app please

**Comment by jsuarezruiz** [comment]
Attached a reproduction sample: [Issue11875.zip](https://github.com/xamarin/Xamarin.Forms/files/5116918/Issue11875.zip)

Works on iOS as expected.

**Comment by viveknegi51288** [comment]
@jsuarezruiz Its not working on android, Can you check on android as well.

**Comment by viveknegi51288** [comment]
@jsuarezruiz I have check your sample app, its only working on ios, I am facing problem in android. can you please check again and let me know

**Comment by jsuarezruiz** [comment]
Yes, is not working on Android as expected. I validated that, removed the _"unverified"_ flag, added the _"Android"_ flag and moved the issue to _"Ready For Work"_.

**Comment by viveknegi51288** [comment]
@samhouts  any update ? when this will fix ?
