### ISSUE TITLE
iOS Accessability VoiceOver stops before the end of screen when using ScrollView

### ISSUE THREAD

**Issue by carlostrujillo** [xamarin/Xamarin.Forms#11876]
### Sample

https://github.com/carlostrujillo/AccessTestXamForms

### Description

When enabling VoiceOver on iOS, and swiping up double fingers, the VoiceOver starts reading all the elements in the screen but stops before the end, making the "boundary reached" sound. The content of the view is a ScrollView and inside there is a StackLayout with the other elements. The number of elements inside the StackLayout is about 10 - 14. Less than 5 elements it seems to work well.
All elements have AutomationProperties.IsInAccessibleTree set to true and AutomationProperties.Name set.

### Steps to Reproduce

1. Enable VoiceOver on iPhone in Settings -> Accessability -> VoiceOver 
2. Run the AccessTestXamForms app and when the main page is loaded, select any item and double tap to open the item details page.
3. Swipe up with double fingers to read all the content from top to bottom

### Expected Behavior

Voice over reads all the items in the page

### Actual Behavior
Voice over stops in the 5th last element (Switch control) before the end. 
If elements are added or removed, the last control read might change yet not reaching the bottom of the page.
If the ScrollView is removed and only use StackLayout this works.

### Information

- IDE and IDE version: Visual Studio 2019
- Platform with the issue: iOS
  - iOS:  13.3.1
- Device or simulator/emulator: Device iPhone XR
-Xamarin Forms 4.7.0.1080

**Comment by rachelkang** [comment]
Hi, @carlostrujillo thanks for submitting this issue! This is no longer an issue in XF 5.0 and the VoiceOver goes all the way through. However, if you continue to have issues after updating to 5.0, feel free to reopen this!

Note - we are still taking a look at other ScrollView/VO-related issues you may experience! (i.e. if you're using TabIndex, you may experience a different issue where the VO reads all the elements but doesn't automatically scroll as well.) As always, if you experience an issue that is not yet on our [Accessibility board](https://github.com/xamarin/Xamarin.Forms/projects/61#card-47095631), we welcome you to submit a new issue
