### ISSUE TITLE
[Bug] Transparent Modal doesn't work on iOS

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#11877]
### Description

When modally pushing a page with a transparent background over an existing page the background is transparent while the Navigation the page is animating, and then the background loses transparency.

Note this impacts the Prism 8 update to the DialogService as we are updating to use a Modal Page with a transparent background. See PR https://github.com/PrismLibrary/Prism/pull/2169/

Also while this may be related to #10861, I've opened this as a separate issue as I have tested with and without a NavigationPage in the mix and get the same results.

### Steps to Reproduce

1. Set App.MainPage = SomeRootPage
2. Create new ContentPage
  - Set the Page Background to Color.Transparent
  - Give the content a mask layer with an opaque color
3. Push the new page modally on the currently visible page

### Expected Behavior

The Page background should be transparent with the opaque mask visible and showing the content of the underlying page

### Actual Behavior

The Page background is transparent while the Navigation Animation is running and then loses transparency. If using `PushModallyAsync(page, false)` the new page simply is presented modally without a transparent background.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: n/a
- IDE: Visual Studio 2019 16.7.1
- Platform Target Frameworks: 
  - iOS:  13.20.2.2 (817b6f72a)
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

| Android | iOS |
|:--------:|:---:|
| ![transparent-modal-android](https://user-images.githubusercontent.com/3860573/90903623-0dcd4a00-e383-11ea-8f61-c43c77f3001a.gif) | ![transparent-modal-ios](https://user-images.githubusercontent.com/3860573/90903647-1887df00-e383-11ea-83d4-e684d839f004.gif) |

### Reproduction Link

https://github.com/PrismLibrary/Prism/tree/transparent-modals/e2e/Forms

### Workaround

n/a

**Comment by jsuarezruiz** [comment]
@dansiegel  Using the PlatformSpecific that allows setting the ModalPresentationStyle:

`On<iOS>().SetModalPresentationStyle(UIModalPresentationStyle.OverFullScreen);`

Should allow you to use a transparent background.

**Comment by dansiegel** [comment]
thanks for the work around and fix in progress.
