### ISSUE TITLE
[Bug] Xamarin Forms Returning Non-Null iCloud Ubiquity Container Object While Xamarin.iOS Standalone Doesn't 

### ISSUE THREAD

**Issue by ctmobiledev** [xamarin/Xamarin.Forms#11886]
I am able to create an iCloud Ubiquity Container in a standalone Xamarin.iOS project but not in a Xamarin Forms project.

I created a simple Xamarin.iOS project with this code segment in the **ViewDidLoad** method:

```
            ThreadPool.QueueUserWorkItem(_ => {
                containerUrl = NSFileManager.DefaultManager.GetUrlForUbiquityContainer(null).Append("Documents", true);
                Console.WriteLine(">>> containerUrl = " + containerUrl);
            });

```

I have all the appropriate settings in the Info.plist file:

```
	<key>NSUbiquitousContainers</key>
	<dict>
		<key>iCloud.iCloudTest001Cont1</key>
		<dict>
			<key>NSUbiquitousContainerIsDocumentScopePublic</key>
			<true/>
			<key>NSUbiquitousContainerName</key>
			<string>MyTest001Documents</string>
			<key>NSUbiquitousContainerSupportedFolderLevels</key>
			<string>Any</string>
		</dict>
	</dict>

``` 
A variant of this code was in another solution here on the Xamarin Forums.

The code above works on an actual iOS device (I tested on an Apple 6S).

I want to be able to do similar for Xamarin Forms, because I want to be able to contact iCloud, but from the Xamarin.iOS project inside of it (not the Shared project folder). To that end, I created an **ICloudHelper** interface in the Shared project, which includes a method signature called **iCloudHelperInit()**. Then, inside the Xamarin.iOS folder (root) level I have an iCloudHelper class which implements the ICloudHelper interface, and a local method that implements the iCloudHelplerInit signature. It has the same C# code segment as above.  

I call the method inside the Shared project using a **DependencyService** as follows:

```
            if (Device.RuntimePlatform == Device.iOS)
            {
                Console.WriteLine(">>> iOS PLATFORM DETECTED");

                DependencyService.Get<ICloudHelper>().iCloudHelperInit();
            }

```
Sadly, this Forms version crashes out with a NullReferenceException. The **Info.plist** file in the Xamarin.iOS folder project has the _exact same XML key values_ as in the standalone Xamarin.iOS project, for the **NSUbiquitousContainers** key.

The behavior I had expected in the Xamarin Forms project is the same as that of the Xamarin.iOS project - namely, a non-null value returned for:

`NSFileManager.DefaultManager.GetUrlForUbiquityContainer`

I don't believe I've done anything incorrectly in the setup; it just seems like one of those many things in abstracting iOS that could easily be missed.

I have attached two very simple projects - **iCloudTest002-001**, the first, is the working Xamarin.iOS standalone project. **iCloudForCG4**, the second, is the Xamarin Forms standalone project. Both projects are zipped into this attachment:

**iCloud-Xamarin-Forms-UBQ-Container-Issue.zip**

I would love to see this resolved, as I love Xamarin Forms and find it much easier for doing iOS development than even regular Xamarin.iOS!

Cheers!

[iCloud-Xamarin-Forms-UBQ-Container-Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/5113557/iCloud-Xamarin-Forms-UBQ-Container-Issue.zip)

**Comment by jsuarezruiz** [comment]
I am getting the same result in both Xamarin.Forms and Xamarin.iOS projects. I get a NullReferenceException in `NSFileManager.DefaultManager.GetUrlForUbiquityContainer`. The info from the manifest (NSUbiquitousContainers) is the same.

Tested on simulator (iOS 13.6) and iPad (iOS 13.5). What specific version are you using for testing?

**Comment by ctmobiledev** [comment]
Javier:

I'm using iOS 13.3.1 on an actual iPhone 6S device. I haven't tested on the iOS simulator, although the Mac is running Xcode 11.6, so whatever simulator comes with that. 

Thanks,
Charles
Small Screen Software

**Comment by hartez** [comment]
@ctmobiledev 

Both projects worked just fine for me - `GetUrlForUbiquityContainer()` returned the URL correctly in each one.

I noticed in the Forms project you attacehd that the entitlements weren't set - under iOS Bundle Signing, Additional Resources, Custom Entitlements:

![image](https://user-images.githubusercontent.com/538025/92262837-f3be5c00-ee98-11ea-9554-da6dc61ba772.png)

I had to update that to point to Entitlements.plist before it would work. Does setting that fix your issue?

**Comment by ctmobiledev** [comment]
Thanks for the help with this. I haven't verified your suggested resolution because unfortunately the project for which this was to be applied has been shuttered for the foreseeable future. So unless someone in the Xamarin organization has an interest in this issue for some reason, this ticket can be closed.

**Comment by ctmobiledev** [comment]
Project discontinued, no need for fix anymore.
