### ISSUE TITLE
[Bug] CollectionView bug in a multi-window app

### ISSUE THREAD

**Issue by KPixel** [xamarin/Xamarin.Forms#11882]
### Description

When multiple `CollectionView` elements are bound to the same observable collection, changing that collection crashes the app.

https://github.com/xamarin/Xamarin.Forms/blob/52592fac6158c9f3abb9118c2ceca6c348e21c98/Xamarin.Forms.Core/Layout.cs#L62

### Steps to Reproduce

[The Control Gallery already has a multi-window sample](https://github.com/xamarin/Xamarin.Forms/blob/52592fac6158c9f3abb9118c2ceca6c348e21c98/Xamarin.Forms.Controls/CoreGallery.cs#L603), so we will add some extra code to repro this bug:

1. Add this new static field to [the content page that is created for these secondary windows](https://github.com/xamarin/Xamarin.Forms/blob/52592fac6158c9f3abb9118c2ceca6c348e21c98/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs):

```C#
private static readonly ObservableCollection<string> ObservableStrings = new ObservableCollection<string>();
```

2. After this line:

https://github.com/xamarin/Xamarin.Forms/blob/52592fac6158c9f3abb9118c2ceca6c348e21c98/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue2482.cs#L88

Add:

```C#
layout.Children.Add(new CollectionView
{
    ItemsSource = ObservableStrings,
    ItemTemplate = new DataTemplate(() => new Label().Bind())
});
layout.Children.Add(new Button
{
    Text = "Click me to add an item to the CollectionView",
    Command = new Command(() => ObservableStrings.Add(DateTime.Now.ToLongTimeString()))
});
```

3. Run the Control Gallery app and click on the "Open Secondary Window" button twice.

4. Click on the new button.

### Expected Behavior

The added items should be displayed in all the windows.

### Actual Behavior

The new windows will appear blank. This seems to happen if we open one secondary window, add some items, then try to open another secondary window.

Or the whole app will crash if we open many secondary windows first before adding the first item.

### Basic Information

- Version with issue: 4.8.0.1269
- Platform Target Frameworks:
  - iOS: Haven't checked
  - Android: Haven't checked
  - UWP: 18362

Note: I am currently running a [modified version of X.F](https://github.com/xamarin/Xamarin.Forms/issues/11881). So, do let me know if the behavior is different on your machines.

**Comment by jsuarezruiz** [comment]
Attached a reproduction sample:
[Issue11882.zip](https://github.com/xamarin/Xamarin.Forms/files/5136096/Issue11882.zip)


`Unable to cast COM object of type 'System.Collections.Specialized.NotifyCollectionChangedEventHandler' to class type 'System.Collections.Specialized.NotifyCollectionChangedEventHandler'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.`

**Comment by KPixel** [comment]
Based on this discussion https://github.com/xamarin/Xamarin.Forms/discussions/11823, I think that this behavior is by design: We should marshal these changes for each window.

The simplest solution is to use something like [MarshalingObservableCollection](https://github.com/xamarin/Xamarin.Forms/blob/52592fac6158c9f3abb9118c2ceca6c348e21c98/Xamarin.Forms.Core/Items/MarshalingObservableCollection.cs) (after fixing its bug reported here: #11880).

So, I think we can close this issue. Ok?
