### ISSUE TITLE
[Bug] [iOS] Editor Placeholder (Visual=Default) is rendered way too high

### ISSUE THREAD

**Issue by acuntex** [xamarin/Xamarin.Forms#11889]
### Description
When using an Editor control in Xamarin.Forms on iOS the Placeholder on iOS is way too high and not on the same position like the text.
On Android it works perfectly.

### Steps to Reproduce

1. Create Editor in xaml
2. Set Placeholder to some text
3. Start app in iOS

### Expected Behavior
Placeholder text is in the same position as the typed text.

### Actual Behavior
Placeholder text is way too high.

### Basic Information

- Version with issue: 4.7.0 Service Release 5
- Last known good version: -
- IDE: irrelevant
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: irrelevant
  - UWP:  irrelevant
- Android Support Library Version: irrelevant
- Nuget Packages: Xamarin.Forms
- Affected Devices: All Apple Devices

### Screenshots

![XamarinBug_EditorPlaceholder](https://user-images.githubusercontent.com/17462039/90982967-11232a00-e56b-11ea-9c33-181f0283b254.png)

### Reproduction Link

https://github.com/acuntex/XamarinBug_EditorPlaceholder

### Workaround

None for now.

**Comment by samhouts** [comment]
closed by #11887
