### ISSUE TITLE
[Bug] GradientStop binding color isn't working

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#11898]
### Description
Trying to bind a color to GradientStop isn't working as expected 

<LinearGradientBrush StartPoint="0,0" EndPoint="1,1">
                                        <GradientStop Color="{Binding BackgroundGradientStart}" Offset="0" />
                                        <GradientStop Color="{Binding BackgroundGradientEnd}" Offset="1"/>
</LinearGradientBrush>

XF Version: 4.8

**Comment by mfeingol** [comment]
@rmarinho:

I just tried this out with the XF 5.0 release, using XAML along these lines:

```xml
<Grid.Background>
            <LinearGradientBrush StartPoint="0,0.5" EndPoint="1,0.5">
                <GradientStop Color="{Binding Color, Converter={StaticResource ColorConverter}}" Offset="0" />
                <GradientStop Color="Transparent" Offset="1.5" />
            </LinearGradientBrush>
        </Grid.Background>
```

The Color property is a string, and its value is set during the course of execution. However, the value passed into the converter is always null. Is that a known issue?

Thanks.

**Comment by Aston13** [comment]
The issue seems to lie in finding the binding path.

For anyone encountering this issue, try to explicitly set the path and then bind to that by reference like I have here with 'siteOpType'. My StateColor property is of type Xamarin.Forms.Color.

```
                <Frame x:DataType="models:BindableSiteOperation" x:Name="siteOpType"
                       BackgroundColor="{Binding StateColor}"
                       Padding="0" 
                       CornerRadius="15">
                    <Grid RowDefinitions="Auto,*"
                          BackgroundColor="{AppThemeBinding Light={StaticResource BackgroundOverlayColorLight}, Dark={StaticResource BackgroundOverlayColorDark}}" 
                          Padding="5">
                        
                        <Grid.ColumnDefinitions HorizontalContentAlignment="Stretch">
                            <ColumnDefinition Width="*"/>
                            <ColumnDefinition Width="*"/>
                        </Grid.ColumnDefinitions>

                        <!--[ Site Icon], [ Site Name ]-->
                        <Grid Grid.ColumnSpan="2" ColumnDefinitions="30,*" Margin="-5">
                            <Grid.Background>
                                <LinearGradientBrush StartPoint="0,0" EndPoint="1,0">
                                    <GradientStop Color="{Binding Source={x:Reference siteOpType}, Path=BindingContext.StateColor}" Offset="0.3">
                                    </GradientStop>
                                    <GradientStop Color="Transparent" Offset="1.0"></GradientStop>
                                </LinearGradientBrush>
                            </Grid.Background>
```

**Comment by ipon85new** [comment]
Так же столкнулся с этим багом. Решение было добавить нужный цвет в словарь статических ресурсов, и использовать чрез биндинг его

`   var neededColor = Color.Red;
   Application.Current.Resources.Add("NeededColor", neededColor );`

`<StackLayout.Background>
                                                                    <LinearGradientBrush EndPoint="1,0">
                                                                        <GradientStop Color="{x:StaticResource NeededColor}" Offset="0.1" />                                                                        
                                                                        <GradientStop Color="White" Offset="1.0" />
                                                                    </LinearGradientBrush>
                                                                </StackLayout.Background>`
