### ISSUE TITLE
Do we have any free nuget package for OCR in xamarin forms ?

### ISSUE THREAD

**Issue by viveknegi51288** [xamarin/Xamarin.Forms#11902]
## Summary
Why we don't have ocr package in xamarin forms yet. Its been a long time for xamarin forms in market.. Can we have this package?

**Comment by jsuarezruiz** [comment]
@viveknegi51288 You can find different options from using Azure Cognitive Services to options using BlinkID SDK, Tesseract OCR, etc.

**Comment by viveknegi51288** [comment]
BlinkID sdk is paid... I am looking for any free nuget package... and Tesseract OCR result is not correct....

**Comment by themronion** [comment]
@viveknegi51288 check out this one https://github.com/Kawaian/OpenCvSharp

**Comment by viveknegi51288** [comment]
@themronion  Thanks for sharing but its also support windows and android... .I want thats support android and ios.
