### ISSUE TITLE
Path.Fill and Path.Stroke not working when set with DynamicResource

### ISSUE THREAD

**Issue by KaeTar** [xamarin/Xamarin.Forms#11907]
### Description
I have quite a few paths in my application.  When I upgraded from Xamarin.Forms 4.7.0.1260 to 4.8.0.1269 all of my paths disappeared and were no longer painting.   I tracked it down to the use of Fill="{DynamicResource xxxx}" and Stroke="{DynamicResource xxxx}".   I am using a resource dictionary for colors that gets swapped out when the theme changes.  If I set the path or the stroke with a dynamic resource that is either a Color or a SolidColorBrush there are no errors however it does not set the color at all and the path never renders visible.    If I set the Fill or Stroke with a static color like Fill="DarkBlue" it works fine.   I am rolling back as this is not going to work for me.

### Steps to Reproduce

1. Create a ResourceDictionary with an entry for <SolidColorBrush x:Key="myPathColor">DarkBlue</SolidColorBrush>
2. Load that dictionary in the app.xaml
3. Create a Path and set the Fill="{DynamicResource myPathColor}"
4. Notice that the color never gets applied
5. Set the path parameter to Fill="DarkBlue" 
6. Notice that it works fine when set directly

### Expected Behavior
I would expect that using a SolidColorBrush from a resource dictionary with DynamicResource would correctly apply the color like it does everywhere else.

### Actual Behavior
Color is never applied and path remains invisible.

### Basic Information

- Version with issue:  4.8.0.1269
- Last known good version:  4.7.0.1260
- IDE:  Visual Studio 2019 16.7.2
- Platform Target Frameworks: 
  - iOS:  13.6
  - Android: 9.0 api 28
  - UWP:  NA

**Comment by jsuarezruiz** [comment]
Is the same issue or related with:

https://github.com/xamarin/Xamarin.Forms/issues/11691
https://github.com/xamarin/Xamarin.Forms/issues/11911

**Comment by shalinasanga** [comment]
is this fixed ? tried on Xamarin.Forms 5.0.0.1709-pre4 not working with Binding
`  <Path  HorizontalOptions="Center" VerticalOptions="Center" Fill="{Binding StatusColor}"
                                      Stroke="Black"     StrokeThickness="1"      Aspect="Uniform" HeightRequest="38" WidthRequest="38"
                                      Data="M 100 100 a 50 50 0 1 0 0.00000001 0 "/>`

**Comment by sthch** [comment]
> is this fixed ? tried on Xamarin.Forms 5.0.0.1709-pre4 not working with Binding
> ` <Path HorizontalOptions="Center" VerticalOptions="Center" Fill="{Binding StatusColor}" Stroke="Black" StrokeThickness="1" Aspect="Uniform" HeightRequest="38" WidthRequest="38" Data="M 100 100 a 50 50 0 1 0 0.00000001 0 "/>`

I've got the same problem, Xamarin.Forms 5.0.0.1709-pre4 
`<Ellipse WidthRequest="6" HeightRequest="6" HorizontalOptions="Center" VerticalOptions="Start" Stroke="{StaticResource AccentColor}" />`

**Comment by KaeTar** [comment]
> is this fixed ? tried on Xamarin.Forms 5.0.0.1709-pre4 not working with Binding
> ` <Path HorizontalOptions="Center" VerticalOptions="Center" Fill="{Binding StatusColor}" Stroke="Black" StrokeThickness="1" Aspect="Uniform" HeightRequest="38" WidthRequest="38" Data="M 100 100 a 50 50 0 1 0 0.00000001 0 "/>`

One of the big changes I noticed was that Stroke and Fill changed from Color to SolidColorBrush.   Are you trying to bind to a Color or a SolidColorBrush?

**Comment by sthch** [comment]
> > is this fixed ? tried on Xamarin.Forms 5.0.0.1709-pre4 not working with Binding
> > ` <Path HorizontalOptions="Center" VerticalOptions="Center" Fill="{Binding StatusColor}" Stroke="Black" StrokeThickness="1" Aspect="Uniform" HeightRequest="38" WidthRequest="38" Data="M 100 100 a 50 50 0 1 0 0.00000001 0 "/>`
> 
> One of the big changes I noticed was that Stroke and Fill changed from Color to SolidColorBrush. Are you trying to bind to a Color or a SolidColorBrush?

Yes, I'm trying to bind it to a Color.
Change the code as followings and it works.
`<Ellipse WidthRequest="6" HeightRequest="6" HorizontalOptions="Center" VerticalOptions="Start">
    <Ellipse.Stroke>
        <SolidColorBrush Color="{StaticResource AccentColor}" />
    </Ellipse.Stroke>
</Ellipse>`

**Comment by shalinasanga** [comment]
> > is this fixed ? tried on Xamarin.Forms 5.0.0.1709-pre4 not working with Binding
> > ` <Path HorizontalOptions="Center" VerticalOptions="Center" Fill="{Binding StatusColor}" Stroke="Black" StrokeThickness="1" Aspect="Uniform" HeightRequest="38" WidthRequest="38" Data="M 100 100 a 50 50 0 1 0 0.00000001 0 "/>`
> 
> One of the big changes I noticed was that Stroke and Fill changed from Color to SolidColorBrush. Are you trying to bind to a Color or a SolidColorBrush?

tried using SolidColorBrush as below, no luck. StatusColor returns hex
`<Path Stroke="Black" StrokeThickness="1" Aspect="Uniform" HeightRequest="35" WidthRequest="35"
                  Data="M 100 100 a 50 50 0 1 0 0.00000001 0 ">
                <Path.Fill>
                    <SolidColorBrush Color="{Binding StatusColor}"/>
                </Path.Fill>
            </Path>`

**Comment by AdrianoRochedo** [comment]
not working on Forms 5.0.0.1931 !!!

**Comment by Jack-Paul** [comment]
Still, the issue is not fixed, I have checked with 5.0.0.2012.
when I bind the path fill color or stroke color to a property, the path disappears.
I also tried using SolidColorBrush, still no luck.

Please fix this issue or provide some workaround!!!

**Comment by JimmyKDev** [comment]
I also have 5.0.0.2012 installed. Binding Stroke and Fill to properties is not working e.g. Fill={Binding ShapeFillColor}

**Comment by EmilAlipiev** [comment]
why was that closed? it is not working.

**Comment by Aston13** [comment]
Encountered this issue today with binding a color to a Line Stroke:

```
    string StateColor = "Green";

    <Line Stroke="{Binding StateColor}" Y1="100" StrokeThickness="5"/>
```

Line does not appear to be visible. However, setting the string directly will work:
```  
    <Line Stroke="Green" Y1="100" StrokeThickness="5"/>
```

**Comment by lperezj** [comment]
I have the same problem. I dont know why its Closed. ???¿?¿? becouse its not working.

<Style x:Key="StatusIconBase"
           TargetType="Path">
        <Setter Property="Fill"
                Value="{StaticResource SystemMessagesHistoryGridTitleTextColor}"/>

I try in the same ResourceDictionary or in other xaml but is not working.

 <Color x:Key="SystemMessagesHistoryGridTitleTextColor">#FF787878</Color>

and with ColorBrush

**Comment by Jack-Paul** [comment]
Why people closing this if it's still not fixed.

**Comment by Jack-Paul** [comment]
Opened as a new bug here.
https://github.com/xamarin/Xamarin.Forms/issues/14418

**Comment by Januplus** [comment]
issue still not fixed
