### ISSUE TITLE
[Bug] Brushes can't use DynamicResource

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11911]
Seems as the brushes API ignores any DynamicResource.

Repro:
1) Define a color, say
```xaml
    <Color
        x:Key="MyColor">Red</Color>
```
in a theme XAML file.

2) Set up a page. To make sure the bg color works, assign it as its bg color as a dynamic resource:
```xaml
BackgroundColor="{DynamicResource MainPageBackgroundColor}"
```

3) Set up a brush and draw with it somewhere, for example:
```xaml
        <BoxView BackgroundColor="Yellow">
                <BoxView
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
                    <BoxView.Background>
	                    <LinearGradientBrush
		                    StartPoint="0.5, 0" EndPoint="0.5, 1">
		                    <GradientStop Color="Green" Offset="0.0" />
		                    <GradientStop Color="{DynamicResource MyColor}" Offset="1.0" />
	                    </LinearGradientBrush>
                    </BoxView.Background>
                </BoxView>
        </BoxView>
```

Expected: The gradient box view should go from green to red.
Result: The gradient box goes from green to fully transparent, in this case green to yellow as that's the color shining through.
Workaround: Use StaticResource instead of a DynamicResource in brushes (but it makes theming/dark mode very hard).

**Comment by Tommigun1980** [comment]
I think this is the root cause of my report at https://github.com/xamarin/Xamarin.Forms/issues/11816, but I'm not 100% sure. But there's a good chance fixing this will fix https://github.com/xamarin/Xamarin.Forms/issues/11816 also.

**Comment by jsuarezruiz** [comment]
Is the same issue or related with https://github.com/xamarin/Xamarin.Forms/issues/11691

**Comment by StephaneDelcroix** [comment]
@jsauvexamarin DynamicResource require the BO to be correctly parented. I did a quick look, and I'm not finding the code that sets the BC to the GS, so it's unlikely that Bindings to GS works. do we have tests for that ?

**Comment by transis2** [comment]
Same problem to me

**Comment by AdrianoRochedo** [comment]
Ellipce.Fill with DynamicResource yet not working on Forms 5.0.0.1931 !!!

**Comment by Tommigun1980** [comment]
> Ellipce.Fill with DynamicResource yet not working on Forms 5.0.0.1931 on UWP !!!
> On Android .. Works

Hi. It's probably best for you to open a new ticket for that issue, and in it refer to this one as well.
Cheers.
