### ISSUE TITLE
[Enhancement] Editor: AutoSizeMinimumHeight and AutoSizeMaximumHeight

### ISSUE THREAD

**Issue by acuntex** [xamarin/Xamarin.Forms#11917]
## Summary
Xamarin introduced the property AutoSize on Editor at some point. The property is responsible for letting the Editor control grow if the text too long.
Unfortunately there is a limitation on the HeightRequest (which is understandable for a dynamically growing control) which means a developer cannot define a minimum or a maximum height.
A developer cannot define at the moment e.g. that his Editor control shows 3 lines by default and can grow up to 6 lines.
At the moment it means that the control can grow to infinity which makes the feature AutoSize not production ready imho.
Thus I am proposing two new properties called AutoSizeMinimumHeight and AutoSizeMaximumHeight which are the bounds in between the editor control can grow and shrink.

## API Changes

In order to facilitate the new AutoSize-Height api, two doubles are added to the Editor class.

    var editor = new Editor();
    editor.Text = "Test";
    editor.AutoSize = EditorAutoSizeOption.TextChanges;
    editor.AutoSizeMinimumHeight = 80; // new API
    editor.AutoSizeMaximumHeight = 160; // new API

or in xaml:
```
        <Editor Text="Test"
                AutoSize="TextChanges"
                AutoSizeMinimumHeight="80"
                AutoSizeMaximumHeight="160" />

```

## Intended Use Case
Basically every basic use case where you need a multi line text field that grow between a bound of min and max heights.

## Prototyping
I already created a prototype that's working on all platforms.

```
    public class CustomEditor : Editor
    {
        public static readonly BindableProperty AutoSizeMinimumHeightProperty = BindableProperty.Create(nameof(AutoSizeMinimumHeight), typeof(double), typeof(Editor), (double)-1, propertyChanged: (bindable, oldValue, newValue)
            => ((CustomEditor)bindable)?.InvalidateMeasure());
        public static readonly BindableProperty AutoSizeMaximumHeightProperty = BindableProperty.Create(nameof(AutoSizeMaximumHeight), typeof(double), typeof(Editor), (double)-1, propertyChanged: (bindable, oldValue, newValue)
            => ((CustomEditor)bindable)?.InvalidateMeasure());

        public double AutoSizeMinimumHeight
        {
            get => (double)GetValue(AutoSizeMinimumHeightProperty);
            set => SetValue(AutoSizeMinimumHeightProperty, value);
        }

        public double AutoSizeMaximumHeight
        {
            get => (double)GetValue(AutoSizeMaximumHeightProperty);
            set => SetValue(AutoSizeMaximumHeightProperty, value);
        }

        protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
        {
            SizeRequest sizeRequest = base.OnMeasure(widthConstraint, heightConstraint);
            if (AutoSize != EditorAutoSizeOption.TextChanges)
                return sizeRequest;
            double height = sizeRequest.Request.Height;
            if (AutoSizeMinimumHeight > 0)
                height = Math.Max(height, AutoSizeMinimumHeight);
            if (AutoSizeMaximumHeight > 0)
                height = Math.Min(height, AutoSizeMaximumHeight);
            return new SizeRequest(new Size(sizeRequest.Request.Width, height));
        }

    }

```

If it is ok with the Xamarin Team I would implement these minimally intrusive changes to the Editor control and create a pull request for XF 5.0.

**Comment by acuntex** [comment]
I might also note that this would also handle https://github.com/xamarin/Xamarin.Forms/issues/10689 and https://github.com/xamarin/Xamarin.Forms/issues/4972

**Comment by jsuarezruiz** [comment]
Thanks for the detailed proposal.

**Comment by MitchBomcanhao** [comment]
Should the minimum/maximum height be calculated in relation with the text line height, instead of an arbitrary pixel count?
Ie I want to show a minimum of 3 lines and a maximum of 10.

**Comment by acuntex** [comment]
@MitchBomcanhao It depends on the use case.
If you always want to make sure to show full lines then definitely.
But it's also possible that you have design constraints that make it necessary to use height expressions. 

When using lines you definitely have to make platform specific changes, e.g. on iOS you would have to use `Control.Font.LineHeight` to calculate the height.

**Comment by JuanuMusic** [comment]
The proposed prototype doesn't work on XF 4.8 (tested on android). Maybe custom rendering is required?

**Comment by xamiell** [comment]
This properties AutoSizeMinimumHeight and AutoSizeMaximumHeight are pretty useful

**Comment by angelru** [comment]
@acuntex
 I'm testing your code and it works fine on Android, on iOS 15 (simulator) it doesn't respect the `AutoSizeMaximumHeight `with `Visual="Material"`

**Comment by angelru** [comment]
Hello, @acuntex 

If we apply the `Visual="Material"` styles to the editor, `AutoSizeMinimumHeight `and `AutoSizeMaximumHeight `do not work on iOS 15

**Comment by jfversluis** [comment]
@acuntex thanks for the detailed proposal! Love it! Unfortunately we can't make this happen anymore for Xamarin.Forms, but if you're still willing and able I would love to discuss this for .NET MAUI. Feel free to open an issue there with this feature request and maybe add some new insights you might have in the time being.

Thanks!
