### ISSUE TITLE
4.8.0 Breaks OnAppearing in Tabbed Navigation, and also HasUnevenRows in ListView

### ISSUE THREAD

**Issue by neoviz** [xamarin/Xamarin.Forms#11916]
### Description
I have an App that was performing perfectly until a recent Xamarin Forms update to 4.8.0; After that update, two bugs with a long history in Xamarin Forms were reintroduced and broke the app. ie:

In a tabbed navigation form, OnAppearing no longer fired correctly when navigating between tabs.
In the ListView, HasUnevenRows was also no longer working, resulting in wrapping text overrunning into the next cell.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version: I was able to revert to 4.7.0.1260 and the issues resolved (whew)
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iOS

**Comment by jsuarezruiz** [comment]
The TabbedPage issue could be the same as: https://github.com/xamarin/Xamarin.Forms/issues/11809
Could you describe better the behavior on TabbedPage?, OnAppearing is only invoked the first time etc?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
