### ISSUE TITLE
Xamarin.Forms.InvalidNavigationException: 'Ancestor must be provided for all pushes except first'

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#11929]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1157985/xamarinformsinvalidnavigationexception-ancestor-mu.html)._

---
[regression] [worked-in:4.7]
Xamarin.Forms.InvalidNavigationException: 'Ancestor must be provided for all pushes except first'

After upgrade to Xamarim Forms v: 4.8.0.1269

---
#### Feedback Bot on 8/21/2020, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Enbi Zhang Zhang [MSFT] on 8/24/2020, 00:07 AM: 

<p>Thanks for your feedback.<br>
Can you provide a steps for us to help us reproduce your issue?</p>
<p>Why do we ask for more info?<br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our guidelines(<a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion</a>), you can get tips on how to provide clear and simple reproducible steps.</p>

#### Feedback Bot on 8/24/2020, 07:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we have a sample where reproduce the issue?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
