### ISSUE TITLE
[Bug] Android HorizontalOptions to CenterAndExpand not Expand for Pickers

### ISSUE THREAD

**Issue by huangjinshe** [xamarin/Xamarin.Forms#11920]
### Description
`HorizontalOptions="StartAndExpand"` and `HorizontalOptions="CenterAndExpand"` all can't expand the pickers. only `HorizontalOptions="FillAndExpand"` worked. especially if I want the content of Pickers align to center but I can't now.

### Steps to Reproduce

Go to download [Oybab Trading System](https://github.com/oybab/TradingSystem).
Open and Run Android project.
Go to "Setting" on the Login page, 
Test the picker which use for change language.(modify the code of picker : HorizontalOptions to "CenterAndExpand" before test)

### Expected Behavior
Pickers content should display on center and Expand

![002](https://user-images.githubusercontent.com/3822799/91204110-2b5d3380-e736-11ea-88e2-e325547c0036.png)

### Actual Behavior
Pickers content display on center but not Expand

![001](https://user-images.githubusercontent.com/3822799/91204127-2f895100-e736-11ea-8c39-2314c6038461.png)

### Basic Information

Version with issue:v4.8
Last known good version:-
IDE:Visual Studio 2019
Platform Target Frameworks:
Android: 10

**Comment by jsuarezruiz** [comment]
@huangjinshe This is the Picker from the screenshot https://github.com/oybab/TradingSystem/blob/d985a1dd3d58280086098d8a54b1c1c020ed1de8/TradingSystemX/TradingSystemX/TradingSystemX/Pages/Controls/SettingPage.xaml#L19?

**Comment by huangjinshe** [comment]
@jsuarezruiz , What do you mean? I don't understand.

**Comment by huangjinshe** [comment]
@jsuarezruiz , The screenshot which I uploaded in here before, I just modified it by PS for let you know the problem. You can also change the code and run for test that.(the place that you pointed)

**Comment by rmarinho** [comment]
Hi can you add a smaller reproduction ?

**Comment by huangjinshe** [comment]
@rmarinho , Nope. You can also create a new page, put a Pickers only for test.

**Comment by rmarinho** [comment]
Hi @huangjinshe  i tried to reproduce and wasn't able.. i tried sample code below , sample is attached. Please change it to repro your issue. 

Thanks

```
<StackLayout Margin="10, 20, 10, 10"  Orientation="Vertical">

        <StackLayout>
            <Label HorizontalOptions="Start" Text="Label 1"  Margin="6,0,0,0" />

            <Label HorizontalOptions="Start" Text="Label 2" Margin="0,20,0,0"/>
            <Entry Text="ServerIP"/>

            <Label HorizontalOptions="Start" Text="Language"/>
            <Picker HorizontalOptions="FillAndExpand">
                <Picker.Items>
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                </Picker.Items>
            </Picker>

            <StackLayout Orientation="Horizontal">
                <Label HorizontalOptions="Start" Text="Language 2" VerticalOptions="Center"/>
                <Picker HorizontalOptions="FillAndExpand" VerticalOptions="Center">
                    <Picker.Items>
                        <x:String>Item 1</x:String>
                        <x:String>Item 2</x:String>
                        <x:String>Item 3</x:String>
                    </Picker.Items>
                </Picker>
            </StackLayout>
          
            <Grid  HorizontalOptions="Center"  VerticalOptions="End" Margin="0, 20, 0, 50">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition/>
                    <ColumnDefinition Width="0.5*"/>
                    <ColumnDefinition/>
                </Grid.ColumnDefinitions>
                <Button Grid.Column="0" HorizontalOptions="End" Command="{Binding BackCommand}" Text="Back"  />
                <Button Grid.Column="2" HorizontalOptions="Start" Command="{Binding ChangeCommand}" Text="Change"/>
            </Grid>
        </StackLayout>
    </StackLayout>
``` 
[App13.zip](https://github.com/xamarin/Xamarin.Forms/files/5267557/App13.zip)

![image](https://user-images.githubusercontent.com/1235097/94003475-2ae6a580-fd93-11ea-8603-c1fbf223e3e5.png)

**Comment by huangjinshe** [comment]
@rmarinho , I do not understand why you do it like that. This issue title is very clear, it is about : `HorizontalOptions` to `CenterAndExpand` not get the result what we want...What are you doing....

You should try to change  `HorizontalOptions` to `CenterAndExpand` (for Pickers), and compare the Expected Behavior of this issue.

**Comment by rmarinho** [comment]
sorry @huangjinshe  you are right i was trying other way to get what you want.

 Why can´t you use FillAndExpand and set `HorizontalTextAlignment="Center"`? 

i think that way you get what you want.

![image](https://user-images.githubusercontent.com/1235097/94007492-7439f380-fd99-11ea-874a-7135ddbf121b.png)

```
StackLayout>
            <Label HorizontalOptions="Start" Text="Label 1"  Margin="6,0,0,0" />

            <Label HorizontalOptions="Start" Text="Label 2" Margin="0,20,0,0"/>
            <Entry Text="ServerIP"/>

            <Label HorizontalOptions="Start" Text="Language"/>
            <Picker HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center">
                <Picker.Items>
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                </Picker.Items>
            </Picker>

            <StackLayout Orientation="Horizontal">
                <Label HorizontalOptions="Start" Text="Language 2" VerticalOptions="Center"/>
                <Picker HorizontalOptions="FillAndExpand" VerticalOptions="Center" HorizontalTextAlignment="Center">
                    <Picker.Items>
                        <x:String>Item 1</x:String>
                        <x:String>Item 2</x:String>
                        <x:String>Item 3</x:String>
                    </Picker.Items>
                </Picker>
            </StackLayout>
          
            <Grid  HorizontalOptions="Center"  VerticalOptions="End" Margin="0, 20, 0, 50">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition/>
                    <ColumnDefinition Width="0.5*"/>
                    <ColumnDefinition/>
                </Grid.ColumnDefinitions>
                <Button Grid.Column="0" HorizontalOptions="End" Command="{Binding BackCommand}" Text="Back"  />
                <Button Grid.Column="2" HorizontalOptions="Start" Command="{Binding ChangeCommand}" Text="Change"/>
            </Grid>
        </StackLayout>
    </StackLayout>
```

I recommend you to read https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options#expansion Expand is a little weird some times, check the note 

![image](https://user-images.githubusercontent.com/1235097/94007317-2de49480-fd99-11ea-9be1-8b0b2aa40a60.png)

**Comment by huangjinshe** [comment]
It worked, I thought `Center` is the default value of `HorizontalTextAlignment` before. If this is the recommend way to use, I use this way. Thanks.
