### ISSUE TITLE
After VS update UWP MSBUILD output crashes

### ISSUE THREAD

**Issue by Legolas87** [xamarin/Xamarin.Forms#11925]
After VS update to 16.7.2 version UWP MSBUILD output crashes, a dump file attached.
It worked in more with recent VS versions

and here is event log error:
Faulting application name: loyhutz.mobile.UWP.exe, version: 11.170.2264.1, time stamp: 0x59d05e5b
Faulting module name: KERNELBASE.dll, version: 10.0.18362.997, time stamp: 0x91b9349a
Exception code: 0xe0434352
Fault offset: 0x000000000003a719
Faulting process ID: 0x7084
Faulting application start time: 0x01d67b7a50beb85a
Faulting application path: C:\Program Files\WindowsApps\22eecf0e-f17b-4e14-90bb-9c295c03d8df_11.170.2264.1_x64__fvf8hs1a2nn1p\loyhutz.mobile.UWP.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: b6467bc9-b58b-4e3e-9b73-835863df257b
Faulting package full name: 22eecf0e-f17b-4e14-90bb-9c295c03d8df_11.170.2264.1_x64__fvf8hs1a2nn1p
Faulting package-relative application ID: App

[loyhutz.mobile.UWP.exe.28804.zip](https://github.com/xamarin/Xamarin.Forms/files/5128533/loyhutz.mobile.UWP.exe.28804.zip)

**Comment by jsuarezruiz** [comment]
I have done several tests after updating Visual Studio 16.7.2, and the UWP Xamarin.Forms Apps continue working:
<img width="2019" alt="Captura de pantalla 2020-08-26 a las 13 39 29" src="https://user-images.githubusercontent.com/6755973/91299511-030b1e80-e7a2-11ea-8b3e-036f44600046.png">

Does it happen with any App or a specific one? If you create a new App from a template, does it work?

I have not seen anything specific in the dump, will try to find something.

**Comment by Legolas87** [comment]
well, running app from VS works, it works also when i package it with VS.
It doesbt work when msbuild works on team city:

    `   <MSBuild Projects="$(SourcePath)\UWP\mobile.UWP.csproj" Properties="OutputPath=$(UwpOutputPath);AppxBundlePlatforms=x86|x64|ARM;AppxBundle=Always;BuildAppxUploadPackageForUap=true;AppxPackageSigningEnabled=$(AppSigningFlag);AppxSymbolPackageEnabled=false;Configuration=Release;DebugType=full"/>`

please note that the same code works right now when it executed under older version of VS , i think 16.6.5

**Comment by MagicAndre1981** [comment]
> well, running app from VS works, it works also when i package it with VS.
> It doesnt work when msbuild works on team city:

```
Exception object: 0000022ddbc096e0
Exception type:   System.TypeLoadException
Message:          Could not find Windows Runtime type 'Windows.ApplicationModel.Resources.Core.ResourceManager'.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    0000006666178660 0000000000000000 System_Runtime_WindowsRuntime!System.Resources.WindowsRuntimeResourceManager.InitializeStaticGlobalResourceContext(Windows.ApplicationModel.Resources.Core.ResourceManager)+0x1
    0000006666178710 00007FFE2DD608BB System_Runtime_WindowsRuntime!System.Resources.WindowsRuntimeResourceManager.get_GlobalResourceContextBestFitCultureInfo()+0xb
    0000006666178740 00007FFE8D1BAB3E System_Private_CoreLib!System.Globalization.CultureInfo.GetCultureInfoForUserPreferredLanguageInAppX()+0x8e
    0000006666178790 00007FFE8D1BA993 System_Private_CoreLib!System.Globalization.CultureInfo.get_CurrentUICulture()+0x13
    00000066661787C0 00007FFE8D1C9C1D System_Private_CoreLib!System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)+0xcd
    0000006666178850 00007FFE8D1A16E7 System_Private_CoreLib!System.SR.InternalGetResourceString(System.String)+0x3a7
    00000066661788F0 00007FFE8D1A12E5 System_Private_CoreLib!System.SR.GetResourceString(System.String, System.String)+0x25
    0000006666178930 00007FFE8D1CA9DD System_Private_CoreLib!System.Exception.get_Message()+0x3d
    0000006666178960 00007FFE8D1CAFA7 System_Private_CoreLib!System.Exception.ToString(Boolean, Boolean)+0x27

StackTraceString: <none>
HResult: 80131522

```

Make sure the matching Windows 10 SDK is installed for your TargetVersion

**Comment by Legolas87** [comment]
thank @MagicAndre1981 for your reply, i will check, btw how did you get this clear error text, it was in dmp file?

**Comment by MagicAndre1981** [comment]
this is in the dmp, but I need the AMD64 mscordaccore.dll in version 4.6.25707.02 from that system to see more from the dmp.

so upload the DLL and the SOS.dll in same version from that system.

**Comment by PureWeen** [comment]
@Legolas87 are you seeing the same exception with just a UWP app? The exception seems like it's just a general exception with how the UWP app is being built. Let us know once you try what @MagicAndre1981 has indicated

**Comment by Legolas87** [comment]
the problem was related to the fact that we used vs build tools instead of vs , its fixed now so i am going to close this
