### ISSUE TITLE
[Bug] [iOS] When in CollectionView's ItemTemplate, the SwipeView emits swipe events together with scroll events

### ISSUE THREAD

**Issue by mduchev** [xamarin/Xamarin.Forms#11932]
### Description
On iOS, SwipeView, when in CollectionView's ItemTemplate, doesn't take all of the gestures during swipe and as soon as the user starts swiping, the CollectionView is very easily scrollable, which is annoying and is not the intended behavior. All apps with swipes done right don't emit multiple gestures during swiping. (e.g. the Mail app on iOS)

This is happening only on iOS. The SwipeView behaves correctly on Android.
I've attached both a sample project & a gif illustration of the issue.

### Steps to Reproduce
1. Create a CollectionView with a SwipeView in its ItemTemplate
2. Add many dummy rows so that the CollectionView can be scrolled
3. Try to swipe a row and at the same to scroll the CollectionView (swipe diagonally)

### Expected Behavior
The swipe gestures shouldn't fight for which event to be executed. As soon as the swipe starts, there shouldn't be any scrolling at all.

### Actual Behavior
The swipe gestures & the scroll gestures are happening simultaneously, which is very confusing and occasionally it's often not the indented behaviour that the user has been expecting.

### Basic Information
- Version with issue: 4.8.0.1269
- Last known good version: N/A
- IDE: Rider for macOS
- Nuget Packages: None
- Affected Devices: iOS devices

### Screenshots
![Aug-26-2020 19-51-56](https://user-images.githubusercontent.com/8217099/91333604-762e8800-e7d6-11ea-8c24-e6bf335f4114.gif)

### Reproduction Link
[DemoSwipeIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5131213/DemoSwipeIssue.zip)

### Workaround
No workaround.

**Comment by jsuarezruiz** [comment]
Related with #11651
