### ISSUE TITLE
[Bug] Snap Points not working in CollectionView with GridItemsLayout

### ISSUE THREAD

**Issue by missy-bowles** [xamarin/Xamarin.Forms#11938]
### Description
A CollectionView that uses a GridItemsLayout with SnapPointsType="Mandatory" does not have snap points and scrolling stops mid column on Android. iOS works as expected.

### Expected Behavior
CollectionView should use snap points

### Actual Behavior
CollectionView does not have snap points

### Basic Information

- Version with issue: Xamarin.Forms 4.6.0
- Last known good version: Unknown
- IDE: VS for Mac 8.7.3
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android

### Reproduction Link
 [SnapPointsRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/5132891/SnapPointsRepro.zip)

### Workaround
None that I know of

**Comment by jsuarezruiz** [comment]
Verified. Happens with Xamarin.Forms 4.6, 4.7 and 4.8. Dynamically updating the `SnapPointsType` value works fine.

**Comment by InquisitorJax** [comment]
@jsuarezruiz "Dynamically updating the SnapPointsType value works fine." - is that a work-around to the issue? If so, what does that mean (how to)?
