### ISSUE TITLE
[Bug] System.NullReferenceException when returning back from a list item in list view inside a tab view

### ISSUE THREAD

**Issue by losebyg** [xamarin/Xamarin.Forms#11945]
### Description
I get System.NullReferenceException when returning back from a list item in list view inside a tab view
### Steps to Reproduce

Note: Only tested on Android thus far
1.  Enter a list view item from the list view (which is in a tab view)
2.  navigate back to the list view

### Expected Behavior
No exception occurs

### Actual Behavior
System.NullReferenceException occurs (See stack trace below)

### Basic Information

- Version with issue: 4.7.0.1080
- Last known good version: First time occurrence.
- IDE: Microsoft Visual Studio Enterprise 2019 Version 16.6.5

- Platform Target Frameworks: 
  - Android: 7.0 
- Android Support Library Version: 
- Nuget Packages:
Prism Dryloc 7.2.0.1422
Xamarin Froms Maps 4.7.0.1080
Xamarin Forsm Material 4.7.0.1080
Fluent Validation 8.6.1
RG Plugins.Popups 2.0.0.3
Xamarin.Android.Support.CustomTabs 28.0.0.3
Xamarin.Android.Support.Design 28.0.0.3

- Affected Devices:

### Screenshots

08-28 12:24:37.616 D/AbsListView( 5592): viewType is heaer or footer
08-28 12:24:37.616 D/AbsListView( 5592): viewType is heaer or footer
08-28 12:24:37.617 D/AbsListView( 5592):  onsize change 
08-28 12:24:37.945 I/art     ( 5592): Starting a blocking GC Explicit
08-28 12:24:37.947 D/Mono    ( 5592): GC_BRIDGE waiting for bridge processing to finish
08-28 12:24:37.971 I/art     ( 5592): Explicit concurrent mark sweep GC freed 805(34KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 16MB/27MB, paused 565us total 25.269ms
08-28 12:24:37.973 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 7 objects 32783 opaque 12544 colors 7 colors-bridged 7 colors-visible 7 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.05ms tarjan 20.64ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.01ms cleanup 1.91ms
08-28 12:24:37.973 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 27.89ms
08-28 12:24:37.973 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 25.17ms, stw 25.85ms promoted 126K major size: 9824K in use: 8947K los size: 3072K in use: 2468K
08-28 12:24:38.248 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 0 objects 0 opaque 0 colors 0 colors-bridged 0 colors-visible 7 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.05ms tarjan 20.64ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.01ms cleanup 0.01ms
08-28 12:24:38.248 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 0.10ms
08-28 12:24:38.248 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 2.68ms, stw 3.20ms promoted 165K major size: 9984K in use: 9125K los size: 3072K in use: 2486K
08-28 12:24:38.430 D/ViewRootImpl@9e01734[MainActivity]( 5592): ViewPostImeInputStage processPointer 0
08-28 12:24:38.524 D/ViewRootImpl@9e01734[MainActivity]( 5592): ViewPostImeInputStage processPointer 1
08-28 12:24:38.542 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 0 objects 0 opaque 0 colors 0 colors-bridged 0 colors-visible 7 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.05ms tarjan 20.64ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.01ms cleanup 0.01ms
08-28 12:24:38.542 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 0.13ms
08-28 12:24:38.542 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 2.13ms, stw 2.79ms promoted 22K major size: 10016K in use: 9149K los size: 3072K in use: 2486K
08-28 12:24:38.761 D/InputMethodManager( 5592): HSI from window - flag : 0 Pid : 5592
08-28 12:24:38.875 I/art     ( 5592): Starting a blocking GC Explicit
08-28 12:24:38.905 I/art     ( 5592): Explicit concurrent mark sweep GC freed 150(5KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 16MB/27MB, paused 522us total 30.112ms
08-28 12:24:38.906 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 1 objects 1 opaque 0 colors 1 colors-bridged 1 colors-visible 1 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.04ms tarjan 0.00ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.02ms
08-28 12:24:38.906 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 31.18ms
08-28 12:24:38.906 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 2.10ms, stw 2.69ms promoted 17K major size: 10016K in use: 9166K los size: 3072K in use: 2486K
08-28 12:24:39.196 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 0 objects 0 opaque 0 colors 0 colors-bridged 0 colors-visible 1 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.04ms tarjan 0.00ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.01ms
08-28 12:24:39.196 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 0.09ms
08-28 12:24:39.197 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 1.99ms, stw 2.49ms promoted 17K major size: 10032K in use: 9184K los size: 3072K in use: 2486K
08-28 12:24:39.517 D/ViewRootImpl@9e01734[MainActivity]( 5592): ViewPostImeInputStage processPointer 0
08-28 12:24:39.521 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 0 objects 0 opaque 0 colors 0 colors-bridged 0 colors-visible 1 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.04ms tarjan 0.00ms scc-setup 0.02ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.01ms
08-28 12:24:39.521 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 0.13ms
08-28 12:24:39.521 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 1.95ms, stw 2.47ms promoted 15K major size: 10048K in use: 9199K los size: 3072K in use: 2486K
08-28 12:24:39.628 D/ViewRootImpl@9e01734[MainActivity]( 5592): ViewPostImeInputStage processPointer 1
08-28 12:24:39.647 D/InputMethodManager( 5592): HSI from window - flag : 0 Pid : 5592
08-28 12:24:39.860 I/art     ( 5592): Starting a blocking GC Explicit
08-28 12:24:39.883 D/Mono    ( 5592): GC_BRIDGE waiting for bridge processing to finish
08-28 12:24:39.901 I/art     ( 5592): Explicit concurrent mark sweep GC freed 489(21KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 16MB/27MB, paused 726us total 41.295ms
08-28 12:24:39.902 D/Mono    ( 5592): GC_TAR_BRIDGE bridges 4 objects 4 opaque 0 colors 4 colors-bridged 4 colors-visible 4 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.05ms tarjan 0.01ms scc-setup 0.01ms gather-xref 0.00ms xref-setup 0.03ms cleanup 0.17ms
08-28 12:24:39.902 D/Mono    ( 5592): GC_BRIDGE: Complete, was running for 42.53ms
08-28 12:24:39.902 D/Mono    ( 5592): GC_MINOR: (Nursery full) time 2.43ms, stw 13.34ms promoted 20K major size: 10064K in use: 9220K los size: 3072K in use: 2486K
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

### Workaround

None as yet

**Comment by jsuarezruiz** [comment]
@losebyg Just to be sure, you have a ListView in a tab using a **TabbedPage** and navigate to a detail page. Then, navigating back, get the crash, right?.

**Comment by jsuarezruiz** [comment]
I have created a sample trying to replicate the issue:

[Issue11945.zip](https://github.com/xamarin/Xamarin.Forms/files/5141701/Issue11945.zip)

But cannot reproduce the exception:

![issue11945](https://user-images.githubusercontent.com/6755973/91554193-f10ab680-e92e-11ea-98ba-68b1a0ebfc67.gif)

**Comment by losebyg** [comment]
Hi Thanks for the fast response. I forgot to mention that I am navigating to another list view 
EG TabView>ListView>ListView Error occurs when I go back to the main list view.
Hope this makes sense.

**Comment by losebyg** [comment]
short video attached. Thanks
[screencapture-1598617867352.zip](https://github.com/xamarin/Xamarin.Forms/files/5142037/screencapture-1598617867352.zip)

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
