### ISSUE TITLE
Xamarin - Menu Hamburger - Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;'

### ISSUE THREAD

**Issue by edujgomes5** [xamarin/Xamarin.Forms#11942]
**Development:**  
I created an App from scratch, directed it to an android version 4.2.2, the project opens normally.  
**Problem Found:**  
When implementing the Hamburger menu with masterdatail and a details page or even breaking app, the following error returns:Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;'  
My MainPage use this stretch to define the MasterDetail e a Detail:  
this.Master = new Views.MasterMenu();  
this.Detail = new NavigationPage(new Views.ListaMesas());  
App.MasterDetail = this;  
**Curiosity:**  
When I run it directed to version 5.0 onwards, it works perfectly. The problem is that I have some app's on clients that use tablets in this version 4.2.2 and the version compiled in Nov / 2019 worked perfectly, now that I needed to make an update, I can't run the app on the client's tablet. Any help is welcome, if there is a package that serves to load this menu, or an alternative way to have this menu, other than by masterdetail, it also serves me.  
**Information and settings:**
Versão Xamarim: 16.7.000.440  
Versão Visual Studio: 16.7.2  
Tablet Positivo - Android 4.2.2  
**Final considerations**  
For the error to be simulated, it will be necessary to debug with a device with android below 5.0. I need it to work from version 4.0 onwards.  
Follows the new project created with some pages and the menu that causes the error mentioned in the title  
[App1.zip](https://github.com/xamarin/bugzilla-archives/files/5129823/App1.zip)

**Comment by themronion** [comment]
> Unfortunately the minimum supported version for Xamarin.Android is API-19 / 4.4. That method (`android.view.view.isAttachedToWindow`) was added to Android in API-19 / 4.4: https://developer.android.com/reference/android/view/View.html#isAttachedToWindow().
> 
> I'll transfer this to Xamarin Forms to see if they have any workarounds, but likely this is a feature that cannot be supported on earlier versions of Android.

+1, the 4.2 version is too low to work normally with Xamarin

**Comment by edujgomes5** [comment]
Good afternoon!

In reality, I don't use this command anywhere within my code. This error appears to me only when I build a menu (masterdetail), and I really need that menu in my app. Is there a library or package that I can use to do this in version 4.1 of android?


[cid:image001.jpg@01D5E1A1.D81CFBA0]



De: Pavlo Lukianets<mailto:notifications@github.com>
Enviado:sábado, 29 de agosto de 2020 11:26
Para: xamarin/Xamarin.Forms<mailto:Xamarin.Forms@noreply.github.com>
Cc:Eduardo Gomes<mailto:edujgomes5@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [xamarin/Xamarin.Forms] Xamarin - Menu Hamburger - Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;' (#11942)


Unfortunately the minimum supported version for Xamarin.Android is API-19 / 4.4. That method (android.view.view.isAttachedToWindow) was added to Android in API-19 / 4.4: https://developer.android.com/reference/android/view/View.html#isAttachedToWindow().

I'll transfer this to Xamarin Forms to see if they have any workarounds, but likely this is a feature that cannot be supported on earlier versions of Android.

+1, the 4.2 version is too low to work normally with Xamarin

**Comment by themronion** [comment]
@edujgomes5 try syncfusions navigation drawer, though not sure if it supports 4.1

**Comment by PureWeen** [comment]
As the comments have mentioned support level for Xamarin.Forms is 4.4+
