### ISSUE TITLE
[Bug] ClearButtonVisibility.Never does not take effect on UWP (2)

### ISSUE THREAD

**Issue by omghb** [xamarin/Xamarin.Forms#11946]
# Description

The issue [#8836 ClearButtonVisibility.Never does not take effect on UWP](https://github.com/xamarin/Xamarin.Forms/issues/8836) is not fixed.

### Steps to Reproduce

1. Clone https://github.com/omghb/XamarinUwpClearButtonVisibilityIssue 
2. Run UWP app
3. Add characters into the entries 

### Expected Behavior

In the "ClearButtonVisibility (Default)" and "ClearButtonVisibility (Never)" the clear button should not get visible.

### Actual Behavior

In the "ClearButtonVisibility (Default)" and "ClearButtonVisibility (Never)" the clear button gets visible as soon a character was entered and the entry has the focus.

### Basic Information

- Version with issue: "Xamarin.Forms" Version="4.8.0.1269"
- IDE: VS 2019 16.6.3
- Platform Target Frameworks: 
  - UWP:  SDK 10.0.18362.0

### Dirty Workaround
``` C#
[assembly: ExportRenderer(typeof(Entry), typeof(MyEntryRenderer))]
namespace MySample.UWP.Renderer
{
    public class MyEntryRenderer : EntryRenderer
    {
        public MyEntryRenderer()
        {
            ((IVisualNativeElementRenderer)this).ControlChanging += ControlChanging;
            ((IVisualNativeElementRenderer)this).ControlChanged += ControlChanged;
        }

        private void ControlChanging(object sender, EventArgs e)
        {
            if (Control != null)
            {
                Control.Loaded -= ControlLoaded;
            }
        }

        private void ControlChanged(object sender, EventArgs e)
        {
            if (Control != null)
            {
                Control.Loaded += ControlLoaded;
            }
        }

        private void ControlLoaded(object sender, RoutedEventArgs e)
        {
            if (Control is FormsTextBox x)
            {
                var m = typeof(FormsTextBox).GetMethod("ClearButtonVisibleChanged", BindingFlags.NonPublic | BindingFlags.Static);
                m?.Invoke(null, new object[] { x, null });
            }
        }
```

**Comment by bmacombe** [comment]
@samhouts I'll take a look this one, I just tested #8836 test page on the latest main and it's still good.  Might be an issue when the visibility is set initially in the XAML, my test page sets it after the control has been loaded.

**Comment by bmacombe** [comment]
Yep, PR on the way
