### ISSUE TITLE
Xamarin Forms show up error list control xaml [Bug] 

### ISSUE THREAD

**Issue by RobertoGFilho** [xamarin/Xamarin.Forms#11952]
Xamarin forms show up error on xaml list of objects : 

                <ct:TitleControl Title="teste" Grid.Row="0">
                    <ct:TitleControl.Buttons>
                        **<ct:IconButtonControl IconSource="Add"/>**
                    </ct:TitleControl.Buttons>
                </ct:TitleControl>

but it's abble to bild app

**Comment by hartez** [comment]
@RobertoGFilho What is the error? Also, which version of Xamarin.Forms are you using?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
