### ISSUE TITLE
Why don't you provide an accordian View as a separate component in xamarin forms, and I also would like to request to provide a position to set image left or right inside a button.

### ISSUE THREAD

**Issue by viveknegi51288** [xamarin/Xamarin.Forms#11956]
Please add a ImagePosition property to a button so that developer can set position of an image inside button left or right.

And Instead of Listview used as an accordian view with use of header, if we will have a separate view for accrodian view that it would make the life easy.

**Comment by themronion** [comment]
@viveknegi51288 about accordian view - check the Expander control. Will it fulfill your request?

**Comment by themronion** [comment]
And the left or right position is achieved easily by custom renderers i guess

**Comment by jsuarezruiz** [comment]
@viveknegi51288 You can modify the image position using ImagePosition property https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.button.buttoncontentlayout.imageposition?view=xamarin-forms

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
