### ISSUE TITLE
[Enhancement] Shell Search Results View is Too Narrow on Android

### ISSUE THREAD

**Issue by tomeverin** [xamarin/Xamarin.Forms#11960]
## Summary
The Shell Search results list view matches the width of the parent search text box. If there is a toolbar button then the search box is already too narrow for this to be functional and thus important text in the search results is truncated. On iOS the results are displayed full width.

![image](https://user-images.githubusercontent.com/24466690/91649339-14aa3a00-eab2-11ea-8de9-eea8f6398afa.png)

It appears that the relevant changes that would need to be made are in `Xamarin.Forms.Platform.Android/Renderers/ShellSearchView.cs` such that the `AppCompatAutoCompleteTextView` dropdown width is altered.

It does not appear to me that there is a way to achieve this with custom renderers

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
