### ISSUE TITLE
[Enhancement] Make implicit styles work with Elements

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#11961]
## Summary

https://github.com/xamarin/Xamarin.Forms/issues/11186 mentions that implicit styles do not work with FontImageSource because the latter does not derive from VisualElement.

I request that you either make this work for Elements (e.g. FontImageSource, TextCell), or generate at least a warning for style definitions that will never actually work. Otherwise, this will lead to great confusion for developers atempting to style their applications.

The workarounds for this are all fairly awkward and unnatural - e.g. creating derived types that are theme-aware.

## API Changes

This should work:

```xml
    <Style TargetType="FontImageSource" ApplyToDerivedTypes="True">
        <Setter Property="Color" Value="{AppThemeBinding Light={StaticResource Gray600}, Dark={StaticResource Gray300}}" />
    </Style>
```

## Intended Use Case

Styling an application, e.g. defining default light and dark mode colors for an application.

**Comment by mfeingol** [comment]
A simple repro in case you need it: https://github.com/mfeingol/repros/tree/master/FontImageSourceStyles

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
