### ISSUE TITLE
[Bug] [iOS][SwipeView] If Swipe view is disabled, tap gesture events are not firing

### ISSUE THREAD

**Issue by janithacw** [xamarin/Xamarin.Forms#11968]
### Description

On iOS, we are using the Swipe view for a Data Template in a Collection view. But If we disabled the swipe view for a line item, tap gesture also will not get fired for the line item. This is working fine on Android.
### Steps to Reproduce

1. Place a Swipe view in a collection view
2. Add a swipe item
3. Add a view to the content of the Swipe view
4. Add a Tap Gesture recognizer to the Content
5. Tap on line item

### Expected Behavior
The Tap gesture Tapped event or command should fire

### Actual Behavior
The tapped gesture event or command doesn't fire if you disabled the swipe view.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  iOS: 13.4
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.7.0.968
- Affected Devices: iPhones

### Screenshots

![swipeviewdemo](https://user-images.githubusercontent.com/52957500/91683270-c65c7000-eb71-11ea-80f3-2e4bf1ba774a.gif)

### Reproduction Link

[Sample Project](https://drive.google.com/file/d/1UyPKDjXY9sd26LBefNcAGx7puOvvZYC3/view?usp=sharing)

### Workaround

No

**Comment by cblanchard519** [comment]
Hey guys just wanted to let everyone know I found a workaround for this issue, you can add an event on SwipeStarted on the SwipeView and close the SwipeView if you don't want the user to have access to swipe functionality, this still leaves the tap event working.
