### ISSUE TITLE
[Bug] iOS Only- 'Cannot access a disposed object. Object name: 'WkWebViewRenderer'.'

### ISSUE THREAD

**Issue by bud4buddies** [xamarin/Xamarin.Forms#11962]
### Description
When a Page with WebView is revisited with fresh data is crashing. This does not happen when using Tabbed page.

### Steps to Reproduce
1.  Create a Search Page with a List of items 
2.  On click/tapping the item, navigate to details with a WebView.
3. Navigate back to the Search page
4. Click on the second item to get to the details page.
---> App crashes with  'Cannot access a disposed object. Object name: 'WkWebViewRenderer'.'

### Expected Behavior

App should not crash and display the new Html content in the WebView.

### Actual Behavior
System.ObjectDisposedException: 'Cannot access a disposed object.
Object name: 'WkWebViewRenderer'.'

### Basic Information

- Version with issue:  4.8.0.1269
- Last known good version:
- IDE: 2019
- Platform Target Frameworks: 
  - iOS:  13.6 (Probbably other versions too)

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by bud4buddies** [comment]
[XamarinBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/5212203/XamarinBugs.zip)
