### ISSUE TITLE
[Bug] TabbedPage inconsistent page apearing behaviour.

### ISSUE THREAD

**Issue by BaseCrusher** [xamarin/Xamarin.Forms#11974]
### Description
When using the Application.PageAppearing event when a TabbedPage is loaded, the even is called in an inconsistent way. 
The event is not triggert as it used to be where you get the event for the root Tabbed page once and then for each tab in order.
In addition to this, when the app goes into the background the event is triggert aswell and the order is of the pages is messed up. When the app enter the forground again, the order of the tabbs is messed up again.

If you need any further informations hit me up.

### Steps to Reproduce

1. Create a Forms App with a tabbed page with 2 or more tabs within navigation pages.
2. Upgrade Xamarin.Forms to 4.8
3. In the App.xaml.cs add an event listener to the OnAppearing event. And write out the page name.
4. Run the application.
5. Send the Application to the background through iOS notification center and back to forground. 

### Expected Behavior

- PageAppearing event not to be called, when the app goes into the background.

- Output of the start of the app to be:
[0:] Page RootTabbedPage
[0:] Page Page1
[0:] Page NavPage1
[0:] Page Page2
[0:] Page NavPage2
[0:] Page Page3
[0:] Page NavPage3

- Output when the app enters forground again to be:
Either:
[0:] Page RootTabbedPage
[0:] Page Page2
[0:] Page NavPage2
Or:
[0:] Page Page2
[0:] Page NavPage2
Or:
Nothing

### Actual Behavior

- PageAppearing event is called, when the app goes into the background.

- Output of the start of the app is:
[0:] Page Page1
[0:] Page NavPage1
[0:] Page RootTabbedPage
[0:] Page Page2
[0:] Page Page3

- Output when the app enters forground again is:
[0:] Page Page1
[0:] Page NavPage1
[0:] Page RootTabbedPage
[0:] Page Page2
[0:] Page Page3

### Basic Information

- Version with issue: 4.8
- Last known good version: 4.7
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android: Not fully testet but broken aswell

### Reproduction Link

https://github.com/BaseCrusher/XamarinFormsTabbedBug

**Comment by StephaneDelcroix** [comment]
> When using the Application.PageAppearing event when a TabbedPage is loaded, the even is called in an inconsistent way.
> The event is not triggert as it used to be where you get the event for the root Tabbed page once and then for each tab in order.

lifecycle events were changed in 4.8, so order might have changed

**Comment by BaseCrusher** [comment]
@StephaneDelcroix 
I did not deny that it was changed. It just behaving in a strange way.

Firstly when I navigate to TabbedPage I would like to know which page is currently displayed. 
So in my opinion the last page appearing event should be the one I'm currenty on.

For example Navigating to a TabbedPage where the first page is displayed, the last event call for Page appearing should be "first page".

Secondly It doesn't makes sense to me why the NavigationPage and the ContentPage are called in the PageAppearing event, when only the ContentPage of the other two pages are called when the TabbedPage is loaded. 
Either there the ContentPage and the NavigationPage PageAppearing event is called for all tabs or only for the one that is currently displayed. But not a mix that doesn't makes sense.

Lastly I put the the TabbedPage as my root Page and inside the TabbedPage all the other Pages are living. So the TabbedPage should be the first one to call the PageAppearing event. 

I'd be happy if you could give me an explanation to why this isn't is the case.
