### ISSUE TITLE
[Bug] FlexLayout Wrap isn't working

### ISSUE THREAD

**Issue by RobertoGFilho** [xamarin/Xamarin.Forms#11975]
Flexlayout Wrap=Wrap isn'tworking

**Comment by hartez** [comment]
@RobertoGFilho On which version of Xamarin.Forms are you seeing this problem?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
