### ISSUE TITLE
[Enhancement] Support BorderWidth/BorderThickness on Frame

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#11981]
## Summary
Support `BorderWidth` or `BorderThickness` on `Frame`. 

Same as [UWP Border.BorderThickness](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.border.borderthickness).

## API Changes
Add `BorderThickness` property on `Frame`.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
