### ISSUE TITLE
[iOS] ScaledScreenSize Height return wrong value when the Device Orientation is Faceup. 

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#11980]
### Description
ScaledScreenSize Height return the wrong value when the Device Orientation is Faceup.

### Steps to Reproduce

1. Run the attached sample in iOS
2.  Tap the button
3. See the ScaledScreenSize height return the wrong value in Faceup orientation.

### Expected Behavior
ScaledScreenSize height returns the correct value in Faceup orientation.

### Actual Behavior
ScaledScreenSize height returns the wrong value in Faceup orientation.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 
- IDE: visual studio 2019
- Platform Target Frameworks: 
  - iOS:  13.2
- Nuget Packages: 4.4.0.991265

### Reproduction Link

[ScreenSizeIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5154480/ScreenSizeIssue.zip)

### Workaround

it is working fine in 3.6.0.344457 version

**Comment by gokulsaravanan** [comment]
@samhouts Any update on this?

**Comment by KarthikRaja26** [comment]
@samhouts  any update on this ?

**Comment by jsuarezruiz** [comment]
@KarthikRaja26 The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13163/files

**Comment by Chansardrake** [comment]
Any update on this @samhouts
