### ISSUE TITLE
[Bug] XAML can't parse child classes in all cases

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11990]
Hi.

If you have a child class and want to instantiate one in XAML, the parser seems to fail. Other cases seem to be successful except when trying to instantiate such a class. Please see the following image of the parser error (please note that the actual error is at the plus sign, not at the closing tag for the array):

<img width="716" alt="Screenshot 2020-09-02 at 9 14 55" src="https://user-images.githubusercontent.com/60286968/91938689-1c115380-ecfd-11ea-85c5-74275e1ba4ac.png">

EnumValueToString is a class inside EnumToLocStringsConverter. Moving it outside the parent class makes XAML parse properly.

Xamarin.Forms 4.8.0.1364

**Comment by Tommigun1980** [comment]
To clarify, the + notation works everywhere else exception when used to create an instance of it. In the screenshot above it works as type for x:Array, but not when instantiating it.

**Comment by StephaneDelcroix** [comment]
Nested classes are not supported in XAML. Never were, in any flavour.
