### ISSUE TITLE
[Bug] Can't map directly to enum via x:Static syntax

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#11992]
I have an enum with all iso codes for languages, and made a converter that should enumerate an enum and map it to localised values. I want to bind it to a multi select input component I made, such as:

`ItemsSource="{Binding Source={x:Static shared:Language}, Converter={StaticResource MapLanguageEnumToLocStrings}}"`

Problem: "Error XFC0100: Syntax for x:Static is "[Member=][prefix:]typeName.staticMemberName""

Seems as x:Static can't access enumerations, just its values, so I can't do this. I'm not sure if this is a bug or a feature request, but I'm leaning towards a bug because shouldn't x:Static just refer to what I'm pointing it at?

Thanks.

**Comment by StephaneDelcroix** [comment]
I can't figure out what you're trying to do...

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
