### ISSUE TITLE
WPF version of Forms app fails to read response from HttpClient request

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12004]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1163596/wpf-version-of-forms-app-fails-to-read-response-fr.html)._

---
[severity:I'm unable to use this version of Visual Studio]
I have a Forms app that works fine in iOS, Android and UWP. I have built WPF version using the instructions at
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf
I am also using Forms 4.8.0.1269 and .Net Framework 4.8

When I attempted to read data from a URL using HttpClient, I get an exception

Exception thrown: 'System.TypeLoadException' in System.Net.Http.Formatting.dll
Method 'SerializeToStreamAsync' in type 'System.Net.Http.ObjectContent' from assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

I have attached the output log leading up to the excetion.

---
#### Feedback Bot on 8/26/2020, 10:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
