### ISSUE TITLE
OpenGLView XF sample problem

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12003]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1169428/openglview-xf-sample-problem.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
VS2019 , Xamarin Forms with shared Net standard 2.0 DLL.
I'd like to use OpenGLView in a ContentPage and all the code in Shared DLL.

1) Basic try, render loop empty, both android and Wpf project run:

```
     oGL.OnDisplay = r =>
            {
               
red += 0.01f;
                if (red >= 1.0f)     red -= 1.0f;
                green += 0.02f; 
                if (green >= 1.0f)     green -= 1.0f;
                blue += 0.03f;
                if (blue >= 1.0f)     blue -= 1.0f;

double seconds = (DateTime.Now - startTime). TotalSeconds;

// t from 0 to 1 every 5 seconds
                double t = (seconds % 5) / 5;

// Find a Xamarin.Forms color
                Color color = Color.FromHsla(t, 1.0, 0.5, 1.0);

// Set background color using OpenGL
              //  GL. ClearColor((float)color. R, (float)color. G, (float)color. B, 1.0f);
              //  GL. Clear((int)(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit));

};
```

2) Let's add some colors.. in the page behind code

```
using OpenTK.Graphics.ES10;
using System;
using Xamarin.Forms;
namespace oGlTest
{
    public partial class MainPage : ContentPage
    {
        float red, green, blue;
        DateTime startTime = DateTime.Now;
        public MainPage()
        {
            InitializeComponent();
            oGL.HasRenderLoop = true;
            oGL.OnDisplay = r =>
            {
              
red += 0.01f;
                if (red >= 1.0f)     red -= 1.0f;
                green += 0.02f; 
                if (green >= 1.0f)     green -= 1.0f;
                blue += 0.03f;
                if (blue >= 1.0f)     blue -= 1.0f;
                double seconds = (DateTime.Now - startTime). TotalSeconds;
                // t from 0 to 1 every 5 seconds
                double t = (seconds % 5) / 5;
                // Find a Xamarin.Forms color
                Color color = Color.FromHsla(t, 1.0, 0.5, 1.0);
                                // Set background color using OpenGL
                GL. ClearColor((float)color. R, (float)color. G, (float)color. B, 1.0f);
                GL. Clear((int)(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit));

};

}
    }
}
```

Android project WARNING;
NU1202	 OpenTK 3.0.1 is not compatible con monoandroid90 (MonoAndroid,Version=v9.0). Il pacchetto OpenTK 3.0.1 supporta: net20 (. NETFramework,Version=v2.0)	oGlTest.Android	

WPF project : no compile warning, but runtime error
System.DllNotFoundException: 'Impossibile caricare la DLL 'libGLES.dll': Impossibile trovare il modulo specificato. (Eccezione da HRESULT: 0x8007007E).'

Is there a way to use this basic OpenGL views ?

---
#### Feedback Bot on 9/1/2020, 02:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
@samhouts what's the status of OpenGLView ?

**Comment by jsuarezruiz** [comment]
What Xamarin.Forms version are you using?. I tried some samples and seems to work fine.
![wpf-opengl](https://user-images.githubusercontent.com/6755973/95094956-c4ff0400-072a-11eb-9deb-125b1e8025b0.gif)

You are trying to use OpenGL ES 1.0 in WPF. Could you use:

`using OpenTK.Graphics.OpenGL;`

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
