### ISSUE TITLE
Urho XF WPF sample problem

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12002]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1168989/urho-xf-wpf-sample-problem.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
I'm trying to use the URHO Xamarin Forms Sample
https://github.com/xamarin/urho-samples/tree/master/FormsSample

with xamarin forms WPF.

It compiles without error but nothing is visible.

The execution "hangs" here:

```
 urhoApp = await UrhoSurface.Show<Charts>(new ApplicationOptions(assetsFolder: default) { Orientation = ApplicationOptions.OrientationType.LandscapeAndPortrait });
```

---
#### Feedback Bot on 8/31/2020, 07:49 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
