### ISSUE TITLE
[Bug] Package name for Android gets distorted when adding numbers

### ISSUE THREAD

**Issue by a-einstein** [xamarin/Xamarin.Forms#12015]
When I change the package name for Android through the properties of the project in Visual Studio to something like 'Name.0.18' (with a version) it gets distorted to 'Name.x0.x18' in xml. Intention was to get a package like 'Name.0.18.apk'
Reopening the properties shows the distorted form too.

When manually correcting the xml to the the desired form, it gets distorted again when building in Azure. Then I have to correct it again there, or add the version to the bare name.

I don't see any purpose in that behaviour, it seems a bug to me.

**Comment by hartez** [comment]
This is as-designed. `Name.0.18` is an invalid value for a package name in Android; see https://developer.android.com/guide/topics/manifest/manifest-element.html#package 

From the docs: 

> However, individual package name parts may only start with letters.
