### ISSUE TITLE
[Bug] XamlC error : Sequence contains more than one element

### ISSUE THREAD

**Issue by darshanio** [xamarin/Xamarin.Forms#12025]
### Description

When we create a new property that hides the existing one in NavigationPage class, the compiler throws `XamlC error : Sequence contains more than one element`.

Create a new property that hides the current one in a the `CustomNavigationPage.cs` class like following:
```csharp
public class CustomNavigationPage : NavigationPage
{
    public static new readonly BindableProperty IconColorProperty = BindableProperty.CreateAttached("IconColor", typeof(Color), typeof(Page), Color.Default);

    public static void SetIconColor(Page page, Color barTintColor)
    {
        page.SetValue(IconColorProperty, barTintColor);
    }

    public static Color GetIconColor(Page page)
    {
        return (Color)page.GetValue(IconColorProperty);
    }
}
```

Use the attached property in MainPage.xaml and compile
```xaml
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="testxamarin.MainPage"
             xmlns:controls="clr-namespace:testxamarin.Controls"
             controls:CustomNavigationPage.IconColor="White">
</ContentPage>
```

### Steps to Reproduce

Project attached for reproduction

1. Create a new class, override NavigationPage
2. Create a new attached property, hide the base class one (say IconColor)
3. Use the new property in your `.xaml` page.

### Expected Behavior

No compile-time error

### Actual Behavior

Gets a compile-time error `XamlC error : Sequence contains more than one element`.

### Basic Information

- Version with issue: 4.8.0.1364
- Last known good version: 4.4.0.991537 (Currently upgrading to latest one)
- IDE: Visual Studio for Mac (8.7.4 build-38)

### Reproduction Link

[testxamarin_4.8.zip](https://github.com/xamarin/Xamarin.Forms/files/5173249/testxamarin_4.8.zip)

### Workaround

None

**Comment by StephaneDelcroix** [comment]
I don't get why you'd want to do that, and not use the BP already defined...

**Comment by darshanio** [comment]
I have implemented custom renderer for the navigation page in my application. Also I've changed the default value in the declaration.
