### ISSUE TITLE
[Bug] LinearGradientBrush becomes white when used in an ios 13 style modal dialog and swipe is used

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#12023]
When used as the background of an ios 13 modal dialog like this:

![image](https://user-images.githubusercontent.com/190756/92204403-ba2f2600-ee83-11ea-8368-74591836b2a9.png)

The lineargradient disappear as soon as you use the swipe gesture that moves the whole dialog up.
Before that it works as expected:

![image](https://user-images.githubusercontent.com/190756/92204495-e8ad0100-ee83-11ea-8bf8-82f4c2f9e82d.png)

### Steps to Reproduce

1. Create a page like this and open it using ShowPopup:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:iOsSpecific="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             x:Class="..."
             iOsSpecific:Page.ModalPresentationStyle="Automatic"
             iOsSpecific:Page.UseSafeArea="True"
             BackgroundColor="White"
             >
    <StackLayout Spacing="0">
        <StackLayout.Background>
            <LinearGradientBrush StartPoint="0,0.3" EndPoint="1,0.7">
                <LinearGradientBrush.GradientStops>
                    <GradientStop Offset="0" Color="#FFE6BF" />
                    <GradientStop Offset="1" Color="#FFF"/>
                </LinearGradientBrush.GradientStops>
            </LinearGradientBrush>
        </StackLayout.Background>

        <Grid VerticalOptions="FillAndExpand">
           ...
        </Grid>
    </StackLayout>
</ContentPage>
```

2. Show the page and use the bottom to top swipe gesture to slightly move the window.

### Expected Behavior
Background stays a gradient

### Actual Behavior
Background becomes white

### Basic Information

- Version with issue: 4.8
- Last known good version: none
- IDE:
- Platform Target Frameworks: 
  - iOS: 13  

### Workaround

None

**Comment by jsuarezruiz** [comment]
@softlion I have created a sample using Xamarin.Forms 4.8.0.1560 using your code  and test it in iOS 13 and 14:
[Issue12023.zip](https://github.com/xamarin/Xamarin.Forms/files/5457209/Issue12023.zip)

Cannot reproduce the issue:
![Issue12023](https://user-images.githubusercontent.com/6755973/97547713-6e55b480-19ce-11eb-9027-415c3fa4bf7c.gif)

Could you take a look to the attached sample?

**Comment by softlion** [comment]
I suppose you should add a content over the gradient. Try a collection view with a transparent background.

What i suppose is that the gradient does not redraw itself when a view with a transparent background is over it.

**Comment by jsuarezruiz** [comment]
I have updated the example adding a CollectionView with a transparent background on top, but I still cannot reproduce the issue, could you check the attached example to see the differences with your App or add an example where reproduce the issue?. Thanks.

![issue12023](https://user-images.githubusercontent.com/6755973/99514011-8f854180-298b-11eb-95c5-55603ce2c33b.gif)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
