### ISSUE TITLE
[Bug] Line Shape crash on iOS

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#12024]
When using a line shape to replace the separator of a collectionview item, previously drawns using a BoxView with a HeightRequest=1, the app crashes immedialty.

![image](https://user-images.githubusercontent.com/190756/92205717-89042500-ee86-11ea-8ba5-f06d05a47206.png)

### Steps to Reproduce

1. Sample code (simplified from real code):

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                     xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                     xmlns:xaml="clr-namespace:WzXam2.Xaml"
                     x:Class="...">

    <StackLayout Spacing="0" VerticalOptions="Fill">

        <Grid VerticalOptions="FillAndExpand">

            <CollectionView VerticalOptions="Fill" ItemsLayout="VerticalList" ItemSizingStrategy="MeasureFirstItem"
                    ItemsSource="...">

                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid>
                            <Grid Padding="0,15" RowDefinitions="*,*" ColumnDefinitions="40,*,*" ColumnSpacing="5">
                                <Label InputTransparent="True" Grid.Row="0" Grid.Column="1" Text="some text" />
                            </Grid>
                            <Line HeightRequest="1" VerticalOptions="End" BackgroundColor="#ccc" />
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
        </Grid>
    </StackLayout>
</ContentPage>
```

2.  Run

### Expected Behavior
don't crash

### Actual Behavior
Crash

### Basic Information

- Version with issue: 4.8 
- Last known good version: none
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS: 13.6  

### Workaround

none

**Comment by jsuarezruiz** [comment]
I have created a sample to try to reproduce the issue, but cannot reproduce it:
[Issue12024.zip](https://github.com/xamarin/Xamarin.Forms/files/5175307/Issue12024.zip)

<img width="402" alt="Captura de pantalla 2020-09-04 a las 16 10 41" src="https://user-images.githubusercontent.com/6755973/92248698-5c253180-eec9-11ea-82ee-6c6dc1b1d7cc.png">

Could you attach a zip with a sample where reproduce the issue?. Thanks in advance.

**Comment by softlion** [comment]
I tried a repro on an empty project, but can't manage to make it crash.
It still crash on the big project though.

![image](https://user-images.githubusercontent.com/190756/92269248-19bd1e00-eee4-11ea-87a0-d7438db22b3d.png)

**Comment by softlion** [comment]
Ok i found the issue. 
Some king of package downgrade of Xamarin Forms.
Closing.
