### ISSUE TITLE
 File name and line number are lost when ToString is called on an exception in the UWP project

### ISSUE THREAD

**Issue by john-larson** [xamarin/Xamarin.Forms#12035]
To reproduce the bug, add the following to App.xaml.cs in **UWP**:

```
        public App()
        {
            UnhandledException += App_UnhandledException;
            this.InitializeComponent();
            this.Suspending += OnSuspending;
        }

        private void App_UnhandledException(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e)
        {
            var newExc = new Exception("App_UnhandledException", e.Exception);
            System.Diagnostics.Debug.WriteLine(newExc.ToString());
        }
```

And throw new Exception(); anywhere in the .NET Standard project.

 If you put a break point next to the `System.Diagnostics.Debug.WriteLine(newExc.ToString());` line and debug, you will notice that the inner exception stacktrace shows the filename and line number in Visual Studio when you hover the cursor over `newExc` but `newExc.ToString()` does not contain this information.

**Comment by StephaneDelcroix** [comment]
this is not the right place to ask. googling gives me https://stackoverflow.com/questions/3328990/how-can-i-get-the-line-number-which-threw-exception
