### ISSUE TITLE
[Enhancement] Range Slider

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#12032]
That simple, Range slider which will be useful in filtering scenarios instead of having two pickers for min and max.

**Comment by pictos** [comment]
@MhAllan, this feature is implemented on [XCT project](https://github.com/xamarin/xamarincommunitytoolkit)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
