### ISSUE TITLE
[Bug] [Android & iOS] Can not reload Webview as soon as the internet is connected and webview.Reload() method is called

### ISSUE THREAD

**Issue by quanvm97** [xamarin/Xamarin.Forms#12034]
### Steps to Reproduce

The issue is reproduced on both android & iOS.
1. Load a any URL in webview while internet break
2. Connect to internet by turning on Wifi or Cellular 
3. Call reload method of Webview after clicking on "Reload" button
4. Two events are Navigating and navigated, both **dont respond** to change in state after webview.reload() called.

I also check that load a URL in available internet, and disconnect & press Reload button. --------> Two events are Navigating and navigated is respond
Then, connect to internet & press Reload button again -----> 2 events are respond

### Expected Behavior
The issue in step 4 should be worked

### Basic Information

- Version with issue: Xamarin.Forms v4.8.0.1364

### Code

This is webview:
```
<WebView x:Name="webView"
                         VerticalOptions="FillAndExpand"
                         Navigated="webviewNavigated" 
                         Navigating="webviewNavigating" />
```

And button to reload
```
<ImageButton Source="ic_reload"
                             BackgroundColor="Transparent"
                             Clicked="OnReloadButtonClicked">
```

Then, code behind:
```
#region OnReloadButtonClicked

        private void OnReloadButtonClicked(object sender, EventArgs e)
        {
                       webView.Reload();
        }

#endregion
```

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
