### ISSUE TITLE
[Enhancement] Add canDismiss parameter to DisplayPromptAsync method 

### ISSUE THREAD

**Issue by djordje200179** [xamarin/Xamarin.Forms#12033]
## Summary
It would be nice if developers could disable closing/dismissing a prompt dialog. So an user would need to enter a value and press `OK` button. `Cancel` button will be hidden or disabled. But I think that hiding the button would be an better option. 

## API Changes
`canDismiss` parameter will be added to the method definition 

`public Task<string> DisplayPromptAsync (string title, string message, string accept = "OK", string cancel = "Cancel", string placeholder = default, int maxLength = -1, Keyboard keyboard = default, string initialValue = "", bool canDismiss = true);`

## Intended Use Case
This could be used in login screens where user **must** enter a password. Also, it could be used in a situation where an user needs to complete an action and enter a value.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
