### ISSUE TITLE
[Bug] DualScreenInfo with Shell

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#12036]
### Description

When you try to use the DualScreenInfo.Current.SpanMode to determine if the application is running on dual screens in a Shell based application it always returns SinglePane.

### Steps to Reproduce

1. Create a new Xamarin Forms project with the Tabbed Shell template.
2. Update Xamarin.Forms to 4.8
3. Add the Xamarin.Forms.DualScreen NuGet package.
4. Add `Debug.WriteLine(DualScreenInfo.Current.SpanMode);` to OnAppearing on the ItemsPage.
5. Run the application in Debug mode on the Surface Duo Emulator.
6. Span the application on both screens.
7. Change to the Browse view in the application.
8. SpanMode will still be SinglePane.

### Expected Behavior

DualScreenInfo.Current.SpanMode should be Wide.

### Actual Behavior

SpanModeDualScreenInfo.Current.SpanMode will still be SinglePane.

### Basic Information

- Version with issue: 4.8.0.1364
- Last known good version: Unknown
- IDE: Visual Studio Community 2019 Version 16.7.2
- Platform Target Frameworks: 
  - Android: 10.0
- Nuget Packages: Xamarin.Forms.DualScreen
- Affected Devices:  Surface Duo Emulator

### Reproduction Link

https://github.com/scottkuhl/DualBug

**Comment by StephaneDelcroix** [comment]
Shell AND DualScreen => this is @PureWeen 's sweet spot !

**Comment by scottkuhl** [comment]
I seem to have been able to narrow this down to being a bug in an older version of the Surface Duo emulator.  I can't recreate the issue on a new version.  Closing.
