### ISSUE TITLE
[Bug] iOS: Safe area is applied too late

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12041]
Hi.

ios:Page.UseSafeArea="True" is not applied when the page loads. This is problematic if you push pages onto a stack as the safe area will only be applied/accessible in OnAppearing, which will be executed after your page push animation has finished. This makes all the elements jump when the slide-in page animation has finished.

On<iOS>().UsingSafeArea() returns true before that but the padding has not been applied yet, also  On<iOS>().SafeAreaInsets() returns all zeroes.

There are workarounds such as https://cyril.cathala.org/2019/02/11/safeareatinsets/, but it's a LOT of code to work around something that should work out of the box imho. So could iOS safe area be fixed so that it works when a page is constructed? I am pretty sure it has worked that way at some point as Xamarin's documentation used to say it will work both in the constructor and in OnAppearing. Also some libraries I use have broken behaviour for iOS safe insets which seems to denote the behaviour has changed.

Thanks.

**Comment by StephaneDelcroix** [comment]
could you please attach a small repro project ? thx

@rmarinho does this ring a bell to you ?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
