### ISSUE TITLE
[Bug] Mediaelement crashes on Android whenever playing a video from the blob store

### ISSUE THREAD

**Issue by MarcBruins** [xamarin/Xamarin.Forms#12048]
### Description
Whenever you try to play a video from the Azure blob storage, the app crashes. If you play the video from somewhere else(ch9 for example) it works fine. Playing the video in browser, on iOS or any platform works fine.

### Steps to Reproduce

1. Download the [channel 9 video xamarin show](https://sec.ch9.ms/ch9/5d93/a1eab4bf-3288-4faf-81c4-294402a85d93/XamarinShow_mid.mp4)
1. Upload the video in Azure blob storage in a public container
1. Download the [mediaelement sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/MediaElementDemos)
1. Adjust the url in the `PlayWebVideoPage.xaml` to point to the video inside the blob storage.
1. Play the video

*To skip the upload part of the reproduction steps you can also use this: https://devsec.blob.core.windows.net/testcontainer/XamarinShow_mid.mp4*

### Expected Behavior

The video plays, like it play on the other platforms.

### Actual Behavior

First a popup appears (see screenshots) that display "Can't play this video".

When pressing ok, a null reference exception occurs. With no stacktrace.

```
System.NullReferenceException
  Message=Object reference not set to an instance of an object.
```

If i look into the ADB device monitor i get the following information:

```
09-08 09:57:10.298: 
V/MediaHTTPService(6100): MediaHTTPService(android.media.MediaHTTPService@99ff071): Cookies: null
09-08 09:57:10.298: V/MediaHTTPService(6100): makeHTTPConnection: CookieHandler (java.net.CookieManager@ca0a97c) exists.
09-08 09:57:10.299: V/MediaHTTPService(6100): makeHTTPConnection(android.media.MediaHTTPService@99ff071): cookieHandler: java.net.CookieManager@ca0a97c Cookies: null
09-08 09:57:11.304: W/MediaHTTPConnection(6100): readAt 20324686 / 32768 => java.net.ProtocolException
09-08 09:57:11.339: W/MediaPlayer(6100): Couldn't open https://devsec.blob.core.windows.net/testcontainer/XamarinShow_mid.mp4: java.io.FileNotFoundException: No content provider: https://devsec.blob.core.windows.net/testcontainer/XamarinShow_mid.mp4
09-08 09:57:11.339: V/MediaHTTPService(6100): MediaHTTPService(android.media.MediaHTTPService@9ffa219): Cookies: null
09-08 09:57:11.360: V/MediaHTTPService(6100): makeHTTPConnection: CookieHandler (java.net.CookieManager@ca0a97c) exists.
09-08 09:57:11.360: V/MediaHTTPService(6100): makeHTTPConnection(android.media.MediaHTTPService@9ffa219): cookieHandler: java.net.CookieManager@ca0a97c Cookies: null
09-08 09:57:12.306: W/MediaHTTPConnection(6100): readAt 20324686 / 32768 => java.net.ProtocolException
09-08 09:57:12.311: E/MediaPlayerNative(6100): error (1, -2147483648)
09-08 09:57:12.311: E/MediaPlayer(6100): Error (1,-2147483648)
09-08 09:57:12.311: D/VideoView(6100): Error: 1,-2147483648
09-08 09:57:12.315: I/mono-stdout(6100): Media failed.

```

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1269
- Last known good version: none
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: Android 9.0
- Affected Devices: All android devices

### Screenshots

![Crash](https://github.com/MarcBruins/Xamarin_Forms___MediaElement/raw/master/Screenshots/Capture.PNG)

### Reproduction Link

[Repo](https://github.com/MarcBruins/Xamarin_Forms___MediaElement/)

### Workaround

No, however i'm investigating it.

**Comment by MarcBruins** [comment]
After investigating this issue, i found out that is the `x-ms-version` property on the storageaccount to `2011-08-18` makes the videos work. My version was `2019-12-12`. Why this works is something i don't know. I'll log an issue with the Azure blob storage folks because this seems weird behavior.

I'll close this as it is not a XF related issue.

**Comment by thankyou1230** [comment]
> After investigating this issue, i found out that is the `x-ms-version` property on the storageaccount to `2011-08-18` makes the videos work. My version was `2019-12-12`. Why this works is something i don't know. I'll log an issue with the Azure blob storage folks because this seems weird behavior.
> 
> I'll close this as it is not a XF related issue.

Hi sir, I'm now facing this problem too. I uploaded a video and image to Azure Storage, then i can't show them in MediaElement and Image too. 
Could you show how to change the x-ms-version. I really don't know where is it
Thanks alots
