### ISSUE TITLE
[Bug] ListView item not resizes properly for content changes when using Frame in the ItemTemplate

### ISSUE THREAD

**Issue by gokulsaravanan** [xamarin/Xamarin.Forms#12046]
### Description

ListView item does not resize properly when text content increases when using Frame in the ItemTemplate(i.e. The content contains a Label that is bound to the content object), the first time the when loading the view is measured properly.

When increases the text content of the Label, the list item remains at the same size and not resized as excepted. This issue occurs when using Frame in the Item Template, 

### Steps to Reproduce

1. Run the attached sample.
2. Tap **Make entries bigger** button (press it one or more times until the text wraps and the items remain in the same size). 

### Expected Behavior
 The list items should resize properly whenever the text changes.

### Actual Behavior
 The list views Items not resized when text content is increased.

### Basic Information

Checked version Xamarin.Forms - 4.5.0.617
- IDE: Visual Studio 2019
  - Android: 9.0
  - iOS:  13.5
  - UWP: 17763
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Xamarin.Forms

### Screenshots
![image](https://user-images.githubusercontent.com/46105032/92405090-850c2780-f152-11ea-8805-485d94d0e0a3.png)

### Reproduction Link
[DataTemplate.zip](https://github.com/xamarin/Xamarin.Forms/files/5184056/DataTemplate.zip)

**Comment by PureWeen** [comment]
FYI I tested with CollectionView and it resizes without any issues

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
