### ISSUE TITLE
[Bug] DataTrigger does not reflect with binding change

### ISSUE THREAD

**Issue by JimmyPun610** [xamarin/Xamarin.Forms#12040]
### Description
I am creating a Label with DataTrigger to change the Text and TextColor with an enum.
However, the data trigger does not change anything on default.

### Steps to Reproduce

1.  Run sample app
2.  Click SET TO HOUSE
3.  Click SET TO FLAT
4. Click SET TO HOUSE
5. Click SET TO NONE

### Expected Behavior
The Label will show No Preference (NONE), House, Flat as button clicked
### Actual Behavior
No Preference does not show.
### Basic Information
I created a thread in the forum for more information
https://forums.xamarin.com/discussion/184754/strange-behaivor-of-datatrigger#latest

- Version with issue:
I am using the latest version of the tools.
It happens in Android and iOS as far as I know.

### Screenshots
<img src="https://us.v-cdn.net/5019960/uploads/editor/4r/duptu4jhp253.gif" width=300>

### Reproduction Link
Sample app
https://us.v-cdn.net/5019960/uploads/editor/fz/j7xshnx9y0pz.zip

### Workaround
Create 3 labels, use data trigger to set IsVisible property with the enum

**Comment by StephaneDelcroix** [comment]
I suspect you're using 'null' as default value or something, and DT detects it as value not to be processed. Try using a different default value.

It still might be a bug though...

**Comment by JimmyPun610** [comment]
> I suspect you're using 'null' as default value or something, and DT detects it as value not to be processed. Try using a different default value.
> 
> It still might be a bug though...

Thank you, but I am not sure what is the default value you are talking about.
But if the condition is not matching any data trigger, it should make the Label apply the original setup.

Anyway, I tried to add all 3 conditions to corresponding data trigger and it is still buggy in my real app. (but it is ok in the sample app)

**Comment by StephaneDelcroix** [comment]
> But if the condition is not matching any data trigger, it should make the Label apply the original setup?

no, that's not how it works. DataTriggers apply a value when a condition is met, but do NOTHING when it's not. otherwise we wouldn't be able to have multiple DT with different conditions.

As it works in your sample, I'm closing this. feel free to reopen if something is still wrong

**Comment by JimmyPun610** [comment]
Just received a reply from the Xamarin Forum that the team is going to fix it in [vNext+1 (5.0.0)](https://github.com/xamarin/Xamarin.Forms/projects/79#card-43635909)
