### ISSUE TITLE
[Bug] Bindable property PropertyChanged event called before the property actually changes

### ISSUE THREAD

**Issue by SuperCorks** [xamarin/Xamarin.Forms#12058]
### Steps to Reproduce
_Please see the attached project for more details._
1. Start from a `ContentPage`.
2. Make a property that raises a `PropertyChanged` event in the binding context of that content page (e.g. in its view model).<br>![image](https://user-images.githubusercontent.com/6114650/92548870-15676c80-f226-11ea-8f80-78999bb5946c.png)
2. Make a custom `ContentView` with a bindable property. The bindable property should be linked to a property within the `ContentView` that raises the `PropertyChanged` event.<br>![image](https://user-images.githubusercontent.com/6114650/92548839-0385c980-f226-11ea-8518-9284c80450f2.png)
3. In the Xaml of the page, bind the property from the page's binding context to the bindable property of the custom child view.<br>![image](https://user-images.githubusercontent.com/6114650/92548964-4182ed80-f226-11ea-9e06-3e264b387d4e.png)
4. Add an event handler to the `PropertyChanged` event of the bindable property.<br>![image](https://user-images.githubusercontent.com/6114650/92549068-7ee77b00-f226-11ea-83a3-63a9e926fc1f.png)
4. Update the property in the page's view model (with a button for example) and observe the flow of execution. You're going to see that the `PropertyChanged` event of the bindable property in the child view is raised before the property is actually changed.
![image](https://user-images.githubusercontent.com/6114650/92549499-662b9500-f227-11ea-8bb4-789682cf5ad1.png)

### Expected Behavior
The property changed event of the bindable property should not be raised from outside the setter, or at least after the setter has been called.

### Actual Behavior
The property changed event is called before the property is actually changed.

### Basic Information

- Version with issue: 4.8.0.1364
- Platform Target Frameworks: Only tested on Android.

### Reproduction Link
[PropertyChangedBug.zip](https://github.com/xamarin/Xamarin.Forms/files/5192283/PropertyChangedBug.zip)

### Workaround

The current workaround is simple but ugly because this is already handled (well... should be) through the short-circuit in the property's setter. But now you need a second short-circuit in the event handler as well. Here's what I did in my real project:
```csharp
// ...
private ObservableCollection<HapticDevice> _deviceList;
private ObservableCollection<HapticDevice> _oldDeviceList;
public ObservableCollection<HapticDevice> DeviceList {
    get => this._deviceList;
    set
    {
        if (this._deviceList != value)
        {
            this._deviceList = value;
            this.OnPropertyChanged(nameof(DeviceList));
            this._oldDeviceList = value;
        }
    }
}
// ...

// then when you add a listener to the PropertyChanged event:
this.PropertyChangedObservable(nameof(DeviceList))
    .Where(_ => this._deviceList != this._oldDeviceList)
    .SubscribeSafely(_ => this.OnDeviceListPropertyChanged(this.DeviceList));
```

**Comment by StephaneDelcroix** [comment]
your BindableValue implementation looks wrong. It should be as this

```
public static BindableProperty BindableValueProperty = BindableProperty.Create(nameof(BindableValue), typeof(int), typeof(subview));

public int BindableValue {
  get => (int)GetValue(BindableValueProperty);
  set => SetValue(BindableValueProperty, value);
}
```

and yes, the order is right, the value BP value has to be set BEFORE the event is triggered, otherwise you couldn't rely on it in the event handler

**Comment by SuperCorks** [comment]
Ok I understand the concept. I didn't know you **HAD** to do your properties get/set like that.

**Comment by MappingSteve** [comment]
FWIW: You don't HAVE to "do your properties like that". 

The shown "symptoms" don't demonstrate a bug. This can be seen by looking at the VALUES in each output line.

The setting of value to "1" generates output in the desired order.

The one detail that might be unexpected, is that the `PropertyChanged` event **is** triggered for "0", *even though that is not a change in value*. This can be seen by the "missing" output line, which would be `Actually raising PropertyChanged from the setter -> 0`.

This suggests something quite interesting (and to me, surprising): that the `PropertyChanged` event is triggered by any call to the setter, NOT by the `OnPropertyChanged` call within the setter.

(Setting the value to what it already is, "0", may be a side-effect of two-way binding in XAML.)

**Comment by dm1tt** [comment]
I HATE NIGGERS
