### ISSUE TITLE
[Bug] ScrollToPosition.Start no longer works after switching from ListView to CollectionView

### ISSUE THREAD

**Issue by lafritay** [xamarin/Xamarin.Forms#12064]
### Description

Here's my call when `control` is `ListView`:

```
control.ScrollTo(e, ScrollToPosition.Start, animated: true);
```

After migrating `control` to `CollectionView` this code still compiles and runs:

```
control.ScrollTo(e, ScrollToPosition.Start, animated: true);
```
However, the scroll position seems to be ignored. No matter what I pass for `ScrollToPosition`, it always works as if `ScrollToPosition.MakeVisible` was passed.

After a few hours of debugging I realize that there is a slight change to the API for `ScrollTo` between `ListView` and `CollectionView`. Here's `ListView`:

```
public void ScrollTo (object item, Xamarin.Forms.ScrollToPosition position, bool animated);
```

And here's `CollectionView`:

```
public void ScrollTo (object item, object group = default, Xamarin.Forms.ScrollToPosition position = Xamarin.Forms.ScrollToPosition.MakeVisible, bool animate = true);
```

Because the `group` parameter is of type `object`, it happily accepts `ScrollToPosition.Start` and uses the default for the `position` argument. The fix of course is to do this:

```
control.ScrollTo(e, position: ScrollToPosition.Start, animated: true);
```

Sharing this here in case it helps someone else avoid the same problem. Feel free to close this bug.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by lafritay** [comment]
@samhouts I'm guessing you're in rapid-triage mode and didn't process this fully. This is less of a bug report and more of an explanation of an API nuance that cost me a few hours when moving from `ListView` to `CollectionView`. I'm posting it here so that others will find it if they hit the same issue that I did. While I think it would be educational to show this report to whoever changed this API, it's not an actual bug. You can close this.

**Comment by samhouts** [comment]
@lafritay You're very right! I saw the needs repro label but no comment and didn't read the issue body at all!

Thank you very much for reporting this. I think you're right...this is a bit quirky, and someone will very likely run into this same situation.
