### ISSUE TITLE
[Bug] [Android] BoxView color is cleared when updating corner radius

### ISSUE THREAD

**Issue by rickclephas** [xamarin/Xamarin.Forms#12061]
### Description

BoxView isn't visible on Android when the corner radius is updated.

### Steps to Reproduce

1. Create a BoxView with a color
2. Add a button
3. Set the corner radius when the button is clicked

### Expected Behavior

The BoxView is visible with the new corner radius 

### Actual Behavior

The color of the BoxView is cleared and therefore the BoxView is invisible.

### Basic Information

- Version with issue: 4.8.0.1364
- Last known good version: 4.7.0.1351
- Platform Target Frameworks: 
  - Android: 9.0 (API 28)
- Android Support Library Version: 28.0.0.3
- Affected Devices: all

### Workaround

The issue is caused by the changes made in #9220.

The `UpdateBackgroundColor` method is called after the corner radius is updated:
https://github.com/xamarin/Xamarin.Forms/blob/32d2fd4c2f205feef82202692a2b8db1e502ee88/Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs#L176

Though that method is completely empty:
https://github.com/xamarin/Xamarin.Forms/blob/32d2fd4c2f205feef82202692a2b8db1e502ee88/Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs#L60-L63

I guess the `UpdateBoxBackground` method should be called instead.

We added the following to our custom renderers `OnElementPropertyChanged` method to "fix" this:
```C#
if (e.PropertyName.Equals(BoxView.CornerRadiusProperty.PropertyName))
    base.OnElementPropertyChanged(sender, new PropertyChangedEventArgs(BoxView.ColorProperty.PropertyName));
```

**Comment by holecekp** [comment]
I can confirm that the bug is still in the latest Xamarin.Forms version.
@rickclephas  Thank you for your workaround with the custom renderer. It helped.
