### ISSUE TITLE
[Enhancement] SwipeView Sensitivity 

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#12067]
It would be nice to have some sort of option to set the SwipeView sensitivity .

I have a SwipeView Inside the ItemTemplate of a CollectionView with a command Binded to SelectionChangedCommand which takes you to another page. 

On some android devices I have tested it is unreliable getting the SelectionChangedCommand to fire 100% of the time because the app thinks your finger is drifting slightly to the left opening the SwipeView when tapping on an item.

I noticed when scrolling down too, sometimes items open as you scroll if you don't scroll perfectly.

**Comment by mcardenasvalsi** [comment]
Is there any progress in this topic?

I hace experience the same behaviour on android devices.

**Comment by kkppstudios** [comment]
Hoping this gets prioritized for the next update release

**Comment by duncancole** [comment]
This is also an issue for me. On Android getting any touch events firing, whether that's the row itself or a button contained within, on a list of swipview items (swipeview is used for a delete option) is very inconsistent. Works fine on iOS but on Android the swipe gesture is just too senstive.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
