### ISSUE TITLE
[Enhancement] Allow Flyout to be fully customizable

### ISSUE THREAD

**Issue by glatzert** [xamarin/Xamarin.Forms#12075]
## Summary
Currently the flyout consists of a list FlyoutItems + MenuItems and the header.
This has some drawbacks, that are unfortunate and limiting:

1) FlyoutItems do allow nested ShellContent, but not nested FlyoutItems or MenuItems, thus "categorization" or grouping is limited.
2) Categorization (with headers) is not possible, due to the FlyoutItems not being fully recursive.
3) Routing in a mixed environment (FlyoutItems + Custom routes via `Routing.RegisterRoute`) is _really_ quirky.

Ideally a The flyout should just be a content view, allowing to place anything, thus we can e.g. create categorized nested lists and just put navigation-Targets on top, which are registered via `Routing.RegisterRoute` ONLY (and thus making routing easier).

## API Changes

Remove the current FlyoutItems-List and allow placing any ContentView inside the AppShell.

E.G:
```
<Shell.FlyoutHeaderTemplate>
  <myViews:MyHeaderTemplate />>
</Shell.FHT>
<Shell.FlyoutTemplate>
  <myViews:MyFlyoutContent />
</Shell.FlyoutTemplate>
```

## Use case
Simplification of navigation, since routes could be all listed in Routing.RegisterRoute, also there's no distinction between page-routes and other routes and thus simplifying navigation alltogether.
Also it gives full control over the flyout and nothing needs to be squished into the unflexible structure of the current flyout.

**Comment by jsuarezruiz** [comment]
cc @PureWeen

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
