### ISSUE TITLE
[Bug] Slider not responding to taps in iOS 14

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#12084]
### Description

I should be able to tap the track of the slider and see the selection change. This was added in https://github.com/xamarin/Xamarin.Forms/pull/2476

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="FormsGallery.XamlExamples.SliderDemoPage"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             Title="Slider Demo">
    <StackLayout>
        <Label Text="Slider"
               FontSize="50"
               FontAttributes="Bold"
               HorizontalOptions="Center" />
        
        <Slider x:Name="slider"
                 Minimum="0"
                 Maximum="100" 
                 VerticalOptions="CenterAndExpand" />

        <Label Text="{Binding Source={x:Reference slider},
                              Path=Value,
                              StringFormat='Slider value is {0:F1}'}"
               FontSize="Large"
               HorizontalOptions="Center"
               VerticalOptions="CenterAndExpand" />
    </StackLayout>
</ContentPage>
```

### Expected Behavior

Touching the slider track moves the value and drag handler to the tap position. This works in the general settings display brightness on iOS.

### Actual Behavior

Touching the slider track doesn't do anything. 

### Basic Information

- Version with issue: 5.0.1.1419-nightly
- IDE:
- Platform Target Frameworks: iOS 14

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/blob/master/FormsGallery/FormsGallery/FormsGallery/XamlExamples/SliderDemoPage.xaml

**Comment by jfversluis** [comment]
Curious, the `Slider` in the control gallery seems to work fine on current main

**Comment by jsuarezruiz** [comment]
Missing to use the Platform Specific?
![issue12084](https://user-images.githubusercontent.com/6755973/99417286-083bbd80-28fa-11eb-9444-a58df64c3bf7.gif)
https://github.com/xamarin/Xamarin.Forms/pull/12883

**Comment by EmilAlipiev** [comment]
I am not sure why this was closed. but this is very easy to reproduce, if you set the slider with properties like below and  once you move to the maximum, on ios, it is not possible to move it again. Should i create a new ticket for this? it surprises me that none else has reported.


 ```
<Slider
                            x:Name="slVolume"
                            HorizontalOptions="FillAndExpand"
                            Maximum="10"
                            MaximumTrackColor="Gray"
                            Minimum="0" 
                            MinimumTrackColor="Green"
                            ThumbColor="{DynamicResource bacgroundColor}"
                            ValueChanged="slVolume_ValueChanged"
                            Value="{Binding SpeechVolume, Mode=TwoWay}" />
```
