### ISSUE TITLE
Carousel child pages not firing OnAppearing or OnDisappearing event when tapping collectionview item in IOS?

### ISSUE THREAD

**Issue by sreejithsree139** [xamarin/Xamarin.Forms#12086]
### Description

I have a Carousel Page with some children. On every child page, I have a collectionview. When clicking the collectionview item, the other child pages will show. In that case, the `OnAppearing` or `OnDisappearing` function is not triggering.

### Steps to Reproduce

1.  Create a Carousel Page with 3 children.
2.  Add a collection view on each child with 3 items: Page1, page2, Page3
3.  When clicking the collection view item show the selected page.
4.  `OnDisappearing` will not trigger for the last page and `OnAppearing` will not trigger for the new page.

### Expected Behavior
`OnDisappearing` should trigger for all the pages when moves to another page and `OnAppearing` should trigger when entering a new page.

### Actual Behavior
 `OnDisappearing` not triggering for the last page and `OnAppearing` not triggering for the new page when move pages via collectionview item click.

### Basic Information
The issue is only on the ios version, the android part is working fine.
XF Version: 4.7.0.968

### Workaround

[CarouselDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/5208440/CarouselDemo.zip)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9430
