### ISSUE TITLE
[Bug] MultiBinding StringFormat with MultiValueConverter

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#12094]
### Description
`StringFormat` of `MultiBinding` does not use the result of `MultiValueConverter` as a parameter.

### Steps to Reproduce
Add `MultiBinding` with `StringFormat="Result of MultiValueConverter={0}"` and `Converter`

### Expected Behavior
`Result of MultiValueConverter={0}`

### Actual Behavior
`Result of MultiValueConverter={FirstBindingValue}`

### Basic Information

- Version with issue: 4.8.0.1364
- Last known good version: -
- IDE: 16.7.3

**Comment by salgiza** [comment]
I'm not sure whether this is the same bug or not, but Multibinding is broken in Xamarin Forms 4.8. After trying to implement all the examples in the docs without success, I found this example: https://github.com/jsuarezruiz/MultiBindingPlayground

It works perfectly with the version of Xamarin Forms that it references (4.7), but stops working as soon as you upgrade the nuget package to 4.8.

P.D. Also, for reference, this was my question in StackOverflow when I was unable to make it work: https://stackoverflow.com/questions/64244447/multibinding-in-xamarin-forms-element-is-null

**Comment by jsuarezruiz** [comment]
I have updated https://github.com/jsuarezruiz/MultiBindingPlayground to Xamarin.Forms 4.8.0.1534 and the sample continue working as expected:
![mb-issue](https://user-images.githubusercontent.com/6755973/95453051-7b046100-096a-11eb-9c1a-ab10e045bb5d.gif)
Are you using a different version?

**Comment by salgiza** [comment]
How weird. I’ll be out of the office until Tuesday, but I’ll double check as soon as I go back (I did try it in the iOS emulator, though, don’t know if that will make any difference).

**Comment by salgiza** [comment]
Ok, I don't know whether it was the fact that an updated nuget package of XF4.8 was released just after I tested the code, or it was the fact that I was expecting it to fail (as it was also failing in my project) and I made a mistake, but yes, I redownloaded @jsuarezruiz example and it works perfectly with the latest stable XF version.

As I mentioned in StackOverflow, even weirder, _my own code_, that didn't work last week, today does.  So either the XF update did somethings, I was visited by gremlins, or I somehow chained several silly mistakes when I tried to use MultiBinding for the first time...

So, please ignore my comments, and sorry for the noise 😞

**Comment by StephaneDelcroix** [comment]
> I was visited by gremlins

I vote on that ^^^. that happens to all of us
