### ISSUE TITLE
[Bug]  Crash in DropGestureRecognizer_Drop() 

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12092]
### Steps to Reproduce
[CrashRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/5210541/CrashRepro.zip)

1. Open attached project
2. Run the app on using the Android emulator and move the chess piece on the grid from one cell to another

### Expected Behavior
No crash

### Actual Behavior
Crash on Android emulator (not on UWP)

### Basic Information
Essentially modifying a UI Element in DropGestureRecognizer_Drop() is causing this crash to happen.

**Comment by PureWeen** [comment]
Hey @snowman745 this is neat!! When you finish this let me know https://twitter.com/PureWeen

I fixed some issues related to this inside 5.0 where I was seeing the same problem

We should have a 5.0 pre1 out soon you can test but in the mean time if you'd like to test the nightly
https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

**Comment by snowman745** [comment]
Thanks, will do.

I installed nightly 4.0.1.1467-nightly and confirmed its fixed in these builds. Hopefully it gets released soon!
