### ISSUE TITLE
[Enhancement] Add option to DisplayPromptAsync for keyboard Enter key to perform same behavior as "OK" button

### ISSUE THREAD

**Issue by tomreich** [xamarin/Xamarin.Forms#12106]
## Summary

On platforms with a physical keyboard, pressing the "Enter" key on after entering text into a modal single-line field typically performs the same action as pressing the OK button.  There doesn't seem to be a way to enable this in the DisplayPromptAsync call.  It would be nice to be able to enable this, and it feels natural on platforms like UWP.

## API Changes

Currently, it seems on platforms with a physical keyboard such as UWP, pressing the Enter key on a DisplayPromptAsync call does nothing.  I imagine this would need to remain the default as not to break pre-existing behavior.  Given that, a new optional parameter is probably the best option.  It could be as simple as a boolean:

    bool completeOnEnterPressed = false

## Intended Use Case
This feels like expected behavior for many/most prompts in a PC/physical keyboard environment.

**Comment by SvendK** [comment]
Oh, just another related request:
My previous comment was about hitting Enter on a physical keyboard.
But if you hit Enter on the soft/screen keyboard, what happens is the keyboard dissappears. I guess it's the same behaviour as OP mentioned, but for them it's also happening for physical keyboard (in UWP).

I'd like the onscreen Enter button to "submit" the prompt, i.e. Accepting the input.

**Comment by mdbill** [comment]
Can we please get this in Maui

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
