### ISSUE TITLE
Xamarion forms ios notification not receiving

### ISSUE THREAD

**Issue by dhanaraj94** [xamarin/Xamarin.Forms#12104]
Xamarin ios push notfication issue
### Description
We are tying to enable push notifications on our iOS application but have run into an issue where the access pop-up comes just the first time we install the application on a device. The following installations, updates, uninstalling and reinstalling does not show the pop up for notifications. 
Is this an issue that has already been confirmed and if so, is there a work around.
### Steps to Reproduce

1. The following installations, updates, uninstalling and reinstalling does not show the pop up for notifications. 

### Expected Behavior
work on all ios devices and ask popup on every new install
### Actual Behavior
not working in any ios device
### Basic Information

- Version with issue:
- Last known good version: not sure
- IDE: xamarin forms
- Platform Target Frameworks: 
  - iOS:  13 latest
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 4.8.0.134 stable
- Affected Devices:
All the ios devices

**Comment by PureWeen** [comment]
@dhanaraj94 I'm not aware of any issues with iOS notifications

If you have a repro of your issue I would recommend logging it over here https://github.com/xamarin/xamarin-macios

Or asking on StackOverflow
