### ISSUE TITLE
[Spec]  GetMetrics is deprecated, what is the new code?

### ISSUE THREAD

**Issue by HeMinzhang** [xamarin/Xamarin.Forms#12111]
# [The feature] 

Provide a concise description of the feature and the motivation for adding it to Xamarin.Forms

 API

namespace Android.Views
{
    //
    // Summary:
    //     Provides information about the size and density of a logical display.
    //
    // Remarks:
    //     Android platform documentation
    //     Portions of this page are modifications based on work created and shared by the
    //     Android Open Source Project and used according to terms described in the Creative
    //     Commons 2.5 Attribution License.
    [Register("android/view/Display", DoNotGenerateAcw = true)]
    public class Display : Java.Lang.Object
    {       ` 
// Remarks:
        //     Portions of this page are modifications based on work created and shared by the
        //     Android Open Source Project and used according to terms described in the Creative
        //     Commons 2.5 Attribution License.
        [Obsolete("deprecated")]
        [Register("getMetrics", "(Landroid/util/DisplayMetrics;)V", "GetGetMetrics_Landroid_util_DisplayMetrics_Handler")]
        public virtual void GetMetrics(DisplayMetrics? outMetrics);

![QQ截图20200914195014](https://user-images.githubusercontent.com/2683269/93082453-8cd44a80-f6c3-11ea-9709-234094855693.png)

### Properties

| API | Description |
| ------------- | ------------- |
| [name] | Gets or sets [description]. |

### Events

| API | Description |
| ------------- | ------------- |
| [name] | [API documentation/description] |
 
# Scenarios

## C# Example
```csharp
var thing = new MyNewControl();
thing.BeAwesome = true;
thing.Color = Color.Cornsilk;
```

## XAML Example
```xaml
<MyNewControl x:Name="thing" BeAwesome="true" Color="Cornsilk" />
```

## CSS Example
```css
MyNewControl {
     color: Cornsilk;
}
```

# Backward Compatibility

Minimum API levels?
Breaking changes?
Unsupported platforms?

# Difficulty : [low/medium/high]

**Comment by PureWeen** [comment]
These APIs are deprecated on the Android APIs so this isn't really part of Xamarin

I would check SO or the Android docs for the replacement API to use
https://stackoverflow.com/questions/63407883/getting-screen-width-on-api-level-30-android-11-getdefaultdisplay-and-getme
