### ISSUE TITLE
[Bug] Strange behavior of animations and activityindicator with Android style

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12117]
### Description
Animations not working properly when apply the below Android style.

### Steps to Reproduce
On the Xamarin.Forms Sample project:
1. Add a `Label ` named SampleLabel and a running `ActivityIndicator ` to the page plus the below animation:
```
protected async override void OnAppearing()
{
            base.OnAppearing();
            await SampleLabel.TranslateTo(240, 0, 600, Easing.Linear);
}
```
2. On Android project set the below theme:
```
<style name="MainTheme" parent="MainTheme.Base"/>
<style name="MainTheme.Base" parent="Theme.AppCompat">
<item name="android:colorBackground">#000000</item>
```

### Expected Behavior
Label text translation to run at the startup of the app with a readable text during and after the animation, activity indicator to be spinning.
### Actual Behavior
Text of label becomes completely overlapped, confused/unreadable during and after the animation ends which is a strange behavior., also the activity indicator circle is not spinning.
### Basic Information
- Sending the App to the background and restore it back makes the label text readable.

- If I remove the last line of the style/theme it becomes readable and the activity indicator spins normally.

- It's only happening on **emulator**, on real device it working normally on both debug and release versions.

- Issue is not occurring when removing the last line of the Android style (`<item name="android:colorBackground">#000000</item>`).

- Happening with whatever color hex is set to `android:colorBackground`, the background color will be black.

- VS hang during build and no error reported when : 

```
<style name="MainTheme" parent="MainTheme.Base"/>
<style name="MainTheme.Base" parent="Theme.AppCompat">
<item name="android:colorBackground">#000000</item>
```

- Version with issue: Emulator 30.0.26. Xamarin.Forms 4.8.0.1364.
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks: .NET Standard 2.0.
  - Android: 9.0 API 28. 
- Android Support Library Version: Xamarin.Android.Support.v7.AppCompat 28.0.0.3

**Comment by PureWeen** [comment]
@Codwy can you attach a repro please?
