### ISSUE TITLE
[Bug] Entry in Grid is not Filling the Column

### ISSUE THREAD

**Issue by fabrossmann** [xamarin/Xamarin.Forms#12113]
### Description

A `Entry` in a `Grid` is not filling the column. 

### Steps to Reproduce

Our application uses a custom entry with a validator. This custom entry is a `Grid`, that is created programmatically and the rows/columns are defined like this:
``` C#
RowDefinitions.Add(new RowDefinition() { Height = new GridLength(1, GridUnitType.Auto) });   

ColumnDefinitions.Add(new ColumnDefinition() { Width = new GridLength(400, GridUnitType.Star) });
EditorIndex = 0;

ColumnDefinitions.Add(new ColumnDefinition() { Width = new GridLength(36 * KiXamarinFormsHelper.Density, GridUnitType.Absolute) }); //KiXamarinFormsHelper.Density is a helper Method for getting the Screen Density
SignalImageIndex = 1;

ColumnSpacing = 0.0;
```
In the Editor Column we add a `Label` for the validation status(which expands like it should) and a custom styled `Entry`.
The SignalImage Column shows the status of the validation as a `Image`. Pressing it switches between the label and entry.

The Entry has the HorizontalOption `FillAndExpand`.

### Expected Behavior
![image](https://user-images.githubusercontent.com/6189957/93084992-3223fa00-f695-11ea-9ce2-c1c831612c52.png)

### Actual Behavior
![actual_behavior](https://user-images.githubusercontent.com/6189957/93083922-9c3b9f80-f693-11ea-8660-a3317220b965.png)

### Basic Information

- Version with issue: `4.8.0.1269`,`4.8.0.1364`
- Last known good version: `4.7.0.1351`
- IDE: VS19
- Platform Target Frameworks: 
  - Android: 9.0 with min Android Version: `4.4`
- Android Support Library Version: `28.0.0.3`
- Nuget Packages:
  - Plugin.CurrentActivity
  - System.Configuration.ConfigurationManager (_4.7.0_)
  - Xam.Plugin.DeviceInfo (_4.1.1_)
  - Xamarin.Android.Support.Compat (_28.0.0.3_)
  - Xamarin.Android.Support.Core.Utils (_28.0.0.3_)
  - Xamarin.Android.Support.CustomTabs (_28.0.0.3_)
  - Xamarin.Android.Support.Design (_28.0.0.3_)
  - Xamarin.Android.Support.v4 (_28.0.0.3_)
  - Xamarin.Android.Support.v7.AppCompat (_28.0.0.3_)
  - Xamarin.Android.Support.v7.CardView (_28.0.0.3_)
  - Xamarin.Android.Support.v7.MediaRouter (_28.0.0.3_)
  - Microsoft.AspNetCore.SignalR.Client (_3.1.7_)
  - Microsoft.Extensions.Logging.Console (_3.1.7_)
  - Microsoft.Extensions.Logging.Log4Net.AspNetCore (_3.1.0_)
  - Newtonsoft.Json
- Affected Devices:
  - Emulator running Android 9.0 or Android 4.4
  - ZEBRA TC700K (Android 6)

### Workaround

Downgrade to a 4.7 version

**Comment by PureWeen** [comment]
@fabrossmann can you attach a repro?

Does this sound like your issue?
https://github.com/xamarin/Xamarin.Forms/issues/12001

It seems to match the versions of regression

**Comment by fabrossmann** [comment]
If the bug also affects the column width , then yes it could sound like ours.

If I find the time, then I will try to attach a reproduction project.

**Comment by samhouts** [comment]
Thanks, we'll look for your repro. If we don't hear back, we'll close as a duplicate. :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
