### ISSUE TITLE
Xamarin - Menu Hamburger - Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;'

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12118]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1162051/xamarin-menu-hamburger-javalangnosuchmethoderror-n.html)._

---
[severity:Accessibility concern]
**Development:** 
I created an App from scratch, directed it to a version of android 4.2.2, the project opens normally.  
**Problem Found:**  
When implementing the Hamburger menu with the masterdatail and the detailpage the same app breaks, returns the following error: **Java.Lang.NoSuchMethodError: 'no method with name='isAttachedToWindow' signature='()Z' in class Landroid/view/ViewGroup;' **
My MainPage use this snippet to define MasterDetail and Detail:  
This. Master = new Views.MasterMenu();  
This. Detail = new NavigationPage(new Views.ListaMesas());              
App.MasterDetail = this;  
**Curiosity:**  
When I squeet it directed to version 5.0 onwards, it works perfectly. The problem is that I have some app's on customers who use tablets in this version 4.2.2 and the version compiled in Nov/2019 worked perfectly, now that I needed to do an update, I can not run the app on the client's tablet. Any help is welcome, if there is any package that suits me to load this menu, or an alternative way to have this menu, other than by masterdetail, also serves me.  
**Information and settings:**  
Xamarim version: 16.7.000.440  
Visual Studio Version: 16.7.2  
Positive Tablet - Android 4.2.2

---
#### Feedback Bot on 8/26/2020, 01:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Android 4.4 KitKat (API 19) is the minimum supported version for Xamarin.Forms
