### ISSUE TITLE
[Android] Uploading correctly signed aab archive from Visual Studio 2019 to Google Play Console fails at 99%

### ISSUE THREAD

**Issue by Hottemax** [xamarin/Xamarin.Forms#12122]
### Description

1) Build Android project, package as aab -> Archive ... Success.
2) Archives ... -> Distribute -> Google Play
3) It finds our Google Play Console, showing the correct Release tracks

Selecting the track and choosing Upload gets stuck at 99% and eventually fails:

Uploading package 97%...
Uploading package 98%...
Uploading package 98%...
Uploading package 99%...
Uploading package 99%...
Uploading package 99%...
Publishing project 'MyApp' completed with errors.
An error occur uploading 'com.myapp.aab', please see the log for more details.

There is no more information in the logs (neither Visual Studio nor the "Mono for Android" folder.
This used to work correctly. I can manually upload the created .aab file from the Google Play Console site, so I know the aab is signed correctly with the upload key.

Environment:
- IDE: Visual Studio 2019 16.7.3
- Xamarin.Forms 4.8.0.1364

**Comment by PureWeen** [comment]
Can you please use the feedback option on VS to log this issue

https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

**Comment by Hottemax** [comment]
Reported

> Can you please use the feedback option on VS to log this issue
> 
> https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

Reported here: https://developercommunity.visualstudio.com/content/problem/1190422/xamarinforms-android-uploading-correctly-signed-aa.html
