### ISSUE TITLE
[Bug] Potential memory leak or mismatch of operations

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#12138]
### Description

I noticed that some controls passed on the binding context to child properties. For example the `Image` element passes it's `BindingContext` along to the `Source` property. However, when changing the source, the context is neither un-set on the old, nor re-set on the new.

This is the only time the image sets the inherited context: https://github.com/xamarin/Xamarin.Forms/blob/release-4.8.0-sr2/Xamarin.Forms.Core/ImageElement.cs#L97
It probably should happen here too: https://github.com/xamarin/Xamarin.Forms/blob/release-4.8.0-sr2/Xamarin.Forms.Core/ImageElement.cs#L101

Also, this is actually a workaround for another, bigger issue: https://github.com/xamarin/Xamarin.Forms/issues/6933

If we can mark certain properties as inheritable, then this whole context code can go away. The RTL should go everywhere. The binging context should also go everywhere. But things like Label text should not. So we really need a way to do this from a property definition.

### Steps to Reproduce

1. Run the attached sample
2. Observe both `TheSource` and `oldSource` have contexts
3. Click "Swap"
4. Observe that `TheSource` no longer has a context and `oldSource` still has the context

### Expected Behavior

The source loses its context once it is removed from the view. And the new source gets the context.

### Actual Behavior

The original source keeps the context and because it is never overwritten, it may actually render the wrong things. The new source never gets the context, so may never work.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[BindingInheritanceBug.zip](https://github.com/xamarin/Xamarin.Forms/files/5233438/BindingInheritanceBug.zip)

### Workaround

Using the secret `SetInheritedBindingContext` method to redirect values all over 😄

**Comment by mattleibow** [comment]
Just thinking that un-setting it might be an issue...

For example, assume 2 image views:

1. set the image A to source A
2. set the image B to source A

Which context should get used? The last used?

But, then when you remove the source from B, then what should happen? Set to null? But now you break A.

**Comment by PureWeen** [comment]
@mattleibow I might be following your sample wrong here but why would setting `TheSource` cause anything to happen?

That's just replacing TheSource with a new ImageSource instance but then there's no Property Changed event to trigger the binding of the source back to the image so oldSource will still be the source that's on the Image

If you change the code to this
```C#
        private void OnSwapButtonClicked(object sender, EventArgs e)
        {
            TheSource = "https://github.com/xamarin/Xamarin.Forms/raw/main/Assets/banner.png";
           OnPropertyChanged(nameof(TheSource));
            OnCheckButtonClicked(null, null);
        }
```

then it works

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
