### ISSUE TITLE
[Spec]  APIS That need to be made public for contributors and Xamarin Community Tookit

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#12136]
# As we move controls over to the XCT we need to expose some properties to the outside world

Here's the list so far. As we create issues to fix these please link them here

Internal
- Binding.SelfPath constant
- GestureRecognizer default ctor
- NullEffect class
Private
- FontElement class
- PaddingElement class

Xamarin.Forms.Core.UnitTests:
Internal:
- RelativeLayoutTests.UnitExpressionSearch class

In addition, the Markup unit tests use reflection to access these private API's in Xamarin.Forms.Core in the BindableObject class: GetContext method, BindableContextAttributes enum , BindablePropertyContext nested class , SetValueArgs nested class

- [Add protected Accessor to VisualElement Constructor](https://github.com/xamarin/Xamarin.Forms/pull/12125)

**Comment by VincentH-Net** [comment]
Thanks for creating this issue @PureWeen; 

Most of the listed API's are used by C# Markup. Once these API's are available in the XTC we can move C# Markup there.

**Comment by bmacombe** [comment]
VisualElement constructor to protected.  There is a PR #12125 for it already, but just to have a complete list.

**Comment by ahoefling** [comment]
As I work through migrating the Popup Control (Xamarin/XamarinCommunityToolkit#292) I will document some of the APIs required that are currently internal. Right, now I have created the referenced PR #12125 to allow protected constructor for `VisualElement`. I know UWP is already giving me some issues and I'll document those here.

**Comment by pictos** [comment]
@PureWeen would be good to have the PlatformSpecific bits public as well. Even if they are decorated with `EditorBrowsable.Never` attribute.
please see:
https://github.com/jfversluis/XamarinCommunityToolkit-1/commit/faf782d8d28193c3f3764505022fda1ce9ffde3c#commitcomment-41827281

**Comment by ahoefling** [comment]
I just submitted 2 PRs that open up several APIs for iOS/UWP that are required to complete the Popup Control port from Xamarin.Forms to the Xamarin Community Toolkit. Once those are merged I will be very close to finishing up my work on the Popup Control

**Comment by Redth** [comment]
@StephaneDelcroix can you weigh in here?

**Comment by VincentH-Net** [comment]
@PureWeen could you add the internal `IPaddingElement` interface to the issue description? 
C# Markup also needs to access that one; I missed it earlier (my bad)
Thx!
