### ISSUE TITLE
WkWebView does not handle cookies consistently

### ISSUE THREAD

**Issue by alekseevabah** [xamarin/Xamarin.Forms#12134]
### Description
Setting the cookie to the webview does not seem to work 100% times on iOS (WkWebView).
In our case we have one webview in one page and clicking on the link inside this webview opens a new page with another webview with the same session cookie. In more than 50% of cases the session cookie is not there in the second webview.
Looks like it could be related to the native iOS cookies issues: https://developer.apple.com/forums/thread/99674

### Steps to Reproduce
(Sample project attached)
1. Open the app: it will load "google.com" in one webview and after navigation is done show an alert with cookies
2. Click on "Load another webview" -> this will load one more webview with the same cookie and same domain. After loading is done the alert with cookie will be shown
3. Press on "Reload the page" button to reload the page with webviews.

### Expected Behavior
Loading the webviews should always result in cookie name/value being displayed in alert dialog.

### Actual Behavior
Sometimes no cookie is shown in the alert dialog after the webview was loaded -> so webview has no access to the cookie which was set before loading it.

### Basic Information

- Version with issue: 4.6.0.1180 (latest has it as well)
- Last known good version: -
- IDE: Visual Studio for Windows 16.5.4
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: -
  - UWP:  -
- Android Support Library Version: -
- Nuget Packages: -
- Affected Devices: physical iPhones (iOS 13.*) as well as iPhoneSimulator

### Reproduction Link

[WkWebViewAndCookies.zip](https://github.com/xamarin/Xamarin.Forms/files/5232089/WkWebViewAndCookies.zip)

**Comment by matmicro** [comment]
Hi,

Fix seems to be included in last Xamarin release :
https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/release-notes/4.8/4.8.0-sr6

By the way i am still facing such kind of issue under iOS (iPhone 6  on iOS 12.4.9, and iPhone 11 on iOS 14.3).
But issue looks more difficult to reproduce on Simulator.

Does anyone is still facing cookie issues ?
May this be related to another bug ?

Thanks and regards
