### ISSUE TITLE
Xamarin page is transparent

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12147]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1184154/xamarin-page-is-transparent.html)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:16.7.2]
This issue started after the VS Community 2019 update to 16.7.3, and possibly a Xamarin update at the same time. When navigating from an initial ContentPage to another ContentPage, the second page is transparent, and the initial page can be seen in the background. After navigating to two different pages, navigation ceases to function. This is a breaking change and renders the app useless.

---
#### Feedback Bot on 9/14/2020, 10:57 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
