### ISSUE TITLE
[Bug] - BackButtonBehavior hide tabs on ios

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12144]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170706/bug-backbuttonbehavior-hide-tabbar-on-ios.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice]
<Shell.BackButtonBehavior>
        <BackButtonBehavior IconOverride="IconBack.png"/>
    [</Shell.BackButtonBehavior>]

In the page that I opened use Shell.TabBarIsVisible = "False", I disabled it for the user experience and when I return with the BackButtonBehavior the tabbar disappears and this only happens in IOS. VIDEO ATTACHMENT

---
#### Feedback Bot on 9/1/2020, 11:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zack Yang [MSFT] on 9/3/2020, 01:45 AM: 

<p>Thanks for your feedback!<br>
Could you provide a project which can reproduce your issue for us? I’m looking forward to hearing from you!</p>

#### denis20gudiel on 9/3/2020, 01:31 PM: 

<p>With pleasure <a target='_blank' href="https://github.com/Cr15Denis/PruebaShellTabbar">https://github.com/Cr15Denis/PruebaShellTabbar</a></p>

#### Feedback Bot on 9/6/2020, 06:59 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### denis20gudiel solved on 9/3/2020, 01:29 PM, 0 votes: 

<p>With pleasure <a target='_blank' href="https://github.com/Cr15Denis/PruebaShellTabbar">https://github.com/Cr15Denis/PruebaShellTabbar</a></p>

**Comment by Cr15Denis** [comment]
Tabbar hides in the back navigation on IOS.
![Bug BackButtonBehavior (1)](https://user-images.githubusercontent.com/70722700/94583097-4988e880-023a-11eb-920a-2a9734e92b31.gif)

**Comment by Cr15Denis** [comment]
TabBarIsVisible = true does not work with back navigation in ios
![TabbarProblem](https://user-images.githubusercontent.com/70722700/94603407-73023e00-0253-11eb-998e-a9aa7cf4fdae.gif)
