### ISSUE TITLE
[Bug] RadioButton Text not rendering on Android (emulator)...BackgroundColor does not work on UWP.

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12149]
### Description

Text for RadioButton not rendering in any Android emulator
Works fine in UWP 

### Steps to Reproduce

1) Create a radiobutton and run it on any Android emulator
2) Make sure Text color is white and background black (or something similiar)

### Expected Behavior

Text should render

### Actual Behavior

Text does not render.

### Screenshots

<img width="480" alt="Radio" src="https://user-images.githubusercontent.com/19957937/93410904-cab1aa00-f84e-11ea-9280-69465746a73d.png">

**Comment by snowman745** [comment]
I just tried other properties such as BackgroundColor.

While Text does not render on Android, BackgroundColor does not render on UWP (works on Android).

There is a mix of properties of which some work only on Android and some work only on UWP.

Not tested on iOS.

**Comment by holecekp** [comment]
Missing text for RadioButton is a known issue. See https://github.com/xamarin/Xamarin.Forms/issues/11776 for more information and a workaround. The issue has been closed so it is difficult to find it.

**Comment by PureWeen** [comment]
This will be fixed on the 5.0 version of RadioButton
