### ISSUE TITLE
Updating an app to Xam Forms 4.8.0.1364 results in no UI shown

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12145]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1171945/updating-an-app-to-xam-forms-4801364-results-in-no.html)._

---
[severity:Other]
I have updated my existing X.F. app to the current release version of Xam Forms (4.8.0.1364). When I execute the app on either the Android emulator (APIs 29 and 30) or my Samsung S8+, there is nothing showing at all on the device or emulators.

If I add break points in the code, the points are being hit.

Reverting back to 4.8.0.1269 results in the app UI showing as it did before. I have tried removing the bin/obj directories, make clean and every other trick I know

---
#### Feedback Bot on 9/3/2020, 01:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Requested more information from the user on the original ticket

**Comment by PureWeen** [comment]
I don't see anything in the logcat file.

Can you try commenting things out of your MainACtivity and just do a really basic page load to see if that works? See if you can narrow it down? This version has been out for some time and we haven't received any other complaints of this nature

So we'll need a repro to really narrow this down further
