### ISSUE TITLE
tabbedpage in xamarin forms

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12148]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1187453/tabbedpage-in-xamarin-forms.html)._

---
[severity:Other] [regression]
hello
when i creat tabbedpage in xamarin forms 
in xaml when i use ctr+s to review emulator ... tabbedpage created three other contentpage .. means i had six contentpage in emulator while i have 3 contentpage

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Requested Repro from the user

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
