### ISSUE TITLE
Orientation change not working correctly, UseSafeArea not working correctly

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12142]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170225/orientation-change-not-working-correctly-usesafear.html)._

---
There are 2 issues reported which may or may not be related.  

I have a CollectionView, which contains a CollectionView, which contains a FlexLayout.
The top CollectionView is being used as a Carousel to contain the other CollectionViews.
When I use ios:Page.UseSafeArea=&quot;true&quot;, it does not handle adding the additional safe area correctly.
If I turn the iPhone to landscape mode, with the notch on the right, then the right edge of the FlexLayout is cut off by the safe area. The left edge starts at the safe area as it should.
It's as if the FlexLayout does not realize that the area it is to be drawn into, has been made shorter by UseSafeArea.  The row is small enough that it should fit in the space provided, but it is cut off instead.

I am creating the page using mostly code rather than mostly XAML in order to gain flexibility. The XAML file is small as it does not create the CollectionViews. I'm using CSS so there are a couple of style sheets. CreateUI.cs contains code to create some base Views. ScoreSheetCreateUI.cs is the base class for creating CollectionViews. SportScoreSheetCreateUI.cs overrides some of the things in ScoreSheetCreateUI.cs. I've also included a screen shot that demonstrates the cut off portion near the notch.

I have included an entire project which demonstrates the problem. There are also some screen shots included.
If you start in landscape mode in an iPhone 11 simulator, it will demonstrate the right side cut off problem.
If you switch to portrait mode while still in the simulator, with the notch at the top. It will demonstrate a different problem. Each line of the FlexLayout should adjust itself to the narrower width of portrait mode, however it does not.
If you start off in Portrait mode and then switch to Landscape mode, some of the Views appear to be shown twice for the same CollectionView item.
If you run it in an Android simulator, it demonstrates the problem where each line of the FlexLayout should adjust its width back and forth as you go from portrait to landscape mode and back. However it does not.

If you look at the style sheet ScoreSheetPage.css, flex-grow is set to 1 for the Name column. That should cause the Name column to grow to fill available space. If you look at the Name column in portrait mode, it is short. In landscape mode, it is long. It grows too long in landscape mode however, and runs off the view area.

---
#### Feedback Bot on 9/1/2020, 10:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rmarinho** [comment]
Is it possible to provide a small reproduction for this issue? I couldn't find the sample project on

https://developercommunity.visualstudio.com/content/problem/1170225/orientation-change-not-working-correctly-usesafear.html

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
