### ISSUE TITLE
ContentTemplate = "DataTemplate local:AboutPage" Cannot resolve Type "AboutPage

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12143]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1170462/contenttemplate-datatemplate-localaboutpage-cannot.html)._

---
[severity:I'm unable to use this version of Visual Studio]
I started a new Mobil C# Xamarin Project compiled and ran once.
Attempted to run the second time project will not build and can not find the dll 
two errors
CS0006 Metadate file could not be found
XFC0000 Cannot resolve type "AboutPage" 

this is installed by VS2019 Project builder Folder View  AboutPage.xaml 

I have tried to build several project always get same error and your answer is always closed looks like recurring bug. 
or poor unittest.

---
#### Feedback Bot on 9/1/2020, 07:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Theresa Zhang Zhang [MSFT] on 9/3/2020, 02:47 AM: 

<p>Thanks for your feedback!<br>
Could you attach a Diagnostic build output after rebuilding your project?<br>
You can change the build output verbosity from <code>Tools -&gt; Options -&gt; Projects and Solutions -&gt; Build and Run -&gt; MSBuild project build output verbosity</code>, and then copy the content of the Build output pane.</p>

#### Ed Rabenda on 9/4/2020, 08:14 AM: 

<br>```1&gt;------ Rebuild All started: Project: BTFO, Configuration: Debug Any CPU ------<br>1&gt;AppShell.xaml(83,23): XamlC error XFC0000: Cannot resolve type &quot;AboutPage&quot;.<br>1&gt;Done building project &quot;BTFO.csproj&quot; -- FAILED.<br>2&gt;------ Rebuild All started: Project: BTFO.Android, Configuration: Debug Any CPU ------<br>3&gt;------ Skipped Rebuild All: Project: BTFO.iOS, Configuration: Debug iPhone ------<br>3&gt;Project not selected to build for this solution configuration <br>2&gt;CSC : error CS0006: Metadata file &#39;C:\Users\ejrab\source\repos\BTFO\BTFO\bin\Debug\netstandard2.0\ref\BTFO.dll&#39; could not be found<br>========== Rebuild All: 0 succeeded, 2 failed, 1 skipped ==========<br><br>```<br>- 
#### Ed Rabenda on 9/4/2020, 08:17 AM: 

<br>[I:]:                     Tracking android devices started<br>[D:]:                     Tracking avd started<br>[D:]:                     TrackDeviceTask got: emulator-5554	device<br>[D:]:                     avd watcher *.ini path: &#39;C:\Users\ejrab\.android\avd&#39;<br>[I:]:                     Got new device list from adb with 1 devices<br>[D:]:                     avd watcher: got device list from avd with 6 devices<br>[D:RunShellCommand]:      emulator-5554 getprop<br>[D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True<br>[D:]:                     ValidateAndroidNdkLocation: `C:\Program Files (x86)\Android\android-sdk\ndk-bundle`, result=True<br>[D:]:                     ValidateJavaSdkLocation: `C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25`, result=True<br>[D:]:                     $(MonoAndroidToolsDirectory) path `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android` is valid<br>[D:]:                     $(MonoAndroidBinDirectory) path `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\` is valid<br>[D:]:                     mscorlib.dll path `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0` is valid<br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Version.txt` exists=False <br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Version` exists=False <br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\Version.txt` exists=False <br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\Version` exists=False <br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Version.txt` exists=False <br>[D:]:                     GetSdkPath `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Version` exists=True <br>[D:]:                     FindVersionFile: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Version, result=True<br>[I:]:                     Found Xamarin.Android 11.0.2.0<br>[I:]:                     Looking for Android SDK...<br>[D:]:                     ValidateAndroidSdkLocation: `C:\Program Files (x86)\Android\android-sdk`, result=True<br><br>1&gt;------ Rebuild All started: Project: BTFO, Configuration: Debug Any CPU ------<br>1&gt;AppShell.xaml(83,23): XamlC error XFC0000: Cannot resolve type &quot;AboutPage&quot;.<br>1&gt;Done building project &quot;BTFO.csproj&quot; -- FAILED.<br>2&gt;------ Rebuild All started: Project: BTFO.Android, Configuration: Debug Any CPU ------<br>3&gt;------ Skipped Rebuild All: Project: BTFO.iOS, Configuration: Debug iPhone ------<br>3&gt;Project not selected to build for this solution configuration <br>2&gt;CSC : error CS0006: Metadata file &#39;C:\Users\ejrab\source\repos\BTFO\BTFO\bin\Debug\netstandard2.0\ref\BTFO.dll&#39; could not be found<br>========== Rebuild All: 0 succeeded, 2 failed, 1 skipped ==========
#### Enbi Zhang Zhang [MSFT] on 9/9/2020, 11:11 PM: 

<p><a rel="user" href="https://developercommunity.visualstudio.com/users/281954/c69b10b2-368d-6529-ba53-1d7a1f192915.html" nodeid="281954">@Ed Rabenda</a> The information is not the diagnostic build output. Please go to 'Tools-&gt;Options-&gt;Projects and Solution-&gt;Build and Run-&gt;MSBuild project build output verbosity' and change the verbosity to "Diagnostic" then rebuild your project. After build finished, copy the content of the build output pane.</p>

#### Feedback Bot on 9/9/2020, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rmarinho** [comment]
What version of Visual Studio are you using?

Can you upload the small repo you are using?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
