### ISSUE TITLE
[Bug] Image.Source doesn't work with "http" URLs 

### ISSUE THREAD

**Issue by bricefriha** [xamarin/Xamarin.Forms#12157]
### Description
Hi everyone! 😃
When I use ``` <Image /> ``` to show an image from an HTTP URL the image doesn't appear however with HTTPS URLs it works perfectly.
I don't if it has been made on purpose (maybe for security reasons 🤷🏽‍♂️) but It's a problem when I want to test my app using an image stored in a personal server (or even in localhost) which doesn't have an SSL certificate.
I found the issue on Android and iOS.

### Steps to Reproduce

1. In your .xaml file put:
```XAML
<StackLayout>
   <!-- The HTTP one -->
   <Image Source="[ insert a HTTP url]" />

   <!-- The HTTPS one -->
   <Image Source="https://vacuumsealer.id/wp-content/uploads/2019/03/Benih-sayur-Wortel-Super.jpg" />
</StackLayout>
``` 
2. Run the app

### Expected Behavior
We should see both images.

### Actual Behavior
We see actually only one image. (the https one)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Enterprise Preview
- Platform Target Frameworks: Xamarin.forms 4.8.0.1451
- Affected DiPhone: Iphone SE 2020 (iOS), Xiaomi Mi9T (Android)

**Comment by PureWeen** [comment]
AFAIK this is enforced by the native platforms and you have to change settings on each platform to allow for http

For example
https://stackoverflow.com/a/51902630
https://stackoverflow.com/a/40299837
