### ISSUE TITLE
[Bug] Switch control not respecting Material Design on Android

### ISSUE THREAD

**Issue by Depechie** [xamarin/Xamarin.Forms#12150]
### Description

When using the `Switch` control in Xamarin Forms, we are able to change the `ThumbColor`. When setting this to `White` and also using `White` for the `ContentPage` `BackgroundColor`, you'll notice that the drop shadow of the `Switch` is gone. According to the Android Material design guidelines, the default Android implementation has this drop shadow.

Reference material from Android with also showing a White example:
https://material.io/develop/android/components/switches
https://material.io/design/interaction/states.html#usage

### Steps to Reproduce

1. Open the https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SwitchDemos demo
2. Change the Switch control on the SwitchXamlPage to have a ThumbColor set to White, change the ContentPage BackgroundColor also to White
3. Run the demo

### Expected Behavior

Switch control should have drop shadow and a border around the thumb circle.

### Actual Behavior

No border or drop shadow can be seen

### Basic Information

- Version with issue: 4.8

### Screenshots

<img width="406" alt="Screenshot 2020-09-17 at 09 23 41" src="https://user-images.githubusercontent.com/351693/93434686-c1652380-f8c8-11ea-921c-6bc04031031f.png">

**Comment by Jagan2412** [comment]
Facing same issue

**Comment by tossingc** [comment]
This issue arose when we switched the Android target to 10.0 (API 29) - TargetFrameworkVersion -> v10.0 and targetSdkVersion -> 29.

_Prior to making that one change, there was a shadow under the white thumb on a white background._

Screenshot from when we were targeting v9.0 (API 28):
![image](https://user-images.githubusercontent.com/847707/121220301-1b888900-c84a-11eb-86b7-9a3e8155920a.png)
