### ISSUE TITLE
[Bug] ApplyTintColor throws exception on iPhone 5 

### ISSUE THREAD

**Issue by Soundman32** [xamarin/Xamarin.Forms#12155]
### Description
When I use `image.ApplyTintColor` on an iPhone 5 (V12.0.1), I get an exception NSInvalidArgumentException

### Steps to Reproduce

            var image = UIImage.FromBundle(element.Image);
            image.ApplyTintColor(element.ImageTintColor.ToUIColor());

### Expected Behavior
   Image should be tinted
### Actual Behavior
   Exception thrown:
NSInvalidArgumentException (wrapped in FoundationMonoTouchException)

### Basic Information

- Version with issue: V4.7.0.1260

- Last known good version: ???
- IDE: VS2019 Mac
- Platform Target Frameworks: 
  - iOS:  Xcode 11.6 (11E708)
- Affected Devices: iPhone 5

### Workaround
Try/catch around image.ApplyTintColor

**Comment by PureWeen** [comment]
This wouldn't be a bug with Forms since the exception is coming from the native iOS API

If you think this is a bug with Xamarin.iOS then can you log a bug with a repro here
https://github.com/xamarin/xamarin-macios
