### ISSUE TITLE
Editor don't show Text set in Constructor of Page

### ISSUE THREAD

**Issue by TFreudi1** [xamarin/Xamarin.Forms#12166]
Setting Editor.text = "XXX" in Page Constructor don't work at least on Android platform.
Steps to reproduce:
Create a simple Xamarins Forms Projekt, place a Editor on the Page, set text in code behind like this:
public partial class test : ContentPage
{
     public test()
    {
         InitializeComponent();
         myEditor.Text = "Should show on Page";
    }
}

**Comment by PureWeen** [comment]
[App16.zip](https://github.com/xamarin/Xamarin.Forms/files/5246691/App16.zip)

@TFreudi1 can you attach a repro please? I've attached a project with your sample and I'm not seeing what you're seeing

**Comment by TFreudi1** [comment]
@PureWeen With your project it works like it should.  I have a little more complex design with lot's of pages and because I had problems with memory leaks (1-2 years ago ) I hold the pages in variable which solved the memory problem  for me.

if (pageBaumFaellung == null)
    pageBaumFaellung = new BaumFaellung();
pageBaumFaellung.Init(); // Setting editor.text here don't work.

await navpage_baum.Navigation.PushModalAsync(pageBaumFaellung);

I will extend your App16 project to that and will upload it tomorrow.

**Comment by TFreudi1** [comment]
@PureWeen : You can close it I can't reproduce it with a simple project only in my production app with many forms. I solved there with a timer:
`public void init()
{
 Device.StartTimer(new TimeSpan(500), () =>
            {
                edt_faellung_bemerkung.Text = ((FISA.MainPage)App.Current.MainPage).g_CurrentTree.sFaellgrund;
                return false;
            });
.....`

I updated your project with my code and linked here, but everytime I press the button in the MainPage, the text is changing as it should which ist not the case with the same logic in my production App. I can live with the DeviceTimer Solution. Thanks
[App16.zip](https://github.com/xamarin/Xamarin.Forms/files/5255950/App16.zip)
