### ISSUE TITLE
[Enhancement] Implement PreviewKeyDown

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12168]
## Summary
Simply to provide an event like [PreviewKeyDown](https://docs.microsoft.com/en-us/dotnet/api/system.windows.uielement.previewkeydown?view=netframework-4.7.2) already available in wpf.

## Intended Use Case
As example: conditionally modify a `Text ` property of an `Entry ` while user is typing and before even being displayed or raising `KeyDown ` event or setting the property.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
