### ISSUE TITLE
[Bug] Xamarin Application does not start up when CollectionView is included in ScrollView and ScrollView's Visible is False

### ISSUE THREAD

**Issue by ibocon** [xamarin/Xamarin.Forms#12164]
### Description
ContentPage stop responding when CollectionView is included in ScrollView and ScrollView's Visible is False

### Steps to Reproduce

1. Create blank Xamarin.Froms project
2. add code below

MainPage
```
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:Test="clr-namespace:CollectionViewTest"
    x:Class="CollectionViewTest.MainPage">
        <ScrollView IsVisible="True">
        <CollectionView
            ItemsSource="{Binding ItemSource}"
            SelectionMode="Single">

            <CollectionView.ItemsLayout>
                <GridItemsLayout
                    Orientation="Vertical"
                    Span="4"
                    VerticalItemSpacing="10"/>
            </CollectionView.ItemsLayout>

            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Image
                        Source="{Test:ImageResource CollectionViewTest.waterfront.jpg}"
                        Aspect="AspectFit"
                        WidthRequest="70"
                        HeightRequest="70"/>
                </DataTemplate>
            </CollectionView.ItemTemplate>

        </CollectionView>
    </ScrollView>
</ContentPage>
```

MainPageViewModel
```
    public class MainPageViewModel : INotifyPropertyChanged
    {
        private ObservableCollection<object> _itemSource;
        public ObservableCollection<object> ItemSource => _itemSource;

        public MainPageViewModel()
        {
            _itemSource = new ObservableCollection<object>();
            for (int i = 0; i < 28; i++)
                _itemSource.Add(new object());
        }

        public event PropertyChangedEventHandler PropertyChanged;
        private void NotifyPropertyChanged([CallerMemberName] String propertyName = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
```
3. Start debug iOS project

### Expected Behavior

Application start.

### Actual Behavior

Application does not response.

### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version: none
- IDE: Visual Studio for Mac Professional 8.7.7 (build 10)

- Platform Target Frameworks: 
  - iOS:  11
- Nuget Packages:
  - None
- Affected Devices:
  - All iOS device include iPad.

### Reproduction Link

[Github](https://github.com/ibocon/StackOverflow/tree/63951109)

### Workaround

```
            <CollectionView.ItemsLayout>
                <GridItemsLayout
                    Orientation="Vertical"
                    Span="4" <-- change to 1, but this is not a good idea for UX...
                    VerticalItemSpacing="10"/>
            </CollectionView.ItemsLayout>
```

**Comment by rmarinho** [comment]
Hello @ibocon  i just tested your code and it works fine. I notice IsVisible is true on the sample code, but in your comment you say is false.

Also why would you need to wrap CollectionView on ScrollView , that's not recommended. 

![image](https://user-images.githubusercontent.com/1235097/93879473-ac76fe80-fcd3-11ea-9868-6948ec86274a.png)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
