### ISSUE TITLE
[Enhancement] Support Dual Screens in Project Templates

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#12176]
I would like to see support for the new TwoPaneView control for Dual Screens included in the existing project templates.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
