### ISSUE TITLE
[Enhancement] Use graphics api to draw controls and discard controls based on platform gui api

### ISSUE THREAD

**Issue by JohnHe404** [xamarin/Xamarin.Forms#12178]
## Summary
The controls based on the platform ui api are not as stable as the controls based on the graphics api, and are easy to extend. Based on a few simple controls, users construct complex controls by themselves.

Considering that javascript and css can be called in ui,

**Comment by rmarinho** [comment]
Hi, what UI API are you referring ?

**Comment by HeMinzhang** [comment]
It's just a new type of ui I thought of at the time.

**Comment by HeMinzhang** [comment]
I thought of more, html5, typescript.
