### ISSUE TITLE
Android - Updating CornerRadius of BoxView clears the background color / drawable

### ISSUE THREAD

**Issue by markmccaigue** [xamarin/Xamarin.Forms#12172]
### Description
Android - Updating CornerRadius of BoxView clears the background color / drawable

### Steps to Reproduce

1. Render a boxview with a background color
2. Update the corner radius
3. Observe the color is gone from the boxview, and it cannot be seen

### Expected Behavior
Original color is retained

### Actual Behavior
Color is removed

### Basic Information

- Version with issue: 4.8.0.1451

### Reproduction Link

https://github.com/markmccaigue/formsboxviewcornerradiusbug

**Comment by rmarinho** [comment]
Duplicated of #12061
