### ISSUE TITLE
[Enhancement] Implement ConverterCulture for bindings

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12181]
## Summary
To provide [ConverterCulture](https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.binding.converterculture?view=netcore-3.1) for bindings, supported in wpf. 

## Intended Use Case
Example usage: `Text="{Binding SomeBinding, StringFormat={}{0:N}, ConverterCulture=de-DE}"`

**Comment by jfversluis** [comment]
This won't be happening for Forms anymore, but let's open this for .NET MAUI. I like this idea!

**Comment by jfversluis** [comment]
Opened proposal for .NET MAUI: https://github.com/dotnet/maui/issues/5696
