### ISSUE TITLE
[Bug] CollectionView should also update the SelectedItems - even if SelectionMode="Single"

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#12182]
## Description

When doing binding, I notice that the selection no longer works when setting the `SelectionMode="Single"` AND `SelectedItems="{Binding SelectedFilters}"`. I would expect that even if there is only a single selection, the behaviour does not change.

Now I have to create 2 paths of code, depending on the mode - when I could have one with a collection.

### Steps to Reproduce

1. Add a CV
2. Add items
3. Bind to `SelectedItems`
4. Set `SelectionMode="Single"`
5. Select an item
6. Observe that the collection never gets items.

### Expected Behavior

The selection is added/changed to the list.

### Actual Behavior

Nothing happens.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: I am testing my app on this one so far.
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment]
It also took me a while to actually test this because I was using an observable collection of `<T>` when there is also #8323

**Comment by hartez** [comment]
If you're using `SelectionMode="Single"`, you need to use `SelectedItem`; if you're using `SelectionMode="Multiple"`, you need to use `SelectedItems`. 

This is by design.
