### ISSUE TITLE
[Bug]  CollectionView scroll jump to up every ItemsSource update

### ISSUE THREAD

**Issue by kerbooo** [xamarin/Xamarin.Forms#12180]
Hello,

1. I am getting remote api into CollectionView every 30 seconds using List or ObservableCollection.
2. After every data update CollectionView is jumping to up of screen. I mean ItemSource is refreshing.
3. But this behavior does not appear in ListView with same code settings

I have used  `ItemsUpdatingScrollMode` but nothing changed.

My XF version is 4.8 and test platform is Android. Android API 29 (Android X)

Thank you in advance.

**Comment by rmarinho** [comment]
Hi @kerbooo  can you please upload  a small reproduction of the issue so we can analyze? 

Thanks

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by mayank2961992** [comment]
CollectionView scroll jump to up every ItemsSource update only for Android, Working fine for iOS
