### ISSUE TITLE
[Enhancement] Google Play In-App Review

### ISSUE THREAD

**Issue by mariohik** [xamarin/Xamarin.Forms#12194]
## Summary
In-App Review for Xamarin.Forms
[Google Play In-App Review API](https://developer.android.com/guide/playcore/in-app-review)
[Integrate In-App Reviews for Java](https://developer.android.com/guide/playcore/in-app-review/kotlin-java#java)

## Intended Use Case
Prompt users to submit Play Store ratings and reviews without the inconvenience of leaving your app or game.

**Comment by rmarinho** [comment]
can you please extend a little bit de description by explaining what you think we should provide? 

thanks

**Comment by mariohik** [comment]
@rmarinho maybe it's best we have this on Xamarin.Essentials. I've opened a feature request there.
