### ISSUE TITLE
[Bug] CarouselView content disappears after 2 rotations if  TextType=Html is used

### ISSUE THREAD

**Issue by Sasha111ua** [xamarin/Xamarin.Forms#12193]
The content of the carousel disappears if you rotate the phone to any side and then back. It happens only if inside template you use label with texttype=html, if textype=text everything works.
Tested IOS only

### Steps to Reproduce

1.  Start application
2.  Rotate device to the left.
3.  Rotate it back.

### Expected Behavior
The content is visible

### Actual Behavior
Screen is empty

### Reproduction Link

https://drive.google.com/file/d/17ONttYq2rwiIoQ11QWsy1YXkgE22DBf1/view?usp=sharing

**Comment by rmarinho** [comment]
![image](https://user-images.githubusercontent.com/1235097/93788731-e808be80-fc28-11ea-8969-cb2298f9beda.png)

**Comment by Sasha111ua** [comment]
https://drive.google.com/file/d/17ONttYq2rwiIoQ11QWsy1YXkgE22DBf1/view?usp=sharing try again, please

**Comment by VladislavAntonyuk** [comment]
I have similar issue.
```xml
<CarouselView
			IndicatorView="{Reference Name=Indicator}"
			IsSwipeEnabled="False"
			Position="{Binding Position}"
			VerticalOptions="FillAndExpand">
			<CarouselView.ItemsSource>
				<x:Array Type="{x:Type ContentView}">
					<View1 />
					<View2 />
					<View3 />
				</x:Array>
			</CarouselView.ItemsSource>
			<CarouselView.ItemTemplate>
				<DataTemplate>
					<ContentView Content="{Binding .}" />
				</DataTemplate>
			</CarouselView.ItemTemplate>
		</CarouselView>
```
when I navigate : View1->View2->View3->View2-View1 . View1 on the last step in blank. navigating forward again shows View2 but View 3 is blank.

**Comment by vtkachen111** [comment]
I am actually still finding this issue on XF 5.0.0.1874 on both ios and android... no matter what content i put within carouselview... swipe right twice, swipe back once, blank screen, then 2 more rights and another blank screen.

**Comment by eamonn-alphin** [comment]
I was having this issue with a contentView inside my carousel. 2 list items, tapping the first will scroll to the next, but tapping a 'back' button on the second will scroll "back" to an empty view. I may have resolved it by setting Loop and IsSwipeEnabled to false.

**Comment by kosozhihin** [comment]
Yes, we're experiencing this on XF 5.0.0.2196 as well. Setting Loop to false does fix it, but it seems that the bug is still there. This should be reopened.
