### ISSUE TITLE
[Enhancement] Provide app-wide status bar color and theme options in Xamarin.Forms

### ISSUE THREAD

**Issue by mikeparker104** [xamarin/Xamarin.Forms#12205]
## Summary
The enhancement described in issue [#7314](https://github.com/xamarin/Xamarin.Forms/issues/7314) proposes the ability to set the StatusBar color and theme for Android and iOS from any Page. 
 
It would be ideal to have the ability to set this globally for the application while being able override that on a page-by-page basis. 

## API Changes

In addition to the changes suggested in issue [#7314](https://github.com/xamarin/Xamarin.Forms/issues/7314):
 
App.SetStatusBarLightTheme();
App.SetStatusBarDarkTheme();
App.SetStatusBarColor(Color color);

## Intended Use Case
Greater control over application styling from Xamarin.Forms removing the need to handle separately in each platform target.

**Comment by maxkoshevoi** [comment]
You can do this with what's described in the #7314 

1) To set global status bar color add this to `App.xaml`
```xaml
<Style TargetType="Page" ApplyToDerivedTypes="True">
    <Setter Property="StatusBarColor" Value="{DynamicResource StatusBarColor}" />
</Style>
```
2) If you want to override global setting for some specific page, you can set `StatusBarColor` for that page directly (this will override styles set in `App.xaml`). Also you can create named styles and apply them to subset of pages.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
