### ISSUE TITLE
[Enhancement] Provide a Blank Forms Shell App template

### ISSUE THREAD

**Issue by mikeparker104** [xamarin/Xamarin.Forms#12204]
## Summary
The current Shell App Template provides some helpful sample classes and content to aid in familiarization and getting started. However, it would be ideal to have a version of this template that does not include the sample content analogous to the Blank Forms App template.

## API Changes

New Visual Studio template without sample classes and content.

## Intended Use Case
For situations where alternative approaches, frameworks, or foundational components are used avoiding the need to first remove the sample classes and content.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
