### ISSUE TITLE
[Bug] Binding does not work to an IDictionary inside an IDictionary (ExpandoObject inside ExpandoObject)

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#12201]
### Description

I have a requirement to create views on the runtime using C# which includes entries, datepickers, etc. 

My VM is:

```
    public class Record : Securable, ICloneable, INotifyPropertyChanged
    { 
        public event PropertyChangedEventHandler PropertyChanged;
        public string FormName { get; set; }
        public ExpandoObject Contents { get; set; }
    }
```

I need to be able to data-bind to Keys and Values inside the Contents.

I can bind to first level objects such as:

` entry.SetBinding(Entry.TextProperty, new Binding($"CurrentRecord.Contents[{id}]", BindingMode.TwoWay));`

And it works beautifully well, but when I try to do something like 

`editableEntry.SetBinding(Entry.TextProperty, new Binding($"Context.Instance.CurrentRecord.Contents[{id}][{editableEntry.StyleId}]", BindingMode.TwoWay));`

It silently fails and when I type values inside the entry, it does not update the contents inside Context.Instance.CurrentRecord.Contents[id] object

I have ensured that the 2nd level keys do exist and I can in fact update them from code behind, but the UI does not update. 

When doing the same for 1st level keys, it works flawlessly.  

Summary:

Binding to an ExpandoObject WORKS
Binding to an ExpandoObject inside ExpandoObject DOES NOT WORK

### Basic Information

- Version with issue:  4.8
- Last known good version: N/A
- IDE: Jetbrains Rider
- Platform Target Frameworks: 
I have only tested that on iOS but since it's a Xamarin.Forms issues, I think it should be present across all platforms.

**Comment by rmarinho** [comment]
Hi @amirvenus  do you mind upload a small reproduction of the issue so we can check better what's happening. 

thanks

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by amirvenus** [comment]
Hi,

I have uploaded a test repo with minimal code to reproduce this bug:

https://github.com/amirvenus/TestDoubleExpando

As you see, I have three labels on the page:

Here is the XAML:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TestDoubleExpando.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TestDoubleExpando"
    BindingContext="{Binding Source={x:Static local:ViewModel.Instance}}">
    <StackLayout BackgroundColor="Black" VerticalOptions="CenterAndExpand">
        <Label
            FontSize="36"
            HorizontalTextAlignment="Center"
            Text="{Binding Username}"
            TextColor="Red" />
        <Label
            x:Name="LabelWithExpando"
            FontSize="36"
            HorizontalTextAlignment="Center"
            TextColor="Red" />
        <Label
            x:Name="LabelWithExpando2"
            FontSize="36"
            HorizontalTextAlignment="Center"
            TextColor="Red" />
    </StackLayout>
</ContentPage>
```

And the code behind:

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Dynamic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TestDoubleExpando
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        protected override async void OnAppearing()
        {
            base.OnAppearing();
            while(true)
            {
                ViewModel.Instance.Username = DateTime.Now.ToLongTimeString();
                
var nameOfExpandoKey = "Dt";
ViewModel.Instance.Expando = new System.Dynamic.ExpandoObject();
(ViewModel.Instance.Expando as IDictionary<string, object>).Add(nameOfExpandoKey, DateTime.Now.ToLongTimeString());
LabelWithExpando.SetBinding(Label.TextProperty, $"Expando[{nameOfExpandoKey}]");
var nameOfNestedExpandoKey = "Nested";
(ViewModel.Instance.Expando as IDictionary<string, object>).Add(nameOfNestedExpandoKey, new ExpandoObject());
var nameOfSecondNestedKey = "Nested2";
((ViewModel.Instance.Expando as IDictionary<string, object>)[nameOfNestedExpandoKey] as IDictionary<string, object>).Add(nameOfSecondNestedKey, DateTime.Now.ToLongTimeString());
LabelWithExpando2.SetBinding(Label.TextProperty, $"Expando[{nameOfExpandoKey}][{nameOfNestedExpandoKey}][{nameOfSecondNestedKey}]");
await Task.Delay(1500);
            }
            
        }
    }
}

```

And my ViewModel:

```
using System;
using System.ComponentModel;
using System.Dynamic;
using System.Runtime.CompilerServices;

namespace TestDoubleExpando
{
    public class ViewModel : INotifyPropertyChanged
    {
        private static ViewModel _instance;

        public static ViewModel Instance => _instance ??= new ViewModel();

        public event PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var propertyChanged = PropertyChanged;
            propertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        private string _username;
        public string Username
        {
            get => _username;
            set
            {
                _username = value;
                OnPropertyChanged(nameof(Username));
            }
        }

        private ExpandoObject _expando;
        public ExpandoObject Expando
        {
            get => _expando ??= new ExpandoObject();
            set
            {
                _expando = value;
                OnPropertyChanged(nameof(Expando));
            }
        }

    }
}
```


As you see, the first two labels work, but the third one doesn't!:

![image](https://user-images.githubusercontent.com/5879559/97224446-0da95a80-17c9-11eb-8c62-1a4771a665d9.png)

**Comment by amirvenus** [comment]
> Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

I have added a test repo and sample code. Please reopen this issue.

Thanks!
