### ISSUE TITLE
[Enhancement] Sticky headers option for CollectionView with greater control over group header position

### ISSUE THREAD

**Issue by mikeparker104** [xamarin/Xamarin.Forms#12209]
## Summary
CollectionView already supports [group headers](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/collectionview/grouping#customize-the-group-header). However, the group headers can only appear at the top of each group for vertical orientation and to the left of the group for horizontal orientation. The headers also scroll along with the items.

A custom control is required to achieve the following design requirements:

1. Support for sticky group headers
2. Displaying group headers above (or below) the group items for horizontal orientation
3. Displaying group headers to the left (or right) of the group items for vertical orientation

A similar request for sticky group headers functionality has been raised in #8656. Having greater control over the position of the group headers in addition to this would be ideal. 

Indicative user experience (top-aligned sticky headers for horizontal orientation):

<p>
<img src="https://user-images.githubusercontent.com/12763221/93892491-7c842700-fce4-11ea-811e-773b0432171f.gif" alt="Indicative sticky group header position experience" height="225" style="display:inline-block;" />

## API Changes

The position and enabling of sticky headers could be specified using the following additional properties:

GroupHeaderAxisOptions GroupHeaderAxis { get; set; }

- Main (default)
- Cross 

GroupHeaderAxisAlignmentOptions GroupHeaderCrossAxisAlignment  { get; set; }

- Start (default)
- End

bool UseStickyGroupHeaders { get; set; } 

These properties might be exposed on the existing [GridItemsLayout](https://docs.microsoft.com/dotnet/api/xamarin.forms.griditemslayout?view=xamarin-forms) or on a new [ItemsLayout](https://docs.microsoft.com/dotnet/api/xamarin.forms.itemslayout?view=xamarin-forms) implementation.

### HEADER POSITION

The resulting header position would vary based on the specified **Orientation** and maintain the current behavior by default. 

#### SCENARIO A:

In this scenario, there are no changes to the default behavior since **GroupHeaderAxisOptions** defaults to **Main** and **GroupHeaderCrossAxisAlignment** defaults to **Start**. Headers appear at the top of each group for vertical orientation and to the left of the group for horizontal orientation.

**Orientation:** Vertical

<p>
<img src="https://user-images.githubusercontent.com/12763221/93905837-5619b800-fcf3-11ea-9001-e6ef3542c3bd.png" alt="scenario a illustration" height="600" style="display:inline-block;" />

**Orientation:** Horizontal

<p>
<img src="https://user-images.githubusercontent.com/12763221/93904593-e8b95780-fcf1-11ea-8fd0-cac64b6cc745.png" alt="scenario a illustration" height="350" style="display:inline-block;" />

#### SCENARIO B:

In this scenario, **GroupHeaderAxis** is set to **Cross** with **GroupHeaderCrossAxisAlignment** still set to its default **Start** value. Headers now appear to the left of each group for vertical orientation and at the top of the group for horizontal orientation.

**Orientation:** Vertical
**GroupHeaderAxis:** Cross

<p>
<img src="https://user-images.githubusercontent.com/12763221/93905641-18b52a80-fcf3-11ea-86fb-d08651b6e6ba.png" alt="scenario b vertical illustration" height="490" style="display:inline-block;" />

**Orientation:** Horizontal
**GroupHeaderAxis:** Cross

<p>
<img src="https://user-images.githubusercontent.com/12763221/93906188-cd4f4c00-fcf3-11ea-96ec-c353d0f76e2f.png" alt="scenario b horizontal illustration" height="350" style="display:inline-block;" />

#### SCENARIO C:

In this scenario, **GroupHeaderAxis** is set to **Cross** with **GroupHeaderCrossAxisAlignment** now set to **End**. Headers now appear to the right of each group for vertical orientation and at the bottom of the group for horizontal orientation.

**Orientation:** Vertical
**GroupHeaderAxis:** Cross
**GroupHeaderCrossAxisAlignment:** End

<p>
<img src="https://user-images.githubusercontent.com/12763221/93906445-1b644f80-fcf4-11ea-9e0f-bdc4165095ed.png" alt="scenario c vertical illustration" height="490" style="display:inline-block;" />

**Orientation:** Horizontal
**GroupHeaderAxis:** Cross
**GroupHeaderCrossAxisAlignment:** End

<p>
<img src="https://user-images.githubusercontent.com/12763221/93906497-29b26b80-fcf4-11ea-89f5-2304042040da.png" alt="scenario c horizontal illustration" height="350" style="display:inline-block;" />

### STICKY HEADERS

Sticky headers could be switched on and off using the **UseStickyGroupHeaders** property. Having a default value of **false**, the current behavior would be maintained unless this property is set explicitly. 

The sticky header behavior, described in [#8656](https://github.com/xamarin/Xamarin.Forms/issues/8656), is appropriate when **GroupHeaderAxis** is not set explicitly or is set to the default **Main** value. 

![sticky_header_proposal_from_issue_8656](https://github.com/xamcat/Scratch/raw/master/FormsStickyHeaders/Videos/FormsStickyHeaders.gif)

The following scenarios demonstrate how the sticky header behavior would manifest itself when **GroupHeaderAxis** is set to **Cross**. The scenarios use the following configuration as an example and is based on having a [Label](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/text/label) set for the group header:

**Orientation:** Horizontal
**GroupHeaderAxis:** Cross
**GroupHeaderAxisAlignment:** Start

#### SCENARIO D:

In this scenario, there are no changes to the default header scrolling behavior since **UseStickyGroupHeaders** defaults to **false**. Based on the current configuration (above), headers appear at the top of each group and scrolls along with its items.

<p>
<img src="https://user-images.githubusercontent.com/12763221/93907130-df7dba00-fcf4-11ea-9a26-536e596f4911.png" alt="scenario d illustration" height="450" style="display:inline-block;" />

#### SCENARIO E:

In this scenario, **UseStickyGroupHeaders** is set to **true**. Based on the current configuration (above), headers still appear at the top of each group. However, a group's header content remains in place as the content scrolls if it represents the left-most group. When the header content reaches the start or end of its items it scrolls along with its items in that direction of travel.

<p>
<img src="https://user-images.githubusercontent.com/12763221/93907253-02a86980-fcf5-11ea-8c7a-01b87201bc04.png" alt="scenario e illustration" height="450" style="display:inline-block;" />

**NOTE:** Scenario E represents the same experience illustrated in the graphic within the [Summary](#summary).

## Intended Use Case
Supporting a broader set of design requirements without the need for custom code.

**Comment by LucaZiegler** [comment]
Another example from the Google I/O 2019 App with sticky text:


https://user-images.githubusercontent.com/36471502/103289364-4b07af80-49e7-11eb-8fa4-7cad20a94303.mp4

**Comment by Sinishisimus** [comment]
+1 upvoting this

**Comment by demoh2019** [comment]
+1

**Comment by uzairali001** [comment]
This feature will be really useful in lot of situations, hopping to get it soon.

**Comment by nicolasHul** [comment]
+1

**Comment by BartoGabriel** [comment]
+1

**Comment by MrMacvos** [comment]
+1

**Comment by angelru** [comment]
I'm still looking for a way to implement a header like it has instagram in the profile part. While scrolling the photos then you have the tabs above photos, reels etc etc

**Comment by Cvijo** [comment]
+1 this would be awesome

**Comment by LeoJHarris** [comment]
👍

**Comment by chenxx08** [comment]
+1111

**Comment by chaoyebugao** [comment]
+1

**Comment by luisabreu84** [comment]
+1

**Comment by Zve** [comment]
+1

**Comment by nicolasHul** [comment]
+1

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by eli191** [comment]
All these kind of functionalities, as scroll to a group header are not discarded with a "Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms." BUT are not even taken into account in MAUI.

**Comment by heribertolugo** [comment]
> All these kind of functionalities, as scroll to a group header are not discarded with a "Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms." BUT are not even taken into account in MAUI.

i was just thinking that. twice today i have seen this exact same thing. you would think that with the number of votes, someone on their team wouldve ported this issue to the maui repo. im unsure of their logic and reasoning for not doing so. what makes them think it was important to developers before but may not be important now? is maui missing this feature? yes -> then port it over, as maui is xamarin's replacement.
