### ISSUE TITLE
[Enhancement] add RemoveStyleSheet or ReplaceStyleSheet methods in ResourceDictionary

### ISSUE THREAD

**Issue by SergTomcat** [xamarin/Xamarin.Forms#12210]
## Summary
_Xamarin.Forms.ResourceDictionary_ class has **Add** method that adds new **StyleSheet** to **StyleSheets** internal list. It would be awesome if there were also _RemoveStyleSheet_ , _ClearStyleSheets_ or _ReplaceStyleSheet_ method; or Add method could replace old stylesheet.

## API Changes

Currently there is _Add_ method:

```
public void Add(StyleSheet styleSheet)
{
	StyleSheets = (StyleSheets ?? new List<StyleSheet>(2));
	StyleSheets.Add(styleSheet);
	this.ValuesChanged?.Invoke(this, ResourcesChangedEventArgs.StyleSheets);
}
```

It's really needed something like that:

```
public void RemoveStyleSheet(StyleSheet styleSheet)
{
	if (StyleSheets != null && StyleSheets.Remove(styleSheet))
	{
		this.ValuesChanged?.Invoke(this, ResourcesChangedEventArgs.StyleSheets);
	}
}

public void ReplaceStyleSheet(StyleSheet styleSheet)
{
	StyleSheets = new List<StyleSheet>(2) { styleSheet };
	this.ValuesChanged?.Invoke(this, ResourcesChangedEventArgs.StyleSheets);	
}
// more flexible
public void ReplaceStyleSheets(IList<StyleSheet> lStyleSheets)
{
	StyleSheets = lStyleSheets;
	this.ValuesChanged?.Invoke(this, ResourcesChangedEventArgs.StyleSheets);	
}

public void ClearStyleSheets()
{
	StyleSheets = null;
	this.ValuesChanged?.Invoke(this, ResourcesChangedEventArgs.StyleSheets);
}
```		

## Intended Use Case
```
currentResourceDictionary.ClearStyleSheets();
currentResourceDictionary.Add(newStyleSheet);
// or even better
currentResourceDictionary.ReplaceStyleSheet(newStyleSheet);
```

It's not important how it would be implemented or called, but there's a need to manipulate stylesheets and clear old ones. Today we can only add them.

Exposing both StyleSheets list and StyleSheetsCollectionChanged event would be even easier, but anything will do.

Thank you in advance.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
