### ISSUE TITLE
[Bug] Regression: setting BoxView Color often has no effect on UWP

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#12214]
Setting the Color property on a BoxView often has no effect on UWP. It seems to work the first time it is set, but not subsequently. BoxView was broken and fixed recently (https://github.com/xamarin/Xamarin.Forms/pull/10540) but has regressed again.

4.8.0.1364: doesn't work
4.8.0.1269: doesn't work
4.7.0.1351: works

The regression may have been introduced by work on Shapes and Brushes ([BoxViewRenderer.cs
 history](https://github.com/xamarin/Xamarin.Forms/commits/3a57e2e0200d5351e85d09d4f693fe65a7a4a8e8/Xamarin.Forms.Platform.UAP/BoxViewRenderer.cs)) @jsuarezruiz .

### Reproduction:
```fsharp
do  base.MainPage <-
        let bv = BoxView(Color = Color.Orange, HeightRequest = 200.)
        let button =
            Button(Text = "Make BoxView black",
                Click = (fun () -> bv.Color <- Color.Black))
        let sl = StackLayout(Views = [bv; button])
        ContentPage(Content = sl)
```
Clicking on the button has no effect.

**Comment by rmarinho** [comment]
Hi @charlesroddie  i tried to reproduce your issue but wasn't able to. Can you help me understand how to reproduce? 

Thanks

[App13-boxview.zip](https://github.com/xamarin/Xamarin.Forms/files/5275912/App13-boxview.zip)

**Comment by charlesroddie** [comment]
Sorry this is a false alarm. Thanks for testing @rmarinho. I discovered we had a workaround in our code that can be removed now. Somehow it interacted with the update.

```csharp
// Use old BoxViewRenderer until https://github.com/xamarin/Xamarin.Forms/issues/10528 is fixed
[assembly: Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(Xamarin.Forms.BoxView), typeof(Xamarin.Forms.Platform.UWP.BoxViewRenderer))]
```

**Comment by charlesroddie** [comment]
Since  Xamarin.Forms.Platform.UWP.BoxViewBorderRenderer is used now, Xamarin.Forms.Platform.UWP.BoxViewRenderer can be removed.
