### ISSUE TITLE
[Bug] iOS 14.0  No entry is created in Device settings

### ISSUE THREAD

**Issue by DaniRvd** [xamarin/Xamarin.Forms#12216]
### Description
Hello guys! I developed an enterprise app and updated my iPad Air 2 to iPadOS 14 to test the app's compatibility with this brand new operating system, but after updating the operating system I reinstalled the app and I saw that I didn't have an entry for the app in device settings. Did anyone have the same problem?

### Steps to Reproduce

1. Install InspectieApp R17 from AppStrore
2. Go to devoce Settings and scroll to botom
3. 

### Expected Behavior
An entry with InspectieApp R17 must be in the settings
### Actual Behavior
No InspcetionApp entry is in device settings
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS: 14.0 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: IPadAir2 with iOS 14
![device settings entry](https://user-images.githubusercontent.com/20532118/94021518-c3455000-fdbc-11ea-87ff-2e762c43c3d7.png)
![installedApp](https://user-images.githubusercontent.com/20532118/94021526-c7716d80-fdbc-11ea-9464-62dc77a6e769.png)

**Comment by rmarinho** [comment]
Hi, did you installed from the AppStore? is it possible to deploy the app from the IDE?

I have deployed an App from the IDE and i see the menu on the settings.

**Comment by DaniRvd** [comment]
Hi!
Indeed if I deploy the application from mac on iPad via usb cable the application appear in device settings but if I install the application from TestFlight or AppStore , I have no application entry in device settings

**Comment by DaniRvd** [comment]
I tried to add Settings.Bundle file to iOS project and now I have an entry in the device settings but only option that I can see is Siri and search and I need to be able to see two more options (Camera access and Photo library access)
I think that is good to metion that I have the privacy option in the Info.plist file.
![image](https://user-images.githubusercontent.com/20532118/94402143-4fb49180-0174-11eb-98a9-0026aa97bd40.png)

PS:
Is not clear for me if Strings.Bundle is need for the Xamarin Forms apss, the application works fine before without Settings.Bundle

**Comment by DaniRvd** [comment]
Just tested on a device with iOS 13.7  and I have same problem there

**Comment by DaniRvd** [comment]
This item can be closed because it is not a bug,  an entry in device settings is created only after the user grant or deny( for the first time ) after install access to  device camera or photo library

**Comment by rmarinho** [comment]
Thanks!
