### ISSUE TITLE
[Bug] Set Icon

### ISSUE THREAD

**Issue by Saleh-Software** [xamarin/Xamarin.Forms#12229]
Hi Please Fix This Bug Of Icon

When i in peroperty will Set Icon application icon

must main activity on android also will be set !!

please in xamarin 5.0 solve this problem why we must custom set  path? instead we will on peroperty will set it!

thank u xamarin forms.

**Comment by rmarinho** [comment]
Hi @DenisHidden  sorry but i don't understand the issue, can you please upload a small repo of the issue? 

Thanks

**Comment by DenisHidden** [comment]
Hi Sir I sorry For Bad English..

Look This Picture
http://err2solution.com/wp-content/uploads/2016/06/1462016AndroidManifest.png

when we set it then also we must change icon for example for android:

https://www.codeproject.com/KB/Blogs/1106631/1462016MainActivity.png

i recommed xamarin forms To Set it auto when we choise in App Peroperty.

when we set in setting all project like android and ios set to setting path for icon.

thank u if solve it we now must custom set it...

**Comment by rmarinho** [comment]
Sorry i can't see the first image, i also still don't fully understand what's the issue.

Can you also upload a sample ? 

Thanks

**Comment by DenisHidden** [comment]
hi look this article 

https://www.codeproject.com/Articles/1106631/Configure-App-Icons-in-Xamarin-Forms-App

i just recommend to xamarin forms Add Feature For Auto Set Icon When We Change In Property

Now Just We Must Custom Set Icon And Name ...

Example:
[Activity(Icon = "@drawable/icon")]

when we Set Icon in Property Like @drawable/CustomIcon

Also Main Activity In Android & Ios And UWP must set to [Activity(Icon = "@drawable/CustomIcon")]

i just want xamarin forms fix this for new version 

when we set in Application Property All Attribute must set same icon of setting.

i hope u understand me.

thanks.

**Comment by hartez** [comment]
@DenisHidden I think I understand what you are asking for. 

You want to have the same icon for your application on all platforms (UWP, iOS, Android). And you would like to be able to set a single property to do this, instead of needing to set properties in each project.

Is that correct?

**Comment by jfversluis** [comment]
That is not implemented in .NET MAUI! 🎉  unfortunately this won't be happening for Xamarin.Forms.
