### ISSUE TITLE
[Bug] Divide by zero exception when calling Device.StartTimer() with zero seconds

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12220]
### Description
I would like to start off a timer with zero delay between calls.
Thus, I pass FromSeconds(0).

However, this creates a divide by zero exception.

### Steps to Reproduce

 Device.StartTimer(TimeSpan.FromSeconds(0), YourCallBack);

Xamarin.Forms version v5.0.1.1.467-nightly.

**Comment by rmarinho** [comment]
What platforms are you seeing this issue?

**Comment by snowman745** [comment]
Repro's on UWP 
Does not repro on Android.
I'm not yet configured to test on iOS.

**Comment by themronion** [comment]
Yeah, can confirm. Once, when i wrote Device.StartTimer(TimeSpan.FromMilliSeconds(0.1)) - got the crash on uwp. I then changed to FromSeconds(0.1) and it worked fine

**Comment by jfversluis** [comment]
See PR
