### ISSUE TITLE
[Enhancement] Supporting VisualState of Items on SelectableItemsView

### ISSUE THREAD

**Issue by myroot** [xamarin/Xamarin.Forms#12225]
## Summary
Items on `SelectableItemsView`(base class of CollectionView) have two state  { Selected, Normal }
I want to control it by using `VisualStateManager`, 
(CarouselView is supporing these `VisaulState` { `CurrentItem`, `NextItem`, `PreviousItem`, `DefaultItem` })

`SelectableItemsView` class is providing a event to notify selected item, but it is not enough, 
as you know, App developer can't access to `View` instance that created by `ItemTemplate`, so no way to change visual state

## API Changes

 Added
``` c#
 class SelectableItemsView : ... {
 ...
    public const string SelectedItemVisualState = "SelectedItem";
    public const string NormalItemVisualState = "NormalItem"; 
...
}
```

## Intended Use Case
``` xaml
<CollectionView.ItemTemplate>
  <DataTemplate>
    <app:MyItemView>
      <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="SelecatableItemStates">
          <VisualState x:Name="SelectedItem">
            <VisualState.Setters>
              <Setter Property="BackgroundColor" Value="Lime" />
            </VisualState.Setters>
          </VisualState>
          <VisualState x:Name="NormalItem">
            <VisualState.Setters>
              <Setter Property="BackgroundColor" Value="White" />
            </VisualState.Setters>
          </VisualState>
        </VisualStateGroup>
      </VisualStateManager.VisualStateGroups>
    </app:MyItemView>
  </DataTemplate>
</CollectionView.ItemTemplate>  
```

**Comment by rmarinho** [comment]
Hi @myroot  CollectionView already exposes those 2 states 

https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Core/VisualStateManager.cs#L17

Here' s how is set on Android 

https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Platform.Android/CollectionView/TemplatedItemViewHolder.cs 

Is this what you are asking for?

**Comment by myroot** [comment]
@rmarinho Yes, it is thing to want, Thanks for answer
