### ISSUE TITLE
[Bug] [MacOS] Buttons don't render correctly when given a HeightRequest

### ISSUE THREAD

**Issue by kevcrooks** [xamarin/Xamarin.Forms#12222]
Buttons don't render correctly when specified with a HeightRequest on 4.8.0.1451, instead they are displayed with a box around the Text, and the clickable area is only inside the box (not the whole button).

Screenshot from 4.8.0.1451 - the difference between the buttons is that I've specified a HeightRequest on "Button2":
![4 8 0 1451](https://user-images.githubusercontent.com/10667683/94043755-3bb00f00-fdc5-11ea-873b-f29709f7d49f.png)

Similar from 4.6.0.1073, which seems to render correctly (I think the behaviour changed around 4.7.*):
![Screenshot 2020-09-23 at 17 54 58](https://user-images.githubusercontent.com/10667683/94044435-09eb7800-fdc6-11ea-8be6-93510dec6e61.png)

Basic button code, using a sample Xamarin.Forms app on Mac:
```
type StyledButton() =
    inherit Button(TextColor = Color.White, BackgroundColor = Color.Red, BorderColor = Color.Yellow)
type App() =
    inherit Application()
    let stack = StackLayout(VerticalOptions = LayoutOptions.Center)
    let b1 = StyledButton(Text = "Button1")
    let b2 = StyledButton(Text = "Button2", HeightRequest=50.)
    do
        stack.Children.Add(b1)
        stack.Children.Add(b2)
        base.MainPage <- ContentPage(Content = stack)
```

**Comment by kevcrooks** [comment]
Thank you for fixing - is this in the latest stable `4.8.0.1560`, or will it be the next one?

**Comment by rmarinho** [comment]
Hi @kevcrooks  it's going to be on 4.8.0
