### ISSUE TITLE
[Bug] Xamarin.Forms 5 MasterDetailPage renaming broke plugins

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12224]
Hi.

I just updated to Xamarin.Forms 5 pre-1, and the NuGets in my project that reference MasterDetailPage broke. I'm not even using MDP in my projects, but some plugins refer to it.

I don't know in how many months (if ever) they will be updated, so how can I use Xamarin.Forms 5 in the meantime?

I think this is an irresponsible change as it may kill off projects that are dependent on legacy plugins, unless there is some kind of fallback for this. So what is the fallback, or should I just accept that due to this I may have to remake my entire project, if updates for the plugins don't materialise soon (hint: they never do)?

This change is an order of magnitude larger than just changing the branch name in GitHub. I hope you understand how much trouble this will cause if you decide to go with it, or at least provide some fallback for the plugin issue.

**Comment by Tommigun1980** [comment]
This change is an order of magnitude larger than just changing the branch name in GitHub. I hope you understand how much trouble this will cause if you decide to go with it.

**Comment by PureWeen** [comment]
@Tommigun1980 it shouldn't have broke it can you provide a repro or more information please?

**Comment by Tommigun1980** [comment]
@PureWeen really good to hear it was not by design, phew! I got scared there for a while.

I re-applied the stash with my Xamarin.Forms 5 changes, and now it works for some reason. I did clean the project both times before building. The error, which I didn't save, was within a renderer that was referring to the MDP inside a commercial plugin.

Really happy the error went away by itself! Feel free to close this, or keep open in case you want to debug why it didn't work the first time.

I'll try to give some more info about the what happened when the error materialised:
* I updated Xamarin.Forms to 5, cleaned and rebuilt
* Got some errors so fixed them
* Built again, but got the MDP error from inside a plugin
* Stashed my changes and filed this report

After reading your post that it shouldn't break plugins:
* Re-applied stash
* Cleaned and built the project
* Now it works

**Comment by Tommigun1980** [comment]
Maybe restarting VS in-between was key? I tried cleaning and rebuilding multiple times before restarting it and got the error every time.

**Comment by rmarinho** [comment]
Do you know what error appear ?

**Comment by Tommigun1980** [comment]
Hi @PureWeen and @rmarinho.

I got the error again just by building. It is as follows:

`/Users/me/Projects/myproject/MyProject.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Boolean Xamarin.Forms.IMasterDetailPageController::get_ShouldShowSplitMode()', referenced from the method 'System.Void SomePlugin.SomeRenderer::WillRotate(UIKit.UIInterfaceOrientation,System.Double)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (MyProject.iOS)`

**Comment by PureWeen** [comment]
@Tommigun1980 what's the name of the plugin?

**Comment by Tommigun1980** [comment]
> @Tommigun1980 what's the name of the plugin?

Hi @PureWeen. Is there any way I could send this info privately?

Thanks.

**Comment by PureWeen** [comment]
@Tommigun1980 shneuvil at Microsoft.com

**Comment by PureWeen** [comment]
@Tommigun1980 can you test the nugets from the build here?

https://dev.azure.com/xamarin/public/_build/results?buildId=27784&view=artifacts&type=publishedArtifacts

**Comment by Tommigun1980** [comment]
> @Tommigun1980 can you test the nugets from the build here?
> 
> https://dev.azure.com/xamarin/public/_build/results?buildId=27784&view=artifacts&type=publishedArtifacts

Hi @PureWeen, I would love to but I can't seem to download anything from there? The "folders" are not clickable for me.

**Comment by workgroupengineering** [comment]
![immagine](https://user-images.githubusercontent.com/12531229/94934027-7b64ae00-04cb-11eb-9bde-7720f6e915d5.png)
![immagine](https://user-images.githubusercontent.com/12531229/94934176-a9e28900-04cb-11eb-981c-a349d2a21c8b.png)

**Comment by Tommigun1980** [comment]
Thanks @workgroupengineering, such weird ui :)

@PureWeen the previous error no longer happens with that package, but there's a new error instead (that probably was not hit last time due to the MDP error):

`/Users/myname/Projects/myproject/MyApp.iOS/MTOUCH: Error MT2101: Can't resolve the reference 'Xamarin.Forms.MediaSource', referenced from the method 'System.Void Xamarin.CommunityToolkit.UI.Views.MediaCapturedEventArgs::.ctor(System.String,System.Byte[])' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (MyApp.iOS)`

This time it seems to be the Xamarin Community Toolkit. I installed it when I updated to Xamarin.Forms 5 as I was using the expander component, and the release notes said to install the community toolkit in that case.

These errors don't happen in debug builds, only in release builds (I have optimised complier turned on).

Thanks.

**Comment by PureWeen** [comment]
@Tommigun1980 yea I have to tell people about those dots a lot :-/ 

I think that error should go away once the next XCT version is out with MediaSource all merged in to XCT

**Comment by Tommigun1980** [comment]
> @Tommigun1980 yea I have to tell people about those dots a lot :-/
> 
> I think that error should go away once the next XCT version is out with MediaSource all merged in to XCT

UI elements that only show up when hovering the mouse over an area are quite... exotic, indeed :D

Thanks for the additional info. In that case I'll wait and take this bug there if it's not resolved. Or should it be here as XCT is the update path for certain Xamarin.Forms 4 features, or has responsibility been shifted over completely?

Thanks again.

**Comment by PureWeen** [comment]
I asked @jsuarezruiz about it and there are already PRs for XCT that will soon be merged that should fix that exception.

Any issues you have with XCT should just get logged with XCT

**Comment by PureWeen** [comment]
Also, @Tommigun1980 thank you for this issue and testing the nuget!!!

**Comment by Tommigun1980** [comment]
Thanks for the additional info, and for fixing this! I'll go ahead and close this issue now as the original error has been solved 👍
