### ISSUE TITLE
[Bug] CarouselView adding unneeded space when wrap inside the parent views

### ISSUE THREAD

**Issue by AlfonChitoSalano** [xamarin/Xamarin.Forms#12237]
### Description
CarouselView is adding space when it is wrap inside parent views.

### Steps to Reproduce

Just add the carouselview and wrap it in parentviews.

### Expected Behavior

No extra space should be added.

### Actual Behavior

Extra space is added

### Basic Information

- Version with issue:
- Last known good version: XF 4.7.0.1260
- IDE: VS 2019
- Platform Target Frameworks: 
Xamarin.Android SDK   11.0.2.0
Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 

- Android Support Library Version: 
Only XF version 4.7.0.1260

### Screenshots

![image](https://user-images.githubusercontent.com/20876086/94164025-1d2c3f80-febb-11ea-9c74-b56186b20674.png)

### Reproduction Link

I have attached a sample project/solution.

### Workaround

Didnt find workaround yet.

**Comment by AlfonChitoSalano** [comment]
[CarouselViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5277128/CarouselViewIssue.zip) sample project attach

**Comment by AlfonChitoSalano** [comment]
maybe this could be related. but not sure yet #8640

**Comment by rmarinho** [comment]
They height is the Padding  

<sos:SoEntryView Padding="0,0,0,20" /> 

if i set that padding to 0.0.0.0

![image](https://user-images.githubusercontent.com/1235097/94179015-cfe8a780-fe93-11ea-8f49-f0711c64c2e8.png)
