### ISSUE TITLE
[Bug] [WPF] When not visible, Picker loses BackgroundColor after hiding/showing

### ISSUE THREAD

**Issue by plamen-i** [xamarin/Xamarin.Forms#12230]
### Description

When not visible, Picker loses BackgroundColor after being hidden by another UI (dialog for example) and then shown again.

This issue is very similar to #11710.

### Steps to Reproduce

[Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5275828/Repro.zip)

1. Start WPF project (AFAIK this problem does not occur with Android)
2. Press Display Modal on green MainPage.
3. On blue ModalPage note that Picker has dark blue BackgroundColor.
4. On blue ModalPage press Toggle Visible button so Picker is hidden.
5. On blue ModalPage press Display Second Modal button.
6. On red SecondModalPage press Close button.
7. After blue ModalPage reappears press Toggle Visible button. Picker reappears but now BackgroundColor is white.

To use workaround to fix bug - in SecondModalPage.xaml.cs uncomment call to WPFFixUI() which temporarily switch BackgroundColor to default and back to dark blue. Note this works only when Picker is visible.

Note also that workaround is not needed if Picker is visible (which is not possible in my original project). After BackgroundColor becomes white if you repeat steps 5 to 7 without hiding the Picker - BackgroundColor restores to dark blue.

P.S. After every change REBUILD WPF project otherwise changes will not appear. This strange behavior does not occur in original project.

### Expected Behavior

Picker always shows dark blue BackgroundColor.

### Actual Behavior

Picker BackgroundColor becomes white.

### Basic Information

- Version with issue: XF 4.8.0.1451
- Last known good version: N/A
- IDE: Visual Studio 2019 16.7.4
- Platform Target Frameworks:
  - WPF: .NET Framework 4.6.1
- Android Support Library Version:  N/A
- Prism.Core: 8.0.0.1850-pre

### Workaround

See above.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
