### ISSUE TITLE
[Enhancement] [WPF] Set Picker BackgroundColor also on dropdown.

### ISSUE THREAD

**Issue by plamen-i** [xamarin/Xamarin.Forms#12234]
## Summary
When Picker BackgroundColor is set to dark (for example for displaying white text on dark background) it is set only on Picker textbox part. That way background of dropdown remains white and white text of items is indistinguishable i.e. items names are invisible.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
