### ISSUE TITLE
[Bug] [WPF] PickerRenderer crashes on Windows 7

### ISSUE THREAD

**Issue by plamen-i** [xamarin/Xamarin.Forms#12233]
### Description

Picker crashes Xamarin.Forms WPF app when run on Windows 7.

### Steps to Reproduce

1. Create Xamarin.Forms WPF app.
2. Put Picker on a Xamarin.Forms ContentPage.
3. Run the app.

### Expected Behavior

Page with Picker shows.

### Actual Behavior

Xamarin.Forms WPF app crashes.

### Basic Information

- Version with issue: XF 4.8.0.1451
- Last known good version: N/A
- IDE: Visual Studio 2019 16.7.4
- Platform: Windows 7 SP1 (actually tested on Windows 7 POS edition)
- Platform Target Frameworks:
  - WPF: .NET Framework 4.6.1
- Android Support Library Version: N/A

### Workaround

After investigation I found this code in PickerRenderer to cause problem:
https://github.com/xamarin/Xamarin.Forms/blob/7484457a4ce422838a074a8ed1a0734a0b25599c/Xamarin.Forms.Platform.WPF/Renderers/PickerRenderer.cs#L82-L90

Workaround:
```
void UpdateBackgroundColor()
{
	if (Control.Template.FindName(TextBoxTemplate, Control) is TextBox textbox && textbox.Parent is Border parent)
	{
		parent.Background = Element.BackgroundColor.ToBrush();
	}
}
```

Note: This workaround does not resolve #12230 but it's interesting that both issues have something to do with Picker BackgroundColor.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
