### ISSUE TITLE
[Bug] [WPF] [XF 5.0] App crash on launch (resource not found 'themes/formsmasterdetailpage.xaml')

### ISSUE THREAD

**Issue by Seuleuzeuh** [xamarin/Xamarin.Forms#12235]
### Description

I've update my new project with XF 5.0 preview 1 and when i try to launch the WPF application the app crash with the following error :
System.Xaml.XamlObjectWriterException: 'La propriété Set 'System.Windows.ResourceDictionary.Source' a levé une exception.'
Inner Exception
IOException: Impossible de trouver la ressource 'themes/formsmasterdetailpage.xaml'.

[detailLog.txt](https://github.com/xamarin/Xamarin.Forms/files/5276631/detailLog.txt)

### Steps to Reproduce

With the repro solution attached bellow, just start the WPF app.

### Basic Information

- Version with issue: 5.0.0.1487-pre1
- Last known good version: 4.8
- IDE: VS19 Version 16.7.4
- Platform Target Frameworks: 
  - WPF : 5.0.0.1487-pre1
- Nuget Packages:
  - Xamarin.Forms : version 5.0.0.1487-pre1
  - Xamarin.Forms.Platform.WPF : version 5.0.0.1487-pre1
- Affected Devices:

### Reproduction Link

[XFCrashRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/5283022/XFCrashRepro.zip)

**Comment by rmarinho** [comment]
@Seuleuzeuh  can you send a small repo? did you clean rebuild and restart vs when updating the packagee?

Thanks

**Comment by mohaaron** [comment]
I can reproduce this and am using all the same software as listed above.

1. Create a Xamarin.Forms project.
2. Following these directions for adding the WPF app https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf
3. Bring nuget packages up to date with stable versions.
4. Running WPF app works with stable packages.
5. Now update packages to pre-release nuget versions.

![Update packages](https://user-images.githubusercontent.com/1719598/94226341-3679bf80-feac-11ea-8452-1c47db735666.png)
![Compile error](https://user-images.githubusercontent.com/1719598/94226343-37aaec80-feac-11ea-95fe-2000e817a79e.png)

**Comment by Seuleuzeuh** [comment]
> @Seuleuzeuh can you send a small repo? did you clean rebuild and restart vs when updating the packagee?
> 
> Thanks

@rmarinho i've edited the issue to add a repro project. Yes i've clean/rebuild/restart a multiple time and also reboot 😄

**Comment by rmarinho** [comment]
Thanks we have a fix for it.
