### ISSUE TITLE
Bug] [iOS] Color was not applied properly when applying the LinearGradient with offset property.

### ISSUE THREAD

**Issue by jeyakasipandi** [xamarin/Xamarin.Forms#12232]
### Description

We have created the custom control to draw the linear gradient using the below code. When using the offset as 0,0.501,0.5,1.

`

        <Frame Padding="0" IsClippedToBounds="True"
         CornerRadius="25" HeightRequest="50" WidthRequest="50" HorizontalOptions="Center" VerticalOptions="Center">
                                                       
            <issue10364:CustomView/>
        </Frame>

`

`   

    public class CustomView : View
    {

    }

`

iOS Renderer

`

        public override void Draw(CGRect rect)
        {
            base.Draw(rect);
            var offsets= new nfloat[4] { 0, 0.501f, 0.5f, 1 };
            CGColor[] colors = { UIColor.Yellow.CGColor, UIColor.Yellow.CGColor, UIColor.Red.CGColor, UIColor.Red.CGColor };
            var ctx = UIGraphics.GetCurrentContext();
            var colorSpace = CGColorSpace.CreateDeviceRGB();
            CGGradient gradient = new CGGradient(colorSpace, colors, offsets);
            ctx.DrawLinearGradient(gradient, new CGPoint(0,0), new CGPoint( this.Frame.Width,  this.Frame.Height), 
            CGGradientDrawingOptions.None);
          }

` 

### Expected Behavior

The first of the diagonal should be yellow color and second half to be red color.

### Actual Behavior

Both the Red shown at first half diagonal and yellow color is showing second half..

### Basic Information

XF version: 4.8

### Screenshots

iOS:
![Simulator Screen Shot - iPhone XS Max - 2020-09-24 at 17 52 51](https://user-images.githubusercontent.com/62105021/94144895-5bac0500-fe8f-11ea-9355-4ca79aefd72d.png)

Android:

![Screenshot_20200924-181055](https://user-images.githubusercontent.com/62105021/94146322-62d41280-fe91-11ea-8dde-b67a33b243bf.jpg)

### Reproduction Link

![Sample](https://github.com/xamarin/Xamarin.Forms/files/5276011/GradientIssueiOS.zip)

**Comment by rmarinho** [comment]
Hi this isn't a Xamarin.Forms bug, seems what's wrong in your sample is the order of the offsets, if you try:
`var offsets = new nfloat[4] {​ 0, 0.5f, 0.501f, 1 }​;` it should work as expected

![image](https://user-images.githubusercontent.com/1235097/94246398-99527180-ff13-11ea-9f70-e4b06d85aa02.png)


https://developer.apple.com/documentation/coregraphics/cggradient/1398454-init
