### ISSUE TITLE
[Bug] Word-wrapped Labels with HorizontalOptions = Start (not StartAndExpand) are padded with space to the right of the text

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#12236]
### Description

Word-wrapped Labels with HorizontalOptions = Start (not StartAndExpand) are padded with space to the right of the wrapped text. I would not expect padding with space to occur without AndExpand being included in the HorizontalOptions.

See https://us.v-cdn.net/5019960/uploads/editor/pn/2p39towgu8gk.png

In the attached image, I have two Labels side by side in a StackLayout with horizontal orientation, and with the StackLayout centered horizontally on the page.

As per the image, when the Labels do not wrap (using XF 4.8), the result is as expected (first example in the image).

However, when the Labels wrap (second example in the image), despite HorizontalOptions not having AndExpand, a whole load of white space (ok, red and green in the image) appears to the right of the wrapped text.

Without AndExpand being specified in the HorizontalOptions of the Labels, I would expect wrapped Labels to appear as per the third or fourth examples in the image.

### Basic Information

- Version with issue: 4.8
- IDE: VS2019
- Platform Target Frameworks: Image is from iOS

**Comment by hartez** [comment]
@johnshardman Can you paste in the XAML/code you're using for this layout? Just to remove any ambiguity.

**Comment by hartez** [comment]
@johnshardman Also, you mention iOS; are you seeing this _only_ on iOS? Or are you also seeing this issue on other platforms?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
