### ISSUE TITLE
[Bug][iOS] CarouselView ScrollTo not work properly

### ISSUE THREAD

**Issue by stivenbr** [xamarin/Xamarin.Forms#12241]
### Description
In CarouselView, on iOS, scrolling to an item by index works fine. Scrolling to an item by object does not work (in 4.8.0.1451). 

In my code, the correct Monkey object is retrieved, but the ScrollTo method isn't scrolling to it.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the scroll by object page.
3. Click the button.

### Expected Behavior
The Proboscis Monkey appears.

### Actual Behavior
The Capuchin Monkey appears.

### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version: -
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  13

### Workaround
(Obsoleted) #7798

**Comment by rmarinho** [comment]
Can you try on 5.0.0 we re-wrote the CarouselView?

**Comment by stivenbr** [comment]
Excellent, if it works in version 5.0.0.1487-pre1
