### ISSUE TITLE
[Bug] SetCollapseStyle and CollapsedPaneWidth doesn't behave normally on UWP with Xamarin.Forms 5.0.0

### ISSUE THREAD

**Issue by SunshineSpring666** [xamarin/Xamarin.Forms#12242]
### Description

 **On<Windows>().SetCollapseStyle(CollapseStyle.Partial);
 On<Windows>().CollapsedPaneWidth(100);**
The above code doesn't behave as expected in **Xamarin.Forms 5.0.0**.

### Steps to Reproduce

1. Create a project in Master-Detail style.
2. Add those two lines of code mentioned above in AppShell.
3. Build and Run.

### Expected Behavior

On UWP, the menu side (master page) shows as narrow as 100px and can be expanded as needed when pressing the hanburger button.

### Actual Behavior

The menu side (master page) always shows in full size and cannot be collapse on UWP.

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0
- Last known good version: Xamarin.Forms 4.8.0
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  20215
- Nuget Packages: Xamarin.Forms 5.0.0
- Affected Devices: UWP PC

### Workaround
Downgrade to Xamarin.Forms 4.8.0

**Comment by rmarinho** [comment]
@SunshineSpring666 are you trying to set these properties to Shell? Those properties are for MasterDetailpage

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/masterdetailpage-navigation-bar

**Comment by SunshineSpring666** [comment]
Nope, still MasterDetailPage. It worked fine with Xamarin 4.8.0 and all previous versions, but with 5.0.0, the hamburger button disappeared and the left panel never show as "partially collapsed" as expected.

I know that 5.0.0 mark MasterDetail as obselete. But I need it to cope with the situation what Flyout cannot handle on UWP:
(1) Menu panel (master side) needs to be "partially collapsed" by default.
(2) Menu panel can be unfolded to full width by clicking hamburger button. 
That's what those two lines of code used to work combining with MasterDetailPage.
Many thanks. Have a nice day.

**Comment by SunshineSpring666** [comment]
Update:
Change MasterDetailPage to use **Xamarin.Forms.FlyoutPage (which does not seem to have official documentation for the moment) solves the issue**. No need to use Flyout in Shell. No need to modify those lines of platform-specific configurations.
Thanks for your kind reply.
