### ISSUE TITLE
[Spec] Add  Command<TExecute, TCanExecute>

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#12243]
#  Command<TExecute, TCanExecute>

Because the paradigm of [`ICommand`](https://docs.microsoft.com/dotnet/api/system.windows.input.icommand?view=netcore-3.1&WT.mc_id=xamarincommunitytoolkit-github-bramin) doesn't require `Execute` to use the same parameter type as `CanExecute`, creating this type-safe `ICommand` would allow for the following scenario where we want to pass in an `int` to `Execute`, but use a `bool` for `CanExecute`:

```csharp
public ICommand PullToRefreshCommand { get; } = new Command<int, bool>(count => FetchNewData(count), isBusy => !isBusy)
```

# API

```csharp
public sealed class  Command<TExecute, TCanExecute> : Command
{
    public Command(Action<TExecute> execute);
    public Command(Action<TExecute> execute, Func<TCanExecute, bool> canExecute);

    public bool CanExecute(TCanExecute parameter);
    public void Execute(TExecute parameter);
}
```

# Difficulty : Low

**Comment by brminnick** [comment]
If approved, feel free to assign this to me! I'm happy to implement it.

I recently added a similar implementation to [XamarinCommunityToolkit for `AsyncCommand<TExecute, TCanExecute>`](https://github.com/xamarin/XamarinCommunityToolkit/blob/1f2d179e35f12ae1d8cda0894b2faa166bfa1e4f/XamarinCommunityToolkit/ObjectModel/AsyncCommand.shared.cs#L10-L34)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
