### ISSUE TITLE
While using accessibility(TalkBack) on popups on Android, Focus also goes to background view.[Bug] 

### ISSUE THREAD

**Issue by HirakCTS** [xamarin/Xamarin.Forms#12251]

**Comment by rmarinho** [comment]
Hi @HirakCTS  can you upload a small reproduction of the issue please so we can understand better?!
Thanks

**Comment by HirakCTS** [comment]
Hi @rmarinho , I am using one small popup view having title and ok button, behind it there is a complete page having list and other elements. when i click on any list item , popup appears. While accessibility is on, focus supposed to stay on popup only but after reading all the elements of popup , focus goes to page behind it.

**Comment by hartez** [comment]
@HirakCTS Which version of Xamarin.Forms are you using? When you say "popups" - are you using a third party library for popups, or are you talking about DisplayAlert/DisplayActionSheet?

**Comment by HirakCTS** [comment]
@hartez I am using 4.8.0.1269 version of xamarin forms and I am using Prism as third party library for popups. Please let me know if you want more details.

**Comment by hartez** [comment]
> @hartez I am using 4.8.0.1269 version of xamarin forms and I am using Prism as third party library for popups. Please let me know if you want more details.

In that case, you should open an issue at [Prism.Plugin.Popups](https://github.com/dansiegel/Prism.Plugin.Popups/issues).

If they determine that the problem is in Forms and not in their popup library, comment here and we can reopen this issue.
