### ISSUE TITLE
[Enhancement] Support for overriding CreateMoreBottomSheet(...) on Android

### ISSUE THREAD

**Issue by miko1258** [xamarin/Xamarin.Forms#12257]
## Summary
Hello, I wanted to create my own 'MoreBottomSheet'. There is virtual method in `ShellItemRenderer` but it isn't used. Instead renderer uses `BottomNavigationViewUtils.CreateMoreBottomSheet`. 

## API Changes
Remove use of `BottomNavigationViewUtils.CreateMoreBottomSheet` in `ShellItemRenderer`. Instead use virtual method of this renderer.

## Intended Use Case
This change will facilitate customizing 'MoreBottomSheet' on Android platform.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
