### ISSUE TITLE
[Enhancement] Provide possibility to execute command upon swipe for SwipeItemView

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12276]
## Summary
Give the possibility for custom swipe items `SwipeItemView` to execute the command upon swipe without the need to tap, through the property `Mode="Execute"`  the same way as it is available for `SwipeItems`:

Following example is not executing command even with `Mode="Execute"` unless tap:
```
<SwipeView>
	<SwipeView.LeftItems Mode="Execute">
		<SwipeItemView Command="{Binding CheckAnswerCommand}" Mode="Execute">
			<StackLayout>
				<Label Text="Action.."/>
				 <ImageButton Source="SomeIcon"/>
			</StackLayout>
		</SwipeItemView>
	</SwipeView.LeftItems>
</SwipeView>
```

## API
| Property | Type | Description |
|:--------:|:--------:|:---------|  
| Mode  | enum|  same as SwipeItems |
|Threshold | double  | The Command/Invoked_event are called/executed only when swiping beyond that percentage value (relative to actual Width or Height) (case of Execute Mode).|

## Intended Use Case
Because when having a single action only, I believe it is much easier and intuitive for user to just swipe and expecting command to execute (maybe if swipe > 50%, or to be defined by developer?) without the need to swipe+tape.
You may probably seen it it multiple modern apps like recent GitHub or Gmail apps.

## Preview
![](https://user-images.githubusercontent.com/4265163/49108516-fdd81300-f24d-11e8-88d9-03b4ca7f90a3.gif)

Same concept in another app: https://kstatic.googleusercontent.com/files/1012809df8743dbb22a6f7ae7bd08e9f0a81ff3e89146f7a955c36bec6007d065946744f9d14448f51dd3522a8cedff7551b55599b87f6efe44851325c1ca1c8

**Comment by Cfun1** [comment]
@davidortinau your last video reminds me of this issue.
Are all Enhancements/features requests frozen for the moment, will be postponed to after MAUI ?
If yes then maybe we will see if it is doable in xct.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
