### ISSUE TITLE
[Regression] On iOS, CollectionView.EmptyView Does Not Appear in Xamarin.Forms v5.0.0.1487-pre1

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#12275]
### Description

On iOS, using Xamarin.Forms v5.0.0.1487-pre1, the `CollectionView.EmptyView` no longer appears.

```csharp
Content = new CollectionView
{
    EmptyView = new Image
    {
        Source = "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2r0Th?ver=5b7d"
    }
}
```

| iOS EmptyView, Xamarin.Forms v5.0.0.1487-pre1 | Android EmptyView, Xamarin.Forms v5.0.0.1487-pre1 | 
| --------------------------------------------- | ------------------------------------------------- |
| ![](https://user-images.githubusercontent.com/13558917/94372323-575f3200-00b1-11eb-9f9e-d142941e0932.png) | ![](https://user-images.githubusercontent.com/13558917/94372474-b7a2a380-00b2-11eb-8a3f-06058a8f78a3.png) | 

### Steps to Reproduce

1. Download/Clone this repo: https://github.com/brminnick/MissingEmptyViewRepro
2. In Visual Sudio, open `MissingEmptyViewRepro.sln`
3. In Visual Studio, set the Startup Project to `MissingEmptyViewRepro.iOS`
4. In Visual Studio, buld/deploy `MissingEmptyViewRepro.iOS` to an iOS Simulator/Device
5. On the **iOS** device, confirm the `EmptyView` image (Microsoft Logo) **does not** appear
6. In Visual Studio, set the Startup Project to `MissingEmptyViewRepro.Android`
7. In Visual Studio, buld/deploy `MissingEmptyViewRepro.iOS` to an Android Simulator/Device
8. On the **Android** device, confirm `EmptyView` image (Microsoft Logo) **does** appear

### Expected Behavior

`CollectionView.EmptyView` should appear on both iOS and Android

### Actual Behavior

`CollectionView.EmptyView` does not appear on iOS

### Basic Information

- Version with issue: v5.0.0.1487-pre1
- Last known good version: v4.8.0.1451

### Reproduction Link

https://github.com/brminnick/MissingEmptyViewRepro

## Workaround

Downgrade to Xamarin.Forms v4.8.0.1451

| iOS EmptyView, Xamarin.Forms v4.8.0.1451 | Android EmptyView, Xamarin.Forms v4.8.0.1451 | 
| --------------------------------------------- | ------------------------------------------------- |
| ![](https://user-images.githubusercontent.com/13558917/94372368-ad33da00-00b1-11eb-83de-d70d2b7c5e82.png) | ![](https://user-images.githubusercontent.com/13558917/94372474-b7a2a380-00b2-11eb-8a3f-06058a8f78a3.png) |

**Comment by BioTurboNick** [comment]
This or a related bug appears to have upstream effects. I have a CollectionView with no items in it, which starts in a container with IsVisible==false.  That property is bound to a boolean. When the boolean changes to true, the entire container does not render.

The problem does not occur if I comment out the Content of `<CollectionView.EmptyView>`, which was just a simple `Label`.

This is on the `-pre4` release.

**Comment by brminnick** [comment]
@BioTurboNick Looks like Javier just opened a PR to fix it 🎉 

https://github.com/xamarin/Xamarin.Forms/pull/13004

**Comment by brminnick** [comment]
@jsuarezruiz I can confirm this was fixed in this PR: https://github.com/xamarin/Xamarin.Forms/pull/12377
