### ISSUE TITLE
[Bug] UWP CollectionView shows empty screen after XF update

### ISSUE THREAD

**Issue by jbe2277** [xamarin/Xamarin.Forms#12272]
### Description
UWP CollectionView shows empty screen after XF update.

### Steps to Reproduce
1. Clone https://github.com/jbe2277/waf.git
2. Checkout commit https://github.com/jbe2277/waf/commit/06a33c5cd317454a06d929de01efc6b2a32f71ee
3. Open src\NewsReader\NewsReader.sln
4. Start the App with "NewsReader.UWP", "Debug", "x86"
5. Verify that news feed items are shown.

6. Update "Xamarin.Forms" from Version="4.8.0.1269" to Version="4.8.0.1451"
7. Start the App again
8. See that news feed items are empty -> Collection view does not render the elements anymore

- Version with issue: "Xamarin.Forms" Version="4.8.0.1451"
- Last known good version: "Xamarin.Forms" Version="4.8.0.1269"
- IDE: VS 2019
- Platform Target Frameworks:
  - UWP:  UWP SDK 18362

### Workaround

Downgrade Xamarin Forms to Version="4.8.0.1269"

**Comment by brandbogard** [comment]
Same issue for me but 1364 works on UWP with a ListView

**Comment by hartez** [comment]
This is fixed in 4.8.0.1821 and onward.
