### ISSUE TITLE
[Enhancement] respect UITabBarItem.Appearance's UITextAttributes

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#12299]
## Summary
When using a tab bar on iOS, the tab bar item has limited customization compared to the iOS version.
Especially, using UITabBarItem.Appearance.SetTitleTextAttributes, you can change the font of the tab bar's text to display it bigger for example.

The problem is, the iOS renderer [here](https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs)  line 419 (UpdateBarTextColor) overrides attributes set in the appearance proxy when it sets the text's color.
Especially it overrides the font property and size and reset it to the default one.

A solution would be to replace

`var attributes = new UITextAttributes();`

by

`var attributes = UITabBarItem.Appearance.GetTitleTextAttributes(UIControlState.Normal)` 

## API Changes
The iOS renderer has no extension point to fix that UpdateBarTextColor method.
A good idea would be either to respect what's already in the Appearance proxy, or support setting text font of the tab from Forms (which is a challenge for Android, as it uses an android resource for that).

## Intended Use Case
The gmail app for iPhone is using tabs with text larger  than the default. The default iOS font for text on tabs is very very small.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
