### ISSUE TITLE
[Bug] MacOS - Layout.ForceLayout() does not work if Layout's bounds is outside of window's bounds

### ISSUE THREAD

**Issue by KyNam** [xamarin/Xamarin.Forms#12308]
### Description

XAML

        <Grid>
                <StackLayout x:Name="stackLayout" 
                             Orientation="Vertical"
                             HorizontalOptions="End"
                             IsVisible="False"
                             IsTabStop="False">
                </StackLayout>
        </Grid>

C#

            //view.IsVisible == true
            //stackLayout.IsVisible == false

            stackLayout.Children.Add(view);

            //workaround 1
            //if (Device.RuntimePlatform == Device.macOS)
            //{
                //view.IsVisible = false;
                //view.IsVisible = true;
            //}

            stackLayout.TranslationX = view.WidthRequest;
            //at this point, stackLayout's bounds is outside of window's bounds

            stackLayout.IsVisible = true;
            stackLayout.TranslateTo(0, 0, 250U, Easing.CubicOut);

            //workaround 2
            //await stackLayout.TranslateTo(0, 0, 250U, Easing.CubicOut);

            //workaround 3
            //stackLayout.TranslationX = 0;

            //does not work, and should be unnecessary
            //stackLayout.ForceLayout() 

With workaround 1, **stackLayout.ForceLayout()**  is not needed.

With workaround 2/3, **stackLayout.ForceLayout()**  works.

### Expected Behavior
**view**'s bounds is calculated and set.

### Actual Behavior
**view**'s bounds is empty (0,0,0,0).

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
