### ISSUE TITLE
[Bug] Shell Flyout - Flyout Header adds bottom outline

### ISSUE THREAD

**Issue by rlubkowski** [xamarin/Xamarin.Forms#12309]
### Description
Defining FlyoutHeader or FlyoutHeaderTemplate adds a bottom shadow/outline that shouldn't be there.

### Basic Information

- Version with issue: 4.8.0.1451
- IDE: Visual Studio Community 2019 (16.7.5)
- Android: 9.0 (Pie)

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/24680206/94661000-c1bce000-0306-11eb-8900-4d4324723fd3.jpg)
![Screenshot (2)](https://user-images.githubusercontent.com/24680206/94661008-c386a380-0306-11eb-8697-d04e7b63aa76.jpg)
![Screenshot (3)](https://user-images.githubusercontent.com/24680206/94661809-d51c7b00-0307-11eb-8ce1-260322e24a1d.jpg)

### Reproduction Link

[FlyoutHeaderShadow.zip](https://github.com/xamarin/Xamarin.Forms/files/5303988/FlyoutHeaderShadow.zip)

### Workaround
Workaround for this issue is to create custom shell renderer:

    public class CustomShellRenderer : ShellRenderer
    {
        public CustomShellRenderer(Context context) 
            : base(context) {}

        protected override IShellFlyoutContentRenderer CreateShellFlyoutContentRenderer()
        {
            var flyoutContent = base.CreateShellFlyoutContentRenderer();

            var cl = ((CoordinatorLayout)flyoutContent.AndroidView);

            for (int index = 0; index < cl.ChildCount; index++)
            {
                var child = cl.GetChildAt(index);

                if (child is AppBarLayout)
                {
                    var view = (AppBarLayout)child;
                    view.OutlineProvider = null;
                }
            }
            return flyoutContent;
        }
    }

**Comment by gechurekimoiMedbook** [comment]
wow thanks for this walk around , it helped sort my design
