### ISSUE TITLE
[Bug] Failed To Resolve Xamarin.Forms.Platform.Android.EllipseRenderer on Xamarin Forms 4.8 and 4.6

### ISSUE THREAD

**Issue by bsglinux16** [xamarin/Xamarin.Forms#12302]
### Description
Xamarin Cannot Build Release Mode on Linking Open.

### Steps to Reproduce

1. Open Linking Mode
2. Disable Debug Libraries
3. Build Failed Getting Failed To Resolve Xamarin.Forms.Platform.Android.EllipseRenderer

### Basic Information

- Version with issue: Xamarin Forms 4.8 and 4.6
- Last known good version: ?
- IDE: VS2019 16.7
- Platform Target Frameworks: 
  - iOS:  none
  - Android: Mono 10.0
  - UWP:  none
- Android Support Library Version: ?
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/35398147/94610107-74aa2100-02a8-11eb-8a58-cb35f24f4372.png)
![image](https://user-images.githubusercontent.com/35398147/94610148-82f83d00-02a8-11eb-8e31-36a1bb0b4cd7.png)
![image](https://user-images.githubusercontent.com/35398147/94610220-9efbde80-02a8-11eb-939c-74e7e56b4d0a.png)

**Comment by hartez** [comment]
@bsglinux16 Are you using an Ellipse in your project? Ellipse is part of Shapes, which wasn't available until 4.7. 

If you clean out the bin/obj folders in your Android project and rebuild, does it work? Or do you still see the error?

**Comment by bsglinux16** [comment]
> @bsglinux16 Are you using an Ellipse in your project? Ellipse is part of Shapes, which wasn't available until 4.7.
> 
> If you clean out the bin/obj folders in your Android project and rebuild, does it work? Or do you still see the error?

Yes Cleaned Project
Upgraded 4.8 But Not Fixed

Not Used Shapes In the Project but Xamarin Forms Fixed After Upgrading to Version 5.0-pre8

I think the problem exists in Xamarin Forms versions 4.6 through 4.8.

**Comment by jsuarezruiz** [comment]
Tried to reproduce using Xamarin.Forms 4.8.0.1451 without success. Attached the sample:
[Issue12302.zip](https://github.com/xamarin/Xamarin.Forms/files/5332940/Issue12302.zip)

@bsglinux16 With what 4.8 specific version had the problem?

**Comment by bsglinux16** [comment]
> Tried to reproduce using Xamarin.Forms 4.8.0.1451 without success. Attached the sample:
> [Issue12302.zip](https://github.com/xamarin/Xamarin.Forms/files/5332940/Issue12302.zip)
> 
> @bsglinux16 With what 4.8 specific version had the problem?

4.8.0.1451
and 4.6.0.1141

**Comment by bsglinux16** [comment]
> Tried to reproduce using Xamarin.Forms 4.8.0.1451 without success. Attached the sample:
> [Issue12302.zip](https://github.com/xamarin/Xamarin.Forms/files/5332940/Issue12302.zip)
> 
> @bsglinux16 With what 4.8 specific version had the problem?

what is the project in zip file for

**Comment by jsuarezruiz** [comment]
With Xamarin.Forms 4.6.0.1141 that error is quite weird, because `EllipseRenderer` was introduced in 4.7. With that version it should be a problem fixed just clearing bin/obj folders.

The attached zip is an example using 4.8.0.1451. I used that sample to compile and deploy from VSMac and VSWin using different linker options etc. I have not managed to reproduce the issue at the moment.

**Comment by bsglinux16** [comment]
> With Xamarin.Forms 4.6.0.1141 that error is quite weird, because `EllipseRenderer` was introduced in 4.7. With that version it should be a problem fixed just clearing bin/obj folders.
> 
> The attached zip is an example using 4.8.0.1451. I used that sample to compile and deploy from VSMac and VSWin using different linker options etc. I have not managed to reproduce the issue at the moment.

Okey Trying Cleaning
I will report the result

**Comment by samhouts** [comment]
@bsglinux16 Any update? Thanks!

**Comment by bsglinux16** [comment]
> @bsglinux16 Any update? Thanks!

I need to clear the project, after I do this, I will try again.

**Comment by bsglinux16** [comment]
Reinstalled Xamarin Forms 4.8.1534

 not reproduced issue

Builded Succesfuly

But R8 if open Application Resources crashing

**Comment by bsglinux16** [comment]
![image](https://user-images.githubusercontent.com/35398147/95680762-895db180-0be4-11eb-91d8-f29625b210cb.png)

**Comment by Redth** [comment]
@bsglinux16  this sounds like a different issue potentially with R8.  I suggest you open an issue in https://github.com/xamarin/xamarin-android with a repro sample.  Thanks!
