### ISSUE TITLE
[Bug] WebView.Navigated event not fired when no internet available on iOS.

### ISSUE THREAD

**Issue by aaRopi** [xamarin/Xamarin.Forms#12312]
### Description

`WebView.Navigated` **_NOT_** fired on iOS when no internet connection is available.

### Steps to Reproduce

1. Hook into `WebView.Navigating` and `WebView.Navigated` events.
2. Run app on iOS without internet connection.
3. Handler for `WebView.Navigated` is never called.

### Expected Behavior

On iOS, when loading a url in the `WebView`, if there is no internet connection available, the `WebView` should fire a [`Navigated`](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webview.navigated?view=xamarin-forms) event with [`WebNavigationResult.Failure`](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webnavigationresult?view=xamarin-forms).

Since this is observed behavior on Android, I expected iOS to behave the same way.

### Actual Behavior

The `Navigated` event is never fired for this error case.

### Basic Information

- Version with issue: 4.8.0.1364
- Platform Target Frameworks: 
  - iOS: 13, 14

### Workaround

No suitable workaround found yet. I know where the bug is and how it can be fixed.

1. iOS WkWebView requires a delegate [`WkNavigationDelegate`](https://developer.apple.com/documentation/webkit/wknavigationdelegate) to handle various callbacks from the `WkWebView`.

2. The `WkNavigationDelegate` has 2 methods to handle errors:

- `DidFailNavigation(WKWebView webView, WKNavigation navigation, NSError error)`
- `DidFailProvisionalNavigation(WKWebView webView, WKNavigation navigation, NSError error)`

3. Only one of them has been implemented as can be seen here: [WkWebViewRenderer source code](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs#L588)

4. For now the solution would be to implement the other method. The implementation can be copied from `DidFailNavigation `

**Comment by Goldstrike** [comment]
It's the same thing when requesting a **invalid url**:
- on **Android**, this will fire a `Navigated` event with `WebNavigationResult.Failure`
- on **iOS**, nothing happens: we only have a **white empty `View`**

Do you prefer I create a new issue, or is it possible to fix this in the same time?

**Comment by aaRopi** [comment]
Hi @Goldstrike ,

Thank you for the additional info. I have a PR that is open fixing the issue I have outlined. Here: #12327 

I don't know if the PR fixes your issue as well.

**Comment by Goldstrike** [comment]
Hi @aaRopi ,
So if I want to use your code, what do I have to do?
- add the [`WkWebViewRenderer.cs` class](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs#L588) in my "**Renderers**" iOS folder
- add you [implementation](https://github.com/xamarin/Xamarin.Forms/pull/12327/commits/29dc9d2c4d529c78994a614a3546fac8f6339fc3) you've given

Is  it correct? Is there something else to do?

**Comment by aaRopi** [comment]
Hi @Goldstrike ,

Yes, I think that should work. Or maybe subclass from the `WkWebViewRenderer`, and add the one extra method my PR also adds.

**Comment by Goldstrike** [comment]
@samhouts @jsuarezruiz 
What's new about this PR? Is there another way to fix the original issue?

**Comment by Goldstrike** [comment]
I've created a new bug for the other cases: #12732
