### ISSUE TITLE
Getting error while running iOS app after update in xcode 12 

### ISSUE THREAD

**Issue by Noufalt** [xamarin/Xamarin.Forms#12310]
### Description
I have updated Xamarin.ios and vs studio also installed latest stable xcode12 version .After updation trying to run the iOS app but I am not able to run .getting below error as per the screenshot 

It also looks like Apple has changed Launch Screen functionality with iOS 14. It mentions old method should still work. We cannot switch to the new method and leave version earlier than iOS 14 behind.
### Steps to Reproduce

1. Update device to iOS 14. Update Xcode to 12
2. Create Launchscreen.storyboard with an image
3. Set info.plist Launch Screen to Launchscreen storyboard above

### Expected Behavior
Launch Screen with image to display in iOS 14 like it does on iOS 13.7

### Actual Behavior
Getting error as per the attached screenshot 
### Basic Information

- Version with issue:
- Last known good version: iOS 13.7, Xcode 11
- IDE:VS for Mac , version 8.7.8
- Platform Target Frameworks: 
  - iOS: 
 Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Community)

### Screenshots

<img width="1217" alt="Screen Shot 2020-09-28 at 8 51 10 AM" src="https://user-images.githubusercontent.com/11627833/94662303-e3bb6000-0310-11eb-918e-f6e84cef7d34.png">

**Comment by Codelisk** [comment]
I got the same error message with ios version 13.6

**Comment by Noufalt** [comment]
Any updates please .

**Comment by hartez** [comment]
> Set info.plist Launch Screen to Launchscreen storyboard above

@Noufalt Are you setting the "Launch screen interface file base name" property to your storyboard? Or have you created a new plist property called "Launch Screen"?

If you want to continue using storyboards, I believe you should set the "Launch screen interface file base name" to your storyboard. The plist setting "Launch Screen" (which should be a Dictionary) is for the new iOS 14 style of launch screen.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
