### ISSUE TITLE
[Bug] Button disappears when setting CornerRadius

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#12315]
### Description

On Android 10 the `Button` only appears/renders when the `CornerRadius` is zero. 

```xaml
<Button
    Grid.Row="1"
    HorizontalOptions="End"
    VerticalOptions="Center"
    HeightRequest="44"
    WidthRequest="44"
    Background="{StaticResource BlueGradient}"
    BorderWidth="0"
    TextColor="White"
    FontSize="24"
    Padding="0"
    CornerRadius="{OnPlatform Android=8, Default=8}"
    Text="{x:Static theme:IconFont.Plus}"
    FontFamily="FontAwesome"/>
```

`CornerRadius=0`:
![image](https://user-images.githubusercontent.com/41873/94725453-651aee80-0321-11eb-9a5a-2b561b36a3d0.png)

`CornerRadius=8`:
![image](https://user-images.githubusercontent.com/41873/94725518-8380ea00-0321-11eb-90a4-4d85e1510c31.png)

### Basic Information

- Version with issue: 5.0-nightly
  - Android: 10

### Reproduction Link

https://github.com/davidortinau/PersonalFinanceSample

**Comment by hartez** [comment]
@davidortinau Can you fix the build errors in that repro project?

**Comment by jsuarezruiz** [comment]
I have created a repro sample using 5.0.0 branch: https://github.com/xamarin/Xamarin.Forms/tree/fix-12315 but cannot reproduce the issue:
<img width="1457" alt="issue12315" src="https://user-images.githubusercontent.com/6755973/94788325-b1bf0200-03d3-11eb-8711-99b7759ddbfd.png">
I'm missing something?

**Comment by davidortinau** [comment]
pushed https://github.com/davidortinau/PersonalFinanceSample/commit/f08e0fb3c6eccc79166c54284c097b0a0993f740 which compiles, runs, and fails to render the `Button`. 

https://github.com/davidortinau/PersonalFinanceSample/blob/main/src/PersonalFinance/Pages/MainPage.xaml#L69

**Comment by jsuarezruiz** [comment]
I still can't reproduce the issue (neither creating example, nor in branch 5.0.0) :(
I have created a small example using Xamarin.Forms 5.0-pre2:
[Issue12315.zip](https://github.com/xamarin/Xamarin.Forms/files/5353460/Issue12315.zip)

The result (same Button using exactly the same properties):
<img width="1361" alt="Captura de pantalla 2020-10-09 a las 10 18 55" src="https://user-images.githubusercontent.com/6755973/95560043-f91f4100-0a18-11eb-8342-313c33bc3e49.png">

@hartez or someone else, can you try the David example and/or mine?

**Comment by davidortinau** [comment]
Updated to 5.0-pre2 and it's working now. 
![image](https://user-images.githubusercontent.com/41873/97488433-401f9880-192c-11eb-80d2-38f4499c307d.png)

So I tried 5.0.1.16606-nightly and it's broken (button disappeared).

![image](https://user-images.githubusercontent.com/41873/97489087-19159680-192d-11eb-94d1-8ac3c92c9acb.png)

Same with your sample project. Button appears when I change to 0 radius.

![image](https://user-images.githubusercontent.com/41873/97490947-84f8fe80-192f-11eb-94c3-45da4600e47e.png)

Updated solution:
[Issue12315.zip](https://github.com/xamarin/Xamarin.Forms/files/5454549/Issue12315.zip)

**Comment by jsuarezruiz** [comment]
I can reproduce the issue in the last attached example but on the 5.0.0 branch, I still can't reproduce it.
@PureWeen Could you try https://github.com/xamarin/Xamarin.Forms/blob/fix-12315/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue12315.xaml to validate this case, please?

**Comment by ryanharding** [comment]
This is still happening on live version. 5.0.1.1876

**Comment by kmvickers** [comment]
I have this happening in version 5.0.1.1876 was there ever a fix ?
