### ISSUE TITLE
[Bug] Xamarin.Forms Blank Template 

### ISSUE THREAD

**Issue by jm-parent** [xamarin/Xamarin.Forms#12326]
### Description

Blank project start with some error.

### Steps to Reproduce

1. Create a Blank project
2. Compile

### Basic Information

- Vs Studio : Version 16.7.5

### Screenshots

![image](https://user-images.githubusercontent.com/39386863/94802537-2ac85480-03e8-11eb-939e-102bfbc56b3b.png)

![image](https://user-images.githubusercontent.com/39386863/94802563-2f8d0880-03e8-11eb-8df3-17407bff6ad0.png)

❗Same error in styles.xml
![image](https://user-images.githubusercontent.com/39386863/94802735-77ac2b00-03e8-11eb-8250-2b2e01e9625e.png)

If i rename all Name to name , it's the turn of androidmanifest 😣

![image](https://user-images.githubusercontent.com/39386863/94802890-b3df8b80-03e8-11eb-933c-a2984039fbab.png)
on this line 
`<application android:label="AnimatedLvItem.Android" android:theme="@style/MainTheme" android:name="android.app.Application" android:allowBackup="true" android:icon="@mipmap/icon" android:debuggable="true">`

I tried with Tabbar template and everything seems ok 👍

**Comment by hartez** [comment]
@jm-parent Does this occur for every new project you create with a blank template?

**Comment by jm-parent** [comment]
Just tried with new VS update. ( Microsoft Visual Studio Enterprise 2019 Version 16.7.6) 

It seems fixed 🤷‍♂️

![image](https://user-images.githubusercontent.com/39386863/96116480-ced1f580-0ee8-11eb-9c02-f49e2446912c.png)

I close this issue 👍
