### ISSUE TITLE
[Bug] FontImageSource problem in TabbedPage/NavigationPage/ContentPage/IconImageSource

### ISSUE THREAD

**Issue by RadoslawKubas** [xamarin/Xamarin.Forms#12325]
### Description

FontImage source works fine as source for TabbedPage page icon if page is directly inside tabbed page, but is not displayed if page is inside NavigationPage.

### Steps to Reproduce

1. Create TabbedPage with 2 pages (PageA, NavigationPage/PageB)
2. On PageA and PageB set IconImageSource

```
 <ContentPage.IconImageSource>
         <FontImageSource
            FontFamily="Arial"
            Glyph="A"
            Size="30"/>
    </views:PageBase.IconImageSource>

```

```
 <ContentPage.IconImageSource>
         <FontImageSource
            FontFamily="Arial"
            Glyph="B"
            Size="30"/>
    </views:PageBase.IconImageSource>

```
3. Start app, icon A is correct, but B is not displayed.

### Expected Behavior

Icon B is displayed.

### Actual Behavior

Icon B is not displayed.

### Basic Information

- Version with issue: 4.8.0.1415
- Last known good version: -

**Comment by hartez** [comment]
As a workaround, you can set the icon directly on the NavigationPage.

**Comment by RadoslawKubas** [comment]
@hartez I checked right now and it doesn't seem to fix the problem.

`<NavigationPage IconImageSource="B.png">`

and

`<ContentPage IconImageSource="B.png">`

works fine. But If I try

```
<NavigationPage.IconImageSource>
         <FontImageSource
            FontFamily="Arial"
            Glyph="B"
            Size="30"/>
<NavigationPage.IconImageSource>
```

icon is not displayed.

**Comment by SudhersonV** [comment]
The below xaml renders fine sin iOS but not in Android.
```
        <ContentPage.IconImageSource>
            <FontImageSource FontFamily="{x:Static v:FontAwesome.FontName}" Glyph="{x:Static v:FontAwesome.File_alt}" />
        </ContentPage.IconImageSource>
```

**Comment by RadoslawKubas** [comment]
Issue is fixed in Xamarin.Forms 5
