### ISSUE TITLE
[Enhancement] Xamarin Forms Components for Azure Communication Services

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#12341]
## Summary
Azure Communication Services comes with SDK's for iOS and Android. It would be great to provide components for Xamarin Forms. The person running the Xamarin Essentials site said that it's not their responsibility.

## API Changes

Add components for the Common and Calling areas of the SDK, which covers the iOS and Android functionality.

**Comment by Sarthak261995** [comment]
It would be so great if we can get bindings of the iOS and Android SDK's and a proper integration document.This can be a revolutionary library who wants to support chat and video/voice calling in their Xamarin App.

**Comment by Sarthak261995** [comment]
Check this Great work https://github.com/Laerdal/Xamarin.AzureCommunicationCalling though he might not be able to update binding on a regular interval

**Comment by NeerajRai111** [comment]
Can you share the plans or development for the integration of Azure communication services with Xamarin Forms?

**Comment by jfversluis** [comment]
No plans or on-going development at the moment :) sorry! Also, this won't be happening for Xamarin.Forms anymore, maybe for .NET MAUI. 

Not sure if that repo is the right place to ask for this though or where these libraries should live exactly. Unfortunately I don't have any more to offer at this time.
