### ISSUE TITLE
[Bug] iOS 14: Date/Time pickers open redundant "old style" bottom pane

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12343]
### Description

Hi.

Xamarin.Forms's date and time pickers open a redundant pane at the bottom on iOS 14. On older iOS versions this area held the date/time spinners, but iOS 14 should open a floating date/time selector. The redundant pane that opens requires the user to click the label inside it before the new "floating" picker is shown.

### Steps to Reproduce

1. Invoke a time or date picker on iOS 14

### Expected Behavior

iOS 14's "floating" picker controls should be used without the additional pane that requires a click before the "floating" picker opens.

### Actual Behavior

iOS 14 opens an "old style" pane at the bottom of the screen, which requires an additional click on the time/date shown in there before the iOS 14 style picker is opened.

### Basic Information

- Version with issue: Xamarin.Forms 5-pre1
- IDE: VS For Mac 2019
- Affected Devices: iOS 14 devices

### Screenshots

<img width="462" alt="Screenshot 2020-10-02 at 18 40 27" src="https://user-images.githubusercontent.com/60286968/94942685-4d896480-04df-11eb-988d-c383ad5af7d8.png">

**Comment by Tommigun1980** [comment]
Is this a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/12258 ?

**Comment by rmarinho** [comment]
yap is a duplicated of #12258
