### ISSUE TITLE
[Bug] RemoveBinding(...) does not reset Text property on Label and Entry

### ISSUE THREAD

**Issue by aeonblaire** [xamarin/Xamarin.Forms#12348]
### Description
RemoveBinding(...) does not reset Text property on Label and Entry

Related question: https://github.com/xamarin/Xamarin.Forms/discussions/12342

### Steps to Reproduce

1. Run the sample source code.
2. (Optional) Type some text to the source Entry.
3. (Choose) Activate OneWay or TwoWay binding using the 'OneWay' button or the 'TwoWay' button, respectively.
4. Type some text to the source Entry.
5. Remove the binding using the 'Remove Binding' button.

### Expected Behavior
Using `RemoveBinding([Entry / Label].TextProperty)` should reset the `[Entry / Label].Text` property, and set it to null.
Also subscription to relevant property changed events should be removed.

### Actual Behavior
Using `RemoveBinding([Entry / Label].TextProperty)` does nothing. Only subscription to relevant property changed events function properly.

### Basic Information
- Version with issue: Xamarin Forms 4.8.0.1451
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  iOS 13.4
  - Android: to be tested...
- Android Support Library Version:
- Nuget Packages: Xamarin Forms 4.8.0.1451
- Affected Devices: Tested on iPhone 11 Pro Max iOS 13.4 (Simulator) and iPhone 7 Plus
[RemoveBinding_does_not_work.zip](https://github.com/xamarin/Xamarin.Forms/files/5321360/RemoveBinding_does_not_work.zip)

**Comment by StephaneDelcroix** [comment]
you have the option to `ClearValue()` after calling `RemoveBinding()`. We don't keep an history of all the values that have been set to a property in the past, so we don't know to which value we should revert: the default ones, or the one that was present before the Binding was set ? RemoveBinding() means: remove the connection that updates values, and nothing more.

I keep this open as I don't get your comment about subscriptions

**Comment by aeonblaire** [comment]
My main concern is related to https://github.com/xamarin/Xamarin.Forms/issues/12202. I think if CollectionView has some glitches in [pre]caching of item views, some subviews might retain the values. Maybe reverting to the default values would have been nice, and might make it more consistent in relation to https://github.com/xamarin/Xamarin.Forms/issues/12347.
Anyway fixes for https://github.com/xamarin/Xamarin.Forms/issues/12202 I think would mitigate any retention of values.

**Comment by jsuarezruiz** [comment]
I've done some tests, and as Stephane indicates, using `ClearValue` in after calling `RemoveBinding`, reset the Text too. 
Let's review #12347 with #12202 to see what happens with subscriptions.
