### ISSUE TITLE
[Bug] FontImageSource does not work on UWP

### ISSUE THREAD

**Issue by nk221** [xamarin/Xamarin.Forms#12344]
### Description
FontImageSource does not work on UWP. 
### Steps to Reproduce

1. Download the project from Reproduction Link
2. Run the application - Image is displayed.
3. Update Xamarin.Forms package to version 4.8.0.1451 or above
4. Run the application - Image is not displayed.

### Expected Behavior
The image is displayed.
### Actual Behavior
The image is not displayed.
### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version: 4.8.0.1364

### Reproduction Link
[https://github.com/nk221/App1](url)

**Comment by jsuarezruiz** [comment]
Is a regression. The commit that introduce the issue is: https://github.com/xamarin/Xamarin.Forms/commit/0be21368444baa0ac032cbaa4e3d8f30766918ee

**Comment by holecekp** [comment]
I think that the mentioned commit should fix the issue https://github.com/xamarin/Xamarin.Forms/issues/12153. It appeared in 4.8 SR 2 and the fix has not been released yet. If you are making changes to the FontImageSource on UWP, please test also that both repro projects from the issue https://github.com/xamarin/Xamarin.Forms/issues/12153 still works (I have posted the repro projects later in the discussion to that issue).
