### ISSUE TITLE
[Bug] Using RemoveBinding(CollectionView.ItemsSourceProperty) does not work.

### ISSUE THREAD

**Issue by aeonblaire** [xamarin/Xamarin.Forms#12347]
### Description
Using `RemoveBinding(CollectionView.ItemsSourceProperty)` does not work.

### Steps to Reproduce

1. Run the sample source. NOTE: the sample source code is a modified version from https://github.com/xamarin/Xamarin.Forms/issues/12202
2. (Optional) Add some more items using 'Add' button.
3. Remove ItemsSource binding using 'Remove binding from ItemsSource' button.
4. Add some more items using 'Add' button.

Additional information:
If this line is uncommented `_clvItems.ItemsSource = null;` Step 4 will generate an unhandled exception.
If `ClearValue(CollectionView.ItemsSourceProperty);` is used instead, Step 4 will also generate an unhandled exception.
If a `ListView` is used, `RemoveBinding(ListView.ItemsSourceProperty)` also does not work, but setting `_clvItems.ItemsSource = null;` does not generate an unhandled exception in Step 4.

### Expected Behavior
Using `RemoveBinding(CollectionView.ItemsSourceProperty)` should reset the CollectionView.ItemSource property, and set it to null. Also, subscriptions to INotifyCollectionChanged events should be removed.

### Actual Behavior
Using `RemoveBinding(CollectionView.ItemsSourceProperty)` does nothing. CollectionView still subscribes to INotifyCollectionChanged events.

### Basic Information

- Version with issue: Xamarin Forms 4.8.0.1451
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS: iOS 13.4
  - Android: to be tested...
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms 4.8.0.1451
- Affected Devices: Tested on iPhone 11 Pro Max iOS 13.4 (Simulator) and iPhone 7 Plus
[CollectionView_Redundant_Binding.zip](https://github.com/xamarin/Xamarin.Forms/files/5321295/CollectionView_Redundant_Binding.zip)

**Comment by aeonblaire** [comment]
As pointed out in https://github.com/xamarin/Xamarin.Forms/issues/12348#issuecomment-704090305, I added the usage of `ClearValue(CollectionView.ItemsSourceProperty);` for additional information.

**Comment by StephaneDelcroix** [comment]
> Using `RemoveBinding(CollectionView.ItemsSourceProperty)` does nothing.

see #12348 

CollectionView still subscribes to INotifyCollectionChanged events.

the source hasn't been cleared, so listening to INCC is expected

**Comment by aeonblaire** [comment]
What? @StephaneDelcroix  I don't understand, you specifically said "RemoveBinding() means: remove the connection that updates values", so why "listening to INCC" is still expected? I thought that subscribing to INCC is the essence of binding to a Collection that implements INCC?

**Comment by StephaneDelcroix** [comment]
Remove the Binding, in this case, drops the inPc connection, so if the ItemSource (as a whole) is swapped as a whole object in your VM, that won't be reflected to your View. But unless you clear it, the ItemSource is still there, and the inCc connection (unrelated to the original Binding) continues to work

**Comment by aeonblaire** [comment]
@StephaneDelcroix IF by 'clear it', you mean ClearValue() ok then, it should be equivalent to setting to null. but if you mean like ObservableCollection.Clear(), It doesn't make sense that the subscription to INCC will be removed only when removing the objects from the ItemSource. But even then, it generates an unhandled exception when adding new objects to the existing item source. Would it be better if I submit a more specific ticket?
