### ISSUE TITLE
[Bug] CarouselView items cannot scroll vertically since v4.6.0.967

### ISSUE THREAD

**Issue by melicaster** [xamarin/Xamarin.Forms#12349]
### Description
CarouselView cannot scroll vertically since v4.6.0.967

### Steps to Reproduce

1. Clone from https://github.com/erossini/CarouselViewChallenge
2. Update Xamarin Forms greater than v4.6.0.967
3. You should not able to scroll vertically using mouse scroll

### Expected Behavior
Expected the CarouselView items to be scrolled vertically when scrolling.

### Actual Behavior
CarouselView items not scrolled.

### Basic Information

- Version with issue: v4.6.0.967 or greater
- Last known good version: v4.6.0.847
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS: Not tested
  - Android: Not tested
  - UWP:  16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Windows 10 devices that using CarouselView

### Screenshots

![image](https://user-images.githubusercontent.com/15340082/94992627-f6a68c80-05bd-11eb-80fc-0d570d09dace.png)
Cannot scroll to right

### Reproduction Link

N/A

### Workaround

Unfortunately, I did not found any workaround except downgrade the version to v4.6.0.847.

**Comment by rmarinho** [comment]
This was fixed by #12361 Would be on the next 4.8.0 or 5.0.0
