### ISSUE TITLE
[Bug] Hot Restart - works on one solution, not another

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#12340]
#### We can make a brand new solution and it'll work fine with Hot Restart on iOS, But the basics do not work on our existing solution...
- the connected iPhone never shows up as "Local device" on the target devices drop down list.
- When checking Configuration Manager, the Debug/iPhone configuration has a greyed out Deploy checkbox, 
- The only situation in which the deploy checkbox is not disabled is if I connect vs2019 to the mac and plug in the iPhone to it. 

Any ideas?

> VS bug [#1226115](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1226115)

**Comment by hartez** [comment]
@MitchBomcanhao Which version of Visual Studio are you using? And which version of Xamarin.Forms?

**Comment by MitchBomcanhao** [comment]
I'm on VS 16.7.4, a few different versions of XF across projects (from 4.2 to 4.6 and 4.8)
Oddly enough, today the iPhone appears as available (sometimes). App is seemingly deployed but crashes on launch.
I don't understand what has changed to allow the local iPhone to be available, but if I can't consistently reproduce it, this issue investigation isn't going very far :/

**Comment by jsuarezruiz** [comment]
@MitchBomcanhao Could you share logs from Visual Studio? (can be via email)

**Comment by MitchBomcanhao** [comment]
I'm sorry, I can't dedicate much more time to this issue right now, as other priorities have crept up... Will reopen this if I still have this issue and can get any more information in the future.
