### ISSUE TITLE
[Bug] iOS 14: Radio buttons gained unremovable one pixel border

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12345]
### Description

When updating to iOS 14, all my radio buttons now show an unremovable one pixel border around them.

### Steps to Reproduce

1. Add a radio button and run on iOS 14.

I used the following:
```xaml
                    <RadioButton
                        Content="Hello world!"
                        IsChecked="True"
                        GroupName="myRadioGroup" />
```

Please note that even explicitly trying to remove the border doesn't work:

```xaml
                    <RadioButton
                        Content="Hello world!"
                        IsChecked="True"
                        BorderColor="Transparent"
                        BorderWidth="0"
                        GroupName="myRadioGroup" />
```

### Expected Behavior

There should not be a border around the radio buttons.

### Actual Behavior

There is a border around the radio buttons.

### Basic Information

- Version with issue: Xamarin.Forms 5-pre1
- IDE: VS For Mac 2019
- Affected Devices: iOS 14 devices

### Screenshots

<img width="130" alt="Screenshot 2020-10-02 at 21 07 50" src="https://user-images.githubusercontent.com/60286968/94955710-aa8f1580-04f3-11eb-889c-279da062533c.png">

### Workaround

Tried to explicitly set border width to 0 and border color to transparent, but the border is still shown and can't seemingly be hidden.

**Comment by jsuarezruiz** [comment]
I have created a reproduction sample:
[Issue12345.zip](https://github.com/xamarin/Xamarin.Forms/files/5326321/Issue12345.zip)

But cannot reproduce the issue:
<img width="1215" alt="Captura de pantalla 2020-10-05 a las 10 55 10" src="https://user-images.githubusercontent.com/6755973/95059579-5e152700-06f9-11eb-936c-1055e39e6b56.png">

I am using Xamarin.Forms 5-pre1 and testing in iOS 14 simulators, can see the result in the previous screenshot. @Tommigun1980 Could you review the attached sample?.

**Comment by Tommigun1980** [comment]
Hi again @jsuarezruiz - I decided to update to Xamarin.Forms 5 again now that dependent libraries work properly with it so this became an issue again. Could you please confirm if you did your test with Xamarin.Forms 5 as the issue doesn't happen with Xamarin.Forms 4.

I double checked the styling in my app and I don't have any custom renderers or styles set up for the radio buttons, so it should be vanilla on my side.

My guess is that the radio button incorrectly uses some other component's color as its border color in XF 5. The color I get in the border is the exact same color I use as an 'accent color' in my app's theme. Problem is I style almost every single control with it so it would take me a long time to isolate which one the radio button is incorrectly using. Maybe you guys could give a pointer on this and I would be happy to help as radio buttons look very buggy for me now.

Thank you.

**Comment by jsuarezruiz** [comment]
@Tommigun1980 I am using Xamarin.Forms 5.0.0 branch and iOS 14.1 simulators. Could you attach an example where reproduce the issue?

**Comment by Tommigun1980** [comment]
> @Tommigun1980 I am using Xamarin.Forms 5.0.0 branch and iOS 14.1 simulators. Could you attach an example where reproduce the issue?

Hi. This is the XAML:

```c#
                <StackLayout Style="{StaticResource ContentStyle}">
                    <Label Text="Select date and time" />
                    <RadioButton
                        Content="Right now"
                        IsChecked="True"
                        GroupName="timeRadioGroup" />
                    <RadioButton
                        Margin="0, -10, 0, 0"
                        x:Name="specifyDateAndTimeRadioButton"
                        Content="Specify date and time"
                        GroupName="timeRadioGroup" />
                    <toolkit:Expander
                        IsVisible="{Binding IsChecked, Source={x:Reference specifyDateAndTimeRadioButton}}"
                        IsExpanded="{Binding IsChecked, Source={x:Reference specifyDateAndTimeRadioButton}}">
                        <StackLayout>
                            <DatePicker />
                            <TimePicker />
                        </StackLayout>
                    </toolkit:Expander>
                </StackLayout>
```

I don't have any special renderers or styles for check box.

**Comment by PureWeen** [comment]
Not sure @Tommigun1980 

did you test with @jsuarezruiz 's repro? I updated his repro to the latest 5.0 and I don't see any borders

Pinging @hartez just in case something rings a bell for him

**Comment by Tommigun1980** [comment]
Hi @PureWeen and @jsuarezruiz, I was not able to reproduce it with the repro case when run as is, but was when copied to my project. I removed one implicit style at a time until found that the following affected the radio buttons:

```
    <Style
		TargetType="Frame"
		ApplyToDerivedTypes="True">
        <Setter
			Property="OutlineColor"
			Value="{DynamicResource MyOutlineColor}" />
    </Style>
```

So apparently a frame's stylings "bleed" into radio buttons.
What I don't understand is why this happens **only** on iOS 14.

**Comment by Tommigun1980** [comment]
I can't get this to work. I need the implicit styling on the frame, but not on radio buttons.
Explicitly overriding BorderColor on the radio button instances, or by adding
```xaml
    <Style
		TargetType="RadioButton"
		ApplyToDerivedTypes="True">
        <Setter
			Property="BorderColor"
			Value="{x:Null}" />
    </Style>
```
does nothing -- if you ever set a border color on frames then radio buttons look ugly on iOS 14.

**Comment by programatix** [comment]
I'm still having this issue with Xamarin Forms 5.0.0.2401 even though it is marked as resolved. Radio buttons inside a Frame with targeted BorderColor style cause them to have border.

**Comment by ahoke-cr** [comment]
I have radiobuttons not inside a frame that have a black 1-pixel border on iOS. I have a global style setting border width to zero and color to transparent. iOS 15.5 and Xamarin.Forms 5.0.0.2083
