### ISSUE TITLE
[Bug] GoToAsync("..") passes null as QueryProperty to previous page

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/Xamarin.Forms#12351]
### Steps to Reproduce

1. Have two pages that accept `QueryProperty` (let's say _item details_ and _edit item_)
2. Open _item details_ of some item using `Shell.Current.GoToAsync` and click on _Edit_ button to open _edit item_ page also using `Shell.Current.GoToAsync`
3. Close _edit item_ page using `await Shell.Current.GoToAsync("..");`
4. _item details_ page will be opened, but with **null** as _QueryProperty_, instead of item id

### Expected Behavior
item id is passed as _QueryProperty_ or state is not changed at all

### Actual Behavior
null is passed as _QueryProperty_ which invalidates state of the page

### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version: -
- IDE: VS2019
- Platform Target Frameworks: v11
  - iOS:  -
  - Android: 11
  - UWP:  -
- Android Support Library Version: 
- Nuget Packages: CClarke.Plugin.Calendars v1.0.14, Xamarin.Essentials v1.5.3.2
- Affected Devices:

### Workaround

Ignore _QueryProperty_ change if page has some value and **null** is passed as new value

**Comment by maxkoshevoi** [comment]
Also there is no animation in this scenario (even if I explicitly ask for it `GoToAsync("..", true)`)

**Comment by PureWeen** [comment]
@maxkoshevoi this is fixed on 5.0

Can you test the latest pre3?
