### ISSUE TITLE
[Bug] CarouselView shows "Value can not be null" error when i insert a listview inside the view

### ISSUE THREAD

**Issue by fkbeys** [xamarin/Xamarin.Forms#12352]
### Description

CarouselView shows "Value can not be null" error when i insert a listview inside the view.

### Steps to Reproduce

1. I want to use the CarouselView with indicator view.
2. To use it dynamically, i wrote the below xaml code.
3. But it shows error "Value can not be null". I think it s a bug.
4. when i remove the listview, the application works fine, but when ever i add the listview, it shows error

[ Project Url on Github ](https://github.com/fkbeys/Carousel-to-Page-with-ndctor)
i shared the xaml code too. i hope it helps 
### Expected Behavior
i want to have 2 carousel view as pages. 
Inside pages, i need listviews.  On the other hand, the indicatorview should show the which page is active.

### Actual Behavior
But due to listview it shows error. when i comment the listview, then it works.it s really interesting

### Basic Information

- Version with issue:4.60.1141
- Last known good version:
- IDE:visual studio windows
- Affected Devices:Android

### *****************Code***********************
 <?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App1.MainPage">

    <StackLayout BackgroundColor="WhiteSmoke">

        <CarouselView IndicatorView="MYINDICATOR">

            <CarouselView.ItemsSource>
                <x:Array Type="{x:Type ContentView}">
                    <ContentView>
                        <StackLayout   >

                            <Label Text="First Page"/>

                            
                            <ListView ItemsSource="{Binding Stocks}">
                                <ListView.ItemTemplate>
                                    <DataTemplate>
                                        <ViewCell>
                                            <StackLayout>
                                                <Label Text="{Binding Name}"  TextColor="Black"/>
                                            </StackLayout>
                                        </ViewCell>
                                    </DataTemplate>
                                </ListView.ItemTemplate>
                            </ListView>
                            
                        </StackLayout>
                    </ContentView>
                    
                    
                    <ContentView>
                        <StackLayout    >
                            <Label Text="Second Page" TextColor="Black"/>
                        </StackLayout>
                    </ContentView>
                    
                    
                </x:Array>
            </CarouselView.ItemsSource>
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <ContentView Content="{Binding .}" />
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>

        <IndicatorView x:Name="MYINDICATOR" BackgroundColor="Transparent" IndicatorColor="LightGray" SelectedIndicatorColor="DarkGray" HorizontalOptions="Center" />

    </StackLayout>
</ContentPage>

**Comment by jsuarezruiz** [comment]
Just a detail, it works without using XamlC.

**Comment by fkbeys** [comment]
> Just a detail, it works without using XamlC.

sir, Do you mean to design the page with C# code?
My page is too complicated and it will be really hard for me to desgn it with c# code.

**Comment by fkbeys** [comment]
> Just a detail, it works without using XamlC.

i have just tried to skip the xaml Xaml Compilation. it works, but listview doesnt show anything

**Comment by fkbeys** [comment]
@jsuarezruiz  i finally managed to make what i want.  I called the ContentVire from an other page. It works 
but this time, the listview doesnt work correctly.
While navigating the listview, the page jump from page2 to page 1.
I uploaded the code on github too. and i uploaded the video too. Please have a look.

[Youtube](https://youtu.be/1yY_uRT7Li4)

[Project On Github](https://github.com/fkbeys/Carousel-to-Page-with-ndctor)

Thanks.

**Comment by rmarinho** [comment]
Hey @fkbeys  just use a `CollectionView` and it will work fine. 

```
     <CollectionView x:Name="MyList" >
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <StackLayout>
                        <Label Text="{Binding Name}"  TextColor="White"/>
                    </StackLayout>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
```

**Comment by fkbeys** [comment]
> Hey @fkbeys just use a `CollectionView` and it will work fine.
> 
> ```
>      <CollectionView x:Name="MyList" >
>             <CollectionView.ItemTemplate>
>                 <DataTemplate>
>                     <StackLayout>
>                         <Label Text="{Binding Name}"  TextColor="White"/>
>                     </StackLayout>
>                 </DataTemplate>
>             </CollectionView.ItemTemplate>
>         </CollectionView>
> ```

thnx. it works.
