### ISSUE TITLE
[Bug] MarkerClicked event triggers only once after opening new Navigation Page (UWP only)

### ISSUE THREAD

**Issue by aristotelis96** [xamarin/Xamarin.Forms#12354]
### Description
This Bug **only** appears on **UWP**. Android seems to be working fine. Have not tested iOS.
When you create a new Navigation Page, by clicking a Pin on the map, the pin works only the first time.
Upon returning from the new Navigation Page, the previous clicked Pin, is not clickable any more.

### Steps to Reproduce

1. Create a xamarin blank project and include Xamarin.forms.map. Also use "Hierarchical Navigation".

2. Initialize a map, create a new Pin with MarkerClicked EventHandler and add Pin with `map.Pins.Add()`.
3. Inside the EventHandler for MarkerClicked event, open a new NavigationPage.
4. Click the pin, go to the new Nav Page and return to the previous Page.

### Expected Behavior
A new Navigation Page is opened when the Pin is clicked. After closing (returning from) the new Navigation Page
the Pin click should be working properly and if clicked, it should open again the new Navigation Page.

### Actual Behavior
Tha Pin click is no longer working, when you click it, nothing happens.

### Basic Information

- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0
  - UWP:  18362
- Nuget Packages: Xamarin.Forms-4.8.0.1451, Xamarin.Forms.Maps-4.8.0.1451
- Affected Devices:  UWP windows 10

### Reproduction Link
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/5322878/Test.zip)

### Workaround

Inside the MarkerClicked handler, create a Pin with `Pin pin = sender as Pin;` , remove it from `map.Pins.Remove(pin)`
and re-add with `map.Pins.Add(pin);`.

**Comment by jsuarezruiz** [comment]
After tapping the Pin and navigating, when navigating back, tapping again does not work (except deleting and adding the pin again), right?. I have done tests in 4.8 and 5.0 and the behavior is:

![issue12354](https://user-images.githubusercontent.com/6755973/95198942-54b0bb00-07dc-11eb-9bb3-659ca897b95a.gif)

Is working without the workaround. Could you try your repro sample without the workaround?.

**Comment by aristotelis96** [comment]
Just downloaded Test.zip, removed the workaround (lines 30,31 MainPage.xaml.cs) and the behaviour is:
![test](https://user-images.githubusercontent.com/35195468/95202098-8a0fd580-07e9-11eb-8a05-d695209c3540.gif)

**Comment by jsuarezruiz** [comment]
@PureWeen Could you try the sample, please?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
