### ISSUE TITLE
[Bug] Grid inside StackLayout does not respect VerticalOptions FillAndExpand on UWP

### ISSUE THREAD

**Issue by nk221** [xamarin/Xamarin.Forms#12363]
### Description
The Grid inside StackLayout does not respect VerticalOptions FillAndExpand on UWP.

### Steps to Reproduce

1. Download the project from Reproduction Link
2. Run the application - the Grid fills all available space of parent StackLayout.
3. Update Xamarin.Forms to version 4.8.0.1364 or above
4. Run the application - the Grid does not fill parent StackLayout.

### Expected Behavior
The Grid should fill all available space of parent StackLayout.

### Actual Behavior
The Grid Height depends on window size and changes from 100% to 0%.

### Basic Information

- Version with issue: 4.8.0.1364
- Last known good version: 4.7.0.1351

### Screenshots
![1](https://user-images.githubusercontent.com/26190351/95083204-9fc3c300-0735-11eb-9d2b-2d2acf82d371.png)

### Reproduction Link
[GridInsideStackLayout.zip](https://github.com/xamarin/Xamarin.Forms/files/5327525/GridInsideStackLayout.zip)

**Comment by jsuarezruiz** [comment]
The behavior is different between 4.7 and 4.8 (and seems incorrect under some conditions in 4.8).

4.7
![issue12363-4 7-2](https://user-images.githubusercontent.com/6755973/95186787-a6e8e080-07ca-11eb-88dc-7f2402599f04.gif)

4.8
![issue12363-4 8-2](https://user-images.githubusercontent.com/6755973/95186845-b7995680-07ca-11eb-9fa4-aba26132d4fb.gif)

cc @hartez
