### ISSUE TITLE
[Bug][Android]Navigate to Tabbed Page from MasterDatail page using button click caused delay 

### ISSUE THREAD

**Issue by saiganeshls2504** [xamarin/Xamarin.Forms#12360]
### Description
The Navigate from Master Detail Page to TabbedPage using button click caused delay. Inside the Tab, we have grid with 42 Label.
XF Version: 4.8.0.1354

### Steps to Reproduce

1. Run the sample
2. click the Load Page with gif modal
3. Initial it took more time to load the page.

### Expected Behavior
it should load quickly
### Actual Behavior
it took more time
### Basic Information

- Version with issue: 4.8.0.1354
- Affected Devices: Moto G5 S plus (Android 8.1 – API 27) 

### Sample and tested Video are attached
[SFIssueDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/5326699/SFIssueDemo.zip)
[20201005_141439.mp4.zip](https://github.com/xamarin/Xamarin.Forms/files/5326589/20201005_141439.mp4.zip)

**Comment by jsuarezruiz** [comment]
To focus the attention on navigating to the details page (MasterDetailPage with a TabbedPage using some custom controls), I have removed the modal view using Rg.Plugins.Popup, the gif, Task.Delay etc.

The result is:

![issue12360](https://user-images.githubusercontent.com/6755973/95216980-fd6a1500-07f2-11eb-969f-952c370c86ec.gif)

Measuring time:
- First navigation: 243 ms
- Successive navigations: 39 ms

If you do a similar test, is it similar result, or are we talking about critical times like second/s?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
