### ISSUE TITLE
[Enhancement] Provide control for color picker

### ISSUE THREAD

**Issue by dhpanteon** [xamarin/Xamarin.Forms#12373]
## Summary
Is it possible to provide control for color picker?

e.g.
1. Standard control: 

![UOUcVAQ](https://user-images.githubusercontent.com/25735370/95165150-09d97800-07c9-11eb-87fa-f34a9ee541f0.png)

2. If above is not possible then can we create control like this? where user can provide list of color hex and Xamarin form will render it as bellow. 

![dialog](https://user-images.githubusercontent.com/25735370/95165173-1231b300-07c9-11eb-9fc7-1732837434fc.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
