### ISSUE TITLE
[Bug] XF ListView and CollectionView leak on Android

### ISSUE THREAD

**Issue by tiitk** [xamarin/Xamarin.Forms#12375]
### Description
ListView and CollectionView remain in Android memory even if page that holds them is wiped by garbage collection.
Works fine with UWP. Not tried with iOS.

### Steps to Reproduce
1. Push page with listview to navigation stack
2. Pop page with listview from navigation stack
3. Clear page content so that nothing is referencing it anymore.
4. Page is sent for garbage collectionig, its children ListView/CollectionView are not.

### Expected Behavior
All children of page should be released from memory when page is released. Even ListView and CollectionView

### Actual Behavior
Page is released from memory but its children ListView and CollectionView are not.

### Basic Information
- Version with issue:
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 4.6, 4.8, 5.0-pre
  - iOS:  dunno
  - Android: 9.0

### Screenshots
https://prnt.sc/utw0rn
https://prnt.sc/utw12j
https://prnt.sc/utw1db
https://prnt.sc/utw1oa
https://prnt.sc/utw1wu
https://prnt.sc/utw252
https://prnt.sc/utw2ez
https://prnt.sc/utw2rl

### Reproduction Link
https://github.com/tiitk/LV

### Workaround
No workaround found.

**Comment by jsuarezruiz** [comment]
cc @hartez

**Comment by PureWeen** [comment]
@tiitk you have to force garbage collection to test if things are cleaned up.

```C#

        protected override void OnAppearing()
        {
            base.OnAppearing();

            Device.BeginInvokeOnMainThread(async () =>
            {
                await Task.Delay(100);
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
            });
        }
```

Try that and let me know your results

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
