### ISSUE TITLE
[Bug] NavigationPage.TitleView do not resize after modal NavigationPage on UWP

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#12382]
### Description
The `TitleView` does not react/resize after `PopModal` of `NavigationPage`.

### Steps to Reproduce
1. Define `TitleView` on `MainPage`
2. Navigate `Modal` to `NavigationPage`
3. `PopModal`
4. Resize window, the `MainPage.TitleView` does not react on resize

### Expected Behavior
`TitleView` resize with application after `PopModal NavigationPage`

### Actual Behavior
`TitleView` does not react/resize with application after `PopModal NavigationPage`

### Basic Information
- Version with issue: 4.8.0.1451
- Last known good version: ?
- IDE: VS Pro 16.7.5
- Platform Target Frameworks:
  - UWP: 18362

### Screenshots
![9X3Vxwewec](https://user-images.githubusercontent.com/4254116/95224576-1b3b7800-07fb-11eb-8a75-1cfeb879314b.gif)

### Reproduction Link
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/uwp-push-navigationPageTitle

**Comment by Connor24601** [comment]
I'm experiencing this same issue. Any updates or workarounds?

**Comment by YZahringer** [comment]
Should be fixed by #10849
