### ISSUE TITLE
[Bug] Design renders Orange MockView in latest version

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12389]
I could not find a open issue on this, all reported issues were closed.

I have the latest nightly build installed. This problem repeats itself overtime and it seems to appear at random times.

Installed: Xamarin.Forms 5.0.01.1457-nightly
Note: Also repro'd in latest released version (4.8.0.1451)

Repro:
1. Open any page in the designer.

Result:
1. Orange screen that shows "MockView".

I have tried rebooting VS, rebooting PC, cleaning solution and rebuilding multiple times.

I got this error to go away once but now I can't seem to.

**Comment by snowman745** [comment]
To fix the issue, after trying pretty much every other proposed solution online, I reinstalled VS updating to VS 2019 Version 16.7.5

Now the designer is working again.

**Comment by jsuarezruiz** [comment]
I'm glad to know that after reinstalling everything works again. I am going to close this issue. If you have any other problem that we can help with, you can open another issue.
