### ISSUE TITLE
[Bug] Page flickers when pushing a new page in Master-Detail

### ISSUE THREAD

**Issue by baneageorge** [xamarin/Xamarin.Forms#12385]
### Description
I noticed that on iOS when pushing a new page that contains Label with TextType="Html" a weird flicker shows before the page shows

### Steps to Reproduce

1. Create a master-detail app
2. Create a page1 with a label and TextType="Html"
3. Create a page2 with a label and don't specify the TextType

### Expected Behavior
When opening any of the pages the animation should be smooth.

### Actual Behavior
Wehn opening page1 a weird animation shows before the page appears.

### Basic Information

- Version with issue: Xamarin forms 4.8.0.1451
- Last known good version:
- IDE: Visual Studio for mac 8.7
- Platform Target Frameworks: 
  - iOS:  14.0 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhones

### Workaround
Don't use labels with TextType='Html'

**Comment by jsuarezruiz** [comment]
Thanks for all the information. I tried to reproduce the issue creating a small sample:
[Issue12385.zip](https://github.com/xamarin/Xamarin.Forms/files/5340426/Issue12385.zip)
But the navigation animations looks without flickering:
![issue12385](https://user-images.githubusercontent.com/6755973/95327480-69f11c80-08a4-11eb-96d6-40c107c99b17.gif)
Not sure if I am using the same navigation hierarchy etc. @baneageorge  Could you take a look to the sample?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
