### ISSUE TITLE
[Bug] Localized string not updated when setting the culture in an async method in Android.

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [xamarin/Xamarin.Forms#12396]
[LocalizationIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5340001/LocalizationIssue.zip)

Localized string not updated when setting the culture in an async method.

### Steps to Reproduce

1. Run the sample. Click the "Lang" button then click "Navigate".
2. Localized string not updated when setting the culture inside the async method.
3. Remove the async in the "lang_Clicked" method and follow the above steps. Now the localized string updated.

### Expected Behavior

The localized string should be updated when setting the culture inside the async method.

### Actual Behavior

The localized string not updated when setting the culture inside the async method.

### Basic Information

- Version with issue: 4.6
  - Android: version 9.0

### Screenshots

Normal method:
![Screenshot_20201007-160655](https://user-images.githubusercontent.com/28334651/95322786-ab8cc200-08ba-11eb-9272-2332e24ed2f0.jpg)

Async method:
![Screenshot_20201007-160749](https://user-images.githubusercontent.com/28334651/95322827-be9f9200-08ba-11eb-8bb5-4e76825356dc.jpg)

**Comment by WorldOfBasti** [comment]
This issue appears on iOS as well.

**Comment by jsuarezruiz** [comment]
But, the Lang button will not work whether it is synchronous or asynchronous execution.
If a service is created where `CurrentCulture` and `CurrentUICulture` is changed on each platform, then will work;
![issue12396](https://user-images.githubusercontent.com/6755973/95571449-c9783500-0a28-11eb-920f-320bb815bb9a.gif)

```
void Button_Clicked(object sender, EventArgs e)
{
    Navigation.PushAsync(new LocalizedXamlPage());
}

async void lang_Clicked(object sender, EventArgs e)
{
    CultureInfo ci = new CultureInfo("es-ES");
    AppResources.Culture = ci;
    DependencyService.Get<ILocalizeService>().SetLocale(ci);
}
```

There is really no impact in this case in using async or not. Could you try it?. If I have not understood something, just let me know!.

**Comment by WorldOfBasti** [comment]
Hello @jsuarezruiz, the AppResources updates fine in an async method. The problem is with the CurrentUICulture. I updated the sample with a label, which shows the current UICulture. Here is a gif: 
![Issue 12396](https://user-images.githubusercontent.com/48362172/95604181-98fbbf80-0a57-11eb-86b7-cd08546abd14.gif). And here is the updated sample: 
[Xamarin_Forms___ResX_Localization_demo.zip](https://github.com/xamarin/Xamarin.Forms/files/5356047/Xamarin_Forms___ResX_Localization_demo.zip)

**Comment by rmarinho** [comment]
I think what's happing is you are setting in a diffrent Thread when you use the async keyword.

try something like this:

``` 
Device.BeginInvokeOnMainThread(() =>
{
       CultureInfo ci = new CultureInfo("es-ES");
       System.Threading.Thread.CurrentThread.CurrentUICulture = ci;
       AppResources.Culture = ci;
});
```

**Comment by WorldOfBasti** [comment]
> I think what's happing is you are setting in a diffrent Thread when you use the async keyword.
> 
> try something like this:
> 
> ```
> Device.BeginInvokeOnMainThread(() =>
> {
>        CultureInfo ci = new CultureInfo("es-ES");
>        System.Threading.Thread.CurrentThread.CurrentUICulture = ci;
>        AppResources.Culture = ci;
> });
> ```

Thank you so much! With this works it as expected.

**Comment by rmarinho** [comment]
Awesome!
