### ISSUE TITLE
[Bug] CollectionView Orientation="Horizontal" with ObservableCollection<T> as Datasource and reorder the Items in the Collection -> Native Crash IOS 14.0

### ISSUE THREAD

**Issue by Fenki404** [xamarin/Xamarin.Forms#12394]
### Description
A CollectionView with Orientation "Horizontal", and ObservableCollection<T> as Datasource.
If the Items in the Collection gets moved from position 2 to 0 and after that 2 to 1, a native crash occures.

### Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/46244359/95318142-6a82b680-0896-11eb-9b9d-a9b75ff30eab.png)
2. 
populate the Collection with 3 Items.
3. 
Sort the Collection with collection.Move(idx, ptr);
[0:] Sort move 2 to 0
[0:] Sort move 2 to 1

### Expected Behavior
   don't crash
### Actual Behavior
   Native Crash

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x121e48a48):0x121e48a38  0f 1f 84 00 00 00 00 00 48 85 ff 7e 1a 48 8b 07 ........H..~.H..
0x121e48a48  f6 40 20 04 0f 85 12 00 00 00 48 8b 35 ef 66 01  .@ .......H.5.f.
0x121e48a58  00 ff 25 01 46 01 00 48 89 
f8 c3 90 55 48 89 e5  ..%.F..H....UH..
0x121e48a68  41 57 41 56 41 54 53 48 83 ec 10 49 89 ff 44 89  AW
AVATSH...I..D.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSendSuper <0x000e1>
	  at UIKit.UICollectionViewLayout:InvalidateLayout <0x001ea>
	  at Xamarin.Forms.Platform.iOS.ItemsViewLayout:InvalidateLayout <0x00172>
	  at System.Object:runtime_invoke_void__this__ <0x00195>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_IntPtr <0x0010d>
	  at UIKit.UICollectionView:MoveItem <0x002ba>
	  at Xamarin.Forms.Platform.iOS.ObservableItemsSource:Move <0x0035c>
	  at <CollectionChanged>d__29:MoveNext <0x0098a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x001fa>
	  at Xamarin.Forms.Platform.iOS.ObservableItemsSource:CollectionChanged <0x0016a>
	  at <CollectionChanged>d__28:MoveNext <0x00552>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x0020a>
	  at Xamarin.Forms.Platform.iOS.ObservableItemsSource:CollectionChanged <0x00192>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x000fa>
	  at System.Collections.ObjectModel.ObservableCollection`1:OnCollectionChanged <0x0011b>
	  at System.Collections.ObjectModel.ObservableCollection`1:MoveItem <0x0019a>
	  at System.Collections.ObjectModel.ObservableCollection`1:Move <0x00080>
	  at UserContentApp.Content.Common.ObservableCollectionExtensions:Sort <0x00c72>
	  at <Load>d__40:MoveNext <0x00d82>
	  at MoveNextRunner:InvokeMoveNext <0x000ab>
	  at System.Threading.ExecutionContext:RunInternal <0x00585>
	  at System.Threading.ExecutionContext:Run <0x00092>
	  at MoveNextRunner:Run <0x001aa>
	  at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00093>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x00153>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0013a>
	  at System.Threading.Tasks.Task:FinishContinuations <0x006ae>
	  at System.Threading.Tasks.Task:FinishStageThree <0x0015a>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00262>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x002e2>
	  at <GetItemsAsync>d__12:MoveNext <0x01562>
	  at MoveNextRunner:InvokeMoveNext <0x000ab>
	  at System.Threading.ExecutionContext:RunInternal <0x00585>
	  at System.Threading.ExecutionContext:Run <0x00092>
	  at MoveNextRunner:Run <0x001aa>
	  at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00093>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x00153>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0013a>
	  at System.Threading.Tasks.Task:FinishContinuations <0x006ae>
	  at System.Threading.Tasks.Task:FinishStageThree <0x0015a>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00262>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x002e2>
	  at <GetItemsFromQueriesAsync>d__17:MoveNext <0x00fea>
	  at MoveNextRunner:InvokeMoveNext <0x000ab>
	  at System.Threading.ExecutionContext:RunInternal <0x00585>
	  at System.Threading.ExecutionContext:Run <0x00092>
	  at MoveNextRunner:Run <0x001aa>
	  at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00093>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x00153>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0013a>
	  at System.Threading.Tasks.Task:FinishContinuations <0x006ae>
	  at System.Threading.Tasks.Task:FinishStageThree <0x0015a>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00262>
	  at WhenAllPromise`1:Invoke <0x008d2>
	  at System.Threading.Tasks.Task:FinishContinuations <0x004c9>
	  at System.Threading.Tasks.Task:FinishStageThree <0x0015a>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00262>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x002e2>
	  at <GetItemsFromQueryAsync>d__18:MoveNext <0x00a82>
	  at MoveNextRunner:InvokeMoveNext <0x000ab>
	  at System.Threading.ExecutionContext:RunInternal <0x00585>
	  at System.Threading.ExecutionContext:Run <0x00092>
	  at MoveNextRunner:Run <0x001aa>
	  at System.Threading.Tasks.AwaitTaskContinuation:InvokeAction <0x00093>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x00153>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x0013a>
	  at System.Threading.Tasks.Task:FinishContinuations <0x006ae>
	  at System.Threading.Tasks.Task:FinishStageThree <0x0015a>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00262>
	  at System.Threading.Tasks.TaskCompletionSource`1:TrySetResult <0x00092>
	  at System.Threading.Tasks.TaskCompletionSource`1:SetResult <0x0007a>
	  at <>c__DisplayClass37_0:<GetAsync>b__0 <0x001b2>
	  at SDQuerySnapshotHandler:Invoke <0x001dd>
	  at SDQuerySnapshotHandler:Invoke <0x0011a>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x00254>
	  at UIKit.UIApplication:Main <0x000b2>
	  at UIKit.UIApplication:Main <0x00132>
	  at UserContentApp.iOS.Application:Main <0x00092>
	  at <Module>:runtime_invoke_void_object <0x00342>

### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  14.0

- Nuget Packages:
- Affected Devices:
   IPhone 11Pro

### Workaround

set the CollectionView.Orientation to Vertical

**Comment by jsuarezruiz** [comment]
Attached reproduction sample:
[Issue12394.zip](https://github.com/xamarin/Xamarin.Forms/files/5340094/Issue12394.zip)

**Comment by hartez** [comment]
@jsuarezruiz I don't see a crash with the repro project, no matter how many times I hit the button.

**Comment by jsuarezruiz** [comment]
Weird. I cannot reproduce it either.

**Comment by jfversluis** [comment]
Not reproducible anymore it seems
