### ISSUE TITLE
[Enhancement] Report Uwp BindingDiagnostics for initial page load

### ISSUE THREAD

**Issue by maxbrister** [xamarin/Xamarin.Forms#12400]
## Summary
For Xamarin/Uwp the runtime tooling does not attach until after the first page loads. Currently, there isn't a way of getting source information for the initial binding failures.

## API Changes

If the `ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO` environment is set on Xamarin/Uwp, BindingDiagnostics should cache events if there are no listeners attached.

## Intended Use Case

The VS binding failures window should be able to report source information for binding failures on the initial page in Xamarin/Uwp.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
