### ISSUE TITLE
Xamarin.Forms xaml file become colorless and non-editable

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12415]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1203956/xamarinforms-xaml-file-become-colorless-and-non-ed.html)._

---
Whenever I close a xaml file and reopen it then file become colorless and non-editable like I can write anything but unable to remove. Whole keyboard is working except tab,space,backspace. And to resolve this issue I have to reopen whole solution. Please guide me how to solve this problem. I try to reset whole setting but still facing problem.

---
#### Feedback Bot on 9/30/2020, 03:54 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could you share some extra information:
- Do you use Visual Studio for Windows or macOS?
- What version?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
