### ISSUE TITLE
Xamarin.Forms MessagingCenter Problem (Code execute more times)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12414]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1191048/xamarinforms-messagingcenter-problem-code-execute.html)._

---
[severity:It's more difficult to complete my work]
When I subscribe to message in page1 constructor and send message from page2, for first time I open page1 no problem but when I close page1 and reopen it again
It receive the message two times and if I close it again and reopen it will receive the message three times and so on

---
#### Michael Anwar Azzar on 9/20/2020, 01:10 AM: 

<p>In an attempt to solve this problem my self I have downloaded the MessagingCenter Class from xamarin.forms source code from here </p><p>https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/MessagingCenter.cs</p><p>and I have modified this function {<strong>commented If statement</strong>}</p><p>and tested it again it working correctly now, (the message sent one time) But I am concerned about the effect of this I don't know if this will affect something else</p><pre>void InnerSubscribe(object subscriber, string message, Type senderType, Type argType, object target, MethodInfo methodInfo, Filter filter)
		{
			if (message == null)
				throw new ArgumentNullException(nameof(message));
			var key = new Sender(message, senderType, argType);
			var value = new Subscription(subscriber, target, methodInfo, filter);</pre><pre class="">			<em>//if (_subscriptions.ContainsKey(key))
			//{
				//_subscriptions[key].Add(value);
			//}
			//else
			//{</em>
				<strong>var list = new List&lt;Subscription&gt; { value };
				_subscriptions[key] = list;</strong>
			<em>//}</em>
		}<br></pre>
</pre>

#### Feedback Bot on 9/21/2020, 08:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Michael Anwar Azzar on 9/23/2020, 08:56 PM: 

<p>I have commented some code in xamarin.forms <strong>core</strong> code not in my project code and included custom MessagingCenter class in my project to solve this problem</p>

#### Feedback Bot on 9/27/2020, 02:38 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Zack Yang [MSFT] solved on 9/22/2020, 10:16 AM, 0 votes: 

<p>Thanks for your feedback! I’m glad you’ve solved the issue. If the other issue occurs ,please feel free to contact us.</p>

#### Michael Anwar Azzar on 9/22/2020, 11:59 AM: 

<p>I have commented some code in xamarin.forms <strong>core</strong> code not in my project code and included custom  MessagingCenter class in my project to solve this problem </p>

**Comment by jsuarezruiz** [comment]
Michael, could you attach a small example where reproduce the issue?

**Comment by MichaelAzzar** [comment]
Sorry for delay 🙂
I attached sample with some images to describe the problem, I apologize for my way in describing the problem

[Small sample with some images](https://drive.google.com/file/d/1TtnwKrEHx3Z2OGUn_R4Vq5x72H2726oh/view?usp=drivesdk)

**Comment by GiampaoloGabba** [comment]
Correct me if i'm wrong but in your example you are opening two times the "Page1" page, right?
You are subscribing to a Message in the constructor (calling the ViewModel that does the subscription), but you are not unsubscribing :)
So when you close the Page1 and then reopen it, you have 2 active subscriptions, and they will continue to grow every time you close and reopen Page 1.

Try to unsubscribe to the message in Page1 in the OnDisappearing override, everything should work fine.
Always remember to unsubscribe when you are using the Messaging center, or strange behaviours/leaks will come to knock to your door soon or later :)

**Comment by MichaelAzzar** [comment]
Correct me if i'm wrong but in your example you are opening two times the "Page1" page, right?
You are subscribing to a Message in the constructor (calling the ViewModel that does the subscription), but you are not unsubscribing :)
Yes you are correct, but I tried unsubscribing,
 It do nothing in my case

**Comment by YiannisBourkelis** [comment]
@jsuarezruiz @GiampaoloGabba @MichaelAzzar @Redth 
[pushpagememorybug.zip](https://github.com/xamarin/Xamarin.Forms/files/5432133/pushpagememorybug.zip)

I am having the same issue with messaging center publishing the same message multiple times. I am attaching a project to reproduce this issue. The problem appears on both iOS and Android, but on iOS it is easier to reproduce.

The messaging center should publish the "NotifyMe Called" message only once, but as you will see it publishes the message multiple times (at max 6 times after ,multiple push/pop of the child page on the navigation stack).

Steps to reproduce:
1. Start debugging on iOS device
2. Tap on "Push Page" button, to push the ChildPage to the Navigation stack
3. Navigate to the previous page
4. Tap on "Push Page" button again and tap "Send Message" button
5. On the Application Output windows you will see the "NotifyMe Called" message appears twice.
6. Repeat steps 3-5. You will see the "NotifyMe Called" message multiple times

**Comment by PureWeen** [comment]
You need to Unsubscribe otherwise it will just keep calling left over subscriptions

The MessageCenter is a global static structure so it will retain references that survive the popping of the page. I realize that it uses weak references but those only get cleaned up after a GC runs
