### ISSUE TITLE
Xamarin Forms PCL Referencing other Net Standard 2.1 Libraries Build Issues

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1207162/xamarin-forms-pcl-referencing-other-net-standard-2.html)._

---
[severity:It's more difficult to complete my work]
Hi,

I have issues with building my Xamarin Forms Android Project, when the PCL is referencing other Net Standard 2.1 libraries.
I am not getting build errors or anything like that.
However every time I update one of these Net Standard 2.1 libraries referenced by the PCL.
I have to do a clean and rebuild of the entire solution otherwise changes in these libraries are not compiled.

Even when major changes are made to these projects Visual Studio still says they are up to date.
When I press the green start button to run my Android start up project.

For all other projects (for example console apps, WPF apps) I have used in Visual Studio, I have not had to do this to get the updated code to deploy.
This is a hassle because sometimes this step can be missed or forgotten and old outdated code will run messing up the debugger
This happens to all my projects even with custom project dependency options set
To reproduce just create a Xamarin Forms Project add a few Net Standard 2.1 Class Libraries, reference them from the PCL and change the code in one of them and redeploy

---
#### Feedback Bot on 10/3/2020, 00:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
The issue happens in Visual Studio for macOS or for Windows?, could you share the Visual Studio version?

**Comment by phillw1994** [comment]
Hi Javier,
I'm using Microsoft Visual Studio Community 2019
Version 16.7.5
Running on Windows 10

**Comment by PureWeen** [comment]
@phillw1994 PCL libraries can't reference Netstandard 2.1 libraries. If I remember correctly PCL only supports up to NS 1.4 (maybe 2.0?)

If I'm not understanding your issue can you add a repro?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
