### ISSUE TITLE
[Bug]  SHELL: FlyoutItem / ShellContent "IsVisible=false" makes it impossible to navigate to (or stay on) that page

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#12428]
### Description
Setting an item to "IsVisible=false" should really only hide it from the flyout, nothing else!
As it is implemented now, you can not navigate (from code) to an invisible item. Even worse, if you are on a page and then set it to invisible, the page is switched to some other page.

### Expected Behavior
All navigation should continue to work normally (you can always override this in code if wanted).
The invisible items should be invisible, nothing else.

### Actual Behavior
Navigation routes are inaccessible which results in strange or unwanted navigation.

### Workaround
I tried to be smart by manipulating the ItemTemplate. I binded the "IsVisible"-property of all items in the template to the "Text-property of the item with a valueconvertor (I added a non-printable character to the text to indicate visibility).
The result is that the item is invisible because the height of the item adapts itself and becomes zero. Because of that, it is also impossible to click on it. Exactly what I need.
BUT NOT IN IOS!! There the itemheight doesn't become zero. There seems to be a minimum itemheight. I will submit a separate issue for that.

**Comment by jsuarezruiz** [comment]
Attached a reproduction sample:
[Issue12428.zip](https://github.com/xamarin/Xamarin.Forms/files/5353975/Issue12428.zip)

**Comment by jsuarezruiz** [comment]
cc @PureWeen

**Comment by AbhijeetChowdhury92** [comment]
Hi,
I'm  using the latest version of Xamarin.forms. In my project, I have got Flyout items that are toggled based on user type dynamically. The problem I'm facing is when I set FlyoutItem IsVIsible  to false to one of the flyout items, I can't navigate to any modal pages or dialogs in iOS.

This wasn't there with Xamarin.forms version 5.0.0.1874.

**Comment by HandiVision** [comment]
Hi, same problem here, some of my shell flyout items visibility are toggled by user status (logged in or not). When an item goes invisible it becomes impossible to navigate to modal pages on iOS. (Using Xamarin.Forms 5.0.0.2291)
