### ISSUE TITLE
[Bug] Xamarin.Forms crash Android.Views.InflateException after rotate in Shell-based app

### ISSUE THREAD

**Issue by uwcanada** [xamarin/Xamarin.Forms#12423]
### Description
On a physical Android device, in debug or release mode, any rotation of any Shell hosted content page will cause the next page to be loaded to crash on load with an InflateException. This project is as stripped back and simple as I could make it. It crashes 100% of the time with the repro steps below.

### Steps to Reproduce
1. Using attached sample proj, start project on a physical Android 10 device (does not crash in emulator in limited testing)
2. Rotate device on home screen
3. Navigate to the next screen by pressing the giant button
4. App will crash with Android.Views.InflateException 'Binary XML file line#1.....' - tested extensively (as in hundreds of times) on a physical device

### Expected Behavior
When not rotated first, the navigation raises no exception. No problems on iOS.

### Actual Behavior
Exception on subsequent nav to any page after rotate.

### Basic Information
- Version with issue: Visual Studio 16.7.5, Xam 16.7.000.452, Xam.Forms 4.8.0.1534
- Last known good version: ?
- IDE: ?
- Platform Target Frameworks:
  - Android: 9, 10

- Android Support Library Version: default? none? no nuget in project
- Nuget Packages: NetStd Library 2.0.3, Xam.Forms, Xam.Forms.Visual.Material
- Affected Devices: LG LM-G820, Android 10

### Screenshots
![image](https://user-images.githubusercontent.com/1211353/95522709-d2bac080-099a-11eb-82c2-c4a6d22ec17c.png)
[RotateCrashAndroidDevice.zip](https://github.com/xamarin/Xamarin.Forms/files/5351703/RotateCrashAndroidDevice.zip)

### Reproduction Link
Project attached

### Workaround
NONE - 3 days of trying.

**Comment by jsuarezruiz** [comment]
Can reproduce the issue. Thanks for the repro sample @uwcanada.

**Comment by uwcanada** [comment]
This is a show stopping critical bug reported over 6 weeks ago; at what point should we expect a fix for an app that is sitting here waiting to launch?

**Comment by PureWeen** [comment]
@uwcanada it looks like this exception is caused by the override you have in MainActivity

```C#
        public override Android.Content.Res.Resources Resources
        {
            get
            {
                var config = new Android.Content.Res.Configuration();
                config.SetToDefaults();

                return CreateConfigurationContext(config).Resources;
            }
        }
```

If I comment that out then everything works fine.

**Comment by uwcanada** [comment]
If true, I owe you a huge thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
