### ISSUE TITLE
[Bug] DatePicker unselected dates not showing

### ISSUE THREAD

**Issue by osamakawish** [xamarin/Xamarin.Forms#12424]
### Description

The dates on the `DatePicker` that aren't selected, aren't visible.

### Steps to Reproduce

Not much, I believe I have a `DatePicker`. Haven't done much color change besides what's noticeable.

### Expected Behavior

I expected them to be visible.

### Actual Behavior

It is not visible.

### Basic Information

Using Xamarin.Forms 4.6. and my Android's version is 10. The minimum SDK version for android is set to 21 and the target is 28.
Not tested on iOS or UWP since this was made on a Visual Studio on Windows 10.

### Screenshots

[The DatePicker when attempting to select a date](https://photos.app.goo.gl/1REkanygQa5AZ1xx9).

### Reproduction Link

Haven't tested this but I think a new Xamarin app with a simple `DatePicker` should be enough to reproduce the issue.

**Comment by osamakawish** [comment]
Also, I should add, I'd ideally want to be able to set the color for all the text, rather than simply make them visible. But I can probably test that around with `colorAccent` or something once I can actually see the text.

**Comment by jsuarezruiz** [comment]
I have created a sample trying to reproduce the issue:
[Issue12424.zip](https://github.com/xamarin/Xamarin.Forms/files/5353228/Issue12424.zip)
But I have not managed to reproduce the problem:
<img width="400" alt="Captura de pantalla 2020-10-09 a las 9 31 21" src="https://user-images.githubusercontent.com/6755973/95555690-74312900-0a12-11eb-9a95-4b8c927aa74c.png">

- Could you try the attached example?
- Are you using a specific configuration (linker, etc)?

**Comment by osamakawish** [comment]
Oops. Sorry, I'll work on this in a bit and double check. Checked on my phone yesterday then forgot about it by accident.

**Comment by osamakawish** [comment]
Okay, so I tried it on both blank and fly layouts, and I get white text for he datepicker. I'm guessing it may have to do with preset colours.

**Comment by osamakawish** [comment]
Okay, I couldn't run your app. I'm getting the following errors (which don't take me to the source of the errors when I double click the errors):

![Screenshot (16)](https://user-images.githubusercontent.com/20045083/95641774-36fc8380-0a72-11eb-8202-21265d921fcf.png)

(Don't worry about the warning at the bottom)

**Comment by osamakawish** [comment]
Sorry, ignore the last comment because I did stuff and I don't recall what I did to get the results above. I downloaded the .zip file and it won't even run on my Android. I have a Samsung Galaxy Tab A if that makes any difference.

**Comment by AmrAlSayed0** [comment]
I have a feeling Dark Mode has something to do with this.

**Comment by osamakawish** [comment]
@AmrAlSayed0 It turns out it was definitely the Dark Mode being turned on.
