### ISSUE TITLE
[Bug] [UWP] [Shell] Back Button Not Displayed

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#12443]
### Description

The back button is not displaying on shell navigation in a UWP app.

### Steps to Reproduce

1. Create a new Xamarin Forms application with the Flyout Menu template.
2. Add a UWP project.
3. Enable the experimental Shell feature.
4. Run the UWP version.
5. Select Browse.
6. Select an item.

### Expected Behavior

A back button appears.

### Actual Behavior

The back button only appears on ios and Android, not UWP.

### Basic Information

- Version with issue: 4.8.0.1534
- Last known good version: Unknown
- IDE: Visual Studio 2019 16.7.5
- Platform Target Frameworks: 
  - iOS:  14.0
  - Android: 9.0 
  - UWP:  19041 

### Screenshots

Android:

![image](https://user-images.githubusercontent.com/4465616/95664912-41ba2580-0b11-11eb-84bc-3b2688a4906a.png)

iOS:

![image](https://user-images.githubusercontent.com/4465616/95664946-8e9dfc00-0b11-11eb-86bd-b0732fd6f28b.png)

Windows:

![image](https://user-images.githubusercontent.com/4465616/95664841-04559800-0b11-11eb-916c-57b53e5f7ab4.png)

### Reproduction Link

https://github.com/scottkuhl/XamarinFormsTemplate

### Workaround

Not yet.  But if I find one it will be listed here: https://github.com/scottkuhl/XamarinFormsTemplate/issues/46

**Comment by PureWeen** [comment]
This should be fixed on 5.0 @scottkuhl 

Let me know if you are still seeing issues there

**Comment by albertoha94** [comment]
Greetings,
Could someone confirm if this was solved please?
I am using `Xamarin.Forms 5.0.0.1709-pre4` with Shell integrated and UWP still doesn't show the back button when using `await Shell.Current.GoToAsync`, is there a setting I'm missing to enable them?

**Comment by BurkusCat** [comment]
@albertoha94 I was seeing this issue on `4.8.0.1821` and I've just upgraded to `5.0.0.1874` (Xamarin 5.0 is officially released now). It appears to have resolved the issue 👍

(Note: I wasn't using Shell, just standard Xamarin.Forms)
