### ISSUE TITLE
[Bug] [UWP] [Shell] First Flyout Item Crashes on Navigation

### ISSUE THREAD

**Issue by scottkuhl** [xamarin/Xamarin.Forms#12444]
### Description

The first button in the side flyout menu always crashes on UWP.  Works fine on Android and iOS.

### Steps to Reproduce

1. Create a new Xamarin Forms application with the Flyout Menu template.
2. Add a UWP project.
3. Enable the experimental Shell feature.
4. Run the UWP version.
5. Select Browse.
6. Select About from the Flyout menu.

### Expected Behavior

The About page appears.

### Actual Behavior

The application crashes.

"The operation attempted to access data outside the valid range (Exception from HRESULT: 0x8000000B)"

### Basic Information

- Version with issue: 4.8.0.1534
- Last known good version: Unknown
- IDE: Visual Studio 2019 16.7.5
- Platform Target Frameworks: 
  - iOS:  14.0
  - Android: 9.0 
  - UWP:  19041 

### Workaround

None found.

**Comment by GiampaoloGabba** [comment]
this is already fixed in the latest v5 prelease :)
I know because i'm playing with uwp shell in these days and with 4.8 i got the same error but with v5 pre2 is gone

**Comment by PureWeen** [comment]
Yea, v5 has a lot of UWP Shell love!!

So please let us know any issues you run into

**Comment by scottkuhl** [comment]
Hopefully starting with v5 UWP overall will become more stable.  It hasn't been getting the attention it deserves for years.  Once I heard of the increased support and focus for Maui I was so happy.

**Comment by PureWeen** [comment]
Closing this for now

Let me know if you still see this issue with 5.0 @scottkuhl
