### ISSUE TITLE
[Bug] Referencing Xamarin Forms Nuget breaks Tizen CarouselPage renderer

### ISSUE THREAD

**Issue by DamianMehers** [xamarin/Xamarin.Forms#12451]
### Description

In my app, I have the following Projects:
* MyApp.Forms - contains all cross-platform Forms code, and references Xamarin.Forms
* MyApp.Tizen - contains Tizen-Specific Forms code, and references MyApp.Forms, Tizen.NET and Tizen.Wearable.CircularUI
* MyApp.iOS -  contains iOS code, and references MyApp.Forms
* MyApp.Android-  contains Androidcode, and references MyApp.Forms

I share my Forms code across all the platforms.  This structure breaks the rendering of the CarouselPage on Tizen.

**The CarouselPage does not render properly when the Tizen Project references the Xamarin.Forms Nuget, either directly or indirectly (such as via the MyApp.Forms project above).**

### Steps to Reproduce

1.  Create a new Tizen Forms wearable project (api version 4)
2.  In your App.xaml.cs replace the main page assignment with ` MainPage = new NavigationPage(new CarouselPage { Title = "hello", BackgroundColor = Color.Orange });`
3. Run the app - the orange background is displayed
4. Update the app to reference the standard Xamarin Forms Nuget.
5. Run the app - the orange background is NOT displayed.  Rendering is broken

This is a simple example, but it seems to me that rendering is totally broken in that pages added to the CarouselPage don't display at all.

### Expected Behavior

I expect to be able to put my shared Xamarin Forms code in its own project, which references the Xamarin Forms Nuget, and have a separate Tizen-Specific project which references the shared project,

### Actual Behavior

Referencing the Xamarin Forms Nuget either directly, or indirectly breaks rendering of the CarouselPage

### Basic Information

* Visual Studio Tools for Tizen 3.1.0.0
* Tizen.NET.Sdk/1.0.9
* Xamarin.Forms 4.8.0.1534
* Tizen.Wearable.CircularUI 1.5.2
* Visual Studio About: [version.txt](https://github.com/xamarin/Xamarin.Forms/files/5361489/version.txt)
### Reproduction Link

[TestTizenCarouselPage.zip](https://github.com/xamarin/Xamarin.Forms/files/5361487/TestTizenCarouselPage.zip)

**Comment by rookiejava** [comment]
Hi @DamianMehers, thank you for reporting issue. Let me check!

**Comment by rookiejava** [comment]
When I checked with the test project you attached, I confirmed that the problem was caused by the side effect of #11824. Since this PR has been applied from 4.8.0.1364, it is recommended to use version 4.8.0.1269  or lower until it is modified.

As you can see below, 4.8.0.1269 works well (both mobile and wearable). Thanks.

<img src="https://user-images.githubusercontent.com/1029134/95822182-5f33fd00-0d66-11eb-821c-b48ad14ab5b2.png" width=240/><img src="https://user-images.githubusercontent.com/1029134/95822184-60652a00-0d66-11eb-93e1-f228898d2af5.png" width=240 />

**Comment by DamianMehers** [comment]
Great, thanks I'll try it out. Not sure yet if the that CarouselPageRenderer depends on internals, but if not perhaps I can compile and register it in the current version.

**Comment by rookiejava** [comment]
Will submit a patch soon. 😉
