### ISSUE TITLE
[Bug] Xaml shouldn't support nested types, giving error instead

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.Forms#12455]
### Steps to Reproduce

1. Use nested types in your XAML, like is done in https://github.com/microsoft/TailwindTraders-Mobile/blob/master/Source/TailwindTraders.Mobile/TailwindTraders.Mobile/Features/Product/Detail/ProductDetailPage.xaml with:
```
x:TypeArguments="local:ProductDetailViewModel, local:ProductDetailViewModel.State"
```
2. Build and debug the app. Note that everything works.
3. Make a change to the page using incremental Hot Reload. Note that you get the hot reload error (from the parser): `Nested types are not supported: ProductDetailModel.State`

### Expected Behavior

Discussed with @StephaneDelcroix and he said that nested types aren't intended to be support with Xaml. They can produce parsing ambiguities, which is the exact same reason that they aren't supported in WPF/UWP.

So, after discussing, we decided that the proper fix here is to give an error message on the Forms side when nested types are used in XAML so that users remove them from their apps. That will avoid any errors from parsing ambiguities, avoids hot reload related errors (where they don't work), and makes Forms XAML more consistent with WPF/UWP. We believe that few apps use nested types, and those that do would thus have to remove them when upgrading to Forms 5.0.

See also https://devdiv.visualstudio.com/DevDiv/_queries/edit/1180608

### Basic Information

- Version with issue: all

**Comment by StephaneDelcroix** [comment]
x:TypeArguments at the top-level is only used by XamlG

**Comment by StephaneDelcroix** [comment]
this will revert #872 and #867

**Comment by StephaneDelcroix** [comment]
nested types are supported in x:Static using the `+` separator. apparently also in WPF. I wonder if the `+` syntax to x:TypeArguments, x:Type, x:DataType, etc is also valid

**Comment by StephaneDelcroix** [comment]
after discussing this with @mgoertz-msft, we agreed to leave things as is. x:TypeArguments, x:Type, and x:Static syntax will keep supporting nested types (the x:Static case is even documented iirc). Could you please file a bug so intellisense stops complaining about it : thanks
