### ISSUE TITLE
[Bug] Why Rectangle couldn't have the same Width as Label. 

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#12454]
### Description

I want to set the width of a Rectangle  to the same width as a Label by using the following code, but the Rectangle is not displayed properly. And when I used the same code for a button, it can display the same width as the Label.  Why?

      <StackLayout
                            Margin="10"
                            BackgroundColor="Purple"
                            HorizontalOptions="FillAndExpand"
                            Orientation="Vertical">

        <Label
                                x:Name="labelTagTitle"
                                BackgroundColor="Gray"
                                FontSize="Large"
                                HorizontalOptions="Center"
                                Text="A label test test test test"
                                TextColor="AntiqueWhite" />

        <Rectangle
                                Fill="DarkBlue"
                                HorizontalOptions="Center"
                                HeightRequest="50"
                                RadiusX="50"
                                RadiusY="50"
                                Stroke="Red"
                                StrokeLineJoin="Round"
                                StrokeThickness="5"
                                WidthRequest="{Binding Source={x:Reference labelTagTitle}, Path=Width}"
                                />

        <Button
                               WidthRequest="{Binding Source={x:Reference labelTagTitle}, Path=Width}"
                               Text="A Button"
                               HeightRequest="50"
                               HorizontalOptions="Center"
                                />

    </StackLayout>

### Steps to Reproduce

1. create a new form app;
2.  add above code to the new app;
3. deploy to a device.

### Expected Behavior
Hope Rectangle couldn't have the same width as Label. 

### Actual Behavior

Rectangle couldn't have the same width as Label. 

### Screenshots
![image](https://user-images.githubusercontent.com/42464252/95700446-9f698180-0c79-11eb-9144-16475c189bb9.png)

**Comment by rachelkang** [comment]
@jessiezh0320 thanks for asking this question! Would you mind sharing some more details and clarifying the situation a bit further? I tried running the code you provided, and it unfortunately causes the app to crash for me. I'd love to be more clear on what exactly is happening with the widths of the various views, and what exactly you're trying to accomplish. Thank you!

**Comment by jessiezh0320** [comment]
Here is a simple demo, you can  check it here. 

[FormApp1.zip](https://github.com/xamarin/Xamarin.Forms/files/5368457/FormApp1.zip)

**Comment by GalaxiaGuy** [comment]
This could be the default padding on Android buttons. There is a platform specific `UseDefaultPadding` that can be used to turn this off:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/button-padding-shadow
