### ISSUE TITLE
[Bug] Cannot Change Using Application.Current.MainPage After MainPage Is Set In Application File.

### ISSUE THREAD

**Issue by bsglinux16** [xamarin/Xamarin.Forms#12450]
### Description

**Once Set in the MainPage Application File, it will not change again.**

### Steps to Reproduce

**1. Set MainPage Mainpage.xaml in App.xaml.cs
2.Application.Current.MainPage = new Sekmeli(); in Initialize Section After MainPage Page Is Loaded; The Page Does Not Change Even We Do It.
3. The page stays on MainPage.xaml and Doesn't Switch to Sekmeli.xaml**

### Expected Behavior

**Switching to Sekmeli.xaml after MainPage.xaml Init**

### Actual Behavior

**MainPage.xaml Remains.**

### Basic Information

- Version with issue: **4.6.1141 // 4.8.1534 // 5.0-pre1 // 5.0-pre2 (Tried Versions)**
- Last known good version: none
- IDE: Vs2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: Mono.Android 9.0 / 10.0  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[UIWorks.zip](https://github.com/xamarin/Xamarin.Forms/files/5361307/UIWorks.zip)

### Workaround

**Tried Using Navigation.PushModalAsync But When I Press Back Button, It Goes Back To Old Page. Page Must Be Permanent**

**Comment by rachelkang** [comment]
@bsglinux16 are you using Shell? What do your LoginPage and HomePage look like? Could you update your attached repro sample project to include these details? Thank you! :)

**Comment by bsglinux16** [comment]
> @bsglinux16 are you using Shell? What do your LoginPage and HomePage look like? Could you update your attached repro sample project to include these details? Thank you! :)

I don't know what is Shell.

I gave HomePage and LoginPage a Wrong Example.
Let me update the description instead of the repro.

**Comment by bsglinux16** [comment]
> @bsglinux16 are you using Shell? What do your LoginPage and HomePage look like? Could you update your attached repro sample project to include these details? Thank you! :)

updated issue

please test repro project
Project pages remains on MainPage not switch Sekmeli.xaml

This is the case with all Projects and Versions I Specified.

**Comment by StephaneDelcroix** [comment]
Everything works as expected.

So, you're doing

```csharp
public App()
{
    MainPage = new MainPage();
}
```

and in MainPage constructor
```csharp
public MainPage()
{
    Application.Current.MainPage = new Sekmeli();
}
```

and you expect the Application.CurrentMainPage to be the `Sekmeli` page ? Well, this assumption is wrong. Whatever you do in the MainPage constructor is executed (the App.Current.MP is actually set to Sekmeli) but then, the MainPage constructor returns an instance of MainPage, and that MainPage is set to App.Current.MP, overriding the previously set value.

**Comment by bsglinux16** [comment]
> Everything works as expected.
> 
> So, you're doing
> 
> ```cs
> public App()
> {
>     MainPage = new MainPage();
> }
> ```
> 
> and in MainPage constructor
> 
> ```cs
> public MainPage()
> {
>     Application.Current.MainPage = new Sekmeli();
> }
> ```
> 
> and you expect the Application.CurrentMainPage to be the `Sekmeli` page ? Well, this assumption is wrong. Whatever you do in the MainPage constructor is executed (the App.Current.MP is actually set to Sekmeli) but then, the MainPage constructor returns an instance of MainPage, and that MainPage is set to App.Current.MP, overriding the previously set value.

So how else do we change the MainPage value?
