### ISSUE TITLE
[Enhancement] Add properties to indicate if a scrollview CanScrollUp or CanScrollDown

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#12463]
## Summary
Phones often hide the scrollbar when it is not active, so a user may not know that they can scroll the view.  Adding properties to indicate if the view can scroll in a particular direction would give the developer the option of adding visual indicators.

## API Changes
Bool CanScrollUp - indicates that the view can be scrolled up
Bool CanScrollDown indicates that the view can be scrolled down.

If the view doesn't extend beyond the space (and thus can't be scrolled at all) both properties would be false.  If the view does extend beyond the space once the user scrolled to the bottom CanScrollDown would be false, 

## Intended Use Case
I have a list of items on the flyout window.  The last item visible ends at the bottom of the view and iOS automatically hides the scrollbar when the user is not actively scrolling.  There is nothing to indicate to the user that they can scroll down and see more options.  With these properties I could add a visual indicator that I could then hide when the user reached the bottom of the scrollview.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
