### ISSUE TITLE
[Bug] Setting Text for button in Shell.TitleView Crashes App in Xamarin Android XF (4.8latest and 5.0)

### ISSUE THREAD

**Issue by dgerding** [xamarin/Xamarin.Forms#12477]
### Setting the text value of a Button throws a JNI Error and crashes app: **"Can't call void android.view.View.setElevation(float) on null object in lapism/SearchView"**.

[This problem, as an Android problem, is referenced in StackOverflow here. ](https://stackoverflow.com/questions/40928788/cant-call-void-android-view-view-setelevationfloat-on-null-object-in-lapism-s)

Xaml button that's a child of Shell.TitleView is:
`<Button x:Name="ButtonSaveWebArticle" Clicked="ButtonSaveWebArticle_Clicked" Text="{Binding SaveButtonText}" IsEnabled="{Binding CanSaveText}" HorizontalOptions="Start" FontSize="Micro" WidthRequest="50" Margin="0,0,0,0" Padding="0,0,0,0">
                    <Button.FontFamily>
                        <OnPlatform x:TypeArguments="x:String">
                            <On Platform="iOS" Value="wordbahn2" />
                            <On Platform="Android" Value="wordbahn2.ttf#wordbahn2" />
                            
                        </OnPlatform>
                    </Button.FontFamily>
                </Button>`

C# that throws exception is just:
`SaveButtonText = _saveButton_SavedText;`

### Steps to Reproduce
Note: I did not create a new project to reproduce, reporting from project in development. However, commenting out the bound single string assignment in the viewmodel gets rid of the crash. Running with the string set crashes.

1. Create button in Xamarin Forms parent app for Shell.TitleView 
2. Use text font icon in the xaml button 
3. Change the text icon string from viewmodel at runtime using bound string property.

### Expected Behavior
Icon string changes

### Actual Behavior
JNI error related to AppBarLayout crashes app.
### Basic Information

- Version with issue: 5.0 (and 4.8 latest)
- Last known good version: ?
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 10 and 11 produce same results
- Android Support Library Version: AndroidX latest releases
- Affected Devices: Emulator and Pixel 4 test devices

**Comment by dgerding** [comment]
Update/Additional Info: On a hunch, I tried using a "plain old string", commenting out the Button.FontFamily element in the xaml referenced example and replacing the FontAwesome font character with a single letter string. 

So... something somewhere doesn't like the unicode character?

**Comment by PureWeen** [comment]
@dgerding can you attach a reproduction please?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
