### ISSUE TITLE
[Bug] 5.0.0_pre could NOT update Xamarin.Forms

### ISSUE THREAD

**Issue by filipoff2** [xamarin/Xamarin.Forms#12470]
### Description

1. Manage/update nuggets for solution from 4.6 to 5.0. pre

2. Common project was updated successfully. 
   manual changes with references to NGraphics.Rect
  
/Controls/Ring.cs(51,51): Error CS0104: 'Rect' is an ambiguous reference between 'Xamarin.Forms.Rect' and 'NGraphics.Rect' (CS0104) 

3.  ios/android projects ware not updated

### Expected Behavior
should update and compile

### Actual Behavior
doesn't compile 
 cant't resolve the reference 'System.Void Xamarin.Forms.FlyoutPage::set_Detail(Xamarin.Forms.Page)

OS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.FlyoutPage::set_Detail(Xamarin.Forms.Page)', referenced from the method 'System.Void Volotea.Mobile.App::CreateNewMainPage(System.Boolean)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101)
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS for MAC community 8.4.8
- Platform Target Frameworks: 
  - iOS:  
  - Android Support Library Version: 
- Nuget Packages:
<PackageReference Include="AWSSDK.Core">
      <Version>3.3.21.20</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
      <Version>3.0.0</Version>
    </PackageReference>
    <PackageReference Include="Com.OneSignal">
      <Version>3.5.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter">
      <Version>3.3.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Analytics">
      <Version>3.3.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.AppCenter.Crashes">
      <Version>3.3.0</Version>
    </PackageReference>
    <PackageReference Include="MvvmLightLibsStd10">
      <Version>5.4.1.1</Version>
    </PackageReference>
    <PackageReference Include="NControl">
      <Version>0.9.1</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.3</Version>
    </PackageReference>
    <PackageReference Include="PCLAppConfig">
      <Version>1.0.1</Version>
    </PackageReference>
    <PackageReference Include="PCLCrypto">
      <Version>2.0.147</Version>
    </PackageReference>
    <PackageReference Include="PCLStorage">
      <Version>1.0.2</Version>
    </PackageReference>
    <PackageReference Include="Plugin.Permissions">
      <Version>3.0.0.12</Version>
    </PackageReference>
    <PackageReference Include="Rg.Plugins.Popup">
      <Version>1.2.0.223</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp.Svg">
      <Version>1.60.0</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp.Views.Forms">
      <Version>1.68.0</Version>
    </PackageReference>
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.6.292</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity">
      <Version>3.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Geolocator">
      <Version>4.5.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle">
      <Version>3.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Settings">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.CardIO.iOS">
      <Version>5.4.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="4.6.0.1073" />
    <PackageReference Include="Xamarin.Forms.Maps">
      <Version>4.6.0.1073</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.Analytics">
      <Version>3.17.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.TagManager">
      <Version>7.1.1.1</Version>
    </PackageReference>
    <PackageReference Include="System.Reflection.Emit" Version="4.6.0">
      <ExcludeAssets>all</ExcludeAssets>
      <IncludeAssets>none</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xamarin.Swift4">
      <Version>4.0.0.2</Version>
    </PackageReference>

**Comment by filipoff2** [comment]
PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.21.20" />
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie" Version="3.0.0" />
    <PackageReference Include="Com.OneSignal" Version="3.5.0" />
    <PackageReference Include="Microsoft.AppCenter" Version="3.3.0" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="3.3.0" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="3.3.0" />
    <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
    <PackageReference Include="NControl" Version="0.9.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="PCLAppConfig" Version="1.0.1" />
    <PackageReference Include="PCLCrypto" Version="2.0.147" />
    <PackageReference Include="Plugin.Permissions" Version="3.0.0.12" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.5" />
	<PackageReference Include="Rg.Plugins.Popup" Version="1.2.0.223" />
    <PackageReference Include="SkiaSharp.Svg" Version="1.60.0" />
    <PackageReference Include="SkiaSharp.Views.Forms" Version="1.68.0" />
    <PackageReference Include="sqlite-net-pcl" Version="1.6.292" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Connectivity" Version="3.2.0" />
    <PackageReference Include="Xam.Plugin.Geolocator" Version="4.5.0.6" />
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
    <PackageReference Include="Xamarin.Essentials" Version="1.3.1" />
    <PackageReference Include="Xamarin.FFImageLoading" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.1539-pre2" />
    <PackageReference Include="Xamarin.Forms.Maps" Version="4.6.0.1073" />

**Comment by filipoff2** [comment]
iOS:
PackageReference Include="AWSSDK.Core">
Version>3.3.21.20</Version>
PackageReference>
PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
Version>3.0.0</Version>
PackageReference>
PackageReference Include="Com.OneSignal">
Version>3.5.0</Version>
PackageReference>
PackageReference Include="Microsoft.AppCenter">
Version>3.3.0</Version>
PackageReference>
PackageReference Include="Microsoft.AppCenter.Analytics">
Version>3.3.0</Version>
PackageReference>
PackageReference Include="Microsoft.AppCenter.Crashes">
Version>3.3.0</Version>
PackageReference>
PackageReference Include="MvvmLightLibsStd10">
Version>5.4.1.1</Version>
PackageReference>
PackageReference Include="NControl">
Version>0.9.1</Version>
PackageReference>
PackageReference Include="Newtonsoft.Json">
Version>12.0.3</Version>
PackageReference>
PackageReference Include="PCLAppConfig">
Version>1.0.1</Version>
PackageReference>
PackageReference Include="PCLCrypto">
Version>2.0.147</Version>
PackageReference>
PackageReference Include="PCLStorage">
Version>1.0.2</Version>
PackageReference>
PackageReference Include="Plugin.Permissions">
Version>3.0.0.12</Version>
PackageReference>
PackageReference Include="Rg.Plugins.Popup">
Version>1.2.0.223</Version>
PackageReference>
PackageReference Include="SkiaSharp.Svg">
Version>1.60.0</Version>
PackageReference>
PackageReference Include="SkiaSharp.Views.Forms">
Version>1.68.0</Version>
PackageReference>
PackageReference Include="sqlite-net-pcl">
Version>1.6.292</Version>
PackageReference>
PackageReference Include="Xam.Plugin.Connectivity">
Version>3.2.0</Version>
PackageReference>
PackageReference Include="Xam.Plugin.Geolocator">
Version>4.5.0.6</Version>
PackageReference>
PackageReference Include="Xam.Plugins.Forms.ImageCircle">
Version>3.0.0.5</Version>
PackageReference>
PackageReference Include="Xam.Plugins.Settings">
Version>3.1.1</Version>
PackageReference>
PackageReference Include="Xamarin.CardIO.iOS">
Version>5.4.1</Version>
PackageReference>
PackageReference Include="Xamarin.FFImageLoading">
Version>2.4.11.982</Version>
PackageReference>
PackageReference Include="Xamarin.FFImageLoading.Forms">
Version>2.4.11.982</Version>
PackageReference>
PackageReference Include="Xamarin.Forms" Version="4.6.0.1073" />
PackageReference Include="Xamarin.Forms.Maps">
Version>4.6.0.1073</Version>
PackageReference>
PackageReference Include="Xamarin.Google.iOS.Analytics">
Version>3.17.0.3</Version>
PackageReference>
PackageReference Include="Xamarin.Google.iOS.TagManager">
Version>7.1.1.1</Version>
PackageReference>
PackageReference Include="System.Reflection.Emit" Version="4.6.0">
ExcludeAssets>all</ExcludeAssets>
IncludeAssets>none</IncludeAssets>
PackageReference>
PackageReference Include="Xamarin.Swift4">
Version>4.0.0.2</Version>
PackageReference>

**Comment by rachelkang** [comment]
Hi @filipoff2! Have you tried right-clicking on the iOS/Android projects separately > Manage NuGet Packages, and trying to update Xamarin.Forms through there? Also, could you share what your target frameworks are? (Are your Android and XCode versioning up to date?) If you're still seeing issues after this, we'd appreciate if you could share the project or a sample of the project so that we could better assist you. Thank you! :)

**Comment by filipoff2** [comment]
:) Yes I did,  
Android 9 
iOS:
![image](https://user-images.githubusercontent.com/15687714/95949130-52f58180-0df2-11eb-88a5-c01a94c59284.png)

**Comment by filipoff2** [comment]
I assume that one of references holds it to update. Will try to add additional info when possible.

**Comment by StephaneDelcroix** [comment]
XF 5 introduced Rect, you should fully qualify your usages if you both use XF and Graphics.

one nice way to do it is to define this at the top of your c# file

```csharp
using NRect = NGraphics.Rect;
using XFRect = Xamarin.Forms.Rect;
```

and use `NRect` or `XFRect` in your code.

**Comment by filipoff2** [comment]
yes fixed NGraphics.Rect  manually in point 2 as written above.
Despite that it's not updating nuggets.

Ok that is NOT 5.0.0 issue 
Have same issue in on 4.8.

**Comment by filipoff2** [comment]
need to go one by one reference and check what target holds it.

**Comment by filipoff2** [comment]
works fine on Visual studio for Windows
