### ISSUE TITLE
[Bug] Building Release results in lc.exe --gatekeeper gkargs.rsp"' returned exit code 1

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#12488]
Repro:

1) Switch build from debug to release.
2) Build

Result:
lc.exe --gatekeeper @"D:\ZynpoChess\Zynpo Chess\Zynpo Chess.UWP\obj\x86\Release\ilc\intermediate\gkargs.rsp"' returned exit code 1	Zynpo_Chess.UWP			

Using Xamarin version 4.8.0.1451
Visual Studio version 16.7.5

**Comment by rachelkang** [comment]
Hi @snowman745 - thanks for submitting this issue! Unfortunately, I wasn't able to reproduce the error you're seeing. Would you be able to share this project or a sample project so that we can take a closer look and try to better understand what you're experiencing? Thanks :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
