### ISSUE TITLE
[Bug] Blank page before MainPage when wrapping in NavigationPage (Android 10 real device, maybe other as well)

### ISSUE THREAD

**Issue by themronion** [xamarin/Xamarin.Forms#12480]
### Description
 So i've seen that this issue was already somewhere here on the forums but as i can see it is still present and i don't know how to deel with it. My MainPage is a very heavy UI, so i suppose it must load longer than usual pages, but the problem is something else -- a blank page appears at the beginning of loading when wrapping in NavigationPage. The UI isn't being blocked because as u can see the indicator is spining. It is crucial for me to have the MainPage wrapped in the NavigationPage because i need to perform navigation. Attaching 2 videos of what i mean  

### Basic Information

Latest Xamarin.Forms and VS

### Screenshots

![ezgif com-gif-maker](https://user-images.githubusercontent.com/52563426/95961955-73cbd000-0e0e-11eb-8b1f-37da9e9d42b0.gif)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/52563426/95962010-82b28280-0e0e-11eb-98c0-bdf704df05e4.gif)

**Comment by rachelkang** [comment]
Hi, @themronion - thanks for submitting this issue! Could you share this project or a simple project that reproduces the issue, so that we can take a closer look? Also, what is the other issue you mentioned that you believe your current issue resembles?

**Comment by themronion** [comment]
@rachelkang here, i think this is the same issue. As i stated here - https://github.com/xamarin/Xamarin.Forms/issues/11993#issuecomment-726794068 i get a white screen after splash screen and before the main page on android 10 when compiling against android 10 and having a complex ui page. Can u give it a try and let me know? If u will not reproduce i'll make up a sample.

**Comment by themronion** [comment]
On monday i will try to test on an android 10 emulator, to see if it is the problem with the os version

**Comment by Redth** [comment]
@themronion can you attach a repro sample please?

**Comment by themronion** [comment]
@Redth try the one here: https://github.com/xamarin/Xamarin.Forms/issues/11993#issuecomment-726794068 (IMPORTANT - ON ANDROID 10!) . Closing my issue as duplicate
