### ISSUE TITLE
Unable to set ControlTemplate for TemplatedView in Xamarin.Forms version 5.0

### ISSUE THREAD

**Issue by MuneeshKumarG** [xamarin/Xamarin.Forms#12484]
### We are using customized TemplatedView for our customers like ContentView. Until version Xamarin.Forms 4.8.0.1534, it works fine. When we upgrade to 5.0 version, it stopped. 

In platform specific Renderer not working after upgrading 5.0. We have set ControlTemplate in our CustomView constructor. If we remove the constructor, it works fine.  

If we set ControlTemplate, native renderer OnElementChanged not working. 
It works until 4.8.0.1534.

Please check the below code and update me the solution for this. 

MainPage.xaml

```XAML
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Sample"
                x:Class="Sample.MainPage" >
    <ContentPage.Content>
        <StackLayout Margin="5">
            <Entry/>
            <local:CustomView/>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

MainPage.xaml.cs

```C# 
public class CustomView : TemplatedView
    {
        public CustomView()
        {
            this.ControlTemplate = new ControlTemplate(typeof(Grid));
        }
    }
```

Android project -> Renderer.cs

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Sample;
using Sample.Droid;
using Xamarin.Forms.Platform.Android;
using Forms = Xamarin.Forms;

[assembly: Forms.ExportRenderer(typeof(CustomView), typeof(CustomViewRenderer))]
namespace Sample.Droid
{
    public class CustomViewRenderer : ViewRenderer<CustomView, View>
    {

        public CustomViewRenderer(global::Android.Content.Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<CustomView> e)
        {
            base.OnElementChanged(e);
        }

    }
}
```

**Comment by rachelkang** [comment]
Hi, @MuneeshKumarG - thanks for submitting this issue! Hmm I wasn't able to reproduce the issue you're describing - could you attach a sample project that reproduces the bug and uses `OnElementChanged` as you wish so that we can take a closer look? Thanks :)

**Comment by MuneeshKumarG** [comment]
Please find the sample below. 

[XF5Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/5391127/XF5Sample.zip)

In 5.0 Xamarin.Forms version OnElementChanged not called, please check.

**Comment by HemalathaMarikuma-syncfusion** [comment]
any progress on this?

**Comment by jeyakasipandi** [comment]
Any update on this?

**Comment by tranb3r** [comment]
Is it fixed in 5.0.0 Pre Release 5 ?

**Comment by bmacombe** [comment]
Glad to see this is a blocker, it causes issues with SyncFusions SFTextInputLayout tested last on pre 5

**Comment by MuneeshKumarG** [comment]
I have checked this problem in Xamarin.Forms version 5.0.0.1829-pre6. But still issue occurring. OnElementChanged have not called. Please check with already attached sample with XF new version.

**Comment by MuneeshKumarG** [comment]
Any update on this?

**Comment by MaximMikhisor** [comment]
SyncFusions SFTextInputLayout does not work also with Xamarin.Forms version 5.0.0.1829-pre6

**Comment by MuneeshKumarG** [comment]
@MaximMikhisor : SfTextInputLayout used TemplatedView. This forum raised for the TemplatedView problem in 5.0. Now the problem resolved in Xamarin.Forms 5.0.0.1874. Now SfTextInputLayout also working fine with this Xamarin.Forms 5.0.0.1874 version.
