### ISSUE TITLE
[Enhancement] Add DragStateChanged event to ItemsViewCell on iOS

### ISSUE THREAD

**Issue by denzerd** [xamarin/Xamarin.Forms#12496]
## Summary
We are trying to implement our own DragAndDrop CollectionView and hit a dead end when trying to implement a custom preview view.
We want the long pressed view to already change to a red border and the preview view to have the same border then as well. The problem is that the actual Drag is only recognised in iOS when it is, well dragged, but in order to do what we want we would need the information when the cell was lifted. The actual problem is to know if the cell was dropped without even moving it, because then we need to change the cells appearance back to its original but the PerformDrop is not fired. All of it is complicated and I can't get it together to explain it well in my head :D
The lifted or none state information comes from the UICollectionViewCell DragStateDidChange method but we can not subclass the UICollectionViewCell class and we rely on the cell provided by Xamarin Forms.

All problems could be solved if we would have the possibility to listen to an event that is fired when the cells Drag State changed.

## API Changes
The ItemsViewCell needs to hold an event to register to that notifies about dragStateChanged events.
The event needs EventArgs that pass the dragState:

```
public class DragStateChangedEventArgs : EventArgs
        {
            public UICollectionViewCellDragState state { get; set; }

            public DragStateChangedEventArgs(UICollectionViewCellDragState state)
            {
                this.state = state;
            }
        }
```

In the ItemsViewCell the event has to be declared, the DragStateDidChange needs to be overridden and the event fired when the method is called.

`public event Action<DragStateChangedEventArgs> DragStateChangedEvent;` 

```
public override void DragStateDidChange(UICollectionViewCellDragState dragState)
 {
                base.DragStateDidChange(dragState);
                DragStateChangedEventArgs args = new DragStateChangedEventArgs(dragState);
                DragStateChangedEvent?.Invoke(args);
}
```

## Intended Use Case
To be able to be notified about drag state changes.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
