### ISSUE TITLE
[Bug] Xamarin.Forms 5 - MasterDetailPage 'Split' behaviour not working anymore on iPad

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#12490]
### Description
I installed Xamari.Forms 5 pre1 (and then pre 2, pre 3) and my MasterDetailsPage which has a MasterBehaviour of 'Split' has stopped working on iPad in portrait mode. The left pane acts like a Popover behaviour in portrait mode, and I can slide it left and right over the Detail content, whereas I want it to be in "Split" mode as I have set it. I tried "SplitOnPortrait" and it also doesn't work (i.e. I can still slide the menu in and out)

It looks like the same issue was introduced in XF 4.2 before being fixed in 4.3, issue [#7710](https://github.com/xamarin/Xamarin.Forms/issues/7710)

(I know MasterDetailsPage has been renamed to FlyoutPage in XF 5 which I tried but this causes a new issue for me which is out of scope of this question where now only the Flyout Page is shown. This may be because I am using Prism to programmatically set the detail page by navigating to it.)

### Repo project

You can download a repo project [HERE](https://drive.google.com/file/d/1zlhVDnW5nB5g5qmanzau09Oer5LTCSe9/view?usp=sharing), but there's honestly nothing to it, it's a MasterDetailPage template app with the behaviour set to "Split" and XF 5 installed.

### Basic Information

- Version with issue: 5.0 pre1, pre2, pre3
- Last known good version: 4.7
- IDE: VS2019 Mac
-  iOS 13.4

**Comment by rachelkang** [comment]
Hi, @HelenMamalaki - thank you for submitting this issue! Would you be able to share your project or a sample project that reproduces the bug so that we can better understand what's happening? If possible, a screen recording demonstrating the buggy behavior on your iPad, would also be helpful. Thanks! :)

**Comment by HelenMamalaki** [comment]
Hi, @rachelkang thank for your comment, I have edited my question additional details: 
1. Added a repo project
2. Problem is only in portrait mode
3. Tried XF5 pre 3 too.

Is there maybe a work around I can use in the mean time? Thanks!

**Comment by HelenMamalaki** [comment]
This is also a problem in portrait mode for UWP. :(

**Comment by HelenMamalaki** [comment]
Thank you for resolving so quickly! I installed the 2 latest nightly build v5.0.1.1668-nightly and one before it is still the problem in it. The Android SwitchRenderer seems to have gone missing too. Am I missing something?

**Comment by PureWeen** [comment]
@HelenMamalaki do you mean RadioButtonRenderer?

The nightly generates from the main branch which wasn't merged up yet. Test again with the nightly that's generated later today and let me know if that has issues
