### ISSUE TITLE
[Enhancement] IndicatorSelectedCommand for IndicatorView

### ISSUE THREAD

**Issue by AlexanderMelchers** [xamarin/Xamarin.Forms#12493]
## Summary
Add an `IndicatorSelectedCommand` to the `IndicatorView` to fire when the user taps an indicator in the view and pass the index/position of the tapped indicator into a `Command`/`Command<int>`.

## API Changes

1. Add a new bindable property that allows binding a command.
2. Detect taps on individual indicators (e.g. `TapGestureRecognizer`s attached to each of the indicators).
3. Fire the bound command with the appropriate indicator's position when a user taps on it.

```
<IndicatorView IndicatorShape="Circle"
                        IndicatorSelectedCommand="{Binding IndicatorSelected}"
                        [...] />
```

## Intended Use Case
I recently changed a part of our app that was using a `CarouselViewControl` and custom page-indicator control for the Forms `CarouselView` and `IndicatorView` combination. And while most of the APIs involved were a one-on-one match (if not a one-to-one mapping), one feature is missing from the `IndicatorView` that I had implemented on my custom page-indicator control: the ability to tap an indicator and fire a `Command` in response. I used this command to switch the slide shown in the `CarouselView`, providing users with shortcuts to move through the latter's pages. As such, responding to a user's swipe might be equally useful.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
