### ISSUE TITLE
[Bug] WebView on UWP ignores TabIndex property

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#12494]
WebView is not respecting TabIndex property on UWP. 

Using the code below, push an instance of TestWebViewTabIndexPageView onto the NavigationStack.
Based on the code, one would expect the tab sequence to be Button, WebView, Button, but instead it is Button, Button, WebView (after which it's unclear where it goes for the next three tabs - an issue first raised in the days of Bugzilla but still not addressed).

Basically, any page that contains a WebView is likely to have unexpected behavior when users attempt to interact via the keyboard or some forms of assistive technology.

using Xamarin.Forms;

using System.Threading.Tasks;

namespace ViewsUsingXamarinForms
{
    public class TestWebViewTabIndexPageView : ContentPage
    {
        private bool _firstTimeOnAppearing = true;

        public TestWebViewTabIndexPageView()
        {
            PopulatePage();
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            if (_firstTimeOnAppearing)
            {
                _firstTimeOnAppearing = false;

                //PopulatePage();

                // The following is just here as a convenience.
                // It's a nasty, hacky way of setting the initial focus, 
                // that introduces a race condition. Good enough for
                // this repro sample though.
                Task.Run(async () =>
                {
                    await Task.Delay(1000);
                    Xamarin.Essentials.MainThread.BeginInvokeOnMainThread(() =>
                    {
                        if (_button1 != null)
                            _button1.Focus();
                    });
                });
            }
        }

        private Button _button1;
        private Button _button2;
        private WebView _webView;

        private void PopulatePage()
        {
            _button1 = new Button
            {
                Text = "Button 1 (TabIndex = 1)",
                TextColor = Color.Black,
                BackgroundColor = Color.White,
                TabIndex = 1,
                VerticalOptions = LayoutOptions.Start
            };

            _webView = new WebView
            {
                BackgroundColor = Color.White,
                HorizontalOptions = LayoutOptions.Fill,
                TabIndex = 2,
                VerticalOptions = LayoutOptions.FillAndExpand,
                Source = new HtmlWebViewSource
                {
                    Html = "<html><body>Hello (TabIndex=2)<br>1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19<br>20<br>21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29</body></html>"
                }
            };

            _button2 = new Button
            {
                Text = "Button 2 (TabIndex=3)",
                TextColor = Color.Black,
                BackgroundColor = Color.White,
                TabIndex = 3,
                VerticalOptions = LayoutOptions.End
            };

            Content = new StackLayout
            {
                HorizontalOptions = LayoutOptions.Fill,
                VerticalOptions = LayoutOptions.Fill,
                BackgroundColor = Color.Pink,
                Children =
                {
                    _button1,
                    _webView,
                    _button2
                }
            };
        }
    }
}

### Basic Information

- Version with issue: 4.8

**Comment by johnshardman** [comment]
I've just seen the UWP documentation at https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/web-view

It says 
"Although WebView is not a Control subclass, it will receive keyboard input focus and participate in the tab sequence. It provides a Focus method, and GotFocus and LostFocus events, but it has no tab-related properties. Its position in the tab sequence is the same as its position in the XAML document order".

Unfortunately, it seems that there is nothing to be done in Xamarin.Forms to solve this. It relies on the developer building things in the desired tab order in the XAML (or presumably C#). That's a nuisance for those of us who build parts of a page and then embed into an additional Layout before populating the Content of a ContentPage.

Suggest this issue be closed (although if anybody knows how to raise one against UWP itself, that would be handy). I wonder if WinUI will solve this...

**Comment by rachelkang** [comment]
@johnshardman this definitely sounds frustrating! I suggest you submit your feedback on this site https://developercommunity.visualstudio.com/spaces/8/index.html and it should then get routed to the appropriate team :)
