### ISSUE TITLE
[Enhancement] Upgrade for Xamarin.Forms maps

### ISSUE THREAD

**Issue by LamijaV** [xamarin/Xamarin.Forms#12504]
Hi, I see that the latest version of Xamarin.Forms maps is still dependent of Xamarin.Android.Support.v4. When can we expect the upgrade for AndroidX (without support libraries)? 

Additional: This is causing androidX issue when combined with one of our native libraries that is using AndroidX.
Thanks!
![image](https://user-images.githubusercontent.com/50732501/96226478-fc737900-0f92-11eb-9e59-fcae9770c474.png)

**Comment by mattleibow** [comment]
This is very weird.

According to the logic, I am splitting on `$`... And it _has_ to exist because I do a `Contains($)` before I do the split: https://github.com/xamarin/AndroidX/blob/master/source/migration/Migration/CecilMigrator.cs#L471-L472

Is it possible to attach a binlog so I can have a closer look? Or even a diagnostic log?

**Comment by rachelkang** [comment]
^ also check your target framework and make sure you're running on Android API 28/29!

and @LamijaV to address your first point, we have a PR open for that (#10873) so you should see an upgrade soon enough :)

**Comment by LamijaV** [comment]
Hi Matt,

Here is the diagnostic output. More info on the project:
XF 4.7.0.1179
compiling and target Android 10.0 (Q)
Xamarin.AndroidX.Migration 10.0.6.1 (tried 1.0.7.1 as well)
native lib for contactless payment (containing visa and mastercard sdks) targeting android 10 and AndroidX

When I include maps I get this exception, when I remove it project build with no errors. When I build the project without this native lib but with maps it builds ok. 

I had same issue with some other packages. I have not been able to detect exact cause but when upgrading them to newer versions that support AndroidX fully error disappears, and that is why I'm hoping upgrade of XF Maps will to :)


Please let me know if I can help you with more info.

[diagnostics.txt](https://github.com/xamarin/Xamarin.Forms/files/5401239/diagnostics.txt)

**Comment by LamijaV** [comment]
> ^ also check your target framework and make sure you're running on Android API 28/29!
> 
> and @LamijaV to address your first point, we have a PR open for that (#10873) so you should see an upgrade soon enough :)

Thanks! Looking forward to it.

**Comment by rmarinho** [comment]
We have a PR for this : https://github.com/xamarin/Xamarin.Forms/pull/12520

**Comment by rmarinho** [comment]
Actually maps were already updated and merged on #10873
