### ISSUE TITLE
[Enhancement] Disable animation when changing X1, X2, Y1 or Y2 of a Line shape.

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#12508]
## Summary
When using a `Line` shape, and changing the values of `X1`, `X2`, `Y1` or `Y2` at runtime (through binding) triggers an animation that moves the line to the new position.

I don't want this animation. This animation triggered even if the Line has `IsVisible="false"`.

## API Changes

Either disable animation when IsVisible = false, or add a new property to disable the animation.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
