### ISSUE TITLE
[Bug] Shell Bottom Tabs are not visible in iOS when we route back from non tabs page to tabs page

### ISSUE THREAD

**Issue by Srikanth540-L** [xamarin/Xamarin.Forms#12505]
[Bug] Shell Bottom Tabs are not visible in iOS when we route back from on tabs page to tabs page
### Description
**NOTE:** I would also like to bring one  issue that happening in **iOS** when we are navigating between pages which have bottom tab and that don't , For example in the below mentioned sample click on monkey tab and select any monkey in the list and once we are monkey detail page click on  monkey details we will navigate to subpage then click on go back button , you will notice that bottom tabs are invisible for the monkey detail page even though  TabBarIsVisible is set ti true , This happens one when you Shell.Current.Navigation.PopAsync(false) for  Shell.Current.Navigation.PopAsync(true) the tabs are visible after some delay.

### Steps to Reproduce

1. [Xamarin_Forms___Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/5389916/Xamarin_Forms___Xaminals.zip)
2.  Download the above sample
3. Click on Monkey tab and then click any monkey in the list then we will route to Monkey details
4 Once on the Monkey Detail Click on the page then we will navigate to Subpage there click on Go Back
5 You will be back on Monkey Detail  page with out tabs even though  TabBarIsVisible is set to true 

### Expected Behavior
Should show tabs if TabBarIsVisible is set to true
### Actual Behavior
Bottom tabs are not visible
### Basic Information

- Version with issue: Xamarin forms 4.8 Latest
- Affected Devices: iOS devices 

### Screenshots

<img width="359" alt="Screenshot 2020-10-16 at 1 06 44 PM" src="https://user-images.githubusercontent.com/59356252/96226856-deb50c80-0fb0-11eb-915b-67b843b5b14d.png">
<img width="337" alt="Screenshot 2020-10-16 at 1 07 04 PM" src="https://user-images.githubusercontent.com/59356252/96226869-e379c080-0fb0-11eb-9fd6-815db6d58eb0.png">
<img width="338" alt="Screenshot 2020-10-16 at 1 07 20 PM" src="https://user-images.githubusercontent.com/59356252/96226874-e4aaed80-0fb0-11eb-8816-5c70df76b388.png">
<img width="341" alt="Screenshot 2020-10-16 at 1 07 35 PM" src="https://user-images.githubusercontent.com/59356252/96226877-e5438400-0fb0-11eb-8bba-e9e90d782b84.png">

### Reproduction Link
 [Xamarin_Forms___Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/5389916/Xamarin_Forms___Xaminals.zip)

**Comment by rachelkang** [comment]
Hi, @Srikanth540-L - thank you so much for submitting this issue! We'll work to fix this :) 

In the meantime, a temporary workaround would be to reenable the popasync animation. So in your SubPage code-behind, if you remove the bool so that you have `await Shell.Current.Navigation.PopAsync();` instead of `await Shell.Current.Navigation.PopAsync(false);`, you should see the Bottom Tabs again. Hope this will work well for the time being!

**Comment by PureWeen** [comment]
This should be fix by the following PR

https://github.com/xamarin/Xamarin.Forms/pull/12320

**Comment by Srikanth540-L** [comment]
Hi @rachelkang , await Shell.Current.Navigation.PopAsync(); will solve the issue but there is delay when the tabs are back to visible but same is not happening when you use the back button in navigation bar which is inbuilt in the xamarin forms
