### ISSUE TITLE
[Bug] Error Certification Kit HighVersionLie

### ISSUE THREAD

**Issue by RobertoGFilho** [xamarin/Xamarin.Forms#12510]
I'm not able to publish UWP app, because show up a erro on kit certification "task failure on active HighVersionLie". I created a new empty APP on xamarin forms then it's happen again.
Visual Studio 16.7.6
Xamarin Forms 4.8.0.1560

**Comment by RobertoGFilho** [comment]
Hi !

follow this steps:


  1.  Create a new Xamarin Forms for iOS, Android and UWP;
  2.  Build your app;
  3.  Click right mouse button on UWP poject;
  4.  Select Publish | Associate you app on store;
  5.  Click Publish | Create AppPackage;
  6.  After your package has created you will run Windows App Certification kit;
  7.  See report;
  8.  Result : App not approved, message : task failure HighVersionLie;

The report is attached in português language;
Best regards
Roberto

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Rachel Kang<mailto:notifications@github.com>
Enviado:sexta-feira, 16 de outubro de 2020 18:09
Para: xamarin/Xamarin.Forms<mailto:Xamarin.Forms@noreply.github.com>
Cc:Roberto Filho<mailto:robertofilho@outlook.com.br>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Error Certification Kit HighVersionLie (#12510)


Hi, @RobertoGFilho<https://github.com/RobertoGFilho> - thanks for submitting this issue. Would you be able to share some more details? What are the exact steps you're taking, and how might we be able to see what you're seeing?

In the meantime, here<https://forums.xamarin.com/discussion/151880/uwp-blank-app-failing-windows-app-certification-kit-highversionlie-test> is also a related conversation from our forums which you may find helpful. Looking forward to hearing more about this issue! :)

**Comment by melicaster** [comment]
I reported the issue at Visual Studio, https://developercommunity.visualstudio.com/content/problem/1224180/failed-wack-on-xamarin-uwp.html. Someone will pick up on it soon.

**Comment by RobertoGFilho** [comment]
I’ve already too!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: melicaster<mailto:notifications@github.com>
Enviado:domingo, 18 de outubro de 2020 00:25
Para: xamarin/Xamarin.Forms<mailto:Xamarin.Forms@noreply.github.com>
Cc:Roberto Filho<mailto:robertofilho@outlook.com.br>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [xamarin/Xamarin.Forms] [Bug] Error Certification Kit HighVersionLie (#12510)

**Comment by mattleibow** [comment]
Something is happening here... I created a blank UWP app - no dependencies/libraries and it also fails with this error.

I'm going to update everything here and see. Maybe it is my IDE, the SDK, something. But, this happens in apps without Xamarin.Forms.

**Comment by hartez** [comment]
This isn't the first time we've seen some weirdness from this test: https://forums.xamarin.com/discussion/151880/uwp-blank-app-failing-windows-app-certification-kit-highversionlie-test

**Comment by mattleibow** [comment]
Just did a few tests and I think it is the WACK test.

I updated to the latest IDE: VS 2019 v16.7.6
I am using the kit: 10.0.19041.1
I tried both x86 and x64
This is a fresh/clean File | New | UWP App

All fails.

What one can do is submit the app to the store and see if it fails there.

**Comment by exotexot** [comment]
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 9.30 GB / 15.97 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.7.30611.23 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
    react-native-windows: ^0.62.14 => 0.62.14
  npmGlobalPackages:
    *react-native*: Not Found

building a uwp app using react-native-windows and also having the exact same issue. this may not be necessarily be realted to xamarin.forms directly.

**Comment by mattleibow** [comment]
Looks like this might be an issue with something else, the React Native team also has it. And I was able to repro with a plain, empty UWP template

https://github.com/microsoft/react-native-windows/issues/6331#issuecomment-718357629

**Comment by Javier118** [comment]
I also have that problem to build the application using WTS for the store version of Visual Studio 16.8.4 .

**Comment by Javier118** [comment]
for my part it's resolved I've updated the sdk

**Comment by mattleibow** [comment]
Closing this issue as it was just the locally installed WACK test that was failing and has also been fixed in the updates.

**Comment by chrisgull** [comment]
This is still happening. VS 2019 16.9.6.
