### ISSUE TITLE
[Bug] Application.RequestedThemeChanged raised twice on iOS when switching to home screen and back

### ISSUE THREAD

**Issue by Eilon** [xamarin/Xamarin.Forms#12512]
### Steps to Reproduce

1. Create a Xamarin.Forms app that listens to the `Application.RequestedThemeChanged` event and set a breakpoint on the event handler (or log it somewhere)
2. Launch app on iOS Simulator
3. App will launch, life is good
4. Switch away from app back to the device home screen and then switch back to your app

### Expected Behavior

No ThemeChanged event should fire at all (because it didn't change!).

### Actual Behavior

The ThemeChanged event fires twice: once to the theme that it _isn't_ and then once back to the actual current theme.

### Basic Information

- Version with issue: `<PackageReference Include="Xamarin.Forms" Version="4.8.0.1451" />`
- Last known good version: Don't know
- Affected Devices: iOS

### Screenshots

Watch video here:
[XamarinDoubleThemeChangeVideo.zip](https://github.com/xamarin/Xamarin.Forms/files/5394542/XamarinDoubleThemeChangeVideo.zip)

### Reproduction Link

Clone repo: https://github.com/Eilon/XamarinThemeChange

### Workaround

No workaround needed per se because you ultimately get the right theme. But my app does extra work because of the double theme change.

**Comment by StephaneDelcroix** [comment]
mmm, I recall we had to add some caching for iOS to prevent that double fire (TriggerThemeChangedActual), but it might be broken...

**Comment by Eilon** [comment]
This was all on the iOS 14 Simulator.
