### ISSUE TITLE
[Bug] ViewRenderer is disposed but still in memory

### ISSUE THREAD

**Issue by llzz19851985** [xamarin/Xamarin.Forms#12517]
### Description
when a view dispose,i found its ViewRenderer still in memory

### Steps to Reproduce

1. A page to B page,B page load a custom ExtensionTabView,its ViewRenderer named AndroidTabViewRender,then exit B page
2. use android studio profiler dump memory information
3. found ExtensionTabView is not in memory,but its ViewRenderer still in memory

![image](https://user-images.githubusercontent.com/1481403/96398658-eff35880-11fe-11eb-9c36-c31c411933e6.png)

![image](https://user-images.githubusercontent.com/1481403/96398496-9a1eb080-11fe-11eb-8efc-e81bee275564.png)

![image](https://user-images.githubusercontent.com/1481403/96398724-1dd89d00-11ff-11eb-8fb0-80d6376b5c80.png)

![image](https://user-images.githubusercontent.com/1481403/96398768-3d6fc580-11ff-11eb-9604-eb720d9d1428.png)

### Expected Behavior
ViewRenderer  not in memory 
### Actual Behavior
ViewRenderer  still in memory 
### Basic Information

- Version with issue:xamarin forms 4.2.0.778463

**Comment by PureWeen** [comment]
Can you try a more recent version of Forms? 

Are you calling GC.Collect/GC.WaitForPendingFinalizers before taking measurements to make sure the GC has ran?

**Comment by llzz19851985** [comment]
@PureWeen yes,I have force GC before dump

**Comment by llzz19851985** [comment]
@PureWeen now I Found not custom view render not remove from memory after page remove from page navigation,all render is always in memory although page removed !

**Comment by jsuarezruiz** [comment]
@llzz19851985 Could you attach a sample where do some tests and reproduce the issue?.

**Comment by llzz19851985** [comment]
@jsuarezruiz any sample you can reproduce the problem,for example pagerender,any demo with page navigation you can find the pagerender not removed when page is detory

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by llzz19851985** [comment]
Closed?!!!,Why?why need support sample?every element in collectionview item not dispose although collectionview dispose

**Comment by llzz19851985** [comment]
@Redth
