### ISSUE TITLE
[Enhancement] Sweep Gradient Brush

### ISSUE THREAD

**Issue by vanka78bg** [xamarin/Xamarin.Forms#12522]
The new `LinearGradientBrush` and `RadialGradientBrush` are a really good addition to the framework. There is another commonly used gradient brush that is currently missing however - the `SweepGradientBrush`. Similar to the `RadialGradientBrush`, the `SweepGradientBrush` draws the gradient in a circle, but sweeps the colors from 0 to 360 degrees, as shown here:

![Sweep-Gradient](https://user-images.githubusercontent.com/1614598/96453371-0ad7c400-1223-11eb-971a-5e756510f2e5.png)

One common usage of this brush is to draw a radial gauge, as illustrated below:

![Radial-Gauge](https://user-images.githubusercontent.com/1614598/96453500-3bb7f900-1223-11eb-9186-30d955d67e9f.jpg)

It is currently possible to achieve this with SkiaSharp, however the library is a too heavyweight dependency for mobile apps. The new components for drawing paths and brushes can relieve us from the need to include Skia with our apps in such simple scenarios.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
