### ISSUE TITLE
While using DatePicker Accessibility (VoiceOver), VoiceOver reads count of month as 31 and count of Days as 12. It supposed to be vice versa[Bug] 

### ISSUE THREAD

**Issue by HirakCTS** [xamarin/Xamarin.Forms#12523]

**Comment by rachelkang** [comment]
Hi, @HirakCTS - thanks for submitting this issue!
Would you be able to share the version of XF you're using? I tested on XF 4.8, and assuming you're referring to the count where the DatePicker reads off the date (i.e. Month 11 of 12), wasn't able to reproduce this bug. Please let me know if I'm misunderstanding the issue. But if I'm understanding correctly and if you happen to have the same configuration, would you be able to share a repro as well? Thanks :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
