### ISSUE TITLE
[Question] Bindable StackLayout vs CollectionView

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12530]
Hi. This is a question and not a bug report.

If you have lots of elements in a collection, let’s say chat messages, which is a more performant option: using a CollectionView, or wrapping a bindable StackLayout in a ScrollView?

I am not using CollectionView in my project atm at all because it is still too buggy.

Would a CollectionView with recycled elements be a better option? If so, do the elements get reused if the entire collection changes, or only when smaller edits happen (add, remove etc.)?
Or is a bindable StackLayout an equivalent option here?

The documentation doesn’t mention any of these so I have to ask here.

Thank you for insights!

**Comment by StephaneDelcroix** [comment]
Bindable StackLayout is ok if the number of items is low. Otherwise you wont hit some performance issue soon

**Comment by Tommigun1980** [comment]
> Bindable StackLayout is ok if the number of items is low. Otherwise you wont hit some performance issue soon

@StephaneDelcroix Thank you for the information, I appreciate it! Maybe the bindable layout docs would benefit of the additional information you just shared as there may be other people who need this information also? Just a thought!

I tried my hardest to start using the collection view but these issues are preventing me from transitioning to it: https://github.com/xamarin/Xamarin.Forms/issues/12554, https://github.com/xamarin/Xamarin.Forms/issues/12555, https://github.com/xamarin/Xamarin.Forms/issues/12576. The issues are just too large to use it for me atm, and I'm very concerned about performance especially in my chat view as I'm forced to use bindable layouts until those are fixed, so I'm in a bit of a pinch here. What would you advice -- do you think those fixes will its way into a release any time soon? And if not what would you advice to do in the interim?

Thank you again for insights!!

**Comment by Tommigun1980** [comment]
> Bindable StackLayout is ok if the number of items is low. Otherwise you wont hit some performance issue soon

@StephaneDelcroix Thank you for the information, I appreciate it! Maybe the bindable layout docs would benefit of the additional information you just shared as there may be other people who need this information also? Just a thought!

I tried my hardest to start using the collection view but these issues are preventing me from transitioning to it: #12554, #12555, #12576. The issues are just too large for me to use it atm, and I'm very concerned about performance especially in my chat view as I'm forced to use bindable layouts until those are fixed, so I'm in a bit of a pinch here. What would you advice -- do you think those fixes will its way into a release any time soon? And if not what would you advice to do in the interim?

Thank you again for insights!!
