### ISSUE TITLE
[Bug] Shapes do not work with StaticResource Fill Colour

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#12538]
### Description

As soon as you set Fill to a StaticResource then the shape disappears. Only tested on UWP so far..

**This line works**

`<Ellipse Fill="Blue" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" />`

**This line doesnt**

`<Ellipse Fill="{StaticResource CompleteColour}" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" >`

XF 4.8.0.1560 - latest release

**Comment by jsuarezruiz** [comment]
@JKennedy24  Could you share the `CompleteColour` definition? Is it a SolidColorBrush?

**Comment by JKennedy24** [comment]
Sure, my resource is:

`<Color x:Key="CompleteColour">#27ae61</Color>`

I had to check this bug 3-4 times before filing it, because I just couldnt work out why setting it to a staticresource would affect the drawing of a control, still can't figure out what potentially is going on here

**Comment by jsuarezruiz** [comment]
I think I know what happens. The type expected by the Fill and Stroke properties is a Brush, not a Color.
Directly assigning a hexadecimal color value works because internally we are using a TypeConverter, but otherwise:

`SetValue: Cannot convert [Color: A=1, R=0.152941182255745, G=0.682352960109711, B=0.380392163991928, Hue=0.404938250780106, Saturation=0.633802831172943, Luminosity=0.417647063732147] to type 'Xamarin.Forms.Brush'`

Tested using a SolidColorBrush and works.

**Comment by JKennedy24** [comment]
so... This is a bug in Xamarin.forms right?

This sounds like the confusion between brush and colours is going to be a nightmare! Is there any way of Xamarin identifying that a colour has been fed in and converting it to a brush, or do I need to store all my colour schemes as both brushes and colours and swap them in where necessary? or do I implement my own type converter and use that?

I don't really understand what (me) the developer is supposed to do here?

**Comment by JKennedy24** [comment]
Extra Info: I just tried:
**Resources**
`            <SolidColorBrush x:Key="CompleteColourSBC">#27ae61</SolidColorBrush>`
**XAML**
`<Ellipse Fill="{StaticResource CompleteColourSBC}" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" >`

But that didnt work,

The only thing that actually worked was:
`<Ellipse Fill="#27ae61" StrokeThickness="0" WidthRequest="10" HeightRequest="10" HorizontalOptions="End" VerticalOptions="End" Margin="0,0,2,2" >`

Hope that helps

**Comment by JKennedy24** [comment]
Any update on this? its a real blocker for me using shapes in my application

**Comment by JKennedy24** [comment]
Workaround for anyone looking to workaround this:
Unfortunately shapes are sealed classes at the moment (and rightly so as they are in preview) so can't be overridden to implement the colours.

But you can use attached behaviours.. here are my attached behaviours to work around this issue:

ShapeColourBehaviour.cs
```
    public class ShapeColourBehaviour
    {
        public static readonly BindableProperty ShapeColourProperty =
            BindableProperty.CreateAttached("ShapeColour", typeof(Color), typeof(ShapeColourBehaviour), Color.Transparent, propertyChanged: OnAttachBehaviorChanged);


        public static Color GetShapeColour(BindableObject view)
        {
            return (Color)view.GetValue(ShapeColourProperty);
        }

        public static void SetShapeColour(BindableObject view, bool value)
        {
            view.SetValue(ShapeColourProperty, value);
        }

        static void OnAttachBehaviorChanged(BindableObject view, object oldValue, object newValue)
        {
            var element = view as Xamarin.Forms.Shapes.Shape;
            if (element == null)
            {
                return;
            }

            var color = (Color)newValue;
            element.Fill = new SolidColorBrush(color);
        }
    }
```

StrokeColourBehaviour.cs
```
 public class StrokeColourBehaviour
    {
        public static readonly BindableProperty StrokeColourProperty =
            BindableProperty.CreateAttached("StrokeColour", typeof(Color), typeof(StrokeColourBehaviour), Color.Transparent, propertyChanged: OnAttachBehaviorChanged);


        public static Color GetStrokeColour(BindableObject view)
        {
            return (Color)view.GetValue(StrokeColourProperty);
        }

        public static void SetStrokeColour(BindableObject view, bool value)
        {
            view.SetValue(StrokeColourProperty, value);
        }

        static void OnAttachBehaviorChanged(BindableObject view, object oldValue, object newValue)
        {
            var element = view as Xamarin.Forms.Shapes.Shape;
            if (element == null)
            {
                return;
            }

            var color = (Color)newValue;
            element.Stroke = new SolidColorBrush(color);
        }
    }
```


**Usage**
` <Ellipse behaviour:ShapeColourBehaviour.ShapeColour="{StaticResource CompleteColour}" behaviour:StrokeColourBehaviour.StrokeColour="{StaticResource CompleteColour}" Margin="{styling:Thickness 5, Phone=4}" Grid.Column="0" IsVisible="{Binding IsSelected}" InputTransparent="True"/>`

**Comment by Nk54** [comment]
I was loosing hairs trying to find why StaticResource for color doesn't work.
But it works with solidColorBrush resources. I thought it would be converted.

@JKennedy24 you set your resources wrong :
<SolidColorBrush x:Key="CompleteColourSBC">#27ae61</SolidColorBrush>

try this instead
<SolidColorBrush x:Key="CompleteColourSBC" Color="#27ae61" />

**Comment by marcoablanco** [comment]
> I was loosing hairs trying to find why StaticResource for Color doesn't work.
> But it works with SolidColorBrush resources. I thought the Color would be converted.
> 
> @JKennedy24 you set your resources wrong :
> `<SolidColorBrush x:Key="CompleteColourSBC">#27ae61</SolidColorBrush> `
> try this instead
> `<SolidColorBrush x:Key="CompleteColourSBC" Color="#27ae61" />`

That works!!
And you can use a static reference to your color:
`<SolidColorBrush x:Key="MySolidColorBrush" Color="{StaticResource MyColor}" />`

**Comment by mrengineer7777** [comment]
> 
> 
> I was loosing hairs trying to find why StaticResource for Color doesn't work.
> But it works with SolidColorBrush resources. I thought the Color would be converted.
> 
> @JKennedy24 you set your resources wrong :
> `<SolidColorBrush x:Key="CompleteColourSBC">#27ae61</SolidColorBrush> `
> try this instead
> `<SolidColorBrush x:Key="CompleteColourSBC" Color="#27ae61" />`

This is exactly what I needed.  I was also trying to use an ellipse with a SolidColorBrush StaticResource.  Thanks!
