### ISSUE TITLE
[Bug] ListView Click causes NRE

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#12533]
### Steps to Reproduce

1. Run Gallery WPF. 
2. Search "list". 
3. Select GroupedList Gallery - Legacy. Click on white space (do not click on row)

### Expected Behavior

No NRE

### Actual Behavior
NRE

### Basic Information

- Version with issue: the latest nightly build

**Comment by rmarinho** [comment]
fixed by #12472)
