### ISSUE TITLE
[Bug] OnChildRemoved(Element child) not working on Xamarin.Forms 4.8 version

### ISSUE THREAD

**Issue by MuneeshKumarG** [xamarin/Xamarin.Forms#12539]
I have created custom layout inherited from Layout. 

Still, I have used OnChildRemoved(Element child) for identifying the child removal process. 

After changing Xamarin.Forms 4.8 version, OnChildRemoved(Element child) not working, I have changed this method to OnChildRemoved(Element child, int oldLogicalIndex). Now I can get the notification in index added method. 

But when I change the Xamarin.Forms 4.7 version, it shows exception for OnChildRemoved(Element child, int oldLogicalIndex) unavailability. 

How to resolve this?

I want to use Xamarin.Forms 4.5 and 4.8 both version.

**Comment by StephaneDelcroix** [comment]
If you want to use both 4.8 and earlier version, use the Obsolete method (and suppress the warning), of #ifdef your code depending on the version you run on

**Comment by MuneeshKumarG** [comment]
Hi StephaneDelcroix,

Thanks for your update. 

How to check the version number using #ifdef

please update me example.

**Comment by MuneeshKumarG** [comment]
Can you update me the example code for this?
