### ISSUE TITLE
Xamarin.Forms (4.8.0.1451) not working right on macOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12549]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/XamarinForms-4801451-not-working-r/1211693)._

---
Xamarin.Forms (4.8.0.1451) is not working right on macOS.

I have attached two pictures (in “right_wrongLook.zip”)

“righLook_Xamarin.Forms (4.7.0.1260).png” shows how the window should look

“wrongLook_Xamarin.Forms (4.8.0.1451).png” shows how it looks with Xamarin.Forms (4.8.0.1451)

---
#### Feedback Bot on 09/10/2020, 11:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Rachel Kang [MSFT] on 13/10/2020, 04:02 PM: 

<p>​Hi @Eigil Krogh Sorensen,<br>
​I think you may have forgotten to attach the images you mentioned - would you mind including them? Also, is there a previous version of Xamarin.Forms in which you witnessed the appropriate behavior? What exactly is not working right with XF 4.8.0.1451 on macOS?</p>
<p>Thanks 😃<br>
​Rachel</p>

#### Rachel Kang [MSFT] on 13/10/2020, 04:02 PM: 

<p>​Hi @Eigil Krogh Sorensen,<br>
​I think you may have forgotten to attach the images you mentioned - would you mind including them? Also, is there a previous version of Xamarin.Forms in which you witnessed the appropriate behavior? What exactly is not working right with XF 4.8.0.1451 on macOS?</p>
<p>Thanks 😃<br>
​Rachel</p>

#### Eigil Krogh Sorensen on 13/10/2020, 05:22 PM: 

<p>They should be attached here<a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/160674-righlook-xamarinforms-4701260.png">righlook-xamarinforms-4701260.png</a><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/160675-wronglook-xamarinforms-4801451.png">wronglook-xamarinforms-4801451.png</a><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/160676-right-wronglook.zip">right-wronglook.zip</a></p><p>Xamarin.Forms (4.8.0.1534) doesn't make any change from Xamarin.Forms (4.8.1451)</p>

#### Rachel Kang [MSFT] on 13/10/2020, 07:27 PM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/48332/EigilKroghSorensen.html">Eigil Krogh Sorensen</a> Thanks for attaching the images! It seems like the disparity is in the background color for what appear to be Entry views. Is that correct? If not, would you be able to elaborate more on what exactly the issue is? If you could also attach this project or a sample project that reproduces the same issue, that would help us better understand what’s happening. Thank you!</p>

#### Eigil Krogh Sorensen on 13/10/2020, 08:02 PM: 

<p>That is correct</p>

#### Rachel Kang [MSFT] on 13/10/2020, 08:38 PM: 

<p>@<a target='_blank' href="https://developercommunity.visualstudio.com/users/48332/EigilKroghSorensen.html">Eigil Krogh Sorensen</a> Thank you for clarifying! Would you please also share this project or a simple project reproducing this issue, so that we can take a closer look? Thanks 😃</p>

#### Eigil Krogh Sorensen on 14/10/2020, 00:20 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
I was able to repro this issue, there's an issue with Entries, on MacOS, being styled with a Style, and the BackgroundColor isn't applied. But the Background color is used a s border color for the entry.
