### ISSUE TITLE
[Bug] [iOS]  Slider ThumbImage is covered by Truck

### ISSUE THREAD

**Issue by HausBJB** [xamarin/Xamarin.Forms#12544]
Hallo

I have defined a ThumbImageSource for the slider, unfortunately it is displayed incorrectly on iOS and the image (font) is pushed into the background of the truck.

### Steps to Reproduce

`                        <Slider
                            x:Name="HausBS"
                            DragCompleted="JSlider_DragCompleted"
                            DragStarted="JSlider_DragStarted"
                            HorizontalOptions="Fill"
                            Maximum="100"
                            Minimum="0"
                            ThumbColor="#003333"
                            VerticalOptions="Fill"
                            Value="50" />`

### Basic Information

- Version with issue:  4.8
- IDE: Visual Studio 2019 16.8.0 Preview 4.0
- iOS:  14.0
- Android: 10.0

###  Repro-Projekt
[https://github.com/HausBJB/App1.git](url)

### Screenshots
iOS
![image](https://user-images.githubusercontent.com/53478848/96708214-32509d00-1399-11eb-8a07-b00ed4b1f891.png)
Android
![image](https://user-images.githubusercontent.com/53478848/96708442-89567200-1399-11eb-9494-35af723fb0dd.png)

**Comment by StephaneDelcroix** [comment]
I'm not sur eI understand the issue. could you please attach a repro project ?

**Comment by HausBJB** [comment]
hello i uploaded the project

**Comment by PureWeen** [comment]
@HausBJB I think this is just a difference with how iOS modifies its slider display vs Android. 

If the track was covering the image you'd see orange overlapping the image on the right side. The image you're using is transparent so on iOS you're just seeing the track through the image. It looks like Android accounts for this and modifies the track whereas Android iiOS doesn't

**Comment by HausBJB** [comment]
Hello, I already thought that means that the Android actually does it wrong because it is transparent and it does not display it transparently

Thanks then that can actually be closed
