### ISSUE TITLE
[Bug] CollectionView adding items - items jumping erratically

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12555]
I tried converting my bindable stack layouts to collection views but am running into several problems again preventing me from using them.

I have items in the collection view that are of different sizes, so ItemSizingStrategy is MeasureAllItems. I have a LinearItemsLayout with ItemSpacing. The collection view serves as container for chat messages.

No matter what ItemsUpdatingScrollMode is set to, items and the scroll position jumps around randomly when I add new items. **This error happens when the CollectionView's item measurement strategy has been set to MeasureAllItems, items of different heights are visible, and a new element is added.**

Video of the issue with a CollectionView, with MeasureAllItems:
https://drive.google.com/file/d/1avaPs2O0oSQNHBEG5GpExNawNB9QvVD5/view?usp=sharing

Video of the issue with a ListView, with UnevenRows:
https://drive.google.com/file/d/1yoKMVuCU0Rerp0evjZ-N8X4c7nbJLmDq/view?usp=sharing

XF 5 latest preview, iOS (didn't test on Android).

EDIT: Added videos.
Please note: A comment further down this thread has repro steps.

**Comment by acuntex** [comment]
If you implement the Scrolled event and track `e.VerticalOffset` you can see that during the scroll on iOS the offset increases and suddenly jumps to 0, and then back.

It's totally messed up, if you want to show a "Scroll Up"-Button depending on the Scroll State, you can see the Button appearing/disappearing because there is suddenly this "0".

**Comment by Tommigun1980** [comment]
> If you implement the Scrolled event and track `e.VerticalOffset` you can see that during the scroll on iOS the offset increases and suddenly jumps to 0, and then back.
> 
> It's totally messed up, if you want to show a "Scroll Up"-Button depending on the Scroll State, you can see the Button appearing/disappearing because there is suddenly this "0".

Ah. The same thing happens very much visually if you use pull-to-refresh - the scroll offset seems to jump to 0 a couple of times.

Xamarin please could this get fixed as it’s currently impossible to edit a collection view due to the jumping around? Thank you so much.

**Comment by Tommigun1980** [comment]
I think this issue is related to https://github.com/xamarin/Xamarin.Forms/issues/12554 which may be both caused by https://github.com/xamarin/Xamarin.Forms/issues/11511.

Furthermore, I can not reproduce this with:
1) A collection view if the item sizing strategy is set to measure first item (unfortunately I can't do it here as the items have different sizes)
2) A list view
3) A bindable layout

So I think all of these issues have to do with bugging MeasureAllItems.

**Comment by Tommigun1980** [comment]
Here is a video of the issue:
https://drive.google.com/file/d/1yoKMVuCU0Rerp0evjZ-N8X4c7nbJLmDq/view?usp=sharing

What is weird is that any CONSECUTIVE add operations work just fine:
https://drive.google.com/file/d/1HOFfEohNkT3R8uTctkEHu80VYcWLk-aQ/view?usp=sharing

If I restart the app, then it always jumps once when adding items.

Couple of notes:
1) This happens only when measurement strategy is all items.
2) The exact same problem happens with a ListView if uneven rows is set to true,
3) The videos were taken from a list view, as the effect is exactly the same and I tried converting the collection views to list views (but the same problem happens there).

**Comment by Tommigun1980** [comment]
Here is a video of the issue:
https://drive.google.com/file/d/1yoKMVuCU0Rerp0evjZ-N8X4c7nbJLmDq/view?usp=sharing

What is weird is that any CONSECUTIVE add operations work just fine:
https://drive.google.com/file/d/1HOFfEohNkT3R8uTctkEHu80VYcWLk-aQ/view?usp=sharing

If I restart the app, then it always jumps once when adding items.

Couple of notes:

This happens only when measurement strategy is all items.
This happens only one time when adding a new item.
This happens only if I scroll to the newly added item.
The exact same problem happens with a ListView if uneven rows is set to true,
The videos were in fact taken from a list view, as the effect is exactly the same and I tried converting the collection views to list views (but the same problem happens there).
So final repro steps:

Have a collection view or list view with uneven rows/measure first item.
Add a new item to it.
Scroll to the newly added item.
The issue happens.
Add more items - issue doesn't happen anymore.
This issue doesn't happen with a bindable StackLayout, even when scrolling to newly added items.
I think this issue is related to #12554 which may be both caused by #11511 and #10842.

So I think all of these issues have to do with bugging measurements of items, possibly when using data templates of different heights (or merely if the items themselves have different heights, haven't tested).

If this could be fixed CollectionView would become the de-facto collection component, but unfortunately I can't use it at all with these issues. The fact ListView suffers of this same exact problem makes me unable to ship anything. Please please prioritise this as it completely defeats the purpose of the collection and list views as you can't alter them.

**Comment by Tommigun1980** [comment]
Here is a video of the issue:
https://drive.google.com/file/d/1yoKMVuCU0Rerp0evjZ-N8X4c7nbJLmDq/view?usp=sharing

What is weird is that any CONSECUTIVE add operations work just fine:
https://drive.google.com/file/d/1HOFfEohNkT3R8uTctkEHu80VYcWLk-aQ/view?usp=sharing

If I restart the app, then it always jumps once when adding items.

Couple of notes:

This happens only when measurement strategy is all items.
This happens only one time when adding a new item.
This happens only if I scroll to the newly added item.
The exact same problem happens with a ListView if uneven rows is set to true,
The videos were in fact taken from a list view, as the effect is exactly the same and I tried converting the collection views to list views (but the same problem happens there).
So final repro steps:

Have a collection view or list view with uneven rows/measure first item.
Add a new item to it.
Scroll to the newly added item.
The issue happens.
Add more items - issue doesn't happen anymore.
This issue doesn't happen with a bindable StackLayout, even when scrolling to newly added items.
I think this issue is related to #12554 which may be both caused by #11511 and #10842.

So I think all of these issues have to do with bugging measurements of items, possibly when using data templates of different heights (or merely if the items themselves have different heights, haven't tested).

If this could be fixed CollectionView would become the de-facto collection component, but unfortunately I can't use it at all with these issues. The fact ListView suffers of this same exact problem makes me unable to ship anything. Please please prioritise this as it completely defeats the purpose of the collection and list views as you can't alter them.

**Comment by Tommigun1980** [comment]
This is now my code just for jumping to the last message. Three hacks for the price of one.

```c#
        private void ScrollToLastMessage(bool animate)
        {
            if (this.vm.ChatMessages.Count > 0)
            {
                var lastItem = this.vm.ChatMessages[this.vm.ChatMessages.Count - 1];
                this.chatMessagesScrollView.ScrollTo(lastItem, ScrollToPosition.End, animate);
            }
        }

        private async void ChatMessagesScrollView_ItemAppearing(object sender, ItemVisibilityEventArgs e)
        {
            // TEMP HACK: can't call ScrollToLastMessage when the list has been populated
            // as it may miss a few items at the tail end. so wait until at least one item
            // has appeared
            if (this.isScrollToLastMessageRequested)
            {
                this.isScrollToLastMessageRequested = false;
                this.ScrollToLastMessage(false);
            }

            if (e.ItemIndex == this.vm.ChatMessages.Count - 1)
            {
                this.isScrolledToLastChatMessage = true;

                // TEMP HACK! even when an item is claimed to be visible (ItemAppearing), it is not so delay a bit.
                // we jump to the last message when data has been loaded so we need an overlay hiding the list,
                // but even when ItemAppearing claims the last item has been made visible the list still shows the
                // initial messages... so delay a slight bit here.
                // TODO: this nonsense can be removed once migrating to CollectionView as it has a scroll policy that
                // can be set to end, which will initially put the list at the end position
                if (!this.HasFullyLoadedChatMessages)
                {
                    await Task.Delay(17);
                    this.HasFullyLoadedChatMessages = true;
                }
            }
        }

        private async void OnChatMessageReceived(IChatService.OnChatMessageReceivedParams args)
        {
            if (this.isScrolledToLastChatMessage)
            {
                // TEMP HACK! for the first new item added to a list, and if it's scrolled
                // near its insertion time, the list jumps around.
                // this nonsense can be removed once https://github.com/xamarin/Xamarin.Forms/issues/12555 is fixed
                if (!this.tempHackHasReceivedAtLeastOneNewMessage)
                {
                    await Task.Delay(200);
                    this.tempHackHasReceivedAtLeastOneNewMessage = true;
                }

                this.ScrollToLastMessage(true);
            }
        }
```

**Comment by Tommigun1980** [comment]
Collection View equivalent follows. Hacks are now mostly centered around ItemsUpdatingScrollMode="KeepLastItemInView" not doing anything when the list is populated, so a manual scroll is required. However, it takes an arbitrary amount of time before ScrollTo actually does anything, so I listen to ChildAdded instead. But even there we need to wait arbitrarily for a few operations to do anything. I really dislike adding this much hacks and random delays to get a list to scroll to the bottom. I also once again have to put an overlay over the collection view while this nonsense is going on, to hide what's going on:

```c#
        // TEMP HACK! ItemsUpdatingScrollMode="KeepLastItemInView" doesn't work when collection view is populated,
        // so wait until one element has been added and manually scroll to bottom.
        // I also tried to manually scroll to bottom when collection gets data, but that is also too early.
        // TODO: remove this nonsense once Xamarin fixes KeepLastItemInView when creating collection, or fixes
        // ScrollTo in conjunction with a collection being populated.
        private async void ChatMessages_ChildAdded(object sender, ElementEventArgs e)
        {
            if (this.tempHackHasRequestedInitialScrollToBottom)
            {
                this.tempHackHasRequestedInitialScrollToBottom = false;

                await Task.Delay(17); // HACK! trying to scroll while items are being added seems to be ignored

                this.ScrollToLastMessage(false);

                await Task.Delay(17); // HACK: scroll doesn't seem to be immediate and it doesn't return a Task to await on...
                this.HasFullyLoadedChatMessages = true;
            }
        }
```

**Comment by Tommigun1980** [comment]
> If you implement the Scrolled event and track `e.VerticalOffset` you can see that during the scroll on iOS the offset increases and suddenly jumps to 0, and then back.
> 
> It's totally messed up, if you want to show a "Scroll Up"-Button depending on the Scroll State, you can see the Button appearing/disappearing because there is suddenly this "0".

This seems to be the root cause. I is very much visible with a CollectionView inside a RefreshView as per https://github.com/xamarin/Xamarin.Forms/issues/12622, and I also debugged that what happens when new elements are added is that ItemAppearing is called for the last element, but then ItemDisappearing is called for it, ItemAppearing for a few elements before it, and ultimately ItemAppearing for the last item AGAIN. So it is exactly as you say, it seems to do an internal scroll whenever the collection changes when MeasureAllItems is turned on *and* items of different heights are visible (and the same for a ListView with UnevenRows turned on).

**Comment by acuntex** [comment]
@Tommigun1980 Do you somehow use FFImageLoading?

I replaced FFImageLoading with Xamarin.Forms.Nuke/GlideX.Forms and the scrolling problems are gone now.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 Do you somehow use FFImageLoading?
> 
> I replaced FFImageLoading with Xamarin.Forms.Nuke/GlideX.Forms and the scrolling problems are gone now.

Wow, I do! Thank you, I will look into it. Maybe all the issues have been caused by FFImageLoading then? I will test Glide/Nuke and report back, but I am unsure if it will fit my needs. I have a very delicate caching strategy where some things are cached on disk + memory, while the bulk only on disk. Glide/Nuke doesn't seem to have any control over it, and the docs don't even mention if "cache" means memory or disk cache. I don't want the clients to redownload all the assets on every boot and only cache them in memory. Anyhow, I'll give it a try and see if FFImageLoading is actually the one creating all of these problems. Thanks for the info, mate!

**Comment by acuntex** [comment]
You can also check https://github.com/kean/Nuke/

If the wrapper provided with Xamarin.Forms.Nuke exposes all APIs then it's possible to set the Cache strategy.

**Comment by Tommigun1980** [comment]
> You can also check https://github.com/kean/Nuke/
> 
> If the wrapper provided with Xamarin.Forms.Nuke exposes all APIs then it's possible to set the Cache strategy.
> 
> Just in case: If you use glidex, you have to provide the HeightRequest/WidthRequest of the images because in some cases it does not show any image if you don't provide it.

Unfortunately the XF integration seems to be platform specific and gives no control on the XF side. I will try temporarily just removing the FFImageLoading to see if it really is causing all these problems, but I do see problems in CollectionViews where FFImageLoading images reside where they have a height set. So I don't see how they could break the scroll view and cause it to jump up and down?

**Comment by Tommigun1980** [comment]
Yeah I confirmed that the issues happen without FFImageLoading. But thanks for the tip anyway, I really appreciate it!!

**Comment by acuntex** [comment]
@Tommigun1980 
Yes, in order to configure Nuke or GlideX you would have to put the configuration code for each platform separate in AppDelegate/MainActivity

Have you removed FFImageLoading completely and you still have the scrolling issues? (Not only replacing CachedImage with Image with CachedImageRenderer.InitImageSourceHandler() active, but the complete NuGet package)

I do have different heights (basically like WhatsApp with messages/images) and the problem is solved.
Btw. you should also try the fix described here: https://github.com/xamarin/Xamarin.Forms/issues/10842#issuecomment-664670915
It's a custom renderer for CollectionView that fixes sizing problems with different heights.

**Comment by Tommigun1980** [comment]
> @Tommigun1980
> Yes, in order to configure Nuke or GlideX you would have to put the configuration code for each platform separate in AppDelegate/MainActivity
> 
> Have you removed FFImageLoading completely and you still have the scrolling issues? (Not only replacing CachedImage with Image with CachedImageRenderer.InitImageSourceHandler() active, but the complete NuGet package)
> 
> I do have different heights (basically like WhatsApp with messages/images) and the problem is solved.
> Btw. you should also try the fix described here: [#10842 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/10842#issuecomment-664670915)
> It's a custom renderer for CollectionView that fixes sizing problems with different heights.

Hi. I don't see any issue with FFImageLoading so I won't be replacing it, but thanks for the suggestion. I am positive it has nothing to do with the collection view and list view issues, I had issues with them before even using FFImageLoading and I can't see how just the mere presence of its NuGet would somehow break the other components. But I did have the entire NuGet removed when I tested removing the images from the collection and list views. It isn't related to it.
I will try the renderer hacks in https://github.com/xamarin/Xamarin.Forms/issues/10842#issuecomment-664670915, thanks again for trying to help me, I really appreciate it!

**Comment by Tommigun1980** [comment]
Apparently my hacks for the list view to scroll to the bottom don't work on Android, so I don't know what to do next. I couldn't find any permutation of controls that work.

@acuntex: The fixes seem all lacking to some degree and either try to hard code the heights of the data templates (can't do as I'm displaying chat messages), or seem to break something else like grouping or headers. If someone provides a renderer that just fixes this issue without breaking something else I'd definitely try it.

**Comment by Tommigun1980** [comment]
Hi @jsuarezruiz. I saw that you had assigned yourself to some of the collection view issues. After having a look at the open issues it seems as this report is a duplicate. In fact there's a ton of reports that seem to all have to do with this exact same measurement problem in CollectionViews (and ListViews), that are exposed when measurement strategy is set to all items *and* items of different heights are visible. The issues manifest when adding items, when scrolling etc.

Do you think there is any chance this could get fixed at some point, as I am honestly unsure of how to proceed. I have spent so much time on this and it all comes back to this issue. I wouldn't be surprised if almost all of my reports had the same root cause of incorrect measurements.

Thank you so much.

**Comment by Tommigun1980** [comment]
Repro project at https://github.com/xamarin/Xamarin.Forms/issues/13231.

**Comment by brentedwards** [comment]
I see a similar issue with CollectionView. We have implemented forever scroll functionality in our app. When the user hits the bottom of the items loaded, the next chunk is loaded. If I scroll to the bottom fast enough, I can see the next record added. However, once I scroll, the CollectionView jumps up the items and it looks as though the app is loading duplicate records. As the CollectionView gets filled with more and more items, that jump can become rather significant. Our application uses Xamarin.Forms 4.5.0.657, however I was able to reproduce this issue in a standalone sample app which uses the latest stable release (5.0.0.1874). I've attached a zip of that sample app.
[CollectionViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/5817345/CollectionViewSample.zip)

**Comment by Tommigun1980** [comment]
> I see a similar issue with CollectionView. We have implemented forever scroll functionality in our app. When the user hits the bottom of the items loaded, the next chunk is loaded. If I scroll to the bottom fast enough, I can see the next record added. However, once I scroll, the CollectionView jumps up the items and it looks as though the app is loading duplicate records. As the CollectionView gets filled with more and more items, that jump can become rather significant. Our application uses Xamarin.Forms 4.5.0.657, however I was able to reproduce this issue in a standalone sample app which uses the latest stable release (5.0.0.1874). I've attached a zip of that sample app.
> [CollectionViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/5817345/CollectionViewSample.zip)

Same happens when items are deleted.

**Comment by hartez** [comment]
@Tommigun1980 are you still seeing this problem with 5.0.0.1931? 

@brentedwards I tried to run your repro app, but it just crashes on load.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 are you still seeing this problem with 5.0.0.1931?
> 
> @brentedwards I tried to run your repro app, but it just crashes on load.

Hi @hartez! I can see the issue partially in 5.0.0.1931 when adding items, the CollectionView is using 'KeepLastItemInView' and it is not scrolled to the bottom. I just replied to you here regarding it:
https://github.com/xamarin/Xamarin.Forms/issues/13231#issuecomment-774378186

It is reproducible with the 'Mega repro project for CollectionView issues' and I added a new video there describing the problem.

Thank you!

**Comment by Tommigun1980** [comment]
(This is an old ticket wherefrom I extracted the bugs into the 'Mega repro project for CollectionView issues' ticket and repro project, which also has more information and better videos of the issues. So maybe this ticket should be closed?

This ticket does contain information about similar ListView problems, but considering it's been deprecated in favour of the CollectionView, and the CollectionView received such solid updates fixing a lot of the pressing issues at least I wouldn't mind if the ListView stayed as it is).

Thank you again.

**Comment by Tommigun1980** [comment]
@hartez I'll go ahead and close this ticket in favour of https://github.com/xamarin/Xamarin.Forms/issues/13231. If you feel differently please reopen it!
