### ISSUE TITLE
[Bug] macOS issues

### ISSUE THREAD

**Issue by andyfmking** [xamarin/Xamarin.Forms#12559]
### Description
Xamarin forms bugs on MacOS platform

1. Navigation Page TitleView not showing controls while toolbarItems show and work correctly
2. FontIcons don't show on app start (shows question mark), shows after replacing the mainpage the second time.
3. Button border height doesn't resize correctly
4. ListView Item Height doesn't resize / fit correctly only fix is declaring HeightRequest of the item

### Steps to Reproduce

1. Create Xamarin Forms Project & add MacOS head
2. Add FontIcons
3. Add Label in NavigationPage's TitleView and use the FontIcon on the label.
4. Add Button with Text in Content Page
5. Add ListView with items in Content Page
6. Run Mac Application

### Expected Behavior
1. Label should be visible on Navigation Bar
2. FontIcons should show on the label's text
3. Button Border should display with correct height
4. Listview Items should be sized correctly

### Actual Behavior
1. Label is invisible on Navigation Bar (all controls are invisible)
2. FontIcons don't show on the label's text instead it shows a question mark
3. Button Border strike through the button (height is smaller than required)
4. ListView Items are spaced more than required size (Appears as VerticalOptions = CenterAndExpand)

### Basic Information

- Version with issue: 4.8.0.1451
- Last known good version:
- IDE: Visual Studio Mac 8.7.8 (build 4)
- Platform Target Frameworks: 
  - iOS:  12.0
  - Android: 10.0
  - UWP:  1669
  - macOS: xamarinmac20
- Android Support Library Version: AndroidX
- Nuget Packages:
- Affected Devices: All

### Workaround

Use toolbar Items on Mac if a button is needed on the Navigation Bar

Set MainPage to a different page from c# code behind to reload the fonts and display them correctly.

Set Row HeightRequest for Listview items to size correctly

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
