### ISSUE TITLE
[Enhancement] Please let WebView support CSS media query ‘prefers-color-scheme'

### ISSUE THREAD

**Issue by chaoyebugao** [xamarin/Xamarin.Forms#12551]
## Summary
For better user experience with dark mode on web sites, Please let WebView support CSS media query `prefers-color-scheme`.

## API Changes

Android & iOS both platforms have problems but different.
Android's WebView can not detect media query `prefers-color-scheme` at all.
iOS's WebView is correctly following OS's appearance, but there is white background flashed before page loaded under dark appearance.

Let WebView with CSS media query `prefers-color-scheme` support, so the pages implemented would switch theme by OS automatically.

## Intended Use Case
MS offical doc site has implemented `prefers-color-scheme`
So everyone can test on [https://docs.microsoft.com/en-us/xamarin/](https://docs.microsoft.com/en-us/xamarin/)

## Reference
https://caniuse.com/?search=prefers-color-scheme
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by chaoyebugao** [comment]
Also there is plan B: [How to override css prefers-color-scheme setting](https://stackoverflow.com/questions/56300132/how-to-override-css-prefers-color-scheme-setting)
But it's complicated and not a standard practice.

**Comment by mubaarakhassan** [comment]
Is there any consideration to implement this feature? This feature is in 'under consideration' for about ten months.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
