### ISSUE TITLE
[Bug] CollectionView requires slight scroll before item spacing becomes correct

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12554]
I tried converting my bindable stack layouts to collection views but am running into several problems again preventing me from using them.

I have items in the collection view that are of different sizes, so ItemSizingStrategy is MeasureAllItems. I have a LinearItemsLayout with ItemSpacing of 12. When the view loads all the items seem to have double item spacing. As soon as I scroll the view even slightly all items jump to their correct positions.

I have a video of the issue, please let me know where to send it if it would be useful.
The issue only started to happen once I replaced a bindable layout with a collection view.

XF 5 latest preview, iOS (didn't test on Android).

**Comment by Tommigun1980** [comment]
I think this issue is related to https://github.com/xamarin/Xamarin.Forms/issues/12554 which may be both caused by https://github.com/xamarin/Xamarin.Forms/issues/11511.

Furthermore, I can not reproduce this with:
1) A collection view if the item sizing strategy is set to measure first item (unfortunately I can't do it here as the items have different sizes)
2) A list view
3) A bindable layout

So I think all of these issues have to do with bugging MeasureAllItems.

**Comment by Tommigun1980** [comment]
I found a fix for this -- one of my data templates had height set to * instead of Auto, and changing it to Auto fixed this. What is strange, however, is that with * CollectionView requires the slight scroll for the items to align properly -- this does not happen with for example bindable layouts so I do think this is an issue in CollectionView still, but I am just happy it works now.

Thanks.

**Comment by rmarinho** [comment]
Duplicated #12722
