### ISSUE TITLE
How to Time Picker Set to Binding Value

### ISSUE THREAD

**Issue by Johnvan** [xamarin/Xamarin.Forms#12556]
Why can't I set the xaml Control TimePicker to the database field Date as follows, the result is 00:00:00 or 12:00:00 if Format is Format="HH:mm"

<TimePicker x:Name="_timePicker2" Format  ="hh:mm" Time="{Binding Date}" ></TimePicker>

Otherwise TimePicker works as far as Setting the time manually.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d81a385-0a5c-f7e0-da81-da565e5100c9
* Version Independent ID: 07691376-7c3c-8e9d-416e-9a92082ffab1
* Content: [TimePicker.Time Property (Xamarin.Forms)](https://docs.microsoft.com/en-au/dotnet/api/Xamarin.Forms.TimePicker.Time?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/TimePicker.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/TimePicker.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
This will be addressed once we merge #11474
