### ISSUE TITLE
[Bug] EmbeddedFonts do not support multiple font faces within the same font family

### ISSUE THREAD

**Issue by timvandenhof** [xamarin/Xamarin.Forms#12558]
### Description
Xamarin.Forms now a days support embedding Fonts in shared code. Therefore the font files (TTF) have to be added to te shared project as embedded resource and exported. After that it should be as easy as referencing the FontFamily in your FontFamilly-attributes or styles.

In practice, many fonts exists of separate font files where each font face is in a separate TTF. Together they form the font family. I would expect Xamarin to handle importing these files as a single font family, so that labels can use FontAttributes to select the correct font face.

### Steps to Reproduce

0. Visual Studio for Mac
1. New Solution > Multiplatform > Blank Forms App (C#)
   Target: iOS and Android
   Version Control: disabled
   App Center Test: disabled
2. Update Xamarin.Forms dependencies on all 3 projects (shared, Android, iOS).
3. Download a font, for example Lato from https://fonts.google.com/specimen/Lato
4. Add TTF-files to a new Fonts folder in the shared project.
5. Set the build type to EmbeddedResource for each TTF-file, using the properties pane.
6. Add a C# file to the Fonts folder with the ExportFont attributes.
```
using Xamarin.Forms;
// Attempt 4: all font faces with alias => last exported font is used for all font faces
[assembly: ExportFont("Lato-Black.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-BlackItalic.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-Bold.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-BoldItalic.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-Italic.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-Light.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-LightItalic.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-Regular.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-Thin.ttf", Alias = "Lato")]
[assembly: ExportFont("Lato-ThinItalic.ttf", Alias = "Lato")]
```
7. Add some Label-controls to the MainPage.xaml
```
<Label FontFamily="Lato" FontAttributes="None" Text="Lato Regular" />
<Label FontFamily="Lato" FontAttributes="Italic" Text="Lato Italic" />
<Label FontFamily="Lato" FontAttributes="Bold" Text="Lato Bold" />
<Label FontFamily="Lato" FontAttributes="Bold,Italic" Text="Lato Bold and Italic" />
```
8. Run the Android app on emulator (Pixel 2, Pie 9.0, API 28)
9. Notice that all labels are rendered in the Thin Italic font face.

### Expected Behavior
All font files (TTF's) loaded where font faces are combined into a single font family, so that they can be used with FontAttributes on Label controls. Alias should be irrelevant.

### Actual Behavior
Alias is required to have a font used at all and only the last registered font face is used, instead of the specified font face on the label.

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1560
- Last known good version: none
- IDE: Visual Studio for Mac (Enterprise) 8.7.8 (build 4)
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS 14.0.0.0
  - Android: Xamarin.Android 11.0.2.0
      Target Framework: Android 9.0 (Pie)
      Minimum Android version: Android 5.0 (API level 21)
      Target Android version: Android 9.0 (API level 28)
  - UWP:  does not apply
- Android Support Library Version: none
- Nuget Packages:
    Xamarin.Essentials 1.5.3.2
    Xamarin.Forms 4.8.0.1560
- Affected Devices:
    Android Emulator: Pixel 2 on Android 9.0 (Pie) with API 28

### Screenshots

Bug: only last loaded font face is shown
![Screenshot_1603309973](https://user-images.githubusercontent.com/2083464/96775434-d5c89e80-13e7-11eb-8e01-2367af55598c.png)

Font file: Lato Regular
![Screenshot 2020-10-21 at 21 57 10](https://user-images.githubusercontent.com/2083464/96775861-6e5f1e80-13e8-11eb-9a2c-4ff30ad3d982.png)
![Screenshot 2020-10-21 at 21 59 04](https://user-images.githubusercontent.com/2083464/96776037-bbdb8b80-13e8-11eb-8724-d75f6df30d84.png)

Font file: Lato Bold
![Screenshot 2020-10-21 at 21 58 12](https://user-images.githubusercontent.com/2083464/96775923-8a62c000-13e8-11eb-8423-7267a389e540.png)
![Screenshot 2020-10-21 at 21 59 27](https://user-images.githubusercontent.com/2083464/96776056-c1d16c80-13e8-11eb-96c6-995ea8087a39.png)

### Reproduction Link

Reproduction solution: [XamarinForms.Repro.FontFaceIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/5418517/XamarinForms.Repro.FontFaceIssue.zip) (804KB)

### Workaround
No workaround found yet.
Maybe there are options to combine multiple TTF's in to a single (different) font file?

If this is not a bug but intended behavior then one of, or combinations of, the following could be made as an improvement to support font faces (random order):
- Update documentation to notice this is not supported;
- Add support for TTC (True Type Font Collections) so that a single file can be loaded with multiple font faces;
- Add support to automatically detect that a font family is already registered and add the font face;
- Add support to specify font faces in the ExportFontAttribute.

Support for multiple font faces:
Android: Supported. see https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml#font-family
iOS: Supported, see https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app
UWP: Seems supported? See https://stackoverflow.com/questions/52129241/uwp-iot-how-to-add-custom-font

**Comment by scriptBoris** [comment]
The problem is very urgent

**Comment by michelevirgilio** [comment]
Definitely needed.

**Comment by michaldivis** [comment]
This would be super userful! My current workaround is not that bad, but still, if this worked the code would be a bit cleaner.

**Comment by wolf81** [comment]
This is an issue indeed. Can we use TTC files with the embedded font loading functionality? That might be a decent work-around, as FontForge can be used (freely) to generate a TTC file for a group of TTF files.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
