### ISSUE TITLE
[Bug] [iOS] CarouselView makes the app crashing with too few items on Xamarin 5.0.0.1558-pre3

### ISSUE THREAD

**Issue by DjeeBay** [xamarin/Xamarin.Forms#12550]
### Description
Adding a CarouselView with less than 5 items freezes the app after scrolling.
More than 5 items the scroll is infinite.
### Steps to Reproduce

1. Brand new project 
2. Adding a CarouselView (same as documentation)

```
<CarouselView.ItemsSource>
    <x:Array Type="{x:Type x:String}">
        <x:String>Baboon</x:String>
            <x:String>Capuchin Monkey</x:String>
        </x:Array>
    </CarouselView.ItemsSource>
    <CarouselView.ItemTemplate>
        <DataTemplate>
            <StackLayout>
                <Frame HasShadow="True"
                       BorderColor="DarkGray"
                       CornerRadius="5"
                       Margin="20"
                       HeightRequest="300"
                       HorizontalOptions="Center"
                       VerticalOptions="CenterAndExpand">
                    <StackLayout>
                        <Label Text="test"
                               FontAttributes="Bold"
                               FontSize="Large"
                               HorizontalOptions="Center"
                               VerticalOptions="Center" />
                    </StackLayout>
                </Frame>
            </StackLayout>
        </DataTemplate>
    </CarouselView.ItemTemplate>
</CarouselView>

```
### Expected Behavior
Not freezing the app or making an infinite scroll.
### Actual Behavior
Freezes the app or in my real world case, making an infinite loop and not displaying the page at all after trying to navigate into it.
### Basic Information

- Version with issue: 5.0.0.1558-pre3
- Last known good version:
- Xamarin.Forms: 4.8.0.1560
- Platform Target Frameworks: 
  - iOS:  14.0
- Affected Devices: iPhone

### Workaround
Not found

**Comment by PureWeen** [comment]
@DjeeBay can you attach a repro please? I tried with your XAML and I'm not seeing the issue you describe

**Comment by DjeeBay** [comment]
Sorry for the delay, here is a simple sample.
For me it still not working, maybe I'm missing something...

[TestXamarin.zip](https://github.com/xamarin/Xamarin.Forms/files/5486230/TestXamarin.zip)

**Comment by jsuarezruiz** [comment]
@DjeeBay This issue have been fixed in Xamarin.Forms 5.0-re4. Could you try to update to that version?

**Comment by jsuarezruiz** [comment]
This the PR with the fix: https://github.com/xamarin/Xamarin.Forms/pull/12787
