### ISSUE TITLE
[Bug] [MacOS] Xamarin.Forms app on Mac isn't responding to universal links

### ISSUE THREAD

**Issue by kevcrooks** [xamarin/Xamarin.Forms#12569]
We have universal links working in our Xamarin.iOS app, but the same is not working when we try to add support in Xamarin.Mac:

We've set up universal links in our Xamarin.iOS app by setting Entitlements to support associated domains:
https://developer.apple.com/documentation/safariservices/supporting_associated_domains
and also by supporting universal links in our app:
https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/supporting_universal_links_in_your_app
In Xamarin Forms for iOS, this corresponded to adding the following lines in our `AppDelegate`:
```
        public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options) => 
            base.OpenUrl(app, url, options);

        public override bool ContinueUserActivity(UIApplication application, NSUserActivity userActivity, UIApplicationRestorationHandler completionHandler) => 
            base.ContinueUserActivity(application, userActivity, completionHandler);
```
and overriding `OnAppLinkRequestReceived()` in to our main Xamarin.Forms `Application`.

This all works fine in iOS, and I've followed the same steps for our Xamarin.Mac application, by using the following lines in our `AppDelegate` instead:
```
        public override void OpenUrls(NSApplication application, NSUrl[] urls) =>
            base.OpenUrls(application, urls);

        public override bool ContinueUserActivity(NSApplication application, NSUserActivity userActivity, ContinueUserActivityRestorationHandler restorationHandler) => 
            base.ContinueUserActivity(application, userActivity, restorationHandler);
```
however when I run this for Mac, the universal links aren't being opened in the app.

The only difference I can see is that for Xamarin.iOS the `ContinueUserActivity()` method exists in `Xamarin.Forms.Platform.iOS.FormsApplicationDelegate`, but for Mac it's not in the corresponding `Xamarin.Forms.Platform.MacOS.FormsApplicationDelegate`, but looks like there might be a not-implemented version in `AppKit.NSApplicationDelegate` instead.

Is there a mistake we're making to get this working on Mac too, or do we need to wait for this to be implemented?

We're using Xamarin.Forms version `4.6.0.1073` at the moment, as waiting for a few fixes to update to the latest.

**Comment by rachelkang** [comment]
Hi, @kevcrooks - thanks for submitting this issue! I'm continuously exploring this issue, but in the meantime, could I ask what version of macOS you're using? And if there are any additional details that you think might be helpful to share, I'd really appreciate them!

Also, here are some resources I've been taking a look at that you may also find helpful:
- https://stackoverflow.com/questions/40991312/universal-links-on-macos
- https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content?language=objc
- https://developer.apple.com/documentation/appkit/nsapplicationdelegate#declaration
- https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/supporting_universal_links_in_your_app?language=objc

**Comment by kevcrooks** [comment]
@rachelkang Thank you, I'm using version 10.15.7 (Catalina), and have uploaded the following `apple-app-site-association` file to our website:
```
{
  "applinks": {
      "details": [
           {
             "appIDs": [ "[TEAM].com.[iOSApp]", "[TEAM].com.[MacApp]" ],
             "components": [
               {
                  "/": "/open/*"
               }
             ]
           }
       ]
   }
}
```

This appears to be the newer format for this file, since the instructions I followed in the links posted above suggested an older format for the file, however I used the validator here to check it: 
https://branch.io/resources/aasa-validator

I've additionally noticed that our iOS app appears to work fine when I test app links on a simulator, but the downloaded app is just opening the links in Safari. I don't know if I'm missing something, or if this is just specific to the device I downloaded the app on. However I think I've followed all the instructions listed in the links above. I'll read through the new links you've posted in the meantime too, and post if we have any success.

Please let me know if you need any more details, as we'd like to add this support if we can?

**Comment by kevcrooks** [comment]
I've just been testing this again, and it appears to be partially working now, but exiting the app with an exception:

- I entered the app link in notes.app (as suggested in the stackoverflow link)
- Clicking this opened Safari, but gave me the option to "open" the link in the app instead.
- Once the app opened the link, it crashed.

I've found that the exception is coming from `ContinueUserActivity` when `base.ContinueUserActivity(application, userActivity, restorationHandler);` is called. 

The exception is
"Foundation.You_Should_Not_Call_base_In_This_Method"
in AppKit.NSApplicationDelegate.ContinueUserActivity() from NSApplicationDelegate.g.css:722

I tried not calling this `base` method, and instead just returning a boolean, but in this case the app starts without handling the link in `Application.OnAppLinkRequestReceived()` which we've overridden for our application. (This is where the app links on the other platforms are handled).

I think it might be possible to manually handle the `userActivity` here to pass the app link url directly, but I wondered if there is a built-in way to do this by a `base` call from our `AppDelegate`, like to the other platforms?

**Comment by kevcrooks** [comment]
@rachelkang we manually implemented something in the `ContinueUserActivity` method (rather than the `base` call that is used for iOS), and this seems to be working.

I hadn't noticed before that the very first time the app link is clicked in Mac, it opens in Safari, with the option to "open" the link in the app, but then every subsequent time the link opens correctly in our app, so this may be what I missed before.

It would be useful if the `base.ContinueUserActivity()` call could be fixed, to avoid our manual implementation (i.e. work in the same way as for iOS, where `base.ContinueUserActivity()` calls the `Application.OnAppLinkRequestReceived()` itself.

Can this issue be kept open for that fix, or shall I open a separate one?

**Comment by Redth** [comment]
We can keep this one open, and hopefully you or someone else in the community can contribute a PR to fix this and link it back to this issue :)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
