### ISSUE TITLE
Fails to Install XF5

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#12575]
Hi,

I am trying to install XF5 on my Mac but it's failing.

Attached is the log...

Thanks,
[Jassim](https://www.emiratesangels.org)

[XF5VisualStudiForMac.zip](https://github.com/xamarin/Xamarin.Forms/files/5425313/XF5VisualStudiForMac.zip)

**Comment by PureWeen** [comment]
@jrahma 


```

Version conflict detected for Xamarin.Android.Support.Annotations. Install/reference Xamarin.Android.Support.Annotations 28.0.0.3 directly to project Angels.Android to resolve this issue. \
 Angels.Android -> Xamarin.Forms.AppLinks 4.8.0.1560 -> Xamarin.Android.Support.v4 28.0.0.3 -> Xamarin.Android.Support.Media.Compat 28.0.0.3 -> Xamarin.Android.Support.Annotations (= 28.0.0.3) \
 Angels.Android -> Com.OneSignal 3.10.1 -> Xamarin.Android.Support.v7.CardView 26.0.2 -> Xamarin.Android.Support.Annotations (= 26.0.2).\
```

It looks like you have nugets with conflicting versions so you'll need to add specific versions of those libraries to resolve the conflicts

For example add `Xamarin.Android.Support.Annotations` version 28.0.0.3

FYI @JonDouglas
