### ISSUE TITLE
[Enhancement] Allow to change the ProgressBar Uncomplete Color

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#12583]
When we have a black background in dark mode we can't see ProgressBar

**Steps to Reproduce**
Set Dark Mode Android
Add a ProgressBar on a black background
Watch
**Expected Behavior**
ProgressBar background should be seen

**Actual Behavior**
ProgressBar size can't be shown

**Basic Information**
Version with issue: Xamarin Forms 4.8.0.1451
Last known good version: None
IDE: Visual Studio 2019
Platform Target Frameworks:
All
Android Support Library Version: Android X

Affected Devices:

**Screenshots**
![Screenshot_1603454809](https://user-images.githubusercontent.com/4941173/97002264-21766780-1510-11eb-949c-6b1b9c3f4f75.png)
![Screenshot_1603454842](https://user-images.githubusercontent.com/4941173/97002270-22a79480-1510-11eb-909e-cc1f9c313eb8.png)

**Workaround**
No workaround

Hey @samhouts, please include tag a/darkmode

**Comment by PureWeen** [comment]
@transis2 are you testing on API 29 devices? For me the progress bar is showing up correctly

![image](https://user-images.githubusercontent.com/5375137/97764591-1b1e5780-1add-11eb-9a6b-8cb7d871d30f.png)

**Comment by transis2** [comment]
@PureWeen I will check

**Comment by transis2** [comment]
Hi @PureWeen, it works when OS theme is set to dark.

Is it possible to expose progressbar progress "uncompleted" color to change ?

If we set BackgroundColor the control look like this print screen below
![Screenshot_1604155186](https://user-images.githubusercontent.com/4941173/97782016-d989bd00-1b6d-11eb-8297-
f3bde0a2df81.png)

**Comment by jsuarezruiz** [comment]
I am going to change this to an Enhancement where the request would be add one more property to the ProgressBar and to be able to modify the background color or the "uncomplete" color. @transis2

**Comment by transis2** [comment]
@jsuarezruiz Yes, thanks.

**Comment by mos379** [comment]
I very much would appreciate that too ;)

**Comment by alexandresanlim** [comment]
Looking forward to it

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
