### ISSUE TITLE
[Bug] Entry Bottom Line can not be seen on black Background in dark mode

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#12584]
When we have a black background in dark mode we can't see Entry control botom line

**Steps to Reproduce**

1. Set Dark Mode Android

2. Add a Entry on a black background
3. Watch

**Expected Behavior**
Entry Botom line should be possible to set to white

**Actual Behavior**
Entry Botom line Color can not be shown

**Basic Information**
Version with issue: Xamarin Forms 4.8.0.1451
Last known good version: None
IDE: Visual Studio 2019
Platform Target Frameworks:
iOS:
Android: Android 10
UWP:

Affected Devices:

**Screenshots**
![Screenshot_1603455499](https://user-images.githubusercontent.com/4941173/97003155-677ffb00-1511-11eb-8a51-6237776bb16a.png)
![Screenshot_1603455572](https://user-images.githubusercontent.com/4941173/97003159-68b12800-1511-11eb-948e-358cf4876ee0.png)

**Workaround**
Create a custom control

Hey @samhouts, please include tag a/darkmode

**Comment by transis2** [comment]
Same issue with Progressbar control
https://github.com/xamarin/Xamarin.Forms/issues/12583

**Comment by PureWeen** [comment]
@transis2 can you test on the latest 5.0 pre3? If you still see an issue can you attach a repro?

For me the underline is white

![image](https://user-images.githubusercontent.com/5375137/97764450-b6fb9380-1adc-11eb-8326-4c27fcb68771.png)

**Comment by transis2** [comment]
@PureWeen sure! I Will test and provide a feedbak

**Comment by transis2** [comment]
@PureWeen Hi, it works when android theme is set to dark.
I was using a custom app theme without change OS theme.
Is it possible to force controls to use dark theme independent of OS theme ?

**Comment by ezesil** [comment]
The same behaviour occurs when setting (in app.xaml.cs's constructor):

`Application.Current.UserAppTheme = OSAppTheme.Light; // Or Dark

It works properly if left Unspecified and your XAML reacts to OS changes, but this doesn't allow changing theme manually.
