### ISSUE TITLE
[iOS] Date picker does not appear to view in iOS 14 simulator  

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#12580]
### Description
Date picker does not appear to view in iOS 14 simulator. I have written the custom render for DatePicker. It is working fine in before and the earlier version of iOS but it is breaking from iOS14.

### Steps to Reproduce

1. Run the sample.
2. Tap the Date picker (Blue Color)
3.  See the DatePicker View does not come to the view.
4. it is working fine in before iOS 14.

### Expected Behavior
The DatePicker need to come to view when we edit the Date.

### Actual Behavior
The DatePicker does not come to view when we edit the Date.

### Basic Information

- Version with issue:XF version 4.8.0.1269, iOS 14
- Last known good version: iOS 13.4
- IDE: VisualStuio

### Screenshots
**iOS 13.4**
![iOS 13 2](https://user-images.githubusercontent.com/35529145/96958598-9c914b00-151b-11eb-8903-b35fea6d3c5d.png)

**iOS 14**
![iOS 14](https://user-images.githubusercontent.com/35529145/96958617-a915a380-151b-11eb-9e36-a44864ac9d44.png)

### Reproduction Link

[DatePickerTest.zip](https://github.com/xamarin/Xamarin.Forms/files/5427420/DatePickerTest.zip)

**Comment by rmarinho** [comment]
Hey, this doesn't seem to be related with Forms you need to update your custom renderer to iOS14.

you can add this or cehck or code on 4.8.0 

```
 this.picker = new UIDatePicker { Mode = UIDatePickerMode.Date };
 if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
 {
         this.picker.PreferredDatePickerStyle = UIKit.UIDatePickerStyle.Wheels;
  }
```
