### ISSUE TITLE
xamarin and html mixed ui

### ISSUE THREAD

**Issue by HeMinzhang** [xamarin/Xamarin.Forms#12591]
The core of the embedded browser in xamarin, you can use javascript, typescript, css, html to design ui, c# is responsible for the logic and the bottom of the framework

## Summary
Please provide a brief summary of your proposal. Two to three sentences is best here.

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

e.g.

In order to facilitate the new Shiny Button api, a bool is added to the Button class. This is done as a bool because it is simpler to data bind and other reasons...

    var button = new Button ();
    button.MakeShiny = true; // new API

The MakeShiny API works even if the button is already visible.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by PureWeen** [comment]
@HeMinzhang I don't quite follow what you're requesting here

Are you looking for something like this?
https://devblogs.microsoft.com/aspnet/mobile-blazor-bindings-experiment/

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
