### ISSUE TITLE
[Bug] Merged dictionary indexing operator can't find merged data, but TryGetValue can

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12592]
Hi.

1) Set up a merged dictionary such as
```xaml
<ResourceDictionary.MergedDictionaries>
    <ResourceDictionary Source="SomeDictionary.xaml" />
</ResourceDictionary.MergedDictionaries>
```
2) Try to access a value that resides in SomeDictionary.xaml via
```c#
var hasValue = Resources.TryGetValue("SomeValueInSomeDictionary", out object someValue);
```
This succeeds.
3) Now try to access the same property via the indexing operator:
```c#
var someValue = Resources["SomeValueInSomeDictionary"];
```
This throws a key not found exception.

---

Workaround 1:
Always use TryGetValue instead of the indexing operator.

Workaround 2:
There is another permutation where the indexing operator does work:
1) Set up a merged dictionary such as
```xaml
<ResourceDictionary.MergedDictionaries>
    <local:SomeDictionary />
</ResourceDictionary.MergedDictionaries>
```
2) Now the indexing operator works:
```c#
var someValue = Resources["SomeValueInSomeDictionary"];
```

All of this is highly unexpected and certainly a bug, no?

---

Question 1: Is there a performance difference between using `<local:SomeDictionary />` and `<ResourceDictionary Source="SomeDictionary.xaml" />`?

The debugger shows that when using `<local:SomeDictionary />` the merged dictionary entry's Keys and Values are populated in the debugger, while they are not when using `<ResourceDictionary Source="SomeDictionary.xaml" />`.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#merged-resource-dictionaries says 
"This syntax does not instantiate the MyResourceDictionary class. Instead, it references the XAML file" regarding `<ResourceDictionary Source="SomeDictionary.xaml" />` syntax. What does 'reference' mean in this context? Will XAML compilation even take place with resource dictionary files without a code-behind?

Question 2: How does an implicit style merged resource dictionary factor in on this -- should it be the last file merged in (ie the first to be searched), or is implicit styling handled as a special case as they don't have keys (in which case it should be the first dictionary to merge in)?

Complaint: A lot of MS documentation says that multiple merged dictionaries is bad for performance. Why is it even called a merged dictionary if the contents aren't really merged, but multiple searches are performed? Why do we have to choose between having one large resource file, or worse performance by splitting it up?

Thanks for answers to my questions too.

---
XF 5-pre3, iOS (didn't test on Android).

**Comment by StephaneDelcroix** [comment]
This was a design choice, and we can't revert it at this time (but maybe for forms 6).

**Comment by Tommigun1980** [comment]
> This was a design choice, and we can't revert it at this time (but maybe for forms 6).

Hi @StephaneDelcroix and thanks for the info!

Which part do you mean was a design choice, that the indexing operator doesn’t work with dictionaries without code-behind? If so, is there a performance difference between the two variants?

Also is there any chance you could answer the two question I had in the report? That information is not available in the documents.

Thanks so much!

**Comment by Tommigun1980** [comment]
@jsuarezruiz Maybe you can help me with the questions? I tried looking everywhere but I don't think it's documented.

**Comment by Tommigun1980** [comment]
@StephaneDelcroix Wouldn't the following be backwards compatible:
Have only one dictionary internally, a true merged dictionary.
Its values would be a 'object value, string sourceDictionary, bool isMerged'.
(Duplicate keys would overwrite existing values, with last-in-wins).
The indexing operator and TryGetValue would return the .value property, so this would be transparent to the user.

When unloading a merged dictionary, it does have information about what to do.

Now everything would be in one dictionary with one lookup only, greatly enhancing styling performance.
This would also fix the discrepancy between the indexing operator and TryGetValue.

**Comment by Tommigun1980** [comment]
@StephaneDelcroix Could you please at least answer if there's a performance difference between the two annotations, and where implicit styles should be merged for optimal performance? Please, it is not documented anywhere.
