### ISSUE TITLE
[Bug] Creating AlertDialog.Builder or Dialog returns Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Monah84** [xamarin/Xamarin.Forms#12595]
### Description
I am trying to build a pop-up page. I created the interface in the common project. Then, I created the implementation in the android project. I called the pop-up using the dependency service. iOS working fine and the pop-up shows correctly. But, in Android project. It seems that there is a bug.

### Steps to Reproduce

```
// this in the common project
public IPopupService
{
      void Show(ContentPage page);
      void Hide();
}

// the implementation of the interface in the Android project
[assembly: Dependency(typeof(PopupService))]

public class PopupService: IPopupService
{
        private Android.Views.View nativeView;
        private Dialog dialog;
        public Show(ContentPage page)
        {
                var context = Android.App.Application.Context;  
                var builder = new AlertDialog.Builder(context);
                dialog = builder.Create(); //new Dialog(context);  <=== here i see in the output window the error mentioned below
                dialog.RequestWindowFeature((int)WindowFeatures.NoTitle);
                //  ... the code
        }

        public void Hide()=>dialog.Hide();
}
```

### Error

> Object reference not set to an instance of an object.10-25 13:07:41.928 I/mono-stdout( 6720): Object reference not set to an instance of an object.
> 
> System.InvalidCastException: Unable to cast object of type 'System.RuntimeType' to type 'Mono.Debugger.Soft.TypeMirror'.
>    at Mono.Debugging.Soft.SoftDebuggerAdaptor.IsGenericType(EvaluationContext ctx, Object type) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 1605
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 946
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitAsExpression(AsExpression asExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 596
>    at ICSharpCode.NRefactory.CSharp.AsExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\AsExpression.cs:line 69
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitParenthesizedExpression(ParenthesizedExpression parenthesizedExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1092
>    at ICSharpCode.NRefactory.CSharp.ParenthesizedExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\ParenthesizedExpression.cs:line 63
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 83
>    at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1416
> System.InvalidCastException: Unable to cast object of type 'System.RuntimeType' to type 'Mono.Debugger.Soft.TypeMirror'.
>    at Mono.Debugging.Soft.SoftDebuggerAdaptor.IsGenericType(EvaluationContext ctx, Object type) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 1605
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 946
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitAsExpression(AsExpression asExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 596
>    at ICSharpCode.NRefactory.CSharp.AsExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\AsExpression.cs:line 69
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitParenthesizedExpression(ParenthesizedExpression parenthesizedExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1092
>    at ICSharpCode.NRefactory.CSharp.ParenthesizedExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\ParenthesizedExpression.cs:line 63
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 83
>    at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1416
> System.InvalidCastException: Unable to cast object of type 'System.RuntimeType' to type 'Mono.Debugger.Soft.TypeMirror'.
>    at Mono.Debugging.Soft.SoftDebuggerAdaptor.IsGenericType(EvaluationContext ctx, Object type) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 1605
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 946
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitAsExpression(AsExpression asExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 596
>    at ICSharpCode.NRefactory.CSharp.AsExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\AsExpression.cs:line 69
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitParenthesizedExpression(ParenthesizedExpression parenthesizedExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1092
>    at ICSharpCode.NRefactory.CSharp.ParenthesizedExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\ParenthesizedExpression.cs:line 63
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 83
>    at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1416
> System.InvalidCastException: Unable to cast object of type 'System.RuntimeType' to type 'Mono.Debugger.Soft.TypeMirror'.
>    at Mono.Debugging.Soft.SoftDebuggerAdaptor.IsGenericType(EvaluationContext ctx, Object type) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 1605
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 946
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitAsExpression(AsExpression asExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 596
>    at ICSharpCode.NRefactory.CSharp.AsExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\AsExpression.cs:line 69
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitParenthesizedExpression(ParenthesizedExpression parenthesizedExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 1092
>    at ICSharpCode.NRefactory.CSharp.ParenthesizedExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\ParenthesizedExpression.cs:line 63
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluatorVisitor.VisitInvocationExpression(InvocationExpression invocationExpression) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluatorVisitor.cs:line 896
>    at ICSharpCode.NRefactory.CSharp.InvocationExpression.AcceptVisitor[T](IAstVisitor`1 visitor) in C:\A\vs2017mb-00002M-1\_work\144\s\external\NRefactory\ICSharpCode.NRefactory.CSharp\Ast\Expressions\InvocationExpression.cs:line 60
>    at Mono.Debugging.Evaluation.NRefactoryExpressionEvaluator.Evaluate(EvaluationContext ctx, String expression, Object expectedType) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\NRefactoryExpressionEvaluator.cs:line 83
>    at Mono.Debugging.Evaluation.ObjectValueAdaptor.GetExpressionValue(EvaluationContext ctx, String exp) in C:\A\vs2017mb-00002M-1\_work\144\s\external\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\ObjectValueAdaptor.cs:line 1416
> 

### Basic Information

- Version with issue: Xamarin.Forms v4.8.1560
- IDE: Visual Studio
- Affected Devices: Android

**Comment by PureWeen** [comment]
@Monah84 can you attach a repro please?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
