### ISSUE TITLE
[Enhancement] Add VisualElement.Name property

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#12608]
## Summary
Add support for getting element name matching x:Name in XAML, e.g. <Label x:Name='MyLabel'/>. So that Hot Reload can display it in Live Visual Tree (and thus users can search for named elements there). 

## API Changes
Add VisualElement.Name property as a first class citizen.

**Comment by StephaneDelcroix** [comment]
> Add VisualElement.Name property as a first class citizen.

or a Namescope method
