### ISSUE TITLE
It doesn't work at all. 

### ISSUE THREAD

**Issue by CarlinhaCamargo** [xamarin/Xamarin.Forms#12606]
neither ios or android version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd1d5949-4dfa-a56a-1fc9-6b6486572b4f
* Version Independent ID: 514ecd14-d006-f7fd-98cf-4195951cc5da
* Content: [WebView.Reload Method (Xamarin.Forms)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webview.reload?view=xamarin-forms#feedback)
* Content Source: [docs/Xamarin.Forms/WebView.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/WebView.xml)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by hartez** [comment]
@CarlinhaCamargo I've attempted to reproduce this issue, but the Reload method seems to be working fine. My repro attempt it attached. Can you tell me if I'm missing a detail? 
 
[_12606 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5439934/_12606.Repro.zip)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
