### ISSUE TITLE
Is Xamarin ready on Linux?

### ISSUE THREAD

**Issue by UltraBurstXD** [xamarin/Xamarin.Forms#12604]
Hi,
I'm migrating from Java to C#, and I'd want to know if Xamarin on linux is production ready.

**Comment by amirvenus** [comment]
No, it's not!

The GTK is in Preview since day dot so perhaps you can create a test project and see what does not work as expected and create an Issue for each bug/lack of feature so that it can get some attention. 

I heard from @davidortinau that GTK will not be a priority in MAUI

**Comment by PureWeen** [comment]
Currently GTK is community supported. If you have specific issues please log them so we can be aware and address
