### ISSUE TITLE
[Bug] [Android] System.NotSupportedException: Unable to activate instance of type MyApp.Droid.Renderers.MyTimePickerRenderer from native handle

### ISSUE THREAD

**Issue by zleao** [xamarin/Xamarin.Forms#12605]
### Description
Android app is crashing when trying to use a TimePicker. It crashes after I try confirm the time selection.
The crash is happening if the `TimePicker` control is disposed while the `TimePickerDialog` is being shown. It looks like the disposing of the `TimePicker` control is not forcing the `TimePickerDialog` to be hidden.

A similar [issue](https://github.com/xamarin/Xamarin.Forms/issues/12044) has been reported but is was closed due to insuficient info.

### Steps to Reproduce
I've created a simple repo that reproduces the described error. You can run the app and follow the instructions.
In a generic way the stesp are:

1. Tap a `TimePicker` to bring forward the dialog to select time;
2. Trigger a dispose of the `TimePicker` control, while the dialog is still visible (this needs to be done in code);
3. Try to set the time, by pressing the 'OK' button in the `TimePickerDialog`
.
### Expected Behavior
I would expect the `TimePicker.Dispose` to ensure the `TimePickerDialog` is hidden

### Actual Behavior
The `TimePickerDialog` is not forcibly hiden when disposing the `TImePicker` and this can lead to a crash in the app

### Basic Information

- Version with issue: 4.8.0.1560
- IDE: VS2019 16.7.6
- Platform Target Frameworks: 
  - Android: 9

### Reproduction Link

[https://github.com/zleao/TimePickerActivationException](https://github.com/zleao/TimePickerActivationException)

### Workaround

The [sample repository](https://github.com/zleao/TimePickerActivationException) I provided to reproduce this behaviour, also has the workaround for this issue...
Before disposing the control (in the renderer) we need to make sure the TimePickerDialog is hidden (see code below):

```
[assembly: ExportRenderer(typeof(MyTimePicker), typeof(MyTimePickerRenderer))]
...
public class MyTimePickerRenderer : TimePickerRenderer
{
        ...

        TimePickerDialog _dialog = null;

        protected override TimePickerDialog CreateTimePickerDialog(int hours, int minutes)
        {
            return _dialog = base.CreateTimePickerDialog(hours, minutes);
        }

        protected override void Dispose(bool disposing)
        {
            if (_dialog != null && _dialog.IsShowing)
            {
                _dialog.Hide();
            }

            base.Dispose(disposing);
        }
        ...
}
```

**Comment by PureWeen** [comment]
@zleao you can't remove the TimePicker from the visual tree while it's still open. This causes the renderer to dispose of the dialog because it's been removed from the visual tree. Once the dialog is closed the listener that's past into the created dialog tries to fire a callback event on that disposed of dialog

You'll need to wait until the dialog is closed or create your own dialog that doesn't use a listener
