### ISSUE TITLE
[Bug] Editor: AutoSize="TextChanges" does nothing

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12618]
Hi.

AutoSize="TextChanges" does not seem to do anything on an Editor component. I do not have a height request set, and it never seems to adjust the number of lines to the content.

Please see the following video of the issue:
https://drive.google.com/file/d/1hkBbbnuTRnOpNklzexZrbS2hxSUTKZ4k/view?usp=sharing

The behaviour I am expecting is that it should start out with one line, and grow as I type. It always stays at four lines and doesn't shrink or grown and AutoSize="TextChanges" does not seem to do anything. As you can see, after the fourth line has been written it also doesn't automatically scroll to reveal what I keep typing, which is also what I would expect.

Bonus request: It would be really nice if you could define max number of lines (in my chat input case I'd like to cap it at five lines or so).

This is the XAML I used:
```xaml
                <Editor
                    Grid.Column="0"
                    x:Name="messageEntry"
                    AutoSize="TextChanges"
                    MaxLength="{Static shared:SharedConstants+MaxStringLength.ChatMessage}" />
```

XF 5-pre3, iOS (didn't test on other platforms).

**Comment by PureWeen** [comment]
Can you attach a repro?

I tested with the following XAML and it works fine

```xaml
<ContentPage.Content>
        <Grid Background="Purple">
            <Grid.RowDefinitions>
                <RowDefinition Height="*"></RowDefinition>
                <RowDefinition Height="Auto"></RowDefinition>
            </Grid.RowDefinitions>
             <Editor Background="Yellow"
                    Grid.Column="0"
                    AutoSize="TextChanges" />
            <Editor Background="Yellow"
                    Grid.Row="1"
                    AutoSize="TextChanges" />
        </Grid>
    </ContentPage.Content>
```

**Comment by Tommigun1980** [comment]
> Can you attach a repro?
> 
> I tested with the following XAML and it works fine
> 
> ```
> <ContentPage.Content>
>         <Grid Background="Purple">
>             <Grid.RowDefinitions>
>                 <RowDefinition Height="*"></RowDefinition>
>                 <RowDefinition Height="Auto"></RowDefinition>
>             </Grid.RowDefinitions>
>              <Editor Background="Yellow"
>                     Grid.Column="0"
>                     AutoSize="TextChanges" />
>             <Editor Background="Yellow"
>                     Grid.Row="1"
>                     AutoSize="TextChanges" />
>         </Grid>
>     </ContentPage.Content>
> ```

Hi @PureWeen.

I tried your example and it looks like this:
<img width="433" alt="Screenshot 2020-10-28 at 23 50 53" src="https://user-images.githubusercontent.com/60286968/97500558-7c78e600-1978-11eb-9661-88b7b2aeee5a.png">

AutoSize="TextChanges" does absolutely nothing. It has never ever worked for me and based on Googling a lot of other people too. Shouldn't it resize the Editor rows to fit the content?

**Comment by Tommigun1980** [comment]
Maybe this is a follow-up issue but as you can see in the video I sent 9 seconds in, the editor should scroll the text, but I have to type one more line before it scrolls. So once the typed text reaches the editor's borders you are effectively typing blind.

**Comment by Tommigun1980** [comment]
Hi @PureWeen, I'd really like to know what could be different if the repro case works properly for you. I need to use a resizing editor for chat message input so is there anything I can do to help here? As I said just running the repro exposes the problem for me so I'd like to know what could be different.
Thanks.

**Comment by PureWeen** [comment]
![2020-11-01_12-46-27](https://user-images.githubusercontent.com/5375137/97811459-60a76580-1c40-11eb-997a-6dcf2effd5dc.gif)

I'm not sure.. It sizes for me here just fine

A repro and more info about the devices you are testing would help

**Comment by PureWeen** [comment]
Please post any of your findings over here

https://github.com/xamarin/Xamarin.Forms/issues/10406

**Comment by Tommigun1980** [comment]
> ![2020-11-01_12-46-27](https://user-images.githubusercontent.com/5375137/97811459-60a76580-1c40-11eb-997a-6dcf2effd5dc.gif) [ ![2020-11-01_12-46-27](https://user-images.githubusercontent.com/5375137/97811459-60a76580-1c40-11eb-997a-6dcf2effd5dc.gif) ](https://user-images.githubusercontent.com/5375137/97811459-60a76580-1c40-11eb-997a-6dcf2effd5dc.gif) [ ](https://user-images.githubusercontent.com/5375137/97811459-60a76580-1c40-11eb-997a-6dcf2effd5dc.gif)
> 
> I'm not sure.. It sizes for me here just fine
> 
> A repro and more info about the devices you are testing would help

And it doesn't for me, as I posted a screenshot of. I literally downloaded your repro project and it doesn't work.

I don't think an answer of "It sizes for me here just fine" is adequate as there clearly is an issue -- tons of people are complaining and your **repro project does not work for me**, I even posted screenshots of it. I don't think an answer of "it works on my device" is adequate when people are posting screenshots of the repro project not working.
