### ISSUE TITLE
[Bug] Hot reload: FlexLayout doesn't refresh

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12616]
Hi.

Hot reloading changes to a flex layout, or changes to its data template do nothing. The page in the simulator does reload but the flex layout and its children are unaffected. This makes iterating flex layouts quite slow.

Thanks.

XF 5-pre3, iOS (didn't test other platforms).

> VS bug [#1239387](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1239387)

**Comment by PureWeen** [comment]
@Tommigun1980 do you have full  page or incremental set?

![image](https://user-images.githubusercontent.com/5375137/97363541-bced3c80-1870-11eb-95e8-d1ba11211d50.png)

**Comment by PureWeen** [comment]
Or can you give an example of your XAML and what you are changing? I did a few tests with FlexLayout and it is working for me. I tested changes to the DataTemplate

**Comment by Tommigun1980** [comment]
Hi @PureWeen.

I have the default turned on, ie entire page.

The flex layout is inside a modally pushed page. All other changes are propagated, except to the ones to a flex layout.

**Comment by Tommigun1980** [comment]
> Or can you give an example of your XAML and what you are changing? I did a few tests with FlexLayout and it is working for me. I tested changes to the DataTemplate

Did you test with BindingContext coming from a binding btw?

**Comment by Tommigun1980** [comment]
Hi @PureWeen. Were you able to reproduce the issue in your repro case when using bindings instead of inline data?
Thanks.

**Comment by jsuarezruiz** [comment]
I have created a sample using Xamarin.Forms a BindableLayout with FlexLayout:

[Issue12616.zip](https://github.com/xamarin/Xamarin.Forms/files/5545941/Issue12616.zip)

![issue126162](https://user-images.githubusercontent.com/6755973/99248499-d4cd3600-2808-11eb-980f-0c35915a89e5.gif)

**Comment by Tommigun1980** [comment]
Hi @jsuarezruiz and thanks for the template -- I am copying in one thing at a time into it to find out exactly what causes it.

While I was doing that I may have accidentally stumbled upon additional information for issue https://github.com/xamarin/Xamarin.Forms/issues/12675#issuecomment-729643839. I am not sure if this is the same issue (as that one is a CollectionView inside a RefreshView) but I am documenting this in case it's relevant and related, so feel free to ignore if this is not useful:

Expected:
<img width="560" alt="Screenshot 2020-11-19 at 23 25 38" src="https://user-images.githubusercontent.com/60286968/99726155-cf007a80-2abe-11eb-8bc7-ec67f58ed4f6.png">

Actual:
<img width="560" alt="Screenshot 2020-11-19 at 23 25 41" src="https://user-images.githubusercontent.com/60286968/99726167-d45dc500-2abe-11eb-94c4-39a48d299247.png">

Modified sample that shows the vertically capped layout:
[Issue12616_CappedHeight.zip](https://github.com/xamarin/Xamarin.Forms/files/5569831/Issue12616_CappedHeight.zip)

Removing the scroll view makes it draw fully.

**Comment by jsuarezruiz** [comment]
@Tommigun1980 Thanks for report this issue: https://github.com/xamarin/Xamarin.Forms/issues/12616#issuecomment-730648732 Maybe, to maintain traceability we should create a specific issue (seems to be different from this one or even 12675).

As for the problem with Hot Reload, do you keep reproducing the problem with the latest versions? If so, could you attach an example? Otherwise, do we modify this issue to validate https://github.com/xamarin/Xamarin.Forms/issues/12616#issuecomment-730648732?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
