### ISSUE TITLE
[Enhancement] initiate a drag with a short press

### ISSUE THREAD

**Issue by ricavir11** [xamarin/Xamarin.Forms#12627]
## Summary
Improving drag & drop feature : be able to initiate a drag with a short press

## API Changes
Adding a property like "DragMode" with following values :
- short press
- long press

## Intended Use Case
While ewperimenting drag & drop feature I noticed that end users didn't found the way to start dragging an element.
They systematicaly try to press shortly the element and dragging immediately. 
Current drag & drop implementation is then very limited in terms of UX.

**Comment by faridseifi** [comment]
Is this still under consideration since a year ago? It is a nice feature to have

**Comment by faridseifi** [comment]
> Is this still under consideration since a year ago? It is a nice feature to have

After lots of try and error I found the following article which uses PanGestureRecognizer and TranslateTo to implement a short press drag and drop. It works perfect in Android and iOS.
 
https://blog.francois.raminosona.com/drag-and-drop-in-xamarin-forms/

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
