### ISSUE TITLE
SignalR not working

### ISSUE THREAD

**Issue by rikun5989** [xamarin/Xamarin.Forms#12625]
### Description
When I initialize HubConnection in xamarin form it gives me error:

Can not resolve reference: `Microsoft.AspNetCore.SignalR.Client.Core`, referenced by `ProjectName`. Please add a NuGet package or assembly reference for `Microsoft.AspNetCore.SignalR.Client.Core`, or remove the reference to `ProjectName`.
### Steps to Reproduce

1. Create new cross plateform project: add Microsoft.AspNetCore.SignalR.Client to all project.
2. Open App.xaml.cs file and create HubConnect with instance name. add required namespace
3. start debug for android.

### Basic Information

- Version with issue: microsoft visual studio 2017 lattest version
- Last known good version: none
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Microsoft.AspNetCore.SignalR.Client
- Affected Devices:

**Comment by marius-bughiu** [comment]
Hmm, I don't have VS2017, but I just now created an app from scratch and - at least with VS2019 - it seems to work. Would you mind giving it a try? - https://github.com/StartDebugging/xamarin-forms-signalr-chat. The SignalR service is already deployed so all you need to do is run two of the client apps (I tested with UWP and Android), click the `Connect` button and then send messages.

**Comment by PureWeen** [comment]
https://github.com/mono/mono/issues/11731#issuecomment-439664488

**Comment by rikun5989** [comment]
> Hmm, I don't have VS2017, but I just now created an app from scratch and - at least with VS2019 - it seems to work. Would you mind giving it a try? - https://github.com/StartDebugging/xamarin-forms-signalr-chat. The SignalR service is already deployed so all you need to do is run two of the client apps (I tested with UWP and Android), click the `Connect` button and then send messages.

There might be some problem in visual studio 2017 with xamarin project. Howevevr it works fine in Visual studio 2019.
I try to run your project in 2017 but same problem occured, but it works fine in 2019.
