### ISSUE TITLE
[Bug] iOS - CollectionView MeasureAll fails with a heterogeneous item source

### ISSUE THREAD

**Issue by WanftMoon** [xamarin/Xamarin.Forms#12626]
### Description
When setting the ItemsSource of a CollectionView with an heterogeneous list (int, datetime and string for example), CollectionView Fails on iOS to MeasureAllItems and resize the cell accordingly.
<img width="835" alt="Screen Shot 2020-10-27 at 10 27 11" src="https://user-images.githubusercontent.com/20956737/97307860-fc9b3080-183e-11eb-8466-17d558f845c1.png">

### Steps to Reproduce

1.  Create a collectionView with the SizingStrategy MeasureAllItems and set the ItemsSource to a list like below: 
` <x:Array Type="{x:Type x:Object}">
                        <sys:DateTime>2001-12-01</sys:DateTime>
                        <sys:DateTime>2006-06-21</sys:DateTime>
                        <sys:Int32>98</sys:Int32>
                        <sys:String>Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon Baboon</sys:String>
                        <sys:String>Goodbye</sys:String>
                        <sys:Int32>98</sys:Int32>
                        <sys:String>Baboon </sys:String>
                        <sys:Int32>98</sys:Int32>
                    </x:Array>`
2. Set the datatemplate
`<DataTemplate>
        <Label Text="{Binding .}" />
</DataTemplate>`

3. Run it on iOS and Android.

### Expected Behavior

The item to be of the correct size

### Actual Behavior

On Android, the it behaves correct.
On iOS, the list will keep the height of the greater item, after it is rendered

![Screenshot_1603804947](https://user-images.githubusercontent.com/20956737/97308496-b0042500-183f-11eb-8826-4f9ef968613b.png)
![Simulator Screen Shot - iPhone 8 - 2020-10-27 at 10 31 56](https://user-images.githubusercontent.com/20956737/97308502-b1355200-183f-11eb-842c-45cb5691c7f5.png)

### Basic Information

- Version with issue: XF 4.8.0.1560
- Last known good version: NA
- IDE: Visual Studio For mac
- Platform Target Frameworks: 
  - iOS: 14.1
  - Android: 9.0
- Nuget Packages:
<img width="214" alt="Screen Shot 2020-10-27 at 10 33 56" src="https://user-images.githubusercontent.com/20956737/97308703-ed68b280-183f-11eb-8b39-f9ca532cf27a.png">

- Affected Devices: iOS

### Screenshots

![Screenshot_1603804947](https://user-images.githubusercontent.com/20956737/97308746-f8234780-183f-11eb-8f0b-c9cc7ed10984.png)
![Simulator Screen Shot - iPhone 8 - 2020-10-27 at 10 31 56](https://user-images.githubusercontent.com/20956737/97308752-f9547480-183f-11eb-8efa-17d3139c0a76.png)

### Reproduction Link

[CollectionViewMeasureAll.zip](https://github.com/xamarin/Xamarin.Forms/files/5445638/CollectionViewMeasureAll.zip)

### Workaround

Don't use heterogeneous item source for now

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/12626

**Comment by WanftMoon** [comment]
@PureWeen can you link the duplicate?

**Comment by WanftMoon** [comment]
@PureWeen @samhouts 
Can you link the duplicate issue?

**Comment by PureWeen** [comment]
It's the number after "Duplicate" https://github.com/xamarin/Xamarin.Forms/issues/12626  that's a clickable link

**Comment by WanftMoon** [comment]
@PureWeen @samhouts 
Just to make sure, this issue is #12626. Why would it be a duplicate from itself?

**Comment by PureWeen** [comment]
Apologies @WanftMoon I meant to link
https://github.com/xamarin/Xamarin.Forms/issues/11011

There are a number of issues logged against MeasureAll 

https://github.com/xamarin/Xamarin.Forms/issues/12622
https://github.com/xamarin/Xamarin.Forms/issues/11511

So just trying to consolidate

**Comment by WanftMoon** [comment]
ty, will follow those issues!

best regards.
