### ISSUE TITLE
[Bug] [Android] Xamarin.Forms.Device.Idiom and Xamarin.Essentials.DeviceInfo.Idiom return idiom phone when on tablet device screen zoom is increased

### ISSUE THREAD

**Issue by maexsp** [xamarin/Xamarin.Forms#12624]
### Description
When checking in Xamarin.Forms Android MainActivity within OnCreate method on a Tablet Device the actual device info it returns incorrect enum TargetIdiom.Phone when Android system settings screen zoom is equal or above 75%. 

### Steps to Reproduce

1.  Open Android system settings. Change "Screen zoom" setting to 75% or higher.
2.  Start your Android App.
3.  Xamarin.Essentials.DeviceInfo.Idiom and/or Xamarin.Forms.Device.Idiom will return "Phone" instead of "Tablet".

### Expected Behavior
Xamarin.Essentials.DeviceInfo.Idiom should return DeviceIdiom.Tablet
Xamarin.Forms.Device.Idiom == TargetIdiom.Phone sould return TargetIdiom.Tablet

### Actual Behavior
Return "Phone"

### Basic Information

- Version with issue: XF 4.7.0.1351
- IDE: VS2019 
- Platform Target Frameworks:
    - Android: Target Framework Android 10.0 (Q), API Level 29
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Test device -> Samsung SM-T865

### Screenshots
4.7.0.1351
![grafik](https://user-images.githubusercontent.com/15746917/97303482-bbb11500-185a-11eb-88f6-42bf503627cc.png)

**Comment by GalaxiaGuy** [comment]
A quick check online reveals this discussion:

https://www.reddit.com/r/androiddev/comments/80y795/how_to_programmatically_check_if_user_has/

It might be fixable by checking the following in the Android idiom code:

```csharp
DisplayMetrics.DensityDeviceStable
```

That is only available in API 24 or higher though.

**Comment by PureWeen** [comment]
Are you seeing the issue with the following repro?

[Issue12624.zip](https://github.com/xamarin/Xamarin.Forms/files/5469427/Issue12624.zip)

I tested on my S9 and even when it's all the way turned up I still just get "Phone"

Maybe it's an older Samsung device issue?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by maexsp** [comment]
@PureWeen The issue is still there. Your zip solution was not running on my VS2019. I commited a full repo for you. By the way, you have to use a tablet to reproduce! Your S9 is a phone. 
The Samsung tablet I used was a Samsung SM-T865 (about 1 year old). But the issue is also reproducable on most tablet emulators.
See my repo: https://github.com/maexsp/XamarinFormAndroidIdiom

**Comment by maexsp** [comment]
@Redth Hi Jonathan. The issue still exists. Custom repo to check the issue can be found in the following demo. 
Main problem: Device.Idiom return Type "Phone" although it is a tablet! Same issue on emulator and on Samsung tablet. Be sure to kill and restart the App once the display settings have changed in the system settings! 

https://github.com/maexsp/XamarinFormAndroidIdiom

Emulator settings to reproduce:
![grafik](https://user-images.githubusercontent.com/15746917/100922445-2dc1ed00-34de-11eb-883e-72eaa368bf3d.png)

Screener:
![idiomscreener](https://user-images.githubusercontent.com/15746917/100922790-990bbf00-34de-11eb-99d0-f258260b558c.gif)
