### ISSUE TITLE
ExportFont requires app uninstall in order to show new Glyphs. (Android)

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Xamarin.Forms#12630]
### Description
When using the Embedded fonts with the [ExportFont] option, when a new Glyph is added, the new font file is not installed with the updated app on the user's device unless the previous version of the app is uninstalled first.

(I am generating an aab)

### Steps to Reproduce

Create an app with an embedded font and display some glyphs on a Page.
Install on an Android device.
Update the embedded font file and add a new Glyph and show it on the page.
Rebuild the app and reinstall on the same device. Either through Visual Studio or through Google Play.

### Expected Behavior
The new glyph should show

### Actual Behavior
Glyph is not displayed unless the app is uninstalled and  installed again.

### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: Unknown
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 9.0

### Workaround

Users must first uninstall the previous version of the app.

**Comment by AlleSchonWeg** [comment]
I reported the same issue: https://github.com/xamarin/Xamarin.Forms/issues/11843

**Comment by PureWeen** [comment]
Closing as duplicate
