### ISSUE TITLE
[Bug] Build failures showing already fixed errors issue is back

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12649]
Hi.

This issue was fixed but is back, namely that whenever you have had any XAML errors and tried to build, then fix say one four errors and build again, VS still shows all the errors you have already fixed. Only a restart of VS seems to help.

XF 5-pre3, VS For Mac 8.8 Preview (this happened also with latest stable).

**Comment by PureWeen** [comment]
@Tommigun1980 can you supply a repro or at least a video so we can have some added context?

**Comment by Tommigun1980** [comment]
Hi. I will take a video soon and post it here. I also just noticed that even when a build is successful it will show any errors I've had during the session, so they are not just shown when a build fails. But I'll get back to this soon.

Thanks.

**Comment by Tommigun1980** [comment]
Shoot. I restarted VS and now it doesn't happen anymore, so presumably it's some condition that needs to be fulfilled for it to trigger. I have had the error happen constantly for two days, so my guess is once it starts to happen it will persist until VS is restarted. I will take a video the next time it happens and gather the VS logs etc.

**Comment by Redth** [comment]
Thanks, please reopen if you end up finding more information on this one.
