### ISSUE TITLE
[Bug] Unnecessary XF build warning after updating VS to 8.8 Preview

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12644]
After updating VS For Mac to 8.8 Preview build 2899 making iOS builds gives the following warnings:

```
/Users/myname/.nuget/packages/xamarin.forms/5.0.0.1558-pre3/buildTransitive/Xamarin.Forms.targets(198,5): warning : Xamarin.Forms recommends TargetPlatformMinVersion >= 10.0.14393.0 (current project is -1)
/Users/myname/.nuget/packages/xamarin.forms/5.0.0.1558-pre3/buildTransitive/Xamarin.Forms.targets(207,5): warning : Xamarin.Forms recommends TargetPlatformVersion >= 10.0.14393.0 (current project is -1)
```

I am not targeting UWP at all. Xamarin.Forms.Targets seems to try to exclude UWP when there is no project with  `Condition="'$(TargetPlatformVersion)' != '' and '$(TargetPlatformMinVersion)' != ''"`, but it is somehow still printed.

Thanks.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/12611
