### ISSUE TITLE
[Bug] Argument out of range CollectionView iOS

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Xamarin.Forms#12656]
I have CollectionView with horizontal linear layout

![image](https://user-images.githubusercontent.com/23138430/97585866-44b68080-1a02-11eb-9da9-23f2f1c17ec3.png)

and when i add footer to collection view it throws exception mentioned in title. only in ios.

![image](https://user-images.githubusercontent.com/23138430/97586592-1c7b5180-1a03-11eb-92f3-12f5460ff02f.png)

Xamarin forms version is 4.8.0.1560

![image](https://user-images.githubusercontent.com/23138430/97586303-c73f4000-1a02-11eb-9898-852ba7081973.png)

![image](https://user-images.githubusercontent.com/23138430/97586428-edfd7680-1a02-11eb-8d3a-bced9d454d82.png)

when i change footer to header or remove footer it works well.

It worked before the last update of xam forms

**Comment by PureWeen** [comment]
@Alex-Dobrynin can you add a repro please? That exception looks like there's a bug with inflating the MainPage and setting the Root View Controller on your app. I suspect there's an error with your XAML that's causing the page to throw an exception on creation.

Can you enable First Chance Exceptions? That might reveal a better exception message as well?

**Comment by Alex-Dobrynin** [comment]
it does not matter what xaml code i have in my app. if i remove footer of collection view or make vertical layout it works, so i make conclusion that the problem is in CollectionView`s footer within horizontal layout, code of that footer i placed above.

**Comment by PureWeen** [comment]
I tested with the following code and it's working fine for me without any exceptions

```XAML
<CollectionView x:Name="cv" Header="{Binding .}" Footer="{Binding .}">
        <CollectionView.ItemsLayout>
            <LinearItemsLayout ItemSpacing="0" Orientation="Horizontal"></LinearItemsLayout>
        </CollectionView.ItemsLayout>
        <CollectionView.HeaderTemplate>
            <DataTemplate>
                <StackLayout  HeightRequest="300">
                    <Label TextColor="Black" Text="Header"></Label>
                </StackLayout>
            </DataTemplate>
        </CollectionView.HeaderTemplate>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <StackLayout  HeightRequest="300">
                    <Label TextColor="Black"  Text="Content"></Label>
                </StackLayout>
            </DataTemplate>
        </CollectionView.ItemTemplate>
        <CollectionView.FooterTemplate>
            <DataTemplate>
                <StackLayout  HeightRequest="300">
                    <Label TextColor="Black" Text="Header"></Label>
                </StackLayout>
            </DataTemplate>
        </CollectionView.FooterTemplate>
    </CollectionView>
```

**Comment by Alex-Dobrynin** [comment]
ok, i`ve investigated this question more deeper.

it does not work within horizontal layout when i do next

![image](https://user-images.githubusercontent.com/23138430/97692071-f22f9f80-1aa7-11eb-914c-d3fca301653b.png)

but when i do this: 

![image](https://user-images.githubusercontent.com/23138430/97692365-59e5ea80-1aa8-11eb-9b88-94301161f2a2.png)

it works well.

So, as you can see it does not work within horizontal layout when I reinstantiate the collection. but when i clear it and add items it works. But, i need exactly first approach with reinstantiate entire collection.

Here is my xaml code:

![image](https://user-images.githubusercontent.com/23138430/97693065-42f3c800-1aa9-11eb-94f0-4199f7ce859d.png)

Also, a bit of magic, yesterday it worked when i changed footer to header, but today header also crashes

**Comment by PureWeen** [comment]
@Alex-Dobrynin can you modify this sample so it crashes in the way that you are seeing?

[Issue12656.zip](https://github.com/xamarin/Xamarin.Forms/files/5467915/Issue12656.zip)

**Comment by xamiell** [comment]
Having the exactly problem!
So many problems I have with Xamarin.Forms.

**Comment by Redth** [comment]
Is anyone able to modify the sample @PureWeen posted to reproduce the issue?

**Comment by Alex-Dobrynin** [comment]
Unfortunately, I cannot put my code which reproduces this issue, coz its under NDA

**Comment by Redth** [comment]
If you're able to reproduce this, please share on this issue and re-open it.  Unfortunately without a way to reliably reproduce it, we won't be able to fix it.
