### ISSUE TITLE
[Bug] Xamarin 4.8.0.1560 caused iOS failed to build

### ISSUE THREAD

**Issue by melicaster** [xamarin/Xamarin.Forms#12659]
### Description
I am getting the following message when building iOS build after updated to Xamarin 4.8.0.1560
MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIDatePicker::set_PreferredDatePickerStyle(UIKit.UIDatePickerStyle)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.DatePickerRendererBase`1::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1<Xamarin.Forms.DatePicker>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

### Steps to Reproduce

1. Created the "Blank Forms App" under MultiPlatform/App/Xamarin.Forms
2. Update to Xamarin 4.8.0.1560
3. Try to build the solution, with no edits

### Expected Behavior
The app should be able to be build properly.

### Actual Behavior
The app failed to build.

### Basic Information

- Version with issue:
- Last known good version: Xamarin 4.8.0.1451
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

N/A

### Reproduction Link

https://forums.xamarin.com/discussion/185633/getting-error-cant-resolve-the-refererence-when-trying-to-run-a-new-solution

### Workaround

You can downgrade to 4.8.0.1451 temporarily.

**Comment by PureWeen** [comment]
@melicaster it sounds like you need to update to the latest XCode and/or version of Visual Studio

The API you are listing there is part of XCode 12 so if you are still on XCode 11 and an older version of Xamarin.iOS you won't be able to compile

**Comment by APopatanasov** [comment]
@PureWeen If we need to upgrade the XCode version to 12 why is the build directive set to XCode 11 (https://github.com/xamarin/Xamarin.Forms/blob/938700b28f500ae0beb7967e10516199b03b2b71/Xamarin.Forms.Platform.iOS/Renderers/DatePickerRenderer.cs#L76)

If the API is introduced with XCode 12 I believe the directive should be changed to 12 as well.
