### ISSUE TITLE
[Bug] iOS 14 - ScrollView has a SafeArea inset

### ISSUE THREAD

**Issue by tuyen-vuduc** [xamarin/Xamarin.Forms#12669]
### Description
When trying using ScrollView as the root element of the page, we could have its child to display underlying the notch.

### Steps to Reproduce

1. Create a simple content page with ScrollView and some content inside
2. Check out it display

### Expected Behavior
- No safearea at the top of the scroll view

### Actual Behavior
- Safearea at the top of the scroll view

### Basic Information

- Version with issue: 4.8
- Last known good version:
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  14.2
- Nuget Packages: 
- Affected Devices: iPhone device with the notch

### Screenshots
![Simulator Screen Shot - iPhone 12 - 2020-10-30 at 09 12 42](https://user-images.githubusercontent.com/3112460/97652288-960d5100-1a90-11eb-99e9-3fcc3ff1e053.png)

### Reproduction Link
N/A

### Workaround
N/A

**Comment by PureWeen** [comment]
@tuyen-vuduc  I don't quite follow

I ran this app with a ScrollView on an iOS 14 device and an iOS 12 device. They both layout about the same as it relates to the notch.

Can you attach a repro?

![image](https://user-images.githubusercontent.com/5375137/97761753-90395f00-1ad4-11eb-8e97-b5a79435c9f4.png)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by movisis** [comment]
It happens on devices like iPhone 8.

I've created my own scroll component, and created a new property:

`        public static readonly BindableProperty NoSafeAreaProperty =
            BindableProperty.Create("NoSafeArea", typeof(bool), typeof(ExtendedScroll), false);

        public bool NoSafeArea
        {
            get { return (bool)GetValue(NoSafeAreaProperty); }
            set { SetValue(NoSafeAreaProperty, value); }
        }`

On the ScrollRenderer:

`        private void SetNoSafeArea(ExtendedScroll view)
        {
            if (view.NoSafeArea)
            {
                ContentInset = new UIKit.UIEdgeInsets(0, 0, 0, 0);
                if (UIDevice.CurrentDevice.CheckSystemVersion(11, 0))
                {
                    ContentInsetAdjustmentBehavior = UIKit.UIScrollViewContentInsetAdjustmentBehavior.Never;
                }
            }
        }`

On my Form, I'm using my scroll component, and set "NoSafeArea=true".

**Comment by movisis** [comment]
> @tuyen-vuduc I don't quite follow
> 
> I ran this app with a ScrollView on an iOS 14 device and an iOS 12 device. They both layout about the same as it relates to the notch.
> 
> Can you attach a repro?
> 
> ![image](https://user-images.githubusercontent.com/5375137/97761753-90395f00-1ad4-11eb-8e97-b5a79435c9f4.png)

On iPhone X, XS and newers, it won't occur. Only on devices with the screen proportion of iPhone 8 or similars.

**Comment by movisis** [comment]
Or else, what I haven't confirmed, it only happens when the content height is bigger than the parent visible area. Anyway, my solution solves the problem.
