### ISSUE TITLE
[Enhancement] Extend the control DisplayPromptAsync to input integer values

### ISSUE THREAD

**Issue by JoergB** [xamarin/Xamarin.Forms#12663]
## Summary
Allow the user to enter an integer value in a convenient and smart way.
While using the control DisplayPromptAsync as an integer input the keyboard entry text field should be accompanied - not replaced - by a slider for easy and fast input.

## API Changes
Overload of the method DisplayPromptAsync using the original signature but extended by the parameters minValue and maxValue and an integer return value.

## Intended Use Case
This input allows validation of the value range and very fast input by using the slider and the given range.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
