### ISSUE TITLE
[Enhancement] Add an overlay layer on Application

### ISSUE THREAD

**Issue by maxbrister** [xamarin/Xamarin.Forms#12661]
## Summary
VS would like to implement element selection behavior for Android/iOS. We need a way of both intercepting mouse events and drawing adorners over existing Xamarin applications.

## API Changes

```csharp
var grid = new Grid();
Application app = ...;
application.OverlayLayer = grid;
```

It might be desirable to use something less obvious or make it clear users shouldn't use the layer themselves. If users start using the `OverlayLayer` in their own apps we will conflict with them.

For example, [this](https://docs.microsoft.com/en-us/windows/win32/api/xamlom/nf-xamlom-ixamldiagnostics-getuilayer) is the API VS uses for Uwp. For Wpf VS places a semitransparent HWND over the user's application. This solution isn't possible on Xamarin.

## Intended Use Case
VS will use the overlay layer to intercept mouse events when in selection mode.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
