### ISSUE TITLE
RadioButtonRenderer in ios doesnt exist

### ISSUE THREAD

**Issue by rozek1szymon** [xamarin/Xamarin.Forms#12678]
There is no property such as RadioButtonRenderer in Xamarin Ios

### Steps to Reproduce

1.  try to create customRadioButton renderer and try to extend from : RadioButtonRenderer

it should be possible to create such a renderer

It occurs in 5.0.0.1558-pre3

In this commit RadioButtonRenderer from IOS was deleted: https://github.com/xamarin/Xamarin.Forms/commit/2a97a6c5f0e39602cd6c7140c80bc872d0f793e0

**Comment by hartez** [comment]
@rozek1szymon It sounds like you're reporting two different issues here - can you please create a second issue for your CheckedChanged problem?

**Comment by rmarinho** [comment]
Yes that renderer was removed,  it was under preview/experimental flag, .
