### ISSUE TITLE
[Bug] UWP ListView header Size problem after 4.8.0.1364 

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#12671]
### Description

Using the 4.8.0.1560 Header in the listView sizes too large as in the screenshot below. Before versions were just fitting the child size. I am using a grid like below in the listview header. 
```
  <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="{OnIdiom Phone=30, Tablet=40, Default=50}" />
                <ColumnDefinition Width="3*" />
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>
```
in the previos versions using Auto, even using * as height, it would just perfectly fit around the children. Why now it is extending almost half size of the screen. Do you have some breaking change between those versions?
 
**4.8.0.1364** is the last knwon working version.. **anything above version has this error.** 
  
### Basic Information

- Version with issue:
- Last known good version: XF 4.8.0.1364 
 
- Nuget Packages: 4.8
- Affected Devices: UWP local

### Screenshots

**4.8.0.1364 version**
![image](https://user-images.githubusercontent.com/10422347/97659114-71a07d00-1a6e-11eb-9089-407139032f66.png)

**4.8.0.1560 version**
![image](https://user-images.githubusercontent.com/10422347/97659140-7e24d580-1a6e-11eb-9499-bb860b0e3f52.png)

**Comment by PureWeen** [comment]
@EmilAlipiev can you attach a repro please?

**Comment by EmilAlipiev** [comment]
I don't really get this because when create a fresh new project and copy the masterdetail implementation from my actual projects, it works fine. I have checked every single details. Nugets installed their versions, compared codes line by line, UWP settings, Manifest, renderers etc all the same. why one works another not? is there any logical explanation or suggestion to follow to reproduce on a new project?

**Comment by Redth** [comment]
Could it be something in the default UWP template's resource dictionary/styles that is different?  

Glad to hear it's working this way for you anyhow.  Thanks for the update.
