### ISSUE TITLE
[Bug] XF5+ CarouselView crashes If last Item is removed

### ISSUE THREAD

**Issue by HarryLobster** [xamarin/Xamarin.Forms#12673]
I make it brief because I am so frustrated....

CarouselView crashes If last Item is removed. 
This is confirmed by Jarvan from the Xamarin-Forum.

The bug is not raised if I use a CollectionView instead or use XF4.8.

Please fix it and think about "Automatic Testing" for your Quality Control. I am tired about all those errors...

**Comment by PureWeen** [comment]
[Issue12673.zip](https://github.com/xamarin/Xamarin.Forms/files/5467827/Issue12673.zip)

**Comment by rmarinho** [comment]
I think PR #12787 fixes this
