### ISSUE TITLE
[Bug] Possibly false positive of XLS0501 

### ISSUE THREAD

**Issue by Uzivatel919** [xamarin/Xamarin.Forms#12679]
### Description

If element has _Name_ property it cannot be set along with _x:Name_.

### Steps to Reproduce

1. Create some custom element.

 ```
using Xamarin.Forms;

namespace Xamarin
{
    public class ExtendedLabel : Label
    {
        public static readonly BindableProperty NameProperty = BindableProperty.Create(nameof(Name), typeof(string), typeof(ExtendedLabel), null);

        public string Name
        {

            get => (string)GetValue(NameProperty);
            set => SetValue(NameProperty, value);
        }
    }
}

 ```
2.  Use it in XAML

 ```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Xamarin.Test"
             xmlns:customElement="clr-namespace:Xamarin">
    <ContentPage.Content>
        <StackLayout>
			<customElement:ExtendedLabel
				x:Name="XamlName"
				customElement:Name="Name"
				/>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
 ```
### Expected Behavior

I believe x:Name and Name should not colide.

### Actual Behavior

Getting _XLS0501 The property 'Name' is set more than once._

### Basic Information

Xamarin.Forms 4.6.0.1141

VisualStudio.16.Release/16.7.7+30621.155
Installed Version: Community
Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Xamarin Templates   16.7.85 (1bcbbdf)
Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)

### Screenshots

![Xamarin Error](https://user-images.githubusercontent.com/26486200/97692186-c1e40300-1a9f-11eb-8a77-11853eaf7d94.png)

### Workaround

Use different bindable property name

### Sample project

[Xamarin.zip](https://github.com/xamarin/Xamarin.Forms/files/5464431/Xamarin.zip)

**Comment by PureWeen** [comment]
@Uzivatel919 I think this is correct

I tested on UWP and UWP reports the same error

![image](https://user-images.githubusercontent.com/5375137/97762812-be6c6e00-1ad7-11eb-8bed-3d46704de886.png)


@StephaneDelcroix can correct me here if I'm mistaken though

**Comment by Uzivatel919** [comment]
I tested just WPF but there already exists is [FrameworkElement.Name](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.name?view=netcore-3.1). I should have tested also UWP. Nonetheless does not it mean that both **Xamarin** and **UWP** reports false positives, @PureWeen?
