### ISSUE TITLE
[Bug] Hot reload: App stops every time after making change and performing action

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12696]
Hi.

I have a 100% repro case where if I do an edit to a page containing a collection view inside a refresh view, make an edit and run a command, the app in the simulator just shuts down. No error is reported in VS, and the log just says "Stopped hot reload session due to ExplicityEnded ...".

I have a video of the entire sequence in case it would be helpful. In that case just let me know where to send it (it contains proprietary stuff about my app so don't want to share it publicly).

Here is a log from VS and it's absolutely chock full of errors:
[VSErrors.txt](https://github.com/xamarin/Xamarin.Forms/files/5468973/VSErrors.txt)

It's full of stuff like:
```
INFO [2020-10-31 13:08:30Z]: XAML Hot Reload Connected and Ready.
INFO [2020-10-31 13:08:46Z]: (MyApp.iOS) Xaml Changed for 'Views/SomePage.xaml' in 'MyApp', sending to app...
WARNING [2020-10-31 13:08:46Z]: StopHotReload: Could not find debugger
INFO [2020-10-31 13:08:46Z]: (MyApp.iOS) Stopped Hot Reload session due to ExplicitlyEnded ...
INFO [2020-10-31 13:08:46Z]: Stopped Hot Reload session.
System.FormatException: Input string was not in a correct format.
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, 
System.ParamsArray args) [0x000b2] in /Users/builder/jenkins/workspace/build-package-osx-mono/2020-
02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Text/StringBuilder.cs:1445 
[..]
```

Thank you.

> VS bug [#1242715](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1242715)

**Comment by BretJohnson** [comment]
Closing this old issue. If you still see problems with .NET MAUI, please open an issue there.
