### ISSUE TITLE
[Bug] [UWP] Editor > Unfocused not triggered when pressing back button

### ISSUE THREAD

**Issue by Brosten** [xamarin/Xamarin.Forms#12716]
### Description
The unfocused event of an editor is not fired when pressing back-button to navigate back in UWP. Works fine on Android...

### Steps to Reproduce
1. Open a second page with something like 
`Navigation.PushAsync(new Page2());`
2. On the second page, have an editor, with an Unfocused event, like
`<Editor Unfocused="Editor_Unfocused"/>`
3. Set focus in the editor
4. Press the back button in top left corner of the UWP app
5. No Unfocused event is triggered

### Expected Behavior
Unfocused event should be triggered

### Actual Behavior
Unfocused event is not triggered

### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: -
- IDE: VS 2019 (16.7.7) Windows 
- Platform Target Frameworks: 
  - UWP:  18362
- Affected Devices: Windows 10 desktop 

### Workaround
override OnBackButtonPressed and try to compensate for the lost logic there.

**Comment by rmarinho** [comment]
Works fine on iOS and Android.
