### ISSUE TITLE
[Bug][iOS] Setting Main page crashing the application 

### ISSUE THREAD

**Issue by nithinshiriya** [xamarin/Xamarin.Forms#12712]
### Description

After the latest Xamarin form version 4.8 ios app crashing while setting the MainPage.

### Steps to Reproduce

1. Login Page => simple page
2. CurrentApplication.MainPage = new LoginPage();
3. After Login
4. CurrentApplication.MainPage = new MasterDetailPage() 
5. Without any information app closed. 

### Expected Behavior
Should have open the MasterdetailPage

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: iOS
  - iOS:  14.0
- Nuget Packages:
  Xamarin: 14.0
- Affected Devices:

**Comment by rmarinho** [comment]
Hi @nithinshiriya can you please upload a small repro project so we can try look whats the issue? was this working in other versions ?

**Comment by nithinshiriya** [comment]
@rmarinho I am going to create a repo. Meantime here is what i am getting.

2020-11-02 16:34:52.069034-0400 Evervast.PicPoll.iOS[45273:2399130] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], UIApplication.m:4207
2020-11-02 16:34:52.071133-0400 Evervast.PicPoll.iOS[45273:2399130] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2020-11-02 16:34:52.071579-0400 Evervast.PicPoll.iOS[45273:2399130] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2020-11-02 16:34:52.071917-0400 Evervast.PicPoll.iOS[45273:2399130] dynamic_cast error 2: One or more of the following type_info's has hidden visibility or is defined in more than one translation unit. They should all have public visibility. N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.
2020-11-02 16:34:57.563484-0400 Evervast.PicPoll.iOS[45273:2399130] [AppCenterCrashes] ERROR: +[MSWrapperLogger MSWrapperLog:tag:level:]/10 Unhandled Exception:
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch
Native stack trace:
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20439f4f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207881ca -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff24671074 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2148
	5   UIKitCore                           0x00007fff23ca31c1 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	6   UIKitCore                           0x00007fff2422b602 _UIScenePerformActionsWithLifecycleActionMask + 88
	7   UIKitCore                           0x00007fff23ca3cd0 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	8   UIKitCore                           0x00007fff23ca3794 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	9   UIKitCore                           0x00007fff23ca3b01 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 819
	10  UIKitCore                           0x00007fff23ca3395 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	11  UIKitCore                           0x00007fff23cab55a __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 178
	12  UIKitCore                           0x00007fff2413587b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 871
	13  UIKitCore                           0x00007fff24248032 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	14  UIKitCore                           0x00007fff23cab2fb -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 352
	15  UIKitCore                           0x00007fff23ad16d3 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 797
	16  UIKitCore                           0x00007fff23ad017d -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 253
	17  UIKitCore                           0x00007fff23ad130c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 208
	18  UIKitCore                           0x00007fff2466f151 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 508
	19  UIKitCore                           0x00007fff2415dbaf -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 358
	20  FrontBoardServices                  0x00007fff25a6a136 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 391
	21  FrontBoardServices                  0x00007fff25a92bfd __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176 + 102
	22  FrontBoardServices                  0x00007fff25a77b91 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
	23  FrontBoardServices                  0x00007fff25a928cb __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 352
	24  libdispatch.dylib                   0x00007fff20106534 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x00007fff2010907e _dispatch_block_invoke_direct + 281
	26  FrontBoardServices                  0x00007fff25ab88f1 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	27  FrontBoardServices                  0x00007fff25ab85d7 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 433
	28  FrontBoardServices                  0x00007fff25ab8a9c -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	29  CoreFoundation                      0x00007fff203a8845 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x00007fff203a873d __CFRunLoopDoSource0 + 180
	31  CoreFoundation                      0x00007fff203a7c81 __CFRunLoopDoSources0 + 346
	32  CoreFoundation                      0x00007fff203a23f7 __CFRunLoopRun + 878
	33  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
	34  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139
	35  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912
	36  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101
	37  ???                                 0x000000010c059b25 0x0 + 4496661285
	38  ???                                 0x000000010a7a6cc3 0x0 + 4470762691
	39  ???                                 0x000000010a79d333 0x0 + 4470723379
	40  Mono                                0x00000001042963e1 mono_jit_runtime_invoke + 1569
	41  Mono                                0x000000010448aca8 mono_runtime_invoke_checked + 136
	42  Mono                                0x0000000104491015 mono_runtime_exec_main_checked + 117
	43  Mono                                0x00000001042f100c mono_jit_exec + 364
	44  Evervast.PicPoll.iOS                0x00000001035f529d xamarin_main + 2685
	45  Evervast.PicPoll.iOS                0x0000000103599f37 main + 71
	46  libdyld.dylib                       0x00007fff20257409 start + 1

  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:407 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Evervast.PicPoll.iOS.Application.Main (System.String[] args) [0x00001] in /Users/robertdoucette/Desktop/SourceCodes/PicPoll/Evervast.PicPoll/Evervast.PicPoll.iOS/Main.cs:12 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Evervast.PicPoll.iOS.Application.Main (System.String[] args) [0x00001] in /Users/robertdoucette/Desktop/SourceCodes/PicPoll/Evervast.PicPoll/Evervast.PicPoll.iOS/Main.cs:12 	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20439f4f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207881ca -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff24671074 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2148
	5   UIKitCore                           0x00007fff23ca31c1 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	6   UIKitCore                           0x00007fff2422b602 _UIScenePerformActionsWithLifecycleActionMask + 88
	7   UIKitCore                           0x00007fff23ca3cd0 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	8   UIKitCore                           0x00007fff23ca3794 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	9   UIKitCore                           0x00007fff23ca3b01 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 819
	10  UIKitCore                           0x00007fff23ca3395 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	11  UIKitCore                           0x00007fff23cab55a __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 178
	12  UIKitCore                           0x00007fff2413587b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 871
	13  UIKitCore                           0x00007fff24248032 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	14  UIKitCore                           0x00007fff23cab2fb -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 352
	15  UIKitCore                           0x00007fff23ad16d3 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 797
	16  UIKitCore                           0x00007fff23ad017d -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 253
	17  UIKitCore                           0x00007fff23ad130c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 208
	18  UIKitCore                           0x00007fff2466f151 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 508
	19  UIKitCore                           0x00007fff2415dbaf -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 358
	20  FrontBoardServices                  0x00007fff25a6a136 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 391
	21  FrontBoardServices                  0x00007fff25a92bfd __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176 + 102
	22  FrontBoardServices                  0x00007fff25a77b91 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
	23  FrontBoardServices                  0x00007fff25a928cb __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 352
	24  libdispatch.dylib                   0x00007fff20106534 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x00007fff2010907e _dispatch_block_invoke_direct + 281
	26  FrontBoardServices                  0x00007fff25ab88f1 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	27  FrontBoardServices                  0x00007fff25ab85d7 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 433
	28  FrontBoardServices                  0x00007fff25ab8a9c -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	29  CoreFoundation                      0x00007fff203a8845 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x00007fff203a873d __CFRunLoopDoSource0 + 180
	31  CoreFoundation                      0x00007fff203a7c81 __CFRunLoopDoSources0 + 346
	32  CoreFoundation                      0x00007fff203a23f7 __CFRunLoopRun + 878
	33  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
	34  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139
	35  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912
	36  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101
	37  ???                                 0x000000010c059b25 0x0 + 4496661285
	38  ???                                 0x000000010a7a6cc3 0x0 + 4470762691
	39  ???                                 0x000000010a79d333 0x0 + 4470723379
	40  Mono                                0x00000001042963e1 mono_jit_runtime_invoke + 1569
	41  Mono                                0x000000010448aca8 mono_runtime_invoke_checked + 136
	42  Mono                                0x0000000104491015 mono_runtime_exec_main_checked + 117
	43  Mono                                0x00000001042f100c mono_jit_exec + 364
	44  Evervast.PicPoll.iOS                0x00000001035f529d xamarin_main + 2685
	45  Evervast.PicPoll.iOS                0x0000000103599f37 main + 71
	46  libdyld.dylib                       0x00007fff20257409 start + 1
2020-11-02 16:34:57.616407-0400 Evervast.PicPoll.iOS[45273:2399130] Unhandled managed exception: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Application windows are expected to have a root view controller at the end of application launch
Native stack trace:
	0   CoreFoundation                      0x00007fff2043a126 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177f78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff20439f4f +[NSException raise:format:] + 0
	3   Foundation                          0x00007fff207881ca -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
	4   UIKitCore                           0x00007fff24671074 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2148
	5   UIKitCore                           0x00007fff23ca31c1 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 122
	6   UIKitCore                           0x00007fff2422b602 _UIScenePerformActionsWithLifecycleActionMask + 88
	7   UIKitCore                           0x00007fff23ca3cd0 __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 198
	8   UIKitCore                           0x00007fff23ca3794 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 474
	9   UIKitCore                           0x00007fff23ca3b01 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 819
	10  UIKitCore                           0x00007fff23ca3395 -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 345
	11  UIKitCore                           0x00007fff23cab55a __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke + 178
	12  UIKitCore                           0x00007fff2413587b +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] + 871
	13  UIKitCore                           0x00007fff24248032 _UISceneSettingsDiffActionPerformChangesWithTransitionContext + 240
	14  UIKitCore                           0x00007fff23cab2fb -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 352
	15  UIKitCore                           0x00007fff23ad16d3 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke + 797
	16  UIKitCore                           0x00007fff23ad017d -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 253
	17  UIKitCore                           0x00007fff23ad130c -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 208
	18  UIKitCore                           0x00007fff2466f151 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 508
	19  UIKitCore                           0x00007fff2415dbaf -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 358
	20  FrontBoardServices                  0x00007fff25a6a136 -[FBSScene _callOutQueue_agent_didCreateWithTransitionContext:completion:] + 391
	21  FrontBoardServices                  0x00007fff25a92bfd __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke.176 + 102
	22  FrontBoardServices                  0x00007fff25a77b91 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 209
	23  FrontBoardServices                  0x00007fff25a928cb __94-[FBSWorkspaceScenesClient createWithSceneID:groupID:parameters:transitionContext:completion:]_block_invoke + 352
	24  libdispatch.dylib                   0x00007fff20106534 _dispatch_client_callout + 8
	25  libdispatch.dylib                   0x00007fff2010907e _dispatch_block_invoke_direct + 281
	26  FrontBoardServices                  0x00007fff25ab88f1 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 30
	27  FrontBoardServices                  0x00007fff25ab85d7 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 433
	28  FrontBoardServices                  0x00007fff25ab8a9c -[FBSSerialQueue _performNextFromRunLoopSource] + 22
	29  CoreFoundation                      0x00007fff203a8845 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	30  CoreFoundation                      0x00007fff203a873d __CFRunLoopDoSource0 + 180
	31  CoreFoundation                      0x00007fff203a7c81 __CFRunLoopDoSources0 + 346
	32  CoreFoundation                      0x00007fff203a23f7 __CFRunLoopRun + 878
	33  CoreFoundation                      0x00007fff203a1b9e CFRunLoopRunSpecific + 567
	34  GraphicsServices                    0x00007fff2b793db3 GSEventRunModal + 139
	35  UIKitCore                           0x00007fff2466d40f -[UIApplication _run] + 912
	36  UIKitCore                           0x00007fff24672320 UIApplicationMain + 101
	37  ???                                 0x000000010c059b25 0x0 + 4496661285
	38  ???                                 0x000000010a7a6cc3 0x0 + 4470762691
	39  ???                                 0x000000010a79d333 0x0 + 4470723379
	40  Mono                                0x00000001042963e1 mono_jit_runtime_invoke + 1569
	41  Mono                                0x000000010448aca8 mono_runtime_invoke_checked + 136
	42  Mono                                0x0000000104491015 mono_runtime_exec_main_checked + 117
	43  Mono                                0x00000001042f100c mono_jit_exec + 364
	44  Evervast.PicPoll.iOS                0x00000001035f529d xamarin_main + 2685
	45  Evervast.PicPoll.iOS                0x0000000103599f37 main + 71
	46  libdyld.dylib                       0x00007fff20257409 start + 1
 (Foundation.MonoTouchException)
  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:407 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/jenkins/workspace/xamarin-macios/xamarin-macios/runtime/Delegates.generated.cs:128 
  at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Evervast.PicPoll.iOS.Application.Main (System.String[] args) [0x00001] in /Users/robertdoucette/Desktop/SourceCodes/PicPoll/Evervast.PicPoll/Evervast.PicPoll.iOS/Main.cs:12 
--- End of stack trace from previous location where exception was thrown ---

  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at Evervast.PicPoll.iOS.Application.Main (System.String[] args) [0x00001] in /Users/robertdoucette/Desktop/SourceCodes/PicPoll/Evervast.PicPoll/Evervast.PicPoll.iOS/Main.cs:12

**Comment by nithinshiriya** [comment]
I have found the root cause of this bug. Facebook SDK is causing an issue.  Closing this bug because nothing to do with Xamarin.
