### ISSUE TITLE
[Bug] App closes on PopAsync (or Xaml Refresh) in Xamarin.Forms iOS 

### ISSUE THREAD

**Issue by SOGAPPS** [xamarin/Xamarin.Forms#12715]
### Description
App stops debugging with no crash error, when:
- Navigating back with "PopAsync()"
- Xaml refresh with "Hot Reload" 

### Steps to Reproduce

1. Add Xamarin.Forms > 3.6.0.709228 to Xamarin Forms iOS Solution
2. Open another page with "PushAsync()"
3.a. Go back to previous page
3.b. App closes with no error log

4. Error also occurs when making Xaml changes and clicking save.

### Expected Behavior
App shouldn't close with no log
### Actual Behavior
App closes with no error log
### Basic Information
Using "Apple Simulator Log" closest to an error message we could get was "Service exited due to SIGSEGV"

- Version with issue: Any Xamarin.Forms greater than 3.6.0.709228
- Last known good version: Xamarin.Forms (v3.6.0.709228)
- IDE: Visual Studio Community 2019 for Mac Version 8.7.9 (build 9)
- Platform Target Frameworks: .NET Standard 2.1
  - iOS:  14.1
- Nuget Packages: 
`<ItemGroup>
    <PackageReference Include="Xamarin.Essentials">
      <Version>1.6.0-pre2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.TestCloud.Agent">
      <Version>0.21.9</Version>
    </PackageReference>
    <PackageReference Include="Plugin.InAppBilling">
      <Version>2.0.0</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.iOS.Lottie">
      <Version>2.5.12</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.AdMob">
      <Version>7.57.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.PerformanceMonitoring">
      <Version>3.1.11</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Facebook.iOS">
      <Version>7.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.Crashlytics">
      <Version>4.0.0-beta.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.iOS.Analytics">
      <Version>6.4.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms">
      <Version>3.6.0.709228</Version>
    </PackageReference>
  </ItemGroup>`
- Affected Devices: iPhone Simulator and Physical Device

### Workaround 
Add "Xamarin.Forms v3.6.0.709228" to iOS solution and run. This works fine

**Comment by rmarinho** [comment]
Hi @SOGAPPS that's really a very old version, can you try with a newer version like 4.8.0 ? >Also a reproduction of the issue would be great.

Thanks

**Comment by SOGAPPS** [comment]
@rmarinho Any Xamarin forms above version "3.6.0.709228" crashes (Debugger stops) the app with no log.
- Using "PushAsync", navigating back cause the app to close
- Making changes to Xaml and clicking save cause the app to close
