### ISSUE TITLE
[Enhancement] RadioButton TextType

### ISSUE THREAD

**Issue by rrEmiZ** [xamarin/Xamarin.Forms#12718]
## Summary

Allow RadioButton label to set TextType (i.e. Html)

## API Changes

var rb = new RadioButton ();
rb.TextType = TextType.Html; // new API

Label on RadioButton displays html

## Intended Use Case

Using html generated dynamic radiobutton lists in XF

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
