### ISSUE TITLE
"CheckedChanged" works only on "check click", it is impossible to uncheck the radio.

### ISSUE THREAD

**Issue by rozek1szymon** [xamarin/Xamarin.Forms#12717]
Like above, "CheckedChanged" doesnt work on ios, I cannon uncheck the radioButton in 5.0 - pre3

**Comment by rmarinho** [comment]
Can you please give us more information what's not working?! Is it setting the `IsChecked` proeprty from code, is it clicking the `RadioButton`? 

Please upload a small sample so we can take a look

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
