### ISSUE TITLE
[Bug] Xamarin.Forms 5- Overlapping text if adding multiple Grid inside Grid with label having large text and also overlap if I add stack layout in between grid too. Not adding proper vertical space between two controls text.

### ISSUE THREAD

**Issue by jhaprasun** [xamarin/Xamarin.Forms#12725]
### Description
I installed Xamarin.Forms 5 Pre 1/2/3 and none of it helped all together. I've taken grid inside grid with label to display text. For small amount of text it doesn't have any issue. But if we have large text to display using multiple grid then it overlaps the text. And also if in between grid if I add stack layout or label then in this case text is also getting overlapped. This problem is getting replicated very easily in all the platforms(iOS,Android and UWP) and almost all the devices iPhone, iPad, Android phone, Tablet and Windows tablet in both portrait and landscape mode too.

### Expected Behavior
Text should not be overlap
### Actual Behavior
Text is overlapping
### Basic Information
Refer description and attached sample repo project

- Version with issue:Xamarin.Forms 5 Pre 1/2/3 
- Last known good version:Xamarin.Forms 4.5.0.356
- IDE: Visual Studio MAC 2019
- Platform Target Frameworks: 
  - iOS:  iOS 13.4
  - Android: Android 10
  - UWP: Windows 10 Enterprise version 1809
- Nuget Packages:
Xamarin.Forms 5 Pre 1/2/3
- Affected Devices:
iPhone, iPad, Android phone, Tablet, Windows tablet and Desktop 

### Screenshots
![Screenshot-1](https://user-images.githubusercontent.com/39085388/98015729-01d71d00-1df5-11eb-9d0b-0c756ac32f00.png)
![Screenshot-2](https://user-images.githubusercontent.com/39085388/98015753-0a2f5800-1df5-11eb-93fe-1c6316744a92.png)

### Reproduction Link

[SampleProject.zip](https://github.com/xamarin/Xamarin.Forms/files/5482779/SampleProject.zip)

### Workaround
No

**Comment by hartez** [comment]
Looks like whatever happened, it happened between 4.8.0.1269 and 4.8.0.1364.

**Comment by hartez** [comment]
Most likely the problem happened here: https://github.com/xamarin/Xamarin.Forms/pull/11903

**Comment by rmarinho** [comment]
@hartez  i don't think so if you test 4.7 you see the issue. 
If you test on 5.0.0 branch you see the issue.

**Comment by hasan9444** [comment]
This issue also  reproducing on XF version 4.8.0.1560
any update on fixing this issue in XF 4?

**Comment by jemunk** [comment]
Upgraded to 4.8.0.1560 and now also see this issue

**Comment by jhaprasun** [comment]
Hi, Issue has been fixed for iOS, UWP and macOS for all type of devices but I can see the problem still exist in Android phone and tablet both.

**Comment by saimel** [comment]
Hi, issue is still present in iOS. I tested in v5.0.0.1931 and v5.0.0.2083

**Comment by gauravsk1996** [comment]
Hi, Issue is still present in iOS. I tested in v5.0.0.2337.
