### ISSUE TITLE
Since updating to Xamarin.Forms 16.7, flag SwipeView_Experimental does not work

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12737]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Since-updating-to-XamarinForms-167-fl/1233057?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio]
Since updating Xamarin.Forms to 16.7, the following code...

```
public override bool FinishedLaunching( UIApplication app, NSDictionary options )
		{
			global::Xamarin.Forms.Forms.SetFlags( "SwipeView_Experimental" );
			global::Xamarin.Forms.Forms.SetFlags( "RadioButton_Experimental" );

global::Xamarin.Forms.Forms.Init();
```

... does not prevent a later exception when trying to construct an instance of **SwipeView**.

---
#### Feedback Bot on 27/10/2020, 07:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Tina Zhao [MSFT] on 28/10/2020, 08:32 AM: 

<p>Thanks for your feedback.<br>
We have release a new version and it seems that this issue has been resolved. Could you update VS and Xamarin Form to latest version,   to check if this issue still appear?</p>

#### patrickryder on 28/10/2020, 00:59 PM: 

(private comment, text removed)
#### Feedback Bot on 28/10/2020, 03:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Patrick, could you indicate what specific version of Xamarin.Forms are you using?, on what platform do you get the error?

**Comment by PatrickRyder** [comment]
Microsoft Visual Studio Community 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.04084

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)

Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jsuarezruiz** [comment]
@PatrickRyder When you are doing:
```
global::Xamarin.Forms.Forms.SetFlags( "SwipeView_Experimental" );
global::Xamarin.Forms.Forms.SetFlags( "RadioButton_Experimental" );
```

The second line sets the flag of the RadioButton overwriting the one of the swipeView. As a result, you only have the flag for RadioButton registered.

Change that two lines by:

`global::Xamarin.Forms.Forms.SetFlags( "SwipeView_Experimental",  "RadioButton_Experimental");`

And everything must works as expected.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by PatrickRyder** [comment]
I still haven't had an opportunity to test this but am certain the fix will work.

Thank you!
