### ISSUE TITLE
[Bug] [iOS] List swipe with MaterialButtonRenderer crash

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#12747]
### Description
The application crashes if the user try to swipe right to left and there is a button with MaterialButtonRenderer.
This happen only on iOS.

### Stack
```
  at Xamarin.Forms.Material.iOS.MaterialButtonRenderer.ApplyThemeIfNeeded () [0x00000] in D:\a\1\s\Xamarin.Forms.Material.iOS\MaterialButtonRenderer.cs:118 
  at Xamarin.Forms.Material.iOS.MaterialButtonRenderer.LayoutSubviews () [0x00006] in D:\a\1\s\Xamarin.Forms.Material.iOS\MaterialButtonRenderer.cs:88 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/14.2.0.12/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at SgatFAST.iOS.Application.Main (System.String[] args) [0x00002] in /Users/pozzy/Projects/AppFAST/SgatFAST/SgatFAST.iOS/Main.cs:16 
```

### Expected Behavior
Not crash

### Actual Behavior
Crash

### Basic Information

- Version with issue: 4.8.0.1560
- IDE: VS on mac
- Platform Target Frameworks: 
  - iOS:  14.x
- Nuget Packages: Xamarin.Forms.Visual.Material

### Screenshots
[Link](https://gofile.io/d/svZXhE) to video.

**Comment by rmarinho** [comment]
Hi @Raystorm7  can you upload a small repo? I just tried a ListView with this template and it works fine:

```
   <DataTemplate x:Key="MessageTemplate">
                <ViewCell>
                    <SwipeView
                        HeightRequest="80">
                        <Grid
                            BackgroundColor="White"
                            RowSpacing="0">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*" />
                                <ColumnDefinition Width="Auto" />
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="Auto" />
                                <RowDefinition Height="*" />
                            </Grid.RowDefinitions>
                            <Label
                                Grid.Column="0"
                                Grid.Row="0"
                                Text="{Binding Title}"
                                Style="{StaticResource TitleStyle}"/>
                            <Label
                                Grid.Column="1"
                                Grid.Row="0"
                                Text="{Binding Date}"
                                Style="{StaticResource DateStyle}"/>
                            <Label
                                Grid.Column="0"
                                Grid.ColumnSpan="2"
                                Grid.Row="1"
                                Text="{Binding SubTitle}"
                                Style="{StaticResource SubTitleStyle}"/>
                            <Label
                                Grid.Column="0"
                                Grid.ColumnSpan="2"
                                Grid.Row="2"
                                Text="{Binding Description}"
                                Style="{StaticResource SubTitleStyle}"/>
                        </Grid>
                        <SwipeView.RightItems>
                            <SwipeItems Mode="Reveal">
                                <SwipeItemView>
                                     <Button Visual="Material" Text="Test Click from RightItems" />
                                </SwipeItemView>
                            </SwipeItems>
                        </SwipeView.RightItems>
                    </SwipeView>
                </ViewCell>
            </DataTemplate>
```

![image](https://user-images.githubusercontent.com/1235097/98240878-0240f680-1f62-11eb-87f0-ada98a2a9575.png)


Thanks

**Comment by Raystorm7** [comment]
> Hi @Raystorm7 can you upload a small repo? I just tried a ListView with this template and it works fine:
> 
> ```
>    <DataTemplate x:Key="MessageTemplate">
>                 <ViewCell>
>                     <SwipeView
>                         HeightRequest="80">
>                         <Grid
>                             BackgroundColor="White"
>                             RowSpacing="0">
>                             <Grid.ColumnDefinitions>
>                                 <ColumnDefinition Width="*" />
>                                 <ColumnDefinition Width="Auto" />
>                             </Grid.ColumnDefinitions>
>                             <Grid.RowDefinitions>
>                                 <RowDefinition Height="Auto" />
>                                 <RowDefinition Height="Auto" />
>                                 <RowDefinition Height="*" />
>                             </Grid.RowDefinitions>
>                             <Label
>                                 Grid.Column="0"
>                                 Grid.Row="0"
>                                 Text="{Binding Title}"
>                                 Style="{StaticResource TitleStyle}"/>
>                             <Label
>                                 Grid.Column="1"
>                                 Grid.Row="0"
>                                 Text="{Binding Date}"
>                                 Style="{StaticResource DateStyle}"/>
>                             <Label
>                                 Grid.Column="0"
>                                 Grid.ColumnSpan="2"
>                                 Grid.Row="1"
>                                 Text="{Binding SubTitle}"
>                                 Style="{StaticResource SubTitleStyle}"/>
>                             <Label
>                                 Grid.Column="0"
>                                 Grid.ColumnSpan="2"
>                                 Grid.Row="2"
>                                 Text="{Binding Description}"
>                                 Style="{StaticResource SubTitleStyle}"/>
>                         </Grid>
>                         <SwipeView.RightItems>
>                             <SwipeItems Mode="Reveal">
>                                 <SwipeItemView>
>                                      <Button Visual="Material" Text="Test Click from RightItems" />
>                                 </SwipeItemView>
>                             </SwipeItems>
>                         </SwipeView.RightItems>
>                     </SwipeView>
>                 </ViewCell>
>             </DataTemplate>
> ```
> 
> ![image](https://user-images.githubusercontent.com/1235097/98240878-0240f680-1f62-11eb-87f0-ada98a2a9575.png)
> 
> Thanks

Sorry my fault, another not updated packages caused the issue.
