### ISSUE TITLE
[Bug] String format does not show double quotes when encoding characters

### ISSUE THREAD

**Issue by nichojo89** [xamarin/Xamarin.Forms#12763]
### Description
In XAML using StringFormat  I must escape my own quotes with encoded 2x like this if I want to display qoutations around a string
`Text="{Binding MyBinding, StringFormat='&quot;&quot;{0}&quot;&quot;'}`

This Doesn't work although. its the expected behavior
`StringFormat='&quot;{0}&quot;'}`

For some reason this works as well
`StringFormat='&quot;{0}&quot;Hello World'}`

### Steps to Reproduce
Use StringFormat as described. above in a XAML binding. 

### Expected Behavior
Shows escaped quotes using StringFormat in XAML against a Binding
### Actual Behavior
Does not show escaped quotes using StringFormat in XAML against a Binding
### Basic Information

- Version with issue: 4.8.0.15.34
- Last known good version: N/A
- IDE: VS4M
- Platform Target Frameworks: 
  - iOS:  14.1
  - Android: 9.0

### Reproduction Link

This works
`StringFormat='&quot;&quot;{0}&quot;&quot;'}`
This Doesn't
`StringFormat='&quot;{0}&quot;'}`

### Workaround
`StringFormat='&quot;&quot;{0}&quot;&quot;'}`

**Comment by StephaneDelcroix** [comment]
your literal value contains curly braces, and needs to be escaped, like this

```xaml
    <Label x:Name="label" Text="{Binding ., StringFormat='{}&quot;{0}&quot;', Source=Foo}" />
```

and that works fine.

ref: https://docs.microsoft.com/en-us/dotnet/desktop/xaml-services/escape-sequence-markup-extension

**Comment by StephaneDelcroix** [comment]
reopening, as the escape sequences fixes the bug, but is not _required_ as the value does not start with an opening curly brace
