### ISSUE TITLE
[Bug] System.DivideByZeroException on ShellFlyoutRecyclerAdapter

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#12766]
**Description**
DivideByZeroException observed in Xamarin.Android/Xamarin.Forms code in the wild.
This erros happens on Xamarin.Forms.Platform.Android\Renderers\ShellFlyoutRecyclerAdapter.cs -> GetItemViewType(int position)

I propose an explicit check to Dictionary before insert value
```
if (_templateMap.ContainsKey(id))
				_templateMap[id] = template;
Else
_templateMap.Add(id) = template;
```

**Stack trace:**
```

(wrapper managed-to-native) System.Object.__icall_wrapper___emul_op_irem(int,int)
Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)
Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value)
ShellFlyoutRecyclerAdapter.GetItemViewType (System.Int32 position)
RecyclerView+Adapter.n_GetItemViewType_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.48(intptr,intptr,int)


```
**Steps to Reproduce**
Unknown

**Expected Behavior**
No crash

**Actual Behavior**
System.DivideByZeroException: Attempted to divide by zero.

**Basic Information**
Version with issue: 4.8.0.1560
Last known good version: n/a
IDE: VS 2019 16.7
Platform Target Frameworks:
iOS: -
Android: API Level 29 Q
UWP: -
Android Support Library Version:
Nuget Packages:
Affected Devices: moto g6 play, Galaxy J2 Core, moto e6s

**Reproduction Link**
This has been observed via AppCenter and is demonstrably rare. Thus, I have no reproduction.

**Comment by PureWeen** [comment]
@transis2 do you have a larger stack trace? Or a sample by chance? Or can you post what your Shell file looks like?

I'm not quite sure how the proposed fix would address the issue.. 

```C#
_templateMap[id] = template;
```

Is initializing the key to a value so the map won't contain that ID at this point ever (AFAICT) 

The problem here seems to be that the `id` value here is < 0 

That would be my guess

**Comment by transis2** [comment]
Hello @PureWeen 

This is how my ShellFlyout looks like

![Screenshot_20201106-174536](https://user-images.githubusercontent.com/4941173/98413234-04857c80-2058-11eb-829e-c0b7d8deca77.jpg)

below is the xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<Shell xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:Views="clr-namespace:Catalogo.View"
             mc:Ignorable="d"
             x:Class="Catalogo.MainPage"
             Shell.BackgroundColor="#2C2C2F"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             ios:Page.UseSafeArea="true"
             FlyoutBehavior="Disabled">
    <Shell.FlyoutHeaderTemplate >
        <DataTemplate>
            <Views:HeaderContent/>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>
    <ShellContent Title="Empresas">
        <ShellContent.Icon>
            <FontImageSource
            FontFamily="{StaticResource FontAwesomeSolid}"
            Glyph="&#xf362;"
            Size="44"
            Color="{DynamicResource CorDestaquePlus}"/>
        </ShellContent.Icon>
        <Views:UsuariosPage/>
    </ShellContent>
</Shell>
```

The App Center Stack trace has no more info than that.

**Comment by transis2** [comment]
I found more info on reports

![image](https://user-images.githubusercontent.com/4941173/98413928-44009880-2059-11eb-9438-3288d7bd01e3.png)

```
(wrapper managed-to-native) System.Object.__icall_wrapper___emul_op_irem(int,int)
Dictionary`2[TKey,TValue].FindEntry (TKey key)
Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value)
BindableObject.GetValue (Xamarin.Forms.BindableProperty property)
Shell.GetNavBarHasShadow (Xamarin.Forms.BindableObject obj)
ShellToolbarTracker.UpdateNavBarHasShadow (Xamarin.Forms.Page page)
<.ctor>b__18_0 ()
GenericGlobalLayoutListener.OnGlobalLayout ()
ViewTreeObserver+IOnGlobalLayoutListenerInvoker.n_OnGlobalLayout (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.72(intptr,intptr)
```

**Comment by jfversluis** [comment]
Seems the reported has abandoned the PR to fix this, closing for now.

@transis2 let us know if you want to revive the PR if still necessary!
