### ISSUE TITLE
[Bug] NavigationPage.BarBackgroundColor is always white.@WPF

### ISSUE THREAD

**Issue by uk-taniyama** [xamarin/Xamarin.Forms#12771]
### Description

Even if you specify "Red” for NavigationPage.BarBackgroundColor, it will be drawn in "White".
Of course Android, iOS is "Red".
```
public App()
{
	InitializeComponent();

	MainPage = new NavigationPage(new MainPage())
	{
		BarBackgroundColor = Color.Red,
	};
}
```

### Basic Information

- Version with issue:4.8.xxx
- Last known good version:4.7.xxx

**Comment by uk-taniyama** [comment]
Changing to this will work.

```
public App()
{
	InitializeComponent();

	MainPage = new NavigationPage(new MainPage())
	{
		BarBackgroundColor = new SolidColorBrush(Color.Red)
	};
}

```

**Comment by bddckr** [comment]
I've run into the same with version 5.0.0.1709-pre4 of the NuGet packages (core Xamarin.Forms + the WPF platform package). The work around to set a brush instead works for me, too. Thanks for that!

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
