### ISSUE TITLE
[Bug] Shell. Don't show shadow for navigation bar if TabbedPage is opened

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/Xamarin.Forms#12775]
### Description
There shouldn't be any shadow under navigation bar if tabbed page is opened.

Here is the source code of the `TabbedPage `
````xaml
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:views="clr-namespace:NureTimetable.UI.Views"
            xmlns:LN="clr-namespace:NureTimetable.Core.Localization;assembly=NureTimetable.Core"
            x:Class="NureTimetable.UI.Views.AddTimetablePage"
            xmlns:vm="clr-namespace:NureTimetable.UI.ViewModels.TimetableEntities"
            xmlns:fonts="clr-namespace:NureTimetable.Models.Consts.Fonts"
            x:DataType="vm:AddTimetableViewModel"
            Title="{LN:Translate AddingTimetable}">

    <TabbedPage.ToolbarItems>
        <ToolbarItem IconImageSource="{FontImage FontFamily={StaticResource MaterialFontFamily}, Glyph={x:Static fonts:MaterialIconsFont.Sync}}" Command="{Binding UpdateCommand}" x:Name="UpdateFromCist" />
    </TabbedPage.ToolbarItems>

    <views:AddEntityPage BindingContext="{Binding AddGroupPageViewModel}" />
    <views:AddEntityPage BindingContext="{Binding AddTeacherPageViewModel}" />
    <views:AddEntityPage BindingContext="{Binding AddRoomPageViewModel}" />
</TabbedPage>
````

### Steps to Reproduce

1. Create shell application
2. Open `TabbedPage` using `Navigation.PushAsync`

### Expected Behavior
![image](https://user-images.githubusercontent.com/6609929/98450728-c36c9580-2147-11eb-9892-7e54e3742163.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/6609929/98450722-ae900200-2147-11eb-901b-91697ccfc36a.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rachelkang** [comment]
Hi, @maxkoshevoi - thanks for submitting this issue! I wasn't able to reproduce this issue you're describing - I tried it on a blank Forms Tabbed App project, but your project seems to be wired a bit differently with your custom controls. If I'm misunderstanding and you can share this project or a sample project reproducing the same issue, that would be extremely helpful! Thank you :)

**Comment by maxkoshevoi** [comment]
Hi, thanks for taking time to investigate this.
Here is project like: https://github.com/maxkoshevoi/NureTimetable

Recently I migrated it to Shell. Before this there was no shadow on that page.

Repro steps:
- Go to Timetables tab
- Tap on plus toolbar item

**Comment by rachelkang** [comment]
@maxbrister thanks for sharing and elaborating! It looks like I somehow missed the detail where you mentioned this is related to Shell - apologies for that! When using Shell, the nav bar has a shadow on Android by default. To disable this, you can set the appropriate property to false with `Shell.NavBarHasShadow="False"`. I tried adding to all your pages, and the shadow disappeared! Give it a try, and let me know if that works for you.

You can find more info about this in our docs here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/configuration#enable-navigation-bar-shadow

And as for the way you've configured the tabbed pages, you might be interested in exploring how you can take further advantage of Shell! Our docs here explain that a bit more: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#bottom-and-top-tabs

**Comment by maxbrister** [comment]
@rachelkang I think you meant @maxkoshevoi

**Comment by rachelkang** [comment]
@maxbrister ah yes, sorry for the confusion! 😅

**Comment by maxkoshevoi** [comment]
Thank you, `Shell.NavBarHasShadow="False"` removed the shadow! But I feel like this should be a default behavior for `TabbedPage`

**Comment by rachelkang** [comment]
@maxkoshevoi awesome! and ok, I'll move this issue to our Enhancements board for your proposal to be considered

**Comment by jfversluis** [comment]
We won't be doing this for Xamarin.Forms anymore. If this is still a thing in .NET MAUI, please make sure to open an issue for the enhancement there. Thanks!
