### ISSUE TITLE
[Bug] DragAndDrop not working when loading custom ListView inside the ScrollView

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#12778]
### Description
When loading our custom ListView control inside the ScrollView, the drag and drop function not worked in Android and iOS. The reported issue is a break in XF version 4.1.0.618606. 

Also, our DragAndDrop works fine without scrollview.

### Steps to Reproduce

1. Run the attached in sample in iOS and Android
2. Drag and drop an item
3. The item is reordered but the dragging is not updated in the view.

### Expected Behavior
ListView item should not be dragged.

![ExpectedBehaviorGif](https://user-images.githubusercontent.com/60344234/98471510-dbf5b200-2212-11eb-9bf0-5c588dfc5c50.gif)

### Actual Behavior
ListView item should be able to drag and drop.

![ActualBehaviorGif](https://user-images.githubusercontent.com/60344234/98471517-e57f1a00-2212-11eb-9345-07fde4ec9283.gif)

### Basic Information
Related to https://github.com/xamarin/Xamarin.Forms/issues/11164

- Version with issue: 4.1.0.618606
- Last known good version: 4.1.0.581479
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.1
  - Android: tested on Android 8.1 API 27
  - UWP:  -
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[DragIssueSample.zip](https://github.com/xamarin/Xamarin.Forms/files/5506811/DragIssueSample.zip)

### Workaround
We need to load our ListView without ScrollView.

**Comment by rachelkang** [comment]
Hi, @LakshmiNatarajan21 - thanks for submitting this issue! Unfortunately, as much of this repro is specific to the custom control, it's difficult to pinpoint the potential XF issue. Would you be able to share a repro where ScrollView might be breaking something without SF components?

Although I don't know much about this DragAndDrop, a behavior which seems to be specific to this custom ListView control, we currently do have our own experimental [DragAndDrop implementation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/drag-and-drop) that you may or may not be familiar with / interested in. Hope this helps!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
