### ISSUE TITLE
[Bug]  [iOS] Rise two Navigating on fore each iframe in WebView.

### ISSUE THREAD

**Issue by Nelo-cool** [xamarin/Xamarin.Forms#12795]
### Description
Hello guys!

I know, in iOS WebView rise Navigating event on each iframe on the page. Even if some pages were loaded after using JS. But why two events? First with address iframe (exmpl: https://www.youtube.ru/embedded/....) and second with **about:blank** address. None at all Navigated event:) Only navigating. 
But how to know when man clicked on the link or WebView load iframe? :( 

### Steps to Reproduce

1. Create application with WebView control and debug on iOS.
2. Open page by Source="{Binding Url}" and set Url to page with iframes.
3. See too:)

### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:   14.1
### Screenshots
![WKNavigationDelegate](https://user-images.githubusercontent.com/902820/98672006-28053b80-2366-11eb-9d70-eeb6d9a48a10.JPG)

### Reproduction Link
Url for project binding with many iframes and js loading: http://api2.ivteleradio.ru/page?id=1031146

**Comment by rachelkang** [comment]
Hi, @Nelo-cool - thanks for submitting this issue! I'm wondering - does this work as expected on Android / other platforms? Is it only an issue on iOS? Also, would you be able to share this project or a sample project reproducing the same bug? Thanks :)

**Comment by Nelo-cool** [comment]
Created little project with this behavior: (in zip archive, without repository, excuse me)
[WebViewAndAboutBlankiOS.zip](https://github.com/xamarin/Xamarin.Forms/files/5519003/WebViewAndAboutBlankiOS.zip)
![Navigating](https://user-images.githubusercontent.com/902820/98707705-62d09900-2391-11eb-97d9-664f916f7706.JPG)

**Comment by rachelkang** [comment]
@Nelo-cool thanks so much for sharing and elaborating! It seems the issue you're describing has been captured in #10350 and specifically this [comment](https://github.com/xamarin/Xamarin.Forms/issues/10350#issuecomment-616629755), so I'm going to close this issue now. If you think I'm misunderstanding, please feel free to reopen!
