### ISSUE TITLE
[Bug] Entry text is invisible on iOS

### ISSUE THREAD

**Issue by robtomlinson** [xamarin/Xamarin.Forms#12809]
### Description
Entry text is invisible on iOS.
### Steps to Reproduce

1. Create Entry text field.
2. Type in text, or populate via code behind.

### Expected Behavior
Entry text should be visible when typing or when pre-filled from code behind.
### Actual Behavior
Entry text is invisible. Cursor position can be moved across the text field, and it can be selected and copied, but there is no visible text on the page. This seems to only be effecting iOS. The entry text is visible as expected on Android.
### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: unknown
- IDE: Microsoft Visual Studio Community 2019 Version 4.8.04084
- Platform Target Frameworks: 
  - iOS:  14.1
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
Xamarin Essentials 1.5.3.2
Xamarin Forms 4.8.0.1560
Xamarin.Forms.Visual.Material 4.8.0.1560
- Affected Devices:
iPhone 12
iPad
### Screenshots
https://postimg.cc/gallery/Gb82F5S

### Reproduction Link
XAML: https://pastebin.com/gtZynAS3
Code behind: https://pastebin.com/jVygJq8m

**Comment by kalska** [comment]
This is caused by the fix of issue [#12246](https://github.com/xamarin/Xamarin.Forms/issues/12246). It cannot handle default color, then the TextColor and BackgroundColor becomes the same.
Workaround is to explicit set the TextColor of the Entry control.

**Comment by robtomlinson** [comment]
@kalska Thank you. I can confirm the workaround of explicitly setting the TextColor of the Entry control does indeed work.

**Comment by rachelkang** [comment]
Hi, @robtomlinson - thanks so much for submitting this issue! We'll be investigating this further.

Repro: [Issue12809.zip](https://github.com/xamarin/Xamarin.Forms/files/5532398/Issue12809.zip)
