### ISSUE TITLE
System.DivideByZeroException: Attempted to divide by zero -Tweener.<Start>b__27_0 (System.Int64 step)

### ISSUE THREAD

**Issue by Ajaydaniel22** [xamarin/Xamarin.Forms#12806]
**Description:** 
The crash happens in a page which utilizes  bluetooth to read external iOT device signals and the page  also has a syncfusion linear progress bar which constantly animates horizontally to indicate scan is in progress.

**Steps to reproduce :** 
Crash is rare and not always reproducible, while it has happened three times in two months. 

**Expected Behaviour:**
Application should display the Bluetooth signals periodically while the progress bar animates continuously.

**Actual Behaviour:** 
Occasional crash but once it happens once it will crash until Application cache is cleared or restarted.

**Line of crash** 
https://github.com/xamarin/Xamarin.Forms/blob/b551dd96640d364dbabc72799836ad9ae22d9520/Xamarin.Forms.Core/Tweener.cs#L105
Assuming the 'rate' in the link above is set as 0, which could cause the crash.

**Stack Trace:** 
Tweener.<Start>b__27_0 (System.Int64 step)
Ticker.SendSignals (System.Int64 step)
Ticker.SendSignals (System.Int32 timestep)
AndroidTicker.OnValOnUpdate (System.Object sender, Android.Animation.ValueAnimator+AnimatorUpdateEventArgs e)
ValueAnimator+IAnimatorUpdateListenerImplementor.OnAnimationUpdate (Android.Animation.ValueAnimator animation)
ValueAnimator+IAnimatorUpdateListenerInvoker.n_OnAnimationUpdate_Landroid_animation_ValueAnimator_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_animation)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.113(intptr,intptr,intptr)

**Basic Information**
Version with issue: Xamarin.Forms 4.8.0.1451
Last known good version: ?
IDE: Rider
Platform Target Frameworks:
iOS:  14
Android: 11.0.2

**Device:** 
Google Pixel 2XL(OS 11) and Oneplus 5(OS 10)
Has not occurred in any iOS devices.

**Comment by rachelkang** [comment]
Hi, @Ajaydaniel22 - thanks for submitting this issue. It seems like this a typical [DivideByZeroException](https://docs.microsoft.com/en-us/dotnet/api/system.dividebyzeroexception?view=net-5.0) which gets thrown whenever `Rate` gets set to `0` - so you should make sure that your `Rate` never equals `0`. If you haven't already, see if you can initialize the value of `Rate` or wrap your code in an if null/0 check. 

I'm closing this issue now, but if you think I'm misunderstanding your concern, please feel free to reopen this issue and if possible, share this project or a sample project that reproduces your issue. Thanks again! :)
