### ISSUE TITLE
Xamarin Tizen for Samsung SMART Signage Platform

### ISSUE THREAD

**Issue by dhpanteon** [xamarin/Xamarin.Forms#12802]
Does xamarin support for Samsung SMART Signage Platform? 

.tpk format is not supported by it.

How do create app and install on Signage TV?

Link: https://displaysolutions.samsung.com/solutions/partner-solution/sssp

**Comment by jsuarezruiz** [comment]
cc @rookiejava

**Comment by rookiejava** [comment]
I'm not sure, but as fa as I know sssp is supporting the web app (*.wgt not *.tpk) only. For more detail, please to the below link. http://samsungdforum.com/B2B/Introduction/Sssp_fea

**Comment by dhpanteon** [comment]
How can i generate Tizen build in *.wgt format ?

**Comment by rookiejava** [comment]
> How can i generate Tizen build in *.wgt format ?

Refer to https://docs.tizen.org/application/web/get-started/overview/

**Comment by dhpanteon** [comment]
Meaning that their is no support for xamarin.forms right now.
Is their any plan to support it in future?

**Comment by Redth** [comment]
@rookiejava can this be closed?

**Comment by rookiejava** [comment]
> Meaning that their is no support for xamarin.forms right now.
> Is their any plan to support it in future?

@dhindrik Yes. However, I'm not sure but I know t it is being reviewed internally. I am also hoping to support .NET and Xamarin on more Tizen devices. I will tell you again if there is a new update.

> can this be closed?

@Redth Yes. :-)
