### ISSUE TITLE
[Bug] Listview doesn't show any content

### ISSUE THREAD

**Issue by melakhvision** [xamarin/Xamarin.Forms#12801]
### Description
Listview doesn't display any content even sample data.
My Configuration.
Using : Windows PC
Software: Visual Studio latest version ( 16.8.0 )
Xamarin: Latest Version.

#XAML CODE With Listview   >>>> SCREENSHOT OF RUNING APP 
![Screenshot_20201111-113135](https://user-images.githubusercontent.com/45154979/98808224-11212080-241c-11eb-9631-8030ce31bf9d.png)

    <StackLayout BackgroundColor="#004E56">
        <ListView>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                            <Label Text="No Content To Can Be Display" TextColor="WhiteSmoke"  FontSize="43" FontAttributes="Bold"/>
                            <Label Text="I Don't Know Why" TextColor="RosyBrown" FontSize="35" FontAttributes="Bold"/>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>

#XAML CODE WITHOUT LISTVIEW >>>> SCREENSHOT 

![Screenshot_20201111-114239](https://user-images.githubusercontent.com/45154979/98808390-52193500-241c-11eb-8731-e417db6a6c85.png)

    <StackLayout BackgroundColor="#004E56">
        <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                            <Label Text="No Content To Can Be Display" TextColor="WhiteSmoke"  FontSize="43" FontAttributes="Bold"/>
                            <Label Text="I Don't Know Why" TextColor="RosyBrown" FontSize="35" FontAttributes="Bold"/>
                        </StackLayout>
    </StackLayout>

### Steps to Reproduce
1. 
when I put a custom cell into a listview no data are shown when I run the application.
2. The content only shows when I remove the listview and put a normal stack layout or any view.

3

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android:   8.0 and 9.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
WIth listview
![Screenshot_20201111-113135](https://user-images.githubusercontent.com/45154979/98808459-6ceba980-241c-11eb-848a-f733bfccafe8.png)

Without listview
![Screenshot_20201111-114239](https://user-images.githubusercontent.com/45154979/98808468-707f3080-241c-11eb-9647-e901df77a5e5.png)

### Workaround

I remove the cache of visual studio and xamarin still have the same issue.
The issue on both device my phone and the emulator
I create a new project to see if I miss something still no data can be display in a listview.

**Comment by Martin080793** [comment]
You are using the ListView wrong. 

You did not set a ItemsSource, which results in an empty ListView. 
You need to bind the ItemsSource to the data you want to display. The ItemTemplate describes how the data ist presented. 

Follow this tutorial to understand the ListView: https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/listview/?tabs=vswin

**Comment by melakhvision** [comment]
I set sample data like a label with text it's not because there is no binding that the listview will not display any content.

**Comment by elgonzo** [comment]
No, it does not look like you have set sample data.

You defined a **DataTemplate** with labels. Emphasis on "DataTemplate". A data template is used for rendering items in the ListView.

But i don't see you having bound any collection with (whatever) items to your listview, or otherwise having defined an ItemSource for your list view.. If there are no items for the list view, the data template is not going to be used for rendering items, because there are no items. Hence, all you see is an empty screen.

**Comment by Redth** [comment]
It's been awhile since the OP responded and it looks like this might not actually be a bug.  I'm going to close the issue, please re-open with more info if need be.
