### ISSUE TITLE
[Bug] Shell OnNavigating and OnNavigated are not invoked on ModalPage

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#12803]
### Description
Invoking _Shell.Current.Navigation.PopModalAsync();_ on a ModalPage won't trigger OnNavigating/OnNavigated for that ModalPage.

### Steps to Reproduce

1. Declare a page modal by adding _Shell.PresentationMode="Modal"_
2. Override OnNavigating and OnNavigated for your Shell
3. Start app in debug mode
4. Navigate to your ModalPage
5. Place breakpoints into OnNavigating and OnNavigated
6. Navigate back using _Shell.Current.Navigation.PopModalAsync();_

### Expected Behavior
Invocation of OnNavigating and OnNavigated should be the same as when navigating back from a regular ContentPage.

### Actual Behavior
OnNavigating and OnNavigated are not invoked on ModalPage.

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1560
- Last known good version: -
- IDE: Rider
- Platform Target Frameworks: 
  - iOS:  13.7
  - Android: not tested yet but possibly same behaviour
- Android Support Library Version: 

### Workaround
No one known that will work within the shell area. An alternative could be the usage of OnAppearing and OnDisappearing from ContentPage.

**Comment by rachelkang** [comment]
Hi, @MaxFmi - thanks for submitting this issue! Could you try updating to the nightly or the latest version of XF (5.0.0.1558-pre3) and letting us know if that changes anything? Thanks :)

cc: @PureWeen

**Comment by MaxFmi** [comment]
Tested with Xamarin.Forms 5.0.0.1709-pre4 -> works great. Thanks :-)

**Comment by rachelkang** [comment]
@MaxFmi Awesome!! I'll be closing this issue now then, but please feel free to reopen if the issue resurfaces
