### ISSUE TITLE
[Bug] UWP application cannot run in release mode after updating Visual Studio

### ISSUE THREAD

**Issue by holecekp** [xamarin/Xamarin.Forms#12815]
### Description

After updating from XF 4.8 Service Release 4 to Service Release 5, UWP applications cannot run in the release mode any more. There is an error "Unable to activate Windows Store app". I have reported almost the same bug for 4.8.1269 (https://github.com/xamarin/Xamarin.Forms/issues/11736) in August.

### Steps to Reproduce

1. Download the repro project: 
[ReproUwpReleaseModeCrashWithXF48SR5.zip](https://github.com/xamarin/Xamarin.Forms/files/5530033/ReproUwpReleaseModeCrashWithXF48SR5.zip)
2. Run it in the release mode.

### Expected Behavior
The application works in both debug and release mode (and all new XF versions are tested to run also in the release mode).

### Actual Behavior
The application work in the debug mode but cannot launch in the release mode.

### Basic Information

- Version with issue: 4.8 sr5 (4.8.0.1687)
- Last known good version: 4.8 sr4
- IDE: VS 2019

### Screenshots
![xf4 8sr8bug](https://user-images.githubusercontent.com/24872113/98931363-35453600-24de-11eb-935f-32d3c5b10070.png)

### Workaround

Downgrade to XF 4.8 sr4.

**Comment by rachelkang** [comment]
Hi, @holecekp - thanks for submitting this issue! Unfortunately, I'm not able to reproduce the error message you're seeing in either release or debug mode, and I'm having issues getting your project to build in general.

That being said - if you haven't already, I recommend you try the following steps after switching to release mode:
- Delete the /bin and /obj folders in your solution
- Clean and rebuild solution
- Restore packages
- Unload and reload project

If those steps don't resolve anything and if you don't yet have the latest version of VS, I recommend updating to the latest version of VS and trying again.

If you've done all of this and are still facing issues, please let us know and share your full build logs that capture the error so that we can take a closer look at what's going on! Thanks :)

**Comment by holecekp** [comment]
@rachelkang Hello. This is really weird. I have downloaded the repro project and I could build it. I have found out that reason why it did not run in the release mode was that I was missing a feature flag for gradient brushes (I have downgraded from XF 5 pre 3). When I added the flag, the repro project works. So please ignore the repro project.

However, my full application still does not run in the release mode. But when I downgrade to the 4.8.1560, the problem still persists. This is very strange. Steps that I have tried:
- I have closed VS.
- I have deleted all bin and obj folders in all projects in the solution. I have also deleted .vs folder.
- I have uninstalled the application from Windows manually.
- I have started VS, restored Nuget packages and rebuilt the solution.
- The result is the same. When I try running the project in the release mode, there is an activation error.

I have also checked out the last stable version of my application that I have published into Microsoft Store (again with deleting temporary files). It also uses XF 4.8.1560) and now it also stopped working in the release mode!

I have the latest Visual Studio (16.8.0). It was updated recently. Windows also updated to the latest version (20H2) a few days ago. I am thinking that one of these updates could be causing this problem.

The application does not start also in the debug mode if I enable "Compile with .net native tool chain" for the debug mode:
![error debug with dot net native](https://user-images.githubusercontent.com/24872113/98983211-c0472000-2520-11eb-987e-4f47cc314dc5.png)

Another weird thing is that when delete all temporary files from the original repro project in the original folder (again with cleaning and deleting) it does not run in the release mode. The same project downloaded into another folder works.

Does anybody have the same problem? Do you have any idea how to solve it?

**Comment by holecekp** [comment]
I have deleted unnecessary files from the project one by one and I have found out that the culprit was MyApplication.UWP.csproj.user file. After deleting the file, the application works in the release mode again.

**So if anyone else has a problem with UWP projects after updating Visual Studio to 16.8 (or 16.8.1), try deleting .csproj.user file in the UWP project.**
