### ISSUE TITLE
[Bug] Many type converters ConvertToInvariantString return localized value

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#12828]
### Description
Many type converters use $"{field}" formatting in ConvertToInvariantString. For example PointTypeConverter:

`public override string ConvertToInvariantString(object value)
{
	if (!(value is Point p))
		throw new NotSupportedException();
	return $"{p.X}, {p.Y}";
}`

### Steps to Reproduce

1.  Create new Xamarin app with UWP "head".
2. Add following code to MainPage constructor
`public MainPage()
{
    Point pt = new Point(1.25, 3.67);
    string sEN = ConvertToInvariantString(pt, "en-us");
    string sDE = ConvertToInvariantString(pt, "de-DE");
    if (sEN != sDE)
    {
        string error = $"en={sEN}, de={sDE}";
        throw new InvalidOperationException(error);
    }
}

private static string ConvertToInvariantString(Point pt, string culture)
{
    CultureInfo cultureInfo = CultureInfo.GetCultureInfo(culture);
    Thread.CurrentThread.CurrentCulture = cultureInfo;
    Thread.CurrentThread.CurrentUICulture = cultureInfo;
    PointTypeConverter pointConverter = new PointTypeConverter();
    string result = pointConverter.ConvertToInvariantString(pt);
    return result;
}
`
3. Build and run UWP head.

### Expected Behavior
No exception thrown

### Actual Behavior
Exception with error message "en=1.25, 3.67, de=1,25, 3,67"

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

> VS bug [#1246275](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1246275)

**Comment by StephaneDelcroix** [comment]
good catch. thanks

**Comment by StephaneDelcroix** [comment]
introduced by #12431
