### ISSUE TITLE
Shell UI discrepency between Samsung S20 Pro and Samsung S9

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12820]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Shell-UI-discrepency-between-Samsung-S20/1244239?preview=true)._

---
I have an app which is not showing the same on the shell tab bar between an S9 and S20 Pro. If you look at the correct_image.jpg, the word "Summary" is complete, but on the S20 Pro it is "Summar" (image.jpg) - the final letter is missing. On a One Plus 7, the UI is the same as on the S9. Is this a feature on the S20 Pro or an issue with forms?

I'm using XF 4.8.0.1560 (with XF Material)

---
#### Feedback Bot on 11/5/2020, 06:00 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi, Paul - thanks for submitting this issue. It seems like this is likely a native feature, specific to the device and not XF. I am curious, however, if you see the same behavior without Material and/or if you've seen different behavior on previous versions of XF. Let us know! Thanks :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
