### ISSUE TITLE
Xamarin Picker v4.8.0.1560 .Add Loses International Font Compatibility

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12821]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Xamarin-Picker-v4801560-Add-Loses-In/1247009?preview=true)._

---
\[severity:It's more difficult to complete my work\] I have been using the picker to allow users to select the language of the choice for the application, presenting those selections in the various associated language fonts. With current release of the picker, in all platforms, the .Add() function hangs when presented non-English, Cognitive Services variants of the text; previous versions were functional. The following and attached code is in use. Languages is the instance of the Picker and languageCodes is the Azure language list.  

```
Languages languages = new Languages(); foreach (string language in languages.languageCodes.Keys) { if (language.IndexOf("(") > 0) { selectionText = language.Substring(0, language.IndexOf("(")); } else { selectionText = language; } list.Add(selectionText); } int count = list.Count; for (int i = 0; i < count; i++) { string language = list\[i\]; App.activeLanguage = languages.languageCodes\[language\]; Task translation = App.cognitiveServices.TranslateToText(language); Languages.Items.Add(translation.Result.ToString()); } 
```

---
#### Marc W. George on 11/7/2020, 00:15 AM: 

<p>Another aspect of the problem is that the picker’s selection box doesn’t display the initial indexed list selection or the actual selection.</p>
<p>I have reversed the version of the NuGet from v4.8.0.1560 to v4.8.0.1451 and the display elements have reappeared, but only list items in English continue to be accepted by the picker. It appears that a dependency component which has be upgraded may be also involved.</p>

#### Feedback Bot on 11/9/2020, 05:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rachelkang** [comment]
Hi, Marc - thank you for submitting this issue. Would you be able to share your project or a sample project that reproduces this issue? I'd love to take a closer look to better understand what's happening there.

And for the second bug you described regarding the initial indexed list selection - would you please file a separate bug report for it, and if possible, also with a repro? Thanks so much :)

**Comment by alaskanrogue** [comment]
FYI, I am preparing a sample project.

**Comment by alaskanrogue** [comment]
Sample project that should demonstrate the problem is attached. NOTE: There are several keys that need to be provided to activate the Azure services in use. Search for "XXXXX" in the solution to provide them.

Feel free to reach out if desired for a Teams session.

[Picker.zip](https://github.com/xamarin/Xamarin.Forms/files/5570312/Picker.zip)

**Comment by PureWeen** [comment]
@alaskanrogue would it be possible to just take the strings that are generated by the service and add them into. a text file? or directly into the code behind?

Also what platform are you seeing this on. Apologies if you mentioned that somewhere but I'm not seeing where that's indicated

**Comment by PureWeen** [comment]
@alaskanrogue are you seeing the issue on 4.8.0.1534?

**Comment by alaskanrogue** [comment]
@PureWeen I was not seeing the problem before v4.8.0.1560. Both Android and iOS have the problem. I believe UWP had the problem as well, but I can't verify at this time because of another problem on that platform. An example solution is already attached to this issue.

**Comment by alaskanrogue** [comment]
@PureWeen Were you able to use the example solution to reproduce and see the problem?

**Comment by alaskanrogue** [comment]
After digging very deep and performing a thread syncing analysis, discover that the Cognitive Services Authentication component that establishes the necessary streams was no longer completing its task before the initialization process of the picker. Therefore the translation was not being performed. The default for no connection is the use of the English based languages collection. Controlling the tread executions enabled the goal of a multilingual picker. This issue can be closed.

![Screenshot 2021-01-01 202954](https://user-images.githubusercontent.com/14001196/103449165-633f2f00-4c72-11eb-8faf-c6bbe9026732.png)
