### ISSUE TITLE
Using custom fonts into WebView with fonts used by ExportFont

### ISSUE THREAD

**Issue by haiduong7411** [xamarin/Xamarin.Forms#12832]
Im using ExportFont in my Xamarin Application. When I use WebView, It needed add custom font but I can not use with ExportFont. I still use .ttf file for each platform (Android Assets and iOS Resources). 

I hope in the future i will do it if current we have not solution.

**Comment by rachelkang** [comment]
Hi, @haiduong7411 - here's a related discussion in our forums that you may find helpful: https://forums.xamarin.com/discussion/33404/set-custom-font-in-webview

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
