### ISSUE TITLE
[Bug] Xamarin Forms Shell OnNavigated not trigger and some features not working properly when long clicking on back button

### ISSUE THREAD

**Issue by unamed000** [xamarin/Xamarin.Forms#12831]
### Description
In iOS 14, Apple add a new behavior for back button that would let user to hold on it and navigate back to multiple levels
https://9to5mac.com/2020/06/23/ios-14-sound-recognition-more/

Because of this, the OnNavigated and Shell.TabBarIsVisible="True" is not working anymore when user back to the root page of the TabBar.

### Steps to Reproduce
1. Make a Xamarin Forms Application Shell with TabBar
2. Make a event handler for OnNavigated for the Shell
3. Make some deeper navigation with TabBar
4. In some deeper page, set the Shell.TabBarIsVisible="False"
5. For the TabBar ShellContent , set Shell.TabBarIsVisible="True" to make sure the TabBar is show when these page are shown
6. Navigate to inner page, long pressing the back button

### Expected Behavior

- OnNavigated on the Shell is triggered
- The Shell.TabBarIsVisible still working like normal press

### Actual Behavior

- OnNavigated not triggered
- The Shell.TabBarIsVisible not working when user return to root page of tab bar

### Basic Information

- Version with issue: Xamarin Forms 4.8.0.1560
- Last known good version: None
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  12.1
- Nuget Packages:
- Affected Devices: All ios devices

### Workaround
I can't find any workaround or anyway to disable the long clicking behavior

**Comment by rachelkang** [comment]
Hi, @unamed000 - thanks for submitting this issue! Could you try updating to the nightly or the latest version of XF (5.0.0.1558-pre3) and letting us know which, if any, of these bugs that might resolve? Thanks 👍 

cc: @PureWeen

**Comment by unamed000** [comment]
Hi @rachelkang , thanks for reaching me out.

Unfortunately, my app turn blank when i upgrade to 5.0.0.1558-pre3 :|. So i can't test this version if my problem is solved.
For now, my workaround is i override the back button and implement our back button to prevent this default behavior, though i don't think this is the correct way to do it for iOS app.

**Comment by Redth** [comment]
Please re-open with a repro if you're able to in the future.  Thanks.
