### ISSUE TITLE
System.MissingMethodException when debug on existing project

### ISSUE THREAD

**Issue by YZ-cheerup** [xamarin/Xamarin.Forms#12833]
### Steps to Reproduce
1. Install VS ( 16.9 preivew1.0 and 16.8.1 ).
2. Open project with path https://github.com/xamarin/xamarin-forms-samples and using AzureNotificationHub\NotificationHubSample.sln.
3. Update Xamarin/Forms NuGet to 5.0.0.1709-pre4.
4. Choose one of the available Android physical devices.
5. Select menu Build > Build Solution.
6. Select Debug Menu > Start Without Debugging.

### Expected Behavior
 Check that the application successfully deployed to this device
### Actual Behavior
 popup a exception dialog as below picture.
![image](https://user-images.githubusercontent.com/69567385/99064112-745bb000-25e0-11eb-9b15-4d80357a57ab.png)

### Basic Information

- Version with issue:
- Last known good version: **Nuget Packages: Xamarin Forms 4.8.0.1687**
- Nuget Packages: Xamarin Forms 5.0.0.1709-pre4
- Affected Devices: Android

### Screenshots
![XF5](https://user-images.githubusercontent.com/69567385/99062960-bc79d300-25de-11eb-9b34-a94913dd553a.gif)

**Comment by StephaneDelcroix** [comment]
does this still happens after a clean/restart of the IDE ?

**Comment by YZ-cheerup** [comment]
I tried the scenario a few more times today, I don't know why but the issue didn't reproduce (even I didn't restart the VS after switched from 4.8 to 5.0).
