### ISSUE TITLE
[Bug] Path not rendered on page reload

### ISSUE THREAD

**Issue by GarryPSmith** [xamarin/Xamarin.Forms#12844]
### Description

Using a Path to provide a shaped background on a page in a Shell app. The Path is correctly rendered on the initial page load but when you switch to another page then back to that page the Path is not rendered.

### Steps to Reproduce

1. Create a new project from the Mobile App (Xamarin Forms) template.
2. Update the project to the Xamarin Forms v5 Nuget package and change Android Target Framework to 10.
3. Replace the contents of the ItemsPage.xaml with the Path as below.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="TestApp.Views.ItemsPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:TestApp.ViewModels"
    xmlns:model="clr-namespace:TestApp.Models"
    x:Name="BrowseItemsPage"
    Title="{Binding Title}">

    <Path
        Aspect="Fill"
        Data="m 0,0 h 100 v 41.910828 c 0,0 -14.861996,6.878981 -50,0 -35.138004,-6.878981 -50,0 -50,0 z"
        StrokeThickness="0">
        <Path.Fill>
            <SolidColorBrush Color="DarkBlue" />
        </Path.Fill>
    </Path>

</ContentPage>

### Expected Behavior

Path is displayed on the page.

### Actual Behavior

Path is displayed on initial page load but when you navigate to the About page and back to the Browse page it is not rendered.

### Basic Information

- Version with issue: 5.0.0.1558-pre3
- Last known good version: ?
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: v10
  - UWP:  not tested
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms (5.0.0.1558-pre3), NETStandard.Library (2.0.3)
- Affected Devices:

### Screenshots

Initial load of page:
![Screenshot_1605302650](https://user-images.githubusercontent.com/14044031/99123617-6dd93280-25f8-11eb-8f8a-dfc9b531e2eb.png)

After navigating away from page and back to it:
![Screenshot_1605302657](https://user-images.githubusercontent.com/14044031/99123689-99f4b380-25f8-11eb-8bfb-00a4ddb0d43e.png)

**Comment by rachelkang** [comment]
Hi, @GarryPSmith - thanks for submitting this issue! 
Confirming that I'm able to repro [Issue12844.zip](https://github.com/xamarin/Xamarin.Forms/files/5539613/Issue12844.zip) and that we'll be looking into this further.

cc @jsuarezruiz
