### ISSUE TITLE
[Bug] CarouselView position resets when visibility toggled.

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#12848]
### Description

CarouselView resets its position when its visibility is changed. It appears from the CarouselViewRenderer code that it is trying to restore the position, but for some reason is not.

### Steps to Reproduce

1. Move CarouselView to another position.
2. Set CarouselView IsVisible=false
3. Set CarouselView IsVisible=true
4. Observe that the CarouselView position has been lost

### Expected Behavior

CarouselView should retain its set position.

### Actual Behavior

CarouselView resets to the 0 position.

### Basic Information

- Version with issue: 4.8.0.1687, 5.0.0.1558-pre-3
- Last known good version: 4.7
- IDE: VS 2019 16.8.1
- Platform Target Frameworks: 
  - Android: 11.0 

### Reproduction Link

[CarouselVisibilityReset.zip](https://github.com/xamarin/Xamarin.Forms/files/5540277/CarouselVisibilityReset.zip)

**Comment by jsuarezruiz** [comment]
On iOS works as expected.
