### ISSUE TITLE
When will Linux be supported?

### ISSUE THREAD

**Issue by dsubiros** [xamarin/Xamarin.Forms#12849]
## Summary
I have been trying to setup Xamarin development in Linux (Ubuntu), but I haven't found any "official" way to do it, or any modern IDE to do it for me.

## Intended Use Case
I have for years been working in Ubuntu, and just recently I started to work with Rider/.NetCore 3.1. I have been reading about Xamarin and sounds awesome, but please, with so many developers using any kind of Linux, why haven't you setup support for Linux? Don't you guys think you are missing this Linux-only community of developers?

Thanks and may God bless you all!

**Comment by jsuarezruiz** [comment]
There is a community supported GTK # backend:
https://github.com/jsuarezruiz/forms-gtk-progress

I've even done tests using MonoDevelop, etc:
![weather-debug-linux](https://user-images.githubusercontent.com/6755973/99234132-6e3e1d00-27f4-11eb-9a29-c751ac8f10fb.gif)

Here a list of samples: https://github.com/jsuarezruiz/xamarin-forms-gtk-samples

And there are some repositories with guides to getting Android ready to use on Linux: https://github.com/0xFireball/xamarin-android-linux

To have specific actions that we can improve, perhaps, a basic documentation section with the IDE configuration, etc?

**Comment by NickMaev** [comment]
What about native support for Linux?

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Forms anymore. I think there is an extensive discussion going on about this for .NET MAUI. Please have a look there and add your upvote so we can prioritize accordingly. Thanks!
