### ISSUE TITLE
[Enhancement] Support stretch/adaptive size on RoundRectangleGeometry

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#12857]
## Summary
Support `stretch/adaptive/dynamic` size on [RoundRectangleGeometry](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/Shapes/RoundRectangleGeometry.cs).

Currently a fixed size must be defined on [Rect](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/Shapes/RoundRectangleGeometry.cs#L25) property.

As mentioned by @davidortinau on [Xamarin.Forms 5 Is Here! | The Xamarin Show (18:10)](https://youtu.be/ttF80UnrJAg?t=1090), it would be useful to support a dynamic/unknown size.

## API Changes
- Support `Rect="0,0,*,*"`?
- Support `Height|Width="Auto|double"`?
- Support `Aspect="None|Fill|Uniform|UniformToFill"`?

## Intended Use Case
Round corners on unknown element size.

**Comment by jsuarezruiz** [comment]
Could be similar to: https://github.com/xamarin/Xamarin.Forms/issues/11482.

**Comment by YZahringer** [comment]
@jsuarezruiz I try to implement it with a `CornerRadiusEffect` and add it to `Xamarin Community Toolkit`. This would allow to have `CornerRadius` everywhere in Xamarin.Forms, until https://github.com/dotnet/maui/pull/650.

This works well on iOS and Android, but `RoundRectangleGeometry` has no effect on UWP.

Any reason why the `Clip` with `GeometryGroup` does not work on UWP? Do you maybe have a workaround?

Related issue: https://github.com/xamarin/Xamarin.Forms/issues/14275
WIP implementation: [CornerRadiusEffect](https://github.com/MADSENSE/Madsense.XamarinForms.Sample/blob/bug-uwp-clip/src/Madsense.XamarinForms.Sample/Effects/CornerRadiusEffect.cs)

**Comment by brminnick** [comment]
Thanks @YZahringer! Could you close this now that the PR has been merged? https://github.com/xamarin/XamarinCommunityToolkit/pull/1316

For some reason, GitHub isn't giving me the option to close this myself 🤷‍♂️

**Comment by YZahringer** [comment]
Fixed on MAUI: https://github.com/dotnet/maui/pull/2445
Fixed on XCT: https://github.com/xamarin/XamarinCommunityToolkit/pull/1316
