### ISSUE TITLE
[Bug] FontImage doesn't support Color as DynamicResource

### ISSUE THREAD

**Issue by maxkoshevoi** [xamarin/Xamarin.Forms#12851]
### Description
`FontImage` doesn't support `DynamicResource` for `Color` property, but supports `StaticResource`

### Steps to Reproduce

1. Add two images to any page (image itself doesn't matter, so we can omit `FontFamily `and `Glyph`):
```xaml
<Image Source="{FontImage Color={StaticResource PrimaryColor}}"/>
<Image Source="{FontImage Color={DynamicResource PrimaryColor}}"/>
```
2. First image won't have any errors, second one will fail with 

> Cannot assign property "Color": Property does not exist, or is not assignable, or mismatching type between value and property

### Expected Behavior
`DynamicResource` can be assigned to `Color` property

### Actual Behavior
`DynamicResource` cannot be assigned to `Color` property

### Basic Information

- Version with issue: 4.8
- Last known good version: -
- IDE: VS2019 16.8.1
- Platform Target Frameworks: 
  - iOS:  
  - Android: 11
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/6609929/99147143-2e0d5c00-2687-11eb-8147-3cbb7e1ffbb9.png)

### Workaround
Use `FontImageSource`

```xaml
<Image>
    <Image.Source>
        <FontImageSource Color="{DynamicResource PrimaryColor}" />
    </Image.Source>
</Image>
```

**Comment by StephaneDelcroix** [comment]
@jsuarezruiz you know what to do here :)

**Comment by spyder81** [comment]
i need that

**Comment by StephaneDelcroix** [comment]
FontImageExtension.Color is _not_ a Bindable property, so you can't Bind to it, or use a DynamicResource

**Comment by StephaneDelcroix** [comment]
instead of 
```xaml
<Image Source="{FontImage Color={DynamicResource PrimaryColor}}"/>
```

use
```xaml
<Image Source="{FontImageSource Color={DynamicResource PrimaryColor}}"/>
```

and that works like a charm. I'm deprecating FontImageSource to avoid confusion in the future

**Comment by maxkoshevoi** [comment]
Oww, so `FontImageSource` can be used in this way too. That's awesome! Thanks for the resolution

**Comment by maxkoshevoi** [comment]
I cannot use `FontImageSource` as a MarkupExtension yet. According to your PR, this functionality will be available in XF5. Is that correct?

![image](https://user-images.githubusercontent.com/6609929/99649930-777df280-2a5d-11eb-8b4b-a739bdb5d940.png)

**Comment by StephaneDelcroix** [comment]
you can use it as a MarkupExtension. ignore the message from intellisense

**Comment by maxkoshevoi** [comment]
It does work, thank you. Could you please tell me, how can I suppress this error in `.editorconfig`?
Tried this `dotnet_diagnostic.XLS0505.severity = none`, but it didn't work.

Also, could you please inherit `FontImageSource` from `MarkupExtension` in your PR, to resolve this error?

**Comment by StephaneDelcroix** [comment]
I've reported this error to Xaml Intelisense.

> Also, could you please inherit `FontImageSource` from `MarkupExtension` in your PR, to resolve this error?

no, that would be wrong

**Comment by maxkoshevoi** [comment]
@StephaneDelcroix thanks again for resolving this issue.
While we are on topic of `FontImageSource` could you please take a look at this: https://github.com/xamarin/Xamarin.Forms/issues/6421? 
`FontImageSource` doesn't support styling so, for example, `FontFamily` needs to be specified every time even if I have only one image font for my application.

**Comment by maxkoshevoi** [comment]
> I've reported this error to Xaml Intelisense.

Hi, are there any news about this incorrect exception?  It's still reported with latest Visual Studio (16.8.4) and Xamarin.Forms (5.0.0.1874).

**Comment by vmp1r3** [comment]
I cannot reference `FontImageSource`

**Comment by jfversluis** [comment]
Seems you need to use `<Image Source="{FontImageSource Color={DynamicResource PrimaryColor}}"/>` and it works. The error isn't great, but I think for Forms it is what it is 🤷
