### ISSUE TITLE
[Shell] Adding BackButtonBehaviour to target page and navigating back to root page hides tabview in root page

### ISSUE THREAD

**Issue by aniruthg** [xamarin/Xamarin.Forms#12869]
### Description
Adding BackButtonBehaviour to target page and navigating back to root page hides tabview in root page

### Steps to Reproduce

1. Have a tabview in rootpage
2. Navigate from "root page" => "target page"
3. set the back button behaviour in target page and set the tabview visibility to false in the target page
3. navigate back from "target page" => "root page"

### Expected Behavior
Tabview in the "root page" should be visible
### Actual Behavior
Tabview in the "root page" is invisible in iOS, Works all good in Android

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1687
- Last known good version:
- IDE: Visual Studio for Mac, Visual studio
- Platform Target Frameworks:  iOS
  - iOS:  Version: 14.2.0.12

- Nuget Packages:
- Affected Devices: iOS all devices

### Screenshots

![out](https://user-images.githubusercontent.com/5231163/99282531-d4a95680-2859-11eb-9279-0bf0992a2a56.gif)

**Comment by jsuarezruiz** [comment]
@aniruthg To see how you create the Tabs and especially the navigation, could you attach a small example where reproduce the issue?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
