### ISSUE TITLE
[Bug] OnIdiom with TargetType Rect causes InvalidCastException on UWP

### ISSUE THREAD

**Issue by jrooke81** [xamarin/Xamarin.Forms#12866]
### Description
Using OnIdiom with TargetType Rectangle results in a build error for usual OnIdiom properties e.g. Default, Desktop, Phone etc (see Screenshot 1)

Setting flags to use experimental shapes and changing the TargetType to Rect allows these properties to be set. However on launch it results in an InvalidCastException being thrown (see Screenshot 2)

### Steps to Reproduce
1. Add an OnIdiom with TargetType Rectangle to the view's resources, see build error
2. Set flag "Shapes_Experimental" in platform project
3. Add an OnIdiom with TargetType Rect to the view's resources,
4. Use the resource key as a StaticResource in an AbsoluteLayout LayoutBounds property
5. Run application

### Expected Behavior
TargetType Rectangle should allow OnIdiom properties to be set
Experimental Shapes TargetType Rect should not throw an InvalidCastException

### Actual Behavior
TargetType Rectangle does not allow OnIdiom properties to be set
Experimental Shapes TargetType Rect throws an InvalidCastException

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: 4.2.0.848062
- IDE: Visual Studio Enterprise 2019
- Platform Target Frameworks:
  - iOS : N/A
  - Android: N/A
  - UWP:  18362 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials, UWP, NETStandard.Library
- Affected Devices: Windows Desktop

### Screenshots
Screenshot 1:
![image](https://user-images.githubusercontent.com/47103652/99255590-0dbada00-280c-11eb-9cea-ec5837599fb1.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/47103652/99255617-17444200-280c-11eb-90da-4a5c0ca52d47.png)

### Reproduction Link

[TestRectangleSample.zip](https://drive.google.com/file/d/1vq_VWajmBeuPcTo8g5jdNgtBSxE5GHS-/view?usp=sharing)

### Workaround

Setting inline in the Xaml for Default Idiom and then adding if checks in the code behind constructor to check device idiom and set accordingly:
`if (Device.Idiom == TargetIdiom.Phone)
{
    AbsoluteLayout.SetLayoutBounds(stkTest, new Rectangle(1, 0, 0.5, 1));
}`

**Comment by StephaneDelcroix** [comment]
looks like you're using a `OnIdiom<Rect>` on a property of type `Rectangle`. (some properties were changed from Rectangle to Rect in 4.8)

**Comment by jfversluis** [comment]
Assuming this is fixed, thanks!
