### ISSUE TITLE
[Bug] OnIdiom detects wrong idiom on some devices

### ISSUE THREAD

**Issue by zillemarco** [xamarin/Xamarin.Forms#12863]
### Description
A customer lamented some layout errors that we found were coused by a wrongly detected idiom on its device.
He is unsing a Redmi Note 8T rurring Android 10.
Doing some debug we found that when he changes the system's font size to something smaller that the default one, the recognized idiom was `Desktop` in the case of the smallest possible font and `TV` in the case of the smaller font.

### Steps to Reproduce

Go to device settings and change the font size scaling to something smaller that the default `Small` value.

### Basic Information

- Version with issue: 4.8
- Last known good version: None
- Platform Target Frameworks:
  - Android: Android 10 
- Affected Devices: Redmi Note 8T

**Comment by jsuarezruiz** [comment]
This issue have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/11206 in Xamarin.Forms 5.0.
