### ISSUE TITLE
[Bug] iOS 14 App freezes when password is entered after email (not completely fixed)

### ISSUE THREAD

**Issue by NeilN1** [xamarin/Xamarin.Forms#12868]
### Description
#12246  not completely fixed 
### Steps to Reproduce

1. Enter username
2. Enter one or more characters in password field
3. Tap anywhere else on screen

### Expected Behavior
Focus changes to tapped control

### Actual Behavior
No focus change, buttons can't be tapped

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: N/A
- IDE: VS Mac  8.8 build 2913
- Platform Target Frameworks: 
  - iOS:  14.1
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

```XML
    <ContentPage.Resources>
    <ResourceDictionary>
      <converter:BoolToButtonImageConverter x:Key="BoolImageConverter"/>
     
            <Style x:Key="EntryStyle" TargetType="Entry">
                <Setter Property="PlaceholderColor" Value="LightGray"/>
                <Setter Property="TextColor" Value="White"/>
                <Setter Property="Margin" Value="20,4"/>
                <Setter Property="WidthRequest" Value="240"/>
                <Setter Property="HorizontalOptions" Value="CenterAndExpand"/>
            </Style>
           
  
     </ResourceDictionary>
  </ContentPage.Resources>

                    <Grid x:Name="Grid_Main">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="70"/>
                        <RowDefinition Height="70"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="4*"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>
                        <Entry
                            Grid.Row="0"
                            Grid.Column="0"
                            x:Name="UserNameEntry"
                            Style="{StaticResource EntryStyle}"
                            Text="{Binding Path=User.UserName}"
                            Placeholder="Username"
                            HorizontalOptions="End"/>
                        <Entry
                            Grid.Row="1"
                            Grid.Column="0"
                            x:Name="PasswordEntry"
                            Placeholder="Password"
                            Style="{StaticResource EntryStyle}"
                            Text="{Binding Path=User.Password}"
                            IsPassword="True"/>
                        <control:RoundButtonControl
                           x:Name="ShowButton"
                            Grid.Row="1"
                            Grid.Column="1"
                            Command="{Binding ShowPasswordCommand}"
                            FontFamily="FontAwesomeSolid"
                            Text="&#xf06e;"
                            HorizontalOptions="Start"/>
                        <control:RoundButtonControl
                           x:Name="HideButton"
                            Grid.Row="1"
                            Grid.Column="1"
                            Command="{Binding HidePasswordCommand}"
                            FontFamily="FontAwesomeSolid"
                            Text="&#xf070;"
                            IsVisible="false"
                            HorizontalOptions="Start"/>
                   </Grid>
```

Note that if password is entered before userid then taps to change focus work, even if password entry is completely deleted, userid entered, and password re-entered.

**Comment by jsuarezruiz** [comment]
I have created a sample:

[Issue12868.zip](https://github.com/xamarin/Xamarin.Forms/files/5553317/Issue12868.zip)

@hartez I cannot reproduce the issue. I think you were the one who fixed #12246, could you test the attached sample?

![issue12868](https://user-images.githubusercontent.com/6755973/99388497-fb0cd780-28d5-11eb-9516-c9fdd346a843.gif)

**Comment by NeilN1** [comment]
Hi @jsuarezruiz  Your sample does not include Material which seems to play a part in this issue.

**Comment by PureWeen** [comment]
@NeilN1 can you try with this repro that uses material and 5.0 pre5?

I'm not getting any crashes
[Issue12868 2.zip](https://github.com/xamarin/Xamarin.Forms/files/5669603/Issue12868.2.zip)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by JPZV** [comment]
@Redth I have exactly the same issue, and no workaround seems to work.

I tried @PureWeen 's sample and it works, so, after researching, I found out that this issue is being triggered with iOS password generator, so, in order to replicate it, you have to implement a "working" Sign Up page either using Associated Domains plus Keychain, or using an authentication provider (Like Firebase)

Please, try this sample (Remember to fill Entitlements.plist with a valid domain and set up that page with a valid [JSON](https://developer.apple.com/documentation/xcode/supporting-associated-domains))
: [Issue12868.zip](https://github.com/xamarin/Xamarin.Forms/files/7563538/Issue12868.zip)

Please, be aware: iOS **MUST** prompt you to use a strong generated password, you **HAVE** to select "Use own password", otherwise the app will not freeze at all. If iOS doesn't prompt you anything (i.e. you didn't set an associated domain), the app will also not freeze.

I tested this sample using the latest Visual Studio for Mac, and with an iPhone 8 (iOS 15.0.1)
