### ISSUE TITLE
[Bug] Elements do not revert to style after clearing local properties if style is not in root ResourceDictionary

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#12874]
### Description
Elements do not revert to style after clearing local properties if style is not in root ResourceDictionary.
[MainPage.xaml.zip](https://github.com/xamarin/Xamarin.Forms/files/5549735/MainPage.xaml.zip)

### Steps to Reproduce

1. Create Xamarin.Froms app with UWP head
2. Update MainPage.xaml and MainPage.xaml.cs to match attached code
3. Build and run.
4. Click on button.

### Expected Behavior
App shows text "HorizontalOptions should revert to Center but it is Center"

### Actual Behavior
App shows text "HorizontalOptions should revert to Center but it is Fill"

### Basic Information

- Version with issue: 5.0.0.1709-pre4 and 5.0.0.1558-pre3 (maybe in other builds)
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

> VS bug [#1247655](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1247655)

**Comment by jsuarezruiz** [comment]
Attached sample using the MainPage files:
[Issue12874.zip](https://github.com/xamarin/Xamarin.Forms/files/5552613/Issue12874.zip)

**Comment by jsuarezruiz** [comment]
The S1 style is applied with HorizontalOptions Center, but it is overridden by directly assigning the Start value in the Label.
So, before tapping the Button the value of HorizontalOptions is Start. Tapping the Button and using `ClearValue`, it eliminates the Start value and the default value of HorizontalOptions remains, which is Fill https://github.com/xamarin/Xamarin.Forms/blob/f35ae07a0a8471d255f7a1ebdd51499e10e0a4cb/Xamarin.Forms.Core/View.cs#L20

**Comment by etvorun** [comment]
@jsuarezruiz @xamarin-release-manager 
Please reactivate this bug. It blocks Hot Reload.

**Comment by StephaneDelcroix** [comment]
@etvorun I observe the same behaviour if the resource is defined at Grid or root (ContentPage) level
