### ISSUE TITLE
Problem with "Clicked" property inside RadioButton on ios

### ISSUE THREAD

**Issue by rozek1szymon** [xamarin/Xamarin.Forms#12879]
### Description
Only for iOS
"Clicked" property in RadioButton throws  following error : 
"Incompatible Delegate Types. First is System.Collections.ObjectModel.ObservableCollection`1[[Xamarin.Forms.Element, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] second is System.EventHandler.'
"

### Steps to Reproduce

1. Create some page with RadioButton inside
2. Add "Clicked" property inside 
3. 

### Expected Behavior
Properly working Clicked 

### Actual Behavior
on page open an error is thrown in page.xaml.g.cs : "Incompatible Delegate Types. First is System.Collections.ObjectModel.ObservableCollection`1[[Xamarin.Forms.Element, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]] second is System.EventHandler.'
"

### Basic Information

- Version with issue:  5.0.0.1709-pre4
- Last known good version: XF 4.8
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  14.2

- Affected Devices:
all the iphones

### Screenshots

![image](https://user-images.githubusercontent.com/38460886/99384252-6ef7b180-28cf-11eb-9836-e789bdd8cc44.png)

**Comment by jsuarezruiz** [comment]
@rozek1szymon Could you attach a sample where reproduce the issue?. I have tried to reproduce creating a new sample, but without success. Or, could you share your RadioButton definition?. RadioButton has the `CheckedChanged` event but not `Clicked`.

**Comment by rozek1szymon** [comment]
` <RadioButton TextColor="Gray" BackgroundColor="Transparent" Margin="0,0,0,20" HorizontalOptions="Center" x:Name="DarkButton" ClassId="1"
                                Clicked="Button_OnClicked" Grid.Row="4" Grid.Column="1">
                        <RadioButton.Margin>
                            <OnPlatform x:TypeArguments="Thickness">
                                <OnPlatform.Platforms>
                                    <On Platform="iOS" Value="5,0,0,20" />
                                    <On Platform="Android" Value="-6,-5,-4,15" />
                                </OnPlatform.Platforms>
                            </OnPlatform>
                        </RadioButton.Margin>
                    </RadioButton>`

I used to have this radio button. In my case I have 7 radiobuttons, when I can have all unchecked, and all checked, so Checked property was good for me, I could have clik and unclick the radio button, I can still do this on android, but I cant on Ios

**Comment by jsuarezruiz** [comment]
But, RadioButton `Clicked` event not exists in 5.0-pre4. After update, you must get the following error compiling:

`Error XFC0009: No property, BindableProperty, or event found for "Clicked", or mismatching type between value and property. `

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
