### ISSUE TITLE
[Bug] Maps crashing in UWP

### ISSUE THREAD

**Issue by theescapers** [xamarin/Xamarin.Forms#12878]
### Description

Since this morning, my app with a Map embedded crashing when map is shown, this is only affecting UWP maps, so assumed to be a Bing maps specific issue.

It's affecting an app that was shipped over a year ago, so maybe Bing Maps backend has changed and is causing the crash?

If wifi is turned off, the crash does not occur.

### Steps to Reproduce

1. Download and run https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps
2. Use one of the options to open a map.
3. Crash.

### Expected Behavior

Doesn't crash.

### Actual Behavior

Crashes

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All Windows devices, tested on 5 different ones..

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps

### Workaround

Currently no, other than to disable the map for UWP devices.

**Comment by theescapers** [comment]
Investigating a little more... This may me a UWP or Maps backend issue, as this UWP/C# (not Xamarin) sample also exhibits the same problem.

https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/mapcontrol/

**Comment by KirstyLH** [comment]
Been getting the same problem in our UWP app on Xamarin.Forms today.  Only started today - we haven't made a code change in a couple of months.  Completely crashes the app with no useful error messages.

**Comment by premiaware** [comment]
I have same problem with my pure UWP App, the App crash if i zoom inside map, is a disaster all customers is blocked!!!!!
any of you have any suggestions?

**Comment by ptripathi-svmx** [comment]
Facing same app crash issue with our UWP app as well. App crashes on accessing any feature that uses bing maps (primarily location related).

**Comment by Russc0** [comment]
Same issue here. Not Forms specific as many non forms apps are crashing also.
If you use satellite mode it works fine. 
Seems to be since latest windows update.
Microsoft's own Map Stylesheet editor app is also not working.

**Comment by shabroek** [comment]
Same issue here. An empty mapcontrol works, as soon as we try to interact with it, it crashes

**Comment by jordyvanderpoel** [comment]
We're also affected by this issue. It seems to crash when changing the zoom level with MapType = street

**Comment by DaanTul** [comment]
Does not seem to limit to Xamarin.Forms. It is a general issue with UWP MapControl

**Comment by premiaware** [comment]
ok but ms can't block apps like this bugs, i work with my app.
It is unacceptable that it does not work. Who can we write to to solve this problem quickly?

**Comment by DaanTul** [comment]
Multiple issues opened on the component itself:

https://github.com/microsoft/microsoft-ui-xaml/issues/3614

https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by jsuarezruiz** [comment]
This issue started to happen a few hours ago, out of nowhere (Nov 17th midnight UTC).

The UWP MapControl is launching an exception: `fail_fast_fatal_app_exit_c0000409_bingmaps.dll!mapcontrol::detailtexturesource::begingettexture`

Affects to Xamarin.Forms.Maps in UWP but also, using the MapControl directly in an UWP App.

As @DaanTul mentioned, there are several issues opened in Microsoft UI XAML and will try to move the issue as quickly as possible.

**Comment by KliffCo** [comment]
Issue can be recreated by creating a new UWP app and adding the 2 following lines to the xaml in the appropriate places:
xmlns:maps="using:Windows.UI.Xaml.Controls.Maps"
<maps:MapControl>

Will crash either straight away or as you zoom in. different zoom levels from different DPI monitors.
Going offline or changing to Aerial maps stops the crash.. though this isn't a valid option for us. I have been trying to make a MapStyleSheet that might fix it with no luck. Even tried setting visible=false to all elements in the css. I guess rastered maps work but not vectors. though the vector roads work on Aerial mode

**Comment by SBI-** [comment]
Can anyone else confirm that just the default Maps App by itself also crashes since today? We're seeing a bunch of clients with Maps instantly crashing, regardless of calling with a xamarin component or without.

**Comment by DaanTul** [comment]
@SBI-  microsoft/microsoft-ui-xaml#3614

**Comment by dunclaw** [comment]
A maps data service was returning invalid data. This has been mitigated and the map control should be working normally.
