### ISSUE TITLE
[Bug] Grid height is not correctly computed on 4.8.0.1687

### ISSUE THREAD

**Issue by usausa** [xamarin/Xamarin.Forms#12900]
### Description

I have a layout with grids and labels.
When I updated to the new version of Xamarin.Forms(4.8.0.1687), the layout is now broken.
Also, in the new version the layout varies depending on the value of the label.

### Steps to Reproduce

1. See xaml below

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="LayoutSample.MainPage">

    <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">

        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Grid Grid.Row="0"
              Background="Red">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="Auto" />
                <ColumnDefinition Width="2*" />
            </Grid.ColumnDefinitions>

            <Label Grid.Column="0"
                   Text="Type"
                   FontSize="Large"
                   HorizontalOptions="Start"
                   VerticalOptions="Center" />
            <Label Grid.Column="1"
                   Text="123"
                   Background="White"
                   FontSize="Large"
                   VerticalOptions="Center" />
            <Label Grid.Column="2"
                   Text="No"
                   FontSize="Large"
                   HorizontalOptions="Start"
                   VerticalOptions="Center" />
            <Label Grid.Column="3"
                   Text="999-999"
                   Background="White"
                   FontSize="Large"
                   VerticalOptions="Center" />
        </Grid>

        <BoxView Grid.Row="1"
                 Background="Blue" />

    </Grid>

</ContentPage>
```

### Expected Behavior

See a screenshot of 4.8.0.1560.

### Actual Behavior

See a screenshot of 4.8.0.1687.

### Basic Information

Version with issue: 4.8.0.1687
Last known good version: 4.8.0.1560
Platform : Android

### Screenshots

* 4.8.0.1560

![4.8.0.1560](https://user-images.githubusercontent.com/1298839/99634986-b1aeba80-2a84-11eb-8010-13477e9aaad6.png)

* 4.8.0.1687

![4.8.0.1687](https://user-images.githubusercontent.com/1298839/99635034-c4c18a80-2a84-11eb-9d2c-19391a54c6a5.png)

* 4.8.0.1687 (Label.Text is empty)

![4.8.0.1687b](https://user-images.githubusercontent.com/1298839/99635086-d5720080-2a84-11eb-9f40-148608f246f1.png)

**Comment by jsuarezruiz** [comment]
Attached repro sample: [Issue12900.zip](https://github.com/xamarin/Xamarin.Forms/files/5565415/Issue12900.zip)

**Comment by transis2** [comment]
Same issue for me

**Comment by MagicAndre1981** [comment]
I also see this in Android and UWP

**Comment by nZeus** [comment]
Hi. We cannot upgrade `Xamarin.Forms` from `4.6.0.726` to `4.8.0.1687` because we also have the same issue. `Height="70*"` doesn't work anymore.
