### ISSUE TITLE
Error CS0234 The type or namespace name 'Maps' does not exist in the namespace 'Xamarin.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#12905]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Error-CS0234-The-type-or-namespace-name-/1231752?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio]
After adding the nuget for Xamarin.Forms, I still can't use the line 
using Xamarin.Forms.Maps;

I tried clearing the NuGet cache to no avail (even cleared it with the commandline nuget.exe tool).  Tried uninstalling Xamarin.Forms and Xamarin.Essentials, also did not work. 

Any help would be greatly appreciated.
Visual Studio about data including nuget and xamarin form versions also included if this helps you: 
Microsoft Visual Studio Professional 2019
Version 16.7.6
VisualStudio.16.Release/16.7.6+30611.23
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA460
Microsoft Visual C++ 2019

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Xamarin   16.7.000.456 (d16-7-6@f8d55b6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   14.0.0.0 (7ec3751a1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

---
#### Feedback Bot on 10/26/2020, 07:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Lee Bererton on 10/28/2020, 04:16 PM: 

<p>also tried uninstalling and reinstalling visual studio, creating a new solution, creating a xamarin forms app, tried adding </p><p>using Xamarin.Forms.Maps;</p><p>again it does not recognize it.</p>

#### Lee Bererton on 10/28/2020, 04:43 PM: 

<p>Xamarin.Forms.Maps is a separate NuGet package from Xamarin.Forms.  Also there is a Map variable in Xamarin.Essentials, so if you are using Geolocation and Geocoding from Xamarin.Essentials, you might as well use the Map that already exists in Xamarin.Essentials.</p>

---
#### Lee Bererton solved on 10/28/2020, 04:16 PM, 0 votes: 

<p>also tried uninstalling and reinstalling visual studio, creating a new solution, creating a xamarin forms app, tried adding </p><p>using Xamarin.Forms.Maps;</p><p>again it does not recognize it.</p>

**Comment by jsuarezruiz** [comment]
Are you adding Xamarin.Forms.Maps Nuget Package: https://www.nuget.org/packages/Xamarin.Forms.Maps/?
More information: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
