### ISSUE TITLE
[Bug] CarouselView freezes after editing/adding items on its itemsource

### ISSUE THREAD

**Issue by robinlevelapp** [xamarin/Xamarin.Forms#12922]
### Description
CarouselView freezes after editing/adding items on its itemsource

### Steps to Reproduce

1. Download the attached file and run
2. click next
2. click add button (it will add item on the current itemsource)
3. then click next or back

[CarouselView.zip](https://github.com/xamarin/Xamarin.Forms/files/5572216/CarouselView.zip)

### Expected Behavior
we should supposed see the word Item Added because its the 
next item on the itemsource

### Actual Behavior
It Freezes or not rendering the next item

### Environment

```
```

**Comment by jsuarezruiz** [comment]
Thanks for the sample. I can reproduce the issue. However I realize you are using Xamarin.Forms 4.6. Upgrading to 4.8 there is no problem inserting items. However, I notice something strange when changing the position programmatically.
![issue12922](https://user-images.githubusercontent.com/6755973/99792035-ce033380-2b26-11eb-945f-b4b5583d4a09.gif)

**Comment by robinlevelapp** [comment]
sorry the issue is not in adding the itemsource but when displaying it after adding. i tried it in 4.8 still the same

**Comment by jakehatinen** [comment]
Hi, 
I have related information on this on Android (iOS works as it should).
1. AppShell Page having CarouselView
2. ItemsSource binded to ViewModel ObservableCollection property, SelectedItem and/or SelectedPosition binded to view model properties
3. OnAppearing triggers ViewModel data loading
4. On end of data loading SelectedItem or SelectedPosition are set to any of the items
5. Regardless of the item in step 4, Item index 0 is visual on screen. Indicator show correct item.

XF 4.8.0.1687

**Comment by ahoefling** [comment]
I just ran into this issue on XF 5.0.0.1791-pre5 where the CarouselView would not render the binded `ObservableCollection` correctly. If I start with 1 item and then add a new item with a button press the order jumps around until I scroll through the collection completely first.

For example, if I incrementally add 4 items and then I start scrolling it may scroll in this order: 1,3,4,2,1,2,3,4. If I try binding to the `CurrentItem` it causes similar issues, it just performs the scroll very quickly.

I can confirm this is not an issue in XF 4.8.0.1821 and this appears to be a regression going to 5.0

**Comment by rmarinho** [comment]
This item should be fixed on 5.0.0.1931 latest stable.
