### ISSUE TITLE
[Bug] [iOS] ObserveWillShow event is fired when returned false from ShouldEndEditing event in iOS 14

### ISSUE THREAD

**Issue by Chansardrake** [xamarin/Xamarin.Forms#12939]
### Description
ObserveWillShow event is fired when returned false from ShouldEndEditing event in iOS 14. It's not fired in iOS 13.

**Renderer code:**

    public class CustomEditorRenderer : EditorRenderer
    {
        public CustomEditorRenderer()
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Editor> e)
        {
            base.OnElementChanged(e);

            if (this.Control != null)
            {
                if (this.Element != null && this.Control != null)
                {
                    this.Control.ShouldEndEditing += ShouldDismissKeyBoard;
                }
            }

            UIKeyboard.Notifications.ObserveWillShow((sender, args) =>
            {
                System.Diagnostics.Debug.WriteLine("In ObserveWillShow");
            });

            UIKeyboard.Notifications.ObserveWillHide((sender, args) =>
            {
                System.Diagnostics.Debug.WriteLine("In ObserveWillHide");
            });
        }

        private bool ShouldDismissKeyBoard(UITextView textView)
        {
            return false;
        }
    }

**Xaml:**

    <StackLayout>
        <vm:CustomEditor BackgroundColor="Red"/>
        <Editor BackgroundColor="Blue"/>
    </StackLayout>

### Steps to Reproduce

1. Run the attached sample
2. Tap the first editor
3. Tap the same editor or next editor,  UIKeyboard.Notifications.ObserveWillShow event will be fired

### Expected Behavior
On tapping the same editor or outside should not fire UIKeyboard.Notifications.ObserveWillShow event

### Actual Behavior
On tapping the same editor or outside fire UIKeyboard.Notifications.ObserveWillShow event

### Basic Information

- Platform Target Frameworks: 
  - iOS:  14

### Reproduction Link

**Sample Link :** [Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/CHATMS~1982018056.zip) 

**Output video:**
iOS 13
[iOS 13.5.zip](https://github.com/xamarin/Xamarin.Forms/files/5581238/iOS.13.5.zip)

iOS 14
[iOS 14.zip](https://github.com/xamarin/Xamarin.Forms/files/5581240/iOS.14.zip)

**Comment by hartez** [comment]
Using your sample project, on iOS 14.2, ObserveWillShow does _not_ fire after ShouldIDismissKeyboard returns `false`. 

Have you tried this on 14.2 yet? It may be that Apple fixed a bug between 14.0 and 14.2. Regardless, this is not something that Forms has control over.
