### ISSUE TITLE
[Bug] Providing AppThemeBinding with a color as a DynamicResource throws exception

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12951]
### Description
When providing `AppThemeBinding` with a defined color as a `DynamicResource `:
```
<Color x:Key="MainColor">#00F798</Color>

<Label Text="Test" TextColor="{AppThemeBinding Light={DynamicResource MainColor},  Dark=green}"/>
```
it throws an exception: 
> SetValue: Cannot convert Xamarin.Forms.Internals.DynamicResource to type 'Xamarin.Forms.Color'

### Steps to Reproduce

1. Give AppThemeBinding  a color as a `DynamicResource `.
2. Change theme.

### Expected Behavior
Color change to `MainColor ` when Light theme selected
### Actual Behavior
Color not changing and exception thrown.
### Basic Information

- Version with issue: 5.0.0.1709
- Platform Target Frameworks: Tested on Android only.
- Android Support Library / AndroidX Version: Xamarin.Google.Android.Material 1.0.0.1

### Environment

1. Visual studio 2019 Version 16.8.1

**Comment by StephaneDelcroix** [comment]
AppThemeBinding isn't a BindableObject, AppThemeBinding.Light isn't a BindableProperty, so you can't use DynamicResource. A bit like you can't use a Binding to set the Converter of a Binding 🤷‍♂️

**Comment by Cfun1** [comment]
@StephaneDelcroix is there a possibility in the future for an enhancement to supports a usage with `DynamicResource`?

**Comment by StephaneDelcroix** [comment]
no. but you can set a style using AppThemeBinding, and that Style can use DynamicResources

**Comment by LeoJHarris** [comment]
@StephaneDelcroix that wont throw an exception but the DynamicResources color doesn't get applied.

Something like this doesnt apply the color I defined:

```xaml
Style
        x:Key="OkButtonStyle"
        TargetType="Button">
        <Setter Property="FontSize" Value="{DynamicResource MediumTextSize}" />
        <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonBackgroundColor}, Dark={DynamicResource PromptOkButtonTextColor}}" />
        <Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />
        <Setter Property="CornerRadius" Value="10" />
        <Setter Property="FontFamily" Value="BoldFont" />
    </Style>
```

**Comment by LeoJHarris** [comment]
@StephaneDelcroix any update on this for the above comment I provided? Its currently impossibly to use a DynamicResource with AppThemeBinding whether it throws exception or the color doesn't get applied.

**Comment by AdamMarciniec** [comment]
@StephaneDelcroix This is burning me as well.  My boss wants clients to be able to specify accent colors for both light and dark modes in our app and not being able to use DynamicResouces with AppThemeBinding means having to have two versions of every style that will need to be maintained. :(  Is it going to be like this in MAUI too?

**Comment by albrecht-jun-zhang** [comment]
@LeoJHarris, when referencing color resource in style, you should use StaticResource instead of DynamicResource

So 
`<Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />`
should be
`<Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource PromptOkButtonTextColor}, Dark={StaticResource PromptOkButtonBackgroundColor}}" />`

**Comment by AlexeyStarkov** [comment]
> @StephaneDelcroix that wont throw an exception but the DynamicResources color doesn't get applied.
> 
> Something like this doesnt apply the color I defined:
> 
> ```
> Style
>         x:Key="OkButtonStyle"
>         TargetType="Button">
>         <Setter Property="FontSize" Value="{DynamicResource MediumTextSize}" />
>         <Setter Property="BackgroundColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonBackgroundColor}, Dark={DynamicResource PromptOkButtonTextColor}}" />
>         <Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />
>         <Setter Property="CornerRadius" Value="10" />
>         <Setter Property="FontFamily" Value="BoldFont" />
>     </Style>
> ```

I think the idea of @StephaneDelcroix was that you can define two styles for light and dark themes and use AppThemeBinding to switch style currently applied to a control.

**Comment by albrecht-jun-zhang** [comment]
> @LeoJHarris, when referencing color resource in style, you should use StaticResource instead of DynamicResource
> 
> So `<Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />` should be `<Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource PromptOkButtonTextColor}, Dark={StaticResource PromptOkButtonBackgroundColor}}" />`

Can't use DynamicResource would really limit the ability to update the color properties in runtime. Basically if your app needs to support multiple themes and your colors are updated in runtime, StaticResource won't work.

**Comment by LeoJHarris** [comment]
> > @LeoJHarris, when referencing color resource in style, you should use StaticResource instead of DynamicResource
> > So `<Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />` should be `<Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource PromptOkButtonTextColor}, Dark={StaticResource PromptOkButtonBackgroundColor}}" />`
> 
> Can't use DynamicResource would really limit the ability to update the color properties in runtime. Basically if your app needs to support multiple themes and your colors are updated in runtime, StaticResource won't work.

@albrecht-jun-zhang That's exactly the issue with apps that rely on dynamically loading colors during runtime. These will need to be referenced as `DynamicResource` which is a problem when using `AppThemeBinding`

**Comment by albrecht-jun-zhang** [comment]
> > > @LeoJHarris, when referencing color resource in style, you should use StaticResource instead of DynamicResource
> > > So `<Setter Property="TextColor" Value="{AppThemeBinding Light={DynamicResource PromptOkButtonTextColor}, Dark={DynamicResource PromptOkButtonBackgroundColor}}" />` should be `<Setter Property="TextColor" Value="{AppThemeBinding Light={StaticResource PromptOkButtonTextColor}, Dark={StaticResource PromptOkButtonBackgroundColor}}" />`
> > 
> > 
> > Can't use DynamicResource would really limit the ability to update the color properties in runtime. Basically if your app needs to support multiple themes and your colors are updated in runtime, StaticResource won't work.
> 
> @albrecht-jun-zhang That's exactly the issue with apps that rely on dynamically loading colors during runtime. These will need to be referenced as `DynamicResource` which is a problem when using `AppThemeBinding`

@LeoJHarris yup, my bad. As you just said that AppThemeBinding won't work with DynamicResource is basically not usefully when apps are relying on dynamically loading colors during runtime. Hopefully MAUI support DynamicResource with AppThemeBinding.

**Comment by LeoJHarris** [comment]
@albrecht-jun-zhang That's right, having `AppThemeBinding` is useful in particular with styles as I demonstrated above which would only be possible with `DynamicResource` if colors may change at runtime. If I recall correctly `StaticResource` will throw an exception? Although I know `DynamicResource` is required in my situation.
