### ISSUE TITLE
[Bug] Xamarin.Forms Picker - One Picker selection clears all the options of the other picker in the same page 

### ISSUE THREAD

**Issue by PaulsonM** [xamarin/Xamarin.Forms#12956]
### Hi! I'm working on an app built using Xamarin.Forms. I just upgraded from Xamarin.Forms 3.4.0.1029999 to 5.0.0.1709-pre4. After this upgrade, I'm facing a new issue wherein a page that has multiple pickers, selecting an option in one picker immediately clears all the options of the other picker in the same page.

I also tried downgrading to latest stable version of Xamarin.Forms i.e., 4.8.0.1687

### Steps to Reproduce

1.  Tap a picker, select an option and click done.  
2. Instantly, the other picker doesn't show any selected item.
3. Click this other picker, you will see the options of this other picker are totally empty!

### Expected Behavior
Should not affect/clear the other picker's options or set it to null

### Actual Behavior
The other picker options are fully empty!

### Basic Information

- Version with issue: 5.0.0.1709-pre4 & 4.8.0.1687
- Last known good version: 3.4.0.1029999
- Platform Target Frameworks: 
  - iOS:  

### Environment

1.
```
Microsoft Visual Studio Community 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA418
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20701.1 Commit Hash:b0da3724234b78593207434292d9f891440edea1
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Workaround

Did you find any workaround for this issue? : NO..

**Comment by PaulsonMac** [comment]
Can any of you please confirm that this is an issue with the latest Xamarin.Forms package..?! I didn't make any changes to the code. In 3.4.0.1029999, this issue I've never faced

**Comment by PaulsonMac** [comment]
Hello..

**Comment by PaulsonMac** [comment]
Thank you JESUS for His help. So, the problem is identified.

`OnItemsSourceChanged `is now getting called only when a binded model of list type is changed as follows :
(1) `PickerOptionsList = null;`
(2) `PickerOptionsList = new List<OptionsModel>();`

And in one of the latest version (after 3.4.0.1029999), `OnItemsSourceChanged `is not getting called when elements are added to the the `ItemSource `List type model property(E.g. `OptionsModel`). For e.g.
`PickerOptionsList.Add(...);` 

For now, as a workaround I'm adding those values like the example below in some areas of code:
var students = new List<Student>() { 
                new Student(){ Id = 1, Name="Bill"},
                new Student(){ Id = 2, Name="Steve"},
                new Student(){ Id = 3, Name="Ram"},
                new Student(){ Id = 4, Name="Abdul"}
            };

But I'm working in the code areas/scenarios where the element is added based on a condition..

**Comment by PaulsonMac** [comment]
Thank you JESUS for His help. So, the problem is identified.

`OnItemsSourceChanged `is now getting called only when a binded model of list type property (say `PickerOptionsList `) is changed as follows :
(1) `PickerOptionsList = null;`
(2) `PickerOptionsList = new List<OptionsModel>();`

And due to some changes/commits in one of the latest version (after 3.4.0.1029999), `OnItemsSourceChanged `is not getting called when elements are added to the the `ItemSource `List type model property(E.g. `PickerOptionsList `) using Add() method. For e.g.
`PickerOptionsList.Add(...);`

For now, as a workaround I'm adding those values like the example below in some areas of code:
```
var students = new List() {
new Student(){ Id = 1, Name="Bill"},
new Student(){ Id = 2, Name="Steve"},
new Student(){ Id = 3, Name="Ram"},
new Student(){ Id = 4, Name="Abdul"}
};

```
I'm working in the code areas/scenarios where the element is added based on a condition..

Xamarin Team, can you help me in letting me know which version/commit (change) that has caused this ? From that changes identified in the commit, we can see if any temporary workaround is possible or not to retain my old code -- having Add() method instead of new List()...

**Comment by PaulsonMac** [comment]
There is no problem on initial binding of the List (say `PickerOptionsList`). But it happens when it is set to null, instantiated and then added with elements (more options) later..

**Comment by hartez** [comment]
@PaulsonMac I'm trying to reproduce the issue you are describing, but I haven't been successful so far. I've attached my repro project - can you tell me what details I'm missing? 

[_12956 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5599717/_12956.Repro.zip)

**Comment by PaulsonMac** [comment]
Sure, I'll check and get back to you

**Comment by PaulsonMac** [comment]
@hartez , in my code, the picker (whose options got cleared) was actually loaded/initialized with options inside the `OnItemsSourceChanged `method. My pickers are custom pickers.

`public static readonly BindableProperty ItemsSourceProperty = BindableProperty.Create("ItemsSource", typeof(IEnumerable), typeof(BindablePicker), null, BindingMode.TwoWay, null, new BindableProperty.BindingPropertyChangedDelegate(BindablePicker.OnItemsSourceChanged), null, null, null);`

**Comment by PaulsonMac** [comment]
Also, in my code, it is based on the first picker's selection, the next picker (whose options got cleared) will be loaded.

Before upgrading from Xamarin.Forms v3.4.0.1029999, the OnItemsSourceChanged method was getting called properly. So, the options of the 2nd picker were also loaded properly.

**Comment by PaulsonMac** [comment]
Yes, I'll give it a try

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
