### ISSUE TITLE
[Enhancement] Add isVisible to Span

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#12959]
# Summary
Please add IsVisible to Span objects.

## API Changes
Add Span.IsVisible (bindable property).

## Intended Use Case
I often have some conditional text inside a sentence and it’d be convenient if they could be built as spans.

Having multiple labels is not the same thing as spacing is different between hiding a span and having multiple conditionally hidden labels. Multiple labels also duplicates a lot of things and isn’t really easily readable.

**Comment by aismaniotto** [comment]
+1

**Comment by jfversluis** [comment]
Thanks for this suggestion! It seems to have gotten a good number of upvotes, so I'll add it to my list for .NET MAUI. As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
