### ISSUE TITLE
[Bug] [UWP][ListView] On background Refresh, the scroll position gets changed and auto set it to the top

### ISSUE THREAD

**Issue by PriyankaAG** [xamarin/Xamarin.Forms#12957]
**Description**
On UWP, We have a listview and its itemsource get changed in background code with a fixed time interval

**Steps to Reproduce**
Add Listview 
Code-behind file add code to update itemsource data
Run the app
Scroll the listview data 
wait for code-behind code to execute

**Actual Behavior**
Scroll position gets set to the first element of  listview

**Expected Behavior:**
Scroll position should not get changed on refresh

**Basic Information**
IDE: VS 2019
Platform Target Frameworks: Windows 10
NuGet Packages: Xamarin.Forms 4.7.0.968
Affected Devices: Windows 10

**Comment by hartez** [comment]
@PriyankaAG Could you please provide a repro project demonstrating your issue?

**Comment by PriyankaAG** [comment]
> @PriyankaAG Could you please provide a repro project demonstrating your issue?

Sure

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
