### ISSUE TITLE
[Enhancement] It would be great to have a way to access known named colors and convert a named string to a color.

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#12966]
## Summary
Given a string like "Red" or "yellow" I am unable to verify that it is a valid color and convert it to a Forms.Color.  It would be great to:
- Get a list of existing named colors 
- Check if a string is a named color
- Return the named color for the string

## API Changes
string[] Color.GetAllColors() - return all named colors
bool Color.IsNamedColor(string name) - is this string a named color "Red" or "red" returns true. "Cat" returns false
Color Color.FromName(string name) - return the color given the name "Red" or "red" returns Color.Red. "Cat" returns Color.Default

## Intended Use Case
The user could be presented with a drop down of colors to choose from.
A color value entered as a string could be validated and converted to a color to be used.

**Comment by StephaneDelcroix** [comment]
you could use reflection to do so

**Comment by czuck** [comment]
I was validating the color string using reflection, but this no longer returns the list of named colors (5.0 pre-3)
```
  //try to convert a named color
  var systemColors = ReflectionExtensions.GetProperties(typeof(Color));
```
and neither does this:
```
var systemColors = typeof(Color).GetProperties(BindingFlags.Static | BindingFlags.DeclaredOnly | BindingFlags.Public);
```
it was suggested I use a ColorTypeConverter and ConvertFromInvariantString so I am attempting that.
