### ISSUE TITLE
[Bug] OnIdiom not working with the new RowDefinitions ColumnDefinitions syntax

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#12965]
### Description
xaml is not accepting `OnIdiom` when used with the new syntax of `RowDefinitions ` and `ColumnDefinitions` https://github.com/microsoft/microsoft-ui-xaml/issues/673:

`RowDefinitions="{OnIdiom Tablet="*,*,auto", Phone="*,*,*"}"` highlight:
> expected '>' AND expected '}'

Tried the following workaround but crashing the app on Xamarin and throwing the exception:
> **System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

```
 <Grid.RowDefinitions>
            <RowDefinitionCollection>
                <OnIdiom x:TypeArguments="RowDefinitionCollection">
                    <OnIdiom.Phone>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                    </OnIdiom.Phone>
                    <OnIdiom.Tablet>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="*"/>
                        <RowDefinition Height="auto"/>
                    </OnIdiom.Tablet>
                </OnIdiom>
            </RowDefinitionCollection>
        </Grid.RowDefinitions>
```
### Expected Behavior
To be accepted as a valid syntax.
### Actual Behavior
Invalid syntax.
### Basic Information

- Version with issue: 5.0.0.1790-pre4
 
### Environment
Visual studio 2019 16.8.1

**Comment by hartez** [comment]
Your XAML syntax is invalid because of your nested double quotes, it should be

`RowDefinitions="{OnIdiom Tablet='*,*,auto', Phone='*,*,*'}"`

That said, it's not working; at runtime, it does give an error:

`SetValue: Can not convert *,*,* to type 'Xamarin.Forms.RowDefinitionCollection`

[_12965 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5593706/_12965.Repro.zip)

**Comment by Cfun1** [comment]
@hartez I don't know what has changed but tested your statement (`RowDefinitions="{OnIdiom Tablet='*,*,auto', Phone='*,*,*'}"`) is working with pre4 and pre5 and not giving any runtime error.

**Comment by Balu2** [comment]
This xaml, <Grid ColumnDefinitions="{OnIdiom Phone='*,3*,*', Tablet='*,*,*'}">, is accepted on iOS and Android. But on UWP I get an exception: System.ArgumentException: 'Value is an invalid value for ColumnDefinitions Parameter name: value'
Im am using the latest version of Xamarin.Forms: version 5.0.0.2012

**Comment by Balu2** [comment]
I see that the xaml was not copied correctly:
`<Grid ColumnDefinitions="{OnIdiom Phone='*,3*,*', Tablet='*,*,*'}">`
