### ISSUE TITLE
[Bug] DisplayAlert on UWP does not behave modally. AccessKeys can be activated on page behind

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#12960]
### Description

On UWP, using XF 4.8, with an alert on screen (as a result of awaiting a call to DisplayAlert), pressing Alt results in AccessKeys for the page behind the alert being shown. Pressing Alt + the AccessKey of something on the page behind the alert results in that AccessKey being invoked, allowing functionality to be activated whilst a supposedly modal alert is displayed in front.

When an alert is on screen (as a result of awaiting a call to DisplayAlert), the page behind should be inactive.

### Steps to Reproduce

1. Create a page that uses AccessKeys on Views
e.g.
_entry.On<Windows>().SetAccessKey("j");

2. Elsewhere on that page, have a Button's Command await DisplayAlert
e.g.
                    Command = new Command(async () =>
                    {
                        await DisplayAlert("Alert", "Tapped", "OK");
                    }),

3. Invoke the operation that results in that Command being invoked, so that the alert is displayed

4. Press Alt

### Expected Behavior

Pressing Alt in this situation should not show the AccessKeys of the page behind the alert

### Actual Behavior

The AccessKeys are shown on the page behind the alert

### Basic Information

- Version with issue: 4.8

**Comment by hartez** [comment]
That's the default behavior, unless I'm misunderstanding the issue. Plain-vanilla UWP also does this - check out the attached project:

[_12960_2 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5599753/_12960_2.Repro.zip)

**Comment by hartez** [comment]
If I'm wrong about that or just totally misunderstanding, ping me on this issue and I'll open it back up.

**Comment by johnshardman** [comment]
The problem is that developers would not expect that, and Microsoft/Xamarin documentation clearly says that DisplayAlert shows a modal popup with interaction with the rest of the app continuing once it is dismissed.

A few examples:
"All Xamarin.Forms-supported platforms have a modal pop-up to alert the user or ask simple questions of them"
"The alert displays modally and once dismissed the user continues interacting with the application."
"Xamarin.Forms has a modal pop-up, known as an alert, to alert the user, or to ask simple questions of them"
"The OnDisplayAlertButtonClicked method calls the DisplayAlert method, to display a modal alert with a single cancel button. Once the alert is dismissed the user can continue interacting with the application."

Refs.:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups
https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/pop-ups/?tabs=vswin&tutorial-step=1

**Comment by davidbritch** [comment]
Hi @johnshardman 

On UWP, `DisplayAlert` uses a `ContentDialog` to show a dialog. The UWP docs (https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs and https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-19041) state that `ContentDialog` displays a modal dialog. However, it's been reported (https://stackoverflow.com/questions/63370236/use-of-keyboard-accelerator-and-keyboard-access-keys-in-windows-10-uwp-with-cont) that a `ContentDialog` can't prevent an access key being invoked.

Therefore, I think the best we can do is to update the Xamarin.Forms access key doc (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/visualelement-access-keys) to say the above.

**Comment by johnshardman** [comment]
Hi @davidbritch 

As well as updating the AccessKey documentation, I'd say that the DisplayAlert documentation also needs updating to make clear that it's not modal on all platforms. Being able to invoke functions on the page behind a dialog that is expected to be modal can cause all sorts of issues that need to be protected against.

If somebody can think of a way of implementing DisplayAlert on UWP without using ContentDialog, that would be preferable. Or, if ContentDialog is used, to add protection against access keys being used. It's a while since I looked at how UWP does AccessKeys, so I cannot remember the detail, but I wonder if something can be done in the handler for AccessKeyDisplayRequested or (as a last resort) AccessKeyInvoked?

**Comment by davidbritch** [comment]
Hi @johnshardman 

Doc updates will get published today.

A temporary solution is to create a global variable (in your library App class) that you set whenever you call `DisplayAlert`, and unset once the dialog has been dismissed. Then in your MainPage class in your UWP project, register an event handler for the `Dispatcher.AcceleratorKeyActivated` event. In the event handler, set `args.Handled` to `true` if the global variable is `true` e.g.

In (UWP) MainPage constructor:

```csharp
Dispatcher.AcceleratorKeyActivated += OnAcceleratorKeyActivated;
```

Then:

```
void OnAcceleratorKeyActivated(CoreDispatcher sender, AcceleratorKeyEventArgs args)
{
  if (App.DialogDisplayed)
  {
    args.Handled = true;
  }
}
```

Admittedly this is hacky, but it stops accelerator keys being displayed or invoked when a dialog is displayed. 

I leave to the engineers whether it's desirable for Xamarin.Forms to do this for you (although they might not be monitoring the issue now it's closed).

Personally I think the UWP team should consider fixing `ContentDialog`. You can log a bug against it on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) and it'll find its way to the UWP team. At the very least you'll then know whether it's something they intend to fix or not.

**Comment by johnshardman** [comment]
Thanks @davidbritch 

I have no issue with that workaround (it's pretty much what I was thinking of putting in my own code), but engineering really ought to sort this out in XF itself, whether using the workaround, a fix for ContentDialog, or replacing use of ContentDialog.

Thanks again David

cc @hartez

**Comment by johnshardman** [comment]
@samhouts @hartez - Can you re-open this please, with a view to embedding the workaround posted above in XF/MAUI?

**Comment by johnshardman** [comment]
Hi @davidbritch 

The updated text says "By default, UWP access keys can be activated when a prompt is displayed. For more information, see VisualElement Access Keys on Windows."

Could this be modified again to make clear that it's "access keys on the page behind" or "access keys, including on the page behind," rather than just "access keys" ?

Thanks

**Comment by davidbritch** [comment]
@johnshardman Done. The CI should make it live within an hour.

**Comment by johnshardman** [comment]
Thanks @davidbritch - sterling work!
