### ISSUE TITLE
[Enhancement] Shell BackButtonBehavior command binding in UWP

### ISSUE THREAD

**Issue by HiMyNameIsGarch** [xamarin/Xamarin.Forms#12975]
## Summary
To change behavior of the back button on shell in UWP.

## API Changes
To bind command on backbuttonbehavior like you can on Android or IOS.

## Intended Use Case
To verify something on that page before the user exists it.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
