### ISSUE TITLE
[Bug] Shell.NavBarIsVisible="False" has no effect on UWP

### ISSUE THREAD

**Issue by nor0x** [xamarin/Xamarin.Forms#12972]
### Description
I'm using Shell on UWP and want to hide the NavBar on specific pages with `Shell.NavBarIsVisible="False"`. It works fine on Android and iOS but simply has no effect on UWP

### Steps to Reproduce

1. create XF + UWP app with shell
2. set `Shell.NavBarIsVisible="False"` on page
3. NavBar still visible

### Basic Information

- Version with issue: 5.0.0.1709-pre4
- Platform Target Frameworks: 
  - UWP:  19041

### Screenshots

![image](https://user-images.githubusercontent.com/3210391/100214886-ab9b5c80-2f10-11eb-8a5f-4417b80eb36d.png)

### Reproduction Link
[https://github.com/nor0x/XFStarter](https://github.com/nor0x/XFStarter)

**Comment by themronion** [comment]
Can confirm this one. Is there a workaround using custom renderers for now?

**Comment by drossoft** [comment]
Any news on this? is there a workaround?

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/1630

**Comment by FabriBertani** [comment]
> [dotnet/maui#1630](https://github.com/dotnet/maui/issues/1630)

But, is this fix available for xamarin forms? Or will it be soon?

Still having this issue on UWP with XF v5.0.0.2196

**Comment by FabriBertani** [comment]
Well, I've found a workaround for this issue too:

On the xaml page set the `NavBarIsVisible` to true

`Shell.NavBarIsVisible="{OnPlatform Android='False', iOS='False', UWP='True'}"`

And then in the code behind

```
protected override void OnAppearing()
{
    base.OnAppearing();

    if (DeviceInfo.Platform == DevicePlatform.UWP)
    {
        MainThread.InvokeOnMainThreadAsync(async () =>
        {
            Shell.SetNavBarIsVisible(this, true);

            await Task.Delay(100);

            Shell.SetNavBarIsVisible(this, false);
        });
    }
}
```

But I'm still not able to hide the back button.

**Comment by KirylMiatsko** [comment]
> Well, I've found a workaround for this issue too:
> 
> On the xaml page set the `NavBarIsVisible` to true
> 
> `Shell.NavBarIsVisible="{OnPlatform Android='False', iOS='False', UWP='True'}"`
> 
> And then in the code behind
> 
> ```
> protected override void OnAppearing()
> {
>     base.OnAppearing();
> 
>     if (DeviceInfo.Platform == DevicePlatform.UWP)
>     {
>         MainThread.InvokeOnMainThreadAsync(async () =>
>         {
>             Shell.SetNavBarIsVisible(this, true);
> 
>             await Task.Delay(100);
> 
>             Shell.SetNavBarIsVisible(this, false);
>         });
>     }
> }
> ```
> 
> But I'm still not able to hide the back button.

I'm facing the same issue. Did you ever managed to hide the back button?
