### ISSUE TITLE
[Bug] Entry drop action does not work in MacOs BigSur

### ISSUE THREAD

**Issue by obie73** [xamarin/Xamarin.Forms#12976]
Dragging files to my application has stopped working in the new version of the operating system.

Until now I could drag a file or folder to an entry control to copy the file/directory path of it.

I have implemented DropGestureRecognizer in the entry control, but event is not fired.

```
<Entry.GestureRecognizers>
         <DropGestureRecognizer AllowDrop="True" Drop="DropGestureRecognizer_Drop" ></DropGestureRecognizer>
</Entry.GestureRecognizers>
```

any ideas?

I have tried the latest version 4.8 and the actual pre version of 5, both work in Catalina but not work in bigsur.

**Comment by PureWeen** [comment]
@obie73 Drag and Drop hasn't been implemented for the MacOS target yet

**Comment by PureWeen** [comment]
NM @obie73  I misread your issue...

I'll take a look

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
