### ISSUE TITLE
[Bug] Shell.Current.GoToAsync from SearchHandler in Shell App.

### ISSUE THREAD

**Issue by Nelo-cool** [xamarin/Xamarin.Forms#12970]
### Description
Hi! 
Working with Shell application and SearchHandler in header. If i called GoToAsync from protected override async void OnItemSelected(object item) i see move to next page (page with search result item). But if i called GoToAsync from protected override async void OnQueryConfirmed() nothing happens, not move between pages :(

Maybe this is a feature? And i can only call GoToAsync in OnItemSelected? But why property "ShowsResults", if i can set its value to False and OnItemSelected not called from UI?

### Steps to Reproduce

1. Create inherited class from SearchHandler, ex: CustomSearchHandler : SearchHandler
2. Override methods: protected override async void OnQueryConfirmed()
3. Write call into OnQueryConfirmed() await Shell.Current.GoToAsync() with you route.
4. Nothing happens, not move between pages

### Expected Behavior
Move to my route (with parameter - Query), where is my page with Search result in List and other features:)

### Actual Behavior
Nothing happens, not move between pages

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: 
- Platform Target Frameworks:
  - iOS:  14.2
  - Android: 7.1
- Affected Devices: Droid phone with Android 7.1, IPhone 7, IPhone SE

### Environment
Microsoft Visual Studio Enterprise 2019
Version 16.8.2

**Comment by PureWeen** [comment]
@Nelo-cool can you attach a repro please?

**Comment by Nelo-cool** [comment]
Okay, on morning tomorrow, little project with this issue in zip.

**Comment by Nelo-cool** [comment]
I don't reproduced! I will try to reproduce it in the initial project and I well write here :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
