### ISSUE TITLE
[Bug] HotReload doesn't work on UWP

### ISSUE THREAD

**Issue by nor0x** [xamarin/Xamarin.Forms#12973]
### Description
HotReload doesn't work on in a File->New Xamarin.Forms UWP project. I have tried it with HotReload and HotReload 2.0 (Full Page and Changes only). iOS and Android projects work just fine. 

I have tried it on both Visual Studio 2019 (16.8.2) and Visual Studio 2019 Preview (16.9.0 Preview 1.0) 

### Steps to Reproduce

1. File New -> Xamarin.Forms + UWP
2. Debug Application
3. Make XAML changes
4. Nothing happens

### Expected Behavior
app should be hot reloaded with the changes

### Actual Behavior
no changes get applied

### Basic Information

- Version with issue: 4.8.0.1451
- Platform Target Frameworks: 
  - UWP:  19041

### Environment
Tested with
- Visual Studio 2019 (16.8.2)
- Visual Studio 2019 Preview (16.9.0 Preview 1.0)

**Comment by hartez** [comment]
@nor0x Do you have incremental builds enabled for your UWP project?

**Comment by hartez** [comment]
@nor0x Would it be possible for you to create a ticket using Visual Studio's Feedback mechanism? That way we can get the logs and see what's going on with VS.

**Comment by nor0x** [comment]
alright, i have submitted a ticket

**Comment by BretJohnson** [comment]
@nor0x  Thanks. Also feel free to share the link to the ticket here, in the github issue, which helps us link them. You should get an email after you created the ticket with the link.

**Comment by DevEddy** [comment]
Same issue on my side. 
@nor0x could you fix the issue?

Thank,
Eddy

**Comment by nor0x** [comment]
@DevEddy not really, i noticed that HotReload outages are somewhat random for me on UWP - for me it works if i try it with a blank project and afterwards debug my actual application.

Really annoying issue though
