### ISSUE TITLE
NRE in PageRenderer

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#12989]
https://github.com/xamarin/Xamarin.Forms/blob/40b3b428e457a47b9e8e59e966433925ef9364a5/Xamarin.Forms.Platform.iOS/Renderers/PageRenderer.cs#L480

```
VisualElementRenderer`1[TElement].get_CanBecomeFirstResponder ()
PageRenderer.OnShouldReceiveTouch (UIKit.UIGestureRecognizer recognizer, UIKit.UITouch touch) D:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\PageRenderer.cs:480
UIGestureRecognizer+_UIGestureRecognizerDelegate.ShouldReceiveTouch (UIKit.UIGestureRecognizer recognizer, UIKit.UITouch touch) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.7.0.166/src/Xamarin.iOS/UIKit/UIGestureRecognizer.g.cs:1002
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.7.0.166/src/Xamarin.iOS/UIKit/UIApplication.cs:86
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Library/Frameworks/Xamarin.iOS.framework/Versions/14.7.0.166/src/Xamarin.iOS/UIKit/UIApplication.cs:65
```

Version with issue 5.0.0-pre4

I do not have exact steps to reproduce, but according to code `v` should be checked for null.

**Comment by BioTurboNick** [comment]
@VladislavAntonyuk out of curiosity do you know of a workaround?

**Comment by jsuarezruiz** [comment]
@VladislavAntonyuk Do you know a way to reproduce it?

**Comment by VladislavAntonyuk** [comment]
@jsuarezruiz I don't have exact steps, but looks like it is reproduced with the RelativeLayout.

**Comment by PureWeen** [comment]
@VladislavAntonyuk are you only seeing this issue on 5.0.0-PRE4?  are you not seeing it on any earlier versions?

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk are you only seeing this issue on 5.0.0-PRE4? are you not seeing it on any earlier versions?

I see it on 5.0.0-pre4. I didn't check on earlier versions

**Comment by VladislavAntonyuk** [comment]
I can try to create a small repro. But not sure, because it happens randomly.
