### ISSUE TITLE
[Bug]  HttpClient with HttpClientHandler   //  Timeout is not working

### ISSUE THREAD

**Issue by gtame** [xamarin/Xamarin.Forms#12986]
### Description
if I use HttpClientHandler  and  try connect a unavailable server. The exception  don't throw.

### Steps to Reproduce

Execute this code:
 

`

                HttpClient client2 = new HttpClient();
                client2.Timeout = TimeSpan.FromSeconds(3);
                var requestDate = System.DateTime.Now;
                try
                {
                    HttpResponseMessage response2 = await client2.GetAsync("http://8.8.8.8/Open");

                }
                catch (System.Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"Without HttpClientHandler throw exeception in { (System.DateTime.Now-requestDate).TotalSeconds } seconds");
                }
                HttpClient client3 = new HttpClient(new HttpClientHandler(), false);
                client3.Timeout = TimeSpan.FromSeconds(3);

                requestDate = System.DateTime.Now;
                try
                {
                     
                       HttpResponseMessage response2 = await client3.GetAsync("http://8.8.8.8/Open");

                }
                catch (System.Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine($"With HttpClientHandler throw exeception in { (System.DateTime.Now - requestDate).TotalSeconds } seconds");
                }
`

### Expected Behavior

Exception throws with the timeout expected.

### Basic Information

- Platform Target Frameworks:  Android , IOS hasn't been tested.
  - Android: Android 8.1 - APi27

### Environment
`Microsoft Visual Studio Enterprise 2019
Versión 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Versión 4.8.03761

Versión instalada: Enterprise

Administrador de paquetes NuGet   5.8.0
Administrador de paquetes NuGet de Visual Studio. Para obtener más información acerca de NuGet, visite https://docs.nuget.org/

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
Para obtener más información, visite https://www.asp.net/

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Extensión de depuración de instantáneas   1.0
Información detallada de la extensión de Visual Studio de depuración de instantáneas

Extensión IntelliCode   1.0
Información detallada de la extensión Visual Studio IntelliCode

Herramientas comunes de Windows Azure   1.10
Ofrece servicios comunes para su uso con los servicios móviles de Microsoft Azure y Microsoft Azure Tools.

Herramientas de Azure App Service v3.0.0   16.8.553.28003
Herramientas de Azure App Service v3.0.0

Herramientas de C#   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Los componentes de C# utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de entrega continua de Microsoft para Visual Studio   0.4
Configuración simplificada de las canalizaciones de Azure DevOps desde el IDE de Visual Studio.

Herramientas de TypeScript   16.0.21016.2001
Herramientas de TypeScript para Microsoft Visual Studio

Herramientas de Visual Basic   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Los componentes de Visual Basic utilizados en el IDE. En función del tipo de proyecto y la configuración, se podría utilizar una versión diferente del compilador.

Herramientas de Visual F#   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Herramientas de Microsoft Visual F#

Microsoft Azure Tools   2.9
Microsoft Azure Tools para Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools para contenedores   1.1
Desarrolle, ejecute y valide sus aplicaciones de ASP.NET Core en el entorno de destino. Presione F5 para ejecutar la aplicación directamente en un contenedor con opción de depuración, o bien presione CTRL + F5 para editar y actualizar la aplicación sin necesidad de recompilar el contenedor.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Paquete del host de adaptador de depuración de Visual Studio Code   1.0
Capa de interoperabilidad para el hospedaje de adaptadores de depuración de Visual Studio Code en Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

Visual Studio Container Tools Extensions   1.0
Vea, administre y diagnostique contenedores en Visual Studio.

Visual Studio Tools para contenedores   1.0
Visual Studio Tools para contenedores

VisualStudio.DeviceLog   1.0
Información sobre el paquete

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Extensión de Visual Studio para habilitar la implementación de Xamarin.iOS y Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Extensión de Visual Studio para habilitar las herramientas de Xamarin Designer en Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.`

**Comment by DevEddy** [comment]
Same here, the timeout seems not to be respected.
The weird thing is that my request timeouts after 134 seconds on Android and after 75 seconds on iOS.

**UWP is working as expected with the same code.**

@gtame @samhouts  have you found more information in the meantime?

Thanks,
Eddy

**Comment by heebaek** [comment]
i think this is same problem #10214

**Comment by PureWeen** [comment]
Closing as duplicate of #10214

**Comment by redradist** [comment]
I've have the same issue with Xamarin.Forms testing on Android ...
Is there a fix for it ?

**Comment by fvansteenbrugge** [comment]
> I've have the same issue with Xamarin.Forms testing on Android ...
> Is there a fix for it ?

Yes:
// Android 4.1 or higher, Xamarin.Android 6.1 or higher
HttpClient client = new HttpClient(new Xamarin.Android.Net.AndroidClientHandler ());

**Comment by 21r8390** [comment]
> Yes: // Android 4.1 or higher, Xamarin.Android 6.1 or higher HttpClient client = new HttpClient(new Xamarin.Android.Net.AndroidClientHandler ()); @fvansteenbrugge 

But what if you have a Xamarin.Form project that uses the same codebase for Android and iOS?

**Comment by fvansteenbrugge** [comment]
> > Yes: // Android 4.1 or higher, Xamarin.Android 6.1 or higher HttpClient client = new HttpClient(new Xamarin.Android.Net.AndroidClientHandler ()); @fvansteenbrugge
> 
> But what if you have a Xamarin.Form project that uses the same codebase for Android and iOS?

You are right. I did not have time for my iOS code yet. My code currently is:

(pinning the certificate was something I also desperately needed in my Xamarin Forms project, see https://thomasbandt.com/certificate-and-public-key-pinning-with-xamarin and my code below for a slightly improved version)

        private readonly Lazy<HttpClient> _apiClient;

        public MyRestService()
        {
            var httpClientHandler = (Device.RuntimePlatform == Device.Android)
                ? // TLS 1.2+ handler for Android, we pin our own certificate included in the App in the Assets folder
                new PinAndroidClientHandler()
                : // TODO iOS???
                new HttpClientHandler();

            _apiClient = new Lazy<HttpClient>(() => new HttpClient(httpClientHandler));
        }

        public HttpClient GetApiHttpClient()
        {
            return _apiClient.Value;
        }
		
		using System.IO;
		using Java.Security;
		using Java.Security.Cert;
		using Javax.Net.Ssl;
		using Xamarin.Android.Net;

		namespace MyNameSpace
		{
			public class PinAndroidClientHandler : AndroidClientHandler
			{
				private TrustManagerFactory _trustManagerFactory;
				private KeyManagerFactory _keyManagerFactory;
				private KeyStore _keyStore;
				private static readonly object CollisionLock = new object();


				protected override TrustManagerFactory ConfigureTrustManagerFactory(KeyStore keyStore)
				{
					if (_trustManagerFactory != null)
					{
						return _trustManagerFactory;
					}

					_trustManagerFactory = TrustManagerFactory
						.GetInstance(TrustManagerFactory.DefaultAlgorithm);

					_trustManagerFactory.Init(keyStore);

					return _trustManagerFactory;
				}

				protected override KeyManagerFactory ConfigureKeyManagerFactory(KeyStore keyStore)
				{
					if (_keyManagerFactory != null)
					{
						return _keyManagerFactory;
					}

					_keyManagerFactory = KeyManagerFactory
						.GetInstance(KeyManagerFactory.DefaultAlgorithm);

					_keyManagerFactory.Init(keyStore, null);

					return _keyManagerFactory;
				}

				protected override KeyStore ConfigureKeyStore(KeyStore keyStore)
				{
					// Use a Lock to prevent calling ConfigureKeyStore multiple times in parallel
					// when multiple API tasks run simultaneously. We need to finish configuration
					// so that subsequent calls will block until finishing configuration
					lock (CollisionLock)
					{
						if (_keyStore != null)
						{
							return _keyStore;
						}

						_keyStore = KeyStore.GetInstance(KeyStore.DefaultType);
						_keyStore.Load(null, null);

						CertificateFactory cff = CertificateFactory.GetInstance("X.509");
						Certificate cert;

						string certificateFile = "MyCertificateName.cer";

						// Add your Certificate to the Assets folder and address it here by its name
						using (Stream certStream = Android.App.Application.Context.Assets.Open(certificateFile))
						{
							cert = cff.GenerateCertificate(certStream);
						}

						_keyStore.SetCertificateEntry("TrustedCert", cert);

						return _keyStore;
					}
				}
			}
		}
