### ISSUE TITLE
[Enhancement] 2 New Properties That Should be Added to Buttons

### ISSUE THREAD

**Issue by techprotom** [xamarin/Xamarin.Forms#12993]
### Other platforms for creating applications such as Kotlin provide a much richer set of controls when compared to Xamarin.Forms.
But of course Xamarin.Forms has one key feature which makes it stand out from the rest: the ability to create multiplatform applications in record time. Xamarin.Forms developers have done an amazing job on providing more options on the UI-side of things - but I do think that more time and effort needs to be invested in using XAML/MVU for creating the UI - instead of having to create custom renderers all of the time.

Crucial properties on components which will be used tens of thousands of times (such as buttons) are missing key properties that if added could make Xamarin.Forms that much better to use:

**Proposal 1 - the ability to set uppercase and lowercase on buttons**

Right now - I am creating a custom renderer just to make it so button text is displayed as lower-case.

Xamarin.Forms should consider adding a property titled 'IsUpperCase' on each button. The user will have the option to set this to either true or false. Realistically - this should not be a massive problem to implement. Sentence case is not my preferred way of creating buttons (not always) - so this can open the eyes up of many UI designers such as me.

This shouldn't be a problem to implement with bindable properties.

**Propsal 2 - the ability to add shadows to buttons/other components**

Shadows can add depth to the user interface.

The implementation could be similar to that of a UWP/WPF button.

I am just adding 2 properties for now - but if anyone has anymore ideas please tell me below.

What do you guys think about this?

_**THINK BIG, XAMARIN.FORMS!**_

_Email: todoescode@gmail.com_

**Comment by VladislavAntonyuk** [comment]
1. you can achieve by using converter: Text={Binding MyText, Converter={StaticResource UpperCaseTextConverter}}
2. put your button in Frame, which already has HasShadow property

**Comment by transis2** [comment]
@VladislavAntonyuk Number 2 is horrible when you push the button

**Comment by MitchBomcanhao** [comment]
>     1. you can achieve by using converter: Text={Binding MyText, Converter={StaticResource UpperCaseTextConverter}}
There's no need to use a special converter - there's a property called TextTransform where you can set text properties to Uppercase or Lowercase.

Regardless, changing the text will not matter if you're then using additional features like visual=Material, where the buttons will be shown in uppercase regardless of what text you pass to them.

**Comment by StephaneDelcroix** [comment]
> but I do think that more time and effort needs to be invested in using XAML/MVU for creating the UI - instead of having to create custom renderers all of the time.

we agree on that, and that's the direction we're taking. Thanks for the suggestions, I hope you got your answer on your first question

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
