### ISSUE TITLE
[Enhancement]🚀🚀🚀 Floating Action Button🚀🚀🚀

### ISSUE THREAD

**Issue by techprotom** [xamarin/Xamarin.Forms#12997]
### **Floating action button**

The floating action button is one of the most crucial components used in Google's material design - especially for layouts in which it is needed to add one or more items to a list or compose a new email. In addition to this - it's striking design - which can come in two forms (mini or normal size) make for a better user experience than using standard buttons.

Imagine this GitHub Repo as a puzzle - this puzzle is missing crucial parts. One of these parts is the floating action - which I know and can guarantee will be a perfect feature/addition to your library. 

Implementing a floating action button in Xamarin.Forms right now is a clunky job - and a third-party library which makes it easier to implement a floating action button plus one that utilises material design would make not only my life - but the life of many others - just that much better.

Please consider adding this to your library - it will certainly attract more users. 

Email me at todoescode@gmail.com if you need help or want to ask any questions.

Images and links:

Floating action button: [https://material.io/components/buttons-floating-action-button](url)

_Regular_
![image](https://user-images.githubusercontent.com/72473828/100551073-719cd280-32e3-11eb-832a-874604e4486a.png)

_Mini_
![image](https://user-images.githubusercontent.com/72473828/100551088-811c1b80-32e3-11eb-8777-c0765fe0efb4.png)

_On Hover_
![image](https://user-images.githubusercontent.com/72473828/100551100-9133fb00-32e3-11eb-863b-6646c976b325.png)

_On Clicked_
![image](https://user-images.githubusercontent.com/72473828/100551108-9ee98080-32e3-11eb-974d-27541f6fad31.png)

_Extended_
![image](https://user-images.githubusercontent.com/72473828/100551119-ac066f80-32e3-11eb-956f-a2c8eb29e4d4.png)

_Extended (no icon)_
![image](https://user-images.githubusercontent.com/72473828/100551130-b9bbf500-32e3-11eb-8ac3-bc761fdf9584.png)

**Use cases (there are many)**

![image](https://user-images.githubusercontent.com/72473828/100551142-cb050180-32e3-11eb-9d4d-b85c858a08f5.png)

![image](https://user-images.githubusercontent.com/72473828/100551157-dbb57780-32e3-11eb-968a-4fab530412bf.png)

![image](https://user-images.githubusercontent.com/72473828/100551166-e40db280-32e3-11eb-9cd4-92f3621193f6.png)

![image](https://user-images.githubusercontent.com/72473828/100551227-2636f400-32e4-11eb-874c-33e7d77813c7.png)

![image](https://user-images.githubusercontent.com/72473828/100551248-30f18900-32e4-11eb-8363-80de26a3ae48.png)

![image](https://user-images.githubusercontent.com/72473828/100551255-364ed380-32e4-11eb-9f61-236b613b5c67.png)

**Comment by jsuarezruiz** [comment]
We got a proposal https://github.com/xamarin/Xamarin.Forms/pull/3295 but it is not available.
I think it would be a proposal that now could fits very well in the Xamarin Community Toolkit https://github.com/xamarin/XamarinCommunityToolkit

**Comment by LeoJHarris** [comment]
@jsuarezruiz has this been proposed in https://github.com/xamarin/XamarinCommunityToolkit yet?

**Comment by jfversluis** [comment]
This won't happen for Xamarin.Forms
