### ISSUE TITLE
[Bug] iOS - Clear Cookies not working on WEBVIEW when Sign out

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/Xamarin.Forms#12999]
### Description
After login into App, we encountered a problem when calling clear cookies at SIGN OUT. this problem occurs on Xamarin Form 4.8.0.1687.  when we are using Xamarin Form 4.8.0.1451 the clear cookies were working fine.

### Steps to Reproduce

1. Install APP
2. Login into APP
3. Dashboard loaded
4. Choose to SIGN OUT from Menu
5. Open Login Page, the Authentication still exist and cookies were not clear

### Expected Behavior
Cookies should be clear

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 10 

- NuGet Packages: Xamarin Form 4.8.0.1687
- Affected Devices: iOS

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.2 (build 41)
Installation UUID: 2cd71d04-ab6c-4e04-bc23-3e7a3325e264
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Apple Developer Tools ===

Xcode 12.2 (17535)
Build 12B45b

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/kok.sang/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/kok.sang/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808020041
Git revision: dba789c00d07d6923cce74016b7e406526d683da
Build date: 2020-11-23 04:40:23-05
Build branch: release-8.8
Xamarin extensions: dba789c00d07d6923cce74016b7e406526d683da

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Android Signature Tool 2.2.0

### Workaround
public void ClearAllCookies()
        {
            NSHttpCookieStorage cookieStorage = NSHttpCookieStorage.SharedStorage;

            foreach (var cookie in cookieStorage.Cookies)
            {
                cookieStorage.DeleteCookie(cookie);
            }
        }

**Comment by PureWeen** [comment]
@sunkerGit do you have a sample app we can test? Or more information about your Login? Is this a custom login page?

**Comment by sunkerGit** [comment]
@PureWeen this is a web login page ASPX (load by WEBVIEW) whereas returned token for authentication. based on the code below when I'm debugging with 4.8.0.1451 ( cookieStorage.Cookies there is a value), but when used 4.8.0.1687 (cookieStorage.Cookies = null):
public void ClearAllCookies()
{
        NSHttpCookieStorage cookieStorage = NSHttpCookieStorage.SharedStorage;

        foreach (var cookie in cookieStorage.Cookies)
        {
            cookieStorage.DeleteCookie(cookie);
        }
}

The steps to reproduce:
1. FRESH install the app on ios
2. login for getting the AUTHENTICATION
3. Success: Dashboard page appear
4. SIGN OUT (debug on ClearCookies() method, we got null at cookieStorage.Cookies when using XF 4.8.0.1687

**Comment by Redth** [comment]
Can you please attach a sample project which reproduces this issue?

**Comment by cgould16** [comment]
Getting same error with exact implementation.  User signing in via webview and still caching credentials, after logout.

**Comment by sunkerGit** [comment]
The current debug I got is NSHttpCookieStorage.SharedStorage.Cookies is empty. how do we set this on WebView? this problem still exists on XF 5.0.0.2012 nuget package.

**Comment by cgould16** [comment]
Here is a cool fix:

Make an interface in your main solution: 
`public interface IClearCookies
    {
         Task Clear();
    }`

Here is the iOS Solution I have made

`public void Clear()
    {
        NSHttpCookieStorage.SharedStorage.RemoveCookiesSinceDate(NSDate.DistantPast);

        WKWebsiteDataStore.DefaultDataStore.FetchDataRecordsOfTypes(WKWebsiteDataStore.AllWebsiteDataTypes, (NSArray records) => {

        for (nuint i = 0; i < records.Count; i++)
        {
                var record = records.GetItem<WKWebsiteDataRecord>(i);
                WKWebsiteDataRecord[] recordArray = new WKWebsiteDataRecord[record.DataTypes.Count];
                WKWebsiteDataStore.DefaultDataStore.RemoveDataOfTypes(record.DataTypes, NSDate.DistantPast, ()=> { });
            }

        });

    }`

Here is the android solution:
`public async Task Clear()
        {
            var cookieManager = CookieManager.Instance;
            cookieManager.RemoveAllCookie();
        }`

Above both android and iOS solution add before namespace declaration:
`[assembly: Dependency(typeof(ClearCookies))]`

I then register this in dependency service like this in main activity and app delegate:
`DependencyService.Register<IClearCookies, ClearCookies>();`


call method by doing this:
`await DependencyService.Get<IClearCookies>().Clear();`

worked for me, let me know if it works for you.

**Comment by sunkerGit** [comment]
Hi @cgould16 ,

thank you for your resolution, it's worked! btw I have to refactor your code. we don't have to use Task for the CLEAR method
here are the fix for iOS:
public void Clear()
        {
            NSHttpCookieStorage.SharedStorage.RemoveCookiesSinceDate(NSDate.DistantPast);

            WKWebsiteDataStore.DefaultDataStore.FetchDataRecordsOfTypes(WKWebsiteDataStore.AllWebsiteDataTypes, (NSArray records) => {

                for (System.nuint i = 0; i < records.Count; i++)
                {
                    var record = records.GetItem<WKWebsiteDataRecord>(i);
                    WKWebsiteDataRecord[] recordArray = new WKWebsiteDataRecord[record.DataTypes.Count];
                    WKWebsiteDataStore.DefaultDataStore.RemoveDataOfTypes(record.DataTypes, NSDate.DistantPast, () => { });
                }

            });

        }

**Comment by sunkerGit** [comment]
All good.
