### ISSUE TITLE
[Bug] Clear Cookies not working on WEBVIEW when SI

### ISSUE THREAD

**Issue by sunkerGit** [xamarin/Xamarin.Forms#12998]
### Description
After login into App, we encountered a problem when call clear cookies
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

**Comment by StephaneDelcroix** [comment]
Duplicate of #12999
