### ISSUE TITLE
Unable to view the list of CI builds. Permission denied

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#13000]
![image](https://user-images.githubusercontent.com/33021114/100592587-fac20280-32ff-11eb-838b-16d458a7ebc7.png)
![image](https://user-images.githubusercontent.com/33021114/100592649-0f05ff80-3300-11eb-9c14-305feb6f0ac4.png)

Also nightly builds are not available( the latest build 5.0.1-1668

**Comment by rmarinho** [comment]
@VladislavAntonyuk  do you see that every time?

What if you try this link https://dev.azure.com/xamarin/public/_build ? 

also nightly isn't pushed from the public ci, is from the private, the last one is 5.0.1.1760

**Comment by VladislavAntonyuk** [comment]
If I open it by the direct link it works. I even can now see the list of builds. but When I switch for example to the Releases and then switch back to the Pipelines it fails again. (the link it opens: https://dev.azure.com/xamarin/_apis/IdentityPicker/Identities/me/mru/common?operationScopes=ims&properties=DisplayName%2CIsMru%2CScopeName%2CSamAccountName%2CActive%2CSubjectDescriptor%2CDepartment%2CJobTitle%2CMail%2CMailNickname%2CPhysicalDeliveryOfficeName%2CSignInAddress%2CSurname%2CGuest%2CTelephoneNumber%2CManager%2CDescription)

**Comment by VladislavAntonyuk** [comment]
As for nuget: The latest builds which I see:
![image](https://user-images.githubusercontent.com/33021114/100855961-786a4780-3493-11eb-8350-4391283853d5.png)

**Comment by rmarinho** [comment]
@VladislavAntonyuk  thanks for catching that , ii saw what was the issue that it stop sigining the main branch nightly.

 i can also repo when changing from releases tab the authentication issue, i will investigate. 

Thanks once again

**Comment by VladislavAntonyuk** [comment]
The authentication issue is most likely related to Azure DevOps defect. I found that it you click on settings button and then on Preview Features, you will also get the error in a few seconds. But this one is not as critical as switching between tabs.

**Comment by rmarinho** [comment]
Ok last nightly was pushed i just confirmed!
