### ISSUE TITLE
Xamarin.Forms - Crashlytics is not logging crashes [Xamarin.Forms 5.0.0.1709-pre4 & Crashlytics 4.6.2] [Bug] 

### ISSUE THREAD

**Issue by PaulsonMac** [xamarin/Xamarin.Forms#13011]
### Description
Hi! I'm using Crashlytics v4.6.2 for my Xamarin.Forms app. Though the crash count is increasing but still no error message/stack trace is logged in the Firebase Console. I tried in release device build as well.

I get the following below logs which makes me think that something else is interfering, but though I tried, I couldn't find what is interfering with Crashlytics (if I've perceived it correctly)

### Expected Behavior
Crashes are not logged with stack trace. I tried throwing NotImplemented exception, Null reference exception and also one crash in picker whose fix is in Xamarin.Forms 5.0.0.1709-pre4

### Actual Behavior
Log crashes with stack trace/error message

### Basic Information

- Version with issue: 5.0.0.1709-pre4
- Last known good version: 3.4.0.1029999
- Platform Target Frameworks: 
  - iOS:  14.1

### Environment

![image](https://user-images.githubusercontent.com/42689728/100740568-f16b8f80-33fe-11eb-8bd5-c3e4f4707b5e.png)

### Build Logs

```
[Crashlytics] The signal SIGABRT has a non-Crashlytics handler (sigabrt_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGBUS has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGFPE has a non-Crashlytics handler (mono_sigfpe_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGILL has a non-Crashlytics handler (<redacted>).  This will interfere with reporting.

[Crashlytics] The signal SIGSEGV has a non-Crashlytics handler (mono_sigsegv_signal_handler).  This will interfere with reporting.

[Crashlytics] The signal SIGSYS has a non-Crashlytics handler (mono_crashing_signal_handler).  This will interfere with reporting.
[Crashlytics] The signal SIGTRAP has a non-Crashlytics handler ((null)).  This will interfere with reporting.
```

### Workaround

No.

**Comment by PaulsonMac** [comment]
Sorry, why there is no response for any opened issues in Xamarin's GoogleApisForiOSComponents repo -  https://github.com/xamarin/GoogleApisForiOSComponents/issues?

**Comment by PaulsonMac** [comment]
It was working fine in Xamarin.Forms v3.4.0.1029999 and Xamarin.Firebase.iOS.Crashlytics v3.14.0 prior to upgrade them.

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-macios/issues/10227
