### ISSUE TITLE
[Questions] How to get the units from a pixel in photoshop?

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#13010]
I know that in Xamarin all is units such as widthRequest.

But If I design a UI in photoshop with 72 dpi

and in the page there is an button that is 88px

Then I should set the Button'heightRequest to 88 ?

I want to ask that 1 pixel =? unit?

**Comment by StephaneDelcroix** [comment]
> I want to ask that 1 pixel =? unit?

it depends on the screen. if you're running, say, on an iPhone with retina display, a single 'unit' could span to 1, 2, or 3 pixels. same goes for android.
