### ISSUE TITLE
[Question] Shell Routing passing properties to more than one page

### ISSUE THREAD

**Issue by patrickhacens** [xamarin/Xamarin.Forms#13021]
## Summary
I would like to know if it is possible to "deep" navigate and insert all routing arguments needed to get into that page and have a natural back navigation behavior

e.g.
```csharp
 await AppShell.Current.GotoAsync("//root/page1?id=1/page2?id=145/page3?id=1555");
```
## Intended Use Case
I have something like a binarytree format of entities and when the app is opened and cache is at like 3 levels down of entities when backbutton is used the parent page does not have an id

**Comment by PureWeen** [comment]
@patrickhacens in theory you can do this but it hasn't really been documented or tested so I wouldn't bet on it 

```C#
 await AppShell.Current.GotoAsync("//root/page1/page2/page3?page1.id=1&page2.id=145&id=1555");
```

I'm going to move this issue over to our Shell project so we can better test the above scenario though.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
