### ISSUE TITLE
[Bug] ListView items elements not stored within LogicalChildren, inaccessible without reflection.

### ISSUE THREAD

**Issue by drasticactions** [xamarin/Xamarin.Forms#13027]
### Description

A ListView is a `TemplatedItemsList<ItemsView<Cell>, Cell>`. This type stores its items (`Cell`) within `_logicalChildren` (and `TemplatedItems`, and not under `LogicalChildren` as the other Elements do. This raw list of cells is also not publically accessible from within this control, needing us to call reflection.

Either having the items available under `LogicalChildren` or at least having a publically accessible list of Cells would make it much easier to get the true `Element` items within this view. 

### Steps to Reproduce

1. Create a ListView
2. Add Cells
3. Call `ListView.LogicalChildren` or `ListView.AllChildren`

### Basic Information

- Version with issue: 5.0.0.1709-pre4 and 4.8.0.1687

### Expected Behavior

ItemCells will be listed under it.

### Actual Behavior

Children are always empty.

### Workaround

Calling Reflection

```
((TemplatedItemsList<ItemsView<Cell>, Cell>)ListView.GetType ().GetProperty ("TemplatedItems", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.GetProperty).GetValue (lv))

or

((System.Collections.Generic.List<Element>)lv.GetType ().GetField ("_logicalChildren", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.GetProperty).GetValue (lv))

```

> VS bug [#1254590](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1254590)

**Comment by StephaneDelcroix** [comment]
Keep calling reflection for ListView (as discussed)
