### ISSUE TITLE
[Bug] iOS Transporter showing default Xamarin icon

### ISSUE THREAD

**Issue by ludas96** [xamarin/Xamarin.Forms#13024]
### Description
After changing the app icons for both Android and iOS, everything looks fine on all the devices deployed to. However, iOS seems to have issues with Transporter as the icon is still shown as the default Xamarin icon while delivering the app. I have removed every reference to Xamarin default icons in my Assets catalog but it's still there.

### Expected Behavior
IPA App should show the same icon in transporter as when deployed.

### Actual Behavior
IPA app shows the default xamarin icon.

Is there something I'm missing? I've set every icon and size for AppIcon assets catalog.

**Comment by PureWeen** [comment]
@ludas96 can you attach a repro please?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Tsukasa42** [comment]
@ludas96 ever solve this issue? Having the same problem here.
