### ISSUE TITLE
[Bug][iOS] Drag-and-drop text bubble gets stuck

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#13026]
### Description

When selecting some text from an Entry or Editor on iOS in a Xamarin.Forms app, I am able to make the selected text bubble disassociate from its textbox and get stuck on the screen. Scrolling the page, navigating to a different page, and foregrounding and backgrounding the app do nothing, there is just a text bubble stuck in a static place on the screen, that cannot be interacted with. It is also possible to create multiple of these bubbles. The only way to get rid of them is to swipe-kill the application.

This is occurring with both entries and editors in multiple places in the app, but I have not been able to reproduce it independently.

### Steps to Reproduce

1. Enter some text into an Entry or Editor
2. Select some of the text to open the Select | Select All context menu
3. Long press the selected text until text bubble is created
4. If you hold onto the text bubble you can drag and drop it to copy & paste into another text box (expected behavior)
5. If you release the text bubble without dragging it, it becomes stuck on the page, and the Cut | Copy context menu is opened on the selected text

### Expected Behavior

Releasing the text bubble dismisses it.

### Actual Behavior

Text bubble becomes stuck in place on screen.

### Basic Information

- Version with issue: 4.8.0.1560
- Last known good version: unknown
- Platform Target Frameworks: 
  - iOS:  14.1
- Affected Devices: 

### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA910
Microsoft Visual C++ 2019

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Visual Basic Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f


Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Screenshots

![LYWY1943 (1)](https://user-images.githubusercontent.com/6132629/100922203-39dc8900-34a3-11eb-828d-1a244cba4d74.gif)

**Comment by PureWeen** [comment]
@jcmanke hmm I tried to reproduce this as well but I'm not really having any luck

Is there a way to create a page that mimics the layout of the one in your gif?
If you update to the latest xcode and test on 14.2 simulators do you see the same issue?

Also what type of device are you testing on?

**Comment by jcmanke** [comment]
@PureWeen I have not been able to reproduce it yet, including copy-pasting a page from the real app into a different solution.

Don't have permission to upgrade Xcode on my work computer, but I'm actively working on the upgrade analysis so the whole team will likely be updating soon.

The video comes from an iPhone 11 Max Pro, I have also reproduced it on an iPhone 6s running iOS 13.0, and an iPhone 12 iOS 14.1 simulator.

**Comment by Redth** [comment]
Please check back in after you've updated your developer environment if the issue still exists and attach a project which reproduces it.  Feel free to re-open the issue in that case.  Thanks!

**Comment by filyjunior** [comment]
I have the same behavior in my application. Any suggestion?
