### ISSUE TITLE
[Enhancement] Keyboard Events

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#13031]
## Summary
Manage keyboard events on application.

## API Changes
Add `KeyUp` and `KeyDown` events on new `Keyboard` class. 

The `KeyEventArgs` should contain the `Key` pressed.

Maybe inspired by Keyboard events on:
- [UWP Keyboard events](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events)
- [Android Keyboard actions](https://developer.android.com/training/keyboard-input/commands)
- [iOS UIPress.key](https://developer.apple.com/documentation/uikit/uipress)

## Intended Use Case
- Manage specific keyboard shortcuts/behavior in application
- Manage specific keyboard navigation
- Manage specific hardware keyboard

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
