### ISSUE TITLE
Mscorlib conflicts with system.memory

### ISSUE THREAD

**Issue by kefyru** [xamarin/Xamarin.Forms#13033]
I made library project (target netstandard 2.1), using MessagePack 2.2.60.
I made class BufferWriter : IBufferWriter, and use it like this:
var buffer = new BufferWriter();
var writer = new MessagePackWriter(buffer);

That library is using by client app (Xamarin.Forms, netstandard2.1) and server app (netcoreapp3.1)

In server app all works ok.
But in client app (XF.IOS) i got System.MissingMethodException: Method not found: void MessagePack.MessagePackWriter..ctor(System.Buffers.IBufferWriter`1).

in debugger i found that:
type of IBufferWriter using in constructor of MessagePackWriter:
System.Buffers.IBufferWriter`1[[System.Byte, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51

and type of IBufferWriter that i use to implement in my BufferWriter is:
System.Buffers.IBufferWriter`1[[System.Byte, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

Help please.

**Comment by StephaneDelcroix** [comment]
I'm sorry to hear this, but it's definitely out of our reach. you should contact the library author
