### ISSUE TITLE
[Bug] Grid broken in 4.8.0.1687

### ISSUE THREAD

**Issue by jthun** [xamarin/Xamarin.Forms#13034]
### Description
There seems to be an issue with Grid layout in XF 4.8.0.1687.

### Steps to Reproduce

1. Create new blank Xamarin Forms project.
2. Paste the sample MainPage.xaml
3. Run and observe the difference between for example 4.8.0.1560 and .1687. The grid is much smaller in .1687 and this is destroying the entire app look-and-feel.

**MainPage.xaml**
<ContentPage
    x:Class="GridTests.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <ContentPage.Resources>
        <Color x:Key="GridBackgroundColor">#AFAFAF</Color>
    </ContentPage.Resources>

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Frame
            Grid.Row="0"
            Padding="24"
            BackgroundColor="#2196F3"
            CornerRadius="0">
            <Label
                FontSize="36"
                HorizontalTextAlignment="Center"
                Text="Grid Test, XF 4.8.0.1687"
                TextColor="White" />
        </Frame>

        <Grid
            Grid.Row="1"
            HorizontalOptions="Center"
            VerticalOptions="Center">

            <Grid.RowDefinitions>
                <RowDefinition Height="*" />
                <RowDefinition Height="3*" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="3*" />
                <ColumnDefinition Width="*" />
            </Grid.ColumnDefinitions>

            <BoxView
                Grid.Row="0"
                Grid.Column="0"
                BackgroundColor="{StaticResource GridBackgroundColor}" />

            <BoxView
                Grid.Row="0"
                Grid.Column="2"
                BackgroundColor="{StaticResource GridBackgroundColor}" />

            <BoxView
                Grid.Row="2"
                Grid.Column="0"
                BackgroundColor="{StaticResource GridBackgroundColor}" />

            <BoxView
                Grid.Row="2"
                Grid.Column="2"
                BackgroundColor="{StaticResource GridBackgroundColor}" />

        </Grid>
    </Grid>

</ContentPage>

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: 4.8.0.1560
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: 9.0 
  - UWP:  Not tested
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

### Screenshots

![Screenshot_20201203-122334 1](https://user-images.githubusercontent.com/9201423/101014365-10d0fc80-3566-11eb-8e41-c0b8e0bf8dbc.jpg)

![Screenshot_20201203-122455 1](https://user-images.githubusercontent.com/9201423/101014405-20504580-3566-11eb-8334-7f27730cf652.jpg)

**Comment by jthun** [comment]
Might be a duplicate of #12900

**Comment by jsuarezruiz** [comment]
This issue seems to be fixed by https://github.com/xamarin/Xamarin.Forms/pull/12475
