### ISSUE TITLE
Android: wrong (cached) density used to compute conversions between pixels and units on multiple displays

### ISSUE THREAD

**Issue by polkduran** [xamarin/Xamarin.Forms#13043]
https://github.com/xamarin/Xamarin.Forms/blob/d99264507dc1623aecb83daf81aadd2effae62ae/Xamarin.Forms.Platform.Android/ContextExtensions.cs#L23-L27

I ran into this problem before taking a look at the code and see the comment.

I have two displays with different sizes, resolution and density - I work on an app for a point of sales, so one screen for the shop owner and other for the client, both displaying different content.

```
Display display; // From the display manager
ContentPage page; // The XF page to display on the secondary screen

var presentation = new Presentation(Application.Context, display);
var nativeView = BuildNativeView(page, presentation.Context);
presentation.SetContentView(nativeView);
presentation.Show();
```
And the `BuildNativeView`:
```
var metricsDisplay = context.Resources.DisplayMetrics;

// This computes the right width and height but when XF displays the view it has wrong boundaries when the main display has a different density (more exactly the first context from which the density was cached on ContextExtensions.
var width = metricsDisplay.WidthPixels / metricsDisplay.Density; //width in units  
var height = metricsDisplay.HeightPixels / metricsDisplay.Density; //height in units 

var renderer = Platform.GetRenderer(view);
if (renderer == null)
{
    renderer = Platform.CreateRendererWithContext(view, context);
    Platform.SetRenderer(view, renderer);
}

var nativeView = renderer.View;
view.Layout(new Rectangle(0, 0, width, height));
renderer.Tracker.UpdateLayout();

return nativeView;
```

When using the `Application.Context.Resources.DisplayMetrics.Density` to convert from pixels to units the view is displayed correctly so I assumed the problem was coming when converting back from units to pixels, which was confirmed by reading the code.

The solution I use now is to use the broken `ContextExtensions` class:
```
var width = context.FromPixels(metricsDisplay.WidthPixels);
var height = context.FromPixels(metricsDisplay.HeightPixels);
```

I would like to fix that with a PR but some question came to my mind:
1. Having a `Dictionary<Context, float>` to cache the density by context, if the context is dismissed (I don't know if this is true) then we risk to hold a reference to it and prevent to be garbage collected.
2. Is there a way to to identify a context without holding a reference to it? (an id or something). 
3. Maybe having a relation between the display id and the density, but what about if the display is disconnected and other one is connected, would we have different ids?

**Comment by PureWeen** [comment]
duplicate 

https://github.com/xamarin/Xamarin.Forms/issues/7239

@polkduran there was a PR here
https://github.com/xamarin/Xamarin.Forms/pull/7983

But it didn't end up getting merged. There are some comments in there about how to fix the implementation so that's probably a good place to start
