### ISSUE TITLE
Missing toolbox icons

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#13061]
We need to add images for some of the more recently added controls. This is the toolbox panel in Visual Studio and Visual Studio for Mac. 

https://github.com/xamarin/Xamarin.Forms/tree/5.0.0/Xamarin.Forms.Core.Design/toolbox

Missing:

* ImageButton
* RadioButton
* CheckBox
* IndicatorView
* CarouselView
* RefreshView
* SwipeView

We need to request icon assets from our design team, add them to the above folders, and then update our xml metadata with the images and code snippets.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
