### ISSUE TITLE
Duplicate / Repeating characters in Entry control with TextTransform property [Xamarin.Forms.Android]

### ISSUE THREAD

**Issue by SubburajPandian** [xamarin/Xamarin.Forms#13062]
### Steps to Reproduce

1. Create Entry control 
2. Set TextTransform="Uppercase"
3. Type some letters - sometimes Duplicate / Repeating characters added. For example, type QWERTY some letters repeating in the entry like QWEERTYY.

### Basic Information

- Version with issue: Xamarin.Forms v4.8.0.1687
- Platform Target Frameworks: 
  - Android: 9.0 emulator and devices 
  
- Nuget Packages: Xamarin.Forms v4.8.0.1687
- Affected Devices: Nexus, HoneyWell CN85

### Screenshots
Here typed only QWERTY but rendered as in screenshot,

![image](https://user-images.githubusercontent.com/25637613/101275367-0df72700-3773-11eb-9b0c-7dd15d1888e9.png)

### Sample code: 

`<Entry TextTransform="Uppercase" />`

### Sample attached: 
[EntryCaps.zip](https://github.com/dotnet/maui/files/5648486/EntryCaps.zip)

**Comment by StephaneDelcroix** [comment]
I can't reproduce this :/

**Comment by SubburajPandian** [comment]
I have tested in **Nexus 5 Oreo 8.1 API 27 Emulator and HoneyWell CN85 Device**.

@StephaneDelcroix Can you confirm in which device you tested the attached the sample?

**Comment by PureWeen** [comment]
@SubburajPandian is this primarily happening for you when typing from a physical keyboard? Or does it also happen on the device?

I'm seeing your issue on a " Nexus 5 Oreo 8.1 API 27 Emulator" when typing from my keyboard to the simulator but not on the simulator itself

**Comment by SubburajPandian** [comment]
@PureWeen Yes, you're right in emulator issue occur when typing from a physical keyboard. What will the cause?

Issue occurring in device also - **HoneyWell CN85**, I didn't checked with other devices.

**Comment by SubburajPandian** [comment]
Any update on this?

**Comment by rachelkang** [comment]
Are you using a bluetooth keyboard? It seems like this might be a keyboard/bluetooth compatibility issue, and if so, one of these resources might be helpful:
https://android.stackexchange.com/questions/41618/how-to-prevent-characters-from-repeating-when-entering-text-with-a-bluetooth-key
https://amigotechnotes.wordpress.com/2019/01/24/android-repeating-keys-with-an-external-bluetooth-keyboard/
https://helpdeskgeek.com/how-to/fix-repeating-keys-with-these-tips/

**Comment by SubburajPandian** [comment]
@rachelkang  No, not using any Bluetooth keyboard. As I mentioned before, issue occurs HoneyWell CN85 Device. Can you check at your end and confirm whether you're facing issue or not.

**Comment by rachelkang** [comment]
Hi, @SubburajPandian - thanks for the update. I unfortunately do not have that device, but tested on all the Android devices I do have and was unable to reproduce the issue. Is it possible that the device is acting out of keyboard device settings specific to that device? (i.e. auto-correct, auto-completion, shortcuts) Could you check your phone's keyboard settings just to make sure?

Also, if you haven't already, could you try updating to the latest version of XF 5 and letting us know if anything changes? Hope this helps :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
