### ISSUE TITLE
📋 Survey: Repo contribution experience, Fall 2020

### ISSUE THREAD

**Issue by Redth** [xamarin/Xamarin.Forms#13073]
Thanks for all your contributions to this project! Along with a number of other Microsoft repos, we have created a survey that we hope allows us to learn what works and what needs attention. It's a little bit less than 30 questions, many of them multiple-choice questions. If maybe takes 10 minutes to complete and it’s anonymous. Your responses will help us make your experience better in this repo, thanks in advance for your time and feedback!

Take the survey [here](https://www.surveymonkey.com/r/92RLF7R?Source=xamarin/xamarin.forms).

**Comment by jpobst** [comment]
Closing issue, as survey is closed.

Thanks to everyone who participated!
