### ISSUE TITLE
[Bug] MarkerClicked not called on Android X

### ISSUE THREAD

**Issue by abelgarciasaiz** [xamarin/Xamarin.Forms#13070]
### Description

Simple map view with a pin with MarkerClicked event defined doesn't get fired on android X but it does in android 9

### Steps to Reproduce

    xmlns:maps="clr-namespace:Xamarin.Forms.Maps;assembly=Xamarin.Forms.Maps"

<maps:Map   x:Name="map"    IsShowingUser="True"  MoveToLastRegionOnLayoutChange="False">

            <x:Arguments>
                <maps:MapSpan>
                    <x:Arguments>
                        <maps:Position>
                            <x:Arguments>
                                <x:Double>40.383</x:Double>
                                <x:Double>-3.717</x:Double>
                            </x:Arguments>
                        </maps:Position>
                        <x:Double>0.01</x:Double>
                        <x:Double>0.01</x:Double>
                    </x:Arguments>
                </maps:MapSpan>
            </x:Arguments>
            <maps:Map.Pins>
                <maps:Pin
                    Address="The city with a boardwalk"
                    InfoWindowClicked="Pin_InfoWindowClicked"
                    Label="Santa Cruz"
                    MarkerClicked="Pin_MarkerClicked"
                    Type="Place">
                    <maps:Pin.Position>
                        <maps:Position>
                            <x:Arguments>
                                <x:Double>40.383</x:Double>
                                <x:Double>-3.717</x:Double>
                            </x:Arguments>
                        </maps:Position>
                    </maps:Pin.Position>
                </maps:Pin>
            </maps:Map.Pins>
        </maps:Map>

### Expected Behavior

Xamarin.Forms and Xamarin.Forms.Maps in the latest version.
Xamarin.AndroidX.* in the latest version

**Comment by PureWeen** [comment]
@abelgarciasaiz can you attach a repro please?

I tested with the sample here

https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps

And I was able to click on the markers without a problem after updating to the AndroidX builds of Xamarin.Forms

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
