### ISSUE TITLE
Cannot set backgroundcolor for a label in CSS

### ISSUE THREAD

**Issue by PaulSinnema** [xamarin/Xamarin.Forms#13080]
### Steps to Reproduce

1. Declare a Label:
	`<Label Text="{Binding Title}" HorizontalOptions="Center" StyleClass="TitleView" />`
2. Add a CSS file and add it to the Resources of the App
3. Define a style in the CSS file:
```
* {
	background-color: black;
	color: white;
}

.TitleView {
	font-size: 20;
	background-color: #2296f3;
}
```
### Expected Behavior
The backgroundcolor of the text is blueish

### Actual Behavior
The background color is black.

**Comment by StephaneDelcroix** [comment]
can you try using lowercase ('titleview') and report ?

**Comment by PaulSinnema** [comment]
@StephaneDelcroix Ok, my bad I found the problem. In the css the following was present:

```
.titleviewback {
	background-color: #2296f3;
}

.titleview {
	font-size: 30;
	background-color: #2296f3;
}
```

A few lines lower:

```
Label {
	color: white;
	background-color: black;
}
```

The latter overrides the color of the style class.

**Comment by rachelkang** [comment]
@PaulSinnema awesome! Glad to hear you figured it out :)

CSS in XF works a bit differently than the expected behavior you describe - as per our docs:

> Styles with matching selectors are applied consecutively, in definition order.

and

> Specificity, and specificity overrides are unsupported.

You can read more about this in our docs [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/#selector-reference)! Hope this helps :)

**Comment by rachelkang** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please submit a feature request describing the enhancement you would like to see. Thank you!
