### ISSUE TITLE
[Bug] Line's Stroke and Rectangle's Fill doesn't rendered as expected while changing the system's appearance.

### ISSUE THREAD

**Issue by sthch** [xamarin/Xamarin.Forms#13093]
### Description
I have already set both Line's Stroke and Rectangle's Fill with AppThemeBinding, but when I changing the system's appearance in settings, their appearance doesn't change as expected. This problem occurs on both iOS and Android platforms.

### Steps to Reproduce
1. Create a Line or Rectangle.
2. Set the Line's Stroke or Rectangle's Fill with AppThemeBinding.
3. Run the application, change the system's appearance in settings.
4. You'll find that the Line or Rectangle's color doesn't rendered as excepted, but if you go back and re-enter, their color can be rendered correctly.

### Expected Behavior
![微信截图_20201210132438](https://user-images.githubusercontent.com/18411241/101725198-2bb5ea80-3aeb-11eb-8f8a-f557896409cf.png)

### Actual Behavior
![微信截图_20201210132507](https://user-images.githubusercontent.com/18411241/101725219-32446200-3aeb-11eb-84ee-2ec616016091.png)

### Basic Information
- Version with issue: 5.0-pre5
- Platform Target Frameworks:
  - iOS: 14.2
  - Android: 11

### Screenshots
![GIF 2020-12-10 12-00-32](https://user-images.githubusercontent.com/18411241/101725855-5f454480-3aec-11eb-8bfe-a2b7d3cdbf0b.gif)

**Comment by jsuarezruiz** [comment]
Could you attach a sample where reproduce the issue?. I created a small sample but cannot reproduce it:
![issue13093](https://user-images.githubusercontent.com/6755973/101752789-2ef0ac80-3ad2-11eb-9bd9-159d2fdd7d39.gif)

**Comment by sthch** [comment]
> Could you attach a sample where reproduce the issue?. I created a small sample but cannot reproduce it:
> ![issue13093](https://user-images.githubusercontent.com/6755973/101752789-2ef0ac80-3ad2-11eb-9bd9-159d2fdd7d39.gif)

Thanks for the reply!
Here is my code sample:

Page.xaml:
`<Line Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" Style="{StaticResource HorizontalSeparator}" />`
`                <Rectangle Grid.Row="4" Grid.Column="0" Grid.ColumnSpan="3" Margin="-15,0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" WidthRequest="{Binding Source={RelativeSource Mode=Self}, Path=Width}" HeightRequest="{Binding Source={RelativeSource Mode=Self}, Path=Height}" StrokeThickness="0">
                    <Rectangle.Fill>
                        <SolidColorBrush Color="{AppThemeBinding Light={StaticResource LightViewBackgroundColor}, Dark={StaticResource DarkPageBackgroundColor}}" />
                    </Rectangle.Fill>
                </Rectangle>`

App.xaml:
`        <Style x:Key="HorizontalSeparator" TargetType="Line">
            <Setter Property="X1" Value="0" />
            <Setter Property="X2" Value="{Binding Source={RelativeSource Mode=Self}, Path=Width}" />
            <Setter Property="Stroke">
                <SolidColorBrush Color="{AppThemeBinding Light={StaticResource LightSeparatorColor}, Dark={StaticResource DarkSeparatorColor}}" />
            </Setter>
            <Setter Property="HorizontalOptions" Value="FillAndExpand" />
            <Setter Property="VerticalOptions" Value="EndAndExpand" />
        </Style>`

**Comment by sthch** [comment]
> Could you attach a sample where reproduce the issue?. I created a small sample but cannot reproduce it:
> ![issue13093](https://user-images.githubusercontent.com/6755973/101752789-2ef0ac80-3ad2-11eb-9bd9-159d2fdd7d39.gif)

I've tried your demo, it works fine, but if I change the Fill Property to a SolidColorBrush(like the code below), the problem occurs.
`<Rectangle 
                           HorizontalOptions="Start"
                           HeightRequest="80"
                           WidthRequest="200">
                    <Rectangle.Fill>
                        <SolidColorBrush Color="{AppThemeBinding Black, Light=Green, Dark=Red}" />
                    </Rectangle.Fill>
                </Rectangle>`

**Comment by sthch** [comment]
@jsuarezruiz Additionally, if you set the Fill Property to a StaticResource, you must set the Fill Property to a Brush, otherwise the shape can't be rendered correctly, is that a bug?
