### ISSUE TITLE
[Bug] CollectionView.ScrollTo crashes (Android)

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#13099]
### Description

I updated my app to test with XF 5 Pre5. But now CollectionView.ScrollTo crashes. It crashes from Pre2 to Pre5. Pre1 works.
Message:
```
Java.Lang.IllegalStateException
  Message=Layout state should be one of 100 but it is 10
```

### Steps to Reproduce

1. Use: CollectionView.ScrollTo(item, null, ScrollToPosition.MakeVisible, true);

### Expected Behavior
Not crash

### Actual Behavior
Crash with animate=true. Setting animate=false works.

### Basic Information

- Version with issue: XF 5 Pre2
- Last known good version: XF 5 Pre1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

### Workaround
CollectionView.ScrollTo(item, null, ScrollToPosition.MakeVisible, false);

**Comment by PureWeen** [comment]
@AlleSchonWeg can you attach a repro? I've attached my attempt and it's not crashing

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5677019/Archive.zip)

**Comment by AlleSchonWeg** [comment]
@PureWeen
Sorry, but i can't create a repro. I tried it, but it's not crashing. Only if i use our app its crash.
I think it has something to do with the content size changing. We use a horizontal CollectionView in a grid. And if we click a item in the collection view we call scrollto to make the item completely visible. After the click we update a placeholder contentview in a another grid cell with different custom controls to display different content.
On one of this custom controls we set a HeightRequest. In my tests i remove the HeigthRequest and the scrollto with animate works. Setting HeightRequest again it crashes again. Then i need to set animate false then it works with HeightRequest.
Setting HeightRequest in my repro try works too.

**Comment by PureWeen** [comment]
@AlleSchonWeg can you test the other pre's as well so we can try to narrow down between which pre this started happening for you?

**Comment by PureWeen** [comment]
@AlleSchonWeg Wait I see in your description you said it started with Pre2

**Comment by hartez** [comment]
> one of this custom controls we set a HeightRequest

@AlleSchonWeg Can you tell us more about this custom control?

**Comment by AlleSchonWeg** [comment]
Thank you for your support.
@hartez the control is dervied from ContentView. No xaml, just the cs file. One BindingProperty with a complex object. We create an AbsoluteLayout and set it as the content.  If the bindingProperty changes we change the children from the AbsoluteLayout.

**Comment by AlleSchonWeg** [comment]
I commented all out at the usercontrol. Still crashing.
The strange thing is, we set the HeightRequest to 500. If i set it to 200, 100 or 50 it works.

**Comment by AlleSchonWeg** [comment]
I will close this issue. With 5.0 it works.
