### ISSUE TITLE
[Bug] Frame.Background not displaying GradientBrush on iOS

### ISSUE THREAD

**Issue by sthch** [xamarin/Xamarin.Forms#13092]
### Description
Set GradientBrush as Frame's background doesn't work on iOS, but working fine on Android.

### Expected Behavior
Frame's background can be rendered as expected on Android.
![微信截图_20201210102831](https://user-images.githubusercontent.com/18411241/101713368-7a0abf80-3ad2-11eb-9e42-a11e9be16697.png)

### Actual Behavior
Frame's background can't be rendered correctly on iOS.
![微信截图_20201210102923](https://user-images.githubusercontent.com/18411241/101713412-94dd3400-3ad2-11eb-8c54-198de6ce1819.png)

### Basic Information

- Version with issue: 5.0-pre5
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 10

**Comment by jsuarezruiz** [comment]
I have created a sample where try to reproduce the issue:
[Issue13092.zip](https://github.com/xamarin/Xamarin.Forms/files/5671510/Issue13092.zip)

But cannot reproduce it:
<img width="1527" alt="Captura de pantalla 2020-12-10 a las 10 02 41" src="https://user-images.githubusercontent.com/6755973/101750201-fac7bc80-3ace-11eb-854f-aa2b184ef134.png">

Tested with Xamarin.Forms 5.0-pre5 on iOS 14 and Android 10. Could you review the attached sample or attach a sample where reproduce the issue?

Some questions:
- Do you use Visual?
- Are you using DynamicResource, AppThemeBinding etc?

**Comment by sthch** [comment]
> I have created a sample where try to reproduce the issue:
> [Issue13092.zip](https://github.com/xamarin/Xamarin.Forms/files/5671510/Issue13092.zip)
> 
> But cannot reproduce it:
> <img alt="Captura de pantalla 2020-12-10 a las 10 02 41" width="1527" src="https://user-images.githubusercontent.com/6755973/101750201-fac7bc80-3ace-11eb-854f-aa2b184ef134.png">
> 
> Tested with Xamarin.Forms 5.0-pre5 on iOS 14 and Android 10. Could you review the attached sample or attach a sample where reproduce the issue?
> 
> Some questions:
> 
> * Do you use Visual?
> * Are you using DynamicResource, AppThemeBinding etc?

Thanks for the reply!
I've find that the reason of my problem is I forget setting the Offset of the GradientStop, after setting the Offset, everything goes fine.
(BUT, on Android, it's all fine without setting the Offset of the GradientStop)

**Comment by jsuarezruiz** [comment]
Ohh, I see. Thanks for your feedback!. I sent a PR to have the same behavior between platforms.
