### ISSUE TITLE
Xamarin forms Android debugging always breaks on exceptions even when exception is disabled and handled

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#13102]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Xamarin-forms-Android-debugging-always-b/1276717)._

---
[severity:It's more difficult to complete my work]
In 16.9.0 Preview 1, when debugging a Xamarin Forms app on an Android device, the "Exception Settings" check boxes have no effect and the debugger always breaks.

As shown in the screenshot, the Acr.* exception should not break even when unhandled.  However, they break into the debugger even when they are handled in user code and even though they are configured to "Continue when unhandled in user code"  I am using "just my code" debug setting.  I tried deleting and re-creating those exception settings but this makes no difference. Build Debugging information is set to "portable".

I am unsure when this problem started. I've been using preview builds for a while and this problems has been happening with multiple previews.  I see similar issues that were fixed in the past but it seems they have cropped up again.

---
#### Feedback Bot on 12/3/2020, 08:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Christopher St-Pierre on 12/3/2020, 08:25 PM: 

<p>FYI : I have the same kind of issue! Even if "Break when this exception type is thrown" is uncheck, VS will show me the Exception Unhandled.</p>

---
### Original Solutions
(no solutions)

**Comment by MaximMikhisor** [comment]
Have same issue in Version 16.9.0 Preview 2.0

**Comment by rachelkang** [comment]
Hi there, thanks for submitting this issue. Would you mind sharing the screenshot again? I unfortunately can't seem to locate it. If you could share any relevant code, that would also be helpful!

Also, this sounds like it may be a VS issue. With what version(s) of VS have you _not_ experienced this issue?

**Comment by MaximMikhisor** [comment]
Hi Rachel,
Maybe you are aright. In my case I updated VS to latest "Microsoft Visual Studio Community 2019 Preview
Version 16.9.0 Preview 2.0", and this bug disappeared.

**Comment by rachelkang** [comment]
@MaximMikhisor awesome! I'll close this issue then, but please feel free to reopen with the additional info if you're having issues again.

**Comment by TheresasAccount** [comment]
I am encountering this issue as well. Just upgraded to Visual Studio Enterprise Edition 16.9.0 Preview 2.0 and that didn't seem to fix the issue. It's appeared at roughly the same time as I started using Enterprise edition, downloading community now to see if there is a difference.

**Comment by TheresasAccount** [comment]
Turned out to be solved by deleting and re-cloning the repository

**Comment by KithorasCarzyl** [comment]
I also experience this issue on Android

Microsoft Visual Studio Community 2019 Version 16.10.3
Xamarin.Forms 5.0.0.2083

**Comment by PredatH0r** [comment]
This problem also occurs with VS 2019 Community Version 16.11.4
Xamarin.Android SDK 11.4.0.5
Android Simulator running Android 12.

Only when I disable ALL first-chance exceptions, the debugger doesn't break. As soon as a single "Common Language Runtime Exceptions" is enabled, VS breaks on every other first chance exception too.

**Comment by marcos-marimon** [comment]
Hi there... Same issue here using VS2022 Enterprise 17.1.2 and Xamarin.Android SDK 12.2.0.4. The application is closed after showing the exception dialog, despite all of the exceptions are disabled in exception settings.
