### ISSUE TITLE
[Enhancement] CollectionView could scroll special offset to exact positions, not just scroll an item at an index into view or Scroll an item into view.

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#13108]
## Summary

Currently,CollectionView defines two ScrollTo methods, that scroll items into view. One of the overloads scrolls the item at the specified index into view, while the other scrolls the specified item into view. 

But we need CollectionView could scroll special offset to exact position. And it can show the process of scrolling, rather than jumping to the final position.

## Intended Use Case
User coud scroll the CollectionView to special offset , not just scroll an item at an index into view or Scroll an item into view.

**Comment by Tommigun1980** [comment]
Is this the same as https://github.com/xamarin/Xamarin.Forms/issues/13198?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
