### ISSUE TITLE
IndicatirView not updating position in the latest xf pre release

### ISSUE THREAD

**Issue by AswinPG** [xamarin/Xamarin.Forms#13115]
### Steps to Reproduce

1. Create a  carouselview and an indicatorview
2. Link them togethet by passing in the indicatorview name to the carouselviews indicatorview property
3. swipe the carouselview, indicator does not change position

### Expected Behavior
Indicator updates position
### Actual Behavior
indicator does not change position
### Basic Information

- Version with issue:
- Last known good version: 5.0 pre 5
- Platform Target Frameworks: 
  - iOS:  Can't check
  - Android: 10
  - UWP:  didn't check
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

```
```

**Comment by AswinPG** [comment]
False alarm.. Sorryy

**Comment by AswinPG** [comment]
It happens only if all items in the itemsource are the same

**Comment by Kapusch** [comment]
I've encountered the same behaviour with XF 5.0 and was not sure about what actually happens.
And it is indeed because I initialize CarouselView with 3 default photos, which are exactly the same...

Thank you for providing your last comment !

**Comment by Kapusch** [comment]
My workaround for this @AswinPG  : using a [DataTemplateSelector](https://docs.microsoft.com/fr-fr/xamarin/xamarin-forms/user-interface/carouselview/populate-data#choose-item-appearance-at-runtime) for the CarouselView.

Indeed, I'm able to display the same default template but with 3 different Items in ItemsSource (DefaultMainPhoto, DefaultAlt1Photo, DefaultAlt2Photo).
