### ISSUE TITLE
[Bug] changing Button.CharacterSpacing leads to an incorrect computed width (too small) on iOS

### ISSUE THREAD

**Issue by softlion** [xamarin/Xamarin.Forms#13116]
### Description
Setting Button.CharacterSpacing to 2.5 on a simple "OK" button leads to a computed width too small on iOS
Result:
![image](https://user-images.githubusercontent.com/190756/101915897-853f1780-3bc6-11eb-96bd-165c14e03ee1.png)

### Expected Behavior
The OK letters should stay inside the button when it has a background.

### Actual Behavior
The OK letters are outside the button's background.

### Basic Information

- Version with issue: all
- Last known good version: the version without CharacterSpacing 
- Platform Target Frameworks:
  - iOS: 14.2 (tested on)

### Repro

- create a horizontal stacklayout with 2 items: a label and a button.
- set the label horizontaloption to FillAndExpand so it takes as much space as possible. The button should not shrink below its minimal width, which is correct when using the default font and the default CharacterSpacing. But which is incorrect otherwise.

### Workaround

None

**Comment by hartez** [comment]
@softlion I'm trying to reproduce this issue, but so far no luck. My attempt is below - is there a detail I'm missing?

[_13116 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5773193/_13116.Repro.zip)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by softlion** [comment]
What are you trying to achieve with this repro. Buttons have a padding. At least put a text with a lot of letters.
