### ISSUE TITLE
[Enhancement] [iOS] Allow overriding ViewWillAppear/ViewDidDisappear in WkWebViewRenderer?

### ISSUE THREAD

**Issue by omatrot** [xamarin/Xamarin.Forms#13114]
## Summary
Android.Webkit.WebView allows to override OnAttachedToWindow/OnDetachedFromWindow:

```
public partial class HybridWebViewRenderer : ViewRenderer<HybridWebView, Android.Webkit.WebView>
{
       protected override void OnAttachedToWindow()
        {
            base.OnAttachedToWindow();
            ...
        }

        protected override void OnDetachedFromWindow()
        {
            ....
            base.OnDetachedFromWindow();
        }
}
```

## API Changes

Allow to override ViewWillAppear/ViewDidDisappear from WkWebViewRenderer.

```
public partial class HybridWebViewRenderer : ViewRenderer<HybridWebView, WkWebViewRenderer>, IWKScriptMessageHandler
{
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);
        }
        public override void ViewDidDisappear()
        {
            base.ViewDidDisappear();
        }
}
```

May be there is a workaround to match the Android implementation.
Any help appreciated.

**Comment by PureWeen** [comment]
ViewWillAppear(Disappear) are UIViewController overrides

I think this SO post covers the range of method choice you have on iOS
https://stackoverflow.com/questions/5060958/uiview-did-appear

Also, I think your renderer should be

public partial class HybridWebViewRenderer : WkWebViewRenderer
