### ISSUE TITLE
[Enhancement] CollectionView Implement IsHeaderStickyProperty for CollectionView.Header

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#13121]
## Summary
As mentioned in the CollectionView  Spec https://github.com/xamarin/Xamarin.Forms/issues/3172, a bindable property named: `IsHeaderStickyProperty` : Specifies whether the header remains in place as the user scrolls. The default is `True`.

Supposed to be implemented as I understand (and as requested in this feature request) to be used not for Group headers but for single main header `CollectionView.Header`. It does not exist currently.

## API Changes
Refers to Spec.

## Intended Use Case
Provide the ability to stick the CollectionView.Header when the user scroll (not talking about group header).

**Comment by angelru** [comment]
Any ideas?
https://luismts.com/stickyheader-xamarin-forms/

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
