### ISSUE TITLE
Grid layout broken when updating to latest xamarin forms

### ISSUE THREAD

**Issue by gabsterdev1** [xamarin/Xamarin.Forms#13127]
### Description
We have quite a few forms where we do some overlapping to achieve the look as in the pic below. We noticed that any version of Xamarin forms above 4.8.0.1560 will break the layout , this includes the latest xamarin forms 5.0.0.1791-pre5 

### Steps to Reproduce

1. I have attached a sample repo
2. Is set to xamarin forms 4.8.0.1560
3. Build and run and you will see 

![image](https://user-images.githubusercontent.com/43923935/102006783-ad8c5a80-3d1b-11eb-8dfc-7d014e96494b.png)

4. Update to 5.0.0.1791-pre5 and the layout is now broken.

This prevents us to upgrade to the latest xamarin forms  and we are keen to move to 5 when released.

Many thanks for your prompt feedback

[SampleRepo.zip](https://github.com/xamarin/Xamarin.Forms/files/5684352/SampleRepo.zip)

**Comment by bPoller2810** [comment]
Sadly this problem seems in a few cases still persists up to 5.0.0.2244. I cant repo this in a empty project right now, but got it in 2 Production apps happening.
