### ISSUE TITLE
[Bug] CarouselView.CurrentItem not working at all

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms#13122]
### Description
I have a `CarouselView` with `ItemsSource` and `CurrentItem` bound to dependency properties defined in the page. Then I have 2 buttons to increment and decrement current item. The problem is that setting `CarouselView.CurrentItem` has no effect on 5.0-pre5. Although it does work properly on version 4.8.

Interesting part is that after swiping the item, current item 'auto-corrects' and starts to work properly.

### Steps to Reproduce

1. Open and run the attached solution
2. Click Next button
3. See that CurrentItem item defined in the page is changed, but `CarouselView` doesn't navigate to the item

### Expected Behavior
CarouselView should navigate to CurrentItem.

### Actual Behavior
CarouselView stays at initial item.

### Basic Information

- Version with issue: 5.0-pre5
- Last known good version: 4.8
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 10.0
  - UWP:  not tested

### Screenshots
Xamarin Forms 5.0-pre5
![5 0-pre5](https://user-images.githubusercontent.com/45604126/101981902-7a40c180-3c70-11eb-9c7a-5695a4bfef7c.gif)

Xamarin Forms 4.8
![4 8](https://user-images.githubusercontent.com/45604126/101981910-83ca2980-3c70-11eb-9a52-4034daaa938c.gif)

![image](https://user-images.githubusercontent.com/45604126/101981863-38b01680-3c70-11eb-9005-593239b15713.png)

![image](https://user-images.githubusercontent.com/45604126/101981869-4b2a5000-3c70-11eb-86dd-917ba7c9b5d9.png)

### Reproduction Link

[CarouselView.CurrentItem.zip](https://github.com/xamarin/Xamarin.Forms/files/5682925/CarouselView.CurrentItem.zip)

**Comment by johnsheatjx** [comment]
This seems to still be an issue on iOS.

**Comment by satzmuthu** [comment]
> This seems to still be an issue on iOS.

Yes facing issue in iOS

**Comment by jrasbr** [comment]
This still does not work on Android. If i set current item to 3 - it will not update the carousel position, but if i set it to 1 or 2 it works fine.
In other words, it will update if CurrentItem is only two places from current position
