### ISSUE TITLE
Collection View Crashes When StackLayout that contains it is bound by HeightRequest

### ISSUE THREAD

**Issue by amy-perelberg-self** [xamarin/Xamarin.Forms#13134]
### Steps to Reproduce

1. Create StackLayout and put something above collectionView (like a grid)
2. Set HeightRequest property of StackLayout to say half the screen height
3. Note that GridListingView below is a subclass of CollectionView
4. Note the HeightRequest Property of StackLayoutEx (which is simply StackLayout) -- without the HeightRequest the Crash DOES NOT OCCUR!
### Expected Behavior
IOS Application doesn't crash
### Actual Behavior
Objective-C exception thrown.  Name: NSRangeException Reason: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
Native stack trace:
	0   CoreFoundation                      0x00007fff2041daf2 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff20177e78 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2049a77f _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff2031af1c -[__NSArrayM objectAtIndex:] + 142
	4   UIKitCore                           0x00007fff23dc01b0 -[_UIFlowLayoutSection frameForItemAtIndexPath:] + 360
	5   UIKitCore                           0x00007fff23daa8e2 -[UICollectionViewFlowLayout _frameForItem:inSection:usingData:] + 153
	6   UIKitCore                           0x00007fff23da40e6 -[UICollectionViewFlowLayout layoutAttributesForItemAtIndexPath:usingData:] + 376
	7   UIKitCore                           0x00007fff23da4426 -[UICollectionViewFlowLayout layoutAttributesForItemAtIndexPath:] + 502
	8   UIKitCore                           0x00007fff23d9eefa -[UICollectionViewData layoutAttributesForItemAtIndexPath:] + 329
	9   UIKitCore                           0x00007fff23d6c395 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 2189
	10  UIKitCore                           0x00007fff23d6c593 -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 88
	11  glassgrab                           0x0000000109921e19 xamarin_dyn_objc_msgSend + 217
	12  ???                                 0x00000001123ccc29 0x0 + 4600941609

"*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array"
### Environment

```
```

### Example Project (If Possible)
                    <cc:StackLayoutEx Orientation="Vertical" Padding="10,0,10,0" Spacing="2" HeightRequest="{Binding TabControlHeight}"
                                      WidthRequest="{Static gg:AppHelper.ScreenWidthLessMargin}">
                        <cc:GridEx>
                            <cc:GridEx.RowDefinitions>
                                <RowDefinition Height="40"/>
                                <RowDefinition Height="Auto"/>
                            </cc:GridEx.RowDefinitions>
                            <cc:GridEx.ColumnDefinitions>
                                <ColumnDefinition Width="40"/>
                                <ColumnDefinition Width="*"/>
                                <ColumnDefinition Width="40"/>
                            </cc:GridEx.ColumnDefinitions>
                            <cc:ImageEx x:Name="ivBackToCollections" Source="{Static gg:Images.Img_backbutton}" HorizontalOptions="Start" Aspect="AspectFill"
                                    WidthRequest="40" HeightRequest="40" ImageTintColor="{DynamicResource GrayColor}"
                                    Grid.Column="0"/>
                            <Label x:Name="lbCollectionTitle" Style="{DynamicResource TitleLabelStyle}" 
                                   VerticalTextAlignment="Center" HorizontalTextAlignment="Center"
                                   VerticalOptions="Center" HorizontalOptions="Center" 
                                   TextColor="{DynamicResource ThemeColor}" Text="{Binding TimeLeftToGrab}" Grid.Column="1"/>
                            <cc:ImageEx x:Name="ivPaymentProcessor" WidthRequest="32" HeightRequest="32" Aspect="AspectFit" 
                                   VerticalOptions="Center" HorizontalOptions="End" Grid.Column="2"
                                   Source="{Binding PaymentProcessorImage}"/>
                            <Label x:Name="lbCollectionTitle2" Style="{DynamicResource TitleLabelStyle}" Text="{Binding CollectionTitleDisplayed}" 
                                   Grid.Column="0" Grid.ColumnSpan="3" Grid.Row="1"/>
                        </cc:GridEx>
                        <ggcc:GridListingView x:Name="lvCollection" IsVertical="True" DisplayPrice="True" DisplayDetails="False"
                                              BackgroundColor="{DynamicResource WhiteInLightMode}" SoldBannerType="Grab" BoughtBannerType="Grab"
                                              Columns="{Binding GrabCollectionColumns}" ListingSize="{Binding GrabCollectionListingSize}"
                                              VerticalSpacing="{Binding GrabCollectionListingSpacing}" HorizontalSpacing="{Binding GrabCollectionListingSpacing}"
                                              CornerRadius="{Binding GrabCollectionListingCorner}"
                                              Listings="{Binding GrabCollectionListings}"/>
                    </cc:StackLayoutEx>

**Comment by rmarinho** [comment]
@amy-perelberg-self  i tried to reproduce this but wasn't able to.. can you please upload a small reproduction ? 

Thanks

**Comment by amy-perelberg-self** [comment]
@rmarinho  I will try to create some standalone code, as this is a part of a very large project.
The crash, however, occurs every time there is a HeightRequest present. As soon as I remove it, the crash doesn't happen anymore.
This must have something to do with the IOS's TableView not having any items at the time you guys do the measuring for the layout.

**Comment by Redth** [comment]
It's going to be very difficult to reproduce this without a sample.  If you could please try and create a smaller sample which exhibits this behaviour and attach it, we might be able to see what's happening.

Thanks

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
