### ISSUE TITLE
[Bug] Shell Tabs in RTL Are not reversed based on FlowDirection 

### ISSUE THREAD

**Issue by AhmedAbuelnour** [xamarin/Xamarin.Forms#13138]
### Description

Example 

    <TabBar x:Name="ShellBar">
        <Tab Title="Home" Icon="home.png"  Route="HomePage">
            <ShellContent  ContentTemplate="{DataTemplate home:HomePage}" />
        </Tab>
        <Tab Title="Bills" Icon="bill.png"  Route="OrdersPage">
            <ShellContent  ContentTemplate="{DataTemplate bills:OrderPage}" />
        </Tab>

        <Tab Title="Cart" Icon="cart.png"  Route="CartPage">
            <ShellContent  ContentTemplate="{DataTemplate cart:CartPage}" />
        </Tab>
        <Tab Title="Account" Icon="account.png"  Route="AccountPage">
            <ShellContent  ContentTemplate="{DataTemplate account:AccountPage}" />
        </Tab>
    </TabBar>

### Expected Behavior
In LTR , and home is selected as Home Page by default

( Home - Orders - Cart - Account) 

In RTL it should be 

(Account - Cart - Orders - Home) but of course with its translation (الرئيسية - الطلبات - العربة - الحساب)

with selecting the Home as default as well

### Actual Behavior

The RTL behaves like LTR exactly, which is wrong

using XF: 4.8

**Comment by rmarinho** [comment]
Hello is just tested this on android and seems to be working. Can you please give us more details, what platforms you see this issue, and please upload a small reproduction sample.

with LTR
![image](https://user-images.githubusercontent.com/1235097/102081736-9aa38400-3e08-11eb-8323-a5376c321829.png)

width RTL
![image](https://user-images.githubusercontent.com/1235097/102081704-8f505880-3e08-11eb-9873-0cfc4b127ec7.png)


Thanks

**Comment by AhmedAbuelnour** [comment]
Here is a github link for the sample https://github.com/AhmedAbuelnour/ShellRLT

**Comment by AhmedAbuelnour** [comment]
Switching the FlowDirection doesn't change the two icons position

**Comment by AhmedAbuelnour** [comment]
@rmarinho Any updates?

**Comment by AhmedAbuelnour** [comment]
Is there any news about this issue?

**Comment by AhmedAbuelnour** [comment]
found a solution
