### ISSUE TITLE
[Bug]  Shell Deferral is null during a navigation

### ISSUE THREAD

**Issue by pictos** [xamarin/Xamarin.Forms#13131]
### Description

If I have a code inside `Shell.Navigating` event that can throw an NRE on DeferralToken.

### Steps to Reproduce

1. Run the code on the link
2. Press the Login button
3. After press the Navigation button a couple of times and after that try to go back using the top arrow.

### Expected Behavior
I can navigate without errors.

### Actual Behavior
I saw an exception

### Basic Information

- Version with issue: branch 5.0.0
- Last known good version: NaN
- Platform Target Frameworks:
  - Android: MonoDroid10
- NuGet Packages: Xamarin.CommunityToolkit
- Affected Devices: Android devices

### Environment
Visual Studio 2019 16.7.7

### Screenshots

https://youtu.be/Acy1WOJvWWQ

### Reproduction Link

https://github.com/pictos/Xamarin.Forms.Sandbox/tree/mvpconf

### Workaround

The workaround is to add a null check inside the

**Comment by rmarinho** [comment]
Ok i updated the code so we can run it 

https://github.com/rmarinho/Xamarin.Forms.Sandbox/tree/mvpconf
