### ISSUE TITLE
[Enhancement] Remove Unit-Agnostic Code, Transition to angularsen/UnitsNet Library as a Standard

### ISSUE THREAD

**Issue by ScottSEA** [xamarin/Xamarin.Forms#13130]
## Summary
The Xamarin Forms library suffers from primitive obsession.  Let's move away from using `long` and `string` for values that should be _objects_ in their own right.

## API Changes

Refactor the codebase so that the Speed, Distance, Temperature, etc... are represented by the appropriate type, not just `long` or `string`

### Example:  
```c#
        public double? Speed { get; set; }
        public double? VerticalAccuracy { get; set; }
        public double? Accuracy { get; set; }
        public double? Altitude { get; set; }
        
        Speed = 1234;
         VerticalAccuracy = 2;
```
While the comments are very helpful, and specify the unit that the code is intended to imply, they do _nothing_ to ensure that the values are clear, concise, and intuitive **in the code**.

Contrast with this:

```c#
        public Speed Speed { get; set; }
        public Length VerticalAccuracy { get; set; }
        public Length Accuracy { get; set; }
        public Length Altitude { get; set; }

         Speed = 1234.MetersPerSecond(); // extension method makes this clear
         Speed = 1234.Meters() // does not compile!
         VerticalAccuracy = Length.FromMeters(2); // more verbose, but also clear.
```
## As an interesting side note:
The [UnitsNet.WindowsRuntimeComponent](https://www.nuget.org/packages/UnitsNet.WindowsRuntimeComponent/) is a dependency of the [Microsoft.IoT.Devices](https://www.nuget.org/packages/Microsoft.IoT.Devices) repo, so we wouldn't exactly be breaking new ground.

**Comment by hartez** [comment]
@ScottSEA Where in Forms are we doing this? I don't recall anywhere that we have a concept of speed, or length, or any other physical measurements.

**Comment by ScottSEA** [comment]
I think you're right.  I should've posted this to Xamarin.Essentials.  Mea Culpa.
