### ISSUE TITLE
[Enhancement] Make MenuShellItem class public

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms#13142]
## Summary
I would like to use compiled bindings in my `Shell.MenuItemTemplate` DataTemplate. 

## API Changes
Make MenuShellItem class public.

## Intended Use Case
I would like to use compiled bindings in my `Shell.MenuItemTemplate` DataTemplate. To do so, I need to specify `x:DataType` attribute. However, the type used during runtime is `MenuShellItem` which is an internal class. I can't use `ShellItem` type (which a base class for `MenuShellItem` class) for `x:DataType`, because I need to get to `MenuShellItem.MenuItem.Command` value. I have a custom button inside the DataTemplate and I want to wire `Command` and `CommandParameter` from `MenuItem` object to it.

![image](https://user-images.githubusercontent.com/45604126/102136243-6e642380-3e59-11eb-9ce2-29b69f12e974.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
