### ISSUE TITLE
[Enhancement] Capture Pointer on UWP while using PanGestureRecognizer

### ISSUE THREAD

**Issue by lutes1** [xamarin/Xamarin.Forms#13140]
## Summary
PanGestureRecognizer does not capture the pointer on UWP though it does on Android, iOS and macOS.

## API Changes
Perform pointer capture on mouse pressed.

## Intended Use Case
Currently to move a view around its parent, on UWP, we must attach a PanGestureRecognizer to its parent, otherwise no events are fired for the continuous gesture after the pointer leaves the bounds of the desired view. That is the case only for UWP, on Android, iOS and macOS the pointer captures all the events until released.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
