### ISSUE TITLE
[Bug] Shapes broken in Xamarin if used within NavigationPage once and navigated back

### ISSUE THREAD

**Issue by maexsp** [xamarin/Xamarin.Forms#13164]
### Description
Shapes are only correct rendered if shown the very first time. When navigating away from a page with shapes and re-open the page again the shapes are totally miss-rendered. See example in my repo.

### Steps to Reproduce

1. Open NavigationPage with Shapes
2. Navigate Back
3. Navigate again into Page with Shapes

### Expected Behavior
Shapes rendered correctly when opening navigation page a 2nd time.

### Actual Behavior
All shapes vertically misplaced and shrinked to 1 px.

### Basic Information

- Version with issue: XF 4.8.0.1687
- Last known good version: unknown
- Platform Target Frameworks: 
  - iOS:  14
  - Android: 9.0
  - UWP:  19.0.3
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: Android emulator, Android Samsung phones, iPhone 

### Screenshots
![shapesDemo](https://user-images.githubusercontent.com/15746917/102351839-631f0e00-3fa7-11eb-99d0-fbf1eaa26e46.gif)

### Reproduction Link
https://github.com/maexsp/XamarinFormAndroidIdiom/tree/ShapesDemo

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/13167
