### ISSUE TITLE
DatePicker don't trigger event when current date is selected

### ISSUE THREAD

**Issue by AleOladayoTosin** [xamarin/Xamarin.Forms#13162]
### Description
     Xamarin forms DatePicker don't trigger event when current date is selected.
     
![image](https://user-images.githubusercontent.com/52206933/102346121-a759e080-3f9e-11eb-953d-82041c1394e8.png)

### Expected Behavior
     There should be an event that triggers when current date is selected
     
### Actual Behavior
     The only event that is available is DateChanged event
     
### Basic Information

- Version with issue:  4.8.0.1687
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:

**Comment by rachelkang** [comment]
Hi, @AleOladayoTosin - thanks for submitting this issue! Are you referring to the [DateSelected](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.datepicker.dateselected?view=xamarin-forms) event? You can find more info on it in our docs [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datepicker#datepicker-in-an-application) if you're not familiar with it. If you're familiar with it and you're saying that this event is not firing, please share your project or a sample project that reproduces the issue! And if I'm completely misunderstanding what you're describing, I would really appreciate more clarity :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
