### ISSUE TITLE
[Bug] DatePicker doesn't use dark theme

### ISSUE THREAD

**Issue by PrimoDev23** [xamarin/Xamarin.Forms#13178]
### Description
Hello guys,
the bug appears inside of the DatePicker control. If you are using dark theme under android the DatePicker dialog will look like this on Visual Default
![image](https://user-images.githubusercontent.com/46970398/102463453-666bd580-404b-11eb-9351-7f922b120fbf.png)

And it will look like this when using dark mode with Visual Material set
![image](https://user-images.githubusercontent.com/46970398/102465554-15111580-404e-11eb-8778-8aa7b1608cd5.png)

### Steps to Reproduce

1.  Create a new Application
2.  Add a DatePicker control
3.  Make sure your device is using dark mode/theme
4.  Run the project and open the DatePicker

### Expected Behavior
DatePicker background would be dark themed

### Actual Behavior
DatePicker background is just white with white text on it (Visual Default)
Or not even themed but at least readable (Visual Material)

### Basic Information

- Version with issue: 5.0.0.1791-pre5
- Last known good version: I don't know, but probably never?
- Platform Target Frameworks: 
  - Android: Android 10+

Editted to add Visual Material information

### Repro link
Repro: [Issue13178.zip](https://github.com/xamarin/Xamarin.Forms/files/5727054/Issue13178.zip)

**Comment by BurkusCat** [comment]
I think this issue is the same as #9033 (pretty much exactly 1 year old :)).

**Comment by irongut** [comment]
Issue #9033 mentions a workaround - remove the following line from `styles.xml` but this line does not appear in that file any more. Is there a current workaround for this issue other than using Visual Material?

```xml
<item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>
```

Oddly TimePicker works fine, this issue just happens with DatePicker.

**Comment by CybrZr00** [comment]
still nothing?

**Comment by PrimoDev23** [comment]
> still nothing?

Looks like xamarin got discontinued in favor of MAUI. Almost nothing is done here anymore and the latest version has still major issues...

**Comment by jfversluis** [comment]
Duplicate of #9033
