### ISSUE TITLE
[Bug] [UWP] App Center logs

### ISSUE THREAD

**Issue by rustem08** [xamarin/Xamarin.Forms#13185]
### Description
AppCenter reports the following a crash of my application on UWP:

ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32, Void*) 
**System.Exception: An async operation was not properly started. Only a single ContentDialog can be open at any time.**

**Stack traces**
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32, RuntimeTypeHandle)
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32, Void*)
__Interop.ForwardComStubs.Stub_3[TThis, TResult](__ComObject, Int32) + 0x37
Windows.UI.Xaml.Controls
ContentDialog.ShowAsync ()
Xamarin.Forms.Platform.UWP.Platform
<ShowAlert>d__59.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices
TaskAwaiter.ThrowForNonSuccess (Task)
System.Runtime.CompilerServices
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (Task)
System.Runtime.CompilerServices
TaskAwaiter.ValidateEnd (Task)
System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
ConfiguredTaskAwaiter.GetResult ()
Xamarin.Forms.Platform.UWP.Platform
<OnPageAlert>d__58.MoveNext ()
System.Runtime.ExceptionServices
ExceptionDispatchInfo.Throw ()
System.Runtime.CompilerServices.AsyncMethodBuilderCore
<>c.<ThrowAsync>b__7_0 (Object)
System
Action`1.Invoke (T)
System.Threading.WinRTSynchronizationContext
Invoker.InvokeCore ()
System.Runtime.InteropServices
McgMarshal.ThrowOnExternalCallFailed (Int32, RuntimeTypeHandle)
__Interop
ComCallHelpers.Call (__ComObject, RuntimeTypeHandle, Int32)
__Interop
ForwardComStubs.Stub_15[TThis] (__ComObject, Int32)
Microsoft.AppCenter.Utils
ApplicationLifecycleHelper.<ctor>b__17_1 (Object, UnhandledErrorDetectedEventArgs)

Unfortunately, this will be one of many Xamarin.Forms bugs on UWP that either happen randomly, or are connected only to some computer configurations. I do excessive testing and I have never encountered this crash on my computer. Providing a repro solution will be almost impossible. Still, I think that even these bugs, which are very hard to reproduce, should not be ignored if they lead to crashes. I hope that the stack trace from AppCenter will be helpful.

### Steps to Reproduce

Unable to reproduce locally. The crash probably occurs randomly, or only on some device configurations. I have looked to Microsoft Partner Center Health reports and 21 crashes are reported at the last 30 days. So I guess this has been the same user and the app crashed repeatedly.

### Expected Behavior
No crashes.

### Actual Behavior
Application crashes.

### Basic Information

- Version with issue:
-  4.8.0.1687
- Last known good version:
- Platform Target Frameworks: 
  - UWP:  18362
- NuGet Packages:
- Xamarin.Forms 4.8.0.1687
- Xamarin.Essentials 1.5.3.2
- Microsoft.AppCenter.Crashes 3.4.3
- Microsoft.NETCore.UniversalWindowsPlatform 6.2.10
- Affected Devices:
UWP
Most affected OS
10.0.19041 50.0%
10.0.18363 50.0%
### Environment

Microsoft Visual Studio Community 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA895
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.553.28003
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.553.28003
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.553.28003
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResXManager   1.48.3862.0
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Workaround

No workaround

**Comment by rachelkang** [comment]
Hi, @rustem08 - thanks for submitting this issue. Would you mind elaborating on how you are using pop-ups (ContentDialog) in your app? If you could share sample code or a small project that recreates how you have pop-ups in your app, that would be really helpful. It's possible that this is a general UWP issue related to how and when the pop-ups are activated - adding some type of condition or delay between pop-ups may be helpful.

You may also find this comment on this older issue relevant/helpful: https://github.com/xamarin/Xamarin.Forms/issues/3015#issuecomment-399258505

**Comment by rustem08** [comment]
Hi, @rachelkang. I call the DisplayAlert method via two methods from the shared code:

```
public static async Task<bool> DisplayAppAlert(string title, string message, string ok, string cancel)
        {
            if (App.IsUITestRun)
            {
                return await Task.FromResult(true);
            }

            var uiHelper = DependencyService.Get<IUIHelper>();
            if (uiHelper?.IsOverlayAvailable == true)
            {
                await uiHelper.EnterStandardMode();
            }

            return await Application.Current.MainPage.DisplayAlert(
                title,
                message,
                ok,
                cancel);
        }

        public static async Task DisplayAppAlert(string title, string message, string ok)
        {
            if (App.IsUITestRun)
            {
                return;
            }

            var uiHelper = DependencyService.Get<IUIHelper>();
            if (uiHelper?.IsOverlayAvailable == true)
            {
                await uiHelper.EnterStandardMode();
            }

            await Application.Current.MainPage.DisplayAlert(
                title,
                message,
                ok);
        }
```
       
Also I use ContentDialog on the closing request from the UWP project :

```
...
Windows.UI.Core.Preview.SystemNavigationManagerPreview.GetForCurrentView().CloseRequested +=
                async (sender, args) =>
                {
                    if (app.AppData?.Timer?.TimerState == TimerState.NotActive)
                        return;

                    args.Handled = true;

                    //if user tries to close app from collapsed mode, we just expand it
                    //app will react to expand event in shared project
                    if (ApplicationView.GetForCurrentView().ViewMode == ApplicationViewMode.CompactOverlay)
                    {
                        await ApplicationView.GetForCurrentView().TryEnterViewModeAsync(ApplicationViewMode.Default);
                        //don't attempt to close app
                        return;
                    }

                    CloseAllOpenPopups();

                    ContentDialog onCloseDialog = new ContentDialog
                    {
                        Title = OSDependedResources.UWP_Close_App_Dialog_Title,
                        Content = OSDependedResources.UWP_Close_App_Dialog_Message,
                        PrimaryButtonText = OSDependedResources.UWP_Close_App_Dialog_ConfirmText,
                        CloseButtonText = OSDependedResources.Cancel
                    };

                    ContentDialogResult result = await onCloseDialog.ShowAsync();

                    if (result == ContentDialogResult.Primary)
                    {
                        Application.Current.Exit();
                    }
                };
...
 private static void CloseAllOpenPopups()
        {
            var popups = VisualTreeHelper.GetOpenPopups(Window.Current);
            foreach (var popup in popups)
            {
                if (popup.Child is ContentDialog dialog)
                {
                    dialog.Hide();
                }
            }
        }
```

I try to repro issue. For example I call 20 DisplayAppAlert from the cycle without await keyword but nothing.

Thank you for issue attention.

**Comment by jsuarezruiz** [comment]
I have done some tests to try to reproduce the issue, but I have not reproduced it. 
In your UWP code, the `CloseAllOpenPopups` method should avoid the issue. I have created a PR in Xamarin.Forms (need to review it with the team) to avoid open a ContentDialog if one is already open: #13720 (Alerts and Prompts).

**Comment by jsuarezruiz** [comment]
@rustem08 However, if you find more info or have a sample where reproduce the issue just let me know to review it.
