### ISSUE TITLE
[Bug] Platform warning recommends TargetPlatformVersion >= 10.0.17763.0 (current project is -1)

### ISSUE THREAD

**Issue by developer9969** [xamarin/Xamarin.Forms#13191]
Hi noticed that we seem to get the warning below not sure how to fix it. 

Severity	Code	Description	Project	File	Line	Suppression State

**Warning		Xamarin.Forms recommends TargetPlatformVersion >= 10.0.17763.0 (current project is -1)**	

this happens with the very latest xamarin forms 

Reproduce

1. Create a blank project
2. Update to the latest xamarin forms (stable)
3. you will see the warning

Suggestions?

many thanks

**Comment by VladislavAntonyuk** [comment]
Change min version of your uwp app

**Comment by developer9969** [comment]
I will close this issue as it only happened on earlier version and not uwp
