### ISSUE TITLE
[Bug] ResourceDictionary loaded from Source does not allow removing RD entries and inconsistent API-wise

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#13209]
### Description
Hot Reload needs API to query and modify ResourceDictionaries loaded from Source yet existing API is mostly inconsistent. Looks like ResourceDictoinary uses helper _mergedInstance field which is not properly assessible for hot reload. 

### Steps to Reproduce
1. Open attached project 
[XamarinApp9.zip](https://github.com/xamarin/Xamarin.Forms/files/5725708/XamarinApp9.zip)
.
2. Set Debug x86.
3. Build and Run.
4. Click on "Get count of resources" button.
  ### Actual: text stating that RD.Count and RD.MergedDiciionaries.Count are 0.
  ### Expected: RD.Count should be 2.
5. Click on "Lookup Color1 resource".
  ### Observe: text stating that Color1 is found and its value displayed.
6. Click on "Delete Color1 resource".
  ### Actual: text stating that Color1 resource is not found.
  ### Expected: text stating that resource deleted.
7. Click on "Lookup Color1 resource",
  ### Actual: text stating that Color1 is found and its value displayed.
  ### Expected: text stating that Color1 resource is not found.

**Comment by BretJohnson** [comment]
I test with SR2 and this is definitely better, with most issues fixed. However, I see that the merged Root.Resources has two entries (right number) but they both have a null key and null value. See screenshot below. So the delete test fails above (as Color1 can't be found in the resource dictionary).

![image](https://user-images.githubusercontent.com/245892/106648782-b866ad00-655e-11eb-946d-bab9de8c38e7.png)

**Comment by StephaneDelcroix** [comment]
@BretJohnson the delete succeed (and Remove() returns true), and you can see that after the Remove() the Count is 1, and LookupResource again fails (proving that this has been removed).

We KNOW there's some discrepancies in the way resources are counted, removed, enumerated, but we can not fix this in the XF 5 timeframe as it would be a breaking change for existing users, but a fix is planned for the next iteration.

In the meantime, we _believe_ you should be able to get whatever you need for HR to work with the current state.

(side node: the [null,null] is a example of mismatch between the enumerator and the count)

**Comment by Redth** [comment]
Closing this issue based on @StephaneDelcroix findings.  Please reopen if you have some more info.

**Comment by BretJohnson** [comment]
I retested myself here & all looks good. Thanks all.
