### ISSUE TITLE
[Bug] After PopAsync, Appearing page behavior is different

### ISSUE THREAD

**Issue by wooooooood** [xamarin/Xamarin.Forms#13208]
### Description
After `PopAsync`, Appearing page behaves different depending on how user navigated to that page.
I wonder if this behavior was intended in XF5 or a bug.

### Steps to Reproduce
With attached sample's Android app,
1. Press browse -> Press some Item -> Navigate back with back button or action bar's `<-` button
2. Log message(`Set PageIDString Called`) is never printed since It's not navigated via shell url

3. Press About -> Press button 'Move via Shell Navigation'
4. Log message(`Set PageIDString Called`) is printed, which means it was navigated by shell
5. Press some Item  -> Navigate back with back button or action bar's `<-` button
6. Again, log message(`Set PageIDString Called`) is printed.

### Expected Behavior
Getting shell navigation url value should not be called on any `PopAsync`.
Or behavior should be same in any situation.

### Actual Behavior
Shell url value is called or not after `PopAsync` depending on how user navigated initially.

### Basic Information

- Version with issue: 5 pre4 ~
- Last known good version: 4.8.1451
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10

### Environment

```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084
```

</details>

### Reproduction Link

[Check this updated repro!](https://drive.google.com/file/d/1_NhKd5nN5agC1kEzxANLC3Fhosx4u2gN/view?usp=sharing)

### Workaround

Instead of using `PopAsync`, Navigate via Shell url (which doesn't support animation but shows expected behavior)
With any better workaround, please share. Thank you.

**Comment by rachelkang** [comment]
Hi, @wooooooood - thanks for submitting this issue!

I'm seeing an exception thrown and app crash when I do the following steps:
1. Click on the "Move via Shell Navigation" button
2. Click on an item
3. Go "back"
4. Navigate back to "About" via Flyout
5. Navigate to "Browse" via Flyout

Can you try to resolve this error first, and then let us know if that changes anything with your original error as well? 
Still need to explore more, but these two issues could be related. Let us know if you need help!

**Comment by wooooooood** [comment]
Hi, @rachelkang! Thanks for the reply.
Actually I was facing the problem you mentioned while developing and made a new issue #13219 
But I'll replace the sample app not to produce further exceptions.
This problem still occurs but sure seems the two issues are related!
