### ISSUE TITLE
[Bug] Hot Reload 

### ISSUE THREAD

**Issue by edsulaiman** [xamarin/Xamarin.Forms#13200]
### Description
Multiple properties with name 'Background' found. "new" keyword to hide properties show an error during hot reload, the bug only occurs after build and then save to trigger hot reload

### Steps to Reproduce

1. Copy this custom control [code](https://github.com/edsulaiman/Xamarin-Form-UiKit/blob/main/src/Button/Button.xaml.cs)
2. Use the custom control
````
<local:Button 
    Type="custom"
    Background="#f5f5f5">
</local:Button>
````
3. Build the xamarin form project
4. Trigger Hot Reload by saving the xaml

### Basic Information

- Version with issue: Xamarin.Forms 4.8.0.1451
- Platform Target Frameworks: 
  - Android: 9.0  

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.2
VisualStudio.16.Release/16.8.2+30717.126
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Community

Azure App Service Tools v3.0.0   16.8.553.28003
Azure App Service Tools v3.0.0

C# Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.8.0-5.20567.16+53c5d7d3cf13d88978744a32a27c5f8350a8400a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.255 (d16-8@d002176)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.4.1.3 (e30c41de3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

> VS bug [#1270217](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1270217)

**Comment by rachelkang** [comment]
Hi, @edsulaiman - thank you for submitting this issue. Unfortunately, I don't have access to the custom control code you shared. If you can share access or create a small project reproducing the same issue, that would be extremely helpful!
I am also curious about the error message you mention - if you could copy/paste the full error message, that would be awesome!

**Comment by edsulaiman** [comment]
Hi, @rachelkang I have created the repository [link](https://github.com/edsulaiman/HotReloadBug).
The error message is 
````
20:13 to 20:-1 - Position 20:13. Multiple properties with name 'HotReloadBug.HotReloadBugCustomControll.BackgroundColor' found.
````

steps to bring up the error [link](https://github.com/edsulaiman/HotReloadBug/blob/master/HotReloadBug/MainPage.xaml)

**Comment by BretJohnson** [comment]
@edsulaiman - are you still seeing issues here? if so, can you resupply access to the https://github.com/edsulaiman/Xamarin-Form-UiKit/blob/main/src/Button/Button.xaml.cs repo (or maybe attach the repo project as a zip to this issue). Sorry for the long delay on the follow up. Thanks.

**Comment by edsulaiman** [comment]
@BretJohnson I'm not sure if this issue still exists or not, I'm not using xamarin form or visual studio anymore. I thought this issue might just happen to me, because no one else had the same problem as me as long as this issue was reported till now. so i'd like to close this issue
