### ISSUE TITLE
[Bug] Bottom row in grid is hidden behind Shell bottom tab bar on iOS in registered route pages

### ISSUE THREAD

**Issue by RGBPlaza** [xamarin/Xamarin.Forms#13206]
### Description
On iOS, sometimes out bottom buttons which have a height of 48px disappear behind the bottom tab bar (part of Shell) and we have to use OnPlatform to add an extra 48px padding at the bottom of the page just to mitigate this effect. Android is completely fine.
I have noticed also that this only seems to affect pages which are navigated to using Shell.GoToAsync() on a programatically registered route. Our bottom button on our root page which is defined in Shell Xaml consistently displays correctly.

### Steps to Reproduce

1.  Create two pages in a shell app with bottom tabs, placing one in shell Xaml and programatically register the route of the other.
2.  In each page, place a grid with two row definitions: *, 48
3.  In each page, create a button with Grid.Row=1
4. Navigate from the fixed page to the registered route page

### Expected Behavior
Button displays at the bottom of the page but above the bottom tab bar.

### Actual Behavior
This only happens on the fixed page.
On the registered route page, the button is hidden behind the bottom tab bar.

### Basic Information

- Version with issue: Latest
- Last known good version: Not Known
- Platform Target Frameworks: 
  - iOS: Latest

### Workaround
As it seems the height of the bottom tab bar is 48px on iOS, hence the complete concealment of the buttons, using OnPlatform to add an extra 48px padding at the bottom of these pages can effectively solve the issue - but it's not very fun and will lead to potential confusion and maintenance issues etc.

**Comment by rachelkang** [comment]
Hi, @RGBPlaza - thanks for submitting this issue. Would you be able to share some your project or a sample project reproducing the issue? Or if you could share bits of the relevant code, that would be really helpful too. I tried following your steps but wasn't able to reproduce the error myself.

**Comment by RGBPlaza** [comment]
Wow okay so after using the Safe Area Insets thing it's okay!! :)

This one:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout
