### ISSUE TITLE
[Bug] [iOS] CollectionView does not bind to items if `IsVisible=False`

### ISSUE THREAD

**Issue by dmariogatto** [xamarin/Xamarin.Forms#13203]
### Description

Bind CollectionView to an item source while not visible (i.e. `IsVisible="False"`), then change visibility to true, no items in the list.

### Steps to Reproduce

```csharp
using System.Collections.Generic;
using Xamarin.Forms;

namespace CollectionViewBrokenAgain
{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = this;
        }

        public List<int> Items { get; } = new List<int>() { 1, 2, 3, 4, 5, 6, 7, 8, 9 };

        protected override void OnAppearing()
        {
            base.OnAppearing();
           // CollectionView is bound to Items, but will be empty if visibility was initially set to false
            ItemsView.IsVisible = true;
        }
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="CollectionViewBrokenAgain.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <CollectionView
        x:Name="ItemsView"
        IsVisible="False"
        ItemsSource="{Binding Items}">
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Frame>
                    <Label Text="{Binding}" />
                </Frame>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>

</ContentPage>
```

### Expected Behavior

Should should items after visibilty is changed to `true`. 

### Actual Behavior

No items displayed.

### Basic Information

- Version with issue: 4.8.0.1821
- Last known good version: 4.8.0.1687
- Platform Target Frameworks: 
  - iOS:  14.2

### Workaround

Can wrap CollectionView in a ContentView, and toggle the visibility on that instead.

### Repro link
Repro: [Issue13203.zip](https://github.com/xamarin/Xamarin.Forms/files/5726025/Issue13203.zip)

**Comment by sawankumarbundelkhandi** [comment]
@rachelkang @dmariogatto same is happening with CarouselView.

**Comment by Tommigun1980** [comment]
This is the same issue as https://github.com/xamarin/Xamarin.Forms/issues/13126, and also bugs 1 and 2 in https://github.com/xamarin/Xamarin.Forms/issues/13231.

**Comment by Tommigun1980** [comment]
This is the same issue as https://github.com/xamarin/Xamarin.Forms/issues/13126, and also bugs 1 and 2 in the repro project at https://github.com/xamarin/Xamarin.Forms/issues/13231.

The only workaround I found was to downgrade to XF 5.0.0-pre4 as this regression was introduced in 5.0.0-pre5 (and is still there in pre6).

**Comment by AlleSchonWeg** [comment]
Hi,
i think i run into a similar issue with version 4.8.0.1560. Wrapping the collectionView inside a ContentView doesn't work for my. I have bind the IsVisible property to my model:
`IsVisible="{Binding Show}"`
After loading the items i set Show=true. On android it works as expected. But on ios i the CollectionView is empty. But i found a workaround. I created a Task without await (because i want no await) but with a little delay:
```
protected override async void OnAppearing() {
  base.OnAppearing();
  //Other code
  _ = Task.Run(async() => {
	 await Task.Delay(100);
	 var vm = (Model)BindingContext;
	 vm.Show= true;
 });
}
```

**Comment by Tommigun1980** [comment]
> Hi,
> i think i run into a similar issue with version 4.8.0.1560. Wrapping the collectionView inside a ContentView doesn't work for my. I have bind the IsVisible property to my model:
> `IsVisible="{Binding Show}"`
> After loading the items i set Show=true. On android it works as expected. But on ios i the CollectionView is empty. But i found a workaround. I created a Task without await (because i want no await) but with a little delay:
> 
> ```
> protected override async void OnAppearing() {
>   base.OnAppearing();
>   //Other code
>   _ = Task.Run(async() => {
> 	 await Task.Delay(100);
> 	 var vm = (Model)BindingContext;
> 	 vm.Show= true;
>  });
> }
> ```

Hi @AlleSchonWeg, the problem with those delays is that its length is dependent on the amount of content and the speed of the device. So what works on one device or collection won’t work on another, so I’d discourage from using one.

**Comment by AlleSchonWeg** [comment]
> > Hi,
> > i think i run into a similar issue with version 4.8.0.1560. Wrapping the collectionView inside a ContentView doesn't work for my. I have bind the IsVisible property to my model:
> > `IsVisible="{Binding Show}"`
> > After loading the items i set Show=true. On android it works as expected. But on ios i the CollectionView is empty. But i found a workaround. I created a Task without await (because i want no await) but with a little delay:
> > ```
> > protected override async void OnAppearing() {
> >   base.OnAppearing();
> >   //Other code
> >   _ = Task.Run(async() => {
> > 	 await Task.Delay(100);
> > 	 var vm = (Model)BindingContext;
> > 	 vm.Show= true;
> >  });
> > }
> > ```
> 
> Hi @AlleSchonWeg, the problem with those delays is that its length is dependent on the amount of content and the speed of the device. So what works on one device or collection won’t work on another, so I’d discourage from using one.

Sure,
this is not a perfect workaround. I only want to share it and perhaps it gives others a hint to workaround their issues. But XF has so many bugs, we have to deal with workarounds every day. Especially CollectionView.

**Comment by mahesh139** [comment]
> This is the same issue as #13126, and also bugs 1 and 2 in the repro project at #13231.
> 
> The only workaround I found was to downgrade to XF 5.0.0-pre4 as this regression was introduced in 5.0.0-pre5 (and is still there in pre6), in case someone is using XF 5.

same issue on stable release XF 5 (5.0.0.1874)

**Comment by Tommigun1980** [comment]
This is a fatal regression, so is there any chance this could be fixed soon?

Repros at https://github.com/xamarin/Xamarin.Forms/issues/13126#issuecomment-751310883 and https://github.com/xamarin/Xamarin.Forms/issues/13231, where the latter exposes more regressions related to this.

Thanks!

**Comment by Tommigun1980** [comment]
Hi @rmarinho. I tested with the latest nightly build of XF and this issue still happens. Is the fix not in the nightly build yet?

Thank you.

**Comment by dmariogatto** [comment]
@Tommigun1980 I think it was only just [merged ](https://github.com/xamarin/Xamarin.Forms/commit/d05bf4ac0383572526992e03bb4aafef4a24719b) into 5.0. So probably not in the nightly yet.

**Comment by Tommigun1980** [comment]
@dmariogatto It was committed four days ago to the 5.0.0 branch. I tested with the latest nightly again and it's not fixed. I have provided two different repro cases for this issue. @rmarinho Is the fix supposed to be in the latest nightly?

Thank you.

**Comment by Tommigun1980** [comment]
@dmariogatto It was committed four days ago to the 5.0.0 branch (https://github.com/xamarin/Xamarin.Forms/commit/c419953e86aa4de9a680439564abe69d60331ab5). I tested with the latest nightly again and it's not fixed. I have provided two different repro cases for this issue.

@rmarinho @hartez Is the fix supposed to be in the latest nightly?

Thank you.

**Comment by dmariogatto** [comment]
@Tommigun1980 @rmarinho @hartez  @rachelkang 

Don't think this one is completely fixed for all scenarios, see #13551.

**Comment by developer9969** [comment]
Hi tested this against 5.0.0.1931 and this is still an issue as collectionView does not show the first time round.

**Comment by rd09** [comment]
I am experiencing the same issue on version 4.8.0.1821.  I have a CollectionView that has IsVisible set to false initially and the bound ItemSource is set.  Then when IsVisible is set to true through binding nothing is displayed.  My work around is to switch the CollectionView back to a ListView.

**Comment by amritpa9** [comment]
> I am experiencing the same issue on version 4.8.0.1821. I have a CollectionView that has IsVisible set to false initially and the bound ItemSource is set. Then when IsVisible is set to true through binding nothing is displayed. My work around is to switch the CollectionView back to a ListView.

i am also facing same issue, i also tried Listview but this issue still appearing on IOS , have you found any solution ?

**Comment by Sasha111ua** [comment]
`protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs changedProperty)
        {
            base.OnElementPropertyChanged(sender, changedProperty);
            if (changedProperty.PropertyName == "IsVisible")
            {
                if (Element.IsVisible)
                {
                    Element.Layout(NativeView.Frame.ToRectangle());
                }
            }
        }`

this helped me

**Comment by zleao** [comment]
I confirm that this is still happening on XF 5.0.0.2545 :(
