### ISSUE TITLE
[Bug] No field with the name mListener is found in Animation class

### ISSUE THREAD

**Issue by bcaceiro** [xamarin/Xamarin.Forms#13204]
### Description
When running my app, with collectionview, I've started to notice these errors printed in the console.

```
[gasdelivery.ap] Accessing hidden field Landroid/view/animation/Animation;->mListener:Landroid/view/animation/Animation$AnimationListener; (greylist-max-p, reflection, denied)
[FragmentManager] No field with the name mListener is found in Animation class
[FragmentManager] java.lang.NoSuchFieldException: No field mListener in class Landroid/view/animation/Animation; (declaration of 'android.view.animation.Animation' appears in /system/framework/framework.jar!classes3.dex)
[FragmentManager] 	at java.lang.Class.getDeclaredField(Native Method)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.getAnimationListener(FragmentManager.java:1301)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.animateRemoveFragment(FragmentManager.java:1638)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1548)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
[FragmentManager] 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
[FragmentManager] 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
[FragmentManager] 	at android.os.Handler.handleCallback(Handler.java:883)
[FragmentManager] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[FragmentManager] 	at android.os.Looper.loop(Looper.java:237)
[FragmentManager] 	at android.app.ActivityThread.main(ActivityThread.java:8167)
[FragmentManager] 	at java.lang.reflect.Method.invoke(Native Method)
[FragmentManager] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
[FragmentManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```
### Steps to Reproduce

1. Declare Collectionview, navigate forth and back
2. Check console log
3. 
### Expected Behavior
No errors printed
### Actual Behavior
Errors printed
### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android: v10.o
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Essentials, Xamarin.Forms, PancakeView, Sharpnado.Shadows
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by AmrAlSayed0** [comment]
A quick search revealed this https://issuetracker.google.com/issues/139349998 https://stackoverflow.com/a/59435170/2427681 I don't if that is the one.

**Comment by bcaceiro** [comment]
I haven't migrated to AndroidX

**Comment by hartez** [comment]
@bcaceiro I'm trying to repro this issue, but so far I've had no luck. I'm attaching my repro - when I run it, I don't see the error message you mentioned. Is there a detail I missing?

[_13204 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5766739/_13204.Repro.zip)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
