### ISSUE TITLE
LinearGradientBrush causes app failure: Unable to activate Windows Store app

### ISSUE THREAD

**Issue by snowman745** [xamarin/Xamarin.Forms#13210]
Repro:
1) Add a LinearGradientBrush to a Grid.Background

Result:

Unable to activate Windows Store app 'd65fdd27-ebcb-48cb-aa27-5cb70fa8a898_0mmnncn3gtxzg!App'. The activation request failed with error 'Operation not supported. Unknown error: 0x80040904'.

Example code:

```
  <LinearGradientBrush StartPoint="0.5,0"
                             EndPoint="0.5,1">
                        <GradientStop Color="#D3251E"
                          Offset="0.0"/>
                        <GradientStop Color="#A32827"
                          Offset="1.0"/>
                    </LinearGradientBrush>

```

Version:
Xamarin.Forms v4.8.0.1821

Repro'd on Android and UWP

**Comment by rachelkang** [comment]
Hi, @snowman745 - thanks for submitting this issue. Would you mind elaborating on the nature of the error message? When is this error thrown? Can you share the full error message / stack trace?

Also, if you can share your project, a sample project reproducing the issue, or any relevant code, that would be immensely helpful :)

**Comment by snowman745** [comment]
[brush.zip](https://github.com/xamarin/Xamarin.Forms/files/5731702/brush.zip)

**Comment by snowman745** [comment]
See attached file in reply above for sample project.

All I did was:

1) Create a new Xamarin.Forms project 
2) Add the code to MainPage.xaml:

    <Grid.Background>
            <LinearGradientBrush StartPoint="0.5,0"
                             EndPoint="0.5,1">
                <GradientStop Color="#D3251E"
                          Offset="0.0"/>
                <GradientStop Color="#A32827"
                          Offset="1.0"/>
            </LinearGradientBrush>
        </Grid.Background>


3) Run the project (UWP)

After you run it, it immediately throws the error.

Please see the attached screenshot. 

This is the only stack I could get:

>	LinearGradientBrush.UWP.exe!LinearGradientBrush.UWP.App.InitializeComponent.AnonymousMethod__5_0(object sender = {LinearGradientBrush.UWP.App}, Windows.UI.Xaml.UnhandledExceptionEventArgs e = {Windows.UI.Xaml.UnhandledExceptionEventArgs}) Line 53	C#



<img width="1794" alt="screenshot4" src="https://user-images.githubusercontent.com/19957937/102926833-93085e80-444a-11eb-8b79-da654d978cc3.png">

**Comment by snowman745** [comment]
Any update?

**Comment by rachelkang** [comment]
@snowman745 hmm are you still on XF 4.8? If so, you need to add the appropriate experimental flag for brushes (more on experimental flags [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags)). If you haven't already, I recommend upgrading to XF 5.0 where brushes are no longer experimental and you won't have to worry about this stipulation!

Let me know if that helps - I wasn't able to reproduce the exact error you're seeing, although that one doesn't seem as directly related to brushes or XF. If you see that error again, I recommend cleaning/rebuilding your projects, deleting the bin/obj folders, and restarting VS as a starting point!

**Comment by jsuarezruiz** [comment]
Trying the attached example, I get this exception:
<img width="792" alt="Captura de pantalla 2021-01-13 a las 12 16 52" src="https://user-images.githubusercontent.com/6755973/104445666-ac0fb580-5599-11eb-96e2-3a2e32a934c5.png">
After include:
`Xamarin.Forms.Forms.SetFlags("Brush_Experimental");`

The sample is working as expected. Could you try the same adding the previous line?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
