### ISSUE TITLE
[Bug] Flyout item navigation behaves different on previous navigating

### ISSUE THREAD

**Issue by wooooooood** [xamarin/Xamarin.Forms#13219]
### Description
When you browse the same page when clicking flyout menu, navigating behavior varies depending on how user previously navigated to that page.
I think it's kind of weird that flyout navigation acts different in some scenarios.
Looks similar with  #13208 issue?

### Steps to Reproduce
With attached repro,

Does not happen when
1. Click "Browse" via Flyout
2. Click "Browse" via Flyout again while you're still in "Browse" page
3. Log message "Value is null" is not printed

But happens when
1. Click on the "Move via Shell Navigation" button at "About"
2. Click "Browse" via Flyout again while you're still in "Browse" page
3. Log message "Value is null" is printed which can cause `TargetInvokeException` without null check

### Expected Behavior
Flyout item navigating behavior should be same all the time
### Actual Behavior
Flyout item navigating behavior differentiates depending on previous navigating
### Basic Information

- Version with issue: XF5 pre5
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10

### Environment
```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084
```

</details>

### Reproduction Link
[Check this out~](https://drive.google.com/file/d/1_NhKd5nN5agC1kEzxANLC3Fhosx4u2gN/view?usp=sharing)

### Workaround
Adding value null check

**Comment by jfversluis** [comment]
@pictos did you want to have another look at this one? Let me know if you need any more info

**Comment by pictos** [comment]
@jfversluis Sure thing. I can review it next week. I let you know if I need more info
