### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AlbertTester** [xamarin/Xamarin.Forms#13211]
### Description
**System.NotSupportedException:** 'Unable to activate instance of type Xamarin.Forms.Platform.Android.BorderDrawable from native handle 0xff8a4eec (key_handle 0x177c75a).'
### Steps to Reproduce

1. Use  formsMessenger.Send(new MainPageChangeRequestMessage { Payload = new MainStage(this.MainStageViewModel), PreventNavStackPush = false });
2.  App crashes

2. 
3. 

### Expected Behavior
Paint the page

### Actual Behavior
Android Crash
### Basic Information
12-21 15:59:28.488 I/mono-stdout( 1467): ### Connected ###Info
12-21 15:59:30.067 W/StaticLayout( 1467): maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-21 15:59:30.078 I/chatty  ( 1467): uid=10287(com.golighthouse.filtr) identical 4 lines
12-21 15:59:30.079 W/StaticLayout( 1467): maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-21 15:59:30.509 D/Mono    ( 1467): Requesting loading reference 7 (of 8) of Mono.Android.dll
12-21 15:59:30.509 D/Mono    ( 1467): Loading reference 7 of Mono.Android.dll asmctx DEFAULT, looking for System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
12-21 15:59:30.510 D/Mono    ( 1467): Assembly Ref addref Mono.Android[0xdab417c0] -> System.Runtime.Serialization[0xc1128380]: 4
**System.NotSupportedException:** 'Unable to activate instance of type Xamarin.Forms.Platform.Android.BorderDrawable from native handle 0xff8a4eec (key_handle 0x177c75a).'

- Version with issue:  Android 8.1.0
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- 
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @AlbertTester - can you check that you are unsubscribing all the messages that you've subscribed to? If that doesn't work, would you please share your project or a sample project reproducing the same issue? Would love to get a clearer idea of how/where the messages are being sent and subscribed in your project. Thanks :)

**Comment by AlbertTester** [comment]
The issue is why I am getting:

12-21 17:04:04.185 I/mono-stdout( 9446): ### Connected ###Info
12-21 17:04:05.124 W/StaticLayout( 9446): maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-21 17:04:05.135 I/chatty  ( 9446): uid=10287(com.golighthouse.filtr) identical 4 lines
12-21 17:04:05.136 W/StaticLayout( 9446): maxLineHeight should not be -1.  maxLines:1 lineCount:1
12-21 17:04:05.630 D/Mono    ( 9446): Requesting loading reference 7 (of 8) of Mono.Android.dll
12-21 17:04:05.630 D/Mono    ( 9446): Loading reference 7 of Mono.Android.dll asmctx DEFAULT, looking for System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
12-21 17:04:05.635 D/Mono    ( 9446): Assembly Ref addref Mono.Android[0xdab41640] -> System.Runtime.Serialization[0xc0edd1a0]: 4
**System.NotSupportedException:** 'Unable to activate instance of type Xamarin.Forms.Platform.Android.BorderDrawable from native handle 0xff8a8c6c (key_handle 0xf20f7cd).'

Xamarin code which works on calls from other screens:
           this.formsMessenger.Send(new MainPageChangeRequestMessage { Payload = new MainStage(this.MainStageViewModel), PreventNavStackPush = false });
calling:
  /// <summary>
        /// The main stage view model.
        /// </summary>
        private IMainStageViewModel MainStageViewModel =>
            this.mainStageViewModel ??= new MainStageViewModel
            {
                AppState = AppStates.MainStage,
                ViewTitle = MainMenuViewModel.HomeMenuItemTitle
            };

**Comment by Redth** [comment]
Can you please attach a sample project which reproduces this issue?

**Comment by ericdc66** [comment]
I'm not sure if this helps, but I was getting the same issue. In my situation, I was using an await for a method with web api service calls and UI updates within a property changed handler. I wrapped my await call in a call to Application.Current.Dispatcher.BeginInvokeOnMainThread() and the problem went away. It seemed like it was related to trying to update a UI element on a non-UI thread (as in WPF or WinForms), but the error message above doesn't really make that clear.
