### ISSUE TITLE
[Bug] Embedded font not showing correctly at Xamarin.Forms.Label and RadioButton

### ISSUE THREAD

**Issue by shinnthant-lab** [xamarin/Xamarin.Forms#13214]
### Description
Embedded font not showing correctly at Xamarin.Forms.Label and RadioButton

Myanmar Unicode Font (MMRTEXT.TTF) Embed not showing correctly at Xamarin.Forms.Label Control and RadioButton Control, but showing correctly at Xamarin.Forms.Entry Control.
I'm Using XF5 Pre5.
Please see the screenshot for more detail. Red Highlighted are wrong but the underlying Text Boxes are showing correct.
### Steps to Reproduce

1. Embed MMRTEXT.TTF as described at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts
2. Add a label to project with this Myanmar Text **အင်္ဂလိပ်ကိုယ်ရေးရာဇဝင် အတွက် အင်္ဂလိပ်အမည်...**

![image](https://user-images.githubusercontent.com/54578974/102885429-bc90ac80-4481-11eb-84b9-4c8e585a5c6a.png)

### Expected Behavior
the font should be showing correctly as showing in Entry. **Edit: I'm tested on Android Device**
### Actual Behavior
the font not showing correctly.
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @shinnthant-lab - thanks for submitting this issue. Would you be able to share your project or a sample project reproducing the issue, so we can take a closer look?

In the meantime, you may also find the blog post helpful: https://devblogs.microsoft.com/xamarin/embedded-fonts-xamarin-forms/

**Comment by shinnthant-lab** [comment]
Hello, @rachelkang thanks for the information, here is my sample solution zip for your reference.
You can see the fonts at App.xaml, embedded code at App.xaml.cs.
Fonts are in Fonts folder.

[MyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/5733447/MyApp.zip)

the expected outcome text is as below image...
![image](https://user-images.githubusercontent.com/54578974/102963127-c2849d00-4516-11eb-9690-246ac37d8e48.png)

**Comment by rmarinho** [comment]
Hi @shinnthant-lab  so i was trying to identify the issue, i changed a little bit the sample to not use the font so i can compare. but they seem similar, but wanted to make sure they are diff.

So the 2nd label and 2nd entry don't have a font, do they look correct? 
If i compare the 2 underline entry seems very similar, but they are diff right? one with the font , other without .

```
  <Label x:Name="lblMyanmarText" Text="{x:Static resources:AppResource.lblMyanmarText}" />
                        <Label x:Name="lblMyanmarText1" Text="{x:Static resources:AppResource.lblMyanmarText}" FontFamily="MMText"/>
                        <Entry x:Name="txtMyanmarText" Text="{x:Static resources:AppResource.lblMyanmarText}" />
                        <Entry x:Name="txtMyanmarText1" Text="{x:Static resources:AppResource.lblMyanmarText}" FontFamily="MMText"/>
```

![image](https://user-images.githubusercontent.com/1235097/106274803-be8e1e00-622c-11eb-8ced-315161cfbba7.png)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
