### ISSUE TITLE
[QUESTION] Background Notifications

### ISSUE THREAD

**Issue by PrimoDev23** [xamarin/Xamarin.Forms#13227]
Hey guys,
I am currently developing a calendar-like app that shall notify the user about meetings etc.

Using this doc I could make the local notifications work
https://docs.microsoft.com/de-de/xamarin/xamarin-forms/app-fundamentals/local-notifications

But as soon as I am removing the app from recents in Android, the notifications aren't delivered anymore (which is normal, i know)

After searching for about an hour, I couldn't find any way to deliver notifications after the app is killed.
I can't rely on Firebase in this case, because I want to keep that app totally offline and usable without any internet connection (Today everyone has internet but for privacy reasons this is a no-go for me)

I would be happy if you could help me solving this little problem even if it's not really an issue of xamarin forms, but more like a lack in documentations.

Thanks in advance.

Sincerely
PrimoDev

**Comment by sarthak1995-26** [comment]
You might have to do this on native side for each platform as you have to create a background service which will run even after app killed these are called background tasks

For Android : You can try Work Manager 
Reference : https://devblogs.microsoft.com/xamarin/getting-started-workmanager/

For iOS : https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/ios-backgrounding-with-tasks

Or best among all check Shiny library 
https://allancritchie.net/posts/shinyjobs

**Comment by PrimoDev23** [comment]
> You might have to do this on native side for each platform as you have to create a background service which will run even after app killed these are called background tasks
> 
> For Android : You can try Work Manager
> Reference : https://devblogs.microsoft.com/xamarin/getting-started-workmanager/
> 
> For iOS : Read about Background fetch technique iOS 7+
> 
> Or best among all check Shiny library
> https://allancritchie.net/posts/shinyjobs

Well thanks, tried and works for android
Can't try for ios because of the lack of a device but that was definitely the answer I searched. Gonna close this.
