### ISSUE TITLE
[Bug] Button.IsEnabled = False doesn't change background color on WPF

### ISSUE THREAD

**Issue by mrvancor** [xamarin/Xamarin.Forms#13226]
### Description

Setting `IsEnabled` to false on a `Button` doesn't change background color - the button is always rendered white color.

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: -
- IDE: Visual Studio 2019 16.8.3
- Platform Target Frameworks: 
  - WPF:  4.8.0.1687
- Affected Devices: Laptop with Windows 10 x64

**Comment by mrvancor** [comment]
In App.xaml i added:

```<Style TargetType="Button">
            <Style.Triggers>
                <Trigger TargetType="Button"
                         Property="IsEnabled"
                         Value="False">
                    <Setter Property="BackgroundColor" Value="{OnPlatform Android='#7A7A7A', iOS='#7A7A7A', WPF='#7A7A7A'}"/>
                    <Setter Property="BorderColor" Value="{OnPlatform Android='Default', iOS='Default', WPF='Transparent'}" />
                    <Setter Property="TextColor" Value="{OnPlatform Android='White', iOS='White', WPF='White'}" />
                </Trigger>
             </Style.Triggers>
</Style>```

But after I launched the application, I saw that the background color of the disabled buttons is white. But when I go to another page and then back, the color changes.

**Comment by mrvancor** [comment]
In App.xaml i added:

```
<Style TargetType="Button">
          <Style.Triggers>
              <Trigger TargetType="Button"
                       Property="IsEnabled"
                       Value="False">
                  <Setter Property="BackgroundColor" Value="#7A7A7A"/>
              </Trigger>
           </Style.Triggers>
</Style>
```

But after I launched the application, I saw that the background color of the disabled buttons is white. But when I go to another page and then back, the color changes.

**Comment by neoDD69** [comment]
I suppose that this issue dosenìt came from Xamarin, but is a bug in WPF.
I've just haved this issue in a XAML .Net 6.0 without using Xamarin.
![image](https://user-images.githubusercontent.com/2903187/196177971-e1a236cd-09f9-45b6-8d08-4c467598baae.png)

**Comment by neoDD69** [comment]
the only way that I've found was to redefine the Template of all Button:
![image](https://user-images.githubusercontent.com/2903187/196230235-1129493d-ef7e-439c-9328-60b1f0851c8f.png)

thanks to [WPF Disabled button's background](https://askcodes.net/coding/wpf-disabled-button-s-background)

IMHO is the base Template of the Button that is wrong made. If you see it ...  you see they use a Border to apply the back color, blocking every way to set it when IsEnabled = False ... call Microsoft ;)
