### ISSUE TITLE
App is stuck at splashscreen and crashing with SIGSEGV, code 1 after user has done an update from playstore.

### ISSUE THREAD

**Issue by arjun159** [xamarin/Xamarin.Forms#13223]
After the user had updated app in playstore to a later version in playstore, xamarin forms had a crash of SIGSEV in splash screen. The issue has been happening only in production 

Xamarin forms version -- 4.7.0.1351
Xamarin Android SDK version -- 11.1.0.17

Most of the devices affected are Huawei, Samsung with different versions of android.

The issue has been happening in the release mode and only after an update installed.

**Comment by balld** [comment]
Working with @arjun159 so adding some more information on this.

As mentioned, this defect only affects some devices, only when installing via Play Store (not adb), and only at point when an existing install is updated to a new version.

We have seen examples in Android versions 6 through 10.
Uninstalling and re-installing the app resolves the crash and app becomes usable. Deleting the app data also resolves the crash.
Our app uses SharedPreferences and sqlite to store data. There are no changes in data storage between versions of the app we're updating from and to..

We have a splashscreen activity which executes normally and launches our main app activty.
The main app activity progresses as normal until it is loading the Xamarin.Forms application:
`LoadApplication(new App());`

The system log on crash contains this info and back trace. Example here from Galaxy A5 2016 running Android 6.0.1 (application ID removed):
```
F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11719 (.xxx.xxx)
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F DEBUG   : Build fingerprint: 'samsung/a5xeltexx/a5xelte:6.0.1/MMB29K/A510FXXS3BPI8:user/release-keys'
F DEBUG   : Revision: '4'
F DEBUG   : ABI: 'arm'
F DEBUG   : pid: 11719, tid: 11719, name: .xxx.xxx  >>> xx.xxx.xxx <<<
F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
F DEBUG   :     r0 00000000  r1 00000000  r2 00000000  r3 00000000
F DEBUG   :     r4 00200025  r5 f4a56cc0  r6 00000000  r7 00000000
F DEBUG   :     r8 dce76370  r9 f6f9eec0  sl ff5b0230  fp ff5afe60
F DEBUG   :     ip f6f9a7d4  sp ff5afd40  lr f6f63435  pc f6f3d0f4  cpsr 600b0030
F DEBUG   :
F DEBUG   : backtrace:
F DEBUG   :     #00 pc 000190f4  /system/lib/libc.so (strlen+71)
F DEBUG   :     #01 pc 0003f431  /system/lib/libc.so (strdup+4)
F DEBUG   :     #02 pc 00008d53  /data/app/xx.xxx.xxx-1/lib/arm/libmonodroid.so (_ZN7xamarin7android8internal16MonodroidRuntime35get_java_class_name_for_TypeManagerEP7_jclass+50)
F DEBUG   :     #03 pc 00019b20  <unknown>
```
Trace starts in unknown code, but progresses to [get_java_class_name_for_TypeManager](https://github.com/xamarin/xamarin-android/blob/master/src/monodroid/jni/monodroid-glue.cc#L2023). Seems we end up with null name for a Java class and call strdup on it.

This crash happens while loading our Forms app, but realise this ticket may belong in the xamarin-android project.

**Comment by balld** [comment]
Apologies. We have resolved this issue. It turned out to be caused by a defect in application code that could trigger infinite recursion in certain update scenarios.

In case any Xamarin app developers should find their way here searching "SIGSEGV" and "get_java_class_name_for_TypeManager" I recommend checking for this possibility. Due to the nature of our defect the recursion did not emerge in dev/test and was not evident from available logging when used in release.

**Comment by arjun159** [comment]
The issue has been resolved. Apologies as @balld  said the issue is at the application end. So closing the issue.
