### ISSUE TITLE
[Bug] Xamarin.Forms.Platform.WPF: ToolbarItem - Text property is always shown

### ISSUE THREAD

**Issue by UweReisewitz** [xamarin/Xamarin.Forms#13235]
### Description
The Text property of the ToolbarItem is always shown. On Andriod it is hidden when an image is present

### Steps to Reproduce
I have created an example that exhibits the problem

Downlod project: https://github.com/UweReisewitz/TestIconImageSource
Compare the Android and the WPF output

### Expected Behavior
The Text should be hidden when an image is present like on Android

### Actual Behavior
The Text is always shown and I have found no way to hide it except setting it to string.Empty which requires a platform-sepcific setting just for this

### Basic Information

Version with issue: 4.8.0.1821
Last known good version: unknown
Platform Target Frameworks:
iOS: Doesn't work because of a problem with the SkiaSharp Libraries
Android: Android 10
UWP: N/A
Android Support Library / AndroidX Version:
NuGet Packages:
Affected Devices:

### Environment
Visual Studio 2019 16.8.3

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by UweReisewitz** [comment]
Today I have updated the sample application to Xamarin.Forms 5.0.0.1874.
The problem is still there .

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
