### ISSUE TITLE
[Bug] Xamarin.Forms.Platform.WPF: Image Control - BackgroundColor Property is ignored

### ISSUE THREAD

**Issue by UweReisewitz** [xamarin/Xamarin.Forms#13233]
### Description
The BackgroundColor Property og the image control is ignored in WPF

### Steps to Reproduce
I have created an example that exhibits the problem
1. Downlod project: https://github.com/UweReisewitz/TestIconImageSource
2. Compare the Anrdoid and the WPF output

### Expected Behavior
Image control should honor the background color 

### Actual Behavior
Background color is ignored; it's always white

### Basic Information

- Version with issue: 4.8.0.1821
- Last known good version: unknown
- Platform Target Frameworks: 
  - iOS:  Doesn't work because of a problem with the SkiaSharp Libraries
  - Android: Android 10 
  - UWP:  N/A
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment
Visual Studio 2019 16.8.3

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by UweReisewitz** [comment]
Today I have updated the sample application to Xamarin.Forms 5.0.0.1874.
The problem is still there.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
