### ISSUE TITLE
[Report Progress Of a Function] 

### ISSUE THREAD

**Issue by Barshan-Mandal** [xamarin/Xamarin.Forms#13248]
I want to create a wrapper that will bind a function to a progress. For example, I would call it like

ProgressBar.ReportProgressFor(MyDefinedFunction())
I want to make a function that will take an user defined function as its parameter and execute it and return the percentage of the user defined function executed in a method property

The code example should be like

var x = ProgressBar.ReportProgressFor(MyDefinedFunction());
and to get the executed percentage we will use x.RemainingPercentage and x.ExecutedPercentage
Please implement it

**Comment by Barshan-Mandal** [comment]
please take it into consideration

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
