### ISSUE TITLE
[Bug] In Forms UWP, back navigation with content view in custom title view not working correct with custom renderer.

### ISSUE THREAD

**Issue by ragulsv** [xamarin/Xamarin.Forms#13241]
### Description
 
When using custom renderer for the content view. It throws "Element is already the child of another element" while converting the content of the content view to the content presenter using the content control.

### Steps to Reproduce

1.  Run the attached sample.
2. Navigate to the sub page and navigate back. 
3. Content view gets hidden and page not navigated back properly.
4. Exception gets thrown in the on element changed method of custom renderer.

### Expected Behavior

Page should be navigated back properly with the content view as like the second time.

### Actual Behavior

In first time page is not navigated back properly and also content view gets disappear.

### Basic Information

- Version with issue: Issue reproduced commonly in all versions.

### Screenshots

- Actual Output
      
![image](https://user-images.githubusercontent.com/28722511/103226009-2e209d00-4951-11eb-9e6c-d2e8c7636196.png)

- Expected Output

![image](https://user-images.githubusercontent.com/28722511/103226090-53ada680-4951-11eb-9964-7baaf6c656c1.png)

### Workaround

Please check the below sample.
[CustomControl.zip](https://github.com/xamarin/Xamarin.Forms/files/5747901/CustomControl.zip)

**Comment by hartez** [comment]
It looks like you have an extra ContentControl in your custom renderer. I think if you remove that it will work.

Try changing

```
if (Element.Content != null)
{
    var renderer = Element.Content.GetOrCreateRenderer();
    var contentControl = new ContentControl();
    contentControl.Content = renderer.ContainerElement;
    contentControl.DataContext = Element.BindingContext;
    this.customView.Content = contentControl;
}
```

to 

```
if (Element.Content != null)
{
	var renderer = Element.Content.GetOrCreateRenderer();
	this.customView.DataContext = Element.BindingContext;
	this.customView.Content = renderer.ContainerElement;
}
```

**Comment by ragulsv** [comment]
But the same thing gets worked correctly in the below xamarin forms version 5.0 preview.
