### ISSUE TITLE
[Bug] VoiceOver/TalkBack combined with Largest Accessibility Font Size changes swipe navigation

### ISSUE THREAD

**Issue by jhunterdfly** [xamarin/Xamarin.Forms#13257]
### Description
When using VoiceOver/Talkback on a list page (in a Prism Tabbed Page with Navigation Page) and normal/default font sizes, I get the left/right swipe navigation to navigation correctly between the items on the page.  It will scroll the list as expected, navigating from list item to list item and scrolling up the page as needed.

However, when the VoiceOver/Talkback is combined with using the maximum font size in the accessibility font size settings, the navigation changes inexplicably.  If an item on the pages (either a label with a lot of text, or a list item ) is large enough to fill the page, then the left/right swipe navigation will navigate to the tab icons rather than the next list item in line.  Or if the user is navigating backward (via left swipe) they are brought to the TitleView rather than previous items in the list.

The 2-finger vertical scrolling does function, however there is no indication to the user that they need to use this capability and hence is not a viable solution.   

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

Left/right scrolling with voiceover/talkback and max accessibility font size should navigate to the next/previous list items even if they're not in view.

### Actual Behavior

Left/right scrolling with voiceover/talkback and max accessibility font size actually navigate to tab items on a right swipe (when not on bottom of the list), or the title bar on a left swipe (when not on top of the list) and skips the next/previous list items.   Which will be extremely confusing to a visually impaired user.

### Basic Information

- Version with issue: latest preview 5.0.0.1709-pre4 
- Last known good version: unknown
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @jhunterdfly - thanks for submitting this issue. Would you be able to share your project or a sample project reproducing this issue? Thanks :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
