### ISSUE TITLE
[Bug] Select-Deselect not working in Xamarin iOS using CollectionView

### ISSUE THREAD

**Issue by ukku2215** [xamarin/Xamarin.Forms#13250]
I have a CollectionView in which user can select or deselect multiple names from the ItemSource provided. It is working perfect on Android i.e user can select-deselect multiple names. But in iOS what happens is, if user selects one name and tries to select another name it is not getting selected. But if I scroll a bit and try to select or deselect the name it works. In short when a view is scrolled even if little bit it works fine. User should be able to select or deselect the names without scrolling the view.
![select deselect (1)](https://user-images.githubusercontent.com/76730815/103276672-2ca4b280-49ed-11eb-8055-a618d88e46bb.gif)

**Comment by hartez** [comment]
@ukku2215 Can you post your select/deselect code? Or even better, a small repro project which demonstrates the issue?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
