### ISSUE TITLE
Hide Keyboard

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#13269]
Hi,

Please add HideKeyboard command with just one word into the Xamarin Forms to replace the DependencyCode:

[https://stackoverflow.com/questions/30437362/how-to-dismiss-keyboard-on-button-press-in-xamarin-forms](https://stackoverflow.com/questions/30437362/how-to-dismiss-keyboard-on-button-press-in-xamarin-forms)

Thanks
Jassim

**Comment by transis2** [comment]
Maybe it can go to essentials

**Comment by jrahma** [comment]
It should have both **ShowKeyboard** and **HideKeyboard**.

Also, it will be great if it's possible to set the default language if the user has more than one language installed.

**Comment by almirvuk** [comment]
@hartez @samhouts I would like to take this one when the decision is made, will this go in Essentials or in XF. :)

**Comment by thecuong064** [comment]
Any idea when this will be implemented in XF or Essentials?

**Comment by groschialeux** [comment]
Functions to hide and show keyboard would be nice but I think we also need this as an attribute to entry tag in xaml.

<Entry
     blah
     blah
     ShowKeyboard="true/false"/>

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
