### ISSUE TITLE
ListView word wrap in Label causing ViewCells to overlap

### ISSUE THREAD

**Issue by derekwheeler-tylertech** [xamarin/Xamarin.Forms#1326]
### Description
For certain values, (but not all), when a Label in a ViewCell word wraps, it's partially superimposed on the next ViewCell in the ListView. 

Visual Studio 2015, 14.0.25425.01 Update 3 (on Windows 10)
Xamarin 4.7.10.38
Xamarin.iOS 11.3.0.47

### Steps to Reproduce

1. Run demo project

### Expected Behavior

List should display correctly

### Actual Behavior

CellView contents overlap

### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS: Broken on iOS for the past 6 or so months on all the versions of Xamarin that I've used during that time. 
  - Android: Works OK on android
  - UWP: I've never tried
- Android Support Library Version: N/A
- Affected Devices: Broken on iPhone6/7/8/X simulators and iPhone6 phone. Was broken on iOS 10.* and is still broken on iOS 11.1.

### Reproduction Link

[ListViewWrapBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1533294/ListViewWrapBug.zip)
![simulator screen shot - iphone x - 2017-12-05 at 17 26 57](https://user-images.githubusercontent.com/34287342/33635756-3b4bc716-d9e7-11e7-9c94-fcc5a7d9a03d.png)

**Comment by jassmith** [comment]
This is caused by an incorrect calculation of the cell height in the ListView renderer. @samhouts looks right up your alley :)

**Comment by syed-pelican** [comment]
We also have similar issue using Xamarin.Forms.2.5.0.121934. This seems to be not only a ListView issue but an issue in general. I have also experienced issues with StackLayout and Label and both elements had issues to calculate height and width. Please fix the engine to calculate correctly as this is fundamental for the UI.

**Comment by jassmith** [comment]
Do you have an additional sample we can use? There haven't really been many changes to the layout system in a long time. Most changes are coming in the way backends work.

**Comment by derekwheeler-tylertech** [comment]
Hey Jason. Was that question for me or syed?

**Comment by MichelMatthey** [comment]
Yes, similar unresolved issue here, the way it renders is not consistent across platforms and it is less than good enough...

We have had to resort to removing the ViewCells dynamically because if we don't it doesn't render the page/form properly and shows the ViewCell empty between thin lines and looks too ugly! this has some really nasty side effects so we are also stuck with this ?

So maybe you need to fix that instead so we don't have to use backdoors kind of solutions, this is because XF is quite flimsy in the way it renders pages and is not consistent across platforms so we do what we can to get the results we need... If the support was a bit better we wouldn't have to resort to such drastic solutions either...

---> If a ViewCell content is blank or empty, the renderer should not display it at all, and should not display the thin separator lines either ? This way would be the expected behaviour you would think ? Can you fix that please ? And also make sure it also works properly on iOS ?

**Comment by samhouts** [comment]
@MichelMatthey I think you might be reporting a different issue. Would you mind opening a new issue with a reproduction illustrating the problem? Thanks.

**Comment by samhouts** [comment]
@syed-pelican If you have a reproduction showing the issues without a ViewCell, can you please provide it to us? Thanks.

**Comment by SlaKul** [comment]
@samhouts  Maybe the issue #1395 would help a bit. It reports the similar problem with measure and layout related to Label in Grid.

**Comment by MichelMatthey** [comment]
Well, the fact is there is a problem with the rendering of ViewCells with Grids and labels using the HasUnevenRows="True" RowHeight="-1" are used, it works fine on Andoid but is flimsy on iOS, but then again, apart from the price, everything is a bit flimsy on iOS! 

They (Apple and iOS) don't even have a a concept of services (No GUI apps that run in the background) which come out of the box on Android and was available in Windows 95 some 20 years ago!!!

Any actual solution for this ?

**Comment by Weishaupt** [comment]
I still experience this behavior in a production app on the iPhone 5s and the iPhone 5s simulator. The Repo Solution from above works fine. Unfortunately, I cannot quite put my finger on what exactly is going wrong.

![grafik](https://user-images.githubusercontent.com/2642714/54948900-11666280-4f3e-11e9-962f-14ca5a4f90bb.png)

As you can see, for two elements the message is too long and wraps. Somehow the spacing is not adjusted as should be.

On the other hand the Message in the Category Messages is fully expanded and word wrapped.

I'm trying to reproduce the issue, but am still unable to do so after two hours of fiddling around. My production code uses Grouping and Template selectors. If I add this to the solution here, it still works.

The template for the Licenses (rendering broken) looks like this:
```xml
<DataTemplate x:Key="LicenseExpiryTemplate">
  <ViewCell>
    <StackLayout Style="{DynamicResource ListViewCellStyle}">
      <Label Text="{Binding Text}"
        LineBreakMode="WordWrap"
        Style="{DynamicResource ListItemTextStyle}" />
    </StackLayout>
  </ViewCell>
</DataTemplate>
```

The template for the messages (working) like this:
```xml
<DataTemplate x:Key="NoContextActionTemplate">
  <ViewCell>
    <StackLayout Style="{DynamicResource ListViewCellStyle}">
      <Label Text="{Binding Subject}"
        LineBreakMode="WordWrap" Style="{DynamicResource ListItemTextStyle}" />
      <Label Text="{Binding MessageContent}"
        LineBreakMode="WordWrap"
        Style="{DynamicResource ListItemDetailTextStyle}" />
    </StackLayout>
  </ViewCell>
</DataTemplate>
```

Maybe someone has an idea as to why this still happens. @samhouts 

I'm using Visual Studio 2019 RC3 and XF 3.6.0.264807 with a .NET standard project.

**Comment by ndastur** [comment]
I'm seeing this bug again on iOS 13.5 using XF 4.7.0.968. I tried downgrade to 4.6.0.967 and bug persists
