### ISSUE TITLE
[Enhancement] RefreshView threshold!

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Forms#13278]
## Summary
Is it possible to define a property for the pull to refresh threshold? Basically the same as Syncfusion here:
https://help.syncfusion.com/xamarin/pull-to-refresh/customization#pullingthreshold

`<RefreshView PullingThreshold="200"/>`

## Intended Use Case
Right now, when I pull down with my finger at the bottom of the screen it still triggers the refresh command. With the `PullingThreshold` property set to 200 (as an example), the refresh command would be triggered only if we reached the top of the screen **AND** the finger is within 200 from the top.

If this is already possible somehow, please advise, thanks!

**Comment by Tarekka** [comment]
Any update on this? RefreshView triggers too easily

**Comment by Cvijo** [comment]
+1 this would be a nice feature to add .. btw what event is fired when you pull to offset (on android you get this blue semicircle when pulling )

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
