### ISSUE TITLE
TabBarIsVisible is set to false ,still TabBar appears on iOS 

### ISSUE THREAD

**Issue by AbhijeetChowdhury92** [xamarin/Xamarin.Forms#13276]
Hi,

This issue re-appeared in the latest version v4.8.0.1821.

_Originally posted by @AbhijeetChowdhury92 in https://github.com/xamarin/Xamarin.Forms/issues/10126#issuecomment-753913258_

**Comment by hartez** [comment]
@AbhijeetChowdhury92 If I update the reproduction project from #10126 to 4.8.0.1821, it still works correctly. Could you submit a small repro project which demonstrates the issue you are seeing?

**Comment by AbhijeetChowdhury92** [comment]
Hi @hartez ,

The reproduction project from #10126 works correctly for me too. It's a bit weird with my project as I have got two iPhone XR and it's working fine on one of my device and the other one is showing a Tab bar although it's visibility is set to false in AppShell.xaml. For the meantime please find attached the screenshot. I will try upgrading the project to latest framework version 5.0.0.1874 today.
![Capture](https://user-images.githubusercontent.com/19604907/103868346-c99ed400-50ee-11eb-874c-28f4b3407706.PNG)
![Screen Shot 2020-12-14 at 12 12 49 PM](https://user-images.githubusercontent.com/19604907/103868350-cad00100-50ee-11eb-8807-926286f46984.png)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
