### ISSUE TITLE
[Bug] CollectionView On MacOS

### ISSUE THREAD

**Issue by Axemasta** [xamarin/Xamarin.Forms#13289]
### Description

Does CollectionView Support MacOS? I wasn't sure whether this was a bug or a feature request as it is not clear whether macOS should support the `CollectionView` control. Looking at the issue history in this repo the macOS tag is present in the work so I believe it should be supported.

### Steps to Reproduce

I have produced a sample repo showing different repeater views in Xamarin Forms. The samples are tested and working perfectly on iOS & Android. On macOS the `CollectionView` implementation is not visible while the `ListView` & `BindableLayout` implementations work as expected.

1. Load provided sample app on iOS & Android
2. Click each button to view an example of the described control
3. Observe each control implementation working correctly
4. Load the sample app on macOS
5. Click each button to view an example of the described control

### Expected Behavior

Observe each control implementation working correctly

### Actual Behavior

`ListView` & `BindableLayout` function as expected but `CollectionView` displays nothing.

When browsing to the `CollectionView` page alot of messages appear in the debugging window:
```
2021-01-05 11:35:05.672 CollectionViewTest.macOS[46801:1496336] WARNING <NSToolbarItemGroup: 0x6000018f8a80> -> view was automatically measured but had an ambiguous height or width and the view's frame size had a zero height or width. Did you forget to add constraints on your view or its subview(s)? Try adding constraints or give the view an intrinsicContentSize
```

### Basic Information

- Version with issue: 4.8.0.1821 (latest stable as of issue)
- Last known good version: ?
- Platform Target Frameworks: 
  - macOS:  macOS Catalina 10.15.7
- Android Support Library / AndroidX Version: 
- NuGet Packages:
  - Refractored.MvvmHelpers (1.6.2)
  - Xamarin.Essentials (1.6.0)
  - Xamarin.Forms (4.8.0.1821)
  - Xamarin.Forms.PancakeView (2.3.0.759)
- Affected Devices:
  - macOS devices
### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.8.3 (build 16)
Installation UUID: 50576cd0-d0c3-4ea0-afa9-4bdb01e067cd
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000107

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.107 (2020-02/a22ed3f094e) (64-bit)
	Package version: 612000107

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.100/Sdks
SDK Versions:
	5.0.100
	3.1.404
	3.1.403
	3.1.402
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.0
	3.1.10
	3.1.9
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Enterprise)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Enterprise)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.507
Hash: e87b24884
Branch: remotes/origin/d16-8
Build date: 2020-10-29 00:31:38 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Enterprise)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/alex.duffell/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/alex.duffell/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:30 UTC

=== Android Device Manager ===

Version: 16.8.0.45
Hash: fc0af5f
Branch: remotes/origin/d16-8
Build date: 2020-10-13 23:32:54 UTC

=== Build Information ===

Release ID: 808030016
Git revision: cc6375d2fdcc1b42532e551e24ce650eaca1ae45
Build date: 2020-11-25 13:16:20-05
Build branch: release-8.8
Xamarin extensions: cc6375d2fdcc1b42532e551e24ce650eaca1ae45

=== Operating System ===

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Thu Oct 29 22:56:45 PDT 2020
    root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

DeepClean 1.2.5
FileNesting 0.1.2
LightSwitch 💡 1.0
Code Coverage 1.0
MFractor 4.4.5

```

</details>

#### Sample Working On iOS

![Sample Running On iOS](https://raw.githubusercontent.com/Axemasta/CollectionViewMac/main/assets/ios_example.gif)

#### Sample Working On Android

![Sample Running On Android](https://raw.githubusercontent.com/Axemasta/CollectionViewMac/main/assets/android_example.gif)

#### Sample Not Working On MacOS

App Window Only

![App Window Recording On Mac](https://raw.githubusercontent.com/Axemasta/CollectionViewMac/main/assets/macos_example_1.gif)

Visual Studio View (See Debugger Messages)

![Full Screen Recording On Mac](https://raw.githubusercontent.com/Axemasta/CollectionViewMac/main/assets/macos_example_2.gif)

### Reproduction Link

[The Main Branch Of This Repo](https://github.com/Axemasta/CollectionViewMac)

**Comment by hartez** [comment]
@Axemasta CollectionView is currently only supported on iOS, Android, and UWP.

**Comment by Axemasta** [comment]
@hartez do you have any idea on the roadmap for adding mac support?

**Comment by DancesWithDingo** [comment]
The docs should at least be updated to state that CollectionView is only supported on iOS, UWP and Android.

**Comment by hartez** [comment]
@Axemasta Unfortunately, I don't know the timeline for macOS support. I know that its unlikely we'll be supporting it on macOS before .NET MAUI.

@DancesWithDingo It's mentioned in the [intro section](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction).
