### ISSUE TITLE
How is my new viewmodel instance remembering an old list's contents, and multiplying calls from messaging center?[Bug] 

### ISSUE THREAD

**Issue by BullCityCabinets** [xamarin/Xamarin.Forms#13293]
### Steps to Reproduce
In attached project...
1. Navigate from HomePage, to OrderPage, to InventoryPage, and select an item.
2. Go back, then back again to the HomePage
3. Repeat navigation to Inventory page and select and item.  UI at the top of that page will show that the OrderPage was sent a message once, but behaved like it received it twice.
4. Repeat step 3, and OrderPage will run it's messageing center related method 3 times.  This occurs once more every time it's navigated from-and-back-to.
5. Examine OrderVM.cs line 56 "OrderItemsDisplayed" and it will still contain items added from step 1.

### Expected Behavior
New viewmodels would not remember old view model information.  

### Actual Behavior
New viewmodels would remember old view model information.  Even clearing lists and unsubcribing from messages in viewmodel's constructor doesn't clear issues.

### Basic Information

- Version with issue: 4.8.0.1821+410-sha.626f756ab-azdo.4309562
- Last known good version: none
- Platform Target Frameworks: 
  - Android: 9.0 

- NuGet Packages: Xamarin.Forms 4.8.0.1821, Xamarin.Essentials 1.6.0
- Affected Devices: any android emulators 

### Environment
<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA783
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

https://github.com/BullCityCabinets/Illustrate-Selection-Bug

### Workaround

none to date

**Comment by hartez** [comment]
The problem is that your old viewmodels from previous instances of your pages are still around until they are garbage collected. 

1. You create and navigate to an instance of OrderPage. OrderPage creates an OrderVM; in its constructor, OrderVM subscribes to any "UpdateOrder" messages. We'll call this instance of OrderVM "OrderVM-A".
2. You navigate back, which pops that instance of OrderPage off the navigation stack. 
3. You create and navigate to a new instance of OrderPage. OrderPage creates a new OrderVM - we'll call this one "OrderVM-B". It is also subscribed to any "UpdateOrder" messages. 

At this point, the initial instance of OrderPage and OrderVM-A are both _eligible_ for garbage collection, but they haven't necessarily been collected yet. Which means that OrderVM_A is still subscribed to "UpdateOrder" messages. Until it is collected, any "UpdateOrder" messages sent by your InventoryVM will be handled by _both_ OrderVM-A _and_ OrderVM-B. So you'll see the results multiple times. And this can keep happening (creating OrderVM-C, -D, -E, etc.) until the garbage collector collects the old view models.

There are several options for handling this:

- Tightly couple your OrderVM and InventoryVM. Instead of using MessagingCenter to communicate between InventoryVM and OrderVM, use events and keep a 1:1 relationship between the VMs.

- Keep a single, central view model. If it only makes sense to have one OrderVM active at a time, just keep one instance central to the application and reuse it. 

- Explcitly unsubscribe old view models from MessagingCenter. As you don't need the view model any more (e.g., when the associated page is popped off the navigation stack), call MessagingCenter.Unsubscribe().

(These are just some options. The right answer for your application will depend on your design and goals.)

**Comment by BullCityCabinets** [comment]
First of all, I have been asking about this in different places for months, and you're the most engaged responder I have encountered, so "thanks, big time."

1) I'd like to point out that "Unsubscribing" in my OrderVM's constructor does not prevent the redundant calls from occurring.  I had tried that.

2) If the lists in the initial View Model are going to persist forever, it's mandatory to use one static View Model in App.cs, correct?    Previous iterations used this design, and it involved what felt like an unprofessional amount of assignments when loading or importing data... running new constructors *seemed* like the simple answer.

3) Would it be reasonable to implement and  run IDisposable on any existing OrderVMs before the Page creates a new one as it's binding context?  I had not yet had success attempting this, yet, and wasn't sure it was possible, and had not seen it as a recommended pattern... but sounds legit, right?

Again, thank you @hartez, for the definitive answer that my code is flawed, so I can move past this train wreck and get on with banging my head against a different wall!

**Comment by hartez** [comment]
> First of all, I have been asking about this in different places for months, and you're the most engaged responder I have encountered, so "thanks, big time."

No problem. Sometimes it's hard for us to respond to all the questions and bugs, but we try :)

> 1. I'd like to point out that "Unsubscribing" in my OrderVM's constructor does not prevent the redundant calls from occurring.  I had tried that.

That _should_ work; maybe there's a bug in MessagingCenter's unsubscribe logic. 

> 2. If the lists in the initial View Model are going to persist forever, it's mandatory to use one static View Model in App.cs, correct?    Previous iterations used this design, and it involved what felt like an unprofessional amount of assignments when loading or importing data... running new constructors _seemed_ like the simple answer.

Again, a lot of that depends on your design and goals. You could also stick with constructing new models as needed, and just use a different inter-model communication mechanism. MessagingCenter is a fine option for that as long as you understand the object lifetime issues involved, but plain old C# events or just direct coupling might be a better option in your case. 

> 3. Would it be reasonable to implement and  run IDisposable on any existing OrderVMs before the Page creates a new one as it's binding context?  I had not yet had success attempting this, yet, and wasn't sure it was possible, and had not seen it as a recommended pattern... but sounds legit, right?

That's certainly one way to do it. I can't immediately see anything wrong with that.
