### ISSUE TITLE
[Enhancement] Make IProvideParentValues Public 

### ISSUE THREAD

**Issue by matthewrdev** [xamarin/Xamarin.Forms#13298]
## Summary
Expose the [IProvideParentValues interface](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/IProvideParentValues.cs) as a public API to allow use by third-party markup extensions.

The `IProvideParentValues` interface is useful for custom markup extensions as it allows the extension to inspect the current hierarchy in the visual tree. Currently, when retrieving the current view via `IProvideValueTarget.TargetObject`, the views `Parent` is unset, leaving `IProvideParentValues` as the only way we get a controls parent.

For users of Xamarin.Forms who wish to create custom markup extensions, this means that we are unable to inspect the parent hierarchy for a control. This has been flagged previously by the community in #5052.

## API Changes

Change `IProvideParentValues` accessibility from `internal` to `public`.

## Intended Use Case
When working with Grids in XAML, we specify the location of a control using the `Grid.Row`/`Grid.Column` syntax.

```
<Grid RowDefinitions="*">
  <Label Grid.Row="0" />
</Grid>
```

By opening up `IProvideParentValues` as a public interface, we can build markup extensions that allow locations and spans to be specified by name:

```
<Grid>
  <Grid.RowDefinitions>
    <RowDefinition x:Name="labelRow" Height="Auto"/>
  </Grid.RowDefinitions>
  <Label Grid.Row="{local:GridLocation labelRow}" />
</Grid>
```

To enable this syntax, the [GridLocation](https://github.com/matthewrdev/Xamarin.Forms.GridLocationExtension/blob/main/GridLocationMarkupExtension/GridLocationExtension.cs) and [GridSpan](https://github.com/matthewrdev/Xamarin.Forms.GridLocationExtension/blob/main/GridLocationMarkupExtension/GridSpanExtension.cs) must be able to find the parent grid for the `IProvideValueTarget.TargetObject`. Currently these extensions must [use reflection to access this API](https://github.com/matthewrdev/Xamarin.Forms.GridLocationExtension/blob/main/GridLocationMarkupExtension/GridMarkupExtensionHelper.cs#L18) as there is no obvious alternative.

For a full working prototype of these extensions, and a deeper explanation into their potential benefits, please see:

 * [Humanising Grids In Xamarin.Forms](https://www.mfractor.com/blogs/news/humanising-grids-in-xamarin-forms).
 * [GridLocation and GridSpan Markup Extensions Prototypes](https://github.com/matthewrdev/Xamarin.Forms.GridLocationExtension)

**Comment by matthewrdev** [comment]
As a follow up on this request, I've tested my extensions in both compiled and interpreted XAML and there is no difference in behaviour for the `IProvideParentValues` interface. In both compiled and interpreted XAML the interface behaves the same and returns the same data.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
