### ISSUE TITLE
Flyout gesture has changed behaviour in version 5.0 [Bug] 

### ISSUE THREAD

**Issue by dxt-rr** [xamarin/Xamarin.Forms#13304]
### Description
After updating to Xamarin forms 5.0.0.1874 the flyout menu can not be opened with a swipe gesture anymore on secondary pages on iOS devices.

### Steps to Reproduce
1. Create a new Xamarin forms project with flyout using the flyout template
2. Update Xamarin forms nuget package
3. Deploy app to iOS device
4. On the "About" page activate the flyout and choose "Browse"
5. Click on any item to get to the details page
6. Swipe from the left screen border to the right

### Expected Behavior
Like on android and on iOS with Xamarin forms version 4.8.0.1821 the flyout menu should open.

### Actual Behavior
The previous page ("Browse") will swipe in like one would tap the back button

### Basic Information
- Version with issue: 5.0.0.1874
- Last known good version: 4.8.0.1821
- Platform Target Frameworks:
  - iOS:  14.2
  - Android: 10

**Comment by rachelkang** [comment]
Hi, @dxt-rr - thank you for sharing! I believe the actual behavior you're describing is the expected behavior - I followed the steps you described and am seeing the same behavior on both the 4.8 and 5.0 versions you mention. On the detail page, swiping from the left screen border goes back a page (this is typical iOS behavior), and when there are no pages to go "back" to (as on the "Browse" page), swiping from the left screen border opens up the flyout menu.

**Comment by dxt-rr** [comment]
Hi Rachel,
Thank you for taking your time to have a look at this.
I am not seeing the same behaviour between the two versions and I have 2 apps in the app store and 1 I am currently developing and the template project and I have tested with 3 different iOS devices (2 iPads and 1 iPhone). It is always the same. With 4.8 I get the flyout, with 5.0 it goes back...
So generally it is possible to get the flyout wherever I am. No matter what behaviour may be the default one, the flyout one is the one I need and I am ordered to implement. So, what can we do to asure to have the intended behaviour in both versions?

**Comment by PureWeen** [comment]
@dxt-rr what device specifically are you seeing this issue on?

**Comment by dxt-rr** [comment]
iPhone11 A2221 iOS 14.2
iPad7 A2197 iOS 14.2
iPad6 A1893 iOS 13.7

**Comment by PureWeen** [comment]
Apologies @dxt-rr but I'm just not seeing what you're seeing

I've tested a version with 1821 and for me it always swipes in the previous page and never opens the flyout
Can you attach a repro and possibly a video of the behavior?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
