### ISSUE TITLE
[Bug] Doesn't show Shell.Title on iOS, but fine on Android.

### ISSUE THREAD

**Issue by Nelo-cool** [xamarin/Xamarin.Forms#13306]
### Description
Hello guys!
In Xamarin Forms 5.0 Release my code:
![image](https://user-images.githubusercontent.com/902820/103770352-f0013880-5036-11eb-8ee9-2368326ddf8f.png)
After build and run in Android (fine):
![image](https://user-images.githubusercontent.com/902820/103770416-060ef900-5037-11eb-8dcb-9e901dfde1bc.png)
On iOS (is bad, from somewhere, the top indent is taken equal to 20 px, I was able to see it debug mode. StackLayout.Margin.Top = 20. What?! :( ) on device SE 1st:
![image](https://user-images.githubusercontent.com/902820/103770524-335ba700-5037-11eb-8e2b-4d0d84849dbf.png)
On iOS (is bad too, but...:): empty view! Okay. rollback to the pre 6 and i can see fine work:
![image](https://user-images.githubusercontent.com/902820/103771050-1673a380-5038-11eb-8b9e-6693720a90af.png)
Good boys:)
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 5.0 release
- Last known good version: 5 pre 6.
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android:  7.1 and above
  - UWP:  none
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @Nelo-cool - thanks for sharing! Confirming that I can reproduce this issue as per my [comment](https://github.com/xamarin/Xamarin.Forms/issues/13310#issuecomment-755445113) here on a related issue. We'll be sure to take a closer look at this
