### ISSUE TITLE
[Enhancement] Looping Scroll

### ISSUE THREAD

**Issue by oicangi05** [xamarin/Xamarin.Forms#13308]
## Summary
My idea is to have a Scrollable view( It could be the ScrollView, CollectionView or a Bindable Layout), in which it is possible to have a looping ItemsSource i.e when scrolling down the user never reaches the end, but the first element of the List. Has anyone done this? 

## Intended Use Case
Something like the EnableLooping of the SFPicker

**Comment by rachelkang** [comment]
Hi, @oicangi05 - thanks for submitting this proposal! While this remains in consideration, you may be interested in checking out [CarouselView](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/introduction) w/ looping (`Loop = True`) as well as @mattleibow's library for adding infinite scrolling support to a XF ListView

**Comment by oicangi05** [comment]
Hi @rachelkang  - thanks for the proposal, I've already checked @mattleibow 's library, but that's not quite what I'm looking for. CarouselView comes closer, but can I set the CarouselView's Orientation to vertical?

**Comment by rachelkang** [comment]
@oicangi05 yep! You can set the vertical orientation as described in our docs [here](https://docs.microsoft.comxamarin/xamarin-forms/user-interface/carouselview/layout#vertical-layout) and as seen in this [sample](https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/CarouselViewDemos/CarouselViewDemos/Views/Spacing/VerticalSpacingPage.xaml) :)

**Comment by oicangi05** [comment]
thanks a lot :) @rachelkang

**Comment by rachelkang** [comment]
no problem, happy to help! :)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
