### ISSUE TITLE
[Android] ViewCell shows ContextActions on tap instead of long press

### ISSUE THREAD

**Issue by bruzkovsky** [xamarin/Xamarin.Forms#1331]
### Description

Original:
https://bugzilla.xamarin.com/show_bug.cgi?id=60850

A ViewCell containing a View with a TapRecognizer will show its ContextActions on every tap, instead of the long-press that is specific for android. Removing the TapRecognizer from the View resolves the behavior.

The context actions on Android should only be shown when there was a long press, hence this is a bug.

### Steps to Reproduce

The attached solution contains a single Android project with X.F backend. Running the project will display a page with a ListView.

1. Tap any item
2. Context menu will appear on top of navigation bar

### Expected Behavior

Nothing

### Actual Behavior

The context menu is shown, although there was no long press.

### Basic Information

- Version with issue: 2.5.0.91635
- Last known good version: 2.4.0.282
- IDE: Visual Studio 15.5
- Platform Target Frameworks: 
  - iOS: NO
  - Android: YES
  - UWP: NO
- Android Support Library Version: 25.4.0.2
- Affected Devices: Wileyfox Swift 2 running Android 7.1.2

### Reproduction Link

[ContextAction.zip](https://github.com/xamarin/Xamarin.Forms/files/1535366/ContextAction.zip)

**Comment by minafaw** [comment]
I have the same issue
