### ISSUE TITLE
[Bug] Shell.TitleView no longer displays a title view on a ContentPage 

### ISSUE THREAD

**Issue by eddieyanez** [xamarin/Xamarin.Forms#13310]
### Description
Since the update to Xamarin.Forms 5, the TitleView has disappeared

### Steps to Reproduce

1. Add Nuget package 5.0.0.1874
2. Inside 
```
<ContentPage ...  />
```
add:
```
    <Shell.TitleView>
        <Label Text="Something"
               HorizontalOptions="StartAndExpand"
               VerticalOptions="StartAndExpand"
               HeightRequest="40"
               WidthRequest="100"
               BackgroundColor="Red"
               TextColor="White"
               />
    </Shell.TitleView>
```

### Expected Behaviour
![Simulator Screen Shot - iPhone 12 Pro - 2021-01-06 at 14 02 21](https://user-images.githubusercontent.com/1080027/103777238-7c582f00-5028-11eb-9006-a6019a40faa7.png)

Works on 4.8.0.18.21.

### Actual Behavior
![Simulator Screen Shot - iPhone 12 Pro - 2021-01-06 at 14 06 10](https://user-images.githubusercontent.com/1080027/103777247-7eba8900-5028-11eb-98fa-b075904a3588.png)

Does not work on 5.0.0.1874.

### Basic Information

- Version with issue:
- Last known good version: 4.8.0.18.21
- Platform Target Frameworks:
  - iOS:  Latest
  - Android: Not tried
- Android Support Library / AndroidX Version: Not tried
- NuGet Packages: Xamarin.Forms
- Affected Devices: Simulator

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: c3a0e221-47dc-43d0-8307-4a48c218643f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/eddieyanez/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/eddieyanez/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.6


```

</details>

### Screenshots

As above.

### Reproduction Link

As above.

### Workaround

No.

**Comment by rachelkang** [comment]
Hi, @eddieyanez - thank you for sharing! I tried to reproduce this issue, but unfortunately wasn't able to.

Would you mind sharing your project or a sample project that reproduces the issue? Or if it's easier, could you edit this project? 
[Issue13310.zip](https://github.com/xamarin/Xamarin.Forms/files/5777209/Issue13310.zip) Thanks :)

This is what I see on 5.0.0.1874:
![Simulator Screen Shot - iPod touch (7th generation) - 2021-01-06 at 12 26 40](https://user-images.githubusercontent.com/21988533/103800735-c33f2800-501a-11eb-8bea-0b7c78a95a29.png)

**Comment by rachelkang** [comment]
@eddieyanez Could you try running on Android and let us know how similar/different the behavior is?

**Comment by eddieyanez** [comment]
Hey, absolutely. Give me an hour or so and I’ll let you know. I’ll try with a new project + yours too. Thanks for looking into this so quickly.

**Comment by eddieyanez** [comment]
> @eddieyanez Could you try running on Android and let us know how similar/different the behavior is?
> Seems like this might be related to #13306

Works on Android. I'll try your project next.

<img width="491" alt="Screenshot 2021-01-06 at 19 05 04" src="https://user-images.githubusercontent.com/1080027/103809903-32843e80-5052-11eb-8379-a9a58ea44414.png">

**Comment by eddieyanez** [comment]
I've tried your project and it works fine on Android, but not on iOS.

Let me know if there's anything else I can do to help investigate.

<img width="488" alt="Screenshot 2021-01-06 at 19 12 35" src="https://user-images.githubusercontent.com/1080027/103810584-6ad84c80-5053-11eb-9a6f-fa9419172661.png">

<img width="485" alt="Screenshot 2021-01-06 at 19 13 35" src="https://user-images.githubusercontent.com/1080027/103810672-8e02fc00-5053-11eb-83eb-0c8c9a0e4614.png">

**Comment by PureWeen** [comment]
@eddieyanez @rachelkang  This looks like it's a "notch" specific bug 

I tested on iPhone SE and it works fine
iPhone 12 it does not work fine

**Comment by lqsantos** [comment]
Some problem here

**Comment by elicul** [comment]
Is there any workaround for this issue?

**Comment by eddieyanez** [comment]
> Is there any workaround for this issue?

Not that I’m aware of, sadly.

**Comment by fhintsch** [comment]
Must go back to Forms 4! Annoying.

**Comment by douglassimaodev** [comment]
How can I get the current title style to apply in Shell.TitleView? I noticed when I use it and add a label to display the table, it is not possible to replicate the titles from the other pages, how to get the current title font size, color, and font family?

**Comment by SakthivelCapgemini** [comment]
Why we have margin in both left and right side, when use Shell.Titleview

**Comment by SakthivelCapgemini** [comment]
This occurs only when i disabling the flyout Behavior feature
