### ISSUE TITLE
[Bug] ProgressBar on Mac does not display at all, but displays correctly on Android. 

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.Forms#13317]
### Description

ProgressBar on Mac does not display at all, but displays correctly on Android. 
Screenshots below.

### Steps to Reproduce

1. Add a ProgressBar to your Xamarin.Form on both Mac and Android

using the following code...

```
var progressBar = new ProgressBar {
	HorizontalOptions = LayoutOptions.CenterAndExpand,
	VerticalOptions = LayoutOptions.CenterAndExpand,
	Progress = item.PercentComplete,
};

var progressLeaderboardStackLayout = new StackLayout {
	Orientation = StackOrientation.Horizontal,
	Children = {
		progressBar,
	}
};
```

### Expected Behaviour

On all platforms it should display a progress bar when the percentage value is great than

### Actual Behaviour

It displays correctly on Android, but NOT on MacOS.

### Basic Information
- NuGet Packages: Xamarin.Forms 4.8.0.1821

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 60c7c193-36a0-40cb-a1f6-65589da22877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.302
	3.1.301
	3.1.200
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.6
	3.1.5
	3.1.2
	2.1.23
	2.1.20
	2.1.19
	2.1.17
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/dominique/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dominique/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Visual Studio for Mac Extension for Tizen 1.5
Meadow 0.7.8

### Build Logs

NA

### Screenshots

Android displays correctly
<img width="395" alt="Screenshot 2021-01-06 at 17 22 44" src="https://user-images.githubusercontent.com/271363/103800088-db776d00-5043-11eb-8f93-c37fb702cbb1.png">

MacOS does NOT display at all on the right, under the Animals category, but the percentage text shows the correct value.
<img width="501" alt="Screenshot 2021-01-06 at 22 28 21" src="https://user-images.githubusercontent.com/271363/103826411-b0564300-506e-11eb-89d3-950c8615db8f.png">

### Reproduction Link

The code above should show the error.

### Workaround

Not that I'm aware of.

**Comment by CartBlanche** [comment]
@hartez @jfversluis I think the issue is that for Mac the NSProgressIndicator is expecting a double value between 0.0-100.0 (according to the docs - https://developer.apple.com/documentation/appkit/nsprogressindicator/1501173-doublevalue?language=objc ), while on iOS and Android the value is 0.0 - 1.0. Seems that Forms is clamping the upper value to 1.0. 

So I think on MacOS, in the ProgressBar Renderer (https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.MacOS/Renderers/ProgressBarRenderer.cs#L84) you might need to multiply the passed in value by 100.

Hope this helps.

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue:
<img width="1276" alt="Captura de pantalla 2021-02-08 a las 11 58 52" src="https://user-images.githubusercontent.com/6755973/107210943-27338280-6a05-11eb-8398-1f2bad6489a0.png">
[Issue13317.zip](https://github.com/xamarin/Xamarin.Forms/files/5943182/Issue13317.zip)

@CartBlanche  Could you attach a sample where reproduce the issue?.

**Comment by CartBlanche** [comment]
@jsuarezruiz I think this may be related to Horizontal/Vertical options mentioned here - https://github.com/xamarin/Xamarin.Forms/issues/13312 by @rachelkang. So my question is still how does this work and appear correctly in Android, but doesn't in iOS/MacOS. Is Android's rendering a bug then?

**Comment by rmarinho** [comment]
Hey @CartBlanche  does it work if you use a Grid instead of a StackLayout?

**Comment by CartBlanche** [comment]
@rmarinho I tried a Grid and it fixed it for iOS, but still seems to be invisible on MacOS.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
