### ISSUE TITLE
[Enhancement] Expose default iOS WkWebViewRenderer delegates to allow for more flexibility without breaking default behavior

### ISSUE THREAD

**Issue by SuperCorks** [xamarin/Xamarin.Forms#13316]
## Summary
The default iOS `WkWebViewRenderer` class is great but difficult to extend. Overwriting both the `NavigationDelegate` and `UiDelegate` breaks default behavior like navigation events (in addition, the methods that raise these navigation events are "For internal use only" as per their doc summary). The proposed enhancement would facilitate the extension of the renderer without having to make use of internal methods by exposing the default [WkNavigationDelegate ](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs#L682) and [WkUIDelegate](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs#L800) and allow developers to extend them.

## API Changes

Change the name of both `CustomWebViewNavigationDelegate` and `CustomWebViewUIDelegate` to something like `DefaultWebViewNavigationDelegate` and `DefaultWebViewUIDelegate`, make them public, unsealed and allow derived classes to call `base()` on its methods.

## Intended Use Case
There are many use cases for such an enhancement... One could override a method or two of the NavigationDelegate to get the mime type of a file to download or [set the user-agent](https://github.com/xamarin/Xamarin.Forms/issues/8432) of some requests without breaking the default navigation events. Personally, I have used a custom `UIDelegate` to handle `target="_blank"` links and popups gracefully. I'm working on a mobile app that wraps a web app and I had to literally copy the open-source code of Xamarin.Forms' `WkWebViewRenderer` to extend it properly, when all I needed to do was extend one method in both CustomWebViewUIDelegate and CustomWebViewNavigationDelegate. In the end, my code looked like this:
![image](https://user-images.githubusercontent.com/6114650/103824289-a2d69400-5041-11eb-851e-770e283e560b.png)
![image](https://user-images.githubusercontent.com/6114650/103824071-3491d180-5041-11eb-88d2-7b809544fc35.png)
![image](https://user-images.githubusercontent.com/6114650/103824102-44111a80-5041-11eb-9edf-7d496561c7f5.png)

**Comment by SuperCorks** [comment]
If this is accepted, I would love to make the PR myself, I just need someone from the Xamarin team to give the green light.

**Comment by SuperCorks** [comment]
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/6340

**Comment by jfversluis** [comment]
Thank you for the extensive explanation here @SuperCorks and sorry you never really got an answer here. We're trying to do better with .NET MAUI with that :(

As with the linked issue, this won't happen for Xamarin.Forms anymore, but be sure to check our plans for .NET MAUI and open a proposal there if this is still something you're interested in. Thanks!
