### ISSUE TITLE
[Bug] ProgressBar on iOS does not respect VerticalOptions = LayoutOptions.CenterAndExpand

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.Forms#13312]
### Description

ProgressBar on iOS does not respect VerticalOptions = LayoutOptions.CenterAndExpand; But this works correctly on Android. Screenshots below.

### Steps to Reproduce

1. Add a ProgressBar to your Xamarin.Form on both iOS and Android
2. Set it VerticalOptions = LayoutOptions.CenterAndExpand

### Expected Behaviour

On all platforms it should centre the control vertically

### Actual Behaviour

It centres correctly on Android, but NOT on iOS.

### Basic Information
- NuGet Packages: Xamarin.Forms 4.8.0.1821

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 60c7c193-36a0-40cb-a1f6-65589da22877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.302
	3.1.301
	3.1.200
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.6
	3.1.5
	3.1.2
	2.1.23
	2.1.20
	2.1.19
	2.1.17
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/dominique/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dominique/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Visual Studio for Mac Extension for Tizen 1.5
Meadow 0.7.8

### Build Logs

NA

### Screenshots

Android is Correct:
<img width="395" alt="Screenshot 2021-01-06 at 17 22 44" src="https://user-images.githubusercontent.com/271363/103800088-db776d00-5043-11eb-8f93-c37fb702cbb1.png">

iOS is NOT Correct:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-06 at 17 15 41](https://user-images.githubusercontent.com/271363/103799701-5ab87100-5043-11eb-8fde-c59be2b4fb3d.png)

### Reproduction Link

The code above should show the error clearly.

### Workaround

Not that I'm aware of directly. Only other way would be to wrap it in another layout structure like a stack layout and use that to centre it vertically. But really it should just work (TM) on all plaforms.

**Comment by hartez** [comment]
@CartBlanche I'm trying to reproduce the issue, but no luck so far. My repro attempt is below.

Can you tell me what I'm missing, or maybe post the XAML/C# for your layout?

[_13312 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/5777592/_13312.Repro.zip)

**Comment by CartBlanche** [comment]
@hartez here is what I'm using...

```
var progressBar = new ProgressBar {
	        HorizontalOptions = LayoutOptions.CenterAndExpand,
	        VerticalOptions = LayoutOptions.CenterAndExpand,
	        Progress = item.PercentComplete,
        };

        var leaderboardIcon = new Image {
          HorizontalOptions = LayoutOptions.EndAndExpand,
          VerticalOptions = LayoutOptions.CenterAndExpand,
          Aspect = Aspect.AspectFill,
          Source = ImageSource.FromResource ("KnightMoves.Resources.leaderboard64x64.png"),
          WidthRequest = 25,
          HeightRequest = 25,
        };

        var progressLeaderboardStackLayout = new StackLayout {
	        Orientation = StackOrientation.Horizontal,
	        Children = {
		        progressBar,
		        leaderboardIcon,
	        }
        };
```

Let me know if you need anything else.

**Comment by CartBlanche** [comment]
@samhouts, @hartez Anything else you need from me?

**Comment by rachelkang** [comment]
Hi, @CartBlanche - thanks for sharing! The difference between your code and @hartez's repro is that you're using a _Horizontal_ StackLayout. Unfortunately, using LayoutOptions vertically is not compatible with a Horizontal StackLayout, and using LayoutOptions horizontally is not compatible with a Vertical StackLayout.

As per our [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options#alignment):
> A StackLayout only respects the Start, Center, End, and Fill LayoutOptions fields on child views that are in the opposite direction to the StackLayout orientation. Therefore, child views within a vertically oriented StackLayout can set their HorizontalOptions properties to one of the Start, Center, End, or Fill fields. Similarly, child views within a horizontally oriented StackLayout can set their VerticalOptions properties to one of the Start, Center, End, or Fill fields.

Hope this makes sense! Let us know if you have any further questions or if I'm misunderstanding something

**Comment by CartBlanche** [comment]
@rachelkang Thanks for explanation. So is the fact it appears correctly on Android a bug then?

**Comment by PureWeen** [comment]
@CartBlanche I would say it's more of a quirk with how the native platforms decide to measure those native components. When sizing the ProgressBar for a horizontal layout we ask the native layer what size it wants to be and then use that to position the element. iOS is kind of weird how it sizes the ProgressBar. If you give it infinite space it'll just throw an exception. 

I'd recommend using a Grid to better define each column or possibly a FlexLayout
