### ISSUE TITLE
[Bug] [UWP] Path object does not take margin into account - draws over all available space

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#13311]
### Description

Using Path does not take margin into account on UWP

### Steps to Reproduce
ref: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/
Add path to page:
```
<Path Aspect="Uniform"
      Stroke="Yellow"
      Fill="Red"
      BackgroundColor="LightGray"
      HorizontalOptions="Start"
      HeightRequest="100"
      WidthRequest="100" Margin="100,100,0,0"
Data="M 11.9992,19.1982C 9.4952,19.1982 7.2922,17.9193 6.0012,15.9783C 6.0272,13.9913 10.0052,12.8983 11.9992,12.8983C 13.9932,12.8983 17.9712,13.9913 17.9972,15.9783C 16.7062,17.9193 14.5032,19.1982 11.9992,19.1982 Z M 11.9992,4.99823C 13.6552,4.99823 14.9992,6.34222 14.9992,7.99823C 14.9992,9.65625 13.6552,10.9982 11.9992,10.9982C 10.3432,10.9982 8.9992,9.65625 8.9992,7.99823C 8.9992,6.34222 10.3432,4.99823 11.9992,4.99823 Z M 11.9992,1.99823C 6.4762,1.99823 1.9992,6.47424 1.9992,11.9982C 1.9992,17.5212 6.4762,21.9982 11.9992,21.9982C 17.5222,21.9982 21.9992,17.5212 21.9992,11.9982C 21.9992,6.47424 17.5222,1.99823 11.9992,1.99823 Z"
>
</Path>  
```

### Expected Behavior
margin applied

### Actual Behavior
margin not applied to path and path image is drawn over all available space, does not account for margin

**Comment by rachelkang** [comment]
Hi, @JKennedy24 - thanks for submitting this issue.

I tried running your code and the margin seems to be working as expected:
![image](https://user-images.githubusercontent.com/21988533/103824098-43788400-5041-11eb-8170-9239e01be0da.png)

What version of XF are you using? This is what I see on **5.0.0.1874**, so if you're not yet on 5.0.0.1874, I recommend you try updating to it!

**Comment by JKennedy24** [comment]
Yes you're right, margin does work. it was something to do with scaling in my app that was confusing me. Sorry about that
