### ISSUE TITLE
[Bug] Forms 5 breaks iOS Shell FlyoutBackground and TitleView

### ISSUE THREAD

**Issue by ColeXm** [xamarin/Xamarin.Forms#13318]
### Description

I noticed that the NuGet packages for Xamarin.Forms 5 (5.0.0.1874) became available, so I upgraded. Immediately a few obvious things are broken in iOS (they seem ok in Android). I'll likely just downgrade, but I'm rather surprised this much obvious things are broken, so I want to confirm that this isn't just something weird with my app. BTW, I've already done a full clean of all bin & obj folders and rebuild everything.

So, the first obvious broken thing is that Shell.FlyoutBackgroundImage is being shown above the menu text, so no text is visible. Interestingly, I can blindly click on the menu items and they do work.

The second broken thing is that Shell.TitleView isn't being show at all. It seems to be never being allocated size.

I haven't tried creating a simple repro of these issues yet, so I suppose it is something strange in my app, but these were working fine before upgrading to Forms 5 .

### Steps to Reproduce

1. Download official sample : https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/
2.  Upgrade `Xamarin.Forms` package to `5.0.0.1874.
3.  Add 10 FlyoutItem in AppShell and   Set `Shell.FlyoutBackgroundImage` and `Shell.TitleView` .

### Expected Behavior

`FlyoutBackgroundImage` would not overlap the item and `TitleView` shows up . 

### Actual Behavior

`FlyoutBackgroundImage` overlap the item and `TitleView` not shows up . 

### Screenshots

//From XF 4
![6](https://user-images.githubusercontent.com/2161256/103843079-2049e500-50d2-11eb-92c7-ae42b1794265.PNG)![9](https://user-images.githubusercontent.com/2161256/103843091-26d85c80-50d2-11eb-95ff-d52b150ccb0b.PNG)

//From XF 5
![Capture](https://user-images.githubusercontent.com/2161256/103843130-38216900-50d2-11eb-866d-e975c6f7358d.PNG)![3](https://user-images.githubusercontent.com/2161256/103843136-3bb4f000-50d2-11eb-9684-88b36a4ac943.PNG)

**Comment by PureWeen** [comment]
Duplicate

https://github.com/xamarin/Xamarin.Forms/issues/13310
https://github.com/xamarin/Xamarin.Forms/issues/13295
