### ISSUE TITLE
[Bug] [Android] WebView.EvaluateJavascriptAsync thrown NullReferenceException when is offscreen in Shell

### ISSUE THREAD

**Issue by ossaltu** [xamarin/Xamarin.Forms#13326]
### Description

WebView.EvaluateJavascriptAsync throws NullReferenceException when is off-screen in Shell.

### Steps to Reproduce

1. When Shell tab is opened background task is executed that does some job and calls WebView.EvaluateJavascriptAsync after some time. Example:

```
public ItemsPage()
{
            InitializeComponent();

            Task.Run(async() => 
            {
                await Task.Delay(TimeSpan.FromSeconds(10));
                try
                {
                    await Device.InvokeOnMainThreadAsync(async () => await browser.EvaluateJavaScriptAsync("var a = 10;"));
                }
                catch(Exception e)
                {
                }
            });
        }
```
2. Click to other Shell tab before delay runs out.
3. NullReferenceExcepion is thrown when EvaluateJavaScriptAsync is executed. 

### Expected Behavior

Js code executed or at least no exception thrown.

### Actual Behavior

NullReferenceExcepion is thrown with stack trace:
```
  at Xamarin.Forms.WebView.EvaluateJavaScriptAsync (System.String script) [0x00067] in D:\a\1\s\Xamarin.Forms.Core\WebView.cs:107 
  at App9.Views.ItemsPage.<.ctor>b__1_0 () [0x000a9] in D:\Projects\Temp\App9\App9\App9\Views\ItemsPage.xaml.cs:23 
```

### Basic Information

- Version with issue: 4.8.0.1821
- Last known good version: -
- Platform Target Frameworks: 
  - Android: 10.0, API level 29
- NuGet Packages: Xamarin.Essentials 1.6, Xamarin.Forms 4.8.0.1821
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Professional 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA605
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.2.231
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```

</details>

### Workaround

Would be nice if some workaround would be provided until the bug is fixed. Maybe there is some property indicating that WebView is off-screen and EvaluateJavascriptAsync should not be called.

**Comment by rachelkang** [comment]
Hi, @ossaltu - thanks for submitting this issue! I'm unclear on how exactly you might be using WebView in your project, and not sure what `browser` is referring to given the code you shared. Would you mind sharing your project or a sample project so that we can take a closer look at what might be happening?

**Comment by ossaltu** [comment]
Hi, I've uploaded whole project here:
[https://1drv.ms/u/s!AuXjDEud3CasgbdFkDSPro-lJqrfnA?e=eSugeN](https://1drv.ms/u/s!AuXjDEud3CasgbdFkDSPro-lJqrfnA?e=eSugeN)
check App9\Views\ItemsPage.xaml.cs file for the example. When launched, it should be easy to reproduce the exception.

**Comment by ossaltu** [comment]
PS. is there any possibility to find that WebView is out of view and EvaluateJavaScriptAsync should not be called?

**Comment by jsuarezruiz** [comment]
@ossaltu Thanks for the sample. I have tried to reproduce the issue but without success. Happens in any specific version or device?. Tested with Pixel 2 API Level 29 and 30 emulators.

You can verify that the tab with the WebView is selected.

**Comment by ossaltu** [comment]
You should place a break point in line 23 of ItemsPage.xaml.cs, otherwise the exception will get swallowed - it's thrown in fire-and-forget background process.

**Comment by PureWeen** [comment]
Yea line 107 on the WebView 

```C#
var result = await handler?.Invoke(script);
```

You can't do that :-)

**Comment by captainjono** [comment]
Im repo'ing this on iOS

**Comment by tpitman** [comment]
I am running into this bug myself. Until it is fixed is there some work around I can do in my code to check something before I call EvaluateJavaScriptAsync in the first place?

**Comment by captainjono** [comment]
@tpitman u will need some kind of sync event like page-load started as a gate to when u executescript. 

ive also used a custom renderer to hook into the native webview's API in cases where i need run a script onstartup in a reliable way.

**Comment by tpitman** [comment]
Thank you for your reply. I am actually doing this. I have a custom renderer and am not doing any script processing until after that. I suspect I might be encountering this when I am trying to dispose of the webview, so not sure how to handle that. I have put guards in place as much as possible.

Is there something exposed that I can check right before doing a script execute?

**Comment by tpitman** [comment]
I have not seen much movement in the 5.0.0 SR 4 planning board lately. Does that mean the devs are head down hard at work on it? :-)

**Comment by jfversluis** [comment]
@ossaltu @tpitman @shameem-pp, a PR for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by jfversluis** [comment]
@tpitman 

> I have not seen much movement in the 5.0.0 SR 4 planning board lately. Does that mean the devs are head down hard at work on it? :-)

See here for a lot of context: #14205

Let me know if there are any questions!
