### ISSUE TITLE
Entry Text color is not changed when IsEnabled set to false

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#13321]
### Description

https://github.com/xamarin/Xamarin.Forms/issues/7119

In my scenario I am not using Xaml part, Entry is added in code behind only. I need to change Entry Text color when IsEnabled is False, also I need all the behaviors when IsEnabled is False like restriction of touch, focus and editing of entry.

### Expected Behavior

Required to change TextColor for Entry when IsEnabled is False.

### Actual Behavior

TextColor changes as gray, given text color is not applied.

### Basic Information

Version with issue: 4.5.0.617
IDE: VS 2017
Platform Target Frameworks:
iOS: 11
Android: Android 8.1
UWP: Windows 10 version 1809

### Screenshots

![entry](https://user-images.githubusercontent.com/39787321/103880202-d1667480-50fe-11eb-8860-2449dda55f83.png)

### Workaround

`            var stackLayout = new StackLayout();`
`            stackLayout.Children.Add(new Entry()`            
`            {`
`                Text = "Hello",`
`                IsEnabled = false,`
`                TextColor = Color.Red,`
`            });`
`            this.Content = stackLayout;`

Could you please provide a solution for this?

**Comment by hartez** [comment]
From your comments on the other linked issue, I gather you want a code (non-XAML) solution for this?

It would look something like this, where `AnEntry` is the Entry for which you want to set up visual states:

```
var commonStates = new VisualStateGroup { Name = "CommonStates", TargetType = typeof(Entry) };

var normal = new VisualState() { Name = VisualStateManager.CommonStates.Normal, TargetType = typeof(Entry) };
commonStates.States.Add(normal);
			
var disabled = new VisualState { Name = VisualStateManager.CommonStates.Disabled, TargetType = typeof(Entry) };
var textColorSetter = new Setter { Value = Color.Red, Property = Entry.TextColorProperty };
disabled.Setters.Add(textColorSetter);

commonStates.States.Add(disabled);

VisualStateManager.SetVisualStateGroups(AnEntry, new VisualStateGroupList { commonStates });
```

**Comment by Ganeshamoorthy10** [comment]
Hi @hartez ,

Thanks for the solution. Its working perfectly in Xamarin Forms Android and iOS, but in UWP its not working. Could you please check on this?

[Uploading SampleProject.zip…]()
