### ISSUE TITLE
[Bug] [Shell] [XF5.0.0] Unable to navigate using PopAsync on Shell

### ISSUE THREAD

**Issue by elicul** [xamarin/Xamarin.Forms#13328]
### Description
Unable to navigate back using ```Shell.Current.Navigation.PopAsync()``` on third child Shell page ```MainPage/FirstPage/SecondPage/ThirdPage```. I'm not sure if this is a bug or if it's designed to work like that.

### Steps to Reproduce

1. Start the application
2. Click on "Click Me!" buttons 3 times until you get a page with a label displaying "Third Page"
3. Use the mobile hardware back button to go back 

### Expected Behavior
* User is navigated back to the "Second Page"

### Actual Behavior
* User is unable to go back

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.1874
- Last known good version: Xamarin.Forms 4.8.0 (Latest)
- Platform Target Frameworks: 
  - Android: 11 
- NuGet Packages: Xamarin.Essentials 1.6.0
- Affected Devices: Samsung Galaxy S9+ SM-G965F (Android 10)

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio: Visual Studio Professional 2019 16.8.3
```

</details>

### Reproduction Link

https://github.com/elicul/XamarinPopAsyncBug/tree/master

### Workaround

* Use ```Shell.Current.Navigation.RemovePage(Shell.Current.Navigation.NavigationStack.LastOrDefault());``` to remove the last page

**Comment by PureWeen** [comment]
@elicul This seems to be an issue related to specifying "uri's" with multiple paths

Another workaround here is to register each pages like so
```C#

            routes.Add(nameof(FirstPage), typeof(FirstPage));
            routes.Add($"{nameof(SecondPage)}", typeof(SecondPage));
            routes.Add($"{nameof(ThirdPage)}", typeof(ThirdPage));
```

and then navigate like this

```C#

            await Shell.Current.GoToAsync($"{nameof(ThirdPage)}");
```

**Comment by elicul** [comment]
@PureWeen thank you for the quick response. I'll be using your workaround.
