### ISSUE TITLE
[Bug] DatePicker style in Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by ColeXm** [xamarin/Xamarin.Forms#13331]
### Description

The style of DatePicker  looks strange after upgrading XF to 5.x , I have to click the inner text to show the datepicker panel , is this a bug or by design ? 
I tried to use custom renderer(DatePickerRenderer) to revert the style as wheel like before , but it seems hard to implement it . 

### Steps to Reproduce

![111221](https://user-images.githubusercontent.com/2161256/103969739-91a49900-51a1-11eb-8908-7b9b25f6d42e.gif)

**Comment by hartez** [comment]
Nope, that's a bug. It should be displaying the wheels version.

**Comment by hartez** [comment]
TimePicker will also have this problem.
