### ISSUE TITLE
[Bug] Should FlexLayout.Direction take into account the FlowDirection?

### ISSUE THREAD

**Issue by sjorsmiltenburg** [xamarin/Xamarin.Forms#13336]
### Description

The FlexLayout has the property Direction with values Row and RowReverse.

Is it a bug that these values result in the same layout regardless of the FlowDirection (LeftToRight or LeftToRight) or is this a bug?

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @sjorsmiltenburg - thanks for submitting this issue. It seems we have a parallel discussion at #3954 so I will be closing this issue, but please feel free to share your thoughts on that thread!
