### ISSUE TITLE
Apple CarPlay and Android Auto

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#13339]
Hi

please add a feature to develop apps which will work on Apple CarPlay and Android Auto

hope this will be available in Xamarin Fos 5.x

Thanks
Jassim

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by christian-strydom** [comment]
Hi jrahma, it is already possible to develop Android Auto and Apple CarPlay apps with Xamarin. I'm creating a [YouTube series](https://youtu.be/nNkVxegb2oU) on how to implement Android Auto and Apple CarPlay apps on .Net Maui, but the process is very similar for Xamarin. The Apple CarPlay video will be up in the next few months.

**Comment by jrahma** [comment]
This is awesome 

I would love to see the MAUI video....

Thank you so much for the great help

**Comment by christian-strydom** [comment]
The Apple CarPlay tutorial for .NET MAUI is now live as well, you can find it [here](https://youtu.be/Yg2I6NbHZp8).
I've added both parts (Android Auto and Apple CarPlay) to the following [playlist ](https://youtube.com/playlist?list=PL0jJqThQHxikbetR1ODplARyLG6YAPKlz)for convenience.
