### ISSUE TITLE
[Bug] Xamarin Searchbar and Xamarin Essentials conflict. 

### ISSUE THREAD

**Issue by Noel-F-Downs** [xamarin/Xamarin.Forms#13332]
I am new to visual studio and Xamarin... I am trying to replicate an iOS app I have written and was having trouble getting the search bar to display in Xamarin forms, in a very simple map project.  So started from scratch and had the map and search bar both showing in the project.    
 
### Description

when I add Xamarin essentials or Xamarin essentials geolocation to the project the search bar disappears.    

### Steps to Reproduce

1. xaml page Code

<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Xamarin.Forms.Maps;assembly=Xamarin.Forms.Maps"
             x:Class="IndigenousPlaceNames.Views.MapPage">

    <ContentPage.ToolbarItems>

        <ToolbarItem IconImageSource="layers.png"
                     Clicked="Add_Layer_ToolbarItem_Clicked"
                     Order="Primary"
                     Priority="0"
                     />

        <ToolbarItem IconImageSource="satelliteicon.png"
                     Clicked="Map_Type_ToolbarItem_Clicked"
                     Order="Primary"
                     Priority="0" />
       
        <ToolbarItem IconImageSource="menu.png"
                     Clicked="Menu_ToolbarItem_Clicked"
                     Order="Primary"
                     Priority="0" />

        <ToolbarItem IconImageSource="search.png"
                     Clicked="Search_ToolbarItem_Clicked"
                     Order="Primary"
                     Priority="0"/>
    </ContentPage.ToolbarItems>

    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition Height="30"/>
            <RowDefinition/>
            </Grid.RowDefinitions>
           

    <SearchBar Grid.Row="0"
               Placeholder="Search items..."
               CancelButtonColor="Orange"
               PlaceholderColor="Orange"
               TextColor="Orange"
               TextTransform="Lowercase"
               HorizontalTextAlignment="Center"
               FontSize="Micro"
               FontAttributes="Italic"
               HeightRequest="30"/>

       
        <maps:Map Grid.Row="1"
                  x:Name="map"
                  HorizontalOptions="Fill"
                  VerticalOptions="Fill"
                  />
  </Grid>
</ContentPage>

2.  when I add this function to the xaml.cs file
 async void FindMe()
        {
            SearchState = "FindMe";
            Position position;
            var location = await Xamarin.Essentials.Geolocation.GetLastKnownLocationAsync();

            if (location != null)
            {
                position = new Position(location.Latitude, location.Longitude);

            }
            else
            {
                position = new Position(-30.59814576, 150.4971203);

            }

            MapSpan mapSpan = new MapSpan(position, 0.20, 0.20);
            map.MoveToRegion(mapSpan);
            Content = map;

        }//end find me

3. 

### Expected Behavior

should display the map, nav bar, search bar and zoom to user location.

### Actual Behavior

displays the map, nav bar, and zooms to user location.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by themronion** [comment]
@Noel-F-Downs the problem is on ur code. In this line 
```
 Content = map;
 ```
 You are setting the map as a content of your page thus instead of a grid your page will have a Map (logically the search bar dissapers cause it is the grid). Change your code, issue can be closed
