### ISSUE TITLE
[Enhancement] Add Flyout Title when FlyoutDisplayOptions="AsMultipleItems" is set.

### ISSUE THREAD

**Issue by cmhofmeister** [xamarin/Xamarin.Forms#13343]
## Summary
When grouping flyout times in a menu, it would be nice if the "Title" property (already present) was used as a header/title for the items underneath it.

## API Changes
The Title field is already present in the API, it is not used when FlyoutDisplayOptions="AsMultipleItems" is set.
```
<FlyoutItem FlyoutDisplayOptions="AsMultipleItems" **Title="MyTitle"** IsTabStop="False">
        <ShellContent Title="About" Icon="icon_about.png" Route="AboutPage" ContentTemplate="{DataTemplate local:AboutPage}" IsTabStop="False"/>
        <ShellContent  Title="Browse" Icon="icon_feed.png" Route="ItemsPage" ContentTemplate="{DataTemplate local:ItemsPage}" IsTabStop="False" />
    </FlyoutItem>
```
## Intended Use Case
The flyout menu can be complicated to look at when there are alot of items.  Being able to group them with a header would be ideal.  In the image below adding "MyTitle" to the grouping would make finding a menu item faster and easier.  My online banking app uses such an approach.

![image](https://user-images.githubusercontent.com/34583987/104049600-db45b180-51aa-11eb-81de-a3d2510f7242.png)

**Comment by davidbuckleyni** [comment]
This would go hand in hand https://github.com/xamarin/Xamarin.Forms/issues/13274

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
