### ISSUE TITLE
[Bug] Line's Stroke and Rectangle's Fill doesn't rendered as expected with SolidColorBrush while changing the system's appearance.

### ISSUE THREAD

**Issue by sthch** [xamarin/Xamarin.Forms#13359]
### Description
Related issue: #13173 

### Steps to Reproduce
See the reference issue.
Same problem still occurs on the latest 5.0 version.

### Basic Information
- Version with issue: 5.0
- Platform Target Frameworks: 
  - iOS:  14.3
  - Android: 11

### Workaround
May be fixed by #13181

**Comment by jsuarezruiz** [comment]
Thanks for the feedback. It seems that #13181 will fix the issue. However, if you have a small example where reproduce the issue I can validate if it is exactly the same.
