### ISSUE TITLE
Xamarin forms responding to system theme change even after setting UserAppTheme.

### ISSUE THREAD

**Issue by samir-dahal** [xamarin/Xamarin.Forms#13353]
### Steps to Reproduce

1. Create a blank xamarin forms application
2. Set: App.Current.UserAppTheme = OSAppTheme.Light; in App.xaml.cs constructor, after initializecomponent.
3.  Run the application in dark model.
### Expected Behavior
Should be the theme specified by the user and doesn't repond to OS.
### Actual Behavior
Responding to OS
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @samir-dahal - thank you for submitting this issue.

I wasn't able to reproduce this issue - if you haven't already, please update to the most recent version of XF 5.0 and let us know if you're still having issues! If so, could you run this sample and let me know what Android devices/versions you're observing this behavior on? Thanks :)

[Issue13353.zip](https://github.com/xamarin/Xamarin.Forms/files/5912902/Issue13353.zip)

**Comment by PureWeen** [comment]
Closing for now since we haven't heard from you. If you can respond to @rachelkang 's question we will re-open
