### ISSUE TITLE
Xamarin.Forms DatePicker shows incorrect date

### ISSUE THREAD

**Issue by mikebikerider** [xamarin/Xamarin.Forms#13366]
### Steps to Reproduce in the Western Hemisphere

1. Download the Xamarin DatePicker sample app 'Days Between Dates' and compile the iOS project.
2. Run the app at the time when UTC Date is 1 day ahead of the local date. In the UTC - 5 time zone (EST US, Canada) that is after 19:00 
3. Look at the DatePicker - the date is one day behind of the local date. Tap the DatePicker to bring up the native iOS control. It shows the correct date. Select another date and click 'Done'. The date shown in the DatePicker is again 1 day behind. 

### Basic Information

- Version with issue: 5.0.0.1874
- Last known good version: 4.8.0.1821
- Platform Target Frameworks: 
  - iOS: 14.3 
  - Android: not affected 

 
  - UWP:  not relevant 
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms
- Affected Devices: iPhone, iPad, simulator

### Environment Visual Studio 2019 16.8.3

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Reproduction Link ![IMG_0508](https://user-images.githubusercontent.com/19241066/104212116-d8dd9480-5402-11eb-8664-0f4ded9db997.PNG)

The screenshot made on January 8 at 19:02 EST (US, Canada)  shows date January 7, 2021.
Is should show  Friday, January 8, 2021.
A screenshot made same day before 19:00 shows correct date January 8, 2021 in wrong format.
The app is not mine. It is the Xamarin.Forms sample up downloaded from the GitHub one day after it was updated to Xamarin.Forms 5.0.0.1874. Downgrading to Xamarin.Forms to 4.8.0.1821 and running the app produced correct date in correct format "D". "D" is the default.  
### Workaround

Set DatePicker IsVisible = False;
In XAML or in code place a Label into the same position (grid cell) as the DatePicker.
In DatePicker.DateSelected add code to set  label text to e.NewDate.ToString("D") or whatever date format you chose.
For the label add TapGestureRecognizer that will call DatePicker.Focus()

**Comment by mikebikerider** [comment]
Comparing DatePickerRenderer.cs for Xamarin.Forms 4.8 and 5.0 makes me think both issues - missing Day of Week for date format "D" and wrong date are caused by changes in UpdateDateFromModel(bool animate)
both start with:
			if (_picker.Date.ToDateTime().Date != Element.Date.Date)
				_picker.SetDate(Element.Date.ToNSDate(), animate);
In 4.8 
 Control.Text = Element.Date.ToString(Element.Format);
In 5.0
				NSDateFormatter dateFormatter = new NSDateFormatter();
				if (Element.Format?.Equals("D") == true)
				{
					dateFormatter.DateStyle = NSDateFormatterStyle.Long;
					var strDate = dateFormatter.StringFor(_picker.Date);
					Control.Text = strDate;
				}

iOS date format long has no Day of Week.
Could be calling NSDateFormatter shifts displayed date by one day when local date is behind or ahead of the UTC date?

**Comment by educatedcg** [comment]
I agree this seems like a bug.. Perfectly working datetime picker no longer picks the correct date. 
If you look at the binding property:
<DatePicker x:Name="EndDate" Date="{Binding SelectedEndDate}" />
 {1/31/2021 12:00:00 AM} - making matters worse, you can't even select the end of the month unless you select the first day of the next month.. It's always off by a day... Maybe the 12AM portion??

**Comment by mikebikerider** [comment]
No, not the 12 AM portion. The underlying iOS DatePicker works correctly and always shows the correct date. The date is pushed 1 day back when control on the page is updated. Date is pushed 1 day back if you are in the Western hemisphere, I am. If I fly to the UTC + zone it would be 1 day ahead at least some hours of the day. It can be quite confusing.
The workaround I suggested is simple. The permanently displayed part of the DatePicker is just a label. Put your own label on top of it and make DatePicker not visible. Update your label in DatePicker.DateSelected event handler, and add TapGestureRecognizer for the label to focus the underlying iOS DatePicker. Look up the original post.
Of course it has to be fixed.
I still will keep my workaround because it gives me more control and better look.

**Comment by hoangwy** [comment]
Same here
![Simulator Screen Shot - iPhone 12 - 2021-01-19 at 18 07 03](https://user-images.githubusercontent.com/3329721/105117321-28663500-5a81-11eb-839d-47374294d3d3.png)
As you can see
The Wheel shows January 19, 2021 but the label shows 1/18/21

**Comment by danielkboyer** [comment]
I am getting the same issue, this is frustrating, a working build is now halted because of this. @mikebikerider solution works, it's just a pain to implement this anywhere I have a DatePicker. Is there a fix that does not require creating a label over it?

**Comment by educatedcg** [comment]
It's crazy that no one is picking this bug up. It's a fundamental breaking bug. If no one picks it up, one of us will have to fix it. I had to revert my app to 4.8, because this make 5.0 unusable for me on iOS.

**Comment by PureWeen** [comment]
I waited all day to test this issue and from what I can tell this is fixed with the latest SR1 of Xamarin.Forms

I'm closing this for now. If you still have an issue with the latest 5.0 release of Forms let me know and we can re-open

**Comment by PureWeen** [comment]
@rachelkang is still seeing this issue where she's at in the world so going to re-open for now :-/

**Comment by mikebikerider** [comment]
The issue has to be caused by changes in DatePickerRendererBase.UpdateDateFromModel(bool animate) from Xamarin.Forms 4.8 to 5.0.
A second work around could be custom renderer overriding OnElementChanged() and OnElementPropertyChanged().
As an extra bonus you can pick a desired DatePicker style - Default, Wheels, Compact for iOS 13.4 and higher.

using YourAppName.iOS.Renderers;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;
using UIKit;
using System.ComponentModel;

[assembly: ExportRenderer(typeof(DatePicker), typeof(MyDatePickerRenderer))]
namespace YourAppName.iOS.Renderers
{
    public class MyDatePickerRenderer : DatePickerRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null && this.Control != null)
            {
                try
                {
                    UIDatePicker picker = (UIDatePicker)Control.InputView;
                    if (UIDevice.CurrentDevice.CheckSystemVersion(13, 4))
                    {
                        //select desired style
                        picker.PreferredDatePickerStyle = UIDatePickerStyle.Automatic;
                    }
                    UpdateDateFromModel(picker, false);

                }
                catch
                {
                    // do nothing
                }
            }
        }
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
            try
            {
                try
                {
                    UIDatePicker picker = (UIDatePicker)Control.InputView;
                    UpdateDateFromModel(picker, true);

                }
                catch
                {
                    // do nothing
                }
            }
            catch { }
        }
        private void UpdateDateFromModel(UIDatePicker picker, bool animate)
        {
            if (picker.Date.ToDateTime().Date != Element.Date.Date)
                picker.SetDate(Element.Date.ToNSDate(), animate);
            Control.Text = Element.Date.ToString(Element.Format);
        }
    }
}

UpdateDateFromModel()  - I pasted from the 4.8 DatePickerRendererBase

**Comment by Westat-Transportation** [comment]
For the record I am also seeing this issue in 4.8.0.1269.

**Comment by tommy-elliott-awh** [comment]
I have experienced this issue emulating in iOS on iPhone 12 iOS 14.3 on 1/27/21 in EST for the full duration between 11:40am EST and 5pm EST on Xamarin Forms 5 in VS 2019 v16.8.4 in Windows, connected to a Mac mini build agent with the latest Xcode 12.  After applying the workaround steps in @mikebikerider 's workaround, the issue was resolved.

**Comment by PureWeen** [comment]
If anyone having this issue can test with the following nugets and let us know if it's resolved that would be helpful

https://dev.azure.com/xamarin/public/_build/results?buildId=34568&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by mikebikerider** [comment]
Xamarin.Forms build 5.0.0.6978 fixes the incorrect date issue.

Prior to installing the new nuget - the date shown in the date picker  (DarkSlateGray background)  was 1 day behind the date shown in the label above the date picker.
The date picker format is "D". The date shown in the date picker control is not format "D". The label above the date picker has date format "D".
The date picker does not show the Day of Week.

[cid:image002.png@01D6FB57.219E7E50]

Build 5.0.0.6978 shows correct date. The date, date format is not "D"

[cid:image004.png@01D6FB57.219E7E50]


Build 5.0.0.6978 opens date picker with old style 'Wheels'. This begs a question what was the point tinkering with the date picker, adding a date bug, and screwing up date format, while keeping the deprecated look and feel? Xamarin.Forms 4.8 and prior show the same older 'Wheels' style date picker, and render the date format "D" correctly.

The date picker style can be selected via custom renderer. Date Picker iOS - specific option would be a more graceful solution.
At this point, grace is not an option.
The Compact (Automatic) style looks odd, Inline not usable.
This is what inline looks like 5.0.0.6978

[cid:image008.png@01D6FB57.219E7E50]

The top of the date picker is cut off.

Conclusion:
The bigger issue, wrong date, seems to be fixed. I'd be more confident taking a look at the DatePicker renderer code.
Two remaining issues:
Date format "D" is not rendered correctly. I have pretty good idea why. iOS dateFormatter.DateStyle.Long is different from .NET "D". The below code from DatePicker.Renderer. UpdateDateFromModel() looks odd and produces odd result.

                                                                if (Element.Format?.Equals("D") == true)
                                                                {
                                                                                dateFormatter.DateStyle = NSDateFormatterStyle.Long;
                                                                                var strDate = dateFormatter.StringFor(_picker.Date);
                                                                                Control.Text = strDate;
                                                                }
If I select "D" in XAML or code I expect the date starting with the Day of Week.
I also expect the iOS and Android versions of my apps have similar look and feel. The  Android date picker with Format="D" shows the date starting with the day of week. The iOS date picker does not show day of week.
It is not such a big deal as I can easily work around via custom renderer, or by placing a label on top of the date picker and displaying the date the way I please.

Date picker Inline style is unusable.
The Compact style has odd look and feel.
My guess is that was the reason for reverting from 'Automatic' in the initial 5.0 release to 'Wheels' in later builds.
In production versions of my iOS apps I kept the Compact (Automatic) style via custom renderer despite the odd look and feel. Not as odd as having to look up someplace else for the day of week.

Michael Rubinstein (mikerider)

**Comment by educatedcg** [comment]
Did this make it into a nightly build? Tried 5.0.1.1876 - nightly build and saw the same effect with that binds a additional datefield to the selected date value

**Comment by tommy-elliott-awh** [comment]
@educatedcg It looks like @mikebikerider said
>Xamarin.Forms build 5.0.0.6978 fixes the incorrect date issue.

which isn't in a nuget release yet, so I'm applying the workaround within the custom iOS renderer until it is available from nuget, and I would suggest you do the same.
