### ISSUE TITLE
[Bug] Android ShellFlyoutRecyclerAdapter System.RankException

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#13362]
### **Description**
System.RankException observed in Xamarin.Android/Xamarin.Forms code in the wild.
This erros happens on Xamarin.Forms.Platform.Android\Renderers\ShellFlyoutRecyclerAdapter.cs -> OnBindViewHolder(RecyclerView.ViewHolder holder, int position)

```
		public override void OnBindViewHolder(RecyclerView.ViewHolder holder, int position)
		{
			var item = _listItems[position];
			var elementHolder = (ElementViewHolder)holder;

			elementHolder.Bar.Visibility = item.DrawTopLine ? ViewStates.Visible : ViewStates.Gone;
			elementHolder.Element = item.Element; //<- Here
		}
```
### Stack trace:

```
Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length)
List`1[T].set_Capacity (System.Int32 value)
List`1[T].EnsureCapacity (System.Int32 min)
List`1[T].AddWithResize (T item)
IElement.AddResourcesChangedListener (System.Action`2[T1,T2] onchanged)
Element.set_Parent (Xamarin.Forms.Element value)
ShellFlyoutRecyclerAdapter+ElementViewHolder.set_Element (Xamarin.Forms.Element value)
ShellFlyoutRecyclerAdapter.OnBindViewHolder (AndroidX.RecyclerView.Widget.RecyclerView+ViewHolder holder, System.Int32 position)
RecyclerView+Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_holder, System.Int32 position)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.52(intptr,intptr,intptr,int)

```

### Steps to Reproduce
Unknown

### Expected Behavior
No crash

### Actual Behavior
Array.Copy (System.Array sourceArray, System.Int32 sourceIndex, System.Array destinationArray, System.Int32 destinationIndex, System.Int32 length)
System.RankException: Only single dimension arrays are supported here.

### Basic Information
Version with issue: 5.0.0.1874
Last known good version: n/a
IDE: VS 2019 16.8.3
Platform Target Frameworks:
iOS: -
Android: API Level 29 Q
UWP: -
Android Support Library Version:
Nuget Packages:
Affected Devices: moto g6 play, Galaxy J2 Core, moto e6s

### Reproduction Link
This has been observed via AppCenter and is demonstrably rare. Thus, I have no reproduction.

**Comment by transis2** [comment]
![image](https://user-images.githubusercontent.com/4941173/104186166-cd836c80-53f4-11eb-8fe9-519d2ceb6439.png)

**Comment by PureWeen** [comment]
@transis2 can you post your AppShell file here? And/or any customizations/styles/etc... that you apply?

**Comment by jsuarezruiz** [comment]
@transis2 Could you attach a sample where reproduce the issue or more info (AppShell file)?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
