### ISSUE TITLE
[Bug] [Android] Font asset not found normal 

### ISSUE THREAD

**Issue by mhughey-vent** [xamarin/Xamarin.Forms#13372]
### Description

After I build my android project, and run it, I get the "Font asset not found normal" exception.

The exception is occurring at the line of code were I'm assigning the MainPage property of Application.

I dug a little into the error, and here is the stack trace:

at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <89755ea61d9c4ae0a40ce90b872c9e2d>:0 
  at **Android.Graphics.Typeface.CreateFromAsset** (Android.Content.Res.AssetManager mgr, System.String path) [0x0004b] in <2df86f44c8e946618f31cb3aed952f5b>:0 
  at **Xamarin.Forms.Platform.Android.FontExtensions.LoadTypefaceFromAsset** (System.String fontfamily) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\FontExtensions.cs:121 
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found normal
	at android.graphics.Typeface.createFromAsset(Typeface.java:839)
	at crc643f46942d9dd1fff9.FormsAppCompatActivity.n_onStart(Native Method)
	at crc643f46942d9dd1fff9.FormsAppCompatActivity.onStart(FormsAppCompatActivity.java:120)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
	at android.app.Activity.performStart(Activity.java:7157)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Seems like Xamarin.Forms.Platform.Android.FontExtensions.LoadTypefaceFromAsset is being called from somewhere, which in turns calls Android.Graphics.Typeface.CreateFromAsset method which generates the error because the font it is looking for doesn't exist. 

I don't use any custom fonts whatsoever, so I don't understand why the error is being generated

### Steps to Reproduce

1. Just started happening
2. 
3. 

### Expected Behavior

Run with no exceptions

### Actual Behavior

Generating a "Font asset not found normal" exception

### Basic Information

- Version with issue: I was using Visual Studio 16.3.3 for Windows and was getting the issue, and after researching online, I upgraded to latest Visual Studio 16.8.3, since everything I read said the issue was fixed. I'm still getting the error in the latest upgrade
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  N/A ( yet)
  - Android: **9.0** (Pie) 
  - UWP:  N/A (yet) 
- Android Support Library / AndroidX Version: 
- NuGet Packages:
   Autofac  version="3.5.2  targetFramework="monoandroid90  
  CommonServiceLocator  version="2.0.4  targetFramework="monoandroid90  
  ExifLib.PCL  version="1.0.1  targetFramework="monoandroid90  
  FastAndroidCamera  version="2.0.0  targetFramework="monoandroid90  
  Fody  version="2.1.0  targetFramework="monoandroid90  developmentDependency="true  
  Microsoft.AppCenter  version="3.4.0  targetFramework="monoandroid90  
  Microsoft.AppCenter.Analytics  version="3.4.0  targetFramework="monoandroid90  
  Microsoft.AppCenter.Crashes  version="3.4.0  targetFramework="monoandroid90  
  Microsoft.CSharp  version="4.5.0  targetFramework="monoandroid90  
  Microsoft.Net.Compilers.Toolset  version="3.1.0  targetFramework="monoandroid90  developmentDependency="true  
  Microsoft.NETCore.Platforms  version="2.2.2  targetFramework="monoandroid90  
  Microsoft.NETCore.Targets  version="2.1.0  targetFramework="monoandroid90  
  Microsoft.Win32.Primitives  version="4.3.0  targetFramework="monoandroid90  
  modernhttpclient  version="2.4.2  targetFramework="monoandroid90  
  MvvmLightLibs  version="5.4.1.1  targetFramework="monoandroid90  
  NETStandard.Library  version="2.0.3  targetFramework="monoandroid90  
  Newtonsoft.Json  version="12.0.3  targetFramework="monoandroid90  
  NLog  version="4.3.8  targetFramework="monoandroid90  
  NodaTime  version="1.3.4  targetFramework="monoandroid90  
  PCLCrypto  version="2.0.147  targetFramework="monoandroid90  
  PCLStorage  version="1.0.2  targetFramework="monoandroid90  
  PdfSharp.Xamarin.Forms  version="1.0.0  targetFramework="monoandroid90  
  PdfSharpCore  version="1.1.23  targetFramework="monoandroid90  
  PInvoke.BCrypt  version="0.5.184  targetFramework="monoandroid90  
  PInvoke.Kernel32  version="0.5.184  targetFramework="monoandroid90  
  PInvoke.NCrypt  version="0.5.184  targetFramework="monoandroid90  
  PInvoke.Windows.Core  version="0.5.184  targetFramework="monoandroid90  
  Plugin.CurrentActivity  version="2.1.0.4  targetFramework="monoandroid90  
  Plugin.Permissions  version="3.0.0.12  targetFramework="monoandroid90  
  PropertyChanged.Fody  version="2.1.1  targetFramework="monoandroid90  developmentDependency="true  
  Rg.Plugins.Popup  version="1.1.5.188  targetFramework="monoandroid90  
  runtime.native.System  version="4.3.1  targetFramework="monoandroid90  
  Serilog  version="2.8.0  targetFramework="monoandroid90  
  Serilog.Enrichers.Thread  version="3.1.0  targetFramework="monoandroid90  
  Serilog.Sinks.Xamarin  version="0.1.25  targetFramework="monoandroid90  
  SixLabors.Core  version="1.0.0-beta0008  targetFramework="monoandroid90  
  SixLabors.Fonts  version="1.0.0-beta0009  targetFramework="monoandroid90  
  SixLabors.ImageSharp  version="1.0.0-beta0007  targetFramework="monoandroid90  
  SixLabors.ImageSharp.Drawing  version="1.0.0-beta0007  targetFramework="monoandroid90  
  SixLabors.Shapes  version="1.0.0-beta0009  targetFramework="monoandroid90  
  sqlite-net-base  version="1.6.292  targetFramework="monoandroid90  
  sqlite-net-pcl  version="1.2.1  targetFramework="monoandroid90  
  sqlite-net-sqlcipher  version="1.6.292  targetFramework="monoandroid90  
  SQLitePCLRaw.bundle_green  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.bundle_sqlcipher  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.core  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.lib.e_sqlite3.android  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.lib.sqlcipher.android  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.provider.e_sqlite3.android  version="1.1.14  targetFramework="monoandroid90  
  SQLitePCLRaw.provider.sqlcipher.android  version="1.1.14  targetFramework="monoandroid90  
  System.AppContext  version="4.3.0  targetFramework="monoandroid90  
  System.Buffers  version="4.4.0  targetFramework="monoandroid90  
  System.Collections  version="4.3.0  targetFramework="monoandroid90  
  System.Collections.Concurrent  version="4.3.0  targetFramework="monoandroid90  
  System.Collections.NonGeneric  version="4.3.0  targetFramework="monoandroid90  
  System.Console  version="4.3.0  targetFramework="monoandroid90  
  System.Diagnostics.Debug  version="4.3.0  targetFramework="monoandroid90  
  System.Diagnostics.Tools  version="4.3.0  targetFramework="monoandroid90  
  System.Diagnostics.Tracing  version="4.3.0  targetFramework="monoandroid90  
  System.Dynamic.Runtime  version="4.0.11  targetFramework="monoandroid90  
  System.Globalization  version="4.3.0  targetFramework="monoandroid90  
  System.Globalization.Calendars  version="4.3.0  targetFramework="monoandroid90  
  System.IO  version="4.3.0  targetFramework="monoandroid90  
  System.IO.Compression  version="4.3.0  targetFramework="monoandroid90  
  System.IO.Compression.ZipFile  version="4.3.0  targetFramework="monoandroid90  
  System.IO.FileSystem  version="4.3.0  targetFramework="monoandroid90  
  System.IO.FileSystem.Primitives  version="4.3.0  targetFramework="monoandroid90  
  System.Linq  version="4.3.0  targetFramework="monoandroid90  
  System.Linq.Expressions  version="4.3.0  targetFramework="monoandroid90  
  System.Memory  version="4.5.1  targetFramework="monoandroid90  
  System.Net.Http  version="4.3.4  targetFramework="monoandroid90  
  System.Net.Primitives  version="4.3.1  targetFramework="monoandroid90  
  System.Net.Sockets  version="4.3.0  targetFramework="monoandroid90  
  System.Numerics.Vectors  version="4.5.0  targetFramework="monoandroid90  
  System.ObjectModel  version="4.3.0  targetFramework="monoandroid90  
  System.Reflection  version="4.3.0  targetFramework="monoandroid90  
  System.Reflection.Extensions  version="4.3.0  targetFramework="monoandroid90  
  System.Reflection.Primitives  version="4.3.0  targetFramework="monoandroid90  
  System.Resources.ResourceManager  version="4.3.0  targetFramework="monoandroid90  
  System.Runtime  version="4.3.1  targetFramework="monoandroid90  
  System.Runtime.CompilerServices.Unsafe  version="4.5.1  targetFramework="monoandroid90  
  System.Runtime.Extensions  version="4.3.1  targetFramework="monoandroid90  
  System.Runtime.Handles  version="4.3.0  targetFramework="monoandroid90  
  System.Runtime.InteropServices  version="4.3.0  targetFramework="monoandroid90  
  System.Runtime.InteropServices.RuntimeInformation  version="4.3.0  targetFramework="monoandroid90  
  System.Runtime.Numerics  version="4.3.0  targetFramework="monoandroid90  
  System.Runtime.Serialization.Primitives  version="4.0.0  targetFramework="monoandroid90  
  System.Security.Cryptography.Algorithms  version="4.3.0  targetFramework="monoandroid90  
  System.Security.Cryptography.Encoding  version="4.3.0  targetFramework="monoandroid90  
  System.Security.Cryptography.Primitives  version="4.3.0  targetFramework="monoandroid90  
  System.Security.Cryptography.X509Certificates  version="4.3.0  targetFramework="monoandroid90  
  System.Text.Encoding  version="4.3.0  targetFramework="monoandroid90  
  System.Text.Encoding.Extensions  version="4.3.0  targetFramework="monoandroid90  
  System.Text.RegularExpressions  version="4.3.1  targetFramework="monoandroid90  
  System.Threading  version="4.3.0  targetFramework="monoandroid90  
  System.Threading.Tasks  version="4.3.0  targetFramework="monoandroid90  
  System.Threading.Timer  version="4.3.0  targetFramework="monoandroid90  
  System.Xml.ReaderWriter  version="4.3.1  targetFramework="monoandroid90  
  System.Xml.XDocument  version="4.3.0  targetFramework="monoandroid90  
  Validation  version="2.4.22  targetFramework="monoandroid90  
  Xam.Plugin.Geolocator  version="4.5.0.6  targetFramework="monoandroid90  
  Xam.Plugin.Media  version="4.0.1.5  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Core.Common  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Core.Runtime  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Lifecycle.Common  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Lifecycle.LiveData  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Lifecycle.LiveData.Core  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Lifecycle.Runtime  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Arch.Lifecycle.ViewModel  version="1.1.1.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Animated.Vector.Drawable  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Annotations  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.AsyncLayoutInflater  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Collections  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Compat  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.CoordinaterLayout  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Core.UI  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Core.Utils  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.CursorAdapter  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.CustomTabs  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.CustomView  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Design  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.DocumentFile  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.DrawerLayout  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Fragment  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Interpolator  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Loader  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.LocalBroadcastManager  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Media.Compat  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Print  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.SlidingPaneLayout  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.SwipeRefreshLayout  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Transition  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v4  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v7.AppCompat  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v7.CardView  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v7.MediaRouter  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v7.Palette  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.v7.RecyclerView  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.Vector.Drawable  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.VersionedParcelable  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Android.Support.ViewPager  version="28.0.0.3  targetFramework="monoandroid90  
  Xamarin.Build.Download  version="0.4.3  targetFramework="monoandroid90  
  Xamarin.Forms  version="4.7.0.1351  targetFramework="monoandroid90  
  XLabs.Core  version="2.3.0-pre02  targetFramework="monoandroid90  
  XLabs.Forms  version="2.3.0-pre02  targetFramework="monoandroid90  
  XLabs.IoC  version="2.3.0-pre02  targetFramework="monoandroid90  
  XLabs.Platform  version="2.3.0-pre02  targetFramework="monoandroid90  
  XLabs.Serialization  version="2.3.0-pre02  targetFramework="monoandroid90  
  ZXing.Net.Mobile  version="2.3.2  targetFramework="monoandroid90  
  ZXing.Net.Mobile.Forms  version="2.4.1  targetFramework="monoandroid90  
- Affected Devices: Using an Android emulator

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA997
Microsoft Visual C++ 2019

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

 Issue occurs when the application begins to run

### Workaround

I'm not using any custom fonts whatsoever, so this error is perplexing and frustrating.

**Comment by PureWeen** [comment]
@mhughey-vent can you attach a reproduction? 

Is your app crashing? Are you just seeing a message in the logs? 
Android has an initial warmup where it figures out any embedded fonts the user might be using and it does this 

But maybe it's being too aggressive in your case? Are you using Shell?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
