### ISSUE TITLE
[Bug] Timepicker UI broken in 5.0.0

### ISSUE THREAD

**Issue by Suplanus** [xamarin/Xamarin.Forms#13373]
### Description
This is a know issue from 4.8, but no one is looking on the closed issue #12258

### Expected Behavior
No picker dialog

### Actual Behavior
A picker dialog is shown

### Basic Information

- Version with issue: 5.0
- Last known good version: 4.8
- Platform Target Frameworks: 
  - iOS:  14

![94279562-f589b580-ff54-11ea-8f1c-e819a96e68b5](https://user-images.githubusercontent.com/2002916/104294251-3fc08380-54bf-11eb-807c-7b732145b998.gif)

**Comment by mduchev** [comment]
I can also confirm that it was working fine in 4.8.0.1821 and it's broken again in 5.0

**Comment by Ralpharoo** [comment]
+1. Just upgraded for new Xamarin.Essentials and the DatePickers are acting as above in XF 5.0.0.1874

If you want a quick fix, I can confirm using the custom renderer mention here works;
https://github.com/xamarin/Xamarin.Forms/issues/11963#issuecomment-696701626

**Comment by NPadrutt** [comment]
This might be a stupid question and it is a bit OT, but is this the default ios behaviour that it first opens this little flyout
![image](https://user-images.githubusercontent.com/1764367/105029280-6d26a780-5a52-11eb-98f7-911b4f278908.png)

and you have to click that again to open the new picker layout?
![image](https://user-images.githubusercontent.com/1764367/105029301-7a439680-5a52-11eb-9666-fa69b6689887.png)

Why not just open that directly?

**Comment by Suplanus** [comment]
>is this the default ios behaviour that it first opens this little flyout?
No. Thats the bug 🐛

**Comment by mduchev** [comment]
Even though there is no "regression" label, like @Suplanus said, this is a regression from 4.8.0.1821.

**Comment by Suplanus** [comment]
It is still unverified... so we have to wait 😕

**Comment by NPadrutt** [comment]
> > is this the default ios behaviour that it first opens this little flyout?
> > No. Thats the bug 🐛

ah, I see. Because the fix in the 4.8 version was that it opens the picker in the wheel style.

**Comment by Suplanus** [comment]
Is fixed in this release: [5.0.0 Service Release 1](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr1)
