### ISSUE TITLE
[Bug] Localization is not updated at Runtime in Xamarin Forms controls and Custom controls

### ISSUE THREAD

**Issue by Devaraj-Sekar** [xamarin/Xamarin.Forms#13389]
### Description

Localization is updated at Runtime in Xamarin Forms

### Steps to Reproduce

1. Create a button in Xamarin forms with some random text. (Default localization language will be English)
2. Add equivalent resource .resx file to the button text.
2. Now, change the localization of the application through some button click event. (Change to French -> Thread.Culture.CurrentCulture("fr-FR"))
3. Culture will not be applied in the button control

### Expected Behavior

Localization should update at run time to any control with equivalent resx. file

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: Android, iOS, UWP
  - iOS:  Latest
  - Android: Latest
  - UWP:  Latest

**Comment by themronion** [comment]
same as - https://github.com/xamarin/Xamarin.Forms/issues/13415

**Comment by Devaraj-Sekar** [comment]
Hi @themronion ,

Thank you for the update.

Please let us know if any improvement on the reported issue.

Regards,
Devaraj S

**Comment by themronion** [comment]
@Devaraj-Sekar https://github.com/xamarin/Xamarin.Forms/issues/13415#issuecomment-760936381
