### ISSUE TITLE
[Bug] Using a custom font in Mac app causes crash. "fontDescriptor cannot be null" error.

### ISSUE THREAD

**Issue by CartBlanche** [xamarin/Xamarin.Forms#13397]
### Description

Call to `descriptor.FontDescriptorWithSymbolicTraits(traits)` returns null (even though the Apple docs don't mention it AppKit, but do mention it for UIKit), 
So when this line is executed, it throws a `frontDescriptor cannot be null` error and crashes the app.
https://github.com/xamarin/Xamarin.Forms/blob/80a4dbfb1cd897f478c38d0aafa6a5d67940d2f3/Xamarin.Forms.Platform.MacOS/Extensions/FontExtensions.cs#L64

Font I'm using:
[LCD14.otf.zip](https://github.com/xamarin/Xamarin.Forms/files/5811143/LCD14.otf.zip)

This font works perfectly fine on iOS and Android.

### Steps to Reproduce

1.  Add Font to Xamarin.Forms shared project's Resource folder.
2. Mark as `EmbeddedResource`
3. Update AssemblyInfo.cs with `[assembly: ExportFont ("LCD14.otf", Alias = "Clock")]`
4. Create Label and reference FontFamily 
```
<Label Text="Hello Xamarin.Forms"
       FontFamily="Clock" />
```

### Expected Behaviour

No Crash and display the font correctly at runtime.

### Actual Behavior

Does Crash

### Basic Information

- Version with issue: v4.8.01821
- Last known good version: No Idea
- Platform Target Frameworks: 
  - iOS:  Works!
  - Android: Works!
  - Mac:  FAILS

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: 60c7c193-36a0-40cb-a1f6-65589da22877
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	5.0.100
	3.1.404
	3.1.403
	3.1.302
	3.1.301
	3.1.200
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	5.0.0
	3.1.10
	3.1.9
	3.1.6
	3.1.5
	3.1.2
	2.1.23
	2.1.20
	2.1.19
	2.1.17
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.404

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.0.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:40-0500

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/dominique/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dominique/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Visual Studio for Mac Extension for Tizen 1.5
Meadow 0.7.8

### Reproduction Link

Not a repro link, but a gist of the crash - https://gist.github.com/CartBlanche/e27d1efbe1dc12056af5e6b29542066c

### Workaround

Don't use Custom fonts on Mac, is my only current advice. But it really should work just as it does on iOS and Android.

**Comment by Immons** [comment]
Confirm this bug. Just stuck on that...

**Comment by CartBlanche** [comment]
@immons, thanks for confirming. Sadly I've not heard anything back from @samhouts or @jsuarezruiz in nearly 2 weeks now, so no idea where this crash is on their fix list.

**Comment by CartBlanche** [comment]
@jsuarezruiz @samhouts  Just wondering if this will ever be addressed?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
