### ISSUE TITLE
[Bug] Editor control rendered incorrectly with material visual in 5.0

### ISSUE THREAD

**Issue by vincentwx** [xamarin/Xamarin.Forms#13409]
### Description
When the Editor control has no text in it, the PlaceHolder is shown in both floating hint area and text input area. Xamarin.Forms 4.8 does not have this problem. This problem is  specific to the new stable 5.0 release.
### Steps to Reproduce
Just drop a line on a page like the one below you will see it on the screen. (Tested on Android)

Editor Placeholder="Remark" PlaceholderColor="Red"

![image](https://user-images.githubusercontent.com/7928489/104656347-ff563680-5673-11eb-89b2-b81f9550eb8f.png)

- Version with issue: 5.0
- Last known good version: 4.8

**Comment by hartez** [comment]
This appears to be the same issue described in #13541

**Comment by hartez** [comment]
Closing this as a duplicate.
