### ISSUE TITLE
[Enhancement] CornerRadius type consistency through controls

### ISSUE THREAD

**Issue by roubachof** [xamarin/Xamarin.Forms#13400]
## Summary
`CornerRadius` is an `int` on `Button` and `ImageButton`, but a `float` on `Frame`.
When creating style, I have to create two value in my resource dictionary:

```xml
<x:Int32 x:Key="ButtonCardCornerRadius">20</x:Int32>
<x:Single x:Key="FrameCardCornerRadius">20</x:Single>
```

Which is quite annoying x)

## API Changes

Pick one type :)

**Comment by GalaxiaGuy** [comment]
And `BoxView` uses the `CornerRadius` type which lets you specify each corner individually (as `double`s).

I don't think this can be changed without being a breaking change for someone. 

Hopefully it will be improved in Maui.

**Comment by programmation** [comment]
Breaking changes are not a problem when they bring improvements. I'm also optimistic that in this case a `TypeConverter` would enable a smooth transition from the current multiple-type system to one single `CornerRadius` type.

**Comment by PureWeen** [comment]
Just an FYI we're planning on standardizing all of this with .NET MAUI by using System.Graphics or System.Drawing for our types
