### ISSUE TITLE
Material-UI bug on several ui controls

### ISSUE THREAD

**Issue by KonstantinKellermann** [xamarin/Xamarin.Forms#13416]
### Description
We found some ui-issues using Xamarin.Forms 5.0.0.1874 and Xamarin.Forms.Visual.Material 5.0.0.1874.
After updating the nuget packages the ui was broken because buttons looked like they were disabled even they were not.

The backgroundcolor of DatePickers, TimePickers, Entries, Editors and Pickers is changing to white (or black if you use the dark theme) if they are disabled and you use material design.
You're not able to change the backgroundcolor even if you set it by AppThemeBinding light and dark.
If you enable these controls all looks like they should be.

Buttons that use material design and an image inside they are looking like disabled buttons when you open a new page. You're still able to push them.
If you remove these images everything looks fine.

![light1](https://user-images.githubusercontent.com/23655725/104720773-62f06a80-572d-11eb-880a-d87300e46a2a.PNG)
![light2](https://user-images.githubusercontent.com/23655725/104721116-afd44100-572d-11eb-8998-2969084ed13f.PNG)
![dark1](https://user-images.githubusercontent.com/23655725/104721129-b2369b00-572d-11eb-9448-a2e88c388a91.PNG)
![dark2](https://user-images.githubusercontent.com/23655725/104721138-b5318b80-572d-11eb-9d40-b95204f2c7fd.PNG)

I created a new project to reproduce it. And found some more controls that have these issues.

[https://github.com/KonstantinKellermann/MaterialTestProject](url)

The last good version was 4.8.0.1821.

### Steps to Reproduce

1. Take a TimePicker, DatePicker, Entry, Editor or a Picker
2. set Visual="Material"
3. choose a backgroundcolor (not white or black so you can see the effect)
4. set IsEnabled="False"
5. compare the settings IsEnabled="False" and IsEnabled="True" you will see the difference

or

1. Take a Button
2. set Visual="Material"
3. choose a backgroundcolor (not white or black so you can see the effect)
4. set the ImageSource
5. compare it to a button with the same settings only with no image in it

### Expected Behavior
The controls should use the given backgroundcolor or it should be possible to change the DisabledBackgroundColor, that would be nice to have, too.

### Basic Information

- Version with issue: 
  - Xamarin.Forms 5.0.0.1874
  - Xamarin.Forms.Visual.Material 5.0.0.1874
- Last known good version: 
  - Xamarin.Forms 4.8.0.1821
  - Xamarin.Forms.Visual.Material 4.8.0.1821
- Affected Devices:
  - Pixel 3a XL - Andorid 10
  - Pixel 3a XL - Andorid 11
  - Samsung Galaxy S9 - Android 10

**Comment by memsom** [comment]
I am also seeing this issue. If I set Visual to Default, the button renders correctly, but if I have Material installed and initialised, I end up with badly rendered buttons in a SyncFusion sfListView swipe template if they have an image. I don't see this in many other places we use Buttons with images, but I think we also set an explicit style on those buttons.

**Comment by AlvaroAlfameta** [comment]
Same problem here
![Snipaste_2021-01-22_08-52-16](https://user-images.githubusercontent.com/70548066/105493007-296cb180-5c8f-11eb-8ba9-727ad8b8a6b4.png)

**Comment by PureWeen** [comment]
If anyone wants to test the nugets here and let me know if it resolves your issues

https://dev.azure.com/xamarin/public/_build/results?buildId=34721&view=artifacts&pathAsName=false&type=publishedArtifacts
