### ISSUE TITLE
[Feature Request] App Shortcuts akin to AppLinks

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#1341]
## Summary ##
Similar to how AppLinks works, I'd like to have AppShortcuts so that we can implement `UIApplicationShortcutItem` (iOS 9) or Dynamic Shortcuts via the `ShortcutManager` (API 25). Apologies in advance, I know there's something in UWP, but I'm not sure what it's called.

![](https://developer.android.com/images/guide/topics/ui/shortcuts.png) ![](https://developer.xamarin.com/guides/ios/platform_features/introduction_to_ios9/3dtouch/Images/QuickActions01.png)

[iOS Sample](https://developer.xamarin.com/samples/monotouch/ios9/ApplicationShortcuts/)  
[Android Sample](https://developer.xamarin.com/samples/monodroid/android-n/AppShortcuts/)

## API Changes ##

```
public interface IAppShortcutEntry {
    string Label { get; set; }
    Uri AppLink { get; set; }
    ImageSource Thumbnail { get; set; }
}

public class AppShortcutEntry : IAppShortcutEntry { /* implement interface*/ }

Application.Current.AppShortcuts.RegisterShortcut(IAppShortcutEntry entry);
Application.Current.AppShortcuts.DeregisterShortcut(IAppShortcutEntry entry);
```

_implementation_
```
var url = $"http://app.mycompany.com/special-link/{someObject.Id.ToString()}";
var entry = new AppShortcutEntry
{
    Label = session.Title,
    AppLinkUri = new Uri(url, UriKind.RelativeOrAbsolute),
    Thumbnail = ImageSource.FromFile("Icon.png")
};
```

```
Application.Current.AppShortcuts.RegisterShortcut(entry);
```

## Intended Use Case ##
The use case is pretty obvious. I'd like to see Forms add support for some of the nice features found in the newer platform APIs. This is a step in that direction, and this feature would really bolster app that are using frameworks like [Prism](https://github.com/PrismLibrary/Prism).

Migrated from [Evolution](https://forums.xamarin.com/discussion/96947/app-shortcuts-akin-to-applinks)

**Comment by AmrAlSayed0** [comment]
This is now implemented in Xamarin.Essentials https://docs.microsoft.com/en-us/xamarin/essentials/app-actions

**Comment by jfversluis** [comment]
As pointed out, this is implemented in Xamarin.Essentials where you can use it. This won't make its way into Xamarin.Forms anymore. Thanks for the proposal!
