### ISSUE TITLE
[Bug] iOS Solution pushing pages before old content disappears

### ISSUE THREAD

**Issue by mleviathan** [xamarin/Xamarin.Forms#13427]
### Description
Hello everyone, I already opened a question on StackOverflow but still couldn't get an answer.
I got a problem with my application, developed using Xamarin.Forms 5.0.0.1874 (but error was present even before updating the NuGet to this version).
When pushing a new page using
await App.Current.MainPage.Navigation.PushAsync(new Views.SessionPage());
the content of present page is not correctly disposed before drawing the new content.
The problem is really easy, I'll attach a pair of screenshots for better explanation.
This happens mostly on iOS physical devices, on iOS Emulators it's less noticeable while on Android physical devices and emulators I'm not able to reproduce it.
Tested with an iPhone 11 and an iPhone 8 Plus.

### Steps to Reproduce

1. Open the solution and run it
2. Tap "New Session" button
3. You'll see the error every time you change page

### Expected Behavior
When pushing a page via Navigation.PushAsync(new xxx) current page content disappears while new page is pushed.

### Actual Behavior
When pushing a page via Navigation.PushAsync(new xxx) current page content stays while new page content is drawn, resulting in both pages visible.

### Basic Information

- Platform Target Frameworks: 
  - iOS:  14.3 
- NuGet Packages: 
DocumentFormat.OpenXml v2.12.0
Plugin.InAppBilling v4.0.2
SQLiteNetExtensions v2.1.0
SQLiteNetExstensions.Async v2.1.0
sqlite-net-pcl v1.7.335
Xamarin.Essentials v1.6.0
Xamarin.Forms 5.0.0.1874
Xamarin.Forms.PancakeView v2.3.0.759
- Affected Devices: every iOS physical device I was able to test

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.8.5 (build 18)
Installation UUID: 76dd402a-82f1-4cdb-984f-8ddd3b6cefbe
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	5.0.101
	5.0.100
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	5.0.1
	5.0.0
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18

=== .NET Core 3.1 SDK ===

SDK: 3.1.405

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Professional)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/levi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/levi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Professional)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Build Information ===

Release ID: 808050018
Git revision: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5
Build date: 2021-01-07 14:45:50-05
Build branch: release-8.8
Xamarin extensions: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.1.0 Darwin Kernel Version 20.1.0
    Sat Oct 31 00:07:11 PDT 2020
    root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64


```

</details>

### Screenshots

[Screenshot 1](https://i.stack.imgur.com/ZBBzi.png)
[Screenshot 2](https://i.stack.imgur.com/PUYQq.png)

Short video showcasing the problem: [Watch me](https://drive.google.com/file/d/10YSOBHbQ1eqH69RZhUZvKt4CX88ngNwB/view?usp=sharing)

### Reproduction Link

Solution to reproduce the bug: [Download](https://drive.google.com/file/d/1zKUY-Rx0RC10kuuDQix6bJYLmbTn481m/view)

### Workaround

Binding page's first layout to a property named IsPageVisible, before pushing setting this property to false will make your page invisible.

**Comment by GalaxiaGuy** [comment]
That is the default native iOS transition, and has been the default Forms uses on iOS forever. It looks odd in this case because your pages are transparent.

You can disable the transition completely by using 
`await App.Current.MainPage.Navigation.PushAsync(new Views.SessionPage(), false);`

**Comment by PureWeen** [comment]
I agree with @GalaxiaGuy on this one

You can also alter the transition using something like https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions
