### ISSUE TITLE
[Enhancement] Support for attached properties that have collection values

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#13428]
## Summary
I would like to be able to easily create attached properties with collection values that can be easily used in XAML, ideally with access to the element's binding context and ancestry.

This may already be possible, but I've tried quite a bit and always face problems.

## API Changes

Make the following sort of thing possible.

_Note the `Binding` that implicitly uses the `BindingContext` of the `Label` and  the `RelativeSource` that should successfully find the `MyPageViewModel` (in case this is used in a `DataTemplate` on a `CollectionView` for instance)._

```csharp

public static readonly MyAttachedProperty =
    BindableProperty.CreateAttached("MyAttached", typeof(IList<MyThing>), typeof(Stuff), new List<MyThing>());
```
```xaml
<Label>
    <local:Stuff.MyAttached>
        <local:MyThing
            Name="{Binding FavoriteText}"
            Command="{Binding FavoriteCommand, Source={RelativeSource AncestorType={x:Type local:MyPageViewModel}}}"
            CommandParameter="{Binding Id}" />
        <local:MyThing
            Name="{Binding RemoveText}"
            Command="{Binding RemoveCommand, Source={RelativeSource AncestorType={x:Type local:MyPageViewModel}}}"
            CommandParameter="{Binding Id}" />
    </local:Stuff.MyAttachedProperty>
</Label>
```

## Intended Use Case

My specific use case right now is to pass a collection of values to an effect that I want to use on some collectionview items.

Even more specific, I want to create an effect for adding iOS accessibility custom actions to an element (https://developer.apple.com/documentation/uikit/uiaccessibilitycustomaction?language=objc)

**Comment by GalaxiaGuy** [comment]
This post covers a similar thing in WPF and UWP:

https://stackoverflow.com/questions/47471077/collection-type-attached-properties

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by GalaxiaGuy** [comment]
@PureWeen @StephaneDelcroix 
I have come up with something works, but I don't know if it is a good idea:

https://github.com/GalaxiaGuy/xf-bugs/tree/experiment/accessibility

This is the XAML it supports:
https://github.com/GalaxiaGuy/xf-bugs/blob/experiment/accessibility/Bug/MainPage.xaml

And this is the bit that makes it work:
https://github.com/GalaxiaGuy/xf-bugs/blob/experiment/accessibility/Bug/XamlCollection.cs
