### ISSUE TITLE
[Bug] iOS: items reorder in UICollectionView is stuck under Xamarin Forms 5.0.0.1874

### ISSUE THREAD

**Issue by vg12345** [xamarin/Xamarin.Forms#13431]
iOS: items reorder in UICollectionView is stuck immediately under Xamarin Forms 5.0.0.1874 in function
    **UICollectionView.UpdateInteractiveMovement**

Works better under older Xamarin Forms version (4.8) but stucks after 10-20 seconds

Attached is the sample application.

Reproduction steps for Xamarin Forms 5.0.0.1874
1.	Press long on item until it become half-transparent
2.	Start drag
3.	Application is stuck immediately

Reproduction steps for Xamarin Forms 4.8
1.	Press long on item until it become half-transparent
2.	Start drag up and down continuously without leaving drug mode
3.	Application is stuck after 10-20 seconds

[App6.zip](https://github.com/xamarin/Xamarin.Forms/files/5860097/App6.zip)

**Comment by vg12345** [comment]
=================================================================
	Native Crash Reporting

=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 

used by your application.
=================================================================

=================================================================

	Native stacktrace:
=================================================================

	0x1009d0120 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x1009c6cbc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x1009d3a60 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x1d8ef7dbc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x19355094c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>

	0x19566b2d0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1935cb9f0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x193548404 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x19566aef4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195678c38 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1956403f8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1956499a0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195649dd4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195649bd4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x195649b40 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x195651fc8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195658848 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195651f34 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195657288 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195651a94 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195652434 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1009948bc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_to_native_trampoline
	0x100b7b310 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_pinvoke_method
	0x100b71ba4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_metho
d_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a86af4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke
	0x100a886fc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke
	0x1008f6c00 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : _ZL31native_to_managed_trampoline_10P11objc_objectP13objc_selectorPP11_MonoMethodS0_j
	0x100955cb0 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : -[__UILongPressGestureRec
ognizer target:]
	0x195a28a4c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a31fc0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a2ec48 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a2e210 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a227a0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a21b30 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ee2534 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ebd934 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f3fa20 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f441c0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f3b480 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redac
5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x100b71a34 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a852c0 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100a8b974 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke_array
	0x100a339c4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_Inte
ted>
	0x1935e0240 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935e0140 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935df488 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935d9a40 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935d9200 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1a96d4598 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x195e9f004 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ea45d8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x100b7c8a4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall
	0x100b7afb8 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC
rnalInvoke
	0x100a43b68 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke_raw
	0x100b7c8a4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall
	0x100b7afb8 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x100b71a34 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a852c0 - /private/var/containers/Bundle/Application/63732F53-7363-
409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100a8a564 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x1009bb8f4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec
	0x100b6d92c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main
	0x100983c20 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : main
	0x1932b8598 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1a6ea3ca0):0x1a6ea3c90  1f 04 00 f1 0b 04 00 54 08 7c 5f c8
 09 81 7d 92  .......T.|_...}.
0x1a6ea3ca0  2a 81 40 39 8a 01 10 36 a8 02 00 36 09 00 c4 d2 
fffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00254>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================

 *.@9...6...6....
0x1a6ea3cb0  0a fd 6c d3 ea 02 00 b4 08 01 09 ab e2 02 00 54  ..l............T
0x1a6ea3cc0  08 7c 0a c8 8a 02 00 34 08 7c 5f c8 28 ff 07 37  .|.....4.|_.(..7

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_CGPoint <0x00022>
	  at UIKit.UICollectionView:UpdateInteractiveMovement <0x00040>
	  at CheeseApp.iOS.Effects.ItemsReorderEffect:OnLongGesture <0x00386>
	  at System.Action`1:invoke_void_T <0x0007c>
	  at Callback:Activated <0x00018>
	  at <Module>:runtime_invoke_direct_void__this___UILongPressGestureRecognizer <0x00040>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00020>
	  at UIKit.UIApplication:Main <0x00038>
	  at CheeseApp.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0008c>
	  at <unknown> <0xfff

**Comment by vg12345** [comment]
=================================================================
	Native Crash Reporting

=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 

used by your application.
=================================================================

=================================================================

	Native stacktrace:
=================================================================

	0x1009d0120 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x1009c6cbc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x1009d3a60 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x1d8ef7dbc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x19355094c - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>

	0x19566b2d0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1935cb9f0 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x193548404 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x19566aef4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195678c38 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1956403f8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1956499a0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195649dd4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195649bd4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x195649b40 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>

	0x195651fc8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195658848 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195651f34 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195657288 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195651a94 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195652434 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x1009948bc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_to_native_trampoline
	0x100b7b310 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_pinvoke_method
	0x100b71ba4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_metho
d_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a86af4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke
	0x100a886fc - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke
	0x1008f6c00 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : _ZL31native_to_managed_trampoline_10P11objc_objectP13objc_selectorPP11_MonoMethodS0_j
	0x100955cb0 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : -[__UILongPressGestureRec
ognizer target:]
	0x195a28a4c - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a31fc0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a2ec48 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a2e210 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a227a0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195a21b30 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ee2534 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ebd934 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f3fa20 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f441c0 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195f3b480 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redac
5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x100b71a34 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a852c0 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100a8b974 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke_array
	0x100a339c4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_Inte
ted>
	0x1935e0240 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935e0140 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935df488 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935d9a40 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x1935d9200 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1a96d4598 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x195e9f004 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : <redacted>
	0x195ea45d8 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x100b7c8a4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall
	0x100b7afb8 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC
rnalInvoke
	0x100a43b68 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke_raw
	0x100b7c8a4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall
	0x100b7afb8 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x100b71a34 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x100b6fe58 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x1009d6d3c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100a852c0 - /private/var/containers/Bundle/Application/63732F53-7363-
409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100a8a564 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x1009bb8f4 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec
	0x100b6d92c - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main
	0x100983c20 - /private/var/containers/Bundle/Application/63732F53-7363-409B-9CA4-24AEC5CCF42F/CheeseApp.iOS.app/Xamarin.PreBuilt.iOS : main
	0x1932b8598 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1a6ea3ca0):0x1a6ea3c90  1f 04 00 f1 0b 04 00 54 08 7c 5f c8
 09 81 7d 92  .......T.|_...}.
0x1a6ea3ca0  2a 81 40 39 8a 01 10 36 a8 02 00 36 09 00 c4 d2 
fffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00254>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================

 *.@9...6...6....
0x1a6ea3cb0  0a fd 6c d3 ea 02 00 b4 08 01 09 ab e2 02 00 54  ..l............T
0x1a6ea3cc0  08 7c 0a c8 8a 02 00 34 08 7c 5f c8 28 ff 07 37  .|.....4.|_.(..7

=================================================================
	Managed Stacktrace:
=================================================================
	  **at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_CGPoint <0x00022>
	  at UIKit.UICollectionView:UpdateInteractiveMovement <0x00040>**
	  at CheeseApp.iOS.Effects.ItemsReorderEffect:OnLongGesture <0x00386>
	  at System.Action`1:invoke_void_T <0x0007c>
	  at Callback:Activated <0x00018>
	  at <Module>:runtime_invoke_direct_void__this___UILongPressGestureRecognizer <0x00040>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00020>
	  at UIKit.UIApplication:Main <0x00038>
	  at CheeseApp.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0008c>
	  at <unknown> <0xfff

**Comment by PureWeen** [comment]
@vg12345 can you attach a reproduction please?

**Comment by vg12345** [comment]
Hi,

Attached is the sample application.

Reproduction steps for Xamarin Forms 5.0.0.1874

  1.  Press long on item until it become half-transparent
  2.  Start drag
  3.  Application is stuck immediately

Reproduction steps for Xamarin Forms 4.8

  1.  Press long on item until it become half-transparent
  2.  Start drag up and down continuously without leaving drug mode
  3.  Application is stuck after 10-20 seconds

Regards,
Vitaly



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vg12345** [comment]
**Seems to be fixed in 5.0.0.1931**

**Comment by vg12345** [comment]
**Seems to be fixed in 5.0.0.1931**
