### ISSUE TITLE
[Bug] How to exclude AdSupport Class from Xamarin.iOS.dll using Linker or other possible ways?

### ISSUE THREAD

**Issue by PaulsonMac** [xamarin/Xamarin.Forms#13435]
### Description
AdSupport is included within the Xamarin.iOS.dll. 

Is there a way to exclude AdSupport class from Xamarin.ios.dll as I don't want Firebase Analytics SDK to use it?

I saw a way to exclude assemblies in Xamarin.iOS Linker documentation section, but is it possible to exclude this AdSupport class of an assembly in Linker?

### Why I want to do this? 

If the AdSupport is included in the app, Firebase says it will pick it up to access the IDFA. This is for the new privacy requirements in iOS 14 from Apple

### Basic Information

Xamarin.Forms App

### Workaround

No

**Comment by PureWeen** [comment]
@PaulsonMac from what I can tell those get linked out

Below is a screen shot from an iphone/release build with full linking on

![image](https://user-images.githubusercontent.com/5375137/105398349-e1df1a80-5be7-11eb-802b-cdc16568bf3f.png)
