### ISSUE TITLE
Add ItemSelected event to CollectionView

### ISSUE THREAD

**Issue by PetrVobornik** [xamarin/Xamarin.Forms#13445]
## Summary
CollectionView's existing event SelectionChanged is OK for touch screens and cursor. But, especially on UWP, users sometimes needs use a keyboard or a controller (on Xbox or TV) for selecting one concretely item from the list. User switch between items by arrow keys, tab, page up/down... (or by Thumbstick on controller) and on one of them press Enter (or A-button). Only in that moment the new event **ItemSelected** will be fired. And for touch screen of course also when the item is tapped (or mouse click).
Currently when user switching between items by keyboard, the event SelectionChanged is fired at each change and is impossible to distinguish, if the user wants to open it or only skip over them to another item.

## API Changes

Please add to class CollectionView event ItemSelected fired only when item is tapped by touch screen, clicked by mouse, or pressed the Enter on it by a keyboard or A-button on the controller. 
The second option is to add information to the SelectionChangedEventArgs class, by which of these variants the existing event SelectionChanged was triggered.

**Comment by PetrVobornik** [comment]
Second use case scenario: 

I select the item and by the existing event SelectionChanged I open the item detail on the second page.
I return back by the back button to the first page with the CollectionView and selected item.
I tap on the same item which is currently selected and the event SelectionChanged is not launched, because selection was not changed.

Yes, I can clear selection in OnAppearing to the page, but when I need check detail of each item, one by one, especially by the keyboard, selection of last opened item is usefully.

Expected behavior: when I press Enter on the same item again, its detail opens again. And when I tap on it, the same thing will happen again too. That is the second reason for adding new event to the CollectionView.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by osnipezzini** [comment]
@jfversluis You should consider continuing to support Xamarin as the libraries are still not legal to use with the Net MAUI.
The library for reading barcodes is a nice example. Use the same library in Xamarin Forms and NET Maui and you'll see the difference is huge. In NET it doesn't work correctly reading barcodes, apart from the fact that in Xamarin you didn't need to put it inside a page. In our company I had to revert everything and go back to Xamarin
