### ISSUE TITLE
Outdated Microsoft Xamarin Support Policy page

### ISSUE THREAD

**Issue by jgoyvaerts** [xamarin/Xamarin.Forms#13443]
Not sure if this is the right place to make this issue, apologies in advance if I'm in the wrong spot.

When researching our potential transition from Xamarin Forms to .NET MAUI I came across this page:
https://dotnet.microsoft.com/platform/support/policy/xamarin, which describes how long Microsoft plans to support Xamarin versions. However, it looks like the page is outdated, seeing as the last Xamarin.Android version it mentions is 10.1.1.0 whereas 11.2 is actually the latest version.

Also, the page only mentions Xamarin.Android and Xamarin.iOS, does Microsoft make any claims/guarantees regarding support for Xamarin.Forms?

**Comment by PureWeen** [comment]
Thank you for the heads up @jgoyvaerts 

@samhouts is taking care of it
