### ISSUE TITLE
[Bug] "java" exited with code 1. (MSB6006)

### ISSUE THREAD

**Issue by sattasundar** [xamarin/Xamarin.Forms#13451]
### Description
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(5,5): Error MSB6006: "java" exited with code 1. (MSB6006) (XamDemo.Android)
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: Xamarin.Forms 5
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jsuarezruiz** [comment]
@sattasundar  We will need more information to address the issue. Could you share traces or an example where reproduce the issue?

**Comment by sattasundar** [comment]
Have created new project and updated nuget to latest version.

And added this https://github.com/TobiasBuchholz/Plugin.Firebase plugin from nuget successfully.

After that when building solution getting this error.

**Comment by sattasundar** [comment]
Issue resolved.
> Try to add the following `PackageReference` to the .csproj file of your android project:
> 
> ```
> <PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.2" ExcludeAssets="build;buildTra
> ```
