### ISSUE TITLE
[Bug] Getting Exception on making HTTPS request : System.Threading.Tasks.TaskCanceledException: Cannot access a disposed object. Object name: 'MobileAuthenticatedStream'

### ISSUE THREAD

**Issue by hrshitjain** [xamarin/Xamarin.Forms#13453]
We have a Xamarin Forms mobile application that is giving exception on iOS when trying to connect the API Backend.

System.Threading.Tasks.TaskCanceledException: Cannot access a disposed object. Object name: 'MobileAuthenticatedStream' on iPhone 11(iOS 14.2).

Cannot replicate but it happens when the device transitions from background to foreground and data are fetched through HTTPS calls to the backend server.

The application compiled with Xamarin.iOS SDK 13.14.1.24.

### Basic Information

- Version with issue: 4.6.0.1073
- Platform Target Frameworks: 
  - iOS:  13.14.1.24
 - Affected Devices:iPhone 11(iOS 14.2)

### Environment

=== Visual Studio Community 2019 for Mac ===
Version 8.5.4 (build 12)
Installation UUID: 924eacf7-d1f2-4507-8cf3-18f4cee21fdf
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)
	Package version: 604000208
=== Mono Framework MDK ===
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208
=== Roslyn (Language Service) ===
3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e
=== NuGet ===
Version: 5.4.0.6315
=== Xamarin Designer ===
Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC
=== .NET Core SDK ===
SDK: /usr/local/share/dotnet/sdk/3.0.101/Sdks
SDK Versions:
	3.0.101
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks
=== .NET Core Runtime ===
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.1
	2.1.14
	2.0.5
=== Xamarin.Profiler ===
Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
=== Updater ===
Version: 11
=== Apple Developer Tools ===
Xcode 11.3.1 (15715)
Build 11C504
=== Xamarin.Mac ===
Version: 6.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400
=== Xamarin.Android ===
Version: 10.0.6.2 (Visual Studio Community)
Commit: xamarin-android/d16-3/c407838
Android SDK: /Users/nagarro/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4.87 (API level 20)
		6.0    (API level 23)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3
Build Information:
Mono: mono/mono/2019-06@476d72b9e32
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333
=== Microsoft Mobile OpenJDK ===
Java SDK: /usr
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
=== Android SDK Manager ===
Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-04-15 20:49:08 UTC
=== Android Device Manager ===
Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-04-15 20:49:28 UTC
=== Xamarin Inspector ===
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1
=== Xamarin.iOS ===
Version: 13.14.1.24 (Visual Studio Community)
Hash: fa00d7a6
Branch: d16-5
Build date: 2020-01-28 19:38:52-0500
=== Build Information ===
Release ID: 805040012
Git revision: 7642369422103e19b0b8d29ddc211abf2fd32607
Build date: 2020-04-16 08:55:15-04
Build branch: release-8.5
Xamarin extensions: 7642369422103e19b0b8d29ddc211abf2fd32607
=== Operating System ===
Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### StackTrace
System.Net.Http
HttpConnection.SendAsyncCore (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpConnectionPool.SendWithNtConnectionAuthAsync (System.Net.Http.HttpConnection connection, System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpConnectionPool.SendWithRetryAsync (System.Net.Http.HttpRequestMessage request, System.Boolean doRequestAuth, System.Threading.CancellationToken cancellationToken)
System.Net.Http
RedirectHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
System.Net.Http
HttpClient.FinishSendAsyncBuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts)

**Comment by PureWeen** [comment]
@hrshitjain we're not going to be able to help on this one without more details here. 

If you have a minimal repro that even just represents the type of HTTP request your making? Is it a 3rd party library?

**Comment by hrshitjain** [comment]
@PureWeen We are not using any third-party library. We are making an HTTP GET request, which works fine in all cases.
This may be related to the MONO issue here: 

- https://github.com/mono/mono/issues/20759
- https://github.com/mono/mono/issues/15462

**Comment by PureWeen** [comment]
I'm going to close this issue here for now and we can follow what the mono team thinks inside the issues you've referenced
