### ISSUE TITLE
[Bug] iOS device can't make requests via HttpClient to web service running on local area network

### ISSUE THREAD

**Issue by meJevin** [xamarin/Xamarin.Forms#13454]
### Description
When using Http client in a sample Xamarin.Forms project I am unable to make any kind of HTTP requests using HttpClient (NSUrlSession) on my iOS device (iPhone 11, iOS 14.3) to a web service running on my development computer. Both devices are connected to the same network. A web service is a ASP.NET Core Web API running NOT in IISExpress but via dotnet run, the launch settings for that service have been configured to use the ip of my computer on my local area network (192.168.1.74). I am developing an application in Xamarin.Forms that interacts with my web service. On android everything works just fine.

When accessing my API from a Chrome application on my iPhone I am able to reach endpoints and everything is ok. In my application however, when making a request to my computer which hosts my web service I get the following error followed by a crash of a Xamarin.Forms application.

An error occurred: 'Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x280be9d40 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <5D24636F-E5D0-496F-A8E6-EC0E78A1D8CF>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <5D24636F-E5D0-496F-A8E6-EC0E78A1D8CF>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.1.74:1488/Auth/Register, NSErrorFailingURLKey=http://192.168.1.74:1488/Auth/Register, _kCFStreamErrorDomainKey=1}'. Callstack: ''

I've also enabled local area network access and allowed HTTP for my Xamarin.Forms application by adding the following lines in Info.plist:
<key>NSAppTransportSecurity</key>
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
  <key>NSAllowsLocalNetworking</key>
  <true/>
</dict>

### Steps to Reproduce

1. Create a blank Mobile App (Xamarin.Forms) project
2. Create a blank ASP.NET Core Web API project
3. In launchSettings.json set applicationUrl to be your local area network ipv4 adddress (and choose a port)
3. dotnet run web api
4. Add the code to test HttpClient request to web api in your local area network in your mobile app

### Expected Behavior
I am able to use HttpClient on iOS to make requests to my development computer which hosts an ASP.NET Core web api. The computer is connected to the same network as my iOS device.

### Actual Behavior
I am unable to use HttpClient on iOS to make requests to my development computer which hosts an ASP.NET Core web api. The computer is connected to the same network as my iOS device. The problem is fully described in the 'Description' section.

### Basic Information

- Version with issue: 4.8.0.1451 (also present on 5.0.0.1874)
- Last known good version: don't know
- Platform Target Frameworks:
  - iOS:  Default (option selected in iOS project when going to Properties -> iOS Buid)
- NuGet Packages: none
- Affected Devices: iPhone 11

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA742
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   16.8.557.25636
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line   2.4.233
2.4.233

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

Qt Visual Studio Tools   2.6.0.7
The Qt Visual Studio Tools allow developers to use the standard development environment without having to worry about any Qt-related build steps or tools.

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Comment by PureWeen** [comment]
@meJevin if you use a native Xamarin.iOS app do you see the same issue?

**Comment by meJevin** [comment]
@PureWeen, I'm sorry, I don't have a Mac machine. I can not provide you with this informatiom.

**Comment by jsuarezruiz** [comment]
I want to replicate the same conditions. Could you indicate which version of Visual Studio you use? And which version of iOS? 

Tried on macOS and  I had to do some changes with certificate etc. 
<img width="297" alt="Captura de pantalla 2021-02-10 a las 14 26 59" src="https://user-images.githubusercontent.com/6755973/107762928-0c774b80-6d2e-11eb-98c1-bf21258379f1.png">

**Comment by meJevin** [comment]
@jsuarezruiz, iOS 14.3, iPhone 11. I'm using Windows 10, not macOS.

**Comment by rmarinho** [comment]
hi @meJevin can you upload a small sample of the code you are using on the asp.net backend and the iOS app. I think iOS only allows to call to real certs and not self signing certificates. But we will need a repro to try to understand what's happening. 

Thanks.

**Comment by meJevin** [comment]
@rmarinho, we can close this issue. I bought a Mac and tested my application by building it in Visual Studio for Mac. Everything suddenly works.

**Comment by bb281** [comment]
I've had the same issue as @meJevin.  My iphone is on the same local network. I can access the web api on my local windows machine via the safari browser http requests, and I can access the web api from my Android device. However, on the iPhone,  I'm having the same issue as @meJevin described above. I can change the api string in the mobile app and point it to my remote machine and it works just fine. So the issue seems isolated to local network access on the iPhone app. 
Also, when I look at my privacy settings on the app it shows that local network access is enabled for the app.
I appreciate any insight/tips on resolving this issue. Thanks.

Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x283be5ec0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0724C5B5-4917-407F-846A-6DB98D9B6EBC>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0724C5B5-4917-407F-846A-6DB98D9B6EBC>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.1.73:5000/api/auth/token, NSErrorFailingURLKey=http://192.168.1.73:5000/api/auth/token, _kCFStreamErrorDomainKey=1}

**Comment by bb281** [comment]
Well I had a different xamarin dev app on my phone and deleted it. Magic! The original app with the issue works now.
