### ISSUE TITLE
[Bug] carouselView currentItem issue in android.

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#13467]
can not set current item correctly in carouselView

### Steps to Reproduce

1. create a carouselview
2. set the itemSource and the currentItem
3. check if it is right.

### Actual Behavior
in the example If I set below list[4] it is correct but if I set the currentItem to list[5] or list[6] it is not right. 

[carouseltest.zip](https://github.com/xamarin/Xamarin.Forms/files/5839705/carouseltest.zip)

**Comment by PureWeen** [comment]
@mcguu can you try with the latest version of forms?

I tested your sample on the latest version of 5.0 and it looks like it's working
![image](https://user-images.githubusercontent.com/5375137/105249252-6de83800-5b3d-11eb-862c-acd6e4d69158.png)

**Comment by mcguu** [comment]
@PureWeen  yes. sorry to waste your time. please solve another bug that immersive is not ok in xamarin.forms shell.
