### ISSUE TITLE
[Bug] [IMPORTANT] Hot Reload doesn't work with .Net Standard 2.1

### ISSUE THREAD

**Issue by meJevin** [xamarin/Xamarin.Forms#13463]
### Description
Hot Reload doesn't work with .Net Standard 2.1. Only works on .Net Standard 2.0

### Steps to Reproduce

1.  Create a Xamarin.Forms project
2.  Switch PCL to .Net Standard 2.1 from 2.0
3.  Try to use Hot Reload feature

### Expected Behavior
Hot reload works on .Net Standard 2.1

### Actual Behavior
Hot reload doesn't work on .Net Standard 2.1

### Basic Information

- Version with issue: 4.8.0.1451 (also present on 5.0.0.1874)
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  Default  (option selected in iOS project when going to Properties -> iOS Buid)
  - Android: 10
- NuGet Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: iPhone 11, Emulated Pixel 3 x86 on Android 10

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019 00435-60000-00000-AA742
Microsoft Visual C++ 2019

ADL Tools Service Provider 1.0
This package contains services used by Data Lake tools

ASA Service Provider 1.0

ASP.NET and Web Tools 2019 16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services 16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012 16.8.557.25636
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019 16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0 16.8.557.25636
Azure App Service Tools v3.0.0

Azure Data Lake Node 1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio 2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools 16.8.557.25636
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio 2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools 3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter 16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus 1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents 1.0
Fabric Diagnostic Events

GitHub.VisualStudio 2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension 1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node 2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service 2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio 16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service 2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node 1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools 2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio 0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager 2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger 1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards 1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers 1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package 1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio 16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools 1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager 5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Open Command Line 2.4.233
2.4.233

ProjectServicesPackage Extension 1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python 16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support 16.8.20241.2
Conda support for Python projects.

Python - Django support 16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support 16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support 16.8.20241.2
Profiling support for Python projects.

Qt Visual Studio Tools 2.6.0.7
The Qt Visual Studio Tools allow developers to use the standard development environment without having to worry about any Qt-related build steps or tools.

SQL Server Data Tools 16.0.62012.31170
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test 1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test. The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test 1.0
Enables Visual Studio's testing tools with unit tests written for Google Test. The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor 1.0
Hosting json editor into a tool window

TypeScript Tools 16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package 1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions 1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake 1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers 1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes 1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog 1.0
Information about my package

VisualStudio.Foo 1.0
Information about my package

VisualStudio.Mac 1.0
Mac Extension for Visual Studio

Xamarin 16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop@79d9533
ProGuard: Guardsquare/proguard@ebe9000
SQLite: xamarin/sqlite@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK 14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Build Logs

> VS bug [#1267658](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267658)

**Comment by meJevin** [comment]
Yo, this is kinda big. Might wanna take a look at this.

**Comment by PureWeen** [comment]
@BretJohnson  @StephaneDelcroix  ?

**Comment by meJevin** [comment]
@PureWeen, bump

**Comment by BretJohnson** [comment]
Are others able to reproduce this? I've gotten one other report that Hot Reload stops working when switching to .NET Standard 2.1, but I'm not able to reproduce it - it works for me. There must be some other element required to make it break. Thanks for any more info that may offer clues.

**Comment by jsuarezruiz** [comment]
I have tested with the empty template updating to Xamarin.Forms 5.0 and using a .NET Standard 2.1 library but, cannot reproduce the issue. 

@meJevin We are missing something? Could you attach a small example where reproduce the problem?

**Comment by mhernanrobledo** [comment]
Same Issue here. On New solution (Shell with tabs) works fine with Net Standard 2.0 but if swith to 2.1 does not works on VStudio 16.9.0 preview 4 and Xamarin Forms 5.0.0.1931. Heres is the Output from Xamarin Hot Reload

Net Standard 2.0
(App1.Android) XAML Hot Reload is using 'changes only' mode
XAML Hot Reload initializing...
WARN: (App1.Android) Unknown Breakpoint Hit: Android.Runtime.JNIEnv.RegisterJniNatives( typeName_ptr, int typeName_len,  jniClass,  methods_ptr, int methods_len)
(App1.Android) HotReload: Initialized Agent.
XAML Hot Reload Connected and Ready.
(App1.Android) Applying XAML Hot Reload update (1 change)


NET Standard 2.1
(App1.Android) XAML Hot Reload is using 'changes only' mode
XAML Hot Reload initializing...
WARN: (App1.Android) Unknown Breakpoint Hit: Android.Runtime.JNIEnv.RegisterJniNatives( typeName_ptr, int typeName_len,  jniClass,  methods_ptr, int methods_len)
(App1.Android) HotReload: Initialized Agent.
XAML Hot Reload Connected and Ready.

**Comment by BretJohnson** [comment]
This is likely this issue (for those who have access): https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1285298
@drasticactions fixed it in 16.10/8.10 and it's a candidate to fix in a 16.9/8.9 SR
