### ISSUE TITLE
[Bug] Xamrain forms Ios project not loading in windows 16..8.4 Community

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#13468]
### Description

Previous to 16.8.4 even though we are not able to run the project on windows except with hot reload the project now fails to even load in visual studio. This was always possible in the forms project type even for basic file editing. Has this now been changed and must always be open on a mac?

### Steps to Reproduce

1. Create a new forms application with ios and andriod checked.
2.  Reload the solution in Community 16.8.4
3. An Error message will be produced

### Expected Behavior
The solution should still load and allow editing of the files this was the case prior to 16.,8.4
### Actual Behavior
![image](https://user-images.githubusercontent.com/5619229/105120626-823f1d00-5aca-11eb-8f5f-f9eb7e67dfba.png)

The following error message is produced by the system

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 - MSFSAddonsHub.Forms.iOS, "D:\GitMaster\MSFSAddonsHub\MSFSAddonsHub.Forms\MSFSAddonsHub.Forms\MSFSAddonsHub.Forms.iOS\MSFSAddonsHub.Forms.iOS.csproj"

No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - MSFSAddonsHub, "D:\GitMaster\MSFSAddonsHub\MSFSAddonsHub.sln"

### Basic Information
Microsoft Visual Studio Community 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA994
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Markdown Editor   1.12.253
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by PureWeen** [comment]
@davidbuckleyni I installed the community edition and it's able to run iOS projects without any issue.

If you go into the VS Installer and remove the Xamarin workload and then re-add it does that fix the issue?

**Comment by davidbuckleyni** [comment]
I will attempt that now but had no issues before the 16.4

**Comment by davidbuckleyni** [comment]
Yeah that seemed to fix it @PureWeen must have been something to do with the last update before 16.8.4

**Comment by davidbuckleyni** [comment]
It happened again basically 20 mins after I done what you said I quit visual studio then come back to same project and got it again odd to say least @PureWeen

**Comment by PureWeen** [comment]
@davidbuckleyni is this happening with a clean new project? or just your own project?

**Comment by davidbuckleyni** [comment]
I will check that in morning for you mate @PureWeen

**Comment by davidbuckleyni** [comment]
Just to be clear this is the error I am reciving I will check it with a clean project today.

![image](https://user-images.githubusercontent.com/5619229/105475015-d1d24400-5c96-11eb-9370-b4d61a718eb3.png)

**Comment by Redth** [comment]
Can you attach the contents of the MSFSAddonsHub.Forms.iOS.csproj file?

**Comment by davidbuckleyni** [comment]
Yeah budy here u go @Redth  this only started happening since the last update to visual studio btw.
[MSFSAddonsHub.Forms.iOS.csproj.txt](https://github.com/xamarin/Xamarin.Forms/files/5879372/MSFSAddonsHub.Forms.iOS.csproj.txt)

**Comment by davidbuckleyni** [comment]
I renamed it to txt as the github didnt allow the csproj extension just

**Comment by davidbuckleyni** [comment]
It seems to be ok this morning did you do something at the ms end @Redth  it loaded it fine.

![image](https://user-images.githubusercontent.com/5619229/106092368-0bd39800-6126-11eb-8bad-078dc73c4040.png)

**Comment by davidbuckleyni** [comment]
Ok this seems odd it must be something on the Microsoft servers side this morning its back to saying needs migration @Redth
Even though I have all workloads of xamrain forms installed nothing has changed in my setup.

![image](https://user-images.githubusercontent.com/5619229/106272643-43773880-6229-11eb-835d-ac41d0e5c370.png)
But today its now showing incomptable is this to do with the SSl certs issues azure is dealing with at present?

![image](https://user-images.githubusercontent.com/5619229/106273510-b7fea700-622a-11eb-9a8d-ab8b0fa57add.png)

**Comment by jsuarezruiz** [comment]
@davidbuckleyni Do you still have this issue? 
If you go into the VS Installer and remove the Xamarin workload and then re-add it does that fix the issue?
If the above does not fix the issue, could you reinstall Visual Studio?

**Comment by davidbuckleyni** [comment]
It does not fix the issue already been thru a re install and the same is the case. 

It shouldn't brake like this but that I should have to remove my dev enviorment  every time a life change comes thru.

**Comment by jsuarezruiz** [comment]
@joj Maybe you can help us in this case with logs, etc.

**Comment by joj** [comment]
The best in this case is to report the issue directly from VS (https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019). We do get some extra information (logs, etc) when that happens. Most of the time, that error is just an installation error and repairing VS fixes it, but we may have an actual bug on our side. If you link it here I can make sure that it gets routed appropriately, which may save some time.
