### ISSUE TITLE
Additional KeyboardFlags' Enum

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#13461]
Hi,

Please add the following to the KeyboardFlags Enum:

ForceCapital / ForceUpper : to force all letters in CAPS.
ForceSmall / ForceLower : to force all letters in Small.

Thanks,
Jassim

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
