### ISSUE TITLE
[Enhancement] Support native Dialogs on Windows Desktop

### ISSUE THREAD

**Issue by UweReisewitz** [xamarin/Xamarin.Forms#13471]
## Summary
Mobile devices use a single page, so it is no problem to show dialogs as areas within this page. On the other hand, in Windows Desktop one expects to see MessageBoxes or Custom Dialogs to show in a separate Window

## API Changes

The BuiltIn Dialogs and the Page (for custom dialogs) should have an option to show them in a separate Window, if possible.
Systems that only have a single page should ignore this option.
The implementation should honor the modality flag and disable underlying windows accordingly.

## Intended Use Case
A Windows Desktop user expects MessageBoxes or custom dialogs (e.g. Search-Input, About Box, Information Details etc.) to show in a separate Window that can be moved freely on the screen (or be moved to a second monitor, for example). This is currently not possible with Xamarin Forms and would be very helpful if  available in MAUI.

**Comment by PureWeen** [comment]
https://github.com/xamarin/XamarinCommunityToolkit/pull/653
