### ISSUE TITLE
[Bug] TitleView is only visible after re-entering the page on iOS - Version 5.0.0.1905

### ISSUE THREAD

**Issue by AndreasReitberger** [xamarin/Xamarin.Forms#13476]
### Description
I updated to the latest stable version of Xamarin.Forms.
Now the `TitleView` content is only visible after re-entering the page. In other words, if the page is shown the first time, the `TitleView` is empty. If I navigate to another page via `Shell.GoToAsync()` and return, the `TitleView` is visible.

### Steps to Reproduce

1. Create a Shell app and add a few ShellItems and a PopUp page
2. While navigating through the ShellItems, the `TitleView` remains invisble
3. If you call `Shell.GoToAsync()` and open another page and return, the `TitleView` is visible

### Expected Behavior
`TitleView` is always visible

### Actual Behavior
`TitleView `gets only visible if another page is opened via `Shell.GoToAsync()`

### Basic Information

- Version with issue: Version 5.0.0.1905
- Affected Devices: IPhone 11 (real device)

### Screenshots
Please see the screenshots below. The first one shows the page when first shown (navigation between ShellItems does not trigger the TitleView to be shown). Second shows a new opened page. After returning, screenshot 3 shows the TitleView.

![image](https://user-images.githubusercontent.com/2952443/105201757-83f7f780-5b41-11eb-9505-ff1d11785410.png) ![image](https://user-images.githubusercontent.com/2952443/105201787-89edd880-5b41-11eb-88e9-d60adb8a8fb0.png) ![image](https://user-images.githubusercontent.com/2952443/105201797-8d815f80-5b41-11eb-940f-f31b61936c9e.png)

### Workaround
Set the Height of your TitleView to 44 on iOS

```XAML
    <Shell.TitleView>
        <Grid HeightRequest="{OnPlatform iOS=44}" >
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>
            <Label Text="About Page" VerticalTextAlignment="Center"/>
            <Label Grid.Column="1" Text="Second" VerticalTextAlignment="Center"/>
        </Grid>
    </Shell.TitleView>
```

**Comment by PureWeen** [comment]
@AndreasReitberger can you attach a repro?  I've attached my attempt but the TitleView is always showing up for me

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5850772/Archive.zip)

**Comment by AndreasReitberger** [comment]
> @AndreasReitberger can you attach a repro? I've attached my attempt but the TitleView is always showing up for me
> 
> [Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5850772/Archive.zip)

Hi @PureWeen 
thanks for your reply. I'll check your repo and check if there are any differents to my project. I'll keep you posted.

**Comment by AndreasReitberger** [comment]
> @AndreasReitberger can you attach a repro? I've attached my attempt but the TitleView is always showing up for me
> 
> [Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5850772/Archive.zip)

Hi @PureWeen 
I checked your repo and was able to reproduce the issue also in your example.

I set the TitleView as followed:

```
<Shell.TitleView>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>
            <Label Text="About Page" VerticalTextAlignment="Center"/>
            <Label Grid.Column="1" Text="Second" VerticalTextAlignment="Center"/>
        </Grid>
    </Shell.TitleView>
```

However only the `VerticalTextAlignment` for the label was needed to let the TitleBar disappear.
Please find the repo here:
[_Issue13476.zip](https://github.com/xamarin/Xamarin.Forms/files/5855606/_Issue13476.zip)

**Comment by Rabosa616** [comment]
I have the same issue

**Comment by AndreasReitberger** [comment]
@PureWeen 
I did some further research and it seems that once a Grid is used, the VerticalTextAlignment fails.

Doesn't work:
```
<Shell.TitleView>
        <Grid>
            <Label Text="About Page" VerticalTextAlignment="Center"/>
        </Grid>
    </Shell.TitleView>
```
Works:
```
    <Shell.TitleView>
        <Label Text="About Page" VerticalTextAlignment="Center"/>
    </Shell.TitleView>
```

Hope this helps!

**Comment by AndreasReitberger** [comment]
Hi @PureWeen 
I just updated to the latest version of Xamarin.Forms.
Now the `TitleView` is displaying, however the Width isn't acurate now.

My `TitleView` is layouted this way:

```
<Grid>
   <Grid.ColumnDefinitions>
      <ColumnDefinition />
      <ColumnDefinition Width = "Auto"/>
      <ColumnDefinition Width = "Auto"/>
   </Grid.ColumnDefinitions>
   <Label />
   <Button Grid.Column="1"/>
   <Button Grid.Column="2"/>
</Grid>
```

On iOS, the last `Button` isn't visible at all, the first `Button` half. So I guess the `Width` of the `TitleView` is not accurate.
Once I'm back home I can send you a screenshot.
