### ISSUE TITLE
[Bug] [iOS] App could not be build with Xcode 11 or lower using Xamarin.Forms 5.0

### ISSUE THREAD

**Issue by AGerchevProgress** [xamarin/Xamarin.Forms#13472]
### Description
I've faced an issue with Xamarin.Forms 5.0 where I cannot build the app with lower version than XCode 12 when the Linker behavior is set to "Link Framework SDKs Only". The bug can be reproduced after this change https://github.com/xamarin/Xamarin.Forms/commit/5a770f90f52c13ef90a18597d7e26ae90dffe207#diff-6fab6656b3d67e8eccc1127901acd8c91f7464b8f61e93af326e504814f334be has been made. 
Please check the attached sample project.

### Steps to Reproduce

1. Open visual studio for MAC.
2. Create a Xamarin.Forms app with target version 5.0.0.1874
3. Set Linker Behavior from the iOS project options to "Link Framework SDKs Only".
4. Build the app with lower version than XCode 12.

### Expected Behavior
The app is successfully build.
### Actual Behavior
The following error occurs: 

Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1<Xamarin.Forms.IndicatorView>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. [/Volumes/Data/dt-x-ag2/_work/75/s/Xamarin-Forms/QSF/QSF.iOS/QSF.iOS.csproj
### Basic Information

- Version with issue: 5.0.0.1874
- Last known good version: 4.8.0.1269

### Reproduction Link
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/5841390/Archive.zip)

**Comment by PureWeen** [comment]
@AGerchevProgress we dropped support for Xcode11 with version 5.0 

Xamarin.iOS doesn't support multi targeting different versions of Xcode. We try to stay backwards compatible as long as we can but as Apple rolls out new iOS versions we have to use newer APIs that are only available with newer versions of Xcode so that apps will be able to run successfully on all versions of iOS
