### ISSUE TITLE
[Enhancement] [iPadOS] Primary, Supplementary and Secondary pages inside UISplitViewController

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#13473]
## Summary

On iPadOS 14, Apple has introduced a new concept:
https://developer.apple.com/documentation/uikit/uisplitviewcontroller?language=objc

## API Changes

FlyOutPage (aka MasterDetailPage)  needs to introduce 'Supplementary' view, so it will become 

FlytOutPage -> FlyOut (also known as Primary in UISplitViewController)
**FlytOutPage -> Supplementary (also known as Supplementary in UISplitViewController)** (NEW!)
FlytOutPage -> Detail (also known as Secondary in UISplitViewController)

## Intended Use Case

It could be a platform-specific change but the use case will be accessing the native view component instead of creating a custom solution and splitting the Detail page into two.

**Comment by PureWeen** [comment]
The structure of .NET MAUI here lends itself to this type of things since it'll be a lot more straight forward exposing native behaviors like this.

The other thing here is that UISplitViewController is only used when you're on an iPad if you're on an iPhone then it's just a UIView with a custom UIView for the Flyout

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
