### ISSUE TITLE
[Android] Frame outline color not rendering

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1347]
### Description
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=27460

The original issue was that the color wouldn't appear unless padding was set. In my sample I don't see the color on Android at all. iOS renders as I'd expect.

<img width="919" alt="screenshot 2017-12-07 08 14 26" src="https://user-images.githubusercontent.com/41873/33720042-56c5f330-db28-11e7-9aaa-a88f33453560.png">

### Steps to Reproduce

1. Create a Frame with an outline color.
2. Run and observe on Android the outline doesn't show the color.

### Expected Behavior
The outline should be the color I've chosen, regardless of padding.

### Actual Behavior
iOS renders as expected. Android outline isn't the chosen color, red.

### Basic Information

- Version with issue: 2.5.0.121934
- IDE: VS Mac
- Platform Target Frameworks: 
  - iOS:  11.1
  - Android: 7.1 running on 8.0 using FormsAppCompatActivity
- Android Support Library Version: 25.4.0.2

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1539431/Archive.zip)

**Comment by mohachouch** [comment]
CarView has no property to change the color of this border. You have to use a GradientDrawable in background. I can fix this bug if you wish.

![image](https://user-images.githubusercontent.com/25939826/33788246-75237e3e-dc71-11e7-9366-d75c00d14932.png)

**Comment by ddobrev** [comment]
When is this going to be released?

**Comment by clovs** [comment]
Still got this issue on Android
```
_FrameLayout = new Frame
            {
                Padding = 20,
                Margin = 10,
                BackgroundColor = Color.White,
                Content = View,
                HasShadow = true,
                OutlineColor = Color.Red,
                VerticalOptions = LayoutOptions.CenterAndExpand,
                HorizontalOptions = LayoutOptions.Center
            };
```

**Comment by mohachouch** [comment]
@clovs  What version of Xamarin Forms do you use?

**Comment by clovs** [comment]
Hello,
"Xamarin.Forms" version="2.5.0.280555" targetFramework="xamarinios10"

You can see on source code here: 
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs
They use a BorderColorproperty from Frame Object, But I got no one! How did they?
I got just an OutlineColorproperty. like describe in the doc:
https://developer.xamarin.com/api/type/Xamarin.Forms.Frame/

So I just redraw an stroke with OutlineColorproperty on the canvas with custom renderer: 
Here my code: 
 ```
public override void Draw(Canvas canvas)
        {
            base.Draw(canvas);
            using (var strokePaint = new Paint())
            using (var rect = new RectF(0, 0, canvas.Width, canvas.Height))
            {
                string FrameBorderColorHex = String.Format("#{3:X2}{0:X2}{1:X2}{2:X2}", (int)(Element.OutlineColor.R * 255), (int)(Element.OutlineColor.G * 255), (int)(Element.OutlineColor.B * 255), (int)(Element.OutlineColor.A * 255));

                // stroke
                strokePaint.SetStyle(Paint.Style.Stroke);
                strokePaint.Color = Android.Graphics.Color.ParseColor(FrameBorderColorHex);
                strokePaint.StrokeWidth = 5;

                canvas.DrawRoundRect(rect, Element.CornerRadius, Element.CornerRadius, strokePaint);  
            }
        }
```

**Comment by andreinitescu** [comment]
Looking at https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/FrameRenderer.cs#L53 `UpdateBackground()` and `UpdateCornerRadius()` are being called but both do same thing:

		void UpdateBackground()
		{
			this.SetBackground(new FrameDrawable(Element, Context.ToPixels));
		}

		void UpdateCornerRadius()
		{
			this.SetBackground(new FrameDrawable(Element, Context.ToPixels));
		}

This ends up in calling `SetBackground` and creating FrameDrawable twice.
This hurts performance and it should be necessary...

Another thing: in the `FrameDrawable` ctor, I see subscription to the `PropertyChanged` event of the `Xamarin.Forms.Frame` instance. I can't see where it's unsubscribing from the event. I haven't though if it's really needed it or not though.

**Comment by reense** [comment]
This issue is still very much a thing. Any updates?

**Comment by jassmith** [comment]
This should be in 3.0.0

**Comment by vhnatyk** [comment]
Hi! I'm still having issue with this on 3.2.0.839982 on Android - on iOS, Google Android simulators all ok - but on Android devices, Frame doesn't draw as expected. I use it to make a single pixel line - but on android devices it has only background. Fixed with a renderer 
``using Android.Content;
using Android.Graphics;
using ProtectionOne.Mobile.P1TechPortal.Controls;
using TechPortal.Droid.Controls;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportRenderer(typeof(SeparatorLine), typeof(SeparatorLineRenderer))]
namespace TechPortal.Droid.Controls
{
    public class SeparatorLineRenderer : FrameRenderer
    {
        public SeparatorLineRenderer(Context context) : base(context)
        {
        }

        public override void Draw(Canvas canvas)
        {
            base.Draw(canvas);

            if (Element == null || Element.BorderColor.A <= 0)
            {
                return;
            }

            using (var paint = new Paint
            {
                AntiAlias = true
            })

            using (var path = new Path())
            using (Path.Direction direction = Path.Direction.Cw)
            using (Paint.Style style = Paint.Style.Stroke)
            using (var rect = new RectF(0, 0, canvas.Width, canvas.Height))
            {
                var raduis = Android.App.Application.Context.ToPixels(Element.CornerRadius);
                path.AddRoundRect(rect, raduis, raduis, direction);
                //paint.StrokeWidth = Context.Resources.DisplayMetrics.Density * 2;  
                paint.SetStyle(style);
                paint.Color = Element.BorderColor.ToAndroid();
                canvas.DrawPath(path, paint);
            }
        }
    }
}

**Comment by D4rkC1own187** [comment]
This is still an issue. I'm using Xamarin.Form 4.0.0425677

**Comment by PureWeen** [comment]
@D4rkC1own187 can you create a new issue and try the latest?
