### ISSUE TITLE
Visual Studio 2019 release 16.8.4 - Xamarin.Forms Error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#13488]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Visual-Studio-2019-release-1684---Xama/1311205)._

---
[regression] [worked-in:16.8.3]
The xamarin.forms project was working fine in visual studio enterprise 16.8.3, but after updating to visual studio enterprise 16.8.4, when I try to open a blank xamarin.forms project, I get the errors in the picture. Also I can't view the .xaml file. Can you please help?
[Ekran görüntüsü 2021-01-15 090849.png] (https://aka.ms/dc/file?name=B8f970c85a060435aaa624876e06e77c2637462881591207463_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_090849.png&tid=8f970c85a060435aaa624876e06e77c2637462881591207463)
[Ekran görüntüsü 2021-01-15 091153.png] (https://aka.ms/dc/file?name=B20127c73a1cc4583a44355b6d29d70ac637462881679531434_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_091153.png&tid=20127c73a1cc4583a44355b6d29d70ac637462881679531434)
[Ekran görüntüsü 2021-01-15 091326.png] (https://aka.ms/dc/file?name=B224bae383f2142eaa6bc607cfe79aa13637462881756159593_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_091326.png&tid=224bae383f2142eaa6bc607cfe79aa13637462881756159593)

---
#### Feedback Bot on 1/15/2021, 07:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Göksel Yüce on 1/15/2021, 08:24 AM: 

<p><a target='_blank' href="https://aka.ms/dc/file?name=Bcd93853904e44cca8524674046daac31637462957589078229_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_111908.png&amp;tid=cd93853904e44cca8524674046daac31637462957589078229">Ekran görüntüsü 2021-01-15 111908.png</a><br>
<a target='_blank' href="https://aka.ms/dc/file?name=Bffb1e30574a44188b24984669046df92637462957692272734_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_111939.png&amp;tid=ffb1e30574a44188b24984669046df92637462957692272734">Ekran görüntüsü 2021-01-15 111939.png</a><br>
<a target='_blank' href="https://aka.ms/dc/file?name=Bcf258511bdab4dc3bc79eee8bef644c1637462957808417502_Ekran_g%C3%B6r%C3%BCnt%C3%BCs%C3%BC_2021-01-15_112008.png&amp;tid=cf258511bdab4dc3bc79eee8bef644c1637462957808417502">Ekran görüntüsü 2021-01-15 112008.png</a></p>
<p>Other mistakes I got</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
If you go into the VS Installer and remove the Xamarin workload and then re-add it does that fix the issue?

**Comment by Gokselyc** [comment]
As a solution I reverted to the previous version. Thank you for your interest.

**Comment by PureWeen** [comment]
@Gokselyc if you update to 16.9 do you still see the same issue?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
