### ISSUE TITLE
Devops Pipeline fails Can't resolve the reference 'System.Void UIKit.UIPageControl  IndicatorViewRenderer (5.0.0.1905) 

### ISSUE THREAD

**Issue by developer9969** [xamarin/Xamarin.Forms#13486]
Hi Xamarin team.

It took few days to make sure I could build my solutions with the latest due to issues with android https://github.com/xamarin/Xamarin.Forms/issues/13303

and when I finally managed to get it going  my devops build fails with

` MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)',
 referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1<Xamarin.Forms.IndicatorView>)'
 in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ]

**In the pipeline**
`monoVersion: '6_12_0'  
xCodeVersion: '12.3' 

- task: Bash@3
      displayName: 'Switch to Mono Version ${{ parameters.monoVersion }}'
      inputs:
        targetType: 'inline'
        script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh ${{ parameters.monoVersion }}'
    - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_${{ parameters.xCodeVersion }}.app;sudo xcode-select --switch /Applications/Xcode_${{ parameters.xCodeVersion }}.app/Contents/Developer
   `

Can anyone suggest a workaround?  I am using "macOS-latest" agent. 

I would hate to revert back to 4.8 after so much effort to upgrade.

many thanks for prompt response

**Comment by PureWeen** [comment]
@developer9969 AllowsContinuousInteraction was added in ios 14 so you're either not on iOS 14 or you have an old version of Xamarin.iOS installed on your devops pipeline

**Comment by developer9969** [comment]
@PureWeen  thanks for replying

1. Pipeline : We are using Microsoft Hosted agent  (we have no control over what is installed)
2. Pool='macOS-latest'
I have the following on visual studio
![image](https://user-images.githubusercontent.com/16970109/105374733-ed3e4000-5bff-11eb-829d-13db77405616.png)

Am I missing the obvious?

thanks

**Comment by developer9969** [comment]
Hi 
the pipeline building is my last hurdle to move to 5 so that I can also use the community toolkit, kind of surprised nobody else is having this issue

One thing I dont understand as I have the following

- Pipeline : We are using Microsoft Hosted agent (we have no control over what is installed)
- Pool='macOS-latest'  (macos-10.15) which according to the document it has the latest installed
   https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md
- Visual studio iOS Project Deployment Target=12.0
- Visual Studio Version : 16.8.4
   And get the error 
`MTOUCH : error MT2101: Can't resolve the reference 'System.Void UIKit.UIPageControl::set_AllowsContinuousInteraction(System.Boolean)', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.IndicatorViewRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs1<Xamarin.Forms.IndicatorView>)'
in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. ]`

 Is this because of the code below.(total guess!) @jsuarezruiz 
![image](https://user-images.githubusercontent.com/16970109/105454452-c9b7db80-5c79-11eb-8480-f8d927b2627c.png)

**Question**
Given I seem to have all the latest stuff and I use the latest macOS pipeline why is it if I changed my Development target to 14.1 just to see if built I get
` MTOUCH : error MT0074: Xamarin.iOS 13.20.2 does not support a deployment target of 14.1 for iOS (the maximum is 13.6). 
 Please select an older deployment target in your project's Info.plist or upgrade to a newer version of Xamarin.iOS.
 `

Is the macOS 10.15really hosting the latest xamarin.iOS? 

Reverted to XF 4.8.1560 pipeline all built and all good.

thanks

**Comment by developer9969** [comment]
@PureWeen  hi there, 
do you have any suggestions?  I trying to establish if it's a problem at my end of if it's a pipeline/XF5 issue?
Given that I have all the latest I double checked and just works on XF4.8.x I have run out of ideas of what it could be.

thanks

**Comment by developer9969** [comment]
Hi all,
**does anyone know how to force the microsoft agent to use a particular version of xamarin.ios**?, it seems for some reasons it always picks up 13.20.2.2 and and wont build against XF5 , I want to force the (mac-os-latest) to use 14.6.0.15 or any 14 version

below is what I use
```
monoVersion: '6_12_0'
xCodeVersion: '12.3'

task: Bash@3
displayName: 'Switch to Mono Version ${{ parameters.monoVersion }}'
inputs:
targetType: 'inline'
script: 'sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh ${{ parameters.monoVersion }}'
bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_${{ parameters.xCodeVersion }}.app;sudo xcode-select --switch /Applications/Xcode_${{ parameters.xCodeVersion }}.app/Contents/Developer
```
`


many thanks

**Comment by PureWeen** [comment]
You can try using boots to install the latest xamarin.ios

https://github.com/jonathanpeppers/boots

If you don't run the select script at all does it work?

**Comment by developer9969** [comment]
@PureWeen  **that did the TRICK** . I commented it out that script and now it selects 14.8.0.3. 
MASSIVE thank you.  I checked the xamarin toolkit and they use that script too , nearly all the pipeline I saw use it.

Problem solved! but a bit confused

**Comment by jvalkyrie** [comment]
Thanks @developer9969 for posting about this issue and @PureWeen for the solution!

I was having the same exact error with `macOS-latest` after upgrading XF from 4.8 to 5 and it was due to the above script in my pipeline. Commenting this out fixed it :)

**Comment by dannythomas13** [comment]
Hi all.

I stumbled across this as I was facing build errors on Azure DervOps after moving to XF5. I had the following task:

`sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MonoVersion)`

And I could see that it was selecting Xamarin.iOS 13.18.2.1 

After disabling the task I could see that Xamarin.iOS 14.14.2.5 is now used and I was hopeful that all would be well but unfortunately the build is still failing. I would really appreciate it if someone could help as I'm worried I will have to rollback to XF4.

I am using the following XF version 5.0.0.2012

And getting the following errors/warnings:

_CompileToNative:
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/response-file.rsp 
  Xamarin.iOS 14.14.2.5 (d16-9: 3836759d4 using framework: /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk
  Process exited with code 1, command:
  /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -framework CoreFoundation -framework Security -framework SafariServices -framework ContactsUI -framework CoreTelephony -framework SystemConfiguration -framework Photos -framework OpenGLES -framework MobileCoreServices -framework MediaPlayer -framework ImageIO -framework GLKit -framework CoreText -framework CoreSpotlight -framework CoreLocation -framework CoreImage -framework CoreGraphics -framework QuartzCore -framework Contacts -framework AssetsLibrary -framework WebKit -framework UIKit -framework Foundation -framework CoreVideo -framework AVFoundation -framework CFNetwork -framework GSS -weak_framework AuthenticationServices /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/registrar.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/main.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Veridian.iOS.exe.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/mscorlib.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Mono.Security.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Xml.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Numerics.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Core.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Net.Http.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Drawing.Common.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Platform.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Core.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Data.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.ComponentModel.Composition.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Runtime.Serialization.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.ServiceModel.Internals.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Web.Services.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Xml.Linq.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Platform.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Autofac.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Wood.Veridian.Tablet.Core.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.Xaml.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.IO.Abstractions.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.IO.FileSystem.AccessControl.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Memory.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Runtime.CompilerServices.Unsafe.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Buffers.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Security.AccessControl.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Security.Principal.Windows.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Acr.UserDialogs.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/BTProgressHUD.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Newtonsoft.Json.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Polly.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Essentials.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/OpenTK-1.0.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Rg.Plugins.Popup.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Plugin.Media.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Serilog.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/SQLite-net.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/SQLitePCLRaw.core.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/SQLitePCLRaw.batteries_v2.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/SQLitePCLRaw.nativelibrary.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/SQLitePCLRaw.provider.dynamic_cdecl.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfImageEditor.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Core.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Licensing.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfPdfViewer.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Pdf.Portable.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Compression.Portable.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Text.Encoding.CodePages.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfProgressBar.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfRangeSlider.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Analytics.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.iOS.Bindings.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Analytics.iOS.Bindings.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Crashes.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AppCenter.Crashes.iOS.Bindings.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Serilog.Sinks.Async.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.AspNetCore.WebUtilities.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.Net.Http.Headers.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Microsoft.Extensions.Primitives.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Text.Encodings.Web.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Serilog.Sinks.File.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Xamarin.Forms.BehaviorsPack.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfAutoComplete.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfRichTextEditor.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Buttons.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfPicker.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfComboBox.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfPopupLayout.XForms.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Plugin.FilePicker.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfImageEditor.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/System.Json.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.Core.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfPdfViewer.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfBusyIndicator.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfRangeSlider.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfRangeSlider.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfRichTextEditor.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfComboBox.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Syncfusion.SfPopupLayout.XForms.iOS.dll.o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/AppCenter.a /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/AppCenterAnalytics.a /Library/Frameworks/Xamarin.iOS.framework/Versions/14.14.2.5/SDKs/MonoTouch.iphoneos.sdk/lib/libmonosgen-2.0.a /Library/Frameworks/Xamarin.iOS.framework/Versions/14.14.2.5/SDKs/MonoTouch.iphoneos.sdk/lib/libxamarin.a /Library/Frameworks/Xamarin.iOS.framework/Versions/14.14.2.5/SDKs/MonoTouch.iphoneos.sdk/lib/libmono-native-unified.a -force_load /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/AppCenterCrashes.a -force_load /Library/Frameworks/Xamarin.iOS.framework/Versions/14.14.2.5/SDKs/MonoTouch.iphoneos.sdk/lib/libapp.a -lsqlite3 -lc++ -Wl,-pie -arch arm64 -miphoneos-version-min=11.0 -isysroot /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -lz -liconv -lz -o /Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/obj/iPhone/Release/mtouch-cache/arm64/Veridian.iOS -u _xamarin_log -u _xamarin_find_protocol_wrapper_type -u _xamarin_release_block_on_main_thread -u _xamarin_get_block_descriptor -u _xamarin_IntPtr_objc_msgSend_IntPtr -u _xamarin_IntPtr_objc_msgSendSuper_IntPtr -u _UIApplicationMain
  Undefined symbols for architecture arm64:
MTOUCH : error MT5210: Native linking failed, undefined symbol: _AdjustTokenPrivileges. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _CloseHandle. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _CreateDirectoryW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _CreateWellKnownSid. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _DuplicateTokenEx. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _FindClose. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _FindFirstFileExW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _FormatMessageW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetCurrentProcess. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetFileAttributesExW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
  		
MTOUCH : error MT5210: Native linking failed, undefined symbol: _GetNamedSecurityInfoW. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in. [/Users/runner/work/1/s/Veridian.Xamarin/Veridian.iOS/Veridian.iOS.csproj]
