### ISSUE TITLE
[Bug] Shell.ItemTemplate and Shell.MenuItemTemplate are not loaded up properly

### ISSUE THREAD

**Issue by GeorgeVelikov** [xamarin/Xamarin.Forms#13497]
### Description

Custom item and menu item templates are not loaded up properly. To "fix" this, we can save the XAML file containing the Shell, prompting a hot reload which would properly load the templates

This seems to be related with using FontImages

### Steps to Reproduce

1. Add some ItemTemplate and MenuItemTemplate to the Shell
2. Run App with a flyout menu
3. Flyout menu has no styling

### Expected Behavior

Flyout menu has styling

![image](https://user-images.githubusercontent.com/45877509/105400168-7e231480-5c1c-11eb-9986-0117e572dd29.png)

### Actual Behavior

Flyout menu has no styling

![image](https://user-images.githubusercontent.com/45877509/105400222-8da25d80-5c1c-11eb-843d-ed80ab95c05d.png)

### Basic Information

- Version with issue:  5.0.0.1874 (XF 5) and 5.0.0.1905 (XF 5 SR 1)
- Last known good version: 4.8.0.1821 (XF 4.8 SR 6)
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 10 

### Workaround

You could probably call a manual layout on the shell once it has loaded

### Reproduction

[XF5ShellIssues.zip](https://github.com/xamarin/Xamarin.Forms/files/5851974/XF5ShellIssues.zip)

**Comment by GeorgeVelikov** [comment]
@PureWeen I have added a reproduction for this issue

[XF5ShellIssues.zip](https://github.com/xamarin/Xamarin.Forms/files/5851971/XF5ShellIssues.zip)

**Comment by PureWeen** [comment]
@GeorgeVelikov so I'm not super sure yet why this worked on 4.8 but `TemplateBinding` is only supposed to be used with ControlTemplates 

For your template all you need to do is this 

```xaml
        <DataTemplate
            x:Key="FlyoutMenuItemTemplate">
            <Grid
                Style="{StaticResource FlyoutGridStyle}">
                <Label
                    Grid.Column="0"
                    FontSize="24"
                    IsVisible="{Binding Icon.Glyph, Converter={StaticResource FalseIfNullConverter}}"
                    Style="{StaticResource FlyoutItemLabelStyle}"
                    Text="{Binding Icon.Glyph}" />

                <Label
                    Grid.Column="1"
                    VerticalTextAlignment="Center"
                    Style="{StaticResource FlyoutItemLabelStyle}"
                    Text="{Binding Title}" />
            </Grid>
        </DataTemplate>
 ```

**Comment by GeorgeVelikov** [comment]
@PureWeen Thanks, that does seem to work!
