### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SelvaKumar68** [xamarin/Xamarin.Forms#13502]
### Steps to Reproduce
We have Xamarin Forms application, in which we use Prism for navigation and to show Custom Display Alert.

For Many page the Prism.ShowDialog  Display alert as expected. But for few pages when Prism.ShowDialog get called we see only white screen on the View. We couldn't proceed any further.

On the Dialog page I did override all the available methods to see from where the view is not showing on screen... Below are the list of override flow it gone..

**Flow for Display Alert shown correctly:**
1. InvalidateLayout()
2. OnSizeAllocated()
3. OnChildAdded (Stack->(Label and Button))
4. ShouldInvalidateOnChildAdd(Stack)
5. InvalidateLayout()
6. OnSizeAllocated()
7. OnBindingContextChanged()
8. OnParentSet()
9. OnChildMeasureInvalidate()
10. TabStopsDefaultValueCreator()
11. TabIndexDefaultValueCreator()
12. OnMeasure()
13. OnSizeRequest()
14. OnMeasure()
15. OnSizeRequest()
16. OnSizeAllocated()
17. LayoutChildren()

**For the DisplayAlert shown white screen:**
1. InvalidateLayout()
2. OnSizeAllocated()
3. OnChildAdded  (Stack->(Label and Button))
4. ShouldInvalidateOnChildAdd(Stack)
5. InvalidateLayout()
6. OnSizeAllocated()
7. OnBindingContextChanged()
8. OnParentSet()

After the OnParentSet(), there is no other override method called during white screen shows on screen.

_Note : This white screen issue happens only on few selected page._

I have checked the Parent View Hierarchy of the page where DisplayAlert shown and not shown... Both were same without any difference...

Can I get any suggestions on proceeding with this white page issue?

**Comment by PureWeen** [comment]
@SelvaKumar68 can you move this issue over to 

https://github.com/PrismLibrary/Prism

So @dansiegel can look at it and then tell me how it's my fault :-p

**Comment by dansiegel** [comment]
ROFL... now the pressure is on to come up with a reason, I mean you're totally asking me to give you one 😆
