### ISSUE TITLE
Dismissing a Modal Page while passing data when using Shell goes back *twice* on the nav stack, instead of once, breaking app navigation

### ISSUE THREAD

**Issue by eddieyanez** [xamarin/Xamarin.Forms#13506]
### Description
For a given navigation stack of **Page A** > **Page B** > **Modal Page**, dismissing the Modal Page with data (e.g. below) navigates all the way back to **Page A** instead of **Page B**. Unfortunately, this issue has now broken the app.
`await Shell.Current.GoToAsync("..?Data=test");`

Dismissing the page (e.g. below) without data navigates back to Page B as expected.
`await Shell.Current.GoToAsync("..");`

### Steps to Reproduce

1. Create a sample Xamarin Forms project.
2. Create Page A
3. Create Page B
3.  Create Modal Page
4. Add button to Page A that navigates to Page B
5. Add button to Page B that navigates to Modal Page
6. Change Modal page's Presentation Mode to 'ModalAnimated'
7. Add two buttons to the Modal Page, one should dismiss the Modal Page without any data e.g. GoToAsync(".."), the other should dismiss the Modal Page while passing data e.g. GoToAsync("..?something=value")
8. (Optional) Add a QueryProperty to Page B with Debug.WriteLine to track navigation

Basic bare bones sample solution attached: [TestSolution.zip](https://github.com/xamarin/Xamarin.Forms/files/5857990/TestSolution.zip)

### Expected Behaviour
Dismissing the modal with data should go back once on the navigation stack.

### Actual Behaviour
Dismissing the modal page with data goes back twice on the navigation stack.

This isn't an issue on Xamarin.Forms version 5.0.0.1874.

### Basic Information

- Version with issue: 5.0.0.1905
- Last known good version: 5.0.0.1874
- Platform Target Frameworks:
  - iOS:  14.3
  - Android: 10.0
  - UWP:  N/A
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: N/A
- Affected Devices: N/A

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.8.5 (build 18)
Installation UUID: 964ecb5b-4953-4ac1-ad89-9e7ffb102d32
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.102/Sdks
SDK Versions:
	5.0.102
	5.0.101
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.2
	5.0.1
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.405

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.3 (17715)
Build 12C33

=== Xamarin.Mac ===

Version: 7.2.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:04-0500

=== Xamarin.iOS ===

Version: 14.8.0.3 (Visual Studio Community)
Hash: c51fabee8
Branch: xcode12.3
Build date: 2020-12-10 21:05:05-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.26 (Visual Studio Community)
Commit: xamarin-android/d16-8/a36ce73
Android SDK: /Users/eddieyanez/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/eddieyanez/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808050018
Git revision: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5
Build date: 2021-01-07 14:45:50-05
Build branch: release-8.8
Xamarin extensions: e83d51ec050ffcdd573462fc1889b58cfe1a5ad5

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.6


```

</details>

### Screenshots

None, but sample solution is attached.

### Reproduction Link

None, but sample solution is attached.

### Workaround

Add a "/" to the navigation path

```C#
 await AppShell.Current.GoToAsync("../?Data=test");
 ```

**Comment by PureWeen** [comment]
@eddieyanez thank you for logging this!!

For now if you want to workaround the issue it looks like you can do the following

" await AppShell.Current.GoToAsync("../?Data=test");"

**Comment by eddieyanez** [comment]
No worries. Thanks for looking at the issue so quickly.

The workaround works for me.
