### ISSUE TITLE
[Bug] CollectionView ui is broken, when the grid is change

### ISSUE THREAD

**Issue by Pelinalpp** [xamarin/Xamarin.Forms#13512]
### Description
CollectionView is broken (ui getting broken), when the grid is change on iOS.
Collectionview's grid doesn't broken on Android. But when I change grid, it turns back at the top of the list. 

### Steps to Reproduce

1. Create a Xamarin Forms project
2. Create a collectionview, that can be one or more than grid. (This can be changed at runtime with a button)
Note: Collectionview elements have different views when there is one grid or when there are multiple grids. For example: collectionview's items have thumbnail and title. When collectionview is one grid, thumbnail is to the left of the title. When collectionview is multiple grid, thumbnail is top on the title. This change with styles, when the click button.
3. Click the button for change grid count of collectionview

This problem is detailed in the following link:
https://stackoverflow.com/questions/65791360/collectionview-is-broken-when-i-change-grid?noredirect=1#comment116375616_65791360

### Expected Behavior
![flowlist](https://user-images.githubusercontent.com/24781631/105611421-4c4db180-5dc6-11eb-9ee1-878207bbd2f4.gif)

### Actual Behavior
![collectionview_broken](https://user-images.githubusercontent.com/24781631/105611413-3cce6880-5dc6-11eb-9dfa-e67745e65174.gif)

**Comment by rmarinho** [comment]
Hi @Pelinalpp seems there are a couple of details there, can you please upload  a small reproduction to help us understand the problem? 

Thanks

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
