### ISSUE TITLE
[Bug] Android: App gets killed during Application.OnSleep operation

### ISSUE THREAD

**Issue by omghb** [xamarin/Xamarin.Forms#13531]
Issue: App gets killed before my `Application.OnSleep` override completes with saving the current state into a JSON file.
Version: Xamarin.Forms 5.0.0

The current Xamarin Forms implementation for `OnSleep` is called when the Activity goes from `OnPause` to the `OnStop` state. See:
https://github.com/xamarin/Xamarin.Forms/blob/3276a592381e579d9c065945d6efdccd68941d7c/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L521-L522

The [Android Activity documentations](https://developer.android.com/reference/android/app/Activity) says:

> Note the "Killable" column in the above table -- for those methods that are marked as being killable, after that method returns the process hosting the activity may be killed by the system at any time without another line of its code being executed. Because of this, you should use the onPause() method to write any persistent data (such as user edits) to storage.

Solution: As `OnStop` is marked as `killable` the `Application.OnSleep` method should be called within the `OnPause` state instead of the `OnStop` state.

**Comment by rmarinho** [comment]
Hi @omghb  i just tested this in our repo and it seems it's able to save the properties without a problem. 

Can you please upload a small reproduction of the issue so we can take a look.

Thanks

**Comment by omghb** [comment]
An important thing to mention is that this issue happens but quite seldom -> it is not reproducible. 

It depends on the decision of Android kill the app instead of completing OnStop first.

**Comment by PureWeen** [comment]
@omghb if you do your saving from the native `OnPause` life cycle do you notice that that works every time and never crashes?

**Comment by omghb** [comment]
I see some issues in Telemetry (AppCenter.ms) when the App loads the persisted state (trying to load an empty json file). So I believed that this issue might be the cause of it.

Now, I'm using `OnPause` for saving the state. This solution might have reduced the reported telemetry issues but I still see some state persistence issues. The still occurring persistency issues might be another bug.

I'm not sure if my change to use `OnPause` has improved it. 

Infos: 
- Target Framework: Android 10 (Q)
- XF 5.0.0.2012

In my opinion the [Android documentation](https://developer.android.com/reference/android/app/Activity) is here a bit confusing: 
> ... the activity may be killed by the system at any time without another line of its code being executed. Because of this, you should use the onPause() method to write any persistent data (such as user edits) to storage.

> Starting with Honeycomb, an application is not in the killable state until its onStop() has returned. This impacts when onSaveInstanceState(android.os.Bundle) may be called (it may be safely called after onPause()) and allows an application to safely wait until onStop() to save persistent state.

> For applications targeting platforms starting with Build.VERSION_CODES.P onSaveInstanceState(android.os.Bundle) will always be called after onStop(), so an application may safely perform fragment transactions in onStop() and will be able to save persistent state later.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
