### ISSUE TITLE
[Enhancement] Comma or Semicolon separated Styles on OnIdiom and OnPlatform

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#13539]
## Summary
Instead of this

```
   WidthRequest="{OnIdiom Phone=24,
                                           TV=24,                                          
                                           Default=48}" />
```

this

```
   WidthRequest="{OnIdiom Phone;TV=24,                                      
                                           Default=48}" />
```

I am not sure if comma is possible as it is used already on other purpose but maybe a semicolon can be used.

**Comment by GalaxiaGuy** [comment]
I suspect this is not reasonably achievable, since the exact syntax used is general to `MarkupExtension`s, and is not specific to `OnIdiom`

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
