### ISSUE TITLE
[Bug] Editor Placeholder is duplicated (again) in Xamarin Forms 5

### ISSUE THREAD

**Issue by SWarnberg** [xamarin/Xamarin.Forms#13541]
### Description
The placeholder in the Editor is yet again duplicated, and overlapped, in Xamarin Forms 5. This was originally reported in [https://github.com/xamarin/Xamarin.Forms/issues/5822](https://github.com/xamarin/Xamarin.Forms/issues/5822) and fixed in [https://github.com/xamarin/Xamarin.Forms/pull/5823](https://github.com/xamarin/Xamarin.Forms/pull/5823).
However, it seems to be back now:

![image](https://user-images.githubusercontent.com/26246346/105839124-4ed02700-5fd1-11eb-829a-c6b31cf2f91b.png)

![image](https://user-images.githubusercontent.com/26246346/105841094-62c95800-5fd4-11eb-9ffe-4fc733f08894.png)

### Steps to Reproduce

1. Upgrade to Xamarin Forms 5
2. Use Editor in a view with Visual Material configured.
3. Run project.

```
<Editor Margin="5" BackgroundColor="White" Text="{Binding Notes}"
             Placeholder="{x:Static resources:AppResources.Notes}" AutoSize="TextChanges"></Editor>

```
### Basic Information

- Version with issue: 5.0.0.1931
- Last known good version: 4.8.0.1687
- Platform Target Frameworks:
  - iOS:  
  - Android:  10.0
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
  - Xamarin.Forms 5.0.0.1931
  - Xamarin.Essentials 1.6.1
  - Xamarin.Forms.Visual.Material 5.0.0.1931

**Comment by SWarnberg** [comment]
Just tested with latest NuGets, still same issue, so I updated description above.

**Comment by rmarinho** [comment]
Hello, i just tested this on 5.0.0 and i can't reproduce, can you upload a simple sample. 

![image](https://user-images.githubusercontent.com/1235097/105844925-e46bb680-5fd1-11eb-95cf-c4940e358b77.png)


Thanks

**Comment by SWarnberg** [comment]
Did you apply Visual Material in your test?
This is how it looks in our production version with 4.8:

![image](https://user-images.githubusercontent.com/26246346/105850941-b17dee80-5fe2-11eb-99f0-f04da11230fd.png)

Exact same code, the only change between the branches are the upgrade of the NuGet packages as specified.

Will see if I can get the time to create a sample.

**Comment by ClaytonIndustries** [comment]
This should be enough to repro 

`<Editor Placeholder="Anything" Visual="Material" />`

**Comment by PLBSoft** [comment]
Hello @rmarinho
The issue can be reproduced with 
 https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/VisualDemos => Editors

### Expected behavior
![image](https://user-images.githubusercontent.com/11420054/105853319-d7f15900-5fe5-11eb-9697-1e2a88916413.png)

### Actual behavior
Since Xamarin.Forms and Xamarin.Forms.Visual.Material 5.0.0.1874
![image](https://user-images.githubusercontent.com/11420054/105852234-81374f80-5fe4-11eb-96ae-fc020eed73cb.png)

Thanks

**Comment by SWarnberg** [comment]
Exactly. Or use attached project. Go to item details page.
[Xamarin Forms 5 Editor.zip](https://github.com/xamarin/Xamarin.Forms/files/5873736/Xamarin.Forms.5.Editor.zip)

**Comment by rmarinho** [comment]
Oh it's with material, ok, thanks.

**Comment by bcardosodeoliveira** [comment]
temp solution....

`[assembly: ExportRenderer(typeof(Editor), typeof(CustomEditorRenderer))]
namespace Calculadora.Droid
{
    public class CustomEditorRenderer_temp : MaterialEditorRenderer
    {
        public CustomEditorRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Editor> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null && Control != null)
                Control.EditText.SetHintTextColor(global::Android.Graphics.Color.Transparent);
        }
    }
}`

**Comment by bcardosodeoliveira** [comment]
temp solution...

```
[assembly: ExportRenderer(typeof(Editor), typeof(CustomEditorRenderer))]
namespace xxx.Droid
{
    public class CustomEditorRenderer: MaterialEditorRenderer
    {
        public CustomEditorRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Editor> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null && Control != null)
            {
                Control.EditText.SetHintTextColor(global::Android.Graphics.Color.Transparent);
            }
        }
    }
}
```

**Comment by PureWeen** [comment]
Yea this looks like it's an upstream bug

If I update the sample project to 
```XAML
<PackageReference Include="Xamarin.Google.Android.Material">
      <Version>1.2.1.1</Version>
    </PackageReference>
    ```
    
    the issue no longer happens
