### ISSUE TITLE
Use of custom NavigationPage class in Xamarin.Forms crashes in iOS build with System.MissingMethodException: Method 'UIKit.UINavigationBar.set_LargeTitleTextAttributes' not found.

### ISSUE THREAD

**Issue by danishaliqau** [xamarin/Xamarin.Forms#1354]
Use of custom NavigationPage class in Xamarin.Forms crashes in iOS build with following error only in latest XF version :-

Unhandled Exception:
System.MissingMethodException: Method 'UIKit.UINavigationBar.set_LargeTitleTextAttributes' not found.

Steps to reproduce :-
1. Create sample Xamarin.Forms app with XF v2.5.0.91635 OR with XF v2.5.0.121934
2. Create custom NavigationPage class by extending NavigationPage.
3. Use this custom class to add ContentPages of app in Navigation. On launch app crashes only in iOS with System.MissingMethodException: Method 'UIKit.UINavigationBar.set_LargeTitleTextAttributes'
error.

iOS app is working fine with XF v2.3.3.193.

Environment details as below :-

Microsoft Visual Studio Professional 2015
Version 14.0.25420.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-50050-34434-AA417
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-50050-34434-AA417
Microsoft Visual Basic 2015

Visual C# 2015   00322-50050-34434-AA417
Microsoft Visual C# 2015

Visual C++ 2015   00322-50050-34434-AA417
Microsoft Visual C++ 2015

Visual F# 2015   00322-50050-34434-AA417
Microsoft Visual F# 2015

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.2.0.11
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   3.4.4
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2015 ENU   14.0.23025
Microsoft Office Developer Tools for Visual Studio 2015 ENU

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.34.0
TypeScript tools for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   4.5.0.486 (fec6f88)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.3.1.2 (9dbc4c5)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.iOS   10.10.0.37 (ad35de4)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by danishaliqau** [comment]
it is happing int 2.5.0.121934 release too

**Comment by rmarinho** [comment]
Is your Xamarin.iOS updated ? on your bot and VS ? do you have XCode9_1 ?

**Comment by danishaliqau** [comment]
I have XCode Version 8.3.3

**Comment by mattclarkie** [comment]
We've got a custom (subclassed) NavigationPage and this isn't affecting us so it's not down purely to that.

**Comment by danishaliqau** [comment]
I see, wel I have update the XCODE to 9.2, it is working fine now
thank you.
