### ISSUE TITLE
[Enhancement] Allow specification of an event source with the WeakEventManager

### ISSUE THREAD

**Issue by AlexanderMelchers** [xamarin/Xamarin.Forms#13545]
## Summary
With XF 5.0 the `WeakEventManager` has been made public. I highly laud this development, as this is a step in the right direction to expire my custom implementation. However, the current Forms' implementation can only be used within the event-source, not the listener. Adding the possibility of specifying an event-source would remedy this, and would greatly extend the usefulness of the `WeakEventManager`.

## API Changes

Provide overloads of the below methods that take an additional `source`-parameter to specify a different event-source from the current class:

```
public void AddEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName = null) where TEventArgs : EventArgs;
public void RemoveEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName = null) where TEventArgs : EventArgs;
```

New methods would have below signature:

```
public void AddEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, object source, [CallerMemberName] string eventName = null) where TEventArgs : EventArgs;
public void RemoveEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, object source, [CallerMemberName] string eventName = null) where TEventArgs : EventArgs;
```

When the `source`-parameter is specified, the `WeakEventManager` will subscribe to the named event within the passed `source`-object, rather than in its parent-object.

## Intended Use Case
Intended use is for cases where the event within the event-source that is to be weakly subscribed to cannot be, or is not desired to be, made into a weak event. This may be in cases where external libraries are involved that an event-consumer might weakly want to listen to; or in cases where only a small number of event listeners need to subscribe to an event in a weakly bound manner, with the rest of the subscriptions functioning normally. Although typically an event-listener would be able to unsubscribe from an event in cases where the event-source outlives the -consumer, this is not always possible - in particular with automatically updated collections.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
