### ISSUE TITLE
[Bug] Shell.Items implicit conversion blocks hot reload of items

### ISSUE THREAD

**Issue by etvorun** [xamarin/Xamarin.Forms#13553]
### Description
Once Shell converts items -  e.g. MenuItem to MenuShellItem - there is no way to modify MenuItem via hot reload as there is no way to get back to MenuItem from MenuShellItem just by analyzing XAML.

### Steps to Reproduce

1. Open attached project in VS 
[XamApp3.zip](https://github.com/xamarin/Xamarin.Forms/files/5876758/XamApp3.zip).
2. Set Debug x86. Make sure Hot Reload "change only" is enabled.
3. Build and run.
4. Open AppShell.xaml.
5. Find StyleClass="MenuItemLayoutStyle" and delete it.
### Expected Behavior
There are no error squiggles.

### Actual Behavior
An error squiggle appears "Object does not match target type" 

### Basic Information
When Xamarin parses XAML like
  <Shell ...> 
      <MenuItem StyleClass="MenuItemLayoutStyle"/>
      <FlyoutItem .../>
it uses implicit operators to convert visuals to ShellItems, e.g. MenuItem to MenuShellItem. But when user modifies MenuItem property VS assumes that it will find MenuItem - no MenuShellItem (an internal class) in Shell.Items collection. Thus it attemps to modify MenuItem.StyleClass on MenuShellItem object.
In order to properly support such Hot Reload scenarios we need a way to get back from MenuShellItem to MenuItem. In general Hot Reload uses implicit operators when setting property values to convert value object. Hot Reload could try to do something similar with target objects. However there are no "convert back" implicit operator. And even if they exists it is not clear that they should be used as we are likely to modify created-on-the-fly object which will be garbage collected right away.

**Comment by PureWeen** [comment]
@etvorun if MenuShellItem was made public would that be enough?

**Comment by etvorun** [comment]
@PureWeen unfortunately not. Hot Reload instructions are generated in VS process (devenv.exe). Because  we have much more information needed to generate incremental changes there. VS is not aware of any implicit transformation happening at runtime. So when VS sees that user changed <MenuItem StyleClass="Foo"> to "Bar" it assumes that it will find MenuItem and it can use reflection to get MenuItem.StyleClass property and then use the method to set value.

We can try working around this issue by rebuilding (deleting+adding) MenuItem every time any of its properties change. This would happen every time  regardless where MenuItem is used. If there are other scenarios like this then we would need to know about them so that we can do similar workarounds.

Said that it would be nice to minimize use of implicit operators in Xamarin.Forms in places relevant to Hot Reload.
