### ISSUE TITLE
[Bug] [iOS] CollectionView does not display items if `IsVisible` modified via a binding/trigger

### ISSUE THREAD

**Issue by dmariogatto** [xamarin/Xamarin.Forms#13551]
### Description

Bind CollectionView to an item source, also bind `IsVisible` to an initially false value. When the binding for `IsVisible` changes to `true` the CollectionView does not display its items. (similar to #13203) 

### Steps to Reproduce

```xml
    <Grid RowDefinitions="*,*,*">
        <!--  Works 👍 (EDIT: doesn't work when IsVisible="false"  -->
        <CollectionView
            x:Name="ItemsView1"
            IsVisible="True" <!-- EDIT: this should be 'false' -->
            ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

        <!--  Does not work 👎  -->
        <CollectionView
            x:Name="ItemsView2"
            Grid.Row="1"
            IsVisible="{Binding Items.Count, Converter={StaticResource IntToBoolConverter}}"
            ItemsSource="{Binding Items}">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

        <!--  Does not work 👎  -->
        <CollectionView
            x:Name="ItemsView3"
            Grid.Row="2"
            ItemsSource="{Binding Items}">
            <View.Triggers>
                <DataTrigger
                    Binding="{Binding Items.Count}"
                    TargetType="View"
                    Value="0">
                    <Setter Property="IsVisible" Value="False" />
                </DataTrigger>
            </View.Triggers>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Frame>
                        <Label Text="{Binding}" />
                    </Frame>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </Grid>
```

### Expected Behavior

Should display items after visibility is changed to `true`. 

### Actual Behavior

No items displayed.

### Basic Information

- Version with issue: 4.8.0.1821
- Last known good version: 4.8.0.1687
- Platform Target Frameworks: 
  - iOS:  14.2

### Workaround

N/A (probably can toggle via code behind)

### Repro link
Repeo: [Issue13203v2.zip](https://github.com/xamarin/Xamarin.Forms/files/5876344/Issue13203v2.zip)

**Comment by AlleSchonWeg** [comment]
@dmariogatto
Is the CollectionView working, if you insert a space somewhere in xaml and save it while the app is running?

**Comment by dmariogatto** [comment]
I made a mistake in the repro project, that first CollectionView should have `IsVisible="False" `, which means it no longer works as expected (`IsVisible="True"` is set in the code behind after binding items, so pretty much the same as #13203).

@AlleSchonWeg 
If I trigger a hot reload, the bottom two collections display correctly.

**Comment by AlleSchonWeg** [comment]
> If I trigger a hot reload, the bottom two collections display correctly.

I had the same problem. A litte delay helps me to workaround this issue: https://github.com/xamarin/Xamarin.Forms/issues/13203#issuecomment-754450816

**Comment by Deepfreezed** [comment]
I am having the same issue on iOS. Using version 5.0.0.1931. Have to make the element visible, add some delay, then bind for it to work. CollectionView view also disappears if I change visibility state of another element that is in the same container.

**Comment by developer9969** [comment]
Hi everyone, just managed to  upgrade to XF5 and went through quite an excercise to find out that we have this visibility issue on the collectionView when we use the "IsVisible" flag to us is a showstopper and I might have to revert to 4.8 unless there is  a workaround. Does anyone know if this is been looked at and planned for next service release?

**Comment by Tommigun1980** [comment]
> Hi everyone, just managed to upgrade to XF5 and went through quite an excercise to find out that we have this visibility issue on the collectionView when we use the "IsVisible" flag to us is a showstopper and I might have to revert to 4.8 unless there is a workaround. Does anyone know if this is been looked at and planned for next service release?

@developer9969 I found one workaround to the IsVisible bug (https://github.com/xamarin/Xamarin.Forms/issues/13548), but it can be cumbersome to implement in certain places. But maybe it can help even a tiny bit?

**Comment by developer9969** [comment]
@Tommigun1980  hi there thanks for your reply and suggestion
 If I can avoid reverting to 4.8  and have a temporary workround that woud be great,currently my ItemSource is set in xaml with binding in View Model.

So somewhow I have to do below in my View CodeBehind, right?
```
var items = this.myCollectionView.ItemsSource;
this.myCollectionView.ItemsSource = null;
this.myCollectionView.ItemsSource = items;
```
Just hope they do a service release very soon as this breaks at least 10 pages in my app.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 hi there thanks for your reply and suggestion
> If I can avoid reverting to 4.8 and have a temporary workround that woud be great,currently my ItemSource is set in xaml with binding in View Model.
> 
> So somewhow I have to do below in my View CodeBehind, right?
> 
> ```
> var items = this.myCollectionView.ItemsSource;
> this.myCollectionView.ItemsSource = null;
> this.myCollectionView.ItemsSource = items;
> ```
> 
> Just hope they do a service release very soon as this breaks at least 10 pages in my app.

Hi. I’m also hoping for a fix and Hartez seems to just have committed one.

But in the interim yeah, you could try setting the ItemsSource to null and back to the value after toggling IsVisible. I am not 100% sure if the hack applies to this case as well, but I suspect these issues may be related as they all are very similar and started to happen in XF5 so it’s probably worth a try.
In my case force re-setting the ItemsSource in the code-behind circumvents the problem, it’s not elegant or performant but at least it works.

And I hope Hartez’s fix solves https://github.com/xamarin/Xamarin.Forms/issues/13548 as well.

**Comment by Eltee-Taiwo** [comment]
> > @Tommigun1980 hi there thanks for your reply and suggestion
> > If I can avoid reverting to 4.8 and have a temporary workround that woud be great,currently my ItemSource is set in xaml with binding in View Model.
> > So somewhow I have to do below in my View CodeBehind, right?
> > ```
> > var items = this.myCollectionView.ItemsSource;
> > this.myCollectionView.ItemsSource = null;
> > this.myCollectionView.ItemsSource = items;
> > ```
> > 
> > 
> > Just hope they do a service release very soon as this breaks at least 10 pages in my app.
> 
> Hi. I’m also hoping for a fix and Hartez seems to just have committed one so that’s good.
> 
> But in the interim yeah, you could try setting the ItemsSource to null and back to the value after toggling IsVisible. I am not 100% sure if the hack applies to this case as well, but I suspect these issues may be related as they all are very similar and started to happen in XF5 so it’s probably worth a try.
> In my case force re-setting the ItemsSource in the code-behind circumvents the problem, it’s not elegant or performant but at least it works.
> 
> And I hope Hartez’s fix solves #13548 as well.

One more note on this, in my case I had to add delays between setting it to null and adding the new values for the UI to catch up. Hopefully that helps someone too until we hear back back from someone on when to expect a fix for this.

```
var items = this.myCollectionView.ItemsSource;
this.myCollectionView.ItemsSource = null;
await Task.Delay(100); //I tried 10 and 1 but they didn't work for me
this.myCollectionView.ItemsSource = items;
await Task.Delay(100);
```

**Comment by rd09** [comment]
I am experiencing the same issue on version 4.8.0.1821.

**Comment by Huaba93** [comment]
@jfversluis @davidortinau could you please fix this in the upcoming SR? Still an issue that needs really ugly workarounds

**Comment by jfversluis** [comment]
@Huaba93 does #14384 have anything to do with this by any chance?
