### ISSUE TITLE
Xamarin Forms App Hangs if iOS Permission Dialog Shown During Form OnAppearing Override

### ISSUE THREAD

**Issue by Yortw** [xamarin/Xamarin.Forms#13550]
### Description
If an iOS permission dialog (specifically the 'local network' permission request, but I suspect any permission will do it) is shown due to code running in the OnAppearing override of a form then the app will hang after the dialog is dismissed. It does not matter if you grant or deny permission, the dialog will close but the app will then be unresponsive to touch and animations won't play etc. Effectively the UI is disabled (though looks 'normal') and does not recover. There is no error or other indicator that the problem is caused by running what is otherwise valid code inside the OnAppearing override, so this is an extremely tricky/time consuming problem to solve when first encountered.

### Steps to Reproduce

1. Create a Xamarin Forms app

2. Add second form to the app. Place a button on the main form that navigates to the second form. (We used a navigation page as the root page).
 
3. In the second form override the OnAppearing event and write some code that will cause iOS to show a permission dialog (trying to send a multicast udp package defintely does it, but trying to access the camera/register for push notifications etc. will likely also work). Ensure all permissions are correctly declared in the plist.info etc. Place some interactive controls on the second form, i.e a button, slider, toggle switch etc.

3. Run the app on an iOS device (iOS 14 or later if using networking code, as the local network permission was only added in iOS 14). The first time it is deployed to the device and run, when you click the button to show the second form iOS will show the permission dialog. Grant or deny permission via the dialog.

### Expected Behavior
The app should resume after the dialog is dismissed and all controls should be responsive to touch etc.
If that's not possible, then I feel an exception should thrown to indicate to the developer what the problem is and how to fix it.
If that's not possible then maybe a .Net Analyser to detect this pattern and warn about it would help?

### Actual Behavior
Once the dialog is dismissed, the XF app is brought back to the foreground but none of the controls on screen are active. The UI is dead to touch input. You can't do anything but force close the app.

Note: This only happens on the first run after the app is cleanly deployed. On subsequent runs the permission has already been granted or denied so iOS does not show the permission dialog, and the app does not hang. To reproduce again you must uninstall the app before deploying agian.

### Basic Information

- Version with issue: VS 2019, Xamarin Forms 4.8.0.1821
- Last known good version: None.
- Platform Target FrameworksiOS
  - iOS:  
  - Android: 9.0 (but I've only seen the problem on iOS, may not be an issue on Android)
  - UWP:  N/A
- Affected Devices: iOS devices running iOS 14+ (actually using an iPod for development and production, but should be the same on an iPhone/iPad etc)

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019
Version 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA814
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.557.25636
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Sandcastle Help File Builder   SHFB
Visual Studio integration for the Sandcastle Help File Builder.
https://GitHub.com/EWSoftware/SHFB

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Workaround

Moving the code from OnAppearing to another location, or running it on a timer/task callback so it does not execute in the call path of OnAppearing fixes the symptom, but it's knowing to do this that is the problem.

**Comment by rmarinho** [comment]
Hi @Yortw thanks for your report, I m having troubles reproducing this issue. can you please upload a small sample showing how to get to that state. 

Thanks

**Comment by Yortw** [comment]
Hi,

I've tried creating a repro (which I thought would be no problem) but unfortunately haven't been able to. I can repro the issue in a production app (which sadly I cannot share) but when I try to create a simple reproduction the problem does not occur. I guess there is at least one more requirement I don't yet understand that is needed in order to reproduce the issue.

**Comment by PureWeen** [comment]
@Yortw unfortunately we probably won't be able to narrow this one down without a reproduction. You might try commenting out various parts of your app until it no longer freezes since you aren't able to reproduce this with a fresh app.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
