### ISSUE TITLE
[Bug] Shell FlyoutItem and ShellContent Icon

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#13559]
Icons with embedded resources do not work in shell side menu. Sometimes they appear and sometimes they don't, the side menu also becomes slow.

Here is the topic thread:
https://docs.microsoft.com/en-us/answers/questions/245372/shell-flyoutitem-and-shellcontent-icon.html

Tested on a Xiaomi mi6

Example:
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/5880527/App1.zip)

**Comment by rmarinho** [comment]
Hello @angelru  do you mind upload a small reproduction of this issue . 

Thanks

**Comment by angelru** [comment]
@rmarinho I already uploaded an example sample

**Comment by rmarinho** [comment]
Thanks. 
When I run the sample I see the icons, do I need to do anything special to try reproduce ?

**Comment by angelru** [comment]
where have you tried it? the problem appears in both of my physical phones. You can also see the thread that I wrote in the official forum that they claim that the same problem happens to them.
https://docs.microsoft.com/en-us/answers/questions/245372/shell-flyoutitem-and-shellcontent-icon.html

**Comment by angelru** [comment]
@rmarinho

**Comment by rmarinho** [comment]
Hey i tested on Samsung S8, and Pixel 2. Android 9 . 

Can you try the latest SR3 5.0.0.2012 @angelru  we updated a little bit the list of flyout items .

@PureWeen  any ideia about this? could be device dependent ?

**Comment by angelru** [comment]
> Hey i tested on Samsung S8, and Pixel 2. Android 9 .
> 
> Can you try the latest SR3 5.0.0.2012 @angelru we updated a little bit the list of flyout items .
> 
> @PureWeen any ideia about this? could be device dependent ?

now seems to be working fine with the latest version of xamarin forms.
