### ISSUE TITLE
[Bug] RadioButton should update IsChecked property (to visually show selection) when SelectedValue is set from VM side

### ISSUE THREAD

**Issue by EP01** [xamarin/Xamarin.Forms#13558]
### Steps to Reproduce

1. Take sample `RadioButton` project VM [here](https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/RadioButtonDemos/RadioButtonDemos/AnimalViewModel.cs).
2. Modify to set the property `Selection` to a valid value on VM creation.
3. Notice that the View does not have any Radio Buttons selected.

### Expected Behavior

The radio button corresponding to the value of Selection should be selected on entry.

### Actual Behavior

The radio button is not selected.

### Basic Information

- Version with issue: 5.0.0.1931
- Platform Target Frameworks:
  - Only tried with Android 10, but assume it's present on all platforms.

### Workaround

Add a `DataTrigger` to each `RadioButton` which manually changes `IsChecked` when `Selection` changes.

```
<StackLayout Margin="10"
                 RadioButtonGroup.GroupName="{Binding GroupName}"
                 RadioButtonGroup.SelectedValue="{Binding Selection}">
        <Label Text="What's your favorite animal?" />
        <RadioButton Content="Cat"
                     Value="Cat" 
                     IsChecked="False">
            <RadioButton.Triggers>
                <DataTrigger TargetType="RadioButton"
                              Binding="{Binding Selection}"
                              Value="Cat">
                    <Setter Property="IsChecked"
                         Value="True" />
               </DataTrigger>
            </RadioButton.Triggers>
        </RadioButton>
</StackLayout>
```

**Comment by rmarinho** [comment]
Oh you don't need the trigger ,  RadioButtonGroup.SelectedValue is what selects the proper radio button.

If you check that's set on the codebehind of the page 

https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/RadioButtonDemos/RadioButtonDemos/GroupedRadioButtonsViewModelPage.xaml.cs#L13

**Comment by Jared-Aus** [comment]
Same issue for me - nothing is checked initially. In my case I'm binding to an enum and not using codebehind.

**Comment by Painwraith** [comment]
I have the same issue, any known solution?
