### ISSUE TITLE
[Bug] Buttons with Visual="Material" and FontImageSource are transparent by default

### ISSUE THREAD

**Issue by giosandev** [xamarin/Xamarin.Forms#13556]
### Description
Buttons with Visual="Material" and FontImageSource are transparent by default instead of normal as usual

### Steps to Reproduce
Declare a button like this:
`<Button    
                    WidthRequest="70"
                    HeightRequest="70"
                    CornerRadius = "35"
                    BackgroundColor="{x:Static helpers:Colors.ButtonBgColor}"
                    TextColor="{x:Static helpers:Colors.ButtonTextColor}"
                    BorderColor="{x:Static helpers:Colors.ButtonBorderColor}"
                    BorderWidth="0.3"
                    ImageSource="{FontImage Color={Static Member=helpers:Colors.ButtonTextColor}, FontFamily={StaticResource Key=MaterialDesignFont}, Glyph={Static Member=helpers:ContainerIconFont.QrcodeScan}}"
                    Clicked="QRCodeBtn_Clicked" Visual="Material"/>`

### Expected Behavior
The button should appear in normal state
### Actual Behavior
The button appears as disabled i.e. semi-transparent

### Basic Information

- Version with issue: all 5,x
- Last known good version: 4.8.0.1821
- Platform Target Frameworks: 
  - Android: tested 7 to 10

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019
Versione 16.8.4
VisualStudio.16.Release/16.8.4+30907.101
Microsoft .NET Framework
Versione 4.8.03752

Edizione installata: Enterprise

ASP.NET and Web Tools 2019   16.8.557.25636
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.557.25636
Per altre informazioni, vedere https://www.asp.net/

Azure Functions and Web Jobs Tools   16.8.557.25636
Azure Functions and Web Jobs Tools

Estensione Debug snapshot   1.0
Informazioni dettagliate su estensione Debug snapshot di Visual Studio

Estensione IntelliCode   1.0
Informazioni dettagliate sull'estensione IntelliCode di Visual Studio

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   5.8.1
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62012.31170
Microsoft SQL Server Data Tools

Strumenti C#   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti del Servizio app di Azure versione 3.0.0   16.8.557.25636
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Microsoft Azure   2.9
Strumenti di Microsoft Azure per Microsoft Visual Studio 2019 - versione 2.9.30924.1

Strumenti di recapito continuo Microsoft per Visual Studio   0.4
Consente di semplificare la configurazione delle pipeline Azure DevOps direttamente dall'IDE di Visual Studio.

Strumenti di Visual Basic   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   16.0.21016.2001
Strumenti TypeScript per Microsoft Visual Studio

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Container Tools Extensions   1.0
Consente di visualizzare, gestire ed eseguire la diagnosi dei contenitori all'interno di Visual Studio.

Visual Studio Tools per contenitori   1.0
Visual Studio Tools per contenitori

VisualStudio.DeviceLog   1.0
Informazioni sul pacchetto

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.261 (d16-8@bb99248)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Estensione di Visual Studio per abilitare gli strumenti di Xamarin Designer in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc


Xamarin.iOS and Xamarin.Mac SDK   14.8.0.3 (c51fabee8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Screenshots
![wrong](https://user-images.githubusercontent.com/25587137/105974294-0d518180-608e-11eb-885d-1e4ba07e56bd.png)

**Comment by Codelisk** [comment]
Can confirm this one happens also for me

**Comment by rmarinho** [comment]
Hi @giosandev  do you mind upload a small reproduction of this issue, i m having trouble trying to reproduce this issue.

Thanks

**Comment by giosandev** [comment]
@rmarinho 
https://github.com/giosandev/TestVisual

**Comment by Codelisk** [comment]
Workaround to use an ImageButton worked for me:


        <ImageButton
            Padding="15"
            BackgroundColor="{Binding BackgroundColor, Source={x:Reference FloatingActionButtonRoot}}"
            Clicked="Button_Clicked"
            Command="{Binding Command, Source={x:Reference FloatingActionButtonRoot}}"
            CornerRadius="28"
            HeightRequest="56"
            HorizontalOptions="Center"
            Source="{Binding ImageSource, Source={x:Reference FloatingActionButtonRoot}}"
            VerticalOptions="Center"
            Visual="Material"
            WidthRequest="56" />

**Comment by ryanharding** [comment]
Same issue, Seems to be loading in the pressed state. Tapping button resets it to correct state and interaction.

**Comment by SR84** [comment]
Same problem here, ImageButton it´s a solution for me.

**Comment by diegokalvo** [comment]
Same Issue. ImageButton isn't a solution for me because I need to set some text in the button with the FontImage

**Comment by giosandev** [comment]
@diegokalvo exaclty! this was my initial issue (see the Login button) apart from the fact that in my opinion a component should do what is expected to do so i hope they'll fix the button tag.

**Comment by diegokalvo** [comment]
> 
> 
> @diegokalvo exaclty! this was my initial issue (see the Login button) apart from the fact that in my opinion a component should do what is expected to do so i hope they'll fix the button tag.

I temporary changed the propery Visual to "Default" value.

**Comment by giosandev** [comment]
@diegokalvo my customers chose the Visual="Material" over Visual="Default" page views so i can't change their directive (at least for now).

**Comment by ryanharding** [comment]
A temporary fix is to reset the background color in a custom renderer 

i.e in your renderer

 protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.Button> e)
        {
            base.OnElementChanged(e);

            if (Control == null || e.NewElement == null)
                return;

            Control.SetBackgroundColor(e.NewElement.BackgroundColor.ToAndroid());
            
        }

**Comment by diegokalvo** [comment]
> 
> 
> A temporary fix is to reset the background color in a custom renderer
> 
> i.e in your renderer
> 
> protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.Button> e)
> {
> base.OnElementChanged(e);
> if (Control == null || e.NewElement == null)
> return;
> 
> ```
> Control.SetBackgroundColor(e.NewElement.BackgroundColor.ToAndroid());
> ```
> 
> }

Thanks but it didn't work for me

**Comment by giosandev** [comment]
Don't ask me why, I don't know, the restore of Visual Studio installation (i did it for another reason) solved the problem.
Restore Visual Studio->Update NuGet packages to 5.0.0.2012 no more default transparent buttons.
