### ISSUE TITLE
[UWP] The SelectedItem in a ListView is not highlighted when set while constructing a page

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#1356]
### Description

Setting a SelectedItem on a ListView when constructing a page doesn't select the item in the list on UWP.

### Steps to Reproduce

This should simply require unzipping and running the reproduction -- the MainPage has a ListView which already does the work of setting the SelcetedItem.

### Expected Behavior

The selected item is visually highlighted in the list.

### Actual Behavior

The selected item is not visually highlighted on UWP. It is on Android and iOS.

### Basic Information

- Version with issue: 2.5.0.191934
- Last known good version: Uncertain. This may have worked at some point, or maybe not.
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.0
  - UWP:  16299
- Android Support Library Version: (Not applicable)
- Nuget Packages: (Not Applicable -- baseline Forms project/updated packages)
- Affected Devices: Devices/machines running Windows 10

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/1543316/App1.zip)

**Comment by owlstack** [comment]
What version of Xamarin.Forms stable will this change be in?

**Comment by owlstack** [comment]
@pauldipietro Hi, Assuming this fix is included in Xamarin.Forms 2.5.0.122203, the first item in my listview is still not highlighted even though I set my SelectedItem = Item[0] in my viewmodel.

**Comment by hartez** [comment]
This has regressed in 3.5.0.

**Comment by samhouts** [comment]
closed by #6973
