### ISSUE TITLE
InputAccessoryView in WkWebView is readonly (should be changeable)

### ISSUE THREAD

**Issue by andreas-siegmund** [xamarin/Xamarin.Forms#13566]
### Description
(I'm quite new to Xamarin development and this is my first issue, so please be generous if I do something wrong)

Since 2019 the field `InputAccessoryView` in `WkWebView` should be changeable (see [here](https://bugs.webkit.org/show_bug.cgi?id=198631)).
The current implementation in Xamarin is as follows:
```
[get: Foundation.Export("inputAccessoryView")]
public virtual UIKit.UIView InputAccessoryView { get; }
```

### Impact
Many RichtText-Editors are implemented using a WkWebView with `contenteditable="true"` to edit HTML formatted text.
Because this field is read-only it is not possible to change the toolbar above the keyboard and only a not very useful standard toolbar is shown:
![image](https://user-images.githubusercontent.com/51786282/106035190-1b29f580-60d4-11eb-8ca4-598a3613b697.png)

The field needs to be editable to allow serious implementations as follows (or even disable this toolbar completely):

![image](https://user-images.githubusercontent.com/51786282/106055368-8f24c780-60ed-11eb-9422-d2ff6e638e59.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/51786282/106056114-97313700-60ee-11eb-8e79-51fed0c6c929.png)

### Expected Behavior
Field `InputAccessoryView` can be assigned.

### Actual Behavior
Field `InputAccessoryView` cannot be assigned.

### Further information
The field `InputAccessoryView` for Entry types can be assigned successfully:

![image](https://user-images.githubusercontent.com/51786282/106057959-eb3d1b00-60f0-11eb-9ab3-88320aad4f14.png)

(This code compiles and it is possible to successfully set a custom toolbar - this serves as proof that Xamarin is able to do it)

Please let me know if some information or anything else is missing. I am more than happy to help getting it fixed. 
Thanks in advance to everybody helping here...

### Basic Information
- Version with issue: Xamari.Forms 5.0.0
- Last known good version: (I assume it was not working before)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by mhamann** [comment]
@andreas-siegmund did you find a workaround for this on Xamarin?
