### ISSUE TITLE
[Bug] ERROR: Could not connect to the remote mac

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Xamarin.Forms#13564]
### Steps to Reproduce

1. In the Xamarin IOS project add a storyboard
2. 
3. 

### Expected Behavior
Will connect to the MAC

### Actual Behavior
First go around you will get an error that the MAC cannot be found.  
I found in a forum where it said to disconnect, forget, and add the mac back again.
This worked, but then the storyboard tried to connect and you get the following message:
Custom components are not being rendered because problems were detected. 
I then opened the log file which stated:  ERROR: Could not connect to the remote mac

### Basic Information

- Version with issue: Microsoft Visual Studio Professional Version 16.8.4, Xamarin Forms 5.0.0.1931
[iOSDesigner-2021-01-27__08-54-16.16948.log](https://github.com/xamarin/Xamarin.Forms/files/5882705/iOSDesigner-2021-01-27__08-54-16.16948.log)

- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
I hope you got this resolved by now. If not, please report the issue through Visual Studio in the Help > Report a problem menu. That will make it land in the right place :)

Thanks!
