### ISSUE TITLE
[Bug] Editor PlaceholderColor and BackgroundColor incorrect on UWP after upgrading to Xamarin.Forms 4.8 (from 4.5)

### ISSUE THREAD

**Issue by ivanv-microsoft** [xamarin/Xamarin.Forms#13573]
### Steps to Reproduce

1. Create a new page with the following control
`<Editor Grid.Row="1" Grid.Column="0" x:Name="VerboseFeedback" Text="" 
                    Placeholder="Some long text, doesn't really matter" PlaceholderColor="Gray" 
                    VerticalOptions="Start" HorizontalOptions="FillAndExpand" MaxLength="4000" 
                    FontSize="12"
                    HeightRequest="100"
                    BackgroundColor="White" TextColor="Black" Margin="10,0,5,5" />`
2. Run it on different platforms
3. 

### Expected Behavior
BackgroundColor is always White
TextColor is always Black
Placeholder text color is always Gray

### Actual Behavior
When Editor control is in focus, Background color is "grayish", and White when not in focus

### Basic Information
Works fine on Android

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![Control_In_Focus_Wrong](https://user-images.githubusercontent.com/28568469/106573690-3fedf500-653a-11eb-932c-ad57f48e5748.png)
![Control_Not_In_Focus_Correct](https://user-images.githubusercontent.com/28568469/106573693-40868b80-653a-11eb-8700-d1aebae5b4bf.png)

**Comment by rachelkang** [comment]
Hi, @ivanv-microsoft - thanks for sharing! I was able to reproduce this on UWP on XF 4.8 and up, when a grid background color is set (in your case it appears gray when the background is black). This is not an issue when the grid background is white, and/or on versions of XF 4.7 and below.

[Issue13573.zip](https://github.com/xamarin/Xamarin.Forms/files/5928283/Issue13573.zip)

**Comment by ivanv-microsoft** [comment]
That's great, thanks Rachel, hopefully it gets fixed (soon).
Any workarounds you could see when debugging/going through the flow? 

Changing background color on the parent grid to white isn't an option, as the entire app theme is "black (& green)".

**Comment by jsuarezruiz** [comment]
@ivanv-microsoft The issue will be fixed by #13728

**Comment by devology-rob** [comment]
I'm seeing this too on UWP, in my case the grid background color is explicitly set to white, but when the editor is focused the background colour is dark-gray and the text is black, making it very hard to read.  Again, if un-focused the editor renders correctly.
