### ISSUE TITLE
[Bug] [iOS] Label with FormattedText Crash on XF 5.0.1.1876

### ISSUE THREAD

**Issue by xDaijobu** [xamarin/Xamarin.Forms#13570]
### Description

if I use Label without FormattedText the app work and Label with FormattedText, I received above crash
### Steps to Reproduce
Create a new project & upgrade to XF 5.0.1.1876

        <Label>
            <Label.FormattedText>
                <FormattedString>
                    <Span Text="25min" />
                    <Span Text=" . " />
                    <Span Text="Free delivery" />
                </FormattedString>
            </Label.FormattedText>
        </Label>

### Expected Behavior
_**Xamarin.Forms 5.0.0.1931**_
<img width="1274" alt="Screen Shot 2021-01-28 at 11 39 17" src="https://user-images.githubusercontent.com/22674537/106090719-66d4b180-615d-11eb-8762-dc834f2b5f0b.png">
### Actual Behavior
_**Xamarin.Forms 5.0.1.1876**_
<img width="1748" alt="Screen Shot 2021-01-28 at 11 47 56" src="https://user-images.githubusercontent.com/22674537/106091264-9d5efc00-615e-11eb-90c8-139cbf957c0f.png">
<img width="1546" alt="Screen Shot 2021-01-28 at 11 48 50" src="https://user-images.githubusercontent.com/22674537/106091316-bcf62480-615e-11eb-8c4c-9b23facd1c3a.png">
### Basic Information

- Version with issue: Xamarin.Forms 5.0.1.1876
- Last known good version: Xamarin.Forms 5.0.0.1931
- NuGet Packages:
- Affected Devices:

**Comment by rachelkang** [comment]
Hi, @xDaijobu - thanks for submitting this issue. Would you mind clarifying what version of XF you're experiencing this issue? 5.0.0.1931 is our most recent version, so I'm not sure what you mean by 5.0.1.1876. 

That being said, I tried running your sample on both 5.0.0.1874 and 5.0.0.1931 on the same emulator as you (iPhone 12 iOS 14.4) and was not able to reproduce this issue.

**Comment by xDaijobu** [comment]
Hey Rachel, thanks for ur reply.
here's the repo
[testt.zip](https://github.com/xamarin/Xamarin.Forms/files/5907809/testt.zip) 

Xamarin.Forms 5.0.1.1876
<img width="945" alt="Screen Shot 2021-02-02 at 07 55 51" src="https://user-images.githubusercontent.com/22674537/106536973-01e9d480-652c-11eb-94ee-be256f1af3ee.png">

**Comment by xDaijobu** [comment]
update ?

**Comment by xDaijobu** [comment]
Related #12259
Related #13526

Fixed by the following PR #13529

the issue no longer happens.
