### ISSUE TITLE
Unchanged new Xamarin Forms mobile project is missing text

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#13579]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Unchanged-new-Xamarin-Forms-mobile-proje/1314278)._

---
[severity:It bothers me. A fix would be nice]
I created a new Xamarin Forms tabbed project. Without any changes, I run it. I noticed that the About Xaml page has way more text than what appears on the app. Upon investigation, it appears that two labels require a colored background or a color for the text. Currently it is White on White - which is hard to read ;- )

Here is the code in question:

```
                <Label Text="Start developing now" FontSize="Title"/>
                <Label Text="Make changes to your XAML file and save to see your UI update in the running app with XAML Hot Reload. Give it a try!" FontSize="16" Padding="0,0,0,0"/>

```
With all the thought that went into creating the text, I imagine the point is to have it read. Otherwise, it could simply be a comment.

---
#### Feedback Bot on 1/20/2021, 02:01 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rmarinho** [comment]
Hello, i just tested this and i can see all text. Can yu please upload a small reproduction?

Thanks

![image](https://user-images.githubusercontent.com/1235097/106277590-4b3adb00-6231-11eb-9153-0b05eb815b9a.png)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
