### ISSUE TITLE
UWP no longer triggers XAML build step in .NET Standard world

### ISSUE THREAD

**Issue by jassmith** [xamarin/Xamarin.Forms#1358]
### Description

Pretty much what the tittle says. Oddly still works with design time builds so intellisense picks up the InitializeComponent calls.

### Steps to Reproduce

1. Try to build reproduction project
2. 
3. 

### Expected Behavior

Build works

### Actual Behavior

Build fails

### Basic Information

- Version with issue: 2.6.0 nightly
- Last known good version: 2.5.0
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  Fall Creators Update
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: N/A

### Screenshots

 N/A

### Reproduction Link

[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/1543641/App3.zip)

**Comment by StephaneDelcroix** [comment]
@kingces95 @jassmith where is 2.6.0.6258-nightly coming from ? latest nightly is 2.5.1.102606-nightly

**Comment by StephaneDelcroix** [comment]
for some unknown reason, UWP build is doing some compilation of its own in `XamlPreCompile`, without even invoking the target `BeforeCompile`
