### ISSUE TITLE
Icon not showing from shell (Xam. Forms)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#13580]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Icon-not-showing-from-shell-Xam-Forms/1318693)._

---
I have a  number of readonly properties in my BaseViewModel which are inheritted by all classes. These properties include properties pointing to all embedded images within my shared project (the images are used throughout the app and always show).

In my AppShell.xaml file I have the following lines for my flyout objects

```
<FlyoutItem Route="IDCard" Title="ID Card" Icon="{Binding IDCard}">
            <ShellContent ContentTemplate="{DataTemplate views:IDCardPage}" />
</FlyoutItem>
```

While the text shows, the Icons don't.

The code in my baseviewmodel for the creation of this property is this

`public ImageSource IDCard => "idcard". PlatformResource();`

PlatformResource is a helper method that adds the Assembly to the start of the image

I've not tested this in earlier versions as I've just started moving this from tabs to flyout. The icon images work fine as tabs

---
#### Feedback Bot on 1/25/2021, 05:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by angelru** [comment]
it's related?
https://github.com/xamarin/Xamarin.Forms/issues/13559

**Comment by rmarinho** [comment]
Hi, thanks for your report. We will need a small reproduction so we can see what's the issue

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
