### ISSUE TITLE
[Bug] [WPF] Incorrect ListView row height of Labels with line breaks in Grid

### ISSUE THREAD

**Issue by CometSL9** [xamarin/Xamarin.Forms#13587]
### Description
Labels with line breaks are not increasing their surrounding Grid's row height inside of a ListView.

### Steps to Reproduce

1.  Create a new XF Project with a new Platform WPF.
2.  Paste the code below onto the main page.
3.  Run.

### Expected Behavior
Correctly adapted line height for each line.

### Actual Behavior
Line height is rendered as if line is a single line without line breaks.

### Basic Information

- Version with issue: 5.0.0.1931
- Last known good version: None
- Platform Target Frameworks: WPF

The bug is really annoying because it hinders this part of my project from getting the "OK" of the colleagues.

Screenshot:
![image](https://user-images.githubusercontent.com/46746288/105961558-f35c7280-607e-11eb-91f8-7bfd715495c3.png)

Code to reproduce the error:
```
<ListView
    HasUnevenRows="True"
    HeightRequest="200"
    HorizontalOptions="Center"
    WidthRequest="300">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="100" />
                        <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>
                    <Label Grid.Column="0" Text="Fixed width" />
                    <Label
                        Grid.Column="1"
                        LineBreakMode="WordWrap"
                        Text="{Binding .}" />
                </Grid>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
    <ListView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>Test</x:String>
            <x:String>Text is too long to display on a single line</x:String>
            <x:String>Another Test</x:String>
        </x:Array>
    </ListView.ItemsSource>
</ListView>
```

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
