### ISSUE TITLE
[Bug] Custom view

### ISSUE THREAD

**Issue by demoh2019** [xamarin/Xamarin.Forms#13599]
### Description

when changing IsVisible Custom view, visibility does not change. 
while IsVisible = "false" works
### Steps to Reproduce

1. Create Custom view
2. change IsVisible

### Expected Behavior
the custom element will disappear
### Actual Behavior
custom item disappears after application restart
### Basic Information

- Version with issue: last version
- Affected Devices:iphone 6s (device)

same problem:
https://forums.xamarin.com/discussion/59642/hiding-a-custom-control

**Comment by rachelkang** [comment]
Hi, @demoh2019 - thanks for submitting this issue. Were you able to reproduce this issue on any other devices/emulators? Also what version of iOS are you using? I'm yet to test on an iPhone 6s device, but was able to see that it works fine on an iPhone 7 (iOS 14) and iPhone 6s (iOS 13) emulator

Also, is there a specific type of custom view control you're experiencing this with, or is it with all custom views? If you could share your project or a sample project, that would be super helpful! Thank you :)
