### ISSUE TITLE
Shell Navigation Error on Android Api 24 Android 7

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Xamarin.Forms#13598]
### Description
I am seeing this error on the Samsung SM-920V Android 7 Api 24.  
Here is the command I am calling:
await Shell.Current.GoToAsync("/MyEditPage", false);
This call works fine on the new Android phone, and even IOS but the older Android phone I get the following error:
System.ArgumentException: 'unable to figure out route for: /MyEditPage
Parameter name: uri'

This is the command I use when clicking the button to navigate
private ICommand _editCommand;
public ICommand EditCommand => _editCommand ?? (_editCommand = new Command(async () => await Edit()));

In App.xaml.cs I have registered the route

Routing.RegisterRoute("MyEditPage", typeof(EditProfileView));

The one exception to this, the button is on a Syncfusion PopUp, but as I said this is working fine in other android phones, even IOS. 

### Expected Behavior
I would expect the navigation to occur

### Actual Behavior
No navigation, getting an error

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment
Microsoft Visual Studio Professional 2019 Version 16.8.4
Microsoft .NET Framework 4.7.03190
Xamarin Forms:  5.0.0.1931
Xamarin.Essentials 1.6.1

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @sisaacks - thanks for submitting this issue! Would you mind sharing your project or a sample project reproducing the issue you're describing, so that we can take a closer look? Thank you :)

**Comment by sisaacks** [comment]
@rachelkang I did above...dont you see it?  
Literally follow the example online...this was working until 5.0
internal async Task GoToMyPage()
        {
               await Shell.Current.GoToAsync("/MyPage", false);
        }

**Comment by sisaacks** [comment]
@rachelkang any updates on this?  I guess I could always swap out the line of code for
await Shell.Current.Navigation.PushAsync....but I would rather not if I do not have too

**Comment by PureWeen** [comment]
@sisaacks AFAICT this is fixed with the latest 2012 release of Forms

If you are still seeing this issue can you attach a project that reproduces the issue
