### ISSUE TITLE
[Bug] The values.xml file is appearing empty.

### ISSUE THREAD

**Issue by marciordonez** [xamarin/Xamarin.Forms#13595]
### Steps to Reproduce

1. Deploy app Xamafin.Forms for Android
2. Stop debugging
3. Deploy again (from the second time onwards). The error will appear.

### Expected Behavior
Deploy more than once without error. From the second time onwards, the values.xml file is appearing empty.

### Actual Behavior
The values.xml file is appearing empty.

### Basic Information
Xamarin Forms v5.0.0.1931
Visual Studio Community v16.8.4 (Windows)

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android: Android Q 10.0 (API 29) 
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/5067254/106365233-e8ba0b80-6312-11eb-9bbf-daaa14239197.png)

### Workaround

Close visual studio and re-deploy

**Comment by rachelkang** [comment]
Hi, @marciordonez - thanks for submitting this issue! I'll be closing this issue as it seems you're no longer experiencing it / it goes away when you restart VS. If you experience this issue again, however, I recommend submitting your feedback within VS by following the [instructions here](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019). This way, the appropriate team will be able to see all the details relevant to your environment and be able to assist accordingly :)
