### ISSUE TITLE
[Bug] Shape.Fill with DynimicResources keeps not working on UWP at Xamarin.Forms 5.0.0.1931

### ISSUE THREAD

**Issue by AdrianoRochedo** [xamarin/Xamarin.Forms#13591]
### Description

Android => OK
IOS => not tested
UWP => NOT OK

**Comment by jsuarezruiz** [comment]
@AdrianoRochedo Could you attach a sample where reproduce the issue or a piece of code?

I tried some tests, and seems to work:

<img width="1576" alt="Captura de pantalla 2021-02-01 a las 18 07 45" src="https://user-images.githubusercontent.com/6755973/106492625-6e2af080-64b8-11eb-9e26-3b9e5a2ffc02.png">

**Comment by AdrianoRochedo** [comment]
I will do more tests like that to try reproduce the issue.
Thanks

**Comment by AdrianoRochedo** [comment]
I see now ... Ihave to use a brush and not a color !!
I was using a Color resource !
Thanks
