### ISSUE TITLE
iOS Remote USB still not available

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#1360]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
This feature got a standing ovation at Evolve 2016. It was around for about a week, then pulled.
There was a survey on Twitter that MANY people didn't know about.  Then ... well .... hello ... nothing.

The thread for it on Xamarin Forums still has people wanting to know when this will be available again.
https://forums.xamarin.com/discussion/comment/311153#Comment_311153

Please bring this back - when it was there it worked great.

**Comment by jassmith** [comment]
Wrong project :)
