### ISSUE TITLE
[Enhancement/Question] UWP FormsCommandBar always show "More...", even if there is no more

### ISSUE THREAD

**Issue by SergTomcat** [xamarin/Xamarin.Forms#13609]
## Summary

Multiple people (me included) stumbled upon a problem in UWP when you cannot remove "more" (three dots) button from a toolbar. If there's any toolbar button, the "More" button will be present, even if there's no secondary elements.

People suggest to completely hide that button with setting it's width to 0.

https://stackoverflow.com/questions/53145798/how-do-i-hide-the-default-toolbar-button-three-dots-in-xamarin-forms-uwp

https://forums.xamarin.com/discussion/183806/uwp-toolbar-autohide-more-button

In _FormsCommandBar_ class I found that _OverflowButtonVisibility_ is overrided to support older Windows builds:

```
			// Are there any commands to display?
			var visibility = PrimaryCommands.Count + SecondaryCommands.Count > 0 ? Visibility.Visible : Visibility.Collapsed;

			if (_moreButton != null)
			{
				// The "..." button should only be visible if we have commands to display
				_moreButton.Visibility = visibility;

				// There *is* an OverflowButtonVisibility property that does more or less the same thing, 
				// but it became available in 10.0.14393.0 and we have to support 10.0.10240
			}
```

But the override value checks **PrimaryCommands** count for "More" button, which doesn't make sense to me.

## API Changes

I'd suggest to make one or all of these things:
- versions fork in code to support _OverflowButtonVisibility_ property
- remove PrimaryCommands check 

`var visibility = SecondaryCommands.Count > 0 ? Visibility.Visible : Visibility.Collapsed;`

- add parameter to control button behaviour

## Intended Use Case
Some pages has only one primary button, some has secondary buttons.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
