### ISSUE TITLE
ImageSource.FromResource fails when running on .NET Core 2.0

### ISSUE THREAD

**Issue by praeclarum** [xamarin/Xamarin.Forms#1362]
### Description

The implementation of FromResource uses reflection and tries to call a method that doesn't exist on .NET Core 2.0.

With .NET Standard 2.0 this code can be fixed to not use reflection.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ImageSource.cs#L73

### Steps to Reproduce

1. Call `ImageSource.FromResource("BugSweeper.Images.Xamarin120.png")`

### Expected Behavior

An ImageSource is created.

### Actual Behavior

```
TargetException: Exception of type 'System.Reflection.TargetException' was thrown.
  System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
  System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Xamarin.Forms.ImageSource.FromResource(string resource, Assembly sourceAssembly)
  BugSweeper.Tile..cctor() in Tile.cs
```

### Basic Information

- Version with issue: 2.4
- IDE: VSM
- Platform Target Frameworks:
  - .NET Core: 2.0.2

**Comment by opcodewriter** [comment]
Wow. Are there other APIs which have same problem? Besides, using reflection should be always a red flag.
When Xamarin decided to go to .NET Standard 2 did anyone think a bit of what can go wrong from an API perspective?

**Comment by TWINSBaltiya** [comment]
I got to fix the situation with this code addition:

using System.Reflection;
var assembly = typeof(ImageResourceExtension).GetTypeInfo().Assembly;
ImageSource.FromResource("BugSweeper.Images.Xamarin120.png", assembly);

"ImageResourceExtension" is any type from the assembly where the image is embedded.

**Comment by ldw9981** [comment]
thanks TWINSBaltiya. 
i spend one day.

**Comment by ravenrgg** [comment]
This fix did not repair my issue.   The exception is gone, but the screen is blank.  Here is the code, it's from the Xamarin.Forms book with your fix.  The image is set to Embedded Resource.

I am running VS2017 15.5.2

using System.Reflection;
using Xamarin.Forms;

namespace ResourceBitmapCode
{
	public class ResourceBitmapCodePage : ContentPage
	{
		public ResourceBitmapCodePage ()
		{
            var assembly = typeof(StreamImageSource).GetTypeInfo().Assembly;
            Content = new Image
            {
                Source = ImageSource.FromResource(
                            "ResourceBitmapCode.Images.ModernUserInterface256.jpg", assembly),
                VerticalOptions = LayoutOptions.Center,
                HorizontalOptions = LayoutOptions.Center
            };
        }
    }
}
