### ISSUE TITLE
[Bug] Setting Height of ListView.GroupHeaderTemplate.ViewCell to 0 will result in default height

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#13624]
### Description
Setting ListView.GroupHeaderTemplate -> ViewCell -> Height="0" will result in default height of the GroupHeader. Setting it to 1 will shrink it to 1. 

### Steps to Reproduce

1. Create a ListView with Grouping 
2. Create a GroupHeaderTemplate and set Height="0" on ViewCell
3. Start on iOS Simulator or Android Emulator

### Expected Behavior
GroupHeader should be invisible.

### Actual Behavior
GroupHeader is shown with default Height.

### Basic Information

- Version with issue: 4.8.0.1269
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  Simulator with iOS 13.7
  - Android: Android 9 (API 28)

### Workaround
Setting Height to 1 instead of 0. 

Implementing the following enhancement will also solve this issue https://github.com/xamarin/Xamarin.Forms/issues/13615

**Comment by rachelkang** [comment]
Hi, @MaxFmi - thanks for submitting this issue. I wasn't able to reproduce this behavior - Would you please share your project or a sample project reproducing the issue so that we can take a closer look? Thanks again :)

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
