### ISSUE TITLE
[Bug] Shell Navigation Animation

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#13621]
When I navigate to another page and load content from my api, the ActivityIndicator flickers or the interface is blocked and produces that feeling of flickering and has to do with the animation because it hasn't finished yet navigation, if I set the animation to false everything works fine. There should be an event apart from OnAppearing or OnDisappearing in shell or ContentPage to determine when the navigation has finished and there execute our API call methods.

Example:

```
   var vm = new ChatMessagesPageViewModel
            {
                ChatRoom = _selectedChat
            };

            var page = new ChatMessagesPage
            {
                BindingContext = vm
            };

            await Shell.Current.Navigation.PushAsync(page);

  public ChatRoom ChatRoom
        {
            get => _chatRoom;
            set
            {
                _chatRoom = value;
                 ChatMessagesLoader.Load(InitMessagesAsync);
            }
        }

 public async Task InitMessagesAsync()
        {
            if (!_chatRoom.IsPrivate)
            {
                var cleanIds = _chatRoom.UserIds.Except(users.Keys);

                if (cleanIds.Any())
                {
                    await Task.WhenAll(cleanIds.Select(async id =>
                    {
                        var user = await ApiRest.UserAsync(id);
                        users.Add(id, user.Name);
                    }));
                }
            }

            var employes =  await ApiRest.ChatMessagesAsync();
}
```

**Comment by angelru** [comment]
It also happens when there is a "complex layout" on the navigation screen. There is a slight blockage

**Comment by angelru** [comment]
![Screenrecorder-2021-02-04-10-28-14-28](https://user-images.githubusercontent.com/11645585/106873063-5760e580-66d4-11eb-9b87-0836d84fc21c.gif)

**Comment by rachelkang** [comment]
Hi, @angelru - thank you for sharing! We definitely agree that's an awesome idea, and we're excited to introduce these capabilities in .NET MAUI - please feel free to check out and follow the discussion on our [current spec for lifecycle events](https://github.com/dotnet/maui/issues/30) and share your thoughts with us! We'd love to hear them :)
