### ISSUE TITLE
XF 5.0 - Build Errors

### ISSUE THREAD

**Issue by Only-Xam** [xamarin/Xamarin.Forms#13637]
### Steps to Reproduce

1. Create a new XF blank project
2. By default I see XF 4.8.0.1451 and Xamarin Essentials 1.5.3.2 packages & SDK NetStandard.Library (2.0.3)
3. Build and run the default Main Page app everything is fine.
3. Now if I just update XF to XF 5.0.0.1931 and try to build the solution again, build is failing.

### Expected Behavior
There should not be any errors and it should build fine..
**Note:** It seems to related  .NET Standard version mismatches but being new to the field, I am unable to figure it out how to fix it. Idea is to gain knowledge from all experts to better handle these issues.

### Actual Behavior
Build is failing with exceptions as highlighted below.
### Basic Information

-Visual Studio Community 16.8.4
-XF 5.0.0.1931
-Microsoft Windows Version 1903 (OS Build 18362.778)
-Detail from UWP.csproj file
           TargetPlatformIdentifier - UAP
           TargetPlatformVersion - 10.0.18362.0
           TargetPlatformMinVersion - 10.0.16299.0

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Build Logs
- Below is the default setup when a new project is created. Here build is successful and app run fine.

![image](https://user-images.githubusercontent.com/66119201/106757694-a3c40b00-666b-11eb-9cbd-b94ec0afadf1.png)

- Now just update to XF to XF 5.0.0.1931 and build again. I see below failures. Even xaml file shows squiggly line for everything.

![image](https://user-images.githubusercontent.com/66119201/106758473-817ebd00-666c-11eb-902b-053cddfacd85.png)

- Errors are as below

![image](https://user-images.githubusercontent.com/66119201/106758553-9a876e00-666c-11eb-8c33-f5237800de7d.png)
 

### Background

Everything was working fine even with XF 5.0, my system was crashed, so I restored it and then reinstalled Visual Studio but now if I am updating to XF 5.0, I am getting build errors. Also here are the sdk installed on my system.

![image](https://user-images.githubusercontent.com/66119201/106759460-c0614280-666d-11eb-91ca-ee0c2295b324.png)

**Comment by rachelkang** [comment]
Hi, @Only-Xam - thanks for submitting this issue! I unfortunately was unable to reproduce it - could you let me know if this sample works for you? [Issue13637.zip](https://github.com/xamarin/Xamarin.Forms/files/5920259/Issue13637.zip)

On your own project, if you haven't already, could you check the nuget packages on each project individually to make sure all the versions match? Make sure there isn't any mismatch between the XF versions across different projects!

**Comment by Only-Xam** [comment]
Hi @rachelkang thanks for looking into it. I tried to run the sample project shared by you but still same issue. It asked me to install Windows 10 SDK and I installed but even after that same problem.

![image](https://user-images.githubusercontent.com/66119201/106869791-4e3f3b00-670b-11eb-8675-acea06120aad.png)

![image](https://user-images.githubusercontent.com/66119201/106870122-b7bf4980-670b-11eb-8e19-965c8b699e3b.png)

- Verified Package version for solution and individual projects

![image](https://user-images.githubusercontent.com/66119201/106874194-43d37000-6710-11eb-9e3e-0c3cd3708aa4.png)

- Here is the list of installed SDKs and runtime versions

![image](https://user-images.githubusercontent.com/66119201/106874437-84cb8480-6710-11eb-88a2-f2f75f2172e4.png)

- Verified installation for missing components but could not find anything odd.
![image](https://user-images.githubusercontent.com/66119201/106875306-7d58ab00-6711-11eb-91d7-101c4ac58c45.png)

- There is mention of similar exceptions here (not exactly same) - https://blog.verslu.is/xamarin/xamarin-communitytoolkit/build-xamarin-communitytoolkit-sample-app-windows/?utm_source=rss&utm_medium=rss&utm_campaign=build-xamarin-communitytoolkit-sample-app-windows
- But no luck


![image](https://user-images.githubusercontent.com/66119201/106877192-759a0600-6713-11eb-98e6-6a26bca93b78.png)



Build started...
1>------ Build started: Project: Issue13637, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "C:\Users\mrrkt\.nuget\packages\xamarin.forms\5.0.0.1931\lib\netstandard2.0\Xamarin.Forms.Core.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "C:\Users\mrrkt\.nuget\packages\xamarin.forms\5.0.0.1931\lib\netstandard2.0\Xamarin.Forms.Platform.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): warning MSB3106: Assembly strong name "C:\Users\mrrkt\.nuget\packages\xamarin.forms\5.0.0.1931\lib\netstandard2.0\Xamarin.Forms.Xaml.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\AssemblyInfo.cs(3,12,3,27): error CS0246: The type or namespace name 'XamlCompilationAttribute' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\AssemblyInfo.cs(3,12,3,27): error CS0246: The type or namespace name 'XamlCompilation' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\AssemblyInfo.cs(3,28,3,50): error CS0103: The name 'XamlCompilationOptions' does not exist in the current context
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(2,15,2,20): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(3,15,3,20): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\AssemblyInfo.cs(1,15,1,20): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\MainPage.xaml.cs(7,15,7,20): error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(7,32,7,43): error CS0246: The type or namespace name 'Application' could not be found (are you missing a using directive or an assembly reference?)
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(16,33,16,40): error CS0115: 'App.OnStart()': no suitable method found to override
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(20,33,20,40): error CS0115: 'App.OnSleep()': no suitable method found to override
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\App.xaml.cs(24,33,24,41): error CS0115: 'App.OnResume()': no suitable method found to override
1>C:\Users\mrrkt\Downloads\Issue13637\Issue13637\Issue13637\Issue13637\MainPage.xaml.cs(11,37,11,48): error CS0246: The type or namespace name 'ContentPage' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "Issue13637.csproj" -- FAILED.

**Comment by Only-Xam** [comment]
Hi @rachelkang after some struggle got it solved.

1. Closed Visual Studio
2. Deleted **bin** and **obj** folders from Project as well individual project folders for Android, iOS & UWP

- XF_TEST_2\XF_TEST_2\**XF_TEST_2**
- XF_TEST_2\XF_TEST_2\**XF_TEST_2.Android**
- XF_TEST_2\XF_TEST_2\**XF_TEST_2.iOS**
- XF_TEST_2\XF_TEST_2\**XF_TEST_2.UWP**

3. Restarted Visual Studio
4. Open solution nd build again.

These steps are mentioned here - https://stackoverflow.com/questions/44251030/vs-2017-metadata-file-dll-could-not-be-found

Thanks to all genius people around the world :)
