### ISSUE TITLE
[Bug] XamarinIOSPackage not loaded correctly

### ISSUE THREAD

**Issue by 21r8390** [xamarin/Xamarin.Forms#13635]
### Description
After a Windows and Visual Studio update I got an error message that XamarinIOSPackage was not loaded properly. So far I have completely uninstalled and reinstalled Visual Studio, searched for error messages, restarted, deleted folders, run as administrator and updated Windows...

Error message looks like this:
https://us.v-cdn.net/5019960/uploads/editor/ir/kr85k42jx57n.png

This problem keeps popping up and there are no solutions to it:
https://developercommunity.visualstudio.com/content/problem/1277223/the-xamariniospackage-did-not-load-correctly.html

### Steps to Reproduce

1. Windows & Visual Studio update
2. Create new project with Xamarin.Forms

### Expected Behavior
Create new project with Xamarin.Forms which is Android and IOS compatible.

### Actual Behavior
Error messages, IOSPackage is not loaded

### Basic Information

- Version with issue: 16.8.4
- Affected Devices: Visual Studio

**Comment by rachelkang** [comment]
Hi, @21r8390 - thanks for submitting this issue. From the discussion thread you shared, it looks like the problem you described has been fixed internally and will be released soon! In the meantime, there are some workarounds mentioned there that I recommend you try if you haven't already:

You can try to see if you continue experiencing this issue on the Preview channel, and/or

> We fixed a similar problem on the current Preview version of Visual Studio, could you try installing it (https://visualstudio.microsoft.com/vs/preview/) and let us know if it works for you so we can confirm it’s the same problem?

give this a try!

> As a workaround for the stable version of Visual Studio, could you try removing the following files from `%LOCALAPPDATA%\Xamarin\MonoTouch`: hosts.settings, platform.settings, hosts.key and then reopening VS again?

Let me know how it goes :)

**Comment by 21r8390** [comment]
Hi @rachelkang
I fixed the problem, by using the _preview version_. 
In the normal version, it still doesn't work... Thanks for the help!

**Comment by PureWeen** [comment]
@21r8390 is this working for you now on the latest Stable version of 16.9?

**Comment by 21r8390** [comment]
Yes, now it works more or less.
Thanks for patching this problem! 👍
