### ISSUE TITLE
Live Player does not work with Azure App Service

### ISSUE THREAD

**Issue by leemorris** [xamarin/Xamarin.Forms#1363]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Live Player does not work with either QuickStart apps created in Azure Mobile App Service or from the Visual Studio Cross Platform Xamarin Forms template when a Azure App Service Backend is selected. The repro is for the Visual Studio Template. If the Azure App Backend is NOT selected, Live Player works correctly.

### Steps to Reproduce

1. Create New Project in Visual Studio 2017
2.  Choose "Cross Platform App (Xamarin Forms)"
3. Choose Template = "Master Detail", Platform = "Android", UI Technology = "Xamarin.Forms", Code Sharing Technology = ".NET Standard"
4. Check the "Include Azure Mobile Apps backend project"
5. Click OK
6. Window will appear to Create App Service, accept defaults. Click Create.

### Expected Behavior
App should build without errors.
App should launch on Android Device that was configured as a Live Player device

### Actual Behavior
App builds without error but when launched on Android Device that is configured as a Live Player device, there are 35 error messages displayed. Here is a sample.

Error	CS0246	The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)	App6.Android	C:\WIP\App6\App6\App6.Android\MainActivity.cs	24	Active

Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.xml.readerwriter/4.0.11/ref/netstandard1.3/System.Xml.ReaderWriter.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.xml.xdocument/4.0.11/ref/netstandard1.3/System.Xml.XDocument.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.xml.xdocument/4.0.11/ref/netstandard1.3/System.Xml.XDocument.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.text.regularexpressions/4.1.0/ref/netstandard1.6/System.Text.RegularExpressions.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.text.encoding/4.3.0/ref/netstandard1.3/System.Text.Encoding.dll".
Error		Failed to load assembly from stream: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path "/data/user/0/com.xamarin.live/files/.nuget/packages/system.text.encoding.extensions/4.0.11/ref/netstandard1.3/System.Text.Encoding.Extensions.dll".

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 ver 15.5
- Platform Target Frameworks: .NetStandard 2.0

  - Android:  

- Android Support Library Version: Xamarin.Android.Support. v4, Xamarin.Android.Support.v7.AppCompat, Xamarin.Android.Support.v7.Cardview, Xamarin.Android.Support.v7.MediaRouter
- Nuget Packages:
Microsoft.AspNet.WebApi.Client
Microsoft.AspNet.WebApi.Core
Microsoft.AspNet.WebApi.OData
Microsoft.AspNet.WebApi.Owin
Microsoft.AspNet.WebApi.Tracing
Microsoft.Azure.Mobile.Client
Microsoft.Azure.Mobile.Client.SQLiteStore
Microsoft.Azure.Mobile.Server
Microsoft.Azure.Mobile.Server.Authentication
Microsoft.Azure.Mobile.Server.Entity
Microsoft.Azure.Mobile.Server.Home
Microsoft.Azure.Mobile.Server.Notifications
Microsoft.Azure.Mobile.Server.Quickstart
Microsoft.Bcl
Microsoft.Bcl.Build
Microsoft.Data.Edm
Microsoft.Data.OData
Microsoft.IdentityModel.Logging
Microsoft.IdentityModel.Tokens
Microsoft.Net.Http
Microsoft.Owin
Microsoft.Owin.Host.SystemWeb
Microsoft.Owin.Security
NETStandard.Library
Owin
Swashbuckle.Core
System.IdentityModel.Tokens.Jwt
System.Spatial
System.ValueTuple
Xamarin.Android.Support.Design
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
Xamarin.Forms

- Affected Devices:
Samsung Galaxy S8+

### Screenshots
![image](https://user-images.githubusercontent.com/6569195/33805714-030e8222-dd83-11e7-9bb1-a24334037f56.png)

### Reproduction Link
[(https://github.com/leemorris/LivePlayerBug/tree/master/App6)]

**Comment by jassmith** [comment]
Same answer as Issue #1351
