### ISSUE TITLE
IndicatorView indicators exceed the display size for Android

### ISSUE THREAD

**Issue by dnse123** [xamarin/Xamarin.Forms#13653]
**Description**
This issue reproduces on Android. 
If I have for example a CarouselView with 30 items, the IndicatorView can display on the screen only 20 dots(based on my display size) the last 10 dots are not visible. As I navigate through the carousel the focus moves from one dot to the other in the IndicatorView, until the 20th item is reached. After that, starting with the 21st item no indicator is highlighted until I reach the first item again or go back to the 20th item.

**Steps to Reproduce**
1. Create a CarouselView and give the ItemSource a large photo gallery.
2. Add an IndicatorView
3. Navigate through the carousel 

**Expected Behavior**
Same as on the IOS. Automatically render the dots for the indicator.

**Actual Behavior**
No indicator is highlighted after the n item, where n is the maximum number of indicators that are visible on the screen.

![Untitled](https://user-images.githubusercontent.com/54101873/106896146-30e47f80-66bf-11eb-9bcb-4f51414b74c3.png)

**Comment by rachelkang** [comment]
Hi, @dnfclas - thanks for submitting this issue! I'm able to repro this issue on Android. Whereas setting the WidthRequest seems to help on iOS, the dots unfortunately appear to be hidden when they overflow the width designated to them on Android.

I modified the XF IndicatorViewDemos Basic IndicatorView sample to test this [IndicatorViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/5927254/IndicatorViewDemos.zip)

cc @rmarinho

**Comment by rmarinho** [comment]
We have the property ` MaximumVisible="10"` will that work ?

**Comment by dnse123** [comment]
If I add the MaximumVisible property, the indicator still doesn't work as it should.

**Comment by rmarinho** [comment]
How should it work? if you use that property it limits the dots right?

**Comment by dnse123** [comment]
Yes it does limit the dots, but if you navigate through the carousel after the MaximumVisible element number, the last indicator is higlighted and if you navigate back the last indicator will remain highlighted until you reach the MaximumVisible element number -1. 
For example. If I have 10 items in the carousel and MaximumVisible=5. If I scroll after the 5'th item the last indicator will remain highlighted. If I am at the 8'th item and i navigate back the indicator does not change, the last indicator will remain highlighted until I reach the 4'th item, then the indicator highlights the 4'th dot.
Is this the expected behaviour?  
What if I don't want to use a MaximumVisible is there a way to have the same behavior on Android as on IOs?

**Comment by rmarinho** [comment]
yes @dnse123  that's the expected behaviour. 
Well if you don't use that property there's no way to know how to fit all the indicators.. 
You can make the items smaller? but other than that I don't know

**Comment by dnse123** [comment]
Ok, thank you.

**Comment by JunkyXL86** [comment]
IMO the MaximumVisible property is pretty useless as mentioned by @dnse123. It would be better to start scrolling the indicator list so that you can always track the movement.
