### ISSUE TITLE
[Bug] Page does not display correctly when searching in Shell.SearchHandler

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#13662]
### Description
I downloaded the sample : https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/
And when tested above sample in devices 9.0 and 10.0, the page does not display correctly.

![image](https://user-images.githubusercontent.com/42464252/106978532-63fa4200-6797-11eb-946f-e1b51bb8b154.png)

### Steps to Reproduce

1. download above sample ;
2. run it on device emulator 9.0 or 10.0;
3. and when we enter some key words into above SearchHandler, the page does not display correctly.

### Expected Behavior

The searched result will show correctly ,just as follows:

![image](https://user-images.githubusercontent.com/42464252/106978622-8e4bff80-6797-11eb-83bc-471c70a2cceb.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/42464252/106978669-a885dd80-6797-11eb-97cc-e7f57abd63ad.png)

Note:

The problem occurs when xamarin form nuget is 5.0, and when I tested the previous sample (the nuget is 4.8.0.1821), the UI is good.

**Comment by rachelkang** [comment]
Hi, @jessiezh0320 - thanks for submitting this issue! I'm able to reproduce on Android, and it definitely seems like a regression

cc @PureWeen

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/pull/13658
