### ISSUE TITLE
ListView pulltorefresh activityindicator is freezing when app is toggled between background and foreground 

### ISSUE THREAD

**Issue by nawnit** [xamarin/Xamarin.Forms#1366]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Whenever the list is pulled activity indicator starts animating and I start a background Task. Now when the app is sent to the background by pressing the home button and brought back to the foreground by clicking app icon on homepage or task menu, activity indicator freezes.

### Steps to Reproduce

1. launch the application
2.pull to refresh on list page 
3. start doing background task 
4. press home button and go to background 
5. comes to foreground 
6. activity indicator stuck 

### Basic Information

- Version with issue: latest 
- Last known good version:
- IDE:Xamarin Studio 6.3
- Platform Target Frameworks: 
  iOS

### Screenshots
![unadjustednonraw_thumb_4](https://user-images.githubusercontent.com/1667509/33817411-84b5b826-de65-11e7-8323-1d3d270d60d4.jpg)

**Comment by jassmith** [comment]
Did you mean to attach a repro case?

**Comment by nawnit** [comment]
[Grouping.zip](https://github.com/xamarin/Xamarin.Forms/files/1554894/Grouping.zip)

Hi I have just created the sample application in which you can see while going to background and coming to foreground indicator is getting stuck.
some more points in Xamarin forms lifecycle , OnAppearing and OnDisappearing method is not hitting while going to background to foreground I mean to say only first time its hitting OnAppearing method but OnDisappearing method is not getting called.

**Comment by nawnit** [comment]
Hi Jassmith,
Is there any update regarding this its known issue ya something need to fix in code side.

**Comment by breyed** [comment]
The activity indicator can also gets stuck even if the app remains in the foreground. If you navigation away from the page with the list view and then navigate back, the activity indicator no longer animates.

**Comment by samhouts** [comment]
Last tested with 4.0.0.62955-pre2. Still an issue.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
