### ISSUE TITLE
[Bug] [XF 5] SwipeView not rendering properly on iOS and Android when swiping

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/Xamarin.Forms#13670]
### Description

Starting from XF 5.0 SwipeView controls begun not to render properly during the swiping gesture: e.g. the whole SwipeView.LeftItems are shown since the beginning of the gesture in transparency. See attached sample project.

(Possible duplicate of https://github.com/xamarin/Xamarin.Forms/issues/13496 or https://github.com/xamarin/Xamarin.Forms/issues/13495 ?)

### Expected Behavior

The SwipeView.LeftItems should be revealed by the SwipeView content while dragging, gradually. Like in XF 4.8:
![XF4_8](https://user-images.githubusercontent.com/56956625/107022843-27821280-67a6-11eb-9612-031a61e853ab.gif)

### Actual Behavior
The content of the SwipeView.LeftItems is revealed at once at the beginning of the dragging gesture.
![xf5](https://user-images.githubusercontent.com/56956625/107022854-2bae3000-67a6-11eb-9745-ed2a88b532fa.gif)

### Basic Information

- Version with issue: 5.0.0.1931
- Last known good version: 4.8
- Platform Target Frameworks:
  - iOS
  - Android

### Sample Project
[SwipeViewBug2.zip](https://github.com/xamarin/Xamarin.Forms/files/5931831/SwipeViewBug2.zip)

**Comment by jsuarezruiz** [comment]
@inimirpaz You can see the fix and follow the conversation about the SwipeView Content BackgroundColor property behavior in #13673 

For now, a simple workaround is set the BackgroundColor to the SwipeView Content.

**Comment by soneparmobile** [comment]
The workaround to set the background color won't work for us if the swipe button is red.
![Simulator Screen Shot - iPhone 12 - 2021-02-11 at 08 58 15](https://user-images.githubusercontent.com/49791858/107670325-79fc7c80-6c47-11eb-8b59-f59ac5a55051.png)

**Comment by bakerhillpins** [comment]
It appears an alternate workaround is to replace the `SwipeItem` with an equivalent implementation of `SwipeItemView`. I've got the `SwipeView` as a `DataTemplate` in a `CollectionView` in case there's some confusion. 

Using the following SwipeItem will result in the display issue: 
 ```
<SwipeItem Text="Favorite"
           Command="{Binding BindingContext.TopicSelected, Mode=OneTime, Source={RelativeSource FindAncestor, AncestorType={x:Type ItemsView}}}"
           CommandParameter="{Binding Mode=OneTime}"
           BackgroundColor="LightGreen" />
 ```

Replacing it with an equivalent SwipeItemView will correct the display issue without requiring the `BackgroundColor` property of the content to be set:
 ```
<SwipeItemView BackgroundColor="LightGreen"
           Command="{Binding BindingContext.TopicSelected, Mode=OneTime, Source={RelativeSource FindAncestor, AncestorType={x:Type ItemsView}}}"
           CommandParameter="{Binding Mode=OneTime}">
    <StackLayout Margin="10">
        <Label Text="Favorite"/>
    </StackLayout>
</SwipeItemView>
 ```
