### ISSUE TITLE
App startup crash in ios 11 and above

### ISSUE THREAD

**Issue by RushAid93** [xamarin/Xamarin.Forms#1367]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
App startup crash in ios 11 and above during review in Apple Store, but working fine on developer's physical phone (running ios 11.2).

### Steps to Reproduce
1. Upload app binary through iTunes Connect.
2. Wait for app reviewed by Apple Store.
3. App startup crash in ios 11 and above.

### Expected Behavior
Run without problem in all iPhone OS.

### Actual Behavior
Startup crash on iOS 11 and above in Apple Store side

### Basic Information
- IDE: Visual Studio 7.3 (build 799)
- Platform Target Frameworks:
   - iOS:  iOS SDK 10.2
   - Android: Android SDK Platform-Tools 27.0.0, Compiling against Android 8.0 (API 26) 
- Android Support Library Version: 26.1.0
- Nuget Packages: 
   - Json.NET 7.0.1
   - ModernHttpClient 2.4.2
   - Xamarin Mobile 0.7.5
- Affected Devices: iPhone running OS 11 and above

**Comment by jassmith** [comment]
Without any kind of repo case or further information, we don't really have a solid mechanism for tracking this down. Are you sure you are testing release builds?

**Comment by kingces95** [comment]
@RushAid93 Please reopen if you're able to provide additional information.
