### ISSUE TITLE
[Bug] CollectionView, empty spaces appear when scrolling

### ISSUE THREAD

**Issue by demoh2019** [xamarin/Xamarin.Forms#13687]
![7741ECC6-F508-4212-AAFE-FB82D9EA717F](https://user-images.githubusercontent.com/75473925/107133790-93729100-68f4-11eb-89de-9dc9f6578ce0.png)
![B2847B1F-7371-415A-AD77-C4C895E10F0E](https://user-images.githubusercontent.com/75473925/107133791-953c5480-68f4-11eb-8e4b-1893ece917e4.png)

### Description
empty spaces appear when scrolling
### Steps to Reproduce

1. create colectionview grouping = true with grid auto cells
2. create RemainingItemsThresholdReachedCommand
3. scroll the page

### Basic Information

- Version with issue: last version
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

**Comment by demoh2019** [comment]
Possibly related to this #8604

**Comment by demoh2019** [comment]
fixed
            OnPropertyChanged(new PropertyChangedEventArgs(CountString));
            OnPropertyChanged(new PropertyChangedEventArgs(IndexerName));
            OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));

**Comment by jsuarezruiz** [comment]
Seems to be the same as https://github.com/xamarin/Xamarin.Forms/issues/8604

**Comment by hartez** [comment]
This is fixed in 5.0.0.1931.

**Comment by demoh2019** [comment]
@hartez my version 5.0.1.1965-nightly also tested on 5.0.0.1931

**Comment by hartez** [comment]
@demoh2019 Any way we could get a minimal repro project? Or at least some idea of what your templates look like, and what you're doing to load more items in your RemainingItemsThresholdReachedCommand?

**Comment by demoh2019** [comment]
the problem appeared due to ScrollTo being called many times by RemainingItemsThresholdReachedCommand the problem is no longer after scrolling from top to bottom
