### ISSUE TITLE
[Bug] Label: LineBreakMode incompatible with MaxLines

### ISSUE THREAD

**Issue by Eltee-Taiwo** [xamarin/Xamarin.Forms#13684]
### Description
On Android: Using both MaxLines and a truncation LineBreakMode on a label cause the label to only use one line before applying the truncation.

### Steps to Reproduce

1. Create a label in a constrained space with text that would cause it to overflow over multiple lines.
2. Add a MaxLines attribute to the label (eg. 2)
3. Add a LineBreakMode that applies truncation to the label (Ex. Tail truncation) 

### Expected Behavior
Text should span across two lines and then truncate. (iOS version)
![image](https://user-images.githubusercontent.com/37124491/107132098-d1929500-68a1-11eb-9a5a-e9e88d9ce467.png)

### Actual Behavior
Text only uses up one line before applying truncation
![image](https://user-images.githubusercontent.com/37124491/107132089-c50e3c80-68a1-11eb-8cc0-d998e2ac47a2.png)

### Reproduction Link
https://github.com/Eltee-Taiwo/13684-MaxLineAndLineBreak

### Environment
Xamarin.Forms 5.0.1.1955-nightly

**Comment by AlleSchonWeg** [comment]
@jsuarezruiz 
I have a similar issue, but with iOS: https://github.com/xamarin/Xamarin.Forms/issues/12710

**Comment by Eltee-Taiwo** [comment]
@AlleSchonWeg  I'd recommend creating a reproduction repo that can be used to test it. If you use my repo, do you experience the same issue? For me maxLines and LineTruncation works on iOS but not on Android.

**Comment by Eltee-Taiwo** [comment]
Thanks @rmarinho !
