### ISSUE TITLE
[Bug] Rotation loses items in Collection View

### ISSUE THREAD

**Issue by adnan** [xamarin/Xamarin.Forms#13689]
### Steps to Reproduce

1. Create a new Xamarin Forms app from Visual Studio template
2. Update to Xamarin Forms 5
3. Run app and click on the Browse tab
4. Switch to landscape view
5. Switch to portrait view
6. Items are no longer displayed in collection view
7. Pull to refresh
8. Items appear

### Expected Behavior

Items should still be visible in collection view on rotation change

### Actual Behavior

Items are no longer visible

### Basic Information

- Version with issue: Xamarin Forms 5
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  14.3
  - id:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jsuarezruiz** [comment]
Can reproduce the issue. Attach a sample where reproduce the issue:
![issue13689](https://user-images.githubusercontent.com/6755973/107199295-876ef800-69f6-11eb-835d-dcae4e1bcfb2.gif)
[Issue136892.zip](https://github.com/xamarin/Xamarin.Forms/files/5942548/Issue136892.zip)

**Comment by hartez** [comment]
This was addressed by 13640/13126 and will be fixed in the upcoming service release.
