### ISSUE TITLE
[Bug] Label Text is not rendered on UWP using XF 5.0 if Text contains "\r\n"

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#13709]
### Description

Upgraded solution from XF 4.8 to 5.0 . During testing found that a Label that has its Text property appended to was not being rendered on UWP. More accurately, the Text property was not being rendered (the BackgroundColor was). Rendering only occurred when the app window was re-sized (including by maximising or restoring the window).

Brief investigation showed that the rendering in XF 5.0 fails when the Text property contains "\r\n" . This worked in earlier versions of Xamarin.Forms

### Steps to Reproduce

Where _statusLabel is a Label that is included in a page already on display, and newItem is a string, do:

`_statusLabel.Text = _statusLabel.Text + "\r\n" + newItem;`

For test purposes, do this when a Button is pressed, so that you can repeat it at will.

### Expected Behavior

The Label's Text property should be rendered immediately.

### Actual Behavior

The Label's Text property is not rendered.

### Basic Information

- Version with issue: 5.0.0.1931
- Last known good version: 4.8
- Platform Target Frameworks: UWP:  18362

**Comment by jsuarezruiz** [comment]
Could you attach a sample where reproduce the issue?. I have tried to reproduce but without success. 
<img width="1156" alt="Captura de pantalla 2021-02-10 a las 11 55 45" src="https://user-images.githubusercontent.com/6755973/107500922-0864f580-6b97-11eb-8707-74a731da7665.png">

**Comment by johnshardman** [comment]
@jsuarezruiz - As per the "Steps to Reproduce"
Where _statusLabel is a Label that is included in a page **already on display**
For test purposes, **do this when a Button is pressed**

Your code is populating Text during the construction of the Page, not updating the Text one the Page is already on display.

**Comment by jsuarezruiz** [comment]
Tried updating the Label Text  using the Button click:
[Issue13709.zip](https://github.com/xamarin/Xamarin.Forms/files/5957789/Issue13709.zip)
![issue13709](https://user-images.githubusercontent.com/6755973/107504219-45cb8200-6b9b-11eb-9505-bc6bcf9d4b13.gif)

**Comment by johnshardman** [comment]
@jsuarezruiz - Ok, I'll put together a repro sample when I have time (trying and failing to get iOS build to deploy currently). I wonder if it's affected by having things wrapped in a ScrollView, but I'll check that when I have time. Thanks

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
