### ISSUE TITLE
[Spec]  Transparent navigation bar with full screen background image

### ISSUE THREAD

**Issue by samt1925** [xamarin/Xamarin.Forms#13708]
# [The feature] 

Need to set the background image starts from (transparent) navigation bar to end of the content page on shell app. I need navigation bars back button and title too.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
