### ISSUE TITLE
[Bug] Label in shell title view doesn't sit well in iOS device when I update XF to 5.0

### ISSUE THREAD

**Issue by kaysho** [xamarin/Xamarin.Forms#13712]
### Description

Labels in shell title view does not align vertically to center on my iOS simulator
### Steps to Reproduce

1. As soon as I updated my Xamarin project to 5.0 from 4.8, I started noticing this issue.
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![Screenshot 2021-02-09 at 12 36 29](https://user-images.githubusercontent.com/27432070/107405949-29cad080-6b08-11eb-8f37-c0e04cc0b42b.png)

**Comment by jsuarezruiz** [comment]
@kaysho Could you share your Shell TitleView definition?, just a Label, use a Layout etc?

**Comment by kaysho** [comment]
Hi @jsuarezruiz 
I pinned up a file new Xamarin forms Shell project and used the Flyout menu.

<Shell.TitleView>
        <Label
            FontSize="Title"
            HorizontalTextAlignment="Start"
            Text="Hello world"
            VerticalTextAlignment="Center" />
</Shell.TitleView>

**Comment by PureWeen** [comment]
@kaysho this has been fixed on the latest release
