### ISSUE TITLE
[Bug] IsClippedToBounds does not working in iOS

### ISSUE THREAD

**Issue by azapatac** [xamarin/Xamarin.Forms#13723]
### Description
When IsClippedToBounds property is true does not working

### Steps to Reproduce

1. Create a solution
2. In one ContentPage, add a Frame with CornerRadius="10"
3. Inside Frame add Grid with IsClippedToBounds="True"
4. Inside the Grid, add one label and button 
5. Add CornerRadius="0" in the button

![image](https://user-images.githubusercontent.com/8869059/107579714-8fc85e00-6bc3-11eb-975f-dba64e17ffb0.png)

### Expected Behavior
The button must have CornerRadius of the Frame at the bottom
![image](https://user-images.githubusercontent.com/8869059/107579602-60195600-6bc3-11eb-973a-f109ad40776d.png)

### Actual Behavior
The button must don't have CornerRadius of the Frame at the bottom
![image](https://user-images.githubusercontent.com/8869059/107579656-745d5300-6bc3-11eb-9135-797ce3a90017.png)

### Environment
=== Visual Studio Community 2019 for Mac ===

Version 8.8.4 (build 30)
Installation UUID: e17d9fcf-a85e-4515-bd40-a30fb47446ae
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000113

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.113 (2020-02/4fdfb5b1fd5) (64-bit)
	Package version: 612000113

=== Roslyn (Language Service) ===

3.8.0-5.20519.18+4c195c3ac1974edcefa76774d7a59a2350ec55fa

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.101/Sdks
SDK Versions:
	5.0.101
	3.1.405
	3.1.404
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.1
	3.1.11
	3.1.10

=== .NET Core 3.1 SDK ===

SDK: 3.1.405

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.6.0.15 (Visual Studio Community)
Hash: 87a1b18d8
Branch: d16-8
Build date: 2020-11-16 21:39:41-0500

=== Xamarin Designer ===

Version: 16.8.0.510
Hash: 44e3f3ce9
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:06:14 UTC

=== Xamarin.Android ===

Version: 11.1.0.17 (Visual Studio Community)
Commit: xamarin-android/d16-8/c0e2b8e
Android SDK: /Users/andreszapata/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: be2226b
Java.Interop: xamarin/java.interop/d16-8@79d9533
ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
SQLite: xamarin/sqlite/3.32.1@1a3276b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/andreszapata/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.8.0.32
Hash: 01a7774
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:24 UTC

=== Android Device Manager ===

Version: 16.8.0.46
Hash: 0a81419
Branch: remotes/origin/d16-8
Build date: 2020-12-10 00:32:44 UTC

=== Build Information ===

Release ID: 808040030
Git revision: eaa21a8983aa5c4bcf6a665892478b4f3d413418
Build date: 2020-12-10 11:06:12-05
Build branch: release-8.8
Xamarin extensions: eaa21a8983aa5c4bcf6a665892478b4f3d413418

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots
Xamarin 4.8 = Good
![image](https://user-images.githubusercontent.com/8869059/107579602-60195600-6bc3-11eb-973a-f109ad40776d.png)

Xamarin 5.0
![image](https://user-images.githubusercontent.com/8869059/107579656-745d5300-6bc3-11eb-9135-797ce3a90017.png)

**Comment by jsuarezruiz** [comment]
@azapatac Could you attach a sample where reproduce the issue?. I have created a small sample:
[Issue13723.zip](https://github.com/xamarin/Xamarin.Forms/files/5963881/Issue13723.zip)
<img width="1324" alt="Captura de pantalla 2021-02-11 a las 9 44 08" src="https://user-images.githubusercontent.com/6755973/107616166-cf3b8c80-6c4d-11eb-9bb5-a8743260b9c0.png">

But cannot reproduce the issue.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
