### ISSUE TITLE
[Bug] Clicks on elements within a SwipeView are buggy

### ISSUE THREAD

**Issue by NullQubit** [xamarin/Xamarin.Forms#13726]
### Description
I've added a button inside a swipe view.  Sometimes it's working fine, sometimes the clicks don't go through.  If it occurs, I need to change location of the click and try a few more times to make it work again.

```
    <StackLayout>
        <SwipeView>
            <SwipeView.RightItems>
                <SwipeItem Text="Delete" BackgroundColor="Red"/>
            </SwipeView.RightItems>
            <StackLayout>
                <Button BackgroundColor="#5BABABAB" Text="asdasdads" WidthRequest="50"/>
            </StackLayout>
        </SwipeView>
    </StackLayout>
```

### Steps to Reproduce

1. Add a button inside a swipe view
2. Try clicking and playing around for a bit.  
3. Sometimes clicks on the button are not going through.

### Expected Behavior

Clicks on elements within a SwipeView should always be responsive.

### Actual Behavior
Sometimes clicks stop working and you need to click somewhere else or reload the page.

### Basic Information
- Xamarin Forms Version: 5.0.0.1931
- Platform Target Frameworks: Android: 10.0
- Sample project: [App2.zip](https://github.com/xamarin/Xamarin.Forms/files/5964048/App2.zip)

<img src="https://user-images.githubusercontent.com/8645793/107619082-4a576f80-6c5b-11eb-8334-632158301814.gif" width="200">

**Comment by jsuarezruiz** [comment]
@NullQubit To review the issue need a little more information:
- What version of Xamarin.Forms do you use?
- On what platform do you reproduce the error?
- What is the visual hierarchy? Do you use the SwipeView in a CollectionView or other visual element?

**Comment by NullQubit** [comment]
@jsuarezruiz Thanks for your reply, added relevant information, sample project that reproduces the issue, and a GIF showing the issue.  In the GIF you can see that some clicks are not going through.

**Comment by jsuarezruiz** [comment]
Thanks for the attached sample!
