### ISSUE TITLE
[Bug] Image with CollectionView with Shell tabs

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#13727]
When I use shell tabs with CollectionView and Image when returning to tab the images are "reloaded", this does not happen if Image has no CollectionView.

 With ffimageloading does not happen.

I have tested on android on xiaomi.

https://github.com/xamarin/XamarinCommunityToolkit/issues/878

**Comment by jsuarezruiz** [comment]
Related sample in https://github.com/xamarin/XamarinCommunityToolkit/issues/878#issue-805482495
