### ISSUE TITLE
Flicker in Master Detail Navigation

### ISSUE THREAD

**Issue by steven-pearson** [xamarin/Xamarin.Forms#1373]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
White screen flickers within the transition from page to page in the PushAsync when navigating (as if a whole white screen is painted between the transitions). Previous versions were smooth.

Was ok in 2.3.4.270 can confirm present in 2.5.0.121934 (but may be since 2.4.x as reported by others)

### Steps to Reproduce
To recreate=> Create a simple master detail app and add a few pages to switch between (can be the same page) 
Navigate between the pages and notice a very quick white screen flicker between them. 

Revert XF back to 2.3.4.270 and try again. No white screen

Problem becomes more exaserbated when page content is more complex (white screen is shown longer).

### Expected Behavior
Clean transition

### Actual Behavior
Flicker's background mid transition

### Basic Information

- Version with issue:2.5.x
- Last known good version:2.3.4.270
- IDE:
- Platform Target Frameworks: 
  - Android: Any
- Android Support Library Version: Any
- Nuget Packages:
- Affected Devices:

### Reproduction Link

This GitHub example will demonstrate the issue https://github.com/MTWSM/Flickering_Issue_Demo

**Comment by FetFrumos** [comment]
Any news?

**Comment by wasaczd** [comment]
The problem still persists (XF 2.5.0.280555) and becomes more and more annoying :-(

**Comment by MrBandaruk** [comment]
Got the same problem. Any news?

**Comment by CSeb96** [comment]
Same problem here. Has anyone solved it?

**Comment by johnsonpontes** [comment]
Same problem here

**Comment by CSeb96** [comment]
A workaround I did was:

var page = new Page();
var masterdetail = new YourMasterPage() {Detail = new NavigationPage(page) };
await Navigation.PushAsync(masterdetail);

No more flickering between pages for me.

**Comment by johnsonpontes** [comment]
Even in version 2.3.4.270 the problem happens

**Comment by sander1133** [comment]
Problem is annoying. Already a few months without a fix. Currently on: 2.3.4.270.

**Comment by sathishkumar1624** [comment]
I have roll backed to 2.3.4.270, still the problem exists. Guys any one has a solution to this.

**Comment by FetFrumos** [comment]
Any news? Anybody here?

**Comment by PMarsh-UB** [comment]
Check this link out @FetFrumos : https://forums.xamarin.com/discussion/70863/flicker-delay-happens-while-navigating-to-some-other-page-on-click-of-menu-item-in-masterdetail-page

I've just posted a solution that may help.

**Comment by swansca79** [comment]
What's the hold up on this issue?  These kind of cosmetic problems just make the Android apps built with Forms look bush league.  The workaround by @PMarsh-UB kind of works, but it's the exact opposite how the official Xamarin documentation says to use the master/detail page.  When I tried it, the title stopped getting picked automatically from the detail page, and the nav drawer icon disappeared, so thats nice...

I guess it's all we can expect, considering how unusable Forms 2.5 and greater is, this is low hanging fruit.

**Comment by sander1133** [comment]
Is there any news or progress on this point?
