### ISSUE TITLE
[Bug] [WPF] NavigationBar Blank when using MasterDetailPage/FlyoutPage

### ISSUE THREAD

**Issue by LinGtriX** [xamarin/Xamarin.Forms#13746]
### Description
When using a MasterDetailPage or FlyoutPage (doesn't matter tested both) in a Xamarin.Forms project where WPF was added, the NavigationBar with the Burger-Icon an Title don't render at all. By a click at the left upper corner you may recognize that the Button for expanding the side-menu is still there and works.

### Steps to Reproduce
1. Create a new Empty Xamarin Project (without Shell)
2. Add WPF-Plattform following these instructions: https://docs.microsoft.com/de-de/xamarin/xamarin-forms/platform/other/wpf
3. Add a MasterDetailPage and set it too the MainPage
4. Add NavigationPage.HasBackButton="True", NavigationPage.HasNavigationBar="True" and MasterBehavior="Popover" to MasterDetailPage xaml
5. Run WPF Application

### Expected Behavior
NavigationBar shown with Burger-Button on the leftside upper corner.

### Actual Behavior
An empty space appears where the NavigationBar usually wold be

### Basic Information
- Version with issue: Xamarin.Forms 4.8.0.1269 and higher
- Last known good version: Xamarin.Forms 4.7.0.1351
- Platform Target Frameworks:
- WPF: 4.7.2
- NuGet Packages:
- Xamarin.Essentials (1.6.1)
- Xamarin.Forms (5.0.0.1931)
- Xamarin.Forms.Platform.WPF (5.0.0.1931)
- Affected Devices: Windows 10 1909 Build 183631316

### Screenshots
![Default](https://user-images.githubusercontent.com/61557348/107792823-dcdc3980-6d55-11eb-9194-c091d8abe835.png)
![SideBarPopOut](https://user-images.githubusercontent.com/61557348/107792835-e06fc080-6d55-11eb-97e1-01d8ea8abed7.png)

### Reproduction Link
[IssueReport.zip](https://github.com/xamarin/Xamarin.Forms/files/5972994/IssueReport.zip)

### Workaround
I tried to fill the NavigationBar via Custom Renderer in the platform specific WPF project but didn't make any progress in solving this

**Comment by peterfoot** [comment]
This appears to be true of any page using NavigationBar. Back button is not visible but clicking where it should be works. Also it fails to render any custom TitleView control so it is very badly broken. Xamarin.Forms 4.7 does show the correct behaviour but reverting this this version is not practical because of other dependencies

**Comment by peterfoot** [comment]
I can see that the TitleView issues is referenced in a separate issue - #3868 

The workaround in #12771 allows you to override the white background when setting using a Brush from code-behind.

**Comment by LinGtriX** [comment]
I dropped the idea of an expanding menu like the MasterDetail-/FlyoutPage could provide, because the WPF-Platform on Xamarin.Forms projects is mostly community driven.
Another option i found is using
if (Device.RuntimePlatform == Device.WPF)
            {
                FlyoutLayoutBehavior = FlyoutLayoutBehavior.Split;
            }
inside the Menu.xaml.cs Constructor

**Comment by MichaWresche** [comment]
I had the same issue and tried to set a background color in the surrounding WPF `FormsApplicationPage`. It seems that the hamburger menu as well as the title have a default foreground color of white (at least in my case). With a dark background color I can see hamburger menu and the page title. 

![image](https://user-images.githubusercontent.com/4797454/139797726-76593579-89e4-4ddd-b887-e1efd4199ad5.png)

![image](https://user-images.githubusercontent.com/4797454/139797693-75a01fe4-e1d4-4b6c-b282-5b8bff9acde7.png)

**Comment by LinGtriX** [comment]
Congrats in solving this for you!
I went further to next project's and won't combine Xamarin with WPF in future if it's possible to avoid this ^^

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
