### ISSUE TITLE
[Android] TapGestureRecognizer do not respond consistently to taps

### ISSUE THREAD

**Issue by adyshimony** [xamarin/Xamarin.Forms#1374]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
On Android the TapGestureRegenisor do not consistently fire the tapped event.

### Steps to Reproduce

Tap on any xamarin forms control (except button) 

### Expected Behavior
gesture event should be fired

### Actual Behavior
most  of times the gesture is not fired

### Basic Information

This is a known bug, but with importance normal.
https://bugzilla.xamarin.com/show_bug.cgi?id=60893#c1

## **We have an application that is about to get to production next month and we must solve this.**

Thanks,

Ady.

**Comment by timahrentlov** [comment]
Is this a variant of the tap gesture being interpreted as a swipe gesture? We have a problem where you need to do the tap really quick for it to register as a tap gesture. Our customer expect to be able to use the touch event in their, and they don't really understand that Forms does not support that fully. What should I tell them?

**Comment by hartez** [comment]
@timahrentlov Which version of Forms are you using?

**Comment by timahrentlov** [comment]
Our human testers has reported the problem on our samsung xCover3 devices since 2.4 : https://forums.xamarin.com/discussion/comment/301864#Comment_301864

Right now, we're using 2.5 build 28055.

**Comment by jassmith** [comment]
Can someone get me a minimal repro of this bug that actually repros the issue on all devices?

I am trying on a Samsung Galaxy 8+ and a Google Pixel. The test app I am using is as follows.

```csharp
			int taps = 0;
			var boxView = new BoxView();
			boxView.Color = Color.Red;
			boxView.Margin = 100;
#pragma warning disable CS0618 // Type or member is obsolete
			boxView.GestureRecognizers.Add(new TapGestureRecognizer(v => System.Diagnostics.Debug.WriteLine("Tapped " + taps++)));
#pragma warning restore CS0618 // Type or member is obsolete

			return new ContentPage { Content = boxView };
```

Every time I tap I get a new tap, no matter how fast I tap.

**Comment by jassmith** [comment]
And I didn't see the repro project on bugzilla, sorry, checking that.

**Comment by jassmith** [comment]
Okay checked that one too. Works fine. If I place a second finger or palm on the screen while trying to do the taps it doesn't work of course, but thats expected. Only some models have proper palm rejection.

**Comment by hartez** [comment]
On a Galaxy S8 running Android 7 (API 24) I cannot reproduce this with the project attached to the Bugzilla issue.

**Comment by hartez** [comment]
> Is this a variant of the tap gesture being interpreted as a swipe gesture? 

> Our human testers has reported the problem on our samsung xCover3 devices since 2.4 : 

There definitely _was_ a problem with tap gestures being interpreted as fling gestures in 2.4; it was addressed with https://github.com/xamarin/Xamarin.Forms/pull/1227.

**Comment by jassmith** [comment]
I agree with EZ, this is fixed as best I can tell

**Comment by hartez** [comment]
If anyone can create a reproduction of this bug using XF 2.5 or higher, please post it and reopen the issue.

**Comment by bobosummer** [comment]
the problem occurs again now.
