### ISSUE TITLE
Support for TreeView in 5.x?

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13742]
I am working on a MacOS project in Visual Studio for Mac.

I am trying to port a Windows applications which had a TreeCtrl.

I can't see a TreeView listed in Visual Studio for Mac and I can't type in in XAML file.

What is the correct way to use Tree Views in Xamarin.Forms 5.x? Or is there a suitable alternative?

Thank you.

**Comment by jsuarezruiz** [comment]
There is no TreeView control in Xamarin.Forms. There are different options at the community level: https://github.com/danvanderboom/Xamarin-Forms-TreeView or https://github.com/jsuarezruiz/TemplateUI
And also from third parties such as SyncFusion or Telerik.

**Comment by ajtruckle** [comment]
Hi @jsuarezruiz I have just looked at your first link and the tool doesn't look like it is supported any more. There is even a post there from 2018 saying it does not work on a Mac:

https://github.com/danvanderboom/Xamarin-Forms-TreeView/issues/11

I will look at the TemplateUI link now.

**Comment by jsuarezruiz** [comment]
This is the TreeView control from TemplateUI running on macOS:
<img width="1021" alt="91595458-dc94e100-e963-11ea-96d1-b59946e8ea0a" src="https://user-images.githubusercontent.com/6755973/107762050-ab9b4380-6d2c-11eb-9bee-927419040b41.png">

The basic stuff is working, but is a preview control (still pending to implement some important properties).

**Comment by ajtruckle** [comment]
@jsuarezruiz  The TemplateUI one looks really good and I think I could use that! Can't get on my Mac at the moment (son is using it for English).

This screen shot is from Windows:

![Screenshot](https://help-vrr.publictalksoftware.co.uk/lib/IMG_VisitsRotaShepherding.jpg)

You can see the tree control on the left and I basically want to replicate that.

**Comment by ajtruckle** [comment]
Hi @jsuarezruiz 

Just to let you know that I put a query on your TemplateUI GitHub system.

Thanks.
