### ISSUE TITLE
RadioButtonGroup not binding to ViewModel

### ISSUE THREAD

**Issue by xshiiiidev** [xamarin/Xamarin.Forms#13752]
Hello I have this problem and I can't find any solution on this from google so I end up here again in the GH repo.

I have this XAML code

```
<StackLayout RadioButtonGroup.SelectedValue="{Binding IsHidden}"
             RadioButtonGroup.GroupName="HiddenStatus"
             Orientation="Horizontal">
    <RadioButton Content="Yes" Value="true" />
    <RadioButton Content="No" Value="false" />
</StackLayout>
```

I am binding this to my ViewModel class boolean property of `IsHidden` but it seems it's not working. I always end up with the RadioButtonGroup output without any of the RadioButton selected when I initialized the XAML page. 

This approach works with my other fields like `Entry`. Only this RadioButtonGroup is not binding to my ViewModel class.

If can someone lead me to the right path of how to do this or if I am doing something wrong with the RadioButtonGroup binding I will thank you so much.

**Comment by hartez** [comment]
@xshiiiidev There is a bug in the way the RadioButton's Value property is compared to the RadioButtonGroup's SelectedValue, so boolean comparisons aren't working as expected. 

As a workaround for now, you can bind to an `object` property in your view model and use string values in your RadioButtons - take a look at [the XAML](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGroupBindingGallery.xaml) and [the code](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Controls/GalleryPages/RadioButtonGalleries/RadioButtonGroupBindingGallery.xaml.cs)

**Comment by xshiiiidev** [comment]
@hartez 

Thank you for the reply, I tried also comparing the values with string values and it's the same it is not binding.

The work around I did was to bind a value on each of the `RadioButton` and compare it in the code behind.

I didn't touch anymore the `RadioButtonGroup` level instead I focus on the `RadioButton` level bindings.

Kinda messy but it works.

**Comment by ekjuanrejon** [comment]
I am having the same issue... I am trying to do this in code... but it does not seem to be working

**Comment by xshiiiidev** [comment]
@ekjuanrejon 

I think they have confirmed this bug and is doing a fix here [5.0.0 SR 4 (Planning)](https://github.com/xamarin/Xamarin.Forms/projects/86#card-55210289)

**Comment by ekjuanrejon** [comment]
@xshiiiidev  Thanks

I am trying to do the following: since i am dynamically creating the RadioButton
```var stackLayout = new StackLayout() { BindingContext = question };
                    RadioButtonGroup.SetGroupName(stackLayout, question.Name);
                    RadioButtonGroup.SetSelectedValue(stackLayout, question.Selection);

**Comment by xshiiiidev** [comment]
@ekjuanrejon 

What you can try is to dynamically create individual RadioButton and assign individual values to each of them instead of RadioButtonGroup.

**Comment by ekjuanrejon** [comment]
yes but I have a list of questions that I need to created radio buttons for... thus I wanted to use the two way binding

**Comment by xshiiiidev** [comment]
You could still use two way binding with each individual RadioButtons.

**Comment by DiegoVenancioVieira** [comment]
> yes but I have a list of questions that I need to created radio buttons for... thus I wanted to use the two way binding

Do you solved it ?

**Comment by chucker** [comment]
@DiegoVenancioVieira I could get it to work with @hartez's sample code (binding to the `RadioButtonGroup`'s `SelectedValue`, and making sure that property is `object` rather than the type I actually want).

**Comment by djrpascu** [comment]
Are you guys getting two-way binding? My getter is getting called on my SelectedValue object property when view loads, but setter not getting called when changing radio button. It's setup for INPC.

**Comment by xshiiiidev** [comment]
@djrpascu 

The two way data binding is not working directly on the RadioButtonGroup. What I did was to bind the models on my individual RadioButton instead. Yup very dirty but we got no choice as of now they are still fixing the RadioButtonGroup binding issue.

**Comment by djrpascu** [comment]
@xshiiiidev 

so I was able to get part of the binding on the RadioButtonGroup.SelectedValue to work (from view to VM), turns out I was missed defining Value I only had Content defined... 😬 but changing the property on VM side still doesn't update view. So I did the following:

>        <StackLayout Grid.Row="27" Grid.ColumnSpan="3" 
>            RadioButtonGroup.GroupName="Result2RadioGroup" 
>            RadioButtonGroup.SelectedValue="{Binding Result2RadioGroup}"
>            Orientation="Horizontal" >
>                <RadioButton x:Name="rbne1" Content="Notified Electrician" Value="Notified Electrician"
>                    IsChecked="{Binding Result2RadioGroup, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbne1}}" />
>                <RadioButton x:Name="rbne2" Content="Planner to Notify Electrician" Value="Planner to Notify Electrician"
>                    IsChecked="{Binding Result2RadioGroup, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbne2}}" />
>                 <RadioButton x:Name="rbne3" Content="N/A" Value="N/A" 
>                    IsChecked="{Binding Result2RadioGroup, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbne3}}" />
>        </StackLayout>

Converter
```
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (value != null)
            {
                var radioButton = parameter as RadioButton;

                if (radioButton != null && radioButton.Value.Equals(value))
                {
                    return true;
                }
            }
            return false;
        }
```

Is there a better workaround? Any know how I might be able to reference the Radio Button control in the Converter Parameter? I wanted to avoid having to create name and reference them.

**Comment by chucker** [comment]
> Are you guys getting two-way binding?

No, I guess it's effectively `OneWayToSource` (even though [I surmise that it isn't supposed to be](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core/RadioButtonGroup.cs#L36)).

I haven't been able to set an initial value. Even if I explicitly set `IsChecked="true"` for the radio button I want, it doesn't look checked, so the RadioButtonGroup probably messes that up after the fact.

**Comment by BillyMartin1964** [comment]
@djrpascu , your way gave me an infinite loop. Any ideas why?

```
  <StackLayout
            Grid.Row="0"
            HorizontalOptions="Center"
            Orientation="Horizontal"
            RadioButtonGroup.GroupName="Reservations"
            RadioButtonGroup.SelectedValue="{Binding SelectedRadioButton}">

            <RadioButton
                x:Name="rbHotel"
                Margin="5,0"
                Content="{x:Static resource:AppResources.Hotel}"
                IsChecked="{Binding SelectedRadioButton, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbHotel}}"
                TextColor="{StaticResource PageTextColor}"
                Value="Hotel">
                <RadioButton.Behaviors>
                    <behaviors:EventToCommandBehavior
                        Command="{Binding ReservationRadioButtonCommand}"
                        CommandParameter="Hotel"
                        EventName="CheckedChanged" />
                </RadioButton.Behaviors>
            </RadioButton>
            <RadioButton
                x:Name="rbFlight"
                Margin="5,0"
                Content="{x:Static resource:AppResources.Plane}"
                IsChecked="{Binding SelectedRadioButton, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbFlight}}"
                TextColor="{StaticResource PageTextColor}"
                Value="Flight">
                <RadioButton.Behaviors>
                    <behaviors:EventToCommandBehavior
                        Command="{Binding ReservationRadioButtonCommand}"
                        CommandParameter="Plane"
                        EventName="CheckedChanged" />
                </RadioButton.Behaviors>
            </RadioButton>
            <RadioButton
                x:Name="rbRentalCar"
                Margin="5,0"
                Content="{x:Static resource:AppResources.RentalCar}"
                IsChecked="{Binding SelectedRadioButton, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbRentalCar}}"
                TextColor="{StaticResource PageTextColor}"
                Value="RentalCar">
                <RadioButton.Behaviors>
                    <behaviors:EventToCommandBehavior
                        Command="{Binding ReservationRadioButtonCommand}"
                        CommandParameter="RentalCar"
                        EventName="CheckedChanged" />
                </RadioButton.Behaviors>
            </RadioButton>
            <RadioButton
                x:Name="rbUber"
                Margin="5,0"
                Content="Uber"
                IsChecked="{Binding SelectedRadioButton, Converter={StaticResource RadioIsCheckedConverter}, ConverterParameter={x:Reference rbUber}}"
                TextColor="{StaticResource PageTextColor}"
                Value="Uber">
                <RadioButton.Behaviors>
                    <behaviors:EventToCommandBehavior
                        Command="{Binding ReservationRadioButtonCommand}"
                        CommandParameter="Uber"
                        EventName="CheckedChanged" />
                </RadioButton.Behaviors>
            </RadioButton>
        </StackLayout>
```

**Comment by djrpascu** [comment]
@BillyMartin1964 What does your VM look like? My guess is that having behaviors is doing double the work. Try commenting those out and see if that works.

**Comment by BillyMartin1964** [comment]
Thanks, @djrpascu  . Seems it was automatically setting it to two way. Once I went to one way, the loop stopped. It still didn't function as needed and I ended up having to use 4 bools for the  4 radio buttons. Pain in the butt.

**Comment by rnbokade** [comment]
I had this problem while working on a project at my job. There, one of the properties was being updated over an API call and I had to update the selected radio-button selection based on it. Can't share the whole code for reference. But here is what the idea was like.
//RadioButtonModel.cs==========
    public class RadioButtonModel
    {
        public RadioButtonModel(string text, uint value, bool isSelected)
        {
            Text = text;
            Value = value;
            IsSelected = isSelected;
        }
        public string Text { get; set; }
        public uint Value { get; set; }
        public bool IsSelected { get; set; }
    }
//Homeviewmodel.cs====================
public HomeViewModel()
{
Options.Add(new RadioButtonModel("settingA","value",false);
.
.
.
}
private List<RadioButtonModels> options = new List<RadioButtonModel>();
public List<RadioButtonModels> Options
{ get {return options;}
 set {SetProperty(ref options, value);}
}
private uint selectedoption;
public uint Selectedoption
{
get {return selectedoption;}
set {
       SetProperty(ref selectedoption,value);
       var copyoptions = Options.ToList();
       copyoptions.ForEach(x => x.IsSelected = x.Value==value);
       Options = copyoptions
}
}
//Home.xml
<StackLayout
                    RadioButtonGroup.SelectedValue="{Binding Selectedoption}"
                    RadioButtonGroup.GroupName="optionsl" Margin="87,0,0,0">
     <CollectionView ItemSource = "{Binding Options}">
 <CollectionView.ItemTemplate>
<DataTemplate>
<RadioButton GroupName="optionl" Value="{Binding Value}" IsChecked="{Binding IsSelected}" Content = "{Binding Text}"/>
</DataTemplate>
<CollectionView .ItemTemplate>
<CollectionView>
</StackLayout>

**Comment by rnbokade** [comment]
Actually, You could also ditch the whole RadioButtonGroup.SelectedValue Concept from XAML and simply bind the checkedchanged in above XAML radio button section to some function in ViewModel which changes the value of some selected property in the viewmodel

**Comment by angelru** [comment]
Hi, will this be ready for the next version? It is important.

**Comment by leoslima13** [comment]
Hey guys, there's another workaround if you don't want to use object to binding the values.
You can use a DataTrigger and Setter to set the property IsChecked = true.
In my case I have an enum value:

```
public enum ClientIsFrom
    {
        Instagram,
        Facebook,
        Whatsapp,
        Other,
    }
```
View
```
<StackLayout Orientation="Horizontal"
                                 RadioButtonGroup.GroupName="clientPlatform"
                                 RadioButtonGroup.SelectedValue="{Binding ClientIsFrom.Value}">
                        <RadioButton GroupName="clientPlatform"
                                     Value="{x:Static models:ClientIsFrom.Facebook}">
                            <RadioButton.Triggers>
                                <DataTrigger Binding="{Binding ClientIsFrom.Value}"
                                             TargetType="RadioButton"
                                             Value="{x:Static models:ClientIsFrom.Facebook}">
                                    <Setter Property="IsChecked" Value="True" />
                                </DataTrigger>
                            </RadioButton.Triggers>
                            <RadioButton.Content>
                                <StackLayout>
                                    <Label Text="{x:Static fonts:FaIcon.Facebook}"
                                           HorizontalOptions="Center"
                                           VerticalOptions="CenterAndExpand"
                                           FontFamily="FontAwesomeBrands"
                                           FontSize="30" />
                                    <Label Text="Facebook"
                                           HorizontalOptions="Center"
                                           VerticalOptions="End" />
                                </StackLayout>
                            </RadioButton.Content>
                        </RadioButton>
                       <RadioButton GroupName="clientPlatform"
                                     Value="{x:Static models:ClientIsFrom.Instagram}">
                            <RadioButton.Triggers>
                                <DataTrigger Binding="{Binding ClientIsFrom.Value}"
                                             TargetType="RadioButton"
                                             Value="{x:Static models:ClientIsFrom.Instagram}">
                                    <Setter Property="IsChecked" Value="True" />
                                </DataTrigger>
                            </RadioButton.Triggers>
                            <RadioButton.Content>
                                <StackLayout>
                                    <Label Text="{x:Static fonts:FaIcon.Instagram}"
                                           HorizontalOptions="Center"
                                           VerticalOptions="CenterAndExpand"
                                           FontFamily="FontAwesomeBrands"
                                           FontSize="30" />
                                    <Label Text="Instagram"
                                           HorizontalOptions="Center"
                                           VerticalOptions="End" />
                                </StackLayout>
                            </RadioButton.Content>
                        </RadioButton>
                      .... other options
```
ViewModel:

`public ReactiveProperty<ClientIsFrom?> ClientIsFrom { get; }`

**Comment by egvijayanand** [comment]
In `iOS 12`, am having issues in toggling among the RadioButtons in a group that is bound with a ViewModel.

The initial selection is set to the RadioButton with the value of the `SelectedMode`, after that unable to toggle to the other RadioButtons in the same group. Even tried setting the `BindingMode` to `TwoWay`, but to no avail.

And the same scenario works fine in Android.

Haven't tried it in higher versions of iOS, will add feedback after checking the same.

Kindly fix this issue at the earliest.

```xml
<StackLayout Orientation="Horizontal" RadioButtonGroup.GroupName="modes" RadioButtonGroup.SelectedValue="{Binding SelectedMode, Mode=TwoWay}">
	<BindableLayout.ItemsSource>
		<x:Array Type="{x:Type x:String}">
			<x:String>Add</x:String>
			<x:String>Subtract</x:String>
			<x:String>Multiply</x:String>
			<x:String>Divide</x:String>
		</x:Array>
	</BindableLayout.ItemsSource>
	<BindableLayout.ItemTemplate>
		<DataTemplate x:DataType="{x:Type x:String}">
			<RadioButton Content="{Binding .}" Value="{Binding .}"/>
		</DataTemplate>
	</BindableLayout.ItemTemplate>
</StackLayout>
```

**Comment by ederbond** [comment]
@jfversluis @hartez @maddymontaquila any news on this?
RadioButton it's a basic control that should just works. Please guys focus on this kind of bug before working on new stuffs. After several years XF it's still full of bugs on out of the box controls. For the good sake, I pray to god that you guys do not make it repeat on .NET MAUI. When I hear people talking about Commet, Blazor Mobile whaterver, I always think? Why not to focus on what matter?: MAKE WHAT YOU HAVE TO JUST WORKS (SQUASH BUGS - PLEASE).

**Comment by jfversluis** [comment]
Hey @ederbond! Thanks for the ping here. I totally understand how that may seem. In fact, maybe part of the reason that this is now open for so long is that we indeed want to make sure we don't repeat this for .NET MAUI.

We're doing the best we can at the moment and are pushing out service releases each month. Sorry we didn't get to this one yet. I see you're a contributor, first: thank you very much for that. But that also means you might have some knowledge to contribute yourself. If that's the case, that is probably your best bet right now to fix this in the timeframe you have in mind. 

Thank you for your patience!

**Comment by jtorvald** [comment]
I completely agree with @ederbond . I hope in .NET MAU there will be more focus on fixing bugs. The tendency seem to be to keep writing new code, new components, new features and no one is fixing serious bugs. The number of times I already thought to leave the Xamarin bandwagon because of these bugs and weird compiler issues after visual studio updates is probably running into double digits.

I also don't want to be negative and I understand a lot of the work is also done by the community and that we as a community also can pickup bugs. The problem there is that it is quite hard to try to fix specific issues in the Xamarin repo. I tried a couple of times to bug fix specific bugs but I can not just add the Xamarin Forms project as a reference to my project since visual studio or msbuild still keeps trying to use the nuget packages for some reason. Sometimes it's also hard to create the problem state in the Xamarin project. 

Even after I fixed a bug and made a pull request it was hard to find a Xamarin insider to help out, give guidance and to review / merge the pull request. I'm willing to fix things, but when you're new to such a large code base it is super handy if you can just ask some questions and get pointers to where to look or ideas on what it can be. Till now I've been struggling to find someone that can full fill such a role.

I really hope that this will change after the big rewrite to MAUI.

That being said: @jfversluis  will controls like the RadioButton be completely rewritten on release date or does this just not exist on release date for Maui? In case it's not going to be available on day one, I would like to give it a try to look into this issue.

**Comment by ederbond** [comment]
By now this bug makes the RadioButton useless for me. I had to create my own RadioButton control.

**Comment by jtorvald** [comment]
@jfversluis @hartez Well, I thought; when you have time to complain, you also have time to make a [PR](https://github.com/xamarin/Xamarin.Forms/pull/15291).... So here it is.

I made a small change in the HandleRadioButtonGroupValueChanged method for the RadioButton.
https://github.com/xamarin/Xamarin.Forms/pull/15291/files#diff-8d1fa33ba160c4d669d76c80fea10cbdf790f2d3cb184d275bd91a2db2fd218eR427

It would be super if someone can check the code change in this method in the RadioButton class and see if there are (potential) issues with it. I tested it as good as I could and in all my weird test cases it works a lot better than the previous value comparison.

Hopefully we can smash this one year old bug and close some issues. Hopefully the contribution also helps for Maui.

**Comment by jfversluis** [comment]
> Well, I thought; when you have time to complain, you also have time to make a PR

This is a statement I can get behind ;) I've kicked off the build, would you be able to test the resulting NuGet [as per the instructions here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages)? Make sure you get the exact version number that is mentioned. Other versions won't have your change.

I will have a look from our side and let's hope we can get rid of this one!

**Comment by jtorvald** [comment]
@jfversluis Thanks for the quick follow-up, will do that directly.

**Comment by jtorvald** [comment]
@jfversluis it seems to work 99% but with using an enum it does not seem to update the value on the bounded property after the selection is changed. That seems to be an unrelated bug, but I will figure out why and send you an update.

**Comment by jfversluis** [comment]
Thanks @jtorvald ! Appreciate it! If I overlook something you're doing feel free to ping or find my email address on my GitHub profile here and shoot me a message so we can discuss some things there if needed.

**Comment by jtorvald** [comment]
@jfversluis  I believe that working with an Enum like I had in mind is not going to work anyway. That is probably a general binding issue with enums. If I use object and convert the string back (in the setter) to an Enum it works. When I use an ValueConverter for my Enum and convert the value back to an Enum it also works. Since that is the standard procedure in XAML anyway, I believe that this PR fixed the issues above.

I pushed a new commit because of some minor issues in the control gallery page. 

**I hope others in this thread that had issues and workarounds for the radiobutton can also test the PR nuget 5.0.0.8122 to see if it fixes their issues and not breaks anything.** 

@xshiiiidev
@ekjuanrejon
@DiegoVenancioVieira
@djrpascu
@chucker
@rnbokade
@angelru
@leoslima13
@egvijayanand
@ederbond

**Comment by ideas2appsaustralia** [comment]
is this fix in xamarin.forms 5.0.0.2401? 

if not can someone be kind enough to point me to where the 5.0.0.8122 nuget can be found?

**Comment by jtorvald** [comment]
@ideas2appsaustralia no it does not. I bet @jfversluis will make a new release very soon.

The instructions to install the 8122 revision can be found [here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages).  Testing your solution with that version is appreciated so we can be sure that we only fix things and not break things.

**Comment by ideas2appsaustralia** [comment]
thanks got it. will be testing

**Comment by jfversluis** [comment]
Yes a new release should be imminent!
