### ISSUE TITLE
Adding .resx and designer files as links causes MissingManifestResourceException at runtime

### ISSUE THREAD

**Issue by sbeanland** [xamarin/Xamarin.Forms#1375]
### Description
Using the master-detail solution template from Visual Studio 2017 15.5, a MissingManifestResourceException can occur at runtime if you add an existing .resx file to the Xamarin forms project _as a link_. The issue does not occur if you add an existing .resx file normally (ie make a copy).

### Steps to Reproduce
(This is simplified to illustrate the problem)
1. Create a new project in Visual Studio -> Cross platform app
2. In the Wizard, select the following settings:
   Master Detail
   Platform: Android, iOS, Windows (UWP)
   UI Technology: Xamarin.Forms
   Code Sharing Strategy: .NET Standard
3. Right click on the solution -> Add -> New project
4. Create a default WPF project
5. Right click on the WPF project -> Add -> New item
6. Add a .resx file to the WPF project and add a new string value to the file 
7. In the Solution Explorer, right click on the Xamarin.Forms project (not the platform-specific projects) and click Add -> Existing item...
8. Navigate to the resource and designer files you created and **Add As Link**
9. In the Xamarin.Forms project, open Views/NewItemPage.xaml.cs 
10. In the NewItemPage constructor, change one of the new Item properties from the hard coded string to the resource string you defined in the .resx file
11. Run the UWP project and click the Add button in the top right

### Expected Behavior
The New Item page opens up with the resource string value displayed

### Actual Behavior
A MissingManifestResourceException is thrown, crashing the application

The issue does not occur if you add the .resx and designer files to the Xamarin.Forms project normally, instead of as links.

A sample project is attached.

[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/1548388/App3.zip)

**Comment by jassmith** [comment]
I think this is more an issue with the VS tooling than Xamarin.Forms itself. You might want to file an issue against XamarinVS on bugzilla (sorry for the bug tracker hopping, hopefully that will get resolved soon). I am leaving this open until @StephaneDelcroix has a chance to confirm what I said and can close the bug as invalid or confirm it.
