### ISSUE TITLE
[Enhancement] Add support for DisplayPromptAsync to MacOS

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13756]
## Summary
I am new to cross platform software development and I am trying to make an application for iOS and MacOS.

## API Changes

Simply add support for MacOS to `DisplayPromptAsync`.

At the moment this code will only work on iOS:

```
        async void DeletePublisherButton_Clicked(System.Object sender, System.EventArgs e)
        {
            if(ListPublishers.SelectedItem != null)
            {
                bool answer = await DisplayAlert("Please confirm!", "Are you sure?", "Yes", "No");

                if (answer)
                {               
                    _ViewModel.vrrData.ListPublishers.Remove(ListPublishers.SelectedItem.ToString());
                }
            }

        }
```

## Intended Use Case
Self explanatory.

Maybe this is already on the roadmap? I am using latest 5.x Xamarin.Forms.

Thanks.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
