### ISSUE TITLE
android:targetSdkVersion="26" causes JSBridge from HybridWebView control to no longer work

### ISSUE THREAD

**Issue by kspearrin** [xamarin/Xamarin.Forms#1376]
### Description

I recently updated my Xamarin.Forms project to Android SDK 26 (Oreo) and noticed that the JSBridge for my [HybridWebView](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/hybridwebview/) control stopped working properly. The `invokeCSharpAction` JavaScript function injected into the loaded webpage already returns undefined.

After messing around with various things for a while I discovered that simply removing `android:targetSdkVersion="26"` from my AndroidManifest.xml file causes the HybridWebView to start properly working again (`invokeCSharpAction` is now not undefined).

### Steps to Reproduce

1. Download attached test project.
2. Debug/run android app.
3. Inspect rendered WebView with `chrome://inspect` in Chrome.
4. Invoke `invokeCSharpAction('Hello!')` from the dev tools console.
5. Observe it works correctly.
6. Stop android app.
7. Edit the Properties/AndroidManifest.xml file and uncomment the line for `<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="26" />`. Comment out/remove the existing `<uses-sdk android:minSdkVersion="15" />` line.
8. Repeat steps 2-3.
9. Observe `invokeCSharpAction` is now undefined.

### Expected Behavior

`invokeCSharpAction` to work regardless of setting `android:targetSdkVersion="26"` on `<uses-sdk>` node in AndroidManifest.xml.

### Actual Behavior

`invokeCSharpAction` is undefined when setting `android:targetSdkVersion="26"` on `<uses-sdk>` node in AndroidManifest.xml.

Also worth noting that I downgraded my app back down to SDK 23 and the `invokeCSharpAction` works correctly no matter if I target `android:targetSdkVersion="23"` in the manifest or not.

### Basic Information

- Version with issue: Xamarin forms 2.3.4-2.5 (latest), Android SDK 26
- Last known good version: Android SDK 23
- IDE: VS 2017
- Platform Target Frameworks:
  - Android: 8.0 
- Android Support Library Version: 23 or 25
- Nuget Packages: n/a
- Affected Devices: All, but testing on Nexus 5X

### Screenshots

n/a

### Reproduction Link

[WebViewTesting.zip](https://github.com/xamarin/Xamarin.Forms/files/1548418/WebViewTesting.zip)

**Comment by kspearrin** [comment]
Also note that I can set android:targetSdkVersion="23" while still compiling against SDK 26 and it works as expected as well.

**Comment by jassmith** [comment]
This issue doesn't seem to be related to the core Xamarin.Forms project but an issue with the docs HybridWebView and the latest SDK. Is that correct?

**Comment by kspearrin** [comment]
@jassmith I suppose. I'm not sure where the actual issue is. Should I open this in some other repo? Xamarin.Android maybe?

**Comment by davidortinau** [comment]
@kspearrin thanks for this. 

I've raised the issue with our docs team to at least add a note, and if possible amend that sample to provide an Oreo compatible implementation.

You could open an issue on the documentation page you linked initially, by hitting the "I have a problem" button on the right. 

If we need anything additional from you, we'll ping back here. For now I'll close this issue since it's not directly against code in this project.
