### ISSUE TITLE
[Bug] CollectionView scrolling doesn't seem fixed

### ISSUE THREAD

**Issue by Tommigun1980** [xamarin/Xamarin.Forms#13777]
Hi.

I want to draw attention to https://github.com/xamarin/Xamarin.Forms/issues/13719.

It was marked as fixed, but if I update to the latest nightly build (build 2017 as of this writing) or the latest stable build (5.0.0.193) the problem doesn't go away.

Repro steps are as mentioned in the ticket; to **download the project linked in the ticket, and update it to the latest XF nightly** (build 2017 as of this writing).

The regression in question completely breaks the CollectionView so any input would be really appreciated. The regression was introduced between XF 5.0.1.1876 and XF 5.0.1.2000-nightly.

Why was https://github.com/xamarin/Xamarin.Forms/issues/13719 closed as fixed? If I take the repro project in there and update to a build that has the "fix" https://github.com/xamarin/Xamarin.Forms/commit/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0, the bug still happens.
Was the fix tested?

Thank you.

**Comment by Tommigun1980** [comment]
@hartez Hi. Just pinging regarding this -- your fix, https://github.com/xamarin/Xamarin.Forms/commit/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0, seems to be in the latest nightly builds but it doesn't seem to fix https://github.com/xamarin/Xamarin.Forms/issues/13719.

**Comment by Tommigun1980** [comment]
I just tested XF 5.0.0-pre3 and the regression is there as well. Pre-2 didn't have the issue.

Why was https://github.com/xamarin/Xamarin.Forms/issues/13719 closed as fixed? If I take the repro project in there and update to a build that has the "fix" https://github.com/xamarin/Xamarin.Forms/commit/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0, the bug still happens.

**Comment by hartez** [comment]
@Tommigun1980 I just downloaded the project from #13231 and updated it to the latest stable (5.0.0.2012) and everything seemed fine - I can scroll to the bottom of the CollectionView (the last half of the last item is no longer cut off) and the scrolling doesn't jump around. 

I also tried the latest nightly (5.0.0.2017) and that also seems to work. Is there some other issue I'm missing?

**Comment by Tommigun1980** [comment]
> @Tommigun1980 I just downloaded the project from #13231 and updated it to the latest stable (5.0.0.2012) and everything seemed fine - I can scroll to the bottom of the CollectionView (the last half of the last item is no longer cut off) and the scrolling doesn't jump around.
> 
> I also tried the latest nightly (5.0.0.2017) and that also seems to work. Is there some other issue I'm missing?

Hi @hartez and thanks for the reply!

If I take the repro project in the aforementioned ticket and update to either latest nightly or latest stable, it looks exactly like in https://drive.google.com/file/d/1CcDqvFsl8XihcqU-YA57eWQIAjF4PxPs/view?usp=sharing.
The fix didn’t do anything for me when running the repro project (or my main project).

Ive been testing with the iPhone 8 simulator and latest Xcode and latest iOS version in the simulator.

I saw the fox included some constant threshold that was very small. Maybe that constant is at fault here here preventing it from happening on all devices?

All I can say is that if I take the repro project and update Xamarin.Forma the issue happens even after the fix.

Thank you.

**Comment by Tommigun1980** [comment]
> @Tommigun1980 I just downloaded the project from #13231 and updated it to the latest stable (5.0.0.2012) and everything seemed fine - I can scroll to the bottom of the CollectionView (the last half of the last item is no longer cut off) and the scrolling doesn't jump around.
> 
> I also tried the latest nightly (5.0.0.2017) and that also seems to work. Is there some other issue I'm missing?

Hi @hartez and thanks for the reply!

If I take the repro project in the aforementioned ticket and update it to either latest nightly or latest stable, it looks exactly like in https://drive.google.com/file/d/1CcDqvFsl8XihcqU-YA57eWQIAjF4PxPs/view?usp=sharing.
The fix didn’t do anything for me when running the repro project (or my main project).

I've been testing with the iPhone 12 simulator and latest Xcode and latest iOS version in the simulator.

I saw the fix included some constant threshold that was very small. Maybe that constant is at fault here here preventing it from happening on all devices?

All I can say is that if I take the repro project and update Xamarin.Forms the issue happens even after the fix.

Thank you.

**Comment by Tommigun1980** [comment]
@hartez To triple check I updated both projects (ie the repro project linked in ticket https://github.com/xamarin/Xamarin.Forms/issues/13719 and my main project) to the latest stable (5.0.0.2012) and to the latest nightly (5.0.0.2017), and the issues are still happening, i.e. can't scroll to bottom and the items jump around constantly (video at https://drive.google.com/file/d/1CcDqvFsl8XihcqU-YA57eWQIAjF4PxPs/view?usp=sharing).

Xcode 12.4, iPhone 12 simulator (iOS 14.4), VS For Mac 8.9 Preview build 1593, XF 5.0.0.2017 + XF 5.0.0.2012 (ie latest everything).

The fix does not do anything for me. The fix https://github.com/xamarin/Xamarin.Forms/commit/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0 added the constant
https://github.com/xamarin/Xamarin.Forms/blob/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs#L20
Maybe it doesn't work on all devices?

I am literally unable to update right now as the CollectionView broke just prior to XF5 SR3, and the fix does not work for me at all.

Thank you.

**Comment by Tommigun1980** [comment]
This is probably not related, but I couldn't help but notice that
https://github.com/xamarin/Xamarin.Forms/blob/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs#L553

changes the state, by calling
https://github.com/xamarin/Xamarin.Forms/blob/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs#L562

Is it really intended that a method that is used to **ask** for whether an update should happen changes the state? Shouldn't the update happen only if said method returns true? I can see a ton of things going wrong if a method is called to see whether something should update actually does the update itself.

**Comment by Tommigun1980** [comment]
Hi. Could this be fixed as my app is completely broken right now.
Thank you.

**Comment by hartez** [comment]
> @hartez To triple check I updated both projects (ie the repro project linked in ticket #13719 and my main project) to the latest stable (5.0.0.2012) and to the latest nightly (5.0.0.2017), and the issues are still happening, i.e. can't scroll to bottom and the items jump around constantly (video at https://drive.google.com/file/d/1CcDqvFsl8XihcqU-YA57eWQIAjF4PxPs/view?usp=sharing).

@Tommigun1980 

I've downloaded the project from 13231 and updated it to 5.0.0.2012. Just today I've run it (in the simulator) on

iPhone 12 Pro Max iOS 14.4
iPhone 12 Pro iOS 14.4
iPhone 12 mini iOS 14.4
iPhone 12 iOS 14.4
iPhone X iOS 12.4

using application builds from both Windows and macOS. (I also ran it on several other devices and sims when testing for SR3). 

On all of these, I can scroll all the way to the bottom (the last item is not cut off) and the scroll doesn't jump around. 

Is there some other detail we're missing here? Is your version of the repro project modified in some way from the one linked in #13231? Are you seeing these issues at all when running on a physical device?

> Xcode 12.4, iPhone 12 simulator (iOS 14.4), VS For Mac 8.9 Preview build 1593, XF 5.0.0.2017 + XF 5.0.0.2012 (ie latest everything).

I'm using VS for Mac 8.9.1 (build 34) (i.e., latest stable). With VS for Windows I'm using 16.9.1 (latest stable).

> XF 5.0.0.2017 + XF 5.0.0.2012

What is the "XF 5.0.0.2017" part of this? AFAIK that's not a published XF NuGet package version.

**Comment by Tommigun1980** [comment]
> > @hartez To triple check I updated both projects (ie the repro project linked in ticket #13719 and my main project) to the latest stable (5.0.0.2012) and to the latest nightly (5.0.0.2017), and the issues are still happening, i.e. can't scroll to bottom and the items jump around constantly (video at https://drive.google.com/file/d/1CcDqvFsl8XihcqU-YA57eWQIAjF4PxPs/view?usp=sharing).
> 
> @Tommigun1980
> 
> I've downloaded the project from 13231 and updated it to 5.0.0.2012. Just today I've run it (in the simulator) on
> 
> iPhone 12 Pro Max iOS 14.4
> iPhone 12 Pro iOS 14.4
> iPhone 12 mini iOS 14.4
> iPhone 12 iOS 14.4
> iPhone X iOS 12.4
> 
> using application builds from both Windows and macOS. (I also ran it on several other devices and sims when testing for SR3).
> 
> On all of these, I can scroll all the way to the bottom (the last item is not cut off) and the scroll doesn't jump around.
> 
> Is there some other detail we're missing here? Is your version of the repro project modified in some way from the one linked in #13231? Are you seeing these issues at all when running on a physical device?
> 
> > Xcode 12.4, iPhone 12 simulator (iOS 14.4), VS For Mac 8.9 Preview build 1593, XF 5.0.0.2017 + XF 5.0.0.2012 (ie latest everything).
> 
> I'm using VS for Mac 8.9.1 (build 34) (i.e., latest stable). With VS for Windows I'm using 16.9.1 (latest stable).
> 
> > XF 5.0.0.2017 + XF 5.0.0.2012
> 
> You're not mixing the latest stable and the latest nightly, are you? Running one on the cross-platform project and one on the iOS project?
> 
> The nightlies are built off of the main branch; depending on when the nightly was built, it won't necessarily contain all the fixes from a release branch (e.g, 5.0.0).

When I run the project it's just broken and looks like this: https://drive.google.com/file/d/1MwB1hc7IIj0_BNXNh4cMWoa7kJNgOdg2/view?usp=sharing

That is from the iPhone 12 simulator. It just doesn't work. It's not modified in any way, it's just the repro project updated to latest XF version.

**Comment by hartez** [comment]
@Tommigun1980 Can you upload/post a new version of your repro project that's updated to the latest XF version? That way I can compare to the version I have here - maybe I'm missing a detail when updating the project.

**Comment by Tommigun1980** [comment]
@hartez I deleted everything and reinstalled the latest version and the issue did go away. So the fix does seem to work for me now. I have not encountered this update problem before.

Thank you for fixing it! I will close this ticket as I can no longer get it to happen.
