### ISSUE TITLE
Using Microsoft Visual Studio Community 2019 Version 16.8.5 and Xamarin Forms 5

### ISSUE THREAD

**Issue by genifycom** [xamarin/Xamarin.Forms#13778]
### Description
If you create a Xamarin Forms app using Studio Community 2019 Version 16.8.5 then the project created still uses:

  <PackageReference Include="Xamarin.Forms" Version="4.8.0.1451" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />

Why does it not offer the choice to create a Xamarin Forms 5 project?
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by hartez** [comment]
Because the templates have not yet been updated to use 5.0.0 by default. This may change in a future version of VS; until then, you'll have to update the nuget packages.
