### ISSUE TITLE
TabbedPage can't show all tabs in bar if there is more than 5 tabs

### ISSUE THREAD

**Issue by MohamedBenAyed** [xamarin/Xamarin.Forms#13785]
### Description
I'm developping a TabbedPage in mode TabFixed with Xamarin form and i have more than 5 tabs. 
the problem is with normal TabbedPage, it show only 4 tabs and a button "More" to show the others 

### Steps to Reproduce

1. Create TabbedPage
2. Add more than 5 pages 
3. you will see the more button and just 4 tabs 

### Expected Behavior
Show all tabs with a very similiar Width whatever the number of tabs
### Actual Behavior
it show only 4 tabs and a button "More" to show the others 
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 

### Screenshots

![image](https://user-images.githubusercontent.com/19921234/108179497-f8ed2b80-7105-11eb-912f-4468a34498e6.png)

**Comment by themronion** [comment]
@MohamedBenAyed thats normal behaviour

**Comment by MohamedBenAyed** [comment]
I have 6 tabs, I want to show all of them one time

**Comment by Xamtastic** [comment]
@MohamedBenAyed Although I don't have an API link, I do believe the design pattern for mobile Tabs is to have no more than 4 - hence I'm inclined to agree with @themronion

**Comment by adammeaney** [comment]
Use the Xamarin Community Toolkits TabView if you need more Tabs.

**Comment by PureWeen** [comment]
This is a limitation of the native BottomNavigationView control on Android
If you add more than 5 items it will just crash so instead we added a more button. 
As others have indicated you would probably have better luck using the TabView or using something like Sharpnado
