### ISSUE TITLE
Java.Lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by kwiqniss** [xamarin/Xamarin.Forms#1378]
### Description
I'm filing this on behalf of a customer. Please contact me directly for customer specific details which I can't share here.

Q: Describe the issue including as much detail as possible
A: We upgraded our mobile app on 11/16. After that we have seen a huge increase in crashes as reported by Google Play console (see picture). The HockeyApp reporting did not see a similar increase.

Here is the little info that Google Play has on the crash:
java.lang.RuntimeException: 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
Caused by: java.lang.reflect.InvocationTargetException: 
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)

We *believe* it is also the most frequent bug we have in HockeyApp, which has more info:
FragmentManagerImpl.checkStateLoss
Java.Lang.IllegalStateException: Can not perform this action after onSaveInstanceState
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
android.support.v4.app.FragmentManagerImpl.checkStateLoss()FragmentManager.java:1842
android.support.v4.app.FragmentManagerImpl.enqueueAction()FragmentManager.java:1860
android.support.v4.app.BackStackRecord.commitInternal()BackStackRecord.java:650
android.support.v4.app.BackStackRecord.commit()BackStackRecord.java:609
android.support.v4.app.DialogFragment.show()DialogFragment.java:143
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.app.Activity.runOnUiThread()Activity.java:6082
md5a9f9c2b68bba3aa8be56a056e4cd456a.MainActivity.n_onActivityResult(Native Method)
md5a9f9c2b68bba3aa8be56a056e4cd456a.MainActivity.onActivityResult()MainActivity.java:66
epic.mychart.android.library.prelogin.a.b()AuthenticationService.java:758
epic.mychart.android.library.prelogin.a.a()AuthenticationService.java:55
epic.mychart.android.library.prelogin.a$4.a()AuthenticationService.java:605
epic.mychart.android.library.prelogin.a$5.a()AuthenticationService.java:628
epic.mychart.android.library.e.f.onPostExecute()CustomAsyncTask.java:608
android.os.AsyncTask.finish()AsyncTask.java:667
at android.os.AsyncTask.-wrap1(AsyncTask.java)
android.os.AsyncTask$InternalHandler.handleMessage()AsyncTask.java:684
android.os.Handler.dispatchMessage()Handler.java:102
android.os.Looper.loop()Looper.java:154
android.app.ActivityThread.main()ActivityThread.java:6823
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1557
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1445
Xamarin caused by: Java.Lang.IllegalStateException: Can not perform this action after onSaveInstanceState
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<9d0e62014b6e4697a3a27c36abf42d32>:0
Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)<788eebdbf0814bff8f927caa5d06e5bb>:0
Android.Runtime.JNIEnv.CallNonvirtualVoidMethod(IntPtr jobject, IntPtr jclass, IntPtr jmethod, JValue* parms)<a3404d7626684c388c9fc4514745d9d3>:0
Android.Support.V4.App.DialogFragment.Show(FragmentManager manager, string tag)<7e083afc7c9045f59e01d9c14931060d>:0
Acr.UserDialogs.UserDialogsImpl.<>c__DisplayClass26_0<TFragment, TConfig>.<ShowDialog>b__0()<a5fa07ca31cf44ee8fe096156a765ea2>:0
Java.Lang.Thread.RunnableImplementor.Run()<a3404d7626684c388c9fc4514745d9d3>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<a3404d7626684c388c9fc4514745d9d3>:0
at (wrapper dynamic-method) System.Object:e9b9f417-abc6-4c6f-91e1-cb97882c1fe4 (intptr,intptr)
--- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
android.support.v4.app.FragmentManagerImpl.checkStateLoss()FragmentManager.java:1842
android.support.v4.app.FragmentManagerImpl.enqueueAction()FragmentManager.java:1860
android.support.v4.app.BackStackRecord.commitInternal()BackStackRecord.java:650
android.support.v4.app.BackStackRecord.c

### Steps to Reproduce
Are you able to reproduce the issue? Is it consistent? Or intermittent?
-We don’t know how to reproduce, but it happens a lot to our customers. See picture of crashes.
 
Do you have related code to what’s shown in the stack trace? Is that something you can share? 
-None of our code is referenced in the Google Play crash report. 

### Expected Behavior
Application should not crash with this error

### Actual Behavior
This crash is reported in Google Play crash reports

### Basic Information

- Version with issue: 2.3.4.267
- Last known good version: Xamarin.Forms 2.3.2.127
- IDE: Visual Studio 2017 Enterprise 15.4.4
- Platform Target Frameworks: 
Android - all versions

- Nuget Packages: see attached screenshot for Nuget packages before and after the change that introduced the issue.
- Affected Devices: No specific device type stands out. All devices.

[XamarinWorkItemDetails.zip](https://github.com/xamarin/Xamarin.Forms/files/1549558/XamarinWorkItemDetails.zip)

Please contact me directly for customer specific details - david.hollowell @ alias

**Comment by jassmith** [comment]
I believe this issue was fixed in 2.4.0, can you please confirm?

**Comment by bentmar** [comment]
A workaround for your case would be to not show the Alert or ActionScheet while the app is in the background and do a local notification instead.

**Comment by kingces95** [comment]
@kwiqniss assuming your +1 means the workaround worked for you. Please re-open if that's not the case. @bentmar Thanks!
