### ISSUE TITLE
[Enhancement] Dual Screen or Split Scrolling and/or CollectionView

### ISSUE THREAD

**Issue by njsokalski** [xamarin/Xamarin.Forms#13799]
## Summary
Layout(s) used to split a View into multiple pieces when necessary. Layout(s) would be arranged just like other Layout(s) (Grid, StackLayout, Frame, etc.), and would have a group name for the associated Layouts. Scrolling any of the associated Layout(s) would automatically synchronize the scroll position of the other associated Layout(s).

## API Changes

bool Origin - Specifies that this Layout is the upper-left most scroll content of the group. This would only be necessary in one of the Layouts for a group, and would have a default value of false. All associated Layouts will automatically use the same content as specified in the Layout where this property is set to true.
string GroupName - Associates the Layout with other Layout(s) of the same GroupName
Layout RightOf - The Layout whose scroll content is immediately to the left of this Layout's scroll content (the scroll content horizontally continues from RightOf to this Layout)
Layout Below - The vertical variation of RightOf
double HorizontalViewportOffset - A custom offset of the viewport used by this Layout. This could be used to cause "overlapping" viewports or partially hidden content. This would most likely be rarely used, and have a default value of 0
double VerticalViewportOffset - The vertical variation of HorizontalViewportOffset
double HorizontalScrollPositionTotal - The horizontal scroll position of this Layout's scroll content relative to all scroll content. Therefore, only the Layout with Origin=true or a HorizontalViewportOffset other than 0 will ever have a value of 0. This property may or may not be readonly, since scrolling will usually be done using HorizontalScrollOffset or a method
double HorizontalScrollOffset - The horizontal scroll position relative to the initial position. Because scrolling is synchronized, this value will be the same for all associated Layouts
double VerticalScrollPositionTotal - The vertical variation of HorizontalScrollPositionTotal
double VerticalScrollOffset - The vertical variation of HorizontalScrollOffset

<Grid ColumnDefinitions="300,*">
   <SplitScroll x:Name="ssLeft" Grid.Column="0" Origin="true" GroupName="TestSplitScroll">
      
   </SplitScroll>
   <SplitScroll x:Name="ssRight" Grid.Column="1" GroupName="TestSplitScroll" RightOf="ssLeft"/>
</Grid>

Note that the second SplitScroll (ssRight) has no content, because it will use the same content as the one with Origin="true" (ssRight)

## Intended Use Case
This is intended for collections and/or large images that need split into multiple scrollable pieces so that they can be custom arranged, either to place elements between them or placed on separate screens. Because one of the most common uses (including mine) will be for collections, you may wish to make a variation with properties such as ItemsSource and ItemPositions, along with methods such as SnapToItem(), or other methods to help align the items with the edges of the different SplitScroll(s).

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
