### ISSUE TITLE
[Bug] CollectionView Header, ItemTresholdReachedCommand

### ISSUE THREAD

**Issue by alzubitariq** [xamarin/Xamarin.Forms#13802]
### Description
When I use a CollectionView with Header(contains some elements)
the ItemTresholdReachedCommand trigger automatically , I think ItemTresholdReachedCommand should only affect ItemTemplate and not the CollectionView Header.

### Code
`<CollectionView  ItemsSource="{Binding Items}"
                         RemainingItemsThresholdReachedCommand="{Binding ItemTresholdReachedCommand}"
                         RemainingItemsThreshold="{Binding ItemTreshold}">
            <CollectionView.Header>
                <Grid HeightRequest="1"/>
            </CollectionView.Header>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>`
### Screenshot

![Bug](https://user-images.githubusercontent.com/79016283/108442809-5b5a3f00-7260-11eb-8ce7-db80ca463d55.gif)

### Expected Behavior
RemainingItemsThresholdReached event fires when there are an items determined by ItemsThreshold not yet scrolled to

Basic Information:
Visual Studio 16.8.5
Xamarin Forms 5.0.0.2012
only tested on Android

**Comment by angelru** [comment]
The same issue:
https://github.com/xamarin/Xamarin.Forms/issues/11060
