### ISSUE TITLE
Text Double Encoded on Xamarin Forms GTK

### ISSUE THREAD

**Issue by ihvrooman** [xamarin/Xamarin.Forms#13808]
Text is still being double encoded on Xamarin Forms GTK. Issue #4880 resolved this but then the issue came back at some point.

Here's my comment from the issue #4880:

@thenderson21
I'm still having this issue on Xamarin Forms GTK 5.0.0.2012. 

I looked at the Label renderer in the repo and it looks like @paymicro and @rmarinho removed your fix when adding a text transform property in commit abd7aa9248937b0c9b8929b73891f5b0dad41ff2 for fix #3667.

Your original fix for double encoding on Label renderer:
![image](https://user-images.githubusercontent.com/61886068/108221951-4ff30080-7106-11eb-8008-c885f1f0235e.png)

Their commit with change to label renderer (that might have added double encoding back in):
![image](https://user-images.githubusercontent.com/61886068/108220556-d9093800-7104-11eb-9ff5-61561697b5db.png)

Screenshot of my app showing issue in Xamarin Forms GTK 5.0.0.2012:
![image](https://user-images.githubusercontent.com/61886068/108218647-e0c7dd00-7102-11eb-99d0-a3562b55ff3c.png)

_Originally posted by @ihvrooman in https://github.com/xamarin/Xamarin.Forms/issues/4880#issuecomment-780594944_

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
