### ISSUE TITLE
[Bug] "System.DivideByZeroException: Attempted to divide by zero." exception when opening the CarouselView in UWP

### ISSUE THREAD

**Issue by RaulBastian** [xamarin/Xamarin.Forms#13818]
"System.DivideByZeroException: Attempted to divide by zero." exception when opening the CarouselView in UWP

### Steps to Reproduce

1. Bind the CarouselView to an observablecollection (in my sample of type int)
2. Define an itemtemplate 
3. Start UWP project

### Expected Behavior
The carousel should show correctly without any exceptions

### Actual Behavior
The carousel isn't shown and a "System.DivideByZeroException: Attempted to divide by zero." exception is raised
### Basic Information

Xamarin.Forms v5.0.0.2012
Target version: Windows 10, version 2004(10.0; Build 19041)
[sample.zip](https://github.com/xamarin/Xamarin.Forms/files/6016707/sample.zip)

**Comment by anirbandebroy** [comment]
Any update regarding it ? It seems the CarouselView  is completely broken for UWP.

**Comment by DennisWelu** [comment]
Based on the crash stack, the problem may be here: https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/CollectionView/LoopableCollectionView.cs#L75. The remainder operator would throw that if the right side count is zero. I looked at pulling renderer code into my project and working around it...but it's a big renderer that uses a lot of internal classes. Makes that process difficult.

**Comment by DennisWelu** [comment]
Interesting behavior change, if you set Loop="False" then the exception changes to 

```
System.IndexOutOfRangeException : Can't set CarouselView to position 0. ItemsSource has 0 items.   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.UpdateFromPosition()
   at Xamarin.Forms.Platform.UWP.CarouselViewRenderer.InitialSetup(Object sender, SizeChangedEventArgs e)
```
Looks like these lines of code will always throw an exception when the items list is empty: https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.UAP/CollectionView/CarouselViewRenderer.cs#L357-L358

**Comment by jsuarezruiz** [comment]
Could you try again using the NuGet package from https://github.com/xamarin/Xamarin.Forms/pull/14597?

**Comment by GikuMironica** [comment]
updates on this issue?

**Comment by krdmllr** [comment]
@jsuarezruiz I tested your example from the XF repo, which works, the sample from @RaulBastian does not, but its basically the same code. I tried to update XF to the latest github package but that did not solve it aswell.
