### ISSUE TITLE
[Bug] Ellipse Fill and Stroke not accepting values from binding Context

### ISSUE THREAD

**Issue by alzubitariq** [xamarin/Xamarin.Forms#13821]
### Description

When bind Fill property or Stroke property it seems they are not from bindable properties 

### Steps to Reproduce

`  <Ellipse Fill="#FF9900" Stroke="#FF9900" /> drawn without issue`
`<Ellipse Fill="{Binding Color}" Stroke="{Binding Color}" /> nothing drawn :(`

### Expected Behavior
I think it should take a color.

### Actual Behavior
only working with fixed values or whatever it is name

### Screenshots
![eliips](https://user-images.githubusercontent.com/79016283/108635637-0ea57c80-7489-11eb-927f-eeaad66814af.gif)

### Basic Information
  Version with issue : 5.0.0.2012
  Last known good version: ?
  IDE: VS for Windows
  Platform Target Frameworks:
  iOS:
  Android: Android 10.0
  UWP:
  Nuget Packages : ?
  Affected Devices : ?

**Comment by EvilVir** [comment]
The problem here is that Fill and Stroke properties expects Brush type value, not Color. It took me some time to realize that, the simple IValueConverter allowed me to bind Color to these properties.

``` 
public class ColorToSolidColorBrushConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture) =>
            value is Color color ? new SolidColorBrush(color) : null;

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) =>
            value is SolidColorBrush brush ? brush.Color : null;
    }
```

Nonetheless it should be "fixed" by allowing to bind Color directly.

**Comment by jsuarezruiz** [comment]
This have been fixed with the latest version. There is an implicit conversion and can use a Color type in this cases.
