### ISSUE TITLE
[Bug] Specifying ScaleY results in ProgressBar going behind neighboring Views rather than the layout being recalculated

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#13825]
### Description

I apply ScaleY to a ProgressBar to make it taller. However, I find that it then goes behind the Views that I would expect to be above it and below it, rather than doing a layout cycle that results in Views being re-positioned to prevent overlap.

The documentation for ScaleY simply says "Gets or sets a scale value to apply to the Y direction", which I would interpret as the VisualElement is made taller and that everything adjusts as per VerticalLayout options etc.
See https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.visualelement.scaley?view=xamarin-forms

@ColeX reproduced this - see https://forums.xamarin.com/discussion/comment/429749/#Comment_429749

### Steps to Reproduce

1. Build a page containing a ProgressBar, with other Views above and below it on the page
2. Set ScaleY on the ProgressBar to a value greater than 1 (start with 10 for obvious effect)

### Expected Behavior

The page layout should adjust so that the ProgressBar does not overlap neighboring Views.

### Actual Behavior

The ProgressBar goes behind neighboring Views, with those other Views not having moved.

### Basic Information

- Version with issue: 5.0.0.1931

### Workaround

See https://forums.xamarin.com/discussion/comment/429749/#Comment_429749
It's not an ideal workaround (it relies on a layout cycle having already been done) but it's usable.

**Comment by StephaneDelcroix** [comment]
Scale doesn't change the object size, or Bounds

**Comment by johnshardman** [comment]
@StephaneDelcroix - It doesn't, but shouldn't it? What would be the reason for it not to do so?

@davidbritch - If the current behavior is intentional, the documentation for Scale, ScaleX and ScaleY should make it clear that these properties do not affect the Width or Height of the VisualElement (I suspect that most people would expect Width and Height to be affected), and should ideally explain how to use WidthRequest and/or HeightRequest to make the VisualElement size match the scaling (even before a layout cycle has been completed already).

**Comment by davidbritch** [comment]
@johnshardman Afraid that the API docs are an engineering responsibility.
