### ISSUE TITLE
[Bug] Xamarin.Forms iOS button Command is not getting invoked

### ISSUE THREAD

**Issue by AbhijeetChowdhury92** [xamarin/Xamarin.Forms#13824]
### Description
I am using latest release of Xamarin Forms 5.0.0.2012. The button command is not getting invoked on iOS. It worked perfectly with 5.0.0.1874.
### Steps to Reproduce

1.  Construct a button
2.  Bind a command 
3.  Tap the button

### Expected Behavior
Command should get invoked
### Actual Behavior
Command not getting invoked
### Basic Information

- Version with issue: 5.0.0.1905, 5.0.0.1931, 5.0.0.2012
- Last known good version: 5.0.0.1874
- Platform Target Frameworks: 
  - iOS:   12.2
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
