### ISSUE TITLE
Allow for async navigating cancellation on WebView

### ISSUE THREAD

**Issue by RubaShanmugamm** [xamarin/Xamarin.Forms#13834]
### Steps to Reproduce

1.  Run the sample on Android. https://www.syncfusion.com/downloads/support/directtrac/general/ze/ComboBox_WebView-860042469
2. I was able to make a DisplayAlert in the event giving them the option to cancel or not.  When I do this it doesn't work. 

### Expected Behavior

e.Cancel as true - It's doesn't navigate

### Actual Behavior

e.Cancel as true - It's navigating to the view.

### Basic Information

- Version with issue: 4.8.0.1534
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by PureWeen** [comment]
@RubaShanmugamm this isn't really going to work because the cancel operation isn't async 

Once you await display alert the execution returns to the caller which sees that cancel is set to false. If you wanted this to cancel using an await we'd have to allow for a task on the args or a cancellation token so that it handled async/cancellation

I've updated the title

**Comment by jeyakasipandi** [comment]
Any update on this?

**Comment by Axemasta** [comment]
@jeyakasipandi Unlikely this ever goes into forms, I forked the control and implemented this feature myself. You are free to try & see if it solves your requirements!

https://github.com/Axemasta/SuperWebView

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
