### ISSUE TITLE
[Bug] [iOS] Null Reference Exception in ContextActionsCell using latest xamarin forms

### ISSUE THREAD

**Issue by Ksurendhar2** [xamarin/Xamarin.Forms#13848]
### Description

I am using latest xamarin forms(5.0.0.1931) version. I am getting Null Reference Exception in ContextActionsCell issue occurred in appcenter. How to solve this issue

### Expected Behavior
No crash

### Actual Behavior
Crash with NullReferenceException in

ContextActionsCell.get_ScrollDelegate ()
ContextActionsCell.PrepareForDeselect ()
ListViewRenderer+ListViewDataSource.OnItemSelected (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs eventArg)
(wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes)
ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell)
ListViewRenderer+ListViewDataSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath)
ContextActionsCell+SelectGestureRecognizer.Tapped (UIKit.UIGestureRecognizer recognizer)
UITapGestureRecognizer+Callback.Activated (UIKit.UITapGestureRecognizer sender)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
### Basic Information

- Version with issue: xamarin forms(5.0.0.1931)
- Platform Target Frameworks: Xamarin.Forms IOS

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
