### ISSUE TITLE
[Enhancement] Using Font Awesome for Context.Actions

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13844]
Hi

I can use Font Awesome fine. But I wanted to use font awesome icons instead of text on my context.actions menu items. But I don’t see any way to set the font family??

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
