### ISSUE TITLE
[iOS] NRE in LabelRenderer.OnElementPropertyChanged()

### ISSUE THREAD

**Issue by gata-bah** [xamarin/Xamarin.Forms#1384]
### Description
We have an ObservableCollection which we bind to the ListView.
As soon as we add/remove items from the ObservableCollection and change the items properties, we get a NRE in LabelRenderer.OnElementPropertyChanged().
ListItem Template contains only Labels whose text is bound to the ListItem.

Test project is attached.

### Steps to Reproduce

1. Open the test project
2. Run the project on iOS Simulator (iOS 11.2)

### Expected Behavior
App doesn't crash.

### Actual Behavior
App crashes (NRE).

### Basic Information

- IDE:
  Visual Studio 2017 (Windows 10)

- Platform Target Frameworks: 
   iOS:  11.2
- Affected Devices:
   Simulator, iPhone 8
- Version:
   Xamarin.Forms 2.4.0.280

[OCApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1551990/OCApp.zip)

### Stack Trace

[stack_trace.txt](https://github.com/xamarin/Xamarin.Forms/files/1554708/stack_trace.txt)

**Comment by jassmith** [comment]
Can you attach the stack trace too please?

**Comment by gata-bah** [comment]
Attached the stack trace as txt file

**Comment by MitchBomcanhao** [comment]
This is the same as [https://bugzilla.xamarin.com/show_bug.cgi?id=59813](https://bugzilla.xamarin.com/show_bug.cgi?id=59813).
Has been going on for a while.

**Comment by StephaneDelcroix** [comment]
The issue is indeed present in 2.4.0. I can not reproduce the issue on your sample once updated to 3.0.0. Seems we fixed it already.
