### ISSUE TITLE
[Bug] CarousleView FlowDirection rtl not work where async load Data

### ISSUE THREAD

**Issue by karimi7514** [xamarin/Xamarin.Forms#13856]
### Description
When CarousleView FlowDirection set to RightToLeft and async load data in OnAppearing, CarousleView not work
### Steps to Reproduce

1. use carouselview in xaml page
2. set FlowDirection="RightToLeft" in  CarousleView  and contentpage
3. async load data in OnAppearing
4. try to scroll CarousleView 

### Expected Behavior
scrolls from right to left
### Actual Behavior
Close app
### Basic Information

- Version with issue:
- Last known good version: 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:

**Comment by StephaneDelcroix** [comment]
Thanks for this report.

Could you please attach a small reproduction project ? We need that in order to validate the bug, create tests to avoid regressions in the future, and validate that the issue being reported is actually fixed.

**Comment by karimi7514** [comment]
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/6045004/App1.zip)

**Comment by PureWeen** [comment]
@karimi7514 I'm not sure what platform you're having issues with here. I tested your sample on iOS/Android and it seems like this issue is android only so I'm going to close this one as a duplicate for now

https://github.com/xamarin/Xamarin.Forms/issues/12052

**Comment by karimi7514** [comment]
There is a problem in Android
