### ISSUE TITLE
[Enhancement] Wrong CommandParameter should report an error

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#13867]
## Summary
If you bind to a `Command<T>` and pass a parameter to the command which cannot be assigned to `T`, then the command execution is just ignored. This should throw an `ArgumentException` or at least write an error to the Output window. If the property is a `Command<T>` (and no `ICommand`) then the XAML Compilation could even report a compile error.

E.g.:

	<Button Text="Command of ParameterVM - called with Wrong Type"
	    Command="{Binding CommandOfParameterVMWrongType}">
		<Button.CommandParameter>
			<local:ViewModel />
		</Button.CommandParameter>
	</Button>

Here `CommandOfParameterVMWrongType` is a `Command<ParameterVM>`, but it is called with a `ViewModel`, so it cannot work.

## Intended Use Case

If the developer has an error in XAML and passes the wrong parameter to a command, then this mistake should easier be found. Currently the call is just ignored. If an `Exception` would be thrown or a message printed to the Debug Output, then this would be visible.

## Reproduction

In the attached project I try multiple variants of how to execute a command. The first variants all write a message to the Debug window. The last (after "Not OK") pass a parameter to the command which cannot be assigned to the correct type and these are not executed. I tested it with UWP and Android, but I guess that all platforms will behave the same in this regard.
[Repro.BindToCommands.zip](https://github.com/xamarin/Xamarin.Forms/files/6043145/Repro.BindToCommands.zip)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
