### ISSUE TITLE
[Enhancement] omit portions of xaml from build depending on Debug/Release environement

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#13896]
## Summary
 **The analogy of `#if DEBUG` in xaml.**
Provide a way to conditionally ignore xaml portions during build depending on environment DEBUG/release, I am not talking about the design time, also some may suggest workarounds like binding `Isvisible` for each View to `DEBUG` constant thru a property or just comment-out the code.

A close example in wpf xaml (but not exactly what described in this issue) https://stackoverflow.com/a/19940157. in other words it's like commenting-out these portions during debug/release mode

### Example
```
 <debug:Label Text="Won't be included in the build if on debug" />
```
or maybe 
```
 <Debug>
      <Label Text="Won't be included in the build if on debug" />
 </Debug>

<Ignore  OnBuild="Release">
           <Label Text="Won't be included in the build if on Release" />
</Ignore>

<Ignore  OnBuild="Debug">
           <Label Text="Won't be included in the build if on Debug" />
</Ignore>
```
## Intended Use Case
Be able to omit/ignore some ui stuff depending on build mode.

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
