### ISSUE TITLE
[Bug] Changing bound sub items won't update UI

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#13903]
### Description

Binding sub items like MyProperty.SubProperty won't update UI when value gets changed
Adding and removing items on ObservableCollection won't update UI. Same goes for SecondProperty.Title

I've also tried the same without MultiBinding. Same result. Initial binding works, but updating isn't.
Attribute="{Binding SecondProperty.ObservableCollectionProperty, Converter={StaticResource MyConverter}

### Steps to Reproduce

1. Bind a sub item via xaml
2. Set value
3. Change values -> UI won't be updated // line 47 in example project BindingSubItem

Example project: [BindingSubItem.zip](https://github.com/xamarin/Xamarin.Forms/files/6067122/BindingSubItem.zip) -> go into BindingSubItem.MyMainPage.MainPageViewModel -> method AddCarToGarage -> line 47

### Expected Behavior

UI should be updated in step three of "Steps to Reproduce"

### Actual Behavior

UI doesn't get updated in step three of "Steps to Reproduce"

### Basic Information

- Version with issue: XF 4.8.0.1269 and 5.0.0.2012
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  14.4
  - Android: -

### Screenshots

![Screenshot 2021-03-01 at 12 35 25](https://user-images.githubusercontent.com/61872738/109492016-9d6a5880-7a8a-11eb-8461-c5328ba13f19.png)

### Workaround

It works fine when SecondProperty gets set again (the whole ObservableCollection). Then the UI will be updated. But that wasn't our intention. We wanted to update the UI when adding/removing items to/from ObservableCollectionProperty.

Works:
- SecondProperty.ObservableCollectionProperty = newObservableCollection
Won't work:
- SecondProperty.ObservableCollectionProperty.add(newItem)

**Comment by PureWeen** [comment]
Bindings only update via INotifyPropertyChanged events. If you want the binding to update and fire your converter you have throw a PropertyChanged event. For example if I add this to your code it works

```C#

         public ObservableCollection<Car> Cars
        {
            get => _cars;
            set
            {
                SetProperty(ref _cars, value);
                Cars.CollectionChanged += (_, __) =>
                {
                    OnPropertyChanged("Cars");
                };
            }
        }
```

**Comment by MaxFmi** [comment]
Thanks for your answer **PureWeen**. 
That works in the sample but unfortunately not in our appliacation. I will try to adjust the sample so that it fits the real application scenario.

**Comment by MaxFmi** [comment]
Another workaround could be to add <Binding Path="ObservableCollection.Count" /> to MultiBinding.
