### ISSUE TITLE
Why is my window appearance not displaying correctly when I change the theme with code?

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13911]
I have used this [tutorial](https://www.thewissen.io/going-dark-easily-implementing-dark-mode-in-your-xamarin-forms-app/) as a basis for what I have implemented.

My `AppDelegate` in my **macOS** build has the following **actions** defined:

        [Action("appearanceAuto:")]
        public void appearanceAuto(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Unspecified;
            Preferences.Set("AppTheme", (int)OSAppTheme.Unspecified);
        }

        [Action("appearanceLight:")]
        public void appearanceLight(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Light;
            Preferences.Set("AppTheme", (int)OSAppTheme.Light);
        }

        [Action("appearanceDark:")]
        public void appearanceDark(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Dark;
            Preferences.Set("AppTheme", (int)OSAppTheme.Dark);
        }

These are linked as first responders to my application main menu. When I click one of the menu items the relevant handler is triggers. But it is not working correctly. For example:

![Screenshot 2021-03-02 at 09 05 52](https://user-images.githubusercontent.com/7985331/109624790-82edb900-7b36-11eb-950d-6fd9fc17c502.png)

When triggered, the frames on this window will toggle correctly. I have the frames set up like this in Xaml:

```
BorderColor="{AppThemeBinding Dark=White,
                                          Light=Black}"
```

They all work. But the rest of the window remains in the dark mode colours. I have not specified any specific colours for the rest of the windows content other than setting the background colour of the page itself to transparent.

Why is my window not correctly redrawing in the right theme?

I have also modified all my Preferences calls to use the shared text property to ensure it is reading / writing from the same location in preferences. In my app.xaml.cs file I have:

        public App()
        {
            //var x = System.Globalization.CultureInfo.CurrentUICulture;

            InitializeComponent();

            if(Device.RuntimePlatform == Device.macOS)
            {
                // Set the theme that the user has picked
                Application.Current.UserAppTheme = (OSAppTheme)Preferences.Get("AppTheme", (int)OSAppTheme.Unspecified, "Global");
            }

            MainPage = new Pages.ElderlyInfirmPage();
        }

Again, the frames show correctly but the rest of the window does not render in the requested theme.

If I change the theme using the operating system general preferences then the window will render in that colour.

**Comment by ajtruckle** [comment]
I tried removing the transparency on the page - no difference.

I tried simply setting:

`Application.Current.UserAppTheme = OSAppTheme.Light;`

No difference. Only my frames respect the theme. Not the rest of the window.

Why? I am using latest Xamarin.Forms etc... packages.

**Comment by ajtruckle** [comment]
Update. If I use this code:

        [Action("appearanceAuto:")]
        public void appearanceAuto(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Unspecified;
            Preferences.Set("AppTheme", (int)OSAppTheme.Unspecified, "Global");

            var app = NSAppearance.GetAppearance(NSAppearance.NameAqua);
            window.Appearance = app;
        }

        [Action("appearanceLight:")]
        public void appearanceLight(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Light;
            window.Appearance = NSAppearance.GetAppearance(NSAppearance.NameAqua);
            Preferences.Set("AppTheme", (int)OSAppTheme.Light, "Global");
        }

        [Action("appearanceDark:")]
        public void appearanceDark(NSObject sender)
        {
            Application.Current.UserAppTheme = OSAppTheme.Dark;
            window.Appearance = NSAppearance.GetAppearance(NSAppearance.NameDarkAqua);
            Preferences.Set("AppTheme", (int)OSAppTheme.Dark, "Global");
        }

Then the toggle does work. Using `window.Appearance = NSAppearance.GetAppearance(NSAppearance.NameDarkAqua);` etc was the key.

And if I put this in my AppDelegate constructor (instead of the main app.xaml.cs file:

            var theme = (OSAppTheme)Preferences.Get("AppTheme", (int)OSAppTheme.Unspecified, "Global");
            if(theme == OSAppTheme.Dark)
            {
                window.Appearance = NSAppearance.GetAppearance(NSAppearance.NameDarkAqua);
            }
            else if(theme == OSAppTheme.Light)
            {
                window.Appearance = NSAppearance.GetAppearance(NSAppearance.NameAqua);
            }

It starts correctly with the right theme.

I do not know why the UserAppTheme mechanism is not catering for this out of the box?

Also, it gives me a problem because I now don't know how to either reset the appearance to "default" of system settings.

**Comment by ajtruckle** [comment]
If I set it to `null` then it reverts to system setting.

It doesn't not seem that this UserAppTheme mechanics is correctly setting the window `Appearance` (or - even better - app - appearance to the relevant setting as I have described for macOS.

**Comment by PureWeen** [comment]
@ajtruckle can you attach a repro please?

**Comment by ajtruckle** [comment]
How can I share it? Too large to attach.

**Comment by ajtruckle** [comment]
Try this @PureWeen :

https://www.dropbox.com/s/bn7q6pwr46p7oyr/TestTheme.zip?dl=0

It shows three buttons that should set the appearance and does nothing.

The only way to change the appearance on MacOS project is in the AppDelegate using the approach I mentioned in my initial posting. But, in theory, I should simply be able to do the same as the test project.

**Comment by ajtruckle** [comment]
Were you able to reproduce?

**Comment by rachelkang** [comment]
Hi, @ajtruckle - if you're still experiencing the issue, would you mind sharing the repro again? When I access the link, it tells me the item was deleted :/

**Comment by ajtruckle** [comment]
Hi @rachelkang 

Try the link now.

**Comment by mhrastegary77** [comment]
same issue

**Comment by rachelkang** [comment]
@ajtruckle I'm trying my best to repro your issue right now - where are you setting that appearanceAuto, appearanceLight, appearanceDark app theme code? I'm not seeing it in the sample you shared

**Comment by ajtruckle** [comment]
Hi

Why do t you take a step back?

Create a iOS project and add a macOS build.

Now try to change the appearance using xamarin api and run the Mac build. It will not work.

You have to use the macOS native api in the macOS project to change the appearance.

Surely this kind of concept is straightforward for development?

I am not on my pc right now. The above should help.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ajtruckle** [comment]
Allow me to make something clear here ....

In my original question above I explained how I ended up getting it to work, by using native code in the macOS project. I have not included that code in the sample as it should not be required. That is the whole point. But I have explained how I did it as a means of explanation.

To reiterate, this UseAppTheme should be enough to change the theme on macOS but it does not. If you try it yourself you will see.

The only way to change the theme on a macOS is to ignore UserAppTheme and do it yourself with the appearance Api as described.

Sorry for any confusion.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
