### ISSUE TITLE
[Enhancement] Make ActivityIndicator fullscreen for appshell

### ISSUE THREAD

**Issue by leandrofagundes** [xamarin/Xamarin.Forms#13924]
## Summary
When using activity indicator on a ShellApp project, the NavBar stills unblocked and the user can navigate back or navigate through menu even when app is busy.

## API Changes

In order to allow the activity indicator to cover full screen, even the nav bar, a template can be add to the appshell.xaml configuration for when the application is busy.

## Intended Use Case

Every time we need a loading on the screen, we can  just call Shell.IsBusy or something like that and the template will be activated.

**Comment by PureWeen** [comment]
@leandrofagundes what do you think about this approach?

https://github.com/xamarin/Xamarin.Forms/pull/8551

**Comment by leandrofagundes** [comment]
Thanks @PureWeen, it really works. I just think it could be a template on appshell.xaml.
