### ISSUE TITLE
Hi ,[I am working on the SwipeView in ListView, SwipeView is very Sensitive while scrolling. Can you please suggest me how to disable swipe while scrolling List and to Disable List Scroll while swiping Left or Right..  ] 

### ISSUE THREAD

**Issue by emilon** [xamarin/Xamarin.Forms#13923]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jsuarezruiz** [comment]
Could you share more information?, what Xamarin.Forms version are you using?, on what platform do you want this behavior?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
