### ISSUE TITLE
tap gesture command and swipe action buttons in collection view are buggy

### ISSUE THREAD

**Issue by krmWorkAccnt** [xamarin/Xamarin.Forms#13931]
### Description
Inside a collection view data template the swipe action buttons & tap gesture command on the item are incredibly buggy -- you may need to tap the item multiple times before the tap gesture recognizes the event, likewise pressing the swipe action button often just closes the swipe panel without invoking the button command.

I don't have time to build a test project as currently i seem to be spending more time building test projects to list bugs on here than i'm spending on our project.

### Steps to Reproduce

1. Build a simple project with a collection view, inside the collection view have a label with a tap gesture command "this is a lot more basic that what we have" -- also include a swipe action button with a simple command to navigate to pop up a dialog.
2.  TEST this on an actual device opposed to the emulator....
3. 

### Expected Behavior
That the tap gesture and swipe action buttons are responsive
### Actual Behavior
They're not -- it's really buggy
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by PureWeen** [comment]
@krmWorkAccnt can you please attach a reproduction?

**Comment by krmWorkAccnt** [comment]
Issue closed
