### ISSUE TITLE
[Bug] Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown

### ISSUE THREAD

**Issue by yusuf-setiawan** [xamarin/Xamarin.Forms#13932]
### Description
Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
java.lang.Error: Java callstack:
crc643f46942d9dd1fff9.PageRenderer.n_onDetachedFromWindow(Native Method)
crc643f46942d9dd1fff9.PageRenderer.onDetachedFromWindow(Unknown Source:0)
android.view.View.dispatchDetachedFromWindow View.java:19802
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3858
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3850
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3850
android.view.ViewGroup.dispatchDetachedFromWindow ViewGroup.java:3850
android.view.ViewGroup.removeViewInternal ViewGroup.java:5481
android.view.ViewGroup.removeViewInternal ViewGroup.java:5452
android.view.ViewGroup.removeView ViewGroup.java:5383
crc643f46942d9dd1fff9.FormsAppCompatActivity.n_onDestroy(Native Method)
crc643f46942d9dd1fff9.FormsAppCompatActivity.onDestroy(Unknown Source:0)
android.app.Activity.performDestroy Activity.java:8114
android.app.Instrumentation.callActivityOnDestroy Instrumentation.java:1388
android.app.ActivityThread.performDestroyActivity ActivityThread.java:5201
android.app.ActivityThread.handleDestroyActivity ActivityThread.java:5245
android.app.servertransaction.DestroyActivityItem.execute DestroyActivityItem.java:44
android.app.servertransaction.TransactionExecutor.executeLifecycleState TransactionExecutor.java:176
android.app.servertransaction.TransactionExecutor.execute TransactionExecutor.java:97
android.app.ActivityThread$H.handleMessage ActivityThread.java:2230
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:230
android.app.ActivityThread.main ActivityThread.java:7752
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:526
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1034

TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType)

TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType)
Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type)
Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
View.n_OnDetachedFromWindow (System.IntPtr jnienv, System.IntPtr native__this)
### Steps to Reproduce

1.  Open apps
2.  the app startup with blank screen (gray screen)

### Basic Information

- Version with issue:
- Android: Android 10
- Affected Devices: vivo NEX S

### Environment
Xamarin Forms : 4.8.0.1821

Microsoft Visual Studio Community 2019
Version 16.8.6
VisualStudio.16.Release/16.8.6+31019.35
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Xamarin   16.8.000.262 (d16-8@4d60f9c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.26 (d16-8/a36ce73)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.10.0.4 (5a05865f6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Screenshots

<!-- If the issue is a visual issue, please include screenshots showing the problem if possible -->
![image](https://user-images.githubusercontent.com/59720637/109908272-8c158c00-7cd6-11eb-8853-e9acafea2eec.png)

**Comment by PureWeen** [comment]
@yusuf-setiawan can you attach a small reproduction of your issue please?

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
