### ISSUE TITLE
[Bug] Entry Background doesn't work to set color

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#13930]
### Description

This doesn't work on UWP or Android, and probably also doesn't work on iOS.

```
<Entry Placeholder="Placeholder" 
                       Background="Purple" />
```

### Expected Behavior

The color of the `Entry` background changes.

### Actual Behavior

Nothing.

### Basic Information

- Version with issue: 5.0.0.2012

### Screenshots

![image](https://user-images.githubusercontent.com/41873/109876844-e0b5fa00-7c37-11eb-96ce-4f782eacf67d.png)

![image](https://user-images.githubusercontent.com/41873/109877046-2672c280-7c38-11eb-855f-f87178252147.png)

### Workaround

Use `BackgroundColor` instead.

![image](https://user-images.githubusercontent.com/41873/109876934-004d2280-7c38-11eb-873d-319decfa0ff4.png)

![image](https://user-images.githubusercontent.com/41873/109877007-1a870080-7c38-11eb-9f1e-e913e2910b72.png)

### Reproduction

[ControlGallery.zip](https://github.com/xamarin/Xamarin.Forms/files/6095742/ControlGallery.zip)

**Comment by jsuarezruiz** [comment]
Do you have a repository with the example?. Have done a quick tests in 5.0 branch and cannot reproduce:
<img width="397" alt="Captura de pantalla 2021-03-04 a las 14 19 59" src="https://user-images.githubusercontent.com/6755973/109970479-677cdc80-7cf5-11eb-9b1e-bf37d4d2c8ae.png">
<img width="486" alt="Captura de pantalla 2021-03-04 a las 14 15 44" src="https://user-images.githubusercontent.com/6755973/109970489-68ae0980-7cf5-11eb-84df-656a6f394913.png">

**Comment by Codelisk** [comment]
Happens for me only with Visual Material Entrys

**Comment by davidortinau** [comment]
@jsuarezruiz I've added my sample zip to the original post. I've been noticing `Background` doesn't seem to work on UWP in other places.
