### ISSUE TITLE
Colour of Entry placeholder text in light theme

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13935]
Not sure where to put this question.

I use no custom styles for drawing. It is all system rendered on my macOS.

Take this `Entry` element:

    <Entry
            x:Name="SelectedElderEntry"
            FontSize="Small"
            HorizontalOptions="FillAndExpand"
             IsReadOnly="True"
             Placeholder="Enter name"
             VerticalTextAlignment="Center" />

Initially there is no text in the element and it is read only.

In dark mode you see the placeholder text:

<img width="511" alt="Screenshot 2021-03-04 at 13 11 48" src="https://user-images.githubusercontent.com/7985331/109969341-b0c82e80-7ceb-11eb-8670-dd854ee89a25.png">

But in light mode:

<img width="502" alt="Screenshot 2021-03-04 at 13 12 01" src="https://user-images.githubusercontent.com/7985331/109969371-ba519680-7ceb-11eb-84f4-b721a861128c.png">

You can't see the text. Why is this? I would expect the placeholder text to be visible whatever the theme.

**Comment by ajtruckle** [comment]
Will this be fixable?

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
