### ISSUE TITLE
[Bug] MTOUCH: Error MT2101: Can't resolve the reference 'System.Void System.Security.Cryptography.DSACng::.ctor(System.Security.Cryptography.CngKey)'

### ISSUE THREAD

**Issue by JasonixDev** [xamarin/Xamarin.Forms#13942]
MTOUCH: Error MT2101: Can't resolve the reference 'System.Void System.Security.Cryptography.DSACng::.ctor(System.Security.Cryptography.CngKey)', referenced from the method 'T Internal.Cryptography.Pal.Windows.PkcsPalWindows::GetPrivateKey(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Boolean,System.Boolean)' in 'System.Security.Cryptography.Cng, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. (MT2101)

**Comment by PureWeen** [comment]
@JasonixDev can you attach a reproduction of your issue please? 

It sounds like you might have different versions of a nuget package added to different projects or you need to tweak the linker settings on iOS

https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=windows

**Comment by JasonixDev** [comment]
Today i updated my Visual Studio for Mac of the latest version. And now i get this errow when i want build the app of a device. Simulator works fine. Yesterday I had no problems. I change nothing, only VS update.

**Comment by joduss** [comment]
I have the same problem. It was compiling fine, then I updated Visual Studio mac, which updated Xamarin.iOS. Now I cannot compile any more.
It is no an issue specific to Xamarin.Forms, since I'm not using Xamarin.Forms.

**Comment by JasonixDev** [comment]
Same problem with the latest Visual Studio Update 8.9.1 (build 34)

**Comment by JasonixDev** [comment]
Found the problem, VS has compile an assembly that come with a nuget sdk.

**Comment by kennepal** [comment]
Hello JaxonixDev.
I suddenly have this exact same problem.
I do not see where you posted the exact fix for this ???
What setting did you change in VS?

**Comment by JasonixDev** [comment]
You need to check the NuGet-Packages in your project, sometimes a package can have an sub-assembly. Select a package in your solution-explorer and expand it, like this:
![image](https://user-images.githubusercontent.com/52561832/113825387-2eff7100-9781-11eb-8f73-272ff5fd15f9.png)
