### ISSUE TITLE
Using Right To Left with ListView

### ISSUE THREAD

**Issue by ajtruckle** [xamarin/Xamarin.Forms#13955]
I set the culture in the `App` class:

            CultureInfo arabicCulture = new CultureInfo("ar-LB");
            CultureInfo.DefaultThreadCurrentCulture = arabicCulture;
            CultureInfo.DefaultThreadCurrentUICulture = arabicCulture;

And I add the `FlowDirection` property to the `ContentPage`:

Here is an example ListView on my window:

                <ListView
                    x:Name="ListElders"
                    HasUnevenRows="True"
                    HorizontalOptions="StartAndExpand"
                    ItemSelected="ListElders_ItemSelected"
                    ItemsSource="{Binding EldersCollection}"
                    SelectedItem="{Binding SelectedElder, Mode=TwoWay}">
                    <ListView.ItemTemplate>
                        <DataTemplate x:DataType="x:String">
                            <ViewCell>
                                <StackLayout Padding="2">

                                    <Label
                                        FontSize="Small"
                                        HorizontalOptions="StartAndExpand"
                                        Text="{Binding .}"
                                        VerticalTextAlignment="Center">
                                        <Label.Padding>
                                            <OnPlatform x:TypeArguments="Thickness">
                                                <On Platform="iOS" Value="0,5,0,4" />
                                            </OnPlatform>
                                        </Label.Padding>
                                    </Label>
                                    <StackLayout.GestureRecognizers>
                                        <TapGestureRecognizer NumberOfTapsRequired="1" Tapped="TapGestureRecognizer_ElderList_Single" />
                                    </StackLayout.GestureRecognizers>
                                </StackLayout>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>

I am primarily using macOS as the target platform at the moment. The results:

<img width="418" alt="Screenshot 2021-03-07 at 21 32 58" src="https://user-images.githubusercontent.com/7985331/110255651-b6906f00-7f8c-11eb-9180-21e7c29aac7d.png">

My screen grab shows two lists because I have two in the window but the second one is just the same with different binding. As you can see the contents of the list view is going off screen on the right edge.

If I comment out all the culture code / flow direct so that it stays in English and start it again:

<img width="407" alt="Screenshot 2021-03-07 at 21 36 20" src="https://user-images.githubusercontent.com/7985331/110255743-2d2d6c80-7f8d-11eb-8350-f29a8fc032a9.png">

What step am I missing to make the items render correctly when the flow direction is right to left?

**Comment by ajtruckle** [comment]
In fact, I find that other controls on the widow still show left to right even though they are automatically set to MatchParent by the system for the flow. For example, placeholder text is showing on the left.

**Comment by ajtruckle** [comment]
I also saw [this](https://www.gitmemory.com/issue/xamarin/Xamarin.Forms/9684/618455819). No resolution.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
