### ISSUE TITLE
[Bug] XF requires .NETFramework >= v4.6.1. You have 'v4.5.1'	

### ISSUE THREAD

**Issue by jfjalburquerque** [xamarin/Xamarin.Forms#13957]
### Description
After update Visual Studio 2019 to version 16.9.0 I cannot build my application.

It appears next error:
`XF004	XF requires .NETFramework >= v4.6.1. You have 'v4.5.1'`

I have tried to solve the issue doing:
- I have followed the steps in: https://forums.xamarin.com/discussion/131914/error-xf-requires-netframework-v4-7-you-have-v4-6-1  but it doesn't work for me. 
- I have reload the project
- I have cleaned NuGets packages and reload again.
- Deleting bin and obj folders from the project

### Steps to Reproduce

1. Update Visual Studio 2019 to v.16.9.0
2. Try to build the application in Xamarin Forms

### Expected Behavior
Build as expected

### Actual Behavior
Error: XF004	XF requires .NETFramework >= v4.6.1. You have 'v4.5.1'

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: Same version was working good in Visual Studio 2019 v16.8.6
- Platform Target Frameworks: 
  - UWP:  max 18362 - min 17763

### Environment
```
Microsoft Visual Studio Community 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA592
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.687.37626
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.687.37626
Azure Functions and Web Jobs Tools

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

### Build Logs
```
Error	XF004	XF requires .NETFramework >= v4.6.1. You have 'v4.5.1'	
```

### Screenshots

Tools installed in my VisualStudio
![imagen](https://user-images.githubusercontent.com/5212042/110303497-bcbd3480-7ffa-11eb-9d96-dd7f3d9052de.png)

**Comment by MrWolfPST** [comment]
VS 16.9.1 don't resolve the issue

**Comment by carbonete** [comment]
I Have this issue when try to publish my UWP project using Windows Application Packaging Project. 
UWP project build normally.

It's urgent i can't generate installer for my app.

thanks

**Comment by carbonete** [comment]
Complementing I try 16.9.1 and have the same problem.

**Comment by EmanterolaDN** [comment]
same issue over here...

**Comment by juanmalm** [comment]
Any update/workaround on this? Our builds are broken...

**Comment by jfjalburquerque** [comment]
As @carbonete said, 16.9.1 doesn't fix the problem, I cannot debug my app because of this

**Comment by MrWolfPST** [comment]
I solved my issue adding at my .wapproj file this:
<PropertyGroup>
    <XFDisableFrameworkVersionValidation>True</XFDisableFrameworkVersionValidation>
  </PropertyGroup>

**Comment by juanmalm** [comment]
@MrWolfPST  it works, but I think it is only a workaround for the real issue. You are only muting the validation.

**Comment by jfjalburquerque** [comment]
@MrWolfPST this workaround works for me. Thanks to share it. 
Almost I can run my app, I will use it while we don't found a fix for it.

**Comment by carbonete** [comment]
Update to VS 2019 to 16.9.2 resolve this issue for me.

**Comment by juanmalm** [comment]
In my case it still failing with 16.9.2

**Comment by jfjalburquerque** [comment]
I continue having the issue after update to 16.9.2

**Comment by jsuarezruiz** [comment]
@Redth Can we escalate this issue and move on the VS team?

**Comment by jsuarezruiz** [comment]
We have some logs from Azure DevOps.

**Comment by jfjalburquerque** [comment]
> 
> 
> Anyone having this issue can you try to install the following devpack
> 
> https://go.microsoft.com/fwlink/?linkid=2099470
> 
> see if that resolves the issue for you?

This one doesn't resolve the issue

**Comment by Redth** [comment]
I think the part we were missing is that this is happening in the .wapproj specifically.  @MrWolfPST thank you for posting your workaround, everyone should consider using this inside their .wapproj for now.

We will update our targets so the validation check does not run inside the context of the .wapproj in a future service release.

**Comment by scearces** [comment]
@MrWolfPST works for me, at least so far. The problem occurred for me using Visual Studio Version 16.9.3 as soon as I added a packaging project and tried to rebuild.

**Comment by digitalnelson** [comment]
The workaround doesn't work for me.  My packaging project builds and runs but then throws a runtime assembly version exception. This packaging project is working fine in 16.9 but not after upgrading to 16.10.  It is also broken in 16.11.

Could not load file or assembly 'System.ObjectModel, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by digitalnelson** [comment]
Disregard, this is a dll hell issue in the packaging project introduced by the vs upgrade.  The validation change is working and allowing the unrelated issue to show.

**Comment by Eebowski** [comment]
Same problem as @digitalnelson. 
Since Version 16.10 I need the workaround to create the package. But if I try to install the package the app crashs at start.

The errorlog shows:
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.19041.1081, Zeitstempel: 0xde3fc775
Ausnahmecode: 0xc000027b

With 16.9.x is all okay.
The UWP standalone without MSIX-Installer works fine.
