### ISSUE TITLE
Xamarin.Forms Grid Measure and Layout bug

### ISSUE THREAD

**Issue by slakul** [xamarin/Xamarin.Forms#1395]
### Description

I attached a simple xaml to reproduce the problem and screenshots. There are four labels "Begin t0 t1 t2 t3 t4 t5 t6 t7 t8 t9 end" which I am not able to show in the correct way without clipping.

### Basic Information

- Version with issue: 2.5.0.121934
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP:  16299

### Screenshots

During windows resize

- ![b1](https://user-images.githubusercontent.com/14055723/33965950-17b5f948-e05e-11e7-9003-660d2c948e86.PNG)

- ![b2](https://user-images.githubusercontent.com/14055723/33965978-1fa20d68-e05e-11e7-8293-a9973f7ab0da.PNG)

- ![b3](https://user-images.githubusercontent.com/14055723/33965979-1fba3adc-e05e-11e7-93b4-648cf4e40474.PNG)

When I removed the row with Height="*" from the main grid

- ![bx1](https://user-images.githubusercontent.com/14055723/33965976-1f71a63c-e05e-11e7-8d5a-d6942275eda5.PNG)

### Reproduction Link

[TestPage2.zip](https://github.com/xamarin/Xamarin.Forms/files/1557359/TestPage2.zip)

**Comment by BradChase2011** [comment]
Ill drop this here https://bugzilla.xamarin.com/show_bug.cgi?id=53561 .  My recommendation is a rewrite on the GridCalc.  There are quite a bit of problems that stem even farther down the chain that just the grid.

**Comment by samhouts** [comment]
Duplicate of #1343
