### ISSUE TITLE
[Bug] XAML resource keys cannot be extracted into string constants

### ISSUE THREAD

**Issue by radioactiveman** [xamarin/Xamarin.Forms#13963]
### Description
XAML keys for resources cannot be extracted into string constants. The same approach works however for example when specifying command parameters.

### Steps to Reproduce

1. Define a const string as resource key
2. Use it in a resource dictionary

```c#
public static class Constants
{
    public const string RedColor = "RedColor";
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Application>
  xmlns:i="... {namespace} ..."
  <Application.Resources>
    <ResourceDictionary>
      <Color x:Key="{x:Static i:Constants.RedColor}">#FF0000</Color>
    </ResourceDictionary>
  </Application.Resources>
</Application>
```

### Expected Behavior
Code compiles and colors are correctly applied.

### Actual Behavior
Code does not compile. And if XAML compilation is disabled, the colors are not applied.

Reported error messages:
XF 5.0: x:Key expects a string literal.
XF 4.8: NullReferenceException

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: -

### Environment
Visual Studio 2019 16.8.6

**Comment by radioactiveman** [comment]
@StephaneDelcroix: Is this expected to work?

**Comment by AmrAlSayed0** [comment]
@radioactiveman I think x:Key is a compile-time property (like x:Name mapped to fields when applied to views) and it is not expected to resolve a MarkupExtension, but still Stephane knows XAML better, I might be wrong.

**Comment by jsuarezruiz** [comment]
`x:Key` require a string literal, just like `x:Name`

**Comment by jfversluis** [comment]
Not sure what is left to do with this one. If you think there is still room for improvement here, please open something on the .NET MAUI repo so we can see what we can do there. Thanks!

**Comment by nogov** [comment]
I find this question still relevant.

From [this old WPF doc](https://learn.microsoft.com/en-us/dotnet/desktop/xaml-services/xkey-directive#xaml-attribute-usage) it should be possible to use markup extensions like the following:

```xaml
<object x:Key="stringKeyValue".../>
-or-  
<object x:Key="{markupExtensionUsage}".../>
```

And there's a good old example on StackOverflow of using it [here](https://stackoverflow.com/a/11016029/21724612).
