### ISSUE TITLE
[Bug] Can't set WidthRequest for Flyout in FlyoutPage on MacOS

### ISSUE THREAD

**Issue by vadd98** [xamarin/Xamarin.Forms#13976]
I'm using Xamarin Forms for MacOS and I'm working on a FlyoutPage. I want to set the Flyout Width to 150, but it remains fixed to 240.

### Steps to Reproduce

1. Create a FlyoutPage
2. Set a WidthRequest on the Flyout

### Expected Behavior

Flyout has to be resizable

### Actual Behavior

Flyout is not resizable.

### Basic Information

- Version with issue: Xamarin.Forms.5.0.0.2012
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: MacBook Pro i9 2019

### Environment

JetBrains Rider 2020.3

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by SagarPanwala** [comment]
I can see Shell has exact functionality, but I also want to use FlyoutPage because Shell is not providing a way to use Page in a Flyout. It's very useful in case of Tablet Split Mode.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
