### ISSUE TITLE
[Bug] ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView API on Xamarin Forms 5.

### ISSUE THREAD

**Issue by rdelangelhmx** [xamarin/Xamarin.Forms#13977]
### Description
I have an application with Xamarin Forms 4.8
I converted it to 5.0.0.2012, I don't have any access to the WebView,
however Apple rejects the application

Mobile App
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
... more settings ...
  </PropertyGroup>

 <ItemGroup>
    <PackageReference Include="Autofac" Version="6.1.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Autofac.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Plugin.AzurePushNotification" Version="2.1.3" />
    <PackageReference Include="Sharpnado.Shadows" Version="1.2.0" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.2" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />  
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />  
    <PackageReference Include="Xamarin.Forms.Extended.InfiniteScrolling" Version="1.0.0-preview2" />  
    <PackageReference Include="Xamarin.Forms.Maps" Version="5.0.0.2012" />  
    <PackageReference Include="Xamarin.Forms.PancakeView" Version="2.3.0.759" />  
    <PackageReference Include="XF.Material" Version="1.7.7" />
  </ItemGroup>

Mobile iOS

    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>

  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="Xamarin.iOS" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac">
      <Version>6.1.0</Version>
    </PackageReference>
    <PackageReference Include="Autofac.Extensions.DependencyInjection">
      <Version>7.1.0</Version>
    </PackageReference>
    <PackageReference Include="HockeySDK.Xamarin">
      <Version>5.2.0</Version>
    </PackageReference>
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection">
      <Version>9.0.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Azure.NotificationHubs">
      <Version>4.1.0</Version>
    </PackageReference>
    <PackageReference Include="Plugin.AzurePushNotification">
      <Version>2.1.3</Version>
    </PackageReference>
    <PackageReference Include="Sharpnado.Shadows">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Xamarin.Forms.Extended.InfiniteScrolling">
      <Version>1.0.0-preview2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms.Maps">
      <Version>5.0.0.2012</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms.PancakeView">
      <Version>2.3.0.759</Version>
    </PackageReference>
    <PackageReference Include="XF.Material">
      <Version>1.7.7</Version>
    </PackageReference>
  </ItemGroup>

Xamarin.iOS 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Xamarin.iOS.dll
v4.0.30319

![image](https://user-images.githubusercontent.com/7826501/110559534-00529400-810a-11eb-92b4-e2c0b9386a77.png)

**Windows**
Microsoft Visual Studio Enterprise 2019
Version 16.9.0
VisualStudio.16.Release/16.9.0+31025.194
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00433-90000-00004-AA996
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2019   00433-90000-00004-AA996
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.687.37626
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.687.37626
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.687.37626
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.687.37626
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Clear MEF Component Cache   1.4
Clears the Visual Studio MEF component cache to fix issues with cache corruption.

Code Converter   1.0
Code Converter Extension Details

Command Explorer   1.0.9999
Provides a tool window to explorer all commands, groups and menus to help extension authors place commands/buttons in the desired location

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.21026.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

DeployToGae Extension   1.0
DeployToGae Visual Studio Extension Detailed Info

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

EZ-GIT   1.9.2

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

File Icons   2.7
Adds icons for files that are not recognized by Solution Explorer

Image Optimizer   4.0.132
Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

KnownMonikers Explorer   1.1.28
A tool window for Visual Studio extension authors to explore the KnownMonikers image collection

Linux Core Dump Debugging   1.0.9.31019
Enables debugging of Linux core dumps.

Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NpgsqlVSPackage Extension   1.0
NpgsqlVSPackage Visual Studio Extension Detailed Info

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.30502.00
Microsoft Office Developer Tools for Visual Studio

Open in Visual Studio Code   1.4.46
Adds a menu command that lets you open any solution, project, folder and file in Visual Studio Code.

Project   1.0
Information about my package

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21026.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.9.21026.1
Conda support for Python projects.

Python - Django support   16.9.21026.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.9.21026.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.9.21026.1
Profiling support for Python projects.

ReviewsToolWindow Extension   1.0
ReviewsToolWindow Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SonarLint for Visual Studio   4.33.0.28535
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Analysis Services   15.0.19445.0
Microsoft SQL Server Analysis Services Designer 
Version 15.0.19445.0

SQL Server Data Tools   16.0.62102.01130
Microsoft SQL Server Data Tools

SQL Server Reporting Services   15.0.19124.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19124.0

SsmsVsIntegration   1.0
Information about my package

Syncfusion ASP.NET Core Project Templates   18.4.0.39
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.

Syncfusion EJ2 Web Conversion and Migration   13.4.0.53
Converts and migrates a web project into a Syncfusion web project.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.31025.194
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Cross Platform Mobile Development (iOS)   16.0.31004.209
Visual C++ for Cross Platform Mobile Development (iOS)

Visual C++ for Linux Development   1.0.9.31019
Visual C++ for Linux Development

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WakaTime   1.0

Windows Template Studio   3.9.20351.2
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.9.000.271 (d16-9@863670b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.0.21 (d16-9/93eab59)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@d6d86b2
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@9d8924d

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**MAC**
Visual Studio Community 2019 for Mac
Version 8.9 (build 1651)
Installation UUID: 451008c9-738d-47eb-80da-fe44db88ed22
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000122

Mono Framework MDK
Runtime:
	Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
	Package version: 612000122

Roslyn (Language Service)
3.9.0-5.21112.8+f3ff04378c972d435826e6181de364b3c0db8d14

NuGet
Versión: 5.8.0.6860

SDK de .NET Core
SDK: /usr/local/share/dotnet/sdk/5.0.103/Sdks
Versiones del SDK:
	5.0.103
	5.0.102
	5.0.101
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.100
SDK de MSBuild: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Versiones de tiempo de ejecución:
	5.0.3
	5.0.2
	5.0.1
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.0
	2.1.23
	2.1.22
	2.1.21

.NET Core 3.1 SDK
SDK: 3.1.406

Xamarin.Profiler
Versión: 1.6.15.68
Ubicación: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Versión: 11

Xamarin Designer
Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

Xamarin.Android
Versión: 11.2.0.0 (Visual Studio Community)
"Commit": xamarin-android/d16-9/f908d16
Android SDK: /Users/isainovelo/Library/Developer/Xamarin/android-sdk-macosx
	Versiones de Android admitidas:
		Ninguna instalada

Versión de SDK Tools: 26.1.1
Versión de las herramientas de plataforma del SDK: 30.0.4
Versión de las herramientas de compilación del SDK: 29.0.2

Información de compilación: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@1d382be
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.32.2@cfe06e0
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ad80a42

Microsoft OpenJDK for Mobile
Java SDK: /Users/isainovelo/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
El código EPL de Android Designer está disponible EPL:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

Android Device Manager
Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

Apple Developer Tools
Xcode 12.4 (17801)
Build 12D4e

Xamarin.Mac
Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

Xamarin.iOS
Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

Build Information
Release ID: 809001651
Git revision: c05b1dec4362b5956d47624a437e900ffdc9aa0a
Build date: 2021-02-25 11:27:51-05
Build branch: release-8.9
Xamarin extensions: c05b1dec4362b5956d47624a437e900ffdc9aa0a

Operating System
Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Nov 10 00:10:30 PST 2020
    root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**Comment by AndreasReitberger** [comment]
@rdelangelhmx 
try this fix:
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

**Comment by rdelangelhmx** [comment]
@AndreasReitberger  I made the changes you suggest in the link
however Apple continues to reject the application
![image](https://user-images.githubusercontent.com/7826501/110667822-40f4f080-8190-11eb-8754-f7dd69eb9cd4.png)
![image](https://user-images.githubusercontent.com/7826501/110667904-58cc7480-8190-11eb-9365-df1ee6632f0b.png)

**Comment by rdelangelhmx** [comment]
I even did two runs with the "grep" to identify the "WebView" and the "UIWebView"
These are the results:
![image](https://user-images.githubusercontent.com/7826501/110830179-897adf80-825e-11eb-8477-e07e2f9fa1ea.png)
![image](https://user-images.githubusercontent.com/7826501/110830241-9f88a000-825e-11eb-8136-89caadd0b24f.png)

**Comment by rdelangelhmx** [comment]
I remove the HockeyApp SDK from my application and the problem has been resolved.
