### ISSUE TITLE
Accessibility for Entry/Editor changes in android

### ISSUE THREAD

**Issue by jaisont07** [xamarin/Xamarin.Forms#13979]
## Summary
Accessibility for entry and editor change in android

e.g.

Accessibility for entry and editor replaces the automationproperties.name / helptext and reads only the entered value once it is entered in Android. In iOS it reads out the automationproperties.name along with the entered value. It would be great to have this feature in android as well. 

    <Entry AutomationProperties.Name="Please input your required value here"
                         Text="{Binding xyz}"   Keyboard="Numeric" />
## Intended Use Case
Provide a detailed explanation of the entered value

**Comment by johnshardman** [comment]
Android does read the AutomationProperties.Name as well as the value (I've just tested it on an Editor to double-check). I suspect that the Verbosity settings in the Talkback settings on your Android device need adjusting if you are using a recent version of Android. Older versions of Android may behave differently.

Note also that AutomationProperties.Name isn't really intended for giving prompts such as "Please input your required value here". Having said that, the Xamarin documentation at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties is misleading in some respects, and the documentation at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties#automationpropertiesname does not demonstrate best practice.

**Comment by jaisont07** [comment]
Yeah.. sorry for that. I have got the expected result in newer version of Android. 
The error I got was in Android 7.
