### ISSUE TITLE
[BUG] [iOS] CollectionView shows blank content

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Forms#13996]
I have a CollectionView that looks like this:

``` xml
        <CollectionView ItemsSource="{Binding Categories}"
                        BackgroundColor="Yellow">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding Name}" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
```

The CollectionView shows blank, not content at all.
To double check, I am also loading `Categories` in a `BindableLayout` and it displays correctly (read below).

```xml
        <StackLayout BindableLayout.ItemsSource="{Binding Categories}"
                     BackgroundColor="Green">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding Name}" />
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>
```

### Here's a sample:
https://github.com/stesvis/CollectionViewSample

#### Steps
There is a catch tho. If you run the app, initially both the CollectionView and the BindableLayout show blank.
But if you have Hot Reload enabled, here's a trick:

 1. Run the app. You see blank content
 2. Change ScrollView with Grid (wait for Hot Reload to apply)
 3. Change Grid back to ScrollView (wait for Hot Reload to apply)
 4. The Bindable layout shows the items correctly

```xml
    <Grid HorizontalOptions="FillAndExpand"
          VerticalOptions="FillAndExpand">
        <Grid.RowDefinitions>
            <RowDefinition Height=".5*" />
            <RowDefinition Height=".5*" />
        </Grid.RowDefinitions>

        <CollectionView ItemsSource="{Binding Categories}"
                        BackgroundColor="LightSlateGray"
                        Grid.Row="0">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding Name}" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>

        <ScrollView HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand"
                    Grid.Row="1">
            <StackLayout HorizontalOptions="FillAndExpand"
                         BindableLayout.ItemsSource="{Binding Categories}"
                         BackgroundColor="LightGray">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <Label Text="{Binding Name}" />
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </StackLayout>
        </ScrollView>
    </Grid>
```

It happens in my app, and in this minimal sample at first try.
Please try it and let me know what you think.

**Xamarin Forms** v5.0.0.2012

Thanks

**Comment by PureWeen** [comment]
@stesvis I wonder if your weaver is hooked up right

I wasn't getting anything and then just changed Categories to this and then it showed up for me fine

```C#
        public ObservableCollection<CategoryDTO> Categories
        {
            get => categories;
            set
            {
                categories = value;
                OnPropertyChanged(new PropertyChangedEventArgs(nameof(Categories)));
            }
        }
        ```

**Comment by stesvis** [comment]
> @stesvis I wonder if your weaver is hooked up right
> 
> I wasn't getting anything and then just changed Categories to this and then it showed up for me fine
> 
> ```cs
>         public ObservableCollection<CategoryDTO> Categories
>         {
>             get => categories;
>             set
>             {
>                 categories = value;
>                 OnPropertyChanged(new PropertyChangedEventArgs(nameof(Categories)));
>             }
>         }
> ```

Yes I use **ReactiveUI** for that, so my object looks like this (explanation [here](https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code)):
```cs
[Reactive] public ObservableCollection<CategoryDTO> Categories {get; set; }
```

I think that for now the solution is to do this:
```cs
Categories.AddRange(categoryDTOs);
```
instead of this (which work in Android just fine):
```cs
Categories = new ObservableCollection<CategoryDTO>(categoryDTOs)
```

Somehow in iOS if you initialize your collection from a list it does not update the UI, but it does it if you create the collection first and add the items on a separate step.

**Comment by rmarinho** [comment]
Hi @stesvis yes seems the solution is to use:

```
Categories.AddRange(categorieDTOs);
```

or 

```
Categories = new ObservableCollection<CategoryDTO>(categorieDTOs);
RaisePropertyChanged(nameof(Categories));
```

Btw I tried on Android and it also didn't worked when setting a new ObservableCollection, I think is because Reactive attribute  is not calling PropertyChanged so the UI is updated.
