### ISSUE TITLE
[Bug] Shell GoBack many times

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#13993]
When I navigate to two pages and press the back button many times, the application does a strange thing.

I have created a Tab Shell project and the only modification I have made is this, so that it navigates twice:

 // This will push the ItemDetailPage onto the navigation stack
```
             await Shell.Current.GoToAsync ($ "{nameof (ItemDetailPage)}? {nameof (ItemDetailViewModel.ItemId)} = {item.Id}");
             await Shell.Current.GoToAsync ($ "{nameof (ItemDetailPage)}? {nameof (ItemDetailViewModel.ItemId)} = {item.Id}");
```

In the video I press the back button normally and everything is fine, but the second time I do it fast and this is the result.

https://user-images.githubusercontent.com/11645585/110800235-47f92d00-827c-11eb-8508-5144c7caafb8.mp4

Tested on android 9

**Comment by jsuarezruiz** [comment]
@angelru What Xamarin.Forms version are you using?

**Comment by angelru** [comment]
@jsuarezruiz  the latest version
