### ISSUE TITLE
[Bug] error : Internal compiler error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PaulAnderson02** [xamarin/Xamarin.Forms#13998]
### Description
Getting the below error when running the Xamarin.Forms UWP application in release mode.

C:\Users\xxx\.nuget\packages\microsoft.net.native.compiler\2.0.6\tools\Microsoft.NetNative.targets(731,5): error : Internal compiler error: Object reference not set to an instance of an object.

### Basic Information

- Version with issue: Visual Studio 2019 16.8 [msbuild version '16.8.3.61104']
  - UWP:  <TargetPlatformVersion>10.0.17763.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

- NuGet Packages: Xamarin.Forms 4.6 and tried with latest stable versions
- Affected Devices:

**Comment by jsuarezruiz** [comment]
@PaulAnderson02 Do you have more detailed logs or could you attach a sample where reproduce the issue?

**Comment by jfversluis** [comment]
No response to our request for details, closing this for now.
