### ISSUE TITLE
ActivityIndicator width is autosize in absolutelayout is -1/0 on windows

### ISSUE THREAD

**Issue by TiesTheunissen** [xamarin/Xamarin.Forms#1399]
### Description
When I create an ActivityIndicator in my absolute layout it doesn't show with the function "            SetLayoutBounds(activityIndicator, new Rectangle(dActivityIndicatorX, dActivityIndicatorY,
                AutoSize, AutoSize));"
the autosize width is -1 or 0 and must be set in widthrequest or fixed size to show.

conform on xamarin forms 2.4.38799 and 2.5.121934

### Steps to Reproduce

1. Create an Xamarin PCL application with an UWP platform application.
2. In the portable classes create an C# page and link the app init page to the new page.
3. Create a new class that inherits AbsoluteLayout.
4. In this class create an ActivityIndicator.
5. Use SetLayoutBounds with autosize as width and height.

### Expected Behavior
The ActivityIndicator shows up and uses the intire screen.

### Actual Behavior
The ActivityIndicator doesn't show.
if the Width is more than 0 it does show.
This code runs oke in Android.

### Basic Information

- Version with issue: confirmed in 2.4.38799 and 2.5.121934
- Last known good version: -
- IDE: Visual Studio
- Platform Target Frameworks:
  - UWP:  10240 
- Nuget Packages: Xamarin forms.
- Affected Devices: UWP

### Reproduction Link
http://www.filedropper.com/bugtestactivitiyindicator_2

**Comment by mgwalm** [comment]
This is still a problem in forms version 3.0.0.482510.
As stated above it works on a contentpage, but not when one uses a NavigationPage.

I've compared the UWP Visual tree of an app that is using a ContentPage to one that is using a NavigationPage, and on the ContentPage there is a DeterminateRoot (border) as the last child of the FormsProgressBar that has an Animation and Visual State property (ie the storyboard is running). However on the NavigationPage version the  DeterminateRoot (border) is present but the Animation and Visual State property is missing, ie, the storyboard is not running.
