### ISSUE TITLE
[Bug] CaoruselView - Call setLayoutManager

### ISSUE THREAD

**Issue by angelru** [xamarin/Xamarin.Forms#13991]
`[RecyclerView] Cannot scroll to position a LayoutManager set. Call setLayoutManager with a non-null argument.`

Android 9

**Comment by jsuarezruiz** [comment]
@angelru  Is it programmatically scrolling to a specific item? Could you attach an example where reproduce the issue?

**Comment by angelru** [comment]
@jsuarezruiz no, just navigate between the tabs in debug mode and see the messages
[13991.zip](https://github.com/xamarin/Xamarin.Forms/files/6188865/13991.zip)

**Comment by rachelkang** [comment]
hmmm interesting - I am able to repro and do see those debug messages on Android only. I can also confirm that this seems specific to CarouselView. @rmarinho do you know what might be causing this?

**Comment by rachelkang** [comment]
Also @angelru are you seeing any odd behaviors that might be related to this, aside from the debug messages?

**Comment by angelru** [comment]
I don't see anything strange in the behavior, but debugging my app I saw that message
