### ISSUE TITLE
[Enhancement] reorder in listview or collection view

### ISSUE THREAD

**Issue by kdbhalala** [xamarin/Xamarin.Forms#14007]
## Summary
add reordering capabilities in listview or collection view
 
I don't know how to submit this but I hope you get an idea of what I'm trying to say

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
