### ISSUE TITLE
Assembly.Location return assembly name[Bug] 

### ISSUE THREAD

**Issue by ehsangfl** [xamarin/Xamarin.Forms#14009]
I have to use Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScript for compile some scripts. on MonoGlobalAssemblyCach constructor inside of  ScriptOptions constructor, on line 32 , 33 :
```
 var systemAssemblyFile = typeof(Uri).Assembly.Location;
            s_gacDirectory = Directory.GetParent(Path.GetDirectoryName(systemAssemblyFile)).Parent.FullName;
```
the SystemAssemblyFile value is "system.dll", not full path of dll. as result,the value of Path.GetDirectoryName(systemAssemblyFile) is empty string, and this is cuase of an exception on Directory.GetParent(string path);

Steps to Reproduce

1. Open New Project
2. Install Microsoft.CodeAnalysis.CSharp.Scripting package
3. Read Default property of Microsoft.CodeAnalysis.Scripting.ScriptOptions
 
`var SO = Microsoft.CodeAnalysis.Scripting.ScriptOptions.Default;`

- Version with issue: Xamarin 4.8.1821
- Android: 21
- Android Support Library : 7
- NuGet Packages: Microsoft.CodeAnalysis.CSharp.Scripting 3.9
-Visual studio 16.8.5

**Comment by jsuarezruiz** [comment]
@Redth What is the correct repository to transfer this issue?
