### ISSUE TITLE
[Enhancement] Include source info for binding failure debug output

### ISSUE THREAD

**Issue by spadapet** [xamarin/Xamarin.Forms#14006]
## Summary

Debug output for binding failures currently looks like "Binding: Message", but it doesn't say where the binding failure came from in a source XAML file. If the binding failure has source info, it should be included in the debug output.

## API Changes

n/a

## Intended Use Case

Visual Studio's Hot Reload feature uses the BindingFailed event to know about binding failures and their source location. But... when the app first starts, before Hot Reload is initialized, binding failures are only available to VS in the debug output window. Those binding failures don't have source info, so double clicking on them in the binding failures pane in VS does nothing.

The selected row happens on boot and has no source info:

![image](https://user-images.githubusercontent.com/2523431/111009901-b3f59700-8349-11eb-9bf7-4b2ecbfc961d.png)

The debug output currently looks like this:

```
[0:] Binding: 'FooNavigateCommand' property not found on 'DataBindingDemos.MainPage', target property: 'Xamarin.Forms.TextCell.Command'
[0:] Binding: 'FooRed' property not found on 'DataBindingDemos.RgbColorViewModel', target property: 'Xamarin.Forms.Slider.Value'
[0:] Binding: 'FooGreen' property not found on 'DataBindingDemos.RgbColorViewModel', target property: 'Xamarin.Forms.Slider.Value'
```

To include source info and not break existing VS debug output parsers, source info should be added on a new line:

```
[0:] Binding: 'FooNavigateCommand' property not found on 'DataBindingDemos.MainPage', target property: 'Xamarin.Forms.TextCell.Command'
Binding source: line=1, column=10, file="path in quotes.xaml"
[0:] Binding: 'FooRed' property not found on 'DataBindingDemos.RgbColorViewModel', target property: 'Xamarin.Forms.Slider.Value'
Binding source: line=2, column=15, file="path in quotes.xaml"
[0:] Binding: 'FooGreen' property not found on 'DataBindingDemos.RgbColorViewModel', target property: 'Xamarin.Forms.Slider.Value'
Binding source: line=3, column=20, file="path in quotes.xaml"
```

The line, column, and file values come directly from the internal SourceInfo object. Both lines need to be written with a single debug output call so that there is no chance for other debug output to appear between them. The line prefix of "Binding source:" doesn't matter much, just need something that can be recognized in a regular expression.

**Comment by LyalinDotCom** [comment]
@spadapet and I talked about this and I am very supportive of this approach to unblock us on startup. @StephaneDelcroix could we get it done in Xamarin.Forms servicing and port into .NET MAUI as well? that would be ideal. I'd love to keep navigate to source a feature that isnt for .NET MAUI customers only

**Comment by spadapet** [comment]
@StephaneDelcroix hold on going forward this PR for now, I'm going to test out moving the BindingFailed event handler to an earlier location in the HotReload code.

**Comment by spadapet** [comment]
I'll also add a comment in the open PR by @StephaneDelcroix, but I think this issue can be closed. @LyalinDotCom can chime in too. With the latest VS Hot Reload and latest Xamarin 5.0.0.2012, the initial binding failures in MainPage.xaml do have source info:

![image](https://user-images.githubusercontent.com/2523431/112549501-28cdc580-8d7b-11eb-8ed7-7abd25a4969f.png)

That's when debugging the Android emulator (I'm assuming iOS would do the same thing). It's just UWP that doesn't have source info for the initial binding failures in MainPage.xaml. Since Android works we probably don't need a fix.

**Comment by jfversluis** [comment]
Closing this for now
