### ISSUE TITLE
Add support for Android bottom navigation bar in Xamarin.Forms

### ISSUE THREAD

**Issue by lukemcnally84** [xamarin/Xamarin.Forms#1400]
The latest Material Design guidelines talk about a bottom navigation bar:
https://material.io/guidelines/components/bottom-navigation.html#

This is available within Android as the BottomNavigationView:
https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html

When can we expect to see this supported in Xamarin.Forms? Ideally, this would be available via the TabbedPage control, as suggested here:
https://forums.xamarin.com/discussion/84565/bottomnavigationview-option-for-tabbedpage-on-android

**Comment by ChaseFlorell** [comment]
I really like this, but I have a question.

Does Top Nav get deprecated for Android or is it maintained as default. Should there be a `UseLegacy` flag to maintain the old way and set bottom nav as the new default? 

```
tabbedPage.On<Android>().UseLegacyTopNavigation();
```

It would be a breaking change if introduced as the new default, so maybe it gets rolled out in two stages.

V2.x

```
tabbedPage.On<Android>().UseBottomNavigation();
```
V3.x

```
[Obsolete("this is now the default")]
public void UseBottomNavitation() {}

//
tabbedPage.On<Android>().UseLegacyTopNavigation();
```

**Comment by dhaligas** [comment]
I think there should be both or essentially have a tabbed view that is the top tab 
it is common in android to combine both top and bottom

**Comment by Goldstrike** [comment]
Any news about this request? A bottom TabbedPage is required if we look UI of the latest  apps!

**Comment by samhouts** [comment]
Hey, I know this issue is older, but we do have an official spec open on #1675 and a PR open on #1748, so I'll go ahead and close this issue. Please follow #1675 and/or #1748 for updates. Thanks!

**Comment by Charuwaka** [comment]
tabbedPage.On<Android>().UseBottomNavigationView() will this work in 3.0 Pre or should i specify Enum position >

**Comment by rcunniffe** [comment]
supposedly it might be done tho?
