### ISSUE TITLE
[Bug] [Android] Borderless Material Entry / Editor shows border

### ISSUE THREAD

**Issue by bhuvan94** [xamarin/Xamarin.Forms#14003]
### Description
Borderless Material Entry / Editor Shows border after updating the Xamarin Forms 5.0.0.2012 and Xamarin.Forms.Visual.Material 5.0.0.2012. Previously it was working fine.
### Steps to Reproduce

I have attached two samples just download and run it.

### Expected Behavior
Border line shouldn't be presented.
### Actual Behavior
Border line is showing.
### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: 4.7.0.1260 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

#### Expected Result
![Screenshot_1615562172](https://user-images.githubusercontent.com/20217737/110962347-e2d63200-8376-11eb-801f-8b19642b4907.png)
#### Actual Result
![Screenshot_1615562652](https://user-images.githubusercontent.com/20217737/110962382-eff32100-8376-11eb-9012-a6d4d989f177.png)

### Reproduction Link

Xamarin Forms_4.7.0.1260:  [TestSample_XamarinForms_4.7.0.1260.zip](https://github.com/xamarin/Xamarin.Forms/files/6131091/TestSample_XamarinForms_4.7.0.1260.zip)

Xamarin Forms_5.0.0.2012:  [TestSample_XamarinForms_5.0.0.2012.zip](https://github.com/xamarin/Xamarin.Forms/files/6131044/TestSample_XamarinForms_5.0.0.2012.zip)

### Workaround

Couldn't find any workaround

**Comment by skadookkunnan** [comment]
Any update on this issue? We are also experiencing this issue.

Please provide an update.

**Comment by PureWeen** [comment]
@bhuvan94 @skadookkunnan 

I'm not really sure how/why your original Custom Renderer worked

Can you try these settings in your custom renderer? 
```C#
 Control.BoxStrokeWidth = 0;
Control.BoxStrokeWidthFocused = 0;
```     
            
![image](https://user-images.githubusercontent.com/5375137/124006882-635d8480-d9a0-11eb-80c8-89037408408e.png)
