### ISSUE TITLE
[Bug] [macOS] Cannot scroll outer scrollview with cursor on the inner scrollview

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#14011]
### Description
In nested scrollview, cannot scroll the parent scrollview when mouse on the inner scrollview in macOS. The issue occurs even if the inner scrollview does not has scrollable content. Also, we have tried the inner scrollview has ScrollOrientation as Neither or IsEnabled as false but nothing works. Any help would be appreciated.

### Steps to Reproduce
1. Run the attached sample.
2. Scroll the view by placing the cursor on the inner scrollview (Blue area)
3. Note: The view cannot scrolled.

### Expected Behavior
The outer scrollview should be scrolled if the inner scrollview reached end/ with no scrollable items.

### Actual Behavior
The outer scrollview not scrolled even the inner scrollview is not scrollable.

### Basic Information

- Version with issue: 5.0

### Environment
**Visual Studio Community 2019 for Mac**
Version 8.7.9

**Xamarin.Mac**
Version: 6.20.2.2 (Visual Studio Community)

**Operating System**
Mac OS X 10.15.7

### Reproduction Link
[ScrollViewIssue](https://www.syncfusion.com/downloads/support/directtrac/general/ze/ScrollViewIssue-1115861209)

### Workaround
No

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
