### ISSUE TITLE
PDF preview in ContentPage

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [xamarin/Xamarin.Forms#14012]
Hi.
Need a working nuget to work with the PDF file.
Which ones do you use?

**Comment by Jakar510** [comment]
see https://github.com/xamarin/Xamarin.Forms/issues/14021#issuecomment-800767875

**Comment by jsuarezruiz** [comment]
I'm going to close this issue to put the focus on https://github.com/xamarin/Xamarin.Forms/issues/14021
