### ISSUE TITLE
Windows bug Xamarin forms Listview returns wrong item

### ISSUE THREAD

**Issue by TiesTheunissen** [xamarin/Xamarin.Forms#1401]
### Description
I have a master detail page. In the master I have 3 groups with each a ObservableCollection list. The fully menu is connected with a command on "onMenuItemTapped" but when I tap an item it gives the wrong item as parameter. Each group returns the item in the list with the tapped index + 1

- Version with issue: Xamarin forms version 2.4.X and 2.5.X
- Last known good version: 2.3
- IDE:
- Platform Target Frameworks: 
  - UWP: version 10420
- Nuget Packages: Xamarin Froms
- Affected Devices: UWP

### Reproduction Link
http://www.filedropper.com/bugtest

Edit: Re-uploaded zip (wiped bin/obj/package folders):
[BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1559477/BugTest.zip)

**Comment by r-a-y-w** [comment]
Signed up just to write this. This is the same problem as https://bugzilla.xamarin.com/show_bug.cgi?id=60720 (High Priority) and am also urgently waiting for a fix. Affects all Windows (RT & UWP).

**Comment by adammeaney** [comment]
I found it to be that the grouping is what makes the items go off.

In a normal ListView, I get the itemselected I expect.

Groups offset the listview.

**Comment by sander1095** [comment]
I can confirm this is happening to me, too.

Xamarin.Forms version:  2.5.0.121934

[Here](https://github.com/xamarin/Xamarin.Forms/files/1563147/UWPListviewProblem.zip) 
you can download my sample app that highlights this HUGE issue. If you run the app on Android everything will work. UWP will choose wrong values and this is a HUGE issue! I can't deploy an app thanks to this.

Using the ItemTapped event in the code-behind will give the same result. 

I'll try to find a work-around and if I can find one, I'll post a comment here. If anyone else finds a work-around, please let me know

**Comment by squinn7** [comment]
I hate to be breathing down your neck but I have followed this issue since it was reported on bugzilla. I have been experiencing it since June. Because of this issue, we can't update any of our apps to use a later version of forms than 2.3.4.270. I would like to know how quickly we can expect this to be resolved. It's not like any other bug which can be worked around. This makes list views unusable which are the backbone of most our apps.

Thanks, in advance. Eagerly awaiting a fix

**Comment by r-a-y-w** [comment]
#1439 is the official (same) issue.

**Comment by sander1095** [comment]
@rmarinho  @samhouts  Thank you very much for fixing this issue! Can you tell me when this fix will be released on Nuget/as a new version? I'd like to update my app with this fix as fast as possible!

**Comment by alistair23** [comment]
Can it be back ported to the 2.4 release as well?

**Comment by rmarinho** [comment]
@alistair23 we are not planing in shipping 2.4 service releases

**Comment by alistair23** [comment]
Is there a work around we can use then? This issue is also in 2.4 which means the whole release doesn't work with UWP.

**Comment by TiesTheunissen** [comment]
@alistair23 we use version 2.4.0.38779. The bug doesn't exist in this version. The problem with this version is that if you click an item it fires 2 times. the first time is wrong. if you allow your code only the seccond time it works fine as a work around.

**Comment by alistair23** [comment]
@TiesTheunissen so you just have a static variable to only act on the second action?

**Comment by sander1095** [comment]
The bug has been fixed in a new release

https://github.com/xamarin/Xamarin.Forms/releases/tag/release-2.5.0-sr4
