### ISSUE TITLE
How do I render a UIButton in Xamarin.iOS? 

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Xamarin.Forms#14022]
How do I render a UIButton in Xamarin.iOS? See the current [Code][1] for the full list. 

This is the code I'm using to create and add the button to the `Xamarin.Forms.Platform.iOS.CellTableViewCell` cell. I cannot get the button to display anything. 
With the use of a `Foundation.NSMutableAttributedString`, it shows a cut-off section of text in the top left corner, regardless of anything I try (alignments, insets, bounds, various constraints, etc). I'm currently trying things from [Xamarin.Forms.Platform.iOS.Renderers.ButtonRenderer][2], but still can't get anything to display at all, no text, no button, or its outline. 

If you could fork the repo and fix it or post the solution here, I would be very grateful. 

	protected override void SetUpContentView()
	{
		var insets = new UIEdgeInsets(SVConstants.Cell.PADDING.Top.ToNFloat(), SVConstants.Cell.PADDING.Left.ToNFloat(), SVConstants.Cell.PADDING.Bottom.ToNFloat(), SVConstants.Cell.PADDING.Right.ToNFloat());
		_Button = new UIButton(UIButtonType.RoundedRect)
				  {
					  AutoresizingMask = UIViewAutoresizing.All,
					  HorizontalAlignment = UIControlContentHorizontalAlignment.Center,
					  VerticalAlignment = UIControlContentVerticalAlignment.Center,
					  ContentEdgeInsets = insets,
					  // TitleEdgeInsets = insets
				  };

		DefaultFontSize = _Button.TitleLabel.ContentScaleFactor;
		DefaultTextColor = _Button.TitleLabel.TextColor;

		_Recognizer = new UILongPressGestureRecognizer(RunLong);
		_Button.TouchUpInside += OnClick;          // https://stackoverflow.com/a/51593238/9530917
		_Button.AddGestureRecognizer(_Recognizer); // https://stackoverflow.com/a/6179591/9530917

		ContentView.AddSubview(_Button);
		_Button.CenterXAnchor.ConstraintEqualTo(ContentView.CenterXAnchor).Active = true;
		_Button.CenterYAnchor.ConstraintEqualTo(ContentView.CenterYAnchor).Active = true;

		_Button.WidthAnchor.ConstraintEqualTo(ContentView.WidthAnchor).Active = true;
		_Button.HeightAnchor.ConstraintEqualTo(ContentView.HeightAnchor).Active = true;

		UpdateConstraintsIfNeeded();
		LayoutIfNeeded();
	}

  [1]: https://github.com/Jakar510/Jakar.SettingsView/blob/update_iOS_API/src/SettingsView.iOS/Cells/CommandCells/ButtonCellRenderer.cs
  [2]: https://github.com/xamarin/Xamarin.Forms/blob/8b10f11651b85b2821214b786f7a101a8b3c81e0/Xamarin.Forms.Platform.iOS/Renderers/ButtonRenderer.cs

**Comment by PureWeen** [comment]
Hey @Jakar510 this is probably a better question for StackOverflow 

Once you start moving into custom renderer and native territory then that's outside the scope of the issues here.

You can use Xcode to attach to a running process on your device and then inspect the visual hierarchy that way which sometimes tells you why something isn't rendering.

I'm guessing you're not setting a frame somewhere or maybe passing the wrong arguments to the base of UIButton?
