### ISSUE TITLE
[Enhancement] Make common internal classes in Xamarin.Forms

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Xamarin.Forms#14023]
## Summary
Make common classes, that are internal, in Xamarin.Forms public. 

## API Changes

Make common classes, that are internal, in Xamarin.Forms public. 
Examples include: 
[KeyboardInsetTracker](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/KeyboardInsetTracker.cs)
[Android Extensions](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.Android/Extensions.cs)
[iOS Extensions](https://github.com/xamarin/Xamarin.Forms/tree/5.0.0/Xamarin.Forms.Platform.iOS/Extensions)

There are many more internal classes that need to be public. There are also android extensions that I found before but can't locate now that make indexing API levels easy but are internal to Xamarin.Forms.

## Intended Use Case
There's no reason to duplicate code.

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Forms anymore and hopefully this will be better with the new .NET MAUI architecture :)

THanks for thinking with us!
