### ISSUE TITLE
[Bug] Android Always working GC in debug mode XF 5

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Xamarin.Forms#14020]
Don't know to which team this bug is related, to VS or to XF or even Xamarin Android, but in debug mode GC is not stopping and application becomes not responsible. When I unplug my phone from PC and restart the app it works perfectly. Don't know how to reproduce this. I beleive it is so rare bug. Only in debug mode. Can reproduce on 2 PC's and on different devices including emulators
2 weeks ago I didnt notice such behavior. 

![image](https://user-images.githubusercontent.com/23138430/111362615-b5032d00-8697-11eb-9dc7-29ae81c22f5e.png)

and this is infinite.

In iOS everything OK, but iOS I run on mac

Maybe when gather more info I will update this post

XF 5, VS 16.8.5, 16.9.1

#https://github.com/xamarin/xamarin-android/issues/5752

**UPD:**
This issue related to the hot reload feature, disabling it fixes the issue. but this is not the solution of the problem

> VS bug [#1296788](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1296788)

**Comment by ErikMatuska** [comment]
Same problem. I am unable to find the source of this problem but after few seconds in DEBUG I go from this:
[Mono] GC_MINOR: (Nursery full) time 14.93ms, stw 15.61ms promoted 1395K **major size: 5200K** in use: 4400K los size: 7168K in use: 5870K

to this:
GC_MINOR: (Nursery full) time 140.39ms, stw 176.88ms promoted 1042K **major size: 548832K** in use: 531093K los size: 32960K in use: 22684K

**Comment by johnbmangold** [comment]
I'm having the same problem. it doesn't appear dependent on any config options. I noticed the issue started up after updating Visual Studio 2019 to 16.9.1. Visual Studio 2019 16.9.2 still has the issue present.

**Comment by jsuarezruiz** [comment]
cc @BretJohnson

**Comment by Redth** [comment]
Closed as there's a partner bug tracking: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1296788
