### ISSUE TITLE
When no default namespace is provided at the project level, the .g.cs files get compiled with a namespace of " ."

### ISSUE THREAD

**Issue by nlraley** [xamarin/Xamarin.Forms#1403]
### Description
If you change the project files so there is no default namespace, then the .g.cs files will compile the code with a space for the namespace, so you end up with a " ." leading the namespace declaration.

I can wipe out the default namespace which requires me to manually specify a namespace for my class files, i.e. TestNamespace.  The .g.cs would then have " .TestNamespace" as the namespace declaration.

### Steps to Reproduce

1. Edit the .csproj files and clear the default namespace value manually.
2. Create a class that will create a .g.cs file and give it a namespace declaration.
3. Build will fail b/c the .g.cs file will list the incorrect namespace.

### Expected Behavior
Namespace should be what is specified in the class file.

### Actual Behavior
An empty space and period are added before the namespace declared in the class file.

### Basic Information

- Version with issue: Latest stable release.
- Last known good version: Recurring issue.
- IDE:
- Platform Target Frameworks: 
  - iOS:  Any
  - Android: Any 
  - UWP:  Any

**Comment by rmarinho** [comment]
Hi, can you provides a simple reproduction sample so we can understand better what's the issue?!

Thanks.

**Comment by nlraley** [comment]
Actually, looking at trying to reproduce this on a fresh Xamarin.Forms project, I can't get it to reproduce the issue any more.  I'll go ahead and close this as I believe it's been resolved since I was seeing the issue.  If I run across it again on another project setup I'll be sure to let everyone know and include a copy of the project reproducing the issue.

Thanks everyone!
