### ISSUE TITLE
[Bug] Hot reload iOS when set to Changes only  app becomes very very slow

### ISSUE THREAD

**Issue by developer9969** [xamarin/Xamarin.Forms#14034]
Hi
I have dont have a repo because it only happens on a production app.

When hot reload is set to  "Changes only"  everything loads very very slow  and the app is unusable.  iOS
Change to Full page or disable Hot reload and and everything is fine!!
![image](https://user-images.githubusercontent.com/16970109/111745995-4daad000-8885-11eb-981d-805f500bab80.png)

Tell me what kind of log you need and how and I can see if I can provide them.

thanks

**Comment by decv86** [comment]
I have to issue

**Comment by jsuarezruiz** [comment]
cc @BretJohnson

**Comment by jtorvald** [comment]
Duplicate/Related to: #14010

**Comment by Redth** [comment]
Closing, tracking in #14010
