### ISSUE TITLE
package androidx.activity.contextaware does not exist. JAVAC0000: androidx.activity.contextaware.OnContextAvailableListener

### ISSUE THREAD

**Issue by Jakar510** [xamarin/Xamarin.Forms#14042]
### Description
[Visual Studio Issue](https://developercommunity.visualstudio.com/t/package-androidxactivitycontextaware-d/1376876?entry=myfeedback&space=8&sort=newest)
error: package androidx.activity.contextaware does not exist. androidx.activity.contextaware.OnContextAvailableListener	
				
	Project not selected to build for this solution configuration 
	AppName.Android -> D:\WorkSpace\AppName\AppName\AppName.Android\bin\Release\AppName.Android.dll
	obj\Release\110\android\src\mono\androidx\activity\contextaware\OnContextAvailableListenerImplementor.java:8: error: package androidx.activity.contextaware does not exist
			androidx.activity.contextaware.OnContextAvailableListener
										  ^
	  Note: Some input files use or override a deprecated API.
	  Note: Recompile with -Xlint:deprecation for details.
	  Note: Some input files use unchecked or unsafe operations.
	  Note: Recompile with -Xlint:unchecked for details.
	 1 error

MainActivity.cs
	 
	[Preserve(AllMembers = true)]
	[IntentFilter(new[]
				  {
					  Android.Nfc.NfcAdapter.ActionNdefDiscovered
				  },
				  Categories = new[]
							   {
								   Android.Content.Intent.CategoryDefault
							   },
				  DataMimeType = App.NFC_MIME_TYPE)]
	[Activity(Label = "AppName", Icon = "@drawable/Icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = Android.Content.PM.ConfigChanges.ScreenSize | Android.Content.PM.ConfigChanges.Orientation)]
	 
	public class MainActivity : Xamarin.Forms.Platform.Android.FormsAppCompatActivity, Application.IActivityLifecycleCallbacks
	{
		internal static MainActivity Instance { get; private set; }
		protected override void OnCreate( Bundle savedInstanceState )
		{
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar;

			base.OnCreate(savedInstanceState);

			LibVLCSharp.Forms.Shared.LibVLCSharpFormsRenderer.Init();
			LibVLCSharp.Shared.Core.Initialize();
			LibVLCSharp.Forms.Platforms.Android.Platform.Init(this);

			Xamarin.Forms.Forms.SetFlags("MediaElement_Experimental");
			Xamarin.Forms.Forms.Init(this, savedInstanceState);
			Xamarin.Forms.FormsMaterial.Init(this, savedInstanceState);
			Xamarin.Essentials.Platform.Init(this, savedInstanceState);

			//MediaManager.CrossMediaManager.Current.Init();
			//ScnViewGestures.Plugin.Forms.Droid.Renderers.ViewGesturesRenderer.Init();
			Plugin.CurrentActivity.CrossCurrentActivity.Current.Init(this, savedInstanceState);
			Plugin.NFC.CrossNFC.Init(this);
			ZXing.Net.Mobile.Forms.Android.Platform.Init();
			Jakar.SettingsView.Droid.SettingsViewInit.Init(this);
			Acr.UserDialogs.UserDialogs.Init(this);
			Rg.Plugins.Popup.Popup.Init(this);

			if ( Build.VERSION.SdkInt >= BuildVersionCodes.Q ) { RegisterActivityLifecycleCallbacks(this); }

			Plugin.Fingerprint.CrossFingerprint.SetCurrentActivityResolver(() => Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity);

			Instance = this;
			LoadApplication(new App(App.Audience.Target.iTrueLogic));
		}

		public override void OnRequestPermissionsResult( int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults )
		{
			//global::ZXing.Net.Mobile.Android.PermissionsHandler.OnRequestPermissionsResult(requestCode, permissions, grantResults);
			Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
			Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
			base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}
		protected override void OnNewIntent( Android.Content.Intent intent )
		{
			base.OnNewIntent(intent);

			// Plugin NFC: Tag Discovery Interception
			Plugin.NFC.CrossNFC.OnNewIntent(intent);
		}
		protected override void OnPause()
		{
			base.OnPause();
			Xamarin.Forms.MessagingCenter.Send(nameof(App), nameof(OnPause));
		}
		protected override void OnRestart()
		{
			base.OnRestart();
			Xamarin.Forms.MessagingCenter.Send(nameof(App), nameof(OnRestart));
		}
		protected override void OnDestroy()
		{
			if ( Build.VERSION.SdkInt >= BuildVersionCodes.Q ) { UnregisterActivityLifecycleCallbacks(this); }

			base.OnDestroy();
		}
		public override void OnBackPressed()
		{
			System.Diagnostics.Debug.WriteLine(Rg.Plugins.Popup.Popup.SendBackPressed(base.OnBackPressed)
												   ? "Android back button: There are some pages in the PopupStack"
												   : "Android back button: There are not any pages in the PopupStack");
		}
		public void OnActivityCreated( Activity activity, Bundle savedInstanceState ) { Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = activity; }
		public void OnActivityResumed( Activity activity ) { Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = activity; }
		public void OnActivityStarted( Activity activity ) { Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = activity; }
		public void OnActivitySaveInstanceState( Activity activity, Bundle outState ) { }
		public void OnActivityDestroyed( Activity activity ) { }
		public void OnActivityPaused( Activity activity ) { }
		public void OnActivityStopped( Activity activity ) { }
	}

### Steps to Reproduce

Started build.

### Expected Behavior

Trying to build in Release mode

### Actual Behavior

Build Failed

### Basic Information

- Version with issue: 11.1.0.26
- Last known good version: ?
- Platform Target Frameworks: 
  - Android: 11
- Android Support Library / AndroidX Version:  11.1.0.26
- NuGet Packages:

	Acr.UserDialogs -- Version: 7.1.0.481
	Jakar.SettingsView -- Version: 1.0.6
	LibVLCSharp.Forms -- Version: 3.4.9
	MailKit -- Version: 2.11.1
	Microsoft.AppCenter -- Version: 4.1.0
	Microsoft.CodeAnalysis.Common -- Version: 3.9.0
	Microsoft.CodeAnalysis.CSharp -- Version: 3.9.0
	Microsoft.CodeAnalysis.NetAnalyzers -- Version: 5.0.3
	Plugin.CurrentActivity -- Version: 2.1.0.4
	Plugin.Fingerprint -- Version: 2.1.2
	Steema.TeeChart.NET.Xamarin.Forms -- Version: 4.2021.2.25
	VideoLAN.LibVLC.Android -- Version: 3.2.0
	Xamarin.Android.Support.v7.AppCompat -- Version: 28.0.0.3
	Xamarin.Android.Support.v7.RecyclerView -- Version: 28.0.0.3
	Xamarin.AndroidX.Activity -- Version: 1.1.0.6
	Xamarin.AndroidX.Annotation -- Version: 1.1.0.9
	Xamarin.AndroidX.AppCompat -- Version: 1.2.0.5
	Xamarin.AndroidX.AppCompat.AppCompatResources -- Version: 1.2.0.5
	Xamarin.AndroidX.AppCompat.Resources -- Version: 1.1.0.1
	Xamarin.AndroidX.Biometric -- Version: 1.0.1.6
	Xamarin.AndroidX.Browser -- Version: 1.3.0.4
	Xamarin.AndroidX.Collection -- Version: 1.1.0.7
	Xamarin.AndroidX.Core -- Version: 1.3.2.1
	Xamarin.AndroidX.CustomView -- Version: 1.1.0.4
	Xamarin.AndroidX.Fragment -- Version: 1.2.5.3
	Xamarin.AndroidX.Legacy.Preference.V14 -- Version: 1.0.0.5
	Xamarin.AndroidX.Legacy.Support.Core.UI -- Version: 1.0.0.7
	Xamarin.AndroidX.Legacy.Support.Core.Utils -- Version: 1.0.0.6
	Xamarin.AndroidX.Legacy.Support.V13 -- Version: 1.0.0.5
	Xamarin.AndroidX.Lifecycle.Common -- Version: 2.3.0.1
	Xamarin.AndroidX.Lifecycle.Extensions -- Version: 2.2.0.5
	Xamarin.AndroidX.Lifecycle.LiveData -- Version: 2.3.0.1
	Xamarin.AndroidX.Lifecycle.LiveData.Core -- Version: 2.3.0.1
	Xamarin.AndroidX.Lifecycle.Runtime -- Version: 2.3.0.1
	Xamarin.AndroidX.Lifecycle.Service -- Version: 2.3.0.1
	Xamarin.AndroidX.Lifecycle.ViewModel -- Version: 2.3.0.1
	Xamarin.AndroidX.Loader -- Version: 1.1.0.6
	Xamarin.AndroidX.Media -- Version: 1.2.1.1
	Xamarin.AndroidX.MediaRouter -- Version: 1.2.2
	Xamarin.AndroidX.Migration -- Version: 1.0.8
	Xamarin.AndroidX.MultiDex -- Version: 2.0.1.7
	Xamarin.AndroidX.Navigation.Common -- Version: 2.3.2.1
	Xamarin.AndroidX.Navigation.Fragment -- Version: 2.3.2
	Xamarin.AndroidX.Navigation.Runtime -- Version: 2.3.2.1
	Xamarin.AndroidX.Palette -- Version: 1.0.0.6
	Xamarin.AndroidX.VersionedParcelable -- Version: 1.1.1.7
	Xamarin.AndroidX.ViewPager -- Version: 1.0.0.6
	Xamarin.AndroidX.WebKit -- Version: 1.4.0
	Xamarin.Forms.Visual.Material -- Version: 4.8.0.1821
	Xamarin.Google.Android.Material -- Version: 1.2.1
	Xamarin.AndroidX.Legacy.Support.V4 -- Version: 1.0.0.5
	Xamarin.Forms -- Version: 4.8.0.1821
	Xamarin.Essentials -- Version: 1.6.1
	ZXing.Net.Mobile.Forms -- Version: 3.0.0-beta5

### Environment

Visual Studio Version 16.8.7

### Build Logs

[Output-Build.txt](https://github.com/xamarin/Xamarin.Forms/files/6178034/Output-Build.txt)

**Comment by Jakar510** [comment]
When i compiled against android 10 instead of 11, the issue doesn't occur.

**Comment by jsuarezruiz** [comment]
Seems to be the same (or related) with https://github.com/xamarin/Xamarin.Forms/issues/13843

**Comment by JamestsaiTW** [comment]
I got this issue today. My workaround is update nuget package Xamarin.AndroidX.Core to version 1.3.2.**3**, build success, and App run initial fine. 
But when I try to navigate my App's page by ShellContent from first page to other page, I got #13843 problem.

**Comment by Jakar510** [comment]
The issue still occurs with VS 16.10.2, with Android SDK v11.3.0.4

**Comment by Jakar510** [comment]
I must compile against Android 10 in order to compile in release builds. debug works with either 10 or 11.

![14042](https://user-images.githubusercontent.com/49802225/122817407-79cb5800-d29d-11eb-8f74-984fe1693958.PNG)

**Comment by Jakar510** [comment]
This needs to be fixed by August 2021. as apps will not be allowed to be uploaded using older APIs.

> Starting in August 2021, new apps will need to Target API level 30 (Android 11) or above and adjust for behavioral changes;

[Source](https://developer.android.com/distribute/best-practices/develop/target-sdk)

**Comment by Jakar510** [comment]
Installing Xamarin.AndroidX.Activity fixes this issue, as suggested by [this comment](https://github.com/xamarin/Xamarin.Forms/issues/14193#issuecomment-828228605).

**Comment by EmilAlipiev** [comment]
> This needs to be fixed by August 2021. as apps will not be allowed to be uploaded using older APIs.
> 
> > Starting in August 2021, new apps will need to Target API level 30 (Android 11) or above and adjust for behavioral changes;
> 
> [Source](https://developer.android.com/distribute/best-practices/develop/target-sdk)

are you sure about this? I am compiling against Android 10 and in appcenter there are crashes related to this. see the other related issue. I think that it has something to do with Androidx Fragment package

**Comment by Jakar510** [comment]
@EmilAlipiev 
perhaps, but it does compile against Android 11 with that package installed, while before it doesn't. The [issues](https://github.com/xamarin/Xamarin.Forms/issues/14193#issuecomment-867755339) with Xamarin.AndroidX.Fragment is a separate, albeit possibly related, problem.
