### ISSUE TITLE
[Bug] Converter doesn't work correctly inside a CollectionView [iOS]

### ISSUE THREAD

**Issue by Marmosquera** [xamarin/Xamarin.Forms#14047]
### Description
I'm facing the following problem only in iOS

In the `DataTemplate `of a `CollectionView`, I have a Label that shows the price of an order.
The order has a status (enum) that can be accepted canceled, rejected, etc.
I have a converter that depending on the status of the order, I set the `TextDecoration `of the `Label `to `StrikeThrough `(when canceled or rejected) or to None in any other case.
When data are loaded for the first time, everything looks good.
After I refresh the data, for the second time, some of the labels have a `TextDecorations.Strikethrough`, although they don't suppose that have (their order status is not canceled or rejected)
Data are hardcoded, so they don't change during refresh
You can find an example at the following repo
I guess the question is obvious, why the converter (or the CollectionView) doesn't work correctly after the second refresh or is it something else that is going wrong?
How can I fix this?

You can see the effect in the following screencast (the price of the second item in the CollectionView will have TextDecorations.Strikethrough after the second refresh)
### Steps to Reproduce

1. Start app
2. Refresh twice

### Expected Behavior

The amount label should only have the decorator `StrikeThrough` when the order is rejected 

### Actual Behavior

The amount label has the decorator `StrikeThrough` no matter the converter return value.

### Basic Information

- Version with issue: v.4.8.0.1269
- Affected Devices: iPhone

### Environment

Microsoft Visual Studio Professional 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA786
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.8.554.20160
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2052803+84e121f1403378489b842e1797df2f3f5a49ac3c
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.8.554.20160
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.8.554.20160
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.8.554.20160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.2.231
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.8.20241.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30924.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.8.43 (00471f8)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.20902.1 Commit Hash:b474efcb6f92db52a8f8e2e6a8cb9648476885cc
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PrestoCoveragePackage Extension   1.0
PrestoCoveragePackage Visual Studio Extension Detailed Info

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.8.20241.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.8.20241.2
Conda support for Python projects.

Python - Django support   16.8.20241.2
Provides templates and integration for the Django web framework.

Python - IronPython support   16.8.20241.2
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.8.20241.2
Profiling support for Python projects.

ResXManager   ResXManager
Manage localization of all ResX-Based resources in one place. Shows all resources of a solution and let's you edit the strings and their localizations in a well-arranged data grid.

SQL Server Data Tools   16.0.62010.06180
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.21016.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.8.0-5.20604.10+9ed4b774d20940880de8df1ca8b07508aa01c8cd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.8.0-beta.20507.4+da6be68280c89131cdba2045525b80890401defd
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.8.2.0
Visual Studio Tools for Unity

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.8.000.260 (d16-8@fd405a2)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.8.0.507 (remotes/origin/d16-8@e87b24884)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.8.112 (86385a3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.1.0.17 (d16-8/c0e2b8e)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: be2226b
    Java.Interop: xamarin/java.interop/d16-8@79d9533
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-8@2fb1cbc

Xamarin.iOS and Xamarin.Mac SDK   14.6.0.15 (87a1b18d8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
```

</details>

### Screenshots

![74887-rpreplay-final1614957172](https://user-images.githubusercontent.com/51424338/111997437-cca83e80-8af9-11eb-888a-d79c5cd60cfa.gif)

### Reproduction Link

https://github.com/gnout/TextDecoration

**Comment by PureWeen** [comment]
This looks like a bug with LabelRenderer and it's not applying the updated values for TextDecorations correctly when the viewcells get reshuffled

If you bind to the TextColor and return a text color instead of decoration then it all stays without issue

I'm not sure the best workaround here outside of creating a custom LabelRenderer for your labels and then process the TextDecoration change or set a different property

You can see our code here that modifies the underline/strike through

https://github.com/dotnet/maui/blob/b1866fd187b7e94c449e5617ff315b8dfe5576ed/src/Compatibility/Core/src/iOS/Renderers/LabelRenderer.cs#L273

**Comment by jsuarezruiz** [comment]
Could you attach again the sample?. Seems to no longer exists.

**Comment by jfversluis** [comment]
Can't be reproduced and no response for three weeks. Closing this, feel free to reopen or open a new issue referencing this one if it still affects you.

**Comment by edgiardina** [comment]
Just a heads up, I don't have a reproducable zip to share but this happens in our codebase 100%. I believe, but am not 100% sure, this is related to collectionview cell reuse since what we see are wrong values when using numeric converters (aka we have a collection of distance 1, distance 2, .... distance n, and when we scroll distance 1 out of view and then scroll back such that distance 1 is back, distance 1 is actually showing a value from another distance value (the cell is not being refreshed or refreshed with the wrong item).

**Comment by edgiardina** [comment]
@jfversluis I would respectfully like this re-opened. My coworker @karuuv built this excellent reproduction project. 
https://github.com/Karuuv/CollectionView_BugRepro ... converters in collectionview along with data reload/refresh seem to fail to update cells and it's caused us to roll back almost all our collectionview implementations to listview.
