### ISSUE TITLE
I wish .... Is there a "debug build" put out by the CI / CD process that generates the NuGet package ?

### ISSUE THREAD

**Issue by stephenhauck** [xamarin/Xamarin.Forms#14053]
I waned to look into these issues ..
https://github.com/xamarin/Xamarin.Forms/issues/10754
https://github.com/xamarin/Xamarin.Forms/issues/6593

But I need a debug build of the package and symbols to do so ... can you (do you already) generate a debug build of the package for us to use when you publish ?

**Comment by MagicAndre1981** [comment]
You can get nightlies builds from here:

![image](https://user-images.githubusercontent.com/8274816/112197341-44668e00-8c0c-11eb-8da0-c0012052dca2.png)

**Comment by stephenhauck** [comment]
Thanks @MagicAndre1981 .... I want the debug build for the last "stable release" ..... does it go back that far ?

**Comment by MagicAndre1981** [comment]
official nuget includes PDBs, SR3 is this [commit](https://github.com/xamarin/Xamarin.Forms/commit/68c17772d89c6e080e6a8cc53bd490f67dcc1bb0) where you can also get the Artifact

**Comment by jsuarezruiz** [comment]
Thanks for the answer @MagicAndre1981. @stephenhauck Let me know if can help with something.

**Comment by stephenhauck** [comment]
> Thanks for the answer @MagicAndre1981. @stephenhauck Let me know if can help with something.

I looked at the link and maybe I'm just wanting  simple answers to things  ..

I should be able to simply ....
- Download a debug build of the Xamarin.Forms NuGet package
- Use a "file source" to add it to my solution ...
- Debug Xamarin.Forms

If I follow the link above and then select the "Browse Files" button I then get navigated to the branch ...
I guess I am supposed to choose "Go to file"  ?????

I just want to debug some issues but the main issue seems to be that Microsoft has abandon Xamarin.Forms in favor of Maui...
The issues I referenced (along with others) seem to be things that can be investigated and addressed very quickly by a company the size of Microsoft ...... if they choose to.

**Comment by Redth** [comment]
https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap

The README of this repo does have instructions for building Xamarin.Forms from source.

The latest stable released nuget package does include .pdb debug symbols. Which may help with line numbers in your call stack.

If you want to debug and step through the code itself, you'll need to build from source and reference the projects from your app instead.
