### ISSUE TITLE
[Enhancement] Shell.Tab decouple icon and text color and visual states support

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#14056]
## Summary
Currently Shell.TabBarUnSelectedColor or Shell.UnSelectedColor acts on both Title and icon color.

1- Be able to style Tab icon or Title colors independently.
2- Implementing built-in Visual states (Selected/Normal or UnSelected/Disabled) for Shell.Tab that could be set in an implicit style.

## Intended Use Case
Trying to change Tint color of the icon when not selected and leave the text as it is.

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
