### ISSUE TITLE
How can listview be bound to the model itself?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14058]
How can listview be bound to the model itself?

listview   

                            <Label TextColor="{Binding  Path=.,Converter={StaticResource CompletionColor}}" IsVisible="{Binding Path=IsCompletion,Converter={StaticResource CompletionVisible}}" VerticalTextAlignment="Center" Margin="0,0,20,0" HorizontalOptions="EndAndExpand" Text="{Binding Path=IsCompletion,Converter={StaticResource CompletionText}}"></Label>

![image](https://user-images.githubusercontent.com/26525599/112404399-43884600-8d4b-11eb-8703-1137b32dcfd6.png)

            listView.ItemsSource = l;
![image](https://user-images.githubusercontent.com/26525599/112404491-69ade600-8d4b-11eb-9205-0fffe18c8e25.png)

**Comment by jsuarezruiz** [comment]
Yes, Binding . is the correct way. Attach a sample where you can see it.

[Issue14058.zip](https://github.com/xamarin/Xamarin.Forms/files/6203899/Issue14058.zip)

**Comment by bbhxwl** [comment]
> Yes, Binding . is the correct way. Attach a sample where you can see it.
> 
> [Issue14058.zip](https://github.com/xamarin/Xamarin.Forms/files/6203899/Issue14058.zip)

My code should be error free, right? I'll debug your demo. It is found that the previous value of convert is null. Then you can get the model. Why was it null several times before? My project may be OK, I only checked the first time is null. I think my binding failed.

**Comment by bbhxwl** [comment]
Is there an active xamarin forum?

**Comment by Redth** [comment]
Try https://docs.microsoft.com/en-us/answers/topics/dotnet-mobile-general.html
