### ISSUE TITLE
Is there a way for collectionview to disable scrolling?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14059]
Is there a way for collectionview to disable scrolling?

                <CollectionView>
  <CollectionView.ItemsLayout>
                        <LinearItemsLayout Orientation="Horizontal"     SnapPointsType="MandatorySingle"
                           SnapPointsAlignment="Start">
                        </LinearItemsLayout>
                    </CollectionView.ItemsLayout>
</CollectionView>

**Comment by jsuarezruiz** [comment]
You can create a custom renderer where you can access the native control property to disable the scroll.

Example in iOS:

```
if (Control != null)  
{  
     Control.ScrollEnabled = false;  
}  
```

**Comment by bbhxwl** [comment]
> You can create a custom renderer where you can access the native control property to disable the scroll.
> 
> Example in iOS:
> 
> ```
> if (Control != null)  
> {  
>      Control.ScrollEnabled = false;  
> }  
> ```

can only  custom renderer？

**Comment by AlleSchonWeg** [comment]
> > You can create a custom renderer where you can access the native control property to disable the scroll.
> > Example in iOS:
> > ```
> > if (Control != null)  
> > {  
> >      Control.ScrollEnabled = false;  
> > }  
> > ```
> 
> can only custom renderer？

Perhaps an effect will work: https://docs.microsoft.com/de-de/xamarin/xamarin-forms/app-fundamentals/effects/introduction

**Comment by Redth** [comment]
An effect may work as well, yes.

**Comment by bricefriha** [comment]
Wouldn't it be better just to implement an ` IsEnabled ` or something to disable scrolling?
