### ISSUE TITLE
[Bug][Shell] Shell.Current.GoToAsync doesn't clear stack on first call

### ISSUE THREAD

**Issue by LightAndrek** [xamarin/Xamarin.Forms#14062]
### Description
On Android, when navigationg for the first time using _Shell.Current.GoToAsync("//route")_, the navigation stack is not cleared. The previous page is still accessible using the back button of the device.

### Steps to Reproduce

1. Create an empty Shell project and replace the content of the ShellApp with 
```
<ShellItem Route="landing">
    <ShellContent ContentTemplate="{DataTemplate views:SplashPage}" />
</ShellItem>

<ShellItem Route="login">
    <ShellContent ContentTemplate="{DataTemplate views:LoginPage}" />
</ShellItem>
```
2. Create two empty _ContentPage_ (SplashPage and LoginPage)
3. Add this piece of code to _SplashPage_
```
protected override void OnAppearing()
{
    base.OnAppearing();
    Task.Run(async () =>
    {
        await Task.Delay(5000);
        await Shell.Current.GoToAsync("//login");
    });
}
```
4. Test

### Expected Behavior
The previous page is not accessible

### Actual Behavior
The first the user taps the back button, the previous page is showed. When calling the same _GoToAsync()_ and tapping the back button again, the app closes and returns to the system drawer.

### Basic Information

- Version with issue: latest 5.0.0.2012
- Last known good version: unknown
- Platform Target Frameworks: 
  - Android: Android 10

**Comment by jsuarezruiz** [comment]
cc @PureWeen

**Comment by PureWeen** [comment]
@LightAndrek can you attach a repro please? I tested your scenario and I'm not seeing the same behavior.

I've attached my attempt
[App14.zip](https://github.com/xamarin/Xamarin.Forms/files/6229406/App14.zip)
