### ISSUE TITLE
false "XFC0000" errors with release builds, debug builds ok and runs

### ISSUE THREAD

**Issue by fbd-ss** [xamarin/Xamarin.Forms#14064]
output window
6>xaml\cells\linear_guage_cell\mqtt_linear_guage_vm_template.xaml(13,6): XamlC error XFC0000: Cannot resolve type "fbd_forms:FbdLinearGaugeButton2".
6>xaml\cells\radial_guage_cell\mqtt_radial_guage_vm_template.xaml(13,6): XamlC error XFC0000: Cannot resolve type "fbd_forms:FbdRadialGuageButton".
6>xaml\themes\standard\standard_screen_style.xaml(763,42): XamlC error XFC0000: Cannot resolve type "FbdLinearGaugeButton2".
6>Done building project "fbd.iot.controller.csproj" -- FAILED.

false "XFC0000" errors with release builds, debug buils ok.  Resharper can find the files, so why cant xamlc

### Steps to Reproduce
build the project, one minute i had never seen this issue, now i cant build a release version.

### Expected Behavior
?
### Actual Behavior
to compile
### Basic Information

- Version with issue: version of what?, 
- Last known good version:
- Platform Target Frameworks: 
   - Android: api29
   - 
- NuGet Packages:
- Affected Devices: emulator and device

### Environment

shouldn't there be a tool that extracts all this info???

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jsuarezruiz** [comment]
What version of Xamarin.Forms are you using?

**Comment by fbd-ss** [comment]
5.0.0.2012
latest version of the ide.
Manually deleting all the bin and obj files made no difference.
I found a workaround.  In one of the projects in the solution i had to rename the namespace where it supposedly couldn't find the objects.  That forced the compiler to compile again and built ok.

**Comment by Redth** [comment]
Thanks for the update, sounds like a cache invalidation issue in the build.  If you can reproduce it, and are able to share your project, please zip it up (with the obj and bin folders) and submit a new issue with it.
