### ISSUE TITLE
[Bug] Xamarin.Forms can't change Application Icons in Xamarin.iOS on local device

### ISSUE THREAD

**Issue by Ogglas** [xamarin/Xamarin.Forms#14077]
### Description and Steps to Reproduce

I have followed both the guide from Microsoft and the upvoted answer on SO to change my iOS Application Icons but it does not work for me.

https://docs.microsoft.com/en-gb/xamarin/ios/app-fundamentals/images-icons/app-icons?tabs=windows

https://stackoverflow.com/a/54806603/3850405

To replicate I have used Visual Studio 2019 16.9.2 -> new project Mobile App (Xamarin.Forms) with these settings:

[![enter image description here][1]][1]

After this I deployed to my local device, `iPhone 12 Pro Max` first using software version `14.4.1` and then `14.4.2`.

The only Mac I have is an old `Macbook Pro 13" mid 2012 with 2,5GHz Dual-Core Intel Core i5`. It does have `macOS Catalina 10.15.7` and Xcode version 12.4 12D4e but running an iPhone simulator is extremely slow and hard to test on. If I do use the simulator it will work on simulated `iPhone 12 Pro Max iOS 14.4`.

I have then replaced every image via file system or the GUI in Visual Studio for Asset Catalogs -> Assets `(File system: Assets.xcassets\AppIcon.appiconset)`. When this did not work I added a new `Asset Catalog` and deleted the old one but it did not work either. 

`Info.plist` says correct source under `Visual Assets` and `App Icons`. 

If I change `Application Name` or `Bundle Identifier` in `Info.plist` the value is updated correctly. However If I try to edit Launch Screen under Launch Images that value is not updated either and only shows Xamarin original. 

Even after creating a new project I have tried to clean the solution and remove every `bin` and `obj` folder for the projects.

Given that it happens in a new project I don't think cache has anything to do with it but I have tried to clear these folders already:

Windows comupter:

    %LocalAppData%\Xamarin\

Mac:

    ~/Library/Caches/Xamarin/

When I cleared these folders I even had to log back in to Apple and get a new certificate via `Automatic provisioning` but I still don't get an updated icon.

https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/component-storage

Have I missed something or is this a bug?

  [1]: https://i.stack.imgur.com/9XtBc.png

### Expected Behavior

See new application icon

### Actual Behavior

Xamarin original icon is shown

### Basic Information

- Platform Target Frameworks: 
  - iOS:  SDK Version: Default, Visual Studio standard setting
- NuGet Packages: 
Xamarin.Essentials: 1.6.1
Xamarin.Forms: 5.0.0.2012+671-sha.68c17772d-azdo.4465181
- Affected Devices: iPhone 12 Pro Max software version 14.4.2.

### Environment

Microsoft Visual Studio Community 2019
Version 16.9.2
VisualStudio.16.Release/16.9.2+31112.23
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA622
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2112521+5741df381174d72f08e3632bb99f52e8635b6a1a
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.9.688.6828
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.9.688.6828
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.6.1000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.9.688.6828
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.1000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.9.21026.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Dotfuscator Community Edition   5.42.0.9514-e0e25f754
PreEmptive Protection - Dotfuscator CE

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

Fine Code Coverage   fcc-f339fe606-9d51-4fca-895c-d50375137b62
Visualize unit test code coverage easily for free in Visual Studio Community Edition (and other editions too)

GitHub.VisualStudio   2.11.102.28613
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.6.1000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.6.1000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.6.1000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.21130.2 Commit Hash:dacc0e71a5e060cdcab466a301cacea359c1b6da
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.9.21026.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.9.21026.1
Conda support for Python projects.

Python - Django support   16.9.21026.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.9.21026.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.9.21026.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.62103.10080
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
```

</details>

**Comment by themronion** [comment]
You forgot to mention that you are probably using Hot Reload and it is one of its limitations

**Comment by Ogglas** [comment]
> You forgot to mention that you are probably using Hot Restart and it is one of its limitations

Nope - Same result using Release version without debugging and Hot Restart. I got a few other tips on SO that did not work either: https://stackoverflow.com/q/66860352/3850405

**Comment by 21r8390** [comment]
I have the same problem. 😖 I'm working on a Windows computer with a connection to a central mac. If I deploy to a iOS device in debug or release mode, it shows the standard Xamarin app icon.
Is this just a deployment bug or will this also be the case when I publish my app?

**Comment by Ogglas** [comment]
@21r8390 Everything works when you deploy the app. I published a test app using Experimental Mobile Blazor Bindings to App Store that has the same issue locally but then everything works when published. 

https://apps.apple.com/se/app/id834914980

https://github.com/dotnet/MobileBlazorBindings

**Comment by 21r8390** [comment]
With a bit of luck and a lot of creativity I found out, if you run it on a Mac in the simulator it works fine. If you consider that, this error only shows up on windows on physical devices. Can anyone confirm this assumption? 👍

**Comment by jfversluis** [comment]
While not optimal, it seems to not be blocking as it does work on the store. Also I think this is not something that is influenced by Forms, if you still have issues with this please open an issue on the Xamarin.iOS repo, thanks!

**Comment by Mephisztoe** [comment]
I have the same problem and here is the funny part:
While the physical device shows the default xamarin appicon right after successful deployment using a Mac, I can see the correct application icon for only a split second when starting the app. When closing the app again, the default icon is back.

It gets even funnier:
When I restart the iPhone by physically turning it off and on again, it constantly shows the correct appicon.

Well... until I redeploy the app... then it starts over.
