### ISSUE TITLE
[Enhancement] Enable selecting and copying text in read only Editor and/or Entry

### ISSUE THREAD

**Issue by Elashi** [xamarin/Xamarin.Forms#14071]
## Summary
Read only Editor and Entry controls should allow selecting text and displaying context menus on long taps to allow Copy.

## Intended Use Case
This feature is important when displaying apps that has long articles like social networking, blogging, news, etc.

**Comment by johnshardman** [comment]
Related to
https://github.com/xamarin/Xamarin.Forms/issues/12930
and
https://github.com/xamarin/Xamarin.Forms/issues/5843

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
