### ISSUE TITLE
[Bug] [Shell] [Android] XF Shell (5.0.0.2012) - back navigation does not work. application crashes.

### ISSUE THREAD

**Issue by ORRNY66** [xamarin/Xamarin.Forms#14082]
### Description
Hi, I came across a problem with navigation in Xamarin Forms Shell version 5.0.0.2012. The problem is that when navigating back, the application crashes. PushAsync or GoToAsync navigation works, unfortunately back navigation does not work with either PopAsync or GoToAsync ("..").

When I changed the Xamarin Forms version to 4.8.0.1821, the navigation works flawlessly.

### Steps to Reproduce

1. Create a Shell project
2. Navigate to the stands

**// Page navigation**
 GoToCommand = new RelayCommand(async () =>
 {
         await Shell.Current.GoToAsync($"{nameof(DetailPage)}?detailtext={this.TextEntry}"); // Navigation works ✔
**or**
         await Shell.Current.Navigation.PushAsync(new DetailPage(this.TextEntry)); // Navigation works✔        
 });

 **// Navigation back**
 GoBackCommand = new RelayCommand(async () =>
 {
         await Shell.Current.Navigation.PopAsync(); // Navigation back does not work when the application crashes ❌
**or**
         await Shell.Current.GoToAsync(".."); // Navigation back does not work when the application crashes ❌ 
 });

### Actual Behavior
Navigation page works, unfortunately reverse navigation no longer works.
After pressing the BACK button, the application will crash.

### Expected Behavior
Navigating back to the page will work as in Xamarin Forms 4.8.0.1821

### Error message
System.ArgumentException: 'Ambiguous routes matched for: //D_FAULT_FlyoutItem4/IMPL_HomePage/HomePage/D_FAULT_DetailPage8/D_FAULT_DetailPage9 matches found: //D_FAULT_FlyoutItem4/IMPL_HomePage/HomePage/D_FAULT_DetailPage8/D_FAULT_DetailPage9,//D_FAULT_FlyoutItem4/IMPL_HomePage/HomePage/D_FAULT_DetailPage8/D_FAULT_DetailPage9 Parameter name: uri'

### Platforms

- [x] Android
- [ ] iOS

### Basic Information
- [Xamarin.Forms 5.0.0.2012](https://www.nuget.org/packages/Xamarin.Forms/5.0.0.2012) 
- Last known good version: 4.8.0.1821 and down
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS: Not tested
  - Android: 10, 8.1, 7.1
  - UWP:  Not tested

### Screenshots
Xamarin.Forms 5.0.0.2012   // Navigation back does not work when the application crashes ❌ 

![](https://i.imgur.com/fxXSKg9.gif)

Navigation works in the Xamarin Forms version  4.8.0.1821 ✔

![](https://i.imgur.com/ttn7DTt.gif)

### Reproduction Link
[ShellNavigationTest.rar](https://filebin.net/nhkar968g5hj7e9m/ShellNavigationTest.rar?t=ctq0geqi)

**Comment by Saxos-Simone** [comment]
I have the same problem.

**Comment by Saxos-Simone** [comment]
@ORRNY66 I've solved!

Try to remove (into **AppShell.xaml.cs**):

~~~
Routing.RegisterRoute(nameof(HomePage), typeof(HomePage));
Routing.RegisterRoute(nameof(SettingsPage), typeof(SettingsPage));
~~~

If pages are registered in **AppShell.xaml**, you must not register them again in **AppShell.xaml.cs**.

**Comment by ORRNY66** [comment]
@Saxos-Simone You're right. Now I looked at it, I accidentally registered it again. Thanks a lot.
