### ISSUE TITLE
How does collectionview disable horizontal scrolling?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14100]
How does collectionview disable horizontal scrolling?

I use effect. It doesn't work

  if (this.Control != null)
            {
              var model=  this.Control as Xamarin.Forms.Platform.Android.GroupableItemsViewRenderer<Xamarin.Forms.GroupableItemsView, Xamarin.Forms.Platform.Android.GroupableItemsViewAdapter<Xamarin.Forms.GroupableItemsView, Xamarin.Forms.Platform.Android.IGroupableItemsViewSource>, Xamarin.Forms.Platform.Android.IGroupableItemsViewSource>;
                model.HorizontalScrollBarEnabled = false;
                 
            }

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
