### ISSUE TITLE
Disable Scrollview scrolling failed.

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14114]
Disable Scrollview scrolling failed.
Here's my custom rendering, or I didn't disable horizontal scrolling

public class ScrollViewCustomRenderer: ScrollViewRenderer
 {

        public ScrollViewCustomRenderer(Context c):base(c) { }
        public override bool OnInterceptTouchEvent(MotionEvent ev)
        {
            
            return false;
        }

        public override bool OnTouchEvent(MotionEvent ev)
        {
            
            return false;
        }

**Comment by rachelkang** [comment]
Hi, @bbhxwl - thanks for submitting this issue. I'm hoping to get a little more context to better understand -
What are you trying to achieve with this custom renderer? Why do you want to use a ScrollView if you don't want it to scroll? Also, what platform are you trying to create this custom renderer for, and are you able to share a full sample? Thanks :)

**Comment by jfversluis** [comment]
No response to our request for more info, closing this for now.
