### ISSUE TITLE
[Bug] Xamarin.Forms 5.0.0.2012 DesignMode.IsDesignModeEnabled is set to true when debugging Android App

### ISSUE THREAD

**Issue by Heinz12** [xamarin/Xamarin.Forms#14118]
### Description

**Xamarin.Forms 5.0.0.2012** & **Visual Studio 2019 V 16.9.3** sets DesignMode.**IsDesignModeEnabled** to **true** when debugging the Android app! 

Debugging UWP is working correctly.

### Steps to Reproduce

1. Create a **Mobile App (Xamarin.Forms)** project from project templates
2. Add following lines of code to **app.xaml.cs** after **InitializeComponent()**;
```
            if (DesignMode.IsDesignModeEnabled) 
                return;
```
 
3. Set a breakpoint on the return statement
4. Select the Android-project and start debugging

### Expected Behavior
Breakpoint should not be hit!

### Actual Behavior
Breakpoint is hit!

### Screenshots

![image](https://user-images.githubusercontent.com/24847652/113842832-60813800-9793-11eb-825a-2a71ca418913.png)

### Workaround

Set a breakpoint to the constructor of the App class and set DesignMode.**IsDesignModeEnabled** to **false** with the debugger
or
Use an older version of Xamarin.Forms (e.g. Version **5.0.0.1931**)

**Comment by Heinz12** [comment]
Test-project see here:  [https://github.com/Heinz12/XFIssueIsDesignModeEnabled](https://github.com/Heinz12/XFIssueIsDesignModeEnabled)

**Comment by Heinz12** [comment]
With the update of **Visual Studio for MAC** to **Version 8.9.6 (build 6)** the problem is the same now for the **iOS-project** but only when deploying to the simulator.
When I deploy to a device (in my case to an iPad) everything is fine.

**Comment by SamuelLioult** [comment]
I have the same issue in VS 2019 v16.9.4

**Comment by bdgza** [comment]
I have updated XF from 4 to 5.0.0.2012 in my project and now also run into this problem debugging for Android – Visual Studio for Mac 8.9.9 (build 3).

**Comment by Heinz12** [comment]
Good News!

With the update to **Visual Studio 2019** Version **16.10.0** the problem is fixed for **Android**!

**Comment by Heinz12** [comment]
Good NEWS!

With the update of **Visual Studio for MAC** to **Version 8.10 (build 1773)** the problem is fixed for **iOS** also!

Thanks!

I will close the issue now! :-)
