### ISSUE TITLE
Page OnActivated

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#14116]
Hi,

Please add OnActivated event for ContentPage which will be fired for example when we navigate from the app to open another app and then open the Xamarin Forms app again because currently there is no such event that helps in this.

Thanks,
Jassim

**Comment by rachelkang** [comment]
Hi, @jrahma - you can achieve this by overriding the [OnAppearing](https://docs.microsoft.com/dotnet/api/xamarin.forms.page.onappearing?view=xamarin-forms#Xamarin_Forms_Page_OnAppearing) method in the page of your choice. Hope this works for your case!

**Comment by jfversluis** [comment]
A suggestion has been given and nothing much will happen in this regard for Xamarin.Forms. For .NET MAUI lifecycle events should be much better so please check that out and let us know there if there is still something you're missing.

Thanks!
