### ISSUE TITLE
Failed to resolve “Xamarin.Forms.Platform.iOS.WebViewRenderer” after upgrading to Xamarin.Forms 5.0.0.2012

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#14120]
I just upgraded to Xamarin.Forms 5.0.0.2012 (from 4.2.0.815419) and when trying to build the iOS project I get the following error:

`Error MT2002: Failed to resolve "Xamarin.Forms.Platform.iOS.WebViewRenderer" reference from "Xamarin.Forms.Platform.iOS, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null" (MT2002)`

I am not using any references to WebViewRenderer anywhere. 

IDE:
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.9.4 (build 25)
Installation UUID: b71efeec-247c-4dbf-8031-d9c70a88a408
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
	5.0.201
	5.0.102
	5.0.101
	3.1.407
	3.1.405
	3.1.404
	3.1.402
	3.1.202
	3.1.102
	3.1.101
	2.2.300
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.4
	5.0.2
	5.0.1
	3.1.13
	3.1.11
	3.1.10
	3.1.8
	3.1.4
	3.1.2
	3.1.1
	2.2.5
	2.1.23
	2.1.22
	2.1.18
	2.1.15
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.407

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.9.0.316
Hash: 2241b204a
Branch: tags/vsm-rel/d16.9-4540908
Build date: 2021-03-10 21:18:10 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Enterprise)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/nielscup/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/nielscup/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9~2
Build date: 2021-03-24 08:30:26 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-03-24 08:30:44 UTC

=== Apple Developer Tools ===

Xcode 12.4 (17801)
Build 12D4e

=== Xamarin.Mac ===

Version: 7.8.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

=== Xamarin.iOS ===

Version: 14.14.2.5 (Visual Studio Enterprise)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

=== Build Information ===

Release ID: 809040025
Git revision: 5d0f80a4343884101c6c7869bc61d5101cf30052
Build date: 2021-03-25 08:43:13-04
Build branch: release-8.9
Xamarin extensions: 5d0f80a4343884101c6c7869bc61d5101cf30052

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by rachelkang** [comment]
Hi, @nielscup - thanks for submitting this issue. Would you be able to share your project or a sample project reproducing the issue so that we can take a closer look? Thanks :)

**Comment by jfversluis** [comment]
No response for a long time, this is probably due to the breaking change of removing the UIWebViewRenderer and replacing it with the WKWebViewRenderer. I assume that some aggressive cleaning and rebuilding was the solution here :)

**Comment by nielscup** [comment]
Yes solved, the answer is here: https://stackoverflow.com/questions/66987291/failed-to-resolve-xamarin-forms-platform-ios-webviewrenderer-after-upgrading-t/66998665#66998665
