### ISSUE TITLE
[Android] Issue for triggering an event when the ActionBar's back button is being tapped

### ISSUE THREAD

**Issue by toussam** [xamarin/Xamarin.Forms#1413]
### Description

I am trying to trigger an event when the user is tapping on the ActionBar's back button. After some research, I found out that I have to overwrite the method OnOptionsItemSelected into my MainActivity, but when the MainPage is set with a MasterDetailPage, this last one is not being called.

For information, I am also overriding the OnPostCreate method to call SetSupportActionBar since that I am using FormsAppCompatActivity and that the loaded toolbar was null if it was loaded into the OnCreate one.

### Steps to Reproduce

1. Set a breakpoint into MainActivity, line 36
2. Launch the application
3. Click on the "CLICK HERE" button to be redirect to the SecondPage
4. Click on the ActionBar's back button

### Expected Behavior

The breakpoint shoud be fired.

### Actual Behavior

The breakpoint is not being fired when doing so.

### Basic Information

- Version with issue: 2.4.0.280
- IDE: Visual Studio 2017
- Android Target Framework: minSdkVersion is the 15th and the used one is the 26th
- Android Support Library Version: v25.4.0.2

### Reproduction Link

https://github.com/toussam/BackButtonIssueSample

**Comment by toussam** [comment]
Hi Samantha, hi Jason,

Is there any news about this enhancement ? I saw that it was added to the backlog before being removed from it.

Thank you in advance for your response and wish you a great day !
Best regards,
Mathias

**Comment by jfversluis** [comment]
Hey there! So sorry this never received a response, that is not really great... It seems that there isn't a lot of traction here and together with the fact that Xamarin.Forms is now in maintenance mode, I will be closing this one. Hope you get a chance to check out .NET MAUI!
