### ISSUE TITLE
[Bug] click outside the stack

### ISSUE THREAD

**Issue by vitaliy5zayats** [xamarin/Xamarin.Forms#14138]
### Description

There are many examples where an element is placed outside its own stack. For [example](https://youtu.be/8_KOYirQzcw?t=2019) - if you add a click event handler to the "Add to Bookmark" button, then a click outside the stack does not give any reaction.

This problem is very limiting when designing an interface.

**Comment by rachelkang** [comment]
Hi, @vitaliy5zayats - I'm not quite sure I understand the issue you're describing. Would you be able to elaborate a bit more and perhaps share a sample project that reproduces the issue as well? Thanks :)

**Comment by jfversluis** [comment]
No response to our request for more info, so assuming this is figured out, thanks!
