### ISSUE TITLE
Crash on fast scrolling (re-use cells) Tableview  with edit objects like Entry/Date fields

### ISSUE THREAD

**Issue by mnidhk** [xamarin/Xamarin.Forms#1414]
### Description

Current Project Updated to 2.5(from 2.4) and when fast scrolling (So when re-use cells is going on) in a tableview with different edit components like entry en date fields.

Everytime hard crash on iOS in Main.cs: Specified cast is not valid.
Test Project included :
A normal tableview where objects are generated onto it

### Steps to Reproduce

1. Open/run test project
2. Scroll quickly the tableview
3. Crash every time on iOS

### Expected Behavior

No crash when scrolling quickly in a tableview with Entry (en other Edit) fields

### Actual Behavior

The app is always crashing when fast scrolling the tableview
Error occurred :
System.InvalidCastException has been thrown
Specified cast is not valid

Looks like the reuse from Cells is not working correctly

### Basic Information

- Version with issue:
 2.4.0.91020 - OK
 2.5.0.77107 - Crash
 2.5.0.91635 - Crash
 2.5.0.121934 - Crash

- Last known good version:
 2.4.0.91020

- IDE:
VS Mac 7.3 (Build 799)
- Platform Target Frameworks: 
Xamarin.forms
  - iOS:  11.2
- Affected Devices:
Simulator + Real devices

### Reproduction Link

Testproject + Screen recording simulator (Same happens on real device)
https://we.tl/1R0nY72TS3

**Comment by davidortinau** [comment]
I've tested this again in the nightly build and can no longer reproduce the crash with the provided code. 2.6.0.211236-nightly
