### ISSUE TITLE
Horizontal collectionview sets collectionview vertical.   

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14153]
Horizontal collectionview sets collectionview vertical.

Simulate multiple choice questions, as if the collection view interface generated by the loop will be reused?

Please watch the video. If the text of the collectionview 2 loop is the same, will it be reused? And the selection state will be reused?

[IMG_0910.zip](https://github.com/xamarin/Xamarin.Forms/files/6309581/IMG_0910.zip)

**Comment by rachelkang** [comment]
Hi, @bbhxwl - thanks for submititng this issue. Would you be able to share your project or a sample project / sample code that reproduces the issue?

If you want your CollectionView to be rendered horizontally, make sure you're setting `ItemsLayout="HorizontalList"` as specified in our docs [here](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/collectionview/layout#horizontal-list).

I'm a bit confused about your questions regarding the loop and selection state - would you mind elaborating a bit more? In the meantime, here are our [docs on CollectionView selection](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/collectionview/selection) that you may find helpful.

**Comment by jfversluis** [comment]
No response to our request for more info, closing this for now.
