### ISSUE TITLE
Items are not appearing in the view when adding at the runtime only in MacOS platform

### ISSUE THREAD

**Issue by saiganeshls2504** [xamarin/Xamarin.Forms#14155]
### Description
Items are not appearing in the view of the SfListview when updating the ItemsSource at the runtime only in MacOS platform. It happens after updating above version of Xamarin.Forms 4.8 onwards.

In the SfListView, we have used the ScrollView to handle scrolling. When updating the ItemsSource at run time, we will reset the ScrollOffset and programmatically scroll the ScrollView using **ScrollToAsync** method. After XF 5 update, the updated items are not came to the view, if we programmatically scroll the view. 

The following is our code snippet to reset the ScrollOffset,

```csharp
        internal void ResetOffset()
        {
            
            this.ScrollOffset =0;

            if (Device.RuntimePlatform != Device.macOS)
            {
                this.ScrollOwner.ScrollToAsync(0, 0, false);
            }
            else
            {
                this.ScrollOwner.ScrollToAsync( 0, ScrollView.Height, false);
            }
        }
```

We have passed the **ScrollView.Height** as **y** parameter and it worked fine until XF 4.8. But, after XF 5, this caused the reported issue as mentioned. 

Also, if we used the below code for macOS then it works fine in XF 5 but not in XF 4.8 or below.

`this.ScrollOwner.ScrollToAsync( 0, 0, false); `

The problem here is, we have used XF 4.5.0.617 for SfListView. But, when updating the sample which used SfListView to XF 5, we are facing the item disappearing issue.

Could anyone please help us to resolve the mentioned issue? Any help would be appreciated.

### Steps to Reproduce

1. Run the sample.
2. click the "Change ItemsSource"
3. Item does not appears in the view.
4.Now scroll the view, item will appear now

### Expected Behavior
New items should be added in the View.

### Actual Behavior
It does not appears umtil the view is scrolled.

### Basic Information
- Version with issue: XF 5.0 and greater
- Good known version: XF 4.8 and lower
- Affected Devices: MacOS

Visual Studio for Mac: === Visual Studio Community 2019 for Mac ===

 

Version 8.9 (build 1651)
Installation UUID: d75baf9c-8299-4afc-a5d9-8165fc70378d
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

 

    Package version: 612000122

 

=== Mono Framework MDK ===

 

Runtime:
    Mono 6.12.0.122 (2020-02/c621c35ffa0) (64-bit)
    Package version: 612000122

 

=== Roslyn (Language Service) ===

 

3.9.0-5.21112.8+f3ff04378c972d435826e6181de364b3c0db8d14

 

=== NuGet ===

 

Version: 5.8.0.6860

 

=== .NET Core SDK ===

 

SDK: /usr/local/share/dotnet/sdk/5.0.201/Sdks
SDK Versions:
    5.0.201
    3.1.406
    3.1.101
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

 

=== .NET Core Runtime ===

 

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    5.0.4
    3.1.12
    3.1.1
    2.1.23
    2.1.15

 

=== .NET Core 3.1 SDK ===

 

SDK: 3.1.406

 

=== Xamarin.Profiler ===

 

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

 

=== Updater ===

 

Version: 11

 

=== Xamarin Designer ===

 

Version: 16.9.0.316
Hash: bd2705417
Branch: remotes/origin/d16-9
Build date: 2021-02-24 00:16:08 UTC

 

=== Apple Developer Tools ===

 

Xcode 12.4 (17801)
Build 12D4e

 

=== Xamarin.Mac ===

 

Version: 7.8.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:43-0500

 

=== Xamarin.iOS ===

 

Version: 14.14.2.5 (Visual Studio Community)
Hash: 3836759d4
Branch: d16-9
Build date: 2021-02-10 17:56:44-0500

 

=== Xamarin.Android ===

 

Version: 11.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d16-9/f908d16
Android SDK: /Users/syncfusion/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        8.1 (API level 27)

 

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

 

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@1d382be
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.32.2@cfe06e0
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@ad80a42

 

=== Microsoft OpenJDK for Mobile ===

 

Java SDK: /Users/syncfusion/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

 

=== Android SDK Manager ===

 

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:14:56 UTC

 

=== Android Device Manager ===

 

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/d16-9
Build date: 2021-02-18 03:15:18 UTC

 

=== Build Information ===

 

Release ID: 809001651
Git revision: c05b1dec4362b5956d47624a437e900ffdc9aa0a
Build date: 2021-02-25 11:27:51-05
Build branch: release-8.9
Xamarin extensions: c05b1dec4362b5956d47624a437e900ffdc9aa0a

 

=== Operating System ===

 

Mac OS X 10.15.7
Darwin 19.6.0 Darwin Kernel Version 19.6.0
    Tue Jan 12 22:13:05 PST 2021
    root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

### Reproduction Link
[ReproduceSample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/SfListView169309616)

**Comment by nacompllo** [comment]
Until this root error is resolved, you can provide a .nupkg with the code this.ScrollOwner.ScrollToAsync( 0, 0, false); added in that condition? You do not need to distribute it through the official Syncfusion channel, just insert it in this same GitHub thread as a downloadable file for customers using Xamarin.Forms 5.0 versions, we can install it and continue working without this error.

**Comment by jfversluis** [comment]
Note for future self: this is happening because of https://github.com/xamarin/Xamarin.Forms/pull/12721

When I revert that it starts working again.

**Comment by jfversluis** [comment]
In #12721 we removed a variable from how the scroll position was determined. I think this fix was the right one, the problem we are seeing right now is that basically you on your side @saiganeshls2504 have implemented a workaround for our code that wasn't working correctly.

I don't see any way to fix this on our side without reintroducing the original bug or break other functionality, unless I add some new property to restore the legacy code and add that back. Do you have any options on your side? Like fix this code on your side and make the minimum dependency on Forms the version with this fix?

**Comment by LakshmiNatarajan21** [comment]
Hi @jfversluis ,

Thank you for the details. We have fixed the reported scenario in the SfListView source.

Regards,
Lakshmi

**Comment by jfversluis** [comment]
Perfect, thanks for letting me know!
