### ISSUE TITLE
[Spec] Shell flyout OnFlyoutMoving

### ISSUE THREAD

**Issue by Cfun1** [xamarin/Xamarin.Forms#14169]
# [The feature] 
Add a possibility to detect when the Shell flyout is sliding/moving from it open/close position.
Currently `IsPresented` property allows only to know about the flyout position at 0% (false-closed) and 100% (true-opened).

# API
### Events
| API | Description |
| ------------- | ------------- |
| OnFlyoutMoving| Triggered whenever the flyout is moving (swiping? sliding?) from it close or open position, either by swipe gesture or by clicking on the flyout icon|
 
### FlyoutSwipingEventArgs 
| API | Description |
| ------------- | ------------- |
| OpenedPercentage | Returns the amount of opening of the flyout in percentage [0-1] [0-100] |
| Direction| Based on last `OpenedPercentage`, is it going in the opening direction or in the closing direction.<br/>**IsClosing**<br/>**IsOpening** |
| TriggerMode|  **Swipe**(manual) Triggered by a swipe gesture<br/>**IconClick** Triggered by clicking on the flyout icon or click on the backdrop while opened. <br/>**Unknown**? Triggered from programmatically? |
 
# Scenarios
Do an animation, trigger some logic, act on ui element or reorganize the elements on the page...

## C# Example
```csharp
void OnFlyoutSwiping(FlyoutSwipingEventArgs args)
{
   if (args.OpenedPercentage > 0.6 && args.Direction.IsClosing)
       //act on a ui element, scale, translate, fade or trigger something
}
```

# Difficulty : [low/medium/high]

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
