### ISSUE TITLE
While using Accessibility(Talk Back) on Popup in Android, Can't able to listen swipe notification in xamarin forms popup. [Bug] 

### ISSUE THREAD

**Issue by PradhapPalani** [xamarin/Xamarin.Forms#14168]
### Description

Greetings,
I have attached framework popup (DisplayAlert popup) sample. I want to listen left swipe or right swipe notification from any view for the purpose to change accessibility focus order. Please can you tell how can we  listen Left swipe and Right swipe notification in Xamarin forms popup. 

### Steps to Reproduce

1. Run the attached sample
2. Click the button to open Popup
3. Swipe left from the Header or  Swipe right from the footer.

### Expected Behavior

Listen left swipe and right swipe notification in the popup view.

### Actual Behavior

When accessibility is On, Can't able to listen left swipe and right swipe notification from the view.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: Android

### Recordings

[Edited_20210416_113842.zip](https://github.com/xamarin/Xamarin.Forms/files/6322890/Edited_20210416_113842.zip)

### Reproduction Link

Please find the display alert  sample link: 
[Popup.zip](https://github.com/xamarin/Xamarin.Forms/files/6316869/Popup.zip)

**Comment by rachelkang** [comment]
Hi, @PradhapPalani - thanks for submitting this issue! If your main goal is to manipulate the accessibility focus order, I suggest you to check out https://github.com/PureWeen/A11YTools instead. In particular, I think you might find the `SetFocus` API there to be especially helpful. Let me know how it goes, and if you're looking to achieve something that the A11yTools can't help you with!

**Comment by PradhapPalani** [comment]
Hi, @rachelkang 

> Hi, @PradhapPalani - thanks for submitting this issue! If your main goal is to manipulate the accessibility focus order, I suggest you to check out https://github.com/PureWeen/A11YTools instead. In particular, I think you might find the `SetFocus` API there to be especially helpful. Let me know how it goes, and if you're looking to achieve something that the A11yTools can't help you with!

**Comment by PradhapPalani** [comment]
Hi, @rachelkang thank you for the reply and your suggested github repository, but my use case not up to this, my requirement is to get the accessibility on overlay views not on the static views.
My use case is 
1. Enable Talk back in android device
2.  Click the button to add a new View in decorview

**Expected Behavior**
 The accessibility focus automatically comes to added new view in decorview and its supposed to stay only on the added view.
**Actual Behavior**
Accessibility focus stays in background view and  we give accessibility to the new view by manually swipe right from the screen 
Please check this output vedio
[Output.zip](https://github.com/xamarin/Xamarin.Forms/files/6433259/Output.zip)

I want to achieve a DisplayAlert popup behavior . please find the output video and sample attached in the issue.

**Comment by PradhapPalani** [comment]
Hi @rachelkang No, it's the same issue as mentioned in this link -https://github.com/xamarin/Xamarin.Forms/issues/14175.

**Comment by rachelkang** [comment]
thanks for clarifying! I'll be closing this issue since it's a duplicate then, but let's continue chatting at #14175 :)
