### ISSUE TITLE
[Bug] If there are many page controls, the loading will be very slow. How to solve this problem?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14161]
The following page is not very complicated, but when I click the button to jump to this page, I need to wait 1 to 2 seconds,

  

<ContentPage.Content>
        <StackLayout BackgroundColor="#F0F4F7">
            
            <StackLayout BackgroundColor="White" 
                               Orientation="Horizontal">
                <Button x:Name="btnBack" 
                            HeightRequest="50" 
                            WidthRequest="50" 
                            HorizontalOptions="Start" 
                            FontSize="20" 
                            BackgroundColor="White" 
                          Clicked="btnBack_Clicked"
                            >
                    <Button.ImageSource>
                        <OnPlatform x:TypeArguments="ImageSource">
                            <On Platform="iOS, Android" Value="back.png" />
                            <On Platform="UWP" Value="Assets/Images/back.png" />
                        </OnPlatform>
                    </Button.ImageSource>
                </Button>
                <Label x:Name="lbTitle" 
                           HeightRequest="50" 
                           HorizontalTextAlignment="Center" 
                           VerticalTextAlignment="Center" 
                           Text="听觉评估" FontSize="20" 
                           TextColor="Black" 
                           FontAttributes="Bold"
                           />
            </StackLayout>
            <StackLayout  Margin="20,20,20,0" Spacing="20">
                <Label FontSize="25" FontAttributes="Bold" Margin="0,0,0,20">模式设置</Label>
                <StackLayout  HeightRequest="50"  Padding="35,0,15,0"  BackgroundColor="White"
                        Orientation="Horizontal">
                    <Label      FontAttributes="Bold" FontSize="15"   VerticalTextAlignment="Center" Text="模式名称" />
                    <Entry Text="{Binding Name}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="End" Placeholder="请输入模式名称">
                        <Entry.Effects>
                            <Effects:EntryEffect></Effects:EntryEffect>
                        </Entry.Effects>
                    </Entry>
                </StackLayout>
                <StackLayout    Padding="35,20,15,20"  BackgroundColor="White"
                      >
                    <Label    FontAttributes="Bold" FontSize="15"   VerticalTextAlignment="Center" Text="左声频率" />
                    <BoxView HeightRequest="1" Margin="0,10,0,10" BackgroundColor="#ccc"></BoxView>
                    <Grid x:Name="gridLeft">
                        <Grid.RowDefinitions >
                            <RowDefinition/>
                            <RowDefinition/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                        </Grid.ColumnDefinitions>

                        <button:SfButton Grid.Row="0" Grid.Column="0" Text="125 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="0" Grid.Column="1" Text="250 Hz" IsCheckable="True"   />
                        <button:SfButton Grid.Row="0" Grid.Column="2" Text="500 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="0" Grid.Column="3" Text="1000 Hz" IsCheckable="True" />
                        <button:SfButton Grid.Row="0" Grid.Column="4" Text="1500 Hz" IsCheckable="True"  />
                        <button:SfButton Grid.Row="1" Grid.Column="0" Text="2000 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="1" Grid.Column="1" Text="3000 Hz" IsCheckable="True"   />
                        <button:SfButton Grid.Row="1" Grid.Column="2" Text="4000 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="1" Grid.Column="3" Text="6000 Hz" IsCheckable="True" />
                        <button:SfButton Grid.Row="1" Grid.Column="4" Text="8000 Hz" IsCheckable="True"  />

                    </Grid>
                </StackLayout>
                <StackLayout    Padding="35,20,15,20"  BackgroundColor="White"
                      >
                    <Label    FontAttributes="Bold" FontSize="15"   VerticalTextAlignment="Center" Text="右声频率" />
                    <BoxView HeightRequest="1" Margin="0,10,0,10" BackgroundColor="#ccc"></BoxView>
                    <Grid x:Name="gridRight">
                        <Grid.RowDefinitions >
                            <RowDefinition/>
                            <RowDefinition/>
                        </Grid.RowDefinitions>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                            <ColumnDefinition/>
                        </Grid.ColumnDefinitions>

                        <button:SfButton Grid.Row="0" Grid.Column="0" Text="125 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="0" Grid.Column="1" Text="250 Hz" IsCheckable="True"   />
                        <button:SfButton Grid.Row="0" Grid.Column="2" Text="500 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="0" Grid.Column="3" Text="1000 Hz" IsCheckable="True" />
                        <button:SfButton Grid.Row="0" Grid.Column="4" Text="1500 Hz" IsCheckable="True"  />
                        <button:SfButton Grid.Row="1" Grid.Column="0" Text="2000 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="1" Grid.Column="1" Text="3000 Hz" IsCheckable="True"   />
                        <button:SfButton Grid.Row="1" Grid.Column="2" Text="4000 Hz" IsCheckable="True"    />
                        <button:SfButton Grid.Row="1" Grid.Column="3" Text="6000 Hz" IsCheckable="True" />
                        <button:SfButton Grid.Row="1" Grid.Column="4" Text="8000 Hz" IsCheckable="True"  />

                    </Grid>
                </StackLayout>
            </StackLayout>
            
            <Grid Margin="-20,0,-20,0" VerticalOptions="EndAndExpand" HorizontalOptions="Fill" BackgroundColor="White" HeightRequest="60">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="2*"  />
                    <ColumnDefinition  Width="3*" />
                    <ColumnDefinition  Width="2*" />
                </Grid.ColumnDefinitions>
                <button:SfButton x:Name="btnComplete"  Clicked="btnComplete_Clicked"    BackgroundColor="#10BDA9" IsEnabled="True" TextColor="White" Grid.Column="1" Margin="20,5,20,5" Text="下一步"  HeightRequest="50"  CornerRadius="25">
                </button:SfButton>
            </Grid>

        </StackLayout>
    </ContentPage.Content>

**Comment by rachelkang** [comment]
Hi, @bbhxwl - thanks for the question! You can check out these docs on [improving Xamarin.Forms app performance](https://docs.microsoft.com/xamarin/xamarin-forms/deploy-test/performance) for some tips

If you continue facing issues, can you share what platforms and devices you're experiencing the performance issues on? And what version of XF you're using? (I suggest using XF 5 if you aren't on it already!) Lastly, I'd be curious to hear if you're seeing the same issues with XF buttons that are not SfButtons

**Comment by jfversluis** [comment]
No response to our request for more info so closing this one
