### ISSUE TITLE
[Android] SetupPageTransition does not work with PushModalAsync

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1416]
### Description
SetupPageTransition does not work with PushModalAsync

### Steps to Reproduce
Repro: https://www.dropbox.com/s/9gcvrx8gh7e8z3m/PageAnimationSample.zip?dl=0

Load the app, press the "click me" button, note that the page animation loads from the bottom to the top.
Change PushModalAsync to PushAsync and reload the app. Set a breakpoint in the navigation renderer, and press the "click me" button, note that SetupPageTransition gets hit, and the animation is changed to loading the page from the top to bottom.

### Expected Behavior
SetupPageTransition gets hit when using PushModalAsync

### Actual Behavior
SetupPageTransition does not get hit when using PushModalAsync, and the default page translation animation is used.

### Basic Information
Tested against Android O.
Tested using Xamarin forms 2.5.0.121934

Note: This is my first time using GitHub issues, how do I know when this is confirmed, or in progress? Thanks

**Comment by rmarinho** [comment]
Hi, the modal navigation isn't handle by the NavigationPageRenderer as PushModal is a general mechanism that can be used without a NavigationPage.

**Comment by Paul-Brenner-Tangoe** [comment]
@rmarinho 
How are we supposed to do custom page animations using modal navigation ? A normal PageRenderer doesn't have SetupPageTransition.

**Comment by JFMG** [comment]
You can do it as it is described here: https://kernel32.net/2016/06/25/xamarin-forms-transitions.html
by overriding the AddView and RemoveView method

For example:
```csharp
public override void AddView(Android.Views.View child)
{
    base.AddView(child);
    var animation = AnimationUtils.LoadAnimation(Context, Resource.Animation.my_animation);
    animation.AnimationEnd += (sender, e) => child.Animation = null;
    child.Animation = animation;
}
```
