### ISSUE TITLE
[Bug] Shell is confused about current route after being swiped away and restarted if app has foreground service

### ISSUE THREAD

**Issue by trampster** [xamarin/Xamarin.Forms#14162]
### Description
If an app with a foreground service is killed (swiped away on android) while navigated to a modal page (//mypage/mymodal) And the the app is relaunched then the old route is remembered but no longer matches what is shown in the app which is back on the root page.

We have tried bringing the Shell back inline with the app by doing the following but none of it helps:
* Shell.Current.Navigation.PopToRootAsync();
* Shell.Current.GoToAsync("..");
* Shell.Current.GoToAsync("//mypage");
* Shell.Current.SendBackButtonPressed();

### Steps to Reproduce

1. Open app that has foreground service and navigate to a modal Route, in Shell.Current.CurrentState.Location.OriginalString is \\mypage\mymodal
2. Swipe the app away on android (this kills the activity) but foreground service is still running
3. Launch the app, route is still \\mypage\mymodal but mymodal is not shown

### Expected Behavior
When relaunching the Shell state matches the app

### Actual Behavior
The Shell continues to believe that we are on the old route.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: NA
- Platform Target Frameworks: 
  - iOS:  NA
  - Android: Android 10
  - UWP:  NA
- Android Support Library / AndroidX Version: NA
- NuGet Packages:
- Affected Devices: Android

### Environment
```
Microsoft Visual Studio Professional 2019
Version 16.9.3
VisualStudio.16.Release/16.9.3+31129.286
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

ASP.NET and Web Tools 2019   16.9.693.2781
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

C# Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

ForGetVisualStudioPackage   1.0
Extension to do ForGet package restore before builds.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30201.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.9.0-6.21160.10+59eedc33d35754759994155ea2f4e1012a9951e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.9.0.316 (remotes/origin/d16-9@fdbf64026)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.9.68 (8e9b569)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11


Xamarin.iOS and Xamarin.Mac SDK   14.14.2.5 (3836759d4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by trampster** [comment]
We have found one work around which is to deliberately navigate to what Xamarin.Forms thinks the current rout is and then to navigate back.

         ```
// horrible work around for Xamarin.Forms bug #14162
         var parts = Shell.Current.CurrentState.Location.OriginalString.Split('/', StringSplitOptions.RemoveEmptyEntries);
         if (parts.Length > 1)
         {
            await Shell.Current.GoToAsync(Shell.Current.CurrentState.Location.OriginalString);
            await Shell.Current.GoToAsync("..");
            parts = Shell.Current.CurrentState.Location.OriginalString.Split('/', StringSplitOptions.RemoveEmptyEntries);
         }
```

**Comment by trampster** [comment]
On Android foreground services result in the process remaining alive even if the app is swiped away, however you UI is kill and recreated if you launch it again. 

It seems that because the process stays around then Xamarin Shell keeps its original state and does not seem to be aware that the UI was relaunched.

**Comment by rachelkang** [comment]
Hi, @trampster - thanks for submitting this issue, and I'm happy to hear you found a workaround!
Would you mind sharing your project or a sample project reproducing this issue so that we can investigate further? It would be extremely helpful; thank you!

**Comment by trampster** [comment]
So this is a little embarrassing, It turns out this one was our fault not Xamarin.Forms. Our Shell type was registered with out IOC container as a singleton, and so it wasn't getting recreated. We have changed this and now it works fine.

**Comment by rachelkang** [comment]
No worries; I'm glad you were able to figure it out! :)
