### ISSUE TITLE
While using accessibility(TalkBack) on Android, accessibility focus goes to background view.[Bug] 

### ISSUE THREAD

**Issue by PradhapPalani** [xamarin/Xamarin.Forms#14175]
### Description

In forms android, While i turned on accessibility, Accessibility focus stays in background view and focus of TalkBack also goes to background view. Its supposed to stay only on the added view in decorview.
I have replicated issue in simple sample. Please find the sample attached in this issue.

Accessibility focus works fine in  DisplayAlert Popup Please find the display alert sample link.
DisplayAlert sample - [Popup.zip](https://github.com/xamarin/Xamarin.Forms/files/6334243/Popup.zip)

### Steps to Reproduce

1.  Enable Talk back in android device
2. Run the attached sample
3.  Click the button(Click to show Popup) to  add View in decorview
4. Accessibility focus stays in  background view 
5. On swiping, focus goes out of the view from footer.

### Expected Behavior

Need to get accessibility focus for added view and supposed to stay only on added view.

### Actual Behavior

Focus goes to background view as well. 

### Basic Information

Version with issue:
Last known good version:
IDE: VS 2019
Platform Target Frameworks:  Forms Android

### Issue Sample Vedio

[20210419_131259.zip](https://github.com/xamarin/Xamarin.Forms/files/6334136/20210419_131259.zip)

### Reproduction Link

Issue occurs in simple sample - [Popup.zip](https://github.com/xamarin/Xamarin.Forms/files/6334140/Popup.zip)

**Comment by rachelkang** [comment]
Hi, @PradhapPalani - thanks for submitting this issue! I unfortunately wasn't able to reproduce the issue on the sample you shared - is there a different sample? That being said, I think I'm familiar with this issue, and we will continue to investigate it.

**Comment by rachelkang** [comment]
One thing you can try is to implement a custom renderer and set importantForAccessibility to noHideDescendants https://developer.android.com/reference/android/view/View#attr_android:importantForAccessibility

**Comment by PradhapPalani** [comment]
Hi @rachelkang I have replicated the issue in the below attached sample. can you please replicate the issue in the attached  sample.
**Expected Behavior :**  When we click the button to add a new view in the decorView then the accessibility focus immediately comes to new view, like in DisplayAlert Popup.
**Sample :** [Popup.zip](https://github.com/xamarin/Xamarin.Forms/files/6396482/Popup.zip)
**output video :**  
[20210419_131259.zip](https://github.com/xamarin/Xamarin.Forms/files/6396508/20210419_131259.zip)

Issue has been replicated in :  **Mi Android One**  device

**Comment by rachelkang** [comment]
I see it now, thank you!

**Comment by KarthikRaja26** [comment]
hi @rachelkang , 

Any updates ?

**Comment by rachelkang** [comment]
@PradhapPalani thanks for the update! Would you be able to share the Forms sample in which you attempted the SetFocus API?

**Comment by PradhapPalani** [comment]
Hi @rachelkang Only properties have been implemented in Forms, and all of the control's rendering and layouting was done in native Android. Please do not mix up the Forms and Native issues. If you can fix the problem for native Android, we'll be able to easily incorporate it into our controls.

**Comment by PureWeen** [comment]
@LuckyDucko hey that's awesome!!! out of curiosity why not make `AndroidTalkbackAccessibilityWorkaround` true by default?

@PradhapPalani  The behavior you are seeing is how Native Android works and isn't a bug.  In your Native example you're just layering LinearLayouts so android is going to keep navigating to those in the screen reader. If you want things to not show up in the screen reader then you'll need to set ImportantForAccessibility to NO on those elements

**Comment by LuckyDucko** [comment]
@PureWeen to be honest, it was worry over having a breaking change. With iOS devices I can be reasonably confident that my code is going to work on the majority of devices. However, my previous accessibility change worked well on my Samsung galaxy a20 (my test android device), but then on nothing else.

However, you make a good point, I looked through the android developer source and I can't see a reason to not switch it on by default. Once it gets into circulation and all seems good, I think I will.

P.S to you and @rachelkang (and the rest of Xamarin team) keep up the good work 👍

**Comment by KarthikRaja26** [comment]
Hi @PureWeen ,

The provided solution is not a proper way for our issue. Since DisplayAlertPopup is working fine without setting ImportantForAccessibility as No for unwanted things. So, could you please tell us how the DisplayAlertPopup keeps the focus while swiping because it will help us to implement the same thing in our side and reopen this issue?

Regards,
Karthik Raja

**Comment by KarthikRaja26** [comment]
Hi @PureWeen ,

Any update for this ?
