### ISSUE TITLE
[Bug] Color.Defult.MultiplyAlpha(0.30).ToAndroid() is crashing the app

### ISSUE THREAD

**Issue by luismts** [xamarin/Xamarin.Forms#14173]
### Description
`Color.Defult.MultiplyAlpha(0.30).ToAndroid()` is crashing the app.

### Steps to Reproduce

1. Go to the MainActivity in your Xamarin.Forms Android project.
2. Go to `OnCreate(Bundle savedInstanceState)` method.
3. Add the following code:
```
var color = Xamarin.Forms.Color.Default;
color.MultiplyAlpha(0.30).ToAndroid();
```

### Expected Behavior
Add a default color modifying the alpha.

### Actual Behavior
The app is crashing.

### Basic Information

- Version with issue: 5.0.0.2012
- Platform Target Frameworks: 
  - Android: Android 9 - API 28

### Build Logs
Default color is:
`R=-1, G=-1, B=-1, A=-1, Hue=-1, Saturation=-1, Luminosity=-1`

**Comment by rachelkang** [comment]
On second thought, after chatting with @mattleibow - something to keep in mind here is that `Xamarin.Forms.Color.Default` is not an actual color, but just a placeholder. It's determined by the control that consumes it

**Comment by mattleibow** [comment]
One example of this is that a Button has a "Default" color for text, background, border and everything else. There is also a `IsDefault` property that you can use to quickly test to make sure that if it is a `Default` color, then you can swap out for whatever you want it to really be.

**Comment by luismts** [comment]
So, the expected behavior is correct? And the implementation is what we need to care about it?

I'm reporting this because XF-Material-Library with the latest version is experimenting with some issues with this code. I also report the issue in their repo; you can see it [here](https://github.com/Baseflow/XF-Material-Library/issues/425).

**Comment by Redth** [comment]
Yes I believe this is expected.  In MAUI we are looking at nullable Color so that the 'default' is instead null and not a 'placeholder'

**Comment by luismts** [comment]
Ok, I'm closing this issue. 

Thanks @Redth
