### ISSUE TITLE
Can not use Safe area in xamarin.android

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#14179]
I want to the status bar be transparent 
`Window.AddFlags(WindowManagerFlags.TranslucentStatus);`

![image](https://user-images.githubusercontent.com/46642851/115143447-ef3a6280-a079-11eb-80a6-ac349b232de6.png)

I am using xamarin.forms Shell android.

**Comment by jpobst** [comment]
I think XF may affect this, assigning to them to check first.

**Comment by mcguu** [comment]
the issue have been post since 18 Aug 2020 · 22 but never be fixed.

nearly 8 months past.

I have to tell you @jpobst 

yes it is XF Shell which affect this they do not want to fix it.

**Comment by rachelkang** [comment]
Hi, @mcguu - thanks for submitting this issue. I'm closing as it's a duplicate of the issue you mentioned https://github.com/xamarin/Xamarin.Forms/issues/11828. We'll take a look as soon as we get the chance - in the meantime, please check out the workaround shared there if you haven't already!

**Comment by mcguu** [comment]
@rachelkang  I have gave up of it but thank you  Mrs kang

**Comment by mcguu** [comment]
@rachelkang  As you can see. 8 days past and nothing changed.
