### ISSUE TITLE
[Enhancement] Composite Shape/Path support

### ISSUE THREAD

**Issue by vanka78bg** [xamarin/Xamarin.Forms#14189]
## Summary

The current API for `Shape`s and `Path`s covers the most basic scenarios for retained mode drawing in Xamarin.Forms. There is a certain limitation in the current API however, preventing us from drawing more sophisticated graphics with multiple brushes or strokes. For instance, consider the following pie chart in the screenshot:

![PieChart-CustomScale](https://user-images.githubusercontent.com/1614598/115386618-4b1ffb00-a1e2-11eb-923b-b0e1adcfff69.png)

Currently the `Shape` class and its inheritors support only a single `Stroke` and `Fill` brush. For this reason, the above pie chart is composed of several `Path`s, each with its own `Stroke` and `Fill`. The problem arises when we try to fit the drawing to the available space in the layout. For a single `Shape` or `Path` we can specify `Fill` or `Uniform` for the `Aspect` property. This des not quite work, when the current drawing is composed of multiple `Shape`s or `Path`s however:

![PieChart-UniformScale](https://user-images.githubusercontent.com/1614598/115387682-aa323f80-a1e3-11eb-97ee-2745c625c9ac.png)

The individual `Path`s are scaled separately, which does not look as expected. My current workaround is to handle the `SizeChanged` event of each individual `Path` like this:

```csharp
private void OnPathSizeChanged(object sender, EventArgs eventArgs)
{
    var path = (Path)sender;

    path.RenderTransform = new ScaleTransform
    {
        // TODO: Compute the actual scale factor somehow...
    };
}
```

The above solution is very inconvenient for complex drawings and computing the correct scale factor might not be so trivial in some cases.

Another problem when using multiple `Shape`s or `Path`s is that each one of them is a separate `View`, so if we have a lot of drawing primitives, the performance would suffer.

What we need is a mechanism to treat multiple `Shape`s and `Path`s as a whole entity, so that we can fit them in the layout together.

## API Changes

I am not the right person to give a very clean API proposal. Here is my initial (draft) suggestion however:

```xml
<CompositePath>
    <CompositeGeometry Rect="10, 20, 30, 40" Stroke="Black" Fill="Red" Data="..." />
    <CompositeGeometry Rect="50, 60, 70, 80" Stroke="Yellow" Fill="Blue" Data="..." />
</CompositePath>
```

The intent of the above XAML markup is to specify a composite path with multiple geometries, each having its own `Stroke` and `Fill` properties.

Another option is to avoid adding new classes to the library, but to expose a single `RenderBounds` property to the `Path` class. The intended usage of this property is to specify the bounding rectangle of the `Path` explicitly, rather than computing it from the individual `PathFigure`s and `PathSegment`s. This way, if we have multiple `Path`s grouped together in the same layout container, we can specify the same `RenderBounds` for all of them, so that setting the `Aspect` property to `Fill` or `Uniform` would work as expected. This approach has the disadvantage that each `Path` is a separate `View`, so the performance would not be as good as my previous suggestion however.

Of course, none of the above proposals can be considered a very clean API. I am open to suggestions what a good API to handle this scenario might look like.

## Intended Use Case

The intended use case for this feature is to allow drawing complex `Shape`s and `Path`s, composed of multiple primitives with different `Stroke`s, `Fill`s etc. Common examples are charts, gauges, busy indicators, emojis etc.

Attached to this issue you can find a small sample app demonstrating the use case:

[MultiShapeApp.zip](https://github.com/xamarin/Xamarin.Forms/files/6343284/MultiShapeApp.zip)

**Comment by gxrsprite** [comment]
In wpf, is is easy, Just use ViewBox.
[https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.viewbox?view=winrt-19041](url)
But in Xamarin.Forms, difficulty.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
