### ISSUE TITLE
[Bug] Path with ArcSegment is not smooth when upscaled

### ISSUE THREAD

**Issue by vanka78bg** [xamarin/Xamarin.Forms#14187]
### Description

It seems that the `ArcSegment` is rendered as series of connected lines. The problem occurs when the initial `ArcSegment` is relatively small, but needs to be upscaled when specifying `Fill` or `Uniform` for the `Aspect` property of the `Path`. Apparently, the `ArcSegment` computes how many connected lines to draw based on its size, however it does not take into account that it can be upscaled or downscaled later, leading to an incorrect rendering.

### Steps to Reproduce

The following XAML markup can be used to reproduce the problem:

```xml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="400" />
    </Grid.RowDefinitions>
    <Path Aspect="Uniform" Stroke="Black" Data="M 0,2 A 2,2 0 1 1 2,4" />
</Grid>
```

Attached to this issue you can find a sample test project, which can also be used to reproduce the same problem.

### Expected Behavior

The `ArcSegment` should appear as a smooth arc on the screen.

### Actual Behavior

The `ArcSegment` appears as series of connected lines on the screen.

### Basic Information

Xamarin.Forms version: 5.0.0.2012

### Environment

Visual Studio 2019 version: 16.9.4

### Screenshots

Here is a screenshot to get an idea how this looks:

![ArcSegment-Scaled](https://user-images.githubusercontent.com/1614598/115384030-3857f700-a1df-11eb-9880-42221a982040.png)

### Reproduction Link

The following sample project can be used to reproduce the problem:

[ShapeApp.zip](https://github.com/xamarin/Xamarin.Forms/files/6342840/ShapeApp.zip)

### Workaround

The current workaround I use is to accommodate the coordinates used in the path, so that they are close to the actual screen coordinates, thus only minimal upscaling or downscaling is performed. This is not very convenient however, because the actual path coordinates are typically produced by a vector drawing program, which might have a different coordinate system, not necessarily in pixels (e.g. inches, centimeters etc.), so the actual coordinates are often small fractional numbers.

**Comment by rachelkang** [comment]
Hi, @vanka78bg - thanks for submitting this issue. You mention ArcSegment, but I'm not seeing it reflected in the XAML and sample you shared. If you're interested in using ArcSegment and the smooth path it can render, check out the docs and sample code [here](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/shapes/geometries#create-an-arcsegment). I hope this helps, but let me know if I'm misunderstanding your issue!

**Comment by jfversluis** [comment]
No response to request for more info, closing this for now.
