### ISSUE TITLE
[Bug] Navigation.PushAsync() can be called multiple times in succession

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/Xamarin.Forms#14181]
### Description

The usage for `Navigation.PushAsync()` shown pretty much everywhere looks like this:

```
private async void OnButtonClicked(object sender, EventArgs e)
{
    await Navigation.PushAsync(new SomeOtherPage());
}
```

However, this usage is **incorrect**. The problem is that the user can hit the button quickly twice in succession, causing `PushAsync` to be called twice. Then when they hit the back button, they'll be redirected to the same page they're on _(also, if loading the page has other side-effects, those side-effects will occur twice)_.

The "correct" way to call `PushAsync` should then look something like this:

```
private async void OnButtonClicked(object sender, EventArgs e)
{
    if(!_isPageTransitioning)
    {
        _isPageTransitioning = true;
        await Navigation.PushAsync(new SomeOtherPage());
        _isPageTransitioning = false;
    }
}
```

The developer needs to do this _everywhere_ `PushAsync` is called.

There's little-to-no use-case to queue up a second transition before the first transition is even complete.  Even if there were, the **default** case should clearly be to disallow it, so developers don't need to write code like above.

Thus, the above workaround should actually be handled by the framework.

### Workaround

```
public static class NavigableElementExtensionMethods
{
    private static bool _isPageTransitioning;

    public static async Task NavigateTo(this NavigableElement currentPage, Page newPage)
    {
        if (!_isPageTransitioning)
        {
            _isPageTransitioning = true;
            await currentPage.Navigation.PushAsync(newPage);
            _isPageTransitioning = false;
        }
    }
}
```

**Comment by jgoyvaerts** [comment]
This is not a framework bug. You should have a way of handling double taps in your application, regardless if the tap causes a PushAsync or not.
For example, if your button performs an action (sending an email, showing an animation, opening a visual element, changing the color of something), you rarely want that action to happen twice when the user accidentally double taps the button. So try solving this from the button perspective, not from the PushAsync perspective.

**Comment by rachelkang** [comment]
Hi, @BlueRaja - thanks for submitting this issue. As @jgoyvaerts mentioned, this is not a framework bug - however, I will convert this to an enhancement request for us to consider.

**Comment by jfversluis** [comment]
Not a framework bug and not something that will make its way into Xamarin.Forms anymore. Thank you all for your input!
