### ISSUE TITLE
[Enhancement] Allow interfaces in x:DataType

### ISSUE THREAD

**Issue by salgiza** [xamarin/Xamarin.Forms#14191]
## Summary
I have lots of reusable XAML controls/contentviews that apply to interfaces. Currently, this means that x:DataType can't be used to validate them/add Intellisense capabilities, as interfaces can't be selected.

## API Changes

No API changes, as such, are required.

## Intended Use Case
This is a real example, and I could give you several more: I have an app that stores several types of documents. Each document has some common fields (id, title, ...) but each one adds several extra properties that are particular for them. I have reusable ContentViews that are used to show/format some information for this commons fields, that are defined in an interface that all documents (classes) implement.

Note: it has to be an interface, because documents are stored using Realm, and creating a base C# class is not an option (any class that is stored in Realm has to directly extend RealmObject).

**Comment by GalaxiaGuy** [comment]
When you say "interfaces can't be selected" what do you mean? I've used interfaces in `x:DataType` before and not had any problems (and intellisense seems to work fine).

I made a quick sample here:

https://github.com/galaxiaguy/xf-bugs/tree/test/interface-datatype

**Comment by salgiza** [comment]
Wow! I thought that this was something that was missing in Xamarin, but then it just seems to be a bug in Visual Studio for macOS.

I just downloaded your project, and it works as intended, but VS does not show the interface as an option when I autocomplete the DataType. 

![CleanShot 2021-04-22 at 13 49 58](https://user-images.githubusercontent.com/6630306/115709585-aaf8dc00-a371-11eb-858b-e620f2486469.png)

As the option was not there, and I'm having a similar problem with generics, I thought that it was also a current limitation of the attribute 🤦🏻‍♂️

**Comment by GalaxiaGuy** [comment]
I suppose the question then becomes, where should "intellisense does not suggest interfaces in `x:DataType`" be reported?

**Comment by salgiza** [comment]
Hehehe, yeah, I must admit that, after I wrote my previous message, I stared for a while at the screen with that exact question in my mind.

I've decided to report it using the option to report bugs in VS for macOS, and I'll see where it goes from there...
https://developercommunity.visualstudio.com/t/intellisense-does-not-show-interfaces-when-autocom/1405793

Thanks a lot, @GalaxiaGuy !

**Comment by Dids** [comment]
The linked issue was closed and not fixed.

Is there anything that can be done about this, or do we just have to accept that this is how it is, and I'll likely never be fixed?
