### ISSUE TITLE
[Bug] Xamarin Forms UWP custom renderers are not working in release mode.

### ISSUE THREAD

**Issue by rajeshangappan** [xamarin/Xamarin.Forms#14207]
### Description
UWP custom renderers are not working in release mode.
Hi team, 
   In xamarin forms UWP, custom renderer assemblies are not loading properly. After a long check i found the workaround.
### Workaround
*workaround**: (https://stackoverflow.com/questions/54999336/xamarin-uwp-runtime-error-in-release-mode)
// You'll need to add using System.Reflection;
List<Assembly> assembliesToInclude = new List<Assembly>();
// Now, add in all the assemblies your app uses
assembliesToInclude.Add(typeof (ClassInOtherAssembly).GetTypeInfo().Assembly);
// Also do this for all your other 3rd party libraries
Xamarin.Forms.Forms.Init(e, assembliesToInclude);
### Expected Behavior
It should be work without workaround
### Actual Behavior
custom renderer assemblies not loading.
### Basic Information
Xamarin Forms UWP

**Comment by jsuarezruiz** [comment]
Is this troubleshooting section helping in this case? here https://docs.microsoft.com/en-US/xamarin/xamarin-forms/platform/windows/installation/#troubleshooting

**Comment by jfversluis** [comment]
No response, assuming the author has resolved this. Closing for now!
