### ISSUE TITLE
How to capture image in camera using Xamarin UITest automation?

### ISSUE THREAD

**Issue by DKumar91** [xamarin/Xamarin.Forms#14200]
I am trying to automate my android app on emulator using Xamarin UITest libraries. I am stuck on automating the camera functionality in my app. When I use app.Repl() console, it shows nothing but the below line:
[[object CalabashRootView]].
I assume this is because my app using the emulator camera as there is not inbuilt app camera. Please suggest me with any code snippet or documentation on how to achieve this?

Xamarin UITest Version: 3.0.15
.Net Framework: 4.8

**Comment by rachelkang** [comment]
Hi, @DKumar91 - thanks for submitting this question! Unfortunately, there's currently no way to automate a camera's photo capturing. However, you can [screenshot](https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.iapp.screenshot?view=xamarin-uitest-sdk) or [load photos](https://forums.xamarin.com/discussion/146013/xamarin-uitest-working-with-photo-capture-and-images-in-uitest-automation) in - More specifically, one idea to test out is to add a camera view and then grab a screenshot! Hope this helps :)

**Comment by jfversluis** [comment]
As far as I know accessing the camera is not something that is supported. Let me know if you did find something by now because I would be interested! :)
