### ISSUE TITLE
[Bug] Xamarin.Forms.Maps - Pin.SendMarkerClick() not implemented

### ISSUE THREAD

**Issue by joeweininger** [xamarin/Xamarin.Forms#14211]
### Description

Pin.SendMarkerClick() is not implemented. Are there any plans to implement this in future releases?

using System.ComponentModel;
/// <summary>To be added.</summary>
/// <returns>To be added.</returns>
/// <remarks>To be added.</remarks>
[EditorBrowsable (EditorBrowsableState.Never)]
public bool SendMarkerClick ();

### Steps to Reproduce

1. Create a Pin
2. Call the SendMarketClick() method of that pin
3. Nothing happens

### Expected Behavior
Firing the SendMarketClick method should open the pin info window.

### Actual Behavior
nothing happens.

### Basic Information

- Version with issue: Xamarin Forms 5.0.0.2012
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  v12-v14
  - Android: v6-v11
  - UWP:  N/A
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms.Maps
- Affected Devices: All

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by rachelkang** [comment]
Hi, @joeweininger - thanks for submitting this issue. `Pin.SendMarkerClick()` is implemented, but it's behavior is different from what you described. It just returns a bool as specified [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps.pin.sendmarkerclick?view=xamarin-forms).

Anyhow, I see you opened a PR! Thank you for your contribution - we'll be sure to take a look :)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
