### ISSUE TITLE
[Enhancement] Wrapping Xamarin.Forms application into WPF UserControl

### ISSUE THREAD

**Issue by magres** [xamarin/Xamarin.Forms#14216]
## Summary
Hi everyone. I faced a legacy industrial system based on WPF, it could be extended with UserControls. At the moment there's only a WPF Window wrapper, but UserControl wrapper is requested by me. 
Or please point me out how to do it by myself. Thanks in advance.

## API Changes

Add classes
Xamarin.Forms.Platform.WPF.FormsApplicationUserControl : System.Windows.Controls.UserControl
Xamarin.Forms.Platform.WPF.FormsContentViewUserControl : System.Windows.Controls.UserControl

**Comment by jfversluis** [comment]
Unfortunately we won't be able to take this in for Xamarin.Forms anymore. If this is still of interest to you, make sure to open a proposal on the .NET MAUI repo. Thanks!
