### ISSUE TITLE
Items are not layout when detail page is navigated in MasterDetailPage

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#1421]
Hi Team,

### Description
When navigating to a ContentPage loaded inside a DetailPage, the items are not layout entirely in view while scrolling and it only layout the elements which are initially loaded.

### Steps to Reproduce

1. In the MasterPage, click the 'Page 2' button, which navigates to a navigation page. See that the items are loaded properly while scrolling in details page.
2. Now click the 'Page 1' button, which navigates to a ContentPage. See that the items are layout only in the View which is displayed in the screen.
3.After scrolling down the list, items are not layout in view. 

### Actual Behavior
While navigating to a ContentPage in Detail page, all items should be visible in the View while scrolling.

### Basic Information

- Platform Target Frameworks: Android
- Android: 7.1 
- Nuget Packages: XAMARIN.FORMS v.2.5.0.91635
- Affected Devices: MOTO G5S

### Screenshots

![image](https://user-images.githubusercontent.com/20282188/34157584-3f7bb010-e4e8-11e7-8972-dddde8830e5a.png)

### Reproduction Link

[MasterDetailPageIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1571622/MasterDetailPageIssue.zip)

**Comment by rmarinho** [comment]
This doesn't seem to directly be related with Xamarin.Forms but with the custom control you are creating. You should be using a ListView it scrolling items.

**Comment by DineshBabuYadav** [comment]
Though the issue may occur in Custom control, we couldn't able to recognize the issue at our end. It seems that the issue arises while layout the custom view with framework element(Master detail page). Could you please ensure the same and revert us asap.

P.S.
Since, the query may not directly related to Xamarin Forms, but if we are requesting an query means then, you need to provide a valid response instead of the query is not directly related to Xamarin Forms. 

Thanks in Advance,
Dinesh
