### ISSUE TITLE
"None" Linking Causes Xamarin.Forms to Break iOS Extension Google Analytics Libraries

### ISSUE THREAD

**Issue by kspearrin** [xamarin/Xamarin.Forms#1422]
### Description

I had originally opened this issue in the [GoogleApisForiOSComponents](https://github.com/xamarin/GoogleApisForiOSComponents/issues/116#event-1394496748) repo since it did not seem relevant to XF, but upon investigation I was directed by @SotoiGhost to move it here.

> After playing with some iOS configuration and different kind of projects, I have come to the conclusion that this is an odd scenario caused by Xamarin.Forms, NetStandard, and the linker that affects only G.Analytics, I tried using Firebase.Analytics and everything worked as expected. Please, if you can, file an issue in Xamarin.Forms GitHub repo, explaining what's happening.

Reference original issue for full history here: https://github.com/xamarin/GoogleApisForiOSComponents/issues/116

### Steps to Reproduce

1. Download test Xamarin.Forms project with iOS and iOS Action Extension here: https://github.com/kspearrin/BuildDownloadTest
2. Run iOS extension on a test device (I am using an iPhone 6S). This problem is not present on the simulator.
3. Set breakpoint in [LoadingViewController](https://github.com/kspearrin/BuildDownloadTest/blob/master/src/iOS.Extension/LoadingViewController.cs#L20)
4. Observe `GaiConstants` values.

### Expected Behavior

`GaiConstants` will have property values.

### Actual Behavior

`GaiConstants` are all null.

Changing the iOS Extension project from `<MtouchLink>None</MtouchLink>` to `<MtouchLink>Full</MtouchLink>` or `<MtouchLink>SdkOnly</MtouchLink>` seems to resolve the problem.

### Basic Information

- Version with issue: 2.4.0.91020
- Last known good version: n/a
- IDE: VS 2017 Windows or Mac
- Platform Target Frameworks: 
  - iOS:  11.6.1.2
- Nuget Packages: Xamarin.Google.iOS.Analytics v3.17.0.2
- Affected Devices: iPhone

### Screenshots

![screen shot 2017-12-16 at 9 59 22 am](https://user-images.githubusercontent.com/1190944/34072664-803f3c7a-e259-11e7-9838-c1e4eaa90f63.png)

### Reproduction Link

https://github.com/kspearrin/BuildDownloadTest

**Comment by rmarinho** [comment]
hi @kspearrin this doesn't seem to be related to Xamarin.Forms but specific to Xamarin.iOS , you should open a bug here

Sorry to redirect you again but can you open a issue here https://github.com/xamarin/xamarin-macios/issues :) thanks

**Comment by jassmith** [comment]
@kspearrin we are going to move the bug for you, I realize now you've been given the run around a bit after reading the history. Will get an updated link in a second.

**Comment by rmarinho** [comment]
@kspearrin we have open a new bug here : 
https://github.com/xamarin/xamarin-macios/issues/3115
