### ISSUE TITLE
Xamarin.Forms UWP ButtonRenderer UpdateContent() ImageOpened event NullReferenceException

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#1423]
I'm getting an intermittent NullReferenceException from the ImageOpened event handler in the UWP ButtonRenderer UpdateContent() function.

The culprit appears to be this line:
Element.InvalidateMeasureNonVirtual(InvalidationTrigger.RendererReady);
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/ButtonRenderer.cs#L154

It seems that "Element" is getting set to null somewhere between the creation of my button and the ImageOpened event triggering.

An easy fix would be to capture the current value of Element in a temporary variable and use that in the lambda function.

There's a few other comments regarding the issue at these links, but I couldn't find any other direct reports of this bug

Forum › Xamarin.Forms › Xamarin.Forms Releases
Xamarin.Forms 2.3.4.270
https://forums.xamarin.com/discussion/comment/264585/#Comment_264585

alexrainman/CarouselView UWP: crash on window resize #199
https://github.com/alexrainman/CarouselView/issues/199#issuecomment-322115694

**Comment by rmarinho** [comment]
Hi, is it possible to provide a small sample so we can try to reproduce the issue. ?

Thanks

**Comment by jalbertSyncroTech** [comment]
Yes, but it won't be until after the new year and the issue is timing related so it may not be reproducible.

What I'm doing is using a CarouselPage as the MainPage of my application, and then adding all of the pages used in my application to the CarouselPage's children in order to "pre-render" them.  I then swap the MainPage to the real page.  The NullReferenceException happens at this point, but if I put a small Task.Delay (currently 500ms) after "pre-loading" the pages I don't see the issue anymore.

Either way, I think the existing code is incorrect as it's assuming in an asynchronous callback that the Element attached to the renderer hasn't changed between when the image load was requested and when the load finished.

**Comment by kingces95** [comment]
@jalbertSyncroTech Happy New Year! Please attach a reproduction. An intermittent reproduction is sufficient so long as it eventually crashes.

**Comment by jalbertSyncroTech** [comment]
Happy New Year to you too! zip with reproducible case is attached.

[Issue1423.zip](https://github.com/xamarin/Xamarin.Forms/files/1605026/Issue1423.zip)

**Comment by jalbertSyncroTech** [comment]
@kingces95 or @rmarinho can you remove the s/needs-info and s/needs-repo tags so that the developers can start looking into this?

**Comment by jassmith** [comment]
Got it, thanks

**Comment by hartez** [comment]
Crashed for me literally the first time I ran it.

**Comment by stefan-stanca** [comment]
Running into the same issue when having animated transitions to ContentPages with buttons that have images.  
Transition is simple as 
  this.TranslationY = 800;
  this.TranslateTo(0, 0, 600, Easing.SinInOut);
Buttons are added programatically as follows:
            var result = new Button
            {
                TextColor = Color.Blue,
                HorizontalOptions = LayoutOptions.Center,
                CornerRadius =  42/ 2 ,
                HeightRequest = 42,
                WidthRequest = 42,
                BorderColor = Color.Blue,
                BackgroundColor = Color.WhiteSmoke,
                BorderWidth = 2,
                Image = ImageSource.FromFile(imageFullPath) as FileImageSource;
            };

**Comment by hartez** [comment]
This was fixed by PR #1576 in 3.0.0.
