### ISSUE TITLE
[Bug]On IOS  With Grouping in collection view with only one item in ItemSource then item display in center not on left side of view. 

### ISSUE THREAD

**Issue by Sonam-Chavan-2015** [xamarin/Xamarin.Forms#14231]
### Description
I have used the collectionview with GridItemsLayout with span of 2 and bind it to collection and if it contains only one item then the item is display at center of the view.
### Steps to Reproduce

 <CollectionView  Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" ItemsSource="{Binding Cards}" ItemSizingStrategy="MeasureAllItems" IsGrouped="True">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" Span="2" HorizontalItemSpacing="10" VerticalItemSpacing="10"/>
                </CollectionView.ItemsLayout>
                <CollectionView.GroupHeaderTemplate>
                    <DataTemplate>
                        <Label Text="{Binding GroupDisplayHeading}" FontSize="24"
                               TextColor="{StaticResource Gray1}" />
                    </DataTemplate>
                </CollectionView.GroupHeaderTemplate>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <views1:cards/>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

### Expected Behavior
Items should display properly in align
### Actual Behavior
one Item display at center only
### Basic Information
on Android the behavior works fine no issues.

If any help or workaround appreciated.

**Comment by jsuarezruiz** [comment]
@Sonam-Chavan-2015 What Xamarin.Forms version are you using?. Could you attach a small sample where reproduce the issue?

**Comment by Sonam-Chavan-2015** [comment]
Hi,

I am using the xmarain forms 5.0 version.
I took same code from https://github.com/xamarin/Xamarin.Forms/issues/6851
only the thing I added is grouping in collectionview
I also check https://github.com/xamarin/Xamarin.Forms/pull/10241 for solution but it not works.

**Comment by Sonam-Chavan-2015** [comment]
Any help appreciate. I am block due to this.

**Comment by Sonam-Chavan-2015** [comment]
I had fix this with ItemSizingStatergy on platform specific.
  <CollectionView.ItemSizingStrategy>
                    <OnPlatform x:TypeArguments="ItemSizingStrategy">
                        <On Platform="iOS" Value="MeasureFirstItem" />
                        <On Platform="Android" Value="MeasureAllItems" />
                    </OnPlatform>
                </CollectionView.ItemSizingStrategy>

May be it can help others if possible.
