### ISSUE TITLE
Label TailTruncation problem - fragment of last letter is not visible

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1425]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=54050

### Description
When using TailTruncation the last letter is only partially visible

### Expected Behavior
Truncate the text without a partial letter.

### Actual Behavior
Truncation shows a partial character.

### Basic Information

- Version with issue: 2.4.0
- Platform Target Frameworks: 
  - Android: 6.0
- Affected Devices: Xiaomi Redmi 3s, Density 3 (Honor 5X)

### Screenshots

![label-truncation](https://user-images.githubusercontent.com/41873/34184556-02ccf07c-e4e6-11e7-85bc-2bde1372ef63.jpg)

### Reproduction

```
public App ()
{
   MainPage = new ContentPage
   {
      BackgroundColor = Color.Pink,
      Content = new StackLayout
      {
         VerticalOptions = LayoutOptions.Center,
         HorizontalOptions = LayoutOptions.Center,
         Children =
         {
	    new Label
            {
	       HorizontalTextAlignment = TextAlignment.Start,
               BackgroundColor = Color.White,
               Text = "0:00 0:0:00:00 0 0000 00 000",
               TextColor = Color.Black,
               FontSize = 12,
               WidthRequest=151,
               LineBreakMode = LineBreakMode.TailTruncation
            }
         }
      }
   };
}
```

**Comment by jassmith** [comment]
We tried to reproduce this in as many ways as we can with your reproduction and other variations. The labels do not seem to be cut off for us. Can you please provide us with more information about how you are reproducing the issue? Are you able to get it to happen to any simulators (which would eliminate any device specific behavior)?

**Comment by jassmith** [comment]
In particular getting it working on a simulator and sending us the configuration of the simulator would be the most helpful steps to take.

**Comment by davidortinau** [comment]
I'm unable to reproduce this issue. I've tried Pixel API 26 and APID 25 with Support Lib 23, Xamarin.Forms 2.4.0.91020. I don't have access to the devices reference in the original post.

Closing for now until someone can contribute a working reproduction.
