### ISSUE TITLE
[Bug][Core] DropCompletedEventArgs.DropResult unused

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#14253]
`DropCompletedEventArgs.DropResult` is unreferenced in the code, in the 5.0 branch. It appears to make `DropCompletedEventArgs` pointless.

**Comment by jfversluis** [comment]
This is going to be real funny if anyone ever gets to read this: yes, it's kind of pointless right now. But we'll keep it. To avoid any API/ABI breaks mostly. If we weren't in Service Release only mode things might've been different, for now it is what it is and not taking the risk of breaking anything.

At most people might be confused on what it's used for. If you happen to find this: It doesn't do anything, sorry!
