### ISSUE TITLE
[Bug] File not found opening iOS project

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Xamarin.Forms#14257]
### Steps to Reproduce

1. Try to build IOS Applcation without getting the following error:  File not found:Assets.xcassets/AppIcon.appiconset/Icon180.png
2. 
3. 

### Expected Behavior
The project should build
### Actual Behavior
The project does not build
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by Domik234** [comment]
Hey,
open your Assets in iOS project and check if "AppIcon" set exists and if includes "Icon180".

Then open your iOS project (.csproj) in text editor and check all ImageAsset values including 

`Assets.xcassets\AppIcon.appiconset\`

Every file that you find must physically exist on drive in "Assets.xcassets" folder.

If no, remove the ImageAsset tag from your .csproj or add the file to your project (you can move manually file to correct place with correct name or use VS Asset Editor (sometimes may cause bugs).

Note:
Info.plist -> Visual Assets -> App Icons - Here you can set App Icon set that should be used for your project.
When you want to replace Xamarin default and you remove it, project sometimes recreates original Xamarin one and makes the bug that happened to you.

**Comment by jsuarezruiz** [comment]
You have tried @Domik234 's comment, you still have the issue, can I help you?
