### ISSUE TITLE
Will there be further updates to Xamarin forms?

### ISSUE THREAD

**Issue by TopSkillDeveloper** [xamarin/Xamarin.Forms#14269]
Developers promised that the support will continue.
quote: "We will continue to service Xamarin.Forms 5 through November 2022."
https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap
And there are no bug fixes since February and no updates

**Comment by MitchBomcanhao** [comment]
microsoft have also claimed [this](https://github.com/xamarin/Xamarin.Forms/issues/14205#issuecomment-828450390):

> Xamarin.Android, Xamarin.iOS, and Xamarin.Forms will bump to new versions of Android and iOS until vNext is released, which in this case is .NET 6 in November 2021. From that point, new OS bumps will be via .NET 6+. This is a continuation of the same policy we've had for years: https://dotnet.microsoft.com/platform/support/policy/xamarin

So, once they release net6, if google or apple or anyone else changes their requirements for store submission to support newer OS versions, everyone who is still on xamarin forms might find themselves unable to continue supporting their own applications.

**Comment by eramrit78** [comment]
We have laso many issues in XF 5. we are not work from last 4 months. How to continue work in XF 5.

**Comment by jsuarezruiz** [comment]
PRs with fixes are being reviewed to prepare a new Release. Hope to share more detailed info soon (date, etc).

**Comment by MitchBomcanhao** [comment]
> PRs with fixes are being reviewed to prepare a new Release. Hope to share more detailed info soon (date, etc).

yeah, nah, that ain't happening.

**Comment by jfversluis** [comment]
> > PRs with fixes are being reviewed to prepare a new Release. Hope to share more detailed info soon (date, etc).
> 
> yeah, nah, that ain't happening.

Please keep being constructive and respectful.

Sorry I found this issue only now. I have been very straight and honest in [this issue](https://github.com/xamarin/Xamarin.Forms/issues/14205) that is about the same as this. I hope that you have been seeing that we brought down the number significantly, keeping our earlier promises and have been releasing new versions every month.

If you would still like to discuss anything that you're not happy about please open a Discussion so we can do it in the open and be transparent about it, or feel free to send me an email to do it in private.
