### ISSUE TITLE
[Bug] Image misalignment in Xamarin forms

### ISSUE THREAD

**Issue by almas-f** [xamarin/Xamarin.Forms#14276]
### Description
I recently updated from Xamarin 4.5 to 5.0 in windows application using WPF and xamarin forms, all the images in my application started misbehaving(disoriented) while scaling. I tried with version between 4.5 from 5.0

### Steps to Reproduce
Please find the attached code below:
https://1drv.ms/u/s!Ao5n7ate9NZDa9rBbWdPeGfARkQ?e=iyk00i

### Expected Behavior
//in version 4.5
![image](https://user-images.githubusercontent.com/62561466/118655304-0bf7c080-b807-11eb-9647-21287c1757d0.png)

### Actual Behavior
//in version 5.0
![image](https://user-images.githubusercontent.com/62561466/118655327-13b76500-b807-11eb-8f0a-b24b763c7df1.png)

### Basic Information

This is my System Info:
System Information report written at: 04/08/21 11:43:40
System Name: LAP000366
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Pro	
Version	10.0.18362 Build 18362	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	LAP000366	
System Manufacturer	Dell Inc.	
System Model	Latitude 5480	
System Type	x64-based PC	
System SKU	07A7	
Processor	Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)	
BIOS Version/Date	Dell Inc. 1.2.10, 3/19/2017	
SMBIOS Version	3.0	
Embedded Controller Version	255.255	
BIOS Mode	UEFI	
BaseBoard Manufacturer	Dell Inc.	
BaseBoard Product	0NDFXD	
BaseBoard Version	A00	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\Windows	
System Directory	C:\Windows\system32	
Boot Device	\Device\HarddiskVolume2	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.18362.1171"	
User Name	MISTRAL\ravichandra.t	
Time Zone	India Standard Time	
Installed Physical Memory (RAM)	8.00 GB	
Total Physical Memory	7.87 GB	
Available Physical Memory	760 MB	
Total Virtual Memory	15.6 GB	
Available Virtual Memory	2.38 GB	
Page File Space	7.75 GB	
Page File	D:\pagefile.sys	
Kernel DMA Protection	Off	
Virtualization-based security	Not enabled	
Device Encryption Support	Elevation Required to View	
Hyper-V - VM Monitor Mode Extensions	Yes	
Hyper-V - Second Level Address Translation Extensions	Yes	
Hyper-V - Virtualization Enabled in Firmware	Yes	
Hyper-V - Data Execution Protection	Yes

### Environment

<details><summary>Show/Hide Visual Studio info</summary>
Microsoft Visual Studio Professional 2017 
Version 15.9.34
VisualStudio.15.Release/15.9.34+28307.1440
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2017   00370-20007-97838-AA332
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeMaid   11.2.231
CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   10.0.17110.1002
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.9.30718.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.28107.00
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.28307.1342
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Driver Kit   10.0.17110.1002
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
```

</details>

### Screenshots
![image](https://user-images.githubusercontent.com/62561466/118655351-1914af80-b807-11eb-9cf5-2c615cda00ae.png)

### Reproduction Link

Please find the attached code below:
https://1drv.ms/u/s!Ao5n7ate9NZDa9rBbWdPeGfARkQ?e=iyk00i

**Comment by jsuarezruiz** [comment]
I have tried the sample using Xamarin.Forms 5 and this is the result:
<img width="1658" alt="Captura de pantalla 2021-06-18 a las 10 45 09" src="https://user-images.githubusercontent.com/6755973/122533876-4c26aa80-d022-11eb-9287-61d130ec2792.png">

Looks like, the expected behavior. Could you share more info?

**Comment by almas-f** [comment]
Please find the Visual Studio Details:

Microsoft Visual Studio Professional 2017

Version 15.9.26

VisualStudio.15.Release/15.9.26+28307.1234

Microsoft .NET Framework

Version 4.8.03752

 

Installed Version: Professional

 

Visual C++ 2017   00370-20007-97838-AA897

Microsoft Visual C++ 2017

 

ASP.NET and Web Tools 2017   15.9.04012.0

ASP.NET and Web Tools 2017

 

ASP.NET Core Razor Language Services   15.8.31590

Provides languages services for ASP.NET Core Razor.

 

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0

For additional information, visit https://www.asp.net/

 

Atomineer Pro Documentation   1.0

Source-code documentation-comment creation and maintenance, and other documentation-related tools.

 

Azure App Service Tools v3.0.0   15.9.03024.0

Azure App Service Tools v3.0.0

 

Azure Functions and Web Jobs Tools   15.9.03024.0

Azure Functions and Web Jobs Tools

 

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

 

CodeMaid   11.2.231

CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.

 

Common Azure Tools   1.10

Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

 

JavaScript Language Service   2.0

JavaScript Language Service

 

JavaScript Project System   2.0

JavaScript Project System

 

JavaScript UWP Project System   2.0

JavaScript UWP Project System

 

Microsoft Azure Tools   2.9

Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.20417.1

 

Microsoft Continuous Delivery Tools for Visual Studio   0.4

Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

 

Microsoft JVM Debugger   1.0

Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

 

Microsoft Library Manager   1.0

Install client-side libraries easily to any web project

 

Microsoft MI-Based Debugger   1.0

Provides support for connecting Visual Studio to MI compatible debuggers

 

Microsoft Visual C++ Wizards   1.0

Microsoft Visual C++ Wizards

 

Microsoft Visual Studio Tools for Containers   1.1

Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

 

Microsoft Visual Studio VC Package   1.0

Microsoft Visual Studio VC Package

 

MLGen Package Extension   1.0

MLGen Package Visual Studio Extension Detailed Info

 

NuGet Package Manager   4.6.0

NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

 

ProjectServicesPackage Extension   1.0

ProjectServicesPackage Visual Studio Extension Detailed Info

 

ResourcePackage Extension   1.0

ResourcePackage Visual Studio Extension Detailed Info

 

ResourcePackage Extension   1.0

ResourcePackage Visual Studio Extension Detailed Info

 

SQL Server Data Tools   15.1.62002.01090

Microsoft SQL Server Data Tools

 

Test Adapter for Boost.Test   1.0

Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

 

Test Adapter for Google Test   1.0

Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

 

TypeScript Tools   15.9.30718.2001

TypeScript Tools for Microsoft Visual Studio

 

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

 

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.

Microsoft Visual F# Tools 10.2 for F# 4.5

 

Visual Studio Code Debug Adapter Host Package   1.0

Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

 

Visual Studio Tools for CMake   1.0

Visual Studio Tools for CMake

 

Visual Studio Tools for Containers   1.0

Visual Studio Tools for Containers

 

Visual Studio Tools for Universal Windows Apps   15.0.28307.1209

The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
