### ISSUE TITLE
CollectionView Crash: 

### ISSUE THREAD

**Issue by brad302** [xamarin/Xamarin.Forms#14270]
This is a little hard to detail but I have just converted a C# based visualisation of a list of products to a CollectionView.

It works initially without issue, at least once, maybe twice but any more than that produces a crash with the below stack trace.

This crash is happening on the iOS simulator as well as my physical iPhone 12 device.

List`1[T].get_Item (System.Int32 index) /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:161
IList.get_Item (System.Int32 index) /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:266
ObservableItemsSource.ElementAt (System.Int32 index) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:240
ObservableItemsSource.get_Item (System.Int32 index) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:40
ObservableItemsSource.get_Item (Foundation.NSIndexPath indexPath) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:96
ItemsViewController`1[TItemsView].GetSizeForItem (Foundation.NSIndexPath indexPath) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:604
ItemsViewDelegator`2[TItemsView,TViewController].GetSizeForItem (UIKit.UICollectionView collectionView, UIKit.UICollectionViewLayout layout, Foundation.NSIndexPath indexPath) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewDelegator.cs:167
(wrapper managed-to-native) ObjCRuntime.Messaging.void_objc_msgSend_IntPtr(intptr,intptr,intptr)
UICollectionView.InsertItems (Foundation.NSIndexPath[] indexPaths) /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UICollectionView.g.cs:499
ObservableItemsSource+<>c__DisplayClass36_0.<Add>b__0 () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:165
ObservableItemsSource.Update (System.Action update, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:277
ObservableItemsSource.Add (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:165
ObservableItemsSource.CollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs args) D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:120
ObservableItemsSource+<>c__DisplayClass32_0.<CollectionChanged>b__0 () D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ObservableItemsSource.cs:104
NSAsyncActionDispatcher.Apply () /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:152
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65
Application.Main (System.String[] args) /Volumes/Data/Development/Xamarin/Applications/VSTS/Neto cPanel/Mobile/iOS/Main.cs:17

I've attached the stack trace in a file so it's easier to read.

[StackTrace.txt](https://github.com/xamarin/Xamarin.Forms/files/6489107/StackTrace.txt)

This section of the app is a little hard to break out for reproducible reasons so I am hoping this is something that can be looked into and corrected without a version of my app to test on.  More than happy to have a Teams session if required.

My app is currently running version 5.0.0.2012

For the record, this is the contents of my development environment ...

=== Visual Studio Community 2019 for Mac ===

Version 8.9.9 (build 3)
Installation UUID: df0cdc0a-deb9-454d-a8d1-9b493a544470
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: Not installed
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: Not installed

=== .NET Core 3.1 SDK ===

SDK: Not installed

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/braddixon/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/braddixon/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-04-21 21:23:40 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-04-21 21:23:58 UTC

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Build Information ===

Release ID: 809090003
Git revision: 163d834aa64ba9129e5ef30e49a947ef67bcd809
Build date: 2021-05-06 10:14:43-04
Build branch: release-8.9
Xamarin extensions: 163d834aa64ba9129e5ef30e49a947ef67bcd809

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

Hopefully we can get to the bottom of this.

**Comment by brad302** [comment]
@rachelkang good news, the issue has resolved itself.

I changed how the invocation works for the view that the CollectionView is contained within.

That and updates to iOS may have fixed it, not sure. Either way, I no longer have the issue so I'm happy for it to be closed.

**Comment by rachelkang** [comment]
@brad1 awesome! Glad to hear :) I'll be closing this issue then, but if the issue resurfaces please feel free to reopen with a sample project attached.
