### ISSUE TITLE
Page with ListView or ScrollView not resized properly when using WindowSoftInputModeAdjust.Resize

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#1428]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=58556

### Description

When using 

        App.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize);

code to set Android to use the AdjustResize option for the SoftInputMode, an initial page with a ScrollView or a ListView is not resized properly if navigated back to from a detail page when the keyboard is showing. 

### Steps to Reproduce

1. Open the attached test project

2. Deploy the Android app to an Android emulator or device (tested with a Marshmallow emulator)

3. Select an item from the ListView

4. Click on the Entry at the bottom of the new page. The keyboard will show. Leave it showing. 

5. Click the back arrow on the upper left to go back to the first page. 

6. repeat steps 3-5 (may not be necessary, but on occasion I have had to do this twice to reproduce the issue)

### Expected Behavior

ListView will take up full screen and be the same size as it was initially.

### Actual Behavior

Bottom part of the ListView is missing. ListView seems to still be resized to allow for the area taken up by 
the keyboard. 

### Basic Information

- Version with issue: 2.3.5.256-pre6
- IDE: VSMac

### Reproduction Link

[AndroidAdjustResizeBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1573713/AndroidAdjustResizeBug.zip)

**Comment by samhouts** [comment]
I can no longer reproduce this issue with version 2.5.0.122203. Please confirm.

**Comment by pauldipietro** [comment]
Seems to not reproduce on an S8, so yes, closing.
