### ISSUE TITLE
Why bother filing issues if there isnt going to be a service release or fixes [Bug] 

### ISSUE THREAD

**Issue by developer9969** [xamarin/Xamarin.Forms#14280]
Hi
We assume you are short staffed and we assume that MAUI is the priority right now. But what do we say to our clients when they file bugs that the app is not behaving as it should. 

Shall we tell them , Please wait for Maui?

@davidortinau  ,
Many of issues reported are critical to us. 

What is the plan?

many thanks

**Comment by jsuarezruiz** [comment]
PRs with fixes are being reviewed to prepare a new Release.

**Comment by developer9969** [comment]
@jsuarezruiz Hi any update regarding the service release?

**Comment by jsuarezruiz** [comment]
We are completing the work in some PRs that must be included in the Service Release, like https://github.com/xamarin/Xamarin.Forms/pull/14101
Hope to share more details soon.

**Comment by developer9969** [comment]
@jsuarezruiz 
Hi there any more news on a release? 
@davidortinau it's now nearly 5 months since last release! I appreciate the constraints you must be working under with a very small team, Xamarin forms is very buggy at the moment V5 is one of the worst releases and I have been using XF since version 2. The current "Meet the bar" list of fixes does not contain what people want. We want the collectionView to be stable. We had to use other controls to avoid the collectionview, even bindableLayout when is not meant to be used.

People are filing issues without realising that there is no chance in hell they are going to be fixed at the moment, it's very frustating. On a latest project I pushed for xamarin when some new arrivals wanted to use Flutter. I dont know flutter YET, but I am going to learn it now and see if we can move away.

You cannot have PRs lying there for more than a year.... they will be useless by now... either Microsoft start believing in Xamarin or people will keep leaving..

**Comment by isness** [comment]
I have a couple of projects running Xamarin.Forms and for the next big one I don't know what to do. XF is now barely usable, and production-ready MAUI release is probably very far in the future. What's more, given the experience with XF, MAUI will probably suffer from the same poor support, so I guess it's not worth waiting for at all.

**Comment by lewcianci** [comment]
> I have a couple of projects running Xamarin.Forms and for the next big one I don't know what to do. XF is now barely usable, and production-ready MAUI release is probably very far in the future. What's more, given the experience with XF, MAUI will probably suffer from the same poor support, so I guess it's not worth waiting for at all.

I moved from xamarin forms to Flutter about a year ago. It's indescribably better. Switching frameworks was a drastic step but I'm so glad to be off the XF/MAUI train.

Just completed a rewrite of one of my old apps and am now making new apps. I still use net core for the API side.

**Comment by jsuarezruiz** [comment]
Recently we released a SR, working on the next one that will be ready in some weeks. The plan is to release a new version every few weeks (3-4). I am going to close this issue, but feel free to reopen or open a new one to share any kind of feedback.
