### ISSUE TITLE
[Enhancement] [CollectionView] Select whether to scroll to first item or header in grouped collections

### ISSUE THREAD

**Issue by Pantheas** [xamarin/Xamarin.Forms#14297]
## Summary
I have a feature request to scroll to a specific group on button click.
I created a "jump marks" control that lists all item groups and is linked to a `CollectionView`.
On item click I call `CollectionView.ScrollTo(group[0], group)` in order to bring the first item of the selected group into the user's view.
However, instead of scrolling to the first item, I would rather scroll to the header of the group.
That is a requirement from my design team.
I already found the reason the scrolling works this way:
[ObservableGroupedSource.cs](https://github.com/xamarin/Xamarin.Forms/blob/ad71f116ed5a5d8402bbd25dbf0b96bb7821d5e1/Xamarin.Forms.Platform.Android/CollectionView/ObservableGroupedSource.cs#L425)

Is it possible for me to override this behavior by e.g. providing a custom `ObservableGroupedSource` like it is possible for image source classes?

## API Changes

In general I think it would be nice to have a setting on the `CollectionView` or an additional parameter in the `ScrollTo` method to state whether the first item of the group or the header should be scrolled into view.

e.g.
<CollectionView
    ItemsSource="{Binding ItemGroups}"
    GroupScrollMode="Header/FirstItem" />
    
```csharp
collectionView.ScrollTo(
    group[0],
    group,
    GroupScrollMode.Header,
    position: ScrollToPosition.Start,
    animate: true);
```    

## Intended Use Case
see introduction

**Comment by Pantheas** [comment]
@jsuarezruiz is it possible for me to override this behavior by e.g. providing a custom ObservableGroupedSource like it is possible for image source classes?

**Comment by Pantheas** [comment]
Any update one this one?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
