### ISSUE TITLE
[Bug] AppShell and Firebase: Android.Content.Res.Resources+NotFoundException: 'Unable to find resource ID #0xffffffff'

### ISSUE THREAD

**Issue by madmike270** [xamarin/Xamarin.Forms#14317]
### Description

Tried to add Firebase to my Xamarin App. After that the app navigation didn´t function anymore, always crashed with the attached bug (Android.Content.Res.Resources+NotFoundException: 'Unable to find resource ID #0xffffffff').
After adding Xamarin.Firebase.Auth the shell navigation always crashed with this bug. I´ve also tried with the Xaminals example app, same result without changing any other code than adding the package. (adapted project is attached)
So far i didn´t find a workaround.

### Steps to Reproduce

1. Take Xaminals template (or any other AppShell project)
2. Install Xamarin.Firebase.Auth(120.0.4) in android project
3. Try to navigate to another stack (in example via the about shellcontent or via Shell.Current.GoToAsync)

### Expected Behavior
- not crashing, navigating to the new stack

### Actual Behavior
- app crashes 

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: -
- Platform Target Frameworks: 
  - Android: 28.0.1 - 30.0.2 
- NuGet Packages:
   - Xamarin.Forms 5.0.0.2012
   - Xamarin.Firebase.Auth 120.0.4
- Affected Devices:
   - emulators and real devices
  

### Reproduction Link

[Xaminals_Firebase.zip](https://github.com/xamarin/Xamarin.Forms/files/6584382/Xaminals_Firebase.zip)

### Build Logs

[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0xf3cae140: maj 3 min 0 rcv 3
[EGL_emulation] eglMakeCurrent: 0xf3cae140: ver 3 0 (tinfo 0xe2ffb1d0) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0xf3cae530, tid 30025
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3ff228000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
Loaded assembly: /data/user/0/com.companyname.xaminals/files/.__override__/System.Net.Http.dll [External]
Thread started: <Thread Pool> #7
Thread started: <Thread Pool> #8
Thread started: <Thread Pool> #9
Thread started: <Thread Pool> #10
Thread started: <Thread Pool> #11
Thread started: <Thread Pool> #12
Thread started: <Thread Pool> #13
Thread started: <Thread Pool> #14
[nyname.xaminal] Background concurrent copying GC freed 47235(1860KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3965KB/7931KB, paused 756us total 112.943ms
[OpenGLRenderer] Davey! duration=1871ms; Flags=1, IntendedVsync=9404193668731, Vsync=9404627002047, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=9404641515400, AnimationStart=9404641535600, PerformTraversalsStart=9404642106500, DrawStart=9406003292600, SyncQueued=9406028619000, SyncStart=9406030308000, IssueDrawCommandsStart=9406030442300, SwapBuffers=9406055852500, FrameCompleted=9406066949000, DequeueBufferDuration=273600, QueueBufferDuration=731300, GpuCompleted=773094116222, 
[Choreographer] Skipped 85 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1465ms; Flags=0, IntendedVsync=9404643665818, Vsync=9406060332428, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=9406075337100, AnimationStart=9406075359800, PerformTraversalsStart=9406075697500, DrawStart=9406076085200, SyncQueued=9406076752300, SyncStart=9406077375000, IssueDrawCommandsStart=9406077639100, SwapBuffers=9406081448000, FrameCompleted=9406109949400, DequeueBufferDuration=643900, QueueBufferDuration=533300, GpuCompleted=901943135632, 
Thread started: <Thread Pool> #15
Thread started: <Thread Pool> #16
[nyname.xaminal] Explicit concurrent copying GC freed 5445(418KB) AllocSpace objects, 12(240KB) LOS objects, 49% free, 3581KB/7163KB, paused 310us total 6.005ms
[nyname.xaminal] Explicit concurrent copying GC freed 1010(158KB) AllocSpace objects, 8(160KB) LOS objects, 49% free, 3423KB/6846KB, paused 309us total 6.048ms
**Android.Content.Res.Resources+NotFoundException:** 'Unable to find resource ID #0xffffffff'

[TabLayout] MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
[nyname.xaminal] No package ID ff found for ID 0xffffffff.
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.xaminals, PID: 29981
[AndroidRuntime] android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
[AndroidRuntime] 	at android.content.res.ResourcesImpl.getResourceTypeName(ResourcesImpl.java:292)
[AndroidRuntime] 	at android.content.res.Resources.getResourceTypeName(Resources.java:2215)
[AndroidRuntime] 	at androidx.fragment.app.FragmentAnim.loadAnimation(FragmentAnim.java:79)
[AndroidRuntime] 	at androidx.fragment.app.DefaultSpecialEffectsController$AnimationInfo.getAnimation(DefaultSpecialEffectsController.java:796)
[AndroidRuntime] 	at androidx.fragment.app.DefaultSpecialEffectsController.startAnimations(DefaultSpecialEffectsController.java:144)
[AndroidRuntime] 	at androidx.fragment.app.SpecialEffectsController.executePendingOperations(SpecialEffectsController.java:294)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2202)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:938)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Der Thread 0xb hat mit Code 0 (0x0) geendet.
[Xaminals_Firebase.zip](https://github.com/xamarin/Xamarin.Forms/files/6584373/Xaminals_Firebase.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/72699792/120478016-b3025d80-c3ac-11eb-900f-61b9d57f6045.png)

![image](https://user-images.githubusercontent.com/72699792/120478046-ba296b80-c3ac-11eb-9635-2f7f6edf0928.png)

**Comment by angelru** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/13843

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/13843
