### ISSUE TITLE
Using Native View Embedding fails if using a Fragment for the native view

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#1431]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=58204

### Description

Reporting customer is using a library that can only provide an Android Fragment to get the map view provided by the library. In trying to get this to work, customer had issues getting the map fragment to size correctly using an embedded native view. In a discussion on the forums [1], a possible solution was provided that worked as long as the page with the embedded Fragment was the first page assigned to the MainPage property. This worked in the provided example that did not use any mapping library and worked in the customer's solution that used the mapping library that provided the Fragment once the  technique was adopted in the customer's solution. However, if instead the page with the embedded Fragment is a) wrapped in a navigation page,  b) pushed onto the navigation stack, or c) the MainPage property is initially set to another page but later MainPage is set to the page with the Fragment then the page load fails with some variation of a Resource not found exception, with varying resource numbers noted like 0x1 or 0x2. The same is true for both the sample solution provided by EZ Hart [2] and in the customer's solution. 

Note this only seems to be a problem when using a Fragment. In the test solution, there is a FragemntThing class which is the fragment that is to be placed in the Forms app, and a FragmentThingViewGroup class that is used to instantiate and wrap the Fragment so it can be passed back to the Forms UI via a Forms ContentView. The Forms ContentView is used as a place holder, then a message is sent to the Android platform which is subscribed to in MainActivity.cs. When the subscriber code is run, the ContentView.Content is populated with the FragmentThingViewGroup. This all works, as noted, as long as the page with the fragment is the first page set as the App.MainPage. Again, if it is assigned to App.MainPage later, or wrapped in a NavigationPage, or pushed onto the NavigationStack (modal or normal) then the ResourceNotFound exception is thrown. 

>07-17 17:09:13.558 W/ResourceType( 2981): No package identifier when getting name for resource number 0x00000001
>[0:] *****Exception: Exception has been thrown by the target of an invocation.
>  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00017] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00213] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x000a1] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at System.Activator.CreateInstance (System.Type type, System.Object[] args) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
>  at Xamarin.Forms.Xaml.CreateValuesVisitor.CreateFromFactory (System.Type nodeType, Xamarin.Forms.Xaml.IElementNode node) [0x00025] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\CreateValuesVisitor.cs:203 
>  at Xamarin.Forms.Xaml.CreateValuesVisitor.Visit (Xamarin.Forms.Xaml.ElementNode node, Xamarin.Forms.Xaml.INode parentNode) [0x00097] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\CreateValuesVisitor.cs:65 
>  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x000b1] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlNode.cs:175 
>  at Xamarin.Forms.Xaml.ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00089] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlNode.cs:172 
>  at Xamarin.Forms.Xaml.RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) [0x00054] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlNode.cs:223 
>  at Xamarin.Forms.Xaml.XamlLoader.Visit (Xamarin.Forms.Xaml.RootNode rootnode, Xamarin.Forms.Xaml.HydratationContext visitorContext) [0x00053] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlLoader.cs:122 
>  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.String xaml) [0x00046] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlLoader.cs:76 
>  at Xamarin.Forms.Xaml.XamlLoader.Load (System.Object view, System.Type callingType) [0x0002f] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\XamlLoader.cs:56 
>  at Xamarin.Forms.Xaml.Extensions.LoadFromXaml[TXaml] (TXaml view, System.Type callingType) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Xaml\ViewExtensions.cs:36 
>  at NativeLayoutParams.MainPage.InitializeComponent () [0x00001] in C:\lp\PCLNativeEmbedFrag\NativeLayoutParams\NativeLayoutParams\obj\Debug\NativeLayoutParams.MainPage.xaml.g.cs:26 
>  at NativeLayoutParams.MainPage..ctor () [0x00008] in C:\lp\PCLNativeEmbedFrag\NativeLayoutParams\NativeLayoutParams\MainPage.xaml.cs:12 
>  at NativeLayoutParams.Page1.Button_Clicked (System.Object sender, System.EventArgs e) [0x00002] in C:\lp\PCLNativeEmbedFrag\NativeLayout

### Steps to Reproduce

1. Open the attached test project

2. deploy Android app to an Android device or simulator.
### Expected Behavior

Page will display two boxes that both say "I'm a Fragment"

### Actual Behavior

Exception is thrown as noted above. 

### Basic Information

- Version with issue: 2.3.5

### Reproduction Link

[PCLNativeEmbedFrag.zip](https://github.com/xamarin/Xamarin.Forms/files/1573732/PCLNativeEmbedFrag.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
