### ISSUE TITLE
[Bug] Item with SwipeView moves along the screen if you rapidly swipe multiple times.

### ISSUE THREAD

**Issue by stavroaudisho** [xamarin/Xamarin.Forms#14325]
Description
I have a list of items, each in a pancake view, and each one has a delete swipeview item. If you swipe quickly a lot of times in the same direction, the pancakeview moves permanently in the direction you're swiping.

Steps to Reproduce
Create a SwipeView in Xamarin Forms and add a right item
Run on device (I tested on a physical iPhone 11 Pro Max)
Swipe multiple times (and quickly) in one direction. I think the issue happens when the swipe animation is still in process, so maybe set the width to 150-300.

Expected Behavior
The pancake view should remain in the same spot it was originally (when the right and/or left items are not shown of course)

Actual Behavior
The view permanently moves in the direction of the swipe 

https://user-images.githubusercontent.com/72600223/120767121-2de98680-c51b-11eb-99dc-f8f609265d0f.mov

![IMG_6647](https://user-images.githubusercontent.com/72600223/120767143-36da5800-c51b-11eb-9335-8d2826990bb5.jpg)

**Comment by jsuarezruiz** [comment]
Could you try again with the NuGet package from https://github.com/xamarin/Xamarin.Forms/pull/14586?
