### ISSUE TITLE
[UWP] ListView ItemSelected event & SelectedItem property only fires once 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1432]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=28520

### Description
The ItemSelected event only fires once. If a navigation occurs, going back still does not trigger the event.

This is more of a problem of the ListView not being able to update the view when the SelectedItem binding property is set to null.

From @pauldipietro:

Using that reproduction (moving the code into a new project to be used against UWP in particular) it seems like this is still a thing where setting it to null isn't firing off the ListView's PropertyChanged event. Checked against the latest 2.3.6-nightly.

### Basic Information

- Version with issue: 2.3.5

### Reproduction Link

[Microsoft.Band.Portable.Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/1573761/Microsoft.Band.Portable.Sample.zip)

**Comment by pauldipietro** [comment]
This looks fixed in master, presumably by #1235.
