### ISSUE TITLE
[Bug] FirebaseAuth exists in both error

### ISSUE THREAD

**Issue by SwissCheezze** [xamarin/Xamarin.Forms#14347]
### Description

I'm new to xamarin and firebase so i wanted to create a login for an app and i used some code from:
https://github.com/yuv4ik/XFFirebaseAuthExample.git to create it
i installed firebaseauthentication.net accidentally in the android sln and when i tried to write this code :

    class FirebaseAuthenticator : IFirebaseAuthenticator
    {
        public async Task<string> LoginWithEmailPassword(string email, string password)
        {
            var user = await FirebaseAuth.Instance.SignInWithEmailAndPasswordAsync(email, password);
            var token = await user.User.GetIdTokenAsync(false);
            return token.Token;
        }
    }
i got this error : 
CS0433	The type 'FirebaseAuth' exists in both 'Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Xamarin.Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'	Project_Alpha.Android

and i cannot get rid of it i have tried cleaning removing obj and bin uninstalling all other firebaseauthentication packages except xamarin.firebase.auth and cannot get rid of it. Any help would be Appreciated

**Comment by jsuarezruiz** [comment]
Could you attach the sample?. In that way,  I can see what packages you are using etc.

**Comment by SwissCheezze** [comment]
Im closing this thread because i found a solution.The problem was in project.csproj where the package name was confusing the xamarin.firebase.auth with firebaseauth.net

**Comment by ennydz** [comment]
i have the same problem , please tell me the solution i'm using xamarin.firebase.auth ( in xamarin android ) and firebaseauth.net ( in xamarin forms )
thanks

**Comment by SwissCheezze** [comment]
@ennydz check your nuget packet menager to see if your packages are where they should be. xamarin.firebase should be only in android, firebase.net in your main project and .ios on ios part.
I got it because there were 2 packages in android .net and xamarin one

**Comment by ennydz** [comment]
thank you very much . 
it's necessary to remove firebase.net from from android and forms too !

it's worked for me after removed FirebaseAuthentication.net from xamarin forms and replace all functions with the other package

best regards.
