### ISSUE TITLE
Xamarin Forms iOS App missing Icon

### ISSUE THREAD

**Issue by FIELDPOINT** [xamarin/Xamarin.Forms#14345]
![image](https://user-images.githubusercontent.com/43620315/121544609-dc883e00-c9d7-11eb-90fa-206781df9e4e.png)

Building on Windows 10.
XForms:  5.0.0.2012

Creating a brand new Xamarin Forms Project and opening it on an iOS Simulator on the MAC. The Icon is missing, shows the default white icon instead.

**Comment by AndreasReitberger** [comment]
This is a known issue. Please see here: 

https://developercommunity.visualstudio.com/t/Cant-deliver-to-the-appstore-since-last/1436223#T-N1445242

They're working on a fix for vs already.

**Comment by FIELDPOINT** [comment]
Thanks a lot for letting me know.

**Comment by rachelkang** [comment]
Closing this issue as it's already being addressed by the appropriate team
