### ISSUE TITLE
Viewmodel instantiates twice using a ViewModelLocator

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1434]
Migrated from https://bugzilla.xamarin.com/show_bug.cgi?id=57081

### Description
In our app we have a problem of viewmodels instantiated twice. 

The reason this is happening is that creating a new Page instantiates a new viewmodel and then pushing the page on the Navigation stack creates the second viewmodel.In the Page XAML we are referencing a view model locator. This viewmodelLocator has a property of the view model and the getter of this property returns a new viewmodel via a resolve in the dependency container (Unity). So, the problem in fact is that pushing the page on the navigation stack using Navigation.PushAsync(page, true) gets a new view model because somehow the bindings reference the viewmodellocator which in turn get the new viewmodel. 

Side information : The dependency container registers viewmodels in a Transient way, not “static”.

Am I wrong to rely on the concept of resolving a new viemwodel each time the MyViewModel property gets called? I don’t want to have a direct reference to the viewmodels because keeping these references means that the Garbage Collector will not release them and the services/repository that gets injection also are not released.

Or does the Navigation.PushAsync() does something that is not correct?
Funny thing is that Navigation.PushModelAsync() works as expected and does not have the side effect of creating a new viewmodel.

Browsing the internet I could only find one other person with the same problem.
https://forums.xamarin.com/discussion/49257/view-model-instantiating-multiple-times

One solution is to remove the BindingContext to the viewmodellocator from the XAML and putting it in the code behind, but I think this will kill my possibility to have live data in the Xamarin Previewer. Am I Right?

Parts of my code for a better understanding of the problem:

Viewmodellocator

public CarsViewModel CarsVIewModel 
{
	get
	{
		return _dependencyContainer.Resolve<CarsViewModel>();
	}

}

CarsPage

BindingContext=“{Binding CarsViewModel, Source={StaticResource ViewModelLocator}}"

NavigationService

var page = Actvator.CreateInstance(type) as BasePage;
await (page.BindingContext as BaseEventsViewModel).Initialize();
await (page.BindingContext as BaseEventsViewModel).LoadDataAsync();
await Navigation.PushAsync(page, true);

Can you tell me why the last line of code calls the ViewModelLocator (again) and gets me a new ViewModelLocator ?
Do I need to strip the BindingContext from the XAML and put it in the code behind? Or do I need to resolve the view model in my NavigationService? And if I strip the BindingContext from the XAML and put in the code behind, would the Xamarin Previewer Still work? 

If it might be the case that this is a known bug that will or can not be fixed in the near future, I would like to know what the next best solution would be and, maybe a more interesting question : Are we wrong for wanting the view models and every injected class to NOT live long? Our current app is a reasonably big App with lots of functionality and lots of view models etc. that would all be in memory.

References : https://bugzilla.xamarin.com/show_bug.cgi?id=45557 
           : https://github.com/xamarin/Xamarin.Forms/pull/470
: https://github.com/xamarin/Xamarin.Forms/pull/983

### Steps to Reproduce

1. Open the solution in Xamarin Studio 
2. Run on iOS Simulator
3. Type something in the username and password entries.
4. Place a breakpoint in the constructor of the CarsViewModel and you will see that the Breakpoint is hit more than once

### Basic Information

- Version with issue: 2.3.4

### Reproduction Link

[BindingsCall.zip](https://github.com/xamarin/Xamarin.Forms/files/1573769/BindingsCall.zip)

**Comment by 1iveowl** [comment]
What is the status on this? I've observed this behavior on Xamarin.Forms 2.5.0.121934.

While waiting for a fix. Are there any known workarounds?

**Comment by marciosouzajunior** [comment]
@1iveowl Can you instatiate you viewModel in view contructor? It will be created every time you navigate to this. Im working this way.

**Comment by 1iveowl** [comment]
@marciosouzajunior I'm not entirely sure how to do that when using a View Model Locator and IoC (AutoFac)? Could you shed some more light to that approach?

**Comment by 1iveowl** [comment]
Update: Updated to Xamarin Forms 2.5.0.122203. The issue remains.

**Comment by marciosouzajunior** [comment]
@1iveowl I dont use locator. Just create view model in code behind constructor of view:

`public partial class MyPage : ContentPage
{
	private MyPageViewModel viewModel;

	public MyPage()
	{
		InitializeComponent();
		viewModel = new MyPageViewModel();
		BindingContext = viewModel;
	}
	
	//...
}`

**Comment by 1iveowl** [comment]
@marciosouzajunior OK. thank you for clarifying. 

Are you sure that the page is not created twice? I haven't tested, but I would think that this makes no difference. Try and set a break point in the constructor of the ViewModel as see if is called once or twice.

**Comment by marciosouzajunior** [comment]
@1iveowl Yes, im sure. The page is created only once.

**Comment by rmurray26** [comment]
Any update on a fix for this?  We are seeing the same issue setting the binding context in XAML using an IoC container (Autofac).

For now our work-around is to capture the binding context on page instantiation and then set the context on the page back to the original after setting it as the root child in a navigation page or when pushing pages onto the navigation stack, but this feels like a bit of a hack.

**Comment by davidortinau** [comment]
Closed by #470 #983
