### ISSUE TITLE
[Bug] iOS - Binding delay when ScrollView used

### ISSUE THREAD

**Issue by filipleifer** [xamarin/Xamarin.Forms#14344]
### Description

When some control e.g. Button is used in ScrollView and it is not visible in screen in initial state (you have to scroll down to be visible) biding is not working when you scroll down and tap button really quickly. It works after some delay (~1-2 seconds). Unfurtunatelly it can be reproduced only on some devices. e.g. (iPhone 7 MN8X2CN). Reproducted on iOS 14.2, 14.5 

### Steps to Reproduce

1. Use sample application 
[ScrollApp.zip](https://github.com/xamarin/Xamarin.Forms/files/6629901/ScrollApp.zip)

2. Scroll down and quickly tap on Button "ClickMe"

### Expected Behavior
Button react on your tap by change of appearace and VM method is  called
### Actual Behavior
Button react on your tap by change of appearace but nothing happed (VM method is not called)
### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: N/A

- Affected Devices: iPhone 7.

**Comment by jsuarezruiz** [comment]
It only happens to you on iPhone 7 14.5, can you reproduce it on other devices or simulators?

**Comment by jfversluis** [comment]
No response to our request for more information. Assuming that this is no longer an issue. Thanks!
