### ISSUE TITLE
[Bug] MT1007: Failed to launch the application on the device 'My iPhone': Invalid Service Error (error: 0xe8000022)		 	0	

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#14354]
### Steps to Reproduce

1. After upgrading to Visual Studio 2019 version 16.10.2 I'm unable to press F5 and debug my app on my iPhone real device.
2. The app is deployed to the device but VS is unable to launch it 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  Default
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: iPhone 11 Pro

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.10.2
VisualStudio.16.Release/16.10.2+31410.357
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA730
Microsoft Visual C++ 2019

.NET Core Debugging with WSL 2   1.0
.NET Core Debugging with WSL 2

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanBinAndObjCommand Extension   1.1.1
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper 2021.1.2   Build 211.0.20210420.181229
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62105.04180
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.73
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   16.10.000.231 (d16-10@8111164)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.10 (0e35b2e0b)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs

1>Starting deploy 'Hasc.MobileLink.iOS' into the device 'Eder’s iPhone'...
1>Deploying 'Hasc.MobileLink.iOS' into the device 'Eder’s iPhone'...
The app Hasc.MobileLink.iOS is already deployed on Eder’s iPhone
1>Deploy succeeded. The app 'Hasc.MobileLink.iOS' has been successfully deployed on Eder’s iPhone.
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
Launching 'Hasc.MobileLink.iOS' on 'Eder’s iPhone'...
Launching...
Using Xcode 12.5 found in /Applications/Xcode.app/Contents/Developer
Xamarin.Hosting: Xamarin.Hosting
Xamarin.Hosting:     Version: cddbd1915d (d16-10)
Xamarin.Hosting:     Xcode: /Applications/Xcode.app
Xamarin.Hosting:     Xcode Version: 12.5
Xamarin.Hosting:     Verbosity: 1
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTiPhoneSimulatorRemoteClient.framework/DVTiPhoneSimulatorRemoteClient
Xamarin.Hosting: Loaded /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/DTDeviceKitBase
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/DVTKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKit.framework/DTDeviceKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTXConnectionServices.framework/DTXConnectionServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTSourceControl.framework/DVTSourceControl
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTServices.framework/DVTServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTPortal.framework/DVTPortal
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/DVTAnalyticsClient
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/XCServices.framework/XCServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAppStoreConnect.framework/DVTAppStoreConnect
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/ContentDeliveryServices
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftware.framework/DVTITunesSoftware
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTProducts.framework/DVTProducts
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTProductsUI.framework/DVTProductsUI
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalytics.framework/DVTAnalytics
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/SourceKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTGraphKit.framework/DTGraphKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDeveloperModeHelper.framework/DVTDeveloperModeHelper
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalyticsKit.framework/DVTAnalyticsKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IDEKit.framework/IDEKit
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IBFoundation.framework/IBFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IBAutolayoutFoundation.framework/IBAutolayoutFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DebugHierarchyFoundation.framework/DebugHierarchyFoundation
Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DebugHierarchyKit.framework/DebugHierarchyKit
Xamarin.Hosting: Loaded Xcode plugins successfully.
Xamarin.Hosting: Device discovery started
Xamarin.Hosting: Device discovery event: Connected (00008030-001C48A02682802E)
Xamarin.Hosting: Connected to Eder???s iPhone (00008030-001C48A02682802E) in 00:00:00.0038861
Xamarin.Hosting: Connecting to 'Eder???s iPhone', token is 0x7fe35779cdc0
Xamarin.Hosting: Connected to 'Eder???s iPhone'
Xamarin.Hosting: Mounting developer image on 'Eder???s iPhone'
2021-06-17 16:48:31.392 mlaunch[4874:753834] Thread Pool Worker DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fe35782e1f0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.5/DeveloperDiskImage.dmg'>', error=-402653066: Error Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for development." UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage, NSUnderlyingError=0x7fe380127210 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653066 "Could not support development." UserInfo={MobileDeviceErrorCode=(0xE8000076), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001188543b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000118890674 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x000000011889108b __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	5   DTDeviceKitBase                     0x0000000118890dca -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 185
	7   ???                                 0x000000014d2cac8f 0x0 + 5589740687
	4   libdispatch.dylib                   0x00007fff201855ce _dispatch_lane_barrier_sync_invoke_and_complete + 60
	6   mlaunch                             0x000000010465e259 xamarin_dyn_objc_msgSend + 217
	8   ???                                 0x000000014d2cab23 0x0 + 5589740323
	9   ???                                 0x000000014d2436fb 0x0 + 5589186299
	10  ???                                 0x000000014d1cca82 0x0 + 5588699778
	11  ???                                 0x00000001164acf26 0x0 + 4668968742
	12  ???                                 0x00000001164acbdb 0x0 + 4668967899
	13  ???                                 0x000000014d1cc8b3 0x0 + 5588699315
	14  ???                                 0x000000014d2ca7de 0x0 + 5589739486
	15  ???                                 0x000000014d1c9533 0x0 + 5588686131
	16  ???                                 0x000000014d1c934b 0x0 + 5588685643
	17  ???                                 0x000000014d2c8283 0x0 + 5589729923
	18  ???                                 0x000000014d245c83 0x0 + 5589195907
	19  ???                                 0x000000014d23df4b 0x0 + 5589163851
	20  ???                                 0x000000014d23d64b 0x0 + 5589161547
	21  ???                                 0x000000014d23d443 0x0 + 5589161027
	22  ???                                 0x000000014d23abba 0x0 + 5589150650
	23  ???                                 0x000000014d23a2fa 0x0 + 5589148410
	24  ???                                 0x000000014d239d63 0x0 + 5589146979
	25  ???                                 0x000000014d239f86 0x0 + 5589147526
	27  mlaunch                             0x0000000104880dcf mono_runtime_try_invoke + 143
	28  mlaunch                             0x00000001048cdf6a worker_callback + 938
	26  mlaunch                             0x000000010474af53 mono_jit_runtime_invoke + 1603
	29  mlaunch                             0x00000001048cbbc1 worker_thread + 369
	30  mlaunch                             0x00000001048d7f83 start_wrapper_internal + 403
	31  mlaunch                             0x00000001048d7dce start_wrapper + 62
	33  libsystem_pthread.dylib             0x00007fff2031e443 thread_start + 15
	32  libsystem_pthread.dylib             0x00007fff203228fc _pthread_start + 224
), DVTRadarComponentKey=261622, NSLocalizedDescription=Could not support development.}}, NSLocalizedRecoverySuggestion=If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device., NSLocalizedFailure=This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running., DVTRadarComponentKey=487927, NSLocalizedDescription=Failed to prepare device for development.}
warning HE0030: Could not mount developer tools on 'Eder???s iPhone': Failed to prepare device for development.
warning HE0031: Failed to mount developer tools on 'Eder???s iPhone'.
2021-06-17 16:48:31.731 mlaunch[4874:753811]  DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device." UserInfo={NSUnderlyingError=0x7fe3579ff3f0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653150 "The service is invalid." UserInfo={MobileDeviceErrorCode=(0xE8000022), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001188543b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000118863c61 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 626
	2   DTDeviceKitBase                     0x0000000118863320 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	3   DTDeviceKitBase                     0x00000001188564f8 __DTDKExecuteInSession_block_invoke_2 + 35
	4   DTDeviceKitBase                     0x0000000118855bda __DTDKExecuteWithConnection_block_invoke_2 + 218
	5   DTDeviceKitBase                     0x0000000118855ad7 __DTDKExecuteWithConnection_block_invoke + 106
	6   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff201855ce _dispatch_lane_barrier_sync_invoke_and_complete + 60
	8   DVTFoundation                       0x000000011677948a DVTDispatchBarrierSync + 208
	9   DVTFoundation                       0x000000011674c65e -[DVTDispatchLock performLockedBlock:] + 60
	10  DTDeviceKitBase                     0x00000001188559d8 DTDKExecuteWithConnection + 226
	11  DTDeviceKitBase                     0x000000011885639c DTDKExecuteInSession + 239
	12  DTDeviceKitBase                     0x0000000118863170 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 131
	13  DVTFoundation                       0x0000000116776931 __DVT_CALLING_CLIENT_BLOCK__ + 7
	14  DVTFoundation                       0x000000011677855b __DVTDispatchAsync_block_invoke + 1191
	16  libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00007fff20177623 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x00007fff2017e5ea _dispatch_lane_serial_drain + 606
	18  libdispatch.dylib                   0x00007fff2017f0e0 _dispatch_lane_invoke + 417
	20  libsystem_pthread.dylib             0x00007fff2031f45d _pthread_wqthread + 314
	21  libsystem_pthread.dylib             0x00007fff2031e42f start_wqthread + 15
	19  libdispatch.dylib                   0x00007fff20188c0d _dispatch_workloop_worker_thread + 811
), DVTRadarComponentKey=261622, NSLocalizedDescription=The service is invalid.}}, NSLocalizedRecoverySuggestion=Please check your connection to your device., DVTRadarComponentKey=261622, NSLocalizedDescription=Failed to start remote service "com.apple.instruments.remoteserver.DVTSecureSocketProxy" on device.}
2021-06-17 16:48:31.731 mlaunch[4874:753833] Thread Pool Worker DTDKRemoteDeviceConnection: Unable to start com.apple.instruments.remoteserver.DVTSecureSocketProxy on device ???00008030-001C48A02682802E???. Falling back to service without proxy.
2021-06-17 16:48:31.769 mlaunch[4874:753811]  DTDKRemoteDeviceConnection: Failed to start remote service "com.apple.instruments.remoteserver" on device. Error: Error Domain=com.apple.dtdevicekit Code=811 "Failed to start remote service "com.apple.instruments.remoteserver" on device." UserInfo={NSUnderlyingError=0x7fe3578479c0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653150 "The service is invalid." UserInfo={MobileDeviceErrorCode=(0xE8000022), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001188543b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000118863c61 __63-[DTDKRemoteDeviceConnection startFirstServiceOf:unlockKeybag:]_block_invoke + 626
	2   DTDeviceKitBase                     0x0000000118863320 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_3 + 22
	3   DTDeviceKitBase                     0x00000001188564f8 __DTDKExecuteInSession_block_invoke_2 + 35
	4   DTDeviceKitBase                     0x0000000118855bda __DTDKExecuteWithConnection_block_invoke_2 + 218
	5   DTDeviceKitBase                     0x0000000118855ad7 __DTDKExecuteWithConnection_block_invoke + 106
	6   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	7   libdispatch.dylib                   0x00007fff201855ce _dispatch_lane_barrier_sync_invoke_and_complete + 60
	9   DVTFoundation                       0x000000011674c65e -[DVTDispatchLock performLockedBlock:] + 60
	10  DTDeviceKitBase                     0x00000001188559d8 DTDKExecuteWithConnection + 226
	8   DVTFoundation                       0x000000011677948a DVTDispatchBarrierSync + 208
	11  DTDeviceKitBase                     0x000000011885639c DTDKExecuteInSession + 239
	12  DTDeviceKitBase                     0x0000000118863170 __48-[DTDKRemoteDeviceConnection futureWithSession:]_block_invoke_2 + 131
	13  DVTFoundation                       0x0000000116776931 __DVT_CALLING_CLIENT_BLOCK__ + 7
	14  DVTFoundation                       0x000000011677855b __DVTDispatchAsync_block_invoke + 1191
	15  libdispatch.dylib                   0x00007fff20177623 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x00007fff2017e5ea _dispatch_lane_serial_drain + 606
	18  libdispatch.dylib                   0x00007fff2017f0e0 _dispatch_lane_invoke + 417
	19  libdispatch.dylib                   0x00007fff20188c0d _dispatch_workloop_worker_thread + 811
	20  libsystem_pthread.dylib             0x00007fff2031f45d _pthread_wqthread + 314
	21  libsystem_pthread.dylib             0x00007fff2031e42f start_wqthread + 15
), DVTRadarComponentKey=261622, NSLocalizedDescription=The service is invalid.}}, NSLocalizedRecoverySuggestion=Please check your connection to your device., DVTRadarComponentKey=261622, NSLocalizedDescription=Failed to start remote service "com.apple.instruments.remoteserver" on device.}
warning MT1043: Failed to launch the application using the instruments service. Will try launching the app using gdb service.
Launching 'com.hasc.mobilelink' on the device 'Eder???s iPhone'
Xamarin.Hosting: Mounting developer image on 'Eder???s iPhone'
2021-06-17 16:48:32.664 mlaunch[4874:753706] [MT] DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fe35782e1f0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.5/DeveloperDiskImage.dmg'>', error=-402653066: Error Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for development." UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage, NSUnderlyingError=0x7fe3776257a0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653066 "Could not support development." UserInfo={MobileDeviceErrorCode=(0xE8000076), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001188543b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000118890674 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x000000011889108b __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff201855ce _dispatch_lane_barrier_sync_invoke_and_complete + 60
	5   DTDeviceKitBase                     0x0000000118890dca -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 185
	6   mlaunch                             0x000000010465e259 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x000000014d2cac8f 0x0 + 5589740687
	8   ???                                 0x000000014d2cab23 0x0 + 5589740323
	9   ???                                 0x000000014d2436fb 0x0 + 5589186299
	10  ???                                 0x000000014d1cca82 0x0 + 5588699778
	11  ???                                 0x00000001164acf26 0x0 + 4668968742
	12  ???                                 0x00000001164acbdb 0x0 + 4668967899
	13  ???                                 0x000000014d1cc8b3 0x0 + 5588699315
	14  ???                                 0x000000014d1cc77e 0x0 + 5588699006
	15  ???                                 0x000000014d1cc675 0x0 + 5588698741
	16  ???                                 0x0000000115dbd861 0x0 + 4661696609
	17  mlaunch                             0x000000010474af53 mono_jit_runtime_invoke + 1603
	18  mlaunch                             0x0000000104880dcf mono_runtime_try_invoke + 143
	19  mlaunch                             0x0000000104883c7f mono_runtime_invoke + 95
	20  mlaunch                             0x000000010465b786 xamarin_invoke_trampoline + 6134
	21  mlaunch                             0x000000010465ce77 xamarin_arch_trampoline + 119
	22  mlaunch                             0x000000010465e0de xamarin_x86_64_common_trampoline + 118
	23  Foundation                          0x00007fff210f1bc1 __NSThreadPerformPerform + 204
	24  CoreFoundation                      0x00007fff2041b6dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x00007fff2041b644 __CFRunLoopDoSource0 + 180
	26  CoreFoundation                      0x00007fff2041b3ba __CFRunLoopDoSources0 + 242
	27  CoreFoundation                      0x00007fff20419dc8 __CFRunLoopRun + 897
	28  CoreFoundation                      0x00007fff20419380 CFRunLoopRunSpecific + 567
	29  Foundation                          0x00007fff210d1647 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
	30  Foundation                          0x00007fff2115a975 -[NSRunLoop(NSRunLoop) runUntilDate:] + 103
	31  mlaunch                             0x000000010465e259 xamarin_dyn_objc_msgSend + 217
	32  ???                                 0x00000001164a4aaf 0x0 + 4668934831
	33  ???                                 0x000000014d1bfdfb 0x0 + 5588647419
	34  ???                                 0x000000014d1bf5af 0x0 + 5588645295
	35  ???                                 0x00000001161a63fb 0x0 + 4665795579
	36  ???                                 0x00000001131d5823 0x0 + 4615657507
	37  ???                                 0x00000001131d5c91 0x0 + 4615658641
	38  mlaunch                             0x000000010474af53 mono_jit_runtime_invoke + 1603
	39  mlaunch                             0x000000010487f3c8 mono_runtime_invoke_checked + 136
	40  mlaunch                             0x0000000104886795 mono_runtime_exec_main_checked + 117
	41  mlaunch                             0x00000001046a629c mono_jit_exec + 364
	42  mlaunch                             0x00000001046a9338 mono_main + 8728
	43  mlaunch                             0x000000010465eaab xamarin_main + 1179
	45  libdyld.dylib                       0x00007fff2033df5d start + 1
	44  mlaunch                             0x000000010465f9b4 main + 36
), DVTRadarComponentKey=261622, NSLocalizedDescription=Could not support development.}}, NSLocalizedRecoverySuggestion=If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device., NSLocalizedFailure=This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running., DVTRadarComponentKey=487927, NSLocalizedDescription=Failed to prepare device for development.}
warning HE0030: Could not mount developer tools on 'Eder???s iPhone': Failed to prepare device for development.
warning HE0031: Failed to mount developer tools on 'Eder???s iPhone'.
Xamarin.Hosting: Mounting developer image on 'Eder???s iPhone'
2021-06-17 16:48:33.772 mlaunch[4874:753706] [MT] DTDeviceKit: Failed to mount DDI from '<DVTFilePath:0x7fe35782e1f0:'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/14.5/DeveloperDiskImage.dmg'>', error=-402653066: Error Domain=com.apple.dtdevicekit Code=806 "Failed to prepare device for development." UserInfo={AssociatedMobileDeviceFunction=AMDeviceMountImage, NSUnderlyingError=0x7fe3800aa4e0 {Error Domain=com.apple.dt.MobileDeviceErrorDomain Code=-402653066 "Could not support development." UserInfo={MobileDeviceErrorCode=(0xE8000076), com.apple.dtdevicekit.stacktrace=(
	0   DTDeviceKitBase                     0x00000001188543b8 DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000118890674 -[DTDKMobileDeviceToken _mountDeveloperDiskImage:withError:] + 1024
	2   DTDeviceKitBase                     0x000000011889108b __58-[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:]_block_invoke + 609
	3   libdispatch.dylib                   0x00007fff20178806 _dispatch_client_callout + 8
	4   libdispatch.dylib                   0x00007fff201855ce _dispatch_lane_barrier_sync_invoke_and_complete + 60
	5   DTDeviceKitBase                     0x0000000118890dca -[DTDKMobileDeviceToken mountDeveloperDiskImageWithError:] + 185
	6   mlaunch                             0x000000010465e259 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x000000014d2cac8f 0x0 + 5589740687
	8   ???                                 0x000000014d2cab23 0x0 + 5589740323
	9   ???                                 0x000000014d2436fb 0x0 + 5589186299
	10  ???                                 0x000000014d1cca82 0x0 + 5588699778
	11  ???                                 0x00000001164acf26 0x0 + 4668968742
	13  ???                                 0x000000014d1cc8b3 0x0 + 5588699315
	12  ???                                 0x00000001164acbdb 0x0 + 4668967899
	14  ???                                 0x000000014d1cc77e 0x0 + 5588699006
	15  ???                                 0x000000014d1cc675 0x0 + 5588698741
	16  ???                                 0x0000000115dbd861 0x0 + 4661696609
	17  mlaunch                             0x000000010474af53 mono_jit_runtime_invoke + 1603
	18  mlaunch                             0x0000000104880dcf mono_runtime_try_invoke + 143
	19  mlaunch                             0x0000000104883c7f mono_runtime_invoke + 95
	20  mlaunch                             0x000000010465b786 xamarin_invoke_trampoline + 6134
	21  mlaunch                             0x000000010465ce77 xamarin_arch_trampoline + 119
	23  Foundation                          0x00007fff210f1bc1 __NSThreadPerformPerform + 204
	22  mlaunch                             0x000000010465e0de xamarin_x86_64_common_trampoline + 118
	24  CoreFoundation                      0x00007fff2041b6dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	25  CoreFoundation                      0x00007fff2041b644 __CFRunLoopDoSource0 + 180
	27  CoreFoundation                      0x00007fff20419dc8 __CFRunLoopRun + 897
	26  CoreFoundation                      0x00007fff2041b3ba __CFRunLoopDoSources0 + 242
	28  CoreFoundation                      0x00007fff20419380 CFRunLoopRunSpecific + 567
	29  Foundation                          0x00007fff210d1647 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
	30  Foundation                          0x00007fff2115a975 -[NSRunLoop(NSRunLoop) runUntilDate:] + 103
	31  mlaunch                             0x000000010465e259 xamarin_dyn_objc_msgSend + 217
	32  ???                                 0x00000001164a4aaf 0x0 + 4668934831
	33  ???                                 0x000000014d1bfdfb 0x0 + 5588647419
	35  ???                                 0x00000001161a63fb 0x0 + 4665795579
	34  ???                                 0x000000014d1bf5af 0x0 + 5588645295
	36  ???                                 0x00000001131d5823 0x0 + 4615657507
	37  ???                                 0x00000001131d5c91 0x0 + 4615658641
	38  mlaunch                             0x000000010474af53 mono_jit_runtime_invoke + 1603
	39  mlaunch                             0x000000010487f3c8 mono_runtime_invoke_checked + 136
	40  mlaunch                             0x0000000104886795 mono_runtime_exec_main_checked + 117
	41  mlaunch                             0x00000001046a629c mono_jit_exec + 364
	42  mlaunch                             0x00000001046a9338 mono_main + 8728
	45  libdyld.dylib                       0x00007fff2033df5d start + 1
	43  mlaunch                             0x000000010465eaab xamarin_main + 1179
	44  mlaunch                             0x000000010465f9b4 main + 36
), DVTRadarComponentKey=261622, NSLocalizedDescription=Could not support development.}}, NSLocalizedRecoverySuggestion=If you are certain that Xcode supports development on this device, try disconnecting and reconnecting the device., NSLocalizedFailure=This operation can fail if the version of the OS on the device is newer than the version of Xcode that is running., DVTRadarComponentKey=487927, NSLocalizedDescription=Failed to prepare device for development.}
warning HE0030: Could not mount developer tools on 'Eder???s iPhone': Failed to prepare device for development.
warning HE0031: Failed to mount developer tools on 'Eder???s iPhone'.

**Comment by jsuarezruiz** [comment]
Can you still launch the application manually by tapping on it? I believe this issue is due to XCode 12.5 not supporting iOS devices updated to iOS higher version. 
@Redth Should we move this issue to Xamarin-ios?

**Comment by ederbond** [comment]
Yes, I can maually launch the application by tapping on it's icon on the screen of my phone and it works just fine. I just can't attach it to VS to debug.

**Comment by jfversluis** [comment]
Seems to be working on newer versions? Going to assume it's fixed then. If not, please let us know :)
