### ISSUE TITLE
[Bug] CollectionView FooterTemplate is not displayed if Footer="-" is not set

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#14359]
**Xamarin.forms 5.0.0.2012:**

_CollectionView FooterTemplate is not displayed if `Footer="-"` is not set_

The footer below will not be displayed unless I set `Footer="-"` in `<CollectionView x:Name="CollectionView1" Footer="">`
```
<CollectionView.FooterTemplate>
    <DataTemplate>
        <StackLayout HeightRequest="100">
            <ActivityIndicator IsRunning="{Binding IsLoadingMore}" VerticalOptions="Center" HorizontalOptions="Center"/>
        </StackLayout>
    </DataTemplate>
</CollectionView.FooterTemplate>
```

Apparently Footer needs some value in order to display `<CollectionView.FooterTemplate>` It took me a while to figure this out...

**Comment by maximusfatigue** [comment]
<CollectionView.FooterTemplate>

        <StackLayout HeightRequest="100">
            <ActivityIndicator IsRunning="{Binding IsLoadingMore}" VerticalOptions="Center" HorizontalOptions="Center"/>
        </StackLayout>
      <StackLayout Padding="0"/>      
    

</CollectionView.FooterTemplate>

Does this work?

**Comment by jsuarezruiz** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout#display-a-templated-header-and-footer

The binding context of FooterTemplate is the value of Footer. Adding Footer="{Binding .}" should make it do what you want.

**Comment by jfversluis** [comment]
No response here, assuming this is resolved!
