### ISSUE TITLE
[Enhancement] Extend the Properties of SwitchCell

### ISSUE THREAD

**Issue by darrabam** [xamarin/Xamarin.Forms#14361]
## Summary
Extend the properties of the SwitchCell to allow for changing font family, size, font attributes, color, accepts formatted text ....etc. SwitchCell is a very useful controller, but very limited.

## Intended Use Case
Minimize the need to do custom renderers for SwitchCell.

**Comment by jfversluis** [comment]
Thanks for the suggestion! At this time we won't be adding any new functionality to Xamarin.Forms anymore unless we really have to. If this is something that you are still interested in, please express your wishes on the .NET MAUI repo :)

Thanks!
