### ISSUE TITLE
[Bug] Null reference at Xamarin.Forms.Platform.iOS.ListViewRenderer+ListViewDataSource.GetCell()

### ISSUE THREAD

**Issue by matteofabris** [xamarin/Xamarin.Forms#14365]
### Description
When opening a ContentView (by a button tap) containing a ListView and instantly switching to another ContentView (again by another button tap) destroying the previous one, the app crashes with this exception:

`System.NullReferenceException: Object reference not set to an instance of an object\  at Xamarin.Forms.Platform.iOS.ListViewRenderer+ListViewDataSource.GetCell (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) <0x102646b90 + 0x002e4> in <fa582f303d264dd7807d18dc69f43f08#2f27a5e9f1964ddcca8f4d22684e1b76>:0 \  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x10207a570 + 0x0002f> in <ad1be307855442e4b2cb88e33f94f908#2f27a5e9f1964ddcca8f4d22684e1b76>:0 \  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x10207a4e0 + 0x00043> in <ad1be307855442e4b2cb88e33f94f908#2f27a5e9f1964ddcca8f4d22684e1b76>:0 \  at MobileByMe.iOS.Application.Main (System.String[] args) <0x1009b3e10 + 0x000ab> in <f483bee7eb5d4506a68db5c40de65754#2f27a5e9f1964ddcca8f4\`

### Steps to Reproduce
1. Tap a button to open a ContentView containing a ListView
2. Tap instantly another button to open another ContentView destroying the previous one

### Expected Behavior
App do not crash and the second ContentView is open regularly

### Actual Behavior
App crashes

### Basic Information
- Version with issue: 5.0.0
- Platform Target Frameworks:
  - iOS:  14

**Comment by jsuarezruiz** [comment]
@matteofabris Could you attach a sample sample where reproduce the issue?. Thanks!

**Comment by jfversluis** [comment]
No response to our request for more info, closing this for now.
