### ISSUE TITLE
[Bug] Fallback Translation of ResX is en-US instead of en-GB 

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#14374]
We've set the neutral NeutralResourcesLanguage to en_GB as described [here](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=macos#specify-the-default-culture) but still get en_US.

### Steps to Reproduce

1. Set NeutralResourcesLanguage in AssemblyInfo.cs to en-GB
2. Add Translations.en-GB.resx, Translations.en-US.resx and Translations.resx (intended as final fallback), all with different translations. 
3. Set your phones language to en and your region for example to NL
4. Use translations on a Page

### Expected Behavior
Translation is from Translations.resx

### Actual Behavior
Text is used from Translations.en-US.resx

### Basic Information

- Version with issue: 4.8.0.1687
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 11

### Workaround

Not known

**Comment by Phil108** [comment]
Filed this again, with more precise description an example code here:

https://github.com/xamarin/Xamarin.Forms/issues/14374
