### ISSUE TITLE
[Bug] AppBoundDomains not activating with XF WebView

### ISSUE THREAD

**Issue by captainjono** [xamarin/Xamarin.Forms#14373]
### Description

App Bound Domains allow `ServiceWorkers` to run under `WKWebView` on iOS. The below article describes how to enable them.
https://webkit.org/blog/10882/app-bound-domains/

I have successfully enabled this feature when using `Xamarin.mac` + `ViewController`, but when using via `Xamarin Forms` [nothing i can do will make AppBoundDomains activate](https://github.com/captainjono/AppBoundDomainTester/issues/1). 

### Steps to Reproduce

1.  Clone https://github.com/captainjono/AppBoundDomainTester/
2.  Build and Deploy `AppBoundTest.Native` to device
3.  Build and Deploy `AppBoundTest.iOS` to device

### Expected Behavior

`Html5test.com` score the same for each build (= `486`)

### Actual Behavior

- `.Native` scores `486` and **activates** ServiceWorker
- `.iOS` scores `>476` and *does not activate* ServiceWorker

### Basic Information

`Console.app` is not reporting anything useful and indicates otherwise the feature has worked. If i do negative testing, i can see it reporting `IsAppBoundDomain: 0` and then i see this flip to ` :1` in consequent logs after doing what i need todo to activate it.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.2 (build 17)
Installation UUID: 4194a1cc-5f0c-44a7-a40e-4e2e15381f41
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
SDK Versions:
	5.0.301
	5.0.203
	5.0.202
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.410
	3.1.409
	3.1.408
	3.1.406
	3.1.405
	3.1.404
	3.1.403
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.7
	5.0.6
	5.0.5
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.16
	3.1.15
	3.1.14
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	2.1.23
	2.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.3 (Visual Studio Community)
Hash: 17fdcf569
Branch: d16-10
Build date: 2021-05-20 15:46:14-0400

=== Xamarin.iOS ===

Version: 14.20.0.3 (Visual Studio Community)
Hash: 17fdcf569
Branch: d16-10
Build date: 2021-05-20 15:46:15-0400

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Build Information ===

Release ID: 810020017
Git revision: 890ad7d9d5b08fa3d325d2c8d6cc202cc79bf500
Build date: 2021-06-10 12:17:16-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.3.0 Darwin Kernel Version 20.3.0
    Thu Jan 21 00:07:06 PST 2021
    root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

```

</details>

### Workaround

Not to use Xamarin forms, and to use Xamarin native, a storyboard and a viewcontroller to host your wkwebview.

**Comment by captainjono** [comment]
After some hacking and ripping im pretty confident that this `LoadUrl` is the offender that is breaking this feature.

https://github.com/xamarin/Xamarin.Forms/blob/ae8e52feb5faacf1890b870eb291b509e5b832e6/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs#L167

 I was able to repo by adapting the WKWebViewRenderer to the native example and repoing the issue, then gutting the cookie code and getting finally started getting a `786` 

Im not that familiar with the intricacies of cookies, but im wondering if this service could instead driven by some combination of `cfg.UserContentController.AddUserScript(.., WKUserScriptInjectionTime.AtDocumentStart, true)` and/or `cfg.UserContentController.AddScriptMessageHandler(..)` since the code seems to be using `JS` to lookup `document.cookies` and _startup_ so it can sync the wkwebview with the xf webview wrapper ?
        
```

**Comment by captainjono** [comment]
@davidortinau Right now, it seems this workaround is fine for my current use-case. this is more of a long term support issue.

**Comment by jfversluis** [comment]
Seems there is a workaround and otherwise not much traction here, going to close this for now. Thanks!
