### ISSUE TITLE
Waiting for bug fix to be released

### ISSUE THREAD

**Issue by KrisVandermotten** [xamarin/Xamarin.Forms#14378]
The bug reported in #13315 was fixed by #13460 back in May.

That's great, but we're still waiting for a release containing this fix. Are there any plans for a release?

Are we supposed to wait for MAUI?

**Comment by amahera** [comment]
@KrisVandermotten, as a workaround - the setting of path stroke thickness = 0 works for me (StrokeThickness="0")

**Comment by KrisVandermotten** [comment]
@amahera Unfortunately that doesn't work for us.

We are now testing with release 5.0.0.2083 from earlier this week.

**Comment by KrisVandermotten** [comment]
Release 5.0.0.2083 tested out OK. Thanks for releasing, I'm closing this issue.
