### ISSUE TITLE
[Bug] Picker control in Xamarin WPF app does not dropdown if you click the text

### ISSUE THREAD

**Issue by bhaynesch** [xamarin/Xamarin.Forms#14388]
### Description
My app uses Picker control in multiple places and all of them now have an editable text control in them.  I have to click the arrow on the right to actually drop down the control.  I upgraded my app to 5.0.0.2012 (from a 4.5 version) and this is the new behavior.  On Android and iOS it still drops down if you click the text area.  Either need to fix the control or provide a property to prevent editing.  UPDATE:  I did figure out that in WPF, it's now support "type ahead" so people can manually find items in a list by typing.  My dropdowns aren't complex enough to need this.  I need to turn it off.
### Steps to Reproduce

1. Create a Picker control in a WPF app with a list of text items
2. Run the app and click on the text area of the Picker control.  It now highlights the text and allows editing.
3. 

### Expected Behavior
Clicking in text area should drop down the control
### Actual Behavior
Clicking in text area is highlighting the text and allowing editing
### Basic Information

- Version with issue:5.0.0.2012
- Last known good version:4.5
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - WPF 5.0.0.2012
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Reproduction Link

Cannot provide.
### Workaround

No.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
