### ISSUE TITLE
Distance operator overloads.

### ISSUE THREAD

**Issue by donbing** [xamarin/Xamarin.Forms#14387]
## Summary
In order that can compare distances for ordering results
Maps.Distance should have <, <=, >, >= overloads.

In order that I get useful feedback in tests asserting on distance values, 
I want a .ToString() override on Maps.Distance that will show me the value and unit of measure

## API Changes

<, <=, >, >= overrides and .ToString() override to be added to Maps.Distance class

## Intended Use Case
Ordering location results in a list view control

**Comment by jfversluis** [comment]
This would be really cool! Unfortunately, we won't be able to add this for Xamarin.Forms any more. If you're still interested in this, make sure to open a proposal on the .NET MAUI repo if there isn't one already.

Thanks!
