### ISSUE TITLE
[UWP] [WinUI] How to use WinUI 2.6 with Xamarin.Forms and UWP?

### ISSUE THREAD

**Issue by Agredo** [xamarin/Xamarin.Forms#14408]
Is there a way to use the lates version of WinUI (2.6) in Xamarin.Forms 5?

**Comment by melicaster** [comment]
Yes. But it seems `webview` doesn't work on UWP, it will show blank. However, you can move to WinUI 3 if you developing for Windows only. See https://docs.microsoft.com/en-us/windows/apps/winui/winui3/ to get started. They have a lot of similarity. Shouldn't be hard to get started.

**Comment by Agredo** [comment]
@melicaster  Yeah this already works but and I created a test app but what if I want want to use WinUI 2.6 with my Xamarin.Forms UWP app? I installes for the UWP App the WinUI Nuget 2.6.1 but it does not change anything

**Comment by jfversluis** [comment]
Hope you got something working by now!
