### ISSUE TITLE
[Bug] Error ITMS-90546

### ISSUE THREAD

**Issue by amr-alaa** [xamarin/Xamarin.Forms#14413]
### Description
after updating the application and VS2019 i can not get my app on ios app store, however it is life 3 since years ago with multi updates within this times 
the app is passed from Xcode and transporter however on test flight i got the 90546 error  
### Steps to Reproduce
1. checket every posible solution on the internet
2. updated the VS2019 to V16.10.3
3. created a new Xamain.ios app and add the depindancies on it .
### Expected Behavior
the transporter application verified the app and it really pass , it is also run on emulator but the app store reject it
### Actual Behavior
itms-90546 error 
### Basic Information
- Version with issue: VS 2019 16.10.3
- Last known good version: VS 2019 16.9
- iOS: 14.5
- NuGet Packages:
<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Newtonsoft.Json">
    <PackageReference Include="Plugin.FirebasePushNotification" Version="3.3.10" />
    <PackageReference Include="Plugin.FirebasePushNotification">
    <PackageReference Include="Plugin.LocalNotification" Version="6.1.0" />
    <PackageReference Include="Plugin.LocalNotification">
    <PackageReference Include="Prism.Forms" Version="8.0.0.1909" />
    <PackageReference Include="Prism.Forms" Version="8.1.97" />
    <PackageReference Include="Prism.Forms">
    <PackageReference Include="Prism.Unity" Version="7.2.0.1422" />
    <PackageReference Include="Prism.Unity.Forms" Version="8.0.0.1909" />
    <PackageReference Include="Prism.Unity.Forms" Version="8.1.97" />
    <PackageReference Include="Prism.Unity.Forms">
    <PackageReference Include="Prism.Wpf" Version="7.2.0.1422" />
    <PackageReference Include="Prism.Wpf">
    <PackageReference Include="RestSharp" Version="106.11.7" />
    <PackageReference Include="RestSharp">
    <PackageReference Include="Syncfusion.Licensing">
    <PackageReference Include="Syncfusion.Xamarin.Core">
    <PackageReference Include="Syncfusion.Xamarin.SfPdfViewer" Version="19.1.0.69" />
    <PackageReference Include="Syncfusion.Xamarin.SfPdfViewer">
    <PackageReference Include="Syncfusion.Xamarin.SfRangeSlider">
    <PackageReference Include="System.Security.Principal.Windows" Version="4.7.0" />
    <PackageReference Include="Unity">
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle" Version="3.0.0.5" />
    <PackageReference Include="Xam.Plugins.Forms.ImageCircle">
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.3" />
    <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.2.4" />
    <PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0.7" />
    <PackageReference Include="Xamarin.CommunityToolkit" Version="1.0.2" />
    <PackageReference Include="Xamarin.CommunityToolkit">
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Essentials" Version="1.6.1" />
    <PackageReference Include="Xamarin.Essentials">
    <PackageReference Include="Xamarin.Essentials.Interfaces" Version="1.5.3.2" />
    <PackageReference Include="Xamarin.Essentials.Interfaces" Version="1.6.1" />
    <PackageReference Include="Xamarin.FFImageLoading" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading">
    <PackageReference Include="Xamarin.FFImageLoading.Forms" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
    <PackageReference Include="Xamarin.FFImageLoading.Transformations" Version="2.4.11.982" />
    <PackageReference Include="Xamarin.FFImageLoading.Transformations">
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1364" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1687" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.1931" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Forms">
    <PackageReference Include="Xamarin.Forms.Maps" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Forms.Maps">
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.1931" />
    <PackageReference Include="Xamarin.Forms.Visual.Material" Version="5.0.0.2012" />
    <PackageReference Include="Xamarin.Forms.Visual.Material">
    <PackageReference Include="ZXing.Net">
    <PackageReference Include="ZXing.Net.Mobile" Version="2.4.1" />
    <PackageReference Include="ZXing.Net.Mobile">
    <PackageReference Include="ZXing.Net.Mobile.Forms" Version="2.4.1" />
    <PackageReference Include="ZXing.Net.Mobile.Forms">

### Screenshots
![image](https://user-images.githubusercontent.com/2277563/125316950-e5529380-e338-11eb-9c7a-a62d77044a51.png)

### Environment
<details><summary>Show/Hide Visual Studio info</summary>
```
VS 2019 16.10.3
Microsoft Visual Studio Enterprise 2019
Version 16.10.3
VisualStudio.16.Release/16.10.3+31424.327
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Enterprise
Architecture Diagrams and Analysis Tools   00433-90000-00004-AA864
Microsoft Architecture Diagrams and Analysis Tools
Visual C++ 2019   00433-90000-00004-AA864
Microsoft Visual C++ 2019
.NET Portability Analyzer   1.1.10808.0
Evaluates portability of assemblies across .NET platforms.
ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools
ASA Service Provider   1.0
ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019
ASP.NET Core Blazor Language Services   16.0.19307.2
ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/
Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0
Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.
Azure Data Lake Tools for Visual Studio   2.6.3000.0
Microsoft Azure Data Lake Tools for Visual Studio
Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.3000.0
Microsoft Azure Stream Analytics Tools for Visual Studio
Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.
C# Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Cookiecutter   16.10.21111.19
Provides tools for finding, instantiating and customizing templates in cookiecutter format.
Devart Entity Developer   6.6.894.0
Devart Entity Developer
Copyright © 2008-2019 Devart. All rights reserved.
Web: www.devart.com/entitydeveloper 
Support: support@devart.com
Developer News   1.3.1
Bring Back Developer News!
Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.
Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
GitHub.VisualStudio   2.11.106.19330
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info
Linux Core Dump Debugging   1.0.9.31313
Enables debugging of Linux core dumps.
Microsoft Azure HDInsight Azure Node   2.6.3000.0
HDInsight Node under Azure Node
Microsoft Azure Hive Query Language Service   2.6.3000.0
Language service for Hive query
Microsoft Azure Stream Analytics Language Service   2.6.3000.0
Language service for Azure Stream Analytics
Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1
Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project
Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package
Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.
NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info
Python   16.10.21111.19
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
Python - Conda support   16.10.21111.19
Conda support for Python projects.
Python - Django support   16.10.21111.19
Provides templates and integration for the Django web framework.
Python - Profiling support   16.10.21111.19
Profiling support for Python projects.
Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.
Silverlight for Visual Studio 2017   1.0
Unofficial support for Silverlight projects in Visual Studio 2017
SlowCheetah - XML config transforms   1.0
This package enables you to transform your app.config or any other XML file based on the build configuration. It also adds additional tooling to help you create XML transforms.
Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info
SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools
SQL Server Reporting Services   15.0.19528.0
Microsoft SQL Server Reporting Services Designers 
Version 15.0.19528.0
Syncfusion ASP.NET Core Project Templates   19.2.0.44
Provides project templates for creating an ASP.NET Core Web Application using Syncfusion ASP.NET Core components.
Syncfusion EJ2 Web Conversion and Migration   13.4.0.53
Converts and migrates a web project into a Syncfusion web project.
SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info
ToolWindowHostedEditor   1.0
Hosting json editor into a tool window
TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio
Visual Basic Tools   3.10.0-4.21318.11+7ceb633154acb9d716fd3eb2b6df1a0468d8e416
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
Visual C++ for Linux Development   1.0.9.31313
Visual C++ for Linux Development
Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.
Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
VisualStudio.DeviceLog   1.0
Information about my package
VisualStudio.Foo   1.0
Information about my package
VisualStudio.Mac   1.0
Mac Extension for Visual Studio
Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0
Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


=== Visual Studio Community 2019 for Mac ===
Version 8.10.3 (build 15)
Installation UUID: 8f709e80-c4b1-465e-bb80-05a7fd430277
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
	Package version: 612000140
=== Mono Framework MDK ===
Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140
=== Roslyn (Language Service) ===
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb
=== NuGet ===
Version: 5.9.0.7134
=== .NET Core SDK ===
SDK: /usr/local/share/dotnet/sdk/5.0.301/Sdks
SDK Versions:
	5.0.301
	5.0.203
	5.0.202
	5.0.101
	3.1.410
	3.1.409
	3.1.408
	3.1.200
	3.1.102
	3.1.100
	2.1.524
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks
=== .NET Core Runtime ===
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.7
	5.0.6
	5.0.5
	5.0.1
	3.1.16
	3.1.15
	3.1.14
	3.1.2
	3.1.0
	2.1.28
	2.1.23
	2.1.16
	2.1.15
	2.1.14
=== .NET Core 3.1 SDK ===
SDK: 3.1.410
=== Xamarin.Profiler ===
Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
=== Updater ===
Version: 11
=== Xamarin.Android ===
Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/amralaa/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3
Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0
=== Microsoft OpenJDK for Mobile ===
Java SDK: /Users/amralaa/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
=== Android SDK Manager ===
Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC
=== Android Device Manager ===
Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC
=== Apple Developer Tools ===
Xcode 12.5 (18205)
Build 12E262
=== Xamarin.Mac ===
Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400
=== Xamarin.iOS ===
Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400
=== Xamarin Designer ===
Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC
=== Build Information ===
Release ID: 810030015
Git revision: 9579bfad0898e06fdd77b8f4127bdcb5412a5b38
Build date: 2021-06-17 13:42:21-04
Build branch: release-8.10
=== Operating System ===
Mac OS X 10.16.0
Darwin 20.2.0 Darwin Kernel Version 20.2.0
    Wed Dec  2 20:39:59 PST 2020
    root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
```

### Screenshots
![image](https://user-images.githubusercontent.com/2277563/125316950-e5529380-e338-11eb-9c7a-a62d77044a51.png)

### Workaround
can not find any one till now
even when created a new app and add the fragrances and nu-get packages 
i did tried to build the project from mac side 
but i gor the following error 

`
/usr/local/share/dotnet/sdk/5.0.301/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(5,5): Error MSB4018: The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages'.
  at NuGet.Packaging.FallbackPackagePathResolver..ctor (System.String userPackageFolder, System.Collections.Generic.IEnumerable`1[T] fallbackPackageFolders) [0x00064] in <4de227ea4c59460d9c861f668d44e958>:0 
  at Microsoft.NET.Build.Tasks.NuGetPackageResolver..ctor (System.String userPackageFolder, System.Collections.Generic.IEnumerable`1[T] fallbackPackageFolders) [0x00006] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver (System.Collections.Generic.IEnumerable`1[T] packageFolders) [0x00018] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver (NuGet.ProjectModel.LockFile lockFile) [0x0002a] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheWriter..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00030] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader.CreateReaderFromDisk (Microsoft.NET.Build.Tasks.ResolvePackageAssets task, System.Byte[] settingsHash) [0x0003a] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets+CacheReader..ctor (Microsoft.NET.Build.Tasks.ResolvePackageAssets task) [0x00015] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups () [0x00000] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore () [0x00018] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.NET.Build.Tasks.TaskBase.Execute () [0x0002e] in <773f053461084f66823cf28076611939>:0 
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:578 
  at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002b9] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:807  (MSB4018) (TPSociety.iOS)
`
[log.txt](https://github.com/xamarin/Xamarin.Forms/files/6802844/log.txt)

**Comment by amr-alaa** [comment]
i solved it

just create a new project then copy the assets folder m then copy the same icons with same names and sizes 

files are with the following names and sizes

{
    "images":[
        {
            "idiom":"iphone",
            "size":"20x20",
            "scale":"2x",
            "filename":"Icon-App-20x20@2x.png"
        },
        {
            "idiom":"iphone",
            "size":"20x20",
            "scale":"3x",
            "filename":"Icon-App-20x20@3x.png"
        },
        {
            "idiom":"iphone",
            "size":"29x29",
            "scale":"1x",
            "filename":"Icon-App-29x29@1x.png"
        },
        {
            "idiom":"iphone",
            "size":"29x29",
            "scale":"2x",
            "filename":"Icon-App-29x29@2x.png"
        },
        {
            "idiom":"iphone",
            "size":"29x29",
            "scale":"3x",
            "filename":"Icon-App-29x29@3x.png"
        },
        {
            "idiom":"iphone",
            "size":"40x40",
            "scale":"1x",
            "filename":"Icon-App-40x40@1x.png"
        },
        {
            "idiom":"iphone",
            "size":"40x40",
            "scale":"2x",
            "filename":"Icon-App-40x40@2x.png"
        },
        {
            "idiom":"iphone",
            "size":"40x40",
            "scale":"3x",
            "filename":"Icon-App-40x40@3x.png"
        },
        {
            "idiom":"iphone",
            "size":"57x57",
            "scale":"1x",
            "filename":"Icon-App-57x57@1x.png"
        },
        {
            "idiom":"iphone",
            "size":"57x57",
            "scale":"2x",
            "filename":"Icon-App-57x57@2x.png"
        },
        {
            "idiom":"iphone",
            "size":"60x60",
            "scale":"1x",
            "filename":"Icon-App-60x60@1x.png"
        },
        {
            "idiom":"iphone",
            "size":"60x60",
            "scale":"2x",
            "filename":"Icon-App-60x60@2x.png"
        },
        {
            "idiom":"iphone",
            "size":"60x60",
            "scale":"3x",
            "filename":"Icon-App-60x60@3x.png"
        },
        {
            "idiom":"iphone",
            "size":"76x76",
            "scale":"1x",
            "filename":"Icon-App-76x76@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"20x20",
            "scale":"1x",
            "filename":"Icon-App-20x20@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"20x20",
            "scale":"2x",
            "filename":"Icon-App-20x20@2x.png"
        },
        {
            "idiom":"ipad",
            "size":"29x29",
            "scale":"1x",
            "filename":"Icon-App-29x29@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"29x29",
            "scale":"2x",
            "filename":"Icon-App-29x29@2x.png"
        },
        {
            "idiom":"ipad",
            "size":"40x40",
            "scale":"1x",
            "filename":"Icon-App-40x40@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"40x40",
            "scale":"2x",
            "filename":"Icon-App-40x40@2x.png"
        },
        {
          "size" : "50x50",
          "idiom" : "ipad",
          "filename" : "Icon-Small-50x50@1x.png",
          "scale" : "1x"
        },
        {
          "size" : "50x50",
          "idiom" : "ipad",
          "filename" : "Icon-Small-50x50@2x.png",
          "scale" : "2x"
        },
        {
            "idiom":"ipad",
            "size":"72x72",
            "scale":"1x",
            "filename":"Icon-App-72x72@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"72x72",
            "scale":"2x",
            "filename":"Icon-App-72x72@2x.png"
        },
        {
            "idiom":"ipad",
            "size":"76x76",
            "scale":"1x",
            "filename":"Icon-App-76x76@1x.png"
        },
        {
            "idiom":"ipad",
            "size":"76x76",
            "scale":"2x",
            "filename":"Icon-App-76x76@2x.png"
        },
        {
            "idiom":"ipad",
            "size":"76x76",
            "scale":"3x",
            "filename":"Icon-App-76x76@3x.png"
        },
        {
            "idiom":"ipad",
            "size":"83.5x83.5",
            "scale":"2x",
            "filename":"Icon-App-83.5x83.5@2x.png"
        },
        {
          "size" : "1024x1024",
          "idiom" : "ios-marketing",
          "filename" : "ItunesArtwork@2x.png",
          "scale" : "1x"
        }
    ],
    "info":{
        "version":1,
        "author":"makeappicon"
    }
}

**Comment by jfversluis** [comment]
Glad to see you resolved it, thanks for letting us know!
