### ISSUE TITLE
[Bug] Errors with google.android.material

### ISSUE THREAD

**Issue by bjkramer0926** [xamarin/Xamarin.Forms#14411]
### Steps to Reproduce

No app changes, but get errors:

seems to be related to xamarin,google.android.material

/Users/briankramer/Projects/SWLog/SWLog.Android/obj/Debug/android/src/crc64720bb2db43a66fe9/TabbedPageRenderer.java(8,8): Error JAVAC0000: error: TabbedPageRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
public class TabbedPageRenderer
(JAVAC0000) (SWLog.Android) javac

/Users/briankramer/Projects/SWLog/SWLog.Android/obj/Debug/android/src/crc643f46942d9dd1fff9/ShellItemRenderer.java(8,8): Error JAVAC0000: error: ShellItemRenderer is not abstract and does not override abstract method onNavigationItemSelected(MenuItem) in OnItemSelectedListener
public class ShellItemRenderer
(JAVAC0000) (SWLog.Android) javac

latest vis stud on mac
all latest updates

### Basic Information

- Version with issue:
- Last known good version: 1.3.0.1
- Platform Target Frameworks: 
  - Android:  
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

=== Visual Studio Community 2019 for Mac ===

Version 8.10.5 (build 16)
Installation UUID: b167b251-7b0b-49cc-b9a5-c4ce205e0bab
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: Not installed
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: Not installed

=== .NET Core 3.1 SDK ===

SDK: Not installed

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/briankramer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/briankramer/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Build Information ===

Release ID: 810050016
Git revision: d6bd382154950cedf91ffdf19704a7c61888a3b4
Build date: 2021-07-02 06:38:37-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Snippet Manager Addin 1.1
Xamarin.Forms HotReload extension 1.4.0
NuGet Package Management Extensions 0.27
.NET Core support for Mono.Debugging 8.0.5

</details>

**Comment by jpobst** [comment]
More info here: https://github.com/xamarin/AndroidX/issues/335

**Comment by jfversluis** [comment]
Linked issue shows as resolved
