### ISSUE TITLE
[Bug] Visual Studio 2019 MacOS - Cannot update nugets on iOS project if WatchApp is referenced

### ISSUE THREAD

**Issue by AndreasReitberger** [xamarin/Xamarin.Forms#14416]
### Description
Whenever I want to update my nugets, also the Xamarin.Forms nuget, I need to remove the reference to the WatchApp project first.
Otherwise I cannot update my nugets on my.

### Steps to Reproduce

1.  Create a WatchApp and link it to the iOS project (reference) 
2.  Try to update Xamarin.Forms on the iOS project (Shared and Android seems to be fine).
3.  See that VS gets an error => Cannot update nugets
4.  Unlink the reference to the WatchApp and try again.

### Expected Behavior
Update should also work if a WatchApp is referenced in the iOS Project.
### Actual Behavior
No updates possible while a reference is set to the iOS Project.

### Basic Information

- Version with issue: Latest VS
- NuGet Packages: Xamarin.Forms and other targeting the iOS project

### Workaround

Remove reference before updating the nugets.

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks!

**Comment by jfversluis** [comment]
No response to our request for more info, closing this one
