### ISSUE TITLE
Path element fill binding not working

### ISSUE THREAD

**Issue by Jack-Paul** [xamarin/Xamarin.Forms#14418]
### Steps to Reproduce

1. `<Path Data="some path" Fill="{Binding Color}"/>` - Not working
2. `<Path Data="some path" Fill="#ff0000"/>`  working fine

### Expected Behavior
Need to fill the path with the color given on the Color property.

### Actual Behavior
Path element disappears.

### Basic Information

- Version with issue: 5.0.0.2012
- Last known good version: 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

Visual Studio 2019, Windows 10

**Comment by gsgou** [comment]
Also not working with v5.0.0.2083
StaticResource and DynamicResource also do not work.

**Comment by jsuarezruiz** [comment]
The type of the binding object is Color or **Brush**?. Must be a Brush to work. 

`<Path Data="some path" Fill="#ff0000"/>`

Is working because a XAML TypeConverter is doing the casting from a hex color to a SolidColorBrush.

**Comment by ngpearce** [comment]
Rather than binding to a Color, if you bind to an actual SolidColorBrush of the color you need this should work. Having the color directly in the markup works because it is converted to a SolidColorBrush for you.

```
var MyColorBrush = new SolidColorBrush(#ff0000);

<Path Data="some path" Fill="{Binding MyColorBrush}"/>
```

**Comment by gsgou** [comment]
@jsuarezruiz thanks, the issue can be closed

**Comment by cakmak-serkan** [comment]
> Rather than binding to a Color, if you bind to an actual SolidColorBrush of the color you need this should work. Having the color directly in the markup works because it is converted to a SolidColorBrush for you.
> 
> ```
> var MyColorBrush = new SolidColorBrush(#ff0000);
> 
> <Path Data="some path" Fill="{Binding MyColorBrush}"/>
> ```

its work thank you very much
