### ISSUE TITLE
xamarin forms xaml Previewer not showing

### ISSUE THREAD

**Issue by RaodeepakER** [xamarin/Xamarin.Forms#14410]
## Summary
Please provide a brief summary of your proposal. Two to three sentences is best here.

## API Changes

Include a list of all API changes, additions, subtractions as would be required by your proposal. These APIs should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some "example" code of usage of your new API.

e.g.

In order to facilitate the new Shiny Button api, a bool is added to the Button class. This is done as a bool because it is simpler to data bind and other reasons...

    var button = new Button ();
    button.MakeShiny = true; // new API

The MakeShiny API works even if the button is already visible.

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by shawyunz** [comment]
It is deprecated in new version, check this: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows

> Warning
>
>The XAML Previewer has been deprecated in Visual Studio 2019 version 16.8 and Visual Studio for Mac version 8.8, and replaced by the XAML Hot Reload feature in Visual Studio 2019 version 16.9 and Visual Studio for Mac version 8.9. Learn more about XAML Hot Reload in the documentation.

**Comment by jsuarezruiz** [comment]
As @shawyunz shared, is deprecated now. Use Hot Reload https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload and, feel free to open other issues and share anything!.
