### ISSUE TITLE
[Bug] HotReload triggering multiple times when using MergedDictionaries

### ISSUE THREAD

**Issue by jpozo20** [xamarin/Xamarin.Forms#14412]
### Description
If your have a ContengPage with a `ResourceDictionary.MergedDictionaries`, the Hot Reload is triggering multiple times when you save. Sometimes it only triggers once if you just launched the app, but the issue becomes apparent after the second or third reload. Other times it just keeps reloading and reloading continually. 
Looks to be a problem with the tooling since it happens on JetBrains Rider too. 

For now I've only found the issue on Android, but tonight I'll be doing more test on iOS
I'm using Full page reload since `Changes only` wasn't working for me. 

EDIT:
After some more testing, it seems the issue happens when the ContentPage is inside a `TabBar` in a `Shell` so it may be related to issue #9309.
In a normal ContentPage though, it triggers a reload for each time you save. So if you make 5 changes, views will reload 5 times as seen in the issue #11899.

### Steps to Reproduce

1. Add a Shell with a TabBar and  a ContentPage
2. Add a separate `ResourceDictionary` xaml with DataTemplates inside
3. Add the the resource dictionary to the `ResourceDictionary.MergedDictionaries` of the ContentPage
4. Modify a control attribute or resource in one of the DataTemplate of the resource dictionary (to test quickly, try changing the `BackgroundColor` in the Resources/DataTemplates.xaml

### Expected Behavior
The Hot Reload should only trigger views reload once after a save

### Actual Behavior
The Hot Reload is triggering multiple times when you save

### Basic Information

- Version with issue: Xamarin.Forms v5.0.2012
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  I have only tested on Android
  - Android: API 28
- Android Support Library / AndroidX Version: Latest
- NuGet Packages:
  -Xamarin.CommunityToolkit v1.6.1
  -Xamarin.Essentials v1.1.0
  -Microsoft.Extensions.DependencyInjection v5.0.1

### Environment

1.Visual Studio for Mac: 
<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.5 (build 16)
Installation UUID: 8895ac96-954d-4cb0-9656-213f64d35bcb
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/6.0.100-preview.3.21202.5/Sdks
SDK Versions:
	6.0.100-preview.3.21202.5
	5.0.301
	5.0.203
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.410
	3.1.409
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	6.0.0-preview.3.21201.4
	5.0.7
	5.0.6
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.410

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/jefry.pozo/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.5
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jefry.pozo/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:34 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-06-01 18:26:52 UTC

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810050016
Git revision: d6bd382154950cedf91ffdf19704a7c61888a3b4
Build date: 2021-07-02 06:38:37-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:47 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64


```

</details>
### Build Logs

N/A

### Reproduction Link

[XamarinSamples-MergedDictionaries.zip](https://github.com/xamarin/Xamarin.Forms/files/6797810/XamarinSamples-MergedDictionaries.zip)

### Workaround

The workaround is to keep all resources in the same file or the App.xaml
But this is not feasible when your views start to get complex or you want to reuse styles and resources.

> VS bug [#1393005](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1393005)

**Comment by drasticactions** [comment]
This is a complex issue. It's a bit of both between the Xamarin.Forms Hot Reload Stack and Xamarin.Forms itself when dealing with "LoadXaml" and the additional parameters needed to poke for updating Resources via "Full Page".

In terms of fixing anything with "Full Page," they most likely will not happen. "Changes Only" is the main way for updates from Xamarin.Forms and MAUI going forward. If you're having issues with that, you can file feedback through Visual Studio or to the MAUI Repo.
