### ISSUE TITLE
Please add xamarin previewer in visual studio.

### ISSUE THREAD

**Issue by n4nouman86** [xamarin/Xamarin.Forms#14427]

**Comment by jsuarezruiz** [comment]
@n4nouman86 Could you share more details?, do you mean https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos? The Previewer is deprecated, the option to go is Hot Reload.

**Comment by jfversluis** [comment]
As pointed out by Javier, the previewer has been deprecated some time ago already so it's unlikely to come back. Definitely for Xamarin.Forms. Who knows what might happen for .NET MAUI, but nothing like this is planned at the moment. Hot Reload is the way to go.

Thanks!
