### ISSUE TITLE
[Bug]  Xamarin.Forms 5.0.0.2083 Fails Upgrading

### ISSUE THREAD

**Issue by Orgbrat** [xamarin/Xamarin.Forms#14425]
Xamarin.Forms 5.0.0.2083 fails to update Android project from 5.0.0.2012

### Steps to Reproduce

1.  Start Manage Nuget Packages
2.  Select Xamarin.Forms 5.0.0.2083
3.  Update

### Expected Behavior
Xamarin.Forms should just update

### Actual Behavior
Receive the following errors
Error	NU1107	Version conflict detected for Xamarin.AndroidX.Core. Install/reference Xamarin.AndroidX.Core 1.5.0 directly to project MyApp.Android to resolve this issue. 
 MyApp.Android -> Xamarin.AndroidX.AppCompat 1.3.0 -> Xamarin.AndroidX.Core (>= 1.5.0) 
 My.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Core (>= 1.3.2.3 && < 1.4.0).

rror		Package restore failed. Rolling back package changes for 'MyApp.Android'.

### Basic Information

- Version with issue:
- Last known good version: 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10.0 
  - UWP: 19041
- Android Support Library / AndroidX Version: 1.5.0
- NuGet Packages:
- Affected Devices:

### Environment
Windows

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by shawyunz** [comment]
Another version conflict:
```
NU1107	Version conflict detected for Xamarin.AndroidX.Lifecycle.LiveData. Install/reference Xamarin.AndroidX.Lifecycle.LiveData 2.3.1 directly to project App.Android to resolve this issue. 
 App.Android -> Xamarin.AndroidX.Work.Runtime 2.5.0.2 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.3.1) 
 App.Android -> Xamarin.Forms 5.0.0.2083 -> Xamarin.AndroidX.Lifecycle.LiveData (>= 2.2.0.4 && < 2.3.0).	App.Android	
```

**Comment by AndreasReitberger** [comment]
Please see here: https://github.com/xamarin/Xamarin.Forms/issues/14417
I already have opened a bug report for that.

**Comment by Orgbrat** [comment]
I know @AndreasReitberger  states he has opened #14417 bug for this issue but this issue will not allow me to update to Xamarin.Forms 5.0.0.2083. Does anyone have any idea when this will be fixed? Please...

**Comment by Orgbrat** [comment]
Allan Ritchie's [comment ](https://github.com/xamarin/Xamarin.Forms/issues/14417#issuecomment-881731212) on issue #14417 seems to have worked for this issue.  Although I believe you should not have to manually modify the project file to get something to update.

**Comment by AndreasReitberger** [comment]
> Allan Ritchie's [comment ](https://github.com/xamarin/Xamarin.Forms/issues/14417#issuecomment-881731212) on issue #14417 seems to have worked for this issue. Although I believe you should not have to manually modify the project file to get something to update.

Yes, it actually should just work. 
It's really frustrating to see what happens to Xamarin.Forms.

They release SR4 with still 25 Issues open (which should have been fixed for this release). Then, for more than two weeks now, silence. No respone, nothing...

**Comment by Orgbrat** [comment]
Closed with objections
