### ISSUE TITLE
[Bug] [Regression] iOS Frame.Background not working

### ISSUE THREAD

**Issue by albilaga** [xamarin/Xamarin.Forms#14426]
### Description
When setting Frame.Background, the background will set to white. But with `BackgroundColor` it is working as expected. This is only happened on iOS

### Steps to Reproduce

1. Create sample page like this
```
ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App1"
             BackgroundColor="Red"
             x:Class="App1.MainPage">

    <StackLayout VerticalOptions="Center" HorizontalOptions="Center">
        <Frame HasShadow="False">
            <Frame.Background>
                <SolidColorBrush Color="Transparent" />
            </Frame.Background>
            <Label Text="Hello" />
        </Frame>
    </StackLayout>

</ContentPage>
```
2. Run the app.

### Expected Behavior
Frame Background should be Transparent.
### Actual Behavior
Frame.Background is White
### Basic Information

- Version with issue:
- Last known good version: 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  14.5
- Issue with version: 5.0.0.2083
- Affected Devices: iOS only

### Screenshots
![image](https://user-images.githubusercontent.com/2399099/125896800-eccabff0-a84a-4e2f-91d2-f128635b2cf3.png)

### Workaround

Use BackgroundColor Transparent instead of Background with SolidBrushColor Transparent

**Comment by thisisthekap** [comment]
@albilaga Thank you for providing the workaround!

Worth to mention: The property `BackgroundColor` is deprecated. So it might be worth it to create a new SR (maybe even just containing that fix) as soon as possible.

**Comment by albilaga** [comment]
Possibly related with this PR https://github.com/xamarin/Xamarin.Forms/pull/13401 ?

**Comment by DevEddy** [comment]
Same problem here. Can't go with the workaround cause i am using a gradient color with alpha. With this SR4 is currently unusable for us.

**Comment by thisisthekap** [comment]
@davidortinau As asked for in #14205: This is a regression.

**Comment by jfversluis** [comment]
@albilaga @thisisthekap a PR is open for this now, would you be able to grab the NuGet from that [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue?

**Comment by DevEddy** [comment]
Hey @jfversluis, I can confirm that version 5.0.0.7409 fixes the issue, good job!

**Comment by jfversluis** [comment]
Perfect @DevEddy thanks! Did you by any chance also play around with it some more besides this issue? Just to make sure this doesn't cause any other unintended things :)

**Comment by DevEddy** [comment]
Hi @jfversluis, yeah, everything we use seems to work correctly. I didn't find any issues on iOS.

**Comment by jfversluis** [comment]
Great! I did some testing and seemed good too. Merged, should be part of the next service release!

**Comment by albilaga** [comment]
Yeah this is working @jfversluis . Thank you
