### ISSUE TITLE
Assertion failure crash

### ISSUE THREAD

**Issue by shayo** [xamarin/Xamarin.Forms#1442]
Dear Xamarin Support,

We are experiencing random crashes (not very consistent, but sometimes during clicking on the navigation "Back" button). 

### Description
System crash.
HockeyApp does not recognizes this crash and does not send a bug report.

It completely shuts down the app. Even when I run in Debug mode. No stack is available.

### Steps to Reproduce
Cannot get a consistent way to reproduce this, but it just happened more than 20 times today :(

### Expected Behavior
Not crashing?
### Actual Behavior

The  "Application Window" shows the following cryptic message:

017-12-20 11:50:08.509 ClimbTag.iOS[1139:940216] *** Assertion failure in void UIViewReportBrokenSuperviewChain(UIView *__strong, UIView *__strong, BOOL)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.9.1/UIView.m:189

### Basic Information

- Version with issue:
- Last known good version:
- IDE: 7.3 build 799

- Platform Target Frameworks: 
  - iOS:  10.3.3

- Nuget Packages:
NuGet Version: 4.3.1.4445
Xamarin.Forms 2.4.0.38779
Version: 11.6.1.2 (Visual Studio Community)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

- Affected Devices:
iPhone 5c

**Comment by kingces95** [comment]
@shayo Please reopen after attaching a reproduction. Please work to make your reproduction as small as possible. Thanks!
