### ISSUE TITLE
[Bug] LinearGradientBrush Background with alpha channel color don't works 

### ISSUE THREAD

**Issue by Fenki404** [xamarin/Xamarin.Forms#14433]
### Description
XF 5.0.0.2083 
Frame with LinearGradientBrush Background with alpha channel color is white instead of transparent.

     <Frame Grid.Row="1" 
               x:Name="OverlayFrame"
               InputTransparent="True"
               VerticalOptions="End"
               HeightRequest="57"
               Padding="0"
               CornerRadius="0"
               HasShadow="False"
               Opacity="0.8"
               >

            <Frame.Background>
                <LinearGradientBrush StartPoint="0.5, 0" EndPoint="0.5, 1">
                    <GradientStop Color="#00000000"
                                  Offset="0" />
                    <GradientStop Color="#000000"
                                  Offset="1" />
                </LinearGradientBrush>
            </Frame.Background>

        </Frame>

### Steps to Reproduce

1. new Shell Project 
2. add frame with LinearGradientBrush Background with alpha color
3. run

### Expected Behavior
render transparent background 

### Actual Behavior
render white background 

### Basic Information

- Version with issue: XF 5.0.0.2083 
- Last known good version: XF 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  14.5
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:  IOS Simulator, IPhone

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/46244359/126154122-1d2dc515-c2c6-42d7-8b66-842d9a9bd94f.png)
![image](https://user-images.githubusercontent.com/46244359/126154300-df3bc69e-b87a-43a3-aa45-1813a9801851.png)

### Workaround

downgrade to V5.0.0.2012

**Comment by thisisthekap** [comment]
We are able to confirm this issue. Specifically, that there is no other workaround than downgrading.

This is to my opinion a pretty severe regression, which makes the SR4 unusable to us.

**Comment by Huaba93** [comment]
maybe related to https://github.com/xamarin/Xamarin.Forms/issues/14426

**Comment by DevEddy** [comment]
Same here, any new infos?

**Comment by radovanov** [comment]
bump bump buuump....

**Comment by thisisthekap** [comment]
This one is a regression in the lastest available service release. I understand that MAUI needs love too. But existing frameworks that are considered to be production ready should get some attention too...

**Comment by jsuarezruiz** [comment]
@Fenki404 Could you try the same with the NuGet package from https://github.com/xamarin/Xamarin.Forms/pull/14576?
