### ISSUE TITLE
[Bug] Switch is slightly cut off on macOS

### ISSUE THREAD

**Issue by CMarcher** [xamarin/Xamarin.Forms#14445]
### Description
The recently implemented Switch for macOS appears to be slightly cut off at the top. I know this seems pedantic, but I'm sure we'd all rather have native controls looking as good as they function.

### Steps to Reproduce

1. Add a switch control pretty much anywhere you want.
2. Look. It is easier to see if the Switch is toggled on.

### Expected Behavior
Switch looks beautiful and smooth all around.

### Actual Behavior
Switch does not look beautiful and smooth all around. It is cut off at the top.

### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version: N/A (Switch was implemented for macOS in 5.0.0.2083)
- Affected Devices: MacBook Pro 16 inch

### Screenshots

_May need to zoom_

<img width="49" alt="Screen Shot 2021-07-22 at 9 38 51 PM" src="https://user-images.githubusercontent.com/25070396/126619215-fe90fdbd-4b71-4157-9bfe-19f59a27ffe3.png">

### Workaround

You can play around with the Switch embedded in a Frame, finding the optimum margin and padding settings. That seems to minimise or get rid of the cut off issue.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
