### ISSUE TITLE
Exception handling in Visual Studio in Xamarin Forms Android project

### ISSUE THREAD

**Issue by rammfire** [xamarin/Xamarin.Forms#14442]
Hi, I have a problem in the implementation of my application.
Now, in the constructor of my application, 20 records are being created that simulate the number of training days. I want to implement a functionality that, when clicked, will determine which element of the collection was selected and, based on the displayed date, will load another data model, which, based on the date, will load information about the exercises that the user did on that day.
[TrainingViewModel.cs](https://github.com/rammfire/SportApp/blob/alpha/SportApp/SportApp/SportApp/ViewModels/TrainingViewModel.cs)
```
public TrainingViewModel()
        {
                PowerTrainings = new ObservableCollection<PowerTraining>();
                for (int i = 0; i < 20; i++)
                {
                    PowerTrainings.Add(new PowerTraining() { DayOfTraining = dateTime });
                }
        }
```
Xaml code for displaying the collection:
[CalendarOfTraining.xaml](https://github.com/rammfire/SportApp/blob/alpha/SportApp/SportApp/SportApp/Views/CalendarOfTraining.xaml)

```
<ContentPage.BindingContext>
        <local:TrainingViewModel/>
  </ContentPage.BindingContext>
```

    <ContentPage.Resources>
        <DataTemplate x:Key="ColorItemTemplate">
            <Frame Margin="5"
              HeightRequest="120"
              BackgroundColor="Azure"
              WidthRequest="105">
                <Label Text="{Binding DayOfTraining}" 
                   HorizontalOptions="Center"
                   VerticalOptions="Center" />

                <Frame.GestureRecognizers >
                    <TapGestureRecognizer Command="{Binding BindingContext.TypeListSelectedCommand, Source={x:Reference flexLayout}}" CommandParameter="{Binding}"></TapGestureRecognizer>
                </Frame.GestureRecognizers>
            </Frame>
        </DataTemplate>
    </ContentPage.Resources>
    
    <StackLayout Margin="10">
        <Label Text="CollectionView"
               FontSize="30"
               FontAttributes="Bold"
               HorizontalOptions="Center" />
        <Label Text="{Binding PowerTrainings.Count, StringFormat='Count: {0}'}" />
        <ScrollView>
            <FlexLayout Direction="Row" 
                            Wrap="Wrap"
                            AlignItems="Center"
                            AlignContent="Center"
                            BindableLayout.ItemsSource="{Binding PowerTrainings}"
                            BindableLayout.ItemTemplate="{StaticResource ColorItemTemplate}">
            </FlexLayout>
        </ScrollView>
    </StackLayout>`

While running debugging in visual studio, when I click on the button that should call the view, execution stops with an exception:
`System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'`

When I comment on a line with a binding, the model loads well, but nothing happens.
`<TapGestureRecognizer Command="{Binding BindingContext.TypeListSelectedCommand, Source={x:Reference flexLayout}}" CommandParameter="{Binding}"></TapGestureRecognizer>`

**Comment by FoggyFinder** [comment]
Well this is not the best place for asking XF-related Qs.

Anyway, can you provide MCVE for the issue or at least attach test project or give a reference to the repo?

**Comment by rammfire** [comment]
> Anyway, can you provide MCVE for the issue or at least attach test project or give a reference to the repo?

https://github.com/rammfire/SportApp/tree/alpha/SportApp/SportApp/SportApp

**Comment by FoggyFinder** [comment]
> > Anyway, can you provide MCVE for the issue or at least attach test project or give a reference to the repo?
> 
> https://github.com/rammfire/SportApp/tree/alpha/SportApp/SportApp/SportApp

OK, that's something.

You got a wrong binding here

```xml
Source={x:Reference flexLayout}}"
```

you should either assign a name to the element like

```xml
<FlexLayout x:Name="flexLayout" ... />
```

and then use reference or replace it with relative bindings. See [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings) for details.

As a side note I'd suggest you considering asking for a code-review.

**Comment by rammfire** [comment]
> ```
> Source={x:Reference flexLayout}}"
> ```
> 
> you should either assign a name to the element like
> 
> ```
> <FlexLayout x:Name="flexLayout" ... />
> ```
> 
> and then use reference or replace it with relative bindings. See [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings) for details.

Thank you for your help, you helped me.
