### ISSUE TITLE
[Bug] [MacOS] Entry lose focus when the parent has gestures

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#14454]
### Description
The Entry/Editor control loses focus when handling gestures for parent. We have custom templated control where the 
each template has ContentView as parent. We have added gestures for the ContentView to handle selection. When loading entry/editor inside the template, the entry loses focus and the ContentView handles the touch.

**Note**: We have same implementation for iOS which works fine. Issue only occurs on MacOS platform.

Please suggest any workaround to handle this scenario if available.

### Steps to Reproduce

1. Run the sample in MacOS
2. Tap the entry
3. Note: The entry loses focus after a second

### Expected Behavior
The entry does not lose the focus and the touch should handled by Entry not its parent.

### Actual Behavior
The touch is handled by parent element not the Entry.

### Basic Information
As mentioned above, we have handled touch for ContentView to perform selection and other customization as below,

```
        private void OnLongPressed()
        {
            System.Diagnostics.Debug.WriteLine("CustomContentViewRenderer OnLongPressed");

 

            if (Window != null)
            {
                Window.MakeFirstResponder(this);
            }
        }
```

This longpressed call back gets called when tapping an entry. And the above makes the entry to lose focus.

But, the above should be called when non-interactable element loaded in the template. 

- Version with issue: 5.0
- Last known good version:
- Platform Target Frameworks: MacOS
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Screenshots
[Replication Video](https://www.syncfusion.com/downloads/support/directtrac/general/ze/EntryFocusIssueVideo-1022497227)

### Reproduction Link
[Replication sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/EntryFocusIssue-1315668881)

### Workaround
No.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
