### ISSUE TITLE
[Enhancement] Images has a DownloadToViewSize property?

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#14452]
## Summary
I think the Image should have a `DownloadToViewSize` Property So it will be faster while show the image.

## API Changes

I know the `Image` has a `CacheEnabled` Property but there is no a `DownloadToViewSize` Property while the `ImageSource` is a uri image.

If my image is 1200 * 800 but the view of the Image which will show the image is only 120 * 80 . it will download the 1200*800 image and show it right? but it will stocked while there is many image controls.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
