### ISSUE TITLE
[Bug] Akka with Xamarin Error "Configuration system failed initialize"

### ISSUE THREAD

**Issue by Zabato7** [xamarin/Xamarin.Forms#14456]
I am trying to create an actor, through the actor system of the akka library, but I receive the error “Configuration system failed initialize” just when trying to create the actor system.

         private static readonly ActorSystem _system;
         public static readonly IActorRef _coordinator;

         static CrawlingSystem ()
         {
             _system = ActorSystem.Create `("crawling-system");`
             _coordinator = _system.ActorOf (Props.Create <BackupActor> (), "backupactor");
         }
The static CreawlingSystem class is called directly by MainPage.Xaml.cs
I am using visual Studio 2019, an empty Xamarin.Forms project, akka 1.4.21, Xamarin.Forms 5.0.0.2012.
Also i tried with versions: akka 1.3.9, Xamarin.Forms 3.3.0912540, but the error persists.

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?

**Comment by jfversluis** [comment]
No response to our request for more info so assuming this is not affecting you anymore, thanks!
