### ISSUE TITLE
[Enhancement] Make a ShellItem attribute of FlyoutItemIsVisible tobe bindable

### ISSUE THREAD

**Issue by jinbatsu** [xamarin/Xamarin.Forms#14458]
## Summary
It is great if web can make ShellItem attribute of FlyoutItemIsVisible is bindable.
So that we can hide/show from View Models.

## Current Case
I can not set bindable attribute of FlyoutItemIsVisible to Shellitem.
And I do not know how to manipulate or accessing **x:name** (if I set to shellitem) from ViewModel.
```
    <ShellItem Route="login" Title="Login" FlyoutItemIsVisible="True">
        <ShellContent ContentTemplate="{DataTemplate myroot:LoginPage}"/>
    </ShellItem>
    <ShellItem Route="register" Title="Register" FlyoutItemIsVisible="True">
        <ShellContent ContentTemplate="{DataTemplate myroot:RegisterPage}"/>
    </ShellItem>

    <ShellItem Route="main" Title="Home" FlyoutItemIsVisible="False">
        <ShellContent ContentTemplate="{DataTemplate myroot:HomePage}"/>
    </ShellItem>
    <ShellItem Route="logout" Title="Logout" FlyoutItemIsVisible="False">
        <ShellContent ContentTemplate="{DataTemplate myroot:LogoutPage}"/>
    </ShellItem>
```

## Intended Use Case
I want to achive like this:
```
    <ShellItem Route="login" Title="Login" FlyoutItemIsVisible="{Binding IsGuest}">
        <ShellContent ContentTemplate="{DataTemplate myroot:LoginPage}"/>
    </ShellItem>
    <ShellItem Route="register" Title="Register" FlyoutItemIsVisible="{Binding IsGuest}">
        <ShellContent ContentTemplate="{DataTemplate myroot:RegisterPage}"/>
    </ShellItem>

    <ShellItem Route="main" Title="Home" FlyoutItemIsVisible="{Binding IsMember}">
        <ShellContent ContentTemplate="{DataTemplate myroot:HomePage}"/>
    </ShellItem>
    <ShellItem Route="logout" Title="Logout" FlyoutItemIsVisible="{Binding IsMember}">
        <ShellContent ContentTemplate="{DataTemplate myroot:LogoutPage}"/>
    </ShellItem>
```

**Comment by AbstractionsAs** [comment]
I've just solved this after struggling myself - bind to "IsVisible" on the "ShellContent" instead

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
