### ISSUE TITLE
Binding iOS Library

### ISSUE THREAD

**Issue by sandsad** [xamarin/Xamarin.Forms#14468]
**Binding iOS Library**
When i binding iOS library, the _Objective-C_ code is an array pointer to _CLLocationCoordinate2D_.  The C# code generated by sharpie is  `(CLLocationCoordinate2D* coords)` . 
If i remove * it will cause me only pass a CLLocationCoordinate2D object when i use it.
How can I change the C# code so that I can pass the CLLocationCoordinate2D array parameter when usingt?

**Comment by sandsad** [comment]
The C# code generated by sharpie that I remove the *

![image](https://user-images.githubusercontent.com/37395235/127295899-4bbba280-4250-4d17-9ab2-11bcfef21b79.png)

**Comment by sandsad** [comment]
[MAMapKit.zip](https://github.com/xamarin/Xamarin.Forms/files/6891788/MAMapKit.zip)

**Comment by sandsad** [comment]
Project in [](https://github.com/sandsad/Xamarin/tree/master)

**Comment by sandsad** [comment]
Project in  https://github.com/sandsad/Xamarin/tree/master

**Comment by bnoffer** [comment]
Have a look at this: https://stackoverflow.com/questions/23665042/how-to-bind-xamarin-ios-obj-c-library-with-marshalling
The solution described in the resolving post should fix your issue.

**Comment by sandsad** [comment]
> 看看这个：[https](https://stackoverflow.com/questions/23665042/how-to-bind-xamarin-ios-obj-c-library-with-marshalling) : [//stackoverflow.com/questions/23665042/how-to-bind-xamarin-ios-obj-c-library-with-marshalling](https://stackoverflow.com/questions/23665042/how-to-bind-xamarin-ios-obj-c-library-with-marshalling)
> 解决帖子中描述的解决方案应该可以解决您的问题。

**Comment by sandsad** [comment]
> Have a look at this: https://stackoverflow.com/questions/23665042/how-to-bind-xamarin-ios-obj-c-library-with-marshalling
> The solution described in the resolving post should fix your issue.

I have soluted it,thanks.
