### ISSUE TITLE
VS 2017 + Xamarin: Imported project was not found

### ISSUE THREAD

**Issue by Hudhud** [xamarin/Xamarin.Forms#1447]
### Description
When I try to create a Xamarin.Fomrs project in Visual Studio 2017, it keeps giving me the following error:
![image](https://user-images.githubusercontent.com/9434115/34260193-527324c2-e665-11e7-9fb3-8490cff989cc.png)

I have tried to re-install VS, but that didn't work. When I open the project in File Explorer, everything is there. However, when I open the solution in Solution Explorer in VS, it says 0 projects, why? How can I fix this?

The files .projitems and .shproj do exist, when I open the path in File Explorer, so I don't understand the error

### Steps to Reproduce

1. Install Visual Studio 2017 Enterprise 
2. Install component for Xamarin (Mobile Development with .NET)
3. Create a new project
4. Select Cross-Platform
5. Select Cross Platform App (Xamarin.Forms)
6. Select Blank App, Android/iOS, Xamarin.Forms & Shared Project

### Expected Behavior
The project will be created without issues

### Actual Behavior
The project is created with issues that I can't solve

### Basic Information

- Version with issue: Have tried different .NET Framework (4.5.2, 4.6.1 & 4.7.1)
- Last known good version: First time using Xamarin
- IDE: Visual Studio 2017 Enterprise. Have also tried with Visual Studio 2015 Enterprise
- Platform Target Frameworks: 
- iOS:  10
- Android: Android SDK 25
- Nuget Packages: 4.5.0.4685

**Comment by rmarinho** [comment]
Hi, with this information is hard to check what's the issue, it doesn't seem directly related with Xamarin.Forms nupkg. We need a sample so we can try reproduce.

Thanks

**Comment by Delie** [comment]
I had exactly the same issue as @Hudhud in VS2017 15.5.2.  I was able to get around it by making sure the new project name had no spaces in it

**Comment by Hudhud** [comment]
I have fixed it. The problem was, as @Delie mentions, that the project name had spaces. I replaced the spaces with "_" and shortened the path, which also was needed.
