### ISSUE TITLE
All-Modal Navigation in Xamarin.Forms.Shell

### ISSUE THREAD

**Issue by PatrickRyder** [xamarin/Xamarin.Forms#14475]
## Summary
I would like to be able to use the **Xamarin.Forms.Shell** with nothing but modal screens, as my application is wizard-style and it does not make sense for users to be able to jump between screens. 

## API Changes
I believe the main API change would be to somehow allow a single **ContentPage** to be set as the 'root' of a **Shell**.

This root page would itself need to be modal, which could be achieved in the normal way - by including **Shell.SetPresentationMode( this, PresentationMode.Modal )** in the constructor.

All other pages could then be declared as normal using the **RegisterRoute()** function and also declared modal in their constructor.

## Intended Use Case
My use case is as follows:

- I want to use **Xamarin.Forms.Shell**, mainly to take advantage of the new navigation events, which my application logic requires.
- My application is entirely wizard-style and so it is preferable for every single screen to be modal and for my own code to manage navigation.
- As a bonus, this should fix my other requirement, which is to have a gradient filling the entire background, because modal screens don't have the separate **Shell** sections displayed at the top and bottom.

**Comment by davidortinau** [comment]
You can do what you describe today. Here is a single content page in Shell. From that page you can modally navigate to all your other pages that you define routes for.

Modal presentation mode: https://devblogs.microsoft.com/xamarin/xamarin-forms-shell-quick-tip-modal-navigation/#presentation-mode
Routing: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#register-detail-page-routes

![image](https://user-images.githubusercontent.com/41873/133462783-f6fd29ce-b383-4971-ab76-b755e61b8ff4.png)
