### ISSUE TITLE
[Bug] UWP Renderers in App.xaml

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#14478]
### Description
i think some of the renderers not working in app.xaml(inside UWP project) like the ShellRenderer.
or i'm doing this in a wrong way?

### Steps to Reproduce

1. create a shellflyout app
2. open uwp project -> app.xaml
3. paste this peace of code

`<Application
    x:Class="flyouttest.UWP.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:uwp="using:Xamarin.Forms.Platform.UWP">
    <Application.Resources>
        <ResourceDictionary>
            <Style TargetType="uwp:ShellRenderer">
                <Setter Property="PaneDisplayMode" Value="Auto" />
                <Setter Property="IsSettingsVisible" Value="True" />
            </Style>
            <Style TargetType="NavigationView">
                <Setter Property="PaneDisplayMode" Value="Auto" />
                <Setter Property="IsSettingsVisible" Value="True" />
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
`

### Expected Behavior
i wanna to achive this
![image](https://docs.microsoft.com/en-us/windows/apps/design/controls/images/displaymode-auto.png)

### Actual Behavior
but i'm stuck with this
![image](https://docs.microsoft.com/en-us/windows/apps/design/controls/images/displaymode-leftminimal.png)

### Basic Information

- Version with issue: Xamarin.Froms 5.0.0 Service Release 4
- UWP:  19041
- Affected Devices: Windows 11 PC

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks!

**Comment by jfversluis** [comment]
No response to our request for more info. I trust you have resolved this in the meantime. Thanks!
