### ISSUE TITLE
[Bug] StackLayout margin is not correctly rendered in iOS

### ISSUE THREAD

**Issue by Qythyx** [xamarin/Xamarin.Forms#14470]
### Description

StackLayout margin is not correctly rendered in iOS.

### Steps to Reproduce

1. Create a `ContentPage` with the root control as a `StackLayout` that has a margin and a background color so you can see it
2. Run the app in iOS (simulator also will show the problem)
3. Notice the top and bottom margin of the `StackLayout` is not rendered correctly

Fortunately, there is an easy workaround for this issue, just wrap the `StackLayout` in an `AbsoluteLayout`.

So, the following code shows the problem:
```xaml
	<StackLayout
		Style="{DynamicResource StackVerticalMargin}">
...
```

And the following works around the problem:
```xaml
	<AbsoluteLayout>
		<StackLayout
			AbsoluteLayout.LayoutBounds="0,0,1,1"
			AbsoluteLayout.LayoutFlags="All"
			Style="{DynamicResource StackVerticalMargin}">
...
```

### Expected Behavior

The margin should render correctly.

### Actual Behavior

The margin is not rendered correctly.

### Basic Information

- Version with issue: XF 5.0.0.2083
- Last known good version: I'm not sure, but I believe the previous XF version was ok
- Platform Target Frameworks:
  - iOS:  all

### Environment

n/a

### Screenshots

Problem
<img src="https://user-images.githubusercontent.com/487802/127313723-42c37702-4216-4650-a474-bd936c5a0c17.png" width="300">

Workaround
<img src="https://user-images.githubusercontent.com/487802/127313755-0a33c495-86cd-4270-9bc7-d048f62329e3.png" width="300">

### Workaround

See above.

**Comment by jsuarezruiz** [comment]
Could you share the `StackVerticalMargin` definition?
Happens on iOS or also in other platforms?

**Comment by jfversluis** [comment]
No response to our request for more info, closing this one
