### ISSUE TITLE
[Bug] Error loading partial Info.plist template file when attempting to run iOS project in emulator.

### ISSUE THREAD

**Issue by MarkLFT** [xamarin/Xamarin.Forms#14480]
### Description

I am using VS2019 on a PC, with a Mac linked to it for building iOS apps. When I build the app I receive the message:

Error loading partial Info.plist template file 'obj/iPhoneSimulator/Debug/mbt/Info.plist': Could not find a part of the path "/Users/myname/Library/Caches/Xamarin/mtbs/builds/AppName.iOS/d86221a1e115ab3d2d619d810102d13413d6ff1743aadea6dda89b4af30fbe19/obj/iPhoneSimulator/Debug/mbt/Info.plist".

The only way I have found to prevent it is to go on the Mac, find the folder mentioned, and delete it. The I can build again for a while until it happens again.

### Steps to Reproduce

1. Create Xam Forms project, select iPhone Simulator build
2. Mac is on same LAN as PC and connected in VS.  
3. Try to build and run the simulator, receive error.

### Expected Behavior

Should be able to run the simulator as easy as the android one.

### Actual Behavior

Unable to test app on simulator

### Basic Information

- Version with issue: Latest, updated VS on both systems, and XCode on MAC.
- Last known good version: Unknown
- Platform Target Frameworks: 
  - iOS:   10
  - Android:  N/A
  - UWP:   N/A
- Android Support Library / AndroidX Version:  N/A
- NuGet Packages: 
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by carbon-paulc** [comment]
I'm experiencing this same issue.  I've heard other people removing the mac folder and rebuilding which fixes their issuse, which doesn't work for me.

Looking in the directory on the mac, it has a few resources and directories but not the APPNAME.iOS.App folder.

My detailed debug output around the error is below:

```
Target "_CompileAppManifest" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets" from project "{path to csproj}" (target "_CreateAppBundle" depends on it):
3>Building target "_CompileAppManifest" completely.
3>Output file "bin\iPhoneSimulator\Debug\APPNAME.iOS.app\Info.plist" does not exist.
3>Using "CompileAppManifest" task from assembly "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\..\iOS\Xamarin.iOS.Tasks.dll".
3>Task "CompileAppManifest"
3>  CompileAppManifest: 2021-08-11T10:50:36.8795591+01:00 - Started
3>  CompileAppManifest: 2021-08-11T10:50:36.8795591+01:00 - Initializing
3>  [xma]: Trying to get a Build Connection for Session '7d8514f9c34759c7f37616f2d70c7b61cbf63c6de70aa83105f84d31c20be54b': Xamarin.Messaging.Build.Client.BuildConnection.7d8514f9c34759c7f37616f2d70c7b61cbf63c6de70aa83105f84d31c20be54b, Lifetime: AppDomain
3>  CompileAppManifest: 2021-08-11T10:50:36.8795591+01:00 - Initialized
3>  CompileAppManifest: 2021-08-11T10:50:36.8795591+01:00 - There's no available inputs to copy to the Mac
3>  CompileAppManifest: 2021-08-11T10:50:36.8795591+01:00 - Serializing intputs
3>  CompileAppManifest: 2021-08-11T10:50:36.8895601+01:00 - Executing
3>  [xma]: Starting remote task execution for 'APPNAME.iOS': Xamarin.iOS.Tasks.CompileAppManifest
3>  [xma]: Sending Request Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic xvs/build/execute-task/APPNAME.iOS/7d8514f002fCompileAppManifest
3>  [xma]: Received Response of Xamarin.Messaging.Build.Contracts.ExecuteTaskMessage to topic build7d8514f9c34759c7f37616f2d70c7b61cbf63c6de70aa83105f84d31c20be54b1124pchar/+/xvs/build/execute-task/APPNAME.iOS/7d8514f002fCompileAppManifest
3>  CompileAppManifest: 2021-08-11T10:50:36.9125598+01:00 - Logging messages
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(235,3): error : Error loading partial Info.plist template file 'obj/iPhoneSimulator/Debug/mbt/Info.plist': Could not find a part of the path "/Users/pcharlton/Library/Caches/Xamarin/mtbs/builds/APPNAME.iOS/7d8514f9c34759c7f37616f2d70c7b61cbf63c6de70aa83105f84d31c20be54b/obj/iPhoneSimulator/Debug/mbt/Info.plist".
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\iOS\Xamarin.Shared.targets(235,3): error :         
3>  CompileAppManifest: 2021-08-11T10:50:36.9125598+01:00 - Finished
3>Done executing task "CompileAppManifest" -- FAILED.
3>Done building target "_CompileAppManifest" in project "APPNAME.iOS.csproj" -- FAILED.
3>
3>Build FAILED.
```

**Comment by varyamereon** [comment]
I am also experiencing this. For what it's worth I'm actually using the latest VS2022 build (Preview 3) and Xcode 13.0 beta on Mac. Deleting the relevant obj folder on Mac and rebuilding does not solve the issue, I am unable to build at all.

**Comment by varyamereon** [comment]
Found what the issue was for me, it was related to the Mobile.BuildTools package from @dansiegel. There is an issue out [here](https://github.com/dansiegel/Mobile.BuildTools/issues/284). Basically I disabled everything I didn't need in the buildtools.json and am now able to build for iOS. Perhaps it's the same issue for you guys @MarkLFT and @carbon-paulc.

**Comment by carbon-paulc** [comment]
Yeah - this matches with my experience, although still trying to figure out the buildtools config to get it to work.

**Comment by jsuarezruiz** [comment]
Seems related with https://github.com/dansiegel/Mobile.BuildTools/issues/287 
I am going to close this one but, if find anything related with tooling etc feel free to reopen or open a new issue.
