### ISSUE TITLE
[Bug] App Crash with SkiaSharp package, added after updating Ios to 14.7.1

### ISSUE THREAD

**Issue by Aleksey1555** [xamarin/Xamarin.Forms#14497]
### Description
After updating Iphone SE to Ios14.7.1 - appear bug. Application Hangs and in debug mode,VS 2019 Shows this error:
Native Crash Reporting

### Steps to Reproduce

1. Create Xamarin.Forms project (with ios project)
2. Add SkiaSharp.Views.Forms 2.80.3 (nuget package) 
3. Start debugging

### Expected Behavior
Normal debugging process
### Actual Behavior
Debugger crash!!
### Basic Information

- Version with issue: Ios 14.7.1
- Last known good version: IOS 14.7

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.10.4
VisualStudio.16.Release/16.10.4+31515.178
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA723
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.10.526.50910
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.10.526.50910
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.10.526.50910
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.10.526.50910
Azure Functions and Web Jobs Tools

C# Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CMakePackage Extension   1.0
CMakePackage Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

LauncherPackage Extension   1.0
LauncherPackage Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40423.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

NVIDIA CUDA 10.2 Wizards   10.2
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight Visual Studio Edition   2019.4.0.19274
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2010 - 2019.
•Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
•Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
•Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
•NLog Copyright © 2004-2006 Jaroslaw Kowalski (jaak@jkowalski.net)
•IronPython and WPFToolkit used under Microsoft Public License (Ms-PL) and are Copyright © Microsoft Corporation
•Portions of RadControls for WPF © 2010-2011 by Telerik Corporation.  All rights reserved.
•zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 
•QtSingleApplication Copyright 2013 Digia Plc and/or its subsidiary(-ies).
•Font Awesome Copyright 2018 Fonticons, Inc.

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

NVIDIA Nsight Visual Studio Edition - CUDA support   2019.4.0.19274
NVIDIA Nsight Visual Studio Edition - CUDA support provides tools for CUDA development and debugging.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62106.24090
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21329.37+246ce641f04b67ef017655275d850bf902a8e40f
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.10.000.234 (d16-10@ecaf29b)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.10.0.115 (remotes/origin/c750fbf1bde3c720d077f51640fe197c6dac7cbe@c750fbf1b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.0.4 (d16-10/ae14caf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: b4a3858
    Java.Interop: xamarin/java.interop/d16-10@f39db25
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0


Xamarin.iOS and Xamarin.Mac SDK   14.20.0.24 (c4b89cddb)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Build Logs
2021-08-09 22:12:19.793 Xamarin.PreBuilt.iOS[1244:94964] Xamarin.iOS: Successfully received USB connection from the IDE on port 10000, fd: 6
2021-08-09 22:12:19.795 Xamarin.PreBuilt.iOS[1244:94964] Xamarin.iOS: Processing: 'start profiler: no'

2021-08-09 22:12:19.795 Xamarin.PreBuilt.iOS[1244:94936] Xamarin.iOS: Profiler not loaded (disabled)

Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/System.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Mono.Security.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS.exe [External]
Thread started:  #2
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS.Library.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/netstandard.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/System.Core.dll [External]
2021-08-09 22:12:20.147 Xamarin.PreBuilt.iOS[1244:94936] Content folder: /var/mobile/Containers/Data/Application/232E8AFD-1382-4F98-924C-8C3702E58975/Documents/XamarinSS.iOS.content

Thread started:  #3
2021-08-09 22:12:20.287 Xamarin.PreBuilt.iOS[1244:94936] Forms app path /var/mobile/Containers/Data/Application/232E8AFD-1382-4F98-924C-8C3702E58975/Documents/XamarinSS.iOS.content/XamarinSS.iOS.exe

2021-08-09 22:12:20.288 Xamarin.PreBuilt.iOS[1244:94936] Xamarin.iOS: Unable to locate assembly 'Xamarin.Forms.Platform.iOS' (culture: '')

2021-08-09 22:12:20.288 Xamarin.PreBuilt.iOS[1244:94936] Xamarin.iOS: Unable to locate assembly 'Xamarin.Forms.Platform.iOS' (culture: '')

Loaded assembly: /private/var/mobile/Containers/Data/Application/232E8AFD-1382-4F98-924C-8C3702E58975/Documents/XamarinSS.iOS.content/XamarinSS.iOS.exe
Loaded assembly: /private/var/mobile/Containers/Data/Application/232E8AFD-1382-4F98-924C-8C3702E58975/Documents/XamarinSS.iOS.content/Xamarin.Forms.Platform.iOS.dll [External]
2021-08-09 22:12:20.304 Xamarin.PreBuilt.iOS[1244:94936] Xamarin.Forms AppDelegate name: AppDelegate

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x100ab0120 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x100aa6cbc - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x100ab3a60 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug
	0x1ea2b429c - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x19e20e5ec - /usr/lib/system/libdyld.dylib : <redacted>

	0x19e1fe008 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e20e418 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e1fe948 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e20ef30 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e20e9c0 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e210928 - /usr/lib/system/libdyld.dylib : <redacted>
	0x19e201ecc - /usr/lib/system/libdyld.dylib : <redacted>
	0x100c5c970 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : do_icall
	0x100c5b010 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper
	0x100c51a8c - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

	0x100c4feb0 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke

	0x100c4d984 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main

	0x100ab6d3c - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x100b652c0 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100b6a564 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x100a9b8f4 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec

32 ba 00 94 e0 03 13 aa 23 01 03 94 20 00 20 d4  2.......#... . .
0x10a41e5f4  f4 4f be a9 
	0x100a63c34 - /private/var/containers/Bundle/Application/78B80CBD-7278-4F24-AFB2-C402008D6360/XamarinSS.iOS.app/Xamarin.PreBuilt.iOS : main
	0x19e1fccf8 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10a41e5f4):0x10a41e5e4  
fd 7b 01 a9 fd 43 00 91 b3 09 00 90  .O.
..{...C......
0x10a41e604  73 82 20 91 81 08 00 b0 21 bc 1b 91 e0 03 13 aa  s. .
....!.......
0x10a41e614  02 00 ae 52 d2 b9 00 94 60 82 01 91 3a ba 00 94  ...R....`...:...

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Dlfcn:_dlopen <0x00026>
	  at ObjCRuntime.Dlfcn:dlopen <0x00010>
	  at Xamarin.PreBuilt.iOS.Applications:LoadFrameworks <0x0009e>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00202>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================

Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
2021-08-09 22:12:24.473 Xamarin.PreBuilt.iOS[1244:94964] Xamarin.iOS: Processing: 'exit process'
2021-08-09 22:12:24.473 Xamarin.PreBuilt.iOS[1244:94964] Xamarin.iOS: The IDE requested an exit, will exit immediately.

The app has been terminated.

### Workaround

no

**Comment by Aleksey1555** [comment]
@filipnavara , thank you for the answer. This is bad situation. Does Apple solving this problem...

**Comment by ZA-David** [comment]
Hi guys experiencing the same problem is there a solution to this?
