### ISSUE TITLE
[Enhancement] Add drag started and completed events/commands to Slider

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#1450]
### Summary
Add DragStarted and DragCompleted events/commands to the Slider control.
These fire at the beginning and end of the slider drag action.

### API Changes
- Add new events: **DragStarted**, **DragCompleted**
DragStarted: Event that is raised when a drag is started.
DragCompleted: Event that is raised when a drag is completed.

- Add new commands: **DragStartedCommand**, **DragCompletedCommand**.

### Intended Use Case
_ValueChanged_ fires for both programmatic and user-initiated changes.
_DragStarted_/_DragCompleted_ fires for user-initiated changes only.

ie. You are building a custom video player and wish to handle user seeking position vs updating the slider programmatically as the video is playing.

We have already built this and it is working on UWP, iOS and Android. Code is ready to contribute.

**Comment by mattrichnz** [comment]
@rmarinho Let me know when this is approved, and I can put a PR together. Thanks!

**Comment by ChaseFlorell** [comment]
I think the events need to return the slider position (even though it _is_ accessible within the Progress property).

**Comment by tekinc** [comment]
@mattrichnz can you share your PR changes? I'm about to implement this on my own. 

Thanks

**Comment by mattrichnz** [comment]
@tekinc Which platform do you need it for? Just waiting on Xamarin team to approve so I can put up a PR for this.

**Comment by kwacks** [comment]
Any update on this item? We ran into the same exact scenario while implementing a custom media player. 
@mattrichnz  can you share your code? I'm also about to implement this.

**Comment by mattrichnz** [comment]
@kwacks @tekinc I will work on putting up a PR tomorrow.
The implementation will be available for you to see then.

**Comment by mattrichnz** [comment]
@kwacks @tekinc Refer to PR #3070.

**Comment by tstivers1990** [comment]
@velocitysystems Thank you. Saved me a bunch of time today.
