### ISSUE TITLE
[Bug] [macOS] Cannot hide the ScrollBar in Xamarin.Forms ScrollView

### ISSUE THREAD

**Issue by LakshmiNatarajan21** [xamarin/Xamarin.Forms#14503]
### Description
We need to hide the ScrollBar of the ScrollView. It works fine by setting the **HasVerticalScroller** to **false**. When overriding the **ScrollWheel** method in the custom ScrollViewRenderer, the Scrolling is not working. Without overring the ScrollWheel method, the scrollbar hides as expected and scrolling also works. But, we need the **ScrollWheel** method to identify the scroll state. 

Below is our custom renderer code,

```
[assembly: ExportRenderer(typeof(ScrollView), typeof(ExtScrollViewRenderer))]
namespace GettingStarted.MacOS
{
    public class ExtScrollViewRenderer : ScrollViewRenderer
    {
        public ExtScrollViewRenderer()
        {
            this.ElementChanged += OnElementChanged;
        }

        protected void OnElementChanged(object sender, VisualElementChangedEventArgs e)
        {
            if (e.NewElement != null)
            {
                this.HasHorizontalScroller = false;
                this.HasVerticalScroller = false;
            }
        }

        public override void ScrollWheel(NSEvent theEvent)
        {
            base.ScrollWheel(theEvent);
        }
    }
}
```

### Steps to Reproduce

1. Run the attached sample in MacOS
2. Note: Scrolling not working.

### Expected Behavior
ScrollBar should not be visible, without affecting scrolling.

### Actual Behavior
Scrolling does not working.

### Basic Information

- Version with issue: Latest

### Reproduction Link
[IssueSample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/IssueSample-1105999170)

### Workaround
No

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
