### ISSUE TITLE
Flyoutpage horizontal screen will not hide flyout?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14512]
Flyoutpage horizontal screen will not hide flyout?
 
![image](https://user-images.githubusercontent.com/26525599/129579518-926c17f6-f8e0-45e3-9385-a9145ffaaa3f.png)

![image](https://user-images.githubusercontent.com/26525599/129579378-9aac9a4a-cd66-46f8-b36d-74da5bcbe230.png)

**Comment by jsuarezruiz** [comment]
You can manage the Flyout behavior using the `FlyoutLayoutBehavior` property.

**Comment by jfversluis** [comment]
We've indicated how to influence this behavior. From the lack of response I'm trusting that this has been resolved by now!
