### ISSUE TITLE
[Bug] ConfigChanges.UiMode not triggered everytime Xamarin.Android

### ISSUE THREAD

**Issue by SamJames101** [xamarin/Xamarin.Forms#14518]
### Description
Switching between light and dark mode on my pixel 4a only triggers OnConfigurationChanged when navigating from settings and the application through the already open applications section (often got to by pulling up from the bottom).
If I navigate by going to the home page first and clicking on the application or settings icon and then switching theme OnCreate is triggered and not OnConfigurationChanged.

I have ConfigurationChanges = ConfigChanges.UiMode
### Steps to Reproduce

1. Open my application.
2. Navigate to the OS home page.
3. Click settings.
4. Switch theme from dark to light or vice versa.
5. Navigate to OS home page.
6. Click on my application.
7. OnCreate Is triggered and new activity is made.

### Expected Behavior
OnConfigurationChanged is hit.
### Actual Behavior
OnCreate is hit and new activity is created
### Basic Information

.Net 5.0.302
Android: 11.3.0.4 API level 27 
Affected Devices: PIxel 4a OS 10

**Comment by jfversluis** [comment]
No response to our request for more info, closing this one
