### ISSUE TITLE
[Bug] [Android] Entry needs double click to open Keyboard

### ISSUE THREAD

**Issue by NicolaSchueepp** [xamarin/Xamarin.Forms#14531]
The mentioned Bug only occurs when the Entry has a Style applied which uses the Visual State Manager. The Bug only appears to be on Android. iOS works perfectly.

If I remove the whole Visual State Manager from the Style, the Entry works as expected.
I also have a video to demonstrate the problem: https://vimeo.com/588825086

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?

**Comment by jfversluis** [comment]
No response to our request for more info, closing this one
