### ISSUE TITLE
[Bug] UWP Performance

### ISSUE THREAD

**Issue by s2886676** [xamarin/Xamarin.Forms#14532]
We have a Xamarin Forms UWP application and recently we noticed some degradation in performance of the app if used for long time. The memory usage of the app keeps increasing with every operation and is not released. We used JetBrains dotMemory tool to memory profiling and found that the unmanaged memory is constantly increasing with use of the app.

Below screenshot is taken from one of the snapshots we got from the tool. Dictionary<String, TableMapping> is constantly retained and not released from memory. We are using Sqlite for persisting data on device.

![image](https://user-images.githubusercontent.com/7592030/130733982-39adbee8-3228-4d95-bac9-ed32c7d650eb.png)

My guess is, it is complaining about the string data-type used in the Model class for the Sqlite table generation but I might be wrong here. One of our models look like below

[Table("WorkOrder")]
public class WorkOrder
{
    [JsonProperty("Workorder")]
    public string Workorder { get; set; }

    [JsonProperty("EquipmentNumber")]
    public string EquipmentNumber { get; set; }

    [JsonProperty("BasicFinishDate")]
    public string BasicFinishDate { get; set; }

    [JsonProperty("BasicStartDate")]
    public string BasicStartDate { get; set; }

    [JsonProperty("iObjNumber")]
    public string IObjNumber { get; set; }

    [JsonProperty("InspectionType")]
    public string InspectionType { get; set; }

    [JsonProperty("FunctionalLocation")]
    public string FunctionalLocation { get; set; }

    [JsonProperty("OrderDescription")]
    public string OrderDescription { get; set; }

    [JsonProperty("Location")]
    public string Location { get; set; }

    [JsonProperty("EquipmentDesc")]
    public string EquipmentDesc { get; set; }

    [JsonProperty("ADRNR")]
    public string ADRNR { get; set; }

    [JsonProperty("PriorityCode")]
    public string PriorityCode { get; set; }

    [JsonProperty("Priority")]
    public string Priority { get; set; }

    [JsonProperty("PriorityType")]
    public string PriorityType { get; set; }

    //[JsonProperty("OBJEK")]
    //public object OBJEK { get; set; }

    [JsonProperty("PoleAddress")]
    public string PoleAddress { get; set; }

    [JsonProperty("Street")]
    public string Street { get; set; }

    [JsonProperty("City")]
    public string City { get; set; }

    [JsonProperty("State")]
    public string State { get; set; }

    [JsonProperty("Country")]
    public string Country { get; set; }

    [JsonProperty("EmployeeID")]
    public string EmployeeID { get; set; }

    [JsonProperty("UserName")]
    public string UserName { get; set; }

    [JsonProperty("RoutingNo")]
    public string RoutingNo { get; set; }

    [JsonProperty("DueDate")]
    public string DueDate { get; set; }

    [JsonProperty("NotifNo")]
    public string NotifNo { get; set; }

    [JsonProperty("NotifType")]
    public string NotifType { get; set; }

    [JsonProperty("ReportedBy")]
    public string ReportedBy { get; set; }

    [JsonProperty("ShortText")]
    public string ShortText { get; set; }

    [JsonProperty("NotifDate")]
    public string NotifDate { get; set; }

    [JsonProperty("Notiftime")]
    public string Notiftime { get; set; }

    [JsonProperty("CodeGroup")]
    public string CodeGroup { get; set; }

    [JsonProperty("Coding")]
    public string Coding { get; set; }

    [JsonProperty("Plant")]
    public string Plant { get; set; }

    [JsonProperty("PlantGroup")]
    public string PlantGroup { get; set; }

    [JsonProperty("Operation")]
    public string Operation { get; set; }

    [JsonProperty("LongText")]
    public string LongText { get; set; }}
Can someone please point me in the right direction of what can be done to resolve this?

Thanks in advance.

### Expected Behavior
Release unmanaged memory
### Actual Behavior
Unmanaged memory keeps increasing when interacting with the PC
### Basic Information

- Platform Target Frameworks: 
  - UWP:  Min version: 17134, Max version: 18362
- Affected Devices: Windows

**Comment by jsuarezruiz** [comment]
From your feedback, I guess is something related with SQLite: https://github.com/TiendaNube/SQLite.Net-PCL/blob/master/src/SQLite.Net/SQLiteConnection.cs#L54 and table mappings.

Could you share a sample where debug/get more information?

**Comment by jfversluis** [comment]
No response to our request for more info. Closing for now.
