### ISSUE TITLE
[Enhancement] The Timer in the page should auto stop with the page disappear or destroyed.

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#14533]
## Summary
I use the timer to make animations or time tick.

If it is a custom control such as loading animation a timer will be needed to animate the loading screen. but if the control disappeared or removed from the page it will not stop automatically. which is not good.

If it is a page there will auto need a timer to get the data every some seconds.

If I have to stop the timer how to confirm there is only 1 timer ? MAYBE the timer 1 is working then I started another. right?

It will get error.

or can there a handle to the timer?

**Comment by jfversluis** [comment]
Hey there! I appreciate the idea, but that kind of conflicts with what a time does. Maybe there could be some specialized animation timer or such. In any case, this is not something that will be added to Xamarin.Forms anymore. If you're still interested in this, please open a suggestion on the .NET MAUI repo. Thanks!
