### ISSUE TITLE
[Bug] DidEnterBackground is not called when screen mirroring enabled

### ISSUE THREAD

**Issue by jameslavery** [xamarin/Xamarin.Forms#14543]
### Description
In the Xamarin.iOS project for a Forms solution, DidEnterBackground is not firing on a physical device when the device is mirroring its screen.

**Note that this is likely to be a Xamarin.iOS bug, not a Xamarin.Forms bug - should it be logged elsewhere?**

### Steps to Reproduce

1. Install an app which has code in the  DidEnterBackground override (e.g. Console.WriteLine calls) on a physical iOS device.
2. Enable screen mirroring on the device.
3. Run the app
4. Send the app to the background by pressing the Home button
5. Tap the app icon to bring to the foreground
6. Double-tap the home button and kill the app

### Expected Behavior
Two DidEnterBackground messages should appear in the console for the device:

> default	08:57:01.946496+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnActivated called.
> default	08:57:05.522005+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnResignActivation called.
> default	08:57:06.287650+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== DidEnterBackground called.
> default	08:57:09.709672+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== WillEnterForeground called.
> default	08:57:10.007193+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnActivated called.
> default	08:57:13.031387+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnResignActivation called.
> default	08:57:14.372900+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== DidEnterBackground called.
> default	08:57:14.377309+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== WillTerminate called.

### Actual Behavior
The DidEnterBackground messages do not appear in the console for the device:

> default	09:17:16.803024+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnActivated called.
> default	09:17:23.129652+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnResignActivation called.
> default	09:17:34.044914+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== WillEnterForeground called.
> default	09:17:34.213623+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnActivated called.
> default	09:17:42.993226+0100	DidEnterBackgroundDemo.iOS	DidEnterBackgroundDemo== OnResignActivation called.

### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version: Not known
- Platform Target Frameworks: 
  - iOS:  14.16.0.5
  - Android: N/A
  - UWP:  N/A
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: Xamarin.Forms 5.0.0.2083
- Affected Devices: iPhone S running iOS 14.7.1

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.8 (build 0)
Installation UUID: aa2a25e1-a1b4-47f4-9fa5-459af02ae7e8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.412
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.202
	3.1.200
	3.1.102
	3.1.101
	3.0.101
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.18
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.0.1
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.15
	2.1.14

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/jameslavery/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.0 (API level 24)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/jameslavery/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810080000
Git revision: 0bc91c25997e4c374dc6eb96809c7bf52f6a7c33
Build date: 2021-08-18 14:50:30-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 4.4.8
Straight8's SpecFlow Integration 1.11.3.0
AddinMaker 1.6.0
XAML Styler 2.0.1
Resource Dictionary Adder 1.0
Project System Tools 0.4


```

</details>

### Screenshots
N/A

### Reproduction Link

[DidEnterBackgroundDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/7055670/DidEnterBackgroundDemo.zip)

### Workaround

None found.

**Comment by jsuarezruiz** [comment]
@mandel-macaque Could we have your help or from someone from the iOS team to validate if this happens also without using Xamarin.Forms?
