### ISSUE TITLE
[Enhancement] Can listview group header Sticky on android ?

### ISSUE THREAD

**Issue by maonaoda** [xamarin/Xamarin.Forms#14540]
## Summary
Unlike iOS,listview with group header cant Sticky when scrolling,Is there any plan to change this ？

**Comment by jfversluis** [comment]
@maonaoda thanks for the suggestion. This is not going to be added in Xamarin.Forms, please see if there is a suggestion for this already in .NET MAUI and if not, add the request there. Maybe with a bit more detail on how you would like it to work exactly.

In the meantime, there is also this one: https://github.com/xamcat/Scratch/tree/master/FormsStickyHeaders that works with `CollectionView``

**Comment by maonaoda** [comment]
@jfversluis 
Thank you for your suggestion.

Due to various problems with collectionView on ios, I finaly have to use listview on ios and use custom collectionView on android.
It seems a bit contrary to the concept of unity. 

In addition, if I have time, I will try .NET MAUI . :)
