### ISSUE TITLE
[Bug] NullReferenceException in DragAndDropGestureHandler.<OnLongPress> on Android

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#14552]
### Description

NullReferenceException inside Xamarin.Forms when using a DragGestureRecognizer. I believe this is a regression, possibly in the latest XF release, but I'm not 100% sure.

### Steps to Reproduce

1. Create a page containing a ListView, whose Viewcells have a StackLayout with a CheckBox and a Label. Add a DragGestureRecognizer to the Label.
2. Open that page on a real phone.
3. Start tapping the checkboxes with your finger.
4. See if you can tap them all before the page crashes

### Expected Behavior

No exceptions thrown.

### Actual Behavior

NullReferenceException inside Xamarin.Forms. I haven't been able to reproduce this in a debugger, but it's easy with a release build on a phone. This is the stack trace:

DragAndDropGestureHandler.<OnLongPress>b__19_0 (Xamarin.Forms.DragGestureRecognizer rec)
DragAndDropGestureHandler.SendEventArgs[TRecognizer] (System.Action`1[T] func, Xamarin.Forms.View view)
DragAndDropGestureHandler.OnLongPress (Android.Views.MotionEvent e)
IOnGestureListener.OnLongPress (Android.Views.MotionEvent e)
GestureDetector+IOnGestureListenerInvoker.n_OnLongPress_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.164(intptr,intptr,intptr)

### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version: Unknown
- Platform Target Frameworks: 
  - Android: 11.0 (R)
- Android Support Library / AndroidX Version: Latest
- NuGet Packages:
- Affected Devices:

### Environment

Microsoft Visual Studio Enterprise 2019
Version 16.11.2
VisualStudio.16.Release/16.11.2+31624.102
Microsoft .NET Framework
Version 4.8.04084

Xamarin   16.11.000.174 (d16-11@e8f56f1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.17 (remotes/origin/11e0001f0b17269345e80b58fb3adf1ba4efe2cd@11e0001f0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.0.5 (d16-11/7776c9f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@48766c0
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@683f375

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks.

**Comment by mfeingol** [comment]
@jsuarezruiz: here's a repro project.

[DragAndDropCrashRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/7145498/DragAndDropCrashRepro.zip)

Can't reproduce in emulator, but was able to reproduce with a debug build on a physical device. Just drag and drop items around until you see a NullReferenceException here:

 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:125,4	C#	Annotated Frame
 	0x26 in Android.Runtime.DynamicMethodNameCounter.87	C#	Annotated Frame
 	0x1D in Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.<OnLongPress>b__19_0 at D:\a\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:254,5	C#	Annotated Frame
 	0x3F in Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.SendEventArgs<Xamarin.Forms.DragGestureRecognizer> at D:\a\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:103,5	C#	Annotated Frame
 	0x17 in Xamarin.Forms.Platform.Android.DragAndDropGestureHandler.OnLongPress at D:\a\1\s\Xamarin.Forms.Platform.Android\DragAndDropGestureHandler.cs:247,4	C#	Annotated Frame
 	0xE in Xamarin.Forms.Platform.Android.InnerGestureListener.Android.Views.GestureDetector.IOnGestureListener.OnLongPress at D:\a\1\s\Xamarin.Forms.Platform.Android\InnerGestureListener.cs:120,4	C#	Annotated Frame
 	0x11 in Android.Views.GestureDetector.IOnGestureListenerInvoker.n_OnLongPress_Landroid_view_MotionEvent_ at /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-30/mcw/Android.Views.GestureDetector.cs:612,5	C#	Annotated Frame
 	0x17 in Android.Runtime.DynamicMethodNameCounter.87	C#	Annotated Frame

**Comment by mfeingol** [comment]
@jsuarezruiz: will that fix be released in an SR at some point?

Thanks.

**Comment by jfversluis** [comment]
@mfeingol, a PR (#14634) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by mfeingol** [comment]
Thanks, @jfversluis. I updated to 5.0.0.7867 from the PR feed and I was unable to repro the crash or any other issues with drag and drop in the context I discussed above. So I think we can call it a fix.

I guess it would be nice if the ListView scrolled when I drag something to the top or bottom of it. But that's a different conversation. :-)

**Comment by jfversluis** [comment]
Perfect, thanks for letting us know!

Haha that is indeed a different conversation. On the other hand... Is that something the OS typically does? I'm now thinking of how iOS has implemented drag & drop OS wide. They also expect you to use 2 fingers and even drag & drop across different apps and such. Does dragging and scrolling up manually work?

Anyway, definitely something to think about here. Thanks for working together with us on this one!
