### ISSUE TITLE
Context action are not changed when selected item changed on Android

### ISSUE THREAD

**Issue by xamoulin** [xamarin/Xamarin.Forms#1455]
### Description

The context actions on Android are not the action of the last selected cell in "long pressed" mode, they are the ones of the originally long pressed cell.

### Steps to Reproduce

1. Have a ListView containing at cells with different MenuItem
2. Long pressed on a cell
3. Select another cell while in "long pressed" mode

### Expected Behavior

The context actions in the ContextActionsBar are replaced by the ones of the newly selected cell.
Or it is not allowed to select another cell.

### Actual Behavior

The context actions in the ContextActionsBar are not replaced. Also, given less context actions in the last selected cell, an OutOfRangeException will result when selecting the last action(s).

### Basic Information

- Version with issue: 2.5.0.121934
- IDE: Rider 2017.2 on Mac
- Platform Target Frameworks:
  - Android: 7.1.1
- Android Support Library Version: 26.1.01
- Affected Devices: Android Simulator API 25

**Comment by rmarinho** [comment]
Hi, we have tried to reproduce and it worked as expected. Can you please provide a small repro app so we can take a look?!

Thanks.

**Comment by xamoulin** [comment]
Here's a repro app. Half of the employees should have 2 context actions and the others 3.
[ListViewCabBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1583085/ListViewCabBug.zip)

**Comment by kingces95** [comment]
Reproduction exhibits stated actual behavior.
