### ISSUE TITLE
[XForms IOS] We have a project in xamarin forms IOS, And our app not installed in IOS 15 beta os versions.

### ISSUE THREAD

**Issue by Yuvaraj-007** [xamarin/Xamarin.Forms#14574]
### Description

One of our project developed in xamarin forms IOS platform, we are using Xamarin forms version as 2.5 

### Steps to Reproduce

1. Create a simple xamarin forms IOS app using the version as 2.5
2. Get the ipa file on IOS, or create the build for ipa file.
3. Try to install it in the IOS 15 beta os installed device like ipad or iphone.
4. Its not installed so's error. 

### Expected Behavior

App installed without any error

### Actual Behavior

app not installed so's error

### Basic Information

- Version with issue: 2.5
- Last known good version: NA
- Platform Target Frameworks: 
  - iOS:  15 beta os
  - Android: NA 
  - UWP:  NA 
- Android Support Library / AndroidX Version: NA
- NuGet Packages: NA
- Affected Devices: IOS 15 installed devices

### Environment

NA

### Screenshots

<img width="272" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/40380876/132045472-37f20a2b-f7f1-4a0a-a3f0-643d36e4d11a.png">

### Reproduction Link

NA

### Workaround

Xamarin IOS native apps works installed and works fine in IOS 15 os installed devices

**Comment by jfversluis** [comment]
@Yuvaraj-007 thanks for the report! You mean you are using Xamarin.Forms 2.5?

**Comment by Yuvaraj-007** [comment]
Hi @jfversluis,

Thanks for the response.

Yes. I am using xamarin forms version as 2.5

**Comment by jfversluis** [comment]
In that case I'm afraid I will have to close this one. The last version of 2.5 came out more than 3 years ago, unfortunately its not feasible for us to support that with a OS version that is coming out today. Please update to a more recent version of Xamarin.Forms. Thanks!
