### ISSUE TITLE
[Bug] Bindings Converter Culture uses CurrentCulture instead of CurrentUICulture

### ISSUE THREAD

**Issue by mos379** [xamarin/Xamarin.Forms#14600]
Shouldn't the Ui culture always be used for bindings?
When having different cultures for the code and backend communication from the UI then this fails.

### Steps to Reproduce

1. System.Globalization.CultureInfo.DefaultThreadCurrentUICulture = new System.Globalization.CultureInfo("de-DE");
2. System.Globalization.CultureInfo.DefaultThreadCurrentCulture = new System.Globalization.CultureInfo("en-US");
3. Create Binding for Label with date as Text with converter
4. <Label Text="{Binding Key, Converter={StaticResource DateTemplateConverter}, StringFormat='{0:D}'}" />

### Expected Behavior
presentation of UI should be in format "Sonntag, 12. September 2021"
### Actual Behavior
presentation of UI is in format "Sunday, September 12, 2021"
### Basic Information

- Version with issue: 5
- Last known good version: Don't know

**Comment by jsuarezruiz** [comment]
Right, but would be a big breaking change that could impact a lot in existing Xamarin.Forms Apps. I think, maybe .NET MAUI is a better way to introduce this change.

**Comment by mos379** [comment]
@jsuarezruiz hmm didn't think it would be a breaking change as probably most people changed the overall culture instead of just the UI culture, but ok. 
Then as a compromise maybe #12181 could see a bump in priority?

**Comment by jfversluis** [comment]
As mentioned this will be a big breaking change that we're not going to do for Forms anymore, sorry about that.

I did [open a proposal for .NET MAUI](https://github.com/dotnet/maui/issues/5696) to add the `ConverterCulture`. If you want to make the default experience better feel free to check if this behavior still exists in .NET MAUI and open a proposal to change it. Thanks!
