### ISSUE TITLE
I have this happening in version 5.0.1.1876 was there ever a fix ?

### ISSUE THREAD

**Issue by kmvickers** [xamarin/Xamarin.Forms#14605]
I have this happening in version 5.0.1.1876 was there ever a fix ?

_Originally posted by @kmvickers in https://github.com/xamarin/Xamarin.Forms/issues/12315#issuecomment-918133284_

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?

**Comment by kcrg** [comment]
@kmvickers 5.0.1.1876 is faar behind, it is old package from January 5, 2021. Don't use nightly nuget feed and try latest stable 5.0.0.2083.

**Comment by jfversluis** [comment]
I didn't pick up on that version number, yeah, that definitely isn't right! Please use the latest package from stable and let us know if it's still an issue.

Thanks @kcrg !
