### ISSUE TITLE
Cannot change TimePicker format 

### ISSUE THREAD

**Issue by jonpryor** [xamarin/Xamarin.Forms#1461]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Steps to Reproduce
1. Turn the "Use 24-hour format" device setting off on your test device
2. Create a TimePicker
3. Change the format sometime later on (e.g. when the user clicks a button)

### Expected Behavior
TimePicker displays time in new format

### Actual Behavior
TimePicker still displays time in original format

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.91635

### Proposed Fix
I can see the problem in Xamarin.Forms.Platform.Android.TimePickerRenderer. The format is cached in OnElementChanged then never gets updated. Presumably, the format just needs to be refreshed in OnElementPropertyChanged if FormatProperty has changed.

**Comment by jonpryor** [comment]
Moved from: https://github.com/xamarin/xamarin-android/issues/1140

**Comment by samhouts** [comment]
[Issue1461.zip](https://github.com/xamarin/Xamarin.Forms/files/1598999/Issue1461.zip)
