### ISSUE TITLE
[Bug] [Regression] Frame BackgroundColor is flashing Black while fast scrolling list

### ISSUE THREAD

**Issue by kcrg** [xamarin/Xamarin.Forms#14610]
### Description
Frame is initially Black and changes its color to as set after a few milliseconds.
iOS seems fine.

### Steps to Reproduce

1. Create CollectionView.ItemTemplate with Frame.
2. Add many items to list.
3. Try to scroll fast.
4. If you are not able to reproduce, kill app and try again.

### Expected Behavior
Frame's BackgroundColor should always be as set.

### Actual Behavior
The BackgroundColor of the frames is initially Black and changes to set after a few milliseconds.

### Basic Information

- Version with issue: **PREVIEW** 5.0.0.**7492**
- Last known good version: 5.0.0.2083
- Platform Target Frameworks: 
  - Android: 11
- NuGet Packages: XF 5.0.0.**7492**
- Affected Devices: Tested on Pixel 3a Android emulator

### Screenshots
![Screenshot_1631571102](https://user-images.githubusercontent.com/7996711/133164034-82ff3783-ac89-4e47-bb4d-cd9493245e98.png)
I was able to capture it in the screenshot.

### Reproduction Link
[FlashingFrameList.zip](https://github.com/xamarin/Xamarin.Forms/files/7157675/FlashingFrameList.zip)

### Workaround
I don't have any.

**Comment by kcrg** [comment]
I'm not sure it is good to report issue from preview version of XF, but recently I saw preparing for releasing [SR5](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr5) and I was worried about this issue. 

If you know this and it has been fixed in the stable release, feel free to close this issue. 
I was unable to download the stable SR5 as it is not yet available on nuget.org.

**Comment by PawKanarek** [comment]
Maybe its because of this line? 
https://github.com/xamarin/Xamarin.Forms/pull/11812/files#diff-52fb832157b4fecfcddfb8e6adaeda5990c2616ce9b208cb441460ecbd24d8f6R178

**Comment by kcrg** [comment]
Works great on XF 5.0.0.2125
