### ISSUE TITLE
Customized Ellipsis on Label

### ISSUE THREAD

**Issue by copang** [xamarin/Xamarin.Forms#14622]
Hello,
As the title says, I want to replace "..." with "...read more" when the label is truncated in Xamarin Forms.
Sorry for my bad english and I hope to get your help.
Thank you very much!

**Comment by jfversluis** [comment]
Unfortunately not possible with anything inside the APIs :) hope you got something figured out by now! If not, please ask on forums or in the discussions, that is better suited for questions. Thanks!
