### ISSUE TITLE
Secure ldap(s) authentication with root certificate

### ISSUE THREAD

**Issue by cemselman** [xamarin/Xamarin.Forms#14627]
## Summary
Ability to make secure ldaps authentication with certificates to ldaps servers. This is important for security reasons as lots of ldap servers are becoming ldaps servers in these days.

## Intended Use Case
My company was using ldap server without certificate with cleartext login. Now all ldap servers are converted to ldaps server. So i have to update our mobile applications to make ldap connection securely with ca root certificate over new ldap(s) servers.

**Comment by jfversluis** [comment]
Thanks for your suggestion! However, it's not really clear to me what needs to be done to support this scenario or how you would want this to work. I would think the changes of getting this into Xamarin.Forms will be pretty low as it's a completely new feature.

If this is something you're still interested in, please consider opening a feature request on the .NET MAUI repo and add a bit more detail on the what and how.

Thanks!
