### ISSUE TITLE
How to load gif on launch screen of xamarin forms iOS application.

### ISSUE THREAD

**Issue by Meera18** [xamarin/Xamarin.Forms#14637]
Following approaches I tried with unsuccessful attempt,

- Tried integrating gif directly on launch screen, which couldn't seem to be possible
- Tried adding multiple images in Xamarin native iOS project to use animation through custom native UIView, UIViewController and calling Xamarin MainPage after that. Here not able to load MainPage after UIViewController.
- Tried using Lottie animation library. When used in MainPage, default launch screen is shown, which is not required.
- Tried creating xib file and to set as launch screen. Here l was trying to use Lottie animation on xib which is not visible.

Please help me here, or point out if I am doing something wrong.

**Comment by ShinichiHezemansCortegs** [comment]
I just have a gif on the first page of the application.

` <Grid>
        <Image Source="TapToStart.gif" IsAnimationPlaying="True" Aspect="AspectFill" />
        <Button Command="{Binding OnTap}" BackgroundColor="Transparent"/>
    </Grid>`
    
But The gif is not played at it's correct speed #9974

there is a work around using the Xamarin.FFImageLoading.Forms nuget package as mentioned in #9974, by adding 2 lines in your appdelegate
`     FFImageLoading.Forms.Platform.CachedImageRenderer.Init();
            FFImageLoading.Forms.Platform.CachedImageRenderer.InitImageSourceHandler();`

There are still some weird artifacts on android tho. Haven't found a solution for that yet. Let me know if you find one.

**Comment by Meera18** [comment]
Thanks @ShinichiHezemansCortegs for replying.
Yes, after adding this to first page, launch screen will still loads first. Hence this approach will not work for me.

**Comment by ShinichiHezemansCortegs** [comment]
I don't know if you still have this issue, but there is a blog about using Animated Splash Screen with Magic Gradients.
https://medium.com/nerd-for-tech/animated-splash-screen-with-magic-gradients-3f372af65c07
but this also just uses the first screen for animation instead of the actual splash screen.

**Comment by jfversluis** [comment]
Hope you got this resolved by now!
