### ISSUE TITLE
[Bug] Unable to enter and edit the text into the Entry on macOS when NSWindowStyle.Borderless

### ISSUE THREAD

**Issue by akarasev** [xamarin/Xamarin.Forms#14630]
### Description

It seems not possible to use the [Entry](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry) in the macOS app with any `NSWindowStyle` unless `NSWindowStyle.Titled` specified. I want to enter text in the `NSWindowStyle.Borderless` window.

### Steps to Reproduce

1. Download the [sample project](https://github.com/akarasev/XamarinFormsEntryIssueDemo) or create a blank Xamarin.Form project as described [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac)
2. Go to the `AppDelegate.cs` and use the `NSWindowStyle.Borderless` style on the `NSWindow` creation
3. Go to `MainPage.xaml` and add the `<Entry/>` tag
4. Run the project

### Expected Behavior

I can enter and edit the text into the Entry.

### Actual Behavior

I cannot enter the text. I cannot even put the cursor into the Entry.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks:
  - macOS: Xamarin.Mac 7.14.0.24
- Android Support Library / AndroidX Version: no
- NuGet Packages:
  - Xamarin.Forms (5.0.0.2083)
- Affected Devices:
  - MacBook Pro 13" M1

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.10.9 (build 3)
Installation UUID: 93be15a8-a7a1-4808-aecc-f66038546f3d
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	5.0.302
	3.1.412
	3.1.411
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	5.0.8
	3.1.18
	3.1.17

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Professional)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Professional)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Build Information ===

Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:27 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 x86_64

=== Enabled user installed extensions ===

VsVim 2.8.0.13


```

</details>

### Screenshots

<img width="1024" alt="screenshot_1" src="https://user-images.githubusercontent.com/4178395/133793219-20007cc2-5a93-4fc1-b9eb-0c1e5d5e62b0.png">
<img width="1024" alt="screenshot_2" src="https://user-images.githubusercontent.com/4178395/133793222-b01cecdd-a78e-43fa-a07c-1fdb0d2d97f7.png">

### Reproduction Link

https://github.com/akarasev/XamarinFormsEntryIssueDemo

### Workaround

Not found

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
