### ISSUE TITLE
[Bug] iOS 15 - Xcode version 13.0 - Visual Studio Enterprise 2019 for Mac Version 8.10.9 - error HE0003: Could not load the framework 'IBFoundation'

### ISSUE THREAD

**Issue by Vinayak-Nikam** [xamarin/Xamarin.Forms#14639]
Xamarin not working with iOS 15 and XCode 13

My iPhone 11 and iPhone 12 Pro Max got upgraded to iOS 15.
I have Xcode version 13.0 (13A233) installed on macOS Big Sur Version 11.5.1
Visual Studio Mac is upgraded to latest -
Visual Studio Enterprise 2019 for Mac === Version 8.10.9 (build 3)
=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Enterprise)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

### Steps to Reproduce

1. Building the Xamarin.Forms projects succeeds.
2. Deploying to physical device fails with error -
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mlaunch -sdkroot "/Applications/Xcode.app/Contents/Developer" --installdev "/Users/"username"/Source/~projectdir/bin/iPhone/Debug/device-builds/iphone13.4-15.0/appname.app" --device ios "--devname=physicaldevicename" --install-progress
error HE0003: Could not load the framework 'IBFoundation' (path: /Applications/Xcode.app/Contents/Frameworks/IBFoundation.framework/IBFoundation): not found.
        

Application could not be uploaded to the device.

**Comment by IoTFier** [comment]
Hi @Vinayak-Nikam, 
I don't think the nuget package for Xamain.iOS to support XCode 13 is ready yet.
The version you mentioned is even one version behind packaged the VS 2019 16.11

We have to wait for the Xamarin apple team to release the new Xamarin.iOS nuget for XCode 13.

**Comment by Vinayak-Nikam** [comment]
Downgrading to Xcode 12.5.1 resolved the issue. But I would appreciate if I get to know when Xamarin.iOS 15 will be released supporting Xcode 13.

**Comment by kcrg** [comment]
@Vinayak-Nikam Check this: https://github.com/xamarin/xamarin-macios/issues/12778

**Comment by jfversluis** [comment]
As @kcrg pointed out, there is the status, not much we can do about it here unfortunately. I can only advise to not update to Xcode 13 yet until support is released.

**Comment by SJaschinski** [comment]
Hi @jfversluis, I do not get the full picture here: In my case we had to upgrade to XCode 13 to build our Xamarin Forms app to build using it otherwise our app will not start on iOS 15. You will just get the message as a user of the app that the developers need to update the app. So, how can we not update to XCode 13 right now when our user base is adopting iOS 15 rapidly?

**Comment by jfversluis** [comment]
@SJaschinski the full picture is: this is not a Xamarin.Forms problem :) Check out the linked issue on the macios repo above, there is already a binary that allows you to build with Xcode 13 and the release is pending. There should be nothing blocking you from working with iOS 15 and Xcode 13.

**Comment by SJaschinski** [comment]
Hi @jfversluis, thanks for your fast response. I can confirm that the new version 8.10.10 of Visual Studio for Mac that dropped two hours after your last comment did fix my problem. Still some visual changes in the app after the upgrade without any code changes but that should be something that can be solved. Thanks again!

**Comment by jfversluis** [comment]
No worries @SJaschinski I can imagine that when it's about your day job you want to know what it's about. Glad that it's resolved! There are indeed some visual things, also in Forms, we're working on those. Track down the issues and add some extra info if you have some. Thanks!
