### ISSUE TITLE
[Bug] Vector image not showing on real iOS devices

### ISSUE THREAD

**Issue by LITTOMA** [xamarin/Xamarin.Forms#14632]
### Description
Vector image not showing on real iOS devices

### Steps to Reproduce

1. Import vector image in PDF format to asset directory.
2. Build the app.
3. Launch in debug mode.

### Expected Behavior
Vector image shows on the Image element

### Actual Behavior
Nothing shows up

### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version: None
- Platform Target Frameworks: 
  - iOS:  14.5
- NuGet Packages:
- Affected Devices: iPhone X

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks.

**Comment by LITTOMA** [comment]
@jsuarezruiz Please check [this](https://github.com/LITTOMA/VectorImageTest)

**Comment by jsuarezruiz** [comment]
Is the repository public? https://github.com/LITTOMA/VectorImageTest Cannot access to it.

**Comment by LITTOMA** [comment]
Sorry, it was private. Made it public now.

**Comment by LITTOMA** [comment]
Do you need more information?
