### ISSUE TITLE
[Bug] In iOS Spacing is added on Top+Left of Grid in CollectionView

### ISSUE THREAD

**Issue by kwdo** [xamarin/Xamarin.Forms#14633]
### Description/Actual Behavior
For grids that are embedded in a CollectionView, approx. 1px spacing is inserted in iOs on the left and above. 
Unfortunately, there is always a small border on the left side of teaser images. Android is OK.

### Expected Behavior
Grids can be inserted in CollectionViews without spacing. You can insert teaser images that take up the full width of the screen.

For grids that are embedded in a CollectionView, approx. 1px spacing is inserted in iOs on the left and above. 
Unfortunately, there is always a small border on the left side of teaser images. Android is OK.

### Steps to Reproduce
As an example I used the Xaminals Sample and made the following changes.

in Views/BearsPage.xaml

`<CollectionView Margin="20"
    ItemsSource="{x:Static data:BearData.Bears}"`

to

`<CollectionView Margin="0"
    ItemsSource="{x:Static data:BearData.Bears}"`

in App.xaml

`<DataTemplate x:Key="AnimalTemplate">
            <Grid Padding="10"`    

to

`<DataTemplate x:Key="AnimalTemplate">
            <Grid Padding="0"`

  ### Basic Information

  - Version with issue: 5.0.0.2083
  - Last known good version: -
  - Platform Target Frameworks: 
    - iOS:  14.5
  - Affected Devices: all iOS

### Screenshots
iOS (Bug)
![ios](https://user-images.githubusercontent.com/8319760/133986581-1710460e-0e9b-4fc8-abae-71100e541012.png)

Android(Good)
![android](https://user-images.githubusercontent.com/8319760/133986567-f1c1d305-a15b-4c46-8bd7-058704333b70.png)

**Comment by jsuarezruiz** [comment]
Seems to be the same or related with https://github.com/xamarin/Xamarin.Forms/issues/12287

**Comment by kwdo** [comment]
Thanks. I can confirmed that the workaround from #12287 worked here too. Thanks @jsuarezruiz
