### ISSUE TITLE
Throwing "NullReferenceException" in pop NavigationPage at MasterDetailPage in iOS

### ISSUE THREAD

**Issue by paradisehuman** [xamarin/Xamarin.Forms#1464]
### Description
I'm using push notification. I track which notification pressed and navigate to the correct page.
Here is my code : 
 ```csharp
 public MainPageMasterDetail(string type,string data)
        {
            var dependencyInjection = App.DependencyInjection();
            _masterPage = new MasterPage { BindingContext = new MasterPageViewModel() };
            Master = _masterPage;
            var mainNavigation = new NavigationPage(new MainPage
            {
                BindingContext = dependencyInjection.Resolve<MainPageViewModel>(),
                Title = Taxi.Resources.Common.ResourceManager.GetString("BetaVersion",
                    new CultureInfo(Application.Current.Properties["Culture"].ToString()))
            });
                switch (type)
                {
                    case nameof(NotificationTypes.SubmitRequestByWorker):
                    {
                        mainNavigation.PushAsync(new TripArchivePage
                        {
                            BindingContext = new TripArchivePageViewModel()
                        });
                        var model = App.DependencyInjection().Resolve<RequestDetailPageViewModel>();
                        model.RequestId = data;
                        mainNavigation.PushAsync(new RequestDetailPage { BindingContext = model });
                        break;
                        }
                    case nameof(NotificationTypes.SendChat):
                    {
                        mainNavigation.PushAsync(new TripArchivePage
                            {
                                BindingContext = new TripArchivePageViewModel()
                            });
                            var requestDetailPageModel = App.DependencyInjection().Resolve<RequestDetailPageViewModel>();
                            requestDetailPageModel.RequestId = data;
                            mainNavigation.PushAsync(new RequestDetailPage { BindingContext = requestDetailPageModel });
                            var chatModel = App.DependencyInjection().Resolve<ChatPageViewModel>();
                            chatModel.RequestId = data;
                            mainNavigation.PushAsync(new ChatPage
                            {
                                BindingContext = chatModel
                            });
                        break;
                    }
                }
            if (Device.RuntimePlatform == Device.Android)
                mainNavigation.BarBackgroundColor = Color.FromHex("9649cb");
                Detail = mainNavigation;
                if (Device.RuntimePlatform == Device.iOS)
                Master.Icon = "Hamburger.png";
            _masterPage.FirstListView.ItemSelected += OnItemSelected;

            _masterPage.SecondListView.ItemSelected += OnItemSelected;
        }
```
Everything is working fine on Android but in iOS for example when I going to chatPage and going back by navigation back button , first pop ,every thing is working as expected , second pop,every thing is working as expected until it reaches to root page and when trying to pop the root page , I got this error in iOS : 

> System.NullReferenceException: Object reference not set to an instance of an object

Here is my StackTrace:

> 1-MainPage+<>c__DisplayClass36_0+<<-ctor>b__2>d.MoveNext () C:\Visual Studio Projects\Eela\Eela.Taxi\Eela.Taxi\Pages\MainPage.cs:468
> 
> 2-ExceptionDispatchInfo.Throw () /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152
> 
> 3-AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018
> 
> 4-UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIKitSynchronizationContext.cs:24
> 
> 5-NSAsyncActionDispatcher.Apply () /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/Foundation/NSAction.cs:163
> 
> 6-(wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
> 
> 7-UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:79
> 
> 8-UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/src/UIKit/UIApplication.cs:63
> 
> 9-Application.Main (System.String[] args) C:\Visual Studio Projects\Eela\Eela.Taxi\Eela.Taxi.iOS\Main.cs:17

 

### Steps to Reproduce

1. Create a Navigation page in master detail page and initial the Detail property in constructor with it
2. Push a page in navigation at master detail page constructor.
3. Pop the pages by back button until it reaches to root page.

### Expected Behavior
Pop the pages to root page
### Actual Behavior
When pop the pages until reaches to root, it throws this exception : 

> System.NullReferenceException: Object reference not set to an instance of an object

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version:-
- IDE: Visual Studio 2017 15.5.2
- Platform Target Frameworks: .netstandatd 2.0
  - iOS:  11.2
  - Android: 7.1 
  - UWP:  -
- Android Support Library Version: 26.1.0.1
- Nuget Packages:-
- Affected Devices:
iPhone 5s , Android emulator

**Comment by paradisehuman** [comment]
After I investigated the problem and reproduced the project, I figured it out it wasn't Xamarin.Forms problem at all !
It was a another Nuget package problem.
Any way after deleting the package code , the problem is gone.

**Comment by kirillkostrov** [comment]
@paradisehuman What other Nuget package caused your case?

**Comment by paradisehuman** [comment]
@kirillkostrov 
[Xamarin.Forms.GoogleMaps](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/)
When the map initialized in Constructor, this was caused the error.
I moved the initialization to OnAppearing method, error was gone.
