### ISSUE TITLE
[Bug] Potential NullReferenceException in IndicatorView

### ISSUE THREAD

**Issue by JunkyXL86** [xamarin/Xamarin.Forms#14654]
See: https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Core/IndicatorView.cs#L131

Stumpled upon it accidentally. IF condition should check for NOT null.

**Comment by jsuarezruiz** [comment]
Changed https://github.com/xamarin/Xamarin.Forms/pull/14659
