### ISSUE TITLE
[Enhancement] ScrollTo Method for grouped collection view so that header is visible

### ISSUE THREAD

**Issue by ziomek64** [xamarin/Xamarin.Forms#14650]
## Summary
It would be nice to have a scroll method to scroll to specific group by index but in a way so that header of the group is fully visible at the top (or define position like in current scrollto method). Right now I scroll to item 0 of group x, the closest to the suggestion I give. I can do ScrollToPosition.Center but that's not it
## API Changes

Something like

var index = 0;
CollectionView.ScrollToGroup(x)

So CollectionView would have like an additional method or something.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
