### ISSUE TITLE
[Bug] Is XF Shell navigation leaking memory?

### ISSUE THREAD

**Issue by danielkraut** [xamarin/Xamarin.Forms#14657]
### Description

Every time app adds a page to navigation stack via `Shell.Current.GoToAsync("MyPage")` a new instance is created, which is to be expected. But after navigating back (either with `Shell.Current.GoToAsync("..")` or with back button) that page is never released from memory or at least is seems that it is the case. I have tried to check it with a finalizer but it is never called, which may be an implementation detail but having also some private object created then its finalizer is also never called and that seems like a bug. I also tried to use Xamarin Profiler which also shows that alive objects are only growing.

When using the older navigation style - `PushAsync, PopAsync` - finalizers are called properly. I will attach a minimal example app to demonstrate the issue which is just the project autogenerated by Visual Studio stripped down to just 2 pages.

If this behavior is expected I would like to get a clarification how XF.Shell manages memory. Right now I am dealing with my own application which after some time only increases its memory usage and never releases it and I am wondering if XF.Shell may be responsible for that. This same issue have already been discussed here https://github.com/xamarin/Xamarin.Forms/issues/11476 but I don't think it was resolved in any way as the responders focused on Messagin centre but I am not using that.

### Steps to Reproduce

1. Create Xamarin Forms Shell application
2. Create 2 pages - one home page and the other registered with `Routing.RegisterRoute`
3. Add button to navigate from main page to other page and back
4. Add private field to other page which contain object of some custom class
5. Add finalizer to other page and custom class, put breakpoint or writing to console to the finalizer
6. Navigate back nad forth between main page and other page
7. Observer that finalizers are never called

### Expected Behavior

Allocated data is released when a page is removed from navigation stack.

### Actual Behavior

Finalizer of the removed page or finalizer of any object the page has reference to is never called.

### Basic Information

- Version with issue: 5.0.0-sr3, 5.0.0-sr4
- Last known good version: unknown
- Platform Target Frameworks: 
  - Android: 10, 11 (haven't tried other OS/platforms)
- NuGet Packages: none
- Affected Devices: all

### Environment

Visual Studio: Visual Studio 2019 16.9.3, 16.11.2

### Screenshots

![obrazek](https://user-images.githubusercontent.com/33424430/134741667-619caa40-1f37-4a58-9e4f-7be490ffc6b7.png)

### Reproduction Link

Minimal example:
[ShellMemoryLeak.zip](https://github.com/xamarin/Xamarin.Forms/files/7228483/ShellMemoryLeak.zip)

**Comment by jfversluis** [comment]
This can be closed for now: https://github.com/xamarin/Xamarin.Forms/pull/14717#issuecomment-1011104514
