### ISSUE TITLE
[Bug] In Xamarion.forms ListView has some issue with iOS 15

### ISSUE THREAD

**Issue by reddy4** [xamarin/Xamarin.Forms#14674]
### Description

In iOS 15 ListView has some default white space at top.

### Steps to Reproduce

Just open existing application which is having ListView  in iOS 15.

**Comment by jsuarezruiz** [comment]
Seems to be the same or related with https://github.com/xamarin/Xamarin.Forms/issues/14664

**Comment by jfversluis** [comment]
Duplicate of #14664
