### ISSUE TITLE
Please make a clear and up-to-date roadmap available

### ISSUE THREAD

**Issue by danielkatz** [xamarin/Xamarin.Forms#1467]
The [current official roadmap](https://forums.xamarin.com/discussion/85747/xamarin-forms-feature-roadmap) is outdated (vNext is 2.5.0, it doesn't contain RTL support as planned, and more...)

If I may suggest moving the roadmap into GitHub and updating it on a monthly basis, so users could plan accordingly.

**Comment by pauldipietro** [comment]
We are aware of the need to update the roadmap. In the meantime, you can keep an eye on the projects tab to see our active triage/vCurrent/vNext projects for what's in the pipeline and being worked on. Please only use the issues feature to report bugs or propose new features. Thanks!
