### ISSUE TITLE
[Bug] Grid children tap event don't fire correctly

### ISSUE THREAD

**Issue by Rades98** [xamarin/Xamarin.Forms#14677]
### Description
I have several objects in Grid with TapGestureRecognizer but whenever I tap any of generated item, it always fires the latest one added event. But when I use StackLayout instead of Grid firing events works fine, but the formatting is mess.. So I would like to use grid, but need to figure out some workaround. AbsoluteLayout do the same as Grid

### Steps to Reproduce

1.  I have object [hexagon](https://pastebin.com/JHb9Pqcx)
2.  Than I have [MainPage](https://pastebin.com/TXQMkn1D)
3.  And enum with hexagon states (this part works)

### Expected Behavior
When I tap on any of hexagon I want it to change color

### Actual Behavior
Doesn't matter which one I tap, always fires event of the last element

**Comment by jsuarezruiz** [comment]
What Xamarin.Forms version are you using?, happens on Android, iOS etc?

**Comment by jfversluis** [comment]
No response to our request for more information. Assuming that this is no longer an issue. Thanks!
