### ISSUE TITLE
[Bug] [iOS] [TimePicker] [iPad] Wrong Keyboard Displays When Tapping New UIDatePicker

### ISSUE THREAD

**Issue by DandiAndy** [xamarin/Xamarin.Forms#14673]
### Description

With the recent release of iPadOS/iOS there is an issue that causes strange behaviour in the Xamarin Forms implementation of the TimePicker.

In iOS/iPadOS 15, tapping on the time of a UIDatePicker styled as a wheel allows you to edit the value with a numeric keyboard. This feature breaks down when adding the the UIDatePicker to the InputView of a UITextfield (as Xamarin Forms does). Tapping the time reveals the wrong keyboard and squishes it into the space that would be available for a numeric keyboard.

**Note this is not an issue specifically with Xamarin Forms and can be created by adding a UIDatePicker to the InputView of a UITextField.**

**Note that this cannot be produced in the simulator. Must be a physical iPad.**

### Steps to Reproduce

1. Create a Xamarin Forms Project with a TimePicker in it.
2. Run the project on a physical iPad device updated with iOS/iPadOS 15.
3. Tap the TimePicker.
4. Tap the time in the InputView wheel.

### Expected Behavior

Numeric Keyboard pops up.

### Actual Behavior

Squished full keyboard pops up.

### Basic Information

- Version with issue: Latest
- Platform Target Frameworks: 
  - iOS:  15
- Affected Devices: iPad

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.9 (build 3)
Installation UUID: 01412eec-76f3-4e52-8623-70136f15f3c8
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.201
	3.1.200
	3.0.100
	2.1.701
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.3
	3.1.2
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.17
	2.1.16
	2.1.12

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Enterprise)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/andrewkenny/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/andrewkenny/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:43:52 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-08-12 20:44:10 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Enterprise)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810090003
Git revision: 156eb53c9c668cb7ff4311ae3d1dab894549848b
Build date: 2021-09-08 07:26:54-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.5.0 Darwin Kernel Version 20.5.0
    Sat May  8 05:10:33 PDT 2021
    root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
```

</details>

### Screenshots

**With Xamarin Forms:**
<img width="593" alt="Screen Shot 2021-09-27 at 4 21 36 PM" src="https://user-images.githubusercontent.com/6966412/135310674-38762c16-bdbd-4f09-8d48-aaacb1652002.png">

**With native swift project:**
<img width="592" alt="Screen Shot 2021-09-27 at 4 20 58 PM" src="https://user-images.githubusercontent.com/6966412/135310787-fa4e13d5-641c-4fdb-8d7a-14719e800325.png">

### Workaround

Create a custom renderer with the following:

```cs
[assembly: ExportRenderer(typeof(CustomTimePicker), typeof(CustomTimePickerRenderer))]
namespace iPad15TimePickerFix.iOS.Renderers
{
    public class CustomTimePickerRenderer : DatePickerRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
        {
            base.OnElementChanged(e);

            if (Control == null)
            {
                return;
            }

            if (e.OldElement != null)
            {
                if (UIDevice.CurrentDevice.CheckSystemVersion(15, 0))
                {
                    (Control.InputView as UIDatePicker).EditingDidBegin -= UIDatePicker_EditingDidBegin;
                }
            }

            (Control.InputView as UIDatePicker).EditingDidBegin += UIDatePicker_EditingDidBegin; ;
        }

        private void UIDatePicker_EditingDidBegin(object sender, System.EventArgs e)
        {
            (Control.InputView as UIDatePicker).ResignFirstResponder();
        }
    }
}
```

**Comment by jsuarezruiz** [comment]
@jfversluis Could you try the TimePicker in an iPad with iOS 15?

**Comment by jfversluis** [comment]
If I understand correctly this only happens on a physical device? I don't have one :( 

Will try with the Simulator now

**Comment by DandiAndy** [comment]
@jfversluis, It doesn't appear to work with the simulator. I couldn't recreate it at least. Seems to only work with physical devices.

**Comment by jfversluis** [comment]
This is what you mean, right? You have to enable the softkeyboard with CMD + K in the Simulator for it to show up :)

![image](https://user-images.githubusercontent.com/939291/135856111-8bf57e52-b352-4fdf-9682-8ec22dfbb83d.png)

**Comment by jfversluis** [comment]
@DandiAndy, a PR for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

I've blocked the popping up of the keyboard right now as inspired by your custom renderer (thanks for that!).

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by DandiAndy** [comment]
@jfversluis, what you should see is a numeric keypad that allows you to input the time manually rather than spinning the wheels. If you were to pull the UIDatePicker out of the UITextField.InputView and just have it inline you would see a numeric keyboard popup instead of that weird squished up keyboard.

As for your fix, I'll take a look and I'll get back to you soon. Thanks!

**Comment by jfversluis** [comment]
Aah gotcha! Yeah, I think we never had real support for the new way of showing pickers and we stuck to the wheels approach. So I think in line of that blocking this is the right thing to do for now. Thanks!

**Comment by DandiAndy** [comment]
@jfversluis, I gave this a go and it's fixed in the latest PR feed version. I tried to find some side effects, but it looks stable. Thanks for your help!

It might already be on the radar, but iOS 15 introduced [compact UIDatePickers](https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/) that works/looks much like the Xamarin Forms implementation without the need for that extra step of adding a UITextField. Might be good to move to that as a solution for the DatePicker/TimePicker for Xamarin Forms/Maui eventually. Going to add a spec and I'll link it here after.

(P.S. Love your YouTube channel. You're my source for Maui news.)

**Comment by jfversluis** [comment]
Awesome, thanks for letting me know!

I am definitely aware, thank you though :) but that will be something for .NET MAUI for sure. We're not going to add behavior changes for Forms. So make sure you open the spec on .NET MAUI, that will be greatly appreciated!

> (P.S. Love your YouTube channel. You're my source for Maui news.)

Love it! Thank you for the support! <3
