### ISSUE TITLE
TestFlight Only Crash DYLD Library not loaded

### ISSUE THREAD

**Issue by cklenk** [xamarin/Xamarin.Forms#1468]
### Description
I have seen many other posts about this issue. I have tried all of the solutions I believe that I have seen in other posts. I am running Xamarin.Forms 2.3.4.247 and am using HockeyApp 5.1.1 for crash reporting.  The application launches just fine when I'm in debug mode and deploy it to a device or simulator. 

Here is a link to my log: [Error](https://gist.github.com/cklenk/04074610ba5c6b024731a1b3f5f6ac41)
### Steps to Reproduce

1. Clean and build solution in AppStore
2. Upload .ipa to TestFlight through Application Loader
3. Download app through TestFlight

### Expected Behavior
No crash like when deploy through debug config
### Actual Behavior
App crashes on splash screen
### Basic Information

- Version with issue: 2.3.4.247
- Last known good version: 2.3.4.247
- IDE: Visual Studio Professional 2017 15.5.2
- Platform Target Frameworks: 
  - iOS: 11.2.1
- Nuget Packages:
CarouselView.FormsPlugin            {4.4.3}                                 
HockeySDK.Xamarin                   {5.1.1}                                  
Microsoft.AspNet.WebApi.Client      {5.2.3}                                  
Microsoft.Bcl                       {1.1.10}                                 
Microsoft.Bcl.Build                 {1.0.21}                                                                                                                       
Microsoft.Net.Http                  {2.2.29}                                 
Microsoft.VisualStudio.SlowCheetah  {3.0.61}                                                                                                                       
modernhttpclient                    {2.4.2}                                  
Newtonsoft.Json                     {10.0.3}                                 
PCLCrypto                           {2.0.147}                                
Plugin.InAppBilling                 {1.2.3.107}                              
Validation                          {2.4.18}                                                                                                                       
Xam.FormsPlugin.Iconize             {1.0.10}                                                                                                                       
Xam.Plugin.Connectivity             {3.0.3}                                                                                                                        
Xam.Plugin.DeviceInfo               {3.1.0.55-beta}                          
Xam.Plugin.Iconize                  {1.0.10}                                 
Xamarin.Auth                        {1.5.0.3}                                                                                                                      
Xamarin.Forms                       {2.3.4.247}                              
- Affected Devices: iPhone 6

**Comment by cklenk** [comment]
Ended up fixing it by deleting the Apple Worldwide Developer Certificates and re-installing them.

**Comment by beaubutton** [comment]
@cklenk Can you elaborate on what the solution was?
