### ISSUE TITLE
[Bug] credit card auto fill doesn't work in WebView on iOS

### ISSUE THREAD

**Issue by iane87** [xamarin/Xamarin.Forms#14688]
### Description
credit card auto fill doesn't work in WebView on iOS
### Steps to Reproduce

1. Save credit card in safari
2.  Visit website inside WebView that accepts credit card payment
3. Auto fill options not there but they are if site is opened directly in safari

### Expected Behavior
Able to auto fill credit card
### Actual Behavior
Unable
### Basic Information

- Version with issue: 5.0.0.2083
- Last known good version:
- Platform Target Frameworks: .net standard 2.0
  - iOS:  14.1
  -
- Android Support Library / AndroidX Version: credit card auto fill works great on Android 10
- Affected Devices: iPhone

### Reproduction Link
Https://Armedrides.com/pay.html
### Workaround
Only workaround so far would be to open payment page in browser instead of WebView which is not an ideal user experience.

**Comment by jfversluis** [comment]
Looks like this is not possible on a platform level, going to close this for now!
