### ISSUE TITLE
[Bug][Android] Shape no longer redrawing itself when the container changes size (sr4 and sr5)

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#14697]
### Description
Up to XF5 sr3, drawing a path with `Aspect="Uniform"` in a container, and then changing the dimensions of said container would make the path redraw itself to fill the available space.
This behavior no longer works on Android devices in both sr4 and sr5, creating all sorts of issues with the ui no longer adapting to changes in sizes.

The change might have been caused by this PR [[Android] Fixed memory leak applying brushes to shapes](https://github.com/xamarin/Xamarin.Forms/pull/12653)

### Steps to Reproduce

1. Add content like the following to a ContentPage.
2. launch the app, get to that page. 
3. Rotate the device.

``` 
<StackLayout>
        <Frame
            Padding="24"
            BackgroundColor="#2196F3"
            CornerRadius="0">
            <Label
                FontSize="36"
                HorizontalTextAlignment="Center"
                Text="Welcome to Xamarin.Forms!"
                TextColor="White" />
        </Frame>
        <Path
            Aspect="Uniform"
            BackgroundColor="Orange"
            HeightRequest="300"
            HorizontalOptions="Fill"
            Stroke="Black"
            VerticalOptions="Fill">
            <Path.Data>
                <PathGeometry>
                    <PathGeometry.Figures>
                        <PathFigureCollection>
                            <PathFigure IsClosed="True" StartPoint="10,100">
                                <PathFigure.Segments>
                                    <PathSegmentCollection>
                                        <LineSegment Point="100,100" />
                                        <LineSegment Point="20,90" />
                                    </PathSegmentCollection>
                                </PathFigure.Segments>
                            </PathFigure>
                        </PathFigureCollection>
                    </PathGeometry.Figures>
                </PathGeometry>
            </Path.Data>
        </Path>
    </StackLayout>
```

### Expected Behavior
The Path will be resized to fill the available space.

### Actual Behavior
The Path is not resized.

### Basic Information

- Version with issue: XF5 sr5 (2125)
- Last known good version: XF5 sr3 (2012)
- Platform Target Frameworks: 
  - Android: Target Android 11  

### Screenshots
starting position: 
![image](https://user-images.githubusercontent.com/31066938/136052045-25e56c3a-2a32-4870-a87a-55df3c614b65.png)

![image](https://user-images.githubusercontent.com/31066938/136052119-d4192825-1f59-4da7-8935-cf5d326dfa3a.png)

![image](https://user-images.githubusercontent.com/31066938/136052181-74ac581e-89f2-4944-aa01-03d1b07ea36f.png)

![image](https://user-images.githubusercontent.com/31066938/136052215-0c194d86-0b11-4f49-93fb-c540185f3898.png)

### Reproduction Link
No need to share a complex project, just use the example content shown above.

### Workaround
Not yet identified.

**Comment by MitchBomcanhao** [comment]
just for reference, here are the PathFigure objects for each triangle used on my example

```
        PathFigure pathFigure1 = new PathFigure 
        { 
            IsClosed = true,
            StartPoint = new Point { X = 10, Y = 100 },
            Segments = new PathSegmentCollection { 
                new LineSegment { Point = new Point { X = 100, Y = 100 } },
                new LineSegment { Point = new Point { X = 20, Y = 90 } },
            } 
        };

        PathFigure pathFigure2 = new PathFigure
        {
            IsClosed = true,
            StartPoint = new Point { X = 60, Y = 80 },
            Segments = new PathSegmentCollection {
                new LineSegment { Point = new Point { X = 115, Y = 70 } },
                new LineSegment { Point = new Point { X = 120, Y = 80 } },
            }
        };
```

**Comment by ackava** [comment]
For anyone having same issue, here is the work around, Keep the top level shape inside a ContentView and recreate shape and add it to Content of ContentView. This will recreate the shape with size.
