### ISSUE TITLE
Xamarin IOS Missing App Icon back again

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Xamarin.Forms#14704]
### Description
When uploading the IPA to Transporter on the MAC Build Server an error occurs stating that the App Icon is missing
### Steps to Reproduce
1. Create Xamarin IOS App
2. Add a asset catalog for your images and add the properly sized images
3. Connect to a MAC for a build server
4. Connect to an actual IOS phone via the MAC
5. Push the IPA file to the MAC
6. Upload the file to Transporter
7. Click Verify

### Expected Behavior
The app should upload with no issues
### Actual Behavior
I get an error from transporter stating:  ERROR-ITMS-90704: "Missing App Icon.  An app icon measuring 1024 by 1024 pixels in PNG format must be included in the Asset Catalog of apps built for iOS, iPadOS, watchOS.  Without this icon, apps cannot be submitted for review.

I am not sure what happened, this was working two months ago.   Since I have upgraded Xamarin, Visual Studio, and XCode.  
### Basic Information
1. Visual Studio - Microsoft Visual Studio Professional 2019 Version 16.11.4
2. Xamarin Forms - 5.0.0.2125
3. IOS Deployment Target 9.0
4. XCODE Version 13.0
5. Transporter Version 1.2.2

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Workaround

<!-- Did you find any workaround for this issue? This can unblock other people while waiting for this issue to be resolved --
![Config](https://user-images.githubusercontent.com/62118624/136268332-9d0cc2b3-6173-47fe-b78a-d0a3183ac56a.PNG)
![Capture](https://user-images.githubusercontent.com/62118624/136268362-4f21f37e-dd90-4e16-8d72-6f1d73bf7d5a.PNG)
>

**Comment by jfversluis** [comment]
This is not a problem in Xamarin.Forms but with Xamarin.iOS and/or Visual Studio. That is not our area or anything we can fix. I see you also already commented on the other issue in the mac-ios repo, please follow up there.

**Comment by sisaacks** [comment]
@jfversluis is there a way I could contact you....I have a couple questions.....I Dont have any other developers to ask and I need and expert before I completely throw away the Xamarin app and go to swift

**Comment by jfversluis** [comment]
You should be able to find my email on my GitHub profile!
