### ISSUE TITLE
Shell BackgroundColor and TabBarBackgroundColor do not update on iOS 15[Bug] 

### ISSUE THREAD

**Issue by Paul2795** [xamarin/Xamarin.Forms#14706]
### Description
See this link: https://issueexplorer.com/issue/xamarin/Xamarin.Forms/14645

I have the same problem.

After upgrading to iOS 15, applications using the Shell.BackgroundColorProperty or Shell.TabBarBackgroundColorProperty and maybe others will stop working due to changes made to the Appearance class in iOS. More details can be found here: https://developer.apple.com/forums/thread/682420.

### Steps to Reproduce

   1. Start app with an iOS 15 device or simulator
   2. Gaze upon the unstyled nav bar and tab bar

### Expected Behavior
Nav bar and tab bar should be styled
### Actual Behavior
Both the styling value should be carried over
### Basic Information

    Version with issue:
    Last known good version: iOS 14.5
    Platform Target Frameworks:
        iOS: 15+
    NuGet Packages: Xamarin.Forms
    Affected Devices: iOS

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

How it should work correctly:
https://user-images.githubusercontent.com/120685/134422750-6f6fefdf-b91f-4383-8697-0dee95970164.png

How this appear with IOS 15
https://user-images.githubusercontent.com/120685/134422755-c155766c-5d20-4099-9f2e-fc0a660e796d.png

### Reproduction Link

https://github.com/xamarin/Xamarin.Forms/files/7213851/ShellsBustedInIos15.zip

### Workaround

It looks like there could be a way to fix this using UINavigationBar.Appearance, but we will need access to the iOS 15 SDK in order to attempt that.

**Comment by jsuarezruiz** [comment]
A new Service Release will be available next week.
