### ISSUE TITLE
the "linkassemblies" task failed for Android Xamarin Forms

### ISSUE THREAD

**Issue by ExzaSolutions** [xamarin/Xamarin.Forms#1471]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

When the Xamarin Forms Project builds the Android build fails.
The android is set to build to Release,and the linking is set to Sdk Assemblies only.
When it is set to None it builds successfully,but the apk is far too big then.

### Steps to Reproduce

1. Add Nuget Packages to Xamarin Forms Solution
2. Set Android Project To Release and linking to Sdk Assemblies only.
3. Build Solution

### Expected Behavior
Should build successfully

### Actual Behavior
Fails with "LinkAssemblies" task failed unexpectedly. System.NullReferenceException: Object reference not set

### Basic Information
Microsoft Visual Studio Community 2017 
Version 15.5.2
VisualStudio.15.Release/15.5.2+27130.2010
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA801
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA801
Microsoft Visual C# 2017

Visual F# 4.1   00369-60000-00001-AA801
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31125.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.20601.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Azure Data Lake Tools for Visual Studio   2.2.9000.1
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure HDInsight Azure Node   2.2.9000.1
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.2.9000.1
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   1.8
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.2.9000.1
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.8.4-pre (3fe64e3)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WebJobs Tools v1.0.0   15.0.31106.0
WebJobs Tools v1.0.0

Xamarin   4.8.0.753 (6575bd113)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.8.188 (c5813fa34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.1.0.25 (HEAD/d8c6e504f)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.6.1.2 (6857dfc)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- IDE: MS VS Community 2017
- Platform Target Frameworks: 
  - Android: 8.0
- Nuget Packages:
<packages>
  <package id="Acr.Support" version="2.1.0" targetFramework="monoandroid60" />
  <package id="Acr.UserDialogs" version="6.5.1" targetFramework="monoandroid80" />
  <package id="AndHUD" version="1.2.0" targetFramework="monoandroid60" />
  <package id="CarouselView.FormsPlugin" version="5.0.2" targetFramework="monoandroid80" />
  <package id="DLToolkit.Forms.Controls.FlowListView" version="2.0.10" targetFramework="monoandroid80" />
  <package id="DLToolkit.Forms.Controls.TagEntryView" version="1.0.4" targetFramework="monoandroid60" />
  <package id="ExifLib.PCL" version="1.0.1" targetFramework="monoandroid60" />
  <package id="FastAndroidCamera" version="2.0.0" targetFramework="monoandroid60" />
  <package id="HockeySDK.Xamarin" version="5.1.1" targetFramework="monoandroid80" />
  <package id="Microsoft.AppCenter" version="1.1.0" targetFramework="monoandroid80" />
  <package id="Microsoft.AppCenter.Analytics" version="1.1.0" targetFramework="monoandroid80" />
  <package id="Microsoft.AppCenter.Crashes" version="1.1.0" targetFramework="monoandroid80" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="monoandroid80" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="monoandroid80" />
  <package id="Microsoft.CSharp" version="4.4.1" targetFramework="monoandroid80" />
  <package id="Microsoft.NETCore.Platforms" version="2.0.1" targetFramework="monoandroid80" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="NETStandard.Library" version="2.0.1" targetFramework="monoandroid80" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="monoandroid80" />
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid60" />
  <package id="Plugin.Permissions" version="2.1.0" targetFramework="monoandroid80" />
  <package id="Plugin.Share" version="7.1.1" targetFramework="monoandroid80" />
  <package id="Rg.Plugins.Popup" version="1.0.4" targetFramework="monoandroid80" />
  <package id="Splat" version="2.0.0" targetFramework="monoandroid80" />
  <package id="sqlite-net-pcl" version="1.4.118" targetFramework="monoandroid80" />
  <package id="SQLitePCLRaw.bundle_green" version="1.1.9" targetFramework="monoandroid80" />
  <package id="SQLitePCLRaw.core" version="1.1.9" targetFramework="monoandroid80" />
  <package id="SQLitePCLRaw.lib.e_sqlite3.android" version="1.1.9" targetFramework="monoandroid80" />
  <package id="SQLitePCLRaw.provider.e_sqlite3.android" version="1.1.9" targetFramework="monoandroid80" />
  <package id="System.AppContext" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Collections" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ComponentModel.TypeConverter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Console" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Globalization" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Net.Http" version="4.3.3" targetFramework="monoandroid80" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Formatters" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Runtime.Serialization.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="System.Xml.XmlDocument" version="4.3.0" targetFramework="monoandroid80" />
  <package id="Xam.Plugin.Badge" version="1.0.0.0" targetFramework="monoandroid60" />
  <package id="Xam.Plugin.Contacts" version="2.2.0.37-beta" targetFramework="monoandroid60" />
  <package id="Xam.Plugin.Geolocator" version="4.1.3" targetFramework="monoandroid80" />
  <package id="Xam.Plugin.Media" version="3.1.1" targetFramework="monoandroid80" />
  <package id="Xam.Plugin.PushNotification" version="1.2.4" targetFramework="monoandroid60" developmentDependency="true" />
  <package id="Xamarin.Android.Arch.Core.Common" version="26.1.0-beta1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Arch.Lifecycle.Common" version="26.1.0-beta1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Arch.Lifecycle.Runtime" version="26.1.0-beta1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Annotations" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Compat" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.UI" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Core.Utils" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.CustomTabs" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Design" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Fragment" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Media.Compat" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Transition" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v4" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.CardView" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.Palette" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.v7.RecyclerView" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="26.1.0.1" targetFramework="monoandroid80" />
  <package id="Xamarin.Build.Download" version="0.4.7" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms" version="2.5.0.121934" targetFramework="monoandroid80" />
  <package id="Xamarin.Forms.Maps" version="2.5.0.121934" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Base" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Basement" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Gcm" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Iid" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Maps" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="Xamarin.GooglePlayServices.Tasks" version="60.1142.0" targetFramework="monoandroid80" />
  <package id="XLabs.Core" version="2.0.5782" targetFramework="monoandroid80" />
  <package id="XLabs.Forms" version="2.0.5782" targetFramework="monoandroid80" />
  <package id="XLabs.IoC" version="2.0.5782" targetFramework="monoandroid80" />
  <package id="XLabs.Platform" version="2.0.5782" targetFramework="monoandroid80" />
  <package id="XLabs.Serialization" version="2.0.5782" targetFramework="monoandroid80" />
  <package id="ZXing.Net.Mobile" version="2.3.2" targetFramework="monoandroid80" />
  <package id="ZXing.Net.Mobile.Forms" version="2.3.2" targetFramework="monoandroid80" />
</packages>
- Affected Devices:

**Comment by samhouts** [comment]
When you say "Add Nuget Packages to Xamarin Forms Solution", which nuget packages are you referring to? Can you reproduce this with a brand new Xamarin.Forms solution, or does it only seem to happen to your project? Thanks

**Comment by latsson** [comment]
Is not this a bug in visual studio that has been fixed? Can't find the bug report right now though.

**Comment by PureWeen** [comment]
This might be a bug with the Android linker

I've seen it come up when you have nugets that still include PCL libraries  or pre-netstandard 2.0 libraries and you add them into  a netstandard 2.0 projects. I'm still running up against this issue with the Azure IoT libraries

https://github.com/Azure/azure-iot-sdk-csharp/issues/197

I fixed it their by just recompiling them against NetStandard 2.0

I've also noticed this error only comes up if you set it to link both user and full assemblies.

**Comment by ExzaSolutions** [comment]
Hi,our appsize was 107mb on Android.
While our competitions size was less than 15mb.
We use progaurd and linking against sdk assemblies and got it down to 42MB +-.
Then the error started to popup.
It took  a week to figure this out and fix it.
I found this very counter productive,especially when you have deadlines.
In the end it was a good learning curve, that is till the next surprise.
We still need to link to the user assemblies to see if we can get the app size still smaller.

Thank you for commenting on this topic I appreciate it very much!
Started to think there is no support for Xamain Forms.

**Comment by PureWeen** [comment]
@ExzaSolutions  have you tried with the latest Visual Studio? I've noticed in my case the latest updates seem to give a better exception than NRE and indicate exactly what it's unable to link

**Comment by ExzaSolutions** [comment]
Hi,thank you,I will give it a try.That will help a lot.

**Comment by jassmith** [comment]
I am migrating this over to the android team :)
