### ISSUE TITLE
macOS 10.15/macOS 12 Monterey (Beta 9) Button Background Color Issue (Xamarin.Forms version 4.8.0.1534 and 5.0.0.2125)

### ISSUE THREAD

**Issue by tn-17** [xamarin/Xamarin.Forms#14724]
### Steps to Reproduce

**Issue 1**
1. Build a mac app using xamarin.forms version 4.8.0.1534 that has a button with a blue background color
2. Copy app to a macOS 12 Monterey Beta 9 VM
3. Launch app

**Issue 2**
1. Build a mac app using xamarin.forms version 5.0.0.2125 that has a button with a blue background color
2. Copy app to a macOS 10.15 Catalina VM and a macOS 12 Monterey Beta 9 VM
3. Launch app

### Expected Behavior

Correct appearance of the implemented button (xamarin.forms version 4.8.0.1534 on macOS 10.15 Catalina VM)

The button retains the blue background color for the button when the app is in and out of focus

![macOS10 15_v4 8 0 1534_working](https://user-images.githubusercontent.com/59483688/137014638-3d876bfe-8f66-44fb-9e79-51d29403bb2d.png)

### Actual Behavior

**Issue 1**
Xamarin.Forms version 4.8.0.1534 & macOS 12 Monterey Beta 9 VM
App in focus has proper appearance with the blue color button but changes to a grey color when the app is out of focus (clicking out of the app window)

![macOS12B9_v4 8 0 1534_not-focus_broken](https://user-images.githubusercontent.com/59483688/137014799-a0e7831b-86ea-4702-b87d-8cdbfa99c814.png)

**Issue 2**
Xamarin.Forms version 5.0.0.2125 & macOS 10.15 Catalina VM

![macOS10 15_v5 0 0 2125_broken](https://user-images.githubusercontent.com/59483688/137015115-ed9a5d06-dd05-414f-b8d9-f5ad9c2debbc.png)

Xamarin.Forms version 5.0.0.2125 & macOS 12 Monterey Beta 9 VM

![macOS12B9_v5 0 0_in-focus_broken](https://user-images.githubusercontent.com/59483688/137015150-6f6aa264-e85b-4adb-ab42-92783844a90b.png)

In the two images above, look closely and you can barely see the words "Sign In". The background color of the button has changed to a white color for when the app is both in and out of focus

### Environment

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.10 (build 8)
Installation UUID: 76317fdd-7a74-4e0f-b624-545f20c0719b
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	3.1.413
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	3.1.19

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Not Installed

=== Microsoft OpenJDK for Mobile ===

Java SDK: Not Found

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Community)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810100008
Git revision: a3ff4b6e658e1f94623e1f3ed34ca94ed4fe78d8
Build date: 2021-09-23 19:50:51-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Thu Sep 30 06:41:59 PDT 2021
    root:xnu-8019.40.96.0.2~12/RELEASE_X86_64 x86_64
```

Above snippet says that the OS is mac OS X 10.16.0 strangely even though this is from visual studio community mac running on a macOS 12 Monterey Beta 9 VM

### Build Logs

Built using azure devops pipeline, I am not sure if the logs from there is applicable. However, the build for xamarin.forms 4.8.0.1534 functions correctly on macOS 10.15 meanwhile the other cases do not with the only changes being the macOS version and/or the xamarin.forms version

### Example Project (If Possible)

I am not allowed to attach this app but am able to provide some redacted code of the button if needed (?)

**Comment by tnguyenseo** [comment]
I found the issue while copying files/code needed to recreate a separate app with just the button. 

Turns out, the button was set to white for macOS. This explains the behavior with xamarin.forms 5.0.0.2125. However, it appears that xamarin.forms 4.8.0.1534 did not make use of this code block since the button kept its blue background which could be another bug on its own (?)

```
<!-- Button colors -->
<Color x:Key="DefaultButtonTextColor">White</Color>
<OnPlatform x:Key="ButtonBackgroundColor" x:TypeArguments="Color" Default="#2672FB"> // correct blue color
	<On Platform="macOS" Value="#F9F9F9"/> // white color
</OnPlatform>
```

custom button properties with the only relevant thing being the background color I suppose,
```
<Style TargetType="Button" x:Key="DefaultButtonStyle">
	<Setter Property="HorizontalOptions" Value="Center" />
	<Setter Property="VerticalOptions" Value="CenterAndExpand" />
	<Setter Property="BorderColor" Value="{DynamicResource ButtonBackgroundColor}"/>
	<Setter Property="BackgroundColor" Value="{DynamicResource ButtonBackgroundColor}"/>
	<Setter Property="BorderRadius" Value="{OnPlatform WPF=4, iOS=0}" />
	<Setter Property="BorderWidth" Value="{OnPlatform WPF=0, iOS=0}" />
	<Setter Property="WidthRequest" Value="200" />
	<Setter Property="HeightRequest" Value="{OnPlatform WPF=26, Default=36}"/>
	<Setter Property="CornerRadius" Value="4"/>
	<Setter Property="TextColor" Value="{DynamicResource DefaultButtonTextColor}"/>
	<Setter Property="Margin" Value="0"/>
	<Setter Property="Padding" Value="0" />
	<Style.Triggers>
		<Trigger TargetType="Button" Property="IsEnabled" Value="False">
			<Setter Property="TextColor" Value="{DynamicResource DisabledButtonTextColor}"/>
			<Setter Property="BackgroundColor" Value="{DynamicResource DisabledButtonBackgroundColor}" />
			<Setter Property="BorderColor" Value="{DynamicResource DisabledButtonBorderColor}" />
		</Trigger>
	</Style.Triggers>
</Style>
```
The style.triggers block might be the reason why the button color changes from blue to grey when out of focus on macOS 12 although I don't understand why this behavior does not occur on macOS 10.15 or 11.6 (just tested).

`DisabledButtonBackgroundColor` is the grey color shown when the app is out of focus on macOS 12 Beta 9

xamarin.forms 5.0.0.2125 seemed to enforce `<On Platform="macOS" Value="#F9F9F9"/> // white color` on macOS 10.15, macOS 11.6, and macOS 12 Beta 9 which resulted in the behavior mentioned in issue 2.

meanwhile xamarin.forms 4.8.0.1534 does not seem to enforce the platform specific color.

The issue with xamarin.form 4.8.0.1534 being weird doesn't matter now since the app is now using xamarin.forms 5.0.0.
