### ISSUE TITLE
[Bug] Xamarin.iOS versions mistmatch

### ISSUE THREAD

**Issue by Midnayt** [xamarin/Xamarin.Forms#14731]
### Description
I have the latest versions of VS 2019(Version 16.11.5) and VS for Mac(v 8.10.11). But when I try pait to Mac I receive an errror:

"The Xamarin.iOS SDK version installed on Max is not compatible with this version of Visual Studio. Would you like us to install Xamarin.iOS '15.0.0.8' for you? This will overwrite any existing Xamarin.iOS installation on your Mac."

**Comment by jfversluis** [comment]
Hey there! It seems you have somehow installed different versions of Xamarin.iOS. You should be able to just say: yes, install that version and it should be sorted :) 

If not, you probably want to check on this repo: https://github.com/xamarin/xamarin-macios or https://developercommunity.visualstudio.com/ and open an issue there if there isn't one already.
