### ISSUE TITLE
Invalid XAML renders in Preview, passes XAML compilation then fails to render at runtime

### ISSUE THREAD

**Issue by enusbaum** [xamarin/Xamarin.Forms#1473]
### Description
Ran into an issue where I had an errant character in my XAML which resulted in runtime issues. This took a while to troubleshoot because the XAML itself renders in preview and even passes compilation checks when XAML compilation is enabled. The resulting runtime experience is just a blank form with no exceptions being thrown.

I have only tested this on iOS, I do not know the experience on Android

### Steps to Reproduce
1. Place Invalid Character after ContentPage declaration in XAML file
The following example has an invalid character on line 3
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="Mobile.Example.InvalidXaml">
    >
    <ContentPage.Content>
        <StackLayout>
            <Label Text="Will not render at runtime" />
        </StackLayout>
	</ContentPage.Content>
</ContentPage>
```

### Expected Behavior

- XAML preview should replicate the same experience rendering the XAML as it does at runtime
- XAML compilation should throw an error

### Actual Behavior

XAML preview displays the form without issue, XAML passes compilation checks and runtime displays a blank form

### Basic Information

- Xamarin.Forms 2.5.0.121934
- IDE: Visual Studio for Mac Community 7.3.2 (build 12)
- Platform Target Frameworks: 
  - iOS: 11.2

#### Preview Screenshot: 
![Preview Screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1F2V2Y1X3K0X3k1Y0j12/Screen%20Shot%202017-12-27%20at%203.56.07%20PM.png)
#### Runtime Screenshot:
![Runtime Screenshot](https://d3vv6lp55qjaqc.cloudfront.net/items/1B1d3i1r160T0P1Q470o/Screen%20Shot%202017-12-27%20at%203.56.37%20PM.png)

**Comment by xamarindevelopervietnam** [comment]
i think you should set label textcolor @enusbaum

**Comment by StephaneDelcroix** [comment]
@enusbaum it is expected from the Previewer to do it's best to display faulty XAML, as, while you aren't done typing it, it is faulty.
But you're right, it could report the errors.

As for the compilation, I'm investigating why it doesn't fail.

**Comment by StephaneDelcroix** [comment]
Could you please attach a reproduction project, as I can't see any invalid character in the snippet. Thanks

**Comment by enusbaum** [comment]
Invalid Character is on line 3 of the above XAML example (">")

**Comment by StephaneDelcroix** [comment]
I was looking for some invalid hidden Unicode character

--
Stéphane Delcroix
+32 475 96 22 99

**Comment by enusbaum** [comment]
I was too when I ran into the issue. Again, this took embarrassingly longer than it should have to figure out what was going on ;)

**Comment by StephaneDelcroix** [comment]
unfortunately, this is valid `Xml`

**Comment by jassmith** [comment]
Closing based on stephanes latest comment
