### ISSUE TITLE
WKWebView missing send navigated event

### ISSUE THREAD

**Issue by 1nfinite** [xamarin/Xamarin.Forms#14737]
I am using Xamarin Form 5.0 with custom WKWebViewRenderer.

In Xamarin android. I can make use of sendNavigated event from WebViewRenderer.ElementController

I would expect this similar function is available in WKWebViewRenderer.
However, I am unable to find sendNavigated event on WKWebViewRenderer, WKWebView.
I would like to manually trigger a custom sendNavigated event. Is this not possible at the moment?

**Comment by jfversluis** [comment]
No response in a while. Closing this one.
