### ISSUE TITLE
[Bug] WebView needs extra settings for API 30 for locally read HTML files

### ISSUE THREAD

**Issue by clintonrocksmith** [xamarin/Xamarin.Forms#14744]
### Description
With Android API 30, extra steps are now required to allow the WebView to read local files on the device.  This is not required before API 29.
Here is a link that confirms the practice.
https://rrtutors.com/site/answer/ERR_ACCESS_DENIED-in-Android-Webview-with-sdk-30

and also..

https://developer.android.com/reference/android/webkit/WebSettings#setAllowFileAccess(boolean)

2 extra lines are needed in the Android Renderer..

Settings.AllowFileAccess = true;
Settings.AllowContentAccess = true;

### Steps to Reproduce

1. Open a project with a WebView and give it a local URL to a html file
2. NOTE: The build mode has to be in RELEASE and be signed.  It doesn't fail in Debug mode.

### Expected Behavior
It should open the html file

### Actual Behavior
The user is presented with an ERR_ACCESS_DENIED error

### Basic Information

- Platform Target Frameworks:
- Android: API 30 

### Workaround

Change Target Framework down to API 29 in Android build settings

**Comment by jfversluis** [comment]
Hey @clintonrocksmith, a PR (#14747) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by clintonrocksmith** [comment]
Hello @jfversluis and @jsuarezruiz 

Thanks for doing this.  Sorry it took me a while to figure out why it wasn't working on Xamarin.Forms but was working in my native web renderer.

![image](https://user-images.githubusercontent.com/140419/138195312-9bdb42f7-7171-40fb-b76a-e90f22217812.png)

I think the number isn't coming back as 30 even though my solution is targeting 30 in both the Manifest and the .csproj file.  I've triple checked.

Could that be correct?

Cheers

Clinton

**Comment by jfversluis** [comment]
Closing this for now assuming it's another issue :)
