### ISSUE TITLE
[Android] FormsApplicationActivity with singleton App no longer works 2.4 onwards

### ISSUE THREAD

**Issue by kentcb** [xamarin/Xamarin.Forms#1474]
### Description

Using a `FormsApplicationActivity` in conjunction with a singleton `App` instance no longer works correctly from 2.4 onwards. If the user hits the hardware back button, then returns to the app, a blank screen is shown instead of the current view.

### Steps to Reproduce

All this is listed in the attached repros, but I'll list it here for good measure:

1. Extend `FormsApplicationActivity` instead of `FormsAppCompatActivity`.
2. Make the `App` instance a static singleton.
3. Use XF 2.4 or higher.
4. After starting the app, hit the hardware back button.
5. Return to the app via the application icon.

The app will appear, but its main view will be empty.

### Expected Behavior

Should continue to work as it does in XF 2.3.

### Actual Behavior

Blank screen shown. According to my investigations, it seems like `OnAttachedToWindow` isn't being called.

### Basic Information

- Version with issue: 2.4 onwards
- Last known good version: `2.3.4.214-pre5` (I wanted to try very latest 2.3 but am unable due to poor Internet right now)
- IDE: VS 2017
- Platform Target Frameworks:
  - Android: `8.0`
- Android Support Library Version: `25.4.0.2`
- Affected Devices: observed on Pixel and Samsung devices

### Screenshots

After repro steps with XF 2.3 (works as expected):

![xf_2 3](https://user-images.githubusercontent.com/1901832/34397107-ba086c24-ebbe-11e7-9a89-4eb87e0b9ddb.png)

After repro steps with XF 2.5 (blank screen):

![xf_2 5](https://user-images.githubusercontent.com/1901832/34397109-be978ba8-ebbe-11e7-901a-999a38fd6892.png)

### Reproduction Link

[XF 2.3](https://github.com/xamarin/Xamarin.Forms/files/1590155/XFRepro_XF_2.3.zip)

[XF 2.5](https://github.com/xamarin/Xamarin.Forms/files/1590156/XFRepro_XF_2.5.zip)

**Comment by rmarinho** [comment]
this is fixed on 3.0.0 latest stable
