### ISSUE TITLE
[Bug] IOS Tab Bar is White is some IOS devices even when set to black

### ISSUE THREAD

**Issue by sisaacks** [xamarin/Xamarin.Forms#14755]
### Description
I have an xamarin shell flyout application.  One of our phones, I Phone 12 Mini the background is showing up white even though I have set it to black.  This only seems to be happening in the mini.  I have read online https://github.com/xamarin/xamarin-macios/issues/12778 that the issue seems to be XCode Related but the last entry made it seem that it was Xamarin related.  
### Steps to Reproduce

1.  Create an Xamarin Shell App
2.  Set the Resource Dictionary Style with the following: 
<Setter Property="Shell.BackgroundColor" Value="Black" />
<Setter Property="Shell.TabBarBackgroundColor" Value="Black" />
 <Setter Property="Shell.TabBarForegroundColor" Value="White"/>

### Expected Behavior
The tab bar should be black and the icons should be white

### Actual Behavior
the tab bar is white and the icons are white

### Basic Information
The tab bar seems to be be white on IOS 15, even when set to black with the style in the Shell Flyout Application.  
I found this online but not sure if this is the correct answer or not: https://stackoverflow.com/questions/69310028/uitabbarcontroller-bartintcolor-not-working-in-ios15/69402468#69402468

- Version with issue: IOS version 15
- Last known good version:  IOS version 14
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment
Windows Microsoft Visual Studio Professional 2019 Version 16.11.5
MAC Build Server Visual Studio 8.10.11
MAC Build Server XCode 13

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
What version of Xamarin.Forms are you using? The version that came out yesterday (2196) should fix this

**Comment by jfversluis** [comment]
Going to assume the linked PR indeed fixed this issue
