### ISSUE TITLE
[Bug] Custom namespace scheme not working

### ISSUE THREAD

**Issue by PaulAnderson02** [xamarin/Xamarin.Forms#14759]
### Description

Adding custom namespace schemas not working. It works when the source code is attached and using a library/assembly throwing error on compilation.

Namespace:
using Company.CustomLibrary;

public class CustomControl
{
}

Schema defined:
```csharp
[assembly: XmlnsDefinition("http://schemas.company.com/xamarin", "Company.CustomLibrary")]
```

xaml:
xmlns:company="http://schemas.company.com/xamarin"
Error:
1>MainPage.xaml(32,10): XamlC error XFC0000: Cannot resolve type "company.CustomControl".

**Comment by thomasgalliker** [comment]
It's ok. As long as it will be working as expected in .NET MAUI ;-)
