### ISSUE TITLE
UWP: No way to allow ListView to select first item by default 

### ISSUE THREAD

**Issue by owlstack** [xamarin/Xamarin.Forms#1476]
### Steps to Reproduce

Here's a SO post detailing the same behavior/issue with UWP: https://stackoverflow.com/questions/47373040/no-way-to-get-listview-to-show-initial-selected-item/47386238#47386238

### Expected Behavior

If I set the SelectedItem in my listview to index 0 item, then the item should be selected by default when the view first loads. 

### Actual Behavior

Currently, it does not appear selected even though it's set to be selected. 

### Basic Information

- Version with issue: 
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP: 10.0.14393.0
- Nuget Packages:
Xamarin.Forms: 2.4.0.282

- Affected Devices:
Panasonic FZ-E1

### Reproduction Link

https://stackoverflow.com/questions/47373040/no-way-to-get-listview-to-show-initial-selected-item/47386238#47386238

**Comment by pauldipietro** [comment]
Fixed by #1356.
