### ISSUE TITLE
[Bug] [Mac] GestureRecognizers.Clear() does not unsubscribe on Mac

### ISSUE THREAD

**Issue by kevcrooks** [xamarin/Xamarin.Forms#14769]
### Description

When adding a tap gesture recognizer and then calling `GestureRecognizers.Clear()` the action is still triggered later by a tap, as shown in the following code:
```
let tgr = TapGestureRecognizer()
tgr.Tapped.Add(fun _ -> doSomething())
myView.GestureRecognizers.Add tgr

// clearing the tap should stop doSomething() after this point, but that's not the case for Mac.
myView.GestureRecognizers.Clear()
```

Later, when tapping on `myView` the `doSomething()` event is still fired on MacOS (this doesn't seem to be a problem on other platforms), even though we have cleared the GestureRecognizers

Are we doing something wrong when trying to clear?

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2012

### Workaround
We handle unsubscribe logic inside `doSomething()` to stop the action being performed, after we want to clear the gesture recognizers. This means that even though `doSomething()` is still called, we can stop any action being taken.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
