### ISSUE TITLE
[Bug] [iOS] [Tablet devices] Tab Bar Icons XAML colors ignored 

### ISSUE THREAD

**Issue by simonemarra** [xamarin/Xamarin.Forms#14771]
### Description
I created a brand new project, using VS2019 for mac. The template I used is the Tabbed App.

All the code is the default one, exception for Xamarin.Forms and Xamarin.Essentials packages, updated to last stable releases at the time of writing the issue

### Steps to Reproduce

1. Create a new project using Tabbed App template
2. Update Xamarin.Forms package to 5.0.0.2196
3. Update Xamarin.Essentials to 1.7.0 (it should be optional and not related to the issue, but this is the way I tested the app)

### Expected Behavior

Tab bar icons should respect the AppShell.xaml code configuration, just like on iPhone simulator/devices 

### Actual Behavior

Tab bar icons ignore the xaml code, but ONLY ON TABLET DEVICES!

### Basic Information

- Version with issue: 5.0.0.2196
- Last known good version: did not tested yet, but this bug seems to be related to XCode13 (see also issue https://github.com/xamarin/Xamarin.Forms/issues/14505#issuecomment-947392572)
- Platform Target Frameworks:
  - iOS: iOS15 and Tablet Devices, XCode13
  - Android: not tested yet any Android tablet
  - UWP:  not tested
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: iOS Tablet devices, tested only iOS15.x devices

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.10 (build 8)
Installation UUID: 85bcc571-144c-488f-9142-d62389a2f4b2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.401/Sdks
SDK Versions:
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.300
	2.2.107
	2.1.505
	2.1.504
	2.1.302
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.5
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.9
	2.1.8
	2.1.2

=== .NET Core 3.1 SDK ===

SDK: 3.1.413

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/simonemarra/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.1
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/simonemarra/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Community)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810100008
Git revision: a3ff4b6e658e1f94623e1f3ed34ca94ed4fe78d8
Build date: 2021-09-23 19:50:51-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0
NuGet Package Management Extensions 0.27
Android Signature Tool 2.2.0
NuGet Package Explorer 0.6

```

</details>

### Screenshots

<img width="1678" alt="ios-tablet-tabbar-issue" src="https://user-images.githubusercontent.com/1699187/138238025-58f12c6d-b738-4283-b837-debc7c717b72.png">

**Comment by jfversluis** [comment]
Very interesting this only happens on tablets.  Thanks for the report!

**Comment by jfversluis** [comment]
I know why it happens! @simonemarra, a PR (#14775) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) (as soon as the build completes) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by jfversluis** [comment]
Thanks! Interesting... Wondering if this has to do with #14774 as well...
