### ISSUE TITLE
[Bug] RouteFactory only called once per root

### ISSUE THREAD

**Issue by trampster** [xamarin/Xamarin.Forms#14770]
### Description
It is not possible to create a RouteFactory for a non singleton view.

This is because GetOrCreate() on RouteFactory is only called the first time you navigate to a Route. This effectively makes all your views singletons. I'm using this to create a dialog which very much must not be a singleton and this currently seems to be impossible

### Basic Information

- Version with issue: 5.0.0.2012
- Platform Target Frameworks: 
  - Android: Android 10.0

**Comment by jfversluis** [comment]
It would be very helpful if you could add a little sample of what you're trying to do
