### ISSUE TITLE
NsRangeException while leaving content page containing custom entry with Xamarin Forms (v5.0.0.2196)

### ISSUE THREAD

**Issue by ashokkumar96** [xamarin/Xamarin.Forms#14788]
### Description
While rendering the custom entry and leaving the page containing custom entry throws the following exception. This issue is breaking in Xamarin Forms version (v 5.0.0.2196). 

![image](https://user-images.githubusercontent.com/49550346/138676318-98c8124d-d867-4d42-996a-3b695a1448e6.png)

### Steps to Reproduce

1. Run the attached sample
2. Click on the open entry button
3. And followed by click on the back button. Application will crashes with NsRangeException

### Expected Behavior
Application should not crashes with No exception

### Actual Behavior
Crashes with NsRangeException exception.

### Basic Information

- Version with issue:
- NuGet Packages: 
Same scenario, working fine with Xamarin Forms version (v 5.0.0.2125).
Affected version : Xamarin Forms version (v 5.0.0.2196)
.
- Affected Devices: Xamarin IOS platform with iPad 8th Gen 14.3 stimulator

### Environment
Microsoft Visual Studio Professional 2019
Version 16.7.7
VisualStudio.16.Release/16.7.7+30621.155
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019   00435-20310-61412-AA219
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Syncfusion Xamarin Project Templates   13.4.0.53
A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.

Syncfusion Xamarin Toolbox   16.2.0.19
Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.

SyncfusionMenu Extension   1.0
SyncfusionMenu Visual Studio Extension Detailed Info

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20514.1+600c0dadd199296df3ed07dfabdc014563a77f7c
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   16.0.30309.115
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.7.000.463 (d16-7@5209782)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.2.0 (d16-7/025fde9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   14.2.0.12 (e0ce49680)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots
![image](https://user-images.githubusercontent.com/49550346/138677350-6bc7c13a-e509-4acc-854e-b8106edda673.png)

### Reproduction Link

[PDFViewerApp (2).zip](https://github.com/xamarin/Xamarin.Forms/files/7409189/PDFViewerApp.2.zip)

### Workaround

No

**Comment by chainslunatic** [comment]
@jfversluis PR #14828 fixes this issue for us

**Comment by jfversluis** [comment]
Great! Thanks for letting me know!

**Comment by chainslunatic** [comment]
@jfversluis #14859 sadly seems to have broken this again in 5.0.0.2244

**Comment by jfversluis** [comment]
> @jfversluis #14859 sadly seems to have broken this again in 5.0.0.2244

Please don't do this in multiple places

**Comment by chainslunatic** [comment]
@jfversluis I removed the other comment because I accidently wrote it there, so no duplicate there.

My problem itself comes from the Syncfusion PDF component, they opened this Issue here, so I thought this would be the correct place to respond that it was broken in the revert that took place in #14859. But I'll inform them so they can open a new Issue based the reproduction from this one here.

**Comment by AshokKumarViswanathan** [comment]
Hi @jfversluis ,

With Latest NuGet of  Xamarin Forms, the issue still not resolved in our end. Kindly do the needful.

Regards, Ashok Kumar Viswanathan.

**Comment by jfversluis** [comment]
Correct, sorry about that. With the next one it will be resolved because I reverted the whole thing that caused this in the first place :)

**Comment by AshokKumarViswanathan** [comment]
@jfversluis Please re-open the issue.

**Comment by jfversluis** [comment]
Not needed, this is fixed with the next release

**Comment by ramkumarsync** [comment]
@jfversluis Is this issue resolved in the Xamarin.Forms 5.0.0.2244 version release? Because I couldn't see this issue listed in the release notes of the mentioned version. Please confirm this.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0-sr7

**Comment by jfversluis** [comment]
@ramkumarsync the next release I was talking about was SR8 :) Working to get that released this week or next
