### ISSUE TITLE
Xamarin forms listview OnScrollChanged

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14785]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-forms-listview-OnScrollChanged/1446196)._

---
I'm using XF 5.0.0.2012 to do a custom renderer for a ListView.
I can't get the  OnScrollChanged fired.
What is missing?

---
#### Feedback Bot on 6/10/2021, 00:59 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Alison Jin [MSFT] on 9/27/2021, 01:39 AM: 

<p>Thank you for your feedback! In order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? What is the actual result and which result do you expect to happen? It would be very helpful if you could provide a sample solution that has this problem.</p>
<p>We look forward to hearing from you!</p>

#### Feedback Bot on 10/12/2021, 07:26 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
No response to our question. Closing this for now.
