### ISSUE TITLE
Deleting bin/obj folder hang my visual studio

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#1478]
I have latest vs 2017  and when I delete bin/obj folder from visual studio the software hangs for 5-6 seconds on intel 7200u.

Anyone have any solution for this. When I do it from disk it's done very fast.  Is deleting bin/obj folder ok.

Thanks

**Comment by pauldipietro** [comment]
This is not a Forms-specific issue and will be closed. I would suggest filing a feedback report through VS itself regarding this behavior. A temporary suggestion would be to delete the .vs folder to see if that aids the situation at all.
