### ISSUE TITLE
Proposal: SetFieldVisitor.Visit should find a Property to set if the field is missing

### ISSUE THREAD

**Issue by Nukepayload2** [xamarin/Xamarin.Forms#1479]
## Summary
I want to develop Xamarin.Forms cross-platform apps with Visual Basic instead of C#, and I have implemented [a T4 template version of XamlG](https://github.com/Nukepayload2/XamarinFormsXamlVB) for VB, which will enable runtime Xaml support for VB. But XamlC can't generate `WithEvents` member initialization when `XamlCompilation` is `XamlCompilationOptions.Compile`, because named Xaml elements are fields in C#, but they are virtual properties
(`WithEvents` members) in Visual Basic. 

## API Changes

No API Changes.  All changes are inside of `public void Visit(ValueNode node, INode parentNode)`.

Replace
```C#
if (field == null)
	return;
Context.IL.Emit(OpCodes.Ldarg_0);
Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
Context.IL.Emit(OpCodes.Stfld, field);
```
With the following code:

```C#
if (field == null)
{
	var withEventsProperty = Context.Body.Method.DeclaringType.Properties.SingleOrDefault(fd => fd.Name == (string)node.Value);
	if (withEventsProperty != null)
	{
		Context.IL.Emit(OpCodes.Ldarg_0);
		Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
		Context.IL.Emit(OpCodes.Callvirt, withEventsProperty.SetMethod);
	}
}
else
{
	Context.IL.Emit(OpCodes.Ldarg_0);
	Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
	Context.IL.Emit(OpCodes.Stfld, field);
}
```

## Intended Use Case
This small change will make XamlC compatible with VB.Net . VB users will enjoy both the performance improvement of pre-compiled Xaml and the convenience of `WithEvents` members.

**Comment by StephaneDelcroix** [comment]
it looks like a small change, but the implication and risks are really high. I'd prefer not taking this in.

**Comment by Nukepayload2** [comment]
@StephaneDelcroix  I have come up with a safer idea. 

Add `public bool SetWithEventsMember {get; set;}` to `SetFieldVisitor` to opt-in `WithEvents` support, and enable this feature in [XamlCTask.TryCoreCompile()](https://github.com/xamarin/Xamarin.Forms/blob/836327b94c63c1b8fa4bf758284b3f2c46ce193c/Xamarin.Forms.Build.Tasks/XamlCTask.cs#L334) by replacing `new SetFieldVisitor(visitorContext)` with `new SetFieldVisitor(visitorContext) { SetWithEventsMember = true }`.

All changes are as follows:
1. In [SetFieldVisitor](https://github.com/xamarin/Xamarin.Forms/blob/f30aa8ae2c54172df237a80dfff7a6eb0c679195/Xamarin.Forms.Build.Tasks/SetFieldVisitor.cs)

Add
```c#
public bool SetWithEventsMember {get; set;}
```
Replace
```c#
if (field == null)
	return;
Context.IL.Emit(OpCodes.Ldarg_0);
Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
Context.IL.Emit(OpCodes.Stfld, field);
```
With 
```c#
if (field == null)
{
	if(!SetWithEventsMember)
		return;
	var withEventsProperty = Context.Body.Method.DeclaringType.Properties.SingleOrDefault(fd => fd.Name == (string)node.Value);
	if (withEventsProperty != null)
	{
		Context.IL.Emit(OpCodes.Ldarg_0);
		Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
		Context.IL.Emit(OpCodes.Callvirt, withEventsProperty.SetMethod);
	}
}
else
{
	Context.IL.Emit(OpCodes.Ldarg_0);
	Context.IL.Emit(OpCodes.Ldloc, Context.Variables[(IElementNode)parentNode]);
	Context.IL.Emit(OpCodes.Stfld, field);
}
```
2. In [XamlCTask.TryCoreCompile()](https://github.com/xamarin/Xamarin.Forms/blob/836327b94c63c1b8fa4bf758284b3f2c46ce193c/Xamarin.Forms.Build.Tasks/XamlCTask.cs#L334)

Replace 
```C#
rootnode.Accept(new SetFieldVisitor(visitorContext), null);
```
With
```C#
rootnode.Accept(new SetFieldVisitor(visitorContext) { SetWithEventsMember = true }, null);
```

**Comment by StephaneDelcroix** [comment]
After reflexion, supporting VB.Net for XF would take way more than this, and I prefer closing this for now as it's not part of our current priorities.
