### ISSUE TITLE
[Bug] Crash in iOS's EntryRenderer due to "NSRangeException Reason: Cannot remove an observer ... for the key path "sublayers" from <CALayer 0x600007b11e80> because it is not registered as an observer."

### ISSUE THREAD

**Issue by lee-m** [xamarin/Xamarin.Forms#14804]
### Description
The changes in PR #14526 added an observer to the ClearButton on an Entry to ensure correct tinting of the clear button which was released in SR6.

After updating to SR6 I'm seeing the following crash on iOS 12.5.5:

Name: NSRangeException Reason: Cannot remove an observer ... for the key path "sublayers" from <CALayer 0x600007b11e80> because it is not registered as an observer.

It happens on EntryRenderer Dispose call at this line:
ClearButton?.Layer?.RemoveObserver(this, new NSString("sublayers"));

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
Application should not crash.

### Actual Behavior
Crashes with the reported error.

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2196 (SR6)
- Platform Target Frameworks: 
  - iOS:  15
- NuGet Packages: Xamarin.Forms 5.0.0.2196 (SR6)
- Affected Devices: iPhone 6 running iOS 12.5.5

### Workaround

None as yet.

**Comment by jfversluis** [comment]
Thanks for the strack trace, I'd still like to have a repro if you can provide it though. From a first quick test I'm not able to reproduce it immediately.

**Comment by lee-m** [comment]
I'm still trying to reduce down our app to something that repro's the crash but it's proving a bit time-consuming trying to peel back several custom controls and effects that are all being used on the crashing page to pinpoint the exact cause.

**Comment by jfversluis** [comment]
Alright, thanks! :) 

I have dug into the code and might have a possible fix. I will put it in a PR in a little. If I could ask you to download the NuGet that results from that and test it for me that would be amazing!

**Comment by stavroaudisho** [comment]
I updated XF to 5.0.0.2196 and just experienced this issue (not sure if they are relevant). When will there be a fix?

**Comment by jfversluis** [comment]
Should be released early next week. Thanks!

**Comment by Alex-Dobrynin** [comment]
@jfversluis in v5.0.0.2244 keep crashing iOS 13.5, not fixed
![image](https://user-images.githubusercontent.com/23138430/142433436-d71db793-9626-409d-b0c0-f2fbed34e81e.png)

**Comment by jfversluis** [comment]
Correct, see #14887 please try the current nightly build

**Comment by aperel66** [comment]
Meanwhile, is there some sort of a workaround?
Like is there a method in the renderer that we can put a try/catch to extinguish this exception?

**Comment by jfversluis** [comment]
> Meanwhile, is there some sort of a workaround? Like is there a method in the renderer that we can put a try/catch to extinguish this exception?

Either downgrade or use the nightly version. I'm thinking of releasing the new version a bit earlier tbh. Running the tests now _maybe_ I can already do the update next week. Either way it would be great to know if the current nightly version fixes the problem for you @aperel66

**Comment by VitalyKnyazev** [comment]
> Meanwhile, is there some sort of a workaround? Like is there a method in the renderer that we can put a try/catch to extinguish this exception?

This works for me even in Release build.
Just try/catch still crashes in Release by some reason so simply not calling Dispose for older iOS.

protected override void Dispose(bool disposing)
{
	if(VersionCheck.IsiOS14OrNewer)
		base.Dispose(disposing);
}

**Comment by aperel66** [comment]
I would love to help you out. However, the crash is very intermittent. I only see it from Microsoft crash center as we have thousands of users. 

Sent from my iPhone
Alex

**Comment by aperel66** [comment]
Thank you!! Thats very helpful!!

Sent from my iPhone
Alex

**Comment by maxholtman** [comment]
I am also encountering this issue and the snippet @VitalyKnyazev posted above worked for me...my only question is - are there harmful side effects to passing this code? Not disposing of resources seems like a memory leak. Going to try looking into EntryRenderer's source code but I thought I might as well ask it here, too. @jfversluis

**Comment by bitshftr** [comment]
This issue seems to be "closed" as I write this on 02/24/2022.  What released version of Xamarin.Forms contains this fix?

**Comment by lee-m** [comment]
@bitshftr This was fixed in SR8

**Comment by bitshftr** [comment]
^ Does that equate to Xamarin.Forms Version 5.0.0.2291 ?

**Comment by rahou25** [comment]
this solves the issue as the error is unhandled.

protected override void Dispose(bool disposing)
        {
            try
            {
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }

put it here in the ios render extension class.
