### ISSUE TITLE
[Bug] FirebaseMessagingService.OnNewToken called before Xamarin.Forms.Forms.IsInitialized

### ISSUE THREAD

**Issue by Guervyl** [xamarin/Xamarin.Forms#14809]
### Description
In my main activity I have: 

            base.OnCreate(savedInstanceState);

            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            global::Xamarin.Forms.FormsMaterial.Init(this, savedInstanceState);
            Xamarin.Essentials.Platform.Init(this, savedInstanceState);

As you can see I called `Xamarin.Forms.Forms.Init` first. But when FirebaseMessagingService.OnNewToken get called when I install and run the app for the first time, `Xamarin.Forms.Forms.IsInitialized` is false. If I tied to access any Xamarin forms component from `OnNewToken` I will get an exception `Could not activate JNI Handle`.
### Steps to Reproduce

1. Create app with Firebase massaging.
2. Run the app for the first time on the phone so that firbase can call `OnNewToken`.
3. Check for `Xamarin.Forms.Forms.IsInitialized` in `OnNewToken` or try to access a dependency service.

### Expected Behavior
Xamarin.Forms.Forms.IsInitialized was supposed to be initialized.

### Basic Information

Xamarin.Essentials: 1.7.0
Xamarin.Firebase.Messaging: 122.0.0.1
Xamarin.Forms: 5.0.0.2125+747-sha.13cfd797c-azdo.5218324

**Comment by jfversluis** [comment]
Hey there, thanks for the report! If I understand correctly, you are trying to reference a Xamarin.Forms component at the time a token is retrieved from FCM for the first time. This probably happens as part of a service or the `Application` class which might happen before the Xamarin.Forms.Init call is made. I don't think there is much we can do about that. If you want to use the information from `OnNewToken` either save the data somewhere or put it in a object where you can retrieve it from later in your UI.

If you think this is not correct, please add a reproduction sample to this issue so I can see how your project it setup and take a closer look.

GOod luck!

**Comment by Guervyl** [comment]
Hi, What you said is correct about adding it to an object. I was trying to save it to a SQLite database. But as the SQLite database component is part of Xamarin Essentials and Xamarin forms, trying to call the dependency service failed.

**Comment by jonaslindholm** [comment]
FirebaseMessagingService:
> All methods ... _may_ be called when the app is in the background or not open.
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService
