### ISSUE TITLE
[Bug] Xamarin.Forms.Shell v5.0.0.2196 Backwards Navigation not working in iOS 15.0

### ISSUE THREAD

**Issue by DiogoSemedo** [xamarin/Xamarin.Forms#14805]
### Description
I'm having an issue when trying to navigate to the previous page with the default iOS back button using Xamarin.Forms.Shell. I will leave the link (https://github.com/DiogoSemedo/xamarin) to repository with a sample, and if you follow the "Steps to Reproduce" you will notice that in step 5 when you navigate to Page3 again, if you wish to navigate backwards you will need to hit back button twice. This makes me believe that pages are not being properly popped when you hit default back button on iOS.
### Steps to Reproduce

1. Run the app.
2. Click button to navigate to "MainPage".
3. Click button to navigate to "Page3".
4. Press back button.
5. Click button to navigate to "Page3".
6. Press back button.
7. Press back button.

### Expected Behavior
Trigger OnNavigated
Navigate to previous page
### Actual Behavior
OnNavigated not triggered
Doesn't navigate to previous page
### Basic Information

- Version with issue: 5.0.0.2196
- Last known good version: 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  15.0 
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: iPhone 13 Pro Max emulator

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.11 (build 8)
Installation UUID: 81b1e6f9-01b3-4826-ade3-587238ff94a2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Versão: 5.9.0.7134

=== SDK do .NET Core ===

SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
Versões do SDK:
	5.0.402
	5.0.401
	3.1.414
	3.1.413
SDKs do MSBuild: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== Runtime do .NET Core ===

Tempo de execução: /usr/local/share/dotnet/dotnet
Versões de Tempo de Execução:
	5.0.11
	5.0.10
	3.1.20
	3.1.19

=== SDK do .NET Core 3.1 ===

SDK: 3.1.414

=== Xamarin.Profiler ===

Versão: 1.6.15.68
Local: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Versão: 11

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Xamarin.Android ===

Versão: 11.3.0.4 (Visual Studio Community)
Confirmar: xamarin-android/d16-10/ae14caf
Android SDK: /Users/dsemedo/Library/Developer/Xamarin/android-sdk-macosx
	Versões Android com suporte:
		Nenhuma instalada

Versão das Ferramentas de SDK: 26.1.1
Versão das Ferramentas da Plataforma SDK: 30.0.4
Versão das Ferramentas de Build do SDK: 30.0.2

Informações do Build: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/dsemedo/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
O código EPL do Android Designer está disponível aqui:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Build Information ===

Release ID: 810110008
Git revision: 5467245e1f99a0c8ccdd2acea02d16c3fb65c220
Build date: 2021-10-07 10:49:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

XAML Styler 2.0.1


```

</details>

### Reproduction Link

https://github.com/DiogoSemedo/xamarin

### Workaround

I found a possible solution to solve this problem, you can customize the Shell BackButtonBehaviour and define a command with Shell.Current.Navigation.PopAsync() which will perform the pop correctly and trigger OnNavigated.

**Comment by jfversluis** [comment]
@DiogoSemedo, a PR (#14900) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by DiogoSemedo** [comment]
@jfversluis Hi, I tested the mentioned scenario in both platforms and the problem seems to be fixed. Thanks !

**Comment by de-preut** [comment]
@jsuarezruiz and @jfversluis I can also confirm, that with @DiogoSemedo test project and the PR version of Xamarin.Forms it's working, but not for modal pages.
Add to "Page3" a `Shell.PresentationMode="Modal"` and a back button and you have multiple "page3" on the modal stack!

**Comment by jfversluis** [comment]
@de-preut if you still think something is wrong please open a new issue, thanks :)

**Comment by de-preut** [comment]
@jfversluis sure thing, please see #https://github.com/xamarin/Xamarin.Forms/issues/14968 (basically a copy of this issue, with a linked sample project)
