### ISSUE TITLE
[iOS] _WebTryThreadLock error on WebView with TranslateTo

### ISSUE THREAD

**Issue by jvlppm** [xamarin/Xamarin.Forms#1480]
### Description

I am receiving a thread error on iOS when animating a WebView (with `TranslateTo`) inside a modal Page.

### Steps to Reproduce

1.  Open a page with `Navigation.PushModalAsync`
2. Inside this new Page, use `TranslateTo` on a WebView.

### Expected Behavior

WebView animates translation.

### Actual Behavior

App crashes, with the following error:

> bool _WebTryThreadLock(bool), 0x60400021ae80: Tried to obtain the web lock from a thread other than the main thread or the web thread. This may be a result of calling to UIKit from a secondary thread. Crashing now...

No stack trace is provided.

### Basic Information

- Version with issue: 2.5.0.12.19.34
- IDE: Visual Studio Community 7.3.2
- iOS: 11.6.1.2

### Reproduction Link

[ModalWebView.zip](https://github.com/xamarin/Xamarin.Forms/files/1594933/ModalWebView.zip)

**Comment by kingces95** [comment]
Reproduction exhibits stated actual behavior.

**Comment by AndreiMisiukevich** [comment]
Error appears if we TranslateTo(0, 100), but not if TranslateTo(100, 0). Looks unusually, because translateX and translateY handle with the same way.
I will leave PR, which fixes that issue (maybe it will help to identify reason faster), but it may be risky
