### ISSUE TITLE
[Bug] GetAbbreviatedDayName in Portuguese

### ISSUE THREAD

**Issue by orwo1** [xamarin/Xamarin.Forms#14810]
### Description
Calling (Some)CultureInfo.DateTimeFormat.GetAbbreviatedDayName((Any)DayOfWeek);
In Portuguese Portugal return the full name of that day,
in contrast with Portuguese Brazil, which works correcly.

### Expected Behavior
someCultureInfo.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday) will return "dom"
For Portuguese Portugal.
### Actual Behavior
someCultureInfo.DateTimeFormat.GetAbbreviatedDayName(DayOfWeek.Sunday) returns "domingo"
For Portuguese Portugal
### Basic Information

- Version with issue: 5.0.0.2012
- Platform Target Frameworks: 
  - iOS:  15.0
  - Android: 10.0

**Comment by jfversluis** [comment]
Thanks for the report! Have you tried this outside of a Xamarin app? It seems like this is more a .NET bug than a Xamarin bug :)

**Comment by orwo1** [comment]
Hi
I have not. It probably is...
It's just my current environment is mobile apps, and it is easier to test it on mobile
with how you switch languages there, either iPhone or some Android phone.

**Comment by jfversluis** [comment]
The culture for Portugal would be pt-PT, right?

And Brazil, pt-BR? But Portugal is the only one not working?

**Comment by jfversluis** [comment]
![image](https://user-images.githubusercontent.com/939291/139817487-38100473-ce57-498d-a10b-4d5234633b0d.png)

Yeah it would seem that this is something in the .NET framework and not so much in Xamarin :(

I think you would need to open an issue here: https://github.com/dotnet/runtime
