### ISSUE TITLE
[Bug] Changing textcolour of Tabbaritem not possible

### ISSUE THREAD

**Issue by Developer112021** [xamarin/Xamarin.Forms#14818]
### Description
Hey, 

we are working with Xamarin.forms - android and iOS. 
After the last update, the tabbaritem-textcolour changed for iOS and is unreadable now. 
We changed the colour with the following code in the appdelegate.cs: 

UITabBar.Appearance.TintColor = UIColor.White;
UITabBar.Appearance.UnselectedItemTintColor = UIColor.Black;

The selected item colour works fine, but the colour of the unselected item didn't changed.
What can we do instead?

Thanks in advance.

### Screenshots

![2021-11-02_02-50-44-](https://user-images.githubusercontent.com/93593936/139861333-98198b0b-ef27-4447-b734-15c44e7bff74.png)

![ios2](https://user-images.githubusercontent.com/93593936/139861389-a164671e-de07-4e29-88e3-51448aea11a7.PNG)

**Comment by jfversluis** [comment]
What version of Xamarin.Forms are you using? Please use the bug report template that we have in place so we can help you quicker. Thanks!

**Comment by Zoppa1** [comment]
I got the same problem. I am using Xamarin.Forms 5.0.0.2196. The reproduce you just need to create a new project.

**Comment by Developer112021** [comment]
Thank you for four quick response!
I got this issue since I upgraded Xamarin.Forms from Version 5.0.0.2125 to Version 5.0.0.2196. 
If you want to reproduce this issue, you only need to create a new Xamarin.forms project and start the iOS project.
The android project works fine and the tabbar is readable, but there are different colours in the iOS project.

**Comment by jfversluis** [comment]
Would you be able to try the current nightly version? Instructions for that are in the README on the front page.

**Comment by Developer112021** [comment]
I tried the current nightly version (5.0.1.2180-nightly), but it didn't change anything.

**Comment by jfversluis** [comment]
Hmm I'm not sure if that is actually the current nightly. Which feed do you have configured? Could you double-check and see that you install one that is versioned 5.0.0.xx? Instead of 5.0.1.xx?

**Comment by Developer112021** [comment]
I tried version 5.0.0.2228-nightly and it works now. 
Thank you so much!!

**Comment by jfversluis** [comment]
Awesome, thanks for testing! So, this is fixed in the upcoming service release. I'm planning to release that next week. I have seen some potential blockers so there might be a slight delay, but shouldn't be more than a week. 

Closing this for now, if after that you see anything weird, feel free to open another issue and reference this (and ping me :))

Thanks for collaborating with me on this to verify it!
