### ISSUE TITLE
Xamarin forms tabbed page navigation bar disappearing in ios app

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14823]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-forms-tabbed-page-navigation-bar/1516514)._

---
[severity:Other]
HI

I have a xamarin forms application builds and runs in android and ios.
The user can launch a custom renderer (a  camera) from the page in the first tab.

When the user returns from the custom renderer the bottom navigation panel in IOS disappears.

This is not a problem in Android - only in IOS.

=== Visual Studio Community 2019 for Mac ===

Version 8.10.7 (build 17)
Installation UUID: 990f77ea-7e13-4425-9b50-084d229363ac
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.400/Sdks
SDK Versions:
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.401
	3.1.302
	3.1.301
	3.1.300
	3.1.200
	3.1.102
	3.1.101
	3.0.100
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.7
	3.1.6
	3.1.5
	3.1.4
	3.1.2
	3.1.1
	3.0.0
	2.1.23
	2.1.21
	2.1.20
	2.1.19
	2.1.18
	2.1.16
	2.1.15
	2.1.13
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0

=== .NET Core 3.1 SDK ===

SDK: 3.1.412

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/tsamimac/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/tsamimac/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.12
Hash: e240b8c
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:48:52 UTC

=== Android Device Manager ===

Version: 16.10.0.14
Hash: e340248
Branch: remotes/origin/d16-10
Build date: 2021-08-03 17:49:10 UTC

=== Apple Developer Tools ===

Xcode 12.5.1 (18212)
Build 12E507

=== Xamarin.Mac ===

Version: 7.14.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

=== Xamarin.iOS ===

Version: 14.20.0.24 (Visual Studio Community)
Hash: c4b89cddb
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Build Information ===

Release ID: 810070017
Git revision: 503b9b053dff2e7f136e96b362a629c199f78a42
Build date: 2021-08-05 12:48:29-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Wed Jun 23 00:26:31 PDT 2021
    root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

---
#### Feedback Bot on 8/29/2021, 10:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Bryce Burrows solved on 9/2/2021, 08:33 PM, 0 votes: 

<p>[Workaround]<br>
So i worked around it by downgrading Xamarin forms to 5.0.0.2012<br>
seems to work ok now.</p>
<p>Will report back if i have futher issues.</p>

**Comment by jfversluis** [comment]
Hey Bryce! This shouldn't be happening. I would be interested in which version of Forms you were seeing this behavior on. There have been some changes in iOS 15 that caused issues with nav bars and tab bars, I think we fixed most of it in service release 6 (and even more in the upcoming service release).

If that is not the case, please feel free to ping me here or please open a new issue with all the details.

Thanks!

**Comment by BlueRaja** [comment]
I'm seeing this same issue when I `ExportRenderer` a `PageRenderer` on any page (even if it does literally nothing).   The navigation bar disappears, with no workaround that I can find.

**Comment by ssm3ll** [comment]
Same here. TabbedPage disappears after navigate back. I disabled all ExportRenderer for any custom page but it doesn't help

**Comment by bryceburrows** [comment]
yeah it's still happeeing

**Comment by bryceburrows** [comment]
> Hey Bryce! This shouldn't be happening. I would be interested in which version of Forms you were seeing this behavior on. There have been some changes in iOS 15 that caused issues with nav bars and tab bars, I think we fixed most of it in service release 6 (and even more in the upcoming service release).
> 
> If that is not the case, please feel free to ping me here or please open a new issue with all the details.
> 
> Thanks!

how  do i "ping" you here?

**Comment by BlueRaja** [comment]
> how do i "ping" you here?

Like this: @jfversluis

**Comment by bryceburrows** [comment]
@jfversluis ping(?! ;) )
