### ISSUE TITLE
Newtonsoft dependencies incompatible with latest Xamarin.Android.Support.*

### ISSUE THREAD

**Issue by JamesNK** [xamarin/Xamarin.Forms#1482]
Copied from https://github.com/JamesNK/Newtonsoft.Json/issues/1443 @Enoges

---

### Expected behavior
Install Newtonsoft.Json in a Xamarin.Forms PCL project with the version of Xamarin.Android.Suport.* v25.4.2 without problem

### Actual behavior
When I try to install Newtonsoft.Json in a XamarinForms PCL project whith latest version of Xamarin.Android.Support.* I received an error of dependencies incompatibility.

### Steps to reproduce
Install Xamarin.Android.Support.* 25.4.2 from Nugget package.
Try to instal Newtonsoft.Json version 10.0.3.

Thanks a lot.

**Comment by kingces95** [comment]
@JamesNK I'm unable to reproduce; I'm able to update android support and reference Newtonsoft.Json and build. 

Could you please attach the solution file so we might observe the error locally? Could you also quote the error message?

**Comment by jassmith** [comment]
The support libraries get installed into the android head project which has nothing to do with Forms using PCL or .NET Standard. Sounds like the user is attempting to install things in the incorrect project.
