### ISSUE TITLE
[Bug] Background is replaced with black color for some controls on Android in nightly build of SR7

### ISSUE THREAD

**Issue by holecekp** [xamarin/Xamarin.Forms#14820]
### Description
I have tried the nightly build of SR7. There is a problem on Android. Some controls does not have correct background color. Black color is used instead (because the text is also black it looks like as if the control is missing). Look at screenshots for more details.

Here is a few details:
- AppThemeBinding is used for BackgroundColor.
- Only some controls are affected. Others work well. I cannot think anything that would have the problematic controls in common (maybe that Frames are in the hierarchy).
- The problematic controls are: mostly Labels (inside a ScrollView that is inside a Frame), and also one Frame with LinearGradientBrush used for the background.

### Expected Behavior
Correct color.

### Actual Behavior
A few controls has black background color instead.

### Basic Information

- Version with issue: 5.0.1.2180-nightly
- Last known good version: 5.0.0.2196
- Platform Target Frameworks: 
  - Android: 11
- NuGet Packages:
- Affected Devices: Emulator for Android 5.1. I have not tested other Android versions because there is currently a bug in choosing the correct emulator. I have more emulators for different Android versions. The Visual Studio however starts the app always in the emulator with 5.1 regardless which emulator I have chosen.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.11.5
VisualStudio.16.Release/16.11.5+31729.503
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA088
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.75.64347
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.75.64347
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.75.64347
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.75.64347
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62107.28140
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21322.6+488cc578cafcd261d90d748d8aaa7b8b091232dc
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.190 (d16-11@2391ed9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.17 (remotes/origin/11e0001f0b17269345e80b58fb3adf1ba4efe2cd@11e0001f0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.4.0.5 (d16-11/7776c9f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@48766c0
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@683f375


Xamarin.iOS and Xamarin.Mac SDK   15.0.0.8 (0796d78dc)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Screenshots

5.0.0.2196:
![sr6](https://user-images.githubusercontent.com/24872113/139961838-d0881926-6b8c-4808-a148-18b9c3b57ebd.png)

5.0.1.2180-nightly:
![nightlywithbug](https://user-images.githubusercontent.com/24872113/139961848-335cb292-c9a9-4529-a981-f77e54799e48.png)

### Workaround
Use SR6 instead for Android (or SR5 if you use UWP because of serious UWP bugs in SR6).

**Comment by jfversluis** [comment]
Just a quick note on this one: I see you're mentioning 5.0.1.xxx-nightly. I don't think this is the latest version, could you maybe try again with 5.0.0.xxx-nightly? Can I ask what the feed is you are using?

Sorry for the confusion!

**Comment by holecekp** [comment]
@jfversluis  I have added Nuget.Config (https://github.com/xamarin/Xamarin.Forms#readme) and I am using xamarin-ci (https://aka.ms/xf-nightly/index.json).

This is strange because today I have changed the version from SR5 back to the latest prerelease and now I can see 5.0.0.2228-nightly as the latest. The 5.0.1.xxx version is not even in the list (and I have not changed the feed since then). I have no idea where it came from.

Anyway, the colors on Android are all right in 5.0.0.2228-nightly so I am closing this issue. I have also checked that the correct nightly version does not contain the UWP issues that I have reported earlier.

**Comment by jfversluis** [comment]
> The 5.0.1.xxx version is not even in the list (and I have not changed the feed since then)

This is because of me 😄  this was the second report this morning of someone using the wrong nightly version so I went to check, saw there was a weird version there and unlisted it so we don't repeat this mistake.

Sorry for the inconvenience here and because of that even more of a bigger thank you for having the patience to collaborate on this and see that everything is working!
