### ISSUE TITLE
Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers - System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/XamarinFormsPlatformiOSRendererPool/1485672)._

---
I've been seeing logs for the following error occur about 200 times/day on a production app. I've been unable to reproduce the issue myself locally, but by following the stack trace I've found a bit of code in Xamarin.Forms.Platform.iOS > RendererPool.cs that seems suspicious (unless I'm misunderstanding something). Below I'll include the code I'm concerned with, a summary of my concern, and finally the stack trace.

### RendererPool.cs > UpdateRenderers(Element newElement)

```
void UpdateRenderers(Element newElement)
{
	var newElementController = (IElementController)newElement;

	if (newElementController.LogicalChildren.Count == 0)
		return;

	var subviews = _parent.NativeView.Subviews;
	for (var i = 0; i < subviews.Length; i++)
	{
		var childRenderer = subviews[i] as IVisualElementRenderer;
		if (childRenderer == null)
			continue;

		var x = (int)childRenderer.NativeView.Layer.ZPosition / 1000;
		var element = newElementController.LogicalChildren[x] as VisualElement;
		if (element == null)
			continue;

		if (childRenderer.Element != null && ReferenceEquals(childRenderer, Platform.GetRenderer(childRenderer.Element)))
			childRenderer.Element.ClearValue(Platform.RendererProperty);

		childRenderer.SetElement(element);
		Platform.SetRenderer(element, childRenderer);
	}
}
```
I'm thinking the issue I'm seeing might be caused by:

```
var element = newElementController.LogicalChildren[x] as VisualElement;
```
There's no check to ensure 'x' is in the range of LogicalChildren. Since I've only seen this error in production I can't say that my assumptions here are definitive but if nothing else, it seems like it might be prudent to add a check here to verify that the index is in range of the collection.

### Stack Trace
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index   
>at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) <0x10541ce6c + 0x0006b> in <da8885cdf78b449d96de00cdb9d47225#5abd187266445b2910f79c6dbf84b4e1>:0
>at System.Collections.ObjectModel.Collection`1[T].get_Item (System.Int32 index) <0x105413220 + 0x0004f> in <da8885cdf78b449d96de00cdb9d47225#5abd187266445b2910f79c6dbf84b4e1>:0    
>at System.Collections.ObjectModel.ReadOnlyCollection`1[T].get_Item (System.Int32 index) <0x105414b44 + 0x0004f> in <da8885cdf78b449d96de00cdb9d47225#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers (Xamarin.Forms.Element newElement) <0x106446474 + 0x0016b> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) <0x106445be0 + 0x001ab> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) <0x1064497b4 + 0x000cb> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) <0x106449768 + 0x00023> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) <0x10644b674 + 0x000c7> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) <0x10644ab04 + 0x0037f> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) <0x10644a40c + 0x0004b> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers (Xamarin.Forms.Element newElement) <0x106446474 + 0x00203> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) <0x106445be0 + 0x001ab> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) <0x1064497b4 + 0x000cb> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) <0x106449768 + 0x00023> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) <0x10644b674 + 0x000c7> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) <0x10644ab04 + 0x0037f> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) <0x10644a40c + 0x0004b> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers (Xamarin.Forms.Element newElement) <0x106446474 + 0x00203> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) <0x106445be0 + 0x001ab> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) <0x1064497b4 + 0x000cb> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) <0x106449768 + 0x00023> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) <0x10644b674 + 0x000c7> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) <0x10644ab04 + 0x0037f> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) <0x10644a40c + 0x0004b> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.ViewCellRenderer+ViewTableCell.UpdateCell (Xamarin.Forms.ViewCell cell) <0x106453818 + 0x0047f> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.ViewCellRenderer.GetCell (Xamarin.Forms.Cell item, UIKit.UITableViewCell reusableCell, UIKit.UITableView tv) <0x106452c38 + 0x000fb> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.CellTableViewCell.GetNativeCell (UIKit.UITableView tableView, Xamarin.Forms.Cell cell, System.Boolean recycleCells, System.String templateId) <0x10644f5dc + 0x00183> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.ListViewRenderer+ListViewDataSource.GetCell (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) <0x10646ef84 + 0x001fb> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at (wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,long)   at UIKit.UITableView.ReloadRows (Foundation.NSIndexPath[] atIndexPaths, UIKit.UITableViewRowAnimation withRowAnimation) <0x1061bb3fc + 0x00093> in <250ad56849ca4d8990c550f6eb45cabe#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Xamarin.Forms.Platform.iOS.CellRenderer+<>c__DisplayClass9_0.<WireUpForceUpdateSizeRequested>b__0 (System.Object sender, System.EventArgs e) <0x10644f078 + 0x00087> in <88ea9adfcd894d98a763d3b59f716d7e#5abd187266445b2910f79c6dbf84b4e1>:0    
>at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)   
>at Xamarin.Forms.Cell.OnForceUpdateSizeRequested () <0x10551deb0 + 0x001af> in <0f4d8989422f43769552240d42a789a6#5abd187266445b2910f79c6dbf84b4e1>:0   
>at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) <0x1053744b8 + 0x0006b> in <da8885cdf78b449d96de00cdb9d47225#5abd187266445b2910f79c6dbf84b4e1>:0    
>at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () <0x1061fa918 + 0x00037> in <250ad56849ca4d8990c550f6eb45cabe#5abd187266445b2910f79c6dbf84b4e1>:0    
>at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)   
>at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) <0x1061a1968 + 0x00047> in <250ad56849ca4d8990c550f6eb45cabe#5abd187266445b2910f79c6dbf84b4e1>:0    at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x1061a18bc + 0x00057> in <250ad56849ca4d8990c550f6eb45cabe#5abd187266445b2910f79c6dbf84b4e1>:0

### Other Info/Environment
This stack trace originates from a call to ```ForceUpdateSize()``` in a subclassed ```ViewCell``` object. The ```ViewCell``` is part of a ```ListView``` with ```HasUnevenRows=true``` and default ```CachingStrategy```

VS Enterprise 2019 for Mac
Version 8.10

Mono: 6.12.0.140

Xcode: 12.5.1

Xamarin.iOS: 14.20.0.1

---
#### Feedback Bot on 7/26/2021, 01:46 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Zack Yang [MSFT] on 7/27/2021, 01:51 AM: 

<p>Thanks for your feedback!<br>
For us to investigate this further, could you please provide the sample project that can be reproduce your issue? We look forward to hearing from you!</p>

#### Zack Yang [MSFT] on 7/27/2021, 07:27 PM: 

<p>This feedback is being re-triaged as we are moving it to another team that can better help with the issue. Thanks for your patience.</p>

#### Feedback Bot on 11/1/2021, 01:33 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we have an example where reproduce the issue?

**Comment by jfversluis** [comment]
Long time no response, hope this is resolved by now. If not please let us know!
