### ISSUE TITLE
[Bug] TabBarTitleColor

### ISSUE THREAD

**Issue by C6H10O5n** [xamarin/Xamarin.Forms#14836]
### Description
Shell.TabBarTitleColor property is ignored when in landscape orientation on ios

### Steps to Reproduce

1. open xanimals sample 
2. update XamarinForms pkg to 5.0.0.2196 
3.run on ios simulator 
4. rotate device then tab bar text changes to default blue

- Version with issue: 5.0.0.2196
- Last known good version: 5.0.0.2125

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue on main. I think have been fixed by https://github.com/xamarin/Xamarin.Forms/pull/14775 and is not included yet in a Service Release. @jfversluis Could you confirm this?

**Comment by jfversluis** [comment]
I would suspect so... @C6H10O5n would you be able to try the nightly feed and see if it works correctly there?

**Comment by C6H10O5n** [comment]
Yes is working in 5.0.1.2031-nightly!!  thanks

**Comment by jfversluis** [comment]
Great! That should be released somewhere early next week :)
