### ISSUE TITLE
Adding rectangle to xamarin forms contentpage raises warnings

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14835]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Adding-rectangle-to-xamarin-forms-conten/1564834)._

---
When a rectangle is used on a xamarin forms page intellisense of the rectange does not work and errors show up.

---
#### Feedback Bot on 10/27/2021, 09:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we get information about the warnings?, what Visual Studio version are you using?

**Comment by jfversluis** [comment]
Long time no response. If this is still an issue to someone, let uw know!
