### ISSUE TITLE
[Bug] No longer receiving Navigated events from Shell when popping a page off the stack

### ISSUE THREAD

**Issue by mediabounds** [xamarin/Xamarin.Forms#14830]
### Description
As of XF 5.0.0 SR4, we are no longer receiving Navigated events when a page is popped off the stack by the user tapping the back button.

I believe the issue is caused by these changes in ShellSection:
https://github.com/xamarin/Xamarin.Forms/commit/86db84805ebfb5a2e36d064a25086782b8dc4a69#diff-44ee8096b48f9224cfbc5fecb140ace1c1a069dfd4f1c2f2761d8517de23d35b

It removes calls to update Shell's current state seemingly under the assumption that GoToAsync will handle it, but unless the back navigation is deferred, GoToAsync is never invoked.

This may be the same issue as #14805.

### Steps to Reproduce
In a Xamarin.Forms project using Shell... 
1. Push a page onto the stack
2. Use the native back button (i.e. the back button in the navigation bar) to go back

### Expected Behavior
A Navigating event would be raised followed by a Navigated Event.

### Actual Behavior
Both events are triggered when *pushing* a view onto the stack.
But when popping, only the Navigating event is raised.

### Basic Information

- Version with issue:
- Last known good version: 5.0.0 SR3

**Comment by jfversluis** [comment]
@mediabounds, a PR (#14900) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!
