### ISSUE TITLE
[Bug] iOS app crashing on  using SectionHeaderPadding below iOS 15

### ISSUE THREAD

**Issue by vanajaRa** [xamarin/Xamarin.Forms#14838]
### Description
Currently I am deploying my app on Xamarin.Forms iOS. I try to customize SectionHeaderPadding for Xamarin ListView using CustomRenderer. I get the crash issue while launching the app.

### Basic Information
VS version: 16.11.4
Xamarin iOS and Xamarin.Mac SDK version: 15.0.0.8

- Version with issue:
Issue occurs only when deploying in the emulator below iOS 15

### Stack trace

"System.MissingMethodException","message":"System.MissingMethodException: Method not found: void UIKit.UITableView.set_SectionHeaderTopPadding(System.nfloat)","hasFullStack":true,"parsedStack":[{"level":0,"method":"unknown","assembly":"unknown","line":0},{"level":1,"method":"Xamarin.Forms.BindableObject.OnPropertyChanged","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs","line":229},{"level":2,"method":"Xamarin.Forms.Element.OnPropertyChanged","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\Element.cs","line":353},{"level":3,"method":"Xamarin.Forms.BindableObject.SetValueActual","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs","line":461},{"level":4,"method":"Xamarin.Forms.BindableObject.SetValueCore","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs","line":397},{"level":5,"method":"Xamarin.Forms.BindableObject.SetValue","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs","line":334},{"level":6,"method":"Xamarin.Forms.BindableObject.SetValue","assembly":"Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Core\\BindableObject.cs","line":311},{"level":7,"method":"Xamarin.Forms.Platform.iOS.Platform.SetRenderer","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Platform.cs","line":238},{"level":8,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":116},{"level":9,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.Load","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":49},{"level":10,"method":"Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[[Xamarin.Forms.VisualElement, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetElement","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs","line":283},{"level":11,"method":"Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[[Xamarin.Forms.VisualElement, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs","line":158},{"level":12,"method":"Xamarin.Forms.Platform.iOS.Platform.CreateRenderer","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Platform.cs","line":227},{"level":13,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":115},{"level":14,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.Load","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":49},{"level":15,"method":"Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[[Xamarin.Forms.VisualElement, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].SetElement","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs","line":283},{"level":16,"method":"Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[[Xamarin.Forms.VisualElement, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementRenderer.cs","line":158},{"level":17,"method":"Xamarin.Forms.Platform.iOS.Platform.CreateRenderer","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Platform.cs","line":227},{"level":18,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":115},{"level":19,"method":"Xamarin.Forms.Platform.iOS.VisualElementPackager.Load","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\VisualElementPackager.cs","line":49},{"level":20,"method":"Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLoad","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\PageRenderer.cs","line":237},{"level":21,"method":"unknown","assembly":"unknown","line":0},{"level":22,"method":"UIKit.UIViewController.get_View","assembly":"Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065","fileName":"/Users/builder/azdo/_work/1/s/xamarin-macios/src/build/ios/native/UIKit/UIViewController.g.cs","line":3211},{"level":23,"method":"Xamarin.Forms.Platform.iOS.PageRenderer.get_NativeView","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\PageRenderer.cs","line":103},{"level":24,"method":"Xamarin.Forms.Platform.iOS.PageRenderer.SetAutomationId","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\PageRenderer.cs","line":311},{"level":25,"method":"Xamarin.Forms.Platform.iOS.PageRenderer.SetElement","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\PageRenderer.cs","line":119},{"level":26,"method":"Xamarin.Forms.Platform.iOS.Platform.CreateRenderer","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Platform.cs","line":227},{"level":27,"method":"Xamarin.Forms.Platform.iOS.NavigationRenderer.CreateViewControllerForPage","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\NavigationRenderer.cs","line":365},{"level":28,"method":"Xamarin.Forms.Platform.iOS.NavigationRenderer+<OnPushAsync>d__52.MoveNext","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\NavigationRenderer.cs","line":342},{"level":29,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs","line":157},{"level":30,"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs","line":186},{"level":31,"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs","line":154},{"level":32,"method":"System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs","line":125},{"level":33,"method":"System.Runtime.CompilerServices.TaskAwaiter`1[[System.Boolean, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs","line":410},{"level":34,"method":"Xamarin.Forms.Platform.iOS.NavigationRenderer+<<ViewDidLoad>b__47_0>d.MoveNext","assembly":"Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\NavigationRenderer.cs","line":233},{"level":35,"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs","line":157},{"level":36,"method":"System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0","assembly":"mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","fileName":"/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs","line":1021},{"level":37,"method":"Foundation.NSAsyncSynchronizationContextDispatcher.Apply","assembly":"Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065","fileName":"/Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs","line":178},{"level":38,"method":"unknown","assembly":"unknown","line":0},{"level":39,"method":"UIKit.UIApplication.Main","assembly":"Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065","fileName":"/Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs","line":86},{"level":40,"method":"UIKit.UIApplication.Main","assembly":"Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065","fileName":"/Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs","line":65},{"level":41,"method":"Glnl.Origination.Mobile.iOS.Application.Main","assembly":"Glnl.Origination.Mobile.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","fileName":"C:\\Users\\VANN1\\source\\repos\\glnl-origination-mobile\\src\\Glnl.Origination.Mobile.iOS\\Main.cs","line":25}]}],"severityLevel":"Error","properties":{"LoggerName":"Glnl.Origination.Mobile.iOS.Application","Message":"Method not found: void UIKit.UITableView.set_SectionHeaderTopPadding(System.nfloat)"}}}}

**Comment by jfversluis** [comment]
That property does not exist prior to iOS15, in your code you should check if you are running on iOS15 and only then try to customize that behavior.

**Comment by nick5454** [comment]
@jfversluis I don't understand why that code runs on a device that is 12.4. Do I need to override the entire event then?
