### ISSUE TITLE
[Enhancement] Migrate existing splash screen to Android 12

### ISSUE THREAD

**Issue by haoyuant** [xamarin/Xamarin.Forms#14849]
Hi, I am not sure if the current release supports the splash screen migration to Android 12, does anyone know when it will be released if not ready yet and any example about how to do this in Xamarin? Thanks : )

**Comment by jfversluis** [comment]
Do you have any more info on what a "splash screen migration" is? Not sure what you mean by this. Also it seems more like a question, please use the discussions for this or the .NET Tech Community site.

**Comment by haoyuant** [comment]
https://developer.android.com/guide/topics/ui/splash-screen/migrate So Android 12 provides a default splash screen for all apps, need to use the SplashScreen API to migrate the existing one to work with the new system.

**Comment by jfversluis** [comment]
Ah OK, thanks! That might be something we need to look into :)

**Comment by domedellolio** [comment]
I follow with interest this topic since we just migrate our app to Android 12 and we look forward to use default one. 
Thanks

**Comment by CleverSoftwarePoland** [comment]
Any news how to use new Splashscreen?

**Comment by jfversluis** [comment]
Afraid not, sorry. Also, looks like we'll have to wait for Xamarin.Android to add this capability first: https://github.com/xamarin/xamarin-android/issues/6517

**Comment by elOG8** [comment]
Hellow, any news how to implemente Splash Screen on Xamarin Android 12 (API 31)..... Thanks

**Comment by jfversluis** [comment]
If there is any news it will be posted here :)

**Comment by jfversluis** [comment]
In the earlier linked issue there is guidance on how to update the splash screen capabilities: https://github.com/xamarin/xamarin-android/issues/6517

The packages from Google themselves are even still in beta stage that's why we also don't have official support for it yet. If you still want to use it right now, refer to the methods in the linked issue. Thanks!

**Comment by wagenheimer** [comment]
Is there any news on this? Still could'nt make my SplashScreen works on Android 12.
