### ISSUE TITLE
iOS TabBar Shell.TabBarBackgroundColor

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14843]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/iOS-TabBar-ShellTabBarBackgroundColor/1545150)._

---
[regression] [worked-in:Not 8.10.10 (Build 8)]
It's a repeat but the latest build 8.10.10 (Build 8) on iOS the Shell.TabBarBackgroundColor is always transparent.  I can't remember the build before.  Android is fine I use Forms.

I have even copied in the example from MS site.  Again code hasn't changed for two years just updated to 8.10.10.

Sorry again but help.

---
#### Feedback Bot on 10/5/2021, 08:14 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Scott Stahurski on 10/25/2021, 03:44 PM: 

<p>This is still an issue but only in <strong>Light mode</strong> on IOS.  In dark mode the tabbar changes color.  It appears the the foreground color for icons and text are set to a shade of white, but so is the background color of the tabbar.</p>
<p>So icons and text do no appear with the same color.  Trying to change programmatically does not help.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I think this should be fixed in newer versions where we have fixes for new iOS APIs that changed this behavior

**Comment by latnok25** [comment]
it's not fixed yet
