### ISSUE TITLE
Accessibility : Not all controls are keyboard focusable or operable

### ISSUE THREAD

**Issue by HarshalCapgemini** [xamarin/Xamarin.Forms#14853]
Accessibility for Android 

Not all controls are keyboard focusable or operable.

Need some property to set focus.

Related to https://github.com/xamarin/Xamarin.Forms/issues/9999

**Comment by rachelkang** [comment]
Hi, @HarshalCapgemini - this is something we hope to focus on more in .NET MAUI. That being said, if you could provide some more information on which scenarios you're having issues with keyboard accessibility, and ideally share a sample project, that would be super helpful!

Regarding the referenced "set accessibility focus" API suggestion, I've responded in the issue regarding how you can leverage that API going forward.

**Comment by jfversluis** [comment]
No response to our request for more info, closing this for now.
