### ISSUE TITLE
Bug] [iOS] List swipe with MaterialButtonRenderer crash

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#14858]
### Description
The application crashes if the user try to swipe right to left and there is a button with MaterialButtonRenderer.
This happen only on iOS.

### Steps to Reproduce
Please follow this guide and\or the video to work with the app.
1 - For the first login use this credentials:

 _REMOVED_
2 - after the message about the translation, redo the login with these credentials:
_REMOVED_
4 - insert an hour and a note then press the "+" button
5 - you can repeat the step 4 to add 2/3 rows
6 - tap on the bottom tab "Timetables"
7 - try to swipe right to left, after a few swipe (or maybe after the first if you are lucky), the app goes to error and crashes

To run the project open AppFAST/SgatFAST.sln

### Stack
```
    at Xamarin.Forms.Material.iOS.MaterialButtonRenderer.ApplyThemeIfNeeded () [0x00000] in D:\a\1\s\Xamarin.Forms.Material.iOS\MaterialButtonRenderer.cs:118 
  at Xamarin.Forms.Material.iOS.MaterialButtonRenderer.LayoutSubviews () [0x00006] in D:\a\1\s\Xamarin.Forms.Material.iOS\MaterialButtonRenderer.cs:88 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.Type principalClass, System.Type delegateClass) [0x00047] in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at SgatFAST.iOS.Application.Main (System.String[] args) [0x00002] in /Users/pozzy/Desktop/per XF/AppFAST/SgatFAST/SgatFAST.iOS/Main.cs:16 
```

### Expected Behavior
Not crash

### Actual Behavior
Crash

### Basic Information

- Version with issue: 5.0.0.2083
- IDE: VS on mac
- Platform Target Frameworks: 
  - iOS:  15.x
- Nuget Packages: Xamarin.Forms.Visual.Material

**Comment by jfversluis** [comment]
Hey there. I removed the link and passwords and such. I don't think it's a great idea to post the full source code of your app here without any licensing. From a quick scan it also looks like you have now exposed Google Service credentials in your iOS plist files and possibly others so you might want to refresh some API keys to make sure it doesn't get misused.

For the actual issue: I see you're using an older version of Forms, please update to the latest version, maybe it's already fixed there. If not, feel free to ping us here of open a new issue with a repro project attached that is not the full source of you app.

Thanks

**Comment by Raystorm7** [comment]
> Hey there. I removed the link and passwords and such. I don't think it's a great idea to post the full source code of your app here without any licensing. From a quick scan it also looks like you have now exposed Google Service credentials in your iOS plist files and possibly others so you might want to refresh some API keys to make sure it doesn't get misused.
> 
> For the actual issue: I see you're using an older version of Forms, please update to the latest version, maybe it's already fixed there. If not, feel free to ping us here of open a new issue with a repro project attached that is not the full source of you app.
> 
> Thanks

Hi, thank you but the issue is replicable also in the latest version.
