### ISSUE TITLE
Accessibility : Modal dialogs don't trap focus

### ISSUE THREAD

**Issue by HarshalCapgemini** [xamarin/Xamarin.Forms#14851]
Accessibility for Android

Modal dialogs don't trap focus.
Trap keyboard and screen reader focus inside the modal dialog. 

Need Xamarin forms to provide some property to focus dialog.

Related to https://github.com/xamarin/Xamarin.Forms/issues/9999

**Comment by rachelkang** [comment]
Hi, @HarshalCapgemini - would you mind elaborating on what behavior you're expecting? As [mentioned ](https://github.com/xamarin/Xamarin.Forms/issues/9999#issuecomment-964393510)in the referenced issue, if you're looking to force the focus somewhere, you can use the new `SetSemanticFocus` method from the XamarinCommunityToolkit.

If you haven't already, I also recommend updating to the latest version Xamarin.Forms or at least to Xamarin.Forms 5.0.0.2083, which has many accessibility improvements. These improvements include an experimental accessibility flag that addresses a lot of improvements in Android accessibility.

To leverage this flag on the latest versions of Xamarin Forms, the following code can be inserted in the App.xaml.cs file, following the InitializeComponent call and before the MainPage is set: `Xamarin.Forms.Device.SetFlags(new List<string> { "Accessibility_Experimental"});`
