### ISSUE TITLE
A global usings/namespaces file to include namespaces for xaml files namespaces

### ISSUE THREAD

**Issue by MrClan** [xamarin/Xamarin.Forms#14865]
## Summary
A global usings/namespaces file to include namespaces for xaml files namespaces

## Intended Use Case
It would reduce significant number of lines on top of every xaml file, that has to be repeated in each file, just to import namespaces.

**Comment by jfversluis** [comment]
I'm not sure what you mean with this? Everything in Xamarin.Forms is already included with just a single namespace declaration and you also have the possibility to do the same with your own namespaces: https://docs.microsoft.com/xamarin/xamarin-forms/xaml/custom-namespace-schemas

**Comment by MrClan** [comment]
What I meant was, to have the ability to be able to move any custom namespace imports, to a single file somewhere, so that they don't have to be repeated in every single xaml file over and over again. An example would look something like this:

# Current State
In current state, my pages/views looks like this:

### Page1.xaml

```
<ContentPage ...
             xmlns:controls="clr-namespace:MyCompany.Controls;assembly=MyCompany.Controls"
             xmlns:views="clr-namespace:MyCompany.Controls;assembly=MyCompany.Views"
             xmlns:utilControls="clr-namespace:MyCompany.Controls;assembly=MyCompany.UtilControls"
             xmlns:effects="clr-namespace:MyCompany.Controls;assembly=MyCompany.Effects"
             xmlns:renderers="clr-namespace:MyCompany.Controls;assembly=MyCompany.Renderers"
             xmlns:resources="clr-namespace:MyCompany.Controls;assembly=MyCompany.Resources"
             xmlns:converters="clr-namespace:MyCompany.Controls;assembly=MyCompany.Converters"
             xmlns:behaviors="clr-namespace:MyCompany.Controls;assembly=MyCompany.Behaviors"
             xmlns:shadows="clr-namespace:MyCompany.Controls;assembly=MyCompany.Shadows"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             ios:Page.UseSafeArea="True"
             NavigationPage.HasNavigationBar="False"
             >

<Label Text="{x:Static resources:Strings.TitleText}" />   
...
</ContentPage>
```

### Page2.xaml

```
<ContentPage ...
             xmlns:controls="clr-namespace:MyCompany.Controls;assembly=MyCompany.Controls"
             xmlns:views="clr-namespace:MyCompany.Controls;assembly=MyCompany.Views"
             xmlns:utilControls="clr-namespace:MyCompany.Controls;assembly=MyCompany.UtilControls"
             xmlns:effects="clr-namespace:MyCompany.Controls;assembly=MyCompany.Effects"
             xmlns:renderers="clr-namespace:MyCompany.Controls;assembly=MyCompany.Renderers"
             xmlns:resources="clr-namespace:MyCompany.Controls;assembly=MyCompany.Resources"
             xmlns:converters="clr-namespace:MyCompany.Controls;assembly=MyCompany.Converters"
             xmlns:behaviors="clr-namespace:MyCompany.Controls;assembly=MyCompany.Behaviors"
             xmlns:shadows="clr-namespace:MyCompany.Controls;assembly=MyCompany.Shadows"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             ios:Page.UseSafeArea="True"
             NavigationPage.HasNavigationBar="False"
             >

<Label Text="{x:Static resources:Strings.TitleText}" />   
...
</ContentPage>
```

# But with this feature

### GlobalNamespaces.xaml
```
<ContentPage ...
             xmlns:controls="clr-namespace:MyCompany.Controls;assembly=MyCompany.Controls"
             xmlns:views="clr-namespace:MyCompany.Controls;assembly=MyCompany.Views"
             xmlns:utilControls="clr-namespace:MyCompany.Controls;assembly=MyCompany.UtilControls"
             xmlns:effects="clr-namespace:MyCompany.Controls;assembly=MyCompany.Effects"
             xmlns:renderers="clr-namespace:MyCompany.Controls;assembly=MyCompany.Renderers"
             xmlns:resources="clr-namespace:MyCompany.Controls;assembly=MyCompany.Resources"
             xmlns:converters="clr-namespace:MyCompany.Controls;assembly=MyCompany.Converters"
             xmlns:behaviors="clr-namespace:MyCompany.Controls;assembly=MyCompany.Behaviors"
             xmlns:shadows="clr-namespace:MyCompany.Controls;assembly=MyCompany.Shadows"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             ios:Page.UseSafeArea="True"
             NavigationPage.HasNavigationBar="False"
             />
```

And with this file in place, all my views/pages would be simplified as shown below:

### Page1.xaml
```
<ContentPage ...
             >
<Label Text="{x:Static resources:Strings.TitleText}" />
...
</ContentPage>
```

### Page2.xaml
```
<ContentPage ...
             >
<Label Text="{x:Static resources:Strings.TitleText}" />
...
</ContentPage>
```

Note that, all the globally imported namespaces are available in all my views, plus any properties set in the base view or global/root page like: `ios:Page.UseSafeArea="True"` or `NavigationPage.HasNavigationBar="False"` are automatically applied with inherited values. Of course, setting the same properties in the current page/view would take preference and override any inherited values.


PS:
A further enhancement, and a really useful option, could be to have a property on views to explicitly specify inheritance from the any file base page or global file as such:
```
<ContentPage ...
             inheritsFrom="GlobalNamespaces.xaml"
             >
```

@jfversluis Hope this clarifies the requirements and use cases of this feature request.

**Comment by jfversluis** [comment]
Thanks for the clarification! I guess that definitely makes sense. As far as I know something like that is not possible at the moment. Although, with the link I posted earlier you would be able to do something like this to at least combine multiple namespaces into one :) but it isn't really the same.

Now for the bad news. I'm pretty sure this won't come to Xamarin.Forms. We're winding down development here, only doing the bare minimum to add support for new platform OS versions and adding bugfixes and stability fixes, etc. We're trying to stay clear of new features.

If this is something you would like to see, please open an issue, especially with that last info, in the .NET MAUI repo as a feature request so we can take a look at it :)

I really like the idea of this though! Maybe it's worth investigating how UWP/WPF do this? Do they have something we could adopt?

Thanks!
