### ISSUE TITLE
StreamImagesourceHandler logs with the wrong logger name

### ISSUE THREAD

**Issue by thomasgalliker** [xamarin/Xamarin.Forms#14862]
Just a minder problem (copy-paste) but it can lead to investigation problems:
StreamImagesourceHandler --> Logger name should be nameof(StreamImagesourceHandler)
https://github.com/xamarin/Xamarin.Forms/blob/d99264507dc1623aecb83daf81aadd2effae62ae/Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs#L199

**Comment by jfversluis** [comment]
Good catch! :D Fixed it
