### ISSUE TITLE
Xamarin.forms App crashes in Background on iOS 15 runtime.m line 1284 xamarin_find_protocol_wrapper_type

### ISSUE THREAD

**Issue by nitinmalik022** [xamarin/Xamarin.Forms#14870]
### Steps to Reproduce

1. launch the app
2. go through the app in usual way, put it in background
3. multiple crashes being logged on firebase but app launches again fine.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 

Visual Studio Community 2019 for Mac
Version 8.10.9 (build 3)
Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)
Package version: 612000140
Mono Framework MDK
Runtime:
Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
Package version: 612000140

NuGet
Version: 5.9.0.7134

.NET Core 3.1 SDK
SDK: 3.1.413

Apple Developer Tools
Xcode 12.5.1 (18212)
Build 12E507

Xamarin.Mac
Version: 7.14.0.24 (Visual Studio Community)
Branch: d16-10
Build date: 2021-06-15 22:03:00-0400

Xamarin.iOS
Version: 14.20.0.24 (Visual Studio Community)
Branch: d16-10
Build date: 2021-06-15 22:03:01-0400
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/70443167/141278329-0a5ada77-7c42-41bf-b35b-8c38354822ca.png)
![image](https://user-images.githubusercontent.com/70443167/141278466-bee274ac-c7b0-4ff1-846c-6b9d8b6a306e.png)

**Comment by jfversluis** [comment]
Do you have any code that is running in the background?

This is very little information to work with, and by default Forms does not run anything in the background so I kind of doubt that this is a bug in Xamarin.Forms.

Please provide more relevant code or a reproduction sample that shows this behavior.

**Comment by nitinmalik022** [comment]
we are not doing/running anything when app is in killed state but we do have things like downloading a file when user is using the app and this task could be running for sometime after user switch between apps.
We also have Couchbase DB  SDK integrated in the app which runs a replicator, which will initiate connection with a Sync Gateway and participate in the replication of database changes to bring both local and remote databases into sync

**Comment by jfversluis** [comment]
Thanks for the extra info! However, unfortunately it's still not nearly enough to get some idea of what is going on here. Additionally I still very much doubt that this is a bug in Forms. Of course I could be wrong :) 

Please see if you can find additional stack traces or any other leads on where the origin of the exceptions might be. I'm closing this for now, please ping me if you find anything that we can work from. Thanks!

**Comment by nitinmalik022** [comment]
I have attached the screenshot of stack trace we are getting on firebase, As we are still not able to replicate this in debug mode so do not have more stack trace on this, we have created a new release after updated our forms and xcode to latest will update you further on this

**Comment by jfversluis** [comment]
The screenshots only show code in mono/UIKit and do not have any information that will help us debug this further. This also leads me to think even more that this is not something that has to do with Forms. Not a single reference to Forms is in this stacktrace.

Let me know if you find anything more, happy to help
