### ISSUE TITLE
Application.Main (System.String[] args) Xamarin.froms(iOS)

### ISSUE THREAD

**Issue by shanmugasundharamselvadurai** [xamarin/Xamarin.Forms#14876]
Hi 
I am facing an app crashs on iOS(Xamarin. forms), Please find the below crash report.

Application.Main (System.String[] args)
SIGABRT: Objective-C exception thrown. Name: NSInvalidArgumentException Reason: Can't add self as subview Native stack trace: 0 CoreFoundation 0x00000001a29bedd4 A408A063-A023-3AAA-A674-0FF01607F818 + 1220052 1 libobjc.A.dylib 0x00000001b75167a8 objc_exception_throw + 60 2 CoreFoundation 0x00000001a28b3e74 A408A063-A023-3AAA-A674-0FF01607F818 + 126580 3 UIKitCore 0x00000001a58e9edc F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 17845980 4 UIKitCore 0x00000001a4cc715c F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5120348 5 UIKitCore 0x00000001a58e3af8 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 17820408 6 UIKitCore 0x00000001a4cc6bf0 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5118960 7 UIKitCore 0x00000001a58e900c F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 17842188 8 UIKitCore 0x00000001a4cc6618 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5117464 9 UIKitCore 0x00000001a4cb5f34 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5050164 10 UIKitCore 0x00000001a4df7688 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 6366856 11 UIKitCore 0x00000001a4cb5eac F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5050028 12 UIKitCore 0x00000001a58e37d4 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 17819604 13 UIKitCore 0x00000001a4cb5ce4 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 5049572 14 UIKitCore 0x00000001a4bb254c F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 3986764 15 UIKitCore 0x00000001a4bc6df8 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 4070904 16 UIKitCore 0x00000001a4bc8288 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 4076168 17 UIKitCore 0x00000001a4ba9e58 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 3952216 18 UIKitCore 0x00000001a58f0be4 F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 17873892 19 QuartzCore 0x00000001a5d77670 BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 1472112 20 QuartzCore 0x00000001a5d77b54 BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 1473364 21 QuartzCore 0x00000001a5d8c78c BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 1558412 22 QuartzCore 0x00000001a5cce5e4 BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 779748 23 QuartzCore 0x00000001a5cfa7f4 BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 960500 24 QuartzCore 0x00000001a5cfbb20 BAEE38F0-F331-3DA8-956E-4532609A7BB6 + 965408 25 CoreFoundation 0x00000001a2937c74 A408A063-A023-3AAA-A674-0FF01607F818 + 666740 26 CoreFoundation 0x00000001a2931d98 A408A063-A023-3AAA-A674-0FF01607F818 + 642456 27 CoreFoundation 0x00000001a2932344 A408A063-A023-3AAA-A674-0FF01607F818 + 643908 28 CoreFoundation 0x00000001a29319f4 CFRunLoopRunSpecific + 600 29 GraphicsServices 0x00000001ba002734 GSEventRunModal + 164 30 UIKitCore 0x00000001a53af75c F9E6CF6F-3B15-3C66-8C35-951AFD4D0CC4 + 12363612 31 UIKitCore 0x00000001a53b4fcc UIApplicationMain + 168 32 thebigword.iOS 0x0000000105d0b518 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 20977420 33 thebigword.iOS 0x0000000105c407b0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 20146596 34 thebigword.iOS 0x0000000105c40734 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 20146472 35 thebigword.iOS 0x00000001049d63f4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 837096 36 thebigword.iOS 0x0000000104d6edd0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 4607940 37 thebigword.iOS 0x00000001068a4d08 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 33140476 38 thebigword.iOS 0x000000010695e81c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 33901072 39 thebigword.iOS 0x0000000106964ad0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 33926340 40 thebigword.iOS 0x0000000106883260 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 33002580 41 thebigword.iOS 0x0000000106a3f248 xamarin_log + 4992 42 thebigword.iOS 0x00000001049d6358 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 836940 43 libdyld.dylib 0x00000001a25edcf8 1A4BE407-C230-309B-AEAB-8E9C62BD377A + 7416

**Comment by jfversluis** [comment]
We will need a lot more detail to know what this is about, please follow the bug report template. Thanks
