### ISSUE TITLE
[Spec]  is there any way to merge 2 info.plist in 1 project?

### ISSUE THREAD

**Issue by kerberosargos** [xamarin/Xamarin.Forms#14889]
Hello folks,

I have 2 project, One of them is a plugin project.  Plugin project has a permission settings for using camera. I would like to create a info.plist in plugin project. My question is about merging two info.plist in my main iOS project in building time. My other similar question is for Android. I have searched much more in internet but I did not find anything about that. I am wondering is there any way to do this?

Thank you in advance.

**Comment by angelru** [comment]
@kerberosargos 

Maybe this can give you an idea, this is how I load google services for 2 environments:

iOS:
```
     <BundleResource Include = "GoogleService-Info-pro.plist" LogicalName = "GoogleService-Info.plist" Condition = "'$ (Configuration)' == 'Release'" />
     <BundleResource Include = "GoogleService-Info-dev.plist" LogicalName = "GoogleService-Info.plist" Condition = "'$ (Configuration)'! = 'Release'" />
```

Android:
```
   <ItemGroup Condition = "'$ (Configuration)'! = 'Release'">
     <GoogleServicesJson Include = "FirebaseConf \ google-services-dev.json">
       <LogicalName> FirebaseConf \ google-services.json </LogicalName>
     </GoogleServicesJson>
   </ItemGroup>
   <ItemGroup Condition = "'$ (Configuration)' == 'Release'">
     <GoogleServicesJson Include = "FirebaseConf \ google-services-pro.json">
       <LogicalName> FirebaseConf \ google-services.json </LogicalName>
     </GoogleServicesJson>
   </ItemGroup>
```

**Comment by kerberosargos** [comment]
@angelru Thank you for your response but I would like to merge 2 different settings files (info.plist or Android.manifest) into 1 file in project building time. I mean I don't want to use different file by mode

**Comment by kerberosargos** [comment]
@angelru please imagine that I have  two projects as **project-a** and **project-b**

info.plist of **project-a**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>MinimumOSVersion</key>
	<string>11.4</string>

</dict>
</plist>
```
info.plist of **project-b**

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSCameraUsageDescription</key>
	<string>This app needs camera permission</string>
</dict>
</plist>

```

final result should be as following

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>MinimumOSVersion</key>
	<string>11.4</string>

	<key>NSCameraUsageDescription</key>
	<string>This app needs camm</string>

	
</dict>
</plist>
```

**Comment by jfversluis** [comment]
I think @Redth gave you a hint on how to do it [on Twitter](https://twitter.com/KerberosArgos/status/1460579498878021639?s=20) I don't think an issue is the right place for this. He already mentioned to maybe [join the Discord](https://aka.ms/dotnet-discord) we have setup or create a discussion for it.

Thanks!

**Comment by kerberosargos** [comment]
Thank you @jfversluis. But I belive this not only my personel request. If somebody explains in this post or writes a blog article about this stiuation, I think so many xamarin lovers can benefit. Because of this I have created this post. Thank you anyway.

**Comment by jfversluis** [comment]
I think that is definitely true. However, GitHub issues are about bugs or feature requests for this product. Not to request any content or support on how to do things with this product :) Having that said, I still believe there will be value in answering this in one way or another, this is just not the right place.

**Comment by Redth** [comment]
Ok so this really depends on what you're trying to achieve.  I'm going to assume the more complicated scenario which is building a NuGet to distribute to others which needs to contain an Info.plist that gets merged into the app projects which consume the nuget package.  

First of all you'll need to create a .targets file with the name and path in your nupkg: `buildTransitive\Xamarin.iOS10\Your.Package.Id.targets` (you'll want this in `buildTransitive\net6.0-ios\Your.Package.Id.targets` for .NET 6) with the contents:

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <!-- For .NET 6 this item group is named just PartialAppManifest without the underscore -->
    <_PartialAppManifest Include="$(MSBuildThisFileDirectory)\Info.plist" />
  </ItemGroup>
</Project>
```

Then of course you need to include the `Info.plist` you want merged in your nuget package also in the `buildTransitive\Xamarin.iOS10\Info.plist` location.

This is all just MSBuild rules here, and you could just as easily use the `_PartialAppManifest` itemgroup to include partial manifests from other projects/locations/etc, the special thing in this example is using the rule where a .targets file with the name of your nuget package id, inside the buildTransitive location is automatically referenced by projects which consume that nuget package, and so the item is added to that itemgroup automatically for them.


Android can leverage the same approach for `AndroidManifest.xml`, except the item group is `AndroidManifest` (this approach also supports [android manifest merger rules](https://developer.android.com/studio/build/manage-manifests) which is super convenient.   Again, remember to put these files in the right location in your nupkg (ie: `buildTransitive/<TargetFramework>/*`).
