### ISSUE TITLE
Tabbar No Longer Appearing

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14895]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Tabbar-No-Longer-Appearing/1550321)._

---
With the latest update to Visual Studio Mac, the tabbar is not appearing on pre-existing Apps that use it (or is working only on certain pages in a very non-standard manner (for example, disappearing when scrollinng)).   I created a new app from the tabbed templates and the tabbar does not appear on the template app on startup either.   The problem is specific to iOS apps; the android apps work fine.   I would appreciate any thoughts or suggestions.

---
#### Feedback Bot on 10/11/2021, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Theresa Zhang[MSFT] on 10/13/2021, 00:58 AM: 

<p>Thanks for your feedback.<br>
I tried to reproduce this issue by creating Tabbed project(New -&gt; Multiplatform -&gt; App -&gt; Tabbed App) or using an existing tabbed project, but it works fine on our side.<br>
Could you provide a screenshot or screen recording for us to investigate this issue further?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### rsbepvb on 10/14/2021, 10:44 AM: 

(private comment, text removed)
#### rsbepvb on 10/14/2021, 10:47 AM: 

(private comment, text removed)
#### rsbepvb on 10/14/2021, 11:50 AM: 

<p>Here is a partial workaround.  I am seeing this problem reported elsewhere on various forums.</p>
<p>////WORKAROUND FOR iOS 15 bug – Xamarin Forms/iOS<br>
//A bug with iOS 15 results in the background color not being set on the main appshell nav and tabbar so we need to force it here<br>
var appearance = new UINavigationBarAppearance()<br>
{<br>
BackgroundColor = UIColor.FromRGB(150, 209, 255),<br>
ShadowColor = UIColor.FromRGB(150, 209, 255),<br>
};</p>
<pre><code>        UINavigationBar.Appearance.StandardAppearance = appearance;
        UINavigationBar.Appearance.ScrollEdgeAppearance = appearance;

        var appearance2 = new UITabBarAppearance()
        {
            BackgroundColor = UIColor.FromRGB(150, 209, 255),
            ShadowColor = UIColor.FromRGB(150, 209, 255),
        };

        UITabBar.Appearance.StandardAppearance = appearance2;
        UITabBar.Appearance.ScrollEdgeAppearance = appearance2;
        ///END OF WORKAROUND
</code></pre>

#### Feedback Bot on 10/14/2021, 11:36 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This is fixed in newer versions :)
