### ISSUE TITLE
[Bug] [5.0.0.2244] [Android] Interacting with a SwipeView inside a ScrollView on a TabbedPage with IsSwipePagingEnabled="false" re-enables page swiping

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Xamarin.Forms#14897]
### Description

Page Swiping on the TabbedPage on Android can be disabled by setting IsSwipePagingEnabled="false".
However this setting appears to be ignored after interacting with a SwipeView that is placed inside a ScrollView on one of the TabbedPage's child pages.
This issue is very similar to #13337, the only difference is the ScrollView.
The fix https://github.com/xamarin/Xamarin.Forms/pull/13404 is not working when the SwipeView is inside a ScrollView.

### Expected Behavior

TabbedPage page swiping should remain disabled

### Actual Behavior

TabbedPage page swiping is re-enabled

### Basic Information

- Version with issue: all, including 5.0.0.2244
- Platform Target Frameworks: android 12

### Reproduction Link

[TestSwipeFix.zip](https://github.com/xamarin/Xamarin.Forms/files/7549364/TestSwipeFix.zip)

**Comment by jfversluis** [comment]
Hey all, a PR (#14902) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by jasonboyda** [comment]
I must be missing something. I've upgraded to XF 5.0.0.2291 which should have resolved this issue, however regardless where the SwipeView is located in the UI (i.e. inside a ScrollView or as the parent), I am still seeing the bug of the IsSwipePageEnabled being re-enabled.

**Comment by jasonboyda** [comment]
> @jasonboyda did you test it with this fix before? If you could pour it into a repro sample that would definitely help!

@jfversluis I was not able to test prior to downloading the newest update to XF. Here is a sample repo which illustrates the problem on Android: https://github.com/jasonboyda/XF5-SwipeViewBugSample. I tried mimicking how it is used in my application. Hope this helps.

**Comment by AlleSchonWeg** [comment]
@jasonboyda 
You are using XF 5.0.0 Service Release 3 in your android project. 
`
<PackageReference Include="Xamarin.Forms" Version="5.0.0.2012" />`

Fix is in SR 7 and above.

**Comment by jfversluis** [comment]
Probably what @AlleSchonWeg mentioned then :)

**Comment by jasonboyda** [comment]
@AlleSchonWeg Good catch. Looks like when I upgraded through the Nuget Package Manager it only updated my Shared project reference. Thanks for everyone's help!
