### ISSUE TITLE
TimePickerRenderer is missing on WPF

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1489]
### Description
From #1488, we need to create the missing renderer  for TimePicker on WPF

**Comment by mohachouch** [comment]
A contributor on Xamarin Forms for WPF  @BradChase2011  told me he would develop a TimePicker. I'll see with him if it's still planned.

I also agree not to add multiple dependency.

**Comment by BradChase2011** [comment]
It is, I have the code for a simplistic on that we use for uwp and wpf.  I will make it a priority to check in.  Mohachouch, let's email about the best place for it.

**Comment by mohachouch** [comment]
@BradChase2011 If the TimePicker have don't use the WpfLightToolkit. I think the best is to create the control in the Xamarin.Forms.Platform.WPF project.

**Comment by rmarinho** [comment]
fixed by #1500
