### ISSUE TITLE
Xamarin NuGet package for Azure Communication Services

### ISSUE THREAD

**Issue by aodegov** [xamarin/Xamarin.Forms#14906]
## Summary
Xamarin NuGet package for Azure Communication Services

## Changes

We'd like to ask you about the opportunity to use Azure Communication Services with Xamarin / MAUI
with / through the appropriate NuGet package for Xamarin / MAUI.

## Intended Use Case
Nowadays a lot of community members strive to build mobile apps on MS stack such as Xamarin / MAUI
and communicate through the Azure Communication Services.
But unfortunately there is no such option as a NuGet package from MS as well we don't see any tutorials or docs about this.

___
Many thanks

**Comment by jfversluis** [comment]
That would be so cool to have! However I don't think this is the right place to ask. You might want to check the current status and possibly put in a request here: https://github.com/Azure/communication

**Comment by aodegov** [comment]
Thanks for the reply, @jfversluis 
As suggested I put request there: https://github.com/Azure/Communication/issues/426

--
Thanks

**Comment by MhAllan** [comment]
@jfversluis I believe here is the right place, they do provide .net library, but we need the video view and video player from MAUI side

**Comment by aodegov** [comment]
@jfversluis I'd like to inform you,
that [this issue ](https://github.com/Azure/Communication/issues/426)was closed without any understanding how it will be processed.
Is there any chance to communicate with Azure Communications Services Team in order to clarify the roadmap for this issue (and issues like this). 
Since community waits on solution more than a year.
Sorry for bothering with this again, we just don't see any activity from MS towards this direction.

Thank you.

**Comment by MhAllan** [comment]
@aodegov  try on MAUI issues, Xamarin most likely not going to add anything

**Comment by jfversluis** [comment]
@MhAllan that is correct, but like I stated earlier, this is not the right place to ask for this. I see your issue (@aodegov) has been migrated to the platform where feature requests are supposed to be for that product. There is not much you can do besides sharing the link to that issue to other people that might be interested in this feature. If more people upvote it, the more likely it will be implemented.

**Comment by aodegov** [comment]
Thanks for your replies @jfversluis 
Will think how to move forward......

**Comment by aodegov** [comment]
@MhAllan , thanks for suggestion.
Already there: [3393](https://github.com/dotnet/maui/issues/3393) and [3394](https://github.com/dotnet/maui/issues/3394).
Created ~month ago.
You can somehow tag or like them, sake of promote in MAUI boards.
