### ISSUE TITLE
[Bug] Loading embedded font causes the app to crash on iOS after upgrade to Visual Studio 16.11.7 and 17.0.1, еmbedded images are not loaded anymore on iOS

### ISSUE THREAD

**Issue by vg12345** [xamarin/Xamarin.Forms#14905]
Application that uses embedded font crashes on iOS

Reproduced on iOS 14.8.1
After upgrade of Visual Studio 2019 from 16.11.6 to 16.11.7
After upgrade of Visual Studio 2022 from 17.0.0 to 17.0.1

Xamarin Forms 5.0.0.2196 (same after upgrade to 5.0.0.2244)

Attached: App5.zip - the most simple application that reproduces the problem
[App5.zip](https://github.com/xamarin/Xamarin.Forms/files/7563932/App5.zip)

**Update:** 
1. Embedded images are not loaded anymore on iOS!
2. Looks like FileStream does not load images correctly too.

Attached: App6.zip. Reproduces the problem with embedded images on iOS. (Successfully loads on Android and UWP, but fails on iOS). 
[App6.zip](https://github.com/xamarin/Xamarin.Forms/files/7609001/App6.zip)
Important: you must build it and deploy to iPhone with Visual Studio 2022 version **17.0.1** to reproduce the problem!

**Update:**
Same problem on Visual Studio 2022 version **17.0.2**

================================================================

	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x00022>
	  at Foundation.NSMutableData:AppendBytes <0x00054>

	  at Foundation.NSData:FromStream <0x0010c>
	  at Xamarin.Forms.Platform.iOS.EmbeddedFontLoader:LoadFont <0x00016>
	  at Xamarin.Forms.Internals.FontRegistrar:HasFont <0x0013e>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:CleanseFontName <0x0000c>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:_ToNativeFont <0x00124>
	  at System.Func`4:invoke_TResult_T1_T2_T3 <0x000ae>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToNativeFont <0x000b4>

	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToNativeFont <0x0005c>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToUIFont <0x0000a>
	  at Xamarin.Forms.Platform.iOS.LabelRenderer:UpdateFont <0x00082>
	  at Xamarin.Forms.Platform.iOS.LabelRenderer:OnElementChanged <0x000d8>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x002a2>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>

	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x00228>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:ViewDidLoad <0x0010c>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0008e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:IntPtr_objc_msgSendSuper <0x0001a>

	  at UIKit.UIViewController:get_View <0x0006c>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:get_NativeView <0x00016>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:SetElement <0x00096>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.Platform:AddChild <0x00052>
	  at Xamarin.Forms.Platform.iOS.Platform:WillAppear <0x00086>
	  at Xamarin.Forms.Platform.iOS.PlatformRenderer:ViewWillAppear <0x00040>
	  at <Module>:runtime_invoke_direct_void__this___bool <0x0009e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend <0x0001a>
	  at UIKit.UIWindow:MakeKeyAndVisible <0x00038>
	  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate:SetMainPage <0x00022>
	  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate:FinishedLaunching <0x0006e>
	  at App5.iOS.AppDelegate:FinishedLaunching <0x00032>
	  at <Module>:runtime_invoke_direct_bool__this___UIApplication_NSDictionary <0x000c8>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x000b2>
	  at App5.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.iOS.HotRestart.Application:Run <0x001fa>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x0005a>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>

=================================================================

The app has been terminated.

**Comment by angelru** [comment]
Right now I can't debug apps on physical iPhone. I get that error and this one that I posted here.
https://developercommunity.visualstudio.com/t/iPhone-iOS-151-physical-debug/1572333

Everything works fine in the emulator.

**Comment by vg12345** [comment]
**Update:** 
1. Embedded images are not loaded anymore on iOS!
2. Looks like FileStream does not load images correctly on iOS.

**Comment by royeagle** [comment]
I have the same issue with embedded images are not loaded on iOS. Please fix.

**Comment by andfgiu** [comment]
I can reproduce the same issue on an iPhone with iOS 15.0.2.

Using VS 2022 17.0.1

On the output window I get almost the same:

`
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x00022>
	  at Foundation.NSMutableData:AppendBytes <0x00054>
	  at Foundation.NSData:FromStream <0x0010c>
	  at Xamarin.Forms.Platform.iOS.EmbeddedFontLoader:LoadFont <0x00016>
	  at Xamarin.Forms.Internals.FontRegistrar:HasFont <0x0013e>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:CleanseFontName <0x0000c>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:_ToNativeFont <0x00124>
	  at System.Func`4:invoke_TResult_T1_T2_T3 <0x000ae>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToNativeFont <0x000b4>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToNativeFont <0x0005c>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToUIFont <0x0000a>
	  at Xamarin.Forms.Platform.iOS.LabelRender
`

**Comment by David-Hartman-emclient** [comment]
I have a similar problem.

```

 at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x00022>
	  at Foundation.NSMutableData:AppendBytes <0x00054>
	  at Foundation.NSData:FromStream <0x0010c>
	  at <LoadImageAsync>d__1:MoveNext <0x00160>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.StreamImagesourceHandler:LoadImageAsync <0x00062>
	  at <GetNativeImageAsync>d__10:MoveNext <0x000c4>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageElementManager:GetNativeImageAsync <0x00052>
	  at <SetImage>d__8:MoveNext <0x00530>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageElementManager:SetImage <0x0005c>
	  at <SetImage>d__6:MoveNext <0x00034>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageRenderer:SetImage <0x0004e>
```
```

**Comment by sblom** [comment]
Happening here, too. Succeeds when I'm debugging an iPhone connected to my Mac, but fails when I'm debugging an iPhone directly connected to Windows.

**Comment by andres-fg** [comment]
Does anybody know a workaround for this?

**Comment by jsuarezruiz** [comment]
Tried https://github.com/xamarin/Xamarin.Forms/files/7563932/App5.zip in iPhone 8 with iOS 15.1 and iPad Mini with iPadOS 15.1 and cannot reproduce, could someone share a sample where reproduce the issue?

**Comment by vg12345** [comment]
Did you try to build and upload it with the **latest** version of Visual Studio 2022 (17.0.1)?

**Comment by vg12345** [comment]
In addition:

Attached: App6.zip. Reproduces the problem with embedded images on iOS. (Successfully loads on Android and UWP, but fails on iOS). 
Important: you must build it and deploy to iPhone with Visual Studio 2022 version **17.0.1** to reproduce the problem!

[App6.zip](https://github.com/xamarin/Xamarin.Forms/files/7609006/App6.zip)

**Comment by EdwinLans** [comment]
Same problem here. After the update from Visual Studio 2022 17.0.0. to 17.0.1 the app crashes on my iOS device - Iphone. Same error as vg12345

**Comment by snice1981** [comment]
Exactly same problem here.  After update of VS2019 and VS2022. Same code works well on ios simulator and also on another machine with older VS2019&VS2022

**Comment by vg12345** [comment]
**Update:**
Same problem on Visual Studio 2022 version **17.0.2**

**Comment by vg12345** [comment]
Looks like more generic problem in **Foundation.NSData:FromStream**

[https://developercommunity.visualstudio.com/t/xamarin-ios-in-visual-studio-2022-problem-with-com/1590471]

**Comment by royeagle** [comment]
Please fix!!! Customer is waiting!!!!!!

**Comment by angelru** [comment]
they are investigating the problem
https://developercommunity.visualstudio.com/t/iphone-ios-151-physical-debug/1572333

**Comment by jfversluis** [comment]
Seems like a problem that is not related directly to Xamarin.Forms then. Please follow the linked support ticket, thanks :)

**Comment by vg12345** [comment]
Seems like nobody in Xamarin team wants even try to debug the attached application to ensure that the problem is not really in Xamarin.iOS platform.

**Comment by jfversluis** [comment]
> Seems like nobody in Xamarin team wants even try to debug the attached application to ensure that the problem is not really in Xamarin.iOS platform.

There are a couple of responses that point out we did, not sure what you're trying to achieve here?

**Comment by vg12345** [comment]
iOS applications crash if using embedded resources.
The crash happens in Xamarin Forms code.
Is it possible that recent IDE changes just showed some unknown bug in Xamarin?
The problem exists about a month. Did somebody investigate this on Xamarin side?

**Comment by jfversluis** [comment]
You say you are using Visual Studio 17.0.1 and are deploying to an iPhone. That means you are using what is called [Hot Restart](https://docs.microsoft.com/xamarin/xamarin-forms/deploy-test/hot-restart). The way Hot Restart works is that there is a prebuilt iOS app, that will dynamically load all of the Xamarin.Forms content, both from us on the SDK side as well as the code you write, inside of it. Including all the embedded resources and everything that is needed to run the app.

To be honest, I don't know how this piece of magic exactly works, I do know that we do not "own" the prebuilt iOS app that is provided as well as the infrastructure that is used to actually deploy and compile and do magic on you iOS device from Windows. So yes, you are using Xamarin.Forms, I totally understand how this must look like a Xamarin or Xamarin.Forms bug to you, but it most likely isn't.

> iOS applications crash if using embedded resources.
If this is true, then the right place to report it would be the xamarin-macios repository since that is Xamarin.iOS, we build on top of that

> The crash happens in Xamarin Forms code.
How can that be if it also occurs with Xamarin.iOS projects?

> Is it possible that recent IDE changes just showed some unknown bug in Xamarin?
Not likely because of how everything works when using Hot Restart, see above

> The problem exists about a month. Did somebody investigate this on Xamarin side?
You can see that I linked a good number of issues on the Xamarin.Forms repo as well as from the Developer Community Portal, so yes people are busy looking into this.

I understand that you might be frustrated by this not working and it not being resolved quickly enough for you, but we're here to make things work. Not trying to close this as "not my problem", I hope that is clear from taking the time to respond to you in detail about how all this is going down.

Just to make sure one more time, I pulled down your App6 sample, ran it on a iPhone XS and an internal Visual Studio version 17.1.0 and I see that the image is not loading there, but with a different stack trace than yours. I'm installing VS2019 as we speak to see if that makes a difference. Do I understand correctly that the problem was not in 16.11.6 but the problem is in 16.11.7?

**Comment by vg12345** [comment]
> Do I understand correctly that the problem was not in 16.11.6 but the problem is in 16.11.7?

The last version without the problem are:
16.11.6 (VS 2019)
17.0.0 (VS 2022)

All later version contain the problem.
Unfortunately, there is no any option to return to one of these "normal" versions for community edition.
The installations of older versions exist for professional and enterprise only

**Comment by jfversluis** [comment]
Unfortunately I can't use VS2019 with iOS 15 it seems. Trying to see if I can somehow get my hands on Vs 17.0.0 to try. 

But if this indeed has something to do with NSData.FromStream then this is still not on us. Again; not to say: not our problem, just so I know where to route this to so this can be resolved.

@dalexsoto does any of this mean something to you?

**Comment by vg12345** [comment]
Of cause, I have no idea which team is responsible for some specified part of code.
But. If there is very serios problem that prevents from people to develop on iOS with your platform, you can at least ensure that the problem is definitely in **Foundation.NSData:FromStream** (or maybe something else) and involve the relevant team inside Microsoft. 
Did your team investigate this?
Can you approve that the problem is in Foundation.NSData:FromStream or reject this?
Not just waiting a month and close all relevant open issues as "not our problem"

**Comment by jfversluis** [comment]
I'm not sure what you want from me here? That is exactly what I am trying to do right now? But my willingness to help is kind of draining if I keep getting negative comments like this to be honest. We're trying to achieve the same here.

**Comment by vg12345** [comment]
I'm not trying to offend you and my notes are not pointed personally to you, So, please, don't take it personally.
This is the issue about serious problem related to Xamarin development and it is reported to Xamarin development team.
I really appreciate your willingness to help but I think that fixing this problem is also the interest of Xamarin team and not just gesture of goodwill to some developer.

**Comment by killer-frog** [comment]
I had this issue and found that I had some old mtouch arguments (`--interpreter --optimize=experimental-xforms-product-type`) still.  Removed these and it worked fine.

**Comment by jfversluis** [comment]
Oh that is great information, thank you!
