### ISSUE TITLE
IndicatorView.ItemsSourceBy Error

### ISSUE THREAD

**Issue by saklanmazozgur** [xamarin/Xamarin.Forms#14914]
Hello, 
I am using IndicatorView in my project. The `IndicatorView.ItemsSourceBy` property works in Xamarin version 4.4.0.9912 but does not work in the latest version 5.0.0.2244. I am encountering the following error.

`The attachable property 'ItemsSourceBy' was not found in type 'IndicatorView'.`

**Comment by saklanmazozgur** [comment]
#9332 The solution to the problem is here. It now uses CarouselView's IndicatorView definition instead of defining IndicatorView.ItemSourceBy.

**Comment by jsuarezruiz** [comment]
The property has changed between that versions. Now you should use the `CarouselView.IndicatorView` property.
