### ISSUE TITLE
[Bug] CollectionView's empty view crashes on iOS 9

### ISSUE THREAD

**Issue by reid-kirkpatrick** [xamarin/Xamarin.Forms#14916]
### Description

CollectionView's empty view crashes on iOS 9: [UICollectionView effectiveUserInterfaceLayoutDirection]: unrecognized selector sent to instance

[This](https://github.com/xamarin/Xamarin.Forms/blob/64c972dcae5f988c9f2bd64ff713030e769c9589/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewController.cs#L495) is the culprit

### Steps to Reproduce

1. Give a CollectionView an EmptyView
2. Run on iOS 9

### Expected Behavior

Empty view is shown

### Actual Behavior

App crashes

### Basic Information

- Version with issue: Latest
- Last known good version: Looks like this code was submitted Dec 2020
- Affected Devices: iOS 9

### Reproduction Link

https://github.com/reid-kirkpatrick/FormsCollectionViewCrash.git

### Workaround

Don't use an empty view, otherwise there isn't one that I know of

**Comment by jfversluis** [comment]
Thanks for the report! I was under the impression that we supported iOS 10+, but on the Docs it mentions 9+. I'll see if we can get an easy fix for this :)

**Comment by jfversluis** [comment]
@reid-kirkpatrick, a PR (#14925) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by reid-kirkpatrick** [comment]
> @reid-kirkpatrick, a PR (#14925) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.
> 
> Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂
> 
> Thanks!

Yep, that fixed it! We don't support rtl, so I can't really test anything related. Thanks so much for the quick work!

**Comment by jfversluis** [comment]
Perfect, thanks for checking this out!
