### ISSUE TITLE
Android - custom NavigationPageRenderer - System.InvalidCastException has been thrown

### ISSUE THREAD

**Issue by stepanic** [xamarin/Xamarin.Forms#1492]
### Description

I want to create custom NavigationPageRenderer for Android but I get exception `System.InvalidCastException has been thrown`, my implementation is based on this sample https://github.com/xamarindevelopervietnam/NavigationAnimationXF/blob/master/NavigationAnimationXF/NavigationAnimationXF/NavigationAnimationXF.Droid/SourceCode/AnimationNavigationRenderer.cs

Xamarin.Forms version is latest stable `2.5.0.121934`

### Steps to Reproduce

Create this custom renderer

```
using System;
using Android.App;
using Android.Content;
using MRRFEU.Droid.Renderers;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using Xamarin.Forms.Platform.Android.AppCompat;

[assembly: ExportRenderer(typeof(NavigationPage), typeof(CustomAnimationNavigationRenderer))]
namespace MRRFEU.Droid.Renderers
{
    public class CustomAnimationNavigationRenderer : NavigationPageRenderer
    {

        public CustomAnimationNavigationRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<NavigationPage> e)
        {
            base.OnElementChanged(e);
        }

        //protected virtual void SetupPageTransition(FragmentTransaction transaction, bool isPush)
        //{
        //    if (isPush)
        //        transaction.SetTransition((int)FragmentTransit.FragmentOpen);
        //    else
        //        transaction.SetTransition((int)FragmentTransit.FragmentClose);
        //}

    }
}
```

### Expected Behavior

To start application without exception

### Actual Behavior

Application is not able to start

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio for Mac 7.3.2 (build 12)
- Platform Target Frameworks: 
  - Android: API level 26
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![screen shot 2018-01-03 at 16 15 49](https://user-images.githubusercontent.com/315282/34526045-6bbcb24a-f0a1-11e7-85c4-da49b73a95b6.png)

**Comment by hartez** [comment]
I've tried creating a reproduction of this using your custom renderer code, but the application starts up just fine. Could you attach a minimal repro project demonstrating the issue? It's possible I'm missing a detail somewhere. 
Thanks!

**Comment by jassmith** [comment]
Closed due to inactivity

**Comment by manikandansai** [comment]
It is valid issue. I'm also facing the same issue

**Comment by Daxton47** [comment]
I have the same issue right now. Seems to throw the System.InvalidCastException when it hits the renderer's constructor in the "shared" or .net project. Strangely, I built a new test solution and the renderer works fine. Same code and everything! I have matching Xamarin versions in both solutions. Very frustrating!!
