### ISSUE TITLE
cameraView I want to do face recognition. Can't I hide and redraw the image?

### ISSUE THREAD

**Issue by bbhxwl** [xamarin/Xamarin.Forms#14931]
If cameraview is set to display, call shutter to get the picture. But there's no way to reset the screen. If I set cameraview to hide, I can't get the picture by calling shutter. No response. I want to get pictures in real time, face recognition and redraw the image

**Comment by jfversluis** [comment]
CameraView is not part of Xamarin.Forms, this is in the Xamarin Community Toolkit. Please open an issue there.

Although I'm not sure what you mean, so you might want to add a bit more clearer description :) thanks!
