### ISSUE TITLE
[Bug][iOS]  Unable to change iOS 15 navigation bar back button color in Shell

### ISSUE THREAD

**Issue by GeethuVinod95** [xamarin/Xamarin.Forms#14948]
### Description
I am trying to change the color of back button in iOS 15 using platform specific code in ShellRenderer. In NavigationPage we can set it by using BarTextColor, but in Shell i am unable to.

   ```
protected override IShellSectionRenderer CreateShellSectionRenderer(ShellSection shellSection)
        {
            var renderer = base.CreateShellSectionRenderer(shellSection);
            if (renderer != null)
            {
                var appearance = new UINavigationBarAppearance();
                appearance.ConfigureWithOpaqueBackground();
                Xamarin.Forms.Application.Current.Resources.TryGetValue("NavBarTextColor", out var navBarTextColor);
                appearance.TitleTextAttributes = new UIStringAttributes() { ForegroundColor = ((Color)navBarTextColor).ToUIColor()};
                Xamarin.Forms.Application.Current.Resources.TryGetValue("PrimaryButtonColor", out var primaryButtonColor);
                appearance.BackgroundColor = ((Color)primaryButtonColor).ToUIColor(); 
                UINavigationBar.Appearance.TintColor = ((Color)navBarTextColor).ToUIColor();
                UINavigationBar.Appearance.StandardAppearance = appearance;
                UINavigationBar.Appearance.ScrollEdgeAppearance = appearance;
            }
            return renderer;
        }
```

### Steps to Reproduce

Visual studio Mac: 8.10.9 (build 3)
macOS Big Sur (intel)
Xamarin Forms : 5.0.0.2083

1. Created new shell template project from Visual Studio
2. Create a CustomShellRenderer inheriting the base class ShellRenderer and add CreateShellSectionRenderer(code above)
3. Update navbar titletext, background  and tint color.

### Expected Behavior
The navigation bar background, title text and backbutton color should change accordingly

### Actual Behavior
Navigation bar background and title text color is getting changed, but back button still shows up in white color.

Anyone else facing this issue? Any fix/workaround would help.
Thanks!

**Comment by tanvirgeek** [comment]
Facing the same issue

**Comment by volcano619** [comment]
any update on this @jsuarezruiz

**Comment by GeethuVinod95** [comment]
I found the solution. Instead of adding those lines of code in CreateShellSectionRenderer, add it to SetAppearance(UINavigationController controller, ShellAppearance appearance). This worked for me.

` public void SetAppearance(UINavigationController controller, ShellAppearance appearance)
        {
            var navBar = controller.NavigationBar;
            var navigationBarAppearance = new UINavigationBarAppearance();
            navigationBarAppearance.ConfigureWithOpaqueBackground();

            Xamarin.Forms.Application.Current.Resources.TryGetValue("NavBarTextColor", out var navBarTextColor);
            navigationBarAppearance.TitleTextAttributes = new UIStringAttributes() { ForegroundColor = ((Color)navBarTextColor).ToUIColor() };

            Xamarin.Forms.Application.Current.Resources.TryGetValue("ContentBackgroundColor", out var primaryButtonColor);
            navigationBarAppearance.BackgroundColor = ((Color)primaryButtonColor).ToUIColor();

            UINavigationBar.Appearance.TintColor = ((Color)navBarTextColor).ToUIColor();
            UINavigationBar.Appearance.StandardAppearance = navigationBarAppearance;
            UINavigationBar.Appearance.ScrollEdgeAppearance = navigationBarAppearance;

            navBar.ScrollEdgeAppearance = navBar.StandardAppearance = navigationBarAppearance;

            controller.NavigationBar.TintColor = ((Color)navBarTextColor).ToUIColor();
        }`
