### ISSUE TITLE
shell TabBarForegroundColor not working

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14947]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/shell-TabBarForegroundColor-not-working/1582189)._

---
Setting the Shell.TabBarForegroundColor, TabBarUnselectedColor has stopped working.  The text and buttons are impossible to see.

If you create a sample XF app, run it on an iPad, you’ll see the problem.  

This seemed to happen when I upgraded to the latest version of xcode.

I’ve included a sample screen shot and the project file

---
#### Feedback Bot on 11/14/2021, 10:22 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 11/17/2021, 04:06 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could you try with the latest version again?. This should be fixed by https://github.com/xamarin/Xamarin.Forms/pull/14649

**Comment by jfversluis** [comment]
No response to our request for more info, closing this for now.
