### ISSUE TITLE
[Bug]  Xamarin.Android.D8.targets(79, 5): java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

### ISSUE THREAD

**Issue by TheWoakus** [xamarin/Xamarin.Forms#14945]
### Description
When i try to build my Xamarin forms app for debug i get the following error:

Xamarin.Android.D8.targets(79, 5): java.lang.ArrayIndexOutOfBoundsException :  Index 4 out of bounds for length 4

So far i've tried every combination of Code Shrinker, Dex Compiler and Multi-Dex, but i still get the same error. My own research on the issue have not yielded any results as it seems that this is not a common issue. Any ideas?

### Steps to Reproduce
1. Start debugging

### Expected Behavior
Successful build

### Actual Behavior
Build failure

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: v11.0
  - Android: 11.0 
- NuGet Packages:
  - Acr.UserDialogs/7.1.0.514
  - FreshMvvm/4.0.1
  - Microsoft.AppCenter.Analytics/4.3.0
  - Microsoft.AppCenter.Crashes/4.3.0
  - Plugin.CurrentActivity/2.1.0.4
  - Plugin.Fingerprint/1.4.9
  - Plugin.Permissions/6.0.1
  - Xam.Plugin.Media/5.0.1
  - Xamarin.Android.Support.v4/28.0.0.3
  - Xamarin.AndroidX.AppCompat.Resources/1.1.0.1
  - Xamarin.AndroidX.AppCompat/1.3.1.1
  - Xamarin.AndroidX.Core/1.6.0.1
  - Xamarin.AndroidX.Legacy.Support.V4/1.0.0.8
  - Xamarin.AndroidX.Lifecycle.LiveData/2.3.1.1
  - Xamarin.AndroidX.Migration/1.0.8
  - Xamarin.AndroidX.RecyclerView/1.2.1.1
  - Xamarin.CommunityToolkit/1.3.0-pre2
  - Xamarin.Essentials/1.7.0
  - Xamarin.FFImageLoading.Forms/2.4.11.982
  - Xamarin.Forms.DebugRainbows/1.1.4
  - Xamarin.Forms/5.0.0.2083

- Affected Devices:
  - API 30 and API 31 Emulator

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
JetBrains Rider 2021.3 EAP 10
Build #RD-213.5744.263, built on November 30, 2021
Rider EAP User
Expiration date: December 30, 2021
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
.NET 6.0.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    rdclient.asyncActions=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    com.jetbrains.rider.android (213.5744.263)

```

</details>

### Build Logs

[binaryLogFile.binlog.zip](https://github.com/xamarin/Xamarin.Forms/files/7640420/binaryLogFile.binlog.zip)

**Comment by TheWoakus** [comment]
It is not clear to us what fixed this for us, but it most likely happened due to some package misalignments/missing support packages.

**Comment by wegascee** [comment]
Perhaps related to this issue (https://github.com/xamarin/xamarin-android/issues/6632)?
