### ISSUE TITLE
[Feature Request] Ability to change page animations

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1494]
### Summary
Right now there isn't a way to change how the page animates to a new page in forms, this would be nice to have.

### API Changes
Not really sure how this should look, maybe something like it is discussed [here](https://forums.xamarin.com/discussion/18818/custom-page-transitions-with-xamarin-forms/p1).

```
PushAsync(Page page, Animation animation)
PushModalAsync(Page page, Animation animation)
```

And then maybe Animation is an enum like this:

```
    public enum Animation
    {
        FromTopToBottom,
        FromBottomToTop,
        FromLeftToRight,
    }
```

### Intended Use Case
To have control over what animation is done when a new page is pushed.
Note that this has 509 votes on the user voice [site](https://xamarin.uservoice.com/forums/258559-xamarin-forms-suggestions/suggestions/6289977-control-the-animation-when-navigation-pages) as well.

**Comment by jfversluis** [comment]
Thanks so much for this proposal! Unfortunately, this won't make its way into Forms anymore. If you're reading this and you still would love to see this in .NET MAUI, make sure to see if there is an issue open for it already and if not, open one with as much detail as you can.

I will also label this appropriately so we can consider this for .NET MAUI.

Thanks!
