### ISSUE TITLE
 Cannot remove an observer <CustomEntryRenderer 0x11506ede0> for the key path "sublayers" from <CALayer 0x282b09620> because it is not registered as an observer.[Bug] 

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [xamarin/Xamarin.Forms#14940]
Fix Entry crashing on iOS < 14 

Name: SIGABRT: Cannot remove an observer <CustomEntryRenderer 0x11506ede0> for the key path "sublayers" from <CALayer 0x282b09620> because it is not registered as an observer.

This issue occurred newly in appcenter we are updating xamarin forms : 5.0.0.2196 released 

Steps to Reproduce
Expected Behavior
Application should not crash.

Actual Behavior
Crashes with the reported error.

Basic Information
Version with issue: Xamarin.Forms 5.0.0.2196 (SR6)
Platform Target Frameworks
iOS: 15
NuGet Packages: Xamarin.Forms 5.0.0.2196 (SR6)
Affected Devices:  Iphone 12.5.5,11.4.1, 13.1.2

Cannot able to recreate this issue

**Comment by jfversluis** [comment]
This issue has been reported many times before, it is fixed with the next release
