### ISSUE TITLE
Embedded resources not showing on Xam Forms apps on iOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#14955]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Embedded-resources-not-showing-on-Xam-Fo/1592160)._

---
[severity:Other]
All embedded resources seem to not show on iOS in release mode. It looks like Apple has changed something that prevents them showing in release mode. It is possible this will also prevent apps being accepted to the store. It does not affect Android

https://issueexplorer.com/issue/airbnb/lottie-ios/1324?fbclid=IwAR1Se1IfzwYfId7weqsUGs2qUdSNK2C5GYaet27PbeAstaJvOMfyOCDksyM - shows the issue and a fix, but this fix is not ideal

This may also impact on .NET MAUI

---
#### Feedback Bot on 11/22/2021, 10:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Paul Johnson on 11/29/2021, 06:56 AM: 

<p>This is affecting all embedded resources held in the forms section</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Seems like this is another ticket: https://developercommunity.visualstudio.com/t/iphone-ios-151-physical-debug/1572333 which points out it seems to be something in VS or another underlaying framework and not so much Xamarin.Forms. Please follow up in the linked ticket. Thanks!
