### ISSUE TITLE
[Bug] [UWP] [Shell] Tab icon not working with FontImageSource

### ISSUE THREAD

**Issue by FrozDark** [xamarin/Xamarin.Forms#14959]
### Description
When using FontImageSource for the tab bar icon in the shell it shows empty square like no icon found
If I do it to FlyoutItem it works as everywhere in the project

### Steps to Reproduce

1. Create shell content with tab bar
2. Set FontImageSource with the custom fonts to the Tab.Icon

### Expected Behavior
Icon to be shown

### Actual Behavior
Empty square shown

### Basic Information
I've created content as follow
```
<FlyoutItem Title="First item">
       // Works
        <FlyoutItem.Icon>
            <FontImageSource FontFamily="MD" Glyph="{x:Static fi:MaterialDesignIcons.Sitemap}"/>
        </FlyoutItem.Icon>

        <Tab Title="First tab">
           // Not working
            <Tab.Icon>
                <FontImageSource FontFamily="MD" Glyph="{x:Static fi:MaterialDesignIcons.Sitemap}" Size="100"/>
            </Tab.Icon>

            <ShellContent Route="OrdersPage" ContentTemplate="{DataTemplate local:OrdersPage}"/>
        </Tab>
    </FlyoutItem>
```

- Version with issue: 5.0.0.2244
- Last known good version: None
- Platform Target Frameworks: 
  - UWP:  19041

### Screenshots
![1](https://user-images.githubusercontent.com/6670150/144757987-583bd8f0-2c08-4c7c-90b7-79019d276b4b.jpg)
![2](https://user-images.githubusercontent.com/6670150/144757990-459324e4-3d2a-4a56-bed0-ff0864935dd5.jpg)

### Workaround
As a workaround create 2 classes in uwp specific platform
First inherits from ShellRenderer (Don't forget to export)
```
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using SomeMyProject.UWP;

[assembly: ExportRenderer(typeof(Shell), typeof(ShellRendererEx))]
namespace SomeMyProject.UWP
{
    public class ShellRendererEx : ShellRenderer
    {
        public override ShellItemRenderer CreateShellItemRenderer()
        {
            return new ShellItemRendererEx(this);
        }
    }
}
```

Second inherits from ShellItemRenderer as below

```
using System;
using System.Collections.Specialized;
using System.Linq;
using System.Threading.Tasks;
using Windows.UI.Xaml.Controls;
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using UwpGrid = Windows.UI.Xaml.Controls.Grid;

namespace SomeMyProject.UWP
{
    public class ShellItemRendererEx : ShellItemRenderer
    {
		public ShellItemRendererEx(ShellRenderer shellContext) : base(shellContext)
        {
        }

        protected override void OnShellItemsChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            base.OnShellItemsChanged(sender, e);
            UpdateBottomBar();
        }

        protected override void OnShellSectionChanged(ShellSection oldSection, ShellSection newSection)
        {
            base.OnShellSectionChanged(oldSection, newSection);

            Task.Delay(1).ContinueWith(async (t) =>
            {
				await Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal, () => 
				{
					UpdateBottomBar();
				});
            });
        }

        private void UpdateBottomBar()
		{
			Border border = Children.OfType<Border>().FirstOrDefault(c => GetRow(c) == 2);
			if (border is null)
            {
				return;
            }
			if (!(border.Child is UwpGrid grid))
			{
				return;
			}

            foreach (AppBarButton btn in grid.Children)
            {
                if (btn.Icon is FontIcon fontIcon)
                {
                    fontIcon.FontFamily = fontIcon.FontFamily.Source.ToFontFamily();
                }
            }
		}
    }
}
```

**Comment by jfversluis** [comment]
Would you be able to attach a small reproduction sample that demonstrates this issue?

**Comment by FrozDark** [comment]
Sorry didn't think that it is necessary

Here it you go

[ShellTabIconRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/7674379/ShellTabIconRepro.zip)

btw tested on Android and it works well

**Comment by jfversluis** [comment]
> Sorry didn't think that it is necessary

It always helps! Thanks for adding it

**Comment by jfversluis** [comment]
It seems that the font alias isn't working. I faintly recall this was an issue on UWP anyway... As a workaround you should be able to use the full font name, e.g. `<FontImageSource FontFamily="Material Design Icons" Glyph="{x:Static fi:MaterialDesignIcons.AlarmSnooze}"/>`

**Comment by lancelotdelamare** [comment]
@jfversluis : can you expand on
>It seems that the font alias isn't working

Is is specific to `<Tab.Icon>`? It appears that font aliases do work sometimes, like on the **Flyout** menu (see `Sitemap` screen shot)

Would you consider posting a fixed version of `ShellTabIconRepro.zip` where you demonstrate that workaround, specifically that using `FontFamily="materialdesignicons"` is performing properly on **UWP**? (using font name instead of alias _does work_ on **Android**) 

I can't seem to get it right, and am still experiencing the very issue described by @FrozDark as reported on Dec 5, 2021.
- Xamarin.Forms 5.0.0.2291
- Microsoft.NETCore.U 6.2.13
- NETStandard.Library 2.0.3
- Xamarin.Essentials 1.7.0.

**Comment by Nk54** [comment]
I can add that the code
`
    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate startUp:HomePage}"
        Route="HomePage">
        <ShellContent.Icon>
            <FontImageSource FontFamily="FAS" Glyph="&#xf015;" />
        </ShellContent.Icon>
    </ShellContent>
`

displays the font on Windows but not on Android (couldn't test on iOS as the Shell control crash on navigated to)

Here is a picture of the bug (ps : the font works well on a label on Android. Thus, it's not a problem related to a bad config a of the font in "AppBuilder".

![image](https://user-images.githubusercontent.com/13755220/165000135-a6fbe18b-6ac9-4d6d-b292-b3d4f876cc6b.png)
![image](https://user-images.githubusercontent.com/13755220/165000150-09e36a24-d9b2-4759-8f20-3016d5ab4641.png)

**Comment by FrozDark** [comment]
Added a workaround until PR is commited
