### ISSUE TITLE
[Forms] Element generates the drop gesture

### ISSUE THREAD

**Issue by dothanhbinh41** [xamarin/Xamarin.Forms#14950]
## Summary
In DropGestureRecognizer, when Drop, DragOver will call event Drop(object sender, DropEventArgs e) but  sender is DropGestureRecognizer. I think the sender is the one with this gesture.

## API Changes
in Xamarin.Forms.Core/DragAndDrop/DropGestureRecognizer.cs
change public async Task SendDrop(DropEventArgs args)
to public async Task SendDrop( View view ,DropEventArgs args) // view is sender

In DragAndDropGestureHandler  
when call SendDrop pass view to function.

**Comment by jfversluis** [comment]
Unfortunately we're not going to add any more features to Xamarin.Forms anymore, we are maintaining this for a while longer, but new features will go into .NET MAUI. Please open a feature request there, thanks!
