### ISSUE TITLE
iOS Crash on App Start

### ISSUE THREAD

**Issue by davidbauer2** [xamarin/Xamarin.Forms#14951]
### **Description**

We have a user that is unable to open our app. They have uninstalled, re-installed, restarted their phone and updated their phone to iOS 15.1 with no luck getting it to start. We have tried multiple different versions for them as well. They have provided the crash log which is shown below, it is the same each time it crashes for them. 

The device they are having an issue on is a iPhone XR running 15.1. They are able to open the app on their iPad and spouses iphone without issues.

### **Steps to Reproduce**

Unfortunately we are not able to get the issue to reproduce on any of our devices or simulator/emulators.

### **Expected Behavior**

App to start up without crashing

### **Actual Behavior**

App crashing on startup.

Date/Time:       2021-12-03T15:19:03.214Z
Launch Time:     2021-12-03T02:44:59.014Z
OS Version:      iPhone OS 15.1 (19B74)
Report Version:  104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000 at 
Crashed Thread:  0

Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00000001b84d0964 __pthread_kill + 8
1   libsystem_pthread.dylib              0x00000001f1930378 pthread_kill + 264
2   libsystem_c.dylib                    0x000000018c51e420 __abort + 124
3   libsystem_c.dylib                    0x000000018c4c6f5c abort + 172
4   OurAppiOS                            0x00000001054990a4 xamarin_unhandled_exception_handler (runtime.m:1153)
5   OurAppiOS                            0x000000010535dff8 mono_invoke_unhandled_exception_hook (exception.c:1265)
6   OurAppiOS                            0x00000001052f2dc4 mono_handle_exception_internal (mini-exceptions.c:2782)
7   OurAppiOS                            0x00000001052f37a4 mono_resume_unwind (mini-exceptions.c:3523)
8   OurAppiOS                            0x00000001052e76e4 mono_arm_resume_unwind (exceptions-arm64.c:420)
9   OurAppiOS                            0x0000000102963168 llvm_resume_unwind_trampoline + 164
10  OurAppiOS                            0x000000010392b4ec Xamarin_iOS_UIKit_UIApplication_Main_string___string_string (UIApplication.cs:0)
11  OurAppiOS                            0x00000001053049e8 mono_jit_runtime_invoke (mini-runtime.c:3164)
12  OurAppiOS                            0x00000001053c010c mono_runtime_invoke_checked (object.c:3052)
13  OurAppiOS                            0x00000001053c6364 mono_runtime_exec_main_checked (object.c:0)
14  OurAppiOS                            0x00000001052e2f7c mono_jit_exec (driver.c:1383)
15  OurAppiOS                            0x00000001054a0dac xamarin_main (monotouch-main.m:493)
16  OurAppiOS                            0x000000010285510c main (main.m:302)
17  dyld                                 0x0000000105c39a24 start + 520 (dyldMain.cpp:876)

Thread 1:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 2:
0   libsystem_kernel.dylib               0x00000001b84caf90 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x00000001f1931254 _pthread_cond_wait + 1224
2   OurAppiOS                            0x0000000105463a7c thread_func (mono-os-mutex.h:219)
3   libsystem_pthread.dylib              0x00000001f192a9a4 _pthread_start + 144
4   libsystem_pthread.dylib              0x00000001f1929ea0 thread_start + 4

Thread 3:
0   libsystem_kernel.dylib               0x00000001b84ca540 semaphore_wait_trap + 8
1   OurAppiOS                            0x000000010536137c finalizer_thread (mono-os-semaphore.h:84)
2   OurAppiOS                            0x000000010540e0f8 start_wrapper_internal (threads.c:1233)
3   OurAppiOS                            0x000000010540df7c start_wrapper (threads.c:1308)
4   libsystem_pthread.dylib              0x00000001f192a9a4 _pthread_start + 144
5   libsystem_pthread.dylib              0x00000001f1929ea0 thread_start + 4

Thread 4:
0   libsystem_kernel.dylib               0x00000001b84cb1a4 __ulock_wait + 8
1   libdispatch.dylib                    0x00000001812fc054 _dlock_wait + 52
2   libdispatch.dylib                    0x00000001812fbdf8 _dispatch_thread_event_wait_slow + 52
3   libdispatch.dylib                    0x000000018130ab9c __DISPATCH_WAIT_FOR_QUEUE__ + 360
4   libdispatch.dylib                    0x000000018130a744 _dispatch_sync_f_slow + 140
5   UIKitCore                            0x0000000183e08398 __37-[_UIRemoteKeyboards startConnection]_block_invoke_3 + 132
6   CoreFoundation                       0x00000001816122f4 __invoking___ + 144
7   CoreFoundation                       0x000000018162fac4 -[NSInvocation invoke] + 464
8   Foundation                           0x0000000182e46f00 __NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__ + 20
9   Foundation                           0x0000000182e67da4 -[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:] + 552
10  Foundation                           0x0000000182e42a84 __88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_3 + 208
11  libxpc.dylib                         0x00000001f196032c _xpc_connection_reply_callout + 112
12  libxpc.dylib                         0x00000001f195385c _xpc_connection_call_reply_async + 84
13  libdispatch.dylib                    0x00000001812fb6e0 _dispatch_client_callout3 + 16
14  libdispatch.dylib                    0x0000000181318ec8 _dispatch_mach_msg_async_reply_invoke + 344
15  libdispatch.dylib                    0x0000000181302cbc _dispatch_lane_serial_drain + 372
16  libdispatch.dylib                    0x000000018130398c _dispatch_lane_invoke + 440
17  libdispatch.dylib                    0x000000018130e1a8 _dispatch_workloop_worker_thread + 652
18  libsystem_pthread.dylib              0x00000001f192a0f4 _pthread_wqthread + 284
19  libsystem_pthread.dylib              0x00000001f1929e94 start_wqthread + 4

Thread 5:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 6:
0   libsystem_kernel.dylib               0x00000001b84ca504 mach_msg_trap + 8
1   libsystem_kernel.dylib               0x00000001b84cab9c mach_msg + 72
2   CoreFoundation                       0x00000001815f7688 __CFRunLoopServiceMachPort + 368
3   CoreFoundation                       0x00000001815fb97c __CFRunLoopRun + 1208
4   CoreFoundation                       0x000000018160f3b8 CFRunLoopRunSpecific + 596
5   Foundation                           0x0000000182e2a354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 232
6   Foundation                           0x0000000182e6bc28 -[NSRunLoop(NSRunLoop) runUntilDate:] + 88
7   UIKitCore                            0x0000000183f288a4 -[UIEventFetcher threadMain] + 520
8   Foundation                           0x0000000182e7a36c __NSThread__start__ + 804
9   libsystem_pthread.dylib              0x00000001f192a9a4 _pthread_start + 144
10  libsystem_pthread.dylib              0x00000001f1929ea0 thread_start + 4

Thread 7:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 9:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 10:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 11:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 12:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 15:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 16:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 21:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 22:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 23:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 24:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 25:
0   libsystem_pthread.dylib              0x00000001f1929e8c start_wqthread + 0

Thread 0 crashed with ARM-64 (Native) Thread State:
    x0: 0x0000000000000000     x1: 0x0000000000000000     x2: 0x0000000000000000     x3: 0x0000000000000000
    x4: 0x0000000000000000     x5: 0x0000000000989680     x6: 0x0000000000000600     x7: 0xffffffff00000400
    x8: 0x1ff943a14f4a1322     x9: 0x1ff943a04a8256a2    x10: 0x00000000000003e8    x11: 0x0000000000bf3d01
   x12: 0x0000000000004009    x13: 0x0000000107174000    x14: 0x0000000000003fff    x15: 0x0000000000003381
   x16: 0x0000000000000148    x17: 0x0000000105c84580    x18: 0x0000000000000000    x19: 0x0000000000000006
   x20: 0x0000000000000103    x21: 0x0000000105c84660    x22: 0x0000000106409a30    x23: 0x0000000107022e48
   x24: 0x0000000107131f50    x25: 0x0000000106776900    x26: 0x000000010701ac00    x27: 0x0000000000000003
   x28: 0x00000001029396bf     fp: 0x000000016d6cd650     lr: 0x00000001f1930378     sp: 0x000000016d6cd630
    pc: 0x00000001b84d0964   cpsr: 0x40000000    esr: 0x56000080

**Comment by jfversluis** [comment]
Without a reproduction or useful logs it's quite impossible to diagnose this. Sorry about that! Let me know if you have a more .NET related stack trace of any other information.
