### ISSUE TITLE
[Internal] Duplicate ItemGroup in Xamarin.Forms.Xaml.UnitTests.csproj

### ISSUE THREAD

**Issue by workgroupengineering** [xamarin/Xamarin.Forms#1496]
### Description
In Xamarin.Forms.Xaml.UnitTests.csproj
there are duplicate ItemGroups.

The lines are:
```xml
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="packages.config" />
  </ItemGroup>
````

[L1005-L1011](https://github.com/xamarin/Xamarin.Forms/blob/c8b4685bc91454d0fb43fd501329e49503521cb4/Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj#L1005-L1011) and [L1037-L1043](https://github.com/xamarin/Xamarin.Forms/blob/c8b4685bc91454d0fb43fd501329e49503521cb4/Xamarin.Forms.Xaml.UnitTests/Xamarin.Forms.Xaml.UnitTests.csproj#L1037-L1043).

**Comment by kingces95** [comment]
Msbuild combines all ItemGroups so splitting them or combining them has no material effect; By convention, authors will split different times of items across different ItemGroup tags. But that's only to make the file more readable -- it has no other material effect.

**Comment by workgroupengineering** [comment]
thanks for the reply, the problem can be seen in the IDE, where you can see two app.config and two packages.config.

![im1](https://user-images.githubusercontent.com/12531229/34604794-6bfc81d6-f209-11e7-993a-48e76b8d25d1.jpg)
![im2](https://user-images.githubusercontent.com/12531229/34604805-71311dba-f209-11e7-8bb7-b5d3b2788b87.jpg)

In addition I think that in case of merge could bring confusion.
