### ISSUE TITLE
[Bug][iOS] Adding custom font to theme causes crash when displaying string

### ISSUE THREAD

**Issue by m-kok** [xamarin/Xamarin.Forms#14973]
### Description
When trying to launch an iOS app using labels that are using custom fonts (Have tried multiple fonts so far), the app will crash the moment it needs to displays strings using this font.
A coworker running an older version of visual studios 2019(16.11.3) is able to use custom fonts while the code and used NuGet packages are the same.

On Android this is not a issue.

### Steps to Reproduce

1. Add a custom font to the project (shared resources because font is used in both android and iOS app).
2. Add a Label to the mainpage using this custom font.
3. Launch app on iOS. 

### Expected Behavior
The app starting correctly and displaying the mainpage using the custom font.

### Actual Behavior
Crash when string is displayed.
This will give the following crash report saying:

form.iOS.FontExtensions:ToNativeFont <0x0005c>
	  at Xamarin.Forms.Platform.iOS.FontExtensions:ToUIFont <0x0000a>
	  at Xamarin.Forms.Platform.iOS.LabelRenderer:UpdateFont <0x00082>
	  at Xamarin.Forms.Platform.iOS.LabelRenderer:OnElementChanged <0x000d8>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x002a2>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x00228>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x000
:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:<ViewDidLoad>b__47_0 <0x0004a>
	  at System.Action`1:invoke_void_T <0x0007c>
	  at Xamarin.Forms.Internals.EnumerableExtensions:ForEach <0x0004c>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:ViewDidLoad <0x001de>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0008e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:IntPtr_objc_msgSendSuper <0x0001a>
	  at UIKit.UIViewController:get_View <0x0006c>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:get_NativeView <0x0000c>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:SetElement <0x00050>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.Platform:AddChild <0x00052>
	  at Xamarin.Forms.Platform.iOS.Platform:WillAppear <0x00086>
	  at Xamarin.Forms.Platform.iOS.PlatformRenderer:ViewWillAppear <0x00040>
	  at <Module>:runtime_invoke_direct_void__this___bool <0x0009e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Me
84>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:ViewDidLoad <0x0010c>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0008e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:IntPtr_objc_msgSendSuper <0x0001a>
	  at UIKit.UIViewController:get_View <0x0006c>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:get_NativeView <0x00016>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:SetElement <0x00096>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:CreateViewControllerForPage <0x00022>
	  at <OnPushAsync>d__52:MoveNext <0x0003a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:OnPushAsync <0x00056>
	  at Xamarin.Forms.Platform.iOS.NavigationRenderer:PushPageAsync <0x00014>
	  at <<ViewDidLoad>b__47_0>d:MoveNext <0x0002e>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder
ssaging:void_objc_msgSend <0x0001a>
	  at UIKit.UIWindow:MakeKeyAndVisible <0x00038>
	  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate:SetMainPage <0x00022>
	  at Xamarin.Forms.Platform.iOS.FormsApplicationDelegate:FinishedLaunching <0x0006e>
	  at Dashboard_Mobile.iOS.AppDelegate:FinishedLaunching <0x0004c>
	  at <Module>:runtime_invoke_direct_bool__this___UIApplication_NSDictionary <0x000c8>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00054>
	  at Dashboard_Mobile.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.iOS.HotRestart.Application:Run <0x001c8>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x0005a>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>

### Basic Information

- Version with issue: Xamarin.Forms version 5.0.0.2012 (5.0.0.2244 also doesn't work)
- Platform Target Frameworks: - iOS:  14.4
- NuGet Packages: Xamarin.Essentials, ShiaSharp (not used on the page causing the crash)
- Affected Devices: Iphone

### Environment

- Using Visual studios 2019 version 16.11.7, a coworker running version 16.11.3 is able to run native fonts

Microsoft Visual Studio Community 2019
Version 16.11.7
VisualStudio.16.Release/16.11.7+31911.196
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA396
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.11.94.52318
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.11.94.52318
Azure App Service Tools v3.0.0

C# Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.21403.6+ae1fff344d46976624e68ae17164e0607ab68b10
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Workaround

None

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?

<img width="314" alt="Captura de pantalla 2021-12-10 a las 10 23 15" src="https://user-images.githubusercontent.com/6755973/145550390-39eeaf8f-31e7-4a85-ae59-cfedd3f8034e.png">
[Issue14973.zip](https://github.com/xamarin/Xamarin.Forms/files/7691598/Issue14973.zip)

**Comment by m-kok** [comment]
Whats the best way to add a sample?

**Comment by m-kok** [comment]
Made a sample project that reproduces the crash (Using a connected iPhone 6 running on windows)
[ThemeApp.zip](https://github.com/xamarin/Xamarin.Forms/files/7692159/ThemeApp.zip)

**Comment by jsuarezruiz** [comment]
@jfversluis Do you have installed VS 2019 16.11.7?. Tried to reproduce with emulators and devices using VS for macOS 2019 and 2022 and VS 2022 on Windows but without success.

**Comment by m-kok** [comment]
I tried to use VS2022, and another Iphone but both don't fix the issue. 
Are you able to reproduce the bug using my example?

**Comment by jfversluis** [comment]
Looks the same as #14934 and #14905 and #14955. Seems to be nothing that is caused from Xamarin.Forms directly. Please follow up on the ticket that is linked in the other issues. Thanks!
