### ISSUE TITLE
[Code signing "Razorpay.framework" failed Xcode Xamarin form] 

### ISSUE THREAD

**Issue by anjanicity** [xamarin/Xamarin.Forms#15001]
### Description
I am getting an error when i archived my project through Xcode (Xamarin form Project integrated with razorpay)
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
It should successfully generated archived for the project 
### Actual Behavior
Showing an error (Code sigining Razorpay.framework failed )
### Basic Information

- Version with issue: Xcode 13.2
- Last known good version: 13 and before successfully archib
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

<img width="752" alt="Screenshot 2021-12-24 at 12 01 22 AM" src="https://user-images.githubusercontent.com/82590925/147280659-7a835e9b-1e4e-4807-90c6-63ff00d4ac53.png">

**Comment by jfversluis** [comment]
Hey @anjanicity thanks for the report! Afraid I will have to close this one though. Since this is using Xcode and a third-party framework it's impossible to know if this is a Xamarin.Forms issue. Also, we'll need a lot more info to say something useful about it like logs etc.

Hope you'll figure it out!

**Comment by anjanicity** [comment]
its Xcode issue when i am archiving my project(integrated with Razor-pay) through Xcode to publish on App Store its showing the same error. i also not able to figure it out what the problem its working with previous version of Xcode
