### ISSUE TITLE
[Enhancement] Add an overloaded constructor for Setter type with BindableProperty and Value as its parameters

### ISSUE THREAD

**Issue by egvijayanand** [xamarin/Xamarin.Forms#15007]
## Summary
While working with C# / Markup, it requires a lot of key strokes to create a Setter and set its Property and Value in the initializer.

## API Changes

Whereas if there is an overloaded constructor that takes the BindableProperty and Value as its parameters, this would save too many keystrokes especially when there're too many Styles / Triggers / Visual States to define.

## Intended Use Case
Present scenario:
`new Setter() { Property = Button.TextColorProperty, Value = Color.White }`

With the Proposed API:
`new Setter(Button.TextColorProperty, Color.White)`

With C# 9 syntax, this would even get simplified when used inside the `Setters` collection:
```CSharp
Setters =
{
    new(Button.TextColorProperty, Color.White)
}
```

**Comment by jfversluis** [comment]
Hey @egvijayanand thanks for the suggestion! Unfortunately, we're trying to add as little new APIs as possible to Xamarin.Forms anymore :)

If this is still something of interest to you, please open a feature request on the .NET MAUI repo, thanks!

**Comment by egvijayanand** [comment]
Hi @jfversluis,

Somehow I forgot that earlier communication about not inducting new APIs into Xamarin.Forms.

For .NET MAUI, will check if one is already included there, if not, will raise a request over there.

Regards,
Vijay Anand E G
