### ISSUE TITLE
[Bug] Xamarin.UITest cannot handle fast updates / UITest is slow. 

### ISSUE THREAD

**Issue by PawKanarek** [xamarin/Xamarin.Forms#15011]
### Description
Xamarin.UITest framework cannot handle fast UI updates. 
I've observed that assertions `WaitForElement()` and `WaitForNoElement()` that detects updates of UI with duration under 300 ms will fail to assert correctly (but even 300ms feels slow for some animations, transitions or layout changes).

### Steps to Reproduce

1. Download modified version of [yours sample "UsingUITests"](https://github.com/xamarin/xamarin-forms-samples/tree/main/UsingUITest) from this repo https://github.com/PawKanarek/reproduction-repo-for-ui-test/tree/main
2. Build iOS app and deploy on emulator (i didn't test other platforms in this sample repository)
3. Run UI TEST named "ButtonWorks"

### Expected Behavior

UITest is passing correctly

### Actual Behavior

UITest is failing

### Basic Information

- Version with issue: probably all Xamarin.Forms
- Last known good version: not known
- NuGet Packages:
```
<PackageReference Include="Xamarin.Forms" Version="5.0.0.1874" />
<PackageReference Include="NUnit" Version="2.6.4" />
<PackageReference Include="NUnitTestAdapter" Version="2.3.0" />
<PackageReference Include="Xamarin.UITest" Version="3.1.0" />
```

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.11 (build 8)
Installation UUID: e610164d-e165-4968-b76c-beb6d7ff97b0
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000140

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.140 (2020-02/51d876a041e) (64-bit)
	Package version: 612000140

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.402/Sdks
SDK Versions:
	5.0.402
	5.0.400
	5.0.302
	5.0.301
	3.1.414
	3.1.412
	3.1.411
	3.1.410
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.11
	5.0.9
	5.0.8
	5.0.7
	3.1.20
	3.1.18
	3.1.17
	3.1.16

=== .NET Core 3.1 SDK ===

SDK: 3.1.414

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.10.0.119
Hash: 36a2d986f
Branch: remotes/origin/d16-10
Build date: 2021-06-02 19:41:34 UTC

=== Xamarin.Android ===

Version: 11.3.0.4 (Visual Studio Community)
Commit: xamarin-android/d16-10/ae14caf
Android SDK: /Users/pkanarek/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 31.0.0

Build Information: 
Mono: b4a3858
Java.Interop: xamarin/java.interop/d16-10@f39db25
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-10@c5732a0

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/pkanarek/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:30:50 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-09-21 02:31:08 UTC

=== Apple Developer Tools ===

Xcode 13.0 (19234)
Build 13A233

=== Xamarin.Mac ===

Version: 7.14.0.27 (Visual Studio Community)
Hash: 2566861a9
Branch: d16-10
Build date: 2021-07-27 02:34:12-0400

=== Xamarin.iOS ===

Version: 15.0.0.6 (Visual Studio Community)
Hash: 2771277e0
Branch: xcode13-ios
Build date: 2021-09-23 10:36:08-0400

=== Build Information ===

Release ID: 810110008
Git revision: 5467245e1f99a0c8ccdd2acea02d16c3fb65c220
Build date: 2021-10-07 10:49:46-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Mon Aug 30 06:12:21 PDT 2021
    root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64


```

</details>

### VIDEO

https://github.com/PawKanarek/reproduction-repo-for-ui-test/blob/main/Screen%20Recording%202021-12-30%20at%2015.15.35.mov?raw=true

from 00:00 to 00:45 we see expected behaviour of passing test when updates have duration 300ms
from 00:45 to 02:04 we see actual behaviour of failing test when updates have duration 200ms  

### Reproduction Link

https://github.com/PawKanarek/reproduction-repo-for-ui-test

### Workaround

Use slower animations, transitions and layout changes for UI test, but this negates idea of not modifying source code for testing purposes.

**Comment by PawKanarek** [comment]
HI everyone I figured this out, looks like  documentation fot method  `WaitForElement()` is incomplete.  https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.ios.iosapp.waitforelement?view=xamarin-uitest-sdk 

This method has parameter  `retryFrequency` of type `Nullable<TimeSpan>` with description `The TimeSpan to wait between each query call to the app. ` and with default value `null` so i what i thought, that when i don't pass any retryFrequency, then it should retry assertion as fast as possible. 

but deep into implementation code of WaitForHelper in Xamarin.UiTest.Shared namespace i see that the wait time is 250 ms. 
![image](https://user-images.githubusercontent.com/15096514/147820695-b180044e-b432-403a-ac5e-e48e01000cc5.png)

I assume thats the reason why didn't noticed updates with time < 300ms. 
Can you please write down in documentation real default value of  `retryFrequency` for method   `WaitForElement()` and `WaitForNoElement()` ?

**Comment by jfversluis** [comment]
Glad you figured it out! I will see if we need to update the docs for this, thanks! :)
