### ISSUE TITLE
[Bug] [Android] Crash from ShellFlyoutRenderer. "Canvas: trying to draw too large bitmap."

### ISSUE THREAD

**Issue by greg84** [xamarin/Xamarin.Forms#15013]
### Description

Tried to create a discussion to get help with this, creating a bug report for additional exposure.

Please see further details here:
https://github.com/xamarin/Xamarin.Forms/discussions/14978

Although this crash comes from ShellFlyoutRenderer, I don't actually have flyout enabled so I'm not sure what's happening here.

If a work around is available please let me know. This is causing a relatively high number of crashes in production (0.3% of users affected).

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior

App should not crash from inside framework code.

### Actual Behavior

App crashes within a few seconds, suggesting an error during startup.

### Basic Information

- Version with issue: 5.0.0.2244 and 5.0.0.2291
- Last known good version: n/a
- Platform Target Frameworks: 
  - iOS: 15.4.0.0
  - Android: 12.0.0.3
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms
- Affected Devices: Reported on Galaxy On Nxt, Galaxy J5 Prime, Redmi Note 5 Pro running Android 7.1.1, 8 and 8.1

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio Community 2019 for Mac
Version 8.10.16 (build 2)
Installation UUID: d84992da-d070-4eea-b6f4-ffdcfdf9880c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

Mono Framework MDK
Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

Roslyn (Language Service)
3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

NuGet
Version: 5.9.0.7134

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/5.0.404/Sdks
SDK Versions:
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	5.0.102
	5.0.101
	5.0.100
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	3.1.404
	3.1.403
	3.1.402
	3.1.401
	3.1.302
	3.0.100
	2.1.401
	2.1.4
	2.0.0
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	5.0.2
	5.0.1
	5.0.0
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.1.10
	3.1.9
	3.1.8
	3.1.7
	3.1.6
	3.0.0
	2.1.23
	2.1.22
	2.1.21
	2.1.20
	2.1.3
	2.0.5
	2.0.0
	1.0.5

Xamarin.Profiler
Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 12.0.0.3 (Visual Studio Community)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/greg/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

Eclipse Temurin JDK
Java SDK: Not Found

Android SDK Manager
Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

Android Device Manager
Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

Apple Developer Tools
Xcode 13.2.1 (19586)
Build 13C100

Xamarin.Mac
Version: 8.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

Xamarin.iOS
Version: 15.4.0.0 (Visual Studio Community)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

Xamarin Designer
Version: 16.11.0.39
Hash: cd672761d
Branch: remotes/origin/d16-11
Build date: 2021-10-06 21:09:18 UTC

Build Information
Release ID: 810160002
Git revision: 6dbc7886fa608147f685a7df3912249400c84716
Build date: 2021-12-14 15:54:37-05
Build branch: release-8.10

Operating System
Mac OS X 11.6.1
Darwin 20.6.0 Darwin Kernel Version 20.6.0
    Tue Oct 12 18:33:42 PDT 2021
    root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

```

</details>

**Comment by jfversluis** [comment]
> Tried to create a discussion to get help with this, creating a bug report for additional exposure.

I understand the reasoning, unfortunately that's not how this work. I'm not going to clutter the issues (any more than they already are) to get more exposure. Thanks for your understanding!

**Comment by greg84** [comment]
Understood @jfversluis, but would it be better to close the discussion and leave this issue open? The application shouldn't crash from inside this method should it? Especially when I'm not using the flyout.

**Comment by greg84** [comment]
This is not a Xamarin issue. I was able to reproduce the issue on the device I purchased.

I had to use a `drawable-xxhdpi` folder for an image that was being displayed. Originally the image was in the `drawable` folder and Android was trying to scale it up by a ridiculous amount.

Thanks for your help on this @jfversluis.

**Comment by jfversluis** [comment]
Oh man! That could've been a hard one to discover! Glad you figured it out!
