### ISSUE TITLE
I want to know if xamarin is the worst environ. to use? splashscreen keeps shutting app for 3 days now. very annoying 

### ISSUE THREAD

**Issue by sergeibystrov** [xamarin/Xamarin.Forms#15014]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
If the app shuts down on the splash screen or anywhere else suddenly, that usually means some kind of unhandled exception has occurred. Please inspect your code and application output for anything like that.

Additionally, if you really want our help, and we're happy to help, I suggest you don't come in opening your first issue and calling us "the worst environment" and secondly; we would need more info than just the title being filled in. Thanks!

**Comment by sergeibystrov** [comment]
> If the app shuts down on the splash screen or anywhere else suddenly, that usually means some kind of unhandled exception has occurred. Please inspect your code and application output for anything like that.
> 
> Additionally, if you really want our help, and we're happy to help, I suggest you don't come in opening your first issue and calling us "the worst environment" and secondly; we would need more info than just the title being filled in. Thanks!

Please, i have finished my app but its running it on release mode that it loads the splashscreen for one minute plus and then the app and immediately exit. i have something like that on this github link: https://github.com/sergeibystrov/SmallWallet2
i use visual studio 2022 to build it so i dont know if visual studio 2022 has a bug because i have rebuild my emulator by increasing the Ram but to no avail. please build the link in release mode . its d default app with added splashscreen settings i used in my app and it exits when it touches the app after splashscreen. i dont know why. please help me urgently.

**Comment by kcrg** [comment]
@sergeibystrov If your app only crashes in Release mode, there may be a problem with the link. If you want, I can try to fix it. ;) You need to change your repository visibility to public, it seems to be private.

**Comment by sergeibystrov** [comment]
> @sergeibystrov Startup crashes can be annoying, I understand that, but these types of reports are unprofessional, toxic, and unnecessary.
> 
> If your app only crashes in Release mode, there may be a problem with linking. If you want, I can try to fix it. ;) You need to change your repository visibility to public, it seems to be private.
let me see because this is my first time pushing code to github

**Comment by sergeibystrov** [comment]
> > @sergeibystrov Startup crashes can be annoying, I understand that, but these types of reports are unprofessional, toxic, and unnecessary.
> > If your app only crashes in Release mode, there may be a problem with linking. If you want, I can try to fix it. ;) You need to change your repository visibility to public, it seems to be private.
> 
> I have just changed the visibility to public. My bad
