### ISSUE TITLE
[Bug] [macOS] Rendering Line shape crashes the app in case xCode 13.2 installed

### ISSUE THREAD

**Issue by sady4850** [xamarin/Xamarin.Forms#15026]
### Description

With Xcode 13.2 installed, any Xamarin Forms app that uses Line shapes crashes immediately when the line is rendered.

### Steps to Reproduce
1. Make sure xCode 13.2 is installed
2. Add a Line shape in XAML (or in code)
3. Run app
For example, this page will crash the app:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XFLineBug.MainPage">

    <Grid>
        <Line X1="10" Y1="10" X2="100" Y2="50" Stroke="Red" StrokeThickness="3"/>
    </Grid>

</ContentPage>
```

Exception thrown: `Could not initialize an instance of the type 'CoreGraphics.CGPath': handle is null.`

Repro project: [CGPathIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/7816506/CGPathIssue.zip)
(this is a clean new Xamarin Forms macOS project with the MainPage changed to show a line shape)

### Expected Behavior

Line is shown on screen

### Actual Behavior

App crashes immediately.

100% reproducible

### Basic Information

- Version with issue: 5.0.0.2125 and 5.0.0.2291 (possibly earlier versions as well)
- Last known good version: unknown
- Platform Target Frameworks:
  - macOS
  - iOS: N.A
  - Android: N/A
  - UWP: N/A
Android Support Library / AndroidX Version: N/A
Affected Devices: all macOS devices

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Visual Studio for Mac 8.10.16
```

</details>

**Comment by activa** [comment]
@jfversluis How can this be fixed by PR #14993? This issue is for MacOS but the PR only changes the iOS code

**Comment by activa** [comment]
@jfversluis Right, just figured that out as well. 
Thanks, learned something new today :-)

**Comment by davibittencourtome** [comment]
I have this same bug using "<Path", @pictos  recommended me to use version "5.0.0.2336-nighly", which already has the fix and everything is fine so far. Please, what is the release forecast for a new version in release?

**Comment by jfversluis** [comment]
Should be any day :) probably early next week

**Comment by davibittencourtome** [comment]
I have this same bug using "<Path", @pictos recommended me to use version "5.0.0.2336-nighly", which already has the fix and everything is fine so far. Please, what is the release forecast for a new version in release?

**Comment by davibittencourtome** [comment]
> Should be any day :) probably early next week

Thank you @jfversluis , have a great weekend!!
