### ISSUE TITLE
[Bug] App.xaml: Value cannot be null. Parameter name: method

### ISSUE THREAD

**Issue by MaxFelinger** [xamarin/Xamarin.Forms#15029]
### Description
We just updated an existing project from Xamarin.Forms 4.8.0.1687 to Xamarin.Forms 5.0.0.1931. Our project sets CopyLocalLockFileAssemblies  to true. 

### Steps to Reproduce

1.  Create a project with Xamarin.Forms 4.8.
2. Update to Xamarin.Forms 5.0.0.1931
3. Build the application.

### Expected Behavior
Build succeeded.

### Actual Behavior
Exception gets thrown: App.xaml: Value cannot be null. Parameter name: method

### Basic Information
- Version with issue: Xamarin.Forms 5.0.0.1931
- Last known good version: 4.8.0.1687
- Platform Target Frameworks: 
  - iOS:  15.2 (but it actually is not relevant)
  - Android: 11 (but it actually is not relevant)

### Workaround

Remove the following tag from your *.csproj files: CopyLocalLockFileAssemblies

**Comment by jfversluis** [comment]
Is there any specific reason you have `CopyLocalLockFileAssemblies` in there? If not, I guess the solution would be to just get rid of it? This is not something that is in the default Xamarin.Forms templates.

I doubt that this is something that is an issue with Xamarin.Forms at this point else we would've seen this issue much earlier and more often. It would really help if you could get an actual reproduction project that shows this problem.

**Comment by MaxFelinger** [comment]
It was there from the creation of the project. So I assume that it was automatically created using Xamarin.Forms 4.5.0.396. We've removed it and everything works just as fine. 

Will close this issue.

**Comment by jfversluis** [comment]
Thanks for letting us know Max!
