### ISSUE TITLE
[Bug] ProgressBar documentation missing in metadata and microsoft docs

### ISSUE THREAD

**Issue by ShinichiHezemansCortegs** [xamarin/Xamarin.Forms#15039]
### Description
Xamarin.Fomrs.ProgressBar has missing documentation for methodes such as ProgressTo.
### Steps to Reproduce
in visual studio 
hover over Xamarin.Forms.ProgressBar
press f12 or go to defenition
look at the descriptions of the parameter for a method

### Expected Behavior
there is a description of what a parameter does

### Actual Behavior
the text "To be added."

### Basic Information
assembly Xamarin.Forms.Core
Xamarin Forms version 5.0.0.2291

[mircosoft docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.progressbar.progressto?view=xamarin-forms#Xamarin_Forms_ProgressBar_ProgressTo_System_Double_System_UInt32_Xamarin_Forms_Easing_)

### Environment
\-

### Build Logs
\-

### Screenshots
\-

### Reproduction Link
\-

### Workaround
units for ProgressTo can be found at [other docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/progressbar)

**Comment by jfversluis** [comment]
Hey thanks for opening this! That is indeed a long standing problem we have with all of our controls. See for instance #7252 

At this point we hope to get something done by backporting some of .NET MAUI, but not sure if we can do that for the time that remains for Forms. Sorry for the inconvience!
