### ISSUE TITLE
Attached Properties XAML Error when `PropertyName` matches the `ReturnType`: No property, bindable property, or event found, or mismatching type between value and property

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#1503]
### Description
An attached property with a `PropertyName` that matches the name of the `Enum` used for the `ReturnType` throws the following error:
>No property, bindable property, or event found, or mismatching type between value and property.

This may be confusing the reflection that the XAML compiler/runtime uses?

I found that if I change `PropertyName` to be a unique name (different from the `Enum`) it works:
https://github.com/brminnick/EntryCustomReturnPlugin/issues/7#issuecomment-355142971

Source Code for Xamarin.Forms Plugin used in the reproduction sample app:
https://github.com/brminnick/EntryCustomReturnPlugin

### Steps to Reproduce
1. Download Reproduction Sample App:
https://github.com/brminnick/XamlAttachedPropertyReproduction
2. Build the solution
3. This line of XAML will throw the following error: 
`entryCustomReturn:CustomReturnEffect.ReturnType="{x:Static entryCustomReturn:ReturnType.Go}"`
>No property, bindable property, or event found...

### Expected Behavior
Project should compile/run with no errors

### Actual Behavior
XAMLC throws the following build error:
>No property, bindable property, or event found, or mismatching type between value and property.

### Basic Information

- Version with issue: Xamarin.Forms v2.5.0.121934
- Last known good version: Unknown
- IDE: VS Mac (Environment information below)
- Platform Target Frameworks: 
  - iOS:  (Environment information below)
  - Android: (Environment information below)
  - UWP: N/A
- Android Support Library Version:(Environment information below)
- Nuget Packages: https://www.nuget.org/packages/Xam.Plugins.Forms.CustomReturnEntry/
- Affected Devices: Android + iOS

### Screenshots

N/A

### Reproduction Link

https://github.com/brminnick/XamlAttachedPropertyReproduction

### Visual Studio for Mac Environment
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.2 (build 12)
Installation UUID: 6e5142b4-e8be-4d1c-b75e-4744b0d8c3de
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Versions:
	2.0.0
	1.0.1
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 8.1.0.25 (Visual Studio Enterprise)
Android SDK: /Users/brandonm/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.1   (API level 16)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.2

Java SDK: /usr
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Enterprise)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Enterprise)

=== Build Information ===

Release ID: 703020012
Git revision: 7d0c9d7ad46b125cf4b7bbf9532c0531b6433ce6
Build date: 2017-12-12 14:03:18-05
Xamarin addins: 6dddaa49fbecb2695fcdcd6b712eb269e288518c
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

NuGet Package Management Extensions 0.12.6
WakaTime 3.0.0
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

**Comment by brminnick** [comment]
Adding @StephaneDelcroix &  @codemillmatt who helped uncover the error

**Comment by StephaneDelcroix** [comment]
The bindable property `ReturnType` is defined like this in your plugin:
```
public static BindableProperty ReturnTypeProperty => _returnTypeProperty ??
            (_returnTypeProperty = BindableProperty.CreateAttached(propertyName: nameof(ReturnType),
                                                                    returnType: typeof(ReturnType),
                                                                    declaringType: typeof(Entry),
                                                                    defaultValue: ReturnType.Default,
                                                                    propertyChanged: OnReturnTypeChanged));
```

Bindable properties needs to be `static` `readonly` fields (https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/custom-dependency-properties), and you are defining it as a property.

Fix your code by changing the declaration to
```
		public static BindableProperty ReturnTypeProperty = BindableProperty.CreateAttached(propertyName: nameof(ReturnType),
																	returnType: typeof(ReturnType),
																	declaringType: typeof(Entry),
																   defaultValue: ReturnType.Default);
```
