### ISSUE TITLE
[Bug] - iOS Xamarin Forms  Default 'Tabbed App' not showing Tabs  

### ISSUE THREAD

**Issue by BicycleMark** [xamarin/Xamarin.Forms#15035]
### Description
Source available here:
https://mark-d-wardell.visualstudio.com/PingApp/_git/PingApp

### Steps to Reproduce (see step #4)

1. Create a Tabbed App with Xamarin Forms installed in to Visual Studio For Mac Community 8.10.16 Build 2
2. run on pixel 2 ASDK (30)
3. Observe Tabs at Bottom of Page (correctly shows aBout Tab and Browse Tab)
![image](https://user-images.githubusercontent.com/11739690/148662653-1bfb7478-ba2c-43eb-b98f-ce714f79b18c.png)

4. run on ios observe no tabs appear Expecting (About and Browse)
![image](https://user-images.githubusercontent.com/11739690/148662666-bb4e872a-c139-4dbb-9d22-efddee7088d8.png)

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots
![image](https://user-images.githubusercontent.com/11739690/148662732-abd18197-b41e-41e6-b6d9-e0f7143b327b.png)

**Comment by jfversluis** [comment]
The Xamarin.Forms NuGet on your iOS project isn't updated: https://mark-d-wardell.visualstudio.com/PingApp/_git/PingApp?path=/PingApp.iOS/PingApp.iOS.csproj&version=GBmaster&line=135&lineEnd=136&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Update that to the latest version and it should work :)
