### ISSUE TITLE
[Bug] [Android] CollectionView leaks GREF when items are removed

### ISSUE THREAD

**Issue by Strifex** [xamarin/Xamarin.Forms#15049]
### Description

When removing items from an ObservableCollection that is bound to a CollectionView - there is a significant leak of references on the Android platform.  This can be observed by an ever-increasing GREF count as items are removed from the colleciton.  This GREF count persists even through Full GCs and eventually will result in the app freezing due to hitting the GREF limit and being unable to clean them up.

This issue is significant enough that our users can't utilize our app on Android for too long without it freezing and they're forced to restart it constantly.  So far, my team has struggled to mitigate this issue as any workarounds we've found only seem to delay the inevitable GREF leak of doom.

### Steps to Reproduce

NOTE: Observed on Android Only

1. Create an ObservableCollection with a large amount of items (at least 500+ but preferably closer to 1k+)
2. Databind the ObservableCollection to a CollectionView
3. Remove an item from the ObservableCollection
4. Observe the GREF count in android - they will continue to increase even if you force GC.Collect()
5. The memory will never be released as long as you stay on the screen

### Expected Behavior

The GREF Count on Android should not increase significantly when removing items from a CollectionView and should eventually decrease after GC calls.

### Actual Behavior

The GREF Count continues to increase as items are removed from a CollectionView until it hits > 46k, forces full GCs, and eventually runs out of CPU and freezes / crashes the application on Android.

### Basic Information

- Version with issue: 5.0.0.2291
- Last known good version: 4.8.0.1821
- Platform Target Frameworks:
- Android: 11.0
- Affected Devices: Multiple Android Devices, including various Pixel, Samsung, Honeywell CN85, etc.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2022
Version 17.0.4
VisualStudio.17.Release/17.0.4+32014.148
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA124
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   17.0.11 (54f19d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.343 (d17-0@fb07a17)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.183 (remotes/origin/d17-0@a351f0f1f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.17 (9e779b0)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.1.0.5 (d17-0/6b0e6b2)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d17-0@febb1367
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.36.0@a575761
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-0@a5194e9


Xamarin.iOS and Xamarin.Mac SDK   15.4.0.0 (8fc41ae82)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

[CollectionView Leak.zip](https://github.com/xamarin/Xamarin.Forms/files/7858733/CollectionView.Leak.zip)

### Workaround

You can "mitigate" some of the issue if you forcibly reset the ObservableCollection - some GREF is released, but there's still a leak and the count will continue to climb as items are removed from the collection.

**Comment by Strifex** [comment]
Some additional insight - It seems while the GREF leak started in the initial Xamarin.Forms 5.0 release (and has persisted since) - it appears to have gotten more aggressive in the latest v5.0.0.2291.

**Comment by roxton001** [comment]
Any updates on this? As a workaround, we had to replace a CollectionView with a ListView component.
