### ISSUE TITLE
objectdisposedexception Xamarin.Forms.Platform.Android.RefreshViewRenderer

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15044]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/objectdisposedexception-XamarinFormsPl/1593234)._

---
[severity:I'm unable to use this version]
I'm developing an Xamarin Forms app for iOS and Android.
Using:
- VS 2022 version 17.0.1
- Xamarin.Forms 5.0.0.2244

Is this a bug (as I've seen this error and fixes for other types of Xamarin.Forms components in StackOverflow)?
If so, when can I expect a patch?

---
#### Feedback Bot on 11/23/2021, 11:38 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jsuarezruiz** [comment]
Could we get more information or a small sample where reproduce the issue?

**Comment by AbuMandour** [comment]
I have the same error, while I am using collection view ,refresh view and statelayout togther
here is my Xaml
`

                  <Grid
                        Grid.Row="2"
                        Margin="10"
                        xct:StateLayout.AnimateStateChanges="False"
                        xct:StateLayout.CurrentState="{Binding DataStatus}">
                        <xct:StateLayout.StateViews>
                            <xct:StateView
                                RepeatCount="5"
                                StateKey="Loading"
                                Template="{StaticResource eventsLoadingCell}" />
                            <xct:StateView
                                StateKey="Empty"
                                Template="{StaticResource empty}"
                                VerticalOptions="FillAndExpand" />
                            <xct:StateView
                                HorizontalOptions="FillAndExpand"
                                StateKey="Error"
                                Template="{StaticResource error}" />
                            <xct:StateView StateKey="Success">
                                <StackLayout>
                                    <RefreshView Command="{Binding RefreshCommand}" IsRefreshing="{Binding IsRefreshing}">
                                        <CollectionView
                                            x:Name="EventsCollectionView"
                                            ItemSizingStrategy="MeasureAllItems"
                                            ItemsSource="{Binding Events}"
                                            SelectedItem="{Binding SelectedEvent}"
                                            SelectionChangedCommand="{Binding SelectionChangedCommand}"
                                            SelectionMode="Single">
                                            <CollectionView.ItemsLayout>
                                                <LinearItemsLayout ItemSpacing="10" Orientation="Vertical" />
                                            </CollectionView.ItemsLayout>
                                            <CollectionView.ItemTemplate>
                                                <DataTemplate x:DataType="models:EventModel">
                                                    <Grid  ColumnDefinitions="1*,2*"
                                                           HeightRequest="{Binding CellHeight}">
                                                        <StackLayout Grid.Column="0">
                                                             <Label FontFamily="PoppinsMedium"
                                                                    HorizontalOptions="Center"
                                                                    TextColor="#3F495D"
                                                                    Text="{Binding StartTime}"/>
                                                        </StackLayout>
                                                        <Grid ColumnDefinitions="10,*,*"
                                                              RowDefinitions="*,*"
                                                              xct:CornerRadiusEffect.CornerRadius="15"
                                                              BackgroundColor="{Binding EventColorHex,StringFormat='#33{0:F2}'}"                                                              
                                                              Margin="5"
                                                              Padding="10"
                                                              Grid.Column="1">
                                                            <StackLayout Grid.RowSpan="2"
                                                                         Grid.Column="0"
                                                                         WidthRequest="5"
                                                                         xct:CornerRadiusEffect.CornerRadius="5"
                                                                         BackgroundColor="{Binding EventColorHex,StringFormat='#{0:F2}'}" />
                                                            <Label Grid.Column="1"
                                                                   Grid.ColumnSpan="2"
                                                                   Grid.Row="0"
                                                                   FontFamily="PoppinsMedium"
                                                                   Text="{Binding EventTitle}"/>
                                                            <Label Grid.Column="1"
                                                                   Grid.Row="1"
                                                                   FontFamily="PoppinsMedium"
                                                                   Text="{Binding StartTime}"/>
                                                            <Label Grid.Column="2"
                                                                   Grid.Row="1"
                                                                   FontFamily="PoppinsMedium"
                                                                   Text="{Binding EndTime}"/>
                                                        </Grid>
                                                    </Grid>
                                                </DataTemplate>
                                            </CollectionView.ItemTemplate>
                                        </CollectionView>
                                    </RefreshView>
                                </StackLayout>
                            </xct:StateView>
                        </xct:StateLayout.StateViews>
                    </Grid>
`

and here is my view model code


`

         private async Task LoadData()
        {
            try
            {
                DataStatus = LayoutState.Loading;
                await Task.Delay(3000);
                var events = new List<EventModel>()
                {
                    new EventModel()
                    {
                        EventTitle = "Morning Routine",
                        StartTime = "06:00 AM",
                        EndTime = "06:30 AM",
                        EventDate = DateTime.Now,
                        DurationPerMinute = 30
                    },
                    new EventModel()
                    {
                        EventTitle = "Weekly Planning",
                        StartTime = "07:00 AM",
                        EndTime = "08:00 AM",
                        EventDate = DateTime.Now,
                        DurationPerMinute = 60
                    },
                    new EventModel()
                    {
                        EventTitle = "Business Meeting",
                        StartTime = "08:00 AM",
                        EndTime = "09:15 AM",
                        EventDate = DateTime.Now,
                        DurationPerMinute = 90
                    },
                    new EventModel()
                    {
                        EventTitle = "Morning Routine",
                        StartTime = "06:00 AM",
                        EndTime = "06:30 AM",
                        EventDate = DateTime.Now,
                        DurationPerMinute = 30
                    },
                    new EventModel()
                    {
                        EventTitle = "Morning Routine",
                        StartTime = "06:00 AM",
                        EndTime = "07:00 AM",
                        EventDate = DateTime.Now,
                        DurationPerMinute = 60
                    },
                };
                AddColorsToEvents(events);
                Events = events;
                DataStatus = LayoutState.Success;
            }
            catch (Exception exception)
            {
                await LoggerService.LogException(exception);
                DataStatus = LayoutState.Error;
            }
        }
        
`
