### ISSUE TITLE
Unable to tap on the ListView items in an Emulator

### ISSUE THREAD

**Issue by SelvaKumar68** [xamarin/Xamarin.Forms#1505]
### Description
When using the listview in the **Android 7.0 API Level 24 Intel Atom x86_64** emulator, the items Tapped event is not called when clicking on the listView item

### Steps to Reproduce

1. Use a Xamarin forms ListView and use ItemTapped Event.
2. Run the sample in **Android 7.0 API Level 24 Intel Atom x86_64** emulator.

### Expected Behavior
The Item tapped event has to get fired when the items are clicked
### Actual Behavior
Item tapped event is not fired.
### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 
 **Android 7.0 API Level 24 Intel Atom x86_64**
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
@SelvaKumar68 Which version of Xamarin.Forms are you using?

**Comment by jassmith** [comment]
Closed due to inactivity
