### ISSUE TITLE
Fix Shell Flyout color issues

### ISSUE THREAD

**Issue by pablo0219** [xamarin/Xamarin.Forms#15061]
Shell Flyout color issues in Xamarin.Forms 5.0.0.2291 (Last version available) and IOS 15(15.2)
Steps to Reproduce:
1. Xamarin.Forms 5.0.0.2291 and IOS 15
2. Default Visual Studio Project (with flyout)

Expected behavior:
Flyout should inherit background color from Shell.Background color
            <Style x:Key="BaseStyle" TargetType="Element">
                <Setter Property="Shell.BackgroundColor" Value="Blue" />

Actual Behavior
Background color is white.

Basic Information:
I believe this issue is related to the same following bugs listed:

https://github.com/xamarin/Xamarin.Forms/pull/14649
https://github.com/xamarin/Xamarin.Forms/issues/14505
https://github.com/xamarin/Xamarin.Forms/issues/14645

![Capture](https://user-images.githubusercontent.com/39707457/149649871-0b27af62-e960-4b8a-a142-c5e34147fedc.PNG)
![Capture1](https://user-images.githubusercontent.com/39707457/149649872-a3399fe9-2ef4-4769-b204-fe652a6201d4.PNG)

**Comment by pablo0219** [comment]
![Capture](https://user-images.githubusercontent.com/39707457/149649467-4278a728-d4e9-484b-8852-819b6b0eeafd.PNG)
![Capture1](https://user-images.githubusercontent.com/39707457/149649469-305dfe3a-60d7-4eb7-a31b-e84bff0c34e3.PNG)

**Comment by pablo0219** [comment]
I clicked he wrong button. Reopen it again.

**Comment by jfversluis** [comment]
Please provide a little reproduction project that shows this issue, thanks!

**Comment by pablo0219** [comment]
I was wrong!! I had a ListView in the flyout which was overriding the flyout background color. It looks that it's white by default. However, what it weird it's that I had a different behavior in IOS compared to Android. I will close the issue because it's not really related to the flyout.

**Comment by jfversluis** [comment]
Glad you figured it out and thanks for letting us know!
