### ISSUE TITLE
Errors while building Xamarin.Forms From source code

### ISSUE THREAD

**Issue by ravinderjangra** [xamarin/Xamarin.Forms#1507]
### Description
Showing Issue with Xamarin.Forms.Build.Tasks.XamlGTask

### Steps to Reproduce
1.  Get the latest code from official git and build

### Expected Behavior
It should work 

### Actual Behavior
Build Log
1>------ Build started: Project: Xamarin.Forms.Controls, Configuration: Debug Any CPU ------
1>E:\Project\XF\.nuspec\Xamarin.Forms.targets(70,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.XamlGTask" task could not be loaded from the assembly E:\Project\XF\.nuspec\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'file:///E:\Project\XF\.nuspec\Xamarin.Forms.Build.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building project "Xamarin.Forms.Controls.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 6 up-to-date, 0 skipped ==========

**Comment by kingces95** [comment]
I'm unable to reproduce the stated error; From a `Developer Command Prompt for VS 2017` command prompt I can successfully restore and build:
> C:\git\forms>c:\nuget\4.4.1\nuget.exe restore Xamarin.Forms.sln
> msbuild xamarin.forms.sln /p:platform=iPhone

Please attach a diagnostic build log as well as the environment and commands issued to reproduce the observed issue.

**Comment by samhouts** [comment]
Sometimes you need to build the Build.Tasks project *first* to ensure that it creates the dlls needed to build the rest of the project.

**Comment by ravinderjangra** [comment]
It was working fine before I updated my forked repo from the official repo.

**Comment by samhouts** [comment]
@ravinderjangra Close VS, and go to the `.nuspec` folder. Delete all `.dll` files in the folder. Restart VS, do a clean, and rebuild the `Build.Tasks` project, then the rest of the solution. That should do it for you. :)

**Comment by ravinderjangra** [comment]
@samhouts still the same. I will try again by cloning the latest again.

**Comment by ravinderjangra** [comment]
@samhouts  @kingces95 It even give me this issue while cloning.

repository 'https://github.com/xamarin/Xamarin.Forms.Build/' not found
clone of 'https://github.com/xamarin/Xamarin.Forms.Build' into submodule path 'E:/Project/XF/Xamarin.Forms.Build' failed
Failed to clone 'Xamarin.Forms.Build'. Retry scheduled
Cloning into 'E:/Project/XF/Xamarin.Forms.Build'...
remote: Repository not found.
repository 'https://github.com/xamarin/Xamarin.Forms.Build/' not found
clone of 'https://github.com/xamarin/Xamarin.Forms.Build' into submodule path 'E:/Project/XF/Xamarin.Forms.Build' failed
Failed to clone 'Xamarin.Forms.Build' a second time, aborting

**Comment by ravinderjangra** [comment]
@kingces95 Please help.
I tried using the same commands as you tried with newly cloned solution,
I am using VS 2017 Enterprise

**Comment by ravinderjangra** [comment]
It's working fine in mac. But I need this running on windows too...

**Comment by PureWeen** [comment]
@ravinderjangra    is this still giving you issues?  I'm new to the forms team and the Forms project has been building fine for me on windows.

**Comment by ravinderjangra** [comment]
Now it's working fine. I skipped submodule while cloning and rebuild all the projects one by one.
Thanks all for help.

**Comment by bobtheotherbuilder** [comment]
My issue's resolved by installing .Net Framework 4.7.2 developer pack.
