### ISSUE TITLE
[Question] How long for nuget package to release

### ISSUE THREAD

**Issue by archergod** [xamarin/Xamarin.Forms#15081]
I see Service Release 9 is there from 3 days, but not availabe on nuget yet. We are waiting for bug fix which is covered in SR9, Is this unusual delay or it take that much (or how much time) to appear on nuget?

**Comment by jfversluis** [comment]
Only thing I can say it's done when it's done :) 

We're doing additional checks to see if there is no regressions or other quality drops in there. Typically it should be pretty fast, this time it takes a bit longer. Sorry about that!

**Comment by MagicAndre1981** [comment]
> Only thing I can say it's done when it's done :)

any update on this? @jfversluis
