### ISSUE TITLE
Custom EntryRenderer - Input string was not in correct format for decimal properties

### ISSUE THREAD

**Issue by PacoRivera13** [xamarin/Xamarin.Forms#15098]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2019 16.11.7

### Description

I'm using a custom EntryRenderer for removing the borders on the input control like this:
```
public class BorderlessEntryRenderer : EntryRenderer
   {
      public BorderlessEntryRenderer()
          : base(Application.Context)
      {
      }

      protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
      {
         base.OnElementChanged(e);
         if (this.Control != null)
         {
            this.Control.SetBackground(null);
            this.Control.Gravity = GravityFlags.CenterVertical;
            this.Control.SetPadding(0, 0, 0, 0);
         }
      }
   }
```

When my app renders the control that is binding to a decimal property. 

```
public decimal OrderAmount
      {
         get => orderAmount;
         set
         {
            SetProperty(ref orderAmount, value);
         }
      }
```
I got the following error and I'm not able to enter any value.
**_Input string was not in correct format_**

I bind my control using code behind.
```
Binding textBinding = new Binding("OrderAmount");
                        textInput = new BorderlessEntry()
                        {
                           Margin = new Thickness(10, 0),
                           Placeholder = formObject.Caption,
                           Style = Application.Current.Resources.GetStyle("BorderlessEntryStyle"),
                           MaxLength = formObject.MaxLength,
                           IsReadOnly = formObject.ReadOnly,
                           HeightRequest = 30,
                           Keyboard = Keyboard.Numeric
                        };
                        textInput.SetBinding(Entry.TextProperty, textBinding);
```

### Steps to Reproduce

1. Create Android Xamarin App
2. Draw a control using code behind.

```
Binding textBinding = new Binding("OrderAmount");
                        textInput = new BorderlessEntry()
                        {
                           Margin = new Thickness(10, 0),
                           Placeholder = formObject.Caption,
                           Style = Application.Current.Resources.GetStyle("BorderlessEntryStyle"),
                           MaxLength = formObject.MaxLength,
                           IsReadOnly = formObject.ReadOnly,
                           HeightRequest = 30,
                           Keyboard = Keyboard.Numeric
                        };
                        textInput.SetBinding(Entry.TextProperty, textBinding);
```

3. Create a decimal property for binding 

### Did you find any workaround?

Not yet

**Comment by jfversluis** [comment]
Hey @PacoRivera13 seems like you are using Xamarin.Forms although you're saying you're not? But only Forms uses renderers :)

Could you specify which Forms version you're using? And if you could add a small reproduction sample that would be totally amazing and helpful. Thanks!

**Comment by PacoRivera13** [comment]
> Hey @PacoRivera13 seems like you are using Xamarin.Forms although you're saying you're not? But only Forms uses renderers :)
> 
> Could you specify which Forms version you're using? And if you could add a small reproduction sample that would be totally amazing and helpful. Thanks!

hi @jfversluis I found this
[https://social.msdn.microsoft.com/Forums/en-US/34ee55b7-7613-4b35-849f-75d3197ae966/entry-binding-decimal?forum=xamarinforms](url)

I was missing a converter which cause the issue, I'll close this.
Thank you!

**Comment by jfversluis** [comment]
Glad you figured it out, thanks!
