### ISSUE TITLE
xamarin forms app won't deploy

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15090]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/xamarin-forms-app-wont-deploy/1638916)._

---
[severity:I'm unable to use this version]

I just rebuilt my windows 10 system (21H2) and reinstalled VS 2022 17.1 Preview 2. This included reinstalling .NET 6.0 and several Android SDKs as well as the Samsung USB drivers to support my Galaxy S10+ as a test device.

I rebuilt several Xamarin Forms applications and successfully deployed and ran them targeting UWP. I do not run iOS apps as I do not have a Mac.

I then attempted to build and deploy to the Samsung device and the Versions 30 and 31 emulators that I had installed. Everything builds successfully but stops with "There were deploymemt errors" dialog box with NO OTHER MESSAGES or diagnostics. At about the same time Info Center pops up but is blank (EDIT: I discovered that this was unrelated.)

Before rebuilding the machine I had been running these applications successfully using the SAME version of Visual Studio.

Other than the popup dialog box, the attached screenshot file is the only information supplied. the "Show output from: Deployment" dialog box is empty.

---
#### Feedback Bot on 1/17/2022, 00:43 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by IndianaGary** [comment]
The issue still persists...

**Comment by jfversluis** [comment]
This one seems very hard to solve. I know you don't see any output on your side, but without any information it's hard to say what it going on. Seems like very specific to your setup as I can't reproduce it. Also unlikely a Xamarin.Forms issue, but more a tooling/Visual Studio issue.

**Comment by IndianaGary** [comment]
Dint know what happened but it spontaneously started working. 🙃

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jfversluis** [comment]
Not loving things that magically start working... But I'll take it for now :P Thanks for letting us know!

**Comment by IndianaGary** [comment]
That’s OK, it stopped working again… 😉

Do you know of any super-secret insider logging, tracing, or debugging tool(s)
I can use to troubleshoot deployment to an Android device or emulator?

Regards,
Gary
