### ISSUE TITLE
[Bug] There is no Cancel button for the iOS Shell SearchHandler input.

### ISSUE THREAD

**Issue by aodegov** [xamarin/Xamarin.Forms#15095]
### Description

Where is the 'Cancel' button for the iOS Shell SearchHandler control ?
Our users simply can not back from focused (selected) SearchHandler control input.
Once input is focused, this just collapses shell header with navigation buttons and there is no option to get back.
Please, return(or add) cancel button functionality for the Shell SearchHandler control.
 
![image](https://user-images.githubusercontent.com/24685526/151059965-4f48b74d-b8f9-408b-8c63-a394b6843b07.png)

**Comment by jfversluis** [comment]
Please add all the details from our bug issue that we have in place. Without it we're missing valuable information that makes it very hard to diagnose what potentially is going on here. Thanks
