### ISSUE TITLE
Issue Subclassing Native Views in net standard library

### ISSUE THREAD

**Issue by DevSharkOne** [xamarin/Xamarin.Forms#1510]
https://developer.xamarin.com/guides/xamarin-forms/platform-features/native-views/#Subclassing_Native_Views

Above sample do not run with net standard library 2.0 for Xamarin Forms

Help please!

**Comment by kingces95** [comment]
Please submit a zipped solution or GitHub repository exhibiting the issue; Please use the template provided when creating a new issue. The one that asks for the actual/expected behavior.

**Comment by DevSharkOne** [comment]
I am sorry.

### Description
I have changed my PCL project to a NetSantard Library and i am trying to implementing subclassing native views for using native controls in xamarin forms but i can not show the control and no error is showed.

### Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/35143072/34629832-a8cac748-f237-11e7-8323-213c834419a5.png)

2. 
![image](https://user-images.githubusercontent.com/35143072/34629925-fb4a7630-f237-11e7-937e-988e0ca1052c.png)

3. 
![image](https://user-images.githubusercontent.com/35143072/34629944-19e78ef2-f238-11e7-911c-51651541b807.png)


### Expected Behavior
![image](https://user-images.githubusercontent.com/35143072/34629964-2477b69e-f238-11e7-8b58-71f8f6b1d1a9.png)


### Actual Behavior
The native control is not showed in the xamarin forms page

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: Net Standard 2.0
  - iOS:  
  - Android: 5.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots



### Reproduction Link

The sample below show the PCL Project 

https://developer.xamarin.com/samples/xamarin-forms/UserInterface/NativeViews/SubclassedNativeControls/


The sample bellow is the Net Standard Library
https://1drv.ms/u/s!AulFit0ojL-U0WDYAM3nGMvJS2U4

**Comment by hartez** [comment]
Your issue is in your ItemsPage.xaml.cs:
```
[XamlCompilation(XamlCompilationOptions.Compile)]
```

[XAMLC is not compatible with native views](https://developer.xamarin.com/guides/xamarin-forms/platform-features/native-views/#Overview). 

So change that line to:
```
[XamlCompilation(XamlCompilationOptions.Skip)]
```
and your subclassed native view will show on the page.
