### ISSUE TITLE
[Bug] NavigationPage.Navigation.PushAsync null pointer exception on MacOS

### ISSUE THREAD

**Issue by bhaynesch** [xamarin/Xamarin.Forms#15121]
### Description
Adding a page to navigation on Mac OS gets a null pointer exception
### Steps to Reproduce

1. Create new NavigationPage object:            var page = new Page();
            NavigationPage.SetHasNavigationBar(page, false);
            NavigationPage = new NavigationPage(page);
2. Add a new page to the stack using PushAsync:  await NavigationPage.Navigation.PushAsync(page);
2. 
3. 

### Expected Behavior
New page is added to navigation stack and appears.  THis code functions correctly in iOS, Android, and WPF versions of our app.
### Actual Behavior
Null pointer exception in AddPage method of MacOS NavigationRenderer

Exception:  Object reference not set to an instance of an object
Call Stack:
  at Xamarin.Forms.Platform.MacOS.NavigationPageRenderer.AddPage (Xamarin.Forms.Page page, System.Boolean animated) [0x001b0] in <dfccd7b5c9234c70934be418ba0c3859>:0 
  at Xamarin.Forms.Platform.MacOS.NavigationPageRenderer.OnPush (Xamarin.Forms.Page page, System.Boolean animated) [0x0006e] in <dfccd7b5c9234c70934be418ba0c3859>:0 
  at Xamarin.Forms.NavigationPage.PushAsyncInner (Xamarin.Forms.Page page, System.Boolean animated) [0x000c9] in <4a0926af3fb243d29600c2bb4a37cfab>:0 
  at Xamarin.Forms.NavigationPage.PushAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00193] in <4a0926af3fb243d29600c2bb4a37cfab>:0 

### Basic Information

- Version with issue: 5.0.0.2125
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - MacOS:  Xamarin.Mac 4.0.30319
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Enterprise 2019 for Mac ===

Version 8.10.17 (build 2)
Installation UUID: c5aad316-7bf4-448e-8ae4-5be89408f256
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000162

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.162 (2020-02/2ca650f1f62) (64-bit)
	Package version: 612000162

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.101/Sdks
SDK Versions:
	6.0.101
	5.0.404
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.1
	5.0.13
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.416

=== .NET 5.0 SDK ===

SDK: 5.0.404

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.0.0.3 (Visual Studio Enterprise)
Commit: xamarin-android/d16-11/f0e3c2d
Android SDK: /Users/clarigentdevelopment/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: c633fe9
Java.Interop: xamarin/java.interop/d16-11@476bb5b
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.35.4@85460d3
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 01:17:52 UTC

=== Apple Developer Tools ===

Xcode 13.2.1 (19586)
Build 13C100

=== Xamarin.Mac ===

Version: 8.4.0.0 (Visual Studio Enterprise)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin.iOS ===

Version: 15.4.0.0 (Visual Studio Enterprise)
Hash: 8fc41ae82
Branch: xcode13.2
Build date: 2021-12-09 01:07:56-0500

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 02:44:16 UTC

=== Build Information ===

Release ID: 810170002
Git revision: 58f7763d4d64fcf005a474d25a5d9fd5ce46d7f5
Build date: 2022-01-05 12:51:28-05
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.1.0
Darwin 21.2.0 Darwin Kernel Version 21.2.0
    Sun Nov 28 20:29:10 PST 2021
    root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 x86_64


```

</details>

**Comment by jfversluis** [comment]
Hey thanks for the report! Would you maybe be able to put this in a small sample project? I'm not entirely sure what you're doing in code. Some testing on my side doesn't show this issue.

Thanks!

**Comment by bhaynesch** [comment]
I created a stripped down program that uses MVVM, has two pages, and during startup, it pushes both pages on the stack to try and simulate what I'm seeing.  I created a WPF project that uses this base code and it worked so I added a MacOS project and unfortunately for me, it worked there too.  So now I'm at a loss at what to try next.  Our application is very complicated and has it's own navigation service that sits on top of the Xamarin one, uses Autofac to register modules to associate view models and pages, and lots of other infrastructure type things that are difficult to simulate in a sample app.  Do you have any suggestions on what I can do next to try and figure out why PushAsync is crashing in my application?  The page I pass in looks valid to me so there must be something else it doesn't like but I don't know where Xamarin.Forms is crashing (other than in AddPage).  I tried with the current version 5.0.0.2337 and with the version my application is using (5.0.0.2125) and couldn't make it fail in my sample app.

**Comment by bhaynesch** [comment]
I changed my sample program to more closely emulate what I do in our app and now PushAsync hangs on Mac and never returns.  But it works fine on WPF.  In the attached solution, Test->ViewModel->BasePageViewModel, the NextPage function gets called from a command button in the Page1ViewModel.  When the app launches, page 1 comes up, user hits button to navigate to page 2.  On WPF page 2 appears.  On Mac, the PushAsync call never returns.  Don't know if this is related to the crash I see in our app but definitely not correct behavior.  In the attached, I've only included the solution, MAC, and WPF projects.
[Test WPFandMAC.zip](https://github.com/xamarin/Xamarin.Forms/files/8035654/Test.WPFandMAC.zip)
.

**Comment by jfversluis** [comment]
I don't see any null pointer, but I do see that you add a `.Wait()` to an async call which is typically not something you want to do. If I remove that, it all works fine :)

Going to assume that this is a wrong usage of async/await. If you still see a NullReferenceException somewhere please let me know

**Comment by bhaynesch** [comment]
I am unable to reproduce the null pointer exception in my sample app, it only occurs in my full app and only on Mac.  Is there a way for me to debug the Xamarin.Forms implementation for Mac myself so that I can try to figure out the problem?

FYI, I wrote my sample app for WPF first and it worked fine with the .Wait on the call.  Interesting that it only hangs on Mac.

**Comment by jfversluis** [comment]
The joys of cross-platform development. What works on one platform does not necessarily work on the other 😅 in either case I would reevaluate why you are doing it that way, it shouldn't be needed and can cause deadlocks like that.

You can clone this repo and build Xamarin.Forms from there. An easy(-ish) way to hook it up to your own source is remove the NuGets and add the projects from this solution as references to your projects and start running from there. Or, we have a Gallery App in there that has reproductions for a lot of issues. You could add your case there and reproduce it through that.

**Comment by bhaynesch** [comment]
I'm chasing my tail trying to make this work with a local copy of Xamarin.Forms.  I have other 3rd party packages that also depend on Xamarin.Forms so they are trying to install it on top of my local copy.  And I literally have hundreds of errors in Visual Studio while trying to use a local copy.  I guess I have to give up on the idea of a "one size fits all platforms" for a Xamarin app and figure out how to rewrite my application so that I have a Mac only version.  That sucks but I feel like I'm going to spend more time trying to fix Xamarin issues.
