### ISSUE TITLE
Listview Data Binding on ItemTemplate binds to ViewModel, not Item in Items source.  

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15132]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Listview-Data-Binding-on-ItemTemplate-bi/1648023)._

---
[severity:I'm unable to use this version] [regression] [worked-in:17.0 build 6509]
VS Mac 2022 - 17.0 preview (17.0 build 6509)

Tried to create a XAML page with a Listview to display a label to display one of the properties in the model bound to the list.

The label in the ItemTemplate is bound to the description property (string) from the type in the ListView.ItemsSource.

However, I get a compiler error that complains that Description is not part of the view model, 

**XamlC error XFC0045: Binding: Property "Description" not found on ".../ViewModels.HomeViewModel"**

It's not supposed to be part of the ViewModel.

The problem also occurs in the maps sample of the Xamarin-Forms-Samples ..   

https://github.com/xamarin/xamarin-forms-samples/blob/main/WorkingWithMaps/WorkingWithMaps/WorkingWithMaps/PinItemsSourcePage.xaml 

---
#### Feedback Bot on 1/26/2022, 11:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### John Hunter on 1/27/2022, 08:18 AM: 

<p>Just as a followup, I was able to get the app to compile and run by adding a “x:DataType” to the DataTemplate item.</p>
<pre><code>    &lt;maps:Map x:Name=&quot;map&quot;
              MapClicked=&quot;OnMapClicked&quot;
              ItemsSource=&quot;{Binding MapLocations}&quot;&gt;
        &lt;maps:Map.ItemTemplate&gt;
            &lt;DataTemplate x:DataType=&quot;models:MapLocation&quot;&gt;
                &lt;maps:Pin Position=&quot;{Binding Position}&quot;
                          Address=&quot;{Binding Address}&quot;
                          Label=&quot;{Binding Description}&quot; /&gt;
            &lt;/DataTemplate&gt;
        &lt;/maps:Map.ItemTemplate&gt;
    &lt;/maps:Map&gt;
</code></pre>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Thanks for the report! I see your original problem was solved. I tried running the Maps sample as pointed out, but that seems to run fine on my end. Let me know if there are still any problems you're facing with this!

**Comment by enjoysmath** [comment]
Um... I'm currently having the exact same issue except their proposed solution does not work!  Same issue!  Also I'm using all standard controls except for an innermost (DataTemplated list item of model type ModbusCommand).  Instead of receivng {Binding} pointing to ModbusCommand it points to the outer View's ViewModel...  Bizarre!

See SO Post: https://stackoverflow.com/q/77809597/7076615
