### ISSUE TITLE
UWP Label with TextType=HTML can go into infinite loop

### ISSUE THREAD

**Issue by capdj** [xamarin/Xamarin.Forms#15138]
As per title, I'm seeing my UWP XF app hang when opening a page with labels on it that have TextType=HTML.

This loop in UAP.LabelHtmlHelper.AddLineBreakIfNeeded looks suspicious:

```
		var lastInline = inlines[inlines.Count - 1];
			while ((lastInline is Windows.UI.Xaml.Documents.Span))
			{
				var span = (Windows.UI.Xaml.Documents.Span)lastInline;
				if (span.Inlines.Count > 0)
				{
					lastInline = span.Inlines[span.Inlines.Count - 1];
				}
			}
```

If lastInline is a Span but with Inlines.Count=0, won't this loop forever? Perhaps there should be an "else break" on the if check?

For example, I can see the hang if the HTML I assign to the label text contains an empty tag such as 
`<p></p>`

**Comment by jfversluis** [comment]
Thanks for the report and investigation on this. To test your theory it would be very helpful if you could provide is with a reproduction sample that shows this issue.

Also, please use the bug report issue template next time. Thanks!

**Comment by jfversluis** [comment]
No response to our request for more info, going to assume this issue has been resolved by the author.
