### ISSUE TITLE
SqlCommandBuilder must not be used in Xamarin Forms

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15133]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SqlCommandBuilder-darf-nicht-in-Xamarin-/1649081)._

---
var dataadapter = new SqlDataAdapter(asqlstr, Adocon);
new SqlCommandBuilder(dataadapter);//erzeugt haarsträubende Fehler  in einer
XAmarins app, bei mir

Nachricht = Could not resolve type with token 01000057 from typeref (expected class 'System.Data.SqlClient.SqlCommandBuilder' in assembly 'System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')

---
#### Feedback Bot on 1/27/2022, 11:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Hey there author, I hope you get to read this here! Unfortunately this issue seems to lack a lot of details about what you are trying to do. Please open a new issue here with all the details in the template if you're still facing this. Thanks!
