### ISSUE TITLE
Equal Margin between last control on screen and bottom of screen 

### ISSUE THREAD

**Issue by raymond-dillon** [xamarin/Xamarin.Forms#15135]
I have a Layout that has a list view and an editor with the property AutoSize="TextChanges" 

When the keyboard appears, the view is shifted upwards but the margin between the list view and the top of the editor and the bottom of the editor and the bott9m of the screen is uneven. 

![42273e20-9668-4004-a7a6-65ffef5872f1.png](https://user-images.githubusercontent.com/28100585/153102160-333aa198-5fa3-423b-9791-66a8e151cce7.png)

How can I make X an equal margin as shown in the image?

**Comment by jfversluis** [comment]
Please see #15134 thanks!
