### ISSUE TITLE
[Internal] VS2017 does not recognize .NET Standard 2.0 in Xamarin.Forms

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#1514]
### Description

Can't build Xamarin.Forms after checking it out because VS does not recognize .NET Standard 2.0 in some projects.

### Steps to Reproduce

1. Make sure you're running a Windows 10 instance (Enterprise in my case)
2. Install VS2017 Enterprise (15.5.2 with .NET 4.7)
3. Check out Xamarin.Forms
4. Rebuild Xamarin.Forms.ControlGallery.Android

### Expected Behavior

Compilation should succeed without errors.

### Actual Behavior

11 projects cannot be built because VS does not recognize .NET Standard 2.0 in their target framework list. Right click a project and go to Properties. Note that the dropdown shows 1.6 as the maximum version recognizable by VS. Since it can't find 2.0, the current selection is empty.

![capture](https://user-images.githubusercontent.com/16855542/34627056-be6b42a2-f224-11e7-89ae-03e2dc079d85.PNG)

![capture2](https://user-images.githubusercontent.com/16855542/34627153-1bdb3c9e-f225-11e7-93bf-47f4bb816eaf.PNG)

.NET Core 2.0 is installed. If I create a blank .NET Standard library, VS does recognize .NET Standard 2.0 in that case. This seems to be isolated to XF solution.

![capture3](https://user-images.githubusercontent.com/16855542/34627173-347bbbd4-f225-11e7-989c-709df3e21982.PNG)

You should try replicating this on a clean install of Win10. Maybe I'm missing something that needs to be installed. Running VS in admin mode did not make a difference.

**Comment by rmarinho** [comment]
what nuget you have installed ?

**Comment by rmarinho** [comment]
make sure you have all this installed:

```
VisualStudio (VisualStudioChannel.Stable, VisualStudioTier.Enterprise, "15.5.2")
  .Workload (VisualStudioWorkload.ManagedDesktop)
  .Workload (VisualStudioWorkload.NetCrossPlat)
  .Workload (VisualStudioWorkload.NativeDesktop)
  .Workload (VisualStudioWorkload.Universal)
  .Component (VisualStudioComponent.Microsoft_VisualStudio_Component_Windows81SDK)
  .Component (VisualStudioComponent.Microsoft_VisualStudio_Component_Windows10SDK_16299_UWP)
 .Component (VisualStudioComponent.Microsoft_VisualStudio_Component_Windows10SDK_16299_UWP_Native)
  .Component (VisualStudioComponent.Component_Android_SDK23)
  .Component (VisualStudioComponent.Component_Android_SDK25)
  .Component (VisualStudioComponent.Component_JavaJDK)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_5_1_TargetingPack)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_5_2_TargetingPack)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_5_TargetingPack)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_6_2_SDK)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_6_2_TargetingPack)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_7_SDK)
  .Component (VisualStudioComponent.Microsoft_Net_Component_4_7_TargetingPack);
```

**Comment by rmarinho** [comment]
also nuget 4.4.1 , (make sure the path uses that)

the sdk version used is here https://github.com/xamarin/Xamarin.Forms/blob/master/global.json#L5

**Comment by adrianknight89** [comment]
I have Nuget 4.5.0 which is what's installed when you install VS2017 15.5.2. I have those components installed as well. I just spinned up a new Windows VM and installed VS2017 on Azure. Same issues there as well.

Are you suggesting that Nuget 4.4.1 should be used as opposed to the newer version?

**Comment by adrianknight89** [comment]
Workaround for now was to delete `global.json` and rebuild solution. The file is messing up with my workspace for some reason even though I have everything installed.
