### ISSUE TITLE
VS 16.11.3: Xamarin project build errors not showing in Error List

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15147]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-16113:-Xamarin-project-build-errors/1537079)._

---
I'm finding that some errors building the Xamarin projects are not showing in the list of errors.
The build fails and I can find the error in the logs (see highlighted error in image below). However, the error is not in the list of errors.
The error below is for a missing x:Key in resources.

I've also found the opposite. Errors show in the list of Errors but the build completes without errors. The only way to get rid of the errors is by restarting VS.

! [image.png] (https://aka.ms/dc/image?name=Bb23751b45eb94f51b0a6aef7cd52a55c637679732564347044_20210923-155415-image.png&tid=b23751b45eb94f51b0a6aef7cd52a55c637679732564347044)

---
#### Feedback Bot on 9/23/2021, 01:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/4/2022, 00:01 AM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

#### Alison Jin [MSFT] on 1/21/2022, 02:29 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ?<br>
If so, could you please provide a sample solution that has this problem so that we can conduct further research?</p>
<p>We look forward to hearing from you!</p>

#### Roberto Mencia Franco on 2/1/2022, 07:53 PM: 

<p>Hi Alison, is your job to ask the users to test VS with newer versions to see if the error goes away?<br>
Why don’t you try to see if it works or not? I’m not your tester. I pay for VS to work well without errors.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Seems like this is a long time ago and a VS issue. Going to assume this is fixed by now, if not, please let us know!
