### ISSUE TITLE
Rebuild from an iOS project always has an error: Xamarin.iOS.Common.targets(254,3): error : The linker output contains more than one assemblies named ''

### ISSUE THREAD

**Issue by Gerome90** [xamarin/Xamarin.Forms#15159]
### Description

Hello Xamarin team,

I have 6 iOS projects and want to build it (DEBUG / RELEASE mode). All referenced iOS projects are running through. The main project has one of these errors:

- **9>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error : The linker output contains more than one assemblies named ''.**

OR

- **C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(254,3): error MT2103: Error processing assembly ', Version=4534.4542.4560.4570, Culture=�, PublicKeyToken=null, Retargetable=Yes': System.NotSupportedException: Specified method is not supported.** 

I have already read everything on this subject and tried some solutions. However, without success.

### Steps to Reproduce

1. Select an iOS-Project
2. Connecting with MAC
3. Clean & Rebuild
3. Error

### Environment

<details><summary>Windows- / MAC-Versions</summary>

- Windows Verions:
   - Visual Studio 2022 17.0.6

- MAC Versions:
   - MAC OS X 11.5.1
   - XCode 13.2.1 (13C100)
   - Visual Studio for MAC 8.10.18 (build 11)
   - Mono Framework 6.12.0.162
   - Xamarin iOS 15.4.0.0 

</details>

### Build Logs

[BinaryProcessBuild.zip](https://github.com/xamarin/Xamarin.Forms/files/8078275/BinaryProcessBuild.zip)

### Screenshots

<details><summary>Project Settings: Build (Screenshot)</summary>

![Build_Settings](https://user-images.githubusercontent.com/49303743/154215483-8ae82118-34c8-4756-b959-7df6a1771523.PNG)

</details>

<details><summary>Project Settings: Build Expert (Screenshot)</summary>

![Build_Settings_Expert](https://user-images.githubusercontent.com/49303743/154215931-8c2fe320-86a6-4249-acb0-59d22bbf16ec.PNG)

</details>

<details><summary>Project Settings: iOS-Build (Screenshot)</summary>

![iOS_Build_Settings](https://user-images.githubusercontent.com/49303743/154216029-7caf56a1-f849-40c0-92aa-8990a59ba0c6.PNG)

</details>

**Comment by jfversluis** [comment]
@dalexsoto this looks more like something in your area?

**Comment by Gerome90** [comment]
I have now copied the entire project and brought it to the MAC. There the projects can be compiled and debugged. 
There again there are other problems, but they are under control.

So the problem must be with the current Visual Studio version (Windows). 
So I can only run the Android projects. On Windows, all the version control is there. On the MAC, I can't get those to integrate. Only GIT is supported.

Can anyone help me?

**Comment by jfversluis** [comment]
If you think this is an issue with Visual Studio, please open an issue with them through the Help > Send Feedback > Report a Problem menu.

I think for Visual Studio for Mac only Git and Subversion are supported, also see here: https://docs.microsoft.com/visualstudio/mac/version-control

For now closing the issue as there doesn't seem to be any work for us here.
