### ISSUE TITLE
[Bug] Navigation Bar doesn't appear until you start scrolling

### ISSUE THREAD

**Issue by NikkiTheStitchQueen** [xamarin/Xamarin.Forms#15151]
### Description
Even with a Shell.BackgroundColor and Shell.Foreground color specified, the navigation bar does not appear until I start scrolling. This occurs in iOS, even with a brand new Xamarin.Forms project.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-large-title

### Steps to Reproduce

1. Create a new Xamarin.Forms project
2. Set a Background/Foreground color (I used a dark blue)
3. Deploy to iPhone simulator
4. Note that when your app launches, the title bar doesn't appear until you start scrolling.

### Expected Behavior
Navigation bar will always appear

### Actual Behavior
Doesn't appear on load - only appears when scrolling. 

### Basic Information

- Version with issue: iOS 15
- Last known good version: Since I am using a simular
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
Please add a reproduction project to demonstrate this issue or at least fill out the info in the template. What version of Xamarin.Forms are you using? Have you tried updating to the latest version?
