### ISSUE TITLE
Image is not properly visible in PDF pages in IOS version 15.2

### ISSUE THREAD

**Issue by Mohanaraja** [xamarin/Xamarin.Forms#15168]
### Description

Image is not properly visible in PDF pages in IOS version 15.2

### Steps to Reproduce

1. Run the attached sample
2. Click the button and load the pdf
3. image is missing on that pdf page.

### Basic Information

-iOS 15.2:
- It's working fine in the iOS 14 version

please find the sample link :
https://www.syncfusion.com/downloads/support/directtrac/general/ze/GettingStartediOS-846132728 

Expected result:
https://www.syncfusion.com/downloads/support/directtrac/general/Expected_output-1497916220

**Comment by jfversluis** [comment]
Thanks for the report! Although the Xamarin.Forms package is installed on this project, no Xamarin.Forms seems to be used at all. This is all Xamarin.iOS code. Additionally, it seems to work mostly for me

![image](https://user-images.githubusercontent.com/939291/154666956-ae221cab-a49e-4d5e-8bcf-01c980ece6a6.png)

Closing this one here, if you still think there is an issue, please open one on the Xamarin.iOS repository.

Thanks!
