### ISSUE TITLE
Visual Studio 2017 Preview - Can not create a Xamarin.Forms Application

### ISSUE THREAD

**Issue by etrupja** [xamarin/Xamarin.Forms#1516]
I am currently using this version of Visual Studio:
![image](https://user-images.githubusercontent.com/20356633/34642624-7864bf98-f316-11e7-9bc0-cdeac54c9e7d.png)

Whenever I try to create a Xamarin.Forms project I get the following error: 
![image](https://user-images.githubusercontent.com/20356633/34642626-7fb61f9e-f316-11e7-9d88-8e032c46c0b8.png)

After I click the Okay button I get the following window which actually does not change anything:
![image](https://user-images.githubusercontent.com/20356633/34642628-8937c450-f316-11e7-909a-e5989ec601f8.png)

**Comment by pauldipietro** [comment]
This is not an XF/API specific issue, and will be closed. I might suggest filing a report through VS and/or trying to repair your installation. Please only use the issues page to file issues with XF itself.
