### ISSUE TITLE
 I Need SerialPort on Android Device.

### ISSUE THREAD

**Issue by mzy666888** [xamarin/Xamarin.Forms#15175]
## Demand

I need to use the serial port of Android device to communicate with other modules. However, Xamarin.Forms does not provide the official serial port call module.

**Comment by jfversluis** [comment]
Hey @mzy666888 thanks for the report! However, we won't be taking any feature requests for Xamarin.Forms anymroe as we're transitioning to .NET MAUI. Thanks!
