### ISSUE TITLE
[Bug] Animations are laggy on Pixel 5

### ISSUE THREAD

**Issue by SymxnCreator** [xamarin/Xamarin.Forms#15183]
### Description
The animations in Xamarin.Forms like FadeTo, ScaleTo, etc. are stuttering on the Pixel 5. I'm not sure, but I think it's due to the frame rate, which has a value of 90 on the Pixel 5. I can't currently test whether the problem also occurs on other smartphones with a frame rate higher than 60. The animations run smoothly on smartphones with a frame rate of 60.

Is this problem fixable or known?

**Comment by jfversluis** [comment]
It would really help if you could add a small reproduction sample, the version of Xamarin.Forms that you are using and how we can test this ourselves. Thanks

**Comment by jfversluis** [comment]
No response to our request for more info, closing this one
