### ISSUE TITLE
[Bug] [iOS] The Label's FontSize not get changed based on Accessibility setting after defined explicit FontSize for label

### ISSUE THREAD

**Issue by vigneshrameshsync** [xamarin/Xamarin.Forms#15196]
### Description

The Label's FontSize not get changed based on Accessibility setting after defined explicit FontSize for label.

### Steps to Reproduce

1. Go to settings -> Accessibility -> Display & Text Size -> Larger Text -> Turn on "Larger Accessibility Sizes".
2. Run the sample from the attachment.

### Expected Behavior
The Accessibility size will be apply for Label too.

### Actual Behavior
The Label's FontSize not get changed based on Accessibility settings.

Version with issue:
Last known good version:
Platform Target Frameworks:
Android: Android SDK version 9.0 (API 28)
UWP: Windows 10, version 2004 (10.0; Build 19041)
NuGet Packages:
Xamarin.Forms version: 5.0.0.2196
Xamarin.Essentials version: 1.7.0
Microsoft.NETCore.UniversalWindowsPlatform version: 6.2.12
NETStandard.Library version: 2.0.3
Affected Devices:
IPhoneSimulator 12 pro Max.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots
<img width="184" alt="image" src="https://user-images.githubusercontent.com/92786682/156554613-a3d7fa9e-e3e2-4610-90ac-daeae768bcdb.png">

### Reproduction Link

[GettingStarted.zip](https://github.com/xamarin/Xamarin.Forms/files/8177667/GettingStarted.zip)

### Workaround

Not found yet.

**Comment by jfversluis** [comment]
Font scaling only works for named sizes, not for fixed font sizes, sorry about that. With .NET MAUI around the corner I don't think we will be changing this for Xamarin.Forms anymore. In .NET MAUI this works out of the box. Also see: https://docs.microsoft.com/xamarin/xamarin-forms/platform/ios/named-font-size-scaling
