### ISSUE TITLE
[Bug] Missing nuget for SR10

### ISSUE THREAD

**Issue by holecekp** [xamarin/Xamarin.Forms#15214]
### Description
I know that we should not ask when the Nuget for SR10 will be ready. But it has been almost 3 weeks since the version has been released so I will try it anyway :-). Is everything all right and the preparation of the Nuget is still in progress?

**Comment by jfversluis** [comment]
No need to try it anyway, we're still working on it, thanks!

**Comment by MagicAndre1981** [comment]
ok, a [SR10.1 was tagged](https://github.com/xamarin/Xamarin.Forms/tree/release-5.0.0-sr10.1) so we will get this version sooner or later.
