### ISSUE TITLE
Embedded icon font shows square box instead of actual icon on UWP release mode

### ISSUE THREAD

**Issue by sheharyarshahid** [xamarin/Xamarin.Forms#15225]
### Description
Embedded icon fonts are not showing actual icons for UWP on release mode. It only shows a square box instead of an actual icon. 

### Steps to Reproduce

1. Add any otf/ttf font file in Resources/Fonts folder of .NET standard library project
2. Set build action of the font file to Embedded resource
3. Change to release mode and run the UWP app

### Expected Behavior
Should work the same as it works in Debug mode

### Actual Behavior
 Shows square boxes instead of the actual icon

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - UWP:  Windows 11 Build 22000

**Comment by jfversluis** [comment]
While this definitely could be a better experience, it's not a bug unfortunately. See here for the solution: https://github.com/xamarin/Xamarin.Forms/issues/12404#issuecomment-713638339
