### ISSUE TITLE
[UWP] Extension methods for Color ToWindowsColor() and ToBrush() not accessible

### ISSUE THREAD

**Issue by mubold** [xamarin/Xamarin.Forms#1522]
### Description
The ``ToWindowsColor()`` and `ToBrush()`` extension methods for Color are not available on UWP because the static class ConvertExtensions in which they are found is ``internal`` instead of ``public``
See : https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/ConvertExtensions.cs#L6

Also, less important but all other implementations of this function on other platforms are in a class named ColorExtensions, I suggest renaming it to be more consistent.

### Expected Behavior

The static class should be public instead of internal, so that those methods can be used outside of Xamarin.Forms, especially useful for renderers.

### Actual Behavior

Extension methods cannot be used.

**Comment by jfversluis** [comment]
Looks like this can be closed, both are public on master: https://github.com/mubold/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/ColorExtensions.cs

**Comment by jfversluis** [comment]
Wow, I don't know how I ended up there, but you're right
