### ISSUE TITLE
2.5.0.122203 not available on NuGet

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/Xamarin.Forms#1524]
### Description
The latest release for Xamarin Forms is _2.5.0 Service Release 3 (2.5.0.122203)_, whereas the latest version on NuGet is 2.5.0.121934. I don't know the details of the release process, but since 2.5.0.12203 is released since 21 days (as of today), I would expect to be available on NuGet as well.

### Steps to Reproduce
1. Go to https://github.com/xamarin/Xamarin.Forms/releases, check latest version --> 2.5.0.122203
2. Go to https://www.nuget.org/packages/Xamarin.Forms/, check latest version --> 2.5.0.121934

### Expected Behavior
Latest release is available on NuGet.
### Actual Behavior
Latest release is not available on NuGet.

**Comment by johannes-schmitt** [comment]
Sorry, I just saw https://github.com/xamarin/Xamarin.Forms/issues/1318 which clarified most of my questions.

How is the suggested (best practice) way of consuming the latest version (e.g. if it contains a bug fix which is important for my project)?

**Comment by jalbertSyncroTech** [comment]
I have the same issue @johannes-schmitt, thanks for posting that link!  I updated #1318 with a request to include more information on the releases page.

Don't know if this will work for you, but you can include a solution level NuGet.Config file that lists a local folder as one of the package sources.

**Comment by insearchof1230** [comment]
I think is the more to this story... If you look at the link below, a 2.5.0.122203 package was published to Nuget but was pulled 3 days later. (3,685 downloads in...)

I'm pretty sure there is/was a breaking bug that STILL isn't resolved to date and looking at the issues list on GitHub (90+) I'm not sure when sr3 will be released.

https://www.nuget.org/packages/Xamarin.Forms/2.5.0.122203

**Comment by insearchof1230** [comment]
2.5.0.122203 looks to be live in Nuget again, but it doesn't look to be a repackage.

**Comment by rmarinho** [comment]
it was just unlisted waiting for 15.5 sr 3 to be shipped

**Comment by EmilAlipiev** [comment]
15.5.3 is already available what is it waiting for?

**Comment by hartez** [comment]
> How is the suggested (best practice) way of consuming the latest version (e.g. if it contains a bug fix which is important for my project)?

If a package version is unlisted but you want to install it and you know the version number, you can do so with the command line tool, using the `-Version` option: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-install
