### ISSUE TITLE
[Bug] [Android] Google Emoji Policy Violation

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#15245]
### Steps to Reproduce

1. Create one or more labels 
2. Put the following text (extracted from https://developer.android.com/guide/topics/ui/look-and-feel/emoji2#custom-views-appcompat) as the Text value(s)
3. Run it on Android 11 or Lower 

### Expected Behaviour

It should display (as it does in iOS):

<img width="379" alt="image" src="https://user-images.githubusercontent.com/5879559/159603880-5b7b4eb6-c25a-45ca-b222-17b90877f48a.png">

13.1: 😶‍🌫️, 🧔🏻‍♀️, 🧑🏿‍❤️‍🧑🏾
13.0: 🥲, 🥷🏿, 🐻‍❄️
12.1: 🧑🏻‍🦰, 🧑🏿‍🦯, 👩🏻‍🤝‍👩🏼
12.0: 🦩, 🦻🏿, 👩🏼‍🤝‍👩🏻

### Actual Behaviour

It displays tofu:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5879559/159603765-cc0ebf16-cf76-4893-abea-589641b93ca8.png">

### Basic Information

- Version with issue:

Latest (and all?)

- Last known good version:

N/A

- Platform Target Frameworks: 
  - iOS: Any
  - Android: 12 (31)
  - UWP:  Not tested
- Android Support Library / AndroidX Version: Latest 
- NuGet Packages: Nothing but the defaults from Xamarin.Forms's blank template. Also tried installing https://www.nuget.org/packages/Xamarin.AndroidX.Emoji2 to no avail) 
- Affected Devices:

Tested on Moto g6 Play running Android 8.0.0

**Comment by amirvenus** [comment]
The issue is potentially due to using `TextView` instead of `AppCompatTextView`.

**Comment by jfversluis** [comment]
You're right, using the `AppCompatTextView` fixes it. I'm kind of concerned about just replacing that while we're in maintenance mode though...

**Comment by amirvenus** [comment]
It runs the risk of all current Forms apps being in violation of the Google Play policies.

**Comment by jfversluis** [comment]
Do you have any more information about why this would be a violation and if Google will actively block apps because of it?

**Comment by amirvenus** [comment]
Extracted from:
https://support.google.com/googleplay/android-developer/answer/11190644?hl=en


Our emoji policy is designed to promote an inclusive and consistent user experience across the Google platform. 

Apps running on Android 12 and above must comply with the latest Unicode version within 4 months of public availability.

In order to remain compliant, developers MUST follow one of the options:

If [AppCompat](https://developer.android.com/jetpack/androidx/releases/appcompat) is already in use, make sure emoji is enabled.
Use an existing [EmojiCompat](https://developer.android.com/reference/androidx/emoji/text/EmojiCompat) library across all surfaces within the app. This should work with custom views that directly use [StaticLayout](https://developer.android.com/reference/android/text/StaticLayout).
Update the handling and font/images for emoji based on the latest version of Unicode.
Use the emoji examples below to test if your app is compliant with the latest Unicode Version:



Examples | Unicode Version
-- | --
😶‍🌫️ 🧔🏻‍♀️ 🧑🏿‍❤️‍🧑🏾 | 13.1
🥲 🥷🏿 🐻‍❄️ | 13.0
🧑🏻‍🦰 🧑🏿‍🦯 👩🏻‍🤝‍👩🏼 | 12.1
🦩 🦻🏿 👩🏼‍🤝‍👩🏻 | 12.0

<p style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0.25rem 0px 0.75rem; caret-color: rgb(31, 31, 31); color: rgb(31, 31, 31); font-family: &quot;Google Sans Text&quot;, Roboto, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 11.375px; text-align: left;"> </p><p style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0.25rem 0px 0.75rem; caret-color: rgb(31, 31, 31); color: rgb(31, 31, 31); font-family: &quot;Google Sans Text&quot;, Roboto, &quot;Helvetica Neue&quot;, Helvetica, sans-serif; font-size: 11.375px; text-align: left;">Please consult<span class="Apple-converted-space"> </span><a href="https://developer.android.com/guide/topics/ui/look-and-feel/emoji2" rel="noopener" target="_blank" style="color: rgb(103, 58, 183); text-decoration: none;">this resource</a><span class="Apple-converted-space"> </span>for additional emoji compatibility guidance.</p>Examples	Unicode Version
😶‍🌫️ 🧔🏻‍♀️ 🧑🏿‍❤️‍🧑🏾	[13.1](https://emojipedia.org/emoji-13.1/)
🥲 🥷🏿 🐻‍❄️	[13.0](https://emojipedia.org/unicode-13.0/)
🧑🏻‍🦰 🧑🏿‍🦯 👩🏻‍🤝‍👩🏼	[12.1](https://emojipedia.org/emoji-12.1/)
🦩 🦻🏿 👩🏼‍🤝‍👩🏻	[12.0](https://emojipedia.org/emoji-12.0/)
 

Please consult [this resource](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2) for additional emoji compatibility guidance.

**Comment by jfversluis** [comment]
Awesome, thanks! Will do some testing and discussing and come back to this :)

**Comment by jfversluis** [comment]
I've opened a PR with the change [here](https://github.com/xamarin/Xamarin.Forms/pull/15279). I would be very thankful if you would assist me in helping me test this. When the build completes there should be a NuGet resulting from it. If you could install that on an existing project and see if all Labels behave as they should that would be very helpful :)

The process for the NuGets [is described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages). Make sure you download the exact version of that build, other NuGets on that feed will not have that same change.

**Comment by amirvenus** [comment]
Thanks for the PR. 

Unfortunately upon testing the with PR's nuget package, the issues persists despite installing Xamarin.AndroidX.Emoji.Bundled nuget package as well and using this on the MainActivity.cs:

```
EmojiCompat.Config config = new BundledEmojiCompatConfig(this);
            EmojiCompat.Init(config);
```

Please advise

**Comment by amirvenus** [comment]
EDIT:

I am pleased to announce that it worked for Labels after installing this package:

https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat

However, the issue persists for Entries and Editors:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/5879559/161613577-a170e109-e201-4729-8d5a-a1671936f616.png">

I hope it helps @jfversluis

**Comment by amirvenus** [comment]
Could we merge this PR anyway? Having some controls compliant is better than nothing and hopefully Buttons will become compliant as well in due course [MAUI, maybe?]

**Comment by jfversluis** [comment]
To make things very clear. What is the current status?

With the current version of Xamarin.Forms 5.0.0.2401 and that new AndroidX.AppCompat version it works for labels and everything? But not Entries and Editors? Is that what you are saying?

Because I don't see anything wrong with the screenshot that you posted?

**Comment by amirvenus** [comment]
The current status:

When I install your proposed PR's nuget version in addition to installing AndroidX.AppCompat 1.4.1.1, Emoji renders properly in many places except for Entries/Editors (`EditText`).

I think if this table is followed, we wouldn't have any problem whatsoever:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/5879559/162185746-8970aa8d-d02a-425e-8443-b0db8c8f8ee1.png">

BUT if it's too much work, we ought to go with the current PR as it supports most of the controls (except for Entries/Editors). 


Regarding the screenshot in my previous comment, as you see, all lines have emojis rendered perfectly well, however, the second line where there is an Entry, they are mixed up and displayed incorrectly (it should have displayed the same emojis as the first line)

**Comment by jfversluis** [comment]
Let me be clear: the chances of the PR as-is to be merged are very small as this is a big, big change that impacts the labels of every Xamarin.Forms (Android) app of every developer out there and that is not something we like to do. At least not without having some kind of fallback scenario people can use to opt-out and revert to the old behavior if needs be.

I am looking into fixing this, but I'm going to do it properly, not rushed :)

Thanks for the extra info!

**Comment by jfversluis** [comment]
I've updated the PR with a more feasible solution. It should also include the fix for `Editor` and `Entry` could you let me know the results of that?

**Comment by jfversluis** [comment]
Build is completed, awaiting your findings @amirvenus, thanks!

**Comment by amirvenus** [comment]
All good! Well done and thank you!

**Comment by jfversluis** [comment]
Thanks @amirvenus! I opened #15303 for the pickers. Would you be able to test that one as well?

Did you find any more controls?

**Comment by amirvenus** [comment]
It's actually gone worse with the Pickers!

<img width="752" alt="image" src="https://user-images.githubusercontent.com/5879559/163046437-80fc6875-b412-4053-9dab-8ead9b62fd24.png">
<img width="639" alt="image" src="https://user-images.githubusercontent.com/5879559/163046469-73f3b5f1-be4f-4b53-9b49-95de067d9fda.png">


I will be checking other controls that have Title or some sort of Text within them and report back to you shortly.

**Comment by amirvenus** [comment]
<img width="745" alt="image" src="https://user-images.githubusercontent.com/5879559/163047500-9d8ee8f6-72c9-4f19-97ed-56ca48001d73.png">

SearchBars have issue as well.

**Comment by amirvenus** [comment]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/5879559/163048743-980ef21d-b4eb-4175-a835-85cc11e88282.png">

RadioButtons are fine! ✅

**Comment by amirvenus** [comment]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/5879559/163049408-41f37ed3-ef48-4532-b39f-2466234060f2.png">

NavigationPage's Title and ToolbarItem are fine! ✅

**Comment by jfversluis** [comment]
I made a mistake with the Picker, sorry about that. Could you try the picker again? I'm working on the SearchBar, but that one is a bit of a headache...

**Comment by jfversluis** [comment]
@amirvenus could really use your input still on this one, thanks!

**Comment by amirvenus** [comment]
Hi @jfversluis 

Sorry for the delay.

I downloaded the nuget package 5.0.0.8152 but the issue persists on Pickers ❌: 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/5879559/164392593-c46ccaea-d66e-459d-a04f-20433dd07d97.png">


SearchBar is fine though ✅

**Comment by amirvenus** [comment]
TableView ❌
 SwitchCell  ❌
 TextCell ❌
 EntryCell ❌
 ViewCell (Custom) ✅

**Comment by amirvenus** [comment]
FlyoutPage ✅

**Comment by jfversluis** [comment]
@amirvenus a new build is finally running with the latest changes. Could I ask you to double-check my work? Thanks! :)

**Comment by jfversluis** [comment]
@amirvenus do you have a project you test this with that I might use as well?

**Comment by amirvenus** [comment]
I am currently away abroad on holiday so it takes a while to conduct my testing.

However once I get a chance tomorrow, I will test your new build and also try uploading my test project to a public repo.

Thanks a lot for the time and effort you have put on this. I really appreciate it!

**Comment by jfversluis** [comment]
@amirvenus of course, no worries! Enjoy your holiday! Let me know when you have something for me :)

**Comment by amirvenus** [comment]
All controls working, except for `Picker`
<img width="430" alt="image" src="https://user-images.githubusercontent.com/5879559/169802709-274ca28f-7d89-4d63-9d4b-bdfbdde3c856.png">

The Title is set to:

Select a monkey😶‍🌫️ 🧔🏻‍♀️ 🧑🏿‍❤️‍🧑🏾

While it displays correctly when you tap on the picker, but on the initial load, it does not!

Tested with the nuget version 5.0.0.8189

**Comment by amirvenus** [comment]
Could you please look into it, @jfversluis ? Thanks!

**Comment by AlleSchonWeg** [comment]
Hi @amirvenus  and @jfversluis,
i have some questions. 
1. The docs still mention that label, for example, https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers#views has TextView as native control class. Is this correct?
2. Should i derive in a custom renderer from the *AppCompatRenderer version?
3. The LabelAppCompatRenderer is registered twice. Is this a problem?https://github.com/xamarin/Xamarin.Forms/blob/9df691e85d8c24486d71b9a502726f9835aad0f7/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L162

**Comment by amirvenus** [comment]
> Hi @amirvenus and @jfversluis, i have some questions.
> 
> 1. The docs still mention that label, for example, https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers#views has TextView as native control class. Is this correct?
> 2. Should i derive in a custom renderer from the *AppCompatRenderer version?
> 3. The LabelAppCompatRenderer is registered twice. Is this a problem?https://github.com/xamarin/Xamarin.Forms/blob/9df691e85d8c24486d71b9a502726f9835aad0f7/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L162

It's really a question for @jfversluis  but I suppose once the branch is merged with the main branch, the docs will become outdated and everything should become Compat.
