### ISSUE TITLE
[Bug] Xamarin.Forms is not able to Archive the Android project - multiple (random) AOT compile errors

### ISSUE THREAD

**Issue by nicolasHul** [xamarin/Xamarin.Forms#15253]
### Description

Today I tried to archive my Xamarin.Forms Android project for publishing. Building it and running on a emulator is all working fine, however suddenly I am getting multiple, and it looks like 'random' AOT compile errors on all kind of libraries. 

So my first guess was that I upgraded some NuGet's which won't compile anymore, so I checked out an older version of the application which was last succesfully archived, but sadly even this version did not Archive anymore. 

I then tried to remove some of the conflicting packages, but then just another package would fail. 

Next I tried to Archive the application on my Visual Studio 2019 (version 16.9.16), but I got some other API level 4 error which was presumably caused by my Android NDK 22.X version, so I downgraded the NDK version back to 21.3.6528147. After the downgrade the project DID successfully Archive on Visual Studio 2019. 

Now I can only assume this is somehow related to Visual Studio 2022 in combination with a Visual Studio 2022 version update, since a colleague of mine has successfully Archived the project before on VS2022 (but he as well is getting errors now on his 17.1.1 VS version) on 6 march 2022. 

I am wondering anyone is experiencing the same problem? As mentioned, our last successfully Archive date (on VS2022) was on 6 march, however, I don't exactly know which version of VS I was running back then.
I don't want to downgrade my VS2022 version just yet to validate this is truly the problem, so therefore I was curious if this issue is known or others experiencing it as well. 

### Expected Behavior
Successfully archiving the project.

### Actual Behavior
Throwing (random?) DLL AOT compile errors on multiple packages. 

### Basic Information
- Version with issue: N/A
- Last known good version: N/A
- Platform Target Frameworks: 
  - Android: 11.0 (API Level 30 - R) but also 12.0  (API Level 31 - S) 

Release settings:
![image](https://user-images.githubusercontent.com/67054132/159927064-61133a3d-c103-49a2-9d0e-9a6ae5a06ff0.png)

### Environment
Visual Studio 2022: 17.1.2 but also 17.1.1

### Build Logs
In this Example it seems to point to `System.Buffers.dll` but after removing that package it points to `System.Drawing.Common.dll` and so on..
`
Not using profile(s) for main assembly: obj\Release\110\android\assets\shrunk\PCS2.APP.Droid.dll
Not using profile(s) for main assembly: obj\Release\110\android\assets\shrunk\PCS2.APP.Droid.dll
Not using profile(s) for main assembly: obj\Release\110\android\assets\shrunk\PCS2.APP.Droid.dll
Not using profile(s) for main assembly: obj\Release\110\android\assets\shrunk\PCS2.APP.Droid.dll
[aot-compiler stderr] C:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.EXE: error: cannot open C:\Program Files (x86)\Android\android-sdk
dk-bundle\platforms\android-28\arch-arm\usr\lib\libm.so,profile-only,profile=C:\SVNWorkingFolder\dms\DMS2\APP\PCS2.APP.Droid\custom.aprof: Invalid argument
[aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly C:\SVNWorkingFolder\dms\DMS2\APP\PCS2.APP.Droid\obj\Release\110\android\assets\shrunk\System.Buffers.dll
[aot-compiler stdout] AOTID AEB167F6-8A4E-3434-38FC-9EE61C1C8D80
[aot-compiler stdout] Executing opt: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\opt" -f -O2 -disable-tail-calls -place-safepoints -spp-all-backedges -o "obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.opt.bc" "obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.bc"
[aot-compiler stdout] Executing llc: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\llc"  -enable-implicit-null-checks -disable-fault-maps -mattr=+vfp2,-neon,+d16 -asm-verbose=false -mtriple=armv7-linux-gnueabi -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_System_Buffers_eh_frame -disable-tail-calls -relocation-model=pic -o "obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp-llvm.s" "obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.opt.bc"
[aot-compiler stdout] Compiled: 5/5
[aot-compiler stderr] AOT of image C:\SVNWorkingFolder\dms\DMS2\APP\PCS2.APP.Droid\obj\Release\110\android\assets\shrunk\System.Buffers.dll failed.
[aot-compiler stdout] Executing the native assembler: "C:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-as"   -mfpu=vfp3 -o obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.s.o obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.s
[aot-compiler stdout] Executing the native assembler: "C:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-as"   -mfpu=vfp3 -o obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp-llvm.o obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp-llvm.s
[aot-compiler stdout] Executing the native linker: "C:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ld.EXE" -Bsymbolic -shared -o obj\Release\110\aot\armeabi-v7a\libaot-System.Buffers.dll.so.tmp "obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp-llvm.o" obj\Release\110\aot\armeabi-v7a\System.Buffers.dll\temp.s.o "-LC:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\arm-linux-androideabi\4.9.x" "-LC:\Program Files (x86)\Android\android-sdk
dk-bundle\platforms\android-28\arch-arm\usr\lib" "-LC:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\..\sysroot\usr\lib\arm-linux-androideabi" "C:\Program Files (x86)\Android\android-sdk
dk-bundle\toolchains\llvm\prebuilt\windows-x86_64\lib\gcc\arm-linux-androideabi\4.9.x\libgcc.a" "C:\Program Files (x86)\Android\android-sdk
dk-bundle\platforms\android-28\arch-arm\usr\lib\libc.so" "C:\Program Files (x86)\Android\android-sdk
dk-bundle\platforms\android-28\arch-arm\usr\lib\libm.so",profile-only,profile=C:\SVNWorkingFolder\dms\DMS2\APP\PCS2.APP.Droid\custom.aprof
XA3001: Could not AOT the assembly: System.Buffers.dll
Done executing task "Aot" -- FAILED.
Done building target "_AndroidAot" in project "PCS2.APP.Droid.csproj" -- FAILED.
Done building project "PCS2.APP.Droid.csproj" -- FAILED.
Build FAILED.`

### Workaround
Archiving the project in Visual Studio 2019, using NDK 21.

**Comment by MagicAndre1981** [comment]
VS2022 17.1 has [issues with deploying](https://github.com/xamarin/xamarin-android/issues/6652), maybe your issue is related to the issues. I also use 2019 as it is more stable compared to 2022 🤷‍♂️

**Comment by jfversluis** [comment]
As mentioned by @MagicAndre1981 this probably has more to do with Xamarin.Android. The linked issue says that something has been fixed and will be released with a new version soon. Going to close this one here for now, I think you'll have the best shot at getting some useful information in the linked issue. Let me know if you think there is still something specific to Forms
