### ISSUE TITLE
[Xamarin Forms][iOS]Tabbed Page tabs disappear after pop

### ISSUE THREAD

**Issue by Shaboo** [xamarin/Xamarin.Forms#1525]
Hi,

I have a navigation page, its root is a Tabbed page,
when I push a new page to the navigation stack, and pop it again,
the tabbed page tabs disappear,

Edit:
When I push a page to the navigation stack, this page contain the following line:
NavigationPage.SetHasNavigationBar(this, false);

and when pop this page from the navigation stack, tabbed page tabs disappear

I am using Xamarin.Forms 2.5.0.121934

**Comment by Shaboo** [comment]
Work around for this (read the edit section before)

set 
`NavigationPage.SetHasNavigationBar(this, true); `
before removing the page from the navigation stack

**Comment by hartez** [comment]
I'm trying to reproduce this issue, and so far I am unable to. Can you upload a minimal project which demonstrates this problem?
Thanks!

**Comment by jassmith** [comment]
Closed due to inactivity

**Comment by VincentH-Net** [comment]
I reproduced this also. Please fix this!

**Comment by RushAid93** [comment]
I'm also got this problem. I'm using Visual Studio for Mac 7.6.11 , Xamarin Forms 3.4.0.1008975 on simulator iPhone 7 iOS 12.1

**Comment by PureWeen** [comment]
@RushAid93  can you create a new issue and try to add reproduction?

**Comment by RushAid93** [comment]
> @RushAid93 can you create a new issue and try to add reproduction?

Yeah sure.
I have upload a very simple app in my repository to demonstrate this problem. Follow the instructions to reproduce the problem.
I also have created a new issue here https://github.com/RushAid93/xamarin_testing/issues/1

**Comment by RushAid93** [comment]
Ok, done.
