### ISSUE TITLE
How to add a .NET 6 library to Xamarin Forms

### ISSUE THREAD

**Issue by petro2050** [xamarin/Xamarin.Forms#15251]
I can't add a .NET 6 project as a dependency to the PCL or the platform specific projects. How can this be done?

![Capture](https://user-images.githubusercontent.com/62858360/159837072-04261bad-d46d-487c-a195-3ae7a3413751.PNG)

**Comment by MagicAndre1981** [comment]
this can't be done with XF. To use .net 6 switch to VS2022/17.2 preview and use MAUI, which is still in preview.

**Comment by jfversluis** [comment]
As indeed pointed out, Xamarin.Forms will not support .NET 6. Thanks!
