### ISSUE TITLE
In Android devices we are receiving two pairing dialog pop ups ? We need user input pairing pop only

### ISSUE THREAD

**Issue by preethiEshwar** [xamarin/Xamarin.Forms#15257]
From Xamarin forms application While initiating pairing firstly it will ask pair with device (device name)i.e just pair pop up appears on click of OK button one more pairing pop up appears requires user input (pin)is required to pair. I want a user input pairing pop up we require only one pop up in android device dont want just pair How do we archive in android devices? Please suggest.

I observed in IOS devices we are receiving only one pairing pop up dialog i.e ( user to enter pin) but in android devices we are receiving 2 pop up dialog. Please let me know the root cause.

I am using Xamarin forms to run on android & IOS . I tried to initiate the pairing by reading characteristic and receiving two pairing pop up. in IOS it is only one.

Only user input pairing pop up is required in android devices. Please suggest how do we get this.

**Comment by jfversluis** [comment]
I'm sorry but I don't really know what you mean. Pairing, you mean with Bluetooth?

I doubt that this is an issue in Xamarin.Forms at this moment and this is probably something that is happening inside of your implemented code. Either way, it's unfortunately impossible to say something useful about it without any relevant reproduction project or relevant code.

Closing this one for now
