### ISSUE TITLE
[Forms][Android] Map doesn't support rectangular tiles

### ISSUE THREAD

**Issue by Knots23** [xamarin/Xamarin.Forms#1526]
### Description
When creating a forms project with a custom renderer and tile provider for the Android project, you'll get to a point where you need to provide the width and height of a Tile. When these values differ (non-square tiles) the map shows gray bars between the tiles.
When using square tiles, but providing a different width/height, it still shows the map properly.

It seems as if the width / height properties of the Tile class are simply ignored.

### Steps to Reproduce

1. Download a sample project like [https://github.com/Emixam23/XamarinByEmixam23/blob/master/Detailed%20Part/Controls/Map/MapTileProject/MapTileProject/MapTileProject.Droid/CustomRenderer/CustomMapRenderer.cs](url)
2. Provide a custom map with non-square tiles and set the width and height in the tile provider accordingly, or use the openstreetmaps tiles ([http://a.tile.openstreetmap.org/{z}/{x}/{y}.png](url)) and set the width and height of the tiles to different values.
3. Run the Android project.

### Expected Behavior
1. If the openstreetmaps tiles are used with a different width and height, you'd expect a misformed/scaled map.
2. If a rectangular map was used width the correct width and height, you'd expect a correct map.

### Actual Behavior
1. The openstreetmap is shown properly.
2. The map is incomplete and shows gray bars between tiles, seemingly drawing squares nonetheless.

### Basic Information

- Version with issue: Xamarin Forms / Xamarin Forms Maps 2.5.0.121934
- Platform Target Frameworks: 
  - iOS:  Not tried / implemented on my end, so untested.
  - Android:  8.0 (Oreo)
- Android Support Library Version: 26.1.0.1

**Comment by pauldipietro** [comment]
The referred to project is rather out of date. Can you please upload a new, minimized reproduction we can run with screenshots that better illustrate the expected/actual behavior?

**Comment by samhouts** [comment]
@Knots23 Please reopen this issue if you're able to provide a new reproduction that will help us diagnose any issue. Thank you!
