### ISSUE TITLE
Setting Maximized for PreferredLaunchWindowingMode in UWP is not working

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15272]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Setting-Maximized-for-PreferredLaunchWin/1699365)._

---
Setting `ApplicationViewWindowingMode.Maximized` for `ApplicationView.PreferredLaunchWindowingMode` is not working in Xamarin Forms UWP projects.

`ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.Maximized`

---
#### Feedback Bot on 3/23/2022, 05:58 AM: 

(private comment, text removed)
#### Feedback Bot on 3/23/2022, 06:04 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Please provide a reproduction project or a little bit more code on where you are actually setting this in order to diagnose this properly. Thanks!

**Comment by kumaresan-cgvak** [comment]
Hello @jfversluis 
Please find the same.
[MaximiseSample.zip](https://github.com/xamarin/Xamarin.Forms/files/8386990/MaximiseSample.zip)
