### ISSUE TITLE
Radiobutton - Command propert missing in XAML/Xamarin Version 17.1.0.87

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15270]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Radiobutton---Command-propert-missing-in/1697334)._

---
Hi

Why is there no Command property available for the RadioButton control in Latest Xamarin version.

Thanks

---
#### Feedback Bot on 3/21/2022, 07:30 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
If you want to get the selected value you probably want to look at the `RadioButtonGroup`
