### ISSUE TITLE
Xamarin crash when add childs to Grid

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15290]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-crash-when-add-childs-to-Grid/10003784)._

---
[severity:It's more difficult to complete my work]
Working in Xamarin.Forms project. Trying to create Grid view by code:
```
Grid grid = new Grid()
{
    ColumnDefinitions = new ColumnDefinitionCollection() 
    { 
        new ColumnDefinition() { Width = new GridLength(1, GridUnitType.Star) } 
    },
    RowDefinitions = new RowDefinitionCollection()
    {
        new RowDefinition() { Height = new GridLength(1, GridUnitType.Star) },
        new RowDefinition() { Height = new GridLength(9, GridUnitType.Star) }
    }
};
grid.Children.Add(new Frame(), ......
```
When i try to write row/column position, Visual Studio process didn't response , sometimes write message "Wait until operation ends", use huge CPU time 
and infinite write data in RAM (until 10GB, then Windows kill process).
I think problem is with IntelliSense. When i just write "grid.Children.Add(...", then move down in IntelliSense tips, i still catch this problem.
Working config: Windows 7 x64, Visual studio 2022, Xamarin.Forms (package version v.5.0.0.2401, Xamarin.Essentials package is 1.7.1).

---
#### Feedback Bot on 4/6/2022, 03:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I reopened the VS Feedback ticket as this really is an issue with VS and not Xamarin.Forms as it would seem. Sorry for the trouble here.

**Comment by joepuhich** [comment]
C# Xamarin Android:
My program crashes on my child in a search method.
I tried to write around the child to no success.
I think it is a flag in the OS, that needs to be set to allow method to child functions.
