### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mlyga** [xamarin/Xamarin.Forms#15292]
### Description
I am using Xamarin.Forms to develop an Android application. I use simple Picker to choose some items. On the device (wasn't able to reproduce it on emulator) sometimes when I click on the picker I cant then choose the whole row (only the part of the row where the text is). Maybe it is not problem of Xamarin, but Android itself?

### Steps to Reproduce

1. On android device (wasn't able to reproduce it on emulator) click on the picker.
2. Click quickly on some choice and then again on the picker.
3. Repeat the second step until this issue happens.

### Expected Behavior
The clickable area should be always on the whole row.

### Actual Behavior
The clickable area rezise only on the text area of the row.

### Basic Information

- Version with issue: Xamarin.Forms 4.7.0.968
- Last known good version:
- Platform Target Frameworks: 
  - Android: API 28
- Affected Devices: Galaxy Tab Active2

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

https://user-images.githubusercontent.com/88679832/162120489-a5930f09-9c0d-452e-8061-32836fcf2ffa.mov

**Comment by jfversluis** [comment]
I see you mention Xamarin.Forms version 4.7, please upgrade to the latest version to see if the bug is still there.
