### ISSUE TITLE
[Bug] Span.GestureRecognizers - TapGestureRecognizer not working on windows and Android in Visual Studio 2022  .NET Maui

### ISSUE THREAD

**Issue by AndreduToit** [xamarin/Xamarin.Forms#15319]
### Description
Using Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 3.0 - .NET Maui app
Label.GestureRecognizers - TapGestureRecognizer  - responds
Span.GestureRecognizers - TapGestureRecognizer  - does not respond

### Steps to Reproduce

1. In VS add a new new .NET Maui App
2. In the MainPage.xaml, after  <Button   Text="Click me" add two labels as follows:
            <Label>
                <Label.GestureRecognizers>
                    <TapGestureRecognizer 
                        Tapped="OnCounterClicked"/>
                </Label.GestureRecognizers>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Label.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Span.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Tapped="OnCounterClicked"/>
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>

### Expected Behavior
Clicking the underlined words in either of the two above labels should fire  OnCounterClicked event

### Actual Behavior
The Label.GestureRecognizers  fires fires the OnCounterClicked event on click.
The Span.GestureRecognizers does not fire the OnCounterClicked event  on click.
Same behavior encountered on Windows Machine and Android Emulator - iOS not tested.
Span.GestureRecognizers worked on Xamarin Forms

### Basic Information

- Version with issue: .NET Maui
- Last known good version: Xamarin Forms
- Platform Target Frameworks: 
  - Android:  
  - WinUI:   
- NuGet Packages: as installed at App creation:
         Microsoft.Maui.Dependencies,
        Microsoft.Maui.Extensions,
        Microsoft.Windows.SDK.BuildTools
        System.Runtime.InteropServices.NFloat.Internal)
- Affected Devices: Widows Machine and Android

### Environment
Standard for .NET Maui Apps

### Build Logs
Not Applicable - solution builds.

### Screenshots
Not Applicable - not a visual issue.

### Reproduction Link
No reproduction case - simple to replicate.

### Workaround
TEMPORARY workaround = use Label. GestureRecognizers  instead of Span.GestureRecognizers 
Problem is that migrating from Xamarin Forms to .NET Maui requires developers to spend time debugging issues that previously worked.

**Comment by AndreduToit** [comment]
Something went wrong with the xaml for two labels - I submit again as follows:
           <Label>
                <Label.GestureRecognizers>
                    <TapGestureRecognizer 
                        Tapped="OnCounterClicked"/>
                </Label.GestureRecognizers>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Label.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>
            <Label>
                <Label.FormattedText>
                    <FormattedString>
                        <FormattedString.Spans>
                            <Span Text="Span.GestureRecognizers - TapGestureRecognizer test : " />
                            <Span Text="tap this" TextDecorations="Underline">
                                <Span.GestureRecognizers>
                                    <TapGestureRecognizer Tapped="OnCounterClicked"/>
                                </Span.GestureRecognizers>
                            </Span>
                            <Span Text="." />
                        </FormattedString.Spans>
                    </FormattedString>
                </Label.FormattedText>
            </Label>

**Comment by AndreduToit** [comment]
Apologies - still seems odd - try aml commented as follows:

**Comment by jfversluis** [comment]
For .NET MAUI apps please use that repo: https://github.com/dotnet/maui, thanks!

**Comment by AndreduToit** [comment]
I have tried to submit a new issue via the repo provided. I filled in all the required fields yet the "Submit new issue" button remains disabled - surely reporting a bug should not be this convoluted and difficult or dare I say flaky........

**Comment by AndreduToit** [comment]
OK I forgot top add a title - my bad - suggest to put a red asterisk against that filed as well....
