### ISSUE TITLE
[Bug] [iOS] NavigationBarSeparator is visible after changing BarBackgroundColor when SetHideNavigationBarSeparator(true)

### ISSUE THREAD

**Issue by JustickDM** [xamarin/Xamarin.Forms#15329]
### Description
NavigationBarSeparator is visible after changing BarBackgroundColor when On<iOS>().SetHideNavigationBarSeparator(true)

### Steps to Reproduce

1. Set On<iOS>().SetHideNavigationBarSeparator(true) on NavigationPage
2. Set BarBackgroundColor on NavigationPage
3. Run App
4. Change BarBackgroundColor 

### Expected Behavior

NavigationBarSeparator is Hidden

### Actual Behavior

NavigationBarSeparator is Visible

### Basic Information

- Version with issue: 5.0.0.2401
- Last known good version:
- Platform Target Frameworks:
  - iOS:  15.2.0.17

### Screenshots
1. App starts with Light Theme (SetHideNavigationBarSeparator(true), NavigationBarSeparator is Hidden - good)
![изображение](https://user-images.githubusercontent.com/33731962/164724908-0d8e02c0-25d2-44af-a645-c80cfecc0cb5.png)
2. Changing App Theme to Dark (SetHideNavigationBarSeparator(true), but NavigationBarSeparator is _Visible_ - **bad**)
![Capture2](https://user-images.githubusercontent.com/33731962/164725313-2d65840d-b1a5-4149-b1eb-43f61b9c70fc.PNG)
3. Changing App Theme back to Light (SetHideNavigationBarSeparator(true), but NavigationBarSeparator is _Visible_ - **bad**)
![Capture3](https://user-images.githubusercontent.com/33731962/164725343-92a07a64-e3b7-44f2-a6cb-581789fb3486.PNG)

### Workaround

UpdateHideNavigationBarSeparator method from - https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L506

Line needed to fix - https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L454
```
internal sealed class NavigationPageRenderer : NavigationRenderer
	{
		private UIImage _defaultNavBarShadowImage;
		private UIImage _defaultNavBarBackImage;
		private bool _disposed;

		public Xamarin.Forms.NavigationPage NavPage => Element as Xamarin.Forms.NavigationPage;

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			NavPage.PropertyChanged += HandlePropertyChanged;
		}

		protected override void Dispose(bool disposing)
		{
			if (_disposed)
				return;

			_disposed = true;

			if (disposing)
				NavPage.PropertyChanged -= HandlePropertyChanged;

			base.Dispose(disposing);
		}

		private void HandlePropertyChanged(object sender, PropertyChangedEventArgs e)
		{
			if (e.PropertyName == Xamarin.Forms.NavigationPage.BarBackgroundColorProperty.PropertyName)
				UpdateHideNavigationBarSeparator();
		}

		private void UpdateHideNavigationBarSeparator()
		{
			bool shouldHide = NavPage.OnThisPlatform().HideNavigationBarSeparator();

			// Just setting the ShadowImage is good for iOS11
			if (_defaultNavBarShadowImage == null)
				_defaultNavBarShadowImage = NavigationBar.ShadowImage;

			if (UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
			{
				if (shouldHide)
				{
					NavigationBar.CompactAppearance.ShadowColor = UIColor.Clear;
					NavigationBar.StandardAppearance.ShadowColor = UIColor.Clear;
					NavigationBar.ScrollEdgeAppearance.ShadowColor = UIColor.Clear;
				}
				else
				{
					NavigationBar.CompactAppearance.ShadowColor = UIColor.FromRGBA(0, 0, 0, 76); //default ios13 shadow color
					NavigationBar.StandardAppearance.ShadowColor = UIColor.FromRGBA(0, 0, 0, 76);
					NavigationBar.ScrollEdgeAppearance.ShadowColor = UIColor.FromRGBA(0, 0, 0, 76);
				}
			}
			else
			{
				if (shouldHide)
					NavigationBar.ShadowImage = new UIImage();
				else
					NavigationBar.ShadowImage = _defaultNavBarShadowImage;
			}

			if (!UIDevice.CurrentDevice.CheckSystemVersion(11, 0))
			{
				// For iOS 10 and lower, you need to set the background image.
				// If you set this for iOS11, you'll remove the background color.
				if (_defaultNavBarBackImage == null)
					_defaultNavBarBackImage = NavigationBar.GetBackgroundImage(UIBarMetrics.Default);

				if (shouldHide)
					NavigationBar.SetBackgroundImage(new UIImage(), UIBarMetrics.Default);
				else
					NavigationBar.SetBackgroundImage(_defaultNavBarBackImage, UIBarMetrics.Default);
			}
		}
	}
```
1. App starts with Light Theme (SetHideNavigationBarSeparator(true), NavigationBarSeparator is Hidden - good)
![Capture4](https://user-images.githubusercontent.com/33731962/164727173-82ae64a2-95e5-4f5a-9202-1a28d0a504bd.PNG)

2. Changing App Theme to Dark (SetHideNavigationBarSeparator(true), but NavigationBarSeparator is _Hidden_ - **good**)
![Capture5](https://user-images.githubusercontent.com/33731962/164727198-8f40b612-324e-43b5-8d04-9ebf226cf982.PNG)

3. Changing App Theme back to Light (SetHideNavigationBarSeparator(true), but NavigationBarSeparator is _Hidden_ - **good**)
![Capture6](https://user-images.githubusercontent.com/33731962/164727213-d5c46a6e-c970-497f-9c9f-03a351718870.PNG)

**Comment by jfversluis** [comment]
Thanks for the thorough report! I think it might've been reported before. Has to do with some changes in iOS 15 and appearance stuff. Anyway...

It seems like you pretty much pinpointed how to fix this as well, aren't you tempted to put it in a PR? ;)
