### ISSUE TITLE
Pair to mac: Cannot create a file when that file already exists

### ISSUE THREAD

**Issue by amirtrio** [xamarin/Xamarin.Forms#15358]
Hi
I can't pair my visual studio to mac. It throws an error when I click "connect"
**Cannot create a file when that file already exists**
Visual studio 2022 version 17.1.6
XCode 13.3
I don't know which file is meant, so I deleted the folder **"/Library/caches/xamarin/mtbs/PROJECT_NAME"** at mac device, but still same error.
I repaired the visual studio, but still same error
![image](https://user-images.githubusercontent.com/70882036/167239877-617f147b-c518-40f5-bfc4-7db7dc9c8068.png)

**Comment by mike-rowley** [comment]
@amirtrio I had the same issue after installing a Preview of Visual Studio.  I resolve this by deleting all the files in C:\Users\<username>\AppData\Local\Xamarin\MonoTouch

Hope this helps you or someone else.

**Comment by amirtrio** [comment]
> @amirtrio I had the same issue after installing a Preview of Visual Studio. I resolve this by deleting all the files in C:\Users\username\AppData\Local\Xamarin\MonoTouch
> 
> Hope this helps you or someone else.

Thank you, that helped. Now visual studio paired to mac successfully

**Comment by nZeus** [comment]
By the way, here is this issue described on VS DevPortal - https://developercommunity.visualstudio.com/t/Xamarin-iOS-Pair-To-Mac-Fails-With-Cann/10013061?entry=problem&ref=native&refTime=1652861076428&refUserId=64994ef8-f884-4e40-a93d-9d581d24cdc2. The fix will be released soon

**Comment by maikoly1** [comment]
> @amirtrio I had the same issue after installing a Preview of Visual Studio. I resolve this by deleting all the files in C:\Users\username\AppData\Local\Xamarin\MonoTouch
> 
> Hope this helps you or someone else.

Thank you.

**Comment by rhunoja** [comment]
> @amirtrio I had the same issue after installing a Preview of Visual Studio. I resolve this by deleting all the files in C:\Users\username\AppData\Local\Xamarin\MonoTouch
> 
> Hope this helps you or someone else.

it works for me, thank you very much!

**Comment by Magic73** [comment]
Thank you!
