### ISSUE TITLE
Cannot set icon on Xamarin.Forms IOS project on VS 2022 under Windows

### ISSUE THREAD

**Issue by Fabio7586** [xamarin/Xamarin.Forms#15363]
Hello, i have a problem:
There is no way to make appear right icon under IOS for my app; I have created an asset and the i have drag and drop png files on square form, then i create reference under csproj file like:

`<ItemGroup>
    <BundleResource Include="Resources\logo.png" />
  </ItemGroup>
  <ItemGroup>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Contents.json">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-20x20@1x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-20x20@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-20x20@3x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-29x29@1x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-29x29@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-29x29@3x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-40x40@1x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-40x40@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-40x40@3x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-60x60@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-60x60@3x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-76x76@1x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-76x76@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\Icon-App-83.5x83.5@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
    <ImageAsset Include="Assets.xcassets\AppIcons.appiconset\ItunesArtwork@2x.png">
      <Visible>false</Visible>
    </ImageAsset>
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\xamarin_logo%403x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\Default.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\Default%402x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\Default-568h%402x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\Default-Portrait.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\Default-Portrait%402x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_about.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_about%402x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_about%403x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_feed.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_feed%402x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\icon_feed%403x.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\xamarin_logo.png" />
  </ItemGroup>
  <ItemGroup>
    <BundleResource Include="Resources\xamarin_logo%402x.png" />
  </ItemGroup>`

and under info.plist i selected right asset for icon;

I setted debug in diagnostic mode and i searched for png names e nothing appear loading... please help 

Output attached.
[compile.txt](https://github.com/xamarin/Xamarin.Forms/files/8662284/compile.txt)

**Comment by jfversluis** [comment]
Please use the bug template we have in place to provide us with all the necessary information and ideally a reproduction sample that shows this issue.
