### ISSUE TITLE
[Bug] [iOS] Editor's TextChanged event is fired on Unfocus even when no text changed

### ISSUE THREAD

**Issue by JustickDM** [xamarin/Xamarin.Forms#15368]
### Description

The Editor's TextChanged event is fired when you unfocus the Editor control, with OldTextValue = (null) and NewTextValue = ""

This bug was fixed earlier for Entry's https://github.com/xamarin/Xamarin.Forms/issues/3385 , but not for Editor's

### Steps to Reproduce

1. Place an Editor in a page, register the TextChanged event handler, run the iOS App.
2. Tap on the Editor to focus it, the Keyboard will show.
3. Tap outside the Editor to unfocus it.

### Expected Behavior

No "TextChanged" event should be fired

### Actual Behavior

"TextChanged" event is fired

### Basic Information

- Version with issue: 5.0.0.2401
- Last known good version: Unknown
- Platform Target Frameworks:
  - iOS:  15.2.0.17

### Workaround
Line needed to fix -
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs#L280
Like this - 
https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Platform.iOS/Renderers/EntryRenderer.cs#L238

**Comment by PawKanarek** [comment]
@JustickDM do you think that we should add this fix into MAUI? More info here: https://github.com/dotnet/maui/issues/7536#issuecomment-1141124318
