### ISSUE TITLE
[QUESTION] What is the exact support end date for Xamarin Form, Is Nov 2023 a safe end date for APP migration?

### ISSUE THREAD

**Issue by nishadthajudeen001** [xamarin/Xamarin.Forms#15379]
### Description
As per this link(https://github.com/xamarin/Xamarin.Forms/issues/14205), Xamarin.Forms 5 will be supported until November 2022, but as per the support policy (https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) since last release was on Nov 2021 , it should support 2 years which should  be November  2023. 

Could you please confirm that Xamarin APP should get support till November 2023 so that the APP migration can be planned based on this Nov 2023 deadline?

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
Xamarin.Forms will be supported as per the policy that you have found. However, on the same page you linked it says release in January of 2021 and the support will be _at least_ until 2 years after that, which is next January. Depending on how things will be by then we might extend, but don't count on that too much.

Ideally you will make the transition asap.

**Comment by giuseppenovielli** [comment]
@jfversluis Thanks, for answer.

I think that Xamarin.Forms now is, over .NET MAUI, stable, with all libraries, developed.

I think that Xamarin.Forms must be continued supported only in maintenance mode, if iOS 16 will be a crash when run my ios app, it must be fixed.

Stop.

Nothing other implementation, but only compatibility with new iOS, Android SDK.

So, we can migrate our big Xamarin.Forms app to .NET MAUI when all is very stable and safe for production.

Thanks for all!

**Comment by nishadthajudeen001** [comment]
@jfversluis 
Thanks for the reply, "Xamarin.Forms" release details wasn't in the Xamarin policy link when I initially posted this question.
Anyway thanks for adding that which helps for accessing the impact for customers.

In addition to that, I have seen below statement regarding additional 1 year support after .Net MAUI GA. https://www.youtube.com/watch?v=5bK2ICHtMxo - 
_“When Microsoft releases .NET 6 in November 2021, Xamarin will officially be switched to .NET MAUI. Xamarin will continue to be supported for another calendar year (until November 2022), but modern support will transition to .NET MAUI.”,_ 

However, .Net MAUI GA in November was slipped and now targeting early Q2 of 2022. does that means that the support might have been extended for another calendar year(until Q2 @2023).  So, hopefully we would get time till  Q2 @2023 with proper support. Please confirm, which help the business to plan migration without any risk.

_“Unfortunately, .NET MAUI will not be ready for production with .NET 6 GA in November. We want to provide the best experience, performance, and quality on day 1 to our users and to do that, we need to slip the schedule. We are now targeting early Q2 of 2022 for .NET MAUI GA.”
https://devblogs.microsoft.com/dotnet/update-on-dotnet-maui/_

**Comment by eqmarcin** [comment]
We have a new big app to build and I'm trying to do this in MAUI but it has so many simple bugs and it's very frustrating to use it for development e.g. on CollectionView in iOS labels are not visible (looks OK on Android); the same code on ListView works OK on both platforms. Simple IsVisible doesn't work for some controls, or SearchBar uses dark mode (which is not enabled) when other controls on the screen are in light mode.

I would like to start this new app in XF (as the standard UI worked well for us) but I don't want to rewrite it to MAUI next year. I think MAUI needs another 6 to 12 months to fix all the basic bugs.
I'm considering Blazor Hybrid at the moment. At least the UI works as it's html + js (the only thing that is missing at the moment is access to QR Codes reader)
