### ISSUE TITLE
Items are not clipped properly when load the item inside the stack layout

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#1538]
Hi Team,

### Description
We have come across an issue in **Xamarin.Forms.UWP** platform while using custom layouts and rendering it with native view. 

**Layout of Custom Layouts:**
•	In the sample, we have created a new **custom ContentView** derived from **ContentView** in which **StackLayout** has added labels as child element.
•	These **custom ContentView** has been added into the **custom Layout<View>** as children and added another label in the **Layout<View>**. And, the **Custom Layout<View>** is loaded into **custom ScrollView**. Finally, custom **ScrollView** loaded into a **ContentPage**.

**Hierarchical structure of sample:**

•	**ContentPage -> Custom ScrollView -> Custom Layout<View> -> Custom ContentView -> StackLayout -> Label (Issue : it doesn’t clip properly if native UWP view is created for Custom ContentView in renderer project)** 

**Replication of issue:**
•	The child elements such as labels in the **StackLayout (loaded in custom ContentView)** doesn’t get clipped **if we create an equivalent view for custom ContentView in UWP renderer project** as like below code example.

**Code Example in PCL Custom ContentView:**

![image](https://user-images.githubusercontent.com/20282188/34720619-63d8cd48-f565-11e7-809b-a049fbf37e0d.png)

**Code Example in UWP renderer Custom ContentView:**

![image](https://user-images.githubusercontent.com/20282188/34720663-872a9ce0-f565-11e7-9b54-c0ab98d2102e.png)

### Expected Behavior

Items are clipped properly when the content is greater than the item height.

### Actual Behavior

Items are not clipped properly, it overlaps on the other item.

### Basic Information

- Platform Target Frameworks: 
  - UWP
- Nuget Packages: XAMARIN.FORMS v.2.5.0.91635

### Screenshots

**_Before writing the renderer_**

![image](https://user-images.githubusercontent.com/20282188/34719655-97d11ca8-f561-11e7-8f99-084b169c2baf.png)

**_After writing the renderer_**
![image](https://user-images.githubusercontent.com/20282188/34719679-ac51c074-f561-11e7-8957-3570f07fc32c.png)

### Reproduction Link

[ClippingBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1615042/ClippingBug.zip)

**Comment by samhouts** [comment]
@DineshBabuYadav  Are you still experiencing this issue? Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
