### ISSUE TITLE
[Bug] Dialog box for method `DisplayPromptAsync ` is displayed abnormally in windows machine

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#15392]
### Description

 Dialog box for method `DisplayPromptAsync ` is displayed abnormally in windows machine.

But it all works on android device.

### Steps to Reproduce

1. create a new maui app 
2. add a button in MainPage(e.g.  `Go to Next Page`) and add `Clicked` event for this button
   
       <Button  Text="Go to Next Page" Clicked="Button_Clicked" />

        private void Button_Clicked(object sender, EventArgs e)
         {
		Application.Current.OpenWindow(new Window()
		{
			Page = new NewTournamentPage()
		});
	    }

3. create a new page `NewTournamentPage`, then add a button (`add`)on this page and add `Clicked` event for this button
     
         <Button   Text="add"  Clicked="Button_Clicked"/>

          private async void  Button_Clicked(object sender, EventArgs e)
        {
		string name = await this.DisplayPromptAsync("Add new Player", "Name:");

		Debug.WriteLine("-----------newPlayerName=  " + name);
	   }
4. click button `add` on page `NewTournamentPage` ,then Prompt will pop up, and after we input some name for the Prompt,  click `Ok` button, then the Prompt  will dismiss and we can get the input name correctly,but at the same time, another Prompt  will popup.
And if we input some string, we can not get the input correctly.

    Besides, If we just try it a few more times,  the Prompt will display on `MainPage` not page `NewTournamentPage`. 

### Expected Behavior

The popup could pop up correctly.

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 6.0

### Screenshots

![image](https://user-images.githubusercontent.com/42464252/171130217-e10c962c-9a51-4c82-94b6-c720303f1685.png)

**Comment by jfversluis** [comment]
Looks like this is about .NET MAUI not Xamarin.Forms :) unfortunately I can't transfer the issue, closing it here, please report on https://github.com/dotnet/maui if this still affects you
