### ISSUE TITLE
Xaamarin Forms not implementing SceneDelegate in iOS

### ISSUE THREAD

**Issue by zurtox** [xamarin/Xamarin.Forms#15409]
Hi everyone

As far as we know, since iOS 13, the structure of iOS projects have been using SceneDelegates which allows using multiple screens.

Xamarin Forms has several issues in iOS platform, now bigger with iOS 15 and the upcoming iOS 16, such as Deeplinks, CarPlay, and some Multiple Screen share.

Does anyone has heard about any new release for fixing this huge issue?

**Comment by jfversluis** [comment]
Xamarin.Forms is in maintanance mode as per our [support policy](https://dotnet.microsoft.com/platform/support/policy/xamarin). If it's not implemented by now, we won't be doing it anymore for Xamarin.Forms. We have support for this in .NET MAUI. If this is something you need you will either have to implement it yourself or upgrade to .NET MAUI.
