### ISSUE TITLE
TabbedPage Renderer customizations are not applying from XF ver:5.0.0.2196 on IOS[Bug] 

### ISSUE THREAD

**Issue by asatya001** [xamarin/Xamarin.Forms#15403]
Please refer this sample https://github.com/CrossGeeks/ExtendedTabbedPageSample
which has older XF version.

### Description
Tabbed page renders are not working from XF version >5.0.0.2125 on IOS.
### Steps to Reproduce

1. Take above git hub solution and run see fonts are working or try changing font sizes.
2. Update the above git hub solution with XF latest or version > 5.0.0.2125 (version 5.0.0.2125 is working, anything grater than this version not working)
3.  Try to run and check if render changes are applying or not, you will see no changes , even font sizes.

### Expected Behavior
renderer customizations should work irrespective of XF version or with >5.0.0.2125
### Actual Behavior
renderer customizations are not working
### Basic Information

- Version with issue:Xamarin.Forms version >=5.0.0.2196
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  13
  - Android: 11
- NuGet Packages: Xamarin.Forms Latest
- Affected Devices: Iphone SE 3rd Generation
### Environment

1.
Visual Studio: Help > About Microsoft Visual Studio >2022 preview
Visual Studio for Mac: Visual Studio > About Visual Studio >2022 preview

**Comment by jfversluis** [comment]
They still work, they just need to be applied in a different way now because of the changes in iOS. For instance see [this](https://github.com/xamarin/Xamarin.Forms/issues/15115#issuecomment-1105726655)
