### ISSUE TITLE
Xamarin.forms app working on device but not once published to new phones (ios and android)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15415]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarinforms-app-working-on-device-but-/10038332)._

---
[severity:I'm unable to use this version]
I have a xamarin.forms applicatino using Shell.

I have a tab bar with 2 buttons ( Main page and About)

When I go to main page I can navigate to any page in the project with out  a problem. But when a user clicks on about the app freezes and dosen't do anything.

This project in only present on device that had never had a version of this app on their phone (through testflight or debug)

So new user downloading it from the app store. There isn't any crash log and no real way of debuging it.
This applys to android and iOS. Before implementing shell I didn't have that problem.

Thank you.

---
#### Feedback Bot on 5/11/2022, 08:08 PM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 5/13/2022, 02:28 AM: 

(private comment, text removed)
#### Samuel Carrier on 5/25/2022, 10:10 AM: 

(private comment, text removed)
#### Feedback Bot on 5/25/2022, 02:27 AM: 

(private comment, text removed)
#### JASON Zhao [MSFT] on 5/30/2022, 01:40 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looking through the original issue it seems a fix has been found. If you believe there is still an issue here, please let us know!
