### ISSUE TITLE
Change Text

### ISSUE THREAD

**Issue by teezenergy** [xamarin/Xamarin.Forms#15423]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

.NET Standard 2.0

### Description

Extract from "NotesPage.xaml":
`<Grid ColumnDefinitions="*,*">
            <Label Grid.Column="0"
                   x:Name="DatumundUhrzeit" 
                   FontSize="Medium"/>
            <Button Grid.Column="1"
                    Text="Refresh"
                    Clicked="OnRefreshButtonClicked"/>
        </Grid>`

Extract from "NotesPage.xaml.cs":
`void OnRefreshButtonClicked(object sender, EventArgs e)
        {
            DatumundUhrzeit.Text = "1";
            Thread.Sleep(1000);
            DatumundUhrzeit.Text = "2";
            Thread.Sleep(1000);
            DatumundUhrzeit.Text = "3";
            Thread.Sleep(1000);
        }`

When I press the "Refresh" button, it takes about 3s for the text to change to "3". The text "1" and "2" is not displayed.
How can I refresh the display so that "1" and "2" are also shown to me?

I am looking for something like "Application.DoEvents();".

### Steps to Reproduce

see Desrciption

### Did you find any workaround?

no

**Comment by jpobst** [comment]
Based on `NotesPage.xaml` and `Classic Xamarin.Android` I am guessing this is Xamarin.Forms.  Transferring issue to the XF repository.

**Comment by jfversluis** [comment]
Change you code to something like below to make it work!

```csharp
async void Button_Clicked(object sender, EventArgs e)
{
    label.Text = "1";

    await Task.Delay(1000);

    label.Text = "2";

    await Task.Delay(1000);

    label.Text = "3";
}
```
