### ISSUE TITLE
[Bug][Android] Editor Placeholder text no longer shows in Xamarin 5.0.0.2478

### ISSUE THREAD

**Issue by kunalprakash3891** [xamarin/Xamarin.Forms#15435]
Hi there, I've noticed after updating to Xamarin 5.0.0.2478 that the placeholder text for the editor component is no longer visible in Android.

To reproduce, create a brand new Xamarin app, plonk an editor component on a page, set the placeholder text to any value, and run the app. 

- Expected result - placeholder text should appear in the editor
- Actual result - no placeholder text!

Downgrading to Xamarin 5.0.0.2401 fixes this issue.

**Comment by thomasgalliker** [comment]
@kunalprakash3891 I can confirm this bug; we did experience it too.
Going back to Xamarin.Forms 5.0.0.2401 for now...

**Comment by jfversluis** [comment]
Would you be able to look at bullet point number 2 here: https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr11

Add that to your code and let me know if that fixes it? Thanks!

**Comment by holecekp** [comment]
I can also confirm this bug. The placeholder text (set by a binding) is not displayed on the start, but it is displayed once it is changed.

**Comment by holecekp** [comment]
The bug is caused by the experimental accessibility features.

As a workaround, you can add the following line before `Forms.Init(...)` in MainActivity.cs in the Android project:
```csharp
global::Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental");
```

**Comment by ahoke-cr** [comment]
@jfversluis it is the accessibility changes that are breaking the editor placeholder. Upon following @holecekp 's suggestion to set that flag the placeholder reappeared.

**Comment by jfversluis** [comment]
Interesting, I would've expected it to be the other feature flag. Thanks for this discovery!

**Comment by ahoke-cr** [comment]
Good morning @jfversluis, I installed the preview package from your PR (5.0.0.8283) and it seems to have resolved the issue with the accessibility changes still enabled:
![image](https://user-images.githubusercontent.com/77813058/177360805-3fc9b01a-04f6-485d-9dee-1cc9863a3a09.png)
