### ISSUE TITLE
StackLayout with zero spacing is not always zero spacing

### ISSUE THREAD

**Issue by kentcb** [xamarin/Xamarin.Forms#1544]
### Description

A `StackLayout` with `Spacing="0"` will not always honor that spacing if it contains controls of certain heights.

### Steps to Reproduce

```XML
    <StackLayout Spacing="0">
        <Label
            HeightRequest="55.7"/>

        <BoxView
            BackgroundColor="#433DBA"
            HeightRequest="10"/>
        <BoxView
            BackgroundColor="#6461B7"
            HeightRequest="10"/>
        <BoxView
            BackgroundColor="#433DBA"
            HeightRequest="10"/>
        <BoxView
            BackgroundColor="#6461B7"
            HeightRequest="10"/>
        ...
    </StackLayout>
```

### Expected Behavior

Each `BoxView` should be right up against the previous `BoxView` with no gaps.

### Actual Behavior

There are gaps periodically in the children following the `Label` with height `55.7` (I am sure there are other heights that trigger the same behavior, but I didn't bother looking for them).

### Basic Information

- Version with issue: `2.5.0.121934`
- Last known good version: N/A
- IDE: VS
- Platform Target Frameworks:
  - Android: 8.0

### Screenshots

![screenshot_20180110-102148](https://user-images.githubusercontent.com/1901832/34750047-736371e2-f5f0-11e7-97bd-a5f570903649.png)

### Reproduction Link

[XFTestBed.zip](https://github.com/xamarin/Xamarin.Forms/files/1617115/XFTestBed.zip)

**Comment by hartez** [comment]
@kentcb What screen size device/emulator are you seeing this on? I'm not seeing it on any of my test devices so far, so I'm guessing it happens with specific combinations of label height and screen size.

**Comment by kentcb** [comment]
It's a Pixel with 5" screen, which I understand to be 1080×1920.

**Comment by andreinitescu** [comment]
@kentcb if you play rotating the device few times does the gap go away at any point? I haven't seen this issue on any of my devices. 
But I guess @hartez already confirmed it to be an issue..

**Comment by Szymaniuk** [comment]
Same at Xiaomi Mi A1. Spacing=0 in some UI is treated like =1 - means there is one pixel line o spacing, between UI components.
