### ISSUE TITLE
Element properties and values are not loading Appropriately [Bug] 

### ISSUE THREAD

**Issue by pallavichandrashekarjetty** [xamarin/Xamarin.Forms#15446]
Hi team,

We are facing some issues with respect to loading the elements in Appium after few Nuget package update in Xamarin.

Please find the below changes in Xamarin:

	
SkiaSharp Updated from 2.80.3 to 2.88.0
	
Xamarin.Essentials Updated from 1.7.1 to 1.7.3
	
Xamarin.Forms Updated from 5.0.0.2401 to 5.0.0.2478

 

This issue is happening only in Android.

Could you please let us know what changes we need to perform in our automation framework or Xamarin instead of updating the element in every location as you know it is a cumbersome process and needs a lot of effort.

We also did a workaround when we downgrade the Xamarin forms version the elements are loading appropriately. So the issue is related to Xamarin forms update. Could you please help us to resolve this issue
Please find the below screenshot for more reference:

Ex: It is the same case in every page :) Elements are not loading appropriately
![image](https://user-images.githubusercontent.com/79142459/176422240-0a79ad94-4518-4148-86cf-6a0937c4d05f.png)

**Comment by SiNeumann** [comment]
I can verify this after the latest update(5.0.0.2478) automation ids mapped to content-desc "vanish" . 
They are not missing completly though. I'm not sure which tool @pallavichandrashekarjetty uses but in my case I use appium/uiautomator2 stack. The behaviour is as such:
On first load (or brief period of time) the content-desc is included in Page Source. Then some reload/refresh happens and then the contend-desc is missing.
I'm quite certain that this is due to the new release as the problem goes away on downgrade to version 5.0.0.2125

Example:
Button at start:
                                                            <android.widget.Button index="0"  class="android.widget.Button" text="Start" content-desc="Wzd_Next" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[29,1363][693,1464]" displayed="true" />
Button afterwards:

                                                            <android.widget.Button index="0"  class="android.widget.Button" text="Start" checkable="false" checked="false" clickable="true" enabled="true" focusable="true" focused="false" long-clickable="false" password="false" scrollable="false" selected="false" bounds="[29,1363][693,1464]" displayed="true" />

**Comment by pallavichandrashekarjetty** [comment]
@SiNeumann I am using Appium and exactly for the first time, elements will load and it is getting disappear after the second time. Not really sure why. I think it is a bug from the xamarin forms Nuget package update

**Comment by SiNeumann** [comment]
@pallavichandrashekarjetty it seems setting Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental"); in Android MainActivity.cs (OnCreate) and iOS Main.cs , solves the issue for now

**Comment by jfversluis** [comment]
I think this will be fixed by #15436 that should be part of the next service release. If that's not the case, please open a new issue. Thanks!

**Comment by askariya** [comment]
Hi @pallavichandrashekarjetty, is this issue still occurring for you? Did using Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental");  help?
I'm running into the same issue and content-desc seems to disappear in all of the Xamarin Forms updates since 2401.

**Comment by pallavicjetty** [comment]
Hi @askariya, Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental");  yes will work like a magic :)

**Comment by askariya** [comment]
@pallavichandrashekarjetty Thanks for the response, which Xamarin Forms release version are you using? `Xamarin.Forms.Forms.SetFlags("Disable_Accessibility_Experimental"); `doesn't seem to be changing anything for me.
