### ISSUE TITLE
iOS project PropertyGroup element references automatically removed

### ISSUE THREAD

**Issue by dbrevitt** [xamarin/Xamarin.Forms#1545]
### Description
MSBuild PropertyGroup elements cannot be referenced within the `<AssemblyName>` element of a Xamarin Forms iOS .csproj file as the '$', '(' and ')' are automatically removed.

There appears to be some special processing that removes illegal characters from the assembly name when loading Xamarin Forms iOS projects. The merits of this are mentioned in a similar issue here: https://bugzilla.xamarin.com/show_bug.cgi?id=32414

Can this illegal character processing be removed? Or, can this processing be postponed until after referenced PropertyGroup elements have been resolved within the `<AssemblyName>` element?

### Steps to Reproduce

1. Edit a Xamarin Forms iOS .csproj file by hand to reference a PropertyGroup element from within the `<AssemblyName>` element e.g. `<AssemblyName>MyProject$(Configuration)</AssemblyName>`
2. Load a solution that contains this project

### Expected Behavior
1. The Xamarin Forms iOS .csproj file remains unchanged
2. 'iOS Project -> Properties -> Application -> Assembly name' reflects the configuration that was loaded. In this case, for a Debug configuration the Assembly name should read 'MyProjectDebug' 
### Actual Behavior
1. The Xamarin Forms iOS csproj file has the `<AssemblyName>` element updated to remove special characters e.g.  `<AssemblyName>MyProjectConfiguration</AssemblyName>`
2. In the project properties, for a Debug configuration the Assembly name reads 'MyProjectConfiguration'

### Basic Information
Xamarin.Forms   2.5.0.122203

Xamarin   4.8.0.757
Xamarin Designer   4.8.188
Xamarin.Android SDK   8.1.3.0
Xamarin.iOS and Xamarin.Mac SDK   11.6.1.2

**Comment by hartez** [comment]
This appears to work as expected in VS Mac. On Windows, I'm seeing the behavior reported above.

**Comment by hartez** [comment]
This appears to be a Xamarin.iOS issue - please file an issue at https://github.com/xamarin/xamarin-macios/issues
