### ISSUE TITLE
[Bug] Xamarin Emulator freezes when Chrome brower is started when running Pixel 5 Android 11.0 API version 31 and 32

### ISSUE THREAD

**Issue by marcelbeeker** [xamarin/Xamarin.Forms#15458]
### Steps to Reproduce

1. Start VS2022
2. Configure a new emulator Pixel5 API version 12.0 or 12.1
3. Start the emulator
4. Start Chrome
5. Sign in with a Google Account
6. Accept the terms
7. In the last step accepting Google Drive the browser freezes completely. No url navigation bar is visible

### Expected Behavior
I works in emulator Pixel API version 11.0

### Actual Behavior
The browser freezes and has no access to the internet

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: API version 11.0
  - Android: Android 11.0 
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

VS2022 running on Windows 11

Wrong
![image](https://user-images.githubusercontent.com/18581814/177632176-49c7eca5-422c-4acb-95d0-84c974f9ebf9.png)

OK
![image](https://user-images.githubusercontent.com/18581814/177632255-34963a3b-6e10-43f7-aaf6-e078f0f4a4b4.png)

**Comment by jfversluis** [comment]
Unless you have configured something very specific these are the emulator images from Google, so there is nothing much we can do here. And if anything, this is not something that belongs with Xamarin.Forms. If you do believe this is an error in our tooling please report the issue through the Visual Studio Help menu. Thanks!

**Comment by marcelbeeker** [comment]
@jfversluis I disagree. This issue is depending if Xamarin (and .NET MAUI) will be used by us developers. I agree Microsoft can't do anything about it. In my option this problem had to be forwarded,  because I believe the only I'm not the only one with this problem I guess. But finally I solved this problem due too this link: https://stackoverflow.com/questions/69134922/google-chrome-browser-in-android-12-emulator-doesnt-load-any-webpages-internet
