### ISSUE TITLE
[Bug] [ANDROID] Multiple Gifs

### ISSUE THREAD

**Issue by jhay06** [xamarin/Xamarin.Forms#15453]
Hi , 
would like to report the bugs i experienced during my development using xamarin

on iOS loading multiple gifs works just fine ,
but on Android , when loading multiple gifs , i dont know how many gifs but im sure too many gifs loaded in one page causes android to crash without logging errors .

I tried to load multiple loading .gif images maybe it is 10-15 views with the same loading.gifs , but as soon as it loads most of the views , it crashed.

**Comment by jfversluis** [comment]
Please use the bug template that we have in place to provide us with all the details. At the very least the error message that you see when the app crashes and some relevant code, ideally a reproduction project that is hosted on GitHub.
