### ISSUE TITLE
Integrate xamarin into existing native projects, like flutter and RN

### ISSUE THREAD

**Issue by liuzhenLz** [xamarin/Xamarin.Forms#15459]
This feature is particularly important for most of the actual needs. Realizing the hot plug of xamarin in the original project will directly promote everyone to use xamarin to develop module functions

**Comment by jfversluis** [comment]
This is something Flutter and React Native will have to support, not us. And I don't think there will be much insentive to do so.

**Comment by liuzhenLz** [comment]
From the perspective of actual project development, this is very important. Without this feature, most of the plans to develop apps with Maui and xamarin will be lost. Maui (xamarin. Forms) should be symbiotic with native ecology to be better.

**Comment by liuzhenLz** [comment]
Or think about it in another way. Why do RN and fluter design their frameworks in this way~
