### ISSUE TITLE
[Bug] Can't Hit Any Breakpoints in VS 2022.

### ISSUE THREAD

**Issue by hazwan223** [xamarin/Xamarin.Forms#15457]
### Description

I can't Hit Any Breakpoints in VS 2022. It started all of the sudden yesterday. It says "No symbols loaded containing source information loaded" under External Resources tab.

### Steps to Reproduce

1. Run new solution on Debug Mode
2. try to hit a breakpoint on any line of code
3. nothing happens

### Expected Behavior
Breakpoint should be hit

### Actual Behavior
Breakpoint is not hit

### Screenshots
![Screenshot 2022-07-06 181240](https://user-images.githubusercontent.com/40681833/177527563-8e7f87cd-b868-4a1c-999d-541b7bfca638.png)

![Screenshot 2022-07-06 181353](https://user-images.githubusercontent.com/40681833/177527792-299d4375-6361-4d3a-927e-24f03a10cbfd.png)

**Comment by jfversluis** [comment]
This sounds more like a Visual Studio issue. Make sure to do a clean and rebuild and maybe even. delete the bin & obj folders from all of your project folders on the filesystem. If that doesn't help, please report an issue through the Visual Studio Help menu.
