### ISSUE TITLE
Could not link assemblies. Reason: Object reference not set to an instance of an object when build a release build

### ISSUE THREAD

**Issue by Shaboo** [xamarin/Xamarin.Forms#1546]
### Description
when I try to build my app in (app store) mode to produce IPA, the following error shown

"**Could not link assemblies. Reason: Object reference not set to an instance of an object when build a release build**"

this is the build log when adding -v -v -v -v for mthouch build parameters

--- inner exception (TaskId:344)
2>  System.NullReferenceException: Object reference not set to an instance of an object (TaskId:344)
2>    at Mono.Linker.TypeReferenceExtensions+<GetMethods>d__4.MoveNext () [0x00047] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker/TypeReferenceExtensions.cs:169  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.TryMatchMethod (Mono.Cecil.TypeReference type, Mono.Cecil.MethodDefinition method) [0x0002d] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:170  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep+<GetBaseMethodsInInterfaceHierarchy>d__12.MoveNext () [0x0006c] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:159  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod (Mono.Cecil.MethodDefinition method) [0x00020] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:111  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod (Mono.Cecil.MethodDefinition method) [0x00009] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:97  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods (Mono.Cecil.TypeDefinition type) [0x00037] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:87  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.MapType (Mono.Cecil.TypeDefinition type) [0x00001] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:45  (TaskId:344)
2>    at MonoTouch.Tuner.MonoTouchTypeMapStep.MapType (Mono.Cecil.TypeDefinition type) [0x00001] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/linker/MonoTouch.Tuner/MonoTouchTypeMap.cs:45  (TaskId:344)
2>    at Mono.Linker.Steps.TypeMapStep.ProcessAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x0001d] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs:40  (TaskId:344)
2>    at Mono.Linker.Steps.BaseStep.Process (Mono.Linker.LinkContext context) [0x0002e] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker.Steps/BaseStep.cs:55  (TaskId:344)
2>    at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0001e] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/external/linker/linker/Mono.Linker/Pipeline.cs:127  (TaskId:344)
2>    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x000e0] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Tuning.cs:82  (TaskId:344)
2>  --- (TaskId:344)
2>    at MonoTouch.Tuner.Linker.Process (MonoTouch.Tuner.LinkerOptions options, MonoTouch.Tuner.MonoTouchLinkContext& context, System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies) [0x003ad] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Tuning.cs:124  (TaskId:344)
2>    at Xamarin.Bundler.Target.LinkAssemblies (System.Collections.Generic.List`1[Mono.Cecil.AssemblyDefinition]& assemblies, System.String output_dir, System.Collections.Generic.IEnumerable`1[T] sharedCodeTargets) [0x0029f] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Target.cs:491  (TaskId:344)
2>    at Xamarin.Bundler.Target.ManagedLink () [0x005c5] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Target.cs:614  (TaskId:344)
2>    at Xamarin.Bundler.Target.ProcessAssemblies () [0x000bb] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Target.cs:800  (TaskId:344)
2>    at Xamarin.Bundler.Application.ProcessAssemblies () [0x0002f] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Application.cs:1407  (TaskId:344)
2>    at Xamarin.Bundler.Application.BuildManaged () [0x00001] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Application.cs:831  (TaskId:344)
2>    at Xamarin.Bundler.Application+<>c.<BuildAll>b__134_1 (Xamarin.Bundler.Application v) [0x00000] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Application.cs:779  (TaskId:344)
2>    at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x00024] in <4fdc5ed61a074cafb49fa42deb20d521>:0  (TaskId:344)
2>    at Xamarin.Bundler.Application.BuildAll () [0x00050] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/Application.cs:779  (TaskId:344)
2>    at Xamarin.Bundler.Driver.Main2 (System.String[] args) [0x00481] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/mtouch.cs:1403  (TaskId:344)
2>    at Xamarin.Bundler.Driver.Main (System.String[] args) [0x00015] in /Users/builder/data/lanes/5665/6857dfcc/source/xamarin-macios/tools/mtouch/mtouch.cs:928  (TaskId:344)
2>  Tool /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch execution finished. (TaskId:344)
2>  MTouch: 2018-01-10T13:37:21.8910438+02:00 - Finished (TaskId:344)

### Steps to Reproduce

1. set build mode to app store
2. build the application

### Expected Behavior
no errors
### Actual Behavior
the build failed with the following error:
Could not link assemblies. Reason: Object reference not set to an instance of an object when build a release build
### Basic Information

- Version with issue: Xamarin Forms 2.5.0.121934
- Last known good version:
- IDE: vs 2017 
- Platform Target Frameworks: 
  - iOS:  11.6.1.1.2
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
@Shaboo This looks like a Xamarin.iOS issue - you should submit it to https://github.com/xamarin/xamarin-macios/issues

**Comment by Shaboo** [comment]
the problem appeared to be with some library that does not support net Standard, when I removed it the build completed with no errors

**Comment by abrantie1z** [comment]
From my experience, downgrading some nuget packages work! I just downgraded some xamarin.Android packages to 25.4.0.2 and the errors went away.
