### ISSUE TITLE
[Bug] (Android) Entry, with certain settings, the phone number of the device is displayed.

### ISSUE THREAD

**Issue by kuririn2001** [xamarin/Xamarin.Forms#15468]
### Description
Hello.
I'm experiencing the phenomenon in the title in my environment, is it a Bug?

### Steps to Reproduce

1. In Xamarin.Forms Android, set the Keyboard of Entry to Numeric or Telephone, and set a string to Placeholder.
2. Run the program and give it a FOCUS when the Entry is displayed.
3. If you leave it as it is for a while, a number that seems to be the phone number of the device is displayed above or below the Entry display,  like a tooltip. (See attached image).

In case you are wondering, it does not happen with no Keyboard set or with other Keyboards (like Chat for example).
Even if Keyboard is set to Numeric, it will not happen if Placeholder is not set.

***Reproduction code**
_MainPage.xaml_

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="placeholdertest.MainPage">

    <StackLayout>
        <Entry Placeholder="input value" Keyboard="Numeric" />
    </StackLayout>

</ContentPage>
```

### Expected Behavior
No extra phone numbers are displayed.

### Actual Behavior
as above-mentioned in the title

### Basic Information

***Platform**
It happens on Android and not on iOS.
I have confirmed that it happens on Android versions 9 and 10.

***Library Version**
We have confirmed that the problem occurs with Xamarin.Forms 5.0.0.2012, but also with the latest version 5.0.0.2478 as of 2022/7/11.
Xamarin.Essentials was confirmed to have a problem with 1.6.1, but we have confirmed that the problem also occurs with the latest version 1.7.3 as of 2022/7/11.

### Environment

=== Visual Studio Community 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: bd25d430-4c61-4e7c-9ee7-3b35156b3609
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/sdk/5.0.408/Sdks
SDK Version:
	5.0.408
	5.0.407
	5.0.406
	5.0.405
	5.0.404
	5.0.403
	5.0.402
	5.0.401
	5.0.400
	5.0.302
	5.0.301
	5.0.203
	5.0.202
	5.0.201
	5.0.103
	3.1.420
	3.1.419
	3.1.418
	3.1.417
	3.1.416
	3.1.415
	3.1.414
	3.1.413
	3.1.412
	3.1.411
	3.1.410
	3.1.409
	3.1.408
	3.1.407
	3.1.406
	3.1.405
	2.1.816
MSBuild SDK: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version:
	5.0.17
	5.0.16
	5.0.15
	5.0.14
	5.0.13
	5.0.12
	5.0.11
	5.0.10
	5.0.9
	5.0.8
	5.0.7
	5.0.6
	5.0.5
	5.0.4
	5.0.3
	3.1.26
	3.1.25
	3.1.24
	3.1.23
	3.1.22
	3.1.21
	3.1.20
	3.1.19
	3.1.18
	3.1.17
	3.1.16
	3.1.15
	3.1.14
	3.1.13
	3.1.12
	3.1.11
	3.0.3
	2.2.8
	2.1.28

=== .NET Core 3.1 SDK ===

SDK: 3.1.420

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.22
 /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 13.4.1 (20504)
Build 13F100

=== Xamarin.Mac ===

Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Community)
Commit :xamarin-android/d17-1/fafdba7

build info: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.4.0
Darwin 21.5.0 Darwin Kernel Version 21.5.0
    Tue Apr 26 21:08:22 PDT 2022
    root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/29966312/178380879-a786582f-a2ab-44fe-853a-0fe7522fa042.png)### Reproduction Link

### Workaround
For now, do not set Keyboard and Placeholder at the same time.

**Comment by jfversluis** [comment]
Looks like this is default Android behavior: https://developer.android.com/reference/androidx/autofill/HintConstants#AUTOFILL_HINT_PHONE_NUMBER_DEVICE()

If you do not want to see this, you probably need to implement a custom renderer to remove this flag from the Entry.
