### ISSUE TITLE
Listview memoryleak when using datepicker

### ISSUE THREAD

**Issue by JellisHogenbijl** [xamarin/Xamarin.Forms#1548]
### Description
There seems to be a memoryleak when using a Xamarin.Forms.DatePicker inside a listview.
I've created a test app that navigates to a page with a listview that contains a datepicker.
When you pop the views there will be some retained memory.
If you comment out the datepicker (in MainPage.xaml) the memory is stable.

Note: tested on Android version 6.0 and 7.0. Not sure if this occurs on iOS as well.

### Steps to Reproduce
- Run the test app
- Tap on the "NEW LISTVIEW" button a couple of times
- Tap on the "POP ALL RECURSIVE ANIMATED" button
- When all views are popped click on GC 2-3 times
- Click refresh to show the current memory usage

Below are my findings of memory usage after adding X amounts of listviews and popping back to the root view.

Loading number of listview without datepicker
25 -> 1,471 MB
50 -> 1,485 MB
75 -> 1,482 MB
110 -> 1,485 MB
200 -> 1,484 MB

Loading number of listview with datepicker
25 -> 3,045 MB
50 -> 4,588 MB
75 -> 6,136 MB
110 -> 8,302 MB
200 -> 13,851 MB

### Expected Behavior
Stable memory usage after popping the navigated views.

### Actual Behavior
Memory is rising after navigating to new pages and then popping them.

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: unknown
- IDE: Visual Studio
- Platform Target Frameworks:
  - Android: tested on 6.0 and 7.0
- Android Support Library Version: 23

[FormsDatepicker.zip](https://github.com/xamarin/Xamarin.Forms/files/1618962/FormsDatepicker.zip)

**Comment by kingces95** [comment]
Drat. Getting `The "GenerateJavaStubs" task failed unexpectedly.` on latest nightly with latest android SDK.

**Comment by JellisHogenbijl** [comment]
Is this something that should/could be solved in the app or is it something that needs to be fixed in Xamarin?

**Comment by MarcBruins** [comment]
I'm having the same issue, is there any progress on this?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
