### ISSUE TITLE
PopToRootAsync from homePage clears navigationStack but child page remains on top - android 

### ISSUE THREAD

**Issue by jszymenderski** [xamarin/Xamarin.Forms#15494]
I have timer (System.Threading) in my home page wich supposed to close all child pages from navigation stack when there is no interaction with user 

` public HomePage()`
 `            {`
         `   InitializeComponent();`
          `  App.IsPortait = (DeviceDisplay.MainDisplayInfo.Orientation == DisplayOrientation.Portrait);`
  `           RefreshMainIcons();`
  `          timer = new Timer(CloseAllPages, null, 0, 1000);`
   `     }`

the CallBack is

` private  void CloseAllPages(object state)`
       ` {`
        `    if (Navigation.NavigationStack.Count > 1 && (DateTime.Now - App.lastUserInteraction).TotalSeconds > SettingsHandlers.noUserInteractSeconds)`
      `      {`
             **`  Navigation.PopToRootAsync();`**
`            }`
`        }`

I 've also tried 

 ` Navigation.NavigationStack[Navigation.NavigationStack.Count - 1].Navigation.PopToRootAsync();`

After call,  navigation stack has only one element (root page) and it's ok, but child page wich was shown during call, remains on screen. 
It is strange because i'm using the same call in OnSleep (app file) and it works

`protected override void OnSleep()`
     `   {`
            `MainPage.Navigation.PopToRootAsync();`
       ` }`

Xamarin SDK 12.0.0.3
Xamarin ver 16.11.000.197
Xamarin Forms 5.0.0.2515
Xamarin.Essentials 1.7.3
Android 12

**Comment by jszymenderski** [comment]
Ok. The problem was with lack of async calls
I've added 
`await Application.Current.MainPage.Navigation.PopToRootAsync();`
and in TimerCallBackFunction 
`Device.BeginInvokeOnMainThread(() => CloseAllPages());`

**Comment by sojan1** [comment]
thank you very much. you saved my time 

await Application.Current.MainPage.Navigation.PopToRootAsync(); to go back to the parent

**Comment by sojan1** [comment]
but this cant get  to the values or navigfations , oer even load of the rootpage
