### ISSUE TITLE
Xamarin.android widget DNS issues when using widget button[Bug] 

### ISSUE THREAD

**Issue by salvesen** [xamarin/Xamarin.Forms#15490]
### Description

When creating a widget button in xamarin.android I get DNS issues when trying to access a API. When clicking the widget button I get a NameResolutionFailure. If using a button in the app there is no issue. 

### Steps to Reproduce

1. I have created a sample here: https://github.com/salvesen/widgetSample
2. Add widget to home screen on phone, click widget button many times
3. Go to log page in app and see the NameResolutionFailures. Click button in app and never get failures.

### Expected Behavior

No NameResolutionFailures when using widget button.

### Actual Behavior

Getting NameResolutionFailures when using widget button

More info in this stackoverflow post: 

https://stackoverflow.com/questions/73150672/xamarin-widget-button-nameresolutionfailure-httpwebrequest

**Comment by jfversluis** [comment]
This is not a Xamarin.Forms bug, you should see if there is an issue for this or log one on https://github.com/xamarin/xamarin-android/
