### ISSUE TITLE
[Feature Request] Add AppCompat version of EntryRenderer

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1549]
### Summary
There isn't a AppCompat version of the EntryRenderer, there should be.

### API Changes
Create a AppCompat version of the EntryRenderer, so that the native control is set as a AppCompatEditText.

### Intended Use Case
Having a AppCompat version of controls makes it easier to style it the same for all Android Versions

**Comment by jfversluis** [comment]
To be honest I'm not sure what the status of this is. Either this is fixed already or we won't be doing it for Xamarin.Forms anymore. Closing this one.
