### ISSUE TITLE
[Issue] iOS Remote Simulator 100% memory, 100% CPU

### ISSUE THREAD

**Issue by dimitar-sd** [xamarin/Xamarin.Forms#15505]
### Description
after running iOS Remote Simulator, the system grabs all available resources and doesn't let them go -100% memory, 100% CPU. One of the processes that takes a lot of resources is System. The other is VS 2022.  Note that this was not a problem with VS 2019.

### Steps to Reproduce

1. Run debugger with Remote Simulator to Windows
2. Start TaskMgr and look at the resources taken from the system
3. it takes 100% of CPU, Memory
4. Remote Simulator stays blank until the page that it shows changes (and Simulator refreshes) enough times until it finally shows the full page in the Simulator.

### Expected Behavior
Remote Simulator runs and shows the remote page.

### Actual Behavior
Remote Simulator runs and shows blank page. After playing with it and moving the home page left and right (with black screen) the simulator shows spinner activity and eventually shows the page. At that point the CPU/Memory take 100% (or a bit after you start the Simulator).

### Basic Information
Visual Studio 2022 17.3.0

**Comment by jfversluis** [comment]
This is a tooling issue and not much we can do about it unfortunately, please report through Visual Studio in the Help menu choose > Provide Feedback > Report a problem. Thanks!
