### ISSUE TITLE
[Bug]  Xamarin telemetry issue with Visual studio 17.3

### ISSUE THREAD

**Issue by developer9969** [xamarin/Xamarin.Forms#15506]
### Steps to Reproduce

1.  Update to VS 17.3
2.  Open any xamarin app
3.  make a change and build 
4.  BOOM you will see the Xamarin Telemetry issue

On big projects it quite time consuming 

Workaround
remove the telemetry from the sdk target

Is there any chance of prioritising this one so that we can get a fix!!

Huge thanks

**Comment by andy-shindey** [comment]
I am facing the same issue. Its maddening.

**Comment by capricciobob** [comment]
Me too. Clean project and build works, but man is that annoying!

**Comment by mbilalbenli** [comment]
I am also to have this error. Alwaysly clearing the project annoying me.

**Comment by daddyqbob50** [comment]
Same Issue.

**Comment by adamhill** [comment]
Same here.

**Comment by developer9969** [comment]
This is now fixed with the release of V17.3.1

**Comment by andy-shindey** [comment]
👍
