### ISSUE TITLE
Android Application Crashes When app is Launched on Android Device version 12

### ISSUE THREAD

**Issue by Rishi2611** [xamarin/Xamarin.Forms#15521]
I have Targeted My Application on Android 12 now when ever app is launched on Android Device of version 12, Application Crashes.

**Comment by jfversluis** [comment]
Thanks for the report! Unfortunately it's impossible to diagnose what might be wrong with just one line of description. Please either add more information like error messages, log output or stack traces or add a reproduction project that we can have a look at. Feel free to open a new issue with much more detail if you want us to have a look. Thanks!
