### ISSUE TITLE
[Xamarin.iOS] ITMS-90338: Non-public API usage - The app references non-public selectors in

### ISSUE THREAD

**Issue by tsutsong** [xamarin/Xamarin.Forms#15528]
I am building a Xamarin.Forms app and deploying to the Apple App Store but rejected for the following reasons:

> **ITMS-90338: Non-public API usage** - The app references non-public selectors in APP-SingOff-Client.iOS: accessibilityBrailleMapRenderRegion, accessibilityBrailleMapRenderer, activePlayer, beginAuthorizationWithRequest:, cancelAuthorizationWithRequest:, checkFocusGroupTreeForEnvironment:, commissioningComplete:, connectionTypesMask, pairDevice:address:port:discriminator:setupPINCode:error:, playerId, serviceExtensionWillTerminate, session:didReceiveData:fromPlayer:, session:didReceiveMessage:withData:fromPlayer:, session:player:didChangeConnectionState:, session:player:didSaveData:, setAccessibilityBrailleMapRenderRegion:, setAccessibilityBrailleMapRenderer:, setConnectionTypesMask:, setListenPort:, sharedController, sleep:, test:, toggle:. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at http://developer.apple.com/support/technical/

I coded the app on a PC in Visual Studio Community 2022 17.3.3
Xamarin.iOS and Xamarin.Mac SDK   15.12.0.2 (87f98a75e)

Packages that I am using are:
Xamarin.Forms : 5.0.0.2515
Xamarin.Essentials : 1.7.3
Newtonsoft.Json : 13.0.1

Target Framework : .NET Standard 2.0

Build Configuration: Release
Linker Behavior: Link Framework SDKs Only
Additional mtouch arguments: --linksdkonly

Can you please help me to fix.

Thanks

**Comment by jfversluis** [comment]
You can't deploy an app that has been developed with Hot Restart, see: https://docs.microsoft.com/xamarin/xamarin-forms/deploy-test/hot-restart#limitations

**Comment by tsutsong** [comment]
I turned off Hot Restart Option from **Tools > Options > Xamarin > iOS Settings > Enable Hot Restart** ,still getting rejection from AppStore.
