### ISSUE TITLE
[Bug] Issue with custom dynamic editor on iOS

### ISSUE THREAD

**Issue by agnihotritanisha** [xamarin/Xamarin.Forms#15538]
### Steps to Reproduce

1. Added a dynamic editor , when keyboard is down editor is of max height and scrolling is working fine always
2. Then keyboard up the editor size is adjust according to keyboard size.
3. So in this case when editor height is small I am not able to view the one to two line text because scrolling is not working , when there is text of 6 to 7 line scrolling is working and I am able to see the text.

### Basic Information : Have created dynamic editor by referring to this link -https://xamgirl.com/adjusting-elements-when-keyboard-shows-in-xamarin-forms/

- Affected Devices: iphone SE and iphone 11

### Environment

"Visual Studio Community 2022 for Mac Preview
Version 17.3 Preview (17.3 build 2083)
Installation UUID: 746da40f-3439-4683-a16b-5ded49e34427

Runtime
.NET 6.0.5 (64-bit)
Architecture: X64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.1.2

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/6.0.400-preview.22330.6/Sdks
SDK Versions:
    6.0.400-preview.22330.6
    6.0.301
    3.1.421
    3.1.420
MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    6.0.6
    3.1.27
    3.1.26

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin [Profiler.app/Contents/MacOS/Xamarin](http://profiler.app/Contents/MacOS/Xamarin) Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 13.3.1 (20103)
Build 13E500a

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-07-22 20:10:14 UTC

Xamarin.Android
Version: 12.3.3.3 (Visual Studio Community)
Commit: xamarin-android/d17-2/4e061b7
Android SDK: /Users/mac-0026/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        12.0 (API level 31)
        8.1  (API level 27)
        11.0 (API level 30)

SDK Command-line Tools Version: 5.0
SDK Platform Tools Version: 31.0.3
SDK Build Tools Version: 30.0.3

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-2@9760f0a9
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.38.2@7b1e016
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-2@fc3c2ac

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.21
Hash: 91e34a0
Branch: remotes/origin/d17-3
Build date: 2022-07-22 20:10:19 UTC

Android Device Manager
Version: 0.0.0.1168
Hash: 4b9aaa3
Branch: 4b9aaa3
Build date: 2022-07-22 20:10:19 UTC

Build Information
Release ID: 1703002083
Git revision: fbfa325b70d6916a49fef93ae6ffc7312ee7a0ba
Build date: 2022-07-22 20:08:03+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.0.1
Darwin 21.1.0 Darwin Kernel Version 21.1.0
    Wed Oct 13 17:33:23 PDT 2021
    root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64"

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

### Build Logs

No build errors are there

**Comment by jfversluis** [comment]
Please add a small reproduction project that shows the issue. Thanks!

**Comment by agnihotritanisha** [comment]
Yes, I am creating a demo. Soon I will share with you.

**Comment by agnihotritanisha** [comment]
[Xamarin_Editor.zip](https://github.com/xamarin/Xamarin.Forms/files/9598950/Xamarin_Editor.zip)
This is our Demo Project.We are facing some problem with scrolling in editor when keyboard is up from so many days in our project.
In our Demo project there is one line text so when the keyboard is up we are unable to scroll in editor.
In this project for dynamic keyboard in Ios we have created a  Custom Keyboard view renderer in our code inside the folder Renderer.
In case of Android this is not creating a problem as when we keyboard up it automatically takes the cursor on the top of editor so our text is visible.  
But in the case of IPhone the cursor reaches bottom of editor when keyboard is up so we are unable to see our text.
In order to see our text when keyboard is up we are scrolling but the scrolls are not working in case of Ios.
And can you please suggest us something so that our cursor reaches the top of editor and our text becomes visible in case of Ios just like android.

**Comment by khanakia** [comment]
I am facing the same issue on M1 Max i cannot scroll through the editor check the video.


https://user-images.githubusercontent.com/2174170/191232762-5ee463a2-af54-4457-9c1d-c6e91f4b6d3e.mp4

**Comment by agnihotritanisha** [comment]
@jfversluis Please provide your suggestion I am facing this problem since last couple of months.

**Comment by khanakia** [comment]
@agnihotritanisha is issue fixed ?

**Comment by agnihotritanisha** [comment]
> @agnihotritanisha is issue fixed ?

Yes
