### ISSUE TITLE
Xamarin editor is not working fine in ios

### ISSUE THREAD

**Issue by agnihotritanisha** [xamarin/Xamarin.Forms#15531]
I am using xamarin.essentials version 1.6.1 and xamarin.forms version 5.0.0.2012 . The problem which I am facing is with ios only . So when text area is small scrollview is not working inside editor works only for long multiline text.

**Comment by jfversluis** [comment]
Please use the bug issue template we have in place to report issues so we're sure to catch all the information we need.

Also, those versions you mention seem out of date, update the the latest versions and see if that fixes it. Thanks!
