### ISSUE TITLE
[Bug] Is Xamarin Support Car Play business Apps

### ISSUE THREAD

**Issue by XamarinRPMTeam** [xamarin/Xamarin.Forms#15545]
Team , This is to ask you about the CarPlay Support in Xamarin . Is Xamarin Support CarPlay? .If yes Could you please get the official documentation on how to do it . We found one and only sample which is music app . Our requirement is to develop a business app which is very much required to do .

**Comment by jfversluis** [comment]
There might be support for Xamarin traditional, but definitely not for Xamarin.Forms. Also I think to create CarPlay apps to begin with you need special approval from Apple.
