### ISSUE TITLE
[Bug] Cannot build to iOS (Physical and Simulator)

### ISSUE THREAD

**Issue by mmendoza-apa** [xamarin/Xamarin.Forms#15549]
### Description
I cannot build to any iOS device or simulator.  The simulators do not even show in xCode
### Steps to Reproduce

1. Create new project
2. Build new project for ios
3. will fail

### Expected Behavior
Should build to device
### Actual Behavior
does not work

**Comment by jfversluis** [comment]
Going to assume that you have figured this out by now. If not, you probably want to report these kind of errors through Visual Studio. Choose Help > Provide Feedback > Report a Problem.

Thanks!
