### ISSUE TITLE
[Bug] iOS HttpClient PostAsync hangs on await

### ISSUE THREAD

**Issue by Henry-IDD** [xamarin/Xamarin.Forms#15559]
Similar to #3252 

### Description
await httpClient.PostAsync(Uri, httpConent);

=>

Sometimes it takes a long time(10~20 seconds) to send the api.

This problem is only encountered on physical iOS devices (iphone and ipad) after iOS 15 version.

It doesn't happen with the iOS 15 version of the emulator, neither does the Android device.

### Basic Information
Xamarin Forms Version: 4.8.0.1821

### Workaround
Use modernhttpclient-updated 2.7.2 version for ios version,

ex.
if (Device.RuntimePlatform == Device.iOS)
{
    httpClient = new HttpClient(new NativeMessageHandler());
}
else
{
    HttpClientHandler handler = new HttpClientHandler();
    httpClient = new HttpClient(handler);
}

Since the latest version (3.4.3) of modernhttpclient-updated will conflict with Portable.JWT 1.0.5 version, choose to use version 2.7.2.

**Comment by jfversluis** [comment]
I see the report is for Xamarin.Forms 4.8 which is quite old and we don't support it anymore.

Please try again with the latest version and open a new issue when the issue still shows with that. Thanks!
