### ISSUE TITLE
Add a property, hide - show keyboard

### ISSUE THREAD

**Issue by DS2107** [xamarin/Xamarin.Forms#15555]
Good afternoon, dear community. I recently started learning xamarin forms. I wrote my own little messenger. There were a lot of problems that I had to deal with. But the only problem that annoys me and which I managed to fix by clever manipulations is the keyboard problem . To write a message, I use either Entry or Edito. After I click on the "submit" button, the editor or entry control disappears from focus. this is very inconvenient because the user can write several messages in a row. In order for the focus not to disappear, I had to write customElem in the Android project and only then use it in the main Xamarin project.Forms. Dear developers, a huge request, make your own Editor or Entry element, in which the keyboard would not lose focus. AlwaysOpen = "true" or false

**Comment by ahoke-cr** [comment]
Xamarin.Forms is being superseded by .NET MAUI and is not having enhancements or new features added any longer. You might consider migrating to .NET MAUI since that has longer-term support and a higher likelihood of something like this being added.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
