### ISSUE TITLE
Nuget 2.5.0.122203 update - Wiped my Android Manifest settings

### ISSUE THREAD

**Issue by StanleyBroo** [xamarin/Xamarin.Forms#1555]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Nuget 2.5.0.122203 update - Wiped my Android Manifest settings
### Steps to Reproduce
Update Xamarin.Forms to Nuget 2.5.0.122203 ### Expected Behavior

### Actual Behavior
Wiped my Android Manifest settings

### Basic Information
VS2017 Enterprise preview
### Screenshots
..no screenshot necessary ..all checkboxes in Android Manifest unchecked after update.
... all [uses-permission] was removed by the update

**Comment by hartez** [comment]
> VS2017 Enterprise preview

@StanleyBroo  Which preview? Also, which `uses-permission` values did you have before they were wiped out?

**Comment by jassmith** [comment]
Closed due to inactivity
