### ISSUE TITLE
Where Application.Properties are stored and can users see them on operating system?

### ISSUE THREAD

**Issue by volkan-akkus-tr** [xamarin/Xamarin.Forms#15560]
Hi,
Sorry for inconvenience. I checked internet but could not find the answer. Please, kindly lead me to the answer.

I want to learn where Application.Properties are stored on iOS and Android.

Are users able to see them somehow? 

Thanks

**Comment by jfversluis** [comment]
This functionality is described here: https://learn.microsoft.com/xamarin/xamarin-forms/app-fundamentals/application-class#properties-dictionary

In theory others can read these values, so you should not use it for sensitive data. You'll want to use [secure storage](https://learn.microsoft.com/xamarin/essentials/secure-storage) for that.
