### ISSUE TITLE
[Bug] MessagingCenter is not thread safe

### ISSUE THREAD

**Issue by Bowman74** [xamarin/Xamarin.Forms#15563]
### Description
Calling subscribe and unsubscribe operations on one thread while doing MessagingCenter calls on another can cause a variety of multi-threading exceptions. The _subscriptions dictionary and the normal list<subscription> can be changed on one thread while another thread is doing a non thread safe operation like any(), contains(), etc. 

The comment on line 207 of the MessagingCenter.cs class acknowledges this issue but the fix used is not thread safe either; the ToList() method itself could fail due to it. 

Bug #15556 is also an example of this behavior.

### Steps to Reproduce

1. Get and run solution at [https://github.com/Bowman74/XFMessagingCenterBug](https://github.com/Bowman74/XFMessagingCenterBug)
2. Press the "No Errors" button and watch the debug window. No errors will happen. More on this later, but this is due to using a SemaphoreSlim to protect multithreaded access To the Subscribe and Unsubscribe method. When done close the popup window to allow the background tasks to complete.
3. Press the "Create Error" button and watch the debug window. Multiple errors will happen. This method is not doing anything to protect the subscribe and unsubscribe methods. When done close the popup window to allow the background tasks to complete.
4. Even worse. Without closing the app after the "Create Error" issue, press the "No Errors" button and watch the debug window. You will now observe multiple errors where there were none before. This is because the exceptions caused in step 2 left the MessagingCenter's _subscriptions dictionary and it's contained list<subscription>'s in an unknown state. Until the app is restarted, MessagingCenters will not be able to have new subscriptions added or removed.

### Expected Behavior
Methods on the MessagingCenter can be called on multiple threads without issue

### Actual Behavior
Subscribing and unsubscribing on multiple threads can cause a variety of exceptions (normally System.InvalidOperationException). If these exceptions are caught and not allowed to crash the app, the MessageCenter can be left in an invalid state and not be usable until the app is restarted.

### Basic Information

- Version with issue: Likely all versions, tested on 5.0.0.2012 and 5.0.02515, I have checked MAUI it is will be a problem there as well.
- Last known good version:  likely none
- Platform Target Frameworks: All platforms
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
Microsoft Visual Studio Enterprise 2019
Version 16.11.18
VisualStudio.16.Release/16.11.18+32802.440
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.110.1451
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.110.1451
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.110.1451
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.110.1451
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.126+g11d4cf0d0c.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.10.15 (552afdf)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.11.000.197 (d16-11@6934992)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.11.0.47 (remotes/origin/d16-11@e0d612363)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.10.5 (355b57a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.0.0.3 (d16-11/f0e3c2d)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/d16-11@476bb5b
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-11@87af37b


Xamarin.iOS and Xamarin.Mac SDK   15.2.0.17 (738fde344)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

### Reproduction Link

[https://github.com/Bowman74/XFMessagingCenterBug](https://github.com/Bowman74/XFMessagingCenterBug)

### Workaround
Wrapping all the methods of the MessagingCenter with containment and delegation and use a SemaphoreSlim to ensure only one thread can access it at at time will correct the issue and is likely the correct solution for

**Comment by jfversluis** [comment]
Thanks for the very extensive report and investigation here, much appreciated! I don't think we're going to fix this for Xamarin.Forms anymore and for .NET MAUI the MessagingCenter has already been deprecated and will be removed for .NET 8. I would suggest to use the CommunityToolkit MVVM Messenger: https://learn.microsoft.com/dotnet/communitytoolkit/mvvm/messenger
