### ISSUE TITLE
[Bug] Dependency Service is NULL only on Xamarin iOS - Xamarin Forms - Xamarin iOS Class Library

### ISSUE THREAD

**Issue by pkvaranasi** [xamarin/Xamarin.Forms#15574]
### Description
Found a critical blocker in running Xamarin Forms apps for iOS. 
It's a simple approach we did but the approach is not running on iOS but it's working perfectly on Android.

We want to. make use of dependency services using Xamarin Forms, but this approach is not working with the below given steps to reproduce.
Attached the source code we had used, which is running on Android, but not running only on iOS.

### Steps to Reproduce

1. Create a new Xamarin Forms apps using Visual Studio 2022 default templates, which creates 3 projects. Core, Android & iOS projects.
2. Write a small test dependency service to test. Write the Interface in the core project, and implementation in iOS project.
3.  Ensure to include assembly & dependency declaration on top of the namespace in the class implementation in iOS project.
4. Test this dependency service, by using DependencyService.Get<>() and it returns the object.
5. Add a solution folder, called Common or Core or any name.
6. Add a project, inside the newly created Common/Core solution folder, of type Class Library (may be .NET Standard 2.0 or 2.1)
7. Add another project , inside the same solution folder, of type "iOS App (Xamarin)". This creates a class library of type Xamarin iOS.
8. Now, delete the dependency services created earlier - Interface and implementation.
9. Refer the newly created Class library to the main core project.
10. Refer the newly created "iOS App (Xamarin)" project to the main iOS project.
11. Now, write the same dependency service in the newly created projects. 
12. Implement the newly created dependency service in the newly created iOS project.
13. Consume this newly created dependency service from iOS project.
14. Dependency service returns NULL.

### Expected Behavior
Dependency service should work in the actual projects and in referred Xamarin projects.
### Actual Behavior
Dependency Service is returning null.
### Basic Information

- Version with issue: Any Xamarin forms version
- Last known good version: Latest Xamarin Forms 5.0.0.2515
- Platform Target Frameworks: 
  - iOS:  11.0

- NuGet Packages: Xamarin.Forms
- Affected Devices: iPhones

### Environment
Visual Studio 2019 MAC
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/9840877/Test.zip)

**Comment by pkvaranasi** [comment]
This is a blocker for us. Really appreciate if someone can this as priority and help us to resolve the issue at the earliest.

**Comment by jfversluis** [comment]
What probably happens is that there is no code reference from Core.iOS in Test.iOS. Therefore, the assembly Core.iOS is removed by the linker since it thinks that it's not being used.

Registering your dependency through a line of code instead of the attribute, [as described here](https://learn.microsoft.com/xamarin/xamarin-forms/app-fundamentals/dependency-service/registration-and-resolution#registration-by-method), will make the problem go away.

Other solutions is: add Core.iOS as an exception to the compiler to not be optimized or make a dummy reference to a type in your Test.iOS project, for instance `var foo = new Core.iOS.PackInfo();`
