### ISSUE TITLE
[Bug] NaN is not a valid value for width, crash < 1s

### ISSUE THREAD

**Issue by mmilkovski** [xamarin/Xamarin.Forms#15579]
### Description
Application is working alright on iOS and Android, unless device UI language is switched to Hebrew (RightToLeft UI) and then it crashes on startup only on iOS. 

After hours of searching the cause, for some reason 2 labels on UI which are longer than device width and have to WordWrap cause this. These labels and the text have been added on the UI like 1 year ago and didn't do this but i also found that some shorter labels that are also centered horizontally on the UI fail to show properly but don't crash the app. 

### Steps to Reproduce

1. in page content put StackLayout with Vertical Orientation
2. add 2 labels, about 150 characters long which should linebreak = wordwrap
3. device language should be Hebrew so the RTL UI

### Expected Behavior
run normally
### Actual Behavior
app crash < 1s
### Basic Information

- Version with issue:
- Last known good version: don't remember
- Platform Target Frameworks: 
  - iOS:  16
  - Android: 12
- NuGet Packages:
- Affected Devices: all with RTL UI (tested iOS 15.7 and 16.0.3)

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

Visual Studio Community 2022 for Mac
Version 17.3.8 (build 5)
Installation UUID: 29ae4465-e02c-4166-b899-d9d46421184c

Runtime
.NET 6.0.5 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.3.0-3.22312.2+52adfb8b2dc71ed4278debcf13960f2116868608

NuGet
Version: 6.2.2.1

.NET SDK (Arm64)
SDK: Not installed

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.5
	6.0.4
	6.0.3
	6.0.2
	5.0.17 (x64 – Unsupported)
	5.0.16 (x64 – Unsupported)
	5.0.15 (x64 – Unsupported)
	5.0.14 (x64 – Unsupported)
	3.1.27 (x64 – Unsupported)
	3.1.25 (x64 – Unsupported)
	3.1.24 (x64 – Unsupported)
	3.1.23 (x64 – Unsupported)
	3.1.22 (x64 – Unsupported)

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.0.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-3/030cd63
Android SDK: /Users/milkovski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-3@7716ae53
SQLite: xamarin/sqlite/3.38.5@df4deab
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@14076a6

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.3.0.23
Hash: 965bf40
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:57 UTC

Android Device Manager
Version: 0.0.0.1169
Hash: fafb1d5
Branch: fafb1d5
Build date: 2022-10-13 22:08:57 UTC

Apple Developer Tools
Xcode 14.0 (21335)
Build 14A309

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Community)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Xamarin Designer
Version: 17.3.0.208
Hash: 0de472ea0
Branch: remotes/origin/d17-3
Build date: 2022-10-13 22:08:53 UTC

Build Information
Release ID: 1703080005
Git revision: 6a0d8af1de04f96af57762154da284796414cdd2
Build date: 2022-10-13 22:06:30+00
Build branch: release-17.3
Build lane: release-17.3

Operating System
Mac OS X 12.6.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Mon Aug 22 20:19:52 PDT 2022
    root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

</details>

### Reproduction Link

i will create simple project if can't be reproduced

### Workaround

comment out that UI section

### Crash stack log
[ios_crash_stack.log](https://github.com/xamarin/Xamarin.Forms/files/9858499/ios_crash_stack.log)
[ios_exception.log](https://github.com/xamarin/Xamarin.Forms/files/9858580/ios_exception.log)

**Comment by mmilkovski** [comment]
it turns out it has to do with NewLine + RTL + Hebrew
working workaround https://github.com/xamarin/Xamarin.Forms/issues/15535#issuecomment-1253358763

**Comment by jfversluis** [comment]
Hey @mmilkovski! A PR (#15605) for this is open now, would you be able to grab the NuGet [as described here](https://github.com/xamarin/Xamarin.Forms/wiki/Preview-Packages) and let us know if this fixes this issue? That will greatly speed up the review process.

Besides verifying if this particular issue is fixed also be sure to check other scenarios in the same area to make sure that this fix doesn't accidentally has side-effects 🙂 

Thanks!

**Comment by mmilkovski** [comment]
Hey @jfversluis - did test the app while using #5.0.0.8369 and it works as it should.

Issue fixed, Thanks !

**Comment by jfversluis** [comment]
@mmilkovski jut to be sure, please don't use that version in production! It's just a test NuGet from a build, it doesn't has all the latest changes and it probably won't update whenever a new official version will come up.

Thanks for confirming though! Merging this change and should show up in the next release which should be soon!

**Comment by mmilkovski** [comment]
Not a problem @jfversluis, had time to spare and wanted to check if the issue was solved. 

Thanks again
