### ISSUE TITLE
[Enhancement] Support for Android 14 and maybe 15?

### ISSUE THREAD

**Issue by mdbill** [xamarin/Xamarin.Forms#15595]
With end of support is May 2024, it seems that **at a minimum Android 14** support should be added.  If not, google will refuse to install XF apps on Android 14+ in Nov 2024.  A production app should be able to live for many years (ideally) after end of support for XF.  And no, my production apps won't port to MAUI easily--if at all.

**Comment by giuseppenovielli** [comment]
@mdbill check this discussion https://github.com/xamarin/Xamarin.Forms/discussions/15508

**Comment by mohachouch** [comment]
We have the same problem in our company. We are using Xamarin Forms in a large application and the migration is not easy at all. The date of March 1, 2024 is coming very quickly. The automatic migration tool is fine for a HelloWorld project but not for a large application with multiple dependencies. @davidortinau @PureWeen @jsuarezruiz can you give us an answer ?

**Comment by holecekp** [comment]
This is a bad news. I hope that Microsoft will reconsider the end of support date and (even more importantly) the support for the upcoming Android 14. When I look at the current state of MAUI, it will not be ready as a replacement by the time when Android 14 is released.

To be fair, the migration process to MAUI was easier than I expected. The only bigger problem for the migration were the incompatibilities between UWP and WinUI . However, the the reason why I think that the current end of support date is not realistic is the huge number of bugs in the current version of MAUI. The simplest controls does not work correctly - I have encountered problems with TapGestureRecognizer, RadioButtons with templates, BoxView, FlexLayout, ToolbarItems, CollectionView items height calculation, pasting text from the Clipboard, Shell menu inconsistencies among different platforms, Controls often not being rendered if IsVisible is changed at runtime, TabbedPage that cannot be used with the Shell, and many others. By the way, I have tried .NET 7 version of MAUI and I can see no progress compared to the latest .NET 6 - one issue has been fixed (AdaptiveTriggers), but multiple new issues have been added (including serious Microsoft.UI.Xaml.Controls.Frame.NavigationFailed crashes on some pages on Windows). Moreover, I cannot see the promised performance benefits. At least not in the emulator. There is an excellent article about the performance improvements in .NET 7 MAUI (https://devblogs.microsoft.com/dotnet/dotnet-7-performance-improvements-in-dotnet-maui/), but the reality is that MAUI version of my app still runs in the emulator about 5 times slower than the original Xamarin.Forms version.

I estimate that it will take at least a year to fix the most significant bugs, and years to make the MAUI to be on the same usability level as Xamarin.Forms.

**Comment by jfversluis** [comment]
As pointed out on the official [support page](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin#:~:text=Xamarin%20support%20will%20end%20on,final%20versions%20Xamarin%20will%20target), that will likely not happen. 

.NET MAUI is the future and May 2024 should give you enough time to transition.

**Comment by mohachouch** [comment]
The release of Android 14 will be available in **September 2023 on Google Nexus**. Applications on Xamarin Forms will therefore not be able to work on Nexus device from September 2023. It is therefore necessary either to change the end of support date to September 2023 or to make Xamarin Forms 5.0 compatible with Android 14.  Thank you.
