### ISSUE TITLE
[Bug] Xamarin.MacOS Rendering Issues inside ScrollView

### ISSUE THREAD

**Issue by ktdev1** [xamarin/Xamarin.Forms#15596]
### Description
Xamarin.MacOS controls inside a ScrollView that are initially out of view frequently do not render on screen after scrolling them into view. This only started happening after we upgraded our Mac system from OS 12.2 to 12.5.

This issue was originally reported here where a Microsoft rep was able to reproduce the issue.
https://learn.microsoft.com/en-us/answers/questions/1063871/xamarinmac-rendering-issues-inside-scrollview.html

### Steps to Reproduce

1. Run the attached sample project, which contains several basic controls (Entry, Labels, Frame, etc) inside of a Scroll View.
2. Scroll down to the bottom of the page or scroll up to the top of the page. Notice that sometimes the controls are missing. 

### Expected Behavior
We expect that the controls will render properly (see picture below):
![image](https://user-images.githubusercontent.com/109307531/200647304-36c50c6f-b4cd-48a2-814a-932dc1891f76.png)

### Actual Behavior
Some of the controls do not render every time:
![image](https://user-images.githubusercontent.com/109307531/200647370-ad2241e9-1419-4bbd-b4a9-969f3d346287.png)
![image](https://user-images.githubusercontent.com/109307531/200647389-1f6c3532-6340-49f1-aa73-723a69bec983.png)

### Basic Information

- Version with issue:  Xamarin.Forms (5.0.0.2515) on MacOS 12.5 and 12.6
- Last known good version: Had previously worked fine on MacOS 12.2
- Platform Target Frameworks: 
  - MacOS:  OS Version 12.5 (Monterey)
- Android Support Library / AndroidX Version: N/A
- NuGet Packages: Xamarin.Forms, Xamarin.Essentials, and we have also included Syncfusion.Xamarin SfDataGrid since we have noticed this control is heavily impacted.
- Affected Devices: We have seen this issue occur on our M1 Mac Mini, 2020 and Intel Macbook Pro, 2017.

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
=== Visual Studio Community 2019 for Mac ===

Version 8.10.25 (build 2)
Installation UUID: 0a26c112-ef54-4561-89d7-2d1c5019759e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000182

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.182 (2020-02/6051b710727) (64-bit)
	Package version: 612000182

=== Roslyn (Language Service) ===

3.10.0-4.21269.26+029847714208ebe49668667c60ea5b0a294e0fcb

=== NuGet ===

Version: 5.9.0.7134

=== .NET SDK (x64) ===

SDK: /usr/local/share/dotnet/x64/sdk/6.0.106/Sdks
SDK Versions:
	6.0.106
	6.0.102
	5.0.408
	5.0.405
	3.1.420
	3.1.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.6
	6.0.2
	5.0.17
	5.0.14
	3.1.26
	3.1.22

=== .NET Core 3.1 SDK ===

SDK: 3.1.420

=== .NET 5.0 SDK ===

SDK: 5.0.408

=== Xamarin.Profiler ===

Version: 1.8.0.22
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 12.2.8.3 (Visual Studio Community)
Commit: xamarin-android/d17-1/fafdba7
Android SDK: /Users/keytech/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 30.0.4
SDK Build Tools Version: 30.0.2

Build Information: 
Mono: dffa5ab
Java.Interop: xamarin/java.interop/d17-1@7ac33610
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.37.1@0893b3b
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7

=== Eclipse Temurin JDK ===

Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.10.0.13
Hash: 1b81df5
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:32 UTC

=== Android Device Manager ===

Version: 16.10.0.15
Hash: 89dcc0b
Branch: remotes/origin/d16-10
Build date: 2021-11-12 00:17:52 UTC

=== Apple Developer Tools ===

Xcode 13.4.1 (20504)
Build 13F100

=== Xamarin.Mac ===

Version: 8.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:06-0400

=== Xamarin.iOS ===

Version: 15.10.0.5 (Visual Studio Community)
Hash: 96b3edb6d
Branch: d17-2
Build date: 2022-05-18 07:32:07-0400

=== Xamarin Designer ===

Version: 16.11.0.60
Hash: 56f9b80b0
Branch: remotes/origin/d16-11
Build date: 2021-12-15 01:44:16 UTC

=== Build Information ===

Release ID: 810250002
Git revision: 0620af530b5800e0eada4882ce1c3d4dad7e53d3
Build date: 2022-06-15 13:41:26-04
Build branch: release-8.10

=== Operating System ===

Mac OS X 12.5.0
Darwin 21.6.0 Darwin Kernel Version 21.6.0
    Sat Jun 18 17:05:47 PDT 2022
    root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 x86_64


```

</details>

### Build Logs
N/A since this appears to be a runtime issue.

### Screenshots
See included screenshots above in the Expected Behavior and Actual Behavior sections.

### Reproduction Link

[MacRender.zip](https://github.com/xamarin/Xamarin.Forms/files/9964203/MacRender.zip)

### Workaround
The user can click on the controls to get them to re-render back into view. Also minimizing and maximizing the application will sometimes get the controls to re-render properly. We’ve noticed this rendering issues mostly affects Frame elements wrapped inside of a Grid element and have been able to resolve most rendering issues inside of the ScrollView by replacing all Frame elements with ContentViews or BoxViews.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
