### ISSUE TITLE
[Bug] Animation is not working on Android (API 31)

### ISSUE THREAD

**Issue by hulluP** [xamarin/Xamarin.Forms#15622]
### Description
new Animation is not working on Android (API 31) anymore. when setting the length to any time the animation does only 2 runs first with value is 1 and second run the value is 100. 
### Steps to Reproduce

1.  download the Animation Sample from https://github.com/xamarin/xamarin-forms-samples/tree/main/UserInterface/Animation/Basic
2.  start the Android Simulator API 31
3. start any Animation -> which will result in a flicker and the animation is complete

### Expected Behavior
like on iOS animation showing correct 
![iPhone](https://user-images.githubusercontent.com/46395952/205868811-238e08fd-a620-4be8-ae46-f8230274e1b9.gif)

### Actual Behavior
Android simulator:
![androidAni](https://user-images.githubusercontent.com/46395952/205868572-9388299d-0b00-429d-b782-886de317bcc9.gif)

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  16.1
  - Android: Target Android 10.0, Emulator API 31
- Android Support Library / AndroidX Version: 
- NuGet Packages: Xamarin.Forms 5.0.0.2515
- Affected Devices: Android

### Environment

Visual Studio Enterprise 2022 for Mac
Version 17.4 (build 2406)
Installation UUID: 61dcca14-32a5-42b6-a17b-797460b5f45d

Runtime
.NET 6.0.9 (64-bit)
Architecture: Arm64

Roslyn (Language Service)
4.4.0-3.22461.4+8ab250290a4010c11a21521f78dbc87dbb7aac81

NuGet
Version: 6.3.1.1

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.100/Sdks
SDK Versions:
	7.0.100
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.203
	6.0.202
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64)
SDK Versions:
	6.0.403
	6.0.402
	6.0.401
	6.0.400
	6.0.302
	6.0.301
	6.0.300
	6.0.203
	6.0.202
	6.0.105
	6.0.104
	6.0.103
	5.0.408
	5.0.407
	5.0.406
	3.1.425
	3.1.424
	3.1.423
	3.1.422
	3.1.421
	3.1.420
	3.1.419
	3.1.418
	3.1.417

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.0
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/x64/dotnet
Runtime Versions:
	6.0.11
	6.0.10
	6.0.9
	6.0.8
	6.0.7
	6.0.6
	6.0.5
	6.0.4
	6.0.3
	5.0.17
	5.0.16
	5.0.15
	3.1.31
	3.1.30
	3.1.29
	3.1.28
	3.1.27
	3.1.26
	3.1.25
	3.1.24
	3.1.23

Xamarin.Profiler
Version: 1.8.0.19
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.1.0.1 (Visual Studio Enterprise)
Commit: xamarin-android/d17-4/13ba222
Android SDK: /......../Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.2
SDK Build Tools Version: 33.0.0

Build Information: 
Mono: a96bde9
Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
SQLite: xamarin/sqlite/3.39.3@23e1ae7
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.12
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.4.0.54
Hash: 6eabb9e
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:26 UTC

Android Device Manager
Version: 0.0.0.1206
Hash: 886af39
Branch: 886af39
Build date: 2022-11-02 23:47:26 UTC

Xamarin Designer
Version: 17.4.0.136
Hash: d49c9ff6d3
Branch: remotes/origin/d17-4
Build date: 2022-11-02 23:47:17 UTC

Apple Developer Tools
Xcode 14.1 (21534.1)
Build 14B47b

Xamarin.Mac
Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

Xamarin.iOS
Version: 16.0.0.72 (Visual Studio Enterprise)
Hash: 6756a1146
Branch: release/6.0.4xx-xcode14
Build date: 2022-09-21 08:51:06-0400

Build Information
Release ID: 1704002406
Git revision: dfb45c1152306f0d5f77334f9d026b0aadb7ec90
Build date: 2022-11-02 23:44:22+00
Build branch: release-17.4
Build lane: release-17.4

Operating System
Mac OS X 13.0.1
Darwin 22.1.0 Darwin Kernel Version 22.1.0
    Sun Oct  9 20:15:09 PDT 2022
    root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

### Screenshots

see above

### Reproduction Link

see above

### Workaround

for dev and testing use another version of Android

**Comment by jfversluis** [comment]
Is it specific to API 31? Does it work on earlier platforms? Do you have energy saver settings on by any chance?

**Comment by hulluP** [comment]
for me it is working on earlier versions of the simulator.
