### ISSUE TITLE
Error while trying to create Archive for iOS App[Bug] 

### ISSUE THREAD

**Issue by dimeom** [xamarin/Xamarin.Forms#15627]
I am trying to archive an iOS app on Xamarin Forms. and I am getting this error:

EMessagingRemoteException: An error occurred on client Build1740301 while executing a reply for topic xvs/build/17.4.0.301/execute-task/MCAuthenticator.iOS/c066583002fACTool
AggregateException: One or more errors occurred.
Win32Exception: ApplicationName='arch', CommandLine='-arch arm64e /usr/bin/xcrun actool --errors --warnings --notices --output-format xml1 --output-partial-info-plist /Users/mcmacbook/Library/Caches/Xamarin/mtbs/builds/MCAuthenticator.iOS/c0665838da3ce9d9f18d873a28779f482406226f044946180c3297466da29eef/obj/iPhone/Release/actool/partial-info.plist --app-icon AppIcons --compress-pngs --target-device iphone --minimum-deployment-target 14.0 --platform iphoneos --compile /Users/mcmacbook/Library/Caches/Xamarin/mtbs/builds/MCAuthenticator.iOS/c0665838da3ce9d9f18d873a28779f482406226f044946180c3297466da29eef/obj/iPhone/Release/actool/bundle /Users/mcmacbook/Library/Caches/Xamarin/mtbs/builds/MCAuthenticator.iOS/c0665838da3ce9d9f18d873a28779f482406226f044946180c3297466da29eef/obj/iPhone/Release/actool/cloned-assets/Assets.xcassets', CurrentDirectory='', Native error= Cannot find the specified file	MCAuthenticator.iOS			

I have searched on the web and tried everything I could but nothing is working...

On my Windows I am working with:
Visual Studio 17.4.2
Xamarin 17.4.0.301
Xamarin iOS and Xamarin Mac 16.0.0.92

on my Mac:
Xcode 14.1
Mac Ventura

**Comment by jfversluis** [comment]
Hey there! This is an issue with the tooling.

Please report this through Visual Studio. Under the Help menu select Provide Feedback and then Report a Problem. Thanks!
