### ISSUE TITLE
Geocoder.GetPositionsForAddressAsync() always return 0 for UWP

### ISSUE THREAD

**Issue by Ajaysinh4377** [xamarin/Xamarin.Forms#1562]
### Description
Xamarin.Forms.Maps  Geocoder.GetPositionsForAddressAsync() always return 0 for UWP

### Expected Behavior
Geocoder.GetPositionsForAddressAsync() return actual positions. 
### Actual Behavior
return 0 position 
### Basic Information
- Platform Target Frameworks:
  - UWP:  16299 
- Nuget Packages: Xamarin.Forms.Maps - 2.5.0.121934
- Affected Devices: LocalMachine

**Comment by hartez** [comment]
@Ajaysinh4377 I just tried using that method from the Maps Gallery section of the Control Gallery, and it appears to be returning results. Can you attach a minimal repro project demonstrating the issue?

**Comment by Ajaysinh4377** [comment]
[https://github.com/Ajaysinh4377/mapDemo](url)

plz check above repo for UWP

**Comment by Ajaysinh4377** [comment]
understood what i am saying ?

**Comment by hartez** [comment]
@Ajaysinh4377 I think the URL for your repo is incorrect.

**Comment by Ajaysinh4377** [comment]
resolved after adding below line in APP.XAML.CS file.

 `Windows.Services.Maps.MapService.ServiceToken = "bingMap Key";`
