### ISSUE TITLE
Unwanted margin on frame using android 4.4

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#1563]
### Description

Frame control has margin on Android 4.4, even with margin set to 0. This doesn't occur on android 5.0 up. 

### Steps to Reproduce

1.  Open the attached project: [FrameMargin.zip](https://github.com/xamarin/Xamarin.Forms/files/1625671/FrameMargin.zip)
2.  Run on android 4.4

### Expected Behavior
The blue bar is being rendered at the top left corner and spanning the entire width without any margin

### Actual Behavior
The blue bar is not being rendered at the top left corner and spanning the entire width, but is has margin the the left, top and right

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: ?
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 25.4.0.2 (but it also occurs with 26.1.0.1)
- Nuget Packages: -
- Affected Devices: -

### Screenshots

![framemarginissue](https://user-images.githubusercontent.com/7567114/34870763-5c1e6a36-f78b-11e7-8c3b-3d603598ce6a.png)

### Reproduction Link

[FrameMargin.zip](https://github.com/xamarin/Xamarin.Forms/files/1625671/FrameMargin.zip)

**Comment by PaulVrugt** [comment]
Does anyone know any workaround for this? This issue really messes up the layout of our apps on android 4.4

**Comment by CNouws** [comment]
@samhouts I'm a team member of PaulVrugt and checked this issue. It seems to be fixed in the latest versions of Xamarin Forms and Android.Support library.

**Comment by samhouts** [comment]
Outstanding! Thank you for taking the time to look at it again, and thank you for letting me know! I'll close this now. Let us know if there is anything else we can do for you.

**Comment by D4rkC1own187** [comment]
Still an issue with the latest Xamarin Forms.
