### ISSUE TITLE
[Bug] Problem with SplashScreen

### ISSUE THREAD

**Issue by freezersharp** [xamarin/Xamarin.Forms#15635]
### Description
All my mobile apps using splash screens but I'm facing an issue when I use Android 13 devices, because these splash screens are not showing. Android 12 (and below) devices are working fine.

### Steps to Reproduce

1. All steps for the android splash process (splash.xml, splashActivity, styles.xml, image in drawable folder, etc.)
2. Set both Android Target version and Compile using Android version options in the Android project, to Android 13.0 (API level 33).
3. Run the app or generate the APK file to testing.

### Expected Behavior
Splash screen is showed in all Android devices.

### Actual Behavior
Android 12 and below, the splash screen is showed correctly.
Android 13: a white screen is showed and the app icon in the middle.

### Basic Information

- Version with issue: All nuget packages to the lastest version.
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 13 (API 33).
  - UWP:  N/A
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices: Android 13 devices and emulators.

### Environment
Tested using Visual Studio 2022 and 2022 Preview, with the lastest updates.
Xamarin Forms 5, even I installed additional nuget packages like:

Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat
Xamarin.AndroidX.Core.SplashScreen

Nothing works.

**Comment by AlleSchonWeg** [comment]
Android 12 implemented a new Splash Screen API:
https://developer.android.com/about/versions/12/behavior-changes-all#splash-screen-migration
Perhaps this could be your problem.

**Comment by jfversluis** [comment]
This should help: https://codetraveler.io/2022/08/16/supporting-android-splash-screens-in-xamarin-forms/
