### ISSUE TITLE
Facing this issue with MAUI. Display promptasync dialog  appears, after Display alert , but doesn't appear first

### ISSUE THREAD

**Issue by shettysupreetha** [xamarin/Xamarin.Forms#15630]
Facing this issue with MAUI. Display promptasync dialog  appears, after Display alert , but doesn't appear first

_Originally posted by @shettysupreetha in https://github.com/xamarin/Xamarin.Forms/issues/8526#issuecomment-1348190876_

**Comment by jfversluis** [comment]
This is the Xamarin.Forms repo, if you have any issues with .NET MAUI, please report it on that repository, thanks!
