### ISSUE TITLE
Attached Property Accessors are not being called

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15657]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Attached-Property-Accessors-are-not-bein/10220291)._

---
After creating an attached property, the Accessors (Set and Get are not being called);

**Code:**
public class AbsoluteLayoutEx: AbsoluteLayout, ITagView
{
**// THIS METHOD NEVER GETS CALLED!!!**
    public static void SetDock(BindableObject bindable, DockStyle dockStyle)
    {
        if (bindable is View v && v.Parent is AbsoluteLayoutEx abs)
            abs.SetDock(v, dockStyle);
    }

**// THIS METHOD NEVER GETS CALLED!!!**
    public static DockStyle GetDock(BindableObject bindable)
    {
        if (bindable is View v && v.Parent is AbsoluteLayoutEx abs)
            return abs.GetDock(v);
        return DockStyle.None;
    }

    public static readonly BindableProperty DockProperty = BindableProperty.CreateAttached("Dock", typeof(DockStyle), typeof(AbsoluteLayoutEx), DockStyle.None);

**Xaml:**
                
                    
                    
                    
                    
                    
                    
                

---
#### Alexander Perelberg on 12/2/2022, 09:45 AM: 

(private comment, text removed)
#### Tracy Wang [MSFT] on 12/4/2022, 07:00 PM: 

(private comment, text removed)
#### Alexander Perelberg on 12/7/2022, 04:26 AM: 

(private comment, text removed)
#### Alexander Perelberg on 12/11/2022, 08:28 AM: 

(private comment, text removed)
#### Feedback Bot on 12/21/2022, 10:54 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looking at the internal ticket this was supposed to be a .NET MAUI bug. If the author sees this and still thinks this is an issue there, please open an issue on https://github.com/dotnet/maui. Thanks!
