### ISSUE TITLE
Restsharp - Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.

### ISSUE THREAD

**Issue by Simon-72** [xamarin/Xamarin.Forms#15663]
Are there any plans to update Xamarin to resolve these warning ?

Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved.
 There was a conflict between "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
     "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
     References which depend on "System.Numerics.Vectors, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll].
         C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll
           Project file item includes which caused reference "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Numerics.Vectors.dll".
             System.Numerics.Vectors
     References which depend on "System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [].
         C:\Users\bob\.nuget\packages\system.text.json\5.0.1\lib\netstandard2.0\System.Text.Json.dll
           Project file item includes which caused reference "C:\Users\bob\.nuget\packages\system.text.json\5.0.1\lib\netstandard2.0\System.Text.Json.dll".
             C:\Users\bob\.nuget\packages\system.text.json\5.0.1\lib\netstandard2.0\System.Text.Json.dll
             C:\Users\bob\Source\Repos\M2S_CN\M2SScanner\Output\bin_App\Release_QA\netstandard2.1\M2SScanner.dll
             C:\Users\bob\.nuget\packages\restsharp\108.0.3\lib\netstandard2.0\RestSharp.dll

**Comment by jfversluis** [comment]
This issue does not contain enough information to properly diagnose what might be going on, sorry.

I suspect you might be able to "fix" it by installing this NuGet package explicitly with a certain version.

**Comment by a-einstein** [comment]
I have exactly the same thing. For years already.

The message tells you all you need to know, I would say.

It's remarkable that only MonoAndroid\v1.0 actually holds dlls, the other ones (up to 13.0, currlently) don't.

There is a similar problem on System.Security.Principal.Windows.
