### ISSUE TITLE
[Bug] Updating Xamarin.AndroidX.AppCompat to 1.6.0 causes ReflectionLoadException

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#15668]
### Description

Updating Xamarin.AndroidX.AppCompat to 1.6.0 causes following error at startup:

`Could not resolve type with token 01000363 from typeref (expected class 'AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper' in assembly 'Xamarin.AndroidX.AppCompat.AppCompatResources, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')`

### Steps to Reproduce

1. Update [Xamarin.AndroidX.AppCompat to 1.6.0](https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat/1.6.0)
2. debug app

### Expected Behavior

app starts fine

### Actual Behavior

error at startup

### Basic Information

- Version with issue: 
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android: Targetframework 12.0
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages: https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat/1.6.0
- Affected Devices:

### Environment

VS2019 16.11.23

### Workaround

stay at [1.5.1.1](https://www.nuget.org/packages/Xamarin.AndroidX.AppCompat/1.5.1.1)

**Comment by jfversluis** [comment]
Usually this happens after an upgrade and you need to aggressively do some rebuilds and/or delete the bin & obj folders to clear the cache. Have you tried that?

**Comment by MagicAndre1981** [comment]
yes, I did this. I just saw at AndroidX repository there is also a [bug report similar to mine](https://github.com/xamarin/AndroidX/issues/690)

**Comment by MagicAndre1981** [comment]
@jfversluis  I also tested the new [massive nuget updates from PR](https://github.com/xamarin/AndroidX/pull/689) and issue is the same. 

Comparing 1.5.1.1 with 1.6.x shows that the classes are renamed. In 1.6.x Compat was added to class names in AndroidX.AppCompat.AppCompatResource. 

![_Appcompat](https://user-images.githubusercontent.com/8274816/213984766-cbc80928-dce5-42ad-a634-b916d29f1d91.png)

This is why DrawableWrapper is not found any longer as the new name is now DrawableWrapperCompat

**Comment by MagicAndre1981** [comment]
The Android Platform implements `ClipDrawableWrapper` in `ShellSearchView.cs` from [DrawableWrapper](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.Android/Renderers/ShellSearchView.cs#L368).

And because of the renamed class this causes runtime failure. So update this code and require new lib as nuget dependency

**Comment by MagicAndre1981** [comment]
as mentioned above a class is renamed and XF requires the old class name which triggers this error.

**Comment by sk1llsh0t** [comment]
It is strange the error only occurs for me when i've set the deployment configuration to release. if it is set to debug, it works.

**Comment by MagicAndre1981** [comment]
ok @jfversluis those new [AndroidX nugets require now Targetframework 12.0 ](https://github.com/xamarin/AndroidX/issues/444). This is a massive change in code. Can someone from the team make retarget and nuget androidx bumps?

**Comment by solomonfried** [comment]
I am targeting Android 12 and still can't build in Release. I have switched back to 1.5.1.1 for the Xamarin.AndroidX.AppCompat and Xamarin.AndroidX.AppCompat.AppCompatResources. 
Seems to be working

**Comment by MagicAndre1981** [comment]
Android 12 is required for building XF with new androidx nugets not your app itself.

**Comment by solomonfried** [comment]
@MagicAndre1981 Not sure I understand. I am building on VS2022 with Android SDK Platform 33 installed.
My Target Android Version for the app is 12.0 API Level 31

Release build fails with Failed to resolve AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper using AppCompat Nuget libraries 1.6.x. But does build with 1.5.1.1

**Comment by MagicAndre1981** [comment]
yes, but trying to make XF comaptible with AndroidX.AppCompat.Graphics.Drawable.DrawableWrapper  1.6.x XF itself must target Android12. Currently they build XF against old AndroidX libs and target Android10

**Comment by solomonfried** [comment]
Got it! So we need to wait for an update. I'll stay on 15.1.1 until we get the XF update

Thanks for the clarification.

**Comment by sasa-bobic** [comment]
A workaround that so far works for me was to build a custom binding library and add missing (renamed) classes back and repacking this in custom local nuget.

Basically this:
https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources/blob/master/Xamarin.AndroidX.AppCompat.AppCompatResources/Additions/DrawableContainer.cs)

And this:
https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources/blob/master/Xamarin.AndroidX.AppCompat.AppCompatResources/Additions/DrawableWrapper.cs

See this repo:
https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources

**Comment by donfbecker** [comment]
Downgrading to 1.5.1.1 does not solve the problem for me.  I have tried clearing all caches after downgrade, but problem persists.

**Comment by rvalitov** [comment]
@donfbecker it worked for me. Perhaps you have some nuget packages that have dependency of the ver 1.6.0 of AppCompat and silently selected newer version to be installed?

**Comment by donfbecker** [comment]
> @donfbecker it worked for me. Perhaps you have some nuget packages that have dependency of the ver 1.6.0 of AppCompat and silently selected newer version to be installed?

The NuGet package manager reported that 1.5.1.1 was installed, but I did find some warnings about version requirements of other Xamarin.AndroidX packages that were in use.  I had to downgrade the other four AndroidX packages as well.

**Comment by cncb-gh** [comment]
Will this be addressed soon or do we all need to use the workaround @sasa-bobic posted?

**Comment by MagicAndre1981** [comment]
there is a [PR](https://github.com/xamarin/Xamarin.Forms/pull/15718) to [fix the issue](https://github.com/xamarin/Xamarin.Forms/pull/15718/files#diff-77f0272ce5bb32786a3ca77952d8a438a9dea0c87bd5f0156e1341394c44eecc) and upgrade to Monodroid13.0

**Comment by AlleSchonWeg** [comment]
Same problem in release mode. Debug works. Problem is that  Xamarin.AndroidX.AppCompat >= 1.6.0 is needed for the new "per-app language preferences" in android 13: https://developer.android.com/guide/topics/resources/app-languages#java

**Comment by siddhant-maurya** [comment]
I am also facing the same error, and our project needs to be updated to Android 13. Can anyone provide a solution please!

**Comment by MagicAndre1981** [comment]
as said, Microsoft works on it and [already has a PR](https://github.com/xamarin/Xamarin.Forms/pull/15718)

**Comment by BillyMartin1964** [comment]
> Xamarin.AndroidX.AppCompat

It's not that it works in debug. It works with Linker set to none.

**Comment by ivaldiviah** [comment]
Downgrading Xamarin.AndroidX.AppCompat  to 1.5.1.1 does not solve the problem, clean the proyect and delete bin and obj folder does not solve the problem...

In Debug mode, works perfectly, the problem is only in release mode, i have de links options to none and persist de error.

Has anyone found any solution?

**Comment by mos379** [comment]
@ivaldiviah just use pre release of xamarin.forms and latest appCompat. then it should work.

**Comment by dejanbasic** [comment]
It works for me, when I also downgrade Xamarin.AndroidX.AppCompat.AppCompatResources to 1.5.1.1

**Comment by pulmuone** [comment]
> A workaround that so far works for me was to build a custom binding library and add missing (renamed) classes back and repacking this in custom local nuget.
> 
> Basically this: https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources/blob/master/Xamarin.AndroidX.AppCompat.AppCompatResources/Additions/DrawableContainer.cs)
> 
> And this: https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources/blob/master/Xamarin.AndroidX.AppCompat.AppCompatResources/Additions/DrawableWrapper.cs
> 
> See this repo: https://github.com/sasa-bobic/Xamarin.AndroidX.AppCompat.AppCompatResources

Thank you. 
I solved it with this content.

**Comment by MagicAndre1981** [comment]
> Thank you. I solved it with this content.

why? Simply use the official [XF SR15](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr15)

**Comment by pulmuone** [comment]
> > Thank you. I solved it with this content.
> 
> why? Simply use the official [XF SR15](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr15)

Maui (.net7) Android AOT Compile Error.
https://github.com/xamarin/xamarin-android/issues/8252#issuecomment-1677395907

**Comment by MagicAndre1981** [comment]
ok, this topic is about Xamarin Forms, so it was not clear that you use MAUI
