### ISSUE TITLE
[Enhancement] Provide template support for tabbar in Xamarin Forms shell platform

### ISSUE THREAD

**Issue by Arunachalam3641** [xamarin/Xamarin.Forms#15662]
Currently, there is only support for adding icons and titles. if template support is given it will be easy to add any customization inside the tab bar.

**Comment by jfversluis** [comment]
Thanks for the suggestion! As Xamarin.Forms is end-of-life, we're not going to add any new functionality to it anymore. If this is something that is important to you, please check if this has already been proposed for .NET MAUI.
