### ISSUE TITLE
[Bug] Unable to use 1.6/1.7 of Xamarin Android Material Design

### ISSUE THREAD

**Issue by haavamoa** [xamarin/Xamarin.Forms#15677]
### Description
[Xamarin.Forms has Android Material Design 1.5](https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/.nuspec/Xamarin.Forms.nuspec) as highest version number its compatible with. This means that we can not benefit from the latest version of Material Design in our Xamarin Forms apps.

### Steps to Reproduce

1. Create a Xam Forms app
2. Head over to nuget manager and try to add Xamarin Material Design version 1.6 / 1.7.
3. Observer error saying that we have to downgrade due to latest Xam Forms dependency.

### Expected Behavior
Be able to benefit the awesome changes from Android Material Design latest versions. 

### Actual behavior

Not able to benefit the awesome changes from Android Material Design latest versions. 

### Basic Information

- Version with issue: 5.0.2515
- Last known good version: None
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by LennoxP90** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/15678
https://github.com/xamarin/Xamarin.Forms/issues/15668

looks like XF is behind.
