### ISSUE TITLE
ViewCell with Grid incorrectly calculates size for last column if it is using Width="*"

### ISSUE THREAD

**Issue by aleksvu** [xamarin/Xamarin.Forms#1568]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
The last column in grid doesn't utilize all not used screen space when used in list view
### Steps to Reproduce

1. Create sample page: 
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ListViewCellBug"
             x:Class="ListViewCellBug.MainPage">
    <AbsoluteLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <ListView
            RowHeight="80"
            HasUnevenRows="False"
            SeparatorVisibility="None"
            SeparatorColor="Transparent"
            ItemsSource="{Binding BugItems}"
            CachingStrategy="RecycleElement"
            HorizontalOptions="FillAndExpand"
            VerticalOptions="FillAndExpand">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <local:GridViewCell/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </AbsoluteLayout>
</ContentPage>
```
2. Create view cell:
```<?xml version="1.0" encoding="UTF-8"?>
<ViewCell xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ListViewCellBug.GridViewCell">
    <Grid x:Name="CallInfoCell" RowSpacing="0" ColumnSpacing="0">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="14"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="28"/>
            <RowDefinition Height="20"/>
        </Grid.RowDefinitions>

        <Label
            Grid.Column="0" 
            Grid.ColumnSpan="2"
            Text="{Binding BugText}"
            LineBreakMode="TailTruncation"
            HorizontalTextAlignment="Start"
            VerticalOptions="Start"
            HorizontalOptions="StartAndExpand"
            Margin="0, 0, 8, 0"/>

        <Image
            Grid.Row="1"
            Grid.Column="0"
            Aspect="AspectFit"
            HeightRequest="14"
            WidthRequest="14"
            Source="icon.png"/>
        <Label
            Grid.Row="1"
            Grid.Column="1"
            Grid.ColumnSpan="2"
            HorizontalTextAlignment="Start"
            Margin="8, 0, 8, 0"
            Text="Moderate text"/>

    </Grid>

</ViewCell>
```
3. View model for page is:
```
public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = new ViewModel();
        }

    }

    class ViewModel
    {
        public enum CallLogListState
        {
            Loading,
            Empty,
            AccessDenied,
            Ready
        }

        ObservableCollection<Item> _items = new ObservableCollection<Item>();
        public ObservableCollection<Item> BugItems
        {
            get
            {
                return _items;
            }
        }

        public ViewModel()
        {
            for(int i = 0; i < 7; i++)
            {
                _items.Add(new Item());
            }

            //if you do not do text change bug will not reproduce
            Task.Run(() =>
           {
               Task.Delay(1000);
               _items[5].BugText = "A very very long long long text in this item, that exceedes screen width";
           });
        }
    }

    class Item : INotifyPropertyChanged
    {
        string _text = "Short text"; //first text must be rather short
        public string BugText
        {
            get
            {
                return _text;
            }

            set
            {
                _text = value;
                PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(BugText)));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }
```

### Expected Behavior
Text supplied with property BugText is truncated at the end of the phone screen

### Actual Behavior
Text is truncated somewhere in the middle of the screen. Perfectly visible in Huawei Nexus 6P
Changing "*" to "Auto" solves the problem but reduces perfomance on scrolling.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: Visual Studio 2017 15.5.1
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: any supported starting from 25.4.0.2

**Comment by davidortinau** [comment]
@aleksvu you have a `ColumnSpan="2"` on the last `Label` that begins in the 2nd column, which would make for 3 columns though you have only 2 defined. If you remove that, the layout with "star" behaves as I think we'd expect.

I simplified the reproduction to just a `<Grid />` and boxes since the list and bindings aren't related.

Expected: the blue box should go all the way to the right edge of the gray box.

<img width="614" alt="screenshot 2018-01-12 16 49 12" src="https://user-images.githubusercontent.com/41873/34898571-62394aca-f7b9-11e7-96f8-b20327b1a507.png">

This is with the last span removed:

<img width="614" alt="screenshot 2018-01-12 16 57 25" src="https://user-images.githubusercontent.com/41873/34898727-2b57d4ee-f7ba-11e7-972d-fd4c70b3d8b3.png">

So, confirming we have something here to look at, but I don't think it's quite what was original described.

Project:

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1627759/Archive.zip)

**Comment by aleksvu** [comment]
@davidortinau Sorry, have misprinted while simplyfing our real code to bug sample.

Actually what you have described is the other bug. My issue works with labels with dynamic text. When the cell data is first loaded it looks like this ("!" and "=" are the borders of the view cell in list, "|" and "-" are for grid cells)
```

===============================
!S|hort text    |             !
!------------------------------
!x| Short text|               !
===============================

```
Then after data is loaded we change text in the firs cell into a much longer one. The behavior we recieve is this:
```
===============================
!A| very very |               !
!------------------------------
!x| Short text|               !
===============================
```
But expected behavior is this:
```
===============================
!A|very very long text here...!
!------------------------------
!x| Short text               |!
===============================

```
In android terms it would be translated as Grid has "wrap_content" option for width, not "match_parent" as for others markups. That's why changing "*" to "Auto" for the last column solves the issue and decreases perfomance - the size of that column simply recalculated.
It is also interesting, that if you add more rows in grid the size of the row with changing texts (in our case the first) sometimes will be calculated for truncation given the length of the text of the last row, like this:
```
===============================
!A| very v.|                  !
!------------------------------
!x| Some longer text|         !
-------------------------------
!Short text|                  !
===============================
```

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
