### ISSUE TITLE
[Bug] label in XAML with TextType="HTML" and binding in viewmodel, not working

### ISSUE THREAD

**Issue by tobih5m** [xamarin/Xamarin.Forms#15695]
### Steps to Reproduce

1. create label in XAML <Label TextType="HTML" Text="{Binding prop}" />
2. create property in viewmodel `prop = "<u>underline</u>"`

### Expected Behavior
underlined text in label
### Actual Behavior
normal text, no html code working with bindings
### Basic Information
- Version with issue: 5.x
- Devices: Emulator with Android 8.1, Real Device with Android 10

**Comment by tobih5m** [comment]
Solution found: don't use TextColor in XAML or use binding with a converter

**Comment by Kol-UI** [comment]
Maybe you could use TextDecorations="Underline" in you Label, with a binding on a bool in you ViewModel. That way TextColor can still be used
