### ISSUE TITLE
🙋🏽‍♀️ [Survey] GitHub contributor experience

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#15690]
### Xamarin.Forms Community! We want to hear from YOU! 

We're asking you to let us know how we're doing as maintainers. Fill out the survey in the link below and tell us what you think.

Whether you've been involved for years or you're relatively new, please tell us about your experience participating and contributing to the project. It should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8KTX9VT?Source=xamarin/Xamarin.Forms

**Comment by jtorvald** [comment]
I don't want to be a pain, but it would really help to get bugs fixed, PR's merged and service releases out of the door if we want Xamarin Forms and Maui to be a success.

**Comment by jfversluis** [comment]
@jtorvald for .NET MAUI service releases are going out very regularly and lots of PRs are merged.

For Forms we have slowed down a bit to not have too many small service releases. If you have any PRs that you want to contribute, I'm happy to have a look and I will see if I can release a service release shortly. Thanks!

**Comment by jtorvald** [comment]
@jfversluis thanks for you quick reply. I wrote to you earlier about https://github.com/xamarin/Xamarin.Forms/pull/15638 (it's already merged) but maybe it ended up in your spam or something (you normally reply very quick, thanks).
Do you think Maui is mature enough now to migrate production apps to? I notice so many Forms libraries not being maintained and the whole experience is working around bugs. Maybe I should just try a migration to Maui if that is more stable?

**Comment by LennoxP90** [comment]
we need a service release to support the latest AndroidX nugets
https://github.com/xamarin/Xamarin.Forms/issues/15668
