### ISSUE TITLE
Add the RadioButtonRenderer on iOS again

### ISSUE THREAD

**Issue by ElRafeta697** [xamarin/Xamarin.Forms#15706]
A few years ago, you added a RadioButtonRenderer for iOS. Since version 5.0, this renderer was removed, difficulting the rendering of this control on iOS. Why you did this? Xamaron Forms RadioButton works very good and it's so easy to understand, which it makes perfect for most of the projects

**Comment by jfversluis** [comment]
I'm afraid I don't understand. The `RadioButton` and therefore also the `RadioButtonRenderer` is still available in the current version of Xamarin.Forms.

**Comment by ElRafeta697** [comment]
I'm talking about the specific iOS renderer

![image](https://user-images.githubusercontent.com/45845703/223682162-e97fdbb9-132e-4ece-9a3d-547fb6ac5e18.png)

Android hasn't this problem
![image](https://user-images.githubusercontent.com/45845703/223681915-865ef189-6ad8-476e-b9ff-6bf777c0f4dc.png)

I'm using Xamarin Forms 5.0.0.2401
