### ISSUE TITLE
XAML Image doesn't show image

### ISSUE THREAD

**Issue by gpsaliola** [xamarin/Xamarin.Forms#15715]
### Description
I've a XAML Image with Source = "https://tile.openstreetmap.org/12/2191/1521.png".
The image it's not show.

### Steps to Reproduce
```
<Image 
    Source="https://tile.openstreetmap.org/12/2191/1521.png"
/>
```
 In the browser the image was shown.
Try: https://tile.openstreetmap.org/12/2191/1521.png

Thank you.

**Comment by jfversluis** [comment]
Thanks for the report! Unfortunately without any additional information this is pretty hard to diagnose. The issue template is there to capture this information: on which platform are you seeing this, what versions? What did you try?

Without this information we don't really have an actionable issue here, sorry.
