### ISSUE TITLE
[Enhancement] Upgrade AndroidTargetFramework from MonoAndroid10.0 to 12 or 13

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#15714]
To fix #15668 and use newer [AndroidX libs you need to target at least MonoAndroid12.0](https://github.com/xamarin/AndroidX/issues/444) and currently you only [target 10.0](https://github.com/xamarin/Xamarin.Forms/blob/076623b1942c1244ecf05757f2810cd4bbec6eca/Environment.Build.props#L37)

Please do this and fix #15668 before you end the XF support.

**Comment by jfversluis** [comment]
I've seen the questions around this. I'm seeing internally what we can do. Thanks!
