### ISSUE TITLE
TitleIcon Aspect Ratio not maintained on iPhone X MasterDetail in Landscape 

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#1572]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
The aspect ratio of the image used as the TitleIcon is not maintained on the iPhone X when rotation to landscape, it is stretched lengthwise.  The image is not stretched on other versions of the iPhone.
### Steps to Reproduce

1. run the attached project on the iPhoneX in landscape
2. 
3. 

### Expected Behavior
The image height and width should shrink to maintain the aspect ratio
### Actual Behavior
The height is reduced by a higher percentage than the width
### Basic Information

- Version with issue:
- Last known good version: none
- IDE: VS2017
- Platform Target Frameworks:
- Forms: 2.5.0

  - iOS:  11.2
- Nuget Packages:
- Affected Devices:

### Screenshots
IPhone 8:
![iphone8_landscape](https://user-images.githubusercontent.com/1641428/34895749-0a5bc2f0-f7b5-11e7-9ab9-026e17ee3713.png)

iPhone X:
![iphonex_landscape](https://user-images.githubusercontent.com/1641428/34895743-055baba8-f7b5-11e7-95eb-f48320d4b406.png)

### Reproduction Link

[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1627617/HeaderTest.zip)

**Comment by davidortinau** [comment]
Confirmed. I'm able to reproduce it. This is also confirmed on 2.6.0.86516-nightly.

.NET Standard with nightly build attached.

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1627679/Archive.zip)

Image showing a properly scale overlay for reference.
![screenshot-2018-01-12-16 07 49](https://user-images.githubusercontent.com/41873/34897690-fda1b2ea-f7b4-11e7-851c-136c0e6e7342.png)

**Comment by samhouts** [comment]
I'm going to close this for now and recommend that you try the TitleView instead, which should now offer greater control of images. Thanks!

**Comment by ceblanda** [comment]
Thanks.  I've bee testing TitleView but I have two concerns with that solution.  First, the images aren't resizing to fit the container.  If I give them a width or height request they will, but just defining the container and setting the aspect doesn't.  Second, it only appears to work for FormsAppCompactActivities.  Due to other issues with AppCompact we are stull using FormsApplicationActivity.

**Comment by samhouts** [comment]
I'm sorry to  hear that the image resizing isn't much better in TitleView. We'll take a look at that when we work on TitleView in the near future. 

As far as your issues upgrading to AppCompat--yikes! I'd love to get a full list of everything that is holding you back. Would you mind opening an issue just for that discussion? I'd love to get you started on AppCompat as soon as possible! 

Thanks!

**Comment by ceblanda** [comment]
Using Xamarin Essentials I am able to set the image width to a percentage of the deice width, which appears to be a good workaround.  The main issue keeping us from AppCompat is #2577 - the hamburger icon does not display on a navigated-to page.  If that could be addressed we are ready to make the move.

**Comment by samhouts** [comment]
Great! I'll mark it as high priority and try to get it prioritized. Thank you!
