### ISSUE TITLE
[Bug] RequiredStringValidationBehavior stays invalid when it should be valid

### ISSUE THREAD

**Issue by CostasAthan** [xamarin/Xamarin.Forms#15721]
### Description
RequiredStringValidationBehavior stays always invalid

### Steps to Reproduce

```
StackLayout myLayout = new StackLayout
{ 
    Children =
    {
        new Entry(),

        new Entry(),
                   
        new Entry()
    }
};

myLayout.Children.OfType<Entry>().ElementAt(2).Behaviors.Add
(
     new RequiredStringValidationBehavior
      {
           RequiredString = myLayout.Children.OfType<Entry>().ElementAt(1).Text,
           InvalidStyle = invalidEntryStyle,
           Flags = ValidationFlags.ValidateOnValueChanging
      }
);
```

1. Run the aforementioned code.
2. Enter the same strings in both the second and the third Entries.

### Expected Behavior

When both Entries have the same input the RequiredStringValidationBehavior should be valid.

### Actual Behavior

The RequiredStringValidationBehavior stays invalid

### Basic Information

- Version with issue: Xamarin.Forms 5.0.0.2578

</details>

**Comment by jfversluis** [comment]
The `RequiredStringValidationBehavior` is something that is not in Xamarin.Forms but the [Xamarin Community Toolkit](https://github.com/xamarin/XamarinCommunityToolkit/). Please report the issue there. Thanks!
