### ISSUE TITLE
GetTasksAbi task could not be loaded in 2.5.0

### ISSUE THREAD

**Issue by owlstack** [xamarin/Xamarin.Forms#1573]
### Steps to Reproduce

1. Upgrade Xamarin.Forms project from 2.4.0.282 to 2.5.0.122 (With .NET standard 1.4 for shared logic class) 
2. Build solution with device connected (in my case UWP device)
3. Get the error 

Oddly, it happens frequently intermittently-- that is, it happens and then I try to build my solution again by clicking on the run button several times. After several times, my solution builds just fine but I still get the error. 

### Expected Behavior
No error and I can run my app just fine 

### Actual Behavior

Error: 

> The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\parallels\.nuget\packages\xamarin.forms\2.5.0.122203\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

And I can't build my solution. 

### Basic Information

- Version with issue: 2.5.0.122
- Last known good version: 2.4.0 (not sure about "last" but this is the version I upgraded from)
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - UWP: 10.0.14393.0
- Nuget Packages: Xamarin.Forms 2.5.0.122, Xamarin 4.8.0
- Affected Devices:
UWP Windows 10 device

**Comment by StephaneDelcroix** [comment]
here's some thought:
- you might depend on different versions of XF for different projects in your solution
- this can happen when switching branches/version of XF without restarting your IDE
- this usually goes away by doing a full clean (clean projects + clean all build artifacts, obj/ bin/, ...). I usually achieve this by doing a `git clean -xfd` (make sure you have no pending changes to commit before doing that)

**Comment by owlstack** [comment]
@StephaneDelcroix I tried to do a clean and rebuild but I still get the same issue and I restarted my IDE as well. I haven't tried deleting the obj and bin files yet. I will give that a try and let you know. 

Should I try the git clean command? Just curious why version control would affect this? Thanks!

**Comment by PureWeen** [comment]
@owlstack.   did you get this resolved?  The  git command Stephane referenced is just a way to clean out your working directory. So it's just a way to leverage git to make sure you don't have any weird artifacts causing issues. That command will delete out your bin/obj and any "compiler" generated files.

**Comment by owlstack** [comment]
@StephaneDelcroix @PureWeen I was able to get this issue resolved. You can close the issue. 

The issue I had was I have upgraded only two projects in my solution when I should have upgraded all projects to the same Xamarin.Forms version as suggested by Stephane.
