### ISSUE TITLE
xamarin forms CollectionView scroll issue

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15735]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/xamarin-forms-CollectionView-scroll-issu/10345963)._

---
[severity:I'm unable to use this version]
Xamarin forms CollectionView scroll issue on ios
please check the video link

https://app.box.com/s/p030wznpqzmf9irhyogtc2vfkqlrlpbj

visual studio edition: 2022
version: 17:5:3
Thanks

---
#### Feedback Bot on 4/22/2023, 07:09 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Without any relevant code or, ideally, a reproduction project it is near impossible to diagnose and potentially fix what might be going on here. If this is still important to you, please open a new issue with all the information requested by the bug template, including code that is used to make up your CollectionView, preferably in a standalone reproduction GitHub repository. Thanks!
