### ISSUE TITLE
VS 17.5.5 - SignTool Error: The /p option requires the /f option

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15750]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-1755---SignTool-Error:-The-p-optio/10356337)._

---
[severity:It's more difficult to complete my work]
Since a few versions ago, UWP publishing started failing for me with this error while trying to publish a package.
There was no configuration changes to this Xamarin Forms projects and all nugets are totally up to date.

I have another machine with 17.4.2 that I specifically don't update because of this issue.
So every time I release UWP on that machine, but today decided to reach out for help. :)

---
#### Feedback Bot on 5/5/2023, 07:15 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by LumberCoder** [comment]
I have the same issue with our Xamarin Forms uwp app.
the UWP nuget version is latest stable 6.2.14
Xamarin Forms nuget version 5.0.0.2545

**Comment by LumberCoder** [comment]
I used Publish -> create app packages on the UWP app, selected sideloading as my distribution method and chose my signing method (an existing certificate).
On the Select and configure packages page:
-  I used my normal output location, 
- allowed the app to automatically increment the version,
- Generate app bundle was set to Always
- x86 and x64 for packages to create

You are probably right that this isn't a xamarin forms issue, but this was the only report of this issue/error message that I could find online, so I thought I'd contribute

**Comment by EmilAlipiev** [comment]
this is also happening in Azure Pipelines now. Probably something to do with the VS2022 windows

**Comment by EmilAlipiev** [comment]
it is for sure VS2022 issue and related to this one https://developercommunity.visualstudio.com/t/-SignTool-Error:-The-p-option-requires-/10307294

**Comment by jfversluis** [comment]
Thanks @EmilAlipiev ! Looks like that issue is still open and even says a fix is pending release. Seems we're done here on this side.
