### ISSUE TITLE
When We set 'contenteditable=false inside contenteditable=true block' the contenteditable=false not working properly on UWP platform

### ISSUE THREAD

**Issue by HemalathaDuraisamy** [xamarin/Xamarin.Forms#15758]
When We set 'contenteditable=true as parent and contenteditable=false as child element' the contenteditable=false not working properly on UWP platform. Its able to edit the content on child element.

### Steps to Reproduce

1. Run the attached sample
2. Click and type the second line ( I have set contenteditable=false )
3. The text will be added in the second line

### Expected Behavior
When focus on the child block and type the text, but do not add it.

### Actual Behavior
When focus on the child block and type the text, the text will be added.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: UWP platform

Simple sample link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Hybrid667048676

We created a video for illustrating the same and it can be downloaded from the below links,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/UWP-450515621

**Comment by jfversluis** [comment]
I would think that this also happens when you create a UWP app without Xamarin.Forms and thus this is probably a bug with them. Please confirm if this also happens in a UWP app without using Xamarin.Forms.

In either case, I'm not sure if this will be fixed still during the lifetime of Xamarin.Forms that is left.

**Comment by HemalathaDuraisamy** [comment]
We are able to reproduce the same issue "When We set 'contenteditable=false inside contenteditable=true block' the contenteditable=false not working properly on UWP platform" on UWP app without using Xamarin Forms. Kindly ensure and provide suggestions for resolving the issue.

UWP sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/WebviewSample1037629117

**Comment by jfversluis** [comment]
In that case you probably want to check with them as this is not something that we can do anything about. Assuming that UWP uses the WebView2 component, you might want to try this repository: https://github.com/MicrosoftEdge/WebView2Feedback

**Comment by ghost** [comment]
We reported the issue with Webview2, but the Webview2 team stated that it was not related to our side. However, the issue was replicated on the Xamarin hybrid WebView UWP platform and the UWP app without Xamarin Forms. Can you please provide suggestions on how to resolve the issue?
