### ISSUE TITLE
Mobile App (Xamarin Forms) Project : IOS LaunchingScreen Cannot Show Correctly

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15759]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Mobile-App-Xamarin-Forms-Project-:-IOS/10382538)._

---
I am creating app with _Mobile App (Xamarin Forms)_ for android and ios.  When debugging for ios, i came across these issues:
1. When debugging with iphone device( iphone 11), it's app icon and launching screen did not change no matter what changes i did in _Asset Catalogs_ and _LaunchScreen.storyboard_ , which showing as :
![Icon60.png](https://aka.ms/dc/image?name=B877a3fc0e661494293884849e79d6659638212896530894910_20230602-160050-Icon60.png&tid=877a3fc0e661494293884849e79d6659638212896530894910)
![Default.png](https://aka.ms/dc/image?name=B8efafa7a982e4d7d8dea4e712c550727638212895746645268_20230602-155931-Default.png&tid=8efafa7a982e4d7d8dea4e712c550727638212895746645268)
2. When debugging with simulator iphone 14 ios 16.4, app icon will changed together with Asset _Catalogs.Assets.AppIcon_, but launching screen will always be black sceen.
3.IOS project created with _Mobile App (Xamarin Forms)_ selection is much different from it created with _IOS App(Xamarin)_ selection in template window. 
no selection in dropdown
![1685693305713.jpg](https://aka.ms/dc/image?name=B23089d1ad204442d9509d80a1beb023f638212901108246719_20230602-160828-1685693305713.jpg&tid=23089d1ad204442d9509d80a1beb023f638212901108246719)
no .xib file in _Resource_

App worked well except for launching screen showing.

---
#### Feedback Bot on 6/2/2023, 01:24 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Looking at the screenshots it seems you might be using Hot Restart. One of the limitations is that you cannot change the icons or launch screen as documented here: https://learn.microsoft.com/xamarin/xamarin-forms/deploy-test/hot-restart#limitations

Try it through a connected Mac and see if the problem is resolved then. If not, please open a new issue. Thanks!
