### ISSUE TITLE
[Bug] Next button on iPhone keyboard with text entries in a List.

### ISSUE THREAD

**Issue by pkvaranasi** [xamarin/Xamarin.Forms#15771]
### Description
Next button in the keyboard on iPhones.
### Steps to Reproduce

1. Any Xamarin Forms application installed on iPhone, with many text entries in the ListView.
2. Any Xamarin Forms application installed on iPhone, with many text entries in the CollectionView.

### Expected Behavior
Like Android keyboard, having a Next button in the keyboard on iPhone, in Xamarin Forms apps, to shift the focus from one entry to the next entry in the list.
### Actual Behavior
No Next button available in the default iPhone keyboard to navigate the focus from one text entry to the next entry in the list.
### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  11.1 
  - Android:  13.1
- NuGet Packages:
- Affected Devices: All iPhones

### Environment

All Environments

### Build Logs

No issues with builds
-->

**Comment by jfversluis** [comment]
You can set `ReturnType="Next"` on the `Entry`, I hope that this doesn't only show it visually but will also allow you to hop to the next Entry. If not, [here is some code](https://gist.github.com/MysterDru/fd0f4f0531365b0ab83ad6760d84caf0) that might be able to help you with that.

Unfortunately at this point in the Xamarin.Forms lifecycle we won't be implementing anything new to support this. You should be able to make this work yourself with a plugin or custom renderer.
