### ISSUE TITLE
When We set 'contenteditable=false inside contenteditable=true block' the contenteditable=false not working properly on UWP platform

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#15770]
We reported the issue with Webview2, but the Webview2 team stated that it was not related to our side. However, the issue was replicated on the Xamarin hybrid WebView UWP platform and the UWP app without Xamarin Forms. Can you please provide suggestions on how to resolve the issue?

_Originally posted by @HemalathaDuraisamy in https://github.com/xamarin/Xamarin.Forms/issues/15758

**Comment by jfversluis** [comment]
You should ask the WebView2 team unfortunately there is nothing we can do on our side about this.
