### ISSUE TITLE
[Bug] Application Crashes When Re-entering a Page Containing a WebView After Navigating Back on Android 13 using Xamarin.Forms V5.0.0.2578

### ISSUE THREAD

**Issue by BrickBios** [xamarin/Xamarin.Forms#15778]
Description
Application Crashes When Re-entering a Page Containing a WebView After Navigating Back on Android 13 using Xamarin.Forms V5.0.0.2578

Steps to Reproduce
Open the activity containing the WebView.
Navigate back using the back button.
Try to re-enter the page containing the WebView.

Expected Behavior
The WebView should open without any issues when attempting to open it multiple times.
Unhandled Exception: Android.Views.InflateException (EXCEPTIONDISPATCHINFO
[error.txt](https://github.com/xamarin/Xamarin.Forms/files/12063462/error.txt)
)

Actual Behavior
The WebView throws an error when opened for the second time.

Basic Information
Visual Studio 2022 version version 17.6
Version with issue: Xamarin.Forms : V5 .0.0.2578, Visual.Material : V5.0.0.2578

Platform Target Frameworks:
Android: Android 13
Android: Android 12
Android: Android 11

**Comment by jfversluis** [comment]
Without any reproduction project or at the very least relevant code this will be very hard to diagnose.
