### ISSUE TITLE
[UWP] Intermittently keyboard pushes part of the view up outside of device screen

### ISSUE THREAD

**Issue by owlstack** [xamarin/Xamarin.Forms#1577]
### Description

I noticed this happen intermittently across my application across several screens. When I focus inside an Entry and the keyboard pops up, it forces some of the screen out of the device screen view. However, this behavior is really hard to reproduce consistently but I notice it happen from time to time. 

### Steps to Reproduce

1. Create a page with an entry near the top of the page
2. Focus/click on the Entry and wait for keyboard to pop up 
3. Intermittently, the keyboard pushes the top of the page outside the device screen area. 

### Expected Behavior

Page and it's element should remain fixed on the device screen and should not be moved up because of the keyboard. 

### Actual Behavior

Keyboard pushes page up outside the device screen area. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - UWP:   10.0.14393.0
- Nuget Packages:
Xamarin.Forms: 2.4.0.282
- Affected Devices:
Panasonic fZ-E1

I recently however upgraded to the latest Xamarin.Forms version 2.5.0.122 but haven't gotten the chance to test if it still occurs with the latest. I'm wondering if something like this has been reported before and is known to be fixed in latest or not?

**Comment by StephaneDelcroix** [comment]
- does it happens only on that Panasonic device ?
- could you please attach a minimal project showcasing your issue ?
- you should also definitely try the latest version on that small reproduction project, and report.

Thanks

**Comment by owlstack** [comment]
@StephaneDelcroix I got the latest version 2.5.0.122 and did some testing last night and I can reproduce it on the latest version. I don't have any other devices to test it on. Maybe I can test it on the simulator then? I'll see if I can add a sample project later this week.

**Comment by samhouts** [comment]
@owlstack Were you able to put together a sample project? Thanks

**Comment by hartez** [comment]
Closing this for now (no response). Feel free to reopen it if new information comes to light.
