### ISSUE TITLE
HttpClient does not respect Timeout after setting the timeout.

### ISSUE THREAD

**Issue by anshumanhcl** [xamarin/Xamarin.Forms#15772]
### Description
I have set the http timeout to 4 seconds , but its takes more time always as 10 secs to 15 secs .
### Steps to Reproduce

1.Create a HttpClient and set Timeout to a value to 4 sec ( the default value).
2.Send a request that takes longer than 4sec but less than the Timeout set.

### Expected Behaviorive the 
The request to return successfully

### Actual Behavior
The request times out after 4sec.

### Basic Information

- Visual Studio Community 2022 for Mac
Version 17.6 (build 1575)

Runtime
.NET 7.0.3 (64-bit)
Architecture: X64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (x64)
SDK: /usr/local/share/dotnet/sdk/7.0.304/Sdks
SDK Versions:
	7.0.304
	6.0.410
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (x64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.7
	6.0.18

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/anshuman_tiwari/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 33.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-06-14 17:06:06 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-06-14 17:06:06 UTC

Apple Developer Tools
Xcode: 14.3.1 21815
Build: 14E300c

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-06-14 17:06:02 UTC

Build Information
Release ID: 1706001575
Git revision: d32bcc352feed2f1f54e237e23e5c375d86eaf9e
Build date: 2023-06-14 17:04:22+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.4.1
Darwin 22.5.0 Darwin Kernel Version 22.5.0
    Thu Jun  8 22:22:22 PDT 2023
    root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64

- Affected Devices: **Android and IOS**

**Comment by jfversluis** [comment]
I highly doubt this is an issue with Xamarin.Forms, if anything this is something in the Mono runtime. Without any reproduction or relevant code it will be impossible to say anything useful unfortunately.

Closing this here for now.
