### ISSUE TITLE
Xamarin forms app takes forever to deploy in android

### ISSUE THREAD

**Issue by PoorneshEcolab** [xamarin/Xamarin.Forms#15777]
### Description
When Xamarin forms app is deployed to android device it builds successfully but doesn't deploy, gets stuck while installing package.

Solutions tried:
Tried deploying to multiple android devices, but still fails.
Uninstalled and reinstalled Visual studio
Updated all nuget packages, tried with sample project, but still fails.
Few threads suggested to enable/disable multi dex and Fast deployment from Android build setting. But still no luck.

### Steps to Reproduce

1. With the latest version of Visual Studio, deploy any sample app on Android phone

### Expected Behavior
The App should be deployed quickly.

### Basic Information

Visual Studio Community 2022 for Mac
Version 17.6 (build 1575)
Installation UUID: c936688e-dca7-410b-ab4b-ca0e552d985e

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.304/Sdks
SDK Versions:
	7.0.304
	7.0.203
	7.0.202
	6.0.410
	6.0.408
	6.0.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.7
	7.0.5
	7.0.4
	6.0.18
	6.0.16
	6.0.15

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.3.1 21815
Build: 14E300c

Xamarin.Mac
Version: 9.3.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:35-0400

Xamarin.iOS
Version: 16.4.0.6 Visual Studio Community
Hash: 97731c92c
Branch: xcode14.3
Build date: 2023-04-11 22:38:36-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-06-14 17:05:55 UTC

Xamarin.Android
Version: 13.2.0.6 (Visual Studio Community)
Commit: xamarin-android/d17-5/a200af1
Android SDK: /Users/VPO1/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.1 (API level 32)
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-06-14 17:06:00 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-06-14 17:06:00 UTC

Build Information
Release ID: 1706001575
Git revision: d32bcc352feed2f1f54e237e23e5c375d86eaf9e
Build date: 2023-06-14 17:04:07+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 13.2.1
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Mon Jan 30 20:38:37 PST 2023
    root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

### Environment

When deployed on android using Visual studio for mac

### Build Logs

Build started 11-07-2023 16:59:38.
__________________________________________________
Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" (Install target(s)):

Target _ResolveAndroidTooling:
    Found Java SDK version 11.0.16.1.
    Found Java SDK version 11.0.16.1.
Target _CheckInstantRunCondition:
    Dex Fast Deployment Enabled: False
Target _ResolveMonoAndroidSdks:
    MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
    Android Platform API level: 33
    TargetFrameworkVersion: v13.0
    Android NDK: 
    Android SDK: /Users/VPO1/Library/Developer/Xamarin/android-sdk-macosx/
    Android SDK Build Tools: /Users/VPO1/Library/Developer/Xamarin/android-sdk-macosx/build-tools/32.0.0/
    Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/
    Application Java class: android.app.Application
Build started 11-07-2023 16:59:38.
__________________________________________________
Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" (Install target(s)):

Target _ResolveAndroidTooling:
    Found Java SDK version 11.0.16.1.
    Found Java SDK version 11.0.16.1.
Target _CheckInstantRunCondition:
    Dex Fast Deployment Enabled: False
Target _ResolveMonoAndroidSdks:
    MonoAndroid Tools: /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/
    Android Platform API level: 33
    TargetFrameworkVersion: v13.0
    Android NDK: 
    Android SDK: /Users/VPO1/Library/Developer/Xamarin/android-sdk-macosx/
    Android SDK Build Tools: /Users/VPO1/Library/Developer/Xamarin/android-sdk-macosx/build-tools/32.0.0/
    Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/
    Application Java class: android.app.Application
Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetTargetFrameworks target(s)):

Target ResolveProjectReferences:
    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetNativeManifest target(s)):

Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetTargetFrameworks target(s)):

Target ResolveProjectReferences:
    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetTargetPath target(s)):

    __________________________________________________
    Project "/Users/VPO1/Projects/Test/Test/Test.Android/Test.Android.csproj" is building "/Users/VPO1/Projects/Test/Test/Test/Test.csproj" (GetNativeManifest target(s)):

Target _ResolveLibraryProjectImports:
  Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.
Target _BuildLibraryImportsCache:
  Skipping target "_BuildLibraryImportsCache" because all output files are up-to-date with respect to the input files.
Target _GenerateLayoutBindings:
  Skipping target "_GenerateLayoutBindings" because it has no outputs.
Target _ConvertResourcesCases:
  Skipping target "_ConvertResourcesCases" because all output files are up-to-date with respect to the input files.
Target _CompileResources:
  Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
Target _PrepareUpdateAndroidResgen:
  Skipping target "_PrepareUpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Target _UpdateAndroidResgen:
  Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Target _ResolveLibraryProjectImports:
  Skipping target "_ResolveLibraryProjectImports" because all output files are up-to-date with respect to the input files.
Target _BuildLibraryImportsCache:
  Skipping target "_BuildLibraryImportsCache" because all output files are up-to-date with respect to the input files.
Target _GenerateLayoutBindings:
  Skipping target "_GenerateLayoutBindings" because it has no outputs.
Target _ConvertResourcesCases:
  Skipping target "_ConvertResourcesCases" because all output files are up-to-date with respect to the input files.
Target _CompileResources:
  Skipping target "_CompileResources" because all output files are up-to-date with respect to the input files.
Target _PrepareUpdateAndroidResgen:
  Skipping target "_PrepareUpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Target _UpdateAndroidResgen:
  Skipping target "_UpdateAndroidResgen" because all output files are up-to-date with respect to the input files.
Target _ResolveAssemblies:
      Adding assembly reference for Test.Android, recursively...
      Adding assembly reference for System.Net.Http, recursively...
      Adding assembly reference for System.Runtime.Serialization, recursively...
        Adding assembly reference for System.ServiceModel.Internals, recursively...
      Adding assembly reference for FormsViewGroup, recursively...
      Adding assembly reference for Java.Interop, recursively...
      Adding assembly reference for Mono.Android, recursively...
        Adding assembly reference for System.Drawing.Common, recursively...
      Adding assembly reference for mscorlib, recursively...
      Adding assembly reference for System.Core, recursively...
      Adding assembly reference for System, recursively...
        Adding assembly reference for Mono.Security, recursively...
      Adding assembly reference for System.Numerics, recursively...
      Adding assembly reference for System.Numerics.Vectors, recursively...
      Adding assembly reference for System.Runtime, recursively...
        Adding assembly reference for System.ComponentModel.Composition, recursively...
      Adding assembly reference for System.Xml, recursively...
      Adding assembly reference for System.Xml.Linq, recursively...
      Adding assembly reference for Test, recursively...
        Adding assembly reference for netstandard, recursively...
          Adding assembly reference for System.Data, recursively...
            Adding assembly reference for System.Transactions, recursively...
          Adding assembly reference for System.Data.DataSetExtensions, recursively...
          Adding assembly reference for System.IO.Compression, recursively...
          Adding assembly reference for System.IO.Compression.FileSystem, recursively...
          Adding assembly reference for System.Web.Services, recursively...
      Adding assembly reference for Xamarin.AndroidX.Activity, recursively...
      Adding assembly reference for Xamarin.AndroidX.Annotation, recursively...
      Adding assembly reference for Xamarin.AndroidX.Annotation.Experimental, recursively...
      Adding assembly reference for Xamarin.AndroidX.AppCompat.AppCompatResources, recursively...
      Adding assembly reference for Xamarin.AndroidX.AppCompat, recursively...
      Adding assembly reference for Xamarin.AndroidX.Arch.Core.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Arch.Core.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.AsyncLayoutInflater, recursively...
      Adding assembly reference for Xamarin.AndroidX.Browser, recursively...
      Adding assembly reference for Xamarin.AndroidX.CardView, recursively...
      Adding assembly reference for Xamarin.AndroidX.Collection, recursively...
      Adding assembly reference for Xamarin.AndroidX.Concurrent.Futures, recursively...
      Adding assembly reference for Xamarin.AndroidX.ConstraintLayout.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.ConstraintLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.CoordinatorLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.CursorAdapter, recursively...
      Adding assembly reference for Xamarin.AndroidX.CustomView, recursively...
      Adding assembly reference for Xamarin.AndroidX.DocumentFile, recursively...
      Adding assembly reference for Xamarin.AndroidX.DrawerLayout, recursively...
Target _ResolveAssemblies:
      Adding assembly reference for Test.Android, recursively...
      Adding assembly reference for System.Net.Http, recursively...
      Adding assembly reference for System.Runtime.Serialization, recursively...
        Adding assembly reference for System.ServiceModel.Internals, recursively...
      Adding assembly reference for FormsViewGroup, recursively...
      Adding assembly reference for Java.Interop, recursively...
      Adding assembly reference for Mono.Android, recursively...
        Adding assembly reference for System.Drawing.Common, recursively...
      Adding assembly reference for mscorlib, recursively...
      Adding assembly reference for System.Core, recursively...
      Adding assembly reference for System, recursively...
        Adding assembly reference for Mono.Security, recursively...
      Adding assembly reference for System.Numerics, recursively...
      Adding assembly reference for System.Numerics.Vectors, recursively...
      Adding assembly reference for System.Runtime, recursively...
        Adding assembly reference for System.ComponentModel.Composition, recursively...
      Adding assembly reference for System.Xml, recursively...
      Adding assembly reference for System.Xml.Linq, recursively...
      Adding assembly reference for Test, recursively...
        Adding assembly reference for netstandard, recursively...
          Adding assembly reference for System.Data, recursively...
            Adding assembly reference for System.Transactions, recursively...
          Adding assembly reference for System.Data.DataSetExtensions, recursively...
          Adding assembly reference for System.IO.Compression, recursively...
          Adding assembly reference for System.IO.Compression.FileSystem, recursively...
          Adding assembly reference for System.Web.Services, recursively...
      Adding assembly reference for Xamarin.AndroidX.Activity, recursively...
      Adding assembly reference for Xamarin.AndroidX.Annotation, recursively...
      Adding assembly reference for Xamarin.AndroidX.Annotation.Experimental, recursively...
      Adding assembly reference for Xamarin.AndroidX.AppCompat.AppCompatResources, recursively...
      Adding assembly reference for Xamarin.AndroidX.AppCompat, recursively...
      Adding assembly reference for Xamarin.AndroidX.Arch.Core.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Arch.Core.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.AsyncLayoutInflater, recursively...
      Adding assembly reference for Xamarin.AndroidX.Browser, recursively...
      Adding assembly reference for Xamarin.AndroidX.CardView, recursively...
      Adding assembly reference for Xamarin.AndroidX.Collection, recursively...
      Adding assembly reference for Xamarin.AndroidX.Concurrent.Futures, recursively...
      Adding assembly reference for Xamarin.AndroidX.ConstraintLayout.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.ConstraintLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.CoordinatorLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.CursorAdapter, recursively...
      Adding assembly reference for Xamarin.AndroidX.CustomView, recursively...
      Adding assembly reference for Xamarin.AndroidX.DocumentFile, recursively...
      Adding assembly reference for Xamarin.AndroidX.DrawerLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.DynamicAnimation, recursively...
      Adding assembly reference for Xamarin.AndroidX.Fragment, recursively...
      Adding assembly reference for Xamarin.AndroidX.Interpolator, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.UI, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.Utils, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.V4, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.LiveData.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.LiveData, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModel, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModelSavedState, recursively...
      Adding assembly reference for Xamarin.AndroidX.Loader, recursively...
      Adding assembly reference for Xamarin.AndroidX.LocalBroadcastManager, recursively...
      Adding assembly reference for Xamarin.AndroidX.Media, recursively...
      Adding assembly reference for Xamarin.AndroidX.MultiDex, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.UI, recursively...
      Adding assembly reference for Xamarin.AndroidX.Preference, recursively...
      Adding assembly reference for Xamarin.AndroidX.Print, recursively...
      Adding assembly reference for Xamarin.AndroidX.RecyclerView, recursively...
      Adding assembly reference for Xamarin.AndroidX.SavedState, recursively...
      Adding assembly reference for Xamarin.AndroidX.SlidingPaneLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.SwipeRefreshLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.Tracing.Tracing, recursively...
      Adding assembly reference for Xamarin.AndroidX.Transition, recursively...
      Adding assembly reference for Xamarin.AndroidX.VectorDrawable.Animated, recursively...
      Adding assembly reference for Xamarin.AndroidX.VectorDrawable, recursively...
      Adding assembly reference for Xamarin.AndroidX.VersionedParcelable, recursively...
      Adding assembly reference for Xamarin.AndroidX.ViewPager, recursively...
      Adding assembly reference for Xamarin.AndroidX.ViewPager2, recursively...
      Adding assembly reference for Xamarin.Essentials, recursively...
      Adding assembly reference for Xamarin.Forms.Core, recursively...
      Adding assembly reference for Xamarin.Forms.Platform.Android, recursively...
      Adding assembly reference for Xamarin.Forms.Platform, recursively...
      Adding assembly reference for Xamarin.AndroidX.DynamicAnimation, recursively...
      Adding assembly reference for Xamarin.AndroidX.Fragment, recursively...
      Adding assembly reference for Xamarin.AndroidX.Interpolator, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.UI, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.Core.Utils, recursively...
      Adding assembly reference for Xamarin.AndroidX.Legacy.Support.V4, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.LiveData.Core, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.LiveData, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModel, recursively...
      Adding assembly reference for Xamarin.AndroidX.Lifecycle.ViewModelSavedState, recursively...
      Adding assembly reference for Xamarin.AndroidX.Loader, recursively...
      Adding assembly reference for Xamarin.AndroidX.LocalBroadcastManager, recursively...
      Adding assembly reference for Xamarin.AndroidX.Media, recursively...
      Adding assembly reference for Xamarin.AndroidX.MultiDex, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.Common, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.Runtime, recursively...
      Adding assembly reference for Xamarin.AndroidX.Navigation.UI, recursively...
      Adding assembly reference for Xamarin.AndroidX.Preference, recursively...
      Adding assembly reference for Xamarin.AndroidX.Print, recursively...
      Adding assembly reference for Xamarin.AndroidX.RecyclerView, recursively...
      Adding assembly reference for Xamarin.AndroidX.SavedState, recursively...
      Adding assembly reference for Xamarin.AndroidX.SlidingPaneLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.SwipeRefreshLayout, recursively...
      Adding assembly reference for Xamarin.AndroidX.Tracing.Tracing, recursively...
      Adding assembly reference for Xamarin.AndroidX.Transition, recursively...
      Adding assembly reference for Xamarin.AndroidX.VectorDrawable.Animated, recursively...
      Adding assembly reference for Xamarin.AndroidX.VectorDrawable, recursively...
      Adding assembly reference for Xamarin.AndroidX.VersionedParcelable, recursively...
      Adding assembly reference for Xamarin.AndroidX.ViewPager, recursively...
      Adding assembly reference for Xamarin.AndroidX.ViewPager2, recursively...
      Adding assembly reference for Xamarin.Essentials, recursively...
      Adding assembly reference for Xamarin.Forms.Core, recursively...
      Adding assembly reference for Xamarin.Forms.Platform.Android, recursively...
      Adding assembly reference for Xamarin.Forms.Platform, recursively...
      Adding assembly reference for Xamarin.Forms.Xaml, recursively...
      Adding assembly reference for Xamarin.Google.Android.Material, recursively...
      Adding assembly reference for Xamarin.Google.Guava.ListenableFuture, recursively...
Target _CopyConfigFiles:
  Skipping target "_CopyConfigFiles" because it has no inputs.
Target _ConvertPdbFiles:
  Skipping target "_ConvertPdbFiles" because it has no outputs.
Target _LinkAssembliesShrink:
  Skipping target "_LinkAssembliesShrink" because all output files are up-to-date with respect to the input files.
Target _CopyConfigFiles:
  Skipping target "_CopyConfigFiles" because it has no inputs.
Target _ConvertPdbFiles:
  Skipping target "_ConvertPdbFiles" because it has no outputs.
Target _GenerateJavaStubs:
  Skipping target "_GenerateJavaStubs" because all output files are up-to-date with respect to the input files.
Target _ManifestMerger:
  Skipping target "_ManifestMerger" because all output files are up-to-date with respect to the input files.
Target _ConvertCustomView:
  Skipping target "_ConvertCustomView" because all output files are up-to-date with respect to the input files.
      Adding assembly reference for Xamarin.Forms.Xaml, recursively...
      Adding assembly reference for Xamarin.Google.Android.Material, recursively...
      Adding assembly reference for Xamarin.Google.Guava.ListenableFuture, recursively...
Target _CopyConfigFiles:
  Skipping target "_CopyConfigFiles" because it has no inputs.
Target _ConvertPdbFiles:
  Skipping target "_ConvertPdbFiles" because it has no outputs.
Target _LinkAssembliesShrink:
  Skipping target "_LinkAssembliesShrink" because all output files are up-to-date with respect to the input files.
Target _CopyConfigFiles:
  Skipping target "_CopyConfigFiles" because it has no inputs.
Target _ConvertPdbFiles:
  Skipping target "_ConvertPdbFiles" because it has no outputs.
Target _GenerateJavaStubs:
  Skipping target "_GenerateJavaStubs" because all output files are up-to-date with respect to the input files.
Target _ManifestMerger:
  Skipping target "_ManifestMerger" because all output files are up-to-date with respect to the input files.
Target _ConvertCustomView:
  Skipping target "_ConvertCustomView" because all output files are up-to-date with respect to the input files.
Target _AddStaticResources:
  Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
Target _GeneratePackageManagerJava:
  Skipping target "_GeneratePackageManagerJava" because all output files are up-to-date with respect to the input files.
Target _GenerateAndroidAssetsDir:
  Skipping target "_GenerateAndroidAssetsDir" because it has no outputs.
Target _PrepareCreateBaseApk:
  Skipping target "_PrepareCreateBaseApk" because all output files are up-to-date with respect to the input files.
Target _CreateBaseApk:
  Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
Target _CompileJava:
  Skipping target "_CompileJava" because all output files are up-to-date with respect to the input files.
Target _CompileNativeAssemblySources:
  Skipping target "_CompileNativeAssemblySources" because all output files are up-to-date with respect to the input files.
Target _CreateApplicationSharedLibraries:
  Skipping target "_CreateApplicationSharedLibraries" because all output files are up-to-date with respect to the input files.
Target _CompileToDalvik:
  Skipping target "_CompileToDalvik" because all output files are up-to-date with respect to the input files.
Target _BuildApkEmbed:
  Skipping target "_BuildApkEmbed" because all output files are up-to-date with respect to the input files.
Target _CopyPackage:
  Skipping target "_CopyPackage" because all output files are up-to-date with respect to the input files.
Target _ResolveAndroidSigningKey:
    Touching "obj/Debug/android_debug_keystore.flag".
Target _AddStaticResources:
  Skipping target "_AddStaticResources" because all output files are up-to-date with respect to the input files.
Target _GeneratePackageManagerJava:
  Skipping target "_GeneratePackageManagerJava" because all output files are up-to-date with respect to the input files.
Target _GenerateAndroidAssetsDir:
  Skipping target "_GenerateAndroidAssetsDir" because it has no outputs.
Target _PrepareCreateBaseApk:
  Skipping target "_PrepareCreateBaseApk" because all output files are up-to-date with respect to the input files.
Target _CreateBaseApk:
  Skipping target "_CreateBaseApk" because all output files are up-to-date with respect to the input files.
Target _CompileJava:
  Skipping target "_CompileJava" because all output files are up-to-date with respect to the input files.
Target _CompileNativeAssemblySources:
  Skipping target "_CompileNativeAssemblySources" because all output files are up-to-date with respect to the input files.
Target _CreateApplicationSharedLibraries:
  Skipping target "_CreateApplicationSharedLibraries" because all output files are up-to-date with respect to the input files.
Target _CompileToDalvik:
  Skipping target "_CompileToDalvik" because all output files are up-to-date with respect to the input files.
Target _BuildApkEmbed:
  Skipping target "_BuildApkEmbed" because all output files are up-to-date with respect to the input files.
Target _CopyPackage:
  Skipping target "_CopyPackage" because all output files are up-to-date with respect to the input files.
Target _ResolveAndroidSigningKey:
    Touching "obj/Debug/android_debug_keystore.flag".
Target _Sign:
  Skipping target "_Sign" because all output files are up-to-date with respect to the input files.
Target _Sign:
  Skipping target "_Sign" because all output files are up-to-date with respect to the input files.
Target _Upload:
    Using cached value from RegisterTaskObject
    Found device: 7PTSPFL7Q4V8WKJ7
Target _Upload:
    Using cached value from RegisterTaskObject
    Found device: 7PTSPFL7Q4V8WKJ7

InstallPackage

InstallPackage

### Workaround
No workaround so far, works when deployed on iOS though.

**Comment by tbaggett** [comment]
Hi @PoorneshEcolab, have you tried the following?
1. Close VS
2. Delete all bin/obj folders under your solution folder
3. Restart VS and open an SDK Command Prompt (under the VS for Mac "Tools - Android" menu section, not sure about Windows) 
4. Entering the "adb kill-server" command in the command prompt window, followed by the "adb start-server" command

I've had cases where deployments to my Android device were taking an hour or more before. Following the above steps reduced it back down to a couple of minutes for me. Good luck!

**Comment by MouratidisA** [comment]
Hi @PoorneshEcolab, have you tried to disable the "fast assembly deployment"? 
I had similar issues deploying my application to Android devices using visual studio for Mac.

**Comment by Paul-N** [comment]
Same story for me, disabling the "fast assembly deployment" solved the issue

**Comment by PoorneshEcolab** [comment]
@Paul-N  @MouratidisA  The only hack that worked for me was:

-  to clear bin and obj from project files
-  Removed caches from my mac **/Users/XYZLibrary/Caches**
- Restarted my machine, and it deploys. 

However, the problem remains after deploying a few times. Though the hack works, I would like to keep the issue opened as this can't be a fix.

**Comment by jfversluis** [comment]
This is an issue for Visual Studio and tooling. There is nothing we can do about this from our side unfortunately. Please report this through Visual Studio by going to Help > Provide Feedback > Report a Problem. That will make it go to the correct team with all the required information.
