### ISSUE TITLE
Xamarin app crash on startup during Apple review process

### ISSUE THREAD

**Issue by gpsaliola** [xamarin/Xamarin.Forms#15799]
The app was rejected by Apple review team with:

"DESCRIPTION OF PROBLEM
The app review process rejected the OkMap Mobile app because it crashes on startup.
This is the received message:

"We were unable to review your app as it crashed on launch. We have attached detailed crash logs to help troubleshoot this issue.

Review device details:

- Device type: iPad
- OS version: iOS 16.6"

In my tests, the app works fine both in debug and on the following physical devices:
iPhone X - iOS 16.5.1
iPhone SE - iOS 16.6
iPad Air - iOS 12.5.6

I've symbolized the crash report that Apple was sent me (see ### Crash log).
I need some information to understand the crash log.

### Steps to Reproduce
Launch the app and verify if the app crashes.

### Expected Behavior
The app should not crash.

### Environment
Microsoft Visual Studio Community 2022
Versione 17.7.0
VisualStudio.17.Release/17.7.0+34003.232
Microsoft .NET Framework
Versione 4.8.09037

Edizione installata: Community

Visual C++ 2022   00482-90000-00000-AA273
Microsoft Visual C++ 2022

Adattatore di test per Boost.Test   1.0
Consente di usare gli strumenti di test di Visual Studio con unit test scritti per Boost.Test. Le condizioni d'uso e le comunicazioni relative a terze parti sono disponibili nella directory di installazione dell'estensione.

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.265.7160
ASP.NET and Web Tools

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.265.7160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.5.3+7f0b0a9d18
PreEmptive Protection - Dotfuscator CE

Estensione VSPackage   1.0
Informazioni dettagliate sull'estensione VSPackage di Visual Studio

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Gestione pacchetti NuGet   6.7.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web https://docs.nuget.org/

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Fornisce servizi di linguaggio per ASP.NET Core Razor.

SQL Server Data Tools   17.7.9.2
Microsoft SQL Server Data Tools

Strumenti C#   4.7.0-3.23373.1+7829f6b85177e96de89bc67f32b61d74ac590f5a
Componenti di C# usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti del Servizio app di Azure versione 3.0.0   17.7.265.7160
Strumenti del Servizio app di Azure versione 3.0.0

Strumenti di Microsoft Azure per Visual Studio   2.9
Supporto per i progetti di Servizi cloud di Azure

Strumenti di Visual Basic   4.7.0-3.23373.1+7829f6b85177e96de89bc67f32b61d74ac590f5a
Componenti di Visual Basic usati nell'IDE. A seconda del tipo e delle impostazioni del processo, è possibile che venga usata una versione diversa del compilatore.

Strumenti TypeScript   17.0.20628.2001
Strumenti TypeScript per Microsoft Visual Studio

Test Adapter for Google Test   1.0
Consente di usare gli strumenti di test di Visual Studio con unit test scritti per Google Test. Le condizioni d'uso e le comunicazioni relative a terze parti sono disponibili nella directory di installazione dell'estensione.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
Sviluppo assistito conl'intelligenza artificiale per Visual Studio.

VisualStudio.DeviceLog   1.0
Informazioni sul pacchetto

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.7.0.214 (d17-7@a69bacb)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Estensione di Visual Studio per abilitare gli strumenti di Xamarin Designer in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.5 (191fe02ea)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Crash Log
Incident Identifier: 45C53262-5DD0-4543-856A-83A61EEEB174
CrashReporter Key:   03541d201e5113174e6a0fc819513ad6562e314d
Hardware Model:      iPhone14,4
Process:             OkMap.iOS [1436]
Path:                /private/var/containers/Bundle/Application/096BDC74-3C3D-47C9-BF40-B6138C63AE4C/OkMap.iOS.app/OkMap.iOS
Identifier:          Gian-Paolo-Saliola.OkMap
Version:             4.02 (1)
Report Version:      104
Code Type:           ARM-64 (Native(?))
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           Gian-Paolo-Saliola.OkMap [831]

Date/Time:           2023-08-11 07:51:52.2042 +0800
Launch Time:         2023-08-11 07:51:51.9133 +0800
OS Version:          iPhone OS 16.6 (20G75)
Release Type:        User
Baseband Version:    2.80.01

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Thread 0 name:  tid_103
Thread 0 Crashed:
0    libsystem_kernel.dylib                  0x1e53f1578 __pthread_kill + 8
1    libsystem_pthread.dylib                 0x20626c118 pthread_kill + 268
2    libsystem_c.dylib                       0x1ad9b4c04 __abort + 128
3    libsystem_c.dylib                       0x1ad95c184 abort + 192
4    OkMap.iOS                               0x1071c2e70 xamarin_find_protocol_wrapper_type + 43265648 (runtime.m:1194)
5    OkMap.iOS                               0x1070db920 mono_invoke_unhandled_exception_hook + 42318112 (exception.c:1299)
6    OkMap.iOS                               0x10707d378 mono_handle_exception_internal + 41931640 (mini-exceptions.c:2783)
7    OkMap.iOS                               0x10707bd4c mono_handle_exception + 41925964 (mini-exceptions.c:3107)
8    OkMap.iOS                               0x107072fc0 mono_arm_throw_exception + 41889728 (exceptions-arm64.c:403)
9    OkMap.iOS                               0x1049ce79c throw_exception + 172
10   OkMap.iOS                               0x1048e5574 System_Reflection_RuntimeConstructorInfo_InternalInvoke_object_object___bool + 132
11   OkMap.iOS                               0x104abcf94 mscorlib_System_RuntimeType_CreateInstanceMono_bool_bool + 2346900 (RuntimeType.cs:0)
12   OkMap.iOS                               0x10708d8b0 mono_jit_runtime_invoke + 41998512 (mini-runtime.c:3191)
13   OkMap.iOS                               0x107124604 mono_runtime_invoke_checked + 42616324 (object.c:3220)
14   OkMap.iOS                               0x107127a88 mono_runtime_invoke + 42629768 (object.c:3107)
15   OkMap.iOS                               0x104887148 native_to_managed_trampoline_14(objc_object*, objc_selector*, _MonoMethod**, unsigned int) + 29000 (registrar.m:759)
16   OkMap.iOS                               0x1048b2258 -[Xamarin_Forms_Platform_iOS_ShellSectionRootRenderer viewDidLoad] + 205400 (registrar.m:18310)
17   UIKitCore                               0x1a88178f8 -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 84
18   UIKitCore                               0x1a84b414c -[UIViewController loadViewIfRequired] + 712
19   UIKitCore                               0x1a87761c8 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 124
20   UIKitCore                               0x1a863d944 -[UINavigationController _startTransition:fromViewController:toViewController:] + 196
21   UIKitCore                               0x1a863cdf4 -[UINavigationController _startDeferredTransitionIfNeeded:] + 608
22   UIKitCore                               0x1a863c444 -[UINavigationController __viewWillLayoutSubviews] + 96
23   UIKitCore                               0x1a863c3a8 -[UILayoutContainerView layoutSubviews] + 172
24   UIKitCore                               0x1a849e420 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1992
25   QuartzCore                              0x1a7958f30 CA::Layer::layout_if_needed(CA::Transaction*) + 500
26   QuartzCore                              0x1a796c4ac CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 148
27   QuartzCore                              0x1a797d8d8 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 444
28   QuartzCore                              0x1a79ace80 CA::Transaction::commit() + 648
29   UIKitCore                               0x1a892675c __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 36
30   CoreFoundation                          0x1a646e6e0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28
31   CoreFoundation                          0x1a64d5210 __CFRunLoopDoBlocks + 364
32   CoreFoundation                          0x1a64a50e8 __CFRunLoopRun + 848
33   CoreFoundation                          0x1a64aa3ec CFRunLoopRunSpecific + 612
34   GraphicsServices                        0x1e19c035c GSEventRunModal + 164
35   UIKitCore                               0x1a8836f58 -[UIApplication _run] + 888
36   UIKitCore                               0x1a8836bbc UIApplicationMain + 340
37   OkMap.iOS                               0x1071c02f4 xamarin_UIApplicationMain + 24
38   OkMap.iOS                               0x1059a4b98 wrapper_managed_to_native_UIKit_UIApplication_xamarin_UIApplicationMain_int_intptr_intptr_intptr_intptr_ + 152
39   OkMap.iOS                               0x105a1edb4 Xamarin_iOS_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 18476468 (UIApplication.cs:58)
40   OkMap.iOS                               0x10708d8b0 mono_jit_runtime_invoke + 41998512 (mini-runtime.c:3191)
41   OkMap.iOS                               0x107124604 mono_runtime_invoke_checked + 42616324 (object.c:3220)
42   OkMap.iOS                               0x107129878 mono_runtime_exec_main_checked + 42637432 (object.c:5288)
43   OkMap.iOS                               0x107072b2c mono_jit_exec + 41888556 (driver.c:1328)
44   OkMap.iOS                               0x1071ca66c xamarin_main + 43296364 (monotouch-main.m:0)
45   OkMap.iOS                               0x1048bfe68 main + 261736 (main.m:178)
46   dyld                                    0x1c59dcdec start + 2220

Thread 1:
0    libsystem_pthread.dylib                 0x206265b74 start_wqthread + 0

Thread 2 name:  SGen worker
Thread 2:
0    libsystem_kernel.dylib                  0x1e53eb578 __psynch_cvwait + 8
1    libsystem_pthread.dylib                 0x20626d078 _pthread_cond_wait + 1232
2    OkMap.iOS                               0x10719ffc0 thread_func + 43122624 (sgen-thread-pool.c:196)
3    libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
4    libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 3 name:  Finalizer
Thread 3:
0    libsystem_kernel.dylib                  0x1e53eac20 semaphore_wait_trap + 8
1    OkMap.iOS                               0x1070ddb48 finalizer_thread + 42326856 (gc.c:965)
2    OkMap.iOS                               0x1071563e4 start_wrapper_internal + 42820580 (threads.c:1289)
3    OkMap.iOS                               0x107156268 start_wrapper + 42820200 (threads.c:1310)
4    libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
5    libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 4:
0    libsystem_pthread.dylib                 0x206265b74 start_wqthread + 0

Thread 5:
0    libsystem_pthread.dylib                 0x206265b74 start_wqthread + 0

Thread 6 name:  com.apple.uikit.eventfetch-thread
Thread 6:
0    libsystem_kernel.dylib                  0x1e53eaca4 mach_msg2_trap + 8
1    libsystem_kernel.dylib                  0x1e53fdb74 mach_msg2_internal + 80
2    libsystem_kernel.dylib                  0x1e53fde4c mach_msg_overwrite + 540
3    libsystem_kernel.dylib                  0x1e53eb1e8 mach_msg + 24
4    CoreFoundation                          0x1a64a4024 __CFRunLoopServiceMachPort + 160
5    CoreFoundation                          0x1a64a5250 __CFRunLoopRun + 1208
6    CoreFoundation                          0x1a64aa3ec CFRunLoopRunSpecific + 612
7    Foundation                              0x1a0726fb4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8    Foundation                              0x1a0726e9c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9    UIKitCore                               0x1a8969cc8 -[UIEventFetcher threadMain] + 416
10   Foundation                              0x1a0740524 __NSThread__start__ + 716
11   libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
12   libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 7:
0    libsystem_pthread.dylib                 0x206265b74 start_wqthread + 0

Thread 8 name:  com.apple.UIKit.KeyboardManagement
Thread 8:
0    libsystem_kernel.dylib                  0x1e53eb7dc __ulock_wait + 8
1    libdispatch.dylib                       0x1ad8fc89c _dlock_wait + 56
2    libdispatch.dylib                       0x1ad8fc650 _dispatch_thread_event_wait_slow + 56
3    libdispatch.dylib                       0x1ad90b714 __DISPATCH_WAIT_FOR_QUEUE__ + 368
4    libdispatch.dylib                       0x1ad90b2c0 _dispatch_sync_f_slow + 148
5    UIKitCore                               0x1a883722c __37-[_UIRemoteKeyboards startConnection]_block_invoke_3 + 156
6    CoreFoundation                          0x1a649dc04 __invoking___ + 148
7    CoreFoundation                          0x1a644bcb4 -[NSInvocation invoke] + 428
8    Foundation                              0x1a07866f8 __NSXPCCONNECTION_IS_CALLING_OUT_TO_REPLY_BLOCK__ + 16
9    Foundation                              0x1a0757a5c -[NSXPCConnection _decodeAndInvokeReplyBlockWithEvent:sequence:replyInfo:] + 520
10   Foundation                              0x1a0cc8a00 __88-[NSXPCConnection _sendInvocation:orArguments:count:methodSignature:selector:withProxy:]_block_invoke_5 + 188
11   libxpc.dylib                            0x2062c5ee4 _xpc_connection_reply_callout + 124
12   libxpc.dylib                            0x2062b8ee8 _xpc_connection_call_reply_async + 88
13   libdispatch.dylib                       0x1ad8fbf2c _dispatch_client_callout3 + 20
14   libdispatch.dylib                       0x1ad919e38 _dispatch_mach_msg_async_reply_invoke + 344
15   libdispatch.dylib                       0x1ad90340c _dispatch_lane_serial_drain + 372
16   libdispatch.dylib                       0x1ad9040d8 _dispatch_lane_invoke + 436
17   libdispatch.dylib                       0x1ad90ecdc _dispatch_workloop_worker_thread + 648
18   libsystem_pthread.dylib                 0x206265ddc _pthread_wqthread + 288
19   libsystem_pthread.dylib                 0x206265b7c start_wqthread + 8

Thread 9:
0    libsystem_pthread.dylib                 0x206265b74 start_wqthread + 0

Thread 10 name:  Timer-Scheduler
Thread 10:
0    libsystem_kernel.dylib                  0x1e53eb578 __psynch_cvwait + 8
1    libsystem_pthread.dylib                 0x20626d078 _pthread_cond_wait + 1232
2    OkMap.iOS                               0x1071adc64 mono_os_cond_timedwait + 43179108 (mono-os-mutex.c:75)
3    OkMap.iOS                               0x10715de60 mono_w32handle_timedwait_signal_handle + 42851936 (w32handle.c:767)
4    OkMap.iOS                               0x10715dd38 mono_w32handle_wait_one + 42851640 (w32handle.c:895)
5    OkMap.iOS                               0x10715df5c mono_w32handle_wait_multiple + 42852188 (w32handle.c:1002)
6    OkMap.iOS                               0x107152650 ves_icall_System_Threading_WaitHandle_Wait_internal + 42804816 (threads.c:2314)
7    OkMap.iOS                               0x1070f3674 ves_icall_System_Threading_WaitHandle_Wait_internal_raw + 42415732 (icall-def.h:1100)
8    OkMap.iOS                               0x1048d8ea8 wrapper_managed_to_native_System_Threading_WaitHandle_Wait_internal_intptr__int_bool_int + 120
9    OkMap.iOS                               0x104ae95f8 mscorlib_System_Threading_WaitHandle_WaitOneNative_System_Runtime_InteropServices_SafeHandle_uint_bool_bool + 2528760 (WaitHandle.cs:0)
10   OkMap.iOS                               0x104ae2238 mscorlib_System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 2499128 (executioncontext.cs:911)
11   OkMap.iOS                               0x10708d8b0 mono_jit_runtime_invoke + 41998512 (mini-runtime.c:3191)
12   OkMap.iOS                               0x107124604 mono_runtime_invoke_checked + 42616324 (object.c:3220)
13   OkMap.iOS                               0x1071291fc mono_runtime_delegate_try_invoke + 42635772 (object.c:4441)
14   OkMap.iOS                               0x1071564dc start_wrapper_internal + 42820828 (threads.c:1258)
15   OkMap.iOS                               0x107156268 start_wrapper + 42820200 (threads.c:1310)
16   libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
17   libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 11 name:  tid_7703
Thread 11:
0    libsystem_kernel.dylib                  0x1e53eb578 __psynch_cvwait + 8
1    libsystem_pthread.dylib                 0x20626d078 _pthread_cond_wait + 1232
2    OkMap.iOS                               0x1071adc64 mono_os_cond_timedwait + 43179108 (mono-os-mutex.c:75)
3    OkMap.iOS                               0x1071b5130 mono_thread_info_sleep + 43209008 (mono-threads.c:1673)
4    OkMap.iOS                               0x10714da00 monitor_thread + 42785280 (threadpool-worker-default.c:728)
5    OkMap.iOS                               0x1071563e4 start_wrapper_internal + 42820580 (threads.c:1289)
6    OkMap.iOS                               0x107156268 start_wrapper + 42820200 (threads.c:1310)
7    libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
8    libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 12 name:  Thread Pool Worker
Thread 12:
0    libsystem_kernel.dylib                  0x1e53eac38 semaphore_timedwait_trap + 8
1    OkMap.iOS                               0x10714e2b8 worker_thread + 42787512 (threadpool-worker-default.c:490)
2    OkMap.iOS                               0x1071563e4 start_wrapper_internal + 42820580 (threads.c:1289)
3    OkMap.iOS                               0x107156268 start_wrapper + 42820200 (threads.c:1310)
4    libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
5    libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Thread 13 name:  Thread Pool Worker
Thread 13:
0    libsystem_kernel.dylib                  0x1e53eac38 semaphore_timedwait_trap + 8
1    OkMap.iOS                               0x10714e2b8 worker_thread + 42787512 (threadpool-worker-default.c:490)
2    OkMap.iOS                               0x1071563e4 start_wrapper_internal + 42820580 (threads.c:1289)
3    OkMap.iOS                               0x107156268 start_wrapper + 42820200 (threads.c:1310)
4    libsystem_pthread.dylib                 0x2062666b8 _pthread_start + 148
5    libsystem_pthread.dylib                 0x206265b88 thread_start + 8

Binary Images:
0x104880000 - 0x1072a7fff OkMap.iOS arm64 <a756a0c044c63395a9c3443efbd205c6> /private/var/containers/Bundle/Application/096BDC74-3C3D-47C9-BF40-B6138C63AE4C/OkMap.iOS.app/OkMap.iOS
0x107aa0000 - 0x107fe7fff libSkiaSharp arm64 <e731a267097031bda384c26188c796ca> /private/var/containers/Bundle/Application/096BDC74-3C3D-47C9-BF40-B6138C63AE4C/OkMap.iOS.app/Frameworks/libSkiaSharp.framework/libSkiaSharp
0x1076a8000 - 0x107793fff libHarfBuzzSharp arm64 <b70950ccc85f3515ae8797452f337d93> /private/var/containers/Bundle/Application/096BDC74-3C3D-47C9-BF40-B6138C63AE4C/OkMap.iOS.app/Frameworks/libHarfBuzzSharp.framework/libHarfBuzzSharp
0x10d4d0000 - 0x10d4dbfff libobjc-trampolines.dylib arm64e <7e77fc541c3331c086e81fb7bf12836c> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
0x1e53ea000 - 0x1e5421fe7 libsystem_kernel.dylib arm64e <681b06a07f6b3fa3a2ce063dc1da7b1b> /usr/lib/system/libsystem_kernel.dylib
0x206265000 - 0x206270ff3 libsystem_pthread.dylib arm64e <aa302f5affe5327aa0033b288b935de1> /usr/lib/system/libsystem_pthread.dylib
0x1ad93f000 - 0x1ad9bcff3 libsystem_c.dylib arm64e <073251d1d4c937748cee75210751a5d8> /usr/lib/system/libsystem_c.dylib
0x1a849a000 - 0x1a9cbefff UIKitCore arm64e <7d57a1d1856f338d97db880c4ec8b02e> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
0x1a794f000 - 0x1a7cc8fff QuartzCore arm64e <8682cc56125a35658075978cc718b93f> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x1a642b000 - 0x1a6812fff CoreFoundation arm64e <a900b4590127379e9cba0eab9c5d559f> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1e19bf000 - 0x1e19c7fff GraphicsServices arm64e <cd8d719514e13c7ca8c950ccea9f2a17> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
0x1c59c7000 - 0x1c5a4ca53 dyld arm64e <c3fc2ee4367f3086beb8420ad442bf88> /usr/lib/dyld
0x1a06e5000 - 0x1a0fc2fff Foundation arm64e <1715de5d08933af0b0c0550bb14f91ec> /System/Library/Frameworks/Foundation.framework/Foundation
0x1ad8f8000 - 0x1ad93efff libdispatch.dylib arm64e <5d16936b4e4c3276ba7a69c9bc760aba> /usr/lib/system/libdispatch.dylib
0x2062a8000 - 0x2062e9fff libxpc.dylib arm64e <a0d322a3d7723260969071f28737c43c> /usr/lib/system/libxpc.dylib

**Comment by jfversluis** [comment]
Without any relevant code or more information it's near impossible to debug this. Also, I do have a feeling this is more something in your project than it is something in Xamarin.Forms.

Try running your app through TestFlight or build it with the Release configuration and see if you can uncover something like that. I you haven't so already, it might help to use some service like App Center Crashes and see if that gives you a lead on where it crashes. Additionally you might be able to check the device logs. Good luck!

**Comment by gpsaliola** [comment]
I've solved! Please see #2150.

**Comment by MitchBomcanhao** [comment]
I assume you meant https://github.com/Mapsui/Mapsui/issues/2150 , which refers to https://github.com/mono/SkiaSharp/issues/2147

**Comment by gpsaliola** [comment]
Yes, sorry.
