### ISSUE TITLE
[Internal] AndroidDeviceInfo is setting ScaledScreenSize with Width for Height

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#1579]
### Description

Here's the issue:

`ScaledScreenSize = new Size(_pixelScreenSize.Width / _scalingFactor, _pixelScreenSize.Width / _scalingFactor);`

When `Size` is being allocated, we're using `Width` for `Height`.

**Comment by adrianknight89** [comment]
@rmarinho @hartez #3641 fixes this.

**Comment by hartez** [comment]
Well, now I'm just sad that @adrianknight89 noticed this like 8 months ago, told us about it, and we somehow still missed it. :(

**Comment by adrianknight89** [comment]
@hartez You guys have a lot on your plate, so I'm not surprised. Looks like it'll be tough to scour the current list of issues and mark duplicate items. Thanks for fixing this issue though. :)
