### ISSUE TITLE
[Bug] It does not prompt me for media access permission. (Android 13 API level 33) using xamarin forms

### ISSUE THREAD

**Issue by ARatifrehman** [xamarin/Xamarin.Forms#15806]
When my target Android version is Android 12.1 (API Level 32), everything works fine.

In Xamarin Android set the target to Android 13 (API 33), but in Android 13, it doesn't prompt me for media access permission.

[Error]
![Screenshot_20230823_102601](https://github.com/xamarin/Xamarin.Forms/assets/142967067/4ad240ba-15b3-4274-a990-e3407355a45c)

![Screenshot 2023-08-23 094501](https://github.com/xamarin/Xamarin.Forms/assets/142967067/2cce9fce-9c9c-40c5-8868-270985721848)

I am trying to update the package, but the package is not getting updated.
![Screenshot 2023-08-23 123131](https://github.com/xamarin/Xamarin.Forms/assets/142967067/049f153f-8ead-4055-a744-89c8153704f8)

**Comment by jfversluis** [comment]
This is not an issue in Xamarin.Forms, probably in the plugin that you are using for this.
