### ISSUE TITLE
Cannot update to XF 5.0.0.0.2612 and essentials 1.80  ExportRenderer no found - Need to re-submit app -App not compatible

### ISSUE THREAD

**Issue by gabsamples6** [xamarin/Xamarin.Forms#15803]
### Description
Hi - wondering if someone could shed some light into this. I need to submit the app because google sent us an email that the app is referencing an old version of android. So I went an updated to the latest XF and essentials and getting errors

Any suggestions why I am getting  ExportRenderer no found and loads of other errors?

if of any help to diagnose the issue this happens in an android class library that we share not  in the actual android project 

I Have

1.   Visual studio 17.7 2022 
2.  Xamarin forms 5.0.0.0.2612
3.  Essentials  1.8.0

and I get  "The type or namespace ExportRenderer could not be found"  

### Steps to Reproduce

1.  Update to  Xamarin forms 5.0.0.0.2612
5.  update Essentials  1.8.0
6. Build solution and I get 
  "The type or namespace ExportRenderer could not be found"  and  lots of errors...

looks as if it cannot find Platform.Android
![image](https://github.com/xamarin/Xamarin.Forms/assets/109357537/7850a6ac-1b46-41ea-b858-26f7002e4ecc)

### Basic Information

- Version with issue:
- Last known good version:
-  Xamarin forms 5.0.0.2545 with essentials 1.7.3   (those were my last references I used and worked)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library / AndroidX Version: 
- NuGet Packages:
Below are the android packages I use 
```
        <PackageReference Include="Xamarin.AndroidX.Core">
          <Version>1.6.0.3</Version>
        </PackageReference>
        <PackageReference Include="Xamarin.AndroidX.RecyclerView">
          <Version>1.2.1.3</Version>
        </PackageReference>
        <PackageReference Include="Xamarin.CommunityToolkit">
          <Version>2.0.6</Version>
        </PackageReference>
        <PackageReference Include="Xamarin.Essentials">
          <Version>1.8.0</Version>
        </PackageReference>
        <PackageReference Include="Xamarin.AndroidX.Palette" Version="1.0.0.10" />
        <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData" Version="2.3.1.3" />
        <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.3.0.8" />
        <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4" Version="1.0.0.10" />
        <PackageReference Include="Xamarin.AndroidX.MediaRouter" Version="1.2.5.2" />
        <PackageReference Include="Xamarin.Forms" Version="5.0.0.2612" />
        <PackageReference Include="Xamarin.GooglePlayServices.Base">
          <Version>117.6.0.3</Version>
        </PackageReference>
```

### Environment

<!--
1.
Microsoft Visual Studio Enterprise 2022
Version 17.7.0
VisualStudio.17.Release/17.7.0+34003.232
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA686
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.265.7160
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.265.7160
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.265.7160
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-3.23373.1+7829f6b85177e96de89bc67f32b61d74ac590f5a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.34 (main@d5ab18b)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.27 (547ea6f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.9.2
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20628.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23373.1+7829f6b85177e96de89bc67f32b61d74ac590f5a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.214 (d17-7@a69bacb)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.3.9 (remotes/origin/d17-7@796d191def)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.21 (150ec9f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.1.2 (d17-5/a8a26c7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.5 (191fe02ea)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by gabsamples6** [comment]
I think I might have resolved it. was not using some dependencies in the android class project

**Comment by Cvijo** [comment]
@gabsamples6  i have the same issue, how did you fix this? what dependencies?

**Comment by gabsamples6** [comment]
@Cvijo  I think i removed all the old android support libraries and just have the androidx ones and that sorted it
