### ISSUE TITLE
[Bug] [Android] Click shell tabbar cause more and more slow, then the phone  "No Response"

### ISSUE THREAD

**Issue by z64664440** [xamarin/Xamarin.Forms#15804]
### Steps to Reproduce

1. Create a new xamarin.forms project with tabbar, do nothing changed ,and run it on Android phone
2. Use auto click tool to click Keep click the tab bar to switch page.
3. Keep click once per 1s, and after about 1Hour; the page switching become more and more slow, 
and finally, phone "No Response" message displayed.

My xamarin.forms version is 5.0.0.2612
The android version  is andorid 13(it also can be reproduced in android12)

Hope you can help me

**Comment by jfversluis** [comment]
I guess this depends on what you do in your project when switching tabs. Without any reproduction, relevant code, logs or anything it's near impossible to say anything about this, sorry.

If you have any more concrete information and you think there is a bug in Xamarin.Forms, feel free to open a new issue.

Thanks
