### ISSUE TITLE
Defining generic classes in XAML

### ISSUE THREAD

**Issue by developMediaSoft** [xamarin/Xamarin.Forms#1580]
### Description
It is possible to specify a class with type parameters in XAML (see step 2), but the generated (partial) definition will cause a runtime failure.

### Steps to Reproduce

1. Add &lt;T&gt; to parameterize a ContentPage derivative in its code-behind
2. Add &amp;lt;T&amp;gt; to x:Class in its XAML
3. Try instantiating it with a concrete type

### Expected Behavior

The class is successfully instantiated according to its definitions in XAML and code-behind

### Actual Behavior

Runtime failure at line global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(GenericClass&lt;T&gt;));

An exception of type 'Xamarin.Forms.Xaml.XamlParseException' occurred in Xamarin.Forms.Xaml.dll but was not handled in user code

Additional information: No embeddedresource found for Project.GenericClass`1[ConcreteType]

### Basic Information

- Version with issue: Xamarin.Forms.2.5.0.122203
- Last known good version: N/A (it's the same on 2.4.0.280)
- IDE: Visual Studio 2015
- Platform Target Frameworks:
  - UWP: 10.0A
- Affected Devices: All

**Comment by StephaneDelcroix** [comment]
Defining generic classes in Xaml is not supported at this time.

step 2 should also be "Add '`1' to x:Class

**Comment by developMediaSoft** [comment]
Thanks, hope someone picks it up.
P.S. Step 2 is <T> encoded using XML entities &gt; (greater than) and &lt; (less than), or am I missing something?

**Comment by CZEMacLeod** [comment]
@developMediaSoft The docs for `x:Class` say it uses the same format as `Type.FullName` which would mean a generic class such as `List<String>` would be written as ```System.Collections.Generic.List`1[System.String]```
Thus your step 2 would be ``` `1[T]``` rather than `&lt;T&gt;`

I think there would be some issues with knowing the list of concrete types that could be instantiated - unless T was internal and all derived classes were sealed??

I have a number of XAML pages which are concrete implementations of a Generic base class which works for my situation - but I don't think that is what you are looking for. (See `x:TypeArguments`)

**Comment by developMediaSoft** [comment]
Thank you for explaining that @CZEMacLeod, I must say I've only learned this fact about x:Class from you now. My use of entities was a guess.

What would knowing concrete types be necessary for?

Indeed simply parameterizing an already-defined generic class in XAML utilizing x:TypeArguments is not what I'm after, but I appreciate you mentioning it for the sake of those who might find this thread via search engines.

**Comment by StephaneDelcroix** [comment]
I don't foresee this being implemented in the coming months by the XF team, and no one volunteered, so I'll close it. We'll reopen it if needed, or I'm sure we can come up with that exact same idea again

**Comment by developMediaSoft** [comment]
Our Xamarin.Forms-based project is in a similar state as this issue

**Comment by lassana** [comment]
So this will never be implemented, right?
