### ISSUE TITLE
'OnIdiom' needs to be overrideable for the Forms Previewer

### ISSUE THREAD

**Issue by alanmcgovern** [xamarin/Xamarin.Forms#1581]
The forms previewer fakes Phone versus Tablet mode by rendering the screens at different resolutions as it is significantly more performant to do this than to create a phone rendering target and a tablet rendering target. However this confuses the mechanism Xamarin.Forms uses to detect phone versus tablet for it's `OnIdiom` xaml element.

Can we make this overridable in some form so we can tell Forms which idiom we're rendering in? Are there other places which attempt to detect phone versus tablet mode which would need to be adjusted/overridden?

**Comment by StephaneDelcroix** [comment]
you can set it with this API, just after you call `Forms.Init()`
```public static void Xamarin.Forms.Device.SetIdiom(TargetIdiom idiom);```

**Comment by StephaneDelcroix** [comment]
you should be, yes. can I close this ?
