### ISSUE TITLE
[Bug] Element.ChildRemoved event is passing the removed child as "sender"

### ISSUE THREAD

**Issue by Lalalalala05** [xamarin/Xamarin.Forms#15818]
### Description

The "OnChildRemoved" method of the "Xamarin.Forms.Element" class is firing the "ChildRemove" event giving the child as the first argument (sender) instead of itself.
I'm assuming this isn't intentional, especially considering that for the "ChildAdded" event the element does give itself as the sender.

**Comment by jfversluis** [comment]
While that does seem odd, it has probably been this way for a long time and would be a breaking change right now. Considering the Xamarin.Forms lifespan we have left, I don't think we will be changing this behavior anymore at this time.

Thank you!
