### ISSUE TITLE
Androd style attribute not found errors after updating Target Andoid Version

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15822]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Androd-style-attribute-not-found-errors-/10451930)._

---
Per Google Play requirements, I updated my Xmarin Forms Target Android version to Android 13.0 (API level 33)

The Android build now breaks with multiple errors such as below.

I have delete obj & bin folders and ensured all nugets are current.

Error APT2260: style attribute 'attr/colorAccent’ … not found

Error APT2260: style attribute 'attr/windowActionModeOverlay’ … not fund

---
#### Feedback Bot on 8/28/2023, 06:30 PM: 

(private comment, text removed)
#### Paul Wang [MSFT] on 8/29/2023, 08:28 PM: 

(private comment, text removed)
#### bill on 9/5/2023, 07:34 AM: 

(private comment, text removed)
#### Feedback Bot on 9/5/2023, 07:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by quintonv** [comment]
I had the same issue, I solved mine by making sure my target and compile SDK were the same. I updated both to API 33 and now it works again.

@jsuarezruiz I think this is a simple fix with the above mentioned

**Comment by jfversluis** [comment]
Yes make sure those are aligned, make sure the targeted SDK is installed on the machine as well of course and then do some clean and rebuilds of the project. Maybe even delete your bin & obj folders. That usually does the trick against caching.
