### ISSUE TITLE
Visual Studio shows errors for popups in error list.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15823]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-shows-errors-for-popups-in/10456096)._

---
Visual studio shows in the error list for each popup an error XFC0000 “Cannot resolve type Popup”.

Xamarin android project.  
Popup is Xamarin.CommunityToolkit.UI.Views.Popup from xamarin community toolkit (a nuget reference).

The build was successful and the app runs fine.  
This issue exists since years.  
See image.

---
#### Feedback Bot on 9/3/2023, 06:43 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
This is unfortunately a long standing issue which is not easily solvable. See more information and fixes/workarounds here: https://github.com/xamarin/XamarinCommunityToolkit/issues/1311
