### ISSUE TITLE
[Bug] Xamarin UiTest Tapping on a Button Takes 2 Minutes When Running Xamarin UiTest on a Mac

### ISSUE THREAD

**Issue by Sht128** [xamarin/Xamarin.Forms#15834]
### Steps to Reproduce

1. Run Test
2. Tap on a button in a page with many elements
3. It is very slow 

### Expected Behavior
Tapping a button shud be fast
### Actual Behavior
It takes 2 and a half minutes to tap on a button
### Basic Information
RUNNING on Pixel 3a API 34 on a Mac
- Version with issue:
- Last known good version:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
Please report to the Xamarin.UITest authors, there is not much we can do about this on our side unfortunately.
