### ISSUE TITLE
[Bug] XF 5.0.0.2612 : a build error for minimum Android API levels 19, 20

### ISSUE THREAD

**Issue by makeman-p81** [xamarin/Xamarin.Forms#15831]
### Description
Can not build Android apps with minimum API levels 19 or 20 since update Xamarin Forms 5.0.0.2612.

### Steps to Reproduce

1. create a blank app
2. set minimum android API level to 19 or 20
3. upgrade Xamarin Forms to version 5.0.0.2612

### Expected Behavior
Successful build

### Actual Behavior
Failed build

### Basic Information

- Version with issue: 5.0.0.2612
- Last known good version: 5.0.0.2578
- Platform Target Frameworks:
  - Android: set min API level 19 or 20

### Build Logs

https://gist.github.com/makeman-p81/1cd12698f83548fe8defc8de9241560c

**Comment by MitchBomcanhao** [comment]
did you read the error messages and do the recommended changes?

**Comment by makeman-p81** [comment]
@MitchBomcanhao 
Does you mean a warning 'NU1605: Detected package downgrade' ?
But it caused by iOS project, not by Android.

**Comment by MitchBomcanhao** [comment]
@makeman-p81 no, read line 110 of the log you posted, and enable multi dex in the android project

**Comment by makeman-p81** [comment]
@MitchBomcanhao 
Thank, it has help me to build app, but before a default value of this option worked correctly for the current case.
Now a release .apk has taken 15.6 Mb (+2 Mb) vs 13.6 Mb on the previous version of XF.

**Comment by jfversluis** [comment]
Looks like this one is solved
