### ISSUE TITLE
Cant compile project with msal and xcode15

### ISSUE THREAD

**Issue by cconner100** [xamarin/Xamarin.Forms#15838]
Hi,

I have a project that compiles with xcode15 and vs2022. This project seems to work on UWP and iOS as expected.

I then added the Microsoft.Identity.Client, compiled with UWP and it works fine but with iOS i get the following error.

9> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(223,3): error : linker command failed with exit code 1 (use -v to see invocation)
9> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(223,3): error : warning: ignoring duplicate libraries: '-lc++', '-lxml2.2', '-lz'
9> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(223,3): error : framework 'System' not found
9> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(223,3): error MT5202: Native linking failed. Please review the build log.

This is with the linker flag set as No Linking and Link only SDK.

But if i set the linker to Link All, while the system compiles, it does not work with anything that uses reflection, it complains with Json.Convert serialize (cant find default constructor for the object)

This is really strange.

It a huge project so its hard to do a sample repro. I can send more build log info but my real concern is why the linker is not finding System.
my build log is attached, this was done using rider but VS, VS Mac and Rider all show the same error

[buildlog.txt](https://github.com/xamarin/Xamarin.Forms/files/13435227/buildlog.txt)

**Comment by jfversluis** [comment]
This probably has to do with the MSAL library rather than with us. Please see if they already have an issue open or open a new one on their repo: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
