### ISSUE TITLE
WebView fails to load from urlwebviewsource with non-ascii characters (works with Uri)

### ISSUE THREAD

**Issue by pfaucon** [xamarin/Xamarin.Forms#1583]
### Description
When loading a WebView with the 'Source' set as a Uri the webview is quite tolerant.  If the 'Source' is setting using a UrlWebviewSource non-ascii characters cause the view to throw an exception

### Steps to Reproduce

1. create a page with a webview
2. set the Source equal to a url with a non-ascii character

example :
```
<WebView x:Name="WebView" HorizontalOptions="FillAndExpand"
                     VerticalOptions="FillAndExpand">
 </WebView>
```

```
WebView.Source = new UrlWebViewSource { Url = "https://www.google.no/maps/place/Skøyen" };
```

### Expected Behavior
it should escape the url as needed and load without exception. When setting the source with a new Uri object it behaves as expected.

### Actual Behavior
Could not initialize an instance of the type 'Foundation.NSUrl': the native 'initWithString:' method returned nil.
It is possible to ignore this condition by setting MonoTouch.ObjCRuntime.Class.ThrowOnInitFailure to false.

### Basic Information

Currently on Xamarin Forms
2.5.0.121934

**Comment by vladbilyk** [comment]
Hmmm, previous behavior (in Forms 2.x) was consistent: URL was not escaped on both platforms (iOS and Android), but now (Forms 3.0) on iOS provided URL is escaped, but on Android - not... It makes me crazy... I prefer the old one...

**Comment by capraynor** [comment]
The webview is not a browser, non-ascii character should escaped by user.
So I think this is not a bug, and should not fix that.
Suggest rollback entire pull request: 
https://github.com/xamarin/Xamarin.Forms/pull/2111

**Comment by rmarinho** [comment]
We are going to rever this fix, @pfaucon I think you will need to encode the url before sending it to forms

**Comment by pfaucon** [comment]
I think the inconsistency argument presented by @vladbilyk is a bit weak, it would not be more difficult to escape both iOS and Android.  

@capraynor's argument is also weak/wrong.  webview is rendererd on iOS using a UIWebView, I don't see a use case where an unescaped url has value, particularly when we know that on iOS it will error out, and the error provided is completely useless.  I'm not certain if Android will auto-escape the URL but it seems unlikely that escaping it will cause harm.

Is there a use case for having an  unescaped url (or errors caused by escaping it)?
