### ISSUE TITLE
Safe spacing not removed on the detail view when the master is opened.

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#1584]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
iPhone X Landscape orientation MasterDetail Page.  When opening the Master the safe space is not removed from the Detail creating a large white space between the Master and Detail sections.
### Steps to Reproduce

1. Run attached test project in landscape orientation on the iPhone X and tap the hamburger icon
2. 
3. 

### Expected Behavior
There should be less white space between the master and detail view, as with previous phones.
### Actual Behavior
There is a large white space between the views, which looks about the same size as the safe area
### Basic Information

- Version with issue:
- Last known good version: none
- IDE: VS2017
- Platform Target Frameworks: 
 - Forms:  2.5.0.122203
  - iOS:  11.2

- Nuget Packages:
- Affected Devices: iPhone X

### Screenshots
iPhone X:
![iphonex_hamburgerspace](https://user-images.githubusercontent.com/1641428/34944723-a911de00-f9ce-11e7-8b52-11c8a0f87410.png)

iPhone 8:
![iphone8_hamburgerspace](https://user-images.githubusercontent.com/1641428/34944705-9bf523a8-f9ce-11e7-8661-c4b21da9e9f3.png)

### Reproduction Link
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1631753/HeaderTest.zip)

**Comment by rmarinho** [comment]
Hi  @ceblanda this is something you will have to handle, i did fix a issue were disabling Safe Areas will return the padding to the correct position. So what you should do is something like this:

Listen to changes in the IsPresented property and toogle UseSafeArea, when you are presenting the master you will set to false the SafeArea and vice versa

```
mdp.PropertyChanged += Mdp_PropertyChanged;
	private void Mdp_PropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
		{
			if(e.PropertyName == MasterDetailPage.IsPresentedProperty.PropertyName)
			{
				((sender as MasterDetailPage).Detail as NavigationPage).CurrentPage.On<iOS>().SetUseSafeArea(!(sender as MasterDetailPage).IsPresented);
			}
			
		}

```

**Comment by ceblanda** [comment]
I'm not delighted :(

First, this does not work properly, the hamburger icon still has the padding.
![image](https://user-images.githubusercontent.com/1641428/40248844-33cd1132-5a9f-11e8-9722-84185179d8f2.png)

Second, why does this have to be handled in every app rather than just once in the framework?
