### ISSUE TITLE
NavigationPage is disguised by Shell

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#15848]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NavigationPage-is-disguised-by-Shell/10538921)._

---
I have replaced Shell with NavigationPage during the project launch process, but I think Shell still exists and NavigationPage is disguised by Shell.  Because the three events of NavigationPage do not work and all the relevant properties of NavigationBar are invalid.
![MauiPageApp04.Error01.png](https://aka.ms/dc/image?name=B075e314a33cd4b189d461e40cbdd97ce638379463009349792_MauiPageApp04.Error01.png&tid=075e314a33cd4b189d461e40cbdd97ce638379463009349792)
![MauiPageApp04.Error02.png](https://aka.ms/dc/image?name=B8bfa7f994a974f70975f97b05d15631a638379463242573921_MauiPageApp04.Error02.png&tid=8bfa7f994a974f70975f97b05d15631a638379463242573921)

---
#### Feedback Bot on 12/11/2023, 08:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Without any relevant code it is hard to determine what is going on here. Since this issue is a while old by now I hope that you have figured it out by now. If not, feel free to open a new issue but please include relevant code snippets or ideally a reproduction project that shows this behavior.
