### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AramMar** [xamarin/Xamarin.Forms#15840]
###IOS App crashes or terminating by ios system.

When we leave app in foreground in some minutes it crashes, there is no any action on it
there is no log neither AppCenter nor Firebase.Crashlatycs. 

Only log that can be helpful is device log

 "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGABRT","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":6,"namespace":"SIGNAL","indicator":"Abort trap: 6","byProc":"***iOS","byPid":14928},

**Comment by jfversluis** [comment]
Unfortunately this has not nearly enough detail to begin to investigate what might be going on here. Let alone to determine if this is a bug in Xamarin.Forms or your own application.

Please try to uncover more details and provide them to us, or provide a reproduction sample that shows this behavior. Thank you and good luck!
