### ISSUE TITLE
[Bug] Xamarin.iOS application crashes on device with test flight version but not with DEBUG version

### ISSUE THREAD

**Issue by manju2305** [xamarin/Xamarin.Forms#15856]
Description
I deployed my iOS application with Release mode from VS for Mac to TestFlight. After installing application on iphone 11 it crashes instantly. I got log from Crashes section of TestFlight but I don't know how it read it.

Expected Behavior
Expected to work.

Actual Behavior
It work with only debug mode, Release deployment with test flight crashes

Basic Information
Version with issue:
Last known good version:
IDE: Visual Studio for Mac 17.6.8
Platform Target Frameworks:
iOS: Xamarin iOS
The crash log:

Incident Identifier: 95079E01-A8C9-43B8-9BE7-A6B2F810A6EA
Hardware Model:      iPhone12,1
Process:             idms.app.iOS [498]
Path:                /private/var/containers/Bundle/Application/86207EA9-EFC6-4B91-88DA-EB48B554FA38/idms.app.iOS.app/idms.app.iOS
Identifier:          com.enerpac.IntegrityAssured-b
Version:             1.1.0 (5.0.1)
AppStoreTools:       15C5500a
AppVariant:          1:iPhone12,1:17
Beta:                YES
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.enerpac.IntegrityAssured-b [655]

Date/Time:           2024-01-23 17:58:10.0780 +0530
Launch Time:         2024-01-23 17:58:09.7078 +0530
OS Version:          iPhone OS 17.2.1 (21C66)
Release Type:        User
Baseband Version:    5.00.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter

Thread 0 name:
Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001fcd3dfbc __pthread_kill + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000021f5eb680 pthread_kill + 268 (pthread.c:1681)
2   libsystem_c.dylib             	0x00000001bd6adb90 abort + 180 (abort.c:118)
3   idms.app.iOS                  	0x0000000107789a38 0x104748000 + 50600504
4   idms.app.iOS                  	0x0000000107651288 0x104748000 + 49320584
5   idms.app.iOS                  	0x00000001075e6380 0x104748000 + 48882560
6   idms.app.iOS                  	0x00000001075e4d54 0x104748000 + 48876884
7   idms.app.iOS                  	0x00000001075daa4c 0x104748000 + 48835148
8   idms.app.iOS                  	0x0000000104d0500c 0x104748000 + 6017036
9   idms.app.iOS                  	0x0000000104aa3b3c 0x104748000 + 3521340
10  idms.app.iOS                  	0x0000000104aa9a64 0x104748000 + 3545700
11  idms.app.iOS                  	0x0000000105e8fdfc 0x104748000 + 24411644
12  idms.app.iOS                  	0x0000000104cc58f0 0x104748000 + 5757168
13  idms.app.iOS                  	0x00000001075f8144 0x104748000 + 48955716
14  idms.app.iOS                  	0x00000001076b1d90 0x104748000 + 49716624
15  idms.app.iOS                  	0x00000001076b55d0 0x104748000 + 49731024
16  idms.app.iOS                  	0x00000001048dc9b0 0x104748000 + 1657264
17  idms.app.iOS                  	0x00000001048e1bc4 0x104748000 + 1678276
18  Foundation                    	0x00000001b468e938 __NSThreadPerformPerform + 264 (NSThread.m:1084)
19  CoreFoundation                	0x00000001b563912c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1957)
20  CoreFoundation                	0x00000001b56383a8 __CFRunLoopDoSource0 + 176 (CFRunLoop.c:2001)
21  CoreFoundation                	0x00000001b5636bbc __CFRunLoopDoSources0 + 340 (CFRunLoop.c:2046)
22  CoreFoundation                	0x00000001b5635898 __CFRunLoopRun + 828 (CFRunLoop.c:2955)
23  CoreFoundation                	0x00000001b5635478 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
24  GraphicsServices              	0x00000001f8b8e4f8 GSEventRunModal + 164 (GSEvent.c:2196)
25  UIKitCore                     	0x00000001b7a5962c -[UIApplication _run] + 888 (UIApplication.m:3685)
26  UIKitCore                     	0x00000001b7a58c68 UIApplicationMain + 340 (UIApplication.m:5270)
27  idms.app.iOS                  	0x000000010777ef10 0x104748000 + 50556688
28  idms.app.iOS                  	0x0000000105f65798 0x104748000 + 25286552
29  idms.app.iOS                  	0x0000000105ec186c 0x104748000 + 24615020
30  idms.app.iOS                  	0x0000000105ec1990 0x104748000 + 24615312
31  idms.app.iOS                  	0x000000010492f084 0x104748000 + 1994884
32  idms.app.iOS                  	0x0000000104cc58f0 0x104748000 + 5757168
33  idms.app.iOS                  	0x00000001075f8144 0x104748000 + 48955716
34  idms.app.iOS                  	0x00000001076b1d90 0x104748000 + 49716624
35  idms.app.iOS                  	0x00000001076b8098 0x104748000 + 49741976
36  idms.app.iOS                  	0x00000001075d6454 0x104748000 + 48817236
37  idms.app.iOS                  	0x0000000107792344 0x104748000 + 50635588
38  idms.app.iOS                  	0x000000010492ee94 0x104748000 + 1994388
39  dyld                          	0x00000001d835adcc start + 2240 (dyldMain.cpp:1269)

Thread 1:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 2:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 3:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 4 name:
Thread 4:
0   libsystem_kernel.dylib        	0x00000001fcd35b1c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000021f5e6fd4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   idms.app.iOS                  	0x0000000107754fb8 0x104748000 + 50384824
3   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
4   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 5 name:
Thread 5:
0   libsystem_kernel.dylib        	0x00000001fcd350f4 semaphore_wait_trap + 8 (:-1)
1   idms.app.iOS                  	0x0000000107654690 0x104748000 + 49333904
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 6 name:
Thread 6:
0   libsystem_kernel.dylib        	0x00000001fcd35178 mach_msg2_trap + 8 (:-1)
1   libsystem_kernel.dylib        	0x00000001fcd34f10 mach_msg2_internal + 80 (mach_msg.c:201)
2   libsystem_kernel.dylib        	0x00000001fcd34e28 mach_msg_overwrite + 436 (mach_msg.c:0)
3   libsystem_kernel.dylib        	0x00000001fcd34c68 mach_msg + 24 (mach_msg.c:323)
4   CoreFoundation                	0x00000001b5637b1c __CFRunLoopServiceMachPort + 160 (CFRunLoop.c:2624)
5   CoreFoundation                	0x00000001b5635a14 __CFRunLoopRun + 1208 (CFRunLoop.c:3007)
6   CoreFoundation                	0x00000001b5635478 CFRunLoopRunSpecific + 608 (CFRunLoop.c:3420)
7   Foundation                    	0x00000001b45c848c -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212 (NSRunLoop.m:373)
8   Foundation                    	0x00000001b45f574c -[NSRunLoop(NSRunLoop) runUntilDate:] + 64 (NSRunLoop.m:420)
9   UIKitCore                     	0x00000001b79bb4a8 -[UIEventFetcher threadMain] + 420 (UIEventFetcher.m:1208)
10  Foundation                    	0x00000001b464bde0 __NSThread__start__ + 732 (NSThread.m:991)
11  libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
12  libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 7:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 8:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 9:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 10:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 11 name:
Thread 11:
0   libsystem_kernel.dylib        	0x00000001fcd35b1c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000021f5e6fd4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   idms.app.iOS                  	0x0000000107764534 0x104748000 + 50447668
3   idms.app.iOS                  	0x000000010770b010 0x104748000 + 50081808
4   idms.app.iOS                  	0x000000010770aee8 0x104748000 + 50081512
5   idms.app.iOS                  	0x000000010770b10c 0x104748000 + 50082060
6   idms.app.iOS                  	0x00000001076f9e14 0x104748000 + 50011668
7   idms.app.iOS                  	0x0000000107675db4 0x104748000 + 49470900
8   idms.app.iOS                  	0x0000000104a39018 0x104748000 + 3084312
9   idms.app.iOS                  	0x0000000104a38b84 0x104748000 + 3083140
10  idms.app.iOS                  	0x0000000104a3868c 0x104748000 + 3081868
11  idms.app.iOS                  	0x0000000104a3863c 0x104748000 + 3081788
12  idms.app.iOS                  	0x0000000104a3853c 0x104748000 + 3081532
13  idms.app.iOS                  	0x0000000104a385e8 0x104748000 + 3081704
14  idms.app.iOS                  	0x0000000104a3b9a4 0x104748000 + 3094948
15  idms.app.iOS                  	0x0000000104a3245c 0x104748000 + 3056732
16  idms.app.iOS                  	0x0000000104a2ff8c 0x104748000 + 3047308
17  idms.app.iOS                  	0x0000000104a2fd8c 0x104748000 + 3046796
18  idms.app.iOS                  	0x0000000104a2fd10 0x104748000 + 3046672
19  idms.app.iOS                  	0x0000000104a325c4 0x104748000 + 3057092
20  idms.app.iOS                  	0x0000000104cc58f0 0x104748000 + 5757168
21  idms.app.iOS                  	0x00000001075f8144 0x104748000 + 48955716
22  idms.app.iOS                  	0x00000001076b1d90 0x104748000 + 49716624
23  idms.app.iOS                  	0x00000001076b772c 0x104748000 + 49739564
24  idms.app.iOS                  	0x00000001076ff9e0 0x104748000 + 50035168
25  idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
26  libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
27  libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 12 name:
Thread 12:
0   libsystem_kernel.dylib        	0x00000001fcd35b1c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000021f5e6fd4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   idms.app.iOS                  	0x0000000107764534 0x104748000 + 50447668
3   idms.app.iOS                  	0x000000010776d29c 0x104748000 + 50483868
4   idms.app.iOS                  	0x00000001076f3a94 0x104748000 + 49986196
5   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
6   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
7   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
8   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 13 name:
Thread 13:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 14 name:
Thread 14:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 15:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 16:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 17:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 18:
0   libsystem_pthread.dylib       	0x000000021f5e79fc start_wqthread + 0 (:-1)

Thread 19 name:
Thread 19:
0   libsystem_kernel.dylib        	0x00000001fcd35b1c __psynch_cvwait + 8 (:-1)
1   libsystem_pthread.dylib       	0x000000021f5e6fd4 _pthread_cond_wait + 1228 (pthread_cond.c:862)
2   idms.app.iOS                  	0x000000010776455c 0x104748000 + 50447708
3   idms.app.iOS                  	0x000000010770b010 0x104748000 + 50081808
4   idms.app.iOS                  	0x000000010770aee8 0x104748000 + 50081512
5   idms.app.iOS                  	0x00000001076a4934 0x104748000 + 49662260
6   idms.app.iOS                  	0x0000000107674398 0x104748000 + 49464216
7   idms.app.iOS                  	0x0000000104a31b48 0x104748000 + 3054408
8   idms.app.iOS                  	0x0000000104a31c00 0x104748000 + 3054592
9   idms.app.iOS                  	0x0000000104a316ec 0x104748000 + 3053292
10  idms.app.iOS                  	0x0000000104a31740 0x104748000 + 3053376
11  idms.app.iOS                  	0x0000000104a2c638 0x104748000 + 3032632
12  idms.app.iOS                  	0x0000000104a2c39c 0x104748000 + 3031964
13  idms.app.iOS                  	0x0000000105927f00 0x104748000 + 18743040
14  idms.app.iOS                  	0x0000000105927cf8 0x104748000 + 18742520
15  idms.app.iOS                  	0x0000000105927c2c 0x104748000 + 18742316
16  idms.app.iOS                  	0x0000000106487e54 0x104748000 + 30670420
17  idms.app.iOS                  	0x0000000104a3245c 0x104748000 + 3056732
18  idms.app.iOS                  	0x0000000104a2ff8c 0x104748000 + 3047308
19  idms.app.iOS                  	0x0000000104a2fd8c 0x104748000 + 3046796
20  idms.app.iOS                  	0x0000000104a2fd10 0x104748000 + 3046672
21  idms.app.iOS                  	0x0000000104a325c4 0x104748000 + 3057092
22  idms.app.iOS                  	0x0000000104cc58f0 0x104748000 + 5757168
23  idms.app.iOS                  	0x00000001075f8144 0x104748000 + 48955716
24  idms.app.iOS                  	0x00000001076b1d90 0x104748000 + 49716624
25  idms.app.iOS                  	0x00000001076b772c 0x104748000 + 49739564
26  idms.app.iOS                  	0x00000001076ff9e0 0x104748000 + 50035168
27  idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
28  libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
29  libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 20 name:
Thread 20:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 21 name:
Thread 21:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 22 name:
Thread 22:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 23 name:
Thread 23:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 24 name:
Thread 24:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 25 name:
Thread 25:
0   libsystem_kernel.dylib        	0x00000001fcd3510c semaphore_timedwait_trap + 8 (:-1)
1   idms.app.iOS                  	0x00000001076f434c 0x104748000 + 49988428
2   idms.app.iOS                  	0x00000001076ff8e8 0x104748000 + 50034920
3   idms.app.iOS                  	0x00000001076ff76c 0x104748000 + 50034540
4   libsystem_pthread.dylib       	0x000000021f5e84d4 _pthread_start + 136 (pthread.c:904)
5   libsystem_pthread.dylib       	0x000000021f5e7a10 thread_start + 8 (:-1)

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000022   x5: 0x000000010ae98800   x6: 0x0000000000001000   x7: 0xffffffff00000600
    x8: 0x2a44964933437989   x9: 0x2a44964b35c43289  x10: 0x00000000000002ee  x11: 0x0000000000000000
   x12: 0x000000010ad86600  x13: 0x00000001082d79cb  x14: 0x00000000000000e0  x15: 0x0000000080000000
   x16: 0x0000000000000148  x17: 0x0000000206874b00  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x0000000000000103  x21: 0x0000000206874be0  x22: 0x0000000000000000  x23: 0x000000010a820600
   x24: 0x00000001082d79c8  x25: 0x000000016b6b4fa0  x26: 0x0000000000000002  x27: 0x0000000107b32960
   x28: 0x0000000000ffffff   fp: 0x000000016b6b41a0   lr: 0x000000021f5eb680
    sp: 0x000000016b6b4180   pc: 0x00000001fcd3dfbc cpsr: 0x40000000
   esr: 0x56000080  Address size fault

Binary Images:
        0x104748000 -         0x1078e7fff idms.app.iOS arm64  <bef94412efac3e34a4bf716c0eb83791> /private/var/containers/Bundle/Application/86207EA9-EFC6-4B91-88DA-EB48B554FA38/idms.app.iOS.app/idms.app.iOS
        0x107da8000 -         0x107de7fff DXGrid arm64  <95813323f6c63a1792fde7a92b3fa813> /private/var/containers/Bundle/Application/86207EA9-EFC6-4B91-88DA-EB48B554FA38/idms.app.iOS.app/Frameworks/DXGrid.framework/DXGrid
        0x107e78000 -         0x107ef7fff DXEditors arm64  <914fbc2e896b36c3be3fbe7a430436ed> /private/var/containers/Bundle/Application/86207EA9-EFC6-4B91-88DA-EB48B554FA38/idms.app.iOS.app/Frameworks/DXEditors.framework/DXEditors
        0x10800c000 -         0x10802ffff DXListView arm64  <9b111686a33f319f8443fd5c76cd2e5d> /private/var/containers/Bundle/Application/86207EA9-EFC6-4B91-88DA-EB48B554FA38/idms.app.iOS.app/Frameworks/DXListView.framework/DXListView
        0x10d864000 -         0x10d86ffff libobjc-trampolines.dylib arm64e  <26d68e81199a300dbc1530ba4630a611> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
        0x1b459c000 -         0x1b50fbfff Foundation arm64e  <c52a963060f13d48a6c350a20de78c6a> /System/Library/Frameworks/Foundation.framework/Foundation
        0x1b5602000 -         0x1b5b2efff CoreFoundation arm64e  <be405d8a546437a3a17e1068db404b23> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
        0x1b782d000 -         0x1b9302fff UIKitCore arm64e  <99ad2a319360369f9c0ba7a0af33e2e7> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
        0x1bd638000 -         0x1bd6b5ff3 libsystem_c.dylib arm64e  <6e5a7692c1e935adb20bc307991df11c> /usr/lib/system/libsystem_c.dylib
        0x1d8355000 -         0x1d83dcb5b dyld arm64e  <630c2209dfd73c72b0a9e856c560f123> /usr/lib/dyld
        0x1f8b8b000 -         0x1f8b93fff GraphicsServices arm64e  <7d6f670c0e4b32158b4e599ef1ab9ed2> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
        0x1fcd34000 -         0x1fcd6cfef libsystem_kernel.dylib arm64e  <55f2cc41248837bdbb95ea2ffd7611ae> /usr/lib/system/libsystem_kernel.dylib
        0x21f5e6000 -         0x21f5f1ff3 libsystem_pthread.dylib arm64e  <e9ae8dcfc2b635d7af24e008b8034e31> /usr/lib/system/libsystem_pthread.dylib

EOF

**Comment by themronion** [comment]
same, crashing after upgrade to xcode 15.1. @rolfbjarne Are there any Xamarin.iOS updates available?

**Comment by rolfbjarne** [comment]
@themronion this is the latest:

https://github.com/xamarin/xamarin-macios/releases/tag/xamarin-ios-16.4.0.23

If you think this is a bug in Xamarin.iOS, please file an issue in https://github.com/xamarin/xamarin-macios/issues/new, and we'll have a look.

**Comment by themronion** [comment]
Gotcha, will downgrade xcode for now

**Comment by manju2305** [comment]
We have succefully cracked the issue, this issue was because of the Babel package which we have used in our APP. When we were pushing the release to Testflight Babel package was enabled and during debug mode , it was switched off. Had to do some Babel configuration changes to fix this issue.

I'm using the Xcode 15.1 , visual studio for MAC version 17.6.8 , xamarin IOS SDK version 17.2
