### ISSUE TITLE
Unable to build Android custom renderers with latest Xamarin.Forms version

### ISSUE THREAD

**Issue by kkohler2** [xamarin/Xamarin.Forms#15857]
### Description
Unable to upgrade to latest version of Xamarin.Forms due to compilation issues after upgrade with custom renderers.

### Steps to Reproduce
1.  Take a working Xamarin.Forms project with a custom Entry renderer and upgrade the the latest version of Xamarin.Forms
2.  Attempt to build the project

### Expected Behavior
Project will build and run as expected

### Actual Behavior
Project does not build.  

### Basic Information
Only change I made to functional app was upgrading Xamarin.Forms version from 5.0.0.2578 to 5.0.0.2622

- Version with issue: 5.0.0.2612 and 5.0.0.2622
- Last known good version: 5.0.0.2578
- Platform Target Frameworks: 
  - Android: Android 10.0
 - Android Support Library / AndroidX Version: 
- NuGet Packages: None
- Affected Devices: All Android

### Environment
Visual Studio 17.8.3

### Build Logs
![image](https://github.com/xamarin/Xamarin.Forms/assets/9455088/d336f4a6-0f1f-46ec-93be-d859fbeb9ad5)

### Reproduction Link

Using the example repository for Xamarin.Forms custom renderers, upgrade to latest version of Xamarin.Forms and try to build.  No other changes are necessary to reproduce.  Last two versions of Xamarin.Forms have this breaking change.
https://github.com/xamarin/xamarin-forms-samples/tree/main/CustomRenderers

### Workaround

Use Xamarin.Forms 5.0.0.2578 or earlier

**Comment by jfversluis** [comment]
That is the version that bumped the target to Android 13. You will have to update the target framework version as outlined in the [release notes](https://github.com/xamarin/Xamarin.Forms/releases/tag/release-5.0.0-sr15). When doing that, the sample builds and works as expected.
