### ISSUE TITLE
After installing the "Miicrosoft.UI.XAML"  NuGet package on UWP platform. The Xamarin Button control style was changed.

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#15854]
After installing the "Miicrosoft.UI.XAML"  NuGet package on UWP platform. The Xamarin Button control style was changed.

### Steps to Reproduce

1. Run the sample
2. you can see after installing the "Miicrosoft.UI.XAML"  NuGet package the button style was changed.

### Basic Information

- Version with issue:
- Last known good version:
- Platform Target Frameworks: UWP
- NuGet Packages: Miicrosoft.UI.XAML

### Screenshots

Without **"Miicrosoft.UI.XAML"**  NuGet package 
![image](https://github.com/xamarin/Xamarin.Forms/assets/87415471/4c8068e6-2d33-4c57-ae21-8b96825c6853)

With **"Miicrosoft.UI.XAML"**  NuGet package 
![image](https://github.com/xamarin/Xamarin.Forms/assets/87415471/daf756b0-36bb-4ba7-b79d-dfa4d9fad36d)

### Sample Link

With **"Miicrosoft.UI.XAML"**  NuGet package 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/XamarinUWP2-1969763199 

Without **"Miicrosoft.UI.XAML"**  NuGet package 
https://www.syncfusion.com/downloads/support/directtrac/general/ze/XamarinUWP2029506082

**Comment by ghost** [comment]
Any updates?

**Comment by jfversluis** [comment]
That is something that comes with WinUI, they implemented a new style which is backwards compatible, so when you install that it will show up in your app. I think there is documentation [here ](https://learn.microsoft.com/windows/apps/design/style/xaml-styles)on how to revert to the old styling if that's what you want.

There is not much we can do about this from our side.
