### ISSUE TITLE
Apps are crashing after installing ASP.NET Web (comes with .NET Core 2.0) in VS2017 all of a sudden my Xamarin Forms Apps start to crash 

### ISSUE THREAD

**Issue by StanleyBroo** [xamarin/Xamarin.Forms#1585]
Apps are crashing after installing ASP.NET Web (comes with .NET Core 2.0) in VS2017 all of a sudden my Xamarin Forms Apps starts to crash ?

It does not have to do with Xamarin Forms .nuget versions. Have tried old commits/branschen, same crash.

What is the relation to .NET Core 2.0 ?

Crash report in App Center:
Object reference not set to an instance of an object.
1
VisualElement.get_BackgroundColor () D:\agent\_work\1\s\Xamarin.Forms.Core\VisualElement.cs:140
2
BoxRenderer.UpdateBackgroundColor () D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\BoxRenderer.cs:54
3
VisualElementRenderer`1[TElement].OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:273
4
BoxRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\BoxRenderer.cs:43
5
(wrapper delegate-invoke) .invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
6
BindableObject.OnPropertyChanged (System.String propertyName) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:138
7
Element.OnPropertyChanged (System.String propertyName) D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:401
8
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:594
9
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391
10
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:174
11
BindingExpression.Apply (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property) D:\agent\_work\1\s\Xamarin.Forms.Core\BindingExpression.cs:77
12
Binding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty) D:\agent\_work\1\s\Xamarin.Forms.Core\Binding.cs:126
13
BindableObject.ApplyBindings (System.Boolean skipBindingContext) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:422
14
BindableObject.ApplyBindings () D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:126
15
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:120
16
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511
17
Element.OnBindingContextChanged () D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354
18
View.OnBindingContextChanged () D:\agent\_work\1\s\Xamarin.Forms.Core\View.cs:99
19
Grid.OnBindingContextChanged () D:\agent\_work\1\s\Xamarin.Forms.Core\Grid.cs:147
20
BindableObject.SetInheritedBindingContext (Xamarin.Forms.BindableObject bindable, System.Object value) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:121
21
Element.SetChildInheritedBindingContext (Xamarin.Forms.Element child, System.Object context) D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:511
22
Element.OnBindingContextChanged () D:\agent\_work\1\s\Xamarin.Forms.Core\Element.cs:354
23
Cell.OnBindingContextChanged () D:\agent\_work\1\s\Xamarin.Forms.Core\Cells\Cell.cs:114
24
BindableObject.BindingContextPropertyChanged (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:442
25
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:597
26
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:391
27
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:544
28
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:84
29
BindableObject.set_BindingContext (System.Object value) D:\agent\_work\1\s\Xamarin.Forms.Core\BindableObject.cs:25
30
TemplatedItemsList`2[TView,TItem].UpdateContent (TItem content, System.Int32 index, System.Object item) D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:614
31
TemplatedItemsList`2[TView,TItem].UpdateContent (TItem content, System.Int32 index) D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:629
32
ITemplatedItemsList<TItem>.UpdateContent (TItem content, System.Int32 index) D:\agent\_work\1\s\Xamarin.Forms.Core\TemplatedItemsList.cs:633
33
ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:256
34
BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent)
35
(wrapper dynamic-method) System.Object.a9fa4d81-7407-4be1-9e12-91d37e82176a(intptr,intptr,int,intptr,intptr)
Xamarin.Forms.BindableProperty targetProperty) D:\agent\_work\1\s\Xamarin.Forms.Core\Binding.cs:126

**Comment by StephaneDelcroix** [comment]
Could you please give us more info:
- the version of XF you're running
- does it happens with the latest version of XF
- we can not reproduce this bug with the information you shared. could you please attach the smallest possible project that triggers the issue ?

Thanks

**Comment by samhouts** [comment]
@StanleyBroo Please reopen this issue if you are able to provide the information requested by Stephane. Thank you!
