### ISSUE TITLE
[Enhancement] Add more descriptive exception for route not found (Shell.Current.GoToAsync).

### ISSUE THREAD

**Issue by crwsolutions** [xamarin/Xamarin.Forms#15865]
When no route is found, the followin exception is thrown.

`Relative routing to shell elements is currently not supported. Try prefixing your uri with ///: ///{originalRequest}`

Because you are led astray by the hints in some situations I would therefore like to add global routing via Routing.RegisterRoute().

When I am on it I don't think that the first sentence is very helpful either. Because it's not entirely clear in some situations what it refers to. So I rather have something like  'Route not found.'

So my suggestion would be to rewrite it to (I removed originalRequest because in my case that is very long and that could  lead to TLDR;):

`Route not found. Possible solutions could be prefixing your uri with '//' or '///' to use relative routing or register the route as global route for detail page routing.`

This refers to:  

https://github.com/xamarin/Xamarin.Forms/blob/88b70ad2824a4f40fa2ef056439ada9dc3e85ab4/Xamarin.Forms.Core/Shell/ShellUriHandler.cs#L394

Navigation docs: https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation?view=net-maui-8.0

**Comment by jfversluis** [comment]
Thanks for the suggestion! This is probably not something we're going to add for Xamarin.Forms anymore since it will go out of support on May 1st. You're welcome to open this suggestion for .NET MAUI if this is still something that needs improvement over there as well!

**Comment by crwsolutions** [comment]
Copied the issue more or less to .Net maui https://github.com/dotnet/maui/issues/20902
