### ISSUE TITLE
[Bug] Xamarin Splash screen not visible turns out black in iOS

### ISSUE THREAD

**Issue by PramodMAUI** [xamarin/Xamarin.Forms#15867]
### Steps to Reproduce

1.  Create a sample app in Xamarin.Forms from windows machine 
2.  Connect to Mac machine with Xcode installed
3. Deploy on simulator or physical device

### Expected Behavior
Splash screen should appear with blue background and Xamarin X logo
### Actual Behavior
Displying black screen
### Basic Information

- Version with issue: Xcode above 14
- Last known good version:
- Platform Target Frameworks: Xamarin.iOS
  - iOS:  iOS 16.4 and 17

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
Probably due to this: https://github.com/xamarin/xamarin-macios/issues/18777 if you create a release version it should work.

**Comment by PramodMAUI** [comment]
We are facing this issue in release mode as well. Getting white screen.
