### ISSUE TITLE
[Bug] App is frozen when resumed (Android)

### ISSUE THREAD

**Issue by AlleSchonWeg** [xamarin/Xamarin.Forms#15860]
### Description
Hi,
sometimes my app is frozen when it restored from the recent apps. It doesn't react on user input. I see the page content but i can't scroll or click buttons. 

When i move my finger on the frozen screen my logcat produces this messages:

> 02-14 14:56:59.007	unknown Phh-Treble with GApps	Info	1357	InputDispatcher	Dropping event because there is no touched foreground window in display 0 or gesture monitor to receive it.

### Steps to Reproduce

No steps. It happens randomly

### Expected Behavior
Not freeze

### Actual Behavior
Freeze

### Basic Information

- Version with issue: 5.0.0.2622
- Last known good version:
- Platform Target Frameworks: 
  - Android: 12.1
- Android Support Library / AndroidX Version: 
- NuGet Packages:
- Affected Devices:

### Environment

<details><summary>Show/Hide Visual Studio info</summary>

```
```

</details>

**Comment by jfversluis** [comment]
Thanks for the report but without any code, logs, repro or anything it's near impossible to diagnose what might be going on here. It might just as well be a third-party library or your own code that is triggering this. Happy to have a look when you have more results from any investigation you might do, but with this there is not much I can do here, unfortunately.
