### ISSUE TITLE
wpf stacklayout  WidthRequest adds unwanted margin

### ISSUE THREAD

**Issue by maxvodoo** [xamarin/Xamarin.Forms#1588]
### Description
when setting stacklayout  WidthRequest it adds unwanted margin 

### Expected Behavior
stacklayout without the extra margin

### Actual Behavior
stacklayout with extra margin
### Basic Information

- Version with issue: xamarin.forms 2.6.0.91472-nightly
- IDE: vs2017
- Platform: WPF
- Affected Devices: Windows 10

### Screenshots

![wpf](https://user-images.githubusercontent.com/10313439/34965043-ef8227b0-fa59-11e7-8f45-9bf34c2fa223.jpg)

**Comment by mohachouch** [comment]
Hi, you can send an sample project. Thanks

**Comment by maxvodoo** [comment]
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/1634479/Test.zip)

**Comment by mohachouch** [comment]
I am currently investigating the bug. But I have some question. 

You have set the value 300 (WidthRequest) to each StackLayout but at the same time you have left the default value HorizontalOptions to FillAndExpand

I tried on UWP the application no longer uses the WidthRequest value if HorizontalOptions is on FillAndExpand. (see screeshot)

I think it's a bit contradictory it's two parameters. At first I advise you to use the Start or End value for HorizontalOptions.

Below the window with 3 stacklayouts:
- First: HorizontalOptions = "FillAndExpand"
- Second: HorizontalOptions = "Start"
- Third: HorizontalOptions = "End"

![image](https://user-images.githubusercontent.com/25939826/35007915-38b7038c-fafb-11e7-8eed-6e6a63333f19.png)

**Comment by maxvodoo** [comment]
You are absolutely right, my real problem I was using a custom layout, (WarpLayout) the source is included in the sample but I excluded it for clarity, if I set HorizontalOptions = "Start", I can't resize the StackLayout beyond the requested width when calling LayoutChildIntoBoundingRegion.

**Comment by mohachouch** [comment]
I can not find the WrapLayout in the test project could send me an example with the WrapLayout.

**Comment by maxvodoo** [comment]
very sorry for the late response, i attached a new solution includes WarpLayout and a UWP project for comparison  
[TestUi.zip](https://github.com/xamarin/Xamarin.Forms/files/1648244/TestUi.zip)

**Comment by mohachouch** [comment]
I will analyze the bug. 

You can replace the HorizontalOptions value with Start to get the same result as on UWP.

I know it's not a real solution but it can help you at first
