### ISSUE TITLE
Should the local variable be used instead of the property

### ISSUE THREAD

**Issue by PBro777** [xamarin/Xamarin.Forms#1591]
A local variable was created for the LogicalChildrenInternal however in line 318 the property is being used instead of the local variable?

https://github.com/xamarin/Xamarin.Forms/blob/f9b27a2edfa2126824f4b41e2712d283eaad50b4/Xamarin.Forms.Core/Layout.cs#L314-L318

I just game a cross this code when looking after multi-thread issue that we are facing in our code.

**Comment by StephaneDelcroix** [comment]
this hardly qualifies as a bug. A missed opportunity? yes. A source of potential bug? yes. An actual bug ? no. That would affect performance by a measurable margin ? no.

**Comment by adrianknight89** [comment]
Not sure what's the verdict on this (i.e. bug or no bug), but I saved you the effort of writing up a PR.
