### ISSUE TITLE
[Proposal] Allow us to see UI test results when a PR is pushed

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#1597]
### Description

Running UI tests on different devices, platforms, and API levels before submitting a PR is not possible for most of us, so we can't always know what existing tests we're breaking if any, and we rely on the team members telling us which tests are broken.

![capture](https://user-images.githubusercontent.com/16855542/35061674-91e0cf10-fb87-11e7-8481-bd38acbb7aad.PNG)

Clicking on 'Details' shows a 401 page. Can the community have read access to UI test results? I'm not sure what information is available on the Details pages, but I assumed they would show the result for each test run.

**Comment by StephaneDelcroix** [comment]
@rmarinho is there anything we can do here ?

**Comment by rmarinho** [comment]
Sorry nothing we can do here, we could basically add a comment with the failed issues but there's no way to add a guest view to VSTS or to TestCloud.

The Details link takes you to the build on VSTS
