### ISSUE TITLE
Command Binding doesn't work .NET Standard

### ISSUE THREAD

**Issue by ConX-Ryan** [xamarin/Xamarin.Forms#1599]
### Description
Basic command binding fails when debugging android devices 
### Steps to Reproduce

1.  create new master detail template project using .NET standard
2.  install package Microsoft.EntityFrameworkCore.Sqlite and make the work around so you can deploy
3.  navigate to about page and click button

### Expected Behavior
Command function should be called
### Actual Behavior
01-18 13:22:13.145 D/ViewRootImpl@770e4f0[MainActivity]( 8796): ViewPostImeInputStage processPointer 0
01-18 13:22:13.221 D/ViewRootImpl@770e4f0[MainActivity]( 8796): ViewPostImeInputStage processPointer 1

but no command is fired

### Basic Information

- Version with issue: 
API 21-24
XF 2.5.0.12203
.NET Standard 2.0
- Last known good version: N/A
- IDE: VS 15.5.4
- Platform Target Frameworks: 
  - iOS: N/A
  - Android: Oreo 
  - UWP:   16299 
- Android Support Library Version: 
- Nuget Packages: Microsoft.EntityFrameworkCore.Sqlite
- Affected Devices: Many

**Comment by StephaneDelcroix** [comment]
Thanks for this report. I have a few questions:
 - how is `Microsoft.EntityFrameworkCore.Sqlite` relevant to this ?
 - could you please attach the simplest possible project that triggers this issue ? (ideally with no des on SF.Sqlite) ?

Thanks

**Comment by ConX-Ryan** [comment]
Hi this is triggered when `Microsoft.EntityFrameworkCore.Sqlite` is included and the workaround for the `System.Runtime.CompilerServices.Unsafe` asm is applied so you can deploy to an android device.

Before that the command binding works when deployed after that it is in the buggy state.

**Comment by StephaneDelcroix** [comment]
see also https://github.com/xamarin/xamarin-android/issues/1196

(probably not XF related)

**Comment by ConX-Ryan** [comment]
Hey Stephane that workaround has the old style project not the new style and isn't a .NET standard project.

I cant see how this can be closed if the .NET Standard code share method is broken

**Comment by berndu** [comment]
The strange thing here is - this works with Xamarin.Forms.2.5.0.280555 but does not work with 2.5.1.444934 - so there must be a relation from the Xamarin.Forms version...
