### ISSUE TITLE
Exception thrown when `Removing Content Using LayoutCompression

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#1601]
### Description

When using LayoutCompression on Views. Either removing the View using `Root.Children.Remove(myGrid);` or clearing content `this.Content = null;` throws a "object Refrence not set exception"

### Steps to Reproduce

1. open sample app [lct.zip](https://github.com/xamarin/Xamarin.Forms/files/1642678/lct.zip)

2.  Run app on Android (havent tested other platforms) and press either button at bottom of page and BANG

### Expected Behavior
Don't throw exception

### Actual Behavior
Crash

### Basic Information

- Version with issue: V.2.5.1222

**Comment by JKennedy24** [comment]
Any update on this? I see it's been marked as "Critical". It makes LayoutCompression unusable untill this is fixed, which is a shame

**Comment by jassmith** [comment]
@JKennedy24 was just working on that this morning actually, fixed :)

**Comment by JKennedy24** [comment]
@jassmith Awesome, Thanks! I'll try it out when I see it's released and feed back if I get any problems
