### ISSUE TITLE
[UWP] Page.Disappearing is raised on the root page of a NavigationPage

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#1602]
### Description

The Disappearing event of the root page in a NavigationPage is raised when opening it.

### Steps to Reproduce

1. In App.xaml.cs: MainPage = new NavigationPage(new MainPage());
2. In MainPage.xaml.cs: this.Disappearing += (s, e) => Debug.WriteLine("MainPage Disappearing");

### Expected Behavior

When the app opens, the line "MainPage Disappearing" should NOT be written to the Debug window.

### Actual Behavior

The event is raised.

### Basic Information

- Version with issue: 2.5.0.19271-pre2 up to 2.5.0.122203
- Last known good version: 2.4.0.91020
- Platform Target Frameworks:
  - UWP: 16299

### Reproduction Link

[UWP_PageDisappearing.zip](https://github.com/xamarin/Xamarin.Forms/files/1642739/UWP_PageDisappearing.zip)

The bug is already confirmed on [bugzilla #60589](https://bugzilla.xamarin.com/show_bug.cgi?id=60589) including another repro project but I didn't find it on GitHub.

**Comment by rmarinho** [comment]
Fixed by #1634
