### ISSUE TITLE
WCF service integration does not work with Visual Studio 2017 15.5.4

### ISSUE THREAD

**Issue by rob2212** [xamarin/Xamarin.Forms#1606]
### Description

When you create a new Xamarin Project in Visual Studio 2017 using .Net Standard libraries, the access to a WCF web service does no longer work. Even the example project by Xamarin does produce the same issue.

### Steps to Reproduce

1. Download the Xamarin example: https://developer.xamarin.com/guides/xamarin-forms/cloud-services/consuming/wcf/
2. Build with Visual Studio 2017 15.5.4
3. Run Android App on a real device

### Expected Behavior
Method call to web service works (method: SoapService.RefreshDataAsync)

### Actual Behavior
Exception: The message with Action '' cannot be processed at the receiver, due to a ContractFilter mismatch at the EndpointDispatcher. This may be because of either a contract mismatch (mismatched Actions between sender and receiver) or a binding/security mismatch between the sender and the receiver.  Check that sender and receiver have the same contract and the same binding (including security requirements, e.g. Message, Transport, None).

### Basic Information

- IDE: Visual Studio 2017 15.5.4
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Android SDK 7.1
  - UWP:  Not tested
- Android Support Library Version: 
- Affected Devices: Samsung Galaxy Tab A (2016)

**Comment by jassmith** [comment]
WCF services are not part of the Xamarin.Forms project. You will need to refile this with the correct project. It looks like you will want to file against the Xamarin.Android https://github.com/xamarin/Xamarin-Android/issues
