### ISSUE TITLE
[macOS] NavigationBar of Modal overlap content with FullSizeContentView & TitlebarAppearsTransparent

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#1608]
### Description
`NavigationBar` of Modal overlap content when `MainWindow.StyleMask |= NSWindowStyle.FullSizeContentView` and `MainWindow.TitlebarAppearsTransparent = true`.

### Steps to Reproduce

1. Set `MainWindow.StyleMask |= NSWindowStyle.FullSizeContentView` and `MainWindow.TitlebarAppearsTransparent = true` on AppDelegate constructor.
2. Call `Navigation.PushModalAsync` with `NavigationPage`

### Actual Behavior
- Content in top of modal is overlapped by NavigationBar
- When Modal is removed, the statusbar is no longer transparent. The color of the statusbar is the same as the NavigationBar of the removed modal

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.122203
- IDE: Visual Studio for Mac 7.3.3 (build 5)
- Platform Target Frameworks:
  - macOS:  10.13.2

**Comment by rmarinho** [comment]
Hum, I m thinking if and how we should fix this. 

1 - Hide the navigation bar when using those 2 properties?

2 - Need to layout the content below the navigation bar, but that will go against UIKit and the user could want to overlap the navigationbar.

3 - No fix, the user should use padding on the page.

**Comment by YZahringer** [comment]
I think that solution 2 is better. The NavigationBar overlaps the child content, it sould be displayed correctly regardless of the window properties.

For solution 1, why use NavigationPage if you do not want to display NavigationBar?

**Comment by rmarinho** [comment]
@YZahringer what if a user wants to for example make a scrollview go below the NavigationBar?
About solution 1 , user uses a NavigationPage because he wants to still navigate between pages, but for example is drawing the navigation buttons himself on the pages.

**Comment by YZahringer** [comment]
I think that in the solution 1 it will do `NavigationPage.SetHasNavigationBar(this, false);` to hide the navigation bar.

When the NavigationBar is displayed, the behavior should be the same with/without `MainWindow.StyleMask |= NSWindowStyle.FullSizeContentView` & `MainWindow.TitlebarAppearsTransparent = true`. Why the content is only overlapped with these properties.

**Comment by titoleru** [comment]
Hiding the navigation is not a solution to this, just a workaround...

The question here is how to address number 2:

2 - Need to layout the content below the navigation bar (using a StackLayout or a Grid)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
