### ISSUE TITLE
FragmentContainer error using Android 8.1 and Support 27.0.2

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#1609]
### Description
In testing the upcoming 27.0.2 support libraries with Android 8.1, the application crashes.

```can't make objects of type android.support.v4.app.FragmentPagerAdapter: 0x132df2c8```

https://gist.github.com/Redth/2766ece9d75a9247a61adeda625e8b59

### Steps to Reproduce

1. File > New > Xamarin.Forms App (not the blank)
2. Update the project to framework 8.1
3. Update the Android libs to 27.0.2 (see @davidortinau for the feed)
4. Run and observe

### Expected Behavior
The application runs and can navigate tabs.

### Actual Behavior
Crashes on startup.

### Basic Information

- Version with issue: 2.5.0
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 27.0.2

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1644087/Archive.zip)

**Comment by hartez** [comment]
@davidortinau Which version of VS are you using?

**Comment by davidortinau** [comment]
@hartez VS Mac 7.4, Alpha channel

https://gist.github.com/davidortinau/aeaec4fa2b6d50590fdf5773203f5a74

**Comment by igorfel** [comment]
@davidortinau i've been facing the same problem, as a work around i've switched to stable channel and now it's working just fine. I'm using windows, i don't know if this will help on mac

**Comment by Redth** [comment]
This is apparently already fixed and will be part of 15.6 P4 release.
