### ISSUE TITLE
[iOS] When dynamically creating a container and putting the current page content into a child of the new container, current page controls become unresponive

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#1611]
### Description
From person who reported the issue to me:
"I was trying to dynamically create a grid and add the current content on the page inside the just created grid and then update the page content to be the grid.
Visually it works fine, but if I try to interact with the controls, none of them are responsive to any click/touch

Here is a sample code of what I am doing:

    var grid = new Grid
    {
          RowSpacing = 0,
          RowDefinitions =
        {
               new RowDefinition { Height= new GridLength (1, GridUnitType.Star) },
               new RowDefinition { Height = new GridLength (1, GridUnitType.Auto) }
        }
    };
 
     this.pageGridContent.Children.Add(this.Content, 0, 0);
     this.pageGridContent.Children.Add(anotherControl, 0, 1);
 
     this.Content = grid;"

### My findings

I created a test project to reproduce the issue and I found that:
1. This issue occurs if using a Grid or a StackLayout for the new container.
2. Issue occurs only on iOS (does not occur on Android, and I did not test UWP)

### Steps to Reproduce

1. Open the attached test solution. 
2. Run on an iOS simulator (tested on iPhone 8 simulator running iOS 11.2)
3. Click on the "Put me in a new container XAML" button. Note the "New Button 1" button is added to the bottom.
4. Click on the "Put me in a new container XAML" button again.

### Expected Behavior
A "New Button 2" button should be added to the bottom. 

### Actual Behavior
Nothing happens. Click event handler is not fired.

### Notes
There is some commenting in the test project that shows some things I tried to figure out what was going on. e.g. I tried with a stacklayout as well as a grid and got the same results. I also tried to see what happened if I did not re-use the initial StackLayout but created a new, identical (except for the button text) layout to add as a child to the new grid. The issue did not occur when doing this. To test, comment out line 54 in **TestGridInGridPage.xaml.cs" and uncomment lines 57-60 and 72. 

Also worth noting is that the latest newly created StackLayout with the "New Button #" always works, i.e. its click event handler is always fired... but any buttons that were in this.Content do not work and do not fire their click event handlers (in the sample all buttons fire the same event handler that creates the new grid and adds this.Content and the new StackLayout to the grid). 

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: None
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 7.1
  - UWP:  n/a
- Android Support Library Version: 25.4.0.2
- Nuget Packages: Nothing other than what X.Forms adds as dependencies.
- Affected Devices: Tested on iOS Simulator iPhone 8 iOS 11.2

### Test Project
[TestGridInGrid.zip](https://github.com/xamarin/Xamarin.Forms/files/1644578/TestGridInGrid.zip)

**Comment by gugavaro** [comment]
Thank you so much @jgold6 for getting this issue logged.

**Comment by StephaneDelcroix** [comment]
at some point in your sample, `this.Content` is present as children of 2 collections. I guess this causes that.

**Comment by gugavaro** [comment]
Hi @StephaneDelcroix , you are right on!!!
As a work around I tried to do the following:

var grid = new Grid
{
      RowSpacing = 0,
      RowDefinitions =
    {
           new RowDefinition { Height= new GridLength (1, GridUnitType.Star) },
           new RowDefinition { Height = new GridLength (1, GridUnitType.Auto) }
    }
};

**var tempContent = this.Content;
this.Content = null;**

this.pageGridContent.Children.Add(tempContent, 0, 0);
this.pageGridContent.Children.Add(anotherControl, 0, 1);

this.Content = grid;"

With those changes it works perfectly! For some reason on Android this workaround is not necessary.
Hopefully it will be an easy fix for us to get in.

thank again,
Gustavo.

**Comment by samhouts** [comment]
Since there's a workaround for this issue, I will close it now. Thank you!
