### ISSUE TITLE
No way to do hardware accelerated graphics on UWP

### ISSUE THREAD

**Issue by j4m3z0r** [xamarin/Xamarin.Forms#1612]
### Description

At present there is no way to do OpenGL or DirectX on Xamarin.Forms UWP applications, though there is on the various mobile platforms, and it looks like Xamarin.Forms.Mac has a WIP OpenGLView.

### Steps to Reproduce

1. Try to create a Xamarin.Forms UWP application with hardware accelerated 3D graphics
2. Fail.

### Expected Behavior

My understanding is that UWP does not have native OpenGL, so I acknowledge that there is some subtlety as to the correct way to proceed. However, I would find either of the following to be something that I can work with:

* Implement OpenGLView on UWP, using Microsoft's ANGLE port for UWP: https://github.com/Microsoft/angle -- this code is already on nuget [here](https://www.nuget.org/packages/ANGLE.WindowsStore). The benefit of this is that it would allow deployment to UWP systems without having to re-write the rendering layer. ANGLE powers WebGL on Windows platforms and has proven itself fairly robust there, so I don't foresee any substantial issues with compatibility to the GL API.
* Implement a "Direct3dView" or similar for UWP only, which would allow 3D rendering using [SharpDX](http://sharpdx.org/). Having to maintain a separate rendering layer for UWP isn't ideal, but certainly a better option than just foregoing UWP altogether.

I think for most purposes, it would suffice for this to provide the functionality of GLES3, or its DirectX equivalent. Given XF's positioning as a cross-platform solution, it's probably not necessary to support full desktop OpenGL -- the ES profiles will suffice.

### Actual Behavior

No 3D graphics control is exposed by Xamarin.Forms.

### Basic Information

- Version with issue: all
- Last known good version: none.

**Comment by j4m3z0r** [comment]
Quick update on this: I needed to get something working, so I went ahead and built [this](https://github.com/j4m3z0r/GLUWP), which provides OpenTK-like bindings to ANGLE, and a GLView class which inherits from SwapChainPanel to setup a GL viewport in your UI. I don't yet know enough about XF internals to expose this as an XF control directly, but I was able to add my GLView to a StackLayout using the platform extension methods, which is a workable solution for me, if not ideal.

This lets me use the same OpenGL code as all the other platforms (there are a handful of similar efforts which just expose OpenGL APIs directly, but OpenTK compatibility is important since that's what you'd use on any other platform).

I point all this out, since it seems like it may factor into this issue. Given the above, does it make sense to start converting this code to an XF control as a solution here? Is GL support vs DX support a point of controversy?

Or is this functionality which is considered too niche to include in XF proper? In that case, since I have a solution that works (and this comment will be around for anyone who searches for this in the future), should we just go ahead and close this?

**Comment by jfversluis** [comment]
Seeing the age of this and the fact that Xamarin.Forms is now in maintenance this won't be making it in anymore. TO be honest I don't know how this works with WinUI in .NET MAUI, so if you have any thoughts about that and are still interested in this, make sure to check if something like this is already possible, on the roadmap or open an issue with a feature request and be as detailed as possible.

THanks!
