### ISSUE TITLE
OpenGLView does not expose raw mouse / touch events

### ISSUE THREAD

**Issue by j4m3z0r** [xamarin/Xamarin.Forms#1613]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

When building apps that use an OpenGLView to display 3D graphics, etc, the code producing those 3D graphics will typically have its own system for handling user interactions, which often won't map neatly to GestureRecognizers.

Please provide a way to get access to the raw mouse / touch events, so that these can be fed into the existing event handling code on 3D rendering engines.

### Steps to Reproduce

1. Build an XF application with an OpenGLView, likely atop an existing game engine that already has touch / mouse handling
2. Try to add a system to respond to user input by converting GestureRecognizer events into an approximation of the touch events that would have generated them
3. Lament that there must be a better way

### Expected Behavior

Frictionless integration of rendering engine with existing touch / mouse handling code into an XF application.

### Actual Behavior

No MouseDown, MouseUp, MouseDragged, etc, events on the OpenGLView.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
