### ISSUE TITLE
Add NSCollectionView Equivalent

### ISSUE THREAD

**Issue by j4m3z0r** [xamarin/Xamarin.Forms#1615]
### Description

I think essentially all platforms now provide some equivalent of the NSCollectionView -- a grid of items (think photo thumbnails), and this is a pretty important control for all manner of apps. Charles Petzold's Xamarin.Forms book outlines a solution in [Chapter 26](https://xamarin.azureedge.net/developer/xamarin-forms-book/XamarinFormsBook-Ch26-Apr2016.pdf) using a custom layout called the WrapLayout, however this does not scale: apps really only remain responsive up to a couple hundred items at most.

Per above, I believe essentially all of XF's targets now have some kind of system for rendering these large grids of cells in a performant manner -- typically by re-using cells and only drawing the cells that are visible. XF should provide an interface to these controls so that XF applications can have fast, large grids too. I believe something similar was done for ListViews.

### Steps to Reproduce

1. Create an XF application using the WrapLayout class described in the XF book.
2. Load up 10,000 items into the WrapLayout
3. Observe that it doesn't work (freeze, crash, etc, depending on your luck)

### Expected Behavior

Grids of items should be able to contain arbitrarily many items and should remain performant.

### Actual Behavior

The solution recommended in the XF book does not work after more than a few hundred items.

**Comment by StephaneDelcroix** [comment]
in 4.0.0, we will give you CollectionView
