### ISSUE TITLE
Bug 59896 - v2.4.0: Adding inserting section to ListView causes crash IF first section is empty

### ISSUE THREAD

**Issue by gayko1976** [xamarin/Xamarin.Forms#1618]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
This is still not fixed with 2.5.0 Service Release 3 from https://github.com/xamarin/Xamarin.Forms/releases/tag/release-2.5.0-sr3
as mentioned here https://bugzilla.xamarin.com/show_bug.cgi?id=59896#c37

PLEASE DO FIX THIS IMMEDIATELY! 

THANK YOU SO MUCH!

**Comment by pauldipietro** [comment]
Already filed as #1333. Please upload any reproductions you might have, and also make certain to fully fill out the report template if possible.
