### ISSUE TITLE
[Proposal] Add OnApplyTemplate virtual method to TemplatedView 

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#1620]
### Description

Add a virtual metod `OnApplyTemplate()` to `TemplateView` class, so that `TemplateView` derived classes (custom templated controls) know when template was realized into a control and its inner children can be found.

### API Changes
```
public class TemplatedView : ...
{
       ...
       protected virtual void OnApplyTemplate()
       {
            // this.FindName('someNameOfAChildControl') should work here
       }
}
```

Probably another API is needed to find children from template, something like `GetTemplateChild(string name)`: https://msdn.microsoft.com/en-us/library/system.windows.frameworkelement.gettemplatechild

### Intended Use Case

In Xamarin Forms, there's no simple\clean way to know when a custom control's `ControlTemplate` was applied so that the custom control can get access to its child controls. I'm not saying it's not possible, but there should be a method simple and elegant like in Windows XAML.

In Windows XAML, the `Control` class has an `OnApplyTemplate`: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement#Windows_UI_Xaml_FrameworkElement_OnApplyTemplate.

**Comment by andreinitescu** [comment]
I could look into this if I get a real green light

**Comment by Juansero29** [comment]
> there's no simple\clean way to know when a custom control's ControlTemplate was applied so that the custom control can get access to its child controls. **I'm not saying it's not possible** [...]

... is it possible? I'm currently facing needing to access the child controls in the ControlTemplate of my control. Do you have any advice on the best way for doing this without  `GetTemplateChild(string name)` nor `OnApplyTemplate()` ?

**Comment by andreinitescu** [comment]
Sure, try to override OnParentSet on the custom control. If I remember correctly, when it’s called, children are instantiated too, so you have access to them. But this obviously won’t work if you want the handle the scenarios when the template changes, which is a bit more complicated to handle.
