### ISSUE TITLE
Add FromStream to StyleSheet

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#1624]
### Description

It would be great if we had a  `FromStream` factory method added to the new StyleSheet. This would simplify adding a StyleSheet that we may be reading locally or downloading from the web. 

### Expected Behavior

```cs
using(var client = new HttpClient())
{
    var stream = await client.GetStreamAsync("http://contoso.com/api/app/css");
    var styleSheet = StyleSheet.FromStream(stream);
}
```

### Actual Behavior

```cs
using(var client = new HttpClient())
{
    var stream = await client.GetStreamAsync("http://contoso.com/api/app/css");
    var styleSheet = StyleSheet.FromReader(new StreamReader(stream));
}
```

### Basic Information

- Version with issue: vNext

**Comment by StephaneDelcroix** [comment]
Downloading part of your UI from the web is a terrible idea in any mobile application.

**Comment by dansiegel** [comment]
@StephaneDelcroix I can appreciate your opinion on that... but that's one of a few scenarios... I recognize there is a method for pulling an embedded resource but again if I'm doing that, I'm working directly with a stream... if I'm reading it in from the filesystem again I'm working first with a stream. Stream is IMHO a better choice for the API than FromReader which first required the stream anyway...
