### ISSUE TITLE
XF - System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by Pinox** [xamarin/Xamarin.Forms#1626]
Getting the following error on many of my projects when trying to upgrade to XF using .net Standard 2 (latest version of XF)

"Could not load assembly 'System.Runtime.CompilerServices.Unsafe' during startup registration."

The easiest way to check error is using stock standard XF Blank template and adding nuget Microsoft.EntityFrameworkCore 2.0.1.   Build and run the app on Oreo (Android 8) and the error will result.

I'm also seeing the same error on other projects that do not use entity framework, is someone looking at this or is there some workaround that I'm not aware of.

**Comment by StephaneDelcroix** [comment]
I wasn't able to reproduce this issue. Could you please attach your sample project ?

Thx

**Comment by StephaneDelcroix** [comment]
this is probably related to #1599

**Comment by kvpt** [comment]
It's a Xamarin Android specific issue, see xamarin/xamarin-android#1196.

**Comment by StephaneDelcroix** [comment]
closing, then

**Comment by Pinox** [comment]
Sorry for the late reply.  plse find attached the repo. Have tried everything on my side to get it working , my summary so far is XF does not support .net standard 2. Not the new file format anyway.

I see no reason why this project should not run on an emulator and I have tried them all. 
All emulators give me the same error.

Can someone plse confirm my result, running out of ideas on my side ;)

[XF_STD2.zip](https://github.com/xamarin/Xamarin.Forms/files/1653638/XF_STD2.zip)
