### ISSUE TITLE
Transparent ToolbarItem after moving back from page iOS Only 

### ISSUE THREAD

**Issue by izzyco** [xamarin/Xamarin.Forms#1631]
### Description
ToolbarItem looks transparent after navigation back from a page. The item is still clickable but looks like the style is changed. This issue only appears on iOS. Similar to issue 1608. 

### Steps to Reproduce
"If you create a simple 2 page navigation app. First page adds a toolbar button when clicked does a Navigation.PushAsync to the second page. When coming back to the first page the toolbar button text is then faded out on the first page. It is still clickable so you can go back to the second page just fine, just a visual issue."

Reference: 
[https://forums.xamarin.com/discussion/113677/navigation-toolbar-button-issue-ios-only.
](https://forums.xamarin.com/discussion/113677/navigation-toolbar-button-issue-ios-only.)

Attached Sample Application 
1. Restore Packages and click the next toolbar item
2. Click the back button 

### Expected Behavior
See the next toolbar item with the same style as the first attempt (Image 1).

### Actual Behavior
See a faded out, almost transparent view of the next toolbar item. 

### Basic Information
- IDE: Visual Studio for Mac 
- Platform Target Frameworks: 
  - iOS:  11.1 

### Screenshots

<img width="283" alt="toolbaritemissue1" src="https://user-images.githubusercontent.com/8538962/35241984-4c3cff80-ff86-11e7-8a95-7912f16c703e.png">

<img width="284" alt="toolbaritemissue2" src="https://user-images.githubusercontent.com/8538962/35241987-4dec7e82-ff86-11e7-8930-981433a13ad9.png">

### Reproduction Link
[NavigationToolbarIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1653428/NavigationToolbarIssue.zip)

**Comment by anurbecirovic** [comment]
Any update on this? I have the same issue.

**Comment by jfversluis** [comment]
I can't seem to reproduce it anymore on iOS 12.1:

![transparenttoolbaritem](https://user-images.githubusercontent.com/939291/48351279-15c66900-e68a-11e8-800a-8ef397a186f8.gif)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
