### ISSUE TITLE
[Enhancement] Label underline/strikethrough support

### ISSUE THREAD

**Issue by jassmith** [xamarin/Xamarin.Forms#1632]
## Rationale

The label currently has no easy mechanism of being underlined. Sometimes applications need the ability to underline text without using an Effect.

## Implementation

Modify the FontAttributes enum to be as follows:

```csharp
public enum FontAttributes
{
	None = 0,
	Bold = 1 << 0,
	Italic = 1 << 1,
	Underline = 1 << 2,
        Strike = 1 << 3
}
```

Renderers and Span parsers will need to understand how to use the new underline and strikethrough flags appropriately.

## Expected Result

On all the platforms the label/span has underline and/or strikethrough applied as expected.

## Implications for CSS

CSS will need to be updated to support the `text-decoration: underline` and `text-decoration:line-through` tags for full compatibility.

## Backward Compatibility

This change is as backwards compatible with existing code as possible. It is possible someone has found some obscure way of depending on there not being any more flags to the FontAttributes enum, but that is unlikely.

Third party renderers will need to be updated to ensure that this functionality is supported through the new official mechanism. Further we will need to be careful to code the changes to the renderers in a careful manner to ensure that if someone is already using an effect to set an underline state on a label that this effect is as best as possible not broken by our changes.

## Difficulty : Easy

This is an easy change and great for a first time contributor. The hardest part will be ensuring the Span can properly parse the new `FontAttributes.Underline` enum values. Some basic defensive coding will be needed to ensure existing code is not broken, ideally the code path when the flags are not set AND have never been set is identical to when they have been. Once a user changes their code to use the flag, the code path can then change for everything.

Even more ideally this would be done without an additional flag for tracking that status; possible using [GetIsDefault](https://github.com/xamarin/Xamarin.Forms/issues/1652).

**Comment by ahmedalejo** [comment]
I think it´s relevant to mention that the most common reason of underline a text is to emphasize that it is a hyperlink. When i implemented underline on forms label spans, it was to make it **tappable**.

So while giving this a shot, next step would be tappable spans. Just as a foot note

**Comment by andreinitescu** [comment]
@ahmedalejo What you want is a button, not a label. If the primary reason why everyone wants underline is because of links, this new feature should be added to Button, not Label

**Comment by ahmedalejo** [comment]
@andreinitescu nope, Think of a laebel with multiline text whereby you have "**@andreinitescu**" in it or url which you want to decorate accordingly

**Comment by mattallscripts** [comment]
We need this feature for underlying a portion of a label. Specifically we have a label showing the blood pressure of a patient, if either the systolic or diastolic portion of the label are out-of-range, then that value string needs to show up red and underlined. Our use-case is an example where underlining is needed other than for purposes of a link or tappable span.

On Jan 23, 2018, at 11:32 PM, Ahmed Aderopo Alejo <notifications@github.com<mailto:notifications@github.com>> wrote:


@andreinitescu<https://github.com/andreinitescu> nope, Think of a laebel with multiline text whereby you have "@andreinitescu<https://github.com/andreinitescu>" in it or url which you want to decorate accordingly

**Comment by ahmedalejo** [comment]
@mattallscripts  thanks for providing other use case whereby hyperlinking isn´t the case.

Come to think of it, in Github the hyperlinks are emphasized without the aid of underlines.
I guess **tappable Span** is another feature request, thank for the fast brainstorm.

**Comment by andreinitescu** [comment]
@ahmedalejo in the examples you give, you would have same issues with Label, because you want only a part of the text to be tappable, not all the Label.

**Comment by alanag13** [comment]
@jassmith are items in the "Ready for implementation" column considered "up for grabs"? If so, how would I claim one?

**Comment by jassmith** [comment]
Post in here you are claiming it, make a branch and start working. We will then assign it to you and whenever you land a PR we will move the card to an appropriate release board.

**Comment by alanag13** [comment]
Thanks -- I I'll hopefully pick up some more with time, but for now just to get familiar with the codebase and everything I'll take this one!

**Comment by alanag13** [comment]
Actually, I just noticed that you added a ton more enhancements to the board between when I commented on this originally and now. Some of them related directly to work that I've done in personal projects and should be easier for me to tackle and deliver, so I'll start with those. In the meantime, someone else can pick this up if they'd like.

**Comment by adamped** [comment]
@alanag13 - anything marked with a F100 is part of a sprint the community is doing, as the result of some of the most requested enhancements for XF. Are you on the XamarinChat slack? I can send you an invite to the specific channel. In there we are helping each other out. Myself and others have contributed to XF before and happy to assist in any PR prep.

**Comment by alanag13** [comment]
@adamped, I'm not on the slack but I'd appreciate the invite! @davidortinau I noticed that you moved this to 'In Progress' even though I actually reneged on it above, so maybe this should be moved back?

**Comment by adamped** [comment]
@alanag13 - Go to https://xamarinchat.herokuapp.com/ and you can invite yourself. Then once done let me know, and I will invite you to the slack channel we have.

**Comment by hartez** [comment]
> I guess tappable Span is another feature request, thank for the fast brainstorm.

@ahmedalejo See: https://github.com/xamarin/Xamarin.Forms/issues/1701

**Comment by hartez** [comment]
Updated this issue to include strikethrough from #1674, since they both require modifying most of the same code.

**Comment by alanag13** [comment]
I'll take this one back since no one jumped at it when I gave it up earlier and it's currently (incorrectly) marked as in progress.

**Comment by alanag13** [comment]
I have Android, iOS, and UWP working for this here: https://github.com/XamarinFormsCommunity/Xamarin.Forms/tree/feature/1632-label-underline-strike. I think I can tackle this for all the platforms -- expect a PR later this week 😄

**Comment by jassmith** [comment]
kickass, cant wait to see a PR

**Comment by alanag13** [comment]
I'm waiting on #1850 for some parts of this, this will also allow the last remaining platform (GTK) to work. Once that is merged I can add Spans and CSS to my PR. The base functionality I have working on everything besides GTK.

**Comment by djcparker** [comment]
@jassmith  - I'd like to see Subscript and Superscript as well.  Can this Enhancement be extended or should it be raised as another one?   The use case I have is for things like  Ug  where the g is scripted  or the tm and (r) symbols.

**Comment by jassmith** [comment]
There is already an open PR, another change would need a new enhancement opened

**Comment by andreinitescu** [comment]
FontAttributes enum is used by Button too. I assume support for Underline and Strike will work for Button too?

**Comment by jassmith** [comment]
It would be ideal but we are willing to take that as an errata for the initial PR rather than gate on it.

**Comment by alanag13** [comment]
My current PR actually puts these on their own enum instead of FontAttributes. You can see my reasons for this I the comments. https://github.com/XamarinFormsCommunity/Xamarin.Forms/pull/9.
That being said I do also call out in the same comment that Buttons are probably the only other control that I see being frequently used for this, so I'm willing to give support for them a run.

**Comment by jassmith** [comment]
Mmm a shame we have competing implementations here. At the moment I tend to lean towards not introducing a new type here. Bold/italic are not fundamentally different to underline/strikethrough if you ask me.

That said I need to reassess the situation. You make some valid points and ultimately this is about API not implementation details. I would like to have a design meeting with you involved if you can. Email me at jas@microsoft to set up a time (if you are interested).

**Comment by andreinitescu** [comment]
I'm for a separate TextDecorations enum, just so we're inline with Windows XAML

**Comment by alanag13** [comment]
@jassmith I sent you a message on this, just wanted to make sure you saw in case one of your email filters swallowed it :-)

**Comment by jassmith** [comment]
It did, thanks for the ping

**Comment by alanag13** [comment]
@jassmith I sent you a follow-up with specific times that work for me, just pinging you again to ensure visibility :-)

**Comment by alanag13** [comment]
I have an early PR for this in progress here, all that is left to do are the suggested correction and handling spans (I was waiting on #1850, which now merged) . @jassmith reviewed this and we agreed that separating TextDecorations in to a new enum was a better approach.

https://github.com/XamarinFormsCommunity/Xamarin.Forms/pull/9

**Comment by RandomString123** [comment]
I for one am very excited about this getting into the final product it will save me a lot of trouble trying to do something similar with unicode tricks or line drawing.

**Comment by AuriR** [comment]
I'm not sure if this is for supporting the enum or for strikethrough, but I've implemented something that simply uses unicode to render the strikethrough. If this helps anyone working on this, here ya go:

```
        private string ConvertToStrikethrough(string stringToChange)
        {
            var newString = "";
            foreach (var character in stringToChange)
            {
                newString += $"{character}\u0336";
            }

            return newString;
        }

```

**Comment by BlueRaja** [comment]
I'm confused.  Target is 3.4.0, but the current version is 3.4.0.1008975 and it doesn't exist there?

**Comment by alanag13** [comment]
@BlueRaja the final implementation of this differed from this initial proposed spec. You can read the docs on `TextDecorations` [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#text-decorations).
