### ISSUE TITLE
ListView highlight still visible after SelectedItem = null when ListView hosted inside NavigationPage as Detail of MasterDetailPage on UWP

### ISSUE THREAD

**Issue by jsbakker** [xamarin/Xamarin.Forms#1633]
### Description

When you have an application with hierarchical navigation (e.g. browse folder or tree structure), there are issues when popping off the Navigation stack. I am using MasterDetailPage as the root Page, and NavigationPage as the Detail Page which is hosting a stack of Pages containing ListViews.

I only started experiencing this after updating from Xamrin.Forms 2.3.2 to 2.5.0. It was observed on UWP, but not on Android.

### Steps to Reproduce

1. Navigate into at least one location deep
2. Press the back button on the navigation frame
3. Look at the page you were previously on

### Expected Behavior

When you pop one level off the navigation stack, the previously navigated item should have no items selected (because we explicitly set SelectedItem = null when pushing the next page, which is now popped).

### Actual Behavior

After popping from the navigation stack, the item you last navigated into on the previous screen is still highlighted.

I have made multiple attempts to work around this myself:

1. Permutations of awaiting Push on the navigation stack, and whether to set SelectedItem = null before or after pushing. Result: no effect.
2. Creating a custom renderer for my listview items, and coming up with two different ways to suppress the highlight when rendering the listview item, both with the same result: even weirder behavior. Now when popping off the navigation stack, you are left on a blank screen and have to press the back button a second time to get to the previous page on the navigation stack. This makes no sense why rendering a cell differently would corrupt the navigation stack, and it smells that there's something wrong with navigation stack with certain view hierarchies.

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: 2.3.2.127
- IDE: Visual Studio 2015 Update 3
- Platform Target Frameworks:
  - UWP:  14393
- Affected Devices: Windows Desktop

### Reproduction Link

I have reproduced in a standalone app this by using the Xamarin cross-platform application template in Visual Studio 2015, then selected the "Master Detail" template, and selected Xamarin.Forms UI Technology, then modified it a tiny, tiny bit. Funny enough, the generated code doesn't use MasterDetailPage at all.

If you make the following changes, it should be reproducible:

- Create a new ContentPage and set a title (this will be master)
- Create a NavigationPage with a new ItemsPage (this has a ListView) on the stack (this will be detail)
- Set MainPage to a new MasterDetailPage, setting the ContentPage as master and NavigationPage as detail
- In ItemsPage OnItemSelected, comment out the push of ItemDetailPage, and instead push a new ItemsPage
- Make note that ItemsListView.SelectedItem =null is being set

**Comment by samhouts** [comment]
@jsbakker Are you still experiencing this issue? Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by jsbakker** [comment]
I'm sorry I missed the February comment. Unfortunately I do not have access to a Windows machine for UWP development, as I have switched employers since logging this issue. I can try setting something up within the next 30 days.

**Comment by samhouts** [comment]
@jsbakker Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
