### ISSUE TITLE
[iOS]  iPad Pro 10.5 inch Swipe not working on webview

### ISSUE THREAD

**Issue by BlackRamsis** [xamarin/Xamarin.Forms#1635]
### Description

Hy, I'm using the carousel view from https://github.com/alexrainman which should be included in Xamarin Forms Version 3.

I have only webviews in my carousel. Only on iPad Pro 10.5 inch i can't swipe right. I'm able to swipe left, but the swipe to right gets not recognized.

The problem is not in the control, cause the swipe seems not to arrive there and
the problem only exist with a special grid constellation if u delete all grids and only use the carousel everything is fine.

### Steps to Reproduce

1. Start the attached Code with a real iPad Pro 10.5 or simulator
2.  make sure u are in landscape mode (in portrait mode its working)

### Expected Behavior
You can swipe right

### Actual Behavior
You can't swipe right

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: never
- IDE:Visual Studio 2015/2017
- iOS:  11.2
- Affected Devices: iPad Pro 10.5 inch

### Reproduction Link
I used the code from https://github.com/alexrainman
and edited the demo code to show the problem

[example.zip](https://github.com/xamarin/Xamarin.Forms/files/1655462/example.zip)

**Comment by pauldipietro** [comment]
I would report this on the PR (#853) as the feature has not yet been merged in.
