### ISSUE TITLE
Desktop support: Setting MenuItem.IsEnabled has no effect (macOS)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1636]
### Description

On macOS, setting MenuItem.IsEnabled to false (from XAML) does not disable the context menu item.

### Steps to Reproduce

1. Run the attached sample and browse to the Context Menu page.
2. Right-click the black BoxView and select the Red context menu item.

AND

1. Run the attached sample and browse to the Menus page.
2. From the application menu select the File > Open menu item (note: this menu item doesn't do anything, but it should be disabled).

### Expected Behavior

Nothing happens as the Red menu item should be disabled.

The File > Open menu item is disabled.

### Actual Behavior

The BoxView changes to red.

File > Open menu item is enabled.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSMac
- Platform Target Frameworks: macOS (10.12.6)

### Reproduction Link

[DesktopSupportIssues-IsEnabled.zip](https://github.com/xamarin/Xamarin.Forms/files/1655725/DesktopSupportIssues-IsEnabled.zip)

**Comment by jfversluis** [comment]
Nowadays `MenuItem.IsEnabled` is readonly, so this should not be a problem anymore.

Enabling/disabling should now happen through the `Command.CanExecute`. Therefore this does not seem relevant anymore.
