### ISSUE TITLE
Desktop support: MenuItem.Command binding doesn't work (macOS)

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1637]
### Description

On macOS, when binding from MenuItem.Command to an ICommand implementation (in both XAML and C#), the binding doesn't seem to work. Both the Execute and CanExecute delegates are never executed.

### Steps to Reproduce

(XAML)
1. Run the attached sample and navigate to the context menu page.
2. Right-click the BoxView and select a color. 

(C#)
1. Edit App.xaml.cs in the attached sample so that the first page in the app is MainPageCS.
2. Navigate to the menus page.
3. In the application menu, select Color > any color.

### Expected Behavior

(XAML)
The BoxView changes to the selected color. In addition, the context menu item for the color is disabled.

(C#)
The BoxView changes to the select color. In addition, the application menu item for the color is disabled.

### Actual Behavior

(XAML)
The BoxView remains black. In addition, all context menu items remain enabled.

(C#)
The BoxView remains black. In addition, all application menu items remain enabled.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSMac
- Platform Target Frameworks: macOS (10.12.6)

### Reproduction Link

[DesktopSupportIssues-MenuItemCommandBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/1655768/DesktopSupportIssues-MenuItemCommandBinding.zip)

**Comment by karlingen** [comment]
@davidbritch did you manage to find a workaround?

**Comment by davidbritch** [comment]
@karlingen No. The feature is broken.

**Comment by jfversluis** [comment]
A workaround is to set the `BindingContext` directly on the menu item. It seems that the binding context is not propagated all the way down to the menu items.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by rohitvipin** [comment]
This is broken for more than 3 years and has not been fixed?

**Comment by jfversluis** [comment]
There is a workaround for this available and macOS has not been a priority (or even officially supported platform) for Forms. Considering all the other priorities we have I don't think this will be fixed, unless someone provides a PR for it. Thanks!
