### ISSUE TITLE
[Xamarin.Forms..Xaml] Error in xFactoryMethod Name

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#1640]
I found a typo in the code.
https://github.com/xamarin/Xamarin.Forms/blob/a7d12e620c9394aa7b6327a24884bce74ab637c4/Xamarin.Forms.Xaml/XmlName.cs#L13
as you can see, you probably need to do this:

```cs
public static readonly XmlName xFactoryMethod = new XmlName ("x", "FactoryMethod");
```

**Comment by StephaneDelcroix** [comment]
thanks for the report. it might looks like a typo, or a bug, but it's nothing but a naming inconsistency. the actual content of that XmlName is never used, so it could be anything

**Comment by StephaneDelcroix** [comment]
fixed anyway
