### ISSUE TITLE
[Android] Tabs navigation fault after removing a tab

### ISSUE THREAD

**Issue by Ofaim** [xamarin/Xamarin.Forms#1644]
Hey all!
I was struggling with that issue for a few months now.  
If you have any idea how to **manipulate around this bug** (until it'll be fixed), PLEASE SHARE!

### Description
Tab was added on runtime. When navigating to another tab, the added tab is removed (using `RemoveAt()` command).
Depending the method of navigation to another tab, the issue appear\not (see "Actual Behavior").

### Steps to Reproduce
Run the following code, given that the app contains 3 permanent tabs and the 4th was added on runtime:
```
public partial class MainPage : TabbedPage
{
    public MainPage()
    {
        InitializeComponent();
        //Some logic...

    ///Max number of tabs = 3, unless CurrentPage is the 4th tab.
    ///When CurrentPage is no longer the 4th tab, it will be removed.
    this.CurrentPageChanged += (object sender, EventArgs e) =>
        {
             if (this.Children.Count > 3 && (CurrentPage != this.Children[3]))
                this.Children.RemoveAt(3);
         };
    }
}
```

### Expected Behavior
Tab [3] will be removed && `CurrentPage` will be the tab the user chose.
### Actual Behavior
If the user slides from tab [3] to tab [2], the app behaves as expected.
If the user chooses tab [0]-[2], then tab [3] is removed (as expected) BUT `CurrentPage` is 1 tab to the left of what the user actually chose.
### Basic Information
According to [this](https://forums.xamarin.com/discussion/114609/tabs-navigation-fault-after-removing-a-tab) thread that I've opened, the problem seems to effect only the Android project.
### Screenshots
Sliding from tab [3] to [2] performs well:
http://us.v-cdn.net/5019960/uploads/editor/2f/7katr50dbs8e.gif
Choosing tab [0]-[2] raising the issue:
http://us.v-cdn.net/5019960/uploads/editor/cy/iw95jtk2iwqm.gif

**Comment by pauldipietro** [comment]
Can you please upload a complete reproduction project as well as clarify if this is only occurring on a specific platform?

**Comment by Ofaim** [comment]
Hey @pauldipietro !
Thank you very much for taking the time to answer :)
I already linked a reproduction project, done by @shantimohan .
I changed it a bit, and it can be found [here](https://github.com/Ofaim/Navigation-fault-after-removing-a-tab).

According to @shantimohan ([here](https://forums.xamarin.com/discussion/114609/tabs-navigation-fault-after-removing-a-tab)) , the issue is Android-specific. I cannot check it, and I don't need to use the same mechanism on a different platform, yet. I'll be needing it in the future, though.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
