### ISSUE TITLE
Android OnDetachedFromWindow bug

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Xamarin.Forms#1646]
### Description

Android application **randomly** crashes before when user kills application.

### Steps to Reproduce

1. Open MasterDetailed page application
2. Force to kill an application proceess

### Expected Behavior

Application should kill, do not trigger an error before kill

### Actual Behavior
Application triggers an error: [NotSupportedException] Unable to activate instance of type Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer (i guess the same with NavigationPageRenderer etc.)

### Basic Information

- OS: Android (versions from log: 4.4.4, 5.0.2, 5.1.1, 6.0, 7.0 etc) 
- Xamarin.Forms 2.5.0.122203

### Log

<pre>Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer from native handle 0x9020001d (key_handle 0x453a0428).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at Android.Views.View.n_OnDetachedFromWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  at (wrapper dynamic-method) System.Object:4adc8d11-ae2c-4e17-bd26-30d6104199c7 (intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <50fac8ede6e6437da7c8d41a391fc2c8>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.n_onDetachedFromWindow(Native Method)
      at md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.onDetachedFromWindow(MasterDetailPageRenderer.java:60)
      at android.view.View.dispatchDetachedFromWindow(View.java:12751)
      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
      at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4027)
      at android.view.ViewGroup.removeAllViews(ViewGroup.java:3971)
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onDestroy(Native Method)
      at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onDestroy(FormsAppCompatActivity.java:80)
      at android.app.Activity.performDestroy(Activity.java:5403)
      at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3574)
      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3605)
      at android.app.ActivityThread.access$1400(ActivityThread.java:144)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1299)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:212)
      at android.app.ActivityThread.main(ActivityThread.java:5137)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
      at dalvik.system.NativeStart.main(Native Method)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:579)
2   java.lang.Thread.getAllStackTraces(Thread.java:521)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:788)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)
5   md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.n_onDetachedFromWindow(MasterDetailPageRenderer.java:-2)
6   md5270abb39e60627f0f200893b490a1ade.MasterDetailPageRenderer.onDetachedFromWindow(MasterDetailPageRenderer.java:60)
7   android.view.View.dispatchDetachedFromWindow(View.java:12751)
8   android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2587)
9   android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4027)
10  android.view.ViewGroup.removeAllViews(ViewGroup.java:3971)
11  md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onDestroy(FormsAppCompatActivity.java:-2)
12  md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onDestroy(FormsAppCompatActivity.java:80)
13  android.app.Activity.performDestroy(Activity.java:5403)
14  android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1117)
15  android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3574)
16  android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3605)
17  android.app.ActivityThread.access$1400(ActivityThread.java:144)
18  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1299)
19  android.os.Handler.dispatchMessage(Handler.java:102)
20  android.os.Looper.loop(Looper.java:212)
21  android.app.ActivityThread.main(ActivityThread.java:5137)
22  java.lang.reflect.Method.invokeNative(Method.java:-2)
23  java.lang.reflect.Method.invoke(Method.java:515)
24  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
25  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
26  dalvik.system.NativeStart.main(NativeStart.java:-2)

Thread 7480:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7481:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7482:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7483:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:364)
2   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:130)
3   java.lang.Thread.run(Thread.java:841)

Thread 7484:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:401)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
5   java.lang.Thread.run(Thread.java:841)

Thread 7485:
0   java.lang.VMThread.sleep(VMThread.java:-2)
1   java.lang.Thread.sleep(Thread.java:1013)
2   java.lang.Thread.sleep(Thread.java:995)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:248)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:258)
5   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:212)
6   java.lang.Thread.run(Thread.java:841)

Thread 7486:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7487:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7489:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7498:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7499:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:138)
2   android.os.Looper.loop(Looper.java:196)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 7501:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7502:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7511:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7516:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7517:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7526:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7529:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:138)
2   android.os.Looper.loop(Looper.java:196)
3   com.android.org.chromium.media.AudioManagerAndroid$SettingsObserverThread.run(AudioManagerAndroid.java:648)

Thread 7530:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7532:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7533:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:401)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
4   com.android.org.chromium.content.common.CleanupReference$1.run(CleanupReference.java:49)

Thread 7534:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7537:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:138)
2   android.os.Looper.loop(Looper.java:196)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 7539:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7543:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7544:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 7551:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 7555:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:138)
2   android.os.Looper.loop(Looper.java:196)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 7929:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8072:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8099:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8170:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8200:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8203:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8208:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor(Thread.java:1205)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2056)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
9   java.lang.Thread.run(Thread.java:841)

Thread 8226:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8234:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8235:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8238:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8239:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8251:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8253:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8254:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8255:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8256:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8257:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8258:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8259:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8262:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)

Thread 8264:
0   dalvik.system.NativeStart.run(NativeStart.java:-2)
</pre>

**Comment by kvpt** [comment]
I encountered this issue too.
This error is quite random but is always related to the dispose process.
I think it's related to some sort of race condition.

The cause of the issue in described in the Xamarin Android documentation [here](https://developer.xamarin.com/guides/android/under_the_hood/architecture/#Premature_Dispose_Calls).

Certain parts of the framework have specific constructor to handle this issue.
Like [here](https://github.com/xamarin/Xamarin.Forms/blob/8017ef5ba3a7afacf917a5838eba7e54db8bf5ad/Xamarin.Forms.Platform.Android/Renderers/MasterDetailContainer.cs#L26) or [here](https://github.com/xamarin/Xamarin.Forms/blob/8017ef5ba3a7afacf917a5838eba7e54db8bf5ad/Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs#L402).

In our applications, it's always the MasterDetailPageRenderer or NavigationPageRenderer that throw this exception.

The solution is to inherit the two renderers and define the constructor like this :
```cs
public YourRenderer(IntPtr handle, Android.Runtime.JniHandleOwnership transfer)
    : base (handle, transfer)
{
}
```

Since this change in our application, this error has not been reproduced.

You can find this issue mentionned in other BugZilla issue : [here](https://bugzilla.xamarin.com/show_bug.cgi?id=60732) and [here](https://bugzilla.xamarin.com/show_bug.cgi?id=57802).

**Comment by paleicikas** [comment]
Add "missing" constructor, I think, is not a solution as it hides real problem: object disposed before its method/property used

**Comment by kvpt** [comment]
I'm agree with you that this solution seem to be not an ideal solution.
But the problem is that the "JVM/Java side" call an object which has been disposed by the "Mono/C# side".

Is it a problem and is it possible to prevent that, I don't know ?
A developer from the Xamarin team may be able to answer this question.

**Comment by MisterJimson** [comment]
I am seeing this as well. 2.5.0.122203

**Comment by PureWeen** [comment]
Do you have a repro and maybe a few more details about your environment?  Just so I can get an idea of the conditions you are running this under? I saw one of the bugzilla issues had a repro but I was unable to recreate the issue with that.  I've tried it on simulator/real device/debug/release/messed with linker and wasn't able to cause it to happen.   Gaining some insight into your running conditions would be helpful

**Comment by MisterJimson** [comment]
These are the details I have.

Seeing it on Android versions 5.0, 5.1.1, 6.0.1, 7.0, and 7.1.1 in the field. Very inconsistent when trying to reproduce in house but happens occasionally. Usually after the app has been running and used for a while. Most of my reports show the app running for a few minutes before crashing, however I see 2 reports that occurred less than 10 seconds from startup.

Also the majority of my reports are Samsung made phones, but I do see 3 reports of other devices (Priv, Nexus 5, Moto Z Play).

**Comment by jassmith** [comment]
Are you using forms to create a splashscreen maybe?

**Comment by MisterJimson** [comment]
I do have a splash screen.

**Comment by MisterJimson** [comment]
Bit more detail. Seems to happen when we are navigating away from MasterDetail to a screen that does not have a MasterDetail page.

For us when the user logs out we see this https://gist.github.com/MisterJimson/dac690fb913782d84ccd12ab105d8c33

**Comment by jassmith** [comment]
I can't seem to whittle this one down, a repro case would go a long way. I do believe its likely a race condition with the splashscreen created using Forms. Can you maybe detail exactly how you do that for me?

**Comment by MisterJimson** [comment]
The splash screen shouldn't be called here. This is on logout, where we go to our login screen. The splash screen only displays on app start.

**Comment by jassmith** [comment]
Without a basic repro case this will be very hard to track down. This is caused by a Page coming up in an android event after we believe it should be gone. This is not a good thing, but I can't cause it in my testing :(

**Comment by MisterJimson** [comment]
I'll see if I can strip down our app to a reproducible sample.
