### ISSUE TITLE
Support binding to attached BP

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#1647]
The current Binding system doesn't allow to use an attached bindable property as binding source, like in 
```
<Grid>
    <Label x:Name="label0" Grid.Row="1"/>
    <Label Text="{Binding (Grid.Row), Source={x:Reference label0}}" />
</Grid>
```

Of course, it can be combined as part of a complex path 
```
<Label Text="{Binding label0.(Grid.Row)}" />
```

If the attached BP owner type is not in the default xmlns, the type has to be prefixed
```
<Label Text="{Binding label0.(local:MyLayout.Altitude)}" />
```
For this reason, this syntax is restricted to xaml only.

Challenges:
 - attach changed handlers to attached BPs
 - keep the current bindings working while refactoring
 
## Formal syntax for Binding Path
_part-element-list_:
 - _empty_
 - _part-separator_
 - _first-part_ _part-list_(opt)

_empty_:
 - ` `

_part-separator_:
 - `.`

_first-part_:
 - _part_
 - _part-separator_ _part_

_part-list_:
 - _part-separator_ _part_
 - _part-separator_ _part_ _part-list_(opt)

_part_:
 - _part-id_
 - _indexer_

_part-id_:
 - identifier
 - `(`_type_`.`_bp_`)`

_type_:
 - identifier
 - xmlnsprefix`:`identifier

_indexer_:
 - _part_id_`[`index`]`

**Comment by AtosNicoS** [comment]
This issue is listed for the x:Bind project:
https://github.com/xamarin/Xamarin.Forms/projects/7

What is the current status of the x:bind implementation?

**Comment by ddobrev** [comment]
When is this planned for fixing?

**Comment by groege** [comment]
Bump

**Comment by YZahringer** [comment]
Any news on that?

**Comment by tuyen-vuduc** [comment]
I am also looking for this feature to work as well.

**Comment by JunkyXL86** [comment]
Same here

**Comment by acaliaro** [comment]
there are some news there?

**Comment by SebastiaanPolfliet** [comment]
Any updates on this? Thanks!

**Comment by marcos-marimon** [comment]
Any update? And support for TemplateBinding as well?

**Comment by jfversluis** [comment]
This won't be happening for Forms anymore. I've added it to the short list for .NET MAUI!
