### ISSUE TITLE
MasterDetailPage throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by TiBall** [xamarin/Xamarin.Forms#1648]
### Description
When adding a MasterDetailPage inside a NavigationPage, it throws an Exception upon loading

### Steps to Reproduce
Start the modified version of the official example at:
https://github.com/TiBall/xamarin-forms-samples/tree/MasterDetailNavigationException/Navigation/MasterDetailPage

### Expected Behavior
MasterDetailPage renders with no Exception

### Actual Behavior
Application terminates because of this error inside the Xamarin Control
"System.ArgumentOutOfRangeException: Non-negative number required.\r\… 
…nParameter name: height\r\n at Windows.Foundation.Size..ctor(Double width, Double height)\r\n at Xamarin.Forms.Platform.UWP.MasterDetailControl.get_MasterSize()\r\n at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.UpdateBounds()\r\n at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.OnControlLoaded(Object sender, RoutedEventArgs routedEventArgs)"

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017 v 15.5.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  10.0.10586.0 and higher
- Android Support Library Version: 
- Nuget Packages: "Xamarin.Forms": "2.5.0.91635"
- Affected Devices: Windows

### Reproduction Link
https://github.com/TiBall/xamarin-forms-samples/commit/f79e75114e970f07ddcf7dfc5df85571c48af67b

**Comment by kingces95** [comment]
[Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2103524/Repro.zip)

Just the reproduction.

**Comment by kingces95** [comment]
FYI, Android throws 

> System.Exception: Android only allows one navigation page on screen at a time

**Comment by PureWeen** [comment]
@kingces95 

[Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2113439/Repro.zip)

**Comment by kingces95** [comment]
@PureWeen Ur attached repro contains env specific .props file. Not sure what generated it.

**Comment by kingces95** [comment]
@TiBall if I update the samples branch and nugets to latest nightly then I no longer see the exception. If that's not also your experience, please reopen.
