### ISSUE TITLE
[macOS] GestureRecognizer on ListView Item not working

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#1658]
### Description
The `TapGestureRecognizer` or `ClickGestureRecognizer` on `ListView` `ItemTemplate` not works on macOS. It works on UWP, Android & iOS.

### Steps to Reproduce
1. Add `ListView` on `ContentPage`
2. Add `GestureRecognizers` on `ItemTemplate`

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.122203
- IDE: Visual Studio for Mac 7.3.3 (build 5)
- Platform Target Frameworks:
  - macOS: 10.13.2

### Reproduction Link
https://github.com/MADSENSE/Madsense.XamarinForms.Sample/tree/ListView-GestureRecognizer

**Comment by YZahringer** [comment]
Temp workaround, add transparent button on background:
````xml
<Button Command="{Binding MyComand}" BackgroundColor="Transparent">
    <Button.IsVisible>
        <OnPlatform x:TypeArguments="x:Boolean">
            <On Platform="macOS">true</On>
        </OnPlatform>
    </Button.IsVisible>
</Button>
````

**Comment by baywolf-studios** [comment]
Seeing this same issue with using a GestureRecognizer on any controls inside the ItemTemplate. The workaround seems to work for now.

**Comment by nor0x** [comment]
Any updates on this? @samhouts 
thanks

**Comment by FrankChen021** [comment]
it has been almost 2 years and still no progress...

**Comment by kmcclive** [comment]
> Temp workaround, add transparent button on background:
> 
> ```
> <Button Command="{Binding MyComand}" BackgroundColor="Transparent">
>     <Button.IsVisible>
>         <OnPlatform x:TypeArguments="x:Boolean">
>             <On Platform="macOS">true</On>
>         </OnPlatform>
>     </Button.IsVisible>
> </Button>
> ```

I was still able to see the button when setting the background color.  Setting the Opacity to 0 makes it truly invisible.
```
<Button Command="{Binding MyComand}" Opacity="0">
    <Button.IsVisible>
        <OnPlatform x:TypeArguments="x:Boolean">
            <On Platform="macOS">true</On>
        </OnPlatform>
    </Button.IsVisible>
</Button>
```
