### ISSUE TITLE
[Enhancement] Button TextAlignment

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1659]
## Rationale

`Button`s do not currently have `HorizonalTextAlignment` or `VerticalTextAlignment` properties, so the text is always aligned in the center of the `Button`.

## Implementation

Add bindable properties to `Button` to match `Label`:

```csharp
public static readonly BindableProperty VerticalTextAlignmentProperty = BindableProperty.Create("VerticalTextAlignment", typeof(TextAlignment), typeof(Button), TextAlignment.Center, propertyChanged: OnVerticalTextAlignmentPropertyChanged);

public static readonly BindableProperty HorizontalTextAlignmentProperty = BindableProperty.Create(nameof(ITextAlignmentElement.HorizontalTextAlignment), typeof(TextAlignment), typeof(Button), TextAlignment.Center, propertyChanged: OnHorizontalTextAlignmentPropertyChanged);
```

Renderers will need to be updated accordingly.

### Android

- `Button.HorizontalTextAlignment == TextAlignment.Start`: text should align to the left in LTR mode and to the right on RTL mode.
- `Button.HorizontalTextAlignment == TextAlignment.Center`: text should align to the horizontal middle. Default.
- `Button.HorizontalTextAlignment == TextAlignment.End`: text should align to the right in LTR mode and to the left on RTL mode.

- `Button.VerticalTextAlignment == TextAlignment.Start`: text should align to the top of the `Button`.
- `Button.VerticalTextAlignment == TextAlignment.Center`: text should align to the vertical middle. Default.
- `Button.VerticalTextAlignment == TextAlignment.End`: text should align to the bottom of the `Button`.

### iOS

See Android

### UWP

See Android

## Implications for CSS

`Button`s should now support `text-align`. I guess `vertical-align` is the closest analogy to `VerticalTextAlignment`.

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that a `Button`'s text defaults to centered, as is the expected behavior now,
2. We ensure that any Effects or Custom Renderers that may have been created to produce this behavior take precedence over any values that we set, to the best of our ability.

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Easy

This is an easy change and great for a first-time contributor. It may not be easy on all platforms to get the VerticalAlignment working, however, so we may opt to just implement HorizontalAlignment.

**Comment by hartez** [comment]
We also need to ensure that this works correctly with the various `ButtonContentLayout` options.

**Comment by ice-j** [comment]
Hi @davidortinau can we lock this issue to you, please so  I can start working on it?

**Comment by StephaneDelcroix** [comment]
see comment https://github.com/XamarinFormsCommunity/Xamarin.Forms/pull/2#issuecomment-361876374 about reusing existing BPs

**Comment by davidortinau** [comment]
@ice-j @jassmith should we close this one in favor of #1668 that is more comprehensive?

**Comment by ice-j** [comment]
@davidortinau Yes, I believe we can.

**Comment by StephaneDelcroix** [comment]
the discussion continues on #1668 ...

**Comment by acaliaro** [comment]
@davidortinau which is the current status of this enhancement?
Will it be in release?

**Comment by jgiacomini** [comment]
@davidortinau  is it released ?

**Comment by Mikilll94** [comment]
Is is going to be released?

**Comment by titoleru** [comment]
Any update on this?
