### ISSUE TITLE
[Enhancement] IsSpellCheckEnabled on Entry/Editor

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1660]
## Rationale

The Entry and Editor controls do not have a simple mechanism for disabling the native spell-checking features. For some basic text entry scenarios (e.g., entering a username or editing markup), the spell-checking features provide a negative experience.

## Implementation

Add the following BindableProperty to InputView:

```
public static readonly BindableProperty IsSpellCheckEnabledProperty = 
BindableProperty.Create("IsSpellCheckEnabled", typeof(bool), typeof(Entry)));
```

The value of `IsSpellCheckEnabled` should roughly map to `UITextField.SpellCheckingType` on iOS, `FormsTextBox.IsSpellCheckEnabled` on UWP, and `FormsEditText.IsSuggestionsEnabled` on Android.

In situations where the value of `IsSpellCheckEnabled` would conflict with the selected Keyboard settings (i.e., where spell checking is not a feature offered for the selected keyboard), this value will have no effect.

## Backward Compatibility

The renderers for Entry and Editor on each platform should check `BindableObject.GetIsDefault()`; the behavior of the renderers should only be altered if `IsSpellCheckEnabled` has been explicitly set. This should provide backward compatibility.

**Comment by hartez** [comment]
This is dependent on https://github.com/xamarin/Xamarin.Forms/issues/1652.

**Comment by jassmith** [comment]
Looks good, I like the usage of GetIsDefault to avoid backcompat issues. Should go a decent way to making things sane.

**Comment by ravinderjangra** [comment]
@hartez should it be added in entry and editor both. or we can add in some common interface?

**Comment by hartez** [comment]
@ravinderjangra `InputView` is a common ancestor of Entry and Editor, so adding it there would cover both cases.
