### ISSUE TITLE
[Enhancement] Ability to set color for switch

### ISSUE THREAD

**Issue by jassmith** [xamarin/Xamarin.Forms#1662]
## Rationale

Sometimes it would be nice to be able to change the color of a switch to make it prettier.

## Implementation

```csharp
public class Switch : View
{
  //<SNIP>

  public Color OnColor { get; set; } // BP, default to Color.Default
}
```

### Android
The trough color should change, this can be achieved by setting the color state list.

```csharp
var purple = Xamarin.Forms.Color.Purple.ToAndroid();
var csl = new ColorStateList(s_colorStates, new[] { purple.ToArgb(), purple.ToArgb() });
Control.TrackTintList = csl;
```

### iOS
The trough color of the switch changes to match the desired color when the switch is in the on position

```csharp
Control.OnTintColor = color;
```

### UWP
Same as iOS

## Implications for CSS
None

## Backward Compatibility
The renderers on each platform should check BindableObject.GetIsDefault(); the behavior of the renderers should only be altered if the BindableProperty has been explicitly set. This should provide backward compatibility.

## Difficulty : Medium

This is very straightforward on iOS. On UWP however it will require editing the template used for the Switch.

**Comment by Depechie** [comment]
The UWP code is up on the Xamarin Forms Community Toolkit:
https://github.com/xamarin/XamarinCommunityToolkit/blob/dev/src/Effects/Effects/Platforms/UWP/Switch/SwitchChangeColor.cs

**Comment by rookiejava** [comment]
On tizen, 
```control.SetPartColor("bg_on",color);```

**Comment by valentinba** [comment]
Could a similar change be made to SwitchCell?

**Comment by dannythomas13** [comment]
Does this work? I am using Xamarin.Forms v3.4.0.925479-pre1 and it appears to have no effect on the rendered switch within UWP
