### ISSUE TITLE
[Enhancement] Entry: Position and color of caret

### ISSUE THREAD

**Issue by kingces95** [xamarin/Xamarin.Forms#1667]
## Rationale

Entry allows text entry into a string. Makes sense to know and set where the text will be entered into the string. Changing the visual indicator of that position is also a nice to have. 

## Implementation

```csharp
public class Entry {
    public static readonly BindableProperty CursorPosition; // int
    public static readonly BindableProperty SelectionLength; // int
    public static readonly BindableProperty CursorColor; // Color
}
```

## Expected Result

`CursorPosition` returns/sets the position at which the next character will be inserted while `CursorColor` sets the Color of the cursor. `SelectionLength` returns the length of text selection within the entry and will be zero if no text is selected. 

## Implications for CSS

None.

## Backward Compatibility

No backwards compatibility concerns. Reasonable defaults exist. 

## Difficulty : Easy

**Comment by tdyocum** [comment]
Hi @davidortinau I'd like to take this issue please.

**Comment by ddobrev** [comment]
Could you please share the planned date for this fix?

**Comment by davidortinau** [comment]
@ntherning I'm not aware of any progress on this, so unless @tdyocum already did it or wants to share progress made, I guess it's all yours.

**Comment by henricm** [comment]
@davidortinau @kingces95 could we skip the color part of this issue? Seems tricky on Android at least - haven't dug into it on UWP yet. But regardless it feels like positioning and coloring the cursor are two different things. So maybe coloring should be handled in a separate issue?

**Comment by AndrueCope** [comment]
Could someone tell me what happened to this? I'm looking at the Editor implemention in Xamarin.Forms 4.0.0.482894 and none of the properties listed at the top of this issue (CursorPosition, SelectionLength or CursorColour) are present on the Editor class. Yet the implication here seems to be that it was merged into Xamarin.Forms in April 2018.
What am I missing?

**Comment by brooksjt943** [comment]
Any chance we can get Cursor Color control for Android?
