### ISSUE TITLE
[Enhancement] SearchBar: Control over NoResultsText

### ISSUE THREAD

**Issue by kingces95** [xamarin/Xamarin.Forms#1669]
![image](https://user-images.githubusercontent.com/4120386/35463696-083422c4-0296-11e8-888a-1d4f23da5f2e.png)

See https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/auto-suggest-box
See https://stackoverflow.com/questions/14089988/how-to-change-the-text-no-results-when-search-in-tableview

## Rationale

UX may want to display a different string than the default when a SearchBar contains no suggestions.

## Implementation

At one point iOS did not support changing the text and required digging the label out. See: https://stackoverflow.com/questions/8447086/uisearchdisplaycontroller-no-results-text. May have to resort to that but we know/doc that it'll be brittle. Or maybe in that case where no first-class API exists we simply do not provide the functionality and wait for the platform to catch up. 

```csharp
public class SearchBar : View {
    public static readonly BindableProperty NoResultsText; // string
}
```

## Expected Result

String assigned to `NoResultsText` displayed if search bar contains no results.

## Implications for CSS

None.

## Backward Compatibility

None.

## Difficulty : Easy

**Comment by rmarinho** [comment]
i wonder if we can do this as a Effect , or even maybe use the suggestions api #1693 make it more general effect and add the NoResultsText to SearchBarSuggestionsEffect

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
