### ISSUE TITLE
[Enhancement] Entry: Control over text-prediction

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1677]
## Rationale

`Entry`s do not currently allow users to disable text prediction/autocomplete/autosuggest without a custom renderer or effect.

## Implementation

Add bindable property to `Entry`:

```csharp
public static readonly BindableProperty IsTextPredictionEnabledProperty = BindableProperty.Create("IsTextPredictionEnabled", typeof(bool), typeof(Entry), true);

```

Renderers will need to be updated accordingly.

### Android

- `IsTextPredictionEnabled == true`: Default. Text prediction is enabled.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

### iOS

- `IsTextPredictionEnabled == true`: Default. Text prediction is enabled. Note: may also disable autocorrect.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

### UWP

- `IsTextPredictionEnabled == true`: Default. Text prediction  is enabled.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

## Implications for CSS

None

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that an `Entry`'s text prediction defaults to enabled, as is the expected behavior now,
2. We ensure that any Effects or Custom Renderers that may have been created to produce this behavior take precedence over any values that we set, to the best of our ability.

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Easy-Medium

This is an easy-medium change and great for a first-time contributor. Biggest challenge will be ensuring that disabling text prediction does not also disable other features of the `Entry` view on all platforms.

**Comment by Swathi-Gopal** [comment]
Hi Samhouts,

I have tried with this **IsTextPredictionEnabled** property in latest Xamarin Forms version (3.1) for Entry. This doesn't work for me. I am in need of turning off/on the prediction in Entry programmatically in Xamarin Forms. 

       // Tried different options
       view.Keyboard = Keyboard.Create(KeyboardFlags.None);
       view.IsTextPredictionEnabled = false;

where view is Entry.

Can you check this or suggest any alternative for this requirement?

**Comment by jrahma** [comment]
I hope this will be added to the Editor control as well

**Comment by tmt242001** [comment]
```
<Entry IsSpellCheckEnabled="False"
       IsTextPredictionEnabled="False">    
    <Entry.Keyboard>
        <Keyboard x:FactoryMethod="Create">
            <x:Arguments>
                <KeyboardFlags>CapitalizeCharacter</KeyboardFlags>
            </x:Arguments>
        </Keyboard>
    </Entry.Keyboard>
</Entry>
```
**IsSpellCheckEnabled** and **IsTextPredictionEnabled** can not be set to false when **KeyboardFlags CapitalizeCharacter** is set.
