### ISSUE TITLE
[Enhancement] Entry: Read-only entry

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1678]
## Rationale

Currently you can set an Entry and Editor to IsEnabled false which technically makes it Read Only but it's greyed out.  Is Read Only would present the field so it looks the same when it's editable but now it's not editable.

## Implementation

Add IsReadonly property to InputView (base class of Entry and Editor)

```csharp


public static readonly BindableProperty IsReadOnlyProperty = BindableProperty.Create(nameof(IsReadOnly), typeof(bool), defaultValue: false);
```

Renderers will make the platform native entry field uneditable but how it looks will not change

Currently the Entry and Editor controls inherit form InputView so need to verify that this enhancement works for both an Entry and Editor

### Android
- `Entry.IsReadonly = true`:  should make the input control uneditable
- `Editor.IsReadonly = true`:  should make the input control uneditable
### iOS
See Android

### UWP
See Android

## Implications for CSS
```css
    user-select: none;
```
## Backward Compatibility
This is adding a new property so should be backwards compatible. Need to ensure that the property defaults to false.

## Difficulty : Easy

This is an easy change and great for a first time contributor.

**Comment by almirvuk** [comment]
Hi,

Can I be assigned to this issue :)

**Comment by rmarinho** [comment]
How does this work for iOS and UWP ?

**Comment by hartez** [comment]
> How does this work for iOS and UWP ?

Same as Android.

**Comment by PureWeen** [comment]
@hartez   I changed the spec to apply to the InputView and to verify implementation with the Entry and Editor controls

**Comment by jassmith** [comment]
Hey @almirvuk, you still working on this? If not we can move it back to the ready for work column

**Comment by almirvuk** [comment]
Had some problems :( , I am planning to finish it by the end of tommorow, is that ok?

**Comment by jassmith** [comment]
More than OK :)

I am just checking in to make sure we're not losing track of things. Thank you for your efforts!

**Comment by alanag13** [comment]
On iOS you can use: https://developer.xamarin.com/api/property/MonoTouch.UIKit.UIView.UserInteractionEnabled/

On Android you can use:
https://developer.xamarin.com/api/property/Android.Views.View.Focusable/

These will prevent text from being edited without changing the respective controls' appearances.

**Comment by almirvuk** [comment]
Thanks! @alanag13, @PureWeen I implemented also for WPF and MacOS, I am also planing to finish Tizen and GTK if that is possible... so is that ok? (asking because in intro to this Enhancement there are Android, iOS and UWP)

**Comment by rookiejava** [comment]
On Tizen you can use [`AllowFocus()`](https://developer.tizen.org/dev-guide/csapi/api/ElmSharp.Widget.html#ElmSharp_Widget_AllowFocus_System_Boolean_).

**Comment by almirvuk** [comment]
Nice, thanks @rookiejava! I am very happy for my progress (as first time XF contributor), I will need day or two more to complete this :)

**Comment by almirvuk** [comment]
@jassmith I made pull request to community repository, I am working on docs and some small improvements. I will make PR on official one in day or two 🙂

**Comment by jassmith** [comment]
Awesome

**Comment by Mikilll94** [comment]
This could be very useful if it was possible to select and copy to clipboard value from such a read-only input. Because i.e. label does not provide functionality of selecting and copying text.

**Comment by Phenek** [comment]
Hey Guys,
Thanks for this property is work like a charm!

It would be great to have it also for Picker, DatePicker, TimePicker, 
because there are also entries.
It would be nice to have :)

Regards,

**Comment by sarthak199526** [comment]
Hi guys I know this is too late but . With this read only property why Long click on entry text which opens copy selectAll option is not opening.Some might want allow user to copy and select specific text which can be easily achieved using this ReadOnly property of Entry if default entry long clicks functionality works.

Regards

**Comment by Elashi** [comment]
> Hi guys I know this is too late but . With this read only property why Long click on entry text which opens copy selectAll option is not opening.Some might want allow user to copy and select specific text which can be easily achieved using this ReadOnly property of Entry if default entry long clicks functionality works.
> 
> Regards

I believe that this is a basic requirement/feature/enhancement that should be enabled ASAP !  I cannot imagine a framework without this feature !
