### ISSUE TITLE
[Enhancement] UWP PlatformSpecific to display JavaScript alerts in WebView

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1682]
## Rationale

By design, the UWP WebView does not respond to the JavaScript `window.alert` function. In some cases, it may be useful to display the messages passed to `window.alert` in the UWP application.

## Implementation

A BindableProperty to control this behavior will have to be added to the Windows PlatformSpecifics:

```
public static readonly BindableProperty IsJavaScriptAlertEnabledProperty = BindableProperty.Create("IsJavaScriptAlertEnabled", typeof(bool), typeof(WebView), false);
```

When this PS is enabled, the UWP WebViewRenderer should inject JavaScript into each rendered page which modifies the `window.alert` function to [call `window.external.notify` instead](https://code.msdn.microsoft.com/windowsapps/How-to-intercept-854d33da). This will allow the WebView to respond to the [`ScriptNotify`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview#Windows_UI_Xaml_Controls_WebView_ScriptNotify) event and display the alert message in an alert dialog. 

## Backward Compatibility

This property will default to `false`; existing applications which rely on suppression of JavaScript alerts should not be affected. 

## Difficulty: Medium

**Comment by jassmith** [comment]
For clarity this should result in a call looking like:

```csharp
webView.On<Windows>().SetIsJavaScriptEnabled (true);
```

**Comment by alanag13** [comment]
I can take this!

**Comment by alanag13** [comment]
this is ready for review.
