### ISSUE TITLE
[Enhancement]  Color on Slider

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1684]
## Rationale

Slider doesn't offer much customization currently. Add some basic cross platform properties to reduce need for custom renderers

## Implementation

Add ThumbColor, Color, and possibly ThumbImage properties 

```csharp

public static readonly BindableProperty ColorProperty = BindableProperty.Create(nameof(ThumbColor), typeof(Color), typeof(Slider), default(Color));

public static readonly BindableProperty ThumbColorProperty = BindableProperty.Create(nameof(ThumbColor), typeof(Color), typeof(Slider), default(Color));

public static readonly BindableProperty ThumbImageProperty = BindableProperty.Create(nameof(ThumbImage), typeof(FileImageSource), typeof(Slider), default(FileImageSource));
```

### Android
When the Color property of the slider is changed this will be reflected on the slide bar.
When the ThumbColor property is changed the Thumb part of the slider will change
If the user specifies an image for the Thumb then an image will be used instead

ThumbColor and ThumbImage are mutually exclusive

### iOS
See Android

### UWP
See Android

## Implications for CSS

```css
slider {color: Red }

//with possible addition of pseudo elements
slider::thumb {color: Red }
slider::thumb {background-image: path }
```

## Backward Compatibility
Third party renderers may need to be updated to ensure that this functionality is supported through the new official mechanism. Further we will need to be careful to code the changes to the renderers in a careful manner to ensure that if someone is already using an effect support this feature that the effect is as best as possible not broken by our changes.  The current default color palette should be maintained so that after this is implemented everyone's current sliders don't change

**Comment by rmarinho** [comment]
we should make sure this is in sync with #1690 in terms of properties and naming
