### ISSUE TITLE
[UWP] Placing a ListView under Grid in a StackLayout makes the Controls in Grid behave wrong on UWP

### ISSUE THREAD

**Issue by HazyFish** [xamarin/Xamarin.Forms#1685]
### Description
In a StackLayout, if putting a ListView under a Grid, the Grid seems to be limited in Height, making the controls inside the Grid misbehave. This occurs in UWP but not in Android. When the ListView is removed, everything goes well. 

### Steps to Reproduce

1. In a StackLayout, place a ListView under a Grid. 
2. Add Controls like Entry, Button, or Label in the Grid. 
3. Run to see the unexpected UI in UWP App.

### XAML Code
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App2"
             x:Class="App2.MainPage">

    <StackLayout>
        <Grid>
            <Button Text="Button"/>
        </Grid>
        <ListView>
            
        </ListView>
    </StackLayout>

</ContentPage>
```

### Expected Behavior
<img width="581" alt="applicationframehost_2018-01-26_14-23-07" src="https://user-images.githubusercontent.com/28922700/35427504-c065e766-02a4-11e8-9fe6-83ffe0e4aac1.png">

### Actual Behavior
<img width="581" alt="applicationframehost_2018-01-26_14-25-57" src="https://user-images.githubusercontent.com/28922700/35427604-6b343bfc-02a5-11e8-8ad0-e21bbe9d94f2.png">

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.122203
- IDE: Visual Studio 2017 Version 15.5.5
- Platform Target Frameworks: 
  - Android: 7.1 & 8.0
  - UWP:  Build 16299

**Comment by PureWeen** [comment]
[App4.zip](https://github.com/xamarin/Xamarin.Forms/files/1687745/App4.zip)

Sample looks fine on Android and iOS
