### ISSUE TITLE
[Enhacement] Add BindingMode.OneTime

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#1686]
### Rationale

The data binding does not have a mode to update the binding target only when the source starts or when the data context changes. 

For the `Label` in the next example, the data binding framework in Xamarin Forms subscribes to the change on the `Status` property:
`<Label Text='{Binding Status}'` />

With `BindingMode.OneTime` it wouldn't have to watch for changes on the `Status` property:
`<Label Text='{Binding Status, Mode=OneTime}'` />

This will speed up rendering of pages with many UI controls with data which does not need to be updated by the user, for example read-only forms with lots of labels. It would also consume less memory.

**Comment by StephaneDelcroix** [comment]
> This will speed up rendering of pages with many UI controls with data which does not need to be updated by the user, for example read-only forms with lots of labels. It would also consume less memory.

In theory, yes. But do you have any numbers ?

**Comment by andreinitescu** [comment]
I don't have any numbers, but there never have been any coming the from XF team either :) for things like "fast renderers" or other optimizations.

I think we can agree it might make a difference at least from memory point of view due to no subscription to `INotifyPropertyChanged` or `INotifyCollectionChanged`. I'm thinking especially about pages which are basically forms with lots of `Labels`.

**Comment by andreinitescu** [comment]
An interesting aspect of using OneTime binding: no memory leak, because there's no subscription.
