### ISSUE TITLE
SQLite Command Builder not working

### ISSUE THREAD

**Issue by MintDeville** [xamarin/Xamarin.Forms#1687]
Hello,

I already filed the Bug with Help of Microsoft support under

https://bugzilla.xamarin.com/show_bug.cgi?id=60733

Its also in your forums under
https://forums.xamarin.com/discussion/comment/304906#Comment_304906

When is this going to be fixed?
I need this to work

**Comment by pauldipietro** [comment]
This is not a Forms issue.

**Comment by MintDeville** [comment]
Its a bug in Xamarin, as its in Visual studio Professional, which I bought. 
Get this thing working.
