### ISSUE TITLE
NavigationBar with Subtitle

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1688]
## Rationale

`NavigationPage` Header only shows a title, it would be nice it was possible to show a subtitle as well.

## Implementation

Add new bindable property to `Page`.

```csharp
public static readonly BindableProperty SubtitleProperty = BindableProperty.Create("Subtitle", typeof(string), typeof(Page), null);

```

Add new attached property `NavigationPage`.

```csharp
public static readonly BindableProperty UseSubtitleProperty = BindableProperty.CreateAttached("UseSubtitle", typeof(bool), typeof(Page), true);

```

Implement new properties on all renderers.

## Implications for CSS

None

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that a `NavaigationPage` defaults to no subtitle, as is the expected behavior now,
2. We ensure that any Effects or Custom Renderers still work
3. Should work with all the other page types
4. Make sure toolbar items and secondary toolbar items still work

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Medium

**Comment by dhaligas** [comment]
@rmarinho can we get 

LeftToolbarItem
TitleView
added to the Navigation Bar

**Comment by rmarinho** [comment]
we should look at #1716 and maybe drop this one

**Comment by samhouts** [comment]
@dhaligas See #1719 for the left aligned toolbar items and #1716 for the TitleView

**Comment by dhaligas** [comment]
thanks @samhouts .. how hard is #1719 ?  I need this one now so I am wondering if I can do this with a renderer?

**Comment by rmarinho** [comment]
I think we should close this and just look at  #1716

**Comment by netapau** [comment]
@dhaligas  I worked on it a bit here, I added an enumeration, a bindable property and I would like to do some renderers but I do not know if I'm on the right track 
https://github.com/netapau/Xamarin.Forms/blob/cf3f167aa0abd6a66360b78e148a1e2aaa4aa919/Xamarin.Forms.Core/ToolbarItem.cs#L1

**Comment by ahmedalejo** [comment]
Hi @rmarinho  #1716 TitleView looks more promising and empowering

**Comment by davidortinau** [comment]
@jassmith seems this is covered by the TitleView spec. Can we close this one?

**Comment by jassmith** [comment]
It is
