### ISSUE TITLE
[Enhancement] Button Ripple effect

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1689]
## Rationale

Create a Effect to add Ripple animation to a button

## Expected Result

Button should have a visual feedback when tapped, similar to what we see on Android..

## Difficulty : Medium

**Comment by sichy** [comment]
Can do this one too. Simple.

**Comment by nickrandolph** [comment]
How does this request align with fixing this bug - https://bugzilla.xamarin.com/show_bug.cgi?id=60188

**Comment by davidortinau** [comment]
@sichy are you working on this? Please update us with your status and in what timeframe you'll be able to make a PR.

**Comment by samhouts** [comment]
@sichy Any progress? Thanks!

**Comment by samhouts** [comment]
@sichy Monthly ping! How is it going? Thanks!

**Comment by agusibrahim** [comment]
only for button?  it's too easy. make it support for all views

**Comment by StephaneDelcroix** [comment]
this will be fixed with the `View.Visual` feature coming in

**Comment by mkieres** [comment]
@StephaneDelcroix Could you provide more details on the `View.Visual` that you're referring to?

**Comment by nickrandolph** [comment]
@mkieres I think he's referring to the support for new renderers coming as part of Shell.
@StephaneDelcroix / @davidortinau will this be available to developers even if they don't / can't adopt Shell?

**Comment by StephaneDelcroix** [comment]
@nickrandolph the 2 features are separate, you can have the material renderers without the shell
