### ISSUE TITLE
[Enhancement] Add Color on ProgressBar

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1690]
## Rationale

The progressbar currently has no way to set the color, it uses the default color of the platform

## Implementation

Add BindableProperty for ProgressColor and TrackColor to the Progressbar 

```csharp
public static readonly BindableProperty ProgressColorProperty = BindableProperty.Create(nameof(Color), typeof(Color), typeof(ProgressBar), Color.Default);
public Color ProgressColor
{
    get { return (Color)GetValue(ProgressColorProperty); }
    set { SetValue(ProgressColorProperty, value); }
}

public static readonly BindableProperty TrackColorProperty = BindableProperty.Create(nameof(TrackColor), typeof(Color), typeof(ProgressBar), Color.Default);
public Color TrackColor
{
    get { return (Color)GetValue(TrackColorProperty); }
    set { SetValue(TrackColorProperty, value); }
}
```

## Expected Result

Should be able to set the color of the ProgressBar as well as the BackgroundColor that is already possible.

### Android

```csharp

Control.TrackTintList = new ColorStateList(s_colorStates, new[] {   Element.TrackColor.ToAndroid().ToArgb() });
Control.ProgressTintList = new ColorStateList(s_colorStates, new[] {   Element..ProgressColor.ToAndroid().ToArgb() });

```

### iOS
```csharp
Control.ProgressTintColor =  Element.ProgressColor.ToUIColor();
Control.TrackTintColor =  Element.TrackColor.ToUIColor();
```

### UWP
```csharp
Control.ForegroundColor =  Element.ProgressColor.ToUIColor();
```

## Implications for CSS
None ?? 

## Backward Compatibility

Make sure Color.Default corresponds to the default color the native renderer was doing before.

**Comment by francedot** [comment]
I have already it implemented on iOS and Android. Can I be assigned to this one? /cc @adamped

**Comment by adamped** [comment]
Well not up to me, but from what I understand, first to comment, gets it :)

**Comment by davidortinau** [comment]
@francedot go for it. Let us know if you have questions.
