### ISSUE TITLE
[F100] MediaPlayer View

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1692]
## Rationale

Forms does not currently have a simple cross-platform way to play audio and video without creating a custom renderer.

## Implementation

This will probably require a `MediaSource` class similar to the `ImageSource` class, with the appropriate subclasses (`FileMediaSource`, `StreamMediaSource`, `UriMediaSource` and their respective type converters).

The actual `MediaPlayerView` should have a bindable property `Source` of `MediaSource`. The renderers for each platform should use native media players. 

The `MediaPlayerView` should have a boolean property `ControlsVisible`; when set to `false`, the transport/playback controls of the native player should be hidden.

The view should have a property `PlaybackState` with possible enum values `Unknown`, `Paused`, and `Playing`.

The view should expose events for 
`PlayRequested`
`PauseRequested`
`PlaybackStateChanged`

Renderers should respond to `PlayRequested` by attempting to play the source media in the native player. They should respond to `PauseRequested` by attempting to pause the media. Changes in native playback state should raise `PlaybackStateChanged` in the `MediaPlayerView`. 

The `MediaPlayerView` should include `SendPlay()` and `SendPause()` methods for raising the `PlayRequested` and `PauseRequested` events.

The initial version of this control will not support background playback for audio. 

## Backward Compatibility

This is a brand new View, so there should not be any backward compatibility issues.

## Difficulty: Very

In addition to playing audio/video, this control also needs to gracefully support incoming call interruption, system-wide audio requests, volume controls (software and hardware), and keeping the screen active during playback. All of these interactions are different on each platform.

**Comment by adrianknight89** [comment]
Android's stock video view isn't great, especially on older APIs and devices. I'm not sure if it's a good idea for Xamarin to create a cross-platform video player unless you're willing to put some serious effort into making a professional-grade control. I believe Google is now using ExoPlayer for YouTube and possibly other apps as well.

https://www.youtube.com/watch?v=6VjF638VObA
https://google.github.io/ExoPlayer/

If you decide to go forward with a video view, can you leverage ExoPlayer for Android? Also, @martijn00 and others have contributed to [ExoPlayerXamarin](https://github.com/martijn00/ExoPlayerXamarin) and [XamarinMediaManager](https://github.com/martijn00/XamarinMediaManager) which can be utilized instead.

**Comment by adamped** [comment]
Would also like your input here @martijn00 :) Is it wise to make this part of the XF framework?

**Comment by jassmith** [comment]
I agree that there is complexity here and the urgency to implement this is minimal. If such a thing were to be designed properly and done, fine. It is rather unlikely we will implement this ourselves.

**Comment by andreinitescu** [comment]
My suggestion is to have something like how Windows XAML has, a `MediaElement` control
See https://msdn.microsoft.com/en-us/library/system.windows.controls.mediaelement(v=vs.110).aspx

It doesn't have any UI beside actual video rendering. No volume controls, no seek bar, nada.
It does have methods like `Play()` `Pause()` `Stop()` and some events to notify when playback changed.

**Comment by hartez** [comment]
The [UWP media element](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.mediaelement#transport-controls) _does_ have UI other than the video. You can hide the transport controls, but they are available.

**Comment by andreinitescu** [comment]
@hartez Correct. I was referring to older XAML platforms (WPF, WindowsPhone, Silverlight). I guess they added it in UWP because of the unified platform idea which means unified look and feel too

**Comment by hartez** [comment]
So here's _my_ thinking, as of right now: if vanilla, out-of-the-box XF supports a media player element, it will be a basic one which utilizes the built-in native media players. Like, very, very basic. For advanced scenarios, bells-and-whistles, etc, developers will need to look at plugins (like the ones Adrian mentioned upthread) or write custom renderers. 

That's the scenario I'm currently targeting.

**Comment by andreinitescu** [comment]
@hartez I think that's what I said too. 
Can you please update the description of the ticket to reflect what you said? 
I suggest to just have a clear list of events, properties, and methods.
I think the things you mentioned in `Difficulty: Very` are not needed, nor the idea of using ExoPlayer.

**Comment by hartez** [comment]
The stuff under "Difficulty" is still relevant; at the very least, the control has to play nice with system audio events. For example, when a call comes in, the native player needs to respond by ducking or pausing; that change in state has to be reported up to the Forms control.

**Comment by charlesroddie** [comment]
Is this thread a request to make https://github.com/martijn00/XamarinMediaManager official, or to copy over code from that project, or to write a new forms media player from scratch?

**Comment by adrianknight89** [comment]
I agree with @andreinitescu that we should have a cross-platform media player (whose playback controls can be hidden when needed). Whether it will be basic or advanced is another issue, and on a personal level, I don't care if this control is part of XF or a third-party plugin. 

It looks like @martijn00 doesn't have the time to commit to working on [XamarinMediaManager](https://github.com/martijn00/XamarinMediaManager) which has NOT seen a new release in 7 months.

My concern with a basic control is that it becomes yet another impediment among others for XF developers to create a serious production app. Video is quite hot on mobile now, and things like live streaming are becoming prevalent across many apps. My recommendation for the team would be hiring Martin to work on XMM. See [here](https://github.com/martijn00/XamarinMediaManager/issues/333).

@davidortinau Would love to hear your opinion.

**Comment by andreinitescu** [comment]
@adrianknight89 In the first version of this control, I'd not put any playback controls at all, just how WPF and Silverlight works. My suggestion is to align with UWP **MediaElement**:

**Events**: MediaOpened, MediaEnded, MediaFailed, CurrentStateChanged, BufferingProgressChanged
**Properties**: Uri Source, TimeSpan Position, double Volume
**Methods**: Play(), Pause()

This will be enough for the start. Adding your own look and feel playback controls will be easy. In next iterations add more features including builtin playback controls.

**Comment by davidortinau** [comment]
@adrianknight89 I'm personally using @martijn00's project. I say we support @martijn00 over there. 

I would like to see this in Xamarin.Forms down the road.

As for how basic or advanced, what's your definition there @adrianknight89 ? What 2 or 3 features would you say are "must have" that you are concerned would be cut if we delivered a v1 basic?

**Comment by charlesroddie** [comment]
> @ andreinitescu
> Events: MediaOpened, MediaEnded, MediaFailed, CurrentStateChanged, BufferingProgressChanged
> Properties: Uri Source, TimeSpan Position, double Volume
> Methods: Play(), Pause()
I agree with this list, minus CurrentStateChanged, BufferingProgressChanged and plus Stop().

I would also suggest that these should all be instance properties on a media View. (Or an audio object if that is separate.)

MediaManager looks like the most developed media player for Xamarin.Forms, but has the above as static methods, e.g. CrossMediaManager.Current.Play.

InTheHand.Forms is also worth looking at.

**Comment by PaulVrugt** [comment]
We're using inthehand.forms for media playback. I think the implementation would be perfect for a basic video player in XF. It is a quite basic control, but does exactly what you want for basic playback. It has events, handles aspect ratio correctly. Has an option for showing/hiding default controls and supports custom http headers for a http source, which come in handy if you are streaming video from an api.

**Comment by peterfoot** [comment]
Hi, I'm the author of InTheHand.Forms and I modelled the MediaElement control on the UWP equivalent. Since then UWP MediaPlayerElement has been released which has a slightly different API. I still think the InTheHand.Forms.MediaPlayer stands up as a decent basic control which wraps the native players. I have looked into (but not started) creating renderers for macOS and WPF as these are now Xamarin Forms targets. I'd be happy to submit the control to Xamarin.Forms.

**Comment by davidortinau** [comment]
@peterfoot I spoke with @jassmith and we would like to proceed with your proposal. iOS, Android, and UWP are the primary needs. We would prefer to match the UWP API closely. 

Let us know if you would like to discuss anything in depth, or just shoot us the PR when you're ready for review. This is great! Thanks.

**Comment by davidbuckleyni** [comment]
What is the status of this has this now been created in 4 as I need to play an audio file to confirm scanning has happened correctly. Even a system sound of the phone for example beep ?.

**Comment by jrahma** [comment]
This should have an option:

1. Play Single Sound Only
2. Play Queued Sound Files in sequence
3. Play Video
4. Display Thumbnail for Video files (before start and after finished)
5. Option for Videos to Play in full screen
6. Option to keep playing sound or video even if the app is closed (though the device player)

If we are talking about recorder then there are more..


Thanks...... :)

**Comment by jrahma** [comment]
Don't forget also the Save option in case the media was played from http and user wants to save it locally in his gallery

This will be a nice feature to avoid IO Streams coding

**Comment by PaulVrugt** [comment]
@samhouts What's the holdup for this feature? The PR has been there for ages. An update about the status would be appreciated

**Comment by jrahma** [comment]
I hope it will play sounds and videos from device as well as URL

**Comment by davidbuckleyni** [comment]
From.what they told me that is the plan.

**Comment by Phenek** [comment]
Hello Guys,
Didn't see that comming!
I'm putting this here, it could help!
[Global.VideoPlayer](https://github.com/Phenek/Global.VideoPlaye)
See ya

**Comment by Phenek** [comment]
Hey @everyOne, first that is awesome! Thanks a lot.
I would like to ask to those who work on this PR, if Renderers should be enough to perform (HLS) lecture with DRM Content (FairPlay, Widevine, Microsoft PlayReady, ..) , 
in your opinion?

@peterfoot  👍
