### ISSUE TITLE
[Enhancement] ProgressBar: Height

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1694]
## Rationale

Currently there is no way to increase the height of the progress bar without using a custom effect/renderer

## Implementation

For backwards compatibility add a property to the ProgressBar to enable height scaling

```csharp

public enum ProgressBarLayoutOption
{
Default // how it currently works
FitToConstraints
}

public ProgressBarLayoutOption LayoutOption //BP

```

### iOS
A number of ways to increase the height are mentioned here
https://stackoverflow.com/questions/3437564/how-to-increase-height-of-uiprogressview

Most seem partial to
```
CGAffineTransform transform = CGAffineTransformMakeScale(1.0f, 3.0f);  
progressView.transform = transform;
```

### Android
```
<style name="CustomProgressBarHorizontal" parent="android:Widget.ProgressBar.Horizontal">
      <item name="android:progressDrawable">@drawable/custom_progress_bar_horizontal</item>
      <item name="android:minHeight">10dip</item>
      <item name="android:maxHeight">20dip</item>
</style>
```

### UWP
https://github.com/bartlannoeye-com/2016-10-ProgressBarTemplateSettings

### Android
If ProgressBarLayoutOption is set to FitToConstraints then the progressbar should size itself vertically like any other control would with the same settings

### iOS
See Android

### UWP
See Android

## Implications for CSS

```css
progressbar {height:100; }
```

## Backward Compatibility
Third party renderers may need to be updated to ensure that this functionality is supported through the new official mechanism. Further we will need to be careful to code the changes to the renderers in a careful manner to ensure that if someone is already using an effect support this feature that the effect is as best as possible not broken by our changes.  The current default height used should be maintained. The height of the progressbar should only change when this behavior is triggered

**Comment by StephaneDelcroix** [comment]
@PureWeen afterthought: reusing ScaleY would mess up with the measurements (controls are measured pre-transforms)

**Comment by PureWeen** [comment]
@edsnider 
Yea the original request this was based on mentioned using ScaleY which I just kind of ran with (I should have researched it a bit better). I'm thinking the original idea for ScaleY came about because when googling around a lot of the top answers for increasing the height are to apply Scale transforms but I do feel like if we use ScaleY we'll be answering the "Why does progressbar use scaleY?" question for years.    I modified the spec to work off of height.

**Comment by edsnider** [comment]
@PureWeen awesome- yea, I think the Height property is more intuitive for declaration even if it ends up being used to set a ScaleY property in the renderer.

**Comment by edsnider** [comment]
Is anyone working on this one yet? If not I can take it. I have done this in custom renderers for iOS and Android so have a good starting point.

**Comment by PureWeen** [comment]
No. @StephaneDelcroix  just removed himself and it'd be awesome to get this one completed!! Especially now that we can add some colors to the progress bar it'd be great to make it bigger.

**Comment by edsnider** [comment]
Ok great!

**Comment by edsnider** [comment]
When changing the `ProgressBar`'s height on iOS - either by `CGAffineTransform.MakeScale` or by resetting `Layer.Frame` the edges around the corners are blurred. 

Best way I have been able to fix this is by using `TrackImage` and `ProgressImage` to set colors instead of `TrackTintColor` and `ProgressTintColor`.

`TrackImage` and `ProgressImage` can be set by creating a `UIImage` with the specified color on the fly.

Any thoughts?

**Comment by PureWeen** [comment]
Do you by chance have a fork you're working against or other that I can pull down, see the effect, and play around with a bit?

**Comment by edsnider** [comment]
@PureWeen yes, I'll get it pushed up so you can take a look.

**Comment by PureWeen** [comment]
@edsnider  are you still working on this? Did you get any code pushed by chance that I can look at?

**Comment by edsnider** [comment]
@pureween yes - sorry the delay. Will get back on it :-)

**Comment by samhouts** [comment]
@edsnider Any progress? Thanks!

**Comment by samhouts** [comment]
@edsnider Monthly ping! How is it going? Thanks!

**Comment by sethom** [comment]
I can't wait until this feature is in! Any updates?

**Comment by toomasz** [comment]
Any updates? Looking forward to use it, thanks!

**Comment by alexmartinezm** [comment]
Any progress here?

**Comment by PureWeen** [comment]
This is probably going to be closed once we push the material visual changes. The material ios ProgressBar supports height out of the box so that can just be used.

**Comment by davidortinau** [comment]
Material for Visual is in 3.6.0 and you can set height on ProgressBar there. Closing this issue in favor of that solution. Will entertain objections.

**Comment by vgdh** [comment]
good future!
