### ISSUE TITLE
[Enhancement] Add Platform specific for ImeOptions 

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1696]
## Rationale

Allow to set ImeOptions  on entry so we have a better experience with the soft keyboard.

## Implementation

Add ImeOptions platform specifc to Entry

```csharp
Entry.On<Android>().SetImeOptions(ImeFlags);
Entry.On<Android>().GetImeOptions();
```

```csharp

public static readonly BindableProperty ImeOptionsProperty = BindableProperty.Create("ImeOptions", typeof(ImeFlags), typeof(Entry), false);

public enum ImeFlags
{
	ForceAscii,
	NoPersonalizedLearning,
        NavigatePrevious,
	NavigateNext,
	NoExtractUi,
	NoAccessoryAction,
	NoEnterAction
}

public static void SetImeOptions(ImeFlags flags)

public static ImeFlags GetImeOptions()

```

### Android

Make changes on renderer to allow this to work

### iOS
none
### UWP
none

## Backward Compatibility

Should have the default value and make sure it doesn't break existing custom renderers

## Difficulty :  Easy

**Comment by alanag13** [comment]
I can take this!

**Comment by alanag13** [comment]
@rmarinho looking over this, shouldn't it be part of #1697 ?

**Comment by rmarinho** [comment]
Yeah this a a diferente feature, specific to Android, the other, my proposal is to implement for all platforms.
