### ISSUE TITLE
[Enhancement] Add ButtonType for return Entry and done Editor

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1697]
## Rationale

Allow to customize the Return button on Entry and Done one Editor using a new api for ReturnButtonType,
Users could use the Enum to set to a particular button type, use the default, or specify a text to be shown or a image

Try to implement https://github.com/brminnick/EntryCustomReturnPlugin for Entry and Editor

## Implementation

```csharp

public static readonly BindableProperty ReturnButtonTextProperty = BindableProperty.Create("ReturnButtonText",
                typeof(string),
                typeof(Entry),
                string.empty);

public static readonly BindableProperty ReturnButtonImageProperty = BindableProperty.Create("ReturnButtonImage",
                typeof(FileImageSource),
                typeof(Entry),
                null);

public static readonly BindableProperty ReturnButtonTypeProperty = BindableProperty.Create("ReturnButtonType",
                typeof(ReturnButtonType),
                typeof(Entry),
                ReturnButtonType.Default);

public static readonly BindableProperty ReturnCommandProperty =  BindableProperty.Create(
               "ReturnCommand",
                typeof(ICommand),
                typeof(Entry));

public static readonly BindableProperty ReturnCommandParameterProperty  = BindableProperty.CreateAttached ("ReturnCommandParameter",
                typeof(object),
                typeof(Entry));


public enum ReturnButtonType
{
	Default,
	Done,
	Go,
        Image,
	Next,
	Search,
	Send,
        Text,
}

```

## Backward Compatibility

Should have the default value and make sure it doesn't break existing custom.
ReturnCommand should work with Completed event

**Comment by brminnick** [comment]
Hey @rmarinho, I'm happy to help with this! Do you have an idea in mind for how `ButtonType` should be architected? I did it as an `enum` in `EntryCustomReturnPlugin`: 

```
	public enum ReturnType
	{
		Default,
		Done,
		Go,
		Next,
		Search,
		Send,
	} 
```

**Comment by rmarinho** [comment]
@brminnick that would be great, i have looked at your work, we want to add something similiar will love your help. We are finishinig this spec first, feel free to add feedback.

**Comment by StephaneDelcroix** [comment]
why are those attached BPs ?
