### ISSUE TITLE
[Enhancement] Icon on TabbedPage UWP

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1705]
## Rationale

Currently Icon are only surface onto iOS and Android and are not shown for the tabs on UWP. Ideally this behavior would work the same across all three platforms

## Implementation

The Forms side of the code is already implemented for this so the main effort is with the UWP TabbedPageRenderer to materialize those icons onto the tabs

### Android
Already works

### iOS
Already works

### UWP
Show icon images

## Backward Compatibility
If users have already implemented a custom renderer against the UWP TabbedPage that adds the icons what's the best way for this to be implemented to reduce that friction?

For UWP this will need to be turned on through Platform specific code
```
layout.On<Windows>()
```
Otherwise icons are just going to show up and surprise people

**Comment by Depechie** [comment]
I already tried fixing this from outside the main Xamarin Forms repo - [http://depblog.weblogs.us/2017/07/12/xamarin-forms-tabbed-page-uwp-with-images](http://depblog.weblogs.us/2017/07/12/xamarin-forms-tabbed-page-uwp-with-images).
The actual problem was getting hold of the correct style being used for the tabs in UWP.

Maybe I can try to fix this in the main repo now?

**Comment by jassmith** [comment]
@Depechie still planning on working on this? If not we can move it back to the ready for implementation column

**Comment by PureWeen** [comment]
@Depechie   if you're still planning to work on this take note of the additional notes in *Backward Compatibility*

**Comment by Depechie** [comment]
@jassmith @PureWeen sorry guys... bit swamped with other work :/
Still want to tackle this, bit indeed need some time to sit down and do it right. So for now yes, please, move it back to Ready for implementation.
Sorry...

**Comment by jassmith** [comment]
No problem amigo, no hard feelings at all. We're just making sure stuff is being tracked :)

**Comment by lateralusX** [comment]
PR including fix for this issue, #1952.
