### ISSUE TITLE
[Enhancement] Picker border customization

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1710]
## Rationale

`Picker` borders can't be customized without effects or custom renderers.

## Implementation

```csharp
public static readonly BindableProperty BorderThicknessProperty =
     BindableProperty.Create(propertyName: nameof(BorderThickness),
	     returnType: typeof(Thickness), declaringType: typeof(Picker));
		
public static readonly BindableProperty BorderColorProperty =
    BindableProperty.Create(propertyName: nameof(BorderColor),
		returnType: typeof(Color), declaringType: typeof(Picker));

public static readonly BindableProperty BorderFillColorProperty =
	BindableProperty.Create(propertyName: nameof(BorderFillColor),
		returnType: typeof(Color), declaringType: typeof(Picker));
```

Renderers will frame the `Picker` based on the supplied Border properties

### Android
- `Picker.BorderThickness`:  should set the thickness of the border
- `Picker.BorderColor`:  should set the outline colors of the border
- `Picker.BorderFillColor`:  should set the internal fill on the border. If fill color is different than Border Color you'll have   | Border Color | Fill Color | Border Color | Component

### iOS
See Android

### UWP
See Android

## Implications for CSS
```css
{border-color: coral;}
{border-width: thin;}

// Fill color possible with addition of pseudo elements
picker::borderfill
{
color
}
```
## Backward Compatibility
This is adding a new set of properties so should be backwards compatible. Need to ensure that if the user doesn't specify any of these properties that the `Picker` appears normal

## Difficulty : Medium
See #1681

**Comment by hartez** [comment]
Rolling this into #1695.
