### ISSUE TITLE
[Enhancement] Page TitleView

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1716]
## Rationale

Users can currently set a text-only title on a `Page` that is inside of a `NavigationPage`, and that title will be shown in the `NavigationBar`. Adding a `TitleView` attached property to `NavigationPage` will offer a greater amount of design flexibility, since it will allow users to put any `View` in the `NavigationBar`.

## Implementation

Add new attached bindable property to `NavigationPage`:

```csharp
public static readonly BindableProperty TitleViewProperty = BindableProperty.CreateAttached("TitleView", typeof(View), typeof(NavigationPage), null);
```

`NavigationPage` will need to be edited to inflate and display the new `TitleView`.

### Android

- If the `NavigationBar` is visible and the child `Page`'s `TitleView` is not null, the `TitleView` will be displayed.

### iOS

See Android

### UWP

See Android

## Implications for CSS

None

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that a `Page`'s TitleView defaults to null, as is the expected behavior now.
2. We ensure that any Effects or Custom Renderers that may have been created to produce this behavior take precedence over any values that we set, to the best of our ability.

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Medium
The biggest challenge here will likely be the now variable size of the `NavigationBar`. We will need to ensure that the height is reported properly so that the `Page` is given appropriate room to render.

See https://forums.xamarin.com/discussion/84526/titleview-for-pages for original proposal.
Related to #1688

**Comment by xamarindevelopervietnam** [comment]
looking for this enhancement!
