### ISSUE TITLE
[CSS] pseudo-element selectors

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#1723]
### Description

support pseudo-element selectors for styling subcontrols
```
entry::placeholder {
    color: pink;
}
```

**Comment by davidbritch** [comment]
At the moment it's impossible to style the background colour and text colour of a `NavigationPage` using CSS. So while I can style a `ContentPage` using CSS, I have to resort to code-behind (for example) to set `NavigationPage.BarBackgroundColor` to the same `Color` that's set on my `ContentPage` using CSS.

Therefore, it'd be useful if `NavigationPage.BarBackgroundColor` and `NavigationPage.BarTextColor` could be set through CSS.  Perhaps like:

```css
::bar {
  background: lightgray;
}
```
