### ISSUE TITLE
Decouple Forms Init from DepenedencyService init.

### ISSUE THREAD

**Issue by awattar** [xamarin/Xamarin.Forms#1725]
https://github.com/xamarin/Xamarin.Forms/blob/39263f2e6009724394d30e54a2f805bb19e72063/Xamarin.Forms.Platform.iOS/Forms.cs#L102

Is there a plan to separate Dependency Service initialization form forms initialization. There are several cases when developers would like to take advantage from working DependencyService before rest of the Forms is initialized.

**Comment by PureWeen** [comment]
What's your use case?

I'm pretty sure the code you are referencing doesn't really deal with the DependencyService that's more for setting up Platform Specific implementations for each platform

The Dependency Service is it's own thing
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/DependencyService.cs

Does this issue relate to what you need?
https://github.com/xamarin/Xamarin.Forms/issues/1739

**Comment by awattar** [comment]
Hi Shane,

Thanks for the answer. The main issue is that we cannot use
DependencyService before forms init because DS is checking some internal
things that are set in Forms Init method. The only way now to deal with it
is to replace DS with other container - for example unity. What I'm
suggesting is to move DS related init from Forms init to some other place
that will be available to DS without need to cal Forms init so de devs
would be able to use it earlier.

Regards,
Michal

Michał Wesołowski

mob:  +48 606 466 866

**Comment by awattar** [comment]
We ended up using Unity just to resolve a few dependences before Xamarin Forms init.

**Comment by brianlagunas** [comment]
@weitzhandler Yes, it would be amazing if Xamarin would start adding interfaces to some of their classes. Unfortunately, Miguel would never let that happen as he does not believe in having well maintainable and testable code using patterns such as IoC which can be achieved via DI.  You have a better chance of winning the lottery than having the Xamarin team add interfaces to anything no matter how much more useful it would make their framework.

**Comment by jfversluis** [comment]
Hey everyone! It's probably clear that this won't be happening for Forms anymore and for .NET MAUI there is a different approach altogether. And it seems @brianlagunas won the lottery because there are ALL INTERFACES IN .NET MAUI! 🎉 

Closing this one, thanks everyone!
