### ISSUE TITLE
[Enhancement] iOS PlatformSpecific for UISlider

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1729]
## Rationale

There is currently no way to to set the value when tapping a slider on iOS

## Implementation.

Add a PlatformSpecific property for Slider on iOS. Customer renderer changes to subscribe to the tap event, calculate position and set the value. `((IElementController)Element).SetValueFromRenderer(Slider.ValueProperty, Value)

```csharp
Slider.On<iOS>().UpdateOnTap(true/false);
```

### Android

None

### iOS
Value of slider should be updated when tapping

### UWP

None

## Implications for CSS

None

## Backward Compatibility

We should set default to false and make sure all custom renderers continue to work even with our implementation. 
Should respect and have some UITest for InputTransparent and and IsEnabled properties.
Should work with a tap gesture by allowing bubbling of the event to the parent.

**Comment by ctartamella** [comment]
I would like to take this one.  @davidortinau

**Comment by jassmith** [comment]
@ctartamella still working on this?

**Comment by henricm** [comment]
@davidortinau I'll take a look on this now as it seems like there is no active work going on. Let me know if there is.
