### ISSUE TITLE
[F100] Camera View

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#1730]
## Rationale

Forms does not currently contain a cross platform view which allows to use and preview the camera of the device it's running on. There are some issues to be answer still, should we support control or just a preview of the image.

## Implementation.

Users should be able to choose front or rear camera and visualize the image. 
Users should be able to show default controls or not.
User should be able to capture a image and use it on Xamarin.Forms
This will probably require a `VideoSource` class similar to the `ImageSource` class, with the appropriate subclasses (`FileVideoSource`, `StreamVideoSource`, `UriVideoSource` and their respective type converters), as talked on #1692 to Support video.

```
public class CameraView : View
{
	public event EventHandler<MediaCapturedEventArgs> MediaCaptured;
	public event EventHandler<EventArgs> MediaCaptureFailed;

	public static readonly BindableProperty ShutterButtonCommandProperty = BindableProperty.Create(nameof(ShutterButtonCommand), typeof(ICommand), typeof(CameraView), null);
	public ICommand ShutterButtonCommand
	{
		get { return (ICommand)GetValue(ShutterButtonCommandProperty); }
		set { SetValue(ShutterButtonCommandProperty, value); }
	}

	public static readonly BindableProperty CameraOptionsProperty = BindableProperty.Create(nameof(CameraOptions), typeof(CameraOptions), typeof(CameraView), CameraOptions.Default);

	public CameraOptions CameraOptions
	{
		get { return (CameraOptions)GetValue(CameraOptionsProperty); }
		set { SetValue(CameraOptionsProperty, value); }
	}

	public static readonly BindableProperty ControlsOptionsProperty = BindableProperty.Create(nameof(ControlsOptions), typeof(CameraControlsOptions), typeof(CameraView), CameraControlsOptions.Default);

	public CameraControlsOptions ControlsOptions
	{
		get { return (CameraControlsOptions)GetValue(ControlsOptionsProperty); }
		set { SetValue(ControlsOptionsProperty, value); }
	}

	public static readonly BindableProperty CaptureOptionsProperty = BindableProperty.Create(nameof(CaptureOptions), typeof(CameraCaptureOptions), typeof(CameraView), CameraCaptureOptions.Default);

	public CameraCaptureOptions CaptureOptions
	{
		get { return (CameraCaptureOptions)GetValue(CaptureOptionsProperty); }
		set { SetValue(CaptureOptionsProperty, value); }
	}

}

public class MediaCapturedEventArgs : EventArgs
{
	public object Data { get; set; }
	public ImageSource Image { get; set; }
       	public VideoSource Image { get; set; }
}

public enum CameraOptions
{
	Default,
	Rear,
	Front
}

public enum CameraControlsOptions
{
	Default,
	Visible,
	Hidden
}

public enum CameraCaptureOptions
{
	Default,
	Photo,
	Video,
	PhotoAndVideo
}
```

## Implications for CSS

None

## Backward Compatibility

None

## Difficulty: Hard

**Comment by StephaneDelcroix** [comment]
that's a control you're trying to control. XF shouldn't do that. the reason is that we can not change its appearance once it's released, and it'll feel awkward in a version or 2 of iOS or Android.

**Comment by hartez** [comment]
Instead of a View, shouldn't we just provide an abstraction over the concept of capturing/selecting images from the native camera/photo implementations?

**Comment by andreinitescu** [comment]
In my opinion, this control should not have any UI, but have just methods/events/properties for functionality. It should be similar to the idea of `MediaElement` (another ticket)

**Comment by dineshmahajan** [comment]
Hi is CameraView for now is stable enough to implement I wanted it to record video

**Comment by jrahma** [comment]
User should be able to customize the buttons, show and hide specific button for example if we don't want to allow front or back camera (switch camera button) or if the user wants to have his own buttons or position the button at top, bottom, vertically right or left, etc..

**Comment by jrahma** [comment]
User should have an option to define how to record video

Just click record video button

Or

Hold to record video (the whatsapp way)

**Comment by Phenek** [comment]
Hey did'nt see that coming!

I tried something like this on my repo.
I put that here maybe it will help someone for iOS part,
The Android have to be reviewed for sure.
[Global.CameraView](https://github.com/Phenek/Global.CameraView)

Regards,

**Comment by jrahma** [comment]
It will be great if it has custom layout or custom view so it can be embed in any ContentPage or ContentView with opional buttons, e.g. Focus, Zoom, Flash On, etc..

**Comment by jrahma** [comment]
User should be able to take a photo or record a video and we should have options if we want just Photo or Just Video, and here is the complication... when we set it to both then we should have an option to make both in same view and user swipe to choose photo or video just like the regular camera app which comes with the phone or one Tap to take a photo and HolidngTap to take a video just like the Whatsapp way

**Comment by robv8r** [comment]
It's been pushed back again?

**Comment by davidbuckleyni** [comment]
It would be cool if there was a way we could add customised buttons to the camera view in similar style to snap chat and other apps.

**Comment by jrahma** [comment]
When you call it CameraView I assume that we can define the aspect ratio for the video as well as image

So if I want to take a photo sized 100x100 then I can restrict the area to 100x100

**Comment by akuehntopf** [comment]
Will it be possible to access the live preview stream data with this control? 
This would enable us to stream the data to barcode scanners, face recognizers, etc.

**Comment by ncg81** [comment]
> Will it be possible to access the live preview stream data with this control?
> This would enable us to stream the data to barcode detectors, face recognizers, etc.

@akuehntopf I second the above. 

**Xamrin Forms Team**, please don't ignore this. Without the possibility to hook into the live preview stream and consume the frames in our code, the Camera View would be of **limited use**.

**Comment by Phenek** [comment]
Relative #7934

**Comment by davidbuckleyni** [comment]
> Relative #7934

This is not relative this is merely a camera view with nothing to do with scanning two totally diff things

**Comment by Phenek** [comment]
Hello @davidbuckleyni,

Has you can see CameraView is already in progress.
When it will be done, we will be able to consume the live preview stream a in our code.
This would enable us to stream the data to barcode detectors, face recognizers, etc.

Did you get it? It will be this first pillar of your Barcode recognition!

Even more you should be able at first to use native bar code scanning with a custom renderer.
And return your result to Xamarin.Forms!

Regards,

**Comment by davidbuckleyni** [comment]
@samhouts  does this mean the bar code stuff will be worked on since it got an approval flag.

**Comment by samhouts** [comment]
@davidbuckleyni There is high interest in it, but we haven't yet committed to it. In the meantime, https://github.com/Redth/ZXing.Net.Mobile/ has a new prerelease with a lot of issue resolved!

**Comment by joehanna** [comment]
Will CameraView allow us to take multiple pictures before dismissing camera?  Thanks!

**Comment by joehanna** [comment]
I just found the Community Toolkit Sample and it is exactly what I need - thanks to all the folks involved!

**Comment by Phenek** [comment]
Hope this will come one day on Xamarin or MAUI. 👾
Any plan for a nuget package, maybe?

**Comment by jfversluis** [comment]
As is clear by now, this won't be making its way into Xamarin.Forms anymore. We have a control now in the Xamarin Community Toolkit, which will also be ported to the .NET MAUI Community Toolkit. I hope we can one day get this in .NET MAUI... 

Thanks for the input here everyone!

**Comment by joehanna** [comment]
Thanks for letting us know @jfversluis. As I have mentioned to you directly in the past, I thank you for your hard work and dedication to the Xamarin community. 

However, I cannot convey the extent of my disappointment with this decision. We trust Microsoft to give us what we need for mobile development as we jump in boots and all to support the c#/.net story, and I have done this since 2002. 

Given apple’s clear focus on delivering a better camera system each year as the main driver for people to upgrade their iPhones, I am perplexed why Microsoft cannot find the means or desire to at least support the camera natively in its toolbox rather than passing it off as an unimportant addon into the Community Toolkit. 

Unbelievable.

**Comment by jfversluis** [comment]
Thank you Joe! Both for your kind words as well as your honest feedback.

I share your sentiment. I think this is an important control to have and that is also why I made it a priority to include it in the Toolkit for now. It's better than not having something at all, I guess.

A bit of background here: what is holding us back mostly is in fact not iOS, but Android. The Android APIs for accessing the camera have been in alpha and beta and just not in a great state for a long time. If we were to implement this as a first-class citizen we want to make sure that the biggest platforms, at the very least, work without any rough edges.

Now, note that I am talking about Xamarin.Forms here. I don't know how fast things can go for .NET MAUI. Our first priority is getting on par with Xamarin.Forms and implement all the new improvements we have in mind architecturally and from there look at implementing new functional features. Like yourself, I hope that will be sooner than later, but I just wanted to give you a bit of context that it's not as simple as us deciding that it's not important enough to include.

I'd be happy to discus a bit more with you through email or another medium about your thoughts on this. I would be curious why it's an obstacle to use the Toolkit other than it's another dependency to add.

Thanks!

**Comment by pecadora6996** [comment]
Hi

I need close the cameraview in the event button. 

how can i implement it?
