### ISSUE TITLE
[Enhancement] Add API for programmatically checking if running in design mode

### ISSUE THREAD

**Issue by therealjohn** [xamarin/Xamarin.Forms#1731]
## Rationale

User’s desire a way to specify code that should only run when their code is running in a designer context such as Previewer or Live Player.

## Implementation

```
// In Xamarin.Forms
pubic static class DesignMode
{
    public static bool DesignModeEnabled { get; set; }
}
```

```
// Example usage 
if(Xamarin.Forms.DesignMode.DesignModeEnabled)
{
    // do something special
}
```

The property should be considered to have a public setter so that third-party tools can also mark this as true when they would prefer to. i.e. LiveXaml, GorillaPlayer, etc. may want to set this to true so users can do something special in those contexts. Or, perhaps it's better to make this read only and make some static method for enabling it. i.e. 

`Xamarin.Forms.DesignMode.EnableDesignMode()` 

See [UWP documentation](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.designmode#Windows_ApplicationModel_DesignMode_DesignModeEnabled). 

## Expected Result

`DesignModeEnabled` would return `true` when code is running in a preview or design-time tool. Otherwise, false. 

### Android

Nothing specific for Android.

### iOS

Nothing specific for iOS.

### UWP

Nothing specific for UWP

## Implications for CSS

None that I am aware of.

## Backward Compatibility

Uncertain, but it seems a new API like this would have little to no backwards compatibility issues.

## Difficulty: Easy

There may be some additional coordination required with the designer team for a few additions for the previewer to work with this. Otherwise, it should be simple to implement.

**Comment by StephaneDelcroix** [comment]
the implications are far from "easy"

**Comment by therealjohn** [comment]
@StephaneDelcroix Can you elaborate? I've been told that this "should be easy" so I was repeating that. I'd be curious to know further details in either direction.

**Comment by therealjohn** [comment]
I started this in #1844. The intent of this F100 issue was just for programmatic checks and did not cover things like `d:DesignHeight` etc. I believe those enhancements are more complex and out of scope for this enhancement.
