### ISSUE TITLE
Color for pickers

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#1732]
## Rationale

Allow to customize the visual appearance of Pickers (DatePicker, TimePicker, Picker)

BackgroundColor and TextColor should be a good start.

#### Picker Implementation
Use a custom ArrayAdapter implementation to set the color of the textviews

Create a PickerContentLayout class where these properties can be defined

```c#

public class PickerLayout
{
public TextColor {get; set;}
}

builder.SetAdapter(new PickerAdapter (this.Context, global::Android.Resource.Layout.SimpleListItem1, items), (s, e) => ((IElementController)model).SetValueFromRenderer(Picker.SelectedIndexProperty, e.Which));
....

		class PickerAdapter : ArrayAdapter<string>
		{ 

			public PickerAdapter (Context context, int textViewResourceId, string[] objects) : base(context, textViewResourceId, objects)			
			{
			}

			public override global::Android.Views.View GetView(int position, global::Android.Views.View convertView, ViewGroup parent)
			{
				var view = base.GetView(position, convertView, parent);
				TextView text1 = (TextView)view.FindViewById<TextView>(global::Android.Resource.Id.Text1);
				text1.SetTextColor(Color.Pink.ToAndroid());

				return view;
			}
		}
```

## Implications for CSS
need pseudo-element and selectors

**Comment by rmarinho** [comment]
We should at least define the API that we have in mind. Some tips how to implement in each platform will help.

**Comment by ravinderjangra** [comment]
@StephaneDelcroix  This has already been closed. so please close this. so no one start working on it.
https://github.com/xamarin/Xamarin.Forms/pull/84

**Comment by StephaneDelcroix** [comment]
@ravinderjangra that's different

**Comment by ravinderjangra** [comment]
@StephaneDelcroix TextColor and BackgroundColor are already added In PR. for what more options we can provide to user for customization? any suggestions?

**Comment by StephaneDelcroix** [comment]
BackgroundColor and TextColor properties applies to the Entry-like control that's part of the `Picker`, not the the dropdownlist part. this is what this issue is about.

**Comment by StephaneDelcroix** [comment]
TitleColor got merged
