### ISSUE TITLE
Label line-height

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#1734]
# Rationale

Customize vertical appearance of label by setting line-height

# Implementation

Add a LineHeightProperty

# Back-Compat

default should be `-1` so when the value isn't set, the renderers knows that they have to ignore the value

# CSS

`line-height`

# Thoughts

Should this be supported at Span level too, as a TextElement or something ?

**Comment by michaeldwan** [comment]
We implemented this with a quick and dirty effect. Our use case didn't require responding to changes so we omitted that, but it's worked well and should be straight forward to bake into Label.

### Routing effect
```csharp
public class MaxLinesEffect : RoutingEffect
{
    public int MaxLines { get; set; }

    public MaxLinesEffect() : base($"Highrise.{nameof(MaxLinesEffect)}") { }
}
```

### iOS PlatformEffect
```csharp
public class MaxLinesPlatformEffect : PlatformEffect
{
    protected override void OnAttached()
    {
        var maxLinesEffect = Element.Effects.FirstOfType<MaxLinesEffect>();
        if (maxLinesEffect == null) {
            return;
        }
        if (Control is UILabel nativeLabel) {
            nativeLabel.Lines = maxLinesEffect.MaxLines;
            nativeLabel.LineBreakMode = UILineBreakMode.TailTruncation;
        }
    }

    protected override void OnDetached() { }
}
```

### Android PlatformEffect

```csharp
public class MaxLinesPlatformEffect : PlatformEffect
{
    protected override void OnAttached()
    {
        var maxLinesEffect = Element.Effects.FirstOfType<MaxLinesEffect>();
        if (maxLinesEffect == null) {
            return;
        }

        if (Control is TextView nativeTextView) {
            if (maxLinesEffect.MaxLines <= 0) {
                nativeTextView.SetMaxLines(99999);
            } else if (maxLinesEffect.MaxLines == 1) {
                nativeTextView.SetSingleLine(true);
                nativeTextView.Ellipsize = TextUtils.TruncateAt.End;
            } else if (maxLinesEffect.MaxLines > 1) {
                nativeTextView.SetMaxLines(maxLinesEffect.MaxLines);
                nativeTextView.Ellipsize = TextUtils.TruncateAt.End;
            }
        }
    }

    protected override void OnDetached() { }
}
```

**Comment by hartez** [comment]
@michaeldwan Are you sure you didn't mean to post that in https://github.com/xamarin/Xamarin.Forms/issues/1706?

**Comment by michaeldwan** [comment]
@hartez 🤦‍♂️

**Comment by henricm** [comment]
Apologize if this is already obvious, but any thoughts on type and unit for line-height? I'm guessing `double`?
And for unit - android for example - should it be dp, px etc?

**Comment by StephaneDelcroix** [comment]
y, double. for mapping to device-units, check what we do elsewhere

**Comment by henricm** [comment]
I've now added LineHeight on Label and Span (see latest commit above for details). It would be great to get some feedback on a few things described below that I've discovered so far.

On Android I've added implementation which allows different line heights in the same Label. However on iOS it doesn't seem to work. Even though we set different styles for each NSAttributedText it only uses the style set on the first span.
On UWP I haven't found any Span like support yet. 
Also on UWP there is only LineSpacing property, not a multipler/relative one. Since we've decided that the Xamarin.Forms Label.LineHeight should be relative one, maybe we should try to convert that on UWP so it behaves as on iOS/Android.

This image illustrates the variable line-height issue on iOS (and UWP). The first label has the line height entered in the text field.
The second colorful label has different Spans set to the line height indicated at the beginning of the string.

![image](https://user-images.githubusercontent.com/3715975/37523383-0e8ab392-2927-11e8-95c2-de801f1ecc19.png)

**Comment by titonton** [comment]
I realized I commented on the PR of this issue. apologies. I had updated to the newest stable version 3.2 and the Line height isn't working for me. this is what I have on my xaml file

``
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="BizPass.Components.ActivityItemNew"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:custom="clr-namespace:BizPass.Controls">
    <StackLayout HorizontalOptions="Fill" VerticalOptions="FillAndExpand">
        
        <ffimageloading:CachedImage x:Name="imgView"  Source="{Binding Thumbnail}" Aspect="AspectFill" FadeAnimationEnabled="True"/>
        <Label x:Name="NameBinding" Text="{Binding Name}" HorizontalTextAlignment="Center" TextColor="#002e62" 
               HorizontalOptions="CenterAndExpand" 
               VerticalOptions="StartAndExpand" 
               FontFamily='{OnPlatform Android="SourceSansPro-SemiBold.ttf#SourceSansPro-SemiBold", iOS="SourceSansPro-SemiBold"}'
               LineHeight="10.0"/>
        
        <Label x:Name="PointBinding" Text="{Binding Points, StringFormat='{0} Points'}" TextColor="#c4950b" HorizontalOptions="Center" VerticalOptions="EndAndExpand">
            <Label.FontFamily>
                <OnPlatform x:TypeArguments="x:String">
                    <On Platform="iOS" Value="SourceSansPro-Bold"/>
                    <On Platform="Android" Value="SourceSansPro-SemiBold.ttf#SourceSansPro-Bold"/>
                </OnPlatform>
            </Label.FontFamily>
        </Label>
    </StackLayout>
</ContentView>
``

**Comment by PrvnKmr** [comment]
@titonton Did you find any solution for this? Giving the LineHeight property to the label won't set the desired font to the label. It goes to the default font in my case.

**Comment by StephaneDelcroix** [comment]
@titonton is your issue the same as #3344? If not, please open a new issue. we do not monitor discussions on closed PRs
