### ISSUE TITLE
[Android] ListView Cell height not adjusted when using large display size and font

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1735]
### Description
When using large font size and display size, text in a list view gets cut off.

Note that I realize the issue may be from setting the Row Height. But the row height is set as a dp value, and should be multiplied by the display size setting, correct? 

### Steps to Reproduce
Load app on Android 7 or higher device.
Press the button
Note that the listview looks fine
Minimize app
Go to settings -> display
Set font size to Largest
Set display size to larger
Go back to app
Press the button
Note that that font in the list view cells is cut off (see screen shots) 

### Expected Behavior
List view looks fine

### Actual Behavior
Text gets cut off

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  Nope
  - Android: 7+
  - UWP:  Nope
- Android Support Library Version: 25
- Nuget Packages:
- Affected Devices: Any running Android 7+

### Screenshots
https://imgur.com/a/bM3vU

### Reproduction Link
https://www.dropbox.com/s/ec1n1o2kknjn6eq/ListViewBigFontSample.zip?dl=0

**Comment by PureWeen** [comment]
What device specifically are you running this on?
I ran a few tests on a Pixel XL emulator and it seems to look good

Largest
![image](https://user-images.githubusercontent.com/5375137/35585066-1f25e898-05b4-11e8-9bd8-70aa6f593762.png)


Default
![image](https://user-images.githubusercontent.com/5375137/35585124-46172174-05b4-11e8-95de-c552658ff068.png)



![image](https://user-images.githubusercontent.com/5375137/35585521-5dc2fb08-05b5-11e8-9daf-f96752fdb940.png)

**Comment by Paul-Brenner-Tangoe** [comment]
Looks like you have to run this on a device with a small screen. I cannot reproduce on a Nexus 5x or a Nexus 6, but I can reproduce it on an emulator with a small resolution. The emulator I am using in those screen shots is from genymotion - "Custom Phone - 768 x 1280 " running Android 7.

**Comment by Paul-Brenner-Tangoe** [comment]
@PureWeen can you remove this from needs-info?

**Comment by jassmith** [comment]
Interesting. wonder what is different about the small devices that causes this. I think just the dpi/size disparity overloads the screen at last.

**Comment by samhouts** [comment]
@Paul-Brenner-Tangoe Are you still experiencing this issue? Thanks!

**Comment by rostyslav-gryb** [comment]
@samhouts it happens for me 
![screenshot_1549304318](https://user-images.githubusercontent.com/7997730/52228086-1d2c9580-28ba-11e9-9f9f-298ac8e12e49.png)

I took the sample project and updated XForms to v3.4.0.1029999 and Xamarin.Android.Support to v28.0.0.1. On emulator "Nexus 6 480x800 hdpi" running Android 7.1.1 this issue happens with default font and display sizes, and with increased sizes it becomes worse.

**Comment by samhouts** [comment]
@rostyslav-gryb Ah, too bad! Thank you for taking the time to look into this, and thank you for letting me know.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
