### ISSUE TITLE
can't reference gtk platform

### ISSUE THREAD

**Issue by yinyue200** [xamarin/Xamarin.Forms#1737]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
can't reference gtk platform
I think revert #1629 could fix the issue.
### Steps to Reproduce

1. install the nuget via PackageReference  (not packages.config)
2. 
3. 

### Expected Behavior
Xamarin.Forms.Platform.GTK is be referenced

### Actual Behavior
Xamarin.Forms.Platform.GTK isn't be referenced

### Basic Information

- Version with issue:2.6.0.132747-nightly
- Last known good version:2.6.0.99477-nightly
- IDE:VS 2017 15.5.5
- Platform Target Frameworks: v4.7.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![devenv_2018-01-30_09-21-32](https://user-images.githubusercontent.com/13848771/35543257-10c3fc28-059f-11e8-8813-3b108d2b6e95.png)

### Reproduction Link

[Reproduction Link](https://github.com/yinyue200/gtkforms)

**Comment by mattleibow** [comment]
Maybe not a REVERT as such but rather the removal of the `<references>` nodes. I am not sure what that is for since those assemblies are already in the actual NuGet package...

**Comment by mattleibow** [comment]
This also needs to be fixed for these packages:
https://github.com/xamarin/Xamarin.Forms/search?utf8=%E2%9C%93&q=references+extension%3Anuspec&type=

**Comment by mattleibow** [comment]
Just a note. This appears to sometimes work with the old packages.config file, but does not work at all with the <PackageReference>

**Comment by jsuarezruiz** [comment]
I'm going to review this Issue.

**Comment by rmarinho** [comment]
fixed by #1772
