### ISSUE TITLE
Xamarin Forms WebView first time do Google search navigation, CanGoBack will return false

### ISSUE THREAD

**Issue by hachi1030-Allen** [xamarin/Xamarin.Forms#1738]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
This is Allen from AGPC support team. I have one customer that is having issue with Xamarin Forms WebView control. The issue symptom is that we simply use WebView to load Google as start page, and when we do a simple search in Google, it will navigate to the list of the search result page, and the GoBack button we declared for that should be enabled, but it does not. If we navigate again to further websites in that list, the GoBack button will work normally.
### Steps to Reproduce
The customer has sent me the sample project, I will share later, and his structure is as below steps:
1. Create a Xamarin Forms project, (PCL or .NET Startdard).
2. The App.xaml.cs is declaring the MainPage as the samplePage he declared.
3. In the samplePage, it's a Tabbed Page with MyPage as local page inside it, code as below:

``` XAML
   <?xml version="1.0" encoding="utf-8"?>
   <TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" 
                          xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:sample" x:Class="sample.samplePage">
           <local:MyPage/>
    </TabbedPage>
```

4. In the MyPage.xaml.cs, it will declare a page that contains a WebView control and 2 buttons for navigation:

``` XAML    
<StackLayout>
            <!--Webseiten Anzeige-->
            <WebView Source="https://www.google.com/" x:Name="o_webview" WidthRequest="1000" HeightRequest="1000" Navigating="webOnNavigating" Navigated="webOnEndNavigating" />
            <!--Laden indicator-->
            <Label x:Name="LoadingLabel" Text="Lädt..." HorizontalOptions="Center" IsVisible="false" />
            <StackLayout Orientation="Horizontal" Padding="10,10">
                <!--Zurück Knopf-->
                <Button x:Name="o_back" Text="&lt;" FontSize="Large" HorizontalOptions="StartAndExpand" Clicked="backClicked" />
                <!--Forwärts Knopf-->
                <Button x:Name="o_forward" Text="&gt;" FontSize="Large" HorizontalOptions="End" Clicked="forwardClicked" />
            </StackLayout>
        </StackLayout>
```

In the code-behind, there will be code that controls the button click event handler and most importantly is that we declare the Navigated event handler as below function:

``` csharp
        void webOnEndNavigating(object sender, WebNavigatedEventArgs e)
        {
            LoadingLabel.IsVisible = false;

            o_back.IsEnabled = o_webview.CanGoBack;
            o_forward.IsEnabled = o_webview.CanGoForward;

        }
```

5. Run the sample in iPhone simulator and Android phone.
6. The first page of the WebView is Google, we type anything in the search bar and click Search or we click on the dropdown list that google provided for Intelligence guess. Then the page will be navigated to the search result list of Google.

### Expected Behavior
Expected behavior should be after navigated to the search result page, the GoBack button should be enabled.
### Actual Behavior
The GoBack button will be disabled.
### Basic Information

- Version with issue: Xamarin.Forms v2.5.0.122203
- Last known good version: No known good version.
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: 8.0
  - UWP:  No use of UWP

- Affected Devices: iPhone simulators and Android phones

### Screenshots
![image](https://user-images.githubusercontent.com/32292089/35544997-fb6f0508-05a7-11e8-89b3-8378905defbf.png)

### Reproduction Link
Sample project: 
Please download from: 
https://drive.google.com/open?id=1KcH6utas6HkY76u3NSo7MSWBvlNsOFoa 

Symptom video:
https://drive.google.com/open?id=1gRL59RRvTHpn1MdIjKDFepYbJ9BmE6X3

**Comment by hachi1030-Allen** [comment]
Update something here. Since the issue video is recorded under iPhone simulator, so I tried to build one native iOS application using WKWebView and the issue cannot be reproduced on native platform. That's why I am thinking this issue should be Xamarin Forms issue.

**Comment by PureWeen** [comment]
Yea there's definitely a race condition going on here.. It seems the Navigated fires before CanGoForward and CanGoBack get set

As a small workaround I noticed that if you inject a slight delay it's enough for those settings to be accurate

```
 async void webOnEndNavigating(object sender, WebNavigatedEventArgs e)
        {
            LoadingLabel.IsVisible = false;
            
            await Task.Delay(10);
            o_back.IsEnabled = o_webview.CanGoBack;
            o_forward.IsEnabled = o_webview.CanGoForward;
             
        }
```

**Comment by hachi1030-Allen** [comment]
@PureWeen Yea, after testing, looks like this is a workaround to this issue. But still looks forward to the fix of this bug.

Thanks,

Allen

**Comment by felipemomm** [comment]
Is it really wrong? You should use Navigated event, not Navigating event, for this case, IMO.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
