### ISSUE TITLE
[UWP] ViewModel Destructor never call when custom view and ListView are having same ItemSoure.

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#1740]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

In that while using only Listview in the view its working perfectly. While using custom view only in the view working perfectly. 
The issue occur only custom view and ListView are in the same view and having same ItemSource.

using customView and test it with the  PerformanceProfiler only one instance of ViewModel is in memory. Compiling to release mode also looks better. It could be that the issue happends only in debug mode. Memory consumption are very important for us.

### Steps to Reproduce

1. Run the sample.
2. Click the button continuously.
3. See the output the destructor never call.  

### Expected Behavior
Need to call the viewModel destructor properly .

### Actual Behavior
Destructor is never called.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
Did you forget to attach the repro?

**Comment by EmilAlipiev** [comment]
@PureWeen  repro is here. http://www.syncfusion.com/downloads/support/forum/135633/ze/TestSfDataGrid_51197b96

**Comment by PureWeen** [comment]
it's called for me


![image](https://user-images.githubusercontent.com/5375137/35746227-5c17a600-0803-11e8-9117-36f46a72036b.png)

Also the GC.Collect is called with a parameter of 100 but the max generation is 2
you can check
```
GC.MaxGeneration
```
for the max generation
