### ISSUE TITLE
MacOS 10.12 NativeView Layering Bug with Label

### ISSUE THREAD

**Issue by jvansickle-cei** [xamarin/Xamarin.Forms#1747]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
A Label appears under a gradient layer of a Grid on MacOS 10.12.6, works appropriately in MacOS 10.13.2

### Steps to Reproduce

1. Create xaml of a grid

<Grid x:Name="TheGrid" WidthRequest="210" HeightRequest="44" Grid.Row="1" Grid.Column="0" VerticalOptions="Center" Margin="0" Padding="0" ColumnSpacing="0" RowSpacing="0">
            <Grid.RowDefinitions>
                <RowDefinition Height="44" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="36" />
                <ColumnDefinition Width="159" />
                <ColumnDefinition Width="15" />
            </Grid.ColumnDefinitions>
            
            <Label Text="The Label" FontFamily="Segoe UI" FontSize="14" FontAttributes="Bold" TextColor="Black" Margin="0, 0 ,0 ,5" VerticalOptions="Center" HorizontalOptions="Start" Grid.Row="0" Grid.Column="1" />
            <Button Text="-" Grid.Row="0" Grid.Column="2" VerticalOptions="Start" HeightRequest="15" Clicked="Minimize" />
        </Grid>

2. Add gradient logic to a custom renderer's OnElementPropertyChanged method used for the Grid

var gradient = MakeGradientLayer();
NativeView.WantsLayer = true;
NativeView.Layer = new CALayer();
NativeView.Layer.AddSublayer(gradient);

3. Trigger gradient drawing and notice it being above the label

### Expected Behavior
Label appears on top of the gradient

### Actual Behavior
Gradient appears on top of the label

### Basic Information

- Version with issue: Xamarin.Forms.Platform.macOS 2.0.0.0
- Last known good version:
- IDE: Visual Studio For Mac Enterprise
- Platform Target Frameworks: 
  - MacOS: 10.13:	(17C76)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Mac Mini running MacOS 10.12.6

**Comment by PureWeen** [comment]
[MacPlatform.zip](https://github.com/xamarin/Xamarin.Forms/files/1692322/MacPlatform.zip)

**Comment by PureWeen** [comment]
Can you attach a repro please? I created the one above and the label appears on top for me. Though I only have 10.12 running in a VM which might not be an accurate test

**Comment by jvansickle-cei** [comment]
I solved this by using the more appropriate ReplaceSublayer method when I have to change the clip of the gradient; being that this is a more appropriate approach than reseting the NSView's Layer property and that it fixes the issue with MacOS 10.12, I am going to mark this issue as closed. If I run into a layering issue again I will be sure to provide source code to reproduce more easily as it was very complicated to get it to happen.
