### ISSUE TITLE
ListView hides first item after scrolling to bottom on Xamarin.Forms iOS side

### ISSUE THREAD

**Issue by rafaelpereira-mobrj** [xamarin/Xamarin.Forms#1751]
### Description

ListView within a StackLayout in a ContentPage does not scroll all the way to the top on iOS yet works fine on Android.

### Steps to Reproduce

1. Tap on a ListView item.
2. Scroll to the bottom of the ListView.
3. Scroll back to the top of the ListView.

### Expected Behavior

Scroll all the way to the top of the ListView to see the very first item.

### Actual Behavior

Scroll all the way to the top of the ListView, on removing the finger from the screen, ListView automatically scrolls down hiding the first item.

### Basic Information

- Version with issue: Xamarin.Forms 2.3.4.267
- Last known good version: No idea, long time issue
- IDE: Visual Studio for Mac Community 7.3.3 Build 7
- Platform Target Frameworks:
  - iOS:  11.2
  - Android:  7.1
- Affected Devices: iPhone 5C, iPhone SE, iPhone 7 Plus

### Videos and Reproduction Link

[movies_and_xaml.zip](https://github.com/xamarin/Xamarin.Forms/files/1678857/movies_and_xaml.zip)
Zip above contains two videos showcasing the problem and the original xaml page (without the xaml.cs codebehind file).

### Other info

Tried to test on more recent Xamarin.Forms versions without success, kept getting an error on compile. Haven't had time yet to set up a project reproducing the problem.

**Comment by PureWeen** [comment]
For now I'm going to move this into more info until there's a repro

I tested a few different ListView variations on iOS 7 and iOS 8 and I couldn't recreate the behavior
Personally I haven't seen this issue

**Comment by samhouts** [comment]
@rafaelpereira-mobrj Have you had a chance to get a repro ready yet? Thanks

**Comment by PureWeen** [comment]
Closing for now. If still happening please attach a repro and reopen

**Comment by patsadow2** [comment]
The same issue

**Comment by Amaro96** [comment]
@Triage remove this like Closed I have the same issue
