### ISSUE TITLE
ControlTemplate's visible but transparent views mask user taps

### ISSUE THREAD

**Issue by programmation** [xamarin/Xamarin.Forms#1758]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

Given an app that uses a `ControlTemplate` to provide functionality, if the `ControlTemplate` has a `ContentView` above its `ContentPresenter` (i.e. after it in the XAML), the `ContentView` masks user taps unless its `IsVisible` property is set to false.

This is a breaking change from previous versions of Xamarin.Forms, where it was sufficient to set the `ContentView`'s `Opacity` to `0.0` (transparent) and events would pass through to views underneath.

### Steps to Reproduce

Please see repro app included with this report. 

The app has two pages labelled "Failing" and "Working".

Tap the button on the "Failing" page and nothing happens.
Tap the button on the "Working" page and an alert appears.

Both pages have a `ControlTemplate` with a `ContentPresenter` underneath a `ContentView`. 

On the "Failing" page's `ControlTemplate` the `ContentView`'s `Opacity` is set to `0.0`, while its `IsVisible` is set to `true`.
On the "Working" page's `ControlTemplate` the `ContentView`'s `Opacity` is set to `0.0`, while its `IsVisible` is set to `false`.

### Expected Behavior

In previous versions of Xamarin Forms, both pages would work, i.e. `IsVisible` would have no effect on the pass-through of events to layers beneath the top `ContentView`.

### Actual Behavior

The `ContentView` has to have its `IsVisible` set to `false` in addition to `Opacity` set to `0.0` in order for events to pass through to layers underneath.

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: At least 2 releases prior
- IDE: VS Mac
- Platform Target Frameworks: === Visual Studio Community 2017 for Mac (Preview) ===

Version 7.4 Preview (7.4 build 884)
Installation UUID: 6c4f5aaf-4e3e-4121-aa23-b12d8d6df997
Runtime:
	Mono 5.8.0.108 (2017-10/9aa78573ee2) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 508000108

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.3
	2.0.0
	1.1.2
	1.1.0
	1.0.5
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.1.2
	2.0.0
	1.0.4
	1.0.0-preview2-1-003177
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.Mac ===

Version: 4.2.0.8 (Visual Studio Community)

=== Xamarin.Android ===

Version: 8.2.0.6 (Visual Studio Community)
Android SDK: /Users/davidd/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0-beta1+69
Hash: 4012b4e
Branch: master
Build date: Thu, 07 Dec 2017 16:20:26 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 11.8.0.8 (Visual Studio Community)
Hash: eaff169d
Branch: d15-6
Build date: 2018-01-09 18:39:05-0500

=== Build Information ===

Release ID: 704000884
Git revision: d383ef2e3a41f2c5071929bbf509796816f4599e
Build date: 2018-01-11 02:34:20-05
Xamarin addins: ae86035c1173492d6ade401296b20c4a5e0e7205
Build lane: monodevelop-lion-d15-6

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

MvvmCross Template pack 2.0.1
AddinMaker 1.4.1
FileNesting 0.1.1
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.2
Paket 0.3
xUnit.NET 2 testing framework support 0.7.5
Internet of Things (IoT) development (Preview) 7.1

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[ControlTemplateTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1681428/ControlTemplateTest.zip)

**Comment by PureWeen** [comment]
The behavior change you're seeing was intentional and came about in an effort to align how this works between the three platforms
https://github.com/xamarin/Xamarin.Forms/pull/935
> With this change, input transparency is entirely a function of the InputTransparent flag; if a layout is marked InputTransparent, then clicks/taps/gestures will pass through it to controls below. Visual transparency (i.e., Opacity and the transparency of the background color) no longer has any bearing on whether a layout is is input transparent.

**Comment by programmation** [comment]
This is a breaking change. Was it highlighted anywhere in release documentation? I recall seeing the PR you mentioned and that's what triggered my experiment with the `IsVisible` flag. NB: `IsVisible` appears to have the same effect as `InputTransparent`. Why is this? Why have two flags that apparently do the same thing? Is one deprecated?

**Comment by programmation** [comment]
Looking at release notes history I see that the PR you referenced landed in XF 2.4. However there's no mention of a breaking change, and no mention of its impact on iOS either. The only comments are about Android.
