### ISSUE TITLE
[Android] Child elements are not layout for custom controls if detail page is navigated at runtime in MasterDetailPage in Xamarin Forms Android platform

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#1764]
Hi All,

We have previously raised an query regarding the child elements did not get layout for Custom controls(Similar to ListView control) if we switch the detail page from Master page menu icon. 

Please refer the report link below.
https://github.com/xamarin/Xamarin.Forms/issues/1421

But you have moved the status into **Invalid**. 

Though the issue may occur in **Custom control**, we couldn't able to recognize the issue where the actual root cause at our end. It seems that the issue arises while layout the custom view with framework element(Master detail page). Could you please ensure the same and revert us asap.

P.S.
Since, the query may not directly related to Xamarin Forms, but if we are requesting an query means then, you need to provide a valid response instead of the query is not directly related to Xamarin Forms.

Ensure it from your side and reopened the task.

Thanks in Advance,
Dinesh B

**Comment by PureWeen** [comment]
There are a couple open issues around scrollviews on Android right now
https://github.com/xamarin/Xamarin.Forms/issues/1332
https://github.com/xamarin/Xamarin.Forms/issues/1736

That look like they may address the issue you are having

I'm thinking once those are resolved this should start working for you on android
Thoughts?

**Comment by samhouts** [comment]
Closing in favor of #1839
