### ISSUE TITLE
Cannot build .NET Core app that reference Xamarin.Forms

### ISSUE THREAD

**Issue by praeclarum** [xamarin/Xamarin.Forms#1777]
### Description

When you reference Xamarin.Forms from a .NET Core app, the build fails with:

> error MSB4062: The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly /Users/fak/.nuget/packages/xamarin.forms/2.5.0.122203/build/netstandard1.0/Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [/Users/fak/Dropbox/Projects/Ooui.Try2/PlatformSamples/AspNetCoreMvc/AspNetCoreMvc.csproj]

### Steps to Reproduce

1. Make a .NET Core app
2. Reference XF 2.5
3. Build

### Expected Behavior

Build succeeds

### Actual Behavior

The above error is returned.

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: VSCode + VS for Mac

**Comment by PureWeen** [comment]
[XFtest.zip](https://github.com/xamarin/Xamarin.Forms/files/1691297/XFtest.zip)

The attached project builds for me inside VS for Mac but not through the dotnet cli

https://github.com/xamarin/Xamarin.Forms/pull/1284

**Comment by drznathou** [comment]
Hi,
Same problem, same setup

**Comment by StephaneDelcroix** [comment]
this is probably resolved on 3.0.x. could you try one of the -nightly build ?

**Comment by drznathou** [comment]
Error is gone don't know freaking know how...Wish I did

I should say that I went back on compiling using Android 7.0

**Comment by drznathou** [comment]
@StephaneDelcroix I tried and succeeded installing 3.0.x but I broke down my android project during the "process" of uninstalling packages so I git revert "ed" one project.
Git wins again

**Comment by jassmith** [comment]
We believe this is fixed in 3.1.0, please re-open if not fixed.
