### ISSUE TITLE
[iOS] Map Memory Leak in ListView Header

### ISSUE THREAD

**Issue by czuvich** [xamarin/Xamarin.Forms#1779]
### Description

When using a Map custom renderer inside of a ListView header, the Map is not being released and is leaking memory.

### Steps to Reproduce

1.  Navigate to a Page with a Map in a ListView header. 
2.  Navigate back to the original page.
3.  The map Dispose() is never invoked nor is OnElementChanged. The map never gets released.
4. Repeat.

### Expected Behavior

Dispose() should be invoked and the native map released.

### Actual Behavior

The app eventually crashes with VectorKit being referenced in the stack trace.  I've attached a sample log that references thread 85 which is running the Map thread.

### Basic Information

- Version with issue:
Maps & Forms 2.5.0.122203
iOS 11.2

- Last known good version:
Not sure

- IDE:
Visual Studio Mac

### Crash Logs

[crash dump 1.txt](https://github.com/xamarin/Xamarin.Forms/files/1687492/crash.dump.1.txt)

### Reproduction Link

I've put in two tests.  Notice how the behavior varies between a page with a ListViewHeader map, and a page that does not have it.  The results differ and the leak is present on the ListView.

[TestiOSMapLeakListViewHeader.zip](https://github.com/xamarin/Xamarin.Forms/files/1687498/TestiOSMapLeakListViewHeader.zip)

**Comment by galadril** [comment]
I have the same issue, but my Map component is in the listview itself (not the header)
Do you also have a work around maybe?

**Comment by czuvich** [comment]
As a workaround, I ended up keeping a reference to the MapView when the page gets pushed onto the stack, and then disposing of it manually when the page is popped.  Seems to work ok so far.

**Comment by galadril** [comment]
Hmm the problem is that my listview can contain like 4 rows of maps :)

**Comment by czuvich** [comment]
That's fine as long as you can grab the reference and dispose of them manually before the page is destroyed.

**Comment by czuvich** [comment]
Any updates?

**Comment by samhouts** [comment]
Since there is a workaround for this issue, I will go ahead and close it now. We are focusing on CollectionView as a resolution for issues such as this. Thank you!

**Comment by samhouts** [comment]
Duplicate of #1877
