### ISSUE TITLE
[UWP] Calling Display Alert from Windows Assigned Access causes app to crash

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1790]
### Description
If an app is opened via a share target then Xamarin Forms crashes when checking IsInvokedRequired

```
		public bool IsInvokeRequired => LockApplicationHost.GetForCurrentView() != null
			? !CoreApplication.GetCurrentView().Dispatcher.HasThreadAccess
			: !CoreApplication.MainView.CoreWindow.Dispatcher.HasThreadAccess;
```

See screen shot for exception

### Steps to Reproduce

1.  Run the attached reproduction
2. Close the app
3.  share something of content type "TEXT" to the app .  I was just using the MAP app and sharing from there

The code calls DisplayAlert from the *OnShareTargetActivated* override on uwp.

### Basic Information

- Version with issue: Xamarin Forms: 2.5.0.122203 
- IDE: VS 2017
- Platform Target Frameworks:
  - UWP:  16299 

### Expected Behavior
The app should Display the Alert and not crash

### Actual Behavior

The app crashes

### Screenshots

![image](https://user-images.githubusercontent.com/5375137/35771375-068c30f2-08e9-11e8-933c-317f1e948dd0.png)

### Reproduction Link

[App4.zip](https://github.com/xamarin/Xamarin.Forms/files/1964739/App4.zip)

**Comment by AlexF12004Roma** [comment]
Is there a workaround for this issue?
I cannot publish any UWP app with share option due to this bug?

**Comment by PureWeen** [comment]
I posted some workarounds for some scenarios here
https://github.com/xamarin/Xamarin.Forms/issues/1783

**Comment by ryanholden8** [comment]
FWIW - Currently encountering the same issue

**Comment by PureWeen** [comment]
I'm no longer seeing this issue in 3.0 pre4. @ryanholden8   @AlexF12004Roma   can you test on pre4 see if that fixes your issue?

**Comment by AlexF12004Roma** [comment]
I cannot test on my Project because i need target UWP W10 Anniversary (14393) and XF 3 is not compatible.

**Comment by PureWeen** [comment]
I tested the sample I made in 2.5 and 3.1 and for me this now works in 3.1
