### ISSUE TITLE
MSBuild task fails to copy Fody on VSTS Agent build

### ISSUE THREAD

**Issue by johnfredrick** [xamarin/Xamarin.Forms#1793]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
I'm traying to build the app every time I make a Check In to source control.
The build breaks when Realm Task tries to copy the Fody dll to Tools directory.

### Steps to Reproduce

1. Create build definition within Visual Studio Team Services and try to build

### Expected Behavior
Build completes sucessfully
### Actual Behavior
CopyRealmWeaver:
  CopyRealmWeaver
  Creating directory "*Undefined*Tools".
1-Development\packages\Realm.Database.1.4.0\build\Realm.Database.targets(28,5): Error MSB3021: Unable to copy file "d:\a\3\s\1-Development\packages\Realm.Database.1.4.0\build\..\tools\RealmWeaver.Fody.dll" to "*Undefined*Tools\RealmWeaver.Fody.dll". Illegal characters in path.

**Comment by rmarinho** [comment]
This doesn't seem a issue related with Xamarin.Forms
