### ISSUE TITLE
[iOS] listView without data crash on ipad. 

### ISSUE THREAD

**Issue by xiangzLL** [xamarin/Xamarin.Forms#1799]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

On ipad,when set listView isrefreshing state is true and without items, at this time tap to srcoll the listView, it will crash.  but it's normal on iphone.

### Steps to Reproduce

1. set listview is refreshing is true  and without items.
2. tap to scroll the listview  (normal tap is ok)
3. app on ipad will crash.

- Version with issue:  Xamarin.Forms.2.3.4.247
- Last known good version:
- IDE:  VS2017
- Platform Target Frameworks: 
  - iOS:  11.2
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/19897396/35839293-9a8d1bd4-0b2a-11e8-8f45-a3f98c06624d.png)

**Comment by jassmith** [comment]
Do you have a repro case?

**Comment by samhouts** [comment]
@xiangzLL Have you been able to create a reproduction project? Thanks

**Comment by xiangzLL** [comment]
page code:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App4.Views.ItemsPage"
              Title="{Binding Title}"
             x:Name="BrowseItemsPage">
    <ContentPage.Content>
        <StackLayout>
            <ListView x:Name="ItemsListView"
                VerticalOptions="FillAndExpand"
                 IsRefreshing="true"
                 ItemSelected="OnItemSelected">
            </ListView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

build and run this page on ipad. then use finger to swipe listview, the program will crash

**Comment by xiangzLL** [comment]
page code:

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App4.Views.ItemsPage"
              Title="{Binding Title}"
             x:Name="BrowseItemsPage">
    <ContentPage.Content>
        <StackLayout>
            <ListView x:Name="ItemsListView"
                VerticalOptions="FillAndExpand"
                 IsRefreshing="true"
                 ItemSelected="OnItemSelected">
            </ListView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>

build and run this page on ipad. then use finger to swipe listview, the program will crash

**Comment by xiangzLL** [comment]
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App4.Views.ItemsPage"
              Title="{Binding Title}"
             x:Name="BrowseItemsPage">
    <ContentPage.Content>
        <StackLayout>
            <ListView x:Name="ItemsListView"
                VerticalOptions="FillAndExpand"
                 IsRefreshing="true"
                 ItemSelected="OnItemSelected">
            </ListView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>`

build and run this page on ipad. then use finger to swipe listview, the program will crash

**Comment by PureWeen** [comment]
[CrashingIsRefreshing.zip](https://github.com/xamarin/Xamarin.Forms/files/1857636/CrashingIsRefreshing.zip)

I tested this on an iphone 5 with ios 10 and it did not crash

It only crashed when I ran it inside the latest simulators...

**Comment by xiangzLL** [comment]
it will be crashed on ipad with ios 11.2

**Comment by Bhauraj001** [comment]
What's the solution? Please comment
