### ISSUE TITLE
[Enhancement] Add FallbackValue and TargetNullValue properties to BindingBase

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#1803]
### Rationale

The two binding properties are very handy in situations when the binding is not available or the source is null. It eliminates the need to create value converters or add unnecessary code in the view-model.

`FallbackValue`:  Gets or sets the value to use when **the binding is unable to return a value**.
`TargetNullValue`:  Gets or sets the value that is used in the target when **the value of the source is null**.

First submitted 4 years ago in 2014: https://bugzilla.xamarin.com/show_bug.cgi?id=22720

See their Windows XAML counterparts (_XAML Standard where are thou?_): 
https://msdn.microsoft.com/en-us/library/system.windows.data.bindingbase.fallbackvalue(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.windows.data.bindingbase.targetnullvalue(v=vs.110).aspx

### Implementation

The `BindingBase` class needs to get the two properties. If they are not set, everything will still work like today.

### Backward Compatibility

Everything still works.

**Comment by StephaneDelcroix** [comment]
This is a breaking change, and that's the reason why it hasn't been added yet.

We will eventually add that capability, but it'll require a backcompat flag.

**Comment by dstefanov** [comment]
Aren't the two new properties optional and therefore can be ignored if not set and preserve the current behaviour?
Essentially playing the part of the backcompat flag?

**Comment by ITCBB** [comment]
This has been open since 2014. Why is adding a non-existant property somehow a breaking change?

**Comment by StephaneDelcroix** [comment]
> Why is adding a non-existant property somehow a breaking change?

I think I've explained this already in multiple threads.

**Comment by ITCBB** [comment]
Then could you copy-paste it? Couldn't find an answer here https://bugzilla.xamarin.com/show_bug.cgi?id=22720 or here https://bugzilla.xamarin.com/show_bug.cgi?id=51164. Maybe there shouldn't be a nother bug ever few months/years?

**Comment by StephaneDelcroix** [comment]
see also #525 and #664

**Comment by StephaneDelcroix** [comment]
I figured a way to make it non-breaking
