### ISSUE TITLE
EntryCell Text Binding fails when iOS Auto-corrects text when the EntryCell loses focus (clicking outside of Entry)

### ISSUE THREAD

**Issue by spouliot** [xamarin/Xamarin.Forms#1806]
_From @garie on January 20, 2018 21:48_

This may be the same or a related issue to [Bug 42096](https://bugzilla.xamarin.com/show_bug.cgi?id=42096).

### Steps to Reproduce

1. Make sure that Auto-Correction is enabled on the iOS device/sim in Settings -> General -> Keyboard. And if using a simulator, do not use the Hardware keyboard as you will not get auto-correction suggestions when using the Hardware Keyboard, so in the iOS Simulator app, deselect "Connect Hardware Keyboard" from the Hardware->Keyboard menu. 
2. Place your cursor inside of an `EntryCell` field and type `ar`
3. Note the autocorrect suggestion is `at`
4. Click another `EntryCell` field - do *not* click the autocorrect suggestion or press space to accept the suggestion
5. Note that the field value now displays `at` instead of the misspelled `ar`
6. Note that the console log (if using the example code below) shows the following:
```
FirstName: a
FirstName: ar
```
7. Debug the app and note that the bound value of the field is the value that was typed rather than the value showing on the screen

### Expected Behavior

Values of bound EntryCells will reflect the autocorrected text

### Actual Behavior

Autocorrected text changes are not reflected in bound values of `EntryCell.Text`

### Environment

```
Visual Studio Community 2017 for Mac
Version 7.3.3 (build 5)
Installation UUID: 21da93c7-2ff8-4531-8366-737d10886905
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.2 (13772)
Build 9C40b

Xamarin.iOS
Version: 11.6.1.3 (Visual Studio Community)
Hash: f70a1348
Branch: xcode9.2
Build date: 2017-12-18 14:47:16-0500

Xamarin.Android
Version: 8.1.3.0 (Visual Studio Community)
Android SDK: /Users/christi/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.0

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

Xamarin.Mac
Version: 4.0.0.215 (Visual Studio Community)

Build Information
Release ID: 703030005
Git revision: b1c2982e201e71ef758866c9ade05f253a8c6f47
Build date: 2017-12-21 11:04:40-05
Xamarin addins: f397ddfbacfb39e60c9cc8d9e410f73faf8c2cbc
Build lane: monodevelop-lion-d15-5

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Mon Nov 13 21:56:25 PST 2017
    root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1
```

### Example Code

Partial .xaml
```
<TableView Intent="Form" x:Name="DataEntryForm">
    <TableRoot>
        <TableSection>
            <EntryCell 
                x:Name="FirstNameField"
                Placeholder="First Name" 
                Text="{Binding Contact.FirstName}"/>
            <EntryCell 
                Placeholder="Last Name" 
                Text="{Binding Contact.LastName}"/>
        </TableSection>
    </TableRoot>
</TableView>
```

Partial binding class
```
        string _firstName = string.Empty;
        public string FirstName
        {
            get { return _firstName; }
            set { 
                Logger.Debug($"FirstName: {value}");
                SetProperty(ref _firstName, value); 
            }
        }
```

_Copied from original issue: xamarin/xamarin-macios#3274_

**Comment by spouliot** [comment]
_From @timrisi on January 22, 2018 18:46_

What version of Xamarin.Forms are you using?

**Comment by spouliot** [comment]
_From @garie on January 23, 2018 13:8_

`<package id="Xamarin.Forms" version="2.4.0.18342" targetFramework="xamarinios10" />`

**Comment by spouliot** [comment]
_From @garie on January 23, 2018 13:10_

Also updated to latest available `<package id="Xamarin.Forms" version="2.5.0.122203" targetFramework="xamarinios10" />` and issue still occurs.

**Comment by MitchBomcanhao** [comment]
We've had a similar issue for quite a long time now, across multiple versions of xamarin up to latest 2.5.0-sr3
A text field where you type something and autocorrect suggests a change. you then tap a button that removes focus from the field and it'll change the text to show the autocorrected entry, but the field data actually saved the non-corrected text.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
