### ISSUE TITLE
Enhancement Request: Slider with multiple markers [Range / Current/Target]

### ISSUE THREAD

**Issue by CZEMacLeod** [xamarin/Xamarin.Forms#1809]
## Summary
Provide enhanced sliders allowing for multiple markers, either to support a range (2 markers where Min <= Lower <= Upper <= Max) or current and target (current value is not selectable/slidable). This would be of use where the item being controlled by the slider takes time to respond.

## API Changes

I would suggest a MultiSlider base class which could (optionally) take a number of markers to be added in it's constructor.
A RangeSlider class could inherit this and enforce the value limits and surface Value[i] -> Lower and Upper properties.
A CurrentTargetSlider class would similarly initialize MultiSlider with 2 markers but set one as 'disabled' and surface it as Current and the other as Target.

The MultiSlider class would have a collection of Markers each of which could have a colour, enabled and value perhaps along with other 'css' properties such as z-index.
Markers could have optional Text properties which could be rendered as tooltips on hover if supported by the platform.

The MultiSlider should surface ValueChanging and ValueChanged events, including the Marker number (which could be changed into specific events for specific markers if required by the various implementations) along with a ValueChangedCommand which would execute if set when a marker has been moved. The value for the command would be the Marker object.

## Intended Use Case
I have seen a number of people looking for a range slider e.g. [Xamarin Cross Platform Dual Slider](https://stackoverflow.com/questions/32470347/xamarin-cross-platform-dual-slider) and in my case I am writing a cross-platform IoT control app. Here the current values are shown from the IoT device, and the values may be changed by the user, but do not instantly update - e.g. in the case of a remote PTZ camera.
This would also 'replace' or introduce the existing [Range Slider](https://components.xamarin.com/view/rangeslider) component to core Xamarin.Forms (with a UWP implementation too).

## Existing Issues
I am aware that there is an existing enhancement request #1684 and #1781 some of which could be leveraged with respect to styling the (multiple) markers.

The existing Slider could be made a special case implementation of MultiSlider (same as RangeSlider) to keep the API consistent but surfacing the existing Value property and ValueChanged event.

**Comment by charlesroddie** [comment]
The current options for this are https://github.com/halkar/xamarin-range-slider and the SyncFusion range slider.
