### ISSUE TITLE
`BindableObject.ClearValue()` does not clear the context of the BindableProperty

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1813]
### Description

`IsSet()` returns `true` after `ClearValue()` is called on a `BindableProperty`.

### Steps to Reproduce

Unit test can be found at https://github.com/xamarin/Xamarin.Forms/pull/1570/commits/f27e18771cdea0c204d898b90903c2e5eb71fb5b (#1570)

### Expected Behavior

`IsSet()` returns `false` after `ClearValue()` is called on a `BindableProperty`.

### Actual Behavior

`IsSet()` returns `true` after `ClearValue()` is called on a `BindableProperty`.

### Reproduction Link

Unit test can be found at https://github.com/xamarin/Xamarin.Forms/pull/1570/commits/f27e18771cdea0c204d898b90903c2e5eb71fb5b

**Comment by StephaneDelcroix** [comment]
I'll investigate and see if there's a good reason for the current behavior. if not, I'll fix
