### ISSUE TITLE
Move `CornerRadius` to `BorderElement`

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#1814]
### Description

`CornerRadius` will be used for CSS. This property is now (as of #1570) shared by `Button` and `Frame`, so it can be moved to the common `BorderElement` class.

**Comment by StephaneDelcroix** [comment]
as one of the `CornerRadius` is `float` and the other is `int`, this will be a breaking change

**Comment by weitzhandler** [comment]
Related #1754.

**Comment by jfversluis** [comment]
Won't be happening for Forms anymore!
