### ISSUE TITLE
Application breaks while using picker.

### ISSUE THREAD

**Issue by shivagurunathan** [xamarin/Xamarin.Forms#1830]
Hi ,  

While using picker in the project, we get a breaking issue with the following callstack.  

Note: We use Xamarin version 2.4.0.280  

**01-19 09:14:06.127 I/MonoDroid( 4730): System.NullReferenceException: Object reference not set to an instance of an object. 
01-19 09:14:06.127 I/MonoDroid( 4730):   at Xamarin.Forms.Platform.Android.PickerRenderer.<OnClick>b__11_2 (System.Object sender, System.EventArgs args) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\PickerRenderer.cs:145  
01-19 09:14:06.127 I/MonoDroid( 4730):   at Android.Content.IDialogInterfaceOnDismissListenerImplementor.OnDismiss (Android.Content.IDialogInterface dialog) [0x0000d] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Content.IDialogInterface.cs:369  
01-19 09:14:06.127 I/MonoDroid( 4730):   at Android.Content.IDialogInterfaceOnDismissListenerInvoker.n_OnDismiss_Landroid_content_DialogInterface_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_dialog) [0x00011] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Content.IDialogInterface.cs:334  
01-19 09:14:06.127 I/MonoDroid( 4730):   at (wrapper dynamic-method) System.Object:d5899a9c-5e40-4345-93bc-a7ffc7e4fda1 (intptr,intptr,intptr)** 

I have attached a sample that replicates the issue.  Procedure to replicate the issue:  
1. In DataGrid, tap a column with GridPicker column(3). 
2. When picker appear, tap outside anywhere in the datagrid to dismiss or close the picker. 
3. With that, please repeat the steps in #2 and do it as fast as you can. 
4. In any seconds, the app will crash.

Regards, 
Shivagurunathan. K

[SfGrid_Sample1421475852 (4).zip](https://github.com/xamarin/Xamarin.Forms/files/1704064/SfGrid_Sample1421475852.4.zip)

**Comment by jassmith** [comment]
Can you confirm this happens with the AppCompat backend as well? The non AppCompat is considered on life-support.

**Comment by shivagurunathan** [comment]
This bug still does exists on non AppCompat forms application.

**Comment by jassmith** [comment]
Im sorry are you saying the bug exists on AppCompat as well? It should have a different stack trace on AppCompat.

**Comment by josephca88** [comment]
@jassmith,,

I hope you could help us. But the issue persist on Non-AppCompat FormsApplication. Our project doesn't use the AppCompat at the first place. As we know, the bug on the picker was only been fixed under the AppCompat Forms of Xamarin but not on the Non-AppCompat.

Following the steps from @shivagurunathan, you can easily reproduce the issue from the sample application provided by him.

Thanks

**Comment by jassmith** [comment]
```csharp
[assembly: ExportRenderer (typeof (Picker), typeof (Xamarin.Forms.Platform.AppCompat.PickerRenderer))]
```

Should get you going right away.  The non-AppCompat backend is hitting end of life really and while I am confirming this bug it won't get prioritized very high considering our already stretched resources.

**Comment by josephca88** [comment]
You have provided a code snippet. However, I have no idea where should the code to be put on?

Can you please let us know. Thanks

**Comment by jassmith** [comment]
Place it in your Android project heads AssemblyInfo.cs

Realistically you can put it at the top of any old file, it doesn't matter. It's an assembly level attribute.

**Comment by jassmith** [comment]
Eh I just realized that will probably crash, worth a try however

**Comment by josephca88** [comment]
What do you mean that it will crash? In what particular instance?

Thanks.

**Comment by jassmith** [comment]
Trying to use the new AppCompat renderer with the old backend. More than likely it will complain its not in an AppCompat activity. This is not 100% for sure, but it is the most likely outcome.

**Comment by josephca88** [comment]
After the test with the provided snippet applied, still experiencing the crash issue.

Here is the crash dump.

> 02-23 09:59:56.594 I/MonoDroid( 5574): System.NullReferenceException: Object reference not set to an instance of an object.
02-23 09:59:56.594 I/MonoDroid( 5574):   at Xamarin.Forms.Platform.Android.PickerRenderer.<OnClick>b__10_2 (System.Object sender, System.EventArgs args) [0x00000] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\Renderers\PickerRenderer.cs:139 
02-23 09:59:56.594 I/MonoDroid( 5574):   at Android.Content.IDialogInterfaceOnDismissListenerImplementor.OnDismiss (Android.Content.IDialogInterface dialog) [0x0000d] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Content.IDialogInterface.cs:369 
02-23 09:59:56.594 I/MonoDroid( 5574):   at Android.Content.IDialogInterfaceOnDismissListenerInvoker.n_OnDismiss_Landroid_content_DialogInterface_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_dialog) [0x00011] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Content.IDialogInterface.cs:334 
02-23 09:59:56.594 I/MonoDroid( 5574):   at (wrapper dynamic-method) System.Object:8d749da0-dfed-44c9-9930-a1c56234febc (intptr,intptr,intptr)

**Comment by shivagurunathan** [comment]
Hi @jassmith ,
Any update on this issue. It would be helpful to us, if you could provide any further solution towards it.

**Comment by jassmith** [comment]
@shivagurunathan can you do me a favor and build a repro that doesn't use any third party deps. This is now coming up in line for a fix and most people cant run your repro due to the 3rd party deps.

**Comment by shivagurunathan** [comment]
Hi @josephca88 ,
Can you please provide the repro.
