### ISSUE TITLE
Using AOT + Bundle into native assemblies duplicates nuget packages into APK?

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#1835]
I tried using AOT and LLVM to reduce start up time in my xamarin forms app on android. It really made trick. I had around 10-12secs and now google firebase reports between 2-7secs based on the device as shown below.

![image](https://user-images.githubusercontent.com/10422347/35947583-d6bbf29e-0c68-11e8-8875-6c4b55297b69.png)

What my settings are as followings; - Link SDK and User assemblies - Bundle into native assemblies - Proguard - no-write-symbols,nodebug - Separate Apk for each Abis

Project file for related group looks like as below;

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <DebugType>
    </DebugType>
    <AndroidLinkMode>Full</AndroidLinkMode>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <AndroidCreatePackagePerAbi>true</AndroidCreatePackagePerAbi>
    <JavaMaximumHeapSize>1G</JavaMaximumHeapSize>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
    <DebugSymbols>false</DebugSymbols>
    <BundleAssemblies>true</BundleAssemblies>
    <AndroidEnableMultiDex>True</AndroidEnableMultiDex>
    <EnableProguard>true</EnableProguard>
    <Debugger>Xamarin</Debugger>
    <AndroidSupportedAbis>armeabi-v7a;x86;x86_64</AndroidSupportedAbis>
    <AndroidLinkSkip>Akavache;Akavache.Sqlite3;SQLiteNetExtensions;SQLiteNetExtensionsAsync;SQLite.Net;SQLite.Net.Async;Syncfusion.DataSource.Portable;Syncfusion.Data.Portable;Syncfusion.Pdf.Portable;Syncfusion.SfDataGrid.XForms;Syncfusion.SfNumericUpDown.XForms;Syncfusion.SfDataGrid.XForms.Android;Syncfusion.SfNavigationDrawer.Android;Syncfusion.SfNavigationDrawer.XForms;Syncfusion.SfNavigationDrawer.XForms.Android;Syncfusion.SfSchedule.XForms;Syncfusion.SfSchedule.XForms.Android;Syncfusion.SfSchedule.Android;Syncfusion.Compression.Portable;Xamarin.GooglePlayServices.AppIndexing;Xamarin.Insights;Splat;Xamarin.GooglePlayServices.Basement;Xamarin.FireBase.AppIndexing;Xamarin.FireBase.Common;Xamarin.GooglePlayServices.Gcm;</AndroidLinkSkip>
    <AndroidEnableMultipleDex>true</AndroidEnableMultipleDex>
    <AndroidExplicitCrunch>true</AndroidExplicitCrunch>
  </PropertyGroup>
```
 
**PROBLEM;** App size increased as expected but it is not the Apk size problem for me, rather installed size on device. here are the values.

APK is 20mb using single apk, settings above but no AOT no LLVM
APK separate apks per abi are 16mb, settings above but no AOT no LLVM
single apk 49 mb, , settings above but with AOT + LLVM
separate Apks per abi are 26 mb,settings above with AOT + LLVM a
Until here, everything seems perfect. I can accept 6mb-10mb increase even it is still so high amount but the difference is installed size of the app on the device. without AOT is around 30mb installs. with AOT+LLVM 100mb+

When I extract the apk, i can see what is in the apk. Capture below is from lib folder (biggest folder) without using AOT and Bundle into Native assemblies

![image](https://user-images.githubusercontent.com/10422347/35947624-160e8574-0c69-11e8-9ebf-9f54908380ec.png)

Capture for with AOT+LLVVM.. see the yellow highlighteds are indeed what we need to install the apk according to the previous apk. I dont know if I need any extra library to run AOT but why those blue underlined 3rd party libraries are there. they are supposed to be bundled into native assemblies as in the first screenshot. Do I understand it wrong or Xamarin has bug on using AOT with Bundles into Native assemblies?

![image](https://user-images.githubusercontent.com/10422347/35947638-244149f6-0c69-11e8-83d8-5fff802e80f0.png)

**Comment by dhaligas** [comment]
@EmilAlipiev check this out https://xamarinhelp.com/reducing-app-file-size-xamarin-forms/

this line will reduce size of your app
```<AndroidAotAdditionalArguments>no-write-symbols,nodebug</AndroidAotAdditionalArguments>
```

**Comment by EmilAlipiev** [comment]
@dhaligas  please read the whole question. I am not asking how to reduce the size (I am already using it). I am reporting duplication.

**Comment by dhaligas** [comment]
yes the title was misleading

**Comment by dhaligas** [comment]
also this would be a Xamarin.Android / Mono issue.  @jonpryor might have some insight into this.

**Comment by jassmith** [comment]
Assigning to android team and moving to invalid on Forms team triage board

**Comment by jonpryor** [comment]
> but why those blue underlined 3rd party libraries are there.

Those libraries, such as `libaot-System.Core.dll.so`, are the AOT output for the assemblies used by your app. They are there because you enabled AOT for your project.

> they are supposed to be bundled into native assemblies as in the first screenshot. Do I understand it wrong or Xamarin has bug on using AOT with Bundles into Native assemblies?

["Bundle assemblies into native code"](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/release-prep/#Bundle_Assemblies_into_Native_Code) does *not* mean "AOT". It means "copy the assembly contents into `libmonodroid_bundle_app.so`." The assembly contents are still IL; the JIT is still used to process them.

> [the `.apk` size] with AOT+LLVM [enabled is] 100mb+

From what you describe, this is normal and expected. AOT results in *huge* size increases. This affords improved performance, as AOT'd members don't need to pull in the JIT, but at the cost of size increases.
