### ISSUE TITLE
Layout is not done properly in MasterDetail page and Carousel page.

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#1839]
### Description
I have came with Layout issue in two pages.

**MasterDetailPage:**
I have a **MasterDetail page** which contains 2 buttons in the master page, load the content page when click Page1 button, which contains label loaded inside the **ScrollView**, I have try to **Re-Layout** the label from one position to another position when click the **Layout button**, but layout is not working.

**CarouselView:**
I have loaded the Label inside the **ScrollView** which is loaded in the **CarouselView** when i try to **Re-Layout** the label from one position to another position but the layout is not working.

### Steps to Reproduce
**MasterDetail Issue replication:**
1. In the Master page click the 'Page 2' button, which navigates to a Navigation page, then click the 'Layout' button. See that the label is re layout from one position to another position in details page.
2. Now switch to Page1 which navigates to Content page and click the Layout button. See that the label is not re layout.

**Carousel issue replication:** 
1.Click Carousel page button, then click the Layout button. See that the label is not re layout.

### Expected Behavior
Label has to re layout from one position to another position.
### Actual Behavior
Re layout is no working.
### Basic Information

- Platform Target Frameworks: Android
- Android: 7.1
- Nuget Packages:  XAMARIN.Forms v2.5.0.121934

### Reproduction Link
[Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/1706820/Bug.zip)

**Comment by DineshBabuYadav** [comment]
Any update on this ?

**Comment by samhouts** [comment]
@DineshBabuYadav It does seem unexpected that the behavior is different. 

May I ask what your goal is for triggering a layout in this way?

**Comment by samhouts** [comment]
Duplicate of #1421, #1764. In future, you are welcome to reopen the old issue with new information instead of creating new ones. We do watch them when the status changes. :)

**Comment by DineshBabuYadav** [comment]
@samhouts ,

We have already provided the replication procedure with very simple sample to replicate the mentioned issue and provided much needed information about the issue in other bug reports #1421, #1764.

However, we will describe the scenario again for a keen clearance to you and help us to sort out from this issue,

In MasterDetailPage, we have some kind of options in master page say page1button and page2button.
While clicking on those buttons, we have loaded a custom view(similar to XF ListView) in the DetailPage (which is actually nothing but a content page) which can referred in the sample.

And, while switching between from page1button to page2button (vice-versa), the items in the custom view gets loaded **initially** but when we re-use the same element while scrolling to achieve the **UI Virtualization** concept. 

The each item gets layout in PCL view as expected but in respective native view in android project, either the OnMeasure or OnLayout overrides is not triggered while re-using which shows the items are not rendered in native view and causes the item's visibility to invisible.

**Goal:**
Creating a custom view similar to Xamarin Forms ListView with UI Virtualization concept.
 
Please let me know if you require further assistance.

Regards,
Dinesh B

**Comment by Selvamz** [comment]
@samhouts, We are from Syncfusion and this issue occurs on Syncfusion ListView component. In our SfListView, we have re-layout (recycle) the items while scrolling.

**Comment by samhouts** [comment]
Got it. Just wanted to determine if there's another way to achieve the desired behavior. For this use case, I think we'll need to investigate further. Thanks!

**Comment by samhouts** [comment]
possibly related to #1332

**Comment by JKennedy24** [comment]
Would be great to get this bugs priority increased.

This is holding back some of the new features in some of the Syncfusion controls, which is disappointing for both Syncfusion and their clients (me)

**Comment by 54321G** [comment]
Any update on this ?

**Comment by AndreiMisiukevich** [comment]
Colleagues, you can try to use my plugin for implementing CarouselView
Check it here https://github.com/AndreiMisiukevich/CardView

**Comment by 54321G** [comment]
Any update on this ?

**Comment by 54321G** [comment]
Any update on this ?

**Comment by jayaleshwari** [comment]
Any update on this ?

**Comment by DineshBabuYadav** [comment]
@samhouts , we are looking for a solution to this report.

**Comment by samhouts** [comment]
@DineshBabuYadav Sorry for the delay! We're working on getting this prioritized. Thank you!

**Comment by RawoofSharief** [comment]
@samhouts , Since, this bug has been dragging from several months. Can you provide any workaround for this?. Please consider this as high priority.

**Comment by JKennedy24** [comment]
Can we prioritise this bug in some way? This bug makes Syncfusion listview in a CarouselView unfortunately unusable on Android. Currently a blocker for our application

**Comment by DineshBabuYadav** [comment]
@samhouts , Can you please update on this? If possible please provide a work around. Our clients are requesting for the work around. So, please make prioritize this issue and update us asap.

**Comment by GnanaPriyaNamasivayam** [comment]
@samhouts , Can you please provide any workaround for this issue now until you fix this issue.  Is there any update on this. Please update us the details asap.

**Comment by DineshBabuYadav** [comment]
@samhouts , Please update.

**Comment by DineshBabuYadav** [comment]
@samhouts , can you please provide any further updates.

**Comment by samhouts** [comment]
This is on the backlog. Thanks!

**Comment by DineshBabuYadav** [comment]
@samhouts , thanks. Can you share us the timeline? So, that we can provide a valid timeline to our customers.

**Comment by samhouts** [comment]
Given our current backlog and priorities, we don't expect to start working on this until early August. Thanks for your patience!

**Comment by syncsiva** [comment]
@samhouts  Still we are waiting for the fix.

**Comment by mageshyadavm** [comment]
@samhouts : Any update on this. Did you consider to start working on this fix as informed to start early august ?

**Comment by samhouts** [comment]
@mageshyadavm No update yet, but we're planning to look at this time within the next week. Thanks!

**Comment by kingces95** [comment]
Happy day! Seems to work on latest nuget. Or am I holding it wrong?

![4E066B4B-29FA-4581-B64E-317E97DA37F6](https://user-images.githubusercontent.com/4120386/63629103-d9765080-c5ab-11e9-8ba3-9944d876e7c8.GIF)
