### ISSUE TITLE
Embedded images are not renamed on VS2017 as on the local drive

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#1840]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

I came across with a strange issue. I am not sure if that is bug fo  xamarin.forms,  .net standard 2.0 or VS 2017. please feel free to move to correct repository. 
Basically changing renaming file on the disk is not refreshed in VS 2017 and there is no refresh button or right click action as well. 

I was wondering why my embedded image is not displayed and figured out that I renamed it on the disk and since VS 2017 doesnt refresh, Images arent loaded.

### Steps to Reproduce

1.  Create a .net standard 2.0 project 
2.  Add an embedded image (tested with png and svg) file in Shared project with uppercase name, rename it using windows explorer, just make it all lower case (not over VS2017). 
3. You can see the file is still using upper case in the VS 2017 Solution explorer

### Expected Behavior

VS 2017 should take the changes
### Actual Behavior

Keeps the casing
### Basic Information

- Version with issue: VS 2017 pro 15.5.6

### Screenshots
File on the disk

![image](https://user-images.githubusercontent.com/10422347/35973961-9ebcb97c-0cd7-11e8-9070-d5e5493d87c9.png)

Same file in VS 2017

 
![image](https://user-images.githubusercontent.com/10422347/35973942-8e639a00-0cd7-11e8-8516-db692ff09df4.png)

 
PS, if I rename the file to be test2.png, it becomes like as below. it recognizes as a new file

![image](https://user-images.githubusercontent.com/10422347/35974207-65091f12-0cd8-11e8-9f47-8c4f0cc76c1e.png)

**Comment by jassmith** [comment]
This isn't a Xamarin.Forms issue and unfortuantely there is nothing we can do to fix it :/
