### ISSUE TITLE
[Enhancement] Allow custom headers to be used when ImageSource is a URI

### ISSUE THREAD

**Issue by alanag13** [xamarin/Xamarin.Forms#1843]
# Rationale

It is common for network resources to require authentication, cookies, api keys, etc to download content, including images. Currently it is not possible to display an `Image` from a network location using XAML unless it is available completely anonymously with no non-standard headers set.

Some forum posts:
https://forums.xamarin.com/discussion/25890/image-source-http-credentials
https://forums.xamarin.com/discussion/40531/uriimagesource-and-authentication-headers
https://forums.xamarin.com/discussion/86483/how-to-get-image-from-httpclient

## Summary
Add a BindableProperty to `Image` of type `HttpRequestHeaders`, and add those headers to `HttpClient` in `PlatformsServices.GetStreamAsync`

## API Changes
`HttpRequestHeaders Image.RequestHeaders` //Bindable Property. Only used if Image source is from a URI.

(internal overload)
 `PlatformsServices.GetStreamAsync(Uri uri, HttpRequestHeaders customHeaders, CancellationToken)`

## Intended Use Case
Display an Image from a source requiring Basic auth info, API keys, etc.
XAML example:
```
<Image  Source="https://apikeyrequired.com/image.jpg" RequestHeaders={Binding MyCustomHeaders}/>
```
## Difficulty: Easy
I would think, but let me know if I'm missing something

**Comment by alanag13** [comment]
Another thought on this, would it make sense to allow devs to define their own full `HttpClient` and not just the headers?

**Comment by adamped** [comment]
I like the idea of exposing the HttpClient but not sure of the implementation.

**Comment by alanag13** [comment]
@adamped yeah, the example above definitely wouldnt apply for `HttpClient`. I might file a separate proposal for that. If it gets some attention it seems like it would be a better solution.

**Comment by Milner99** [comment]
Fantastic this has moved to under consideration - any update?

**Comment by RyanGaudion** [comment]
Are there any updates to this issue?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
