### ISSUE TITLE
LineBreakMode does nothing when label is in grid

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1847]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Migrating this 1 year old bug here - https://bugzilla.xamarin.com/show_bug.cgi?id=52631

In a simple grid with two labels, the first label has a long string of text. If you set LineBreakMode to tail truncate on this label, it doesn't truncate. Instead the first label overlaps the second label.

### Steps to Reproduce

1. Run app
2. Note that the labels are not truncated

### Expected Behavior
Both labels are truncated at the end

### Actual Behavior
Labels are displayed on top of each other

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 7, and iPhone 5s on simulator running iOS 9.3

### Screenshots
https://imgur.com/k4cz2vv

### Reproduction Link
https://www.dropbox.com/s/rvpsmjw2qzb0up0/LineModeSample.zip?dl=0

**Comment by jassmith** [comment]
By my testing this is working as expected. The auto-columns make zero effort to fit into the screen size as they are not specced to. The super wide auto columns will just push off the edge of the screen. Obviously when you span the first label into the second column they will overlap labels. And since the colums can and do expand beyond screen size you will not see truncation.

While I can understand a desired behavioral change, and change to this behavior would be considered backwards compatible breaking and would certainly break a large number of existing applications.

**Comment by Paul-Brenner-Tangoe** [comment]
@jassmith Could you clarify? I am a little confused. you say "The auto-columns make zero effort to fit into the screen size as they are not specced to" but the [docs](https://developer.xamarin.com/guides/xamarin-forms/user-interface/layouts/grid/#Rows_and_Columns) say that auto

> automatically sizes to fit content in the row or column

So with two labels in a grid with two columns, without column span set, I would interpret that to mean "fit the labels so that they both fit in the columns" i.e, truncate the labels. But it instead only shows the first label, is this a bug, or is it working by design and the docs should be updated to explain what auto actually does?

Also, the docs say for star

> Specifying one row/column with * will cause it to fill the available space.

But your description of auto sounds like the description of star given in the docs.

Nevertheless, could the [docs](https://developer.xamarin.com/api/property/Xamarin.Forms.Label.LineBreakMode/) for linebreakmode be updated to say that a long label will not truncate in a grid with a column set to auto? Because I don't think people would expect that not to work.

**Comment by jassmith** [comment]
Auto basically sizes the column to be the desired size of the element, if that happens to be wider than the grid itself, thats what it does. In other words Auto makes no consideration for "available space" at all, star does.
