### ISSUE TITLE
System.ComponentModel.DataAnnotations throws exception on IOS Actual Device

### ISSUE THREAD

**Issue by kishorupare** [xamarin/Xamarin.Forms#1851]
I have use System.ComponentModel.DataAnnotations in portable class project. This work great in Android Actual Device but failed on IOS actual device. In IOS emulator it work great but not on Actual iPhone. It thows deployment error as 

Could not AOT the assembly '/Users/rnr_mac/Library/Caches/Xamarin/mtbs/builds/RujulERP_Mobile.iOS/43d2ca3e2c725a70d6f4c6086aa946e8/obj/iPhone/Debug/mtouch-cache/64/Build/System.ComponentModel.DataAnnotations.dll'	RujulERP_Mobile.iOS

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-macios#3449
