### ISSUE TITLE
[Forms][Android][custom rendrerer]android.widget.LinearLayout cannot be cast to android.widget.ImageView

### ISSUE THREAD

**Issue by Shaboo** [xamarin/Xamarin.Forms#1860]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
in Xamarin Forms, I have a content page, inside it, I have an image with gesture recognise like following,

```
<Image Grid.Row="0" Grid.Column="1" Source="Share.png">
  <Image.GestureRecognizers>
    <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped_2"></TapGestureRecognizer>
  </Image.GestureRecognizers>
</Image>
```

In android project, I have a custom renderer to make the Taps on tabbed page in bottom, so When I call
the following function:
```
if (Platform.GetRenderer (view) == null) {
  Platform.SetRenderer (view, Platform.CreateRenderer (view));
}
```
the following exception is thrown
`Java.Lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ImageView`

when I remove the Gesture Recogniser, the exception is not thrown any more,
note that this issue happened only after I updated Xamarin.Forms from version 2.3.3.193 to version
2.5.0.122203

### Steps to Reproduce

1. following the description above
2. 
3. 

### Expected Behavior
no exception thrown
### Actual Behavior
the following exception is thrown:
`Java.Lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.ImageView`
### Basic Information

- Version with issue:
- Last known good version:
- IDE: vs2017 community 15.5.6
- Platform Target Frameworks: 

  - Android: 7.1 
  - UWP:   
- Android Support Library Version: 27.0.3
- Nuget Packages:
- Affected Devices:
all android devices

**Comment by PureWeen** [comment]
@Shaboo   can you attach a minimal reproduction please?

**Comment by Shaboo** [comment]
solved after updated the following packages to latest version: 26.1.0.1
Xamarin.Android.Support.Design
Xamarin.Android.Support.v4
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
