### ISSUE TITLE
[Enhancement] Give us a real MinimumWidthRequest / MinimumHeightRequest

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1862]
### Rationale
MinimumWidthRequest & height does not do what it sounds like. There was a PR to fix it, but it was closed as it would be a breaking change. I understand the reason to not want to do a breaking change, but the issue shouldn't just be ignored. 

see:
https://github.com/xamarin/Xamarin.Forms/pull/386
https://forums.xamarin.com/discussion/84885/rejected-obsolete-minimum-width-height-request

> Most people interpret it to mean "The minimum size the control can ever be and no smaller ever" where the actual intent of the property is "the smallest size the control can be squished to when the desired size cannot be met"

Having a property that sets the minimum size the control can be would be very useful.

### Summary
Add a new property that lets us set a minimum width / height of controls.

### API Changes
Add a new property, no idea on the name, maybe
```
ActualMinimumWidthRequest 
ActualMinimumHeightRequest 
```

We also really should update the property description of MinimumWidthRequest  since it does not do what it sounds like it does.

### Intended Use Case
It would be nice to be able to give controls a minimum width / height.

**Comment by jassmith** [comment]
Thats what WidthRequest/HeightRequest do if you set the Minimum's equal to them.

**Comment by PaulVrugt** [comment]
@jassmith 

That doesn't appear to be the case. I have stacklayout containing a label with a long text. If I set the heightrequest to 40, the text is truncated if it is longer.

I now fixed it by not setting a heightrequest at all. I added i boxview to my stacklayout with a height of 40. Now the label pushes the stacklayout larger when the text is long enough.

I've seen all kinds of bugs and pull request about this minimumheightrequest/minimumwidthrequest. I really think it should be worth the same taking a look at this....

**Comment by HelenMamalaki** [comment]
Why is this enhancement closed? I was just about to request the same since all bugs/ forum discussions so far seem to get stuck on the naming of the existing MinimumHeightRequest property...either way a new property is needed which we can use the set the min/max height of a VisualElement..why is this being ignored?
https://forums.xamarin.com/discussion/84885/obsolete-minimum-width-height-request
https://forums.xamarin.com/discussion/66049/does-minimumheightrequest-work-at-all
https://bugzilla.xamarin.com/show_bug.cgi?id=44738

**Comment by MappingSteve** [comment]
@jassmith

> That's what WidthRequest/HeightRequest do if you set the Minimum's equal to them.

I think you are not seeing the need being described.  

What you say is only accurate if `HeightRequest` is large enough to hold the desired value and/or the view is capable of expanding beyond `HeightRequest` if needed.

Consider a stack of labels, with bound text that may require an arbitrary number of lines.  
Consider a desire to have each label to be at least 60 DPs tall, but to grow taller if necessary.  

In the following XAML, what **Style** would work BOTH for the short text (forcing it to be 60 DPs tall), AND for the very long text (allowing it to be as tall as it wanted)?  In this scenario, there is an abundance of space, so MinimumHeightRequest has no effect.  
As shown, with `HeightRequest` commented out, the Short text is NOT the desired (minimum) height.  
If uncomment that line, the Short text is the desired height, but the multi-line text gets truncated.

`    <ContentPage.Resources>
        <Style TargetType="Label">
            <Setter Property="LineBreakMode" Value="WordWrap" />
            
            
        </Style>
    </ContentPage.Resources>
    <ContentPage.Content>
        <Grid VerticalOptions="Fill" ColumnSpacing="0" BackgroundColor="Yellow">
            <Grid.ColumnDefinitions>
                
                <ColumnDefinition Width="80" />
            </Grid.ColumnDefinitions>
            <StackLayout BackgroundColor="Blue">
                <Label Text="Short" />
                <Label Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor." BackgroundColor="Green" />
                <Label Text="Short 2" />
            </StackLayout>
        </Grid>
    </ContentPage.Content>
`

AFAIK, this often-made request is still unmet, and this issue should be re-opened.

**Comment by tomeverin** [comment]
@MappingSteve  @jassmith  I agree that this issue should be reopened, this functionality would be very useful and is not met using the MinimumWidth/Height properties

**Comment by marceloarchiza** [comment]
The fact that they keep closing this thread and after 4 years no one from Microsoft cared about this 💀

**Comment by radoczsandor** [comment]
Unacceptable that the issue is still exists and nobody cares about it. One of the most important property and they just ignore it.
