### ISSUE TITLE
[WPF] Xamarin.Forms WPF load local html throw ArgumentException with message "Relative URIs are not allowed"

### ISSUE THREAD

**Issue by 5yunus2efendi** [xamarin/Xamarin.Forms#1864]
### Description

Load local html with the following code will throw ``ArgumentException`` with message "Relative URIs are not allowed":
```csharp
var source = new HtmlWebViewSource()
{
    BaseUrl = "https://www.google.com/",
     Html = @"<html><body> <h1>Xamarin.Forms</h1> <p>Welcome to WebView.</p> </body>
   </html>"
};
WebView.Source = source;
```

### Steps to Reproduce

1. Create Xamarin.Forms project
2. Follow instruction [how to create Xamarin.Forms WPF](https://javiersuarezruiz.wordpress.com/2018/01/15/xamarin-forms-aplicaciones-wpf/)
3.  Add WebView control and use above code

### Expected Behavior

Show web page

### Actual Behavior

throw ``ArgumentException`` with message "Relative URIs are not allowed"

### Basic Information

- Version with issue: [3.0.0-ci0011](https://ci.appveyor.com/nuget/xamarin-forms-wpf-ci)
- IDE: VIsual Studio 2017 15.5.3
- Platform Target Frameworks: WPF

**Comment by PureWeen** [comment]
[issues1864.zip](https://github.com/xamarin/Xamarin.Forms/files/1718699/issues1864.zip)

**Comment by 5yunus2efendi** [comment]
I am still confuse, what xamarin.forms version should I use to test prelease, is it 3.0.x or 2.6.x? I see that xf 3.0.x has `Xamarin.Forms.Platform.WPF` merged to it and 2.6.x hasn't

**Comment by 5yunus2efendi** [comment]
For now my solution was to create my own WebView renderer and copy the all [WebViewRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs), make a change from https://github.com/xamarin/Xamarin.Forms/blob/b96f65bdd9e7e931971338b122a8940e2a35ccc7/Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs#L74-L77 to
```csharp
Control.NavigateToString(html);
```

**Comment by mohachouch** [comment]
Hello,

Version 3.0.0-ci0011 is a version that was created before adding the project to Xamarin Forms main project.

It is no longer necessary to use AppVeyor but use the nigltly build of Xamarin Forms. https://blog.xamarin.com/try-the-latest-in-xamarin-forms-with-nightly-builds/

Regarding the bug, I'm going to watch this.

Thanks for your report

**Comment by 5yunus2efendi** [comment]
Ok, looking forward for this!
