### ISSUE TITLE
[Android]  Fix Vector Drawables to work with pre api 21

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#1872]
### Description
Currently if you use a Vector Drawable with a pre lollipop device it causes the application to crash

### Steps to Reproduce

Create a Vector Drawable and use it with a Xamarin Forms Image
Attached project works

### Expected Behavior
On pre lollipop it should load the image. If it proves too problematic to get these working on pre lollipop then the app should at least not crash.

### Actual Behavior
it crashes
Vector Drawables were disabled on pre api 21 until  version 23.4.0 of the support libraries

### Basic Information

- Android Support Library Version: Requires version 23.4.0 or higher to work

https://stackoverflow.com/questions/36867298/using-android-vector-drawables-on-pre-lollipop-crash

### Reproduction Link

[VectorTestProject.zip](https://github.com/xamarin/Xamarin.Forms/files/1718386/VectorTestProject.zip)

**Comment by sgong-pdftron** [comment]
Any plan on getting this working? Thanks!
