### ISSUE TITLE
OnAppearing is called for all the pages in the NavigationStack when resuming the Android app

### ISSUE THREAD

**Issue by olegpidsadnyi** [xamarin/Xamarin.Forms#1874]
### Description
When resuming the Android app (turning the screen on) OnAppearing is called for all the pages in the current NavigationStack, not only the last one.
When navigating back OnAppearing is not called for the page, because it was already called previously by mistake.

### Steps to Reproduce

0. PushAsyncModal(new NavigationPage())
1. Navigation.PushAsync(page1),  Navigation.PushAsync(page2)
2. Turn the screen OFF
3. Turn the screen ON
4. OnAppearing in called for page1 and page2. Expected only page2
5. Press back arrow. OnAppearing is not called for page1, expected to be called

### Expected Behavior

It is expected that OnAppearing/OnDisappearing would be called only for the current page just as a regular navigation.

### Actual Behavior
Exactly how it is described in the closed issue on bugzilla, even though there were later comments that issue still remains:
https://bugzilla.xamarin.com/show_bug.cgi?id=41322

### Basic Information

- Version with issue: 2.4.0.282
- Last known good version:
- IDE: Visual Studio Community Mac
- Platform Target Frameworks: 
  - Android: 6.1, 7.1

**Comment by PureWeen** [comment]
[issue1874-PushImmediately.zip](https://github.com/xamarin/Xamarin.Forms/files/1720749/issue1874-PushImmediately.zip)

@olegpidsadnyi   can you attach a reproduction? I did notice some OnAppearing oddities on Android if you push pages immediately after setting the MainPage but none of those oddities included an OnAppearing call for multiple pages when I turned the app off and then on again

The reproduction I have attached here pushes the pages in such a way that when clicking the back button onappearing doesn't fire.

This sample works fine on UWP.

I'm just curious to see something with the results you are talking about

**Comment by olegpidsadnyi** [comment]
OK, @PureWeen. Here is the file:
[Reproduce.zip](https://github.com/xamarin/Xamarin.Forms/files/1721551/Reproduce.zip)

One thing I missed is that the NavigationStack is pushed modally. Basically I have an app which is Master-Detail page and I don't want to remove it out of the App.MainPage anymore.
Then I have a small wizard which I push modally and can cancel or complete that flow and finally dismiss the modal page and come back to my lovely Master-Detail.

Then If I turn the screen off on the second page of my modal wizard and turn it on again I'll get this in the application output:

!!!!!!!!!!!!!!!!!!!!!ReproducePage.OnAppearing!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!SecondPage.OnAppearing!!!!!!!!!!!!!!!!!!

Where SecondPage is the top one and only it should get OnAppearing called, but both are called instead.

I hope I'm not misusing all kinds of guidelines.

**Comment by kingces95** [comment]
Reproduction behaves as described.

**Comment by hartez** [comment]
The described behavior is no longer occurring in 3.5.0; run the test for Issue [52318](https://bugzilla.xamarin.com/show_bug.cgi?id=52318) to verify. However, another problem has manifested - see #4986.
