### ISSUE TITLE
 [Android] Forms.Maps Memory Leak

### ISSUE THREAD

**Issue by dreeanic** [xamarin/Xamarin.Forms#1877]
On Android, Map instances don't seem to be completely destroyed. Easiest way to reproduce is to push a Page containing a Map and then move back and forth a number of times. 

The behaviour is the same as the one described here: https://bugzilla.xamarin.com/show_bug.cgi?id=39489, but the out of memory crash happens after more iterations. For example, testing on a LGE Nexus 5 API 21 leads to the following results:
- using Xamarin.Forms.Maps version "2.3.3.193" the sample app crashes on the 16th push of the Page containing the Map
- using Xamarin.Forms.Maps version "2.5.0.122203" the sample app crashes after approx. 200 iterations. Once every 80 iterations or so, GC collects the pages and map instances (the finalizers are triggered), but the memory keeps increasing, as seen on the Profiler's Memory Allocations graph.

### Steps to Reproduce

1. Run the sample app
2. Press the "Move to Map Loop" button and wait. The page containing the map is pushed and popped programatically, on a timer. 
3. Observe the app crashing with an out of memory message (it takes 200 iterations on my phone, with this basic map)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: compiling against Android SDK  7.1 
- Xamarin.Forms "2.5.0.122203"
- Xamarin.Forms.Maps "2.5.0.122203"
- Xamarin.GooglePlayServices.Maps "42.1021.1"

### Screenshots

![mapsprofile](https://user-images.githubusercontent.com/25563600/36173033-7779fb26-1110-11e8-9a1b-4ad197804e29.png)

### Reproduction
[test-map-leaks.zip](https://github.com/xamarin/Xamarin.Forms/files/1721638/test-map-leaks.zip)

**Comment by samhouts** [comment]
@dreeanic Are you still experiencing this issue? Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by konradzuse** [comment]
I can confirm this is still an issue. I can perform 20-30 iterations before our app crashes.

We have a custom map renderer, there I can see that the dispose method is never called, so the map doesn't release it's resources.
