### ISSUE TITLE
[iOS] Random SIGSEGV & SIGTRAP crashes.

### ISSUE THREAD

**Issue by RalphJacobson** [xamarin/Xamarin.Forms#1883]
### Description

I'm receiving the following crash reports from HockeyApp for iOS:

- SIGTRAP - see [SIGTRAP.txt](https://github.com/xamarin/Xamarin.Forms/files/1724371/SIGTRAP.txt)
- SIGSEGV - Selector name found in current argument registers: _tintColorUpdating - see [SIGSEGV.txt](https://github.com/xamarin/Xamarin.Forms/files/1724375/SIGSEGV.txt)

I have no idea how to trace these issues.  Any suggestions?

### Steps to Reproduce

I unfortunately cannot give you steps to reproduce as it happens randomly.

### Expected Behavior

Not to crash the application.

### Actual Behavior

Crashes application.

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: Unknown
- IDE: Visual Studio 2017 Enterprise 15.5.6
- Platform Target Frameworks:
  - iOS:  11.2

**Comment by rmarinho** [comment]
Hi, thanks for the report but we will need at least a sample to look at try to reproduce on our side.

**Comment by RalphJacobson** [comment]
Hi, thanks for the reply.

I was able to symbolicate the stack trace for the SIGTRAP crash, see [SIGTRAP symbolicated.txt](https://github.com/xamarin/Xamarin.Forms/files/1726707/SIGTRAP.symbolicated.txt)

I don't have the dSYM's for the SIGSEGV crash anymore.

Hope this helps.

**Comment by RalphJacobson** [comment]
Turns out @rmarinho was right, just needed exception handling around some 3rd party lib and the problems went away. Thanks.
