### ISSUE TITLE
Xamarin.Forms.Pages dependes on modernhttpclient?

### ISSUE THREAD

**Issue by dazinator** [xamarin/Xamarin.Forms#1886]
### Description

When targeting `netstandard,` I get this build warning:

> warning NU1701: Package 'modernhttpclient 2.4.2' was restored using '.NETPortable,Version=v0.0,Profile=Profile259, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

This is seemingly because Xamarin.Forms.Pages has this dependency on ModernHttpClient? Why is this dependency needed? Does Xamarin.Forms.Pages make web calls? The nuget package isn't built for netstandard yet.

However this is a fork that is: https://github.com/alexrainman/ModernHttpClient

Can you consider dropping this dependency, or switching to netstadnard compataible one.

In my experience the application should be approvide the HttpClient handler, so it should be an option for the application to configure this, not something that xamarin enforces?

**Comment by rmarinho** [comment]
We need to update that Project

**Comment by Kukkimonsuta** [comment]
May I ask what is the reason behind having this dependency? I'm failing to see any use in the solution.

**Comment by ShahmanTeh** [comment]
may I know what's the status of this issue?  I'm using AlexRainman's ModernHttpClient-Updated and this has cause a conflicted references on Xamarin.Forms.Themes.

**Comment by mohammedwed** [comment]
I'm having the same issue, is there a solution? or a hack to get around with it?

**Comment by CZEMacLeod** [comment]
This was raised over a year ago and still has no answer or resolution.
@samhouts Just marking it inactive doesn't fix the problem for anyone... Is there an actual reason for the dependency, or can it be removed or fixed?

**Comment by samhouts** [comment]
Hi @CZEMacLeod! We're happy to accept a pull request for this issue. It is a lower priority for us, since the usage of Xamarin.Forms.Pages is much lower than the core packages. That said, I'm sure @pauldipietro and @davidortinau would love to hear about your experience with Xamarin.Forms.Pages and the problems that it solved for you! Thanks for your patience.

**Comment by andreinitescu** [comment]
See #5390
