### ISSUE TITLE
XAMLC fails with DataTrigger

### ISSUE THREAD

**Issue by MarcosCobena** [xamarin/Xamarin.Forms#1891]
### Description

Using a DataTrigger where Value references an enum fails at XAMLC time.

### Steps to Reproduce

1. Unzip attached [DataTriggerBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1726971/DataTriggerBug.zip)
2. Open contained sol. and build it

### Expected Behavior

Build succeeded.

### Actual Behavior

Build failed:

```
Building Solution: DataTriggerBug (Debug)
[...]
      Resource: DataTriggerBug.DataTriggerBugPage.xaml... 
       Creating empty DataTriggerBugPage.__InitComponentRuntime ...done.
       Copying body of InitializeComponent to __InitComponentRuntime ...done.
       Parsing Xaml... done.
       Replacing DataTriggerBugPage.InitializeComponent ()... failed.
    /Users/marcos/Projects/DataTriggerBug/DataTriggerBug/DataTriggerBugPage.xaml : error : The given key was not present in the dictionary.
      Changing the module MVID...done.
    
    Writing the assembly... done.
Done building target "XamlC" in project "DataTriggerBug.csproj" -- FAILED.

Done building project "DataTriggerBug.csproj" -- FAILED.

Build FAILED.

/Users/marcos/Projects/DataTriggerBug/DataTriggerBug/DataTriggerBugPage.xaml : error : The given key was not present in the dictionary.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.07

---------------------- Done ----------------------

Build: 1 error, 0 warnings
```

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: (don't know sorry)
- IDE: VS for Mac

**Comment by StephaneDelcroix** [comment]
I tested your xaml on master.

It now properly throws
> Position 8:14. The Property 'TargetType' is required to create a 'Xamarin.Forms.DataTrigger' object. 

and it works fine with the TargetType set.
