### ISSUE TITLE
NavigationPage.Navigation.PopToRoot(false) does not show RootPage on MacOS

### ISSUE THREAD

**Issue by therealjohn** [xamarin/Xamarin.Forms#1894]
_From @KlaasTroost on February 15, 2018 13:37_

### Steps to Reproduce

1. Create Xamarin Forms project
2. Add MacOS
3. add a MasterDetailPage
4. Add a NavigationPage to the Detail page 
5. Push 5 pages using the Navigation property.
6. At the end Close all pages with Navigation.PopToRoot(true)

### Expected Behavior
My expectation was that my first (the root) page would show up.

### Actual Behavior
PopToRoot(false) does do the job if you look at the NavigationStack.Count property, it is decreased from for example 5 to 1. But the RootPage does no get  shown. On UWP PopToRoot there's nothing wrong but on MacOS the RootPage does not Appear.

### Environment

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.3 (build 12)
Installation UUID: a52d80d8-32a8-4535-b541-efa27c3ab2ac
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.4 (Visual Studio Enterprise)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Enterprise)
Android SDK: /Users/klaastroost/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3  (API level 15)
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 27
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.216 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030012
Git revision: b07492f1e48be596bad92dc4b7a3bc2d128ed0f9
Build date: 2018-01-30 13:15:55-05
Xamarin addins: 7c8f967d67207118dd99a1d0cc9c228045b30c5f
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.2
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.1

### Example code
```
public async Task PopToRoot(int activeTab = 0)
{
   System.Diagnostics.Debug.WriteLine($"PopToRoot() - start - NavigationStack / ModalStack: {CurrentPage?.Navigation?.NavigationStack?.Count} / {CurrentPage?.Navigation?.ModalStack?.Count}");
   await CurrentPage.Navigation.PopToRootAsync(false);
   System.Diagnostics.Debug.WriteLine($"PopToRoot() - end - NavigationStack / ModalStack: {CurrentPage?.Navigation?.NavigationStack?.Count} / {CurrentPage?.Navigation?.ModalStack?.Count}");
}
```

### Output from code Above:
PopToRoot() - start - NavigationStack / ModalStack: 2 / 0
...
...
...
PopToRoot() - end - NavigationStack / ModalStack: 1 / 0

_Copied from original issue: xamarin/xamarin-macios#3496_

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
