### ISSUE TITLE
Samsung Device, Numeric Keyboard -> No comma, dot event not fired

### ISSUE THREAD

**Issue by OPunktSchmidt** [xamarin/Xamarin.Forms#1898]
### Description

When i create an entry with keyboardtype numeric and run my app on samsung devices, the keyboard shows not a comma key (,). It only shows a dot key (.). But when i press the dot key, the TextChanged event is not fired.

We confirmed this behavior on a Samsung Galaxy Tab A (2016) and Samsung A5. When we install an other keyboard than the standard samsung keyboard (like SwiftKey) it works but this would be not an user-friendly solution. Numeric keyboard works correctly on devices from HTC, Sony, LG etc.

### Steps to Reproduce

```
Xamarin.Forms.Entry entry = new Xamarin.Forms.Entry();
entry.Keyboard = Xamarin.Forms.Keyboard.Numeric;
```

Run this on an actual samsung device.

### Expected Behavior

It would be optimal if the comma key is displayed and working. Alternatively, but should at least the dot key fire the TextChanged Event.

### Actual Behavior

The keyboard shows not a comma key (,). It only shows a dot key (.). But when i press the dot key, the TextChanged ist not fired.

### Basic Information

- Version with issue: 2.5.0.91635
- Last known good version: I do not know exactly but any version of august or september 2017
- IDE: Visual Studio 2017
- Platform Target Frameworks:  
  - iOS:  9.0
  - Android: 8.0
- Affected Devices: All actual Samsung devices

### Screenshots

https://ibb.co/hiTnFn

**Comment by jassmith** [comment]
What language do you have set?

**Comment by OPunktSchmidt** [comment]
German

**Comment by jassmith** [comment]
Upon review this is an issue with the custom Samsung keyboards themselves. They do not respect the current locale and thus result in the wrong keys being displayed. I don't think there is any way for us to fix this however I would be excited to hear if there is one.

The best advice I can give is don't use a numeric keyboard on samsung phones on locales that use a , separator :/

**Comment by harrykimpel** [comment]
I think I found a solution for the comma issue on Samsung devices. I am using a custom Entry implementation in platform independent XAML content page. In the Android project I am then using a custom entry renderer that overrides the OnElementChanged method. My sample code snippet looks like this:

`protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                this.Control.KeyListener = DigitsKeyListener.GetInstance(true, true); // I know this is deprecated, but haven't had time to test the code without this line, I assume it will work without
                this.Control.InputType = Android.Text.InputTypes.ClassNumber | Android.Text.InputTypes.NumberFlagDecimal;
            }
        }`

That does the trick for me and now I can enter commas also on Samsung devices.

**Comment by danieltabarest** [comment]
@harrykimpel thanks for the help, it works for me.

**Comment by pigiax** [comment]
Great! The workaround works like charm

**Comment by EmilAlipiev** [comment]
> I think I found a solution for the comma issue on Samsung devices. I am using a custom Entry implementation in platform independent XAML content page. In the Android project I am then using a custom entry renderer that overrides the OnElementChanged method. My sample code snippet looks like this:
> 
> `protected override void OnElementChanged(ElementChangedEventArgs e)
> {
> base.OnElementChanged(e);
> 
> ```
>         if (Control != null)
>         {
>             this.Control.KeyListener = DigitsKeyListener.GetInstance(true, true); // I know this is deprecated, but haven't had time to test the code without this line, I assume it will work without
>             this.Control.InputType = Android.Text.InputTypes.ClassNumber | Android.Text.InputTypes.NumberFlagDecimal;
>         }
>     }`
> ```
> 
> That does the trick for me and now I can enter commas also on Samsung devices.

that solution isn't a good one. it only changes skin of the keyboard replacing dot with comma. that's why comma appears 2 times (one grayed out) in the keyboard but in fact, when you press the comma, entry get a dot and you should replace it using string replace dot with comma. it is a dirty workaround. I believe that it is a but in Xamarin, not in Samsung. Samsung does different than other manufacturers.

I dont believe that this is a samsung problem. actually samsung does different than other manufacturers.

- other manufacturers: they display dot and comma in their keyboard regardless of culture and let the user to handle decimal text input in their code.

- samsung: they display dot or comma based on the culture. this culture I dont know what? Is it culture of app, probably no. is it culture of text input, probably. but samsung keyboard does that and Xamarin.android doesnt handle it. I tested with java written app, it works just fine. it just doesnt appear on other manufacturers because they dont restrict like samsung,

**Comment by wagenheimer** [comment]
Please, anybody could please post the complete solution to Workaround this?

**Comment by EmilAlipiev** [comment]
You have asked on xamarin forums and there is reply there. It didnt help?

**Comment by wagenheimer** [comment]
The reply here is a bit different of others I tested and that didn't work. I just implemented it, but I don't have a Samsung Device to test it. My client will test it tomorrow and then give a feedback if it worked or not.

**Comment by EmilAlipiev** [comment]
As i wrote on forum, reply here is outdated. Please follow forum reply and if you have any further question you can ask there

**Comment by VirtualNomad00** [comment]
> As i wrote on forum, reply here is outdated. Please follow forum reply and if you have any further question you can ask there

Can you post the link to the forum

**Comment by AlexxSilva** [comment]
This solution works.
