### ISSUE TITLE
[Enhancement] 'IsSelectionEnabled' on ListView

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1901]
## Rationale 

A common question about the Xamarin.Forms ListView is how to disable selection. Current methods require custom renderers and/or handling the ItemSelected event by de-selecting the item. This is a common enough request that we should simply provide a property to handle it.

## Implementation

ListView will need a new bindable property `IsSelectionEnabled`. The default value will be `true`. When this property is set to `false`, tapping/clicking on items in the ListView will no longer select them; the ItemSelected event will not fire, the item will not be highlighted as "selected", and the value of the SelectedItem property will remain null.

If the SelectedItem property is set when `IsSelectionEnabled` transitions to `false`, SeletedItem will be set to `null` and the ItemSelected event will not fire. 

When `IsSelectionEnabled` is `false`, the ItemTapped event will still fire.

## Difficulty: Medium

Disabling all selection highlighting on all platforms might prove to be a challenge.

**Comment by andreinitescu** [comment]
@hartez I already submitted this one https://github.com/xamarin/Xamarin.Forms/issues/1801
I think having an enum instead of a bool flag makes it easier to extend it in the future for multiple selection.

**Comment by hartez** [comment]
@andreinitescu Somehow I missed that when I look for proposals. And after talking with Shane about it and thinking some more, you're right - the enum is a better option. Gonna close this one.
