### ISSUE TITLE
InputTransparent Does Not Handle Keyboard Input

### ISSUE THREAD

**Issue by jkastner** [xamarin/Xamarin.Forms#1903]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
When a control, such as a button, has InputTransparent set to true, mouse interaction is disabled as expected. However, Keyboard interaction is still possible, as when a user 'tabs' onto the control and presses the keyboard to activate the button.

### Steps to Reproduce

1. Create a Button element in xaml. 
2. Set InputTransparent to True
3. Press 'tab' until the Button is highlighted.
4. Press 'space' or 'enter' to activate the button.

### Expected Behavior
The keyboard strokes are ignored, as the control is flagged as input transparent.

### Actual Behavior
The Button's bound command or click event is activated.
### Basic Information

- Version with issue: 
2.5.0.280555
- Last known good version:
None.
- IDE:
VS 2017 15.5.2

- Platform Target Frameworks: 
  - Android: 8.0 
  - UWP:  14393

- Nuget Packages: 
Xamarin.Forms 2.5.0.280555
Microsoft.NETCore.UniversalWindowsPlatform 5.2.2

- Affected Devices:
UWP 
Android Virtual Device

### Screenshots
![inputtransparentbug](https://user-images.githubusercontent.com/1066087/36324198-a1ad662c-1321-11e8-8e12-929ecb47cba1.gif)

### Reproduction Link
https://github.com/jkastner/InputTransparentXFBug

**Comment by rmarinho** [comment]
Seems the logic thing to do here is to set IsEnabled to false on the button , or bind the command to the view model and handle the CanExecute action. InputTansparent is related with overlay of components not tab stop. I think the best we can do is mark this as a Enhancement for tab stop feature on Xamarin.Forms

**Comment by rmarinho** [comment]
We should review this when we pick #1700

**Comment by jkastner** [comment]
The reason we didn't go for the IsEnabled option in the first place was to avoid having to restyle the control, but that makes sense. I appreciate the suggestion on the CanExecute callback - that's the approach we're taking to workaround this problem. 

I'd still suggest it be fixed, in addition to the TabStop support, as it's not obvious that a user could still access the transparent control through sheer accident or clever intent. 

Personally, we're not blocked, however.

**Comment by samhouts** [comment]
I believe this should now be resolved in 3.4.0. You can set IsTabStop = false. Thank you!
