### ISSUE TITLE
Editor Placeholder/PlaceholderColor

### ISSUE THREAD

**Issue by ozielguimaraes** [xamarin/Xamarin.Forms#1907]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Why Editor doesn't have a property Placeholder and PlaceholderColor?

### Steps to Reproduce

1. Missing property Placeholder
2. Missing property PlaceholderColor

### Expected Behavior
Placeholder and PlaceholderColor properties for Editor as the Entry element.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by cbwalther1** [comment]
There is an iOS bug. Long placeholders that should be more than 1 line aren't wrapped/clipped to the Editor's bounds.

**Comment by cbwalther1** [comment]
> There is an iOS bug. Long placeholders that should be more than 1 line aren't wrapped/clipped to the Editor's bounds.

Sorry, I see there is an opened issue already.
https://github.com/xamarin/Xamarin.Forms/issues/4291
