### ISSUE TITLE
iOS ListView items Layout View Rendering 

### ISSUE THREAD

**Issue by gregmercer** [xamarin/Xamarin.Forms#1911]
# iOS ListView with Layout View Rendering

### Description

Update: I've added a screenshot, mov and stacktrace. All are located on the following repo.
https://github.com/gregmercer/ListFrames4

On iOS the Slots are not rendered (or invisible?). Displays a blank open space where the Slots should have been rendered.

### UI Structure

```
Xamarin Forms 
  Content Page
    StackLayout
      ListView (ItemSource Rooms)
        ItemTemplate 
          DataTemplate
            StackLayout
              Label
              Label
              TimeSlotsWrapLayout (Layout<View>)
                BindingProperty (TimeSlotsSourceProperty TimeSlots)
                  Frame (Varying number Frames - TimeSlots)
                    Label 
```                  

Not using groups 

### Code @
https://github.com/gregmercer/ListFrames2
https://github.com/gregmercer/ListFrames4
(I've recently simplified the code that causes the issue - so it is much easier to follow. Also just added another variation, ListFrames4, which uses a 'more standard' ItemsSource for the WrapLayout and a template for the TimeSlots.)

### Stack Trace

https://github.com/gregmercer/ListFrames4/blob/master/stacktrace-2.5.0.280555.txt

### Steps to Reproduce
- When App opens the FramesPage gets OnAppearing. Shows page with UI structure hierarchy shown above.
- Tab to second page - OtherPage.
- Tab back to Frames page.

### Actual Behavior
- Scroll. Notice Slots are not being rendered (or invisible?).

### Expected Behavior
- The Slots should be displaying correctly for each ListView row.

### Some findings:

> Running with local build of Xamarin Forms I've found that if I changed the 

> RendererPool.cs UpdateNewElement method to have the following new testing code it 

> seemed to cause the Slots to render correctly:

```
public void UpdateNewElement(VisualElement newElement)

    ...

      if (oldChildren.Count == newChildren.Count)
      {
        for (var i = 0; i < oldChildren.Count; i++)
        {
          if (oldChildren[i].GetType() != newChildren[i].GetType())
          {
            sameChildrenTypes = false;
            break;
          }
        }
      }
      else
        sameChildrenTypes = false;

<testing code added>

      if (sameChildrenTypes) 
      {
          if (newElement is StackLayout)
          {
              //sameChildrenTypes = false;
              ClearRenderers(_parent);
              FillChildrenWithRenderers(newElement);
              return;
          }
      }

</testing code added>
```

### Basic Information

> Version with issue: - Include="Xamarin.Forms" Version="2.5.0" a356efc
Last known good version: - New issue

> IDE: - Visual Studio

> Platform Target Frameworks:
iOS: Renders incorrectly, or invisible.
Android: Works fine

### Nuget Packages:
Xamarin Forms

### Affected Devices:
IOS emulator and iPhone 6 (real device)

Screenshots

https://github.com/gregmercer/ListFrames4/blob/master/Screen-Shot2018-02-22-7.42.45-AM.png

**Comment by samhouts** [comment]
I downloaded the project and ran it on both Android and iOS. I didn't notice any missing slots. Can you provide screenshots to illustrate the behavior you're describing? Thanks!

**Comment by gregmercer** [comment]
Hi Samantha,

I've added a screenshot, mov file and a stack trace for the issue. All of
these files can be found at:

https://github.com/gregmercer/ListFrames4

Thanks,
Greg

**Comment by gregmercer** [comment]
Can anyone give me an update on this issue?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
