### ISSUE TITLE
GUI Contribution

### ISSUE THREAD

**Issue by AnaChips** [xamarin/Xamarin.Forms#1913]
### Description
When a developer develops a app in Xamarin, the Business logic is written in C# and the UI is coded manually through XAML. Untill the app runs on a emulaor/device, the developer has only a vague idea(imagination) of the UI developed. Thus this project focuses on building "the GUI based design element" in Xamarin-forms. (It is inspired by android studio).

### Expected Behavior
![image](https://user-images.githubusercontent.com/25129720/36352516-1aa4896a-14e0-11e8-9835-89e455ee9be1.png)

https://drive.google.com/open?id=0Bx5OwGPUWtTvMmJMMmMxWm05S01iVFltMmRLMk5pUHFMQVVv

The project plans to provide the facility of the  canvas on which widgets can be dropped from the adjacent widget-palette. It also aims at the creation of the design and text tabs, where-in the XAML code will be auto-generated as per the designed UI. 

### Actual Behavior
![image 1](https://user-images.githubusercontent.com/25129720/36352520-2272bb6c-14e0-11e8-883e-73450bbb733c.png)

https://drive.google.com/file/d/0Bx5OwGPUWtTvWWhPdW9tR0d4cmZ2RUthVEstTUFtZDk5d3g4/view?usp=sharing

(Use drive links if image is not accessiable)

**Comment by davidortinau** [comment]
Thanks for the mock. I can say with certainty that many many Xamarin.Forms developers would welcome design tools.

As this is not the domain of Xamarin.Forms itself, but rather that of developer tools, I'm closing this issue. If you undertake building a designer for Xamarin.Forms, please keep us posted on your progress!
