### ISSUE TITLE
[Enahacement] [Documentation] Update the Element class hierarchy diagram

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#1914]
### Rationale

I found myself looking many times to the hierarchy diagram from here https://developer.xamarin.com/api/type/Xamarin.Forms.Element/. I think it's a great reference for developers. And I am sure I not the only one who thinks the same.
But the diagram hasn't been updated to include newer classes like TemplatedPage, TemplatedView, or TableView.

I wish it included all classes.

Also, I wish it had a way to view the image without zooming-in or save the image (the image is actually in full size), something like clicking the image to see it full view would be great.

**Comment by andreinitescu** [comment]
Uh oh, the image I referred to is now gone in the link to the `Element` class, probably it didn't make it when documentation migrated from Xamarin to Microsoft docs. 
Such a pitty! Please, please put it back.
For the reference, I am referring to this image: 
![5oivx](https://user-images.githubusercontent.com/743918/47168041-9488ea00-d308-11e8-98c6-7ed9882b8157.png)
In my issue from February 18, 2018 I was referring that the image hasn't been updated with all the new classes.

**Comment by jfversluis** [comment]
Don't think this is very relevant anymore and worth investing time in. Thanks for the suggestion!
