### ISSUE TITLE
Previewer doesn't work for custom components in Xamarin.forms.Android

### ISSUE THREAD

**Issue by RathanakumarSekar** [xamarin/Xamarin.Forms#1918]
### Description

While we checking the XAML previewer for custom components in Xamarin.Forms.Android  InvalidcastException occurred in previewer window. In iOS it works good.

For you reference i have attached the screen shot image.

Please check the same issue from your side and let me know if you have any concern on this.

### Basic Information

- Version with issue:  2.5.0.280555

- IDE:
- Platform Target Frameworks: 

  - Android:  

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/36629214/36379173-9e80d658-15a3-11e8-929b-9a0956bb4904.png)

**Comment by samhouts** [comment]
Can you be more specific about the custom components that you're using? If you could provide a reproduction project, that would be helpful. Thanks.
