### ISSUE TITLE
Visual Studio 2017 (v15.5.6) Create an empty solution (0 Projects)

### ISSUE THREAD

**Issue by Amine-Smahi** [xamarin/Xamarin.Forms#1922]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
After creating a Xamarin.Forms project using visual studio 2017 i get an empty solution, but when i create an xamarin.android project then it works, it seems like there is a problem with xamarin.forms, i installed everything xamarin needs from the bootstraper.
### Steps to Reproduce

1. New Project > Cross Platform > Xamarin.Forms 

### Expected Behavior

Create a working project with xamarin.forms project with xamarin.Android and xamarin.IOS

### Actual Behavior
Create an empty solution ( 0 projects)
### Basic Information
Visual studio 2017 version 15.5.6
![p20](https://user-images.githubusercontent.com/24621701/36391824-95332ccc-15a8-11e8-938c-cbc9854f3a0e.png)

### Screenshots
![p19](https://user-images.githubusercontent.com/24621701/36391835-9ee9ae94-15a8-11e8-85ed-656cefcf838f.png)

### Reproduction Link
![p17](https://user-images.githubusercontent.com/24621701/36391859-b94b06d4-15a8-11e8-824d-c410552292e6.png)
![p18](https://user-images.githubusercontent.com/24621701/36391878-c8f87526-15a8-11e8-96eb-9af695ebd5a0.png)

**Comment by oussamabonnor1** [comment]
i am currently having the same issue, i hope they fix it soon.

**Comment by jimmgarrido** [comment]
This is most likely an issue with the template creation rather than Xamarin.Forms itself. Is this a new VS install? Can you create a new Xamarin.Forms project but unselect the Android platform to see if that works? And please also attach the logs from Help > Xamarin > Zips Logs. 

Thanks!

**Comment by Amine-Smahi** [comment]
Yes @jimmgarrido this is a new install, i did create  a new Xamarin.Forms project but unselect the Android platform and it didnt solve the problem , i stil get 0 projects

**Comment by biapar** [comment]
I've the same problem.

**Comment by jassmith** [comment]
https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/578252

Moved to the appropriate team

**Comment by jimmgarrido** [comment]
I've moved this over to developer community so this can be tracked as a Visual Studio issue: https://developercommunity.visualstudio.com/content/problem/210099/new-xamarinforms-template-creates-empty-solution.html

Please vote and comment on the new report.

**Comment by brotherkennyh** [comment]
I am having this same issue. I have a fresh install on a new PC. Have reinstalled Vs and Xamarin a number of times. Old projects seem to work., but I cannot create a new one. I'm on VS 2017 Community 15.7.3

Any help would be appreciated.

**Comment by joelcdoyle** [comment]
This issue still exists, even at VS 15.7.3, despite the resolved status of the Dev Community ticket

**Comment by foreverfun** [comment]
I fixed the problem by moving C:\Program Files\dotnet\ above/up C:\Program Files(x86)\dotnet\ in my path environment variable.

**Comment by davidhenley** [comment]
Same issue, brand new install. I have tried reinstalling, but still same.

**Comment by StefanOber** [comment]
Repair didn't work for me. But I updated and installed the latest Android SDKs in Tools > Android > SDK Manager and now it works (the problem only appeared when I selected Android but not with iOS).
