### ISSUE TITLE
StackLayout with large HeightRequest overflows boundary of containing StackLayout

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#1924]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=42727 here

From the bugzilla report:
I've got a Label in a StackLayout in a StackLayout:

Due to the large HeightRequest the inner StackLayout fills the whole space available. But if we remove its child Label, the StackLayout grows beyond the size of its parent StackLayout.

The attached screenshot demonstrates the behavior.

We'd expect the HeightRequest to be evaluated independently of the containing Children.

Also as noted in the report, a button acts differently than a label, with a button added it overflows, while a label doesn't.

### Steps to Reproduce

Run app
Note that the yellow stacklayout does not overflow
Comment out the label in stacklayout, or change it to be a button instead
Note that the yellow stacklayout overflows

### Expected Behavior
Stacklayout does not overflow

### Actual Behavior
Stacklayout overflows

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 7, and iPhone 6s running iOS 9.3

### Screenshots
https://bugzilla.xamarin.com/attachment.cgi?id=16754

### Reproduction Link
https://www.dropbox.com/s/ruznx1levdzkdwi/stacklayoutheightsample.zip?dl=0

**Comment by samhouts** [comment]
It is an interesting behavior, and I believe it's due to Labels reporting back their height after rendering to resize their parents due to word-wrapping, etc. 


May I ask what your use case is for wanting the inner StackLayout to overflow in all cases?

Thanks

**Comment by Paul-Brenner-Tangoe** [comment]
@samhouts I have not experienced this one myself, I just migrated it because it seemed like something that should be fixed. I think the expected behavior would be that it should not overflow in all cases.

**Comment by Paul-Brenner-Tangoe** [comment]
@samhouts can you remove the needs info tag please

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
