### ISSUE TITLE
iOS ListViewRenderer has a bug in row insertion/deletion logic.

### ISSUE THREAD

**Issue by mll** [xamarin/Xamarin.Forms#1927]
### Description

See commit 1f770f65886213e28677092ccea355ee799cfa51 (the current commit on master at the time of writing).

The code in Xamarin.Forms/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs: 532-544
reads:

			switch (e.Action)
			{
				case NotifyCollectionChangedAction.Add:

					UpdateEstimatedRowHeight();
					if (e.NewStartingIndex == -1 || groupReset)
						goto case NotifyCollectionChangedAction.Reset;

					Control.BeginUpdates();
					Control.InsertRows(GetPaths(section, e.NewStartingIndex, e.NewItems.Count), InsertRowsAnimation);
					Control.EndUpdates();

					break;

This code is buggy and leads to crashes when the ListView is dynamically updated using ObservableCollection as its data source. This is because updates to the UITableView are not issued in an appropriate way. 

Imagine an empty list. When you try to dynamically add an element using ObservableCollection.Add(),
the event is intercepted and the code above is executed. The problem is that the dataSource for UITableView gets updated *before* BeginUpdates() gets called. This causes a crash coming from UITableView internals that reads:

"NSInternalInconsistencyException Reason: Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out)."

This is because the data source was updated way before the code on hand was run. The data source should reflect the situation before the update at the time BeginUpdates() gets called, then the update to the data source should be applied, then the InsertRows() should be called and finally EndUpdates() should be issued.

### Steps to Reproduce

1.  Create a new project with a single page containing a ListView bound to ObservableCollection<string> as its ItemSource and a single button.
2. On a button action, call Add("test") on the ObservableCollection.
3. Run the project on an iOS device and click on the button.

### Expected Behavior

The "test" row should be added to the list.

### Actual Behavior

A crash:

"NSInternalInconsistencyException Reason: Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out)."

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: Unknown
- IDE: Visual Studio OS X 7.3.2(12) and Visual Studio 2017 on a PC (15.5.2)
- Platform Target Frameworks: 
  - iOS:  All
  - Android: Irrelevant
  - UWP:  Irrelevant
- Android Support Library Version: Irrelevant
- Nuget Packages: Irrelevant
- Affected Devices: All iOS devices

**Comment by samhouts** [comment]
Probably related to #1900

**Comment by samhouts** [comment]
@mll Do you still experience this issue? I am having trouble getting this scenario to crash. Thanks!

**Comment by mll** [comment]
Hi @samhouts. I do not work with Xamarin anymore. That said - if no one changed the code exempts above the bug will persist. It will not necessarily manifest itself in all the scenarios but it should be reproducible if you try some experimentation.
