### ISSUE TITLE
Creating a project with a dash in the name does not update the standard namespace

### ISSUE THREAD

**Issue by benjs** [xamarin/Xamarin.Forms#1928]
### Description
When creating a project with a dash in the name, the standard namespace is not updated.

### Steps to Reproduce

1. Create a Cross-Platform .Net Standard Xamarin project with a dash in the name, for example "project-name"
2. Create a file, for example "ViewModelBase.cs"
3. Multiple Errors appear (because of the dash)

### Expected Behavior
When creating the project with the name "project-name", the standard namespace should change to "project_name". It is already changed in the standard "MainPage.xaml", but not in the project settings.

### Basic Information

- Version with issue: 2.5.0.280555
- IDE: Visual Studio 2017 Community, Version 15.5.6

**Comment by jfversluis** [comment]
I think this is more of a Visual Studio issue than a Xamarin.Forms one. Closing this.
