### ISSUE TITLE
Xamarin Forms on Android: ScrollView on ListView header crashes app when closing page

### ISSUE THREAD

**Issue by Mirksar** [xamarin/Xamarin.Forms#1931]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
In a page with this structure:

        <ListView>
            <ListView.Header>
                <ScrollView Orientation="Horizontal">
                    <StackLayout Orientation="Horizontal">
                        <BoxView Color="Green ">
                        </BoxView>
                    </StackLayout>
                </ScrollView>
            </ListView.Header>
        </ListView>

The app crashes when pressing back on the device with this stack trace:

ScrollViewRenderer.Dispose (System.Boolean disposing)
D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs - line 180
System.NullReferenceException: Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
ScrollViewRenderer.Dispose (System.Boolean disposing) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:180
Object.Dispose () /Users/builder/data/lanes/5809/413eed68/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:203
ListViewRenderer.Dispose (System.Boolean disposing) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewRenderer.cs:60
Object.Dispose () /Users/builder/data/lanes/5809/413eed68/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:203
VisualElementRenderer`1[TElement].Dispose (System.Boolean disposing) D:\agent\_work\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:234
Object.Dispose () /Users/builder/data/lanes/5809/413eed68/source/monodroid/external/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:203

### Steps to Reproduce
Please, find atached a project that reproduces the crash. Execute the project and just press back on Android

### Expected Behavior
Going back from the app doesn't crash the app
### Actual Behavior
When pressing back on the navigation  the app crashes

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: 8.0

### Reproduction Link
https://www.dropbox.com/s/di52t93ag4kewxe/ScrollCrashTest.7z?dl=0

**Comment by HoussemDellai** [comment]
For now you can put the ScrollView inside a Grid and that should work.
<ListView>
    <ListView.Header>
        <Grid>
            <ScrollView Orientation="Horizontal">
                <StackLayout Orientation="Horizontal">
                    <BoxView Color="Green ">
                    </BoxView>
                </StackLayout>
            </ScrollView>
        </Grid>
    </ListView.Header>
</ListView>

**Comment by tekinc** [comment]
@hartez is this resolved?

**Comment by hartez** [comment]
@tekinc Yes. Fixed in XF 3.1.0 and later.

**Comment by tekinc** [comment]
@hartez I tested with 3.1.* and 3.2.* preview, both failed. My use case is on a push notification within the app, App() is called again and my mainpage is reloaded.

**Comment by tekinc** [comment]
Yes it does.

Tarek Ahmed
TEK Inc
http://www.tek.us
o.(855) 354-5TEK
m.917. <917.696.8126>304.9444

**Comment by hartez** [comment]
Just tested the reproduction project against 3.1, and it does not throw the exception. 

> App() is called again and my mainpage is reloaded. That's when I get the exception.

Based on this I think we're looking at a different bug. Please create an issue for this and we'll look into it.
