### ISSUE TITLE
GTK: App Lifecycle events have not been implemented

### ISSUE THREAD

**Issue by robertsundstrom** [xamarin/Xamarin.Forms#1933]
## Rationale
For GTK+, the app lifecycle events have not been implemented.

The following methods should be invoked on the ```Application``` object from ```Xamarin.Forms.Platform.GTK.FormsWindow``` in order to invoke the corresponding lifecycle event handlers:

* SendStart();
* SendResume();
* SendSleep();

Some of them doesn't seem to fit in the window-based paradigm, as also is the case with the macOS binding.

Shouldn't there be a Quit event? Why not?

**Comment by jsuarezruiz** [comment]
I'm gonna review it!.
The implementation of SendStart() is simple. I have to think how to fit the rest of the events.
As for the Quit event, in PlatformServices each platform implements a QuitApplicaiton method, do you mean that?

**Comment by robertsundstrom** [comment]
@jsuarezruiz Great! 

I just wondered how to detect when the app really is quitting. There is no overridable method for that in the App class.
