### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#1936]
### Description

Since using asynchronous calls to our web services I am now getting this exception every so often.

Literally performing the same operation replicates it 10% of the time: Launch App > Click on MasterDetailPage > Select Settings Page (Tabbed page with 2 pages).

The other 90% of the time everything works as expected.

Every now and again it will throw an object reference not set to an instance of an object instead.

There is a web services implementation call which syncs the settings when the page loads.

VS breaks on the following line of code:

return DependencyService.Get<IWebServices>().CallProgFromWeb(parameterObj, encryptionKey);

With "System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary."

Both parameterObj and encryptionKey are ok.

IWebServices seems to appear under the property DependancyTypes, the only different to the others being the value "GlobalInstance" seems to be null under DependancyImplementions.

I have also noticed it only seems to fall over when IWebServices is in the DependencyService.DependancyImplementions twice for some reason.

I have tried adding the line "DependencyService.Register();" into the App page with no luck.

StackTrace:
at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.2/src/mono/external/corert/src/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:223 
at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00041] in D:\agent_work\1\s\Xamarin.Forms.Core\DependencyService.cs:28

I'm not sure if this issue is just for IOS but I can replicate it in IOS every x number of tries, Android I couldn't.

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  11.2
- Nuget Packages: 
Behaviors.Forms
sqlite-net-pcl
Zxing.Net.Mobile.Forms
Xamarin.Controls.SignaturePad

### Screenshots

![xamarin1](https://user-images.githubusercontent.com/29727003/36472636-44573148-16ea-11e8-974f-ad55aeab39c4.png)

![xamarin2](https://user-images.githubusercontent.com/29727003/36472998-3a500e8a-16eb-11e8-8a09-6e153e114f44.png)

**Comment by daves1992** [comment]
I think I have whittled this down to performing two dependency calls essentially at the same time after app load which would explain the duplication.

The first page in the tab page was going off and syncing the settings using the webservices implementation while the second page also went off and retrieved a data list.

**Comment by samhouts** [comment]
Do you have a reproduction project you can share with us? It'll be difficult to diagnose anything on our side without it. Thanks.

**Comment by rags217** [comment]
I am facing the same issue. Randomly dependency service throws  (null or keynotfound) exception for database interface implementation in Android platform.

**Comment by jassmith** [comment]
No repro and I can't cause it with my wild guessing. If you want to post a repro @rags217 feel free to re-open.
