### ISSUE TITLE
[UWP] Choppy animation

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#1937]
### Description

Animation is choppy on UWP [link1](https://forums.xamarin.com/discussion/113862/uwp-animation-performance-issues) [link2](https://forums.xamarin.com/discussion/90173/uwp-animation-performance-with-xamarin-forms) [link3](https://forums.xamarin.com/discussion/comment/266814#Comment_266748).

### Expected Behavior

60 fps (if that is the screen refresh rate)

### Actual Behavior

24-30 fps

### How to fix

A search of DispatcherTimer in the repo returns several examples with Interval=TimeSpan.FromMilliseconds(15) or 16. LayoutPerformanceGallery.cs also uses a TimeSpan.FromMilliseconds(10). These are clearly attempts to get 60fps but they will fail on Windows because of [slow timers](https://github.com/xamarin/Xamarin.Forms/issues/1623). 

Instead, a CompositionTarget.Rendering event should be used on Windows.

**Comment by MelbourneDeveloper** [comment]
Can confirm that animations are terrible in UWP. We have a sidebar menu that collapses and opens. You can see visually that it does so in about 4-5 steps. It looks terrible.
