### ISSUE TITLE
Expose a rendering event in Xamarin.Forms

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#1938]
It is standard to use timer on Xamarin.Forms to do somthing once a frame ([example](https://forums.xamarin.com/discussion/100569/how-to-animate-a-simple-smooth-rotation)), but this fails because of [slow timers](https://github.com/xamarin/Xamarin.Forms/issues/1623) on Windows and is not the best approach in any case.

A rendering event exposed in Xamarin.Forms would be a much better approach.

This will allow users to do their own animation smoothly, whereas https://github.com/xamarin/Xamarin.Forms/issues/1937 would give smooth animations of Xamarin.Forms elements.

**Comment by samhouts** [comment]
We had a similar conversation on https://forums.xamarin.com/discussion/84510/improved-life-cycle-support. Is this the behavior that you need? Thanks.

**Comment by charlesroddie** [comment]
I don't think so as these events need to be once per frame (usually 60fps) while those are rarer.

The intention is to do animation in SkiaSharp and I am not completely sure if refresh information should be derived from Xamarin Forms or from SkiaSharp. @mattleibow is this issue better off in SkiaSharp?

**Comment by mattleibow** [comment]
SkiaSharp is really independent of how to get a refresh rate as it just draw when told to do so. You could also just call Invalidate in the paint event. Painting is requested at the next available moment, so it is fine to do that.

I'll be honest, I noticed choppy animations with UWP, but not so much with Android and iOS, so it looks to be the timer.

**Comment by mattleibow** [comment]
It was mentioned in the "parent" issue that there could be an event that is raised when the screen is refreshed. That will be good for skiasharp as I think that logic is not skiasharp specific and may be used by other frameworks.

With skiasharp on native, not forms, the developer will have access to the native mechanisms.

**Comment by jassmith** [comment]
I'd take such an API if we had a suggestion of what event to hook on each platform.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. I think something might be implemented in this regard in .NET MAUI already.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or maybe even already implemented or open an issue with a detailed feature request. Thanks!
