### ISSUE TITLE
[iOS] ImageCell command triggered when raising CanExecuteChanged

### ISSUE THREAD

**Issue by xamoulin** [xamarin/Xamarin.Forms#1940]
### Description

The command bound to an ImageCell is executed when CanExecuteChanged is raised while the cell is selected on iOS. It work as expected on Android.

### Steps to Reproduce

1. Bind a command to items of a ListView
2. In the Execute method of the command, raise CanExecuteChanged (with CanExecute = false)
3. Still in the Execute method, raise CanExecuteChanged (with CanExecute = true)
4. The command will be triggered again 

### Expected Behavior

The Command is not triggered again

### Actual Behavior

The Command is triggered again

### Basic Information

- Version with issue: 2.5.0.122203
- IDE: Rider (MacOS)
- Platform Target Frameworks:
  - iOS:  Min version: 10.0, Device: 11.2.5
- Affected Devices: iPod, iPhone, and simulator (I haven't tried on iPad)

### Reproduction Code

    public class AsyncCommand : ICommand
    {
        ...
        
        public bool CanExecute(object parameter)
        {
            return !executionInProgress;
        }
    
        public async void Execute(object parameter)
        {
            await ExecuteAsync(parameter);
        }
    
        private async Task ExecuteAsync(object parameter)
        {
            executionInProgress = true;
            ChangeCanExecute();
            try
            {
                await execute(parameter);
            }
            finally
            {
                executionInProgress = false;
                ChangeCanExecute();
            }
        }
    
        public void ChangeCanExecute()
        {
            CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }
    }

**Comment by samhouts** [comment]
Can you provide a more complete reproduction project that shows how you have bound the command to the ListView items? Thanks!

**Comment by xamoulin** [comment]
Here is a repro project : [ImageCellCommandBug.zip](https://github.com/xamarin/Xamarin.Forms/files/1830485/ImageCellCommandBug.zip)

While doing it, I identified additional requirements to reproduce the bug:
- The ListView must not have its CachingStrategy set to RecycleElement
- The ImageCell must have a context action

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
