### ISSUE TITLE
Unable to retrieve the margin set in the DataTemplate

### ISSUE THREAD

**Issue by SridharanGajendran** [xamarin/Xamarin.Forms#1945]
### Steps to Reproduce

Xamarin.Forms.View templateLayout = listView.ItemTemplate.CreateContent() as Xamarin.Forms.View;

IVisualElementRenderer render = templateLayout.GetOrCreateRenderer();

When created the renderer, in UWP, I am not able to get the margin of the data template.

### Expected Behavior
Need to get the margin value set for the root panel in the data template.
### Actual Behavior
No margin value is able to get.

### Basic Information
  - UWP:  16299 
- Nuget Packages: latest Xamarin Nuget Package

**Comment by samhouts** [comment]
Can you provide a reproduction project that shows what you're trying to do? Thanks
