### ISSUE TITLE
Firing INPC on compiled bindings isn't updating the UI

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#1949]
### Description

When using compiled bindings, firing INPC on properties that views on the UI bind to isn't resulting in an updated UI.

If you switch off compiled bindings, the page works as expected.

### Steps to Reproduce

1. Run the attached sample.
2. On the CompiledBindings page enter some text in the Entry.

### Expected Behavior

Entered text is stored in the CompiledBindingsViewModel.Text property, and INPC fires and updates the UI (entered text is displayed and the boolean value changes to true).

### Actual Behavior

Entered text is stored in the CompiledBIndingsViewModel.Text property, INPC fires but the UI isn't updated despite binding to the correct view model properties.

### Basic Information

- Version with issue: 2.6.0.200305-nightly
- IDE: VSMac 7.3.3
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: API 26

### Reproduction Link

[CompiledBindings-INPCerror.zip](https://github.com/xamarin/Xamarin.Forms/files/1747538/CompiledBindings-INPCerror.zip)

**Comment by StephaneDelcroix** [comment]
So the problem is about this Binding

```xaml
<Label Text="{Binding IsTextEntered}" />
```

to this property

```csharp
public bool IsTextEntered
{
    get { return !string.IsNullOrWhiteSpace(_text); }
}
```

not being updated. It's probably due to the mismatch between types (`string` and `bool`)

**Comment by davidbritch** [comment]
Here's a new sample with a converter for displaying the `IsTextEntered` property from the view model. I've also updated the sample to Forms 3.1.
 
Note that while the `Text` property is set as the user enters text in the `Entry`, the `Label` that also binds to the `Text` property isn't updated.

[CompiledBindings-INPCerror.zip](https://github.com/xamarin/Xamarin.Forms/files/2222823/CompiledBindings-INPCerror.zip)

**Comment by StephaneDelcroix** [comment]
if I copy-paste your code in my test project, it works fine. I wonder what's going on...

**Comment by StephaneDelcroix** [comment]
I think I've nailed it. `PropertyChangedEventHandler`s are getting collected
