### ISSUE TITLE
Add a way to set RaiseOnEqual flag in bindable property to true

### ISSUE THREAD

**Issue by sdebruyn** [xamarin/Xamarin.Forms#1950]
### Description

Bindable properties are not set when the original value reference equals the new value. Xamarin.Forms includes an internal flag `SetValueFlags.RaiseOnEqual` to change this behavior. While this flag is correctly checked when applying a new value, there is no way to enable this flag.

### Steps to Reproduce

1. Create a bindable property
2. Set the value of the property
3. Explicitly set the same value again

### Expected Behavior

Property changed notification and a way to enable this behavior (as an option in the Bindable Property)

### Actual Behavior

No notification

### Use case

The bindable property contains information with a metric unit (e.g. 1 meter). The information is stored in an abstract way without a unit and the unit itself is added with an `IValueConverter`.

The user of the app changes his preferences; he now wants to see all information in imperial units. The source triggers a property changed notification with an empty string because all the converters need to be triggered again so that they can now represent the same information in a different manner (in this case: 3.28 feet).

### Relevant code

https://github.com/xamarin/Xamarin.Forms/blob/bfd3ad6491329e58ab145d20d2057ecfb0e06b52/Xamarin.Forms.Core/BindableObject.cs#L585

On line 585, there is a reference equals check. On lines 586 and 594 the code uses that check _or the unused RaiseOnEqual flag_ to verify if it should actually set the new value of the property.

### Basic Information

- Version with issue: 2.5.0.122203
- Last known good version: ???
- IDE: Visual Studio for Mac 7.3.3 (build 17)
- Platform Target Frameworks: all
- Android Support Library Version: N/A
- Affected Devices: all

### Screenshots

N/A

### Reproduction Link

Will provide if needed (since every app will show this behavior).

### IDE info
```
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3.3 (build 17)
Installation UUID: 75a3e4df-6d6e-4364-9dac-61e6293ef1f9
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.1.1
	1.1.0
	1.0.5
	1.0.4
	1.0.1
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
	1.0.3
	1.0.0-preview2-1-003177
	1.0.0-preview2-003131
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.4 (Visual Studio Enterprise)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Enterprise)
Android SDK: /Users/sam/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.3 (API level 18)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.216 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030017
Git revision: 88d62dcf15156ff583f785fa668dbf2a254db12e
Build date: 2018-02-09 08:36:16-05
Xamarin addins: 7c8f967d67207118dd99a1d0cc9c228045b30c5f
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Android Signature Tool 2.1.2
Gist Ide Information 1.1.0
MSBuild Editor 2.0.1
NuGet Package Explorer 0.2
NuGet Package Management Extensions 0.12.6
Redth's Addins 1.0.9
Show in Github 1.0.4
Internet of Things (IoT) development (Preview) 7.1
```

**Comment by SamuelDebruyn** [comment]
@rmarinho Looks like you made a typo and accidentally closed this issue instead of #1905

**Comment by softlion** [comment]
Solution: use

```
SetValueCore(BindableProperty property, object value, SetValueFlags attributes = SetValueFlags.None)
```

which is a public method.

**Comment by jfversluis** [comment]
Thanks for the suggestion! It seems it didn't get much traction, sorry about that. We won't be changing this for Xamarin.Forms anymore. If this is something that still interests you and is needed, please let us know for .NET MAUI, thanks!
