### ISSUE TITLE
Scaling broken with current Forms (WidthRequest property)

### ISSUE THREAD

**Issue by nodoid** [xamarin/Xamarin.Forms#1953]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
I am setting a static property which gets the physical screen size from the device. This is then applied to the WidthRequest property of a button. The request is being ignored.

### Steps to Reproduce

1. Download and build the following source https://www.dropbox.com/s/o2m5piotj39kr6t/dynamicsize.zip?dl=0
2. Run on UWP, Android or iOS

### Expected Behavior
The button is correctly scaled (this can equally be an image or any other UI object)

### Actual Behavior
The button appears full screen. A debug point before the Content is set shows the screen size is correctly read

### Basic Information

- Version with issue:
- Last known good version: 2.5.0.122203 (Android/iOS)
- IDE: VS.Mac and VS2017 15.5.7
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 6
  - UWP:  16299

### Reproduction Link

https://www.dropbox.com/s/o2m5piotj39kr6t/dynamicsize.zip?dl=0>

This is bug is also related to #1893 and shows it as a minimal case

**Comment by MelbourneDeveloper** [comment]
This may or may not be related to https://github.com/xamarin/Xamarin.Forms/issues/1965

But, I only started investigating these issues because I have a problem in Android in one App. If there is an ListView on screen in an Auto RowDefinition, on UWP the row shrinks and expands appropriately. But, on Android, the row is always expanded which it shouldn't be. I've tried hard to recreate the bug, but I can't get it to happen outside of our app.

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/36929404-3ef99c80-1e34-11e8-8571-ab33e90a877a.png)

This is what I see on Android. The buttons span the screen width. User expects only the button to span the displayed percentage.

**Comment by nodoid** [comment]
Happens on iOS and UWP as well

**Comment by jassmith** [comment]
This is expected behavior. The default HorizontalOptions is fill. To get the behavior you want you need to specify button.HorizontalOptions = LayoutOptions.Center; (or Start or End).

**Comment by nodoid** [comment]
On UWP at least, setting the HorizontalOptions to start gives incorrect scaling (roughly double what it should be - see that attached screen shot)
![uwpbug](https://user-images.githubusercontent.com/2233242/37033777-fe4db1ae-213e-11e8-9bb0-11a22b214b9e.png)

**Comment by nodoid** [comment]
I can get a similar result on iOS and Android

**Comment by jassmith** [comment]
When I run your app this is because your App.ScreenSize is incorrectly set to 1200 instead of 600 when your layout is calculated and you never recalculate those width requests. When I fix your App.ScreenSize to the correct size I get the correct results.
