### ISSUE TITLE
MenuItem - Icon - Allow any ImageSource

### ISSUE THREAD

**Issue by dazinator** [xamarin/Xamarin.Forms#1955]
When adding a `ToolbarItem` it's `Icon` property has to be a `FileImageSource`. This means I can't use third party image sources that provide, for example, svg support.

Would you consider relaxing the constraint to `ImageSource` so we can use  for example `SvgImageSource` ?

**Comment by MelbourneDeveloper** [comment]
This was a problem for us as well. In fact, we had to bend over backwards to replace the UWP control's XAML template simply for the purpose of adding a non-silhouette image in to the control. And, that's just one platform.

**Comment by samhouts** [comment]
I'm going to close this issue in favor of #3207. Thank you for your feedback!
