### ISSUE TITLE
CornerRadius problem with 2.5.0.280555

### ISSUE THREAD

**Issue by bulente** [xamarin/Xamarin.Forms#1956]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

warning CS0618: 'Button.BorderRadius' is obsolete: 'BorderRadius is obsolete as of 2.5.0. Please use CornerRadius instead.'

### Steps to Reproduce

1. Replace the BorderRadius with CornerRadius in the PCL code

### Expected Behavior
Both iOS and Droid works without problem

### Actual Behavior
iOS works without problem but Droid code gives this error:
`Method 'Xamarin.Forms.Button.set_CornerRadius' not found`

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: - 
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.0
- Android Support Library Version: 26.1.0.1 / 47

**Comment by samhouts** [comment]
I think you might need to do a clean, uninstall from device, and rebuild, redeploy. Also ensure that your Android project was properly updated to the newest version.

**Comment by bulente** [comment]
@samhouts, uninstall from device and rebuild-redeploy solved the problem, thanks.

**Comment by samhouts** [comment]
Awesome! Thanks! :)
