### ISSUE TITLE
Error "opcode" encountered

### ISSUE THREAD

**Issue by prahna** [xamarin/Xamarin.Forms#1957]
### Description
Hey guys, I am trying to do something similar to OnPlatform but for DeviceOrientations. I have seen the implementation of the OnPlatform and decided to do something similar. But unfortunately, when I add the declaration of my new OnOrientation class, I get this "error : opcode" with absolutely no information.
Here is the code that generates the error :
```
<GridLengthTypeConverter x:Key="GridLengthTypeConverter"/>

      <views:OnOrientation x:Key="GridFirstRowHeight" x:TypeArguments="GridLength" ValueConverter="{StaticResource GridLengthTypeConverter}">
        <views:OnOrientation.Orientations>
          <views:OrientationValue Orientation="Landscape" Value="1*"/>
          <views:OrientationValue Orientation="LandscapeFlipped" Value="1*"/>
          <views:OrientationValue Orientation="Portrait" Value="3*"/>
          <views:OrientationValue Orientation="PortraitFlipped" Value="3*"/>
        </views:OnOrientation.Orientations>
      </views:OnOrientation>
```

As soon as I comment out this code, the error disappears.
Anyone encountered the same issue or has any information on how to fix this ?
Thank you all in advance

### Expected Behavior
Not have the error .

### Actual Behavior
Compilation error due to XAML declaration

### Basic Information

- Version with issue: 2.5.0
- Last known good version: -
- IDE: VS2017
- Platform Target Frameworks:
  - iOS:  11
  - Android: 7.0
- Android Support Library Version: v7

### Screenshots
![image](https://user-images.githubusercontent.com/1527444/36548431-478ac9ea-17be-11e8-9384-04b9e8f285af.png)

**Comment by samhouts** [comment]
How did you implement `OnOrientation`? Did you set up a `TypeConverter`? Can you share your code? Thanks

**Comment by prahna** [comment]
Hi, this is the implementation of the OnOrientation class.

`

    [ContentProperty("Value")]
    public class OrientationValue
    {
        public DeviceOrientations Orientation { get; set; }

        public object Value { get; set; }
    }

    [ContentProperty("Orientations")]
    public class OnOrientation<T>
    {
        public IValueConverter ValueConverter { get; set; }

        public T Portrait { get; set; }

        public T Landscape { get; set; }

        public OnOrientation()
        {
            Orientations = new List<OrientationValue>();
        }

        public List<OrientationValue> Orientations { get; set; }
        public static implicit operator T(OnOrientation<T> onOrientation)
        {
            var service = DependencyService.Get<IDeviceOrientationService>();
            var currentOrientation = service.CurrentOrientation;
            foreach (var orientationValue in onOrientation.Orientations)
            {
                if (orientationValue.Orientation == currentOrientation)
                {
                    if (onOrientation.ValueConverter != null)
                    {
                        return (T)onOrientation.ValueConverter.Convert(orientationValue.Value, typeof(T), null,
                            CultureInfo.CurrentCulture);
                    }

                    return (T) orientationValue.Value;
                }
            }

            if (onOrientation.Landscape != null && 
                currentOrientation == DeviceOrientations.Landscape)
                return onOrientation.Landscape;

            if (onOrientation.Portrait != null &&
                currentOrientation == DeviceOrientations.Portrait)
                return onOrientation.Portrait;

            return default(T);
        }

`

**Comment by StephaneDelcroix** [comment]
I tried to reproduce your issue on both 2.5 and our nightly, and the Xaml (or whatever I was able to extrapole from your snippets) compiles just fine.

please come up with the smallest piece of reproducible test case, and reopen the ticket.
