### ISSUE TITLE
Crashes by shrinking page using FlexLayout on macOS

### ISSUE THREAD

**Issue by yamachu** [xamarin/Xamarin.Forms#1959]
### Description

Crash when FlexLayout that does not meet height criteria appears.

### Steps to Reproduce

1. Generate ContentPage using FlexLayout that direction is column
2. Set one or more FlexLayout set property Basis
3. Shrink main window until its height close to 0
4. It will throw `System.ArgumentException`

### Expected Behavior

Handle this exception

### Actual Behavior

Throw exception and crash

### Basic Information

- Version with issue: 2.6.0.211236-nightly
- IDE: Visual Studio for Mac 7.4 build 985
- Platform Target Frameworks: 
  - Mac: 4.2.0.19

### Reproduction Link

https://github.com/yamachu/ReproFlexLayoutShrink

**Comment by StephaneDelcroix** [comment]
fixed by #2010
