### ISSUE TITLE
ListView - No Indication When DataTemplate Error Occurred

### ISSUE THREAD

**Issue by MelbourneDeveloper** [xamarin/Xamarin.Forms#1966]
### Description
When XAML is rendered dynamically inside controls like ListView with a DataTemplate, there is often no visual indication that the parsing/rendering has failed. Moreover, if the element doesn't end up getting rendered, it can cause the app to crash. Also, clicking on a ListView item that did not correctly render will crash the app. This is a problem with ListView, but probably happens with several controls that implement DataTemplate based item creation.

### Steps to Reproduce
1. Clone this repo https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git
2. Run the UWP sample
3. Click ListView DataTemplates
4. Notice that in the top left where the ListView should be, there is nothing
5. Hover over the ListView in the top left. Notice that the items **ARE** highlighted as you move over them
6. Click on an item -> App Crash

To Fix:
1.  Open the page ListViewDataTemplateIssuePage.xaml. 
2.  Delete the text AbsoluteLayout.LayoutBounds="ASDFSDF@#$#$@#$"
3. Recompile and run test. 
4. Notice that the ListView now works fine.

### Expected Behavior
Give the user some indication that the ListView's items didn't render correctly. Perhaps making the control glow red or something. And, the app doesn't crash when you click on an item.

### Actual Behavior
The area of the screen where the ListView exists goes blank, and the app crashes when you click on an item.

### Basic Information
- Version with issue: 2.5.0.280555
- Last known good version:
- IDE: VS
- Platform Target Frameworks: 
  - UWP:  16299 
  - Probably all platforms
- Nuget Packages: Xamarin.Forms 
- Affected Devices:

### Screenshots
[ListView](https://www.dropbox.com/s/xi3905g18eh3k5v/ListViewIssue.png?dl=0)

### Reproduction Link
https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git

**Comment by MelbourneDeveloper** [comment]
A note on this...

The XAML parser is not parsing deep enough in to DataTemplates to validate the XAML. I guess this is being done for performance reasons. I suppose that's warranted. But, it might be worth weighing up the performance cost of further scanning in to DataTemplate content to see if the XAML is valid. Just a thought.

**Comment by MelbourneDeveloper** [comment]
@pauldipietro , @samhouts @davidortinau 

Is this issue going to get some attention?

I've spoken to David at length about these kinds of issues. It affects our team a lot more than it affects other teams, and I'll explain why. Most of time, people design screens inside Visual Studio with XAMLC, or by programmatically building the visual tree. With XAMLC turned on, I think this error gets caught at compile time. However, our XAML is stored as text inside the database so that it can be configured by the configuration team. Our UI is 100% customisable. So, when the configuration person hits the "Render" button, it looks like everything checks out fine. But, when they open the screen with the ListView, the screen just goes blank and nothing happens. Even though there was invalid XAML attached to the control, the configuration person can't see what went wrong.

Just yesterday, I spent hours trying to get a ListView formatted correctly because I had some bad XAML in the ItemTemplate, but couldn't figure out what it was because when the XAML was rendered, there was no error message, or anything to let me know what was going wrong.

One potential way of dealing with this problem is to include a BindableProperty called "ItemTemplateXAMLError" or something along those lines so that another control can bind to the errors that occur. This isn't great, but it would be better than nothing. It still means that if something goes wrong, the configuration person needs to put another control on the screen and bind to the error property.

Recently, a pull request was accepted in to the XF codebase which allows for dynamic rendering of XAML. As more people start using this, they are going to have the same kinds of issues.

**Comment by samhouts** [comment]
@MelbourneDeveloper This is great feedback, and we're definitely taking it into consideration. We are looking at our DataTemplates as a whole in an effort to make the process of building ListViews easier and more intuitive, and this feedback is a critical discussion point. I'm afraid I don't have any timelines to give you, but it is on our radar. Thank you!

**Comment by MelbourneDeveloper** [comment]
@samhouts , Thanks. I guess I should point out that DataTemplates are not only used in ListViews etc. We use DataTemplates extensively for different kinds of configurable functionality. Whatever the outcomes are for this issue, it should be something that can be applied across the board to all controls that use DataTemplates.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
