### ISSUE TITLE
[Enhancement] More error information from XAMLC when missing OnPlatform tag

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#1978]
### Description

If I'm using the `OnPlatform` feature in XAML and forget the <OnPlatform> tag, the XAMLC error message is not very helpful in diagnosing the problem. For example if I do the following:

```
<ToolbarItem Clicked="OnItemAdded">
	<ToolbarItem.Text>
		<!--Forgot the OnPlatform tag-->
			<On Platform="Android,iOS" Value="+" />
			<On Platform="UWP" Value="Add" />
	</ToolbarItem.Text>
</ToolbarItem>
```

The error from XAMLC is just `Sequence contains no elements`. In XAMLG, the runtime error includes XmlLineInfo, which gives me a clue where to start looking for the problem.

### Steps to Reproduce

1. Create a ContentPage with `[XamlCompilation(XamlCompilationOptions.Compile)]`
2. In `<ContentPage.ToolbarItems>`, add the above XAML.
3.  Build.

### Expected Behavior

The line/character information provided by XAMLG when encountering this error. Even better if the error could provide the name of the file where the error occurs.

### Actual Behavior

`Sequence contains no elements`

**Comment by StephaneDelcroix** [comment]
FYI: XamlG is not the tool used at runtime. XamlG is the generator for the partial code behind class
