### ISSUE TITLE
typo issue: string and property name is not same

### ISSUE THREAD

**Issue by akgulebubekir** [xamarin/Xamarin.Forms#1983]
it shold be "ClassStyles"

https://github.com/xamarin/Xamarin.Forms/blob/185d1ce6adb83dd652552afbca337186a80f2a03/Xamarin.Forms.Core/MergedStyle.cs#L59

**Comment by StephaneDelcroix** [comment]
in this case, it could be "foo" that it wouldn't change a think. that property is only used internally and so the name doesn't matters
