### ISSUE TITLE
TapGestureRecognizer not fire for items inside cells when list appears

### ISSUE THREAD

**Issue by simyco** [xamarin/Xamarin.Forms#1986]
### Description
TapGestureRecognizer not fire in Android devices after list appears, if i scroll the list and tap the area the gesture will fire, in iOS everything works fine
### Steps to Reproduce
I've a code like this:

```
 <ViewCell.View>
<Grid BackgroundColor="White">
    <Grid.Padding>
        <OnPlatform x:TypeArguments="Thickness" iOS="0,0,0,0" Android="0,0,0,0" WinPhone="10,5,10,5" />
    </Grid.Padding>
    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="50" />
        <ColumnDefinition Width="*" />
        <ColumnDefinition Width="50" />
    </Grid.ColumnDefinitions>
    <Image Margin="10,0,0,0" Source="{Binding Converter={StaticResource DocumentImageConverter}}" Grid.Column="0" />
    <Grid Grid.Column="1" Padding="16,8,16,8">
        <StackLayout VerticalOptions="CenterAndExpand" HeightRequest="60">
            <Label Margin="0,0,0,0" Text="{Binding Nome}" Grid.Row="0" Style="{StaticResource TextDocumentCell}" />
            <Label Margin="0,0,0,0" Text="{Binding Converter={StaticResource DocumentDescriptionConverter}}" Grid.Row="1" Style="{StaticResource SubDocumentTextStyle}" />
        </StackLayout>
    </Grid>
    <Grid Grid.Column="2" Margin="0,2,0,2" Padding="0,5" IsVisible="{Binding Formato, Converter={StaticResource DocumentActionConverter}}">
        <Image Source="ic_more" HorizontalOptions="CenterAndExpand"></Image>
        <Grid.GestureRecognizers>
            <TapGestureRecognizer Command="{Binding Path=BindingContext.OnActionDocumentCommand, Source={x:Reference Name=Documenti}}" CommandParameter="{Binding .}" />
        </Grid.GestureRecognizers>
    </Grid>
</Grid>
</ViewCell.View>
```

### Expected Behavior
The gesture fires when item tapped
### Actual Behavior
Nothing happens when item tapped
### Basic Information

- Version with issue: 2.5.0.280555
- IDE: Visual studio for Mac
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 26.0.2

**Comment by kingces95** [comment]
Please attach the full reproduction solution.

**Comment by syed-pelican** [comment]
We have the same issue in our app, structure is as follows:

```XAML
<ListView
            x:Name="FeedList"
            Margin="0,1,0,0"
            ItemsSource="{Binding FeedItems}"
            ItemTemplate="{StaticResource feedDataTemplateSelector}"
            HasUnevenRows="true"
            BackgroundColor="{StaticResource ContentBackgroundColor}"
            SeparatorVisibility="None"
            IsVisible="{Binding ShowPage}"
            ex:ListViewExtensions.DisableRowHighlight="true"
            IsPullToRefreshEnabled="{StaticResource IsPullToRefreshEnabled}"
            RefreshCommand="{Binding PullToRefreshCommand}"
            IsRefreshing="{Binding IsPullToRefreshActive}"
            CachingStrategy="RecycleElement">
            <ListView.Behaviors>
                <b:EventToCommandBehavior
                    EventName="ItemAppearing"
                    Command="{Binding ItemAppearingCommand}" />
                <b:EventToCommandBehavior
                    EventName="ItemDisappearing"
                    Command="{Binding ItemDisappearingCommand}" />
            </ListView.Behaviors>
</ListView>
```
But curiously, disabling **IsPullToRefreshEnabled**  on Android helps and first item registers the gesture. On iOS it behaves the usual way. I'd really like to package the solution and send it up for repo but its a production app and can't upload the solution.

**Comment by adrianknight89** [comment]
Seeing this issue on both platforms actually

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
