### ISSUE TITLE
[macOS] Entry does not accept common key commands

### ISSUE THREAD

**Issue by jvansickle-cei** [xamarin/Xamarin.Forms#1988]
### Description

Entry elements do not accept standard text entry key combinations such as ⌘a, ⌘c, and ⌘v.

### Steps to Reproduce

1. Add Entry to a xaml layout
2. Click into Entry
3. Attempt copy, paste, select all key combinations

### Expected Behavior

Standard key combinations out of the box

### Actual Behavior

No standard key combinations

### Basic Information

- Version with issue: 2.4.0.280
- Last known good version: None
- IDE: Visual Studio for Mac Enterprise (7.3.3 build 23)
- Platform Target Frameworks: 
  - macOS:  10.13
- Android Support Library Version: N/A
- Nuget Packages: 
- Affected Devices: MacBook Pro (Retina, 15-inch, Mid 2015)
 
### Screenshots

None

**Comment by jvansickle** [comment]
I believe I have a suitable solution for this enhancement. I will be opening a PR directly.

**Comment by jvansickle** [comment]
I canceled PR #3202 because I discovered you can keep the storyboard-described application menu alive by setting the Menu bindable property of your Application implementation. See the PR comments for further detail. @samhouts could you mark this closed?

**Comment by samhouts** [comment]
Sure, thank you!
