### ISSUE TITLE
IOS NFC Library support (reading tags)

### ISSUE THREAD

**Issue by soryncrash13** [xamarin/Xamarin.Forms#1993]
Are you going to introduce some library/ies to support NFC for ios? The reading-event only is enough, so you can create an app for windows, android and ios(only reading here).

**Comment by fredeil** [comment]
Do you mean like https://developer.xamarin.com/guides/ios/platform_features/introduction-to-ios11/corenfc/ @soryncrash13 ?

**Comment by jassmith** [comment]
This isn't a Xamarin.Forms issue. Also iOS has NFC libraries as fredeil pointed out.

**Comment by soryncrash13** [comment]
i've seen that core nfc library for ios, but am I able to make a xamarin.forms app for both android and ios (using PCL project type, not shared project)? On ios I know I can only perform reading actions and that's more than enough, but on android I want to make it possible both reading and writing tags. Thanks a lot guys! :smiley:
