### ISSUE TITLE
[iOS] Shadow platform effect is only being applied when you set a background color for a box view

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2003]
### Description
https://github.com/xamarin/Xamarin.Forms/pull/1896

Given two box views
```c#
    <StackLayout>
        <BoxView x:Name="boxViewWithBackground" BackgroundColor="White"></BoxView>
        <BoxView x:Name="boxViewWithoutBackground"></BoxView>
    </StackLayout>
```

```c#
public MainPage()
	{
			InitializeComponent();
            TheShadowRemainsCast(boxViewWithBackground);
            TheShadowRemainsCast(boxViewWithoutBackground);
        }

        private void TheShadowRemainsCast(BoxView boxView)
        {
            boxView.On<iOS>().SetShadowColor(Color.Gray);
            boxView.On<iOS>().SetShadowRadius(3);
            boxView.On<iOS>().SetShadowOffset(new Size(2, 2));
            boxView.On<iOS>().SetShadowOpacity(0.8);
            boxView.On<iOS>().SetIsShadowEnabled(true);
        }
```

Only the box view with the background set to white will show a shadow

### Steps to Reproduce

 
[BoxViewShadow.zip](https://github.com/xamarin/Xamarin.Forms/files/1773296/BoxViewShadow.zip)

### Expected Behavior

Both box views should show a shadow effect

### Actual Behavior

Currently only the box view with the background color set to white shows the shadow effect

### Basic Information

- Version with issue:2.6.0.233087-nightly

**Comment by jassmith** [comment]
Im not sure we can do much about this, iOS computes the opacity of the target when computing shadows. Transparent things dont really cast shadows much...

**Comment by PureWeen** [comment]
Good point
I saw you could draw a path
```
layer.ShadowPath = UIBezierPath.FromRect(layer.Bounds).CGPath;
```
but you might want to cast shadows on things inside the container so probably too opinionated to do something like that
