### ISSUE TITLE
[Enhancement] ReferenceExtension exception message

### ISSUE THREAD

**Issue by lacerdaeduardo** [xamarin/Xamarin.Forms#2007]
## Summary
Provide an enhancement in ReferenceExtension Exception message.

In order to facilitate troubleshooting when referencing elements in XAML pages, the exception message at ReferenceExtension "Can't resolve name on Element" must be improved to the following:

`throw new Exception($"Can't resolve name on Element {Name}");`

This way, when this exception is throwed at runtime, the developer can find the wrong element name in seconds.

## Intended Use Case
Create a new Entry referencing another one that doenst exists at the same XAML page, e.g: 

```
  <Entry x:Name="txtConfirmNewPassword" IsPassword="True" Placeholder="{i18n:Translate Text=txt_confirm_password}"
                       Text="{Binding ConfirmNewPassword}"
                       v:Validation.Validator="{v:CompareEntryValidator CompareValue={Binding Source={x:Reference txtNewPassword}, Path=Text}, ErrorLabel={**Reference** PasswordsDontMatch}, ErrorColor=Red}"/>

```

**Comment by StephaneDelcroix** [comment]
the exception should also be a XamlParseException, and report the line and column info
