### ISSUE TITLE
Application crashes when executing a parse statement in PCL

### ISSUE THREAD

**Issue by nesh746** [xamarin/Xamarin.Forms#2008]
Consider the following statement somewhere in PCL project:

double val = double.Parse("0.1233");

This statement successfully executes in all Android physical devices (Tried different OS versions). The same statement also gets executed successfully on many of iPhone and iPad physical devices. However this statement is making the app to crash for a particular iOS device for me when it works fine in all other phones and tablets.

### Steps to Reproduce

1. Create a sample xamarin.forms project and add that parse statement mentioned as above in PCL which should get executed when the app is run.
2. Run the application.
3. Observe the application.

### Expected Behavior

The statement should get executed without causing any error.

### Actual Behavior

statement is making the app to crash for a particular iOS device only.

### Basic Information

- Version with issue: latest stable xamarin forms nuget package
  - iOS:  SDK version 10.2 is used to compile the code.

- Affected Devices:

iPhone X with iOS version 11.1.2

**Comment by StephaneDelcroix** [comment]
I guess you have a `Culture` problem here, and that particular phone is running with a local in which the decimal separator is ',' instead of '.'

**Comment by nesh746** [comment]
@StephaneDelcroix  How do I fix the issue?

**Comment by hartez** [comment]
@nesh746 On the device you are having problems with, what do you have set for the Language and Region (in Settings -> General)?

**Comment by StephaneDelcroix** [comment]
or Parse with InvariantCulture

**Comment by nesh746** [comment]
@hartez 
I have checked on the device, the language is English and Region is South Africa

**Comment by hartez** [comment]
@nesh746 If you want to parse independent of the current culture (i.e., if you want to always assume "0.1233" rather than "0,1233"), then you should use InvariantCulture as Stephane suggests.

`double val = double.Parse("0.1233", CultureInfo.InvariantCulture);`
