### ISSUE TITLE
Intellisense pop-up documentation not displayed for Forms API

### ISSUE THREAD

**Issue by tanmay-bhattacharjee** [xamarin/Xamarin.Forms#2013]
Intellisense pop-up documentation not displayed for Forms API

Steps:
1. Create a forms solution.
2. Build solution.
3. Open any .xaml file and type <lab... 
4. Once intellisense is seen, find that the api doc is not visible.

Expected Result:
Intellisense api doc should be displayed.

Actual Result:
Api documentation not displayed on intellisense selection.

Build Info:
 - Microsoft Visual Studio Enterprise 2017 Preview
 - Version 15.6.0 Preview 6.0
 - VisualStudio.15.Preview/15.6.0-pre.6.0+27421.1
 - Microsoft .NET FrameworkVersion 4.7.02556
 - Xamarin 4.9.0.749 (9b0fce36d)
 - Xamarin Designer 4.10.58 (cee1369d0)
 - Xamarin.Android SDK 8.2.0.15 (HEAD/22d97e153)
 - Xamarin.iOS and Xamarin.Mac SDK 11.8.0.20 (1c6f300)
 
Build Gist:
https://gist.github.com/parasAmbhore/a70ae9b16237b2fb719c713e61c1939d

Test Case Link:
https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/tests/view/22878971&group_by=cases:section_id&group_order=asc&group_id=537940

Test Suit Link:
https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/plans/view/54475

Reproducible:
100% [Happens Everytime]

ScreenCast Link:
https://www.screencast.com/t/2ZZOA1YGPESm

Attaching IDE logs for reference.
[API_Issue_Zip_Logs.zip](https://github.com/xamarin/Xamarin.Forms/files/1781017/API_Issue_Zip_Logs.zip)

**Comment by hartez** [comment]
@tanmay-bhattacharjee As far as I know, Visual Studio Intellisense never displays the API summary information for XAML. Some third-party plugins (e.g., Resharper) support that.
