### ISSUE TITLE
DependencyService does not gets registered if called by xamarin.forms project before registering

### ISSUE THREAD

**Issue by rags217** [xamarin/Xamarin.Forms#2014]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

When DependencyService is registered before PLC project calls for the method, it works well. However if it is called before the native project registers the method, Register method in Dependency service never works again

Steps to Reproduce

1. Create the dependency object for an interface in PLC project 
2. Verify it returns null
3. Register native class for its corresponding class
4. Re-create the dependency object for an interface in PLC project

### Expected Behavior
It is not supposed to be null. it should return platform specific implementation object

### Actual Behavior
It returns null

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: Xamarin Studio for Mac
- Platform Target Frameworks: 
  - Android: 8.0
  - Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices: Samsung galaxy, LG variants

### Screenshots

Crash

### Reproduction Link

Unable to reproduce everytime

**Comment by hartez** [comment]
@rags217 Could you provide a minimal reproduction project that demonstrates the issue? Or show us the code you are using to register the service and the code you are using to access the interface in the PCL project?

**Comment by rags217** [comment]
Please find a sample project in the below link:

https://github.com/rags217/DSTest

Instructions to reproduce:

1. click set dependency1 button -> message displayed: dependency1 is set
2. click call dependency2 button -> message displayed: dependency1 is called
3. That works fine
4. now try in the reverse order for second dependency
5. click call dependency2 button -> message displayed: dependency2 is null
6. click set dependency1 button -> message displayed: dependency2 is set
7. click call dependency2 button **AGAIN**-> message displayed: dependency2 is null

**Result : Step 7 is expected to return a valid object of second dependency class while it continues to return null.**

Bottomline, if by any means a DepencyService is called before the class is registered, it will never return a valid object even if the registration happens later on. That results in unexpected behaviour on handsets that take some time to load native components.

**Comment by rags217** [comment]
This can be closed as I have created another issue with full information while this was in closed state.

https://github.com/xamarin/Xamarin.Forms/issues/2445
