### ISSUE TITLE
Interacting With a CustomButtonRenderer That Contains A UIDatePicker Disables All TimePickers

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/Xamarin.Forms#2015]
_From @Edward472 on March 2, 2018 20:29_

### Steps to Reproduce

1. Have a Custom Button that is rendered using a CustomButtonRenderer which contains a UIDatePicker
2. Place the CustomButton on a view with a TimePicker
3. Click on the TimePicker 
4. TimePicker allows changes and selections
5. Click on the Custom Button
6. Go back and click the Timepicker

We have also reproduced this behavior with the timepicker and custom button on seperate views. As long as you render the custom button and click on it, all resulting timepickers in any subsequent view will behave this way. Small sample project attached.

### Expected Behavior
TimePicker should allow for changes

### Actual Behavior
TimePicker allows for scrolling of hour/minute/seconds but wheels are grey and do not retain any selection. After scrolling the time wheels go back to whatever the initial value of the picker was. The only way to get the time pickers back to normal is to close and reopen the app.

### Environment
Reproduced in IOS Simulator on Mac running Sierra
Reproduced on Physical IPad Air 

```=== Visual Studio Community 2017 for Mac ===

Version 7.3.3 (build 23)
Installation UUID: 1ed947ba-f8fc-4cd4-bb73-34f5183f47e9
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

'/Applications/Xamarin Profiler.app' not found

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.4 (Visual Studio Community)
Hash: db807ec9
Branch: xcode9.2
Build date: 2018-01-10 16:45:48-0500

=== Xamarin.Android ===

Version: 8.1.5.0 (Visual Studio Community)
Android SDK: /Users/csci/Library/Android/sdk
	Supported Android versions:
		7.0 (API level 24)

SDK Tools Version: 25.1.7
SDK Platform Tools Version: 24.0.2
SDK Build Tools Version: 24.0.2

Java SDK: /usr
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 4.0.0.216 (Visual Studio Community)

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 703030023
Git revision: e02ab111d8181ffe766c2258141282c88188ebb6
Build date: 2018-02-20 08:06:38-05
Xamarin addins: 5ce2b6790676a4542aa0d69d07f6a716e17d4e65
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jan 11 22:59:40 PST 2018
    root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

NuGet Package Management Extensions 0.12.5
xUnit.NET 2 testing framework support 0.7.5
Redth's Addins 1.0.9
Gorilla Player 1.0.0.5
Internet of Things (IoT) development (Preview) 7.1
```

### Example Project (If Possible)

[TimePickerRendererTest.zip](https://github.com/xamarin/xamarin-macios/files/1776480/TimePickerRendererTest.zip)

_Copied from original issue: xamarin/xamarin-macios#3652_

**Comment by mandel-macaque** [comment]
This looks like a xamarin-forms issue. Will move it there for them to triage.

**Comment by hartez** [comment]
Using the attached project, you don't have to touch the custom button to induce the broken behavior; apparently creating a new UIDatePicker in the buton renderer's OnElementChanged is enough.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
