### ISSUE TITLE
XF 2.5 build failed targeting Xamarin.Android 7.0 or 6.0

### ISSUE THREAD

**Issue by 5yunus2efendi** [xamarin/Xamarin.Forms#2016]
### Description
I want to create an app using XF 2.5 with Xamarin.Android 7.0, but it says build failed with the following error:

![capture](https://user-images.githubusercontent.com/19399214/36990233-9bd4b0d0-20d6-11e8-9322-55f39a3e6d9f.PNG)

So the only workaround right now is to target Xamarin.Android 7.1 or above.

### Steps to Reproduce

1. Create Xamarin.Forms project
2. Add XF 2.5 on NuGet
3. Build the project

### Expected Behavior
Build success and I can run the app

### Actual Behavior
Shows "Build error"

**Comment by hartez** [comment]
@5yunus2efendi Which build of the 2.5 NuGet package are you using (e.g., 2.5.0.122203, 2.5.0.280555)?

In your Android project settings, on the Application tab, what is selected for "Compile using Android version: (Target Framework)"? And on the Android Manifest tab, what is selected for "Minimum Android version" and "Target Android version"?

**Comment by 5yunus2efendi** [comment]
XF version: 2.5.1.317207-pre1
Compile using Android version: (Target Framework): Android 7.0 or Android 6.0 (both has the same issue)
Minimum Android version: Android 4.0.3 (API Level 15)
Target Android version: Use Compile using SDK version

**Comment by rmarinho** [comment]
this is a issue restoring packages and the target version was still Android 6.0 and there's no Support for fragments there. Solutions is update your androdi csproj to 7.0. and then install Xamarin.Forms

**Comment by hartez** [comment]
@5yunus2efendi 2.5 is not compatible with Android 6. Android 7 should work fine. If you're seeing this issue while targeting 7, you may need to completely remove the Forms packages, restart Visual Studio, and re-add the Forms packages.

I apologize, we realize it's not the best update experience. There is some work in progress to make the [feedback during the NuGet update process more helpful](https://github.com/NuGet/Home/issues/4051) and to make the package manager UI better about [indicating which packages are compatible with your project](https://github.com/NuGet/Home/issues/5725).

**Comment by 5yunus2efendi** [comment]
I am sorry, I forgot to mention that I changed Xamarin.Android.Support to 23.3.0 because XF 2.5 for Xamarin.Android 6 or 7 has minimum dependencies Xamarin.Android.Support 23.3.0, note that I need Xamarin.Android.Support 23.3.0 is because when the app released, the size of it's app is relatively small than Xamarin.Android.Support 24 or above, I also have an app that target 2.4.* and it's size is relatively small

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/1794823/App2.zip)

**Comment by pauldipietro** [comment]
On a cursory look over, it appears the project shows the build error in question when trying to build.

**Comment by 5yunus2efendi** [comment]
Any update on this?

**Comment by 5yunus2efendi** [comment]
I'll close this one
