### ISSUE TITLE
BindingContext object not being passed thru CommandParameter

### ISSUE THREAD

**Issue by insearchof1230** [xamarin/Xamarin.Forms#2019]
### Description
ViewCell BindingContext object is not being passed thru the CommandParameter property to viewModel (Prism.Forms). All signs point to the BindingContext being the issue, not the CommandParameter.

XAML Snippet:
```
<ListView x:Name="List" Grid.Row="0" ItemsSource="{Binding AttachmentTypeSet.Items}">
 <ListView.ItemTemplate>
  <DataTemplate>
   <ViewCell>
    <StackLayout x:Name="Item" Padding="15,0">
     <Grid>
      <Grid.ColumnDefinitions>
       <ColumnDefinition Width="8*" />
       <ColumnDefinition Width="1*" />
       <ColumnDefinition Width="1*" />
      </Grid.ColumnDefinitions>
      <Label Grid.Row="0" Grid.Column="0" Text="{Binding Message}" VerticalOptions="Center" />
      <Button BindingContext="{Binding Source={x:Reference List}, Path=BindingContext}" Command="{Binding Camera}" **CommandParameter="{Binding Source={x:Reference Item}, Path=BindingContext}"** Grid.Row="0" Grid.Column="1" Text="Cam" TextColor="#0098d1" HorizontalOptions="End" />
      <Button BindingContext="{Binding Source={x:Reference List}, Path=BindingContext}" Command="{Binding Library}" **CommandParameter="{Binding Source={x:Reference Item}, Path=BindingContext}"** Grid.Row="0" Grid.Column="2" Text="Lib" TextColor="#0098d1" HorizontalOptions="End" />
     </Grid>
    </StackLayout>
   </ViewCell>
  </DataTemplate>
 </ListView.ItemTemplate>
</ListView>
```

ViewModel Snippet:
```
_camera = new DelegateCommand<FAMLookupItem>(**u** => TakePicture(FileSource.Camera, (AttachmentTypeViewModel)u.Obj));
_library = new DelegateCommand<FAMLookupItem>(**u** => TakePicture(FileSource.Picker, (AttachmentTypeViewModel)u.Obj));
```

### Steps to Reproduce

1. Create a ListView. 
2. Create a button within the ViewCell.
3. Set a bindingContext to the button for the ListView rows object.
4. Click the button

### Expected Behavior
CommandParameter passed into ViewModel should not be NULL.

### Actual Behavior
CommandParameter passed into ViewModel IS NULL.

### Basic Information

- Version with issue: 2.5.1.317207-pre1
- Last known good version: 2.5.0.280555
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  11.2 
  - Android: didn't try
  - UWP:  didn't try
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms.2.5.1.317207-pre1.nupkg
- Affected Devices:

### Screenshots
N/A

### Reproduction Link
Will create one if requested.

**Comment by insearchof1230** [comment]
Oops, clicked the wrong button trying to close a comment I actually wanted to just “discard”.

**Comment by Szymaniuk** [comment]
Most probably, that I faced exact same issue.
Last good version for iOS - 2.5.0.280555
Issue occurs for iOS at - 2.5.1.317207-pre1

For Android, it's working correctly at 2.5.0.280555 as well as at 2.5.1.317207-pre1

However I'm doing something else, but strictly related to this issue description - https://forums.xamarin.com/discussion/comment/283081/#Comment_283081

I'll try to reproduce it on smaller repo and try to attach repo.

**Comment by StephaneDelcroix** [comment]
behavior probably changed when margin #983.

you probably can get around this by writing your bindings this way. to also makes more sense...
```
<Button Command="{Binding BindingContext.Camera, Source={x:Reference List}}" CommandParameter="{Binding}" Grid.Row="0" Grid.Column="1" Text="Cam" TextColor="#0098d1" HorizontalOptions="End" />
```

**Comment by insearchof1230** [comment]
@StephaneDelcroix After your suggestion, it seems to be working as expected.
