### ISSUE TITLE
[CSS] Allow `class` as a shorthand for `StyleClass`

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#2022]
Some might find it intuitive to write
```xml
<Label x:Name="foo" class="description" Text="Bar" />
```

instead of
```xml
<Label x:Name="foo" StyleClass="description" Text="Bar" />
```

To avoid additional confusion and risks, `class` should be a passthrough property to `StyleClass` on `VisualElement`. While we're at it, why not deprecate `StyleClass` ?

## Risks
 - confusion possible with `x:Class` in XAML,
 - confusion with `class` in code, requiring to escape it `@class`,
 - a property starting with a lowercase,
 - possibility to set both, and get inconsistent results

**Comment by jassmith** [comment]
Agreed, we must deprecate StyleClass to at least attempt to limit the amount of codebases with split usage.

**Comment by migueldeicaza** [comment]
No we should not deprecate - this is a convenience alias.   Please update.

**Comment by StephaneDelcroix** [comment]
fixed
