### ISSUE TITLE
Adding launch image using LaunchScreen.storyboard in xamarin.ios not working for all devices.

### ISSUE THREAD

**Issue by nawnit** [xamarin/Xamarin.Forms#2024]
I am working on Xamarin.ios and using visual studio for development. I have added LaunchScreen.Storyboard for displaying launch image as I want to target new iPhoneX device as well. Problem that I am facing issue the splash screen image is not reflecting in all devices.

I cannot use LaunchImage.launchimage assets image approach as there is no placeholder available for iPhoneX for adding image in Visual studio for mac .

I have tried adding images in Images.xcassets folder and accessing it in storyboard. However, its just displays blank screen.

Also tried editing contents.json for adding iphoneX launch image, still no success.

I have tried different images for different resolution added in resource folder but still getting same issue its not coming.

**Comment by hartez** [comment]
@nawnit Which version of Visual Studio for Mac are you running?

**Comment by nawnit** [comment]
@hartez I am using 7.3.3(build 23)

**Comment by nawnit** [comment]
@hartez Thanks, I have updated the visual studio for mac its available for iPhone X. now Its working for me.

**Comment by hartez** [comment]
@nawnit Glad to hear it's working!
