### ISSUE TITLE
no jump list shown in a grouped ListView on UWP

### ISSUE THREAD

**Issue by FrankChen021** [xamarin/Xamarin.Forms#2028]
### Description

on UWP,  a jump list is supposed to show after clicking the group header in a `ListView `control. But, **if the contentpage where the listview is located is nested in a `TabbedPage` or `MasterDetailPage `**, clicking the group header shows no jump list and the content of listview also disappears.

### Steps to Reproduce

1.  open the groupingSampleListView project in the official sample project (https://github.com/xamarin/xamarin-forms-samples.git) 

2.   add a  `TabbedPage`  which contains two pages to the project. the two tabs uses the 'GroupListXaml' page which contains a group list view provided in the sample.

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="groupingSampleListView.Views.TabbedPage1"
             xmlns:pages="clr-namespace:GroupingSampleListView">
    <NavigationPage Title="JumpListDoesNotWorkWell">
        <x:Arguments>
            <pages:GroupedListXaml/>
        </x:Arguments>
    </NavigationPage>

    <pages:GroupedListXaml Title="JumpListWorksWell" />
</TabbedPage>
```

3.  change the code in default ctor of App to initialize the MainPage to the TabbedPage we added above

```
namespace GroupingSampleListView
{
	public class App : Application
	{
		public App ()
		{
                    MainPage = new NavigationPage(new TabbedPage1()));
		}

        ....
}
```

4.  launch the UWP project

### Expected Behavior

both the jump lists of two list views in two tab pages should work well. the list views show as 
![image](https://user-images.githubusercontent.com/6525742/37045615-55797be0-21a1-11e8-89f3-dae220a7c905.png)

and after clicking the group header( v or f ), there should be a jump list shown as below
![image](https://user-images.githubusercontent.com/6525742/37045636-604443b6-21a1-11e8-8ec9-d49310b483c0.png)

### Actual Behavior
the jump list of the first list view does not work well. **after you click the group header, all the content of the list view disappears without showing the jump list.**

the jump list of the second list view works well

if the page which contains a list view is nested in a a master-detail page(either master page or detail page), whether the page is in the master page or the detail page, the jump list does NOT work well. here is an example.

```
<?xml version="1.0" encoding="utf-8" ?>
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="GroupingSampleListView.MasterDetailPage1"
             xmlns:pages="clr-namespace:GroupingSampleListView">
  <MasterDetailPage.Master>
    <pages:GroupedListXaml Title="DoesNOTWorkWellInMaster" />
  </MasterDetailPage.Master>
  <MasterDetailPage.Detail>
    <pages:GroupedListXaml Title="DoesNOTWorkWellInDetail" />
  </MasterDetailPage.Detail>
</MasterDetailPage>
```

### Basic Information

- Version with issue:  Xamarin Form 2.4.0.282, Xamarin Form 2.5.0.280555
- IDE:
- Platform Target Frameworks: .NET Framework 4.5
  - UWP:  16299
  - Windows OS: Win10 Pro Insider Preview Build 17074_prerelease_flt.180116-1539

**Comment by hartez** [comment]
@FrankChen021 I've tried to reproduce the issue but so far I have not been able to - the jump lists in both tabs seem to work fine.

I'm attaching my repro project attempt - can you tell me if I'm missing anything? 

[groupingSampleListView.zip](https://github.com/xamarin/Xamarin.Forms/files/1791034/groupingSampleListView.zip)

**Comment by jassmith** [comment]
OnAppearing continues to be a horrible place to do things :/

Wonder what UWP dislikes here.

**Comment by hartez** [comment]
@FrankChen021 Thanks, the updated project definitely displays the behavior.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
