### ISSUE TITLE
ItemsSource CollectionChanged (Reset) Clears Picker SelectedItem

### ISSUE THREAD

**Issue by MelbourneDeveloper** [xamarin/Xamarin.Forms#2032]
### Description
If a Picker's ItemsSource raises a CollectionChanged event, and the NotifyCollectionChangedAction is Reset, the Picker's SelectedItem will be cleared out. 

**_Yes_**, even if none of the items in the ItemsSource have removed.

### Steps to Reproduce
1. Clone this repo: https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git
2. Run the sample in UWP mode
3. Click the button labelled "Picker Issue"
4. Click the Reset button
5. Notice the SelectedItem is cleared out (nulled out). This shouldn't happen because none of the items in the ItemsSource have been removed.

### Expected Behavior
SelectedItem does not change

### Actual Behavior
SelectedItem is cleared out (nulled out)

### Basic Information
A Reset action from CollectionChanged in and of itself should not affect the SelectedItem. It should only affect the SelectedItem if the SelectedItem has been removed from the ItemsSource - e.g. if it is completely cleared. I haven't tested on other platforms but my guess is that the behavior will be the same.

- Version with issue: 2.5.0.280555
- Last known good version: ?
- IDE: VS 2017
- Platform Target Frameworks: 
  - UWP:  16299 
  - Probably all platforms
- Nuget Packages: Xamarin.Forms

### Screenshots
https://www.dropbox.com/s/bimhdc9knj404pu/Before.png?dl=0

https://www.dropbox.com/s/kdwfycdyjpkk70e/After.png?dl=0

### Reproduction Link
https://ChristianFindlay@bitbucket.org/ChristianFindlay/xamarin-forms-scratch.git

**Comment by BradChase2011** [comment]
Just to clarify on this bug, this happens on all OS's.  This isnt UWP specific.  There are a few things wrong with the SelectedItem setting.  This happens on changing out the BindingContext as well as the ItemsSource.  Do we need to set the SelectedItem based on a -1 SelectedIndex?  This implies there is not a NULL value in the list but the user wants to be able to select NULL.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ajphall** [comment]
I confirm this still happens on 4.8.0.1451 and have submitted a PR to fix it.  Thanks to @MelbourneDeveloper for sharing your workaround.

**Comment by dimonovdd** [comment]
this issue is still not closed. I workaround changed the decision from @MelbourneDeveloper. 


```csharp
public class SafeSelectedItemBehavior : Behavior<Picker>
    {
        private const string PropertyName = "SafeSelectedItem";
        #region Fields 
        private Picker _Picker;
        private INotifyCollectionChanged? _NotifyCollectionChanged;
        #endregion

        #region Bindable Properties 
        public static BindableProperty SafeSelectedItemProperty = BindableProperty.CreateAttached
        (
            PropertyName,
            typeof(object),
            typeof(Picker),
            null
        );

        public static object? GetSafeSelectedItem(BindableObject view)
        {
            return view.GetValue(SafeSelectedItemProperty);
        }

        public static void SetSafeSelectedItem(BindableObject view, object value)
        {
            view.SetValue(SafeSelectedItemProperty, value);
        }
        #endregion

        #region Protected Overrides 
        protected override void OnDetachingFrom(Picker bindable)
        {
            _Picker.BindingContextChanged -= Picker_BindingContextChanged;
            _Picker.PropertyChanged -= Bindable_PropertyChanged;
            _Picker.SelectedIndexChanged -= _Picker_SelectedIndexChanged;
            if (_NotifyCollectionChanged != null)
            {
                _NotifyCollectionChanged.CollectionChanged += NotifyCollectionChanged_CollectionChanged;
            }
            base.OnDetachingFrom(bindable);
        }

        protected override void OnAttachedTo(Picker bindable)
        {
            base.OnAttachedTo(bindable);
            _Picker = bindable;
            _Picker.BindingContextChanged += Picker_BindingContextChanged;
            _Picker.PropertyChanged += Bindable_PropertyChanged;
            _Picker.SelectedIndexChanged += _Picker_SelectedIndexChanged;
        }

        private void _Picker_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (_Picker.SelectedItem != null)
            {
                SetSafeSelectedItem(_Picker, _Picker.SelectedItem);
                Refresh();
            }
        }
        #endregion

        #region Event Handlers 
        private void Picker_BindingContextChanged(object sender, EventArgs e)
        {
            AttachINotifyCollectionChangedHandler();
            Refresh();
        }

        private void Bindable_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(Picker.ItemsSource))
            {
                AttachINotifyCollectionChangedHandler();
                Refresh();
            }
            else if(e.PropertyName == PropertyName)
            {
                _Picker.SelectedItem = GetSafeSelectedItem(_Picker);
            }
        }

        private void NotifyCollectionChanged_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            Refresh();
        }
        #endregion

        #region Private Methods 
        private void AttachINotifyCollectionChangedHandler()
        {
            if (_NotifyCollectionChanged != null)
            {
                _NotifyCollectionChanged.CollectionChanged -= NotifyCollectionChanged_CollectionChanged;
            }

            if (_Picker.ItemsSource is INotifyCollectionChanged notifyCollectionChanged)
            {
                _NotifyCollectionChanged = notifyCollectionChanged;
                _NotifyCollectionChanged.CollectionChanged += NotifyCollectionChanged_CollectionChanged;
            }
        }

        private void Refresh()
        {
            var safeSelectedItem = GetSafeSelectedItem(_Picker);
            if (safeSelectedItem == null)
            {
                return;
            }

            if (_Picker.ItemsSource != null && _Picker.ItemsSource.Contains(safeSelectedItem) && !safeSelectedItem.Equals(_Picker.SelectedItem))
            {
                _Picker.SelectedItem = safeSelectedItem;
            }
        }
        #endregion
    }
```
