### ISSUE TITLE
App crashes when setting CurrentPage on TabbedPage in ctor in 2.5.1pre1

### ISSUE THREAD

**Issue by bentmar** [xamarin/Xamarin.Forms#2035]
### Description
App crashes when navigating to a tabbedpage thats sets CurrentPage to something  other than the first page.

```
  public class TabPage : TabbedPage
    {
        public TabPage()
        {
            Title = "Bug";
            Children.Add(new ContentPage() { Title = "Page 1" });
            Children.Add(new ContentPage() { Title = "Page 2" });
            Children.Add(new ContentPage() { Title = "Page 3" });
            CurrentPage = Children[1];  <-- Crash
        }       
    }
```

### Steps to Reproduce
1. Made a repro, just start the app and it crashes

### Expected Behavior
Should see the tabbedpage with the CurrentPage being Page2

### Actual Behavior
Crash

### Basic Information
https://github.com/xamarin/Xamarin.Forms/commit/d2f6ffae5ba6d9988fbb40d265f015a21a44b127#diff-7feeca82b01e77527e9263a06421f443 I think this PR is the cause of this crash

- Version with issue: 2.5.1-pre1
- Last known good version: 2.5.0.280555
- IDE: Visual Studio 2017
- Affected Devices: Android

### Reproduction Link
[listtap.zip](https://github.com/xamarin/Xamarin.Forms/files/1788580/listtap.zip)
The project uses the last known good version, update it to 2.5.1-pre1 and it will crash

**Comment by Shaboo** [comment]
still exists in pre3 as well
