### ISSUE TITLE
MergedDictionaries crashes on iOS (and Android with my reproduction solution)

### ISSUE THREAD

**Issue by Sokoo92** [xamarin/Xamarin.Forms#2037]
### Description
So MergedDictionaries aren't working on iOS, they work on Android. I tried to reproduce the bug with a new project, the problem now is actually that it crashed on both Android and iOS giving me a 

> Object reference not set to an instance of an object

No idea why, but might be a bug too. In my original project it does work for Android but not for iOS (I followed the exact same steps as I did in my original project trying to reproduce it). The solution I attached should reproduce the bug for iOS, but as it is crashing on the following line:

`Resources.MergedDictionaries.Add(new Theme1());`

Giving me the object reference exception. The code in the reproduction solution I attached is identical to the one in my original project where it doesn't crash on the object exception, only crashed on iOS telling me there's no such resource with the name "Primary".

### Steps to Reproduce

1. Open attached solution
2. Put buildconfiguration to Theme1 or create one that is called Theme1, else the Dictionary won't be merged, you can see what happens at line 12 to 14 in App.xaml.cs
3. Build
4. Run

### Expected Behavior
A merged dictionary with the one I tell it to merge with.
### Actual Behavior
Crashes either on the line where I add the merged dictionary with object reference exception, or crashed on iOS telling me there's no such property as "Primary"
### Basic Information

- Version with issue: latest stable
- Last known good version: N.A.
- IDE: Visual Studio 2017 community edition
- Platform Target Frameworks: 
  - iOS:  iOS 11.2
  - Android: Android 6.0 API level 23
- Nuget Packages: Xamarin.Forms
- Affected Devices: iPhones (tested on iPhone X simulator running 11.2) and Android visual studio emulator.

### Reproduction Link
https://ufile.io/gj9jf

**Comment by Sokoo92** [comment]
Hmmm did you put the build configuration to Theme1? I forgot to add that to the steps to reproduce :( sorry I'll edit.

**Comment by hartez** [comment]
@Sokoo92 Switching the theme worked, thanks!

**Comment by Sokoo92** [comment]
@hartez No problem! Hope you can pinpoint the exact bug that's causing it.

**Comment by StephaneDelcroix** [comment]
Thanks for this report. There's no bug here. The version of XF (2.5.x) you're using do not lazily creates the `Application.Resources` `ResourceDictionary for you. This capability will be present in the 3.0.x series.

So, creates the ResourceDictionary before adding to it

```csharp
Resources = new ResourceDictionary();
Resources.MergedDictionaries.Add(new Theme1());
```

**Comment by Sokoo92** [comment]
@StephaneDelcroix Thank you, this solved the Object reference error on Android and iOS, yet the Theme1.xaml still isn't loaded in for iOS, the text stays black and does not properly show the colors from the MergedDictionary.
Added this to my repro project:
`            Resources = new ResourceDictionary();

#if THEME1
            Resources.MergedDictionaries.Add(new Theme1());
#endif

		    MainPage = new NavigationPage(new MainPage());
		}`
Any solution for this?

**Comment by StephaneDelcroix** [comment]
the `THEME1` constant isn't defined anywhere

**Comment by Sokoo92** [comment]
@StephaneDelcroix Where do I need to define it then? I added it to my iOS project properties under build:
http://prntscr.com/iou3i4
The text stays black on iOS =/

**Comment by Sokoo92** [comment]
@StephaneDelcroix it is working now, sorry for the inconvenience it may have caused.
