### ISSUE TITLE
ForceUpdateSize Delay issue

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#2039]
Hi Xamarin

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Cells/Cell.cs#L211-L218

We can see such comment "don't run more than once per 16 milliseconds", but this code doesn't ensure 16 milliseconds delay... It just requires to wait every thread, there is no thread sync..

Perhaps, it can be regarding to https://forums.xamarin.com/discussion/123437/forceupdatesize-slows-ui#latest

**Comment by samhouts** [comment]
Hi @AndreiMisiukevich! Since we closed the related PR, do we want to keep this issue open for an alternate fix, or have we decided it is no longer necessary?

Thanks!

**Comment by stefan-stanca** [comment]
Why has this issue been closed? It is still very much present in the latest release (2.5.1.444934). I am still getting this behavior on ios when i programatically change the height of a child view (by changing IsVisible property)

**Comment by karlingen** [comment]
@AndreiMisiukevich Please re-open :)

**Comment by AndreiMisiukevich** [comment]
@karlingen there is #2735 
Let's close this one

**Comment by FrankSzendzielarz** [comment]
Still seeing this in 2020. What's the work around? ListView with a dynamic cell resize on ios works only for a few clicks before becoming unresponsive.
