### ISSUE TITLE
[Android] ShouldPreserveKeyboardOnResume exhibits the same behavior regardless of it's value

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2045]
### Description

Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=48307 here

### Steps to Reproduce

1. Run app and click the "pause and resume lifecycle events" button
2. Click in the Entry to display the soft keyboard.
3. Pause/sleep the app.
4. Resume the app.

### Expected Behavior
With ShouldPreserveKeyboardOnResume set to false, the keyboard should not appear

### Actual Behavior
Keyboard appears regardless of ShouldPreserveKeyboardOnResume value

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS: nope
  - Android: yes
  - UWP:  nope
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 6 running Android 6

### Reproduction Link
https://www.dropbox.com/s/e074gnnfk70fzke/PlatformSpecifics.zip?dl=0 - updated bugzilla project to 2.5

**Comment by adrianknight89** [comment]
@Paul-Brenner-Tangoe I just tested this platform specific in my app and noticed it works only when the screen is locked and unlocked. AdjustResize will always preserve the keyboard if we background and foreground the app unless it's done via screen lock. In that case, we need this property. Perhaps, we just need to update the documentation.

**Comment by Paul-Brenner-Tangoe** [comment]
@adrianknight89 are you saying this is native Android behavior ? If so, do you know how to get the desired effect? (not open the keyboard on resume). Thanks

**Comment by adrianknight89** [comment]
@Paul-Brenner-Tangoe If you unfocus the control in page OnDisappearing or app OnSleep, it will disappear, but this removes focus completely (i.e. no blinking cursor). If you want the control to be focused without the keyboard, you can create a dependency service method to hide it via `InputMethodManager` and call it in OnResume. Look at [KeyboardManager](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.Android/KeyboardManager.cs). 

In the future, you can set `HandleKeyboardOnFocus` to false which should give you control over the soft keyboard during focus changes, but you also need to set `ShouldPreserveKeyboardOnResume` to false. See #4248. Then, you'd need to handle IsFocused property changes in a custom renderer to show/hide the keyboard.

**Comment by Paul-Brenner-Tangoe** [comment]
@adrianknight89 Thanks!

@samhouts Can we get the documentation updated if this is not a bug?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
