### ISSUE TITLE
Controls Don't Disable Properly

### ISSUE THREAD

**Issue by AceCoderLaura** [xamarin/Xamarin.Forms#2047]
### Description
Controls do not visually indicate that they are disabled and they are not disabled according to the platform.

### Steps to Reproduce

1. Checkout https://bitbucket.org/ChristianFindlay/xamarin-forms-scratch
2. Open the TestXamarinForms.sln file
3. Run the application
4. Click on "IsEnabled Issue"
5. Notice the enabled controls on screen, appearing as enabled controls should
6. Click the "Disable This Page" button
7. Notice none of the controls have had their native "IsEnabled" property set to false
8. Notice that none of the controls exhibit visual indications of being disabled
9. Notice that not even the page is greyed out to any degree

### Expected Behavior
The controls should grey out by having the native IsEnabled property set on them.

### Actual Behavior
The page becomes what seems to be input transparent, which is not the same as disabled.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: Unknown
- IDE: Visual Studio 2017 Professional
- Platform Target Frameworks: 
  - Android: 8.0
  - UWP: 16299
- Nuget Packages:
Google.Apis.Calendar.v3             {1.32.2.1146}                            TestXamarinFormsLibrary                                                             
NETStandard.Library                 {2.0.1}                                  TestXamarinFormsLibrary                                                             
Xamarin.Forms                       {2.5.0.280555}                           TestXamarinFormsLibrary                                                             
Xamarin.Forms                       {2.5.0.280555}                           TestXamarinForms.iOS                                                                
Xamarin.Forms                       {2.5.0.280555}                           TestXamarinForms.Droid                                                              
Microsoft.NETCore.UniversalWindo... {6.0.7}                                  TestXamarinForms.UWP                                                                
Xamarin.Forms                       {2.5.0.280555}                           TestXamarinForms.UWP        
- Affected Devices: HTC U11

### Screenshots
![image](https://user-images.githubusercontent.com/21048448/37124813-00fe728c-22be-11e8-855a-7e07181aec79.png)
![image](https://user-images.githubusercontent.com/21048448/37124799-f060d316-22bd-11e8-8442-25786ee69f1d.png)

### Reproduction Link
https://bitbucket.org/ChristianFindlay/xamarin-forms-scratch

**Comment by jassmith** [comment]
Disabling a parent does not automatically disable all children.

**Comment by MelbourneDeveloper** [comment]
@jassmith please reopen this issue.

**Comment by MelbourneDeveloper** [comment]
@jassmith if this is the case, why is there half a feature implemented? 

When you turn of IsEnabled at the highest level, lower level controls mostly stop accepting input. Why is that even being done in Xamarin Forms? It's basically useless. We expected it to work, because the feature is half implemented, but when we looked more closely, it's just bizarre behavior.

Do you realize that you can even tab in to controls where the parent has IsEnabled set to false? What's the point of the children not accepting input, if the user can get around this?

**My recommendation would be to cascade the IsEnabled property down to other controls as per other XAML based Microsoft technologies. But, if that is not possible, there shouldn't be any inconsistent behavior that makes developers think that the controls are disabled when they are actually not.**

**Comment by jassmith** [comment]
As I said, I would love to change the behavior but I can't. And yes I realize you can do those things you mention.

**Comment by jassmith** [comment]
Changing the default behavior would be considered a breaking change, and yes I know we've had this discussion before. I would actually love to change the behavior of this interaction to something I consider far saner. You're 100% right that this could be made better by having an implicit flowthrough of the IsEnabled property. This however would be a behavioral break that would have to be quirked out.

I am not saying quirking it on its own is a blocker to us doing it, but it certainly adds a huge amount of complexity and delay to it actually getting done. In the past we've been allowed to unify behaviors, but not change behaviors once they are unified (and no existing backend did flowthrough for us to unify towards).

**Comment by MelbourneDeveloper** [comment]
Well, what are we supposed to do?

**Comment by jassmith** [comment]
I already passed this over to the PM team, that's it. If you want to write a spec you can but it will need to include some kind of sane quirking mechanism that doesn't currently exist in forms (that will be the bulk of the delay).

**Comment by jassmith** [comment]
Oh as for you,
```csharp
		private void EnableElementAndChildren (VisualElement element, bool enable)
		{
			element.IsEnabled = enable;
			if (element is ILayout)
			{
				foreach (var child in element.LogicalChildren)
					EnableElementAndChildren(element, enable);
			}
		}
```

I suppose the ILayout check isn't really needed, but I like it just to avoid going into weird edge cases.

**Comment by MelbourneDeveloper** [comment]
OK. Thanks. This isn't going to deal with all situations. We are going to need to do something like keep a list of all elements that were previously disabled, and then re disable them when other controls are re enabled. Of course this breaks all kinds of logic like binding logic and so on.

Meantime, I recommend coming up with a long term plan on how to fix this issue, and also rip out the hack code to make the controls input disabled when their parent is disabled. This hack doesn't fix any issues. It just confused us and made us think IsEnabled cascading was working when it actually wasn't.

**Comment by AceCoderLaura** [comment]
We're aware of our options in terms of hacks. There's no need to bother with such folly. Please focus on what you can do instead of what we're going to have to do. Thank you.

**Comment by jassmith** [comment]
okie dokie, I'll leave that to you then.

**Comment by KthProg** [comment]
Soooooooo?

**Comment by KthProg** [comment]
I noticed that I disabled a cell in a list view and there was no visual indication of it being disabled. This issue is over a year old.

**Comment by viktorszekeress** [comment]
I don't understand why this even needs a discussion. In all platforms that use XAML (WPF, WP8, UWP), it's a well know fact, that IsEnabled does apply to all children. 
Hence this should not be considered as behavior change, it should be considered as bug fix. I consider current implementation as wrong (and so do all other developers, just look at xamarin forums).

**Comment by derekantrican** [comment]
Related issue: https://github.com/xamarin/Xamarin.Forms-api-docs/issues/97

**Comment by valentasm1** [comment]
On iOs if you have buttons in ScrollView and then ScrollView is IsEnable=false buttons dont work, but on android works.

**Comment by jfversluis** [comment]
This is way old, which isn't great, but that also means that this functionality now probably is even more breaking then it was back then. I think the chances of still happening during the lifetime of Xamarin.Forms are pretty low.
