### ISSUE TITLE
Error on building solution after upgrading Forms NuGet

### ISSUE THREAD

**Issue by tanmay-bhattacharjee** [xamarin/Xamarin.Forms#2052]
On upgrading the forms version from an old version of forms and building the solution, build error is observed.

Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Users\User\.nuget\packages\xamarin.forms\2.5.1.340284-pre2\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	App53.Android	C:\Users\User\.nuget\packages\xamarin.forms\2.5.1.340284-pre2\build\netstandard1.0\Xamarin.Forms.targets	55	

Pre-Requisite:
Configure a custom Nuget Feed using the following Forms Nuget:
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1445932&tab=artifacts&_a=summary

Steps:
1. Launch VS and create a Blank Forms shared project.
2. Navigate to manage nuget packages for solution window.
3. Select "nuget.org" as source and select "Forms" package.
4. Downgrade the forms package to "2.3.4.270"
5. Build the solution.
6. Now, upgrade the forms nuget to the latest pre-rel from the custom feed i.e. "2.5.1.340284-pre2"
7. Once upgrade is successfull, build the solution.

Expected Result:
Solution should build successfully.

Actual Result:
Build error observed.

Build Info:
 - Microsoft Visual Studio Enterprise 2017  Version 15.6.0
 - VisualStudio.15.Release/15.6.0+27428.1
 - Microsoft .NET FrameworkVersion 4.7.02556
 - Xamarin 4.9.0.749 (9b0fce36d)
 - Xamarin Designer 4.10.58 (cee1369d0)
 - Xamarin.Android SDK 8.2.0.15 (HEAD/22d97e153)
 - Xamarin.iOS and Xamarin.Mac SDK 11.8.0.20 (1c6f300)
 
Build Gist:
https://gist.github.com/neerajdeshmukh/54d02a68c386b3c9ed003821c06892c6

Test Case Link:
https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/tests/view/23006947&group_by=cases:section_id&group_order=asc&group_id=108096

Test Run Link:
https://xqa-testrail.eastus.cloudapp.azure.com/index.php?/plans/view/54599

Reproducibility:
100% [Happens Everytime]

Attached Zip Logs and screen-shot of error for reference.
[Forms_Nuget_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/1793253/Forms_Nuget_Issue.zip)
![nuget_issue](https://user-images.githubusercontent.com/25505991/37152677-2ec388aa-2300-11e8-81e0-86c5e208f020.png)

**Comment by rmarinho** [comment]
This is because Visual Studio locks the task from the previous nuget, Clean, close vs, delete bin/obj folders, open VS update package, should work. Please reopen if it doesn't

**Comment by ckerkhoff** [comment]
I'm getting the same error even after clean, close or deleting bin/obj/package folders. It's also causing clean to fail with the same error.
