### ISSUE TITLE
XAML Parsing

### ISSUE THREAD

**Issue by Rombersoft** [xamarin/Xamarin.Forms#2056]
### Description
I just updated Xamarin.Forms version to 2.5.0 and my code is not working already. But when I returned to previous version problem stayed. I don't know why project broke and I don't remember last stable version
### Steps to Reproduce

<Label x:Name="_historyMenu" Text="{local:TranslateExtension menu1}" Grid.Row="0" Style="{StaticResource menuItemStyle}">

### Expected Behavior

Normal starting on emulator

### Actual Behavior
Xamarin.Forms.Xaml.XamlParseException: Position 47:46. MarkupExtension not found for local:TranslateExtension

### Basic Information

- Version with issue:  2.5.0
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks
  - Android: 17 and 23 SDK I tried
- Affected Devices: visual studio emulator

### Screenshots

![image](https://user-images.githubusercontent.com/19586466/37170778-73afa08e-2314-11e8-883c-1c70a0bfef55.png)

There is my XAML:

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:App1"
             x:Class="App1.MainPage"
             Title="E-Bookkeepper">

    <ContentPage.Resources>
        <ResourceDictionary>
            <Style x:Key="menuItemStyle" TargetType="Label">
                <Setter Property="Grid.Column" Value="1" />
                <Setter Property="FontSize" Value="Medium" />
                <Setter Property="Grid.ColumnSpan" Value="4" />
                <Setter Property="VerticalOptions" Value="Center" />
                <Setter Property="Margin" Value="0" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>
    <ContentPage.ToolbarItems>
        <ToolbarItem Name="Create" Icon="menu.png" Clicked="Button_Clicked"></ToolbarItem>
    </ContentPage.ToolbarItems>
    <AbsoluteLayout x:Name="_mainContainer" BackgroundColor="Black" Padding="0">
        <Label x:Name="_labelResidue" TextColor="DarkCyan" IsVisible="False" AbsoluteLayout.LayoutBounds=".5, .8, .8, .1"
                AbsoluteLayout.LayoutFlags="All" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"></Label>
        <Button x:Name="_butAdd" Image="addButton.png" BorderRadius="20" BorderWidth="0" AbsoluteLayout.LayoutBounds="0.5, 0.5, 85, 69"
                AbsoluteLayout.LayoutFlags="PositionProportional"
                BackgroundColor="Transparent" BorderColor="Blue" Clicked="Add_Clicked"/>
        <Frame x:Name="_menuPanel" CornerRadius="10" AbsoluteLayout.LayoutBounds="-1.5, 0, 0.6, 0.27" AbsoluteLayout.LayoutFlags="All" BackgroundColor="Ivory" Padding="15,10,15,10">
            <Grid RowSpacing="0" ColumnSpacing="0" Padding="0">
                <Grid.RowDefinitions>
                    <RowDefinition Height="*" />
                    <RowDefinition Height="11" />
                    <RowDefinition Height="*" />
                    <RowDefinition Height="11" />
                    <RowDefinition Height="*" />
                    <RowDefinition Height="11" />
                    <RowDefinition Height="*" />
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                <Image Grid.Column="0" Grid.Row="0" Source="history.png" Aspect="AspectFit" Margin="0,0,10,0" VerticalOptions="Fill"/>
                <Label x:Name="_historyMenu" Text="{local:TranslateExtension menu1}" Grid.Row="0" Style="{StaticResource menuItemStyle}">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Tapped="MenuOnSelected"/>
                    </Label.GestureRecognizers>
                </Label>
                <BoxView Grid.Column="0" Grid.Row="1" Grid.ColumnSpan="5" BackgroundColor="DarkGray" HorizontalOptions="Fill" HeightRequest="1" Margin="0,5"/>
                <Image Grid.Column="0" Grid.Row="2" Source="statistic.png" Aspect="AspectFit" Margin="0,0,10,0" VerticalOptions="Fill"/>
                <Label x:Name="_statisticMenu" Grid.Row="2" Text="{local:TranslateExtension menu2}" Style="{StaticResource menuItemStyle}">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Tapped="MenuOnSelected"/>
                    </Label.GestureRecognizers>
                </Label>
                <BoxView Grid.Column="0" Grid.Row="3" Grid.ColumnSpan="5" BackgroundColor="DarkGray" HorizontalOptions="Fill" HeightRequest="1"  Margin="0,5"/>
                <Image Grid.Column="0" Grid.Row="4" Source="settings.png" Aspect="AspectFit" Margin="0,0,10,0" VerticalOptions="Fill"/>
                <Label x:Name="_settingsMenu" Grid.Row="4" Text="{local:TranslateExtension menu3}" Style="{StaticResource menuItemStyle}">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Tapped="MenuOnSelected"/>
                    </Label.GestureRecognizers>
                </Label>
                <BoxView Grid.Column="0" Grid.Row="5" Grid.ColumnSpan="5" BackgroundColor="DarkGray" HorizontalOptions="Fill" HeightRequest="1"  Margin="0,5"/>
                <Image Grid.Column="0" Grid.Row="6" Source="bug.png" Aspect="AspectFit" Margin="0,0,10,0" VerticalOptions="Fill"/>
                <Label x:Name="_bugMenu" Grid.Row="6" Text="{local:TranslateExtension menu4}" TextColor="Red" Style="{StaticResource menuItemStyle}">
                    <Label.GestureRecognizers>
                        <TapGestureRecognizer Tapped="MenuOnSelected"/>
                    </Label.GestureRecognizers>
                </Label>
            </Grid>
            
        </Frame>
    </AbsoluteLayout>

</ContentPage>

**Comment by Rombersoft** [comment]
This is my Extension class

 [ContentProperty("Text")]
    public class TranslateExtension : IMarkupExtension
    {
        readonly CultureInfo ci;
        const string ResourceId = "App1.Resx.Resource";

        private static readonly Lazy<ResourceManager> ResMgr = new Lazy<ResourceManager>(() => new ResourceManager(ResourceId, typeof(TranslateExtension).GetTypeInfo().Assembly));

        public TranslateExtension()
        {
            if (Device.RuntimePlatform.ToLower().Contains("ios") || Device.RuntimePlatform.ToLower().Contains("android"))
            {
                ci = DependencyService.Get<App1.ILocalize>().GetCurrentCultureInfo();
            }
        }

        public string Text { get; set; }

        public object ProvideValue(IServiceProvider serviceProvider)
        {
            if (Text == null)
                return "";

            var translation = ResMgr.Value.GetString(Text, ci);

            if (translation == null)
            {
                #if DEBUG
                throw new ArgumentException(String.Format("Key '{0}' was not found in resources '{1}' for culture '{2}'.", Text, ResourceId, ci.Name), "Text");
                #else
                translation = Text; // returns the key, which GETS DISPLAYED TO THE USER
                #endif
            }
            return translation;
        }
    }

**Comment by hartez** [comment]
@Rombersoft  Where in your XAML are you declaring the `local` namespace?

**Comment by Rombersoft** [comment]
It exist but I forgot copy paste it. Day ago all works excellent.
more over when I deleted problem code string in XAML, deleted recursive bin & obj folders, restarted IDE and rebuilt all solution that I again get same error. I don't understand something. Where is saved old code if I cleaned all solution from old code??? Only after system reboot IDE shew another problem in this XAML file that Button_Clicked method is not found. But when I click right mouse on this method and select "Show definition" that IDE exactly directs to this method body. It's miracles, charms I don't know such words to take in order to image my shock.

**Comment by Rombersoft** [comment]
I will show all files just help me, please.

**Comment by jassmith** [comment]
Either Linker or you need to uninstall the app from the target system.

**Comment by Rombersoft** [comment]
Jassmith I don't understand what you mean.
I've tried to create new project Xamarin.Forms today and I was disappointed. Why did this type project changed? It is not similar as that I created half year ago. PCL contains XAML, classes but does not contain a references, properties! Moreover I can't add reference on PCL because it missing in list of projects which can be added. I ask you. What was changed in template project Xamarin.Forms in Visual studio? Why can not I create such project using old ordinary way?

**Comment by jassmith** [comment]
The decision to move the default to shared projects instead of PCL is not one I personally agree with. Shared projects are just glorified file linking for your head solutions, so in a build sense all files are just in a single project for each target.

**Comment by Rombersoft** [comment]
Thank you for linker advice. I change linking from "Sdk and user assemblies" to "Sdk assemblies only" and all became work. What is this shit?

**Comment by Rombersoft** [comment]
Excuse me, where have to I add attribute [PreserveAttribute]?

**Comment by hartez** [comment]
@Rombersoft You would add it as an attribute on your TranslateExtension class. Something like:

```
[Preserve (AllMembers = true)]
public class TranslateExtension : IMarkupExtension 
{ ...
```

But unless you are having issues with your app being too large with linking set to "Sdk Assemblies Only", you can probably just leave that setting alone and not worry about the Preserve attribute.

Some references:
https://developer.xamarin.com/guides/android/advanced_topics/linking/
https://developer.xamarin.com/guides/ios/advanced_topics/linker/

**Comment by Rombersoft** [comment]
Yes friend. But I have already written that parcer have not being found method Button_Clicked also. And in this case a tribute will not resque. Thank you very much. I will read your links with joy.

**Comment by Rombersoft** [comment]
Problem has happened due to broken Nuget manager

**Comment by Rombersoft** [comment]
Problem has happened due to broken Nuget package manager
