### ISSUE TITLE
WebView on Xamarin.Forms is not loading the files from the application local storage in UWP

### ISSUE THREAD

**Issue by PandeyAlokKumar** [xamarin/Xamarin.Forms#2058]
### Description
Hi,
I am developing a application on using Xamarin.forms for the cross platforms (UWP,iOS and Android). I am able to download the file from server and able to store to local storage using PCLStorage cross platform plugin.

I am trying to create a viewer using the WebVIew which will display the local storage files as per each platform support.

I am using WebView to create the viewer so that this can be used on each platform. When loading the files from local storage webview is not loading the files even not showing any error in loading. I am facing this issue on the UWP platform.

I am following the URL schema ms-appdata:///local/ for loading the local storage files as per

E.g:_
ms-appdata:///local/Packages/8126d6e9-f697-4abd-924b-73a159412c15_4fh6xh3q1xw62/roaming/1-17045247-1.PDF

### Steps to Reproduce

1. Keep some files in your local storage inside your application package
2. Load files in the WebVIew
3. WebView is not showing any content

### Expected Behavior
Not showing the content of file.. It seems not able to load files from storage
### Actual Behavior
It should show the file in the WEBVIEW

**Comment by hartez** [comment]
The WebViewRenderer for UWP doesn't seem to be able to handle ms-appdata:/// URIs at all.

**Comment by PandeyAlokKumar** [comment]
Do we have any workaround for this issue?

**Comment by bkaankose** [comment]
WebView is not compatible to load PDF files in UWP. You might say it uses Edge engine which can load PDF files but the truth is things are different in UWP. WebView is not Edge and you can't open PDFs in WebView afaik. 

Best approach would be to use pdfjs or PdfDocument class in Windows SDK. PdfDocument can render each PDF page in BitmapImage. You can even cache those Bitmaps in your local storage and get faster initialization time. This solution however only provides the displaying part. You can't edit or interact with the image as you can do with the PDF normally.

I am not exactly sure what you are trying to achieve with the ms-appdata schema but other than PDF problem you need to know that ms-appdata schema needs IUriToStreamResolver implementation most of the time. 

There are a lot of things that affects WebView's initialization on UWP and it's just a maze now.

**Comment by PandeyAlokKumar** [comment]
Thanks for your reply..

In my application I am downloading files of different file formats like (.MP3, MP4, .JPG, .PNG, .XLS, .RTF, .TXT etc.) from the server and storing to the application roaming storage.

I want to load the files from the local storage i.e. from roaming folder in WebView to display the content in the application. 

I am not able to load any files from local storage to WebView. 

 

Hope now you understand what I am looking to achieve. Looking ahead for your help to resolve this issue or any other alternative.

 

Thanks & Regards,

Alok Pandey

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ArunkumarRamakrishnan** [comment]
Hi, Still we are facing this issue. Is it ready to use? I don't see any related work item to track of it.
