### ISSUE TITLE
XamlCompilation attribute inconsistency

### ISSUE THREAD

**Issue by stmax82** [xamarin/Xamarin.Forms#2062]
When you create a new Cross-Platform App (Xamarin.Forms) with a shared .NET Standard project you get the following MainPage.xaml.cs:

```csharp
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}
	}
```

When you add a new "Content Page" to that project you get the following Page1.xaml.cs:

```csharp
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class Page1 : ContentPage
	{
		public Page1 ()
		{
			InitializeComponent ();
		}
	}
```

Note that there is a XamlCompilation attribute on Page1 but not on MainPage.

Also the [documentation](https://developer.xamarin.com/guides/xamarin-forms/xaml/xamlc/) says:

> XAMLC is disabled by default to ensure backwards compatibility.

I think the project templates should be updated (and possible the documentation too) - either put the XamlCompilation attribute on all pages (also on the MainPage) or remove it from newly created pages (which would conform to the documentation, which says that XAMLC is disabled by default).

Tested with VS2017 15.5.7.

**Comment by jassmith** [comment]
when we say its disabled by default we mean that if you dont add the attribute XamlC is disabled, not that the templates dont inflate a page with the attribute on them. That said I think the MainPage will start coming with the attribute as well.

**Comment by stmax82** [comment]
Is there a case already for adding the attribute to the MainPage or should I create one?
