### ISSUE TITLE
iOS - TabbedPage & Splash with iPhone X SafeArea

### ISSUE THREAD

**Issue by offroadn** [xamarin/Xamarin.Forms#2067]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
How do I solve the issue with using tabs on iOS 11 - iPhone X where the tabs are adjusted outside the tabbar area? Also, the splash image becomes stretched. I have tried implementing the SetUseSafeArea. All other devices seem to work correctly.
### Steps to Reproduce

1. use Iphone X
2. Have mulitple tabs with images (icons)
3. Load screen

### Expected Behavior
images are centered within tabbar item
### Actual Behavior
images are pulled out of the tabbar item
### Basic Information

- Version with issue:
- Last known good version: never
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: 2.5.0.280555
- Affected Devices: 

### Screenshots

![image](https://user-images.githubusercontent.com/12273672/37227158-49648a92-23aa-11e8-8531-4b30165430fb.png)

**Comment by hartez** [comment]
@offroadn I'm trying to reproduce the issue but so far everything seems fine; the tab bar icons seem to be placed correctly when I run on an iPhone X. 

Could you post a reproduction project demonstrating the issue? Perhaps I'm missing a detail.

**Comment by offroadn** [comment]
I have created a sample project. I noticed the strangeness because of the ios renderer.
[TabIssueProject.zip](https://github.com/xamarin/Xamarin.Forms/files/1799510/TabIssueProject.zip)

**Comment by pangia** [comment]
Also have this issue. Please advise.

**Comment by mayesa** [comment]
Same issue here.

**Comment by pauldipietro** [comment]
Project looks to display the issue in the original screenshot

**Comment by rmarinho** [comment]
Hum, if I comment out the custom renderer where you are changing the frame I get this:

![simulator screen shot - iphone x - 2018-03-21 at 19 21 18](https://user-images.githubusercontent.com/1235097/37732519-29d5a08e-2d3d-11e8-8934-634df7dac50c.png)

And the reason the images are really near the edge of the TabBar is because of the size of the images, notice the one on the right (Page3) where I use a image with recommended size and with title.
