### ISSUE TITLE
Customizing the NavigationBar in Xamarin form at Content Page Label (UWP)

### ISSUE THREAD

**Issue by PandeyAlokKumar** [xamarin/Xamarin.Forms#2068]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
I am developing a Xamarin form application in which we are customizing the ToolBarItems added to NavigationPage. 

-- Setting the below property in XAMARIN.UWP is hiding the default EllipsisButton so i can place my own Toolbar items.
 <Style x:Key="EllipsisButton" TargetType="Button">
            <Setter Property="MaxWidth" Value="0"/>
  </Style>
But the above is behaving for the application label. 
I am pushing a new ContentPage as Modal Async on the Navigation and adding the toolbarItems  but not able to see the toolbar items in this current Cntent page.

Navigation bar is visible but the Toolbaritems is showing as empty so user will not be able to understand which Toolbaritems action is clicked.

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
The added toolbaritems should be showed along with the icon and title.
### Actual Behavior
Navgation bar is shown with empty ToolbarItems
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PandeyAlokKumar** [comment]
Hi Paul,

Please find the sample code URL as below:-

 

https://drive.google.com/file/d/1LjhnytBxmxuGPha7I7xtKbtQX-xmWMxG/view?usp=sharing

 

let me know if you need any additional details.

 

Thanks & Regards,

Alok Pandey

**Comment by PureWeen** [comment]
I'm not quite following what issue you're having

```XAML
 <Style x:Key="EllipsisButton" TargetType="Button">
</Style>
```

Styles only the EllipsisButton for example if you do

```XAML
        <Style x:Key="EllipsisButton" TargetType="Button">
            <Setter Property="Background" Value="Pink"/>
        </Style>
```

You'll see only the EllipsisButton changes. If you want the other toolbar items to have more information then I'd recommend adding icons to them indicating the behavior then the user can click the Ellipsis to get more information.

I'm going to close this for now please re-open if I'm misunderstanding
