### ISSUE TITLE
Xamarin.Forms Previewer Fail

### ISSUE THREAD

**Issue by jamiewest** [xamarin/Xamarin.Forms#2070]
### Description

The Xamarin.Forms Previewer does not work with iOS.

### Steps to Reproduce

1. New project
2. Try to view xaml using Xamarin.Forms Previewer.
3. Error

### Expected Behavior

Shows the UI.

### Actual Behavior

Error:

System.TypeInitializationException was thrown.
The type initializer for "App Name" threw an exception.
at <unknown method> at offset 51 in file:line:column <filename unknown>:0:0
at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Obj... blah blah blah

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: IDK, was there ever one?
- IDE: VS2017 15.6.1

> VS bug #580673

**Comment by alanmcgovern** [comment]
Hi,

Would it be possible to share a copy of the project which triggers this problem? 

Thanks!

**Comment by jamiewest** [comment]
Disabling the linker seems to solve the issue. Is this normally required in order for this to work?

**Comment by drewgillies** [comment]
Hi @jamiewest: re-iterating @alanmcgovern's request for a failing project. Will close in a few days if no response. Thanks!

**Comment by alanmcgovern** [comment]
Please reopen the issue if you have further information which can help us diagnose and resolve the problem!

Thanks!
