### ISSUE TITLE
Unhandled exception does not reflect a place throwing

### ISSUE THREAD

**Issue by Rombersoft** [xamarin/Xamarin.Forms#2071]
I run debug project on VISUAL STUDIO 2017 and get such error:

![image](https://user-images.githubusercontent.com/19586466/37255044-421805ce-254f-11e8-8b01-ea5da88f804b.png)
Why IDE does not show place of throwing exception in my code??? I've deleted .vs ~/bin ~/obj folders - it did not help

**Comment by bkaankose** [comment]
Check your output dialog. You'll see the full stacktrace inside Android Debug output. I guess it's expensive for IDE to get the full details on some circumstances. That's why VS is failing to retrieve.

**Comment by Rombersoft** [comment]
I've already checked. But there is not stacktrace

**Comment by jassmith** [comment]
This one drives me bananas too, however it is not a Xamarin.Forms related issue. Please file here instead: https://bugzilla.xamarin.com/enter_bug.cgi?product=Visual%20Studio%20Extensions
