### ISSUE TITLE
iOS - Hamburger icon appears on HasBackButton = false

### ISSUE THREAD

**Issue by Blin4ik91** [xamarin/Xamarin.Forms#2074]
### Description
We have a masterdetail navigation in our app, the issiue is when a page within 
the navigationstack (not root) has set the "HasBackButton" property to false, 
the hambuger icon appears instead, even though it needs to be hidden. (Only on iOS)

### Steps to Reproduce

1. Create a Masterdetail navigation
2. Navigate with "pushasync()" to another page
3. set "HasBackButton" to false.

### Expected Behavior
No icon is displayed
### Actual Behavior
The hambuger icon appears instead
### Basic Information
- IDE: VS 15.6.1
- Platform Target Frameworks: 
  - iOS:  11.2
- Affected Devices: e.g. iPhone 7

**Comment by jassmith** [comment]
This is the expected behavior. The Hamburger menu is not the back button.
