### ISSUE TITLE
Picker.SelectedItem gets called twice

### ISSUE THREAD

**Issue by MaxFe** [xamarin/Xamarin.Forms#2075]
### Description

Setting SelectedItem programmatically leads to two calls of bound SelectedItem

### Steps to Reproduce
XAML: 
```xml
<Picker ... SelectedItem="{Binding SelectedItemX}" />
```
Code:
```csharp
public TypeOfX SelectedItemX {
    get => _selectedItemX;
    set => SetProperty(ref _selectedItemX, value); 
}
```

1. Navigate to page 
2. Set SelectedItemX: SelectedItemX = LoadXFromSqlite
-> That lead to call the setter of SelectedItemX twice (programmatically and from View)

### Expected Behavior
The view should realize that is has been updated by Vm and don't set SelectedItem again.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: 2.5.0.280555
- IDE: Visual Studio 2017
- Platform Target Frameworks: UWP
  - UWP:  16299.251 

### Reproduction Link
I haven't prepared a project because it should happen in every app.

**Comment by StephaneDelcroix** [comment]
similar to #2073. See my explanation there.

make sure your property setter (or your `SetProperty` method) no-op when the value isn't changed.

**Comment by MaxFe** [comment]
The event SelectedIndexChanged seems to be called twice too. Using Prism.Behaviors.EventToCommandBehavior call the bound command twice (when the SelectedItemX was set programmatically). The first call hits immediately. And the second with a delay of 100 - 200 ms.

**Comment by sahadevgupta** [comment]
@MaxFe  I'm also facing this issue is there any workaround or solution for it?

**Comment by amalu2020** [comment]
@MaxFe @sahadevgupta  Did you guys got a solution for the above picker issue?

I'm also facing this issue..
Can u plz guide me?

**Comment by amalu2020** [comment]
@sahadevgupta Thank you👍
