### ISSUE TITLE
Visual Studio 15.6.1 regression Android.Util.AndroidRuntimeException Activity did not call through to super.onCreate()

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#2081]
Cross posted to mono and Xamarin.Android
https://github.com/mono/mono/issues/7577
https://github.com/xamarin/xamarin-android/issues/1399

We have a Xamarin.Forms Android app that was previously working with VS 15.5.7 and is no longer working with VS 15.6.1.  It crashes during startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate().

Our activity does override OnCreate(), and we've verified via the debugger that the base.OnCreate() is being called.  However, the Xamarin.Forms FormsAppCompatActivity that Android applications are supposed to sub-class also overrides OnCreate(), so if it's just overriding that causes the issue everyone using Xamarin.Forms should be seeing this.

This is currently a show-stopper for our development team.

### Steps to Reproduce

1. Upgrade from VS 15.5.7 or earlier to 15.6.1
2. Android Application crashes at startup with the unhandled exception AndroidRuntimeException: Activity did not call through to super.onCreate()

### Expected Behavior

App should not crash, it was previously working with 15.5.7.

### Actual Behavior

App crashes, this is a regression.

### Version Information

Visual Studio 15.6.1
Xamarin.Android SDK   8.2.0.15 (HEAD/22d97e153)
Xamarin.Forms 2.5.0.280555 (also w/Xamarin.Forms 2.4.0.280)

### Log File

Call Stack
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
0x6 in Android.Runtime.UncaughtExceptionHandler.UncaughtException	C#
0x1A in Java.Lang.Thread.IUncaughtExceptionHandlerInvoker.n_UncaughtException_Ljava_lang_Thread_Ljava_lang_Throwable_	C#
0x1D in object.9a1fd30c-e995-4621-8122-35964d969409	C#

**Comment by jalbertSyncroTech** [comment]
I won't have a reproducible case any time soon.  This is happening on two of our machines, but not on a third one - all with the same code, VS version, and Android emulator settings.  Also, I wasn't able to reproduce it from a vanilla Xamarin.Forms template.

**Comment by jalbertSyncroTech** [comment]
Another instance of this issue
https://github.com/xamarin/xamarin-android/issues/1414 android.util.SuperNotCalledException

**Comment by PureWeen** [comment]
@jalbertSyncroTech   after you updated did you try with a clean project?  Delete bin/obj ?  I've seen this error a couple times when the binaries get out of sync. I saw this a couple days ago when testing a project on VS 2015 actually. Once I got a fresh project it worked fine

**Comment by jalbertSyncroTech** [comment]
Thanks @PureWeen, yes that does occasionally help.  What sometimes works is doing a clean/rebuild all.  However, that doesn't seem to work for developer on our team who gets this most often.  Also, I still get it consistently on the first build after a clean checkout.

What I can't figure out is why this is so random?  We all have the same VS version and Android SDK components.

**Comment by jalbertSyncroTech** [comment]
On 15.6.4, didn't help.  I've been following the Xamarin.Android release notes here.
https://developer.xamarin.com/releases/android/xamarin.android_8/xamarin.android_8.2/

**Comment by jalbertSyncroTech** [comment]
Minor update:
This happens consistently on a clean checkout, but using "Rebuild Solution" specifically (without cleaning first, and not just "Build Solution") seems to work-around the issue.

**Comment by jalbertSyncroTech** [comment]
Another update:
This seems to be related to the generated Resource.Designer.cs file.  We have multiple library projects that provide shared resources to our main application.  There are duplicate id's in these files such that different projects have the same id for different resources.  Occasionally when we see a crash on startup, it's referring to a resource with one of these duplicate id's.

**Comment by PureWeen** [comment]
There's some work in this area that should be going out in 15.7 as well so I'm hopeful it'll help.  Once those bits make it out to preview I'll let you know and we can see if that helps.    I've had a couple issues in this area as well that I know they are working on. 

So when you rebuild does it "de-duplicate" those id's? Does it generate a different Resource file? In my case the problem is coming from something with dex generation

I noticed because there was a variation with this file
\obj\Debug\android\bin\classes.dex

Between the working and non working projects. When I copied the file over from the non working into the working one it would start working again.    I feel good about 15.7 :-)

**Comment by jassmith** [comment]
In the mean time this is an android issue and not something we are going to be tracking in the Forms project. You can use the xamarin/xamarin-android project if you want to file this there though I am pretty sure there is already a bug for this.
