### ISSUE TITLE
[iOS] ListView Header disappears when items are added

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2084]
### Description

Migrating https://bugzilla.xamarin.com/show_bug.cgi?id=45327 here

From bugzilla:
Sometimes, when you add or remove items from a ListView, the Header element is given an incorrect size and disappears. I'm not exactly sure what sequence of events causes it, but I have attached a project that reproduces based on the UI in my project.

The project represents a page that is performing some long operation that will produce a set of items for the ListView. In preparation, the Header element of the ListView is set up. A 3-second Task inside the RouteDetailsView constructor simulates the completion of that long-running task and population of items. When the items are populated, the header disappears.

I've done some debugging via Immediate/Watch and discovered the Label in the header is being given a Height of -1. I've confirmed this with Label-derived classes that override OnSizeAllocated(). My understanding is you should NEVER pass a -1 for any size parameter in XF layout, so something's probably going haywire in the renderer for the ListView. 

### Steps to Reproduce

Run app
Wait 3 seconds
Note that the listview had a header, and after 3 seconds it is gone

### Expected Behavior
Items are updated, without affecting the header

### Actual Behavior
Header disappears

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: no
  - UWP:  not tested
- Android Support Library Version: 25
- Nuget Packages: just forms
- Affected Devices: tested on Nexus 5x running Android 8, and iPhone 5s running iOS 9.3 

### Reproduction Link
https://www.dropbox.com/s/fg9dfd4m5sk7p4d/lstheaderbug.zip?dl=0

**Comment by StephaneDelcroix** [comment]
This is a very old report with a very reproduction here.

Could you please confirm the problem still happens on 2.5.1 or nightly ?

Thanks

**Comment by Paul-Brenner-Tangoe** [comment]
@StephaneDelcroix  not sure why you added the needs repro tag, it has a repo with the latest stable version installed. I re-tested this against 2.5.1.340284 prerelease, and the issue still occurs.
I tried testing it against 3.1.0.27304 nightly, but it won't compile, gives me "the "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded"

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
