### ISSUE TITLE
PullTORefresh is not working for the UWP platform using XamarinForms ListVIew

### ISSUE THREAD

**Issue by PandeyAlokKumar** [xamarin/Xamarin.Forms#2086]
### Description

Added a listview in my application and added the enable the PullToRefresh property for the listView.

### Steps to Reproduce

1. Creating XamarinForms application and add a ListView conrol to forms
2. Enable PullToRefresh property and add a Refresh command 
3. The Refresh command is not getting called 

### Expected Behavior

This should call the Refresh command 

### Actual Behavior

This is not happening on UWP. I have only tested on the Windows 10 tablets.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
I don't get this part of your comment
> This is not happening on UWP. I have only tested on the Windows 10 tablets.

could you please:
- attach a small project triggering the issue
- tell us on which platform it happens

Thanks

**Comment by PandeyAlokKumar** [comment]
Hi Stephane,
I have created the sample for the PullToRefresh XamarinForms feature. The file-size was large so uploaded to google drive and find the below link.

https://drive.google.com/open?id=1YzhrE9xH8GBJslEbzUEhtTyncsZAE1uP

As per XamarinForms docs, I have added the below code to enable the PullToRefresh feature:-

` IsPullToRefreshEnabled="true" 
	          RefreshCommand="{Binding RefreshCommand}" 
	          IsRefreshing="{Binding IsBusy}" `
Next, RefreshCOmmand is added in the ViewModel

Issue:- Trying to pulling down the list view but Refresh command is not getting called.

Please suggest or correct me if anything more need to be added to get this working.

Looking ahead for your quick reply.
Let me know if you are facing any issue while dowloading the sample from the google drive.

**Comment by PandeyAlokKumar** [comment]
Hi Stephane,

 

Please find sample code link which is having a PullToRefresh feature property enabled but refresh command is not getting called.

 

https://drive.google.com/open?id=1YzhrE9xH8GBJslEbzUEhtTyncsZAE1uP

 

Let me know if you need any more details.

 

Thanks & Regards,

Alok Pandey

**Comment by StephaneDelcroix** [comment]
@PandeyAlokKumar  you still haven't been clear about the platform on which this happens

**Comment by PandeyAlokKumar** [comment]
I am currently checking on UWP platform.

**Comment by StephaneDelcroix** [comment]
Pull to refresh is not implemented in UWP at the moment. this explain why it doesn't work...

**Comment by PandeyAlokKumar** [comment]
Any alternate approach to achieve this on UWP platform?

**Comment by jbpoulsen** [comment]
I guess you should just add a button above or below the ListView. Alternatively you could add a ToolbarItem and let that call your "RefreshCommand". I'm currently debating this issue myself.

**Comment by jbpoulsen** [comment]
Just as a side node, beside adding a refresh button, I have actually also created a custom renderer for the ContentPage to intercept KeyEvents, so hitting F5 will also refresh the data in my listview. Works like a charm.

**Comment by nbevans** [comment]
UWP supports this now - as of Windows 10 build 1803: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/pull-to-refresh

Looks pretty trivial to wire up too. Would be good to get this added to XamForms.

**Comment by jlf0dev** [comment]
Any update on this? or @nbevans did you find a workaround?

**Comment by paradisehuman** [comment]
@StephaneDelcroix Any updates for using PullToRefresh in UWP desktop mode? It doesn't do anything on desktop mode.

**Comment by samhouts** [comment]
Please try the RefreshView instead. Thanks!

**Comment by nbevans** [comment]
Is ListView deperecated now?
