### ISSUE TITLE
[iOS] Foundation.MonoTouchException Objective-C exception thrown.

### ISSUE THREAD

**Issue by MaytagMuRun** [xamarin/Xamarin.Forms#2087]
### Description

We have created an app that needs to add and removes views. When testing we encountered some crashes. I created a project that reproduces our issue.

I tried adding System.Threading.SemaphoreSlim to prevent adding and removing view at the same time, but it still crashes.

Adding and removing views causes Foundation.MonoTouchException Objective-C exception thrown.  Name: NSGenericException Reason: *** Collection <CALayerArray: 0x600000244da0> was mutated while being enumerated.

### Steps to Reproduce

1. Please see the reproduction project.
2. Click the button as fast as you can.
3. After some time it will crash on iOS Simulator and real devices.

### Basic Information

- Version with issue: Xamarin Forms 2.5.0.280555
- Last known good version:
- IDE: Visual Studio Community 2017 for Mac Version 7.0.1 (build 24)
- Platform Target Frameworks:
- Xamarin.iOS Version: 10.10.0.36 (Visual Studio Community)
- Nuget Packages: Xamarin Forms 2.5.0.280555
- Affected Devices: iPhone 5, iPhone 7, iPhone 8

### Screenshots

![screen shot 2018-03-13 at 2 59 30 pm](https://user-images.githubusercontent.com/37324947/37327904-17946272-26d3-11e8-8695-6a960db1c940.png)

### Reproduction Link

https://github.com/MaytagMuRun/TestBug

**Comment by StephaneDelcroix** [comment]
I can confirm this behavior. The Children collection is modified "too often", and is modified while still handling the modification from the previous change

**Comment by nickginis** [comment]
I am experiencing the same issue as shown in the sample project. Is there any update on when this could potentially be worked on for a fix? Thanks

**Comment by darrenasc** [comment]
Snap! Guys, this is a major issue on a project I'm working on and presents a big risk to the viability of the solution. We would really appreciate some guidance around if/when this will included in a release so that we can plan accordingly.

Thanks,
Darren. 
Mobile Solutions Development Manager, Stockland.

**Comment by hoquem1** [comment]
Any update on this issue. I am having same issue today after getting the latest updates for Visual Studio Mac , Xamarin and Mono.

**Comment by shoeIT** [comment]
any news on this ?
I also get this error recently...

**Comment by AndreiMisiukevich** [comment]
The same issue was reported to one of my open-source projects https://github.com/AndreiMisiukevich/CardView/issues/127

I do all work in lock sections - still reproduce it sometimes.

**Comment by aman720gupta** [comment]
I'm also facing the same issue with the usage of AndreiMisiukevich/CardView.

@AndreiMisiukevich any solution for same?

**Comment by morokolo** [comment]
In Xamarin Forms, You would get this type of error if you have not registered an interface that you are implementing in the platform specific project i.e iOS. try register in you AppDelegate or  MainActivity .  **TIP :** iOS error handling in Xamarin forms is horrible, if you get errors like this in a cross platform project, try running the Android build, the errors you get with Android are much better and more sensible.
`  public class iOSInitializer : IPlatformInitializer
    {
        public void RegisterTypes(IContainerRegistry container)
        {
            container.Register<IAppVersionAndBuild, VersionAndBuildiOS>();
        }
    }`

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by darrenasc** [comment]
No longer required thanks.

**Comment by rshah1803** [comment]
Hi @samhouts,

We are getting this issue quite frequently now, I am not sure with IOS 14 upgrad. We are using Latest Media plugin and while taking photos some times app crashes. It very random. Can you please help

Thanks,
Rohan

**Comment by rshah1803** [comment]
and its throwing same error as mentioned above v Foundation.MonoTouchException thanks

**Comment by sisaacks** [comment]
I am also getting this issue.  I am not sure why, it just started......getting monotouchexception as well

**Comment by brytonhuggins** [comment]
Running IOS 14.7.1 and using Xamarin.Essentials 1.7.0 I am getting the same error while attempting to take pictures using the MediaPicker. Has a solution been found / Can this issue be reopened?
