### ISSUE TITLE
Setting FontFamily for ios UIBarButtonItem does to work when navigating between pages with and without navigationbar

### ISSUE THREAD

**Issue by rasmuschristensen** [xamarin/Xamarin.Forms#2097]
### Description
Setting a custom font for ios toolbar items does not when when navigation from a page without a navigationbar to a page with navigationbar looses the customfont set for toolbaritems
### Steps to Reproduce

1. Create a vanilla XF app with XAML
2. Add 2 pages
3. Set NavigationPage.HasNavigationBar to false on the page that open when the app starts
4. Create a toolbar item on the second page
5. Make a PageRenderer for default ContentPage
6. inside ViewWillAppear in the ios PageRenderer set fontfamily to a custom font (I'm using fontawesome)
7. Make a button to navigate from first to second page
8. Try to change the first page to have HasNavigationBar set to true
9. Now it works as I would expect it to work as in using the custom font

### Expected Behavior
Custom font should be used
### Actual Behavior
Custom font is not used
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
XF 2.5.0.280555
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
could you please attach a small reproduction project ? thanks

**Comment by rasmuschristensen** [comment]
Hi @StephaneDelcroix 

I made a repo here: https://github.com/rasmuschristensen/IconBugHunt

You should be able to flip the visibility of the navigationbar in XamFontAwesomePage.xaml to trigger the issue, there is a comment in the code. It's only valid to verify in iOS for this project.

**Comment by rasmuschristensen** [comment]
Seems like the missing thing is the NavigationController. If I hack and add the NavigationBar when moving to the next page, it works. But then I need to hide it again for the firstpage. Still think this is a bug?

**Comment by rasmuschristensen** [comment]
Any status?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
