### ISSUE TITLE
Xamarin.Forms 2.5 & Admob, doesn't work anymore. (Nested Layouts Issue?)

### ISSUE THREAD

**Issue by marcojak** [xamarin/Xamarin.Forms#2098]
### Description
I updated my solution to a .NetStandard project & Xamarin.Forms 2.5. Now if I try to run the app, the Ads are not showed anymore with this error: "Not enough space to show ad. Needs 411x49 dp, but only has 411x49 dp.".
I suspect there is an issue with nested layouts (stacklayout inside an absoluteLayout).

### Steps to Reproduce

1. Create a ContentPage with an AbsoluteLayout and a StackLayout:
2. The code:
```
BaseLayout = new AbsoluteLayout
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
                BackgroundColor = Color.White,
                Padding = new Thickness(0),
            };

            Content = BaseLayout;

            ContentLayout = new StackLayout
            {
                Padding = new Thickness(0),
                Spacing = 0,
            };

            AbsoluteLayout.SetLayoutBounds(ContentLayout, new Rectangle(0, 0, 1, 1));
            AbsoluteLayout.SetLayoutFlags(ContentLayout, AbsoluteLayoutFlags.All);

            BaseLayout.Children.Add(ContentLayout);

            var ads = new MyAdView
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.End,
                AdsId = "XXX",
                Margin = 0
            };

            ContentLayout.Children.Add(ads);
```

3. If run the app, you get the error "Not enough space to show ad. Needs 411x49 dp, but only has 411x49 dp.".

PS. If I set the ads as child of BaseLayout I can see the ads.

### Expected Behavior
I should be able to see the ads (I was before moved to .NetStandard & Xamarin.Forms 2.5
### Actual Behavior
I get this error "Not enough space to show ad. Needs 411x49 dp, but only has 411x49 dp." and the ads are not showed.

### Basic Information

- Version with issue:
- Last known good version: PCL &  Xa.arm.Forms 2.3
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: Tried with 26 & 27
- Nuget Packages:
- Affected Devices: I tried on a Pixel 2 (it worked before I updated to .NetStandard & Xamarin.Forms 2.5)

**Comment by StephaneDelcroix** [comment]
please attach a small repro project that we'll to investigate, fix, and confirm it's fixed

**Comment by marcojak** [comment]
I've added a repro project to this message.
I've removed my Admob Ids but a part that, the project is ready to go.

So we have a stacklayout inside an absolutelayout and the ads is child of the stacklayout.
In this way it doesn't work, like there was a "space" between the 2 layouts.

if I add the ads directly to the absolutelayout, it works.
If I set the page content to the stacklayout and the ads as child of this stacklayout, it works as well.

Ps. it worked fine until I moved to .NetStandard and Xamarin.Forms 2.5


[TestAds.zip](https://github.com/xamarin/Xamarin.Forms/files/1812053/TestAds.zip)

**Comment by PureWeen** [comment]
I took your repro and ran it against 2.3.4.270 with a PCL Profile259 library and when ran against a Pixel 2 simulator and I get the same error message
*[Ads] Not enough space to show ad. Needs 411x49 dp, but only has 411x49 dp.*

I'm going to close this for now. Please let me know if I've missed something and should re-open
