### ISSUE TITLE
ListView header still visible after set to null

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#2099]
1. Create a ListView with HasUnevenRows="True" IsGroupingEnabled="True" and with a header that contains a label.
2. Sometime after the ListView has been rendered, set the header to null.

The header will still be displayed on UWP. Not sure about iOS and Android. Xamarin.Forms 2.5.0.280555.

**Comment by ravinderjangra** [comment]
This was resolved. 
https://github.com/xamarin/Xamarin.Forms/pull/1765
