### ISSUE TITLE
[UWP] PanGestureRecognizer doesn't fire complete event if the mouse leaves the bounds of the window

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2100]
### Description
On UWP when using a PanGestureRecognizer if your mouse leaves the bounds of the UWP window while you have it held down then your next click inside the UWP window will have skipped a GestureID and the previous GesturedId will never have sent a Complete message

### Steps to Reproduce

1.  Run the sample for UWP
2.  if you click and hold down on the screen and move the mouse around you'll see the red box move. 
3. While you have the mouse click pressed down move the mouse outside the bounds of the UWP window
4. At this point if you bring the mouse back into the window (while still pressed down) you'll notice the box no longer moves with the mouse
5. Now if you Release the mouse then click back down you'll see a list of events show up in a list view with the last 20 events that occurred. Here you'll see the args that were skipped

[PanGestureRecognizerUwpComplete.zip](https://github.com/xamarin/Xamarin.Forms/files/1811962/PanGestureRecognizerUwpComplete.zip)

The sample is setup to only show events when there has been a break in expected events

### Expected Behavior
Not sure if this is possible on UWP but if the mouse leaves the bounds of the window it should just come back in and pick up where it left off with the same gestureid.

If that's not possible then the GestureId should complete and a new one should pickup sequentially

### Actual Behavior
Complete doesn't fire if mouse leaves the bounds of the UWP window

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 15.6.2
- Platform Target Frameworks:
  - UWP:  16299 
- Nuget Packages: 2.6.0.257167-nightly

### Screenshots

 
![image](https://user-images.githubusercontent.com/5375137/37416136-a3e10eca-2772-11e8-8d55-6f57ab9e26fc.png)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by shrikantbmali** [comment]
I have the same issue, Can we reopen this issue, and I can provide all needed information...
