### ISSUE TITLE
XAML Compiler Passes Hanging Behaviors

### ISSUE THREAD

**Issue by adamhill** [xamarin/Xamarin.Forms#2112]
### Description
XAML Compiler does not catch non-enclosed Behaviors

### Steps to Reproduce

1. Add a Behavior to an element (like EventToCommand), but **omit** the enclosing <Tag.Behaviors/> tags.
2. Turn on XAML Compilation.
3. Compile, App will build and deploy, but Behavior will not work.

### Expected Behavior
An Error from the XAML Compiler

### Actual Behavior
App compiles without complaint and runs fine except the Behavior does not fire.

### Basic Information

VS 15.6.1
Latest Xamarin
iOS & Android

**Comment by jassmith** [comment]
Sorry for the lack of response, confirmed.

**Comment by samhouts** [comment]
@adamhill Can you clarify the issue you're experiencing, per @StephaneDelcroix's comment? Thanks!

**Comment by PureWeen** [comment]
Closed for inactivity. If you can clarify the info @StephaneDelcroix  requested we can reopen.
