### ISSUE TITLE
Memory Leak on Xamarin Forms UWP

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#2113]
### Description
I wrote UWP but this can be also on Android on IOS because I profiled only UWP application using VS2017.

### Steps to Reproduce

1. Open VS 2017 and start a new xamarin forms project by selecting tabbed page or masterdetail page. 
2. No need to write any single code.
3.  Profile UWP application for memory and take snapshots like in the screenshots

- First snapshot is after application is loaded.
- 2nd one has taken after selecting an item in the list and navigating to the ItemDetailsPage
- 3rd snapshot was taken after navigating back to ItemsPage

### Expected Behavior
not see ItemDetailsPage on 3rd snapshot because I am navigating back and this page is popped from the navigation stack. so it should be removed, collected by GC or disposed.
### Actual Behavior
ItemDetailsPage is still in the memory although it is popped
 
### Screenshots

![image](https://user-images.githubusercontent.com/10422347/37481714-bdf3d516-2882-11e8-9bba-69dc49d8959e.png)

![image](https://user-images.githubusercontent.com/10422347/37481722-c2cd5210-2882-11e8-9ad8-df73943d9a45.png)

### Reproduction Link

See the uploaded project. it includes Profiling session Report as well

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/1816530/App1.zip)

**Comment by SSpormann** [comment]
I see this behavior in my project as well and I thougt a good workauround would be to reuse the pages once they are generated. But the even there are bindings that are generated and will never die even if I null the page.

**Comment by nschoenberg** [comment]
@EmilAlipiev I noticed this in my project as well. Further analyses revealed that NavigationService (Prism) is holding a refererence to _previousPage and my "leak" was goine by navigating to another page. Not 100% sure it is prism only, so maybe give it a try.

**Comment by cheles** [comment]
Just an update that might impact XF too.
We released UWP 6.2.9 NuGet update with huge improvements in memory handling and GC calls while targeting >=RS4. The complete release notes are here: https://github.com/microsoft/dotnet/blob/master/releases/UWP/net-native2.2/README.md
@EmilAlipiev  can you try to update everything to latest and see if you still repro memory leak while navigating between pages?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by EmilAlipiev** [comment]
Hi @samhouts I have just tested using 4.7 and collectionView with 350 items each has 2 pictures using ffimageloading.
Memory is keep increasing on scrolling down and up. It seems that recycling doesnt work at all. once. When I click the back button the page and pop the page, memory remains the same. Obviously a leak. 
Exact the same Datatemplate, Just replaced with Syncfusion SfListview and Recycling works perfectly fine. Memory is not increasing dramatically on scrolling up down. When i pop the page, memory is restored back to the starting point. So yes it is still the case with 4.6 and 4.7

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
