### ISSUE TITLE
[UWP] DisplayAlert shows the title twice

### ISSUE THREAD

**Issue by rdaniel0** [xamarin/Xamarin.Forms#2117]
### Description
The title of the alert is shown twice, once in the title bar of the popup, and again as a big header.

### Steps to Reproduce

1. Create a new cross-platform Xamarin.Forms project.
2. Call `DisplayAlert("title", "message", "OK");` in Constructor of MainPage code-behind and fill in parameters.
3. Run the UWP project.

### Expected Behaviour
Title in the alert should only show up once.

### Basic Information

- Version with issue: Xamarin.Forms 2.5.1.317207
- IDE: Visual Studio
- Platform Target Frameworks: 
- UWP: 16299

### Screenshots

![screen shot 2018-03-16 at 15 46 53](https://user-images.githubusercontent.com/18712717/37505562-503602ba-2931-11e8-846e-8601106b7033.png)

**Comment by jfversluis** [comment]
Now the question remains: which one do we want to keep? ;)

**Comment by bkaankose** [comment]
It's not a bug. OS is designed that way. I don't see any reason that XForms are responsable for this.

**Comment by samhouts** [comment]
Yep, this is default UWP behavior. No need for us to change it. Thank you for your feedback!
