### ISSUE TITLE
[Android] Forms Map doesn't reload after updating Google Play Services

### ISSUE THREAD

**Issue by dreeanic** [xamarin/Xamarin.Forms#2120]
Currently, as seen on the Map sample app (https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps), if Google Play Services aren't up to date a nice message appears, prompting the user to update the services. However, after doing the update and returning to the app the map isn't reloaded. There is still the "update" button displayed, linking to Google Play Store which now displays an up to date Google Play Services.

What would be the best way to initialize Forms Maps again and reload the map without having to restart the app?

**Comment by jfversluis** [comment]
Hope you got this revolved by now... 😬
