### ISSUE TITLE
Maps should listen to Pin property changes

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#2121]
### Description

The Pin class in the Maps project inherits from BindableObject, but the Map does not update on a property change to a Pin.

### Steps to Reproduce

1. Add a Pin to a Map.
2. Change the Position property of the pin.
3. Change the Label property of the pin.
4. Change the Address property of the pin.

### Expected Behavior

2. The pin will move to its new position on the map.
3. When the pin is tapped and its info window is displayed, it will display the new Label on the first line.
4. When the pin is tapped and its info window is displayed, it will display the new Address on the second line.

### Actual Behavior

No property changes are reflected in the UI.

### Basic Information

- Platforms Affected: Android, iOS
- Reproduction: https://gist.github.com/jcmanke/13ebdad7c58f71bf74f4ffc9841f7cea

**Comment by jcmanke** [comment]
Added some more details and a reproduction case.

**Comment by PureWeen** [comment]
[MapPins.zip](https://github.com/xamarin/Xamarin.Forms/files/1862193/MapPins.zip)
