### ISSUE TITLE
Dynamic StyleSheet Providers

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#2123]
### Description

When working with a modular app design I may need to reference a StyleSheet by name without actually having it available in the local assembly, or for that matter even knowing where it ultimately is coming from. Essentially I might have something like:

```cs
public interface IStyleSheetFileProvider
{
    StyleSheet GetStyleSheet(string name);
}

public class StyleSheetLocator
{
    public string Name { get; set; }

    public static implicit operator StyleSheet(StyleSheetLocator locator)
    {
        var provider = Application.Current as IStyleSheetFileProvider;
        return provider.GetStyleSheet(locator.Name);
    }
}
```

I should be able to reference this from either code or XAML to inject a stylesheet, however this currently only works in code.

### Steps to Reproduce

This results in an `Exception`.

```xml
<ContentPage xmlns:styles="clr-namespace:AwesomeApp.Common.Styling;assembly=AwesomeApp.Common">
  <ContentPage.Resources>
    <styles:StyleSheetLocator Name="Styles.css" />
  </ContentPage.Resources>
</ContentPage>
```

This works..

```cs
public class MyPage : ContentPage
{
    public MyPage()
    {
        Resources.Add(new StyleSheetLocator { Name = "Styles.css" });
    }
}
```

### Expected Behavior

Both code and XAML should work

### Actual Behavior

Only adding the StyleSheet from code works. When compiling there is a build error:

```
Severity     Description	
Error        Position 9:10. resources in ResourceDictionary require a x:Key attribute
```

### Basic Information

- Version with issue: vNext
- Last known good version: n/a
- IDE: n/a

### Screenshots

![image](https://user-images.githubusercontent.com/3860573/37547336-51e63f10-292e-11e8-86ee-85a71a76b036.png)

### Reproduction Link

[AwesomeApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1820973/AwesomeApp.zip)

**Comment by StephaneDelcroix** [comment]
in order for your type to be added in a RD without a x:Key, it should be of a type supported by one of the `Add()` overload taking a single parameter, i.e. RD, or StyleSheet. you might want to try to abuse those.

**Comment by dansiegel** [comment]
@StephaneDelcroix what you’re suggesting is not XAML friendly. This really needs to be revisited. What we have right now is confusing. With this being a vNext feature I would say we need to get rid of the existing StyleSheetExtension and expose the internal List<StyleSheet>. This would make it more consistent between code and XAML, not to mention it would make it easier if someone wanted to add more than one StyleSheet from XAML.

**Comment by StephaneDelcroix** [comment]
I'm not sure I understood your original request correctly, but I'm even less understanding your last comment.

- *Extension classes, and IValueProvider are XAML-friendly. And `<StyleSheet>`'s don't get a special treatment at all in our loaders,
- noting prevents you from writing your own StyleSheetExtension (or if it does, please report it as a bug). This what you probably should do...
- noting prevents you from adding multiple StyleSheets in a RD (or if it does, again, you know what to do)
- StyleSheet(Extension).Source points to a file-like path, which is actually a mapping to a resource-id in the same assembly of the xaml file referring to it. We might extend that syntax in the future to be able to point to a resource in a different assembly.

**Comment by dansiegel** [comment]
There's a couple parts to this. First is the current API particularly in XAML is misleading. Unless I've missed something here...

```xml
<ContentPage.Resources>
  <StyleSheet Source="Styles.css" />
</ContentPage.Resources>
```

Looking at this I might think that we're referencing `Xamarin.Forms.StyleSheets.StyleSheet`, when in fact I believe it's actually referencing the StyleSheetExtension. Why is this confusing? Well because it leads to the to the thought that the following code equivalent would work:

```cs
public MyPage()
{
    Resources = StyleSheet.FromAssemblyResource(GetType().Assembly, "AwesomeApp.Styles.css");
}
```

Of course if that worked then my original sample for the Dynamic StyleSheet provider would work. It of course doesn't because Resources needs a ResourceDictionary not a StyleSheet since the StyleSheet is actually something contained in the ResourceDictionary.

This leads to the next issue that I brought up in my follow up with multiple StyleSheets. This should be something that works with ease in XAML which it just doesn't. It's easy enough to call `Resources.Add(...)` in code, but this leads to a poor XAML experience. Exposing the internal list of StyleSheets makes this much easier so that you might have something more like:

```xml
<ContentPage.Resources>
  <ResourceDictionary>
    <ResourceDictionary.StyleSheets>
      <StyleSheet Source="Style1.css" />
      <StyleSheet Source="Style2.css" />
    </ResourceDictionary.StyleSheets>
  </ResourceDictionary>
</ContentPage.Resources>
```

Not to mention that this makes the it clearer that Resources isn't either a StyleSheet or a ResourceDictionary but rather that it is always a ResourceDictionary and you are adding 1-* StyleSheets to that ResourceDictionary.

**Comment by dansiegel** [comment]
@StephaneDelcroix does that help clarify the issue?
