### ISSUE TITLE
Xamarin Installation in VS 2017

### ISSUE THREAD

**Issue by aammfe** [xamarin/Xamarin.Forms#2124]
I know this is not right place to ask but I have tried to ask in Xamarin form but I could not share image link over there bcs "You have to be around for a little while longer before you can post links."

I have installed Xamarin.
![image](https://user-images.githubusercontent.com/11896817/37553911-7c2cb384-29f2-11e8-8dc0-c82a1c827b21.png)

you can check its installed 
![image](https://user-images.githubusercontent.com/11896817/37553920-a4cd9ae2-29f2-11e8-9fca-70630bd1aa11.png)

but not finding it in project create menu.
![image](https://user-images.githubusercontent.com/11896817/37553927-c8b49ac8-29f2-11e8-93c6-fae827cb46dd.png)

**Comment by StephaneDelcroix** [comment]
> I know this is not right place to ask

yeah, sorry. try restarting VS

**Comment by aammfe** [comment]
I did restart and start installing again but it stuck on this .

![image](https://user-images.githubusercontent.com/11896817/37559314-7e4232ae-2a45-11e8-94f1-953bbfc19145.png)

**Comment by aammfe** [comment]
![image](https://user-images.githubusercontent.com/11896817/37559410-7975d2e2-2a47-11e8-8579-be799953eaff.png)

I did restart VS
