### ISSUE TITLE
AppCompat Theme not working for Dialog.Alert on pre Lollipop devices.

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#2126]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description 
Guys after updating latest nuget packages for Forms to 2.5.0. Appcompat theme for dialog alert is not working on pre lollipop devices.

### Steps to Reproduce

1. Check any alert dialog after updating to Forms 2.5 on pre-lollipop devices. 

### Expected Behavior
After applying appcompat theme dialog alert should be appear as material design alert on pre lollipop devices.

### Actual Behavior
After applying appcompat theme dialog alert not changed to material design alert.

### Basic Information

- Version with issue: 2.5
- Last known good version: 2.4
- IDE: VS for Mac
- Platform Target Frameworks:  Android 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: pre-lollipop devices

**Comment by hemantksh** [comment]
@jassmith  Do we have any update on this?

**Comment by hemantksh** [comment]
@samhouts @jassmith This defect was taken in sprints 137 and 138 but was not completed. It is not in the current sprint. When do we expect this to be worked upon? An early resolution is requested.

**Comment by samhouts** [comment]
@hemantksh Given our current priority list, this is planned for Sprint 140. Thanks!

**Comment by hemantksh** [comment]
@samhouts This defect has been lingering for long. Can this be prioritised please?

**Comment by samhouts** [comment]
@hemantksh Have you tested this with a later version of Forms recently? We're currently on 4.1. Thanks!

**Comment by jfversluis** [comment]
I think this was (coincidentally) fixed with this change: https://github.com/xamarin/Xamarin.Forms/commit/e1ad3bad6852c4f17ccaaf4aeaea3e160d973e1b#diff-f1670823482d44d073b015178c2bcb0b

Which should be available in the latest 4.4 version. I am not able to reproduce anymore, so I will assume this is fixed. If you find anything different, please feel free to reopen it.
