### ISSUE TITLE
Getting Java.Lang.SecurityException with Forms.Maps

### ISSUE THREAD

**Issue by davefxy** [xamarin/Xamarin.Forms#2138]
When I debug a Cross Platform Mobile App (Xamarin Forms, .Net Standard, Android) on a Samsung tablet, I get this error after the app has downloaded and begins to run. VS displays an unhandled exception : 
Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION

It appears the problem is a combination of using a TabbedPage and adding a ContentPage with a map control with IsShowingUser=true.
If I run the same code with IsShowingUser=true on a ContentPage by itself, it runs fine.

If I remove IsShowingUser option from the ContentPage on the TabbedPage, it run just fine.
Run the accompanying zipped project.

Environment versions:
Hardware: Samsung Galaxy S2 (SM-T810 Android 7.0, API 24)
Microsoft Visual Studio Community 2017 
Version 15.6.3
VisualStudio.15.Release/15.6.3+27428.2011
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

C# Tools   2.7.0-beta3-62707-11. Commit Hash: 75dfc9b33ed624dff3985c7435c902c3c58c0e5c
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.9.0.752 (0faa808ee)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.58 (cee1369d0)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

[MyWorkingWithMaps_Bug Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/1826992/MyWorkingWithMaps_Bug.Bug.zip)

**Comment by jcmanke** [comment]
I doubt your TabbedPage has anything to do with it, it's just IsShowingUser = true on the map.

**Comment by jcmanke** [comment]
Also, it's stated in the [Google API docs](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#setMyLocationEnabled(\)) that you must have location permissions to show the user location on the map, unless you specify a custom location source.

**Comment by davefxy** [comment]
I use the same code on a contentpage instead of a tabbedpage and I do not get the error. I have the permissions set in the sndroid manifest file.

**Comment by davefxy** [comment]
Now I cannot recreate this bug. I believe it is not a bug.
