### ISSUE TITLE
SearchBar not visible in iOS 10 when using CenterAndExpand

### ISSUE THREAD

**Issue by dannypease** [xamarin/Xamarin.Forms#2139]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
The Xamarin Forms SearchBar does not appear when using iOS 10. It appears to be fine on iOS 11. Adding HeightRequest does not seem to work
### Steps to Reproduce

1. Add a SearchBar to a Xamarin Forms Content Page
2. Run an iOS simulator or device in iOS 10.3
3. SearchBar is not visible

### Expected Behavior
SearchBar should appear
### Actual Behavior
SearchBar does not appear
### Basic Information

- Version with issue: iOS 10.3
- Last known good version: iOS 11.2
- IDE:
- Platform Target Frameworks: 
  - iOS:  10.3
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
The SearchBar appears to work as expected on the control gallery app running against master and I also cannot reproduce the behavior with a basic project running on a 10.3 simulator and the latest prerelease. We'll need a reproduction project we can run in order to investigate further.

**Comment by dannypease** [comment]
Thanks for your input Paul.

The issue was due to having a HorizontalOptions="CenterAndExpand" on the SearchBar. 
Strange as the SearchBar does not show in 10.3 with the Horizontal Options added but it works fine in 11.2. Also if you change the Horizontal Options to FillAndExpand it works fine in both versions.

Dan

**Comment by pauldipietro** [comment]
Thanks for the info on the CenterAndExpand
