### ISSUE TITLE
[UWP] fails to show context menu of a list view item 

### ISSUE THREAD

**Issue by FrankChen021** [xamarin/Xamarin.Forms#2142]
### Description

on UWP, context menu of a list view item cell won't be opened if the mouse is clicked outside any children controls of that cell

### Steps to Reproduce

1.  open the `interactivityListView` sample project provided by official [xamarin-forms-samples
](https://github.com/xamarin/)

2.  open the `interactiveListViewCode.cs`, add a button to the ViewCell. the picture below shows the code differences, the right part shows the code we added

![image](https://user-images.githubusercontent.com/6525742/37638431-d7ee9c12-2c47-11e8-95ea-5be40a4aba3d.png)

3.  run the UWP sample project

### Expected Behavior

the APP shows as 
![image](https://user-images.githubusercontent.com/6525742/37636855-5f38bcce-2c3f-11e8-9d57-fd6cc8e5d937.png)

the dotted rectangle shows size of a cell. **it's supposed to show the context menu if the mouse is right clicked at ANY POSITION of this cell because the context menu is associated with this cell** 

### Actual Behavior

unfortunately, **only if we click in the areas of child controls in a cell** (as the red rectangles shown below), the context menu would be showed. if the mouse is clicked in other position of that cell, there's is no context menu.

![1](https://user-images.githubusercontent.com/6525742/37636707-97dae1a2-2c3e-11e8-98ba-3019714bf1e8.png)

if `HorizontalOptions` of Label is set to `FillAndExpand`, the label expands to the whole cell, as the dotted rectangle shown below. So if we click in any position of this rectangle, the context menu DOES SHOW. **but if we click in those red rectangles, it WON'T**

![image](https://user-images.githubusercontent.com/6525742/37636830-2a4d09b6-2c3f-11e8-8edb-f3d0bb5e1561.png)

### Basic Information

- Version with issue: Xamarin Form 2.5.0.280555. I've tested 2.4.0.280, the problem is also there.
- Last known good version:
- IDE: Visual Studio 2017 15.6.3
- Platform Target Frameworks: 
   - UWP:  16299

### Reproduction Link

[interactivityListView.zip](https://github.com/xamarin/Xamarin.Forms/files/1828143/interactivityListView.zip)

**Comment by pauldipietro** [comment]
It appears to occur when using the horizontal orientation on the layout.

**Comment by FrankChen021** [comment]
@pauldipietro whether it's horizontal orientation or vertical orientation makes no difference

why does the original sample project work? it definitely uses vertical orientation. but it works not because that. in vertical orientation, the default value of  `HorizontalOptions ` of controls is `Fill`,  these control stretch to fill the layout horizontally. in most of case, the position where a mouse is clicked inside a cell is in a sub control, so the context menu shows. if you change  value of `HorizontalOptions `to `Start `or `End`, this problem would be easier to reproduce.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
