### ISSUE TITLE
Xamarin.Forms Label won't word wrap inside a Grid

### ISSUE THREAD

**Issue by ddobrev** [xamarin/Xamarin.Forms#2144]
Details at https://forums.xamarin.com/discussion/17488/xamarin-forms-label-wont-word-wrap-inside-a-grid . It might be related to https://github.com/xamarin/Xamarin.Forms/issues/1343 and https://github.com/xamarin/Xamarin.Forms/issues/2137 .

**Comment by pauldipietro** [comment]
Closing this issue as it is incomplete and doesn't follow the template. I would also suggest seeing if the other issues mentioned are directly related and if so add more information to those reports rather than file a new one as it keeps things simplified.
