### ISSUE TITLE
[iOS] Unhandled Exception:  System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#2145]
Unhandled Exception:  System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: index

### Steps to Reproduce

1. Use the attached project
2. Start typing in the "filter crash" entry.

### Expected Behavior
List on the screen filters

### Actual Behavior
App crashes

### Basic Information

- Version with issue: 2.5.1 340284 pre2
- Last known good version: 2.5.0
- IDE: VS2017

### Reproduction Link

[temp.zip](https://github.com/xamarin/Xamarin.Forms/files/1829898/temp.zip)

**Comment by StephaneDelcroix** [comment]
I can confirm the app is crashing

**Comment by PureWeen** [comment]
This looks to be fixed on 3.0 pre4
