### ISSUE TITLE
ObservableCollection doesn't work in Binding context  when listview bind locally.

### ISSUE THREAD

**Issue by Parmendrakumar** [xamarin/Xamarin.Forms#2149]
### Description:  I have a chat application and when I have click to send button then message goes to firebase server then after 4 second update my listview i am using ObservableCollection,
But I want to show my send message immediate on list view Because sender user cant want his own message for bind in list. So I have bind send message locally
But Now I listview doesn't bind recieve message, means ObservableCollection  collection doesn't work.

### Steps to Reproduce

1. Open attached message in VS and Deploy to two different devices. Open ChatPage.XAML.cs
2. Send message from one device.  
Observed that On device One message bind immediate in list view and On devive two messsage recieve after 3 second.
3.  Message send from Device Two then I doesn't recieve any message. 

Actual Result: Never recieve message from server to any of device.

### Basic Information
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
Xamarin.forms 2.5.0

### Reproduction Link

https://drive.google.com/open?id=1tx-aXAThQ_Bs7VaPYEzvyUSX7ltSSMoE

**Comment by pauldipietro** [comment]
The general behavior appears to occur with the message being received from the second device (tested with an Android device -> iOS sim) but further investigation will need to be made to determine if there's specifically a Forms problem or not.

**Comment by StephaneDelcroix** [comment]
I'm not sure i understand this, and as @pauldipietro says, it's unclear if it's a forms problem or not.

Could you isolate your issue in very simple scenario (that doesn't involve clients or servers) ? Then attach it to this ticket, and reopen it ?

Thanks
