### ISSUE TITLE
[VisualStateManager] "Focused" does not behave correctly.

### ISSUE THREAD

**Issue by P3PPP** [xamarin/Xamarin.Forms#2157]
### Description

The common visual state "Focused" does not behave correctly.

### Steps to Reproduce

use Xamarin.Forms 3.0.0-pre2

```
<Entry Placeholder="IsFocused: true = Orange, false = Green" >
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroupList>
            <VisualStateGroup x:Name="CommonStates">
                <VisualState x:Name="Normal">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="Green" />
                    </VisualState.Setters>
                </VisualState>
                <VisualState x:Name="Focused">
                    <VisualState.Setters>
                        <Setter Property="BackgroundColor" Value="Orange" />
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateGroupList>
    </VisualStateManager.VisualStateGroups>
</Entry>
```

### Expected Behavior

When Entry is focused it's BackgroundColor set to Green, and When Entry is not focused it's BackgroundColor set to Orange.

### Actual Behavior

When Entry is focused it's BackgroundColor set to Orange, and When Entry is not focused it's BackgroundColor set to Green.

### Basic Information

- Version with issue: 3.0.0.296286-pre2
- Last known good version: nothing
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - all

### Reproduction Link

https://github.com/P3PPP/CommonStatesFocusedReproduction

**Comment by hartez** [comment]
Fixed by PR #2158. Thanks, @P3PPP !
