### ISSUE TITLE
[Android] System.ObjectDisposedException in Android.FastRenderers.ImageRenderer

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#2164]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

Rarely, I'm getting an `ObjectDisposedException` in `FastRenderers.ImageRenderer.OnElementChanged`.

### Steps to Reproduce

Unknown. I haven't been able to reproduce this myself. It has happened 5 times out of about 500 app sessions (about 16 hours).

### Expected Behavior

No crash.

### Actual Behavior

Crash.

### Basic Information

- Version with issue: 2.5.1.340284-pre2
- Platform Target Frameworks:
  - Android: 8.0
- Android Support Library Version: 26.0.2
- Nuget Packages:
- Affected Devices:
  - Android 5.1 and Android 6.0

```csharp
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.ImageRenderer'.
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
View.set_Elevation (System.Single value)
ElevationHelper.SetElevation (Android.Views.View view, Xamarin.Forms.VisualElement element)
ImageRenderer+<OnElementChanged>d__9.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.adecb630-c0ed-4109-aa56-c3d78da618d2(intptr,intptr)
```

It seems adding a disposed check here would fix it, but I don't know if this is a sign of something else being wrong:

https://github.com/xamarin/Xamarin.Forms/blob/5917ae180e0184f8e72484e6f43433d289c081b3/Xamarin.Forms.Platform.Android/FastRenderers/ImageRenderer.cs#L72

**Comment by pauldipietro** [comment]
Please let us know if you find a way to provide a reproduction scenario so we can investigate further.

**Comment by GalaxiaGuy** [comment]
I think I've worked out how to recreate it, although it will take me a little while to get a clean version. The summary is as follows:

- I have an image that is slow to load. I'm faking it with a URL of https://httpbin.org/delay/10 -  in my real situation it isn't actually anywhere near this slow, explaining why it happens so rarely and only on low end or older devices.
- The image is inside a `DataTemplate` that gets it content recreated.
- If this happens before the image has loaded, _sometimes_ the exception is thrown.

The exact trigger for the `DataTemplate` content creation might not be supported use case (I'm switching content based on screen size and/or orientation) but it could probably happen with a `ListView`.

I will see how simple I can get it.

Incidentally, I had a look at the code and it seems everything in `OnElementChanged` before the crash (`UpdateAspect` and `EnsureId`) has a disposed check.

**Comment by GalaxiaGuy** [comment]
After trying for a while, I could not get it to happen at all with a `ListView`.

However, when I said "sometimes the exception is thrown" in my test, I was apparently overstating the situation - it only happened once. I think the issue is probably only triggered by very precise unlucky timing.

I believe in my case I can avoid it by handling my data templates differently. But I still think the disposed check is a good idea.

**Comment by PureWeen** [comment]
@GalaxiaGuy   agreed

I have a pull request for a new control ImageButton
https://github.com/xamarin/Xamarin.Forms/pull/1974

Where I generalized that behavior and added a check for that IsDisposed before setting the elevation

**Comment by jurzer** [comment]
I get the same error all the time. `ListView` with multiple rows. In the `DataTemplate` `ListView` nested another `ListView` with a `DataTemplate` which has an image, the image is loaded from the URL. Obviously, when you quickly scroll through the list, the images do not have time to load and the application crashes with this error.

Xamarin Forms: 4.4.0.991265+398-sha.ee1eca51d-azdo.3306453
Platform Target Frameworks: Android 9.0
Android Support Library Version: 28.0.0.3
Affected Devices: Android 8.1
