### ISSUE TITLE
enable source link support

### ISSUE THREAD

**Issue by ctaggart** [xamarin/Xamarin.Forms#2165]
You can simplify debugging of Xamarin.Forms significantly by enabling source link support. Current process:
https://blog.xamarin.com/debugging-xamarin-forms/

A video example of what it should be like:
https://youtu.be/gyRGhCQPkB4?t=1m

Source link support will need to be enabled in the debugger too. VS 2017 & VS Code have support.

**Comment by MagicAndre1981** [comment]
any update? @ctaggart please create a pull request that adds it, so that this gets included very soon.

**Comment by MagicAndre1981** [comment]
btw can you @ctaggart  create a sourcelink version of 2.5.1.444934 and publish it on your MyGet feed until the official version is out? 

i get an exception and would like to set a breakpoint to see more details:

```
Exception thrown: 'System.Reflection.TargetException' in Xamarin.Forms.Platform.UAP.dll
System.Reflection.TargetException: Exception of type 'System.Reflection.TargetException' was thrown.
   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by ctaggart** [comment]
@MagicAndre1981 No, this is not something that I need for any of my paid contract work, which is all I have time more right now. If you need it, make it.

**Comment by PureWeen** [comment]
Android/iOS debug tooling currently doesn't support SourceLink
This would currently only work for UWP/WPF

**Comment by samhouts** [comment]
Closing this for now. We can revisit it when it is supported by Xamarin.iOS and Xamarin.Android. Thank you!

**Comment by samhouts** [comment]
I think it's about time we revisit... https://github.com/mono/mono/pull/12403

**Comment by MagicAndre1981** [comment]
@samhouts when will this ship? What is vNext+1? 4.3?

**Comment by jfversluis** [comment]
Yes, this will be 4.3 but then it will still need support on the IDE. It should be around the same time, but not guarantees. At least we will be ready! :)

**Comment by MagicAndre1981** [comment]
ok, so this require changes to Xamarin.Android and VS? So we need 16.3/16.4? Currently I'm still at 2017 15.9.x
