### ISSUE TITLE
2.5 pre3 buttons are too big and without rounded corners, shadow On Android

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#2170]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Something changed with the shape of buttons. see the screen shots below. 
### Steps to Reproduce

1. add button
2. and compare with latest 2.5 stable and pre3
3. 

### Basic Information

- Version with issue:
- Last known good version:2.5.0280555
- IDE:Visal studio 2017
- Platform Target Frameworks: 
 
  - Android:  Test with 6.1 and 7.1 on device and emulator
 
- Android Support Library Version:  26.1
 

### Screenshots

2.5 pre3

![image](https://user-images.githubusercontent.com/10422347/37825835-7b3d6664-2e91-11e8-9cd1-9d9648676822.png)

2.5.0280555

![image](https://user-images.githubusercontent.com/10422347/37826187-bfa4195a-2e92-11e8-9650-2ad9bef3ecce.png)

**Comment by pauldipietro** [comment]
I believe this is related to #1954.

**Comment by EmilAlipiev** [comment]
@pauldipietro it is actually other way around but if I understand correctly, you reverted changes of 2.5.0280555 and default buttons dont style dont apply on android. we should do it ourselves?

**Comment by samhouts** [comment]
@EmilAlipiev We didn't not revert the changes, but they are now opt-in. I know you saw my comment on #1935, but in case someone else hits this issue, I wanted to leave a breadcrumb here for them to follow. Thanks! :)
