### ISSUE TITLE
iOS: Navigating back from page with HasNavigationBar=false resizes page incorrectly

### ISSUE THREAD

**Issue by shnaz** [xamarin/Xamarin.Forms#2178]
### Description
We have a problem where the content of a page(1) WITH NavigationBar is cut off at the bottom when navigating BACK from a page(2) WITHOUT NavigationBar. Seems like the page is incorrectly updating its size on reappearing based on the old value of NavigationBar.HasNavigationBar.
I am setting the property in the constructor like this:
```
		public Page2()
		{
			InitializeComponent();
			NavigationPage.SetHasNavigationBar(this, false);
		}
```

### Steps to Reproduce

1. You have Page1 with a NavigationBar. 
Page1 has two Labels. LabelA FillAndExpands and LabelB is 70 pts in height.
2. Push Page2 with no NavigationBar, HasNavigationBar=false
3. Now pop Page2 and witness that LabelB is cut off

### Expected Behavior
Page1 shows the whole content on reappearring
### Actual Behavior
Page1 content is cut off by the same amount of height as the iOS NavigationBar.

### Basic Information

- Version with issue:
- Last known good version: -
- IDE: 
Visual Studio For Mac 7.4
- Platform Target Frameworks: 
 iOS: 11.2
- Nuget Packages: 
Xamarin.Forms 2.5.0.280555
- Affected Devices:
iPhones
iPads
iOS Simulators

### Screenshots
![hasnavigationbarerrordemo](https://user-images.githubusercontent.com/6933856/37865233-d8c4c730-2f79-11e8-89d4-53aa76d5e034.gif)

### Reproduction Link

[NavigationBarErrorSample.zip](https://github.com/xamarin/Xamarin.Forms/files/1844478/NavigationBarErrorSample.zip)

**Comment by alickmail** [comment]
I got the same problem too

**Comment by PureWeen** [comment]
Hey @shnaz  thanks for the great bug report

Can you test against
*2.5.1.392594-pre3*

Let me know if you still have the issue?

I ran your sample against *2.5.0.280555* Saw the issue and then upgraded to *2.5.1.392594-pre3* and it seems to be fixed.

Please re-open if this doesn't appear to be fixed in pre3

**Comment by shnaz** [comment]
Hi @PureWeen 

Great! I can confirm that the issue is resolved with _2.5.1.392594-pre3_.
Do you know when to expect this change to be released?

**Comment by shnaz** [comment]
Same as this issue: [https://github.com/xamarin/Xamarin.Forms/issues/1426](url)

**Comment by PureWeen** [comment]
Should be soon just has to go through a few more screenings. So if those all pass then it should be soon
