### ISSUE TITLE
FadeTo(double opacity, uint length) does not work

### ISSUE THREAD

**Issue by Rombersoft** [xamarin/Xamarin.Forms#2179]
### Description
I don't remember version where all worked good but I remember date. It was at November of last year.
I've noticed this for Android and have not checked this for iOS

### Steps to Reproduce

1. Create button
2. Create some event and handler to it
3. In this handler write this code

```
_butAdd.FadeTo(0, 300);
Task.Delay(300).Wait();
_butAdd.IsVisible = false;
```
or
```
 _butAdd.FadeTo(1, 300);
 _butAdd.IsVisible = true;
 Task.Delay(300).Wait();
```
### Expected Behavior
Button must achieve or bunk slowly
### Actual Behavior
But it achieves or bunk instantly
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  not checked
  - Android: some
  - UWP:  not checked

- Nuget Packages: Last stable
- Affected Devices: Visual Studio emulator and real Huawei Honor 8 Lite

**Comment by PureWeen** [comment]
calling *.Wait* on the task and also not awaiting the *FadeTo* won't really cause this to work as intended. The Wait will freeze the UI Thread so you won't see any fade effects happening since the UIThread is blocked. After the Wait expires then it will just be made InVisible..

My guess of why you are seeing different behavior is that something with the FadeTo was probably made to be a bit more async (which is better)

You'll want the code to be more like this
```
 private async void BtnClickMe_Clicked(object sender, EventArgs e)
        {
            await btnClickMe.FadeTo(0, 300);
            btnClickMe.IsVisible = false;
        }
```

**Comment by Rombersoft** [comment]
My event handle was with async keyword. And rarely this worked. And UI thread was not frozen. If something was changed in new version of Xamarin.Forms that you say about it.

**Comment by Rombersoft** [comment]
No no no. Issue can not be closed. I've tried your advice but found out new problem. I have two buttons and firstbutton must achieve slowly and second button must bunk slowly. Actions with both buttons must happen simultaneously and in older xamarin forms version so was. But in new version I've noticed today that at start first achieved fully and than second button began to bunk. What can I do that my buttons achieve and bunk simultaneously??? Please example code
