### ISSUE TITLE
[Enhancement] Add ItemFocused/ItemUnfocused event to ListView

### ISSUE THREAD

**Issue by rookiejava** [xamarin/Xamarin.Forms#2181]
## Rationale

`ListView` currently  has no events to detect whether an item receives foucs or loses focus. Especially, considering the case of using an extenral input device (e.g. remote controller) such as TV, `ItemFocused` and `ItemUnfocused` are necessary for providing better user experience.

## Implementation

Add `ItemFocused` and `ItemUnfocused` events to the `ListView`

```cs
public event EventHandler<ItemFocusEventArgs> ItemFocused;
public event EventHandler<ItemFocusEventArgs> ItemUnfocused;
```
```cs
public sealed class ItemFocusEventArgs: EventArgs
{
	public ItemFocusEventArgs(object item)
	{
		Item = item;
	}
	public object Item { get; private set; }
}
```

## Backward Compatibility

This is a brand new events, so there should not be any backward compatibility issues.

**Comment by PureWeen** [comment]
Can the developer just use the focused features of the view inside the listview itself? 

If there's a remote control each element would have a focused event that it could react to and change how it looks or do whatever?  There's also a Visual State Manager that can be used to apply different styles based on the focused state
https://xamarinhelp.com/visualstatemanager-xamarin-forms-phase-1/

There are a few ways someone can interact with items and surfacing all of these from the ListView might get a bit excessive

**Comment by rookiejava** [comment]
I am talking about the perspective of navigating menu items. On the TV, unlike mobile environment, moving the focus itself can be considered as an item changed. Of course, there are `ItemSelected` and `ItemTapped` in existing ListView as a event.  These are similar, but a little different.

 Events | Mobile | TV
---|---|---
`ItemSelected` | Touch (or click) an item  | Press 'OK' button
`ItemTapped` | Touch an item | Touch an item (only touch screen TV available)
`ItemFocused` | Touch (or click) an item | Press arrow (Up/Donw/Left/Right) key

**Comment by jassmith** [comment]
Moved to enhancement board so its not lost in triage

**Comment by AwsomeCode** [comment]
This is useful for normal application as well. Eg. Like adding new invoice item in list. And remove the last empty option if list not focus.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
