### ISSUE TITLE
[WPF] FontFamily Assignment in platform specific project don't work

### ISSUE THREAD

**Issue by mohamedsaif** [xamarin/Xamarin.Forms#2187]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

For all controls with FontFamily - setting it to a CUSTOM font   defined in the platform specific project does not work in Xamarin.Forms.WPF

### Steps to Reproduce

1. Set a custom FontFamily in Xamarin.Forms.WPF project 

### Expected Behavior
Custom FontFamily will take effect 

### Actual Behavior
Ignored 

### Basic Information

- Version with issue: Xamarin.Forms.WPF
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - WPF

**Comment by mohachouch** [comment]
Hi, Can you join a reproduction project. Thanks

**Comment by mohamedsaif** [comment]
[XF.IssuesApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1904658/XF.IssuesApp.zip)

Attached is the reproduction project to clarify the issue
