### ISSUE TITLE
[WPF] Modal Page Transperancy doesn't work

### ISSUE THREAD

**Issue by mohamedsaif** [xamarin/Xamarin.Forms#2188]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Popping a Modal Page from a MasterDetailView isn't transparent even though I'm setting it to transparent in both the NavigationPage, and the ContentPage inside it

### Steps to Reproduce

1. Pop a modal page from MasterDetailView in either NavigationPage or ContentPage

### Expected Behavior
Transparency setting to be honored 

### Actual Behavior
Modal is not transparent

### Basic Information

- Version with issue: Xamarin.Forms.WPF
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
    - WPF
- Affected Devices:
   - Windows Devices

**Comment by mohachouch** [comment]
Hi, Can you join a reproduction project. Thanks

**Comment by jassmith** [comment]
Modals do not overlay previous content, they replace it wholesale, this is expected. Prior content is entirely unloaded.

**Comment by mohamedsaif** [comment]
[XF.IssuesApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1904652/XF.IssuesApp.zip)

Attached is the reproduction project to clarify the issue
