### ISSUE TITLE
[WPF]  Placeholder property doesn't work

### ISSUE THREAD

**Issue by mohamedsaif** [xamarin/Xamarin.Forms#2189]
### Description
Placeholder Property on Entry doesn't work on Xamarin.Forms.WPF

### Steps to Reproduce
1. set the Placeholder property on an Entry control

### Expected Behavior
Placeholder text to be displayed
### Actual Behavior
No placeholder text is displayed after setting the property
### Basic Information

- Version with issue: Xamarin.Forms.WPF
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
   - Xamarin.Forms.WPF
- Affected Devices: Windows Devices

**Comment by mohachouch** [comment]
Hi, Can you join a reproduction project. Thanks

**Comment by mohamedsaif** [comment]
[XF.IssuesApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1904666/XF.IssuesApp.zip)

Attached is the reproduction project to clarify the issue
