### ISSUE TITLE
[WPF] Custom Controls 2-way binding doesn't work

### ISSUE THREAD

**Issue by mohamedsaif** [xamarin/Xamarin.Forms#2190]
### Description
Custom Controls 2-way binding doesn't work (Xamarin.Froms.WPF). Works only for getting the value (not writing it back)

### Steps to Reproduce
Create a custom control in the Xamarin.Forms project with bindable property. Add the custom control to a view that uses it and bind custom property with TwoWay binding. Run the WPF project that include the new custom control

### Expected Behavior
2-way binding should work (read/write)
### Actual Behavior
it only binds the Get not the Set

### Basic Information

- Version with issue: current nightly build of (Jul 2017) Xamarin.Forms.WPF
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: \
    - Xamarin.Froms.WPF
- Affected Devices:
    - Windows Devices

**Comment by mohachouch** [comment]
Hi, Can you join a reproduction project. Thanks

**Comment by mohamedsaif** [comment]
@mohachouch can you elaborate what is needed from myside?

**Comment by mohachouch** [comment]
@mohamedsaif Just a small reproduction project

**Comment by mohamedsaif** [comment]
[XF.IssuesApp.zip](https://github.com/xamarin/Xamarin.Forms/files/1904654/XF.IssuesApp.zip)

Attached is the reproduction project to clarify the issue

**Comment by samhouts** [comment]
@mohamedsaif I assume that you are referring to Issue 7 in this sample project, which you have marked as fixed. And I confirm that it appears fixed:

![image](https://user-images.githubusercontent.com/7827070/38889643-2b7242ec-4234-11e8-9dd9-8d4c1440bb08.png)


Is this still an issue?

Thanks

**Comment by pauldipietro** [comment]
Closing as we've had no response for over a month. Please reopen with more information and a reproduction if necessary.
