### ISSUE TITLE
Xamarin forms master detail page has few issues in Xamarin Mac.

### ISSUE THREAD

**Issue by fazil1987** [xamarin/Xamarin.Forms#2195]
### Description

1.  Master detail page Menu icon is not getting displayed at all ( irrespective of having the icon in both resources as well as in image sets ).
2. Master page is not hidden by default.
3. Screen flickers for every navigation that happens through the click of the option

### Steps to Reproduce

1. Create a empty Xamarin forms application in VS2017 of windows  
2. Add a master detail page using the template
3. Make that page as a start up page by setting the App main page to masterDetailPage
4. Create a Xamarin mac application in VS for mac
5. Make the necessary changes to integrate with Xamarin forms application.
    Changes mentioned here : https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/
6. Add the appropriate image sets in asset.xcasettes folder 
7. When you run the app in VS for mac , the master detail page shows up.
     
### Expected Behavior

1. Menu icon should appear 
2. Master page should be hidden by default.
3. Screen should not flicker for every navigation that happens through click of the options. ( should have smooth navigation )

### Actual Behavior

1. Menu icon not appearing 
2. Master page is presented by default.
3. On clicking the menu options, detail page loads with flickering effect

**Note : It doesn't flicker in Full Screen mode**

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version:
- IDE: Visual studio as well as Visual studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - Mac : 4.2.0.20
- Android Support Library Version: 
- Nuget Packages:
<packages>
  <package id="Plugin.Multilingual" version="1.0.2" targetFramework="xamarinmac20" />
  <package id="Xamarin.Forms" version="2.5.0.280555" targetFramework="xamarinmac20" />
</packages>
- Affected Devices:
Mac OS 
### Screenshots
<img width="926" alt="screen shot 2018-03-26 at 12 21 29 pm" src="https://user-images.githubusercontent.com/7386648/37950564-9bdac9de-31b6-11e8-864e-37d81deee7eb.png">

**Comment by chamons** [comment]
Originally from: https://forums.xamarin.com/discussion/comment/325204#Comment_325204

FYI @rmarinho

**Comment by rmarinho** [comment]
Hey 1 and 2 are the default behaviors, since this is Desktop version, it shows as slipt and without the toggle button.

3 seems a bug i will take a look.

**Comment by fazil1987** [comment]
Thanks @rmarinho

**Comment by fazil1987** [comment]
Hi @PureWeen, is there any info that you need from my end ? 

I think following details would be helpful. 

**Mac Version :** Mac OS Sierra ( 10.12. 6 )

**Giffy Image :** 
![flickering_issue](https://user-images.githubusercontent.com/7386648/38185014-729fb34c-3669-11e8-9ec4-bcf5106913bf.gif)

**Comment by ShahroozAnsari** [comment]
can i ask when this problem solve? I start a project base on it :|

**Comment by Papirosnik** [comment]
In my case, when I set Title property for the pages, I'd say it is not flickering of entire window.
It looks like caption twitching.
When you switch items,  caption bar disappears and appears again with new title on it.
Anyway, it looks a bit ugly.
Please fix ASAP!

**Comment by JunielKatarn** [comment]
Currently, I get a different effect.
Following a sample app shown here https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/MasterDetailPage , the Mac variant crashes when clicking on the (navigation) menu, throwing a NullPointerException from Main.cs.

Is there a relevant unimplemented API on macOS that we need to know about?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
