### ISSUE TITLE
Entry + Focus + Animation

### ISSUE THREAD

**Issue by rudacs** [xamarin/Xamarin.Forms#2196]
### Description

I'm facing a problem with animation.
I have a search field that will stay in the header. And it is displayed (Animation) when I click on a button. But I also need to focus on the field so the keyboard can appear.
Only by doing this the animation hangs.
If I take the focus it works normally.
In the last step (gif) I click off to disappear with the keyboard before clicking to perform the animation and it works normally.

### Steps to Reproduce

```
public class App : Application
{
    public App()
    {
        var entry = new Entry()
        {
            Placeholder = "Search..."
        };

        var button = new Button()
        {
            Text = "Show/Hide",
            BackgroundColor = Color.Red,
            TextColor = Color.White
        };

        button.Clicked += async (sender, e) => 
        {
            if (entry.Opacity == 1)
            {
                entry.Unfocus();
                await entry.TranslateTo(0, -100, 250, Easing.CubicOut);
                entry.Opacity = 0;
            }
            else
            {
                entry.Opacity = 1;
                entry.Focus();
                await entry.TranslateTo(0, 0, 250, Easing.CubicOut);
            }
        };

        var content = new ContentPage
        {
            Title = "Test Animation",
            Content = new StackLayout
            {
                Margin = new Thickness(20, 100, 20, 20),
                Spacing = 20,
                Children =
                {
                    entry,
                    button
                }
            }
        };

        MainPage = new NavigationPage(content);
    }
}
```

### Expected Behavior

Animation occurs without crashes.

### Actual Behavior

Animation is not fluent. It freezes.

### Basic Information

- Version with issue: 2.5.0.280555
- IDE: VS for Mac 
- Platform Target Frameworks:
  - iOS:  11.2.6
- Nuget Packages: Basic setup test
- Affected Devices: Many iPhone

### Reproduction Link

![ezgif-6-534e47a4af](https://user-images.githubusercontent.com/2153223/37971435-4d077faa-31ac-11e8-89fe-77df70ffaa87.gif)

**Comment by rudacs** [comment]
This is not an idea of ​​quality. It will not stay fluid and intuitive to the user. In addition to the opposite, I'll have to wait for the keyboard to exit in order to do the animation.

**Comment by hartez** [comment]
Which device/simulator are you running this on in your gif? I've been testing the attached repro project on devices and simulators, and it seems to work just fine. The closest I can get to the animation hanging is a slight jerkiness the first time it runs on an iPhone 5s sim running 11.4, and after the first animation it's smooth.

 Is there something I'm missing?

[_2196 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2171336/_2196.Repro.zip)

**Comment by samhouts** [comment]
@rudacs We haven't heard from you in 30 days, so we hope that this issue no longer affects you. If it does, please reopen the issue with more information, if possible. Thank you!
