### ISSUE TITLE
List view groups not updating while scrolling is happening IOS - unless run on main thread

### ISSUE THREAD

**Issue by Nixon-Joseph** [xamarin/Xamarin.Forms#2198]
### Description
I have attached a repro the shows the behavior - this is an implementation of an infinite scroll.

The issue is, if the adding of the item group doesn't happen inside a `Device.BeginInvoke...` then the items aren't posted to the screen until all movement in the listview stops and also you're not still touching the screen.

main issue is if I use main thread stuff - then there can be a slight ui lag while it's putting the items in.
if I don't use main thread - then it doesn't scroll smoothly, has to stop in order to update list.

### Steps to Reproduce

1.  have grouped item list view
2.  add items dynamically when last item in list is brought into view
3.  add them not explicitly on main thread

### Expected Behavior
seamlessly add items to list

### Actual Behavior
empty space on bottom of list until all interaction ends, then new data pops in.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: N/A
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - iOS:  

### Reproduction Link

[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/1853978/App3.zip)

**Comment by Nixon-Joseph** [comment]
Has anybody seen this? I'd like to not have to do special iOS logic if possible. It works fine in android without forcing main thread.

**Comment by hartez** [comment]
Looking at your code, you appear to be doing something very different on iOS than on Android/UWP. Does this behavior persist if you handle the list the same way on all the platforms?

(I realize you're handling it differently because of an iOS bug - what happens if you update to the latest nightly build which has a fix for that bug?)

**Comment by samhouts** [comment]
@Nixon-Joseph We haven't heard from you in 30 days, so we hope that this issue no longer affects you. If it does, please reopen the issue with more information, if possible. Thank you!

**Comment by Nixon-Joseph** [comment]
@hartez  Sorry, I didn't receive a notification for previous comment.

I can try updating and testing, but currently the latest Xamarin update has a lot of breaking changes in my application, so it's not a solution I can follow.
