### ISSUE TITLE
[iOS] swiping down the notification window causes the Orientation on ios to get stuck as unknown

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2200]
### Description

Currently on Forms the following code is used to set the orientation
```C#
_notification = UIDevice.Notifications.ObserveOrientationDidChange((sender, args) => CurrentOrientation = UIDevice.CurrentDevice.Orientation.ToDeviceOrientation());
```

If you swipe down the notification bar this will cause the CurrentOrientation to be set to Other and it remain as Other

### Steps to Reproduce

Just swipe down the notification window and observe the value of the CurrentOrientation
```
[0:] Portrait
[0:] Unknown
[0:] Unknown
[0:] Unknown
```

### Expected Behavior
The CurrentOrientation should remain whatever it was before being set to Other 

### Actual Behavior
The CurrentOrientation stays set to Other until you trigger some sort of Orientation change

### Basic Information
  - iOS:  11.2

### Reproduction Link

This is just a native iOS project that I used to indicate the behavior I'm talking about
[Orientation.zip](https://github.com/xamarin/Xamarin.Forms/files/1854481/Orientation.zip)

### Implementation details

Currently thinking this but need to research more

*UIDevice.CurrentDevice* returns UIDeviceOrientation which is more about the Physical device orientation. For example it includes FaceUp and FaceDown

*UIApplication.SharedApplication.StatusBarOrientation* returns UIInterfaceOrientation and remains portrait while the notification window becomes visible and invisible.   

Implement a Platform property for iOS that uses the *StatusBarOrientation* instead of the *UIDeviceOrientation*

Along with this fix might want to change uses of IsPortrait() in the iOS code base to instead check the *StatusBarOrientation* . I noticed in case where you check for IsPortrait() the code will seem to stop working if the notification window is dragged down. 

I found this out when looking at
https://github.com/xamarin/Xamarin.Forms/pull/1984

When I drag the notification window down the pull to refresh code stops working

**Comment by PureWeen** [comment]
From Apple

> Apple Developer Relations
April 4 2018, 9:17 AM
A solution is under investigation.  We will follow up with you again when it is available.

**Comment by PureWeen** [comment]
From Apple
> Apple Developer Relations
June 5 2018, 7:59 AM
We believe this issue is resolved in the latest iOS 12 beta.
Please test with the latest iOS beta. If you still have issues, please update your bug report with any relevant logs or information that could help us investigate.
iOS beta
https://developer.apple.com/download/

**Comment by samhouts** [comment]
I will close this now. Please reopen if you think this is still an issue. Thanks!
