### ISSUE TITLE
[Android] On VS for Mac update the F# Xamarin Forms template to match C#

### ISSUE THREAD

**Issue by knocte** [xamarin/Xamarin.Forms#2203]
### Update

The confusion here comes from the F# templates on VS for Mac using older base classes. F# needs to be updated to match the C# template.

### Description

Using a NavigationPage in an Android&iOS app which has a default icon for both platforms, and without calling `SetTitleIcon` method, makes the default app icon appear on Android, but not on iOS.

### Steps to Reproduce
1. Create a blank XamarinForms app, with Android & iOS projects.
2. Set a default app icon on the Android project. (If you run the app on the emulator you now see the app icon in the background before being opened.)
3. Set a default app icon on the iOS project. (If you run the app on the emulator you now see the app icon in the background before being opened.)
4. Use a NavigationPage instead of a Page.
5. Launch the app in the iOS emulator (result: the first root page of the app doesn't have any icon at the top of the root page). See screenshot #1.
6. Launch the app in Android emulator.

### Expected Behavior
For consistency, you should not see any icon at the top of the page, like in iOS. Because `SetTitleIcon` has not been called in this code.

### Actual Behavior
You can see the app icon also at the top of the root page. See screenshot #2.

### Basic Information

- Version with issue: 3.0 preview
- IDE: VS4Mac 7.4.1 (build 48)
- Xamarin iOS&Android&Mac versions: the current ones in the stable channel.

### Screenshots
<img width="441" alt="screen shot 2018-03-28 at 8 03 09 pm" src="https://user-images.githubusercontent.com/331303/38047589-4c7d6e74-32c3-11e8-9d9d-1fbf136c6c2d.png">

<img width="398" alt="screen shot 2018-03-28 at 8 03 59 pm" src="https://user-images.githubusercontent.com/331303/38047577-4387f032-32c3-11e8-96af-7c6df930b150.png">

### Reproduction Link

Clone [this project](https://github.com/knocte/gwallet/tree/frontend) (and checkout commit dcc6c0c493abf0c7c5d83993fb0c9233dd19f046 ), and run the Droid and/or iOS app.

**Comment by PureWeen** [comment]
I wasn't able to recreate using your steps to reproduce because those produce a different base application than your sample project

Your sample project is based on *FormsApplicationActivity* and not *FormsAppCompatActivity* which is what the newer templates use when creating a blank project

So I don't feel like your sample project quite meshes with the expectation of Forms to arrive at consistent behavior between ios/android

**Comment by PureWeen** [comment]
For me it did
I'd recommend creating a blank forms project and checkout MainActivity, the layouts, and the styles axml that it creates to be all setup for FormsAppCompatActivity

**Comment by knocte** [comment]
@PureWeen it didn't work for me. If I replace FormsApplicationActivity with FormsAppCompatActivity, I get this NullReferenceException:

```
[Mono] Found as '__android_log_print'.
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.InternalSetPage (Xamarin.Forms.Page page) [0x0005e] in D:\agent\_work\6\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:308 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.SetMainPage () [0x00000] in D:\agent\_work\6\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:336 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.LoadApplication (Xamarin.Forms.Application application) [0x0026f] in D:\agent\_work\6\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:132 
[MonoDroid]   at GWalletFrontendXamForms.Droid.MainActivity.OnCreate (Android.OS.Bundle bundle) [0x00014] in /Users/andres/Documents/Code/gwalletFRONTEND/src/GWallet.Frontend.XamForms.Droid/MainActivity.fs:28 
[MonoDroid]   at Android.Support.V4.App.FragmentActivity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x0000f] in <1e89c43d3c7d48b5ba69bfc0b1bdf114>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.8e7aa82b-6ea9-4aa4-85c1-f0f184b0721e(intptr,intptr,intptr)
```

**Comment by knocte** [comment]
I also tried creating a brand new Xamarin.Forms app from the templates, and it still inherits from FormsApplicationActivity, so this is still a bug (at least in the stable channel).

**Comment by PureWeen** [comment]
Yea you'll get that null exception if the tabs and layouts it expects aren't there.  Here's a doc that walks through upgrading the app 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat

As far as why your templates are giving you FormsApplicationActivity and not AppCompat that's a stranger situation. I'm wondering if a plugin or something else is getting in the way of updating those templates or causing it to draw from a different set of templates?

I've attached what gets generated for me using a clean install from the latest VS  for Mac stable channel

[template.zip](https://github.com/xamarin/Xamarin.Forms/files/1864283/template.zip)

**Comment by knocte** [comment]
> As far as why your templates are giving you FormsApplicationActivity and not AppCompat that's a stranger situation

Maybe it's because I'm using F# templates and not C#? We could reopen this bug to track the update of the F# templates :)

**Comment by PureWeen** [comment]
Oh yea :-)  Ok those are still using *FormsApplicationActivity* :-/   let me see where the efforts are on that one and I'll reopen if that's not already in the works somewhere
