### ISSUE TITLE
Font aliasing and color aren't displayed correctly in MacOS without a retina display

### ISSUE THREAD

**Issue by vcx** [xamarin/Xamarin.Forms#2204]
### Description

Font aliasing and color aren't displayed correctly in MacOS without a retina display. They both work well in native code.

### Steps to Reproduce

1. Download the attachment, compile and run on a Mac computer without retina display (or in an older monitor attached to it)

### Expected Behavior

- Colors matching RGB
- Fonts with correct aliasing, or at least in a readable way.

### Basic Information

- Version with issue: 2.5.0
- Last known good version: None released; but nightly solves the color issue.
- IDE: VS 2017 latest
- Platform Target Frameworks:
  - MacOS
- Affected Devices: any MacOS without retina displays

### Screenshots
See attachments color-issue and font-issue.

### Issue details

We are applying RGB colors in Xamarin.Forms, and it works perfectly on UWP, but rather strange on Mac. In fact, the colors on Mac seem lighter than expected. In the picture, last window is the Xamarin.Forms.

Is this an expected behavior? Should we start adjusting Hue, Sat and Luminosity altogether?
Here are the sample codes for both Xamarin.Forms and native applications:

#### Xamarin.Forms
```
    <StackLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <StackLayout x:Name="teste" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="#32d2c8">
            …
        </StackLayout>
    </StackLayout>
```
#### Native
```
                        <subviews>
                            <box >
                                <rect key="frame" x="0.0" y="0.0" width="480" height="270"/>
                                <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                                …
                                <color key="fillColor" red="0.1960784314" green="0.82352941180000006" blue="0.7843137255" alpha="1" colorSpace="custom" customColorSpace="sRGB"/>
                            </box>
```

On the font issue, we are using custom fonts for our application, and we noticed that whenever we use them with a small font size (say 11), they appear to be pixelated and, sometimes, we can barely read it. To demonstrate it, we downloaded one of our fonts (Segore WP Light) and one provided by Apple (SF Pro Display), putting them site-by-side on both Xamarin.Forms and native applications. The result was clear: on the native application, the fonts are rendered perfectly, whereas in Xamarin.Forms they get pixelated (Apple’s font is better rendered, but still presents some cracks and pixels).

However, if we increase the font size (say 14), the problem goes away. Moreover, if we use the Mac system native fonts the problem is not presented. 
So the question is: should we have an additional care for fonts alien to the Mac OS system? Could we solve this somehow in Xamarin.Forms?

Sample code snippet:

#### Xamarin.Forms
```
            <Label FontSize="11" Text="Welcome to Xamarin Forms!" FontFamily="Segoe WP Light" VerticalOptions="Center" HorizontalOptions="Center" TextColor="White" />
            <Label FontSize="11" Text="Welcome to Xamarin Forms!" FontFamily="SF Pro Display" VerticalOptions="Center" HorizontalOptions="Center" TextColor="White" />
```
#### Native
```
                                        <textField horizontalHuggingPriority="251" verticalHuggingPriority="750" fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="sdr-ex-IXh">
                                            <rect key="frame" x="165" y="235" width="149" height="22"/>
                                            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                                            <textFieldCell key="cell" scrollable="YES" lineBreakMode="clipping" sendsActionOnEndEditing="YES" alignment="center" title="Welcome to Xamarin Forms!" id="myO-YS-RLq">
                                                <font key="font" size="11" name="SegoeWP-Light"/>
                                                <color key="textColor" name="controlBackgroundColor" catalog="System" colorSpace="catalog"/>
                                                <color key="backgroundColor" white="1" alpha="0.0" colorSpace="deviceWhite"/>
                                            </textFieldCell>
                                        </textField>
                                        <textField horizontalHuggingPriority="251" verticalHuggingPriority="750" fixedFrame="YES" translatesAutoresizingMaskIntoConstraints="NO" id="3ew-qC-fwm">
                                            <rect key="frame" x="170" y="211" width="139" height="22"/>
                                            <autoresizingMask key="autoresizingMask" flexibleMaxX="YES" flexibleMinY="YES"/>
                                            <textFieldCell key="cell" scrollable="YES" lineBreakMode="clipping" sendsActionOnEndEditing="YES" alignment="center" title="Welcome to Xamarin Forms!" id="f6e-Eh-Wvu">
                                                <font key="font" size="11" name="SFProDisplay-Regular"/>
                                                <color key="textColor" name="controlBackgroundColor" catalog="System" colorSpace="catalog"/>
                                                <color key="backgroundColor" white="1" alpha="0.0" colorSpace="deviceWhite"/>
                                            </textFieldCell>
                                        </textField>
```

I've grouped in a single issue because, after doing some investigation in code and past issues, I believe they're related, but let me know if you prefer to split in two.

X
[POCFonts.zip](https://github.com/xamarin/Xamarin.Forms/files/1857817/POCFonts.zip)
![font-issue](https://user-images.githubusercontent.com/44371/38057211-0cb218ca-32b5-11e8-8eec-2196c4e9b7b4.jpg)
![color-issue](https://user-images.githubusercontent.com/44371/38057212-0cd04b24-32b5-11e8-9999-ebd349710a43.jpg)

**Comment by PureWeen** [comment]
The font parts of this look to be resolved in the latest code base. I tested the Xamarin Forms sample using *SF Pro Display* against master and the font looks good. I then tested against *3.0.0.296286-pre2* and the font no longer looked good.   Once the next pre comes out can you test against that and then update this ticket to see if that resolves your issue?

As far as the background I couldn't quite get that to work where I saw a different background.  Can you attach the native macOS project you are using to cause that behavior? 

Overall I'm thinking this is resolved on the master branch though :-)

**Comment by vcx** [comment]
Just in case, which commit did you use in your test that made fonts work correctly? I'd like to do other tests here.

**Comment by jassmith** [comment]
Moving back over to ready for work and assigning MacOS backend expert :)

**Comment by jassmith** [comment]
As for if this will make it to 2.5.x, nope.

**Comment by vcx** [comment]
@jassmith, @PureWeen: do you know exactly in which commit the font issue was solved? One of the devs in the team here tested on top of latest commit in master today, no luck.

Also, by just reading the description, I'm not sure our case is the same of #2159. Our is more related to font aliasing, not weight... and it's not random.

**Comment by samhouts** [comment]
@rmarinho Please also identify what commit may have resolved the color issue so we can confirm that was done. Thanks!

**Comment by rmarinho** [comment]
Hey the solved the color issue was in commit https://github.com/xamarin/Xamarin.Forms/commit/b8de5564bf05f9086a0d7bc8c33bcce9b38803e4 
you can find it on version 3.0.0 and above.

I have now a setup (non retina mac) i m debugging the issue, will update as soon as as i have a good answer.

**Comment by rmarinho** [comment]
Do you mind for now to test 3.5.0 stable and also turn off font smoothing on the Mac your are trying. 
It seems that works for me...

![screen shot 2019-03-04 at 01 07 05](https://user-images.githubusercontent.com/1235097/53705132-29a10100-3e1a-11e9-9258-71e2599d4dd5.png)
![screen shot 2019-03-04 at 01 06 03](https://user-images.githubusercontent.com/1235097/53705133-2a399780-3e1a-11e9-8544-f9056c3f1f09.png)

**Comment by rmarinho** [comment]
After more investigation i ws able to found this on Apple's documentation 

https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html

```
*Using screen fonts (for font sizes 16 pt and smaller) optimizes text layout for a standard-resolution display. For screen font, text is laid out using integral glyph advancements. Because the higher pixel density on a high-resolution display allows for floating-point glyph advancements even at small font sizes, screen font is no longer required.*Floating-point advancements result in more precise layout, as shown in Figure 1-4, and allows for kerning and ligatures for smaller font sizes. If your app is document-based and supports text editing and layout, you should familiarize yourself with the default text settings. See Adjust Font Settings to Ensure Document Compatibility.
```

This made me test retiring a ScreenFont with different RenderingModes and test the results with several options on Retina and Non Retina with LCD font Smoothing on and off

With LCD font smoothing *ON* with *NON retina mac*

![screen shot 2019-03-04 at 14 59 53](https://user-images.githubusercontent.com/1235097/53748580-809bea00-3e9d-11e9-8967-d2dfadbd240a.png)

![screen shot 2019-03-04 at 15 01 09](https://user-images.githubusercontent.com/1235097/53748579-809bea00-3e9d-11e9-8319-8a6636104b65.png)

![screen shot 2019-03-04 at 15 03 08](https://user-images.githubusercontent.com/1235097/53748577-80035380-3e9d-11e9-88a9-3092e5c4c08d.png)

![screen shot 2019-03-04 at 15 06 35](https://user-images.githubusercontent.com/1235097/53748576-80035380-3e9d-11e9-8839-09a60a0e9231.png)

**Comment by rmarinho** [comment]
With LCD font smoothing *OFF* with NON retina Mac

![screen shot 2019-03-04 at 15 15 43](https://user-images.githubusercontent.com/1235097/53749069-80e8b500-3e9e-11e9-90bf-cc35e2ee1727.png)

![screen shot 2019-03-04 at 15 11 18](https://user-images.githubusercontent.com/1235097/53749093-8d6d0d80-3e9e-11e9-858d-3923cdc5c208.png)

![screen shot 2019-03-04 at 15 09 48](https://user-images.githubusercontent.com/1235097/53749112-9958cf80-3e9e-11e9-8e92-66ae2df4050d.png)

![screen shot 2019-03-04 at 15 08 00](https://user-images.githubusercontent.com/1235097/53749128-a1187400-3e9e-11e9-82dc-99325665a719.png)

**Comment by rmarinho** [comment]
@vcx hey, do you mind test this package and see if it works for you ? 
[debug.zip](https://github.com/xamarin/Xamarin.Forms/files/2927840/debug.zip)
