### ISSUE TITLE
[UWP] Custom Renderer for ActivityIndicator does not appear if in NavigationPage

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2205]
### Description

Replaced the default `ActivityIndicator` with a `ProgressRing` on UWP. The renderer displays perfectly on a `ContentPage`, but when the same page is displayed via a `NavigationPage`, the renderer fails to appear.

### Steps to Reproduce

1. In App.xaml.cs, confirm that `MainPage = new NavigationPage(new ProgressRing.MainPage());` is uncommented. Run.
2. Observe that there is no spinning circle below the Label.
3. In App.xaml.cs, comment `MainPage = new NavigationPage(new ProgressRing.MainPage());` and uncomment `MainPage = new ProgressRing.MainPage();`. Run.
4. Observe that there is now a spinning circle below the Label.

### Expected Behavior

![image](https://user-images.githubusercontent.com/7827070/38058039-4c352376-3296-11e8-80df-36b69babaf04.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/7827070/38058015-32f64606-3296-11e8-96cd-f4d3cfb1ec49.png)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:   
- Android Support Library Version: N/A
- Nuget Packages: 
- Affected Devices:

### Reproduction Link

[ProgressRing.zip](https://github.com/xamarin/Xamarin.Forms/files/1857858/ProgressRing.zip)

**Comment by bojan96** [comment]
I have same issue but with default activity indicator(ProgressBar) on UWP

**Comment by samhouts** [comment]
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/1483

**Comment by mgwalm** [comment]
This is still a problem in forms version 3.0.0.482510.
As stated above it works on a contentpage, but not when one uses a NavigationPage.

I've compared the UWP Visual tree of an app that is using a ContentPage to one that is using a NavigationPage, and on the ContentPage there is a DeterminateRoot (border) as the last child of the FormsProgressBar that has an Animation and Visual State property (ie the storyboard is running). However on the NavigationPage version the  DeterminateRoot (border) is present but the Animation and Visual State property is missing, ie, the storyboard is not running.
