### ISSUE TITLE
PushModalAsync on first run causes ObjectDisposedException for PlatformRenderer in iOS

### ISSUE THREAD

**Issue by robheffo79** [xamarin/Xamarin.Forms#2208]
### Description
I am developing an Android / iOS app that show's data from a client's CRM system. When attempting to show a notification in a popup modal, on iOS there is an ObjectDisposedException thrown. This only occurs when the app is first installed. If the app is being restarted, it does not occur. I have attempted to reproduce the issue in a vanilla project but have been unable to replicate the issue.

There is no issue in Android.

[Exception Output.txt](https://github.com/xamarin/Xamarin.Forms/files/1858621/Exception.Output.txt)

### Steps to Reproduce

1. Create a TabbedPage
2. On ContentPage as a tab, attempt to open another ContentPage as a Modal Popup.

### Expected Behavior
Show a ContentPage as a popup

### Actual Behavior
App crashes with an ObjectDisposedException

### Basic Information

- Version with issue: 2.5.0.280555
- IDE: Visual Studio 2017 v15.6.4
- Platform Target Frameworks:
  - iOS:  11.2
  - Android: 8.1
- Affected Devices: iOS Devices

### Reproduction Link
Source can be provided privately

**Comment by PureWeen** [comment]
@robheffo79   this is a tricky one if you can't boil it down. I tried creating a vanilla project myself and I didn't get any exceptions. I don't see any clues in the stack trace really. Maybe you're pushing a page that's already been disposed? In your project having the issues can you just slim it down to more match the workflow vanilla project you said it's working fine with?

**Comment by robheffo79** [comment]
It's a very strange one. As I said it only affects iOS. I paired the code all the way back to a basic Hello World form and still got the issue.

I am working around it by intercepting the exception, recreating my tab page, then pushing the Modal again. Which then works. If you got some debuggable nugets for Xamarin Forms I would be happy to diagnose and advise

**Comment by PureWeen** [comment]
for that I'd recommend pulling down the source and generate a nuget from that

- git clone https://github.com/xamarin/Xamarin.Forms.git
- msbuild Xamarin.Forms.SLN
- set NUGET_DIR= download a nuget.exe somewhere and specify location here
- .create-nuget.bat

**Comment by jassmith** [comment]
Can you provide the hello world reproduction you worked it down to please?

**Comment by PureWeen** [comment]
If you hadn't tried to yet. Enabling CLR Exceptions is sometimes useful in those cases for breaking at the correct exception point

**Comment by andy200486** [comment]
Hi, I'm having the same problem as you.

I'm using Xamarin Auth to connect via Google. When the authentication is done and ok I do :

`UIViewController.DismissViewController(true, null);`

Then, I click on a button and I'm trying to make a pushmodalasync :

`await Application.Current.MainPage.Navigation.PushModalAsync(navigationPage)`

My app crash with this error :  

```
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'PlatformRenderer'. at Foundation.NSObject.get_SuperHandle () [0x0004a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.16/src/Xamarin.iOS/Foundation/NSObject2.cs:456 at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.16/src/Xamarin.iOS/UIKit/UIViewController.g.cs:2983 at Xamarin.Forms.Platform.iOS.Platform.EndEditing () [0x00051] in <7402bf39df944a9ebf61606e5f9c45a4>:0 at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PushModalAsync (Xamarin.Forms.Page modal, System.Boolean animated) [0x00000] in <7402bf39df944a9ebf61606e5f9c45a4>:0 at Xamarin.Forms.Internals.NavigationProxy.OnPushModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x00022] in D:\a\1\s\Xamarin.Forms.Core\NavigationProxy.cs:212 at Xamarin.Forms.Application+NavigationImpl.<>n__1 (Xamarin.Forms.Page modal, System.Boolean animated) <0x103c59040 + 0x0004b> in <209f66ed8fe04cb6a815feb8c3b62471#9e100c547031591382a60437c9f2f5db>:0 at Xamarin.Forms.Application+NavigationImpl+d__3.MoveNext () [0x00065]
```

If I don't do the : 

`UIViewController.DismissViewController(true, null);`

my app doesn't crash.

Here is the code of the full page for the connection with google in iOS :

```
public class GoogleLoginPageIos : IGoogleLoginPage
  {
    public static GoogleAuthenticator m_auth;
    private static UIViewController viewController;

    public void OnAuthenticationCompleted()
    {
      viewController.DismissViewController(true, null);
    }

    public void OnAuthenticationCanceled()
    {
      viewController.DismissViewController(true, null);
    }

    public void OnAuthenticationFailed()
    {
      viewController.DismissViewController(true, null);
    }

    public void StartAuthentication(Action onStartLogin, Action<Account> onSuccessfullLogin)
    {
      m_auth = new GoogleAuthenticator(onStartLogin, onSuccessfullLogin, this);

      var authenticator = m_auth.OAuth2Authenticator;
      var mainViewController = UIApplication.SharedApplication.KeyWindow.RootViewController;
      viewController = authenticator.GetUI();

      mainViewController.PresentViewController(viewController, true, null);
    }
 }
```
Could someone help me ?

**Comment by aimore** [comment]
I am facing the same issue described originally in this thread.

`{System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'PlatformRenderer'.
  at Foundation.NSObject.get_SuperHandle () [0x00012] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.15/src/Xamarin.iOS/Foundation/NSObject2.cs:449 
  at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.15/src/Xamarin.iOS/UIKit/UIViewController.g.cs:2983 
  at Xamarin.Forms.Platform.iOS.Platform.EndEditing () [0x00051] in <0648e2dffe9e4201b8c6e274ced6579f>:0 
  at Xamarin.Forms.Platform.iOS.Platform.Xamarin.Forms.INavigation.PushModalAsync (Xamarin.Forms.Page modal, System.Boolean animated) [0x00000] in <0648e2dffe9e4201b8c6e274ced6579f>:0 
  at Xamarin.Forms.Internals.NavigationProxy.OnPushModal (Xamarin.Forms.Page modal, System.Boolean animated) [0x00022] in D:\a\1\s\Xamarin.Forms.Core\NavigationProxy.cs:212 
  at Xamarin.Forms.Application+NavigationImpl.<>n__1 (Xamarin.Forms.Page modal, System.Boolean animated) <0x14631a0c0 + 0x00062> in <b1baaea67aeb409ca7e75b039f7cca37>:0 
  at Xamarin.Forms.Application+NavigationImpl+<OnPushModal>d__3.MoveNext () [0x00065] in D:\a\1\s\Xamarin.Forms.Core\Application.cs:401 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Plugin.Popups.PopupPageNavigationService+<DoPush>d__6.MoveNext () [0x000d8] in D:\a\1\s\src\Prism.Plugin.Popups\PopupPageNavigationService.cs:103 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<>c__DisplayClass38_1+<<ProcessNavigationForContentPage>b__0>d.MoveNext () [0x00050] in D:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:454 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<DoNavigateAction>d__45.MoveNext () [0x000da] in D:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:656 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<ProcessNavigationForContentPage>d__38.MoveNext () [0x001a3] in D:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:452 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<ProcessNavigation>d__30.MoveNext () [0x001ca] in D:\a\1\
  s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:329 
--- End of stack trace from previous location where exception was thrown ---
  at Prism.Navigation.PageNavigationService+<NavigateInternal>d__28.MoveNext () [0x000f9] in D:\a\1\s\Source\Xamarin\Prism.Forms\Navigation\PageNavigationService.cs:281 }`

**Comment by PureWeen** [comment]
@aimore can you create a new issue with a repro please?

**Comment by aimore** [comment]
I created a new solution using the same configuration (XF version and etc..), and it worked just fine.
Same with my current project affected with this error, is hard to reproduce because it happens randomly.
The StackTrace as you see does not help much, it is just weird.

**Comment by klogeaage** [comment]
I have the same problem, but when using authentication via AppCenterAuth. Essentially, using that breaks Modal dialogs in Xamarin.Forms. I think I could produce a sample if necessary.
