### ISSUE TITLE
ObjCRuntime.RuntimeException - Failed to compute the token reference for the type

### ISSUE THREAD

**Issue by GribovAlexander** [xamarin/Xamarin.Forms#2209]
### Description

An unhandled exception occurs when running the application referencing a Bindings Library for Xamarin.iOS in certain scenarios.

### Steps to Reproduce

See the included archive.

1. Build "MyFramework" for iOS.
2. Build "MyLibrary" for Xamarin.iOS.
3. Build and run "appTest" application.

### Expected Behavior

When building the same library and running the "appTest" in Visual Studio for mac 7.4 - no runtime errors. 

### Actual Behavior

The following runtime exception occurs in Visual Studio for mac 7.5 preview:

ObjCRuntime.RuntimeException
Failed to compute the token reference for the type 'MyLibrary.IMyDelegate, MyLibrary, Version=1.0.6662.22178, Culture=neutral, PublicKeyToken=null' because the assembly couldn't be found in the list of registered assemblies.

### Basic Information

- Version with issue: Visual Studio for mac 7.5 preview build 933
- Last known good version: Visual Studio for mac 7.4 build 1033
- IDE: Visual Studio for mac 7.5 preview build 933
- Platform Target Frameworks: 
  - iOS:  11.10.0.32

### Reproduction Link

[xamarin_ios_test.zip](https://github.com/xamarin/Xamarin.Forms/files/1859952/xamarin_ios_test.zip)

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-macios/issues/3830
