### ISSUE TITLE
UWP NativeForms - Can't add FrameworkElement to Frame

### ISSUE THREAD

**Issue by jsiemens** [xamarin/Xamarin.Forms#2212]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description

When I try to navigate to a Xamarin Forms page in a UWP frame, it does not work.

I tried using Xamarin Forms 2.5.0.280555 initially. Also tried 2.5.1..392594-pre3 and 3.0.0.296286-pre2. None of them worked.

Example:

`                MainFrame.Navigate(new XamarinFormsPage());`

If I try creating a FrameworkElement and setting that as the content of a ContentControl, it also fails. 

`                Placeholder.Content = new XamarinFormsPage().CreateFrameworkElement();`

It appears to work if you navigate to Xamarin Forms page on the root frame of the Windows (as shown in Xamarin examples). It also seems to work if you set the Content property on your main page (as shown in docs). But it's not very useful to me if I can only use Xamarin Forms pages as full screen (in which case it's not much different than just using Xamarin Forms without Native Forms).

The MainPage.Xaml looks like this:
```
<forms:WindowsPage
    x:Class="NativeFormsTest.UWP.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:forms="using:Xamarin.Forms.Platform.UWP"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NativeFormsTest.UWP"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Page.BottomAppBar>
        <CommandBar>
            <AppBarButton x:Name="back" HorizontalAlignment="Left" Icon="Back" Label="back" VerticalAlignment="Top" Click="Back_Click"/>
            <AppBarButton x:Name="next" HorizontalAlignment="Left" Icon="Forward" Label="forward" VerticalAlignment="Top" Click="Next_Click"/>
        </CommandBar>
    </Page.BottomAppBar>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <StackPanel Orientation="Vertical">
            <TextBlock Text="Header"></TextBlock>
            <Frame x:Name="MainFrame">
                <Frame.ContentTransitions>
                    <TransitionCollection>
                        <NavigationThemeTransition/>
                    </TransitionCollection>
                </Frame.ContentTransitions>
            </Frame>
            <ContentControl x:Name="Placeholder"></ContentControl>
            <TextBlock Text="Footer"></TextBlock>
        </StackPanel>
    </Grid>
</forms:WindowsPage>
```

MainPage.xaml.cs:
```
    public sealed partial class MainPage
    {
        public MainPage()
        {
            this.InitializeComponent();

            MainFrame.Navigate(typeof(Frame1)); // This works
            Placeholder.Content = new Frame1(); // This works too

            //LoadApplication(new NativeFormsTest.App());
        }

        private void Back_Click(object sender, RoutedEventArgs e)
        {
            if (MainFrame.CanGoBack)
            {
                MainFrame.GoBack();
            }
        }

        private void Next_Click(object sender, RoutedEventArgs e)
        {
            Type current = MainFrame.SourcePageType;

            if (current.Name == "Frame1")
            {
                MainFrame.Navigate(typeof(Frame2)); // This works
                Placeholder.Content = new Frame2(); // This works too
            }

            if (current.Name == "Frame2")
            {
                // *** This fails ***
                MainFrame.Navigate(new XamarinFormsPage());

                // *** This also fails ***
                Placeholder.Content = new XamarinFormsPage().CreateFrameworkElement();
            }
        }
    }
```
Frame1.xaml:
```
<Page
    x:Class="NativeFormsTest.UWP.Frame1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NativeFormsTest.UWP"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <TextBlock Text="Frame1"></TextBlock>
    </Grid>
</Page>
```

Frame1.xaml.cs:

```
namespace NativeFormsTest.UWP
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class Frame1 : Page
    {
        public Frame1()
        {
            this.InitializeComponent();
        }
    }
}
```

Frame2.xaml:
```
<Page
    x:Class="NativeFormsTest.UWP.Frame2"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NativeFormsTest.UWP"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <TextBlock Text="Frame 2"></TextBlock>
    </Grid>
</Page>
```

Frame2.xaml.cs:
```
namespace NativeFormsTest.UWP
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class Frame2 : Page
    {
        public Frame2()
        {
            this.InitializeComponent();
        }
    }
}
```

### Steps to Reproduce

I have attached a sample app that demonstrates the problem. The app attempts to load 3 frames. The first two are using standard UWP, and the third frame is trying to load a Xamarin Forms page. The first 2 work, the third one doesn't.

1. Load the attached solution.
2. Run the application.
3. Press the forward arrow button to go to "Frame 2". Press it again to attempt to go to the 3rd frame which is the Xamarin Forms page. 

### Expected Behavior

Third frame loads.

### Actual Behavior

Third frame doesn't load.

### Basic Information

- Version with issue: Xamarin Forms 2.5.0.280555
- Last known good version: None, to my knowledge.
- IDE: VS 2017 15.6
- Platform Target Frameworks: 
  - UWP:  16299 
- Nuget Packages: None, other than default.
- Affected Devices: Windows 10 Fall Creators Update

### Reproduction Link

[NativeFormsTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1862030/NativeFormsTest.zip)

**Comment by adamhewitt627** [comment]
I was thinking about doing something along these lines in a project of mine, and would have jumped on fixing this except it appears to me to work as documented, at least in Xamarin.Forms 4.3. If I understand your issue correctly, [this gist](https://gist.github.com/adamhewitt627/728f20d2dafb3b92f1f75b0ca9ca970b) shows it working.

**Comment by adamhewitt627** [comment]
On a related note, I see some possible issues with the existing implementation:https://github.com/xamarin/Xamarin.Forms/blob/1192deedabdb0fd1eb13243cac1f6ac438afd643/Xamarin.Forms.Platform.UAP/PageExtensions.cs#L7

Because of how the UWP Frame caches Pages, it isn't clear to me how this can possibly support back navigation. I haven't actually tried it yet, but the `Guid` is only added during a forward navigation and removed right away.

#### First Cut
Just a quick shot at more complete handling is something like this. I know this lays out the simple case from the Gist, but I don't know how it works in a larger context.
```cs
public class FormsPageWrapper<T> : Page 
    where T : Xamarin.Forms.ContentPage, new()
{
    private readonly T _page;

    public FormsPageWrapper()
    {
        _page = new T();
        Content = _page.CreateFrameworkElement();
    }
}

//No longer an extension method
_frame.Navigate(typeof(FormsPageWrapper<XamarinPage>));

//TODO - Could be made an extension, but what about .NET Native?
public static void Navigate<TPage>(this Frame frame)
    where T : Xamarin.Forms.ContentPage, new()
{
    var pageType = typeof(FormsPageWrapper<>).MakeGenericType(typeof(XamarinPage));
    frame.Navigate(pageType);
}
```

### Summary

1. The Xamarin.Forms page is constructed during the navigation.
2. What about `DataContext`/`BindingContext`? My projects use view-model first, and I pass the DataContext as the navigation parameter. That doesn't necessarily apply as generally through a construct like this.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
