### ISSUE TITLE
Design assemblies should only target v4.5

### ISSUE THREAD

**Issue by dotMorten** [xamarin/Xamarin.Forms#2216]
### Description
The .Design assemblies are targeting .NET 4.7, but if you use Xamarin.Forms in WPF and target an older version (4.5-4.7) you'll get the following warnings:
```
2>------ Build started: Project: FormsTestApp.WPF, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3274: The primary reference "Xamarin.Forms.Core.Design, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3274: The primary reference "Xamarin.Forms.Xaml.Design, Version=2.0.0.0, Culture=neutral, processorArchitecture=MSIL" could not be resolved because it was built against the ".NETFramework,Version=v4.7" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1".
2>  FormsTestApp.WPF -> c:\apps\dotnet\TestApps\FormsTestApp.WPF\bin\Debug\FormsTestApp.WPF.exe
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 1 skipped ==========
```
### Steps to Reproduce

1. Create a WPF project targeting 4.6.1
2. Reference `Xamarin.Forms.Platform.WPF.3.0.0.296286-pre2` and the dependencies which only requires 4.5.0
3. Build, and observe the above warnings

### Expected Behavior
No warning is generated.

### Actual Behavior
Build warnings

### Basic Information

- Version with issue: 3.0.0.296286-pre2
- Last known good version:
- IDE: VS2017 (15.5.2)
- Platform Target Frameworks: 
  -net461
- Android Support Library Version: 
- Nuget Packages:
```xml
    <PackageReference Include="Xamarin.Forms">
      <Version>3.0.0.296286-pre2</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms.Platform.WPF">
      <Version>3.0.0.296286-pre2</Version>
    </PackageReference>
```
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/1378165/38160384-b6f6d3bc-3471-11e8-8d4f-66ce36cd8744.png)

**Comment by dotMorten** [comment]
Example of offending code: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Design/Xamarin.Forms.Core.Design.csproj#L12

**Comment by jassmith** [comment]
Dupe of #2299

**Comment by jassmith** [comment]
Sorry wrong bug, what a day Im having with that.

**Comment by jassmith** [comment]
Good catch

**Comment by StephaneDelcroix** [comment]
Reopening, as I reverted the PR

**Comment by ysangkok** [comment]
So these warnings do not actually prevent using the assembly, am I right?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by dotMorten** [comment]
@samhouts It goes against the recommendation for .Design assemblies in VS. if Xamarin.Forms for WPF is moving to .NET Core, it might not be a big deal though?

**Comment by samhouts** [comment]
Yeah, I think that since these are just warnings, and we'll want to migrate to .NET Core fully anyway, we can close this. Thanks!!
