### ISSUE TITLE
[Enhancement] CarouselView implementation

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#2219]
Hi colleagues
I saw, that you merged https://github.com/alexrainman/CarouselView project into your repository and it will be standard carousel view of XF.

I want to suggest you to check my implementation of this view that is base on PanGestureRecognizer.

Also my implementation provides opportunities:
a) customizing of animations time/easing etc. (CardsView/CarouselView etc.)
b) customizing carousel indicators (you can use circle view or any Image or what you want)
c) you can manage view via adding them into collection or by setting properties directly (So, your view model will contain 3 properties next/current/previous contexts)

My implementation supports caching views (So, views can be reused)

You can check it here https://github.com/AndreiMisiukevich/CardView

**Comment by AndreiMisiukevich** [comment]
@jassmith Hi
Have you checked it yet?)

**Comment by AndreiMisiukevich** [comment]
@samhouts @jassmith Hi colleagues
Did you check this plugin yet?

Some people propose me to suggest Xamarin team to take my plugin as primary CarouselView.
So, I'm doing it =)

Many people think, that my realization is more stable and flexible you may to check the samples and source code.

I fixed a little naming convention for easier understanding of this plugin.
ItemTemplate, ItemsSource, SelectedIndex, SelectedItem etc.

78 stars (6 mos) and 16 Forks https://github.com/AndreiMisiukevich/CardView/stargazers
The is no active bugs https://github.com/AndreiMisiukevich/CardView/issues only feature requests

And there is active PR for getting carousel preview feature (in development now, there are some bugs still) https://github.com/AndreiMisiukevich/CardView/issues/17

I will be glad to answer you questions

**Comment by Magendanz** [comment]
I switched over to Andrei's version of CarouselView and find it much more stable, especially on Android.  With the switch to the standard naming conventions and addition of SelectedItem, it's much closer to the standard we set when I was developing WPF controls for Windows Surface at Microsoft.

I'd suggest setting him up a feature branch on Xamarin.Forms so he can inherit from ItemsView<TVisual>, then you can better compare and contrast the two implementations.

**Comment by AndreiMisiukevich** [comment]
Added docs section https://github.com/AndreiMisiukevich/CardView/tree/master/docs

**Comment by AndreiMisiukevich** [comment]
If you need further information, please, let me know.

**Comment by shoeIT** [comment]
"There are no active bugs now https://github.com/AndreiMisiukevich/CardView/issues only feature requests"

You have 99 downloads on Nuget of course there are just a few issues, since the plugin is not used very often. I use Alexs CarouselView and I've just tested your control. I have found about 3 issues within minutes. There are some nice features in your CarouselView but compared to this one (https://www.nuget.org/packages/CarouselView.FormsPlugin/) it is still a small child, which needs to be tested a lot to see if it is really stable.

**Comment by AndreiMisiukevich** [comment]
@shoeIT 
"I have found about 3 issues within minutes" 

I will appreciate if you create them on my github project ;)

**Comment by AndreiMisiukevich** [comment]
@samhouts Hey Samantha
What is the status of this issue?

**Comment by samhouts** [comment]
During our initial spike of CollectionView, we realized that many of the same concepts and underlying API apply to CarouselView, too. We're currently exploring the possibility of using CollectionView as a CarouselView (see https://github.com/xamarin/Xamarin.Forms/projects/13#card-12053462). Thanks!

**Comment by AndreiMisiukevich** [comment]
@samhouts so, we can close this ticket, can't we?

**Comment by samhouts** [comment]
We aren’t making any decisions until we evaluate the results of the spike.

**Comment by markmccaigue** [comment]
@samhouts Hi Samantha, I hope you don't mind me bumping this issue, but I was wondering if you folks have had a chance to evaluate the CollectionView-based spike yet?

We're looking at implementing carousel functionality and it would be really appreciated if you could give a steer on the most likely direction of travel for the upcoming 'official' CarouselView if at all possible. Thanks!

**Comment by jassmith** [comment]
The collectionview we are now confident will completely replace the needs of CarouselView. Please feel free to leave any concerns you have on its spec.
