### ISSUE TITLE
[Enhancement] Please add Press and Release GestureRecognizers

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/Xamarin.Forms#2220]
### Description

I came across the need for this issue trying to resolve #1702 (`Button.Padding`).
Based on [this](https://stackoverflow.com/a/36185411/75500) answer, I tried to substitute a `Button` with a `Label`, so that I can get rid of the unwanted Padding forced on `Button` in Android.
My problem is I need to have control on the duration of the click/tap/mouse-touch down.

My suggestion is hereby to introduce two more `GestureRecognizer`s: `PressGestureRecognizer` and `ReleaseGestureRecognizer` that will solve this demand.

### Steps to Reproduce

1. Create a `Button` with a single character (i.e. `+`).
2. Launch the project on Android
3. There is a huge gap (especially horizontal) between the `Button`'s edge and the text it contains. The only way to get rid of it is using custom renderers or substitute it with a `Label`, using `TapGestureRecognizer`.
4. Let's choose `Label`.
5. We can only mimic the `Clicked` event with a `TapGestureRecognizer`, but the `Pressed` and `Released` events of `Button` have no alternatives in `Label` or other controls.

### Expected Behavior
We should be able to have a `Pressed` and `Released` behavior any control.

### Basic Information

- Version with issue: 2.5.0.280555
- IDE: VS 15.6.4
- Platform Target Frameworks: Xamarin.Forms, most specifically Android
### Screenshots

![image](https://user-images.githubusercontent.com/2716316/38172399-56832988-35b4-11e8-9b67-78ec72aab0c6.png)

### Reproduction Link

- #1702 
- [here](https://forums.xamarin.com/discussion/comment/325899)

**Comment by jbachelor** [comment]
Thanks so much in advance for adding the Pressed and Released GestureRecognizers... This will be very helpful in providing just small amounts of animation to give the app a more lively, responsive look and feel for the user. Looking forward to using these.  =)

**Comment by Huaba93** [comment]
I would also very much appreciate a PressGestureRecognizer and ReleaseGestureRecognizer. 
You could also add a Pressed & Released Event/Command to TapGestureRecognizer.

**Comment by AdamDiament** [comment]
Yes please!

**Comment by PureWeen** [comment]
Closed in favor of
https://github.com/xamarin/Xamarin.Forms/issues/3492
