### ISSUE TITLE
 The missing file is ..\..\packages\Xamarin.Forms.2.5.0.280555\build\netstandard1.0\Xamarin.Forms.props.

### ISSUE THREAD

**Issue by SatyaRamprasad** [xamarin/Xamarin.Forms#2226]

**Comment by PureWeen** [comment]
?

Can you provide a little more information?

If you 
- close your project
- delete bin/obj
- delete package directory

Does that fix?
Or can you attach a sample of the project you are having issues with?

**Comment by jassmith** [comment]
You have an invalid unpack or need to restart your IDE. Either way closing due to lack of response.
