### ISSUE TITLE
 [UWP] MasterPage - Blank Area below Popover menu the *second* time you show it

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#2228]
Migrated from bugzilla, this is still happening as of version 2.5.0.280555
https://bugzilla.xamarin.com/show_bug.cgi?id=60106

Screenshot
https://bugzilla.xamarin.com/attachment.cgi?id=25259

Visual Studio 2017 solution that reproduces the issue
https://bugzilla.xamarin.com/attachment.cgi?id=25258

----------

This may be related to:

Bug 54036 - [UWP] MasterPage - Bad Rendering
https://bugzilla.xamarin.com/show_bug.cgi?id=54036
  
[UWP] Correctly calculates height of Master Page content #953
https://github.com/xamarin/Xamarin.Forms/pull/953

How to remove space in MasterDetailPage Master in xamarin Forms - UWP?
https://stackoverflow.com/questions/44385234/how-to-remove-space-in-masterdetailpage-master-in-xamarin-forms-uwp

I'm using Visual Studio 2017 15.3.5 and Xamarin.Forms 2.4.0.282 on Windows Anniversary Edition.

I have a MasterDetailPage at the root of my UWP application, where the MasterBehavior is set to Popover and the Detail page is a Navigation page.  The *second* time I click the upper-left hamburger icon to display the menu, the height of the page is truncated such that there's a blank space the height of the title bar at the *bottom* the page.  It's almost like the height of the title bar is being subtracted from the height of the Master page twice.

I've attached a screenshot and a Visual Studio 2017 solution that reproduces the issue.  All of the relevant Xamarin.Forms code is in App.xaml in the .Net Standard project.

Please note you have to open the menu a *second* time to reproduce the issue, so just running the application and opening the menu once won't be enough.

**Comment by jassmith** [comment]
Confirmed happens in 3.0.0

**Comment by aneti9862** [comment]
Xamarin.Forms: 3.0.0.446417

The problem is still not fixed (when the size of page is changed or if you click on the hamburger button second time.

![masterdetailpage](https://user-images.githubusercontent.com/32899557/41218420-4d597c0c-6d5b-11e8-8952-f773001a102a.png)

**Comment by jalbertSyncroTech** [comment]
Just confirming that the original issue, where you show the Popover a second time is fixed.  There is still an issue when you resize, but for my purposes the original issue has been resolved.
