### ISSUE TITLE
DidReceiveRemoteNotification fires when app running on foreground. 

### ISSUE THREAD

**Issue by skulshresthazc** [xamarin/Xamarin.Forms#2232]
### Description
We have Implemented PN for Xamarin.Forms Application using Azure Notification Hub.

### Actual Behavior
In IOS\Android if notification gets fired and application is running in foreground, it's directly landed on desired screen, if in any case user receives notification that is redirecting to page 2 and user is on page 1, then page2 is navigated and this behavior is inconvenient for the user as the user is working on page1 and upon receiving the notification it's redirect to page2. 

### Expected Behavior
User should not be redirected to page 2 when app is running on foreground, and it should be popup in notification tray.

**Comment by jassmith** [comment]
Im sorry I do not understand your problem at all. Can you explain more clearly? Pictures sound like they would help a lot here...

**Comment by pauldipietro** [comment]
Closing as we've had no response for over a month. Please reopen with more information and a reproduction if the issue still occurs on 3.0/3.1-pre.
