### ISSUE TITLE
Croitical - no icon in IOS proect of a xamarin forms application

### ISSUE THREAD

**Issue by ormaa** [xamarin/Xamarin.Forms#2234]
### Description
in a xamarin forms application, there is no icon visible in IOS project, deployed on simulator.

### Steps to Reproduce

Create a xamarin forms application.
open assets.xcassets in ios project.
delete appicon 
import a brand new app icon set, created by professional tool, and recognised by xcode application.
clean all
build
run

### Notes
The appicon asset is used with xcode, in a native application project I created. 
I am then sure that the content is proper, and valid for an IOS application.

### Expected Behavior
the app icon should be what is in appicon assets

### Actual Behavior
the icon the not displayed, there is only the default con (blanck square with lines inside)
### Basic Information

- Version with issue:
Version with issue: visual studio community 7.4.1 build 48
Last known good version: none
IDE: visual studio community 7.4.1 build 48
MACOS High sierra 10.13.3

### Screenshots
<img width="1257" alt="screen shot 2018-04-03 at 15 45 23" src="https://user-images.githubusercontent.com/26183915/38253096-0fd24b9c-3756-11e8-86ef-1789117b9a2f.png">

**Comment by olivier38070** [comment]
Hi,

I fixed it by deleting the appicon asset, adding a new one. modify the info.plist to target : no icon.
come back in assets page, import the appicon assets
go back to info.plist, set the app icon to the imported one.
clean all
build
run, the icon was updated.

I hope I do not forget any step here...
thanks
Olivier

**Comment by jassmith** [comment]
Not a forms issue, follow Olivier's instructions above to get your icon working :)

If you have issues still please file against xamarin/xamarin-macios or ask me to migrate this issue for you.
