### ISSUE TITLE
[All] Stepper Maximum does not allow a value less than 1

### ISSUE THREAD

**Issue by ckrempp91** [xamarin/Xamarin.Forms#2236]
### Description
It was discovered that while using a Stepper control and setting/binding the Maximum property to a value less than 1 would throw a ArgumentException. The exception states that the Maximum property was invalid.

Here is a reproduction project of the issue. This is just a barebones project created with the Visual Studio 2017 Xamarin project template using .NET Standard. [StepperRepo.zip](https://github.com/xamarin/Xamarin.Forms/files/1873238/StepperRepo.zip)

Here is the XAML code for the stepper:
`<Stepper
    Value="-2"
    Maximum="-1"
    Minimum="-5"
    VerticalOptions="Center"
    HorizontalOptions="Center"
/>`

### Steps to Reproduce
1. Open the reproduction project
2. Target any platform (The MainPage.xaml should already have the Stepper setup)
3. Run the application

### Expected Behavior
The control should allow for a negative range of numbers for example: Minimum -5 and Maximum: -1

### Actual Behavior
The app throws an ArgumentException stating that the Maximum property is invalid.

### Basic Information
- IDE: Visual Studio 2017 15.6.4
- Platform Target Frameworks:
  - Xamarin: 4.9.0.752
  - Xamarin.Android SDK - 8.2.0.16
  - Xamarin.iOS/Xamarin.Mac SDK - 11.8.1.28
  - UWP:  16299
- Android Support Library Version: 25.4.0.2
- Xamarin.Forms: 2.5.0.280555

**Comment by bugadani** [comment]
Your expectations and your code are doing different things: you coded that you want your maximum be less (-5) than your minimum (-1). That is nonsense and without digging deeper I would guess that this mixup causes your exception.

**Comment by ckrempp91** [comment]
I apologize the XAML code example was incorrect. I was up to late trying to write the bug report, and have updated the XAML to be correct now. The reproduction project had the correct code in place and can still reproduce the problem.

**Comment by jassmith** [comment]
This is a long known issue, simply define the Minimum before you define the Maximum in your XAML. Otherwise the values get coerced.
