### ISSUE TITLE
Xamarin Forms crash in IOS project do not stop at exception line - do not display full exception trace

### ISSUE THREAD

**Issue by olivier38070** [xamarin/Xamarin.Forms#2242]
### Description
When I debug an IOS project on a Xamarin Forms solution, when there is exception, 
the debugger do not stop at exception line
the debugger do not display complete exception message
exception message exist : I can copy the text on the popup and paste it in text editor.

The option in Run, New Exception catch-point  + Pause the program + When an exception is thrown are selected.

### Steps to Reproduce

Create a Xamarin forms application
in the xaml page, add a listview, with image and label.
in code behind, load image with RSS feed images
run the IOS project on ios device
scroll the listview
app will crash : see screen shot

for code, please do not hesitate to check my github solution 
note : it is a work in progress, just for me to validate the stability of xamarin tools before working on it on production projects.

https://github.com/ormaa/RSS-Reader_IOS-Android

### Expected Behavior
The app should stop where the exception occurred
the exception popup should display the message and stack trace

### Actual Behavior
the app stop in main.cs
the popup do not display any message, but a hort part of the message. no stack trace.

### Basic Information

Version with issue: visual studio community 7.4.2 build 12
Last known good version: none
MACOS High sierra 10.13.3
Xcode 9.3, swift 4.1

I obtain the same error when I run app on IOS simulator, or IOS device iphone 5S IOS 11.3

### Screenshots
![screen shot 2018-04-04 at 11 01 35](https://user-images.githubusercontent.com/8026564/38298735-7bb40dbc-37f8-11e8-8126-e21bb8d2dc3c.png)

<img width="1547" alt="screen shot 2018-04-04 at 11 08 29" src="https://user-images.githubusercontent.com/8026564/38298758-8e69e9f4-37f8-11e8-9888-0a57643b84e4.png">

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-macios#3893
