### ISSUE TITLE
Cannot register properly custom renderer if placed into an external library

### ISSUE THREAD

**Issue by peppe130** [xamarin/Xamarin.Forms#2254]
### Description

Hi,

I'm trying to create a library with all my custom renderers but not all of them get registered properly. I can't see some customizations after installing my **NuGet** library into my PCL project. For example, my **Android** custom ScrollView renderer has a method to show/hide scrollbars. Even if that method is called, scrollbars are always shown. The code works fine, I had it in all my Apps. The problem occurs when moving the custom renderer into an external library. Everything works just fine if I leave the custom renderer into my project as a standard class.

### Steps to Reproduce

**_Custom ScrollView render_**
```c#
namespace MyLibrary.Forms.Renders
{
    [Xamarin.Forms.Internals.Preserve(AllMembers = true)]
    public class ScrollView : Xamarin.Forms.ScrollView
    {
        #region ShowVerticalScrollBar
        public static readonly BindableProperty ShowVerticalScrollBarProperty = BindableProperty.Create(nameof(ShowVerticalScrollBar), typeof(bool), typeof(Renders.ScrollView), false);
        /// <summary>
        /// Gets or sets a value indicating whether the Renders.ScrollView should have the vertical scrollbar.
        /// </summary>
        public bool ShowVerticalScrollBar
        {
            get => (bool)GetValue(ShowVerticalScrollBarProperty);
            set => SetValue(ShowVerticalScrollBarProperty, value);
        }
        #endregion

        #region ShowHorizontalScrollBar
        public static readonly BindableProperty ShowHorizontalScrollBarProperty = BindableProperty.Create(nameof(ShowHorizontalScrollBar), typeof(bool), typeof(Renders.ScrollView), false);
        /// <summary>
        /// Gets or sets a value indicating whether the Renders.ScrollView should have the horizontal scrollbar.
        /// </summary>
        public bool ShowHorizontalScrollBar
        {
            get => (bool)GetValue(ShowHorizontalScrollBarProperty);
            set => SetValue(ShowHorizontalScrollBarProperty, value);
        }
        #endregion
    }
}
```

**_Custom ScrollView renderer_**
```c#
[assembly: ExportRenderer(typeof(MyLibrary.Forms.Renders.ScrollView), typeof(MyLibrary.Droid.Renderers.ScrollViewRenderer))]
namespace MyLibrary.Droid.Renderers
{
    [Xamarin.Forms.Internals.Preserve(AllMembers = true)]
    public class ScrollViewRenderer : Xamarin.Forms.Platform.Android.ScrollViewRenderer
    {
        Forms.Renders.ScrollView @ScrollView;

        public static void Init()
        {
            // This method is called from the MainActivity right after the Forms.Init(...).
            var ignore1 = typeof(Forms.Renders.ScrollView);
            var ignore2 = typeof(CShape.Droid.Renderers.ScrollViewRenderer);
            RegisterRenderer(typeof(Xamarin.Forms.ScrollView), typeof(MyLibrary.Forms.Renders.ScrollView), typeof(MyLibrary.Droid.Renderers.ScrollViewRenderer));
        }

        static void RegisterRenderer(Type originalRender, Type customRender, Type customRenderer)
        {
            Assembly assembly = originalRender.Assembly;
            Type registrarType = assembly.GetType("Xamarin.Forms.Internals.Registrar") ?? assembly.GetType("Xamarin.Forms.Registrar");
            PropertyInfo registrarProperty = registrarType.GetProperty("Registered", BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public);
            object registrar = registrarProperty.GetValue(registrarType, null);
            MethodInfo registerMethod = registrar.GetType().GetRuntimeMethod("Register", new[] { typeof(Type), typeof(Type) });
            registerMethod.Invoke(registrar, new[] { customRender, customRenderer });
        }

        public ScrollViewRenderer(Context context) : base(context) { }

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            if (e.OldElement != null)
            {
                e.OldElement.PropertyChanged -= OnElementPropertyChanged;
            }
            if (e.NewElement != null)
            {
                @ScrollView = e.NewElement as Forms.Renders.ScrollView;
                @ScrollView.PropertyChanged += OnElementPropertyChanged;
                UpdateScrollBars();
            }
        }

        void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (_("Content") ||
                _(Forms.Renders.ScrollView.ShowVerticalScrollBarProperty.PropertyName) ||
                _(Forms.Renders.ScrollView.ShowHorizontalScrollBarProperty.PropertyName)
               ) UpdateScrollBars();

            bool _(string equalsTo) => e.PropertyName.Equals(equalsTo);
        }

        void UpdateScrollBars()
        {
            /*
                This method is called by OnElementChanged(...) method when the custom ScrollView
                is firstly initialized and also each time the value of ShowVerticalScrollBar and 
                ShowHorizontalScrollBar properties changes.
             */
            VerticalScrollBarEnabled = @ScrollView.ShowVerticalScrollBar;
            HorizontalScrollBarEnabled = @ScrollView.ShowHorizontalScrollBar;
            if (ChildCount > 0)
            {
                GetChildAt(0).VerticalScrollBarEnabled = @ScrollView.ShowVerticalScrollBar;
                GetChildAt(0).HorizontalScrollBarEnabled = @ScrollView.ShowHorizontalScrollBar;
            }
        }
    }
}
```
### Expected Behavior

The ScrollBars should not be visible.

### Actual Behavior

The ScrollBars are visible even if ShowVerticalScrollBar and ShowHorizontalScrollBar properties are set to false.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: Unknown
- IDE: Visual Studio Community (7.4.2 build 12)
- Platform Target Frameworks: 
  - iOS:  1.0
  - Android: 8.1 Oreo

**Comment by jassmith** [comment]
Any reason you are not just using the built in properties?

**Comment by peppe130** [comment]
Built-in properties are not enough for the kind of Apps I have to make. Is there any solution? Thanks

**Comment by jassmith** [comment]
The built in properties are clobbering your settings and they have no idea you are setting the same properties they are. I still dont understand why the built in properties aren't good enough for setting the scrollbar visibility. Those properties already exist.

**Comment by hartez** [comment]
@peppe130 So you had custom renderers for Android which worked fine when you included them directly in your project. You moved them to an external library and they have stopped working. Is that correct?

>  I can't see some customizations after installing my NuGet library into my PCL project.

Does you Android project have a reference to your NuGet library? If not, that might explain why Forms is not finding your custom renderer during initialization.

**Comment by peppe130** [comment]
@hartez Yes, exactly. The package might be referenced correctly because other renderers work fine.

**Comment by peppe130** [comment]
@jassmith For the moment I've set scrollbars visibility via styles.xml but I still need to set it programmatically.

**Comment by hartez** [comment]
> The package might be referenced correctly because other renderers work fine.

@peppe130 You have other custom renderers in your external library which work on Android, but the custom ScrollViewRenderer does not?

**Comment by peppe130** [comment]
@hartez Only the two properties (**ShowVerticalScrollBar** and **ShowHorizontalScrollBar**) that I wrote in the first comment, do not work if they are moved into an external library. I don't understand why. It's like something, foreign to the library, is overriding those properties. Maybe, Android fault.

**Comment by hartez** [comment]
@peppe130 Why do you have the `Init` and `RegisterRenderer` methods? The `Export` attribute should be enough to tell Forms to use your renderer.

**Comment by samhouts** [comment]
Since this issue hasn't been updated in more than 30 days, we will close it now. Please feel free to reopen it if you are still experiencing this issue and have more information. Thank you!
