### ISSUE TITLE
Android CreateFragment native forms

### ISSUE THREAD

**Issue by TomBruyneel** [xamarin/Xamarin.Forms#2256]
There is a functional difference between IOS and android when it comes to page extensions for native forms.

IOS allows to create a viewcontroller from every Page object: 

public static UIViewController CreateViewController(this Page page)

Android only allows to create a fragment from a ContentPage object

public static Fragment CreateFragment(this ContentPage view, Context context)

I can't seem to find any reason for this, as the code is almost 100% the same apart from this. Is this something that could be changed, or is there a good reason for the difference between the platforms?

On IOS we can create a native form from a NavigationPage while on Android this is impossible.

**Comment by jassmith** [comment]
On Android we have to control a lot more of the stack to do the navigation, so you end up limited to ContentPages because we couldn't reliably make navigation work otherwise. It's not impossible for us to open this up in the future, but for now this was the decision made.

In short android fragment management is something as a framework you either want to be mostly in control of you leave it up to users to do for themselves.

**Comment by hartez** [comment]
Just to provide some more context - 
The fact that you can create a `UIViewController` from any `Page` object and use it with the Native Forms feature is an accident of history. If you look at the code in `Xamarin.Forms.Platform.iOS/PageExtensions.cs`, you'll notice there are actually two different extension methods. One takes a `Page`, the other takes a `ContentPage`. 

For various reasons (including the ones Jason mentions above), when the Native Forms feature was conceived we decided that (at least in the initial release) it would only support `ContentPage` on each platform. So extensions methods were created on each platform which could create the correct native type from `ContentPage`. We might (and I stress that this is _not_ a guarantee, just a possibility) decide to support other page types in the future, but for now the only officially supported page type for Native Forms is `ContentPage`.

The other extension method, the one which takes a `Page`, is much older than the Native Forms feature, and is really just an internal method used by Forms. Unfortunately, it happens to work (mostly by accident) with Native Forms, and has caused some confusion.

**Comment by TomBruyneel** [comment]
Okay, seems clear, we'll just have to remember to avoid using the page extension method when doing the IOS dev first :).

Thanks for the answers
