### ISSUE TITLE
[iOS] ScrollToAsync not working on iOS

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#2271]
### Description

ScrollToAsync fails to scroll to the specified Element on iOS.

### Steps to Reproduce

1. Open the ControlGallery
2. Navigate to test case 36651
3. Tap "Add Item"

### Expected Behavior

The ScrollView scrolls down far enough to display the last item in the list.

### Actual Behavior

The ScrollView maintains its current position.

### Basic Information

- Version with issue: 3.0.0
- Last known good version: unknown

**Comment by jvhgamer** [comment]
This remains to be fixed on latest Xam.Forms, for iOS.

**Comment by rmarinho** [comment]
Fixed by #8241
