### ISSUE TITLE
[MacOS] Image from file not getting searched in the bundle

### ISSUE THREAD

**Issue by gabornemeth** [xamarin/Xamarin.Forms#2322]
### Description

When the source of an image is defined by ```FileImageSource```, the image is not getting searched in the the main bundle on MacOS on contrary to the iOS platform.
Workaround is injecting your custom ```IImageSourceHandler``` to handle ```FileImageSource``` types.
```csharp
Xamarin.Forms.Internals.Registrar.Registered.Register(typeof(FileImageSource), typeof(MyFileImageSourceHandler));
```

### Steps to Reproduce

1. Create a XAML containing something like <Image Source="MyImage" />
2. Add any PNG as MyImage.png to the Mac application's Resource folder as BundleResource.
3. Run your app!

### Expected Behavior

Image should be presented as it is on iOS (and Android).

### Actual Behavior

FileImageSource could not be resolved by the built-in FileImageSourceHandler, so no image is visible.

### Basic Information

- Version with issue: 3.0.0.354232-pre3
- Last known good version: none
- Platform Target Frameworks:
  - MacOS: 4.2.1.28

**Comment by AndreiMisiukevich** [comment]
I'm clarifying: you should try something like
```csharp
new Image { Source = "calculator" }
```
