### ISSUE TITLE
Pan Gesture on Android does not start after holding tap

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#2324]
### Description

Holding a touch for a time before starting to move prevents the pan gesture on a View from starting. 

### Steps to Reproduce

1. Navigate to UI test 39768 in the Control Gallery.
2. Follow the instructions on screen.

### Expected Behavior

The image begins to move and "Success" is displayed.

### Actual Behavior

The image does not move.

### Basic Information

The image will move if the initial tap is not held in the same place for very long. This is likely a conflict between long press detection and pan gesture detection.

This is broken in 3.0.0; it worked correctly in when the test was initially created (at commit c83c19f106162ca55ab57dfea3693246ec6155fa).

**Comment by samhouts** [comment]
Maybe related to https://github.com/xamarin/Xamarin.Forms/pull/1753?
