### ISSUE TITLE
[UWP] Issue1875 crashes on 3.0.0 but does not crash on 2.5.1

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2332]
### Description
Load data in OnItemAppearing shouldn't cause a crash

Related to #1235

### Steps to Reproduce
Run ControlGallery  Issue1875 on UWP version 3.0.0 beta 3

### Expected Behavior
Doesn't crash

### Actual Behavior
Crashes

**Comment by hartez** [comment]
https://github.com/xamarin/Xamarin.Forms/commit/e81f4c39f555351b2bc4a11d7d71b227526f98de should have closed this issue.
