### ISSUE TITLE
[UWP] NRE when checking IsInNativeLayout during OnScrollToRequested

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#2336]
### Description

In the UWP ScrollViewRenderer, calling OnScrollToRequested can result in a NullReferenceException.

### Steps to Reproduce

1. Navigate to UI test 35472 in Control Gallery.
2. Follow the test instructions.

### Expected Behavior

Test completes.

### Actual Behavior

Application crash.

This behavior is occurring on the 3.0.0 branch.

**Comment by sirimanu** [comment]
NRE is occurring on iOS as well.

**Comment by chiragjuneja** [comment]
Can you tell me in which Xamarin.Forms version this fix will be available?
