### ISSUE TITLE
[Android] Appearing/Disappearing events do not appear when app is resumed from sleep

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2348]
### Description

https://bugzilla.xamarin.com/show_bug.cgi?id=40722 seems to be resurfaced. Neither events are called, regardless of the value of the platform specific.

Also, while fixing this issue, please add instructions to the UI test that this test is only applicable on Android.

### Steps to Reproduce

1. Run B40722 in Control Gallery
2. Tap the button to toggle events back and forth (clears event log on screen); make sure you have the events Enabled
3. Follow instructions (sleep device, wake device)

### Expected Behavior

Should show Appearing/Disappearing events in on screen log

### Actual Behavior

Shows nothing

### Basic Information

- Version with issue: 3.0.0,251
- Last known good version:

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by PureWeen** [comment]
@samhouts  should this be in needs info?

**Comment by samhouts** [comment]
It has the needs info label, doesn't it? ;)

**Comment by samhouts** [comment]
Even if we open the bugs ourselves, we should wait to see if someone else has experienced it recently...you can subscribe to issues without commenting or whatever.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
