### ISSUE TITLE
[iOS] Possible ListView Memory Leak

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2363]
### Description

The test for https://bugzilla.xamarin.com/show_bug.cgi?id=42329 FAILS on iOS, indicating that it is possibly an issue. 

### Steps to Reproduce

1. Run B42329 in Control Gallery
2. Follow instructions

### Expected Behavior

Destructor message is shown

### Actual Behavior

Nothing is shown

### Basic Information

- Version with issue: 3.0.0,2.5.1,2.5.0
- Last known good version:

**Comment by ionixjunior** [comment]
I believe that this memory leak is not caused by ListView because I removed all content of the **_42329_FrameWithListView** page and the problem still occur.

**Comment by brunck** [comment]
@samhouts This test was automated by PR #5880 and it seems to work on iOS.

**Comment by samhouts** [comment]
@brunck Good call! Thanks!
