### ISSUE TITLE
[UWP] Crash when opening multiple Alerts

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2369]
### Description

When multiple alerts are opened at the same time, UWP crashes with "Only a single ContentDialog can be open at any time."

Related to #881 

### Steps to Reproduce

1. Run B43469 or B45743 on Control Gallery

### Expected Behavior

Test loads

### Actual Behavior

Test crashes

### Basic Information

- Version with issue: 3.0.0
- Last known good version: 2.5.1

**Comment by ashishm29** [comment]
I am facing same issue with 3.0.0.550146 (Latest Version).
