### ISSUE TITLE
[UWP] WebView does not show FilePicker

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#2382]
### Description

WebView with HTML content containing a file picker input does not render the input.

### Steps to Reproduce

1. Run B44500 in Control Gallery

### Expected Behavior

File picker is displayed

### Actual Behavior

Nothing is displayed

### Basic Information

- Version with issue: 3.0.0,251
- Last known good version:

**Comment by paymicro** [comment]
I couldn't reproduce this bug on the branches `master` and `3.0.0`.
![](http://g.recordit.co/nx1aOxkH04.gif)
Is possible it is already fixed?
