### ISSUE TITLE
[WPF] StackLayout VerticalOptions = LayoutOptions.End is not working

### ISSUE THREAD

**Issue by flyingxu** [xamarin/Xamarin.Forms#2394]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
In StackLayout, VerticalOptions = LayoutOptions.End is not working
### Steps to Reproduce

1.  Edit Xamarin.Forms.Controls/GalleryPages/StackLayoutGallery.cs as below:
```
    var stack = new StackLayout { VerticalOptions = LayoutOptions.End};
```
change to `LayoutOptions.End`
```
Button b1 = new Button { Text = "Boring", HeightRequest = 100, MinimumHeightRequest = 50 };
```
`HeightRequest ` is changed to **100** (make it shorter)
```
Button b4 = new Button { Text = "Meh", HeightRequest = 100, MinimumHeightRequest = 50 };
```
again `HeightRequest ` is changed to **100** (make it shorter)
2. Run the project of Xamarin.Forms.ControlGallery.WPF, then select StackLayout Gallery - Legacy
3. Check the layout of the StackLayout

### Expected Behavior
Buttons should be bottom-aligned
### Actual Behavior
Buttons are top-aligned
### Basic Information

- Version with issue: 3.0.Pre3
- Platform Target Frameworks: 
  - WPF:  3.0.pre3

### Screenshots

![capture](https://user-images.githubusercontent.com/122225/38453371-437e2824-3a87-11e8-933c-f23a22538b0d.PNG)

**Comment by mohachouch** [comment]
I started to investigate this issue.

I think I have found the error (see screenshot)

I will continue to validate this solution and I will make a pull request in the next days.

Thanks :)

![image](https://user-images.githubusercontent.com/25939826/38457140-e4bb0996-3a8c-11e8-9635-efa60d685839.png)
