### ISSUE TITLE
ListView with multiple columns

### ISSUE THREAD

**Issue by encrypt0r** [xamarin/Xamarin.Forms#2397]
Multiple columns can be very useful in ecommerce, gallery, and all kinds of other scenarios. Is there any plan to add support for that?

## Spec
Ideally we would add a `ColumnDefinitionCollection` to `ListView`:

```csharp
public static readonly BindableProperty ColumnDefinitionsProperty;
public ColumnDefinitionCollection ColumnDefinitions { get; set; }
```

**Comment by borbmizzet** [comment]
I would really like to see this.

**Comment by rmarinho** [comment]
Hi we could look at new features but after a discussion of a spec, please provide a spec for this feature so we can discuss. 

Thanks

**Comment by encrypt0r** [comment]
@rmarinho done

**Comment by borbmizzet** [comment]
I'm assuming this feature request to be a ListView-type thing that repeats the DataTemplate horizontally until it reaches the column limit, then wraps to the next row, similar to [daniel-luberda/DLToolkit.Forms.Controls](https://github.com/daniel-luberda/DLToolkit.Forms.Controls/tree/master/FlowListView/).  Am I on the same page as what you were proposing @encrypt0r?

**Comment by encrypt0r** [comment]
@borbmizzet That's right, however, having a `ColumnDefinitionCollection` would provide much more flexibility. And I think it's a basic enough feature to be included in Xamarin Forms itself.

**Comment by samhouts** [comment]
This will be covered by #3172. Thank you!
