### ISSUE TITLE
[iOS] Focus stops working for picker after it's already been focused then unfocused

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2398]
### Description
Picker.Focus
Picker.Unfocus
Picker.Focus <- does not work

Thinking this might be the cause
https://github.com/xamarin/Xamarin.Forms/pull/1278

Because if you select something in the list then the focus/unfocus works fine

### Steps to Reproduce

Run control gallery test Issue2339 and just try to focus then unfocus then focus again

### Expected Behavior
Picker should keep being able to focus

### Actual Behavior
Picker stops being able to focus

### Basic Information

- Version with issue: 3.0.0
- Last known good version: 2.5.1

### Implementation notes
The original purpose of the Control Gallery test was for windows but it seems from this PR
https://github.com/xamarin/Xamarin.Forms/pull/762
That that's ok

The Issue2339 should be updated to reflect that it only applies to iOS/Android and the behavior isn't consistent on UWP on purpose

**Comment by samhouts** [comment]
closed by #2433
