### ISSUE TITLE
Entry with numeric/telephone keyboard changing app background color

### ISSUE THREAD

**Issue by Z18782** [xamarin/Xamarin.Forms#2400]
### Description

I'm noticing very odd behavior on Android using Xamarin.Forms. Typing into an Entry with a numeric/telephone keyboard (all other types don't have this issue) darkens the background color. This behavior occurs even on a clean project with nothing but an Entry:

```
using Xamarin.Forms;

namespace App1
{
    public class App : Application
    {
        public App()
        {
            MainPage = new MainPage();
        }
    }

    public class MainPage : ContentPage
    {
        public MainPage()
        {
            Content = new Entry { Keyboard = Keyboard.Numeric }; // or Keyboard.Telephone
        }
    }
}
```
When the Entry is first focused into, nothing unusual happens. In fact, if you click the tick at the bottom right of the keyboard to close it without entering anything, nothing happens either. But if you type anything (even if you backspace it), the background color of the app changes. It even affects other pages in a navigation stack.

Interacting with the Entry again changes the background color back to the original shade, after which the problem does not reoccur. However, in a multi-page app, navigating somewhere else and then returning allows the glitch to happen again.

Also, on an even stranger note, while trying to figure out what causes/does not cause the problem, it suddenly stopped happening. Even closing and reopening the app did not recreate the problem. But once I restarted the emulator, the problem returned.

### Steps to Recreate
1. Have an entry with the numeric/telephone keyboard
2. Input something
3. Unfocus

### Expected Behavior
The background color should not change.

### Actual Behavior
It changes. 

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: Unsure, only just confirmed the problem although I did observe the darkened background color a few weeks back but thought it was just my screen.
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: Android 8.0 - API 27, does not occur in Android 7.1 - API 26
- Nuget Packages: None

Shown here is a GIF illustrating the problem:
![animated gif-downsized_large](https://user-images.githubusercontent.com/38181250/38466905-2c2aa888-3ae5-11e8-9836-17b68d9dd6f5.gif)

I have not included a sample project because the the code is very simple (the code block above alone is enough).

**Comment by Z18782** [comment]
I've tried rolling back Xamarin Forms to 2.2.0.31 and the problem still exists there.

**Comment by rmarinho** [comment]
This doesn't happen on a device, I just tried on Google Pixel 2 and it doesn't change the color. 

Please test on the Device, and reopen if it's still the case. 

Thanks
