### ISSUE TITLE
Memory Issue with Zebra TC56CJ devices running Android 6.0.1

### ISSUE THREAD

**Issue by ivzhang** [xamarin/Xamarin.Forms#2410]
### Description
Device: Zebra TC56CJ
Xamarin.Android App: Basic app with three buttons. Button 1 creates a new activity instance and finishes the current activity, button 2 does a minor collection, button 3 does a major collection. 

This device, when running a Xamarin.Android application, does not properly collect and dispose memory as we would expect. Some of the objects are eventually collected, after 2 - 3 minutes, but the memory never returns close to where it started. I've attached a profiler showing this. 

### Steps to Reproduce

1. Run the application on the specific device and start profiler 
2. Click on the "Start Activity" button 10 times 
3. See the increase in memory over time
4. Stop and wait several minutes, see GC running but the same amount of memory
5. Click the Major collect button a few times
6. Waited several minutes before seeing 1/3 of the memory collected but nowhere close to what it was before 

### Expected Behavior
- Expected memory to be collected after several seconds and after forcing a minor/major collection. We reproduced with a Samsung Galaxy S8 device that showed objects being collected properly. 

### Actual Behavior
- Had to wait several minutes without any memory collection happening. When we forced a memory collection, it took several minutes before we saw a slight dip in the memory usage.

### Basic Information

Visual Studio Enterprise 2017 for Mac
Version 7.4.1 (build 48)
Installation UUID: bfdae6a6-34f9-4e8d-bf1f-35ab562c0a97
Runtime:
Mono 5.8.1.0 (2017-10/6bf3922f3fd) (64-bit)
GTK+ 2.24.23 (Raleigh theme)

Package version: 508010000

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
2.0.5
2.0.0
1.1.1
1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
2.1.4
2.0.0
1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.8.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.1
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.2.1.28 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.8.1.28 (Visual Studio Enterprise)
Hash: 3979d081
Branch: d15-6
Build date: 2018-03-09 16:22:34-0500

Xamarin.Android
Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/aaronennis/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
4.2 (API level 17)
4.3 (API level 18)
4.4 (API level 19)
5.0 (API level 21)
5.1 (API level 22)
6.0 (API level 23)
7.0 (API level 24)
7.1 (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.6
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 704010048
Git revision: 6a86203dd590c6cfdf814c8832d24d2ad1e2606f
Build date: 2018-03-20 11:16:55-04
Xamarin addins: 8d83cea9e4ae03cb0c14ba3fbaafdbb0cbd170e7
Build lane: monodevelop-lion-d15-6

Operating System
Mac OS X 10.13.3
Darwin 17.4.0 Darwin Kernel Version 17.4.0
    Sun Dec 17 09:19:54 PST 2017
    root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

### Reproduction Link

[MemoryTest2 (Latest).zip](https://github.com/xamarin/Xamarin.Forms/files/1891263/MemoryTest2.Latest.zip)

[ZebraTC56CJ Profiler.zip](https://github.com/xamarin/Xamarin.Forms/files/1891268/ZebraTC56CJ.Profiler.zip)

**Comment by rmarinho** [comment]
Hi, this issue should be open on https://github.com/xamarin/xamarin-android , this repo is for Xamarin.Forms product.
