### ISSUE TITLE
Listview with HasUnevenRows doesn't auto change custom cell height when image change on iOS

### ISSUE THREAD

**Issue by chentotal** [xamarin/Xamarin.Forms#2412]
### Description
Listview with HasUnevenRows doesn't auto change custom cell height when image change.
Custom cell has a image and some labels and icons.
When I scroll listview image in cells would change size by different data, and row height won't properly fit
with new image size.
I need to scroll the cell with wrong size up to out of the screen and in again, it maybe would update to correct size. 
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:2.5.1
- IDE:VS 2017
- Platform Target Frameworks: 
  - iOS: 11

**Comment by samhouts** [comment]
For performance reasons, we do not automatically resize Cells when the content changes. Scrolling the ListView causes the Cells to recycle, which is why you see the update happen at that time. 

You can call `Cell.ForceUpdateSize` when your image changes to update the size. Please see https://developer.xamarin.com/samples/xamarin-forms/UserInterface/ListView/DynamicUnevenListCells/ for a sample app using this feature.

If you have any further issues, please let us know. Thanks!

**Comment by chentotal** [comment]
Oh, no. I reported the wrong one.
Please check here.

I use uneven listview with custom cell.
There is one image and two labels in cells.
Image with AspectFill couldn't show whole image in cells.
is it caused by the same reason?

** Screenshot

sample 1
![inkedsample1_li](https://user-images.githubusercontent.com/17058420/38592915-584c2854-3d71-11e8-9535-2ecfd5a61937.jpg)

original image 1 - without black border
![original1](https://user-images.githubusercontent.com/17058420/38592824-dd7ebb46-3d70-11e8-95c1-ff05d67fcd42.png)

sample 2
![inkedsample2_li](https://user-images.githubusercontent.com/17058420/38592917-5b561f96-3d71-11e8-8986-a630ec1d3bec.jpg)

original image 2 - without black border
![original2](https://user-images.githubusercontent.com/17058420/38592840-f0724894-3d70-11e8-99e6-28b004e98925.png)

** Sample Project
[https://github.com/chentotal/ListviewSampleProject](url)

**Comment by chentotal** [comment]
Another question.
If I want to make a page like Facebook News Feed, should I use ListView or StackLayout within ScrollView?
Thanks.

**Comment by chentotal** [comment]
I try to use Cell.ForceUpdateSize after image download completed with FFImageLoading.
On iOS, I couldn't scroll the ListView.
It keep going back to the top.

`
public partial class MyViewCell : ViewCell	
{

    public MyViewCell()
    {

        InitializeComponent();
        myImage.Success += UpdateImageSize;
    }
    void UpdateImageSize(object sender, FFImageLoading.Args.SuccessEventArgs args)
    {
	    Device.BeginInvokeOnMainThread(() =>
	    {
		    this.ForceUpdateSize();
	    });
    }
}`
