### ISSUE TITLE
Xamarin.Forms is rendering different colors on iOS and Android, given the same Hex Color Code.

### ISSUE THREAD

**Issue by DiegoPatrocinio** [xamarin/Xamarin.Forms#2413]
### Description

Xamarin.Forms is rendering different colors on iOS and Android, given the same Hex Color Code.

iOS: Most of times it renders the correct color, but in some cases it renders a different shade.

Android: On Simulator, most of times it renders a different shade of the given color in the Hex Color Code, but on a real device (Galaxy Note8 - Snapdragon - Android 8.0) it behaves like iOS, renders most of colors correctly, but in some cases it renders a different shade.

### Steps to Reproduce

1. Create a Grid, Boxview or any other control, set it background color for a #0066CC, #10664D, #FD0087 or #018CFF.

2. Run it on both Android and iOS Simulator, and put them side-by-side.

3. Watch your OCD drive you crazy.

### Expected Behavior

Render the same color on every platform.

### Actual Behavior

Rendering different colors on each platform (at least Android and iOS).

### Basic Information

- Version with issue: 2.5.0.121934
- Last known good version: ???
- IDE: VS4Mac
- Platform Target Frameworks: 
  - iOS: 11.3
  - Android: 7.1, 8.0
- Nuget Packages: None
- Affected Devices: iOS Simulator (Any Device), Android Simulator (Pixel 5, Android 7.1), Samsung Galaxy Note8 (Snapdragon - Android 8.0).

### Screenshots

iOS Simulator x Android Simulator x Android Real Device. It's very small difference, but it's different.

<img width="1430" alt="screen shot 2018-04-10 at 10 46 45" src="https://user-images.githubusercontent.com/14826301/38565474-ca6b4aec-3cb7-11e8-89ab-53865a02a7f2.png">

### Reproduction Link

Demo Project reproducing the issue, just fire it up.

https://drive.google.com/file/d/1kxtsSoudBvBub6uxpAkFajaD48FJ6RPo/view?usp=sharing

**Comment by GalaxiaGuy** [comment]
I suspect this is to do with color spaces:

https://github.com/xamarin/Xamarin.Forms/issues/2218

Out of curiosity, what happens if you compare the background color of a `Frame` on Android and iOS?

**Comment by rmarinho** [comment]
Yeah this seems the color space issue related with #2218

**Comment by Bejasc** [comment]
I'm also seeing the same, using #EB7311 as my colour. 
In my case, the value is set as that in a resource dictionary, with the pages referencing the colour by its key. 

The colour appears identical for all controls referencing it, though the colour is 'washed out' by a few shades on iOS and appears much more vibrantly (and as expected) on Android. 

As an interesting note, I've run an emulator on our mac, and the colour appears as it should be expected (no washout) on the emulator, but on the device, the colour is a few shades different.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by EddieNoureddine** [comment]
Issue is still around . Not resolved yet with the latest xf 5.0

**Comment by keithhol** [comment]
Any update?
