### ISSUE TITLE
RoutingEffect on Android doesn't work anymore if Xamarin.Forms >= 2.5.0.280555

### ISSUE THREAD

**Issue by lewixlabs** [xamarin/Xamarin.Forms#2422]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

### Description
Xamarin.Forms project based on new .Net Standard shared project
Using [Xamarin Forms Routing Effect](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/creating) and Xamarin.Forms >= 2.5.0.280555 on Android buttons are not rendered anymore (they are invisible).
I already tried to clean whole solution (debug/obj folders too), all nuget packages and rebuild all on Visual Studio 2017 (Windows)  and Visual Studio for Mac (stable channel).

### Steps to Reproduce

1. Create a new Routing Effect in .Net Standard project
2. Create a related PlatformEffect in Android subproject and in OnAttached callback set this custom effects
`                var control = Control as Android.Widget.Button;
                control.SetBackgroundResource(Resource.Drawable.RoundBluBeButton);
                control.SetAllCaps(false);`
RoundBluBeButton is a axml with only one custom UI property
Content of RoundBluBeButton.axml is
```
<?xml version="1.0" encoding="utf-8"?>
<!-- Style for "rectangle_" -->
<!-- Add this snippet to layer-list xml in drawable. -->
 <shape  xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
 <corners android:radius="10dp" />
  </shape>
```

3. Button in xaml (in .Net Standard shared project) is declared inside a StackLayout, withi this properties
`                    <Button x:Name="btnLogin" Text="Login" VerticalOptions="Center" Style="{StaticResource blubeButtonBlueItalic}" TextColor="White" IsEnabled="{Binding IsLoginEnabled, Mode=OneWay}">
                        <Button.Effects>
                            <local2:BluBeButtonEffect/>
                        </Button.Effects>
                    </Button>`

### Expected Behavior
With previsous Xamarin.Forms releases (2.5.0.122203 and older) button are correctly rendered with rounded corners

### Actual Behavior
WIth Xamarin.Forms >= 2.5.0.280555 on Android button are not rendered (they are invisible)

### Basic Information

- Version with issue:
- IDE: Visual Studio 2017 v15.6.6 on Windows 10 & Visual Studio for Mac (stable channel)
- Platform Target Frameworks: 
  - Android: compile & target version are 27

**Comment by samhouts** [comment]
I tried to reproduce this, but I think we might be missing a few pieces of information. Can you please attach a small project that demonstrates the issue? Also, can you please confirm that you see this issue with 2.5.1? Thank you.

**Comment by lewixlabs** [comment]
Hi @samhouts ,
yes i confirm this issue happens with 2.5.1 too
I created from scratch a new simple xamarin forms project (from Visual Studio for Mac, has PCL but issue happens with .Net Standard too).
I confirm with this new project i got this issue with Xamarin Forms 2.5.1 and not with Xamarin Forms 2.5.0
I uploaded this test project here
https://1drv.ms/u/s!Amd7OvANAb4LhpY5zFzJ3-JxpAJsbg

Let me know if you need more info.
Thanks.

Lewix

**Comment by samhouts** [comment]
related to #1570/#1935

**Comment by lewixlabs** [comment]
Hi @samhouts,
i'm reading your other posts, but actually i don't understand if is there a workaround to get rounded corners on Android Buttons (from Xamarin Forms 2.5.1)?
Thank you for any suggestion.

**Comment by samhouts** [comment]
Please try the `CornerRadius` property on the `Button` instead of replacing the background with your routing effect.

The PRs that are mentioned above fixed `CornerRadius` (previously called `BorderRadius`) on Android. I think they also caused the issue that you're experiencing now.

**Comment by lewixlabs** [comment]
Yes new CornerRadius property fixes my issue.
Good to know.

Thank you!
