### ISSUE TITLE
[F#] The XAML parser requires BindableProperties to be public static fields which are not supported in F#

### ISSUE THREAD

**Issue by jimbobbennett** [xamarin/Xamarin.Forms#2425]
### Description

When the XAML parser looks for bindable properties, it looks at the public static fields on the control. This works fine in C#, but F# does not support public static fields in the language. This means building custom controls in F# that can be called from XAML is not possible.

### Steps to Reproduce

1. Try to create a bindable property as a public static field in a custom control implemented in F#
2. Find you can't 😜

### Expected Behavior

It would be nicer if the XAML parser was able to use static properties or private static fields for the bindable properties instead of just public static fields. This way F# would be supported

### Basic Information

- Version with issue: All
- Last known good version: None

### Reproduction Link

https://github.com/jimbobbennett/TicTacToe/tree/FormsXAMLErrorRepro shows an example app with a control called CellControl with no way to make the Command and GameCell bindable properties work.

**Comment by jimbobbennett** [comment]
The line of code in question is https://github.com/xamarin/Xamarin.Forms/blob/6376fe7bf2da3395b19f28fe89ad0145d0a2d82d/Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs#L274.

The simplest option to fix this that I can see is to remove the public requirement, allowing fields created using `static let` or `static val mutable` to be accessed by the parser.

**Comment by StephaneDelcroix** [comment]
using `static let` generates an `internal` field, and it should be usable

**Comment by nosami** [comment]
```fs
    static let OnGameCellChanged (bindable : BindableObject) (oldValue : obj) (newValue : obj) : unit =
        let control = bindable :?> CellControl
        let n = newValue :?> GameCell
        control.UpdateFromGameCell n
        ()
```

looks like this when decompiled.

```cs
[CompilerGenerated]
internal static void OnGameCellChanged (BindableObject bindable, object oldValue, object newValue)
{
	//IL_0000: Unknown result type (might be due to invalid IL)
	//IL_0001: Expected O, but got Unknown
	CellControl cellControl = LanguagePrimitives.IntrinsicFunctions.UnboxGeneric<CellControl> ((object)(?)bindable);
	GameCell g = LanguagePrimitives.IntrinsicFunctions.UnboxGeneric<GameCell> (newValue);
	cellControl.UpdateFromGameCell (g);
}
```

**Comment by StephaneDelcroix** [comment]
@nosami we figured the internal field earlier today with @jimbobbennett, and then dropped some notes in order to recall what was discussed, but thanks for confirming.

the short-term plan is to modify the XAML loader so it can see internal fields. This will allow accessing BP defined in the current assembly, but won't allow creating a component in f# that can be reused by an external assembly.

the long-term plan would be to actually `Register()` our BPs (we only `Create()` them right now), so the XAML parser would only care about the BP table and not the fields. It will speed up XAML inflation but would at the same time require gross hacks to maintain XamlC working...

**Comment by jimbobbennett** [comment]
@StephaneDelcroix - thought it would be fun to fix this myself, but not sure about testing it. Code change doesn't break any tests, so I'm assuming the access modifiers aren't explicitly tested. Ideally I'd like to have an F# app in the UI tests, so how should I go about doing this?

**Comment by StephaneDelcroix** [comment]
@jimbobbennett show me your changes, I'll tell you if they're breaking :)
