### ISSUE TITLE
ios listview unable to set background via trigger because of selection animation

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#2427]
### Description
Because of the background animation in the iOS listview, setting a background on the content of a listview item via a trigger doesn't work, when this trigger is set during the tap.

### Steps to Reproduce

1. Open the test project
2. Run it on iOS
3. Tap some listview items

### Expected Behavior
Tapped items become Red because they are selected, just as in android.

### Actual Behavior
Tapped items sometimes become Red for about half a second, and then revert to blue. Other times, the items become grey on tap instead of red, but they still revert to blue after the tapped animation has ended. Once you scroll down in the listview and the item scrolls out of screen, and you scroll back, the item HAS become red.

### Basic Information

- Version with issue: 2.6 nightly build, and 2.5.1
- Last known good version: -
- IDE:Visual studio 2017
- Platform Target Frameworks: 
  - iOS:  any (tried 9 and 11)
- Nuget Packages: using behaviorspack in sample project to use the eventtocommandbehavior
- Affected Devices: iphones

### Screenshots
- adding a screenshot with only blue listitems doens't clarify the issue. You need to run the test app.

### Reproduction Link

[ListViewBackground.zip](https://github.com/xamarin/Xamarin.Forms/files/1901622/ListViewBackground.zip)

Edit:
added description the color being corrected after scrolling the listview

**Comment by PaulVrugt** [comment]
I'm actually looking for a workaround to make our selections in listview work correctly. So if anyone has any suggestions, let me know. The test project runs fine on android, however, it doesn't work in iOS

**Comment by PaulVrugt** [comment]
@rmarinho 
Not sure if you're the right person to ask, but do you have any idea of a workaround for this issue? Or can you maybe point me to someone who knows a workaround?

**Comment by khadeeja-alif** [comment]
I'm facing the same issue in iOS. Please suggest a workaround

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
