### ISSUE TITLE
[FlexLayout] Position property is apparently not implemented

### ISSUE THREAD

**Issue by charlespetzold** [xamarin/Xamarin.Forms#2429]
Xamarin.Forms 3.0.0.354232-pre3 supports a new `FlexLayout`. The public `Position` property is of type `FlexPosition`, an enumeration with two members: `Relative` (the default) and `Absolute`. 

Apparently the `Absolute` option is supposed to allow a child to be positioned with pixel coordinates, but there seems to be no mechanism for specifying those coordinates.

**Comment by StephaneDelcroix** [comment]
we should reuse, or use something similar to, `AbsoluteLayout.LayoutBounds`

**Comment by charlespetzold** [comment]
`Position` is a bindable property, not an attached bindable property. It applies to the entire `FlexLayout`. If setting `Position` to `Absolute` causes the `FlexLayout` to position children based on specified bounds, what's the point of using `FlexLayout` at all in this scenario? Why not just use `AbsoluteLayout`?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
