### ISSUE TITLE
NuGet: what happened to 2.6.0.251661?

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/Xamarin.Forms#2430]
### Description
I had some trouble with the versions released on nuget.org.
My project was based on 2.5.0.122203 and I updated yesterday to 2.6.0.251661.
I had some problems with that version and had to roll back to 2.5.0.

Now I see that this version is not in nuget.org anymore. For me it looks like, this was released accidentally...

I expected to find some information in the release notes or so, but I couldn't. So maybe someone can help me:
* why/when was 2.6.0.251661 published to nuget.org?
* why/when was it removed again?

**Comment by samhouts** [comment]
2.6.0.251661 was a nightly build. It was never on nuget.org. It would have been on https://www.myget.org/F/xamarinforms-ci/api/v2. See https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds.

**Comment by johannes-schmitt** [comment]
@samhouts, your hint with the nightly build made me remember that some time ago I added https://www.myget.org/F/xamarinforms-ci/api/v2 as a NuGet source. That's why Visual Studio offered me to update to 2.6.0.251661...

My bad and sorry for any inconvenience. Such a stupid mistake...

**Comment by samhouts** [comment]
No problem at all! We're very happy that you tried out a nightly build. We hope that availability is helpful. :)
