### ISSUE TITLE
Entries bound to number fields don't handle cultures that use a comma as a fraction separator

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#2434]
### Description

When setting the culture to a language that uses a comma (,) as a fraction separator, and then binding an Entry to a numeric property, whenever you add a comma and then type an additional number, Xamarin.Forms strips the comma.

| Entered | Expected | Actual
| --- | --- | --- |
| 12,3 | 12,3 | 123 |

The reason for this is because Xamarin.Forms is most likely doing a `.ToString()` (invariant culture) instead of `.ToString(culture)`. Now I can't prove this because I couldn't find where Forms does the translation, but you can see the affects in my [attached repro](https://github.com:ChaseFlorell/Xamarin.Forms.Not.Handling.Decimal).

The result is that the comma is being treated as a thousands separator instead of a fraction separator, thereby stripping the comma in the conversion.

### Steps to Reproduce

1. clone https://github.com:ChaseFlorell/Xamarin.Forms.Not.Handling.Decimal
2. set your device culture to French
3. run the iOS app and enter `12,3` into the first and second Entry fields

### Expected Behavior

12,3 should be displayed in both

### Actual Behavior

123 is displayed in the first
12,3 is displayed in the second

> _note: the reason the second behaves as expected is because I've attached a custom converter._

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: n/a
- IDE: VS 2017
- Platform Target Frameworks: 
  -  iOS:  11.3
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms
- Affected Devices: All (core)

### Screenshots

N/A

### Reproduction Link

https://github.com:ChaseFlorell/Xamarin.Forms.Not.Handling.Decimal

**Comment by rmarinho** [comment]
I think you will need to use a Converter as a workaround,
But this is a issue related with Binding and be or not Culture aware. for now this is more a dupe/ related with  #2049 and we are going to track the effort there.

**Comment by ChaseFlorell** [comment]
@rmarinho if you look at my repro, I've already written a converter... the issue really is that we have to do it at all. Applying this filter to several dozen inputs is tedious and prone to mistake... especially in a data heavy app like ours.

**Comment by ChaseFlorell** [comment]
if you mean "breaking change" as in properly converting data based on culture, and possibly breaking ppl who are relying on that bug... I think it's acceptable.

/cc @davidortinau
