### ISSUE TITLE
Crashing in Xamarin.Forms.Platform.iOS.ImageRenderer

### ISSUE THREAD

**Issue by leeyeong23** [xamarin/Xamarin.Forms#2440]
### Description
Similar to bug #1795 , this time happened on image renderer, only in iOS platform, already update to Xamarin.Forms 2.5.1-sr1

### Expected Behavior
App not crashing
### Actual Behavior
App crashing

**Comment by rmarinho** [comment]
Hi we would need more information, a reproduction will be great and stacktrace .

Thanks

**Comment by pauldipietro** [comment]
Closing as we've had no response for over a month. Please reopen with more information and a reproduction if the issue still occurs on 3.0/3.1-pre.
