### ISSUE TITLE
Delay in loading image when setting the image from the android renderer.

### ISSUE THREAD

**Issue by JayaramanAyyanar** [xamarin/Xamarin.Forms#2441]
### Steps to Reproduce

1. Run the sample.
2. The sample has two buttons, first button with setting the image from the renderer and the second button with setting the image from the PCL.
3. When click the Renderer image button, the image loads with the delay in the android where the same loads the image fast in the iOS and UWP.
4. When click the PCL image button, the image loads faster.
5. So, there is an issue when setting the image from the renderer.

 

### Expected Behavior
   The image should load faster in the android when setting the image from the renderer. 
### Actual Behavior
   The image loads delayed when setting the image from  the renderer.
### Basic Information
   The image load faster in iOS and UWP but not in the android when setting the image from the render.
- Version with issue: 2.4.0.280
- IDE: Visual Studio 2015 (Windows)
- Platform Target Frameworks: 
  - Android: 4.4 and above.
- Affected Devices: Samsung S6

### Bug reproducing sample

[Delay in loading Image.zip](https://github.com/xamarin/Xamarin.Forms/files/1901458/Delay.in.loading.Image.zip)

**Comment by rmarinho** [comment]
I can see a small delay even on 2.5.1.444934

**Comment by PureWeen** [comment]
@JayaramanAyyanar  can you test 3.0 pre3 and see if that works better for you?  I tested it locally and it looks like it loads a lot faster.  We put a fix into 3.0 so that instead of always rendering a BitmapDrawable from an image it uses more of the native Android bits to grab the drawable.

**Comment by JayaramanAyyanar** [comment]
Hi @PureWeen ,
I have tested in 3.0 pre3 and the issue is resolved. 
Thank you.
