### ISSUE TITLE
SHA3-256 compatibility

### ISSUE THREAD

**Issue by kiranbasvaraj** [xamarin/Xamarin.Forms#2443]
Hi,
I want to create SHA3-256 hash code for string values. Can you please suggest me how to achieve this in xamarin forms and please let me know if there is any compatible nuget plugins.

Thanks in Adavance

**Comment by rmarinho** [comment]
Hi there's no way to do this currently on Xamarin.Forms out of the box, i also don't see any plugin for this.
You would need to implement a DependecyService and do the SHA calculation on the platform side, maybe take a look at  System.Security.Cryptography. By using a DS you can then access the calculated hash on Xamarin.Forms land.

**Comment by kiranbasvaraj** [comment]
Thanks a lot ,

But as of now I managed to use the same plugin in xamarin .forms and it is
working fine,we need to use .Net standard library instead of PCL library .
Then we would have access to all .net standards Apis.

Regard ,
Kiran
