### ISSUE TITLE
OnAppearing still called even if I go back from second page

### ISSUE THREAD

**Issue by 5yunus2efendi** [xamarin/Xamarin.Forms#2450]
### Description
Suppose I have two pages with NavigationPage, then I override OnAppearing method in the second page:
```csharp
protected override async void OnAppearing()
{
    base.OnAppearing();
    await Task.Delay(10000);
    Debug.WriteLine("OnAppearing");
}
```
The weird thing is that, if I navigate from first page to second page and then go back to first page as much as I can before `10000` delay , the `Debug.WriteLine("OnAppearing")` code still be called, so am I missing something here?

### Expected Behavior
The `Debug.WriteLine("OnAppearing")` code not be called even if go back from second page

### Actual Behavior
The `Debug.WriteLine("OnAppearing")` still be called

### Basic Information

- Version with issue: 2.5.0.122203 in this reproduction (but I have a project that use 3.0.0.354232-pre3 which has the same issue)
- IDE: Visual Studio Community 2017 15.5.3
- Platform Target Frameworks:
  - iOS:  11.6.1.2
  - Android: 8.1.3.0
  - UWP:  16299

### Gif how to test
![2018-04-13-02-32-14](https://user-images.githubusercontent.com/19399214/38700317-db911856-3ec4-11e8-8b56-ac0ea72c06e5.gif)

### Reproduction Link
[App4.zip](https://github.com/xamarin/Xamarin.Forms/files/1904636/App4.zip)

**Comment by ChaseFlorell** [comment]
That's because it's async void. The void method his the await and immediately returns. It's not stopping you from navigating back, but the rest of the code is still executing.

**Comment by 5yunus2efendi** [comment]
What should I do if the code is
```csharp
protected override async void OnAppearing()
{
    base.OnAppearing();
    HttpResponseMessage response = await httpClient.GetAsync("https://github.com/xamarin/Xamarin.Forms");
    Debug.WriteLine(response.StatusCode);
}
```
and the `GetAsync` is wait more than 5 seconds (due to slow internet connection) and user go back on 2 or 3 seconds? so what should I do?

**Comment by PureWeen** [comment]
@5yunus2efendi   That's kind of a big question

I think reading through the documentation on Tasks would really help you out
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation

The short answer is that *await* is really just a way to help you deal with async code. So what your code above is doing is kicking off a separate background thread and then when that thread finishes it picks up where it left off.

All of this happens within the contained scope of that method.  So if you need those results to just be thrown away you would need to deal with that after the await comes back or just cancel the Task when *OnDisappearing* fires

**Comment by ChaseFlorell** [comment]
Create a Cancellation token OnAppearing and cancel it OnDiappearing. Pass it into your async code. 

Still smelly and you should look at something like Prism to handle navigation, move your logic to the ViewModel.

**Comment by 5yunus2efendi** [comment]
@PureWeen sorry, I didn't mean to ask like that.

I actually already implemented the code using cancellation, I just thought there will be a better implementation from XF, anyway, thanks guys!

**Comment by PureWeen** [comment]
@5yunus2efendi  aw ok. 

Here's a discussion about extending Commands in forms to handle tasks
https://github.com/xamarin/Xamarin.Forms/issues/1857

Which I think addresses what you're asking about a bit better.
