### ISSUE TITLE
ListView Grouping Enhancement

### ISSUE THREAD

**Issue by MelbourneDeveloper** [xamarin/Xamarin.Forms#2454]
### Description
The groupingSampleListView shows some cool functionality that ListView is capable of. The UI is great. We want to implement this in our app. Unfortunately, the functionality requires a second model to be written in code. For example, in this sample there is a "VeggieModel", and a "GroupedVeggieModel". So, even if the app already had a VeggieModel that is groupable with Linq, the programmer needs to create the GroupedVeggieModel class to get the benefit of grouping. In this sample, the grouping is on ShortName/LongName, but in reality, a class may have many properties for grouping, and to leverage any of them, the programmer would need to write a class for each one.

Our application is 100% XAML driven. We define all of our UI in XAML. So, we don't write any code. Someone who is configuring our system would not have access to add a new class like GroupedVeggieModel. So, I propose that if the grouping model is not specified, then Linq should be used to group on a given property of the model that is not grouped. 

This particular code does not work, but it is an example of how I think it should work behind the scenes. I.e. the model should be grouped up by some property specified at the XAML level via reflection. The groupingPropertyName variable would be moved on to the ListView class as a property to be set in XAML.

```
        public class VeggieModel
	{
		public string Name { get; set; }
		public string Comment { get; set; }
		public string Type { get; set; }
		public string Image { get; set; }
		public VeggieModel ()
		{
		}
	}

        public partial class GroupedListXaml : ContentPage
	{
		public GroupedListXaml ()
		{
			InitializeComponent ();

                        var groupingPropertyName = "Type";

			var veggies  = new List<VeggieModel> ();

                        veggies.Add (new VeggieModel () { Name = "celery", Type = "Veggie", Comment = "try ants on a log" });
                        veggies.Add (new VeggieModel () { Name = "tomato", Type = "Fruit", Comment = "pairs well with basil" });
                        veggies.Add (new VeggieModel () { Name = "zucchini", Type = "Veggie", Comment = "zucchini bread > bannana bread" });
                        veggies.Add (new VeggieModel () { Name = "peas", Type = "Veggie", Comment = "like peas in a pod" });
                        veggies.Add (new VeggieModel () {Name = "banana", Type = "Fruit", Comment = "available in chip form factor"});
                        veggies.Add (new VeggieModel () {Name = "strawberry", Type = "Fruit", Comment = "spring plant"});
                        veggies.Add (new VeggieModel () {Name = "cherry", Type = "Fruit", Comment = "topper for icecream"});

                        var grouped = veggies.GroupBy(v => v.GetType().GetRuntimeProperty(groupingPropertyName).GetValue(v));

                        lstView.ItemsSource = grouped;
		}
	}

```

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="GroupingSampleListView.GroupedListXaml">
	<ContentPage.Content>
        <ListView x:Name ="lstView" IsGroupingEnabled="true" GroupDisplayBinding="{Binding Key}" GroupShortNameBinding="{Binding Key}">
			<ListView.ItemTemplate>
				<DataTemplate><TextCell Text="{Binding Name}" Detail = "{Binding Comment}" /></DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</ContentPage.Content>
</ContentPage>

```

This is what the object model looks like when grouped by Linq:
![image](https://user-images.githubusercontent.com/16697547/38716915-ca24513e-3f26-11e8-9395-1666ffa6fe75.png)

Note: I think think that grouping should be the job of CollectionViewSource: #2193 . So, it would be better to spend the time implementing this functionality there, but while grouping remains fixed inside ListView, this functionality would be good.

### Screenshots
![image](https://user-images.githubusercontent.com/16697547/38716306-5085f6aa-3f23-11e8-8075-928c0d3997fb.png)

![image](https://user-images.githubusercontent.com/16697547/38716307-551919c2-3f23-11e8-9a29-1bf0ac484550.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
