### ISSUE TITLE
[UWP] Navigation Leaks var. LayoutRenderer

### ISSUE THREAD

**Issue by SSpormann** [xamarin/Xamarin.Forms#2456]
### Steps to Reproduce

1.  Generate NavigationPage and generate a "startPage" and a second Page, with objects such as Images, Lables, Stacklayouts.

2. Navigate back and foreward, and watch the memory usage grow.

3. Our initial workaourd was to reuse the second Page, that reduced the leaks to a minimum, but the objects, LayoutRenderer, LabelRendere and ImageRenderer, are still leaking.

### Expected Behavior
I would expect the Renderer to be reused for the objects mentioned above.

### Actual Behavior
Objects are generated on navigate and sometimes after gc.collects() when no Navigation took place.

### Basic Information

- Version with issue: 3.0.0.354232-pre3
- Platform Target Frameworks: Xamarin.Forms
  - UWP:  16299 -

### Screenshots
this image is after comming back from the prev. initialized second page
![image](https://user-images.githubusercontent.com/22739414/38727845-6c069c32-3f0e-11e8-8889-b82dcf3531db.png)

this image is after waiting for a while.
![image](https://user-images.githubusercontent.com/22739414/38727912-9f6ecd88-3f0e-11e8-948c-f91d93ba9f0c.png)

### Reproduction Link
I hope I can provide one soon

**Comment by PureWeen** [comment]
@SSpormann  I am seeing some small leaks with UWP but I'm not seeing what you are specifically referencing in this ticket. 

I have a test project where I basically push and pop this page
```
   public class ListPage : ContentPage
        {
            public ListPage()
            {
				StackLayout layout = new StackLayout();

				layout.Children.Add(new Image() { Source = "coffee.png" });
				layout.Children.Add(new Button() { Text = "!!!BUTTON!!!" });

				layout.Children.Add(new ListView
				{
					ItemTemplate = new DataTemplate(typeof(Cell)),
					ItemsSource = new List<string> { "A" },
				});

				Content = layout;
            }
        }
```

off and on the navigation stack but I'm not seeing any of those renderers being left over. If there's something additional I can try or you could provide a repro that'd be super helpful

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/2113
https://github.com/xamarin/Xamarin.Forms/issues/2420

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/2522

**Comment by PureWeen** [comment]
Closing for now. If you can provide a repro and are still having this issue we can re open
