### ISSUE TITLE
Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by ronalsilva** [xamarin/Xamarin.Forms#2461]
### Description
hi guys, I'm with one probleme, my project is with this error  "Could not create the Java Virtual Machine."

### Basic Information

- VS 17
- Windows 10
- Xamarin forms

![capturar](https://user-images.githubusercontent.com/9373434/38741898-70e202fc-3f11-11e8-8e5c-1ddaf28c078a.PNG)

**Comment by rmarinho** [comment]
Sorry but this will need a reproduction and should be  open against https://github.com/xamarin/xamarin-android

**Comment by ronalsilva** [comment]
Thinks
