### ISSUE TITLE
CarouselPage, Scrollview, SetHasNavigationBar(this, false) and SetUseSafeArea behave incorrect

### ISSUE THREAD

**Issue by Sasha111ua** [xamarin/Xamarin.Forms#2463]
I have a Carousel page with children and NavigationPage.SetHasNavigationBar(this,false);. The child has a scrollview and label inside the scrollview.
As a result the scrollview in child is always scrollable even if there is no needs in this and content of the child jumps around the page. 
I know that this was a bug for ContentPage as well and was fixed in some earlier versions of Xamarin forms you was need to add On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true); 
Seems like this does not apply to Carousel page because the content still behaves incorrect and jumps.

### Steps to Reproduce

1. Launch sample project 

### Expected Behavior
View is not scrollable

### Actual Behavior
View is scrollable

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: 2.3
- IDE: Visual Studio Prof 2017 ver 15.6.4
- Platform Target Frameworks: 
  - iOS:  11.8.1.28
- Affected Devices: IOS 11

### Sample project

https://www.dropbox.com/s/mkzdbzbk1a27a5a/App6.rar?dl=0

**Comment by sebfia** [comment]
Same problem here!

**Comment by IronLionShawn** [comment]
I'm also having this issue. Hoping the Xamarin team can fix this.

**Comment by AndreiMisiukevich** [comment]
@sebfia @IronLionShawn 
You can try this package instead https://github.com/AndreiMisiukevich/CardView

**Comment by fmilicchio** [comment]
@Sasha111ua I can confirm on Xamarin Forms 3.4 on macOS (Visual Studio Community 7.7.2 build 21). 

Is there a way of using your code without a page renderer?

**Comment by Sasha111ua** [comment]
> @Sasha111ua I can confirm on Xamarin Forms 3.4 on macOS (Visual Studio Community 7.7.2 build 21).
> 
> Is there a way of using your code without a page renderer?

i dont think so

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
