### ISSUE TITLE
Visual Studio 2017 Release 3 

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#2466]
### Description
Uppon creating a new forms project and launch the project builds fails.

### Steps to Reproduce

1.  Open Visual Studio
2.  Launch the Emulator
3.  File New Projects Universal App Xamrian Forms
4  Build Project and Attempt to deploy

### Expected Behavior
Project should run and deply to device
### Actual Behavior

https://www.dropbox.com/s/x5s861xn6meh8jt/XamLogs.zip?dl=0

**Comment by samhouts** [comment]
Can you please be more specific about the issue you're experiencing? 

Your steps say to launch the emulator, but you do not specify which platform you are working with. 

Your logs indicate that you are using the Live Player, not the emulator. 

You say "Visual Studio 2017 Release 3", but I am not sure what version that is referring to.

Thanks

**Comment by pauldipietro** [comment]
Closing as we've had no response for over a month. Please reopen with more information if necessary.
