### ISSUE TITLE
Label CharacterWrap in StackLayout not work

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [xamarin/Xamarin.Forms#2467]
Hi,
LineBreakMode="CharacterWrap" for label is not working in this simple code,when i remove all stacklayouts or use Grid instade of stacklayout this will work.I think &amp; char is problem too because when i remove it this will works too.

```xml
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Agrin.UI.Views.Contents.LinkInfoView" Padding="10">
    <ContentView.Content>
        <StackLayout>
            <Frame CornerRadius="5" BackgroundColor="#5e98d3">
                <StackLayout BackgroundColor="Blue">
                    <Grid>
                        <Label Text="http://cdn.p30download.com/?b=p30dl-software&amp;f=Mozilla.Firefox.v59.0.2.x86_p30download.com.zip" BackgroundColor="Red" TextColor="White" LineBreakMode="CharacterWrap"/>
                    </Grid>
                </StackLayout>
            </Frame>
        </StackLayout>
    </ContentView.Content>
</ContentView>
```

check this link for text too "http://cld19.cdn.p30download.com/p30dl-software/Mozilla.Firefox.v59.0.2.Farsi.x64_p30download.com.zip?1523131328"

**Comment by samhouts** [comment]
Please complete the issue template in the future to be sure you provide information we need to properly troubleshoot an issue. You did not indicate which platform exhibits this issue, nor which version of Xamarin.Forms you are using.

As far as I can tell with your sample code, `CharacterWrap` is working as expected. Please note that `CharacterWrap` is not supported on UWP, as there is no native option for that.

Please take a look at the attached sample and make any alterations necessary to demonstrate the issue.

Thanks.


iOS:
![ios2467](https://user-images.githubusercontent.com/7827070/38825432-650373c4-4161-11e8-967a-c9fc7aa22970.jpg)

Android:
<img width="720" alt="android2467" src="https://user-images.githubusercontent.com/7827070/38825452-753998a4-4161-11e8-9d3f-a29380ee836d.png">

UWP:
<img width="378" alt="uwp2467" src="https://user-images.githubusercontent.com/7827070/38825480-9451a876-4161-11e8-9af9-cc89a13d833b.PNG">

[Issue2467.zip](https://github.com/xamarin/Xamarin.Forms/files/1916528/Issue2467.zip)

**Comment by Ali-YousefiTelori** [comment]
Thank you,
When i test this in new project that is works fine! I don't know what is the problem now,
My project is very big and I cannot upload.

**Comment by hartez** [comment]
@Ali-YousefiTelori Which version of Xamarin.Forms are you using? Which platform is exhibiting the incorrect behavior? Could you post at least a screenshot of the incorrect behavior?

**Comment by pauldipietro** [comment]
Closing as we've had no response for over a month. Please reopen with more information and a minimized reproduction if the issue still occurs on 3.0/3.1-pre.
