### ISSUE TITLE
Could not install package 'System.IO.FileSystem 4.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. 

### ISSUE THREAD

**Issue by pkpaul5** [xamarin/Xamarin.Forms#2469]
Working on Xamarin Cross Platform project(PCL) in Visual Studio 2017. Need to do some file IO operations but not able to add reference to System.IO.FileSystem nugget. Getting this error Could not install package 'System.IO.FileSystem 4.3.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by samhouts** [comment]
Yes, @jcmanke  is correct. Please see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=vswin for some other information on dealing with files. Thanks.
