### ISSUE TITLE
Binding Converter and BindingContext

### ISSUE THREAD

**Issue by zoilder** [xamarin/Xamarin.Forms#2475]
### Description
I'm trying pass to binding converter, the bindingcontext of a viewcell, using "Binding Path=., Converter=...."
Instead of bindingcontext, null is pass to convert function.

If i use a property of my model, it pass ok.

### Steps to Reproduce
1. Use a similar xaml to this:
```
<?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="GestorColecciones.Test"
             xmlns:local="clr-namespace:GestorColecciones"
>
    <ContentPage.Resources>
        <ResourceDictionary>
            <local:TestConverter x:Key="testConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>
    <ContentPage.Content>
        <StackLayout HorizontalOptions="FillAndExpand"
                               VerticalOptions="FillAndExpand"
        >
            <ListView ItemsSource="{Binding Items}" 
                            HorizontalOptions="FillAndExpand"
                            VerticalOptions="FillAndExpand"
            >
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <TextCell Text="{Binding Path=., Converter={StaticResource testConverter}}" />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

My converter is:
```
public class TestConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new NotImplementedException();
    }
}
```
2. Debug in "public object Convert(object value, Type targetType, object parameter, CultureInfo culture)"

### Expected Behavior
I think that Convert function should receive, the bindingcontext of viewcell,  in value parameter.
### Actual Behavior
Value parameter in Convert function receives null.

### Basic Information
- Version with issue: Xamarin.Forms 3.0.0.354232-pre3 with NetStandard.
- Last known good version: 
- IDE: Visual Studio 2017 15.6.4 and Visual Studio 2017 Mac.
- Platform Target Frameworks:
  - iOS:  11.3
  - Android: 8.0
  - UWP:  Not tested.
- Android Support Library Version
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[TestBindingConverter.zip](https://github.com/xamarin/Xamarin.Forms/files/1915396/TestBindingConverter.zip)

**Comment by StephaneDelcroix** [comment]
It is possible for the context to be null at first, when the cell is created. the context is applied later on. can you confirm that the context is ALWAYS null ? thanks

**Comment by andreinitescu** [comment]
Wondering if it's related to https://github.com/xamarin/Xamarin.Forms/issues/1803

**Comment by zoilder** [comment]
You're right.

It call twice. First call with null and second call with bindingcontext.

I close issue.

Thank you very much and sorry for my misunderstanding about that.
