### ISSUE TITLE
[iOS] Removing item from ObservableCollection causes app closure

### ISSUE THREAD

**Issue by Yelnik** [xamarin/Xamarin.Forms#2481]
### Description
Attempting to remove an item from an ObservableCollection list causes an un-catchable exception that closes the application. Note, this issue existed in a previous combination of iOS SDK and Xamarin.Forms package but was fixed.

### Steps to Reproduce

1. Create an ObservableCollection list of a simple class (i.e. class MyClass { string _name; int _id; } - Something like this
2.  Add 1 item to the list
3.  Obtain a reference to this item in any way: (ex: var itemRef = _deviceList.First(x => x._name == ConnectedDevice.Name);     OR obtain the index of the item with `IndexOf`
4. Attempt to remove the item with `.Remove` or `.RemoveAt`

### Expected Behavior
I expect the item to be removed and the application to continue
### Actual Behavior
The application fails fatally with the following messages in the Debug window:

2018-04-16 15:50:57.099 TSApp.iOS[1844:127772] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3698.52.10/UITableView.m:1685
[0:] Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: attempt to delete row 0 from section 0 which only contains 0 rows before the update
Native stack trace:
	0   CoreFoundation                      0x0000000183ebada4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001830745ec objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183ebabf8 <redacted> + 0
	3   Foundation                          0x00000001848aafa0 <redacted> + 112
	4   UIKit                               0x000000018dbb1200 <redacted> + 4608
	5   UIKit                               0x000000018dbaff10 <redacted> + 92
	6   TSApp.iOS                      0x0000000104dd7738 wrapper_managed_to_native_ObjCRuntime_Messaging_void_objc_msgSend_intptr_intptr + 104
	7   TSApp.iOS                      0x0000000104d72448 UIKit_UITableView_EndUpdates + 40
	8   TSApp.iOS                      0x00000001052c3050 Xamarin_Forms_Platform_iOS_ListViewRenderer_UpdateItems_System_Collections_Specialized_NotifyCollectionChangedEventArgs_int_bool + 2448
	9   TSApp.iOS                      0x00000001052bf738 Xamarin_Forms_Platform_iOS_ListViewRenderer_OnCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 120
	10  TSApp.iOS                      0x000000010555683c Xamarin_Forms_Internals_TemplatedItemsList_2_TView_REF_TItem_REF_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 172
	11  TSApp.iOS                      0x000000010555b7d8 Xamarin_Forms_Internals_TemplatedItemsList_2_TView_REF_TItem_REF_OnProxyCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs_bool + 8456
	12  TSApp.iOS                      0x00000001055596a4 Xamarin_Forms_Internals_TemplatedItemsList_2_TView_REF_TItem_REF_OnProxyCollectionChanged_object_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 116
	13  TSApp.iOS                      0x00000001054712e0 Xamarin_Forms_ListProxy_OnCollectionChanged_System_Collections_Specialized_NotifyCollectionChangedEventArgs + 176
	14  TSApp.iOS                      0x0000000105473758 Xamarin_Forms_ListProxy__c__DisplayClass33_0__OnCollectionChangedb__0 + 152
	15  TSApp.iOS                      0x0000000104d425d4 Foundation_NSAsyncActionDispatcher_Apply + 36
	16  TSApp.iOS                      0x0000000104c98368 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 248
	17  TSApp.iOS                      0x00000001069c498c mono_jit_runtime_invoke + 796
	18  TSApp.iOS                      0x0000000106a40bb8 mono_runtime_invoke_checked + 148
	19  TSApp.iOS                      0x0000000106a4427c mono_runtime_invoke + 80
	20  TSApp.iOS                      0x00000001049cca08 _ZL30native_to_managed_trampoline_1P11objc_objectP13objc_selectorPP11_MonoMethodj + 232
	21  TSApp.iOS                      0x00000001049cd0ec -[__MonoMac_NSAsyncActionDispatcher xamarinApplySelector] + 52
	22  Foundation                          0x00000001849060ec <redacted> + 340
	23  CoreFoundation                      0x0000000183e63404 <redacted> + 24
	24  CoreFoundation                      0x0000000183e62c2c <redacted> + 276
	25  CoreFoundation                      0x0000000183e6079c <redacted> + 1204
	26  CoreFoundation                      0x0000000183d80da8 CFRunLoopRunSpecific + 552
	27  GraphicsServices                    0x0000000185d63020 GSEventRunModal + 100
	28  UIKit                               0x000000018dd6178c UIApplicationMain + 236
	29  TSApp.iOS                      0x0000000104de1f80 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 368
	30  TSApp.iOS                      0x0000000104d6a93c UIKit_UIApplication_Main_string___intptr_intptr + 44
	31  TSApp.iOS                      0x0000000104d6a8fc UIKit_UIApplication_Main_string___string_string + 172
	32  TSApp.iOS                      0x0000000104a01484 TSApp_iOS_Application_Main_string__ + 164
	33  TSApp.iOS                      0x0000000104c98368 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 248
	34  TSApp.iOS                      0x00000001069c498c mono_jit_runtime_invoke + 796
	35  TSApp.iOS                      0x0000000106a40bb8 mono_runtime_invoke_checked + 148
	36  TSApp.iOS                      0x0000000106a468f8 mono_runtime_exec_main_checked + 120
	37  TSApp.iOS                      0x00000001069a79a4 mono_jit_exec + 268
	38  TSApp.iOS                      0x0000000106b2f088 xamarin_main + 2220
	39  TSApp.iOS                      0x0000000104a01364 main + 96
	40  libdyld.dylib                       0x0000000183811fc0 <redacted> + 4
The app has been terminated.
Failed to Stop app:  An error occured on client IDB490753 while executing a reply for topic xvs/idb/4.9.0.753/stop-app
The app has been terminated.

### Basic Information

- Version with issue: Version of what?
- Last known good version:
- IDE: Visual Studio 2017 Professional
- Platform Target Frameworks: iOS targets 11.3
  - iOS:  11.9.1.24
  - Android: Does not affect Android
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 2.5.1.444934
- Affected Devices:

**Comment by samhouts** [comment]
Does this describe the issue you're having?

https://github.com/xamarin/Xamarin.Forms/issues/2473

**Comment by Yelnik** [comment]
That doesn't look to be quite the same as I am not getting a `System.ArgumentOutOfRangeException`, I would probably be able to catch that if I were. The 'exception' I'm getting fully closes my application and cannot be caught in a try/catch block

**Comment by samhouts** [comment]
I have created a sample project to try to reproduce this issue, but it does not throw an error. Can you please try the project and add to it until you see the issue described? Thank you!

[Issue2481.zip](https://github.com/xamarin/Xamarin.Forms/files/1921992/Issue2481.zip)

**Comment by Yelnik** [comment]
To be honest, I don't even know how to build that project.

It looks like

**Comment by Yelnik** [comment]
To be honest I don't know how to build that project

It seems like the class the ObservableCollection is holding has to have objects from a bluetooth library I'm using to cause that crash when using .Remove

**Comment by samhouts** [comment]
Are you able to create and post your own reproduction then? It would be very helpful. Thanks

**Comment by PureWeen** [comment]
Closing for now. If you can provide a repro and are still having this issue we can re open

**Comment by CarlosHSantos** [comment]
Same error here!

**Comment by goedware** [comment]
In latest XF version (**4.5.0.617**) using `ObservableCollection.RemoveAt(index)` with a valid index raises `ArgementOutOfRangeException`.
It is iOS only. On Android that code it is working fine.
The ObservableCollection is bound to the `ItemsSource `of a `CarouselView`
