### ISSUE TITLE
Animating a `View` that is currently animating will throw  `System.InvalidOperationException`:

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#2482]
### Description
Animating a `View` that is currently animating will throw  `System.InvalidOperationException`:

>TaskCompletionSource[TResult].SetResult (TResult result)
System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.

### Steps to Reproduce

1. Download/Clone sample app reproduction: https://github.com/brminnick/AnimationCrashReproductionSample
2. Build/Deploy AnimationCrashReproductionSample to an Android or iOS emulator/device
3. Quickly double-tap the button on the screen to induce the Exception

### Expected Behavior

The animating Task should be canceled gracefully, avoiding the Exception.

### Actual Behavior

Performing an animation on a `View` that is currently animating will throw  `System.InvalidOperationException`:

### Basic Information

- Version with issue: v2.5.1.444934
- Last known good version: Never
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.1
  - UWP:  Unknown
- Android Support Library Version: v27.0.2
- Nuget Packages: Xamarin.Forms
- Affected Devices: iOS, Android, UWP

### Screenshots

https://github.com/brminnick/Videos/blob/master/AnimationCrashReproductionSample/AnimationCrashReproductionSample.gif

### Reproduction Link

https://github.com/brminnick/AnimationCrashReproductionSample

**Comment by samhouts** [comment]
Confirmed on 2.4.0, 2.5.0, and 2.5.1.

**Comment by hartez** [comment]
Related: https://bugzilla.xamarin.com/show_bug.cgi?id=41016
