### ISSUE TITLE
Custom ResourceDictionary throws ArgumentException with Xamarin.Forms 2.5 or higher

### ISSUE THREAD

**Issue by APopatanasov** [xamarin/Xamarin.Forms#2483]
### Description
Custom ResourceDictionary throws ArgumentException when merging with another dictionary and a resource from that dictionary is overridden
### Steps to Reproduce

1. Create a custom ResourceDictionary for example:
` public class TestResourceDictionary : ResourceDictionary { public TestResourceDictionary() {  } } `
2. Merge the custom ResourceDictionary with another that contains some resources:
`<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="ThemingExample.Custom"><Color x:Key="ListViewItemBorderColor">Blue</Color> </ResourceDictionary>`
3. Override the "ListViewItemBorderColor" resource:
`<local:TestResourceDictionary MergedWith="local:Custom"><Color x:Key="ListViewItemBorderColor">Orange</Color></local:TestResourceDictionary>`

### Expected Behavior
The "ListViewItemBorderColor" should change its value to Orange.
### Actual Behavior
ArgumentExecption is thrown: System.ArgumentException: A resource with the key 'ListViewItemBorderColor' is already present in the ResourceDictionary.
### Basic Information

- Version with issue: introduced with **2.5** and still can be reproduced with **3.0**
- Last known good version: **2.4**
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android:  8.1
  - UWP:  16299
- Android Support Library Version: v27.0.2
- Nuget Packages: Xamarin.Forms
- Affected Devices: -

### Reproduction Link

Here is a sample project reproducing the issue:
[ThemingExample.zip](https://github.com/xamarin/Xamarin.Forms/files/1918421/ThemingExample.zip)

**Comment by StephaneDelcroix** [comment]
this is a Xaml parsing issue, and not a ResourceDictionary issue. the workaround is defining and assigning RDs in code.
