### ISSUE TITLE
[Android] Using a page renderer on Android completely breaks the UI

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2489]
### Description
While creating a sample for a different bug, I came across a very odd issue.

The sample app is just a content page in a navigation page with a button to go to a tabbed page with two tabs. 

If you have the page renderer enabled (the renderer just has a WriteLine), when you press the button to go to the tabbed page, the tabbed page comes up all messed up (see screen shots). If you remove the renderer, it works fine. No issues on iOS.

### Steps to Reproduce

Load app.
Press the "press me" button
Note that the button is still on the page and text is displayed on top of it
Go the the android APageRenderer class and remove the ExportRenderer
Load app and press the button again
Note that the tabbed page looks fine 

### Expected Behavior
App loads the tabbed page without issue

### Actual Behavior
UI is messed up 

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  no
  - Android: yes
  - UWP:  not tested
- Android Support Library Version: 26
- Nuget Packages: just forms
- Affected Devices: Tested on Nexus 5x on Android 8 and iPhone 6 running iOS 9.3

### Screenshots
https://imgur.com/a/7fIAu

### Reproduction Link
https://www.dropbox.com/s/b0l0vojl273ffrj/tabpagesamplebug.zip?dl=0

**Comment by Paul-Brenner-Tangoe** [comment]
@davidortinau I know you guys have loads of bugs that need to be worked on, but can this please be looked at. This is a extremely bad bug. I modified the sample project so that that main page is a tabbedpage, and when you have the renderer enabled, the tabs don't appear anymore. The renderer is doing nothing, it makes no sense. I am completely stuck until this is fixed. See screenshots: https://imgur.com/a/It0Eo

Apologies for the ping @adrianknight89 but you are really good at fixing stuff.

**Comment by samhouts** [comment]
You're replacing the renderer for every kind of `Page` with a `PageRenderer`. The `PageRenderer` doesn't know how to draw tabs. The `TabbedRenderer` knows how to draw tabs. You need to create a custom renderer for each kind of `Page` subclass you want to override and use the proper renderer. `PageRenderer` is meant for generic `Page`s, typically `ContentPage`s.


Here are the renderers we use:
```
[assembly: ExportRenderer(typeof(TabbedPage), typeof(TabbedRenderer))]
[assembly: ExportRenderer(typeof(NavigationPage), typeof(NavigationRenderer))]
[assembly: ExportRenderer(typeof(CarouselPage), typeof(CarouselPageRenderer))]
[assembly: ExportRenderer(typeof(Page), typeof(PageRenderer))]
[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(PhoneMasterDetailRenderer), UIUserInterfaceIdiom.Phone)]
[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(TabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)]
```

**Comment by Paul-Brenner-Tangoe** [comment]
@samhouts @jassmith Please re-open- this is 100% a bug

You guys talk about not wanting to do breaking changes all the time, I did some investigating and found that this works completely fine on version 2.2.0.45. It breaks on 2.3.0.34-pre1 on. This is a breaking change.

I understand that a PageRenderer doesn't know how to to draw tabs, but the internal TabbedRenderer should get called, as well as my PageRenderer, and since the PageRenderer does absolutely nothing, the tabs should still get drawn.

The TabbedPage is just an example, this breaks the UI on every single kind of page. 

Every app has mixes of different kind of pages. If this truly is by design, and you don't care this works fine on 2.2, then doing an ExportRenderer for a Xamarin.Forms.Page should give a compile error and not be allowed, since it breaks every single page that is not a ContentPage.

Or it should be changed to do what #2490 does, and it should not be called on any page but ContentPage. Wouldn't you at least want the iOS and Android behavior to match?

**Comment by jassmith** [comment]
Im looking into this now, please calm

**Comment by jassmith** [comment]
This is actually broken due to the switch to AppCompat. We will make the change to make sure AppCompat renderers of a more derived type are not overwritten by renderers of a less derived type.

**Comment by Paul-Brenner-Tangoe** [comment]
@jassmith apologies, what do you mean by "more derived type are not overwritten by renderers of a less derived type"? Are you changing it so Android matches iOS (and only gets called for ContentPages?)

**Comment by samhouts** [comment]
Yes, that's the original behavior, and that's the behavior we will restore.

**Comment by jassmith** [comment]
Correct.

A better way to explain this is how it would work for Buttons (again lets ignore any oddities currently caused by AppCompat).

Lets assume we have a custom button:

```csharp
public class ShinyButton : Button {}
```

Now if we want to make a renderer for it we do:

```csharp
[assembly: ExportRenderer (typeof(ShinyButton), typeof(ShinyButtonRenderer))]

public class ShinyButtonRenderer : ... {}
```

In this case then we get the following renderers:

```csharp
var button = new Button (); // uses stock ButtonRenderer
var shinyButton = new ShinyButton (); // uses ShinyButtonRenderer
```

Now lets say you export your own ButtonRenderer as well

```csharp
[assembly: ExportRenderer (typeof(Button), typeof(StockButtonRenderer))]

public class StockButtonRenderer : ... {}
```

Great! Now lets look at out two controls again:

```csharp
var button = new Button (); // uses stock StockButtonRenderer
var shinyButton = new ShinyButton (); // uses ShinyButtonRenderer
```

ShinyButton still gets teh ShinyButtonRenderer because ShinyButtonRenderer is exported to the more derived type (ShinyButton is more derived than Button). StockButtonRenderer replaces the Xamarin.Forms ButtonRenderer because you clobbered it with your export, however it gets used in the same cases where our renderer would have been used.

**Comment by jassmith** [comment]
In this case the error is the way Xamarin.Forms is inserting the AppCompat renderers allows for them to get clobbered by less derived types by mistake.
