### ISSUE TITLE
[iOS] PageRenderer is not called on TabbedPage and NavigationPage

### ISSUE THREAD

**Issue by Paul-Brenner-Tangoe** [xamarin/Xamarin.Forms#2490]
### Description
A PageRenderer with the ExportRenderer set to be called on a Xamarin.Forms.Page is not called for TabbedPages and NavigationPages on iOS. On Android it does get called.

### Steps to Reproduce

Run app in debug mode on iOS
There is a WriteLine call in the PageRenderer. Note that on iOS it outputs:
Main - the first page
Press the "press me" button. It loads the tabbed page with 2 tabs
Note it outputs:
One - that's the first tab
Two- that's the second tab

Repeat on Android (see note)
Note it outputs:
nav - that's the navigation page the main page is wrapped in
main - the first page
tab - that's the tabbed page
tabone - that's the navigation page that the first tab is wrapped in
one - the first tab
tabtwo - that's the navigation page that the second tab is wrapped in
two - the second tab

### Expected Behavior
The PageRenderer gets hit for everything that inherits from Xamarin.Forms.Page

### Actual Behavior
It only seems to get hit for ContentPages

Note: Ignore the broken UI on Android, that's from bug #2489. This is an extremely frustrating bug because as a workaround I need to duplicate a lot of code in my renderers, can we please get a hotfix for this?

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  yes
  - Android: no
  - UWP:  not tested
- Android Support Library Version: 26
- Nuget Packages: just forms
- Affected Devices: Tested on Nexus 5x on Android 8 and iPhone 6 running iOS 9.3

### Reproduction Link
https://www.dropbox.com/s/b0l0vojl273ffrj/tabpagesamplebug.zip?dl=0

**Comment by samhouts** [comment]
I don't have an answer for why this appears to behave in the opposite manner as #2489, but if iOS did use this renderer for all types inheriting from `Page`, then you would have the same problem that you do on Android--no tabs because a `PageRenderer` can't draw tabs. 

You need to create different renderers for each page type. Here's what we use on iOS:

```
[assembly: ExportRenderer(typeof(TabbedPage), typeof(TabbedRenderer))]
[assembly: ExportRenderer(typeof(NavigationPage), typeof(NavigationRenderer))]
[assembly: ExportRenderer(typeof(CarouselPage), typeof(CarouselPageRenderer))]
[assembly: ExportRenderer(typeof(Page), typeof(PageRenderer))]
[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(PhoneMasterDetailRenderer), UIUserInterfaceIdiom.Phone)]
[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(TabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)]
```

**Comment by Paul-Brenner-Tangoe** [comment]
@samhouts in the same way that a ButtonRenderer gets called for every class that inherits from a Button,
a user would expect that a custom renderer for a Xamarin.Forms.Page should get called for every class that inherits from a Page.

If this truly is by design, then please update the docs for custom renders that says,

"A ExportRenderer set for a Xamarin.Forms.Page will only get called for ContentPages" 

Because that is not expected behavior at all.

**Comment by jassmith** [comment]
This is actually broken due to the switch to AppCompat. We will make the change to make sure AppCompat renderers of a more derived type are not overwritten by renderers of a less derived type.

**Comment by jassmith** [comment]
Oops I did this to the wrong bug

**Comment by albertonpa-npauctions** [comment]
I'm having the same issue, calling a custom rendered on a TabbedPage. The event subscription on my CustomRenderer its not being invoked.
