### ISSUE TITLE
Xamarin Forms Android app crash on boot in Release config with ProGuard on after updated to 27.0.2

### ISSUE THREAD

**Issue by motoko89** [xamarin/Xamarin.Forms#2491]
### Description
This happens after I upgraded `Xamarin.Android.Support.*` packages to version 27.0.2. App works when I build and run in Debug but failed when published to the Store. I tried Release config and it indeed crashes on boot

I followed the suggestion here https://bugzilla.xamarin.com/show_bug.cgi?id=36287 and turned off ProGuard for Release config

### Steps to Reproduce

1. Create Xamarin Forms project
2. Update all packages to the latest version
3. Turn on Proguard in Release Config
4. Build in Release and deploy to physical device

### Expected Behavior

Not crash on boot

### Actual Behavior

Crash on boot

### Basic Information

- Version with issue: `Xamarin.Android.Support.*` 27.0.2
- Last known good version: `Xamarin.Android.Support.*` 26.1.0.1
- IDE: VS for Mac 7.4.3 (build 10) Stable Channel
- Platform Target Frameworks: 
  - iOS:  
  - Android: target API Level 27
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 2.5.0.280555
- Affected Devices: all Android versions

**Comment by PureWeen** [comment]
Can you try some of the suggestions I made in this thread

https://github.com/xamarin/Xamarin.Forms/issues/2457

I have a couple projects running with *27.0.2* and they aren't having any issues

**Comment by motoko89** [comment]
@PureWeen  thanks! I will try it out

**Comment by PureWeen** [comment]
from @jonathanpeppers 
> there is now a way to include proguard files in a NuGet, I believe.
I bet Xamarin.Forms needs to ship something like: `-keep class android.support.v7.widget.** { public *; }` making sure we only include as little as needed

From this thread https://github.com/xamarin/Xamarin.Forms/issues/2495

It looks like 
```
-keep class android.support.v7.widget.FitWindowsFrameLayout { *; }
-dontwarn android.support.v7.widget.FitWindowsFrameLayout
```

Was enough to resolve the issue

**Comment by PureWeen** [comment]
Closing this issue for now. Please comment if you are still having issues and Proguard didn't resolve
