### ISSUE TITLE
Xamarin Forms Template missing

### ISSUE THREAD

**Issue by NidhieRaichura** [xamarin/Xamarin.Forms#2492]
### ISSUE:  Xamarin Forms Template missing

Not able to create new Xamarin forms project in VS 2017. I even tried reinstalling Xamarin in Visual Studio. 

Also a couple of days back my WebView application was running in debug mode absolutely fine in the emulator. But now the same solution is throwing the following error.

### - Last known good version: 
   IDE: VS 2017 15.5.7
   Xamarin Designer: 4.8.188
   Android: 8.1.5.0
   iOS: 11.6.1.4

### - Version with issue: 
 IDE: Microsoft Visual Studio Professional 2017 v15.6.6
 Platform Target Frameworks: Microsoft .Net Framework v4.7.02558
 Xamarin: v4.9.0.753   
 iOS:  11.9.1.24
 Android: 8.2.0.16
 Xamarin Designer v4.10.96

### Current Version
![xamarinformsmissing](https://user-images.githubusercontent.com/21195822/38913120-ac22a478-42f6-11e8-9ee2-84f93a054136.PNG)

### Older Version
![xamarinolderversion](https://user-images.githubusercontent.com/21195822/38914118-d135fbac-42fb-11e8-85b7-6274cadc1e44.png)

**Comment by samhouts** [comment]
Can you confirm that the Mobile Development with .NET option is checked in the Visual Studio Installer? 

To check, open the Visual Studio Installer and click Modify on your installation.

![image](https://user-images.githubusercontent.com/7827070/38948472-965ccd14-42f4-11e8-81ab-d4a409ad92b0.png)

**Comment by NidhieRaichura** [comment]
Hi samhouts,
As mentioned above, I uninstalled it and reinstalled the Mobile Development with .NET. Still the issue persists.

**Comment by juluvanahd** [comment]
Reinstall windows or format your drive.

**Comment by samhouts** [comment]
Reinstalling Windows seems a bit extreme. Let me confer with the Visual Studio team and see if they have a better suggestion.

**Comment by jimmgarrido** [comment]
I am following up via email to gather additional logs.

**Comment by NidhieRaichura** [comment]
Hi guys! I wrote up to Microsoft and found the solution to this issue. 
The template had been disabled by default, probably during an update and failed to enable later.
It can be enabled in Visual Studio in :
# Tools > Extensions and Updates

![image](https://user-images.githubusercontent.com/21195822/39510667-19c86e10-4e08-11e8-96c3-7a8e14c527b2.png)

**Comment by pauldipietro** [comment]
Closing as this seems resolved.
