### ISSUE TITLE
[Android] Updated to latest Xamarin.Android.Support packages, release APK generated is now non-functioning

### ISSUE THREAD

**Issue by Yelnik** [xamarin/Xamarin.Forms#2495]
### Description
Several Xamarin.Android.Support packages were version 26.1.0.1, I updated the packages to the current version 27.0.2, and the release APK generated is now 8 MB less than the debug build and crashes immediately on run

Debug build is 45156kb, release is 37217kb - This discrepancy was never the case before updating the Nuget packages

The project configurations are the same for the debug and release build

### Steps to Reproduce

1. Update Android support Nuget packages to latest
2. Build in release and attempt to run
3. 

### Expected Behavior
I expect the application to be runnable

### Actual Behavior
The app crashes immediately

### Basic Information

- Version with issue: Xamarin.Android support libraries of version 27.0.2
- Last known good version: 26.1.0.1
- IDE: VS 2017 Professional
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.2.0.16
  - UWP:   
- Android Support Library Version: 27.0.2
- Nuget Packages:
- Affected Devices: All

**Comment by Yelnik** [comment]
I don't even know where I would be able to see what the exception is since it's only in release that this happens

But it looks like if I disable ProGuard it does run properly

**Comment by Yelnik** [comment]
It's look like it's probably `Didn't find class "android.support.v7.widget.FitWindowsFrameLayout`

**Comment by PureWeen** [comment]
So in your progaurd.cfg class you can add
```
-keep class android.support.v7.widget.** { *; }
-dontwarn android.support.v7.widget.*
```

or be more specific with
```
-keep class android.support.v7.widget.FitWindowsFrameLayout { *; }
-dontwarn android.support.v7.widget.FitWindowsFrameLayout
```

and that should fix it for you

**Comment by Yelnik** [comment]
Actually, I don't have a CFG for ProGuard, I see there's one generated in `\obj\Release\proguard`, but editing that doesn't seem to have worked, and there's a lot more lines in it than I'd have expected

How do I go about adding one, or should I in this case?

**Comment by PureWeen** [comment]
this talks about adding the proguard file

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=vswin

it's pretty easy the only caveat is if  you're on windows to be sure to read this part
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=vswin#troubleshooting

**Comment by Yelnik** [comment]
My only concern is all of the configurations that were generated automatically, if I specify my own configuration, will these be lost? Or should I copy what's in the automatically generated one into my own?

**Comment by PureWeen** [comment]
no they won't be lost
it'll use both

**Comment by Yelnik** [comment]
Ok great, thanks a lot
