### ISSUE TITLE
Desktop: titlebar customization

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#2505]
Open a random desktop application and look at the titlebar. It probably is customized with icons, dynamic text, and buttons.

Xamarin Forms should have a way to customize a TitleBar by setting a View as the TitleBar.

On native UWP the relevant methods are:
`CoreApplicationViewTitleBar.ExtendViewIntoTitleBar`
`Window.Current.SetTitleBar(UIElement value)`

Platforms: UWP, WPF, MacOS, Linux

**Comment by samhouts** [comment]
Somewhat related to https://github.com/xamarin/Xamarin.Forms/issues/1716

**Comment by charlesroddie** [comment]
I changed my mind about adding this to Xamarin.Forms. Better to Keep Xamarin.Forms simple.

The following code inside OnLaunched in App.Xaml.cs hides the titlebar.

```csharp
ApplicationViewTitleBar formattableTitleBar = Windows.UI.ViewManagement.ApplicationView.GetForCurrentView().TitleBar;
formattableTitleBar.ButtonBackgroundColor = Colors.Transparent;
CoreApplicationViewTitleBar coreTitleBar = CoreApplication.GetCurrentView().TitleBar;
coreTitleBar.ExtendViewIntoTitleBar = true;
```
