### ISSUE TITLE
[macOS] MasterDetailPage: default MasterBehavior doesn't show Master page

### ISSUE THREAD

**Issue by patridge** [xamarin/Xamarin.Forms#2507]
### Description

When using a MasterDetailPage in macOS, there appears to be no `MasterBehavior.Popover` implementation. This could be intended, but it also appears the behavior for `MasterBehavioir.Default` is `Popover`, so macOS users cannot view the master page at all.

### Steps to Reproduce

1. File > New > Blank Forms App
2. Add new macOS project (per [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac#missing-xamarinforms-features) or [blog post](https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/))
3. Add a MasterDetailPage implementation
4. Set the master-detail page to use `MasterBehavior.Default`
5. Run on macOS to see missing master page

### Expected Behavior

Being a desktop platform, I expected the default to be the same as `MasterBehavior.Split`, showing the master page alongside the initial detail page.

### Actual Behavior

The master page is not shown, and there doesn't appear to be any way to view it by dragging in from the edge of any side of the app window.

### Basic Information

- Version with issue: confirmed in 2.5.1.x and 3.0.0.354232-pre3
- Last known good version: none found
- IDE: VSMac
- Platform Target Frameworks: macOS
  - macOS: 4.2.1.28
- Nuget Packages: just Forms and File>New defaults
- Affected Devices: MacBook Pro

### Screenshots

Result of `MasterBehavior.Default` or `MasterBehavior.Popover`:
![image](https://user-images.githubusercontent.com/713665/39009149-16e2c848-43c8-11e8-986b-162d96f3b7be.png)

Result of `MasterBehavior.Split`:
![image](https://user-images.githubusercontent.com/713665/39009140-1072b518-43c8-11e8-830e-65478210f088.png)

> Note: the Y-flipped issue shown here has been resolved by wrapping the detail content in a container view.

### Reproduction Link

While this isn't the same as the steps above, it's very close. This is a course exercise for Xamarin University's XAM290 course where we explore `MasterBehavior`. It's also the source of the above screenshots.

https://github.com/XamarinUniversity/XAM290/tree/3876fdea03b76fa3a137e5114a075c8b09184317

**Comment by ShahroozAnsari** [comment]
@samhouts  when this problem solved and i can use it ? I have project Base on it

**Comment by DennisWelu** [comment]
In fact here is the key line in the MasterDetailPageRenderer.cs for MacOS: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.MacOS/Renderers/MasterDetailPageRenderer.cs#L149

And here is the equivalent line in the MasterDetailPageRenderer.cs for UWP: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/MasterDetailPageRenderer.cs#L347

The only logic difference is the allowance of Popover behavior on UWP.

**Comment by BradChase2011** [comment]
@DennisWelu Agreed, this code breaks our master details as well.  Will be changing the code on our fork.
