### ISSUE TITLE
TriggerAction Properties of type uint Can't be Compiled on Build When Set in xaml

### ISSUE THREAD

**Issue by sonic1015** [xamarin/Xamarin.Forms#2508]
### Description

When a TriggerAction Property is set in Xaml, the code cannot be compiled when XamlCompilation is enabled. (Works fine when disabled).

### Steps to Reproduce

1. Compile Attached Code
2. Uncomment the Trigger Action with a Property
3. Try to Build

### Expected Behavior

Code Compiles

### Actual Behavior

Build Fails with "error : opcode"

### Basic Information

- Version with issue: Tested on 2.5.0 & 2.5.1
- Last known good version: unknown
- IDE: VS 2017 15.6.6
- Platforms Effected: All

### Reproduction Link

https://github.com/sonic1015/bugRepo/releases/tag/2

**Comment by samhouts** [comment]
If you change your property type to be an `int` instead of a `uint`, it works fine. It looks like we don't have implicit support for `uint`. Thanks
