### ISSUE TITLE
Pin.Clicked does not work

### ISSUE THREAD

**Issue by fhnaseer** [xamarin/Xamarin.Forms#2509]
### Description
Event listener is not triggered for Pin.Clicked event,
Looks like this bug is opened again,
https://bugzilla.xamarin.com/show_bug.cgi?id=25557

### Steps to Reproduce

1. var pin = new Pin()...
2. pin.Clicked += PinOnClicked;
3. Map.Pins.Add(pin)

### Expected Behavior
PinOnClicked should be triggered,

### Actual Behavior
PinOnClicked is not called. Event is not triggered on clicking pin in the map,

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: Don't know
- IDE: Visual Studio 2017 (15.6.6)
- Platform Target Frameworks:
  - Android: 8.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
At least on Android, it looks like the `Clicked` event is fired when you tap on the `Pin` label, not the `Pin` itself.

**Comment by samhouts** [comment]
I'm not fully sure if this is an actual bug or a documentation issue. We need to define expectations for this behavior.

**Comment by fhnaseer** [comment]
I verified it. Event is fired on label tap. In that case Clicked should be ranemed to LabelClicked or something else,
