### ISSUE TITLE
[Enhacement] Preserve page backstack

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#2510]
### Rationale
Xamarin Forms should preserve the page navigation backstack. This becomes critical for the user experience.

A common example is of an editor app which has a screen where the user takes notes in a document, When user navigates away to another app, if the OS is low in memory, the OS will destroy the UI views of the editor app. When user navigates back to the editor app, the user should see the same screen with the notes editor. 

There's currently no way to recreate the page backstack in XF without actually reconstructing each Page and pushing the page to the navigation. Which is not desired. Doing so has different implications. For example the user will see screens being created and navigated away, not pretty at all. Another option might be for the app to keep and preserve its own internal navigation stack. Not easy, it's something which should be really in the framework.

### Implementation
The framework should keep track and preserve page navigation. There should be an internal virtual navigation stack. When the native top-level view is recreated, the framework should recreate and show last page in the navigation stack as well, similarly to how the native works. 

I can see at least one decision to take: the Page list given by `NavigationStack` property. Currently the list is of Page instances. In the case of preserving the navigation stack, I don't think still having Page instances would work. So either a) change from IReadOnlyList<Page> to something like IReadOnlyList<IPage> or b) consider that the list only containes materialized Page's (which means it would be empty when user navigates back to the editor app in my example).

### Backward Compatibility
Not sure

**Comment by bentmar** [comment]
Cant this be fixed with a viewmodel that lives forever?

**Comment by andreinitescu** [comment]
It's not a view-model issue. The core of the problem is how to recreate the Page navigation stack. 

Consider a simple example of an app which has a NavigationPage as root page:
1. Use opens the XF app. App navigates to Page1.
2. From Page1, user navigates to Page2
3. User navigates away from the XF app to home screen.
4. Suppose we're on Android. OS destroys the Activity at this point. This can be mimicked in Android in developer options by enabling the option to destroy Activities.
5. User hits back button. Activity is recreated, XF is created, Page1 is shown. Instead, we should see Page2. Hitting hardware or software back button on Page2 should navigate back to Page1

**Comment by nadjibus** [comment]
I think Xamarin.Forms already has Navigation.InsertPageBefore to remove the need to push one page after another, so the flow will be like this:

1. Display your top most page.
2. Add all hierarchy by calling Navigation.InsertPageBefore(previousPage, this);

InsertPageBefore will add a page in the navigation stack in the background, so the user won't notice anything (no animation or something). I already implemented this on several apps and it works very good, for eg. on tapping a chat message push notification, the app starts directly with the chat page, then when user taps back, it returns to the main page instead of closing the app.

**Comment by andreinitescu** [comment]
@nadjibus Thanks a lot for your comment. `InsertPageBefore` is a nice idea! 
But it's not the ideal solution in my opinion. The right solution would be  not having to create any `Page` at all, except of course the top page.

**Comment by jfversluis** [comment]
I don't think this is something that will be fixed anymore for Xamarin.Forms at this stage. Thank everyone for the input here!
