### ISSUE TITLE
Unable to build Xamarin.Forms project if directory contains '#' character.

### ISSUE THREAD

**Issue by mrward** [xamarin/Xamarin.Forms#2511]
### Description

Build fails if part of the path containing the Xamarin.Forms project contains a # character.

### Steps to Reproduce

1. Open Visual Studio for Mac 7.4 to create a Xamarin.Forms class library (New Project dialog - Multiplatform - Library - Xamarin.Forms - Class Library)
2. Create the new solution so that it will be created in a directory where one part of its path contains a # character (.e.g. ~/Projects/Tests/c#/MySolution/MyProject)
3. Build the project using Visual Studio for Mac or using msbuild from the command line.

### Expected Behavior

Project builds without error.

### Actual Behavior

Build fails with error about being unable to load the XamCTask. If the # character is removed from the directory then the build succeeds.
```
  ~/Projects/Tests/we#gwaeg23wge/packages/Xamarin.Forms.2.5.0.121934/build/portable-win+net45+wp80+win81+wpa81/Xamarin.Forms.targets(103,3): error MSB4061: The "XamlCTask" task could not be instantiated from "~/Projects/Tests/we#gwaeg23wge/packages/Xamarin.Forms.2.5.0.121934/build/portable-win+net45+wp80+win81+wpa81/Xamarin.Forms.Build.Tasks.dll". Could not load file or assembly 'Xamarin.Forms.Build.Tasks' or one of its dependencies [~/Projects/Tests/we#gwaeg23wge/wegwaeg23wge/wegwaeg23wge.csproj]
  ~/Projects/Tests/we#gwaeg23wge/packages/Xamarin.Forms.2.5.0.121934/build/portable-win+net45+wp80+win81+wpa81/Xamarin.Forms.targets(103,3): error MSB4060: The "XamlCTask" task has been declared or used incorrectly, or failed during construction. Check the spelling of the task name and the assembly name. [~/Projects/Tests/we#gwaeg23wge/wegwaeg23wge/wegwaeg23wge.csproj]
```
Tried a few different versions of Xamarin.Forms:

 - 2.5.0.121934
 - 2.5.1.444934
 - 3.0.0.354232-pre3

Also tried Microsoft.Bcl.Build, which has its own task dll that gets loaded, and that seems to work when the directory contains a # character.

**Comment by StephaneDelcroix** [comment]
the XamlCTask is not the first task loaded, and the other ones do not report error ?

**Comment by StephaneDelcroix** [comment]
Can't repro...

**Comment by mrward** [comment]
Note that this affects projects that use a packages.config file. PackageReference projects do not load the Xamarin.Forms.Build.Tasks.dll from the solution's packages directory but from ~/.nuget/packages so the problem does not happen if you are using PackageReferences. The latest VS Mac 7.5 creates .NET Standard projects using PackageReferences. So VS Mac 7.4 should be used, or alternatively a PCL project can be created, then Xamarin.Forms added, then a .xaml file added.
