### ISSUE TITLE
Android: unable to disable arrow/hamburger transition animations when using a custom icon

### ISSUE THREAD

**Issue by Goldstrike** [xamarin/Xamarin.Forms#2513]
### Description
I would like to use a "custom" icon instead the default  "hamburger" icon. But I want that this icon is only visible on the "main" page, on the "childs" pages, I want to keep the "back arrow" icon.
This is done easily on iOS, but on Android I need to use a custom renderer. 
This custom renderer allow to:
 - display the "custom" icon when the "main" page is displayed
 - display the "arrow back" icon when a "child" page is displayed
This works well, but there is still a problem; a short transition animation during the navigation:
 - that transforms the "hamburger" icon into "arrow back" icon, when navigating from "main" page to a "child" page
 - that transforms the "arrow back" icon into "hamburger" icon, when returning to the "main" page

### Steps to Reproduce

1. Create a project that contains a MasterDetail page as MainPage.
2. Create 3 ContentPage: a menu for the Master, a home page for the Details, and another page as child page
3. Replace the icon of the menu page.
4. Add the following Android renderer to get the expected behavior:

```
[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(CustomIconRenderer))]
namespace MyProject.Droid.Renderers
{
    public class CustomIconRenderer : MasterDetailPageRenderer
    {
        protected override void OnLayout(bool changed, int l, int t, int r, int b)
        {
            base.OnLayout(changed, l, t, r, b);
            var toolbar = FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);
            if (toolbar != null)
            {

                for (var i = 0; i < toolbar.ChildCount; i++)
                {
                    var imageButton = toolbar.GetChildAt(i) as ImageButton;
                    var drawerArrow = imageButton?.Drawable as DrawerArrowDrawable;
                    if (drawerArrow == null)
                        continue;

                    bool displayBack = false;
                    var app = Xamarin.Forms.Application.Current;

                    var detailPage = (app.MainPage as MasterDetailPage).Detail;
                    var navPageLevel = detailPage.Navigation.NavigationStack.Count;
                    if (navPageLevel > 1)
                        displayBack = true;

                    if (!displayBack)
                        ChangeIcon(imageButton, Resource.Drawable.icon);
                }
            }
        }

        private void ChangeIcon(ImageButton imageButton, int id)
        {
            if (Android.OS.Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.Lollipop)
                imageButton.SetImageDrawable(Context.GetDrawable(id));
            imageButton.SetImageResource(id);
        }
    }
}
```

### Expected Behavior
As the "hamburger" icon is no longer used, the related transition animations shouldn't  be displayed.

### Actual Behavior
The related transition animations are still displayed.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version: ??
- IDE: VIsual Studio 2017 (15.6.4)
- Platform Target Frameworks: 
  - Android: 5.1

### Screenshots
[screenshot](https://media.giphy.com/media/g4IyAyuwhhayhjySpJ/giphy.gif)

### Reproduction Link
[sample](https://github.com/Goldstrike/HamburgerIcon)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
