### ISSUE TITLE
[UWP] RotationX and RotationY don't work 

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#2514]
### Description

Using RotationX or Ratation doesn't do the expected on UWP

### Steps to Reproduce

1. run sample https://github.com/xamarin/xamarin-forms-samples/tree/master/ScaleAndRotate
2. navigate to RoationX or RationY
3. Change the slider value

### Expected Behavior

Should rotate the label

### Actual Behavior

Nothing happens

### Basic Information

- Version with issue: 3.0.0
- Last known good version: 2.5.1
- IDE:
- Platform Target Frameworks: 
    - UWP:   16299 

- Nuget Packages:  3.0.0-pre4

### Reproduction Link

 https://github.com/xamarin/xamarin-forms-samples/tree/master/ScaleAndRotate

**Comment by MarcusSpecht** [comment]
Good to know it is already worked on. Just ran into Xamarin.Forms.Animation with RotationY not working with Xamarin.Forms 3.0.0.446417 on UWP.
