### ISSUE TITLE
When using XAML compilation, binding to command whose class definition is in external project generates an error

### ISSUE THREAD

**Issue by ptsoccer** [xamarin/Xamarin.Forms#2518]
### Description
When using compile time data bindings, binding a button's command to a command whose class definition is in another project generates:

Member '\<class name>' is declared in another module and needs to be imported

### Steps to Reproduce

1. Create two projects, one being a xamarin forms project and one being a .NET standard 2 project and have the xamarin forms project reference the .NET standard 2 project
2. In the .NET standard project, create a view model class and implementation of ICommand. Have the view model have an instance of the ICommand implementation.
3. Turn on XAML compilation in the xamarin forms project
4. Create a button in the xamarin forms project and bind its command to the command property on the view model
5. Compile the xamarin forms project

### Expected Behavior
The project should compile successfully

### Actual Behavior
An error is returned:
Member 'ViewModel.DelegateCommand' is declared in another module and needs to be imported

### Basic Information
- Version with issue: 2.5.1 and 3.0-pre3

### Reproduction Link
[XamarinStaticBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/1933455/XamarinStaticBinding.zip)

**Comment by StephaneDelcroix** [comment]
that's an issue in the BindingsCompiler
