### ISSUE TITLE
When using XAML compilation, it would be nice to know at compile time that a binding conversion can't be done

### ISSUE THREAD

**Issue by ptsoccer** [xamarin/Xamarin.Forms#2532]
### Description
Xamarin Forms does not automatically do certain implicit type conversions in the bindings, instead the binding must have a converter, there must be a StringFormat in the binding (if the target property is a string) the type must be IConvertible, or one of the hardcoded types. If you bind to a property where this is not the case, an InvalidCastException is thrown and then swallowed, and the binding doesn't work. It would be nice if, when XAML compilation is turned on, this condition was detected and shown at compile time rather than bindings silently not working during runtime.

### Steps to Reproduce

1. Create a xamarin forms project
2. Create a custom class (doesn't have to do anything).
3. Create a view model class that exposes a property for the custom class
4. Create a view that binds to that view model, and bind the custom class property in the view model to a label's text
5. Turn on XAML compilation for that view
6. Compile and run the program

### Expected Behavior
A compile error is generated

### Actual Behavior
An InvalidCastException is thrown when the program is run (must have break on throw turned on in exception dialog and Just My Code disabled to see the exception).

### Basic Information

Version with issue: 3.0-pre3

### Reproduction Link
This is a UWP project

[XamarinStaticBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/1939532/XamarinStaticBinding.zip)

**Comment by StephaneDelcroix** [comment]
@ptsoccer 
> does not automatically do certain implicit type conversions in the bindings

can you develop this a bit ? looks like room for enhancement...

**Comment by ptsoccer** [comment]
Are you asking me to elaborate on that? If so, I'm not sure that's the best way to go, considering that would require evaluating conversion operators that are implemented and possibly doing some kind of best match in case none of the operators create the exact type needed. I feel like this would create too much complexity and confusion. Probably the most I would do is call ToString if the target binding is of type string (WPF already does this which is why I ran into this issue, I am sharing the viewmodels between my WPF views and Xamarin Forms views).

**Comment by StephaneDelcroix** [comment]
@ptsoccer We already, at multiple places, execute implicit cast operators where it makes sense. So yes, I'd be nice if you could provide an example of what's not working and what you expect so we can figure out if it makes sense to support it or not

**Comment by ptsoccer** [comment]
ToString is not called on a custom class when the target property is a string, so the binding ends up not working, but that wasn't my original issue since the fix is easy, adding StringFormat='{0}' to the binding. My issue is I don't know about this until runtime, and even at runtime it isn't obvious there is an issue since the InvalidCastException is swallowed. The solution file I uploaded should show that assuming you have just my code disabled and break on throw turned on.

**Comment by jfversluis** [comment]
I think many improvements have been made in this area. If there is still something you're missing that you're interested in, please make sure to open a suggestion on the .NET MAUI repository. Thanks!
