### ISSUE TITLE
Picker FontFamily, FontAttributes, FontSize Properties

### ISSUE THREAD

**Issue by tlpearson** [xamarin/Xamarin.Forms#2533]
### Description
Setting the Forms Picker FontFamily, FontAttributes, FontSize properties should change the list elements as well as the selected item.

### Steps to Reproduce
Set any of the Picker's FontFamily, FontAttributes, FontSize properties to a value in XAML or in code.

### Expected Behavior
Setting the Picker FontFamily, FontAttributes, FontSize properties should change the list elements as well as the selected item.

### Actual Behavior
Only the selected item is changed in iOS and Android;  the list items are displayed in the default font. UWP FontFamily, FontAttributes, FontSize properties are set correctly.

### Basic Information

- Version with issue: 3.0.0.354232-pre3
- Last known good version: none
- IDE:  Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 7.1 
  - UWP:  16299

**Comment by SagarPanwala** [comment]
Can we different font size for Title, SelectItem and items in picker list ?

**Comment by charlesroddie** [comment]
FontFamily works on UWP but not iOS (where it affects the selected display but not the menu).

**Comment by nonubitta** [comment]
Is there any progress on this one?
Not working on ios and android. :(

**Comment by kevcrooks** [comment]
Is there a planned fix for this, or a workaround that will enable us to get a custom font in the rendered picker on Android?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
