### ISSUE TITLE
Leak?

### ISSUE THREAD

**Issue by amccorma** [xamarin/Xamarin.Forms#2534]
Is this leak coming from the Xamarin framework or my code?

[WindowManager] 
[WindowManager] android.view.WindowLeaked: Activity md52f806127ecc1a696113c916d4a12cae6.MainActivity has leaked window DecorView@4e70f66[MainActivity] that was originally added here
[WindowManager] 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:572)
[WindowManager] 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
[WindowManager] 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:97)
[WindowManager] 	at android.app.Dialog.show(Dialog.java:419)
[WindowManager] 	at md52f806127ecc1a696113c916d4a12cae6.MainActivity.n_onBackPressed(Native Method)
[WindowManager] 	at md52f806127ecc1a696113c916d4a12cae6.MainActivity.onBackPressed(MainActivity.java:92)
[WindowManager] 	at android.app.Activity.onKeyUp(Activity.java:2864)
[WindowManager] 	at android.view.KeyEvent.dispatch(KeyEvent.java:3358)
[WindowManager] 	at android.app.Activity.dispatchKeyEvent(Activity.java:3165)
[WindowManager] 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
[WindowManager] 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
[WindowManager] 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
[WindowManager] 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
[WindowManager] 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:428)
[WindowManager] 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5003)
[WindowManager] 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4965)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4500)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4553)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4519)
[WindowManager] 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4652)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4527)
[WindowManager] 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4709)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4500)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4553)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4519)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4527)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4500)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4553)
[WindowManager] 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4519)
[WindowManager] 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4685)
[WindowManager] 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4854)
[WindowManager] 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3038)
[WindowManager] 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2574)
[WindowManager] 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2565)
[WindowManager] 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3015)
[WindowManager] 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
[WindowManager] 	at android.os.MessageQueue.nativePollOnce(Native Method)
[WindowManager] 	at android.os.MessageQueue.next(MessageQueue.java:323)
[WindowManager] 	at android.os.Looper.loop(Looper.java:136)
[WindowManager] 	at android.app.ActivityThread.main(ActivityThread.java:6682)
[WindowManager] 	at java.lang.reflect.Method.invoke(Native Method)
[WindowManager] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
[WindowManager] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
[ViewRootImpl@b795bc1[MainActivity]] mHardwareRenderer.destroy()#4
[ViewRootImpl@b795bc1[MainActivity]] dispatchDetachedFromWindow
[InputTransport] Input channel destroyed: fd=152

**Comment by StephaneDelcroix** [comment]
Thanks for reporting this issue.

Unfortunately, we can't answer that.

Please provide a really simple project reproducing the issue, do everything you can to make sure the issue is not in your code, and then report again, and we will look at it
