### ISSUE TITLE
[Enhancement] Deprecate minimum(Width/Height)Request and add new alternatives

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#2536]
# Description
This enhancement is based on a comment I made on #2000. This enhancement proposal suggests adding MaximumHeightRequest and MaximumWidthRequest properties to VisualElement. I completely agree it would be a welcome addition to have these properties as counterparts of MinimumHeightRequest and MinimumWidthRequest.

However, as lots of discussion about the existing properties exist, and the general agreement is that the properties don't do what you would expect them to do, we should fix it once and for all. So my proposal:

- Deprecate MinimumHeightRequest and MinimumWidthRequest properties from VisualElement
- Add new properties MinHeightRequest, MinWidthRequest, MaxHeightRequest, MaxWidthRequest. NOTE THE DIFFERENT NAMES
- The new properties should do what users expect them to do, being:
    - The min properties should make sure an element gets at least the value set in the property value
    - The max properties should make sure an element never grows larger than the value set in the property

This way, we can deprecate the old properties (leaving exising implementations intact) and introduce new properties (that actually do what people expect) in the same release.

**Comment by PaulVrugt** [comment]
I don't see the problem. We can depreciate them and leave the current functionality as it is, and add the new properies with the new names (max and min instead of maximum and minimum) in the same release. In a later release we can remove the old properties

**Comment by ChaseFlorell** [comment]
This is one API i'd love to see _broken_ and rebuilt. With the current state of MinimumHeightRequest and MinimumWidthRequest, I'd venture a guess that < 5% of users actually use it.

Example
```xml
<ContentView BackgroundColor="White" > 
  <Label HorizontalOptions="Fill" 
         MinimumHeightRequest="30"
         Margin="6"
         Text="{Binding Notes}" />
</ContentView>
```

I would expect this to make the Label a minimum of 30d tall even if there is no text within. What it actually does... Nothing.

**Comment by dunlavy** [comment]
Also include an internal discussion why the terrible names were part of the API in the very first place.

Sorry if that sounded snark.  But I hate these properties.

**Comment by profexorgeek** [comment]
After researching and testing, I believe these properties actually do work as intended with some conditions. In this specific example the `MinimumHeightRequest` may not be working correctly because `HeightRequest` is not specified. If the actual height is smaller than the minimum height, behavior is undefined. Additionally if `MinimumHeightRequest` is not specified, the default behavior is that the element **cannot** be shrunk! Please see these docs for updated details on minimum property behavior:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/common-properties#minimum-request-properties

**Comment by jfversluis** [comment]
I think everyone will be happy about this behavior changing with .NET MAUI! Please go check out the changes of there, we won't be making any more changing on how it works on Xamarin.Forms. If you have any ideas on this and you're still interested, please open something on the .NET MAUI repo, thanks!
