### ISSUE TITLE
Bug in XmlSerializer on Deserialization

### ISSUE THREAD

**Issue by Hunv** [xamarin/Xamarin.Forms#2542]
### Description
XmlSerializer is not working properly when deserializing a given XML string to object.

### Steps to Reproduce

1. Create a new Solution with a .Net or .Net Core Project and a Xamarin Forms project (Android)
2. Download XSD File from https://www.vdv.de/trias-xsd-v1.2.zipx?forced=true and convert it to classes (i.e. using Xsd2Code+ Extension for Visual Studio with default settings but GenerateOrderXmlAttributes = True, GenerateXmlAttributes = True and CollectionObjectType = Array)
3. Execute this code in .Net (Core) and Xamarin Forms project:
```
var xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?> <Trias xmlns=\"http://www.vdv.de/trias\" version=\"1.2\"> <ServiceDelivery> <ResponseTimestamp xmlns=\"http://www.siri.org.uk/siri\">2018-04-22T15:40:20Z</ResponseTimestamp> <ProducerRef xmlns=\"http://www.siri.org.uk/siri\">EFAController10.2.10.2-EFA-STATIC02</ProducerRef> <Status xmlns=\"http://www.siri.org.uk/siri\">true</Status> <MoreData>false</MoreData> <Language>de</Language> <DeliveryPayload> <LocationInformationResponse> <LocationResult> <Location> <StopPoint> <StopPointRef>de:08115:5947</StopPointRef> <StopPointName> <Text>Hauptstraße</Text> <Language>de</Language> </StopPointName> <LocalityRef>8115051:6</LocalityRef> <WheelchairAccessible>false</WheelchairAccessible> <Lighting>false</Lighting> <Covered>false</Covered> </StopPoint> <LocationName> <Text>Weil im Schönbuch</Text> <Language>de</Language> </LocationName> <GeoPosition> <Longitude>9.05147</Longitude> <Latitude>48.62194</Latitude> </GeoPosition> </Location> <Complete>true</Complete> <Probability>0.958000004</Probability> <Mode> <PtMode>bus</PtMode> <BusSubmode>localBus</BusSubmode> </Mode> <Mode> <PtMode>bus</PtMode> <BusSubmode>expressBus</BusSubmode> </Mode> <Mode> <PtMode>bus</PtMode> <BusSubmode>demandAndResponseBus</BusSubmode> </Mode> </LocationResult> </LocationInformationResponse> </DeliveryPayload> </ServiceDelivery> </Trias>";

await streamWriter.WriteAsync(xml);
streamWriter.Flush();
responseStream.Position = 0;

XmlSerializer x = new XmlSerializer(typeof(Trias));    
object res = x.Deserialize(responseStream);

if (((ServiceDeliveryStructure)((Trias)res).Item).DeliveryPayload != null)
    Debug.WriteLine("Deserialization successful");
else
    Debug.WriteLine("Deserialization failed");
```

### Expected Behavior
The result should be the same, i.e. the value at res.Item.DeliveryPayload

### Actual Behavior
.Net (Core) deserializes the xml as expected and contains a value for DeliveryPayload but Xamarin Forms project didn't deserialized this property (and also some others)

### Basic Information

- Version with issue: 2.5.1.444934
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks: 
  - Android: 8.1 (Oreo)
- Nuget Packages: Only default ones
- Affected Devices: i.e. emulator (VS Emulator for Android)

### Reproduction Link
[XmlProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/1948110/XmlProblem.zip)

**Comment by StephaneDelcroix** [comment]
Thanks for reporting this issue. Unfortunately it is out of the scope of the Xamarin.Forms project, and there is nothing at all we can do here.

Please note that .netCore and your android app runs on different runtimes, and on different profiles. That looks a good place to start looking.
