### ISSUE TITLE
Xamarin Forms UWP Label is blurry when using TranslationX or TranslationY

### ISSUE THREAD

**Issue by Russc0** [xamarin/Xamarin.Forms#2554]
### Description
Label text becomes blurry after adding TranslationX or TranslationY. Any value except 0 causes the blur.

### Steps to Reproduce

1.  Create label and add TranslationX=25
2. 
3. 

### Expected Behavior
Sharp Text

### Actual Behavior
Blurry Text

### Basic Information

- Version with issue: All versions of Xamarin Forms up to the latest v3.0 Preview
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - UWP:  10.0 Build 16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![without any translation](https://user-images.githubusercontent.com/6091094/39347698-a722a3ec-4a26-11e8-8a47-e4e37afaf996.png)
![after translation](https://user-images.githubusercontent.com/6091094/39347697-a6e64a6e-4a26-11e8-816c-a2eaf06b7fbf.png)

**Comment by Russc0** [comment]
bump

**Comment by hartez** [comment]
I can no longer reproduce this in 4.5, so I'm closing this issue. If you are still affected by it, reply here and we'll reopen it.

![Annotation 2020-02-05 164759](https://user-images.githubusercontent.com/538025/73893614-639f3200-4837-11ea-99eb-2dadee72b6ae.png)
