### ISSUE TITLE
[iOS] Xamarin.Forms Listview Row Height Does Not Update When Hidden Controls

### ISSUE THREAD

**Issue by LeeCenY** [xamarin/Xamarin.Forms#2555]
### Description
https://github.com/xamarin/Xamarin.Forms/issues/2383

Hidden controls also do not update height！
If a control of the Item inside the ListView is hidden, Android will automatically adjust the height of the UI Item, but iOS will not automatically adjust the height

**Comment by XXISerenaIXX** [comment]
Probably a duplicate of #2383 .

**Comment by jasoncouture** [comment]
I am also affected by this issue, any status updates?

**Comment by aabc123** [comment]
I've worked around this with a custom renderer that allows me to call BeginUpdate/EndUpdate on the underlying UITableView which refreshes the heights of the custom view cells.

**Comment by vecalion** [comment]
@aabc123 I wonder if you can share your workaround?

**Comment by aabc123** [comment]
You need to create an instance of the custom ListView below instead of the one in Xamarin.Forms.  When you change your ViewCell height, you need to call refresh() on this list view.

You'll probably need to delay the call one tick e.g.

`
Device.BeginInvokeOnMainThread(() => _listView.refrehs());
`

Here's the custom control.  It also sets the caching strategy so you may want to change that.

`
using System;
using Foundation;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(Controls.ListView), typeof(Controls.ListViewRenderer))]
namespace Controls
{
    public class ListView : Xamarin.Forms.ListView
    {
        public ListView() : base(ListViewCachingStrategy.RecycleElement)
        {
        }

        /// <summary>
        /// Refresh the visible rows
        /// </summary>
        /// <remarks>Will re-load the visible rows, taking in to account any height changes in the view cells
        /// which will animate to their new height
        /// 
        /// If the layout has just changed, you may want to delay this with an await Task.Delay or Device.BeginInvoke
        /// before calling
        /// </remarks>
        public void refresh()
        {
            tableView.BeginUpdates();
            tableView.EndUpdates();
        }

        /// <summary>
        /// The current tableview
        /// </summary>
        public UITableView tableView;
    }

    public class ListViewRenderer : Xamarin.Forms.Platform.iOS.ListViewRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
        {
            // Invoke base
            base.OnElementChanged(e);

            if (e.OldElement is ListView oldLv)
            {
                oldLv.tableView = null;
            }
            if (e.NewElement is ListView lv)
            {
                lv.tableView = Control;
            }
        }
    }
}
`

**Comment by IsmaelMendonca** [comment]
Hello guys, 

Do you have any updates on it?

I am also facing this annoying issue. I am trying a lot of workarounds but I think this is a serious problem in the iOS ListView component.

regards.

**Comment by wadebaird** [comment]
I am encountering this issue as well.  Here is my simple repro:

1. Create a new Xamarin.Forms Master / Detail project
2. Replace the Content in the ItemsPage with this code:
` <StackLayout>
        <ListView x:Name="ItemsListView"
                ItemsSource="{Binding Items}"
                VerticalOptions="FillAndExpand"
                HasUnevenRows="true"
                RefreshCommand="{Binding LoadItemsCommand}"
                IsPullToRefreshEnabled="true"
                IsRefreshing="{Binding IsBusy, Mode=OneWay}"
                CachingStrategy="RecycleElement"
                SelectionMode="None">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Padding="10">
                            <StackLayout>
                                <StackLayout.GestureRecognizers>
                                    <TapGestureRecognizer Tapped="SocketDetailsSummary_Tapped"/>
                                </StackLayout.GestureRecognizers>
                                <Label Text="{Binding Text}" 
                                        LineBreakMode="NoWrap" 
                                        Style="{DynamicResource ListItemTextStyle}" 
                                        FontSize="16" />
                            </StackLayout>
                            <StackLayout x:Name="ItemDetail" IsVisible="False">
                                <Label Text="{Binding Description}" 
                                        LineBreakMode="NoWrap"
                                        Style="{DynamicResource ListItemDetailTextStyle}"
                                        FontSize="13" />
                            </StackLayout>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
        <StackLayout x:Name="ItemsStackView"
                BindableLayout.ItemsSource="{Binding Items}"
                VerticalOptions="FillAndExpand">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <StackLayout Padding="10">
                        <StackLayout>
                            <StackLayout.GestureRecognizers>
                                <TapGestureRecognizer Tapped="SocketDetailsSummary_Tapped"/>
                            </StackLayout.GestureRecognizers>
                            <Label Text="{Binding Text}" 
                                        LineBreakMode="NoWrap" 
                                        Style="{DynamicResource ListItemTextStyle}" 
                                        FontSize="16" />
                        </StackLayout>
                        <StackLayout x:Name="ItemDetail" IsVisible="False">
                            <Label Text="{Binding Description}" 
                                        LineBreakMode="NoWrap"
                                        Style="{DynamicResource ListItemDetailTextStyle}"
                                        FontSize="13" />
                        </StackLayout>
                    </StackLayout>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>
    </StackLayout>`
3. Add this method to the class:
`private void SocketDetailsSummary_Tapped(object sender, EventArgs e)
        {
            var parent = ((Layout)sender).Parent as Layout;
            var detailsStack = parent.FindByName("ItemDetail") as Layout;
            detailsStack.IsVisible = !detailsStack.IsVisible;
        }`
4. Load the form in iOS (This works in Android for me!!!!) and try to expand the items in the list view. The StackLayout works, but you can see the list view items expanding behind the next row (in the red box in the image below):

![image](https://user-images.githubusercontent.com/35878500/58137558-888b4080-7be7-11e9-8750-04871999251c.png)

Xamarin Forms 3.6.0.264807 and 4.0.0.425677
iOS 12.2
Android 8.1

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
