### ISSUE TITLE
[Android] Button's shadow being clipped when inside layout

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/Xamarin.Forms#2558]
### Description

I'm opening this issue as instructed here: https://bugzilla.xamarin.com/show_bug.cgi?id=58277

I'm still experiencing the bug described in the related bugzilla thread.

### Steps to Reproduce

As said in the thread, just create a page with this UI:

    var buttonLayout = new Grid
    {
        RowDefinitions =
        {
            new RowDefinition { Height = new GridLength(1, GridUnitType.Auto) }
        },
        RowSpacing = 12,
        Padding = new Thickness(16)
    };

    buttonLayout.AddChild(new Button { BackgroundColor = Color.FromHex("#ffffff"), Text = "Button1" }, 0, 0);
    Content = buttonLayout;

Obs. As the default button has some padding, the clipping is only noticeable when raised (clicked).

### Expected Behavior

The shadow is not clipped.

### Actual Behavior

The shadow is clipped.

### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version: none
- Platform Target Frameworks:
  - Android: 8.1, 8.0, 7.1

### Screenshots

![screenshot](https://user-images.githubusercontent.com/12024080/39373698-c9408a78-4a1e-11e8-89d3-247ed16e1cca.png)

Left: The clipped shadow
Right: The same button with a workaround (hidden ContentView added to the same layout the button is, better described in the bugzilla thread and in the repro project)

### Reproduction Link

[ShadowTest.zip](https://github.com/xamarin/Xamarin.Forms/files/1955927/ShadowTest.zip)

**Comment by hartez** [comment]
Adding a repro with the buttons side-by-side, because the problem is hard to see at first. Push both buttons at once when they're next to each other and it becomes obvious.

[shadowtest (side-by-side).zip](https://github.com/xamarin/Xamarin.Forms/files/1968087/shadowtest.side-by-side.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
