### ISSUE TITLE
Xamarin custom renderer for UWP not working

### ISSUE THREAD

**Issue by hauteur** [xamarin/Xamarin.Forms#2559]
### Description
Changes to the Control property in a custom renderer for UWP/Xamarin DatePicker and TimePicker have no effect.  There are no errors, it just doesn't display - for example, setting Color.BorderBrush does nothing.  The exact same code applied to a regular picker work just fine.

### Steps to Reproduce

1.  Create a Xamarin Forms project and a UWP project
2.  Create a custom renderer for a DatePicker control
3. Add code to change the border (BorderBrush, BorderThickness)
4. Run the code

### Expected Behavior
The border should be set

### Actual Behavior
There is no effect

### Basic Information

- Version with issue:  Xamarin Forms 1.x through 2.5.1
- Last known good version:  None
- IDE:  Visual Studio 2017 and Visual Studio for Mac
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages:  Xamarin.Forms
- Affected Devices:  UWP

### Reproduction Link

https://www.dropbox.com/s/nuhm596kkewkph3/UwpRenderer.zip?dl=0

**Comment by hartez** [comment]
Your custom renderer is actually working just fine; you're running into a UWP issue with the DatePicker and TimePicker templates. Setting BorderBrush on those controls doesn't have any effect at all with the default UWP control templates. Try creating a plain old UWP project with just a DatePicker and setting BorderBrush; you'll see what I mean.

To make this work, you will need to take the default templates for the DatePicker and TimePicker controls and modify them in your UWP project. Your custom templates need to bind the flyout button style properties for BorderBrush to the template's BorderBrush property. I'm attaching an updated version of your project with the changes to make DatePicker work so you can see an example (the relevant changes are in the Resources.xaml file and in App.xaml). 

[DatePickerBorder.zip](https://github.com/xamarin/Xamarin.Forms/files/1971665/DatePickerBorder.zip)
