### ISSUE TITLE
FlexLayout has trouble when rendering in a ContentView on Android

### ISSUE THREAD

**Issue by markjulmar** [xamarin/Xamarin.Forms#2563]
### Description
`FlexLayout` doesn't layout elements the same when placed into a `ContentView` that is added to a `ContentPage` on Android. It works properly on iOS and UWP.

### Steps to Reproduce

1. Download [sample project](https://github.com/XamarinUniversity/build2018-labs/tree/master/lab2/start)
2. Run the app in Android, provide a name, color and click "Enter Circle".
3. Notice that the entry field is about 200px _above_ the bottom of the screen - it should be at the bottom.
4. Select a message, this navigates to a new screen that hosts the _same_ `ContentView` but in a `Grid` host with other content above it - notice that now the entry is at the bottom.

### Basic Information

- Xamarin.Forms 3.0.0.427558-pre4
- IDE: VS2017 15.6 and 15.7

### Screenshots
**Android (bad)**
![Android (bad)](https://user-images.githubusercontent.com/5099741/39389207-df255e4a-4a4b-11e8-973d-9facfd0cbdbb.png)

**UWP (good)**
![uwp](https://user-images.githubusercontent.com/5099741/39389195-cf68a0ca-4a4b-11e8-94ba-0f1a5d2ac4c5.png)

**iOS (good)**
![iOS](https://user-images.githubusercontent.com/5099741/39389198-d2d34dc8-4a4b-11e8-9e65-331b500f2e52.jpg)

### Reproduction Link
Here's a sample project: https://github.com/XamarinUniversity/build2018-labs/tree/master/lab2/start

**Comment by StephaneDelcroix** [comment]
I no longer can reproduce this. I guess we fixed the layout issue in Android at some point
