### ISSUE TITLE
Xamarin.Forms Previewer fails if you don't have either an Android or iOS project

### ISSUE THREAD

**Issue by MarkStega** [xamarin/Xamarin.Forms#2565]
### Description
Xamarin.Forms Previewer fails if you don't have either an Android or iOS project

### Steps to Reproduce

1. Create a new cross platform app and pick only the UWP target
2. Attempt to view the MainPage.xaml of the cross platform project in the previewer
3. Selecting either Android or iOS as the platform displays an error message
4. Need a platform choice of 'UWP'

### Expected Behavior
Should be able to preview without having an Android or iOS project
### Actual Behavior
No preview available
### Basic Information

- Version with issue: 3.0.0.427558-pre4
- Last known good version:
- IDE: VS 2017 15.7.0 Preview 5
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android:  n/a
  - UWP:   16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
The Xamarin.Forms Previewer does not currently support UWP; that's why you're not seeing an option for it.

**Comment by MarkStega** [comment]
Since UWP is a supported target in XF I believe that the Previewer should be enhance to to support that platform..
