### ISSUE TITLE
Xamarin forms Android Release build with ProGuard giving Warning couldn't able to make build

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#2566]
### Description
Xamarin forms Android build in release mode enabling ProGuard giving 6K warning couldn't able to make build.
### Steps to Reproduce

1. Enable proGuard 
2. Enable Multi-Dex
3. Try to build on release mode it will give you 6K Warring

### Expected Behavior
Warning needs to resolved 
### Actual Behavior
6K warning is there
Please check attach file for warning logs

Severity	Code	Description	Project	File	Line	Suppression State
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.NonNull	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.NonNull	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.NonNull	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.RestrictTo	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.RestrictTo	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		
Warning		android.arch.core.internal.FastSafeIterableMap: can't find referenced class android.support.annotation.RestrictTo$Scope	KegID.Android	C:\Project\KegID\KegID\KegID.Android\PROGUARD		

[WarningList.txt](https://github.com/xamarin/Xamarin.Forms/files/1959707/WarningList.txt)
### Basic Information

Microsoft Visual Studio Professional 2017 
Version 15.6.7
VisualStudio.15.Release/15.6.7+27428.2043
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual F# Tools 10.1 for F# 4.1   00369-60000-00001-AA420
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40405.0
Azure Functions and Web Jobs Tools

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.9.11-pre (71eb098)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.27428.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.9.0.753 (f0f46392f)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.10.96 (a702a9ceb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.2.0.16 (HEAD/a78295902)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.9.1.24 (f62de47)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Version with issue:
XAMARING FORMS : 2.5.1.444934

- Last known good version:
- IDE: VS 2017 (Version 15.6.7)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 

Mono.Android v4.0.30319
proguard6.0.2 (Updated)
- Nuget Packages:

![image](https://user-images.githubusercontent.com/1029026/39416850-cdee84e8-4c6d-11e8-8b3a-49c704a8bc8c.png)
![image](https://user-images.githubusercontent.com/1029026/39416876-eaea3a92-4c6d-11e8-954b-06b115270d8f.png)
- Affected Devices:

**Comment by jitendrajadav** [comment]
Any update??

**Comment by hartez** [comment]
@jitendrajadav Can you post your Proguard configuration file?

**Comment by PureWeen** [comment]
@jitendrajadav 

You'll need to add a local proguard.cfg file for the classes that are referenced in your warning

https://github.com/xamarin/Xamarin.Forms/issues/2491
https://github.com/xamarin/Xamarin.Forms/issues/2457

For example in your file I see a lot about android.support.annotation so you can try adding in
```
-keep class android.support.annotation.** { *; }
-dontwarn android.support.annotation.*
```

To see if that reduces your warnings

Also I wouldn't enable both multidex and ProGuard
Just enabling ProGuard should be enough to achieve whatever it is you want to achieve.  Multidex can cause weird issues on pre Lollipop Android devices

**Comment by hartez** [comment]
@jitendrajadav If you add @PureWeen's suggestions to your configuration, does it reduce the number of errors?

**Comment by jitendrajadav** [comment]
@hartez still same error nothing is happened

**Comment by jitendrajadav** [comment]
Thank you @hartez  and @PureWeen for suggestion finally I have solved my problem like adding and removing some of configuration..

I am just adding my full configuration file please have a look 👍 

`


-dontpreverify
-repackageclasses ''
-allowaccessmodification
-optimizations !code/simplification/arithmetic
-keepattributes *Annotation*

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep class android.support.annotation.** { *; }
-dontwarn android.support.annotation.*
-keep class android.support.v7.widget.FitWindowsFrameLayout { *; }
-dontwarn android.support.v7.widget.FitWindowsFrameLayout
-dontwarn com.google.android.gms.**
-keep class com.google.android.gms.**
-dontwarn com.microsoft.appcenter.utils.**
-dontwarn com.microsoft.appcenter.push.**
-keepattributes Signature
-keepattributes InnerClasses
-dontoptimize
-keep class org.apache.** { *; }
-keepnames class com.fasterxml.jackson.** { *; }
-keepnames class javax.servlet.** { *; }
-keepnames class org.ietf.jgss.** { *; }
-dontwarn org.apache.**
-dontwarn org.w3c.dom.**

-dontwarn android.support.v4.**

-keep class * extends com.myCompany.package.flavor.Flavor { *; }
-keep class com.myCompany.** { *; }

-keep public class * extends android.view.View {
public <init>(android.content.Context);
public <init>(android.content.Context, android.util.AttributeSet);
public <init>(android.content.Context, android.util.AttributeSet, int);
public void set*(...);
}

-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class * {
public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class * implements android.os.Parcelable {
static android.os.Parcelable$Creator CREATOR;
}

-keepclassmembers class **.R$* {
public static <fields>;
}`
