### ISSUE TITLE
Code-behind x:Name not linking properly

### ISSUE THREAD

**Issue by jhumphrey1** [xamarin/Xamarin.Forms#2574]
### Description
Cannot access named components from code-behind

### Steps to Reproduce

1. Create a new blank Xamarin Forms project
2. Add 'x:Name="myTextLabel" ' to the default "Welcome to Xamarin.Forms" label, and 'x:Name="myContentPage" ' to the default ContentPage
3. Try and reference them in the code-behind

### Expected Behavior
Should run as expected
### Actual Behavior
myTextLabel gives 'Not Available' error (shown in image)
myContentPage gives standard "myContentPage does not exist in current context"
![xamarin-error](https://user-images.githubusercontent.com/19778665/39483407-4938c3b6-4d40-11e8-8662-50961d28bf2b.png)

Trying to run the code with just the myTextLabel referenced works as expected. Trying to run it with myContentPage referenced does not.

### Basic Information

- Version with issue:
- Last known good version: N/A
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 8.1
- Android Support Library Version: v27.0.2
- Nuget Packages: Xamarin.Forms v2.5.1.444934
- Affected Devices: Note 8, iPhone X

### Screenshots
Here is the xaml, all blocked text is the same (Namespace name)
![xamarin-error-2](https://user-images.githubusercontent.com/19778665/39483606-f329aa20-4d40-11e8-8330-b5024a6bc9c6.png)

**Comment by StephaneDelcroix** [comment]
1. `textLabel` getting underlined is an intelissense issue. A lot of improvement on this side are coming very soon...
2. we indeed do not generate fields for `x:Name`s declared on the root XAML element. But we properly register them to the namescopes, so they can be used in `{x:Reference}` markups.

**Comment by StephaneDelcroix** [comment]
I'm still wondering why one needs a field to be created for a x:Name on the root 🤷‍♂️

**Comment by assanesuzy** [comment]
This is still an issue. This happened to specific file. After updating VS for mac to 8.9.5 (build 4) it started acting up. I can't assign names to any controls other than the ones that already had a name prior to the update. I had to manually add the name in the xaml.g.cs file. after restarting, the file was generated without the name and I was back at square one

<img width="552" alt="Screen Shot 2021-04-13 at 10 59 42 AM" src="https://user-images.githubusercontent.com/78758450/114574768-8604ba80-9c47-11eb-9eb0-b4ccddd5573d.png">

<img width="442" alt="Screen Shot 2021-04-13 at 10 59 52 AM" src="https://user-images.githubusercontent.com/78758450/114574732-7f764300-9c47-11eb-96db-96ea3398eb71.png">

**Comment by restorepro** [comment]
Yes, i am having this issue still while trying to access the mediaElement control by name in the code behind. It happens often for me with various control. I usually delete obj/bin folders and restart and the problem goes away but the mediaElement x:name doesn't want to work...

**Comment by asavalle** [comment]
I am also still having this issue. It seems to come and go. I have several other View's in Xamarin that I am able to properly reference in the code behind. But one class in particular keeps having this issue. I tried to use the name anyway, since it was said to be an Intellisense issue, but it will not let me proceed.
This is very aggravating and seems to not be a priority at all for Microsoft.

**Comment by agostino-pique** [comment]
This is unfortunately still an issue on MAUI too. 
Just like @asavalle some files are properly referenced but in anothers the issue always presents itself.
