### ISSUE TITLE
Relative path resources/styles don't work with Shared Projects and Xamarin.iOS

### ISSUE THREAD

**Issue by kzu** [xamarin/Xamarin.Forms#2583]
### Description

Organizing styles in a separate `Styles` folder is valid and works in NETStandard code sharing strategy. In Shared Projects, the approach works for Xamarin.Android but doesn't for Xamarin.iOS

### Steps to Reproduce

1. Create a Cross-Platform Xamarin.Forms app, using Shared Projects as code sharing strategy
2. Create a resource dictionary XAML under a new `Styles` folder in the shared project
3. Reference it via a `<ResourceDictionary Source="Styles/[FILE].xaml" />` element in a page

### Expected Behavior

The app builds fine for both Android and iOS

### Actual Behavior

Android builds fine. iOS fails with:

```
Views\AboutPage.xaml(11,29): error : Position 11:29. Resource '../Styles/Global.xaml' not found.
```

### Basic Information

- Version with issue: 3.0 pre4
### Reproduction Link

[XamlRelativePath.zip](https://github.com/xamarin/Xamarin.Forms/files/1967691/XamlRelativePath.zip)

**Comment by kzu** [comment]
The issue seems to be related to the missing relative paths to resources when generating `XamlResourceId` attributes on iOS. If you change the `ResourceDictionary` from:

```xml
        <ResourceDictionary Source="../Styles/Global.xaml"/>
```
to
```xml
        <ResourceDictionary Source="Global.xaml"/>
```

Build succeeds for iOS. It's now obviously broken for Android though :(

**Comment by StephaneDelcroix** [comment]
It looks like an iOS issue.

adding 2 embedded resources with the same name in different folders (in a shared project) fails with

> CSC : error CS1508: Resource identifier 'gh2583.iOS.Foo.html' has already been used in this assembly
