### ISSUE TITLE
exception when replace page in CarouselPage [IOS]

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#2585]
if I use such code to replace current page:
`carouselPage.Children[index] = page;`
then it will throw some a exception.

I guess this is because of this line:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Internals/NotifyCollectionChangedEventArgsExtensions.cs#L71
```
removeAt(self.OldItems[i], i + self.OldStartingIndex);
insert(self.OldItems[i], i + self.OldStartingIndex, true);
```

it remove oldItems, and add oldItems AGAIN!!!

**Comment by bill2004158** [comment]
because haven't insert the new page, it cause a exception when PositionChildren() in CarouselPageRenderer

```
			foreach (ContentPage child in ((CarouselPage)Element).Children)
			{
				UIView container = _containerMap[child];
```

the new page is not in _containerMap!!!

**Comment by hartez** [comment]
Reproduction project:

[_2585 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/1971995/_2585.Repro.zip)
