### ISSUE TITLE
Add CSS Validation Task

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#2587]
### Description

CSS Support in Forms needs validation due to differences between what Forms supports vs what is valid CSS. By adding a validation task to the MSBuild pipeline this can greatly reduce developer headaches and help developers fix issues before the app is built and deployed to a device/simulator.

### Common Issues

1. Using unsupported syntax. As @davidortinau pointed out with this sample from #2572

```cs
^ContentPage {
  background-image: none;
}
```

2. Not embedding the CSS file
3. Improperly Referencing the CSS Location

| - Themes
| - - styles.css
| - Views
| - - ViewA.xaml

```xml
<ContentPage x:Class="MyApp.Views.ViewA">
  <ContentPage.Resources>
    <!-- Should be ../Themes/styles.css -->
    <Style Source="Themes/styles.css" />
  </ContentPage.Resources>
</ContentPage>
```

### Proposal

Additional MSBuild Tasks should be added to perform the following validation:

1. Ensure the when a stylesheet is defined in XAML that the resource exists in the specified path
1. Ensure that when a stylesheet is embedded that it is fully parsable for Forms Use
  - There aren't basic syntax errors that make it unreadable
  - There isn't a defined style that includes unsupported syntax. 

### Basic Information

- Version with issue: 3.X
- Last known good version: n/a

**Comment by StephaneDelcroix** [comment]
either this or compile the CSS files into IL...

👍

**Comment by dansiegel** [comment]
I would imagine if the CSS files were compiled to IL it would make #2588 a moot point since there wouldn't be much point trying to optimize the stylesheet. 

The important thing for this though would be to try to identify issues and help developers fix them. There are probably a few ways of doing this from Roslyn Analyzers for in code analysis to help developers catch/correct an issue before build, to Tasks at build time as I mentioned previously. One key requirement in my mind would be that the error messages need to be helpful and instructive for how to correct the issue.

**Comment by jfversluis** [comment]
Hey @dansiegel as always great stuff coming from you! Don't think we'll be adding this to Forms no more and not sure if something like this would make it into .NET MAUI. Seems like the traction on CSS has never been that big, but maybe I'm wrong :)

If it's still important to you, make sure to bring it up on the .NET MAUI repo. Thanks!
