### ISSUE TITLE
FlexLayout provides space for invisible children

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#2593]
### Description
Within a FlexLayout I have children that are `IsVisible="False"` but they still take up space. If I replace FlexLayout with a StackLayout it collapses the space as expected.

### Steps to Reproduce
Do that ^

### Expected Behavior
invisible children should not take up space in the layout.

### Actual Behavior
they are there, in hiding

### Basic Information

- Version with issue: 3.0.0.446417

### Screenshots
https://www.screencast.com/t/lAFePJkJP

### Reproduction Link
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/1970895/Archive.zip)

**Comment by azrinsani** [comment]
Hi, this is still a problem, please re-open

**Comment by IeuanWalker** [comment]
@davidortinau this is an issue in Maui preview

**Comment by NZKobra** [comment]
Almost 4 years later, and this issue still exists in XF 5.0.0.2337...

This issue really needs to be reopened and addressed properly.
