### ISSUE TITLE
ImageSource.FromResource issue

### ISSUE THREAD

**Issue by jhumphrey1** [xamarin/Xamarin.Forms#2604]
### Description
Embedded resource is getting different resource ID based on build system
### Steps to Reproduce

1. Create images folder in xamarin forums project
2. Add any image and mark it as Embedded Resource (Yes this is done for all images)
3. Reference that image in MVVM as seen in screenshots below

### Expected Behavior
Should show image as expected
### Actual Behavior
As shown in screenshot, image is located with Android/iOS specific path, eg. ProjectName.iOS.start.png and ProjectName.Droid.Images.start.png instead of ProjectName.Images.start.png
### Basic Information

- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - iOS: 11.3
  - Android: 8.1

### Screenshots
Code used for debugging, modified from code found here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#debugging-code

![image](https://user-images.githubusercontent.com/19778665/39643353-7e2ece30-4fa2-11e8-893a-dca2002aaf00.png)

Result of debugging iOS, project namespace whited out
![image](https://user-images.githubusercontent.com/19778665/39643516-0332c4b0-4fa3-11e8-8c38-52c8a10ee8b3.png)
Result of debugging Android, project namespace whited out
![image](https://user-images.githubusercontent.com/19778665/39643645-683abb1a-4fa3-11e8-87e8-a9cd0aa0b814.png)

Binding target
![image](https://user-images.githubusercontent.com/19778665/39643835-02898516-4fa4-11e8-87aa-36d2a9eabf6b.png)

Xaml
![image](https://user-images.githubusercontent.com/19778665/39643257-3590974e-4fa2-11e8-811a-7f1298f2a2a2.png)

Project Layout
![image](https://user-images.githubusercontent.com/19778665/39643725-aba814f6-4fa3-11e8-9bbd-350370480f6a.png)

**Comment by hartez** [comment]
The example you are working from (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#embedded-images) is using a PCL project The images in that example are embedded in the PCL assembly (WorkingWithImages.dll). Calling `typeof(EmbeddedImages).GetTypeInfo().Assembly` retrieves the WorkingWithImages assembly. The images are embedded under the assembly name, folder (none, in this case), and image name. So the resources names look like `WorkingWithImages.beach.jpg`. 

You appear to be using a shared project, which means that you don't have a non-native assembly to embed the images in. Instead, you're embedding them in your native assemblies (ProjectName.Droid and ProjectName.iOS). The embedded resource names are built from the name, folder, and image name, so they end up being `ProjectName.Droid.Images.start.png` and `ProjectName.iOS.Images.start.png`. 

If you stick with the shared project, you will need to account for the assembly name when loading your resources. I suggest using a markup extension (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#using-xaml), checking the assembly name (`this.GetType().Assembly.GetName()`), and modifying the source string before passing it to `ImageSource.FromResource`.
