### ISSUE TITLE
[iOS] ListView.Header's Margin is not working

### ISSUE THREAD

**Issue by JaeWLee** [xamarin/Xamarin.Forms#2606]
**Description**

<ListView.Header>'s content has margin. but, that's not work properly

**Expected Behavior**

should work like in android, it's only in iOS

**Basic Information**

    IDE: Visual Studio 2017 for Mac
    Platform Target Frameworks:
        iOS: 11.3
        Android: 8.1

**Screenshots**

<img width="567" alt="screen shot 2018-05-05 at 4 20 06 am" src="https://user-images.githubusercontent.com/35772429/39648179-8deca9ee-501c-11e8-9dc3-cf4b125f6b21.png">
<img width="419" alt="screen shot 2018-05-05 at 4 21 44 am" src="https://user-images.githubusercontent.com/35772429/39648180-8f1380a4-501c-11e8-8789-f915428988e3.png">

**Comment by Paul-Brenner-Tangoe** [comment]
Same as https://github.com/xamarin/Xamarin.Forms/issues/1865

**Comment by samhouts** [comment]
Duplicate of #1865
