### ISSUE TITLE
[UWP] Setting Span BackgroundColor has no effect on UWP

### ISSUE THREAD

**Issue by Koseng** [xamarin/Xamarin.Forms#2611]
### Description
Setting the Span BackgroundColor in a FormattedText of a label has no effect on UWP. iOS and Android do work fine.

### Steps to Reproduce
Create a Label with a FormattedText and use Spans. Set the background color of the span. Reproduction solution attached.

### Expected Behavior
The label formatted text has the given BackgroundColor

### Actual Behavior
On UWP the label formatted text has not the given BackgroundColor

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.427558-pre4
- Last known good version: I think it never worked so far.
- IDE: Visual Studio 2017 15.6.7
- Platform Target Frameworks: 
  - UWP:  UWP SDK 16299,  
- Android Support Library Version: 
- Nuget Packages: UWP v6.0.8

### Reproduction Link
[UwpSpanBackgroundColorIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/1976955/UwpSpanBackgroundColorIssue.zip)

**Comment by pauldipietro** [comment]
The `Windows.UI.XAML.Documents.Run` class which the UWP [LabelRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/LabelRenderer.cs) uses unfortunately does not support background colors, as it has no `Background` property. [(MSDN Docs)](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Documents.Run)

**Comment by Koseng** [comment]
Then please add that remark in your API documentation. [https://developer.xamarin.com/api/property/Xamarin.Forms.Span.BackgroundColor/](url)
