### ISSUE TITLE
[Android] Selecting Entry Controls Within ViewCells Causes FocusChange Cycle

### ISSUE THREAD

**Issue by Koseng** [xamarin/Xamarin.Forms#2613]
### Description
Porting Bug 35058 from Bugzilla. https://bugzilla.xamarin.com/show_bug.cgi?id=35058

When using a ListView that contains ViewCells with an Entry, selecting through the Entry controls will fire off a cycle of several FocusChange events before the destination cell is focused.

Jimmy  was able to reproduce the issue on both Forms 1.5.0 and 1.5.1-pre2.

Application output: https://gist.github.com/jimmgarrido/2d239d227f674c7acc4e

Still occuring on current versions of xamarin forms.

**Ported the reproduction solution to xamarin forms v3.0 pre-4.**
[ListViewFocusCycle.zip](https://github.com/xamarin/Xamarin.Forms/files/1977628/ListViewFocusCycle.zip)

### Steps to Reproduce 
1. Run the attached solution on Android 5.0+
Ported: [ListViewFocusCycle.zip](https://github.com/xamarin/Xamarin.Forms/files/1977628/ListViewFocusCycle.zip)
https://bugzilla.xamarin.com/attachment.cgi?id=13439
2. Select “John”
3. Select “James”
4. Select” Mary”

### Actual Results
In the application output, you will see that the app goest through several Focus changed cycles between the selected and previously selected cell until it stays focused on the  selected one.

### Expected Results
FocusChanged is fired on the selected and previously selected cell just once.

### Basic Information
- Version with issue: All versions since 1.5.0
- Last known good version: unknown

### Remarks
Posted StackOverflow Workaround does not work if there are changes made to the list. Like reordering, removing items, adding items...
http://stackoverflow.com/questions/42018962/entry-control-focus-unfocus-event-triggering-randomly-inside-listview-in-xamarin

### Reproduction Link
[ListViewFocusCycle.zip](https://github.com/xamarin/Xamarin.Forms/files/1977628/ListViewFocusCycle.zip)
https://bugzilla.xamarin.com/attachment.cgi?id=13439

### Other issues related to the topic:
#1600 Entry focus issue inside ListView
#1906 Unfocused issue with Entry in listview

**Comment by samhouts** [comment]
Duplicate of #1600
