### ISSUE TITLE
[Android] Issue with the Entry's PlaceholderColor - API 19 - v4.4.2

### ISSUE THREAD

**Issue by toussam** [xamarin/Xamarin.Forms#2616]
### Description
I am currently testing one of my company's applications with some older devices to checkout if everything is working correctly and I found a small bug with the Entry. If I type some text into the control, tap on the back button to finally come back to the same page and remove the given text (saved through a view model for example), the placeholder's color is not correct.

### Steps to Reproduce

1. Launch the application
2. Click on the button to be redirect to the SecondPage
3. Type some text into the entry
4. Tap on the back button
5. Click back on the button to be redirect to the SecondPage
6. Removed the text from the entry

### Expected Behavior
The PlaceHolder's color should be in Silver as it was defined into the XAML.

### Actual Behavior
The Placeholder's displayed color is actually black.

### Basic Information

- Version with issue: 2.4.0.280
- IDE: Visual Studio 2017
- Android Target Framework: minSdkVersion is the 15th and the used one is the 19th
- Android Support Library Version: v25.4.0.2
- Affected devices: tested with a Samsung Note II GT-N7100

### Screenshots

Expected behavior
![screenshot_2018-05-07-15-24-36](https://user-images.githubusercontent.com/8759012/39704253-016e969e-520b-11e8-8359-64cdae7bb594.png)

Actual behavior
![screenshot_2018-05-07-15-24-46](https://user-images.githubusercontent.com/8759012/39704256-03c4203a-520b-11e8-99d8-171edb3e2bb2.png)

### Reproduction Link

[https://github.com/toussam/PlaceholderColorIssueSample](https://github.com/toussam/PlaceholderColorIssueSample
)

**Comment by toussam** [comment]
Hi @StephaneDelcroix and @samhouts ,

I noticed this issue was not included into the recent sprints. Is it possible to fix it into the next one ?

Thank you in advance for your response and wish you a great week !

**Comment by techduggu** [comment]
@toussam Have you tried this with latest version of Xamarin.Forms? I tried to reproduce but I can see it works as expected now.

**Comment by toussam** [comment]
@techduggu : I didn't. The issue was observed on one project of my previous company. Since I am no longer working for them, I didn't follow up the issue.

If you tried the given sample with the latest version of Xamarin.Forms and it's working as expected then I am guessing that it was fixed.

**Comment by toussam** [comment]
@techduggu : I took the time, this evening, to download the sample and to test with the latest version of Xamarin.Forms, as you recommended. The issue is still present. ;)

**Comment by techduggu** [comment]
Hi @toussam 
I tried to reproduce the exact sample with latest Xamarin.Forms (master branch) and it looks to be working fine. Please correct me if something else is expected here (refer screenshot). 
May I know which latest version of Xamarin.Forms did you try with (stable, pre-release version etc.)?

![Issue2216_working](https://user-images.githubusercontent.com/17450941/67362974-02a26580-f58a-11e9-97bd-23c4a14857b8.gif)

**Comment by toussam** [comment]
Hi @techduggu,

From my point of view, you were not able to reproduce the issue because the emulator that you are using is based on the API 27. The observed behavior was discovered on the API 19 (4.4.2).

About your final question: I updated the Xamarin.Forms nugget package to its latest stable version.

Best regards,

**Comment by techduggu** [comment]
@toussam Good catch and could be the reason. Currently I don't have API 19 SDK installed but I'll try to reproduce it once I have it. Meanwhile I'll let any one from the Xamarin team to look into this as a quick option. Thanks!

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
