### ISSUE TITLE
[Enhancement] Ellipse/Circle Control

### ISSUE THREAD

**Issue by pingzing** [xamarin/Xamarin.Forms#2621]
# Rationale

Currently, there's no way to draw a blob of rounded pixels in Xamarin Forms without either employing a library, doing some brittle hackery with rounded BoxView, or drawing it yourself with Skia. None of these are _great_ options.

- Judging quality and completeness of libraries is often a difficult task.
- Rounded BoxViews don't respond well to resizing, or behave consistently between platforms.
- The Skia solution requires either throwing out XAML entirely and drawing everything yourself, or creating a ContentView that contains a Skia canvas, and a single circle. Furthermore, exposing all the useful properties of that circle via `BindableProperties` would be a fair bit of boilerplate.

# API

I'd expect at least the following properties, shameless stolen from the [UWP Ellipse definition](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.shapes.ellipse#properties-):

- `Stroke : Color`
- `Fill : Color`
- `StrokeThickness : double`
- `HeightRequest  : double`
- `WidthRequest : double`

**Comment by samhouts** [comment]
Duplicate of #2452
