### ISSUE TITLE
[iOS] MasterDetailPage doesn't work as expected with 3.0.0.446417

### ISSUE THREAD

**Issue by Code-DJ** [xamarin/Xamarin.Forms#2630]
### Description
The MasterDetailPage without MasterBehavior was working correctly on 2.5.x - in portrait mode it was a popover and in landscape it was split with the Master taking around 25% of the screen and Detail taking the rest. After upgrade to 3.0.0.446417, no matter what I set the MasterBehavior to, it always works in Split mode with the Master taking slightly more than 50% of the screen. Additionally, in Landscape, each time you select an item in the Master, the Master hides and the Detail takes the entire screen (this may be the default behavior of split mode).

### Steps to Reproduce

1. On VS for Mac, create a new Shared project - it creates 3 projects Shared, iOS, Android.
2. Check and see that the package reference is to Xamarin.Forms 3.0.0.446417 in both the iOS and Android projects.
2. In my case I deleted all the files in the Shared project, added App.cs, TestMasterDetailPage.cs, TestMasterPage.cs, TestDetailPage.cs. App.cs MainPage = TestMasterDetailPage. Add Master and Detail pages just have a background color to differentiate the two pages (nothing else on it).
3. Run the iOS project in iPad 10.5 simulator (verified on 9.7 works the same) in Landscape mode. Notice that the default behavior is the Detail takes the entire screen. If you swipe on the screen, the Master appears and takes over 50% of the screen.
4. Set MasterBehavior in TestMasterDetailPage to Default, SplitOnLandscape has no impact.
5. Delete Xamarin.Forms package from both iOS and Android projects. Add Packages Xamarin.Forms 2.5.1.527436 to both.
6. Close VS for Mac. Reopen the project, clean the solution.
7. Run the project in iPad 10.5 simulator in Landscape mode. See that Master and Detail are split with Master taking only 1/4th the screen space. This is the expected behavior.

### Expected Behavior
On Xamarin.Forms 3.0.0.446417 Master should Popover the Detail in Portrait orientation and Split (taking 1/4th screen space) in Landscape orientation.

### Actual Behavior
Master takes more than 50% space in both Portrait and Landscape orientations and is always in Split mode.

### Basic Information
Visual Studio Enterprise 2017 for Mac
Version 7.5 (build 1254)
Installation UUID: 4ac69a27-3bcb-4de1-85d7-78fe5a92c513
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.3 (14154)
Build 9E145

Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Enterprise)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Enterprise)
Android SDK: /Users/vkamath/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 27.0.0

Java SDK: /usr
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Build Information
Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

Operating System
Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

### Screenshots
On Xamarin.Forms 2.5.1.527436
![ipad pro 10 5-inch - on xamarin forms 2 5 1 527436](https://user-images.githubusercontent.com/8212554/39764133-8f417f6a-52a4-11e8-970a-1fae37d7e9e4.png)

On Xamarin.Forms 3.0.0.446417 - it opens with Detail taking entire screen (completely Red). Swipe and see Master takes more than 50% of the screen.
![ipad pro 10 5-inch on xamarin forms 3 0 0 446417](https://user-images.githubusercontent.com/8212554/39764134-8f5b1c22-52a4-11e8-9436-5b1a72421a73.png)

**Comment by sander1133** [comment]
Annoying bug for a stable release!😞
In which version is this solution shipped?

**Comment by StephaneDelcroix** [comment]
@sander1133 it'll likely be fixed in `3.0.0-sr2`
