### ISSUE TITLE
[UWP] Setting WebView.Source as HtmlWebViewSource Processes Scripts Twice

### ISSUE THREAD

**Issue by joelbyrd** [xamarin/Xamarin.Forms#2631]
### Description
In UWP, when setting a WebView.Source property to type HtmlWebViewSource, the body and/or any scripts in the body appear to be processed twice.

### Steps to Reproduce

1. Create a new project, setting the main page Content to a WebView
2. Set the WebView.Source property to a new HtmlWebViewSource with the Html property set to an HTML document string that includes a simple script in the body that appends some content to a div in the body (for example: "<script>document.getElementById('someDivId').innerHtml += 'Testing';</script>" - see Reproduction Link below)
3. Launch UWP simulator for solution

### Expected Behavior
WebView content should display "Testing" once.

### Actual Behavior
WebView content displays "Testing" twice.

### Basic Information

- Version with issue: Xamarin.Forms v3.0.0.446417 (though I also see the behavior in v2.5.0.280555)
- Last known good version: Not sure if this has ever worked
- IDE: Visual Studio 2017, Version 15.3.5
- Platform Target Frameworks: 
  - UWP:  Windows 10 Creators Update (10.0; Build 15063)
- Nuget Packages: No additional packages added other than default Xamarin.Forms solution packages.
- Affected Devices: UWP simulator

### Screenshots

![image](https://user-images.githubusercontent.com/987670/39765120-16d785dc-52af-11e8-9cde-ffe52ad52657.png)

### Reproduction Link

https://www.dropbox.com/s/6791vm6bh5aac8g/WebView.zip?dl=0

**Comment by joelbyrd** [comment]
This issue is caused by the way the base url is being included dynamically. In the `WebViewRenderer.LoadHtml()` method, an internal WebView (internalWebView) is created and then loaded (via `internalWebView.NavigateToString(html);`) in order to parse the HTML document and insert a base url (via `InvokeScriptAsync`). Now let's say the HTML document includes JavaScript that dynamically adds HTML (via `someDiv.innerHTML += ...`). At this point, the document has been processed and the dynamic HTML has been added once. THEN, when this HTML string (with dynamic HTML already added to it) is passed to the actual WebView being used in the app, then it gets processed a second time, and the dynamic HTML therefore is added a second time - NOT expected behavior.

See [Xamarin.Forms.Platform.UWP.WebViewRenderer.LoadHtml()](https://github.com/xamarin/Xamarin.Forms/blob/882bf07917bea57b93d0d9becd768dcab739c26f/Xamarin.Forms.Platform.UAP/WebViewRenderer.cs#L26).

There needs to be another way of dynamically inserting the base url, or another way of solving whatever adding the base url is solving in the first place.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
