### ISSUE TITLE
Forms 3.0: White border around frames?

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#2634]
In case of my app it looks cool and is a great design idea but I guess it might not be the expected / wanted result that Frames now have a random white border. This appears for me since the 3.0 update of forms.

**Comment by rricarrdo** [comment]
Yeah... I confirm that is happening in Xamarin.Forms 3.0.0.446417 by default.

Simple workaround for now is to set BorderColor="Transparent" on the Frame.

**Comment by PaulVrugt** [comment]
I have the same issue. This is probably because of #1385 

Why doesn't a frame have a borderwidth property? I think it should have it, and the default should be 0 to keep backwards compatibility

**Comment by StephaneDelcroix** [comment]
could you please attach a small sample ? thanks

**Comment by PaulVrugt** [comment]
i can, but no sooner than coming Monday. so hopefully someone can upload a sample before then

**Comment by Sebastian1989101** [comment]
Just use a Frame with any not white page on Android (didn't test iOS and UWP yet). Don't know what sample code you expect for such a issue?

**Comment by kjsguld** [comment]
I had the same issue today. I've tried both OutlineColor="Transparent" and BorderColor="Transparent", and both of the seems to work.
