### ISSUE TITLE
Button is disabled when Visiblility set from false to true.

### ISSUE THREAD

**Issue by borbmizzet** [xamarin/Xamarin.Forms#2636]
### Description
When a XAML Button's IsVisible Propery gets set to false, and then true again, the IsEnabled Property is set to false when the button becomes visible.
### Steps to Reproduce

1. Bind the IsVisible property to a bool
2. Display the page
3. Click the button
4. Set the IsVisible bool to false
5. Delay 3 seconds
6. Set the IsVisible bool to true

### Expected Behavior
Button is enabled
### Actual Behavior
Button is disabled
### Basic Information

- Version with issue: 2.5.1.527436
- Last known good version: 2.5.0.280555
- IDE: VS 15.6.7/15.7
- Platform Target Frameworks: 
  - iOS:  Latest
  - Android: Latest 
- Android Support Library Version: 27
- Nuget Packages: Xamarin.Forms(.Pages) 2.5.1.527436
- Affected Devices: Ios, Android

**Comment by opcodewriter** [comment]
@borbmizzet Is it reproducing on XF 3.0 too?

**Comment by borbmizzet** [comment]
I'm not certain.  I'm running Forms with MvvmCross and they only just now pushed up a PR to update to XF 3.0.

**Comment by opcodewriter** [comment]
@borbmizzet  I see. God helps us all then. This kind of bugs when XF is supposed to be mature at version 3.0, is depressing. At least to me. Maybe it's just me.

**Comment by StephaneDelcroix** [comment]
I just tested iOS on 3.0.0 with the following handler

```csharp
async void Handle_Clicked(object sender, System.EventArgs e)
		{
			var btn = sender as Button;
			btn.IsVisible = false;
			await Task.Delay(3000);
			btn.IsVisible = true;
		}
```

it works as expected, the button is enabled when the visibility is reset to `true`

**Comment by StephaneDelcroix** [comment]
It also works perfectly fine in `2.5.1`. I'm closing this issue. Feel free to reopen and attach a reproduction project (that ideally doesn't depend on MvX).
