### ISSUE TITLE
[Enhancement] Report Binding failures

### ISSUE THREAD

**Issue by pingzing** [xamarin/Xamarin.Forms#2639]
# Rationale

In Xamarin.Forms, when a {Binding} expression fails, it fails silently, and at runtime. The only indication that the binding has failed is that nothing appears in the UI. Debugging this can be difficult--is it a BindingContext issue? A typo in my property name? Did I accidentally define my property as a member variable? Etc.

# Suggestion

Log binding failures similarly to the way that WPF and UWP do:

>System.Windows.Data Error: 40 : BindingExpression path error: 'NonExistingProperty' property not found on 'object' ''Grid' (Name='pnlMain')'. BindingExpression:Path=NonExistingProperty; DataItem='Grid' (Name='pnlMain'); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String') 

and print them out to the Debug log.

\~EDIT\~: Looking at [BindingExpression.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BindingExpression.cs) it looks like the logging code is there, but it never gets printed out to my Debug or Output windows. Could it be a configuration issue on my end?

Running Windows 10, Visual Studio 2017 15.6.7, reproducing this in XF 2.5.1.444934.

**Comment by Paul-Brenner-Tangoe** [comment]
+1 This would be fantastic.

**Comment by jfversluis** [comment]
I was triggered by this issue, looks like a good addition!

As @pingzing already mentioned, it is already written to the Trace logs.
To get them out right now, you could add this line somewhere in your app initialization code: 

`Xamarin.Forms.Internals.Log.Listeners.Add(new DelegateLogListener((arg1, arg2) => Debug.WriteLine(arg2)));`

Of course, you could do something other than a `Debug.WriteLine()`. Now, these messages (and probably others) will show up in your own app output.

![screenshot 2018-05-30 10 42 56](https://user-images.githubusercontent.com/939291/40709417-42443154-63f6-11e8-9d98-5b9bfa5f04a1.png)

Any thoughts on how we can make this more accessible?

**Comment by pingzing** [comment]
A few things come to mind immediately:

* Copy what UWP (and I think WPF?) does, and expose it as an event: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.debugsettings.bindingfailed . This could just be a proxy for the internal log listener you showed above.

* Introduce a DebugSettings class, and add it as a static property on [`Xamarin.Forms.Application.App`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class). To start, it could just have something like a `ShowBindingFailures` flag. If there's no expectation of future debug flags like this, maybe just add it directly to `App`.

**Comment by jfversluis** [comment]
@pingzing could you check the referenced commit on my fork? Something like this?

**Comment by pingzing** [comment]
That's very close to what I was thinking! I made a few minor changes in my fork-of-your-fork: https://github.com/pingzing/Xamarin.Forms/commit/bf4ba936ac893eec63c5c516325ea1f825a26dbe

My changes were driven by two things: My interpretation that toggling the `IsBindingTracingEnabled` flag should always enable printing to the Output log, and that event handler was just there for advanced scenarios. 

On that note though, I'm not sure if my simple `Debug.WriteLine("")` would be reliable/flexible enough?

Thoughts? Maybe too complex?

**Comment by jfversluis** [comment]
That makes sense. That way you don't need to do anything special to make this work besides toggling the setting. If you do have more wishes, you can hook into the event handler.

But now, how are we going to pull this together? :P

**Comment by pingzing** [comment]
Uh. Github is not well suited to this scenario =D

Maybe add me as a contributor to your fork, and we can use it as a basis for an eventual PR?

**Comment by jfversluis** [comment]
Done!
