### ISSUE TITLE
[Enhancement] Animatable MenuItem

### ISSUE THREAD

**Issue by gmwilhelm** [xamarin/Xamarin.Forms#2641]
## Summary

VisualElement implements IAnimatable so all controls that are derived from VisualElement can be animated. But MenuItem does not implement IAnimatable, so for example a ToolbarItem can not be animated.

## API Changes

IAdd IAnimatable to MenuItem and implement that interface, so that all controls derived from MenuItem can be animated.

## Intended Use Case

Enabling animations like rotation, scaling, fading etc. on MenuItems

**Comment by StephaneDelcroix** [comment]
`MenuItem`s do not have properties like rotation, or scale, or opacity. They're not `VisualElement`s. Making them `IAnimatable` would allow you to animate the Text, or the Command.

I don't see any value in that.

**Comment by gmwilhelm** [comment]
@StephaneDelcroix 

Why don't you see any value in animating a ToolbarItem? 

For example i have a ToolbarItem that i want to animate with a rotation while i'm loading some stuff.
At the moment, i can't do that.

**Comment by AustrianDudes** [comment]
We also would love to add a rotation animation to a ToolbarItem. Our apps shows an icon for starting a synchronization with our servers.

**Comment by redradist** [comment]
I need the same functionally for spinning synchronization image, like spinning progress but in ToolbarItem
