### ISSUE TITLE
Latest Visual Studio and Xamarin Forms 3.0 update won't deploy to device

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#2644]
Hi,

I have just upgraded to latest Visual Studio Mac and to Xamarin Forms 3.0 and now I have this problem.

All my applications only work on simulator but when I connect my iPhone to my Mac it will build the app and just stop with no errors [Build Success] and nothing will be installed on my device.

It was beautifully working just before I upgraded to Xamarin Forms 3.0.

Here is the build output:

[https://www.softnames.com/temp/OutputBuild.rtf](https://www.softnames.com/temp/OutputBuild.rtf)

Kindly help..

**Comment by StephaneDelcroix** [comment]
Please report this issue to VisualStudio for Mac. we can't help much over here.

**Comment by brendanzagaeski** [comment]
Cross-referencing note for the Microsoft team

This issue has also been reported in: <https://developercommunity.visualstudio.com/content/problem/249249/latest-visual-studio-update-wont-deploy-to-device.html>

**Comment by BioTurboNick** [comment]
@StephaneDelcroix This isn't a Visual Studio Mac issue. Same issue when building from Visual Studio 2017.

SIGABRT during Xamarin init according to crash dump.

**Comment by BioTurboNick** [comment]
@jrahma - Are you sure it just isn't deploying, or is it deploying but crashing immediately? I'm seeing the latter.

**Comment by jrahma** [comment]
It's not deploying. Looks like it's a bug [https://developercommunity.visualstudio.com/content/problem/249249/latest-visual-studio-update-wont-deploy-to-device.html?childToView=251948#comment-251948](https://developercommunity.visualstudio.com/content/problem/249249/latest-visual-studio-update-wont-deploy-to-device.html?childToView=251948#comment-251948)

**Comment by BioTurboNick** [comment]
Okay, maybe my thing is different.
