### ISSUE TITLE
Provide access to container from ListView item

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#2654]
In WPF, [ItemsControl.ContainerFromElement](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.itemscontrol.containerfromelement?System_Windows_Controls_ItemsControl_ContainerFromElement_System_Windows_DependencyObject_=) lets you break out of your view model to access the view that contains it. Xamarin.Forms needs an equivalent, for example to let you get at the ViewCell of a ListView. Otherwise, you end up with [hacky workarounds](https://stackoverflow.com/q/48811089/145173).

**Comment by deakjahn** [comment]
Can you upvote this a thousand times? Ore more than that? Constant problem. Most people are so enamored to MVVM that they simply don't understand that not all scenarios can or should be handled with binding. Just to name one, I routinely need to reach cells that have graphics Skia canvases and there is both no way and, actually, no reason to use binding (it's slow). Still, I need to keep in touch with the cell all right.

The necessary code is all there in XF for internal use. All it would need to open it up for us to use. Pretty, please...

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
