### ISSUE TITLE
MacOS main menu only shows the apple logo and the first item

### ISSUE THREAD

**Issue by ErwinDeGroot** [xamarin/Xamarin.Forms#2659]
Hi team,

### Description

I have a macOS app based on Xamarin.Forms. The Main.storyboard contains a main menu (opening in xCode shows the default menu items 'app_name' 'view' and 'window'). When I run the app however, only the first menu item is visible (including its submenu).

The missing menu items would not be a very big issue to me, was it not that **Apple rejected my app from the macOS App Store because it is missing the mandatory windows menu item.** 

I've submitted this issue a month ago at the Visual Studio developers community and Matt Ward [MSFT] was able to reproduce it. He forwarded the problem to the Xamarin.Forms team. I haven't heard about any progress since.
[Developers Community: MacOS main menu only shows one item](https://developercommunity.visualstudio.com/content/problem/234191/macos-main-menu-only-shows-one-item.html)

### Steps to Reproduce

1. Create a new Xamarin.Forms project
2. Add a macOS project (running the project at this point shows the full menu)
3. Update 'main.cs' and 'AppDelegate.cs' to use the 'App.xaml' from the shared Xamarin project
4. Running the project now shows a reduced main menu.

### Expected Behavior

The main menu at the top of the screen shows a complete menu, including the menu item 'Window'.

### Actual Behavior

The main menu at the top of the screen shows only the apple logo and the first menu item (which is the name of the app). Other menu items (e.g. 'Windows') are not visible.

### Basic Information

- Version with issue:
   VS for Mac 7.4.2
   Mono 5.8.1.0
   Xamarin.Mac 4.4.0.49

- Last known good version:
   None that I'm aware of. The issue was there from the start.
- IDE:
   Visual Studio Community 2017 for Mac
- Platform Target Frameworks: 
   macOS: High Sierra (Mac OS X 10.13.3)

### Screenshots

The following screenshot shows the reduced run time menu at the top left and the full menu design in XCode.

![screen shot 2018-05-10 at 16 11 46](https://user-images.githubusercontent.com/39160280/39874111-2b70f36a-546d-11e8-894a-a94391f70f53.png)

### Reproduction Link

I've created a minimal project which shows the problem:

[TestMenuBar.zip](https://github.com/xamarin/Xamarin.Forms/files/1991911/TestMenuBar.zip)

**Comment by ErwinDeGroot** [comment]
Hey, I didn't want to wait for the (pre)release to be published, so I downloaded a nightly build. It now works like expected. Thanks you guys for fixing this!

**Comment by fazil1987** [comment]
I don't see this working even in nightly build strange :(
