### ISSUE TITLE
FlexLayout incorrectly applies padding

### ISSUE THREAD

**Issue by simontocknell** [xamarin/Xamarin.Forms#2663]
### Description

Testing on Android emulator.

I have set `Padding = new Thickness(20, 0, 20, 0)` and `JustifyContent = FlexJustify.SpaceBetween`, so would expect there to be padding on both edges, and then an even space between each button.

### Actual Behavior

The padding all seems to be applied to the right hand side.

### Screenshots

![capture](https://user-images.githubusercontent.com/883083/39881676-871681d8-5479-11e8-9405-0cdcc70ef69a.PNG)

**Comment by StephaneDelcroix** [comment]
this was pointed to me by @davidortinau a few days ago. Thanks for filing this

**Comment by charlesroddie** [comment]
On UWP I find that Padding has no effect. Margins have an effect horizontally but not vertically. Overall padding and margins could use some basic testing on UWP.

**Comment by StephaneDelcroix** [comment]
still an issue, do not close (yet)
