### ISSUE TITLE
[Android] Buttons with BackgroundColor shadow/size problems.

### ISSUE THREAD

**Issue by hubertdej** [xamarin/Xamarin.Forms#2664]
### Description

Depending on Xamarin.Forms version, Buttons with BackgroundColor set to something different than Default/Transparent differ from material design look.

### Steps to Reproduce

1. Create a project and add `<Button BackgroundColor="BlueViolet" />` to the main page.
2. Install different Xamarin.Forms versions and compare results.

### Expected Behavior

Buttons have material design look.

### Actual Behavior

2.5.0.122203: shadow is clipped because it's too big (similar to #2558)
2.5.0.280555: buttons are too short, shadows are colored.
2.5.1.444934+: buttons are too big, no shadows.

### Basic Information

- Last known good version: none.
- Platform Target Frameworks:
  - Android: 8.1

### Screenshots
_Click to see full size_

**2.5.0.122203**
<img src="https://i.imgur.com/2iOosBe.png" width="400"/>

**2.5.0.280555**
<img src="https://i.imgur.com/HHYree0.png" width="400"/>

**2.5.1.444934+**
<img src="https://i.imgur.com/GZB3KKA.png" width="400"/>

**2.5.0.122203**, **2.5.1.444934+** comparison
<img src="https://i.imgur.com/v8DKMpR.png" width="400"/>

**Comment by samhouts** [comment]
Please see https://github.com/xamarin/Xamarin.Forms/pull/1935#issuecomment-375728802 for instructions to make the buttons match material design again (i.e., enable the shadow and padding). Thanks.

**Comment by hubertdej** [comment]
Thank you for the response. I followed your suggestion to use platform specifics but it didn't help much. I made two gifs to illustrate it.

Xamarin Forms **3.0.0.446417**

`BackgroundColor="Default"`
![](https://i.imgur.com/tYKm4VV.gif)
As you can see the only difference here is that in Xamarin Forms the shadow is shifted. Because of that we have much lower contrast near the bottom edge and it looks worse.

`BackgroundColor="#d9534f"`
`android:Button.UseDefaultShadow="True"`
![](https://imgur.com/NssU1Kb.gif)
UseDefaultShadow makes it look like **2.5.0.280555**. As I've mentioned above "shadows are colored".

I hope something can be done about it.

**Comment by hubertdej** [comment]
"Native" here is the way that Xamarin Live Player displays it.

**Comment by samhouts** [comment]
I'm afraid I don't understand. I assumed that you were comparing a Button made either in a native Android or Xamarin.Android app to a Button made in Xamarin.Forms. Is that not the case?

**Comment by hubertdej** [comment]
I found an image of the Danger button on the Internet and then I created a Button in Xamarin.Forms and compared them, so there was no source code of the native project.

Now I created these two projects:
[forms.zip](https://github.com/xamarin/Xamarin.Forms/files/2149522/forms.zip)
[native.zip](https://github.com/xamarin/Xamarin.Forms/files/2149523/native.zip)

![comparison](https://user-images.githubusercontent.com/34969251/42094568-7b4f8594-7bb0-11e8-9e51-e4fa53dc676a.gif)

Hope it helps.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
