### ISSUE TITLE
NRE in Grid EnsureRowsColumnsInitialized() for Xamarin.Forms iOS

### ISSUE THREAD

**Issue by devlanfear** [xamarin/Xamarin.Forms#2665]
### 
App crashes randomly (when refreshing UI when data updated) with NRE in Grid.EnsureRowsColumnsInitialized() inside Xamarin.Forms.
Also got NRE in: Grid.GetLastAutoRow(Xamarin.Forms.BindableObject child).
There are several more places where crash happens - all are related to Grid.Invalidate method.
Possibly related to: https://forums.xamarin.com/discussion/88367/nullreferenceexception-on-grid-calculateautocells-only-xf-ios

### Steps to Reproduce
Actually really hard to prepare sample project that can produce error in a right way.
We observe crash like 1/50 cases in our app. We expect that crashes are related to some "hard" operations on UI, so nearest plan is to speed up UI to check this.
So I would like to create bug without sample to reproduce - in case if this issue is well known and there is a workaround.

### Expected Behavior
No NRE inside Xamarin.Forms

### Actual Behavior
NRE inside Xamarin.Forms

### Basic Information

- Version with issue: 2.5.1.444934
- IDE: VS/VS for Mac
- Platform Target Frameworks: 
  - Xamarin.Forms:  2.5.1.444934

### Stacktrace
```
Xamarin.Forms.Grid.EnsureRowsColumnsInitialized()
Xamarin.Forms.Grid.MeasureGrid(double width, double height, bool requestSize)
Xamarin.Forms.Grid.LayoutChildren(double x, double y, double width, double height)
Xamarin.Forms.Layout.UpdateChildrenLayout()
Xamarin.Forms.Layout.OnSizeAllocated(double width, double height)
Xamarin.Forms.VisualElement.SizeAllocated(double width, double height)
Xamarin.Forms.Layout.<>c.<OnChildMeasureInvalidated>b__45_0()
Foundation.NSAsyncActionDispatcher.Apply()
at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIKit.UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate)
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)
```

**Comment by StephaneDelcroix** [comment]
The forum post you're referring to is about `_columns` or `_rows` being `null`, which are initialized in `EnsureRowsColumnDefinition()`.

My best guess, and my biggest fear, is a race condition :/

**Comment by StephaneDelcroix** [comment]
we were unable to reproduce this, so we're closing it. if you can come up with a sure way to trigger this bug, please comment and reopen this issue
