### ISSUE TITLE
Frame shadow not showing up on android after 3.0.0.446417 update

### ISSUE THREAD

**Issue by Nixon-Joseph** [xamarin/Xamarin.Forms#2666]
### Description
Possibly same issue as https://github.com/xamarin/Xamarin.Forms/issues/2423
Although I'm having the issue on modern devices -> api 26+.
Steps and behavior same as linked issue, other than api level.

***Edit***
Confirmed - dropping down to `2.5.1.527436` - shadows show up.

**Comment by StephaneDelcroix** [comment]
closing as dupe, adding a comment to the original bug
