### ISSUE TITLE
Xamarin.Forms.Build.Tasks.GetTasksAbi build error

### ISSUE THREAD

**Issue by jdstobbe** [xamarin/Xamarin.Forms#2667]
### Description
_The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\Projects\.nuget\packages\xamarin.forms\3.0.0.446417\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	App7.Android_	

Error is listed 3 times, once for ios, android and uwp.

In addition, the following warning:

Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	App7.Android		1	Active

### Steps to Reproduce

1a.  Start fresh:  New Project,  Visual C#--Cross-Platform--Moble App (Xamarin.Forms),  Blank App--<checked Android, iOS, Windows (UWP)>, Shared Project
1b.  Start fresh:  New Project,  Visual C#--Cross-Platform--Moble App (Xamarin.Forms),  Blank App--<checked Android, iOS, Windows (UWP)>, >NET Standard
(no code or other additions or subtraction)

2. Clean Solution  

3.  Rebuild (or Build Solution)

Note:  Solutions that used to Build, no longer Build.

### Expected Behavior
Clean build.

### Actual Behavior
Error Shown above.

### Basic Information
Have tried:  downgrading Xamarin Forms, restarting VS, reboot PC

- Last known good version:
Xamarin.Forms 2.4

- IDE:
Microsoft Visual Studio Enterprise 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA949
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40501.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40424.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40424.0
Azure Functions and Web Jobs Tools

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10420.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.27703.01
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

System Specs:
OS Name	Microsoft Windows 10 Enterprise 2015 LTSB
Version	10.0.10240 Build 10240
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DM-BR4G9Y1
System Manufacturer	Dell Inc.
System Model	OptiPlex 7010
System Type	x64-based PC
System SKU	OptiPlex 7010
Processor	Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, 3401 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A21, 12/21/2015
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	Legacy
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Desktop
Secure Boot State	Unsupported
PCR7 Configuration	Not Available
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.10240.17770"

**Comment by hackzai** [comment]
I have the same error too.

**Comment by StephaneDelcroix** [comment]
try cleaning and restarting the IDE.

if it persists, please attach your failing project, as we can reproduce over here

**Comment by hackzai** [comment]
I manage to resolved by installed .NET framework 4.7.1.

**Comment by StephaneDelcroix** [comment]
oh, yes, that...

**Comment by jdstobbe** [comment]
checking with our IT dept....do you believe that 4.7.2 would also fix the issue?

**Comment by dotMorten** [comment]
According to David Kean this is a bug in XF's build task:

> Folks this is a bug in the Xamarin task - it's making the assumption netstandard is in the GAC.

https://twitter.com/davkean/status/995148571891580928

**Comment by veringm** [comment]
Same problem here after upgrading xamarin.forms to 3.0.0.x. Installing .NET 4.7.1 made it work again.

**Comment by dotMorten** [comment]
We still haven't been told _why_ this change was made. I don't really get what features .NET 4.7.1 added that 4.6.1 didn't have which this build task relied on. This is an absolutely silly requirement - especially considering 4.7.1 isn't installed by default with VS2017.

One does not simply update a .NET Framework as it's a system-wide global change (that's why WPF on .NET Core is such a big deal as it resolves that issue)

**Comment by VladislavAntonyuk** [comment]
<Reference include="netstandard"/> fix the problem without installation of net 471

**Comment by SML913** [comment]
@dotMorten how did you do that ?

**Comment by LJordanCoCo** [comment]
I just want to add a bit of context here. 

**Conditions:**

- Start with an empty packages folder in /user/.nuget/packages
- Have one solution that is pre-upgrade (using project reference packages). In my case it's all the way back to 2.4
- Have one solution that is post-upgrade. In my case it's 3.1.0.697729
- Restore packages for both solutions at least once.
- Note that in the /user/nuget/packages/xamarin.forms folder _both_ sets of packages are downloaded
- Note that _only_ 3.1.0.697729 is installed on the new solution
- Try to build new solution
- Build intermittently fails with one of several errors, including XamlGTask and GetTasksAbi.
- Anecdotally, this seems to happen to me more when I try to build everything (right-click the Android project and click build with nothing else built). Building each project one at a time in order of dependency sometimes gets past this.

**Conclusion:**
Even when a solution has only the latest and greatest, if the old packages even exist on your machine, there can be problems. 

Note that in my configuration, I have some packages (notably FFImageLoading) that still reference older versions of Forms (in a >= way).  While having a direct package reference of a higher version _should_ prevent using the older versions (at least that's my understanding from the documentation), the build process seems to look at _every_ package available and tries to use lower versions even when it seems incorrect to do so.

I don't know if any of this will be useful, but I hope it helps someone who lands here.

**Comment by LJordanCoCo** [comment]
If you are also experiencing this issue, I'd say not. I'm currently on 10 Pro 1803 with VS 2017 15.8.0.

**Comment by divyesh008** [comment]
Installing .net framework 4.7.1 will solve the issue!

**Comment by AlexDelRosario** [comment]
El mismo error me paso lo que realize para el funcionamiento fue Eliminar las carpetas Bin y Obj de cada archivo Luego limpie y recompile luego actualice mi Windows 10 a la ultima versión y todo empezó a funcionar correctamente. Saludos.

**Comment by AlexDelRosario** [comment]
El mismo error me paso lo que realize para el funcionamiento fue Eliminar las carpetas Bin y Obj de cada archivo Luego limpie y recompile luego actualice mi Windows 10 a la ultima versión y todo empezó a ### **funcionar correctamente.** Saludos.
