### ISSUE TITLE
Allow to extend TableSection

### ISSUE THREAD

**Issue by xamoulin** [xamarin/Xamarin.Forms#2668]
### Description

Allow to extend TableSection by removing the sealed qualifier.

**Comment by geskill** [comment]
\+ TableRoot (in order to add ItemsSource and ItemTemplate property in my code).

**Comment by Axemasta** [comment]
Hi Guys, 

This would be such a nice feature. Adding corner radius to box-view was nice but it was not necessary, we could do that ourselves. However there are a fair few use cases for extending table sections that could be really useful. I'll give my use case:

My resourcing app allows users to create expense claims that go into our backend with all the info needed for invoicing plus pictures of the receipts. The forms is static, so I used `TableView`, I currently have the following section for adding images:

![image1](https://user-images.githubusercontent.com/33064621/62038766-45a0a700-b1ee-11e9-860f-8f7c0701b829.png)

The button prompts a new forms to add an image, when added any images will be added to this section (above the button).

This implementation looks nice, but the code behind it is dreadful. There is no portability, I build all my custom functionality into generic controls that I can port around the app, this is the one part of my app that is unportable. If `TableSection` were to become extendable the implementation could become 1 simple line of xaml:

`<controls:AttachmentsSection Attachments="{Binding ExpenseAttachments}"/>`

It would be very much appreciated if this change was to be made!

**Comment by jfversluis** [comment]
See comment on the PR I had opened for this: https://github.com/xamarin/Xamarin.Forms/pull/7948#issuecomment-541553857

You might want to find another solution instead of using a `TableView` for this.
