### ISSUE TITLE
.netStandard missing error when building 3.0 branch 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [xamarin/Xamarin.Forms#2672]
### Description
I have cloned the source code of XF in Master branch and it builds with no problems, however when I switch the branch from master to 3.0 I get the following error . And suddenly I cannot make a netstandard 2 Projects anymore . 
 
```
The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.	Xamarin.Forms.CustomAttributes	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets
```
### Steps to Reproduce

1. Clone the source code 
2.  Build the solution 

### Expected Behavior

It builds successfully 

### Actual Behavior
 Error 
```
The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.	Xamarin.Forms.CustomAttributes	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets
```
### Basic Information

- Version with issue:
- Last known good version: master branch 
- IDE: Visual Studion 2017

**Comment by StephaneDelcroix** [comment]
you have to clean and restart the IDE when switching branches, if the differences are big enough
