### ISSUE TITLE
Exception occurs when giving null values in picker itemsource collection

### ISSUE THREAD

**Issue by suriyakalidoss** [xamarin/Xamarin.Forms#2674]
### Steps to Reproduce

1.Assign null value to one of the items in collection
2.Bind the collection as the itemsource to the picker
3.programs crashed when clicking the picker

### Expected Behavior
When assigning null value to one of the item in the collection ,picker should not crash while clicking. 
### Actual Behavior
When assigning null value to one of the  items in the collection, empty string should added while drop down the picker.
### Basic Information

- Version with issue:.Xamarin Forms 2.4.0.280
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: API 22
  - UWP:  10.0.14393.0

### Screenshots

Please refer the below link for images
Image:  http://www.syncfusion.com/downloads/support/directtrac/general/ze/BUGZILLA497018189

### Reproduction Link

Sample link : http://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample1031557222

**Comment by hartez** [comment]
[_2674 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4162078/_2674.Repro.zip)

Looks like the Picker is missing a null check in GetDisplayMember before calling `item.ToString()`.

**Comment by sahi82** [comment]
Picking this issue
