### ISSUE TITLE
Stack layout not properly using scaled image size in UWP project

### ISSUE THREAD

**Issue by MarkStega** [xamarin/Xamarin.Forms#2676]
### Description
Images in a stack layout are arranged using full image size even if the image is scaled

### Steps to Reproduce

1. 
Create a XAML page with the following content:
`         <StackLayout Orientation="Horizontal"
                     Grid.Row="0"
                     Padding="0"
                     Spacing="0">
            <Image Source="{local:ImageResource Optimiser.NG.Assets.Resources.ORGO.png}"
                   Scale="1.0" />
            <Image Source="{local:ImageResource Optimiser.NG.Assets.Resources.ORGO.png}"
                   Scale="1.0" />
            <Image Source="{local:ImageResource Optimiser.NG.Assets.Resources.ORGO.png}"
                   Scale="1.0" />
            <Image Source="{local:ImageResource Optimiser.NG.Assets.Resources.ORGO.png}"
                   Scale="1.0" />
            <Image Source="{local:ImageResource Optimiser.NG.Assets.Resources.ORGO.png}"
                   Scale="1.0" />
        </StackLayout>`
2.  Run the application selecting the UWP project as the startup project. The 5 images are drawn as expected. 
3. Change the 1.0 scale factor to 0.5 for all 5 images. Run the UWP app again. The images are scaled but placed in the same location as the unscaled images.

### Expected Behavior
Expect that scaling the images would be reflected in the spacing
### Actual Behavior
Images are centered as if still full size
### Basic Information

- Version with issue: 3.0.0.0.446417
- Last known good version: n/a
- IDE: Visual Studio 2017 15.7.0 for Windows
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: n/a 
  - UWP:  16299 
- Android Support Library Version: n/a
- Nuget Packages:
Microsoft.NETCore.UniversalWindowsPlatform 6.1.4
NETStandard.Library 2.03
FZ 3.0.0.0.446417
- Affected Devices: Windows

### Screenshots
![iconsatfullsize](https://user-images.githubusercontent.com/634561/39925164-972c5e6a-54f8-11e8-88b4-1bfbee6069c4.png)
![iconsscaled0 5](https://user-images.githubusercontent.com/634561/39925165-97394238-54f8-11e8-8944-608b40b4f3b3.png)

**Comment by StephaneDelcroix** [comment]
That's not a bug. Transformation (scale, rotate, translate) are applied after the measure pass, and do not affect measurement.

**Comment by MarkStega** [comment]
It certainly seems to me that the bug is that the measure pass is performed before the transformation pass.

**Comment by GalaxiaGuy** [comment]
Although it might not be the behavior you want, it's well established that Scale (and the other transform properties) don't affect layout, so changing it would be a massive breaking change.
