### ISSUE TITLE
Breaking Change in 3.0.0.446417 : Mac app - Application Menus not working 

### ISSUE THREAD

**Issue by fazil1987** [xamarin/Xamarin.Forms#2679]
We have created a Mac app out of Xamarin Forms - Xamarin Mac cocoa app integration as per this article https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/

Initial Xamarin Forms version was  2.5.0.280555

When we upgraded to the latest version 3.0.0.446417, the application menus stopped working. In fact most of the menus are not even visible. 

This happens even for a hello world app created out of XF latest version. 

### Steps to Reproduce

1.  Create a Hello world Mac app
2.  Integrate with hello world Xamarin Forms app
3. Run the application
4. Check the Application menus

### Expected Behavior
1. All default app menus should appear
2. Menu's should open its child menus when clicked

### Actual Behavior
1. Only one menu ( with app name ) appears.
2. Even on clicking the menu, nothing happens 

### Basic Information

- Version with issue: 3.0.0.446417
- Last known good version: 2.5.0.280555
- IDE: Visual Studio For Mac 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - Mac : Latest Xamarin.Mac app
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:  Mac OS in 10.11, 10.12 and 10.13

### Screenshots

![appmenuissue](https://user-images.githubusercontent.com/7386648/39932408-ab0b223a-555d-11e8-86c5-5e19e783d2e1.gif)

**Comment by fazil1987** [comment]
The moment we remove the NSMainStoryBoard file link in the info.plist to integrate with Xamarin Forms, This stops working. 

We currently stopped publishing our app due to this. Any workaround till this gets fixed would be really appreciated given our situation. 

Now we can't even go back to previous version because even though this problem would be fixed,  the app as such works only in 10.12, it breaks in 10.13 as well in 10.11

**Comment by rmarinho** [comment]
@fazil1987 you need to add back the storyboard. Also check this  issue with more info why it's needed #2659  remember our macOS is still on preview so some changes will be expected before going stable.
Thanks. And please reopen if it's still a problem.

**Comment by fazil1987** [comment]
Hi @rmarinho, though this solves the App menu issue, it kind of brings the new issue by opening a another app window. Please see the attachment

Definitely, we can't ship our app with this. Secondly, thought you said its in preview, since it's added part of the stable XF package, I expect it to be stable with whatever it supports. Ofcourse, it cannot be bug free, but bugs like this basic is not giving a good feel

![new_window_pop_up](https://user-images.githubusercontent.com/7386648/40127097-4861b41c-594c-11e8-832b-0222afca9f36.gif)

**Comment by fazil1987** [comment]
@rmarinho @StephaneDelcroix  guys why no reply on this ?

**Comment by ErwinDeGroot** [comment]
@fazil1987 you want a solution to problem #2659, which should be solved already. However the fix is not available yet, so we need to wait until the next (pre)release.

**Comment by fazil1987** [comment]
@ErwinDeGroot As @rmarinho mentioned in his previous comment that 

> please reopen if it's still a problem.

So, I thought its fixed part of the minor XF update that was popping up in my VS for mac. Anyways, thanks for fixing it and I am looking forward for the next version.
