### ISSUE TITLE
Open a file from Remote Network Share in Xamarin UWP application

### ISSUE THREAD

**Issue by jainankit2474** [xamarin/Xamarin.Forms#2683]
Is there any way to open a file from Remote Network Share in Xamarin UWP Application. ?

We tried with Xamarin File Picker, but it includes user to select the file.

    private void OpenFile()
    {
        FileData fileData = await CrossFilePicker.Current.PickFile();
        string fileName = fileData.FileName;
        string contents = System.Text.Encoding.UTF8.GetString(fileData.DataArray);
     }

We want that If the user clicks on the **Path** then the file will display in a Read Mode.

**Comment by StephaneDelcroix** [comment]
this question is more suited to other forums, like stackoverflow. Please try to get help from there

**Comment by jainankit2474** [comment]
It is specific to Xamarin UWP Application that is targetting to .NET Standard 2.0. We have the option to use the code, but it's not working in .NET Standard 2.0. It is throwing an error "Package 'XPlat.Storage 1.2.18073.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.".

**Code:**
```
var filename = @"\\myserver\myshare\myfile.txt";
var file = await StorageFile.GetFileFromPathAsync(filename);
using(var istream = await attachmentFile.OpenReadAsync())
    using(var stream = istream.AsStreamForRead())
          using(var reader = new StreamReader(stream)) {
              var contents = reader.ReadToEnd();
          }
```

**Comment by StephaneDelcroix** [comment]
we do not own `XPlat.Storage`
