### ISSUE TITLE
[Enhancements] ImageCell image loading reuse

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2687]
### Description
Currently all the ImageCell code on each platform doesn't reuse the image loading code that's used by ImageRenderer.  This will become more of a problem once GIFS are added but currently this causes the largest issues on Android because the coded that was added to pull from drawables isn't being used this if a user uses an ImageCell they will get an out of memory exception

### Expected Behavior
All image loading code should just use the same Utility functions to load images

### Actual Behavior
Image loading code is copy pasted around

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
