### ISSUE TITLE
Unable to share ef core data model with annotations during use of Live Player IOS

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#2692]
When attempting to use datanoations with a shared model from my ef core model and bind it to a slenderised j son list and include a reference in my xamrain forms project the xamrin live player will fail.

Steps to reproduce

1. Create a xamrin forms app all three platforms create a web api that shares a .net standard libary.
2. Add the reference to ef core shared libary which holds the models and data notations such as [Key] etc 
3. Call the json deslierzier in json .net to the object within the xamrin forms  app.
4. Deploy to the live player it will complain 
[XLP_Logs_18-05-12_21-30-27.txt](https://github.com/xamarin/Xamarin.Forms/files/1997920/XLP_Logs_18-05-12_21-30-27.txt)
![image](https://user-images.githubusercontent.com/5619229/39961358-6769b530-562c-11e8-8a45-93dcdbc5050c.png)
![image](https://user-images.githubusercontent.com/5619229/39961365-81fa8a82-562c-11e8-8d6b-eb258c9bf346.png)

Please find the below repo url 

https://github.com/davidbuckleyni/CallManagmentApp

**Comment by davidbuckleyni** [comment]
Thank you do we have a time for this at all this will be great

**Comment by StephaneDelcroix** [comment]
cc @praeclarum

**Comment by davidbuckleyni** [comment]
Do we no a time line as to when this may be pushed to PR and are we as developers avialable to work o this

**Comment by davidbuckleyni** [comment]
I believe that its not just ios affected may be all three platforms

**Comment by davidbuckleyni** [comment]
I find it very poor that we do not get status updates on progress of items.

**Comment by StephaneDelcroix** [comment]
LivePlayer is not supported by this team (and probably not supported anymore). closing. thanks
