### ISSUE TITLE
Provide FlexLayout support for aligning with auto margins

### ISSUE THREAD

**Issue by sparkie108** [xamarin/Xamarin.Forms#2694]
### Description

"auto" doesn't appear to be a valid margin value when using FlexLayout.  It is allowed in CSS and is very useful for aligning elements, see [Aligning with auto margins](https://www.w3.org/TR/css-flexbox-1/#auto-margins).

### Steps to Reproduce
Add the following style:
   ` margin-left: auto;`

### Basic Information

   ` <PackageReference Include="Xamarin.Forms" Version="3.0.0.446417" />`

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
