### ISSUE TITLE
[iOS] View is clipped at the bottom with ongoing phone call/active Wi-Fi hotspot

### ISSUE THREAD

**Issue by RyuuTora** [xamarin/Xamarin.Forms#2699]
### Description

As we know. On iOS the status bar can change in height (an color) if you for instance have an ongoing phone call or have the WiFi hotspot active.
When presenting a navigation page (with one or more pages) modally with elements aligned to the bottom of the screen, the view will be clipped at the bottom. But only if the view is presented after the status bar got the larger height.
If the view is already presented when the status bar changes in height, the view resizes correctly.
When the view is clipped, and the status bar is changed to default height, the view is still clipped and the only way to get a correctly sized view is to close it and present it again (or to restart the app).

It should be noted that if the page is presented modally without being embedded in a navigation page, no clipping of the view occurs, even if the status bar has the larger height from the beginning.

Also to be noted, iPhone X doesn't really suffer from this as it just displays a smaller indicator in the corner of the status bar (rather than increasing the height of it).

### Steps to Reproduce

1. Create an empty Xamarin Forms app
2. Create a page 
   - Add a Grid or StackLayout
   - Add some element to the Grid (or StackLayout), like a Label, Button (or another layout with sub elements). Set *VerticalOptions* to "End" for this element.
3. In the constructor for *App.xaml.cs* set *MainPage* to whatever page you like. Can be the one we created in **Step 2** or an empty one.
4. In *OnStart()* create a new *NavigationPage* with the page we created in **Step 2** as the *root page* (pass it to the constructor).
5. Now present the created *NavigationPage* using *PushModalAsync* (on *MainPage.Navigation*).
(Of course the page could be presented later, for instance via a button. But this is the easiest way to reproduce the issue).

### Expected Behavior

A correctly sized view with no clipping.

### Actual Behavior

An incorrectly sized view, where elements aligned to the bottom of it gets clipped.

### Basic Information

- Version with issue: Xamarin Forms 3.0.0
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: N/A 
  - UWP:  N/A 
- Android Support Library Version: 
- Nuget Packages: Xamarin Forms
- Affected Devices: iPhone/iPhone Simulator (not iPhone X/iPhone X Simulator)

### Screenshots

**Normal status bar, no clipping**

<a title="Normal status bar, no clipping" href="https://user-images.githubusercontent.com/23473245/39992951-a263fce2-5774-11e8-99fe-6036defcd0ee.png" target="_blank"><img src="https://user-images.githubusercontent.com/23473245/39992951-a263fce2-5774-11e8-99fe-6036defcd0ee.png" width="220" alt="Normal status bar, no clipping" /></a>

**Large status bar, no clipping**

<a title="Large status bar, no clipping" href="https://user-images.githubusercontent.com/23473245/39992952-a281162e-5774-11e8-8643-1fb8738029a4.png" target="_blank"><img src="https://user-images.githubusercontent.com/23473245/39992952-a281162e-5774-11e8-8643-1fb8738029a4.png" width="220" alt="Large status bar, no clipping" /></a>

**Large status bar, clipping at bottom**

<a title="Large status bar, clipping at bottom" href="https://user-images.githubusercontent.com/23473245/39992955-a29d66a8-5774-11e8-9004-e1f75b53b3e5.png" target="_blank"><img src="https://user-images.githubusercontent.com/23473245/39992955-a29d66a8-5774-11e8-9004-e1f75b53b3e5.png" width="220" alt="Large status bar, clipping at bottom" /></a>

**Comment by pauldipietro** [comment]
Checked against 3.1pre as well; would note to not use an iPhone X device/simulator as the background identifier functions differently from other iPhone devices.

**Comment by RyuuTora** [comment]
As @pauldipietro points out, iPhone X doesn't suffer from the issue due to its different status bar layout. I've updated the description so that it's a bit clearer on that point.

**Comment by kurianov-pavel** [comment]
Has anyone found a solution to this problem?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
