### ISSUE TITLE
WPF Renderers in External Assemblies Don't Always Load

### ISSUE THREAD

**Issue by peter0302** [xamarin/Xamarin.Forms#2700]
[XFormsWPFBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2000859/XFormsWPFBug.zip)

### Description
If WPF custom renderers are in their own assembly separate from the main application, they are not always loaded.

### Steps to Reproduce

1. Define a custom control in the shared Xamarin Forms project, e.g., `public class MyLabel : Label`, and use it in the main page of the shared project.
2. Create a WPF project for the main application, following the example at [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf](url)
3. Create a second WPF project as a `WPF Custom Control Library (.NET Framework)` and add Nuget references to `Xamarin.Forms` and `Xamarin.Forms.Platform.WPF`
4. Create a custom renderer for `MyLabel` in the WPF custom control project, overriding `OnElementChanged`. Set a breakpoint in that method.
5. Run the WPF main project.

See also attached solution for minimum reproduction steps.

### Expected Behavior

I expect the breakpoint in `OnElementChanged` gets hit.

### Actual Behavior

The breakpoint in `OnElementChanged` in my WPF renderer does not get hit because the assembly is not loaded. However, the one in an identically set-up assembly for the UWP project does.

### Basic Information

- Version with issue: v3.1.0.469394-pre1
- Last known good version: NA
- IDE: VS2017 15.7.1
- Platform Target Frameworks: 
  - UWP:  16299 (used for reference only; issue is in WPF)
  - WPF: NETFX 4.6.1
- Nuget Packages:  Xamarin.Forms.Platform.WPF v3.1.0.469394-pre1
- Affected Devices: NA

### Additional Info

It is pretty clear what is happening; the WPF renderer assembly is not being loaded at runtime because the linker doesn't see any direct references to it in the code. Notably if I add an initializer within the renderer assembly as a dummy method and call it from the main assembly, then it works fine. I therefore hesitated before posting this as an issue as it may seem obvious that this is needed; however, the UWP project does *not* appear to have the issue, so it seemed worth noting for that reason.

Moreover, I tried using the `Preserve` attribute per [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/introduction](url) but this seemingly had no effect, which might also be unintended. The information online also seems to suggest that the issue is limited to IOS, but that does not appear to be the case.

Either way, I figured it was worth posting so others who come across the issue can quickly find this workaround.

**Comment by StephaneDelcroix** [comment]
This is a known behavior. You have to somehow add a reference to that external assembly. A Common pattern is to add, and call , a static empty `Init()` method.

**Comment by peter0302** [comment]
Yeah I figured that might be known; like I said what threw me is that the UWP project didn't require it and the info I was finding online was inconsistent. I'll self-close this then so hopefully anyone else who comes across this will see this solution. Thanks!
