### ISSUE TITLE
[WPF] Page doesn't render

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#2704]
### Description
Page doesn't render if init navigation not in constructor

### Steps to Reproduce
1. Create Xamarin Forms app with Android and wpf projects.

2 In Xamarin Forms app change method to this
public App()
        {
            InitializeComponent();
            InitApp();     // used for DI        
        }

protected override async void OnStart()
        {
            base.OnStart();
            await  InitNavigation();
            OnResume();
        }

private static Task InitNavigation()
        {
            var navigationService = IoC.Container.GetInstance<INavigationService>();
            return navigationService.InitializeAsync(); // Navigate to page NavigateToAsync<MainViewModel>()
        }

3. Run on Android. The page is rendered.
4. Run on WPF. The page is not rendered

### Expected Behavior
Page is rendered on wpf

### Actual Behavior
The page can be rendered on WPF if run InitNavigation on Constructor

public App()
        {
            InitializeComponent();
            InitApp();
            InitNavigation();          
        }

protected override async void OnStart()
        {
            base.OnStart();
            OnResume();
        }
### Basic Information

- Version with issue: 3.1.0.469394-pre1, the same on previous
- Last known good version:
- IDE: VS2017 15.7.1
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
We will need a reproduction project as you're presumably using an outside library.

**Comment by VladislavAntonyuk** [comment]
I also use Autofac for DI. You can test on this project https://github.com/jsuarezruiz/xamarin-forms-gtk-movies-sample.
in this file https://github.com/jsuarezruiz/xamarin-forms-gtk-movies-sample/blob/master/src/Movies/Movies/App.xaml.cs
move InitNavigation(); from ctor to protected override void OnStart()

**Comment by PureWeen** [comment]
looks like a timing issue with changing the Mainpage in onstart

if you add an

await Task.Delay(10)

before initiating the navigation then it renderers

**Comment by VladislavAntonyuk** [comment]
On your device it’s enough 10 milliseconds delay in another maybe not. So I think it should be fixed

**Comment by brettclutch** [comment]
FYI I ran into this as well, took me a few hour to realize that setting 'MainPage' after constructor doesn't work. E.g. trying to set MainPage in OnStartUp doesn't actually set the page. I solved by adding a NavigationPage() in constructor + MainPage.PushAsync() to push my page to be displayed.
