### ISSUE TITLE
StyleSheet Reference Tag Throws Build Error. 

### ISSUE THREAD

**Issue by TrustEEI** [xamarin/Xamarin.Forms#2708]
### Description
    <ContentPage.Resources>
        <StyleSheet Source="/Assets/Style/style.css" />
    </ContentPage.Resources>

The above code is causing the application to fail during build with a generic error message. 

### Steps to Reproduce

1.  Browse to https://github.com/xamarin/Xamarin.Forms/issues/1552. At the bottom of the page, find the CSS.zip file. Download and open Xamarin Project. 
2.  Attempt to Build and Deploy project to via Xamarin Live or an emulator.  
3.  Error is Thrown. Build Fails.

This also occurs on the Monkey CSS Project as well. 

### Expected Behavior
1. Project Successfully Builds. 
2. CSS is properly referenced in the app and effects the styling of the app.

### Actual Behavior
1. Build Fails. Throws the same error message as reported in 1552. The Same issue is references in Ticket 1553. 

The behavior also occurs with the Monkey CSS Example App. https://developer.xamarin.com/samples/xamarin-forms/UserInterface/Styles/MonkeyAppCSS/

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.446417
[Xamarin-StyleSheet-Issue-ScreenShots.docx](https://github.com/xamarin/Xamarin.Forms/files/2003481/Xamarin-StyleSheet-Issue-ScreenShots.docx)

- Last known good version: Unknown.

### Screenshots
Attached

**Comment by StephaneDelcroix** [comment]
also, it looks like the issue reported are intellisense issues. could you filter those out ?

**Comment by StephaneDelcroix** [comment]
closing as inactive
