### ISSUE TITLE
Navigation not working after Navigating to page with a Custom Layout

### ISSUE THREAD

**Issue by johnfurog** [xamarin/Xamarin.Forms#2710]
### Description
Navigation not working after Navigating to page with a Custom Layout on Xamarin.Forms Version >2.5.0.280555
### Steps to Reproduce

1. Navigate to a page with Custom Layout 
2. Go Back
3.  Navigate to any page

### Expected Behavior
Able to navigate to that pages
### Actual Behavior
Navigation Not Working
### Basic Information

- Version with issue: >2.5.0.280555
- Last known good version: <=2.5.0.280555
- IDE: Visual Studion 15.6 Community Edition
- Platform Target Frameworks: 
  - iOS:  NONE
  - Android: 8.1 
  - UWP:  NONE 
- Android Support Library Version: 
- Nuget Packages: 4.6.0
- Affected Devices: Samsung Galaxy J5 Prime (7.0)

### Reproduction Link
https://github.com/johnkennethfurog/PrismNavigationService

**Comment by pauldipietro** [comment]
This seems to function differently on 3.1 where the first navigation works correctly, but going back causes subsequent attempts to fail. Tested on an 8.1 emulator.

**Comment by johnfurog** [comment]
hi @pauldipietro same with my scenario , navigation working perfectly until you navigate to a page with custom layout , after that navigation will not work anymore

**Comment by rmarinho** [comment]
is this issue only with Prism Library ?

**Comment by johnfurog** [comment]
I dont think it is related to the prism library . Ive tried it also on a solution that dont use prism and the issue still exist

**Comment by rmarinho** [comment]
Can you please add a reproduction of this issue without using Prism , thanks

**Comment by johnfurog** [comment]
Yeah sure. Ill attach it today

**Comment by johnfurog** [comment]
upon doing it without prism template pack and the issue is now gone .
