### ISSUE TITLE
[UWP][XamlC] Not hitting breakpoints

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#2712]
### Description

I have a Xamarin.Forms project that uses a .Net Standard shared component. I’m using Windows 10 RS4 (17134) with Visual Studio 2017 v15.7.1. I can hit breakpoints I set in the UWP code but I can’t get it to hit breakpoints I set on the .Net Standard share code. Following the instructions below does not fix the issue. I tried this on multiple machines and also with just a sample project that uses .Net Standard and the issue reproes across all these scenarios. Is this known? Is there a workaround?

### Screenshots

![image001](https://user-images.githubusercontent.com/313003/40044111-b0e021ee-5826-11e8-9288-cc40a69e67e2.jpg)

**Comment by kvpt** [comment]
I also encountered this problem on a project.
Looking from where Visual Studio get the pdbs  ("Debug > Windows > Modules" during debugging), I found that the pdbs are not searched in the right folder.
I have for the moment added an xcopy command in the post build event of the project.
It's perhaps the same problem here.

**Comment by powerdude** [comment]
I ran into this too.  Try changing the property of the UWP project.  Build -> Advanced (button at bottom) ->Debugging Information = Full.

Also, check your .Net Standard project and see that it's set to PDB-only.

I read somewhere that somehow the template was changed accidentally or something.

**Comment by MelbourneDeveloper** [comment]
@StephaneDelcroix as far as I know, you cannot change this through the Visual Studio front end. You have to directly edit your csproj file. I've had this problem before. Here is an example of how to fix it:

```
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
```

**Comment by MelbourneDeveloper** [comment]
@StephaneDelcroix  it seems to be a known issue, but all the related issues seem to have been closed...

I don't know if anyone is planning on actually fixing it...

https://github.com/dotnet/standard/issues/621

**Comment by StephaneDelcroix** [comment]
@MelbourneDeveloper, @powerdude, @kvpt : thanks for those information, it's helpful

**Comment by cbs-cbt** [comment]
Hello,
I have the same problem here. Had to select "PDB only" in project's properties.
@MelbourneDeveloper you can change the option by selecting the project -> Properties -> Build -> Advanced -> Debugging information the select "Pdb-only"

**Comment by StephaneDelcroix** [comment]
@PureWeen is this related to the fix you pushed a few days ago ?
