### ISSUE TITLE
The OnAppearing() issue with Navigation.PushAsync()

### ISSUE THREAD

**Issue by Billycool1020** [xamarin/Xamarin.Forms#2716]
### Description

In main page use a button call ` Navigation.PushAsync(new Page1())` to open `Page1`.  The `OnAppearing()` in `Page1` fired again immediately if I call the `Device.OpenUri(new Uri("https://github.com/"))` in the `OnAppearing()`. But if I set a breakpoint or set `Task.Delay(500)` before the `Device.OpenUri()`, second `OnAppearing()` will not fired until I get back from the browser. The similiar issue also happens when call `Navigation.PushAsync()` in the `OnAppearing()`.   

### Steps to Reproduce

1.  The App.cs:
```
		public App ()
		{
			InitializeComponent();
			MainPage = new NavigationPage(new MainPage());
		}

```
2. MainPage
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"           
             x:Class="App1.MainPage">
    <StackLayout>
        <!-- Place new controls here -->
        <Button Text="Page 1" x:Name="button" Clicked="button_Clicked"/>
    </StackLayout>
</ContentPage>
```

```
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}
                private void button_Clicked(object sender, EventArgs e)
                {
                    Navigation.PushAsync(new Page1());
                }
       }
```

3. Page1
```
	public partial class Page1 : ContentPage
	{
		public Page1 ()
		{
			InitializeComponent ();
       		 }
      		 protected override  void OnAppearing()
    		 {   
                        base.OnAppearing();
                        Device.OpenUri(new Uri("https://github.com/"));
                 }
         }

```
### Expected Behavior
`OnAppearing()` fired and open one tab in the browser.
### Actual Behavior
`OnAppearing()` fired twice and open two tabs in the browser. If I set a breakpoint or set `Task.Delay(500)` before the `Device.OpenUri();`, second `OnAppearing()` will not fired immediately .
### Basic Information

- IDE:  Visual Studio Enterprise 2017 15.7.1 
- Platform Target Frameworks: 
  - Android: 8.1

**Comment by pauldipietro** [comment]
The described behavior appears to occur as of the 3.1-pre on an 8.1 emulator.

**Comment by VahidShir** [comment]
I have this problem in Xamarin.Forms "2.5.1.527436" and on both emulator and device.

**Comment by PureWeen** [comment]
Consolidating OnAppearing issues here
https://github.com/xamarin/Xamarin.Forms/issues/6919
