### ISSUE TITLE
iOS: How to get stack trace line numbers in runtime?

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#2718]
I'm catching exceptions thrown from my code but still want to investigate them so I save them to a log file.
I have a TestFlight user who gets these exceptions that I can't repeat.
Now the log file has all the method names but no line numbers.

From a forum thread I learned that I need to include all debug info on the Compiler page and also not use the LLVM compiler. Regret that is not enough.

Looking at the project file I can see that the debug configuration also has  this line: `<MtouchDebug>True</MtouchDebug>`
When I copy it to the release config the line numbers do appear however can I upload a build like that to iTunesConnect? What are the official steps to get the line numbers in runtime?

Please advise.

**Comment by duzenko** [comment]
No, 
`<DebugType>full</DebugType>`
is not working for me.

**Comment by PureWeen** [comment]
do you have all of the things here checked?

https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/debugger-settings

whatever build you are producing if you deploy that to a local device are you able to hit break points from the IDE?

**Comment by duzenko** [comment]
That works on iOS but not on Android.
I checked Enable Developer Instrumentation and set Debug Information to Full.

**Comment by PureWeen** [comment]
can you by chance send a small project showing the issue? Mainly so I can just see your project settings and try for myself?

With Android you might need to turn off the linker/proguard in order to have a build published that will give you line numbers

**Comment by PureWeen** [comment]
@duzenko  try unchecking "optimize code" in the project => build menu

When I do that then I'm getting line numbers on android

**Comment by PureWeen** [comment]
No updates in the last 30 days
