### ISSUE TITLE
[Suggestion] Opinionated cross-platform theme

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/Xamarin.Forms#2721]
## Title
Create a theme or library, that when applied to an existing XF project, the app will be styled and rendered strictly **the same** on all platforms, using unified view sizes, docking, padding etc.

## Rationale

Xamarin.Forms has been great for consumer apps. For LoB apps it's a hard time.
LoB apps', especially in-company apps, have a very strong bias towards productivity and layout of apps vs. their design and graphics which are 2nd level priority.

You often need adaptive screens that can run both on mobile and laptops or tablets, and on any platform.

With this in mind, it doesn't always make sense to have the UI render differently per platform given the screen sizes are equal (thus requiring you to fine-tune it specifically to each platform).
The important feature would be adaptivity and responsiveness, not 'native look and feel'.

#### Difficulty
Intermediate

Related: #2415.

**Comment by rogihee** [comment]
Please take a look at #2415 and #2452, I think that will cover your wishes.

**Comment by weitzhandler** [comment]
@rogihee 
They're not. they are related but do something else. It's actually mentioned in my post.

**Comment by weitzhandler** [comment]
ping @Mike-EEE

**Comment by weitzhandler** [comment]
@rogihee 
They're not. they are related but do something else. It was actually mentioned in my post.

@Mike-EEE ping

**Comment by pmoorelegistek** [comment]
I agree with this goal but I don't think it requires any changes to the core Xamarin Forms project. Using custom renderers you could accomplish this on your own. Just pick a theme - Material Design, Fluent, whatever - and run with it.

**Comment by weitzhandler** [comment]
> Just pick a theme - Material Design, Fluent, whatever - and run with it.

Pick? from where? I'm asking for official embracement here.

**Comment by pmoorelegistek** [comment]
Maybe I'm not sure what you're asking for exactly. Do you want MS to design a brand new uniform app look and feel and program it into the Xamarin Forms platforms? Why can't you do this on your own?

**Comment by weitzhandler** [comment]
I'm asking Xamarin to provide a theme that makes a Xamarin.Forms app render equally on all devices.

**Comment by MelbourneDeveloper** [comment]
I think you're missing the point of the Xamarin.Forms library. It's not intended to look exactly the same on all platforms. Silverlight was an attempt to create a graphics engine that has pixel for pixel graphics rendering on all supported platforms. It basically achieved that. Xamarin.Forms is a library that allows for native apps to be created for multiple platforms with their native look and feel, control behaviour, transitions, and so on. However, there are multiple projects underway including Avalonia (https://github.com/AvaloniaUI/Avalonia). WPF is also coming to .NET Core 3.0 and that may at some point in the future work on platforms other than Windows. 

You should also check this out. It is an implementation of UWP's rendering engine on wasm:
http://platform.uno/

**Comment by Mike-EEE** [comment]
> It's not intended to look exactly the same on all platforms

Indeed, it might have been intended as such, but what makes that the "right" way to render an application?  I think the ask here is more of an improvement in this thinking/assumption. 

I myself have always considered it a very short-sighted approach (not to mention _incredibly_ expensive).  UX paradigms don't last very long.  It seems like 5-6 years.  Looking at a WinForms or WPF app, each look dated these days in their own respects.  iOS/Droid have been in the lead for about that range of time now and are starting to look and feel a little stale in their own right.

Great UX is great UX.  It doesn't need to be tied to a platform, look, or feel.  The web demonstrates this plainly.

**Comment by weitzhandler** [comment]
> I think you're missing the point of the Xamarin.Forms library.

I know very well what native look and feel. Have you read my post? Native look and feel is not always ideal. For instance, in LoB apps for example, or other non-consumer productivity apps.
So I'm asking Xamarin to provide a means to turn a Xamarin app into an equally rendered app, not via graphics/drawing, but rather by theming etc.

**Comment by pmoorelegistek** [comment]
Again I agree with the sentiment of having apps with common UX across all platforms. But there are multiple ways to achieve that. 

Way 1 is to make custom renderers for each platform that render the controls with the look you want. You'd still be using the native platform's framework for the actual rendering but you could customize the look to your heart's content. And you could do this now without any changes to Xamarin Forms. 

Way 2, which may be what is being suggested, would be to have totally loiokless controls and have all the rendering logic done in the cross platform layer. The individual platforms would merely provide a means of drawing primitives and receiving user input. This is what WPF does, wrapping Direct3D, and UWP does, wrapping DirectionConposition. 

For better or worse Xamarin Forms uses way 1. Other projects like Avalonia, use way 2. I suspect way 1 was employed with XF originally back in the day because doing all UI rendering in managed code on mobile devices might have been infeasible at the time. Not entirely sure though. Regardless, dependency on the native platform for control rendering seems pretty deeply embedded into XF, not merely philosophically but also architecturally. Asking them to move to a single renderer system at this point would I suspect be a non starter. 

But way 1 is still perfectly viable and I'm not sure why someone who wanted a common UX for all platforms couldn't achieve this in a matter of weeks if not days.

**Comment by weitzhandler** [comment]
@pmoorelegistek @Mike-EEE 

Not quite. What I'm asking Xamarin is for a theme and perhaps additional functionality that will be dressed upon the current XF that will ensure all controls are styled and measured the same in all platforms.

**Comment by jassmith** [comment]
Im sorry I dont see how MaterialShell + DrawingSpec don't handle this?

MaterialShell (not Shell, MaterialShell) will use the Drawing spec to produce consisten cross-platform UI.

**Comment by jassmith** [comment]
@weitzhandler 

> Have you read my post? I know very well what native look and feel is. Native look and feel is not always ideal. For instance, in LoB apps for example, or other non-consumer productivity apps.
So I'm asking Xamarin to provide a means to turn a Xamarin app into an equally rendered app, not via graphics/drawing, but rather by theming etc.

Yes this is what MaterialShell does. Yes it does it by drawing, but of course it does, how else would we get the buttons to look the exact same everywhere. The idea is MaterialShell provides default templates which do the drawing and thus everything looks the same for all controls inside a MaterialShell (in particular they look Material Design).

**Comment by jassmith** [comment]
Please feel free to leave comments on those specs if you feel they dont address your concerns.

**Comment by weitzhandler** [comment]
In my earlier [comment](https://github.com/xamarin/Xamarin.Forms/issues/2721#issuecomment-389357847) I said:

>@rogihee
>Please take a look at #2415 and #2452, I think that will cover your wishes.
>They're not. they are related but do something else. It was actually mentioned in my post.

After reading your response @jassmith looks like I'm the one who misunderstood MaterialShell. Now that's truly amazing, and I'm so glad it's coming to Xamarin! For me, this is a clear game changer.
Native look and feel took too much of development time having to fine-tune all the controls to each platform.
What it doesn't target tho, is adaptive design, see my other issue #2723.

**Comment by weitzhandler** [comment]
In my earlier [comment](https://github.com/xamarin/Xamarin.Forms/issues/2721#issuecomment-389357847) I said:

>@rogihee
>Please take a look at #2415 and #2452, I think that will cover your wishes.
>They're not. they are related but do something else. It was actually mentioned in my post.

After reading your response @jassmith looks like I'm the one who misunderstood MaterialShell. Now that's truly amazing, and I'm so glad it's coming to Xamarin! For me, this is a clear game changer.
Native look and feel took too much of development time having to fine-tune all the controls to each platform.
I thought MaterialShell only provides outer navigation, and preset **layout**, and I'm so glad it also comes to target style. I'd encourage you to emphasize it in your post #2415, would be good to make a TL;DR section or title on top that summarizes its contents.
So thank you XF guys for the hard work, and sorry @rogihee for being harsh.

What it doesn't target tho, is adaptive design, see my other issue #2723.

**Comment by rogihee** [comment]
Good to hear @weitzhandler, I was also a bit confused by the word "Shell" myself, and what it meant precisely. No worries!

**Comment by pmoorelegistek** [comment]
Wow I didn't know about this either. Looks like a big step in the "lookless" direction. Very glad to see this!

**Comment by pmoorelegistek** [comment]
@Mike-EEE
'It does make me wonder though, if XF acquires WebAssembly support, which platform will it render?"

Blazor I assume? I've been tempted to experiment with this when I can find some time. Should be attainable right now though and I'd be shocked if TPTB aren't quietly working on this.

**Comment by Mike-EEE** [comment]
Ah @pmoorelegistek by "platform" I meant "platform theme" sorry for the confusion there. It would indeed be rendered via WebAssembly, but what will it _look_ like?  All platforms to date each have their own theme/look/feel as we have been discussing, but the web doesn't.  So... how will it look?  Sounds like there's a whole lot more in the works here so it's not something to worry about, IMO.

**Comment by Mike-EEE** [comment]
Indeed @pmoorelegistek as I said, great UX is great UX.  It has no boundaries and can neither be constrained nor contained.  This is also how innovation carries forward, without imposed or imagined limits.

**Comment by jassmith** [comment]
No chance you guys would want to help stand up material theme drawings once I got the vertical slice done?

**Comment by pmoorelegistek** [comment]
@jasmith count me in!

**Comment by weitzhandler** [comment]
@jassmith I'll be happy.

**Comment by weitzhandler** [comment]
>@legistek commented on [May 17]:(https://github.com/xamarin/Xamarin.Forms/issues/2721#issuecomment-389849444)
Blazor I assume?

I reckon Blazor wouldn't be the choice as it's not really a rendering engine.
