### ISSUE TITLE
[Suggestion] View order support (ability to place view on top/back)

### ISSUE THREAD

**Issue by weitzhandler** [xamarin/Xamarin.Forms#2722]
## Title
Please implement a means to determine on overlapping controls which of them appears on top.

### Description
In WPF/UWP and also in the web, we can use [ZIndex] or [zindex](https://www.w3.org/wiki/CSS/Properties/z-index) respectively, to set up the order of the controls on the screen. Please implement this propery on Xamarin.Forms as well.

### Implementation 

Add an attached property for `View` that allows setting its `ZIndex`. Alternatively, add a set of methods or behaviors that allows bringing a control to front or moving them to the back.

<ListView Layout.ZIndex="2"/>

or

myView.BringToFront();

#### Android
[bringToFront](https://developer.android.com/reference/android/view/View#bringtofront)

#### UWP
[Canvas.ZIndex](https://msdn.microsoft.com/pt-pt/library/windows.ui.xaml.controls.canvas.zindex.aspx) attached property.

#### iOS
[zPosition](https://developer.apple.com/documentation/quartzcore/calayer/1410884-zposition)

### Difficulty
Easy

**Comment by StephaneDelcroix** [comment]
currently z-index is somehow supported by the order of the Children elements. but there's no guarantee...

**Comment by weitzhandler** [comment]
Yes, but changing the order after rendering doesn't bring the view on top.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
