### ISSUE TITLE
[Enhancement] Add multi-touch support to TapGestureRecognizer

### ISSUE THREAD

**Issue by mattrichnz** [xamarin/Xamarin.Forms#2726]
## Summary
Add multi-touch support to the the existing `TapGestureRecognizer`. While multiple taps are supported, only a single touch point can be tracked. This would add support to detect the difference between a single-finger tap, two-finger tap etc.

I am happy to contribute a PR for this as we already have these built for iOS, Android and UWP.
Happy to accept additional contributions for Tizen, GTK, MacOS etc.

## API Changes
One new bindable property:

    /// <summary>
    /// Gets or sets the number of touches required.
    /// </summary>
    public int NumberOfTouchesRequired
    {
        get { return (int)GetValue(NumberOfTouchesRequiredProperty); }
        set { SetValue(NumberOfTouchesRequiredProperty, value); }
    }

## Intended Use Case
Able to detect and respond to a single tap, multi-finger tap as separate commands/events.
E.g. Useful for natural gesture interaction in the UI, media playback etc.

**Comment by mattrichnz** [comment]
@pauldipietro @samhouts This is very simple on iOS/MacOS but a bit trickier on Droid and UWP.
Would _both_ a single-tap and double-tap need to support multi-touch?

Note: On UWP, this would mean we would need to modify the handling path for tap and double tap events using a `Windows.UI.Input.GestureRecognizer` instead of subscribing to the SDK-provided `Tapped` and `DoubleTapped` events on the container.

**Comment by PureWeen** [comment]
new home
https://github.com/xamarin/Xamarin.Forms/issues/3494
