### ISSUE TITLE
iphone 5 UseSafeArea issue

### ISSUE THREAD

**Issue by Ajaysinh4377** [xamarin/Xamarin.Forms#2733]
### Description
I am facing toolbar content overlapping issue before, and after adding following a line of code resolve issue for iPhone X, iPhone 6s plus etc. but not resolve for iPhone 5

`On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);`

### Screenshots

![iphonesissue](https://user-images.githubusercontent.com/35361721/40101888-78d1d26c-5906-11e8-8ccb-287973bb7a33.jpg)

**Comment by pauldipietro** [comment]
Could you possibly upload a reproduction? What version is this occurring on?

**Comment by Ajaysinh4377** [comment]
Model Name :-  iPhone 5
Version :- 10.3.3

**Comment by PureWeen** [comment]
SafeAreaInsets are iOS 11 only
