### ISSUE TITLE
Xamarin forms Listview DataTemplate inside Picker not working in iOS working fine in Android

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#2739]
### Description
Xamarin forms Listview DataTemplate not working in iOS working fine in Android

### Steps to Reproduce

1. Create any Xamarin forms project with Listview and inside the Listview you have to add Picker and assing the ItemsSource
2. 
3. 

### Expected Behavior
It should show UI
### Actual Behavior
Nothing is happen blank
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

![Uploading Screenshot_20180516-171706.png…]()

**Comment by pauldipietro** [comment]
Defining a basic item template with the source manually set on the cell's picker appears to work for me. How are you assigning the ItemsSource? Can you attach a reproduction and more information about what version you're experiencing this issue on?

(Note: The attached screenshot does not work)

**Comment by jitendrajadav** [comment]
Hi @pauldipietro thank you for updating me I have found my problem it is working fine thank you.
