### ISSUE TITLE
[Android] System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.PageContainer from native handle

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#2740]
### Description

Just one of the many manifestations of this issue:
https://stackoverflow.com/questions/10593022/monodroid-error-when-calling-constructor-of-custom-view-twodscrollview/10603714#10603714
https://bugzilla.xamarin.com/show_bug.cgi?id=40692

This time the class in question is Xamarin.Forms.Platform.Android.PageContainer

### Steps to Reproduce

Not sure if you need one. Unless PageContainer must not need a (IntPtr, JniHandleOwnership) constructor in which case I can try to create one.

### Expected Behavior
Exception is not thrown inside framework. App does not crash.

### Actual Behavior
App crashes. Exception can't be handled in user code.

### Basic Information

- Version with issue: XF 3.0 stable.
- Last known good version: 2.5 (possibly).
- IDE: VS2017
- Platform Target Frameworks:
  - Android: 8.1

### Stack Trace
```

05-16 15:12:40.209 I/MonoDroid( 8220): UNHANDLED EXCEPTION:
05-16 15:12:40.238 I/MonoDroid( 8220): System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.PageContainer from native handle 0x19 (key_handle 0xe9edc19). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.PageContainer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
05-16 15:12:40.238 I/MonoDroid( 8220):    --- End of inner exception stack trace ---
05-16 15:12:40.238 I/MonoDroid( 8220):   at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.238 I/MonoDroid( 8220):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.238 I/MonoDroid( 8220):    --- End of inner exception stack trace ---
05-16 15:12:40.238 I/MonoDroid( 8220):   at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.238 I/MonoDroid( 8220):   at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Android.Views.View.get_Parent () [0x0001f] in <25661073a35344a89f215a4cf81af37c>:0 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Xamarin.Forms.Platform.Android.ViewExtensions.RemoveFromParent (Android.Views.View view) [0x00004] in D:\a\1\s\Xamarin.Forms.Platform.Android\ViewExtensions.cs:25 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnDestroyView () [0x0002c] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:71 
05-16 15:12:40.239 I/MonoDroid( 8220):   at Android.Support.V4.App.Fragment.n_OnDestroyView (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <3682f8af23a748128467fbf9c57ae876>:0 
05-16 15:12:40.239 I/MonoDroid( 8220):   at (wrapper dynamic-method) System.Object.0657e64b-01ca-491f-b914-ea4443b1ecc1(intptr,intptr)
```

**Comment by PureWeen** [comment]
@duzenko  a reproduction would be nice to see how you are interacting with the app to cause this. This error usually comes about because of not properly disposed elements. The adding of the constructor is a workaround that sometimes works but usually just hides the issue or causes more

**Comment by duzenko** [comment]
Here you go
[xp.zip](https://github.com/xamarin/Xamarin.Forms/files/2035452/xp.zip)

**Comment by PureWeen** [comment]
@duzenko  thank you

It looks like there is a timing issue with the pop and then swapping out the Detail Page
I put a basic 
```C#

			await Task.Delay(200);
```
And then the error no longers occurs

Either way thank you for the repro

**Comment by EmilAlipiev** [comment]
> @duzenko thank you
> 
> It looks like there is a timing issue with the pop and then swapping out the Detail Page
> I put a basic
> 
> ```cs
> 			await Task.Delay(200);
> ```
> 
> And then the error no longers occurs
> 
> Either way thank you for the repro

i had same problem using 3.4 version. it causes when i pop a modalpage with data and read this data on other page and load it. this throws exactly this exception. when i am debugging step by step, exception doesnt occur. it seems like it happens too fast. i have feeling that page behind in stack appears faster than page pops. if i insert task.delay like you suggested error is gone. it looks like a bug in xamarin forms  recent versions. it never happened before.
