### ISSUE TITLE
Unable to load DLL e_sqlite3

### ISSUE THREAD

**Issue by wjvii** [xamarin/Xamarin.Forms#2744]
When trying to run a Xamarin Forms WPF that includes a SQLite database it errors with

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at TestUsingSQLite.MainPage..ctor() in C:\Temp\TestUsingSQLite\TestUsingSQLite\MainPage.xaml.cs:line 19
   at TestUsingSQLite.App..ctor() in C:\Temp\TestUsingSQLite\TestUsingSQLite\App.xaml.cs:line 14
   at TestUsingSQLite.WPF.MainWindow..ctor() in C:\Temp\TestUsingSQLite\TestUsingSQLite.WPF\MainWindow.xaml.cs:line 30

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### Steps to Reproduce

1. Create a Xamarin Cross Platform application
2. Add the WPF project per online instructions https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf 
3. Add reference to Microsoft.Data.Sqlite

### Expected Behavior
Did not expect to get a sqlite3 error. Tried adding a number of different nuget packages that had SQLite components but none resolved the issue.

### Actual Behavior
Got an unable to load dll error

### Basic Information

- Version with issue: XamarinForms.Platform.WPF v3.1.0.469394-pre1
- Last known good version: NA
- IDE: Visual Studio Enterprise 15.7.1
- Platform Target Frameworks: WPF
- Nuget Packages: Microsoft.Data.Sqlite, NETStandard.Library, Xamarin.Forms, Xamarin.Forms.Platform.WPF.
[TestUsingSQLite.zip](https://github.com/xamarin/Xamarin.Forms/files/2009778/TestUsingSQLite.zip)

- Affected Devices:

**Comment by PureWeen** [comment]
If you create an empty WPF project and add the Microsoft.Data.Sqlite nuget package do you get the same error? Does this only come up once you mix in XF?

**Comment by wjvii** [comment]
Only when Xamarin Forms WPF is involved.

**Comment by PureWeen** [comment]
@wjvii  try installing the Microsoft.Data.Sqlite package into the WPF project as well

once i did that your sample ran fine. My guess is that the *Microsoft.Data.Sqlite* package or one of the dependent packages isn't setup quite right so it's not correctly being applied into the WPF project if the package is only installed into the netstandard project

**Comment by PureWeen** [comment]
Hmm I'm not sure .. .I ran that project you attached there and for me it runs fine. Is that project you attached failing for you? 

Have you googled around about that error by chance?

https://github.com/ericsink/SQLitePCL.raw/issues/161
I've seen a number of different issues pop up about that error and usually it's just the wrong library being referenced or something similar with architecture type mismatches

**Comment by wjvii** [comment]
Yes, exact same project. I figure a picture is worth a thousand words so I will include the video of what happens for me. If it is working for you maybe it is just some simple change I need to make on my end in order to get it to run. I am on Windows 1803 and using VS 2017 15.7.1 Enterprise Edition.

[2018-05-18_150755.zip](https://github.com/xamarin/Xamarin.Forms/files/2019375/2018-05-18_150755.zip)
