### ISSUE TITLE
TimePicker ignores FontSize setting on android

### ISSUE THREAD

**Issue by universaldata-eu** [xamarin/Xamarin.Forms#2745]
### Description
the TimePicker view control ignores the FontSize property in android. ios behaviour is as expected.
### Steps to Reproduce

1. create a new Mobile App (Xamarin.Forms), named TimePickerTest, select Blank App and .NET Standard
2. In the MainPage.xaml paste the following code:

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TimePickerTest"
             x:Class="TimePickerTest.MainPage">
    <StackLayout Orientation="Vertical">
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="24"/>
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="16"/>
        <TimePicker HorizontalOptions="Center" VerticalOptions="Center" />
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="24"/>
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" FontSize="16"/>
        <DatePicker HorizontalOptions="Center" VerticalOptions="Center" />
    </StackLayout>
</ContentPage>
```

3. start the project with android

### Expected Behavior
the timepicker controls should have different font sizes.
the datepicker controls should have different font sizes.

### Actual Behavior
the timepicker controls have all the same font size.
the datepicker controls should have different font sizes.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.482510
- Last known good version: -
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 27.0.3
- Affected Devices: emulator, acer iconia

### Screenshots

![image](https://user-images.githubusercontent.com/39343748/40130513-8ab32982-5937-11e8-8bee-2345e0e6c025.png)

**Comment by pauldipietro** [comment]
Tested the behavior against a Nougat emulator where it occurs

**Comment by universaldata-eu** [comment]
tested with Xamarin.Forms 3.1.0.583944
bug NOT solved. with testproject still same behaviour.
