### ISSUE TITLE
UWP - Subclassing NavigationPage causes crashes - SetResult on Completed Task

### ISSUE THREAD

**Issue by FrancoisM** [xamarin/Xamarin.Forms#2747]
In my xamarin forms app, I subclassed `NavigationPage`. Then I add instances of my subsclass as children of a `MultiPage`.
No issue with iOS and Android but with UWP the following [line ](https://github.com/xamarin/Xamarin.Forms/blob/882bf07917bea57b93d0d9becd768dcab739c26f/Xamarin.Forms.Platform.UAP/PageControl.cs#L148)crashes.

Indeed, it seems the task is already completed. Could `SetResult `be replaced with `TrySetResult`?

**Comment by pauldipietro** [comment]
Could you please give us a reproduction sample? We also do suggest using the provided template for filing issues.

**Comment by FrancoisM** [comment]
Here is a [repro](https://github.com/FrancoisM/ReproUWPCrash).

**Comment by pauldipietro** [comment]
Thanks for the reproduction; I quickly ran it on Android and UWP, and only the latter crashes. Checked against 3.1-pre as well.

**Comment by FrancoisM** [comment]
While I don't understand what happened, and while I think it's always safer to use `TrySetResult `rather than `SetResult`, I managed to avoid the crash by setting `MainPage `after constructing the `MultiPage `that it is set to. I updated the [repo ](https://github.com/FrancoisM/ReproUWPCrash)accordingly.
