### ISSUE TITLE
Gesture is not recognized for custom view in Xamarin.Forms.macOS platform

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#2750]
### Description
We have created a simple **CustomView** derived from **Grid** and wrote the renderer for it in **macOS** platform as like following code example. And loaded a **ScrollView** as it's child element and the ScrollView's content as **StackLayout**. And we have added a **tap gesture recognizer** to the **StackLayout** to detect whether the gesture is recognized or not.

**Issue:** 
If we set the custom **NSView** to our custom view in the renderer as SetNativeControl, the tap gesture call back for the **StackLayout** is not raised.

### Code Snippet

**Forms View:**

**XAML Page**

`public partial class MainPage : ContentPage
	{

		CustomGridView customGridView;
		ScrollView scrollView;
		StackLayout stacklayout;

		public MainPage()
		{
			InitializeComponent();
			InitiailzeCustomView();
		}

		private void InitiailzeCustomView()
		{
			customGridView = new CustomGridView();
			scrollView = new ScrollView();
			stacklayout = new StackLayout();

			var tap = new TapGestureRecognizer();
			tap.Tapped += Tap_Tapped; ;

			for (int i = 0; i < 10; i++)
			{

				var stack = new StackLayout();
				var label = new Label();
				label.FontSize = 20;
				label.TextColor = Color.Teal;
				label.HorizontalTextAlignment = TextAlignment.Center;
				label.VerticalTextAlignment = TextAlignment.Center;
				label.Text = "Label : " + i;
				stack.Children.Add(label);
				stacklayout.Children.Add(stack);
			}

			stacklayout.GestureRecognizers.Add(tap);

			scrollView.Content = stacklayout;
			customGridView.Children.Add(scrollView);

			this.Content = customGridView;
		}

		private void Tap_Tapped(object sender, EventArgs e)
		{
			DisplayAlert("Alert!", "Tapped event is raised", "OK");
		}
	}`

**CustomView:**
`public class CustomGridView : Grid
    {
        public CustomGridView()
        {
        }
    }`

**macOS renderer**
`[assembly: ExportRenderer(typeof(CustomGridView), typeof(CustomGridViewRenderer))]
namespace BasicCustomView.macOS
{
	public class CustomGridViewRenderer : ViewRenderer<CustomGridView, CustomNSView>
    {

		CustomNSView CustomNSView;

        public CustomGridViewRenderer()
        {
			
        }

		protected override void OnElementChanged(ElementChangedEventArgs<CustomGridView> e)
		{
			base.OnElementChanged(e);
			if(e.NewElement != null)
			{
				CustomNSView = new CustomNSView();
				this.SetNativeControl(CustomNSView);
			}
		}
	}

	public class CustomNSView : NSView
	{
		public CustomNSView()
		{
			
		}
	}
}
`

### Steps to Reproduce

1.  Run the attached sample in **macOS** platform
2.  Tap the view and note that Tapped event in the MainPage.Xaml.cs is not triggered.
3.  Comment the **SetNativeControl** code snippet in the renderer project and perform the step 1. Now, the gesture event is raised.

### Expected Behavior
Gesture event should recognize in all aspects.

### Actual Behavior
Gesture event is not recognized.

### Basic Information

- Version with issue: Xamarin.Forms version - **3.0.0.446417**
- Last known good version: **NA**
Visual Studio Community 2017 for Mac
Version 7.5 (build 1254)
Installation UUID: 64fc755c-9a4c-485d-ac0e-16d265955d7a
Runtime:
    Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)
 
    Package version: 510010047
 
NuGet
Version: 4.3.1.4445
 
.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    2.0.5
    2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
    2.1.4
    2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks
 
Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
 
Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/syncfusion/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        4.3    (API level 18)
        4.4    (API level 19)
        4.4.87 (API level 20)
        5.0    (API level 21)
        5.1    (API level 22)
        6.0    (API level 23)
        7.0    (API level 24)
        7.1    (API level 25)
 
SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26 rc1
SDK Build Tools Version: 26 rc1
 
Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
 
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
Apple Developer Tools
Xcode 9.0 (13247)
Build 9A235
 
Xamarin.Mac
Version: 4.4.1.176 (Visual Studio Community)
 
Xamarin.iOS
Version: 11.10.1.177 (Visual Studio Community)
Hash: 7e782c1e
Branch: d15-7
Build date: 2018-04-25 15:27:13-0400
 
Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1
 
Build Information
Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7
 
Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

### Reproduction Link
[BasicCustomView.zip](https://github.com/xamarin/Xamarin.Forms/files/2011964/BasicCustomView.zip)

Please let us know if you require further assistance to replicate the issue.

Regards,
Dinesh Babu Yadav

**Comment by DineshBabuYadav** [comment]
Can you provide any workaround for this?

**Comment by pauldipietro** [comment]
@rmarinho may know more about this

**Comment by DineshBabuYadav** [comment]
@rmarinho , Additionally, 

If we write the renderer for StackLayout (derived as a custom view) in native renderer project as like below code example and added the **NSClickGestureRecognizer**, the tapped event is still not raised.

**Code Example:**

**Forms View:**

```
public class StackView : StackLayout
{

}

```

**macOS View:**

```
[assembly: ExportRenderer(typeof(StackView), typeof(StackViewRenderer))]
namespace BasicView.macOS
public class StackViewRenderer : VisualElementRenderer<StackView>
{

   private NSClickGestureRecognizer tapGestureRecognizer;

   protected override void OnElementChanged(ElementChangedEventArgs<StackView> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null)
            {
                 tapGestureRecognizer = new NSClickGestureRecognizer();
                 tapGestureRecognizer.AddTarget(() =>
                 {
                     OnTapped();
                 });
                 tapGestureRecognizer.DelaysPrimaryMouseButtonEvents = false;
                 this.AddGestureRecognizer(tapGestureRecognizer);
            }

            private void OnTapped()
           {
                //Not raised
           }
}
```

Please let me know if you require further assistance on replicating the issue.

Regards,
Dinesh Babu Yadav

**Comment by DineshBabuYadav** [comment]
any update on this?

**Comment by AndreiMisiukevich** [comment]
@DineshBabuYadav hi, try to Use **ClickGestureRecognizer** for Mac/Tizen instead (Check Device.RuntimePlatform)

**Comment by taksh35** [comment]
Hello Dineshbabu can you please help regarding image tap gesture on xamarin forms mac.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
