### ISSUE TITLE
[Binding] use DefaultValue on failed type conversion

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#2753]
When a binding value can not be converted to the target type, the binding system do nothing (log a message) instead fo defaulting to the property `DefaultValue` (or, with #2742, the FallbackValue)

**Comment by charlesroddie** [comment]
From a non-xaml user this seems wrong. Such code shouldn't compile, and if it compiles it shouldn't run, and allowing it to both compile and run hurts the process of detecting and fixing bugs. But perhaps xaml users think differently.

**Comment by StephaneDelcroix** [comment]
@charlesroddie bindings are not typed, and we (most of the time) have no way to infer the type of the value at compile time.

This duck-typing capability is very convenient as a binding could apply, e.g., on any type that has a `Name` property, or on types deserialized from a son query.

If you want strict typing, you can enable binding compilation, and you'll get more errors at compile-time.

**Comment by StephaneDelcroix** [comment]
BadIdea(™)
