### ISSUE TITLE
Add xml docs to Children.Add(view, left, right, top, bottom) for grids

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#2754]
Children.Add(View view, int left, int right, int top, int bottom) for a Grid doesn't behave as most people would expect: right and bottom are non-inclusive.

Can we add the following comments to the documentation:
/// <param name="right">The rightmost column number + 1 </param>
/// <param name="bottom">The bottom row number + 1 </param>

This could go in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Grid.cs , line 309.

It's a tiny edit but I'm posting an issue as I don't know if it's OK to put comments there: I can't find xml documentation elsewhere in the file or in similar files.

**Comment by charlesroddie** [comment]
https://forums.xamarin.com/discussion/21950/set-column-span-by-using-grid-children-add-from-source-code

**Comment by StephaneDelcroix** [comment]
we don't do xml doc, we document the code in a separate process, then include the documentation in the nuget before packaging.

the doc for `Children.Add()` can be found here: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.grid.igridlist-1.add?view=xamarin-forms

it should show up in your intellisense...

**Comment by charlesroddie** [comment]
@StephaneDelcroix Thanks for the list. Who can fix that documentation?

Currently none of the descriptions there are correct.

left
The left edge of the column span. Must be greater than **or equal to** 0.

right
The right edge of the column span **plus 1**. Must be greater than left.

top
The top edge of the row span. Must be greater than **or equal to** 0.

bottom
The bottom edge of the row span **plus 1**. Must be greater than top.
