### ISSUE TITLE
[Xaml] parsing too permissive

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#2756]
According to https://developercommunity.visualstudio.com/content/problem/252490/error-in-xamarin-stringformat-intellisense.html, this xaml snippet

```xaml
<ToolbarItem Text="{Binding Path=StartTime, StringFormat='{0:yy-MM-dd}'}" />
```

is correctly parsed even though the opening curly brace is not escaped. I suspect the single-quotes wrapping the string format are respsonsible for this.

this should throw an exception, as `0:yy-MM-dd` is probably not a valid markup extension.

**Comment by samhouts** [comment]
Reverting the fix for this issue pending further discussion.
