### ISSUE TITLE
Add printing support and XAML to PDF converter

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#2770]
### Description
I am developing Xamarin forms application where I want printing functionality for e.g.  Invoice I can generate in XAML now this XAML I have to print and share via PDF how would I can do?

I have tried several way like HTML to PDF and PDFSharp but no hope PDFSharp is only support in .Net Standard 1 my project is .Net Standard 2 and HTML will giving so many erorr like 

sample code of HTML to PDF is here where I am not able to find webpage
`
if (webpage == null)
            webpage = new Android.Webkit.WebView(GetApplicationContext());

        int width = 2102;
        int height = 2973;

        webpage.Layout(0, 0, width, height);
        webpage.LoadDataWithBaseURL("",html, "text/html", "UTF-8" , null);
        webpage.SetWebViewClient(new WebViewCallBack(file.ToString()));
` 
In that case **webpage** I am not able to find?

please find below link:

[](https://stackoverflow.com/questions/37340813/xamarin-free-html-or-doc-to-pdf-conversion)
[](https://github.com/akgulebubekir/PDFSharp.Xamarin.Forms)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
This doesn't appear to be the proper place for a question like this, as we use issues for proposals and bug reports; general API usage questions would probably be better suited for a place like StackOverflow. If there is an actual bug in Forms, please upload a reproduction so we can investigate it.
