### ISSUE TITLE
Upgrading to Xamarin forms 3.0 breaks intellisense.

### ISSUE THREAD

**Issue by kfuller002** [xamarin/Xamarin.Forms#2774]
### Description
I have a project where intellisense works fine for .xaml files, but if i upgrade xamarin forms from 2.5.1.444934 to anything 3.0 or higher it stops working, rolling back changes solves the problem.  This only breaks for .xaml, .cs files work fine.  I also tried some brand new projects, shared project works fine on 3.0 but .net standard intellisense doesn't work even on a new project.

I am also using the latest version of resharper.

### Steps to Reproduce

1. Create new project: Visual C#, Cross-Platform, Mobile App (Xamarin.Forms), Blank App, .NET Standard
2. Open MainPage.xaml in the .NET Standard 2.0 project.
3. Try adding a new control or property and I get no intellisense at all.

### Expected Behavior
Updating an existing project to 3.0 or higher, or creating a new project, I would expect intellisense to work for .xaml files.
### Actual Behavior
Intellisense does not work for xaml files.
### Basic Information
I also use resharper if that could be effecting things, version: 2018.1 (most recent)
- Version with issue:
- Last known good version:
Xamarin forms 2.5.1.444934

All default versions below:

- IDE: Visual Studio 2017 15.7.1
- Platform Target Frameworks: 
  - iOS:   11.10 
  - Android: 8.3  
  - UWP:  10.0 Build 16299 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by davidortinau** [comment]
It's Resharper based on other confirmed reports we've seen. Please disable Resharper or install their patched version which I believe may now be available.

**Comment by BenoistLUGNIER** [comment]
At first, be sure that the "open with" option for xaml file is set to "Source Code (text) Editor"

upgrading to XF 3.0.0.482510 seems to fix the intellisense problem
If you have resharper, set xaml intellisense to Visual Studio not to Resharper
