### ISSUE TITLE
[Intellisense] Resources from MergedWith and ResourceDictionary.MergedDictionaries are not displayed in Intellisense

### ISSUE THREAD

**Issue by YGuerin** [xamarin/Xamarin.Forms#2776]
### Description

In VS, 15.7.1, Resources from MergedWith and ResourceDictionary.MergedDictionaries are not displayed in Intellisense 

### Steps to Reproduce

1. Create a first dictionary Dictionary1 with one resource Resource1
2. Create a second dictionary Dictionary2 with one resource Resource2
3. Create a resource Resource3 in App.xaml
4. In App.xaml :
- Refer Dictionary1 with ResourceDictionary.MergedWith
- Refer Dictionary2 with ResourceDictionary.MergedDictionaries
5. In MainPage.xaml, use Intellisense to find previous resources as a StaticResource

### Expected Behavior
All resources are displayed with Intellisense 

### Actual Behavior
Only resources in App.xaml are displayed

### Basic Information

- Version with issue: XF 3.0.0.482510
- Last known good version: -
- IDE: Visual Studio 15.7.1
- Platform Target Frameworks: 
  - iOS:  11.10.1.177
  - Android: 8.3.0.19

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/2019036/App2.zip)

**Comment by PureWeen** [comment]
I also tested this on 15.8.0 Preview 1.1 and it has the same issue

**Comment by mgoertz-msft** [comment]
Thank you. We have an active bug in VS to track this problem.

**Comment by YGuerin** [comment]
@mgoertz-msft Does the active bug appears on developercommunity.visualstudio.com ? Can you link it if it's the case ? Thanks you

**Comment by mgoertz-msft** [comment]
@YGuerin  No, I simply created a bug in our database for this issue directly. Feel free though to create a VS feedback ticket which I would be able to link to our internal bug.

**Comment by StephaneDelcroix** [comment]
bug is handled upstream. closing
