### ISSUE TITLE
[GTK] ControlGallery.Gtk: VisualStateManager validation example does not recover "non-error" state

### ISSUE THREAD

**Issue by atsushieno** [xamarin/Xamarin.Forms#2778]
Run ControlGallery.Gtk (I verified on Mac but would be applicable to anywhere) and open "VisualStateManager" Gallery, choose "Validation Example" and try some invalid inputs e.g.

1. send without Subject. It will change textbox background color as red. And even after you enter valid subject, it won't go back to the right state.
2. enter Message more than 40 characters. The background color becomes red, but even after you remove some characters so that the message besomes <40 chars, it still remains red.

Both work just fine on Android.

### Basic Information

- Version with issue: 882bf07
- IDE: VSMac 7.6 preview (build 711)

### Screenshots

![screen shot 2018-05-19 at 16 21 34](https://user-images.githubusercontent.com/53929/40266131-be595de2-5b80-11e8-8386-b49a3cac42a2.png)

**Comment by jsuarezruiz** [comment]
Thanks for the detailed description. I'll check what happens.
