### ISSUE TITLE
Entry HorizontalTextAlignment not working Android XF3.0

### ISSUE THREAD

**Issue by Umar3x** [xamarin/Xamarin.Forms#2780]
### Description
Only on ANDROID. 
On last XF 3.0.0.482510, seems entries got a regression. Setting       
HorizontalTextAlignment = TextAlignment.Center does not work anymore and the text is align left anyway in an entry. 

### Steps to Reproduce

1. Create a simple entry
     _entry = new Entry
            {
                Keyboard = Keyboard.Numeric,
                HorizontalOptions = LayoutOptions.FillAndExpand,
                HorizontalTextAlignment = TextAlignment.Center,
                Placeholder = "PlaceHolder"
            };

### Expected Behavior
Should center input text in an entry when set to Center. Was the case on 2.5 and before. 

### Actual Behavior

The entry on Android does not take the TextAlignment.Center and so the input text is align left.

### Basic Information

- Version with issue:
- Last known good version: on XF 2.5.0.122203
- IDE: VS 15.6.5
- Platform Target Frameworks:  .NET standard Android 8.0 & iOS 10>
 - iOS:  iOS 10 and above 
 - Android:  API 26 Android 8.0 --> 
- Nuget Packages: XF & XFM 3.0 
- Affected Devices: Honor 9, Honor 8, Samsung A5 2016, Moto G2, BlackView

**Comment by pauldipietro** [comment]
#2167
