### ISSUE TITLE
[Android] IOnCameraMoveListener can not be found on Android.Gms.Maps.GoogleMap class

### ISSUE THREAD

**Issue by ygorats** [xamarin/Xamarin.Forms#2781]
### Description
After installing a newer version of Xamarin (hoping that Forms Previewer works), I couldn't compile my project, it throws an error related to 

> Reference to type 'GoogleMap.IOnCameraMoveListener' claims it is defined in 'Xamarin.GooglePlayServices.Maps', but it could not be found ...

### Steps to Reproduce

1. Install Xamarin for Visual Studio 4.5.0.476.
2. Try to compile a project that uses MapRenderer class.

### Actual Behavior
It seems that the interface name has changed or something like.
See screenshots

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: 7.0 
- Android Support Library Version: 27.0.2
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/5714320/40270177-f9489f84-5b5e-11e8-9666-a347695aa0d8.png)

**Comment by PureWeen** [comment]
Can you attach a repro please? 

2 things
- I created a quick test project for myself and it worked for me
- I'm pretty sure Android 7.0 isn't compatible with support libraries 27.0.2 so that might be the core of your problems

**Comment by ygorats** [comment]
I found that the problem was the target version of the project, thank you for the support anyway an sorry for anything.
