### ISSUE TITLE
When Entry's Keyboard type is given as Numeric "," has been disabled in Samsung S8 devices.

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/Xamarin.Forms#2786]
### Description
We have used the Entry and when Keyboard type is given as Numeric, "," has been disabled in Samsung S8 devices.

### Expected Behavior
In Samsung s8 device, "," should be enabled.

### Actual Behavior
 In Samsung s8 device, "," has been disabled.

### Basic Information

- Version with issue: 3.0.0.482510
   
- Affected Devices: Samsung S8 Device Version 8.0.0

### Screenshots

[Screenshot_20180521-150922.jpg.zip](https://github.com/xamarin/Xamarin.Forms/files/2022075/Screenshot_20180521-150922.jpg.zip)

**Comment by olezhko** [comment]
I have same problem with lg g5. 
it depend on decimal separator. when i change phone language from russian to english, decimal separator become enabled.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/1898

**Comment by h4rdc0d3** [comment]
I have the same problem with Samsung Galaxy S7 Edge, Spanish language.

**Comment by brux88** [comment]
are there news?

**Comment by AntRemo** [comment]
Same question. Tried to workaround for a few days with no success :(

**Comment by mknotzer** [comment]
Any news? For us this issue is a show stopper. We can't migrate to Xamarin Forms 3.

**Comment by AntRemo** [comment]
Hi @samhouts 
If this issue is closed, would these comments appear on anyone's radar?
Thanks

**Comment by mknotzer** [comment]
Check out https://github.com/xamarin/Xamarin.Forms/issues/1898

**Comment by samhouts** [comment]
Duplicate of #1898

**Comment by olezhko** [comment]
Somebody check in Xamarin.Forms 4.4.0. This fix not work now!
