### ISSUE TITLE
HorizontalTextAlignment doens't work with Entry when setting IsPassword=true

### ISSUE THREAD

**Issue by mustafashaban** [xamarin/Xamarin.Forms#2794]
### Description
After upgrading to XF 3.0 I noticed many issues in text alignment behavior 
I solved most of them by changing the **HorizontalTextAlignment** from Start to End or opposite
but this issue that couldn't be solved for me **(while it was working before upgrading)**
when I set the IsPassword property to True the text will always be on the left, no chance to move it to right
Note, I am using the Arabic language, I tried with the FlowDirection but also not working

### Steps to Reproduce

1. Add Entry
2. Set IsPassword=True
3. Try changing HorizontalTextAlignment, no change

### Expected Behavior
change the alignment from right to left or opposite 

### Actual Behavior
no change at all
### Basic Information

- Version with issue:
- Last known good version: 2.5.1
- IDE:
- Platform Target Frameworks:
  - iOS:  didn't test
  - Android: 7.1
  - UWP:  didn't test 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/21288236/40344396-4596ce3e-5d9d-11e8-9ec2-d250396882bb.png)

**Comment by PureWeen** [comment]
@mustafashaban this should be fixed by this  upcoming PR
https://github.com/xamarin/Xamarin.Forms/pull/2743

If that doesn't look like it will fix your issue please let me know
