### ISSUE TITLE
Color RGB constructor does not work

### ISSUE THREAD

**Issue by garie** [xamarin/Xamarin.Forms#2799]
### Description

Creating a color as `new Color(r, g, b)` does not work as expected - the color is instead equivalent to `White`. According to the documentation, 

> The `Xamarin.Forms.Color.FromRgb` method is striclty equivalent to `new Color (r, g, b)`

However, it is simple to see that this is not the case. This occurs on both iOS and Android.

### Steps to Reproduce

```
System.Diagnostics.Debug.WriteLine("Constructor: " + (new Color(74, 74, 74)));
System.Diagnostics.Debug.WriteLine("FromRgb: " + Color.FromRgb(74, 74, 74));
System.Diagnostics.Debug.WriteLine("FromHex: " + Color.FromHex("#4a4a4a"));
```

### Expected Behavior

This should print the same output for all three.

### Actual Behavior

```
Constructor: [Color: A=1, R=1, G=1, B=1, Hue=0, Saturation=0, Luminosity=1]
FromRgb: RGB: [Color: A=1, R=0.290196090936661, G=0.290196090936661, B=0.290196090936661, Hue=0, Saturation=0, Luminosity=0.290196090936661]
FromHex: [Color: A=1, R=0.290196090936661, G=0.290196090936661, B=0.290196090936661, Hue=0, Saturation=0, Luminosity=0.290196090936661]
```

As you can see, creating a `new Color(74, 74, 74)` is not equivalent to `Color.FromRgb(74, 74, 74)`.

### Basic Information

- Version with issue: 2.5.0.280555
- Last known good version:
- IDE: Visual Studio for Mac Community 7.4.3 (build 10)
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: 8.1
  - UWP: Did not test
- Android Support Library Version: API 26
- Nuget Packages:
- Affected Devices: I checked iPhone X and Nexus 5X simulators.

**Comment by programmation** [comment]
@garie The R/G/B values in the constructor are fractions.

The correct call for the constructor is 

```System.Diagnostics.Debug.WriteLine("Constructor: " + (new Color(74.0/255.0, 74.0/255.0, 74.0/255.0)));```

**Comment by StephaneDelcroix** [comment]
@garie the constructor takes values from 0-1. see https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.color.-ctor?view=xamarin-forms

you can use `Color.FromRgb()`

**Comment by powerdude** [comment]
Wouldn't it make sense for constructor to throw an exception if values are not 0-1?
