### ISSUE TITLE
Android: ShowAlert returns Task which never completes when Activity is destroyed

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#2801]
### Description

Page.ShowAlert and other similar methods on Page return Task.
On Android, the Task never returns when Activity is destroyed.
This can be seen easily by using Developer options and have the option to recreate the activity when navigating away from it.
Android even gives a warning in logcat that the app leaks the Activity.

This issue was described in 2014 in the Xamarin Forms forum: https://forums.xamarin.com/discussion/18010/dialogs-leaking-memory-on-android

### Steps to Reproduce

```
class MainPage : Page
{ 
   public MainPage()
  {
       Do();
  }
  
  async void Do() {
      await ShowAlert("A", "B", "Cancel");  // This will never return even when Activity is recreated
  }
}
```

### Expected Behavior

Task should complete (or maybe throw TaskCanceledException?)

### Actual Behavior

Task never completes.

### More info 

The TaskCompletionSource used [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/AlertArguments.cs#L15) in AlertArguments class should be cancelled when Activity is destroyed or recreated such that code returns.
The Page.DisplayAlert returns the Task of the TaskCompletionSource [here ](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Page.cs#L149)

```
public Task<bool> DisplayAlert(string title, string message, string accept, string cancel)
{
	if (string.IsNullOrEmpty(cancel))
		throw new ArgumentNullException("cancel");

	var args = new AlertArguments(title, message, accept, cancel);a
	MessagingCenter.Send(this, AlertSignalName, args);
	return args.Result.Task;
}
```

The TaskCompletionSource has result set [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/PopupManager.cs#L116) however in the case when Activity is destroyed or recreated, nor a result nor an exception is thrown to somehow tell the client awaiting on the ShowAlert to continue.

I think a partial solution is that in PopupRequestHelper:Dispose [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/PopupManager.cs#L56)  to have a way to cancel all the active TaskCompletionSource's.

I think this can apply to other kinds of dialogs\popups as well and I think there's a similar problem on UWP and iOS too.

**Comment by andreinitescu** [comment]
There's two bad things which happen here: Task never returning and Activity leaking because of AlertDialog not exiting.
AlertDialog is used in PopupRequestHelper, PickerRenderer and TimePickerRenderer. All these leak the Activity when it gets re-created without closing the dialog.

**Comment by andreinitescu** [comment]
What does the "inactive" tag mean?

**Comment by knocte** [comment]
Your `Steps to Reproduce` include an `async void` method. Does the bug still happen if you use `async Task` instead?

**Comment by andreinitescu** [comment]
Yes, it doesn't matter

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
