### ISSUE TITLE
[GTK] State of GTKEntry widget changes to 'insensitive' when user types in text.

### ISSUE THREAD

**Issue by sf-ica** [xamarin/Xamarin.Forms#2810]
### Description

When the user tries to replace the text of an entry widget the state changes to 'insensitive'. No text can be entered.

### Steps to Reproduce

1. Create a new page with an entry widget.
2. Define the "Placeholder" and "Text" properties.
3. Start the application.
4. Select the entry's text (this should be the default behaviour if the entry is the first or only widget on the page).
5. Type in some characters (don't delete the text with backspace or delete key).

### Expected Behavior

The entered letters should appear and the state of the entry shouldn't change.

### Actual Behavior

Only the first entered letter appears, then the state changes to 'insensitive'.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0
- Last known good version: ---
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  -GTK: 2.12
- Affected Devices: Windows 10 PC, Raspbery Pi with Raspbian 9.4 & Mono 5.12.0.226.

### Screenshots
![bug](https://user-images.githubusercontent.com/39555596/40420967-662302c4-5e8a-11e8-96ab-b178709d5f17.png)

### Example code

SimplePage.xaml

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="App2.SimplePage">
    <ContentPage.Content>
      <StackLayout>
         <Entry Placeholder="I destroy things!" Text="Don't overwrite me!"></Entry>
      </StackLayout>
    </ContentPage.Content>
</ContentPage>

```

SimplePage.xaml.cs

```
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace App2
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	public partial class SimplePage : ContentPage
	{
      public SimplePage()
		{
			InitializeComponent();
		}
	}
}
```

Code Repro
```C#
new ContentPage()
			{
				Content = new StackLayout(){
					Children = {
						new Entry(){
							Placeholder = "I destroy things!",
							Text = "Don't overwrite me!"
						}
					}
				}
			};
```

**Comment by jsuarezruiz** [comment]
Thanks for the detailed description. I'll check what happens.

**Comment by jsuarezruiz** [comment]
[PR ](https://github.com/xamarin/Xamarin.Forms/pull/2915) sent.
![2810-issue](https://user-images.githubusercontent.com/6755973/40886544-3cfcde20-673a-11e8-80b8-8511cfdbcda1.gif)
