### ISSUE TITLE
When upgrading nuget (to XF3) receive "This collection is read only"  VS2017

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#2812]
### Description
Same issue as reported in this bugzilla:
https://bugzilla.xamarin.com/show_bug.cgi?id=61113

VS2017 - Trying to upgrade a really simple basic starter app from XamForms2.5 to 3.0.  Some packages updated, some don't.  For example `Xamarin.Android.Support.Core.Utils` won't install with Visual Studio error pane reporting "This collection is read-only."

![image](https://user-images.githubusercontent.com/11351506/40440031-c718a5a2-5e8a-11e8-829e-b5dc445f5ecc.png)

### Steps to Reproduce

1.  Simple project that is XamForms 2.5
2. Try to update to XamForms 3.0
3. or - try to update all of the existing nugets in the project - some succeed some fail.

### Expected Behavior
To actually be able to upgrade Xamarin without it always being a nightmare

### Actual Behavior
Nightmare

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@tlhintoq  do you have more info about the type of project 2.5 is or can you include your Simple project (pack ref, pcl, etc....)?

 I haven't seen this issue and I upgrade up and down between 2.5 and 3.0 a few times a week

Also I'm curious what version of Visual Studio you are on

**Comment by activa** [comment]
This was fixed in Visual Studio 15.7.2 (which was released this week)

See also https://github.com/NuGet/Home/issues/6468

**Comment by PureWeen** [comment]
Closing for now. @tlhintoq  hopefully the nightmare is over
