### ISSUE TITLE
[UWP] Moving items around in an Observable Collection on UWP causes the list view to scroll down 

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2813]
### Description

On UWP if you have a ListView bound to an ObservableCollection then move elements around
```C#
dataElements.Move(0, 2);
```

it will cause the list view to scroll down

### Steps to Reproduce
Just ran the sample. It moves items around on a timer and you'll see it scroll down after the first move. It does not scroll down like this on iOS and Android

### Expected Behavior
Scroll position of list view shouldn't change

### Actual Behavior
Scroll position of list view changes

### Basic Information

- Version with issue: 3.0
- UWP:  16299 

### Reproduction Link
[ListViewObservableCOllection.zip](https://github.com/xamarin/Xamarin.Forms/files/2032481/ListViewObservableCOllection.zip)

**Comment by paymicro** [comment]
This seems to be the normal behavior of UWP
A clean UWP project behaves the same way.
Screencast: http://recordit.co/5aJh4unnno

**Comment by StephaneDelcroix** [comment]
closing per @paymicro comment
