### ISSUE TITLE
[UWP] set isvisiable to false crashes the app

### ISSUE THREAD

**Issue by jaykainlabs** [xamarin/Xamarin.Forms#2814]
### Description
Just run the sample app, and it crashes after updating the Xamarin Forms to the latest
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/2032813/App1.zip)

### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
The search bar to be invisiable
### Actual Behavior
the app crashes
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
duplicate of https://github.com/xamarin/Xamarin.Forms/issues/2633
