### ISSUE TITLE
[Enhancement] Bindable AutomationId

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#2819]
# Description
I'm not sure why not more people are running into this. We are developing apps using xamarin.forms and use UI testing via AppCenter. Some of our pages use templated controls like a listview to show a list of items. However, we have no way of setting a unique automationid for the items in the datatemplate, because the automationid property is not bindable. This causes us to not be able to identify individual items during UI testing.

According to this uservoice:
https://xamarin.uservoice.com/forums/144858-xamarin-platform-suggestions/suggestions/13865469-make-automationid-a-bindableproperty-in-xamarin-fo
the feature was planned in 2016, but it seems it was never implemented

**Comment by PureWeen** [comment]
One way to work around is add an event to the BindingContext changed of whatever element and then set it there from the code behind

```C#
		private void Label_BindingContextChanged(object sender, EventArgs e)
		{
			Label label = sender as Label;
			if (label.BindingContext != null)
				label.AutomationId = (label.BindingContext as SomeView).Property.ToString();
		}
```

**Comment by bruzkovsky** [comment]
Some platforms allow this property to be set only once (I think it was iOS). You need to check the value of AutomationId beforehand:
```C#
private void Label_BindingContextChanged(object sender, EventArgs e)
{
    Label label = sender as Label;
    if (label.BindingContext is SomeViewModel vm && label.AutomationId == null)
        label.AutomationId = vm.Property.ToString();
}
```

**Comment by brianhager** [comment]
I tried this approach with buttons and it works well when you only have one screen worth of buttons. Problem is, the buttons are within a scroll view and when you scroll the screen, the same buttons are reused for the next set of buttons that will be shown on the screen and the need to reset the AutomationIds for the buttons for the next set when scrolling is needed. Problem is, you can't set AutomationIds more then once. They have already been set for the first "scroll page""

`        private void SetIsNotDownloadedAutomationId(object sender, EventArgs e)
        {
            Button button = sender as Button;
            button.AutomationId = null;
            if (button?.BindingContext != null && button.AutomationId == null)
                button.AutomationId = (button.BindingContext as StateToManageDisplay).StateName;
        }`

**Comment by PaulVrugt** [comment]
I think this can be closed in favor of https://github.com/xamarin/Xamarin.Forms/issues/3845 , which is apparently currently being implemented
