### ISSUE TITLE
SetGrow And SetBasis not working inside OnAppearing

### ISSUE THREAD

**Issue by steffenSuess** [xamarin/Xamarin.Forms#2821]
### Description
The methods "FlexLayout.SetGrow" and "FlexLayout.SetBasis" do not work as expected when they are placed inside the "OnAppearing"-Method of a Page. The size of the lowest segment in the FlaxLayout can not be set. It always works well inside the constructor. See Screenshots.

### Basic Information

- Version with issue: Xamarin.Forms (3.0.0.482510)
- Last known good version: -
- IDE: Visual Studio Community 2017 for Mac 7.5
- Platform Target Frameworks: 
  - iOS:  11.3
  - Android: Not Tested 
  - UWP:  Not Tested

### Screenshots

![xaml](https://user-images.githubusercontent.com/24249476/40478509-829d75c8-5f49-11e8-8964-26091667eec8.png)
![constructor](https://user-images.githubusercontent.com/24249476/40478522-8e10d0e4-5f49-11e8-83cd-05ed9e285f9d.png)
![simulator screen shot - iphone x - 2018-05-24 at 11 39 48](https://user-images.githubusercontent.com/24249476/40478527-9425a68a-5f49-11e8-8a9d-8536c245b60e.png)
![onappearing](https://user-images.githubusercontent.com/24249476/40478536-98983bf6-5f49-11e8-9cb5-7e344dc6cd9e.png)
![simulator screen shot - iphone x - 2018-05-24 at 11 38 56](https://user-images.githubusercontent.com/24249476/40478540-9d941382-5f49-11e8-9966-760b8f8b7aff.png)

**Comment by StephaneDelcroix** [comment]
currently verifying that layout is invalidated on changes of grow/shrink values

**Comment by StephaneDelcroix** [comment]
the order in which the propertyChanged event and the propertyChanged are fired are such that the Invalidation happens (with the event) before the flexitem values are actually changed (by the delegate)
