### ISSUE TITLE
[UWP] SearchBar.IsSpellCheckEnabled platform-specific doesn't work.

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#2822]
### Description

The `SearchBar.IsSpellCheckEnabled` platform-specific on UWP, newly released in Xamarin.Forms 3.0, does nothing. [This page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.isspellcheckenabled#Windows_UI_Xaml_Controls_TextBox_IsSpellCheckEnableduwp) suggests I should be receiving spell check and auto correction.

### Steps to Reproduce

1. Run the ControlGallery.WindowsUniversal project from the Xamarin.Forms repo.
2. In the app, browse to issue 1691_2.

### Expected Behavior

Spell checking should be enabled in the first `SearchBar`.

### Actual Behavior

Spell checking isn't enabled in the first `SearchBar` (or any of the `SearchBar` instances).

### Basic Information

- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  Build 17134 (version 1803)
- Nuget Packages: 3.0.0.482510 (if consuming via NuGet, rather than using the controls gallery project)

### Screenshots

![spellcheck](https://user-images.githubusercontent.com/8092460/40483479-093e0d9e-5f50-11e8-8ef6-65c640c6d50f.PNG)

### Reproduction Link

Controls Gallery project in Xamarin.Forms repo (I can supply a different repo case if required).

**Comment by PureWeen** [comment]
> Run the ControlGallery.WindowsUniversal project from the Xamarin.Forms repo.
are you running from master? or are you running the 3.0 gallery

I'm not seeing what you're seeing 

![image](https://user-images.githubusercontent.com/5375137/40501786-1cbf684a-5f46-11e8-8100-2751da784619.png)

The only behavior that I did see is that it seems like "Enable spellcheck" doesn't get applied retroactively. So in the SearchBar if you type misspelled words then enable spell check doesn't recheck what's been typed. But for me spell check is working

**Comment by pauldipietro** [comment]
Is the global setting disabled? I'm not sure if this would have an effect but it'd be worth checking in the Settings app.

![capture](https://user-images.githubusercontent.com/1251024/40502111-fa850d86-5f57-11e8-8a99-e17585760f5e.PNG)

**Comment by davidbritch** [comment]
My settings were as above but still no red squiggles for mis-spellings. I turned the above settings off, and back on again and suddenly the platform-specific sprang into life. Must be a Windows bug.

Thanks guys.
