### ISSUE TITLE
[UWP] InputView.DetectReadingOrderFromContent doesn't work

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#2823]
### Description

The `InputView.DetectReadingOrderFromContent` and `Label.DetectReadingOrderFromContent` platform-specific on UWP, newly released in Xamarin.Forms 3.0, don't seem to work. [This page](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.textreadingorder) suggests that switching between using the defined flow direction, and detecting the reading order from the content should yield a different layout.

### Steps to Reproduce

1. Run the ControlGallery.WindowsUniversal project from the Xamarin.Forms repo.
2. In the app, browse to issue 1717.

### Expected Behavior

Toggling between using the flow direction and detecting the reading order from the content should yield a difference.

### Actual Behavior

Toggling between using the flow direction and detecting the reading order from the content yields no difference.

### Basic Information

- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  Build 17134 (version 1803)
- Nuget Packages: 3.0.0.482510 (if consuming via NuGet, rather than using the controls gallery project)

### Screenshots

Using flow direction:

![02uwp](https://user-images.githubusercontent.com/8092460/40483838-56313454-5f51-11e8-8d74-e35151f16b37.PNG)

Detecting the reading order from the content:

![03uwp](https://user-images.githubusercontent.com/8092460/40483848-5d8576f2-5f51-11e8-8885-8aca97e3be98.PNG)

### Reproduction Link

ControlGallery.WindowsUniversal project in the Xamarin.Forms repo. Alternatively, I can supply a different sample if required.

**Comment by PureWeen** [comment]
If I'm understanding the MSDN article correctly and @hartez 's comment from the original ticket that's expected behavior

https://github.com/xamarin/Xamarin.Forms/issues/1717#issuecomment-363606637
> Unlike FlowDirection and its logic, the reading order logic for DetectFromContent will not affect the alignment of the text within the text control, it just adjusts the order in which blocks of bidirectional text are laid out.

When running the Issue 1717 UI test you can see the period switch sides as you change it to detect from content

I debugged the code as well and it's definitely setting the native control to
> Control.TextReadingOrder = TextReadingOrder.DetectFromContent;
