### ISSUE TITLE
[MacOS] Xamarin.Forms Global Style not persistently working

### ISSUE THREAD

**Issue by isesco** [xamarin/Xamarin.Forms#2824]
### Description
There is an issue with Xamarin.Forms Global Style not persistently working within a Xamarin Mac app. The problem occurs when opening a new window. The first time the window is loaded, the Styling is loaded as well. If you close the new window and open it again, Visual Studio throws an exception -Xamarin.Forms.Xaml.XamlParseException: Position 6:20. StaticResource not found for key staticLabelStyle

### Steps to Reproduce
1. Create a button that opens a new window.
2. When the new window is open for the first time, the style loads fine.
3. Close the new window, click button to open a new window again, exception is thrown.
[XamFormsPlayground-2.zip](https://github.com/xamarin/Xamarin.Forms/files/2194286/XamFormsPlayground-2.zip)

### Expected Behavior
The style should be loaded every time a new window is open.

### Actual Behavior
The style is only visible when the window is first loaded. An exception is thrown when closing and reopening the window.

### Basic Information

- Version with issue: **3.0.0.482510**
- Last known good version: **N/A**
- IDE: **VisualStudio for Mac 7.5 (build 1254)**

**Comment by isesco** [comment]
Hi Shane,

I have attached the sample app to this email. This sample should allow you to repro the issue.

Thank you,

﻿ --
Isaac Escobar Quezada

v-isesco@microsoft.com<mailto:v-isesco@microsoft.com>

[Microsoft]
If you have any feedback about my work, please let either me or my manager Nam Su Kang know at nkang@microsoft.com<mailto:nkang@microsoft.com>

**Comment by samhouts** [comment]
@isesco Do you have a sample project you can share? Thanks!

**Comment by jvansickle** [comment]
@samhouts I believe I have come across this same issue as @isesco in the past. Please see https://github.com/jvansickle/Xamarin.Forms_macOS_GS macOS project in the solution for an example.

**Comment by PureWeen** [comment]
[XamFormsPlayground-2.zip](https://github.com/xamarin/Xamarin.Forms/files/2194284/XamFormsPlayground-2.zip)

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
