### ISSUE TITLE
[Enhancement] Creating a bindable property with enum backing does not select enum default

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#2826]
### Description
When I create a bindable property for an enum, I have to explicitly set a default value in the Bindable.Create() method for that enum otherwise a runtime error will occur. Why is that? In my opinion, by default, the first member of an enum type should be chosen by the Create() method. See attached.

This issue seems to exist for structs as well. For example, if you create a bindable property for `TimeSpan`, you need to explicitly do `new TimeSpan()` or `default(TimeSpan)` while in reality a `TimeSpan` defaults to "00:00:00".

### Reproduction Link

[Demo.zip](https://github.com/xamarin/Xamarin.Forms/files/2036585/Demo.zip)

**Comment by charlesroddie** [comment]
If there is going to be a default, it should be explicit. Placing a value first in an enum does not implly that it is intended to be a default. No need to make bindings even more hacky than they are already.

**Comment by adrianknight89** [comment]
I should have been clear about default enum values. You're right that the first enumeration isn't always the default one. Here's an example:

```
enum MyEnum
{
      A = 1,
      B = 0,
      C = 2
}
```

`default(MyEnum)` would return `B`.

Official [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties) for bindable properties mentions the following for the `defaultValue` parameter of `Create()`:

> Providing a default property value that's different from the default for the type of the property.

which, to me, implies that `Create()` is supposed to set the property to its default if `defaultValue` is not provided.

I'd say the documentation should make it clear that for enums and structs, an explicit initialization must be provided or the `Create()` method should be modified to define defaults.

**Comment by activa** [comment]
The documentation is wrong. The default value is of type object and the default is null. When the property type is a value type, the code is trying to cast null to a value type and of course that throws an exception.

So either the code needs to change so it uses default(T) in case the default value is null, or the documentation should make it clear that the provided default value should be something that can be casted the property type.

**Comment by activa** [comment]
Fixing the code to do what the documentation says looks pretty easy.

Adding this to the BindableProperty constructor should do it:
```
if (ReturnType.IsValueType && Nullable.GetUnderlyingType(ReturnType) == null && DefaultValue == null)
    DefaultValue = Activator.CreateInstance(ReturnType);
```

**Comment by activa** [comment]
See PR #2827
