### ISSUE TITLE
[IOS] label not rendering in BOLD when using a STYLE, Droid however works

### ISSUE THREAD

**Issue by raymondjstone** [xamarin/Xamarin.Forms#2831]
### Description

Label titleLabel = new Label
            {
                Text = title,
                //BackgroundColor = Color.Transparent,
                BackgroundColor = Color.White,
                WidthRequest = (Constants.DeviceWidth * 0.85) - 30,
                Style = Device.Styles.ListItemDetailTextStyle,
                HorizontalTextAlignment = TextAlignment.Center,
                FontAttributes = FontAttributes.Bold,
                TextColor = Color.Black
            };

in IOS does not render in bold but does in Android

### Steps to Reproduce

1. add label to a content page

### Expected Behavior

Both Droid and IOS should render text in bold

I believe that this only started to happen when I moved from a named size of font to a style (which I require to do for accessibility reasons).

### Actual Behavior

Droid renders text in bold, IOS does not

### Basic Information

- Version with issue: 30.0
- Last known good version: none, 2.5 had issue as well
- IDE: Visual Studio 15.7.2
- Platform Target Frameworks: 
  - iOS:  11.10.1.178
  - Android: 8.3.0.19
  - UWP:  N/A 
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

**Comment by jameslavery** [comment]
Could this be related to Xcode versions? See my post on the forum here:

https://forums.xamarin.com/discussion/128330/xcode-9-4-1-seems-to-break-styles-on-ios#latest

**Comment by raymondjstone** [comment]
The issue predates the Xcode version that is causing you issues and seems more related to the rendering process used by Xamarin. My guess is that the length of space needed by a label is being calculated as if the accessibility text is visible. No styles are affected and no control other than label so not relate to styles at all as far as I can see (and I use styles extensively in the app for accessibility reasons)

**Comment by toussam** [comment]
Just met the issue while developing a new feature. I noticed that this last one was reported last may. Did you guys decided to debug it in a near future ? Thank you in advance for everything !

**Comment by breyed** [comment]
It also works on UWP and WPF. Just not iOS.

**Comment by toussam** [comment]
Hi @samhouts ,

Since the issue has been fixed, could you tell me in which version it will be release ? (or at least the expected one) I looked at the 3.5.0 Service Release 1 and it was not listed into it.

I thank you in advance for your time and your response !
Best regards,
