### ISSUE TITLE
ResourceProvider Exception in Xamarin.Forms 3.0 due to Signature Change

### ISSUE THREAD

**Issue by LanceMcCarthy** [xamarin/Xamarin.Forms#2835]
### Description

Due to the change made in https://github.com/xamarin/Xamarin.Forms/pull/1976 for Xamarin.Forms 3.0, ResourceDictionaries that were compiled with XF 2.4 fail to load throwing the following exception:

**Can't resolve the reference 'System.Func`2<System.String,System.String> Xamarin.Forms.Internals.ResourceLoader::get_ResourceProvider()', referenced from the method 'System.Void TheExternalResourceDictionary::InitializeComponent()' in 'Xamarin.Forms.Core**

In particular, the ResourceDictionary in this case contains the styles for custom Xamarin.Forms controls that have a minimum support Xamarin.Forms version of 2.4

## Steps to Reproduce

Download the simple repro using the link at the bottom of this post. Let me walk you through the two solutions:

1. **CustomControls** - A simple class library with the ResourceDictionary
2. **ResLoaderRepro** - The Xamarin.Forms runtime app that present the problem

![image](https://user-images.githubusercontent.com/3520532/40567303-c21b87ae-6042-11e8-8ea1-8e378ac04df7.png)

### 1- CustomControls.sln (aka CoolGrid)

This is very simple class library that contains one class, `CoolGrid`, that inherits from `Xamarin.Forms.Grid`. 

```
public class CoolGrid : Xamarin.Forms.Grid
    {
        public CoolGrid()
        {
            this.Resources = new CoolGridTheme();
        }
    }
```

The ResourceDictionary, "CoolGridTheme.xaml", is also very simple and contains a couple `OnPlatform` for height and a Style to set CoolGrid's `BackgroundColor`

```
<OnPlatform x:TypeArguments="x:Double" x:Key="Height" Default="32">
    <On Platform="Android" Value="45"/>
    <On Platform="iOS" Value="36"/>
    <On Platform="UWP" Value="32"/>
</OnPlatform>
<OnPlatform x:TypeArguments="x:Double" x:Key="MinimumHeight" Default="33">
    <On Platform="Android" Value="28"/>
    <On Platform="iOS" Value="28"/>
    <On Platform="UWP" Value="33"/>
</OnPlatform>
    
<Style x:Key="BaseCoolGridStyle" TargetType="customControls:CoolGrid">
    <Setter Property="HeightRequest" Value="{StaticResource Height}"/>
    <Setter Property="MinimumHeightRequest" Value="{StaticResource MinimumHeight}"/>
    <Setter Property="BackgroundColor" Value="DarkGray"/>
</Style>
```

The compiled result was copied to the Libs folder in the 2nd solution's folder.

### 2 - ResLoaderRepro.sln

This solution contains the Xamarin.Forms 3.0 projects (_created using the **File > New > Xamarin.Forms app > Blank App** template and only kept Android to keep it small_). 

I updated the XF NuGet page to the latest public release and added the reference to the CustomControls assembly in the Libs folder.

Finally, on MainPage, I add a single instance of CoolGrid:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:customControls="clr-namespace:CustomControls;assembly=CustomControls"
             x:Class="ResLoaderRepro.MainPage">
    
    <StackLayout>
        <customControls:CoolGrid x:Name="MyCoolGrid" HeightRequest="100" WidthRequest="100"/>
    </StackLayout>
</ContentPage>
```

Here's a screenshot to better explain the simplicity of the setup:

![image](https://user-images.githubusercontent.com/3520532/40566522-1ca1cc3c-603f-11e8-8bb0-5034bec816d4.png)

## Expected Behavior

The `CoolGrid` control will render.

## Actual Behavior

An exception is thrown (see scrrenshot 4 below

**System.MissingMethodException: System.Func`2<string, string> Xamarin.Forms.Internals.ResourceLoader.get_ResourceProvider()**

Here's a screenshot of the break:

![image](https://user-images.githubusercontent.com/3520532/40566182-86e233fe-603d-11e8-9ded-41088d3add79.png)

## Basic Information

- Version with issue:
- Last known good version: v2.5.1.527436
- IDE: VS2017 15.7.2
- Platform Target Frameworks: All
- Android Support Library Version: 23.3+
- Nuget Packages: XF 3.0+

## Screenshots

Screenshots inline with the explanation above.

## Reproduction Link

[Download the reproducible from here (3.1 MB)](https://progresssoftware-my.sharepoint.com/:u:/g/personal/mccarthy_progress_com/EXTatEGac0ZOo15fmHCktJ4BS10QdS60nWEh_aIkODGAjw?e=VxAC05)

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-macios/issues/3639

**Comment by Szymaniuk** [comment]
Any chance for quick fix? It's blocking me from updating my app to any Xamarin.Forms greater than **2.5.1.527436**...

**Comment by StephaneDelcroix** [comment]
I'm literally investigating this right now, but still can't tell if we'll be able to deliver a fix, nor can't I give you a time frame.

The workaround is to make sure all your dependencies are compiled against latest XF 3.0.0

**Comment by LanceMcCarthy** [comment]
I can confirm https://github.com/xamarin/Xamarin.Forms/pull/2880 fixes the problem in my tests (attached repro and commercial 3rd party libraries).

**Repro Screenshot (using new Xamarin.Forms package containing fix):**

![image](https://user-images.githubusercontent.com/3520532/40797211-5eacc07e-64d5-11e8-8da5-af9554af0466.png)

**Comment by StephaneDelcroix** [comment]
@LanceMcCarthy could you also confirm it works on iOS ? thanks

**Comment by LanceMcCarthy** [comment]
@StephaneDelcroix confirmed working on iOS 11.4, iPhone 8

![image](https://user-images.githubusercontent.com/3520532/40838792-a4fccd9c-656d-11e8-80c0-0ed90820959e.png)

**Comment by avintoptaros** [comment]
Hi @StephaneDelcroix , do you know when the next release will be with this fix? Thank you.

**Comment by stephanosio** [comment]
@avintoptaros It looks like the fix is already included in the release-3.0.0-sr3 and beta-3.1.0-pre3.

**Comment by avintoptaros** [comment]
@stephanosio I see that on the release page there is no release-3.0.0-sr3 version (https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.0/)

**Comment by stephanosio** [comment]
@avintoptaros Try this: https://github.com/xamarin/Xamarin.Forms/releases
