### ISSUE TITLE
[UWP] does not render Frame CornerRadius

### ISSUE THREAD

**Issue by varyamereon** [xamarin/Xamarin.Forms#2838]
### Description
UWP does not render Frame with CornerRadius, instead it reverts to square corners. Control is rendered correctly on iOS and Android. https://bugzilla.xamarin.com/show_bug.cgi?id=56914 refers.

### Steps to Reproduce

1. Add frame to Xamarin.Forms project.
2. Set corner radius > 0
3. Run project on UWP. Frame ignores corner radius property.

### Expected Behavior
Xamarin.Forms should render a UWP Border control with the background color set inside and corner radius set as appropriate.

### Actual Behavior
A Border control is rendered correctly but inside another element which shares the same background color, making the control appear like it has square edges.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0
- Last known good version: n/a
- IDE: Visual Studio 2017 15.7.2
- Platform Target Frameworks: 
  - UWP: 17134
- Affected Devices: Tested on Surface Book.

### Screenshots
![androidscreenshot](https://user-images.githubusercontent.com/29577046/40575508-0e84c6a0-60de-11e8-8248-e8787b08956b.png)
![uwpscreenshot](https://user-images.githubusercontent.com/29577046/40575548-dc11030e-60de-11e8-879c-4d522cdb254d.png)

### Reproduction Link
https://github.com/varyamereon/FrameIssue

**Comment by MartinZikmund** [comment]
May I take this one? @jassmith @varyamereon  @pauldipietro

**Comment by JTOne123** [comment]
Any ideas?

![image](https://user-images.githubusercontent.com/3457140/47265356-94b6fe80-d52f-11e8-8356-e719f1bea755.png)
