### ISSUE TITLE
Compiling .net standard dll's to .net native for Xamarin Forms

### ISSUE THREAD

**Issue by Pinox** [xamarin/Xamarin.Forms#2840]
My apologies for posting a question rather than filing an issue.

I currently have XF app and is reading about obfuscation off dll's in the release build. What I don't understand is why can't I build .net standard dll's using the .net native toolchain and then use these in Xamarin Forms.

UWP touts the .net native toolchain with massive increase in performance. 
          -Up to 60% performance improvement on cold startup times
          -Up to 40% performance improvement on warm startup times
          -Less memory consumption of your app when compiled natively

Why can't we have the same in Xamarin Forms .net standard dll's ?  Would this not be easy gains in performance for XF or is there a technical reason like Mono that prevents us from using this ?

**Comment by jassmith** [comment]
Mono would need to support native compiled .NET Native dlls. At the moment Xamarin.iOS already does AOT compilation (which is monos version of the same thing) and you can enable AOT compilation on Android.

**Comment by Pinox** [comment]
@jassmith  Thanks,  I did not know that for Android.  So when I enable AOT it will compile also the .net standard dll's to native code or does it only do native compilation on the main project ?

**Comment by jassmith** [comment]
it only does it on the main project
