### ISSUE TITLE
WPF: Image from stream doesn't work

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#2844]
### Description
When trying to using a byte array (which becomes a MemoryStream) as the source of an Image, the Image does not render.

### Steps to Reproduce

1. Load a byte array from a real image. 
2. Turn that byte array into a MemoryStream
3. Turn that into an ImageSource with ImageSource.FromStream(() => memStream)
4. Use that ImageSource on an Image control
5. Image control renders as blank

### Expected Behavior

Image control should render the original image the byte array came from

### Basic Information

I have already researched and fixed the problem, but since I am not experienced in WPF, I am not confident in my fix.  Therefore, I will show my fix here and you guys can put in the correct fix.

The problem is in the ImageRenderer for the WPF platform in the StreamImageSourceHandler class.  It does this:

				using (Stream stream = await ((IStreamImageSource)streamsource).GetStreamAsync(cancelationToken))
				{
					bitmapimage = new BitmapImage()
					{
						StreamSource = stream
					};
				}

I am guessing there are two things wrong here.  The first is that the using statement will GC the stream which we put inside the bitmapimage so the StreamSource of the bitmapimage becomes unusable after it leaves the using block.  The second thing wrong is that you can't just set the StreamSource.  You have to use BeginInit and EndInit (just like you already do for the UriImageSourceHandler in the same source file).  So my fix is the following:

                Stream stream = await ((IStreamImageSource)streamsource).GetStreamAsync(cancelationToken);
                bitmapimage = new BitmapImage();
                bitmapimage.BeginInit();
                bitmapimage.StreamSource = stream;
                bitmapimage.EndInit();

This fixes the rendering of the Image, but perhaps there is a memory leak with the Stream??  Please investigate and commit a proper fix.  Thanks.

**Comment by RogerHardiman** [comment]
I've just hit this exact same problem when porting an existing XF application to WPF.

**Comment by tlhintoq** [comment]
To WPF????
Do you mean the UWP project of your Xamarin.Forms solution?
Or are you really porting a Xamarin.Forms solution to Windows Presentation Foundation somehow?

**Comment by scastria** [comment]
Yes, WPF. Xamarin.Forms 3.0 added WPF support.

**Comment by RogerHardiman** [comment]
Wpf for me too

**Comment by peter0302** [comment]
The BitmapImage needs to be created with CacheOption.OnLoad:

https://msdn.microsoft.com/en-us/library/system.windows.media.imaging.bitmapimage.cacheoption(v=vs.110).aspx
