### ISSUE TITLE
Native Views in XAML sample doesn't work in iOS platform

### ISSUE THREAD

**Issue by ColeXm** [xamarin/Xamarin.Forms#2845]
All the sample in this [link](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml)  works fine in Android and UWP, but not work in iOS platform. The sample only show a blank page without any native control on it.

**Comment by davidortinau** [comment]
@ColeXm are you using 3.0.0? It was reported and fixed. A service release will be available for this soon.

https://github.com/xamarin/Xamarin.Forms/pull/2772

If that's not the case, please provide a small reproduction for your issue.

**Comment by ColeXm** [comment]
Yes, the sample in that link all are using  3.0.0, Thanks.
