### ISSUE TITLE
Intellisense can't recongize  'Resource.Dimension'  definition

### ISSUE THREAD

**Issue by aixiaozi** [xamarin/Xamarin.Forms#2846]
### Description

I created some 'Resource.Dimension'  resource but Visual Studio 2017 intellisense can't recongize it. Underline all dimension resources in my cs code with the error: 

     `Resource.Dimension` does not contain a definition for...

Intellisense offer me only standard dimensions properties.

### Steps to Reproduce

1. Create a blank Xamarin.Android project

2. Add dimens value in Resources\values\dimens.xml

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <dimen name="fab_margin">16dp</dimen>

  <dimen name="main_text_item_size">17dp</dimen>
</resources>

```

3. Use it in MainActivity:

```
var a = Resources.GetDimension(Resource.Dimension.fab_margin);
```
![a](https://user-images.githubusercontent.com/18043540/40608828-63110f90-629f-11e8-9f7c-f0fa9cc1cc92.PNG)

### Expected Behavior
Without intellisense error

### Actual Behavior
Has intellisense error but could run application without a problem and problem persists.

### Basic Information
- IDE: VS 2017 15.7.2
- Platform Target Frameworks: 
- Android: Android Target Version: 27
- Android Support Library Version: the latest version: 27.0.2

Tried clean solution, delete bin&obj folder, problem exists. And I could found `Resource.Dimension` resource in `Resource.Designer.cs` file:

![2](https://user-images.githubusercontent.com/18043540/40608779-39b759c4-629f-11e8-9a74-ffc2102d6d22.PNG)

### Screenshots
![a](https://user-images.githubusercontent.com/18043540/40608548-5f3983b2-629e-11e8-805a-d5f0750470f1.PNG)

**Comment by StephaneDelcroix** [comment]
I think this isn't a `Xamarin.Forms` issue...

/cc @mgoertz-msft

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-android#1796
