### ISSUE TITLE
System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by manishp-rapidd** [xamarin/Xamarin.Forms#2847]
Hi @StephaneDelcroix

https://github.com/xamarin/Xamarin.Forms/issues/2632

This issue still appears when i use ControlTemplate="{StaticResource MyTemplate}"

ex:
`<local:Gh2632Base xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
x:Class="Xamarin.Forms.Xaml.UnitTests.Gh2632"
xmlns:local="clr-namespace:Xamarin.Forms.Xaml.UnitTests"
ControlTemplate="{StaticResource MyTemplate}"
x:Name="Page">`

![image](https://user-images.githubusercontent.com/30525904/40612305-93fc4bea-6297-11e8-96fb-94b5cdf11223.png)

If I remove ControlTemplate="{StaticResource MyTemplate}" from my code, everything works as expected.

**Comment by StephaneDelcroix** [comment]
could you please:
- attach a reproduction project
- tell us on which version you have that issue.

thanks

**Comment by StephaneDelcroix** [comment]
The fix for #2632 isn't included yet in XF 3.0.0.482510. Please test the upcoming version, or the nuget here https://github.com/xamarin/Xamarin.Forms/releases/tag/release-3.0.0-sr2, and open a new issue if the problem persists
