### ISSUE TITLE
HorizontalTextAlignment property does not work

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#2850]
### Description
HorizontalTextAlignment property does not work

### Steps to Reproduce

            Entry entryQuantita = new Entry() { FontSize = 120, FontAttributes = FontAttributes.Bold, HorizontalTextAlignment = TextAlignment.Center, Keyboard = Keyboard.Numeric };

add this entry to a StackLayout. Alignment is left, not center 

### Expected Behavior
Entry center Aligned
### Actual Behavior
Entry left Aligned
### Basic Information

- Version with issue: 3.1.0.469394-pre1
- Last known good version: 2.5.1
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: Min version 4.3  Destination 8.1 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Datalogic DL-AXISTS

### Screenshots

![image](https://user-images.githubusercontent.com/5759350/40625545-7cf745aa-62b3-11e8-8842-ea3d86747df7.png)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/2167

**Comment by tmt242001** [comment]
Issue still exist in 3.0.0.530893

**Comment by tmt242001** [comment]
It Works now. Tested on 3.0.0.550146 (rebuild after deleting bin and obj folders)
