### ISSUE TITLE
Question: Enhanced ListView (build 2017)

### ISSUE THREAD

**Issue by ackava** [xamarin/Xamarin.Forms#2851]
Last year in build 2017, in some of the videos it was announced that Xamarin.Forms 3.0 will,

1. Support DataTemplate of type View instead of Cell, no more cells
2. Support adding Views directly into ListBox

I see that DataTemplate for ListBox still needs to be of type Cell, so these ideas were abandoned?

**Comment by jassmith** [comment]
ListView2 Spec should be coming soon. It's being actively worked on. You can track the spike progress if you want in the lv2spike branch.
