### ISSUE TITLE
Support UITableViewStyle.Grouped for ListView on iOS

### ISSUE THREAD

**Issue by xamoulin** [xamarin/Xamarin.Forms#2852]
### Description

It would be great that the UITableView under the ListView could be initialized with UITableViewStyle.Grouped. Something like the Intent property of TableView.

**Comment by xamoulin** [comment]
It would be realy nice if it could be done soon, because it's the only thing that prevent me from using ListView instead of TableView.

**Comment by jfversluis** [comment]
I'm pretty sure this won't be happening anymore 😅  and not sure if this is a feasible candidate for .NET MAUI, but if you think it is, make sure to open something there!
