### ISSUE TITLE
SelectedItem does not fire when binded

### ISSUE THREAD

**Issue by D4rkC1own187** [xamarin/Xamarin.Forms#2856]
### Description
ItemSelected binding does not work. ItemSelected is bind in XAML.
### Steps to Reproduce
Binded SelectedItem in view model.
For test purpose, I call SelectedItem when the "Add" button is click.

Run test project. In "Browse" page click "Add" button. Nothing happens.

In ItemPage.xaml.cs: 
Line 43: you will see I'm declaring an object to SelectedRow.

Line 46: works if you declare object to listview's SelectedItem.

1. 
Bind SelectedItem in XAML
2. 
Initialize SelectedItem with any item in list view source
3. 
Nothing happens.

### Expected Behavior
SelectedItem should highlight the item.
### Actual Behavior
Nothing.
### Basic Information

- Version with issue: Xamarin Forms (3.0.0.446417)
- Last known good version: Last time I knew it was working was around December 2017. Just don't know which version it was.
- IDE: Visual Studio Community
- Platform Target Frameworks: 
  - iOS:  11.10.1.177
  - Android: Version: 8.3.0.19
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

### Screenshots

N/A

### Reproduction Link
[SelectedItem does not work.zip](https://github.com/xamarin/Xamarin.Forms/files/2049112/SelectedItem.does.not.work.zip)

**Comment by jassmith** [comment]
You need to set the binding mode of SelectedItem to two way.

Also where you set SelectedItem = null will clear your binding so it will only work once unless you change that to also be a ViewModel level operation.
