### ISSUE TITLE
XF: IsVisible binding will not work if there is ScrollView in a RelativeLayout and specify the RelativeLayout.HeightConstraint value

### ISSUE THREAD

**Issue by allenliu1030** [xamarin/Xamarin.Forms#2864]
### Description
This is Allen from APGC support team. Now there is one customer of mine is having issue with XF as the title mentioned.
The page is one form submit page, customer is using RelativeLayout with lots of controls in it. One of the container in the RelativeLayout is a ScrollView with multiple controls in it. And the issue is happened with one of the switch element which will control a GPS location showing.
The page layout will looks like the below one:

```XML
<RelativeLayout>
	<!-- Some other controls -->
	<ScrollView x:Name="IssueScrollView"
				RelativeLayout.HeightConstraint = "{ConstraintExpression Type=RelativeLayoutToParent, Property=Height, Constant=-45"} >
            <StackLayout Orientation="Horizontal" VerticalOptions="Center">
	        <Label YAlign="Center" Text="Send location data?" TextColor="White" FontSize="Medium" FontAttributes="Bold" ></Label>
		<Switch x:Name="sendLocation" IsToggled="{Binding SendCurrentLocation, Mode=TwoWay}" Toggled="SendLocationToggled" ></Switch>
	    </StackLayout>
	    <StackLayout Orientation="Horizontal" HorizontalOptions="Start" VerticalOptions="Center" IsVisible="{Binding IsFindingLocation, Mode=OneWay}" HeightRequest="25">
                <ActivityIndicator IsRunning="{Binding IsFindingLocation, Mode=OneWay}" HeightRequest="20" HorizontalOptions="Start" Color="White" >
                 </ActivityIndicator>
                 <Label  YAlign="Center" VerticalOptions="Center" Text="Getting your location" HorizontalOptions="StartAndExpand" TextColor="White"></Label>
             </StackLayout>
	</ScrollView>
</RelativeLayout>
```
The normal process is that after turning on the Switch, first it will pop up the permission request for accessing Location, then the StackLayout containing ActivityIndicator and Label should be visible, and the ActivityIndicator should be running.
Current issue is that the permission request will pop up, but the StackLayout will not show. But the code should be running. What we tested is that if we click on one of the Entry element in that page, the StackLayout will then show with everything working normally from then on.
Also, when we get into the form page, if we focus on the Entry first, then the switch will work just as what we want.

One thing I have done to troubleshooting is that if we comment out `RelativeLayout.HeightConstraint = "{ConstraintExpression Type=RelativeLayoutToParent, Property=Height, Constant=-45"}`, then the feature will work normally but the UI will not be showing correctly as customer's original design.

### Steps to Reproduce

1.  Run the customer's code and deploy to Android phone.
2.  Go to the target page.
3.  Directly turn the switch on.
4.  Click Yes when the permission request comes out.

### Expected Behavior
The permission request shows and after giving permission, the StackLayout containing ActivityIndicator will show.
### Actual Behavior
The StackLayout containing ActivityIndicator will not show.
### Basic Information

- Version with issue: XF 2.5.1 and XF 3.0 (This is what I tested, from customer's code, he's using XF 2.5.1, I tried to upgrade to 3.0 but still the same issue.)
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  Currently customer is not working on iOS.
  - Android: My testing is based on 8.0
  - UWP:  No need to investigate UWP.
- Android Support Library Version: No need.
- Nuget Packages: No need.
- Affected Devices: Android devices.

### Screenshots

If we directly turn on the switch, first we will get the permission request as below:

![image](https://user-images.githubusercontent.com/36911474/40698623-7943389c-6402-11e8-8115-46459ac30497.png)

After giving the permission, the issue will reproduce as below: the StackLayout will not show.

![image](https://user-images.githubusercontent.com/36911474/40698563-39311256-6402-11e8-9990-61d7139eb69b.png)

Above is the issue.

After click on the Entry box of Carriage, the StackLayout will show:

![image](https://user-images.githubusercontent.com/36911474/40698577-4972496e-6402-11e8-97d0-1f26ce7f4377.png)

And then the location will show also in that place:

![image](https://user-images.githubusercontent.com/36911474/40698590-556446c8-6402-11e8-8dbb-d715533ac967.png)

### Reproduction Link

Please contact me through mail if the engineer who is working this case needs to take a look at the customer's code.

**Comment by jassmith** [comment]
Hi Allen,

I have tried to reproduce this locally and cannot. Can you please email me the repro case?

**Comment by allenliu1030** [comment]
Hi Jason, due to our policy, I have shared this link to our customer. And this is not our current status of the issue because we have been working offline on this issue. So I have informed my customer that this issue has already been determined as a bug and shared the link to him.

From now on we will track the bug fix status from this link only since I cannot keep the case open for such a long time. Hope you can understand that. So if customer is having any queries or questions, please help to answer them from here. And also, please help to update the comments here is you have any update on the issue. 

Thanks so much!

Allen

**Comment by pauldipietro** [comment]
Due to a lack of updates or further reports for some time now, this will be closed. If the customer is able to share a reproduction as asked for, this issue can be reopened. Thanks!
