### ISSUE TITLE
This code doesn't work in Live player, work fine in android emulator

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#2871]
### Description
When I  run this code it's work in emulator but when I debug it in live player, it doesn't work all, it's make exception.
### Steps to Reproduce

![image](https://user-images.githubusercontent.com/2105258/40730931-845e2bc4-644d-11e8-8e46-6997e9f99a54.png)

### Expected Behavior
should show the result in live player on phone
### Actual Behavior
not compile at all on live player.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment]
CSS is not supported just yet. Coming soon.

**Comment by anirugu** [comment]
OK, this means I can use only Live player for my emulator, no problem, thanks for update @jamesmontemagno
