### ISSUE TITLE
LocalNotification calling weird order of app lifecycle events

### ISSUE THREAD

**Issue by JanNepras** [xamarin/Xamarin.Forms#2872]
### Description
There is weird sequence of life cycle events in App.xaml.cs after click on local notification. If you schedule local notification, click on it from locked screen and open the app it triggers OnResume event, App.xaml.cs constructor and OnStart event. This has to be reproduced in specific order. Project replicating the issue is included.

### Steps to Reproduce

1. Run Android project
2. Click "Launch Notification" (it schedules notification in 5 sec)
3. Click hardware home button
4. Lock the screen
5. Wait for notification and open app by clicking on it
6. See breakpoints in App.xaml.cs and order how it runs

### Expected Behavior
It should call the constructor and OnStart event.
### Actual Behavior
It calls OnResume, constructor and Onstart event.
### Basic Information
It has to be replicated in this specific order otherwise it works well.
- Version with issue: Xamarin.Forms 2.5.0.280555, 3.0.0.482510
- Last known good version: NA
- IDE: Visual Studio
- Platform Target Frameworks: 

  - Android: Andriod 8.1
 
- Android Support Library Version: 25.4.0.2
- Nuget Packages:
- Affected Devices: Samsung S5

### Reproduction Link
https://1drv.ms/u/s!As1Bb4lGxggCg-tJ8q5zTIUuvycBdw

**Comment by PaulVrugt** [comment]
We also have issues with padding an sizes. For instance, a stack layout in a grid cell with height "auto". When the padding of the stack layout changes, the size of the stack layout changes, and the grid should resize. This doesn't happen, and we have to manually call forcelayout on the grid to fix the size.

We run into this when adding support for the iPhone x notch. 

Does this fix also include these situations?

**Comment by jassmith** [comment]
Android is restarting your activity when the notification is selected. Trying setting LaunchMode = SingleTop.
