### ISSUE TITLE
Media.xcassets not in Resources in iOS project

### ISSUE THREAD

**Issue by wescur88** [xamarin/Xamarin.Forms#2874]
### Description
Media.xcassets not in Resources in iOS project, when creating AssetCatalogs from default Info.plist editor.  Media.xcassets is created in the project folder instead in VS2017 version 15.6.6. The Info.plist editor creates the XSAppIconAssets key with this string value: Resources/Media.xcassets/AppIcons.appiconset.
This causes invalid binary validation from ItunesConnect.

### Steps to Reproduce

1. Create iOS project.
2. Add AssetCatalogs and add all images.
3. Submit App to ItunesConnect with AppStore build

### Expected Behavior
Binary to be processed successfully for app release.

### Actual Behavior
Binary is rejected. Missing Info.plist value - A value for the Info.plist key 'CFBundleIconName' is missing in the bundle 

### Basic Information

- Version with issue: Xamarin Forms 2.5.0.280555 and above. VS2017 version 15.6.6
- Last known good version: 
- IDE:VS2017
- Platform Target Frameworks: 
- iOS:    10.3 and above
- Nuget Packages: Xamarin Forms 2.5.0.280555 and above.
- Affected Devices: N/A

**Comment by wescur88** [comment]
Work around is to manually edit the Info.plist and change
<string>Resources/Media.xcassets/AppIcons.appiconset</string>
	<key>CFBundleShortVersionString</key>
to
<string>Media.xcassets/AppIcons.appiconset</string>
	<key>CFBundleShortVersionString</key>

**Comment by KeithJRome** [comment]
This appears to still be an issue in VS 15.7.3 as well. It is noticeable with a new mobile app project when deployed to simulator or device right away - the app icon is the iOS default placeholder.

The workaround above does resolve the problem.

The same issue occurs if you provide asset catalog for launch images too. That plist entry for XSLaunchImageAssets will need to be corrected manually too.

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-macios#4201
