### ISSUE TITLE
System.IO.File.GetCreationTime and .GetLastWriteTime Returning 0

### ISSUE THREAD

**Issue by OneVideo** [xamarin/Xamarin.Forms#2877]
C# calls to System.IO.File.GetCreationTime and .GetLastWriteTime (for each of the local and UTC method forms) return 0 on Android target runtimes when the filename includes a period ('.') character in addition to the one delimiting the extension.  
   * Use of the character is permitted in Android filenames
   * Not using the character in the filename is a mitigation, as the functions return proper datetimes 

### Steps to Reproduce

1. Create a file in LocalApplicationData directory.  Name it simply. e.g., Foobar.mp4
    In a Xamarin Forms project, code:     string sFn = "Foobar.mp4";
2. Use System.IO.File methods to observe the file creation datetime and modified, e.g.,
    string sFQFn = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData), sFn);
    DateTime dtThisCopy = File.GetCreationTimeUtc(sFQFn );
    DateTime dtLastWrite = File.GetLastWriteTimeUtc(sFQFn );

3. Change the code so that sFn = "Foo.bar.mp4" and rename the referred to file, then repeat Step 2

### Expected Behavior
The DateTime values returned for "Foo.bar.mp4" and "Foobar.mp4" should be identical.
### Actual Behavior
Return values are DateTime equivalents of 0
### Basic Information

- Version with issue:  XF 3.0.0.482510
- Last known good version:
- IDE:  Visual Studio 15.7
- Platform Target Frameworks: 
  - iOS:  
  - Android: 25.4.0.2 APIs 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-android#1798
