### ISSUE TITLE
Custom view rendering issue while converting view from Xamarin Forms to native Xamarin.Android #1967

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#2882]
Bug report best practices: https://github.com/xamarin/Xamarin.Forms/wiki/Submitting-Issues

Since we are not able to reopen our previous issue report https://github.com/xamarin/Xamarin.Forms/issues/1967,  we have created this new issue report.

## Description
Adding a custom view to the UI doesn’t occupy the entire space (loaded a grid containing 3 labels Subject, Notes, Location within a frame). A frame is set with Padding property and Grid is loaded into Frame such that the grid inside the frame doesn’t occupy the space accordingly.

Actual issue is while converting the custom view from Xamarin forms to native android. That is, in our case we are rendering the view alone (virtually) in Xamarin forms through mapping and layouting for the custom view and parenting its children are done in native Xamarin.Android.So when it comes to Xamarin forms, parenting its children in source level is not possible ,only by setting height and width to custom view in sample level fixed the issue. Thus we have attached the sample for the mentioned issue in our earlier updates.

We have converted the custom view from Xamarin forms to native referring the below conversion.

http://michaelridland.com/xamarin/creating-native-view-xamarin-forms-viewpage/

We suspect that this is a framework issue with the Grid and positioning of the elements within a Grid. Since we tried with the same layouts directly in xamarin forms and Grid occupied the entire UI in that.UI is rendered as expected Kindly find the sample along with the screenshot for this

**Sample:**

[CustomRenderer.zip
](https://github.com/xamarin/Xamarin.Forms/files/1750631/CustomRenderer.zip)

**Screenshot :**
![36579997-3ec78d2e-188c-11e8-9678-6c8477ee6cc7](https://user-images.githubusercontent.com/39787321/40778562-327ed4dc-64ef-11e8-9888-6aecab38db24.jpg)

**Steps to Reproduce**
Deploy the attached sample, in the view, a grid will be loaded in the frame according to the labels added to it.

**Expected Behavior**
Grid with labels to occupy entire Frame.

**Actual Behavior**
Grid occupies the space in the Frame according to the width and height of the labels.

Only when width request or height request is set to grid or each of the children inside the grid, expected behaviour is obtained.

**Basic Information**
Version with issue: Xamarin 2.4.0
Platform Target Frameworks:
Android: 7.1
The issue is reproduced only in Xamarin.Forms Android platform.

**Sample**

[CustomControl.zip
](https://github.com/xamarin/Xamarin.Forms/files/1750628/CustomControl.zip)

**Screenshot**
![36580001-40f458fc-188c-11e8-8c21-6c1af7e17364](https://user-images.githubusercontent.com/39787321/40778531-17718f86-64ef-11e8-8864-4fad0aee9521.jpg)

Could you please check with the above details and provide us with a possible solution for this.

**Note**: We have checked with the latest Xamarin Forms version 3.0 and issue exists in this version also.

**Comment by jassmith** [comment]
I cannot get your reproduction to run, can you please provide me with better instructions on what I am supposed to be running out of your samples? The CustomRenderer example seems to work fine. The CustomControl one I cant seem to run?

**Comment by PureWeen** [comment]
No updates in the last 30 days. If you're still having an issue please let us know and we can re-open

**Comment by Ganeshamoorthy10** [comment]
Hi @jassmith,

We are able to run the CustomControl sample. Could you please share the faced issue details while running the CustomControl sample?

**Comment by Ganeshamoorthy10** [comment]
Hi @PureWeen ,

We are still facing the issue. Could you please reopen this incident?

**Comment by PureWeen** [comment]
@Ganeshamoorthy10  can you try the latest version of Forms? Maybe you could record a quick little video of how you are reproducing the issue so that we can see what you are doing

**Comment by Ganeshamoorthy10** [comment]
Hi @PureWeen ,

We have checked with latest version of Forms and still we are facing this issue. We have prepared a video to demonstrate how issue is reproduced. Kindly refer the video and the modified sample in below.

Sample: CustomControl

Video: Video

Description:
•	I have created a custom control library project.
•	In CustomViewLayout.XForms project we have created a CustomView property. 
•	In CustomViewLayout.XForms.Android project using renderer, I have converted the Forms view to the native (Android) view. 
•	In CustomViewLayout.Android project native view is added to my custom control.

Steps to Reproduce:
•	Add library project CustomViewLayout.XForms as reference in Xam_Sample (PCl) project.
•	Add library project CustomViewLayout.XForms, CustomViewLayout.XForms.Android, CustomViewLayout.Android as reference in Xam_Sample.Android project.
•	In Xam_Sample project, Frame view with Grid (with 3 labels) is assigned to my CustomView property. 
•	Now, if I deploy the sample, you can see the custom view rendering issue “Grid view is not occupied the entire screen” (Kindly refer our second screen shot in above description).
•	When i directly add the frame view with gird (with 3 labels), then grid occupies the entire screen (Kindly refer our first screen shot in above description).

Expected Behavior:
Grid should occupy the entire screen.

Could you please check with the above details and provide us with a possible solution for this?

Regards,
Ganeshamoorthy C

**Comment by hartez** [comment]
From [the article you took this technique from](http://michaelridland.com/xamarin/creating-native-view-xamarin-forms-viewpage/): 

> WARNING: this is a expert level technique and isn’t officially supported by Xamarin.

That said, I'm not sure how we can help you here. The sample linked in the previous comment does not match what you are showing in the video; it just displays a blank white screen. The best I can do is take a couple of guesses at where you might be going wrong:

1. This line in CustomLayoutRenderer.cs: 
`                    nativeCustomViewLayout.CustomView = ConvertFormsToNativeView(e.NewElement, e.NewElement.CustomView, new ViewGroup.LayoutParams((int)e.NewElement.Bounds.Right, (int)e.NewElement.Bounds.Bottom));`

`e.NewElement.Bounds.Right` and `e.NewElement.Bounds.Bottom` are probably both still `-1` here, so you are asking the native view to layout to a size of -1 x -1. 

2. In ConvertFormsToNativeView, you are doing this:

```
viewGroup.Layout(0, 0, (int)view.Width, (int)view.Height);
var viewsize = view.Measure(double.PositiveInfinity, double.PositiveInfinity);
```

Which means you are calling viewGroup.Layout using the height and width of an unmeasured View; I would guess that the size of the View at this point is -1 x -1. 

Regardless, the technique you are using is unsupported; that it does not work the way you have written it is not a Forms issue.
