### ISSUE TITLE
Orientation mode PortraitUpsideDown is ignored in iOS

### ISSUE THREAD

**Issue by Stensan** [xamarin/Xamarin.Forms#2888]
### Description
It seems the orientation mode PortraitUpsideDown doesn't work in iOS and is ignored. The other orientations are okay.

### Steps to Reproduce

1. Create new Xamarin.Forms + iOS project
2. Add "UIInterfaceOrientationPortraitUpsideDown" to UISupportedInterfaceOrientations in info.plist file.
3. Start app and turn the phone upside down

### Expected Behavior
App changes to PortraitUpsideDown 
### Actual Behavior
App is still in the normal Portrait mode
### Basic Information

- Version with issue: Xamarin.Forms 3.0, 2.5 and 2.4
- Last known good version: Probably versions before 2.4
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS: 11.3 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: This bug affects "Plugin.DeviceOrientation", but it also occurs without it
- Affected Devices: iPhone 8, real device and simulator

**Comment by TomSoderling** [comment]
This is a big issue for us as well. Happening on all our XF apps. Xamarin.Forms v3.4.0.1009999

**Comment by jfversluis** [comment]
Retested with most recent XamForms version and seems to work now. With the exception of iPhone X and up, but it seems that is something Apple has decided not to support anymore: https://forums.developer.apple.com/message/268015

**Comment by TomSoderling** [comment]
Thanks @jfversluis
