### ISSUE TITLE
In vs 2015, I can't create project, someone check this log #helpneeded

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#2889]
---------------------------
Microsoft Visual Studio
---------------------------
Package Installation Error

Could not add all required packages to the project. The following packages failed to install from 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\XAMARIN\XAMARIN.FORMS\Packages':

Xamarin.Android.Support.Animated.Vector.Drawable.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Animated.Vector.Drawable 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Annotations.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Annotations 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Compat.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Compat 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Core.UI.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Core.UI 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Core.Utils.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Core.Utils 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Design.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Design 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Fragment.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Fragment 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Media.Compat.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Media.Compat 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.v4.25.4.0.2 : Could not install package 'Xamarin.Android.Support.v4 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.v7.AppCompat.25.4.0.2 : Could not install package 'Xamarin.Android.Support.v7.AppCompat 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.v7.CardView.25.4.0.2 : Could not install package 'Xamarin.Android.Support.v7.CardView 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.v7.MediaRouter.25.4.0.2 : Could not install package 'Xamarin.Android.Support.v7.MediaRouter 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.v7.RecyclerView.25.4.0.2 : Could not install package 'Xamarin.Android.Support.v7.RecyclerView 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Xamarin.Android.Support.Vector.Drawable.25.4.0.2 : Could not install package 'Xamarin.Android.Support.Vector.Drawable 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
---------------------------
OK   
---------------------------

**Comment by jassmith** [comment]
This bug was already filed and redirected to components.
