### ISSUE TITLE
Feature Request: Implement RaiseEvent function for Android BackButton Event

### ISSUE THREAD

**Issue by sonic1015** [xamarin/Xamarin.Forms#2890]
### Description
In classes that inherit the FormsAppCompatActivity or FormsApplication class, it is impossible to override the default back button behaviour AND respect whether Forms has handled the button event or not.

### Sample Use Case

1.  Suppose I would like the back button to send app to the background instead of destroying the activity
2. Would also like to maintain the behaviour with regards to Navigation, Closing Modal Popups, etc.

### What is Stopping This

Since we can't invoke the BackPressed Event, we can't inform Forms of the event, and can't tell if Forms handled the event. Thus we are stuck with either sending the app to the background on back pressed OR allowing Forms to handle BackEvents but not both.

### Basic Information

- Platform Target Frameworks: 
  - Android: All
  - UWP:  Possibly??? Don't know about this one...
- Affected Devices: All devices with a back button

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
