### ISSUE TITLE
[CSS] vendor prefix

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#2891]
NOTE: this document is not a full spec. some side discussion happened on chats, and on PR reviews.

In addition to the already supported properties, we should introduce vendor prefixes `-xf-`, or `-forms-` and map them to some other of our properties.

See also #1723

### Proposed new properties
|Property|Applies to|Values (string literals are `grayed`, while types are _italic_)|Example|
|---|---|---|---|
|`color`|`BoxView`, `ActivityIndicator`, `ProgressBar`, ...|_color_  \| `initial`|`color: green;`|
|`-xf-placeholder`|`Entry`, `Editor`|_quoted text_ \| `initial`|`-xf-placeholder: "your name here";`|
|`-xf-placeholder-color`|`Entry`, `Editor`|_color_ \| `initial`|`-xf-placeholder-color: limegreen;`|
|`-xf-max-length`|`InputView`|_int_ \| `initial`|`-xf-max-length: 16;`|
|`-xf-keyboard`|`InputView`| `plain` \| `chat` \| `email` \| `numeric` \| `telephone` \| `text` \| `url` \| `initial`|`-xf-max-length: 16;`|

**Comment by davidortinau** [comment]
Would NavigationPage's BarBackgroundColor and BarTextColor fall into this category of updates?

**Comment by StephaneDelcroix** [comment]
@davidortinau 

> Would NavigationPage's BarBackgroundColor and BarTextColor fall into this category of updates?

they would better be served by pseudo-element selectors, but as we idon'thave those yet, a vendor prefix property will do in the meantime. Please add them to the list

**Comment by GalaxiaGuy** [comment]
I would like Spacing on StackLayout and Grid.

| Property | Applies to | Values (string literals are `grayed`, while types are _italic_) | Example |  |
|--------------------|-------------|-------------------------------------------------------------|-----------------------|---|
| `-xf-spacing` | `StackLayout` | _double_ &#124; `initial` | `-xf-spacing: 8` |  |
| `-xf-row-spacing` | `Grid` | _double_ &#124; `initial` | `-xf-row-spacing: 8` |  |
| `-xf-column-spacing` | `Grid` | _double_ &#124; `initial` | `-xf-column-spacing: 8` |  |
