### ISSUE TITLE
[Android, UWP] Span Gesture Recognizer issues with two adjacent spans

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#2892]
### Description

When adding TapGestureRecognizer (and probably other Recognizers) to two adjacent spans the Tap behavior isn't consistent across platforms

### Steps to Reproduce

Run the sample and try to click on each span

```C#
var label = new Label();

			var s = new FormattedString();
			var span = new Span { Text = "I will fire when clicked", FontAttributes = FontAttributes.Bold };
			var span2 = new Span { Text = "I will not fire when clicked", FontAttributes = FontAttributes.Bold };
			span.GestureRecognizers.Add(new TapGestureRecognizer()
			{
				Command = new Command(async () =>
			   {
				   await MainPage.DisplayAlert("Yay clicked", "yay clicked", "yay clicked");
			   })
			});

			s.Spans.Add(span);
			s.Spans.Add(span2);

			span2.GestureRecognizers.Add(new TapGestureRecognizer()
			{
				Command = new Command(async () =>
			   {
					await MainPage.DisplayAlert("not working", "not working", "not working");
			   })
			});

			label.FormattedText = s;

			return new ContentPage()
			{
				Content = new StackLayout()
				{
					Children = { label },
					Padding = 40
				}
			};
```

### Expected Behavior
Both spans should be clickable and remain clickable

### Actual Behavior
Android - can click once but no more
UWP - can't click at all

### Basic Information

- Version with issue: 3.1 nightly
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - Android: api 19
  - UWP:  16299
 
### Reproduction Link

Code in description

**Comment by manicoder** [comment]
Same issue with me. 
I update xamarin forms 3.2 Pre-2
But span gestures only 1 time click and when we click second time its doesn't fire.

**Comment by manicoder** [comment]
I tried with command also. But same behavior with commands.

**Comment by PureWeen** [comment]
@manicoder  this will be resolved with pre-3

**Comment by manicoder** [comment]
Great! When its available pre-3?
