### ISSUE TITLE
The type or namespace name 'WPF' does not exist

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#2893]
### Description
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'WPF' does not exist in the namespace 'Xamarin.Forms.Platform' (are you missing an assembly reference?)

- Nuget Packages: 3.1 preview

### Screenshots
![image](https://user-images.githubusercontent.com/33021114/40816487-f6860038-6555-11e8-9c18-5cbd19ca6de1.png)

**Comment by HelenMamalaki** [comment]
Hey, how did you resolve this? I am getting the same error for 3.3.0.912540 which is a stable version!
