### ISSUE TITLE
Change SearchBar base class to InputView

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#2902]
### Description

Change the `SearchBar` base class from `View` to `InputView` in order to give it Keyboard, IsSpellCheckEnabled, and MaxLength properties.

I know it's technically a breaking change, but spellcheck on a SearchBar is obviously something people want because it was added as a Windows platform specific, and I have extended the SearchBar to add a Keyboard and made a behavior for MaxLength in my own projects.

**Comment by jassmith** [comment]
I dont think this would be a breaking change, we could take this if it got implemented.
