### ISSUE TITLE
Question: Xamarin.Forms startup time on Xamarin.Android

### ISSUE THREAD

**Issue by 5yunus2efendi** [xamarin/Xamarin.Forms#2903]
XF 3 really has an improvement startup time on Xamarin.Android, but on low-end devices it's still quite long (about 4.5-7 s of startup time), and then a while ago I read about Xamarin.Forms startup time on Xamarin.Android, link to the blog is http://tirania.org/blog/archive/2018/May-18.html (yap, it's Miguel de Icaza's blog), in the blog it says that to remove any dynamic code to integrate with Java Runtime, so is it going to be on [Feature Roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap) or is it going to be "independent" work?

Thank you..

**Comment by jassmith** [comment]
Its part of the X.A. roadmap, not X.F.

**Comment by 5yunus2efendi** [comment]
Is there a reference to the roadmap in case it's already implemented?

**Comment by jassmith** [comment]
I have no idea, sorry, you could go ask on the xamarin-android github?

**Comment by 5yunus2efendi** [comment]
Oke, I will. Thanks.
