### ISSUE TITLE
Trying to deploy a andriod app to the simualtor fails. With a standard libary with entity framework core.

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#2905]
### Description
I have been trying to use xamrain with a simple model for years now and every other release it seems to get worse than better, Please guys make this my goto development tools for andriod and ios please.
### Steps to Reproduce

1. Create a Xamrian Forms app add an existing .net standard core libary with ef core 2.02 to the app.
 
### Expected Behavior
App to launch and show data from dl core libary
### Actual Behavior

Project will not even build with this version and deploy to the simliautor.

### Basic Information

Android application is debugging.
Could not connect to the debugger.
06-02 12:44:26.277 I/art     ( 8691): Late-enabling -Xcheck:jni
06-02 12:44:26.664 W/monodroid( 8691): Creating public update directory: `/data/user/0/com.companyname.FuelCallManager/files/.__override__`
06-02 12:44:26.664 W/monodroid( 8691): Using override path: /data/user/0/com.companyname.FuelCallManager/files/.__override__
06-02 12:44:26.664 W/monodroid( 8691): Using override path: /storage/emulated/0/Android/data/com.companyname.FuelCallManager/files/.__override__
06-02 12:44:26.671 W/monodroid( 8691): Trying to load sgen from: /data/user/0/com.companyname.FuelCallManager/files/.__override__/libmonosgen-2.0.so
06-02 12:44:26.671 W/monodroid( 8691): Trying to load sgen from: /storage/emulated/0/Android/data/com.companyname.FuelCallManager/files/.__override__/libmonosgen-2.0.so
06-02 12:44:26.672 W/monodroid( 8691): Trying to load sgen from: /storage/emulated/0/../legacy/Android/data/com.companyname.FuelCallManager/files/.__override__/libmonosgen-2.0.so
06-02 12:44:26.672 W/monodroid( 8691): Trying to load sgen from: /data/app/com.companyname.FuelCallManager-1/lib/x86/libmonosgen-2.0.so
06-02 12:44:26.673 W/monodroid( 8691): Trying to load sgen from: /data/user/0/com.companyname.FuelCallManager/files/.__override__/links/libmonosgen-2.0.so
06-02 12:44:26.688 W/monodroid-debug( 8691): Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:29250,server=y,embedding=1
06-02 12:44:26.720 W/monodroid-debug( 8691): Accepted stdout connection: 20
06-02 12:44:27.508 D/Mono    ( 8691): Image addref mscorlib[0xab92ea20] -> mscorlib.dll[0xad26b500]: 2
06-02 12:44:27.509 D/Mono    ( 8691): Prepared to set up assembly 'mscorlib' (mscorlib.dll)
06-02 12:44:27.510 D/Mono    ( 8691): AOT: image 'mscorlib.dll.so' not found: dlopen failed: library "/data/app/com.companyname.FuelCallManager-1/lib/x86/libaot-mscorlib.dll.so" not found
06-02 12:44:27.510 D/Mono    ( 8691): AOT: image '/usr/local/lib/mono/aot-cache/x86/mscorlib.dll.so' not found: dlopen failed: library "/data/app/com.companyname.FuelCallManager-1/lib/x86/libaot-mscorlib.dll.so" not found
06-02 12:44:27.510 D/Mono    ( 8691): Config attempting to parse: 'mscorlib.dll.config'.
06-02 12:44:27.510 D/Mono    ( 8691): Config attempting to parse: '/usr/local/etc/mono/assemblies/mscorlib/mscorlib.config'.
06-02 12:44:27.542 D/Mono    ( 8691): Assembly mscorlib[0xab92ea20] added to domain RootDomain, ref_count=1

![image](https://user-images.githubusercontent.com/5619229/40874231-a13a5d44-6664-11e8-97be-797dc809122b.png)

[Xamrian Logs For Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/2064957/Xamrian.Logs.For.Bug.zip)

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-android#1801

**Comment by jonpryor** [comment]
> Project will not even build with this version and deploy to the simliautor.

This is *deeply* confusing to me; the mere fact that it *deployed to the device and is running* means that the app *did* build and *was* deployed:

```
06-02 12:44:26.664 W/monodroid( 8691): Creating public update directory: /data/user/0/com.companyname.FuelCallManager/files/.__override__
```

That's an on-device log message. It can only be generated if the app has built and has deployed.

Additionally, there is no error message provided in the original comment, nor in the screenshot. The selected text in the Output panel of Visual Studio (in the image) is *normal*, ***not*** an error.

`2018-06-02_12-12-41.4756.Ide.log` *does* contain some stack traces, but those are from `Xamarin.VisualStudio.Inspector`, which appears to be unrelated and ignorable.

What *exactly* is the bug? Could you please provide a repro project?

**Comment by jassmith** [comment]
Yeah sorry Jon I meant to comment here that this one confuses me too.
