### ISSUE TITLE
Entry and Picker Shrinked in TableView

### ISSUE THREAD

**Issue by DamienDoumer** [xamarin/Xamarin.Forms#2906]
### Description
The Picker and Entry are cut off when I stack them with a label in a view cell. I used the Grid and StackLayout to stack them as I could but the edges of the Entry and the Picker still cutoff as shown on the screenshot. This happens exactly when I set the margins of the controls (Any margin be it top, bottom, left... result in the right edge of the picker or the entry to be cutoff). 

### Steps to Reproduce

1. Create a table view and a table section in it
2. Add a view cell to this section, and place a container which can contain the picker or the Entry with the label in it.
3. Stack the controls (Label and (Picker or Entry) horizontally
4. Set a margin property to the container
5. Run on __UWP__
### Expected Behavior
The label should stack horizontally perfectly with the picker or the Entry as it does normally.

### Actual Behavior
 the picker or textview are cut off at the edge on any screen size.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.482510
- Last known good version:
- IDE: VisualStudio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  16299 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 3.0.0.482510
- Affected Devices: UWP

### Screenshots

![xfissue](https://user-images.githubusercontent.com/16731017/40874491-e5786494-6667-11e8-907e-744d3421ab88.PNG)

### Reproduction Link

`<TableSection>`
                        `<ViewCell>`
                            `<StackLayout Orientation="Horizontal"`
                                        ` Margin="5">`
                                `<Label Text="Result"/>`
                                `<Entry />`
                            `</StackLayout>`
                        `</ViewCell>`
                    `</TableSection>`

**Comment by jassmith** [comment]
Can you provide a reproduction project please?

**Comment by DamienDoumer** [comment]
Yes of course

**Comment by PureWeen** [comment]
No updates in the last 30 days. If you're still having an issue please attach a reproduction and we can re-open
