### ISSUE TITLE
[Enhancement] Ability to set BackgroundColor for ViewCell

### ISSUE THREAD

**Issue by pfedotovsky** [xamarin/Xamarin.Forms#2909]
It would be nice to have BackgroundColor property on ViewCell.

E.g. when using TableView, section headers and items both have the same background color on Android, making them difficult to distinguish. 

There's  open source project xfgloss that adds missing properties, but it currently has an issue with Android: https://github.com/tbaggett/xfgloss/issues/29

It would be nice to have this functionality out of the box.

**Comment by seanyda** [comment]
Do you mean to add a `BackgroundColor` property to `TextCell`, `SwitchCell` etc? You would just add the `BackgroundColor` to the `View` assigned on the `ViewCell`.

**Comment by pfedotovsky** [comment]
@seanyda  yes, I mean adding `BackgroundColor `to `TextCell`, `SwitchCell`, etc. I thought that adding the property to `ViewCell `automatically adds it to all kind of cells, but now I realized that `TextCell `doesn't inherit from `ViewCell`. So probably the right class to extend with `BackgroundColor `is `Cell`.

Supporting all kinds of cells would be nice, but if it's difficult to do for all cells at once, `TextCell `would be an excellent place to start.

**Comment by seanyda** [comment]
There is a method you can override (which I assume is what XFGloss uses) called `SetBackgroundColor` which comes from the `CellRenderer` class. It would be nice to have it as a property in forms though.

**Comment by jsclay** [comment]
Any update on this issue? Thanks!

**Comment by jfversluis** [comment]
Hey look at that! I made a PR for this one, looooong time ago! ANyway, this won't be happening for Forms anymore :) 

Thanks for all your time and effort on this everyone!
