### ISSUE TITLE
use flex layout inside listview item

### ISSUE THREAD

**Issue by mo-kml** [xamarin/Xamarin.Forms#2913]
### Description
im using flex layout into listview item and listview wont render after that
how can i use flex in listview item template?
- Version with issue:

- Nuget Packages: 3.0.0.482510

**Comment by StephaneDelcroix** [comment]
could you please attach a reproduction project ? thanks

**Comment by PureWeen** [comment]
No updates in the last 30 days. If you're still having an issue please let us know and we can re-open
