### ISSUE TITLE
Stepper alternate constructor NOT calling this() to initialize platformConfigurationRegistry

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#2918]
If you look at Slider, it has 2 constructors, the default with no arguments and an alternate with min, max, and value.  The default constructor initializes _platformConfigurationRegistry and the alternate constructor extends the default with ": this()".  This way the alternate constructor will still initialize the _platformConfigurationRegistry.

Stepper is NOT doing this.  The alternate constructor does NOT call this() so the _platformConfigurationRegistry is NOT being initialized so any app using the alternate constructor will crash (at least on Android) with NPE.

**Comment by samhouts** [comment]
closed by #2994
