### ISSUE TITLE
Why is Stepper Up button hardcoded to 10 pixels height on Android?

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#2919]
StepperRenderer for Android shows:

`_upButton.SetHeight((int)Context.ToPixels(10.0));`

Why is this?  It causes the _downButton to be taller than the _upButton.

**Comment by jassmith** [comment]
Its been that way forever it turns out. Should be applied to both, I dont see different size buttons on my test device but I honestly believe there is a dpi where it happens.
