### ISSUE TITLE
TapGestureRecognizer blocks List View Context Actions

### ISSUE THREAD

**Issue by FischerChris1** [xamarin/Xamarin.Forms#2922]
### Description
When tap gesture recognizer is added to the List View item with Context Menu, Context Menu no longer could be opened as TapGestureRecognizer blocks/intercepts all calls.
It was already fixes in Xamarin.Forms 2.5 but now it's occurring again in XF 3.0.

### Steps to Reproduce

1. Reference nuget Xamarin.Forms 3.0 
2. Build simple View with ListView for e.g.
<ListView x:Name="MyListView"
                HasUnevenRows="True"
                IsPullToRefreshEnabled="true"
                IsRefreshing="{Binding IsLoadingData}"
                IsVisible="{Binding IsListViewVisible}"
                ItemsSource="{Binding MySuperCollection}"
                RefreshCommand="{Binding RefreshDataCommand}"
                SeparatorVisibility="None">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <ViewCell.ContextActions>
                                <MenuItem
                                    Command="{Binding Path=BindingContext.ShowInfoCommand, Source={x:Reference MyView}}"
                                    CommandParameter="{Binding}"
                                    IsDestructive="False"
                                    Text="Info" />
                                <MenuItem
                                    Command="{Binding Path=BindingContext.DeleteEntryCommand, Source={x:Reference MyView}}"
                                    CommandParameter="{Binding}"
                                    IsDestructive="True"
                                    Text="Delete" />
                            </ViewCell.ContextActions>
                            <ContentView>
                                <ContentView.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.OpenFileCommand, Source={x:Reference MyView}}" CommandParameter="{Binding}" />
                                </ContentView.GestureRecognizers>
<Label Text="{Binding Filename}"/>
</ContentView>
</ViewCell>
</DataTemplate>
</ListView.ItemTemplate>
</ListView>
3. Start the app on Android and long press on ListViewItem. ConextMenu appears but when tap finger is released the TapGestureRecognizer (from ContentView) Command is executed. In this example -> a file is opened with no chance to tap one of the menu items (info or delete).  

### Expected Behavior
On long press the user can tap one of the menu items and on short press the TapGestureRecognizer is executed. 
### Actual Behavior
Start the app on Android and long press on ListViewItem. ConextMenu appears but when tap finger is released the TapGestureRecognizer (from ContentView) Command is executed. In this example -> a file is opened with no chance to tap one of the menu items (info or delete).  

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.482510
- Last known good version: Xamarin.Forms 2.5.0.280555 
- IDE: Visual Studio for Mac 7.5.2 (build 40)
- Platform Target Frameworks: 
  - Android: 7.1 
  
- Android Support Library Version: v7 -> 25.4.0.2
- Nuget Packages:
- Affected Devices: Different Android Smartphones

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/1932
