### ISSUE TITLE
[Android] Animating Grid child height when its RowDefinition is auto sized creates alignment issues

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#2923]
### Description
I'm trying to animate `HeightRequest` of a Grid child when its parent grid is structured like so with `RowSpacing` set to 0:

```
<Grid.RowDefinitions>
	<RowDefinition Height="20"/>
	<RowDefinition Height="Auto"/>
	<RowDefinition Height="5"/>
	<RowDefinition/>
	<RowDefinition Height="50"/>
</Grid.RowDefinitions>
```

As far as I know, there is no direct way to animate a `RowDefinition` `Height` so I decided to auto size the row and animate the child element's height instead. In theory, this should work fine. In practice, `Auto` is causing issues. When the height of the element is changing in real time, both the bottom and top parts are creating a flickering/permanent void (white in my case because the background color of the page is white). Note that this issue does not exist on iOS.

### Steps to Reproduce

1. Run the attached project
2. Click "Animate second row" button several times until you see the issue

### Expected Behavior

Grid auto-sizing should work.

### Basic Information

- Version with issue: 3.1.0.469394-pre1
- Last known good version: Not sure
- IDE: VS  2017 15.7.2
- Platform Target Frameworks: 
  - Android: 8.1
- Affected Devices: Tested it on Galaxy S9+

### Reproduction Link

[App34.zip](https://github.com/xamarin/Xamarin.Forms/files/2068105/App34.zip)

**Comment by adrianknight89** [comment]
Might be related to #2137 and #1395

**Comment by jassmith** [comment]
Layout callbacks come back async on android so this approach is failing us a bit here. I'll have a think about what can be done to make that work better.

**Comment by adrianknight89** [comment]
possibly related: #1544

**Comment by scxp** [comment]
@samhouts Can we expect a fix to this anytime soon?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
