### ISSUE TITLE
[iOS] ListView with DataTemplate containing additional ListView throws exception on ItemTapped event

### ISSUE THREAD

**Issue by seanyda** [xamarin/Xamarin.Forms#2925]
### Description

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (3) beyond bounds (3) for section (0).
Native stack trace:
	0   CoreFoundation                      0x00000001083861e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010906a031 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001083fb975 +[NSException raise:format:] + 197
	3   UIKit                               0x00000001052a9420 -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:] + 1179
	4   UIKit                               0x00000001052aa3f1 -[UITableView _scrollToRowAtIndexPath:atScrollPosition:animated:usingPresentationValues:] + 146
	5   UIKit                               0x00000001052ade3f -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1643
	6   SiteSurvey.iOS                      0x0000000101dbd009 xamarin_dyn_objc_msgSend + 217
	7   ???                                 0x0000000129afa2a8 0x0 + 4994343592

### Steps to Reproduce

1. Create a `ListView` with a `DataTemplate` containing an additional `ListView` (with `HasUnevenRows` property as true)
2. Add an additional item to the `ListView` in the `DataTemplate` (which will be an `ObservableCollection`)
3. Run `ForceUpdateSize` on the `ViewCell` (Sometimes the cell will resize without doing this, however it doesn't each time).
3. Tap the new row in the ListView

### Basic Information

- Version with issue: All
- Last known good version: N/A
- IDE: Visual Studio for Mac - Version 7.5 Preview (7.5 build 1222)
- Platform Target Frameworks: 
  - iOS: Xamarin.iOS 11.10.1.174, Compiling against 11.0
- Affected Devices: All

**Comment by jassmith** [comment]
Can you attach a small repro case? Putting ListViews in ListViews definitely causes bad things but Im not seeing this exact issue.

**Comment by seanyda** [comment]
@jassmith Is it possible to send a repo privately? I don't have time to attach one but could send you over the project I'm currently working on.

**Comment by PureWeen** [comment]
@seanyda  apologies for the late reply but yes
send one to shneuvil at microsoft

**Comment by samhouts** [comment]
@seanyda Since we haven't heard from you in 30 days, we hope that this issue no longer affects you. If it does, please feel free to reopen this issue and provide the updated reproduction project. You may send one to the the email address provided in https://github.com/xamarin/Xamarin.Forms/issues/2925#issuecomment-405414588. Thank you!

**Comment by JTOne123** [comment]
I guess I caught the same issue with XForms 3.1.0.637273 on iPhone 6S (iOS 11.2.5)

```
Runtime.ThrowNSException (System.IntPtr ns_exception)
Foundation.MonoTouchException: Objective-C exception thrown. Name: NSRangeException Reason: -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:usingPresentationValues:]: row (0) beyond bounds (0) for section (0). Native stack trace: 0 CoreFoundation 0x00000001859f317c <redacted> + 148 1 libobjc.A.dylib 0x0000000184c3c528 objc_exception_throw + 56 2 CoreFoundation 0x00000001859f30ac <redacted> + 0 3 UIKit 0x000000018f2d3bb0 <redacted> + 1724 4 UIKit 0x000000018f2d41cc <redacted> + 152 5 UIKit 0x000000018f0c4a90 <redacted
```

```
Runtime.ThrowNSException (System.IntPtr ns_exception)
Runtime.throw_ns_exception (System.IntPtr exc)
(wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr,intptr,bool,long)
UITableView.SelectRow (Foundation.NSIndexPath indexPath, System.Boolean animated, UIKit.UITableViewScrollPosition scrollPosition)
ListViewRenderer+ListViewDataSource.OnItemSelected (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs eventArg)
(wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell)
ListViewRenderer+ListViewDataSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

I do not know how to reproduce it but maybe my stack trace will help you

**Comment by GagandeepSingh510** [comment]
what is the solution to this i am getting same issue in my application,is it the version of xamarin forms to be updated because i am on 3.2 .Please reply
Thanks :)
