### ISSUE TITLE
ListView separator disappears when scrolling on Android emulator

### ISSUE THREAD

**Issue by ryanavogel** [xamarin/Xamarin.Forms#2928]
### Description

If you add a ListView to a ContentPage and the ListView has enough data to require scrolling, some of the separator lines between the items will disappear when you scroll the ListView.

### Steps to Reproduce

1. Create an empty Xamarin.Forms project in Visual Studio.
2. In the provided MainPage.xaml.cs file, add a view model and data source.
3. Next, in the provided MainPage.xaml file, add a ListView (with a name) and add a Label inside the data template. Bind the Label to the data source added earlier.
4. Back in the MainPage.xaml.cs file, set the ListView data source to the data source created earlier. Make sure the data source has enough items to make the ListView scroll.
4. Run the application in an Android emulator.
5. Scroll the ListView.

### Expected Behavior
The separator line between ListView items is visible while scrolling and after scrolling.

### Actual Behavior
The separate line for some ListView items disappears while scrolling or after scrolling.

### Basic Information

- Version with issue: 3.0.0.482510 (I have also tested using the more recent releases. I listed those versions in the Nuget Packages below.)
- Last known good version:
- IDE: Visual Studio Enterprise 2017
- Platform Target Frameworks:
  - Android: 8.0
- Nuget Packages: 3.0.0.530893, 3.1.0.530888-pre2
- Affected Devices: Nexus 5 Android 6.0 and Nexus 6 Android 8.0 (emulators)

### Screenshots

![image](https://user-images.githubusercontent.com/17071837/40929159-8b77ad0a-67e9-11e8-89b4-24464bbfde7a.png)

### Reproduction Link

Solution I used to reproduce the issue [XamarinFormsTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2069114/XamarinFormsTest.zip)

*NOTE: This issue does not exist on my physical Android device running Android 6.0. Also, I haven't had a chance to test this on iOS.

**Comment by SlinkyRaptor** [comment]
Are you able to scale the emulator up? I've seen similar results on the iOS emulator when it is attempting to scale down. Increasing the size made them appear again.

**Comment by jamesmontemagno** [comment]
This usually means that the sim/emulator is just scaled and it is very small so it will look like this. Try at 100% scale or on a real device.

**Comment by jassmith** [comment]
What the others said
