### ISSUE TITLE
WPF cannot include Forms directly or through Shared library

### ISSUE THREAD

**Issue by DennisWelu** [xamarin/Xamarin.Forms#2935]
### Description
Adding a Xamarin Form XAML/CS file directly to the your WPF project, or including one via direct reference to a shared class library, the file will not build: **error CS0103: The name 'InitializeComponent' does not exist in the current context**

(If instead you create a NetStandard 2.0 class library and reference the shared project there, then reference the NetStandard 2.0 library from the WPF project, everything builds.)

### Steps to Reproduce

1. Create a new WPF application from template, accept the defaults
2. Add a new Xamarin Forms xaml/cs Page to the project and make sure its build action is set to **Embedded resource**  and Custom tool to **MSBuild:UpdateDesignTimeXaml**
3. Build

### Expected Behavior
No errors

### Actual Behavior
error CS0103: The name 'InitializeComponent' does not exist in the current context

### Basic Information

- Version with issue: Tried with 3.x including 3.1 prereleases
- Last known good version: N/A
- IDE: VS2017 15.7.3
- Platform Target Frameworks: 
  - WPF:  .Net 4.6.1
- Nuget Packages: Xamarin.Forms and Xamarin.Forms.Platform.WPF

**Comment by StephaneDelcroix** [comment]
Thanks for reporting this. You should look for the following info in a diagnostic build:
- is the x.f.targets correctly imported in the WPF head ?
- is the XamlG task triggered ? it should be, either before BeforeCompile, or on CoreCompileDependsOn

As you have a workaround (using a ns2.0 library), and as the WPF platform is community supported, I'm going to close this issue. But feel free to reference it if you come up with a PR to fix it.

Thanks
