### ISSUE TITLE
3.0.0 vertical text alignment broken in android searchbar

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#2936]
### Description
The change in the pull request (commit https://github.com/xamarin/Xamarin.Forms/commit/732f4d5a99ca6dcf2764be76b4734f6d3b1c70ba) changes the way the aligment is set in the SearchBar. Before the change, both the horizontal and vertical alignment were set in the UpdateAlignment method of the SearchBarRenderer. After the change, only the horizontal alignment is set. This causes the placeholder and search text to no longer be centered in the search bar.

### Steps to Reproduce

1. place a search bar on a page in android
2. give it a height of 60, and a placeholde text
3. run the app

### Expected Behavior
placeholder is centered vertically in the search bar

### Actual Behavior
placeholder is NOT centered vertically in the search bar

### Basic Information

- Version with issue: 3.0.0.482510 and up
- Last known good version: 2.5.1.527346

### Screenshots

2.5.1 (before change):
![correct](https://user-images.githubusercontent.com/7567114/40969549-7a6f4886-68b8-11e8-9b04-bad498b72ecf.png)

3.0.0 (after change):
![wrong](https://user-images.githubusercontent.com/7567114/40969556-7ecba622-68b8-11e8-9294-e2e7cdae5513.png)

### Reproduction Link
Haven't created a test project, but I think the issue is clear

**Comment by IeuanWalker** [comment]
@samhouts @PureWeen @rmarinho  When will the Xamarin.Forms NuGet get this fix? And what version of the NuGet should we go on to avoid this issue for now?

**Comment by DevEddy** [comment]
@IeuanWalker if you like you can fix this with you own renderer for now: Snippet: https://gist.github.com/DevEddy/07fe39141f0f3852f46fe3ab9bf43f8f

**Comment by IeuanWalker** [comment]
@DevEddy thanks, ill give that a go

**Comment by rmarinho** [comment]
@DevEddy @IeuanWalker yes, we are shipping 3.0.0 with this fix. Should be out  soon.
