### ISSUE TITLE
Creating a version of the Xamarin.Forms nuget package that contains Xamarin.Forms.Debug.targets.

### ISSUE THREAD

**Issue by workgroupengineering** [xamarin/Xamarin.Forms#2937]
### Description
when you are developing your own library and want to adding unit test, the xamarin.forms package does not contain Xamarin.Forms.Debug.targets and you need to download it from the repository and edit the project file.

### Steps to Reproduce

1.  Add at solution test project
2.  Add to test project reference at Xamarin.Forms package
3.  Add test that wants to check the correct functioning of the library in xaml[c]

### Expected Behavior
- existence in the Xamarin.Forms.Debug.targets package
- in the test project import Xamarin.Forms.Debug.targets
### Actual Behavior
- there is not Xamarin.Forms.Debug.targets in  package
- in the test project import Xamarin.Forms.targets
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS Comunity Edition 15.7.3
- Platform Target Frameworks: **All**
- Nuget Packages:  **Xamarin.Forms 3.0.0.530893**

**Comment by StephaneDelcroix** [comment]
hey @workgroupengineering,

At this point, we do not want to commit on maintaining, or not modifying, the `DebugXamlCTask` task you use. As such, we don't want to public the `Debug.targets`.

`DebugXamlCTask` is an internal tool we use. Feel free to use it too if it suits your needs, but that's about all we can do.
