### ISSUE TITLE
BindingContext becomes null after removing item from ListView

### ISSUE THREAD

**Issue by peppe130** [xamarin/Xamarin.Forms#2939]
### Description
Using ObservableCollection and ListView, removing an item from the collection causes NullReferenceException due to null BindingContext. When the item is first created, the BindingContext is **NOT** null; it becomes null when the item is removed from the ObservableCollection which contains it. After removing the item, the OnBindingContextChanged() method of the item itself it's called again but, this time, the BindingContext is null. I have to check for null values in each OnBindingContextChanged() method of the Views I set as ItemTemplate. It's really annoying and it could led to bugs and even crash if I forget to check for null values. Waiting for a prompt reply. Thanks for your efforts.

### Steps to Reproduce

1. Create an instance of `ObservableCollection<T>()`, where **T** is a nullable type.
2. Create a ListView item and set it as ItemTemplate of the ListView.
3. Set the ObservableCollection<T> as ItemsSource of the ListView.
4. Check whether the BindingContext is null in the OnBindingContextChanged() method of the ListView item.

### Expected Behavior
1. OnBindingContextChanged() method should not be called twice.
2. Or better, BindingContext should not be null.

### Actual Behavior
OnBindingContextChanged() is called twice and the second time BindingContext is null.

### Basic Information

- Version with issue: 3.0.0.530893
- Last known good version: N/A
- IDE: Visual Studio for Mac 7.5.2 (build 40)
- Platform Target Frameworks: .NET Standard 2.0
  - iOS:  10.0
  - Android: 8.1 
- Android Support Library Version: 27.0.2

**Comment by StephaneDelcroix** [comment]
> Actual Behavior
> OnBindingContextChanged() is called twice and the second time BindingContext is null.

that's not considered a bug. null is a valid value for a BindingContext, and the Binding system supports it.
make sure your code doesn't break on a null BindingContext.
