### ISSUE TITLE
[iOS] OnPopToRoot should be renamed to OnPopToRootAsync

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#2941]
iOS `NavigationRenderer` is returning a `Task<bool>` when OnPopToRoot is called. It's an async method and should have the `Async` post-fix. Compare it to Android `NavigationPageRenderer` which has the said post-fix..

**Comment by adrianknight89** [comment]
Unfortunately, this issue is not isolated. There are many async methods that lack `Async`. I'm not sure if this issue should be addressed in multiple places or stay as-is. I'd at least suggest that future methods should include this postfix if they are asynchronous.

**Comment by jassmith** [comment]
breaking change, wish we could. Feel free to review Shell for this kind of issue if you want to make sure this doesn't happen again :)

**Comment by adrianknight89** [comment]
That said, do you have plans to address this issue across the framework?

**Comment by jassmith** [comment]
Nope, renaming APIs for the sake of renaming is currently not in the cards.
