### ISSUE TITLE
LiveReload: Derived controls not shown in iOS or updated in Android

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#2942]
### Description
Forum post:
https://forums.xamarin.com/discussion/comment/333144#Comment_333144

If you have a UI control that inherits from `Contentview` it isn't shown on iOS through LiveReload, AT ALL.
The derived control doesn't LiveReload when changes are made, but does update if changes are made to the `PageView` that is hosting the inherited control.

### Steps to Reproduce

1. Make a `ContentViewBase : ContentView` control that inherits from `ContentView`
2. Make a control of that time.... An `AboutView` or something similar
3. Place the `AboutView` on `MainPage`
4. Update the `AboutVIew` and save.  Updates are NOT pushed to the LiveReload target device.
5. Make a change on the `MainPage` and save so it pushes out.  The target device shows the updated page **and** derived control.

### Expected Behavior
iOS should show the derived control.
Android should show the updates to the derived control.

### Actual Behavior
Doesn't (see above)
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2017 v.15.7.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/11351506/40994551-85dc91e4-68ca-11e8-958f-b665cca161f8.png)

![image](https://user-images.githubusercontent.com/11351506/40994563-8dde64e4-68ca-11e8-86de-59df0697f32d.png)

![image](https://user-images.githubusercontent.com/11351506/40994570-93dc653a-68ca-11e8-88a6-955f56d36e75.png)

**Comment by StephaneDelcroix** [comment]
Thanks for taking the time to report this. Unfortunately, LiveReload isn't a product that is actively supported, even less by this team
