### ISSUE TITLE
Issue in Release mode on android.

### ISSUE THREAD

**Issue by vidya091209** [xamarin/Xamarin.Forms#2947]
i am using  .net 2.0 standard  xamarin.form 3.0(3.0.0.530893) latest package.
Visual studio 15.7.3 . i have taken the blank template and have this lines of code only.
i have this peace of code code every thing works in debug mode but fails in release mode.
i am getting this error:

var time = DateTime.Now;
            var tuple = new Tuple<DateTime>(time);
            try
            {
                var t = Expression.Property(Expression.Constant(tuple), "Item1");
                msg.Text = t.ToString();
            }
            catch (Exception ex)
            {
                msg.Text = ex.Message;
            }
![image](https://user-images.githubusercontent.com/12954559/41015614-b5410b10-6968-11e8-9bdb-17c49308693b.png)

**Comment by jassmith** [comment]
The linker is removing the property more than likely. Try accessing the property in a no-op just to force the linker to keep it.

**Comment by vidya091209** [comment]
thanks @jassmith  its working now. what is issue here please explain a bit more for my understanding.

**Comment by jassmith** [comment]
When you have the linker enabled in release mode it removes any code you dont use. The linker isn't able to understand reflection however, so it will remove things you only access via reflection and you get these errors.
