### ISSUE TITLE
CarouselPage child pages don't fire OnAppearing after update to XF 3.0

### ISSUE THREAD

**Issue by hacko-bede** [xamarin/Xamarin.Forms#2951]
### Description
After updating to XF 3.0+  OnAppearing event of child pages added to CarouselPage is no longer fired when the page is changed.

### Steps to Reproduce

1.  Create project to XF 2.5 add CarouselPage and in it add child pages of same type that populates data when OnAppearing event is fired
2.  Update to XF 3.0 and observe how only initially loaded page will receive OnAppearing event when loaded and the rest of the pages will not receive the event when displayed on Android device.

### Expected Behavior
OnAppearing fired when current page in CarouselPage is changed.

### Actual Behavior
OnAppearing is not fired

### Basic Information

- Version with issue:
- Last known good version: 2.5.0.280555
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Nuget Packages: Xamarin.Forms 3.0.0.530893
- Affected Devices: Xperia Z1, Xperia XA, Android_API-23_x86_Emulator

**Comment by sinappsys** [comment]
News?

**Comment by PorkiePie** [comment]
Any news on this yet? It is causing me real problems.

Is there any workaround someone has found?

**Comment by PorkiePie** [comment]
I am nervous about rolling back. I am using a pre-release feature for mapping and there are bound to be dependency issues requiring Forms 3.0. 
As a (hopefully!!) short term workaround I have had to put a button on each page to manually trigger the event. 
I tried looking at the pre-releases of .Forms but they caused other issues

**Comment by sinappsys** [comment]
@jassmith @samhouts  News? I've been waiting for the bug fix for 3 months. When will the problem be solved?
Thanks

**Comment by asimeonov** [comment]
This is really annoying bug and a lot of time passed since the initial bug release. This feature is important for my current app and I'm still delaying updates that I want to release cause of that. Seems like a trivial issue really.

**Comment by sinappsys** [comment]
@jassmith @samhouts  News for this bug?
Thanks

**Comment by sinappsys** [comment]
up

**Comment by PorkiePie** [comment]
@sinappsys Is your comment 'up' significant?

**Comment by sinappsys** [comment]
@PorkiePie 
"up" is an invitation to read the requests I made "up" without having received any response. I apologize for not being clear. Is it possible to know when this problem will be solved? I'm stuck in months I can not update Xamarin.Forms.
 Thank you

**Comment by PorkiePie** [comment]
@hacko-bede @sinappsys 
This is an issue for me. I have a new project which needs Forms 3.0 to use some of the new features with maps etc, and also needs OnAppearing in a carousel, so I am really stuck. This is such a big issue but no interest from Xamarim, apparently. 
I was hoping that the 'Up' comment was somehow referencing a fix.

**Comment by hacko-bede** [comment]
@PorkiePie I do agree with you. Total ignorance from Xamarin team to give any estimation / update about this maybe got us a bit mad :)

**Comment by samhouts** [comment]
We appreciate you taking the time to report this problem. Given our current set of priorities, we expect that this issue will be worked on during our next sprint (143) beginning on 10/15. Please note that our priorities do change occasionally, but as of today, this is our plan. Thank you for your patience!

**Comment by PorkiePie** [comment]
@samhouts Thanks for that. Much appreciated. I assume this will go into a pre-release, is there any rough estimate of when this will be available - I realise things change but I have a client who I would like to give at least an indication to.

**Comment by sinappsys** [comment]
Are there any news?
Thanks

**Comment by PaulWagener** [comment]
Has this issue been fixed in 3.5.0.94564-pre3? Because while it now seems to work in Android it is now broken on iOS in exactly the same way that it was broken on Android before...

**Comment by samhouts** [comment]
@PaulWagener Yikes! Please open a new bug so we can investigate. Thanks!

**Comment by asimeonov** [comment]
Did anyone opened a bug for that? Will be nice to have it fixed 👍

**Comment by cbagpipe** [comment]
Experiencing this bug on Xamarin.Forms 4.7.0.1351 when changing `CarouselPage.CurrentPage` from code.
I'm using `CarouselPage` to display main app page, that contains main menu in TitleView and navigates between pages by pressing on menu items (It's transitional code. Trying to move from TabbedPage to proper mvvm implementation). 

So code looks like:
```csharp
 private void SetCurrentPage(MainMenuItemViewModel activeItem)
        {
            if (MainPage == null)
                return;

            MainPage.Children.Clear();
            MainPage.Children.Add(ActiveItem.Page);
        }
```

It this case both `OnAppearing` and `OnDisappearing` not working at all (and I was relying on them hard).
But when I Pushing or Popping a subpage from `CarouselPage`'s `CurrentPage`, both methods working like a charm.
