### ISSUE TITLE
[iOS] WebView not render/update HTML source after second call

### ISSUE THREAD

**Issue by raphibolliger** [xamarin/Xamarin.Forms#2952]
### Description
WebView does not render HTML content (except first time call) when BindingContext is changed at the page on iOS. The same example works fine on Android. The page is always the same and BindingContext changes before showing with navigation. For details see the attached gifs.

### Steps to Reproduce
Run the attached WebViewTest. (Actually the project name is UserDialogs, because of an other test.)

1. Press Button "HtmlWebView1" -> HTML shows in WebView properly
2. Press Back
3. Press Button "HtmlWebView2" -> Empty WebView
4. Press Back
5. Select another HtmlWebView -> Always empty
6. All further calls to WebViews will be empty

### Implementation Details
```XAML
<WebView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
    <WebView.Source>
        <HtmlWebViewSource Html="{Binding HtmlSource}"></HtmlWebViewSource>
    </WebView.Source>
</WebView>
```
```C#
// html source
const string HTML1 = "<h1>PAGE 1</h1><p>This is Page 1</p>";

// page is always created
_htmlWebView = (Page)Activator.CreateInstance(typeof(HtmlWebView));
...
// setting the binding context when pushing a new view (context will be removed on destroy)
_htmlWebView.BindingContext = new HtmlViewModel(HTML1);
await Navigation.PushAsync(_htmlWebView);
```

### Expected Behavior
It should show the changed HTML source in the WebView. On Android the behaviour is correct. On iOS it works only the first time on a view call.

### Actual Behavior
After a BindingContext change it will never show any HTML content in the WebView on iOS after first call.
### Basic Information

- Version with issue: Xamarin Forms 3.0.0.482510
- Last known good version: never
- IDE: Microsoft Visual Studio Professional 2017 (15.7.3)
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1 
- Nuget Packages: Xamarin Forms 3.0.0.482510
- Affected Devices: iPhone

### Screenshots / Videos
![ios1](https://user-images.githubusercontent.com/6289764/41024974-f9067058-6970-11e8-8782-7b516ef8627a.gif)
![ios2](https://user-images.githubusercontent.com/6289764/41024980-fdffe454-6970-11e8-911e-4c8171fa7b4d.gif)
![android](https://user-images.githubusercontent.com/6289764/41024988-0149cb2a-6971-11e8-84b3-51934b030a13.gif)

### Reproduction Link
[WebViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2075244/WebViewTest.zip)

https://github.com/xamarin/Xamarin.Forms/pull/4254#issuecomment-438553622

**Comment by suchithm** [comment]
Any update on this bug, looks like this issue still exists when switching urls.
Source updated with url1 it is showing
Source updated again with url2 not updating existing webview page.


` <WebView x:Name="LiveWebView"  Source="{Binding WebViewSourceUrl}" VerticalOptions="FillAndExpand" Navigated="LiveWebView_Navigated" />`
