### ISSUE TITLE
[Android] TFS build fails with Error : Value cannot be null. Parameter name: type

### ISSUE THREAD

**Issue by mattrichnz** [xamarin/Xamarin.Forms#2953]
### Description
After upgrading an existing project to .NET Standard 2.0 and XF 3.0-sr2, the Xamarin.Android build definition fails in TFS. Existing iOS and UWP build definitions work fine.

Note: The project builds successfully in VS2017 for all platforms, just fails in TFS for the Android build.

### Steps to Reproduce

1. Create a Xamarin.Android build definition in TFS.
2. Create a sample project using the latest VS2017 .NET Standard template.
3. Run the build.

### Expected Behavior
The build should complete successfully.

### Actual Behavior
The build fails during XAML compilation with the following error(s):
`App.xaml:App.xaml(0,0): Error : Value cannot be null. Parameter name: type`

This error is repeated for **all XAML pages and views** included in the project.

### Basic Information

- Version with issue: .NET Standard 2.0, Xamarin Form 3.0-sr2
- Last known good version: .NET Standard 1.4, Xamarin Forms 2.5.x

**Comment by Quax82** [comment]
I can confirm this issue. Even new, empty pages have this issue.

V2.5.x works fine

**Comment by johandep** [comment]
I have the same issue. All xaml pages give this error. I'm using VS for Mac, latest stable version. On the latest XF v2.5 everything works fine, but on all XF v3.x releases this issue occurs. This started when using .NET Standard 2.0.

**Comment by mattrichnz** [comment]
@Quax82 @johandep Looks like this is a build issue with XF v3.0+ and .NET Standard 2.0.
I haven't experienced the problem on VS2017 (15.7.3) though, only with TFS CI builds.

As a workaround, we have found the following works to solve the issue on TFS:

- Before the Xamarin.Android build step, add a "Visual Studio Build" step to build the SLN.
ie. You can create a specific SLN just for the Android build, and tick the required projects in the Build Configuration Manage.
- Untick "Clean" on the Xamarin.Android build step so the previously-built projects are not cleaned and rebuilt.

**Comment by Quax82** [comment]
Thanks for the info. Is there any known workaround for non TFS builds?

**Comment by mattrichnz** [comment]
@Quax82 Hmmm. I'm not seeing this on non-TFS builds using either VS for Mac or VS2017.
Have you updated to the latest versions?
A couple of things to try:

- Clean and rebuild
- Delete obj and bin folders. Try again?

**Comment by StephaneDelcroix** [comment]
I'd like to have more info on how to reproduce this with msbuild only (no tfs):
- a sample project
- the exact versions

@johandep I'm interested to get your repro as well

**Comment by johandep** [comment]
@StephaneDelcroix ,I fixed it in my project by compiling a package (estimote library which I had referenced) with the same XF 3 version I included everywhere else. That library was first compiled with XF 2.5.1.

**Comment by StephaneDelcroix** [comment]
@johandep oh, interesting. I'm still interested by a repro, as I'd like to see if I can fix this

**Comment by mattrichnz** [comment]
@StephaneDelcroix Will work on getting you a repro project and msbuild script to execute.

**Comment by mattrichnz** [comment]
@StephaneDelcroix I'm unable to repro this after updating to XF 3.0.0-sr5.
I can't even repro it using msbuild with a simple repro project any more.

TFS build task is working once again and XAMLC completes successfully. I'm not sure if perhaps this issue was resolved in XF 3.0.0-sr2, or if it may have been the result of another package causing the build failure. I did update FFImageLoading to the latest NuGet, not sure if that was related?

In any case, I can no longer repro the XAMLC build failure.

**Comment by sivanov-hill30** [comment]
I do experience this issue with VS2017 for Windows and I've tried Xamarin versions 3.0.0.561731 (latest stable) to 3.1.0.561732-pre4

**Comment by StephaneDelcroix** [comment]
@johandep could you quickly come up with a repro project (project targeting XF3, and dependency build on earlier version) ?

@sivanov-hill30 are you sure all your XF versions are aligned in the current solution ? Please attach a repro project so we can investigate

**Comment by mattrichnz** [comment]
@StephaneDelcroix Looks like this issue has come back with XF 3.2-stable.
TFS build task with the Xamarin.Android build-def is failing on all pages and views with:
(Where App.xaml is the name of the file)

`(XamlC target) ->   App.xaml : error : Value cannot be null`

Previously this was resolved after updating to to XF 3.0.0-sr5.
Everything continued working all the way along to XF 3.1.0-sr2, but now fails again with 3.2.0
Any ideas?

**Comment by sivanov-hill30** [comment]
@mattrichnz I'm sorry for disappearing from the thread, I should have posted an update. This error was fixed on my side by reviewing and upgrading all XF components as well as Xamarin.Android and Xamarin.Android.Support.* to the latest versions. I've also switched from using VS2015 to VS2017 and started using Visual Studio 2017 for Mac.
