### ISSUE TITLE
[UWP] Default Slider has only 10 possible values

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#2955]
Slider intervals are inconsistent accross platforms. The problematic platform is UWP:

The current behavior on UWP is approximately: snap to integers (if there are at least 10 integers in the range); otherwise snap to 10 points in the range.

https://bugzilla.xamarin.com/show_bug.cgi?id=38471
> Charles Petzold 2016-02-04 20:45:48 UTC
> A default WinRT/UWP Slider has its StepFrequency property set to 0.1, meaning that the default slider can only yield values of 0, 0.1, 0.2, ... 0.9, 1.0.
> This is in contrast to the default Android Slider, which is given a maximum value of 1000, yielding values of 0, 0.001, 0.002, ... 0.099, 1.000.
> To make these two Sliders consistent, the WinRT Slider should have its [StepFrequency]( https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.slider.stepfrequency#Windows_UI_Xaml_Controls_Slider_StepFrequency) always set to (Maximum - Minimum) / 1000.

Also on UWP a tooltip is shown by default, unlike on iOS (not sure about Android). For consistency the tooltip should be [disabled](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.slider.isthumbtooltipenabled#Windows_UI_Xaml_Controls_Slider_IsThumbToolTipEnabled) on UWP.

(Ideally there would be Xamarin.Forms properties that allow for setting of slider snap intervals and tooltips, but this would require extra work on iOS since the default slider is [limited](https://stackoverflow.com/questions/40670919/uislider-missing-features-snap-tooltip-and-ticks).)

**Comment by charlesroddie** [comment]
@AxelUser

**Comment by jassmith** [comment]
Yeah this hsould be set to a much more reasonable value.

**Comment by AxelUser** [comment]
@jassmith may you assist me about any UWP project in Xamarin Froms solution to test issues, like `Xamarin.Forms.ControlGallery.Android`?
