### ISSUE TITLE
Is it possible to make a xamarin.forms WPF app and use the component from .net framework?

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#2956]
I have one app which heavily depends on system.drawing and  componentone http://helpcentral.componentone.com/nethelp/c1pdf/C1.C1Pdf.4~C1.C1Pdf.C1PdfDocument.html (licensed stuff)

Is it possible to use xamarin.forms ( no andorid and ios) supported needed and build the app and make it work on windows.

Anyone have any idea over this.

Thanks

**Comment by VladislavAntonyuk** [comment]
in your common csproj
`
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net471</TargetFrameworks>
  </PropertyGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net471'">
    <Reference Include="PresentationFramework" />
  </ItemGroup>

<Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />`

**Comment by jassmith** [comment]
Xamarin.Forms does not support System.Drawing itself however you very much can use System.Drawing in your native head while also using Xamarin.Forms components. Closing as this isn't really a bug.
