### ISSUE TITLE
Toolbar is not renderered or not defined 

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#2958]
### Description
I want to override OnOptionsItemSelected(IMenuItem item), So I call
`
Toolbar toolbar = FindViewById<Toolbar>(Resource.Id.toolbar);
SetSupportActionBar(toolbar);`
1. if I call it in OnCreate method toolbar is null
2. if I call it before base.OnStart it is also null, after that it founds.
3. But if I call it after base.OnStart it doesn't renderer until I switch on another tab and go back.

### Steps to Reproduce

1. Create new Xamarin Forms application
2.  inherit your main activity form FormsAppCompat - public class MainActivity : FormsAppCompatActivity
3. In OnCreate method:
`csharp
Toolbar toolbar = FindViewById<Toolbar>(Resource.Id.toolbar);
 SetSupportActionBar(toolbar);`

### Expected Behavior
toolbar is found and set
### Actual Behavior
toolbar is null
### Basic Information

- Version with issue:
- Platform Target Frameworks: 
  - Android: 8.1 
- Android Support Library Version: latest form nuget
- Nuget Packages: latest xamarin forms 3.0 pre-2
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/33021114/41037213-45d80764-699b-11e8-8aa1-c312494fc5a1.png)
![image](https://user-images.githubusercontent.com/33021114/41037235-57ab4bfe-699b-11e8-96d6-07c7cae97e41.png)
![image](https://user-images.githubusercontent.com/33021114/41037284-835c0fe0-699b-11e8-8eaa-a31ef4b85aa5.png)
![image](https://user-images.githubusercontent.com/33021114/41037321-a7eed798-699b-11e8-95da-2670b2046dcf.png)

**Comment by Paul-Brenner-Tangoe** [comment]
May be related to https://github.com/xamarin/Xamarin.Forms/issues/2118 ?

**Comment by VladislavAntonyuk** [comment]
Yes, it looks similarly. But I have added a bit more steps to reproduce and different behaviors

**Comment by jassmith** [comment]
Yeah thats not really how Forms works. We have many toolbars we juggle around as needed, not just a single one. FindViewById is not going to find a toolbar at that point.

**Comment by jassmith** [comment]
Override the NavigationPage renderer and dig out the toolbar using GetChildAt() if you want to grab the toolbar.
