### ISSUE TITLE
A stable way to do navigation without preserving navigation stack.

### ISSUE THREAD

**Issue by aleksvu** [xamarin/Xamarin.Forms#2962]
### Description
Xamarin.Forms should have any way to navigate from page without saving previous navigation stack.

If there is any way - please help.

### Steps to Reproduce

1.  Create two pages (Page1 and Page2 in later steps), put button on first page and bind it with the Command, that executes navigation.

2. First way to do this navigation:
`Application.Current.MainPage = new NavigationPage(new Page1());`

Navigation command:
`new Command( () => Application.Current.MainPage = new NavigationPage(new Page2()));`

3. Second way to to do navigation (also can be in some generalization used to forget about the page you are navigating from, but not the whole stack):
`Application.Current.MainPage = new NavigationPage(new Page1());`

Navigation command:
```
new Command( async () =>
{
           Page prevPage = null;
           INavigation navigation = (INavigation)Application.Current.MainPage;

            lock (_locker) //_locker and _isNavigating are both members of some class, used for navigation, not members of Page1
            {
                if (_isNavigating)
                {
                    return;
                }

                _isNavigating = true;

                prevPage = navigation.NavigationStack[navigation.NavigationStack.Count - 1];
            }

            await navigation.PushAsync(new Page2());

            lock (_locker)
            {
                if (prevPage != null)
                {
                    navigation.RemovePage(prevPage);
                }

                _isNavigating = false;
            }
}
 );
```
After pressing navigate button press hardware back button on android device.

4. Third way to to do navigation. Prepare modal Page1 on top of Page2:

```
NavigationPage navigation = new NavigationPage(new Page2());
await navigation.PushModalAsync(new Page1());
Application.Current.MainPage = navigation;
```

Navigation command:
`new Command( async () => await navigation.PopModalAsync() );
`
Quickly tap navigation button at least two times;

### Expected Behavior
Application works fine.

### Actual Behavior
For  step 2 - occasionaly get https://github.com/xamarin/Xamarin.Forms/issues/1518
For step 3 - user can return on previous page on some conditions. Sometimes it leads to side effects because logic of the page considers, that user cannot return.
For step 4 - get this crash:
```
I/MonoDroid(24920): System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
I/MonoDroid(24920): Parameter name: index
I/MonoDroid(24920):   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <0c18defc272d41ba9268164538921aa7>:0 
I/MonoDroid(24920):   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <0c18defc272d41ba9268164538921aa7>:0 
I/MonoDroid(24920):   at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <0c18defc272d41ba9268164538921aa7>:0 
I/MonoDroid(24920):   at Xamarin.Forms.Application+NavigationImpl+<OnPopModal>d__2.MoveNext () [0x00028] in <afec569c85894ae9a18371a2fecd2d37>:0 
```

### Basic Information

- Version with issue: 2.5.* and 3.0.0.*
- Last known good version: None
- IDE: VS 15.7.3
- Platform Target Frameworks: 
  - Android: 8.1  
- Android Support Library Version: 27 
- Affected Devices: Any Android. Most affected (seem to have more side effects) Xiaomi devices

**Comment by jassmith** [comment]
Re-assigning the main page is an expensive operation, however step 4 seems a pretty tractable bug.

**Comment by StephaneDelcroix** [comment]
this is unsupported, but we plan to solve that problem with the Shell.
