### ISSUE TITLE
CarouselPage supports SetUseSafeArea only on first 2 pages

### ISSUE THREAD

**Issue by K232** [xamarin/Xamarin.Forms#2963]
### Description
I've created a demo project with code from https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.carouselpage?view=xamarin-forms, also use _SetUseSafeArea_ to support iPhone X as described here https://blog.xamarin.com/making-ios-11-even-easier-xamarin-forms/ 

Unfortunately, SafeArea is only supported on the first two screens: The initial one and one to the left. As soon as you scroll 2 to the left, SafeArea is not observed anymore.

### Steps to Reproduce
I've attached a very simple sample based on the 2 pages linked above. 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;

namespace TestCarouselPage
{
    public partial class MainPage : CarouselPage
    {
        public MainPage()
        {
            InitializeComponent();
			CreatePages();
        }

        private void CreatePages()
		{

			Children.Clear();

			Color[] colors = { Color.Red, Color.Green, Color.Blue };
            foreach (Color c in colors)
            {
                ContentPage cp = new ContentPage
                {
                    Content = new StackLayout
                    {
                        Children = {
                        new Label { Text = c.ToString () },
                        new BoxView {
                            Color = c,
                            VerticalOptions = LayoutOptions.FillAndExpand
                            }
                        }
                    }
                };
				cp.On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);
                Children.Add(cp);
            }

            
		}
    }
}

```

### Expected Behavior
Safe Area is supported on all pages.

### Actual Behavior
Safe Area is only supported on initial page and on first page to the left.

### Basic Information

- Version with issue: XF 3.0.0.530893
- Platform Target Frameworks: 
  - iOS:  11.4
- Affected Devices: iPhone X

### Screenshots
![iphone x - page 1](https://user-images.githubusercontent.com/685016/41051022-47bce814-69b5-11e8-97ec-197955725973.jpg)
![iphone x - page 2](https://user-images.githubusercontent.com/685016/41051023-47f0fb5e-69b5-11e8-952b-f90fcaaec5bd.jpg)
![iphone x - page 3](https://user-images.githubusercontent.com/685016/41051025-4815aeb8-69b5-11e8-82ba-5fddb5c29dc2.jpg)

### Reproduction Link
[TestCarouselPage.zip](https://github.com/xamarin/Xamarin.Forms/files/2077147/TestCarouselPage.zip)

**Comment by jassmith** [comment]
Yeah this is unfortunately due to how virtualization works with combined with the SafeAreaInsets. There is probably another inset propagation wiggle required to make this work.

**Comment by Swiftless** [comment]
I'm also experiencing this issue and it's severely impacting development.

Would there at least be a potential workaround until a fix is available? Nothing I'm trying appears to work.

**Comment by K232** [comment]
Any news on this?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Chimbox** [comment]
I'm having this issue in Xamarin Forms 5.0.0.2337
