### ISSUE TITLE
Regression: Appium not seeing iOS table elements after 2.3.4 sr6 (2.3.4.270)

### ISSUE THREAD

**Issue by CMyhill** [xamarin/Xamarin.Forms#2971]
### Description
I am using Appium Desktop for Mac to automate UI tests.  When testing our Xamarin Forms iOS application we can locate all visual element except those which appear in a ListView which is populated after the initial load of the page.  

This issue is not seen in version 2.3.4.270 but for all subsequent versions the issue exists.

### Steps to Reproduce

1.  Install Appium Desktop and run (https://github.com/appium/appium-desktop/releases/tag/v1.6.1)
2. Build the iOS applicaiton in Release for Simulator
3. Start an inspector session with the following settings;
{
  "platformName": "iOS",
  "app": "AppiumXamarinListView/AutmationIdTest.iOS/bin/iPhoneSimulator/Release/AutmationIdTest.iOS.app",
  "deviceName": "iPhone 8",
  "automationName": "XCUITest"
}
4. View the view hierarchy 

The app value for Appium needs to be the full path from / 

### Expected Behavior

Regardless of when the table is populated I should be able to inspect all elements in a table

### Actual Behavior

Elements in a table are not visible, we only see the top level table element and non under it

### Basic Information

- Version with issue: All greater than 2.3.4.270
- Last known good version: 2.3.4.270
- IDE: Mac
- Platform Target Frameworks: 
  - iOS:  11.4
- Nuget Packages:
- Affected Devices: all iOS device

### Reproduction Link

https://github.com/CMyhill/AppiumXamarinListView

**Comment by StephaneDelcroix** [comment]
We're sorry you no longer are able to run Appium, but we do not do support for it...
