### ISSUE TITLE
Buttons aren't released properly when using a touchscreen.

### ISSUE THREAD

**Issue by sf-ica** [xamarin/Xamarin.Forms#2978]
### Description

Buttons aren't released properly when using a touchscreen under Linux with Xamarin.Forms.Platform.GTK.

### Steps to Reproduce

1. Create a page with a few buttons.
2. Open the page.
3. Touch the buttons.

### Expected Behavior

After a button has been touched the colors should change back to the initial state.

### Actual Behavior

The state doesn't change.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.GTK 3.0.0.550146
- Last known good version: n/a
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Linux/GTK
- Affected Devices:
  - Raspberry Pi Zero with current Raspbian (Stretch) and this touchscreen: https://www.waveshare.com/wiki/3.5inch_RPi_LCD_(B)

### Screenshots

![gtkbuttons](https://user-images.githubusercontent.com/39555596/41142533-5480adfa-6af6-11e8-8ee4-26c6245b607d.png)

### Affected code

The issue is caused by your custom button widget:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.GTK/Controls/ImageButton.cs#L130

Without the expose event handler buttons behave as expected, but I cannot use custom colors in Xamarin.Forms anymore.

**Comment by StephaneDelcroix** [comment]
should have been closed by merging #3123
