### ISSUE TITLE
Is there a way to bulk add Views to Children property of the Layout element?

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#2979]
I have more number of elements that I add to the Grid or StackLayout from the code. And every time I call the "Children.Add" there are many updates.
 Is there a way to add all View at a time, or something similar?

**Comment by AmrAlSayed0** [comment]
While on the topic, is there a way to force the UI to stop the Layout/Measure pass while I am doing bulk/heavy modifications to the UI and then re-enable it after?

**Comment by CZEMacLeod** [comment]
@KSemenenko @AmrAlSayed0 I think StackLayout inherits from VisualElement which has BatchBegin and BatchCommit which I think are designed for these scenarios.

**Comment by KSemenenko** [comment]
@AmrAlSayed0 @CZEMacLeod 
Thanks, I'll try!

**Comment by jassmith** [comment]
Layout updates are already grouped together automatically which is the more expensive part. Just adding a bunch of children in a row will result in a single layout pass.
