### ISSUE TITLE
When will FastRenderers be made public?

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#2983]
I am overriding Renderers with my own, for example:

```
[assembly: ExportRenderer(typeof(Xamarin.Forms.Label), typeof(MyProjLabelRenderer))]
namespace MyProj.Droid.CustomRenderers.Controls
{
    public class MyProjLabelRenderer : LabelRenderer
    {
        public MyProjLabelRenderer(Context context) : base(context)
        {

        }
```

But cannot override `FastRenderers.LabelRenderer` because it is [internal](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/FastRenderers/LabelRenderer.cs).

 When will these be made public?

**Comment by adrianknight89** [comment]
They were public initially but changed to internal with #1074. @hartez

**Comment by JKennedy24** [comment]
Am I correct in thinking that my app wont benefit from `FastRenderer` for `Label` if I use my `LabelRenderer` in the example above. Even if I do use the SetFlags("FastRenderers_Experimental")

**Comment by adrianknight89** [comment]
While I'm not 100% sure, I think you're right. The experimental flag turns on fast renderers baked in to the XF assembly. You'd still need to inherit from a fast renderer if you want to customize the "default" one.

Btw, I noticed that `Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer` is public while other fast renderers are internal. I think the team needs to fix this and in theory we should be able to extend default fast renderers (i.e. they should be public).

**Comment by jassmith** [comment]
There are not public yet because we are not happy with their API yet. They will be made public sometime after ListView2 and Shell release.
