### ISSUE TITLE
System.FormatException: 'Input string was not in a correct format.'

### ISSUE THREAD

**Issue by inforithmics** [xamarin/Xamarin.Forms#2986]
### Description

I can set to FontSize to a Number or predefined value like Large this does not work when I use OnPlatform.

### Steps to Reproduce

1. Create Cross Platform Application, With .Net Standard.
2.  Replace MainPage.xaml with 
```
 <!-- Place new controls here -->
    	<Label Text="Large Text" 
               FontSize ="Large"
    	       HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" />
        <Label Text="Large Text OnPlatform"
               HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand">
            <Label.FontSize>
                <OnPlatform x:TypeArguments="x:Double">
                    <On Platform="Android" Value="Large"/>
                    <On Platform="iOS" Value="Large" />
                    <On Platform="UWP" Value="Large" />
                </OnPlatform>
            </Label.FontSize>
        </Label>
```
3.  Start App it crashes with 
System.FormatException: 'Input string was not in a correct format.'

### Expected Behavior
It works
### Actual Behavior
It crashes with exception System.FormatException: 'Input string was not in a correct format.'
### Basic Information

- Version with issue: 3.0.0.550146
- Last known good version: None
- IDE: Visual Studio 2017.7
- Platform Target Frameworks: 

  - iOS:  11.4
  - Android: 8.1 
  - UWP:  16299
- Android Support Library Version: v27.0.2
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[App6.zip](https://github.com/xamarin/Xamarin.Forms/files/2084330/App6.zip)

**Comment by AmrAlSayed0** [comment]
You are passing the value of "Large" (a string in this case) to something that is expecting a value of x:Double which can't be parsed. Try changing the x:Double to x:NamedSize so that Large would be converted to a NamedSize correctly. The reason why Large (or other sizes) work directedly on the property is that Xamarin.Forms has converters that convert this named size to a double when needed.

**Comment by rmarinho** [comment]
You should use a double value  like @AmrAlSayed0 referred. To use something like `Large` you should do:

```
 <OnPlatform x:TypeArguments="NamedSize"
                    iOS="Large"
                    Android="Large"
                    WinPhone="Medium" />
```

Thanks

**Comment by inforithmics** [comment]
Thanks for the fast response

Unfortunatly it didn't work, I even tried the neweset Xamarin.Forms 3.1 Preview Release

Following message was displayed

Position 17:18. No property, bindable property, or event found for 'FontSize', or mismatching type between value and property.	

when I remove this
[assembly: XamlCompilation (XamlCompilationOptions.Compile)]

It crashes on runtime so NamedSize doesn't seem to work
