### ISSUE TITLE
Very high memory consumption when navigating between two pages.

### ISSUE THREAD

**Issue by sf-ica** [xamarin/Xamarin.Forms#2987]
### Description

Memory consumption increases constantly when navigating between two pages. When the app requires about 80% of the available memory some resources are freed.

### Steps to Reproduce

1. Create a new application with two pages.
2. Go forward and backwards.

### Expected Behavior

Memory consumption shouldn't increase significantly.

### Actual Behavior

Memory is freed too late.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.GTK 3.0.0.550146
- Last known good version: n/a
- IDE: Visual Studio 2018
- Platform Target Frameworks: 
  - Linux/GTK
- Affected Devices: Raspberry Pi Zero with Raspbian (Stretch) and Mono 5.12.0.226.

### Example Code

I created two simple pages with the following code behind:

```
public partial class Page1 : ContentPage
 {
		public Page1()
		{
			 InitializeComponent();
		}

		protected override void OnAppearing()
		{
			 base.OnAppearing();

			 Task.Run(async () =>
			 {
					await Task.Delay(1000);
					Device.BeginInvokeOnMainThread(() =>
					{
						 Navigation.PushAsync(new Page2(), false);
					});
			 });
		}
 }
```

```
public partial class Page2 : ContentPage
{
	public Page2 ()
	{
		InitializeComponent ();
	}

	protected override void OnAppearing()
	{
		 base.OnAppearing();

		 Task.Run(async () =>
		 {
				await Task.Delay(1000);
				Device.BeginInvokeOnMainThread(() =>
				{
					 Navigation.PopAsync(false);
				});
		 });
	}
}
```

You can see with top how the memory consumption increases constantly. I inserted an image on page 2 and after 400 iterations the app requires 75% of my memory:

```
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 2250 pi        20   0  529444 331540   6516 S 20.6 74.7   2:41.02 mono
```

**Comment by jsuarezruiz** [comment]
Thanks for the detailed feedback, I will review it.

**Comment by jsuarezruiz** [comment]
Work in progress: [https://github.com/jsuarezruiz/Xamarin.Forms/tree/feature/2987-gtk-memory]( https://github.com/jsuarezruiz/Xamarin.Forms/tree/feature/2987-gtk-memory)
