### ISSUE TITLE
If you have chat it just stop working :)

### ISSUE THREAD

**Issue by patsadow2** [xamarin/Xamarin.Forms#2988]
XAMARIN 3.0.0.482510

UWP 

- scrollTo down in object from observable list doesnt work anymore 👎 

IOS

- entry doesn't go up by default when you enter some data.... like in Android (write one to all platforms) no i dont want to use scrollview, if it a solution i can either use translate to some position....

Conclusion:
Fixing bugs introduce more bugs.... 

After update to 3.1.0.550168-pre3 

UWP
- item in null before update it worked :)

    ```
    async void OnItemSelected(object sender, SelectedItemChangedEventArgs args)
        {
            var item = args.SelectedItem as Item;
            if (item == null)
                return;

            await Application.Current.MainPage.Navigation.PushModalAsync(new ItemDetailPage(new ItemDetailViewModel(item)),false);
            ItemsListView.SelectedItem = null;
        }
```

**Comment by jassmith** [comment]
A repro would really help me identify the issues you are seeing.

**Comment by patsadow2** [comment]
IHostE on my github

**Comment by samhouts** [comment]
ScrollView bug: #3367

**Comment by samhouts** [comment]
iOS Entry bug: 2768

**Comment by samhouts** [comment]
UWP SelectedItem bug: #3378

**Comment by samhouts** [comment]
Since it is very difficult to work with an issue reporting multiple bugs, we are going to close this issue. Please follow the issues referenced above for updates on the bugs mentioned here. Thank you!
