### ISSUE TITLE
[UWP] Xamarin.Forms 3.1 ListView ItemTapped event issue for UWP. 

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#2996]
### Description
I am facing LIST VIEW related issues after upgrading to Xamarin Forms 3.1.0.550168 package.
ItemTapped event is not working for Newly added item into list.

If item is already added into the list its working fine, but if you add item dynamically then Tapped event is not executing for new items. It's working fine for ANDROID.
### Steps to Reproduce

1. Create Xamarin.Forms project.
2. Select Platform UWP.
3. Upgrade to Xamarin.Forms Nuget to 3.1.0.550168 
4. Add  ListView with 2-3 items and one button.
5. Bind ItemTapped event to listView using Xamarin.Forms.BehaviorsPack.
6. Run Project. 
7. ItemTapped will work fine for 2-3 items. Now click on Button and Added Item into the list on each click dynamically.
8. Item Tapped will not work for Newly added item.

### Expected Behavior
 Item Tapped Event should work for newly added items too.

### Actual Behavior
Item Tapped Event working for Exiting item only not working for dynamically added item.

### Basic Information

- Version with issue: XF 3.1.0.550168 
- Last known good version: XF 3.0.0.482510
- IDE: Microsoft Visual Studio Community 2017
- Platform Target Frameworks: 
  - UWP:  16299 

- Affected Devices: UWP

### Screenshots
![1](https://user-images.githubusercontent.com/30036418/41190633-6fcdfb84-6c00-11e8-837b-b79c25d1e90d.png)
![2](https://user-images.githubusercontent.com/30036418/41190634-70172c00-6c00-11e8-91ea-42a360cb2f9b.png)

**Comment by la99er** [comment]
I still have the issue. Should this bug be fixed already?

**Comment by PureWeen** [comment]
It will be resolved with the next release
