### ISSUE TITLE
horizontal Scrollview breaks scrolling when flowdirection is set to rtl

### ISSUE THREAD

**Issue by smartprogrammer93** [xamarin/Xamarin.Forms#3000]
### Description

As in the title the horizontal scrollview doesnt allow you to scroll anymore if you set its flowdirection to righttoleft

### Steps to Reproduce

1. make a scrollview with orientation set to horizontal
2. set its flowdirection to righttoleft

### Expected Behavior

scrolling working

### Actual Behavior

scrolling does not work

### Basic Information

- Version with issue: 3.1.0.550168-pre3
- IDE: visual studio 2017
- Platform Target Frameworks: 
  - iOS:  not sure if it exists in ios
  - Android: oreo
  - UWP:  don't use it

### Related to

issue: #1222

**Comment by smartprogrammer93** [comment]
I managed to workaround this by 
for android:
setting the viewgroup.layoutdirection
for ios:
seting the contentoffeset to the end

**Comment by danielkatz** [comment]
It looks like the problem stems from an error in measuring the ScrollViewContainer.
We managed to create a working workaround for this issue [RtlScrollViewFix](https://github.com/danielkatz/RtlScrollViewFix).
There is a secondary bug, that int RTL mode, the scrollbar starts from the left side, which in RTL is the end. This issue resolve by this workaround a well.

**Comment by PureWeen** [comment]
@danielkatz  thank you for the solution project that's been very helpful. The current problem I'm looking into is that the solution you have only works because the minSdkVersion is set to 19

If I set it back down to 15 then it doesn't work on the scrollview is just stuck

**Comment by danielkatz** [comment]
@PureWeen I didn't test it this far back, but my first suspect will be the ScrollX handling that was glitchy even on 19+.
Would the solution work without the whole block at line 83?

**Comment by danielkatz** [comment]
@PureWeen Besides, according to the [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left), RTL is supported from API 17+, so prior to 17 the whole thing can be disabled...

**Comment by PureWeen** [comment]
Yea I realize that about the API 17+ but if I just setup a native Xamarin Android app with a horizontal scrollview set to RTL the whole thing works just fine

**Comment by smartprogrammer93** [comment]
Still breaks scrolling as of xamarin 3.3.0.689585-nightly
Sorry for being impatient, really wanted to check if it works now.

**Comment by PureWeen** [comment]
@smartprogrammer93  this fix hasn't been merged up from 3.1 yet to master

**Comment by smartprogrammer93** [comment]
@PureWeen ops, sorry my bad, just excited.

Thanks for the hard work

**Comment by PureWeen** [comment]
@smartprogrammer93  I'm excited that you're testing nightlies!!!

Once there's a package to test I'll let you know

**Comment by PureWeen** [comment]
@smartprogrammer93  so it was only out with the nightly briefly but this fix is part of the service release

https://www.nuget.org/packages/Xamarin.Forms/3.1.0.697729

**Comment by jafarullahag** [comment]
Check this link for entire implementation, 

https://xamarinindia.blogspot.com/2018/11/xamarin-forms-rtl-right-to-left-support.html
