### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.Bitmap'.

### ISSUE THREAD

**Issue by ben-powley** [xamarin/Xamarin.Forms#3003]
### Description
When launching a Xamarin Forms 3.0 app on either the simulator or an actual device, the app crashes when loading a tabbed page with the error "System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.Bitmap'".

### Steps to Reproduce

Unfortunately it's not consistent. Sometimes it will crash 10 times in a row, sometimes it will work 10 times in a row.

### Expected Behavior
The app should function as normal and load the tabbed page.

### Actual Behavior
The app crashes with the error "System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Android.Graphics.Bitmap'".

### Basic Information

- Version with issue: 3.0.0.550146
- Last known good version: 3.0.0.482510
- IDE: Visual studio 2017 proffesional
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages:
- Affected Devices:
-- Android 7.1 Simulator
-- Samsung Galaxy S9+ 8.1
-- Android 8.0 Simulator

**Comment by AmrAlSayed0** [comment]
Might be a duplicate of #2004 and #2637 or just related.

**Comment by ben-powley** [comment]
@AmrAlSayed0 Ah it does seem like it. I didn't see those when looking earlier. Thanks!
