### ISSUE TITLE
Using ncrunch getting worse since commit "[XamlG] builds incrementally, add MSBuild integration tests (#2825)" 

### ISSUE THREAD

**Issue by berndu** [xamarin/Xamarin.Forms#3004]
### Description

ncrunch is a popular unit test tool which is not support but does work mainly with Xamarin forms apps as well.

Since this [commit](https://github.com/xamarin/Xamarin.Forms/commit/b84b35bb5f36c0a507604100de8a6d754f831668) there is no more possibility to skip XamlC build step (which fails in ncrunch).

### Steps to Reproduce

1. Create a simple Xamarin forms app and add a unittest
2. add something to skip XamlC build step (--> Condition="'$(_XamlCAlreadyExecuted)'!='true'")
3. let ncrunch build the unit tests in you 

### Expected Behavior
XamlC step should be skipped and ncrunch tests run

### Actual Behavior
There is no way to skip the build step and ncrunch is useless (reduced to business logic).
Before we used it in our view models successfully as well.

### Basic Information

- Version with issue: 3.0.0.530893
- Last known good version: 3.0.0.482510
- IDE: 15.7.3
- Platform Target Frameworks: iOS/Android (unittests)
  - iOS:  nn
  - Android: nn
  - UWP:  nn
- Android Support Library Version: nn
- Nuget Packages: nn
- Affected Devices: all

Problem was removing that from Xamarin.forms.targets file (Line 89-92):
`
<Target Name="XamlC" AfterTargets="AfterCompile" Condition="'$(_XamlCAlreadyExecuted)'!='true'">
		<PropertyGroup>
			<_XamlCAlreadyExecuted>true</_XamlCAlreadyExecuted>
		</PropertyGroup>
`

**Comment by StephaneDelcroix** [comment]
msbuild properties starting with a `_` are usually reserved for internal usage. If they suits your needs, use them, but don't rely on to be stable, or supported across versions.

if you have a good use case for always skipping XamlC with an msbuild property, please file an enhancement request, eventually with a proposed implementation.

**Comment by berndu** [comment]
Would be great to have a XamlCAlreadyExecuted flag in the build process to skip the step - e.g. for ncrunch - to remove the _ ok  thats convention...

**Comment by jonathanpeppers** [comment]
@berndu can you try what I did in #3034 ?

We don’t really know what NCrunch is doing, it might also be worth looking at Visual Studio’s new Live Unit Testing feature.

**Comment by berndu** [comment]
I will try this and come back when i verified - i shortly looked at the changes and think it can do exactly what is needed to get it running again.

**Comment by berndu** [comment]
I tried - works great! Thanks a lot - so we can write this in to our project file - in a first step and in a second ask ncrunch to set the "DesignTimeBuild" what is the official correct way for this.
