### ISSUE TITLE
TimePicker: restrict available minutes

### ISSUE THREAD

**Issue by MaxFe** [xamarin/Xamarin.Forms#3016]
### Description
The TimePicker let us choose between 0 and 60 minutes. We use the TimePicker to set an appointment date and it rarely makes sense to set an appointment with 39 minutes. It would be great to have a restriction posibility like "AllowedMinutes"={00,15,30,45}

### Basic Information

- Version with issue: 2.5.1.527436
- IDE: Visual Studio 15.7.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/31653042/41290363-f3f5e91e-6e4c-11e8-9826-beb62563a562.png)

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
