### ISSUE TITLE
[UWP] Grouped ListView ArgummentOutOfRageException ItemTapped

### ISSUE THREAD

**Issue by CarstenGruenzner** [xamarin/Xamarin.Forms#3018]
### Description
Tapping on an item in a grouped ListView causes an ArgumentOutOfRangeException.

### Steps to Reproduce

1. Compile and start sample 
2. Click on the "Fill" Button.
3. Tap on any item of the ListView

### Expected Behavior

Invoke the event handler.

### Actual Behavior

Throws an ArgumentOutOfRangeException.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.561731
- Last known good version: Xamarin.Forms 3.0.0.446417
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - UWP:  16299  
- Nuget Packages: Xamarin.Froms 

- Affected Devices:
Windows 10
### Reproduction Link

[GroupedListViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2094341/GroupedListViewIssue.zip)

**Comment by PureWeen** [comment]
Probably related to this
https://github.com/xamarin/Xamarin.Forms/issues/3019
