### ISSUE TITLE
UWP UI Tests can't find Labels

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3022]
### Description

The AutomationPeer that was added to enable Labels to be found in UWP tests was reverted because it had unintended consequences for the Narrator.

Another solution needs to be found so we can get automated tests working again.

https://github.com/xamarin/Xamarin.Forms/pull/2876/files#diff-2d9dd75388745f6bfedf2b80ea8d4c76R38

**Comment by jfversluis** [comment]
Looks like this has already been fixed long ago
