### ISSUE TITLE
Can't call WCF methods in Xamarin.Forms (Cross-Platform)

### ISSUE THREAD

**Issue by AliParLouS** [xamarin/Xamarin.Forms#3024]
### Description
Hi,
I just create a simple WCF project with default values (without change even a single line of code), i publish it in web, Consume it in EXE application and it work fine, Cosume it in asp.net webform and it work fine.

Now i create another simple Xamarin Cross-Platform with .Net Standard 2 (UWP, iOS, Android), Used "Microsoft WCF Web Service Reference Provider" and i checked all 3 project in **UWP work fine** but in android and iOS can't call GetDataAsync().

### Steps to Reproduce

Xamarin button clicked code : 
```
Service1Client client = new Service1Client(Service1Client.EndpointConfiguration.BasicHttpsBinding_IService1);
string returnString;
returnString = await client.GetDataAsync(Convert.ToInt32(entNumber.Text));
lblResult.Text = returnString;
await client.CloseAsync();
```

### Expected Behavior
It should return an string like "You entered : 123" into a label

### Android runtime error after clicked button :

> 
> Unhandled Exception:
> 
> System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Error in deserializing body of request message for operation 'GetData'. OperationFormatter encountered an invalid Message body. Expected to find node type 'Element' with name 'GetData' and namespace 'http://tempuri.org/'. Found node type 'Element' with name 'GetDataAsync' and namespace 'http://tempuri.org/'

### iOS runtime error after clicked button :

> Unhandled Exception:
> 
> System.InvalidOperationException: MonoTouch does not support dynamic proxy code generation. Override this method or its caller to return specific client proxy instance

### Basic Information

- Version with issue:
- Last known good version:
- IDE:15.7.3
- Platform Target Frameworks: Net Standard 2.0 
  - iOS: 11.12.0.4 
  - Android: 8.3.3.2 
  - UWP:  Couldn't find UWP version 
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms 3.0.0.550146
Xamarin.Android.Support.v7.MediaRouter 25.4.0.2
Xamarin.Android.Support.v7.CardView 25.4.0.2
Xamarin.Android.Support.v7.AppCompat 25.4.0.2
Xamarin.Android.Support.v4 25.4.0.2
Xamarin.Android.Support.Design 25.4.0.2
System.ServiceModel.Security 4.4.0
System.ServiceModel.NetTcp 4.4.0
System.ServiceModel.Http 4.4.0
System.ServiceModel.Duplex 4.4.0
NETStandard.Library 2.0.1
Microsoft.NETCore.UniversalWindowsPlatform 6.1.5
- Affected Devices:
Android : Note 4, Android Emulator 7.1
iOS : iPhone 6 Plus Emulator
UWP : Local Machine

**Comment by samhouts** [comment]
Android and iOS lack the required infrastructure to call WCF methods directly. However, you can follow this guide to create proxies: https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf

I will go ahead and close this issue now, but if you have any further questions, feel free to reopen this issue. Thank you!

**Comment by denmusic1992** [comment]
I'm stuck with the same problem...
I used slsvcutil.exe, as explained in [(https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf)], but code is too complicated with all these events.
I tried to do this using ChannelFactory, and on android it works like a charm, but on iOS there is the same error: 

> Unhandled Exception:

> System.InvalidOperationException: MonoTouch does not support dynamic proxy code generation. Override this method or its caller to return specific client proxy instance

Is there any chance to do this another way?

**Comment by denmusic1992** [comment]
If that would be interesting for somebody, I have resolved my issue.
As I mentioned, I didn't have a connection from my iOS device to my WCF service. And after days of searching the info, I tried to connect via physical Android device, not an emulator, and it didn't connect too!

So I investigated, that windows turned on my windows defender.... Lame mistake. After disabling that everything works perfect!

If you'll have such a mistake, please, check your connection from remote device! Hope that will help someone.
