### ISSUE TITLE
CarouselView doesn't update when SelectedItem is changed

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Xamarin.Forms#3029]
### Description
The current implementation of CarouselView in the feature_carouselview branch doesn't update the page or trigger the ItemSelected event when SelectedItem is changed.

### Steps to Reproduce

1. Build NuGet package for feature_carousel branch and use it in your project
2. Create a ContentPage with a CarouselView control
3. In the page constructor, set the CarouselView control's ItemsSource and SelectedItem

### Expected Behavior
Like in a ListView, changing SelectedItem should update the view and trigger the ItemSelected event.

### Actual Behavior
SelectedItem value is updated, but the change is ignored by the CarouselView control and renderer.

### Basic Information
Changes to Position are noticed, and so that's the current workaround.  Looking at the source, CarouselViewRenderer.OnElementPropertyChanged() doesn't handle the case where the PropertyName is SelectedItem.  Looks like this was just an oversight.

- Version with issue:  Xamarin.Forms feature_carouselview branch, View #1882
- Last known good version: New feature
- IDE: VS 2017 v15.7.3
- Platform Target Frameworks:
  - iOS:  11.12.0.4
  - Android: 8.3.3.2
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices:: Android & iOS tested

**Comment by alexrainman** [comment]
SelectedItem is not on my original control. @samhouts can you point me out where/how this was implemented?

**Comment by myroot** [comment]
Because `SelectedItemProperty` BindingMode is OneWayToSource. 
https://github.com/xamarin/Xamarin.Forms/blob/9edefd556939d849ca482702f4d3ff51e487aff8/Xamarin.Forms.CarouselView/CarouselView.cs#L131
It does not intended changing by user/source

**Comment by Magendanz** [comment]
Such an implementation would be inconsistent with CarouselPage, ListView and Picker, which all have getters and setters for the SelectedItem property.

**Comment by alexrainman** [comment]
It can be inconsistent but dont confuse SelectedItem with Position, which i advice to use for what you want.

**Comment by Magendanz** [comment]
In a world dominated by MVVM design patterns, SelectedItem is much more useful than Position.  (And for consistency, it should really be SelectedIndex, right?)

**Comment by alexrainman** [comment]
I am fine with renaming Position to SelectedIndex but that property wasnt designed to be an object but integer and its binding mode should be two ways. The entire architecture of the control depends on that. Maybe thats why it is broken now.

**Comment by alexrainman** [comment]
Integer because express the index of the selected item. Two ways because it will be updated when the user swipe or can be changed in VM to update to programmatically change the selected item. Selected item should be an object that will contain the native android or ios selected view or, if possible, the XF view.

**Comment by alexrainman** [comment]
I really don't understand why such amount of changes in a working code.

**Comment by Magendanz** [comment]
I used to develop WPF controls for the [Microsoft Surface SDK](https://www.microsoft.com/en-us/download/details.aspx?id=26716), and we were pretty obsessive about ensuring consistency in our naming conventions and inheritance so that developers could apply their knowledge of existing controls to new ones.  And while the code may work, I believe there's a higher bar for including it in the Microsoft frameworks.  Arbitrary changes may generate support issues for decades.

**Comment by rmarinho** [comment]
Closing this issue as we will be using `CollectionView` going forward .

Thanks
