### ISSUE TITLE
Button View has been differ in XForms.Android and XForms.iOS

### ISSUE THREAD

**Issue by AshokNatesan** [xamarin/Xamarin.Forms#3035]
### Description
Button View has been differ in XForms.Android and XForms.iOS when add the Image into Button

### Steps to Reproduce

1. Run the sample in both Android and iOS
2. see the width of the button will be differ when add the image within Button

### Expected Behavior
 we expect same view in both Android and ios

### Actual Behavior
Android have some space in both left and right side of the Image but in ios no space.

### Screenshots
[Images.zip](https://github.com/xamarin/Xamarin.Forms/files/2100928/Images.zip)

### Sample:
[SfDataGrid_Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/2100933/SfDataGrid_Sample.zip)

**Comment by StephaneDelcroix** [comment]
iOS and android controls are rendered actively on each platform and, as such, are expected to be different.
