### ISSUE TITLE
Brotli Compression in XF?  When? How?

### ISSUE THREAD

**Issue by dlandi** [xamarin/Xamarin.Forms#3038]
Hi, Brotli Compression was introduced in .Net Core 2.1 
https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/

However, it is not available in .NET Standard 2 which is what I am targeting for all future Xamarin projects.

Question: Is there any way I can get Brotli Compression into an XF/.NET Standard 2 project?

Thanks.

**Comment by samhouts** [comment]
Hi @dlandi! Brotli Compression was added to .NET Standard 1.4, but as far as I can tell, you still need to reference additional packages to get the types (see https://blogs.msdn.microsoft.com/dotnet/2017/07/27/introducing-support-for-brotli-compression/ for more information). 


I'll go ahead and close this as answered for now, but if you run into any snags, feel free to reopen this issue and let us know!

Thanks!

**Comment by samhouts** [comment]
Aaaand I was just informed that this will not work on mobile at this time, but there is an enhancement open to reolve it. You will likely want to follow that issue for updates. Sorry for the confusion! https://github.com/dotnet/corefxlab/issues/1673
