### ISSUE TITLE
[UWP] : Xamarin.Forms 3.0  Items added in Observable Collection are not reflecting in List View.

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#3050]
### Description

 Items added in Observable Collection are not reflection on View.

I have bind Observable Collection to List View.
At the time of binding Observable Collection is null.
Later i added items in Observable Collection but it is not reflecting on View.

### Steps to Reproduce

1. Bind null Observable Collection to List View.
2. Run Project.
3. Add items in to Observable Collection dynamically.
4. Items will not display on View.

### Expected Behavior
Items should display on View.

### Actual Behavior
Items  added in  Observable Collection but not reflecting on View.

### Basic Information

- Version with issue: XF 3.0.0.561731
- Last known good version: XF 3.0.0.482510
- IDE: Microsoft Visual Studio Community 2017
- Platform Target Frameworks: 
 - UWP:  16299 

- Affected Devices: UWP

### Reproduction Link

[Xam.MvvmSolution.zip](https://github.com/xamarin/Xamarin.Forms/files/2105738/Xam.MvvmSolution.zip)

**Comment by PureWeen** [comment]
This will be fixed in 3.1 with this PR
https://github.com/xamarin/Xamarin.Forms/pull/3023

@ashishm29  I tested your sample against the above PR and items displayed


![image](https://user-images.githubusercontent.com/5375137/41479131-674b2456-7087-11e8-9fab-c121493dbc61.png)
