### ISSUE TITLE
ListView ItemSelected ignored

### ISSUE THREAD

**Issue by Maxima078** [xamarin/Xamarin.Forms#3051]
### Description
ListView:
When Binding ItemSource and SelectedItem, if ItemSource is cleared then filled again with same instances the next SelectdItem set will be ignored if it was already set.

### Steps to Reproduce
1. Bind ListView to an ObservableCollection and SelectedItem
2. From the ViewModel, initialize ItemSource and Set SelectedItem to the first item
3. Add a "Reset" button with a Command bound to the ViewModel.
This Command have to clear and fill again the collection with the same instance of your objects (do not re-create them) and finally set SelectedItem to the first item

### Expected Behavior
At first load: The first item should be highlighted
At reset (button): The first item should still be highlighted

### Actual Behavior
At first load: The first item is highlighted
At reset (button): no item is highlighted

I guess since the SelectedItem instance has not changed (it is the same reference) the BindableProperty ignore it and the callback is not called.
But since we first set the ItemSource, ListView.SelectedItem should be set to null automatically. Note I have tested:
- Clear() then Add() again each item in the Collection
- Set the collection to a new instance of ObservableCollection
None of those use-case automatically set SelectedItem to null.
Maybe sometime we wouldn't want the SelectedItem being set to null if we just cleared the collection then add items but the SelectedItem is still in the collection... But when ItemSource is set to a new instance SelectedItem should be set to null.

### Workaround
Two workarounds:
1 - at reset just before setting SelectedItem, set it to null and await Task.Delay(1000)
2 - at reset create new instance of each object in the collection

### Basic Information

- Only tested on Android
- Xamarin.forms 3.1.0.550168-pre3

**Comment by samhouts** [comment]
This is probably a breaking behavior change if we were to address it, but I think it warrants further discussion. Would you mind adding a small sample project that demonstrates this behavior so we can be sure we're talking about the correct behavior? Thanks!

**Comment by Maxima078** [comment]
Here is a sample, let me know if you want me to add information.
[ListViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2111166/ListViewSample.zip)

**Comment by pauldipietro** [comment]
Repro does what is described inside (not highlighting), for upkeep.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
