### ISSUE TITLE
Static resources inside TableView using XAML doesn't work

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#3052]
### Steps to Reproduce

1. Create xamairn forms project 
2. use code below, it crashes that resource cant be found

```
 <ContentPage.Resources>
        <ResourceDictionary>
          <x:String x:Key="caption" >Hello there!</x:String>
        </ResourceDictionary>
      </ContentPage.Resources>

    <TableView>                 
        <TableRoot Title="x">
            <TableSection Title="y">
                <TextCell Text="{StaticResource caption}" />
            </TableSection>
        </TableRoot>
    </TableView>

```

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2017 pro latest update
- Platform Target Frameworks: 
 
  - UWP:  17134 
- Android Support Library Version: 
- Nuget Packages: xamarin forms 3.0.0.561731
- Affected Devices: UWP local

 it was reported long time a go but still not fixed.
 https://forums.xamarin.com/discussion/19526/static-resources-inside-tableview-using-xaml-doesnt-work

**Comment by samhouts** [comment]
[Issue3052.zip](https://github.com/xamarin/Xamarin.Forms/files/2107716/Issue3052.zip)
This did not crash for me. Can you please try the attached project and alter it such that it exhibits the behavior that you're experiencing? Thank you1

**Comment by EmilAlipiev** [comment]
sorry, i found the mistake it was my own coding mistake. i am closing this.
