### ISSUE TITLE
[UWP] ItemTapped and ItemSelected events returning null for Item/SelectedItem in ListView

### ISSUE THREAD

**Issue by weej89** [xamarin/Xamarin.Forms#3056]
### Description
When subscribing to either ItemTapped or ItemSelected events in a ListView both are returning null for the Item (ItemTappedEventArgs.Item) and SelectedItem (SelectedItemChangedEventArgs.SelectedItem).  Seems like this might have something to do with Issue #2996.  Behavior has not been consistent except on pre-release 3.1.0.561732-pre4.  Up until testing this version behavior was resembling something closer the the bug in Issue #2996 where after a few operations on the ObservableCollection it would just continue returning null.

Both iOS and Android seem to work fine.

### Steps to Reproduce

1. Create new .NETStandard Xamarin.Forms Project targeting UWP, iOS, and Android
2. Create page with ListView
3. Bind ListView.ItemsSource to ObservableCollection with data
4. Subscribe to either ItemTapped or ItemSelected events in code
5. Observe that EventArgs for either the Item being Tapped or Selected return null

### Expected Behavior

Should return model data from the ObservableCollection in either Item or SelectedItem property and not null unless set in the case of SelectedItem.

### Actual Behavior

When an item is tapped on the ListView both ItemSelected and ItemTapped argument properties for the data model are null.

### Basic Information

- Version with issue: 3.1.0.561732-pre4
- Last known good version: 3.0.0.482510
- IDE: Visual Studio 2017 Professional for Windows (Ver. 15.7.3)
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages: Prism ver. 7.0.0.396
- Affected Devices: Windows 10 PC

### Reproduction Link

[UWPListViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2107281/UWPListViewIssue.zip)

**Comment by PureWeen** [comment]
This will be fixed in the next 3.1 release with this PR
https://github.com/xamarin/Xamarin.Forms/pull/3023

**Comment by Thorocaine** [comment]
I seem to be having this problem with Xamarin.Forms 5.0.0.2012
