### ISSUE TITLE
Invalid cast in Xamarin.Forms/Xamarin.Forms.Platform.Android/Renderers/NavigationRenderer.cs

### ISSUE THREAD

**Issue by ltaljaard** [xamarin/Xamarin.Forms#3057]
I'm inheriting from NavigationRenderer class for my Android project and overriding this method: protected override void OnElementChanged(ElementChangedEventArgs<NavigationPage> e)

When I call "base.OnElementChanged(e);" it throws an "invalid cast" exception in line 227 of NavigationRenderer.cs. Line 227 is this:

((Platform)Element.Platform).NavAnimationInProgress = true;

When I put a breakpoint there and add the below to the Watch window during runtime:

((Platform)Element.Platform).NavAnimationInProgress

then the result is "Invalid cast".

However when I change it to this the Watch window:

((Xamarin.Forms.Platform.Android.AppCompat.Platform)Element.Platform)

then it returns a valid value (true or false), as the author of NavigationRenderer.cs intended for the cast to work.

So this exception seems to be caused by an ambiguous definition of the Platform class.

The problem can be resolved by specifying the full name (including the prefixes) where the cast is performed on line 227. There are other similar locations where this cast is performed, those locations should be updated as well.

**Comment by samhouts** [comment]
Just to be clear, this exception only happens for you when you are attempting to use your IDE to debug your renderer, correct? Which IDE are you using (e.g., VS 2017, VS for Mac)?

**Comment by PureWeen** [comment]
No updates in the last 30 days. If you're still having an issue please let us know and we can re-open

**Comment by ltaljaard** [comment]
@samhouts It happens from both VS for Mac and VS for Windows latest releases. It happens whether I debug or not, I have just tried to highlight the underlying problem by showing that if I give an unambiguous cast in debug mode it works fine. Meaning to say I think the solution will be to specify the full path in the cast on line 227 of NavigationRenderer.cs

@PureWeen please reopen this call.

**Comment by PureWeen** [comment]
@ltaljaard  are you possibly inheriting from the wrong Navigation Renderer
There's an appcompat one and a non appcompat one. I have a feeling that you are inheriting from the non appcompat one but your running AppCompat.

I've attached a repro with a custom navigation renderer

[NavigationRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2202457/NavigationRenderer.zip)

If you can modify that to demonstrate your issue that would be very helpful

**Comment by PureWeen** [comment]
Closed for inactivity. If you're able to attach a repro then we can reopen.
