### ISSUE TITLE
First page of CarouselView is blank on iOS

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Xamarin.Forms#3058]
### Description
The current implementation of CarouselView in the feature_carouselview branch shows a blank page on iOS for the first item selected.  It stays blank even after navigating away and returning to that page.

### Steps to Reproduce

1. Build NuGet package for feature_carousel branch and use it in your project
2. Create a ContentPage with a CarouselView control
3. In the page constructor, set the CarouselView control's ItemsSource and Position (SelectedItem doesn't work yet)

### Expected Behavior
ItemTemplate should be displayed with bindings to SelectedItem.

### Actual Behavior
Page is entirely blank.

### Basic Information
It works as expected on Android.  On iOS, only the first page is affected.

- Version with issue: Xamarin.Forms feature_carouselview branch, View #1882
- Last known good version: New feature
- IDE: VS 2017 v15.7.3
- Platform Target Frameworks:
  - iOS:  11.12.0.4
  - Android: 8.3.3.2
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: Android & iOS tested

### Screenshots
Observed: (during swipe left)
![observed](https://user-images.githubusercontent.com/2725343/41491330-4d592234-70ad-11e8-81c0-36abf7f4cb94.png)

Expected: (next swipe left)
![expected](https://user-images.githubusercontent.com/2725343/41491335-5d40fc94-70ad-11e8-82cc-e7fde26f54cc.png)

**Comment by alexrainman** [comment]
@samhouts there is a lot of code refactoring and code moved from one place to another. My original code was done in certain way after hours of testing how the each platform specific controls behave. This can be the result of that.

**Comment by rmarinho** [comment]
Hi, closing this issue as we will be using `CollectionView` going forward. 

Thanks.
