### ISSUE TITLE
ListView Crashed with InvalidCast when GroupHeaderTemplate is defined

### ISSUE THREAD

**Issue by POFerro** [xamarin/Xamarin.Forms#3061]
### Description
ListView is throwing an InvalidCastException when a GroupHeaderTemplate is defined
### Steps to Reproduce

1. Having this xaml:
```xml
<ListView ItemsSource="{Binding Categorias}" 
                  GroupDisplayBinding="{Binding Titulo}"
                  GroupShortNameBinding="{Binding Titulo}"
                  IsGroupingEnabled="true">
            <ListView.HeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="*" />
                            <ColumnDefinition Width="*" />
                        </Grid.ColumnDefinitions>

                        <Label Grid.Column="0"
                               Text="Despesas" 
                               HorizontalOptions="Center" />
                        <Label Grid.Column="1"
                               Text="Receitas" 
                               HorizontalOptions="Center" />
                    </Grid>
                </DataTemplate>
            </ListView.HeaderTemplate>
            <ListView.GroupHeaderTemplate>
                <DataTemplate>
                    <Grid>
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition Width="Auto" />
                            <ColumnDefinition Width="*" />
                        </Grid.ColumnDefinitions>

                        <Label Grid.Column="1"
                               Text="{Binding Titulo}" />
                    </Grid>
                </DataTemplate>
            </ListView.GroupHeaderTemplate>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Titulo}" Detail="{Binding RegExpStr}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```
2.  With this Model:
```c#
    public class ViewModel
    {
        public ObservableCollection<Categoria> Categorias { get; set; }
    }
    public class Categoria
    {
        public string Titulo { get; set; }

        public static implicit operator ReadOnlyObservableCollection<SubCategoria>(Categoria d)
        {
            return d.SubCategorias;
        }
        [DataMember()]
        public ObservableCollection<SubCategoria> subCategorias = new ObservableCollection<SubCategoria>();

        [IgnoreDataMember]
        public ReadOnlyObservableCollection<SubCategoria> SubCategorias { get { return new ReadOnlyObservableCollection<SubCategoria>(this.subCategorias); } }

        public Categoria()
        {
        }
    }

    public class SubCategoria
    {
        [IgnoreDataMember]
        public Categoria Categoria { get; private set; }
        public string Titulo { get; set; }
        public string RegExpStr { get; set; }

        public SubCategoria()
        {
        }
    }
```
### Expected Behavior
Should show grouped items in listView

### Actual Behavior
Throws an InvalidCastException
System.InvalidCastException: Specified cast is not valid.
  at at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
  at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].InsertGrouped (System.Object item, System.Int32 index) [0x000a1] in <ce2b877421c54ec290ac8c22bb563f4b>:0
  at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].GroupedReset () [0x00083] in <ce2b877421c54ec290ac8c22bb563f4b>:0
  at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnCollectionChangedGrouped (System.Collections.Specialized.NotifyCollectionChangedEventArgs e) [0x00459] in <ce2b877421c54ec290ac8c22bb563f4b>:0
  at Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].OnProxyCollectionChanged 
...
### Basic Information

- Version with issue:
Looking at current code in GitHub I see the function:
`		TemplatedItemsList<TView, TItem> InsertGrouped(object item, int index)
		{
			var children = item as IEnumerable;

			var groupProxy = new TemplatedItemsList<TView, TItem>(this, children, _itemsView, _itemTemplateProperty);
...
			if (GroupHeaderTemplate != null)
			{
				groupProxy.HeaderContent = (TItem)GroupHeaderTemplate.CreateContent(groupProxy.ItemsSource, _itemsView);
...
`
Should this last cast exist? GroupHeaderTemplate.CreateContent doesn't seem to create an object of type <TItem> isn't it returning a view? Not of type View but some regular View?

Best regards
POFerro

**Comment by PureWeen** [comment]
@POFerro   * ListView.GroupHeaderTemplate* needs to be in a ViewCell

```xml
<ListView.GroupHeaderTemplate>
				<DataTemplate>
					<ViewCell Height="40">
						<Grid>
							<Grid.ColumnDefinitions>
								<ColumnDefinition Width="Auto" />
								<ColumnDefinition Width="*" />
							</Grid.ColumnDefinitions>

							<Label Grid.Column="1"
                               Text="{Binding Titulo}" />
						</Grid>
					</ViewCell>
				</DataTemplate>
			</ListView.GroupHeaderTemplate>
```

Also 
```xml
GroupDisplayBinding="{Binding Titulo}" 
```

Can't also be set if you've specified a GroupHeaderTemplate

**Comment by POFerro** [comment]
Hi PureWeen,

Thank you for your quick answer. That solved it.

Best regards
POFerro
