### ISSUE TITLE
Visual Studio crashing a lot when I create a class in shared project and add a reference.

### ISSUE THREAD

**Issue by anirudhagupta** [xamarin/Xamarin.Forms#3064]
VS 2017 8 previews 2 

write some code or copy paste from somewhere else, just click on the bulb, VS will hang for few seconds and then crash and restarted if you do same light build you will be in the loop of the crash.

If I write namespace manually by typing, things will be fine otherwise it's crashing always with the lightbulb.

**Comment by kingces95** [comment]
@anirugu Could you use Camtasia to capture a video of the steps you take before it crashes as well as attach the solution?

**Comment by anirudhagupta** [comment]
@PureWeen maybe this https://developercommunity.visualstudio.com/content/problem/274932/visual-studio-crash-on-stream-written-in-my-code.html

**Comment by PureWeen** [comment]
That's a better place for dealing with this kind of issue. If you can provide them a repro there that would be helpful. 

I'd recommend going through the steps they have listed there with the feedback collector to provide them with some additional info
