### ISSUE TITLE
Not adding xaml file visual studio 2017(Version 15.7.4)

### ISSUE THREAD

**Issue by PinkoAgrawal** [xamarin/Xamarin.Forms#3067]
### Description
After updating visual studio to 15.7.4, When adding content page in Shared project it is not getting added throwing exception.
### Steps to Reproduce
1. Create new project on xamarin forms(I am not adding UWP proj)
2. In shared project try adding ContentPage 
3. It is not getting added throwing exception.

### Expected Behavior
Content page should add along with .xaml file 
### Actual Behavior
Content page not adding at all throwing exception & sometimes adding only .xaml,.cs file only.
### Basic Information
Microsoft Visual Studio Enterprise 2017 
Version 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA519
Microsoft Architecture Diagrams and Analysis Tools

Application Insights Tools for Visual Studio Package   8.12.10405.1
Application Insights Tools for Visual Studio

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

C# Tools   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

TypeScript Tools   15.7.20419.2003
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Web Extension Pack 2017   15.0.4
The easiest way to set up Visual Studio for the ultimate web development experience.

Xamarin   4.10.10.2 (35a01d8dc)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
- Version with issue: VS2017 15.7.4
- Last known good version: VS2017 15.7.2
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![contenzpageexp](https://user-images.githubusercontent.com/38238586/41580992-abf41564-73ba-11e8-9cc5-78a2d8326278.png)

### Reproduction Link

LogFile:
[VsProjectFault_93d1bb7a-b050-46c1-b330-7660ccefa790.failure.txt](https://github.com/xamarin/Xamarin.Forms/files/2114129/VsProjectFault_93d1bb7a-b050-46c1-b330-7660ccefa790.failure.txt)

**Comment by PinkoAgrawal** [comment]
I have added log file too please through it.

**Comment by kzu** [comment]
@davkean who owns the shared project system?

**Comment by PinkoAgrawal** [comment]
Where are you xamarin people I am wasting my time everyday, Despite that I am unable to add Content Page.

**Comment by kzu** [comment]
Looping @joj who will follow up shortly.

FWIW, I do have a repro with our cross platform template.

**Comment by PinkoAgrawal** [comment]
Not getting, do you need that issue link?

**Comment by davkean** [comment]
Yes, a link to the issue on VS Developer Community.

@kzu @joj This looks similar to: https://github.com/dotnet/project-system/pull/3496, but TBH unsure write now if Shared Projects are using our Page.xaml rule or UWP's.

**Comment by PinkoAgrawal** [comment]
https://developercommunity.visualstudio.com/content/problem/276069/throwing-expection-adding-new-content-page.html

Please check it.

**Comment by kzu** [comment]
I cannot reproduce this anymore in the latest 15.8 Preview.
