### ISSUE TITLE
Android button borders not rendering

### ISSUE THREAD

**Issue by bijington** [xamarin/Xamarin.Forms#3068]
### Description

Borders on `Button`s in Android do not appear to be rendering.

According to the documentation for `BorderColor` on a `Button` found [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.button.bordercolor?view=xamarin-forms):
"This property has no effect if BorderWidth is set to 0. On Android this property will not have an effect unless BackgroundColor is set to a non-default color."

There is a slight added complexity that the control I am using inherits from Button to incorporate some of our internal logic however this should not be affecting the rendering.

### Steps to Reproduce

1. Implement a ButtonRenderer as per the attached sample solution.

[BorderIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2131110/BorderIssue.zip)

2. Create a **Button** and set the following properties:

     ```
    CornerRadius = 1;
    BackgroundColor = Color.Yellow;
    BorderWidth = 5;
    BorderColor = Color.Red;
   ```

3. Witness that on Android the border is not rendered but on UWP is it.

### Expected Behavior

A red border should be rendered.

### Actual Behavior

No border is rendered on Android whereas on UWP it does.

### Basic Information

- Version with issue: **3.0.0.561731**
- Last known good version: **unknown**
- IDE: **Visual Studio 2017 (15.7.3)**
- Platform Target Frameworks: 
  - iOS:  
  - Android: **8.3.3.2**
  - UWP:  **17134**
- Android Support Library Version: **27.0.2** _(27.0.2.1 is available however I am having difficulty updating to it.)_
- Nuget Packages: **Xamarin.Forms (3.0.0.561731)**
- Affected Devices: **Blackview A8 Max (Android version 6.0)**

### Screenshots

![img_1497](https://user-images.githubusercontent.com/17139988/41528636-872bc336-72e2-11e8-98b2-49b63f3a81b7.JPG)

### Reproduction Link

N/A

**Comment by kingces95** [comment]
@bijington if you could attach a reproduction, we'd appreciate it.

**Comment by bijington** [comment]
@kingces95 I may have jumped the gun early on raising this bug. It appears that it is something relating to my `ButtonRenderer` class that is causing the issue. I have attached a solution in case it is an issue still. I am inheriting from the Xamarin renderer and not interfering with anything Border related (well I don't believe I am) so I wouldn't expect to see this behaviour.

[BorderIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2127543/BorderIssue.zip)

**Comment by kingces95** [comment]
Behavior not quite as described on master however visual effect markedly different between UAP and Android when specifying a button boarder color (regardless of Button subclassing). On Android there is no boarder, on UAP there is.

**Comment by kingces95** [comment]
@bijington Would you mind updating the reproduction steps to reflect the results of your investigation? That way, when this bug get to the top of the stack, we know we're addressing your issue. Specifically, what behavior is unexpected in the subclassed button vs non-subclassed button.

**Comment by bijington** [comment]
@kingces95 I have update the reproduction steps to match what I discovered during creating the sample project. I hope it helps.

**Comment by 07101994** [comment]
I think this issue is not reproducible on the master branch.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by bijington** [comment]
I'm happy for this to be closed down. It's been quite some time since I raised it and I don't think I am able to reproduce it anymore

**Comment by samhouts** [comment]
Thank you!
