### ISSUE TITLE
Exception when creating BindableProperty with BindingMode.OneTime

### ISSUE THREAD

**Issue by hshristov** [xamarin/Xamarin.Forms#3071]
### Description

When creating a BindableProperty with BindingMode.OneTime an exception is thrown. The exception is `Not a valid type of BindingMode
Parameter name: defaultBindingMode`

### Steps to Reproduce

1. Create new Xamarin.Forms blank app
2. In the MainPage.xaml.cs add the following line inside the MainPage class:
```
public static BindableProperty TextProperty =
            BindableProperty.Create("Text", typeof(string), typeof(MainPage), null, BindingMode.OneTime);
```
3. Run the app

or

1. Download the attached zip.
2. Run the app

### Expected Behavior
The app should not crash.

### Actual Behavior
An exception is thrown.

### Basic Information

- Version with issue: Xamarin.Forms 3.0.0.561731
- Last known good version: Not sure
- IDE: Visual Studio Enterprise 2017 for Mac Preview (7.6 build 947)
- Platform Target Frameworks: It is crash in Xamarin.Forms so I think it applies to all platforms.
- Nuget Packages: The default one coming with Xamarin.Forms Blank App template
- Affected Devices: all

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2111528/Archive.zip)

**Comment by StephaneDelcroix** [comment]
This was fixed in master as part of #1850. Creating a patch for 3.0.0 and 3.1.0...

**Comment by opcodewriter** [comment]
@StephaneDelcroix  Maybe add some unit tests to catch some simple issues?

**Comment by hshristov** [comment]
Thanks @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
@opcodewriter it's tested on master. adding tests in this backport will make it harder to merge later on
