### ISSUE TITLE
Button behavior when soft keyboard is open is inconsistent

### ISSUE THREAD

**Issue by eric99r** [xamarin/Xamarin.Forms#3072]
### Description

When typing in entry fields, a soft keyboard appears in both platforms. 
In both platforms if you want to close the keyboard by tapping the screen, it closes with one exception in behavior.

Android: If you tap on a button while the keyboard is open, it launches a pressed/clicked/released button event **and** the VM command fires.

IOS: If you tap on a button while the keyboard is open, it launches a pressed/clicked/released button event **but** the VM command doesn't fire.

### Steps to Reproduce

1. Tap on an entry field to open the soft keyboard 
2. Scroll down to a button 
3. Tap the button while the keyboard is still open

### Expected Behavior
Button commands should always fires if buttons are being pressed

### Actual Behavior
Button commands doesn't fire

### Basic Information

- Last known good version: N/A
- IDE: Visual Studio Enterprise 2017
  - iOS:  11.3
  - Android: API 23

**Comment by kingces95** [comment]
@eric99r If you could attach a reproduction, we'd appreciate it.

**Comment by PureWeen** [comment]
@eric99r  I tested this locally and for me the button event fired when the soft keyboard was open. I'm going to close this for now and if you are still having the issue please attach a repro
