### ISSUE TITLE
WebView shows blank screen with XF3.0

### ISSUE THREAD

**Issue by LGFox** [xamarin/Xamarin.Forms#3073]
### Description
Xamarin.Forms WebView control doesn't apply custom port in URL on iOS and shows blank screen.

### Steps to Reproduce
1. Create empty Xamarin.Forms app.
2. In xaml add <WebView Source="http://portquiz.net:8080/" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" />
3. Run it on iOS.

### Expected Behavior
The page is opened. (It does on Android)

### Actual Behavior
Blank screen displayed.

### Basic Information
- Version with issue:  Xamarin.Forms.3.0.0.561731
- Last known good version: --
- IDE: VisualStudio 2017 15.7.2
- Affected Devices: Checked on iPhone 7 Plus

### Reproduction Link
https://github.com/LGFox/WebView.Bug

**Comment by kingces95** [comment]
@rmarinho I'm going to assume you triaged this given you self-assigned it. Lemme know if that's not the case.

**Comment by davidhardie** [comment]
Sadly this also drops any url based basic authentication.
url of “https://user:pwd@server.com/resource” drops the user:pwd part.
This worked on Xamarin 2.5 (cant confirm if 3.0 was affected, but 3.1 was tested and the url is changed, dropping the creds.

Will this change also include a fix for this use case?
