### ISSUE TITLE
Nightly builds are not nightly

### ISSUE THREAD

**Issue by pfedotovsky** [xamarin/Xamarin.Forms#3075]
Currently, the last nightly build (https://myget.org/feed/xamarinforms-ci/package/nuget/Xamarin.Forms) is dated May, 19th. 
It would be nice to have real nightly builds, which are much more frequent. For instance, I'd like to try the following change: https://github.com/xamarin/Xamarin.Forms/issues/2993, but no package contains it.

**Comment by hartez** [comment]
The nightly builds are only pushed if they pass all of our automated tests. We are in the process of transitioning to a new automated test system, and some of our tests are being temperamental. Once we've ironed out the automated testing issues, the nightly builds should be coming out at a more regular pace.
