### ISSUE TITLE
Horizontal text alignment is treated differently in Android and iOS for Labels with arabic content

### ISSUE THREAD

**Issue by dirivero** [xamarin/Xamarin.Forms#3077]
### Description

HorizontalTextAlignment on Labels behaves differently in iOS and Android when the label contains arabic text.

### Steps to Reproduce

Open attached project, compile and run in Android & iOS to see the rendering differences.

Code is just this:
```
<StackLayout Margin="0,50">
    <Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Start" />
    <Label Text="مرحبًا بكم في Xamarin.Forms!" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Start" />
</StackLayout>
```

Note: it doesn't matter whether this is included in Android's manifest or not: `android:supportsRtl="true"`

### Actual Behavior

In Android, the arabic text inverts the text alignment whereas in iOS the text alignment defined by the programmer is honored.

### Expected Behavior

Both platforms should behave the same. 

I believe that making the alignment dependent on the label content makes it difficult if you have apps with mixed content (or multiple language support). For instance, regular numbers are treated as LTR text and they are used in arabic applications so if you have to display a list of data and some are numbers the layout may suffer unless you invert the text alignment just for numbers. It may be even harder if you don't know exactly if the data to show is arabic or not. 

For that, I'd prefer that Android behaves as iOS does and not the other way round, or at least have an option to get the current iOS behavior everywhere.

### Basic Information

- Version with issue: 3.0.0.561731 and 3.1.0.561732-pre4
- Last known good version: 2.5.1.527436
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS:  11.4
  - Android: tried with Android 6 and 8
- Android Support Library Version: 27.0.2.1
- Affected Devices: Android simulators

### Screenshots

iOS:
![image](https://user-images.githubusercontent.com/7670773/41565746-6dfdb4a4-732e-11e8-80c7-47aa933b9ddc.png)

Android:
![image](https://user-images.githubusercontent.com/7670773/41565758-7d95ccc6-732e-11e8-8398-fc998e883cb7.png)

### Reproduction Link

[TextAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/2113198/TextAlignment.zip)

**Comment by kingces95** [comment]
Behavior is as described on master.

**Comment by RezaNorouzians** [comment]
i have the same error , could you please help me :(
my project works fin in ios but in android alignement is reverse for persian text.

**Comment by dirivero** [comment]
A possible workaround to get a consistent behavior is to write a simple custom renderer that forces the Android's TextDirection of the label to TextDirection.Ltr:
https://developer.xamarin.com/api/field/Android.Views.TextDirection.Ltr

Hope that helps.

**Comment by RezaNorouzians** [comment]
> A possible workaround to get a consistent behavior is to write a simple custom renderer that forces the Android's TextDirection of the label to TextDirection.Ltr:
> https://developer.xamarin.com/api/field/Android.Views.TextDirection.Ltr
> 
> Hope that helps.

thank you so much my friend , but i did not find any TextDirection property for lable control. i dont know how can i solve it.

**Comment by RezaNorouzians** [comment]
[assembly: ExportRenderer(typeof(CustomLabel), typeof(CustomLabelRenderer))]
namespace Canpars.Droid.CustomRender
{
    public class CustomLabelRenderer : LabelRenderer
    {
        public CustomLabelRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
        {
            base.OnElementChanged(e);
            var view = (CustomLabel)Element;
            if (view == null) return;

            view.FontSize = 30;
           !!!!  There is no attribute for label control to set textdirection
        }  

    }
}

**Comment by dirivero** [comment]
You can access the android control through `this.Control` property. Try this:

```Control.TextDirection = Android.Views.TextDirection.Ltr;```

**Comment by RezaNorouzians** [comment]
> Control.TextDirection = Android.Views.TextDirection.Ltr;

i did , but the label still on the same place and not move .

thank you so much

**Comment by RezaNorouzians** [comment]
finaly i found the solution , i put each lable in one stacklayout with property HorizontalOptions=end then it works.
for ios and android it works ;)

 <StackLayout HorizontalOptions="End">
                <Label Text="Hi" HorizontalTextAlignment="End"></Label>                              
  </StackLayout>
  <StackLayout  HorizontalOptions="End">
                <Label Text="سلام" HorizontalTextAlignment="End"></Label>
   </StackLayout>

**Comment by RezaNorouzians** [comment]
<StackLayout HorizontalOptions="End">
                <Label Text="Hi" HorizontalTextAlignment="End"></Label>                              
</StackLayout>
<StackLayout  HorizontalOptions="End">
                <Label Text="سلام" HorizontalTextAlignment="End"></Label>
</StackLayout>

**Comment by khalidhex** [comment]
Any updates about this issue ?

**Comment by babuljamkhande** [comment]
> > Control.TextDirection = Android.Views.TextDirection.Rtl;
> > Control.Gravity = Android.Views.GravityFlags.Right;
> 
> By using above two lines in my Android CustomLabelRenderer was able to resolve the issue. Please follow below gist for code reference.
> 
> https://gist.github.com/hamid-shaikh/dddc717e5d3c847361f4b6576d8d5df6
> https://gist.github.com/hamid-shaikh/0565a7aafdeb5551c0caf1de6342e839

@hamid-shaikh 
Thanks a lot for sharing fix for alignment issue, using this was able to resolve similar issue in my project which i was facing for quite long.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by dirivero** [comment]
It seems to be working fine now. Thanks!

**Comment by matteofabris** [comment]
This issue is still present just as in the original description.
