### ISSUE TITLE
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.XXXRenderer from native handle

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Xamarin.Forms#3080]
### Basic Information
- Version with issue: Latest
- Affected Platform: Android (versions from log: 5.0 - 8.0)

### Log

<pre>Xamarin Exception Stack:
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.ScrollViewRenderer from native handle 0xffb1b1cc (key_handle 0x5bbb241).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Android.Views.View.n_OnDetachedFromWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <263adecfa58f4c449f1ff56156d886fd>:0
  at (wrapper dynamic-method) System.Object.f6b7326d-602e-4d8c-83ea-a38d8b496124(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.ScrollViewRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <263adecfa58f4c449f1ff56156d886fd>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <263adecfa58f4c449f1ff56156d886fd>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md51558244f76c53b6aeda52c8a337f2c37.ScrollViewRenderer.n_onDetachedFromWindow(Native Method)
      at md51558244f76c53b6aeda52c8a337f2c37.ScrollViewRenderer.onDetachedFromWindow(ScrollViewRenderer.java:91)
      at android.view.View.dispatchDetachedFromWindow(View.java:16769)
      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3428)
      at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:5153)
      at android.view.ViewGroup.removeAllViews(ViewGroup.java:5099)
      at md5f493dec2f3f35774ee989aaa40ef64fd.MainActivity.n_onCreate(Native Method)
      at md5f493dec2f3f35774ee989aaa40ef64fd.MainActivity.onCreate(MainActivity.java:44)
      at android.app.Activity.performCreate(Activity.java:6955)
      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
      at android.app.ActivityThread.-wrap14(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6776)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
</pre>

**Comment by kingces95** [comment]
@paleicikas If you could attach a reproduction, we'd appreciate it.

**Comment by PureWeen** [comment]
@paleicikas  is the scrollview part of a listview at all?

**Comment by paleicikas** [comment]
The same with MasterDetailPageRenderer, thousands of: 

<pre>System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer from native handle 0x8090001d (key_handle 0x423b7250).
  at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x0017d] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) [0x000b9] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object._GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00017] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00000] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Java.Lang.Object.GetObject[T] (System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00006] in <263adecfa58f4c449f1ff56156d886fd>:0
  at Android.Views.View.n_OnDetachedFromWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00000] in <263adecfa58f4c449f1ff56156d886fd>:0
  at (wrapper dynamic-method) System.Object.97b97cd4-2244-4eef-9889-8324d358cfb8(intptr,intptr)
--- End of inner exception stack trace ---
  System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
    at Java.Interop.TypeManager.CreateProxy (System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) [0x00054] in <263adecfa58f4c449f1ff56156d886fd>:0
    at Java.Interop.TypeManager.CreateInstance (System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) [0x00111] in <263adecfa58f4c449f1ff56156d886fd>:0
  --- End of inner exception stack trace ---
    Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
      at Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
      at java.lang.Error: Java callstack:
      at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.n_onDetachedFromWindow(Native Method)
      at md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.onDetachedFromWindow(MasterDetailPageRenderer.java:60)
      at android.view.View.dispatchDetachedFromWindow(View.java:13392)
      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2793)
      at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4236)
      at android.view.ViewGroup.removeAllViews(ViewGroup.java:4180)
      at md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.n_onDestroy(Native Method)
      at md51558244f76c53b6aeda52c8a337f2c37.FormsAppCompatActivity.onDestroy(FormsAppCompatActivity.java:80)
      at android.app.Activity.performDestroy(Activity.java:5623)
      at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1123)
      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3693)
      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3724)
      at android.app.ActivityThread.access$1500(ActivityThread.java:169)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:136)
      at android.app.ActivityThread.main(ActivityThread.java:5476)
      at java.lang.reflect.Method.invokeNative(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:515)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
      at dalvik.system.NativeStart.main(Native Method)
</pre>

Sorry, the is not way attach a reproduction (to much logic).

**Comment by paleicikas** [comment]
@PureWeen no, scrollview not used in listview (header or footer)

**Comment by tekinc** [comment]
Anyone have any work around for this?

**Comment by samhouts** [comment]
@tekinc We've been unable to pinpoint the cause as of yet, since we do not have a project that reproduces the problem. Do you have a sample project you can share? Thank you!

**Comment by pauldipietro** [comment]
Due to a lack of updates or comments for over 30 days, this will be closed. Please reopen this with a sample project as requested if the issue still occurs with the latest stable/nightly release of Forms. Thanks!

**Comment by PureWeen** [comment]
Just a quick note @paleicikas  sent me a project privately that he's working with me on to see if I can recreate.

That being said if anyone can create a repro for this here that would be great!

**Comment by eschragw** [comment]
I see this issue when I have a scrollview in a child page. When I background the app and then resume the app, the app will crash with that error. I can consistently replicate this issue in our main app. If you need more info, I can try to replicate it in a smaller project to provide as a sample.

**Comment by PureWeen** [comment]
@eschragw  if you can that would be really helpful!

I've tried to recreate this one but haven't had any luck as of yet

**Comment by radioactiveman** [comment]
@eschragw Are you using MvvmCross in your project by any chance?

**Comment by eschragw** [comment]
@PureWeen @radioactiveman I am using MvvmCross. My error when away when I corrected my app from having NoHistory set to true. The page with the scrollview was on a modal view. Things have gotten hectic, so I have not been able to create a sample project. I might be able to get to it this if you guys are weren't able to repro.

**Comment by Mustafa7070** [comment]
i have same problem her:
"System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.ImageButtonRenderer from native handle... "

Android: 8.1.0 Android Build: OPM1.171019.026 Manufacturer: OPPO Model: RMX1811

**Comment by PureWeen** [comment]
@Mustafa7070  do you have a reproduction or an app you can provide so I can see and fix the issue?

**Comment by Mustafa7070** [comment]
@PureWeen  ok , i will ask my manager 
and here is the view where i am using ImageButton

https://drive.google.com/file/d/1Rk8BxYUV7u-C-ElUa0lk1z7DOSFxRpZt/view?usp=sharing

**Comment by lassana** [comment]
Does anyone know a workaround for this?

**Comment by PureWeen** [comment]
@lassana the cases for this vary a lot. It's similar to only having a NullReferenceException. There isn't really a core issue this comes from. If you have a repro of your scenario and can open a new issue we can look at fixing it for your particular case

**Comment by lassana** [comment]
@PureWeen thanks for replying! I've got 100% reproducible sample. Creating a new issue...

**Comment by lassana** [comment]
I created https://github.com/xamarin/Xamarin.Forms/issues/5894 with a repro.

**Comment by Monikaprime** [comment]
09-18 19:40:51.549 W/prime.craftdev(26714): Accessing hidden method Landroid/view/View;->getTransitionAlpha()F (light greylist, reflection)
09-18 19:40:51.576 W/prime.craftdev(26714): Accessing hidden method Landroid/text/SpannableStringInternal;->length()I (light greylist, JNI)
09-18 19:40:51.618 W/prime.craftdev(26714): Accessing hidden field Landroid/view/View;->mViewFlags:I (light greylist, reflection)
09-18 19:40:51.621 W/prime.craftdev(26714): Accessing hidden method Landroid/view/View;->setTransitionAlpha(F)V (light greylist, reflection)
09-18 19:40:51.623 W/prime.craftdev(26714): Accessing hidden method Landroid/view/ViewGroup;->suppressLayout(Z)V (light greylist, reflection)
09-18 19:40:51.626 W/prime.craftdev(26714): Accessing hidden method Landroid/view/View;->setLeftTopRightBottom(IIII)V (light greylist, reflection)
09-18 19:40:52.809 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:52.904 I/chatty  (26714): uid=10149(prime.craftdev) identical 2 lines
09-18 19:40:52.919 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:53.628 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:53.630 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:53.755 I/prime.craftdev(26714): Explicit concurrent copying GC freed 14428(773KB) AllocSpace objects, 21(420KB) LOS objects, 49% free, 3MB/6MB, paused 71us total 22.912ms
09-18 19:40:53.758 D/Mono    (26714): GC_TAR_BRIDGE bridges 317 objects 25456 opaque 11374 colors 317 colors-bridged 317 colors-visible 317 xref 6 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.10ms tarjan 11.07ms scc-setup 0.07ms gather-xref 0.01ms xref-setup 0.00ms cleanup 1.05ms
09-18 19:40:53.758 D/Mono    (26714): GC_BRIDGE: Complete, was running for 26.54ms
09-18 19:40:53.758 D/Mono    (26714): GC_MINOR: (Nursery full) time 21.86ms, stw 23.11ms promoted 1276K major size: 16176K in use: 8102K los size: 7168K in use: 4265K
09-18 19:40:53.991 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{c47a171 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:54.026 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ......I. 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:54.898 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{ae18e41 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:54.933 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:55.111 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:55.112 I/chatty  (26714): uid=10149(prime.craftdev) identical 1 line
09-18 19:40:55.138 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:55.714 I/prime.craftdev(26714): Explicit concurrent copying GC freed 7814(523KB) AllocSpace objects, 6(120KB) LOS objects, 50% free, 3MB/7MB, paused 76us total 25.729ms
09-18 19:40:55.717 D/Mono    (26714): GC_TAR_BRIDGE bridges 290 objects 34986 opaque 15069 colors 290 colors-bridged 290 colors-visible 290 xref 3 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.11ms tarjan 13.84ms scc-setup 0.06ms gather-xref 0.01ms xref-setup 0.03ms cleanup 1.62ms
09-18 19:40:55.717 D/Mono    (26714): GC_BRIDGE: Complete, was running for 29.74ms
09-18 19:40:55.717 D/Mono    (26714): GC_MINOR: (Nursery full) time 24.38ms, stw 26.02ms promoted 1300K major size: 16176K in use: 9512K los size: 15360K in use: 11853K
09-18 19:40:55.753 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:55.754 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:55.758 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{37c0fb3 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:55.774 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:55.787 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:56.320 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:56.321 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:56.325 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{e5f52c9 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:56.346 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:56.356 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:56.676 D/Mono    (26714): GC_BRIDGE waiting for bridge processing to finish
09-18 19:40:56.704 I/prime.craftdev(26714): Explicit concurrent copying GC freed 7677(503KB) AllocSpace objects, 3(60KB) LOS objects, 50% free, 3MB/7MB, paused 110us total 25.732ms
09-18 19:40:56.708 D/Mono    (26714): GC_TAR_BRIDGE bridges 845 objects 925 opaque 126 colors 845 colors-bridged 845 colors-visible 845 xref 50 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.16ms tarjan 0.51ms scc-setup 0.39ms gather-xref 0.03ms xref-setup 0.08ms cleanup 0.21ms
09-18 19:40:56.708 D/Mono    (26714): GC_BRIDGE: Complete, was running for 32.47ms
09-18 19:40:56.708 D/Mono    (26714): GC_MAJOR: (LOS overflow) time 46.49ms, stw 49.14ms los size: 9216K in use: 1067K
09-18 19:40:56.708 D/Mono    (26714): GC_MAJOR_SWEEP: major size: 11296K in use: 8861K
09-18 19:40:57.775 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{a304112 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:57.806 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:58.027 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:58.028 I/chatty  (26714): uid=10149(prime.craftdev) identical 1 line
09-18 19:40:58.047 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:58.547 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:58.548 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:58.552 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{d14fc12 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:58.569 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:58.579 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:58.884 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{850d109 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:58.902 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:40:58.996 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:59.008 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:40:59.076 I/prime.craftdev(26714): Explicit concurrent copying GC freed 15234(860KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 3MB/7MB, paused 74us total 26.104ms
09-18 19:40:59.077 D/Mono    (26714): GC_TAR_BRIDGE bridges 303 objects 306 opaque 1 colors 303 colors-bridged 303 colors-visible 303 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.07ms tarjan 0.09ms scc-setup 0.06ms gather-xref 0.01ms xref-setup 0.03ms cleanup 0.08ms
09-18 19:40:59.077 D/Mono    (26714): GC_BRIDGE: Complete, was running for 28.38ms
09-18 19:40:59.077 D/Mono    (26714): GC_MINOR: (Nursery full) time 9.76ms, stw 11.78ms promoted 972K major size: 11648K in use: 9910K los size: 9216K in use: 2462K
09-18 19:40:59.911 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{1a24c7c V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:40:59.934 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ......ID 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:00.065 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.066 I/chatty  (26714): uid=10149(prime.craftdev) identical 1 line
09-18 19:41:00.087 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.412 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.412 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.416 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{d508190 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:00.430 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.443 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:00.765 I/prime.craftdev(26714): Explicit concurrent copying GC freed 14655(759KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/7MB, paused 62us total 26.304ms
09-18 19:41:00.768 D/Mono    (26714): GC_TAR_BRIDGE bridges 258 objects 50241 opaque 20560 colors 258 colors-bridged 258 colors-visible 258 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.11ms tarjan 22.25ms scc-setup 0.06ms gather-xref 0.01ms xref-setup 0.05ms cleanup 2.12ms
09-18 19:41:00.768 D/Mono    (26714): GC_BRIDGE: Complete, was running for 30.43ms
09-18 19:41:00.769 D/Mono    (26714): GC_MINOR: (Nursery full) time 34.54ms, stw 36.43ms promoted 1353K major size: 12976K in use: 11376K los size: 9216K in use: 2462K
09-18 19:41:00.844 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.845 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.849 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{f2421b5 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:00.919 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:00.953 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... .......D 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:01.791 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:01.792 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:01.795 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{44ac9bb V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:01.812 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:01.822 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:02.066 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{746c4fd V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:02.127 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:02.128 I/chatty  (26714): uid=10149(prime.craftdev) identical 1 line
09-18 19:41:02.138 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:02.145 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:02.273 I/prime.craftdev(26714): Explicit concurrent copying GC freed 16718(950KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/7MB, paused 73us total 26.327ms
09-18 19:41:02.277 D/Mono    (26714): GC_TAR_BRIDGE bridges 289 objects 48117 opaque 19843 colors 289 colors-bridged 289 colors-visible 289 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.08ms tarjan 19.94ms scc-setup 0.06ms gather-xref 0.01ms xref-setup 0.03ms cleanup 2.83ms
09-18 19:41:02.277 D/Mono    (26714): GC_BRIDGE: Complete, was running for 31.28ms
09-18 19:41:02.277 D/Mono    (26714): GC_MINOR: (Nursery full) time 31.45ms, stw 33.34ms promoted 1223K major size: 14208K in use: 12696K los size: 9216K in use: 2462K
09-18 19:41:02.414 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:02.417 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{9524cdd V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:02.433 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:02.449 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:03.477 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{6095030 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:03.500 W/View    (26714): requestLayout() improperly called by md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer{2d32db1 V.E...... ........ 0,0-1080,1947 #8a5} during second layout pass: posting in next frame
09-18 19:41:03.694 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:03.695 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:03.902 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:03.902 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:03.906 W/View    (26714): requestLayout() improperly called by md51558244f76c53b6aeda52c8a337f2c37.ScrollViewContainer{3503fe6 V.E...... ......ID 0,0-1080,843} during layout: running second layout pass
09-18 19:41:03.919 W/StaticLayout(26714): maxLineHeight should not be -1.  maxLines:1 lineCount:1
09-18 19:41:03.964 I/prime.craftdev(26714): Explicit concurrent copying GC freed 17480(925KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 3MB/7MB, paused 74us total 26.756ms
09-18 19:41:03.965 D/Mono    (26714): GC_TAR_BRIDGE bridges 302 objects 395 opaque 54 colors 302 colors-bridged 302 colors-visible 302 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.07ms tarjan 0.16ms scc-setup 0.05ms gather-xref 0.01ms xref-setup 0.02ms cleanup 0.10ms
09-18 19:41:03.965 D/Mono    (26714): GC_BRIDGE: Complete, was running for 28.97ms
09-18 19:41:03.965 D/Mono    (26714): GC_MINOR: (Nursery full) time 8.11ms, stw 10.51ms promoted 1007K major size: 15248K in use: 13782K los size: 9216K in use: 2462K
Unhandled Exception:

System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer from native handle 0x7fca8de8f4 (key_handle 0xb386ba9).

**Comment by johnshardman** [comment]
Also getting this (for ImageButtonRenderer) after upgrading to XF 4.5.0.356 . Didn't happen before upgrading (for completeness, I also updated a few other NuGets at the same time, but none that interact with ImageButtons).

System.NotSupportedException
  Message=Unable to activate instance of type Xamarin.Forms.Platform.Android.ImageButtonRenderer from native handle 0x7fcb2a3564 (key_handle 0x4dc4486).
