### ISSUE TITLE
HttpClient bug on Android emulator

### ISSUE THREAD

**Issue by lander1337** [xamarin/Xamarin.Forms#3084]
### Description
When I try to get SOAP message from service using HttpClient, xml that I read with HttpResponseMessage.Content.ReadAsStringAsync() sometimes(random) is broken, tags miss latters or '>' simbol. Was checking traffic with fiddler, service return valid xml, so the problem some where on HttpClient.    
 
### Steps to Reproduce
0. Use Android emulator
1. Create/use service that return xml.
2. Create app that using System.Net.Http.HttpClient for get info from service.
3. Make request to service, read string from response, and sometimes for some reason this "xml-string" would be broken.

### Expected Behavior
For example, service return:

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://free-web-services.com/soap">
<SOAP-ENV:Body>
        <ns1:addResponse>
            <sum>8</sum>
            <time>0.0002</time>
        </ns1:addResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

So i expect same xml, when read it from response.

### Actual Behavior
Service return same xml as expected(check with fiddler), but when read it from response i get(sometimes):

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://free-web-services.com/soap">
    <SOAP-ENV:Body>
        <ns1:addResponse>
            <sum>8</sum>
            <time>0.0002</time>
        </ns1:addResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope

There is no '>' at last tag.

### Basic Information
This bug happends in ~30% of request, sometimes it get valid xml. In my example, missing letter is same every time('>'). Xml's that i get from my service is large(length ~ 200k), it could be missed latter(should be <ComputerID></ComputerID>, i get <ComputerID></ComputeID>). Sorry for bad English. 

- Version with issue: 3.0.0.446417
- IDE: VS Community 2017 15.7.1
- Platform Target Frameworks: 
  - Android(Emulator): 
    -Work as expected - Android 4.4
    -Bug reporoduce - Android 6.0, Android 7.1, Android 8.1 
- Affected Devices: Face this bug only on emulator(normal devices works good)

**Comment by StephaneDelcroix** [comment]
Thanks for reporting this, and sorry for the very late answer. Xamarin.Forms doesn't provide, or support, the HttpClient, but make use of the one provided by the Xamarin.Android framework.

If the problem still happens, you should try to report the issue there.

**Comment by lander1337** [comment]
If somebody will face same problem, u can check state about this bug [here](https://github.com/xamarin/xamarin-android/issues/2569).
