### ISSUE TITLE
Arabic characters are unreadable

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3094]
Hi,

The Arabic characters are unreadable in Visual Studio for Mac.

It's a pain...

Hope this will be resolved soon..

Thanks,
jassim

**Comment by GalaxiaGuy** [comment]
If the problem is just in the editor, it is probably better to report it here:
https://github.com/mono/monodevelop/issues

**Comment by pauldipietro** [comment]
https://github.com/mono/monodevelop/issues/5121
