### ISSUE TITLE
[Android] Bottom Tab Bar Customization

### ISSUE THREAD

**Issue by acastr7** [xamarin/Xamarin.Forms#3096]
### Description
The current android TabbedPageRenderer implementation takes advantage of `FormsAppCompatActivity.TabLayoutResource` to allow us to customize how we want the tabs to appear. There needs to be a `FormsAppCompatActivity.BottomTabLayoutResource` to allow us to customize the bottom bar appearance. 

The tablayout gets instantiated like so:

```
TabLayout tabs;
if (FormsAppCompatActivity.TabLayoutResource > 0)
   tabs = _tabLayout = activity.LayoutInflater.Inflate(FormsAppCompatActivity.TabLayoutResource, null).JavaCast<TabLayout>();
 else
   tabs = _tabLayout = new TabLayout(activity) { TabMode = TabLayout.ModeFixed, TabGravity = TabLayout.GravityFill };
```

For the Bottom Navigation View it gets instantiated like so:

```
_bottomNavigationView = new BottomNavigationView(Context)
{
   LayoutParameters = bottomNavigationViewLayoutParams,
   Id = Platform.GenerateViewId()
};
```

### Expected Behavior
Add a` FormsAppCompatActivity.BottomTabLayoutResource `in the main activity so we can customize as we want.

### Actual Behavior
No ability to customize tab bar without traversing views to find it.

**Comment by kingces95** [comment]
@acastr7 if you could attach a reproduction solution, we would appreciate it.

**Comment by acastr7** [comment]
@kingces95 I think it would help to look at this https://github.com/jsmarcus/Iconize/blob/c05affcf5254d9562efde6da80b35fe5c64273b7/src/Plugin.Iconize/Platform/Android/Renderers/IconTabbedPageRenderer.cs#L61.
Before when we wanted to access the toolbar layout, we could find it because Xamarin.Forms registers the ID for the layout. Now that there is a bottom navigation view, there is no way to easily access the Navigation view to help us override the default behavior.

**Comment by jfversluis** [comment]
Seeing this issue is quite old, a lot happened in this area in the meantime and Xamarin.Forms now being in maintenance mode, I think it's safe to say we can close this one :)

I hope you will check out .NET MAUI! If there is still something you would like to see improved there in this area, please let us know!
