### ISSUE TITLE
ListView item Context menu (android) behind popup

### ISSUE THREAD

**Issue by Nixon-Joseph** [xamarin/Xamarin.Forms#3100]
### Description
I have a full screen popup/modal with a listview in it, and I tried adding a context menu to the items. It technically works, however the context menu shows up behind the popup/modal, so it's useless.

### Steps to Reproduce

1.  Create full screen popup/modal containing a list view with context menu on data template
2.  Push popup/modal to popup stack
3.  Open context menu on item

### Expected Behavior
Menu appears above all other ui.

### Actual Behavior
Menu appears behind popup

### Basic Information

- Version with issue: 2.5.1 through 3.0.0
- Last known good version: N/A
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: API 26
- Nuget Packages:
- Affected Devices:
 - Nexus 6

**Comment by kingces95** [comment]
@Nixon-Joseph If you could attach a reproduction we'd appreciate it.

**Comment by PureWeen** [comment]
Closing for now because inactive 30 days. If this still is an issue please attach a repro and we can re-open.

I tested this myself locally and wasn't able to reproduce

```C#
ListView view = new ListView();
			view.ItemsSource = Enumerable.Range(0, 100);
			ContentPage page = new ContentPage();
			page.Content = view;
			view.ItemTemplate = new DataTemplate(() =>
			{
				ViewCell cell = new ViewCell();
				cell.View = new Label() { Text = "Context Actions" };

				cell.ContextActions.Add(
					new MenuItem()
					{
						Text = "CONTEXT "
					});

				return cell;
			});

			MainPage = new NavigationPage(
				new ContentPage()
				{
					Content = new Label() { Text = "cat" }
				});

			MainPage.Navigation.PushAsync(page);
```
