### ISSUE TITLE
Unable to hide the scrollbar visibility of ScrollBar in Xamarin Forms.

### ISSUE THREAD

**Issue by Yuvaraj-Syncfusion** [xamarin/Xamarin.Forms#3105]
Hi Xamarin Team

### Description

We have found a strange issue in XF- Android platform: The 'HorizontalScrollBarEnabled' property doesn't work in latest Xamarin Forms version (v 3.1.0.583944). In Write render the ScrollView to set this property as false is not reflecting in the view.

Here we have loaded ScrollView (Horizontal orientation) in StackLayout with labels 

### Steps to Reproduce

1. Run the attached sample.
2. Scroll the views, ScrollBar is not hide.
3. If ScrollView is Horizontal orientation it is working fine.

We are using following approach in rendering 

```
[assembly: ExportRenderer(typeof(ScrollViewExt), typeof(ExtendedScrollViewRenderer))]
namespace ScrollView_Renderer.Droid
{
    public class ExtendedScrollViewRenderer : ScrollViewRenderer
    {
        public ExtendedScrollViewRenderer()
        {
        }

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            this.HorizontalScrollBarEnabled = false;
            this.VerticalScrollBarEnabled = false;
        }
    }
}

```

### Expected Behavior

ScrollBar is hide when loading the views, and scrolling the views

### Actual Behavior

ScrollBar is not hide when loading the views, and scrolling the views

### Basic Information

- Version with issue: Xamarin.Forms v- 3.1.0.583944
- IDE: Visual Studio 2017 version 15.7.4
- Platform Target Frameworks: 
  -Xamarin.Android SDK 8.1.5.0 (HEAD/75f8c6838)
  -Xamarin.Android Reference Assemblies and MSBuild support.
  -Xamarin.iOS and Xamarin.Mac SDK 11.6.1.4 (db807ec)
- Android Support Library Version: 27.0.2.1
- Nuget Packages: Xamarin.Forms -v- 3.1.0.583944
- Affected Devices: All Android Devices

### Sample File 
[ScrollView_Renderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2123678/ScrollView_Renderer.zip)

**Comment by kingces95** [comment]
Request: Support HorizontalScrollBarEnabled & VerticalScrollBarEnabled. ListView2 may address this request.

**Comment by bmacombe** [comment]
I don't have time to check it out right now, but I wonder if this is a bug with PR #1910 that I think was just included in 3.1

**Comment by bmacombe** [comment]
@Yuvaraj-Syncfusion I think you are seeing a behavior change because of PR #1910.  Since you are using XF 3.1 you no longer need to add your own renderer to adjust scroll bar visibility because the Scrollview now has a HorizontalScrollBarVisibility property.

**Comment by Brosten** [comment]
I'm using a scrollView (Orientation = Horizontal) with HorizontalScrollBarVisibility = Never.
Still Android is showing the scroll. Even though the scroll bar is not SHOWN, the space where the scroll-bar should have been shown is still occupied by the non-showed scrollbar.

**Comment by jfversluis** [comment]
Looks like this could've been closed long time ago because it's now part of the core functionality! 🎉
