### ISSUE TITLE
[Enhancement] LineBreakMode for Button

### ISSUE THREAD

**Issue by peterfoot** [xamarin/Xamarin.Forms#3106]
##Summary
Add LineBreakMode (as currently supported on Label) to the Button control to specify text wrapping/trimming behavior. I've created an implementation as an Effect here:-
https://github.com/inthehand/InTheHand.Forms/blob/master/InTheHand.Forms/ButtonLineBreakModeEffect.cs

##API Changes

Addition of LineBreakMode property on Button. Use existing LineBreakMode enum.

##Intended Use Case
Allows you to specify the linebreak/wrapping appearance for Buttons rather than reverting to different default platform specific appearances.

**Comment by samhouts** [comment]
related to #1668

**Comment by samhouts** [comment]
@velocitysystems Yes! That would be great! Thank you!

**Comment by pictos** [comment]
@samhouts  since the #7043 already has a PR, I want to work on this issue. I'll send a draft PR for this.

**Comment by FIELDPOINT** [comment]
Any updates on this?
