### ISSUE TITLE
iOS - UISwitch.Appearance.OnTintColor broken in 3.1.0.583944 update.

### ISSUE THREAD

**Issue by philmoz** [xamarin/Xamarin.Forms#3111]
### Description

The iOS setting UISwitch.Appearance.OnTintColor no longer works after the Xamarin.Forms 3.1.0.583944 update.

### Steps to Reproduce

1. Set UISwitch.Appearance.OnTintColor in the AppDelegage.cs FinishedLaunching method.
(see https://docs.microsoft.com/en-au/xamarin/xamarin-forms/platform/ios/theme#uiswitch)

### Expected Behavior

On iOS switches show the selected colour when in the On state.

### Actual Behavior

Switches are shown with the default iOS green colour in the On state.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 3.0.0.561731
- IDE: Visual Studio for Mac 7.5.3 (build 7)

**Comment by markjackmilian** [comment]
Same bug here.

**Comment by kingces95** [comment]
@philmoz If you could attach a reproduction, we'd appreciate it.

**Comment by philmoz** [comment]
[XF_3111.zip](https://github.com/xamarin/Xamarin.Forms/files/2131271/XF_3111.zip)

Before 3.1.0.583944 update:
![simulator screen shot - iphone se - 2018-06-25 at 08 26 43](https://user-images.githubusercontent.com/9474356/41824332-e60c7386-7851-11e8-9474-ef70bdf31289.png)

After 3.1.0.583944 update:
![simulator screen shot - iphone se - 2018-06-25 at 08 28 06](https://user-images.githubusercontent.com/9474356/41824334-ef9fc02e-7851-11e8-831e-da9dcf745162.png)

**Comment by markjackmilian** [comment]
@vyasaraj999 you can use the “incolore” property in xamarin forms switch

**Comment by philmoz** [comment]
Is this ever going to get fixed or do I now have to manually add another property to every switch?

Instead of having one theme setting applied to all switches I now have to add a property to them all (and hope I don't miss one).

What happened to not breaking existing functionality?

**Comment by vyasaraj999** [comment]
@markjackmilian thanks.... it is working fine now.

**Comment by rmarinho** [comment]
Should be fixed on 3.3.0 as pr #3819  was merged alread
