### ISSUE TITLE
ScrollView on iOS resets its scroll offset

### ISSUE THREAD

**Issue by Keboo** [xamarin/Xamarin.Forms#3112]
### Description
On iOS the `UIScrollView` used to render the `ScrollView` resets its [contentOffset](https://developer.apple.com/documentation/uikit/uiscrollview/1619404-contentoffset) to (0,0) when the size of the ScrollView changes. The examples used here use horizontal scrolling, but the same issue applies in vertical mode, it just takes more effort to re-create the same conditions. 
I believe this is the same issue described in this [existing bugzilla report](https://bugzilla.xamarin.com/show_bug.cgi?id=43947).

### Steps to Reproduce

1. Create a XF app.
2. Add a `ScrollView`. It should be positioned inside of a container such that its size can change. For simplicity, I set its Orientation to Horizontal, and centered inside of a `Grid`.
3. Add content to the `ScrollView`. For my example I simply used a `StackLayout` (Orientation horizontal), with a bunch of `Labels`.
4. Scroll the `ScrollView`, the cause its size to change. For this I added a `TapGestureRecognizer` that changed the `HeightRequest` of the label.

### Expected Behavior
The `ScrollView` should maintain its offset.

### Actual Behavior
The `ScrollView` resets its offset to 0.

### Basic Information

- Version with issue: 
- Last known good version: N/A
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  11.4
  - Xamarin.Forms: 3.1.0.583944 (though I suspect it goes back to 2.3.2)

### Screenshots

![scrollviewererror](https://user-images.githubusercontent.com/952248/41750174-5548f0e8-756f-11e8-9e7b-81acb088a10c.gif)

### Reproduction Link

Example project shown above is [here](https://github.com/Keboo/Xamarin.Forms.ScrollViewer.Bug)
There is also a sample project on the original [bugzilla report](https://bugzilla.xamarin.com/show_bug.cgi?id=43947)

### Analysis
In my [example project ](https://github.com/Keboo/Xamarin.Forms.ScrollViewer.Bug) I have also included a workaround that I am using in my project. What follows is how I came to it.
The reset is occurring because the ContentSize of the `UIScrollView` is being set to a value smaller than the current `contentOffset`. Because the `contentOffset` is no longer contained with the new `contentSize` so it resets the `contentOffset` to (0,0). 

In the [iOS ScrollViewRenderer.OnNativeControlUpdated](https://github.com/xamarin/Xamarin.Forms/blob/47fd55130bfa9bd78188d2c55b9ec3abef3cd8ea/Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs#L214-L218) it sets the ContentSize to be equal to the `Bounds.Size`. In the example project, this set is what triggers the the `contentOffset` to move to (0,0). It then calls [ScrollViewRenderer.UpdateContentSize](https://github.com/xamarin/Xamarin.Forms/blob/47fd55130bfa9bd78188d2c55b9ec3abef3cd8ea/Xamarin.Forms.Platform.iOS/Renderers/ScrollViewRenderer.cs#L263-L268) which then properly resets the ContentSize based on the new ContentSize from the Forms element.

For my workaround, I simply derive from the ScrollViewRenderer and override the ContentSize property. It then blocks any change to this property that disagrees with the Forms ContentSize. At least for my application this is an acceptable workaround. However I suspect this may not work in all cases.

**Comment by kingces95** [comment]
[Xamarin.Forms.ScrollViewer.Bug-master.zip](https://github.com/xamarin/Xamarin.Forms/files/2129473/Xamarin.Forms.ScrollViewer.Bug-master.zip)

**Comment by JKennedy24** [comment]
This is a 2 minute fix that would provide huge improvement to UX for Xamarin Forms apps. Hopefully will be in an update soon

**Comment by AndreiMisiukevich** [comment]
@Keboo @kingces95 
https://github.com/xamarin/Xamarin.Forms/pull/3842

looks the same issue

**Comment by bill2004158** [comment]
should be fixed in #3842

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
