### ISSUE TITLE
Xamarin.Forms.Themes problems

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3117]
### Description

We don't have a good story to tell about Pages and Themes. While Pages is a stable release, Themes is still a pre-release.

Users are reporting problems with Themes being optimised out by the linker in release mode. While this can be avoided, some style classes that work fine in debug mode don't work in release mode.

The situation as is can't go on as we are acquiring user ire for Themes still being a pre-release and not always working well.

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/master/Pages/DataPagesDemo
https://github.com/xamarin/xamarin-forms-samples/tree/master/Themes/ThemesDemo

**Comment by kingces95** [comment]
Re triage: From a bug triage perspective, we need info from mgmt on how to proceed so that's why I'm parking this in needs info.

**Comment by jfversluis** [comment]
I think both Pages and Themes are no longer a... theme.

![R](https://user-images.githubusercontent.com/939291/154129198-b65d9332-1dfc-4212-b7f0-e544ede0fd5c.gif)
