### ISSUE TITLE
Button with background color is incorrect rendered on Android

### ISSUE THREAD

**Issue by jenscski** [xamarin/Xamarin.Forms#3121]
### Description
When setting background color on a button, the border/margin/padding goes away, so buttons with background is missing spacing and is larger than the buttons without background color.
### Steps to Reproduce

1.  Set BackgroundColor on a button

### Expected Behavior
That the button keeps its border/margin/padding

### Actual Behavior
The border/margin/padding disappears, and button is visiably larger, eating up spacing.

### Basic Information

- Version with issue: Xamarin.Forms: 3.1.0.583944
- Last known good version: Xamarin.Forms: 2.5.0.280555
- IDE: Visual Studio 15.7.4
- Platform Target Frameworks:
  - Android: 8.3.3.2
- Android Support Library Version:  27.0.2.1

### Screenshots
With error
![device-2018-06-22-144338](https://user-images.githubusercontent.com/4134254/41777432-94083d40-762b-11e8-9b4b-ed1473adc06f.png)

Without error
![device-2018-06-22-145045](https://user-images.githubusercontent.com/4134254/41777468-ae8d2658-762b-11e8-9db9-1a1d06dd9757.png)

### Reproduction Link
https://www.dropbox.com/s/lvzyjjn76jjwt9m/ButtonBackgroudColorError.zip?dl=1

**Comment by samhouts** [comment]
Please see the instructions in this comment: https://github.com/xamarin/Xamarin.Forms/pull/1935#issuecomment-375728802. Thanks!
