### ISSUE TITLE
[Enhancement] Better support for system icons

### ISSUE THREAD

**Issue by sdebruyn** [xamarin/Xamarin.Forms#3122]
### Description

When you want to offer the user the most native experience, true to the platform, you might want to use the built-in system icons. Both Android and iOS support them.

E.g. https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/system-icons/

At the moment, you have to create a custom renderer or effect to achieve this. I feel like this should be a lot simpler, they are the defaults after all...

### Expected Behavior

Use something like `Icon="Add"` in your XAML.

### Actual Behavior

Write a custom renderer.

### Basic Information

- Version with issue: 1.0 - 3.1
- Last known good version: /

**Comment by dansiegel** [comment]
Seems like this would be a good add for the Community Sprint/F100

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
