### ISSUE TITLE
[Shell] 3bar.png missing for the flyout menu hamburger

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3124]
### Description
The resource cannot be found. It works fine if I copy the images manually to the head projects.

### Basic Information

- Version with issue: 3.2.0.599850

### Reproduction Link

https://github.com/davidortinau/Gastropods

Parent: #2415

**Comment by StephaneDelcroix** [comment]
the png is included as BundleResource in the Platform project

**Comment by rmarinho** [comment]
fixed by #5961
