### ISSUE TITLE
Entry - add Font Property (Enhancement)

### ISSUE THREAD

**Issue by MappingSteve** [xamarin/Xamarin.Forms#3126]
To be consistent with Label and Button, add a "Font" property, rather than requiring individual setting of Family/Size/Attributes.

Version: Xamarin.Forms 3.0

**Comment by ravinderjangra** [comment]
I was checking this but found that it is marked obsolete for Label. so should this also be removed along with adding Font property to entry.
https://github.com/xamarin/Xamarin.Forms/blob/9fe5372c1d80ca8fcff0c4fc397d25f91f6b61d3/Xamarin.Forms.Core/Label.cs#L95-L100

**Comment by MappingSteve** [comment]
IMHO, not having `Font` on Label would be incredibly inconvenient; much more so than on Entry. Would mean having to separately set fontfamily, fontattributes, and font size, on every label style, and every individual label that chooses to override the base style.

**Comment by samhouts** [comment]
While we are not intending to remove the `Font` property on any element, we plan to keep it marked as obsolete and therefore unsupported. Using the individual properties is the preferred method of setting font values. As such, we do not want to add `Font` to other elements. We regret that this decision was not made earlier--we greatly appreciate contributions, and we hate to see our contributors work on something that we later decide not to include in the project. 

So, thank you for this suggestion, and while we will decline it at this time, we are open to considering a different solution that might improve font management.
