### ISSUE TITLE
Allow GLES3 in OpenGLView

### ISSUE THREAD

**Issue by j4m3z0r** [xamarin/Xamarin.Forms#3127]
### Description

OpenGLView only provides GLES2 support, but GLES3 has been pretty commonplace for quite some time now (it was introduced on iDevices on the A7 chip, which dates back to 2013). Can we add an option to create a GLES3 context instead?

The relevant code looks to be here:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/OpenGLViewRenderer.cs#L56

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/OpenGLViewRenderer.cs#L44

I realize that OpenGL is a "deprecated" API (at least according to Apple), but at present we don't have a robust cross platform replacement, so it would be good to have the OpenGLView be as useful as possible until such time as a replacement becomes available.

Given how long GLES3 has been around, it's probably not unreasonable to just switch over to GLES3 wholesale; I believe it is backwards compatible. If there is concern about losing device support, then a fallback to a GLES2 context and a way to know which GLES version is in use would also work.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
