### ISSUE TITLE
Add Selected and Unselected events to Maps.Pin object

### ISSUE THREAD

**Issue by ncarandini** [xamarin/Xamarin.Forms#3131]
## Summary
I'd like to have `Selected ` and `Unselected `  events on `Xamarin.Forms.Maps.Pin` class that fires when the user tap the pin.

## API Changes
Add
- `public event EventHandler Selected;` 
- `public event EventHandler Unselected;` 

to the `Xamarin.Forms.Maps.Pin.cs` file (and implement it on platforms code).

## Intended Use Case
We already have the  pin `Clicked` event,  but it's actually fired when the user, after tapping the pin, then taps the pin label. This is a double action so that the clicked event is not really related to the pin itself, but to the label of the pin.

I do understand that changing the semantic of `Clicked` and eventually adding a `LabelClicked` event would be a breaking change on existent Xamarin.Forms code, so I'm asking for the `Selected` event that can solve the issue without breaking existing code.

Moreover, AFAIK there isn't an event that's been fired when a selected pin is unselected.

This can be useful (and much needed) at least in this scenario:

1. Suppose I want to show something related to the pin in the same page where the Map is shown, whenever the user tap a pin:

  ![image](https://user-images.githubusercontent.com/139274/41808135-74750964-76d9-11e8-954b-627896991822.png)

As you can see the user has to tap twice to get the Clicked event fired, one for selecting the pin and get the pin label shown, the other when tapping the label to fire the clicked event.

And when the user taps on another pin, or just unselect it tapping on the map, the footer message become out of sync because is still related to the latest tapped pin label.

**Comment by danudnas** [comment]
there is a function that is executed after click:
 pin.MarkerClicked += (s, args) =>
            {
                Console.WriteLine("Do what ever you wnat in heare");
            };
