### ISSUE TITLE
Android 4.1 exception: Java.Lang.NoSuchMethodError: no method with name='isInLayout' signature='()Z' in class Landroid/view/ViewGroup;

### ISSUE THREAD

**Issue by rzakirov** [xamarin/Xamarin.Forms#3132]
### Steps to Reproduce

1. Run

### Basic Information

- Version with issue: XF 3.1.
- Last known good version: XF3.0
- IDE: VS2017
 
- Sln: https://github.com/rzakirov/XF31-API16-Excpetion

**Comment by K232** [comment]
See also [https://forums.xamarin.com/discussion/128491/xamarin-forms-android-system-runtime-serialization-dll-so-not-found](https://forums.xamarin.com/discussion/128491/xamarin-forms-android-system-runtime-serialization-dll-so-not-found )

**Comment by kingces95** [comment]
Application launches without issue on latest `3.2.0` branch. Please re-open should you be able to reproduce the issue. To create a local nuget package `set NUGET_DIR=x:\nuget\4.4.1\` then `.create-nuget.bat droid`. 

![image](https://user-images.githubusercontent.com/4120386/42187655-82150d7a-7dec-11e8-9bc8-09a15d4dcc62.png)

**Comment by kingces95** [comment]
You may need to wait till https://github.com/xamarin/Xamarin.Forms/pull/3200/files clears before `.create_nuget.bat` will work.

**Comment by tmt242001** [comment]
Issue exist in 3.1.0.637273

**Comment by dais-set** [comment]
Hi, we've also hit the same java.lang.NoSuchMethodError: no method with name='isInLayout' signature='()Z' in class Landroid/view/ViewGroup;
in the latest stable Xamarin.Forms. I'm worried it is not just our old test device but other phones that will have the issue. Could you advice on a workaround? I'd rather use newer versions of Xamarin.Forms but as this is production code will not be able to do so as we can't just break everything and then wait for a fix sometime in the distant future.
I'm downgrading Xamarin.Forms back to 3.0.0.561731 (which worked) and as usual, will not upgrade until we absolutely must :(

**Comment by kyluke** [comment]
Any updates on this?

**Comment by lahna200** [comment]
Resolved in the last release (3.1.0 Service Release 2)

**Comment by jamesmontemagno** [comment]
Yup, can confirm it is in: https://www.nuget.org/packages/Xamarin.Forms/3.1.0.697729

**Comment by xleon** [comment]
Confirmed this is fixed on 3.2 pre2

**Comment by frogcrush** [comment]
This is happening again on latest Nuget. Can we re-open?
