### ISSUE TITLE
Is Version 3.1.0 Released?

### ISSUE THREAD

**Issue by Timothy-Liu** [xamarin/Xamarin.Forms#3134]
In the document https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.1/3.1.0/, it looks the version 3.1.0 is released. But the lasted build is marked as RC. Is the version 3.1.0 released?

**Comment by EmilAlipiev** [comment]
yes it is released and there are breaking changes https://forums.xamarin.com/discussion/128514/be-aware-of-breaking-xaml-changes-on-xf-3-1/p1?new=1

**Comment by StephaneDelcroix** [comment]
the release-candidate was published as stable after going through QA:
https://www.nuget.org/packages/Xamarin.Forms/3.1.0.583944
