### ISSUE TITLE
breakpoint doesn't hit when I use .net standard

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#3137]
Here is the code for test and reproduce https://github.com/anirugu/CameraTesting

I am trying to make a app, in app a button clicked and camera opened. camera clicked and files saved.

I write the code, debug it. it was hitting the c# code breakpoint in first few run, later on stop hitting the breakpoint.

I run same code with shared project, it's working but it doesn't execute the code, maybe static method can't opened camera.

please check the code, I made it in 3.0 and later on I make it in 2.4 to make sure nothing is wrong with version 3.0. 

it's not running, I got exception, the c# code doesn't match the code currently running. I spent few hours working on it. still not finished with this.

**Comment by PureWeen** [comment]
Yea it's unfortunate that's needed. The Forms templates will have that included with the next release of VS which should help out the confusion some
