### ISSUE TITLE
[UWP] : DisplayActionSheet Is Hiding behind Loader.

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#3139]
### Description
Reference : #3015  - Please refer last comment.This issue is closed but my problem is still  exist. 
please help me solve this problem.

var res = await Application.Current.MainPage.DisplayActionSheet("Add Item ?", "Cancel", "", "YES", "NO"); -- is hiding behind loader.

### Steps to Reproduce

1. Start Loader using Acr.UserDialogs Plugin.
2. Open Alert Popup. 

### Expected Behavior

1. Alert should come on top of Loader
2. Alert should not close on clicking outside.

### Actual Behavior
1. Loader is coming on top of Alert. 
2. Alert is closing if user clicks anywhere outside application.

### Basic Information

- Version with issue:
     XF - 3.0.0.482510
- Last known good version: NA
- IDE: Microsoft Visual Studio Community 2017
- Platform Target Frameworks:
     UWP: 16299

- Nuget Packages:
    Acr.UserDialogs - v7.0.1.

    XF - 3.0.0.482510
- Affected Devices: UWP

### Screenshots

![displayactionsheetissue](https://user-images.githubusercontent.com/30036418/41762199-9d592a26-7617-11e8-8aca-b8a9450dd4a2.png)

![actionsheetasyncissue](https://user-images.githubusercontent.com/30036418/41762198-9d0900fa-7617-11e8-8ec7-692243d10192.png)

**Comment by paymicro** [comment]
1. Alert should come on top of Loader.

`Application.Current.MainPage` is not changed automatically when the Main page is changed in code.
This page may not be present in visual tree or be present behind another page / dialog (behind the loader).

2. Alert should not close on clicking outside.

\<Page\>.`DisplayActionSheet` shows `Flyout`.
> Unlike a dialog, a flyout can be quickly dismissed by tapping or clicking somewhere outside the flyout, pressing the Escape key or Back button, resizing the app window, or changing the device's orientation.
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs#dialogs-vs-flyouts

Therefore, its behavior is not like `Dialog`'s.

**Comment by ashishm29** [comment]
hi @paymicro 

1) I have single page sample Application, So i don't think so that  it is the case of Changing Application.Current.MainPage.

**_I have tried code behind too, still getting same result:_**

_btnAddMore.Clicked += btnAddMore_Clicked;_
  **private async void btnAddMore_Clicked(object sender, EventArgs e)
        {
            UserDialogs.Instance.ShowLoading("Loading...");
            var res = await DisplayActionSheet("Add Item ?", "Cancel", "", "YES", "NO");
            SimpleIoc.Default.GetInstance<MainViewModel>().DisplayList.Add(new Country { Name = "NEW COUNTRY : " + SimpleIoc.Default.GetInstance<MainViewModel>().DisplayList.Count.ToString() });
            UserDialogs.Instance.HideLoading();
        }**

**Comment by paymicro** [comment]
Hi @ashishm29 
You can try adding `await Task.Sleep(200)` before `DisplayActionSheet`. To let the "Loading" dialog appear and not show the `ActionSheet` before it appears.

**Comment by ashishm29** [comment]
hi @paymicro 
1) System.Threading.Tasks doesn't have method like Task.Sleep(200).
2) Even if this works this is just a temporary fix.

Thanks.

**Comment by hartez** [comment]
This is an issue with a third-party component; we will not be addressing it. 

The dialog you are using for "Loading" is a ContentDialog, which by its nature blocks the UI until dismissed. I would suggest either dismissing the "Loading" dialog when you want to display other content, or using a different component for your "Loading" message.
