### ISSUE TITLE
Can someone create Example Demo Project with WPF, macOS and maybe Linux Desktop as target builds?

### ISSUE THREAD

**Issue by ALIENQuake** [xamarin/Xamarin.Forms#3140]
Hi,

I have simple project created using Windows Forms and exactly the same project created in WPF. All I need is a starting point which will produce simple cross-platform GUI app. 

Can someone create Example Demo Project with WPF, macOS and maybe Linux Desktop as target builds? Possible?

**Comment by pauldipietro** [comment]
[WPF](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf);
[macOS](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac);
[GTK#](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/gtk)
