### ISSUE TITLE
Regression Issue - Content set after an await is not visible #1760 NOT FIXED

### ISSUE THREAD

**Issue by ceblanda** [xamarin/Xamarin.Forms#3142]
### Description
Android only, Master/Detail window opened from master, Content is blank if set after an await

### Steps to Reproduce

1. Run the attached app.  Label on the detail screen reads "Before the await", then changes to "After the await"
2. Open the Master menu and choose the TestPage option.  This opens the same page as step 1.  The "Before the await" label is visible, then the view is blank.

### Expected Behavior
The window should behave the same in both steps.

### Actual Behavior
The second label is not displayed in the second step

### Basic Information

- Version with issue: 2.5.0 (and 2.4)
- Last known good version: 2.3.4.270
- IDE: VS2017
- Affected Devices: Android

### Reproduction Link
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2133118/HeaderTest.zip)

**Comment by ceblanda** [comment]
Today this is working running the same test app on the same device with 3.1.0.583944

**Comment by samhouts** [comment]
Closing per https://github.com/xamarin/Xamarin.Forms/issues/3142#issuecomment-401791500. Please reopen if it stops working again! Thank you!
