### ISSUE TITLE
[Enhancement] [Documentation] Specify XF version 

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#3143]
### Rationale 
The documentation does not state which Xamarin Forms version the class/method/property applies to.

Example: The `ReturnType` property of `Entry` is only available in Xamarin Forms v3.1.

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.entry.returntype?view=xamarin-forms#Xamarin_Forms_Entry_ReturnType

**Comment by StephaneDelcroix** [comment]
ping @lobrien
