### ISSUE TITLE
[Android] IsClippedToBounds on (Fast Renderer) Frame not working

### ISSUE THREAD

**Issue by GyllionElderen** [xamarin/Xamarin.Forms#3150]
### Description
The property 'IsClippedToBounds' is not working as expected on Frames. When set to false, the frame will still not allow elements to be rendered outside of its bounds. This is only happening with frames that use the Xamarin.Forms.Platform.Android.AppCompat.FrameRenderer renderer. When using the Xamarin.Forms.Platform.Android.FrameRenderer renderer, the problem is fixed, but the shadow is gone.

See https://bugzilla.xamarin.com/show_bug.cgi?id=59448

### Steps to Reproduce

1. Make a Frame on a ContentPage
2. Set the property 'IsClippedToBounds' on the frame to 'false'
3. Set an element in the content of the frame that will be rendered outside of its bounds (e.g. TranslationX + 50)
4. Compile and run. Only the parts inside the frame will be visible 

### Expected Behavior
Parts of the element will be visible outside a frame when the property 'IsClippedToBounds' is set to 'false'.

### Actual Behavior
Parts of the element are not visible outside a frame when the property 'IsClippedToBounds' is set to 'false'.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: Unkown
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 7.1

### Screenshots
Expectations:
![expectations](https://user-images.githubusercontent.com/32705616/41899804-a70b5f26-792d-11e8-91fb-f8bdab4c6f25.PNG)

Reality:
![reality](https://user-images.githubusercontent.com/32705616/41899684-64068e94-792d-11e8-8f82-6ef9744ef114.PNG)

### Reproduction Link
https://github.com/GyllionElderen/IsClippedToBoundsFrameTest

**Comment by autosoftmultimedia** [comment]
I still got this problem! Any solution?

**Comment by NirmalSubedi17** [comment]
Still having the same issue! Is there any work around?

**Comment by imdanielpiva** [comment]
Hello @NirmalSubedi17, how did you manage to use the Custom Frame Render you've mentioned? Sorry for the newbie question, I've just got started with Xamarin.Forms.

**Comment by imdanielpiva** [comment]
Based on https://bugzilla.xamarin.com/show_bug.cgi?id=59448 this bug is confirmed.

**Comment by autosoftmultimedia** [comment]
News about this issue? I'm still releasing my app with Forms 3.1 due to this bug.

**Comment by Zukka** [comment]
> ### Description
> The property 'IsClippedToBounds' is not working as expected on Frames. When set to false, the frame will still not allow elements to be rendered outside of its bounds. This is only happening with frames that use the Xamarin.Forms.Platform.Android.AppCompat.FrameRenderer renderer. When using the Xamarin.Forms.Platform.Android.FrameRenderer renderer, the problem is fixed, but the shadow is gone.
> 
> See https://bugzilla.xamarin.com/show_bug.cgi?id=59448
> 
> ### Steps to Reproduce
> 1. Make a Frame on a ContentPage
> 2. Set the property 'IsClippedToBounds' on the frame to 'false'
> 3. Set an element in the content of the frame that will be rendered outside of its bounds (e.g. TranslationX + 50)
> 4. Compile and run. Only the parts inside the frame will be visible
> 
> ### Expected Behavior
> Parts of the element will be visible outside a frame when the property 'IsClippedToBounds' is set to 'false'.
> 
> ### Actual Behavior
> Parts of the element are not visible outside a frame when the property 'IsClippedToBounds' is set to 'false'.
> 
> ### Basic Information
> * Version with issue: 3.1.0.583944
> * Last known good version: Unkown
> * IDE: Visual Studio 2017
> * Platform Target Frameworks: 
>   
>   * Android: 7.1
> 
> ### Screenshots
> Expectations:
> ![expectations](https://user-images.githubusercontent.com/32705616/41899804-a70b5f26-792d-11e8-91fb-f8bdab4c6f25.PNG)
> 
> Reality:
> ![reality](https://user-images.githubusercontent.com/32705616/41899684-64068e94-792d-11e8-8f82-6ef9744ef114.PNG)
> 
> ### Reproduction Link
> https://github.com/GyllionElderen/IsClippedToBoundsFrameTest

I just tried and the bug is already present.

My Configuration is:
- Visual Studio 2019 Professional
- Xamarin Forms 4.2.0.778463

**Comment by jamesmontemagno** [comment]
@pauldipietro can you take a look at this again.

**Comment by ColeXm** [comment]
I have the same issue on scrollview , IsClippedToBounds  does not work even i took the solution in the link : https://bugzilla.xamarin.com/show_bug.cgi?id=59448  .

**Comment by Zukka** [comment]
Any news?

**Comment by matibak** [comment]
Calling `this.SetClipToOutline(false);` in Android custom FrameRenderer allows drawing outside of the frame
