### ISSUE TITLE
Effect doesn't work when the FastRenderers flag is set.

### ISSUE THREAD

**Issue by landl0526** [xamarin/Xamarin.Forms#3151]
When define an Effect to set the label's maximum lines, this Effect works fine:
```
[assembly: ExportEffect(typeof(Sample.Droid.Effects.MultiLineEffect), "MultiLine")]
namespace Sample.Droid.Effects
{
    public class MultiLineEffect : PlatformEffect
    {
        protected override void OnAttached() {
            var effect = (PCLEffect)Element.Effects.FirstOrDefault(e => e is PCLEffect);
            if (Control is TextView tv) {
                var maxLines = effect.MaxLines;
                if (maxLines > 0) {
                    tv.Ellipsize = TextUtils.TruncateAt.End;
                    tv.SetSingleLine(false);
                    tv.SetMaxLines(maxLines);
                }
            }
        }

        protected override void OnDetached() {
        }
    }
}
```
But after setting a fast renderers tag, this Effect become invalid.

**Comment by mpanzica** [comment]
As a workaround, setting the TextView properties when the Element's "Renderer" property changes fixes the issue:

```
public class MultiLineEffect : PlatformEffect
{
    protected override void OnAttached() {
    }

    protected override void OnDetached() {
    }

    protected override void OnElementPropertyChanged(PropertyChangedEventArgs args) {
        base.OnElementPropertyChanged(args);
        if(args.PropertyName == "Renderer") {
           SetMaxLines();
        }
    }

    void SetMaxLines() {
        if (Control is TextView tv) {
            var effect = (PCLEffect)Element.Effects.FirstOrDefault(e => e is PCLEffect);
            var maxLines = effect.MaxLines;
            if (maxLines > 0) {
                tv.SetSingleLine(false);
                tv.SetMaxLines(maxLines);
            }
        }
    }
}
```

**Comment by JFMG** [comment]
I experienced the same result for a label effect. I put the fast renderers line `Forms.SetFlags("FastRenderers_Experimental");` in my MainActivity.cs and my label effects won't work anymore. However, the `OnAttached` got called. I ran through the code with a debugger and everything seems to work fine, except you can't see the result in the UI.

**Comment by rbev** [comment]
This appears to be due to OnAttached/OnDetached not being called when the Renderer changes, and fastrenderers seems to attach the effect before loading the fast renderer.

My suspicion is that this is potentially a leak if an effect attaches to event handlers with fast renderers enabled.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
