### ISSUE TITLE
Error retrieving parent for item, On new projects itself  (˘⌣˘ )

### ISSUE THREAD

**Issue by PinkoAgrawal** [xamarin/Xamarin.Forms#3152]
### Description
I am using Visual Studio MAC Community version with Xamarin.Forms. After creating xamarin forms project I started gettingg errors
**Error retrieving parent for item** I got total 9 errors. I have closed VS, Clean & Rebuild etc..no use. **At least don't show issues in newly created projects.**

### Steps to Reproduce

1. Create xamarin forms project. Update nuget packages.
2. 
3. 
### Expected Behavior
Project should execute successfully
### Actual Behavior
Getting so many errors.
### Basic Information

- Version with issue:
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 3ad16a2d-ba7b-4910-b298-64ae85ff9f88
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/gsps/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		6.0   (API level 23)
		7.1   (API level 25)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.4
Darwin 17.5.0 Darwin Kernel Version 17.5.0
    Fri Apr 13 19:32:32 PDT 2018
    root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.5

- Affected Devices: Android(API 25) Emulator

### Screenshots

<img width="1330" alt="screen shot 2018-06-26 at 4 22 12 pm" src="https://user-images.githubusercontent.com/38238586/41907176-b2260caa-795d-11e8-95be-dc1953f1786a.png">

**Comment by StephaneDelcroix** [comment]
you probably should report this to https://github.com/xamarin/xamarin-android/

**Comment by PinkoAgrawal** [comment]
This is Xamarin.Forms project on Xamarin.Android project.

**Comment by hartez** [comment]
@PinkoAgrawal Android projects in Xamarin.Forms are built on Xamarin.Android.

I've opened up an issue at https://github.com/xamarin/xamarin-android/issues/1934 and referenced this issue.
