### ISSUE TITLE
Available screen height calculated wrong when navigation bar is hidden.

### ISSUE THREAD

**Issue by sf-ica** [xamarin/Xamarin.Forms#3153]
### Description

When hiding the navigation bar the available screen height isn't calculated properly.

### Steps to Reproduce

1. Create a page with a Grid layout.
2. Define the following rows:
```
<Grid.RowDefinitions>
	<RowDefinition Height="30" />
	<RowDefinition Height="*">
	<RowDefinition Height="30" />
</Grid.RowDefinitions>
```
3. Add some content.
4. Hide the navigation bar:
```
class Foobar : ContentPage
{
	public Foobar()
	{
		NavigationPage.SetHasNavigationBar(this, false);
	}
}
```

### Expected Behavior

The layout should use the entire page.

### Actual Behavior

There's a gap at the bottom of the page. It has exactly the same size as the hidden navigation bar. You find an example in the attached screenshot.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.GTK 3.1.0.583944
- Last known good version: n/a
- IDE: Visual Studio 2018
- Platform Target Frameworks:
  - GTK on Windows and Linux

### Screenshots

![gap](https://user-images.githubusercontent.com/39555596/41907568-8ddd0874-7941-11e8-9d5a-d43adc3d7ae8.png)

### Workaround

I tried several workarounds but the only working solution is to update the row definition at runtime during the SizeChange() event.

```
public BasePage()
{
	 NavigationPage.SetHasNavigationBar(this, false);

	 double max = 0;
	 const double OtherPixels = 70;
	 RowDefinition rowDefinition = null; // control has not been created yet!

	 SizeChanged += (s, e) =>
	 {
			if (Height > max && Height >= OtherPixels)
			{
				 if(rowDefinition == null)
				 {
						rowDefinition = FindControl<RowDefinition>("ContentRowDefinition");
				 }

				 max = Height;
				 rowDefinition.Height = max - OtherPixels;
			}
	 };
}

T FindControl<T>(string name)
{
	 var controller = this as IPageController;
	 T control = default(T);

	 foreach (var child in controller.InternalChildren)
	 {
			control = child.FindByName<T>(name);

			if(control != null)
			{
				 break;
			}
	 }

	 return control;
}
```

**Comment by jsuarezruiz** [comment]
Thanks for the detailed description, I'll take a look.
