### ISSUE TITLE
[IOS] V3.1.0 Crashes on ios with in RenderPool

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#3154]
### Description

Xamarin.Forms V3.1.0 Crashes on ios with the following stack trace:

Invalid Cast Exception
"  at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)\n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.UpdateRenderers (Xamarin.Forms.Element newElement) [0x0008c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) [0x00080] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VåisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00069] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) [0x0001c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x0002c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.FrameRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x00000] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x0012a] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.GetFreeRenderer (Xamarin.Forms.VisualElement view) [0x00048] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.FillChildrenWithRenderers (Xamarin.Forms.VisualElement element) [0x00035] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.FillChildrenWithRenderers (Xamarin.Forms.VisualElement element) [0x0002c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.RendererPool.UpdateNewElement (Xamarin.Forms.VisualElement newElement) [0x00078] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00069] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnRendererElementChanged (System.Object sender, Xamarin.Forms.Platform.iOS.VisualElementChangedEventArgs args) [0x0001c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x0002c] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x0012a] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003d] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000de] in <0aa4434e6c8849f1bca03cc1ef0ae57c>:0 \n  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement 

### Basic Information

- Version with issue: V3.1.0
- Last known good version: V2.5.1 (Latest)
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  11.1

**Comment by JKennedy24** [comment]
has there been any progress on this bug or are there any ways to work around this issue? my ios app is kaput at the moment due to this

**Comment by kingces95** [comment]
@JKennedy24 From the stack trace it's hard to identify what cause the issue. Could you attach a reproduction? If you could start from a blank forms app and add just enough logic to demonstrate the issue that'd really help.

**Comment by JKennedy24** [comment]
@kingces95 I'm affraid I haven't got a lot of time currently to get toghether a sample.

Below is my View though:

```
<Grid CompressedLayout.IsHeadless="{StaticResource CompressionLayoutOn}" Grid.Row="3" HorizontalOptions="Center" RowSpacing="0" WidthRequest="500">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="80"/>
                        <RowDefinition Height="25"/>
                        <RowDefinition Height="80"/>
                        <RowDefinition Height="25"/>
                        <RowDefinition Height="70"/>
                        <RowDefinition Height="10"/>
                        <RowDefinition Height="*"/>
                    </Grid.RowDefinitions>
                    
                    <Frame Grid.Row="0" BackgroundColor="{StaticResource SelectOneButtonBackground}" CornerRadius="5" BorderColor="{StaticResource SelectOneButtonBackground}" Padding="0">
                        
                        <Grid CompressedLayout.IsHeadless="{StaticResource CompressionLayoutOn}" Padding="15" >
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="50"/>
                                <ColumnDefinition/>
                                <ColumnDefinition Width="50"/>
                            </Grid.ColumnDefinitions>
                            <Entry x:Name="userName" IsSpellCheckEnabled="False" IsTextPredictionEnabled="False" AutomationId="UserNameControl" Grid.Column="1" custom:KeyboardStyle.KeyboardFlags="CapitalizeNone" Keyboard="Email" HorizontalTextAlignment="Center" Text="{Binding UserName}" FontSize="{styling:Font 20}" TextColor="{StaticResource SelectOneTextColour}" Placeholder="{trans:Translate Email/UserName}" BackgroundColor="Transparent"/>
                            <Image Source="{styling:Image fs_User.png}" HeightRequest="50" BackgroundColor="Transparent"/>
                            <Image Source="{styling:Image fs_Tick.png}"  Grid.Column="2" IsVisible="{Binding UserName, Converter={StaticResource NullToFalseConverter}}"/>
                        </Grid>
                    </Frame>
                    
                    <Frame Grid.Row="2" BackgroundColor="{StaticResource SelectOneButtonBackground}" CornerRadius="5" BorderColor="{StaticResource SelectOneButtonBackground}" Padding="0">
                        <Grid>
                            
                        </Grid>
                        <!--<Grid CompressedLayout.IsHeadless="{StaticResource CompressionLayoutOn}" Padding="15">
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="50"/>
                                <ColumnDefinition/>
                                <ColumnDefinition Width="50"/>
                            </Grid.ColumnDefinitions>

                            <custom:ExtendedEntry AutomationId="PasswordControl" IsSpellCheckEnabled="False" IsTextPredictionEnabled="False"  Grid.Column="1" IsPassword="{Binding ShowPassword, Converter={StaticResource InverseBooleanConverter}}" HorizontalTextAlignment="Center" EnterCommand="{Binding SignIn}" custom:KeyboardStyle.KeyboardFlags="CapitalizeNone" Text="{Binding Password}" FontSize="{styling:Font 20}" TextColor="{StaticResource SelectOneTextColour}" Placeholder="{trans:Translate Password}" BackgroundColor="{StaticResource SelectOneButtonBackground}"/>
                            <Image Source="{styling:Image fs_Lock.png}" HeightRequest="50" BackgroundColor="Transparent"/>
                            <Button Text="Show" Grid.Column="2" TextColor="{StaticResource SelectOneTextColour}" FontSize="{styling:Font 16}" Command="{Binding ShowPasswordCommand}">
                                <Button.Triggers>
                                    <DataTrigger TargetType="Button" Binding="{Binding ShowPassword}" Value="True">
                                        <Setter Property="Text" Value="Hide"/>
                                    </DataTrigger>
                                </Button.Triggers>
                            </Button>
                            <Image Source="{styling:Image fs_Tick.png}" Grid.Column="2"  IsVisible="False"/>
                        </Grid>-->
                    </Frame>
                    
                    <custom:IconButton Grid.Row="4"  AutomationId="SignInButton" WidthRequest="250" HorizontalOptions="Center" Text="{trans:Translate SignIn}" TextColour="White" Icon="{styling:Image fs_Enter.png}" Enabled="{Binding SignInIsEnabled}" ClickedCommand="{Binding SignIn}" ButtonColour="{StaticResource AccentColour}" OutlineColour="Transparent" IconBackgroundColour="{StaticResource AccentColourDarker}"/>
                    <Button Grid.Row="6" TextColor="{StaticResource AccentColour}" Text="See a Demo!" Command="{Binding SeeDemo}" VerticalOptions="Center" HorizontalOptions="Center"/>
                    
                </Grid>
            </Grid>
```

I've narrowed it down to a `Frame` that contains a `Grid` that has `CompressionLayout` on.

If I remove `CompressionLayout` from the grid it works fine
