### ISSUE TITLE
[Android] Effects methods are called even when Control is disposed

### ISSUE THREAD

**Issue by Gabriehl** [xamarin/Xamarin.Forms#3159]
### Description

Effects invoke the `OnAttached()` and `OnElementPropertyChanged()` methods even when the Control is already disposed.

### Steps to Reproduce

1. Create a class that inherits from a Xamarin.Forms View (I'll call it "MyView", as I will be mentioning it several times).
2. In `MyView`, create a public property (I'll call it "MyProperty") with a backing BindableProperty.
3. In the `App` class, create a public property of the same type as `MyProperty` (I'll call it "MyAppProperty") and call the `OnPropertyChanged()` method when it changes.
3. Create an Effect (it will be added to `MyView`) and override the method `OnElementPropertyChanged()`. There, update/call any of the Control's properties/methods. 
4. Add `MyView` to a page, adding the effect to it and binding `MyProperty` to `MyAppProperty` (`{Binding MyAppProperty, Source={Static Application.Current}}`).
5. When the app is running, open that page, pop from it and update `MyAppProperty` from somewhere. 

### Expected Behavior

The effect's `OnElementPropertyChanged()` doesn't get called, as the Control is already disposed.

### Actual Behavior

The effect's `OnElementPropertyChanged()` gets called, resulting in an `ObjectDisposedException` (with the message "Cannot access a disposed object") as soon as a property/method of the Control is updated/called.

### Basic Information

- Version with issue: 3.1.0.583944
- IDE: Visual Studio 2017 15.7.4
- Platform Target Frameworks:
  - Android: 8.1

### Reproduction Link

[ControlDisposedOnEffect.zip](https://github.com/xamarin/Xamarin.Forms/files/2138935/ControlDisposedOnEffect.zip)

**Obs.** To reproduce the issue on the repro project: tap the Button, pop from the page, then tap the Button again.

**Comment by PureWeen** [comment]
Probably related
https://github.com/xamarin/Xamarin.Forms/issues/2520

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
