### ISSUE TITLE
[Android] TFS build fails with when specifying VerticalScrollBarVisibility in XF 3.1

### ISSUE THREAD

**Issue by mattrichnz** [xamarin/Xamarin.Forms#3160]
### Description
After upgrading an existing project to XF 3.1-RC and setting `VerticalScrollBarVisibility` on a `ScrollView` in a XAML page, the Xamarin.Android build definitions fails in TFS. 
Existing iOS and UWP build definitions work fine.

### Steps to Reproduce

1. Create a Xamarin.Android build definition in TFS.
2. Create a sample project using the latest VS2017 .NET Standard template.
3. Add a XAML page with a `ScrollView` with `VerticalScrollBarVisibility` set.

### Expected Behavior
The build should complete successfully.

### Actual Behavior
The build fails during XAML compilation with the following error(s):
`Error : Position 65:13. No property, bindable property, or event found for 'VerticalScrollBarVisibility', or mismatching type between value and property.`

### Basic Information

- Version with issue: XF 3.10RC
- Last known good version: N/A

### Workaround

- Give the ScrollView an `x:Name`.
- Set the VerticalScrollBarVisibility in the ctor of the XAML page.

**Comment by StephaneDelcroix** [comment]
we'd need a repro project for this.

this looks like an error that XamlC would throw, indicating that there's a mismatch between the Build.Tasks.dll and the XF version. That usually comes from multiple different versions used in the same assembly

**Comment by samhouts** [comment]
@mattrichnz We haven't heard from you in 30 days, so we hope that this issue no longer affects you. If it does, please reopen the issue with a project that exhibits the issue if possible. Thank you!
