### ISSUE TITLE
Bindings to a DynamicObject

### ISSUE THREAD

**Issue by aloisdeniel** [xamarin/Xamarin.Forms#3177]
### Description

Binding properties of a DynamicObject to a bindable object doesn't work.

### Steps to Reproduce

1. Create a dynamic view model class

```csharp
 public class DynamicViewModel : DynamicObject, INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        private string title = "dynamic";

        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            if (binder.Name == nameof(title))
            {
                this.title = value as string;
            }

            return true;
        }

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            if (binder.Name == nameof(title))
            {
                result = this.title;
            }

            return base.TryGetMember(binder, out result);
        }

        public override IEnumerable<string> GetDynamicMemberNames()
        {
            return new[] { nameof(title) };
        }

    }
}
```
2. Bind a page to the dynamic view model

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    x:Class="Dynamic.Sample.HomePage">

    <Grid>
        <Label VerticalOptions="Center" Text="{Binding title}" />
    </Grid>
    
</ContentPage>
```
```csharp

  public partial class HomePage
  {
        #region Constructors

        public HomePage()
        {
            this.BindingContext = new DynamicViewModel();
            InitializeComponent();
        }

        #endregion
  }
```

### Expected Behavior

The `dynamic` value should be displayed on the screen.

### Actual Behavior

Nothing is displayed on the screen and a log appears :

```
'title' property not found on 'Dynamic.DynamicViewModel', target property: 'Xamarin.Forms.Label.Text'
```
### Basic Information

- Version with issue: 3.1.0.583944

**Comment by StephaneDelcroix** [comment]
as a workaround, bind to an array

**Comment by aloisdeniel** [comment]
To an array ? Did you mean `Dictionary<string,object>` with `[key]` accesses ?

**Comment by StephaneDelcroix** [comment]
a dictionary is an option, any type implementing the indexer would work too

```csharp
public object this[string index]    // Indexer declaration  
{  
    get {
        //equiv to TryGetMember
    }
    set {
        //equiv to TrySetMember
    }
} 
```

**Comment by AmrAlSayed0** [comment]
I was under the impression that dynamic objects don't work on iOS and are not even implemented in Mono due to [platform limitations](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations). While this page doesn't mention `dynamic` keyword or the `DynamicObject` but [here](https://www.wintellect.com/cant-use-dynamic-c-keyword-xamarin-ios/) and [here](https://www.wintellect.com/dynamic-objects-and-call-sites/) it says that the `dynamic` keyword generates code at runtime which is not allowed on iOS.

**Comment by StephaneDelcroix** [comment]
It's true that Xamarin.iOS does not ship with a DLR, required for a `dynamic` object, and you won't be able to declare a `dynamic` variable and assign it to your subclass of `DynamicObject`.

But, as `DynamicObject` is part of netstandard2.0, I don't see why we shouldn't be able to bind to it (haven't properly investigated through).

On platform not supporting the DLR, it won't probably bring any real value (same can be achieved with indexers), but if you run on a platform that supports the DLR, if your code rely on `dynamic`s, being able to bind to those objects looks natural to me.

**Comment by aloisdeniel** [comment]
One important thing to notice with the indexer approach : the raised property change doesn't trigger an update from the view : it only works as one way bindings. 

The support for DynamicObjects would be a lot more consistant though.

**Comment by StephaneDelcroix** [comment]
Indexers can trigger INPC. Look for samples in our unit tests.

**Comment by aloisdeniel** [comment]
Thanks! Didn't know it was possible. :)

The relevant code:

```csharp
[IndexerName("Indexer")]
public string this [int v] {
  get { return values [v]; }
  set {
    if (values [v] == value)
	return;

   values [v] = value;
   OnPropertyChanged("Indexer[" + v + "]");
  }
}
```

**Comment by mdonogma** [comment]
Any working example of indexer approach available? I have .net standard with Xamarin forms but need working guidance on above code snippet using indexer

**Comment by cabal95** [comment]
Not sure if anybody is still looking for a work-around type solution to this, but we ended up using this:

https://github.com/MobileEssentials/DynamicForms/blob/master/src/Xamarin.Forms.Dynamic.Desktop/DictionaryModel.cs

We made a small change to the GetTypeInfo() method so that it would check for a real property (say defined in a subclass) before checking/returning a value from the dictionary.

**Comment by StalinSVD** [comment]
> Not sure if anybody is still looking for a work-around type solution to this, but we ended up using this:
> 
> https://github.com/MobileEssentials/DynamicForms/blob/master/src/Xamarin.Forms.Dynamic.Desktop/DictionaryModel.cs
> 
> We made a small change to the GetTypeInfo() method so that it would check for a real property (say defined in a subclass) before checking/returning a value from the dictionary.

Thanks a lot, that worked!

**Comment by anpin** [comment]
hello everyone, I'm wondering if something had changed and DynamicObjects are actually working on iOS now since they are mentioned in the [Xamarin.iOS documentation](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject?view=xamarinios-10.8)?

**Comment by jfversluis** [comment]
Looks like we at least have a workaround for this. This is probably not something that we're still going to fix for Xamarin.Forms. If this is still an issue with .NET MAUI, please consider opening an issue there with all the latest info. Thank you for all the input and effort here!
