### ISSUE TITLE
Device.IsInvokeRequired throws COMException on UWP

### ISSUE THREAD

**Issue by miroslav22** [xamarin/Xamarin.Forms#3179]
### Description

Device.IsInvokeRequired throws COMException when calling it from a thread *other* than the main GUI thread on UWP for Xamarin.Forms

Ex thrown System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.ApplicationModel.LockScreen.LockApplicationHost.GetForCurrentView()
   at Xamarin.Forms.Platform.UWP.WindowsBasePlatformServices.get_IsInvokeRequired()
   at Xamarin.Forms.Device.get_IsInvokeRequired()
   at TestMobileApp.MainPage.<>c.<.ctor>b__0_0()

Was working before I updated Visual Studio to latest version (see screenshot below)

### Steps to Reproduce

Use this code in MainPage of Xamarin.Forms App:

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TestMobileApp
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
            

		    Task.Run(() =>
		    {
		        try
		        {
		            Debug.WriteLine("Testing");

		            var test = Device.IsInvokeRequired;

		            Debug.WriteLine("Is invoke req: " + test);
		        }
		        catch (Exception ex)
		        {
		            Debug.WriteLine("Ex thrown " + ex);
		        }
		    });
        }
	}
}

### Expected Behavior
No Exception to be thrown, return true as not on main thread and invoke required

### Actual Behavior
Exception thrown as above

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: n/a
  - UWP:  16299 (happens in all that I've tried)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:  Running on local Windows machine

### Screenshots
![image](https://user-images.githubusercontent.com/1083535/42045372-4bc281f4-7af3-11e8-95b9-9794a4e5bc38.png)

**Comment by PureWeen** [comment]
@miroslav22  what version of Xam Forms are you on? This looks like something that was fixed in the latest 3.1 version

**Comment by miroslav22** [comment]
Apologies it does indeed work okay in Forms 3.1.

I Should have checked for a newer version!

Thanks :)
