### ISSUE TITLE
Need of method to set BindableProperty value that could be overridden from implicit Style

### ISSUE THREAD

**Issue by hshristov** [xamarin/Xamarin.Forms#3185]
Hi team,

There is a need for a method that sets `BindableProperty` current value but is with less priority from everything else (like style setter, local value, etc.) except BindableProperty.DefalutValue.
The use case is that I have custom control that should be with specific colors, fonts, etc. but I still want to allow developers to target my control and override these properties from implicit style.

There is a nice internal method [internal void SetValue(BindableProperty property, object value, bool fromStyle)](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BindableObject.cs#L349) that have last parameter `bool fromStyle` and this is exactly what is needed here.
Do you think there is an option to make this method public or expose similar one that will allow this use-case?

**Comment by hshristov** [comment]
@hartez @paulbatum Why don't you close this issue?  As it seems you don't plan to even triage it...

**Comment by hartez** [comment]
@hshristov Apologies, somehow this fell through the cracks in our triage process. We're working to address that. In the meantime, it's @pauldipietro you mean to ping, not Paul Batum.

**Comment by hshristov** [comment]
@hartez Thanks for the feedback and sorry for the wrong ping (autocomplete...)

**Comment by hshristov** [comment]
@hartez @pauldipietro Any progress on this request?

**Comment by samhouts** [comment]
@StephaneDelcroix Do you see an issue with exposing a version of `SetValue`? Thanks!

**Comment by StephaneDelcroix** [comment]
I'm not comfortable to open the SetValue overload, as it prevents future work on that area.

OTOH, if I'm not open to the solution proposed here, I'm all ears to the problem. I might miss something here, but it looks like you should be able to do that using defaultValue or defaultValueCreator, unless you inherit your control from one of ours.

Setting the default values in the default constructor is definitely not the recommended way, and we actually changed from that to what we use right now with Frame.Padding.

If this doesn't help you, I'd like a better explanation of what you're trying to achieve, ideally with a very small code sample. Even if we can't make the method public, there's probably something we can do

**Comment by hshristov** [comment]
@StephaneDelcroix There are two problems here:

- First we have composite controls (control that is build from other controls) and we want to be able to set values on those inner controls but still allow developers to use implicit styles in order to restyle these controls
- The second problem is about theming. We want to be able to change the values of some BindableProperties so that our controls looks like your material controls but still enable developers to restyle any control using implicity style.
We have three type of controls: composite controls (one that are using ControlTemplate), Skia controls and native controls (e.g. those using Renderers).
For composite controls we don't want to inherit from every control in order to override the method that is called by `defaultValueCreator` (if there is such method because some properties doesn't expose such virtual method). We want to be able set their inital values and still support implicit styles.
For Skia controls we have properties that are backing `BindableProperties` but if we go and set them directly (when `VIsual="Material"`) developer won't be able to know the real value of the BindableProperty. We can't use `defaultValueCreator` beause Visual property is set very late in the process.
Same problem apply for our native controls. We know how to map `BindableProperty` to native property but they value of `BindableProperty` and the value of the native control will differ. (For example once we create the native control we will check if Visual is Material and then we will go and apply some properties from our palette to the native control in order to make it look Material. But the value of the `BindableProperty` will be the default value. If we set `BindableProperty` to the same value from material palette we will not allow developers to target this property using Styles).

I will be happy to provide more information if needed.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
