### ISSUE TITLE
Java.Lang.NoSuchMethodError: no method with name='isInLayout' signature='()Z on Android 4.1.2

### ISSUE THREAD

**Issue by matteozoni** [xamarin/Xamarin.Forms#3186]
I have updated Xamarin.Form to the version 3.1.0.583944. 

Running my application on Android 4.1.2 I get the error "Java.Lang.NoSuchMethodError: no method with name='isInLayout' signature='()Z' in class Landroid/view/ViewGroup;". On Android 8.0 works fine.

Microsoft Visual Studio Community 2017 
Versione 15.7.4
VisualStudio.15.Release/15.7.4+27703.2035
Microsoft .NET Framework
Versione 4.7.03056

Edizione installata: Community

ASP.NET and Web Tools 2017   15.0.40601.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.7.31476
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40608.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.0.40617.0
Azure Functions and Web Jobs Tools

Gestione pacchetti NuGet   4.6.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web http://docs.nuget.org/.

Merq   1.1.19-rc (a4ffc1b)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

Pacchetto di Strumenti Application Insights per Visual Studio   8.12.10405.1
Strumenti Application Insights per Visual Studio

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Servizio di linguaggio JavaScript   2.0
Servizio di linguaggio JavaScript

SQL Server Data Tools   15.1.61804.210
Microsoft SQL Server Data Tools

Strumenti C#   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Componenti di C# usati nell'IDE. A seconda delle impostazioni e del tipo di progetto, potrebbe essere usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti di Microsoft Azure   2.9
Strumenti di Microsoft Azure per Microsoft Visual Studio 2017 - versione 2.9.10420.2

Strumenti di recapito continuo Microsoft per Visual Studio   0.3
Consente di automatizzare la configurazione dell'integrazione di compilazione continua e del recapito di compilazione continua direttamente dall'IDE di Visual Studio.

Strumenti TypeScript   15.7.20419.2003
Strumenti TypeScript per Microsoft Visual Studio

Strumenti Visual Basic   2.8.3-beta6-62923-07. Commit Hash: 7aafab561e449da50712e16c9e81742b8e7a2969
Componenti di Visual Basic usati nell'IDE. A seconda delle impostazioni e del tipo di progetto, potrebbe essere usata una versione diversa del compilatore.

Visual F# Tools 10.1 per F# 4.1   15.7.0.0.  Commit Hash: 173513e369ffb7a1c4d5dccf83696d9aac2ab2d0.
Microsoft Visual F# Tools 10.1 per F# 4.1

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.10.10.2 (35a01d8dc)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   4.12.1 (f3257e429)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by arino-godinho** [comment]
I have same issue...

**Comment by rspulini** [comment]
I have same issue...

**Comment by kingces95** [comment]
@rspulini @arino-godinho @matteozoni Could you attach a small reproduction?

**Comment by GalaxiaGuy** [comment]
It believe it was introduced here:

https://github.com/xamarin/Xamarin.Forms/commit/92b7f1f5477e5804530c3af03fd8cb5842106a1e#diff-22025e2a9c1807b8efa13c3309de99a4

`View.IsInlayout` was introduced in API 18 (Android 4.3).

The only other place that references it has a version check:

https://github.com/xamarin/Xamarin.Forms/blob/14af670f5a200d164284fa4f0b3e4f7ce03b53df/Xamarin.Forms.Platform.Android/VisualElementTracker.cs#L193

**Comment by arino-godinho** [comment]
@kingces95 Sample tested with Android 4.2 emulator - API 17

**Reproduction Link** 
[AppSampleIssue3186.zip](https://github.com/xamarin/Xamarin.Forms/files/2176331/AppSampleIssue3186.zip)

**Comment by LiamReynaud** [comment]
Hi,
What is the minimum downgrade XF version to not having this issue?

**Comment by tmt242001** [comment]
I also have same issue...

**Comment by rspulini** [comment]
I am with version 3.1.0 but still the error continues

**Comment by rspulini** [comment]
can you help me? api 17 version

**Comment by hartez** [comment]
The fix is in a service release slated to come out soon (it's currently winding its way through the testing process).

**Comment by deczaloth** [comment]
Two and a half moths since the last update.

@hartez @kingces95 @samhouts , are there any news on this topic?

**Comment by GalaxiaGuy** [comment]
@deczaloth 

It has been tagged `beta-3.2.0-pre2` which was released "2 months ago".

https://www.nuget.org/packages/Xamarin.Forms/3.2.0.729530-pre2
