### ISSUE TITLE
Environment.SpecialFolder.Personal Returns Locked Path

### ISSUE THREAD

**Issue by NickDevoctomy** [xamarin/Xamarin.Forms#3192]
### Description

The special folder path Environment.SpecialFolder.Personal on my Galaxy S8 returns a path that I can store files in, but it's in a hidden "root only" area that I can't view either when browsing on my PC via USB, or on the device itself (unless I route).

Even though the path is

/data/user/0/…

I can't access the files I'm creating.  I don't know if this is specific to the Galaxy S8.

The following all produce the same result,

System.Environment.SpecialFolder.ApplicationData
System.Environment.SpecialFolder.MyDocuments
System.Environment.SpecialFolder.Personal

### Steps to Reproduce

1.  Create a file in Environment.SpecialFolder.Personal
2.  Attempt to find it on your device, using any non-rooted method
3.  Note that you cannot even see the file, but the app can.

### Expected Behaviour

I should be able to access anything in Environment.SpecialFolder.Personal, so the path should be accessible.  Otherwise it's not a personal path if the user can't even get to the data within it.

### Actual Behaviour

Data gets "lost", although the application can read/write it fine, the user cannot access it.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - Android: 8.0.0
- Nuget Packages:
 - Xamarin.Android.* (27.0.2.1)
 - Xamarin.Forms (3.1.0.583944)
- Affected Devices:
 - Galaxy S8

### Reproduction Link

https://1drv.ms/u/s!AlN90gKdry3-tKdzo__P9p5UuUHaww

### What Is Your Favourite Colour?

Orange

**Comment by NickDevoctomy** [comment]
I've got a work around for now by not using the special folder paths at all, instead in my android build I can use the Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDocuments).AbsolutePath value and derive a suitable location from that.  It does require that I add the relevant permissions, but that's to be expected.

**Comment by hartez** [comment]
This is working as intended.

**Comment by NickDevoctomy** [comment]
If the same API on Windows devices produces a folder that can be accessed, but the Android one doesn't.  Isn't that then an inconsistent set of APIs? *curious*

**Comment by NickDevoctomy** [comment]
I understand that,  but from this perspective,  if I open "My Files" app on my phone and then open the "Documents" folder,  it's reasonable to expect that folder to be "My Documents", it isn't. I understand this is probably an issue with .NET standard as opposed to Xamarin though.
