### ISSUE TITLE
TabbedPage as Master on MasterDetailPage problems

### ISSUE THREAD

**Issue by pavelcleveland** [xamarin/Xamarin.Forms#3194]
### Description
The issues could be reproduced for Xamarin Forms 3.1 (2.5 doesn't have this problem) for iOS platform only.
 took an example of Master Detail page from here

https://developer.xamarin.com/samples/xamarin-forms/Navigation/MasterDetailPage/MasterDetailPage.zip

and slightly modified it by changing Master page from Content to TabbedPage.
### Steps to Reproduce
When application starts (again iOS only all is OK for Android and UWP)

1. Master shows overlapping Detail (like IsPresented = true but it is not)
2. Master looks frozen upon start. The only way to make it moving is a click on "Contact" icon which. overlaps "sandwich" icon - master page with slide out.
3. Click on sandwich button to bring master page back over and select Tab 2
Click inside of Entry box and all page content slides to the right of master page and becomes inaccessible

### Expected Behavior
Upon application start master page should be hidden by default.
Clicking inside of Entry box should not make page contents to disappear

### Actual Behavior
Upon application start master page overlaps detail and not responsive.
Clicking inside of Entry box on tabbed page Tab2 makes all page contents diaapear

### Basic Information

- Version with issue:
3.1
- Last known good version:
2.5
- IDE:
Visual Studio for Mac 7.5.3
- Platform Target Frameworks: 
  - iOS:  
11.12
  - Android:  
N/A
  - UWP:   
N/A
- Android Support Library Version: 
N/A
- Nuget Packages:
Xamarin.Forms 3.1
- Affected Devices:

### Reproduction Link

Download project from here:
https://developer.xamarin.com/samples/xamarin-forms/Navigation/MasterDetailPage/MasterDetailPage.zip

Update MasterPage from here:
<?xml version="1.0" encoding="UTF-8"?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" 
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="using:MasterDetailPageNavigation"
			 x:Class="MasterDetailPageNavigation.MasterPage"
			 Padding="0,200,0,0"
			 Icon="hamburger.png"
			 Title="Personal Organiser">

    <ContentPage Title="Tab 1">
        <StackLayout>
            <ListView x:Name="listView" x:FieldModifier="public">
               <ListView.ItemsSource>
                    <x:Array Type="{x:Type local:MasterPageItem}">
                        <local:MasterPageItem Title="Contacts" IconSource="contacts.png" TargetType="{x:Type local:ContactsPage}" />
                        <local:MasterPageItem Title="TodoList" IconSource="todo.png" TargetType="{x:Type local:TodoListPage}" />
                        <local:MasterPageItem Title="Reminders" IconSource="reminders.png" TargetType="{x:Type local:ReminderPage}" />
                    </x:Array>
                </ListView.ItemsSource>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Grid Padding="5,10">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="30"/>
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>
                                <Image Source="{Binding IconSource}" />
                                <Label Grid.Column="1" Text="{Binding Title}" />
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </StackLayout>
    </ContentPage>

    <ContentPage Title="Tab 2">
        <StackLayout>
            <Label Text="Enter:"/>
            <Entry />
       </StackLayout>
    </ContentPage>
</TabbedPage>

**Comment by hartez** [comment]
I'm attempting to reproduce this behavior using the repro project below. So far, I have not been able to (everything appears to work fine). Is there a step I might be missing?
[MasterDetailPageNavigation Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2168359/MasterDetailPageNavigation.Repro.zip)

**Comment by pavelcleveland** [comment]
[MasterDetailTabbedPage .zip](https://github.com/xamarin/Xamarin.Forms/files/2170199/MasterDetailTabbedPage.zip)
Here is the the project with updated Master page

**Comment by pauldipietro** [comment]
The master is in unresponsive for me in the repro, as described.

**Comment by rmarinho** [comment]
Can you add this on your iOS project?


[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(TabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)] 

See if it helps on 3.0.0 or 3.1.0 versions

**Comment by pavelcleveland** [comment]
I tried to add ExportRenderer to Main.cs and also tried to create a separate class to make sure it gets called by putting a breakpoint on ViewDidLoad and it does get called but the problem is still there.

Do I need to have any specific code in this renderer?

Here is a renderer class I used:

using System;
using MasterDetailPageNavigation.iOS;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(SimpleMasterDetailPageRenderer), UIUserInterfaceIdiom.Pad)]
namespace MasterDetailPageNavigation.iOS
{
    public class SimpleMasterDetailPageRenderer : TabletMasterDetailRenderer
    {
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
        }
    }
}

**Comment by rmarinho** [comment]
Oh you don't need a new renderer just the export. 

[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(TabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)]

What's the Xamarin.Forms version?

**Comment by pavelcleveland** [comment]
Well, I tried both. 

3.1.0.697729

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
