### ISSUE TITLE
ListView separators on iOS have space/gap on left side. Cannot be fixed with margin property.

### ISSUE THREAD

**Issue by greg84** [xamarin/Xamarin.Forms#3196]
### Description

ListView separators on iOS have a gap on the left hand side.

### Steps to Reproduce

1. Create a new page.
2. Add a ListView control to the page.
3. Observe left margin for separators on iOS device.

### Expected Behavior

List view separators should span entire screen width to match the control width.

### Actual Behavior

Gap on left.

### Basic Information

- Version with issue: 3.0.0.482510
- Last known good version: n/a
- IDE: Visual studio Mac

### Reproduction XAML

```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="...">
    <ContentPage.Content>
            <ListView>
            </ListView>
    </ContentPage.Content>
</ContentPage>
```

### Screenshots

![image](https://user-images.githubusercontent.com/4529974/42138690-5e3daf4c-7d79-11e8-98e8-0b1978be8ce5.png)

**Comment by Stensan** [comment]
Hi, you can write a custom ListViewRenderer in your iOS project and set Control.SeparatorInset = UIEdgeInsets.Zero;

**Comment by greg84** [comment]
Nice - Thanks, I'll do that!
