### ISSUE TITLE
UITest: Problems with Backslashes

### ISSUE THREAD

**Issue by laDanz** [xamarin/Xamarin.Forms#3197]
### Description
Regarding the AppQuery:
`app.WaitForElement(c => c.Marked("123\\456")) is working, while`
`app.WaitForElement(c => c.Marked("D\\A")) is not.`

### Steps to Reproduce

1. See attached example project.
[BackslashQueryDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2155079/BackslashQueryDemo.zip)
2. Build
3. Run test.

### Actual Behavior
See attached error log.
Caused by: NoViableAltException('\\'@[])
[calaba_exception.txt](https://github.com/xamarin/Xamarin.Forms/files/2155084/calaba_exception.txt)

### Basic Information

- Version with issue: Xamarin.UITest Version=2.2.4
- Last known good version: n/a
- IDE: Visual Studio 2017 Professional
- Platform Target Frameworks: 
  - Android: targetSdkVersion="27"

### Screenshots
none

**Comment by jmoody** [comment]
Can you try escaping the backslash?

```
app.WaitForElement(c => c.Marked("123\\456")) is working, while
app.WaitForElement(c => c.Marked("D\\A")) is not.
```

**Comment by laDanz** [comment]
How?

Isn't it already escaped?

Joshua Moody <notifications@github.com> schrieb am Do., 12. Juli 2018,
13:49:

**Comment by jmoody** [comment]
```
D\A => D + alert bell
```

Are you searching for D + alert bell?  Or the string "D\A"?

If you are looking for the string "D\A", try escaping the backslash using `D\\A` or `D\\\A`.

**Comment by jmoody** [comment]
> app.WaitForElement(c => c.Marked("D\\A")).Any()

Now that looks more like a bug.

Does this also happen in iOS?

**Comment by jmoody** [comment]
We are tracking internally.   I cannot provide any information about when or if this issue will be resolved.

Thank you for reporting and thanks for clarification!

**Comment by AndreyMitsyk** [comment]
Issue has been resolved. Will be a part of the next Xamarin.UITest dev release.
