### ISSUE TITLE
Image view flicker when change parent view

### ISSUE THREAD

**Issue by rtnm** [xamarin/Xamarin.Forms#3198]
### Description

`Image` view flicker when change parent view, but only for `Source` retrieved `ImageSource.FromResource("")`

The problem is better seen on the device than on the emulator.

### Steps to Reproduce

```
using System;

using Xamarin.Forms;

namespace FlickerProject {
    public class FlickerPage: ContentPage {

        AbsoluteLayout al;
        Image image1;
        Image image2;
        Image image3;

        public FlickerPage() {
            al = new AbsoluteLayout();
            al.VerticalOptions = LayoutOptions.FillAndExpand;

            image1 = new Image { Source = ImageSource.FromResource("FlickerProject.example-app.png") };
            al.Children.Add(image1);
            AbsoluteLayout.SetLayoutBounds(image1, new Rectangle(50, 50, 200, 100));

            image2 = new Image { Source = ImageSource.FromUri(new Uri("https://xamarin.com/content/images/pages/forms/example-app.png")) };
            al.Children.Add(image2);
            AbsoluteLayout.SetLayoutBounds(image2, new Rectangle(50, 150, 200, 100));

            image3 = new Image { Source = ImageSource.FromFile("example-app.png") };
            al.Children.Add(image3);
            AbsoluteLayout.SetLayoutBounds(image3, new Rectangle(50, 250, 200, 100));

            var button = new Button { Text = "Test" };
            button.Clicked += Button_Clicked;

            var stack = new StackLayout();
            stack.Children.Add(al);
            stack.Children.Add(button);

            Content = stack;
        }

        void Button_Clicked(object sender, EventArgs e) {
            al.Children.Remove(image1);
            al.Children.Remove(image2);
            al.Children.Remove(image3);

            al.Children.Add(image1);
            AbsoluteLayout.SetLayoutBounds(image1, new Rectangle(50, 50, 200, 100));

            al.Children.Add(image2);
            AbsoluteLayout.SetLayoutBounds(image2, new Rectangle(50, 150, 200, 100));

            al.Children.Add(image3);
            AbsoluteLayout.SetLayoutBounds(image3, new Rectangle(50, 250, 200, 100));
        }

    }
}
```

### Expected Behavior

There is no flicker in all cases

### Actual Behavior

`Image` view flicker when change parent view, but only for `Source` retrieved `ImageSource.FromResource("")`

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0.583944
- Last known good version: -
- IDE: Visual Studio for Mac 7.5.3 (build 7)
- Platform Target Frameworks:
  - iOS:  11.4
- Nuget Packages: -
- Affected Devices: iPhone 7

**Comment by rtnm** [comment]
For Android:
* FromResource - flicker
* FromUri - flicker
* FromFile - no flicker

**Comment by hartez** [comment]
Repro project:

[_3198 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2167641/_3198.Repro.zip)

The flicker also occurs on iOS when using FromResource, and on UWP using all three methods.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
