### ISSUE TITLE
Replace all occurences of FileImageSource with ImageSource

### ISSUE THREAD

**Issue by rogihee** [xamarin/Xamarin.Forms#3207]
### Description
In order to be able to use other image sources such as SVG based ones all Core controls and renderers should use `ImageSource ` instead of `FileImageSource`.

When the Core is updated, renderers should also be updated to never assume a `FileImageSource`.

These are the occurrences I could track down in Core and other Platform renderers:

### Core
1. `Button.Image`
2. `MenuItem.Icon`
3. `NavigationPage.TitleIcon`
4. `Page.Icon`
5. `Slider.ThumbImage`

### Android
1. NavigationPageRenderer toolbar icon
2. TabbedPageRendererer tab icon
3. ImageViewExtensions that is used by BaseCellView
4. Fastrenderers Button.Image
5. Platform title Icon

### iOS
1. ButtonRenderer image
2. NagivationRenderer title image
3. SliderRenderer thumb image

### UWP
None.

See also:  #1955

**Comment by ysmoradi** [comment]
Any news?
+1

**Comment by groege** [comment]
Is there a way to speed this up? It shouldn't be that big of a change right?

**Comment by MelbourneDeveloper** [comment]
Is this on its way?
