### ISSUE TITLE
Bindings function improperly (fire repeatedly) under debug mode

### ISSUE THREAD

**Issue by pfaucon** [xamarin/Xamarin.Forms#3211]
Edit: Updated description

### Description
When running normally a data binding update fires once (expected), but when running with a breakpoint in the setter the data binding fires indefinitely. 

Also empirically it seems to accelerate/stack calls, wherein if I am quick to close the keyboard at the beginning it closes, but after a few seconds the keyboard is unable to close before opening again 

### Steps to Reproduce

open the project:
[EntryTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2162397/EntryTest.zip)

or
create a new project (XF, cross platform)
replace the ItemsViewModel and ItemsPage with https://gist.github.com/pfaucon/c01effa8eeea39112078fadaace7cea8 (essentially just adding the entry)

1. run the application with a breakpoint in the setter
2. type "..", to trigger the setter reseting the value to 0 (it seems to fire on the first "." too)

### Expected Behavior
it should be behave the same under the debugger as without.  Specifically it should not spam the setter indefinitely

### Actual Behavior
it spams the setter indefinitely when a breakpoint is set 

### Basic Information

- Version with issue: 2.5.1.44934 (prod), 3.0.0.446417 (for our test)
- Last known good version: NA
- IDE: VS for mac
- Platform Target Frameworks: 
  - iOS:  9.0 (prod) 11.4 (test)

### Screenshots

https://www.useloom.com/share/d1d604020ea145298e76f3ce98f8dc86

### Reproduction Link

project file is attached, it is simple to trigger

**Comment by hartez** [comment]
I cannot reproduce the reported behavior on VS for Mac or VS for Windows.

Which line of the setter are you placing the breakpoint on?

**Comment by pfaucon** [comment]
It's in the video that I attached:
https://www.useloom.com/share/d1d604020ea145298e76f3ce98f8dc86

when I triggered it I don't think it mattered which line I put the breakpoint on, as long as the breakpoint was hit.  I'm having trouble loading the video at the moment, but I think it was on line 72 or 73 though (the first 2 lines of the setter).

Here is a dump of the VS information:

=== Visual Studio Community 2017 for Mac ===

Version 7.5 (build 1254)
Installation UUID: 60293d52-0aa2-45f2-94c9-8fc0f91e6a62
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.0.36 (master / 0c7c49a6)

	Package version: 510010047

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.176 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/<me>/Library/Android/sdk
	Supported Android versions:
		4.4 (API level 19)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 27.0.2

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705001254
Git revision: 498923ea36d2c7fe440c4e4b8cfb75bd50bbd748
Build date: 2018-05-05 10:35:24-04
Xamarin addins: 219f1c4943b4693b837b4173dd10ea982a47c852
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

**Comment by PureWeen** [comment]
@pfaucon  I feel like this is more related to just a quirk of the iOS Simulators and not a bug with XF or Xamarin in General

For example if I 
-open up safari on the ipad simulator
-hit period and click off ipad in the url bar
-it'll just type a bunch of periods

**Comment by pfaucon** [comment]
Good point, I can replicate the same so I guess it is a bug in the iOS simulator itself then.  I'm closing the issue, thank you for your help
