### ISSUE TITLE
Get error when using FlexLayout with Xamarin Live Player

### ISSUE THREAD

**Issue by ColeXm** [xamarin/Xamarin.Forms#3212]
Xamarin Forms Version: 3.1.0583944 
Xamarin Live Player Version : beta V1.5.196 (696)

Error : 

**Position 7:6. Type FlexLayout not found in xmlns http://xamarin.com/schemas/2014/forms          
Dependent project myProject.csproj failed to build, using old version.**

**Comment by hartez** [comment]
@ColeXm Is this happening in a new project, or an existing project you have updated to 3.1? Are you using VS for Windows or VS for Mac?

**Comment by alberk8** [comment]
Does not work for VS for Windows.   Do not have VS Mac to test.

**Comment by biozal** [comment]
Can confirm it is happening once upgrading to Forms v3.1.0.697729

**Comment by AJLewis** [comment]
I can confirm that FlexLayout will not allow Xamarin Live Player to launch using the following:
Forms: v3.1.0.697729
Visual Studio For Mac
Google Pixel XL

**Comment by fgiacomelli** [comment]
same for me

**Comment by PureWeen** [comment]
LivePlayer is not supported by this team (and probably not supported anymore). closing.
