### ISSUE TITLE
Xamarin Forms WebView ignores port

### ISSUE THREAD

**Issue by martinguess** [xamarin/Xamarin.Forms#3213]
### Description

Xamarin Forms WebView ignores port whent setting WebView.Source (IOS only) in version 3.0.0.561731 and later.

### Steps to Reproduce

1. Create a new project with a simple WebView (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview)
2. Set url with non-standard port: this.Browser.Source = "http://portquiz.net:8080/";

### Expected Behavior

App should open the url with port 8080.

### Actual Behavior

App open the url with port 80.
Website shows "You have reached this page on port 80."
On IOS Only!

### Basic Information

- Version with issue: 3.0.0.561731 and later
- Last known good version: 3.0.0.550146
- IDE: Visual Studio 2017 Community
- Platform Target Frameworks: 
  - iOS:  11.4 
- Nuget Packages: Xamarin.Forms 3.0.0.561731
- Affected Devices: all (simulator and device)

### Screenshots

![screenshot](https://user-images.githubusercontent.com/1926297/42268356-8a4c770e-7f7b-11e8-90cf-8cf83d2d04a1.png)

**Comment by hartez** [comment]
This was fixed by PR #3120.
