### ISSUE TITLE
Exception has been thrown by the target of an invocation when building with Xaml compilation enabled and setting Margin property on FlexLayout

### ISSUE THREAD

**Issue by kpespisa** [xamarin/Xamarin.Forms#3226]
### Description
Exception has been thrown by the target of an invocation when building with XamlC compilation enabled and setting Margin property on FlexLayout

### Steps to Reproduce

1. Create a Xamarin Forms project
2. Create a content page or view using XAML
3. Include a FlexLayout 
4. Set the Margin Property of that FlexLayout
5. Enable Xaml Compilation [assembly: XamlCompilation(XamlCompilationOptions.Compile)]

### Expected Behavior
Margin values are respected. 

### Actual Behavior
Error mentioned above 

### Basic Information
In the Visual Studio Xaml Preview the margin works fine. This also works fine when building without Xaml compilation.

- Version with issue:
- Last known good version: Unknown
- IDE: Visual Studio Mac
- Platform Target Frameworks: Xamarin.Forms 3.0 and 3.1

**Comment by hartez** [comment]
@kpespisa I am trying to reproduce this issue and so far I have not been able to. Can you post a minimal repro project or take a look at mine below and tell me what I am missing?

[_3226 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2169074/_3226.Repro.zip)

**Comment by kpespisa** [comment]
Thanks. I was able to reproduce the issue if I set the margin to

`Margin="0 0 0 10"`

**Comment by pauldipietro** [comment]
I don't know if this is a bug or not. Using commas will fix the issue and allow the app to run, and the same comma-less margin being applied to a StackLayout will cause the same error. Perhaps there is better potential error messaging here.

@StephaneDelcroix

**Comment by mflplatinum** [comment]
True the commas allow the code to compile without an error, but then the layout loses the margin

**Comment by kpespisa** [comment]
True the commas allow the code to compile without an error, but then the layout loses the margin.

**Comment by StephaneDelcroix** [comment]
There are 2 syntaxes for margins. One with comma, used in xaml: “l, t, r, b” and one for CSS without comma “t r b l” (notice the different argument ordering”. 

If you disable XamlC, the runtime parser is permissive enough to allow, and recognize both syntaxes, but you shouldn’t rely on that. 

Now, make sure you have your arguments ordered correctly, and report back if you still can’t get the margins to work on flexlayout. 

@pauldipietro not a bug to me

**Comment by kpespisa** [comment]
Thank you, I did not realize the differences between the two syntaxes. I'm new to Xaml, and I was looking at an example site using the CSS style syntax so I assumed adding the commas was just optional.
