### ISSUE TITLE
Feature Request - Default Search Directory for UWP Icons (Platform Specific)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#3228]
I would really like to put all of my icons/images inside of the `Assets` folder, however this creates some not so great looking code:

```
<Image>
                <Image.Source>
                    <OnPlatform x:TypeArguments="ImageSource">
                        <On Platform="iOS" Value="icon_twitter.png"/>
                        <On Platform="Android" Value="icon_twitter.png"/>
                        <On Platform="UWP" Value="Assets/icon_twitter.png"/>
                    </OnPlatform>
                </Image.Source>
            </Image>
```

Ideally I would like to do:

```xml
<Image Source="icon_twitter.png"/>
```

I could do this if I put it into the UWP root, but that clutters up the project if it is large.

I would like something like:

```
On<UWP>().SetImageSearchDirectory("Assets");
```

Then my nice pretty Image would work.

**Comment by samhouts** [comment]
related to #2235

**Comment by jsuarezruiz** [comment]
I loved the idea. I have sent [PR](https://github.com/xamarin/Xamarin.Forms/pull/3420).
I have created **Platform Specific** at the Application level.

Example:
`On<UWP>().SetImageSearchDirectory("Assets");`

**Comment by Aculeo** [comment]
For future readers arriving here, I guess it's been renamed. (Why is this not part of the documentation?)

```
Xamarin.Forms.Application.Current.On<Windows>().SetImageDirectory("Assets");
```

This is how I got it working.
