### ISSUE TITLE
Feature Request - Toolbar Elevation - Android Platform Specific

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#3231]
We have **SetElevation** which works on elements, however there is no way to set the elevation of the toolbar. Currently we have to go into the Toolbar.axml and specify:

```
    android:elevation="6dp"
```

However, that is app wide and we don't want to use this if using tabs on top, so we will need to be able to set this on a page by page basis.

API could simply be the SetElevation on navigation page?

**Comment by rajeshjha7868** [comment]
Please enable this feature as this is the primary need for a good UI.

**Comment by hartadi** [comment]
can we use
`android:elevation="0dp"`
to remove drop shadow?

**Comment by jfversluis** [comment]
Won't be doing this for Forms anymore! Labelling it for consideration for .NET MAUI
