### ISSUE TITLE
Feature Request - Button IsPressed Property

### ISSUE THREAD

**Issue by ChasakisD** [xamarin/Xamarin.Forms#3232]
### Description
Right now, there is a IsFocused Property on the VisualElement class. Since IButtonController contains SendPressed and SendReleased, i think there should be a way to find if the button is pressed. 

By doing that, a common visual state could be created and named "Pressed". So inside the Button class the SendPressed will make IsPressed to true and SendReleased back to false. In addition to the property SendPressed could GoToState "Pressed" and SendReleased GoToState "Normal". This will help on situations where you want to change the icon color when it is pressed and you do not want to create a custom class that inherits from Button and on each Pressed, Released event will go to each state.

**Comment by jfversluis** [comment]
Thanks for your interest in this! This won't be happening in Xamarin.Forms anymore. If you still want this to happen, please make sure to open a feature request on the .NET MAUI repo.

Thanks
