### ISSUE TITLE
EntryCell in iOS not left aligned

### ISSUE THREAD

**Issue by rohitvipin** [xamarin/Xamarin.Forms#3240]
### Steps to Reproduce

1. Create a new Xamarin forms solution in 3.1.0
2. Create a tableview, add entry cell to its root. 
3. Run on iOS

### Expected Behavior
Entry cell is left aligned. 

### Actual Behavior
Entry cell is not left aligned (a left padding of ~100 is present)
The calculation [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs#L149) seems off and create a value of 96 when running against iPhone X, if it set start to 0, everything works fine.  

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 3.0
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: 8.1
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone, iPad, iPod

### Screenshots
![simulator screen shot - iphone x - 2018-07-09 at 12 30 00](https://user-images.githubusercontent.com/11459048/42435392-01f3e174-8374-11e8-8890-492a4f567fd5.png)

**Comment by pauldipietro** [comment]
Confirmed occurring against 3.1.

**Comment by AndreiMisiukevich** [comment]
@rohitvipin do you want get it without side padding?

**Comment by rohitvipin** [comment]
Isn't that the default behaviour if create it directly in iOS?

**Comment by rohitvipin** [comment]
Is this somewhere fixed? Or still open?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Mengshishishi** [comment]
This issue appears in iOS 14, the TextLabel is not aligned when rendering cells as UITableViewCell.

**Comment by Redth** [comment]
Can you please provide a repro sample?

**Comment by Mengshishishi** [comment]
The issue happens in iPhone 11, iPhone 12, and iPhone 12 mini. It appears regardless of which version of iOS. 
![image](https://user-images.githubusercontent.com/17246916/103792433-edf1a680-5043-11eb-95e5-29950557c7e7.png)

**Comment by Redth** [comment]
Can you please attach a sample project which reproduces the issue?

**Comment by PureWeen** [comment]
Closing this issue for now. If you can attach a reproduction we can re-open
