### ISSUE TITLE
Android: Navigating back from page with HasNavigationBar=false resizes page incorrectly

### ISSUE THREAD

**Issue by GiorgioGe** [xamarin/Xamarin.Forms#3242]
### Description
We have detected the same problem for Android as described under #2178 for iOS.
"We have a problem where the content of a page(1) WITH NavigationBar is cut off at the bottom when navigating BACK from a page(2) WITHOUT NavigationBar. Seems like the page is incorrectly updating its size on reappearing based on the old value of NavigationBar.HasNavigationBar."

### Steps to Reproduce

1. You have Page1 with a NavigationBar.
    Page1 has two Labels. LabelA FillAndExpands and LabelB is 70 pts in height.
2. Push Page2 with no NavigationBar, HasNavigationBar=false
3. Now pop Page2 and witness that LabelB is cut off

### Expected Behavior
Page1 shows the whole content on reappearring
### Basic Information
Page1 content is cut off by the same amount of height as the iOS NavigationBar.

- Version with issue: -
- Last known good version:- 
- IDE:
   Visual Studio 2017
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 
- Nuget Packages:
  Xamarin.Forms v3.1.0.583944
- Affected Devices:

### Screenshots
See #2178

### Reproduction Link
See #2178

**Comment by pauldipietro** [comment]
Using the referred issue's reproduction with 3.1, the bar at the bottom shows as expected on an iPhone X and 8 simulator. Please provide an updated reproduction if possible.

**Comment by GiorgioGe** [comment]
We are a little under pressure, but I will provide the updated reproduction as soon as possible.

**Comment by samhouts** [comment]
@GiorgioGe Since we haven't heard from you in 30 days, we hope that this issue no longer affects you. If it does, please feel free to reopen this issue and provide the updated reproduction project. Thank you!
