### ISSUE TITLE
[Android] D-pad navigation does not work

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#3247]
As reported here: https://bugzilla.xamarin.com/show_bug.cgi?id=30894

A default Xamarin Forms application can not be navigated using the hardware d-pad on Android. This page (https://developer.android.com/training/keyboard-input/navigation
) suggests an Android app should support this by default.

The linked bugzilla suggests this is intended behavior, so this might be better classified as an enhancement.

**Comment by dev-fJ-del** [comment]
any progress on this issue? @samhouts

**Comment by samhouts** [comment]
This is still under consideration. We do tend to prioritize enhancement requests with a lot of interest, and this one seems to be less active than others. Thank you for this suggestion, and thank you for your patience!

**Comment by karsten-kuepper** [comment]
How do you count interest? I'm waiting for this. Would be awesome if you can prioritize this.

**Comment by samhouts** [comment]
Among other sources of feedback, we take into consideration the number of participants on the issue, including the number of positive reactions, commenters, etc.

**Comment by eramrit78** [comment]
Hi
I have same issue in my XF 4.6  my app rejected on play store because of this issue. It work perfect on mobile and tablets but on tv it not work. kindly resolve it asap.

**Comment by mikeoliphant** [comment]
I am also interested in support for d-pad navigation on Android.

**Comment by bitshftr** [comment]
This is critical for Android TV apps.  I need it.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
