### ISSUE TITLE
Intermittent null exception in UWP OnPageAlert()

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#3250]
### Description

I'm getting an intermittent null exception from Xamarin.Forms.Platform.UAP/PlatformUWP.cs OnPageAlert().

The culprit appears to be from the fix for #2607 "[UWP] Deadlock if you rapid fire alerts".

This code is not thread safe, specifically this block:
```
while (s_currentAlert != null)
{
	await s_currentAlert;
}

s_currentAlert = ShowAlert(alertDialog);
options.SetResult(await s_currentAlert.ConfigureAwait(false));
s_currentAlert = null;
```
https://github.com/xamarin/Xamarin.Forms/blob/8c23ad6c893b8e5b7f3fd2573c4ebde0a0441950/Xamarin.Forms.Platform.UAP/PlatformUWP.cs#L107

If two or more alerts are queued up using Device.BeginInvokeOnMainThread() then, because ConfigureAwait(false) continues in a new thread, when the first one finishes it may set s_currentAlert to null in between the null check and the await of the while loop for the second one.

A simple fix may be to:
1. Capture the s_currentAlert using in the while loop in a temporary variable
```
var currentAlert = s_currentAlert;
while (currentAlert != null)
{
  await currentAlert;
  currentAlert = s_currentAlert
}
```
2. Capture the result of ShowAlert()
```
var showAlert = ShowAlert(alertDialog);
s_currentAlert = showAlert;
options.SetResult(await showAlert.ConfigureAwait(false));
s_currentAlert = null;
```

### Steps to Reproduce

1. Queue up two or more alerts
2. Close the first alert, the null exception is intermittent

### Expected Behavior

There should be no null exception.

### Actual Behavior

There is an intermittent null exception.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: 2.5.0.280555 (likely through 3.0.0.561731)
- IDE: Visual Studio 2017 15.7.3
- Platform Target Frameworks:
  - UWP:  16299

**Comment by PureWeen** [comment]
Yea :-/ 

or maybe coalesce the check

```C#
await s_currentAlert ?? Task.Delay(0)
```

**Comment by jalbertSyncroTech** [comment]
That'll fix the first case, but you'll still need a temporary variable to fix the second case as the previous alert may have set s_currentAlert to null in between the second alert creating and awaiting it.

**Comment by PureWeen** [comment]
Can that happen? The second alert is only going to be able to create an alert once the previous alert has already set it to null. 

The while loop will only exit once this line of code
```
s_currentAlert = null;
```
Has already ran

**Comment by jalbertSyncroTech** [comment]
Sure it can: both threads are awaiting the same task, so if the 2nd alert continues first and gets paused just before `options.SetResult(await s_currentAlert.ConfigureAwait(false));`, then the 1st task will set s_currentAlert to null before the 2nd alert has a change to use it.

**Comment by jalbertSyncroTech** [comment]
never mind, I see what you meant: the 2nd alert will still be in the while loop until the 1st alert has set the s_currentAlert to null

**Comment by PureWeen** [comment]
That being said :-)  Your suggestion to assign to a local variable sits with me as a better and more clear approach.  PR has been created.
