### ISSUE TITLE
iOS HttpClient GetAsync hangs indefinitely on await

### ISSUE THREAD

**Issue by kevinrodriguez-io** [xamarin/Xamarin.Forms#3252]
### Description

iOS Application hangs indefinitely while calling HttpClient.GetAsync(...); if the internet connection dies.
I'm not using wait() or .result to block the methods, everything is being called asynchronously.

### Steps to Reproduce

1. Create a Web Api which returns a Delay for 1m on a GET REST endpoint.
2. Create Xamarin Forms Project (PCL), implement HttpClient.GetAsync to call a REST endpoint.
3. Call the Web Api endpoint.
4. On your physical ios device, disconnect the WIFI
5. Application hangs indefinitely

### Expected Behavior

If the internet connection fails, an error should be raised and the application should continue it's execution.

### Actual Behavior

The application hangs on the await directive indefinetly

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Enterprise 2017
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: N/A
  - UWP:  4.5.1
- Nuget Packages:
Microsoft.AspNet.WebApi.Client
- Affected Devices:
iPad 4 MK9N2CL/A

**Comment by pauldipietro** [comment]
Can you upload a reproduction and clarify if this only occurs on physical devices?

**Comment by jashif** [comment]
This happens to me also , am using the System.net.http version 4.0.0 , mono version 8.0 , i have a single instance httpclient and if try to call web services after 5 or 6 calls the httpclient hangs and throws operation cancelled exception. as a workaround i have to create new instance of httpclient every time. this make application low performance also. i was wondering why i cant have single httpclient instance , is it related to max no of connections to server ?.

**Comment by kartikbb** [comment]
We are also facing the same issue. Any updates on this?

**Comment by PureWeen** [comment]
@kartikbb  do you have a way we can repro?  I'm using *HttpClient GetAsync* in a number of application and I've never seen it hang so it'd be useful to have a repro as an HttpClient can be configured in a lot off different ways

**Comment by kevinrodriguez-io** [comment]
I did experience the problem by doing the following:

Create Xamarin PCL based project

Create api endpoint that downloads a big file (Aprox 100mb)
Download using getasync
Disconnect the internet while downloading.
Client hangs forever.

My HttpClient resolves the following:

Assembly System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETPortable\v4.6\Profile\Profile44\System.Net.Http.dll

**_I managed to find a workaround_** which was installing the ModernHttpClient Nuget Package in each of my Projects (Portable, Android, iOS) And changing my httpclient constructor to:

new HttpClient(new ModernHttpClient.NativeMessageHandler())

Anyways, i hope you find a solution, maybe i am using an older version, but I don't have any Update available for that package on nuget.

**Comment by rmarinho** [comment]
I think this might be a bug related with Mono HttpClient implementation ? 
Can you try something like this:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.iOS.UITests/Xamarin.Forms.Core.iOS.UITests.csproj#L103

``` 
  <Target Name="AfterBuild">  
     <Delete Files="bin/$(Configuration)/System.Net.Http.dll" /> 
  </Target> 
```

**Comment by PureWeen** [comment]
Closed for inactivity. If you're able to test what rmarinho mentioned we can reopen

**Comment by jonathanantoine** [comment]
Hello,

I manage to reproduce it, the sample is here : [ReproTaskPoolNotWorking.zip](https://github.com/xamarin/Xamarin.Forms/files/2714681/ReproTaskPoolNotWorking.zip).

Steps to reproduce the issue :
1. Launch the app.
2. Wait for this log to be displayed 'Batch X created'.
3. Wait 1 second.
4. Put the app in background ( press the home button for example).
5. Wait 10 seconds and put the app in foreground.
6. Notice that no more thread / requests are made.

(I sometimes have to do it several times for the bug to happen).

The code is pretty simple :
` public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.

            ThreadPool.SetMinThreads(70, 70);
            ThreadPool.SetMaxThreads(70, 70);

            Task.Run(() => StartTheLoopAsync().ConfigureAwait(false));
        }

        private const int howMuchLoop = 60;
        private long _taskCounter = 1;
        private async Task StartTheLoopAsync()
        {
            while (true)
            {
                Debug.WriteLine($"[{_taskCounter:D4}]Will be starting batch {_taskCounter}");

                var toWait = new List<Task<HttpResponseMessage>>(howMuchLoop);
                for (int i = 0; i < howMuchLoop; i++)
                {
                    toWait.Add(Task.Factory.StartNew(
                    () => { return new HttpResponseMessage() { StatusCode = HttpStatusCode.OK }; }
                    , CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default));

                    var httpClient = new HttpClient
                    {
                        Timeout = TimeSpan.FromSeconds(10)
                    };
                    toWait.Add(httpClient.GetAsync(
            "https://url.com?q=dede" + Guid.NewGuid().ToString("N").Substring(0, 5)));

                }

                Debug.WriteLine($"[{_taskCounter:D4}] Batch {_taskCounter} created");

                try
                {
                    await Task.WhenAll(toWait);
                }
                catch (Exception)
                {
                    // ignore
                }
                var howMuchErrors = toWait.Count(t =>
                {
                    try
                    {
                        return t.Exception != null || !t.Result.IsSuccessStatusCode;
                    }
                    catch (Exception)
                    {
                        return true;
                    }
                }) ;

                toWait.Clear();
                Debug.WriteLine($"[{_taskCounter:D4}]batch {_taskCounter} has now been executed : {howMuchErrors} errors.");

                _taskCounter++;
                await Task.Delay(1000).ConfigureAwait(false);
            }
        }`

Example of error log : [logs.zip](https://github.com/xamarin/Xamarin.Forms/files/2714686/logs.zip)

**Comment by Charuwaka** [comment]
@pauldipietro can you please reopen this issue, yes this issue exist Still Exist in Xamarin Forms iOS,But in Android its perfectly Working.

let say i am downloading an image 

`//Network  Available 
var image= await DownloadImage();



private Task <byte[]> DownloadImage()
{ 
//Network Not Available  // here it hangs for a time range between 3-5 minutes and returns result
 using(var responseMessage = await Client.GetAsync("url").ConfigureAwait(false)) {

 }
}`

**Comment by ianvink** [comment]
I've had similar issues sometimes. I found that by removing the ConfigureAwait in my models where data binding happens gets rid of the problem. Not sure why.

**Comment by Gitta9000** [comment]
I used {call}.Result instead of await {call} and that worked for me.

**Comment by Henry-IDD** [comment]
I've had similar issues sometimes.

XF Version: 4.8.0.1821
【symptom】

await httpClient.PostAsync(Uri, httpConent);

=>

Sometimes it takes a long time(10~20 seconds) to send the api.

This problem is only encountered on physical iOS devices (iphone and ipad) after iOS 15 version.

It doesn't happen with the iOS 15 version of the emulator, neither does the Android device.
