### ISSUE TITLE
Xamarin.Forms Button

### ISSUE THREAD

**Issue by SokHeangKhun** [xamarin/Xamarin.Forms#3256]
I have an issue of Xamarin.Forms button on Android. I have ask the quest on stackoverflow. Here is the link https://stackoverflow.com/questions/50824759/xamarin-forms-button-background

**Comment by GalaxiaGuy** [comment]
This could be a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3220

**Comment by SokHeangKhun** [comment]
How could I solve this?

**Comment by pauldipietro** [comment]
Duplicate of the aforementioned issue; please use the other issue for further discussion
