### ISSUE TITLE
Ctrl+A does not select all in WPF password Entry

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3258]
In Xamarin.Forms for WPF, in an ordinary Entry, pressing Ctrl+A selects all text in the Entry. This proper, standard behavior in Windows.

However, if IsPassword="True", Ctrl+A does not select all text. It should.

**Comment by breyed** [comment]
It turns out Ctrl+A is the tip of the iceberg. None of the navigation keys work either. This would be OK if all text were selected when the Entry received focus, but it doesn't. Currently, the only way to change a password is to backspace through every character.

**Comment by pauldipietro** [comment]
Described behavior validated against 3.1.
