### ISSUE TITLE
Page.DisplayActionSheet truncates and ignores casing in WPF

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3259]
In WPF, `Page.DisplayActionSheet` displays the sheet title in all caps without wrapping. This is contrary to iOS, which uses mixed case and wraps, and thus allows for reasonably lengthy and descriptive titles. iOS uses such descriptive titles in much of its UI.

Please update to preserve case, wrap text, remove bolding, and use a smaller font size. In general, render the `title` parameter as dialog box body text (which despite the parameter name is what it really is - there is no actual dialog box title).

Xamarin.Forms 3.1.0.583944

**Comment by pauldipietro** [comment]
Described behavior occurs using 3.1
