### ISSUE TITLE
XamlC NRE using derived view from Layout<T>

### ISSUE THREAD

**Issue by nikolayDemirev** [xamarin/Xamarin.Forms#3260]
### Description
Adding children into a custom layout delivered from Layout<T> causes Object reference not set to an instance of an object while building when XamlCompilation is enabled

### Steps to Reproduce

1. Build the attached project

### Expected Behavior
The project can be compiled

### Actual Behavior
Error while building the project "Object reference not set to an instance of an object"

### Basic Information

- Version with issue: 2.5.... to latest
- Last known good version: No
- IDE: VisualStudio for PC Version 15.6.6
- Platform Target Frameworks: .NET Standard 2.0
  - iOS:  11.4
  - Android: 8.1
  - UWP:  16299
- Nuget Packages: Default from the Xamarin.Forms project template

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/2180142/App1.zip)

**Comment by pauldipietro** [comment]
Deferring to @StephaneDelcroix

**Comment by nikolayDemirev** [comment]
@PureWeen I wanted to use the MyGLayout class as a custom Layout where I define how it will layout its children, not a ContentView. I want to set its Children collection, which is set as a content property by the base class Layout<T>.

For example, if I want to implement a WrapLayout, I will pass children, not single ContentView.

**Comment by PureWeen** [comment]
Right so instead of ContentView just set that attribute to *[ContentProperty("Children")]*

```C#
	[ContentProperty("Children")]
	public abstract class MyGLayout<T> : Layout<T> where T : View
	{
		public MyGLayout()
		{			
			Children = new List<View>();
		}

		protected override void LayoutChildren(double x, double y, double width, double height)
		{
		}

		public new List<View> Children { get; set; }
	}
```
