### ISSUE TITLE
[WPF] When you tap the selected item in a ListView, ItemTapped is not raised

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#3265]
### Description

A ListView has two events: ItemSelected and ItemTapped. ItemSelected is only raised, when the selection changed, but ItemTapped should be raised every time when I tap an item. Also if it is already selected.

### Steps to Reproduce

Tap the same item in a ListView twice

### Expected Behavior

ItemTapped is raised

### Actual Behavior

ItemTapped is only raised, if the item was not selected before. It thus behaves the same as ItemSelected.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: none
- IDE: VS 2017 15.8, preview 3
- Platform Target Frameworks:
  - WPF, .NET Framework 4.6.1

### Reproduction Link

[Repro.WPFListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2180651/Repro.WPFListView.zip)
The repro project shows which events have been raised with which items on the right side of the window. I left UWP in so that the results can easily be compared.

**Comment by pauldipietro** [comment]
The difference in behavior does occur. Thanks for the repro.
