### ISSUE TITLE
[WPF] When scroll a ListView with a touchscreen, the highlighting behaves strange

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#3266]
### Description

When you use a touchscreen to scroll a ListView, the touched cell becomes highlighted (not like the selected cell) and when you then move your finger up/down, the highlighting does not stay at your finger tip, but the cell where the original touch was is highlighted.

### Steps to Reproduce

1. Display a ListView
2. Touch any cell
3. drag your finger up or down to scroll the ListView

### Expected Behavior

Either the highlighting should stay with the finger, or there should be no highlighting at all (like UWP).

### Actual Behavior

The cell at the original touch position stays highlighted.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: none
- IDE: VS 2017 15.8, preview 3
- Platform Target Frameworks:
  - WPF:  .NET Framework 4.6.1, Windows 10

### Screenshots

As the touch position cannot be seen on the screenshot, this doesn't make sense.

### Reproduction Link

[Repro.WPFListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2180707/Repro.WPFListView.zip)
I left UWP in so that the results can easily be compared. The UWP project doesn't highlight anything when scrolling the ListView.

**Comment by pauldipietro** [comment]
Thanks for the repro; described behavior does occur.

**Comment by pauldipietro** [comment]
Behavior was reproducible on a Surface Book 2 screen.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by MichaelRumpler** [comment]
I updated the attached repro project from XF 3.1 to 4.8.0.1534 and 5.0.0.1539-pre2.

The highlighting of the touched cell is still the same.

`ItemTapped` is now different, but still wrong. In the old version, `ItemTapped` was not raised at all when you tapped the selected item. Now it raises `ItemTapped` three times. When you tap a cell which is not selected, then it raises `ItemTapped` twice with the previously selected cell, then `ItemSelected` once with the correct cell and again `ItemTapped` once - this time also with the correct cell.
When you scroll the list, `ItemTapped` is also raised twice with the selected cell (not the touched one). In this case, it should not raise `ItemTapped` at all.

**Comment by MichaelRumpler** [comment]
Here is the updated solution. This is with XF 5.0.0.1539-pre2.

[Repro.WPFListView.zip](https://github.com/xamarin/Xamarin.Forms/files/5363813/Repro.WPFListView.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
