### ISSUE TITLE
[WPF] the order of transformations is not correct

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#3271]
### Description

If you apply more than one of Rotation, Scale and TranslationX/Y to any element, then the order of these transformations is not correct on WPF.

But that order is of crucial importance. If you rotate the element first and then change TranslationX, then the element is moved on the X axis. But if you first apply TranslationX and then rotate it by 90 degrees, the translation is actually along the Y axis.
The same problem occurs with Scale. If TranslationX is set to 100 first and then the Scale is set to 2, then the element will actually be moved by 200 which is wrong.
Scale and Rotation should be applied first and then TranslationX/Y.

### Steps to Reproduce

1. set Rotation="90" to any element
2. change TranslationX on that same element

### Expected Behavior

The rotated element should move along the X axis.

### Actual Behavior

It moves along the Y axis.

### Basic Information

- Version with issue: 3.1.0.583944
- IDE: VS2017 15.8, preview 3
- Platform Target Frameworks:
  - WPF, .NET Framework 4.6.1, Windows 10

### Reproduction Link

[Repro.WPFTransformations.zip](https://github.com/xamarin/Xamarin.Forms/files/2181253/Repro.WPFTransformations.zip)
The repro project is essentially a copy of the sample on https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#the-binding-mode. I just changed RotationX/Y to TranslationX/Y.
I don't know why Scale doesn't work on UWP in this sample, but that's another problem. The text is scaled on WPF, only that it is applied in the wrong order. This is easily visible, when you change Scale to values less than one.

**Comment by pauldipietro** [comment]
Thanks for the repro, can see the difference in behavior
