### ISSUE TITLE
UWP Regression: Drag and drop reordering not firing CollectionChanged

### ISSUE THREAD

**Issue by 1Cor125** [xamarin/Xamarin.Forms#3273]
### Description
Reordering UWP list view using drag and drop, CollectionChanged events are not fired. This appears to have regressed between 3.0.0.482510 and 3.0.0.530893. In 482510 it was firing both a Remove and an Add event. In 530893 it stopped firing any events on a drag and drop reorder. The latest 3.1 version does not fix the issue.

### Steps to Reproduce
1. Run the attached app using a UWP ListView renderer with drag and drop reordering enabled on build 482510. Note that Add and Remove events fire on a reorder.
2. Run the attached app on build 530893. Note that **_no_** events fire on a reorder.

### Expected Behavior
Add and Remove events should be dispatched on a drag and drop reorder.

### Actual Behavior
No events are dispatched.

### Basic Information
- Version with issue: >= 3.0.0.530893
- Last known good version: 3.0.0.482510
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  10.0.16299.309
- Nuget Packages: Xamarin.Forms
- Affected Devices: UWP devices

### Reproduction Link
[ReorderNotCallingCollectionChanged.zip](https://github.com/xamarin/Xamarin.Forms/files/2181722/ReorderNotCallingCollectionChanged.zip)

**Comment by pauldipietro** [comment]
Confirming that the behavior does appear to occur/not occur as described.
