### ISSUE TITLE
[iOS] For ListView in Recycle mode ScrollTo causes cell leak and in some cases NRE

### ISSUE THREAD

**Issue by VitalyKnyazev** [xamarin/Xamarin.Forms#3275]
### Description
When ListView uses Recycle mode and cells have MenuItem and a framework like Prism.Forms is used then ListView.ScrollTo causes NRE.

Root cause - ListView.ScrollTo leaks cells in Recycle mode. Leaked cells with MenuItem still listen to OnMenuItemPropertyChanged and after navigating away from the page Prism.Forms sets BindingContext to null which causes NRE in ContextActionsCell.SetupSelection as GestureRecognizers is already null.

**Another way to get leaked cells is to scroll the list a bit then rotate device and scroll again, go back - crash.**

### Steps to Reproduce

Run App2.iOS project from this solution (can be tricky to build, but possible):
https://github.com/VitalyKnyazev/Leaking-ListView

1. Navigate to Transaction page
2. Click 'Scroll to'
3. Navigate back

### Expected Behavior
No cells are leaked, like when for example UITableView.ScrollRectToVisible is used to implement ListView.ScrollTo instead of UITableView.ScrollToRow.

### Actual Behavior
Recycled cells are leaked when UITableView.ScrollToRow is used, looks like a bug in iOS.

### Basic Information

- Version with issue: 3.1.0.583944
- Last known good version: N/A
- IDE: Visual Studio 2017 15.7.5
- Platform Target Frameworks: 
  - iOS:  11.4.1

- Nuget Packages: Xamarin.Forms 3.1.0.583944
- Affected Devices: iPhone/iPad

### Screenshots

N/A

### Reproduction Link

https://github.com/VitalyKnyazev/Leaking-ListView

**Comment by pauldipietro** [comment]
Please provide an update when you have a repro. Thanks!

**Comment by VitalyKnyazev** [comment]
Added demo project link

**Comment by VitalyKnyazev** [comment]
PureWeen, go to "Transactions (leaks, but no crash)" screen, click "Scroll To" then go back, check main screen messages like "Leaked MenuItem.PropertyChanged subscription count: 86" and "Leaked MenuItem count: 86". I modified Xamarin code a bit to insert those counters.
