### ISSUE TITLE
[macOS] Grid Row Height zero does not hide contents

### ISSUE THREAD

**Issue by jvansickle** [xamarin/Xamarin.Forms#3277]
### Description

When using a grid with multiple rows, if a middle row's height is set to 0 (zero) then the content of the row is still displayed.

### Steps to Reproduce

1. Add a Grid with three rows and a way to toggle the height of the middle row
2. Set middle row height to zero

### Expected Behavior

The content of middle row should not be visible and the grid should adjust for the zero-height row.

### Actual Behavior

The grid adjusts, but the content of the middle row is still displayed and overlaps with other row's content.

### Basic Information

- Version with issue: master
- Last known good version: none
- IDE: VS for Mac 7.5.3 build 7
- Platform Target Frameworks: 
  - macOS: 
- Affected Devices: Mac computers

### Screenshots

![screen shot 2018-07-11 at 10 23 03 am](https://user-images.githubusercontent.com/7631608/42578411-6acf1aca-84f4-11e8-993a-1a1e1dbb1655.png)
![screen shot 2018-07-11 at 10 22 56 am](https://user-images.githubusercontent.com/7631608/42578413-6ae70fea-84f4-11e8-9d93-9bfa763a8616.png)
![simulator screen shot - iphone 8 - 2018-07-11 at 10 21 57](https://user-images.githubusercontent.com/7631608/42578414-6b1d6342-84f4-11e8-9023-8554ebd68e97.png)
![simulator screen shot - iphone 8 - 2018-07-11 at 10 21 56](https://user-images.githubusercontent.com/7631608/42578415-6b3059a2-84f4-11e8-8478-39fc7520de89.png)

### Reproduction Link

https://github.com/jvansickle/XamFormsGridRowBugRepro

**Comment by jvansickle** [comment]
I will be working on a fix for this

**Comment by jvansickle** [comment]
@pauldipietro I haven't been able to fix this as quickly as I had hoped. I'm not familiar enough with the renderers / elements that allow the Grid to work without an explicit renderer. Would someone on the Xamarin team want to look into this, or should I look into making a macOS specific renderer for Grid using the newer NSGridView?

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
