### ISSUE TITLE
Add like x:DataType property in WPF into DataTemplate to type and template connection

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#3278]
Hi, I think that you need to add the x:DataType property in DataTemaplte. this works well in WPF and it's strange that it's still not in XF

**Comment by GalaxiaGuy** [comment]
`x:DataType` has been supported since at least October 2017:
https://blog.xamarin.com/databinding-power-moves-you-may-not-be-using-yet/

Here are a couple of discussions relating to it:
https://github.com/xamarin/Xamarin.Forms/issues/3032
https://github.com/xamarin/Xamarin.Forms/issues/3030

**Comment by KSemenenko** [comment]
@GalaxiaGuy I meant the functional as in WPF, when I specify the data type for which this DataTemplate was created. Now I'm having trouble creating DataTemaplte and calling ctor DataTemaplte(Type type) to support caching in ListView.
