### ISSUE TITLE
No XAML TypeConverter for Size, results in IL error

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3280]
### Description
Using the new `ShadowOffset` with platform specific results in an IL error.

<img width="851" alt="screenshot 2018-07-11 14 41 59" src="https://user-images.githubusercontent.com/41873/42597558-c018b17e-851e-11e8-9eb1-1a5689aceb69.png">

### Steps to Reproduce

1. Code https://github.com/davidortinau/TheLittleThingsPlayground/blob/master/TheLittleThingsPlayground/Views/ThreeOnePage.xaml#L13
2. Add `ShadowOffset` like this:
```
<BoxView WidthRequest="100" HeightRequest="100"
                      x:Name="ShadowBox"
                    BackgroundColor="Black"
                    ios:VisualElement.ShadowColor="Red"
                    ios:VisualElement.ShadowOpacity="1"
                    ios:VisualElement.ShadowRadius="10"
                    ios:VisualElement.ShadowOffset="4,10"
                    ios:VisualElement.IsShadowEnabled="true"
                    />
```

3. Run and observe the IL error

### Expected Behavior
The size should work just like in C#:

```
ShadowBox.On<iOS>().SetShadowOffset(new Size(0, 20));
```

### Basic Information

- Version with issue: 3.1.0

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/

**Comment by StephaneDelcroix** [comment]
`Size` doesn't have a `TypeConverter`
