### ISSUE TITLE
[Android] TabbedPage Add `BarSelectedTextColor`

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3281]
Currently there is no way to set  the BarSelectedTextColor which means if you are only using Text for Tabs there's no way to set the color so that Selected and Unselected look different

The default template for tabs doesn't have images set for Android icons so if the user tries to color the text then there's no way for them to color the text differently for unselected

**Comment by ahoefling** [comment]
I have something that I implemented as a CustomRenderer that supports this and a little bit more. I added 3 properties to the TabbedPage

* SelectedIconColor
* IconColor (or UnselectedIconColor)
* SelectedTextColor

Current Platforms Implemented:

* Android
* iOS

This gives the developer power to set both the text color and icon color for the unselected/selected state. 

@davidortinau I'm starting to work up a Pull Request I would like to submit. Should I include everything I mentioned that covers both text and icon coloring or just focus on the part about Text Coloring for selected/unselected

**Comment by jfversluis** [comment]
If I'm not mistaken, this one is also fixed by #4899 and should be possible today on Android with the functionality mentioned in #3478. Unless I don't fully understand what is meant here.

**Comment by ahoefling** [comment]
I think your PR fixes this issue. I was starting to push for changes that allow you to update the icon color as well.  Which maybe we should create a new GitHub Issue to track icon color if it isn't supported and close this one out.

Does your code change handle icon color or does it just work for text color?

**Comment by jfversluis** [comment]
Actually, the Android implementation has not changed. So you should be able to test that with the platform specific that is in place for Android today. If I'm not mistaken the image should work as well, but I'm not a 100% sure.

**Comment by ahoefling** [comment]
I completely forgot about this one. Thanks @samhouts for taking it as up-for-grabs as I am working on a PR for iOS/Android that I'll submit later this weekend. I have all the code from a previous project and blog I wrote so it is just a matter of integrating it with the platform project. 

I'm taking the code from my [Tab Page Renderer Blog](https://www.andrewhoefling.com/Blog/Post/xamarin-forms-a-better-tabbed-page-renderer)

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
