### ISSUE TITLE
VisualElementPackager.RemoveChild (Xamarin.Forms.VisualElement view)

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Xamarin.Forms#3284]
### Description

Something with ContentPage.Content set logic (not reproduced; prediction) on Android, possible cases: 
- multi BaseContentPage.PreloaderPage() call (multi ContentPage.Content value sets) in single ContentPage
- multi BaseContentPage.PreloaderPage() call (multi ContentPage.Content value sets) in TabbedPage (once or more in TabbedPage child page)
 
<pre>
BaseContentPage.PreloaderPage (Common.Models.ColorPaletteColor palette, System.String text)
System.NullReferenceException: Object reference not set to an instance of an object

Trace:
VisualElementPackager.RemoveChild (Xamarin.Forms.VisualElement view)
VisualElementPackager.OnChildRemoved (System.Object sender, Xamarin.Forms.ElementEventArgs e)
(wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.ElementEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.ElementEventArgs)
Element.OnChildRemoved (Xamarin.Forms.Element child)
VisualElement.OnChildRemoved (Xamarin.Forms.Element child)
Page.OnInternalRemoved (Xamarin.Forms.VisualElement view)
Page.InternalChildrenOnCollectionChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedAction action, System.Object item, System.Int32 index)
ObservableCollection`1[T].RemoveItem (System.Int32 index)
Collection`1[T].RemoveAt (System.Int32 index)
TemplateUtilities.OnContentChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess)
BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value)
ContentPage.set_Content (Xamarin.Forms.View value)
BaseContentPage.PreloaderPage (Common.Models.ColorPaletteColor palette, System.String text)
BaseContentPage+<BadResponseRetry>d__50.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
GenericJsonContentPage`1+<Sync>d__18[T].MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
GenericJsonContentPage`1+<SyncOnAppearing>d__5[T].MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
GenericJsonContentPage`1+<<OnAppearing>b__3_0>d[T].MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.3a1edd24-ca4b-4f27-87d8-e319966eea1b(intptr,intptr)
</pre>

### Steps to Reproduce

**BaseContentPage.cs**
<pre>
protected void PreloaderPage(ColorPaletteColor palette = null, string text = null)
{
    ...

    Content = new PreloaderLayoutView(color, text);
}
</pre>

where **PreloaderLayoutView** (simple StackLayout with Children.Add(label)): 

<pre>internal class PreloaderLayoutView : StackLayout { ... }</pre>

### Basic Information

- XF: 3.0.0.530893
- OS: Android (from log: 6.0.1, 7.0, 7.1.1, 8.0)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
