### ISSUE TITLE
Incorrect left padding in Android

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3287]
Moving an issue from the xamarin-forms-samples repo (https://github.com/xamarin/xamarin-forms-samples/issues/339) to this repo from @LaloCo

If I set Layout Compression to a StackLayout that is defined inside a ScrollView, the result on Android has some extra left padding. On iOS it looks fine, the exact same way as without Layout Compression.

My code looks something like this:

    <ContentPage.Content CompressedLayout.IsHeadless="True">
        <ScrollView>
            <StackLayout VerticalOptions="Center"
                         CompressedLayout.IsHeadless="True"
                         Margin="20">
                <Image x:Name="iconImage"
                       Aspect="AspectFit"
                       HorizontalOptions="FillAndExpand"
                       Margin="0, 0, 0, 50"
                       HeightRequest="150"/>
                <Entry x:Name="EmailEntry" 
                       Placeholder="Email address"
                       Keyboard="Email"            />
                <Entry x:Name="PasswordEntry"
                       Placeholder="Password"
                       IsPassword="True"/>
                <Button x:Name="LoginButton" 
                        Margin="0,50,0,0"
                        Text="Log in"/>
                <Button x:Name="RegisterUserButton" 
                        Margin="0,50,0,0"
                        Text="Register"
                        HorizontalOptions="End"            />
            </StackLayout>
        </ScrollView>
    </ContentPage.Content>

**Comment by TingtingAn** [comment]
Any luck for Android Padding?  Any idea to set left padding to 0 in Android.
I wrote this `<Button Text="{Binding Text}" Padding="0"></Button>`, it did not work for Android.

**Comment by samhouts** [comment]
This issue doesn't seem to have had any activity in a long time. We're working on prioritizing issues and resolving them as quickly as we can. To help us get through the list, we would appreciate an update from you to let us know if this is still affecting you on the latest version of Xamarin.Forms, since it's possible that we may have resolved this as part of another related or duplicate issue. If we don't see any new activity on this issue in the next 30 days, we'll evaluate whether this issue should be closed. Thank you!

**Comment by Redth** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
