### ISSUE TITLE
Platform Specific -> Android Bottom Tabs Set Shift Mode

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#3289]
Currently we can set bottom tabs on Android with the new stuff in Xamarin.Forms 3.1, but if you add more then 3 items then it will auto start shifting :(

The code to adjust this can be found: https://github.com/jamesmontemagno/Xamarin-Templates/blob/master/Xamarin.Android-Templates/Projects/BottomTabsApp/BlankAppCompat/BottomNavigationViewUtils.cs

This would be a nice addition please!

**Comment by PureWeen** [comment]
Duplicate
https://github.com/xamarin/Xamarin.Forms/issues/3083
