### ISSUE TITLE
Xamarin.Forms [iOS] is much slower than [Android] in rendering lots of views

### ISSUE THREAD

**Issue by ljezny** [xamarin/Xamarin.Forms#3292]
### Description

Creating lots of views (i.e. 1000+) takes 100x longer on iOS than Android.

```

StackLayout stackLayout = new StackLayout() { Orientation = StackOrientation.Vertical };
            for (int i = 0; i < 1000; i++) {
                stackLayout.Children.Add(new Label() { Text = i.ToString() });
            }
            return stackLayout;

```

### Steps to Reproduce

1.  Try to show ContentPage with StackLayout with 1000+ Labels
2. Run on iOS, it take more than a minute
3. Run on Android, it takes second

### Expected Behavior

1000+ more labels should be rendered on iOS in seconds.

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: None
- IDE: VS for Mac 7.5.3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: tested on iPhoneX simulator and Android Emulator (7.0.0)

**Comment by jfversluis** [comment]
(Android) performance is a big focus area for .NET MAUI. While we do our best to also have performance increasements here, and I think we had some over the years, I will close this one for now. If there is still a specific scenario where you have issues, please let us know!
