### ISSUE TITLE
ActivityIndicator change color to black on Xamarin.MAC after the second display.

### ISSUE THREAD

**Issue by eduardoanies** [xamarin/Xamarin.Forms#3301]
### Description

Try to run this code on a Xamarin.Mac project.

```
ActivityIndicator activityIndicator = new ActivityIndicator
            {
                Color = Color.LightGreen,
                IsVisible = true,
                IsRunning = true,
                VerticalOptions = LayoutOptions.CenterAndExpand,
            };
```
It will show the  ActivityIndicator with color LightGreen the first time, the second time it will show the color black, (This happens only on MacOs, on Android, iOs, UWP works as expected).
### Steps to Reproduce

1. Display an ActivityIndicator on Mac with some color different to black, like green or blue.
2. Dimiss the ActivityIndicator
3. Show the ActivityIndicator again

### Expected Behavior

The ActivityIndicator color should be the indicated in the code like green or blue

### Actual Behavior

The ActivityIndicator color is black

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: --
- IDE: Visual Studio Community for MAC version 7.5.3 (build 7)
- Platform Target Frameworks: 
  - MacOs
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms 3.1.0.637273
- Affected Devices:
macOS High Sierra
Version 10.13.4
### Screenshots
https://stackoverflow.com/questions/51334903/how-to-change-the-color-of-activityindicator-in-xamarin-forms-macos

### Reproduction Link

**Comment by AndreiMisiukevich** [comment]
I will clarify "Dismiss" in current context means "remove from parent", because setting IsVisible = false/true doesn't cause this bug :) IsRunning also has no effect. Remove and add again only
