### ISSUE TITLE
Ambiguous exception occurs while accessing the derived class property 

### ISSUE THREAD

**Issue by suriyakalidoss** [xamarin/Xamarin.Forms#3302]
### Description
    Unable to access the derived class new instance property(MyProperty1) while using the same property name in both base class and derived class.Please refer the below code snippet
  public class BaseClass
    {
        List<string> myMessage = new List<string>();
        public List<**string**> **MyProperty1**
        {
            get
            {
                return myMessage;
            }
            set
            {
                myMessage = value;
            }
        }
    }

    public class DerivedClass : BaseClass
    {
        List<double> myMessage = new List<double>();
//Here property is created using same name with newly created instance with list as double but unable to access
        public new List<double> MyProperty1
        {
            get
            {
                return myMessage;
            }
            set
            {
                myMessage = value;
            }
        }
        
    }
 class TestClass
    {
        static void Main()
        {
               

                Type myType = typeof(DerivedClass);
                PropertyInfo myStringProperties1 = myType.GetProperty("MyProperty1");
//Unable to access the derived class property ambiguios exception occurs

          
        }
    }
### Steps to Reproduce

1. Run the attached sample 
2. Access the derived class property
3. Ambiguios exception occurs

### Expected Behavior
Ambiguos exception should not occurs
### Actual Behavior
Ambiguos exception occurs while acessing  derived class same name newly created instance property
### Basic Information
 Issue occurs in simple sample

### Screenshots

![image](https://user-images.githubusercontent.com/31415578/42721271-a41dc2aa-8755-11e8-892e-11a302160a01.png)

### Reproduction Link

[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/2194676/Sample.zip)

**Comment by PureWeen** [comment]
I'm pretty sure you are just running into how reflection works

https://stackoverflow.com/questions/4151794/ambiguous-exception-using-reflection

Let me know if the SO post doesn't resolve your question.
