### ISSUE TITLE
XF Android Button Rendering On Press is Malfunctioning

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/Xamarin.Forms#3303]
### Description

Creating a basic, customized pill button in Xamarin Forms where I supply a fade to color animation on the button's Pressed event results in a strange, mini version of the button appearing in the upper left corner of its layout on Android as well as its fill being darker than intended (see screenshots below). I tried to remedy by supplying a CustomRenderer that sets StateListAnimator to null and it made no difference. Also out of random desperation tried to enable the experimental fast renderers and that too of course did not help.

Please advise on a quick fix, or if this is indeed a bug that I must wait to get addressed. Thank you.

### Steps to Reproduce

My setup aside, here's the min steps to see this issue in action:
1.  Create new Xamarin Forms project targeting Android
2.  Add the following XAML to the main page:
```
    <ContentPage.Resources>
        <ResourceDictionary>
            <Style
                x:Key="PillButtonStyle"
                TargetType="{x:Type Button}">
                <Setter
                    Property="BackgroundColor"
                    Value="Transparent" />
                <Setter
                    Property="TextColor"
                    Value="LimeGreen" />
                <Setter
                    Property="BorderColor"
                    Value="LimeGreen" />
                <Setter
                    Property="BorderWidth"
                    Value="2" />
                <Setter
                    Property="CornerRadius"
                    Value="30" />
            </Style>
        </ResourceDictionary>
    </ContentPage.Resources>
    <StackLayout
        HorizontalOptions="CenterAndExpand"
        VerticalOptions="CenterAndExpand">
        <Button
            x:Name="btn"
            Style="{x:StaticResource PillButtonStyle}"
            Text="Test" />
    </StackLayout>
```
3. Add this to the code-behind:
`btn.Pressed += (sender, e) => { btn.BackgroundColor = Color.LightSeaGreen; };`

4. Run on device/emulator, and press down on the button for a couple of seconds to see that the mini button phenomenon occurs in the upper left of its layout. While still pressing, move your finger (or cursor in emulator :) ) off the button, it will show the proper visual state.

### Expected Behavior

No weird mini button fading in and out on press. And no "mask" distorting the fill color from what was set in the code.

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: n/a
- IDE: VS2017 Enterprise 15.7.5
- Platform Target Frameworks: 
  - Android: 8.1

- Android Support Library Version: v27.0.2.1
- Nuget Packages: Irrelevant
- Affected Devices: All Real and Emulated

### Screenshots

![image](https://user-images.githubusercontent.com/13161978/42721336-ad74a484-876b-11e8-9b72-c152c9de1384.png)

**Comment by pauldipietro** [comment]
#3220

**Comment by mzhukovs** [comment]
Thanks for quick response. I can create a separate issue but I noticed on **iOS** if you do the press and then move your finger (while still pressing) outside the bounds of the button and then release, the Released event never fires. Simple repro: add a button in XAMLAd, add in codebehind to change button background color to orange on Pressed event, add another for Released to change it to blue. If you do the action described above, button will remain orange.   Please let me know if you're already aware of this issue or if I should create separate bug. @pauldipietro
