### ISSUE TITLE
PushModalAsync ignores NavigationPage on UWP

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3305]
On UWP, when a modal page is invoked like this:

``` c#
sourcePage.Navigation.PushModalAsync(new NavigationPage(modalRoot));
```

The resulting page does not use the navigation page. There is no title and the toolbar is not shown.

Xamarin.Forms 3.1.0.637273

**Comment by pauldipietro** [comment]
#3298
