### ISSUE TITLE
Button does not recalculate width on WPF

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3308]
On WPF, after a Button has been displayed, if you change its Text, its width doesn't change. This can cause the new text to be clipped.

Xamarin.Forms 3.1.0.637273

**Comment by mohachouch** [comment]
Hi, thanks for the feedback. You can add an reproduction project. Thanks.

**Comment by breyed** [comment]
I don't have an isolated repro. I observed the behavior in a production project. iOS worked file. Android was flakey (first shows the text with the old width, including momentarily wrapping it if the new text was longer and had a space). UWP never changed at all.

I stand-alone repro should be easy to make, but better would be to ensure that the XF unit tests contain covered for changing a Button's text and then checking to ensure that Width gets updated correctly.

**Comment by mohachouch** [comment]
@PureWeen @samhouts @rmarinho  This issue is fixed by #3750
