### ISSUE TITLE
[WPF] NotImplementedException When executing Clear and Remove methods on ObservableCollection 

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#3309]
When executing Clear and Remove methods on ObservableCollection the exception is thrown: 'System.NotImplementedException' in Xamarin.Forms.Core.dll.
But if I cover it with try catch the result of the operation is correct.

Tested on
Xamarin latest 3.1 version
Platform WPF

**Comment by mohachouch** [comment]
Hi, thanks for the feedback. You can add an reproduction project. Thanks.

**Comment by VladislavAntonyuk** [comment]
![image](https://user-images.githubusercontent.com/33021114/42876722-3e2d0eae-8a90-11e8-9fab-92f610fbb10e.png)
![image](https://user-images.githubusercontent.com/33021114/42876769-65e2e6bc-8a90-11e8-85b4-b76abdadb75d.png)

**Comment by jsuarezruiz** [comment]
PR sent!
