### ISSUE TITLE
XF - Android - TabbedPage Toolbar only shows the active ToolbarItem when ToolbarPlacement is bottom and ContentPage count bigger than 4

### ISSUE THREAD

**Issue by allenliu1030** [xamarin/Xamarin.Forms#3312]
### Description
There is a new feature in Xamarin.Forms 3.1 version which we already support for Android toolbar to be placed in the bottom. But currently after testing I found there is a bug, when the content page within the Tabbed Page is bigger than 4, then the Toolbar will now show all the tabs there, only the current active tab will be showed.

### Steps to Reproduce

1. Create a XF project and make sure the XF version is over 3.1. (My testing is 3.1.0.637273)
2. Write the code as below in the MainPage.xaml file:

  ``` XML

<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:AllenTestTabbedPageButtom"
             xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
             android:TabbedPage.ToolbarPlacement="Bottom"
             x:Class="AllenTestTabbedPageButtom.MainPage">

    <local:ContentPage1 Title="1">
        
    </local:ContentPage1>

    <local:ContentPage2 Title="2">
        
    </local:ContentPage2>
    
    <ContentPage Title="3">
        
    </ContentPage>

    <ContentPage Title="4">
        
    </ContentPage>

    <ContentPage Title="5">

    </ContentPage>

</TabbedPage>

  ```

3. Run the application

### Expected Behavior
There should be five tabs in the toolbar which name 1,2,3,4,5.

### Actual Behavior
Only the active tab will be shown and the other ones can be only switched and then the tab will be selected accordingly.

### Basic Information

- Version with issue: XF 3.1.0.637273
- Last known good version: NA
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: Android 8.1
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices:

### Screenshots
When we at the first page which title is 1:

![image](https://user-images.githubusercontent.com/36911474/42751278-d50c1a38-891c-11e8-978d-40b8c5518e11.png)

Then we switch to Tab 2:

![image](https://user-images.githubusercontent.com/36911474/42751318-f7da2c8a-891c-11e8-9133-45d4f2b31110.png)

**Comment by PureWeen** [comment]
@allenliu1030  This is how the BottomNavigationBar works in Android.  Once it goes above 3 items it goes into shift mode which only displays the icons and not the text.

We're going to implement this
https://github.com/xamarin/Xamarin.Forms/issues/3083

Soon at which point you can turn off that shifting and then you should be able to see the text when you have 4 or 5 items
