### ISSUE TITLE
Setting Span.Style to a Device Style from C# throws an exception

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3314]
### Description

In XAML, setting the `Span.Style` property to one of the `Device` styles works fine. However, it fails in C#.

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

`Device.Styles.TitleStyle` is applied to the `Span`.

### Actual Behavior

Crashes on both iOS and Android. On iOS a `NullReferenceException` will be thrown. On Android a `MissingMethodException` is thrown (Xamarin.Forms.Span.set_style).

Removing the `Style` property setter from the `Span` causes the app to run.

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0.637273
- IDE: VSMac
- Platform Target Frameworks:
  - iOS: 11.4
  - Android: API 27
  - UWP:  Not tried.

### Reproduction Link

[SpanTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2198131/SpanTest.zip)

**Comment by PureWeen** [comment]
Exception appears to happen because Span is not a VisualElement

Seems like the property Style needs to be extracted out to an interface so the style can be retrieved from either

![image](https://user-images.githubusercontent.com/5375137/42787717-fd1c3782-8918-11e8-90c3-a66ebb26fbde.png)

**Comment by StephaneDelcroix** [comment]
@PureWeen how is this a regression ?

**Comment by PureWeen** [comment]
@StephaneDelcroix 
It was more that it was a broken aspect of a new feature and I just wanted to make sure it got prioritized higher but probably wasn't a necessary attribute
