### ISSUE TITLE
[MAC] ScrollTo method is not working in Xamarin.Forms for mac platform

### ISSUE THREAD

**Issue by bhaveshsoft1** [xamarin/Xamarin.Forms#3319]
### Description
We are developing chat application using Xamarin.Forms (2.5.0.91635) (Even I checked in latest version of Xamarin.Forms 3.1.0.637273 but it not works). We are trying to implement very basic functionality to scroll on bottom when user open any chat window or send/receive messages. It working fine in iOS and Android but it not works in mac platform. Can you please suggest how to implement ScrollTo in mac.

When to expect this feature means after how much time?

### Steps to Reproduce

ScrollTo method is not working in simple listivew in mac platform.

### Expected Behavior

It should be scroll to last message when below line of code execute.

lstMessages.ScrollTo(objlastmessage, ScrollToPosition.Start, false);

### Actual Behavior

It is not scroll to last item of list-view.

### Basic Information

- Version with issue: Xamarin.Forms 2.5.0.91635 (even I checked in 3.1.0.637273 version too)
- Last known good version: Don't know
- IDE: Visual Studio 7.4.2 (build 12)
- Platform Target Frameworks: 
### Screenshots
NA
### Reproduction Link
NA

**Comment by DennisWelu** [comment]
I'm running into this on Mac _and_ WPF.
Similar to https://github.com/xamarin/Xamarin.Forms/issues/1519.
