### ISSUE TITLE
ListView has no SelectedIndex property like Picker control

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#3324]
### Description
There is no way to DE-select by index in a ListView like there is in a Picker, or like other Microsoft technologies such as WPF.
Normally we would de-select in a Picker by setting the SelectedIndex to -1.  The same is done in a [WPF ListView](https://msdn.microsoft.com/en-us/library/system.web.ui.webcontrols.listview.selectedindex(v=vs.110).aspx).

But this property seems to have been overlooked in the Xamarin ListView.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
Duplicate
https://github.com/xamarin/Xamarin.Forms/issues/2811
