### ISSUE TITLE
[UWP] ContentPage appears at wrong size 

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#3326]
### Description

When I open a page, it appears in a slightly oversized way on UWP. The bottom edge (about 30-40 px high) is missing. Upon slight modification of the main window size, probably on the first SizeChanged event, it returns to normal.

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: 3.1.0.583944
- IDE: VS 2018
- Platform Target Frameworks:
  - UWP:  16299

**Comment by PureWeen** [comment]
@deakjahn    Are you seeing this issue on UWP or WPF?  The title says UWP but the description says WPF

Also can you attach a repro so that we're on the same page with what you mean by *when I open a page*?

**Comment by deakjahn** [comment]
Sorry, old habits. UWP all across.

**Comment by deakjahn** [comment]
This will be another manifestation of the navigation page problem mentioned in about three other bugs but not exactly the same symptoms. I'll upload it anyway and you decide whether it's duplicate or not. :-)

**Comment by deakjahn** [comment]
[XamarinDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2202752/XamarinDemo.zip)

A master-details setup, with a navigation page. Toolbar at top. I do see the toolbar upon start (other bugs say it's not visible) but the 50-px high orange frame at the bottom is mostly hidden. On the first resize event, the orange frame jumps into position.

**Comment by PureWeen** [comment]
yea @deakjahn 
I tested your sample with this PR
https://github.com/xamarin/Xamarin.Forms/pull/3298

And it looks like the orange now shows up correctly as it did with 3.1

**Comment by deakjahn** [comment]
Then looking forward to the next release, I guess. Thanks.
