### ISSUE TITLE
[UWP] DatePicker allows a date to be selected which violates the MinimumDate property

### ISSUE THREAD

**Issue by mjewild** [xamarin/Xamarin.Forms#3331]
### Description
UWP DatePicker allows a date to be selected which violates the MinimumDate property.

### Steps to Reproduce
With the current Date set to 3rd July 2018 and MinimumDate set to 2nd July 2018
1. Select 1st July 2018
2. 1st July not allowed and date bounces to the minimum (2nd July).
3. Select 1st July 2018 again
4. 1st July is now incorrectly allowed. The date displayed is the 1st. The actual underlying Date property is the 2nd.

### Expected Behavior
You should always be prevented from selecting a Date lower than the MinimumDate.
This is how it worked in 2.5

### Actual Behavior
You can select a Date lower than the MinimumDate on the 2nd attempt.

### Basic Information

- Version with issue: 3 onwards, Still broken in 3.3.0.669060-nightly
- Last known good version: 2.5.1.527436
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - UWP:  16299 

### Reproduction Link
[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2205482/TestApp.zip)

**Comment by cgollubske** [comment]
This issue has been closed for a while but is still broken in the latest version 4.0.0.425677. Could someone let us know when it's going to be fixed?
