### ISSUE TITLE
[Android] Memory leak in MasterDetailPage

### ISSUE THREAD

**Issue by duzenko** [xamarin/Xamarin.Forms#3332]
### Description
Switching detail pages leaks memory.

### Steps to Reproduce

1. Run the attached project.
2. Click the Test button a few times.
3. Watch memory leaking.

### Expected Behavior
Memory consumption stays constant.

### Actual Behavior
Memory leaks.

### Basic Information

- Version with issue: 3.1+
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: 8.1

### Reproduction Link

[leaks.zip](https://github.com/xamarin/Xamarin.Forms/files/2205550/leaks.zip)

**Comment by PureWeen** [comment]
I also ran this through profiler which confirmed a leak

**Comment by opcodewriter** [comment]
I hope this gets fixed very soon, I noticed same issue, it's a pretty serious problem
