### ISSUE TITLE
DynamicResource didn't load correct in Merging Resource Dictionary

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/Xamarin.Forms#3338]
### Description
DynamicResource didn't load when we using it in merging resource dictionary in some case. 
### Steps to Reproduce

1. Create a separate resource dictionary with some color. Reference this color in some style.
2. Change this color in runtime.
3. Push a page after color changed.

### Expected Behavior
The new page should apply the new color
### Actual Behavior
The new page still keep the old color
### Basic Information
If we put this color into App.xaml, it will work fine, but if we put it into a separate style file. It doesn't work, and it only happens in a new pushed page

- Version with issue: 3.1.0.637273
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.12.04
  - Android: 8.3.3.2
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[Demo](https://www.dropbox.com/s/04bwwbnsqy6h1g3/TestDynamicResource.zip?dl=0)

**Comment by StephaneDelcroix** [comment]
button on the first page does change color, but not through `{DynamicResource}`. You're also not modifying the `PrimaryColor` in the Merged RD, so you end up with 2 resources named `PrimaryColor`. Actually, replacing the `{DynamicResource}` on the second page by `{StaticResource}` shows a Red button.

I'll review the order in which resources are evaluated, but so far it looks consistent

**Comment by jessejiang0214** [comment]
Hi @StephaneDelcroix, It should be only one PrimaryColor in the App which I define in SeparateStyle.xaml. If there're two, definitely it's a bug, cause I only declare one.

**Comment by StephaneDelcroix** [comment]
@jessejiang0214 you actually define 2
- the first one in `SeparateStyle`,
- the you add one in the main RD: 

```csharp
App.Current.Resources["PrimaryColor"] = clicked ? Color.Green : Color.Red;
```

**Comment by jessejiang0214** [comment]
Ok, I think you didn't know what I want to do.
I want to do like change the theme. If I declare PrimaryColor in RD, when I click the button on the first page, it will change the color to green, so next page it should show the green color.

If I declare PrimaryColor in App.xaml, the behavior is what I want, the second page shows the green color.

If I declare it in SeparateStyle, the second page won't change the color, which is wrong.

**Comment by StephaneDelcroix** [comment]
I totally understand what you try to do. setting `App.Current.Resource["PrimaryColor"]` does not changes the resource in SeparateStyle, it creates a duplicate in Application.Resources
