### ISSUE TITLE
WebView.Navigated Event not firing on First run

### ISSUE THREAD

**Issue by WojTherapy** [xamarin/Xamarin.Forms#3341]
### Description
Hi All,

I came across the problem with WebView.Navigated event. It seems that whenever you try to navigate to the page first time when you install app freshly on device (both iOS and Android) Navigated event never gets fired. It could be due to the fact that an actual navigation to the page and page content is being passed after server sends certain data back after initial connection attempt. So:

### Steps to Reproduce

Create WebView, assign URL. Application sends URL to the server. When this is complete and page has been navigated (Navigated event has been fired) Server sends back required verification details. and navigate to new page. However Navigated event never gets fired when you run application first time on the device (fresh install), when you close web view and try again it works fine. It also works fine if application is already on installed on device and u run it again.

Visual Studio Community 2017 for Mac
Version 7.5.1 (build 22)
Installation UUID: 9ffe50b7-ce3c-44e0-8f72-ff7ef3009707
Runtime:
	Mono 5.10.1.47 (2017-12/8eb8f7d5e74) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010047

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

Xamarin.Mac
Version: 4.4.1.178 (Visual Studio Community)

Xamarin.Android
Version: 8.3.0.19 (Visual Studio Community)
Android SDK: /Users/mac/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

Xamarin.iOS
Version: 11.10.1.178 (Visual Studio Community)
Hash: 408d3574
Branch: d15-7
Build date: 2018-05-08 18:56:30-0400

Build Information
Release ID: 705010022
Git revision: 60442dd643a20c7a4ae1f8705b8d1de8972eee78
Build date: 2018-05-15 01:43:39+00
Xamarin addins: 4194ffe4868321e4c3477bd56aed579bda4c6fbb

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

Enabled user installed addins
Redth's Addins 1.0.9
Internet of Things (IoT) development (Preview) 7.5

**Comment by PureWeen** [comment]
@WojTherapy  Can you attach a repro?

I tested using the following code and navigated fired for me every time

[WebViewNavigated.zip](https://github.com/xamarin/Xamarin.Forms/files/2211013/WebViewNavigated.zip)

**Comment by WojTherapy** [comment]
Hi,

I'll create sample app based on our code when I get a minute. I think it could be due to the fact that we actually populate the WebView in AbsoluteLayout after user input (Button press). In your example WebView is a main content initially.

**Comment by WojTherapy** [comment]
Hi guys, found out what the issue was. One of the methods that generates Token required to load website via WebView took too much time and didn't manage to execute before Webview was actually initialised, hence loading empty page. Because of that hence Navigated event never gets fired (page never finish navigating). 

Thx for your help!
