### ISSUE TITLE
[Android] BoxView BackgroundColor not working on 3.2.0-pre1

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3342]
Setting the BackgroundColor directly or view the OnPlatform markup extension, it doesn't render on Android. 

### Basic Information

- Version with issue: 3.2.0.637442-pre1

### Screenshots

<img width="584" alt="screenshot 2018-07-19 14 38 34" src="https://user-images.githubusercontent.com/41873/42966197-05c3e8da-8b62-11e8-9ba1-033ed490f52f.png">

<img width="545" alt="screenshot 2018-07-19 14 38 59" src="https://user-images.githubusercontent.com/41873/42966214-0e0446a2-8b62-11e8-9421-ccf1040c4425.png">

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/3.2.0-pre/TheLittleThingsPlayground/Views/ThreeTwoPage.xaml

**Comment by PureWeen** [comment]
Another simple repro

[BoxViewBackgroundColor.zip](https://github.com/xamarin/Xamarin.Forms/files/2212007/BoxViewBackgroundColor.zip)
