### ISSUE TITLE
[Android, UWP] LineHeight not working on 3.2.0-pre1

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3344]
### Description
I set the LineHeight to 1.5 (or more) and it looks good on iOS, but on Android it appears to have no impact.

### Basic Information

- Version with issue: 3.2.0.637442-pre1

### Screenshots

<img width="545" alt="screenshot 2018-07-19 14 39 22" src="https://user-images.githubusercontent.com/41873/42966446-c9ba7420-8b62-11e8-8dab-c63c613676aa.png">
<img width="562" alt="screenshot 2018-07-19 14 39 16" src="https://user-images.githubusercontent.com/41873/42966447-c9ccf0be-8b62-11e8-8cc1-6dd3ecb4a2ab.png">

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/3.2.0-pre/TheLittleThingsPlayground/Views/ThreeTwoPage.xaml

[LineHeight.zip](https://github.com/xamarin/Xamarin.Forms/files/2212038/LineHeight.zip)

**Comment by kingces95** [comment]
Pull request adding `LineHeight` feature: https://github.com/xamarin/Xamarin.Forms/pull/2132

**Comment by kingces95** [comment]
Unit test https://github.com/xamarin/Xamarin.Forms/blob/5112f0928fc377550a5dd58213b520a0f6cae518/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue1734.cs.

**Comment by kingces95** [comment]
`LineHeight` only has effect if the text wraps. For this issue, none of the labels wrap so `LineHeight` will have no effect. Even when the text wraps the bounding rectangle only encompasses an area sufficient to hold `LineHeight` equal to 1. Changing the `LineHeight` doesn't re-compute the correct rectangle even though the wrapped label is re-drawn. Changing the `FontSize` however _does_ recompute the bounding rectangle for `LineHeight` and the re-drawn label then appears as expected. Both `LineHeight` and `FontSize` appear to use the same logic to trigger re-drawing so I'm gonna need to ask @jassmith to take a peek and show me what I'm missing.

**Comment by kingces95** [comment]
![1743](https://user-images.githubusercontent.com/4120386/43424644-c701655e-93eb-11e8-80b1-90c8b5e00d6c.GIF)

**Comment by kingces95** [comment]
Looked at this with @jassmith. Is odd. Will pick up tomorrow.

**Comment by samhouts** [comment]
Closed by https://github.com/xamarin/Xamarin.Forms/pull/3452
