### ISSUE TITLE
DependencyService is not thread-safe

### ISSUE THREAD

**Issue by lassana** [xamarin/Xamarin.Forms#3348]
### Description

The title speaks for itself. You can find the following line in the [DependencyService.cs](https://github.com/xamarin/Xamarin.Forms/blob/fd733037a4788a9f1049142f6d33a30330ab8108/Xamarin.Forms.Core/DependencyService.cs):

```
DependencyImplementations[targetType] = implementor != null ? new DependencyData { ImplementorType = implementor } : null;
```

The problem with it is that `Dictionary<>.Insert()` throws a `NullReferenceException` internally if the dictionary instance is modified from another thread during the insert operation. You can find more info [here](https://stackoverflow.com/questions/1320621/throw-a-nullreferenceexception-while-calling-the-set-item-method-of-a-dictionary) and in the [.NET documentation](https://msdn.microsoft.com/en-us/library/xfhwa508.aspx):

> A Dictionary<TKey, TValue> can support multiple readers concurrently, as long as the collection is not modified. Even so, enumerating through a collection is intrinsically not a thread-safe procedure. In the rare case where an enumeration contends with write accesses, the collection must be locked during the entire enumeration. **To allow the collection to be accessed by multiple threads for reading and writing, you must implement your own synchronization.**

Personally I see this exception in the Firebase console (pretty rarely, though):

```
Exception android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00111] in <d2bfb6c5445546a4b00eb2d3c2cc918e>:0
at System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) [0x00000] in <d2bfb6c5445546a4b00eb2d3c2cc918e>:0
at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x0003c] in <afec569c85894ae9a18371a2fecd2d37>:0
at MyApplication.Droid.Adapters.Firebase.Messaging.AppFirebaseInstanceIdService.OnTokenRefresh () [0x0004d] in <fc32d2f17bb7468fa3aca8d4fd1ecc8f>:0
at Firebase.Iid.FirebaseInstanceIdService.n_OnTokenRefresh (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <09a4f89addb34f02af055f39e6c540b7>:0
at (wrapper dynamic-method) System.Object.39cf8d1d-9d33-4942-8e61-bdf7f20d6734(intptr,intptr)
md505183ac6112b122fe6ed6669911b68ec.AppFirebaseInstanceIdService.n_onTokenRefresh (AppFirebaseInstanceIdService.java)
md505183ac6112b122fe6ed6669911b68ec.AppFirebaseInstanceIdService.onTokenRefresh (AppFirebaseInstanceIdService.java:29)
com.google.firebase.iid.FirebaseInstanceIdService.zza ()
com.google.firebase.iid.FirebaseInstanceIdService.zzF ()
com.google.firebase.iid.FirebaseInstanceIdService.handleIntent ()
com.google.firebase.iid.zzb$1.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)
```

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: -
- Affected Devices: all

**Comment by PureWeen** [comment]
Definitely isn't thread safe but we'll need to determine if the performance impact of us making that thread safe without letting the user control that is worth it.

At this point if users are seeing threading issues then access to that DependencyService could be coordinated by the user through a factory or similar to apply their own thread safe layer

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
