### ISSUE TITLE
[Android, iOS] Badge implementation for tabs

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/Xamarin.Forms#3352]
BadgeValue: string to set the number of notification-like items.
BadgeColor: background color of each badge
BadgeTextColor: Foreground color of each badge text
SelectedBadgeTextColor: selected foreground color of each badge text

Previous work
https://github.com/xamarin/Xamarin.Forms/pull/469

**Comment by jerone** [comment]
Possible implementation: https://github.com/xabre/xamarin-forms-tab-badge

**Comment by geskill** [comment]
imho, we have two options here:

1. Implementation of a few but the most important attributes: `BadgeText`, `BadgeColor` and `BadgeTextColor`. Skipping Position, Font and other options for now.
2. Universal Badge implementation in a static class using attached properties; `Badge.Text`, `Badge.TextColor`, `Badge.Color`, `Badge.Font`, `Badge.FontAttributes`, `Badge.FontFamily`, `Badge.FontSize`, `Badge.Margin` (...) that can be use everywhere on Buttons, Labels or Images. See here: https://github.com/xabre/xamarin-forms-tab-badge/issues/64

**Comment by programmation** [comment]
Attached properties, please!

**Comment by Syed-Esqimo** [comment]
cmon why is this inactive :(

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
