### ISSUE TITLE
MacOS Xamarin App crashes with 3.2-pre1

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#3353]
### Steps to Reproduce

1. Create new MacOS application
2. I have added menu (in code), but not sure that it could be the root of the problem (I saw some Pull request which has changes in MacOS menu)
2. Run
3. Application crashes on LoadApplication method

### Basic Information

- Version with issue: 3.2-pre1
- Last known good version: 3.1 latest
- IDE: VS for Mac
- Nuget Packages: 3.2-pre1
- Affected Devices: MacOS 10.13.6

**Comment by PureWeen** [comment]
Confirmed. Fresh application with Mac project updated to 3.2 crashes

**Comment by VladislavAntonyuk** [comment]
I am not sure but it could be here https://github.com/xamarin/Xamarin.Forms/commit/b901924d6447b73b5af2bb6d3eee1a58eb6c4cf0#diff-fc961d9e26579e17f41d2f68536b6255
