### ISSUE TITLE
Re-visit Xamarin.Forms.CarouselView

### ISSUE THREAD

**Issue by Heshanp** [xamarin/Xamarin.Forms#3366]
The current release of Xamarin.Forms.CarouselView is outdated/no longer maintained.
It would be nice to get this component up to date and release a new version.

**Comment by VladislavAntonyuk** [comment]
you can use carouselpage instead

**Comment by pauldipietro** [comment]
Please follow #1882.

**Comment by Livven** [comment]
> Please follow #1882.

FYI that issue triggers a 500 server error.
