### ISSUE TITLE
[UWP] ScrollTo method is not working in Xamarin.Forms for UWP platform

### ISSUE THREAD

**Issue by bhaveshsoft1** [xamarin/Xamarin.Forms#3367]
### Description

We are developing chat application using Xamarin.Forms (2.5.0.91635) for UWP. We are trying to implement very basic functionality which is scroll to bottom when user open any chat window or send/receive messages. It working fine where no scroll in chat window but when messages are more then we show vertical scroll bar in chat widow. we are using below line to goes to last item of list view.

                        Device.BeginInvokeOnMainThread(() =>
                        {
                            try
                            {
                                lstMessages.ScrollTo(objlastmessage, ScrollToPosition.Start, false);
                            }
                            catch (Exception ex)
                            {
                            }
                        });

We are use ObservableCollection to store message and bind it with listview.

Now problem is that when messenger app get any message from other user then system add it in observation collection and then move to last message in chat window, in between if if user typing message in Xamarin text editor then it freeze the UI until listivew update. so how to fix this issue. please some need hep. So user is legging in typing.

Please note that receive message in background thread. 

### Steps to Reproduce

1. Make a simple chat window using list view.
2. put the text editor below the chat window
3.  fill the list view from 100 message
4. Now when you try to add more message in list view then it freeze the UI for few second

### Expected Behavior
It should not be freeze.

### Actual Behavior
It should not be freeze.

### Basic Information

Version with issue: Xamarin.Forms 2.5.0.91635 (even I checked in 3.1.0.637273 version too)
Last known good version: Don't know
IDE: Visual Studio 7.4.2 (build 12)
Platform Target Frameworks:

**Comment by Druffl3** [comment]
A little late to the party, but this is not working in XF 4.4.0.991864
