### ISSUE TITLE
Editor does not show a border unlike Entry

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3369]
Hi,

Why the Editor control does not show a border or at least provide option property for border as the Editor will just show a white area on iOS without any border.

Why do we need the Editor inside a Frame  or use platform specific dependencies just to show a border when we don't have to do that in the Entry

Thanks,
Jassim

**Comment by VladislavAntonyuk** [comment]
you can set border color and border width

**Comment by jrahma** [comment]
Editor does not have border property

**Comment by AndreiMisiukevich** [comment]
@samhouts this changes will be breaking
would it be acceptable to adjust them like in iOS Entry?

**Comment by samhouts** [comment]
Duplicate of #3727
