### ISSUE TITLE
[UWP] No Toolbar with Tabbed Template for XF version 3.1.0.637273  

### ISSUE THREAD

**Issue by djaus2** [xamarin/Xamarin.Forms#3379]
### Description
With Xamarin.Forms, when running the Tabbed template, the **NewItem page** doesn't show a Toolbar.
With X.F version 3.1.0.637273. Works OK on Android Emulator
### Steps to Reproduce

1. Create a project: Visual C#/Cross Platform/Mobile App (Xamarin.Forms)
2. Choose Tabbed with .NET Standard Code Sharing and set for UWP target
3. Run app and press [+] Add a new item

### Expected Behavior
NewItem page should show with the Azure toolbar at top.
### Actual Behavior
Page shows but no toolbar on that page
### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: 3.1.0.561732-pre4 (works with this later version)
- IDE:
Windows 10 (1803)
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.8.0 Preview 4.0
VisualStudio.15.Preview/15.8.0-pre.4.0+27906.1
Microsoft .NET Framework
Version 4.7.03056
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  . 16299  Bug also on 17134
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Forms
- Affected Devices: Run on desktop

### Reproduction Link
The Tool_Bug folder in:
https://github.com/djaus2/Xamarin.Forms.DJsBugs

The other project in that repository works on this issue (Its X.F Version 3.1.0.561732-pre4 )

**Comment by jassmith** [comment]
This should be fixed in SR2

**Comment by jassmith** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/3298
