### ISSUE TITLE
Feature request: support using namespace in XAML

### ISSUE THREAD

**Issue by hshristov** [xamarin/Xamarin.Forms#3380]
### Description

Currently in XAML when you want to import class from third party assembly you have to write:
```
xmlns:ns="clr-namespace:X.Y;assembly=Z"
```
As all assemblies are known at compile time the UWP syntax would be more convenient:

```
xmlns:ns="using:X.Y"
```

**Comment by GalaxiaGuy** [comment]
I believe this has already been added:

https://github.com/xamarin/Xamarin.Forms/pull/851

**Comment by StephaneDelcroix** [comment]
`using:` works already, and default to the current assembly

**Comment by hshristov** [comment]
Unfortunately it doesn't work if the type is not in the current assembly and this is exactly my case.
From [porting wpf to uwp](https://docs.microsoft.com/en-us/previous-versions/windows/apps/br229571(v=win.10))
> Instead of using a clr-namespace:/assembly= qualifier set for code-to-XAML namespace references, you use the using: qualifier. XAML namespaces no longer reference specific assemblies; all assembly qualification and inclusion is handled by the application model and how you compose your app package.

Are there any plans on implementing this in Xamarin.Forms?
