### ISSUE TITLE
Please add the Terrain Map Type and Custom Map Pin Rotation to Xamarin.Forms.Maps

### ISSUE THREAD

**Issue by BillyMartin1964** [xamarin/Xamarin.Forms#3382]
I like using Xamarin Forms Maps, but now I need to be able to show the Google Map Terrain and be able to show which way the wind is blowing with a rotating custom pin. I know it can be done, because I've seen it in other apps, so could you please add these features to make it more versatile>

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
