### ISSUE TITLE
[UWP] Navigation bar hidden

### ISSUE THREAD

**Issue by WebDucer** [xamarin/Xamarin.Forms#3383]
### Description

With the current version of Xamarin.Forms (3.1.0.637273) on UWP devices the navigation bar is hidden. With the previous version (3.1.0.583944) it works.

### Steps to Reproduce

1. Create a new Xamarin.Forms app from template
2. Change `MainPage = new MainPage();` to `MainPage = new NavigationPage(new MainPage());` in `App.xaml.cs`
3. Update Xamarin.Forms to version 3.1.0.637273
4. Start UWP app

### Expected Behavior

Navigation bar should be visible on top of the page.

### Actual Behavior

Navigation bar is hidden.

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: 3.1.0.583944
- IDE: VS 2017 15.7.5
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  16299
- Android Support Library Version: default
- Nuget Packages: default
- Affected Devices: Windows 10

### Screenshots

![hiddennavigationbar_3 1 0 637273](https://user-images.githubusercontent.com/761881/43096309-f96873a8-8eb8-11e8-9179-0e34b33a1ca7.png)
![navigationbar_3 1 0 583944](https://user-images.githubusercontent.com/761881/43096310-f98718bc-8eb8-11e8-8eaa-45b0dbaef6f1.png)

**Comment by pauldipietro** [comment]
#3297
