### ISSUE TITLE
Localized satellite packages are not included in build output when using PackageReference

### ISSUE THREAD

**Issue by domyd** [xamarin/Xamarin.Forms#3386]
### Description

[Localized satellite packages](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages#localized-satellite-packages) do not seem to work in a Xamarin app when using the PackageReference restore method. 

Likely related: https://github.com/Humanizr/Humanizer/issues/380

### Steps to Reproduce

Repro project: [SatelliteAssemblyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2223193/SatelliteAssemblyApp.zip). It's a git project with two additional branches: (*Note: the referenced test nuget packages are included in `/localpackages` and restoring them should just work*)

- Branch `works-single-package` references one single NuGet package (`SatelliteAssemblyTest.1.0.0`) that includes the main assembly and one localized resource DLL.
- Branch `doesnt-work-multiple-packages` references two NuGet packages: `SatelliteAssemblyTest.1.0.1` (which only has the main assembly) and `SatelliteAssemblyTest.de.1.0.1` (which only contains the localized resource DLL).

1) Build solution in Release mode
2) Archive Android project to get an APK

### Expected Behavior
The localized resource DLLs are included in the APK in both cases (`/assemblies/de/SatelliteAssemblyTest.resources.dll` exists within the APK). On a device with German culture, the label on the main page should say "Deutsch" in both cases.

Expected APK: [works-single-package.zip](https://github.com/xamarin/Xamarin.Forms/files/2223194/works-single-package.zip)

### Actual Behavior
The localized resources are missing in the case of split nuget packages (`/assemblies/de` doesn't exist within the APK). On a device with German culture, the label on the main page says "English".

Actual APK: [doesnt-work-multiple-packages.zip](https://github.com/xamarin/Xamarin.Forms/files/2223195/doesnt-work-multiple-packages.zip)

### Basic Information

- Version with issue: 3.0.0.561731
- Last known good version: not tested
- IDE: VS 2017 (v15.7.5)
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 27.0.2
- Nuget Packages: none, except the test package(s)

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-android#2012

**Comment by domyd** [comment]
I probably should have mentioned that I did not try this on iOS (or UWP), my bad. 

I just tried it on iOS and got the same issue (AdHoc build): the contents of the localized-resources-only nuget package are missing in the IPA and on an iPhone with only German locale set up, it says "English".
