### ISSUE TITLE
iOS Share Extension code does not execute in Visual Studio or Visual Studio for Mac

### ISSUE THREAD

**Issue by ChrisMacLeanRQI** [xamarin/Xamarin.Forms#3391]
### Description
When trying to integrate an iOS Share Extension into a Xamarin Forms Cross-Platform .NET Standard 2.0 project, the code for the default ShareViewController does not execute.

### Steps to Reproduce

1. Create a new Cross-Platform project and add an iOS Share Extension project
2. When trying to share a photo from the Photo app on either the iOS Simulator or Device, the extension shows up in the Activity list, but code does not execute

### Expected Behavior
Clicking on the Share Extension activity should fire code for ViewDidLoad(), IsContentValid() and DidSelectPost()

### Actual Behavior
No breakpoints are hit on the ShareViewController class and a Debug.WriteLine test does not get executed.

### Basic Information

- Version with issue: Xamarin.Forms v3.1.0.637273
- Last known good version:
- IDE: Visual Studio Professional 2017 v17.7.5 and Visual Studio for Mac v7.5.3
- Platform Target Frameworks: 
  - iOS:  8.0 up to 11.4
 - Nuget Packages:
Microsoft.NETCore.UniversalWindowsPlatform v6.1.5
NETStandard.Library v2.0.3
Xamarin.Android.Support.v4
Xamarin.Android.Support.Design
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.CardView
Xamarin.Android.Support.v7.MediaRouter
Xamarin.Forms v3.1.0.637273

- Affected Devices: iOS Simulator - ALL, iPod Touch 5 iOS v9.3

### Reproduction Link
I could not post the Cross-Platform project since it is too big so I have created a Xamarin.iOS project and posted that.  The same problem occurs.
[iOSShareExtensionTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2228692/iOSShareExtensionTest.zip)

**Comment by jassmith** [comment]
Im very confused about what you are expecting here. You have a Forms iOS head linked against a standard iOS project head. The Forms head never attempts to invoke anything outside what looks like gets generated with the templates and the non-forms head doesn't even properly build? This isn't a bug with the Xamarin.Forms project as best I can tell?

**Comment by ChrisMacLeanRQI** [comment]
We're not entirely sure what you mean by Xamarin Forms iOS head versus standard iOS project head.  I could not upload our Xamarin Forms project because it was too big.  I uploaded a Xamarin.iOS project because it has the same issue.  We have created a new project to test the issue.  It does appear that the Share Extension code is firing, but the breakpoints are not working and System.Diagnostics.Debug.WriteLine doesn't show anything in the Output window.  We can't debug the Share Extension to check what is happening.

**Comment by jgold6** [comment]
This should be an iOS or an IDE issue. Spoke with reporting customer on phone and resolved issue. It appears that when using the iOS Remoted simulator on Windows, the debugger will not attach. 

I will refile the issue in the appropriate place.
