### ISSUE TITLE
OnSizeAllocated does not account for "UseSafeArea"

### ISSUE THREAD

**Issue by jeffreydalby** [xamarin/Xamarin.Forms#3401]
### Description
The width and height from OnSizeAllocated are the full screen size of the device and not the "Safe Area"  thus throwing off any calculations used for placement of objects, such as changing a layout after device rotation.

### Steps to Reproduce

1. Create a page that uses OnSizeAllocated to change the size of objects based on orientation
2. Add UseSafeArea to the page
3. On an iPhone X that object sizes will be incorrect and can expand into the "Safe Area"

Code that can cause this:

```
            if (Width < Height)
            {
                myWidthHeightRequest = Width / 4;
                IconLayout.HeightRequest = Height * 0.60;
                IconLayout.HorizontalOptions = LayoutOptions.Center;
                IconLayout.Orientation = StackOrientation.Vertical;
            }
            else
            {
                myWidthHeightRequest = (Width - 20) / 7;
                mySpacing = 10;
                IconLayout.HeightRequest =myWidthHeightRequest *2;
                IconLayout.HorizontalOptions = LayoutOptions.CenterAndExpand;
                IconLayout.Orientation = StackOrientation.Horizontal;
            }


                Button1.HeightRequest = myWidthHeightRequest;
                Button1.WidthRequest = myWidthHeightRequest;

                Button2.HeightRequest = myWidthHeightRequest;
                Button2.WidthRequest = myWidthHeightRequest;

                Button3.HeightRequest = myWidthHeightRequest;
                Button3.WidthRequest = myWidthHeightRequest;

                Butto4.HeightRequest = myWidthHeightRequest;
                Button4.WidthRequest = myWidthHeightRequest;

                Button5.HeightRequest = myWidthHeightRequest;
                Button5.WidthRequest = myWidthHeightRequest;

                Button6.HeightRequest = myWidthHeightRequest;
                Button6.WidthRequest = myWidthHeightRequest;

                IconLayout.Spacing = mySpacing;
                FirstRow.Spacing = mySpacing;
                SecondRow.Spacing = mySpacing;
                ThirdRow.Spacing = mySpacing;

            }


            }
```

### Expected Behavior
width and height of OnSizeAllocated will take into account the safe area.
### Actual Behavior
width and height are the full size of the screen
### Basic Information

- Version with issue: All that support UseSafeArea
- Last known good version: None
- IDE: Visual Studo
- Platform Target Frameworks: 
  - iOS:  11.x

- Affected Devices: iPhone X

### Screenshots
Example of an image button in a 
![](https://us.v-cdn.net/5019960/uploads/editor/qj/piosdwkgxbb6.png)

See https://forums.xamarin.com/discussion/129392/onsizeallocated-usesafearea-changing-layouts-by-orientation-on-iphone-x for example code.

**Comment by jassmith** [comment]
Have you tried setting SetUseSafeArea to true in the iOS platform specifics? This should solve your problem. You can find the API here: https://github.com/xamarin/Xamarin.Forms/blob/release-3.1.0-sr2/Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Page.cs#L75

**Comment by jassmith** [comment]
Reopen if you still have issues

**Comment by jeffreydalby** [comment]
Yes. That is what is meant by the issue occurs when setting UseSafeArea to true. Is there some other way to set that value? 

We use the XAML way of setting it according to:
https://blog.xamarin.com/making-ios-11-even-easier-xamarin-forms/

xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
    ios:Page.UseSafeArea="true" >
