### ISSUE TITLE
Entry is getting coverd by the Keyboard if you set TranslateY = -100

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#3403]
### Steps to Reproduce

1. Download this reproduction case: https://github.com/ederbond/BugEntryVsKeyboard
2. Run it on android 
3. There are two Entries on the page. Tap both of them, 

### Expected Behavior
 I was expecting that when I tap the Entry's both of them I'll be repositioned above the keyboard.

### Actual Behavior
 The one I've set the TranslationY property gets covered by the keyboard.

### Basic Information

- Version with issue:<PackageReference Include="Xamarin.Forms" Version="3.1.0.637273" />

- Last known good version:

- IDE: Visual Studio 2017 Enterprise

- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 7.0

- Android Support Library Version: 
Xamarin.Android.Support.v4 --- v27.0.2.1
Xamarin.Android.Support.v7.AppCompat --- v27.0.2.1
Xamarin.Android.Support.v7.CardView --- v27.0.2.1
Xamarin.Android.Support.v7.MediaRouter --- v27.0.2.1

- Nuget Packages:
"Xamarin.Forms" Version="3.1.0.637273"

- Affected Devices: 
SAMSUNG GALAXY TAB A (2016)

### Reproduction Link

https://github.com/ederbond/BugEntryVsKeyboard

**Comment by ederbond** [comment]
Hello @jassmith , do you guys have any news on this ?

**Comment by jfversluis** [comment]
Hope this is resolved by now 😬
