### ISSUE TITLE
SwipeDirection enumeration

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3404]
### Description

Should the `SwipeDirection` enumeration have the `Flags` attribute? It's hard to see how a swipe can be both left and right.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/SwipeDirection.cs

**Comment by jassmith** [comment]
You could allow for swipes in multiple directions to trigger the same action
