### ISSUE TITLE
[iOS] System.ObjectDisposedException: from SwitchCellRenderer when changing ItemSource

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3408]
### Description
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CellTableViewCell'.

The exception happens on this line

https://github.com/xamarin/Xamarin.Forms/blob/d3d59ee4f0b3098457e1debe8d7b03d0d0061a53/Xamarin.Forms.Platform.iOS/Cells/SwitchCellRenderer.cs#L5

### Steps to Reproduce

1. Run the Reproduction
2. click on Tabby and/or sphinx at the top

### Expected Behavior
Not to crash

### Actual Behavior
Crashes

### Basic Information

- Version with issue: 3.2 
- Last known good version:  not sure. I tested back to 2.5 and it has the same issue
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  16299 

### Reproduction Link

[AzureChallengerMobileApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2233342/AzureChallengerMobileApp.zip)

**Comment by rmarinho** [comment]
Fixed by #3518
