### ISSUE TITLE
[WPF] ListView and TabbedPage with nested item

### ISSUE THREAD

**Issue by KasperinK** [xamarin/Xamarin.Forms#3410]
### Description
Nested items in a listview render on top of each other when changing tabs.

(The following steps are just the most basic stripped down example I could make. In reality in place of the Grid in the third column I have a ContentView (a custom control) with a Grid inside of it and an image and labels inside of the Grid.)

### Steps to Reproduce
Create a new Xamarin.Forms .NetStandard project.
Add a Xamarin.WPF project.
Create a TabbedPage in your Xamarin.Forms project.
Add a ListView to one of them.
In your item template have a Grid with 3 columns.
Place a label in each of the first two columns.
Place a grid in the third column and put a label inside of it.
Give your listview an ItemsSource.
Switch to tab two and then back to tab one and your UI screws up.

### Expected Behavior
![image](https://user-images.githubusercontent.com/39413152/43284249-cf765dba-90e0-11e8-89ff-187478d57a80.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/39413152/43284291-fa9f9e98-90e0-11e8-99cb-62095bf8a11e.png)

### Basic Information

- Version with issue: 3.1.0.637273
- Last known good version: None
- IDE: Visual Studio 2017 Version 15.7.4
- Nuget Packages: Xamarin.Forms and Xamarin.Forms.Platform.WPF

### Reproduction Link
[ListViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2233373/ListViewIssue.zip)

**Comment by jassmith** [comment]
I think this is due to measure calls being made that don't match the final arrange call that actually gets sent. Whoever picks this up come talk to me if you can and I will try to download the insanity.

**Comment by KasperinK** [comment]
The label says UWP but I think it should be WPF.
