### ISSUE TITLE
[Android] Swipe Command fires twice on Android for each swipe action

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3415]
### Description

The Swipe Gesture Recognizer fires the Swiped Event twice for a single swipe. 

Also it's using HasFlags
https://github.com/xamarin/Xamarin.Forms/blob/67f87df3d4d7ff6d21d176ab56cf2db13cbcad0a/Xamarin.Forms.Core/SwipeGestureRecognizer.cs#L58

I'd recommend changing those out as well

### Steps to Reproduce

Run the reproduction and swipe the screen (left or right). The repro has two labels on the screen that count one each time the Swiped event fires.

Running this same repro on iOS/UWP it only fires each event once

### Expected Behavior
Fire swiped event once for each swipe

### Actual Behavior
Swipe event currently fires twice

### Basic Information

- Version with issue: 3.2
- Last known good version: new features as of 3.2
- IDE:
- Platform Target Frameworks: 
  - Android: 8.1

### Reproduction Link
[SwipeGestures.zip](https://github.com/xamarin/Xamarin.Forms/files/2233803/SwipeGestures.zip)

**Comment by ajaichemmanam** [comment]
I am trying to implement swipe to remove element with the swipe gesture recogniser. As it fires twice, when I remove the element, Cannot access disposed object exception is thrown
