### ISSUE TITLE
Getting SIGABRT 6 in Android when running http calls in parallel

### ISSUE THREAD

**Issue by tsequeira-vhs** [xamarin/Xamarin.Forms#3421]
### Description
We have a Xamarin.Forms app which is crashing with '**signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr -------- java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x3ce2**'

We are running multiple calls to web services with HttpClient in parallel using Task.WhenAll()

The crash is random and due to this we are unable to identify the root cause.

### Steps to Reproduce
1. Login (first time)
2. Set pin code (first time)
3. Enter pin code (from second time)
4. Launches a page with blue header
5. If no crash, kill the app and repeat steps from 3.

Note: To make the crash more frequent enable gref logging using the following ADB command: '**adb shell setprop debug.mono.log gref**'

### Expected Behavior
The app should not crash

### Actual Behavior
App crashes with '**java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x3ce2**'

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 Enterprise
- Platform Target Frameworks:
  - Android: 8.1 
- Android Support Library Version: API 27
- Affected Devices: Tested on Pixel 2 and Samsung S8

### Logs
[ReportLog-1.txt](https://github.com/xamarin/Xamarin.Forms/files/2236090/ReportLog-1.txt)
[ReportLog-2.txt](https://github.com/xamarin/Xamarin.Forms/files/2236091/ReportLog-2.txt)

**Comment by tsequeira-vhs** [comment]
We have attached stripped down version of the code. 
[EngageDummy.zip](https://github.com/xamarin/Xamarin.Forms/files/2236134/EngageDummy.zip)

**Comment by jassmith** [comment]
This issue was moved to xamarin/xamarin-android#2013
