### ISSUE TITLE
ListView ContextActions lose BackgroundColor of selected item (iOS)

### ISSUE THREAD

**Issue by fsantanac** [xamarin/Xamarin.Forms#3422]
### Description
If use a renderer for a  ViewCellRenderer and set the SelectedBackgroundView work fine until add a ViewCell.ContextActions to the listview, loose the set color, convert in gray

### Steps to Reproduce

1. 
Create a xaml listview
2. 
Create ViewCellRenderer class:

        public override UIKit.UITableViewCell GetCell(Cell item, UIKit.UITableViewCell reusableCell, UIKit.UITableView tv)
        {

            var cell = base.GetCell(item, reusableCell, tv);

////////// THIS WORK FINE WITHOUT CONTEXTACTIONS
            cell.SelectedBackgroundView = new UIView
            {
                BackgroundColor = UIColor.FromRGB(0.43f, 0.64f, 0.15f)

            };
             return cell;
        }
3. 
Run on ios

### Expected Behavior
Not loose the BackgroundColor from the SelectedBackgroundView
### Basic Information

- Version with issue:
Xamarin 3.1.0.637273
- Last known good version:
- IDE: VS2017 mac
- Platform Target Frameworks: 
  - iOS: 11.4

**Comment by jassmith** [comment]
iOS wont do this if you set the SelectionMode to disabled however I suspect this isn't what you want. This is iOS doing this by default however :/

**Comment by fsantanac** [comment]
Sorry for my english.
Effectively, I do not want to disable selection. I just want my background color to prevail

**Comment by KSemenenko** [comment]
Maybe our issue #3450 is related?

**Comment by fsantanac** [comment]
No,no, my problem is with selected rows. Atached two images, one image with ViewCell.ContextActions and another without this.
This my code, thee green backgroud is correct, the gray no. if you remove the ViewCell.ContextActions from xaml work fine, show the green color set in  ViewCellRenderer

            <ListView x:Name="listView" ItemsSource="{Binding ListItems, Mode=TwoWay}" SelectedItem="{Binding SelectedItem, Mode=TwoWay}" BackgroundColor="Transparent">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <ViewCell.ContextActions>
                                <MenuItem Command="{Binding BindingContext.DeleteCommand, Source={x:Reference Name=listView}}" CommandParameter="{Binding ID}"
                                    IsDestructive="{Binding borrable}" Text="{i18n:Translate Borrar}" />
                            </ViewCell.ContextActions>
                        
                            <ContentView>
                                <Label Text="{Binding servicio}" VerticalOptions="CenterAndExpand" Margin="10,0,0,0" TextColor="{Binding TextColor}" />
                            </ContentView>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            <ListView.Footer>
                <StackLayout>
                </StackLayout>
            </ListView.Footer>              
        </ListView>

![selectedwithcontexactions](https://user-images.githubusercontent.com/2085673/43475773-b428af60-94ee-11e8-8fbf-fed03fe7976d.png)
![selectedwithoutcontexactions](https://user-images.githubusercontent.com/2085673/43475774-b44d6b8e-94ee-11e8-86df-31490e929f37.png)

**Comment by KSemenenko** [comment]
In fact, I also have problems with the gray background on iOS.

**Comment by bill2004158** [comment]
Same problem in ios

**Comment by bill2004158** [comment]
it seems the answer is:
https://stackoverflow.com/questions/27679863/selectedbackgroundview-is-not-shown-when-tableviewcell-is-selected-programmatica

**Comment by bill2004158** [comment]
when tapped the item it will call this method:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/ContextActionCell.cs#L689  
`table.SelectRow(selector._lastPath, false, UITableViewScrollPosition.None)`
because of that call, ios will update the cell background to gray.

it seems this will fix that problem.
https://stackoverflow.com/questions/18019834/cannot-change-uitableview-blue-highlight-color

**Comment by jfversluis** [comment]
This seems old! :D I'm going to assume we fixed this by now, if not, please let me know!
