### ISSUE TITLE
Effects are lost after Android device change orientation 

### ISSUE THREAD

**Issue by ali-h2010** [xamarin/Xamarin.Forms#3423]
### Description
I created a simple effects to access the toolbar and change the font type and the color of the title. 
which was working fine until i change the orientation where the effects is lost in landscape and not return even if you go back to the original direction. 

If i start with landscape the effect is loaded correctly but same issue if i change the orientation
 
### Steps to Reproduce

1. Create an Effect in Android
2. Apply the effect and access the page
3. change the orientation of the device.

### Expected Behavior
The effect should be reapplied on changing the orientation 
### Actual Behavior
the effect is lost unless the page is reloaded
### Basic Information
I tested with Android 8

- Version with issue: Xamarin 3.1
- Last known good version:- 
- IDE:Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by ali-h2010** [comment]
@pauldipietro ,should i create a reproduction link to this or the issue is clear?

**Comment by jassmith** [comment]
I believe the issue is you have your android activity configure to restart on orientation change. You need to allow the android activity to handle orientation changes (the template should do that by default really) to prevent this from happening.

**Comment by ali-h2010** [comment]
@jassmith Thanks for your response but i have some questions.
Which template are you referring to? And how to handle the orientation in the Android activity? 
Shouldn't Xamarin call the effects on change of orientation?
