### ISSUE TITLE
Feature Request - add view load and unload method

### ISSUE THREAD

**Issue by j4587698** [xamarin/Xamarin.Forms#3426]
### Description

I think view should be away to call load and unload method like page's onappearing and ondisappearing.
It's a very useful method to controlling operations that are required only when the control is displayed.

**Comment by AmrAlSayed0** [comment]
There is already an issue with the same request #2210 and pull request is in progress #3214

**Comment by j4587698** [comment]
@AmrAlSayed0 I didn't find this, I'm close this issues, thanks a lot.
