### ISSUE TITLE
ToolBar with UWP

### ISSUE THREAD

**Issue by pvalade** [xamarin/Xamarin.Forms#3429]
### Description

Toolbar and Title not appearing on all navigation pages

### Steps to Reproduce
1.   Add toolbar and toolbar items in XAML page
2.   Compile for UWP Local Machine 
3.  

### Expected Behavior

Title with toolbar items should appear on main page

### Actual Behavior

Title  with toolbar does not appear

### Basic Information

Toolbar and Title appear on Andoid emulator

- Version with issue:  3.1.0.637273 (including pre
- Last known good version: 3.1.0.583944
- IDE:
- Platform Target Frameworks: 
 - UWP:  16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
#3297
