### ISSUE TITLE
Add VSTS YAML Configuration

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#3430]
### Description

Now that VSTS supports YAML configurations, a YAML build configuration should be added to the repo to better assist the community in being able to run custom builds.

#### Goals

By adding a YAML configuration this should help to do the following:

1. Remove barriers of entry for the F100 by ensuring developers can properly build/test before submitting a PR
1. Attract more adoption by making enterprises feel they can patch and run custom builds for their needs with minimal effort
1. Help developers by getting more 1st hand visibility into how Xamarin.Forms itself is built and then tested.

**Comment by rmarinho** [comment]
it's on my backlog!

**Comment by adrianknight89** [comment]
Please also update [this page](https://github.com/xamarin/Xamarin.Forms/wiki/How-to-Build-Xamarin.Forms-NuGet) when you're done.

**Comment by samhouts** [comment]
closed by #4385
