### ISSUE TITLE
Enhaunchment. Add FilePicker (Open/SaveFileDialog) control

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#3432]

**Comment by GalaxiaGuy** [comment]
I don't think this would depend on anything inside Forms, and so may be better fit elsewhere, for instance:

https://github.com/xamarin/Essentials/issues/251

There is also:

https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows
