### ISSUE TITLE
Bottom navigation bar button focus doesn't work on Android

### ISSUE THREAD

**Issue by VBPrakash** [xamarin/Xamarin.Forms#3434]
### Description
Bottom navigation bar button focus doesn't work on Android

### Steps to Reproduce

1. Create bottom tabbed page on android
2. Try using "Tab" key event on page 
3. "Tab" key event highlights the button element within the page button not tabbed page navigation buttons.

### Expected Behaviour
"Tab" key event should highlight or set focus for the tabbed page navigation buttons when bottom tabbed page is used in Android
### Actual Behavior
"Tab" key event doesn't highlight or focus the tabbed page navigation buttons when bottom tabbed page is used in Android
### Basic Information
"Tab" key event works properly when tabbed page for Android is default or top.
- Version with issue: Xamarin Forms 3.1
- Last known good version: NA
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - Android: 8.1
- Affected Devices: All android devices

### Screenshots

![toptabbedpage](https://user-images.githubusercontent.com/7272034/43377332-a2ec83b4-93dd-11e8-9e88-4b4cafb0cb58.png)
![bottomtabbedpage](https://user-images.githubusercontent.com/7272034/43377333-a315ecfe-93dd-11e8-9dcf-5ce3b7fd52e6.png)

**Comment by samhouts** [comment]
Would you be able to attach your test project to help us reproduce the issue? Thanks!

**Comment by PureWeen** [comment]
Closed for inactivity. If you're able to attach a repro then we can reopen.
