### ISSUE TITLE
ButtonRenderer causing crash in Xamarin forms app in android devices

### ISSUE THREAD

**Issue by Bhauraj001** [xamarin/Xamarin.Forms#3435]
### Description
App is Crashed in all Android devices for Xamarin forms app

System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer'.

### Steps to Reproduce
I have app with 4 buttons and it navigates 4 pages, all 4 pages contains Skiasharp.
1.  When i tap on pages multiple times(navigates between pages)
2. App is crashing with below log.

The same thing works for iOS but it fails in Android..

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer'.
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue parameters)
View.get_Context ()
ButtonRenderer.UpdateBitmap ()
ButtonRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) .invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
BindingExpression.Apply (System.Boolean fromTarget)
BindingExpression+BindingExpressionPart.b__49_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.0fa052d2-505e-4538-a06d-cc6a7f2bcb69(intptr,intptr)*

### Basic Information

- Version with issue: Xamarin Forms 3.0.0.482510
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: Target Version Android 8.1(API Level 27), Minimum Android Version is Android 5.0(API Level 21)

- Nuget Packages:
Microchart v0.8.3 prerelease
- Affected Devices: Attached screenshot from appcenter

### Reproduction Link
![1](https://user-images.githubusercontent.com/35101591/43443754-6b5e5142-94bf-11e8-9c92-6d011379a60c.JPG)
![2](https://user-images.githubusercontent.com/35101591/43443755-6b91cbe4-94bf-11e8-8432-acbd1a8cf021.JPG)
![3](https://user-images.githubusercontent.com/35101591/43443756-6bc3b730-94bf-11e8-8fc3-aa9f1d2346e0.JPG)
![5](https://user-images.githubusercontent.com/35101591/43443757-6beda932-94bf-11e8-9868-fcfeecb8e504.JPG)
![6](https://user-images.githubusercontent.com/35101591/43443758-6c19abea-94bf-11e8-9727-98fc5eb82b34.JPG)
![7](https://user-images.githubusercontent.com/35101591/43443759-6c42149a-94bf-11e8-80ab-dd71e4be7381.JPG)
![8](https://user-images.githubusercontent.com/35101591/43443760-6c77e67e-94bf-11e8-9c15-9b9a0f44ac75.JPG)
![9](https://user-images.githubusercontent.com/35101591/43443761-6ca392ec-94bf-11e8-871d-ffbcffdd07c8.JPG)
![10](https://user-images.githubusercontent.com/35101591/43443762-6ccc6ffa-94bf-11e8-8272-ef71e9526ea7.JPG)

**Comment by Bhauraj001** [comment]
Hi @pauldipietro - Could you please share the work around for the bug.. my app is crashing multiple times for above issues.. error says "System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer'." but I am not using any ButtonRenderers..

**Comment by VladislavAntonyuk** [comment]
please fill the template for the issue

**Comment by Bhauraj001** [comment]
Hi @VladislavAntonyuk - Can you share the document for template, I will update as per template.. I am new to this..

**Comment by VladislavAntonyuk** [comment]
copy it when you create a new issue

**Comment by Bhauraj001** [comment]
Hi @VladislavAntonyuk -  I updated the bug infromation, Can you please look into this. This bug is affecting to almost all devices.

**Comment by rmarinho** [comment]
Hi @Bhauraj001 can you try to update to 3.1.0 and see if you still see this issue? 

Also can you give us a small reproduction of the problem?! Since this also involves SkiaSharp and the crash with ButtonRenderer.UpdateBitmap I suspect these are related. 

We would need to also need the versions you are using from Skia etc, so please provide a small reproduction sample. 

Thanks

**Comment by BhaurajBiradar** [comment]
Hi,

Please see below link for UI

https://forums.xamarin.com/discussion/129658/crash-in-android-for-xamarin-forms-application#latest

and add skiasharp view in all tab page.. keep tapping on multiple times.. app will crash

Sorry for late reply.. I was not well.

**Comment by rmarinho** [comment]
Hi @BhaurajBiradar  that snippet of code is not enough since it doesn't show bits with SkiaSharp. Please provide a small project that reproduces the problem. 

Thanks

**Comment by samhouts** [comment]
@Bhauraj001 @BhaurajBiradar Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
