### ISSUE TITLE
Embedded resource not found (ending with ISO 639-1 language code?)

### ISSUE THREAD

**Issue by EmmanuelJego** [xamarin/Xamarin.Forms#3436]
### Description
Hello !
I was trying to read embedded resource files with a stream (`Stream stream = assembly.GetManifestResourceStream(FilePath)`), but the stream was null, which means the file hasn't been found.
The file path has a format "MyNameSpace.MyResourcesFolder.MyFileName", and "MyFileName" has a format "myFile.en.json" ("en" for "english" because I have to create this file in **different languages**).
The file **has a build action set to "Embedded resource"**.
In order to make sure it wasn't a typing mistake or whatever, I tried to get all embedded resources with `Assembly.GetManifestResourceNames()`, which returned **all my embedded resource files, except this particular file**!
If I rename this file with a format like **"myFile_en.json" (replacing ".en" by "_en"), then the file is found**.

So I thought it was beacause the file name was ending with multiple dots ("name.x.json"). But this is actually not the case : if I rename my file with a format **"myFile.zz.json", then the file is also found**.

It seems like I **can't end a file name with a dot and an ISO 639-1 language code** ("zz" is not a valid language code, but has the same length, which means that this issus is not due to a string length between 2 dots or whatever). I tried multiple language codes ("en", "fr", "es"...) : each time, the file is not found.

### Steps to Reproduce

1. Create a file "myFile.en.json" and another "myFile.zz.json" ("en" or another ISO 639-1 language code which is not marked as "macrolanguage" that you can find at https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
2. Give them a "Embedded resource" build action
3. Get all manifest resources with `var list = IntrospectionExtensions.GetTypeInfo(typeof(MyClass)).Assembly.GetManifestResourceNames();`

### Expected Behavior
Both files are in "list".

### Actual Behavior
Only "myFile.zz.json" is in the list.

### Basic Information
- IDE: Visual Studio 15.7.2

Is it a normal behavior? Or is it due to something else than ISO 639-1 language code? (that's the only reason I found...)

Thanks for your help !
Emmanuel

**Comment by GalaxiaGuy** [comment]
This might be a better question for the Mono team directly:

https://github.com/mono

However, looking at the dotnet reference source version of `ResourceManager.cs`, it does indeed look like it is intentional behavior:

https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/resources/resourcemanager.cs#L88

```
    // basename.culture name.resources
    // 
    // The base name can be the name of your application, or depending on 
    // the granularity desired, possibly the name of each class.  The culture 
    // name is determined from CultureInfo's Name property.  
    // An example file name may be MyApp.en-US.resources for
    // MyApp's US English resources.
```

**Comment by VladislavAntonyuk** [comment]
You have to set neutral language property to en

**Comment by StephaneDelcroix** [comment]
This is unrelated to Xamarin.Forms, and we can't do anything about it. closing.
