### ISSUE TITLE
ButtonRenderer causing crash in Xamarin forms app in android devices

### ISSUE THREAD

**Issue by BhaurajBiradar** [xamarin/Xamarin.Forms#3447]
Description
App is Crashed in all Android devices for Xamarin forms app

System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer'.

Steps to Reproduce
I have app with 4 buttons and it navigates 4 pages, all 4 pages contains Skiasharp.

When i tap on pages multiple times(navigates between pages)
App is crashing with below log.
The same thing works for iOS but it fails in Android..

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer'.
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue parameters)
View.get_Context ()
ButtonRenderer.UpdateBitmap ()
ButtonRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) .invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget)
BindingExpression.Apply (System.Boolean fromTarget)
BindingExpression+BindingExpressionPart.b__49_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.0fa052d2-505e-4538-a06d-cc6a7f2bcb69(intptr,intptr)*

Expected Behavior
Actual Behavior
Basic Information
Version with issue: Xamarin Forms 3.0.0.482510

Last known good version:

IDE: Visual Studio 2017

Platform Target Frameworks:

Android: Target Version Android 8.1(API Level 27), Minimum Android Version is Android 5.0(API Level 21)
Nuget Packages:
Microchart v0.8.3 prerelease

Affected Devices: Attached screenshot from appcenter

Screenshots
Reproduction Link
![1](https://user-images.githubusercontent.com/41940233/43443958-2897c284-94c0-11e8-87a7-260513146a5e.JPG)
![2](https://user-images.githubusercontent.com/41940233/43443959-28c173f4-94c0-11e8-8c33-a3d39604d209.JPG)
![3](https://user-images.githubusercontent.com/41940233/43444015-4a9f97e4-94c0-11e8-923e-b0962ba23b1c.JPG)
![5](https://user-images.githubusercontent.com/41940233/43444016-4af680fe-94c0-11e8-9666-5e6ae9efd441.JPG)
![6](https://user-images.githubusercontent.com/41940233/43444018-4b3c5a2a-94c0-11e8-8061-419e754ccad8.JPG)
![7](https://user-images.githubusercontent.com/41940233/43444019-4b665064-94c0-11e8-95f5-d61fbdca1c10.JPG)
![8](https://user-images.githubusercontent.com/41940233/43444020-4b9148a0-94c0-11e8-885d-33a8238619d2.JPG)
![9](https://user-images.githubusercontent.com/41940233/43444021-4bbe01f6-94c0-11e8-9590-0b68040a8223.JPG)
![10](https://user-images.githubusercontent.com/41940233/43444022-4bed639c-94c0-11e8-801e-6fb7f723dc3c.JPG)

**Comment by rmarinho** [comment]
duplicate #3435
