### ISSUE TITLE
Please support Fluent Design for UWP in Xamarin Form?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/Xamarin.Forms#3449]
As the title, Please support Fluent Design for UWP in Xamarin Form?
Thank you!

**Comment by AdhamAliAhmed** [comment]
Strongly agree
I had to do a lot of custom renderers to achieve so
The thing is that they render XamarinForms pages to custom control. Not UWP pages like Navigation view and Pivot

**Comment by davidortinau** [comment]
@nguyenthanhliemfc and @AdhamAliAhmed it would help me greatly to understand what you've been doing up to now to implement fluent in your apps, and what platforms beyond UWP you're targeting with that design. Would you please share here, or shoot me an email, with your experiences, specific examples, and screenshots? We can talk more about this topic. david.ortinau@microsoft.com

**Comment by AdhamAliAhmed** [comment]
Well... for me i implemented an `Windows.UI.Xaml.Media.AcrylicBrush` in a XF `TappedPage` for an app i was working on.
I tried using an effect and then attaching it to the `TappedPage` but it didn't work. 
It doesn't get attached although i follow all the rules. I created an issue for this couple of days ago BTW.

So i ended up creating a custom control that derives from `TappedPage` and then i created a custom renderer for `UWP` only. The custom renderer derives from `TappedPageRenderer` so the final native image is a `FormsPivot`. `FormsPivot` inherits from `Windows.UI.Xaml.Control.Pivot` so it has all the Pivot properties.
Following the Fluent Design guidelines, first of all: you would extend the view to the toolbar.
`CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = false;`
then, you would apply the `AcrylicBrush` on the `Control.ToolbarBackground`. Here is the building blocks for all this. The shared custom control, The custom renderer and the XAML code. This is 100% XAML friendly.

The custom control: 
[AcrylicTappedPage.cs](https://gist.github.com/AdhamAliAhmed/cd98340971921a52fc5dcbbebf015eb4)
The custom renderer: 
[AcrylicTappedPageRenderer.cs](https://gist.github.com/AdhamAliAhmed/ffe830562f80cf232ae551ada073f404)
The XAML code:
[MainPage.xaml](https://gist.github.com/AdhamAliAhmed/023765ebeb6d5f5e4047385cb7a39692)

To be clear i have some issues with the `CommandBars `and basically all the stuff at the right of the header of the `FormsPivot`.
I also have some hard-coded values for the margins.

But i'm pretty sure you can figure this out

**Comment by AdhamAliAhmed** [comment]
There is three main iconic figures about FluentDesign
1- Acrylic Material Brush
2- RevealHighlight
3- RevealFocus (Not widely used)

All other stuff are just principles.

**Comment by AdhamAliAhmed** [comment]
I tried to make a RevealHighlight effect but i have no experience on consuming ThemeResources in code. Because essentially RevealHighlight is a ThemeResource.

**Comment by AdhamAliAhmed** [comment]
You can write a Xaml markup in a form of string and then read it using a `StreamReader` but the bindings and stuff is gonna be a huge pain in the butt

**Comment by nguyenthanhliemfc** [comment]
I want UWP app in Xamarin Form have Fluent Design as when I create a single UWP project by Windows Template Studio tool.

**Comment by AdhamAliAhmed** [comment]
@davidortinau Any progress so far ?

**Comment by AdhamAliAhmed** [comment]
I've been trying for like two days to create a sample for you that demonstrates my point. But unfortunately I have a problem with my Visual Studio that causes a build failure when deploying to UWP from a XamarinForms project and waiting for the support respond

**Comment by nguyenthanhliemfc** [comment]
For who want to apple Fluent Design for UWP https://github.com/nguyenthanhliemfc/MasterDetailPageFluentDesignForUWP

**Comment by BurkusCat** [comment]
Does `Visual="Material"` work on UWP? Obviously, it would be great if it did but I don't think it would be a huge priority (fluent design makes much more sense on Windows). If it doesn't, I think it would be cool if there was a `Visual="Fluent"`, that for starters, only works on UWP.

You could then set a page to be `<Setter Property="Visual" Value="{OnPlatform iOS=Material, Android=Material, UWP=Fluent}" />`.

I'd personally expect this to effect things like a picker. Try using a Xamarin Forms UWP dark mode picker with a mouse vs using a dark mode picker in the Windows 10 settings app.

Windows 10 settings
![image](https://user-images.githubusercontent.com/7528322/89733214-da69f180-da4b-11ea-87bd-853ac955e3b2.png)

Xamarin Forms UWP
![image](https://user-images.githubusercontent.com/7528322/89733224-f2417580-da4b-11ea-82c0-acf628dfd4d6.png)

**Comment by iTKerry** [comment]
Is there any progress with it after 2 years?

**Comment by mhrastegary77** [comment]
@iTKerry  well i can't even use my renderers anymore in XF 5 :(
it was working in XF 4.7 btw

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Forms, but for .NET MAUI we'll adopt the latest and greatest WinUI styling! Thanks everyone!
