### ISSUE TITLE
OnSizeAllocated does not account for "UseSafeArea" when using iOS platform specifics

### ISSUE THREAD

**Issue by jeffreydalby** [xamarin/Xamarin.Forms#3451]
Since I don't have the ability to reopen an issue that was closed this is for 
https://github.com/xamarin/Xamarin.Forms/issues/3401

With the slight clarification that the issue was specifically for when using the iOS platform specific "UseSafeArea" option that was suggested as a fix (the issue is with the suggested fix)

### Description
The width and height from OnSizeAllocated are the full screen size of the device and not the "Safe Area"  thus throwing off any calculations used for placement of objects, such as changing a layout after device rotation.

### Steps to Reproduce

1. Create a XAML page that uses OnSizeAllocated in the code behind to change the size of objects based on orientation.
2. Add UseSafeArea to the page following the technique show here using iOS platform specific options:
https://blog.xamarin.com/making-ios-11-even-easier-xamarin-forms/
```
xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
ios:Page.UseSafeArea="true" >
```

3. On an iPhone X the object sizes will be incorrect and can even expand into the "Safe Area"

Code that can cause this:

```
            if (Width < Height)
            {
                myWidthHeightRequest = Width / 4;
                IconLayout.HeightRequest = Height * 0.60;
                IconLayout.HorizontalOptions = LayoutOptions.Center;
                IconLayout.Orientation = StackOrientation.Vertical;
            }
            else
            {
                myWidthHeightRequest = (Width - 20) / 7;
                mySpacing = 10;
                IconLayout.HeightRequest =myWidthHeightRequest *2;
                IconLayout.HorizontalOptions = LayoutOptions.CenterAndExpand;
                IconLayout.Orientation = StackOrientation.Horizontal;
            }


                Button1.HeightRequest = myWidthHeightRequest;
                Button1.WidthRequest = myWidthHeightRequest;

                Button2.HeightRequest = myWidthHeightRequest;
                Button2.WidthRequest = myWidthHeightRequest;

                Button3.HeightRequest = myWidthHeightRequest;
                Button3.WidthRequest = myWidthHeightRequest;

                Butto4.HeightRequest = myWidthHeightRequest;
                Button4.WidthRequest = myWidthHeightRequest;

                Button5.HeightRequest = myWidthHeightRequest;
                Button5.WidthRequest = myWidthHeightRequest;

                Button6.HeightRequest = myWidthHeightRequest;
                Button6.WidthRequest = myWidthHeightRequest;

                IconLayout.Spacing = mySpacing;
                FirstRow.Spacing = mySpacing;
                SecondRow.Spacing = mySpacing;
                ThirdRow.Spacing = mySpacing;

            }


            }
```

### Expected Behavior
width and height of OnSizeAllocated will take into account the safe area.
### Actual Behavior
width and height are the full size of the screen
### Basic Information

- Version with issue: All that support UseSafeArea
- Last known good version: None
- IDE: Visual Studo
- Platform Target Frameworks: 
  - iOS:  11.x

- Affected Devices: iPhone X

### Screenshots
Example of an image button in a 
![](https://us.v-cdn.net/5019960/uploads/editor/qj/piosdwkgxbb6.png)

See https://forums.xamarin.com/discussion/129392/onsizeallocated-usesafearea-changing-layouts-by-orientation-on-iphone-x

**Comment by rmarinho** [comment]
You need to check what are SafeArea Insets and use that in your calculation. Since we depend on how the platform treats the safe area insets, when it updates it should set the padding of the page on Xamarin Forms land, so use the Padding on your calculation and maybe also recaluclate when padding changes. 

let me knwo if that works for you.

**Comment by jeffreydalby** [comment]
That's the info I needed.  Elsewhere I had been told that the size and width of OnSizeAllocated took that into account.  Looks like all that needs to be done is to update docs/examples of using UseSafeArea to say- if you are using on size allocated add:

width = width - Padding.HorizontalThickness;
height = height - Padding.VerticalThickness;

to the beginning of your code.

Thank you!
