### ISSUE TITLE
Picker accessibility text is wrong

### ISSUE THREAD

**Issue by CarnageMarkus** [xamarin/Xamarin.Forms#3454]
### Description

Using voiceover/talkback on both Android and iOS, picker control is read as "entry/textfield, double tap to edit",
also adding AutmationProperies.SetName + AutomationProperties.SetHelpText does not prevent device from reading texts in this order:
1. AutomationProperties.SetName 
2. "textfield"
3. AutomationProperties.SetHelpText
4. "double tap to edit"

Additionally, focusing picker (either by method call or by tapping) causes voiceover/talkback to say "character mode, something something"

### Expected Behavior
Read picker as a Button. Picker has no meaning in accessibility (especially on Android). The TextField that's clicked on should read as a "Button" and not a text field because the action a user is going to take on the picker will be the same as a button.  When a user hears that something is an "edit text field" that tells the user the interaction is going to be via a keyboard.

Using SetName and SetHelpText also needs to be more resilient on Android which will probably involve injecting yourself into the delegates that are used to build the help text used.

https://stackoverflow.com/questions/25641081/android-acccessibility-how-do-i-change-the-text-read-out-loud-for-an-edittext-v

Also once something is selected the "Text Field" needs to retain whatever was set for SetName and SetHelpText. 

### Actual Behavior
picker is read as textfield/entry

### Basic Information

- Version with issue: 3.1.0.583944
- IDE: VS for Mac Comunity 2017 
- Platform Target Frameworks: 
  - iOS: 11.4
  - Android: 27
- Android Support Library Version: v7

**Comment by samhouts** [comment]
closed by #5125 and #5145

**Comment by andos716** [comment]
I am still getting this issue in Xamarin Forms 4.8?
