### ISSUE TITLE
Ability to set SetCanceledOnTouchOutside in android AlertDialogs when using Page.DisplayAlert

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#3455]
Right now, the default behavior of android AlertDialogs is to set the SetCanceledOnTouchOutside to true. Since this is done in the PopupManager class which is an internal class, I don't see any way to inject any code somewhere to set it back to false. Is it possible at all? Or do I need to create a whole custom DisplayAlert system to be able to set this?

Just to be clear, we would to have some popup to not close when clicking somewhere outside of the popup and force the user to make a choice.

**Comment by samhouts** [comment]
Do you only need this in Android?

**Comment by PaulVrugt** [comment]
@samhouts 
Well, the default behavior in iOS is already that you need to make a choice, tapping anywhere outside of the popup doesn't close it on iOS, on Android it does.

I don't know what the behavior on UWP is since we don't develop for UWP

**Comment by samhouts** [comment]
Gotcha! Thank you!

**Comment by quentinR0bert** [comment]
Any news about this request ?

**Comment by maexsp** [comment]
We also run into this problem. Is there any workaround for now? On iOS it is by default not cancelable. 
We would need to set this only for Android.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
