### ISSUE TITLE
[iOS] MasterDetail on Tablet incorrectly measures layout on rotation to landscape 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3458]
### Description
When running  the app on iPad simulator and rotating repeatedly to landscape (typically the 2nd time landscape is shown) the content will be shoved to the right.

This doesn't occur with `MasterBehavior = MasterBehavior.Popover;`

### Steps to Reproduce

1. Run the app on iPad
2. Rotate twice to landscape

### Expected Behavior
Layout should be consistent, no gap to left.

### Actual Behavior
Gap

### Basic Information

- Version with issue: 3.2.0-pre1
  - iOS:  11.4

### Screenshots

Before:
<img width="1259" alt="screenshot 2018-08-01 14 18 30" src="https://user-images.githubusercontent.com/41873/43543835-cff53e40-9596-11e8-81f7-c45615202fea.png">

After: 
<img width="1259" alt="screenshot 2018-08-01 14 15 47" src="https://user-images.githubusercontent.com/41873/43543843-d5dc3db8-9596-11e8-80b6-f542cef55a3b.png">

### Reproduction Link

https://github.com/davidortinau/flexibility/

Update it to 3.2.0-pre1

**Comment by rmarinho** [comment]
this is related with #3085 

workaround: Update to 3.1.0 and  had this to your project

`[assembly: ExportRenderer(typeof(MasterDetailPage), typeof(TabletMasterDetailRenderer), UIUserInterfaceIdiom.Pad)]`

**Comment by cbartonnh** [comment]
@davidortinau We are seeing this issue in 3.1 stable as well. Do we know when this fix might hit a preview build? it is not in pre2 and we are a bit too close to releasing the code to introduce a nightly...
