### ISSUE TITLE
NuGet package claims it supports UAP 10.0, but it actually only supports UAP 10.0.15138

### ISSUE THREAD

**Issue by steffenloesch** [xamarin/Xamarin.Forms#3461]
According to #2859, Xamarin.Forms 3.0 relies on .NET Standard 2.0 and hence is not expected to run on Windows versions below the Fall Creators Update. However, the NuGet package still claims that the `uap10.0` target framework is supported: https://www.nuget.org/packages/Xamarin.Forms. Should the package layout be changed to give `uap10.0.15138` as supported target instead of `uap10.0`?

**Comment by samhouts** [comment]
Since the issue you refer to (#2859) is asking us to update the package layout to 10.0.15138, this issue is a duplicate. Thank you.
