### ISSUE TITLE
UWP Xamarin.Forms cannot use System.ServiceModel.Http NuGet Package

### ISSUE THREAD

**Issue by riwaida** [xamarin/Xamarin.Forms#3462]
### Description
When UWP app project refers System.ServiceModel.Http NuGet package, it always crashes with following exception message and callstack.

> ((System.IO.FileLoadException)e.Exception).Message
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Could not load file or assembly 'System.ServiceModel.Primitives, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> e.Exception.RemoteStackTrace
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> at App1.MainPage..ctor()
> at App1.App..ctor()
> at App1.UWP.MainPage..ctor()
> at App1.UWP.App1_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage()
> at App1.UWP.App1_UWP_XamlTypeInfo.XamlUserType.ActivateInstance()
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Steps to Reproduce
(Attached [App1.zip](https://github.com/xamarin/Xamarin.Forms/files/2252576/App1.zip) sample project to reproduce the problem)
1. On VS2017, create new Xamarin.Forms solution as following option.
 Platform: Windows (UWP)
 Code Sharing Strategy: .NET Standard
2. When you done creating a solution, you can find two projects in Solution Explorer.
3. Right click on code sharing project, you can click [Manage NuGet Packages...].
4. On NuGet Package Manager, search "System.ServiceModel.Http" and install the latest version one (v4.5.3).
5. Next, please replace with the code below for MainPage.xaml.cs for code sharing project.
~~~~~~~~~~~~~~~~~~~~~
using System.ServiceModel;
using Xamarin.Forms;

namespace App1{
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            var channel = new ChannelFactory<ITest>(new BasicHttpBinding(), new EndpointAddress("http://localhost:8000/Example"));
        }
    }

    [ServiceContract()]
    public interface ITest
    {
    }
}
~~~~~~~~~~~~~~~~~~~~~
6. Launch and execute app with Debug x86 or x64 build.

### Expected Behavior
Launch application without any problem.
### Actual Behavior
Crash with 'System.IO.FileLoadException' at LoadApplication().
~~~~~~~~~~~~~~~~~~~~~
namespace App1.UWP
{
    public sealed partial class MainPage
    {
        public MainPage()
        {
            this.InitializeComponent();

            LoadApplication(new App1.App());  << Exception 'System.IO.FileLoadException' occurs at here
        }
    }
}
~~~~~~~~~~~~~~~~~~~~~
### Basic Information

- Version with issue: Xamarin.Forms v3.1.0.697729
- Last known good version: System.ServiceModel.Http v4.4.4
- IDE: Any editions of Visual Studio 2017 (Version 15.7.5)
- Platform Target Frameworks: 
  - iOS:  Not confirmed.
  - Android: This problem does not occured on Android platform.
  - UWP:  UAP,Version=10.0.16299.0
- Android Support Library Version: 
- Nuget Packages:
 Microsoft.NETCore.UniversalWindowsPlatform 3.1.7
 Xamarin.Forms 3.1.0.697729
 NETStandard.Library 2.0.3
 System.ServiceModel.Http 4.5.3
- Affected Devices:
Windows Devices

- Other version info
 Xamarin Designer   4.12.1 (f3257e429)
 Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
 Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)
 Xamarin.Android Reference Assemblies and MSBuild support.
 Xamarin.iOS and Xamarin.Mac SDK   11.12.0.4 (64fece5)
 Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by rmarinho** [comment]
You should open this issue in the System.ServiceModel.Http NuGet related repository, it doesn't seem this issue is related to Xamarin.Forms itself.

**Comment by riwaida** [comment]
Thanks Rui,
I forwarded this as WCF's one (https://github.com/dotnet/wcf/issues/3088)
