### ISSUE TITLE
Visibility state of a label doesn't change in the native renderer

### ISSUE THREAD

**Issue by Swathi-Gopal** [xamarin/Xamarin.Forms#3464]
### Description
I have tried to get the Xamarin.Forms Label properties mapped to its native view for  eg. XF.UWP by declaring as Custom Label(custom class inherited from Label )

In order to get Custom Label native view ,accessed by using (Platform.CreateRenderer(customlabel).GetNativeElement() as Windows.UI.Xaml.FrameworkElement ) method.

And noticed that in native view (GetNativeElement() as Windows.UI.Xaml.FrameworkElement ) all property value gets updated from XForms label (text, foreground and so) except **Visibility** (in XF.Label IsVisble set as false) and it’s not updated in native view Visibilty , But in UI Label's Visibility gets collapsed.

How can I get mapped Visibility value from native element created and when its gets updated?

In Pcl - 

**label.IsVisible = false;**

### Steps to Reproduce
Run the attached sample.
1.  Set IsVisible for Label as False.
2. Implement interface for LabelRenderer
3. In the native label renderer, inside the interface, return native view created through PlatformRenderer.

### Expected Behavior
 Label should not be visible in the view and Visibility property of the TextBlock in the native view should be **Collapsed**.

### Actual Behavior

Though Label is not be visible in the view as expected, while debugging **Visibility** property of the TextBlock in the native view is shown as Visible.

### Basic Information

Nuget Packages: 
- Xamarin Forms version used: 2.5.0.122203.
Also tested in latest version.

- Affected Devices:
Checked for Xamarin Forms UWP Desktop

### Screenshots

![label_visibility](https://user-images.githubusercontent.com/36147200/43575899-9a6f3396-9665-11e8-9f30-d2971197a92c.png)

### Reproduction Link

Attached the issue reproducing sample for Xamarin Forms UWP platform. But need to confirm the working and required suggestions for all three Xamarin Forms platforms (Android,iOS and UWP).

[CustomEntrySample.zip](https://github.com/xamarin/Xamarin.Forms/files/2252936/CustomEntrySample.zip)

Could anyone check this and share your suggestions for this? Is this the behavior or how does it work internally?

**Comment by rmarinho** [comment]
Hi this is not the way one should be writing custom Renderers , what do you want to achieve?
You should manually create the label  then set all the properties yourself on the control. 

What you are doing is just the creating a new renderer from inside your renderer, from what I can understand from your code.

**Comment by PureWeen** [comment]
Closed for inactivity. If you're able to address rmarinho's question we can reopen
