### ISSUE TITLE
ScrollView scroll to top automatically in iOS

### ISSUE THREAD

**Issue by vipulpatel808** [xamarin/Xamarin.Forms#3465]
### Description
When user click on hide or display stack layout inside scrollview, it will automatically scrolls to top of page. This issue is happens only in iOS and in Android it is working fine. Please refer the attached video.

### Steps to Reproduce

1.  Added Scrollview in xamarin forms application
2.  Inside it add stack layouts some of them are visible & some of them are hidden
3. Run the application, scroll down & try to show stacklayout which is hidden by default on click of another stacklayout.

### Expected Behavior
Scroll of scrollview should maintain where user has scrolled.

### Actual Behavior
Scroll of page is automatically scroll to top on any action.

### Basic Information

- Version with issue: 3.2.0.637442-pre1
- Last known good version: no
- IDE: Visual Studio Community on Windows 10
- Platform Target Frameworks: 
  - iOS:  11.2
  - Android: Working fine
  - UWP: NA
- Android Support Library Version: 
- Nuget Packages: https://www.nuget.org/packages/Xamarin.Forms/3.2.0.637442-pre1
- Affected Devices: Any iPhone

### Screenshots
Please find below link of video

https://drive.google.com/file/d/1fVHG-72coKDoEevKN4-D8Ei2XwBu1I74/view?usp=sharing

**Comment by rboyette** [comment]
I'm also seeing this issue in Xamarin Forms v3.1.0.583944. This seems to be similar to [this bug here from bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=33385). I'll see if I can get a reproduction of it

**Comment by PureWeen** [comment]
Closed for inactivity. If you're able to attach a repro then we can reopen.

**Comment by lucassuburu** [comment]
having the same problem here...

**Comment by vipulpatel808** [comment]
Hi PureWeen,

Sorry for the delay as I didn't get the notification for update. I have prepared a demo project whch you can download from below link.

https://drive.google.com/file/d/1_7YkUax0oxtkfpWn27yQbrtUma4Kow1a/view?usp=sharing

Steps to reproduce.
1) Click on more details of 1st layout
2) Scroll down
3) Click on more details of 2nd layout

You can see that scrollview scrolls to top of page automatically.

Thanks,
