### ISSUE TITLE
Feature Request - Dotnet New Templates

### ISSUE THREAD

**Issue by studio315b** [xamarin/Xamarin.Forms#3471]
With Xamarin Forms being .net standard, could we get dotnet templates? I'd love to be able to develop Android apps on my Linux machine.

I'd be willing to do the work if someone could link me to the Visual Studio templates to base them off.

**Comment by dansiegel** [comment]
this should be fairly straight forward... @pierceboggan I'm guessing you already have them for the new templates in VS & VS Mac... just a matter of pushing the generated NuGet.

**Comment by adrianknight89** [comment]
@kingces95 Should this be reported to the VS team instead similar to #3593?

**Comment by jfversluis** [comment]
This is already here for .NET MAUI, yay!
