### ISSUE TITLE
[UWP] Cannot set GroupTemplate height in Xamarin Forms

### ISSUE THREAD

**Issue by knightmeister** [xamarin/Xamarin.Forms#3472]
### Description
This happens only on UWP. I am trying to set a different height on a group header within my `ListView`, and it's not working. The content of the header is cropped, but the layout height for the group header is not reduced.

### Steps to Reproduce

To do a quick reproduction of this, I started with the [Xamarin Forms listview grouping sample][2]. I've included the XAML and code behind, the view models are [available at Github][3].

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:local="clr-namespace:ListView"
                 x:Class="ListView.MainPage"
                 BackgroundColor="#181f32">
    
        <ContentPage.Content>
            <ListView x:Name ="lstView" IsGroupingEnabled="true" 
                      GroupDisplayBinding="{Binding LongName}" 
                      GroupShortNameBinding="{Binding ShortName}"
                      HasUnevenRows="True">
                <ListView.GroupHeaderTemplate>
                    <DataTemplate>
                        <ViewCell Height="10">
                            <ContentView BackgroundColor="Red">
                                <Label Text="{Binding LongName}"
                                   FontAttributes="Bold"
                                   FontSize="12"
                                   TextColor="Black"
                                   BackgroundColor="Yellow"/>
    
                            </ContentView>
                        </ViewCell>
                    </DataTemplate>
                </ListView.GroupHeaderTemplate>
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell Height="44">
                            <Grid BackgroundColor="White">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="*" />
                                </Grid.RowDefinitions>
                                <Label Text="{Binding Name}" Grid.Row="0" />
                                <Label Text="{Binding Comment}" Grid.Row="1" />
                            </Grid>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </ContentPage.Content>
    
    </ContentPage>

And the code behind:

	public partial class MainPage : ContentPage
	{

        private ObservableCollection<GroupedVeggieModel> grouped { get; set; }

        public MainPage()
		{
			InitializeComponent();

            grouped = new ObservableCollection<GroupedVeggieModel>();
            var veggieGroup = new GroupedVeggieModel() { LongName = "vegetables", ShortName = "v" };
            var fruitGroup = new GroupedVeggieModel() { LongName = "fruit", ShortName = "f" };
            veggieGroup.Add(new VeggieModel() { Name = "celery", IsReallyAVeggie = true, Comment = "try ants on a log" });
            veggieGroup.Add(new VeggieModel() { Name = "tomato", IsReallyAVeggie = false, Comment = "pairs well with basil" });
            veggieGroup.Add(new VeggieModel() { Name = "zucchini", IsReallyAVeggie = true, Comment = "zucchini bread > bannana bread" });
            veggieGroup.Add(new VeggieModel() { Name = "peas", IsReallyAVeggie = true, Comment = "like peas in a pod" });
            fruitGroup.Add(new VeggieModel() { Name = "banana", IsReallyAVeggie = false, Comment = "available in chip form factor" });
            fruitGroup.Add(new VeggieModel() { Name = "strawberry", IsReallyAVeggie = false, Comment = "spring plant" });
            fruitGroup.Add(new VeggieModel() { Name = "cherry", IsReallyAVeggie = false, Comment = "topper for icecream" });
            grouped.Add(veggieGroup); grouped.Add(fruitGroup);
            lstView.ItemsSource = grouped;
        }
	}

### Expected Behavior
The list view group headers do not have padding between the header and the first list item. This works as expected in Android and iOS.

### Actual Behavior
UWP only - There is a large space between the group header and the first list item.

  [1]: https://i.stack.imgur.com/OprXZ.png
  [2]: https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/ListView/Grouping/
  [3]: https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/ListView/Grouping/groupingSampleListView/groupingSampleListView/ViewModel/veggieModel.cs

### Screenshots
![bug](https://user-images.githubusercontent.com/1528425/43623409-6e88c368-9724-11e8-85ae-cbb68ff162e5.png)

**Comment by rmarinho** [comment]
Seems dupe for the issue #3448
