### ISSUE TITLE
[Android] Device.OpenUri("https://google.coom"); throws exception

### ISSUE THREAD

**Issue by xyashapyx** [xamarin/Xamarin.Forms#3474]
### Description

While calling Device.OpenUri("https://google.coom"); on old versions of Android exception happens.
Exception:
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. 

### Steps to Reproduce

1. open Device.OpenUri("https://google.coom"); on android versions 5 or 6

### Expected Behavior
Opens link in a browser
### Actual Behavior
Exception throws
### Basic Information

- Version with issue:
- Last known good version:
- IDE: 
- Platform Target Frameworks: 3.1.0.637273
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
HI Forms only supports Android API15 our higher.

**Comment by xyashapyx** [comment]
But that's problem occurs on Android API 21, 22 and 23, (Android 5.0-6.0)
