### ISSUE TITLE
[iOS] LayoutCompression Performance Issues

### ISSUE THREAD

**Issue by endarea** [xamarin/Xamarin.Forms#3475]
On iOS, using `CompressedLayout.SetIsHeadless` on multiple elements slows down the page. For example, adding 150 labels to a `Page` (each label wrapped in a `StackLayout`) takes quite a while to render:
1. The page pushed from "Without LayoutCompression" button renders in under 2 seconds
2. The page pushed from "With LayoutCompression" button renders in about 13 seconds. The only difference between the pages is that `LayoutCompression` is set on each `StackLayout`

The same issue seems to be described here: https://forums.xamarin.com/discussion/107099/layout-compression-slowing-down-pages

_Without LayoutCompression:_
![without_layoutcompression_01](https://user-images.githubusercontent.com/41328559/43636058-b1eeccfc-9719-11e8-9125-56564c27090e.png)

_With LayoutCompression:_
![with_layoutcompression_01](https://user-images.githubusercontent.com/41328559/43636088-c66f27bc-9719-11e8-9605-c71b287b4a4b.png)

### Expected Behavior
Layout compression should improve page rendering performance. On Android both versions (with/without `LayoutCompression` set) render in under 1 second on my phone, with slightly better performance when setting `LayoutCompression`.

### Basic Information

- Version with issue: : Xamarin.Forms 3.1.0.637273
- Last known good version: -
- IDE:
- Platform Target Frameworks:
  - iOS:  : 11.4
- Affected Devices: Tested on iPhoneX Simulator (iOS 11.4) and iPhone 5C (iOS 10.3.3)

### Reproduction Link
[LayoutCompression.zip](https://github.com/xamarin/Xamarin.Forms/files/2256873/LayoutCompression.zip)

**Comment by Evolutionlab** [comment]
I experienced the same issue: on iOS, LayoutCompression slow down the rendering on complex layout

**Comment by pauldipietro** [comment]
Thank you for the reproduction; the split on my Mac was about 1.5/11.5.

**Comment by JKennedy24** [comment]
This seems like quite a big issue.

When trying to optimise your views you use `CompressionLayout` and end up making it 10x worse. Looks like a good easy sample that someone who understands `compressionlayout` should be able to diagnose?
