### ISSUE TITLE
[Android] Device.OpenUri("https://google.coom"); throws exception

### ISSUE THREAD

**Issue by xyashapyx** [xamarin/Xamarin.Forms#3477]
### Description
While calling Device.OpenUri("https://google.com"); on old versions of Android exception happens.
Exception:
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag.
### Steps to Reproduce

1. open Device.OpenUri("https://google.com"); on aAndroid API 21, 22 and 23, (Android 5.0-6.0)

### Expected Behavior
Opens link in a browser

### Actual Behavior
Exception throws

### Basic Information

- Version with issue:
- Last known good version: 3.1.0.637273
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by VladislavAntonyuk** [comment]
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag.

Set this flag

**Comment by VladislavAntonyuk** [comment]
Also provide the source where the problem is reproduced

**Comment by xyashapyx** [comment]
I'm just calling this Device.OpenUri("https://google.coom"); code from my view model. 
How can I add that flag while calling Device.OpenUri?

**Comment by VladislavAntonyuk** [comment]
in manifest file on your android project

**Comment by samhouts** [comment]
@xyashapyx What devices/emulators are you experiencing this crash on? Thanks!

**Comment by xyashapyx** [comment]
I've fixed that with using package that @jamesmontemagno provided.
