### ISSUE TITLE
Allow TintColor and UnselectedItemTintColor as platform-specifics

### ISSUE THREAD

**Issue by robertmiles3** [xamarin/Xamarin.Forms#3478]
### Description
Now that we have...

```
On<Android>().SetBarItemColor(Color.Red);           // Unselected image+text color
On<Android>().SetBarSelectedItemColor(Color.White); // Selected image+text color
```

...we no longer need a TabbedPage renderer for Android just to set these items. However, it is still required to have an iOS TabbedPage renderer to set the equivalents on iOS side (`TintColor` and `UnselectedItemTintColor`). For feature parity between the two (and for ease of setting these very common properties), I propose the equivalents on iOS such as...

```
On<iOS>().SetTintColor(Color.Red);                 // Unselected image+text color
On<iOS>().SetUnselectedItemTintColor(Color.White); // Selected image+text color
```

### Basic Information

Xamarin.Forms 3.1.0.697729

**Comment by rscholey** [comment]
Has anyone looked into the setting of translucent in iOS.  If your page is black and you try to set the tab areas to black then they will appear as very dark grey unless you have something like this to set translucent to false:

    public class CustomShellRenderer : ShellRenderer
    {
        protected override IShellSectionRenderer CreateShellSectionRenderer(ShellSection shellSection)
        {
            var renderer = base.CreateShellSectionRenderer(shellSection);
            if (renderer != null)
            {
                var a = (renderer as ShellSectionRenderer);
                (renderer as ShellSectionRenderer).NavigationBar.Translucent = false;
            }
            return renderer;
        }

        protected override IShellItemRenderer CreateShellItemRenderer(ShellItem item)
        {
            var renderer = base.CreateShellItemRenderer(item);
            (renderer as ShellItemRenderer).TabBar.Translucent = false;
            return renderer;
        }
    }
