### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by pereirafabiosantos2018** [xamarin/Xamarin.Forms#3481]
Please, add theses properties to Editor:
- Placeholder, PlaceholderColor, BorderColor.

Thanks.

**Comment by AmrAlSayed0** [comment]
A pull request #2012 for this is already merged and will be released with 3.2.0.

**Comment by samhouts** [comment]
Yep, this issue duplicates #1907 and #3369. Please follow those issues for updates. Thank you!
