### ISSUE TITLE
Cannot able to restrict the bouncing effect when we fling the scroll view in xamarin forms MacOs if VerticalScrollElasticity property is None

### ISSUE THREAD

**Issue by pradeepkumar417** [xamarin/Xamarin.Forms#3488]
Hi Team,

### Description
I have changed the **VerticalScrollElasticity** property value as **None** to disable the bouncing effect of the ScrollView in macOS renderer platform. Unfortunately, Bouncing effect is not working if fling action is performed in the scroll view for fast scrolling. Meanwhile, if ScrollView is dragged slowly, the bouncing effect is not enabled as expected.

### Steps to Reproduce
1. Run the attached sample.
2. Scroll to some rows down (say 5-10 rows).
3. Fling the scroll view towards the upwards direction to reach the top of the view. Now you can see the bouncing effect when the view reaches the top even if I define the **VerticalScrollElasticity**  as **None**.

### Expected Behavior
Bouncing effect should disable when the ScrollView reaches the top/bottom of the view.

### Actual Behavior
Bouncing effect is still occurs when the ScrollView reaches the top/bottom of the view.(when we fling the ScrollView)

### Basic Information

Visual Studio Community 2017 for Mac
Version 7.5.2 (build 40)
Installation UUID: aec84a52-8539-4ee5-b218-939a7ad80dec
Runtime:
    Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
 
    Package version: 510010057
 
NuGet
Version: 4.3.1.4445
 
.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    2.0.5
    2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.4/Sdks
SDK Versions:
    2.1.4
    2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks
 
Xamarin.Profiler
Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
 
Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/syncfusion/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        4.2    (API level 17)
        4.3    (API level 18)
        4.4    (API level 19)
        4.4.87 (API level 20)
        5.0    (API level 21)
        5.1    (API level 22)
        6.0    (API level 23)
        7.0    (API level 24)
        7.1    (API level 25)
        8.0    (API level 26)
 
SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26.0.1
SDK Build Tools Version: 25.0.3
 
Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
 
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
 
Apple Developer Tools
Xcode 9.0 (13247)
Build 9A235
 
Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)
 
Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400
 
Xamarin Inspector
Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1
 
Build Information
Release ID: 705020040
Git revision: cfe2fc0566bc4db990242959de40505a13f58352
Build date: 2018-05-30 11:24:18-04
Xamarin addins: 3ac7413ef51a88e06367313c27aec8f7292752a6
Build lane: monodevelop-lion-d15-7
 
Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
 
Enabled user installed addins
Internet of Things (IoT) development (Preview) 7.1

### Screenshots

[ScrollView Bouncing.zip](https://github.com/xamarin/Xamarin.Forms/files/2261921/ScrollView.Bouncing.zip)

### Reproduction Link

[simple.zip](https://github.com/xamarin/Xamarin.Forms/files/2261922/simple.zip)

**Comment by pradeepkumar417** [comment]
Hi Team,

Any update on this report???

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
