### ISSUE TITLE
Objectdisposed crash when closing app in release build

### ISSUE THREAD

**Issue by PaulVrugt** [xamarin/Xamarin.Forms#3489]
### Description
Lately, we have an app that crashes every time the app is closed (swiped away) in android. The issue ONLY occurs on release builds. On debug builds the app works fine. The exception stacktrace (caught by appcenter) is:

JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer'.
JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)
JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
DrawerLayout.RemoveDrawerListener (Android.Support.V4.Widget.DrawerLayout+IDrawerListener listener)
NavigationPageRenderer.Dispose (System.Boolean disposing)
Object.Dispose ()
Platform.SetPageInternal (Xamarin.Forms.Page newRoot)

This is a very pressing issue for us, since we are unable to release an update for our app when the app crashes (almost) every time it is closed.

### Steps to Reproduce
We cannot seem to reproduce it in a small app. I seems to happen to 1 of our 3 apps. Even though there is major code sharing between them.

### Expected Behavior
App doesn't crash on close

### Actual Behavior
App crashes on close

### Basic Information

- Version with issue:
- Last known good version: don't know. Reverted back until 3.0.482510 but app still crashed.
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - Android: 8.1 (27)
- Android Support Library Version: 27.0.2.1
- Nuget Packages: Lots.
- Affected Devices: Tested on LG Nexus 5X

### Reproduction Link
We are unable to create a small reproduction. It seems be a race condition in our app that isn't present in a small demo app. We're trying to discover a point in time in our history where the error started occurring, which might give us a clue as to what is the trigger for this issue.

**Comment by samhouts** [comment]
Can you try the package linked in https://github.com/xamarin/Xamarin.Forms/issues/2004#issuecomment-410796027 and see if it happens to resolve your issue? Thanks!

**Comment by samhouts** [comment]
This issue was moved to xamarin/xamarin-macios#4583

**Comment by PaulVrugt** [comment]
@samhouts  thanks for the info!

I'll try with the package and get back to you with the result of the test

**Comment by samhouts** [comment]
@PaulVrugt That's disappointing! Good find narrowing down the Android version, however. Hopefully, that is a good clue. 

Would you mind trying the workaround in https://github.com/xamarin/Xamarin.Forms/issues/2004#issuecomment-411520373? I'm wondering if this is another symptom of the GC bug https://github.com/xamarin/xamarin-android/issues/2049.

**Comment by ZwaanBanaan** [comment]
@samhouts I have tried the workaround #2004 and it had no effect. I also tried disable Linking, AOT and using the concurrent garbage collector but these also had no effect.

**Comment by PaulVrugt** [comment]
To clarify. I have been moved to a different project. @ZwaanBanaan is still on the apps project and has taken over responsibility of this issue.

**Comment by samhouts** [comment]
Okay, thank you for taking the time to try the workarounds! Next step: please send me the code, if you can, to sahou at Microsoft, and we'll see what we can find. Thanks!

**Comment by ZwaanBanaan** [comment]
Unfortunatly our code has a closed source and it whould become a lot of work to strip down our application without knowing for sure if we can reproduce the problem then. We do want to share our code but is there some kind of garantee that can be provided to us that our code won't be shared with 3th parties?

**Comment by ZwaanBanaan** [comment]
@samhouts is there some kind of service to savely share our closed source project?

**Comment by ZwaanBanaan** [comment]
We made some changes to the code and it seems that the problem only occurs one on every 15 times we close the app. We aren't able to reproduce it and we think that it could be a timing issue. We also can't reproduce it in our stripped down project so we are going to leave it like this and see if the problem reoccurs in the future. Thanks for all the help!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue. Thank you!

**Comment by PaulVrugt** [comment]
@samhouts 
What's the deal with this issue? I'm confused by all the status updates. It seemed what is was fixed in 4.1.0, but now it's moved back to "in progress", while bug issue is still closed.

**Comment by samhouts** [comment]
@PaulVrugt It should be fixed in 3.6, 4.0, and 4.1 now. Sometimes our project scripts go a little crazy. Thanks! :)
