### ISSUE TITLE
Xamarin.iOS: Nullable DateTimeOffset can't use Property.SetInfo

### ISSUE THREAD

**Issue by MaxFe** [xamarin/Xamarin.Forms#3490]
This error occured the first time while deserializing a json string. The destination object had a nullable DateTimeOffset. Using a DateTimeOffset works fine. The statement from Xamarin.iOS documentation is "Using Reflection's Property.SetInfo to set the value on a Nullable<T> is not currently supported.".

### Description
Xamarin.iOS limitations:  https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations  
EF Core should have the same problem: https://bugzilla.xamarin.com/show_bug.cgi?id=61053
Since AutoMapper (version 7.0.1) is using reflection too it might have the same problem (untested).

### Steps to Reproduce

1.  Create an object with nullable DateTimeOffset
2.  Create a json string for that object where the DateTimeOffset variable is null
3.  Deserialize this string -> crash

### Expected Behavior
Should deserialize like not nullable DateTimeOffset

### Actual Behavior
App crash on deserialize nullable DateTimeOffset

### Basic Information

- IDE: Visual Studio for Mac 7.5.4 (Build 3)
- Platform Target Frameworks: 
  - iOS:  11.4.1 (15G77)
- Nuget Packages:  Newtonsoft.Json 11.0.2
- Affected Devices: iPad

**Comment by samhouts** [comment]
This issue was moved to xamarin/xamarin-macios#4584
