### ISSUE TITLE
Application.Quit throws an error

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3491]
Hi,

I am trying just a simple:

Application.Quit()

but getting:

Error CS0120: An object reference is required for the non-static field, method, or property 'Application.Quit()' (CS0120)

**Comment by samhouts** [comment]
Can you please attach a sample project that shows what you're trying to do? Thank you!

**Comment by jrahma** [comment]
I was referring to just a normal ReadOnly property similar to the WinForm TextBox's ReadOnly because currently if I want to make the Entry or Editor readonly I will have to set IsEnabled to false then change the color to normal Entry text color (black) because setting it to disabled will confuse the user as there is a difference between disabled and readonly so I was suggesting to make it easier in one strep to set read only to true or false

**Comment by jrahma** [comment]
Please see the attached

[ApplicationQuit.zip](https://github.com/xamarin/Xamarin.Forms/files/2266734/ApplicationQuit.zip)

**Comment by samhouts** [comment]
Try `Application.Current.Quit()`. `Application.Current` is the instance. If you have further questions such as this, you may want to try posting them on the forums (https://forums.xamarin.com/categories/xamarin-forms). Thank you!

**Comment by jrahma** [comment]
I only tried Application.Quit because it was mentioned here:

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.quit?view=xamarin-forms

regarding the Application.Current.Quit() it does nothing when you call it as you can see in this attached project.
[ApplicationQuit.zip](https://github.com/xamarin/Xamarin.Forms/files/2267334/ApplicationQuit.zip)

**Comment by samhouts** [comment]
Ah, that's good feedback. We should update the documentation to be more clear here. This feature was added for desktop platforms only ( see #1126). It doesn't apply to mobile platforms. Sorry for the confusion.

**Comment by jrahma** [comment]
thanks Samantha 👍
