### ISSUE TITLE
[Enhancement] IsPanning and additional touch events

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3493]
# IsPanning and additional touch events to PanGestureRecognizer

This will provide a bindable property on PanGestureRecognizer to indicate that the gesture is currently in the state of panning.
It will also add the additional Start,Cancel, and TouchEvents being added to the rest of the gestures

_Note: Nothing in this specification is guaranteed to be final; all features, implementations, and interfaces are subject to change._

# API

## Supporting APIs

In order to provide the user with as much available information as possible, we are going to add additional information about all currently active touches. 

#### GestureEventArgs
[Additional Touch Data Attached to Updated events](https://github.com/xamarin/Xamarin.Forms/issues/3479)

### PanGestureRecognizer
```C#
public sealed class PanGestureRecognizer : GestureRecognizer
{
	public bool IsPanning { get; }
  
	public ICommand FinishedCommand { get; set; }
	public object FinishedCommandParameter { get; set; }

  	// Bindable Property will live on GestureRecognizer
	public ICommand CancelledCommand { get; set; }
	public object CancelledCommandParameter { get; set; }
	
	// Bindable Property will live on GestureRecognizer
	public ICommand StartedCommand { get; set; }
	public object StartedCommandParameter { get; set; }  
}
```
### Properties

| API | Description |
| ------------- | ------------- |
| IsPanning | The status of this the Gesture is running but not completed. |
| CancelledCommand | If the gesture starts then gets cancelled for some reason this command will fire.  |
| CancelledCommandParameter ||
| StartedCommand | Gesture has recognized the touch and is responding to touch changes.  |
| StartedCommandParameter ||

### PanGestureRecognizer 

Will now inherit from [GestureEventArgs](https://github.com/xamarin/Xamarin.Forms/issues/3479) so it can receive additional touch point data

```csharp
public class PanGestureRecognizer : GestureEventArgs
{	
}
```

### Examples

```XAML
<StackLayout
	BackgroundColor="{Binding IsPanning, 
			  Source={x:Reference panGesture}, 
			  Converter={StaticResource boolToColor}}">
    <StackLayout.GestureRecognizers>
        <PanGestureRecognizer x:Name="panGesture" />
  </StackLayout.GestureRecognizers>
</StackLayout>
```

Demonstrates binding the background color of the container view to the IsPanning property and setting the BackgroundColor through a converter. This allows the user to easily tie visual indicators to the PanGestureRecognizer while a pan is occurring.

**Comment by jfversluis** [comment]
Already marked as for .NET MAUI, let's close here
