### ISSUE TITLE
[Enhancement]  TapGestureRecognizer Improvements

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3494]
# TapGestureRecognizer Improvements
- IsTapping
	- Specified number of touches have come down and back up but it hasn't reached the number of taps required to be recognized as Tapped.
- Updated Event Args
	- Adds an event to the Gesture Recognizer with additional information about the fingers causing the tap
- NumberOfTouches
	- Allows for multiple touch tapping

_Note: Nothing in this specification is guaranteed to be final; all features, implementations, and interfaces are subject to change._

# API

## Supporting APIs

In order to provide the user with as much available information as possible, we are going to add additional information about all currently active touches. 

#### GestureEventArgs
[Additional Touch Data Attached to Updated events](https://github.com/xamarin/Xamarin.Forms/issues/3479)

### TapGestureRecognizer
```C#
public sealed class TapGestureRecognizer : GestureRecognizer
{
  	public bool IsTapping { get; }
  
  	// Bindable Property will live on GestureRecognizer
	public ICommand CancelledCommand { get; set; }
	public object CancelledCommandParameter { get; set; }
	
	// Bindable Property will live on GestureRecognizer
	public ICommand StartedCommand { get; set; }
	public object StartedCommandParameter { get; set; }  
	
	public static readonly BindableProperty NumberOfTouchesProperty;
	public int NumberOfTouches { get; set;}
  
	public event EventHandler<TapUpdatedEventArgs> TapUpdated;
}
```
### Properties

| API | Description |
| ------------- | ------------- |
| IsTapping | Specified number of touches have come down and back up but it hasn't reached the number of taps required to be recognized as Tapped. |
| CancelledCommand | If the gesture starts then gets cancelled for some reason this command will fire.  |
| CancelledCommandParameter ||
| StartedCommand | Gesture has recognized the touch and is responding to touch changes.  |
| StartedCommandParameter ||
| NumberOfTouchesRequired | Number of touch points required for gesture command to execute (default 1). |

### Events

| API | Description |
| ------------- | ------------- |  
| TapUpdated | Occurs whenever there is a change is state for this Gesture.  |

### TapUpdatedEventArgs 

```csharp
public class TapUpdatedEventArgs : GestureEventArgs
{	
	public GestureStatus StatusType { get; }
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| GestureStatus | Indicates state of gesture (Started, Running, Canceled, Completed). |

### Examples

```XAML
<StackLayout BackgroundColor="{Binding IsTapping, 
			  Source={x:Reference tapGesture}, 
			  Converter={StaticResource boolToColor}}">
    <StackLayout.GestureRecognizers>
        <TapGestureRecognizer x:Name="tapGesture" />
  </StackLayout.GestureRecognizers>
</StackLayout>
```
Demonstrates binding the background color of the container view to the IsTapping property and setting the BackgroundColor through a converter. This allows the user to easily tie visual indicators to the TapGestureRecognizer while a tap is occurring.
***

```XAML
<Image Source="ThreeFingers.jpg">
    <Image.GestureRecognizers>
        <TapGestureRecognizer
		NumberOfTouchesRequired="3"
		NumberOfTapsRequired="2"
                StartedCommand="{Binding OnStarted}" />
  </Image.GestureRecognizers>
</Image>
```

When three fingers come into contact with an image and are released the OnStarted command will fire.

***

```C#
public class TapContainer : ContentView
{
  BoxView touchView;
  
  public TapContainer()
  {
    var tapGesture = new TapGestureRecognizer ();
    tapGesture.TapUpdated += OnTapUpdated;
    tapGesture.NumberOfTouchesRequired = 4;
    GestureRecognizers.Add (tapGesture);
  }

  void OnTapUpdated (object sender, TapUpdatedEventArgs e)
  {
    TouchEvent data = e.TouchEvent;
    if(e.StatusType == GestureStatus.Started)
    {
    	this.BackgroundColor = Color.Yellow;
    }
    else if(e.StatusType == GestureStatus.Completed)
    {
    	this.BackgroundColor = Color.Green;
    }
    else 
    {
    	this.BackgroundColor = Color.Default;
    }
  }
}
```

The user taps the view once (touch has come down and been released) which will set the BackgroundColor to Yellow. It will now remain Yellow until they have tapped 3 more times or stopped tapping.

**Comment by jamessdixon** [comment]
I am new to XF and I opened this issue on SO:  https://stackoverflow.com/questions/53273005/xamarin-forms-tap-and-double-tap

So when a tap happens, we know if the tap is a single, double, or other -> perhaps number of taps.  The downside is that the single tap will have a delay until it is determined that there are not other taps.  This is a tradeoff I would gladly make.  Perhaps set the delay via a property or in the constructor?

**Comment by KSemenenko** [comment]
@PureWeen This can be easily implemented using TouchGuesterRecoginzer.
Can I create a new one that will be called a type of MultiTapRecogizer and TapRecogizer be kept original.

**Comment by Tommigun1980** [comment]
Please add duration for long tap support, or remove the sealed keyword from the class. I don't think any class in Xamarin should be sealed as it makes it impossible to extend any functionality, which is especially important as the core functionality Xamarin provides is extremely limited for any kind of app development.

**Comment by jfversluis** [comment]
Already marked as for .NET MAUI, let's close here
