### ISSUE TITLE
 MasterDetail on Mac crashes when navigation from a subview to a different view from master

### ISSUE THREAD

**Issue by matthewpritchett** [xamarin/Xamarin.Forms#3495]
### Description
When navigating with a MasterDetail view in a Xamarin.Forms macOS project. You can navigate between the main pages fine. But if you navigate to a child page of one of the main pages and attempt to go from there directly to a different main page, an exception is thrown. I created a repo with a sample project that reproduces this issue.

pseudo code (actual repo link at bottom):
_navigationService.NavigateAsync("/MainPage/NavigationPage/ViewA");
_navigationService.NavigateAsync("SubViewA");
_navigationService.NavigateAsync("NavigationPage/ViewB");

### Steps to Reproduce

1. Run project
2. Click on SubViewA label to navigate to the subviewA page.
3. Now click on the ViewB label to navigate to ViewB page.
4. You should see an exception here.

### Expected Behavior
No exception

### Actual Behavior
Exception

### Basic Information

- Last known good version: na
- Xamarin.Forms version: 3.1.0.637273
- IDE: VisualStudio Mac

### Reproduction Link

[https://github.com/baywolf-studios/TestMasterDetail](https://github.com/baywolf-studios/TestMasterDetail)

**Comment by baywolf-studios** [comment]
Just checking if you guys need anything else from me to troubleshoot the bug?

**Comment by baywolf-studios** [comment]
Just checking to see if anyone had been able to look at this issue.

**Comment by baywolf-studios** [comment]
Checking if anyone had had time to review this issue as it’s a fairly big application breaking bug. Thanks.

**Comment by baywolf-studios** [comment]
Checking in for any updates..

**Comment by baywolf-studios** [comment]
@samhouts just checking if anyone has had time to review this bug. Thanks!

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
