### ISSUE TITLE
[suggestion] Xamarin.Forms.UI package for cross platform UI

### ISSUE THREAD

**Issue by John0King** [xamarin/Xamarin.Forms#3496]
Current Xmarin.Forms is force on platform native look,  but for most phone development ,  developers who use native language want thire app look the same or similar on each platform.

Why don't build a beautiful cross platform UI by default and force on customization ?

and most phone app won't running on desktop, we can have different namespance in that package `Xamrin.Forms.UI.Phones` `Xamarin.Forms.UI.Desktop`  `Xamarin.Forms.UI.Tvs`

**Comment by pauldipietro** [comment]
Take a look at [Shell](https://github.com/xamarin/Xamarin.Forms/issues/2415) and feel free to contribute to the discussion.

**Comment by John0King** [comment]
@pauldipietro  Is the Shell spect  just a default page with many configurable properties ? 
My Suggesstion is about add a default layout/control that can be customize, and also add many many out-of-box layouts/controls. Each layout or control behavior not depend on the platform but depend on Xmal  or Xamarin look.   Then we can code Xamarin.Forms like native language (without things like `<OnPlatform />` )
This package will add more controls day by day , make develop much easier .
