### ISSUE TITLE
Feature Request - Default Value for Converter if Binding is null

### ISSUE THREAD

**Issue by wegascee** [xamarin/Xamarin.Forms#3497]
**Summary**
If an UI element has BindingContext `null` than the attached converter isn't called. Here some default value is taken. It would be nice if we could define a default value for such cases. E.g. similar to `TargetNullValue` /`FallbackValue` in WPF.

**API Changes**

E.g. for the mentioned converter issue:

Code behind:
`public Binding (string path, Xamarin.Forms.BindingMode mode = Xamarin.Forms.BindingMode.Default, Xamarin.Forms.IValueConverter converter = null, object converterParameter = null, string stringFormat = null, object source = null, object fallbackValue);`

Xaml:
`BackgroundColor="{Binding IsUnread, Converter={StaticResource UnreadColorConverter}, FallbackValue=Color.White}"`

**Intended Use Case**
For cases where a binding has not yet been set or the binding is set to `null` to have a placeholder UI element

**Comment by mohachouch** [comment]
It’s coming in 3.2.0 : https://github.com/xamarin/Xamarin.Forms/pull/2742
