### ISSUE TITLE
[Xamarin.Forms] QUESTION : How to save ContentPage UI as a PDF and Print.

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#3498]
### Description
QUESTION : 
I want to design a Layout and  Print it on A4 page.
So, How do I save Content Page as a PDF and Fire it on Printer.

### Platforms:
Android
UWP
IOS

**Comment by Paul-Brenner-Tangoe** [comment]
This is something to post to the forums. This is for bug tracking.

**Comment by samhouts** [comment]
Yep, I think you'll have better luck with your question on https://forums.xamarin.com/categories/xamarin-forms, @ashishm29. This is a little outside our scope here. Thank you!
