### ISSUE TITLE
Multiple Custom Renderer for a particular renderer?

### ISSUE THREAD

**Issue by Himatheja** [xamarin/Xamarin.Forms#3499]
### Description
Can we Create two Custom renderers for a particular renderer ? Please provide any link for Custom Entry Renderer (iOS)?

### Basic Information

- IDE:
- Platform Target Frameworks: 
~Apple Developer Tools
Xcode 9.4.1 (14161)
Build 9F2000

~Xamarin.Mac
Version: 4.4.1.193 (Visual Studio Community)

~Xamarin.iOS
Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

~Xamarin.Android
Version: 8.3.3.2 (Visual Studio Community)
~Android SDK: /Users/******/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
- Nuget Packages:

Version: 4.3.1.4445

**Comment by samhouts** [comment]
You can! Follow the instructions on https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/entry. You can create `MyEntry` and `MyEntry2`, both inheriting from `Entry` and `EntryRenderer`. If you need additional guidance, you may want to post your question on the forums (https://forums.xamarin.com/categories/xamarin-forms). Thank you!
