### ISSUE TITLE
[Enhancement] RotateGestureRecognizer

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3504]
# RotateGestureRecognizer

When two fingers have moved enough in the opposite direction to be considered a rotation. The gesture ends when both fingers are lifted

_Note: Nothing in this specification is guaranteed to be final; all features, implementations, and interfaces are subject to change._

# API

## Supporting APIs

In order to provide the user with as much available information as possible, we are going to add additional information about all currently active touches. 

#### GestureEventArgs
[Additional Touch Data Attached to Updated events](https://github.com/xamarin/Xamarin.Forms/issues/3479)

## RotateGestureRecognizer

RotateGestureRecognizer will provide a Rotation Gesture

```csharp
public class RotateGestureRecognizer
{
	public static readonly BindableProperty IsRotatingProperty;
	public bool IsRotating { get; set; }
  
  	// Bindable Property will live on GestureRecognizer
	public ICommand CancelledCommand { get; set; }
	public object CancelledCommandParameter { get; set; }
	
	// Bindable Property will live on GestureRecognizer
	public ICommand StartedCommand { get; set; }
	public object StartedCommandParameter { get; set; }  
	
	public event EventHandler<RotateGestureUpdated> RotateGestureUpdated;	
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| IsRotating | Rotate Gesture is currently active and sending updates to RotateGestureUpdated. |
| CancelledCommand | If the gesture starts then gets cancelled for some reason this command will fire.  |
| CancelledCommandParameter ||
| StartedCommand | Two fingers have moved in opposite directions enough to be considered a rotation.  |
| StartedCommandParameter ||

### Events

| API | Description |
| ------------- | ------------- |
| RotateGestureUpdated | Occurs whenever there is a gesture event on the native device related to Rotating  |

### RotateGestureUpdatedEventArgs 
```csharp
public class RotateGestureUpdatedEventArgs : GestureEventArgs
{	
	public double Total { get; }
	public double Delta { get; }
	public Point Center {get; }
}
```

### Properties

| API | Description |
| ------------- | ------------- |
| Total | The total rotation in degrees since the Gesture started. |
| Delta | The number of degrees changed since the last update event. |
| Center | Bindable property indicating the current center point between the two fingers used for this rotation. |
| Velocity | The velocity of the rotation in degrees per second. |

### Examples
```XAML
<StackLayout
	BackgroundColor="{Binding IsRotating, 
			  Source={x:Reference rotateGesture}, 
			  Converter={StaticResource boolToColor}}">
    <StackLayout.GestureRecognizers>
        <RotateGestureRecognizer x:Name="rotateGesture" />
  </StackLayout.GestureRecognizers>
</StackLayout>
```

Demonstrates binding the background color of the container view to the IsRotating property and setting the BackgroundColor through a converter. This allows the user to easily tie visual indicators to the RotateGestureRecognizer while a rotate is occurring. 

***
```C#
public class RotateContainer : ContentView
{
  BoxView touchView;
  
  public RotateContainer ()
  {
    var rotateGesture = new RotateGestureRecognizer ();
    rotateGesture.RotateGestureUpdated += OnRotateUpdated;
    GestureRecognizers.Add (rotateGesture);
  }

  async void OnRotateUpdated (object sender, RotateUpdatedEventArgs e)
  {
    TouchEvent data = e.TouchEvent;
    if(e.StatusType == GestureStatus.Started || e.StatusType == GestureStatus.Running)
    {
    	await Task.WhenAll (
	  this.RelRotateTo(e.Delta, e.Delta / e.Velocity),
	  this.TranslateTo(e.Center.X, e.Center.Y, 0)
	);
	
    }
  }
}
```

This demonstrates rotating and translating a ContentView as the user performs a rotation gesture on the screen.

**Comment by jfversluis** [comment]
Marked as .NET MAUI material, let's close this one here!
