### ISSUE TITLE
[UWP] PR #3299 causes NRE (crash) in ScrollViewRenderer

### ISSUE THREAD

**Issue by activa** [xamarin/Xamarin.Forms#3505]
### Description

UWP apps crash when opening a page with a ScrollView

Crash is caused by a missing null check in the UpdateContent() method in Xamarin.Forms.Platform.UAP / ScrollViewRenderer.cs. The bug was introduced in PR #3299 

### Steps to Reproduce

In a UWP app, navigate to a page with a ScrollView

### Expected Behavior

Doesn't crash

### Actual Behavior

Crashes with NRE on line 136 in Xamarin.Forms.Platform.UAP / ScrollViewRenderer.cs

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: 3.1.0.637273

**Comment by activa** [comment]
See also #3507

**Comment by JKennedy24** [comment]
This issue has been closed. Does this mean it has been fixed?

I am still seeing this issue with latest XF package (3.1.0 SR2)

**Comment by JKennedy24** [comment]
ok I can see the duplicate issue and will link it here for anyone else
https://github.com/xamarin/Xamarin.Forms/issues/3507

I'm guessing this is fixed in 3.2.0
