### ISSUE TITLE
WPF Platform: Custom Renderer not Focusable/Keydown not able to fire

### ISSUE THREAD

**Issue by brettclutch** [xamarin/Xamarin.Forms#3506]
### Description
When using a 'Custom Renderer' which in my case is displayed as the Details of a MasterDetailPage. I can never get the Control.Keydown or Control.GotFocus events to fire, even though I set Control.Focasable = true. There is something higher up in the chain eating the focus events and preventing Keydown events from firing on the Custom Renderer.

**Comment by jfversluis** [comment]
Sorry we never got to this! I hope you have something figured out in the meantime 😅 closing this here in an attempt to make our administration a bit better.
