### ISSUE TITLE
Better exception management for resourcedictionary styles

### ISSUE THREAD

**Issue by stefano-corricelli** [xamarin/Xamarin.Forms#3512]
### Description
When you accidentally define multiple style with same x:Key in ResourceDictionary, when you start the application the exception thrown is "expected to have a root view controller at the end of application launch" that is not useful to identify the problem

### Steps to Reproduce

1. Define multiple style with same x:Key in App resourcedictionary
2. Launch app

### Expected Behavior
A better error message

### Actual Behavior
A not useful message

### Basic Information

- IDE: Visual Studio Mac 
- Platform Xamarin.Forms 3.1.0

**Comment by stefano-corricelli** [comment]
it occours also in iOS

**Comment by StephaneDelcroix** [comment]
At runtime, this exception is thrown

> System.ArgumentException : A resource with the key 'foo' is already present in the ResourceDictionary.

and it happens with XamlC on or off. Could you please share a sample app triggering this issue for you ?

Thanks

**Comment by stefano-corricelli** [comment]
i'm working on mac:

Visual studio for mac Version 7.5.4 (build 3)
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
NuGet
Versione: 4.3.1.4445
[exception.txt](https://github.com/xamarin/Xamarin.Forms/files/2282672/exception.txt)

**Comment by stefano-corricelli** [comment]
i'm available for a skype call if you need to see something else

**Comment by PureWeen** [comment]
@stefano-corricelli   can you include  sample targeting the latest forms release?
https://www.nuget.org/packages/Xamarin.Forms/3.2.0.809874-pre3

**Comment by stefano-corricelli** [comment]
> @stefano-corricelli can you include sample targeting the latest forms release?
> https://www.nuget.org/packages/Xamarin.Forms/3.2.0.809874-pre3

ok i'll try

**Comment by StephaneDelcroix** [comment]
No new activity on this, so I'm closing it. If it happens again, make sure to attach a small project triggering the problem, that uses the latest XF version.
