### ISSUE TITLE
How do I use my own IoC container in DependencyService?

### ISSUE THREAD

**Issue by robertsundstrom** [xamarin/Xamarin.Forms#3522]
I want to inject instances of services from my IoC-container of choice into the constructor of a markup extension. Is there a safe way to hook it up?

I use ```Microsoft.Extensions.DependencyInjection``` as an abstraction.

**Comment by robertsundstrom** [comment]
Now I see that MarkupExtensions are required to have a parameterless constructor.

And that the ```IServiceProvider``` that gets passed into the ```ProvideValue``` method only resolves XAML services.

In my case I have a ```TranslateExtension``` with a dependency on a ```ResourceContainer``` service which is currently being resolved by a Service Locator (a bad pattern). I would rather inject the ```ResourceContainer``` in the constructor. 

Anyway, it would be useful to be able to inject anything everywhere provided that you have registered your service provider. 

I suggest building an infrastructure based around a common abstraction layer that supports multiple provider, such as ```Microsoft.Extensions.DependencyInjection```.

**Comment by AmrAlSayed0** [comment]
I know I am missing something here but wasn't this already implemented by #1870 ?

**Comment by robertsundstrom** [comment]
@AmrAlSayed0 Yes. I've done some more experimentation, and I got it working with ```ResolveUsing```. However, it does not work for MarkupExtensions. A parameterless constructor is required to activate the class.

**Comment by AmrAlSayed0** [comment]
@robertsundstrom Sorry I deleted my comment after realizing I was wrong. You are right, MarkupExtensions still use Activator.CreateInstance for resolving. https://github.com/xamarin/Xamarin.Forms/blob/e3b6e4755eda0e7611694929d6b0529ee2c40d4b/Xamarin.Forms.Xaml/MarkupExtensionParser.cs#L38

**Comment by StephaneDelcroix** [comment]
markup extensions can't have ctor parameters injected. but you can use property injection, that ends up being similar at the end (a ctor parameter is no more than a property being set, with some guarantee of timing)
