### ISSUE TITLE
[iOS] Finicky tap gesture recognition on Spans

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3525]
### Description

I tried out the new gesture recognizer functionality on Spans that's part of 3.2. When adding a `TapGestureRecognizer` to a `Span` from C#, while taps are detected on the `Span` they are really finicky on iOS.

```
            var span = new Span { Text = "default, " };
            span.GestureRecognizers.Add(new TapGestureRecognizer { Command = new Command(async () => await DisplayAlert("Tapped", "This is a tapped Span.", "OK")) });
            formattedString.Spans.Add(span);
```

### Steps to Reproduce

1. Run the attached sample. It will launch the LabelPageCode.
2. Tap the "default" text, in the final Label (this Label comprises three Spans).

### Expected Behavior

The `TapGestureRecognizer` detects the tap and displays an alert, regardless of the exact location where the `Span` is tapped.

### Actual Behavior

The `TapGestureRecognizer` detects the tap and displays an alert, provided you click on an area above the text. For example, clicking on the black pixels that make up the word doesn't result in the alert being displayed. But clicking just above a letter displays the alert (e.g. click just above the "u").

### Basic Information

- Version with issue: 3.2.0.637442-pre1
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  11.4

### Reproduction Link

[Text.zip](https://github.com/xamarin/Xamarin.Forms/files/2274106/Text.zip)

**Comment by PureWeen** [comment]
If I click around really fast it also throws the following exception

![image](https://user-images.githubusercontent.com/5375137/43926744-8328b120-9be8-11e8-9215-db0e39a6502e.png)
