### ISSUE TITLE
[Android] GetFragment(Page, bool, bool); System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index

### ISSUE THREAD

**Issue by jkereako** [xamarin/Xamarin.Forms#3528]
### Description
Our Android crash logs reported an index out-of-range exception in the method [GetFragment(Page, bool, bool)]. It appears GetFragment(Page, bool, bool) indexes into the array `_fragmentStack` without performing a  bounds check. 

```csharp 
Fragment GetFragment(Page page, bool removed, bool popToRoot)
{
    // pop
    if (removed)
        return _fragmentStack[_fragmentStack.Count - 2];

    // pop to root
    if (popToRoot)
        return _fragmentStack[0];
    
    // push
    return FragmentContainer.CreateInstance(page);
}
```

I should mention that [other parts of the caller](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L762) of GetFragment(Page, bool, bool), namely SwitchContentAsync(Page, bool, bool, bool), do perform bounds checks on `_fragmentStack`.

### Steps to Reproduce
Reproduction steps are unclear. I _think_ it could be reproduced by calling `PopToRootAsync` multiple times.

### Expected Behavior
I would expect this method or it's caller to perform a bounds check to ensure that `_fragmentStack` has elements. If there are no elements, I'm not sure what the correct action would be since GetFragment(Page, bool, bool) returns a Fragment which is used in the caller.

### Actual Behavior
[GetFragment(Page, bool, bool)] assumes that `_fragmentStack` contains elements even if it's empty and indexes into the array.

### Basic Information
- Version with issue: 3.1.0.637273
- Last known good version:
- IDE: VisualStudio for Mac Community, 7.5.4 (3)
- Platform Target Frameworks: 
  - iOS:  10
  - Android: 8.0
- Android Support Library Version: 4
- Nuget Packages:
- Affected Devices: All Android devices

### Stack Trace
```
ThrowHelper.ThrowArgumentOutOfRange_IndexException ()
2
NavigationPageRenderer.GetFragment (Xamarin.Forms.Page page, System.Boolean removed, System.Boolean popToRoot)
3
NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot)
4
NavigationPageRenderer.OnPopToRootAsync (Xamarin.Forms.Page page, System.Boolean animated)
5
NavigationPageRenderer.PopToRootAsync (Xamarin.Forms.Page page, System.Boolean animated)
6
NavigationPageRenderer.OnPoppedToRoot (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e)
7
NavigationPage+<PopToRootAsyncInner>d__79.MoveNext ()
8
ExceptionDispatchInfo.Throw ()
9
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
10
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
11
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
12
TaskAwaiter.GetResult ()
13
NavigationPage+<PopToRootAsync>d__50.MoveNext ()
14
ExceptionDispatchInfo.Throw ()
15
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
16
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
17
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
18
TaskAwaiter.GetResult ()
19
NavigationContextExtensions+<HandleDeeplink>d__3.MoveNext ()
20
ExceptionDispatchInfo.Throw ()
21
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
22
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
23
Thread+RunnableImplementor.Run ()
24
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
25
(wrapper dynamic-method) System.Object.df2497ed-753b-4774-a317-88b3b6941b74(intptr,intptr)
```
[GetFragment(Page, bool, bool)]: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L818-L830

**Comment by samhouts** [comment]
I know this is a difficult one to reproduce, but if you can manage to create a small reproduction project that more or less mimics the structure of the app in which you see this issue, that would be helpful. Thank you!

**Comment by jkereako** [comment]
@samhouts Alrighty I'll give this a shot. I'll try to reproduce this in a small test project. I'll have time to work on it this weekend.

**Comment by adrianknight89** [comment]
> I would expect this method or it's caller to perform a bounds check to ensure that _fragmentStack has elements. If there are no elements, I'm not sure what the correct action would be since GetFragment(Page, bool, bool) returns a Fragment which is used in the caller.

When I wrote this method, I intentionally left out the bounds check so that the root cause can be identified elsewhere. If there are no elements, the team needs to decide why and what to do about it.

**Comment by logicsandbox** [comment]
@samhouts @jkereako This can be reproduced by pushing a page onto the NavigationStack from the App.xaml.cs as the app is starting, and then removing the page at any point.

For me, looking at the NavigationStack and the Modal stack, they are identical both when the app crashes and when it does  not (if that page is added, but not during the startup process). Is there something lower level that is still initializing when App.xaml.cs code is running?

 I am working on making a repo to show this.

**Comment by javisoft** [comment]
I'm having the same issue when upgrading from 3.2 to 3.3. The workaround from @logicsandbox worked for me.

**Comment by alexanderzuban-usic** [comment]
Have the same with version 4.6.0.847

`List`1[T].get_Item (System.Int32 index)
NavigationPageRenderer.GetFragment (Xamarin.Forms.Page page, System.Boolean removed, System.Boolean popToRoot)
NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot)
NavigationPageRenderer.OnPopToRootAsync (Xamarin.Forms.Page page, System.Boolean animated)
NavigationPageRenderer.PopToRootAsync (Xamarin.Forms.Page page, System.Boolean animated)
NavigationPageRenderer.OnPoppedToRoot (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e)
NavigationPage.PopToRootAsyncInner (System.Boolean animated)
NavigationPage.PopToRootAsync (System.Boolean animated)`

**Comment by carbonete** [comment]
I have same issue with 5.0.0.1931  .

This still in To Do ?
