### ISSUE TITLE
DatePicker's HorizontalTextAlignment

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3530]
Hi,

Please add a HorizontalTextAlignment property to Xamarin Forms DatePicker.

Thanks,
Jassim

**Comment by Soundman32** [comment]
Is this something that can already be done with `HorizontalOptions` ?

**Comment by jrahma** [comment]
it's different

**Comment by Soundman32** [comment]
How is it different?  What is it that you are trying to do?

**Comment by jrahma** [comment]
Center Text is different than Center the Contro. I want to center the Text within the control not center the control, within the page

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
