### ISSUE TITLE
Frame change appearance in Xamarin.Forms 3.1.0

### ISSUE THREAD

**Issue by viniciusmaia** [xamarin/Xamarin.Forms#3532]
I used to use the Frame control of Xamarin.Forms as a CardView for Android, but I updated the Xamarin.Forms package to version 3.1.0 and the frame appearence has changed. It doesn't have elevation and shadows. I tried to create a custom renderer, but doesn't work.

To explain what I'm trying to say, see the pictures below. First picture is the old behaviour of frame. The appearence is exactly like CardView in Android and the second picture is the new behaviour, for the version 3.1.0 of Xamarin.Forms. The frame doesn't have elevation and shadows.

That's the old appearence

![cardview_velho](https://user-images.githubusercontent.com/5260850/43920569-aee48396-9bef-11e8-90ed-c626a314c75a.png)

That's the new appearence in xamarin.forms 3.1.0

![cardview_novo](https://user-images.githubusercontent.com/5260850/43920612-cb7d4a38-9bef-11e8-9e76-8ee4b91a22db.png)

**Comment by lewcianci** [comment]
I don't see this in my XF 3.1 app.  Are you sure you don't have a custom renderer overriding the way the frame is displayed?

**Comment by viniciusmaia** [comment]
Actually, I use a control that extends frame. I named it CardView, but, for Android platform, it changes nothing. My CardView class have differences only for iOS and I tested modifying the CardView for a simple frame and the result was the same.

```
 public class CardView : Frame
    {
        public CardView()
        {
            Padding = 0;

            if (Device.RuntimePlatform == Device.iOS)
            {
                HasShadow = false;
                BorderColor = Color.Transparent;
                BackgroundColor = Color.Transparent;
            }
        }
    }
```

**Comment by samhouts** [comment]
Frame appears to render identically for me in 3.0.0 and 3.1.0. Can you please test the attached project and alter it such that it exhibits the issue? Thank you!
[Issue3532.zip](https://github.com/xamarin/Xamarin.Forms/files/2279756/Issue3532.zip)

3.0.0
![screenshot_20180810-194641](https://user-images.githubusercontent.com/7827070/43985881-ec75be02-9cbf-11e8-8242-1cd0a982acaa.jpg)

3.1.0
![screenshot_20180810-194947](https://user-images.githubusercontent.com/7827070/43985883-f1c87d22-9cbf-11e8-888a-36f86a0f4655.jpg)

**Comment by viniciusmaia** [comment]
I created a simple "Hello Xamarin Forms!" project and the problem continues.

I posted the project on GitHub. There is the link.

https://github.com/viniciusmaia/XamarinForms.FrameIssue

**Comment by viniciusmaia** [comment]
I did many tests here with different versions of Xamarin Forms package. With versions >= 3.0.0, the behaviour was random. Sometimes, Frame appearence was like CardView in android, but sometimes was like I posted. After, I tested with version 2.5.1 and works like a charm

**Comment by viniciusmaia** [comment]
I tested in Android 6.0 (Marshmallow) and in 5.1 (Lollipop)

**Comment by samhouts** [comment]
Are you using an emulator or device? Which one?

**Comment by viniciusmaia** [comment]
I tested in a device with Android 6.0 and in emulator with Android 5.1.

**Comment by hartez** [comment]
On a device with Android 7.1 (API 15), the frame in the repro project looks fine. When I run it on an emulator with API 21, I'm seeing the flattened version:

![screenshot_1535165546](https://user-images.githubusercontent.com/538025/44614339-e79a6100-a7df-11e8-928c-82488e73b244.png)

**Comment by hartez** [comment]
My results were with XF 3.1.

**Comment by rajvision10** [comment]
It's still there in same sample project with Forms 4.7. There is no way as of now to add shadow. Can any one please make this issue as high priority ? Two year old bug and still exists with latest forms version.

**Comment by jfversluis** [comment]
Waaaay old issue. I hope this is resolved by now. If there is still something you think that is wrong, please open a new issue. Thanks!
