### ISSUE TITLE
Extend Thickness with Uniformity Checking Functions

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Xamarin.Forms#3534]
### Description
Add the Methods IsUniform, IsHorizonallyUniform and IsVerticallyUniform to the Thickness struct. They are self-explanatory. The methods could be used in #1695 but also other Thickness related code to fast path if the Thickness is Uniform. A rounded rectangle with a uniform thickness can be drawn on Android via Path.AddRoundedRectangle. A rounded rectangle with variable border width would have to draw several different arcs with variable width, incurring some overhead. A quick reusable uniformity check could reduce duplicate code

**Comment by Mrnikbobjeff** [comment]
I would also offer to implement this if this should become desired, as I have already written the necessary methods for #1695 and put them in an internal extension method static class. Exposing this via the struct would still be desirable IMHO.

**Comment by jfversluis** [comment]
Thank you so much for this suggestion, even though years old! So sorry we never got to respond to this properly. With .NET MAUI on the horizon, we won't be adding this to Xamarin.Forms anymore. If this still interests you, please check how we do this in .NET MAUI and if you still see room for improvement, let us know.

Thanks!
