### ISSUE TITLE
Compiled bindings producing invalid IL code

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3539]
### Description

The `CompiledColorSelectorPage` in the attached sample throws an `InvalidProgramException` when using compiled bindings between a page and a view model. The problem seems to be the `Slider` bindings. When they are commented out there's no problem.

Note 1: The attached sample uses the 3.2-pre2 NuGet that has been distributed internally, so requires the package to be hosted a local NuGet feed.

Note 2: The `CompiledColorSelectorPage` is identical to the `BetterColorSelectorPage`, but uses compiled bindings. The point being there are no problems with the code when using normal bindings.

### Steps to Reproduce

1. Run the attached sample and browse to the "Compiled color selector" page (bottom of the ListView).

### Expected Behavior

A color selector that uses compiled bindings appears.

### Actual Behavior

InvalidProgramException: Invalid IL code in DataBindingDemos.CompiledColorSelectorPage

### Basic Information

- Version with issue: 3.2.0.729350-pre2
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  Not tried.
- Android Support Library Version: 27.0.2

### Reproduction Link

[DataBindingDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/2277543/DataBindingDemos.zip)

**Comment by StephaneDelcroix** [comment]
thanks, I'm able to repro that in a unit test
