### ISSUE TITLE
Implement TabLayout.IOnTabSelectedListener for Bottom Tabbed Bar Android 

### ISSUE THREAD

**Issue by chentotal** [xamarin/Xamarin.Forms#3540]
### Description
I tried to implement TabLayout.IOnTabSelectedListener in TabbedPageRenderer.
If SetToolbarPlacement on Bottom, the events wouldn't be triggered.
But if SetToolbarPlacement on Top, the events would be triggered.
For example, TabLayout.IOnTabSelectedListener.OnTabReselected wouldn't be called if bar is on Bottom.

**Comment by ThomasLebrun** [comment]
I can confirm that I have the exact problem on my side. I'm in the same situation with TabLayout.IOnTabSelectedListener.OnTabReselected and it's not raised if ToolbarPlacement is set to Bottom

**Comment by PureWeen** [comment]
@chentotal  and @ThomasLebrun 

When the tablayout is on the bottom it's using a BottomNavigationView not a TabLayout so you would most likely need to use

```
BottomNavigationView.IOnNavigationItemSelectedListener
```

**Comment by chentotal** [comment]
BottomNavigationView.IOnNavigationItemReselectedListener is not implement.
I already report a issue.
[https://github.com/xamarin/Xamarin.Forms/issues/3549](url)
