### ISSUE TITLE
Ability to Set Minimum Height and Width to a View.

### ISSUE THREAD

**Issue by jashif** [xamarin/Xamarin.Forms#3545]
Hi 

It would be very helpfull to have the ability to set mininum height and width to a view or control in xamarin forms , Eventhough there is a property called MinimumHeightRequest it doesnt work at all.

**Comment by samhouts** [comment]
Please follow https://github.com/xamarin/Xamarin.Forms/issues/2536 for updates. You can also see https://github.com/xamarin/Xamarin.Forms/issues/2887 for context. Thanks!
