### ISSUE TITLE
Add DisplayText and Value to the ActionSheet

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3546]
Hi,

In the ActionSheet, currently we van only add text and select based on the text but the text might change in the database as we rely on the id not the text so it will be great if you allow to attach a value to the actionsheet then we can do selection based on the value not the text.

Thanks,
Jassim

**Comment by ProcuraIsaac** [comment]
This would be fantastic.  Or if there's another way to get the same functionality, let us know.

**Comment by jfversluis** [comment]
Not sure what this means, also not going to be implemented in Forms anymore. Thanks!
