### ISSUE TITLE
Xamarin.Forms Secondary ToolbarItem Icon not showing

### ISSUE THREAD

**Issue by allenliu1030** [xamarin/Xamarin.Forms#3550]
### Description
This is Allen from APGC Xamarin support team. Currently my customer is trying to achieve the secondary toolbar item as below effect which supported by native Android:

![image](https://user-images.githubusercontent.com/36911474/44017592-73d707d2-9f0b-11e8-9615-9f2d8a192e04.png)

You can target to the forum link, almost the same code:

https://forums.xamarin.com/discussion/47989/icon-for-toolbaritem-with-order-secondary 

```XML
     <ToolbarItem Icon="icon1.png"></ToolbarItem>
    <ToolbarItem Icon="icon2.png"></ToolbarItem>
    <ToolbarItem Icon="icon3.png" Order="Secondary" Text="Task3"></ToolbarItem>
    <ToolbarItem Icon="icon4.png" Order="Secondary" Text="Task4"></ToolbarItem>
```

Also, if this is a by-design behavior but customer wants this feature, what is the best practice to achieve this for customer?

### Steps to Reproduce

1. Create a new Xamarin.Forms project.
2. Implement the above UI code into the MainPage.xaml file.
3. Run with Android platform.

### Expected Behavior

![image](https://user-images.githubusercontent.com/36911474/44017592-73d707d2-9f0b-11e8-9615-9f2d8a192e04.png)

### Actual Behavior

Only text will be shown there. No icons.

**Comment by samhouts** [comment]
#1873 got us partway there, but we still don't expose the toolbar or the menu items, and we don't add an icon to secondary toolbar items. I am not sure what the limitation was that prevented us from setting the icon on secondary toolbar items (maybe @jassmith has more context), but we can take a look to see if this is possible. Thank you!

**Comment by allenliu1030** [comment]
Thanks for the reply. Actually Jason asked me to check with you though.

If this is not currently a feature with XF, is there any workaround that we might be able to achieve as a workaround here?

Thanks!

**Comment by samhouts** [comment]
I think we hide too much in the renderer to let you do it with the current codebase. https://forums.xamarin.com/discussion/comment/145957/#Comment_145957 has an interesting solution, if that works for now. I'll check with the team to see if anyone else has idea.s

**Comment by ChaseFlorell** [comment]
just reviving this one. I've run into it after implementing #7557 in a sandbox.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. 

I see someone already opened an issue, so might be good to express your interest there!

Thanks!
