### ISSUE TITLE
[Android] Implementation of BottomNavigationView.IOnNavigationItemReselectedListener for Bottom Tabbed Bar

### ISSUE THREAD

**Issue by ThomasLebrun** [xamarin/Xamarin.Forms#3552]
### Summary ###
Implement a Reselected property for TabbedPage when a user reclicks on a tab

### API Changes ###

```C#
public object ReSelectedItem //Bindable Property
```

### Android implementation notes and existing work
https://github.com/xamarin/Xamarin.Forms/pull/3553

In order to allow developers to know when an user click on the same tab. We simply implement IOnNavigationItemReselectedListener on the TabbedPageRenderer:

`public class TabbedPageRenderer : BottomNavigationView.IOnNavigationItemReselectedListener`

We introduce a new method that is raised when a selected tab is clicked again:
`OnNavigationItemReselected`

### Intended Use Case ###
It will help developers to know that a selected tab has been ReSelected

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
