### ISSUE TITLE
Xamarin forms Latest updates issue # Boolean converter issue

### ISSUE THREAD

**Issue by vyasaraj999** [xamarin/Xamarin.Forms#3554]
Updated Xamarin forms to 3.1  then I am facing the new issue with the forms loading from xaml in both Android and IOS.

Here is the stack trace

VisualElement+VisibilityConverter.ConvertFromInvariantString (System.String value)
D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs - line 936

System.InvalidOperationException: Cannot convert " false" into System.Boolean

1
VisualElement+VisibilityConverter.ConvertFromInvariantString (System.String value) D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:936
2
TypeConversionExtensions.ConvertTo (System.Object value, System.Type toType, System.Func`1[TResult] getConverter, System.IServiceProvider serviceProvider) D:\a\1\s\Xamarin.Forms.Core\Xaml\TypeConversionExtensions.cs:118
3
TypeConversionExtensions.ConvertTo (System.Object value, System.Type toType, System.Func`1[TResult] minfoRetriever, System.IServiceProvider serviceProvider) D:\a\1\s\Xamarin.Forms.Core\Xaml\TypeConversionExtensions.cs:76
4
ApplyPropertiesVisitor.TrySetValue (System.Object element, Xamarin.Forms.BindableProperty property, System.Boolean attached, System.Object value, System.Xml.IXmlLineInfo lineInfo, Xamarin.Forms.Xaml.Internals.XamlServiceProvider serviceProvider, System.Exception& exception) D:\a\1\s\Xamarin.Forms.Xaml\ApplyPropertiesVisitor.cs:476
5
ApplyPropertiesVisitor.SetPropertyValue (System.Object xamlelement, Xamarin.Forms.Xaml.XmlName propertyName, System.Object value, System.Object rootElement, Xamarin.Forms.Xaml.INode node, Xamarin.Forms.Xaml.HydrationContext context, System.Xml.IXmlLineInfo lineInfo) D:\a\1\s\Xamarin.Forms.Xaml\ApplyPropertiesVisitor.cs:332
6
ApplyPropertiesVisitor.Visit (Xamarin.Forms.Xaml.ValueNode node, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\ApplyPropertiesVisitor.cs:57
7
ValueNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:86
8
ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:143
9
ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:145
10
ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:145
11
ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:145
12
ElementNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:145
13
RootNode.Accept (Xamarin.Forms.Xaml.IXamlNodeVisitor visitor, Xamarin.Forms.Xaml.INode parentNode) D:\a\1\s\Xamarin.Forms.Xaml\XamlNode.cs:200
14
XamlLoader.Visit (Xamarin.Forms.Xaml.RootNode rootnode, Xamarin.Forms.Xaml.HydrationContext visitorContext) D:\a\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:143
15
XamlLoader.Load (System.Object view, System.String xaml) D:\a\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:89
16
XamlLoader.Load (System.Object view, System.Type callingType) D:\a\1\s\Xamarin.Forms.Xaml\XamlLoader.cs:67
17
Extensions.LoadFromXaml[TXaml] (TXaml view, System.Type callingType)

**Comment by StephaneDelcroix** [comment]
Please attach a small project reproducing the issue.

**Comment by kingces95** [comment]
Might just be a typo. Looks like there is a space in the string which is being deserialized:

> " false"

**Comment by kingces95** [comment]
@vyasaraj999 Please confirm this is not a typo. If not, please re-open with a reproduction.

**Comment by StephaneDelcroix** [comment]
oh, I missed the `" false"` yesterday, as I was reading this on my phone. We definitely could do better and trim.

**Comment by StephaneDelcroix** [comment]
also, it's totally possible that this was "regressed" when the `VisibilityConverter` was added as enum parsing was trimming, the the new converter is not

**Comment by vyasaraj999** [comment]
This is a not a typo issue I could not able to see any trimming issue too.

**Comment by vyasaraj999** [comment]
It is crashing in the Xamarin Forms Visual Element line-936 which is the latest update 3.1 which I cannot edit that file might be the issue in the latest xamarin forms or is there any thing I can do to add any converter file.

**Comment by vyasaraj999** [comment]
Sorry guys.... actually there was an issue in my xaml file where the visible property Isvisible=" false" is assigned like this it was resolved with removing the space.

Thanks a lot guys...

**Comment by StephaneDelcroix** [comment]
As I said, this is an actual regression
