### ISSUE TITLE
[Enhancement] Editor: Control over text-prediction 

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3555]
## Rationale

#1677 for Editor

`Editor`s do not currently allow users to disable text prediction/autocomplete/autosuggest without a custom renderer or effect.

## Implementation

Add bindable property to `Editor`:

```csharp
public static readonly BindableProperty IsTextPredictionEnabledProperty = BindableProperty.Create("IsTextPredictionEnabled", typeof(bool), typeof(Editor), true);

```

Renderers will need to be updated accordingly.

### Android

- `IsTextPredictionEnabled == true`: Default. Text prediction is enabled.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

### iOS

- `IsTextPredictionEnabled == true`: Default. Text prediction is enabled. Note: may also disable autocorrect.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

### UWP

- `IsTextPredictionEnabled == true`: Default. Text prediction  is enabled.
- `IsTextPredictionEnabled == false`: Text prediction is disabled.

## Implications for CSS

None

## Backward Compatibility

Since we are adding new properties, there should be no compatibility problems as long as:

1. We ensure that an `Editor`'s text prediction defaults to enabled, as is the expected behavior now,
2. We ensure that any Effects or Custom Renderers that may have been created to produce this behavior take precedence over any values that we set, to the best of our ability.

Third party renderers will need to be updated to ensure that this functionality is officially supported.

## Difficulty : Easy-Medium

This is an easy-medium change and great for a first-time contributor. Biggest challenge will be ensuring that disabling text prediction does not also disable other features of the `Editor` view on all platforms.

**Comment by noamyogev84** [comment]
Hi @samhouts I'd like to tackle this one.
Any suggestions/code pointers? I'll start by reviewing #1677

**Comment by noamyogev84** [comment]
Hi @samhouts. 
Please let me know if anything's missing. I've tested the new behavior both with the UWP Gallery Project, and with Android Emulator. seems OK.

I'll be happy to do any modifications if needed.

**Comment by jcmanke** [comment]
Wouldn't it be better to add this property to `Entry` and `Editor`'s base class `InputView` than to have it duplicated?

**Comment by suhailsinghbains** [comment]
I'll wait you guys are sure what specific changes I have to do :)
