### ISSUE TITLE
DatePicker fails when binding to both minimum and maximum dates

### ISSUE THREAD

**Issue by JesseLiberty** [xamarin/Xamarin.Forms#3556]
### Description
DatePicker control works fine when binding to minimum or maximum but when you bind to both it throws an exception.

### Steps to Reproduce

1. Create a datepicker
2. Bind MinimumDate to a datetime
3. Bind Maximum Date to a datetime

### Expected Behavior
Minimum and Maximum dates are reflected in use of datepicker
### Actual Behavior
Exception is thrown
### Basic Information

- Version with issue:
3.1.0.697729
- Last known good version:
- IDE:  Visual Studio 2017 (Windows)
- Platform Target Frameworks: 
  - iOS:  
  - Android:   8.1
  - UWP:   
- Android Support Library Version:   27.0.2.1 (?)
- Nuget Packages:
- Affected Devices:
Galaxy S5 (and emulators)

**Comment by StephaneDelcroix** [comment]
make sure Min and Max dates are set in the right order, to avoid validation failure (i.e., at any moment, Min should be < Max)

**Comment by kingces95** [comment]
This works fine on 3.2.0. Please attach a reproduction if your use case is different. 
```	
var page = new ContentPage();			
var picker = new DatePicker();		
picker.MaximumDate = DateTime.Now.AddMonths(1);		
picker.MinimumDate = DateTime.Now;		
page.Content = picker;		
MainPage = page;
```

**Comment by JesseLiberty** [comment]
The problem comes if you don't set the minimum and maximum dates initially (e.g., when using a backing variable).  Then the dates default to min date and it crashes.  The trick is to make sure you initialize the dates in the picker when you create it

**Comment by rodrigojuarez** [comment]
I have a binding to minimumdate / maximumdate and date, when the minimum date changes, the date takes the same value
The current date is already between min / max before change to min
If I remove the mininumdate binding, everything works fine
