### ISSUE TITLE
(WPF) Label displays only one line

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#3558]
### Description
A label in a stack layout only displays its first line. It doesn't wrap.

### Steps to Reproduce
1. Create this: `<StackLayout><Label Text="Lotsa text here"/></StackLayout>`

### Expected Behavior
The text wraps and all lines of text are displayed. This is the behavior on UWP.

### Actual Behavior
Only the first line of text is displayed.

### Basic Information
- Version with issue: 3.1.0.697729

**Comment by mohachouch** [comment]
I don't unstedand this issue. I don't have the same behavior.

Can you attached an reproduction project 

![image](https://user-images.githubusercontent.com/25939826/44684760-2e8b8f00-aa4a-11e8-9ddb-73b10cb7f14a.png)

**Comment by breyed** [comment]
Run this [repro project](https://github.com/breyed/xamarin-wpf-label-wrap-repro). If you resize the window to be smaller than the text, the text doesn't wrap.

**Comment by mohachouch** [comment]
Thanks bug confirmed. It is linked to this bug: https://github.com/xamarin/Xamarin.Forms/issues/3308

PR soon :)

**Comment by mohachouch** [comment]
@PureWeen @samhouts @rmarinho  This issue is fixed by #3750

**Comment by mohachouch** [comment]
@samhouts this issue is fixed by #3750
