### ISSUE TITLE
[Android] MasterDetailPageRenderer.OnDetachedFromWindow

### ISSUE THREAD

**Issue by paleicikas** [xamarin/Xamarin.Forms#3564]
### MOST AFFECTED OS
SDK 24: 48.7%
SDK 26: 25.7%
SDK 23: 14.4%
SDK 25: 7.8%
Others: 3.4%

<pre>
Xamarin Exception Stack:
System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Platform.Android.AppCompat.MasterDetailPageRenderer.OnDetachedFromWindow () [0x0000c] in <6b73296523894c3d8d57f5a8e3480a43>:0
  at Android.Views.View.n_OnDetachedFromWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <263adecfa58f4c449f1ff56156d886fd>:0
  at (wrapper dynamic-method) System.Object.fb5072c8-2d1b-406a-af85-0cdfa02bc730(intptr,intptr)

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1556)
2   java.lang.Thread.getAllStackTraces(Thread.java:1606)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:923)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:50)
5   md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.n_onDetachedFromWindow(MasterDetailPageRenderer.java:-2)
6   md58432a647068b097f9637064b8985a5e0.MasterDetailPageRenderer.onDetachedFromWindow(MasterDetailPageRenderer.java:60)
7   android.view.View.dispatchDetachedFromWindow(View.java:17611)
8   android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3729)
9   android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
10  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
11  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
12  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
13  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
14  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
15  android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
16  android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3704)
17  android.view.ViewRootImpl.doDie(ViewRootImpl.java:6787)
18  android.view.ViewRootImpl.die(ViewRootImpl.java:6757)
19  android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:493)
20  android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:424)
21  android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
22  android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5087)
23  android.app.ActivityThread.-wrap6
24  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
25  android.os.Handler.dispatchMessage(Handler.java:108)
26  android.os.Looper.loop(Looper.java:166)
27  android.app.ActivityThread.main(ActivityThread.java:7425)
28  java.lang.reflect.Method.invoke(Method.java:-2)
29  com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
30  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Thread 900:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:784)

Thread 901:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:235)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:784)

Thread 902:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:386)
2   java.lang.Thread.sleep(Thread.java:327)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:345)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:371)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:284)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:784)

Thread 923:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 925:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 927:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 939:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 940:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 942:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 945:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   Mz.run
10  java.lang.Thread.run(Thread.java:784)

Thread 954:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   Mz.run
10  java.lang.Thread.run(Thread.java:784)

Thread 956:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:101)
2   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
3   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
4   java.lang.Thread.run(Thread.java:784)

Thread 957:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
2   com.android.okhttp.okio.AsyncTimeout.-wrap0
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 1010:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2059)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:784)

Thread 1121:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:784)

Thread 1142:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:784)

Thread 1144:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:784)

Thread 1146:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
9   java.lang.Thread.run(Thread.java:784)

Thread 1177:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1168)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1147)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:784)
</pre>

---

No code to reproduce
Latest XF

**Comment by kingces95** [comment]
Team is undecided on whether to revert PR until we have a reproduction or submit fix as it's likely to unblock customer. So if you could provide a repro, that would certainly expedite the fix as well as allow us to ensure it's the right fix.
