### ISSUE TITLE
[GTK] WebView not working

### ISSUE THREAD

**Issue by usr4711** [xamarin/Xamarin.Forms#3571]
### Description
The WebView on GTK isn't displayed.

### Steps to Reproduce

1. Install debian stretch and monodevelop
2. Create a .NET standard project for the shared components, that contains a MainPage with a WebView
3. Because libwebkit-dev isn't available anymore, as suggested on https://github.com/jsuarezruiz/forms-gtk-progress/blob/master/Faq.md, install libwebkitgtk-dev
4. Create a GTK project, that references and initializes the shared project

### Expected Behavior
The URL in the WebView should be visible. It's working on Windows.

### Actual Behavior
Gray area/ now WebView is rendered.

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: -
- IDE: MonoDevelop

**Comment by Simon-Thompson** [comment]
Any update on this? I'm experiencing the same issue. Only error thrown by the app is:
```Gtk-CRITICAL **: 16:12:14.372: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed```

Works fine on Windows, but fails on Linux. Version of Xamarin.Forms is 4.0.30319, testing platform is Ubuntu 18.04

**Comment by chris208** [comment]
Any update on this? I got same issue. 
This is the error message: Gtk-CRITICAL **: 09:09:10.922: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

**Comment by Simon-Thompson** [comment]
@chris208, haven't heard from the Xamarin folks about this since posting last year =[
I think @jsuarezruiz was working on this branch, but hasn't updated the project in a while.

**Comment by martinstoeckli** [comment]
> 
> 
> Any update on this? I got same issue.
> This is the error message: Gtk-CRITICAL **: 09:09:10.922: IA__gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed

@chris208 - This error I get when compiling on Windows and running on Linux. If the code is compiled on Linux with MonoDevelop there is no such error message, but the WebView isn't shown anyway. The WebView is visible only on the Windows platform, other controls are shown on both Windows and Linux.

**Comment by thongnm** [comment]
@martinstoeckli Did you have a solution for this issue? I am struggling with it on Mac OS too. Actually, I was creating an extension for Visual Studio For Mac. It only contains a simple dialog with a Webview control. However, the Webview control is failed to render. Other controls (label, button, etc) work fine.

**Comment by martinstoeckli** [comment]
@thongnm - I didn't try since, waiting for DotNet5 to come out before I make another attempt.

**Comment by jasells** [comment]
Has there been any progress on this issue?  I am looking to host a WebGL page in a XForms app on Linux...  This doesn't even seem to be an option on GTK# for Windows, since the browser engine is I.E. at least when the GTK-app is .Net Framework 4.8.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
