### ISSUE TITLE
[iOS] PopToRootAsync capture exception Xamarin_Forms_Platform_iOS_NavigationRenderer_ParentingViewController

### ISSUE THREAD

**Issue by LeeCenY** [xamarin/Xamarin.Forms#3580]
### Steps to Reproduce

1. 
```
try {
    await NavigationPage.Navigation.PopToRootAsync();
} catch (Exception e){
    System.Diagnostics.Debug.WriteLine(e.Message); 
}
```
2. 
Unbalanced calls to begin/end appearance transitions for <Xamarin_Forms_Platform_iOS_NavigationRenderer_ParentingViewController: 0x7fb64b436780>.

3.  
When you don't use try catch, it doesn't crash, just enter await NavigationPage.Navigation.PopToRootAsync(); no changes on the UI

### Expected Behavior
Jump page
### Actual Behavior
no changes on the UI
iOS has such a problem, Android is no problem
### Basic Information

- Version with issue: 2.5.1.444934
- Last known good version:
- IDE: Visual Studio Community 2017 for Mac Version 7.5.4 (build 3)
- Platform Target Frameworks: 
  - iOS:   iOS 11
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:  4.3.1.4445
- Affected Devices: iOS

**Comment by kingces95** [comment]
@LeeCenY Please attach a reproduction. Thanks!

**Comment by LeeCenY** [comment]
@kingces95 Google Translate: Sorry! It's hard to reproduce Dome, not all PopToRootAsync, I want to know: Xamarin_Forms_Platform_iOS_NavigationRenderer_ParentingViewController exception is generally a problem

**Comment by PureWeen** [comment]
@LeeCenY  
-is that await inside a method that's marked as async void? That might be why you are seeing different behavior
-it sounds like you're triggering multiple navigations or triggering the pop during some life cycle event
-also you are on a fairly old version of XF. Can you update to the latest and see if you still have issues?

For a repro I would recommend emulating your navigation structure to see if you can recreate. My guess is that there is some odd loop or timing happening where you are firing that pop.

**Comment by LeeCenY** [comment]
Thank! i have solved.

**Comment by AlexanderMelchers** [comment]
@LeeCenY, I've just run into the same exception message with the last two versions of XF. Do you remember what you did to solve the issue, back in 2018?

**Comment by LeeCenY** [comment]
> @LeeCenY, I've just run into the same exception message with the last two versions of XF. Do you remember what you did to solve the issue, back in 2018?

I'm sorry, I've forgotten and now our company has switched back to native development

**Comment by AlexanderMelchers** [comment]
Pity! But thanks for the quick reply, @LeeCenY!
