### ISSUE TITLE
Two keyboards appear when editing the TextColumn after the NumericColumn

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#3582]
### Description

Hi Team,

We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin

We would like to bring to your notice a bug that we encountered recently when editing the first column (Numeric column) alphanumeric Keyboard appears which is fine, after that while editing second column (Text Column), same alpha numeric keyboard appears first, next text keyboard comes to the view which is issue. 

Issue was reproduced only on Samsung Android device with Android version 6 Marshmallow , API - 23. only on Samsung keyboard 

Issue was ensured with Xamarin forms version 2.4.0.280 and latest stable version of 3.1.0.697729 too.

### Steps to Reproduce

1. Run the attached sample
2. Enters in to edit mode by double tabbing
3. Edit any cell in the first column (Numeric column)
4. Then tab any where to collapse the keyboard
5.  Now edit the second column (Text column)
6. Able to see first "**Alphanumeric keyboard**" comes to the view after that "**Text keyboard**" appears, which is mentioned issue

### Expected Behavior
Only Text keyboard should appear while edit the Text column after editing of Numeric column
### Actual Behavior
After editing Numeric column if editing happens for Text column, first Alphanumeric keyboard comes to the view then Text keyboard appears.
### Basic Information

- Version with issue: 2.4.0.280
- Last known good version:  3.1.0.697729
- IDE:
- Platform Target Frameworks: 
  - Android: 6 Marshmallow API 23
- Nuget Packages: 3.1.0.697729
- Affected Devices:  6 Marshmallow API 23 version devices

### VideoLink

[TwoKeyboardVideo.zip](https://github.com/xamarin/Xamarin.Forms/files/2293076/TwoKeyboardVideo.zip)

### Reproduction Sample Link
[BugReport.zip](https://github.com/xamarin/Xamarin.Forms/files/2293254/BugReport.zip)

### Note: In case if SfDatagrid packages are not restored in the sample, you can download the package Syncfusion.Xamarin.SfDataGrid from nuget.org.

**Comment by kingces95** [comment]
Seems to be working on 3.2.0 API 23. 

![88439e8d-1151-49ec-a3b8-68f32bf6313d](https://user-images.githubusercontent.com/4120386/44241993-f9865f00-a162-11e8-8f59-0e81c2b7d46a.GIF)

Note that after upgrading nuget package I had to manually edit the shared project file to remove old packages.

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @kingces95,
 
Thanks for the update, but am afraid your validation of the issue is still wrong. 
 
We had clearly mentioned that the issue was reproducible only in a Samsung device when input type was set as SamsungKeyboard in Android Version 6.0 Marshamallow.
 
The issue will not be reproduced in the same Samsung device running 6.0 Marshamallow if the input type is set as Google Keyboard.
 
So am afraid i may have to reopen this again for further investigation from your side.
