### ISSUE TITLE
Span does not have bindable property 'GestureRecognizers'

### ISSUE THREAD

**Issue by eddie010** [xamarin/Xamarin.Forms#3586]
### Description
The Span Type does not have a GestureRecognizers property to define a TapGestureRecognizer with. 

### Steps to Reproduce

1. Open a xaml file
2. Add a Label
3. Add Label.FormattedText to the Label
4. Add FormattedString to the Label.FormattedText property
5. Add Span to the FormattedString
6. Try to Add Span.GestureRecognizers to the span

### Expected Behavior
I expected to be able to define a TapGestureRecognizer for a single Span and Bind a Command to it.

### Actual Behavior
An error will show saying Span doesn't have a GestureRecognizers property

### Basic Information

- Version with issue: Xamarin.Forms v3.1.0.697729
- Last known good version: 3.1.0 (feature was merged to master om May 9th)
- IDE: Visual Studio 2017 Enterprise (Version 15.8.0)

### Merge showing it should be supported

https://github.com/xamarin/Xamarin.Forms/pull/1850
According to the above URL the feature should have already been implemented.

**Comment by samhouts** [comment]
The feature was split. Gesture Recognizers made it into 3.2.0. https://github.com/xamarin/Xamarin.Forms/pull/2173. Thanks!
