### ISSUE TITLE
[iOS] Manifest file editor does not properly check/uncheck device interface orientations

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#3593]
### Description

The editor and the Info.plist file show different things. Please see reproduction steps.

### Steps to Reproduce

1. Create a new project using VS2017 15.7.6
2. Right click iOS project and go to Properties -> iOS Manifest -> Click link to open the manifest editor
3. Uncheck Landscape Left (or Landscape Right)
4. Click Save All (Cntrl + Shift + S)
5. Observe that Info.plist file removes UIInterfaceOrientationLandscapeLeft (or right) but adds UIInterfaceOrientationPortraitUpsideDown (why?)

1. Create a new project using VS2017 15.7.6
2. Right click iOS project and go to Properties -> iOS Manifest -> Click link to open the manifest editor
3. Uncheck Landscape Left AND Landscape Right at the same time
4. Click Save All (Cntrl + Shift + S)
5. Observe that Info.plist file removes UIInterfaceOrientationLandscapeRight but adds UIInterfaceOrientationPortraitUpsideDown (why?) and does not remove UIInterfaceOrientationLandscapeLeft

**Comment by kingces95** [comment]
Needs to be moved to VS issues. However that's done... @samhouts?

**Comment by adrianknight89** [comment]
@kingces95 Do you mean another repository? I have one more XF VS issue to submit. Let me know where it goes.

**Comment by adrianknight89** [comment]
I also submitted this on the VS Developer Community: https://developercommunity.visualstudio.com/content/problem/318816/xfios-manifest-file-editor-does-not-properly-check.html
