### ISSUE TITLE
Xamarin iOS does not deploy to device

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3595]
Hi,

The latest VS for Mac and Xamarin iOS will not deploy to device.

Here is a bug posted long time back with no solution yet.

[https://developercommunity.visualstudio.com/content/problem/249249/latest-visual-studio-update-wont-deploy-to-device.html?childToView=313081#comment-313081
](https://developercommunity.visualstudio.com/content/problem/249249/latest-visual-studio-update-wont-deploy-to-device.html?childToView=313081#comment-313081
)

**Comment by kingces95** [comment]
Please re-post this issue at https://github.com/xamarin/xamarin-macios. 

Thanks!
