### ISSUE TITLE
Binding and GestureRecognizers not working inside TitleView on a NavigationPage

### ISSUE THREAD

**Issue by AArayeshi** [xamarin/Xamarin.Forms#3596]
### Description
Binding elements of  TitleView on a NavigationPage not retrieving data from view model and also GestureRecognizers not fires by clicking on TitleView elements.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the items detail pages by selecting one item from list in main page.
3. Start editing on entry box with "Edit me" placeholder that not changes TitleView sub title.
4. Also by clicking TitleView inside toolbar nothing happens. 

### Expected Behavior
By editing text entry TitleView subtitle must be changed to editing text inside text entry.
By clicking on TitleView subtitle must be changed to "Command done".

### Actual Behavior
Nothing happens.

### Basic Information

- Version with issue: v3.2.0.637442-pre1 and  v3.2.0.729530-pre2
- Last known good version:
- IDE: VS2017 15.7.5
- Platform Target Frameworks: 
  - iOS:  
  - Android:  8.1
  - UWP:   

### Reproduction Link
[TitleViewBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/2296115/TitleViewBinding.zip)

**Comment by xamarindevelopervietnam** [comment]
thank you @AArayeshi

**Comment by kingces95** [comment]
As described. Use iOS project as Android project fails to build on windows due to path length exception.

**Comment by AArayeshi** [comment]
It looks like nobody working on this bug.

**Comment by samhouts** [comment]
closed by #3823

**Comment by haxton2694** [comment]
3.3.0.840541-pre1 does not include this fix - will there be a pre-release with this implemented in the near future?

**Comment by AArayeshi** [comment]
It looks like working in stable 3.2.0.871581. Thanks.
