### ISSUE TITLE
Adding x:DataType to a ContentPage breaks nested other types

### ISSUE THREAD

**Issue by MichaelRumpler** [xamarin/Xamarin.Forms#3598]
### Description

If you add `x:DataType` to the topmost element in a xaml file, then any references to other objects cannot be found although they are very obvious. I added two examples to the repro project.

1. In a `ListView`:

~~~~ xaml
	<ContentPage ...  x:DataType="local:ViewModel">
		<ListView ItemsSource="{Binding Items}">
			<ListView.ItemTemplate>
				<DataTemplate>
					<ViewCell>
						<StackLayout Orientation="Horizontal">
							<Label Text="{Binding Text1}" />
							<Label Text="{Binding Text2}" />
						</StackLayout>
					</ViewCell>
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</ContentPage>
~~~~

This doesn't compile, because it can't find `Text1` and `Text2` in the type `ViewModel`. You have to specify another `x:DataType="local:SomeObject"` for the `DataTemplate` (`ViewModel.Items` is a `SomeObject[]`).
When the `ListView` is bound to a `List<T>`, then its items have DataType `T`. It shouldn't be needed to specify it again.

2. Binding to another element in the view.

~~~~ xaml
	<ContentPage ...  x:DataType="local:ViewModel">
		<StackLayout>
			<Picker Title="Picker" x:Name="thePicker" ItemsSource="{Binding Strings}" />
			<Label Text="{Binding Source={x:Reference thePicker}, Path=SelectedItem}"/>
		</StackLayout>
	</ContentPage>
~~~~

This also doesn't compile because the property `SelectedItem` cannot be found in `ViewModel`. You have to add `x:DataType="Picker"` to the `Label`.

It could be argued if this is a bug or an enhancement, but I rather see it as bug. But the workaround is very easy, so it's not top priority.

### Expected Behavior

I would expect those data types to be inferred by the rest of the xaml.

### Actual Behavior

`x:DataType` must be specified every time, when the bound object changes.

### Basic Information

- Version with issue: tested with XF 3.0.0.561731 and 3.2.0.729530-pre2
- IDE: VS 2017 15.8

### Reproduction Link

The attached project doesn't compile. Both samples are demonstrated in MainPage.xaml. The lines which make it work are commented out.
[Repro.CompiledBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/2297533/Repro.CompiledBinding.zip)

**Comment by GalaxiaGuy** [comment]
One further issue for point 2: Just specifying the `x:DataType` doesn't help if you have different properties on the same element bound to different sources.

**Comment by StephaneDelcroix** [comment]
Part 2 is fixed. Binding with Source are no longer compiled

**Comment by akamud** [comment]
I'm having this same issue, I created a simple repro here: https://github.com/akamud/DataTypeIssue.

You can see Intellisense correctly reports the data binding:
![image](https://user-images.githubusercontent.com/954102/106475236-7b2dec80-6484-11eb-8012-50abea347e81.png)

But if I try to compile it, it shows the wrong data type, using the data type from the content page:
![image](https://user-images.githubusercontent.com/954102/106475311-900a8000-6484-11eb-8b72-4ce5e11f38ea.png)

**Comment by ajtruckle** [comment]
It is not clear to me. Do I change to using this DataType for my ContentPage, knowing it will break all my bindings, or leave it as it is?

**Comment by ajtruckle** [comment]
This helped:

https://devblogs.microsoft.com/xamarin/compiled-bindings-xamarin-forms/

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
