### ISSUE TITLE
Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3599]
Hi,

Ia m trying to create the iOS archive in order to publish my app but getting:

Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved. These reference conflicts are listed in the build log when log verbosity is set to detailed.

I tried to remove the Microsoft CSharp and install it again from both the main project as well as the iOS project but same problem

It was reported as buy on:

[https://bugzilla.xamarin.com/show_bug.cgi?id=59600](https://bugzilla.xamarin.com/show_bug.cgi?id=59600)

Kindly help...

Thanks,
Jassim

**Comment by kingces95** [comment]
Please re-open this bug against https://github.com/xamarin/xamarin-android. 

Thanks!
Chris
