### ISSUE TITLE
Image CornerRadius Property

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3600]
Hi,

Please add CornerRadius property to the Image instead of adding the image inside a Frame and set the Frame's CornerRadius value.

Thanks,
Jassim

**Comment by VladislavAntonyuk** [comment]
You can use CircleImage nuget package

**Comment by AndreiMisiukevich** [comment]
I think, it is much more better to add this property to VisualElement (or View).

**Comment by adrianknight89** [comment]
I too would like to see this property for all visuals if possible. For now, @jrahma could use FFImageLoading and apply a RoundedTransformation to avoid using a frame which doesn't seem to work on iOS with images.

**Comment by samhouts** [comment]
Duplicate of #1754
