### ISSUE TITLE
[Android] Unable to activate instance of type Xamarin.Forms.Platform.Android.ListViewAdapter when using nested ListViews and DataTemplateSelector

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3603]
### Description

ListView
-DatatemplateSelector
--Listview

When swapping out the ItemSource on the parent ListView you'll get an exception of
*Unable to activate instance of type Xamarin.Forms.Platform.Android.ListViewAdapter*

https://github.com/xamarin/Xamarin.Forms/blob/4d5a1f5482eeb43661d0ac972262e09c53e61117/Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs#L153

### Steps to Reproduce
1. Run Control Gallery for Issue3408
2. Click Change Source
3. Click Change Property
4. Click Change Source
5. Crash

### Expected Behavior
No crash and ItemSource swaps out fine

### Actual Behavior
Crashes

### Basic Information

- Version with issue: 3,2
- Last known good version: Not sure
- IDE:
- Platform Target Frameworks: 
  - Android: 8.0

**Comment by rmarinho** [comment]
This is causing a failure when navigating back from this test too no need to change the source.
