### ISSUE TITLE
Android: TableView Height always same as Width 

### ISSUE THREAD

**Issue by sglorz** [xamarin/Xamarin.Forms#3609]
Steps to Reproduce

I created a TableView in my application. For iOS and UWP, everything is fine. For Android, the Height of the TableView is not properly calulated as it is always equal to its Width.
Version Information

VS 2017
Xamarin.Forms 3.1.0.697729

**Comment by hartez** [comment]
@sglorz Can you post a reproduction project? Or at least the layout (XAML or code) that you're using when you see this behavior?

Thanks.

**Comment by sglorz** [comment]
I've found a strange behavior in TableModel.OnSizeRequest

Size is calculated using  Device.Info.ScaledScreenSize and in Android Device.Info.ScaledScreenSize.Width is equal to Device.Info.ScaledScreenSize.Height

This may help you to investigate.

**Comment by hartez** [comment]
@sglorz Yep, ScaledScreenSize definitely looks suspicious on Android. 

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Forms.cs#L285
