### ISSUE TITLE
[MacOs]Slider inside StackLayout Horizontal Orientation

### ISSUE THREAD

**Issue by Lucasjuv** [xamarin/Xamarin.Forms#3610]
##Summary
When you put a label and a slider inside a StackLayout with Horizontal orientation in MacOs it breaks the page drawing when requesting for width. (NaN is not a valid value for width)

##API Changes

Fix the slider width setting when inside a horizontal orientated StackLayout.

##Intended Use Case
Use for a sliding option with description.

**Comment by hartez** [comment]
[_3610.zip](https://github.com/xamarin/Xamarin.Forms/files/2311961/_3610.zip)
