### ISSUE TITLE
DesizedSize at 3.2 Includes Margin which causes controls to be hidden

### ISSUE THREAD

**Issue by dbanta6** [xamarin/Xamarin.Forms#3616]
### Description
Sizing calculation changed between 3.1.0.697729 and 3.2.x-pre2.  In 3.1.x the DesiredSize did not include the Margin.  In 3.2.x the DesiredSize does include the margin.  I noticed this when using a StackLayout that contains an SKCanvasView and Label.  In 3.1 the label is visible, in 3.2 the label is not visible.  I reproduced this using the SkiaSharpFormsDemos SimpleCirclePage.

### Steps to Reproduce

1. Run the sample code against 3.1 and 3.2 Xamarin.Forms.  

### Expected Behavior
3.1 - Both the skia drawing and label and button below are visible.
### Actual Behavior
In 3.2 the label is hidden
### Basic Information

- Version with issue:3.2.0.729530-pre
- Last known good version:3.1.0.697729
- IDE:VS2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
Expected (functionality at 3.1)
![3 1xamarinforms](https://user-images.githubusercontent.com/8250307/44367893-513c0780-a48e-11e8-827f-a4691920c49a.png)
Actual (functionality at 3.2 - note missing label)
![3 2xamarinforms](https://user-images.githubusercontent.com/8250307/44367891-513c0780-a48e-11e8-8fab-5bdb3b95c39b.png)
DesiredSize Calculation at 3.1
![3 1desiredsize](https://user-images.githubusercontent.com/8250307/44367892-513c0780-a48e-11e8-8438-e344854af99a.png)
DesiredSize Calculation at 3.2 - now includes margin
![3 2desiredsize](https://user-images.githubusercontent.com/8250307/44367894-51d49e00-a48e-11e8-9bc8-d6a21d203d2e.png)

### Reproduction Link

[3.2ReproCode.txt](https://github.com/xamarin/Xamarin.Forms/files/2304018/3.2ReproCode.txt)

**Comment by hartez** [comment]
Repro is available at https://github.com/hartez/xamarin-forms-samples/tree/xf-3616

That branch has the demo code and is currently set at 3.1 (working); update to 3.2.0.729530-pre2 and the label disappears.

**Comment by PureWeen** [comment]
@dbanta6  This looks to be fixed by this PR
https://github.com/xamarin/Xamarin.Forms/pull/3570

I've attached the nuget created from that PR if you want to test. 
I tested locally and the text looks to show up now.

[win.zip](https://github.com/xamarin/Xamarin.Forms/files/2311761/win.zip

**Comment by dbanta6** [comment]
Thanks!  I'll take a look at it today.

**Comment by dbanta6** [comment]
That fixed it.  Thanks!

**Comment by PureWeen** [comment]
Yay! Thank you for the great report and for testing the package.
