### ISSUE TITLE
Unable to post reply on Xamarin forums(not Xamarin.Forms)

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#3621]
### Description
I have asked one question on xamarin forums & I got one reply too. But when I want to post some information in on the same thread I am getting exception on Chrome & Firefox browser. 

I am not able to continue on my thread. I was wondering where should I ask this question as xamarin forums isn't working for me. Than I realize that this place might be better.
Please solve that error as soon as possible.

### Steps to Reproduce

1.  Ask one question on xamarin forums
2.  If you get reply, try to post some on the same thread
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://forums.xamarin.com/discussion/136676/executing-services-apis-in-background-without-waiting-next-line-execution#latest

![xamforum](https://user-images.githubusercontent.com/19743421/44391537-c02c6580-a54d-11e8-9e08-f60318b7f24f.png)

**Comment by hartez** [comment]
Closing this because you appear to have been able to post a reply eventually.
