### ISSUE TITLE
Android build failed, trying to compile against Windows libraries?

### ISSUE THREAD

**Issue by taramasalata** [xamarin/Xamarin.Forms#3623]
### Description

Out of the blue I get the following build error. I have not recently added any nugets, I cannot find any reference to Windows.Foundation and I have no idea where it is trying to reference this package, or why. The Android build seems to be trying to include something from UWP. It happened after adding a line of C# (unrelated) but when I remove that line, no change.

1>------ Build started: Project: PackageName.Android, Configuration: Debug Any CPU ------
1>  PackageName.Android -> C:\Xamarin\PackageName\PackageName\PackageName.Android\bin\Debug\PackageName.Android.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1831,2): error XA2002: Can not resolve reference: `Windows.Foundation.FoundationContract`, referenced by `Windows.Foundation.UniversalApiContract`. Please add a NuGet package or assembly reference for `Windows.Foundation.FoundationContract`, or remove the reference to `Windows.Foundation.UniversalApiContract`.

This was working fine until 2am and this error just appeared. I have literally no idea what happened to trigger it. I have a very large project, I'm not sure where to look to tell anyone how to reproduce this. I simply have no idea how to debug this. It happens on debug and release. All packages are up to date.

I have tried cleaning it, including manually removing bin/obj folders, I have destroyed and remade the emulator, tried building just the android package on its own, linking SDK and user, linking none. I have scoured the code for UWP references in Android. I simply have no idea what to do to even figure out why this is happening.

Any clues AT ALL how to debug this VERY gratefully received.

**Comment by taramasalata** [comment]
now I come to think of it I accepted a Xamarin update shortly before this

**Comment by taramasalata** [comment]
This is in my Project.Android.csproj. Now to figure out why.


  <ItemGroup>
    <Reference Include="Mono.Android" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Xml" />
    <Reference Include="Windows.Foundation.UniversalApiContract">
      <HintPath>..\..\..\..\Program Files (x86)\Windows Kits\10\References\10.0.16299.0\Windows.Foundation.UniversalApiContract\5.0.0.0\Windows.Foundation.UniversalApiContract.winmd</HintPath>

**Comment by taramasalata** [comment]
I deleted that bottom reference manually, reloaded everything, and it ran. I have no idea where that came from at all.

**Comment by hartez** [comment]
Sounds like you have a solution, then. I am going to close this issue for now; if this problem persists (i.e., if that reference shows up randomly again in an Android project), please reopen this issue.

**Comment by taramasalata** [comment]
You're welcome :-)
