### ISSUE TITLE
[GTK] Enhancement: Allow toolbar to be customized.

### ISSUE THREAD

**Issue by ryebri** [xamarin/Xamarin.Forms#3625]
##Summary
The current implementation of the GTK Toolbar on the navigation pages does not allow for the toolbar to be disabled, or replaced with a custom toolbar.  An ideal solution would allow for resizing of the toolbar and adding custom elements.

##API Changes

In order to facilitate replacing the toolbar, there would need to be a method to replace the NativeToolbarTracker in NavigationPageRenderer.cs.  To facilitate changing the size of the toolbar, the GtkToolbarConstants class would need to change from an internal to public class.  The ToolbarTracker class would need to have an ability to accept new GtkToolbarConstants.  

Another option for implementation would be to allow for the toolbar to be hidden and tie into the Xamarin Forms navigation stacks with a custom toolbar written using Xamarin Forms.

ToolbarTracker.Visible {get; set;}

##Intended Use Case
Intended use case is to provide a similar application experience across mobile and Linux platforms by having a similar toolbar layout in addition to similar page layouts.  Currently there is only one type of toolbar for the Xamarin.Forms.Platform.GTK library, which makes it challenging to customize without pulling the library, customizing it, and building it.  It would enhance the use case of using Xamarin Forms for Linux via GTK.

**Comment by jfversluis** [comment]
We won't be doing this for Forms anymore, thanks for your suggestion!
