### ISSUE TITLE
ViewCellRenderer ignores the accessory (if any) when getting the width

### ISSUE THREAD

**Issue by JohnHMP** [xamarin/Xamarin.Forms#3626]
https://github.com/xamarin/Xamarin.Forms/blob/a8eab7f46a394ee6e8f9824737684937bd0c7868/Xamarin.Forms.Platform.iOS/Cells/ViewCellRenderer.cs#L117

If an accessory is set then use size.Width - 20 (for example), otherwise use size.Width

**Comment by hartez** [comment]
Forms doesn't support iOS accessories out of the box. However, you can add support for them with [customer renderer](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/). In fact, James Montemagno has [an article demonstrating how to do this](https://montemagno.com/adding-a-disclosure-indicator-accessory-to/).

**Comment by JohnHMP** [comment]
I know that and I already have a custom renderer to add an accessory. The issue is that when I do the calculation for the width is incorrect, it needs to take into consideration that the accessory is visible.
James's solution has the same problem as my renderer btw.

This is a simple fix, you can replace the line I quoted with:
    var width = Accessory == UITableViewCellAccessory.None ? size.Width : size.Width - 30;

**Comment by JohnHMP** [comment]
@hartez Any response to this?

**Comment by hartez** [comment]
> the calculation for the width it is incorrect, it needs to take into consideration that the accessory is visible.

@JohnHMP What's the consequence of not taking the accessory into account in SizeThatFits? That is, what goes wrong? I'm trying to determine what the test for this bug should look like.

**Comment by JohnHMP** [comment]
@hartez the issue is with dynamic height cells, in some situations (e.g. word wrapping text) the end of the text is lost as the height of the cell is sometimes incorrect. The text can sometimes wrap beyond the bounds of the cell, specifically when the last word of the text would normally fit on the end of the line, but with an accessory there is less space and so it wraps. The SizeThatFits thinks the available space is x, but with an accessory the available space is x -30 which would result in a correct height that would include the word wrapped text.

**Comment by JohnHMP** [comment]
@hartez is that sufficient information for you?

**Comment by JohnHMP** [comment]
@hartez is this going to be opened as an issue? Or would you like me to resubmit?

**Comment by JohnHMP** [comment]
@rmarinho thank you for taking a look. If you update one of your list view cell models to have text that will word wrap onto 3 lines (update the list view so that it support uneven rows as well of course).
Normally this would be fine, but reduce the text in the cell by 1 char at a time until the size calculation thinks the height of 2 lines of text is sufficient, when it still isn't. The label will then wrap off the bottom of the cell.
Let me know how you get on, with your test project it should be just a few minutes to see it. If it still doesn't fail for you I'll update one of the Xamarin example apps to show the issue.

**Comment by rmarinho** [comment]
I have tried but wasn't able to. I m uploading the sample project that you could do some tweaking to reproduce and help us figure it out. 

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/2411617/App2.zip)

Thanks

![simulator screen shot - iphone xs max - 2018-09-24 at 16 59 19](https://user-images.githubusercontent.com/1235097/45963500-34f63200-c01b-11e8-93e4-21bf984b55fd.png)

**Comment by JohnHMP** [comment]
@rmarinho Thank you for the demo app, I have replicated the issue for you. Modify the ImageModel.Text to:
`Title = "Test A1234567890B1234567890C1234567890D1234567890E1234567890F1234567890"`
Run this on the iPhone 8 simulator. You will see the text stops at F1234, it should word wrap to another line to complete the full F1234567890.
Removing the switch for the accessory in the cell renderer resolves the problem, the text is not cut off regardless of its length.

And to be fair, your screenshot above shows the problem too, the word forever is missing as it will be on the next line. The size has been miscalculated due to the accessories.

**Comment by JohnHMP** [comment]
@rmarinho do you now see the problem?

**Comment by rmarinho** [comment]
@JohnHMP Yap,  thanks.

**Comment by JohnHMP** [comment]
Is this going to get picked up anytime soon?
