### ISSUE TITLE
Back button on NavigationBar disappear on Android

### ISSUE THREAD

**Issue by PWaliaDev** [xamarin/Xamarin.Forms#3627]
### Description
Back button on Navigation Bar on Android gets disappear when bring application from background to foreground. To show back button application has to restart.

### Steps to Reproduce

1. Open page that have default back button on Navigation bar.
2. Put the application in background.
3. Bring application in foreground.
4. Back button no longer is visible.

### Expected Behavior
Back button should always visible.

### Actual Behavior
Back button disappear.

### Basic Information

- Version with issue: 3.1
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - Android: All versions
- Affected Devices- Android

**Comment by hartez** [comment]
@PWaliaDev I have attempted to reproduce this bug, but so far I have not been able to. With the attached project, sending the application to the background and bringing it back to the foreground does not cause the back button to disappear. Is there some detail we are missing? 

[_3627 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2310839/_3627.Repro.zip)

**Comment by PWaliaDev** [comment]
@hartez My scenario is given below.
1.On my First view i hidded NavigationBar using HasNavigationBar Api.
2.Then i navigate to second view by tapping on button and here i show NavigationBar using same Api.
3. When i press hardware back button on second view and goto first view and again i tap on hardware back button application goes into background.
3. Bring application into foreground and again navigate to second view. There no soft back button is visible on navigation bar.

Let me know if this helps.

And resolve this ASAP.

**Comment by samhouts** [comment]
@PWaliaDev Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
