### ISSUE TITLE
Android: Primary ToolbarItems do not appear disabled

### ISSUE THREAD

**Issue by adammeaney** [xamarin/Xamarin.Forms#3628]
### Description

Toolbar Items on Android do not appear disabled when they are an icon that is not in the overflow menu. There is no visual change between enabled and disabled.

### Steps to Reproduce

1. Open the Control Gallery
2. Navigate to the ToolbarItems Gallery page
3. Observe the toolbar item with the menu icon. It is disabled, but still identical to the icon not disabled.

### Expected Behavior

Icon is greyed out.

### Actual Behavior

Icon does not change.

### Basic Information

According to this [Bugzilla report](https://bugzilla.xamarin.com/show_bug.cgi?id=25661), comment 12 shows a way to make an icon disabled. 

I find this solution sub-par, as each other platform demonstrates a disabled icon without having to have a second icon and an xml drawable. One linked image works well enough, and it should on all platforms.

I have demonstrated it is simply fixed in my own code, inserting the following code in the UpdateMenuItemIcon method of the NavigationPageRenderer.

```
    if (!menuItem.IsEnabled)
    {
       iconDrawable.Mutate().SetColorFilter(AColor.Gray, PorterDuff.Mode.SrcIn);
    }
```

If given approval, I have no issue submitting a PR with this in it, or any other color than gray is fine as well.

- Version with issue:
- Last known good version: None
- IDE: Visual Studio 2017 15.8.1
- Platform Target Frameworks: All
  - Android:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

iOS:

![image](https://user-images.githubusercontent.com/6599983/44423963-22d13180-a54d-11e8-98c8-5c8f7cbf90af.png)

Android:

![image](https://user-images.githubusercontent.com/6599983/44424191-eeaa4080-a54d-11e8-828c-c24264234e91.png)

### Reproduction Link

Examine Control Gallery

**Comment by vyasaraj999** [comment]
Try this on the UI xaml page which changes the color on the selected tabs and remains same on unselected tab.
android:TabbedPage.BarItemColor="#FFFFF" 
android:TabbedPage.BarSelectedItemColor="anycolor"

**Comment by adammeaney** [comment]
@hartez If you guys want me to go ahead and code up my suggested fix, I can.

If you want to go a different way, or not work with it at all, just let me know.
