### ISSUE TITLE
WebClient TotalBytesToReceive always Returns -1

### ISSUE THREAD

**Issue by yanshouwang** [xamarin/Xamarin.Forms#3630]
### Description
after i upgraded to VS 2017 15.8, the DownloadProgressChanged event of WebClient occured an error that  the e.TotalBytesToReceive parameter always returns -1, and it's work fine before i upgraded and in my workmate's VS 2017 15.7.
### Steps to Reproduce

The follow is my code:
`
               DownloadProgress = 0;

                // After upgrade to VS 2017 15.8.0 TotalBytesToReceive always Returns -1
                using (var client = new WebClient())
                {
                    client.DownloadProgressChanged += (s, e) =>
                    {
                        DownloadProgress = (double)e.BytesReceived / e.TotalBytesToReceive;
                    };

                    await client.DownloadFileTaskAsync(_otaUri, tempPath);
                }
                return true;

                //using (var client = new HttpClient())
                //using (var stream = await client.GetStreamAsync(_otaUri))
                //using (var fs = new FileStream(tempPath, FileMode.Append))
                //{
                //    var totalBytes = stream.Length;
                //    var receivedBytes = 0;
                //    var readBytes = 0;
                //    var buffer = new byte[102400];

                //    while ((readBytes = await stream.ReadAsync(buffer, 0, buffer.Length)) > 0)
                //    {
                //        fs.Write(buffer, 0, readBytes);
                //        receivedBytes += readBytes;
                //        DownloadProgress = (double)receivedBytes / totalBytes;
                //    }
                //    fs.Flush();
                //    fs.Close();
                //}
                //return true;
`
I also try to use HttpClient but the buffer length confused me...
I will open that file immediately after i download my apk file, but if I use the fileStream and the download speed is to fast the bag will not be readable right now
And the WebClient works very well except can't read the whole length...
Any suggestions to me or What can I do to fix that?

### Expected Behavior
The e.TotalByteToReceive returns the file's real length.
### Actual Behavior
always returns -1
### Basic Information

- Version with issue: VS 2017 15.8
- Last known good version: VS 2017 15.7
- IDE: Visual Studio Comunity
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 8.1
  - UWP:  NULL
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![youdu 20180822142703](https://user-images.githubusercontent.com/24455689/44446528-cab33180-a617-11e8-9f17-7b780c24f5f8.png)

**Comment by Sebastian1989101** [comment]
I have the very same problem with the latest release of VS. It also happens on VS for Mac.

**Comment by pauldipietro** [comment]
Can you please confirm that this had nothing to do with a Forms update?

**Comment by Sebastian1989101** [comment]
@pauldipietro I did not change any NuGet package what so ever. The last time I upgrade my NuGet packages is 3 month ago and it has worked until the VS 2017 update to 15.8.

**Comment by pauldipietro** [comment]
Okay, thanks. This sounds to me like it should be filed elsewhere, but will need to figure out where.

**Comment by yanshouwang** [comment]
@pauldipietro I tested this on android and uwp again with the latest VS2017 15.8.3 and Xamarin.Forms 3.1.0.697729, but it's still returns -1 to me until the whole file downloaded.
The project link is here:
[https://github.com/yanshouwang/Test.Forms.git](url)
Here is the screenshots:
![screenshot_1536383301](https://user-images.githubusercontent.com/24455689/45250678-df5b2d80-b36a-11e8-959f-b53b3479615d.png)
![screenshot_1536383362](https://user-images.githubusercontent.com/24455689/45250680-e3874b00-b36a-11e8-9ac1-d40b9e077d21.png)

**Comment by PureWeen** [comment]
I can't really say if this used to work or not but this isn't really a forms issue.

I've attached a project here that's purely a UWP project and it also returns -1 for TotalBytesToReceive.

I would log the issue here
https://developercommunity.visualstudio.com/spaces/8/index.html

In the mean time you can inspect the webclient parameter and grab the content-length header to retrieve the value that you want

[WebClientTotalDownload.zip](https://github.com/xamarin/Xamarin.Forms/files/2373686/WebClientTotalDownload.zip)

I also did the same thing with a netcoreapp and that one did correctly set TotalBytesToReceive

In general WebClient is a bit weird to use and overall I'd recommend using HttpClient
