### ISSUE TITLE
Allow OnChildMeasureInvalidated(object sender, EventArgs e) to be overriden or a return method

### ISSUE THREAD

**Issue by KaelSuncaster** [xamarin/Xamarin.Forms#3631]
### Description

Stackpanels or the base layout is not very efficient, when a large number of child elements visibility changes, these cause unnecessary layout calculations. These should be done in bulk, with one calculation.

### Steps to Reproduce

1. Have a stack panel or the new experimental items control with a large set of hidden children.
2. Update all children to visible. Noticeable delay as the layout is done per child.

### Expected Behavior
Smooth transition.
### Actual Behavior
UI thread is blocked. Large delays.

This can be changed in the base layout or allow developers to ignore children raising invalidate measure to throttle changes for one layout pass.

### Basic Information

- Version with issue: Current
- Last known good version: None
- Affected Devices: All?

This will be an issue with the new ItemsControl. Having dynamic children will be a large use case for the new control.

https://github.com/xamarin/Xamarin.Forms/issues/1743

**Comment by hartez** [comment]
@KaelSuncaster What platform are you seeing this problem on? Could you provide a reproduction project which demonstrates this issue?

**Comment by samhouts** [comment]
@KaelSuncaster Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
