### ISSUE TITLE
[WPF] DisplayAlert has no Text Wrapping 

### ISSUE THREAD

**Issue by KasperinK** [xamarin/Xamarin.Forms#3634]
### Description
DisplayAlert is not wrapping the text.

### Steps to Reproduce
Create a Xamarin.WPF project.
Use DisplayAlert with a long message.

### Expected Behavior
![image](https://user-images.githubusercontent.com/39413152/44474488-63d25000-a5f8-11e8-8adf-bf8eafbee8dd.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/39413152/44474514-764c8980-a5f8-11e8-8e19-1be84919a1a2.png)

### Basic Information
- Version with issue: 3.1.0.697729
- Last known good version: None, I tested every version.
- IDE: Visual Studio 2017 Version 15.7.4
- Nuget Packages: Xamarin.Forms and Xamarin.Forms.Platform.WPF

### Reproduction Link
[DisplayAlertIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2311059/DisplayAlertIssue.zip)

**Comment by mohachouch** [comment]
Bug in template : https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Themes/FormsContentDialog.xaml line 55.  Replace TextTrimming by TextWrapping="WrapWithOverflow"
