### ISSUE TITLE
[XAMLC] App crashed when binding Switch.IsToggled property to view model

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#3642]
### Description

Getting following exception when app with enabled XAMLC and binding Switch IsToggled property to view model
```
Unhandled Exception:

System.InvalidProgramException: Invalid IL code in XamlcBug.MainPage:<InitializeComponent>typedBindingsM__4 (XamlcBug.MainPageViewModel,bool): IL_0003: call      0x06000012
```

 occurred
### Steps to Reproduce

1.  Run attached project

### Expected Behavior

App should not crash
### Actual Behavior
App crashes

### Basic Information

- Version with issue: 3.1.0.697729 (happens also on latest nightly)
- Last known good version:
- IDE: Visual Studio 2017 15.8
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version:
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/3065454/44528240-4c26c480-a6e9-11e8-8624-63526fb0f942.png)

### Reproduction Link

[XamlcBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2314589/XamlcBug.zip)

**Comment by toomasz** [comment]
Hello, I tested in with XF 3.3.0.912540 and it no longer occurs, i think we can close it.

**Comment by StephaneDelcroix** [comment]
Great, I fixed some bugs related to that lately, and somehow forgot to link the PR to this issue.
