### ISSUE TITLE
[UWP] Picker placeholder text

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#3646]
### Description

According to the documentation (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.picker.title?view=xamarin-forms#Xamarin_Forms_Picker_Title), `Title` is displayed differently. Actually, it's rendered as a `Control.Header` on UWP. Is there any specific reason for this? The combobox the `Picker` is rendered with has a proper `PlaceholderText` property and it functions flawlessly. Why isn't it used?

It's rather straightforward to work around this issue by creating a descendant of `Picker` and minimally modifying its renderer but the reason for the original decision simply escapes me.

### Steps to Reproduce

1. Use a Picker.
2. Set its Title.
3. Run on UWP.

### Basic Information

- Version with issue: current
- Last known good version: none

**Comment by hartez** [comment]
> Is there any specific reason for this?

The Title property seemed to map more naturally to the [ComboBox.Header](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.header#Windows_UI_Xaml_Controls_ComboBox_Header) property than the [ComboBox.PlaceholderText](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.combobox.placeholdertext#Windows_UI_Xaml_Controls_ComboBox_PlaceholderText) property. Especially in the case of pre-filled data, where the PlaceHolderText would never be visible to the user, so the purpose of the form field would not be apparent.

> It's rather straightforward to work around this issue by creating a descendant of Picker and minimally modifying its renderer

Yup.

**Comment by MitchBomcanhao** [comment]
In a cross-platform world, I want my android and iOS and UWP apps to behave roughly the same without having to make custom renderers for each one to ensure they do.

2 years later, this is still the same and we still have to put in a special renderer to make the UWP app show the text in the placeholder bit just like iOS and Android.

**Comment by hammondreg** [comment]
No answer!
