### ISSUE TITLE
Two keyboards appear when editing the TextColumn after the NumericColumn with Samsung  Android version 6 devices only on Input type of Samsung Keyboard 

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#3647]
### Description

Hi Team, 

We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin

Below mentioned issue is only on Samsung  devices with "**Android version 6 Marshmallow and API 23**" with Input type as only on "**Samsung Keyboard**"

We would like to bring to your notice a bug that we encountered recently when editing the first column (Numeric column) alphanumeric Keyboard appears which is fine, after that while editing second column (Text Column), same alpha numeric keyboard appears first, next text keyboard comes to the view which is issue. Issue has replicated on 3.2.0 version too.

Also we have already crated bug report related to this issue. Bug report link : https://github.com/xamarin/Xamarin.Forms/issues/3582, But you have validated wrongly as by deploying Android_6 emulators and stated keyboard working fine. So, Do check on Samsung Android version 6 devices with only **Samsung keyboard**. Also we would like to mention here while giving input type as google keyboard on same Samsung Android version 6 devices keyboard working fine.

### Steps to Reproduce

1.Run the attached sample in Samsung  devices with "**Android version 6 Marshmallow and API 23**" with Input type as only on "**Samsung Keyboard**"
2.Enters in to edit mode by double tabbing
3.Edit any cell in the first column (Numeric column)
4.Then tab any where to collapse the keyboard
5.Now edit the second column (Text column)
6.Able to see first "Alphanumeric keyboard" comes to the view after that "Text keyboard" appears, which is mentioned issue

### Expected Behavior

Only Text keyboard should appear while edit the Text column after editing of Numeric column

### Actual Behavior

After editing Numeric column if editing happens for Text column, first Alphanumeric keyboard comes to the view then Text keyboard appears.

### Basic Information

- Version with issue:  2.4.0.280
- Last known good version: 3.2.0.729530-pre 2
- IDE: 
- Platform Target Frameworks:
  - Android: Android: 6 Marshmallow API 23
- Nuget Packages: 3.2.0.729530-pre 2
- Affected Devices: Android version 6 Marshmallow API 23 devices

### VideoLink

(https://github.com/xamarin/Xamarin.Forms/files/2293076/TwoKeyboardVideo.zip)

### Reproduction Sample link 

[BugReport.zip](https://github.com/xamarin/Xamarin.Forms/files/2317134/BugReport.zip)

Note: In case if SfDatagrid packages are not restored in the sample, you can download the package Syncfusion.Xamarin.SfDataGrid from nuget.org.

**Comment by hartez** [comment]
I can confirm this on a Samsung Galaxy Tab 3, API 26, using the default Samsung software keyboard. When switching between text inputs, the previous input's keyboard is displayed briefly, then it switches to the new keyboard.

Just to make sure it wasn't a Samsung issue, I threw together a standard Xamarin.Android app with two different input types on two EditText controls. Switching between them does not display the delay that we see in BugReport.zip. So the delay seems to be caused by something in Forms. 

[SamsungKeyboards Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2319773/SamsungKeyboards.Repro.zip)

**Comment by adrianknight89** [comment]
I believe the issue might be related to `DescendantFocusToggler`. Setting and reverting `DescendantFocusability` of the parent view may be the culprit. @hartez Is anything happening with #2151? I noticed it's using `AppCompatEditText`; thus, skipping `DescendantFocusToggler`.
