### ISSUE TITLE
[XAMLC] [Hang] App updating view model property periodically always hangs after ~14th update

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#3650]
### Description

Hang observed short after starting my app when XAML Compilation is enabled. App is updating view model property in 200ms interval. App attached to bug report.

Hang is not observed when XAMLC is disabled.

### Steps to Reproduce

1. Run attached app
2. Wait few seconds
3. Counter not long updates, UI thread is hang, app not responding

### Expected Behavior

App should not hang
### Actual Behavior

App Hangs

### Basic Information

- Version with issue: 3.1.0.697729, also 3.3.0.775299-nightly
- Last known good version: 
- IDE: VS 15.8
- Platform Target Frameworks:
  - Android: 8.1

### Reproduction Link

[XamlcBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2318343/XamlcBug.zip)

**Comment by toomasz** [comment]
```
private async void UpdateIndefinitely()
        {
            while(true)
            {
                UpdateAndIncrease(ref _number);
                await Task.Delay(200);
            }
        }
```

@dminta It will run synchronously unitl await task delay, then continuation will be scheduled on ui thread.

**Comment by dminta** [comment]
@toomasz Ok, I've tried the sample and can confirm the issue. I also noticed that GC is working hard allocating and freeing thousands of objects.

When I removed `Text={Binding Label}`. added `x:Name="label"` in MainPage.xaml, then set Text binding in code at the end of `MainPage` constructor:
 `label.SetBinding(Label.TextProperty, new Binding(nameof(MainPageViewModel.Title), source: viewModel));` - problem disappeared.

**Comment by toomasz** [comment]
@dminta I can also reproduce issue when i just change string property from button OnClick command, app just hangs after several clicks. Might be related to #3613

**Comment by toomasz** [comment]
Any chance of getting this fixed in upcoming release? This issue is blocking use of XAMLC in all projects that are dynamically updating view model properties. Thanks.

**Comment by StephaneDelcroix** [comment]
dupe of #3613

**Comment by StephaneDelcroix** [comment]
@dminta at least, the generated code looks right. it's the invocation that's probably wrong
