### ISSUE TITLE
Merged ResourceDictionary resources cannot be modified as DynamicResource

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#3661]
### Description

Back around XF 2.5 we received the possibility to specify resource dictionaries in separate files and merge them into app or page resources later. However, items (eg. colors) specified in those separate files cannot be modified in order to be used as dynamic resources, for instance, to support theming.

### Steps to Reproduce

1. Check out the attached sample.
2. There are twice three colors, three defined in a separate resource dictionary, three directly in the application resources.
3. The app constructor tries to modify all six colors.

### Expected Behavior

All buttons appear in YellowGreen.

### Actual Behavior

Only half of them appear in YellowGreen.

### Basic Information

- Version with issue: current
- Last known good version: n/a

### Reproduction

[XamarinDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2321103/XamarinDemo.zip)

**Comment by pauldipietro** [comment]
I see that @StephaneDelcroix has self-assigned this but it does appear that the reproduction behaves as described.
