### ISSUE TITLE
GTK: ListView entries are handled as XML internally; this conflicts with the other platforms

### ISSUE THREAD

**Issue by tluyben** [xamarin/Xamarin.Forms#3663]
### Description

As ListView string items are handled as XML, illegal characters for XML will not render. This is fine but is incompatible with the other platforms. 

Of instance strings with < > etc won't be rendered and generate a Gtk-WARNING as they should be &amp;lt; &amp;gt; etc 

This is contrary to the other platforms so I would label it a bug. 

### Steps to Reproduce

1. Create a ListView with an item "< Back" in Platform.GTK
2. Run application

### Expected Behavior

A row showing "< Back" rendered and clickable.

### Actual Behavior

An empty row "" rendered and clickable.

### Basic Information

- Version with issue: 3.1.0.697729 of Xamarin.Forms.Platform.GTK
- Last known good version: do not know
- IDE: Visual Studio 15.6.0
- Platform Target Frameworks: 
 - GTK: 3.1.0.697729
- Affected Devices: Windows 10, Linux

**Comment by tluyben** [comment]
It is the Pango markup (excuse my ignorance); it does behave completely difference than other platforms so it would probably be better to switch that off if possible.

**Comment by jsuarezruiz** [comment]
I can take a look. Thanks for the feedback.

**Comment by jsuarezruiz** [comment]
I reproduce the bug: [Issue3663.zip](https://github.com/xamarin/Xamarin.Forms/files/2333522/Issue3663.zip)

**Comment by jsuarezruiz** [comment]
PR sent: [https://github.com/xamarin/Xamarin.Forms/pull/3684](https://github.com/xamarin/Xamarin.Forms/pull/3684)
