### ISSUE TITLE
[GTK] Removing labels from StackLayout and re-adding them makes them have Height=0 when rendered

### ISSUE THREAD

**Issue by tluyben** [xamarin/Xamarin.Forms#3665]
### Description

When you dynamically add labels (for instance for flexible/dynamic form) to a Vertical StackLayout, and then remove them again, the second time they are added, their Height = 0 and hence they are invisible. 

Adding HeightRequest=20 (for instance) makes them visible again. 

This is contrary to the other platforms where this works as expected. 

### Steps to Reproduce

1. Create a Vertical StackLayout myLayout, Add a Label "Hello World!" and a Button "Refresh" below the StackLayout (in another one or wherever), 
2. Bind Button to do myLayout.Children.Clear() and myLayout.Children.Add(new Label("No World!"))
3. Run and Click the Button 

### Expected Behavior

"No World!" label shows up 

### Actual Behavior

No label shows up

Note that if you Add(new Label() { Text = "Yes World!', HeightRequest=20 }) it does show up. 

### Basic Information

- Version with issue: 3.1.0.697729 of Xamarin.Forms.Platform.GTK
- Last known good version: do not know
- IDE: Visual Studio 15.6.0
- Platform Target Frameworks: 
 - GTK: 3.1.0.697729
- Affected Devices: Windows 10, Linux

**Comment by jsuarezruiz** [comment]
I can take a look. Thanks for the feedback.

**Comment by jsuarezruiz** [comment]
I can reproduce the Issue. I attach a sample. Let's see what happens!
[Issue3665.zip](https://github.com/xamarin/Xamarin.Forms/files/2333255/Issue3665.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
