### ISSUE TITLE
[UWP] NavigationPage on UWP - Effects are not applied

### ISSUE THREAD

**Issue by knightmeister** [xamarin/Xamarin.Forms#3666]
### Description
I am able to apply Effects to NavigationPages on Android. It does however not work on UWP.

### Steps to Reproduce

1. Add an effect to the shared project
````
namespace App4.Effects
{
    public class TestEffect : RoutingEffect
    {
        public TestEffect() : base("Test.TestEffect")
        {

        }
    }
}
````

2. Add the effect implementation to UWP
````
[assembly: ResolutionGroupName("Test")]
[assembly: ExportEffect(typeof(TestEffectUwp), "TestEffect")]

namespace App4.UWP.Effects
{
    public class TestEffectUwp : PlatformEffect
    {
        protected override void OnAttached()
        {
              System.Diagnostics.Debugger.Break();
        }

        protected override void OnDetached()
        {
            
        }
    }
}
````
3. Add a navigation page with the following XAML
````
<?xml version="1.0" encoding="utf-8" ?>
<NavigationPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:effect="clr-namespace:App4.Effects"
             x:Class="App4.NavigationPage">

    <NavigationPage.Effects>
        <effect:TestEffect />
    </NavigationPage.Effects>
   
</NavigationPage>
````

### Expected Behavior
The break point will fire when the effect is applied.

### Actual Behavior
UWP effect is never called for NavigationPage

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: N/A
- IDE: VS 2017 15.7.4
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: 8.1
  - UWP:  16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
