### ISSUE TITLE
[Enhancement] Add text-transforms to Label

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#3667]
## Summary
Our design-people came up with a design that includes headers that are all uppercase. Right now, we use a converter for this or included it in a markup extension for values that we localize. I think it would be great to have a couple of text transforms (a la CSS) in Forms available by default.

## API Changes

It makes the most sense to implement this on the `Label` control. A new property would be introduced taking in a new enum. You can see them underneath:

- `Label.TextTransform` value of `TextTransform` enum
- `TextTransform` enum: `None`, `Uppercase`, `Lowercase`, `Title`, `None` will be the default to be backwards compatible.

## Intended Use Case
As mentioned already in the summary; you might encouter use-cases where you want to implement text with a certain casing. While this is solvable by entering a string uppercase, writing your own extension, etc. In my opinion this is purely a styling thing and belongs to a property on the control so you don't have to think about this anymore.

**Comment by Depechie** [comment]
Just as extra request ( could be placed on different issues, but I think this one fits well ), would love to have a broader ability like UWP function binding: https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings

That way we don't need to add more and more properties to the control for regular string rendering.
