### ISSUE TITLE
[GTK] Background of ListView is always grey

### ISSUE THREAD

**Issue by tluyben** [xamarin/Xamarin.Forms#3668]
### Description

No matter what color you apply to the BackgroundColor of ListView, it is always grey. 

### Steps to Reproduce

1. Add a ListView to a project, set the BackgroundColor = Color.Blue, add a few items

### Expected Behavior

List with a Blue background.

### Actual Behavior

List with a grey background. 

### Basic Information

- Version with issue: 3.1.0.697729 of Xamarin.Forms.Platform.GTK
- Last known good version: do not know; in the gallery by Ruiz Jsuarez, the ListViews also have grey backgrounds
- IDE: Visual Studio 15.6.0
- Platform Target Frameworks: 
 - GTK: 3.1.0.697729
- Affected Devices: Windows 10, Linux

**Comment by jsuarezruiz** [comment]
I can take a look. Thanks for the feedback.

**Comment by rmarinho** [comment]
Hi thanks can you please give us a reproduction example? 

I have tried the following code and seems to work.

```
var listv = new ListView {
				BackgroundColor = Color.Blue,
				ItemsSource = new string[] { "1", "2", "3" }
			};

var page = new ContentPage();
page.Content = listv;
```

<img width="799" alt="screen shot 2018-08-29 at 17 24 34" src="https://user-images.githubusercontent.com/1235097/44801407-e3d85700-abb0-11e8-83ce-6d8b7456fa99.png">

**Comment by jsuarezruiz** [comment]
Cannot reproduce the problem with **3.1.0.697729**:
![imagen](https://user-images.githubusercontent.com/6755973/44804765-a4b30180-abc2-11e8-8e1b-d42fdd147f45.png)
[Issue3668.zip](https://github.com/xamarin/Xamarin.Forms/files/2333150/Issue3668.zip)
Can you give more information?

**Comment by tluyben** [comment]
Yes, I will make a project. I think it might have something to do with the fact that mine is on top of two different stacklayouts.

**Comment by tluyben** [comment]
Apologies, this one can be closed. My bad; while trying to reproduce this issue I found something deep in the system that made this happen.
