### ISSUE TITLE
In UWP : Scrollview not working or visible when added to scrollable tab control.

### ISSUE THREAD

**Issue by bhaveshsoft1** [xamarin/Xamarin.Forms#3669]
### Description

We have created custom scrollable tab control by extending tab control mentioned in below reference url https://www.codeguru.com/virtual-mobile/a-tab-control-in-xamarin.html

Scroll view control was rendering properly and visible till xamarin forms DLL : 3.1.0637273 and below. 
But in xamarin forms DLL : 3.1.0.697729, their is some problem in rendering of scroll view hence my ui is getting disturbed. 

But if i set scroll view "is visible" property set to false using 3.1.0.697729. Then UI other than scroll view is rendering properly. In mac scroll view rendering is fine with this 3.1.0.697729. So i believe their is some UWP specific issue in scroll view.

Also i have searched "xamarin form" code in github for above versions and found that many changes are done for visibility and rendering of scroll view in uwp by xamarin team.

I believe due to those changes. My existing code either need more code configuration which you can suggest or their is some bug in DLL : 3.1.0.697729 for scroll view in UWP.

It will take lot of time for me to produce sample for your team. But if same person go through his code then probably he could suggest whether their is a bug or due to 3.1.0.697729 version more configuration is needed in scroll view.

### Steps to Reproduce

NA

### Expected Behavior

NA

### Actual Behavior

NA

### Basic Information

- Version with issue: xamarin.forms 3.1.0.697729
- Last known good version: xamarin.forms 3.1.0637273
- IDE: VS 2017 15.6.7
- Platform Target Frameworks: 
  - UWP:  Microsoft.NETCore.UniversalWindowPlatform => 6.1.7
- Affected Devices: window 10 , version 1803 , os build : 17134.228

### Screenshots

NA

### Reproduction Link

NA

**Comment by pauldipietro** [comment]
If you find the time, please upload a reproduction solution when able to better illustrate the scenario in question where your behavior has changed.

**Comment by samhouts** [comment]
@bhaveshsoft1 Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
