### ISSUE TITLE
IOS: Disabled picker is not recognizable as disabled

### ISSUE THREAD

**Issue by byrcb** [xamarin/Xamarin.Forms#3673]
### Description
IOS: Disabled picker is not recognizable as disabled because it looks the same as a enabled one. The only difference is that it is blocked. 

### Steps to Reproduce
1. Bind bool property to Picker.IsEnabnled
2. Set bindable bool property to false 
3. Picker appear like it is enabled

### Expected Behavior
The Picker should be recognizable as disabled

### Actual Behavior
Disabled Picker could not be differentiate from an enabled one.

### Basic Information
- Version with issue (Xamarin Forms): 3.1.0.583944
- Last known good version: -
- IDE (Mac): Visual Studio 7.6 (2190)
- Platform Target Frameworks: 
  - iOS:  11.4.1 (15G77)

**Comment by rmarinho** [comment]
From our tests it seems that there's differences from a Enabled and Disabled Picker, as you can see in the below screenshot. Is there something we are missing? Isn't this what you see? 

![simulator screen shot - iphone x - 2018-08-29 at 17 42 36](https://user-images.githubusercontent.com/1235097/44802187-f18edc00-abb2-11e8-89ba-b8cfea9d5304.png)

**Comment by samhouts** [comment]
@byrcb  Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
