### ISSUE TITLE
[GTK] Inconsistent alignment of elements in StackLayout based on addition to a parent StackLayout

### ISSUE THREAD

**Issue by tluyben** [xamarin/Xamarin.Forms#3674]
### Description

When I have an existing vertical StackLayout oldLayout and I create a new vertical StackLayout like; 

    newLayout = new StackLayout { Orientation = StackOrientation.Vertical,  Children = { lblTitle, lblMessage, txtInput, slButtons } };
    oldLayout.Children.Add(newLayout);

vs

    newLayout = new StackLayout { Orientation = StackOrientation.Vertical };
    oldLayout.Children.Add(newLayout);

    layout.Children.Add(lblTitle);
    layout.Children.Add(lblMessage);
    layout.Children.Add(txtInput);
    layout.Children.Add(slButtons);

where lblTitle, lblMessage is type Label, txtInput of Type Entry and slButtons of Type StackLayout, but I do not think the control types matter, although Labels seem to be affected worse. 

The former does not show the the Labels until you slightly change the dimensions of the window while the latter works as expected. 

Note that both examples work on the other platforms including WPF. 

### Steps to Reproduce

1. Implement the first example above on a ContentPage
2. Run

### Expected Behavior

2 labels, a text entry and 2 buttons vertically aligned.

### Actual Behavior

Only a text entry and 2 buttons vertically aligned appear. When the window is in anyway resized, the proper controls show up as expected in the first place. 

### Basic Information

- Version with issue: 3.1.0.697729 of Xamarin.Forms.Platform.GTK
- Last known good version: do not know; in the gallery by Ruiz Jsuarez, the ListViews also have grey backgrounds
- IDE: Visual Studio 15.6.0
- Platform Target Frameworks: 
 - GTK: 3.1.0.697729
- Affected Devices: Windows 10, Linux

**Comment by jsuarezruiz** [comment]
Related with #3665.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
