### ISSUE TITLE
[Previewer, Android] Custom font throws an error 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3687]
### Description

Original issue. https://bugzilla.xamarin.com/show_bug.cgi?id=57417#c5

I can confirm this still happens.

### Steps to Reproduce

1. Preview an Android UI with a custom font. 

### Expected Behavior
Renders

### Actual Behavior
Errors

### Basic Information

- Version with issue: still present in 3.2

### Reproduction
https://github.com/microsoft/ConferenceVision

**Comment by alanmcgovern** [comment]
I don't know why this is assigned to me, but ill assume this is a dupe of: https://github.com/xamarin/Xamarin.Forms/issues/3520

**Comment by alanmcgovern** [comment]
NOTE: Issues which are actually in the forms previewer should be tagged with the 'forms-previewer' label. That's what surfaces them to us.
