### ISSUE TITLE
WPF Window border cannot be removed

### ISSUE THREAD

**Issue by micrtoeq** [xamarin/Xamarin.Forms#3688]
### Description

Despite setting the Properties App.Current.MainWindow.AllowsTransparency to true and App.Current.MainWindow.WindowStyle to System.Windows.WindowStyle.None, the Windows border cannot be removed.

### Steps to Reproduce

Either set 

App.Current.MainWindow.AllowsTransparency = true and 
App.Current.MainWindow.WindowStyle =System.Windows.WindowStyle.None

in the constructor of the main window or set the Parameters 

WindowStyle="None" 
AllowsTransparency="True"

in the XAML of the main application page.

### Expected Behavior

Window border should be removed.

### Actual Behavior

Window border is showing.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.WPF. ver. 3.2.0.729530-pre2
- Last known good version:
- IDE: VS 2017 15.8.2
- Platform Target Frameworks: WPF
- Affected Devices: Windows 10

**Comment by ZeProgFactory** [comment]
With Xamarin.Forms 4.1.0.555618  
and Xamarin.Forms.Platform.WPF 4.1.0.555618  
it still doesn't work.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
