### ISSUE TITLE
WPF: Unable to intercept back button 

### ISSUE THREAD

**Issue by micrtoeq** [xamarin/Xamarin.Forms#3689]
### Description

We cannot find any possibility to intercept the back button in a Xamarin Forms WPF project.
I.e. the NavigationPage.OnBackButtonPressed is only called on Android and UWP, but not in WPF.
We have also tried to intercept the back button in the WPF project natively, which is also never called:
System.Windows.Application.Current.Navigating += new NavigatingCancelEventHandler(OnNavigating);

### Steps to Reproduce

1. Add a new WPF Project.
2. Create a page with abutton which pushes another page. Try to intercept the top left back button (back menu) on the second page when going back to the first page.

### Expected Behavior
One should be able to intercept the back button (ind interupting the page popping, if needed) before popping the page. This works in UWP and Android.

### Actual Behavior
No interception available.

### Basic Information

- Version with issue: Xamarin.Forms.Platform.WPF 3.2.0.729530-pre2
- Last known good version:
- IDE: VS 2017 15.8.2
- Platform Target Frameworks: WPF
- Affected Devices: Windows 10

**Comment by rmarinho** [comment]
NavigationPage.OnBackButtonPressed is only called when Hardware button is used I think is the same on iOS and Android. tapping back on iOS navigation page will not call OnBackButtonPressed

**Comment by micrtoeq** [comment]
Thank you for your info.

Yes, we know that OnBackButtonPressed is thought for the hardware button, but our problem ist that we cannot find ANY possibility to intercept this back button in WPF. By the way, in UWP this event is called when clicking the top left back button in the window (software).
