### ISSUE TITLE
Cant access x:Name property of an XF control

### ISSUE THREAD

**Issue by devmikew** [xamarin/Xamarin.Forms#3692]
It would be nice to be able to access the x:Name property of an XF control, either created directly in XAML, or in a style/control template.

Also, to copy that name to the top level native control created by the renderer.

Eg, in Windows a FrameWorkElement has a Name property which is copied from the XAML.

Android has Id, however it is an integer. It also has Tag which is an object.

Then when debugging your code you could find the rendered control associated with your XF control.

also one could write code to Find a control by name. Or have platform dependent code reference the control by name, eg, in the VisualStateManager.

In XF it would need to be added to Element.

**Comment by thedjnova** [comment]
x:Name is used to create the reference to the elements in C# so I cant see how it would be possible or what the purpose would be?

**Comment by devmikew** [comment]
Have you ever tried to debug an app on its intended platform?

Uwp and wpf do it.

I"ve since discovered that even XF partially does it. But the x:Name is put in to StyleId.

All I'm really asking is it is put into a property called Name and copied to the rendered control, if the platform supports it.

**Comment by devmikew** [comment]
Also, as I said in the original post, if one wants to write  VSM platform dependend xaml you need to have the name property of a control. Eg:
									<VisualState.Setters>
										<Setter Target="ContentRoot.MinHeight" Value="0" />
										<Setter Target="ContentViewbox.Visibility" Value="Collapsed" />
										<Setter Target="TextLabel.Visibility" Value="Collapsed" />
										<Setter Target="OverflowTextLabel.Visibility" Value="Visible" />
									</VisualState.Setters>

ContentRoot.MinHeight finds a control by name of ContentRoot.

**Comment by devmikew** [comment]
I didn't close it, or, didn't mean to.
