### ISSUE TITLE
Please Reopen [Enhancement] Padding on Buttons #1702

### ISSUE THREAD

**Issue by TFreudi1** [xamarin/Xamarin.Forms#3693]
It is still not working, please Reopen it

VS 2017 15.8.2
In Xaml: Button Padding="0" 
gives
Unhandled Exception:

Xamarin.Forms.Xaml.XamlParseException: Position 24:21. Cannot assign property "Padding": Property does not exists, or is not assignable, or mismatching type between value and property

@TFreudi1

**Comment by pauldipietro** [comment]
Closing per comments on that issue that it in fact works.
