### ISSUE TITLE
[Android] Is FastRenderers_Experimental still needed?

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/Xamarin.Forms#3696]
Hello,

Do we still need to call Xamarin.Forms.Forms.SetFlags("FastRenderers_Experimental") with latests XF releases? (3.1.0.697729)

Thanks

**Comment by pauldipietro** [comment]
Yes.

**Comment by iashaik** [comment]
A year later... Still experimental.

**Comment by hartez** [comment]
> A year later... Still experimental.

@iashaik The fastrenderers have been stable and out from under the experimental flag since ... 4.2 I think. They are now the default renderers.
