### ISSUE TITLE
[Android] popup menu moving top-left

### ISSUE THREAD

**Issue by godevrepo** [xamarin/Xamarin.Forms#3697]
### Description
If I use a Secondary Toolbar-Item to push a new page through a ViewModel on to the Navigation stack, the popup menu item is moving to the top-left corner before disappearing. This only happens when a page is pushed, not when the page stays the same.

### Steps to Reproduce
I think it happens mostly with older projects.
1. Create a secondary toolbar item
2. Create a ViewModel with a command pushing a new Page onto the navigation stack
3. Bind the command to the toolbar item

### Expected Behavior
Popup menu item disappering and new page opening

### Actual Behavior
Popup menu item moving to the top-left corner before disappearing and opening new page

### Basic Information

- Version with issue:
- Last known good version: don't know
- IDE: MS Visual Studio 15.7.4
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices:

### Screenshots

![bug](https://user-images.githubusercontent.com/4274219/44986661-d3472880-af84-11e8-9f44-0f140893782b.gif)

### Reproduction Link
I used the MasterDetail Example to reproduce as it was the "cleanest" project I had around with this issue. I could not reproduce it with every project.
https://drive.google.com/file/d/1kROvYO5C-tdNZKhaATnqaTbsMBqcBRs4/view?usp=sharing

**Comment by pauldipietro** [comment]
I seem unable to reproduce this on 7.0 and 8.0 emulators using the provided sample. Perhaps it's a device-specific issue with regards to hardware and processor power. Can you elaborate on your system hardware or if you've tried this on any actual devices?

**Comment by godevrepo** [comment]
Thanks for the answer. I tried it on different emulators and real devices. We had this problem with a different project where multiple people on different machines had this problem. I am going to test this as well as the other project on a new personal system and report my results.

**Comment by samhouts** [comment]
@godevrepo  Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
