### ISSUE TITLE
Xamarin.Forms view is freezing when appearing

### ISSUE THREAD

**Issue by azuken** [xamarin/Xamarin.Forms#3702]
### Description

On some devices, app is freezing and memory is increasing indefintely. We have no information, no error log, just garbage collector logs which says memory is increasing

### Steps to Reproduce

1. Use latest builds of Xamarin.Forms (3.1.0.637273 and 3.1.0.697729)
2. View contain tabbed page, listview, "PullToRefresh" widget from Syncfusion, and Floating Action Button from FAB.Forms (dependencies updated manually)
3. App launch, with a login view, and when logged and main view is appearing, app is freezing.

### Expected Behavior

App navigation

### Actual Behavior

App frozen

### Basic Information

- Version with issue: 3.1.0.637273 and 3.1.0.697729
- Last known good version: 3.1.0.583944
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - Android: Android API 27 (Tested and reproduced on API 24 and 26)
- Android Support Library Version: v7
- Nuget Packages: Xamarin.Forms
- Affected Devices: Samsung Galaxy A6 (2016) and Samsung Galaxy S9 Plus

**Comment by pauldipietro** [comment]
Can you please upload a reproduction solution which displays the issue? Have you also tested the app with and without custom (non-XF) controls?

**Comment by azuken** [comment]
I've tested with and without custom controls, and it appears that is SyncFusion PullToRefresh control which cause freeze, but not the widget itself ; if I delete a call on the Main Thread, it works (except action in the function called in main thread). Here is a sample of the code :

`            Device.BeginInvokeOnMainThread(pullToRefresh.StartRefreshing);

            await ViewModel.RefreshInterventions(refreshType);

            Device.BeginInvokeOnMainThread(pullToRefresh.EndRefreshing);`

Maybe call this is not the right thing, but we can't find other solution on docs.

**Comment by pauldipietro** [comment]
I would still suggest uploading a reproduction if possible so we can see exactly what's occurring in this scenario. Based on the information originally provided, can you confirm that the SF control was working with one of the more recent versions?

**Comment by azuken** [comment]
Here is two screenshots : https://imgur.com/a/61rlSOo
We cannot really see the difference, except that icon on the floating button is not loaded when app is freezing. We also cannot click on menu, tabs or DatePicker. The code I've posted before is executed in the "OnAppearing" function of the view.

The SF control works fine with the previous version I've mentioned (3.1.0.583944) so I rollbacked to this version for production. I tested the app with latest XF and SF releases with multiple devices (OnePlus 5, Samsung Galaxy 8, Wiko U FEEL LITE, iPhone 7) and everything works fine, but not with some other devices. We detected that bug with a customer which have a Samsung Galaxy A6 2016. I saw that no changes were made in Xamarin.Forms.Core.Device since 4 months.

I've made a test with a Task.Run for the second instruction (in my previous post), and delete Device. BeginInvokeOnMainThread() calls (all async definitions too); app still freeze.

I've made a second test with a ContinueWith for the third instruction, same.

I've read all SF documentation about PullToRefresh, and it seems that we are using correctly the control.

**Comment by PureWeen** [comment]
@azuken  can you please upload a reproduction? 
Looking at the diff between version you say is working vs not working
https://github.com/xamarin/Xamarin.Forms/compare/release-3.1.0-rc1...release-3.1.0-sr1.1

nothing jumps out at me that would cause this issue

Having a repro would be really helpful 
Have you reached out to SF at all to see if they have any thoughts?

**Comment by azuken** [comment]
Hi, sorry for the delay.

I will try next week to upload you a reproduction of the bug, I cannot upload the entiere solution since it belongs to my company.

I do not have contacted SF, but I will do it too.

**Comment by StephaneDelcroix** [comment]
no repro project in a month. closing. reopen when you have a repro project to attach. thanks
