### ISSUE TITLE
[Feedback] Wierd colors after update to .fomrs 3.1 and VS 2017 (17.5)

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3716]
### Description

<p>I have updated my (shared) project from 2.3.x (under VS2015) to 3.1 (under Vs2017) and thereby had massive problems with the base colors - especially to the android project. 
Without any change from my side, all back colors have e.g. changed to white (instead of black) in Android. 
As I have set the text colors to white (and some other “bright” colors), the app becomes unusable.
I don’t work with xaml principally yet (I do anything in code).
To be able to change the base colors back as they were in 2.3.x, I had to break up my app.cs in app.xaml and app.xaml.cs and define all colors (for each platform) in app.xaml.
In my app, I also use various pickers, where I also set a title (“Please chose....”).
The problem is, that the title text to the picker should be grey by default for Android, but is black now.
So I now have “black holes” in my app, where the titles (“Please...”) should be showed and there is no property to the Picker, where the color can be set (so I’m not able to set the title color in app.xaml on in code to grey again). 
So I would have to change the back color to the picker to some other color (e.g. gray) only to enable the users to read the title text (what would break the look and feel of my app completely).
Therefore my question:
Where are the base colors for Android in a .forms project defined and how can the base colors be reset (I don’t think, that the base color to the picker title has changed per default from grey to black)?
Thanks for a fast an clear answer.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/315706/wierd-colors-after-update-to-fomrs-31-and-vs-2017.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/666962">original linked feedback ticket</a>.

### Source

[677724](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677724)

**Comment by FredyWenger** [comment]
@samhouts:
You have not taken over my (I think important) comment to the issue (so.. here it is):
Update to the picker title color problem:
It seems, as the text color to the picker title **is** grey principally…
As soon, as I set the background color of the picker to another color (e.g. grey or white), I can, see that the text color to the title seems to be grey.
But, the (grey) title is not showed by default (black background color set in app.xaml), or if I set the background color of the picker in code to black.
So.. it may be another bug, that the (grey) title is not showed on a black background...

**Comment by samhouts** [comment]
This is a very strange issue! Are you able to send us your project so we can take a look? Thanks!

**Comment by samhouts** [comment]
Also, can you describe how you updated the project to 3.1? Did you update the nuget packages, or did you create a new project and carry your code over to it? Thanks, @FredyWenger!

**Comment by FredyWenger** [comment]
I know, that's it is a very strange issue, therefore, I have lost day's to try resolve it.
I can't send you  my project as I already have modified it.
As I worte, I have **updated/migrated**  from 2.3.x to 3.1 and have **not** created an new project.
Copied the project (all files) in an new root directory, open it in VS2017, update ale nugets and recompile - then I had the color problems (without any change in the code).
Then I had to split my app.cs to app.xaml and app.xaml.cs to be able to define all colors myself.
The remaining problem is the not showed grey picker title on a black background (not to comprehend).
But maybe, you can answer my **initial question:**
**Where** are/were the **base colors** defined for an Android project (**without** app.xaml).
Somewhere, they have to come from and the problem seems to be **there**…
By my tries to solve the problem, I don't have found any information and also no file in the project, so it seems as the definition is somewhere in the Xamarin base...

**Comment by PureWeen** [comment]
@FredyWenger  for the most part we try to take a very non opinionated approach to enforcing a theme or specific colors.  Sometimes with android this is tricky but most controls attempt to just color themselves based on the defaults as specified by the android theme itself.


For example if you use the theme
*Theme.AppCompat.Light.DarkActionBar*
Then it'll be a light theme whereas if you use
*Theme.AppCompat*
Then it'll be a dark theme

But those are just features of Android and not features of Xamarin

I've attached a set of really simple projects below. One is using XF 2.3 and the other is using 3.1 and you can see that the picker in both look the same

![image](https://user-images.githubusercontent.com/5375137/45329384-68b26180-b51d-11e8-9fde-1dcc842d4ce6.png)

[ThemeTEst.zip](https://github.com/xamarin/Xamarin.Forms/files/2368740/ThemeTEst.zip)

If your color scheme is super wrong my recommendation would be to start with the android theme in your android project

**Comment by samhouts** [comment]
@FredyWenger  Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
