### ISSUE TITLE
[Feedback] Xamarin Forms Startup Time Slow

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3722]
### Description

- VS2107 (the one released Tuesday), only the CrossPlatform option installed (added UWP Xamarin support)<br>
- Create Cross Platform Project&gt;Single View using Xamarin Forms<br>
- (VS made projects for Android, iOS and UWP)<br>
- Switched to Release build.<br>
- Compiled and deployed to 3 real devices:<br>
- Samsung S7 (Startup time is 2 seconds)<br>
- LG Nexus 5 (Startup time is 3 seconds)<br>
- Asus Nexus 7 [2012] (Startup time is 4 seconds)<br>
The measured startup time for all of the above was measured by closing all previously started apps<br>
Then running the release build of the app manually on the phone and counting the time until the &quot;Welcome to Xamarin Forms!&quot;<br>
is displayed.<br>
Those times are totally unacceptable.<br>
To put this in perspective, Apple had a bit of a scandal when they first introduced their AutoLayout mechanism... it added<br>
150 milliseconds to the start time and developers were (quite reasonably in my view) upset. (Apple has since greatly improved things.)<br>
You've added 2000 to 4000 milliseconds to start time.<br>
But hey, what's an order of magnitude between friends! :-)<br>
____________<br>
Developer Community URL: <a href="https://developercommunity.visualstudio.com/content/problem/27969/xamarin-forms-startup-time-slow.html">https://developercommunity.visualstudio.com/content/problem/27969/xamarin-forms-startup-time-slow.html</a><br>
______________<br>

### Source

[395078](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/395078)

**Comment by charlesroddie** [comment]
Are there automated metrics of startup time? I have seen more useful info in the Xamarin forums giving both AOT and non-AOT startup times, but can't find the thread right now.

**Comment by 5yunus2efendi** [comment]
I think it's not just Xamarin.Forms what causes the startup time slow, it's also cause by Xamarin.Android (already filed an issue [here](https://github.com/xamarin/xamarin-android/issues/1802) and here the [project board](https://github.com/xamarin/xamarin-android/projects/8))

**Comment by MhAllan** [comment]
Too slow startup, any updates on this?

**Comment by LeonWhelan** [comment]
Hi, Any chance this is even being worked on? An update would be great.

**Comment by samhouts** [comment]
This has been a journey of a thousand steps, and we have more to go, I'm sure. But to answer your question, yes, we've been working on it. Here are some examples:

https://github.com/xamarin/xamarin-android/pull/2515
https://devblogs.microsoft.com/xamarin/faster-startup-times-with-startup-tracing-on-android/
https://devblogs.microsoft.com/xamarin/optimize-xamarin-android-builds/
https://devblogs.microsoft.com/xamarin/faster-android-startup-times-with-startup-tracing/
https://github.com/xamarin/Xamarin.Forms/pulls?q=is%3Apr+label%3Aa%2Fperformance

**Comment by mnxamdev** [comment]
We are trying to get a UWP app out the door using the Xamarin.Forms code we are using for our Android and iOS app. Startup time on UWP is absolutely terrible. We're talking 6-15 seconds of staring at a splash screen for an empty app! I hope this can be fixed soon.

**Comment by charlesroddie** [comment]
@mnxamdev are you testing in release mode (i.e. with an AOT build)?

On UWP we get debug mode from 6.5 to 3.5 seconds (getting less the more you open the app), release mode 2.2s on a complex app.

The strange thing is that if we time the creation of the `Xamarin.Forms.Application` where all of our code is, it's 1.8s in debug mode but only 0.25s in release mode. That means release mode saves 1.5s of time from our code, but doesn't save any time outside of that. Does that mean that the Xamarin.Forms platform code already AOTed even in debug mode but just very slow?

**Comment by mnxamdev** [comment]
> @mnxamdev are you testing in release mode (i.e. with an AOT build)?
@charlesroddie We are testing UWP in Release mode for x86 and x64 only. When you say AOT are you referring to the “Compile with .NET Native tool chain“ option for UWP? If not can you explain where that option is?

**Comment by mnxamdev** [comment]
For UWP is .Net Native Toolchain compilation the problem here? So what I figured out is if I set our UWP app to Release mode for x86 or x64 and unchecked .Net Native Toolchain and our app starts around 2 seconds but with it on I get app start in 6-8 seconds. From what I understand even if we uncheck that, the store will build with .Net Native Toolchain, is that correct?
https://forums.xamarin.com/discussion/81212/upload-uwp-to-the-windows-store-without-net-native

If Xamarin isn't looking to improve the startup time on UWP, some guidance here would be good.

**Comment by charlesroddie** [comment]
@mnxamdev AOT giving slower startup times is very unusual. I understand that it's time consuming to do but I think you'll have to get a reproduction. Worth a separate issue too.

**Comment by trampster** [comment]
We just spent some time trying to optimise the startup time of our app which using Xamarin.Forms and the shell
Here is what we have done
* Profiled startup tracing
* Compiled xaml
* Delayed most app initialization until after the UI is shown (we do nothing in App.OnStart/Activity.OnStart()
* IoC using a custom solution that doesn't use reflection

We seem to have run out of ways to speed it up.

Our startup time is 3 seconds till the UI is shown. Which honestly is not acceptable.

Are there any plans to address this?

**Comment by jfversluis** [comment]
That is awesome @azrinsani thanks for letting us know! I think we have taken steps to make this better, and we're putting in even more effort for .NET MAUI in this area. Thanks everyone for your time and effort on this and tips to make it better. Please keep adding those. Closing this one for now as there is not much work for us more to do here right now.
