### ISSUE TITLE
[iOS] Make the 5 click reset control gallery feature of iOS more explicit

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3724]
### Description

Currently on the control gallery in ios if you tap 5 times quick enough it causes the control gallery to reset. This feature is extremely helpful but can also be very confusing when testing things like gestures or just clicking buttons in general.

It would be useful to slightly modify this feature to lower the probability of the action matching up with testing procedures

Adding a way to disable this feature, pop open a dialog instead of auto restart, or  possibly isolate the clicking to a specific region.

**Comment by AndreiMisiukevich** [comment]
@PureWeen i suggest such way:
1) Add an attribute (**EscapeBackMainScreenAttribute(boold isEnabled)** for example)
2) Find top page (shown now)
3) 
Check whether EscapeBackMainScreenAttribute is set (and if true, check is it enabled == false), before calling Reset method. If both conditions are true - **return**; https://github.com/xamarin/Xamarin.Forms/blob/dd3ebdfa3b1b5a8bdac0d0f3ade529eb4aed2e90/Xamarin.Forms.ControlGallery.iOS/AppDelegate.cs#L174

@PureWeen @hartez any ideas?

**Comment by AndreiMisiukevich** [comment]
@PureWeen @hartez 
Hey guys, how about changing this feature
I propose to refuse using 5 times clicks at all. Perhaps it would be better to handle "Shake gesture" and do the same stuff after detecting "shake".

Any ideas?

**Comment by hartez** [comment]
I'd be fine with "shake", since we can activate that on simulators with a hotkey.
