### ISSUE TITLE
[GTK] TableView doesn't appear to be updating when you remove and add new Table Sections

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3725]
### Description
When running the Xamarin Forms Control Gallery for GTK the test cases screen doesn't appear to update it's view as you try to filter down issues

The list of issues is updated by removing and adding a new Section
```C#
	_section = new TableSection("Bug Repro");

				foreach (var issueCell in issueCells) {
					_section.Add (issueCell);
				} 

				Root.Add(_section);
```
But those changes don't seem to propagate visually

### Steps to Reproduce

1.  Run Xamarin.Forms.ControlGallery.GTK
2. Click go to test cases
3. type things into the SearchBar
4. you'll notice that the list of issues doesn't update like it does on the other platforms

### Expected Behavior
the list of issues should filter down based on the input

### Actual Behavior
They don't filter down

### Basic Information

- Version with issue: 3.2
- Last known good version: not sure

### Screenshots

![image](https://user-images.githubusercontent.com/5375137/45122405-f27abd00-b120-11e8-867f-a243de1c6d87.png)

vs

![image](https://user-images.githubusercontent.com/5375137/45122419-fc9cbb80-b120-11e8-922e-96614d40bddc.png)

**Comment by jsuarezruiz** [comment]
I will take a look!

**Comment by jsuarezruiz** [comment]
I sent a PR.
![3725](https://user-images.githubusercontent.com/6755973/46245149-963a4e80-c3e9-11e8-9f36-43ef62e3b157.gif)
