### ISSUE TITLE
[WPF] Additional OnAppearing when using Navigation.PushAsync

### ISSUE THREAD

**Issue by MartinWegner** [xamarin/Xamarin.Forms#3726]
### Description
Switching between Contentpages with Navigation.PushAsync causes an additional set of functioncalls to OnAppearing and OnDisappearing. The back Button has the same issue. This seems to be specific to WPF.

### Steps to Reproduce

1. Download ReproCase
2. Start app and click "Nav" Button
3. Watch the console output window

### Expected Behavior
BoxViewClock.MainPage Void OnDisappearing()
BoxViewClock.Page1 Void OnAppearing()

### Actual Behavior
BoxViewClock.MainPage Void OnDisappearing()
BoxViewClock.MainPage Void OnAppearing()
BoxViewClock.Page1 Void OnAppearing()
BoxViewClock.MainPage Void OnDisappearing()

### Basic Information

- Version with issue: 3.2.0.729530-pre2 + 3.1.0.697729 (Latest stable and Latest prerelease)
- Last known good version: none
- IDE: Microsoft Visual Studio Enterprise 2017 Version 15.8.0
- Platform Target Frameworks: 
  - WPF:  4.7
- Nuget Packages:
NETStandard.Library                 {2.0.3}                                  BoxViewClock                                                                                                                                 
Xamarin.Forms                       {3.2.0.729530-pre2}                      BoxViewClock                                                                                                                                 
OpenTK                              {3.0.1}                                  BoxViewClock.WPF                                                                                                                             
OpenTK.GLControl                    {3.0.1}                                  BoxViewClock.WPF                                                                                                                             
WpfLightToolkit                     {1.0.3}                                  BoxViewClock.WPF                                                                                                                             
Xamarin.Forms                       {3.2.0.729530-pre2}                      BoxViewClock.WPF                                                                                                                             
Xamarin.Forms.Platform.WPF          {3.2.0.729530-pre2}                      BoxViewClock.WPF         

### Reproduction Link
[ReproCase_DoubleOnAppearing.zip](https://github.com/xamarin/Xamarin.Forms/files/2355793/ReproCase_DoubleOnAppearing.zip)

**Comment by pauldipietro** [comment]
Thank you for the reproduction which displays the behavior.

**Comment by mohachouch** [comment]
@samhouts Bug not reproduced on the latest version. I think the PR # 3372 to fix this bug.
