### ISSUE TITLE
Editor Border

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3727]
Hi,

Please add a border to Editor control..

Currently the Editor shows on iOS without border so we have to keep it inside a Frane but it will be easier if you add the border property or feature.

Thanks,
Jassim

**Comment by jfversluis** [comment]
Seems like a duplicate of #3369

**Comment by sebastianfilke** [comment]
Yeah, this bug is annoying.  Is there any plan to fix it soon?

![image](https://user-images.githubusercontent.com/10894484/52778664-d02d8980-3046-11e9-86d0-a8556dad3965.png)

**Comment by titoleru** [comment]
This should be an easy implementation and it would be really handy!!! This is a huge bug of a property not only behaving differently in Android and iOS, but also behaving differently in entries and editors in iOS itself

**Comment by jfversluis** [comment]
Don't think we will fix this for Forms anymore. Make sure to check how it works for .NET MAUI and see if we can better align it there. Thanks!
