### ISSUE TITLE
Animated Splash Screen

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3729]
Hi,

Is the any plan to add an option which allows animated splash screen for iOS, Android and UWP?

Thanks
Jassim

**Comment by adrianknight89** [comment]
@jrahma As far as I'm aware, there is no such thing as an animated splash screen (other people can correct me on this). You can, however, put up a static image like @GalaxiaGuy suggested and then run an animation to trick people into thinking they are looking at an animated splash screen. Maybe, [LottieXamarin](https://github.com/martijn00/LottieXamarin) can be of good use for this purpose.

**Comment by jrahma** [comment]
Keep in mind this should also provide an option to set the a splash screen for light mode and another splash screen for dark mode so all what user needs to do is just to select the image / video for each mode
