### ISSUE TITLE
Grid.Row and Grid.Column IsVisible

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#3732]
Hi,

Please add IsVisible to Grid.Row and Grid.Column instead of setting the Height to 0 or -1

Thanks,
Jassim

**Comment by andreinitescu** [comment]
Can't you just set the `IsVisible` to `false` on the content inside the row/column?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
