### ISSUE TITLE
[Feedback] Xamarin UWP screen orientation lock not working

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3735]
### Description

<p>Microsoft's documentation says that setting the supported rotations in Package.appxmainifest should lock the app's orientation, but that is not working for me.

I have it set to Landscape and Landscape-Flipped, but my app still rotates freely.

* The app is written using Xamarin Forms 3.0.0.452510
* I am using Microsoft.NetCore.UniversalWindowsPlatform version 6.1.4
* I am running Visual Studio 15.7.4
* I am deploying to a Surface Pro 4 running Windows 10 version 1709 (Fall Creators Update)
* The surface is set to tablet mode only - although the setting to notify on change is set.  There have been no notifications
* There are also iOS and Android versions of my app, they work as desired.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/288903/xamarin-uwp-screen-orientation-lock-not-working.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/644587">original linked feedback ticket</a>.

### Source

[678652](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678652)

**Comment by PureWeen** [comment]
This isn't related to forms
It's UWP specific

There are a few questions about this
https://stackoverflow.com/questions/48326750/xamarin-forms-uwp-how-to-lock-app-to-landscape-orientation

that seem to indicate that you can't really lock it in all cases
