### ISSUE TITLE
[Feedback] Unable to change window border in Xamarin Forms WPF

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3736]
### Description

<p>We can neither change the border color of th main window nor remove the border in Xamarin Forms WPF.

We tried to set the XAML properties natively and also to set the window properties programmatically. Nothing changes the window border, which is always blue in our case.

XAML

&lt;wpf:FormsApplicationPage x:Class=&quot;Client.WPF.MainWindow&quot;
        xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot;
        xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot;
        xmlns:local=&quot;clr-namespace:Client.WPF&quot;
        xmlns:wpf=&quot;clr-namespace:Xamarin.Forms.Platform.WPF;assembly=Xamarin.Forms.Platform.WPF&quot;
        mc:Ignorable=&quot;d&quot;
        Height=&quot;450&quot; Width=&quot;800&quot; 
        Background=&quot;#455A64&quot;
        WindowStyle=&quot;None&quot; 
        ResizeMode=&quot;NoResize&quot;
        AllowsTransparency=&quot;True&quot;
        BorderBrush=&quot;#000000&quot;
        BorderThickness=&quot;0&quot;
        WindowState=&quot;Maximized&quot;
        &gt;
&lt;/wpf:FormsApplicationPage&gt;

Code:
this.WindowStyle = System.Windows.WindowStyle.None;
            App.Current.MainWindow.AllowsTransparency = true;
            App.Current.MainWindow.BorderBrush = new SolidColorBrush(System.Windows.Media.Color.FromRgb(255,0,0));
            App.Current.MainWindow.BorderThickness = new System.Windows.Thickness(0);</p>
<a href="https://developercommunity.visualstudio.com/content/problem/279579/unable-to-change-window-border-in-xamarin-forms-wp.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/637660">original linked feedback ticket</a>.

### Source

[678650](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678650)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ZeProgFactory** [comment]
In wich version it will be implemented? 
With Xamarin.Forms 4.1.0.555618
and Xamarin.Forms.Platform.WPF 4.1.0.555618
it still doesn't work.
