### ISSUE TITLE
[Feedback] Xamarin Forms custom renderer for DatePicker and TimePicker not working for UWP

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3739]
### Description

<p>I have a Xamarin forms project that supports UWP, iOS, and Android.  I have custom renderers for many controls including the DatePicker and the TimePicker.

The customer renderers work just fine on iOS and Android.  On UWP, the renderers run just fine, but setting Control.BorderBrush and Control.BorderThickness has no effect.

See the attached screenshots for the code I'm using as well as the output.  You can see other controls in the image whose rendering is controlled by custom renderers.  I also have a regular picker (not pictured) that works fine as well. 

The picker isn't in the screenshot, but I do have the code in the screenshot.</p><p><br></p><span class=text style="box-sizing:border-box;color:rgb(33, 33, 33);display:inline-block;font-size:14px;font-style:normal;font-variant:normal;font-weight:400;letter-spacing:normal;margin-left:0.9em;orphans:2;text-align:left;text-decoration:none;text-indent:0px;text-transform:none;white-space:normal;word-spacing:0px;"><p style="box-sizing:border-box;display:inline;margin-bottom:0.5em;margin-left:0px;margin-right:0px;margin-top:0px;">I uploaded a sample.  You can get it at https://www.dropbox.com/s/nuhm596kkewkph3/UwpRenderer.zip?dl=0 </p><p>
</p></span><p><b></b><i></i><u></u><sub></sub><sup></sup><strike></strike><br></p>
<a href="https://developercommunity.visualstudio.com/content/problem/240063/xamarin-forms-custom-renderer-for-datepicker-and-t.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/606198">original linked feedback ticket</a>.

### Source

[678635](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678635)

**Comment by pauldipietro** [comment]
Sample link has a 404

**Comment by samhouts** [comment]
Unfortunately, the reproduction link appears to be expired. If anyone is able to provide a reproduction of this issue, please feel free to reopen this issue and attach it. Thank you!

**Comment by hauteur** [comment]
For some reason, I didn't see the notifications when you guys responded.  I uploaded a new reproduction.  Please let me know if you have any issues getting to it.

https://www.dropbox.com/s/8sr1jkpwaqs0b97/DatePickerBorder.zip?dl=0
