### ISSUE TITLE
[UWP] Xamarin forms entry buffering on fast keyboard entry

### ISSUE THREAD

**Issue by Gilbertvan** [xamarin/Xamarin.Forms#3755]
### Description
A xamarin forms page with simple entry component, type very fast, on UWP you will see characters are not being displayed, but will be displayed when subsequently entering keys.

### Steps to Reproduce

1. Create standard xamarin app with visual studio from template
2. put entry component on mainpage.xaml
3. deploy on windows device (tested on atom z2*** and z8*** family)

### Expected Behavior
expected to see all entered characters

### Actual Behavior
slowly showing buffered characters.

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0697729
- Last known good version: ??
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - iOS:  works fine
  - Android: works fine
  - UWP:  W10 pro 1803 build 17134
- Android Support Library Version: 
- Nuget Packages: All standard from visual studio template
- Affected Devices: Atom Z2*** and Z8*** family tablets.

**Comment by Gilbertvan** [comment]
after playing with this a bit more :
- dismissing the on screen keyboard makes all the text appear.
- only appears when debugging the application

**Comment by PureWeen** [comment]
@Gilbertvan  I tested this with a YOGA 2 and I didn't see the issue

Can you test this phenomenon with a native UWP app? I'm just curious if this is more ea UWP level issue then a Forms one.  

We don't really "buffer" input as it is typed in UWP. The text is just going straight into the native control

**Comment by PureWeen** [comment]
Yes, I would log it here
https://developercommunity.visualstudio.com/spaces/8/index.html
