### ISSUE TITLE
[iOS] SafeAreaInsets is difficult to use correctly - not knowing when it changes

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#3757]
The `UseSafeArea` platform specific is easy to use and works well. But for more advanced scenarios when you want to use `SafeAreaInsets`, there are problems.

There does not seem to be a way to know when it changes. This is a big problem for an app that supports rotation.

As a subset of this, I'm also not sure when it is first set. In the first call to a page's `OnSizeAllocated` method for instance it does not appear to be set.

On an app I worked on that didn't support rotation, it was easy to work around. We had a splash page (that didn't care about the safe area itself) that would grab the insets in `OnAppearing` and put them in the app resources. Other pages could then use them where appropriate. That's no longer a solution for an app supporting rotation.

I'm not sure what the solution should be. One possibility would be to make the safe are a property on `ContentPage` instead of being a platform specific (especially since something will have to be done about Android P's display cutouts).

**Comment by PureWeen** [comment]
I think I follow your description
You can bind to those platform specifics

```XAML
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Triage.Page1"     
			 xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
			 ios:Page.UseSafeArea="true"
			 ios:Page.SafeAreaInsets="{Binding Test, Mode=OneWayToSource}"
			 >
	<ContentPage.Content>
		<StackLayout>
			<Label Text="Welcome to Xamarin.Forms!"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
		</StackLayout>
	</ContentPage.Content>
</ContentPage>
```

And once that is setup you'll get the thickness of the SafeAreaInset once it changes.
If I'm not matching up with your description can you attach a repro so I can see where you are having difficulties.

**Comment by GalaxiaGuy** [comment]
Actually, I think that will do exactly what I need. I was looking for a way to listen for changes directly. This way I can bind it to something and listen for changes to that.

Thanks.
