### ISSUE TITLE
System.IndexOutOfRange: Index was outside the bounds of the array at Mono.Cecil.MetadataReader.ReadLocalConstant

### ISSUE THREAD

**Issue by GeoffreyFook** [xamarin/Xamarin.Forms#3760]
### Description

I am unable to debug my application. I am getting an "IndexOutOfRangeException" whenever the debugger hits one of my break points in android. The problem seems to go away if I avoid using linq or keep my code extremely simple. 

For example:
```
if(someVariable == true)  ---> this does not break.
{

}

```
instead of
```
if(someVariable) ----> This does.
{
}

```
### Steps to Reproduce

I am unsure on the steps to reproduce this. I am running an emulator using haxm (I have tried multiple), Android 8.1 as target framework. Xamarin.forms version 3.1.0.697729.

### Basic Information

- Version with issue:
- Last known good version: Unsure
- IDE: Visual studio 2017
- Platform Target Frameworks: 

  - Android: 8.1

- Android Support Library Version: 
- Nuget Packages: 

Auth0.Oidc.Client.Android v2.3
Plugin.CurrentActivity 2.1.04
sqlite-net-pcl: 1.4.188
Xam.Plugin.Geolocator: 4.5.0.6
Xam.Plugin.Media: v4.0.1.5
Xam.Plugins.Forms.ImageCircle: v.3.0.0.5
Xamarin.Android.Support.Design: v.27.0.2.1
Xamarin.Android.Support.v4: v27.0.2.1
Xamarin.Android.Support.v7.AppCompat: v27.0.2.1
Xamarin.Android.Support.v7.CardView: v.27.0.2.1
Xamarin.Android.Support.v7.MediaRouter: v.27.0.2.1
Xamarin.Forms: v3.1.0.697729
Xamarin.Forms.Maps: v2.5.0.077107
Xamarin.GooglePlayServices.Maps: v60.1142.1
Xamarin.GooglePlayServices.Places: v60.1142.1
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/39644464/45380056-08492000-b602-11e8-9ccd-4ab1b7e7e8e7.png)

**Comment by samhouts** [comment]
@GeoffreyFook Since we haven't heard from you in more than 30 days, we hope that this issue is no longer affecting you. If it is, please feel free to reopen this issue and provide the requested information. Thank you for your report!
