### ISSUE TITLE
When selecting a button from a cell in a list and changing the color of this button, strange behavior occurs on the seventh cell 

### ISSUE THREAD

**Issue by UniomTeam** [xamarin/Xamarin.Forms#3768]
### Description
When selecting a button from a cell in a list and changing the color of this button, strange behavior occurs, where the seventh cell with another component button also receives color change or even change in the text itself. I understand that a cell should not have its behavior altered content / button when another cell has its button clicked.
### Steps to Reproduce

1. Create List View with datas and a button into then
2. Click on button and change your color after that
3. You see the seventh/others cells background color change too

### Expected Behavior
Click button and change a crown only in your own cell
### Actual Behavior
Clicking on button of cell changes properties of another cell
### Basic Information
- Version with issue: All
- Last known good version: All
- IDE: VS 2017 for Mac with Xamarin Forms
- Platform Target Frameworks: 
  - iOS:  greater than iOS 10.3
  - Android: greater than Android 5.1
  - UWP:  no
- Android Support Library Version: no applicable
- Nuget Packages: no applicable
- Affected Devices: no applicable

## Button Cell Clicked
![image](https://user-images.githubusercontent.com/34030072/45425469-d8d0fc80-b66f-11e8-9eef-b9ea29589634.png)
## Button Seventh Cell behavior Issue
![image](https://user-images.githubusercontent.com/34030072/45425488-e4242800-b66f-11e8-9c18-4573f5b320d1.png)

### Reproduction Link
https://drive.google.com/open?id=1SlKnGOE-zz7ZLW9Tno4tUfVEzRC08r0L

**Comment by PureWeen** [comment]
@UniomTeam  can you attach a sample of how you are changing the background color?
Since listviews use templates it's usually best to set things like background color via bindings otherwise you will effect the template itself.

I'm guessing you are using recycle as well so my guess is that you are effecting the template manually opposed to using bindings

[ListVIewColoring.zip](https://github.com/xamarin/Xamarin.Forms/files/2375428/ListVIewColoring.zip)

**Comment by UniomTeam** [comment]
[ListTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2376251/ListTest.zip)
@PureWeen here one example of code.

**Comment by PureWeen** [comment]
@UniomTeam  right

You're basically modifying the template directly when you do this
```
        public void AddList(object sender, EventArgs args)
        {
            Button buttonCount = (Button)sender;
            Button _btnLike = buttonCount.Parent.FindByName<Button>("WideButton1");
            _btnLike.BackgroundColor = Color.Blue;
           
        }
```

Forms attempts to reuse the controls as much as possible in a listview in order to optimize for performance.

If you want to modify the BackgroundColor based on row changes then you need to control that through binding

```XAML
<Button  Grid.Row="1" Grid.Column="0" x:Name="WideButton1" 
                                     CommandParameter="{Binding .}" 
                                     TextColor="White" 
                                     HorizontalOptions="Center" 
                                     Clicked="AddList"
                                     WidthRequest="225" 
                                     HeightRequest="30"
                                     FontSize="12" Text="My Button" BackgroundColor="{Binding SomeValue}" />
```

And then if you need to you can use a ValueConverter to convert that Value to what color you want it to represent

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters

**Comment by PureWeen** [comment]
@UniomTeam  

MVVM + https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters

```XAML
<Button  Grid.Row="1" Grid.Column="0" x:Name="WideButton1" 
                                     CommandParameter="{Binding .}" 
                                     TextColor="White" 
                                     HorizontalOptions="Center" 
                                     Clicked="AddList"
                                     WidthRequest="225" 
                                     HeightRequest="30"
                                     FontSize="12" Text="My Button" BackgroundColor="{Binding SomeValue,
                                    Converter={StaticResource valueToColor}}" />
```

```C#
public class ValuetoColorConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
    {
       if(value == something)
            return Color.Pink;

       return Color.Black

    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        throw new not ImplementedException()
    }
}
```

If it's still not quite clear I'd recommend posting a question to StackOverflow
