### ISSUE TITLE
[WPF] ListView.Header not being rendered

### ISSUE THREAD

**Issue by kfreezen** [xamarin/Xamarin.Forms#3770]
### Description
ListView.Header does not render with Xamarin.Forms.Platform.WPF.

### Steps to Reproduce

1. Download attached reproduction project
2. Build and run ListViewBug.WPF (can compare with ListViewBug.UWP to see difference)

### Expected Behavior
ListView header should show two columns named "Column1" and "Column2". Nothing shows up.

### Actual Behavior
ListView header does not show at all on WPF project.

### Basic Information

- Version with issue: 3.2.0.809874-pre (and 3.1.0.697729)
- Last known good version: N/A
- IDE: VS2017 Community
- Platform Target Frameworks: 
  - UWP:  16299
  - WPF
- Affected Devices: Windows Classic Desktop

### Screenshots
WPF:
![image](https://user-images.githubusercontent.com/346924/45443007-93252b80-b691-11e8-963d-18cc1ecf91fa.png)

UWP:
![image](https://user-images.githubusercontent.com/346924/45443122-d2ec1300-b691-11e8-8bcf-f97983430e69.png)

### Reproduction Link
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2376261/ListViewBug.zip)

**Comment by alex-relov** [comment]
![image](https://user-images.githubusercontent.com/26199529/60739497-9ae4f200-9f7b-11e9-94f4-2ec4617fa3b6.png)
![image](https://user-images.githubusercontent.com/26199529/60739522-afc18580-9f7b-11e9-9aa2-d64d2662a1fc.png)
4.1.0.555618
similar problem, there is a header in uwp, but it is missing in wpf. XF 4.1.0.555618
