### ISSUE TITLE
[Android] FormattedText not being rendered

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#3772]
### Description

FormattedText is not being rendered on Android

### Steps to Reproduce

1. Go to test 3525

### Expected Behavior

all text should show

### Actual Behavior

some of the text is not shown
### Basic Information

- Version with issue:master branch
- Last known good version: 3.2

### Screenshots

![simulator screen shot - iphone x - 2018-09-12 at 19 53 53](https://user-images.githubusercontent.com/1235097/45447016-490a6d00-b6c6-11e8-8921-9e55c4235e39.png)
![screenshot_1536778312](https://user-images.githubusercontent.com/1235097/45447018-490a6d00-b6c6-11e8-8598-dd31fc30f61c.png)

### Reproduction Link

3525 on the Gallery

**Comment by adrianknight89** [comment]
I think the fix for this and #3883 should be released together.
