### ISSUE TITLE
Add Reload method to WebView

### ISSUE THREAD

**Issue by yinchengvy** [xamarin/Xamarin.Forms#3776]
### Description
Native WebView have reload function. And I can use it  after loaded url failed.
But Xamarin.Forms WebView has no reload function.
And how can I reload WebView on Xamarin.Forms?

**Comment by PureWeen** [comment]
@yinchengvy  If you re-assign the existing URL the page will reload with that url but there's not a way right now to call Reload on the webview

All the underlying controls have a reload feature so you could use a custom renderer to set this up. It would be a good idea for us to surface the Reload methods into Forms
