### ISSUE TITLE
Dark mode on Mojave doesn't work right

### ISSUE THREAD

**Issue by jimbobbennett** [xamarin/Xamarin.Forms#3777]
### Description

When using Dark Mode on Mojave, controls are unusable due to the way they are drawn (for example no visible text on buttons).

### Steps to Reproduce

1. Create a macOS Forms app.
2. Run it on macOS Mojave (beta)
3. 

### Expected Behavior

Apps should be usable

### Actual Behavior

Parts of the controls are not visible

### Basic Information

- Version with issue: 3.1.0.697729
- Last known good version: None
- IDE: VS for Mac
- Platform Target Frameworks:
  - macOS
- Affected Devices: macOS running Mojave

### Screenshots

Light mode:

<img width="572" alt="light" src="https://user-images.githubusercontent.com/1710385/45482821-fa50e780-b746-11e8-9aa1-f78cc20a5099.png">

Dark Mode:

<img width="572" alt="dark" src="https://user-images.githubusercontent.com/1710385/45482838-03da4f80-b747-11e8-9807-cc717c4ffb8c.png">

### Reproduction Link

https://github.com/jimbobbennett/SqueakyAppLinuxAndMac

**Comment by jvansickle** [comment]
A workaround for this is to add "NSRequiresAquaSystemAppearance" with "Yes" in your Info.plist. This will set the application to disregard the "Dark Mode" of the OS.

**Comment by sergey-tihon** [comment]
`Disregard the Dark mode` is the Fix? really?
Is proper dark mode support planned?

**Comment by sergey-tihon** [comment]
Discussed this with @migueldeicaza today:
It may worth to think about proper support of Dark mode
