### ISSUE TITLE
[Android] WebView Navigating event not always fired

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#3778]
### Description

In the Android WebViewRenderer, the Navigating event is fired from the `ShouldOverrideUrlLoading(AWebView view, string url)` method in the WebClient, which seems to get hit when the original URL is redirected or navigation occurs from the initial URL, but not when the original URL begins loading. (This method was also deprecated in API level 24 and replaced with `ShouldOverrideUrlLoading(AWebView webView, WebResourceRequest request)` .)

The WebClient should instead override the `OnPageStarted` method and fire the Navigating event there, for consistency with firing the Navigated event from `OnPageFinished`. This method is hit for initial loads, redirects, and subsequent navigations.

I also believe that WebClient should be moved from a private inner class of the WebViewRenderer to a public class, so that custom renderers can subclass it to inject custom WebViewClients without having to re-implement firing of all the WebView events.

https://forums.xamarin.com/discussion/138821/navigating-on-android-webview-doesnt-always-fire

### Steps to Reproduce

1. Add a WebView to a page in a Xamarin.Forms project
2. Register for the Navigating event of the WebView
3. Set the source to a UrlWebViewSource that will not redirect (e.g. https://www.google.com)
4. Run on an Android device

[WebViewAndroid.zip](https://github.com/xamarin/Xamarin.Forms/files/2380442/WebViewAndroid.zip)

### Expected Behavior

The Navigating event will be fired when the WebView begins loading google.com.

### Actual Behavior

The Navigating event is not fired.

### Basic Information

- Affected Devices: Android

**Comment by samhouts** [comment]
closed by #3780

**Comment by jws2103** [comment]
Hi @samhouts ,

Is this issue actually fixed?

I was able to replicate this issue on the latest Xamarin forms (3.6.0.293080).

This is only happening on Android.

So the steps to replicate are
1. Create a new Xamarin Project
2. Add a webview
3. Subcribe Navigating event

Expected:
- Navigating event fires every time webview url changes

Actual:
- Navigating event fires only once

Can you please re-open this issue if it's not fixed yet?

If there're any workarounds, it would be great to share.


Kind Regards,
Jay
