### ISSUE TITLE
[Android] Scaling broken on Android

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3781]
### Description
Scaling isn't being applied correctly on Android

### Steps to Reproduce

Run the following sample
https://github.com/xamarin/xamarin-forms-samples/blob/master/XamlSamples/XamlSamples/XamlSamples/StaticConstantsPage.xaml

### Expected Behavior
Look at screen shot below. Both of them should look like 3.1

### Actual Behavior
3.2 is scaling incorrectly

### Basic Information

- Version with issue: 3.2
- Last known good version: 3.1
- Platform Target Frameworks: 
  - Android: 8.1

### Screenshots

![image](https://user-images.githubusercontent.com/5375137/45516698-2ed59b00-b769-11e8-9b68-763784234279.png)

### Reproduction Link

Run the following sample
https://github.com/xamarin/xamarin-forms-samples/blob/master/XamlSamples/XamlSamples/XamlSamples/StaticConstantsPage.xaml

**Comment by StephaneDelcroix** [comment]
We (@jassmith and I) suspect it's related to scaling the new Corners for the BoxView.

I'm quickly trying to confirm that hypothesis and then make sure the scaling is correct when no corner radius is set.

**Comment by StephaneDelcroix** [comment]
@PureWeen I can not reproduce that behavior on this (physical) pixel 2

**Comment by samhouts** [comment]
Closed by #3786
