### ISSUE TITLE
Xamarin forms symbol server

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#3783]
Before I can submit my bug I need to debug Xamarin.Forms to see where in Forms the Code it’s failing.

In VS2017 how do I configure the ability to debug Xamarin Forms Code . my app running is Xamarin Forms 3.1

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/2222
https://blog.xamarin.com/debugging-xamarin-forms/
