### ISSUE TITLE
Xamarin Forms 3 not working with Android 4.1

### ISSUE THREAD

**Issue by FetFrumos** [xamarin/Xamarin.Forms#3785]
I need to run my app(Xamarin Forms 3.1) on the device with Android  4.1. 
The requirements(official documentation) are written: "Android 4.0.3 (API 15) or higher". But XF 3.1 does not work on versions lower than 4.4. I get this error:

 09-13 18:05:37.752 E/AndroidRuntime(10979): FATAL EXCEPTION: main
 09-13 18:05:37.752 E/AndroidRuntime(10979): java.lang.UnsatisfiedLinkError: Couldn't load monodroid: findLibrary returned null
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at java.lang.Runtime.loadLibrary(Runtime.java:365)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at java.lang.System.loadLibrary(System.java:535)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:34)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:22)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread.installProvider(ActivityThread.java:4560)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread.access$1300(ActivityThread.java:130)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.os.Handler.dispatchMessage(Handler.java:99)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.os.Looper.loop(Looper.java:137)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at android.app.ActivityThread.main(ActivityThread.java:4745)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at java.lang.reflect.Method.invokeNative(Native Method)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at java.lang.reflect.Method.invoke(Method.java:511)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 09-13 18:05:37.752 E/AndroidRuntime(10979):    at dalvik.system.NativeStart.main(Native Method)

What is the minimum version of the android for XF 3.0? Which version of Xamarin Forms supports android 4.1?

**Comment by PureWeen** [comment]
@FetFrumos   Can you attach a repro?

I did a little bit of testing and it looks like Xamarin Forms is indeed broken for API 15 but it works for me with API 16

**Comment by PureWeen** [comment]
Also @FetFrumos  can you speak to why you're needing to run forms on Android 4.1 ? 
We're looking at possibly raising the minimum API in the future so I'm just curious about your use case

**Comment by FetFrumos** [comment]
This is the customer's requirement. There are people who use old devices.

**Comment by StephaneDelcroix** [comment]
No attached project in a month. closing. reopen when you have a repro project to attach
