### ISSUE TITLE
[Android] Xamarin Forms currently doesn't work on API 15

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3787]
### Description
Control.TrackDrawable, Control.LineSpacingMultiplier, and _view.LineSpacingExtra
Are only available on API 16

### Steps to Reproduce
1.  Run the Xamarin Forms Control Gallery

### Expected Behavior
Control Gallery should run on API 15

### Actual Behavior
Control Gallery crashing on API 15

### Basic Information

- Version with issue: 3.2
- Last known good version: 3.0
- IDE:
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by kingces95** [comment]
Like the man says, "Android 4.4 (API 19) or higher." So... close?
