### ISSUE TITLE
[Android] MasterDetail default text style accessibility

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#3796]
Google now detects accessibility issues with applications in its pre-launch testing.

The default style for labels and background was detected as low contrast, a ratio of 4.46 (#6D6D6D font vs #EEEEEE background), and recommends a ratio of at least 4.5 for small text, 3.0 for large text.

Suggest background be made a bit brighter or text a bit darker by default. (e.g. TitleStyle, BodyStyle)

**Comment by rmarinho** [comment]
Do you have a example @BioTurboNick ? is this only for the MDP ?

**Comment by rmarinho** [comment]
I tried the Accessibility Scanner and I did't saw any complains. Are you using AppCompact version ?

**Comment by BioTurboNick** [comment]
I'm using FormsAppCompatActivity, if that's what you mean. I haven't run the scanner in a while though, it's also possible they adjusted it to not complain for small deviations.

**Comment by rmarinho** [comment]
If you could check again and provide a repo that would be great. I have test with the styles you refer on a Page with MDP and I don't see warnings from the Accessibility scanner. 

Please provide any additional steps you took to get those warnings.

Thanks

**Comment by BioTurboNick** [comment]
Confirmed, no longer an issue. Closing.
