### ISSUE TITLE
Xamarin Forms ButtonRenderer Crashes on Android 6

### ISSUE THREAD

**Issue by RvDillen** [xamarin/Xamarin.Forms#3800]
### Description
Xamarin Forms 3.1 App crashes at start up on ButtonRenderer.
Issue happens only on Android 6. 
On Android 4, 7 and 8 the error does not occur.

### Steps to Reproduce

1. StartUp Application. 
2. App crashes already in MainActivity.OnCreate (Caused by ButtonRenderer)
3. 

### Expected Behavior
No Crash

### Actual Behavior
Crash

### Basic Information

- Version with issue: Xamarin Forms 3.1.0.697792
- Last known good version: 2.3.4
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android 6 Only (Android 4, 7,8 have no problems): 
  - Android Support Library Version:  25.4.0.2
  - Affected Devices : Sumsung XCover 3 VE

### Reproduction Link

[StackTrace Crash ButtonRenderer on Android 6.txt](https://github.com/xamarin/Xamarin.Forms/files/2387988/StackTrace.Crash.ButtonRenderer.on.Android.6.txt)

**Comment by RvDillen** [comment]
**Update Issue:**
Can not send actual project where crash happens, but dowloaded xamarin forms sdk and debugged situation. Crash happens in method:
ButtonBackgroundTracker.UpdateDrawable()

if (Forms.IsLollipopOrNewer)
{
	var rippleColor = _backgroundDrawable.PressedBackgroundColor.ToAndroid();
	_rippleDrawable = new RippleDrawable(ColorStateList.ValueOf(rippleColor),backgroundDrawable, null);
	_nativeButton.SetBackground(_rippleDrawable);
}
else
{
	_nativeButton.SetBackground(_backgroundDrawable);
}

Call: _nativeButton.SetBackground(_rippleDrawable) causes crash (see new stacktrace)

**WorkAround:**
As as work around I created a local ButtonBackgroundTracker class and replaced statement
(Forms.IsLollipopOrNewer) => (OS.Build.VERSION.SdkInt > OS.BuildVersionCodes.M)
cause android M has no problems.

[StackTrace BackgroundTracker on Android 6.txt](https://github.com/xamarin/Xamarin.Forms/files/2441974/StackTrace.BackgroundTracker.on.Android.6.txt)

**Comment by RvDillen** [comment]
Sorry, item is not closed, just want to add extra info.

**Comment by RvDillen** [comment]
@PureWeen Just checked our project with Forms 3.2.0.871581.
Situation is the same as Forms 3.1: Crash on Android 6 (not 7).
 Stacktrace is identical.

Op wo 3 okt. 2018 om 18:23 schreef Shane Neuville <notifications@github.com

**Comment by hartez** [comment]
@RvDillen What properties are set on the button that's causing the crash?

**Comment by RvDillen** [comment]
The button properties are:

    <Button  x:Name ="svgButton"
        BindingContext="{x:Reference gridButton}"
        BackgroundColor="Transparent"
        Command="{Binding Command}"
        CommandParameter="{Binding CommandParameter}"/>

**Comment by RvDillen** [comment]
The button properties are:

    <Button  x:Name ="svgButton"
        BindingContext="{x:Reference gridButton}"
        BackgroundColor="Transparent"
        Command="{Binding Command}"
        CommandParameter="{Binding CommandParameter}"/>

**Comment by RvDillen** [comment]
The button properties are:

    <Button  x:Name ="svgButton"
        BindingContext="{x:Reference gridButton}"
        BackgroundColor="Transparent"
        Command="{Binding Command}"
        CommandParameter="{Binding CommandParameter}"/>


Op vr 19 okt. 2018 om 05:50 schreef E.Z. Hart <notifications@github.com>:

**Comment by PureWeen** [comment]
@RvDillen  looking at your stack trace I see that you are using a custom renderer

```
  at Xamarin.Forms.Platform.Android.ButtonRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x000a5] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ButtonRenderer.cs:117 
  at MedicMessenger.Droid.Render.FeedbackButtonRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00001] in C:\Source\A_Forms_3.1\1191_medical_messenger\MedicMessenger.Android\Render\FeedbackButtonRenderer.cs:28 
```

If you disable that custom renderer do you still get the same exception? 

It also looks like you are using a Non App Compat renderer. Is your Android project Not updated to App Compat? I would be curious to see if you are getting the same exception after updating the project to App Compat.

**Comment by RvDillen** [comment]
@PureWeen

The crash is not caused by the custom renderer. 
I already tried a default button with several Renderers

1) Android.ButtonRenderer
2) Android.AppCompat.ButtonRenderer
3) Android.FastRenderers.ButtonRenderer

Behaviour is the same for all Renderers:
Crash on Android 6 (only) happens in method "ButtonBackgroundTracker.UpdateDrawable()"

Call: "_nativeButton.SetBackground(_rippleDrawable)" 
causes crash (see 2e stacktrace)

**Comment by PureWeen** [comment]
@RvDillen  can you create a repro by chance? 
Maybe take your project as it is and shrink down parts? Or possibly you can send it to me privately? shneuvil at microsoft.com?

I've tried what you've posted in the comments and I'm not running into this issue so I feel like there's some project configuration you have that's triggering it. Possibly something from your styles? or sdk settings? or other?

**Comment by RvDillen** [comment]
Sample project is send to @PureWeen

**Comment by PureWeen** [comment]
Confirmed this only appears to crash on 6.0

**Comment by PureWeen** [comment]
@RvDillen  so I think something about the style you are applying to buttons in the

values-v21\styles.xml 

Isn't playing nicely with RippleDrawable

If I comment out the style you have in there setup for Button then it doesn't crash.

**Comment by PureWeen** [comment]
I agree but I think it's still an android level thing and I'm not sure if we can do much about it. My guess is that it's either an android bug or there's a style there being applied that's not compatible with Android 6.0

I searched around on the exception you posted and there are a number of results that talk about incompatible styles causing this exception

For example
https://stackoverflow.com/questions/30870443/inflateexception-with-floatingactionbutton-from-official-design-library

If one uses the non *app* based backgroundTint it can cause layout inflation to crash.

Did you happen to narrow down any specific item in that style that was causing the crash?

**Comment by RvDillen** [comment]
@PureWeen : I found the cause of the crash:
It is the non app based backgroundTint.
I noticed that some "silent java errors" in the visual studio output dialog vanished as well. 
Thank you.
