### ISSUE TITLE
PullToRefresh App freeze in the Xamarin.forms 3.2.0.729530-pre2 version 

### ISSUE THREAD

**Issue by JayaramanAyyanar** [xamarin/Xamarin.Forms#3803]
### Steps to Reproduce

1. Run the sample.
2. Try to pull down
3. Continuously try the step 2 and you could find the app begin to freeze.

### Expected Behavior
The App should not freeze even if we pull down continuously.
### Actual Behavior
The App is freezing if we pull down continuously.
### Basic Information
App freeze in the Xamarin.forms 3.2.0.729530-pre2 version which is working fine with Xamarin.forms version to 3.1.0.697729. I have attached the both the samples in the reproducible section.
- Version with issue: 3.2.0.729530-pre2 
- IDE: Visual studio 2017
- Platform Target Frameworks: \
  - Android:  \\

### Reproduction Link

[Sample(3.2.0.729530-pre2 ).zip](https://github.com/xamarin/Xamarin.Forms/files/2388186/Sample.3.2.0.729530-pre2.zip)
[Sample(3.1.0.697729).zip](https://github.com/xamarin/Xamarin.Forms/files/2388189/Sample.3.1.0.697729.zip)

**Comment by kingces95** [comment]
Hit 260 char limit on windows; Will circle back and try again on Mac.

**Comment by kingces95** [comment]
I'm unable to reproduce this on device on our latest 3.3.0 branch. Please resubmit if your able to reproduce on our latest pre-release.
