### ISSUE TITLE
Getting irregular height measure from OnSizeAllocated(),when Layout hosted inside the scrollview of MasterDetailsPage.   

### ISSUE THREAD

**Issue by bala2346** [xamarin/Xamarin.Forms#3807]
### Description
Hi Team
     We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.

UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview

FeatureTour: https://www.syncfusion.com/products/xamarin

UserGuide:https://help.syncfusion.com/xamarin/sflistview/getting-started

We would like to bring to your notice a bug that we encountered recently in MasterDetailsPage. Getting an irregular height from the OnSizeAllocated when the page loaded inside the scroll view. 

Loading a Syncfusion’s SfDataGrid control or Xamarin.Forms.ListView inside a scroll view as the first page of details page and add another page without the scroll view loaded layout has next page of the details. The first page must contain only 6  to 7 rows(items).

SfDataGrid Scenario

In the case of SfDataGrid loaded inside a scroll view, while initially loading the data grid height is set as expected based on the number of rows and the scroll view is not scrollable. Now switch to another page and again come to an initial page, the non-scrollable page is now transformed to the scrollable page with irregular height obtained from the OnSizeAllocation override.

In Xamarin.Forms.ListView scenario

 In the case of  Xamarin.Forms.ListView loaded inside a scroll view, the situation is vice versa. When initially loaded itself, the height of the list view is greater than the content page and transform to the scrollable view. After switching to another page and again back to the initial page, the scrollable page is transformed to no scrollable page and is rendered correctly based on the number of rows(items) in the list view.

I have attached the video and debug video for this scenarios and attached with two sample in it, one for SfDataGrid and another one with Xamarin.Forms.Listview to replicate the issue.

### Steps to Reproduce
In Xamarin.Forms.ListView scenario

1)Run the Listview sample,
2) Initially loaded a page is getting the view of the master view. please absorbed the page that contains the limited data and page is greater than the contained items.
3) Click the toggle button and switch to another page in details.
4) Again switch the toggle button and come back to the initial page, now you can absorb the same page with the same data but the height of the page is correctly fixed in its content page height and transformed to a non-scrollable page.

In SfDataGrid Scenario

1)Run the Datagrid sample,
2) Initially loaded a page is getting the view of the master view. please absorbed the page that contains the limited data and page is not greater than the scroll view height.
3) Click the toggle button and switch to another page in details.
4) Again switch the toggle button and come back to the initial page, now you can absorb the same page with the same data but the height of the page is exceeding than the content page height and transformed to a scrollable page.

### Expected Behavior
After the switch from the any another the page, the height must retain the same height, should not be exceeded then the rows(items).

### Actual Behavior
The page height is varied when loaded inside the scroll view in the master-detail page, after the switching from another page.

### Basic Information
Version with issue: 2.4.0.280
IDE: Visual Studio 2017
Platform Target Frameworks: Xamarin.Forms.Android
 - Android: 8.1
Nuget Packages:  2.4.0.280
Affected Devices: All Android device.

### Reproduction Link
 ListView Sample : [ListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2389469/ListView.zip)
 ListView Video: [ListView Video.zip](https://github.com/xamarin/Xamarin.Forms/files/2389468/ListView.Video.zip)
SfDataGrid Sample:[DataGrid Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/2389473/DataGrid.Sample.zip)
SfDataGrid Video: [SfDataGrid Video.zip](https://github.com/xamarin/Xamarin.Forms/files/2389470/SfDataGrid.Video.zip)

**Comment by hartez** [comment]
I'm attempting to reproduce your bug using the sample you uploaded (ListView.zip), but so far I have been unable to. When I run the sample,  the label at the bottom is visible immediately and the list is not scrollable. I've included a video of the sample running.

[3807.zip](https://github.com/xamarin/Xamarin.Forms/files/2411655/3807.zip)

Have I missed something?

**Comment by bala2346** [comment]
Hi @hartez,
    I suppose you have run the sample in an android tablet. The reported issue is working fine on a tablet. It's replicated only in android phones. Our bad that we failed to mention it in the description. Sorry for the inconvenience caused.

**Comment by hartez** [comment]
@bala2346 I ran the sample in a phone emulator running Android 8.1.

If you observe the issue on phones and not on tablets, perhaps it has something to do with the screen size? What screen sizes are you seeing the problem on?

**Comment by bala2346** [comment]
Hi @hartez ,
  One plus 6 devices-- screen size: 1080 x 2280 pixel & 6.28-inch screen, But it will replicate in all mobile devices.

**Comment by bala2346** [comment]
Hi @hartez,
  Any update?

**Comment by hartez** [comment]
@bala2346 This is the ListView Sample (ListView.zip) running on a 1080 x 2280 screen. The initial page is not scrollable and the Activity box is visible at the bottom.

Please provide an updated repro project which demonstrates the issue.

![screenshot_1539811136](https://user-images.githubusercontent.com/538025/47116831-fe799480-d21f-11e8-8036-db07975fa594.png)

**Comment by samhouts** [comment]
@bala2346 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
