### ISSUE TITLE
Minimal Android cross platform project with Microsoft.EntityFrameworkCore gives reference error

### ISSUE THREAD

**Issue by davefxy** [xamarin/Xamarin.Forms#3810]
### Description
Create a Android cross platform solution without adding any code, add the Microsoft.EntityFrameworkCore
nuget package to both of the projects in the solution, gets the reference error.
### Steps to Reproduce
1. Create a Android cross platform project and add nuget pkg Microsoft.EntityFrameworkCore

2. Compile

3. Error		Can not resolve reference: `System.Buffers`, referenced by `System.Memory`. Please add a NuGet package or assembly reference for `System.Buffers`, or remove the reference to `System.Memory`.	EFAndroidProblem.Android			

### Expected Behavior
    Clean compile
### Actual Behavior
    Compiles with reference error
### Basic Information

- Version with issue:
Xamarin forms 3.2.0.839982
- Last known good version:
- IDE:
       Visual Studio 2017 (PC) 15.8.4
- Platform Target Frameworks: 
       Android: 8.1 (Oreo) & 9.0
- Android Support Library Version: 
- Nuget Packages:
    Xamarin.Forms v3.2.0.839982
    NETStandard.Library   v2.0.3
    Microsoft.EntityFrameworkCore  v2.1.3
- Affected Devices:

**Comment by hartez** [comment]
See also: https://github.com/aspnet/EntityFrameworkCore/issues/13631

**Comment by hartez** [comment]
Reproduction of issue: 

[_3810 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2494519/_3810.Repro.zip)

**Comment by divega** [comment]
@marek-safar just to have it cross-referenced here, this seems similar to the issue reported in https://github.com/aspnet/EntityFrameworkCore/issues/13631, only different versions of EF Core are used. 

If this repros consistently, it may be a blocker for using recent versions of EF Core with Xamarin Android.

**Comment by tipa** [comment]
This issue also happens using Xamarin.Android

**Comment by fourth-vasilpopov** [comment]
For now, seems there is "compatible" System.Memory nuget package (labelled "v.4.5.n-servicing-27114-05"). To install, you need to click on "Include prerelease" checkbox to get it.

**Comment by samhouts** [comment]
This issue was moved to xamarin/xamarin-android#2534
