### ISSUE TITLE
Getting errors after adding new xaml content page in 3.2.0.839982

### ISSUE THREAD

**Issue by kiranbasvaraj** [xamarin/Xamarin.Forms#3816]
### Steps to Reproduce

1. install 3.2.0.839982  xamarin.forms nuget  
2. add new xaml content page 
3. build 

### Expected Behavior
project should build without errors
### Actual Behavior
getting errors after adding new xaml content page
### Basic Information

- Version with issue:
- Last known good version:
- IDE:Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:xamarin.forms 3.2.0.839982
- Affected Devices:all android devices

### Reproduction Link

![err](https://user-images.githubusercontent.com/18255703/45677091-fc54e500-bb50-11e8-9836-897a1b2ef835.PNG)

**Comment by StephaneDelcroix** [comment]
could you attach the `Page1.xaml.cs` and `Page1.xaml.g.cs` files ?

**Comment by kiranbasvaraj** [comment]
@StephaneDelcroix  sorry i have deleted the project since it was not working
