### ISSUE TITLE
UNHANDLED EXCEPTION Xamarin.Forms 3.2.0.839982

### ISSUE THREAD

**Issue by gayko1976** [xamarin/Xamarin.Forms#3817]
Hi Xamarin Developers

I encounter the following exceptions with the latest stable Xamarin.Forms release on both iOS and Android:

**Android**
`MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid]   at Client.Pages.MeetingRoom.MeetingRoomPage.RegisterEventHandlers () [0x00072] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[MonoDroid]   at Client.Pages.MeetingRoom.MeetingRoomPage..ctor () [0x0000c] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[MonoDroid]   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
[MonoDroid]   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00017] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at System.Activator.CreateInstance (System.Type type) [0x00000] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[MonoDroid]   at Client.Pages.Menu.MenuVm.ShowPage (System.Object sender) [0x00011] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[MonoDroid]   at Client.Pages.Menu.MenuPage.<.ctor>b__0_0 (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs e) [0x0001a] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[MonoDroid]   at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
[MonoDroid]   at Xamarin.Forms.ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00017] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0012a] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes) [0x00000] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell) [0x0005e] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.ListView.NotifyRowTapped (System.Int32 index, Xamarin.Forms.Cell cell) [0x00023] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.ListViewAdapter.HandleItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id) [0x0007b] in <02db0bcb95874f4db06b80f38eac4adf>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.CellAdapter.OnItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id) [0x0002e] in <02db0bcb95874f4db06b80f38eac4adf>:0 
[MonoDroid]   at Android.Widget.AdapterView+IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.IntPtr native_view, System.Int32 position, System.Int64 id) [0x00019] in <7b11087f679f4f839385bbe5de3785fe>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.54(intptr,intptr,intptr,intptr,int,long)
[zygote] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: ch.ergon.client, PID: 7855
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
[AndroidRuntime]   at Client.Pages.MeetingRoom.MeetingRoomPage.RegisterEventHandlers () [0x00072] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[AndroidRuntime]   at Client.Pages.MeetingRoom.MeetingRoomPage..ctor () [0x0000c] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[AndroidRuntime]   at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
[AndroidRuntime]   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]    --- End of inner exception stack trace ---
[AndroidRuntime]   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00017] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at System.Activator.CreateInstance (System.Type type) [0x00000] in <77cd0ac959454c86bdf4b6c891c7df5b>:0 
[AndroidRuntime]   at Client.Pages.Menu.MenuVm.ShowPage (System.Object sender) [0x00011] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[AndroidRuntime]   at Client.Pages.Menu.MenuPage.<.ctor>b__0_0 (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs e) [0x0001a] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
[AndroidRuntime]   at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
[AndroidRuntime]   at Xamarin.Forms.ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00017] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0012a] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes) [0x00000] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell) [0x0005e] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.ListView.NotifyRowTapped (System.Int32 index, Xamarin.Forms.Cell cell) [0x00023] in <3a9c335d80a748a29a8f8588acbed83f>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.ListViewAdapter.HandleItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id) [0x0007b] in <02db0bcb95874f4db06b80f38eac4adf>:0 
[AndroidRuntime]   at Xamarin.Forms.Platform.Android.CellAdapter.OnItemClick (Android.Widget.AdapterView parent, Android.Views.View view, System.Int32 position, System.Int64 id) [0x0002e] in <02db0bcb95874f4db06b80f38eac4adf>:0 
[AndroidRuntime]   at Android.Widget.AdapterView+IOnItemClickListenerInvoker.n_OnItemClick_Landroid_widget_AdapterView_Landroid_view_View_IJ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_parent, System.IntPtr native_view, System.Int32 position, System.Int64 id) [0x00019] in <7b11087f679f4f839385bbe5de3785fe>:0 
[AndroidRuntime]   at (wrapper dynamic-method) System.Object.54(intptr,intptr,intptr,intptr,int,long)
[AndroidRuntime] 	at md51558244f76c53b6aeda52c8a337f2c37.CellAdapter.n_onItemClick(Native Method)
[AndroidRuntime] 	at md51558244f76c53b6aeda52c8a337f2c37.CellAdapter.onItemClick(CellAdapter.java:89)
[AndroidRuntime] 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
[AndroidRuntime] 	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
[AndroidRuntime] 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
[AndroidRuntime] 	at android.widget.AbsListView$3.run(AbsListView.java:4049)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:789)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:98)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6541)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**iOS**
`objc[18491]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x7fff88dfb748) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1125b4eb0). One of the two will be used. Which one is undefined.
objc[18491]: Class AMSupportURLSession is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x7fff8a12a9f0) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1125b4f00). One of the two will be used. Which one is undefined.
MonoTouch: Could not install sigaction override, unexpected sigaction implementation.
objc[18496]: Class AXAccessQueue is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities (0x123b1c780) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AXHearingSupport.framework/AXHearingSupport (0x12ae53888). One of the two will be used. Which one is undefined.
objc[18496]: Class AXAccessQueueTimer is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/AccessibilityUtilities.framework/AccessibilityUtilities (0x123b19d50) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Accessibility.framework/Frameworks/AXHearingSupport.framework/AXHearingSupport (0x12ae538d8). One of the two will be used. Which one is undefined.
2018-09-18 11:06:28.584 Client.iOS[18496:2408018] ConvertToNSExceptionAndAbort
2018-09-18 11:06:28.588 Client.iOS[18496:2408018] Inserted Xamarin Exception Stack Line!
2018-09-18 11:06:28.588 Client.iOS[18496:2408018] Name: System.Reflection.TargetInvocationException
2018-09-18 11:06:28.588 Client.iOS[18496:2408018] Message: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an objectXamarin Exception Stack:
  at Client.Pages.MeetingRoom.MeetingRoomPage.RegisterEventHandlers () [0x00072] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
  at Client.Pages.MeetingRoom.MeetingRoomPage..ctor () [0x0000c] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
  at (wrapper managed-to-native) System.Reflection.MonoCMethod.InternalInvoke(System.Reflection.MonoCMethod,object,object[],System.Exception&)
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00017] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in <3c7b99a36820490fb2cbc5a6fc6b06d8>:0 
  at Client.Pages.Menu.MenuVm.ShowPage (System.Object sender) [0x00011] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
  at Client.Pages.Menu.MenuPage.<.ctor>b__0_0 (System.Object sender, Xamarin.Forms.SelectedItemChangedEventArgs e) [0x0001a] in <87ae4d2cf79f4e14934e0b2f35136bd4>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[Xamarin.Forms.SelectedItemChangedEventArgs].invoke_void_object_TEventArgs(object,Xamarin.Forms.SelectedItemChangedEventArgs)
  at Xamarin.Forms.ListView.OnSelectedItemChanged (Xamarin.Forms.BindableObject bindable, System.Object oldValue, System.Object newValue) [0x00017] in <3a9c335d80a748a29a8f8588acbed83f>:0 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x0012a] in <3a9c335d80a748a29a8f8588acbed83f>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in <3a9c335d80a748a29a8f8588acbed83f>:0 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes) [0x00000] in <3a9c335d80a748a29a8f8588acbed83f>:0 
  at Xamarin.Forms.ListView.NotifyRowTapped (System.Int32 groupIndex, System.Int32 inGroupIndex, Xamarin.Forms.Cell cell) [0x0005e] in <3a9c335d80a748a29a8f8588acbed83f>:0 
  at Xamarin.Forms.Platform.iOS.ListViewRenderer+ListViewDataSource.RowSelected (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) [0x0006f] in <66855f87e3b64ff38a3e1034f86d8129>:0 
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in <4ab8db046af64ab0ae036378dae8bfd3>:0 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0002c] in <4ab8db046af64ab0ae036378dae8bfd3>:0 
  at Client.iOS.Application.Main (System.String[] args) [0x00000] in <5b29b4e1208f41ebbd77b10ed7c6ca37>:0 `

**Thanks for helping with/fixing this!**

Cheers 
Philipp

**Comment by dblookup** [comment]
+1

**Comment by samhouts** [comment]
@gayko1976 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
