### ISSUE TITLE
AnchorX / AnchorY cause layout issues on rotation

### ISSUE THREAD

**Issue by programmation** [xamarin/Xamarin.Forms#3825]
### Description
Using `AnchorX` or `AnchorY` properties makes layout fail after rotation.

### Steps to Reproduce

See enclosed repro project.

1. Start project.
2. Rotate the simulator / device.
3. Observe purple frame is misplaced.
4. Remove `AnchorX` and `AnchorY` properties from `Frame`.
5. Rotate the simulator / device.
6. Observe purple frame is laid out correctly.

### Expected Behavior
Purple frame should stay in the right relationship to the rest of the layout.

### Actual Behavior
Purple frame is placed incorrectly in the layout.

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: No idea!
- IDE: N/A
- Platform Target Frameworks: 
  - iOS:  11
  - Android: 8.1 
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

### Screenshots

**Incorrect behaviour:**
![simulator screen shot - iphone x - 2018-09-19 at 17 10 00](https://user-images.githubusercontent.com/10096185/45736672-faf9ea00-bc2e-11e8-8986-79bd2ae93525.png)
![simulator screen shot - iphone x - 2018-09-19 at 17 10 06](https://user-images.githubusercontent.com/10096185/45736673-faf9ea00-bc2e-11e8-8a0c-7bcccb27cfc4.png)
![simulator screen shot - iphone x - 2018-09-19 at 17 10 10](https://user-images.githubusercontent.com/10096185/45736674-faf9ea00-bc2e-11e8-8e90-99e9d0a10b03.png)

**Correct behaviour:**
![simulator screen shot - iphone x - 2018-09-19 at 16 59 31](https://user-images.githubusercontent.com/10096185/45736234-b02ba280-bc2d-11e8-8a74-5f2a27bc166f.png)
![simulator screen shot - iphone x - 2018-09-19 at 16 59 38](https://user-images.githubusercontent.com/10096185/45736235-b02ba280-bc2d-11e8-990e-2f3c6295af9f.png)

### Reproduction Link

[Test20180919.zip](https://github.com/xamarin/Xamarin.Forms/files/2395764/Test20180919.zip)

**Comment by kingces95** [comment]
Unable to reproduce; See expected behavior on 3.3.0 head. Please re-open if you're able to re-produce on the latest pre-release.

**Comment by JimmyRobz** [comment]
Reproduced in iOS, works on Android. My current workaround is not to use AnchorY but manually calculate additional translate value.
