### ISSUE TITLE
[WPF] FontSize setter in Label style in App.xaml not being used in WPF

### ISSUE THREAD

**Issue by DuncWatts** [xamarin/Xamarin.Forms#3827]
### Description
I have a Style with TargetType of Label which contains a FontSize setter.  The specified FontSize does not get used in the WPF build.  The exception to this is if the Label has FontAttributes="Bold" in which case the FontSize does get used.

### Steps to Reproduce

1. Inside App.xaml, add following style:

~~~xml
<Style TargetType="Label">
    <Setter Property="FontSize" Value="20" />
</Style>
~~~

2. Add the following Label controls:

~~~xml
<Label Text="Standard" />
<Label Text="Bold" FontAttributes="Bold" />
~~~

### Expected Behavior
Both Labels display at FontSize 20, as they do on UWP, iOS and Android builds.

### Actual Behavior
Only the Bold label displays at FontSize 20.

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: None
- IDE: VS2017 15.8.1
- Nuget Packages: Xamarin.Forms / Xamarin.Forms.Platform.WPF

### Screenshots

![image](https://user-images.githubusercontent.com/23555469/45740400-1cd27d00-bbed-11e8-8e70-46f4968754dc.png)

### Reproduction Link

[FontSizeRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/2396110/FontSizeRepro.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
