### ISSUE TITLE
[UWP] TitleView width measures too long when navigating back to page with titleview

### ISSUE THREAD

**Issue by dontspeak** [xamarin/Xamarin.Forms#3828]
### Description

In newest version 3.2 of XF there still seem to be serious issues with the visibility of elements in NavigtionPage. There are some bugs mentioned here on github, but the Xamarin Team said all are solved with 3.1 or 3.2. Thats not true. I see 2 issues that may be related:

Setting:
- XF Application as NET Standard 2.0 Project
- UWP Application that uses this XF Application

### Steps to Reproduce

1. Start attached UWP app  --> See issue 1

### Expected Behavior

1. ToolbarItem must be shown 
2. TitleView must be shown

### Actual Behavior

1. The UWP app does not show the ToolbarItems. On Mouseover we see a grey area, but no text. Only when the hamburger is clicked, the text appears.

### Basic Information

- Version with issue: Xamarin.Forms / Xamarin.Forms.Platform.WPF 3.2.0.839982
- Last known good version: no
- IDE: VS 2017 15.8.2
- Platform Target Frameworks:
  - WPF: .NET 4.7.1, 64Bit
  - UWP:  16299
- Nuget Packages:
Xamarin.Forms / Xamarin.Forms.Platform.WPF
- Affected Devices:
All

### Screenshots
![uwp](https://user-images.githubusercontent.com/21156731/45743310-05e75700-bbfc-11e8-973d-cc64f7016fdb.PNG)

### Reproduction Link

[NavBarBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/2396319/NavBarBugs.zip)

**Comment by PureWeen** [comment]
@dontspeak  unless I'm misunderstanding what you're saying that's how toolbar items in UWP have always showed up. You only see the icons in the nav bar and then when you click the three dots you see text.

Though your repro does expose a different bug where navigating back on UWP causes the Page's titleview to be too wide.

So I would say the page that's first visible is correct behavior. Then when you click back that page has an incorrect titleview

**Comment by dontspeak** [comment]
@PureWeen 
Regarding WPF TitleView: Ok thank you!

But regarding the UWP ToolbarIcons: No, I cant believe that this is the correct behaviour? When starting the app, **no** texts are visible. But mooving with the mouse over shows the grey rectangles, that should contain the texts. Because there are **no** icons configured in XML, this cannot works as expected??? Only if you click, you get the texts visible. I have added a video to show again the issue.

Please let me know whether this really **works as desinged** ?

[UWPBugAvi.zip](https://github.com/xamarin/Xamarin.Forms/files/2408725/UWPBugAvi.zip)

**Comment by PureWeen** [comment]
@dontspeak  this is how UWP natively works with the command bar implementation.
https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars

I'm pretty sure this is a UWP design decision to promote iconography over just having text.

For example if you use a bottombar on Android and have > 3 icons you won't have any text you'll just see icons.

**Comment by dontspeak** [comment]
@PureWeen ok thanks for pointing this out
