### ISSUE TITLE
iOS PullToRefresh not working within PreferLargeTitles within Navigation Page and Tabbed Page

### ISSUE THREAD

**Issue by james1301** [xamarin/Xamarin.Forms#3829]
### Description
ListView PullToRefresh does not work within a Tabbed Page > Navigation Page > Content Page running on iOS with the NavigationPage.PrefersLargeTitles set to true.

### Steps to Reproduce

1. Run Sample App on iOS
2. Try to Pull to Refresh on the tab, and it doesn't work

### Expected Behavior
Pull to Refresh works, like it does when not using the PreferLargeTitles
### Actual Behavior
Pull to refresh does not work
### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: Unknown
- IDE: Visual Studio 2017 version 15.8.4
- Platform Target Frameworks: 
  - iOS:  11.4
- Nuget Packages: -
- Affected Devices: -

### Screenshots

N/A

### Reproduction Link

Added sample project.
[TabbedPageWithNavigationPage.zip](https://github.com/xamarin/Xamarin.Forms/files/2396437/TabbedPageWithNavigationPage.zip)

**Comment by rmarinho** [comment]
Hi, I have just tried and I couldn't reproduce this issue. 

![simulator screen shot - iphone 7 plus - 2018-09-25 at 13 09 58](https://user-images.githubusercontent.com/1235097/46013522-7858ab00-c0c4-11e8-8cb1-c21bae340fdb.png)

**Comment by samhouts** [comment]
@james1301 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
