### ISSUE TITLE
UWP: SwipeGestureRecognizer not recognising a swipe

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#3831]
### Description

Swipes not recognised with a `SwipeGestureRecognizer` on UWP. Works fine on iOS/Android.

### Steps to Reproduce

1. Run the attached sample.
2. Navigate to the Swipe Page (XAML) (or any other page).
3. Swipe in the BoxView.

### Expected Behavior

The swipe is recognised, the `OnSwiped` event handler executes and the Label updates.

### Actual Behavior

The Label doesn't update, indicating that the `OnSwiped` event handler isn't executing.

### Basic Information

- Version with issue: 3.2.0.839982
- IDE: VS2017 15.8.4
- Platform Target Frameworks: 
  - UWP:  17134

### Reproduction Link

[SwipeGesture.zip](https://github.com/xamarin/Xamarin.Forms/files/2397308/SwipeGesture.zip)

**Comment by mattrichnz** [comment]
@davidbritch @pauldipietro I can confirm this too.

**Comment by mattrichnz** [comment]
Just realised, isn't this fixed in 3.3.0 by #3098?

**Comment by mattrichnz** [comment]
@samhouts I know this is in 3.30-pre1, but this really needs to be picked over to an upcoming 3.2.0-sr1 release given `SwipeGestureRecognizer` was a key feature in the 3.20 release.

**Comment by davidbritch** [comment]
Looks like this is fixed by https://github.com/xamarin/Xamarin.Forms/pull/3098
