### ISSUE TITLE
Label with FormattedString not updated!

### ISSUE THREAD

**Issue by toumir** [xamarin/Xamarin.Forms#3832]
### Description
Hi, 
the same data bound to Label, one without FormattedString and the Other with FormattedString respectively
when updating the Data in code behind, the Label with FormattedString not updating, is this intended ?

### Expected Behavior
data update 

### Actual Behavior
data not updating when it changed programmatically (in code behind)
### Basic Information
- IDE: VS
- Platform Target Frameworks: 
  - Android: 6.0 
  - iOS:  not tested 
  - UWP:  not tested 

### Screenshots

![2018-09-19_15-18-00](https://user-images.githubusercontent.com/10366325/45759182-a3a44b80-bc27-11e8-9dfe-b0d78be3309e.gif)

### Reproduction Link
**update the data in code behind**
XAML 
```
//...
<Label>
	<Label.FormattedText>
		<FormattedString>
			<Span Text="MyData : " TextColor="Blue"/>
			<Span Text="{Binding Data}"/>
		</FormattedString>
	</Label.FormattedText>
</Label>

<Label Text={Binding Data}/>
//...
```

**Comment by StephaneDelcroix** [comment]
default binding mode for Span.Text is `OneTime`. use `{Binding Data, Mode=OneWay}`

if that doesn't fix it, please reopen
