### ISSUE TITLE
Cannot Bind to ViewModel within TitleView

### ISSUE THREAD

**Issue by james1301** [xamarin/Xamarin.Forms#3833]
### Description
Trying to bind the new NavigationPage.TitleView to a property on my ViewModel, but it doesn't work. Not sure what the default BindingContext should be within here.

### Steps to Reproduce

1. Create a NavigationPage that then has another Page as it's child. When trying the following code, nothing is displayed because the BindingContext, does not flow through from the Page.
`    <NavigationPage.TitleView>
        <StackLayout>
            <Label Text="{Binding Title}" />
        </StackLayout>
    </NavigationPage.TitleView>`

### Expected Behavior
Displays text as the title based on the BindingContext, of it's parent page.
### Actual Behavior
Displays nothing because I presume the BindingContext is null, or set to something else.
### Basic Information

- Version with issue: 3.2
- Last known good version: N/A
- IDE: Visual Studio 2017 (15.8.4)
- Platform Target Frameworks: 
  - iOS:  11.4
- Nuget Packages: N/A
- Affected Devices: N/A

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by PureWeen** [comment]
duplicate and fixed
https://github.com/xamarin/Xamarin.Forms/pull/3823
