### ISSUE TITLE
NavigationPage TitleView is not set in UWP

### ISSUE THREAD

**Issue by mackayn** [xamarin/Xamarin.Forms#3834]
### Description
In Xamarin Forms 3.2, setting the TitleView in UWP projects does not work, in the default template app, In Android and iOS the TitleView is set correctly. 

This issue 1st arose in our own app, in that app when navigating to the TitleView page on app startup, the TitleView is blank in UWP but navigating away and reloading the page renders  the content.

### Steps to Reproduce

1. Default solution to UWP
2. Start the App (ITems page should be shown)

### Expected Behavior
ItemsPage should be shown with a TitleView that contains two buttons and an Entry control

### Actual Behavior
Works as Expected in Android
Works as Expected in iOS
Nothing is rendered in Navigationbar in UWP

### Basic Information

- Version with issue: Version with issue: Xamarin.Forms.3.2.0.839982
- Last known good version: None
- IDE: VS2017 15.8.2 (Windows)
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android: 7.1
  - UWP: 16299

- Nuget Packages:
- Affected Devices: ALL

### Screenshots

1. UWP
![titleview - uwpbug](https://user-images.githubusercontent.com/17179957/45766903-b1120380-bc30-11e8-8bc5-4186f83dd1f1.png)

2. Android
![titleview - android](https://user-images.githubusercontent.com/17179957/45766909-b5d6b780-bc30-11e8-8359-40eeaf2608de.png)

3. iOS
![titleview- ios](https://user-images.githubusercontent.com/17179957/45766921-be2ef280-bc30-11e8-9b22-8dc699c35676.png)

### Reproduction Link

[TitleViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2397806/TitleViewBug.zip)

**Comment by kingces95** [comment]
Behavior is as described.
