### ISSUE TITLE
[Enhancement] Add IsVisible to ToolbarItem

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3838]
## Rationale

At times you need to check if a toolbar item is visible, and to set it thus.

Related: https://xamarin.uservoice.com/forums/258559/suggestions/15508584

## Implementation

Add new properties to `Toolbaritem` for:
* IsVisible

**Comment by AmrAlSayed0** [comment]
Meanwhile, this is already implemented [here](https://forums.xamarin.com/discussion/comment/317152/) by @adamped and Norman Mackay but only on the Xamarin.Froms layer, no renderers.

**Comment by Skirtek** [comment]
Is there any progress? This feature is in progress for about four months :(

**Comment by mackayn** [comment]
@Skirtek 

Adam wrote a little to support toolbar visibility which I modified a bit, it's not perfect but used it in a few apps in an MVVM scenario.

https://forums.xamarin.com/discussion/40622/found-a-way-to-make-toolbaritems-visible-invisible-without-a-custom-renderer

**Comment by Skirtek** [comment]
Thanks! I used your code with a little changes. But still waiting for support from Xamarin Team :)

**Comment by cmeeren** [comment]
The workaround posted above is not something I can live with, since if the initial state is hidden, the toolbar item still pops up for a second before disappearing. This is confusing to users.

Hoping this will get officially implemented!

**Comment by thudugala** [comment]
Also please add "Font Family" or "File Image Source" for Font Icon support

**Comment by mfeingol** [comment]
This would be a great enhancement to ToolbarItem.

**Comment by MortMH** [comment]
I need this as well to remove/add functionality based on account type.

**Comment by Skirtek** [comment]
One year anniversary of this issue is coming! ;)

**Comment by stesvis** [comment]
If a regular button can/should be visible or invisible depending on some condition, why assume that a toolbar button should be always visible?

**Comment by Skirtek** [comment]
Could you tell us what happend with #3946? Could we expect this feature soon?

**Comment by jfversluis** [comment]
@Skirtek from the top of my head the biggest problem, also emerges from the comments in the PR you linked, is that the toolbar items, at least on iOS, simply don't support this. That is why we would need to work around this somehow. But doing that causes a lot of side-effects and other unwanted behavior we cannot predict. I would not hold my breath for seeing this feature very soon. Of course you are welcome to propose a solution and/or open a PR for it.

**Comment by burrowj** [comment]
Would a ZeroWidth option be possible

**Comment by muak** [comment]
I tried creating the pull request #8878 for this issue.

**Comment by Skirtek** [comment]
@muak I am very glad that the problem will be solved. Congratulations! :)

**Comment by groege** [comment]
Any idea, what Xamarin version will this be available, and when that version will be pushed to nuget?

**Comment by jfversluis** [comment]
@groege it's too early to say. The PR is not merged yet. We need to review it and test it first.

My guess now is that it would be part of 4.6.

**Comment by rosalesruben** [comment]
any updates about this? i need it. Thanks!

**Comment by muak** [comment]
I made the custom renderer version for #8878.
https://github.com/muak/HidableToolbarItem

It might be a workaround for some while.

**Comment by Magendanz** [comment]
I took a much simpler approach:

```
    public class CustomToolbarItem : ToolbarItem
    {
        protected override void OnPropertyChanged(string propertyName = null)
        {
            base.OnPropertyChanged(propertyName);
            if (propertyName == nameof(IsEnabled))
            {
                var items = (Parent as Page).ToolbarItems;

                // Hide ToolbarItem when it's command is disabled
                if (IsEnabled && !items.Contains(this))
                    Device.BeginInvokeOnMainThread(() => items.Add(this));
                else if (!IsEnabled && items.Contains(this))
                    Device.BeginInvokeOnMainThread(() => items.Remove(this));
            }
        }
    }
```

Note that you can't add or remove ToolbarItems on the current thread in newer XF builds because apparently the parent is enumerating the collection and it crashes with a "Collection was modified; enumeration operation may not execute."

**Comment by djrpascu** [comment]
> I took a much simpler approach for my workaround, leveraging the IsEnabled property:
> 
> ```
>     public class PeekabooToolbarItem : ToolbarItem
>     {
>         protected override void OnPropertyChanged(string propertyName = null)
>         {
>             base.OnPropertyChanged(propertyName);
>             if (propertyName == nameof(IsEnabled))
>             {
>                 var items = (Parent as Page).ToolbarItems;
> 
>                 // Hide ToolbarItem when it's command is disabled
>                 if (IsEnabled && !items.Contains(this))
>                     Device.BeginInvokeOnMainThread(() => items.Add(this));
>                 else if (!IsEnabled && items.Contains(this))
>                     Device.BeginInvokeOnMainThread(() => items.Remove(this));
>             }
>         }
>     }
> ```
> 
> Note that you can't add or remove ToolbarItems on the current thread in newer XF builds because the parent seems to be enumerating the collection and it crashes with a "Collection was modified; enumeration operation may not execute."

I'm seeing this for iOS, seems to work ok for UWP. Ever figure out a workaround to it?

**Comment by Magendanz** [comment]
> I'm seeing this for iOS, seems to work ok for UWP. Ever figure out a workaround to it?

The BeginInvokeOnMainThread() approach above has been an effective workaround for me.

**Comment by jfversluis** [comment]
Hey everyone, thank you so much for your patience, input and workarounds etc. At this point we won't be adding anything new to Xamarin.Forms. Unfortunately, that includes this one. I see a lot of people would want this, so I am making sure to put this on a list for consideration for .NET MAUI. If it's something you're still interested in as well, make sure to see if it's on the roadmap, maybe there is an issue already of open something with as much detail as possible.

Thank you all for all your time and effort on this!
