### ISSUE TITLE
[Enhancement] Hide Scroll Bars on ListView

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3843]
## Rationale

Sometimes you just don't want to see the bars.

## Implementation

Just like we added for `ScrollView` on #1910.

```
<ScrollView VerticalScrollBarVisibility="Always"
                HorizontalScrollBarVisibility="Never">
```

**Comment by jfversluis** [comment]
Let me have a crack at this!

**Comment by mikescandy** [comment]
I played a bit with this and it's trivial to hide/display scrollbars.
But the horizontal one is kind of useless, as I can't find a way to scroll content horizontally inside the listview. Any tip on this?

**Comment by jfversluis** [comment]
@mikescandy Let's coordinate. I've got this done for iOS, MacOS, Android, UWP and WPF already. It would be a waste of effort if we're both looking into this 🙂
