### ISSUE TITLE
[Enhancement] Add a Clear button to DatePicker and TimePicker

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3844]
## Rationale

See https://xamarin.uservoice.com/forums/144858/suggestions/16997776

## Implementation

TBD

## API

TBD

**Comment by brinawebb** [comment]
As a part of this you will also need to support a null value, DateTime?, correct?

**Comment by opcodewriter** [comment]
@davidortinau I don't understand, why did you set the issue on UserVoice to COMPLETED.
It's misleading, it's not completed, why not set the issue to PLANNED?
The UserVoice on that portal, xamarin.uservoice.com is completely broken. It looks like "planned" was overwritten with "completed" status. If I select "planned" it shows "completed" features. Sigh...

**Comment by davidortinau** [comment]
@opcodewriter sorry if I got your hopes up. 

I marked them completed because there is a transition happening with our use of UserVoice and the only way to grant you back your votes was to mark it completed. I tried to make the actual status clear in the comment I added. We won't be tracking those items moving forward on UserVoice.

**Comment by samhouts** [comment]
related to #3728

**Comment by jfversluis** [comment]
I am looking into #3728, when that is implemented; is this really added value?
What would a button look like on the different platforms? I think if we add a button, users will want to be able to style it, etc.

I would propose to just implement the nullable date (or time for that matter) and let users implement their own clearing functionality/buttons/controls.

Thoughts?

**Comment by cmcclure-penlink** [comment]
Either that are create an event when the cancel button is hit. Should come that way by default.

**Comment by andreinitescu** [comment]
I wanted initially to add a comment to #6947 but I want to keep discussion separated.

I think it's confusing to have a Clear button on the picker dialog. The picker dialog itself always shows a date, there's no way not have it show a date selected, like how for example selection works in ListView (SelectedItem can be null).

So I think a Clear button would make more sense on the picker text field and it makes sense to work with the new `SelectedDate` property on the DatePicker introduced by #6947:

![image](https://user-images.githubusercontent.com/743918/61663328-08fa1a80-acd9-11e9-80cb-1857dace5b26.png)

If we agree it makes sense to have a Close button this way, I can work on a separate PR to have the date picker show a close button to set the new DatePicker `SelectedDate` property to null. It would require however first getting merged #6947 and #5277 (which btw, I don't know why it was postponed again to vNext+1)

**Comment by jcmanke** [comment]
Copied comment from https://github.com/xamarin/Xamarin.Forms/pull/6947#issuecomment-513905929

>In my custom nullable pickers, we have have 3 buttons: Clear (set to null), Cancel (close the dialog without changing the BindableProperty's value) and OK/Done (set the BindableProperty value to the current dialog value).

>![Screenshot_1563820576](https://user-images.githubusercontent.com/6132629/61656467-6fa21880-ac86-11e9-9545-35d0c39f97f1.png)

>![ios_nullable_datepicker](https://user-images.githubusercontent.com/6132629/61656583-b6900e00-ac86-11e9-820a-c4999109081e.png)

**Comment by adammeaney** [comment]
One concern we had when doing the Nullable Date Picker for ourselves was the clear button on the Text Field.

If we put it on the text field, what about when we wanted to do the nice thing and stick a Calendar icon over there to appear like the UWP Date Picker? That was an option a few of our guys requested, and I thought it looked strange when we had both an X and a Calendar.

**Comment by jfversluis** [comment]
Duplicate of #3728

**Comment by jfversluis** [comment]
Please see the linked issue above for the reason why this was closed. Thank you!
