### ISSUE TITLE
Android InputTransparency With Nested Layouts

### ISSUE THREAD

**Issue by MaxHampton** [xamarin/Xamarin.Forms#3846]
### Description

I am creating a menu for an app I am working on. It is working as expected on iOS. On Android, I am having issues interacting with the menu. Basic XAML layout below. I have tried a number of combinations for InputTransparent and CascadeInputTransparent to make it so the nested buttons are tappable, while content behind the menu is still scrollable. The ContentViews are added dynamically in response to a bound items property. 

Before I say "it's not working," what's the correct setup for input transparency to get this working? The code below shows how I've configured it. I reported the same issue prior to 3.2, thought a fix was coming with the new version.

    <StackLayout InputTransparent=True CascadeInputTransparent=False>
      <ContentView InputTransparent=True CascadeInputTransparent=False> 
        <Grid InputTransparent=True CascadeInputTransparent=False>
          <Label Grid.Column=0 InputTransparent=True />
          <Button Grid.Column=1 InputTransparent=False />
        </Grid>
      </ContentView>
      <ContentView>
        <Grid>
          <Label Grid.Column=0 />
          <Button Grid.Column=1 />
        </Grid>
      </ContentView>
      <ContentView>
        <Grid>
          <Label Grid.Column=0 />
          <Button Grid.Column=1 />
        </Grid>
      </ContentView>
      <Button />
    </StackLayout>

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: XF 3.2.0.839982
- Last known good version: N/A
- IDE: Visual Studio 2017 Enterprise
- Platform Target Frameworks: 

  - Android: Latest (8.1)

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by MaxHampton** [comment]
This was previously tracked here https://github.com/xamarin/Xamarin.Forms/issues/2858

**Comment by MartinZikmund** [comment]
I can confirm updating to 3.2 broke the `InputTransparent` again for me as well. I think the problem is related to the new `SwipeGesture`, but have yet to confirm.

**Comment by jassmith** [comment]
Confirmed this is broken, @hartez can maybe shed some light here.

**Comment by MartinZikmund** [comment]
Hi, any status update on this :-) ? We would really love to update to 3.3, but are stuck on 3.1 because of this problem...

**Comment by MartinZikmund** [comment]
@hartez @samhouts ping, we are now facing an issue that prevents us from using compiled bindings, which has been fixed in later versions so it would be awesome if this got fixed, as it is a blocker for us...

**Comment by MartinZikmund** [comment]
@hartez @samhouts Reaching out again, any chance on looking into this? Our business app is still stuck on 3.1 and are missing quite a lot of new Xamarin.Forms features due to this bug... Thanks :-)

**Comment by samhouts** [comment]
@MartinZikmund We are working on getting this prioritized. Thank you for your patience!

**Comment by MartinZikmund** [comment]
@samhouts Seems this works in 4 Preview, maybe fixed with unrelated issue :-) . Thanks!
