### ISSUE TITLE
[F100] Add support for RelativeSource binding

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3847]
## Rationale

https://forums.xamarin.com/discussion/20179/databinding-to-a-command-inside-a-datatemplate#latest

http://xamarin.uservoice.com/forums/258559/suggestions/6451625

## Implementation

Like UWP? https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/relativesource-markup-extension

**Comment by StephaneDelcroix** [comment]
to my knowledge, all of what is achieved through RelativeSource can also be achieved with `{x:Reference}`...

is there any missing case ?

**Comment by james1301** [comment]
And yeah also like the first forum post on this issue. When using a DataTemplate for like a ListView, getting back to the BindingContext, of the parent to access a Command on the ViewModel?

Especially useful when it is a generic DataTemplate perhaps used in multiple places, rather than having to make sure all the instances of ListView, have the same name.

**Comment by GalaxiaGuy** [comment]
There is an implementation here: https://github.com/xamarin/Xamarin.Forms/issues/3765

https://github.com/RenaudAvenas/Mobile.Controls/blob/master/Mobile.Controls/MarkupExtensions/RelativeSourceBinding.cs

**Comment by spaceman502** [comment]
RelativeSource Self would be very nice

**Comment by legistek** [comment]
Is anyone actively working on this? I pretty desperately need this before I can port my WPF application to XF and would like to take it on if no one else is.

**Comment by legistek** [comment]
I want ahead and took a stab at this. Unless I'm missing something it was surprisingly straightforward. The code is here:
https://github.com/xamarin/Xamarin.Forms/compare/master...legistek:gh3487-relativesource-binding

And here's some sample XAML that works after my changes:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:custom="clr-namespace:RelativeSourceTesting"
             x:Class="RelativeSourceTesting.MainPage">
	<ContentPage.Resources>
		<ControlTemplate x:Key="CustomControlTemplate">
			<Label Text="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=Text}"/>
		</ControlTemplate>
	</ContentPage.Resources>
    <ContentPage.Content>
		<StackLayout x:Name="Stack0">
			<StackLayout x:Name="Stack1">
				<!-- [Blank] -->
				<Label Text="{Binding RelativeSource={RelativeSource AncestorType={x:Type StackLayout}, AncestorLevel=3}, Path=StyleId}"/>
				
				<!-- Stack0 -->
				<Label Text="{Binding RelativeSource={RelativeSource AncestorType={x:Type StackLayout}, AncestorLevel=2}, Path=StyleId}"/>
				
				<!-- Stack1 -->
				<Label Text="{Binding RelativeSource={RelativeSource AncestorType={x:Type StackLayout}}, Path=StyleId}"/>

				<!-- SelfBindingLabel -->
				<Label x:Name="SelfBindingLabel"
					   Text="{Binding RelativeSource={RelativeSource Self}, Path=StyleId}"/>

				<!-- My Custom Control -->
				<custom:CustomControl ControlTemplate="{StaticResource CustomControlTemplate}"
									  Text="My Custom Control"/>
			</StackLayout>
		</StackLayout>
	</ContentPage.Content>
</ContentPage>
```

Any reason not to submit a PR for this? It just needs some unit tests.

cc: @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
@legistek please open a PR
