### ISSUE TITLE
Enhancement Xamarin Forms tvOS

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#3849]
For now I can only create native apps for tvOS. 
It would be great to use common UI from .net standard library to start application from tvOS project

**Comment by StephaneDelcroix** [comment]
we had a branch for that in the distant past...

Providing a tvOS backend is not in the priorities of the XF team at the moment, but an external contribution is welcome. Most of the code can be shared between this implementation and the iOS/macOS one.

**Comment by jfversluis** [comment]
I think it's safe to say this won't be happening for Forms anymore.
