### ISSUE TITLE
Feature Request : PopupControl

### ISSUE THREAD

**Issue by jashif** [xamarin/Xamarin.Forms#3854]
Is there any plan to include  a popup control , in xamarin forms control list, Currently In our project we are writing the renderers to get the popup behaviour. It will help a lot in showing various alert scenarios to user.

Currently in our project we create renderers using native control in each of below platforms.
Popup in Windows 
Pop Window in Android

**Comment by pauldipietro** [comment]
Please see #1778. Thanks!
