### ISSUE TITLE
[Android] Label underline doesn't work in 3.3.0-pre1 with Fast Renderers

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#3857]
### Description

Underline works in iOS but **not** Android.

```
<Label Text="Label/Span Underline and Strikethrough" TextDecorations="Underline"  class="featureHeader" Margin="0,0,0,10"/>
```

### Screenshots

<img width="927" alt="screenshot 2018-09-20 21 02 45" src="https://user-images.githubusercontent.com/41873/45856180-12ad9d00-bd19-11e8-8389-31b56545c513.png">

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/3.3.0-pre/TheLittleThingsPlayground/Views/ThreeThreePage.xaml

**Comment by rmarinho** [comment]
I can't repo this tried api27 and api 25
[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/2406563/App2.zip)
![screenshot_1537555188](https://user-images.githubusercontent.com/1235097/45899917-1f43fb00-bdd6-11e8-97e3-6f048b3cffd7.png)

**Comment by PureWeen** [comment]
As with Max Lines this is broken on Fast Renderers only
