### ISSUE TITLE
[Android] ListView items collapse unless RowHeight is set

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#3861]
### Description

I'm not yet sure of the exact circumstances but others might chime in to help. There was this error: https://github.com/xamarin/Xamarin.Forms/issues/3427

It hasn't been really fixed but the new problems seem to be linked. As I can see now, `HasUnevenRows` isn't directly doing anything now as described in the original error, however, neither _true_ nor _false_ really creates an acceptable ListView any more unless `RowHeight` is specifically set. Without setting `RowHeight`, list items simply collapse and don't show the entire cell contents any more. Immediate downgrade required, this is completely unusable now.

### Basic Information

- Version with issue: 3.2
- Last known good version: 3.1
  - Android: 27.0.2.1

**Comment by deakjahn** [comment]
As I tried to come up with a repo, it turned out to be a different problem, ending in the same results. I'll link to a new bug report soon.

**Comment by deakjahn** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/3862

The real reason was that `HasUnevenRows` (or anything else for that matter) cannot be set from a style using the new `OnPlatform` markup. I was barking up the wrong tree... :-)

**Comment by samhouts** [comment]
It looks like you've determined that this issue was invalid and is replaced by #3862. If I have misinterpreted this, please reopen this issue. Thanks!
