### ISSUE TITLE
System.Net.WebException: The operation has timed out.

### ISSUE THREAD

**Issue by matteozoni** [xamarin/Xamarin.Forms#3863]
Hi, I have a problem with the latest versions of xamarin form.

I have this code that has always worked correctly until the latest updates, which downloads a text file from a server.

        private string GetUrlString(string url)
        {
            try
            {
                string latest = string.Empty;

                var downloadEvent = new AutoResetEvent(false);
                var uri = new Uri(url);
                var request = WebRequest.Create(uri);
                var result = request.BeginGetResponse(response =>
                {
                    using (var stream = request.EndGetResponse(response).GetResponseStream())
                    using (var reader = new StreamReader(stream))
                        latest = reader.ReadToEnd();
                    downloadEvent.Set();
                }, null);

                if (downloadEvent.WaitOne(5000))
                    return latest;
                request.EndGetResponse(result);
                return null;
            }
            catch
            {
                return null;
            }
        }

now after several seconds i get the error "System.Net.WebException: The operation has timed out."

I have the problem with both Android and iOS.

Here the test case: https://drive.google.com/open?id=1URej1za2vDrnJuz7mF_8rcWRZm9DkHQP

Below the version of the components

Microsoft Visual Studio Community 2017 
Versione 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036
Microsoft .NET Framework
Versione 4.7.03056

Edizione installata: Community

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Estensione ResourcePackage   1.0
Informazioni dettagliate sull'estensione ResourcePackage di Visual Studio

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Funzioni di Azure e strumenti per processi Web   15.9.02009.0
Funzioni di Azure e strumenti per processi Web

Gestione pacchetti NuGet   4.6.0
Gestione pacchetti NuGet in Visual Studio. Per altre informazioni su NuGet, visitare il sito Web http://docs.nuget.org/.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools per contenitori   1.1
Consente di sviluppare, eseguire e convalidare applicazioni ASP.NET Core nell'ambiente di destinazione. Premere F5 per modificare l'applicazione direttamente in un contenitore senza debug oppure CTRL+F5 per modificare e aggiornare l'app senza ricompilare il contenitore.

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

Pacchetto di Strumenti Application Insights per Visual Studio   8.13.10627.1
Strumenti Application Insights per Visual Studio

Pacchetto host dell'adattatore di debug di Visual Studio Code   1.0
Livello di interoperabilità per l'hosting degli adattatori di debug di Visual Studio Code in Visual Studio

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Servizio di linguaggio JavaScript   2.0
Servizio di linguaggio JavaScript

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

Strumenti C#   2.9.0-beta8-63208-01
Componenti di C# usati nell'IDE. A seconda delle impostazioni e del tipo di progetto, potrebbe essere usata una versione diversa del compilatore.

Strumenti comuni di Azure   1.10
Fornisce servizi comuni da usare con Servizi mobili di Azure e gli strumenti di Microsoft Azure.

Strumenti di Microsoft Azure   2.9
Strumenti di Microsoft Azure per Microsoft Visual Studio 2017 - versione 2.9.10730.2

Strumenti di recapito continuo Microsoft per Visual Studio   0.4
Consente di semplificare la configurazione delle pipeline Azure DevOps direttamente dall'IDE di Visual Studio.

Strumenti TypeScript   15.8.20822.2001
Strumenti TypeScript per Microsoft Visual Studio

Strumenti Visual Basic   2.9.0-beta8-63208-01
Componenti di Visual Basic usati nell'IDE. A seconda delle impostazioni e del tipo di progetto, potrebbe essere usata una versione diversa del compilatore.

Visual F# Tools 10.2 per F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
Microsoft Visual F# Tools 10.2 per F# 4.5

Visual Studio Tools per contenitori   1.0
Visual Studio Tools per contenitori

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Estensione di Visual Studio per consentire lo sviluppo per Xamarin.iOS e Xamarin.Android.

Xamarin Designer   4.15.9 (d000f568b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by samhouts** [comment]
What version did you upgrade from that was working? The test case has 3.0.0 installed. What can I downgrade to that will make it work again? Thanks!

**Comment by matteozoni** [comment]
I have the impression that it is a problem that occurred after the update of visuals studio that of xamarin form.

**Comment by matteozoni** [comment]
no news?

**Comment by manimerz** [comment]
Having the same issue here with:

```csharp
using (Stream requestStream = await request.GetRequestStreamAsync())
{
    using (var writer = new StreamWriter(requestStream))
    {
        // Do stuff here
    }
}
```
I'm trying to run this code with Visual Studio **15.8.9** and Xamarin **4.11.0.779** and it throws the same **TimeoutException** after subsequent runs (approx. 10 times).

Because @matteozoni suggested a VS-Update could have caused this, I also tested it with a fresh install of Visual Studio **15.7.6** and Xamarin **4.10.10.2**
Now it does not even throw the Exception.

Am I doing something wrong here, or is there a problem with the disposal of WebRequests?

**Comment by matteozoni** [comment]
I have installed today VS 15.9.1 and does not solve the problem

**Comment by kingces95** [comment]
Without a complete reproduction, I'm unable to know in what threading environment you are making the call but I can reproduce this if I make asynchronous call on the UIThread and can resolve this by placing the asynchronous call off the UIThread. 

```
new Thread(delegate()
{
	GetUrlString("http://www.google.com");
}).Start();
```

While I'd have expected to be able to initiate an async call from the UIThread (Isn't that the point of async!?) the docs say it shouldn't be done. Apparently, it's not _totally_ asynchronous. Or rather, its only asynchronous from the point of view of the network traffic. It still blocks locally setting up the networking stack. 

see https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.begingetresponse?view=netframework-4.7.2

> The BeginGetResponse method requires some synchronous setup tasks to complete (DNS resolution, proxy detection, and TCP socket connection, for example) before this method becomes asynchronous. As a result, this method should never be called on a user interface (UI) thread because it might take considerable time (up to several minutes depending on network settings) to complete the initial synchronous setup tasks before an exception for an error is thrown or the method succeeds.

**Comment by matteozoni** [comment]
What do you mean by "complete reproduction"?

In my first post I put an example of the problem

https://drive.google.com/open?id=1URej1za2vDrnJuz7mF_8rcWRZm9DkHQP

**Comment by gvsharma** [comment]
upgrade your xamarin version and it solves the problem

**Comment by gautambjain** [comment]
I downgraded to VS 15.7.6 to resolve it.
