### ISSUE TITLE
Bring Shadow to IRoundedCorners views

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#3867]
### Description
It would be nice to have bindable properties like:
ShadowColor
ShadowOffset 
ShadowOpacity
ShadowRadius 

to allow the developer to control the Shadow on elements like Frame, StackLayout, Grid and etc.
Specially it should draw the shadow consistently on both iOS and Android
 and works well with rounded corners elements.

**Comment by ederbond** [comment]
It would allow me to easly create a beaudifull bottom drawer like this:

![image](https://user-images.githubusercontent.com/12549812/50247305-a8130880-03be-11e9-81b7-5634e26fe952.png)

Note the rounded corner on the TopRight and TopLeft of the drawer and also the subtle rounded shadow.

**Comment by ederbond** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/1754

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
