### ISSUE TITLE
[WPF] Implement TitleView

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3868]
### Description
Implement TitleView on WPF

https://github.com/xamarin/Xamarin.Forms/pull/2586
https://github.com/xamarin/Xamarin.Forms/issues/1716

**Comment by nitishmani** [comment]
Any update on when this is to be released. Its more than a year after the issue #5664 was reported and still trying to come up with a solution? Has MS stopped funding for Xamarin?

**Comment by peterfoot** [comment]
I had a very brief look into how this is implemented. I can (using a custom renderer) create a renderer for the TitleView and see WPF generated for all the controls I created in my custom control however I haven't been able to insert these into the Visual Tree successfully in the AppBar.

**Comment by jfversluis** [comment]
Don't think we will be doing this for Xamarin.Forms anymore, sorry! :(
