### ISSUE TITLE
Allow me to individually choose witch corners IRoundedCorners will rounded.

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#3871]
Add a bindable property to IRoundedCorners to allow developers to choose individually, witch side of a IRoundedCorners element that should be rounded:

Ex:
`public static readonly BindableProperty RoundedCornersProperty = BindableProperty.Create(nameof(RoundedCorners), typeof(string), typeof(RoundedCornerView), "All", validateValue: OnRoundedCornersPropertyValidateValue);`

Usage:

```
<StackLayout Orientation="Vertical" Spacing="30" VerticalOptions="CenterAndExpand" HorizontalOptions="CenterAndExpand">

      <controls:RoundedCornerView CornerRadius="80" RoundedCorners="TopLeft, TopRight">
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="White"/>
      </controls:RoundedCornerView>

      <controls:RoundedCornerView CornerRadius="80" RoundedCorners="TopLeft">
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Red"/>
      </controls:RoundedCornerView>

      <controls:RoundedCornerView CornerRadius="20" RoundedCorners="TopRight">
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Green"/>
      </controls:RoundedCornerView>

      <controls:RoundedCornerView CornerRadius="20" RoundedCorners="BottomRight">
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Blue"/>
      </controls:RoundedCornerView>

      <controls:RoundedCornerView CornerRadius="20" RoundedCorners="BottomLeft">
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Purple"/>
      </controls:RoundedCornerView>

      <controls:RoundedCornerView CornerRadius="20" RoundedCorners="All" >
        <BoxView HeightRequest="100" WidthRequest="100" BackgroundColor="Black" />
      </controls:RoundedCornerView>
    </StackLayout>
```

![screenshot-1537560408080](https://user-images.githubusercontent.com/12549812/45903961-dbdf9180-bdc1-11e8-809a-e7da656720a3.jpg)

**Comment by samhouts** [comment]
Thank you for the feedback. The `CornerRadius` property supports a uniform value, which will apply to all corners, but it also supports specifying the values for all four corners separately, like so:

```
CornerRadius = "0,20,0,20"
```

This translates to `topLeft = 0, topRight = 20, bottomLeft = 0, bottomRight = 20`.

I believe this satisfies your suggestion, but let us know if it does not.

**Comment by ederbond** [comment]
woow. That is amazing. Thanks @samhouts.

**Comment by ederbond** [comment]
Hello @samhouts, the <Frame> view is not behaving as expected when trying to control individual corners like you mentioned. I have created a brand new Xamarin.Forms project on VS 2017, also updated the XF nuget package to the latest version 3.2.***.


Here is the XAML of my page:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:FrameTest" x:Class="FrameTest.MainPage">

    <StackLayout>
        <Frame BorderColor="Red" CornerRadius="10" HeightRequest="200" WidthRequest="200" VerticalOptions="Center" HorizontalOptions="CenterAndExpand"/>
        <Frame BorderColor="Blue" CornerRadius="10,0,10,0" HeightRequest="200" WidthRequest="200" VerticalOptions="Center" HorizontalOptions="CenterAndExpand"/>
    </StackLayout>

</ContentPage>
```
And here is the result on android:


![screenshot-1537649548662](https://user-images.githubusercontent.com/12549812/45921678-4eb73e00-be90-11e8-8074-be4a0dcea6ea.jpg)

Note that the blue frame is not rounding the cornes as expected.

On iOS the blue frame is not render at all. It just shows the red one...
Could you reopen this as a bug ?
