### ISSUE TITLE
[Core] LogWarningsToApplicationOutput doesn't work because Debug.* calls are stripped from forms release binary

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3873]
### Description

The changes made here
https://github.com/xamarin/Xamarin.Forms/pull/2911
https://github.com/xamarin/Xamarin.Forms/pull/2911/files#diff-53e5e1990ef7edb7111d2ee76b8b3436R67

Don't work because the Forms dlls are compiled as release so all Debug.* calls get stripped 

From dotpeek
![image](https://user-images.githubusercontent.com/5375137/45909705-b00fdc00-bdc0-11e8-9d15-6c54fa27d362.png)

### Steps to Reproduce

1. create a project
2. add forms 3.3
3. setup an invalid binding
4. nothing will get output about that

### Expected Behavior
Invalid binding should show up in debug output

### Actual Behavior
Invalid binding don't show up

### Basic Information

- Version with issue: 3.3
- Last known good version: 3.3

### Reproduction Link
[BindingMessageErrors.zip](https://github.com/xamarin/Xamarin.Forms/files/2407274/BindingMessageErrors.zip)

**Comment by StephaneDelcroix** [comment]
🤦‍♂️
