### ISSUE TITLE
Separate repo for fake store app

### ISSUE THREAD

**Issue by IoTFier** [xamarin/Xamarin.Forms#3877]
### Description
Hi @jassmith, @davidortinau,

Just like Gastropods repo on David's GitHub repo, will it be possible to post a separate working repo of the fake (google) store app?
https://github.com/xamarin/Xamarin.Forms/tree/shell/Xamarin.Forms.Controls/XamStore

Thanks

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by davidortinau** [comment]
@IoTFier sure, I can harvest a sample that shows this deeper sample.

**Comment by StephaneDelcroix** [comment]
that example is no longer up-to-date
