### ISSUE TITLE
[Enhancement] Create ListView CellHeight property

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#3880]
### **Rationale**

`HasUnevenRows` property doesn't seem to work uniformly across all platforms. There seems to be a strange coupling with `RowHeight` as well, as explained [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview.hasunevenrows?view=xamarin-forms). Both of these properties can potentially be made obsolete in favor of `CellHeight` which is a struct similar to GridLength when we add row definitions to a Grid.

### **Implementation**

```
public static readonly BindableProperty CellHeightProperty // type: CellLength, default: CellLength.Default

public enum CellUnitType
{
        Default,
	Absolute,
	Auto
}

public struct CellLength
{
      // getters
      public CellUnitType CellUnitType
      public bool IsDefault
      public bool IsAbsolute
      public bool IsAuto
      public int Value

     // static objects
     public static CellLength Default
     public static CellLength Auto

      // constructors
      public CellLength(int value)
      public CellLength(int value, CellUnitType type)

     // also add Equals, GetHashCode, ToString, and implicit operators
}

CellLengthTypeConverter for converting strings into CellLength
```
### Backward Compatibility

Both `HasUnevenRows` and `RowHeight` need to function as-is, but marking them obsolete and encouraging the use of `CellHeight` should be the preferred way.

Note: `ItemHeight` can be another name choice, but we should make sure whatever name is chosen, it meshes with the rest of the new names.

**Comment by samhouts** [comment]
We're planning to remove the concept of Cells with CollectionView (#3172). We have no plans to add significant features to Cells/ListView. Thank you!
