### ISSUE TITLE
BoxView corner radius

### ISSUE THREAD

**Issue by dirivero** [xamarin/Xamarin.Forms#3884]
### Description
BoxView's CornerRadius introduced in XF 3.2 is not density independent on android devices.

### Steps to Reproduce

Include this code in any page:
`<BoxView BackgroundColor="Blue" HeightRequest="100" CornerRadius="50" />`

### Expected Behavior

Image 1 (taken from an iOS device):
<img width="277" alt="image1" src="https://user-images.githubusercontent.com/7670773/45956111-1aef2c00-bfe8-11e8-84a4-f2c348bc1576.png">

### Actual Behavior

Image 2 (taken from a 320dpi android device):
<img width="306" alt="image2" src="https://user-images.githubusercontent.com/7670773/45956334-9bae2800-bfe8-11e8-80c1-ab95188e0716.png">

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: N/A
- IDE: VS MAC
- Platform Target Frameworks:
  - Android: >= API 19

I guess using `Context.ToPixels(...)` in `UpdateCornerRadius` method in this renderer should fix it: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/BoxRenderer.cs

**Comment by AmrAlSayed0** [comment]
This is already merged but not released #1998
