### ISSUE TITLE
NavigationPage modifies StatusBar text color so you cannot define NavigationBar text color and statusbar text color seperately

### ISSUE THREAD

**Issue by dogancoruh** [xamarin/Xamarin.Forms#3888]
I have an enterance xaml "WelcomePage" to welcome end user in my xamarin forms app.
Background is a blurred image so there is no navigation bar and statusbar text color must be white because of the colors...
When i set the statusbar color with the classical approach (View-controller based setting > NO and setStatusBarStyle blabla...) it works. But if i push the WelcomePage embedded in a NavigationPage, it makes the statusbar text color black. If i set BarTextColor to white. I solves but i ruins the next pushed page bartextcolor because next page's bar is white. So text is white, background is white... white empty bar problem... I tried to set pushed page's BarTextColor to black in OnAppearing but Statusbar changes too...
This statusbar text change behavior is not a good approach i think... can you find a way to set them seperately. Maybe extra properties to set statusbar background and text colors...

**Comment by samhouts** [comment]
@dogancoruh Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
