### ISSUE TITLE
Xmarin Form on MAC - using Xcode 10 & iOS 12 - doesn't run on Simulator

### ISSUE THREAD

**Issue by xuanmaithanh** [xamarin/Xamarin.Forms#3906]
### Description
After I update the Xcode to v10 to support iOS 12, I can't run the build on iOS Simulator 
### Steps to Reproduce

1. Open the project on MAC by Visual Studio MAC, using Xcode 10 to support iOS 12
2. Build the project --> OK
3. Run with simulator (IPhone X iOS 12) --> can't run due to unexpected issue

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
seems to work fine here. Can you send some screenshots. what version of Xamarin.Forms.

Does a Xamarin.iOS app run ok?

maybe a repo of a project your are using ? thanks

**Comment by AmrAlSayed0** [comment]
I had a problem that might be related to this. I updated Xcode to 10 but didn't open it after and then tried to run iOS 12 simulator from VS for MAC but it didn't work. Only when I ran the new Xcode it downloaded extra tools it was missing and the simulator (through VS for MAC) ran correctly.

Might help you.

**Comment by rmarinho** [comment]
Right so that's something normal related with Xcode and not forms. 

So closing as this is not related.

**Comment by xuanmaithanh** [comment]
thanks all for the advice, it's working now
