### ISSUE TITLE
[WPF] Height of items not consistent

### ISSUE THREAD

**Issue by MartinWegner** [xamarin/Xamarin.Forms#3913]
### Description
When adding and removing a contentview from a stacklayout the height is not consistent.

### Steps to Reproduce
1. Open Reprocase
2. Click Show, Hide, Show

### Expected Behavior
Height is always the same. I don't know if big or small is correct, but it should be consistent.

### Actual Behavior
Height changes from the first display to the second.

### Basic Information
- Version with issue: 3.3.0.840541-pre1 and before
- Last known good version: none 
- IDE: Microsoft Visual Studio Enterprise 2017 Version 15.8.0
- Platform Target Frameworks: 
  - WPF: 4.7

### Reproduction Link

[ReproCase_Heightrequest.zip](https://github.com/xamarin/Xamarin.Forms/files/2422679/ReproCase_Heightrequest.zip)

**Comment by mohachouch** [comment]
Thank you for the reproduction which displays the behavior.
