### ISSUE TITLE
How to Access iOS 12 TextContentType Property in Xamarin Forms

### ISSUE THREAD

**Issue by zumrywahid** [xamarin/Xamarin.Forms#3916]
### Description
I want to accès the UITextfield property of reading incoming OTP code in Xamarin Forms application. i tried it in the Entry field , but i cannot find the the property

Can someone help me? i have updated the Visuals studio for mac to support Xcode 10.0

**Comment by rmarinho** [comment]
You will need to create a CustomRenderer, you can read more how to do it [here](https://developer.xamarin.com/samples/xamarin-forms/CustomRenderers/Entry/)

**Comment by thomasgalliker** [comment]
@zumrywahid here is a ready-to-use CustomEntryRenderer which extends Xamarin Form's Entry: https://github.com/thomasgalliker/CrossPlatformLibrary/blob/0af9f1e376eb9392249915959c278ed7315f6821/CrossPlatformLibrary.Forms.iOS/Renderers/CustomEntryRenderer.cs#L125
