### ISSUE TITLE
ListView crash: NSInternalInconsistencyException Reason: Attempt to create two animations for cell

### ISSUE THREAD

**Issue by rogihee** [xamarin/Xamarin.Forms#3917]
### Description
Sometimes when navigating to a page, app crashes when resetting the ItemsSource on a ListView. The source is an "unconventional" use of a ObservableCollection. 

### Steps to Reproduce
1. Create ViewModel with ObservableCollection with items
2. Let Page listen to ViewModel changes in OnPropertyChanged 
3. Reset the ItemsSource in OnPropertyChanged
4. ListView crashes because it tries to create two "Delete" animations for same rows, perhaps a race condition, on line 560 of the ListViewRenderer.
[stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/2423952/stacktrace.txt)

### Basic Information

- Version with issue: 3.2.0
- Last known good version:
- IDE: VS18.5.1
- Platform Target Frameworks: 
  - iOS:  11.14.0.14
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
Hi I have tried to repo but wasn't able, you mind attach a small sample project or tweak this one to see if we can reproduce. 

I used the ItemsPage, first tab 

[TheLittleThingsPlayground-master.zip](https://github.com/xamarin/Xamarin.Forms/files/2428672/TheLittleThingsPlayground-master.zip)

**Comment by samhouts** [comment]
@rogihee Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
