### ISSUE TITLE
HttpClient not accepting Authorization headers (401 Unauthorized)

### ISSUE THREAD

**Issue by dush88c** [xamarin/Xamarin.Forms#3918]
I have used **System.Net.Http** to create an HTTP client to access the Web API GET method which is authorized as below. But it returns **unauthorized** (401) error always even if it works fine in Postman with same authorization token (**Bearer**)

```
using (var ProfileClient = new HttpClient())
            {
                var token = OAuthToken.Instance.AccessToken;
                ProfileClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                
                var response = await ProfileClient.GetAsync(AppSettings.AbbottAuthorizationProfileUrl);
                
                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    return CheckProfileReturn(response);
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.Unauthorized)
                {
                    return new Tuple<bool, string>(false, "Unauthorized access");
                }
                else
                {
                    var result = await response.Content.ReadAsStringAsync();
                    var errorModel = JsonConvert.DeserializeObject<OauthError>(result);
                    return new Tuple<bool, string>(false, errorModel?.ErrorDescription);
                }
            }
```

I have no idea why this is not working in Xamarin.Forms httpclient ?
Versions 
Xamarin Forms : 2.4.0.280
System.Net.Http : MonoAndroid\v1.0\4.0.30319 
![http](https://user-images.githubusercontent.com/9262431/46144938-1e024a80-c27c-11e8-8a17-1390cad4cf6f.JPG)
.Net : 4.5

Thanks

**Comment by rmarinho** [comment]
Hi this doesn't seem a issue related with Xamarin.Forms itself.

Trying to help you might want to migrate to use the latest version of Xamarin Forms like 3.2.0 that uses netstandard .

You should inspect the headers of the call to see how the request is form. also might want to check if its a https issue or something.

Feel free to reopen if you figure is something wrong with Xamarin.Forms.

Thanks

**Comment by Adincodavid** [comment]
@dush88c dis you solved this issue??
I have the same problem

**Comment by dush88c** [comment]
In my case, there was '/' at end of the url. Once it's removed. It worked.

**Comment by amirvenus** [comment]
I have the same issue 
I can obtain the token using MSAL and in fact, I can use that bearer token in Postman but when I pass it to my HttpClient, I keep getting 401.

I think this is rather a mono bug...

**Comment by poorankharol** [comment]
I have the same issue does not work on android app but works on postman

**Comment by Mirazyzz** [comment]
@amirvenus @rmarinho did you found out the reason of this issue?
