### ISSUE TITLE
 FreshTinyIoC.TinyIoCResolutionException

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#3921]
### Description
Getting exception on starting itself

> FreshTinyIoC.TinyIoCResolutionException: Resolve failed: myPageModel - Reason: /system/lib/libsqlite.so

App.xaml.cs

```
InitializeComponent();
FreshIOC.Container.Register<IContactRepository, ContectRepository>();  
var mainPage = FreshPageModelResolver.ResolvePageModel<AddContactPageModel>();
MainPage = new FreshNavigationContainer(mainPage);
```

I am using FreshMvvm & SQLite to my project. I have installed 3 libraries from nuget
1) FreshMvvm 2.2.4
2) SQLite.Net-PCL 3.1.1
3) SQLite.Net.Core-PCL 3.1.1

[I am following this article](http://bsubramanyamraju.blogspot.com/2018/03/getting-started-with-xamarin-forms.html)

### Steps to Reproduce

1. Create Xamarin.forms project & add above libraries
2. Do CRUD operation using FreshMvvm by following above article.
3. If you are following above article-- Execute app

### Expected Behavior
App should execute

### Actual Behavior
Getting crashed on startup

### Basic Information
Using xamarin forms with sqlite & FreshMvvm with visual studio IDE & the little related issue I got with same exception 

> FreshTinyIoC.TinyIoCResolutionException: Resolve failed: myPageModel - Reason: /system/lib/libsqlite.so

On XF-Previwer so I have assigned that on visual studio developer community below

https://developercommunity.visualstudio.com/content/problem/344704/an-exception-occured-while-rendering-control.html

- Version with issue:
- Last known good version:
- IDE:
Microsoft Visual Studio Enterprise 2017 
Version 15.8.1
VisualStudio.15.Release/15.8.1+28010.2003
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   4.11.7-pre (8955b2a)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Universal Windows Apps   15.0.28010.00
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Xamarin   4.11.0.732 (d15-8@33e83e124)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.218 (79f535bdd)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.113 (e1d02a7)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.18 (HEAD/3d8a28f1a)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.13 (373c313)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots

![xfsc1](https://user-images.githubusercontent.com/19743421/46152783-5c553500-c28f-11e8-91a5-01831e04cebc.png)

![xfsc2](https://user-images.githubusercontent.com/19743421/46152800-62e3ac80-c28f-11e8-9d02-e319fd716ad2.png)

![xfsc3](https://user-images.githubusercontent.com/19743421/46152815-6a0aba80-c28f-11e8-9206-fd89b7d73a47.png)

### Reproduction Link

> VS bug [#712428](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/712428)

**Comment by kingces95** [comment]
Please add a zipped reproduction.

**Comment by arvindrajachourasiya** [comment]
@kingces95 - I am attaching my xamarin forms project here

[TestProjectFresh.zip](https://github.com/xamarin/Xamarin.Forms/files/2442641/TestProjectFresh.zip)

Even xamrin forms previewer showing the same exception

![previer](https://user-images.githubusercontent.com/19743421/46421554-f7e31b80-c74f-11e8-84ef-22e3b5a3348c.png)

**Comment by hartez** [comment]
The SQLite.Net-PCL NuGet package you're using is an older version and doesn't support more recent Android versions. I suspect that's why you are having problems.

If you move to [sqlite-net-pcl](https://www.nuget.org/packages/sqlite-net-pcl) it should work on more recent Android versions.

**Comment by arvindrajachourasiya** [comment]
@hartez - You suspect , that's you close ticket, ridiculous. Did you check the same code base using  _sqlite-net-pcl_  whether working or not?

**Comment by arvindrajachourasiya** [comment]
Experiencing same issue with _sqlite-net-pcl_  too

![sqlitefresh](https://user-images.githubusercontent.com/19743421/47204132-2f80d300-d3a0-11e8-92ee-4aef7cf1842a.png)

**Comment by hartez** [comment]
> @hartez - You suspect , that's you close ticket, ridiculous. Did you check the same code base using _sqlite-net-pcl_ whether working or not?
> 

Yes, I did. And it worked fine.

I say "suspect" because I had to modify your repro project in order to get it building at all. There were several errors in your AndroidSQLite.cs file.  After fixing them, I got the error shown in your first screenshot (which is a different error than the one shown in your second screenshot). I updated to sqlite-net-pcl, fixed the namespaces, built the project, and ran it. It started up just fine. Here's a screenshot:

![screenshot_1539973843](https://user-images.githubusercontent.com/538025/47236929-cfd3f900-d39a-11e8-825a-4c373551ca56.png)

So I say "suspect" because it's possible you are running very different code than the code I updated. Anyway, here's you repro project, fixed:

[TestProjectFresh Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2496939/TestProjectFresh.Repro.zip)

**Comment by arvindrajachourasiya** [comment]
@hartez - I have downloaded above "TestProjectFresh" provided by you. Still I am not able to open screens/xaml files in Xamarin.Forms Preview window. The above screenshot you have provided doesn't seem that is from XF Previewer. The issue I have assigned is totally upon Previewer window only. Please have a look on this screenshot from repository provided by you. 
![freshtyni](https://user-images.githubusercontent.com/19743421/47280458-225c2200-d5f4-11e8-96e5-2cc00b36406a.png)

**Comment by hartez** [comment]
Okay, this appears to be a Previewer bug. The error occurs on the VS for Windows previewer with version 15.8.7.  VS for Mac with version 7.6.9 also appears to have a similar problem, but I can't see the actual error message to be sure.

VS for Mac 7.7 preview (build 1710) displays the page in the Previewer without error. However, the problem still happens on Windows with 15.9.0 Preview 4.0.

**Comment by samhouts** [comment]
I tested this with 16.0.0 Preview 4 SVC1, and this is no longer an issue. Thanks!
