### ISSUE TITLE
[iOS] Rapidly clicking span on UI test 3525 throws a null exception on simulators

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#3930]
### Description

I was running UI test 3525 on iOS 12.0 simulators and ran into an issue. If you click the "Clickable" label several times quickly, it's going to throw a null exception. The issue seems to be coming from `CreateChildRecognizerHandler` of `EventTracker` because ['childGestures'](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.iOS/EventTracker.cs#L180) is null.

Note that I did not test this on a physical device and don't know if the issue exists there.

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/46388960-fab81080-c66a-11e8-9438-e68603b80588.png)
Reproduced exception as described.

**Comment by AndreiMisiukevich** [comment]
5 taps cause it
Related commit @hartez  dd3ebdfa3b1b5a8bdac0d0f3ade529eb4aed2e90
