### ISSUE TITLE
IsEnabled property is not working for View Renderer

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#3931]
### Description

Hi Team,

We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin.

We would like to bring to your notice a bug that we encountered recently Xamarin.Forms.VisualElement .IsEnabled bool property is not working for CustomContentView renderers. To replicate the issue I have prepared the sample with following use cases.
1. CustomContentView is derived from ContentView
2. CustomLabel is  derived from Label. And added this customLabel to CustomContentView
3. Write render-er for both of the view.
5. I have set IsEnabled property as false to either CustomContentView or CustomLabel
6. Now In onTouch event of render-er class I am doing interactions (I have changed the CustomLabel backgroundcolor). View backGround color gets changed.

  As per the IsEnabled Property behavior hit rest was restricted to the View , But here I am able to do interactions in view render-er. The same was tested by setting IsEnabled as false to Label also.  But here , IsEnabled property does allow the interactions which is issue. Bug has replicated in Xamarin Forms all platforms.

### Steps to Reproduce

1. Run the sample
2. Touch MyLabel Text
3.  you can able to see view background color gets changed.

### Expected Behavior
1.  If InEnabled as false to the View, View should not allow any interactions, This case fails while writing render-er class and doing interactions.

### Actual Behavior
2. If IsEnabled as false,  View renderer allows Interaction 

### Basic Information

- Version with issue:
- Last known good version:  3.1.0.583944
- IDE:
- Nuget Packages: 2.4.0.280
- Affected Devices: All devices in all platforms

Reproduction Sample link

http://www.syncfusion.com/downloads/support/directtrac/general/ze/IsEnabled928215761

**Comment by rmarinho** [comment]
Hi the correct way might be to use` InputTransparent = true ` Let me know if that helps.

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @rmarinho  
InputTransaparent = true helps to avoid touch interactions which is fine, but while setting IsEnabled false changing View color as Light gray also notify view is not enabled and view does not handle any interactions. So I want same behavior as IsEnabled holds.

**Comment by hartez** [comment]
In your repro, you're deriving your `CustomContentViewRenderer` from `VisualElementRenderer<CustomContentView>`. The `VisualElementRenderer` class does not provide any handling of the `IsEnabled` property, so setting `IsEnabled` on your `CustomContentView` has no effect.

If you are going to derive from `VisualElementRenderer`, you will have to provide your own handling of the `IsEnabled` property. For example, in your `OnTouchEvent` override, you could change you code to this:
```
public override bool OnTouchEvent(MotionEvent e)
{
    if (Element != null && Element.IsEnabled)
    {
        ((this.Element.Content) as CustomLabel).BackgroundColor = Color.Green;    
    }
    
    return base.OnTouchEvent(e);           
}
```
in order to ignore the touch events if `IsEnabled` is set to `true`.
