### ISSUE TITLE
Picker/Datepicker/timepicker PlaceholderColor

### ISSUE THREAD

**Issue by seddik** [xamarin/Xamarin.Forms#3935]
### Description
There is no property for the placeholdercolor like the other components
### Steps to Reproduce

property to be implemented

### Expected Behavior
mypicker.PlaceholderColor=Colors.Pink;
### Actual Behavior
no implemented

**Comment by jfversluis** [comment]
I think this is fixed with #4701

Although not for DatePicker and TimePicker, but I will create a separate issue for that

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
