### ISSUE TITLE
Use UIPopoverPresentationController for Pickers on large(r) screen devices

### ISSUE THREAD

**Issue by j4m3z0r** [xamarin/Xamarin.Forms#3937]
At present, using a Picker on iPad results in a giant widget appearing at the bottom of the screen. I've been looking, and haven't been able to find any examples of this style of picker being used on modern apps on iPad. With the larger screen real estate on the iPad (and on most phones nowadays), I think using a popover to display lists of options is probably more appropriate. Aside from anything else, it will provide a visual cue to the user as to what it is that they're selecting.

There are some separate tickets open about making popover views available in general so that we can fill them with whatever content we want. However the case I'm making here is that it makes sense for the default rendering of Pickers on iPad (at least) be updated. This way Pickers on Mac and Pickers on iPad will work roughly the same.

**Comment by j4m3z0r** [comment]
Here's a screengrab from the Notes app on iPad showing the style of widget that seems to be commonplace for Pickers:

![img-0031](https://user-images.githubusercontent.com/3580291/46230882-d2ed4380-c31e-11e8-8644-62de947bea1a.PNG)

**Comment by jfversluis** [comment]
To be complete, you also have a screenshot of how it happens in XF now? I can have a look at this.

**Comment by j4m3z0r** [comment]
Hi, thanks for picking this up. I’ll get you a screenshot when I’m back at my computer tomorrow.

You’re correct that the notes example is not directly comparable, however I looked through pretty much all the Apple apps on my iPad (and a bunch of prominent third party apps), and couldn’t find any examples of the traditional picker (the one that slides up from the bottom of the screen) used anywhere — this was the cleanest example of selecting an something from a list of strings that I could find.

Definitely open to other ways of displaying lists of options, but the old style picker control seems to be effectively deprecated at this point.

**Comment by j4m3z0r** [comment]
Here's a screenshot from the Xamarin Forms Samples. Note that the picker is taking up a huge chunk of the screen, and there's nothing to indicate what it is that you are "picking".

![img_0032](https://user-images.githubusercontent.com/3580291/46304252-03bdba80-c563-11e8-9256-5b1031854ed2.PNG)

**Comment by jfversluis** [comment]
I (very) briefly looked into this but didn't find any apparent setting for this, I would expect it shouldn't be too hard and we would not have to build anything custom. But I'm open to suggestions!

**Comment by j4m3z0r** [comment]
Ok, thanks for that. Perhaps the place to start is whether or not my view that the existing solution is effectively deprecated is a controversial one? I wasn't able to find another iPad app that uses this style of widget any more -- did you find anything recent that uses it?

**Comment by j4m3z0r** [comment]
Good call on checking Safari — I didn’t think of that! That feels like the clearest guidance we’ll get on what current best practices are — Apple’s HIG seems not to be as updated as quickly as industry tastes evolve.

Regarding implementation, I also found [this](
https://www.raywenderlich.com/3127-ipad-tutorial-for-ios-how-to-port-an-iphone-application-to-the-ipad) which included this snippet I hadn’t seen before for switching behavior based on whether you’re on iPhone or iPad:

    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad) {

So that might be a good tool for choosing the right behavior for the device, though I’m guessing XF already contains something similar.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
