### ISSUE TITLE
[Error] ListView's Header and Footer is not working in WPF

### ISSUE THREAD

**Issue by JaeWangL** [xamarin/Xamarin.Forms#3947]
### Steps to Reproduce
1. Add ListView with Header
```
                <ListView Grid.Row="2"
                          ItemsSource="{Binding KeyPoints}">
                    <ListView.Header>
                        <StackLayout>
                            <Label Text="TEST" />
                        </StackLayout>
                    </ListView.Header>
                </ListView>
```
2. Build and Debug
3. Have no result in Header

### Expected Behavior
ListView's Header and Footer is working properly

- Version with issue: 3.2.0.839982
- IDE: Visual Studio 2017, 15.8
- Platform Target Frameworks: WPF

**Comment by jsuarezruiz** [comment]
Related to #3770.
