### ISSUE TITLE
After compiling Android, I have to restart VS before I can compile iOS

### ISSUE THREAD

**Issue by bgege** [xamarin/Xamarin.Forms#3950]
### Description
It is a shared library project. We work on Windows, in Visual studio. After any Android debugging, if i also want to compile iOS, I have to restart Visual Studio.

Pressing the "play" button doesnt do anything, nothing in the Output or Build windows

We use the Hyper-v emulator

**This issues is reproduced exactly the same on 2 developer laptops**

### Steps to Reproduce

1. Press Debug ("green play") button on Android
2. After app successfully launched, press Stop debugging
3. Switch the startup project over to iOS
4. Press Debug button again

### Expected Behavior
Application compiles

### Actual Behavior
Nothing happens

If I restart visual studio, this time opening with the iOS as the default startup project, then it compiles and debugs with no problems. Switching from iOS back to Android also works. 

### Basic Information

- Version with issue:  Xamarin Forms 3.2,  Xamarin plugin 4.11.0.776
- Last known good version: Worked in Xamarin 3,0
- IDE: Visual studio 1.8.5
- Platform Target Frameworks: 
  - iOS:  Xamarin.Ios 12.0.0.15
  - Android: 9.0.0.19

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Virtual machiens

**Comment by samhouts** [comment]
@bgege Are you still experiencing this issue?

**Comment by bgege** [comment]
@samhouts No, because I havent touched done any X-platform Xamarin development in a long time, only apps that target a single platform. So I cannot confirm if this isssue still exists.

**Comment by samhouts** [comment]
@bgege Thanks for getting back to me! I'll go ahead and close this for now, but if you have any other issues in the future, please let us know!!
