### ISSUE TITLE
I am not getting the .xaml.cs under the .xaml file.

### ISSUE THREAD

**Issue by anirudhagupta** [xamarin/Xamarin.Forms#3951]
tested in community VS 2017 (have installed uninstall many time) problem still the same. .xaml file and .xaml.cs file are not collpase exapanded under each other as it's work in wpf and last time it's functioning same in xamarin project too.

Is it known bug, I have created many .xaml file in my xamarin project and it's never look like working. Am I missing some settings that can be enabled to make it work.

Thanks

**Comment by WarBorg** [comment]
@guptaanirudha what type of project are you using ? a .net standard one or PLC ? also do you have the xamarin.forms nuget package installed in that project?

**Comment by WarBorg** [comment]
@guptaanirudha ahh I was asking because I had a similar issue with .net standard and I had to clear the csporj and reinstall the nuget package, but on shared projects I have no experience sorry

**Comment by guptaanirudha** [comment]
@WarBorg  thanks for help,

I have this issue from last few weeks, Happening with every shared project I tried, here is the screenshot

![image](https://user-images.githubusercontent.com/35772421/46287236-78aee580-c59f-11e8-8b01-ae9d8c1296cd.png)

**Comment by WarBorg** [comment]
but the App.xaml.cs looks ok, maybe you can take a look in the csproj file (xml mode) and see if you can find any differences between the App.* file and Posts.* file

**Comment by mgoertz-msft** [comment]
Make sure your code-behind file has a dependent upon tag in the csproj that refers back to the XAML file like this:

```
    <Compile Include="MainWindow.xaml.cs">
      <DependentUpon>MainWindow.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
```

**Comment by guptaanirudha** [comment]
@mgoertz-msft 

I open the .csrproj file of my shared project. It's show me this 

![image](https://user-images.githubusercontent.com/35772421/46387775-fd0b8080-c6e5-11e8-82e8-562e9691a5fe.png)

please check where I can put that thing.

I tested this on 2 machine. On one computer I create a new project thing work fine.
I tested on 2nd machine and it's not dependent. Please check the screenshot, Is that thing code need to be in shared project's .csproj file or it must be somewhere else because of shared project.

**Comment by mgoertz-msft** [comment]
@guptaanirudha Thank you for sharing the screenshot. What does the Rnivedita.projitems file look like?

**Comment by guptaanirudha** [comment]
@mgoertz-msft  here is the file https://github.com/rnivedita/Rnivedita-Mobile/blob/master/Rnivedita/Rnivedita/Rnivedita.projitems

**Comment by StephaneDelcroix** [comment]
@anirudhagupta we don't have the rights to open your linked `.projitems`. could you please point @mgoertz-msft and us to the correct file ? thanks

**Comment by anirudhagupta** [comment]
I didn't get any response after my last message so I remove that repos. I will reproduce it in my free time.
