### ISSUE TITLE
[iOS] Deprecate the `Page.UseSafeArea` property

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#3965]
## Summary

The `Page.UseSafeArea` property is a bit strange in that it directly changes the Padding property. We might consider deprecating it and directing users to the `Page.SafeAreaInsets` property instead.

## API Changes

Remove `Page.UseSafeArea`

**Comment by jfversluis** [comment]
Thanks for this suggestion (no really Samantha, thank you!)! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
