### ISSUE TITLE
ListView RowHeight Affects The GroupHeader

### ISSUE THREAD

**Issue by OmerHmead** [xamarin/Xamarin.Forms#3970]
### Description
When setting the grouped list's RowHeight to a specific value it will affect the items as well as the GroupHeader

### Steps to Reproduce

1. Create a ListView with GroupHeader
2. Set ListView RowHeight to a value other than the default (say 100)

### Expected Behavior
Only the Items height should be affected

### Actual Behavior
The RowHeight will be applied to Items and GroupHeader

### Basic Information

- IDE:Visual Studio 2017 v15.6
- Platform Target Frameworks: 
  - iOS:   tested on 12.0 simulator and device
  - Android: tested on 8.0 simulator and device
### Screenshots
![iosimage](https://user-images.githubusercontent.com/41253169/46353423-d2c5ae80-c664-11e8-9422-518e218695bd.png)
![androidimage](https://user-images.githubusercontent.com/41253169/46353425-d5280880-c664-11e8-95ba-c5971a28a478.png)

### Reproduction Link

[ListViewRowIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2438104/ListViewRowIssue.zip)

**Comment by kingces95** [comment]
I'mg closing this because changing it now would break the behavior of those who are relying on that layout. Right? If the behavior has regressed from a previous version that we'll restore it. 

Can you work around by apply `Height` to the `GroupHeaderTemplate`'s `ViewCell`?

**Comment by OmerHmead** [comment]
Thank you, this workaround works only if the `HasUnevenRows` is set to `True` .

I'm sorry I forgot to mention in the bug that it only happens when the `HasUnevenRows="False"` which is my case (I need to have it set to `False` for the performance side effect of it, I have heavey cells)

Maybe we can have a new property `GroupHeaderRowHeight` to specify the default row height for the group header?

**Comment by Omarkth** [comment]
test
