### ISSUE TITLE
[Android,UWP] Image no longer showing up for Issue1914 which is using an Absolute Layout

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3972]
#### Android
Run Issue1914 in the Gallery on Android and you should see a rotating bank in the middle of the device

I'm pretty sure this only effects the AbsoluteLayout. If you change the base class to StackLayout then the bank appears.

If you remove the animation the issue still exists

#### UWP
I'm not sure if this ever worked on UWP. UWP I tested back to 3.1.0 and it still doesn't work.
If fixing the Android regression doesn't fix UWP then might just open a new issue for fixing on UWP

#### iOS
Tested on iOS and it seems to work fine

### Steps to Reproduce

1. Run Xamarin.Android Control Gallery
2. Go to Issue 1914

### Expected Behavior
You should see a rotating bank in the center of the screen

### Actual Behavior
The screen is blank

### Basic Information

- Version with issue: 3.3
- Last known good version: 3.2

### Screenshots

Running on 3.3 
![image](https://user-images.githubusercontent.com/5375137/46372437-5f15a880-c648-11e8-9741-0294d1ac90ed.png)

Running on 3.2
![image](https://user-images.githubusercontent.com/5375137/46372732-3641e300-c649-11e8-9b99-f3889e860019.png)

**Comment by paymicro** [comment]
Why are proportional widths and heights equal to 100 in 1914 UItest? The documentation says that they should be between 0 and 1.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/absolute-layout#proportional-values

I think PR https://github.com/xamarin/Xamarin.Forms/pull/3388 fixes this issue
