### ISSUE TITLE
[Android] Label not wrapping text after pre-release 3.3.0

### ISSUE THREAD

**Issue by ivancea** [xamarin/Xamarin.Forms#3973]
### Description
Labels are not wrapping text in Android since 3.3.0 pre-releases.

### Steps to Reproduce

1. Create a Contentpage with a Label inside
2. Add a long text to the label

Example:
```
<ContentPage.Content>
    <StackLayout>
        <Label Text="Welcome to Xamarin.Forms Welcome to Xamarin.Forms Welcome to Xamarin.Forms !"/>
    </StackLayout>
</ContentPage.Content>
```

### Expected Behavior
The label text should wrap.
3.2.0 Android screenshot:
![imagen](https://user-images.githubusercontent.com/5280509/46378111-ebe95200-c69a-11e8-881d-915ce3ccd2ad.png)

3.3.0 UWP, PC screenshot:
![imagen](https://user-images.githubusercontent.com/5280509/46377998-914ff600-c69a-11e8-9012-e18f60b17100.png)

### Actual Behavior
The label text won't wrap and a part of the text won't be shown.

3.3.0 Android screenshot:
![imagen](https://user-images.githubusercontent.com/5280509/46377916-5cdc3a00-c69a-11e8-920f-b286cb9b067e.png)

### Basic Information

- Version with issue: 3.3.0.871608-pre2
- Last known good version: 3.2.0.839982
- IDE: Microsoft Visual Studio 2017 Community
- Platform Target Frameworks:
  - Android: Minimum: 4.0.3, Target: 8.1
  - UWP:  16299
- Android Support Library Version: v7
- Nuget Packages: Xamarin Forms, Xamarin Essentials, NETStandard v2.0.3, ...
- Affected Devices: Tested in a Xiaomi Mi5 and AVD

**Comment by hartez** [comment]
@ivancea This should be fixed in the next prerelease by #3936.
