### ISSUE TITLE
Android linking error with Xamarin.Forms 3.2. 

### ISSUE THREAD

**Issue by axelgorris** [xamarin/Xamarin.Forms#3976]
### Description

Android linking error with Xamarin.Forms 3.2. It works fine with Xamarin.Forms 3.1.

This method is the one failing to link correctly: 

> Android.Views.ScaleGestureDetector Xamarin.Forms.Platform.Android.GestureManager::InitializeScaleDetector()

### Steps to Reproduce

1. Build android project with Linker Behaviour set to SDK assemblies only
2. A "LinkAssemblies" error appears

### Expected Behavior

The project builds correctly

### Actual Behavior

The following error appears:

> (SignAndroidPackage target) (1) ->
(_LinkAssembliesShrink target) -> 
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly. projectname.Mobile.Droid.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2053,5): error MSB4018: Mono.Linker.MarkException: Error processing method: 'Android.Views.ScaleGestureDetector Xamarin.Forms.Platform.Android.GestureManager::InitializeScaleDetector()' in assembly: 'Xamarin.Forms.Platform.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.V4.View.ScaleGestureDetectorCompat::SetQuickScaleEnabled(Android.Views.ScaleGestureDetector,System.Boolean) 

### Basic Information

- Version with issue: 3.2
- Last known good version: 3.1
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 7.0
  - UWP:  N/A
- Android Support Library Version: 25.4.0.2
  - Xamarin.Android.Support.v4 25.4.0.2
  - Xamarin.Android.Support.Design 25.4.0.2
  - Xamarin.Android.Support.v7.AppCompat 25.4.0.2
  - Xamarin.Android.Support.v7.CardView 25.4.0.2
  - Xamarin.Android.Support.v7.MediaRouter 25.4.0.2
  - Xamarin.Android.Support.Fragment 25.4.0.2
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
I'm unable to reproduce this on 3.3.0 head. Is there something I need to do besides simply change the linking setting and try and compile the template project?

**Comment by axelgorris** [comment]
Nevermind, it was due to dependencies changing from XF3.1 to XF3.2 (target framework and android support packages). It is now working.

**Comment by JonasSL** [comment]
Hi! I'm having the same issue. What dependency did you update to fix the problem?

**Comment by VBPrakash** [comment]
Hi,
How did you solve the issue ? Can you please provide more information on the solution ?

**Comment by denisvitez** [comment]
@JonasSL @VBPrakash 
I updated Xamarin.Android.Support libraries to v27 and this seemed to have solved the issue for me.

**Comment by axelgorris** [comment]
Sorry totally missed the replies. I just updated the android support libraries to v27

**Comment by salamoun** [comment]
I have same problem:
`error MSB4018: Mono.Linker.MarkException: Error processing method: 'Android.Views.ScaleGestureDetector Xamarin.Forms.Platform.Android.GestureManager::InitializeScaleDetector()' in assembly: 'Xamarin.Forms.Platform.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.V4.View.ScaleGestureDetectorCompat::SetQuickScaleEnabled(Android.Views.ScaleGestureDetector,System.Boolean)`

Android Support Library Version: 25.4.0.2
Xamarin.Forms 3.3.0.912540

**Comment by salamoun** [comment]
Xamarin Forms required  Xamarin.Android.Support libraries v27.

**Comment by Nickolas-** [comment]
I'm using latest Xamarin.Forms 3.4.0.* and latest Xamarin Android Support Library 28.0.0.1 and still have same issue.

**Comment by kEph13** [comment]
We're also seeing this issue with Xamarin.Forms 3.5.0.169047 and Android Support libraries 28.0.0.1

The error is:
```
The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Xamarin.Forms.Platform.Android.BottomNavigationViewUtils::SetShiftMode(Android.Support.Design.Widget.BottomNavigationView,System.Boolean,System.Boolean)' in assembly: 'Xamarin.Forms.Platform.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.Design.Internal.BottomNavigationItemView::SetShiftingMode(System.Boolean)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Orbose.Mobile.Droid			
```

**Comment by kEph13** [comment]
Based on [this file](https://github.com/xamarin/Xamarin.Forms/blob/release-3.5.0-rc1/Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs) it looks like the __ANDROID_28__ definition isn't being triggered for some reason.

**Comment by kEph13** [comment]
Ok, fixed it. It looks like you have to reinstall Xamarin Forms if you change the project targeting.

Specifically, various references that XF adds (Xamarin.Forms.Platform.Android, in my case) are hint-pathed to versioned Mono folders, and if there are processor directives they won't match up with the overall build level.
