### ISSUE TITLE
Android TabbedPage Bottom - Incorrect positioning for text and icons (3.2.0)

### ISSUE THREAD

**Issue by ben-powley** [xamarin/Xamarin.Forms#3983]
### Description
The bottom placed Android TabbedPage is rendering the text and icons incorrectly.

### Steps to Reproduce

1. Create a TabbedPage
2. Set android:TabbedPage.ToolbarPlacement="Bottom"
3. Add 4 navigation pages, each with a content page
4. Set the icon and title on the 4 navigation pages

### Expected Behavior
The tabs should render with the text beneath the icon.

### Actual Behavior
The icon and text overlap

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: 3.1.0
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 27.0.2
- Affected Devices: Default Pixel emulator running 8.0 or 9.0

### Screenshots

https://imgur.com/a/3W3bCyL

**Comment by ben-powley** [comment]
@PureWeen Potentially but I'm not sure. If I downgrade the project to Xamarin.Forms 3.1.0, the tabs render correctly (see below)

https://imgur.com/a/ZDK84B2

**Comment by kingces95** [comment]
@ben-powley If you've already got a reproduction, could you please attach it? We're happy to reconstruct the reproductions but if can get 'em for free than we'll take 'em!

**Comment by kingces95** [comment]
[App31.zip](https://github.com/xamarin/Xamarin.Forms/files/2444496/App31.zip)

**Comment by kingces95** [comment]
[FormsGallery.zip](https://github.com/xamarin/Xamarin.Forms/files/2444530/FormsGallery.zip)
This app renders text and icons to tabs correctly. If you have the reproduction which produces a layout that doesn't work please attach and reopen. Thanks!

**Comment by ben-powley** [comment]
Hey @kingces95 I've figured it out!

The issue was occurring because I didn't have a `<TabbedPage.Children>` component within my `<TabbedPage>`, whereas your example does. I noticed the Xamarin forms docs don't mention using .Children in the XAML at all so I've created a pull request for the docs as it seems to be the issue.

Thanks for your help!

**Comment by mr5z** [comment]
I have experienced the same thing and I have this kind of layout structure:

```
<?xml version="1.0" encoding="UTF-8"?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" 
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
            xmlns:views="clr-namespace:CompanyName.Views"
            xmlns:tabs="clr-namespace:CompanyName.Views.Tabs"
            xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
            android:TabbedPage.ToolbarPlacement="Bottom"
            Title="{Binding Title}" 
            x:Class="CompanyName.Views.MainTabbedPage">
    <TabbedPage.Children>
        <tabs:AdventureTabNavigationPage>
            <x:Arguments>
                <tabs:AdventureTabPage TabPosition="{Binding TabPosition}" Icon="baseline_flight_takeoff_white_18dp" />
            </x:Arguments>
        </tabs:AdventureTabNavigationPage>
        <tabs:MapTabPage TabPosition="{Binding TabPosition}" Icon="baseline_place_white_18dp" />
        <tabs:LeaderboardPage TabPosition="{Binding TabPosition}" Icon="baseline_bar_chart_white_18dp" />
        <tabs:SettingsTabPage TabPosition="{Binding TabPosition}" Icon="baseline_settings_white_18dp" />
    </TabbedPage.Children>
</TabbedPage>
```
As you may have noticed, I have the `TabbedPage.Children` specified where ben-powley considers as the solution but it didn't work in mine.

**Comment by elmotron** [comment]
@mr5z I have exactly the same problem and adding Children didn't help either. Any news on this?
