### ISSUE TITLE
[UWP] Document in the README.md the steps required to run UI Tests

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#3984]
### Description
A quick summary of the steps go 

- follow the instructions here to get the winappdriver running https://github.com/Microsoft/WinAppDriver#installing-and-running-windows-application-driver
- From the Xamarin Forms SLN launch the Xamarin.Forms.ControlGallery.WindowsUniversal project (this is what installs the app with that identifier onto your system)
- at this point you should be able to run any of the UWP tests

**Comment by emunin** [comment]
I see you labeled this hacktoberfest, so it's up for grabs? If so, what wiki needs updating? I'd love to contribute to Xamarin.Forms, but I'm new to open source and this community.

**Comment by samhouts** [comment]
It is! Here's a pretty detailed guide for how to contribute: https://blog.xamarin.com/beginners-guide-contributing-xamarin-forms/

**Comment by emunin** [comment]
Was looking at putting this under the Build from the Command line section. Is this what you had in mind?
 
 ### UI Tests ###

 ##### Run UWP UI Tests #####
To run the UWP UI Tests:
    
1. Install and run the [Windows Application Driver](https://github.com/Microsoft/WinAppDriver#installing-and-running-windows-application-driver).
2. Launch the `Xamarin.Forms.ControlGallery.WindowsUniversal` project to install the ControlGallery application onto your system.

You should now be able to run any of the UWP UI Tests.

**Comment by samhouts** [comment]
Looks good to me!
