### ISSUE TITLE
OnIdiom x:TypeArguments Default is not recognized as separate xaml attribute

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#3993]
### Description

It doesn't seem to be working using like below. I am getting

No property, bindable property, or event found for 'Default', or mismatching type between value and property.

`<OnIdiom x:TypeArguments="x:Double" Phone="150" Tablet="250" Default="300" />`

that seems to be working however

   HeightRequest="{OnIdiom Phone=200, Tablet=300, Default=350}"
is that intended?

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: Android
  - Android: android all versions 

- Nuget Packages: xamarin forms 3.2.0.871587

**Comment by kingces95** [comment]
I'm going to close this issue because it's more of a question than a bug report. That said, I'll ping @StephaneDelcroix. Short of that, please post on the forums.

**Comment by EmilAlipiev** [comment]
i think that it is a question and possible bug. Because this usage was presented in earlier versions like below
`<OnIdiom x:TypeArguments="x:Double" Phone="150" Tablet="250" Desktop="300" />`

Now the question is are we throwing away this usage and we should just use this one with 3.2
`HeightRequest="{OnIdiom Phone=200, Tablet=300, Default=350}"`

if this is not intended it looks like a bug to me

**Comment by StephaneDelcroix** [comment]
The xml-element `OnIdiom` syntax never had a `Default` property. The fact that the markup extension has one is indeed creating a discrepancy we should fix. I'm filing an enhancement request for that.

@EmilAlipiev if I'm not capturing the essence of what you're saying, feel free to comment below, and reference the version in which this used to work.

**Comment by EmilAlipiev** [comment]
@StephaneDelcroix  what do you mean by OnIdiom never had a Default property? this seems to be working for me `HeightRequest="{OnIdiom Phone=200, Tablet=300, Default=350}"`, I am seeing changes if I run on to UWP Desktop. if i have this on image i can see the change when i change default value.
But yes it will be nice to have in general, I think that OnIdiom is more often used to adjust layouts.
 

I need this in some cases for example;

**Comment by StephaneDelcroix** [comment]
that's the source code for the markup Extension, not the element-style one, accepting x:TargetType

**Comment by EmilAlipiev** [comment]
So you mean that it will not only work for` HeightRequest="{OnIdiom Phone=200, Tablet=300, Default=350}"` ?

It is quite confusing as intellisense suggest me default but compiling returns error

![image](https://user-images.githubusercontent.com/10422347/46581820-eb580f00-ca3e-11e8-84ad-1e61b29a617f.png)
