### ISSUE TITLE
Editor Placeholder's Font and FontSize on iOS are not set 

### ISSUE THREAD

**Issue by jotprabh1** [xamarin/Xamarin.Forms#4004]
### Description
Setting the Editor's FontFamily and FontSize doesn't change the Placeholder's Font and FontSize.

### Steps to Reproduce

1. Use Editor Control in StackLayout
2. Set FontFamily and FontSize properties on Editor
3. Check on an iOS device

### Expected Behavior
The FontFamily and FontSize properties set on the control should be used by the Placeholder.
 
### Actual Behavior
The placeholder uses the default FontFamilty and FontSize and it doesn't change as per the properties set on the control on an iOS device. It works fine on an android device.
### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: Unclear
- IDE: Visual Studio for Mac
- Platform Target Frameworks: iOS
  - iOS:  12

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/46562928-48ff2680-c89a-11e8-824b-3caecbf27f47.png)
Entry's with different font sizes for placeholder text render differently, as expected, on iOS 12.0 on branch 3.3.0 as of this post. Please reopen with a reproduction if there are additional environmental steps necessary to reproduce. Thanks!

**Comment by kingces95** [comment]
Oops. Used `Entry` instead of `Editor`.
