### ISSUE TITLE
Grid RowDefinition ActualHeight is hidden, SizeChanged misleading

### ISSUE THREAD

**Issue by christoroth** [xamarin/Xamarin.Forms#4011]
### Description
I have a situation where I need to know the height of a grid row at runtime.  
RowDefinition has an internal property actualHeight that I can see in the "non-public members" list in the VS debugger but the RowDefinition class is sealed and that property is internal so there is no way to add an extension method to access it.

Have checked the above in UWP and iOS and the values look good so I'd really like to use them!

While looking at the GitHub source, I saw that the SizeChanged event is misleading.  It is fired if the Height property changes but not if the actual size (e.g. set to 1,Auto, the size of the row would change if the device is rotated, window changes size etc).  

### Steps to Reproduce

1. N/A 

### Expected Behavior
SizeChanged event on RowDefinition to be triggered when the actual size is changed (likewise with ColumnDefinition). SizeChanged on other objects indicates a physical size changed.

HeightPropertyChanged event for the actual property change detection 

Make Actual Height a visible, bindable property like it is in WPF.

### Basic Information

- Xamarin Forms: 3.2.0.829982
- IDE: VS 2017 Pro
- Platform Target Frameworks: 
  - iOS:  12.0
  - Android: 8.0
  - UWP:  17134

**Comment by Tommigun1980** [comment]
Please make it public.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
