### ISSUE TITLE
Bindable Span height Issue

### ISSUE THREAD

**Issue by OmerHmead** [xamarin/Xamarin.Forms#4026]
### Description
When trying update span text using binding the text will cut off , if the new label text needs more rows to display
### Steps to Reproduce

1. Open the sample project
2. Click on the button (to make the bindable span text longer)
3. Note that the text will cut off

### Expected Behavior
The label height should be update and the text shouldn't cut off
### Actual Behavior
The bindable span text cut off
### Basic Information

- IDE: Microsoft visual studio 2017 15.8.5
- Platform Target Frameworks: 
  - iOS:  12 simulator
  - Android: 8 device and simulator
### Screenshots

Android
![android issue](https://user-images.githubusercontent.com/41253169/46582683-7f33d600-ca53-11e8-8da5-d25540dc15f1.gif)
IOS
![bindable-ios-span-issue](https://user-images.githubusercontent.com/41253169/46582684-7f33d600-ca53-11e8-8649-e4e56e1e5e41.gif)

### Reproduction Link

Sample Code
[Bindable-Span-Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/2453962/Bindable-Span-Issue.zip)

**Comment by paymicro** [comment]
Also reproduced in UWP.
