### ISSUE TITLE
Entry custom font binding isPassword getting reset to default font

### ISSUE THREAD

**Issue by sivashankararumugam** [xamarin/Xamarin.Forms#4029]
### Description
Android only,
In over application we are using custom font. For password, i'm showing option hide/show for the password field this was implemented by binding the bool property to ispassword. when I tap on the show/ hide custom font is reset to default font. 
### Steps to Reproduce

1. Add Entry control and set IsPassword as bindable and add label as show/hide text
2. Handle the IsPassword property in hide/show label tapped.
3. Add custom font to the application and apply custom font for the entry through the styles

### Actual Behavior
On page load , custom font is applied, if the property changed in IsPassword then the custom font is reset to default font. 
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio 2017
- Platform Target Frameworks: 
  - Android: 8.0,8.1,7.0 
- Android Support Library Version: 
- Nuget Packages: Xamarin forms 3.2.0839982
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
@StephaneDelcroix @sivashankararumugam 
Duplicated https://github.com/xamarin/Xamarin.Forms/issues/4018

**Comment by 444194401** [comment]
yes

**Comment by sivashankararumugam** [comment]
Yes
