### ISSUE TITLE
Native renderer is not found from my custom control for Xamarin Forms iOS

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#4031]
## Description

I have created a custom control in Xamarin forms and its native control set as custom control which inherits from UITextField, when I tried to get native renderer form my custom control using **Platform.CreateRenderer(myCustomControl)**, default renderer is obtained and native renderer is not found for Xamarin Forms iOS. Kindly refer the screenshots below,

**Image_1**
![Image_1](https://i.postimg.cc/63pWBv2V/Screen_Shot_2018-10-08_at_10.44.47_AM.png)

**Image_2**
![Image_2](https://i.postimg.cc/HxmgL7rv/Screen_Shot_2018-10-08_at_11.28.52_AM.png)

For Xamarin Forms Android, native renderer is obtained properly from my custom control using sample code , Kindly refer the screenshot below,

**Image_3**
![Image_3](https://i.postimg.cc/J7PG9RgC/Screen_Shot_2018-10-08_at_11.36.30_AM.png)

**Note:** I have passed forms and native view in ViewRenderer for Xamarin Forms iOS renderer. kindly refer the code snippet below,

Code snippet:
public class MyCustomControl : ViewRenderer<View, UITextField>
{
}

Could you please share in which scenario default renderer will be obtained? 
Also, could you please suggest how to get native renderer in this scenario and from default renderer? 

Regards,
Ganeshamoorthy C

**Comment by hartez** [comment]
@Ganeshamoorthy10 What does your `ExportRenderer` attribute look like?

**Comment by samhouts** [comment]
@Ganeshamoorthy10 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
