### ISSUE TITLE
iOS ipa failes validation in Application Loader wth ERROR ITMS-90023 

### ISSUE THREAD

**Issue by Hovejr** [xamarin/Xamarin.Forms#4034]
### Description
When we archive our app and sign it, the payload contains all icons that are needed, but when we try to upload the ipa with Application loader it fails with ERROR ITMS-90023 on images 76x76, 167x167 and 152x152, but the icons exist with correct naming: Icon-76.png, Icon-76@2x.png and Icon-83.5@2x.png. The icons have not changed for the last 12 months, so the error appeared out of nothing. Also, after random number of clean and rebuild it sometimes suddenly goes trough to AppStoreConnect. We have tried using XCode for signing and uploading the archive, but this fails as well. The path to the xcassets given in Info.plist is correct as well as paths in the .csproj-file to the images and Contents.json

### Expected Behavior
The app uploads since payload contains all icons

### Actual Behavior
The upload fails because of missing images that exists in the payload and are referenced

### Basic Information
- Version with issue: Xamarin.Forms 3.1 and 2.5
- Last known good version: Xamarin.Forms 3.1 and 2.5
- IDE: Visual Studio 2017 for Mac version 7.6 and Visual Studio 2017 for Mac version 7.7 build 1470
- Platform Target Frameworks: 
  - iOS:  12.0
- Nuget Packages:
- Affected Devices: iPad

### Screenshots
Error message from Application Loader:
<img width="635" alt="screen shot 2018-10-08 at 12 19 25" src="https://user-images.githubusercontent.com/6113869/46603917-d9d13e80-caf4-11e8-8b69-76e595938b92.png">

From package content of archive:
![screen shot 2018-10-08 at 12 59 08](https://user-images.githubusercontent.com/6113869/46605504-09cf1080-cafa-11e8-8a6a-ad8da58f4f84.png)

**Comment by samhouts** [comment]
Does anything in this forum post help you? Thanks! https://forums.xamarin.com/discussion/71397/missing-required-file-icon-error-itms-90022-itms-90023

**Comment by Hovejr** [comment]
Tried that, and is the app is then uploaded but rejected because we are not using xcasset for icons.
Ended up scraping the old iOS.csproj, creating a new, adding all the old files and got it trough, so found a wau around it, but not the cause.

**Comment by samhouts** [comment]
Very odd. If you happen to encounter this issue again, please let us know. Thank you!

**Comment by jaspervanmegroot** [comment]
Having the same issue here. Really annoying. Can't upload to the Appstore now..

**Comment by AmauryBJ** [comment]
Solution Found ! It's not a name, or a folder, or a Content.Json problem. Stop searching that side. it's just a visual studio/xcode bug... 
Before archiving your app, select : "Generic Device" in the destination instead of "iPhone" for example.
Archive your app like that !
And it's gonna be good !

**Comment by jaspervanmegroot** [comment]
@AmauryBJ How do you this on visual studio on windows? I can't find the option Generic Device.

**Comment by AmauryBJ** [comment]
So, first send the app on your iPhone in debug mode, and then select "Generic Device" here to be able to create a good archive
![genericdevice](https://user-images.githubusercontent.com/7004659/47477270-a98fdc80-d824-11e8-840e-9aa4a5d3a56c.jpg)

**Comment by AmauryBJ** [comment]
To bo able to see generic device you need to unplug your iphone !

**Comment by jaspervanmegroot** [comment]
On Windows is this different:
![knipsel](https://user-images.githubusercontent.com/19607572/47481604-5a51a800-d834-11e8-8fb0-5b6fb2a61b16.PNG)

Still got it not working..

**Comment by AmauryBJ** [comment]
Two questions : 
- Did you check "generic device" instead of iphone ?
- You are using your mac remotly to compile ? Did you try directly on your mac ?

**Comment by jaspervanmegroot** [comment]
1. There is no option for Generic Device
2. And yes I use a mac remotely to compile. I will try it ;)

**Comment by jaspervanmegroot** [comment]
Still no succes..

**Comment by jaspervanmegroot** [comment]
Got it working with setting Visual Studio on Appstore (only Appstore, no iPhone selected) and than Archive for publishing!

**Comment by atokuswanto** [comment]
Thanks for your kind tip @AmauryBJ 
FYI, I add an interesting link.

https://developercommunity.visualstudio.com/t/xamarin-ios-generated-ipa-file-does-not-include-al/1640607

https://developercommunity.visualstudio.com/t/xamarin-ios-generated-ipa-file-does-not-include-al/1640607#TPIN-N10055126
