### ISSUE TITLE
Error creating Xamarin.Forms application.

### ISSUE THREAD

**Issue by guisoli** [xamarin/Xamarin.Forms#4044]
### Description

Hello, I'm having a issue with Xamarin... btw I'm a novice

### Steps to Reproduce

1. Create a Xamarin.Forms project
2. Try to compile and run it on an Android device 

### Expected Behavior

Since no changes were made, the expected behavior was to run normally

### Actual Behavior

It presents the following Exception

Erro		ADB0000: Comprimento não pode ser menor que zero. // length cannot be less than 0
Nome do parâmetro: length
   em System.String.Substring(Int32 startIndex, Int32 length)
   em Mono.AndroidTools.AndroidInstalledPackage..ctor(String value)
   em Mono.AndroidTools.Internal.AdbOutputParsing.ParseLastResortPackageList(String output)
   em Mono.AndroidTools.AndroidDevice.<>c__DisplayClass68_0.<GetPackagesLastResort>b__0(Task`1 t)
   em System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()		 	0	

(I'm Brazillian <3)

### Basic Information

- Version with issue: Xamarin 4.11.0.776
- IDE: Visual Studio 2017 (15.8.6)
- Platform Target Frameworks: 
  - Android:  
- Android Support Library Version: android-sdk 23 
- Nuget Packages:
- Affected Devices: Android

**Comment by samhouts** [comment]
What device are you using? Does anything on this forum post seem helpful to you? Thanks! https://forums.xamarin.com/discussion/93343/cant-deploy-on-device-android-marshmallow

**Comment by samhouts** [comment]
@guisoli Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jm2ads** [comment]
Y ando?
