### ISSUE TITLE
Reference platform specific properties from XAML

### ISSUE THREAD

**Issue by JanabiSoft** [xamarin/Xamarin.Forms#4048]
##Summary
Reference platform specific properties directly from XAML syntax

e.g.

        <ContentPage 
                xmlns:android="clr-namespace:Android.Widget;"          
                xmlns:win="clr-namespace:Windows.UI.Xaml.Controls;">

               <StackLayout>
                      <Entry Text="Hello World" win:BorderThickness="2" android:backgroundColor="red" 
                                android:textAllCaps="true" />
                </StackLayout>
        </ContetnPage>

##Intended Use Case
for faster and straightforward development of Xamarin Forms based apps.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
