### ISSUE TITLE
Label.FormattedText does not dyanmically change size

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#4054]
### Description

Text set via `Label.FormattedText` does not change size when the system text size changes.

### Steps to Reproduce

1. Create a form with a SlackLayout containing two labels. In the first label, set `Text` to "Hello". In the second label, set `FormattedText` to a `FormattedString` with a single `Span`  with text "World".
2. Create a dynamic binding for the `Style` of each label to "ListItemCaptionStyle".
3. Run the app.
4. In the platform's control panel, change the size to the smallest (e.g. on iOS, Settings > Display & Brightness > Text Size).
5. Compare the labels' text sizes.
6. In the platform's control panel, change the size to the largest.
7. Compare the labels' text sizes.

### Expected Behavior
"Hello" and "World" are both dynamically change small or both large, depending on the system setting.

### Actual Behavior
The label with the `Text` property worked. The label with `FormattedText` did not.

### Basic Information
Tested on iOS. I haven't tested on other platforms.

- Version with issue: Xamarin.Forms 3.2.0.871581
- Platform Target Frameworks:
  - iOS:  10.0

**Comment by GalaxiaGuy** [comment]
I suspect this is related to #3901 . `Font` properties are not always propagated from `Label` to `Span` correctly.

**Comment by breyed** [comment]
Perhaps, though as in the repro above, the problem occurs even if no properties on the `Span` are set except `Text`.

**Comment by jfversluis** [comment]
I've looked into this issue in regard to another problem we had here and I see that this seems fixed. At least, following the steps in the first comment I cannot reproduce this behavior any longer with v4.2. My reproduction project is attached here: [Repro4054.zip](https://github.com/xamarin/Xamarin.Forms/files/3541255/Repro4054.zip)

If you believe this is in error, please reopen the issue.
