### ISSUE TITLE
Native Windows view HyperlinkButton throw exception

### ISSUE THREAD

**Issue by JanabiSoft** [xamarin/Xamarin.Forms#4057]
### Description
<win:HyperlinkButton NavigateUri="http://www.bing.com" />

### Error
Cannot assign property "NavigateUri": Property does not exist, or is not assignable, or mismatching type between value and property

###
I understand that properties accepting other than string values need to be referenced by {x:Static }
but how I use a uri, I tried {x:Static new Uri('http://www.bing.com')}, also I cannot use code behind because native views does not support x:Name.
so what is the solution?

- Version with issue:
- Last known good version: XF 3.2
- IDE: VS 15.8
- Platform Target Frameworks: 
  
  - UWP:

**Comment by hartez** [comment]
@JanabiSoft You will need to construct the URI using the style detailed at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml#passing-arguments-to-native-views

Something like the following should work:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/				
			 x:Class="Xamarin.Forms.Controls.Issues.NativeHyperLink" 
			 xmlns:win="clr-namespace:Windows.UI.Xaml.Controls;assembly=Windows, Version=255.255.255.255,
				Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime;targetPlatform=Windows" 
			 xmlns:sys="clr-namespace:System;assembly=System">
	<ContentPage.Content>
		<StackLayout Margin="20">
			<win:HyperlinkButton Content="Hello World">
				<win:HyperlinkButton.NavigateUri>
					<sys:Uri>
						<x:Arguments>
							<x:String>https://www.bing.com</x:String>
						</x:Arguments>
					</sys:Uri>
				</win:HyperlinkButton.NavigateUri>
			</win:HyperlinkButton>
		</StackLayout>
	</ContentPage.Content>
</ContentPage>
```

Note that you have to declare the `System` namespace at the top.

**Comment by JanabiSoft** [comment]
@hartez Thanks, keep the good work
