### ISSUE TITLE
Tablayout is null when using Bottom Tabbar in Android

### ISSUE THREAD

**Issue by quantumarun** [xamarin/Xamarin.Forms#4058]
### Description
I am using the new Xamarin.Forms feature to set the Tabbar at Bottom for Android using below properties

 xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
    android:TabbedPage.ToolbarPlacement="Bottom"

I need to hide the tabbar when navigated to other pages. I had written a custom renderer inherited from TabbedPageRenderer. On OnElementChanged when i try to get the Tablayout its always null.
            this.TabsLayout = (TabLayout)this.GetChildAt(1);
and this i am not able to set the visibility to gone in case when navigated.

When i remove the code for ToolPlacement then it works fine and TabLayout is not null.

### Steps to Reproduce

1. In Android project, create a tabbed Page application and set ToolPlacement as Bottom
2. Create a Custom Renderer on TabbedPageRenderer and using OnElementChanged extract the TabLayout.
3. TabLayout is null.

### Expected Behavior

TabLayout should not be null

### Actual Behavior

Tablayout is null.

### Basic Information
Xamarin.Forms: 3.2.0.871581
Xamarin.Android.Support.v4: 27.0.2.1
Xamarin.Android.Support.v4: 27.0.2.1
Xamarin.android.support.v7.appCompat: 27.0.2.1

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by GalaxiaGuy** [comment]
When using bottom navigation, a `TabLayout` is not used, a `BottomNavigationView` is used instead.

You might have to check what the renderer is doing (https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs) but the same kind of thing is probably achievable.

Have you checked what type the return value of `this.GetChildAt(1);` is? If that isn't the `BottomNavigationView`, then it will still be somewhere in the view hierarchy.

**Comment by quantumarun** [comment]
Well this.GetChildAt(1) is null and this.GetChildAt(0) is a Relative Layout. this has a non-public member _bottomNavigationView.

**Comment by quantumarun** [comment]
Any Fix for this?

**Comment by PureWeen** [comment]
That Relative Layout contains the _bottomNavigationView

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/TabbedPageRenderer.cs#L246

**Comment by PureWeen** [comment]
*That* being what?  Just set the visibility on the RelativeLayout to false like you were with tablayout or access the Children of the RelativeLayout to get the _bottomNavigationView
