### ISSUE TITLE
Android crashes (plural) before app load completes

### ISSUE THREAD

**Issue by pfaucon** [xamarin/Xamarin.Forms#4060]
### Description
We have an application that seems to crash occasionally before it finishes loading. Crashes can be seen randomly, crashes usually appear in Google play, but not in AppCenter.

### Steps to Reproduce

1.  ?? seems sporadic

### Expected Behavior
App should always complete loading

### Actual Behavior
App occasionally crashes before completing loading

### Basic Information

- Version with issue: 3.2.0.871581
- Last known good version: unfortunately unknown
- IDE: Visual Studio for mac (also present in CI builds from Bitrise)
- Platform Target Frameworks: 
  - iOS:  (N/A, we have not observed or received reports of the exception here) 11.3
  - Android: Minimum = 5.0, Target = 8.1 (27)
- Android Support Library Version: 27.0.2.1
- Nuget Packages: [packages.config](https://gist.github.com/pfaucon/173baf1929012bb437929288126f28d2)
- Affected Devices:
At least Samsung S8/S8+

### Crash Logs

I managed to catch a few of the crashes in the crash logs, but unfortunately it is not particularly helpful: 
https://gist.github.com/pfaucon/4ec0f46bbe91f47416d835633feceb0f
https://gist.github.com/pfaucon/916172c22549c28cd95ff1bda70675e1

Here are some of the crash reports collected by the Android developer logs 
https://gist.github.com/pfaucon/29e2338789ada549a5258158126b53a2

### Reproduction Link

Not sure how to reproduce, seems sporadic.  The occurrences today I was using other apps (hadn't used our app since at least the day before).  I tapped a notification from it that had arrived the day before, and a crash occurred.  Tried launching from launcher, crashed again.  Tried launching again, everything was fine.  

It seems probable that it is a code issue on my side, perhaps in the configuration somehow, but the crash logs somehow avoid our exception tracker (registering it is the first action after forms init), and the errors are not very useful for tracking down the error source, any suggestions would be appreciated.

**Comment by hartez** [comment]
What (if anything) does your application do before Forms.Init()? Do you have any code running during OnResume, OnPause, etc.?

**Comment by samhouts** [comment]
@pfaucon Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
