### ISSUE TITLE
ArgumentOutOfRangeException in Android NavigationPageRenderer

### ISSUE THREAD

**Issue by radioactiveman** [xamarin/Xamarin.Forms#4069]
### Description
Our crash reports contain an unhandled `ArgumentOutOfRangeException` in the Android `NavigationPageRenderer`. Unfortunately I could never reproduce the crash myself.

[Stacktrace.txt](https://github.com/xamarin/Xamarin.Forms/files/2472795/Stacktrace.txt)

I guess this exception occurs here in [line 621](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L621) because there is no check if the collection is empty. My suggestion is to use `FirstOrDefault()` with a null check.

### Steps to Reproduce
Unknown

### Expected Behavior
No unhandled exception causing a crash.

### Actual Behavior
App crashes.

### Basic Information

- Version with issue: 3.2.0.839982
- Last known good version: Unknown
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 7.0
- Android Support Library Version: 27.0.2.1
- Affected Devices: Multiple vendors and devices, Android 6 - 8

**Comment by samhouts** [comment]
Are you able to provide any more context into the structure of your app? Are you using a MasterDetailPage? Modal pages? Do you change the MainPage of your app at any time? Thanks!

**Comment by radioactiveman** [comment]
The app uses MvvmCross with its NavigationService to do all the navigation. We use neither master detail pages nor modal pages.

**Comment by radioactiveman** [comment]
@hartez Any update on this issue? Your changes in #4132 are only relevant for Android, how can they make iOS tests fail? Are they not false positives?

**Comment by hartez** [comment]
The changes aren't making the iOS tests fail; the _new_ test doesn't pass on iOS. And that's because it shouldn't - the whole situation is invalid. A NavigationPage should never be in a situation where it's visible and does not have a root page. 

So the actual bug isn't the lack of a null check; something else is going wrong to cause this situation.

Which version of MvvmCross does your application use? Are you using the `MvxPagePresentationAttribute` `WrapInNavigationPage` or `NoHistory` options?

**Comment by radioactiveman** [comment]
Thanks for the fast answer. The relevant version of the app uses MvvmCross 5.7.0.
We released a new version recently and updated MvvmCross to 6.2.2.
So far we have no crash reports about this anymore. I will keep an eye on it and reopen this issue if required.
