### ISSUE TITLE
View doesn't measure the exact size when used ControlTemplate

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#4070]
Hi Team,

### Description
We have noticed that when used ControlTemplate for a View, the exact View size measured from the renderer is not obtained correctly based on its contents. We have attached the sample which replicates the issue for your reference. You can check the behavior in our sample by commenting the method which initializes the ControlTemplate and verify the size obtained. This issue is seen in all the platforms. Can you please look into it and provide suitable solution for this issue?

### Steps to Reproduce

1. Run the attached sample.
2. Click the 'Add children' button.

### Expected Behavior
The size of the item should be obtained properly when used ControlTemplate.

### Actual Behavior
The size is obtained as '8' which is irrelevant to the element contents.

### Reproduction Link
[CustomView.zip](https://github.com/xamarin/Xamarin.Forms/files/2472887/CustomView.zip)

**Comment by hartez** [comment]
You don't appear to be giving the native layout engine an opportunity to measure or layout the contents of your control. 

Change your Button_Clicked method to see what I mean:
```
        private async void Button_Clicked(object sender, EventArgs e)
        {
            contentView.BackgroundColor = Color.AntiqueWhite;
            var grid = new Grid();
            for (int i=0;i<3;i++)
            {
                var label = new Label() {FontSize=40 };
                label.Text = i.ToString();
                grid.Children.Add(label, 0, i);
            }
            contentView.Content = grid;
            parent.Children.Add(contentView, 0, 1);
            Size viewSize = new Size((this.Width), double.PositiveInfinity);
            //You can check the exact size of the contents here.
            var measuredSize = DependencyService.Get<IMeasureSize>().CalculateSize(parent, contentView, viewSize);
            Debug.WriteLine($">>>>> MainPage Button_Clicked: {measuredSize}"); // Height will be 8

            await Task.Delay(100); // Let the layout engine do its work

            // Measure again 
            measuredSize = DependencyService.Get<IMeasureSize>().CalculateSize(parent, contentView, viewSize);
            Debug.WriteLine($">>>>> MainPage Button_Clicked: {measuredSize}"); // Height will be final height
        }
```
