### ISSUE TITLE
[Enhancement] Create InputTransparent for Span

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4073]
### Rationale

I ran into a case where I was setting `InputTransparent` to true on a label, but a few spans in it needed to be clickable with a tap gesture recognizer. Setting `InputTransparent` to true on a label turns off the gesture recognizers for the spans. If a span had this property instead, we could fine tune input transparency so that specific spans may be made clickable while other parts of the label can pass the gesture down to its parent.

### Implementation 

`public static readonly BindableProperty InputTransparentProperty = BindableProperty.Create("InputTransparent", typeof(bool?), typeof(Span), default(bool?));`

Default for this property should be a nullable bool (or a default enum) so that the state of input transparency for the span is indeterminate and strictly follows the behavior of the label. Any true/false value set on the span overwrites the behavior of the label for the tap coordinates of the span.

### Backward Compatibility

At this point, I'm not sure if there are any backward compatibility issues.

Edit: I'm not sure if we can bind to nullable properties in XAML without an explicit converter, and I don't have time to verify that right now. As I said, maybe an enum or something else could be used instead.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
