### ISSUE TITLE
error CS0103: The name 'InitializeComponent' does not exist in the current context

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#4074]
[NOTE: originally reported here 
https://github.com/xamarin/Xamarin.Forms/issues/2863#issuecomment-429385270]
### Description

I created a new project (Xamarin.Forms, blank, shared project). I attach this project as [App6](https://github.com/xamarin/Xamarin.Forms/files/2473844/App6.zip). Than I opened VS2017 (updated this morning to newest version 15.8.7) and try to build the project for UWP. Get the same "CS0103 The name 'InitializeComponent' does not exist in the current context" error again. The diagnostic build output is [here](https://github.com/xamarin/Xamarin.Forms/files/2473841/ce97bab0e787485aa8fa5b8576b4a322.vssolutionbuild.zip). The system info looks like

> Microsoft
> 
> Visual Studio Community 2017 
> Version 15.8.7
> VisualStudio.15.Release/15.8.7+28010.2046
> Microsoft .NET Framework
> Version 4.7.03056
> 
> Installed Version: Community
> 
> Visual C++ 2017   00369-60000-00001-AA779
> Microsoft Visual C++ 2017
> 
> Application Insights Tools for Visual Studio Package   8.13.10627.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.8.05085.0
> ASP.NET and Web Tools 2017
> 
> C# Tools   2.9.0-beta8-63208-01
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
> Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> GitHub.VisualStudio   2.5.8.5165
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> MLGen Package Extension   1.0
> MLGen Package Visual Studio Extension Detailed Info
> 
> Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
> Support for debugging Mono processes with Visual Studio.
> 
> NuGet Package Manager   4.6.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> ProjectServicesPackage Extension   1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> ResourcePackage Extension   1.0
> ResourcePackage Visual Studio Extension Detailed Info
> 
> TypeScript Tools   15.8.20822.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   2.9.0-beta8-63208-01
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
> Microsoft Visual F# Tools 10.2 for F# 4.5
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the > Microsoft Windows 10 Software Development Kit.
> 
> VisualStudio.Mac   1.0
> Mac Extension for Visual Studio
> 
> Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin Designer   4.15.9 (d000f568b)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates   1.1.116 (9619170)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
> Xamarin.Android Reference Assemblies and MSBuild support.
> 
> Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

If you like to look onto my computer, than this is possible too.

### Steps to Reproduce

Run the attached project

### Expected Behavior

build succeed

### Actual Behavior

build fails

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
looking at the log, XamlGTask isn't executed

**Comment by charlenni** [comment]
@StephaneDelcroix Yes, this could be the reason. I compiled the project for iOS and get the same error. And when I check the folder for the xaml.g.cs file, I don't find one. I checked this with @mgoertz-msft in June.

I uninstallaed VS2017 and reinstalled it. But this didn't helped me. Using the same project on Mac is no problem. So I assume, that it is a problem with my PC.

**Comment by charlenni** [comment]
So, now I tested some more things. Deinstalled VS2017 and installed it again. Than tried my open source app with Android. And what should I say: it works. Than started the Mac and tried with iOS. It doesn't work :(.

So I could say: it works for Android and not for iOS and UWP.

**Comment by StephaneDelcroix** [comment]
iOS (on your App6) works fine. are you reusing the same checkout of the project between builds ? does cleaning all of the `obj/` and `bin/` folders help ? Is your VisualStudio for Mac up to date ?

On your UWP log, I don't see any single indication that the PackageReference loaded the `Xamarin.Forms.targets`. Is your nuget version up-to-date and fully supports PackageReferences ?

At this point, and given the information I have (your project: works for me) and the build log, it seems very unlikely to be a Xamarin.Forms issue, but more a build tool issue or config problem

**Comment by charlenni** [comment]
First of all, thank you for your help.

iOS and UWP both have the same problem. The iOS version could only build on my Mac, not my Windows machine. I deleted all obj and bin folders.

The Build output for iOS looks like

````
1>------ Build started: Project: App6.iOS, Configuration: Debug iPhoneSimulator ------
1>  Connecting to Mac server 192.168.55.163...
1>  Connecting to Mac server 192.168.55.163...
1>C:\Users\weltz\source\repos\App6\App6\App6\App.xaml.cs(12,13,12,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\weltz\source\repos\App6\App6\App6\MainPage.xaml.cs(14,13,14,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
````

The Build output for UWP looks like

````
1>------ Build started: Project: App6.UWP, Configuration: Debug x86 ------
1>C:\Users\weltz\source\repos\App6\App6\App6\MainPage.xaml.cs(14,13,14,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
1>C:\Users\weltz\source\repos\App6\App6\App6\App.xaml.cs(12,13,12,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
````

Do the same with the Android version, than it works. So it is a iOS and UWP problem. And yes, I assume, that it is a problem of my Windows machine.

I didn't installed an extra NuGet version. I use the NuGet function from VS2017 (seems 4.6.0). Not sure, if VS2017 use the normal NuGet.exe. VS2017 is up to date. Btw. VS for Mac is up to date too. I updated both yesterday.

For me, it is a Xamarin.Forms problem. If I create normal UWP projects, they compile fine. It could be a build tool issue. But what could I doing wrong? Uninstalled and installed VS2017 two times now. Created new blank projects, not existing ones. Any suggestion where I could look or what I could change?

**Comment by kzu** [comment]
@charlenni if you chose NETStandard in the "Code Sharing Strategy", this problem disappears. That is why we changed it to be the new default in 15.8, and it will be the only option in dev16.

Would be extremely helpful to find out the root cause why it fails, nevertheless.

**Comment by StephaneDelcroix** [comment]
closing as this is addressed in the templates. feel free to attach a repro project and reopen the issue

**Comment by charlenni** [comment]
@StephaneDelcroix Sorry for not closing this issue.

At the end, nothing of the above helped. What I did? I bought a new hard disk, installed Windows and VS 2017 new. Now it works 😁

Thank you all for your help.
