### ISSUE TITLE
Picker control's ItemsSource property does not support full TwoWay binding

### ISSUE THREAD

**Issue by grahampcharles** [xamarin/Xamarin.Forms#4077]
### Description
When using a `Picker` control with its `ItemsSource` bound to an `ObservableCollection`, the `Picker` only responds to additions and deletions in the collection, not to updates in the collection's members.

### Steps to Reproduce
1.   Create a `Picker` control bound to an `ObservableCollection`
2.   Mutate the displayed property (that is, the property denoted by the `Picker`'s `ItemDisplayBinding`) of one member of the collection

### Expected Behavior
The new value should appear in the `Picker`.

### Actual Behavior
No changes are shown in the `Picker`.

### Basic Information
- Version with issue: 3.1.0.697729
- Last known good version: none
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.1 - API 27
- Nuget Packages: Refactored.MvvmHelpers (although the problem presents without this package as well)

### More Information

As a [response on StackOverflow](https://stackoverflow.com/questions/52796368/picker-not-updating-when-itemssource-changed) indicated, the `Picker` [source code](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Picker.cs#L136) includes a call to `UnApply()` in `GetDisplayMember()`. This would seem to indicate that this behavior might be by design -- but if so, it's:
  * incomplete -- since `ObservableCollection.Add()` and `.Remove()` work as expected
  * undocumented -- the [docs page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/) for Picker does not indicate that `ItemsSource` is intended to only work `OneWay`.
  * unnecessary -- why make `Picker` the only obligate `OneWay` control?

### Screenshots

Before: https://github.com/grahampcharles/PickerUpdateSample/blob/master/PickerUpdateSample/PickerUpdateSample/Screenshots/Screenshot%20Before.png

After: https://github.com/grahampcharles/PickerUpdateSample/blob/master/PickerUpdateSample/PickerUpdateSample/Screenshots/Screenshot%20xAfter.png

### Reproduction Link

Here's a sample: https://github.com/grahampcharles/PickerUpdateSample

**Comment by hartez** [comment]
To clarify, what you are expecting is that if the `Picker` is using the `ItemDisplayBinding` property, when that property changes on the underlying item the update display value should be reflected in the Picker.

That's not currently supported, but it would be nice. I'm adding it to our enhancements list.

This issue title is misleading; this doesn't have anything to do with two-way binding, it's just that the Picker does not monitor individual item property changes.

**Comment by DamianSuess** [comment]
Looking forward to this being fixed, and waiting patiently. Is there any chance this will be on an upcoming sprint sometime soon?

**Comment by viktorszekeress** [comment]
What's the current status of this issue?
Or could you provide us with the workaround?

**Comment by DamianSuess** [comment]
Just a heads up, the referenced source code for this defect does reference ``ItemsSource`` as per the [MainPage.xaml](https://github.com/grahampcharles/PickerUpdateSample/blob/master/PickerUpdateSample/PickerUpdateSample/MainPage.xaml) file.

```xaml
<Picker x:Name="thePicker" ItemsSource="{Binding MyItems}" ItemDisplayBinding="{Binding MyItemName}"></Picker>
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
