### ISSUE TITLE
[Enhancement] New solutions should use the Android namespace instead of Droid

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4078]
When you create a new solution, the Android project is putting all native files under [AppName].Droid.*, but the project name is [AppName].Android. In order to match the behavior of iOS, the next release of VS XF templates should start using the Android name in namespaces. @pierceboggan, what do you think?

**Comment by GalaxiaGuy** [comment]
One disadvantage of this is if you write custom renderers or effects (or anything that requires native Android code) is that you will get name collisions a lot more which can lead to very confusing errors.

(This doesn't happen for iOS since `iOS` doesn't appear in any namespaces - `Android` does).

**Comment by SamuelDebruyn** [comment]
It's `.Droid` and not `.Android` because otherwise all of your code conflicts with the [Android namespace](https://developer.xamarin.com/api/namespace/Android/) from Android itself. You'd have to use the `global::` prefix all the time. I'd keep it `.Droid`.

**Comment by samhouts** [comment]
I think we won't do this, for the reasons @sdebruyn mentioned. Thanks for the suggestion!
