### ISSUE TITLE
[Enhancement] Please include image sizes on AppIcon window for iOS assets

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4081]
Visual Studio for Windows does not show image sizes required for AppIcon assets when we're adding app icons on iOS. Xamarin Studio for Mac had this functionality, so I'd like to see it implemented on Windows as well.

Mac

![asset02](https://user-images.githubusercontent.com/16855542/46927604-d0b40600-cffb-11e8-9274-743b4da69703.png)

Windows

![capture](https://user-images.githubusercontent.com/16855542/46927620-ee816b00-cffb-11e8-80b8-cd8f98731300.PNG)

Note that if you click a box above and look at the Properties window, then you could see the image size, but this information isn't easily discoverable as most people wouldn't think to look at this window right away. XCode also prints image sizes (in points) on the designer window.

**Comment by pauldipietro** [comment]
Feedback is always appreciated, but this sort of suggestion should be filed through Developer Community.
