### ISSUE TITLE
Accessibility on MasterDetailPage in Split Behavior

### ISSUE THREAD

**Issue by seanmodgov** [xamarin/Xamarin.Forms#4085]
### Description

I have been having a quick look at Accessibility because of the legislation that will be coming in soon for public sector bodies (WCAG 2.1 AA accessibility standards).

I focused on Android because I noticed the following line in a blog called "Making Your Xamarin.Forms Apps Accessible" by Paul DiPietro - on Android, some controls, incuding Button, unfortunately don’t behavior properly for reasons pertaining to Android itself.

I turned on TalkBack on the Android, and deployed the Xamarin.Forms application.

We have a MasterDetailPage in our project that we display in Split MasterBehavior.
I have noticed that the accessibility  from TalkBack works quite well on the MasterPage, but not at all on the DetailsPage.

This is definitely caused by the MasterDetailPage with a MasterBehavior of Split, because I made the attached repro that has the problem with MasterBehavior of Split, but not if I change the MasterBehavior to Popover.

### Steps to Reproduce

1.  Run the attached repro on an android device
2. Turn on TalkBack: Settings->Accessibility->TalkBack->On
3. Tap anything in the right-hand pane
4. Nothing is highlighted and nothing is spoken
5. Tap anything in the left-hand pane
5. The option is spoken to the user

### Expected Behavior
Items in the right-hand pane are spoken to the user as well as those in the left-hand pane

### Actual Behavior
Items in the right-hand pane are NOT spoken to the user, whereas those in the left-hand pane are

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0.697729
- IDE: Visual Studio Enterprise 2017 - 15.8.7
- Platform Target Frameworks: 
  - Android: Device: 6.0.1. Compile: 8.1. Min: 5.0. Target: 8.1.
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms
- SDK: NETStandard.Library 2.0.3
- Affected Devices: Nexus 7.

### Reproduction Link
[Repro1.zip](https://github.com/xamarin/Xamarin.Forms/files/2478907/Repro1.zip)

**Comment by PureWeen** [comment]
This is currently fixed on .NET MAUI

With Regards to Xamarin.Forms
If you haven't already, I also recommend updating to the latest version Xamarin.Forms or at least to Xamarin.Forms 5.0.0.2083, which has many accessibility improvements. These improvements include an experimental accessibility flag that addresses a lot of improvements in Android accessibility.

To leverage this flag on the latest versions of Xamarin Forms, the following code can be inserted in the App.xaml.cs file, following the InitializeComponent call and before the MainPage is set: Xamarin.Forms.Device.SetFlags(new List<string> { "Accessibility_Experimental"});
