### ISSUE TITLE
Add AsyncCommand and AsyncCommand<T> class

### ISSUE THREAD

**Issue by SergeBerwert** [xamarin/Xamarin.Forms#4087]
I would like to suggest to add AsyncCommand and AsyncComman<T> class to Xamarin Forms. In Gui Project, it’s often a problem to change between Sync and Async functions. It would be a lot easier if a command could bound to an async method. Frameworks like MvvmCross already have this capability.
Here an Example how I Imaging the code should look like:

```
    public class MenuViewModel
    {
        public ICommand MenuItemCommand { get; }

        public MenuViewModel()
        {
            MenuItemCommand = new AsyncCommand(OnMenuItemTabbed);
        }

        public async Task OnMenuItemTabbed(object state)
        {
            await Application.Current.NavigationProxy.PushAsync(RootPage);
        }
    }

```

**Comment by dansiegel** [comment]
While I can certainly appreciate what you're saying, I do not believe this belongs in Xamarin Forms. It is also important to remember that a command is for all practical purposes an Event Handler, which is in fact a time where it is considered ok to use `async void`. I would also have to say that you're really only going to use a command if you're architecting your application with an MVVM pattern, which also likely means you're using a 3rd party library. This suggestion thus belongs at that layer.

**Comment by SergeBerwert** [comment]
@dansiegel what you might be not aware of is that the synchronous implementation already is part of the Xamarin.Forms.Core: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Command.cs that’s why I think it belongs to there.
And because Xamarin Forms supports binding and everything it is not necessary to use another framework to have a MVVM application.
I consider myself not really like an expert in the async/await best practices, but I thought you have to be careful with the context. An Easy to use solution would help to avoid problems.

**Comment by GalaxiaGuy** [comment]
This was discussed here: #1857

**Comment by PureWeen** [comment]
To @GalaxiaGuy's point there's a decent discussion about this already https://github.com/xamarin/Xamarin.Forms/issues/1857

**Comment by dansiegel** [comment]
@SergeBerwert I'm well aware of the API including Command/Command<T>. These are pretty basic implementations of ICommand and really all that should be included in the Xamarin.Forms API. What you are proposing (which was already discussed) belongs outside of Xamarin.Forms.
