### ISSUE TITLE
[Android] Talkback reports incorrect number of list items

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#4090]
### Description

When tapping an item in a list for the first time, Talkback reports the number of items in the list. The number reported is consistently 2 greater than the correct number.

My best guess is that we have some phantom items in the list, possibly an invisible header and footer item.

### Steps to Reproduce

1. Enable Talkback 
2. Open the repro project from #4085 
3. Open the Detail page and tap "Browse" or "About"

### Expected Behavior

Talkback will report that the tapped item is in a list of 2 items. 

### Actual Behavior

Talkback will report that the tapped item is in a list of 4 items.

### Basic Information

- Version with issue: 3.1.0.697729 - 3.3.0.893527-pre3
- Last known good version: ???

### Reproduction Link

See #4085

**Comment by PureWeen** [comment]
Moved to https://github.com/dotnet/maui/issues/3995

**Comment by bertoferrero** [comment]
For those who are waiting for the fix but require a hot solution by now, I created this customrender by analysing the https://github.com/dotnet/maui/issues/3995 fix.
This code directly removes header and footer views, if you need any of them just adapt the code.

	class FixedAccesibilityListViewRenderer : ListViewRenderer
	{
		public FixedAccesibilityListViewRenderer(Context context) : base(context)
		{
		}
		protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
		{
			base.OnElementChanged(e);
			if (e.NewElement != null)
			{
				AListView nativeListView = Control;
				if (nativeListView == null)
				{
					var wrappedAdapter = (nativeListView.Adapter as Android.Widget.HeaderViewListAdapter).WrappedAdapter;
					if (nativeListView.FooterViewsCount > 0)
					{
						Android.Views.View footerView = (wrappedAdapter.GetType().GetProperty("FooterView").GetValue(wrappedAdapter, null) as Android.Views.View);
						nativeListView.RemoveFooterView(footerView);
					}
					if (nativeListView.HeaderViewsCount > 0)
					{
						Android.Views.View headerView = (wrappedAdapter.GetType().GetProperty("HeaderView").GetValue(wrappedAdapter, null) as Android.Views.View);
						nativeListView.RemoveHeaderView(headerView);
					}
				}
			}
		}
	}

**Comment by bertoferrero** [comment]
For those who are waiting for the fix but require a hot solution by now, I created this customrender by analysing the https://github.com/dotnet/maui/issues/3995 fix.
This code directly removes header and footer views, if you need any of them just adapt the code.

	class FixedAccesibilityListViewRenderer : ListViewRenderer
	{
		public FixedAccesibilityListViewRenderer(Context context) : base(context)
		{
		}
		protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
		{
			base.OnElementChanged(e);
			if (e.NewElement != null)
			{
				AListView nativeListView = Control;
				if (nativeListView != null)
				{
					var wrappedAdapter = (nativeListView.Adapter as Android.Widget.HeaderViewListAdapter).WrappedAdapter;
					if (nativeListView.FooterViewsCount > 0)
					{
						Android.Views.View footerView = (wrappedAdapter.GetType().GetProperty("FooterView").GetValue(wrappedAdapter, null) as Android.Views.View);
						nativeListView.RemoveFooterView(footerView);
					}
					if (nativeListView.HeaderViewsCount > 0)
					{
						Android.Views.View headerView = (wrappedAdapter.GetType().GetProperty("HeaderView").GetValue(wrappedAdapter, null) as Android.Views.View);
						nativeListView.RemoveHeaderView(headerView);
					}
				}
			}
		}
	}
