### ISSUE TITLE
Parsing OnPlatform<T> value (from Application Resources)

### ISSUE THREAD

**Issue by albilaga** [xamarin/Xamarin.Forms#4091]
### Description
Parsing OnPlatform value from Application Resources make little bit complicated
### Steps to Reproduce

Create Custom control which have property object. In my case I create custom control with name FontSize. Because FontSize can be string and also double I create it in object like this
  ```
public object FontSize
        {
            get { return (string)base.GetValue(FontSizeProperty); }
            set { base.SetValue(FontSizeProperty, value); }
        }

        public static BindableProperty FontSizeProperty = BindableProperty.Create(
            propertyName: nameof(FontSize),
            returnType: typeof(object),
                                                         declaringType: typeof(ExtErrorEntry),
            defaultValue: Xamarin.Forms.Entry.FontSizeProperty.DefaultValue.ToString(),
            defaultBindingMode: BindingMode.OneWay);
```

### Expected Behavior
When parsing value from string it is easier because Xamarin.Forms have FontSizeConverter. The problem is when using On Platform. It is should be easier to parsing On Platform like maybe `OnPlatform[Device.RuntimePlatform].Value` 
### Actual Behavior
To parsing value from OnPlatform I need to iterate OnPlatform.Platforms then in Platforms.Platform but the value is OnPlatform.Platforms. The code sample is like this
```
if (newValue is Xamarin.Forms.OnPlatform<double> onplatforms)
                {
                    bool isFound = false;
                    foreach (var onplatform in onplatforms.Platforms)
                    {
                        foreach (var platform in onplatform.Platform)
                        {
                            if (platform.Equals(Device.RuntimePlatform))
                            {
                                isFound = true;
                                control.Entry.FontSize = Convert.ToDouble(onplatform.Value);
                                break;
                            }

                        }
                        if (isFound)
                        {
                            break;
                        }
                    }
                }```

**Comment by StephaneDelcroix** [comment]
I do not understand what you're trying to do here. You shouldn't parse OnPlatform values yourself, but only get the returned value.

If you want to expose a property `FontSize`, do it this way:

```csharp

		public static readonly BindableProperty FontSizeProperty =
			BindableProperty.Create("FontSize", typeof(double), typeof(IFontElement), -1.0);

		[TypeConverter(typeof(FontSizeConverter))]
		public double FontSize
		{
			get { return (double)GetValue(FontSizeProperty); }
			set { SetValue(FontSizeProperty, value); }
		}
```

The `FontSizeConverter` will make sure everything is converted, and set, correctly, from both a string (NamedSize) or a value, using OnPlatform or not.

**Comment by albilaga** [comment]
Thanks @StephaneDelcroix  I don't know I can do that.
