### ISSUE TITLE
[iOS] System.UnauthorizedAccessException: Access to the path "PropertyStore.forms" is denied. Possible BackgroundFetch issue?

### ISSUE THREAD

**Issue by nbsoftware** [xamarin/Xamarin.Forms#4092]
### Description

When I leave my app started in the background and I use other apps in the meantime, and then resume my app by clicking on its icon or from its window in the multitasking view, everything seems ok most of the times, but say I leave it all night and resume it in the morning, the "home screen" reappears briefly (which I presume is an indication that the app has freshly restarted) then it instantly crashes with the following exception caught by AppCenter.

### Steps to Reproduce

1. play with an Xamarin Forms app
2. leave it in the background
3. play with as many other apps as possible to put some memory pressure on the initial app so that it restarts completely when resumed
4. resume initial app - home screen should appear then instantly crashes

### Expected Behavior

Should not crash

### Actual Behavior

`/Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO/FileStream.cs - line 274
System.UnauthorizedAccessException: Access to the path "PropertyStore.forms" is denied.`

```/Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO/FileStream.cs:274
/Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO/FileStream.cs:149
/Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFileStream.cs:127
/Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFileStream.cs:142
IsolatedStorageFile.OpenFile (System.String path, System.IO.FileMode mode) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/corlib/System.IO.IsolatedStorage/IsolatedStorageFile.cs:915
Deserializer+<>c.<DeserializePropertiesAsync>b__1_0 ()
Task`1[TResult].InnerInvoke ()
Task.Execute () /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2509
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult ()
Application+<GetPropertiesAsync>d__80.MoveNext () D:\a\1\s\Xamarin.Forms.Core\Application.cs:317
```

### Basic Information

I am using the latest Xamarin Forms v3.2.0.871581.
Not sure though (reading the stack trace) if its a Xamarin Forms issue or a Xamarin.iOS one...

```Visual Studio Community 2017 for Mac
Version 7.6.9 (build 22)
Installation UUID: be4088b1-069a-44b1-bca1-a8bc61ab68dc
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

NuGet
Version: 4.3.1.4445

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Xamarin.Android
Version: 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/fmeyer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		6.0   (API level 23)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Apple Developer Tools
Xcode 10.0 (14320.25)
Build 10A255

Xamarin.Mac
Version: 5.0.0.0 (Visual Studio Community)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

Xamarin.iOS
Version: 12.0.0.15 (Visual Studio Community)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 706090022
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376
Build date: 2018-10-05 16:38:51+00
Build branch: release-7.6
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7

Operating System
Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64```

**Comment by andreinitescu** [comment]
Does the device enters lock screen and you have a passcode set?

**Comment by nbsoftware** [comment]
Correct.

Before resuming the app surely the device had already enter lock screen (probably a number of times) and I need to use either FaceID or passcode to unlock it. Then launch the app (which should resume) and then the crash happens. Of course this does not happen systematically. But when it happens, I noticed that the app did go through a whole restart rather than normal resuming.

**Comment by nbsoftware** [comment]
Did that. Doesn't crash. Works as expected.

**Comment by andreinitescu** [comment]
You said you have app logs. Before it crashed, can you see any other crashes?  I'm thinking the app actually crashed earlier.
Another thing I'd look into is, make sure you don't have a leak which makes your app run twice. By "app" I mean having XamarinForms Application class instantiated when another instance already exists.

**Comment by nbsoftware** [comment]
Ah... this reminds me something I should have mentioned: my app has Background Fetch enabled which doesn't seem to pose any issue in itself as I can see it called regularly and only does a REST call over a /ping API for now...

**Comment by hartez** [comment]
@nbsoftware Can you give us some more details about how you use Application.Properties? Are you reading/storing properties during app startup, or during any other lifecycle events (pause, resume, stop, etc.)?

**Comment by nbsoftware** [comment]
Yes, I do use `Application.Current.Properties` in the `OnAppearing` of the main login screen (which happens to be the first one to display if not already authenticated).
And I do read & write.

**Comment by nbsoftware** [comment]
Ok so I think @andreinitescu was right in the first place, it is most likely a matter of the app hanging there (sometimes, not always) when launched in BackgroundFetch mode, so that the next normal launch when this condition happens produces the crash.

I've cleaned up a bit my main app cycle events and used `app.ApplicationState == UIApplicationState.Background` to determine if the app has been launched in BackgroundFetch to do much less startup initialization and things seem to be going smoother, at least for now.

One supplemental (but correlated) question is that, at least with my app, even with this cleaning, when debugging the Background Fetch within VS (Mac), it does all what it is expected to do but when the background job has finished, the debugger seems to be still attached to the process (and the process still there). Is that an indication that something is still wrong or is it an issue within VS?
