### ISSUE TITLE
Binding a Collection through ViewModel property to the Bindabe property of CustomView in XAML gives null value in BindablePropertyChanged().

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#4095]
### Description

Hi Team,

We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin.

We would like to bring to your notice a bug that we encountered recently when we set Binding a Collection through ViewModel property to the Bindabe property of CustomView(derived from grid layout) in XAML gives null value in BindablePropertyChanged(),  BindingPropertyChanged() method gives null value when this method hits second time.  We have Implemented a Custom View and have set Binding a collection like following here. For further clarification and better explanation I have added the customView and binding codes alone.

Custom View:
 public class CustomView : Grid
    {
        public ObservableCollection<object> Column
        {
            get { return (ObservableCollection<object>)GetValue(ColumnProperty); }
            set { this.SetValue(ColumnProperty, value); }
        }

        public static readonly BindableProperty ColumnProperty = BindableProperty.Create("Column", typeof(ObservableCollection<object>), typeof(CustomView), null, BindingMode.TwoWay, propertyChanged: OnColumnPropertyChanged);
        public CustomView()
        {
            Column = new ObservableCollection<object>();
        }

        private static void OnColumnPropertyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            
        }
    }
XAML : Collection Property Binding Code:
 <local:CustomView x:Name="customsView" Column="{Binding MyCollection}"></local:CustomView>

Also you can run the attached sample to ViewModel collection property codes too.

In the above code example, OnColumnPropertyChanged() method while hits first time newValue set as count 0,( which is dummy value from Column Property Instance). While second time hits newValue given as null from InitializeComponent() which is un-Expected behaviour, We observed this as issue, while third time hits of this property newValue set as Count 1 (from bindable collection property). So
we want at second time hits itself of this method OnColumnPropertyChanged() newValue should get the Value from bindable collection property while set in XAML page. 

Also we would like to mention while creating Bindable Property Instead of default value as null , If we add collection directly (new ObservableCollection<object>()) like this  newValue was getting as null value can be avoided. We expected the same with actual default value as null from Bindable property.

### Steps to Reproduce

1.  Run the Attached sample
2. Hit the break point at OnColumnPropertyChanged() method, check the newValue and callstack while hits every time,
3.  At second time hit of this OnColumnPropertyChanged() method newValue given as null and CallStack is from InitializeComponent().

### Expected Behavior
At second time hit of this OnColumnPropertyChanged() method newValue should set value from given bindable property.
### Actual Behavior
 At second time hit of this OnColumnPropertyChanged() method newValue given as null.

### Basic Information

- Version with issue: 2.4.280
- Last known good version: 2.4.280
- IDE:
- Android Support Library Version: All version
- Nuget Packages:  2.4.280
- Affected Devices: All devices, will all xamarin platfom

### Reproduction Sample Link

http://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample899637657

**Comment by hartez** [comment]
In your repro project, you declare your `CustomView` in XAML in MainPage as the content of your `ContentPage`:

`<local:CustomView x:Name="customsView" Column="{Binding MyCollection}"></local:CustomView>`

And then in the MainPage constructor, you are doing this:

```
public MainPage()
{
    InitializeComponent();
    customView = new CustomView();
    this.Content = customView;
}
```

These two lines are the problem: 
```
customView = new CustomView();
this.Content = customView;
```

Before these lines run, you already have a `CustomView` which is already the Content of your `ContentPage`, and which is already data bound to your view model. The first line creates a whole new `CustomView` (which fires off `OnColumnPropertyChanged` with a `null` `newValue`, because it isn't bound to anything). The second line then sets the Content of the `ContentPage` to the new `CustomView`, which then changes its binding context to the view model and fires `OnColumnPropertyChanged` again. 

Delete those two lines and the values in `OnColumnPropertyChanged` should make more sense.
