### ISSUE TITLE
(Android) Crash at Dependency service call 

### ISSUE THREAD

**Issue by Rajeswari06** [xamarin/Xamarin.Forms#4097]
Checking with android devices. In offline, on kill and relaunch app was crashing and the error was below

"Index was outside the bounds of the array. at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00147] in <cd3db6fb7af04deba6ed8e11978795f3>:0 at System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) [0x00000] in <cd3db6fb7af04deba6ed8e11978795f3>:0 at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget)"

### Steps to Reproduce
1. Use dependency service in app
2. Go to offline
3. Use the app, kill and relaunch the app

### Expected Behavior
App should work properly

### Actual Behavior
Crash is happening ( 70 to 80% times)

- Version with issue: 3.0.0.561731
- Last known good version: 3.0.0.561731
- IDE:visual studio
- Platform Target Frameworks: 
 - Android: all versions above 5.0
- Nuget Packages: Xamarin Forms 3.0.0.561731
- Affected Devices: Android

**Comment by Rajeswari06** [comment]
[app-c4637a26-5526-4b23-9d0d-3a5e7360be18-id-47cfae10-1358-411e-8eeb-aff30179f9e9.txt](https://github.com/xamarin/Xamarin.Forms/files/2483189/app-c4637a26-5526-4b23-9d0d-3a5e7360be18-id-47cfae10-1358-411e-8eeb-aff30179f9e9.txt)

**Comment by AndreiMisiukevich** [comment]
```csharp
static readonly ConcurrentDictionary<Type, DependencyData> DependencyImplementations = new ConcurrentDictionary<Type, DependencyData>();
```
instead of

```csharp
static readonly Dictionary<Type, DependencyData> DependencyImplementations = new Dictionary<Type, DependencyData>();
```

Probably can solve this issue, because it looks like thread-safety issue

**Comment by hartez** [comment]
@Rajeswari06 At what part of the app lifecycle do you use your dependency service? How are you registering your service?

**Comment by Rajeswari06** [comment]
@hartez I was registering the dependency service call like below,
 [assembly: Dependency(typeof(SDK_Android))] in the droid folder.

In my app I am using app center to send the error logs. if the service call fails then I am sending that exception message to the app center and other places also I am using dependency service to call the native functionality. 

The crash was happening mostly in offline scenario.

**Comment by hartez** [comment]
Yeah, I think @AndreiMisiukevich is right about this one. Needs to be a ConcurrentDictionary.

**Comment by hartez** [comment]
... and it's going to be kind of a pain to make that change; there doesn't appear to be a ConcurrentDictionary for netstandard 1.0. 

It's an easy change to make for 2.0, though.

**Comment by AndreiMisiukevich** [comment]
@hartez let's work around of ConcurrentDictionary. Just use lock section for thread safety

**Comment by Rajeswari06** [comment]
@AndreiMisiukevich  thank you for your quick response.

Can you please let me know when this fix was available to us

**Comment by AndreiMisiukevich** [comment]
@Rajeswari06 hi, can you provide small sample for reproducing this crash?
And is it possible to reproduce it on android emulator?
thx

**Comment by AndreiMisiukevich** [comment]
@Rajeswari06 ?

**Comment by Rajeswari06** [comment]
we have not tried with android emulator. 
We are working on the sample, mostly crashing in offline

**Comment by Rajeswari06** [comment]
@AndreiMisiukevich  my issue is resolved by adding lock. calling that dependency service from multiple threads caused the issue, based on the above suggestions I have added the lock.

**Comment by AndreiMisiukevich** [comment]
@Rajeswari06 unfortunately i couldn't reproduce it :(
