### ISSUE TITLE
x:DataType issue when there is a null object in binding path.

### ISSUE THREAD

**Issue by ysmoradi** [xamarin/Xamarin.Forms#4102]
### Description

I receive a null reference exception in user code when I bind to something like "{Binding SomeObjectWhichIsNull.SomeProperty"} when SomeObjectWhichIsNull is null.

Note that I'm using default visual studio settings for debugging.

### Steps to Reproduce

See Reproduction Link.

### Expected Behavior

No exception.

### Actual Behavior

I receive an exception, even when I select to see exceptions in my own codes. There is no way to ignore it.

### Basic Information

- Version with issue:
- Last known good version: N/A
- IDE: Visual Studio 2017 15.8.5 Enterprise edition.
- Platform Target Frameworks: This happens in Xamarin Forms Core (3.3.0.893527-pre3)

### Screenshots

![image](https://user-images.githubusercontent.com/5352980/47040672-af861d80-d193-11e8-8e49-fd6aed891107.png)

### Reproduction Link

Clone https://github.com/ysmoradi/XDataTypeIssues and un comment [this line](https://github.com/ysmoradi/XDataTypeIssues/blob/master/XDataTypeIssues/XDataTypeIssues/MainPage.xaml#L17). Then run the app.

**Comment by ysmoradi** [comment]
I'm sure you're so busy with other tasks, but could you please let me know when this gets fixed? Thanks in advance.

**Comment by StephaneDelcroix** [comment]
I can not reproduce this issue on your project, or on an unit test on our master. Please reopen (or ask for this to be reopened) if it still happen to you on the next 3.5.0-pre version

**Comment by StephaneDelcroix** [comment]
The exception is thrown, and captured (TypedBinding.cs:200)

**Comment by ysmoradi** [comment]
As I mentioned, I'm using default visual studio debug configuration.

![image](https://user-images.githubusercontent.com/5352980/48909369-52604480-ee82-11e8-94a0-dc873e544cb4.png)

It's not expected to see a null reference exception regularly. I tried throwing/capturing the exception in some sample code, and visual studio is not interrupting me unless I ask vs to show all exceptions to me.

```csharp
    public static class Test
    {
        private static object obj;

        public static void Do()
        {
            try
            {
                var a = obj.ToString();
            }
            catch { }
        }
    }
```

![image](https://user-images.githubusercontent.com/5352980/48909266-12995d00-ee82-11e8-9227-cecd7c9a8873.png)

But no matter what debug configuration I use, I see that NRE from TypedBinding )-:
I have to ask vs not to show NRE, no matter what causes that exception.

I can send a video if you want.

**Comment by StephaneDelcroix** [comment]
there's no need to send a video. I can reproduce your issue
