### ISSUE TITLE
[Android] Searchbar breaks previewer

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4108]
### Description

Previewer is throwing an exception on this line

https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.Android/Renderers/SearchBarRenderer.cs#L64

![image](https://user-images.githubusercontent.com/5375137/47050705-9616ae80-d15e-11e8-82f2-e77079c421a0.png)

### Steps to Reproduce

1.  Add SearchBar to a Xamarin Forms Page
2.  Try to use the Previewer

### Expected Behavior
Previewer should render SearchBar when previewing with Android control

### Actual Behavior
Previewer crashes with exception

### Basic Information
- Version with issue: The code has been around for a number of years.  So it's hard to say how long it's been broken on the previewer side.

> VS bug [#707179](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/707179), VS bug [#723527](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/723527), VS bug [#939685](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/939685)

**Comment by Ackara** [comment]
Same thing happening for me.
