### ISSUE TITLE
[WPF] Button transparency does not work in WPF

### ISSUE THREAD

**Issue by jfquarto** [xamarin/Xamarin.Forms#4114]
### Description
 Setting the Button.BackgroundColor to Color.Transparent does not seem to work in WPF

### Steps to Reproduce
In the xaml code behind (of the shared project):
Button button = new Button() {BackgroundColor = Color.Transparent};

### Expected Behavior
Label (with text) behind the button should be shown through.
(Works in the same solution for Droid and UWP)

### Actual Behavior
Label not shown through. Backgroundcolor of the button seems to have the default color (gray) ?

### Basic Information

- Xamarin.Forms 3.4.0.920272-nightly
- Visual Studio 2017 Pro
- Microsoft .NET Framework 4.7.2 (for WPF)

**Comment by krdmllr** [comment]
![image](https://user-images.githubusercontent.com/11095003/66689525-9cfdd180-ec8b-11e9-927a-57458b33a884.png)
This seems to work in the current 4.3.0, you can see a button trough another button with Color.Transparent

```
<Grid HeightRequest="100">
    <Button Text="Test"></Button>
    <Button BackgroundColor="Transparent" Text="Click Here!" />
</Grid>
```

**Comment by jfversluis** [comment]
Confirmed what @krdmllr is saying, seems to work in current version.

Thank you for paying attention Konrad!
