### ISSUE TITLE
[WPF] ListView.ScrollTo does not work in WPF

### ISSUE THREAD

**Issue by jfquarto** [xamarin/Xamarin.Forms#4115]
### Description
 ListView,ScrollTo method does not seem to work in WPF

### Steps to Reproduce
In the xaml code behind (of the shared project):
view.ScrollTo(e.SelectedItem, ScrollToPosition.MakeVisible, false);

### Expected Behavior
View should scroll to the selected item and make that visible
(Works in the same solution for Droid and UWP)

### Actual Behavior
View does not scroll to the selected item neither makes it visible.

### Basic Information

- Xamarin.Forms 3.4.0.920272-nightly
- Visual Studio 2017 Pro
- Microsoft .NET Framework 4.7.2 (for WPF)

**Comment by sahithi89** [comment]
Is there any workaround for this issue, I am also having the same problem.

**Comment by jfquarto** [comment]
Not that I know of. Haven’t looked at it anymore because the Xamarin application I worked on is set on hold by my company.


Met vriendelijke groet,
​
Johan Fontijne
Software developer
Quarto B.V.
Westbaan 200
Moordrecht
2841 MC
Nederland
Tel: +31 182 700 500
Email: johan.fontijne@quarto.nl
Web: www.quarto.nl
De disclaimer van toepassing op email van Quarto Betaalsystemen vindt u op https://www.quarto.nl/disclaimer-quarto
Van: sahithi89 <notifications@github.com>
Verzonden: Thursday, 16 May 2019 07:14
Aan: xamarin/Xamarin.Forms <Xamarin.Forms@noreply.github.com>
CC: Johan Fontijne <johan.fontijne@quarto.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [xamarin/Xamarin.Forms] [WPF] ListView.ScrollTo does not work in WPF (#4115)


Is there any workaround for this issue, I am also having the same problem.

**Comment by jsuarezruiz** [comment]
The problem is that the [ListViewRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Renderers/ListViewRenderer.cs) in the Xamarin.Forms WPF backend not implement **ScrollToRequested**.
The fix require the implementation of the method where find the `ScrollViewer` using the `VisualTreeHelper` and then use the `ScrollToVerticalOffset` (and better with a smooth animation).
