### ISSUE TITLE
Forms 3.3: TextDecorations aren't unset by a DataTrigger

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#4121]
### Description

In Forms 3.3, `TextDecorations` aren't unset by a DataTrigger, unlike `FontAttributes`, which are.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the "Basic Switch Bindings" page.
3. Toggle the italic/bold switches on/off and the text appearance changes as expected.
4. Toggle the underline or strikethrough switches on/off.

### Expected Behavior

The text is underlined/receives strikethrough, and when toggling the switches to off the text decoration is undone.

### Actual Behavior

The text is underlined/receives strikethrough, but the text decoration remains when toggling the switches to off.

### Basic Information

- Version with issue: 3.3 -pre3.
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  12.0
  - Android: API 27.
  - UWP:  Not tried.
- Android Support Library Version: 27.0.2.1

### Screenshots

Underline switch toggled on:

![simulator screen shot - iphone 8 - 2018-10-18 at 10 26 07](https://user-images.githubusercontent.com/8092460/47144892-667fb780-d2c0-11e8-8490-3d63726c4bbb.png)

Underline switch toggled off:

![simulator screen shot - iphone 8 - 2018-10-18 at 10 26 12](https://user-images.githubusercontent.com/8092460/47144901-6c759880-d2c0-11e8-856a-a87522c3de29.png)

### Reproduction Link

[SwitchDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2491188/SwitchDemo.zip)

**Comment by LeoJHarris** [comment]
Any chance this will be fixes any time soon?

**Comment by samhouts** [comment]
There is an open PR for it, but I think we're still working on it. Thanks!

**Comment by LeoJHarris** [comment]
@samhouts thanks for the update! Hope it can be resolved soon that would be great!

**Comment by Mikilll94** [comment]
Any update on this?

**Comment by mackayn** [comment]
Just ran into this as well in 4.6.0 SR5

**Comment by jfversluis** [comment]
Can't reproduce in 5.0.0 SR7 (5.0.0.2244), let me know if this is still an issue for someone!

**Comment by PlatypusJo** [comment]
I have this problem in 5.0.0.2622
