### ISSUE TITLE
PanUpdated event of PanGestureRecognizer does not trigger when add Gesture to a layout, hosting a scrollview as its child

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#4122]
### Description
Hi Team,

PanUpdated event of PanGestureRecognizer does not trigger when add Gesture to a layout, hosting a scrollview as its child

### Steps to Reproduce

1. Run the sample.
2. Put the breakPoint to PanUpdated event.
3. Now Scroll the ListView . The PanUpdated event does not fire.
4. PanUpdated event does not fire. even there is no scroll able content in ListView.

### Expected Behavior
PanUpdated event should be fire.
### Actual Behavior
PanUpdated event does not fire.
### Basic Information

- Version with issue: 2.4.0.280
- IDE:  2017
- Platform Target Frameworks: Xamarin.Forms.Android

Android: 8.1
Nuget Packages: 2.4.0.280
Affected Devices: All Android device.

### Reproduction Link
[FrameWork.zip](https://github.com/xamarin/Xamarin.Forms/files/2491295/FrameWork.zip)
[FrameWork1.zip](https://github.com/xamarin/Xamarin.Forms/files/2491767/FrameWork1.zip)
[FrameWork 2.zip](https://github.com/xamarin/Xamarin.Forms/files/2491835/FrameWork.2.zip)

**Comment by hartez** [comment]
Yes, this is a known issue. The ScrollView intercepts the touch events to handle scrolling. 

Moving this into enhancements; it may be covered by the upcoming gesture work.

**Comment by MdNaushad** [comment]
@hartez Can you let me know in which release should we expect this to be fixed?

**Comment by hartez** [comment]
@MdNaushad At the moment I cannot say; the gesture work which may address this has not been scheduled.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
