### ISSUE TITLE
ToolbarPlacement doesn't work on UWP

### ISSUE THREAD

**Issue by dannythomas13** [xamarin/Xamarin.Forms#4123]
The following will correctly place the tabs on the bottom for Android, but not UWP, is this a bug or have I done it incorrectly?

<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
            android:TabbedPage.ToolbarPlacement="Bottom"
            xmlns:windows="clr-namespace:Xamarin.Forms.PlatformConfiguration.WindowsSpecific;assembly=Xamarin.Forms.Core"
            windows:Page.ToolbarPlacement="Bottom"
            x:Class="eWorker.Core.Pages.MainPage"
            xmlns:local="clr-namespace:eWorker.Core.Pages">
    <NavigationPage x:Name="navigationPage" Title="My Work">
    </NavigationPage>
    <ContentPage Title="Profile">
        <StackLayout>
            <Label Text="Profile" 
                    HorizontalOptions="Center"
                    VerticalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage>
</TabbedPage>

**Comment by hartez** [comment]
@dannythomas13 I think you might want to try filing that again.
