### ISSUE TITLE
Make transitive refs use Xamarin Forms targets build targets.

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4126]
### Description
- Net Standard Library A that References XF
- Net Standard Library B that References Library A but doesn't reference XF
- Now if I add an XF XAML file to Library B then Library B won't compile because the transitive targets from Library A aren't running against Library B. If you open the code behind file for the XAML you'll see that all the XF class references are resolving so the library is transitively applied to B but the XAML isn't able to run

- Possible Fix
https://github.com/reactiveui/refit/blob/master/Refit.HttpClientFactory/Refit.HttpClientFactory.csproj#L11
https://twitter.com/onovotny/status/1052713546801405952
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

### Steps to Reproduce

1. Open Attached Project
2.  Try to build

### Expected Behavior
Build Works

### Actual Behavior
Build fails because Triage NetStandard Library isn't getting the transitive build targets applied 

### Basic Information

- Version with issue: 3.4
- Last known good version: Always

### Reproduction Link
[TransitiveTargets.zip](https://github.com/xamarin/Xamarin.Forms/files/2492476/TransitiveTargets.zip)

**Comment by StephaneDelcroix** [comment]
Once this is fixed, there's another problem to take care of: at least in VSMac, we do not have the new file templates for XF on Library B

**Comment by StephaneDelcroix** [comment]
I don't think this is a bug, more the default behavior. The `compile` asset is transitive, the `build` is not by default. There's no way in our XF nuget to declare an override for PrivateAssets that'll be included on package reference.
In addition, doing that will have a huge build perf implication as XamlC will run on all assemblies, including the native ones.

Declaring the XF nuget as a development dependency, or setting `PrivateAssets="content files;analyzers"` is, at the end, the choice of the nuget package consumer, and even if that was our intention, we have no way of being prescriptive on that matter.

thanks @mrward for the explanations
