### ISSUE TITLE
[Enhancement] Extend ContentView 

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#4127]
### Rationale

We often need a container view which displays a single data item (an `object`), by creating the child view  using a `DataTemplate` / `DataTemplateSelector` and bind this child view to the data item. (similar to the mechanism used by `ListView` to display every item in ItemsSource).

In **UWP**/**WPF** this container is the popular [`ContentControl`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentcontrol). 
The `ContentControl` displays a "content" materializing  it based on the `ContentTemplate` and the `ContentTemplateSelector` propeties:

```
<ContentControl Content="{Binding SelectedEmployee}" ContentTemplateSelector="{Binding EmployeeItemTemplateSelector}" />
```

In **Xamarin Forms** a similar control is the `ContentView`.
But there's no baked-in or a easy way to bind to a data item and create the child view based on a DataTemplate/ControlTemplate. One needs to create a mechanism to achieve this, and it's ugly, here's just one example: https://forums.xamarin.com/discussion/84810/datatemplates-and-contentcontrols
There are other ways but all require extra work for such a simple task.

### Implementation
Add three bindable properties to `ContentView` class:
```
public object ContentItem { get; set; }   
public DataTemplate ContentTemplate { get; set; }
public DataTemplateSelector ContentTemplateSelector { get; set; }
```

When any of these properties are set (at least one is required to be set), instead of using the `View` instance returned by `Content` property,  the `ContentView` creates the child view using these properties.
The child view is created trying to use ContentTemplate/ContentTemplateSelector if any of them are set, and the child view has the binding context bound to the value of the `ContentItem` property.

**Another option to consider:**
Instead of adding a new property `ContentItem` from a backward compatibility point of view, how safe would it be to actually change the return type of the existing `Content` property from `View` to `object`? As far as I can tell, it shouldn't be a problem I think. This would be the **preferred** option.

### Expected Result

Have `ContentView` create a child based on the given data item (an `object`), and on the  given DataTemplate/DataTemplateSelector.

### Backward compatibility
It will just work. 
The new mechanism to create the child view of `ContentView` only kicks-in when any of the new properties are set. If none of them are set, it works like before.

### Difficulty 
Easy/Medium?

**Comment by andreinitescu** [comment]
Other naming options for the 3 properties:
```
public object Item { get; set; }   
public DataTemplate ItemTemplate { get; set; }
public DataTemplateSelector ItemTemplateSelector { get; set; }
```
I think this should be clearer and less confusing, since they differentiate much better than the `Content` property.

**Comment by charlesroddie** [comment]
This looks like it increases complexity of the ContentView class - more data and a lot more logic you have to understand to understand the ContentView. I don't see why your suggestion involves altering ContentView. You are suggesting a new view, ContentControl, which just inherits from ContentView. No need to hijack ContentView for this purpose.

Also I don't think Xamarin should be baking in further a specific approach to propogating changes in data to UI. Move all this stuff out to separate libraries and keep Xamarin clean would be my vote.

**Comment by andreinitescu** [comment]
@charlesroddie 
> This looks like it increases complexity of the ContentView class - more data and a lot more logic you have to understand to understand the ContentView.

It doesn't increase any complexity, it just makes it more flexible.  My proposal is actually about making `ContentView` **MVVM friendly**, which now it's not. 

If you look to the "Backward compatibility" section, you should see that you can completely ignore these new properties and use it like before just fine.

> Also I don't think Xamarin should be baking in further a specific approach to propogating changes in data to UI.

You mean MVVM is bad and Xamarin should not improve support for it?

**Comment by charlesroddie** [comment]
> If you look to the "Backward compatibility" section, you should see that you can completely ignore these new properties and use it like before just fine.

Yes but it can no longer be explained what ContentView is simply. With your suggestion it will no longer just show the Content. It may show the content, and may do something completely different, depending on additional properties. So you have to understand your additional properties to understand how ContentView works.

You can explain "Although ContentView is complex, you can use it **as if** it shows the Content.". But that is rather inadequate.

> You mean MVVM is bad and Xamarin should not improve support for it?

Unfortunate how bindings/xaml are baked in. Really slows development and adds bugs.

**Comment by andreinitescu** [comment]
> With your suggestion it will no longer just show the Content. It may show the content, and may do something completely different, depending on additional properties. 

There's no confusion. The current `Content` takes a `View`. The new property I'm suggesting takes an object, a data item (it could actually be a `View` too, just how the `ContentControl` from UWP/WPF works)

It's a common pattern in Xamarin Forms and it's originating from Windows XAML (UWP/WPF), may controls take either views or data items.

> Unfortunate how bindings/xaml are baked in. Really slows development and adds bugs.

So in your opinion MVVM is bad. Now, what's wrong with data-binding? 
Data-binding spares us from a lot of plumbing code. With XAMLC (thanks @StephaneDelcroix), the performance is as fast as writing the code by hand, except it's all taken care of by magical unicorns 🦄

**Comment by charlesroddie** [comment]
There is a View called ContentView that does X. It's very simple and is used a lot. Let's keep it that way.

You want a View that does Y. You want to get ContentView to do Y as well as X. Why? Why not just make a different view that does Y?

**Comment by andreinitescu** [comment]
After adding the new properties, I'd actually deprecate the `Content` property (by adding the `Obsolete` attribute on it).
The more I think about it, I now wonder how safe would it be if we changed `Content` property from `View` to `object` and just use it?

> You want a View that does Y. You want to get ContentView to do Y as well as X. Why? Why not just make a different view that does Y?

Nope, with my proposal, the current `ContentView` still serves the **same** purpose, like stated in the documentation [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.contentview?view=xamarin-forms):
> An element that contains a single child element.

**Comment by charlesroddie** [comment]
> After adding the new properties, I'd actually deprecate the Content property

Lol

> Now, what's wrong with data-binding?

Not type safe, relies on magic strings, apprently requires pluming inside the UI framework not just outside. There are better methods of reactive UIs that don't suffer from these problems.

**Comment by andreinitescu** [comment]
> Not type safe, 

How come it's not type safe? Please read about XAMLC: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xamlc

> relies on magic strings, apprently requires pluming inside the UI framework not just outside

I get it, you hate XAML, MVVM and data-binding :)   And that's OK, whatever floats your boat

Let's not kid ourselves, in my opinion, no matter the programming language/library/framework you use, all the code you write every day is of magic "strings".

> There are better methods of reactive UIs that don't suffer from these problems.

Reactive programming is very nice, and ReactiveUI for example works well with MVVM.
But what does it have to do with this ticket?

**Comment by StephaneDelcroix** [comment]
Guys, please keep this discussion civil. Thanks.

Let me add my 2cents here. Thanks for this proposal, but I think you're trying to think this too far. a ContentView is already something that adapts itself to a "DataTemplate" (the View) and a context, the actual bindingContext.

If you need more than this, you can still add a few attached bindable properties to a ContentView, and use that. But it's very unlikely that we will accept this kind of capability directly in XF.Core in the foreseeable future.

**Comment by andreinitescu** [comment]
@StephaneDelcroix 
>  a ContentView is already something that adapts itself to a "DataTemplate" (the View) and a context, the actual bindingContext.

That's exactly my point and I already mentioned it in the description. 
The existing ContentView is not MVVM friendly, it doesn't do have this capability and it requires extra work to achieve this. It's missing a key feature.

**Comment by legistek** [comment]
I agree with this proposal and would really like to see it made. @StephaneDelcroix there's no way (that I can find?) to declare a `DataTemplate` as a `StaticResource` and then assign it as the template for a `ContentView`, which is a very common need. Instead you have to make a new `ContentView` as a .xaml and .xaml.cs pair. That's pretty cumbersome and there's no way to change the template at runtime. Not clear why we wouldn't want to just have a `ContentControl` as described. I'm happy to write it and PR it. Or am I missing something?

**Comment by legistek** [comment]
Why not something as simple as this:

https://github.com/xamarin/Xamarin.Forms/compare/master...legistek:contentcontrol

?
