### ISSUE TITLE
EventHandler Signature Error in 3.3.0 

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#4130]
Signature (parameter 1) of EventHandler "OnFilterTextChanged" doesn't match the event type

Control:

`public delegate void SelectedTextChangedEventHandler(object sender, TextChangedEventArgs args);`
`public event SelectedTextChangedEventHandler TextChanged;`

XAML:
`<controls:EntryEx TextChanged="OnFilterTextChanged"/>`

Code:

`private void OnFilterTextChanged(object sender, EventArgs args)` // Error
`private void OnFilterTextChanged(object sender, TextChangedEventArgs args)` // OK

**Comment by hartez** [comment]
@mknotzer Are you talking about a third-party project of some sort? Forms doesn't contain a control called "EntryEx".

**Comment by StephaneDelcroix** [comment]
could you please:
- use the [template](https://github.com/xamarin/Xamarin.Forms/blob/master/ISSUE_TEMPLATE.md) for filing issues, and more important fill the version informations (last good one, version with problem)
- attach the simplest possible project triggering your problem

Thanks a lot

**Comment by StephaneDelcroix** [comment]
as a workaround, you can define your event this way, and avoid declaring a delegate

```csharp
public event EventHandler<TextChangedEventArgs> TextChanged;
```

**Comment by andreinitescu** [comment]
XamlC seems like it only wants the event handler with `EventArgs`, although `TextChangedEventArgs` is derived from `EventArgs`.

Not sure, I think the issue is XamlC choosing the `TextChanged` event from `Entry`, not the `TextChanged` event from the derived class `EntryEx` (maybe an issue with reflection?)

What's interesting is when disabling XamlC it works:
```
[assembly: XamlCompilation(XamlCompilationOptions.Skip)]
```
@mknotzer  Can you confirm it's working for you if you change to `XamlCompilationOptions.Skip` in App.xaml.cs?

@mknotzer Please attach a reproduction case so that @StephaneDelcroix should debug it

**Comment by mknotzer** [comment]
The error only occurs with
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]

No error message with
[assembly: XamlCompilation(XamlCompilationOptions.Skip)]

**Comment by mknotzer** [comment]
workaround is working

`public event EventHandler<TextChangedEventArgs> TextChanged`

**Comment by DieselSoup** [comment]
Hello,

I started experiencing this issue after updating Xamarin.Forms to version 3.6.0.293080. Came up with a workaround by switching "TappedEventArgs" to just "EventArgs" in my code behind. Any update on the status of this issue?

**Comment by FreedomDesi** [comment]
Hello,
When i update the Xamarin.Forms version 3.6.0.293080.Come up with many error.If any solutions then help me.
 
![picturemessage_u0uv3hyd q3h](https://user-images.githubusercontent.com/24875408/55953886-ef2d4e00-5c7a-11e9-9e97-15cde8ce8857.png)

**Comment by StephaneDelcroix** [comment]
@DieselSoup @FreedomDesi this issue is closed. if you have a similar one with 3.6.0, please open a new issue, AND ATTACH A SMALL REPRO PROJECT. ping me when it's done, and I'll look at it

Thanks a lot.

**Comment by StephaneDelcroix** [comment]
see #5887 for reopened issue

**Comment by FreedomDesi** [comment]
> 
> 
> Hello,
> 
> I started experiencing this issue after updating Xamarin.Forms to version 3.6.0.293080. Came up with a workaround by switching "TappedEventArgs" to just "EventArgs" in my code behind. Any update on the status of this issue?

If you have to changed TappedEventArgs to EventArgs then no issue will happening in code behind.In latest Xamarin forms you must change the all events like "SelectedItemChangedEventArgs" to "EventArgs" and all Button click events must have (object sender, EventArgs e) parameter.
