### ISSUE TITLE
Touch sensitivity is poor for elements in iOS devices

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#4137]
Hi All,

TouchMoved override method is not sensitive while swiping rapidly over the items, but the TouchBegan and TouchEnded override is called as expected. TouchMoved gets called only when pressed hard and moved over an item. I have tried using DelaysTouchesBegan and DelaysTouchesEnded properties but still couldn’t achieve the performance as expected. 

I have checked by extending the grid element and swiped rapidly. Found that the touch overrides are called correctly. But when I have used the same grid inside a simple layout as below.

<Grid>
    <ScrollView>
        <local:GridExt>
            <Label/>
        </local:GridExt>
    </ScrollView>
</Grid>

Now when I swiped rapidly over the Label/Grid element moved override doesn’t call.

Can anyone please let me know whether this is the default touch behavior in iOS platform or have any workaround to call the TouchMoved override once touch began and moved with slight movement over an element.

For your reference, we have attached the sample which replicates the issue and you can download it from the below link.

[Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/2495498/Bug.zip)

Replication procedure:
Step 1: Run the attached sample.
Step 2: Swipe over the item **rapidly**.
Step 3: Note the output window 

Actual Behavior:
It can be seen that only TouchBegan and TouchEnded override method will be called.

Expected behavior:
TouchMoved should also be called when moved rapidly. When having Grid element alone in the view and swiped rapidly, the touch moved is working as expected. 

Tested Devices:
iPAD - Model: A1538
iOS version: 10.3.2

iPhone 8
iOS version: 11.0

Thanks,
G.Muthu kumaran.

**Comment by hartez** [comment]
> When having Grid element alone in the view and swiped rapidly, the touch moved is working as expected.

You see fewer events when your control is in a ScrollView because it's capturing  some of the touches. If you want all of the touches to be sent to your GridExt control first, you'll need to subclass ScrollViewRenderer and process the TouchesMoved event there.

**Comment by hartez** [comment]
Do you want to know how far the user has moved the touch since it began? If that is what you want, it may be easier to add a UIPanGestureRecognizer to GridExRenderer. Something like this:
```
        public GridExtRenderer() 
        {
            var t = new UIPanGestureRecognizer((pgr) => Debug.WriteLine($">>>>> MyScrollViewRenderer GridExtRenderer: {pgr.TranslationInView(this)}"));
            AddGestureRecognizer(t);
        }
```
