### ISSUE TITLE
[iOS] NavigationPage.TitleIcon no longer centered

### ISSUE THREAD

**Issue by petermajor** [xamarin/Xamarin.Forms#4138]
### Description
With Xamarin Forms 3.2, the TitleIcon used to be center aligned. 
With Xamarin Forms 3.3, the TitleIcon is not center aligned.

### Expected Behavior
The TitleIcon in the navigation bar should be center aligned

### Actual Behavior
The TitleIcon in the navigation bar is top, left aligned

### Basic Information

- Version with issue: 3.3.0
- Last known good version: 3.2.x
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:  12.0.0.15
- Nuget Packages:
- Affected Devices:

### Screenshots

3.2.0
![titleicon_3_2_0](https://user-images.githubusercontent.com/6995790/47214478-f7749280-d395-11e8-945a-e7fb84594027.png)

3.3.0
![titleicon_3_3_0](https://user-images.githubusercontent.com/6995790/47214482-fb081980-d395-11e8-91b8-31d00abf2296.png)

### Reproduction Link

https://github.com/petermajor/TitleIconBug
Repository is using Xamarin Forms 3.2 package
It behaves as expected
Update Xamarin Forms to 3.3, Title Icon does not behave as expected

**Comment by hartez** [comment]
@petermajor Your repro project isn't building - can you fix the build errors so we can see the issue?

**Comment by petermajor** [comment]
@hartez My bad! 

Sorry to waste your time on that. Please try again.

**Comment by hartez** [comment]
@petermajor Thanks! 

Yep, it's very definitely not centered.

**Comment by gjkhw** [comment]
I bumped into this as well. FWIW, it would be nice if the docs for SetTitleIcon showed images for platforms beside iOS, since the behavior varies by platform (Android has always placed the icon on the left, and continues to do so in 3.3, for instance).

**Comment by ChrisTTian667** [comment]
I also bumped into this, because it's not possible to center at all. Even when you are using TitleView, in case you are using ToolbarItems (as we do) as well.

**Comment by starkos** [comment]
Even if you try to center it manually, it is placed off-center, at least on iOS.

```xml
<NavigationPage.TitleView>
    <Label Text="Title" HorizontalOptions="Center" VerticalOptions="Center" />
</NavigationPage.TitleView>
```
<img width="404" alt="screen shot 2018-11-07 at 10 40 36 am" src="https://user-images.githubusercontent.com/249247/48141993-f1c5ea80-e279-11e8-9bc5-0b2ac48ec017.png">

Awesome feature though, makes life so much easier.

**Comment by jameslavery** [comment]
I see this is marked as _Done_. When can we see a release with this fixed?

I'm assuming it's not in 3.4.0.1008975, which we're using and we're seeing this problem.

**Comment by PureWeen** [comment]
It'll be part of the next SR for 3.4 @jameslavery

**Comment by jameslavery** [comment]
> It'll be part of the next SR for 3.4 @jameslavery

Thanks - you know what I'm about to ask... Any idea when that'll be? Feel free to point me to the right place where the release schedule is published!

The good news is that I can tell my customer that it's been fixed!

**Comment by PureWeen** [comment]
@jameslavery 

*Fingers crossed* if it gets through QA it should be an early xMas :-)
