### ISSUE TITLE
Chain validation failed exception after TLS 1.2 changes

### ISSUE THREAD

**Issue by Rajeswari06** [xamarin/Xamarin.Forms#4139]
### Description

I have modified my the android properties like below to update TLS1.2

HttpClient implementation - Android
SSL/TLS implementation - Native TLS 1.2+
Android httpclient - 
var client = new HttpClient(new Xamarin.Android.Net.AndroidClientHandler ());

After updating functionality is working fine in all devices except samsung Tablet with latest android version. we are getting Chain validation failed exception message

### Steps to Reproduce

1. Implement tls 1.2 changes
2. Invoke API
3. Check the exception 

### Expected Behavior

API should give the proper response

### Actual Behavior

Exception was coming 

### Basic Information

- Version with issue: 3.0.0.561731
- Last known good version: 3.0.0.561731
- IDE:visual studio
  - Android: all versions above 5.0
- Affected Devices: Samsung Tablet with latest android version

![tls1 2](https://user-images.githubusercontent.com/23097051/47215351-c78db500-d3be-11e8-8e78-90bd571aaaa3.PNG)
[chainvalidation.txt](https://github.com/xamarin/Xamarin.Forms/files/2495589/chainvalidation.txt)

**Comment by hartez** [comment]
@Rajeswari06 Does your tablet have the correct time and date settings?

**Comment by Rajeswari06** [comment]
Thank you @hartez.

Its working fine after setting date and time format to current.
