### ISSUE TITLE
ViewCell is not reused on UWP when ListViewCachingStrategy is set to RecycleElement.

### ISSUE THREAD

**Issue by bhaveshsoft1** [xamarin/Xamarin.Forms#4148]
I’m able to reproduce this, most simply, but using the built in ListView and ViewCell. My MainPage xaml looks like:

 

ViewCell is not reused on UWP when ListViewCachingStrategy is set to RecycleElement.

		<?xml version="1.0" encoding="utf-8" ?>

		<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"

					 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"

					 xmlns:local="clr-namespace:DoesListViewLeak"

					 x:Class="DoesListViewLeak.MainPage">

			 <StackLayout>

				

				<Label Text="Welcome to Xamarin.Forms!"

				   HorizontalOptions="Center"

				   VerticalOptions="Start" />

				<ListView x:Name="MessageListView"

								  SeparatorVisibility="None"

								  Margin="0,0,0,0" 

								  HasUnevenRows="True"

								  HorizontalOptions="FillAndExpand"

								  VerticalOptions="FillAndExpand">

					<x:Arguments>

						<ListViewCachingStrategy>RecycleElement</ListViewCachingStrategy>

					</x:Arguments>

					<ListView.ItemTemplate>

						<DataTemplate>

							<ViewCell>

								<Label x:Name="MessageLabel"

										   Text="{Binding MessageText}"

										   BackgroundColor="#AABFCB"

										   HorizontalOptions="FillAndExpand"

										   VerticalOptions="FillAndExpand"

										   Margin="0"/>

							</ViewCell>

						</DataTemplate>

					</ListView.ItemTemplate>

				</ListView>

				<Button Text="Add Message" Clicked="AddMessageButton_Clicked" />

				<Button Text="GC" Clicked="GCButtonClicked" BackgroundColor="#BFDDEB" FontSize="Micro"/>

			</StackLayout>

		</ContentPage>

 

My code-behind:

		using System;
		using System.Collections.Generic;
		using System.Collections.ObjectModel;
		using System.Linq;
		using System.Text;
		using System.Threading.Tasks;
		using Xamarin.Forms;
		 
		namespace DoesListViewLeak

		{
			public partial class MainPage : ContentPage
			{

				// try observable collection
				// try adding INotifyPropertyChanged
				//private ObservableCollection<Message> _messages =

				//    new ObservableCollection<Message>();

				private ObservableCollection<Message> _messages =

					new ObservableCollection<Message>();

				public MainPage()
				{
					InitializeComponent();
				}

				private void AddMessage()
				{
					_messages.Add(new Message { MessageText = $"m{_messages.Count}" });
				}

				protected override void OnAppearing()
				{
					base.OnAppearing();

					for (var i = 0; i < 4; i++)
					{
						AddMessage();
					}
		 
					MessageListView.ItemsSource = _messages;
				}

				private void AddMessageButton_Clicked(object sender, EventArgs e)
				{
					AddMessage();
				}

				private async void GCButtonClicked(object sender, EventArgs e)
				{
					GC.Collect();

					await Task.Delay(TimeSpan.FromMilliseconds(250));

					GC.Collect(1);
					GC.Collect(2);

					await Task.Delay(TimeSpan.FromMilliseconds(250));

					GC.Collect(1);
					GC.Collect(2);
				}
			}
		}

The app starts by adding 4 items to an observable collection and setting it as the ItemSource. At this point, there are 4 ViewCell objects in memory

Next, I have a button to add things to the list at runtime. Each time 1 item is added to the observable collection, 2 ViewCells are added in memory.

By the time I’ve added about 100 messages, I have over 300 ViewCell items in memory.

Clicking the button to perform GC does not free any of the ViewCell items from memory.
Expected behavior is that when RecycleView is set as ListViewCachingStrategy then the  ViewCells should be re-used and we only keep enough to display the items from the ItemSource which are visible on screen.

However, we see that atleast 2 ViewCells are created for each item added to the ItemSource at runtime and no ViewCells are reused.

**Comment by rmarinho** [comment]
There's no support for UWP and `ListViewCachingStrategy` . 
That said i think we shouldn't have 300 ViewCell created. Marking as enhancement

**Comment by mattregul** [comment]
is there any known workaround for this?

**Comment by kwiqniss** [comment]
Hi rmarinho,
According to https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/performance
The Universal Windows Platform (UWP) ignores the RetainElement caching strategy, because it always uses caching to improve performance. Therefore, by default it behaves as if the RecycleElement caching strategy is applied.
So, the RecycleElement caching strategy should be valid.

**Comment by rmarinho** [comment]
You are correct, it was my mistake. I will look at this with the team.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
