### ISSUE TITLE
Support for Windows UWP IOT core app Navigation

### ISSUE THREAD

**Issue by squinn7** [xamarin/Xamarin.Forms#4151]
We got a strange customer request this week and I figured it was worth asking. 

Customer requested if they could use one of our Xamarin forms apps on a Raspberry pi. We got a test device and loaded Windows IOT core on it.

The app indeed works correctly however, there is no navigation back button. The post below is the most relevant material I can find on the topic.

https://social.msdn.microsoft.com/Forums/en-US/971ce18a-9988-4a87-b0ce-1e252110b173/how-is-the-back-button-handled-on-windows-10-iot-core?forum=WindowsIoT 

My question is, since Microsoft seems to recommend implementing the back button in software, is this something that will be done in Xamarin forms at some point or not? I am not really putting this in as a feature request but more so wondering if it is already in the works or if a work around currently exists.

Thanks in Advance

**Comment by hartez** [comment]
@squinn7 I'm going to put this in the Enhancements section for now. It's possible that we _might_ address this a some point in the future, but it's not a high priority at the moment. That said, if someone were to submit a PR for handling it, that'd be awesome.

**Comment by jfversluis** [comment]
Guess we never got to this, thanks for the suggestion!
