### ISSUE TITLE
BoxView CornerRadius doesn't work on iOS

### ISSUE THREAD

**Issue by IslamKHALIL** [xamarin/Xamarin.Forms#4152]
### Description
Using Xamarin.Forms 3.3 (latest release), I try to use BoxView control with CornerRadius set to 180 do draw Ellipse; it's working as intended on Android but not on iOS as rectangle gets displayed ignoring the CornerRadius property.
### Steps to Reproduce

1. Create new Xamarin.Forms blank project
2. Type this code in the MainPage.xaml:
<Grid>
        <BoxView CornerRadius="180"
                 HeightRequest="50"
                 WidthRequest="50"
                 BackgroundColor="Red"
                 VerticalOptions="Center"
                 HorizontalOptions="Center" />
    </Grid>
3. Run the iOS project.

### Expected Behavior
Red ellipse (circle) gets displayed in the middle of the screen.
### Actual Behavior
Red rectangle gets displayed in the middle of the screen.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 Community & Visual Studio for Mac Community
- Platform Target Frameworks: 
  - iOS:  11.4
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
> Type this code in the MainPage.xaml:

@IslamKHALIL I think you missed pasting in some code :)

**Comment by IslamKHALIL** [comment]
It's a totally blank project and this is the only code that you need to write to reproduce the issue:
`
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ExploreXamarinForms.Views.MainPage">
    <Grid>
        <BoxView CornerRadius="180"
                 HeightRequest="50"
                 WidthRequest="50"
                 BackgroundColor="Red"
                 VerticalOptions="Center"
                 HorizontalOptions="Center" />
    </Grid>
</ContentPage>
`
And here's a screenshot of the whole solution if it helps: 
![image](https://user-images.githubusercontent.com/14354738/47250166-6cd77600-d41d-11e8-9e52-a0b1c0265a52.png)

**Comment by StephaneDelcroix** [comment]
As soon as you use a `CornerRadius` value bigger than the ½ of the smallest dimension, you start, indeed, to get what might look like strange drawing artifacts.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/313003/47293241-de741780-d609-11e8-8a3e-32211b70a46c.png">

This is probably not a bug, and there's no way for us to get a consistent degraded mode for all platforms. But we could probably ensure that the sum of corner radii in one direction are never bigger that the size in that direction

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
