### ISSUE TITLE
App crashes on start with Mac Xamarin.Forms v3.3 

### ISSUE THREAD

**Issue by Papirosnik** [xamarin/Xamarin.Forms#4153]
### Description
I have updated Xamarin.Forms package in my app on Mac from version 3.2. to 3.3 and now the app crashes immediately on start.
NullReference has been thrown in NSApplication.Main(args);
### Steps to Reproduce

1. Create a blank Xamarin.Forms app on mac
2. Ensure that XF is of version 3.3
3. Launch it and observe  crash at the start

### Expected Behavior
It should work

### Actual Behavior
It does not work

## Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: 3.2.0.871581
- IDE: Visual Studio for Mac 2017 (7.6.9 build 22)
- Platform Target Frameworks: 
    Xamarin.Mac

- Nuget Packages: Realm, NUnit, Newtoonsoft.Json, HtmlAgilityPack, Xam.Plugin.Connectivity, Xam.Pluggin.Settings, Xamarin.Forms

- Affected Devices: can suppose all mac device

### Screenshots

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) AppKit.NSApplication.NSApplicationMain (int,string[]) [0x0005a] in <f1c86876a1c44005b0ee4cf99f2fbb91>:0
  at AppKit.NSApplication.Main (string[]) [0x00040] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.0.0.0/src/Xamarin.Mac/AppKit/NSApplication.cs:100
  at Moneytracker.Mac.MainClass.Main (string[]) [0x00048] in /Users/slavak/work/moneytracker/Moneytracker.Mac/Main.cs:11
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x00051] in <51a57b12ab604853b753a4a0747075da>:0

Native stacktrace:

	0   Money Tracker                       0x00000001010346e8 mono_handle_native_crash + 264
	1   Money Tracker                       0x0000000100fb0f06 altstack_handle_and_restore + 70
	2   libobjc.A.dylib                     0x00007fff7e4fd184 objc_release + 36
	3   libobjc.A.dylib                     0x00007fff7e4fe087 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 817
	4   AppKit               New Frame - {X=0,Y=100,Width=0,Height=0}
               0x00007fff549b539b __37+[NSDisplayCycle currentDisplayCycle]_block_invoke + 244
	5   QuartzCore                          0x00007fff6264c8c7 _ZN2CA11Transaction19run_commit_handlersE18CATransactionPhase + 49
	6   QuartzCore                          0x00007fff6264b389 _ZN2CA11Transaction6commitEv + 171
	7   AppKit                              0x00007fff5516da72 __65+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayRefresh]_block_invoke + 283
	8   CoreFoundation                      0x00007fff572f9417 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	9   CoreFoundation                      0x00007fff572f933f __CFRunLoopDoObservers + 527
	10  CoreFoundation                      0x00007fff572db8b8 __CFRunLoopRun + 1240
	11  CoreFoundation                      0x00007fff572db153 CFRunLoopRunSpecific + 483
	12  HIToolbox                           0x00007fff565c5d96 RunCurrentEventLoopInMode + 286
	13  HIToolbox                           0x00007fff565c5a0f ReceiveNextEventCommon + 366
	14  HIToolbox                           0x00007fff565c5884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	15  AppKit                              0x00007fff54876a73 _DPSNextEvent + 2085
	16  AppKit                              0x00007fff5500ce34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	17  AppKit                              0x00007fff5486b885 -[NSApplication run] + 764
	18  AppKit                              0x00007fff5483aa72 NSApplicationMain + 804
	19  ???                                 0x000000010867bc9e 0x0 + 4435983518
	20  ???                                 0x000000010868bdbb 0x0 + 4436049339
	21  Money Tracker                       0x0000000101047e41 mono_jit_runtime_invoke + 1441
	22  Money Tracker                       0x0000000101143a1f mono_runtime_invoke_checked + 127
	23  Money Tracker                       0x000000010114a96e mono_runtime_exec_main_checked + 110
	24  Money Tracker                       0x0000000100fa6f49 mono_jit_exec + 297
	25  Money Tracker                       0x0000000100fa9f24 mono_main + 11124
	26  Money Tracker                       0x0000000100f47ae9 xamarin_main + 1305
	27  Money Tracker                       0x0000000100f48ab4 main + 36
	28  libdyld.dylib                       0x00007fff7f122015 start + 1

**Comment by rmarinho** [comment]
@Papirosnik can you give us a reproduction ?

thanks

**Comment by Papirosnik** [comment]
> @Papirosnik can you give us a reproduction ?
> thanks

No, I can't.
But you can take it from over here: 
https://github.com/xamarin/Xamarin.Forms/issues/4156

**Comment by rmarinho** [comment]
I just wanted to make sure it was the same issue. so closing as duplicate
