### ISSUE TITLE
GoogleService-Info.plist does not load? (Xamarin forms iOS)

### ISSUE THREAD

**Issue by TimVanDenEnden** [xamarin/Xamarin.Forms#4154]
I am trying to use Firebase cloud message system. For that I need to load the GoogleService-Info.plist but when I try to open it gives me this error.

<img width="1680" alt="screenshot 2018-10-20 at 11 45 58" src="https://user-images.githubusercontent.com/21998860/47254130-df684600-d45d-11e8-9b29-ec8215e5771c.png">

The Build action is set to: BundleResource.

**Comment by AndreiMisiukevich** [comment]
@TimVanDenEnden it seems to be VS problem (not Xamarin.Forms) :)
https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem

**Comment by TimVanDenEnden** [comment]
@AndreiMisiukevich Thx for your time.

**Comment by abdo-012** [comment]
Guy any one have a soulution for this
