### ISSUE TITLE
Forms 3.3 + Mac (Regression+Crash) Changing MainPage

### ISSUE THREAD

**Issue by Abhijit-Revamp** [xamarin/Xamarin.Forms#4156]
### Description
Crash after updating to 3.3 Stable. In Forms + Mac, changing Applications Main Page crashes. Working in 3.2

### Steps to Reproduce
Steps for regression crash
1. Create a new Project with Forms 3.2 + iOS (Android not required now)
2. Add a MacOS cocoa project with Forms 3.2 dependency. Set this as default project.
3. Make necessary changes in macOS files and ensure the MainPage is visible. 
4. Add a new SecondPage.XAML
5. In App.xaml.cs, change the app's MainPage to SecondPage.XAML (just to verify its working)
6. To the SecondPage add a button 'Click Me'. In the button handler add the following code
`var myApp = (App)Xamarin.Forms.Application.Current;`
`myApp.MainPage = new MainPage();`
7. Run the macOS app, click the button 'Click Me'. Wait for few seconds >>CRASH <<

### Expected Behavior
Specified page must be visible and application continues to work.
### Actual Behavior
 >>CRASH<<
### Basic Information

- Version with issue: 3.3.0.912450
- Last known good version:3.2.0871581
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - macOS: 10.11 
- Nuget Packages: forms 3.3.0.912450
- Affected Devices:

**Comment by AndreiMisiukevich** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/4153 duplicated

**Comment by AndreiMisiukevich** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/4153 duplicated

**Comment by AndreiMisiukevich** [comment]
I investigated

Breaking commit: cceee9ded6c8cadb19eb547f72d03c6c14230058

Remove it, and all will work properly 

```csharp
#if __MACOS__
		public override NativeView NextKeyView { 
			get {
				return FocusSearch (forwardDirection: true) ?? base.NextKeyView;
			}
			set {
				if (value != null) // setting the value to null throws an exception
					base.NextKeyView = value;
			}
		}

		public override NativeView PreviousKeyView {
			get {
				return FocusSearch (forwardDirection: false) ?? base.PreviousKeyView;
			}
		}
#else
```

This is strange, but if you leave just

```csharp
		public override NativeView PreviousKeyView {
			get {
				return base.PreviousKeyView;
			}
		}
```

It will continue crash the app

**Comment by Abhijit-Revamp** [comment]
Release notes of 3.3.0.967583 says this issue is fixed --> [Release Notes](https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.3/3.3.0-sr1/)

It still crashes.

**Comment by maxim-saplin** [comment]
Same trouble with NullReferenceException in AppKit.NSApplication.NSApplicationMain in Xamarin.Forms 3.3, 3.4 and 4.0 pre1 on Mac. 
3.2 works fine. 
In my case the exception happens whenever Xamarin.Forms animation is triggered, other parts of my app seem to work fine.

**Comment by taterjuice** [comment]
4.0 prerelease has this issue as well. Can't build any apps with more than 1 page. Completely nonfunctional.

**Comment by taterjuice** [comment]
Any ETA on this release?

**Comment by Abhijit-Revamp** [comment]
@samhouts can we have an ETA on this please?
It's close to 90 days now... especially a **blocking** issue like this.

**Comment by DennisWelu** [comment]
Great to see the issue In Progress! Be sure to test on Mojave. It was after the update to Mojave and XF3.3 that I started having blocking issues, including this one, on MacOS.

**Comment by DennisWelu** [comment]
Circling back...great to have this fix, and it works!

**Comment by RadWes** [comment]
Latest update worked!  Good work!

**Comment by DeerSteak** [comment]
This is still happening on Xamarin.Forms 4.0 pre9. I reverted to 3.6 and was able to continue for now.

**Comment by DeerSteak** [comment]
@samhouts this is still present in Xamarin.Forms 4.0.0 final release. I had to downgrade to 3.6.0 again.

**Comment by samhouts** [comment]
@DeerSteak Thanks for the new issue! This one is specifically for MacOS, so I don't believe it is related. We'll take a look at your issue on 6244.

**Comment by KevinJalais** [comment]
Same here, changing MainPage in Xamarin.Forms.Application makes the MacOS app crash.

I first downgraded Xamarin.Forms from 4.0.0.49... to 3.6.0.34... and it was still crashing.
Then I downgraded Xamarin.Forms on the common library too, and it worked.
