### ISSUE TITLE
[Enhancement] Any way we could leverage UIStackView for StackLayout?

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4162]
I haven't used this control yet, but since it arranges its children either horizontally or vertically, we should look into using this native control for laying out items. This could be turned on through an experimental flag or an Assembly attribute for backwards compatibility.

**Comment by StephaneDelcroix** [comment]
Thanks for the suggestion. Making the StackLayout works, and behave like it does right now, on top of UIStackView (respecting the current options) looks like a lot of work for no real benefits.
