### ISSUE TITLE
[UWP]SearchBar.Focus()

### ISSUE THREAD

**Issue by sude22** [xamarin/Xamarin.Forms#4169]
### Description
Calling SearchBar.Focus() in ContentPage.OnAppearing(), the focus is not set.
### Steps to Reproduce

1. ContentPage with SearchBar
2. Call SearchBar.Focus() in ContentPage.OnAppearing()
3. Focus is not set

### Expected Behavior
The focus is set.
### Actual Behavior
The focus is not set.
### Basic Information

- Version with issue:3.3.0.912540
- Last known good version:2.5.x
- IDE:VS2017 15.8
- Platform Target Frameworks: 
  - UWP:  1809

**Comment by mjjames** [comment]
I can confirm I also have this issue since updating to the latest version of Xamarin.Forms. It was working for me in 3.2.x, I've checked the result code of .Focus and it does return true but it appears the text input doesn;t recieve the focus.

**Comment by sude22** [comment]
I wonder if I did something wrong, or if this bug is to unimportant that it's not even got a label :(
