### ISSUE TITLE
BoxView Margin not working version 3.3

### ISSUE THREAD

**Issue by jitendrajadav** [xamarin/Xamarin.Forms#4171]
### Description
BoxView Margin not working I have Margin="-10,0,-10,0" not working
I have attached Screen shot which is having tracking No# which is BoxView I need full width of BoxView 
please check
### Steps to Reproduce

1. Any ContentPage having grid and assing grid margin  "Margin="10,0,10,0"
2. Inside the grid add BoxView control and give margin to BoxView like Margin="-10,0,-10,0"
3. It wont work nagative margin in previos version of XF working fine

### Expected Behavior
It should work with negative margin 
### Actual Behavior
It won't work with negative margin 
### Basic Information
Microsoft Visual Studio Professional 2017 
Version 15.8.7
VisualStudio.15.Release/15.8.7+28010.2046
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Microsoft Visual Studio Tools for Applications 2017   00369-60000-00001-AA420
Microsoft Visual Studio Tools for Applications 2017

Visual C++ 2017   00369-60000-00001-AA420
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Windows Template Studio   2.4.18260.1
Windows Template Studio quickly builds a UWP app, using a wizard-based UI to turn your needs into a foundation of Windows 10 patterns and best practices.

Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.9 (d000f568b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Live Reload   0.4.0 (remotes/origin/dev@75526a0)
Provides live reload capabilities for Xamarin XAML.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.20 (HEAD/86d33f45b)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 

  - Android:  version 6 API Level 23

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![screenshot_20181023-121346](https://user-images.githubusercontent.com/1029026/47341237-29e7fd80-d6be-11e8-974e-b64e585802f9.png)

**Comment by StephaneDelcroix** [comment]
Could you be more explicit about what works, what does not, on which platform ?

What are your expectations for the negative values ?

**Comment by jitendrajadav** [comment]
@StephaneDelcroix Please have a look I have added more information and screen shot as well
thank you

**Comment by StephaneDelcroix** [comment]
in which XF version did you got that working before ?

**Comment by samhouts** [comment]
I'm not sure if this ever actually worked (@jitendrajadav if you know what version you saw this working in, please let us know), but you can achieve the desired affect by wrapping the Grid in a StackLayout. Thanks!
