### ISSUE TITLE
NavigationPage.TitleView right align don't work on UWP

### ISSUE THREAD

**Issue by wincotv** [xamarin/Xamarin.Forms#4174]
### Description
NavigationPage.TitleView right align don't work on UWP platform.
![image](https://user-images.githubusercontent.com/3726570/47299553-c2c53d00-d61a-11e8-83df-ce5110c46f16.png)

### Expected Behavior

Label : UserName aligned to right.

### Actual Behavior

Label aligned left.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - UWP: 17134   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/3726570/47299361-521e2080-d61a-11e8-9997-6084d58e66ee.png)

**Comment by YZahringer** [comment]
Same issue, UWP can not take the full width of the NavigationPage. Works on iOS & Android.

**Comment by YZahringer** [comment]
Fixed with #3987?

**Comment by wincotv** [comment]
I have installed XF 3.3.0.912540 and don't work.

**Comment by YZahringer** [comment]
@wincotv It's not released in XF v3.3.0.912540. Maybe in next SR.

**Comment by wincotv** [comment]
With 3.3.0.967583 it don't work on UWP. I have navbar defined in Xaml MasterDetailPage.
![image](https://user-images.githubusercontent.com/3726570/47911595-2dd20780-de96-11e8-8b60-97dea226f0e0.png)

**Comment by PureWeen** [comment]
@YZahringer  Yea :-/ unfortunately I had to back out the change that auto updated the size because of this bug

https://github.com/xamarin/Xamarin.Forms/issues/4116

If the user resizes the UWP window to be too small then the auto resize code would crash UWP
So once #4116 is fixed then I can put that code back in

**Comment by PureWeen** [comment]
@wincotv  can you open a new issue so we can make sure to track what you're seeing?

**Comment by wincotv** [comment]
I created new Issue #4292
