### ISSUE TITLE
Grid with scroll view in it is not scrollable.

### ISSUE THREAD

**Issue by TimVanDenEnden** [xamarin/Xamarin.Forms#4180]
Hi,
I am trying to make a grid with one static bar on the top and under it I want the scrollview fill the rest of the page. When I scroll I want the content go under the top bar.

```xaml
<ContentPage.Content>
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="AUTO"/>            
    </Grid.RowDefinitions>
            
    <ScrollView Grid.Row="0" BackgroundColor="Yellow">
        <StackLayout>
            <Grid>
                <Grid.RowDefinitions>
                    <RowDefinition Height="AUTO"/>  
                    <RowDefinition Height="AUTO"/>  
                </Grid.RowDefinitions>
                        
                <Frame Grid.Row="0" Padding="10" HeightRequest="500" Margin="10">
                    <Label Text="Test1"/>            
                </Frame> 
                <Frame Grid.Row="1" Padding="10" HeightRequest="500" Margin="10">
                    <Label Text="test2"/>            
                </Frame> 
                        
            </Grid>
        </StackLayout>
    </ScrollView>
            
    <StackLayout Grid.Row="0">
        <Frame Padding="30">
            <Label Text="Title of page"/>            
        </Frame>            
    </StackLayout>
            
</Grid>
</ContentPage.Content>
```

**Comment by mohammedwed** [comment]
The markup seems to be way over complicated for such a simple view!

StackLayout by default tries to fill the height of its container, but since the grid row height is set to Auto, the grid wants the StackLayout to determine the height, and the StackLayout is waiting for the grid row to specify height in order to render itself.

You also have both the ScrollLayout and the StackLayout positioned at row 0 of the main grid.

I would use only one grid as a container and specify the height of its first row, and set the second row height to * so it can take the rest of the screen, and position the ScrollView in the second row.

You can also refer to the Grid documentation for further details:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid

I hope this helps.

**Comment by TimVanDenEnden** [comment]
<img width="247" alt="screenshot 2018-10-23 at 08 01 22" src="https://user-images.githubusercontent.com/21998860/47338981-0d39ce80-d69a-11e8-9e77-4b54f0f9cc9b.png">

This image above show what I wanna achieve. I can not figure out how to do it.

**Comment by FedorSulaev** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="60">
            <RowDefinition Height="*">
        </Grid.RowDefinitions>

        <Frame Grid.Row="0">
            
        </Frame>

        <ScrollView Grid.Row="1">
            <Grid>
                
            </Grid>
        </ScrollView>

    </Grid>
</ContentPage>`

**Comment by FedorSulaev** [comment]
![image](https://user-images.githubusercontent.com/1536446/47340701-bd620400-d6a7-11e8-9df3-c62b71489d30.png)

**Comment by TimVanDenEnden** [comment]
@FedorSulaev Hey thank you for the code above it works 😃, Do you also maybe know how I can get the circle button flying above the scroll view at fixed position like in my image?

**Comment by FedorSulaev** [comment]
You can put it inside the main grid inside row 1 after the scroll view and it will be on the top.

**Comment by TimVanDenEnden** [comment]
@FedorSulaev I will like to have it in the right bottom corner. So when you scroll it stays at the right corner.

**Comment by FedorSulaev** [comment]
@TimVanDenEnden You'll need to set alignment and margins on the button
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/margin-and-padding
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options

**Comment by StephaneDelcroix** [comment]
@TimVanDenEnden looks like you got your question answered. closing

**Comment by TimVanDenEnden** [comment]
Yheaa got it working sorry I totally forgot to say thank you.

**Comment by hi2amit12** [comment]
thanks
