### ISSUE TITLE
Xamarin forms migration from 2.5 to 3.3 some errors occur

### ISSUE THREAD

**Issue by Sonic3R** [xamarin/Xamarin.Forms#4183]
**Isse one:**

I changed old code (to support xamarin 3.0) from:

    <OnPlatform x:Key="CrossPlatformStackOrientation" x:TypeArguments="StackOrientation">
              <On Platform="iOS" Value="Vertical"/>
              <On Platform="UWP" Value="Horizontal"/>
    </OnPlatform>

to

    <OnPlatform x:Key="CrossPlatformStackOrientation" x:TypeArguments="StackOrientation" iOS="Vertical" UWP="Horizontal" />

I met the following error: 

> No property, bindable property, or event found for 'UWP', or mismatching type between value and property.

If I remove `x:TypeArguments`, no error occur but on runtime, I got

> Cannot determine property to provide the value for

**Issue two:**

I get error 

> Expected '}'

for

    <Label Text="{Binding Description.CreationDateTime,Converter={StaticResource StringFormatConverter}, ConverterParameter='{0:dd-M-yyyy HH:mm:ss}'}"
                         Style="{StaticResource MyResourceText}" Grid.Row="0" Grid.Column="3" Margin="0,3,5,0"/>

at `ConverterParameter` attribute

**Issue three:**

for 

    <GridLength x:Key="TileSeparatorHeight">0</GridLength>

I got:

> The type 'GridLength' does not support direct content.

It happens for Thickness too:

    <Thickness x:Key="TileStartDatePadding">0,0,0,0</Thickness>

How to solve them ?

**Comment by StephaneDelcroix** [comment]
could you please:
- only report a single problem per ticket (open 3 different ones)
- use the template for reporting issues, and fill the required parts
- attach a sample project to your issues, so we can reproduce the issues.

Thanks
