### ISSUE TITLE
[Android] Rework  BackgroundTracker to not retain or possibly even use Bitmaps

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4185]
### Description
The current strategy for drawing borders into a biitmap and retaining a separate bitmap for every image isn't very efficient.  

A few thoughts
- don't retain a bitmap of the background just draw it
- use a drawable 
- look into using masks which might let you reuse a drawable or bitmap better

There are a lot of open source Android native projects that draw borders and backgrounds without retaining bitmaps

### Steps to Reproduce

1. Create a stacklayout with 1000 images
2. set the border
3. app crashes

I realize this is an extreme case but the memory still shouldn't bloat just because we're setting the border. We've already done a number of fixes so you can create 1000 versions of the same image so setting the border on those shouldn't cause it to crash

### Expected Behavior
Adding a border/background shouldn't cause memory bloat

### Actual Behavior
Adding a border/background causes memory bloat

### Basic Information

- Version with issue: 3.4
- Last known good version: None
- Platform Target Frameworks: 
  - Android: 8.1

**Comment by mattleibow** [comment]
This probably can be addressed in: https://github.com/xamarin/Xamarin.Forms/pull/3251

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
