### ISSUE TITLE
[Android] Picker list shows up, when focus is set on other controls. 

### ISSUE THREAD

**Issue by tmt242001** [xamarin/Xamarin.Forms#4187]
### Description

Android issue. 
Xamarin.Form 3.3.0.912540 issue. Works ok in 3.2.0.871581

When setting the focus on some other control, picker list shows up. when picker and other controls are inside ListVew.DataTemplate.ViewCell.
[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/2508026/App2.zip)

### Steps to Reproduce

1. Run the attached sample solution
2. Select a value from Picker
3. It works correctly
4. Set focus on Entry
5. The picker list shows up
6. That is incorrect 

### Expected Behavior

when setting the focus on the entry, picker list should not show up.

### Actual Behavior

when setting the focus on the entry, picker list shows up.

### Basic Information

- Versions with issue: Xamarin.Form 3.3.0.912540, 3.3.0.967583, 3.4.0.1008975
- Last known good version: Xamarin.Form 3.2.0.871581
- IDE: 15.8.7
- Platform Target Frameworks: 
  - Android: 9 

### Sample

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/2508028/App2.zip)

**Comment by nbevans** [comment]
Same issue as this https://github.com/xamarin/Xamarin.Forms/issues/4260

**Comment by nbevans** [comment]
https://github.com/xamarin/Xamarin.Forms/commit/cceee9ded6c8cadb19eb547f72d03c6c14230058#diff-a8dc9a010c576f0d2924c24ea2e54596R103

This most recent commit to PickerRenderer.cs looks highly suspect to me.

**Comment by nbevans** [comment]
I have developed a workaround for those in desperate need. Rather simple, turn off the `Control.Focusable` on the `PickerRenderer` which prevents that internal `OnNativeFocusChanged` from being superfluously invoked.

I've tested this rudimentarily and cannot find any impacts, though I'm sure it reverses the TabStop improvements that the aforementioned commit was meant to bring.

```
public class HackFix20181030PickerRenderer : PickerRenderer {
    public HackFix20181030PickerRenderer(DroidContext context) : base (context) { }

    protected override void OnElementChanged(ElementChangedEventArgs<Picker> e) {
        base.OnElementChanged(e);
        
        if (Control != null) {
            Control.Focusable = false;
        }
    }
}
```

**Comment by MikaTas** [comment]
I was about to post here and issue about this aswell as I was facing a similar issue after updating from 3.2.. to 3.3.0.912540.

But, I can confirm that using the workaround Control.Focusable = false; in the customrendered as mentioned solved the acute problem.

**Comment by nbevans** [comment]
Glad it was of help to you 👍

**Comment by mikecamimo** [comment]
Not sure if this is in any way related, but we put an arrow image to the right of our pickers to give more of a visual representation to the user that it is a picker list. The image has a tap gesture to trigger the picker, where we call picker.Focus() to bring up the picker. 
Prior to 3.3 this worked fine. In 3.3, on android at least it seems now that the picker fires twice, resulting in the user has to select their option twice.

**Comment by tmt242001** [comment]
Issue still exist in 3.3.0.967583

**Comment by AtosNicoS** [comment]
I just noticed another bug, I am not sure if this is related. Android only:

If Option A is selected and I select B and then scrol down, so that the entry is out of focus, the option gets resetted to A. Do you also see this problem?

**Comment by zezelazo** [comment]
> I just noticed another bug, I am not sure if this is related. Android only:
> 
> If Option A is selected and I select B and then scrol down, so that the entry is out of focus, the option gets resetted to A. Do you also see this problem?

Try changing the CachingStrategy of the ListView to "RetainElement"

**Comment by AtosNicoS** [comment]
Yes that worked. I also opened the issue here and got a different suggestion as well: https://github.com/xamarin/Xamarin.Forms/issues/4390

**Comment by tmt242001** [comment]
Issue still exist in 3.4.0.1008975

**Comment by valdetero** [comment]
@rmarinho Will this be in the next 3.4.x release? I just put in some nasty hacks to get around this in 3.4.0.1008975.

**Comment by rmarinho** [comment]
@valdetero yes

**Comment by DennisWelu** [comment]
Thanks all. FWIW this "fixed" the reported issue which was also happening in my app. But with 3.4.1009999 I found that the on screen keyboard input was now messed up. I'm not sure if its related to this fix or if its something new in the release. Just a heads up. For me, I'm using a SearchBar instead of an Entry, it might accept a few characters but then it freezes up, and in fact the keyboard hangs around even after the app was killed.

**Comment by baneageorge** [comment]
@kellyelton Hi Kelly, your fix worked like a charm thank you so much! Now a new one came out... with the entry fields, the keyboard pops out in weird situations. Is there a way to do something similar?

**Comment by kellyelton** [comment]
@baneageorge I would ask @nbevans , I just copied thier solution and made it easier to copy/paste.
