### ISSUE TITLE
VS project goes broken after upgrade update package to  latest preview.

### ISSUE THREAD

**Issue by anirudhagupta** [xamarin/Xamarin.Forms#4196]
create a xamarin.forms project in VS 15.9.4 Preview and select only android.

upgrade all the package to latest preview and it doesn't work anymore. tested in today's releases (preview).

![image](https://user-images.githubusercontent.com/35772421/47428581-54ff4980-d7b1-11e8-9088-d7b5e174ed5a.png)

**Comment by StephaneDelcroix** [comment]
please attach your broken project.

**Comment by anirudhagupta** [comment]
I reproduce it now on a different machine, yesterday it was preview 3 and now it's preview 4. it's giving a different kind of error. 
please look
https://github.com/anirudhagupta/Testing.Forms

**Comment by PureWeen** [comment]
@anirudhagupta what error are you getting?
