### ISSUE TITLE
Custom cornerRadius hidden by Xamarin forms cornerRadius

### ISSUE THREAD

**Issue by RenaudAvenas** [xamarin/Xamarin.Forms#4198]
### Description
Custom cornerRadius hidden by Xamarin forms cornerRadius

### Steps to Reproduce

1. Create a class named CornerRadius with "Bob" property
2. Use this type to declare a BindableProperty in a custom control
3. Use this property in a .XAML and set the Bob property

### Expected Behavior
The project build correctly and application use the good CornerRadius class and apply "Bob" property

### Actual Behavior
The build failed => The compilation indicate that "Bob" property does not exists

### Basic Information

- Version with issue: 3.3.X
- Last known good version: 3.2.X
- IDE: Visual Studio 2017 Pro 15.8.6
- Platform Target Frameworks: 
  - Android: 7.1

**Comment by StephaneDelcroix** [comment]
please provide a test project. Thanks

**Comment by PureWeen** [comment]
Closing for now. @RenaudAvenas if you can provide a test project then we can reopen.
