### ISSUE TITLE
Supply actual build version for all Xamarin.Forms* assemblies

### ISSUE THREAD

**Issue by mpreyskurantov** [xamarin/Xamarin.Forms#4203]
We are developing a crash reporting library for Xamarin.Forms and Xamarin platform-specific apps, and one of the main essential pieces of info we want to capture is the used Xamarin.Forms (Xamarin.Forms.Core) and Xamarin.Forms.Platform versions, which may affect the application functionality. While the related packages have the actual version information (for example, "3.3.0.912540"), the corresponding assemblies are always built with the same build version:

Xamarin.Forms.Core 2.0.0.0
Xamarin.Forms.Platform 1.0.0.0
Xamarin.Forms.Platform.iOS 2.0.0.0
etc.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Properties/AssemblyInfo.cs#L7-L8

For this task, it would be useful if you supply the actual build version for all Xamarin.Forms* assemblies inside the corresponding packages.
Let us know if there are any alternative recommended ways to retrieve this info, for example, at runtime in code, especially in the platform-specific (Android, iOS, etc.) project. In addition, let us know if we can elaborate on this inquiry and describe a partial point in greater detail.

**Comment by StephaneDelcroix** [comment]
we can not bump the `AssemblyVersion`, but we could bump the AssemblyFileVersion. We already have the mechanism in place for generating them, but we need to fix our build chain to follow them.

**Comment by mpreyskurantov** [comment]
I believe that it would be fine as a starting point. If possible, let me know when a package with this functionality is available, so that I can test it and provide feedback. Thank you for the quick response.

**Comment by samhouts** [comment]
closed by #6068
