### ISSUE TITLE
[XAML] All objects added to an IDictionary must have a Key attribute

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4210]
### Description

Every now and then, I see a compiler error reporting on a lack of key in user-defined XAML styles. This issue happens rarely when I open XAML files in VS 15.8.7.

> Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0515	All objects added to an IDictionary must have a Key attribute or some other type of key associated with them.	TestApp	Test.xaml	12	

### Screenshots

![1](https://user-images.githubusercontent.com/16855542/47474694-c48b2e00-d7dd-11e8-9ae3-391bc4fd55f5.PNG)

![2](https://user-images.githubusercontent.com/16855542/47474768-2e0b3c80-d7de-11e8-9967-1549231376af.PNG)

If this error should be thrown, why isn't it thrown consistently on every view that lacks style keys? If it should not be thrown, why is it being thrown occasionally?

**Comment by AbdAlghaniAlbiek** [comment]
you need to add x:key for style

**Comment by samhouts** [comment]
I'm going to close this for now. If this happens again, please open an issue via Visual Studio Feedback. Thanks!

**Comment by NogginBox** [comment]
This happened to me when the build action for the XAML file was wrong. I checked it against a working XAML file and made them match. This was in .NET MAUI, but it might be the same issue.
