### ISSUE TITLE
BindigContex of ItemTemplates in ListView is the Parent (not the ItemsSource)

### ISSUE THREAD

**Issue by elybarak** [xamarin/Xamarin.Forms#4211]
### Description
BindingContext for the DataTemplate assigned to ItemTemplate isn't the ItemsSourece items, but BindingContext of the ListView itself.
### Steps to Reproduce

1. Create a class 'Person' for ex., and a property "IEnumerable<long> Phones"
2. Create a ListView with BindingContext = new Person() and ItemsSource = {Binding Phones}.
3. Add a ItemTemplate `<TextCell Text={Binding .}/>`.
99. you see, the binding show the Person, not the phone. BindingContext is 'Person' instead of long (Phone).

### Expected Behavior
BindingContext should to be a item of ItemsSource.

### Actual Behavior
BindingContext is the BindingContex of he ListView istelf.

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: ? 
- IDE: Visual Studio 2017
- Platform Target Frameworks: .Net Standard 2.0
  - iOS:  none
  - Android: 8.0
  - UWP:  1803
- Android Support Library Version: none
- Nuget Packages: Xamarin.Forms
- Affected Devices: all

**Comment by StephaneDelcroix** [comment]
this looks very strange.

could you please attach a very simple project to this report, so we can investigate ?

thanks a lot

**Comment by elybarak** [comment]
I'm sorry, the problem occurs only when using a IEnumerable as item. (in my case BsonDocument of LiteDB)

**Comment by StephaneDelcroix** [comment]
please provide a simple project reproducing the issue

**Comment by elybarak** [comment]
maybe its only by BsonDocument...
[Here](https://github.com/elybarak/ListViewBug) is a example.

**Comment by StephaneDelcroix** [comment]
Your project doesn't run for me, I got an AmbiguousMatchException while trying to resolve the Binding. 

I will investigate this separately (and wonder how you got that working).

What do you get (visually) while running this project ?

**Comment by elybarak** [comment]
i run it on UWP and there is no Exception.
Visually i see, well, nothing. the binding is not working because the binding context is not the correct item, so nothing is showing:
![image](https://user-images.githubusercontent.com/35643344/47505080-17182900-d876-11e8-9d49-3287b8158dbb.png)

**Comment by StephaneDelcroix** [comment]
With the fix of #4215, I get

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/313003/47555225-8f7cf980-d90b-11e8-8797-1c1cf346a863.png">

And that looks fine to me.

I'm still confused by your original comment
> 4. you see, the binding show the Person, not the phone. BindingContext is 'Person' instead of long (Phone).

vs your last comment:
> Visually i see, well, nothing. the binding is not working because

I don't know what to do with this, so I'm closing the ticket. If you can come up with a repro triggering the original report, reopen it. And I think #4215 fixes the blank screen.

**Comment by elybarak** [comment]
it's probably #4215, but  in UWP, instead of AmbiguousMatchException is the binding not the currect object. how do you fix it? i have to use BsonDocument and it have implicit casting.
