### ISSUE TITLE
Xamarin.Forms ListView ItemTapped cannot be excuted on iOS 11.4

### ISSUE THREAD

**Issue by yinchengvy** [xamarin/Xamarin.Forms#4213]
### Description
When I updated Xamarin.Forms from 3.2.0.839982  to 3.2.0.871581.
I found all ListView's ItemTapped are failed on iOS 11.4.

Xamarin.Forms :  3.2.0.871581
iOS SDK: 11.4

---- 

And I test Xamarin.Forms(3.2.0.871581) on iOS 12.0, It's OK.
Also I update Xamarin.Forms to 3.3.0, and failed always on iOS 11.4.

Please fix this issue, Thx.

**Comment by samhouts** [comment]
@yinchengvy  Can you please attach a small reproduction project that exhibits the issue? Thanks!

**Comment by PureWeen** [comment]
Closing for now. If you can provide a test project then we can reopen.
