### ISSUE TITLE
[Android] Entry ReturnType=Next not passing to next text field

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#4214]
### Description

When using `ReturnType`=Next on an `Entry` on Android, the button on the keyboard changes but going from one text field the next doesn't work.

### Steps to Reproduce

    <StackLayout Orientation="Vertical">
      <Entry Keyboard="Default" Placeholder="First name" ReturnType="Next" />
      <Entry Keyboard="Default" Placeholder="Last name" ReturnType="Next" />
      <Entry Keyboard="Default" Placeholder="Address" ReturnType="Next" />
      <Entry Keyboard="Text" Placeholder="City" ReturnType="Next" />

There is a common workaround people use: a `Completed` event of the `Entry` can call the next one:

    private void AddressField_Completed(object sender, EventArgs e) => CityField.Focus();

However, this has the problem that the keyboard closes momentarily and opens again immediately.

### Expected Behavior

Should both send the focus to the next text field and not dismiss the keyboard momentarily.

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: n/a
- Platform Target Frameworks:
  - Android: 8.1, API 27
- Android Support Library Version: 27.0.2.1

**Comment by deakjahn** [comment]
It wasn't intended as a proposal at all. :-) It's a workaround people tend to use (judging by SO and Xamarin Forum answers) but has its problems. If there is a proposal, it's to fix the bug to function as the documentation promises.

**Comment by pauldipietro** [comment]
Validating the described behavior against 3.4 for the time being.

**Comment by ashwinkumar6** [comment]
An alternative solution for the time being would be to use a custom effect as mentioned [here](https://iwritecodesometimes.net/2018/06/25/building-a-next-entry-effect-for-ios-and-android-in-xamarin-forms/)

**Comment by samhouts** [comment]
closed by #6706
