### ISSUE TITLE
Trying to install app on LgK7 (X210) doesn't work.

### ISSUE THREAD

**Issue by TimVanDenEnden** [xamarin/Xamarin.Forms#4217]
Hi I am trying to install my app on an android device (real) and it says installing but it not showing up on the phone at all.

**Comment by VladislavAntonyuk** [comment]
make sure you set main launcher attribute on your main activity

**Comment by TimVanDenEnden** [comment]
My app is crossplatform not only android is it still relevent that link then?

**Comment by VladislavAntonyuk** [comment]
Yes

**Comment by StephaneDelcroix** [comment]
Thanks for this report. Unfortunately, this is not the right place to seek assistance. Try the forums, or stackoverflow.

if you're 100% certain your setup is correct, and that is a bug, please report the bug to the xamarin android team : https://github.com/xamarin/xamarin-android/issues/new
