### ISSUE TITLE
Place holder text of TextBox is not properly aligned when TextBox height is assigned in Xamarin Forms UWP

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#4230]
### Description

Place holder text of TextBox is not properly aligned when TextBox height is assigned and added as custom renderer for Custom layout in Xamarin Forms UWP project. With default height of TextBox place holder text is aligned properly at the beginning, when I assign TextBox height as 40, place holder text is aligned at end. So, cursor and place holder text is overlapping. How can i arrange the position of the place holder text to overcome this issue? Kindly refer the attached image and sample below.

### Screenshot 
**Image**
![Image](https://i.postimg.cc/nhBzpkDb/Custom-Renderer-1.png)

**Sample:** 
[CustomRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2520079/CustomRenderer.zip)

**Note:**
In above sample, TexBox used as custom renderer for custom layout is renderer of the Editor. We are also facing issue when renderer of Entry is used as TextBox. 

Regards,
Ganeshamoorthy C

**Comment by pauldipietro** [comment]
This shouldn't be an issue on the latest stable release. Please report back with an updated reproduction if otherwise. The reproduction appeared to be running 2.4; creating a new project and using the custom renderer in the reproduction works as normal with things in line.
