### ISSUE TITLE
[Android] Padding on button on android don't work if less than 20

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/Xamarin.Forms#4249]
### Description
If we set a padding less than 20, the requested padding is ignored.

### Steps to Reproduce
1. Set a button 
2. Set a padding < 20

### Expected Behavior
The button have the requested padding

### Actual Behavior
We have a button with a default padding

### Basic Information

- Version with issue: 3.2.0.871581
- IDE:
- Platform Target Frameworks: 
  - Android: Android 8.1 
- Android Support Library Version:  27.0.2.1

### More information

If we set a padding of 5(Left, Top, Right, Bottom) and an HeightRequest of 25 and a MinimumWidthRequest of 0, we will have a button with no padding on Top and Button. And with a default padding (>5) on Left and Right

For our project, we already haved our own ButtonExtended with a CustomPadding propertie, for what i've seen on your ButtonRenderer, we have mostly the same implementation, the only difference is that we set 4 more native element on the Android.Widget.Button : SetMinWidth, SetMinHeight, SetMinimumWidth, SetMinimumHeight.

And if we use our implementation with only setting the 4 native element and your implementation (Padding) it's works with a padding < 20.

So it's maybe only you don't set this properties.

**Comment by pauldipietro** [comment]
I don't seem able to reproduce this. Can you attach a reproduction when you get a chance? Does the issue still occur on 3.3 with a full clean and rebuild?

**Comment by samhouts** [comment]
@quentinR0bert Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
