### ISSUE TITLE
iOS Accessibility VoiceOver does not stop on Header element when using the Heading Rotor setting if element is ListView Header.

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#4252]
### Description

Not easy to describe, so bear with me. There is an iOS Accessibility feature called VoiceOver which has a [Rotor control](http://www.afb.org/info/living-with-vision-loss/using-technology/cell-phones-tablets-and-other-mobile-technology-for-users-with-visual-impairments/apple-ios-for-iphone-and-ipad-considerations-for-users-with-visual-impairments-and-blindness/the-voiceover-rotor/12345). 

If the Rotor control is set to "Headings" then flicking up or down with one finger should navigate between all of the visual elements that have the UIKit.UIAccessibilityTrait.Header flag set.

In the attached test project, there is one page with a ListView. You will see three headings, one is the page Title (set as a heading automatically), the second is a Label outside of the list view which uses an Effect to set the UIKit.UIAccessibilityTrait.Header flag, and the third is a Label in the Header of the ListView which also uses an Effect to set the UIKit.UIAccessibilityTrait.Header flag. 

The issue is that when flicking down to go to the next Heading, the third heading, the one that is the ListView.Header, is not found, but it is found when flicking up (after tapping on a list item to set the cursor below the 3rd heading). 

### Steps to Reproduce

1. Load the attached test project.
2. Deploy to an iOS device (VoiceOver feature is not easily used on simulator)
3. On iOS device, open Settings app and go to **General > Accessibility > VoiceOver** and turn on the VoiceOver feature. You will now have to tap an item once to select it and then double tap the item to execute it.
4. Go back to the TestVoiceOverHeading App and flick down with one finger to scroll through the headings.

### Expected Behavior
Headings 1, 2, and 3 should all be stopped on and their titles read aloud by VoiceOver.

### Actual Behavior
Headings 1 and 2 only are stopped on and titles read aloud by VoiceOver.

5. Now tap on any item in the list view and flick up.

### Expected Behavior
Headings 3, 2, and 1 should all be stopped on and their titles read aloud by VoiceOver.

### Actual Behavior
As expected.

### Notes

So the above steps to reproduce should demonstrate that VoiceOver with the Headings rotor control finds the elements that have UIKit.UIAccessibilityTrait.Header flag set except if the element is set as the ListView.Header in which case the element is only found when flicking up to go to previous headers. 

It is also worth noting that if I had a grouped list, and set the ListView group headers to use the UIKit.UIAccessibilityTrait.Header flag, these group headers will be recognized by VoiceOver heading Rotor control regardless of the direction of flick, i.e. works as expected. Issue seems to only occur for elements in the ListView.Header or ListView.HeaderTemplate element. 

### Workaround

I am able to workaround this issue by using a [custom ListView renderer ](https://developer.xamarin.com/samples/xamarin-forms/CustomRenderers/ListView/)and overriding the GetViewForHeader method and returning a UILabel with the UIAccessibilityTrait.Header set.

### Basic Information

- Version with issue: 3.1.0 and 3.3.0
- Last known good version: Unknown
- IDE: VS for Mac
- Platform Target Frameworks:
  - iOS:  12
- Affected Devices: iPhone (Issue does not seem to occur on iPad)

### Reproduction Link

[TestVoiceOverHeading.zip](https://github.com/xamarin/Xamarin.Forms/files/2526922/TestVoiceOverHeading.zip)

**Comment by pauldipietro** [comment]
I think I see the behavior being described. Correct me if I'm wrong, but selecting the header 1 and dragging your thumb down while held (not so much a "flick" as that reads individual letters off) skips to the item 5, at least for me on an iPhone X, while going back up goes through the previous items/headers. It seems like it's not working correctly, at any rate.

**Comment by jgold6** [comment]
You need to set the Rotor control to "Headings". To do this, use a two-finger rotate gesture on the screen until you hear "Headings" (and see it on the rotor control). Once this rotor control  is set, you just FLICK up or down with one finger, not SWIPE. when FLICKING up or down, the selection cursor should move between ONLY the headings. See the [article I linked on the Rotor control ](http://www.afb.org/info/living-with-vision-loss/using-technology/cell-phones-tablets-and-other-mobile-technology-for-users-with-visual-impairments/apple-ios-for-iphone-and-ipad-considerations-for-users-with-visual-impairments-and-blindness/the-voiceover-rotor/12345) for more info.

**Comment by pauldipietro** [comment]
That does it, yes.

**Comment by jfversluis** [comment]
This is way old and a lot has improved for accessibility both in Forms and even more in .NET MAUI. Hopefully this is resolved by now, if not please report this on .NET MAUI so we can zoom in on this again. Thanks!
