### ISSUE TITLE
Button Size changed when updated from version Xamarin.forms 3.1 to Xamarin.forms 3.3 with FormsApplicationActivity

### ISSUE THREAD

**Issue by truecaller12** [xamarin/Xamarin.Forms#4258]
### Steps to Reproduce

1. with xamarin.forms 2.5 defined a button 
2. update xamarin.forms to 3.3, buttons changes in height.
i have the following styling (same with 2.5 and 3.3)

```xaml
 <?xml version="1.0" encoding="utf-8" ?>
        <selector xmlns:android="http://schemas.android.com/apk/res/android" >
        <item android:state_pressed="true" >
         <shape android:shape="rectangle"  android:padding="10dp">  
             <corners android:radius="3dp"/>
             <solid   android:color="#96BD0D"/>
             <stroke android:width="1dip" android:color="#96BD0D" />        
         </shape>
        </item>
        <item android:state_focused="true">
         <shape android:shape="rectangle"  android:padding="10dp">
             <corners android:radius="3dp"/>
             <stroke android:width="1dip" android:color="#96BD0D" />
             <solid android:color="#96BD0D"/>       
         </shape>
        </item>  
        <item >
        <shape android:shape="rectangle"  android:padding="10dp">
             <corners android:radius="3dp"/>
              <solid   android:color="#829293"/>
             <stroke android:width="1dip" android:color="#829293" />
         </shape>
        </item>
        </selector>

 <style name="CKButton" parent="@android:style/Widget.Button">
    <item name="android:background">@drawable/mybutton</item>
    <item name="android:textColor">#000000</item>
    <item name="android:padding">10dp</item>
  </style>

```

![752fd82c-8490-4194-928c-b8fae2f6bede](https://user-images.githubusercontent.com/44604556/47711407-70e17000-dc35-11e8-8bf8-7f07ba8cb7a1.png)

### Expected Behavior
THe button should retain their property
### Actual Behavior
The height property seems to change
### Basic Information

- Version with issue:
- Last known good version: xamarin.forms 2.5
- IDE: visual studio 2017 15.8.5
- Platform Target Frameworks: 
  - Android:  8.1 
- Affected Devices:

**Comment by truecaller12** [comment]
What is see while creating the sample projetc is...with xamarin.forms 3.1  verison the button height was retained but as soon as i updated to xamarin.forms 3.3 , the button height was changed .





[SampleButton.zip](https://github.com/xamarin/Xamarin.Forms/files/2533335/SampleButton.zip)

**Comment by truecaller12** [comment]
Any update on this?

**Comment by samhouts** [comment]
Please see https://github.com/xamarin/Xamarin.Forms/pull/1935#issuecomment-375728802. Does changing these properties help you? Thanks@

**Comment by samhouts** [comment]
@truecaller12  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
