### ISSUE TITLE
The "IsEnabled = false" state of the controls doesn't retain its state on page navigation in Xamarin.Forms.WPF

### ISSUE THREAD

**Issue by chandanhs464** [xamarin/Xamarin.Forms#4259]
### Description
I have two pages 
1- MainPage 
2- NextPage

I've added three controls in the NextPage and set IsEnabled = False for all three controls.
I'm navigating from MainPage to NextPage by Navigation.PushModalAsync(nextPage)
The first time I enter to NextPage all three controls are disabled.
But When I navigate back and re-enter to the NextPage the controls are enabled in the UI.

### Example Code
**MainPage.xaml.cs**
```
public partial class MainPage : ContentPage
{ 
    NextPage nextPage;
        public MainPage()
        {
            nextPage = new NextPage();
            InitializeComponent();
        }
        private void Button_Clicked(object sender, EventArgs e)
        {
            Navigation.PushModalAsync(nextPage);
        }
}
```
**MainPage.xaml**
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XFWPF"
             x:Class="XFWPF.MainPage" x:Name="MyPage">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Button Grid.Row="0" Text="Click" Clicked="Button_Clicked"/>
    </Grid>
</ContentPage>

```
**NextPage.xaml.cs**
```
public partial class NextPage : ContentPage``
{
    public NextPage ()
    {    
        InitializeComponent ();
            DisableControls();
    }
        public void DisableControls()
        {
            mySwitch.IsEnabled = false;
            myPicker.IsEnabled = false;
            myButton.IsEnabled = false;
        }
}
```
**NextPage.xaml**
```
            <?xml version="1.0" encoding="utf-8" ?>
            <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                         xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                         x:Class="XFWPF.NextPage">
                <ContentPage.Content>
                    <StackLayout>
                        <Label Text="Welcome to Xamarin.Forms!"
                            VerticalOptions="CenterAndExpand" 
                            HorizontalOptions="CenterAndExpand" />
                        <Switch x:Name="mySwitch"/>
                        <Picker x:Name="myPicker"/>
                        <Button Text="Press here" x:Name="myButton"/>
                    </StackLayout>
                </ContentPage.Content>
            </ContentPage>

```
### Expected Behavior
The state of the controls should be disabled even after navigating on and off multiple times from the page.

### Actual Behavior
The state of the controls are enabled in the UI.

- Version with issue: Xamarin.Forms.Platform.WPF v3.3.0.912540
- IDE: Microsoft Visual Studio Professional 2017

### Screenshots
Step 1:
![capture](https://user-images.githubusercontent.com/41326575/47713809-2b3a9c80-dc61-11e8-98fa-266efbd1ace5.PNG)

Step 2:
![capture1](https://user-images.githubusercontent.com/41326575/47713832-3c83a900-dc61-11e8-84cb-cd6a318d0113.PNG)

Step 3:
![capture2](https://user-images.githubusercontent.com/41326575/47713915-676dfd00-dc61-11e8-8ad3-371e7c1cb962.PNG)

Step 4:
![capture3](https://user-images.githubusercontent.com/41326575/47713930-705ece80-dc61-11e8-851a-b816cb229918.PNG)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
