### ISSUE TITLE
Picker inside a Listview triggered randomly on Android

### ISSUE THREAD

**Issue by AtosNicoS** [xamarin/Xamarin.Forms#4260]
### Description
I have got a Listview with a `Picker` and `Entry` controls inside `CellView`s. If I click one of the `Picker` elements and then enter the `Entry` keyboard menu, the `Picker` Selection Selection menu pops up again. If I type a single character, the popup appears again. If I close the menu, it pops up as well.

I broke down the issue, to a more simple version, with much of my binding eliminated, so the problem is very unlikely in my code. It does not matter if the picker has an item source or not. This does not happen with `UWP`, because they use a drop down instead of a popup. I did not test on IOS.

I have tested this on an emulator, no real android device!

### Steps to Reproduce

1. Create a List View
2. Add a Datatemplate with a picker and an entry
3. Start the App
4. Click the picker
5. Enter the text field
6. The Picker randomly appear.

### Expected Behavior
No Popup is displayed

### Actual Behavior
The popup randomly opens

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: None, new issue for me.
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 8.1 API 27
  - UWP:  16299
- Android Support Library Version: API27
- Nuget Packages: I've added Grpc, should not be the problem here.
- Affected Devices: Android

### Screenshot
![grafik](https://user-images.githubusercontent.com/37442184/47720366-05f06300-dc4e-11e8-9729-12eeca2bc500.png)

### Reproduction Link

This is a minimal version of my xaml, it makes the bug appear.
```xml
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Amc.Views.ScopePage"
             Title="{Binding Title}">
    <ListView
        x:Name="ConfigurationsListView"
        ItemsSource="{Binding TestData}" 
        HasUnevenRows="true">
        <ListView.ItemTemplate>
            <DataTemplate>
                <ViewCell>
                    <StackLayout>
                        <Picker Title="Test1"></Picker>
                        <Entry Text="Test2"></Entry>
                    </StackLayout>
                </ViewCell>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</ContentPage>
```

**Comment by nbevans** [comment]
We are getting this too. Both real and emulated devices.

We were on the latest 3.4 pre but I am now going back through the versions to find a release where this doesn't happen.

**Comment by pauldipietro** [comment]
Closing as duplicate
