### ISSUE TITLE
Label HorizontalTextAlignment="Center" not working in conjunction with LineHeight on iOS 

### ISSUE THREAD

**Issue by HenrikPihl** [xamarin/Xamarin.Forms#4262]
### Description

HorizontalTextAlignment="Center" has no effect if LineHeight is assigned a value

### Steps to Reproduce

1. Create 2 labels 
2.
``` <Label HorizontalTextAlignment="Center" Text="This is center aligned&#x0a;line 2" />```
```<Label HorizontalTextAlignment="Center" LineHeight="1.5"  Text="This should be center aligned&#x0a;line 2"  />```
 

### Expected Behavior
Both labels center aligned
### Actual Behavior
On Android both labels are center aligned
On iOS only the first label is center aligned
### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: N/A issue found when migrating from custom renderer
- IDE: VS on Mac
- Platform Target Frameworks: 
  - iOS:   11.1
  - Android:  7.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
Tested on iOS against 3.4 as well where this behavior occurs
