### ISSUE TITLE
regarding Remote Simulator to Windows issue

### ISSUE THREAD

**Issue by patesuj** [xamarin/Xamarin.Forms#4271]
### Steps to Reproduce
Hello,
When I run my Xamarin iOS test via Visual Studio 2017, I got the following message: “iOS tests are not supported on Windows”. I have set up Remote Simulator to Windows option so it should open simulator but it didn't happen so please tell me what's wrong? 

According to following link, it should work.
https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/index

Here is my test configuration:
I have installed Visual Studio 2017 Enterprise Version 15.8.5 with Xamarin version 4.11.
I have created new Test Project using Xamarin.UITest Cross-Platform Test Project template.
I have also configured Mac Book using Pair to Mac option and it is connected fine.
I have checked Remote Simulator to Windows option in IOS Settings via VS Tools options in order to run my test on remote simulator.
I have following code in my Test.cs file
	    if (platform == Platform.iOS)
            {
                return ConfigureApp
                    .iOS
		    .InstalledApp("com.example.yourappbundleid")
                    .EnableLocalScreenshots()
                    .StartApp();
                    
            }
When I run the test, I got the following message: iOS tests are not supported on Windows.
As I have said earlier, I have set up Remote Simulator to Windows option so it should open simulator but it didn't happen so please tell me what's wrong? 
I knew we can't run test directly on windows machine using actual device but I should open the remote simulator.
Please suggest me the solution or any updated information you have regarding running iOS test on Remote Simulator.
Many thanks in advance.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by patesuj** [comment]
Thanks Paul for your quick reply.
I have created test in VS 2017 using Xamarin UI Test template so I want to execute that test on the remote simulator so I can verify the steps that I have included in my test. So please help me to execute that test on the remote simulator using VS 2017. I already have my Mac paired to my laptop. And I have also installed VS for Mac and XCode on my mac book.
Thanks in advance.

**Comment by pauldipietro** [comment]
You will have to use your Mac to run the UITests. 

> The Remoted iOS Simulator for Windows allows you to test your apps on an iOS simulator displayed in Windows alongside Visual Studio 2017.

The use of "test your apps" here is simply implying "to run your app" which is potentially confusing.
