### ISSUE TITLE
Xamarin.Forms Button ContentLayout property not working as expected

### ISSUE THREAD

**Issue by bverp** [xamarin/Xamarin.Forms#4272]
### Description

When setting the contentlayout property for buttons the spacing is not working when the imagelocation is set to top or bottom.

### Steps to Reproduce

```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:local="clr-namespace:Buttons" x:Class="Buttons.MainPage">
    <StackLayout Padding="50">
        <Button ContentLayout="Right,50" Text="Sometext" Image="euro.png" HeightRequest="125" BackgroundColor="Teal" WidthRequest="250" HorizontalOptions="Center" TextColor="White"/>
        <Button ContentLayout="Left,50" Text="Sometext" Image="euro.png" HeightRequest="125" BackgroundColor="Teal" WidthRequest="250" HorizontalOptions="Center" TextColor="White"/>
        <Button ContentLayout="Top,50" Text="Sometext" Image="euro.png" HeightRequest="125" BackgroundColor="Teal" WidthRequest="250" HorizontalOptions="Center" TextColor="White"/>
        <Button ContentLayout="Bottom,50" Text="Sometext" Image="euro.png" HeightRequest="125" BackgroundColor="Teal" WidthRequest="250" HorizontalOptions="Center" TextColor="White"/>
    </StackLayout>
</ContentPage>
```

### Expected Behavior

A spacing of 50 between text and images for imagelocation Top or Bottom

### Actual Behavior

Left and Right are fine but for Top or Bottom no spacing is applied

### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: ?
- IDE: Visual Studio for Mac 7.6.10
- Platform Target Frameworks: 
  - iOS:  12.0

### Screenshots

[https://i.stack.imgur.com/OWS8R.png](https://i.stack.imgur.com/OWS8R.png)

**Comment by Pantheas** [comment]
I have a Button with an image and ContentLayout set to "Right".
On Android, everything is working as excepted and the image is placed at the right margin.
On iOS though, the image is placed on the right side of the font, but directly after it. No matter what spacing I provide, the image's position does not change.
I would expect the same behavior for iOS as it is for Android.

**Comment by mattleibow** [comment]
I spotted this while working on https://github.com/xamarin/Xamarin.Forms/pull/4967. I have a fix coming in there.

**Comment by mattleibow** [comment]
I also spotted another thing - when setting the Spacing to say 20, there is also a padding of 10 (basically half) applied to the button. I am not sure if this is a bug or a feature, but do we want to reproduce this for vertical? Consistency says yes, but my heart says bug. This can be "undone" with a negative padding, and I am sure changing this is going to break everyone. It is just weird and only in the direction of the layout.

Here are some pictures 😺 

| Spacing = 0 | Spacing = 20 | Spacing = 40 |
| :-: | :-: | :-: |
| <img width="79" alt="screen shot 2019-01-13 at 03 57 54" src="https://user-images.githubusercontent.com/1096616/51080636-36418c80-16e8-11e9-8446-821e08044079.png"> | <img width="117" alt="screen shot 2019-01-13 at 03 58 11" src="https://user-images.githubusercontent.com/1096616/51080641-45c0d580-16e8-11e9-8449-69509b6f6e83.png"> | <img width="153" alt="screen shot 2019-01-13 at 03 58 25" src="https://user-images.githubusercontent.com/1096616/51080646-60934a00-16e8-11e9-9b38-b0807129c319.png"> |
| <img width="73" alt="screen shot 2019-01-13 at 03 58 59" src="https://user-images.githubusercontent.com/1096616/51080651-743eb080-16e8-11e9-9ffd-472fdab429b8.png"> | <img width="75" alt="screen shot 2019-01-13 at 03 59 12" src="https://user-images.githubusercontent.com/1096616/51080652-815b9f80-16e8-11e9-852d-e092d2237ff4.png"> | <img width="74" alt="screen shot 2019-01-13 at 03 59 28" src="https://user-images.githubusercontent.com/1096616/51080653-86205380-16e8-11e9-9cbd-e04d6d151b84.png"> |

**Comment by mattleibow** [comment]
This is fixed in https://github.com/xamarin/Xamarin.Forms/pull/4967
