### ISSUE TITLE
[macOS] Transform / Rotate / Scale don't work on Frame

### ISSUE THREAD

**Issue by programmation** [xamarin/Xamarin.Forms#4277]
### Description

Please see the repro project for details. The project has one page where a `Frame` has `Rotate`, `RotateX`, `RotateY`, `TransformX`, and `TransformY` applied to it. All the modifications work on iOS and Android but have no effect on MacOS. Not tested on other platforms.

### Steps to Reproduce

1. Run the repro project in MacOS.

### Expected Behavior

Frame should be skewed and rotated.

### Actual Behavior

Frame is neither skewed nor rotated.

### Basic Information

- Version with issue: XF 3.3
- Last known good version: N/A (don't think it ever worked)
- IDE: VS Mac
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

### Screenshots

iOS (Working)

![simulator screen shot - ipad 5th generation - 2018-11-01 at 18 44 19](https://user-images.githubusercontent.com/10096185/47839329-83f76a00-de06-11e8-973f-1bc60d546018.png)

Android (Working)

![screenshot_1541058560](https://user-images.githubusercontent.com/10096185/47839491-0849ed00-de07-11e8-9348-8e8ce7ae3bae.png)

MacOS (Not working)

![screen shot 2018-11-01 at 18 51 47](https://user-images.githubusercontent.com/10096185/47839565-41825d00-de07-11e8-8804-e2b848e6e1a2.png)

### Reproduction Link

[FrameRotationTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2537638/FrameRotationTest.zip)

**Comment by SeRgI1982** [comment]
For those one who needs quick workarround (far from ideal but works), take a look here [#7815](https://github.com/xamarin/Xamarin.Forms/pull/7815#issuecomment-546246568)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
