### ISSUE TITLE
New attribute ItemPickingDisplayBinding for Picker

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#4279]
##Summary

For usability reasons sometimes more text needs to get displayed during the picking process.
On the page there is only space for the short text.

##API Changes

New bindable attribute ItemPickingDisplayBinding (see ItemDisplayBinding)

##Intended Use Case
displaying of the initals of a person on the page, but the name during the picking

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
