### ISSUE TITLE
Swipe left/right gesture

### ISSUE THREAD

**Issue by ddobrev** [xamarin/Xamarin.Forms#4281]
Really? 2018 is the 5th, FIFTH, year of Xamarin.Forms and you still don't support basic gestures? What the hell has been going on all these years? How much time does it take to get your act together? It's open source but you all are PAID to write this open source. When are you going to actually do it and stop wasting people's time finding various third parties which all don't work, just in a different manner?

**Comment by pauldipietro** [comment]
#2727 might be of interest to you.

**Comment by ddobrev** [comment]
@pauldipietro when are you releasing it?

**Comment by ddobrev** [comment]
@pauldipietro SwipeGestureRecognizer doesn't work for cells in a list view.
