### ISSUE TITLE
ListView selection done programatically is not reflected in UI Xamarin.Forms.WPF 

### ISSUE THREAD

**Issue by chandanhs464** [xamarin/Xamarin.Forms#4284]
### Description
ListView selection done programatically is not reflected in UI Xamarin.Forms.WPF 
i.e, ListView.SelectedItem

### Example Code

**MainPage.xaml**
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XFWPF"
             x:Class="XFWPF.MainPage">

    <StackLayout>
        <Label Text="My List View" 
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" />
        <ListView x:Name="myList"/>
        <Button Text="Click Here!" x:Name="myButton" Clicked="myButton_Clicked"/>
    </StackLayout>
</ContentPage>
```

**MainPage.xaml.cs**
```
public partial class MainPage : ContentPage
{
    ObservableCollection<string> numList = new ObservableCollection<string> 
    {
        "One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten"
    };

    public MainPage()
    {
        InitializeComponent();
        myList.ItemsSource = numList;
    }

    private void myButton_Clicked(object sender, EventArgs e)
    {
        myList.SelectedItem = numList[4];
    }
}
```

### Expected Behavior
List view item should be selected
![capture2](https://user-images.githubusercontent.com/41326575/47904177-c3779200-deaa-11e8-9091-ce739752f5e5.PNG)

### Actual Behavior
List view item is not highlighted or selected
![capture1](https://user-images.githubusercontent.com/41326575/47904199-cf635400-deaa-11e8-98e4-bd3c3f21a76d.PNG)

### Basic Information

- Version with issue: v3.3.0.967583
- IDE: Microsoft Visual Studio Professional 2017

**Comment by BillKlinton79** [comment]
I think i have the same issue here. Did you found any solution?

**Comment by chandanhs464** [comment]
@BillKlinton79 I haven't found anything yet. :(

**Comment by BillKlinton79** [comment]
@chandanhs464 , Thanks man!

**Comment by krdmllr** [comment]
I tried to reproduce it in the current branch 4.3.0 but everything worked as designed.
@samhouts @mohachouch should I open a PR with the added issue to the XF Controls Gallery?
You can find the sample here https://github.com/krdmllr/Xamarin.Forms/blob/issue-4284/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4284.xaml
https://github.com/krdmllr/Xamarin.Forms/blob/issue-4284/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue4284.xaml.cs

**Comment by jfversluis** [comment]
As indicated by @krdmllr this seems to work with the current version. If you find that this is not the case. Please open another issue or feel free to reopen this one. Thanks!
