### ISSUE TITLE
[iOS] Layout error in Toolbar

### ISSUE THREAD

**Issue by tobiasqfs** [xamarin/Xamarin.Forms#4285]
### Description
The Toolbar Options show weird behavior on first start. Once you
### Steps to Reproduce

1. Check out: https://github.com/tobiasqfs/carconfig.git
2. Open Project
3. Start iOS Version
4. Click on second TabBar item to refresh toolbar options

### Expected Behavior
The text of the Toolbar items should be inside the borders. 
### Actual Behavior
The text of the Toolbar items is overlaying.
### Basic Information

Code can be found here:
https://github.com/tobiasqfs/carconfig/blob/master/CarConfigurator/CarConfigurator/de/qfs/model/ui/ToolbarManager.cs

### Screenshots
![simulator screen shot - iphone xs max - 2018-11-02 at 14 30 37](https://user-images.githubusercontent.com/35342983/47918199-1aca3200-deac-11e8-9c88-2b46a3527e38.png)

**Comment by pauldipietro** [comment]
The reproduction uses an older version of Forms (3.0) and I believe this is the same issue as #2798 (which references a newer issue, #3457).
