### ISSUE TITLE
Editor Placeholder text does not wrap

### ISSUE THREAD

**Issue by dannypease** [xamarin/Xamarin.Forms#4291]
When adding long placeholder text in an Editor, the next does not wrap and goes off screen in Android only

### Steps to Reproduce

1. Add an Editor
2. Add a long placeholder sentence
3. Text does not wrap

### Expected Behavior
The placeholder text should wrap in the same way the actual Editor text does

- Version with issue: 3.3.0.967583
- Last known good version: n/a
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 7.1
  - UWP:  n/a

**Comment by andreinitescu** [comment]
@dannypease Can you please a sample app which reproduces this?

**Comment by dannypease** [comment]
Hi, please find a sample that reproduces the error. The error occurs when the Editor is in a horizontal StackLayout. 

`<StackLayout>
        <StackLayout
            Orientation="Horizontal"
            Spacing="0"
            BackgroundColor="White"
            HorizontalOptions="FillAndExpand">
   
            <BoxView
                HeightRequest="150"
                WidthRequest="3"
                BackgroundColor="Purple" />
            
            <StackLayout
                Spacing="0"
                Padding="10,0,0,0"
                HorizontalOptions="FillAndExpand">
                
                <Editor
                    Placeholder="Once upon a time far far away there lived a bear. The bear lived in the woods all on his own."
                    PlaceholderColor="Gray"
                    HeightRequest="150"
                    MaxLength="500"
                    HorizontalOptions="FillAndExpand">
                </Editor>
            </StackLayout>
        </StackLayout>       
    </StackLayout>`

**Comment by samhouts** [comment]
I'm fairly sure that this won't work, since you're giving the Editor infinite width to expand horizontally. Does this work for you if you put a WidthRequest on the Editor?

**Comment by kingces95** [comment]
Android/iOS exhibit same layout on 3.5.0 head...
![image](https://user-images.githubusercontent.com/4120386/49677858-10f49b00-fa25-11e8-9f41-aca6bc4a4bf2.png)

**Comment by kingces95** [comment]
Reproduction can be reduced to the following. Not sure why you'd want to have a horizontal stack layout display your entry control. It's odd, and probably not subject to heavy traffic. It doesn't render the same on Android/iOS. Android runs off the edge of the far screen. iOS smuhes the whole thing on the left so that _every character_ gets wrapped. 
```
<StackLayout
    Orientation="Horizontal">
    <Editor
        Placeholder="Once upon a time far far away there lived a bear. The bear lived in the woods all on his own.">
    </Editor>
</StackLayout>
```

**Comment by kingces95** [comment]
[App68.zip](https://github.com/xamarin/Xamarin.Forms/files/2659090/App68.zip)

**Comment by dannypease** [comment]
@kingces95 It's not just the placeholder that is the issue. Another example of this bug is if you were creating a text messaging type of view.
For example, you are creating a text message feature and you want an editor to expand as the user types and it has a button to the right of the editor that allows the user to send the message.
Let's say you have a horizontal stack layout, with an Editor inside and also an image to the right hand side of the editor to act as the "Send Message" button.
Now you also include the AutoSize="TextChanges" property on the editor so that the editor height expands as the user types, again the text does not wrap.

**Comment by adrianknight89** [comment]
I just ran into this issue on iOS. The width of the Editor is spanning the whole width of the screen. Editor text wraps to new lines as usual, but the placeholder is single-lined and cut off.

**Comment by adrianknight89** [comment]
#5659

**Comment by Carl-Wen** [comment]
Same issue here, Xamarin.Forms version is 4.2.0.815419.

**Comment by AntoninMartin** [comment]
Hi,

I have this issue on iOS, I don't know if it can help but I have found a little trick.

You can get placeholderlabel by reflection, then set frame and bounds with these of editor and finish by settings some properties.

`_placeholderLabel = typeof(EditorRenderer).GetField("_placeholderLabel", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(this) as UILabel; `

`_placeholderLabel.TranslatesAutoresizingMaskIntoConstraints = true;`
`_placeholderLabel.Bounds = Control.Bounds;`
`_placeholderLabel.Frame = Control.Frame;`
`_placeholderLabel.LineBreakMode = UILineBreakMode.WordWrap;`
`_placeholderLabel.TextAlignment = UITextAlignment.Left;`
`_placeholderLabel.Lines = 0;`
`_placeholderLabel.SizeToFit();`
`_placeholderLabel.SetNeedsDisplay();`

It's not a correction or even a solution but just a workaround until issue is resolved :)

**Comment by leo-mck** [comment]
I tested this on iOS 11.4 and 13.1 on versions
4.4.0.991210
4.3.0.908675 
4.2.0.910310
4.1.0.778454
3.6.0.709228
and the problem is there. on iOS the placeholder does not get wrapped. The code

```
<StackLayout VerticalOptions="Center" >

        <Editor HeightRequest="200" Placeholder="This is a long placeholder string that should break line on the device but only do on android" >
        </Editor>

        <Editor HeightRequest="200" >
            <Editor.Placeholder>
                This is a long placeholder
string that should break
line on the device but only do on android
            </Editor.Placeholder>
        </Editor>

    </StackLayout>
```
Results on (android left, iOS right):

![xf_ios_placeholder_bug](https://user-images.githubusercontent.com/876986/69149540-79f9e500-0ab5-11ea-8f8e-b800ab30bae7.png)

I tried @AntoninMartin workaround on a custom renderer but it did not work for some reason :/

**Comment by guilhermereisti** [comment]
Same issue here. Xamarin.Forms 4.4.0.991265

**Comment by jfversluis** [comment]
This is actually a cause for bug #8569. Opened a PR that fixes both

**Comment by douglassimaodev** [comment]
any update on it? I am facing this, XF 4.8

**Comment by jessejiang0214** [comment]
It happens in XF 4.7, need to re-open the ticket?

**Comment by JoeTomkinson** [comment]
I still see this in XF 5.0.0.2515 <- I realise that Xamarin is likely to be completely phased out soon in favour of MAUI but is there a fix for this?

**Comment by dasunmax89** [comment]
I'm too seeing this in XF 5.0.0.2515

**Comment by LeoJHarris** [comment]
Wow still an issue to 2023. Guessing Xamarin wont get this much needed fix?
