### ISSUE TITLE
[macOS] WebView freezes using CustomRenderer

### ISSUE THREAD

**Issue by joseluisct** [xamarin/Xamarin.Forms#4294]
### Description
When using a CustomRenderer for `WebView` on macOS, It is stuck and it's not possible to focus on an `input` to write Text, or right click to open context menu. (for ex. to open console and debug)

It worked OK before with the same CustomRenderer but I've been testing with different versions of XF and the issue also happens, from 3.0 to 3.3

### Steps to Reproduce
1. Create a simple CustomRenderer for `WebView`
Using this code:
`protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.WebView> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null)
            {
                var customWebView = Element as CustomWebView;
                Control.UIRunJavaScriptAlertPanelMessage += Control_UIRunJavaScriptAlertPanelMessage;
            }
        }
        private void Control_UIRunJavaScriptAlertPanelMessage(object sender, WebKit.WebViewJavaScriptFrameEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Alert received: " + e.WithMessage);
        }`
2. Add a `CustomWebView` on a new `ContentPage`
3. Put `Source` property with value https://www.bing.com
4. Navigate to new page via `Navigation.PushAsync`
5. Execute on terminal: `defaults write com.yourcompany.yourbundleid WebKitDeveloperExtras TRUE` to enable WebView debug.

### Expected Behavior
Be able to write text and right click to open context menu. As it works without CustomRenderer.

### Actual Behavior
Not able to write text and right click to open content menu.

### Basic Information
- Version with issue: Xamarin.Forms 3.3.0.967583
- IDE: Visual Studio for Mac 7.6.11 (build 9)
- Platform Target Frameworks: 
  - macOS: 10.13.6 

### Screenshots

![webviewcustomrenderer](https://user-images.githubusercontent.com/21303541/47955727-7d026000-df9c-11e8-9eff-1c39470d7e3a.gif)

### Reproduction Link

https://github.com/joseluisct/WebViewIssues

**Comment by pauldipietro** [comment]
Using the reproduction with 3.3 I do find that the bottom left button/custom webview does not show the right click menu as described.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
