### ISSUE TITLE
[Android] Refocusing a focused Entry inside the event handler of another view hides and shows the keyboard

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4298]
### Steps to Reproduce

1. Run the attached repro
2. Focus the entry by tapping on it
3. Keyboard shows up
4. Now, click the button below
5. Keyboard hides and shows again.

### Expected Behavior

On iOS, the keyboard never hides which is a more natural experience than what's happening on Android. I'd expect the keyboard to stay on instead of losing focus due to button tap.

### Reproduction Link

[App1hjl.zip](https://github.com/xamarin/Xamarin.Forms/files/2546214/App1hjl.zip)

**Comment by Jjagg** [comment]
It would be better if views could be marked to not take focus from editable views. See also #2136.
I haven't found a good workaround yet.

My use-case is a rich text editor with e.g. a bold button (actually a label with gesture recognizer) that when clicked should not affect the editor focus.

**Comment by stevefriesen** [comment]
Is there any update on this?

Our use-case is that we have an entry that has focus and we have a label with a tap gesture recognizer that can be clicked to display something, but we want the entry to retain focus.

**Comment by divyesh008** [comment]
*Android CustomEditorRenderer*

```
protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
{
    base.OnElementChanged(e);
    if (Control != null)
    {
        Control.FocusChange += (sender, eh) =>
        {
            if (eh.HasFocus)
            {
                Device.BeginInvokeOnMainThread(() =>
                {
                    var imm = (InputMethodManager)Control.Context.GetSystemService(Context.InputMethodService);
                    imm.HideSoftInputFromWindow(Control.WindowToken, HideSoftInputFlags.None);
                });
            }
        };
    }
}
```

**Comment by jfversluis** [comment]
There was a PR for this, but it will require new APIs that we won't be adding to Forms anymore at this time. As a result I will close this for now. Have a look at .NET MAUI to see if this is still an issue and if it is, open an issue/feature request there. Thanks!
