### ISSUE TITLE
[Xaml] LiveReload, HotReload for Mac

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#4299]
Hi, i want to share my implementation of "live reloading" feature.
As I understand, currently LiveReload isn't available for Visual Studio for Mac (Sorry, i can be wrong).
Anyway may be it will be interesting to see

https://github.com/AndreiMisiukevich/HotReload

**Comment by pauldipietro** [comment]
Hi Andrei,

While your work is appreciated, we want to make sure GitHub is only being used for active issues pertaining to Xamarin.Forms for sake of housekeeping and organization. I would refer to the information on issue #4155 (specifically [this](https://github.com/xamarin/Xamarin.Forms/issues/4155#issuecomment-433519777) comment) regarding our current situation with Xamarin Live Reload. Thank you for your understanding.
