### ISSUE TITLE
Creating a class like CrossFilePicker's FileData in the main Xamarin.Forms

### ISSUE THREAD

**Issue by ChristianKleineidam** [xamarin/Xamarin.Forms#4302]
CrossFilePicker has a class:

	public class FileData
	{
		public byte[] DataArray { get; set; }

		public string FileName { get; set; }
	}

CrossFilePicker uses that class because going from a file path to a byte[] is different on different platforms. This problem isn't isolated to the issue of letting the user picking files but also comes up at different times when handling files. 

I'm thinking about creating a new plugin that works with files and if I would reuse the FileData class from CrossFilePicker I would have a dependency in my code that makes little sense. If FileData on the other hand would be part of the core Xamarin.forms I could easily reuse it without any issue.

**Comment by andreinitescu** [comment]
@ChristianKleineidam You posted on the wrong repository. Please post your issue to the right repository.

**Comment by rmarinho** [comment]
Hi, we are not looking at the time to add this class. 

We will mark this as an  enhancement to be looked when handling a file picker on Xamarin.Forms.
