### ISSUE TITLE
[Android] TabbedPage's child is appearing before it should be

### ISSUE THREAD

**Issue by toussam** [xamarin/Xamarin.Forms#4303]
Hi guys,

### Description

I noticed an issue when the MainPage is set with a TabbedPage that is containing several children and where one of them is also a TabbedPage. This child's OnAppearing method is being trigger before the user tap on the related tab.

### Steps to Reproduce

1. Open the provided sample into Visual Studio
2. Set some breakpoints into every pages' contructor and OnAppearing method
3. Launch the solution on an Android device
4. Observe the issue

### Expected Behavior

The TabbedPage child's OnAppearing method shouldn't be trigger once the app is running.

### Actual Behavior

The TabbedPage child's OnAppearing method is being trigger once the app is running.

### Basic Information

- Version with issue: 3.1.0.697729 (default one) and 3.3.0.912540 (last one)
- Last known good version: N/A
- IDE: Visual Studio 2017 v15.8.8
- Platform Target Frameworks:
  - Android: android:minSdkVersion="15" and android:targetSdkVersion="28"
- Android Support Library Version: 27.0.2

### Reproduction Link

Cf. the attached sample

I thank you in advance for your response and wish you a great week !
Best regards,

[TabbedPageIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2548234/TabbedPageIssue.zip)

**Comment by soneparmobile** [comment]
This is still happening on Android. I have a tabbed application with 5 tabs. All 5 tabs' OnAppearing are firing when the app loads.

**Comment by kristianpinke** [comment]
Same here. Using Xamarin 16.8.000.262 with Xamarin.Android SDK 11.1.0.26 in Android 11 project.
Problem occurs every time I fire-up the app.

This is blocking when you loading SQLite (w EFCore) data in OnAppearing = deadlock.
