### ISSUE TITLE
Grid row height not being recalculated with rotated labels

### ISSUE THREAD

**Issue by Depechie** [xamarin/Xamarin.Forms#4308]
### Description

When you define a Grid control with RowHeight equal to Auto and place a rotated label in it, the text of the rotated label will be trimmed.
Seems like there should be a recalculation cycle happening after rotation, this is now not being done.

### Steps to Reproduce

1. Create a Xamarin forms app with following XAML as it's content:

```
    <Grid HorizontalOptions="FillAndExpand">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="5*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        
        <Label Text="Test1" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="2" HorizontalTextAlignment="End" HorizontalOptions="End" Rotation="45" />
        <Label Text="Test2" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="3" HorizontalTextAlignment="End" HorizontalOptions="End" Rotation="45" />
        <Label Text="Test3" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="4" HorizontalTextAlignment="End" HorizontalOptions="End" Rotation="45" />
        <Label Text="Test4" Grid.Row="0" Grid.Column="0" Grid.ColumnSpan="5" HorizontalTextAlignment="End" HorizontalOptions="End" Rotation="45" />
    </Grid>
```

### Expected Behavior

Label text should be completely visible.

### Actual Behavior

The top T char of each label is trimmed and set out of bounds of the grid row.

### Basic Information

- Version with issue: 3.3.0.967583
- Last known good version: none
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.0.0.15
  - Android: 9.0.0.20
  - UWP:  not tested

**Comment by andreinitescu** [comment]
I think this is expected, the rotation does not participate in layout calculation, it's a render transform not layout transform

**Comment by Depechie** [comment]
Would be great if we can force the grid to recalculate the row height afterwards somehow...

**Comment by StephaneDelcroix** [comment]
as @andreinitescu said, measurements are done pre-transform

**Comment by CARP-Kaiser** [comment]
@StephaneDelcroix so there isn't a proper way to rotate labels in a grid. That sucks.

**Comment by mjfreelancing** [comment]
Is there are workaround to this? I currently have a tall, narrow, grid column that I want to rotate a label -90 degrees but it is being truncated because of the layout calculations as described above. I've found plenty of reported examples but haven't found any viable solutions.

**Comment by thedee** [comment]
> Is there are workaround to this? I currently have a tall, narrow, grid column that I want to rotate a label -90 degrees but it is being truncated because of the layout calculations as described above. I've found plenty of reported examples but haven't found any viable solutions.

Did you ever figure out a solution?

**Comment by Depechie** [comment]
@thedee I have not looked into this myself anymore, but I would think using Skia would be a solution... like shown here https://forums.xamarin.com/discussion/132260/sizing-with-rotation-in-a-grid-incorrect
