### ISSUE TITLE
On WPF and GTK Application hangs indefinitely while calling HttpClient.GetAsync(...);

### ISSUE THREAD

**Issue by insinfo** [xamarin/Xamarin.Forms#4311]
### Description
On WPF and GTK Application hangs indefinitely while calling HttpClient.GetAsync(...);
### Steps to Reproduce

1. Open Visual Studio 2017 15.8.7 .NET 4.7.03062 Windows 7
2. Create a project Xamarin.Forms 3.3.0.967583 crox platform .Net Standard
3. Add a WPF .NET 4.7^ project and configure it as indicated on the Microsoft website
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf
4. In the Xamarin.Forms project add a button in XAML and bind a click event
in the click event add the following code

```xaml  string page = "http://www.google.com/";     
            HttpClient client = new HttpClient();
            HttpResponseMessage response = await client.GetAsync(page);
            HttpContent content = response.Content;      
            string result = await content.ReadAsStringAsync();
            Utils.ShowAlert(this, result);    
```

### Expected Behavior
which does the http request, and returns the data without crashing the application

### Actual Behavior
the application hangs indefinitely
### Basic Information

- Version with issue:  3.3.0.967583
- Last known good version:
- IDE: Visual Studio 2017 15.8.7
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
  - WPF:
  - GTK:
- Android Support Library Version: 
- Nuget Packages:  
 Newtonsoft.Json 11.0.2  
 Acr.UserDialogs 7.0.1
JWT 4.0.0
Microsoft.Net.Http 2.2.29
NETStandard.Library 2.0.3
SkiaSharp.Views.Forms 1.60.3
sqlite-net-pcl 1.5.231
Xamarin.Forms 3.3.0.967583

- Affected Devices:

### Reproduction Link
project that is giving problem this problem
https://github.com/insinfo/Colaboro

**Comment by rmarinho** [comment]
Hi, I don't see the repo for http call on your link, seems it's just using just sqlite ? can you create a simple test project and upload here?

In the meanwhile can you take a look at these samples they use gtk and wpf and httpclient calls and they work. 

https://github.com/jsuarezruiz/xamarin-forms-gtk-movies-sample

**Comment by PureWeen** [comment]
Closing for now. If you can provide a test project then we can reopen.
