### ISSUE TITLE
XLabs: Gestures.Interests not exists

### ISSUE THREAD

**Issue by scriptBoris** [xamarin/Xamarin.Forms#4315]
I using XLabs forms, for using extended elements, such as ExtendedButton or GesturesContent. But Visual display me warning that "In the type "Gestures" could not find the attached property "Interests". And i cant compile application with rebuild button.

BUT! When I click on the F5 button, the application compiles and runs without errors.

- Nuget Packages:
XLabs.Core;
XLabs.Forms;
Xlabs.Platform;

![image](https://user-images.githubusercontent.com/29772096/48040766-43587180-e1b5-11e8-8ef5-5376f138fae0.png)

**Comment by amalmo** [comment]
XLabs has been deprecated.

**Comment by dansiegel** [comment]
1. XLabs while being a plug-in to Xamarin Forms was always 3rd party and not an officially supported plugin. 
2. The latest stable release of XLabs was 3 years ago and built against Xamarin Forms 1.5 vs the current stable release of Xamarin Forms 3.3. 
3. The most recent release of XLabs is still 2 years old, a preview and built against Xamarin Forms 2.3. 
4. You’re bringing up a problem with a library that is in an archived status. 
5. You just brought up traumatic memories of working with Xamarin Forms 1.X
6. I could go on, but seriously why did you open an issue that was never going to be taken seriously but will be closed?

**Comment by scriptBoris** [comment]
I'm sorry. You can close thread. My bad.

**Comment by andreinitescu** [comment]
It would be interesting however to make a list of features which would be useful to get into Xamarin Forms
