### ISSUE TITLE
Xamarin.Forms Previewer window showing different output than Emulators

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#4316]
I have making android layout with the help of previewer window. After making desired layout when I execute it on emulator it shows different output. 
See code below
```
    <MasterDetailPage.Master>
        <ContentPage Title="MasterP" >
            <StackLayout BackgroundColor="#01796F">
                <StackLayout Margin="25,10,25,0" Padding="0,30,0,0">
                    <Image  BackgroundColor="Accent" Aspect="AspectFill" Source="Enrich.png"></Image>
                </StackLayout>
                <StackLayout  Margin="20,10,20,0" >
                    <Button  Margin="20,5,20,0"   HorizontalOptions="FillAndExpand" Text="Menu 1"></Button>
                    <Button  Margin="20,0,20,0"   HorizontalOptions="FillAndExpand" Text="Menu 1"></Button>
                    <Button  Margin="20,0,20,0"   HorizontalOptions="FillAndExpand" Text="Menu 1"></Button>
                </StackLayout>
            </StackLayout>
        </ContentPage>
    </MasterDetailPage.Master>
```

### Description
Project: Xamarin.Android
Previewer window: Android
Emulator: Nexus_5X_API_28(Android 9.0-API 28)

### Steps to Reproduce

1. Create Xamarin forms project make MasterDetailPage.
2. Write code in master Tag as above. Execute in the above Emulator 
3. 

### Basic Information

Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots

![previewerop](https://user-images.githubusercontent.com/19743421/48047175-3c356180-e1bd-11e8-87a2-8fcd7e964491.png)

### Reproduction Link

> VS bug [#724792](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/724792)

**Comment by rmarinho** [comment]
This might be realted with `AspectFill` and the size of the image. 

Can you give us a small reproduction showing the problem. 

Thanks

**Comment by arvindrajachourasiya** [comment]
@rmarinho - Find the ZIP file attached here. In this file check Main.xaml page on previewer. 

[TestProjectXamarin.zip](https://github.com/xamarin/Xamarin.Forms/files/2560495/TestProjectXamarin.zip)
