### ISSUE TITLE
Custom control measure and arranging issue in Xamarin.Forms.UWP while adding in StackLayout with other control in StackPanel in Xamarin.Forms.

### ISSUE THREAD

**Issue by JeyasriVijay** [xamarin/Xamarin.Forms#4317]
### Description

I have custom control and added it in StackLayout in Xamarin.Forms but custom control not measured and arranged. 

**Note:**
Custom control style has ScrollViewer which have VerticalScrollBarVisibility as Auto, and rendered the children of custom control based on available size of parent panel and seems that parent panel size not get updated while added in StackLayout , 

**Tested Sample**

[CustomControl.zip](https://github.com/xamarin/Xamarin.Forms/files/2552032/CustomControl.zip)

### Steps to Reproduce
**Issue:
 Custom Control HorizontalOptions to be StartAndExpand/ CenterAndExpand and VerticalOptions to be FillAndExpand
**

Custom control has not been measured and arranged with layout options.

**Replication Procedure.**

•	Run the attached sample.

•	Custom control not rendered.

`<ScrollView  >
        <StackLayout x:Name="stackLayout" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <local:MyCustomControl x:Name="MyCustomControl"  HorizontalOptions=" StartAndExpand"  VerticalOptions="FillAndExpand" />
            <Button HeightRequest="300" IsVisible="True"/>
            <Button HeightRequest="300" IsVisible="True"/>
        </StackLayout>
    </ScrollView>
`

**Issue:  
Custom Control HorizontalOptions and VerticalOptions to be FillAndExpand**

Custom Control SizeChanged event not fired when maximize/minimize the page , but custom control MeasureOverride size get changed when application size get changed.

**Replication Procedure.**

•	Change the HorzontalOptions to FillAndExpand in attached sample.

•	Resize the page , custom control size changed not fired when page minimized and only updated on page maximized.

`<ScrollView  >
        <StackLayout x:Name="stackLayout" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <local:MyCustomControl x:Name="MyCustomControl"  HorizontalOptions="FillAndExpand"  VerticalOptions="FillAndExpand" />
            <Button HeightRequest="300" IsVisible="True"/>
            <Button HeightRequest="300" IsVisible="True"/>
        </StackLayout>
    </ScrollView>
`

**Issue in this scenario too.**

`<ScrollView  >
        <StackLayout x:Name="stackLayout" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <local:MyCustomControl x:Name="MyCustomControl"  HorizontalOptions="StartAndExpand"  VerticalOptions="FillAndExpand" />
            <Button HeightRequest="300" IsVisible="False"/>
            <Button HeightRequest="300" IsVisible="False"/>
        </StackLayout>
    </ScrollView>
`

### Expected Behavior
Custom control panel available size to be updated while adding in StackLayOut

### Actual Behavior
Custom control available size not to be updated while adding in StackLayOut

### Basic Information

- IDE: VS 2017
- Platform Target Frameworks: 
  - UWP:  The version of the UWP SDK you are compiling against,  16299 
- Nuget Packages: Xamarin.Forms - 2.4.0.280
- Affected Devices: Desktop

Could you please check the render issue with custom control style have ScrollViewer which have VerticalScrollBarVisibility as Auto in StackLayout?

Custom control panel available size to be updated while adding in StackLayOut alone

**Comment by rmarinho** [comment]
You need to implement ArrangeOverride on the ViewRenderer and actually arrange the controls because the base renderer doesn't know what to do with these controls.

If you override on your renderer you will get the vailable size, then you have to set the values also to your control.

**Comment by JeyasriVijay** [comment]
Can you please modify the sample shared to achieve my requirement,

I have tested the same, you can find the demo sample in arrange override could not raised only measure override called, 

Please test the sample

**Comment by JeyasriVijay** [comment]
Hi ,

Thanks for your reply.

I agree to set control minimum width to render control , i have tested the sample shared by you with  latest packages , but still facing issue in custom control SizeChanged event . please find the images.

Kindly share your suggestion to get the soultion.

![onpagemaxized](https://user-images.githubusercontent.com/24602456/48178323-fa342900-e33e-11e8-8a53-432eeef8bb92.png)

**Issue in page minimized** 

![onpageminimised](https://user-images.githubusercontent.com/24602456/48178412-6151dd80-e33f-11e8-84b0-7c80b4230be5.png)

`  <ScrollView  >
        <StackLayout x:Name="stackLayout" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <local:MyCustomControl x:Name="MyCustomControl"  HorizontalOptions="FillAndExpand"  VerticalOptions="FillAndExpand" />
            <Button HeightRequest="300" IsVisible="True"/>
            <Button HeightRequest="300" IsVisible="True"/>
        </StackLayout>
    </ScrollView>`

**Comment by JeyasriVijay** [comment]
Got solution to fire size changed event by assign minimum height to custom control , thanks for your help.

**Comment by rmarinho** [comment]
Awesome!
