### ISSUE TITLE
[Android] Pop Up a picker when changing the page of CarouselPage

### ISSUE THREAD

**Issue by paymicro** [xamarin/Xamarin.Forms#4318]
### Description

When changed page of `CarouselPage` pop-ups `Picker` control as if he was pressed.

### Steps to Reproduce

1.  Create CarouselPage 
2.  Add 2 pages with Picker control
3.  Focus on a `Picker`
4.  Change page

### Expected Behavior

Picker don't pops up

### Actual Behavior

Picker pops up

### Basic Information

- Version with issue: master branch
- Last known good version: -
- IDE: Windows Visual Studio 2017 15.8.8

### Screencast

http://recordit.co/FkHj45S1pK

### Reproduction Link

https://github.com/paymicro/Xamarin.Forms/commit/1d1d01a89e0b78fd47010ad18b7ce346cca6897b

**Comment by rmarinho** [comment]
Seems this is a regression introduced by https://github.com/xamarin/Xamarin.Forms/commit/cceee9ded6c8cadb19eb547f72d03c6c14230058

We are forcing the picker to up on focus, that will work fine for the Tab stop , but will have issues like we see when the page comes into Focus, passes focus to children, this will  open the pop up picker

**Comment by tmt242001** [comment]
#4187 related
