### ISSUE TITLE
OnPlatform/OnIdiom markup extension not working using NamedSize

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#4319]
**Description**
This nice new markup facility doesn't seem to work in a style if i use NamedSize
 
**Steps to Reproduce**

add resource style for label as below
```xaml
<Setter Property="FontSize" Value="{OnIdiom Phone=Micro, Default=Small}" />
```

**Expected Behavior**

it works like below one

```xaml
<Setter Property="FontSize" >         
    <OnIdiom x:TypeArguments="Font" Phone="Micro" Tablet="Small" Desktop="Small" />         
</Setter>
```

it works like

Basic Information
Version with issue: 3.3

**Comment by StephaneDelcroix** [comment]
the title complains about `OnPlatform`, the sample applies to `OnIdiom`. I guess both markup extensions have the same issue...
