### ISSUE TITLE
Regression: native views don't lose their native parent when they lose the XF parent

### ISSUE THREAD

**Issue by ddobrev** [xamarin/Xamarin.Forms#4329]
### Steps to Reproduce

1. Set the content of a ContentView to a native view (use NativeViewWrapper or ToView());
2. Save the content to a local variable;
2. Set the content to null;
3. Add the saved content to another parent.

### Expected Behavior

The native view appears in another parent. 

### Actual Behavior

Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### Basic Information

- Version with issue: 3.3.0
- Last known good version: 3.2.0

**Comment by rmarinho** [comment]
Hi, could you upload a short repo showing the issue?!

Thanks

**Comment by samhouts** [comment]
@ddobrev  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by rcoelhoAtterbury** [comment]
Was this ever resolved? I have been beating my head on this issue for several days now. My needs are move complex, but to simplify the complexities, I've narrowed it down to creating a single cell GridLayout in NativeAndroid using the Activity as Context. I insert a TextView in the GridLayout. I use ToView to generate a wrapper and attach it to an AbsoluteLayout in XF. This shows up fine, on initial display. However, if I show another page, and then return to the page that holds this item, it crashes. If I allocate the GridView as usual, but do not (convert to form and and attach to layout in XF) the backward navigation works fine. I tried detaching the view at the Android level, but that didn't seem to make a difference. Please help.
