### ISSUE TITLE
iOS Debugging broken with latest VS Update

### ISSUE THREAD

**Issue by taori** [xamarin/Xamarin.Forms#4335]
### Steps to Reproduce

1. Switch back and forth between iPhone and iPhoneSimulator Platform
2. Start debugging

### Expected Behavior
Debugger should attach

### Actual Behavior
Debugger does not attach properly because MAC picks the wrong cache path. Check screenshots for further indications on what is going wrong.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.1.0.15 (cbfb047)
  - Android: 
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
This is what i am getting in the Debugging part for my output window
![grafik](https://user-images.githubusercontent.com/5545184/48134053-12ea0380-e299-11e8-83dc-239318af3b5d.png)
This is what i am getting in the build part for my output window
![grafik](https://user-images.githubusercontent.com/5545184/48134210-a0c5ee80-e299-11e8-8b3f-209ef83d6ad3.png)
My VS settings are to build for "iPhone" not "iPhoneSimulator". While the build part picks the correct platform, MSBuild seems to pass on the wrong arguments to the debugging process - thus the expected cache Path is not available and the debugger won't launch properly.

Note that i had to set up "iPhoneSimulator" previously in order to get a proper error message which pointed me to another build issue (on iPhoneSimulator msbuild told me i need to update XCode on mac, while iPhone gave me a generic error code with no additional information)

So there's something messy going on in the build chain right now.

.targets code used for my custom build integration script to deduct paths (build chain was regularly broken (automated symbol upload etc) because of target changes until i made a custom build script)
	`	<CreateProperty Value="/Users/admin/Library/Caches/Xamarin/mtbs/builds/STM.iOS/$(BuildSessionId)/bin/$(Platform)/$(Configuration)/"><Output PropertyName="MacBuildFolder" TaskParameter="Value" /></CreateProperty>`

The used build properties are nothing unordinary as you can see.

**Comment by rmarinho** [comment]
Hi, can you please open your issue here , https://github.com/xamarin/xamarin-macios/issues/ . 
Sorry try to move it but that transfer beta feature isn't working for me.

Thanks
