### ISSUE TITLE
[macOS] BoxView binding to BackgroundColor broken

### ISSUE THREAD

**Issue by Abhijit-Revamp** [xamarin/Xamarin.Forms#4338]
###  #Description
BoxView Background color binding does not work on macOS.
Related to #3557 

### Steps to Reproduce

1. Add following XAML element to how a horizontal line across parent (Say grid)
```
<BoxView HorizontalOptions="FillAndExpand" HeightRequest="10"
                     VerticalOptions="FillAndExpand" BackgroundColor="{Binding ElementColor}" />
```
2. In the code behind, inside the databound object, define the property (You can set any color)
```
public Color ElementColor { get { return Color.FromHex("#FF006489"); } }
```

### Expected Behavior
The BoxView must inherit background color from the bound property

### Actual Behavior
BoxView has transparent color

### Basic Information

- Version with issue: 3.2.0.871581
- Last known good version:
- IDE: VS Mac
- Platform Target Frameworks: 
  - macOS:  

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by Abhijit-Revamp** [comment]
just forgot to mention.
Its Xam.Forms project with macOS target (it works fine on iOS)

**Comment by rmarinho** [comment]
Hey did a shot test and worked fine for me. Can you please upload a small repo.

```
var cp = Color.FromHex("#FF006489");
var box = new BoxView { Color = Color.Pink, HeightRequest = 100, WidthRequest = 100 };
box.SetBinding(BoxView.BackgroundColorProperty, ".");
box.BindingContext = cp;
```
<img width="338" alt="screenshot 2018-11-09 at 23 46 22" src="https://user-images.githubusercontent.com/1235097/48294032-d3c6d880-e479-11e8-9348-0402879dedd5.png">

Thanks

**Comment by Abhijit-Revamp** [comment]
You can access the solution from 
https://github.com/Abhijit-Revamp/XamIssues.git

**Comment by Abhijit-Revamp** [comment]
Any update on this?

**Comment by domyd** [comment]
I can reproduce this bug on WPF as well when binding to `BackgroundColor` (Button -> Command -> Change VM color property -> not updated in UI). However, the binding to `Color` works as expected and, from what I can tell, behaves exactly the same.

**Comment by hartez** [comment]
@domyd If you're seeing this bug on WPF, please open a new issue for that platform. Thanks.
