### ISSUE TITLE
Bold ToolbarItem text

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#4339]
On iOS, many Navigation Bar buttons created using Xamarin.Forms ToolbarItems on NavigationPages do not have a native feel. In an iOS app, Navigation Bar buttons on the default workflow path are rendered in bold. Examples are the "Done" button when adding a contact in Phone, the "Add" button when adding an event in Calendar, and the "Send" button when sending an email in Mail. This sort of rendering is not currently supported by ToolbarItem.

The Xamarin.Forms abstraction should have a way to indicate that a ToolbarItem is the default or allow specifying a style for the ToolbarItem. It might be possible to do this with a custom renderer, although correlating ToolbarItems to UINavigationBars doesn't seem easy, especially if the ToolbarItems can change dynamically. But it doesn't really matter, since providing a native experience using cross-platform code without resorting to platform-specific coding is the mission of Xamarin.Forms to begin with. Hence the need for a more complete ToolbarItem abstraction.

**Comment by rmarinho** [comment]
Have you tried UIAppearence to try style those?

**Comment by breyed** [comment]
I haven't found a way to map from ToolbarItem to UINavigationBar, so I have nothing to apply UIAppearance to. Plus, I'd rather not have to write a custom render for this at all. For another example, I happened to write a review for an iOS app in the App Store today and noticed that the Done button was bold. Bold buttons are as much a bread-and-butter feature of iOS as large titles, and should likewise be supported by the Xamarin.Forms abstraction as first-class citizens.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
