### ISSUE TITLE
[Shell] Page content on iOS is cut off

### ISSUE THREAD

**Issue by jimmgarrido** [xamarin/Xamarin.Forms#4342]
### Description
I am seeing the top of the page being cut off when using shell on iOS. So far I've noticed this happens to controls when inside a `StackLayout`, but a `Label` used by itself also has this issue so they may be more instances of this.

### Steps to Reproduce

1. Create a new project using shell
2. Add a `StackLayout` to a page with another control like `ListView` inside it
3. Deploy to iOS

### Expected Behavior
The entire control is visible

### Actual Behavior
The top of the control is cutoff by the edge of the screen, navbar, etc.

### Basic Information

- Version with issue: 3.5.0.988554
- Last known good version: 
- IDE: VS2017 15.9
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/4087358/48166588-dd93e480-e29d-11e8-9e1a-7563ac852b71.png)

### Reproduction Link

[App80.zip](https://github.com/xamarin/Xamarin.Forms/files/2559595/App80.zip)
Parent: #2415

**Comment by tmulin** [comment]
I try to use a ScrollView wrap the StackLayout , in this case the page displays OK !

**Comment by davidortinau** [comment]
As @tmulin points out, `ScrollView` is ok. I can also get this to be ok without a `ScrollView` by enabling UseSafeArea on the `ContentPage`.

![shell-ios-scrollview](https://user-images.githubusercontent.com/41873/52833758-1b29ba00-30a4-11e9-969a-065d78a68290.png)

This also shows oddly in the Previewer, down by about 20px.

![shell-scrollview-previewer](https://user-images.githubusercontent.com/41873/52833817-6c39ae00-30a4-11e9-9d0f-b332ddea3772.png)

The same content of a `Grid` without a `ScrollView` is under the `NavigationBar`:

![shell-ios-vertical](https://user-images.githubusercontent.com/41873/52833774-385e8880-30a4-11e9-9653-8665b1320baa.png)

**Comment by rmarinho** [comment]
Just set ` Shell.SetPaddingInsets="true"` in your ShellItem.
