### ISSUE TITLE
[Enhancement] Change bindable layout implementation for the better

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#4346]
### Rationale

Based on conversations on PR #4269 which was related to adding ItemsSource and ItemTemplate to the Map control, the XF team instead want the existing implementation on bindable layouts changed (the PR is #4052) and in a way it's being used by Map too and other controls.

To be easier, I will copy and paste the comments from the XF team:

@rmarinho:
- Can't you reuse the BindableLayout helpers here? I think it makes more sense to reuse some of that code. Maybe even improve the the helpers so we can use it here and in more places. 

@StephaneDelcroix:
- It is worth making BindableLayout generic (with a better name) so it can handle Views, Pins, you name it.
- our goal is to provide templating capabilities to all controls exposing collections (as described in #1708). But we would like to avoid:
         - exposing templating directly (prefer attached BPs)
         - duplicating the INPC/INCC code everywhere.
         The best approach, in my opinion, would be -- for maintaining purposes -- to generify the BindableLayout code, and then exposing a non-generic BindableLayout and PinRepeater (whatever the name) classes. You're welcome to propose something.

**Comment by andreinitescu** [comment]
@ruimarinho @stephanedelcroix

I looked over @hartez work on CollectionView. Suprinsingly, it appears to me it's how you mentioned you don't want things to be.
The CollectionView is implementing ItemsSource and ItemTemplate properties and the renderers duplicate in their own code observing and reacting to the changes on the ItemsSource collection:

iOS: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs
Android: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/CollectionView/ObservableItemsSource.cs

Also, `Picker` works in the exact same way.

Since those implementations are fine, I'm now confused of what you want.

In the meantime, it's a pity there's still no simple way to have bindable layouts and bindable pins on the Map.

**Comment by andreinitescu** [comment]
@rmarinho @StephaneDelcroix Any feedback? Thanks

**Comment by StephaneDelcroix** [comment]
CollectionView supports virtualization, that's where the difference comes from. Picker should follow the same pattern as Maps.Pin.
But you make an excellent point here... and I should revisit your Maps.Pin PR with that in mind...

**Comment by StephaneDelcroix** [comment]
I reopened #4269 and BindableLayout has shipped, so it's hard to change it anymore. If you're fine with that, I'm going to close this. Thanks for your patience.
