### ISSUE TITLE
Rendering issues tabbed page on iOS 12.1 (Demo included)

### ISSUE THREAD

**Issue by jorisvergeer** [xamarin/Xamarin.Forms#4347]
### Steps to Reproduce

1. Use a nested tabbed page on iOS 12.1
(See attached demo project and screenshots)
Look at the navigation buttons.

### Expected Behavior
iOS < 12.1
![image](https://user-images.githubusercontent.com/1906639/48194610-c57b9e00-e34d-11e8-81ba-f3ad2c486e3a.png)

### Actual Behavior
iOS == 12.1
 ![image](https://user-images.githubusercontent.com/1906639/48194720-17bcbf00-e34e-11e8-9ae2-2276035cbe82.png)

### Basic Information

- Version with issue: 3.3
- Last known good version: None
- IDE: Visual Studio (Altough it does not matter
- Platform Target Frameworks: 
  - iOS:  SDK Default (12.1), Deployment Target: 8
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: iOS 12.1

### Reproduction Link

[iOSFailDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2561405/iOSFailDemo.zip)

**Comment by rmarinho** [comment]
Hi, i can repo this but tbh we really didn't ever support nested tabbed pages on iOS.

**Comment by jfversluis** [comment]
Never really supported and not much traction here. @jorisvergeer although you're Dutch, I'm going to have to close this for now. Thanks for the report!
