### ISSUE TITLE
.NET Standard library's PDB has invalid sequence points

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [xamarin/Xamarin.Forms#4353]
### Description

The default Xamarin.Forms project in Visual Studio 15.8.4 produces a PDB file alongside the .NET Standard library. In the Release configuration, this PDB file has sequence points whose IL offsets point to the middle of an IL instruction, not the start of one.

As a result, the Visual Studio debugger will not hit breakpoints associated with these errant sequence points.

Note that I'm filing this issue on behalf of a Xamarin partner, PreEmptive Solutions. We found this issue when, as part of [Dotfuscator's protection of Xamarin projects](https://blog.xamarin.com/protecting-xamarin-apps-dotfuscator/), we were unable to map some sequence points to instructions, and therefore could not preserve those sequence points.

### Steps to Reproduce

These instructions are the fastest way to see the issue. For other ways of verifying the issue, see Other Evidence, below.

1. Create a new C# Xamarin.Forms project with the default settings:
    - Template: Blank
    - Platform: Android, iOS, UWP
    - Code Sharing Strategy: .NET Standard  
2. Build the Android project in Release / Any CPU, which will also trigger a build for the .NET Standard library.
3. Launch [ILSpy](https://github.com/icsharpcode/ILSpy) (version used: 3.2.0.3856) and configure it to show internal code elements and sequence points:
    - View -> Check "Show internal types and members"
    - View -> Options... -> Decompiler -> Check "Show info from debug symbols, if available"
    - Language drop-down: set to "IL"
4. Open the .NET Standard library in the Android project's `bin\Release` folder.
5. Browse to the `InitializeComponent` method of either the `App` or `MainPage` type.
6. Review the IL code (a.k.a. MSIL or CIL). Comments indicate the presence of sequence points from the PDB.

### Expected Behavior

All of the `sequence point` comments just list line, column, and file information, indicating the sequence points are valid and point to the start of the instruction after the comment.
For example:

    // sequence point: (line 21, col 13) to (line 21, col 88) in C:\code\InvalidPdbOffsets\InvalidPdbOffsets\InvalidPdbOffsets\obj\Release\netstandard2.0\MainPage.xaml.g.cs
    IL_0000: nop
    
indicates a sequence point with IL offset `0x0000`, which is the same as the offset as the `nop` instruction.

### Actual Behavior

A `sequence point` comment lists a different IL offset than the following instruction, indicating a sequence point that does not point to the start of an instruction.
For example:

    IL_000d: ldtoken InvalidPdbOffsets.MainPage
    // sequence point: !! at IL_0011 !!(line 22, col 9) to (line 22, col 10) in C:\code\InvalidPdbOffsets\InvalidPdbOffsets\InvalidPdbOffsets\obj\Release\netstandard2.0\MainPage.xaml.g.cs
    IL_0012: call class [netstandard]System.Type [netstandard]System.Type::GetTypeFromHandle(valuetype [netstandard]System.RuntimeTypeHandle)

indicates a sequence point with IL offset `0x0011` (note the `!!` in the comment, highlighting the issue). The nearest instructions start at offsets `0x000d` and `0x0012` - meaning the sequence point actually points to the middle of the `ldtoken` instruction's operand.

### Other Evidence

I have also independently verified the issue two other ways:

* By using [System.Reflection.Metadata](https://www.nuget.org/packages/System.Reflection.Metadata) to view the sequence points' IL offsets and comparing to the output of [ILdasm](https://docs.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler). This verifies that the issue is in the assembly using Microsoft's tools, and not a mistake made by ILSpy or the library it uses, Mono.Cecil.
* By enabling debugging in the Release configuration and attempting to hit a breakpoint on the line indicated by the errant sequence point. While I was able to hit the preceding line, I was unable to hit or even step into the errant line.

### Basic Information

- Version with issue: Xamarin 4.11.0.756 (d15-8@b66ff7180)
- Last known good version: Not known
- IDE: Visual Studio Professional 2017, Version 15.8.4
- OS: `Microsoft Windows [Version 10.0.16299.309]`
- Platform Target Frameworks:
    - Android: 8.1 (Oreo)
- Nuget Packages: the default
- Affected Devices: N/A

### Reproduction Link

[InvalidPdbOffsets.zip](https://github.com/xamarin/Xamarin.Forms/files/2562337/InvalidPdbOffsets.zip)

Attached is a ZIP'd git repository. The default `master` branch follows the reproduction steps above.

Also present is a `with-release-debugging` branch that indicates how I enabled debugging for the Release configuration, where I was unable to hit a breakpoint at `MainPage.xaml.g.cs` on line 22.

**Comment by StephaneDelcroix** [comment]
Sequence points aren't expected to match for InitializeComponent, as InitializeComponent IL is fully replaced post-compilation.

I'll see if we can do something, or report the problem to `mono.cecil`
