### ISSUE TITLE
[CollectionView] Failure to set ItemsSource causes an unhandled exception to occur

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#4366]
### Description

Cross-referencing to #3172 and #4265

When using `CollectionView`, not explicitly setting the `ItemsSource` value causes an unhandled exception.

### Steps to Reproduce

1. Run attached sample and note the unhandled exception
2. Re-run the sample after uncommenting the `ItemSource =` line in App.xaml.cs and the app will no longer crash

Tested on Android, but might happen anywhere if it's not handled in Core.

### Expected Behavior
App handles a lack of an ItemSource without throwing an exception

### Actual Behavior
An unhandled exception occurs which can cause confusion as to it being the root cause.

### Reproduction Link

[CVSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2567644/CVSample.zip)

**Comment by hartez** [comment]
> Expected Behavior
> App handles a lack of an ItemSource with a graceful exception

It shouldn't even throw an exception; it should just not display anything. It's totally reasonable to be in a state where the CollectionView exists but the ItemsSource hasn't been set yet.
