### ISSUE TITLE
Add down arrow / up arrow to picker on android

### ISSUE THREAD

**Issue by JanabiSoft** [xamarin/Xamarin.Forms#4372]
##Summary
on android there is no way to differentiate between entry and picker, so please add down arrow / up arrow to picker.

##API Changes
Unknown

##Intended Use Case
to enhance the UI

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
