### ISSUE TITLE
[iOS] crash on reused page with ScrollView

### ISSUE THREAD

**Issue by jimmgarrido** [xamarin/Xamarin.Forms#4381]
### Description
When using Shell on iOS, I'm experiencing a crash on when navigating to a page with a `ScrollView` for the second time.

### Steps to Reproduce

1. Run the attached project on iOS
2. Open the flyout and go to "About"
3. Open the flyout and go to "Browse"
4. Go back to "About"

### Expected Behavior
The app navigates to "Browse"

### Actual Behavior
The app crashes

### Basic Information

- Version with issue: 3.5.0.988554
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  12.0

### Reproduction Link

[App79.zip](https://github.com/xamarin/Xamarin.Forms/files/2573412/App79.zip)

**Comment by kingces95** [comment]
On `origin/shell-3.4.0` I get this: 
![snag_aa69b98](https://user-images.githubusercontent.com/4120386/48652570-3f420600-e9a4-11e8-9241-b383c7eb2363.png)

**Comment by StephaneDelcroix** [comment]
Not a Shell issue. ScrollViewRenderer doesn't inherit from VisualElementRenderer`1, so the RendererProperty is never cleared
