### ISSUE TITLE
[MacOS] Appearing doesn't fire on MacOs when navigating backwards

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4387]
### Description
If you click the backbutton on MacOS the Appearing event doesn't fire on the page that becomes active

### Steps to Reproduce

1. Push two pages onto a NAvigationPAge
2. subscribe to onappearing on the first page
3. click the back button in the header bar

### Expected Behavior
OnAppearing should fire

### Actual Behavior
OnAppearing doesn't fire

### Reproduction Link

you can use Bugzilla31688 in the control gallery. Just override OnAppearing on the pages that get inserted into the stack to test this issue

**Comment by AndreiMisiukevich** [comment]
@PureWeen i tested with own sample

tried to push Page1, then OnButtonClick (in Page1) push Page2
Tried to go back and OnAppearing of Page1 was called.

I think, it can be something related to InsertPage .
