### ISSUE TITLE
[macOS] Issue2399 Crashes on macOS

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4389]
### Description
Running Issue2399 on macOS causes a gnarly crash on  macOS.

The point of Issue2399 is to test that all effects are detached from a listview so ideally when this is fixed the purpose of Issue2399 will also be maintained for macOS

### Steps to Reproduce

1.  Run Issue2399 in the Control Gallery
2.  Click back in the header
3.  App freezes up then crashes

### Expected Behavior
Doesn't crash

### Actual Behavior
Crashes

### Basic Information

- IDE: VS for MAC
- Platform Target Frameworks: 
  - macOS - 10.14.2

**Comment by AndreiMisiukevich** [comment]
@PureWeen Hi, could you please check this PR https://github.com/xamarin/Xamarin.Forms/pull/4607 ?

As issue isn't reproduced on that branch

**Comment by Miiite** [comment]
I think this issue should be closed for clarity. I was not able to reproduce it on branch 3.5.0
