### ISSUE TITLE
[iOS] HttpClient GetAsync does not consider connection loss as an error

### ISSUE THREAD

**Issue by Flheriau** [xamarin/Xamarin.Forms#4392]
### Description

I'm using HttpClient to download files from URLs with GetAsync method. With huge images for example, when I stop internet connection manually in the middle of the download, it is considered as a normal ending for the GetAsync method and the resulting HttpResponse is totally normal (status 200, no error message, no exception).  Depending of the moment of the connection loss, the resulting image corresponds to the download progress (starting from the top of the image).

### Steps to Reproduce

1. Download an image from a public URL using HttpClient.GetAsync
2. Disable your internet connection during the download 
3. Set an Image ImageSource with the response

### Expected Behavior

At least an exception for the connection loss or another status for the HttpResponse

### Actual Behavior

Nothing.

### Basic Information

- Version with issue: 
   - Xamarin.Forms 3.3.0.912540
   - Xamarin.iOS 12.1.0.15
   - HttpClient Implementation : NSUrlSession (iOS 7+)

### Sample project

[TestHttpClientGet.zip](https://github.com/xamarin/Xamarin.Forms/files/2584792/TestHttpClientGet.zip)

Simple sample project with a "Download" button.
To reproduce, you need to stop internet connection after you clicked on Download.

**Comment by kingces95** [comment]
Could you please provide a sample app as well as the URL used download an image that reproduces the problem?

**Comment by Flheriau** [comment]
You can see a Sample project in the description. The image used is 10 Mo large to have the time to stop the internet connection. (https://www.spacetelescope.org/static/archives/images/publicationjpg/heic0711a.jpg)

**Comment by Flheriau** [comment]
Any update on this ? Did you manage to reproduce the problem with the sample ?

**Comment by samhouts** [comment]
This issue was moved to xamarin/xamarin-macios#5215
