### ISSUE TITLE
Migrate Forms Signing to use standard Signing Service

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#4393]
### Description

The current signing step seems to be strictly tied to Xamarin Engineering. This could be changed if the Xamarin Engineering team adopted the use of Oren's [SignService/SignClient](https://github.com/onovotny/SignService). It's already used for a number of .NET Foundation projects including Prism, ReactiveUI, Humanizer, Xunit. The benefit here would be that if an enterprise (or anyone really) wanted to generate a custom build that was still signed, they could do so in a manner that is used among other .NET projects and is very easy to setup. 

Using something like the following Signing Script would make this highly configurable since anyone generating their own build would simply need to define a few variables and be able to sign their NuGet's, while anyone who doesn't have these variables defined would be able to still get the build without signing.

```ps1
$currentDirectory = split-path $MyInvocation.MyCommand.Definition

# See if we have the ClientSecret available
if([string]::IsNullOrEmpty($env:SignClientSecret)){
    Write-Host "Client Secret not found, not signing packages"
    return;
}

dotnet tool install --tool-path . SignClient

# Setup Variables we need to pass into the sign client tool

$appSettings = "$currentDirectory\appsettings.json"
$fileList = "$currentDirectory\filelist.txt"

# GitHub projects will appear as User/Project unless sanitized
$repoName = $env:BUILD_REPOSITORY_NAME -replace ".*/",""

$azureAd = @{
    SignClient = @{
        AzureAd = @{
            AADInstance = $env:SignClientAADInstance
            ClientId = $env:SignClientClientId
            TenantId = $env:SignClientTenantId
        }
        Service = @{
            Url = $env:SignServiceUrl
            ResourceId = $env:SignServiceResourceId
        }
    }
}

$azureAd | ConvertTo-Json -Compress | Out-File $appSettings

$nupkgs = Get-ChildItem $env:BUILD_ARTIFACTSTAGINGDIRECTORY\*.nupkg -recurse | Select-Object -ExpandProperty FullName

foreach ($nupkg in $nupkgs){
    Write-Host "Submitting $nupkg for signing"

    .\SignClient 'sign' -c $appSettings -i $nupkg -f $fileList -r $env:SignClientUser -s $env:SignClientSecret -n $repoName -d $repoName -u $env:BUILD_REPOSITORY_URI

    Write-Host "Finished signing $nupkg"
}

Write-Host "Sign-package complete"
```

**Comment by duncanmak** [comment]
@cadsit Can you look into this?

**Comment by duncanmak** [comment]
Hello, this is Duncan and I run the Release Engineering at Xamarin.

We have no plans to move away from our existing setup for code signing right now because of a hard requirement to use Microsoft certificates when publishing to nuget.org.

There is a bit more detail listed here: https://blog.nuget.org/20170914/NuGet-Package-Signing.html

I'll be engaging with other Microsoft projects hosted under the .NET Foundation to figure out what the official guidelines should be. I'll update this issue when I find out more.

Thanks!
