### ISSUE TITLE
[iOS] ListView cannot reset selected status

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#4394]
### Description
ListView cannot reset selected status
[UnselectedListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2577065/UnselectedListView.zip)

### Steps to Reproduce
as in my simple demo

1. click to select a item, which will become selected, and it shows SelectedBackgroundView 
2. and click **same** item again,  it try to clear selected status by `ItemsListView.SelectedItem = null;`
3. then it should clear SelectedBackgroundView, however, it doesn't

### Basic Information

- Version with issue: 3.3.0.967583
- IDE: VS
- Platform Target Frameworks: 
  - iOS:  

### Reproduction Link

[UnselectedListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2577065/UnselectedListView.zip)

### Reason:

1.  ListViewDataSource will set _selectionFromNative to true, when clicked on an item.
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L1124
2. and reset it to false when SelectedItem Changed.
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L1064
3. however, if click on **same** item,  SelectedItem is not changed, and it doesn't have chance to reset _selectionFromNative to false.
4.  if ItemsListView.SelectedItem = null then, because of _selectionFromNative is still true, it will prevent _uiTableView.DeselectRow() to executed in the same method OnItemSelected.
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L1092
5. thus, it cannot reset selected status, even SelectedItem is set to null.

**Comment by kingces95** [comment]
Add ability to unselect selected item by clicking the same item again. Feel free to submit a PR if you've got a change that'll enable this behavior else we'll push it on the stack.

**Comment by kingces95** [comment]
Oops. Works on android. So we'll take it as a bug.

**Comment by bill2004158** [comment]
it means in ios, ItemsListView.SelectedItem = null cannot de-select the row in some case.
