### ISSUE TITLE
[Android] FFImageLoading Crashes on Calling Init Method

### ISSUE THREAD

**Issue by zekeinferno** [xamarin/Xamarin.Forms#4405]
### Description
After updating Xamarin Forms to 3.4.0 pre-2 or later, FFImageLoading crashes when you call its initialization method on Android.

### Basic Information

- Version with issue: Xamarin Forms 3.4.0.987044-pre2 and later
- Last known good version: Xamarin Forms 3.4.0.925479-pre1
- IDE: Visual Studio for Mac

### Screenshots

<img width="942" alt="screen shot 2018-11-14 at 12 48 45 pm" src="https://user-images.githubusercontent.com/7019380/48513523-412b8e00-e819-11e8-9493-2f86d019bbf1.png">

### Reproduction Link

[FFImageLoading_CrashOnInit.zip](https://github.com/xamarin/Xamarin.Forms/files/2587612/FFImageLoading_CrashOnInit.zip)

**Comment by NiknakSi** [comment]
Having the same issue, exactly the same scenario as @zekeinferno. I appreciate though that this may legitimately be a problem with FFImageLoading instead (such as relying on something XF now considers to be a bug which has been fixed since 3.4.0.925479-pre1)...

**Comment by kingces95** [comment]
Error occurred while restoring NuGet packages: The local source 'C:\Users\Chris\Downloads\FFImageLoading_CrashOnInit\Example\LocalPackages' doesn't exist.
1>------ Build started: Project: Example.Common, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1004: Assets file 'C:\Users\Chris\Downloads\FFImageLoading_CrashOnInit\Example\Example.Common\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
1>Done building project "Example.Common.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by kingces95** [comment]
All packages are already installed and there is nothing to restore.
Time Elapsed: 00:00:00.1837786
========== Finished ==========

Error occurred while restoring NuGet packages: The local source 'C:\Users\Chris\Downloads\FFImageLoading_CrashOnInit\Example\LocalPackages' doesn't exist.

**Comment by kingces95** [comment]
If possible, start with the VS template project and add only what you need there.

**Comment by IoTFier** [comment]
Same here … VS 15.9.1; XF 3.4 Stable Error while init of FFImageloading -

https://github.com/luberda-molinet/FFImageLoading/issues/1154

**Comment by daniel-luberda** [comment]
It should be filed in newest stable.

**Comment by zekeinferno** [comment]
I have confirmed that the issue has been resolved with the reproduction project I provided originally, I'll be closing this issue. Thanks for the help everyone!
