### ISSUE TITLE
Unable fo use Forms.Init()

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#4407]
### Steps to Reproduce

1. Create project A and add nuget package Xamarin.Forms.Platform.WPF
2. Create GTK project, add project A as reference and add nuget package Xamarin.Forms.Platform.GTK
3. in GTK project call Forms.Init();

### Expected Behavior

There should not be any errors

### Actual Behavior

Compilation error

### The root of the problem

Because Forms class has the same namespace, compiler doesn't know which Assembly to use.

So possible solution is to add platform into the namespace (e.g. Xamarin.Forms.GTK.Forms.Init())

**Comment by VladislavAntonyuk** [comment]
the possible solution is to use Aliases for each package, but it makes code more complex

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
