### ISSUE TITLE
GTK navigation is broken

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#4409]
### Description
Unable to switch back from the child page 

### Steps to Reproduce

1. Create navigation page
2. Click on link to child page

### Expected Behavior
The navigation bar is visible

### Actual Behavior
The navigation bar is missed

### Basic Information

- Version with issue: 3.5

### Screenshots
WPF:
![image](https://user-images.githubusercontent.com/33021114/48517774-13bdff00-e870-11e8-9ea2-b3b8960b25a1.png)

GTK:
![image](https://user-images.githubusercontent.com/33021114/48517792-26d0cf00-e870-11e8-8b7b-6c8cfda24ec3.png)

**Comment by joseluisct** [comment]
I'm having the same issue with GTK.

**Comment by jsuarezruiz** [comment]
I have the feeling that it is related to https://github.com/xamarin/Xamarin.Forms/issues/4713
Let's review this to try to fix the Issue.

**Comment by VladislavAntonyuk** [comment]
@knocte , still broken on the latest night build

**Comment by nels83** [comment]
I had the same problem, does this commit : https://github.com/nels83/Xamarin.Forms/commit/627c7838f6931473faa2d43c0bb4ce62cb9f5ade fixes it for you ?

**Comment by VladislavAntonyuk** [comment]
4.2.0.539943-nightly still broken

**Comment by knocte** [comment]
@VladislavAntonyuk the commit that @nels83 asked you to test is not in Xamarin.Forms master, but his fork.

**Comment by VladislavAntonyuk** [comment]
@nels83 , @knocte yes, the yor commit fixes the problem

**Comment by knocte** [comment]
This issue can be closed then, as it was merged in master here: https://github.com/xamarin/Xamarin.Forms/commit/7a1434b74784853cd1ddeb1746b4e6327faa0acc

**Comment by jfversluis** [comment]
Strange, this issue should've been closed when merging the PR. Well, here we go!

**Comment by knocte** [comment]
> this issue should've been closed when merging the PR

For that to happen, the commit message needs to include the string "fixes #4409" (note I said the commit message, not the PR description).

**Comment by VladislavAntonyuk** [comment]
@jfversluis , Please reopen the issue. it is only half fixed.
@nels83 The issue is fixed for the master page. 
Steps to reproduce.
1. On master page and detail page add a button to the navigation bar
2. navigate from master page to detail page. Navigation bar is displayed (as expected)
3. Click on the back button and navigate again to the detail page

AR: Navigation bar is not displayed
ER: Navigation bar is displayed

**Comment by knocte** [comment]
@VladislavAntonyuk if yours are different steps to reproduce than the OP's, then it's a different bug, please open a new one.
