### ISSUE TITLE
DatePicker.MinimumDate misbehaves when data-bound

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#4413]
### Description

When a DataPicker's MinimumDate property is bound to a DateTime property on a page, and that property's value is assigned in code, the DatePicker's Date property is incorrectly assigned the value as well.

Assigning MinimumDate in code, without a binding, works fine.

### Steps to Reproduce

1. Set up a DatePicker with Date bound to property D and MinimumDate bound to property MD
2. Assign D = 11/23/2018
3. Assign MD=11/15/2018

Observe that D is incorrectly set to 11/15/2018.

### Expected Behavior

MinimumDate should only influence Date when less then Date.

### Actual Behavior

Date is reset to MinimumDate even when greater than Date.

### Basic Information

- Version with issue: 3.3.0.967583
- Last known good version: ?
- IDE: VS 2017 15.9
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 27.0.2.1
- Nuget Packages: Many
- Affected Devices: Android

### Reproduction Link

Same issue as https://github.com/xamarin/Xamarin.Forms/issues/3556#issuecomment-432304334

**Comment by kingces95** [comment]
Please include a reproduction and re-open. That way we can be sure we're issuing the initialization in the same order.

**Comment by mfeingol** [comment]
No longer able to reproduce this, sorry.
