### ISSUE TITLE
Enable binding of View Model (BindingContext) methods, just like properties

### ISSUE THREAD

**Issue by buzzware** [xamarin/Xamarin.Forms#4415]
XAML templates currently bind :
1) properties
2) events to code-behind handler methods
3) commands

Commands are very verbose, typically involving a whole new file and class that must be instantiated and bound to a new property, when all we actually want/need is a single method.
Event handler methods are convenient, but only possible in the code-behind. Most professional Xamarin developers use MVVM frameworks, but methods in the BindingContext ie view model cannot be bound to.

# PROPOSAL

Enable binding of event handers and/or commands to simple methods in the BindingContext via some simple syntax in XAML. I'm not sure how exactly is the best way to do it, and there would be many opinions about this. My main concern is that become possible in some form, and the details can be worked out in this issue.

**Comment by andreinitescu** [comment]
@buzzware That can be done in different ways by ways of attaching to the element or extending XAML:
- Event trigger, see [EventTrigger](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers#event-triggers) and implementation in UWP [here](https://github.com/Microsoft/XamlBehaviors/wiki/CallMethodAction) which you can easily port
- Behavior, see [here](https://www.davidbritch.com/2016/04/xamarinforms-behaviors.html)
- A custom attached bindable property
- A custom Markup extension

**Comment by StephaneDelcroix** [comment]
binding to events and to methods is a capability ox `x:Bind` we consider porting to our `Binding` and compiled bindings.

**Comment by andreinitescu** [comment]
I've never seen the "proposal-accepted" tag before. Does this mean only the enhancement issues with "t/enhancement" tag are accepted? Not to mention there's also "up-for-grabs" tag too.
For someone who wants to contribute it's not clear at all which enhancement got green light...

**Comment by StephaneDelcroix** [comment]
@andreinitescu  in doubt... ask

enhancement/bug qualifies the type of ticket. Not all enhancements can be accepted. this one is :)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
