### ISSUE TITLE
iOS: ListView in TabbedPage make bottom area dead touch

### ISSUE THREAD

**Issue by Ngoc-Quang** [xamarin/Xamarin.Forms#4417]
Hello,

Same as the title: I meeting issue when use listView in Tabbedpage. Bottom area "dead touch" about 10% page's height.

I found issue same as this: https://forums.xamarin.com/discussion/97177/tabbedpage-masterdetailpage-listview-resulting-in-dead-touch-area-on-ios
But have no solution now.

MasterDetailPage.Detail > TabbedPage > NavigationPage > NavigationPage > ListViewpage > listview

Could you please help me check and suggest resolution to fix it?
Thanks.

### Basic Information

- Version with issue: 3.3.0.967583
- Last known good version: Unknown
- Platform Target Frameworks: 
  - iOS:  XCode version 9.4
  - Android: good working

- Affected Devices: emulator and real device 

### Screenshots

![listview](https://user-images.githubusercontent.com/26499058/48531978-0f75fe00-e8d1-11e8-9fb6-8442d93c073b.PNG)

**Comment by Ngoc-Quang** [comment]
Resolved:

MasterDetailPage.Detail > TabbedPage > NavigationPage > NavigationPage > ListViewpage > listview
change to :
MasterDetailPage.Detail > NavigationPage > TabbedPage > NavigationPage > ListViewpage > listview

**Comment by nileshrppatel** [comment]
@Ngoc-Quang thanks for the solution.
