### ISSUE TITLE
[macOS] DisplayAlert invisible first time (Mojave Dark Mode)

### ISSUE THREAD

**Issue by Abhijit-Revamp** [xamarin/Xamarin.Forms#4421]
### Description
Xam.Forms -> DisplayAlert on macOS is not visible first time but UI is blocked (modal).
Subsequent times the display is as expected.

### Steps to Reproduce
1. macOS Mojave (Dark Mode)
2. Create a macOS project for XamForms
3. In MainPage, on button click invoke the following
```
DisplayAlert("Message", "Hello", "Ok");
```

### Expected Behavior
Modal popup to be visible

### Actual Behavior
First time the popup is not visible but blocks the UI. Pressing Spacebar will dismiss the popup.
See the two images attached. One where you can barely see the outline.
**Note: The screen shots are from actual APP**

### Basic Information

- Version with issue: 3.2
- Last known good version:
- IDE: VS Mac 
- Platform Target Frameworks: 
  - macOS:  10.14.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
<img width="538" alt="displayalert_1" src="https://user-images.githubusercontent.com/44320018/48544461-a51d8780-e8e9-11e8-98f7-1a525427482d.png">
<img width="528" alt="displayalert_2" src="https://user-images.githubusercontent.com/44320018/48544462-a51d8780-e8e9-11e8-831d-0d6a676999c3.png">

**Comment by jfversluis** [comment]
Can't reproduce with the latest versions. Seeing the age of this I will close it for now and assume it's fixed. Happy to be told otherwise.
