### ISSUE TITLE
Future proof API for design time rendering

### ISSUE THREAD

**Issue by alanmcgovern** [xamarin/Xamarin.Forms#4429]
We have been bitten several times by API removals in forms. This is the most recent occurrence of the problem https://github.com/xamarin/Xamarin.Forms/pull/4355 .

Rather than invoking APIs directly as we have been doing in the past, would it be possible to provide a static class which encompasses every invocation we need? This insulates us from changes to APIs and allows Forms a bit more leeway in making internal changes. It could also make it a little easier to make versioned changes to the API.

**Comment by StephaneDelcroix** [comment]
make a proposal
