### ISSUE TITLE
Binding not working in titleview using xamarin.forms ios but works in android

### ISSUE THREAD

**Issue by tp16190** [xamarin/Xamarin.Forms#4430]
I am using xamarin.forms (3.3.0.967583) version for developing application. In one of my page I am displaying dynamic content to label inside titleview using mvvm binding. It works fine in android but not in ios. I also see other related issues but not helping. See below sample code.

`<NavigationPage.TitleView>
        <StackLayout HorizontalOptions="Start" VerticalOptions="Center" Margin="0" Padding="{OnPlatform iOS='25,0,0,0', Android=0}">
            <Label Text="{Binding SelectedProduct.Title,Mode=TwoWay}" TextColor="White" FontSize="{StaticResource LargeFontSize}" FontFamily="{StaticResource OpenSansRegular}" VerticalTextAlignment="Center" />
        </StackLayout>
    </NavigationPage.TitleView>`

**Comment by kingces95** [comment]
```
<NavigationPage.TitleView>
    <StackLayout 
        HorizontalOptions="Start" 
        VerticalOptions="Center" Margin="0" 
        Padding="{OnPlatform iOS='25,0,0,0', Android=0}">
        
        <Label 
            Text="{Binding SelectedProduct.Title, Mode=TwoWay}"
            TextColor="White" FontSize="{StaticResource LargeFontSize}" 
            FontFamily="{StaticResource OpenSansRegular}" 
            VerticalTextAlignment="Center" />
    </StackLayout>
</NavigationPage.TitleView>
```

**Comment by kingces95** [comment]
I'm unable to reproduce this behavior. Please attach a full zipped solution project and re-open. Thanks!
