### ISSUE TITLE
MasterDetailPage default icon not showing up in iOS

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#4437]
### Description
I have Xamarin.Forms project. I am making `MasterDetailPage`. It is working as expected in Android but when it comes to iOS, not showing default hamburgur icon at top left.  This is my code below

```
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestProjectXamarin" 
             xmlns:Vms="clr-namespace:TestProjectXamarin.ViewModel"      
             x:Class="TestProjectXamarin.MainPage">
    <MasterDetailPage.Master >
        <ContentPage  Title="Master page" BackgroundColor="Red">
            <StackLayout BackgroundColor="Red">
                <StackLayout Margin="25,10,25,0" Padding="0,30,0,0">
                    <Image  BackgroundColor="Accent" Aspect="AspectFill" Source="Enrich.png"></Image>
                </StackLayout>
                <StackLayout  Margin="20,10,20,0" >
                    <Button  Margin="20,5,20,0"   Command="{Binding CommandMenu1}"  HorizontalOptions="FillAndExpand" Text="Games"></Button>
                    <Button  Margin="20,0,20,0"  Command="{Binding CommandMovies}"  HorizontalOptions="FillAndExpand" Text="Movies"></Button>
                    <Button  Margin="20,0,20,0"   HorizontalOptions="FillAndExpand" Text="Setting"></Button>
                </StackLayout>
            </StackLayout>
        </ContentPage>
    </MasterDetailPage.Master>
    <MasterDetailPage.Detail>
        <ContentPage>
            <StackLayout>
            </StackLayout>
        </ContentPage>
    </MasterDetailPage.Detail>
        
</MasterDetailPage>

```

### Steps to Reproduce

1. Create Xamarin.Forms project make `MasterDetailPage` 
2. Use code above.
3. 

### Expected Behavior
Expecting humbuger icon for iOS application
### Actual Behavior
Instead of showing hamburger icon, showing Title of `MasterDetailPage`
### Basic Information

Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Affected Devices: iPhone 6s plus iOS 12.1

### Screenshots
![humburger](https://user-images.githubusercontent.com/19743421/48611253-df4f5d80-e9ab-11e8-9b30-8210d4a06769.png)

**Comment by kingces95** [comment]
Please attach a zip of the reproduction solution and re-open. The code does not include the games tab or event handler.

**Comment by arvindrajachourasiya** [comment]
> The code does not include the games tab or event handler.

Is there any relation between GamesTab page & this issue?

**Comment by arvindrajachourasiya** [comment]
Check this repository I have attached & do not close issue without fixing it. Now how can I reopen it or do I need to assign it again?

[TestProjectXamarin.zip](https://github.com/xamarin/Xamarin.Forms/files/2591594/TestProjectXamarin.zip)

**Comment by NickA55** [comment]
Update on this please....
