### ISSUE TITLE
Xamarin.Form Previewer not showing images for iOS

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#4439]
### Description
I am working with Xamarin.Forms previewer on iOS. I have added some icons to iOS Resource folder & 
 did Clean & Rebuild on solution level. Closed & Reopen IDE. After that when opening the same xaml file on **Previewer window**, image not showing up. After executing it image showing in Simulator  Below my code, even if not significant I am giving it

```
<MasterDetailPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestProjectXamarin" 
             xmlns:Vms="clr-namespace:TestProjectXamarin.ViewModel"      
             x:Class="TestProjectXamarin.MainPage">
    <MasterDetailPage.Master >
        <ContentPage Title="☰"  BackgroundColor="Red">
            <StackLayout BackgroundColor="#B2EC5D">
                <StackLayout Margin="25,10,25,0" Padding="0,30,0,0">
                    <Image  BackgroundColor="Accent" Aspect="AspectFill" Source="Enrich.png"></Image>
                </StackLayout>
            <StackLayout  Margin="20,10,20,0" >
                <Button  BackgroundColor="#FFF0F5" Margin="20,5,20,0"   Command="{Binding CommandMenu1}"  
                            HorizontalOptions="FillAndExpand" Text="Games"></Button>
                <Button  BackgroundColor="#FFF0F5" Margin="20,0,20,0"  Command="{Binding CommandMovies}"  
                            HorizontalOptions="FillAndExpand" Text="Movies"></Button>
                <Button  BackgroundColor="#FFF0F5" Margin="20,0,20,0"   HorizontalOptions="FillAndExpand"
                            Text="Setting"></Button>
            </StackLayout>
            </StackLayout>
        </ContentPage>
    </MasterDetailPage.Master>
    <MasterDetailPage.Detail>
        <ContentPage>
            <StackLayout>
            </StackLayout>
        </ContentPage>
    </MasterDetailPage.Detail>
        
</MasterDetailPage>

```

### Steps to Reproduce

1. Create xamarin.forms project
2.  Add images to iOS Resource folder, those are not showing up.
3. 

### Expected Behavior
Images show display

### Actual Behavior
Not displaying
### Basic Information
Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Affected Devices: iPhone 5s 12.1

### Screenshots
**Xamarin.Forms Previewer output**:

![iospre](https://user-images.githubusercontent.com/19743421/48614042-4fadad00-e9b3-11e8-9bf8-f9b63ec1b6f7.png)

**Simulator output**:

![simulatoricon](https://user-images.githubusercontent.com/19743421/48614372-188bcb80-e9b4-11e8-8a3c-59f544394060.png)

### Reproduction Link

> VS bug [#731419](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/731419)

**Comment by alanmcgovern** [comment]
@viniciusjarina looked at this a while ago and the issue can't be reproduced:

![06039a36-1e8f-4314-a235-58f692d3ceed](https://user-images.githubusercontent.com/264396/55549758-879d5e80-56ce-11e9-88c8-de060a5de34a.gif)

Can you share a copy of a project which triggers the issue? Vinicius should be able to use that to diagnose what's going on
