### ISSUE TITLE
iOS tabbed page shows edit button after screen rotation

### ISSUE THREAD

**Issue by jorisvergeer** [xamarin/Xamarin.Forms#4441]
### Description
During a manual monkey test we discovered that on iOS the tabbed page's overflow menu sometimes shows an "Edit" button which is not functional.

### Steps to Reproduce

1. Create a tabbed page with more than 5 sub pages
2. Open the app in portrait
3. Open the overflow menu (notice the absence of an "edit" button)
4. Rotate the phone in landscape (The overflow menu now also closes which is undesirable on itself)
5. Open the overflow menu again (It now shows a non functional edit button)

### Expected Behavior
No edit button

### Actual Behavior
A edit button

### Basic Information

- Version with issue: 3.3
- Last known good version: - 
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices: iPhone

### Screenshots

Here two screenshots, one before rotation and one after rotation

#### Before rotation
![image](https://user-images.githubusercontent.com/1906639/48620757-782cab80-e9a1-11e8-9a17-28f33cb5b643.png)

#### After rotation
![image](https://user-images.githubusercontent.com/1906639/48620787-94304d00-e9a1-11e8-9093-fd6eed92e949.png)

**Comment by kingces95** [comment]
I'm not reproducing the edit button nor the shutting of the overflow menu using this reproduction on iOS 12 device. 

[App56.zip](https://github.com/xamarin/Xamarin.Forms/files/2591399/App56.zip)

**Comment by jorisvergeer** [comment]
Don't close this just yet!!!

Your demo totally has this behavior on my device. An iPhone 6S Plus using iOS 12.1.

https://youtu.be/M6pc_ODvInc

**Comment by rmarinho** [comment]
We need to check why this happens. Since it initially doesn't show, I think it shouldn't show after the rotation.
