### ISSUE TITLE
Listview Onclicked Orange background in Android

### ISSUE THREAD

**Issue by ElsaAM4Y** [xamarin/Xamarin.Forms#4447]
### Steps to Reproduce

1.  Create xamarin.forms project with a listview in it. If you click in the listview to a detailpage the background is a terrible orange color. To work around is not easy. Please make it a general color instead or orange.
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by arvindrajachourasiya** [comment]
Even I face this issue. Whenever clicking on list item it is showing Orange color. When you want to change that orange color you need to write custom render or some tricky logic in shared project. I tried that once doing from shared project. Here 
https://stackoverflow.com/questions/25885238/xamarin-forms-listview-set-the-highlight-color-of-a-tapped-item/53079812#53079812

But the issue with it is, It is not working on just ### Tap when you release cursor/finger that time it is going show you appropriate color. It should be more easy so that people can do from xaml, In both ways when people clicking or releasing finger.
Thank you.

**Comment by samhouts** [comment]
There is a proposed enhancement here (https://github.com/xamarin/Xamarin.Forms/pull/2050), but it is still in progress. Thanks!

**Comment by mohamedDotNet** [comment]
this is so ridiculous that the color is still orange??? the workarounds are too complicated for a simple color change.

**Comment by ElsaAM4Y** [comment]
Go to your Android project, Resources, values and open styles.xml 
Paste in this code:
<item name="android:colorActivatedHighlight">@android:color/transparent</item> 
Problem solved, easy.

**Comment by mohamedDotNet** [comment]
@ElsaAM4Y please be so kind as to give me the full copy and paste, in the styles file?

**Comment by ElsaAM4Y** [comment]
I am trying to paste the code, but it comes out strange. But you go to Android project - resources - values - styles.xml. And then item name="android:colorActivatedHighlight">@android:color/transparent. You do this exactly like the line above between tags.

**Comment by mohamedDotNet** [comment]
@ElsaAM4Y  THANK YOU so much, your input was a great help, my selected item is now transparent which looks A BILLION times better than the hidious orange.  question though say i wish to make it another color can i just say @android:color/pink ?

**Comment by ryanbuening** [comment]
As ElsaAM4Y mentions above. Put the following in styles.xml:

`<item name="android:colorActivatedHighlight">@android:color/transparent</item>`

**Comment by DennisWelu** [comment]
`colorActivatedHighlight` works for normal selection, but the list item turns another color (white for me) when active while showing the context action options (after doing the long press):

![image](https://user-images.githubusercontent.com/2190011/80832699-c4c66f80-8bb2-11ea-81d0-b1858b46b0a4.png)

Is there another style for that state of the item?

**Comment by DaveBrickley** [comment]
Is there any news on when you might be able to address this properly on both platforms please?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
