### ISSUE TITLE
PopModalAsync with older XF does not crash iOS8.1 but latest XF crashes on iOS8.1 but not on iOS12.x

### ISSUE THREAD

**Issue by Paul-GolfingScribe** [xamarin/Xamarin.Forms#4452]
### Description

I have code that employs PopModalAsync and using Xamarin Forms v2.3.4.270 the app does NOT crash with iOS 8.1 If I take that same code and upgrade to the latest Xamarin Forms then the app DOES crash with iOS 8.1 but does not crash with iOS 12.x

### Steps to Reproduce

1. Create iOS XF project
2. Create a Class that makes use of Navigation.PopModalAsync() such as:

public class GolferPage : ContentPage
{
    public GolferPage()
    {
        Label label = new Label();
        label.Text = "Using either Done button causes a crash in iOS 8.1, but not in the latest iOS.  " +
            "However using Xamarin Forms v2.3.4.270 will NOT cause a crash.";

        Button buttonDone = new Button();
        buttonDone.Text = "Done";
        buttonDone.Clicked += async (sender, e) => await DoneAsync();

        AddDoneButton();

        StackLayout stackLayout = new StackLayout
        {
            VerticalOptions = LayoutOptions.StartAndExpand,
            Padding = new Thickness(20),
            Children = {
                label,
                buttonDone
            }
        };

        Content = new ScrollView
        {
            Content = stackLayout
        };
    }

    public void AddDoneButton()
    {
        var btnDone = new ToolbarItem
        {
            Text = "Done",
            Priority = 0
        };

        btnDone.Clicked += async (sender, e) => await DoneAsync();
        ToolbarItems.Add(btnDone);
    }

    protected async Task<Page> DoneAsync()
    {
        return await Navigation.PopModalAsync();
    }
}

3. Run the App on iOS 8.1
4. Activate Navigation.PopModalAsync()
5. Observe the exception thrown

### Expected Behavior

No Exception thrown

### Actual Behavior

Exception is thrown (but on iOS 8.1 and not on later iOS versions, specifically iOS 12)

### Workaround

Setting Content to null in OnDisappearing prevents the exception, for example:

bool shouldDispose = false;
protected async Task<Page> DoneAsync()
{
    shouldDispose = true;
    return await Navigation.PopModalAsync();
}

protected override void OnDisappearing()
{
    base.OnDisappearing();

    if (shouldDispose)
    {
        Content = null;
    }
}

### Basic Information

- Version with issue: 3.3.0.967583
- Last known good version: v2.3.4.270
- IDE: VS Mac
- Platform Target Frameworks: 
  - iOS:  iOS 8.1
- Nuget Packages: Xamarin Forms
- Affected Devices: iOS 8.1

### Reproduction Link

Placed two solutions in https://github.com/Paul-GolfingScribe/PopModalAsyncRegressionDefect

* ToolbarPopBug - uses Xamarin Forms v2.3.4.270 and there is no crash on iOS 8.1
* ToolbarPopBug2Crash - uses Xamarin Forms v3.3.0.967583 and throws ObjectDisposedException on iOS 8.1 but does not with iOS 12.x

### Possible Related Defect
Forum suggestion is that https://bugzilla.xamarin.com/show_bug.cgi?id=57898  Android bug might be related, noting in case the two are caused by the same problem

**Comment by rmarinho** [comment]
Hi, we are not supporting iOS8. Can you try update the device to at least iOS9 ?

**Comment by Paul-GolfingScribe** [comment]
The current documentation states iOS8 and above is supported 
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/installation?tabs=windows#target-platforms

Can you reference documentation stating the supported platform versions with Xamarin Forms versions?
