### ISSUE TITLE
[UWP] Label MaxLines doesn't work

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4458]
### Description
Label MaxLines should display 4 lines and then truncation, but it only shows one line. IF I remove the `LineBreakMode="TailTruncation"` then I get 4 lines.

### Steps to Reproduce
Run this and use the 3.3 page.

https://github.com/davidortinau/TheLittleThingsPlayground/blob/master/TheLittleThingsPlayground/Views/ThreeThreePage.xaml#L37

```
<Label x:Name="TruncatedLabel" MaxLines="4" LineBreakMode="TailTruncation" Text="You should see 4 lines of text and truncation at the end. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam mattis quam non enim pellentesque, ut placerat purus finibus. Nulla quis tincidunt ante. Ut mauris lectus, aliquam a sagittis vitae, consequat eget elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque convallis nunc nisi, a imperdiet elit efficitur et. Duis in lectus mollis, interdum ipsum et, tincidunt orci. Fusce ipsum metus, imperdiet non lacus vitae, facilisis feugiat magna. Nulla volutpat nisl tortor, a consectetur felis consectetur non. Curabitur in enim vulputate sem volutpat bibendum id nec lorem. Mauris laoreet lacus ac volutpat tempus."/>
```

### Expected Behavior
I should see 4 lines ending with truncation "...".

### Actual Behavior
I see 1 line ending with truncation "...".

### Basic Information

- Version with issue: 3.4.0.1008975

### Screenshots

![image](https://user-images.githubusercontent.com/41873/48685016-f04dc980-eb79-11e8-8428-00fbae806887.png)

After removing `LineBreakMode="TailTruncation"`:

![image](https://user-images.githubusercontent.com/41873/48685106-46bb0800-eb7a-11e8-844e-2281108d8cc8.png)

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/master/TheLittleThingsPlayground/Views/ThreeThreePage.xaml#L37

**Comment by jfversluis** [comment]
Found the cause, I'll provide a fix in the coming days

**Comment by CucaMacaii** [comment]
Hello. I am writing this in Oct 2022 and it still happens, exactly as described above - MaxLines="5" without LineBreakMode="TailTruncation" works, but with LineBreakMode="TailTruncation" I only see one line, ellipsized. I expected to see 5 lines, ellipsized. I think that I have the latest updates... or am I missing some update ? Thank you.
