### ISSUE TITLE
[UWP] BoxView CornerRadius doesn't work

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4459]
### Description
When setting the corner radius, UWP doesn't render it.

### Steps to Reproduce
Run this:

https://github.com/davidortinau/TheLittleThingsPlayground/blob/master/TheLittleThingsPlayground/Views/ThreeTwoPage.xaml#L86

```
<BoxView FlexLayout.AlignSelf="Center"
                     BackgroundColor="#CC3300"
                     WidthRequest="200"
                     HeightRequest="100"
                     CornerRadius="10,0,0,10"
                     />
```

### Expected Behavior

Top left and lower right corners should be rounded.

### Actual Behavior

They are not rounded.

### Basic Information

- Version with issue: 3.4.0.1008975

### Screenshots

![image](https://user-images.githubusercontent.com/41873/48685417-c1d0ee00-eb7b-11e8-8b34-5f94376b7bf7.png)

Android showing what is expected:

![image](https://user-images.githubusercontent.com/41873/48685419-cac1bf80-eb7b-11e8-84e3-1a5d5cf31e16.png)

### Reproduction Link

https://github.com/davidortinau/TheLittleThingsPlayground/blob/master/TheLittleThingsPlayground/Views/ThreeTwoPage.xaml#L86

**Comment by rmarinho** [comment]
If you use Color it works, but it doesn't render as it should . should be just 2 rounded corners. 

<img width="969" alt="capture" src="https://user-images.githubusercontent.com/1235097/48951758-abd67b00-ef37-11e8-9a77-e0dee23e0828.PNG">

**Comment by JohnHair** [comment]
UWP, BoxView is ignoring corner radius. Specifying a colopur makes no difference.
Is this going to be fixed? I am seeing this in the latest XF nugets 4.1.0.673156.

**Comment by bmacombe** [comment]
Submitted a PR that I think will address this, but needed to use a Border to get control over individual corner radius instead of the current UWP rectangle.
