### ISSUE TITLE
Is AppCompat pretty much required these days for XF?

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#4464]
After scanning the source, I think the new Page.TitleView requires AppCompat??  Why is that?  If I only care about the later API versions and don't need to be backwards compatible with earlier Android versions, should I be able to use non-AppCompat for my MainActivity.cs?

**Comment by rmarinho** [comment]
Hi, it allows you to use these new features on old devices. Imagine you wrote an app with all brand new API for API28 and then the user install's in a API15 device, you don't want ti to crash. AppCompact helps by making these api work or don't crash, as well as introduce new apis.

As rule you want to be on AppCompact on XamarinForms.
