### ISSUE TITLE
UWP frozen when set application mainpage after update to Xamarin.forms 3.4

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#4465]
Hi
After Update Nuget to Xamarin,forms 3.4,

UWP app'll be frozen (or it has been crashed?) after set the application.current.mainpage twice:
code here :

[MDXamarinSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2593913/MDXamarinSample.zip)

No error can be catch
![qq 20181119134252](https://user-images.githubusercontent.com/16309962/48688403-0c487e00-ec01-11e8-97a7-5331a55f9e42.jpg)

app.cs code:
`MainPage = new NavigationPage(new LoginPage());`

loginpage.cs code:
```
private void LoginBtn_Clicked(object sender, EventArgs e)
        {
            try
            {
                Application.Current.MainPage = new NavigationPage(new MainPage());
            }
            catch (Exception ex)
            {
                var eb = ex;
            }
        }
```

**Comment by rmarinho** [comment]
You are trying to wrap an `MasterDetailPage` in a `NavigationPage` . 

If you change to this, it works.  
```
 Application.Current.MainPage = new  MainPage();
```

Please reopen if you still have issues. 

Thanks

**Comment by jingliancui** [comment]
@rmarinho  Hi
I know that Xamarin.forms suggest we should not use a navigation page wrap the masterdetailpage，but that is not flexible for a product.
Sometime I want use these for some product scene,And this work fine in android I tested which is Xamarin.forms 3.4. 
And I know this feature is supported in uwp in Xamarin.forms 3.3.

**Comment by rmarinho** [comment]
From the documentation regarding `MasterDetailPage`

"Developers should only use master detail pages as the application root page."
​
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.masterdetailpage?view=xamarin-forms

Users should try to follow the guidelines we provide for architecturing the app on the better way possible . 
I would recommend users change to have the NavigationPage as the Detail. And you could for exampel show the LoginPage as a Modal page.

**Comment by jfversluis** [comment]
Old issue and seems things are not used as they should. I hope everything works for you by now, closing this one.
