### ISSUE TITLE
Android crash when Updated to Forms 3.4

### ISSUE THREAD

**Issue by KaelSuncaster** [xamarin/Xamarin.Forms#4466]
### Description

Updated project to Xamarin forms 3.4., known working version was 3.1

### Expected Behavior

No Andriod error on startup

### Actual Behavior

Java.Lang.LinkageError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendBatchUpdate(FFIZFFFFFFFF)V"

### Basic Information

[ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.LinkageError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendBatchUpdate(FFIZFFFFFFFF)V"
11-19 08:12:23.510 E/mono-rt ( 4898):   at (wrapper dynamic-method) System.Object.38(intptr,intptr,intptr)
11-19 08:12:23.510 E/mono-rt ( 4898):   --- End of managed Java.Lang.LinkageError stack trace ---
11-19 08:12:23.510 E/mono-rt ( 4898): java.lang.NoSuchMethodError: no non-static method "Lcom/xamarin/forms/platform/android/FormsViewGroup;.sendBatchUpdate(FFIZFFFFFFFF)V"
11-19 08:12:23.510 E/mono-rt ( 4898): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementTracker_AttachTracker.n_onViewAttachedToWindow(Native Method)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementTracker_AttachTracker.onViewAttachedToWindow(VisualElementTracker_AttachTracker.java:31)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.View.dispatchAttachedToWindow(View.java:15406)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2953)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1516)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.Choreographer.doFrame(Choreographer.java:619)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.os.Handler.handleCallback(Handler.java:751)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.os.Looper.loop(Looper.java:154)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at java.lang.reflect.Method.invoke(Native Method)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
11-19 08:12:23.510 E/mono-rt ( 4898): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
11-19 08:12:23.510 E/mono-rt ( 4898):

**Comment by PureWeen** [comment]
Can you try rebuilding the project see if that fixes?
or
- closing VS
- delete bin/obj
- open VS
- try again?

**Comment by KaelSuncaster** [comment]
Cheers, the above resolved the crash.
