### ISSUE TITLE
Xamarin.iOS Tabbed Page tabs bar disappear after PopAsync()

### ISSUE THREAD

**Issue by RushAid93** [xamarin/Xamarin.Forms#4467]
### Description
I have a TabbedPage that contains 3 pages (Page 1, Page 2, Page 3). When any tab is selected, the tabs bar which displays all the pages is presented. Then I add a NavigationPage on top of the TabbedPage. After that, when I remove the page using PopAsync / press back button, and select other tab in the TabbedPage, the tabs bar disappear, which is not supposed to happened.

Note: This is only happened in iOS. On Android, the tabs bar works normally.

### Steps to Reproduce
1. Create a TabbedPage as the root page.
2. Add a NavigationPage to the navigation stack (use PushAsync other page).
3. Clear the most top page in the navigation stack (use PopAsync).
4. Select other tab in the root TabbedPage, and the tabs bar is disappear.

### Expected Behavior
The tabs bar is expected to be displayed permanently.

### Actual Behavior
The tabs bar is gone in iPhone

### Basic Information
- Version with issue: Xamarin.Forms 3.4.0.1008975
- IDE: Visual Studio for Mac 7.6.11
- Platform Target Frameworks: 
  - iOS:  Version 12.2.1.10 (Visual Studio Community), Xcode 10.1 (14460.46)
- Nuget Packages: Version 4.3.1.4445
- Affected Devices: All iPhone (simulator and devices)

### Reproduction Link

I have uploaded a very simple project in this repository that demonstrates this problem below
https://github.com/RushAid93/xamarin_testing.git

**Comment by rmarinho** [comment]
Hi @RushAid93 I have tried your sample , . I tried to reproduced but it wasn't able to :

Clicked the label to push a new page.
New page was pushed on 1st tab.
Click "Click Here" to pop the page.
Page pops and goes back to 1st tab. 
Click the other tabs all work. 

Am I missing something. here's the updated sample .

[xamarin_testing-master.zip](https://github.com/xamarin/Xamarin.Forms/files/2608869/xamarin_testing-master.zip)

**Comment by RushAid93** [comment]
> Hi @RushAid93 I have tried your sample , . I tried to reproduced but it wasn't able to :
> 
> Clicked the label to push a new page.
> New page was pushed on 1st tab.
> Click "Click Here" to pop the page.
> Page pops and goes back to 1st tab.
> Click the other tabs all work.
> 
> Am I missing something. here's the updated sample .
> 
> [xamarin_testing-master.zip](https://github.com/xamarin/Xamarin.Forms/files/2608869/xamarin_testing-master.zip)

Are you test this on Android? On Android it works just fine. This is happened only in iOS, all devices and simulators in iOS.

**Comment by samhouts** [comment]
Instead of overriding `OnCurrentPageChanged()`, attach an event to `CurrentPageChanged` and move your code there. You're trying to get the `CurrentPage` too early in the override. Thanks!

**Comment by gentilijuanmanuel** [comment]
Hi, @RushAid93 . I cloned your solution and tried it on iOS. The tabs bar does not disappear after doing what you describe. What really disappears is the Navigation bar, and that's because when you call `NavigationPage.SetHasNavigationBar()` method, you're passing `false` to Page 1 and `true` to the other pages (MainTab.xaml.cs, line 31).

**Comment by RushAid93** [comment]
Hmm, really? That is weird. May I know your Xamarin.Forms version ?

**Comment by Eldin66** [comment]
I am getting this behavior as well. I will provide a sample in a couple hours.
