### ISSUE TITLE
Xamarin.Forms built from source missing UWP WindowsPage

### ISSUE THREAD

**Issue by davidpsaylor** [xamarin/Xamarin.Forms#4472]
### Description
Hello, I'm trying to build Xamarin.Forms to debug some binding exceptions I was getting while migrating PCL to .NET Standard.

I followed the instructions at "Debugging Xamarin Open Source Frameworks: Part 1 – Xamarin.Forms". The machine is Windows 10 Version 10.0.17134 Build 17134, building source code from github with tag release-3.3.0-sr1.2 (commit 9e72c50). The compile completes just fine, and I made the local nuget repository and linked it to the solution.

I get just one compile error:

\obj\x86\Debug\MainPage.g.i.cs
namespace MyProject.NETCore.UWP
{
partial class MainPage : global::Xamarin.Forms.Platform.UWP.WindowsPage
{

Severity Code Description Project File Line Suppression State
Error CS0234 The type or namespace name 'UWP' does not exist in the namespace 'Xamarin.Forms.Platform' (are you missing an assembly reference?) MediView.Mobile.NETCore.UWP C:\git\MEDIVIEW\MediView.Mobile.NETCore\MediView.Mobile.NETCore.UWP\obj\x86\Debug\MainPage.g.i.cs 13 Active

I've tried cleaning, rebuilding, unlinking, linking directly, nothing seems to help. The Xamarin.Forms.Platform DLL is in the nuget package. Any idea why it wouldn't be recognized?

### Steps to Reproduce

1. Git clone Xamarin.Forms repository.
2. Checkout tag release-3.3.0-sr1.2 (commit 9e72c50).
3. Build the project.
4. Run the .create-nuget.bat
5. Create local 

### Expected Behavior

Self-compiled nuget package should be drop-in replacement for actual nuget package.

### Actual Behavior

Compiler complains on missing class Xamarin.Forms.Platform.UWP.WindowsPage.  

### Basic Information

- Version with issue:
- Last known good version: None
- IDE: Visual Studio 2017 15.9.1 (latest)
- Platform Target Frameworks: 
  - UWP:  16299
- Android Support Library Version:  N/A
- Nuget Packages: Self-hosted
- Affected Devices: Windows computer

**Comment by YGuerin** [comment]
Some informations given here : https://forums.xamarin.com/discussion/comment/355515
(but I assume that the author of this issue and from the post is actually the same person)

**Comment by jfversluis** [comment]
I think this should be resolved by now :)
