### ISSUE TITLE
AppLinks doesnt work on iOS

### ISSUE THREAD

**Issue by pmahend1** [xamarin/Xamarin.Forms#4478]
### Description
I am using Deeplinking in iOS version 12.1 Simulartor ,app links does get created but ```OnAppLinkRequestReceived``` doesnt get hit 

Related links :
- [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/deep-linking](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/deep-linking)
- [https://www.youtube.com/watch?v=UJv4jUs7cJw](https://www.youtube.com/watch?v=UJv4jUs7cJw)

### Steps to Reproduce

1. Create a new project 
2. Add code to create App-links 
3. In simulator go to search view - enter the same URL
--or--
Open it from some other app , like - iMessages

4. Search bar should preview the App link but does not

I have not linked it with Azure but I think it should show as indexed URL 

### Expected Behavior
App links indexed should be shown on iOS 

### Actual Behavior
App links not shown

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: NA 
  - UWP:  NA  
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices:

### Reproduction Link

Reproduced repo : [DeeplinkingiOSIssue](https://github.com/pmahend1/DeeplinkingiOSIssue)

**Comment by rmarinho** [comment]
Hi @pmahend1 I think that doc might not be updated, to integrate with website you need a set of other requirements. Do you have AASA (apple-app-site-association) file on your website? via https? You also will need to set associated domains in the app configuration on apple.developer portal as well as in the  app itself on Entitlements list. Do you have the requirements ? 

Heres some good post explaining :
https://medium.com/@abhimuralidharan/universal-links-in-ios-79c4ee038272

**Comment by pmahend1** [comment]
The document clearly states "On the iOS platform, there's no additional setup required to use this functionality.". I think this was for iOS version 9 or below. I read that from version 9 Apple enabled Universal linking which does require, AASA and website set up.  I was expecting at least app URL indexing to work per Deeplinking documentation (thought it was local)

There were issues with Android deeplinking too which I notified at [Xamarin.forms-samples](https://github.com/xamarin/xamarin-forms-samples/issues/368) but still its pending too.

My question is does this Deeplinking i.e Xamarin.Forms.Applinks do work with latest iOS versions with these other set-ups for universal linking?

**Comment by rmarinho** [comment]
@pmahend1 i have talked with docs team and they are preparing a new sample.

@davidbritch can you please notify here when we release the new docs / sample for this.

Thanks

**Comment by pmahend1** [comment]
**Update :** I followed this link for [Universal links on iOS with Xamarin forms](https://marcofolio.net/ios-universal-links-xamarin-forms-asp-net-core/) , Still ```OnAppLinkRequestReceived``` doesnt get hit. I did create a website from Azure and deployed with a valid ```AASA``` file and tested on real device.

**Comment by davidbritch** [comment]
Updated the doc and sample a few weeks ago.

**Comment by faceoffers28** [comment]
@pmahend1 and @rmarinho I can confirm that this is not working in my Xamarin.Forms iOS app. Universal Links used to work before my upgrade to the iOS 12.1 SDK. In fact, I just upgraded from XF 2.5.1.444934 to 3.6.0.264807 thinking this might fix the problem. My test device is an iOS 6S running 12.1.4. It works just fine on Android. Just tested using this link (http://branch.io/resources/aasa-validator/) and everything is still Green. Please advise.

**Comment by Bridgerz** [comment]
I am also having problems setting up Universal Links on my Xamarin.Forms iOS  app. Added the apple-app-site-association file to my site and added the domain to the associated domains in my Entitlements.plist. Deep Linking is working fine for Android but iOS is causing me a lot of issues.

**Comment by VladislavAntonyuk** [comment]
I get it called on iOS by
```xml
public override void PerformActionForShortcutItem(UIApplication application,
            UIApplicationShortcutItem shortcutItem,
            UIOperationHandler completionHandler)
        {
            if (!string.IsNullOrEmpty(shortcutItem?.Type))
            {
                Xamarin.Forms.Application.Current.SendOnAppLinkRequestReceived(new Uri(shortcutItem.Type));
            }
        }
```

**Comment by xleon** [comment]
`Xamarin.Forms.Application.Current.SendOnAppLinkRequestReceived` is not getting called when it should in iOS. 

As a workaround I had to override this method in `AppDelegate`: 

```
public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
        {
            var uri = new Uri(url.ToString());
            var formsApp = Xamarin.Forms.Application.Current;
            formsApp.SendOnAppLinkRequestReceived(uri);
            
            return true;
        }
```

**Comment by jufergom** [comment]
@xleon Your code just saved my life! Thank you, you are a genius.

**Comment by iBobb** [comment]
Still an issue with Xamarin.iOS 15.4 and Xamarin Forms 5.0.0.2012 testing on Simulator with iOS 15.2. @xleon's workaround worked for me. Thank you.

**Comment by xleon** [comment]
I'm glad my hack helped you out but how is this issue closed? Is there a fix anywhere?
