### ISSUE TITLE
[Android] Localization does not work in release mode with "Bundle assemblies into native code" option enabled

### ISSUE THREAD

**Issue by raphibolliger** [xamarin/Xamarin.Forms#4479]
### Description
Localization does not work in release mode with "Bundle assemblies into native code" option enabled. The app has only 2 languages available after startup. I could not finally figure out which of the languages will be taken and put into the package for Android. As a second language to the default (English) it could be the first RESX file in VS file tree or it could be first RESX file after Resources.resx in VS file tree.
In my eyes there will be bundled only 2 resource files at build time and the others are lost.

The main thing on this issue is that it is reported several times here in Xamarin.Forms and in xamarin.android. As far as I know there is no proper solution or fix for this and other people also asking for help. It is happening only in a enterpise environment and is blocking us to ship a clean working solution to our customers.

Laguage switch is working fine with the workaround described later and also in debug mode.

#### Demo project
https://github.com/raphibolliger/XamarinLocalizeTest
You can have a look at the view on the running app. Its also a short logging included during app startup which will write a translated (or not) sentence to the console.

#### Workaround
My workaround for this problem is to manually include builded dll's of resources in the Android project via Assets. And then load it on startup in MainActivity. This is not included in the demo project. 

### Steps to Reproduce

1. Build the demo project with "Bundle assemblies into native code" enabled in release mode
2. Start the app
3. Verify the localized sentences

### Expected Behavior
Each sentence should be displayed in a different language.

### Actual Behavior
Actually on my devices (Nexus 5X and Motorola Moto G) Chinese is the only localized sentence.

### Basic Information

- Version with issue: Xamarin.Forms 3.3.0.967583
- Last known good version: none
- IDE: Microsoft Visual Studio Enterprise 2017, Version: 15.9.0
- Xamarin Version: 4.12.3.69
- Platform Target Frameworks: 
  - iOS:  12.2.1.10
  - Android: 9.1.0.38 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 3.3.0.967583
- Affected Devices: Nexus 5X and Motorola Moto G

### Screenshots
| ![img_0235](https://user-images.githubusercontent.com/6289764/48755249-fedcd380-ec94-11e8-8a78-a3a0cbad44ee.png) | ![img_0236](https://user-images.githubusercontent.com/6289764/48755256-02705a80-ec95-11e8-95d1-d63b3386fb04.jpg) |
|---|---|
| DEBUG | RELEASE |
### Reproduction Link
https://github.com/raphibolliger/XamarinLocalizeTest

**Comment by raphibolliger** [comment]
Other issues related to this: (I opened a new issue due to new discoveries)
- https://github.com/xamarin/Xamarin.Forms/issues/1595
- https://github.com/xamarin/xamarin-android/issues/2178

**Comment by rmarinho** [comment]
Let's track all this on #1595
