### ISSUE TITLE
Render GL errors 

### ISSUE THREAD

**Issue by supercotan** [xamarin/Xamarin.Forms#4481]
From time to time I get Open Gl Errors with Xamarin Forms. I use SkiaSharp for rendering. Last versions for both.

**11-19 16:37:13.842 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
GL errors! frameworks/base/libs/hwui/renderthread/OpenGLPipeline.cpp:105**
**11-19 16:37:17.475 E/OpenGLRenderer( 4480): GL error:  GL_INVALID_OPERATION
11-19 16:37:17.475 F/OpenGLRenderer( 4480): GL errors! frameworks/base/libs/hwui/renderthread/OpenGLPipeline.cpp:105**

**Comment by supercotan** [comment]
occurs in both the emulator and the physical device

**Comment by rmarinho** [comment]
Hi we would need more info to properly look better what's going on. Can you please provide more insight in the versions that you are using, what os , and a small repo?
IT would be great if you can fill the template we provide for new issues. it will help us better triage this issue and start working on it. 

Thanks

**Comment by supercotan** [comment]
### Description
From time to time I get Open Gl Errors with Xamarin Forms. The application crash and ends automatically. Previously in the project did not use Admob and the error was the same. Over time it has happened to me several times with both emulators and physical devices. It happens at random.

It even happened to me in a code like this (lblTime is a Label):
                
                while (...)
                {
                    try
                    {
                        await lblTime.FadeTo(0, 500);
                        await lblTime.FadeTo(1, 500);
                    }
                    catch (Exception ex)
                    {
                        break;
                    }
                }

### Steps to Reproduce
I am not able to reproduce it. It happens in a random way, Both in emulators and in physical devices.

### Basic Information

- IDE: Visual Studio 2017 15.9.2
- Platform Target Frameworks: 
  - Android: Min: 5.0. Target: 8.1 
- Nuget Packages: Xamarin Forms 3.4.0.1008975, SkiaSharp 1.60.3, Xamarin.Android.Support 27.0.2.1 (Compat y Annotations), Xamarin.GooglePlayServices.Ads 60.1142.1
- Affected Devices: any



### Part of Debug Trace

11-19 16:36:53.922 I/zygote  ( 4480): Do partial code cache collection, code=243KB, data=115KB
11-19 16:36:53.922 I/zygote  ( 4480): After code cache collection, code=243KB, data=115KB
11-19 16:36:53.922 I/zygote  ( 4480): Increasing code cache capacity to 1024KB
11-19 16:36:54.959 D/Mono    ( 4480): DllImport searching in: '__Internal' ('(null)').
11-19 16:36:54.959 D/Mono    ( 4480): Searching for 'java_interop_jnienv_call_nonvirtual_void_method'.
11-19 16:36:54.959 D/Mono    ( 4480): Probing 'java_interop_jnienv_call_nonvirtual_void_method'.
11-19 16:36:54.959 D/Mono    ( 4480): Found as 'java_interop_jnienv_call_nonvirtual_void_method'.
11-19 16:36:54.967 D/Mono    ( 4480): DllImport searching in: '__Internal' ('(null)').
11-19 16:36:54.967 D/Mono    ( 4480): Searching for 'java_interop_jnienv_call_boolean_method'.
11-19 16:36:54.967 D/Mono    ( 4480): Probing 'java_interop_jnienv_call_boolean_method'.
11-19 16:36:54.967 D/Mono    ( 4480): Found as 'java_interop_jnienv_call_boolean_method'.
11-19 16:36:55.242 D/DynamitePackage( 4480): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
11-19 16:36:55.364 I/Ads     ( 4480): Starting ad request.
11-19 16:36:55.364 I/Ads     ( 4480): This request is sent from a test device.
11-19 16:36:55.562 I/zygote  ( 4480): Background concurrent copying GC freed 20818(1304KB) AllocSpace objects, 12(408KB) LOS objects, 49% free, 2MB/5MB, paused 6.966ms total 149.553ms
11-19 16:36:55.770 I/Choreographer( 4480): Skipped 83 frames!  The application may be doing too much work on its main thread.
11-19 16:36:57.369 W/zygote  ( 4480): JNI RegisterNativeMethods: attempt to register 0 native methods for md58432a647068b097f9637064b8985a5e0.FrameRenderer
11-19 16:36:57.786 I/Choreographer( 4480): Skipped 119 frames!  The application may be doing too much work on its main thread.
11-19 16:36:58.175 I/zygote  ( 4480): NativeAlloc concurrent copying GC freed 2218(467KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 1.243ms total 242.335ms
11-19 16:36:58.603 I/Ads     ( 4480): Scheduling ad refresh 70000 milliseconds from now.
11-19 16:36:58.696 I/Ads     ( 4480): Ad finished loading.
11-19 16:36:58.793 I/Choreographer( 4480): Skipped 59 frames!  The application may be doing too much work on its main thread.
11-19 16:36:58.975 D/Mono    ( 4480): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
11-19 16:36:58.975 D/Mono    ( 4480): Searching for 'sk_paint_set_stroke_width'.
11-19 16:36:58.975 D/Mono    ( 4480): Probing 'sk_paint_set_stroke_width'.
11-19 16:36:58.985 D/Mono    ( 4480): Found as 'sk_paint_set_stroke_width'.
11-19 16:36:58.991 D/Mono    ( 4480): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
11-19 16:36:58.991 D/Mono    ( 4480): Searching for 'sk_path_reset'.
11-19 16:36:58.991 D/Mono    ( 4480): Probing 'sk_path_reset'.
11-19 16:36:58.991 D/Mono    ( 4480): Found as 'sk_path_reset'.
11-19 16:36:58.993 D/Mono    ( 4480): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
11-19 16:36:58.993 D/Mono    ( 4480): Searching for 'sk_path_move_to'.
11-19 16:36:58.993 D/Mono    ( 4480): Probing 'sk_path_move_to'.
11-19 16:36:58.993 D/Mono    ( 4480): Found as 'sk_path_move_to'.
11-19 16:36:58.996 D/Mono    ( 4480): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
11-19 16:36:58.996 D/Mono    ( 4480): Searching for 'sk_path_line_to'.
11-19 16:36:58.996 D/Mono    ( 4480): Probing 'sk_path_line_to'.
11-19 16:36:58.996 D/Mono    ( 4480): Found as 'sk_path_line_to'.
11-19 16:36:59.007 D/Mono    ( 4480): DllImport searching in: 'libSkiaSharp.so' ('libSkiaSharp.so').
11-19 16:36:59.007 D/Mono    ( 4480): Searching for 'sk_path_close'.
11-19 16:36:59.007 D/Mono    ( 4480): Probing 'sk_path_close'.
11-19 16:36:59.007 D/Mono    ( 4480): Found as 'sk_path_close'.
11-19 16:36:59.316 I/Choreographer( 4480): Skipped 30 frames!  The application may be doing too much work on its main thread.
11-19 16:37:00.396 I/Ads     ( 4480): Ad finished loading.
11-19 16:37:00.512 D/Mono    ( 4480): DllImport searching in: '__Internal' ('(null)').
11-19 16:37:00.512 D/Mono    ( 4480): Searching for 'java_interop_jnienv_call_void_method'.
11-19 16:37:00.512 D/Mono    ( 4480): Probing 'java_interop_jnienv_call_void_method'.
11-19 16:37:00.514 D/Mono    ( 4480): Found as 'java_interop_jnienv_call_void_method'.
11-19 16:37:01.255 D/DynamitePackage( 4480): Instantiating com.google.android.gms.ads.ChimeraAdOverlayCreatorImpl
11-19 16:37:01.272 I/Ads     ( 4480): Ad opening.
11-19 16:37:02.742 I/zygote  ( 4480): NativeAlloc concurrent copying GC freed 17663(1190KB) AllocSpace objects, 11(384KB) LOS objects, 49% free, 2MB/5MB, paused 18.457ms total 530.262ms
11-19 16:37:03.209 W/zygote  ( 4480): Attempt to remove non-JNI local reference, dumping thread
11-19 16:37:03.255 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:03.570 I/Choreographer( 4480): Skipped 96 frames!  The application may be doing too much work on its main thread.
11-19 16:37:04.039 W/zygote  ( 4480): Attempt to remove non-JNI local reference, dumping thread
11-19 16:37:04.252 I/zygote  ( 4480): NativeAlloc concurrent copying GC freed 338(77KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 2.438ms total 666.199ms
11-19 16:37:04.273 I/Choreographer( 4480): Skipped 41 frames!  The application may be doing too much work on its main thread.
11-19 16:37:04.404 W/zygote  ( 4480): Attempt to remove non-JNI local reference, dumping thread
11-19 16:37:04.685 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:04.996 I/zygote  ( 4480): NativeAlloc concurrent copying GC freed 1226(142KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 913us total 716.405ms
11-19 16:37:05.166 W/zygote  ( 4480): Attempt to remove non-JNI local reference, dumping thread
11-19 16:37:05.169 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:05.624 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:05.674 I/Choreographer( 4480): Skipped 56 frames!  The application may be doing too much work on its main thread.
11-19 16:37:05.975 W/zygote  ( 4480): Attempt to remove non-JNI local reference, dumping thread
11-19 16:37:05.978 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:06.051 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:06.402 I/zygote  ( 4480): NativeAlloc concurrent copying GC freed 921(174KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 3MB/6MB, paused 1.002ms total 588.419ms
11-19 16:37:13.371 I/Ads     ( 4480): Ad closing.
11-19 16:37:13.411 I/Choreographer( 4480): Skipped 43 frames!  The application may be doing too much work on its main thread.
11-19 16:37:13.414 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:13.562 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
11-19 16:37:13.794 W/zygote  ( 4480): Checksum mismatch for dex base.apk
11-19 16:37:13.796 W/zygote  ( 4480): Checksum mismatch for dex base.apk
11-19 16:37:13.842 D/EGL_emulation( 4480): eglMakeCurrent: 0xc38684a0: ver 2 0 (tinfo 0xbe6c1e10)
**GL errors! frameworks/base/libs/hwui/renderthread/OpenGLPipeline.cpp:105
11-19 16:37:17.475 E/OpenGLRenderer( 4480): GL error:  GL_INVALID_OPERATION
11-19 16:37:17.475 F/OpenGLRenderer( 4480): GL errors! frameworks/base/libs/hwui/renderthread/OpenGLPipeline.cpp:105**

**Comment by samhouts** [comment]
@supercotan There's not much we can do to investigate this issue with the information given. Can you provide the project that you're experiencing this issue with? Thanks!

**Comment by samhouts** [comment]
@supercotan Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
