### ISSUE TITLE
DI containers and IoC principles

### ISSUE THREAD

**Issue by rafsanulhasan** [xamarin/Xamarin.Forms#4485]
### Description
Hello,
I found Prism (with Unity DI container or others) more useful than that of DependencyService in Xamarin because it supports applying IoC principles such as constructor injection. Though, the current built in one is productive, it would be nice if it had a capability of doing such things. I felt the essence of this because it provides a number of flexibility including loosely coupling, test-ability and so on. I can use prism with unity or anything else, but I (and probably other developers in the community out there) would love Xamarin more than ever before if such functionality is incorporated in Xamarin by default because there might be someone out there like me who don't want to rely on third-party libraries rather they rely on Xamarin itself. Additionally it would be great if it has such functionality to integrate with third party libraries for DI containers only like the DI container .NET Core uses by default in ASP.NET Core project.

Thanks in advance.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: Xamarin.Forms
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
Thanks, we already tracking this here #3522 . 
Please provide more of your feedback in that issue please.
