### ISSUE TITLE
Template 10 Hamburger Menu support in Xamarin.Forms

### ISSUE THREAD

**Issue by rafsanulhasan** [xamarin/Xamarin.Forms#4488]
### Description
Hello,
I'm developing a cross-platform app using Xamarin.Forms using .NET Standard as the shared project. During the development I found the essence of a Hamburger Menu similar to one that is used in [Template 10](https://github.com/Windows-XAML/Template10) for UWP. The menu that MasterDetailPage is currently using does not support a collapsed state, it only closes or shown. It it possible to add such feature in Xamarin.Forms? Or can I change the default behavior for MasterDetailPage?

### Steps to Reproduce

1. Create a new Xamarin.Forms project with MasterDetailPage using VS 2017 and run it
2. Click on the Hamburger icon to open it, click on it again 
3. It has been closed or hidden 

### Expected Behavior
The Hamburger menu should have a state "collapsed" that should collapse the menu and show the Icons only so that users can navigate around the other pages of the app 

### Actual Behavior
The Hamburger menu disappears when user clicks outside the menu or click on Hamburger icon 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by rmarinho** [comment]
Hi @radekdoulik thanks for your feedback. I think this could be a good candidate for a `PlatformSpecific` we can't really change the default behaviour as that is a breaking change, but we could introduce a PS that allows user to say the hidden should show as collapsed on UWP.

**Comment by rafsanulhasan** [comment]
Hi @rmarinho, is it possible to have such Hamburger menu in all the platforms?

**Comment by rafsanulhasan** [comment]
@rmarinho what's the status?

**Comment by rafsanulhasan** [comment]
@rmarinho  any update?

**Comment by maexsp** [comment]
This would be great to have it on UWP. Similar to the UWP NavigationView - PaneDisplayMode="LeftCompact"

See https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
