### ISSUE TITLE
[FlexLayout] Grow works on iOS but not Android

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4491]
### Description
I have 3 entries. The first should occupy the full width, and the second and third should occupy a second row. Setting `FlexLayout.Grow=1` on the first works as desired on iOS, but not Android. Perhaps this isn't the best way to do this, but seeing the different on iOS and Android it seems worth looking into to make sure the layout is **consistently** applied on both platforms, even if wrong. 

`FlexLayout.Basis=100%` on the first Entry does produce the layout I want.

```xaml
<FlexLayout Direction="Row" Margin="10" Wrap="Wrap" JustifyContent="SpaceBetween">
                    
                    <Entry
                       Placeholder="Title"
					   PlaceholderColor="Blue"
                       Text="Vintage Dress"
                       BackgroundColor="#ddd"
                       FlexLayout.Grow="1"
                       />
                    
                    <Entry 
                       Placeholder="Price"
					   PlaceholderColor="Blue"
                       Text="$10" 
                       FlexLayout.Basis="30%"
                       BackgroundColor="#ddd"
                       />
                    
                    <Entry 
                       Placeholder="Location"
					   PlaceholderColor="Blue"
                       BackgroundColor="#ddd"
                       FlexLayout.Basis="60%"
                       />
                </FlexLayout>
```

### Expected Behavior
Layouts should be the same.

### Actual Behavior
Layouts are different.

### Basic Information

- Version with issue: 3.4.0 (Visual build)

### Screenshots

<img width="877" alt="screen shot 2018-11-20 at 10 05 07 am" src="https://user-images.githubusercontent.com/41873/48786422-6fdbb580-ecac-11e8-9a7b-f07a77b5f869.png">

**Comment by StephaneDelcroix** [comment]
>Expected Behavior: Layouts should be the same.

Layouts should be the same given the following constraints:
- elements have the same measure on each platform
- available width is the same.

What I see here, despite being very different, is actually correct (the best form of correct) in each case. The point of flex os to be adaptive, and the screenshots shows a good level of adaptiveness.

Achieving grid-like layout in flex is not a given, but it's easy to achieve. refer to the sample here https://gist.github.com/StephaneDelcroix/da29dcbb1a1f7501bab387e76ad0be17#file-grid2-xaml
(also, use CSS)
