### ISSUE TITLE
DatePicker inside TableView raises popup dialogs unexpectedly

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#4494]
### Description
When used inside TableView's ViewCell, a DatePicker will sometimes raise its pop up dialog unexpectedly after its value is changed.

### Steps to Reproduce

1. Run the provided sample app in the Android emulator.
2. Change the start date to 11/26.
3. Change the end date to 11/29.

### Expected Behavior
No further dialogs pop up after user activity has ceased.

### Actual Behavior
After setting the end date, two DatePicker dialogs pop up again without user intervention.

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: Unknown
- IDE: VS 2017 15.9.2
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 27.0.2.1
- Nuget Packages: None
- Affected Devices: N/A

### Reproduction Link

[DatePicker.zip](https://github.com/xamarin/Xamarin.Forms/files/2602868/DatePicker.zip)

**Comment by rmarinho** [comment]
I think #4344  fixes this issue. @paymicro can you confirm?!

**Comment by paymicro** [comment]
Confirmed 💯 #4344 fixes this issue.
