### ISSUE TITLE
ResourceDictionary: InitializeComponent() should be called implicitly if constructor at the code behind class has been missed

### ISSUE THREAD

**Issue by SymmetryKeeper** [xamarin/Xamarin.Forms#4497]
### Description
WPF allows to use xaml-based Resource Dictionaries or another Controls with a missed explicit constructor at the code behind class. In this case `InitializeComponent()` should be called implicitly.

### Steps to Reproduce

1. Add a xaml-based Resource Dictionary with the code behind class
2. Remove an explicit default constructor with `InitializeComponent()` call from the code behind class
3. Try to use the dictionary

### Expected Behavior
Should be initialized properly

### Actual Behavior
Not initialized [can not find values by keys]

**Comment by StephaneDelcroix** [comment]
you can use a Xaml resource dictionary without code behind, or a matching x:Class. But if you choose not to call `InitializeComponent()` you're on your own.... there's nothing we can do

**Comment by SymmetryKeeper** [comment]
@StephaneDelcroix 
Thanks. Yes, I understand.

But I have checked now WPF implementation and looks that WPF call/recall `InitializeComponent()` when we try to use something at XAML even if we missed manually call `InitializeComponent()` at constructor.

Similar approach allows to avoid unobvious and not very necessary exceptions. Seems if you want to save explicit calling of `InitializeComponent()` the exception should correspond an actual reason.

For example, if I missed `InitializeComponent()` instead `KeyNotFoundException` I expect to get a message `Component is not initialized`.

It is just a good practice to avoid unnecessary exceptions or to show actual reasons of them.
