### ISSUE TITLE
BackPressed/OnOptionsItemSelected not invoked when using TabbedPage

### ISSUE THREAD

**Issue by bmaulik** [xamarin/Xamarin.Forms#4503]
### Description
When navigated from a TabbedPage to another page, FormsAppCompatActivity.BackPressed event  or OnOptionsItemSelected method not invoked for toolbar back button in android. However, when pressing hardware back button FormsAppCompatActivity.BackPressed event in invoked.

### Steps to Reproduce
1. Create an new project with Tabbed Forms App Template
2. Override OnOptionsItemSelected method or subscribe to FormsAppCompatActivity.BackPressed event

### Expected Behavior
If OnOptionsItemSelected method is overridden then it should be invoked.
If FormsAppCompatActivity.BackPressed event is subscribed then it should be invoked.

### Actual Behavior
OnOptionsItemSelected method is not invoked.
FormsAppCompatActivity.BackPressed event is not invoked.

### Basic Information
- Version with issue: 3.4
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - Android: 8.1

**Comment by rmarinho** [comment]
This is similar to  #3894 , `FormsAppCompatActivity.BackPressed`is for hardware button. What we need to expose is a better way to intercept the software back button

**Comment by b1mn** [comment]
Any estimation for when it could be done/resolved?

**Comment by pauldiston** [comment]
I believe I am experiencing the same behaviour where all was working fine when my MainActivity inherited from FormsApplicationActivity however I am having issues when my MainAcitivity inherits from FormsAppCompatActivity.

**Comment by bmaulik** [comment]
Closing this out and MAUI is the next version to look at. Hopefully it will have some kind of solution for this.

**Comment by EricPucho** [comment]
For those who still want to intercept software back button action, just implemented the renderer on the platforms (NavigationPageRenderer -> Android & NavigationRenderer -> iOS) and overrided OnPopViewAsync to intercept the action. You can use Page.Title to do specific actions in every ContentPage, TabbedPage etc.

It's worked for both back actions : hardware and software.
