### ISSUE TITLE
[F100] Make Label display HTML from a string

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#4504]
### Rationale

Make Label able to display HTML from HTML string. 

Sure, solutions exist from worse ones (WebView) to better ones (renderers). But it maybe time after so many years to have such a simple feature built in into the framework?

### Implementation
 Every platform has a way to render HTML:

**iOS**: UILabel.AttributedText = new NSAttributedString(...);
**Android**: TextView = Html.fromHtml(html);
**UWP**: TextBlock.Text = Windows.Data.Html.HtmlUtilities.ConvertToText(html);

I don't know exactly what is best way to add this, so it's simple and without adding breaking changes.
Maybe add a new property to Label, something like `Html`:

```
public class Label : ..
{ 
     public string Html { get; set; }  // bindable property
}
```

Setting it would clear the content of the existing `FormattedText` property. Same happens the other way, setting `FormattedText` clears out the `Html` property. Normally there's no logical reason for someone to use both properties, but even if he\she does it, it will work OK by both properties being mutually exclusive.

This is backward compatible, it's simple to use and implement.

**Comment by jfversluis** [comment]
Just opened a PR for this.

> UWP: TextBlock.Text = Windows.Data.Html.HtmlUtilities.ConvertToText(html);

This doesn't show it as HTML. It strips all the tags and shows you the plain text. There is nu built-in support for UWP to show HTML formatting.

**Comment by davidortinau** [comment]
@jfversluis yeh, Forms would need to parse that for UWP like: https://github.com/matteobortolazzo/HtmlLabelPlugin

**Comment by jfversluis** [comment]
> @jfversluis yeh, Forms would need to parse that for UWP like: https://github.com/matteobortolazzo/HtmlLabelPlugin

Pinged the guy if he would mind if I take his code as a starting point for that. Even if we do. I'm not sure if this will be a real addition. It might cause more trouble than anything else. People will come and ask why HTML tag x is not supported. Or images aren't working or links, etc. Support for HTML tags will not be consistent across platforms. So, I think you are discussing this internally, and of course, it's up to you guys ultimately, but I think there are some things to consider here.

**Comment by matteobortolazzo** [comment]
@jfversluis No problem, use my UWP code :) However, I don't think implementing HTML rendering is a good idea. As @jfversluis said, people will open issues on why Android doesn't display images or lists. iOS doesn't support hyperlinks out of the box, the implementation breaks with custom fonts. On UWP you can't parse every tag or match every CSS property to a TextView property. The same HTML/CSS can be very different across different OSs. For things like lists on Android, you can implement custom rendering on top of the official one, but there are a lot of other tags, Html.fromHtml(html); is not enough.

**Comment by andreinitescu** [comment]
Native APIs do not handle all possible tags anyway, the docs mention this, so I don’t see why someone would expect Xamarin Forms to do more than what the native does.
The purpose of this feature is to allow simple rich text to be displayed by label. Maybe “Html” is not best name for the property.
As long as documentation clearly states the native API on which the implementation is based on, it should be OK, so that developer doesn’t have to dig into the XF code to find out. Beside that, people will always complain anyway.

**Comment by jfversluis** [comment]
Sure, we can do it and manage expectations. But I’m not sure if it’s worth the hassle. You can do all kinds of formatting with the spans now and if you really want to view some piece of html you will probably use the WebView.

Just wondering what would be the real added value and how many people do actually want to use this? And how much effort will it cost to test all kinds of scenarios for this and maintain this while in practice it’s like IE6 all over again in a Label control.

**Comment by andreinitescu** [comment]
I find WebView very heavy for this job, it’s really not a good idea. 
Except maybe UWP all platforms have a way to display rich text in a label. I think UWP has a way too, I will investigate.
One example of a scenario is when you have rich text coming from backend.

**Comment by andreinitescu** [comment]
What scenarios are you thinking when you say “test all scenarios” I don’t understand. XF does what the native does, it’s simple

**Comment by andreinitescu** [comment]
XF just forwards to native. Your example with MaxLines should work just how native works in combination with the corresponding feature which sets html. 
In regards with uwp, I was thinking if it wouldn’t be possible to use the new Visual feature and switch the renderer when “Html”property gets set. 
I wish the “FormattedText” property on label returned an interface instead of the FormattedString. If you look to native you can see the need for this.
