### ISSUE TITLE
[Feedback] VS2017 enterprise check Budle Assemblies into Native Code, Localization not work

### ISSUE THREAD

**Issue by grendello** [xamarin/Xamarin.Forms#4515]
_From @PureWeen on September 11, 2018 21:35_

_From @samhouts on September 5, 2018 19:8_

### Reproduction
[TodoLocalized.zip](https://github.com/xamarin/xamarin-android/files/2372808/TodoLocalized.zip)

If you set the Android project configuration to 
Release Mode and check "Bundle assemblies into native code" then localization doesn't work
if you uncheck  "Bundle assemblies into native code" then localization works

1) on the first page there's a picker at the top you can click to select different languages
2) select a different language
3) click on the PLUS arrow to go to the second page
4) the text on the buttons should now be in the language you selected

This has come up before
https://stackoverflow.com/questions/43787461/localization-doesnt-work-using-bundle-assemblies-into-native-code-in-release
https://bugzilla.xamarin.com/show_bug.cgi?id=55603

### Description From Dev Community

<p>xamarin.forms , Currently when build release Xamarin Android Apk then install app on device,it is run well ,but Localization is not work, it is only show system language(chinese) and english,when I change language to Korean ,it is show english not
Korean .
when i not check Budle Assemblies into Native Code,it is run well for Localization .

project  See Attachment

Steps:
1.select release mode,check Budle Assemblies into 
   Native Code ,then generate project
2.Archive the project and distribute
3.Install app on device,then open app, change 
   language

hope get help,thanks!</p>
<a href="https://developercommunity.visualstudio.com/content/problem/267954/vs2017-enterprise-check-budle-assemblies-into-nati-1.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/627183">original linked feedback ticket</a>.

### Source

[661459](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/661459)

_Copied from original issue: xamarin/Xamarin.Forms#3718_

_Copied from original issue: xamarin/xamarin-android#2178_

**Comment by grendello** [comment]
_From @jonpryor on September 12, 2018 1:36_

@grendello: Did we ever get around to doing the Android side of mkbundle+satellite assemblies, e.g. 
https://bugzilla.xamarin.com/show_bug.cgi?id=11430?

**Comment by grendello** [comment]
Loading of satellite assemblies from the bundle works as expected (that's with XA/master):

```
09-17 16:03:48.941 15877 15877 I monodroid-assembly: open_from_bundles: looking for bundled name: 'de/TodoLocalized.resources.exe'
09-17 16:03:48.941 15877 15877 D Mono    : Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-x86-debug/lib/TodoLocalized.resources.dll'.
09-17 16:03:48.941 15877 15877 D Mono    : Assembly Loader probing location: '/Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/sdks/out/android-x86-debug/lib/TodoLocalized.resources.exe'.
09-17 16:03:48.941 15877 15877 D Mono    : Assembly Loader probing location: 'de/TodoLocalized.resources.dll'.
09-17 16:03:48.941 15877 15877 D Mono    : Unloading image TodoLocalized.resources.dll [0xcdd2e600].
09-17 16:03:48.941 15877 15877 D Mono    : Assembly Loader loaded assembly from bundle: 'de/TodoLocalized.resources.dll'.
```

And also, when the app is first started - **before changing the locale from the drop-down** - the UI that shows up after clicking the `plus` button is in  Korean (which is expected from looking at the source code). I think the mechanics of loading satellite assemblies from the bundle work fine and the issue is somewhere else. I'll keep investigating.

**Comment by grendello** [comment]
I reused test case from [an old bug](https://bugzilla.xamarin.com/show_bug.cgi?id=55603) to see if i18n works in a "plain" Android app and have confirmed that it does work as expected - satellite assemblies are loaded from the app bundle and translations are applied. Here's a screenshot of the test app from the bug report running in the emulator: 
![screenshot_1537260022](https://user-images.githubusercontent.com/184788/45675342-76747200-bb2f-11e8-84f8-85e2a1c2b9fd.png)
The code which sets the locale in the above project is very simple:

```csharp
public class Activity1 : Activity
        {
                ResourceManager _manager = new ResourceManager ("I18nResourcesBug.strings", typeof(Activity1).Assembly);

                protected override void OnCreate (Bundle bundle)
                {
                        base.OnCreate (bundle);

                        // Set our view from the "main" layout resource
                        SetContentView (Resource.Layout.Main);

                        TextView text = FindViewById<TextView> (Resource.Id.cultureName);
                        text.Text = "Current culture: " + CultureInfo.CurrentUICulture.Name;

                        text = FindViewById<TextView> (Resource.Id.myText1);
                        text.Text = MyResources.ResAccessor.GetString ("MY_STRING");

                        text = FindViewById<TextView> (Resource.Id.myText2);
                        text.Text = _manager.GetString ("MY_STRING");

                        var c = CultureInfo.GetCultureInfo ("fr-CA");
                        text = FindViewById<TextView>(Resource.Id.myText_fr);
                        text.Text = _manager.GetString ("MY_STRING", c);
                }
        }
```

All put together, it leads me to think that the bug is in `Xamarin.Forms` (resource caching perhaps?) since the code in the sample application attached by @PureWeen appears to be correct *and* the localization works initially as pointed out before.

**Comment by grendello** [comment]
_From @pooran on October 19, 2018 16:16_

Any update on this?

**Comment by rmarinho** [comment]
Follow up on #4479
