### ISSUE TITLE
Binding to an empty collection with indexing throws unhandled exception

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#4516]
### Description

Binding to an empty collection when path is using property index throws unhandled exception. 

The documentation doesn't say what's the expected behavior for this scenario. Other Microsoft XAML frameworks (WPF\UWP) do not throw an exception. 

I hope you can see that in practice, not throwing an exception is very useful when dealing with empty collections. Empty collections coming from JSON are very common (and they're preferred over returning null).

XAML:

```xaml
<Image Source="{Binding Images[0]}" />
```
Code:
```csharp
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            BindingContext = new MainPageViewModel();
        }
    }

    class MainPageViewModel
    {
        // Works with null value
        //public Uri[] Images { get; }

        // Doesn't work with empty array
        public Uri[] Images { get; } = { };
    }
```
### Expected Behavior
No crash. 

### Actual Behavior
Throws exception

### Basic Information

- Version with issue: Latest (3.4.0.1008975)
- Last known good version: I don't know

### Reproduction Link

[TestBindingToNullCollection.zip](https://github.com/xamarin/Xamarin.Forms/files/2609032/TestBindingToNullCollection.zip)

**Comment by StephaneDelcroix** [comment]
> not throwing an exception is very useful
I second that opinion

**Comment by StephaneDelcroix** [comment]
on the plus side, I think this is handled correctly with compiled bindings. the collection is supposed to throw an IndexOutOfRangeException, and that exception is caught,
