### ISSUE TITLE
IMarkupExtension fails with: unable to find a public static field

### ISSUE THREAD

**Issue by dpjonesVst** [xamarin/Xamarin.Forms#4523]
### Description
An IMarkupExtension that works in Xamarin Forms v3.2 now fails in v3.3 and v3.4

### Steps to Reproduce

1. Create an IMarkupExtension
2. Use it in your XAML: {x:Static extensions:CustomNamedSize.Small}
3. Gives error: x:Static: unable to find a public -- or accessible internal -- static field, static property etc.

### Expected Behavior
The extension values should be available in the XAML

### Actual Behavior
XAML error in most recent versions of Xamarin Forms

### Basic Information

- Version with issue: Xamarin Forms v3.3 and v3.4
- Last known good version: Xamarin Forms v3.2
- IDE: Visual Studio
- Platform Target Frameworks: 
  - UWP:  16299  

[MarkupExt.zip](https://github.com/xamarin/Xamarin.Forms/files/2610470/MarkupExt.zip)

**Comment by StephaneDelcroix** [comment]
What's happening here is that you have a class named `CustomNamedSizeExtension` and an enum named `CustomNamedSize`.

When faced with a name to resolve (`CustomNamedSize` in your case, the Xaml loader first tries to resolve to a type with the "Extension" suffix of it (`CustomNamedSizeExtension`), then to the type with the exact same name (`CustomNamedSize`).

There was a bug that wasn't applying this rule correctly in some nested cases (like yours), that has been resolved. So what you experience is the correct behavior, and your current code is relying on a buggy behavior. We're sorry for the inconvenience it could cause, but we won't revert that change.
