### ISSUE TITLE
[Feedback] Loading Indicator Binding not firing Ipad (only) android, iphone OK!

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4544]
### Description

<p>We have a Xamarin app that we have relased onto the app store for Android already. 

I have been in the process of getting the IOS verison working 100 % before i also finally upload that version. 

The issue specifically is the loading indicator thats built into Xamarin. 

The app displays the loading indicator in the top left (0,0), this value is done through binding 

on app startup i store the width and height into variable and then for the loading indicator i have a new variable to store this info as follows

LoadingIndicatorPosition = new thickness (0, 0, (width / 100), (width / 100));

This works fine on andorid and always displays the indicator in the top left and the height and width is scaled to be consistent acrross devices. 

This also works fine on Iphones, dispalying when it should same as android.

However on Ipad the indicator never displays.
If i stop the breakpoint on the variable, i can see it has the values, but the binding never fires to update it. I have tried using the linker preserve options incase that was stripping something away. 

If i input the loading indicator values in xml manually (hardcoded), the same as the calculated values from using the screen width. 

example

(0, 0, 100, 100) the loading indicator displays correctly on IPad.

Im at a loss on what i can do, the binding is very simple and works on every other platform fine

       // Loading indicator position
        [Preserve(AllMembers = true)]
        private Thickness _loadingIndicatorScreenPosition;
        // [Preserve(AllMembers = true)]
        public Thickness LoadingIndicatorScreenPosition
        {
            get
            {
                Debug.WriteLine(App.LoadingIndicatorScreenPosition);
                return App.LoadingIndicatorScreenPosition;
            }
            set
            {
                _loadingIndicatorScreenPosition = value;
                OnPropertyChanged(&quot;LoadingIndicatorScreenPosition&quot;);
            }
        }

As this app is based around bluetooth, i cannot release the app without the loading indicator. I cannot find anything online as to what may be the issue. Please help me find a solution

Thank you

Linker option currently set to SDK Only</p>
<a href="https://developercommunity.visualstudio.com/content/problem/362953/loading-indicator-binding-not-firing-ipad-only-and.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/711637">original linked feedback ticket</a>.

### Source

[736041](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736041)

**Comment by kingces95** [comment]
Asked for a reproduction back on the orig issue.
