### ISSUE TITLE
[Feedback] xamarin form expandable list do not expand after search

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4545]
### Description

<p>Hellow, am in confusion where did i do wrong, i followed this Tutorial https://www.youtube.com/watch?v=GG10QPrRC3w

LexisListModel.cs, LexisPage .xaml :- 
&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot;
             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
             xmlns:local=&quot;clr-namespace:Lexicon&quot;
             x:Class=&quot;Lexicon.LexisPage&quot;
             Title=&quot;Search in Listview&quot;&gt;
    
    &lt;ContentPage.BindingContext&gt;
        &lt;local:LexisListModel/&gt;
    &lt;/ContentPage.BindingContext&gt;

    &lt;Grid BackgroundColor=&quot;Black&quot;&gt;
        &lt;Grid.RowDefinitions&gt;
            &lt;RowDefinition Height=&quot;40&quot; /&gt;
            &lt;RowDefinition Height=&quot;8*&quot; /&gt;
        &lt;/Grid.RowDefinitions&gt;

        &lt;SearchBar Grid.Row=&quot;0&quot;
                   x:Name=&quot;MySearch&quot;
                   Text=&quot;{Binding Word}&quot;
                   Margin=&quot;2,2,2,0&quot;
                   BackgroundColor=&quot;White&quot;
                   CancelButtonColor=&quot;Black&quot;
                   Placeholder=&quot;Search&quot;
                   TextChanged=&quot;MySearch_TextChanged&quot;
                   PlaceholderColor=&quot;LightGray&quot;/&gt;

        &lt;ListView Margin=&quot;2,0,2,2&quot;  
                  Grid.Row=&quot;1&quot;
                  x:Name=&quot;MyList&quot;
                  BackgroundColor=&quot;White&quot;
                  ItemTapped=&quot;ListViewItem_Tabbed&quot; 
                  ItemsSource=&quot;{Binding Words}&quot;  
                  HasUnevenRows=&quot;True&quot; &gt;

            &lt;ListView.ItemTemplate&gt;
                &lt;DataTemplate&gt;
                    &lt;ViewCell&gt;
                        &lt;StackLayout Padding=&quot;5&quot;&gt;
                            
                            &lt;Label Text=&quot;{Binding Chang}&quot;  
                                   FontSize=&quot;Medium&quot;  
                                   TextColor=&quot;Black&quot;/&gt;
                            
                            &lt;StackLayout IsVisible=&quot;{Binding Isvisible}&quot;  
                                         BackgroundColor=&quot;DarkGray&quot;
                                         Margin=&quot;2,2,2,2&quot;&gt;
                                &lt;Grid&gt;
                                    &lt;Grid.RowDefinitions&gt;
                                        &lt;RowDefinition Height=&quot;Auto&quot;/&gt;
                                        &lt;RowDefinition Height=&quot;Auto&quot;/&gt;
                                    &lt;/Grid.RowDefinitions&gt;
                                    
                                    &lt;Label Text=&quot;{Binding Hint}&quot;  
                                           WidthRequest=&quot;110&quot;
                                           Margin=&quot;2,2,2,2&quot;
                                           FontSize=&quot;5&quot;
                                           Font=&quot;Italic&quot;
                                           TextColor=&quot;Blue&quot;/&gt;
                                    
                                    &lt;Label Text=&quot;{Binding English}&quot;  
                                           HorizontalOptions=&quot;Center&quot;
                                           WidthRequest=&quot;110&quot;  
                                           FontSize=&quot;15&quot;  
                                           TextColor=&quot;White&quot;/&gt;
                                &lt;/Grid&gt;

                                &lt;Label Text=&quot;{Binding Define}&quot;  
                                       WidthRequest=&quot;100&quot;
                                       Margin=&quot;2&quot;
                                       FontSize=&quot;15&quot;  
                                       TextColor=&quot;White&quot;/&gt;
                            &lt;/StackLayout&gt;
                        &lt;/StackLayout&gt;
                    &lt;/ViewCell&gt;
                &lt;/DataTemplate&gt;
            &lt;/ListView.ItemTemplate&gt;
        &lt;/ListView&gt;
    &lt;/Grid&gt;
&lt;/ContentPage&gt;

LexisPage.xaml.cs :-
public partial class LexisPage : ContentPage
	{
        public ObservableCollection&lt;Word&gt; Words { get; set; }
        //LexisListModel ViewList;
        public LexisPage ()
		{
			InitializeComponent ();
            ViewList = new LexisListModel();
            BindingContext = ViewList;
		}

        private void ListViewItem_Tabbed(object sender, ItemTappedEventArgs e)
        {
            Word word = e.Item as Word;
            LexisListModel vm = BindingContext as LexisListModel;
            vm?.ShowOrHiddenWords(word);
        }
        
        public LexisListModel ViewList { get; set; }

        private void MySearch_TextChanged(object sender, TextChangedEventArgs e)
        {
            MyList.BeginRefresh();
            MyList.ItemsSource = string.IsNullOrWhiteSpace(e.NewTextValue)
                ? ViewList.Words
                : ViewList.Words
                    .Where(i =&gt; i.Chang.ToLower()
                        .Contains(e.NewTextValue));

            LexisListModel vm = BindingContext as LexisListModel;

            MyList.EndRefresh();
        }
    }

I could be able to search but after searched Text has been clicked it do not Expand, but before any search been made, it performe normal. I have been trying other option but could not work. [Visual Studio 2017, Version 15.8.4. win 10. Xamarin form]. Please help if there is any alternative too, Thank you</p>
<a href="https://developercommunity.visualstudio.com/content/problem/375566/xamarin-form-expandable-list-do-not-expand-after-s.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/723880">original linked feedback ticket</a>.

### Source

[736037](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736037)

**Comment by kingces95** [comment]
Hm, don't think this guy is reporting a bug. He's just trying to make something work. Not that we can't investigate but will de-prioritize in lieu of tackling issues where customer thinks they found a bug.
