### ISSUE TITLE
[Feedback] Stuck on build when making changes to XAML - XF

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4548]
### Description

<p>Make changes to XAML files and do not save the file

hit build or debug 

VS will get stuck on building forever.

It can however be avoided if using Save option after making changes to XAML files prior to build.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/379728/stuck-on-build-when-making-changes-to-xaml-xf.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727265">original linked feedback ticket</a>.

### Source

[736033](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736033)

**Comment by kzu** [comment]
Fixed in 15.9 already.

**Comment by samhouts** [comment]
HUZZAH
