### ISSUE TITLE
[Feedback] Xamarin.Forms 3.4.0 Swipe Gesture Recognizer

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4551]
### Description

<p>Hi,
Xamarin.Forms 3.4.0 swipe gesture recognizer not working in UWP. (Working in XF 3.3.0)
I defined only for Left and Right directions.  Now, Up and Down in Stack Layout is not scrolling.

&lt;local:TestScrollView Orientation=&quot;Vertical&quot;&gt;
    &lt;StackLayout Orientation=&quot;Vertical&quot;&gt;
        &lt;StackLayout.GestureRecognizers&gt;
            &lt;SwipeGestureRecognizer Direction=&quot;Left&quot; Swiped=&quot;OnTestLayoutLeftSwiped&quot; /&gt;
            &lt;SwipeGestureRecognizer Direction=&quot;Right&quot; Swiped=&quot;OnTestLayoutRightSwiped&quot; /&gt;
        &lt;/StackLayout.GestureRecognizers&gt;
    &lt;/StackLayout&gt;
&lt;/local:TestScrollView&gt;</p>
<a href="https://developercommunity.visualstudio.com/content/problem/390012/xamarinforms-340-swipe-gesture-recognizer.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734231">original linked feedback ticket</a>.

### Source

[736027](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736027)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/4552
