### ISSUE TITLE
Xamarin.Forms.Core.dll is not valid

### ISSUE THREAD

**Issue by MichalStrehovsky** [xamarin/Xamarin.Forms#4563]
### Description

The IL metadata in the Xamarin.Forms.Core assembly is invalid.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise>peverify C:\Temp\ilcRepro\In\Xamarin.Forms.Core.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[MD]: Error: Method has a duplicate, token=0x0600142f. [token:0x0600142E]
[MD]: Error: Method has a duplicate, token=0x0600142e. [token:0x0600142F]
2 Error(s) Verifying C:\Temp\ilcRepro\In\Xamarin.Forms.Core.dll
```

The tokens in question are around `get_ResourceProvider` so the signs point to this being caused by #2880.

### Steps to Reproduce

1. Build a Xamarin forms app on UWP in Release configuration

### Expected Behavior

Builds fine.

### Actual Behavior

.NET Native compiler crashes with:

```
    MSBUILD : error : Error: NUTC301D:Internal Compiler Error: Invalid class variable '0' in signature while compiling method 'static System.Func`2<System.String, System.String> Xamarin.Forms.Internals.ResourceLoader.get_ResourceProvider()'.
    MSBUILD : error : ILT0005: 'C:\dd\PN1\binaries\amd64chk\ProjectN\TestILC\ProductIlc\Tools64\nutc_driver.exe @"C:\Temp\ilcRepro\int\MDIL\[redacted].rsp"' returned exit code 1
```
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by MichalStrehovsky** [comment]
cc @StephaneDelcroix, I'm adding you to an internal mail thread.

**Comment by StephaneDelcroix** [comment]
looks like ShameHat is executed TWICE

**Comment by StephaneDelcroix** [comment]
> We are using a custom Xamarin.Forms build [...][of] 3.2.0.

2 things to check:
- is the dup present in 3.2.0, or 3.4.0 ?
- ShameHat should detect that the assembly was already modified

**Comment by StephaneDelcroix** [comment]
the problem isn't present in released nugets
