### ISSUE TITLE
[Android] ImageButtonRenderer missing methods and properties in android

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/Xamarin.Forms#4566]
### Description
In XF 3.4 the Renderer of ImageButton in Android we have some missing method and properties.
We can't have acces to Element or Control or override OnElementChanged.

<img width="2232" alt="capture d ecran 2018-11-28 a 15 19 54" src="https://user-images.githubusercontent.com/14908719/49157864-1cf3a500-f321-11e8-8407-22d68de0bc3c.png">

In the iOS Renderer we have acces to this elements.

**Comment by PureWeen** [comment]
Part of this is already merged into master and this PR
https://github.com/xamarin/Xamarin.Forms/pull/4534

fixes the rest
