### ISSUE TITLE
Can't wrap Binding flag inside Label.Text 

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4572]
_From @ColeXm on November 27, 2018 6:43_

Error was thrown when i write 
&lt;Label&gt;
   &lt;Label.Text&gt;
        &lt;Binding Path="Blue"

It says "Property Text does not support values of type 'Binding' "  even though i downgrade xamarin.forms from 3.4 to 2.5 .

---

_Copied from original issue: MicrosoftDocs/xamarin-docs#1179_

**Comment by StephaneDelcroix** [comment]
we have tests for that, but not with XamlC on

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Xaml.UnitTests/LoaderTests.cs#L181-L199

**Comment by ColeXm** [comment]
Hi , sorry for the late reply, this is the sample ,actually it is just a new blank project .

https://github.com/ColeXm/TestDemo

**Comment by StephaneDelcroix** [comment]
your sample, once I removed the `//` comment from the Xaml, works JustFine(™). I'll need some more info...

**Comment by ColeXm** [comment]
Problem persists after removing the `//` comment.
