### ISSUE TITLE
Tabs bar on TabbedPage doesn't scroll to selected Tab if set programmatically.

### ISSUE THREAD

**Issue by yorkshenpolestar** [xamarin/Xamarin.Forms#4576]
### Description
Tabs bar on TabbedPage doesn't scroll to selected Tab if set programmatically.

Similar question:

- https://bugzilla.xamarin.com/show_bug.cgi?id=58441
- https://stackoverflow.com/questions/45356270/how-to-force-xamarin-forms-tabbedpage-to-scroll-to-selected-tab-progammatically/45406150#45406150

### Steps to Reproduce

1. Run the attached Android project
2. Press button Open TabbedPage.

### Expected Behavior
The TabbedPage will display and the tab bar will show that "Tab 10" is selected.

### Actual Behavior
The TabbedPage is opened and the "Tab 10" page contents are displayed however the tab bar does not show the "Tab 10" tab unless you scroll to it.

### Basic Information
This happens when the Android TabLayout TabMode is set to be scrollable. If using the default, fixed setting then all the tabs are visible but sized to fit horizontally.

- Version with issue: VS 2017 for Windows:  15.9.2
- Xamarin.Forms version: 3.4.0.1008975

### Screenshots

[Expected Behavior](https://i.stack.imgur.com/WiScU.gif) ,  [Actual Behavior](https://user-images.githubusercontent.com/18043540/49196214-06068e80-f3c5-11e8-91bf-e990883152c0.gif)

### Reproduction Link

[ControlIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2627429/ControlIssue.zip)

#### Question

I want to know whether this was a bug or a by-design problem? Any suggestions or tips will be great appreciated!

**Comment by samhouts** [comment]
Seems like a good candidate for a platform specific configuration. Thanks!

**Comment by candidodmv** [comment]
@samhouts I will appreciate very much if it will be available for specific configuration. I did think "what? it's doesn't exist yet?"

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
