### ISSUE TITLE
CPU usage is maintained at 25% when scrolling through the ListView 

### ISSUE THREAD

**Issue by Suhasini-Suresh** [xamarin/Xamarin.Forms#4580]
### Steps to Reproduce

1. Run the sample attached
2. Scroll through the listview at fast rate 

### Expected Behavior
Items in the ListView should be visible when scrolling instead of getting the black background color 
### Actual Behavior
 CPU usage is at 25% continously ; ListView is with a black background color and the items are not visible 
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 3.1.0.69
- Affected Devices:

### Screenshots

[ScrollingListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2628660/ScrollingListView.zip)

![cpuusage](https://user-images.githubusercontent.com/25817167/49215610-2d725100-f3ef-11e8-89a1-4590f147d2c7.png)

### Reproduction Link

[FWListView.zip](https://github.com/xamarin/Xamarin.Forms/files/2628657/FWListView.zip)

**Comment by StephaneDelcroix** [comment]
I guess your machine has 4 cores, so we basically make the best usage of the resources available here, as the UI is single-threaded.

**Comment by samhouts** [comment]
I don't think the CPU usage is something that is within our (Xamarin.Forms's) control. Those black boxes are just the placeholders that are rendered to give a visual cue that more is loading. https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-gridview-and-listview#placeholders
