### ISSUE TITLE
[Android] With the introduction of ImageButton in 3.4.0, the behaviour of setting Source to null on an Image has changed in Android

### ISSUE THREAD

**Issue by jorisvergeer** [xamarin/Xamarin.Forms#4597]
### Description

I cannot clear an Image by setting the source to null. 
This behavior has changed in 3.4.0 with the introduction of ImageButton.

This only affects Android.

The issue is probably causes by this change in Xamarin.Forms.Platform.Android/Extensions/ImageViewExtensions.cs

![image](https://user-images.githubusercontent.com/1906639/49288355-cd3be780-f4a0-11e8-8b1a-663f7f8b582f.png)

### Steps to Reproduce

1. Create an image view
2. Set source to an image resource
3. Set source back to null

### Expected Behavior
The Image is goes back to its initial state without an image to show.

### Actual Behavior
The old image is still visible.

### Basic Information

- Version with issue: 3.4.0
- Last known good version: 3.1

**Comment by PureWeen** [comment]
In testing it looks like this behavior changed from 3.1 to 3.2
I tested with 3.2 and 3.2 exhibits the behavior you are talking about and it also causes it to act differently than Button when you set that source to null

**Comment by jorisvergeer** [comment]
It could be wrong in an earlier version. It got noticed in our app when we updated to 3.4.
