### ISSUE TITLE
[Android] ImageButton on android is not clipping view to corner radius

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4606]
### Description
I'm using the new ImageButton control introduced with XF 3.4 to create circular image button. Unfortunately it doesn't work on Android.

it looks like the rounding on Android will need to be achieved by utilizing canvas.drawcircle inside the Draw method. So the paint object and all the parameters for that will need to be setup and used instead of base.draw

### Steps to Reproduce

`<ImageButton Grid.Row="0" Grid.Column="0" 
             Source="{Binding ProfileImage, Converter={StaticResource PathToImageConverter}}"
             CornerRadius="50"
             HorizontalOptions="Center" VerticalOptions="Center"
             HeightRequest="100" WidthRequest="100">
</ImageButton>`

Or run the ControlGallery Issue G1724 which demonstrates a circular button.

### Expected Behavior

See a circular image

### Actual Behavior

Image is rectangular

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: VS 2017 Professional 15.9.2
- Platform Target Frameworks: 
  - iOS:  12.0 (16A366)
  - UWP:  16299
  - Android: 9.0
- Nuget Packages:
- Affected Devices:

### Screenshots

Android
![profile_ios](https://user-images.githubusercontent.com/84007/48892213-3939a280-ee46-11e8-83c5-3d933dd77e8a.png)

UWP
![profile_uwp](https://user-images.githubusercontent.com/84007/48892231-46569180-ee46-11e8-9ec5-871857d61eec.png)

**Comment by syed-pelican** [comment]
Need this fix badly :(

**Comment by PureWeen** [comment]
I want to live Sambot!!!

**Comment by CARP-Kaiser** [comment]
When will this fix be available?

**Comment by CARP-Kaiser** [comment]
@samhouts Why does this say closed when it hasn't come out in the past 3 releases?

**Comment by samhouts** [comment]
Issues are closed when they are merged, not when they are released. This was merged into master, so it will be part of 4.5.0. @PureWeen is this fix suitable for a backport to 4.4.0?

**Comment by PureWeen** [comment]
@samhouts Yes! I'll backport it to 4.4.0 so it'll be part of the next SR of 4.4.0

**Comment by CARP-Kaiser** [comment]
You both are awesome. @samhouts thank you for the describing the difference between the two.

**Comment by CARP-Kaiser** [comment]
@PureWeen @samhouts Thanks you guys for your hard work.
