### ISSUE TITLE
How to obtain the dynamically changing editor height at runt time for Xamarin Forms UWP? 

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#4611]
### Description

In our sample, we have added custom editor and changed the height of the editor based on the given text by calling ‘InValidateMeasure’ for Xamarin Forms UWP. It works fine but when i call ‘InValidateMeasure’, 'OnSizeAllocated' and 'OnMeasure' override methods are not triggered. So, it is not possible to estimate and obtain the changed height of the editor at run time. Could you please provide your valuable suggestion on this? If it is achievable through renderer, could you please modify the sample and provide solution?

**Sample:**  [CustomControl.zip](https://github.com/xamarin/Xamarin.Forms/files/2638674/CustomControl.zip)

Regards,
Ganeshamoorthy C

**Comment by kingces95** [comment]
Could you please elaborate on what features we're missing that prompted you to create a custom renderer? We'd prefer to add those features than debug the custom renderers so the feature becomes more generally available.

**Comment by Ganeshamoorthy10** [comment]
Hi @kingces95 ,

My requirement is to auto expand the height of the editor based on provided input.

**Comment by Ganeshamoorthy10** [comment]
Hi @kingces95 ,

Could you please reopen this?

**Comment by dbnex14** [comment]
Same issue here.  Editor in Xamarin UWP is not behaving as in Xamarin Android or iOS.
I am sending some data from a server app to client (using TCP/IP).  Both Android and iOS apps work as expected and the data is displayed in Editor in my Xamarin.Forms app.
But on UWP, this will not happen even though I receive data from server successfully

**Comment by jfversluis** [comment]
Way old issue and seems more like a question than a bug? Hope you got it figured out by now :)
