### ISSUE TITLE
How to add older iOS simulator on Visual studio for windows.

### ISSUE THREAD

**Issue by ColeXm** [xamarin/Xamarin.Forms#4618]
After I downloaded `iOS 9.0 Simulator` and set `Deployment Target` to 9.0 

i can see iphone4S simulator appear in `XCode` or `Visual studio for mac` 

![](https://us.v-cdn.net/5019960/uploads/editor/kp/042vjfjyfta0.png "") ![](https://us.v-cdn.net/5019960/uploads/editor/54/cjbcrcda8phb.png "")

However ,when i check it in visual studio on windows.

**When i first open simulator drop-down list**

![](https://us.v-cdn.net/5019960/uploads/editor/ci/rg5lgy4xfhac.png "")

**When i click `device` , iPhone 4S shows up.**

![](https://us.v-cdn.net/5019960/uploads/editor/as/75kmapdfvlck.png "")

**When i select iPhone 4S , it shows `iPhone XR`**

 ![](https://us.v-cdn.net/5019960/uploads/editor/h8/7igikfw1faj3.png "")

- Version 

- Xcode : 10.1(10B61)
- Visual Studio :15.9.2
- Xamarin.Forms : 3.4.0.1008975
- Xamarin : 4.12.3.72
- Xamarin.iOS : 12.2.1.10

**Comment by kingces95** [comment]
Should be opened against Xamarin VS team.
