### ISSUE TITLE
[Android] App crashes when showing/scrolling a pdf

### ISSUE THREAD

**Issue by FebeD** [xamarin/Xamarin.Forms#4622]
### Description

Our Android app crashes a lot when we try to open or scroll a pdf.
I use the exact same code as the example in Xamarin Recipes.
Sometimes it happens immediately, sometimes after a while.
I don't know what causes the crash, but I think it happens faster on slow devices and with larger pdf's.

### Steps to Reproduce

I was able to reproduce the crash in your example.
I just replaced the App constructor by the following code:

```csharp
    public App ()
	{
        //MainPage = new WebViewPageCS();

        MainPage = new NavigationPage(new ContentPage()
        {
            Content = new Button
            {
                Command = new Command(async () =>
                {
                    await Navigation.PushAsync(new WebViewPageCS());
                })
            }
        });

        Navigation = MainPage.Navigation;
    }
```

### Expected Behavior

The pdf should open and we should be able to scroll.

### Actual Behavior

The app crashes, sometimes immediately, sometimes after a while

### Basic Information

- Version with issue: 2.3.4.247 and 3.4.0.1008975
- Last known good version:/
- IDE: Visual Studio 15.8.6
- Platform Target Frameworks:
  - Android: 8.1

**Comment by FebeD** [comment]
I can't get a stacktrace.

[DisplayPDF.zip](https://github.com/xamarin/Xamarin.Forms/files/2648371/DisplayPDF.zip)

**Comment by kingces95** [comment]
Hm. Works for me.
![snag_3d1f85](https://user-images.githubusercontent.com/4120386/49546158-b112be80-f883-11e8-9460-986b56fb6c81.png)

**Comment by StephaneDelcroix** [comment]
@kingces95 your android emulator is probably not a 'slow device', and is unlikely to turn out of memory (provided you close slack and teams)

@FebeD please provide a stacktrace, or better instruction to reproduce this, like a list of (common) devices on which it crashes.

**Comment by kingces95** [comment]
Hm, well, not sure what to tell you. Does this reproduce for you on newer devices? My LGE Nexus 5 is not super old but its not super new either. It load up the `.pdf` OK. It may be that the app simply needs a beefy device to handle the work of loading a `.pdf`...

**Comment by FebeD** [comment]
@kingces95 The app doesn't crash on my Samsung Galaxy A3 (2017).

**Comment by PureWeen** [comment]
@FebeD  can you try to use logcat to see what the exception is? Sometimes that will reveal a little extra info that the VS debugger isn't capturing?

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by PureWeen** [comment]
@FebeD 
Is that crash log from your full version of the app or from the repro you've included on this ticket? It seems like there are some other services referenced in the log but maybe I'm not parsing it correctly.

Some thoughts
- Run the repro attached to this issue
- make sure it's being deployed as debug with all the instrumentation enabled  (maybe turn off shared runtime just to see if that makes a difference)
- Maybe try Android studio and ensure all your filters are turned off? https://stackoverflow.com/questions/35364373/android-app-crashes-without-any-logcat-or-any-exception


![image](https://user-images.githubusercontent.com/5375137/50653375-8f6e2b00-0f46-11e9-89ff-2fde83140d61.png)

**Comment by samhouts** [comment]
@FebeD  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
