### ISSUE TITLE
entry textalignment in xamarin.foms

### ISSUE THREAD

**Issue by Ershad95** [xamarin/Xamarin.Forms#4632]
test alignment in entry not working ..when i set right for text alignment ,placeholder set in left ,this issue see in android

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
[App61.zip](https://github.com/xamarin/Xamarin.Forms/files/2650449/App61.zip)
![snag_4c46e744](https://user-images.githubusercontent.com/4120386/49541614-61c69100-f877-11e8-83c2-010bc754f6c1.png)
Placeholder responds to horizontal text alignment.
