### ISSUE TITLE
Doc for adding Mac project appears to be out of date

### ISSUE THREAD

**Issue by SmartmanApps** [xamarin/Xamarin.Forms#4638]
### Description
I'm trying for the first time to add a Mac project to a Forms solution by following https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac. I'm having trouble as intellisense is coming up with different things to what is said in the doco. e.g.  the doco says to add "using Xamarin.Forms.Platform.MacOS;" but the closest thing that intellisense comes up with is "using Xamarin.Forms.PlatformConfiguration.macOSSpecific;" - not sure if this is a new version of the original statement or something else altogether. Similarly as I progressed through other parts of the document I came upon other instances of intellisense not finding what's in the doco. It appears that there have been updates since the doco was written and the doco hasn't been updated to reflect that.

### Steps to Reproduce

1. try following the doco to add a Mac project to an existing Forms solution (checking that intellisense is matching up along the way. note: first 6 steps were all okay - it was step 7 where the issues started to pop up)
2. 
3. 

### Expected Behavior
Successfully add Mac project. i.e. intellisense matches what is written in the doco and everything works.
### Actual Behavior
intellisense failing to find several of the specified names/objects
### Basic Information

- Version with issue: Xamarin.Mac 5.2.1.11
- Last known good version: (this is first attempt at this)
- IDE: Visual Studio for Mac Community 2017 Version 7.7 (build 1868)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Mac OS X 10.12.6

### Screenshots
![image](https://user-images.githubusercontent.com/20635275/49493257-948c7b80-f8af-11e8-92f8-1eb18574fff0.png)
![image](https://user-images.githubusercontent.com/20635275/49493578-c05c3100-f8b0-11e8-9158-b729306bf7ab.png)

### Reproduction Link
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac

**Comment by chucker** [comment]
I realize this issue is fairly old, but it's still open, so…

> the doco says to add "using Xamarin.Forms.Platform.MacOS;" but the closest thing that intellisense comes up with is "using Xamarin.Forms.PlatformConfiguration.macOSSpecific;" - not sure if this is a new version of the original statement or something else altogether

`using Xamarin.Forms.Platform.MacOS;` is still correct as of Xamarin Forms 4.7. I'm not sure why aren't seeing that.

A few things to check on the **MyApp.macOS** project:

* does the `csproj` reference the right target framework? (Note that this bit, as I understand it, will change significantly in either .NET 5 or .NET 6.)

```xml
    <TargetFrameworkVersion>v2.0</TargetFrameworkVersion>
    <TargetFrameworkIdentifier>Xamarin.Mac</TargetFrameworkIdentifier>
```

* do you have a project reference to the platform-agnostic **MyApp** project?

```xml
  <ItemGroup>
    <ProjectReference Include="..\MyApp\MyApp.csproj">
      <Project>{…}</Project>
      <Name>MyApp</Name>
    </ProjectReference>
  </ItemGroup>
```

* do you have a package reference to Xamarin Forms in your Mac-specific project?

```xml
    <PackageReference Include="Xamarin.Forms">
      <Version>4.7.0.1080</Version>
    </PackageReference>
```

I think the last one may be it. That NuGet package is built such that [the platform-specific additions get added conditionally](https://github.com/xamarin/Xamarin.Forms/blob/main/.nuspec/Xamarin.Forms.nuspec#L302).

**Comment by jfversluis** [comment]
@davidbritch FYI, didn't check if this is still the case. You can judge if we still want and/or need to update this.

Closing it here. For anyone finding this, I show how to add the macOS target in [this video](https://www.youtube.com/watch?v=bBN9gBtO5nc), I think that one is still up-to-date.
