### ISSUE TITLE
[iOS] TabletMasterDetailRenderer center line color

### ISSUE THREAD

**Issue by yang-er** [xamarin/Xamarin.Forms#4643]
### Description

When a MasterDetailPage with BackgroundColor not manually set is shown in tablet mode, center line becomes white.

I don't know if it is intended, so I don't want to make a pull request.

If I set BackgroundColor = Color.DarkGray in my code, it will become better.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/TabletMasterDetailRenderer.cs

Seems that an Element's background color is default white, void UpdateBackground() make the center line become white. So I think the best way to solve it is modify default value in MasterDetailPage.

### Steps to Reproduce

1. Tablet mode
2. BackgroundColor not manually set
3. Just show!

### Expected Behavior

Center line is gray like other iPad apps such as System Settings look like.

### Actual Behavior

A single white line.

### Basic Information

- Version with issue: 
- Last known good version: N/A
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.1 (11.x also)
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: 3.2/3.3/3.4
- Affected Devices: iPad series

### Screenshots

I'm sorry but I don't know how to upload an image...

**Comment by yang-er** [comment]
![simulator screen shot - ipad 6th generation - 2018-12-05 at 21 29 21](https://user-images.githubusercontent.com/10959348/49516950-da5c3a80-f8d5-11e8-9198-39cf85c05443.png)
Ahh ha I found it.
the dark gray one is the scroll bar.

**Comment by kingces95** [comment]
Found it? As in this is not an issue anymore? Please re-open if that's not the case.

**Comment by yang-er** [comment]
I mean i found the way to create a screen shot...
The vertical gray line is the scroll bar.
There should be a gray line at the right of scroll bar as iOS default.
