### ISSUE TITLE
[Shell] BottomNavigationView Flickers and TitleView Improvements

### ISSUE THREAD

**Issue by ChasakisD** [xamarin/Xamarin.Forms#4647]
## Summary
First of all, thank you for your hard work on the Shell! :)

I have been using the new Shell for a while and spotted some issues.
Let's have a Shell with ```FlyoutBehavior="Disabled"``` and lets assume the following 2 approaches:
* The first one is when having one ShellItem and many ShellSections(each one has one ShellContent), so we get a BottomNavigationView.
* The second one is when having one ShellItem with one ShellSection with many ShellContents, so we get the TabbedPage.

1) In the first approach (BottomNavigationView) when switching the bottom tabs on Android, it flickers the UI, like the page is getting re-rendered. So, when using some custom controls to achieve gradients, corner radius etc, it's a bit buggy. Furthermore there is no way to set a global TitleView that applies to all the ShellSection. Each page must have it's own TitleView and on switch it also re-renders the TitleView, so the flickers also happens. Maybe am i missing something? I tried to set the Shell.TitleView to the Shell and into the ShellItem but it doesn't seem to work.

2) In the second approach (TopTabs) switching works fine without any flickering stuff(maybe because of the ViewPager caching). But, setting at least at one content the TitleView, it applies everywhere! So no flickering on the TitleView, but it's confusing! If i apply the TitleView to the Page it will work or not? Maybe it depends?

The way I am thinking the Shell is to be able to customize the global TitleView, while giving the opportunity to change the title view on any level. What i mean is:
* If you set the TitleView to a ShellContent, only this one will get the specific TitleView. 
* If you set the TitleView to a ShellSection every ShellContent of the Section will get this TitleView, except when the ShellContent get its own.
* If you set the TitleView to a ShellItem every ShellSection will get the TitleView except it gets its own, etc.. I think that I am explaining it well.

I feel sorry for not following the template but there were some categorizations and the issue was more general

## Intended Use Case

These will apply to everyone that wants to apply the BottomTabs and also to customize the Toolbar.

**Comment by kingces95** [comment]
@ChasakisD Thanks so much for your feedback. It would be more valuable if you could break this issue into individual issues for each concern along with an attached reproduction. If your willing, please close this out and re-open individual tasks. Short of that we'll add this to our backlog.

**Comment by ChasakisD** [comment]
Alright! Sorry for any inconvenience! Will open different issues asap.
