### ISSUE TITLE
[iOS,Android] TapGestureRecognizer doesn't work for first cells of CollectionView

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#4652]
### Description

Since there's no SelectedItem, trying to add a TapGesture to my Item so I can navigate. 
The command for the gesture is only executed after I scroll and tap a "fresh" row.. on the first items if I tap the command is not executed. 

### Steps to Reproduce

1. Add a gesture to your ItemTemplate
```
<DataTemplate xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="SCE.Templates.PostListItemTEmplate" xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms">
    <Grid HeightRequest="200" HorizontalOptions="FillAndExpand">
        <Grid.GestureRecognizers>
            <TapGestureRecognizer Command="{Binding Command}" CommandParameter="{Binding .}" />
        </Grid.GestureRecognizers>
        <Grid.RowDefinitions>
            <RowDefinition>
            </RowDefinition>
            <RowDefinition Height="50">
            </RowDefinition>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <ffimageloading:CachedImage InputTransparent="true" Grid.RowSpan="2" DownsampleToViewSize="true" DownsampleHeight="200" Source="{Binding Image}" Aspect="AspectFill" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />
        <ContentView Grid.Row="1" InputTransparent="true"  Padding="10" VerticalOptions="EndAndExpand" BackgroundColor="#7F000000">
            <Label Text="{Binding Title}" FontAttributes="Bold" FontSize="20" TextColor="White" />
        </ContentView>
    </Grid>
</DataTemplate>
```
2. Bind some items to your CollectionView
```
<CollectionView ItemsSource="{Binding Posts}" ItemTemplate="{StaticResource postListItemTemplate}" />
```
3. Create a list of Posts and set a Command for each with a debug action. 

```
foreach (var post in Posts)
			{
				post.Command = new Command(obj => {
					System.Diagnostics.Debug.WriteLine("Called");
				});
			}
```
4. Run sample and click the 1 st item.

### Expected Behavior

Command with debug action should execute for 1st cell.

### Actual Behavior

Command doesn't execute.

### Basic Information

- Version with issue: 4.0.0-pre
- iOS, Android

**Comment by mikescandy** [comment]
For me the command is not triggering on any item in the collectionview. My collection is horizontal though.

**Comment by ernestoyaquello** [comment]
> For me the command is not triggering on any item in the collectionview. My collection is horizontal though.

This was happening to me the other day after upgrading Xamarin Forms: the command wouldn't get triggered in any of my items. However, I moved the assignation of the `TapGestureRecognizer` from the XAML file to the code behind and the commands went back to working properly. Weird.

**Comment by adrianknight89** [comment]
The way you're binding commands for each post seems weird to me. Can't you create a single `Command` for the entire view model and bind individual items like this:

```
<Grid.GestureRecognizers>
      <TapGestureRecognizer Command="{Binding BindingContext.Command, Source={x:Reference Root}}" CommandParameter="{Binding .}" />
</Grid.GestureRecognizers>
```
Not sure if this will change anything though...

**Comment by hartez** [comment]
It's working fine for me using 4.0 pre 2. Are you still seeing this problem? Is there something I'm missing in my repro?

[_4652Repro Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2766597/_4652Repro.Repro.zip)

**Comment by rmarinho** [comment]
This was an issue with my code, setting the Command later and it wasn't iNPC so the 1st cells didn't update command, new cells were getting the command.

@adrianknight89 I have a file with the template so I can't use x reference irc. this is some code I have around for some time , I was using selected item and was trying to get around that for CollectionView in a quick test but ...
