### ISSUE TITLE
IsTabStop property not working when Grid contains ScrollView

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#4653]
### Description
We are having Grid with ScrollView architecture.

**Grid->ScrollView->Label**

**IsTabStop** property set as **False** for the Grid but when I click tab button focus moved to it.

### Steps to Reproduce

1. Run the attached sample
2. Click tab button which focus on the grid.

### Expected Behavior
Focus not moved to grid
### Actual Behavior
Focus still moved to it
### Basic Information

- Version with issue: Xamarin.forms 3.4.0.1008975
- Platform Target Frameworks: 
  - UWP: 16229

### Reproduction Link

[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/2652294/Sample.zip)

**Comment by PieEatingNinjas** [comment]
I don't think this is a bug, or I'm misunderstanding the issue.
When I look at the sample that you provide, I see that you're setting `IsTabStop="false"` on the Grid, not on the ScrollView.
```
<Grid Grid.Column="2" IsTabStop="False">
    <ScrollView>
        <Label Text="Label" Grid.Row="0"/>
    </ScrollView>
</Grid>
```
When you press tab, the focus is moved to the Scrollview, which is expected as you didn't define `IsTabStop="false"` on the Scrollview itself. Setting IsTabStop doesn't apply to child elements, only on the element itself. If you want to avoid focus on the Scrollview, you should set it explicitly on that element.
