### ISSUE TITLE
Load base64 image works fine on Tizen emulator, but white blank on real Tizen device

### ISSUE THREAD

**Issue by 5yunus2efendi** [xamarin/Xamarin.Forms#4657]
### Description
I have the following code to load image:
```code
byte[] imageBytes = await MethodToGetBytesAsync();
ImageSource = Xamarin.Forms.ImageSource.FromStream(() => new MemoryStream(imageBytes));
```
Load image using other than `FromStream` works fine

### Steps to Reproduce

1. Create Xamarin Forms project for Tizen
2. Add image control and load image using code above
3. Deploy to Tizen device (not emulator)

### Expected Behavior
Image appear

### Actual Behavior
Image not displayed instaead it's show white blank

### Basic Information

- Version with issue: Xamarin.Forms 3.1.0.583944
- IDE: Visual Studio 2017
- Platform Target Frameworks: Tizen

**Comment by rookiejava** [comment]
@5yunus2efendi Could you tell me which target device you tested? Smart TV? or Galaxy Watch ? or anything else?

**Comment by rookiejava** [comment]
When I checked with [XamFormsImageResize ](https://github.com/Samsung/xamarin-forms-samples/tree/master/XamFormsImageResize) sample app, it works fine as shown below. I've tested on both Samsung Smart TV 2018 model and Samsung Galaxy Watch.
![fromstream](https://user-images.githubusercontent.com/1029134/49623010-2f4f9c00-fa0f-11e8-870c-baf17a7ca905.png)

**Comment by 5yunus2efendi** [comment]
The device is Samsung Smart TV.

It works now, it's because the image is too large (about 2mb) so the image needs to be resize.
