### ISSUE TITLE
[iPad] MasterDetailPage IsPresented stops working after device rotation

### ISSUE THREAD

**Issue by ferenckozma** [xamarin/Xamarin.Forms#4660]
### Description
This is an **iPad only** issue, works on iPhone, Android and UWP with same code.

Master side of the **MasterDetailPage** being used for showing a flyout menu (**MasterBehavior=Popover**). Open by swiping has to be disabled to do not accidentally open it with Map scrolling gesture in Detail side, etc. (**IsGestureEnabled**=false).
Master side opened with setting the **IsPresented** property explicitly.

When you rotate the device while the Master page **IsPresented** (i.e. changing from **Portrait** to **Landscape** or the opposite), the Master side closing and it cannot be opened anymore, ignoring the **IsPresented** property thereafter.

Note: in case you re-enable the swipe gesture and open the Master side manually by swiping in the page from the left edge of the device, it starts to work again normally, even if you disable the **IsGestureEnabled** again. I have found an issue registered for this which was fixed in 2015, but it seems to be here again.

### Steps to Reproduce

1. Set MasterDetailPage MasterBehavior to Popover, IsGestureEnabled to false.
2. Open Master page by setting IsPresented to true (we were using two way binding to bool VM property to it, setting it to true by a Button Command)
3. Rotate the device (Master closing here..)
4. Try to open it again as in step two.

### Expected Behavior
Master page opens again (in Popover mode).

### Actual Behavior
Master Page not appearing anymore. By re-enabling gesture and manually swiping in the popover Master page, it starts to work again.

### Basic Information

- Version with issue: Xamarin.Forms 3.1.4
- Affected Devices: iPad only

**Comment by samhouts** [comment]
Can you please provide a sample project that shows the behavior? Thanks!

**Comment by PureWeen** [comment]
Closing for now. @ferenckozma if you can provide a sample project we can reopen
