### ISSUE TITLE
Empty resources tag throws an error

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4661]
### Description
```
<?xml version="1.0" encoding="utf-8" ?>
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ShellGallery.App">
    <Application.Resources>

    </Application.Resources>
</Application>
```

When running that I get an error "no embedded resource found for ShellGallery.App". Removing the Application.Resources tags fixes it.

### Expected Behavior
And empty tag does not throw this error.

### Actual Behavior
The error.

### Basic Information

- Version with issue: 4.0-pre1

### Screenshots
<img width="1675" alt="screen shot 2018-12-06 at 9 04 50 am" src="https://user-images.githubusercontent.com/41873/49592391-95b4bb80-f936-11e8-9207-6f643f5e5ac0.png">

**Comment by StephaneDelcroix** [comment]
might be related to #4582

**Comment by StephaneDelcroix** [comment]
this is the Xaml equivalent of writing this C#
```csharp
app.Resource =
```
it definitely misses a right hand side. But the error you're being is wrong

**Comment by StephaneDelcroix** [comment]
The same code doesn't throw any exception for me. the error message looks unrelated to the empty tag, but more to the embedded resource.

could you please reopen with a repro ? ❤
