### ISSUE TITLE
What's the thoughts of officially supporting webassembly?

### ISSUE THREAD

**Issue by DierkDroth** [xamarin/Xamarin.Forms#4665]
## Summary
Considering the dawn of Xamarin Forms 4.X and the latest news on Connect() (open sourcing all relevant MS UI frameworks) I think it's fair to ask these questions:

1) Are there any considerations to support webassembly/HTML5 as an official platform for Xamarin Forms? If so, could you please elaborate on these considerations?
2) If no, could you please share the reasons which prevented MS from making XF available on webassembly/HTML5?

Note: I'm well aware of Ooui. However, with deep respect for the author and without any offense nor intention to discount his work I have to state:
- there was not much activity on that project recently
- after all that project is not 'backed up' by MS
Hence, I could not consider it being at the same level as any potential, official support of Xamarin Forms for webassemblyHTML5

## API Changes
n.a.

## Intended Use Case
Make Xamarin Forms an ubiquitous UI framework across all relevant platforms

**Comment by kingces95** [comment]
Might want to ask this question in the XF forum. This venue accepts bugs and enhancements. We'll keep it here but you'll likely get more traction in the forum.

**Comment by BradChase2011** [comment]
I think the main hold up here is waiting for Mono to catch up.  Once WebGL and the rest of the bindings are in place then the renderer work is the easy part.  Hell once WebGL is in I think you will see a ton of custom solutions start to pop up.

**Comment by DierkDroth** [comment]
Thanks. I posted [an inquiry ](https://forums.xamarin.com/discussion/146228/what-are-the-considerations-to-officially-support-webassembly-html5#latest)on the XF forum
