### ISSUE TITLE
Tab through list of entries doesnt work

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#4673]
### Description
Cannot tab through list of Entries.

I have a list of entries and I am using the "Tab" button on the keyboard on all 3 platforms.

### Steps to Reproduce

1. Create list of entries
2. Press tab
3. see it doesnt work

### Expected Behavior
tab to next entry in thelist

### Actual Behavior
nothing happens

**Comment by kingces95** [comment]
Tabbing only works with a physical keyboard. So that'd be all desktop platforms or an attached bluetooth keyboard. FYI, It also affects accessibility. 

Possibly related: https://github.com/xamarin/Xamarin.Forms/issues/4561

**Comment by JKennedy24** [comment]
@kingces95 I am using a bluetooth keyboard on my samsung galaxy tab. 

here is my code:

     <ListView Grid.Row="1" ItemsSource="{Binding Milage}" SelectionMode="None">
                                <ListView.ItemTemplate>
                                    <DataTemplate>
                                        <ViewCell>

                                            <Grid CompressedLayout.IsHeadless="{StaticResource CompressionLayoutOn}" RowSpacing="0">
                                                <Grid.ColumnDefinitions>
                                                    <ColumnDefinition/>
                                                    <ColumnDefinition Width="100"/>
                                                </Grid.ColumnDefinitions>

                                                <Grid.RowDefinitions RowSpacing="1">
                                                    <RowDefinition Height="49"/>
                                                    <RowDefinition Height="1"/>
                                                </Grid.RowDefinitions>

                                                <Label Margin="5,0,0,0" FontSize="{styling:Font 16}" VerticalOptions="Center" Grid.Column="0" Text="{Binding Date, Converter={StaticResource DateToLocalisedStringConverter}, ConverterParameter=DateFormatLong}">
                                                    <Label.Triggers>
                                                        <DataTrigger TargetType="Label" Binding="{Binding BusinessMiles, Converter={StaticResource NullToTrueConverter}}" Value="True">
                                                            <Setter Property="TextColor" Value="{StaticResource InCompleteColour}"/>
                                                        </DataTrigger>
                                                    </Label.Triggers>
                                                </Label>
                                                <Entry  x:Name="milage" TabIndex="{Binding SortKey}" VerticalOptions="Center"  Grid.Column="1" Margin="1" Text="{Binding BusinessMiles, Mode=TwoWay}" TextColor="Black" MinimumWidthRequest="30"/>
                                                <BoxView Grid.Row="1" Grid.ColumnSpan="2" Color="{StaticResource SecondarySeperatorColour}" />
                                            </Grid>
                                        </ViewCell>
                                    </DataTemplate>
                                </ListView.ItemTemplate>

**Comment by BrayanKhosravian** [comment]
@bruzkovsky
