### ISSUE TITLE
[Enhancement] Support drag-and-drop reordering in CollectionView

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#4676]
## Summary
Support drag-and-drop reordering in `CollectionView`.

## API Changes

```
public static readonly BindableProperty ReorderModeProperty;
public CollectionViewReorderMode ReorderMode { get; set; }

public enum CollectionViewReorderMode {
     Disabled,
     Enabled
}
```

When ReorderMode is set to **Enabled**, the view supports drag-and-drop reordering.
Upon dragging an item in the collection, the **Move()** method on the `ObservableCollection<T>` is called to signal the change to the dataset.

## Intended Use Case
Reordering a collection of elements ie. tasks, reminders, photos, tracks in a playlist etc.

## Other Notes

- Supported in iOS 9 and above+ in `UICollectionView`.
https://github.com/xamarin/ios-samples/tree/master/ios9/CollectionView

- Supported on Android in `RecyclerView` using `ItemTouchHelper`.
- Supported on UWP in `GridView`using `CanReorderItems="true"` and `ReorderMode`.

**Comment by velocitysystems** [comment]
As a side note, we have built custom renderers for XF 3.3/3.4 to bring this functionality to `ListView`.
We currently have this supported on Android, iOS and UWP.

**Comment by velocitysystems** [comment]
@samhouts @hartez Would be happy to work on a PR for this if approved.

**Comment by bbl-Laobu** [comment]
Also: Drag and drop onto another item

Being able to drag and drop onto another item and having an event triggered that provides a references to the item that was dragged and the element that was dropped onto would be great as well.
 
Thus: drag item -> drop onto other item -> trigger event 

Use case: 
- Manually group: move item onto other item to create folder 
- Move item in folder; in a collection containing both items and folders, drop items into folders... (= how file explorer works)
- Perform action when 2 items are combined (perform calculation, transform, start process...)
- ... 

Having drag and drop and the corresponding event when dropping would allow a developer to do this.
Note that proper visuals will need to be present when dragging, dropping, hovering above and item...etc

**Comment by peterfournier** [comment]
@bbl-Laobu I'm working on a nuget for this feature here [DragNDrop](https://github.com/peterfournier/Xamarin.Forms.DragNDrop). Working on the iOS implementation now.

**Comment by adrianknight89** [comment]
I believe this should be supported by XF (i.e. no need for a separate Nuget).

**Comment by velocitysystems** [comment]
@adrianknight89 Agree

**Comment by adrianknight89** [comment]
@velocitysystems You could go ahead and submit a PR if you have it working already. I don't see a reason against this feature. I'd change the property name though. `ReorderMode` sounds like an enum not a boolean. Maybe try `Draggable`? Also, as mentioned above, it'd be nice to have proper events (DraggingStarted, Dragging, DraggingEnded, etc.) along with source and target items.

Other things to keep in mind:

- How will this work in the case of grouped items?
- Needs to be tested in linear and grid layouts
- Needs to be tested in portrait and landscape modes
- Will this be supported only by CollectionView? What about CarouselView?
- Needs to be tested with ObservableRangeCollection in addition to the typical collections/lists
- Is there a way to cancel dragging while it's in progress? Sometimes this might be needed upon UI errors or new items being added to the data source after DB fetch.
- Can drop animations be customized?

**Comment by marcojak** [comment]
This would be a great addon to a CollectionView.
Any news about it?

**Comment by dinobu** [comment]
I hope this will be supported on all 3 platforms (UWP, iOS, and Android) in Xamarin.Forms

**Comment by steckenpferd** [comment]
Any Status Update - this would be great !!

**Comment by CliffAgius** [comment]
Is anyone actually working on this? Nobody assigned is all.

There is the Nuget of SharpNado - https://github.com/roubachof/Sharpnado.Presentation.Forms that already does most of this so maybe rather than re-invent the wheel this can be pulled in.  I've used it on a project and it's fantastic.

Obviously would need to ask @roubachof if thats Ok...

**Comment by EmilAlipiev** [comment]
@CliffAgius this is similar way what SfListview and SfGrid from syncfusion is doing. They dont use listview but using grid they create a listview. I dont like this because it has many disadvantages. we need actual listview or collectionview to implement this functionality. At least they can get the dragging functionality from this library.
This is actually a powerful feauture but i dont understand why xamarin doesnt give it to a priority

**Comment by ske66** [comment]
My issue with the Sharpnado library is the Horizontal "ListView" is not a listview at all. I assumed it would have inherited from either a Collection or Listview but instead is inherits from View. This means that some features such as properties like SelectedItem are not included. You won't be able to apply her changes to the Xamarin ListView. @peterfournier looks like your PR is the most likely candidate

**Comment by roubachof** [comment]
@CliffAgius would be happy to help :)
The issue is that the `CollectionView` has its own set of abstractions and architecture, so it would require quite some time to adapt to those. 
Also, it's really easy to implement drag n drop with `RecyclerView` and `UICollectionView`. So I guess it would be way easier to implement it starting from their architecture than trying to blend in my implementation.

**Comment by Kalyxt** [comment]
What about raising a reward for someone who will do it ? 🍡

**Comment by jamsoft** [comment]
> 
> 
> @bbl-Laobu I'm working on a nuget for this feature here [DragNDrop](https://github.com/peterfournier/Xamarin.Forms.DragNDrop). Working on the iOS implementation now.

Did you get anywhere with iOS Peter?

**Comment by jamsoft** [comment]
> Also, it's really easy to implement drag n drop with `RecyclerView` and `UICollectionView`. So I guess it would be way easier to implement it starting from their architecture than trying to blend in my implementation.

Do you have any links to examples of doing this?

**Comment by roubachof** [comment]
yup it's implemented in my Component here: 

https://github.com/roubachof/Sharpnado.Presentation.Forms/blob/master/Sharpnado.Presentation.Forms.iOS/Renderers/HorizontalList/iOSHorizontalListViewRenderer.DragAndDrop.cs

**Comment by jamsoft** [comment]
> 
> 
> yup it's implemented in my Component here:
> 

I cannot thank you enough. Much appreciated.

One question. When in Grid Layout mode with a single column is it also possible to have any form of grouping? With a group header view?

If not, I wonder where would be a good place to start on adding that feature IYO?

**Comment by roubachof** [comment]
maybe it would be good idea to open a feature issue on the [Sharpnado's repo] (https://github.com/roubachof/Sharpnado.Presentation.Forms/issues) and discuss it there cause I'm afraid we would mess this issue if we continue our discussion.

**Comment by velocitysystems** [comment]
Just an update - with the announcement of Maui, I'm a little hesitant to put too much time into new feature work on XF now, but just focusing on bug fixes. Perhaps in the meantime, would be best to focus on implementing this in a separate NuGet package which can be bolted onto XF.

**Comment by jfversluis** [comment]
This would be soooo cool to have! And I see there is a lot of traction on this. I've put it on a list to make sure we have a look at this for .NET MAUI. Sadly, it won't happen for Forms anymore. If you have any detailed ideas about this, make sure to open a request on the .NET MAUI repo with all the details that you have on how you would like to use this.

Thanks everyone for the time and effort that you put into this!

**Comment by billvenhaus** [comment]
I completed implementations for this in both Xamarin Forms & .NET MAUI.

Here's the spec & pull request I submitted for .NET MAUI:
https://github.com/dotnet/maui/issues/3767
https://github.com/dotnet/maui/pull/3768

@jfversluis  would you be at all interested in having me submit this into the Xamarin Forms repo as well? Perhaps a new branch that way you have it just in case? I've got it ready to go here:
https://github.com/billvenhaus/Xamarin.Forms/commit/50c801958ea986d3c0729da47346e858f391df3e

Here are some standalone packages I wrote that everyone can use for the time being:
https://github.com/billvenhaus/ReorderableCollectionView.Forms
https://github.com/billvenhaus/ReorderableCollectionView.Maui

**Comment by jfversluis** [comment]
@billvenhaus you're the GOAT! This stuff is amazing, thank you for pouring this into specs and even code. 

Like stated: I would love to have this in Forms, but at this time we can't add anything new because that will only add to the load of maintaining this while that is something that we want to phase out. I think this will be a great addition to .NET MAUI though, so let's see how it goes there :)
