### ISSUE TITLE
Declaring FontSize in shared label causes Java.Lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by D4rkC1own187** [xamarin/Xamarin.Forms#4677]
### Description
When using a shareable label and setting the font size from in a list view' cell, the app crashes. If you remove the font size, the app does not crash.

Seems to be any ViewCell. Reproduce the same issue using a TableView.

### Steps to Reproduce
1. 
Create a Forms Class Library.
Create a BaseLabel.
Create a SharedLabel that extends BaseLabel
2. 
Create Android Class Library
Reference Forms Class Library from step 1.
Create custom BaseLabelRenderer from BaseLabel
3. 
Create a Blank Forms App
Referenced Forms Class Library from step 1.
Create a ContentView with elements. Use a SharedLabel in the ContentView
Create a ContentPage with a ListView that uses ContentView as ViewCell
4.
Run application and get a Java.Lang.ArrayIndexOutOfBoundsException
If you remove the FontSize in SharedLabel, app does not crash.
If you remove the FontSize in ShareLabel but declare the FontSize in xaml, the app crashes.

**Works on iOS.**

### Expected Behavior
Show Content Page
### Actual Behavior
Crashes with Java.Lang.ArrayIndexOutOfBoundsException
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Mac Visual Studio 7.7(1868)
- Android Library: 27.0.2
- Platform Target Frameworks: 
  - Android: API 19 

### Screenshots
https://ibb.co/6s2R5CK

### Reproduction Link
Repro project
https://drive.google.com/file/d/1uGLdq1_stQZOal_NtuMD4oFj3N1r9Ujo/view?usp=sharing

Repro project with Xamarin.Forms 3.4.0.1008975
https://drive.google.com/open?id=1bwtrhLdSc009f0pM2Os7wH8keXixWGdk

**Comment by kingces95** [comment]
Dang. Getting some very odd build errors...

**Comment by D4rkC1own187** [comment]
What building errors are you receiving?

**Comment by kingces95** [comment]
Saying Forms doesn't exist in Xamarin after updating. Could you update to latest nightly, clean, and submit the repro again?

**Comment by D4rkC1own187** [comment]
Repro project with Xamarin.Forms 3.4.0.1008975. Updated and clean.
https://drive.google.com/open?id=1bwtrhLdSc009f0pM2Os7wH8keXixWGdk

**Comment by hartez** [comment]
The problem is in your `BaseLabelRenderer` class. In `OnElementPropertyChanged`, you are doing this:
```
Control.SetLines(lameLabel.MaxLines);
```

If the value of `lameLabel.MaxLines` is -1, this will throw an `ArrayIndexOutOfBoundsException`. You need to check the value of `lameLabel.MaxLines` before calling `Control.SetLines()`.
