### ISSUE TITLE
[Enhancement] Add a property to Image that will indicate you want EmbeddedResources to load scaled to device aspect ratio

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4680]
### Description
https://forums.xamarin.com/discussion/comment/355760?

If you load an image that is an EmbeddedResource it will just load the image at the exact pixel dimensions of the image. If the image is a BundledResource (iOS) or an AndroidResource then when it's loaded the dimensions will be Image.Dimensions * Scale

Images loaded from EmbeddedResources should have the option to scale based on the aspect ratio of the device

```C#
public class Image
{
       public ImageScaleRatio DeviceScale {get;set;} //BP
}
public class ImageButton
{
       public ImageScaleRatio DeviceScale {get;set;} //BP
}

public class Button
{
       public ImageScaleRatio DeviceScale {get;set;} //BP
}

enum ImageScaleRatio
{
     Default,
     ScaledToDeviceAspectRatio
}
```

### Steps to Reproduce
Run the attached Sample and you can see the difference with loading an image that is Embedded into a shared library vs loading the image as a resource that's part of the native project

### Reproduction Link
[ImageWidth.zip](https://github.com/xamarin/Xamarin.Forms/files/2659057/ImageWidth.zip)

**Comment by PureWeen** [comment]
> 👎

👍 
 

> 2/ a better name would involve `Scale` or something

 public ImageScaleRatio DeviceScale {get;set;} //BP  ?

> 3/ shouldn't this be a property of the ImageSource, not the Image ?

How would this be surfaced in XAML? I thought about having it on ImageSource but all the *ImageSource* properties on our components just take a string that gets converted to an ImageSource so the *ImageSource* is kind of hidden from the user.  I was thinking maybe adding a static default as well like *ImageSource.SetDeviceScaleLoadDefault()* in case the user wanted to just not have to set that all the time

**Comment by GalaxiaGuy** [comment]
Could it be specified via a markup extension?

```csharp
<Image Source="{ImageResource Source=MyApp.image.jpg, DeviceScaleRatio=ScaledToDeviceAspectRatio}"/>
```

**Comment by StephaneDelcroix** [comment]
there's no need for  markupextension, Image.Source already have a [TypeConversion]

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
