### ISSUE TITLE
GTK ListView.ItemAppearing triggers for every item on the list even when they are not visible

### ISSUE THREAD

**Issue by egarim** [xamarin/Xamarin.Forms#4682]
### Description
ItemAppearing triggers for every item on the list even when they are not visible
### Steps to Reproduce

1) Create a list view and set the item source to an observable collection
2) add items to the observable collection, you need to add enough items to have some of them visible and the for the others you need to scroll.
### Expected Behavior
The event ItemAppearing  should trigger only for the visible items of the listview, if you add more items to the itemsource and they are not visible, the event should not trigger, it should only trigger when you start scrolling and the items become visible 
### Actual Behavior
No matter if the items are visible or not the event trigger for all the items, if you add more items to the itemsource the event trigger even when they are not visible yet
### Basic Information

- Version with issue: 3.4.0.1008975 and greater 
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: GTK on windows
  

- Nuget Packages:
<package id="Xamarin.Forms" version="3.4.0.1008975" targetFramework="net47" />
 <package id="Xamarin.Forms.Platform.GTK" version="3.4.0.1008975" targetFramework="net47" />
- Affected Devices: Windows 10

### Reproduction Link
[infinite.zip](https://github.com/xamarin/Xamarin.Forms/files/2659428/infinite.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
