### ISSUE TITLE
Xamarin 4.0.0.8055-pre1 Shell doesn't load the Stylesheets on first presenting pages

### ISSUE THREAD

**Issue by MiltoxBeyond** [xamarin/Xamarin.Forms#4683]
### Steps to Reproduce

1.  Add Multiple Pages to a Basic Shell Application
2.  Add Stylesheets with simple non-white background-color style applied to ^contentpage in App.xaml
3.  Build & Run app
4.  First load of the pages will be all white default backgrounds

### Expected Behavior

Pages load with defined styles each time

### Actual Behavior

Pages load with default backgrounds the first time, then when you navigate away and back it'll load the styles properly.  But it should be loading from the start.

### Basic Information

- Version with issue: 4.0.0.8055-pre1
- Last known good version: n/a
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 9.0  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![screenshot_20181208-031723](https://user-images.githubusercontent.com/7705397/49683773-2fe04500-fa98-11e8-8a43-c5841d26cbca.jpg)
![screenshot_20181208-031716](https://user-images.githubusercontent.com/7705397/49683774-2fe04500-fa98-11e8-8d44-6fbd2643b704.jpg)
![screenshot_20181208-031832](https://user-images.githubusercontent.com/7705397/49683775-34a4f900-fa98-11e8-9b46-627287fe5214.jpg)
![screenshot_20181208-031838](https://user-images.githubusercontent.com/7705397/49683776-34a4f900-fa98-11e8-93bf-a64dc66015ac.jpg)

### Reproduction Link

There is no special code in here just a default template with stylesheets added.
My Stylesheet is:
 
```
^contentpage {
    background-color: #04A0FF;
    color:#FFF;
}

```
Parent: #2415

**Comment by hartez** [comment]
Repro:
[_4684 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2665421/_4684.Repro.zip)

**Comment by samhouts** [comment]
This is still an issue, but it presents differently now. It no longer applies the stylesheet at all on subsequent loads.
