### ISSUE TITLE
Xamarin 4.0.0.8055-pre1 Shell Crashes when navigating too quickly

### ISSUE THREAD

**Issue by MiltoxBeyond** [xamarin/Xamarin.Forms#4684]
### Steps to Reproduce

1.  Create AppShell Application
2.  Create 3 ContentPages
3.  Setup shell like so:
```xml
<Shell xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Example"
             RouteScheme="app" 
             RouteHost="example.com"
             Route="main"
             x:Class="Example.AppShell">
    <ShellItem Title="Home" Route="Home">
        <ShellSection>
            <ShellContent>
                <local:HomePage />
            </ShellContent>
        </ShellSection>
    </ShellItem>
    <ShellItem Title="Connect" Route="connect">
        <ShellSection>
            <ShellContent Title="Connect">
                <local:ConnectPage />
            </ShellContent>
            <ShellContent Title="Control">
                <local:ControlPage />
            </ShellContent>
        </ShellSection>
    </ShellItem>
</Shell>
```

### Expected Behavior

Since all the pages are basically just the defaults, we expect to have all the navigation be quick and simple.

### Actual Behavior

If you navigate back and forth between pages with tabs and the pages without and move back and forth fairly quick the app crashes when you click on the hamburger with a NullReferenceException without much information to help on the first exception.  It may not happen on the first click of the hamburger icon but if you go back and forth and toggle between pages in the tabs it should be reproducable.

![image](https://user-images.githubusercontent.com/7705397/49683936-674ff100-fa9a-11e8-9c41-f78865f56d7d.png)

The second unhandled exception does have a clue:
![image](https://user-images.githubusercontent.com/7705397/49683978-fa892680-fa9a-11e8-81a6-65dc279904ff.png)

I also verified that it isn't related to the other issue I submitted at https://github.com/xamarin/Xamarin.Forms/issues/4683 by removing the styles and just letting it run by default themes

### Basic Information

- Version with issue: 4.0.0.8055-pre1
- Last known good version: n/a
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0-preview8
- Affected Devices: OnePlus 6, Emulator

**Comment by MiltoxBeyond** [comment]
I did verify this is specifically if you make the app have top tabs.  If you do instead:

```xml
    <ShellItem Title="Connect" Route="connect">
        <local:ConnectPage />
        <local:ControlPage />
    </ShellItem>
```
The app seems to be more stable.  Nevertheless the bug still exists for the top tabs.

**Comment by hartez** [comment]
Confirmed. Here's the repro:
[_4684 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2665404/_4684.Repro.zip)
