### ISSUE TITLE
Drop .net standard 1.0 target framework 

### ISSUE THREAD

**Issue by ysmoradi** [xamarin/Xamarin.Forms#4685]
Xamarin Forms 3.0 requires us to have .NET standard 2.0 supported runtime such as UWP16299, .NET 461 etc which is absolutely fine.

But I can't understand why csproj files have target framework for .net standard 1.0!
I was adding [SeriazliableAttribute] to Xamarin Forms exception classes based on the following recommendations:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/creating-and-throwing-exceptions#defining-exception-classes

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1064-exceptions-should-be-public?view=vs-2017

But I wasn't able to do that. Because [Serializable] attribute is added on .net standard 2.0 and it's not supported on .net standard 1.0

When a project targets .net standard 2.0, it aims to use its cool features, but it's not easily possible in Xamarin Forms's current structure.

I'm getting serialization exception instead of XamlParseException regularly on my projects and it's annoying )-:

Thanks in advance.

**Comment by StephaneDelcroix** [comment]
long story short, the netstandard1.0 support is there so we keep supporting projects still targeting PCL. We will eventually drop netstandard1.0 support, but now is not the time yet.

it's fine to add ns20 features only, like exception serialization, and wrap that code in
```
#if NETSTANDARD2_0`

#endif
```.
