### ISSUE TITLE
[Android] StackLayout.LayoutChildren null ref XF 3.4

### ISSUE THREAD

**Issue by Liam2349** [xamarin/Xamarin.Forms#4689]
First time reporting a bug. I hope this is an acceptable format. I have provided as much detail as I can, with a video of the issue, with timestamps, and a proposed solution at the end of this post. I use my own private source control server for my projects, so I'm also new to GitHub.

### Description
When modifying a StackLayout, a null reference exception is raised in Xamarin.Forms.Core.StackLayout.cs:66. The Plots and Requests properties of the layoutInformationCopy (and _layoutInformation) are null. This occurs on Android, when the app is minimized. I don't think this exception has been raised when the app is maximized. I guess it may have something to do with the activity being suspended.

I determined this by forking the Xamarin.Forms source and debugging it, thanks to this very helpful post by Jon Goldberger: https://blog.xamarin.com/debugging-xamarin-forms/

I followed his instructions, and used my own fork to figure out the above crash point. Prior to following the guide, I only knew that there was a null ref in the StackLayout.LayoutChildren method.

Looking through the code, you may wonder how these properties can be null, because in my testing, CalculateLayout is ALWAYS called before this exception is raised, and CalculateLayout sets these properties to non-null. I have found that if I set a conditional breakpoint before the call to CalculateLayout, for when _layoutInformation.Plots is null, and if I then F11 into CalculateLayout and F10 over everything in there, then the Plots and Requests properties are ALWAYS non-null. However, if I hit that break point, and then F5 over the method, there is a very good chance that the properties will still be null after executing CalculateLayout, leading to a null ref on line 66.

Perhaps you guys who know more about the framework will know more about how this could happen. I've not been looking at the code for very long, but I cannot see how these properties could be null. It's like there's a glitch at a deeper level.

As it's such an odd issue, I decided to make a video. Some parts are sped up, and some are slowed down, to shorten the video and make some points more clear. I also blurred a few things for privacy: https://www.youtube.com/watch?v=88mGjcyWvWg&feature=youtu.be

In the video, you can see my desktop, running VS 2017, and the WPF version of my Clipboard Everywhere app. This WPF version doesn't show the problem, but is used to demonstrate the problem on Android by sending a file to my phone, one of my new features I wanted to release soon. WPF app sends a file to the Android app, which is currently being debugged on my Note 9. The app loads, initializes, and then I minimize it. I then send the file from WPF, and if I F5 over the CalculateLayout method, the Plots and Requests properties have a good chance to be null, crashing the app. When the file is sent, this causes the layout to update. It seems the issue is close to the visibility of child items in the main StackLayout for the page. The points where the crash occur are near where these child items are made visible and invisible, but I'm not sure how to narrow it down further.

**Timestamps:** 
* 0 to 00:23, demonstrating the null ref, I actually didn't expect this part to crash. It's a bit unstable.
* 00:28 to 02:07, demonstrating that, when stepping through the method, the Plots and Requests properties are never null
* 02:10 to end, demonstrating that the properties can be null when skipping the method with F5

The "child" always seems to be a StackLayout containing two children, which are both custom controls I made, however that's only what "child" refers to because it can't progress through the loop, due to the null properties. Here is the full Layout of the page. It's hosted in a TabbedPage, inside a NavigationPage: https://pastebin.com/YyrBMywr

The StackLayout with the two children is the one that's very near the top, with Orientation="Horizontal". I use the CustomEntry and ImageButton (my own version, made it a bit back, it's actually not displaying images but FontAwesome icons), frequently through my apps, and haven't seen this issue anywhere else.

The layout_SendingFiles, scrollView_CurrentPath and layout_Files all contain dynamic content. Controls are added at runtime but I don't delete them, I found it better performance-wise to cache them for re-use, so they have their IsVisible set to False when not in use. When being used again, I set their properties as appropriate for the new content they are displaying. However, I have to manually set the heights of each control in the Files layouts, and the heights of the Files layouts themselves, each time the layouts are updated, as the controls seem to inexplicably double in height every time I re-use them. Perhaps this relates to a different bug in the framework. I've had to redesign a layout to avoid that issue before.

### Steps to Reproduce
I can't share my code, and I'm not sure if I will be able to make another project to reproduce this issue. I don't have time travel debugging, which I feel could be useful here, so I'm not sure how to investigate this further.

Reproducing this issue currently depends on having the Android app, the WPF app, and the web service running.

```C#
class CustomLabel : Label
{
	protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
	{
		var returnValue = base.OnMeasure(widthConstraint, heightConstraint);
		InvalidateMeasureInternal(InvalidationTrigger.MeasureChanged);
		return returnValue;
	}
}

public Page CreateDefaultMainPage()
{
	return new ContentPage()
	{
		Content = new StackLayout()
		{
			Children = 
			{
				new CustomLabel()
			}
		}
	};
}
```

### Expected Behavior
Not crashing.

### Actual Behavior
Crashing due to null ref

### Basic Information

- Version with issue: 3.4
- Last known good version: Unknown. Looks like StackLayout is not changed very frequently.
- IDE: VS 15.9.2
- Platform Target Frameworks:
  - Android: v9, API 28
- Android Support Library Version: v27.0.2.1
- Nuget Packages: Lots. Can I get a list somewhere from VS?
- Affected Devices: Galaxy Note 9 Exynos, unsure if it would happen on others. I would like to test the emulators but they don't use bridged networking so the particular software feature I've developed that raises this problem doesn't work as the emulators don't get their own IP.

### StackTrace
{"Source":"Xamarin.Forms.Core","StackTrace":" at Xamarin.Forms.StackLayout.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x000b4] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\StackLayout.cs:66 <br/> at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x00166] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:263 <br/> at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x00011] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:223 <br/> at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00001] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\VisualElement.cs:801 <br/> at Xamarin.Forms.VisualElement.SetSize (System.Double width, System.Double height) [0x0002c] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\VisualElement.cs:1033 <br/> at Xamarin.Forms.VisualElement.set_Bounds (Xamarin.Forms.Rectangle value) [0x00069] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\VisualElement.cs:277 <br/> at Xamarin.Forms.VisualElement.Layout (Xamarin.Forms.Rectangle bounds) [0x00001] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\VisualElement.cs:687 <br/> at Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion (Xamarin.Forms.VisualElement child, Xamarin.Forms.Rectangle region) [0x00211] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:177 <br/> at Xamarin.Forms.ScrollView.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x00095] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\ScrollView.cs:201 <br/> at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x00166] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:263 <br/> at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x00011] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:223 <br/> at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00001] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\VisualElement.cs:801 <br/> at Xamarin.Forms.Layout+<>c.<OnChildMeasureInvalidated>b__45_0 () [0x00094] in C:\\Repos\\Xamarin.Forms-Forked\\Xamarin.Forms.Core\\Layout.cs:380 <br/> at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <2530aa2e412d4754af3ae7e1a8c80b6d>:0 <br/> at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <2530aa2e412d4754af3ae7e1a8c80b6d>:0 <br/> at (wrapper dynamic-method) System.Object.23(intptr,intptr)","InnerException":null,"Message":"Object reference not set to an instance of an object."} 

### Screenshots
This image shows an attempted fix, by including a null check, but the check passed and the null got through.

The three breakpoints are conditionals for when _layoutInformation.Plots is null. The first was hit, the second two were not. Looks like Plots was set to null after leaving the else block.
<img width="935" alt="stacklayoutbug_nullcheckpassed" src="https://user-images.githubusercontent.com/18562068/49692473-ad1cc000-fb53-11e8-984f-fb1ad63acacb.PNG">

### Proposed Solution
The best solution I have found so far is to try/catch the LayoutChildIntoBoundingRegion method. This seems to work without any negative effects that I can see, so far. It doesn't seem to cause any layout issues. Here are the changes I would like to propose for the StackLayout.LayoutChildren method: https://github.com/Liam2349/Xamarin.Forms/commit/4fe7f9215ae65b1ea65aaf8303464fd600a4595c

In addition to my try/catch, I removed the layoutInformationCopy variable, as it doesn't seem to be a copy. Perhaps someone mixed up their reference and value-types when writing that in?

It's 3AM here in the UK, and I've been at this for a few hours now, so I'll see how it goes tomorrow. I look forward to your responses. Please let me know if I've missed anything.

Thanks for reading and I look forward to your responses.

**Comment by kingces95** [comment]
Please try to reduce your reproduction and attach it as a zip file.

**Comment by Liam2349** [comment]
@kvpt Thanks for pointing that out. I think my intellisense has been having some issues, because I didn't see anything that set _layoutInformation to a new instance when I looked for all references to the field, aside from the original setting of the field.

I put a break point in InvalidateMeasureInternal, and it is called a lot, so it's probably the culprit. It seems to be called every time a label has its text changed, and there's a lot of label text being changed when this problem occurs.

Since I made this post, I've been using my proposed fix, and haven't experienced any issues since that I know of. I'm aware that exceptions are relatively expensive to deal with when compared to a null check, but I'm not sure what a better fix would be. Maybe someone could go deeper and prevent InvalidateMeasureInternal from being called at inopportune times, which seems to be whenever the Activity is minimized, but I imagine that would be a long fix, and I'm not sure of the knock-on effect that not calling this method could have. My try/catch seems like a pretty safe fix.

How do you determine what level of fix is acceptable? Because right now, I've got to keep using my own fork until something gets fixed in the official version.

@kingces95 I don't think I can manage a repro project. I'm not even sure of the exact cause here, and there's a lot of code surrounding the problem. I just happened to be able to find a simple fix to it.

**Comment by PureWeen** [comment]
I'm able to reproduce with this code. My guess is that your custom controls are causing the measure to get invalidated during the OnMeasure method or somewhere similar

This should definitely be fixed from our side but maybe this will give you enough info to modify how your custom controls work so you can get back to just using our packages

```C#
class CustomLabel : Label
{
	protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
	{
		var returnValue = base.OnMeasure(widthConstraint, heightConstraint);
		InvalidateMeasureInternal(InvalidationTrigger.MeasureChanged);
		return returnValue;
	}
}

public Page CreateDefaultMainPage()
{
	return new ContentPage()
	{
		Content = new StackLayout()
		{
			Children = 
			{
				new CustomLabel()
			}
		}
	};
}
```

**Comment by Liam2349** [comment]
@PureWeen Sorry for the late response. I'm glad that you managed to reproduce the issue from my limited info.

However, looking at your code, it seems that your reproduction depends on overriding OnMeasure, but I have not done this in any of my controls, so I'm not sure what to take away from this in regards to modifying my own controls. I would like to go back to the official package, but for the time being it's not an issue for me, as thankfully the small fix I made has been perfectly stable.

**Comment by PureWeen** [comment]
I did it that way to more explicitly cause the exception but there are a lot of different things that will cause *InvalidateMeasureInternal* to be called. My guess is that the custom control is changing something which causes *InvalidateMeasureInternal* to be called. For example, on a label if you change the text, font, etc.

We have this issue scheduled for this sprint so we should have it resolved here soon and then we can make sure it resolves your issue
