### ISSUE TITLE
[Enhancement] SecurityException from Forms.Maps with explicit target SDK

### ISSUE THREAD

**Issue by Magendanz** [xamarin/Xamarin.Forms#4691]
### Description
https://github.com/xamarin/Xamarin.Forms/issues/4691#issuecomment-450898431

When providing an explicit targetSdkVersion, OnMapReady() throws a Java.Lang.SecurityException which does not occur when "Use Compile using SDK version" is selected.

Message: "Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION"

Note that these permissions are defined in the manifest, and maps are displayed as expected if the explicit target SDK is not used.  Unfortunately, since October the Google Play Store will no longer allow us to submit apps without an explicit targetSdkVersion defined.  (It mistakenly assumes that the target is the minSdkVersion.)

### Steps to Reproduce

1. Create a blank Xamarin Forms shared project (accept all defaults)
2. In NuGet Package Manager, add Xamarin.Forms.Maps and update all packages to latest stable versions
3. Replace Label on MainPage.xaml with a Map control.  Set IsShowingUser to "true".
4. Add required permissions and API key to manifest.
5. Launch project (in Debug or Release, on device or simulator)

### Expected Behavior
Should just show basic map of Rome with My Location button.

### Actual Behavior
Unhandled exception: "Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION" in Xamarin.Forms.Maps.Android.MapRenderer.OnMapReady() when setting MyLocationEnabled on the GoogleMap.

If you then set the Target Android Version to "Use Compile using SDK version", rebuild and relaunch, the app behaves as expected.

### Basic Information

- Version with issue: v3.4.0.1008975
- Last known good version: Unknown
- IDE: VS 2017 v15.9.3
- Platform Target Frameworks: 
  - Android: 8.1 (Oreo)
- Android Support Library Version: v9.1.0.38
- Nuget Packages: Xamarin.Forms.Maps v3.4.0.1008975 and latest stable dependencies
- Affected Devices: Android

### Reproduction Link

[MapDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/2661186/MapDemo.zip)

**Comment by jcmanke** [comment]
Are you requesting location permission from the user before you set `IsShowingUser = true`?

This can only be considered an SDK issue if you were previously compiling on an SDK version less than 6.0, when all permissions were granted at install time rather than at runtime, and you're only discovering now changes that were made to Android 3 years ago.

**Comment by Magendanz** [comment]
And yet I've been deploying successfully to devices running Android 5.0 to 9.0 until now simply by setting the Target Android Version to "Use Compile using SDK version", just as is shown in all the Xamarin.Forms.Maps sample code.  It's only the new Google Play Store requirement (which is inexplicably ignorant of the compile target SDK) which makes that workaround now infeasible.

Ultimately, I was able to get my app restored on the Google Play Store yesterday by using Plugin.Permissions from James Montemagno, but it seems odd that deploying a product using Xamarin.Forms.Maps effectively requires a 3rd-party plug-in to function on Android.  At the very least, Xamarin should provide sample code showing an implementation of runtime permissions that eliminates that dependency.

Alternatively, Xamarin could roll Plugin.Permissions into Xamarin.Essentials.  Currently, the code is there but it's been made internal.

**Comment by jamesmontemagno** [comment]
So if you set the Target version to Marshmellow or above you will need to get permission to show the user location. You can do this via: https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/ or by using my plugin to handle this for you: https://montemagno.com/simplified-ios-android-runtime-permissions-with/

I do think Forms should attempt to handle this automatically though like we do for Xamarin.Essentials.
