### ISSUE TITLE
Setting Margin on items in CollectionView has no effect

### ISSUE THREAD

**Issue by rasmuschristensen** [xamarin/Xamarin.Forms#4692]
### Description
Running the CollectionView sample app using  Forms 4.0-pre (4.0.0.8055-pre1) I tried to make space between items by setting the Margin of the Frame. This has no effect and I was unable to make any spacing between the elements

### Steps to Reproduce

1. Run the sample from the github repo
2. Set a Margin to a value like 5 or 10 on the Frame in the itemtemplate of the GridListPage
3. Run

### Expected Behavior
Space between elements

### Actual Behavior
No change in the UI

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by pauldipietro** [comment]
See #4681 which should resolve this. Perhaps we could take the Margin into consideration but it would probably be best to keep this localized to a singular issue.
