### ISSUE TITLE
Latest Xamarin.Forms (v 3.4.0.1008975) is not compiling on our windows machine

### ISSUE THREAD

**Issue by ojasteredesai** [xamarin/Xamarin.Forms#4694]
### Description

The latest xamarin forms build (v 3.4.0.1008975) is not compiling on our windows machine.
We have created a sample application and got below errors.

**When we downgraded Xamarin.Forms to v 2.5.0.280555, The project is compiling and deployed to both IOS and Android devices.**
****
### Steps to Reproduce

1. Create a sample xamarin forms app and run the project.

### Expected Behavior
The application should be complied and run on device or emulator.
### Basic Information

- Version with issue: xamarin forms build (v 3.4.0.1008975) 
- Last known good version:
PFA visual studio details and sample project.
1. [Visual studio version info.txt](https://github.com/xamarin/Xamarin.Forms/files/2663041/Visual.studio.version.info.txt)

2. [App1.zip](https://github.com/xamarin/Xamarin.Forms/files/2663042/App1.zip)

### Screenshots
![image](https://user-images.githubusercontent.com/22704125/49731274-d1d27e00-fca0-11e8-9ae9-c638ca99e780.png)

**Comment by hartez** [comment]
@ojasteredesai Is this problem still occurring? If you attempt to build again, do the errors persist? I just downloaded the attached project and hit build, and it built without errors.

**Comment by ojasteredesai** [comment]
Yes it is still occuring. I have attached the installed visual studio information file. Would you please check it and let me know if it is any updates for it required.

**Comment by StephaneDelcroix** [comment]
your projects is fine. what you're experiencing is some kind of caching of the build.tasks.

when updating xf, make sure to restart your IDE. also, some people reported similar issue with multiple instances of VS open at the same time.

also, you report an issue with v3.4, but your sample uses 3.0.0. 3.4 does not have a task with the name reported in the screenshot, but none of the .targets file distributed with 3.4.0 uses it either.

from an XF point of view, this, unfortunately, looks all fine
