### ISSUE TITLE
HorizontalTextAlignment not honored after 

### ISSUE THREAD

**Issue by AuriR** [xamarin/Xamarin.Forms#4698]
### Description
HorizontalTextAlignment not honored on Label in ListView when ObservableCollection item updated. A ListView, with a Horizontal StackLayout, and a label at the end with a "FillAndExpand" HorizontalOptions and HorizontalTextAlignment as "End" will render fine initially, but when the collection is updated, the HorizontalTextAlignment of the Label isn't honored.

### Steps to Reproduce

1. Git repo: URL https://aurir.visualstudio.com/Reptile%20Tracker **(email me and I'll add you)**
2. Launch app, and note on Scores page all items are right-aligned and 0
3. Use Take photo, take a photo, regardless, one score will update. Note the score is left aligned.

(see attached photos for repro)

![before change](https://user-images.githubusercontent.com/3044108/49775712-a3639b80-fcbe-11e8-869e-9e27d71fa610.jpg)
![after change](https://user-images.githubusercontent.com/3044108/49775718-a8c0e600-fcbe-11e8-90dc-c4775e81ffaf.jpg)

### Expected Behavior
Label should update with appropriate text and be right justified.

### Actual Behavior
Label is rendered left justified.

### Basic Information

- Version with issue: Confirmed with XF 3.3.0.967583 and 3.4.0.1008975
- Last known good version: (don't know, haven't checked)
- IDE: VS Mac and VS Windows - doesn't matter which VS IDE.
- Platform Target Frameworks: 
  - iOS:  (doesn't appear to matter, happens on Android and iOS) 
  - Android: (doesn't appear to matter, happens on Android and iOS)  
  - UWP: haven't checked, not targeting UWP
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
Android and iOS Simulators, Galaxy S9+ and iPhone XR, doesn't appear limited by device

**Comment by kingces95** [comment]
Can you provide a zip file containing a reproduction? Or add it to a private GitHub repo and add me as a contributor?

**Comment by AuriR** [comment]
I'll take care of that today.

**Comment by AuriR** [comment]
Here ya go: https://1drv.ms/u/s!AmKBMqPeeM_1gP2GXuKwDCYKn9m_qto

The repro steps above are from this solution. Thanks!

**Comment by AuriR** [comment]
CC @kingces95 That I've sent the repo zip above. Happy New Year!

**Comment by PureWeen** [comment]
@AuriR  Really cool app!!

So I'm testing the project you sent but for me everything is staying justified correctly
Maybe send me a gif? 

![image](https://user-images.githubusercontent.com/5375137/50665423-de7b8680-0f6d-11e9-8db2-5375ae73a95e.png)


![image](https://user-images.githubusercontent.com/5375137/50666039-416e1d00-0f70-11e9-97ad-a44304164a48.png)

**Comment by AuriR** [comment]
@PureWeen Right - the app as it stands works. Here's the ItemTemplate to use to repro the issue. Sorry, I thought I had included it:
```
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <StackLayout Orientation="Horizontal" HorizontalOptions="Fill">

                                <Image Source="{Binding Icon}" />
                                <Label Text="{Binding Name}" FontSize="36" VerticalTextAlignment="Center" HorizontalOptions="Fill" />
                                <Label Text="{Binding Score}" HorizontalTextAlignment="End" VerticalTextAlignment="Center"  HorizontalOptions="FillAndExpand" FontFamily="{StaticResource ScoreFont}" FontSize="36" />

                            </StackLayout>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
```

**Comment by PureWeen** [comment]
Hmm I'm still not having any luck reproducing. I'm probably misinterpreting one of your steps
Here's the project I'm using.  Can you test and modify to reproduce?
[ReptileTracker.zip](https://github.com/xamarin/Xamarin.Forms/files/2727999/ReptileTracker.zip)

**Comment by AuriR** [comment]
@PureWeen Will do.

**Comment by PureWeen** [comment]
@AuriR  yea I did this step
> Use Take photo, take a photo, regardless, one score will update. Note the score is left aligned.

It takes a photo and the number increments one but the score stays right aligned

**Comment by AuriR** [comment]
@PureWeen Thanks. I'll take a look! Odd. To be fair, I'm a bit confused how Fill works. I understand the descriptions, and watched on XamU, but I'm not clear that it always works as described. Maybe I'm using the wrong layout for doing things... mixing Horizontal StackLayouts in Vertical StackLayouts has been an issue for me recently. I'll fill background colors to see what's happening, and it's all over the place in width, even though Fill is used on the inside container. Not sure if there's a bug or there's a misunderstanding on my part, or both. Can you point me to where those width decisions/calculations are made in the XF codebase, and maybe I can watch what's happening? Maybe a screen sharing session would work, assuming you're on the XF team?

**Comment by stevehurcombe** [comment]
I don't have a reproducible example but I too see loss of alignment in all sorts of seemingly random scenarios. Clearly they aren't random, but there is something amiss.

**Comment by AuriR** [comment]
@stevehurcombe Thanks, I'll give that a shot. I can't use a pre-release in Production, though :-/

**Comment by rmarinho** [comment]
@AuriR any feedback if it worked with 4.0-pre2 ? thanks

**Comment by samhouts** [comment]
@AuriR Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
