### ISSUE TITLE
Android crash on main page change

### ISSUE THREAD

**Issue by kvpt** [xamarin/Xamarin.Forms#4706]
### Description
After migrated to Xamarin.Forms 3.4.0 from Xamarin 2.5.0, I got several exceptions in AppCenter of type **JavaLocationException**/**NotSupportedException**.

![image](https://user-images.githubusercontent.com/1446221/49834644-35da6c80-fd9d-11e8-9875-e80522abe2c3.png)

Before that, my application has no crash reported.

After some tests, impossible for me to reproduce it.

However, the information that can be deduced from the stacktrace is that the crash is during the main page affectation, and that the renderer seem to have been disposed.
So I cloned the repository and go to **SetPageInternal** method, the only incoming call was from the **LoadApplication** method in the activity. In this method was made the dispose of the renderer when the page was replaced. For me this case is possible, if you use a splashscreen (which is my case) or if the method LoadApplication is called a second time, when Android recreate the activity for exemple.

So to confirm that it's the case, I tried to call LoadApplication method twice and indeed the exception occured.

After some debug in the code, I found that the dispose of the renderer was also done later in the Cleanup method called by the method SetPageInternal inside the Platform class.
So I removed the dispose call in the Activity but after that another exception occured : **IllegalArgumentException: No view found for id 0x1 (unknown)**.
This time it was the ClearValue of  the page renderer which caused that, so I moved this code in the platform cleanup code near the dispose.

With those modifications I can now call the LoadApplication method twice without crash and with the application working smoothly.

I think that it will fix the crash encountered by the customers which use splashscreen in their apps or the case when application are restored from background.

I will made a PullRequest that fix the issue.

### Steps to Reproduce

1.  Create a new project from the Template
2.  Call LoadApplication twice in the MainActivity (this code is obviously wrong but must not crash the application)

### Expected Behavior
No crash

### Actual Behavior
Crash

### Basic Information

- Version with issue: All after 2.5.0
- Last known good version: 2.5.0
- IDE: Visual Studio 2017 15.9.3
- Platform Target Frameworks:
  - Android

**Comment by keannan5390** [comment]
I wanted to provide an additional sample project that can reproduce this issue, I know @kvpt also provided one in the PR that is attached to this issue as well.

[https://github.com/keannan5390/xamarin.forms_issue_4706](xamarin.forms_issue_4706)

The reproduction steps of the issue that I'm experiencing are a little bit more random. We have a recurring issue with this crash on the Samsung Galaxy Tab E running android 6 or android 7. If we run the app with the visual studio mac debugger on this tablet, after about 3 minutes (on average, sometimes longer, sometimes shorter) the MainActivity will get recreated. The OnPause, OnStop, and OnDestroy methods are invoked by the operating system, and then the activity is re-created via OnCreate().

When this happens, if the FormsApplication is registered as a singleton, the crash described in the occurs.

I don't have much for reproduction steps beyond this, as it isn't reproducible on all devices. But this particular device, it is reliably occurring given the steps described above. We have seen it happen on other devices as well, it seems to be devices that are older, and therefore have less memory available on the device. But, we haven't been able to reproduce the issue reliably on any device other than the Tab E.

Device Info:
![device info](https://raw.githubusercontent.com/keannan5390/xamarin.forms_issue_4706/master/device_info_1.png "Device Info 1")
![device info](https://raw.githubusercontent.com/keannan5390/xamarin.forms_issue_4706/master/device_info_2.png "Device Info 2")
