### ISSUE TITLE
Views loaded inside the DataTemplate is not clipped when fast scrolling happens only on 3.3.0 version

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#4712]
### Description

We would like to bring to your notice a bug that we encountered recently, **Views loaded inside the DataTemplate is not clipped when fast scrolling happens, Issue came only on 3.3.0 version**, We have SfDataGrid Custom Control which is derived from Grid, And we have DataTemplate to load the customViews, Load the label inside the DataTemplate, In this case scroll the SfDataGrid fastly, Inside of the DataTemplate loaded CustomViews are not clipped outside of the Grid, Issue was Xamarin forms Android.
**In Xamarin forms version 3.2.0.871581, this case was working fine views are clipped perfectly while scrolling, But after updating the Xamarin forms version to 3.3.0.967583 Views are not clipped properly which is loaded inside the DataTemplate.**

We have attached the video for issue replicated xamarin forms version, and working xamarin forms version.

We are pretty sure this issue was only on xamarin froms version 3.3.0.967583, So Provide the solution from your side, Also let us know at which upcoming version can we expect this bug will get fixed ? 

### Steps to Reproduce

1.  Run the attached sample (Clean the sample and deploy It, If Syncfusion.Xamarin.SfDataGrid packages are not restored, you can download the package from nuget.org)
2.  Scroll the Grid 
3.  You can able to see Inbetween Button and SfDataGrid space, There was a blue color view(Label View which is loaded inside the DataTemplate) comes and hides continuously while scrolling(blinking occurs)

### Expected Behavior
Views loaded inside the DataTemplate should clipped perfectly out of the Grid, when scrolling happens like previous xamarin forms versions 3.2.0.871581. 

### Actual Behavior
Views loaded inside the  DateTemplate is not clipped outside properly while scrolling in xamarin forms version  3.3.0.967583  

### Basic Information

- Version with issue:  3.3.0.967583
- Last known good version: 3.2.0.871581
- IDE:
- Platform Target Frameworks: 
  - Android: All version of Android version
- Nuget Packages: 3.3.0.967583
- Affected Devices: All Android devices 

### VideoLink
Issue Video link:
http://www.syncfusion.com/downloads/support/directtrac/general/ze/Issue-1284649642
Without Issue Video link :
http://www.syncfusion.com/downloads/support/directtrac/general/ze/Withoutissue1203811962

### Reproduction Link
http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGrid3_1-124841335

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi Team,

Could you please look into this or would you require any more details regarding this issue ? Is there anything else we can do from our side ?

**Comment by PureWeen** [comment]
@DeepikaBalaSubramaniyan in case you haven't seen this yet. I tried to test this with our latest 4.0 pre1 release but it seems the syncfusion control isn't compatible because of some additions to our interfaces

```
(11817): no implementation for interface method Xamarin.Forms.IScrollViewController::get_LayoutAreaOverride() in class Syncfusion.SfDataGrid.XForms.ExtScrollViewer
```

Just an FYI

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @PureWeen 

We will check our control on Xamarin forms version 4.0 and let you know the further details.

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @PureWeen 

4.0 pre 1 version is not stable version,  we will update our controls after Xamarin forms stable version releases, So we have checked reported issue in last stable version **3.4.0.100999**, While up scrolling the grid clipping issue is replicated in last stable version of xamarin forms, So we request you to fix this issue on your last stable version.

For your version sample is attached with last Stable version of Xamarin forms **3.4.0.100999**, Link:
[4:20 PM] Pradeep Kumar Balakrishnan
http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGrid30905267

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi All,

After fixing this issue "
 no implementation for interface method Xamarin.Forms.IScrollViewController::get_LayoutAreaOverride() in class Syncfusion.SfDataGrid.XForms.ExtScrollViewer" in our SfDataGrid control, I have checked with Xamarin forms latest pre release version 4.0.0.169046-pre5, Issue remains the same, For your reference have provided the sample with  Xamarin forms latest pre release version 4.0.0.169046-pre5, Check and fix this issue on upcoming forms versions.

Sample link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/DataGrid1769032387

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi All,

Any update on this issue ?

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @samhouts 

We are waiting for this fix for a long time. Can you please let us know when this issue will get fixed ?

**Comment by Sivaraman761** [comment]
Hi @samhouts 

we have found that, above mentioned issue occurred because of this #3559 changes. And we have found workaround for the same, workaround is set “IsClippedToBounds” as true for android scrollview. So can you please let us know whether it is conventional to set IsClippedToBounds property  as true ?

**Comment by Sivaraman761** [comment]
Hi @samhouts 

Any update on this issue?

**Comment by SubburajPandianV** [comment]
+1

**Comment by syncsiva** [comment]
+1

**Comment by Sivaraman761** [comment]
Hi Team,

Any update on this issue?

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @samhouts 

Can you please let us know when this issue will get fixed ?

**Comment by samhouts** [comment]
> we have found that, above mentioned issue occurred because of this #3559 changes. And we have found workaround for the same, workaround is set “IsClippedToBounds” as true for android scrollview. So can you please let us know whether it is conventional to set IsClippedToBounds property as true ?

@DeepikaBalaSubramaniyan Hi! In reviewing this issue, I see that the above description is actually the desired behavior. Please set `IsClippedToBounds` to `true` on your `ScrollView`. Thanks!
