### ISSUE TITLE
XamarinForms GestureRecognizer issue

### ISSUE THREAD

**Issue by 1saeedsalehi** [xamarin/Xamarin.Forms#4714]
### Description
`TapGestureRecognizer`  will miss some taps when you try to tap frequently.
It seems Android is working fine, but UWP is failing to behave correctly.

### Steps to Reproduce

1.  Add a `TapGestureRecognizer`  on a frame to show tapped count on a label
2. Try to tap frequently on frame
3. Count your tap in your mind!
4. Compare your tapped with shown label

### Expected Behavior
count which shown on label should be equal with actual tapped count

### Actual Behavior
it's less than actual amount

### Basic Information

- Version with issue: XamarinFroms 3.4.0.1008
- Last known good version: N/A
- IDE: Visual Studio  version 15.9.2
- Platform Target Frameworks: 

  - Android: 8.1
  - UWP:  Windows 10 version 1809 Build 17763

### Reproduction Link

I've made a GitHub repository to show how can it be reproduced, it can be accessed [here](https://github.com/1saeedsalehi/XFGestureRecognizerIssue)

**Comment by Estevete** [comment]
Have you found any workaround while waiting the release? I've tried setting a button behind, and works. But with for example a grid with 42 frames and 42 buttons behind it takes a bit to load it.

**Comment by YZahringer** [comment]
Same issue on UWP, no problem on Android or iOS

**Comment by YZahringer** [comment]
The current behavior is specific to the UWP platform and is documented here: [UIElement.DoubleTapped](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.doubletapped#remarks)

> If a user interaction also fires DoubleTapped, Tapped will fire first to represent the first tap, but the second tap won't fire an additional Tapped. 

Replacing `NumberOfTapsRequired == 2` by `NumberOfTapsRequired == 1 || NumberOfTapsRequired == 2` on [OnDoubleTap/children](https://github.com/xamarin/Xamarin.Forms/blob/8e90f8270454acdbed16a5bb88d875edac6ee826/Xamarin.Forms.Platform.UAP/VisualElementTracker.cs#L327)  and [OnDoubleTap/view](https://github.com/xamarin/Xamarin.Forms/blob/8e90f8270454acdbed16a5bb88d875edac6ee826/Xamarin.Forms.Platform.UAP/VisualElementTracker.cs#L336) should solve the issue.

**Comment by samhouts** [comment]
closed by #10078
