### ISSUE TITLE
UWP: Webview: Memory Leak

### ISSUE THREAD

**Issue by csk1nner** [xamarin/Xamarin.Forms#4720]
### Description
Using Xamarin.Forms (3.4.0.1008975), for UWP (windows 10) the webview control will take more and more memory space until it crashes the application
### Steps to Reproduce

1. Create a simple Xamarin.Forms application where page A navigates to page B that encapsulates a webview
2. Run the application and note the memory in Task Manager that the application is consuming
3. Navigate to the page that contains the webview.  Notice that Task Manager is increasing the memory footprint of the application.
4.  Navigate back to the root (page A).  Notice that the memory footprint in task manager is not fully recycled. 
5. Repeat steps 3 & 4 until application crashes

### Expected Behavior
The webview control should closely mimic the resource allocation of Edge browser

### Actual Behavior
After three or four navigation cycles (depends on webpage) the application crashes.

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  17134
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
UWP (Windows 10)

### Screenshots
http://dynamiconnections.com/downloads/screenshot.png

### Reproduction Link

http://dynamiconnections.com/downloads/navigationsample.zip

**Comment by csk1nner** [comment]
Hello there!

Hope you are having a good day.  Any news on this?  I'm curious to know if there is a work around for this.

Cheers,

Caleb

**Comment by cheles** [comment]
hi @samhouts. any updates on this? it looks like this was reported on UWP standalone apps too, not only XF and it looks like webview controller is leaking some memory in Back/Forward stack.

**Comment by CannoliSquid** [comment]
Any updates on this issue?

**Comment by cheles** [comment]
Just an update that might impact XF too.
We released UWP 6.2.9 NuGet update with huge improvements in memory handling and GC calls while targeting >=RS4. The complete release notes are here: [https://github.com/microsoft/dotnet/blob/master/releases/UWP/net-native2.2/README.md](url)
@csk1nner can you try to update everything to latest and see if you still repro memory leak while navigating between pages?

**Comment by csk1nner** [comment]
The memory leak is still in place.  Same issue.  Massive increase in memory on UWP.  Android and IOS work fine.

**Comment by cheles** [comment]
my tests showed super improvements. Are you sure you've targeted >=RS3? or else, can you share a repro?

**Comment by csk1nner** [comment]
Hello there,

Spun up a fresh tabbed xamarin.forms app and experienced the same problem.  Added a webview control to the ItemDetailPage and was able to get the memory leak to occur.  Please see attached code.  Using the latest updates with pre-releases.  Problem is occurring on UWP.  

Please let me know what to change up to get this working.

Cheers,

Caleb

[MemoryTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3838995/MemoryTest.zip)

**Comment by csk1nner** [comment]
One more thing.  I think this issue has something to do with video players.  When I browse to a somple website like: http://www.xamarin.com/ - There are no problems.  Complex (normal news sites) crash this.

Cheers,

Caleb

**Comment by csk1nner** [comment]
Gang!  I've got an app trending in the Microsoft store (Unfiltered.me) that really needs this fix.  Is there anything I can do to move the ball forward?  Do you have some pre-release builds that I can test?  I I code the fix?

**Comment by t-johnson** [comment]
I was curious about this issue and have had experience finding these kind of memory issues in the past.
Looked into the various WebView components for each platform for event handlers that may not have been removed.

I see a difference in the UWP WebViewRenderer (Xamarin.Forms\Xamarin.Forms.Platform.UAP\WebViewRenderer.cs) when compared to the other platforms.  This ones Dispose() does not remove the event handlers that get added to the Element in OnElementChanged, whereas all the other platforms seem to do this.  

Its been my experience that unremoved delegates can cause the GC to hold onto the objects, even when one might expect that they would go away themselves.

I'd be willing to try this out however i've never contributed to XF before so not sure how to go about building and testing a locally build dll.

**Comment by t-johnson** [comment]
So ... not as straight forward as I first thought.  The WebView control seems to be allocating huge amounts of memory when visiting youtube.com, and yet if I force a GC after closing the form with the WebView on it, my process memory goes down.  And that is in the current code - no changes made.  So my preliminary changes might have just got lucky with when GC happened to occur.

Either way, forcing GC after closing any WebView hosting page is probably not going to fly.  This seems to be a memory problem that is unrelated to XF, and more related to the UAP/WebView implementation itself.  Understandably it is quite a complex control.

Another thing I tried was to force the WebView to execute in a separate process [by passing the WebViewExecutionMode to the WebView constructor](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.-ctor?view=winrt-19041#Windows_UI_Xaml_Controls_WebView__ctor_Windows_UI_Xaml_Controls_WebViewExecutionMode_) which does seem to make the whole thing a lot more robust, as the bizarre memory profile is now outside of the current process.

Was wondering if any XF people would weigh in on whether it would be worth Implementing this ?  it have to be 'opt-in' somehow to avoid potential breaking of existing apps, as apparently there can be slight behavior differences with this mode.  

I suppose this would also be possible for people to opt-in by making their own custom renderer if the Xamarin.Forms.Platform.UWP.WebViewRenderer provided a protected member to allow setting the WebViewExecutionMode to be used in the Windows.UI.Xaml.Controls.WebView constructor.  

Thoughts?

**Comment by wtheronjones** [comment]
I think I noticed this on a UWP project, perhaps having something to do w/ how the navigation system caches pages.   (I could see them in "Microsoft Edge DevTools Preview")
I made it a point to navigate the webview to "about:blank" when leaving the screen containing the webview.
