### ISSUE TITLE
Underline missing when changing value to label

### ISSUE THREAD

**Issue by stefano-corricelli** [xamarin/Xamarin.Forms#4734]
### Description
If i change label text with datatrigger the underline textdecoration disappear

### Steps to Reproduce
look at the attached code 

### Expected Behavior
underline don't have to disappear

### Actual Behavior
underline disappear

### Basic Information
- Version with issue: 3.4.0.1008975
- IDE: VS mac 7.7 (build 1868)
- Platform Target Frameworks: 
  - iOS:  12.1

[issue.zip](https://github.com/xamarin/Xamarin.Forms/files/2679271/issue.zip)

**Comment by AndreiMisiukevich** [comment]
@hartez @samhouts 
Works fine on latest master code

![image](https://user-images.githubusercontent.com/10124814/51004192-b3cf9600-154a-11e9-8b87-3ff9bbee497e.png)

**Comment by stefano-corricelli** [comment]
work with  <PackageReference Include="Xamarin.Forms" Version="3.6.0.220655" />

this ticket can be closed
