### ISSUE TITLE
Manipulation Events not working when "ListView" inside in view --UWP

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#4735]
### Description
Hi Team
We at Syncfusion develop data visualization controls for Xamarin and we have more than 90 controls spread across all platforms of Xamarin. Please refer the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/sfdatagrid/overview
FeatureTour: https://www.syncfusion.com/products/xamarin
UserGuide:https://help.syncfusion.com/xamarin/sflistview/getting-started

**Issue**
     We would like to bring to your notice a bug that we encountered recently in Layout. I have written the custom view  as (MyView.cs) which is derived from the Loyout < **View**> and  also written renderer (as MyViewRenderer.cs) in UWP platform,  when i add any other view or layout (Like scrollview, stack-layout) as children to my custom view , touch manipulation events are working fine. But when i add **Listview**  as a child to my view. I doesn't get any notification from the manipulation events.
I have attached a sample & video in this report.

**Note**
Don't use pointer , pointer events are working fine.

### Steps to Reproduce
1. Before start please watch the video i have attached in this 
2. Open the sample i have attached in this report 
3. First go to Mainpage.cs file in PCL and add  **Scrollview**  as a child to my view(MyView) and run the sample, once it get into the view, place a breakpoint inside (MyViewRenderer.cs renderer in UWP )in manipulationDelta, manipulation-completed, manipulation-started event's, Now do the touch interaction in screen , you can see that all manipulation events are triggered and working fine.
4. Now change the child to  **ListView** from MainPage.cs and do the same touch interaction . you would see that manipulation events aren't triggered while touch interaction.

### Expected Behavior
 1. Manipulation Events should  fires when touch interaction happen

### Actual Behavior
 1. Manipulation Events aren't fires when touch interaction happen

### Basic Information
- Version with issue: I have checked from 2. 5 to 3.2 issue has reproduced 
- Last known good version:NA
- IDE: VisualStudio
- Platform Target Frameworks: UWP 
  - UWP: Windows 10 (Build 16299)a
- Nuget Packages:
   Version: 3.2.0.871581
- Affected Devices: Windows

### Reproduction Link
Sample : [PullToRefresh.Simple.Sample.zip]
Video  : [Manipultion.zip]
(https://github.com/xamarin/Xamarin.Forms/files/2679448/Manipultion.zip)
(https://github.com/xamarin/Xamarin.Forms/files/2679449/PullToRefresh.Simple.Sample.zip)

**Comment by charlesroddie** [comment]
The Xamarin.Forms team consideres ListView buggy and badly designed and is replacing it with CollectionView ( https://github.com/xamarin/Xamarin.Forms/issues/3172, https://blog.xamarin.com/xamarin-forms-4-0-preview/ ) . It may be worth trying CollectionView in the preview and seeing if you get the same bug.

**Comment by BalasubramaniSundaram** [comment]
Hi @charlesroddie ,
         Sorry, we already have a control which derived from listview and delivered to end-users, it's not possible to change to CollectionView, so please provide a proper solution to overcome this use-case.

Regards,
Balasubramani Sundaram.

**Comment by BalasubramaniSundaram** [comment]
Hi Team, 
  Any update 

regards,
Balasubramani Sundaram

**Comment by BalasubramaniSundaram** [comment]
Hi @pauldipietro  & @kingces95 , 
     Any Update on this ..

Regards,
Balasubramani Sundaram.

**Comment by PureWeen** [comment]
@BalasubramaniSundaram  so I think this is generally a limitation of UWP specifically and not Forms getting in the way. If I create a native UWP project with just a listview

```xaml
<Page>
 <Grid x:Name="gridContorl" Background="Pink">
		<ListView x:Name="listView" Background="Blue"></ListView>
    </Grid>
</Page>
```

if you attach manipulation events to listView they don't fire. So this isn't really XF getting in your way and I'm guessing CollectionView would have the same problem. 

Have you tried to use https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.gesturerecognizer by chance? From my tests PointerPressed and those all still fire so I think you can propagate those to a GestureRecognizer and do what you need to do that way

**Comment by Muthukumaran-G** [comment]
Hi @PureWeen ,

Tried using GestureRecognizer also. But still couldn't find any suitable workaround to recognize the gesture events.

**Comment by BalasubramaniSundaram** [comment]
Hi @PureWeen , 
   In Xamarin.Forms 4.2 the pointer event also didn't get fired. Please provide the valid solution to overcome from this.

**Comment by BalasubramaniSundaram** [comment]
Hi @samhouts, 
 Please re-open this incident.

**Comment by KarthikRaja26** [comment]
Hi @samhouts ,

Any update on this ?

**Comment by SergTomcat** [comment]
Any news?
