### ISSUE TITLE
[Visual][Android] Entry requires 2 taps to launch keyboard

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4739]
### Description

On first tap the placeholder moves, and on second tap the keyboard appears.

https://www.screencast.com/t/aEGPnAwYAWy

The keyboard immediately appears when the Entry already has a value and is in that UI state.

iOS does not have this problem.

### Basic Information

- Version with issue: 4.0.1.33101

### Reproduction Link

https://github.com/PureWeen/VisualTesting

**Comment by PureWeen** [comment]
This will be fixed with next update of visual packages

The padding hack to fix Android's lack of Placeholder centering was causing the keyboard not to show on  first tap
