### ISSUE TITLE
Editor control with TranslateTo method applied result in exception & crash

### ISSUE THREAD

**Issue by ppetrov** [xamarin/Xamarin.Forms#4740]
### Description
Dynamically create Editor control when a button is tapped, then it's added to the grid layout and an animation is applied to it. It result in a exception and if performed multiple times in a crash. I've checked with other controls(Button, Label, DatePicker, Image, ImageButton, StackLayout, Grid, ListView, Slider, SearchBar, Stepper, TableView, WebView) and it works OK - no exception or crash

### Steps to Reproduce

1.  Create a page XAML
```
<Grid x:Name="MainGrid">
      <Button Text="Animate Editor" Command="{Binding AnimateEditorCommand}"
              HorizontalOptions="Center" VerticalOptions="Center" WidthRequest="120">
      </Button>
    </Grid>
```

2. Code-behind for AnimateEditorCommand

```
		private async void AnimateEditorCommand()
		{
			var grid = new Grid { BackgroundColor = Color.Gray };

			grid.GestureRecognizers.Add(new TapGestureRecognizer { Command = this.HideCommand });

			var view = new Editor
			{
				HorizontalOptions = LayoutOptions.Center,
				VerticalOptions = LayoutOptions.Start,
				BackgroundColor = Color.OrangeRed,
				Margin = new Thickness(100),
				WidthRequest = 200,
				HeightRequest = 40,
			};

			grid.Children.Add(view);

			this.MainGrid.Children.Add(grid);

			view.TranslationX += Application.Current.MainPage.Width;
			await view.TranslateTo(0, 0);
		}
```

### Expected Behavior

No exception or crash.

### Actual Behavior

Exception
Thread started:  #3
2018-12-14 19:28:45.462 AtosClient.iOS[6638:3284952] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   Foundation                          0x0000000232e01fc0 <redacted> + 96
	1   Foundation                          0x0000000232bfdfd0 <redacted> + 76
	2   Foundation                          0x0000000232bfdee4 <redacted> + 120
	3   Foundation                          0x0000000232bfdc90 <redacted> + 112
	4   UIKitCore                           0x000000025ead6260 <redacted> + 284
	5   AtosClient.iOS                      0x0000000100b95168 AtosClient.iOS + 4198760
	6   AtosClient.iOS                      0x0000000100b4bb04 AtosClient.iOS + 3898116
	7   AtosClient.iOS                      0x00000001011164fc AtosClient.iOS + 9970940
	8   AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	9   AtosClient.iOS                      0x0000000101b19
7e0 mono_pmip + 24712
	10  AtosClient.iOS                      0x0000000101b865b0 mono_pmip + 470616
	11  AtosClient.iOS                      0x0000000101b89bd4 mono_pmip + 484476
	12  AtosClient.iOS                      0x00000001007ab078 AtosClient.iOS + 94328
	13  AtosClient.iOS                      0x00000001007aaf80 AtosClient.iOS + 94080
	14  UIKitCore                           0x000000025eae9998 <redacted> + 1380
	15  QuartzCore                          0x0000000236838a34 <redacted> + 184
	16  QuartzCore                          0x000000023683d9c4 <redacted> + 324
	17  QuartzCore                          0x000000023679c9d4 <redacted> + 340
	18  QuartzCore                          0x00000002367cb2f4 <redacted> + 608
	19  AtosClient.iOS                      0x0000000100b950a8 AtosClient.iOS + 4198568
	20  AtosClient.iOS                      0x0000000100b30e28 AtosClient.iOS + 3788328
	21  AtosClient.iOS                      0x0000000101199620 AtosClient.iOS + 10507808
	22  AtosClient.iOS                 
     0x00000001008e678c AtosClient.iOS + 1386380
	23  AtosClient.iOS                      0x00000001008e42d8 AtosClient.iOS + 1376984
	24  AtosClient.iOS                      0x00000001008e412c AtosClient.iOS + 1376556
	25  AtosClient.iOS                      0x00000001008e40b0 AtosClient.iOS + 1376432
	26  AtosClient.iOS                      0x00000001008e68f4 AtosClient.iOS + 1386740
	27  AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	28  AtosClient.iOS                      0x0000000101b197e0 mono_pmip + 24712
	29  AtosClient.iOS                      0x0000000101b865b0 mono_pmip + 470616
	30  AtosClient.iOS                      0x0000000101bb35bc mono_pmip + 654948
	31  AtosClient.iOS                      0x0000000101bb3380 mono_pmip + 654376
	32  libsystem_pthread.dylib             0x0000000231e702fc <redacted> + 128
	33  libsystem_pthread.dylib             0x0000000231e7025c _pthread_start + 48
	34  libsystem_pthread.dylib             0x0000000231e73d08 thread_start + 4
)
2018-12-14 19:28:45.466 AtosClient.iOS[6638:3284952] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   Foundation                          0x0000000232e01fc0 <redacted> + 96
	1   Foundation                          0x0000000232bf44d4 <redacted> + 36
	2   UIKitCore                           0x000000025e3267a8 <redacted> + 92
	3   UIKitCore                           0x000000025e32513c <redacted> + 116
	4   UIKitCore                           0x000000025e3263c8 <redacted> + 168
	5   UIKitCore                           0x000000025e3273e8 <redacted> + 420
	6   UIKitCore                           0x000000025ead58e4 <redacted> + 328
	7   AtosClient.iOS                      0x0000000100b95168 AtosClient.iOS + 4198760
	8   AtosClient.iOS                      0x0000000100b4bb04 AtosClient.iOS + 3898116
	9   AtosClient.iOS                      0x00000001011164fc AtosClient.iO
S + 9970940
	10  AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	11  AtosClient.iOS                      0x0000000101b197e0 mono_pmip + 24712
	12  AtosClient.iOS                      0x0000000101b865b0 mono_pmip + 470616
	13  AtosClient.iOS                      0x0000000101b89bd4 mono_pmip + 484476
	14  AtosClient.iOS                      0x00000001007ab078 AtosClient.iOS + 94328
	15  AtosClient.iOS                      0x00000001007aaf80 AtosClient.iOS + 94080
	16  UIKitCore                           0x000000025eae9998 <redacted> + 1380
	17  QuartzCore                          0x0000000236838a34 <redacted> + 184
	18  QuartzCore                          0x000000023683d9c4 <redacted> + 324
	19  QuartzCore                          0x000000023679c9d4 <redacted> + 340
	20  QuartzCore                          0x00000002367cb2f4 <redacted> + 608
	21  AtosClient.iOS                      0x0000000100b950a8 AtosClient.iOS + 4198568
	22  AtosClient.iOS                      0x0000000100b
30e28 AtosClient.iOS + 3788328
	23  AtosClient.iOS                      0x0000000101199620 AtosClient.iOS + 10507808
	24  AtosClient.iOS                      0x00000001008e678c AtosClient.iOS + 1386380
	25  AtosClient.iOS                      0x00000001008e42d8 AtosClient.iOS + 1376984
	26  AtosClient.iOS                      0x00000001008e412c AtosClient.iOS + 1376556
	27  AtosClient.iOS                      0x00000001008e40b0 AtosClient.iOS + 1376432
	28  AtosClient.iOS                      0x00000001008e68f4 AtosClient.iOS + 1386740
	29  AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	30  AtosClient.iOS                      0x0000000101b197e0 mono_pmip + 24712
	31  AtosClient.iOS                      0x0000000101b865b0 mono_pmip + 470616
	32  AtosClient.iOS                      0x0000000101bb35bc mono_pmip + 654948
	33  AtosClient.iOS                      0x0000000101bb3380 mono_pmip + 654376
	34  libsystem_pthread.dylib             0x0000000231e702fc <redacted> + 128
	35  
libsystem_pthread.dylib             0x0000000231e7025c _pthread_start + 48
	36  libsystem_pthread.dylib             0x0000000231e73d08 thread_start + 4
)
2018-12-14 19:28:45.473 AtosClient.iOS[6638:3284952] This application is modifying the autolayout engine from a background thread after the engine was accessed from the main thread. This can lead to engine corruption and weird crashes.
 Stack:(
	0   Foundation                          0x0000000232e01fc0 <redacted> + 96
	1   Foundation                          0x0000000232bf6a78 <redacted> + 32
	2   Foundation                          0x0000000232c39580 <redacted> + 540
	3   Foundation                          0x0000000232c38a50 <redacted> + 396
	4   Foundation                          0x0000000232c3879c <redacted> + 272
	5   Foundation                          0x0000000232c38020 <redacted> + 264
	6   UIKitCore                           0x000000025e3170b4 <redacted> + 488
	7   UIKitCore                           0x000000025e317534 <redacted> + 36
	8   UIKitCore                           0x000000025e317c34 <redacted> + 84
	9   UIKitCore                           0x000000025e31d00c <redacted> + 684
	10  UIKitCor
e                           0x000000025e327014 <redacted> + 112
	11  UIKitCore                           0x000000025e325b54 <redacted> + 176
	12  UIKitCore                           0x000000025e326004 <redacted> + 992
	13  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	14  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	15  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	16  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	17  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	18  Foundation                          0x0000000232bf451c <redacted> + 108
	19  UIKitCore                           0x000000025e3267a8 <redacted> + 92
	20  UIKitCore                           0x000000025e32513c <redacted> + 116
	21  UIKitCore                           0x000000025e3263c8 <redacted> + 168
	22  UIKitCore                           0x000000025e3273e8 <redacted> + 420
	23  UIKitCore                       
    0x000000025ead58e4 <redacted> + 328
	24  AtosClient.iOS                      0x0000000100b95168 AtosClient.iOS + 4198760
	25  AtosClient.iOS                      0x0000000100b4bb04 AtosClient.iOS + 3898116
	26  AtosClient.iOS                      0x00000001011164fc AtosClient.iOS + 9970940
	27  AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	28  AtosClient.iOS                      0x0000000101b197e0 mono_pmip + 24712
	29  AtosClient.iOS                      0x0000000101b865b0 mono_pmip + 470616
	30  AtosClient.iOS                      0x0000000101b89bd4 mono_pmip + 484476
	31  AtosClient.iOS                      0x00000001007ab078 AtosClient.iOS + 94328
	32  AtosClient.iOS                      0x00000001007aaf80 AtosClient.iOS + 94080
	33  UIKitCore                           0x000000025eae9998 <redacted> + 1380
	34  QuartzCore                          0x0000000236838a34 <redacted> + 184
	35  QuartzCore                          0x000000023683d9c4 <redacted> + 324
	36  Quart
zCore                          0x000000023679c9d4 <redacted> + 340
	37  QuartzCore                          0x00000002367cb2f4 <redacted> + 608
	38  AtosClient.iOS                      0x0000000100b950a8 AtosClient.iOS + 4198568
	39  AtosClient.iOS                      0x0000000100b30e28 AtosClient.iOS + 3788328
	40  AtosClient.iOS                      0x0000000101199620 AtosClient.iOS + 10507808
	41  AtosClient.iOS                      0x00000001008e678c AtosClient.iOS + 1386380
	42  AtosClient.iOS                      0x00000001008e42d8 AtosClient.iOS + 1376984
	43  AtosClient.iOS                      0x00000001008e412c AtosClient.iOS + 1376556
	44  AtosClient.iOS                      0x00000001008e40b0 AtosClient.iOS + 1376432
	45  AtosClient.iOS                      0x00000001008e68f4 AtosClient.iOS + 1386740
	46  AtosClient.iOS                      0x0000000100a95b68 AtosClient.iOS + 3152744
	47  AtosClient.iOS                      0x0000000101b197e0 mono_pmip + 24712
	48  AtosClient.iOS                 
     0x0000000101b865b0 mono_pmip + 470616
	49  AtosClient.iOS                      0x0000000101bb35bc mono_pmip + 654948
	50  AtosClient.iOS                      0x0000000101bb3380 mono_pmip + 654376
	51  libsystem_pthread.dylib             0x0000000231e702fc <redacted> + 128
	52  libsystem_pthread.dylib             0x0000000231e7025c _pthread_start + 48
	53  libsystem_pthread.dylib             0x0000000231e73d08 thread_start + 4
)

**Stack trace from the crash (they can be from the previous error)**
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Engine marked as needing optimization even though it's already in progress.
Native stack trace:
	0   CoreFoundation                      0x0000000232256f10 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000231424a40 objc_exception_throw + 56
	2   CoreFoundation                      0x000000023216b06c <redacted> + 0
	3   Foundation                          0x0000000232c573e0 <redacted> + 112
	4   Foundation                          0x0000000232bf6ba8 <redacted> + 336
	5   Foundation                          0x0000000232c39580 <redacted> + 540
	6   Foundation                          0x0000000232c38a50 <redacted> + 396
	7   Foundation                          0x0000000232c3879c <redacted> + 272
	8   Foundation                          0x0000000232c38020 <redacted> + 264
	9   UIKitCore                           0x000000025e3170b4 <redacted> + 488
	10  UIKitCore                           0x000000025e319154 <redacted> + 352
	11  UIKitCore                           0x000000025e319500 <redacted> + 164
	12  UIKitCore                           0x000000025e327014 <redacted> + 112
	13  UIKitCore                           0x000000025e325b54 <redacted> + 176
	14  UIKitCore                           0x000000025e326004 <redacted> + 992
	15  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	16  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	17  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	18  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	19  Foundation                          0x0000000232bf451c <redacted> + 108
	20  UIKitCore                           0x000000025e3267a8 <redacted> + 92
	21  UIKitCore                           0x000000025e32513c <redacted> + 116
	22  UIKitCore                           0x000000025e3263c8 <redacted> + 168
	23  UIKitCore                           0x000000025e3273e8 <redacted> + 420
	24  UIKitCore                           0x000000025ead58e4 <redacted> + 328
	25  UIKitCore                           0x000000025eae9998 <redacted> + 1380
	26  QuartzCore                          0x0000000236838a34 <redacted> + 184
	27  QuartzCore                          0x000000023683d9c4 <redacted> + 324
	28  QuartzCore                          0x000000023679c9d4 <redacted> + 340
	29  QuartzCore                          0x00000002367cb2f4 <redacted> + 608
	30  QuartzCore                          0x00000002367cc15c <redacted> + 92
	31  CoreFoundation                      0x00000002321e4b94 <redacted> + 32
	32  CoreFoundation                      0x00000002321df828 <redacted> + 412
	33  CoreFoundation                      0x00000002321dfdc8 <redacted> + 1264
	34  CoreFoundation                      0x00000002321df5b8 CFRunLoopRunSpecific + 436
	35  GraphicsServices                    0x0000000234453584 GSEventRunModal + 100
	36  UIKitCore                           0x000000025e43b558 UIApplicationMain + 212
	37  TestClient.iOS                      0x0000000101497508 TestClient.iOS + 4240648
	38  TestClient.iOS                      0x000000010142b8fc TestClient.iOS + 3799292
	39  TestClient.iOS                      0x000000010142b8bc TestClient.iOS + 3799228
	40  TestClient.iOS                      0x00000001010b3e80 TestClient.iOS + 163456
	41  TestClient.iOS                      0x000000010138db68 TestClient.iOS + 3152744
	42  TestClient.iOS                      0x00000001024117e0 mono_pmip + 24712
	43  TestClient.iOS                      0x000000010247e5b0 mono_pmip + 470616
	44  TestClient.iOS                      0x000000010248386c mono_pmip + 491796
	45  TestClient.iOS                      0x00000001023f85e8 TestClient.iOS + 20366824
	46  TestClient.iOS                      0x0000000102529ce0 _Z9__isctypeim + 47160
	47  TestClient.iOS                      0x00000001010b3d7c TestClient.iOS + 163196
	48  libdyld.dylib                       0x0000000231c9fb94 <redacted> + 4

Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Variable stored in table doesn't match passed in variable Xamarin_Forms_Platform_iOS_EditorRenderer:0x102771610.<unknown var (bug!):0x2837124c0>{id: 34} != Xamarin_Forms_Platform_iOS_EditorRenderer:0x102771610.Width{id: 36}
Native stack trace:
	0   CoreFoundation                      0x0000000232256f10 <redacted> + 252
	1   libobjc.A.dylib                     0x0000000231424a40 objc_exception_throw + 56
	2   CoreFoundation                      0x000000023216b06c <redacted> + 0
	3   Foundation                          0x0000000232ca5c30 <redacted> + 88
	4   Foundation                          0x0000000232dfeb84 <redacted> + 536
	5   Foundation                          0x0000000232dffb74 <redacted> + 180
	6   Foundation                          0x0000000232bf5b04 <redacted> + 76
	7   UIKitCore                           0x000000025e32b81c <redacted> + 3324
	8   UIKitCore                           0x000000025e32ab08 <redacted> + 308
	9   Foundation                          0x0000000232bf49d4 <redacted> + 100
	10  Foundation                          0x0000000232c37fa4 <redacted> + 140
	11  UIKitCore                           0x000000025e3170b4 <redacted> + 488
	12  UIKitCore                           0x000000025e319154 <redacted> + 352
	13  UIKitCore                           0x000000025e319500 <redacted> + 164
	14  UIKitCore                           0x000000025e327014 <redacted> + 112
	15  UIKitCore                           0x000000025e325b54 <redacted> + 176
	16  UIKitCore                           0x000000025e326004 <redacted> + 992
	17  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	18  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	19  UIKitCore                           0x000000025e325ed8 <redacted> + 692
	20  Foundation                          0x0000000232bf451c <redacted> + 108
	21  UIKitCore                           0x000000025e3267a8 <redacted> + 92
	22  UIKitCore                           0x000000025e32513c <redacted> + 116
	23  UIKitCore                           0x000000025e3263c8 <redacted> + 168
	24  UIKitCore                           0x000000025e3273e8 <redacted> + 420
	25  UIKitCore                           0x000000025ead58e4 <redacted> + 328
	26  UIKitCore                           0x000000025e810c4c <redacted> + 92
	27  UIKitCore                           0x000000025ea73244 <redacted> + 48
	28  UIKitCore                           0x000000025eae9998 <redacted> + 1380
	29  QuartzCore                          0x0000000236838a34 <redacted> + 184
	30  QuartzCore                          0x000000023683d9c4 <redacted> + 324
	31  QuartzCore                          0x000000023679c9d4 <redacted> + 340
	32  QuartzCore                          0x00000002367cb2f4 <redacted> + 608
	33  UIKitCore                           0x000000025e434d90 <redacted> + 172
	34  UIKitCore                           0x000000025e395654 <redacted> + 5516
	35  UIKitCore                           0x000000025e38dee0 <redacted> + 152
	36  CoreFoundation                      0x00000002321e55b8 <redacted> + 24
	37  CoreFoundation                      0x00000002321e5538 <redacted> + 88
	38  CoreFoundation                      0x00000002321e4e1c <redacted> + 176
	39  CoreFoundation                      0x00000002321dfce8 <redacted> + 1040
	40  CoreFoundation                      0x00000002321df5b8 CFRunLoopRunSpecific + 436
	41  GraphicsServices                    0x0000000234453584 GSEventRunModal + 100
	42  UIKitCore                           0x000000025e43b558 UIApplicationMain + 212
	43  TestClient.iOS                      0x0000000101253508 TestClient.iOS + 4240648
	44  TestClient.iOS                      0x00000001011e78fc TestClient.iOS + 3799292
	45  TestClient.iOS                      0x00000001011e78bc TestClient.iOS + 3799228
	46  TestClient.iOS                      0x0000000100e6fe80 TestClient.iOS + 163456
	47  TestClient.iOS                      0x0000000101149b68 TestClient.iOS + 3152744
	48  TestClient.iOS                      0x00000001021cd380 mono_pmip + 24712
	49  TestClient.iOS                      0x000000010223a150 mono_pmip + 470616
	50  TestClient.iOS                      0x000000010223f40c mono_pmip + 491796
	51  TestClient.iOS                      0x00000001021b4188 TestClient.iOS + 20365704
	52  TestClient.iOS                      0x00000001022e5880 _Z9__isctypeim + 47160
	53  TestClient.iOS                      0x0000000100e6fd7c TestClient.iOS + 163196
	54  libdyld.dylib                       0x0000000231c9fb94 <redacted> + 4

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: VS 2017 version 15.9.4
- Platform Target Frameworks: 
  - iOS:  12.0 (16A366)
  - Android: Haven't tested it
  - UWP:  Works fine

**Comment by hartez** [comment]
Repro project:
[_4740 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2681543/_4740.Repro.zip)

The auto-layout errors definitely show up in the output, though I haven't seen it actually crash the application yet. 

Like @ppetrov says, this only seems to happen for Editor; other controls I've tried don't have this issue. Forcing the Translations onto the UI thread doesn't seem to help. My first instinct is that the constraints 
 set up in CreatePlaceholderLabel() are the issue.

**Comment by AndreiMisiukevich** [comment]
@hartez i don't see any error messages in output with latest code on **master**
(tested with simulator)

**Comment by ppetrov** [comment]
Today I've update my Xamarin Forms to version 3.5.0.129452 and everything works fine

**Comment by AndreiMisiukevich** [comment]
@ppetrov think, you can close this issue :)
