### ISSUE TITLE
forms in UWP show empty button for DisplayActionSheet

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [xamarin/Xamarin.Forms#4744]
DisplayActionSheet is showing empty button in UWP when value is "" (empty string) but hide in android, when value is null instade of "" (empty) that will hide in both (android and uwp).

**Comment by hartez** [comment]
@Ali-YousefiTelori I made a repro project to reproduce the error you are reporting. Let me know if this project accurately displays the error.

[_4744 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2693578/_4744.Repro.zip)

It seems that passing in any `null` value in the `string[]` for the `buttons` parameter causes a crash on Android; on UWP, it becomes a blank button; on iOS, it is ignored.

On all three platforms, and empty string (`""`) becomes a blank button.

So at the very least, we need to make all three platforms behave the same way for `null` - I suggest we follow iOS and ignore `null`.

**Comment by Ali-YousefiTelori** [comment]
thank you for your review @hartez  I forgot to tell you what button was my meat, I mean "Destruction" button in youe example. check this out in your mainpage.cs:

```csharp
        private void Button_Clicked(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", "", "button", string.Empty);
        }

        private void Button_Clicked_1(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", null, "button", "");
        }

        private void Button_Clicked_2(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", "Destruction", "button", "Hello");
        }
```

however if you did this you will see exception in android:

```csharp
        private void Button_Clicked(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", "", "button", string.Empty);
        }

        private void Button_Clicked_1(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", null, "button", null);
        }

        private void Button_Clicked_2(object sender, EventArgs e)
        {
            DisplayActionSheet("Title", "Cancel", "Destruction", "button", "Hello");
        }
```
