### ISSUE TITLE
Unhandled Exception:  System.InvalidOperationException

### ISSUE THREAD

**Issue by gabry90** [xamarin/Xamarin.Forms#4749]
### Description

During some animation; suchase fadeto, translateto etc my app crashed with this follow exception:

Unhandled Exception:

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

12-15 15:56:47.113 I/MonoDroid(13943): UNHANDLED EXCEPTION:
12-15 15:56:47.122 I/MonoDroid(13943): System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
12-15 15:56:47.122 I/MonoDroid(13943):   at (wrapper dynamic-method) System.Object.45(intptr,intptr,bool,int,int,int,int)
12-15 15:56:47.122 I/MonoDroid(13943):   at (wrapper native-to-managed) System.Object.45(intptr,intptr,int,int,int,int,int)
12-15 15:56:47.122 I/MonoDroid(13943):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
12-15 15:56:47.122 I/MonoDroid(13943):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <42dc777b518744fdae9988e94489a4a0>:0 
12-15 15:56:47.122 I/MonoDroid(13943):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <42dc777b518744fdae9988e94489a4a0>:0 
12-15 15:56:47.122 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout (System.Int32 p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4, System.Int32 p5) [0x00086] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:181 
12-15 15:56:47.122 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x00149] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:102 
12-15 15:56:47.122 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateLayout () [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:133 
12-15 15:56:47.123 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].UpdateLayout (System.Collections.Generic.IEnumerable`1[T] children) [0x00034] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:350 
12-15 15:56:47.123 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0000e] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:336 
12-15 15:56:47.123 I/MonoDroid(13943):   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198 
12-15 15:56:47.123 I/MonoDroid(13943):   at (wrapper dynamic-method) System.Object.45(intptr,intptr,bool,int,int,int,int)
12-15 15:56:47.287 W/google-breakpad(13943): ### ### ### ### ### ### ### ### ### ### ### ### ###
12-15 15:56:47.287 W/google-breakpad(13943): Chrome build fingerprint:
12-15 15:56:47.287 W/google-breakpad(13943): 71.0.3578.98
12-15 15:56:47.287 W/google-breakpad(13943): 357809852
12-15 15:56:47.287 W/google-breakpad(13943): ### ### ### ### ### ### ### ### ### ### ### ### ###
12-15 15:56:47.287 E/mono-rt (13943): Stacktrace:
12-15 15:56:47.287 E/mono-rt (13943): 
12-15 15:56:47.288 E/mono-rt (13943):   at <unknown> <0xffffffff>
12-15 15:56:47.288 E/mono-rt (13943):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_new_string (intptr,intptr&,char*,int) <0x00007>
12-15 15:56:47.288 E/mono-rt (13943):   at Java.Interop.JniEnvironment/Strings.NewString (char*,int) [0x00009] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Java.Interop.JniEnvironment/Strings.NewString (string) [0x00024] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Android.Runtime.JNIEnv.NewString (string) [0x0000a] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Java.Lang.Error..ctor (string) [0x00020] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Android.Runtime.JavaProxyThrowable..ctor (System.Exception) [0x00007] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Java.Lang.Throwable.FromException (System.Exception) [0x0001e] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.288 E/mono-rt (13943):   at Android.Runtime.AndroidEnvironment.UnhandledException (System.Exception) [0x0006a] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.288 E/mono-rt (13943):   at (wrapper dynamic-method) object.45 (intptr,intptr,bool,int,int,int,int) [0x00047] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
12-15 15:56:47.288 E/mono-rt (13943):   at (wrapper native-to-managed) object.45 (intptr,intptr,int,int,int,int,int) [0x00033] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
12-15 15:56:47.289 E/mono-rt (13943):   at <unknown> <0xffffffff>
12-15 15:56:47.289 E/mono-rt (13943):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00007>
12-15 15:56:47.289 E/mono-rt (13943):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00074] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.289 E/mono-rt (13943):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout (int,int,int,int,int,int) [0x00086] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:181
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x00149] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:102
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1<TElement_REF>.UpdateLayout () [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:133
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1<TElement_REF>.UpdateLayout (System.Collections.Generic.IEnumerable`1<Xamarin.Forms.Element>) [0x00034] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:350
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1<TElement_REF>.OnLayout (bool,int,int,int,int) [0x0000e] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:336
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnLayout (bool,int,int,int,int) [0x0000d] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:365
12-15 15:56:47.289 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (intptr,intptr,bool,int,int,int,int) [0x00008] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:198
12-15 15:56:47.289 E/mono-rt (13943):   at (wrapper dynamic-method) object.45 (intptr,intptr,bool,int,int,int,int) [0x0002f] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
12-15 15:56:47.289 E/mono-rt (13943):   at (wrapper native-to-managed) object.45 (intptr,intptr,int,int,int,int,int) [0x00033] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
12-15 15:56:47.289 E/mono-rt (13943):   at <unknown> <0xffffffff>
12-15 15:56:47.290 E/mono-rt (13943):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a (intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*) <0x00007>
12-15 15:56:47.290 E/mono-rt (13943):   at Java.Interop.JniEnvironment/InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference,Java.Interop.JniObjectReference,Java.Interop.JniMethodInfo,Java.Interop.JniArgumentValue*) [0x00074] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.290 E/mono-rt (13943):   at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <42dc777b518744fdae9988e94489a4a0>:0
12-15 15:56:47.290 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.FormsViewGroup.MeasureAndLayout (int,int,int,int,int,int) [0x00086] in D:\a\1\s\Xamarin.Forms.Platform.Android.FormsViewGroup\obj\Release\generated\src\Xamarin.Forms.Platform.Android.FormsViewGroup.cs:181
12-15 15:56:47.290 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateLayout () [0x00149] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:102
12-15 15:56:47.290 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.VisualElementRenderer`1<TElement_REF>.UpdateLayout () [0x00012] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:133
12-15 15:56:47.290 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.AppCompat.Platform.Xamarin.Forms.Platform.Android.IPlatformLayout.OnLayout (bool,int,int,int,int) [0x00020] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:218
12-15 15:56:47.290 E/mono-rt (13943):   at Xamarin.Forms.Platform.Android.PlatformRenderer.OnLayout (bool,int,int,int,int) [0x0000e] in D:\a\1\s\Xamarin.Forms.Platform.Android\PlatformRenderer.cs:73
12-15 15:56:47.290 E/mono-rt (13943):   at Android.Views.ViewGroup.n_OnLayout_ZIIII (intptr,intptr,bool,int,int,int,int) [0x00012] in <1219ce5aae934ab095dc0e05b2110050>:0
12-15 15:56:47.290 E/mono-rt (13943):   at (wrapper dynamic-method) object.40 (intptr,intptr,bool,int,int,int,int) [0x0002f] in <d4a23bbd2f544c30a48c44dd622ce09f>:0
12-15 15:56:47.290 E/mono-rt (13943):   at (wrapper native-to-managed) object.40 (intptr,intptr,int,int,int,int,int) [0x00033] in <d4a23bbd2f544c30a48c44dd622ce09f>:0

### Steps to Reproduce

Can't reproduce case

### Basic Information

- Version with issue: latest Xamarin.Forms stable version
- Last known good version:
- IDE: Visa Studio 2017 15.9.4
- Platform Target Frameworks:
  - Android: Android SDK version 8.0
- Android Support Library Version: ?
- Nuget Packages:
- Affected Devices: Xiaiomi Mi6

### Screenshots

No screenshoots

### Reproduction Link

No link

**Comment by PureWeen** [comment]
@gabry90  can you at least post the way you are doing animations? Or possibly you can send me a project privately? shneuvil at microsoft.com ?

There's not too much to go on with your stack trace

**Comment by samhouts** [comment]
@gabry90  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
