### ISSUE TITLE
Make `Xamarin.Forms.WeakEventManager` Public

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#4750]
## Summary
`Xamarin.Forms.WeakEventManager` is an excellent example of how to leverage the Weak Event pattern to avoid memory leaks.

I'd love to leverage it in my Xamarin.Forms apps, but the class is currently `internal`.

### Current API

```csharp
namespace Xamarin.Forms
{
    internal class WeakEventManager`
```

### Requested API

```csharp
namespace Xamarin.Forms
{
    public class WeakEventManager
```

## Intended Use Case
This will allow Xamarin.Forms devs to to implement the Weak Event pattern without needing to [implement a custom version](http://paulstovell.com/blog/weakevents) or rely on [3rd party dependancy](https://www.nuget.org/packages/WeakEvent/).

**Comment by brminnick** [comment]
I also recommend tweaking the API for `AddEventHandler` and `RemoveEventHandler` to use `[CallerMemberName]`

### Current API
```csharp
public void AddEventHandler(string eventName, EventHandler handler)
public void AddEventHandler<TEventArgs>(string eventName , EventHandler<TEventArgs> handler)
public void RemoveEventHandler(string eventName, EventHandler handler)
public void RemoveEventHandler<TEventArgs>(string eventName, EventHandler<TEventArgs> handler)
```

### Current Usage
```csharp
public event EventHandler CanExecuteChanged
{
    add => _weakEventManager.AddEventHandler(nameof(CanExecuteChanged), value);
    remove => _weakEventManager.RemoveEventHandler(nameof(CanExecuteChanged), value);
}
```

### Recommended API
```csharp
public void AddEventHandler(EventHandler handler, [CallerMemberName] string eventName= "")
public void AddEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName= "")
public void RemoveEventHandler(EventHandler handler, [CallerMemberName] string eventName= "")
public void RemoveEventHandler<TEventArgs>(EventHandler<TEventArgs> handler, [CallerMemberName] string eventName= "")
```

### Recommended Usage
```csharp
public event EventHandler CanExecuteChanged
{
    add => _weakEventManager.AddEventHandler(value);
    remove => _weakEventManager.RemoveEventHandler(value);
}
```

**Comment by charlesroddie** [comment]
Strange to have this in the xamarin.forms namespace though isn't it? Looking at the api, it doesn't look good enough to me to add to .net standard, with all the string identifiers. The current situation, where you need to copy and paste it or use a lib, may be best.

**Comment by StephaneDelcroix** [comment]
it's indeed a very useful pattern, but it's not the mission of XF to deliver, and support this.

**Comment by StephaneDelcroix** [comment]
@brminnick thanks for the API change suggestion. good one

**Comment by brminnick** [comment]
@StephaneDelcroix 
No worries - that's understandable

You can also drop the constraint for `AddEvent<TEventArgs>` and `RemoveEvent<TEventArgs>`, because [`System.EventHandler<TEventArgs>` doesn't constrain its `TEventArgs`](https://docs.microsoft.com/en-us/dotnet/api/system.eventhandler?view=netframework-4.7.2).

### Current API

```csharp
public void RemoveEventHandler<TEventArgs>(string eventName, EventHandler<TEventArgs> handler) where TEventArgs : EventArgs;

public void AddEventHandler<TEventArgs>(string eventName, EventHandler<TEventArgs> handler) where TEventArgs : EventArgs;
```

### Recommended API

```csharp
public void RemoveEventHandler<TEventArgs>(string eventName, EventHandler<TEventArgs> handler);

public void AddEventHandler<TEventArgs>(string eventName, EventHandler<TEventArgs> handler);
```

**Comment by StephaneDelcroix** [comment]
@brminnick nah, let's keep the constraint

**Comment by danielmeza** [comment]
@StephaneDelcroix then to who the mission is? in order to open a issue there and track the support of this must have feature?

**Comment by brminnick** [comment]
@danielmeza I took the Xamarin.Forms implementation and added it to my AsyncAwaitBestPractices NuGet Package:
https://github.com/brminnick/AsyncAwaitBestPractices#weakeventmanager

I added type safety, `WeakEventManager<T>`, and added support for more types of events: `event Delegate`, `event EventHandler`, `event EventHander<T>`, `event Action` and `event Action<T>`

**Comment by charlesroddie** [comment]
@danielmeza Your suggestion that this should be in a specific UI library doesn't make sense. Obviously if they implemented it in WPF you would not be able to use it in Xamarin.Forms projects, .Net Standard projects, anything that is not a WPF project. Since the code involved does not have a UI dependency, it is not the responsibility of any UI library, and should be done as a .Net Standard project, as @brminnick has correctly done.

If you want to track official support for weak event handlers in .Net, https://github.com/dotnet/corefx/issues/11898 is a good start.

**Comment by danielmeza** [comment]
@charlesroddie  https://github.com/dotnet/corefx/issues/11898 this is was I talking about, not to include this in any UI library, thanks for the link.

**Comment by jbe2277** [comment]
Xamarin friendly WeakEvent implementation provided by: [System.Waf.Core](https://github.com/jbe2277/waf). 
**Motivation**
- Independent of a specific application model. Must work with: WPF, Xamarin (Forms), MAUI, UWP, WinUI.
- Support AOT compilation (e.g. Xamarin.iOS, UWP .NET Native).
- Usable with existing publishers (sources) without modifying them -> Event handler subscription declares it to be weak.

**Example** for INotifyPropertyChanged.PropertyChanged:
``` C#
public class Publisher : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;
}

public class Subscriber
{
    public void Init(Publisher publisher)
    {
        // Instead of publisher.PropertyChanged += Handler; use the following statement:
        WeakEvent.PropertyChanged.Add(publisher, Handler)        
    }

    public void Handler(object? sender, PropertyChangedEventArgs e) { }
}
```
More details can be found on this Wiki page [Weak Event](https://github.com/jbe2277/waf/wiki/Weak-Event).
