### ISSUE TITLE
XAML Error message too vague:  Error: The given key 'Xamarin.Forms.Xaml.ElementNode' was not present in the dictionary. 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4751]
### Description

I'm getting this error trying to run a new XAML page that ran previously. I made several updates, but this message doesn't tell me which one is a problem.

```
/work/TheLittleThingsPlayground/TheLittleThingsPlayground/Views/ThreeFivePage.xaml: Error: The given key 'Xamarin.Forms.Xaml.ElementNode' was not present in the dictionary. (TheLittleThingsPlayground)
```

### Steps to Reproduce

1. Run the attached project

### Expected Behavior

Display an error that provides direction on where the issue is in the file, or steps to identify where it is.

### Actual Behavior

The above error only tells me the file. I'm left to retrace my changes one by one, building and rebuilding, until I figure it out. 

### Basic Information

- Version with issue: 4.0-pre1

### Screenshots

<img width="2030" alt="screenshot 2018-12-15 12 42 46" src="https://user-images.githubusercontent.com/41873/50046363-c0ee8780-0067-11e9-98e7-0bb088376e62.png">

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2682972/Archive.zip)

**Comment by davidortinau** [comment]
Turns out the actual error was that the `DemoViewModel` took an optional constructor argument.

**Comment by StephaneDelcroix** [comment]
object construction in Xaml expects a default parameterless public constructor. A constructor with an optional parameter is quite different from a parameterless one. But
1/ we should fail with the proper error
2/ we could make sure this is supported
