### ISSUE TITLE
[Shell] Tabs came back

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4758]
### Description

I have hidden tabs all the pages, and when I push a new page the tabs are coming back on Android. On iOS they do not.

For example, page `ThreeThreePage.xaml`  has this to hide the tab bar:

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
             x:Class="TheLittleThingsPlayground.Views.ThreeThreePage"
             Shell.TabBarIsVisible="False"
             Title="3.3.0"
             BackgroundColor="{OnPlatform Android=White}">
```

And it looks like this:

<img width="584" alt="screenshot 2018-12-15 21 32 54" src="https://user-images.githubusercontent.com/41873/50049711-01262800-00b1-11e9-8c24-432531772655.png">

Tapping the upper right toolbar item pushes a new page using the "old" navigation service, and the result is this:

<img width="928" alt="screenshot 2018-12-15 21 29 52" src="https://user-images.githubusercontent.com/41873/50049716-1d29c980-00b1-11e9-8cf3-4b13ac8dc583.png">

### Expected Behavior

Tabs should not be visible when I've hidden it.

### Actual Behavior

Tabs. So many tabs!

### Basic Information

- Version with issue: 4.0-pre1

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2683239/Archive.zip)

Parent: #2415

**Comment by samhouts** [comment]
closed by #5896
