### ISSUE TITLE
Allowing code generation at run time

### ISSUE THREAD

**Issue by sadqiang** [xamarin/Xamarin.Forms#4759]
I need to evaluate mathematics expressions at runtime on Xamarin apps.
My attempt is as follows but it fails.

- `Install-Package Microsoft.CodeAnalysis.CSharp.Scripting`
- add  `using Microsoft.CodeAnalysis.CSharp.Scripting;` in any code behind page
- assign `CSharpScript.EvaluateAsync<int>("1 + 2").Result.ToString()` to any label.

Is it possible to request a feature that allow us to generate code at runtime?

**Comment by sadqiang** [comment]
As a reference, I also discussed it on mono: https://github.com/mono/mono/issues/8852

**Comment by charlesroddie** [comment]
This isn't a Xamarin issue. iOS and UWP restrict codegen. This needs to be solved in mono aot/corert/.net native (perhaps with an interpreter not codegen) and then it will work in Xamarin. I wouldn't expect this any time soon and it would be an extremely heavy solution.

What maths expressions do you need to evaluate? Just algebra?

**Comment by sadqiang** [comment]
@charlesroddie : I want to let users input their own function, for example, f(x,y)=x^2+y*sin(x) and the application can calculate, for example, f(2,0) = 4. I also want to create a fractal generator based on the function input by the users.

**Comment by Happypig375** [comment]
I recommend using [Math.NET Symbolics](https://github.com/mathnet/mathnet-symbolics) to parse the Math equation and calculate it. It is much, much, much faster than using a JavaScript engine from my past experience.

**Comment by StephaneDelcroix** [comment]
not a Xamarin.Forms limitation. closing
