### ISSUE TITLE
Generic base class for XAML markup extensions

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#4760]
### Description
A very, very unhelpful error is encountered in XAML files when having a generic base class for XAML markup extensions.

### Steps to Reproduce

1. Add code
```cs
  public abstract class MarkUpExtensionBase<T>: IMarkupExtension<T> {
    public abstract T ProvideValue();
    public T ProvideValue(IServiceProvider serviceProvider) => ProvideValue();
    object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider) =>
      ProvideValue(serviceProvider);
  }

  public class MultiplyExtension : MarkUpExtensionBase<double> {
    public double Base { get; set; }
    public double By { get; set; }

    public override double ProvideValue() => Base * By;
  }
```
2. Add XAML
```xaml
<?xml version="1.0" encoding="UTF-8"?>
<ContentView xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:i="clr-namespace:LocalNamespace"
             x:Class="LocalNamespace.LocalClass">
    <AbsoluteLayout>
          <Button Text="A" Scale="{i:Multiply Base=2, By=3}"/>
    </AbsoluteLayout>
</ContentView>
```
3. Observe error when compiling
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Object reference not set to an instance of an object.	LocalProject	C:\Users\user\Source\Repos\LocalProject\LocalNamespace\LocalClass.xaml	1	
```

### Expected Behavior
Compiles and works with the same behaviour with a non-generic base class

### Actual Behavior
Above error encountered.

### Basic Information

- Version with issue: At least both 3.1.0 and 3.4.0
- Last known good version: Maybe before 3.1.0
- IDE: Visual Studio 2017 (15.9.4)
- Platform Target Frameworks: 
  - .NET Standard 2.0
- Nuget Packages: Xamarin.Forms, SkiaSharp.Views.Forms
- Affected Devices: All

### Screenshots

![image](https://user-images.githubusercontent.com/19922066/50055312-4f5a2a80-0188-11e9-932d-79eb236616b2.png)

### Reproduction Link

Please comment if this is necessary

**Comment by StephaneDelcroix** [comment]
I fixed this issue, but be aware that abusing of MarkupExtensions might hurt your runtime perfs
