### ISSUE TITLE
[Enhancement] Shell Flyout needs ability to position other content

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4763]
## Summary

I want to position content fixed at the bottom of the Flyout menu, fixed at the left, etc. I would prefer to be able to supply a control template to the flyout and/or  have additional layout targets like the header.

## Examples

![menu](https://user-images.githubusercontent.com/41873/50061846-21192280-0169-11e9-9bb2-9c9c3ed81bbc.png)
![img_1839](https://user-images.githubusercontent.com/41873/50061851-28403080-0169-11e9-864b-79618a4cdef8.PNG)
![img_1838](https://user-images.githubusercontent.com/41873/50061852-28403080-0169-11e9-939c-81762177e218.PNG)
![img_1837](https://user-images.githubusercontent.com/41873/50061853-28403080-0169-11e9-81ab-074245f1868b.PNG)
Parent: #2415

**Comment by rmarinho** [comment]
FooterFlyout ?

**Comment by davidortinau** [comment]
`FlyoutFooterTemplate` has been requested many times during the preview. 

Jason recommended providing a template for the Flyout as a whole, which would also be good, however overkill perhaps for most use cases. Could we do both?

**Comment by anthcool** [comment]
Is this feature being actively worked on or even still considered?  I have come to the point where this would be a nice thing to have but it's not there.  I may at some point need to rip out the Shell functionality altogether since it keeps you from customizing your flyout layout.  Ugh...

**Comment by sumathij** [comment]
Can I expect this feature in next release.? Or it is very helpful for me if anyone provide an alternative solution for this feature.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
