### ISSUE TITLE
[Shell] Cannot prevent flyout menu list from scrolling.

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4765]
### Description

The list of menu items (ShellItems) scroll. I want them to not scroll at all, but the flyout doesn't provide a property for this.  For example, the Uber app flyout doesn't scroll on an iPhone X. Even if there is a check for available height and need for scrolling, I still want control of this.

### Basic Information

- Version with issue: 4.0-pre1

### Screenshots

![img_1838](https://user-images.githubusercontent.com/41873/50061983-f11e4f00-0169-11e9-9b67-325c03bee293.PNG)

Parent: #2415

**Comment by rmarinho** [comment]
imo I don't want scroll if everything fits fine. Today we always have scroll. 

So Auto should be just scroll if needed.
Enable
Disable

**Comment by jamesmontemagno** [comment]
4.94*  nice! <3
