### ISSUE TITLE
[Shell] Unable to set status bar color / preference

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4768]
### Description

I should be able to easily set the color (android) or preference (iOS) of the status bar in Xamarin.Forms styles. Presently this requires platform code and/or info.plist like configuration.

### API

Maybe something like: 

```
<Shell
  android:StatusBarColor="Blue" 
  ios:StatusBarStyle="Light|Dark|"
...>
```

If there's a way to do this without platform specific, that would be preferred. It's not very discoverable and intellisense tends to not show them.
Parent: #2415

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
