### ISSUE TITLE
[Shell] URI based navigation missing methods

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4769]
### Description

I should be able to do everything with `Shell` navigation that I can  do with the existing navigation service, and not have to switch between APIs/services. `Shell` is missing:

- Pop / Back
- Pop to root
- Modal

### Basic Information

- Version with issue: 4.0-pre1
Parent: #2415

**Comment by PureWeen** [comment]
@davidortinau so this all "works" now with pre9 

I tested doing this via Shell.Current.Navigation and I also tested it by just using the Navigation property on the page itself. Both of them worked the same

The only thing that's a little bit weird and takes you out of the `Shell Standard` experience is that once you push something modally then that modal page operates under the rules of a non shell type experience. It has to be in a navigation page etc...

So a more Shell like Modal experience will need to be developed for 4.1 or 4.2

**Comment by anthcool** [comment]
I would really like these things as well for Shell.

Desired scenario:

Using Shell URI navigation, I can specify whether a target page resets the stack or not (whether or not that target page is defined within the Shell visual structure).
