### ISSUE TITLE
[Shell] Specify transitions

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4770]
### Description

As part of the Shell spec I should be able to specify the transition animation to be used when executing a route/navigation. The API is missing.

iOS modal segues provide (for example):
- Default
- Cover vertical
- Flip horizontal
- Cross dissolve
- Partial curl

and the ability to opt-out of animation.

iOS also provides the ability to "peek and pop" which previews the segue before committing.

### Basic Information

- Version with issue: 4.0-pre1
Parent: #2415

**Comment by samhouts** [comment]
Duplicate of #6033
