### ISSUE TITLE
HorizontalTextAlignment property doesn't work as expected in Android

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#4771]
### Description

HorizontalTextAlignment property doesn't work when it is set to Center.

### Steps to Reproduce

1. Add label with text alignment as center in StackLayout and define CachingStrategy as RecycleElement to listview.
<StackLayout>
<Label Text="{Binding ContactName}" 
            HorizontalTextAlignment="Center"/>
</StackLayout>
2. Run the sample .
3. Initially loads properly with center alignment but on scrolling text alignment changes.

### Expected Behavior

Text should align in center initially and also on scrolling.

### Actual Behavior

while scrolling text aligns to left.

### Basic Information

- Version with issue: 3.4.0.100897, 3.2.0.871581, even in 2.4.0.280
- Last known good version:
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: Min version 4.4 TargetVersion 8.1
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Tested in  Lenovo 7.0, Mi 8.0

### Screenshots

![image](https://user-images.githubusercontent.com/44390143/50072077-f32fee80-01f9-11e9-9786-37df57ccf747.png)

### Reproduction Link

Please find the sample from below link to reproduce the issue:
http://www.syncfusion.com/downloads/support/directtrac/general/ze/ListViewXF183758258

**Comment by kingces95** [comment]
Hm, works for me on 3.5.0. 

![3e653a12-8c49-4ee1-8cd1-4bfcc56138d7](https://user-images.githubusercontent.com/4120386/50367506-c85cd780-0524-11e9-9e8d-ca00bb089537.GIF)
