### ISSUE TITLE
Hide all Obsolete members from intellisense

### ISSUE THREAD

**Issue by kzu** [xamarin/Xamarin.Forms#4772]
A quick search on the codebase shows 130 matches for `[Obsolete(`, yet most (all?) of them are still visible in intellisense and pollute the API unnecessarily.

I think it would be fitting to annotate them all with `[EditorBrowsable(EditorBrowsableState.Never)]`.

I could contribute this change if deemed desirable.

Thanks!

**Comment by rmarinho** [comment]
+1 from me!

**Comment by StephaneDelcroix** [comment]
a PR would be totally fine. I don't get why Intelisense doesn't filter them out though

**Comment by kzu** [comment]
Yep, I wish intellisense just did the hiding by default for obsolete things too!

**Comment by jamesmontemagno** [comment]
Love this!

**Comment by kingces95** [comment]
@kzu PR away.
