### ISSUE TITLE
TapGestureRecognizer doesn't work for my Hyperlink in Xamarin.Mac

### ISSUE THREAD

**Issue by ChristianKleineidam** [xamarin/Xamarin.Forms#4775]
### Steps to Reproduce

I create a hyperlink through the code. You need to have a ViewModel with the possibility to bind `FileName` and `FilePickButton`:

                                <Label.FormattedText>
                                    <FormattedString>
                                        <Span Text="{Binding FileName,Mode=OneWay}"
                                        TextColor="#007AFF"
                                        FontSize="Medium"
                                        TextDecorations="Underline">
                                            <Span.GestureRecognizers>
                                                <TapGestureRecognizer Command="{Binding FilePickButton}" />
                                            </Span.GestureRecognizers>
                                        </Span>
                                    </FormattedString>
                                </Label.FormattedText>

### Expected Behavior
When I click on den hyperlink the function FilePickButton will be started the same way as it gets started in UWP/Android/iOS

### Actual Behavior
When I click on the hyperlink nothing happens.

### Basic Information

- Version with issue: Xamarin Forms 4.0.0.8055-pre1
- Affected Devices: MacBook Pro 2018

It might be a similar issue as https://github.com/xamarin/Xamarin.Forms/issues/2750 but I submitted a separate issue as I have the problem without creating a CustomView.

**Comment by AndreiMisiukevich** [comment]
@ChristianKleineidam hi
Seems it's by design.. but it isn't convenient.. @rmarinho @PureWeen  what do you think? 
Use **ClickGestureRecognizer** for Mac/Tizen instead (Check Device.RuntimePlatform)

**Comment by ChristianKleineidam** [comment]
If I simply exchange `TapGestureRecognizer` to `ClickGestureRecognizer ` in my code, it doesn't work in UWP. 
Given the intention of Xamarin.Forms it seems bad that I have to use a different function depending on the platform.

**Comment by AndreiMisiukevich** [comment]
@ChristianKleineidam yes :) I wanted to provide you any workaround. 
Also made PR for solving this issue
