### ISSUE TITLE
[Enhancement] Desktop: Multi-window support

### ISSUE THREAD

**Issue by jwosty** [xamarin/Xamarin.Forms#4777]
## Summary
Because Xamarin.Forms is becoming more and more of a real desktop platform, which I am very excited for, it should have a mechanism to create and manage multiple native windows at once on desktop platforms only.

## API Changes
I'm not completely sure what this would look like; I would love some feedback on the topic. I figure it's useful to at least open the floor to discussion. My main question to everyone is, then: Can this be done in a backwards-compatible way, or is this necessarily a earthshattering change? 

## Intended Use Case
Any sufficiently complex desktop application will soon need to be able to use _at least_ a second window; take, for example, the ever-so-common "Settings" (or "Preferences") window. While you can certainly jerry-rig this with platform-specific code, it will be ugly, brittle, and more work than it should be.

**Related to #2723**

**Comment by jwosty** [comment]
One potential way to create this would be to have a ``MultiWindowPage``, which would contain an IEnumerable of sub-pages, each of which would go in their own window.

**Comment by samhouts** [comment]
Related to #2432

**Comment by samhouts** [comment]
now related to #6483

**Comment by jfversluis** [comment]
Thanks for the idea and the input! This is a strong focus area for .NET MAUI, but won't be happening for Forms anymore. Closing this one
