### ISSUE TITLE
[Enhancement] Padding on Label

### ISSUE THREAD

**Issue by stefano-corricelli** [xamarin/Xamarin.Forms#4784]
## Summary
Make padding available in Label

## API Changes
var label = new Label();
label.Padding = new Thickness(10,0,0,0);

<Label Text="Test" Padding="10,0,0,0"/>

## Intended Use Case
It can be useful for a simple header or section divider instead of creating a contentView with padding and putting a label into it.

LOOK at the picture for an example
![schermata 2018-12-18 alle 09 26 20](https://user-images.githubusercontent.com/37268333/50141127-fd5bf680-02a6-11e9-9173-d8d84bdadf5c.png)

**Comment by thomas-bartleet** [comment]
What's wrong with putting a `Label` inside a `StackLayout`?

**Comment by stefano-corricelli** [comment]
it's an extra view layer.
Padding on label is available through CustomRenderer. I think this can be useful for others

**Comment by Evolutionlab** [comment]
i agree, we need every possibile tool to semplify layouts and avoid nesting views/layouts when possibile

**Comment by StephaneDelcroix** [comment]
on iOS, we don't use `UITextView`, but `UILabel`, and `UILabel` doesn't have `TextContainerInset`. so what do you recommend there ?

**Comment by stefano-corricelli** [comment]
I've seen that this can be done by overriding UILabel DrawText method in iOS
I'm doing some test with customrender I'll reply here when I've a working solution.

**Comment by stefano-corricelli** [comment]
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/2699387/Test.zip)


> on iOS, we don't use `UITextView`, but `UILabel`, and `UILabel` doesn't have `TextContainerInset`. so what do you recommend there ?

**Comment by stefano-corricelli** [comment]
any update ?

**Comment by jfversluis** [comment]
I would like to give it a shot, but I'm a bit worried about the custom inheritance we would have to create from the UILabel in regard to any other issues we might introduce here. Or maybe I'm overthinking things then... @StephaneDelcroix what do you think?

**Comment by JKennedy24** [comment]
This would be useful. Alot of the time in my application I have to do the following:

                                <ContentView BackgroundColor="Orange" Padding="10">
                                    <Label Style="{StaticResource HeaderMediumTextStyle}" Text="Availability}"/>
                                </ContentView >

Would be nice to get rid of the redundant ContentViews and just do:

                                    <Label Style="{StaticResource HeaderMediumTextStyle}" BackgroundColor="Orange" Padding="10" Text="Availability}"/>

**Comment by jfversluis** [comment]
Thanks for the feedback! I really see the added value for this. Just want to have a second opinion on the implementation for iOS. Also, some other PRs I need to finish up first.

@samhouts @davidortinau what is the win factor for this one? 😉

**Comment by stefano-corricelli** [comment]
Thank you guys, I'll appreciate if I can be mentioned if this enhancements will be distributed

**Comment by MookieFumi** [comment]
I've checking how it works and I'll try to do it in Android and iOS platforms so I'm going to open a new PR related with this issue.

**Comment by adrianknight89** [comment]
This should be given a higher priority, in my opinion. Like others, I've been wrapping labels with other controls to add tap gestures & padding and increase the surface area for the label tap. As mentioned earlier, this complicates the UI tree, but also makes it difficult to use spans. Consider the following scenario:

- Add a label with multiple spans, each with its own tap gesture.
- Toggle the visibility of a span on and off upon tapping

This works fine with a Label. Now, if you use a Grid/StackLayout with two labels, in a ListView, I've observed that the visibility changes are jarring. The parent layout is not handling such changes properly.

Aside from this, there are existing issues with spans, especially on Android, which make label tapping a poor experience on Xamarin Forms. See #4143 and #6046.

**Comment by andreinitescu** [comment]
See #6299. Feedback is welcome.
