### ISSUE TITLE
WPF WebView returns WebNavigationResult.Success in Navigated event for invalid URL

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#4787]
### Steps to Reproduce

1. Put WebView on a form
2. Set it's URL to unreachable source, e.g. "https://maxim-saplin2.github2.io/cpdt_results/"
3. Add Navigated event handler and check e.Result value on handler being called

### Expected Behavior

e.Result == WebNavigationResult.Failure

### Actual Behavior

e.Result == WebNavigationResult.Success 

### Basic Information

- Version with issue: 3.4
- IDE: Visual Studio Community 2017/15.19.4
- Platform Target Frameworks: WPF

**Comment by JamesBrining** [comment]
Not sure if this is the same issue but I get a success result if a web page returns a HTTP 500 error. Surely this should return a failure?

**Comment by maxim-saplin** [comment]
Assuming WebView is eventually replaced with a newer version this issues might be resolved automatically. https://github.com/xamarin/Xamarin.Forms/issues/10719

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
