### ISSUE TITLE
[Android] No method with name='setClipBounds' crash in ItemsViewRenderer

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#4790]
### Description

Crash `Java.Lang.LinkageError: no method with name='setClipBounds'` on Android 4.1/4.2.
`ClipBounds` property on the `RecyclerView` is set _without_ an API check for >= API 18.
https://github.com/xamarin/Xamarin.Forms/blob/f2948f1f0cf9829fe6ddafc60df2ac06a6a59ed0/Xamarin.Forms.Platform.Android/CollectionView/ItemsViewRenderer.cs#L48

**ClipBounds** property was added in API Level 18.
https://developer.xamarin.com/api/property/Android.Views.View.ClipBounds/

This change was introduced with the new `CollectionView`.

### Steps to Reproduce

1. Use a `Xamarin.Forms.CollectionView` control.

### Expected Behavior
App should not crash.

### Actual Behavior
App crash on an Android 4.1/4.2 device.

### Basic Information

- Version with issue: XF 4.0.0-pre1
- Last known good version: N/A
- Affected Devices: Android 4.1/4.2

### Suggestion
- _12/18 MR: I have tested ignoring this with an API check and it seems to correctly layout OK._
- Can we use the `ViewCompat` method available [here](https://android.googlesource.com/platform/frameworks/support/+/e5f75a851fbee9fbf1de31c738577fd86861a101/compat/java/android/support/v4/view/ViewCompat.java#1547) in Android.Support.V4.View? ie.
`ViewCompat.SetClipBounds(this, new Rect(0, 0, Width, Height));`

**Comment by pauldipietro** [comment]
We no longer support any APIs below 19, so this will be closed.
