### ISSUE TITLE
[macOS] Implement ImageButton on macOS

### ISSUE THREAD

**Issue by magmasystems** [xamarin/Xamarin.Forms#4792]
### Description
I am trying to port a working Xamarin Forms 3.4x project to macOS. The ImageButtons do not display.

### Steps to Reproduce
I have the following XAML code. I even tried to get a border to be displayed on the macOS version, just so I know that some of the ImageButton logic is working, even if the image itself was not being displayed. However, nothing displays on macOS, not even the border.

```
<ImageButton x:Name="btnFirstQuestion" Source="TriangleFastBackward.png"
                        IsEnabled="{Binding Path=IsFirstQuestion, Converter={StaticResource inverseBooleanConverter}}" 
                        Clicked="OnFirstQuestionClicked">
            <ImageButton.BorderWidth>
                    <OnPlatform x:TypeArguments="x:Double">
                            <On Platform="macOS" Value="1" />
                    </OnPlatform>
            </ImageButton.BorderWidth>
</ImageButton>
```

### Expected Behavior
The ImageButton should be displayed with the associated image and a 1px border. Even if the image has difficulty displaying, the 1px border should be displayed.

### Actual Behavior
Nothing is displayed.

### Basic Information
Xamarin Forms 3.40.1008975

- Version with issue:
- Last known good version: None
- IDE: Visual Studio Mac Community 7.71
- Affected Devices: MacBook Air Mid 2012, Mohave 10.14.1

**Comment by magmasystems** [comment]
A little more info about the bug that I reported. The ImageButton works fine on Android and on iOS. I was curious to see if the image was actually loading, so I added an Image with the same image source to my XAML.

```
<ViewCell>
    <FlexLayout Direction="Row" JustifyContent="SpaceAround">                        
       <ImageButton Source="EditQuestionBank.png" HeightRequest="32" WidthRequest="32" />
       <Image Source="EditQuestionBank.png" HeightRequest="32" WidthRequest="32" />
```
The **Image** displays just fine. It is a 32x32 PNG. The **ImageButton** still does not display.

**Comment by magmasystems** [comment]
I created a small sample project that displays the problem. Please download the sample project from [here](https://magmasystems.visualstudio.com/_git/XamarinImageButtonTest)

@kingces95

**Comment by mdonogma** [comment]
Is image button supposed to work on .Mac apps to?

same issue with my Xamarin.forms Mac project. Image button functions on iOS, android but doesn't show. in Xamarin.mac - even with the width and height set it doesn't work.
XAML:
  <ImageButton Source="Rectangle.png"
                    HorizontalOptions="Center"
                    VerticalOptions="CenterAndExpand" WidthRequest="100" HeightRequest="100" >

IOS screenshot
![image](https://user-images.githubusercontent.com/13458476/52156193-818d0080-26d2-11e9-89e5-ae123b0d2389.png)
![image](https://user-images.githubusercontent.com/13458476/52156206-8c479580-26d2-11e9-9eb2-5fbc3777432f.png)

Mac screenshot - no button
![image](https://user-images.githubusercontent.com/13458476/52156226-ac775480-26d2-11e9-956e-4d48fed85266.png)

**Comment by mdonogma** [comment]
just want to point out the official documentation doesn't indicate imagebutton won't work on Xamarin forms Mac apps. - what about uwp apps?
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/imagebutton

**Comment by tekmun** [comment]
Now that Xamarin Essentials 1.6 supports MacOS, it's possible to build MacOS app from Xamarin Forms.  Unfortunately, the lack of renderer for Image Button for MacOS is the show-stopper. 

Can this be a top priority in Xamarin Forms especially after so much efforts being put into supporting Xamarin.MacOS over the past two years?  Thank you.

**Comment by CartBlanche** [comment]
I have the same issue on MacOS. I will see if I can work out how to add the renderer and submit a PR.

**Comment by mhrastegary77** [comment]
Same issue :(

**Comment by jfversluis** [comment]
Unless someone wants to pick this up, I will review it, but otherwise this won't be happening for Xamarin.Forms anymore, sorry!

**Comment by CartBlanche** [comment]
@jfversluis Has this already been implemented in Maui??

**Comment by jfversluis** [comment]
@CartBlanche for .NET MAUI we share the code between iOS and macOS, so yes that has been implemented there: https://github.com/dotnet/maui/wiki/Status#-imagebutton
