### ISSUE TITLE
[Enhancement] ImageButton should display alternate text if image cannot be rendered

### ISSUE THREAD

**Issue by magmasystems** [xamarin/Xamarin.Forms#4793]
## Summary
If for some reason, the image in an ImageButton cannot be rendered, there should be an option for the developer to specify an alternate text to be displayed, much like the <img> tag in HTML.

## API Changes

<ImageButton ...... alt="X" ... />

## Intended Use Case
I am having difficulty displaying an ImageButton with Xamarin Forms in a macOS project (see bug #4792 ). It would be good if I was able to specify some alternative text that could be displayed.

**Comment by jfversluis** [comment]
Thanks for your suggestion! This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
