### ISSUE TITLE
Updating properties on WkWebViewConfiguration after WkWebView has been created has no effect

### ISSUE THREAD

**Issue by mchipeta** [xamarin/Xamarin.Forms#4815]
### Description

Setting properties on WkWebViewConfiguration after a WkWebView has been created has no effect. I created a simple custom renderer that inherits from WkWebViewRenderer (see ..\WkWebViewConfigurationIssue.iOS\Renderers\BasicWkWebViewRenderer.cs in the attached sample) to set a couple of properties in the OnElementChanged method to allow videos to play automatically:

        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);

            Configuration.AllowsInlineMediaPlayback = true;
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                Configuration.MediaTypesRequiringUserActionForPlayback = WKAudiovisualMediaTypes.None;
            }
            else
            {
                Configuration.MediaPlaybackRequiresUserAction = false;
            }
        }

However, this has no effect. I only managed to get videos to play automatically after injecting a properly configured WkWebViewConfiguration object into the constructor of WkWebView (see the constructor of ..\WkWebViewConfigurationIssue.iOS\Renderers\AdvancedWkWebViewRenderer.cs in the attached sample - a slightly modified copy of [WkWebViewRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs) in the Xamarin.Forms master branch). 

[WkWebViewConfigurationIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2691309/WkWebViewConfigurationIssue.zip)
You can switch between BasicWkWebViewRenderer and AdvancedWkWebViewRenderer by commenting out the appropriate line in ..\WkWebViewConfigurationIssue.iOS\Properties\AssemblyInfo.cs from the attached sample.

### Steps to Reproduce

1. Download the attached sample.
2. Run the sample on an iOS device or simulator.

### Expected Behavior
The video should start playing automatically.
### Actual Behavior
The video does not play automatically.
### Basic Information

- Version with issue: Xamarin.Forms 3.4.0.1008975
- Last known good version: Unknown
- IDE: Visual Studio Enterprise 2017 v15.9.2
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: N/A 
  - UWP:  N/A 
- Android Support Library Version: N/A
- Nuget Packages:
  - Xamarin.Forms 3.4.0.1008975
  - NETStandard.Library 2.0.3
- Affected Devices: iOS 8 and above

**Comment by mchipeta** [comment]
[WkWebViewConfigurationIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2691319/WkWebViewConfigurationIssue.zip)

**Comment by kingces95** [comment]
Going to file this a feature request to enable auto-play of videos.

**Comment by ats124** [comment]
I have a similar problem.
`WKWebViewConfiguration.ApplicationNameForUserAgent` property will not be updated.
Because `WKWebView.Configuration` property returns a copy, I think that other properties will not be updated as well.

How about adding a constructor like the following?
``` csharp
public WkWebViewRenderer(WKWebViewConfiguration config) : base(RectangleF.Empty, config)
{
}
```

**Comment by ravinderjangra** [comment]
I'm having the same issue. Any update on this? Also @ats124's suggestion makes sense. I can raise a PR with same.
