### ISSUE TITLE
[android]OnResume lifecycle event is not called when android app foregrounded

### ISSUE THREAD

**Issue by Vishnunavaneeth** [xamarin/Xamarin.Forms#4821]
### Description
I am developing a Xamarin Forms app targeting both android and iOS. It is working as expected in iOS and most of the android phones. But when I tested in my Moto G android phone(Android 8.0.0, with 6GB of RAM), OnInitialized event is triggered instead OnResume event when the application is foregrounded. So every time my application gets initialized when foregrounded which is very strange and annoying

### Steps to Reproduce

1. install the xamarin forms application in Moto G(Android 8.0.0)
2. goto wifi application and change the wifi(it is one of the cases for my application) Or just press home button to get the application backgrounded
3. bring the application to foreground, OnInitialize event is triggered instead of OnResume event

### Expected Behavior
OnResume event should be called
### Actual Behavior
OnInitialized event is called
### Basic Information

- Version with issue:
Xamarin Forms : 3.4.0.1008975
Android 8.0.0
Phone:Moto G
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: 8.0.0
  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
MotoG

**Comment by kvpt** [comment]
Do you mean OnCreate instead of OnInitialized ?
If it's the case I don't think it's a bug, it's the way Android work.
When the app is in background, you have no warranty that the app activity will not be killed by Android.
It's often happen when your device is low on memory.
You can even force Android to kill background activity in a developer mode setting to test this case.

**Comment by kingces95** [comment]
Hm, well, there you go. You might have been killed by Google.

**Comment by Vishnunavaneeth** [comment]
Hello,  Sorry If I didn't explain you well. I was talking about Xamarin Forms App life cycle events and Ofcourse, I meant OnInitialized and not OnCreate. In this case, OnInitalized was=s called instead of OnResume which is wrong. That too this behavior happens only in one particular phone which I believe is a bug. Please note that there are no memory crunch on the phone, it is having 6GB of RAM and no other apps were launched in our tries.

**Comment by Vishnunavaneeth** [comment]
Hello,

Sorry If I didn't explain you well. I was talking about Xamarin Forms App life cycle events and Ofcourse, I meant OnInitialized and not OnCreate. In this case, OnInitalized was called instead of OnResume which is wrong. That too this behavior happens only in one particular phone which I believe is a bug. Please note that there are no memory crunch on the phone, it is having 6GB of RAM and no other apps were launched in our tries.

So there is an issue. Please do not close this defect.

Thanks and Regards,
Vishnu
