### ISSUE TITLE
Previewer doesn't check ProjectCapability

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#4822]
### Description

the previewer require the Forms nuget, but it should instead check for ProjectCapability

<img width="737" alt="image" src="https://user-images.githubusercontent.com/313003/50219276-fc9e8f80-038e-11e9-88e5-d6d590774996.png">

https://github.com/xamarin/Xamarin.Forms/blob/5a8e612d8aef6e57a9a01f8e1c50e004334fbec6/.nuspec/Xamarin.Forms.targets#L23

/cc @alanmcgovern @drewgillies

> VS bug [#754336](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754336)

**Comment by StephaneDelcroix** [comment]
see https://github.com/xamarin/Xamarin.Forms/pull/1164

**Comment by alanmcgovern** [comment]
We display this message when Xamarin.Forms.Core.dll can't be located. This assembly is a pre-requisite for doing anything.

Either the forms nuget was not restored correctly, or something else has gone wrong. Either way, we would not gain anything from changing this check.

Without information about what caused that message to appear we won't be able to do anything.

**Comment by StephaneDelcroix** [comment]
the message is caused when I try to enable the previewer on projects directly linked to the XF sources, and not the nuget. Any xaml page of our ControlGallery for example

**Comment by alanmcgovern** [comment]
So the scenario is you have xaml files in a csproj, and that csproj has a `<ProjectReference >` to xamarin.forms.core.csproj?

**Comment by StephaneDelcroix** [comment]
> So the scenario is you have xaml files in a csproj, and that csproj has a <ProjectReference > to xamarin.forms.core.csproj

and an import to the x.f.targets, that defines the project capability

**Comment by alanmcgovern** [comment]
Yeah - my point is that the project capability won't help us. What we require is a copy of the forms binaries, and you're hitting a scenario where we seem to fail to find them. Without the binaries we can't render :)

We will investigate this particular scenario. It will be lower priority than the dev16 work as this scenario is limited to the case where you are directly working with Forms.

Thanks!
