### ISSUE TITLE
Latest Android support binaries cause "java.exe exited with code 2" build errors

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#4825]
### Description

Just updated to latest Android support binaries, seeing this error building my Xamarin Forms app:

1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2610,3): error MSB6006: "java.exe" exited with code 2.

### Steps to Reproduce

1. Install latest Android support binaries
2. Build
3. Observe Java.exe error

### Expected Behavior

Successful builds, like before the update.

### Actual Behavior

Build errors.

### Basic Information

- Version with issue: 28.0.0
- Last known good version: 27.0.2.1
- IDE: VS 15.9.4
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
Thanks for filing this issue. But in order to even start investigating we'd need at the very least a full build log, and ideally a zipped version of your project.

thanks

**Comment by mfeingol** [comment]
Yeah, sorry for the post and run. I'll get you more specifics when I'm home later today.

**Comment by mfeingol** [comment]
Any downsides to enabling multidex, btw? I see rumblings about decreased startup time, which is already an issue with my app...

**Comment by PureWeen** [comment]
@mfeingol if you can get below the dex limit through ProGuard that would be more ideal

Here's some info on getting started with ProGuard and XF
https://github.com/xamarin/Xamarin.Forms/issues/2709

**Comment by mfeingol** [comment]
Thanks for that. I grabbed the proguard.cfg file from https://stackoverflow.com/questions/39514518/xamarin-android-proguard-unsupported-class-version-number-52-0/43959560#43959560. I'm curious how much of that file is really needed... But I was able to deploy and run an x86 release build into the emulator after manually keeping `android.support.v7.widget.FitWindowsLinearLayout` and `android.support.v7.widget.FitWindowsFrameLayout` as well.

I also bit the bullet and enabled AOT + LLVM, which took me down an NDK installation rabbithole (https://github.com/xamarin/xamarin-android/issues/2429).

Again, I'd say in general it would be good if these more advanced topics could be approached in a somewhat easier fashion.

**Comment by bondarenkod** [comment]
I started getting the same building error after update to 28.0.0 libraries 
I tried to rebuild & clean (all bin\obj manually) before I turned on the **multi dex**. I hope that's the solution)

**Comment by amaan-ahmad** [comment]
> Thanks for that. I grabbed the proguard.cfg file from https://stackoverflow.com/questions/39514518/xamarin-android-proguard-unsupported-class-version-number-52-0/43959560#43959560. I'm curious how much of that file is really needed... But I was able to deploy and run an x86 release build into the emulator after manually keeping `android.support.v7.widget.FitWindowsLinearLayout` and `android.support.v7.widget.FitWindowsFrameLayout` as well.
> 
> I also bit the bullet and enabled AOT + LLVM, which took me down an NDK installation rabbithole ([xamarin/xamarin-android#2429](https://github.com/xamarin/xamarin-android/issues/2429)).
> 
> Again, I'd say in general it would be good if these more advanced topics could be approached in a somewhat easier fashion.

Thanks man ! that helped me out !

**Comment by manuelduarte077** [comment]
https://www.jon-douglas.com/2016/09/05/xamarin-android-multidex/
