### ISSUE TITLE
[Enhancement] Make CollectionView ItemTemplate work with DataTemplateSelector

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#4826]
Currently, setting the `ItemTemplate` property to a `DataTemplateSelector` throws an exception because `LoadTemplate` in `ElementTemplate` is null. We should be able to provide different data templates based on item state when using `CollectionView`.

**Comment by matteopiccioni** [comment]
I think the following exception is related DataTemplateSelector

XF version: 4.0.0.304370-pre8
With this version of XF DataTemplateSelector are working  great on Android

Using iOS I have the following exception:
`Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).
Native stack trace:
	0   CoreFoundation                      0x00000001ba281ebc <redacted> + 252
	1   libobjc.A.dylib                     0x00000001b9451a50 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001ba197a2c <redacted> + 0
	3   Foundation                          0x00000001bac861d0 <redacted> + 112
	4   UIKitCore                           0x00000001e6e50d04 <redacted> + 12840
	5   UIKitCore                           0x00000001e6e4d760 <redacted> + 548
	6   UIKitCore                           0x00000001e6e4d804 <redacted> + 68
	7   UserApp.iOS                         0x0000000105c6edb0 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 50642384`

**Comment by Henri2h** [comment]
I don't know if it supposed to be fixed, but I still experience this issue using XF 4.0.0.394984-pre10.

**Comment by TheBaileyBrew** [comment]
@matteopiccioni -- I had a similar issue, and it was related to how I was refreshing my CollectionView. 

Are you by chance, trying to empty the ObservableCollection with .Clear() or by a different method?

I was trying to change the Collection manually (by clearing out data) rather than just reinstantiating the OC with the new data that was being returned from my API call. by doing this instead, I stopped getting that error.

    myObservableCollection = new ObservableCollection<ModelClass>(ReferenceToItemsBeingAddedFromAPIReturn);

**Comment by matteopiccioni** [comment]
> @matteopiccioni -- I had a similar issue, and it was related to how I was refreshing my CollectionView.
> 
> Are you by chance, trying to empty the ObservableCollection with .Clear() or by a different method?
> 
> I was trying to change the Collection manually (by clearing out data) rather than just reinstantiating the OC with the new data that was being returned from my API call. by doing this instead, I stopped getting that error.
> 
> ```
> myObservableCollection = new ObservableCollection<ModelClass>(ReferenceToItemsBeingAddedFromAPIReturn);
> ```

Hello, at the end I roll back to listview
