### ISSUE TITLE
Custom fonts don't work in UWP when they are set by code

### ISSUE THREAD

**Issue by egarim** [xamarin/Xamarin.Forms#4828]
### Description
Custom fonts don't work in UWP when they are set by code
### Steps to Reproduce
1) In any content-page add a label by code and set the font family to UW<filename>#<font name>, and set the text property
2) Run the application

### Expected Behavior
the text should be shown using the correct font family
### Actual Behavior
the text is not shown or show squares
### Basic Information

- Version with issue:
- Last known good version: unknown
- IDE: Visual Studio 2017
- UAP,Version=10.0.16299.0
- Xamarin Forms = 3.4.0.1008975
- Affected Devices:
Windows 10
### Screenshots
![image](https://user-images.githubusercontent.com/2864804/50269260-ce788880-043e-11e9-8bcf-b511756d16b7.png)

### Reproduction Link

[CustomFont.zip](https://github.com/xamarin/Xamarin.Forms/files/2697736/CustomFont.zip)

**Comment by kingces95** [comment]
Hm, well if I use the debugger to dig out the string XAML created and get the `char` as an `int` then smash that into the C# like this `((char)61722)` then it works. So I think the issue is the XAML char encoding vs the C# encoding.

**Comment by egarim** [comment]
Thanks, converting to chars do the trick. Now I wonder why does it work in android without doing the char conversion?
