### ISSUE TITLE
FontIcon was crashed in Android Previewer

### ISSUE THREAD

**Issue by Chozarajan** [xamarin/Xamarin.Forms#4831]
### Description

If we set the font icon in XAML code, it's not shown in the previewer. The null reference was thrown in previewer page. 

### Steps to Reproduce

1. Compile the attached sample
2. Open the Android previewer
3. The Icon was not shown in the previewer

### Expected Behavior
The Icon has to show in the previewer.

### Actual Behavior
The null reference exception was thrown in the previewer.

### Basic Information

- Version with issue: All versions
- Last known good version: - 
- IDE: VS 17 MAC
- Platform Target Frameworks: 
  - Android: 7.1
- Android Support Library Version: None
- Nuget Packages: None
- Affected Devices: previewer error

### Screenshots

Issue Image:
![image](https://user-images.githubusercontent.com/42271947/50280368-4b712580-0472-11e9-9a19-cd90de5acd15.png)

### Reproduction Link

Sample Link : 
[FontIconIssueSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2698517/FontIconIssueSample.zip)

> VS bug [#754970](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754970)

**Comment by TimBarham** [comment]
No longer repro's with latest Previewer and Forms.

**Comment by RathnaPrem** [comment]
Hi @TimBarham 

The reported issue still occurs in the latest Xamarin.Forms stable and beta versions.

![Screenshot 2019-03-19 at 2 31 58 PM](https://user-images.githubusercontent.com/47023307/54593212-0b5f1600-4a54-11e9-864b-fc5fa2b4c622.png)

**Comment by Chozarajan** [comment]
Please reopen this issue
