### ISSUE TITLE
Behaviors in ControlTemplate throws InvalidOperationException

### ISSUE THREAD

**Issue by vincentcastagna** [xamarin/Xamarin.Forms#4835]
### Description
When using a behavior in a `ControlTemplate`, throws ` InvalidOperationException : Operation is not valid due to the current state of the object`

I reproduced the error with prism `EventToCommandBehavior `but also with custom `EventToCommandBehavior`. 

There is a thread on XF forum about this issue that many developers met 

https://forums.xamarin.com/discussion/88518/behaviors-in-controltemplates

### Steps to Reproduce

1. Create a ControlTemplate with a ListView
2. Add a Behavior to the ListView
3. Use the ControlTemplate

### Expected Behavior

No exception.
 
### Actual Behavior

The exception is thrown on any kind of control with an attached `EventToCommandBehavior `or a control for which there are one or more `Command Binding` **AND** `behaviors `attached. 

### Basic Information

- Version with issue (and older - Issue since 2017 see XF forum):
- Xamarin Forms 3.2 
- Prism Forms : 7.1
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  iOS 12  
  - Android: Android 9.0 

- Affected Devices: ALL 

### Reproduction Link

A bit of a cleaner repro without bin/obj folders and updated to latest XF
[ReproFromShane.zip](https://github.com/xamarin/Xamarin.Forms/files/2722541/ReproFromShane.zip)

Edit : @PureWeen  thanks for providing sample, did not find time for that ... apologize. 

PRISM 
[Repro.rar](https://drive.google.com/file/d/1klkV9xIHY-ZZt1AiftxYyBdMcufD1l2N/view?usp=sharing)

**Comment by kingces95** [comment]
Having issues loading the project on 3.5.0 latest. Could you resubmit your issue without any 3ed party assemblies (ie. prism)?

![image](https://user-images.githubusercontent.com/4120386/50365919-db6aaa00-051a-11e9-9332-de193182427e.png)

**Comment by Nk54** [comment]
I run into the same issue today.
The same code runs well when outside a ControlTemplate.

The workaround to use is to avoid TemplateBinding and use a Binding with a Source set to the Control.
e.g: `Command="{Binding ItemTappedCommand, Source={x:Reference Self}, Mode=OneTime}"`
Where Self is the root element.

**Comment by EP01** [comment]
Just ran into this on UWP too. Workaround works, thanks @Nk54!

**Comment by libin85** [comment]
I have the same issue, Behaviors dont work in ControlTemplate. Get an error "operation is not valid due to the current state of the object"

**Comment by andreinitescu** [comment]
This is by design. `TemplateBinding` only works within the actual content. it doesn't work setting it on a `Behavior` which is not a view and has no parent view, it's just an "attached" property:
```
<ListView.Behaviors>
      <behavior:EventToCommandBehavior EventName="ItemSelected" Command="{Binding LoadMoreCommand}"/>
</ListView.Behaviors>
```
The same behavior is in WPF and UWP.

**Comment by andreinitescu** [comment]
One solution is already given by @Nk54 above, which is to use x:Reference.
Another solution, but not yet available, is to use RelativeSource binding, which is coming in #4375

**Comment by StephaneDelcroix** [comment]
thx again @andreinitescu for the extra investigation. you're right. and thanks also fro providing guidance towards a solution
