### ISSUE TITLE
[Shell] Cannot pass querystring value to registered route

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4837]
### Description

When a page is not in a `ShellContent`, the querystring values aren't passed/applied.

### Steps to Reproduce

Register a route like:

```
Routing.RegisterRoute("second",  typeof(Page2));
```

Navigate to it like:

```
await (App.Current.MainPage as Shell).GoToAsync($"app:///base/second?id=new");
```

And retrieve the query property like:

```
[QueryProperty("ID", "id")]
    public partial class Page2 : ContentPage
    {
        public Page2()
        {
            InitializeComponent();
        }
        
        private string _id = "Broken";
        public string ID
        {
            get { return _id; }
            set
            {
                _id = value;
                IDLabel.Text = _id;

            }
        }
    }
```

### Expected Behavior

The  ID is set.

### Actual Behavior

Not set.

### Basic Information

- Version with issue: 4.0-pre1

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2700181/Archive.zip)

**Comment by Robtom5** [comment]
I've just had this error occur again on V4.0.0.346134-pre9. I'm getting an ArgumentException `System.ArgumentException: unable to figure out route for: app://foo.com/shell_mock/outing?parameter=bar
Parameter name: uri`
When I'm registering the route using `Routing.RegisterRoute("outing", typeof(OutingPage));`. If I define the page in my shell xaml instead then it resolves correctly
