### ISSUE TITLE
[Shell] ContentPage with UseSafeArea incorrectly renders

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#4840]
### Description

I have a  `ContentPage` in an app being ported to Shell. The tabs atop the page are not displayed when inside of Shell although the space is reserved; they just aren't visible. 

<img width="545" alt="screenshot 2018-12-20 20 36 48" src="https://user-images.githubusercontent.com/41873/50322195-baae4000-0499-11e9-94f3-d34eacd62812.png">

Removing the UseSafeArea shows the content, however now under what would be the nav bar (my app removes the nav bar background).

Related to #4752 

<img width="545" alt="screenshot 2018-12-20 20 39 21" src="https://user-images.githubusercontent.com/41873/50322264-f6e1a080-0499-11e9-9bd6-d234bc8cf291.png">

Original app and page:
https://github.com/davidortinau/HowYouSay/blob/master/HowYouSay.Shared/Views/HomeView.xaml

This YConstraint appears to be the difference. Removing  it and assuming a 0 coordinate "fixes" the issue.  

https://github.com/davidortinau/HowYouSay/blob/master/HowYouSay.Shared/Views/HomeView.xaml#L28

But I'm concerned that the layout renders different in Shell  than it did in the non-Shell app that uses MasterDetailPage and NavigationPage.

### Expected Behavior

Tabs (Buttons and BoxViews) appear at the top, between the nav bar and the ListView.

<img width="545" alt="screenshot 2018-12-20 20 55 52" src="https://user-images.githubusercontent.com/41873/50322179-af5b1480-0499-11e9-94f8-3b3e83c2e015.png">

### Actual Behavior

The space is there, but the elements are not visible.

<img width="545" alt="screenshot 2018-12-20 20 36 48" src="https://user-images.githubusercontent.com/41873/50322195-baae4000-0499-11e9-94f3-d34eacd62812.png">

If I hide the ListView the buttons appear to be possibly below it:

<img width="545" alt="screenshot 2018-12-20 20 52 25" src="https://user-images.githubusercontent.com/41873/50322249-e92c1b00-0499-11e9-82d0-5642683b459c.png">

### Basic Information

- Version with issue: 4.0-pre1

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2701354/Archive.zip)
Parent: #2415

**Comment by rmarinho** [comment]
If you `Shell.SetPaddingInsets` to true it fixes the issue:

![simulator screen shot - iphone xs max - 2019-03-06 at 18 10 39](https://user-images.githubusercontent.com/1235097/53904240-7c0e3780-403d-11e9-9952-8d963e1db96d.png)

after:

![simulator screen shot - iphone xs max - 2019-03-06 at 18 27 03](https://user-images.githubusercontent.com/1235097/53904259-86303600-403d-11e9-9bf3-8bdacc9d7132.png)
