### ISSUE TITLE
"Can't resolve reference get_Platform()" when targeting connected iPhone, Forms 4.0.0

### ISSUE THREAD

**Issue by klzig** [xamarin/Xamarin.Forms#4841]
### Description
After upgrading to Forms 4.0.0, build fails with following error when targeting a connected iPhone 6S.  Build and deploy succeed when targeting simulated iPhone 6S or physical Android device.

> Can't resolve the reference 'Xamarin.Forms.Internals.IPlatform Xamarin.Forms.Element::get_Platform()', referenced from the method 'System.Void Naxam.Mapbox.Platform.iOS.Extensions.FormsViewContainer::Dispose(System.Boolean)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.	CTForms.iOS	

### Steps to Reproduce

1. Working project on Forms 3.4
2. Upgrade nuget to Forms preview 4.0.0
3. Target connected iPhone, build

### Expected Behavior
App builds and deploys to connected iPhone

### Actual Behavior
Build error.  Build and deploy succeed when targeting simulated iPhone.

### Basic Information

- Version with issue: 4.0.0.8055-pre1
- Last known good version: 3.4.0.1008975
- IDE: Visual Studio 2017 15.9.4 (Windows)
- Platform Target Frameworks:
  - iOS:  12.1
- Nuget Packages:
Xamarin.Forms v4.0.0.8055-pre1
Xamarin.Essentials v1.0.0
Newtonsoft.Json v12.0.1
Naxam.Mapbox.Forms v1.0.5.2
- Affected Devices:
iPhone 6S (the only physical iOS device I have)

### Screenshots

N/A

### Reproduction Link

N/A

**Comment by StephaneDelcroix** [comment]
X.F.Element.Platform was removed (#4235), but was part of our hidden API and shouldn't have been used by `Naxam.Mapbox. Please report this issue to that library authors.
