### ISSUE TITLE
Bottom Tabbed Bar With Customised Tab Menu

### ISSUE THREAD

**Issue by ronakshethia** [xamarin/Xamarin.Forms#4842]
I am trying to get a Circular Icon of my Application Logo right in middle of tabbed bar menu's, I have 5 Tab Menu's where the third one i want it to look like this

this

![demo](https://user-images.githubusercontent.com/35444818/50330674-1de3b500-0522-11e9-8a71-ef5a497211a4.png)

trying to get this on Android & Ios

i have tried custom rendering by removing the padding but still not able to get the desired result, i found one solution updating icon using SetTabIcons Method but this method does not get trigger when we are working with bottom tabbed bar in Android, please suggest me something which can help me to get this for both android & Ios

**Comment by ronakshethia** [comment]
@ChasakisD i tried doing that but could not make it work could you please help me with code or some reference

**Comment by samhouts** [comment]
Hi! If you're still looking for assistance, try https://forums.xamarin.com/categories/xamarin-forms. Thanks!
