### ISSUE TITLE
Text isn't entered into the correct textfield in android

### ISSUE THREAD

**Issue by Axemasta** [xamarin/Xamarin.Forms#4844]
### Description
I have a form where the user can fill in different bits of information. The form is created using a `TableView`. I have created the following UI:

```
<TableView>
    <TableSection>
        <ViewCell>
            <StackLayout Orientation="Horizontal">
                <Label Text="Field 1"/>
                <Entry Placeholder="Enter text to field one"/>
            </StackLayout> 
        </ViewCell>
        
        <ViewCell>
            <StackLayout Orientation="Horizontal">
                <Label Text="Field 2"/>
                <Entry Placeholder="Enter number to field two" Keyboard="Numeric"/>
            </StackLayout> 
        </ViewCell>
    </TableSection>
</TableView>
```

When text is entered into `Field 1`, selecting `Field 2` will bring up a numeric keyboard and quickly swap to a default keyboard. Any text entered will now be entered into `Field 1`. This does not occur when field 2 is the first textbox to be pressed.

### Steps to Reproduce

I have included a zip file with this issue of a barebones recreation of the issue

1. Create a new app and paste the above XAML into the MainPage.xaml
2. Run the app
3. Press textfield 1 and enter text
4. Press textfield 2 and enter text

### Expected Behavior
Textfield 1 pops up the default keyboard and any text entered populate this textfield.
Textfield 2 pops up the numeric keyboard and any numbers entered populate this textfield.

### Actual Behavior
When pressing textfield 2, the numeric keyboard pops up and then a new keyboard pops up (the same as for textfield 1), any text entered will be placed into textfield one, whilst textfield 2 is highlighted.

### Basic Information

- Versions with issue:
3.3.0.637273
3.3.0.967583
3.4.0.1008975

- Last known good version: ? This code worked in 2.5
- IDE: Visual Studio Community for Mac (7.7.2, build 21)
- Platform Target Frameworks: 
Targeting 27, minimum 21, running on 24
- Android Support Library Version: 
tested with 27.0.21 & 28

- Nuget Packages:
Out of the box
- Affected Devices:
Motorola Moto 4G

### Screenshots

![xamarin bug demo 1](https://user-images.githubusercontent.com/33064621/50347906-2989a880-052f-11e9-991a-6a85b8d2d50e.gif)
![xamarin bug demo 2](https://user-images.githubusercontent.com/33064621/50347916-31e1e380-052f-11e9-928a-b9a0b05e509c.gif)

### Reproduction Link
[EntryBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2703183/EntryBug.zip)

**Comment by kingces95** [comment]
Unable to reproduce on 3.5.0... maybe we fixed it?

![e5a64b8e-7ff7-44d0-93b2-cef30601a411](https://user-images.githubusercontent.com/4120386/50368923-e846c800-0531-11e9-9196-2401fa01f4cf.GIF)

**Comment by Axemasta** [comment]
@kingces95 did you try this with my provided code? it could have been the device but I'd like to know if others had the same issues on the versions I tested the bug.
