### ISSUE TITLE
HorizontalTextAlignment in Label is not working when setting LineHeight (IOS only)

### ISSUE THREAD

**Issue by moustafashaban** [xamarin/Xamarin.Forms#4847]
### Description
HorizontalTextAlignment in Label is not working when setting LineHeight 
Note, this is only in IOS, Android is fine
### Steps to Reproduce

1. add a label in the contentPage like this
        `    <Label LineHeight="2" FontSize="30" HorizontalOptions="Fill" HorizontalTextAlignment="End" Text="Test Text Test Text Text Test Text Text Test Text Text Test Text Text Test Text Test Text Text Test Text Text Test Text Text Test Text Text Test " />`
2. try with removing the 

> LineHeight="2"

### Expected Behavior
HorizontalTextAlignment should work the same when adding or removing LineHeight property
### Actual Behavior
HorizontalTextAlignment is not updated (it is acting only as Left)

Xamarin Library: 3.4.0.1008975

**Comment by PureWeen** [comment]
I tested on master and it looks like this which seems correct.

Does this look how you would expect it to?

![image](https://user-images.githubusercontent.com/5375137/50720999-0e618180-1075-11e9-8db7-ee6b69ec0242.png)
