### ISSUE TITLE
[Enhancement] Make ItemsSource and ItemTemplate more broadly available

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#4849]
## Summary

Many apps are data driven. There are many times in which the right control just might be a StackLayout, Grid, or a FlexLayout. All of these layouts layouts could greatly benefit from an ability to simply Bind a collection of data, and have the children more dynamically added with DataTemplates and/or a DataTemplateSelector.

## API Changes

An `itemsSource` and `ItemTemplate` would be added to common layouts like StackLayout, FlexLayout, & possibly the Grid to facilitate dynamically building out data driven views. In the case of the Grid we probably need some additional helper here that would provide greater context when trying to layout the Children (i.e. which row/column/{row|col}span

e.g.

```xml
<StackLayout ItemsSource="{Binding Monkeys}">
  <StackLayout.ItemTemplate>
    <DataTemplate>
      <SomeAwesomeView />
    </DataTemplate>
  </StackLayout>
</StackLayout>
```

**Comment by GalaxiaGuy** [comment]
A pair of attached properties have recently been added that can be used with any layout to achieve this effect:

https://github.com/xamarin/Xamarin.Forms/pull/4052

**Comment by dansiegel** [comment]
Perfect. No reason to keep this open then.
