### ISSUE TITLE
Android previewer issues and Visual Studio 2017 XAML formatting issues

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#4851]
### Description

Please checkout the video
https://www.youtube.com/watch?v=OPjuBA0zlno&feature=youtu.be

The issues showed in the video are (in the same order I recorded in the video) :

1.  **After creating a project and building it, opening the previewer doesn't show the preview**. 
    In order to see the preview before starting my work, I have to do a small change just to trigger the preview.

2. Android previewer (iOS previewer seems to work): Setting **FontSize** is not reflected in the preview

3.  Android previewer (iOS previewer seems to work): Setting **RotationX/Y** is not reflected in the preview

4.  Very annoying and important: **Formatting the XAML** does not work.
    (I noticed that even if sometimes it works, it breaks after a while, the formatting just stops working. Trying to fix it by reopening the XAML and/or rebuilding the project doesn't work).

/cc @alanmcgovern @drewgillies 

### Steps to Reproduce

Please see the video 

### Basic Information

- Version with issue:
- Last known good version: `¯\_(ツ)_/¯`
- IDE: **Visual Studio 2017 Enterprise, v15.9.4**
- Platform Target Frameworks: 
  - Android: The default of the Xamarin Forms project template (Android 8.1)

### Reproduction Link

> VS bug [#756305](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/756305)

**Comment by andreinitescu** [comment]
Setting the RotationX/Y property is still not working in VS2019. 
I'm sorry but what's the point of reporting issues if they're being closed without being fixed?

**Comment by drewgillies** [comment]
Have reactivated this bug.

**Comment by maddyleger1** [comment]
@andreinitescu We are closing this bug as it is not an issue with Xamarin.Forms - it's an issue inside of Visual Studio. We are tracking the X/Y Rotation internally and I can update you here when it's fixed. Thanks!

**Comment by BretJohnson** [comment]
As for the X/Y Rotation, here's the status:

When the rotation property is set in the native Android designer it doesn't render either. Nor does it render in Android Studio. The layoutlib based renderer must just not support it, for whatever reason.

Rotation (which adds an perspective effect to the text) does render properly on the Android device itself, so it's supported with Android & Forms, just not by the Google layoutlib desktop render code.
