### ISSUE TITLE
[Enhancement] TargetIdiom as Xbox or Console

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#4852]
## Summary
Currently, if i run a UWP, on xbox or desktop, TargetIdiom is always Desktop. This can be extended as we know from the Device.Family as below

AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Desktop"
AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Xbox"

## API Changes
 
TargetIdiom enum has new value as "Xbox" or "Console"
 
## Intended Use Case
It helps to adjust functionality and UI on Xbox to separate from Desktop

**Comment by EmilAlipiev** [comment]
why actually below code is used to detect platform [here](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.UAP/Forms.cs)? Uwp Api already gives DeviceFamily  which determines if it is desktop, mobile or xbox. 

```
static Windows.Foundation.Metadata.Platform DetectPlatform()
		{
			bool isHardwareButtonsAPIPresent = ApiInformation.IsTypePresent("Windows.Phone.UI.Input.HardwareButtons");

			if (isHardwareButtonsAPIPresent)
				return Windows.Foundation.Metadata.Platform.WindowsPhone;
			return Windows.Foundation.Metadata.Platform.Windows;
		}
```

can we change this with this? According to below code can be extended with Xbox  as well.

```
static Windows.Foundation.Metadata.Platform DetectPlatform()
		{
			return AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Desktop" ? Windows.Foundation.Metadata.Platform.Windows: Windows.Foundation.Metadata.Platform.WindowsPhone; 
		}
```

**Comment by jfversluis** [comment]
This API seems to hold the information we are after https://docs.microsoft.com/en-us/uwp/api/Windows.System.Profile.AnalyticsVersionInfo

However, I can't find a list of all the possible options that are implemented at this moment.

**Comment by EmilAlipiev** [comment]
It looks like there is no official documentation but according to [this ](https://social.msdn.microsoft.com/Forums/en-US/c4f5221e-2e50-4ed9-847b-dfe619f0741b/what-are-the-possible-values-of-devicefamily-analyticsversioninfo-and-why-they-are-not?forum=wpdevelop)

"Windows.Mobile"
"Windows.Xbox"
"Windows.Holographic"
"Windows.Team"
"Windows.IoT"
"Windows.Desktop"

**Comment by StephaneDelcroix** [comment]
we have a TargetIdiom 'TV' that could be used for Xbox, but we're not setting it correctly
