### ISSUE TITLE
[F100] Character Spacing (LetterSpacing/Kerning) in Label and Button

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#4855]
## Summary
I often see in the design measured distance between the letters in the text.
I think that it is necessary to add such a parameter in the Label and Button controls.

## API Changes

I propose to add the CharacterSpacing Property to Label and Button.
```cs
    var button = new Button ();
    button.CharacterSpacing = 6.5; // new API

    var label = new Label ();
    label.CharacterSpacing = 6.5; // new API
```

**Comment by KSemenenko** [comment]
I already have a implementation for iOS, Android and UWP, I can create a pull request.
@pauldipietro @samhouts

**Comment by samhouts** [comment]
Great! This looks like a good addition to the set of shared properties in #1668. We'd love to see it. Thanks!

**Comment by KSemenenko** [comment]
@samhouts I created PR
