### ISSUE TITLE
[Question] What is the equivalent of RecyclerView in Xamarin.Forms?

### ISSUE THREAD

**Issue by sadqiang** [xamarin/Xamarin.Forms#4857]
I am a newbie in Xamarin.Forms. I am searching for an equivalent of RecyclerView (Android widget) in Xamarin.Forms. If there is no such equivalent, is there any other trick to get the same performance?

**Comment by FedorSulaev** [comment]
You can set CachingStrategy on a ListView to RecycleElement https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/performance
