### ISSUE TITLE
NU1605: Detected package downgrade: Xamarin.Forms from 3.3.0.912540 to 2.5.0.280555. Reference the package directly from the project to select a different version. App3.Android -> App3 -> Xamarin.Forms (>= 3.3.0.912540)

### ISSUE THREAD

**Issue by GanesanRengasamy** [xamarin/Xamarin.Forms#4858]
Hi All,

I have tried to downgrade the Xamarin.Forms NuGet package in the Xamarin NetStandard project. But I have faced the below issue.

NU1605: Detected package downgrade: Xamarin.Forms from 3.3.0.912540 to 2.5.0.280555. Reference the package directly from the project to select a different version.
App3.Android -> App3 -> Xamarin.Forms (>= 3.3.0.912540)

NU1605: Detected package downgrade: Xamarin.Forms from 2.5.1.527436 to 2.5.0.280555. Reference the package directly from the project to select a different version.

Could you please suggest me to resolve this problem?

**Comment by jamesmontemagno** [comment]
Maybe just uninstall the NuGet package first and then re-install the version you desire?

**Comment by AzyIsCool** [comment]
App3.Android and App3 are referencing different versions of Xamarin.Forms, make sure both projects are referencing the same version (by updating both of them to the newest version or by downgrading both to a version you want to use)

**Comment by GanesanRengasamy** [comment]
Hi @AzyIsCool,

I am sure both App3 and App3.Android projects refer the same version of Xamarin.Forms NuGet packages.

**Comment by StephaneDelcroix** [comment]
this is a nuget issue, there's nothing we can do from this side. if downgrade doesn't work, remove all package references, and add the new ones again
