### ISSUE TITLE
Specifying binding as markup extension parameter prevents binding from functioning

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#4860]
### Description

Value is not updated when supplying binding as markup extension parameter

### Steps to Reproduce

1. Use the default Xamarin.Forms project template
2. Paste MainPage.xaml.cs
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace XFBindingTest
{
    public class AExtension : IMarkupExtension<string>
    {
        public string B { get; set; }

        public string ProvideValue(IServiceProvider serviceProvider) => B;

        object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider) => B;
    }

    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }
        public string Z { get; } = "Hi!";
    }
}

```
3. Paste MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XFBindingTest"
             x:Class="XFBindingTest.MainPage">

    <StackLayout>
        <!-- Place new controls here -->
        <Label Text="{local:A {Binding Z}}"
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" />
    </StackLayout>

</ContentPage>
```
4. Build and run

### Expected Behavior
"Hi!" would appear at center of page

### Actual Behavior
Nothing appears

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: Idk
- IDE: Visual Studio 15.9.4
- Platform Target Frameworks:
  - UWP:  16299

### Screenshots
![image](https://user-images.githubusercontent.com/19922066/50447981-a961a980-0959-11e9-81aa-48bdf297871b.png)

```diff
-        <Label Text="{local:A {Binding Z}}"
+        <Label Text="{Binding Z}"
```
![image](https://user-images.githubusercontent.com/19922066/50447955-79b2a180-0959-11e9-81a0-6b30405ec011.png)

### Reproduction Link

Comment if needed

**Comment by StephaneDelcroix** [comment]
markup extensions do not have a BindingContext, so the Bindings can't be evaluated.And it makes sense as markup expressions are short-living helpers objects. I'd recommend to:
- not pass a Binding to a property of a markup expression,
- or have you property be of type BindingBase, and deal with the Context stuff on you your own (your markup extension probably will have to be of type BindingBase as well)

**Comment by Happypig375** [comment]
So how to pass a reference to a field as a parameter to a markup extension? I'm puzzled.
