### ISSUE TITLE
AbsoluteLayout proportional positioning

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#4862]
### Description
Proportional ain't proportional!

### Steps to Reproduce

1. MainPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XFBindingTest"
             x:Class="XFBindingTest.MainPage">

    <AbsoluteLayout BackgroundColor="LightYellow">
        <BoxView AbsoluteLayout.LayoutBounds="0, 0, 1, 1" AbsoluteLayout.LayoutFlags="All" BackgroundColor="LightSalmon"/>
        <BoxView AbsoluteLayout.LayoutBounds="0, 0, 0.25, 0.25" AbsoluteLayout.LayoutFlags="All" BackgroundColor="Teal"/>
        <BoxView AbsoluteLayout.LayoutBounds="0.75, 0.75, 0.25, 0.25" AbsoluteLayout.LayoutFlags="All" BackgroundColor="Lime"/>
    </AbsoluteLayout>

</ContentPage>
```
2. Build and run

### Expected Behavior
Top left quarter is teal colored, bottom right quarter is lime colored, the rest two quarters are light salmon colored

### Actual Behavior
Top left quarter and bottom right quarter positioned very awkwardly

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: Visual Studio 15.9.4
- Platform Target Frameworks:
  - UWP:  16299

### Screenshots
![image](https://user-images.githubusercontent.com/19922066/50448974-378c5e80-095f-11e9-9700-0deba74054e8.png)

### Reproduction Link
Comment if needed

**Comment by Happypig375** [comment]
Not only UWP, but iOS and Android as well.
iOS (Simulator, iPhone XS Max 12.1):
![image](https://user-images.githubusercontent.com/19922066/50593937-77aa8e80-0ed5-11e9-94ce-7354edc58ddf.png)
Android (Emulator, Android_Accelerated_Nougat):
![image](https://user-images.githubusercontent.com/19922066/50594230-a5440780-0ed6-11e9-9cb5-5d5ba54fa92e.png)

**Comment by PureWeen** [comment]
Yea I can see how it can be a little confusing. 
The X and Y for proportional isn't just the x and y position of the left and top edge

This explains goes into more detail about it
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/absolute-layout#proportional-layouts

This allows you to more easily left justify, right justify, and center things without having to take variable width into consideration
