### ISSUE TITLE
Multi line without text wrap in Label 

### ISSUE THREAD

**Issue by 632575987** [xamarin/Xamarin.Forms#4868]
### Help wanted: I want to display multi lines in a label control, without text wrapping, just scroll the content left to right when the screen can’t display the full line. I tried to set the linebreak mode or Max rows 
But it doesn’t work well,the text is still wrap to a new line when the text length is long

I test it on android 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
hey @632575987 I'm not seeing the same issue you are.. I tested with this code

And it works fine for me.
If you still have a question I would ask on Stackoverflow. You'll probably get an answer over there much quicker then here

```C#
MainPage = new NavigationPage(
                new ContentPage()
                {
                    Content =
                    new ScrollView()
                    {
                        HorizontalScrollBarVisibility = ScrollBarVisibility.Always,
                        Orientation = ScrollOrientation.Horizontal,
                        Content = new StackLayout()
                        {
                            Children =
                            {
                                new Label() {
                                    Text = "Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium Medium End Beginning",
                                    MaxLines = 1
                                }
                            }

                        }
                    }
                });
```
