### ISSUE TITLE
[UWP] Windows 10.1809 has style differences

### ISSUE THREAD

**Issue by deakjahn** [xamarin/Xamarin.Forms#4871]
### Description

Some style settings that worked quite all right on Windows 10.1803 seem to have problems on .1809.

Platform specific base styles like `ListItemTextStyle`and `ListItemDetailTextStyle` render in smaller text. Named font sizes like `Micro`, `Small` etc don't work at all, they all result in a normal sized text. 

The metrics of the navigation page toolbar icons have deteriorated.

### Steps to Reproduce

1. Create a simple app with items above
2. Run it on both 1803 and 1809 to see the difference

### Expected Behavior

Consistent display

### Basic Information

- Version with issue: any recent
  - UWP:  17763

### Screenshots

![commandbar](https://user-images.githubusercontent.com/2234271/50538299-8dceec80-0b6d-11e9-9dc5-5410d5daae69.png)
above: 1803, below: 1809

**Comment by PureWeen** [comment]
@deakjahn  can you attach a repro?

I tested on 1809 and for me the named font sizes are working fine

```xaml
new Label() { Text = "Medium", FontSize = Device.GetNamedSize (NamedSize.Medium, typeof(Label))},
new Label() { Text = "Small" , FontSize = Device.GetNamedSize (NamedSize.Small, typeof(Label))},
new Label() { Text = "Micro" , FontSize = Device.GetNamedSize (NamedSize.Micro, typeof(Label))}
```


![image](https://user-images.githubusercontent.com/5375137/50717157-9ed29e80-1042-11e9-9f76-8d46ca2edb0a.png)

**Comment by samhouts** [comment]
@deakjahn  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
