### ISSUE TITLE
Add property Button.ImageSize please

### ISSUE THREAD

**Issue by PetrVobornik** [xamarin/Xamarin.Forms#4873]
## Summary

Add property 

    public Size ImageSize { get; set; }

for Button class/control, please. Use it for setting of image Width and Height when Button is [rendered](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/ButtonRenderer.cs#L179) (in all platforms). You can also use nullable type "**Size?**" (or some special values as double.NaN for Width and Height) which means use current behavior, i.e. to set image size by source image width and height in pixels.

### Use case when it is necessary

In UWP subproject I have these icon variants:

- icon_cancel.scale-100.png (24x24)
- icon_cancel.scale-200.png (48x48)
- icon_cancel.scale-400.png (96x96)

On display where windows scale is 100% buttons are displayed fine (24x24), but on the second display with 225% zoom an images in buttons bigger (96x96) and it is terrible. When I set button height the picture is cropped. The same icons in toolbars has good size.

**Comment by charlesroddie** [comment]
The description of this issue isn't clear. Screenshots would help.

**Comment by PetrVobornik** [comment]
OK I'm including mix of some screenshots. The problem is that now I have no chance to set button image size, except to change pixel size of the picture in the file. But in higher resolution I want to use bigger picture for finer raster. 

![button-imagesize](https://user-images.githubusercontent.com/11021768/50558999-e7acef00-0cf2-11e9-977b-3a1c077976f3.png)

In Android project it works better, probably because of that image dimensions are correctly recalculated to the screen resolution. But there are no two (or more) displays with different scale factor.

**Comment by charlesroddie** [comment]
What if you set heightrequest and widthrequest?
This should be svg not png but I'm not sure if svg buttons is in the currently released Xamarin.Forms yet.

**Comment by mattleibow** [comment]
I have a PR that I am working on to support any `ImageSource` in all the places: #4915 This will also allow you to use the new `FontImageSource` to put gyphs into buttons or page icons. It does not address the specific issue on the cropping, but at least with the `FontImageSource` you will be able to specify `FontSize`.

**Comment by EmilAlipiev** [comment]
> I have a PR that I am working on to support any `ImageSource` in all the places: #4915 This will also allow you to use the new `FontImageSource` to put gyphs into buttons or page icons. It does not address the specific issue on the cropping, but at least with the `FontImageSource` you will be able to specify `FontSize`.

Does this work also with svg? I cannot make it work on UWP

**Comment by jfversluis** [comment]
I think some improvement already happened here for Forms and BIIIIIG improvements for .NET MAUI. Please check that out. If you still have suggestions for .NET MAUI, please open them on that repo. Thank you!
