### ISSUE TITLE
[UWP] XF.PageRenderer Resizes Wrong in UWP Parents

### ISSUE THREAD

**Issue by yang-er** [xamarin/Xamarin.Forms#4874]
### Description

This is a test for adding Xamarin.Forms controls or pages into UWP 

I had tried using some built-in renderers in my iOS/Android/UWP project's platform-aware codes, most works fine.

### Steps to Reproduce

1. Just run the sample I uploaded.
2. When App.xaml.cs Line 38 is typeof(MainPage), it is in **origin** UWP environment.
3. When App.xaml.cs Line 38 is typeof(MainPage2), it is in **Xamarin.Forms** UWP environment.

### Expected Behavior

The page renders well in the Pivot.

### Actual Behavior

The panel outside the real control's size becomes (0,0).

By the way, it seems that only one `ListViewItem` was added when in origin UWP environment.

### Basic Information

- Version with issue: 3.4.0
- Last known good version: N/A
- IDE: Visual Studio 2017.9.4
- Platform Target Frameworks: 
  - UWP: 17134
- Nuget Packages: 3.4.0

### Screenshots

First I'd like to say it is perfect with Xamarin.Forms UWP projects.

![formswindowspageallright](https://user-images.githubusercontent.com/10959348/50563539-a7805780-0d58-11e9-98e9-f96e38751907.png)

When the page seems blank, I found the `TextBlock`s for the datas in ViewTree Panel.

![textblockaddedtoviewtree](https://user-images.githubusercontent.com/10959348/50563537-a6e7c100-0d58-11e9-9095-c3197302b75d.png)

But its parent `Panel` becomes invisible, which gets a size of (0,0).

![textblockparentnotwellshown](https://user-images.githubusercontent.com/10959348/50563538-a6e7c100-0d58-11e9-8c67-c440034ece51.png)

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/2718574/App1.zip)

Happy new year!

**Comment by yang-er** [comment]
It may also be a new feature request if you agree...

It's just for fun!

**Comment by PureWeen** [comment]
@yang-er  I think what you are looking for is to use

```C#
PivotItem2.Content = new ListViewPage().CreateFrameworkElement();
```

To create the content. If you do that then it looks like it all sizes itself correctly
