### ISSUE TITLE
[UWP] ImageButton Padding applied inwards instead of outwards

### ISSUE THREAD

**Issue by scastria** [xamarin/Xamarin.Forms#4879]
### Description
A Button with an image of 50x50 is sized at 50x50.  When Padding is applied, that Padding is applied outwards keeping the image at 50x50 but growing the size of the Button to include the Padding.  This allows a developer to increase the hit area of a button to help with fat fingering.  However, on UWP, ImageButton applies the Padding inwards so that the ImageButton stays at 50x50 but the image shrinks inwards to include the Padding.  This makes it impossible for a developer to increase the hit area of an ImageButton without changing the size of the actual image file.

Attached is a sample program to demonstrate the issue.  iOS and Android seem to work fine.  UWP is the platform with the issue.  I have also attached 3 screenshots, one for each platform.

![iosimagebutton](https://user-images.githubusercontent.com/4534494/50575870-345ffb00-0dc3-11e9-9d7b-b6c78c4b429c.png)
![androidimagebutton](https://user-images.githubusercontent.com/4534494/50575871-37f38200-0dc3-11e9-8015-88f9fe757e8a.png)
![uwpimagebutton](https://user-images.githubusercontent.com/4534494/50575872-3b870900-0dc3-11e9-9aa6-b0019dfb6670.png)

### Sample Program
[TestImageButton.zip](https://github.com/xamarin/Xamarin.Forms/files/2719589/TestImageButton.zip)

**Comment by mrlacey** [comment]
I'm looking at this.
It appears to be an issue with applying the padding to the image, rather than the button it is contained within.
