### ISSUE TITLE
Text not shown as it should Xamarin.Forms.GTK

### ISSUE THREAD

**Issue by AzyIsCool** [xamarin/Xamarin.Forms#4880]
### Description
Text sometimes doesn't show as it should when using anything from Xamarin.Forms
Text shows as it should when using Dialog from GTK class

### Steps to Reproduce

1. Get a Label (doesn't matter if by code or XAML)
2. Give Label some text with parts like `
3. Parts of the text will not show as they should

### Expected Behavior
With what I'm using it for it should say ``We couldn't find Deltarune or Undertale in this folder, if you're using this for another game then as long there is a data.win file and the game was made with GameMaker then this program should work but there are no guarantees that it will.``

### Actual Behavior

Say's ``We couldn&apos;t find Deltarune or Undertale in this folder, if you&apos;re using this for another game then as long there is a data.win file and the game was made with GameMaker then this program should work but there are no guarantees that it will.``

### Basic Information

- Version with issue: 3.4.0.1008975
- Last known good version: N/A
- IDE: Windows: VS 2017, Linux: MonoDevelop 
- Platform Target Frameworks: 
  - Windows
  - Linux
  - macOS 
- Nuget Packages: Xamarin.Forms, Xamarin.Forms.Platforms.GTK
- Affected Devices: All OS's

### Screenshots

![capture2](https://user-images.githubusercontent.com/21204235/50575924-ff719980-0dfe-11e9-819d-a70fdc7d1fd0.PNG)

![capture](https://user-images.githubusercontent.com/21204235/50576044-54aeaa80-0e01-11e9-8ac4-60a05e8ad6a8.PNG)

### Reproduction Link

https://github.com/AzyIsCool/HATE

**Comment by Rfvgyhn** [comment]
Just wanted to add that it also happens with a `Button` and `Entry.Placeholder` but not `Entry.Text`.

**Comment by thenderson21** [comment]
It looks like the text is getting double encoded, once when span it set, and in the `GenerateMarkupText()`  method is being called in the label extension. I believe I have a fix for it, I will try submitting a pull; request shortly.

**Comment by ihvrooman** [comment]
I'm still having this issue on Xamarin Forms 5.0.0.2012.

![image](https://user-images.githubusercontent.com/61886068/108218647-e0c7dd00-7102-11eb-99d0-a3562b55ff3c.png)

**Comment by DaZhu** [comment]
same problem, so ... i  use Lable.FormattedText instead
