### ISSUE TITLE
Visual Studio 2017: F12 on XAML 'Clicked' callback doesn't always jump to definition

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#4881]
### Description

F12 on XAML 'Clicked' callback fails with `Cannot navigate to definition`.

### Steps to Reproduce

1. Select a Clicked callback in XAML. E.g. `Clicked="Foo_Clicked"`
2. Press F12
3. Most of the time, this will fail with `Cannot navigate to definition`. Sometimes it will succeed.

### Expected Behavior

Jump to function definition in code-behind

### Actual Behavior

`Cannot navigate to definition` dialog box.

### Basic Information

- Version with issue: Current VS 2017
- Last known good version: Unknown
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 28

**Comment by StephaneDelcroix** [comment]
//cc @mgoertz-msft

**Comment by mfeingol** [comment]
This is still an issue in Visual Studio 2019 RTM.

**Comment by samhouts** [comment]
@mfeingol If you are still experiencing this issue, please report it using the send feedback option within Visual Studio. Thanks!
