### ISSUE TITLE
 Bottom TabbedPage not working with Xamarin Live Player from Android

### ISSUE THREAD

**Issue by x0r00** [xamarin/Xamarin.Forms#4884]
IDE vs 2017 15.9
NetStandard.Library v2.0.3
XamarinForm 3.4.0.1008975
Windows 10

TabbedPage.Xaml looks like this:
`<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="https://xamarin.com/schemas/2014/forms"            
xmlns:x="https://schemas.microsoft.com/winfx/2009/xaml"            
x:Class="Spolujizda.MainTabbedPage"            
BarTextColor="Black"            
BarBackgroundColor="#f1f1f1"            
xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"            
android:TabbedPage.ToolbarPlacement="Bottom"            
android:TabbedPage.BarItemColor="#999999"            
android:TabbedPage.BarSelectedItemColor="Black">
</TabbedPage>`

When I build it in VS, it builds fine.
When I deploy it into Hyper-V Android Emulator, it builds and works fine.
However when I try to deploy it via Xamarin Live Player to my Google Pixel 2 I get this in output:

`Start Spolujizda.Android, Google Pixel 2 Player, .
Attempting connection to debug address: 192.168.88.11:37847.
Connected to: 192.168.88.11:37847.
Deploying C:\dev\csharp\spolujizda\Spolujizda\Spolujizda.Android\Spolujizda.Android.csproj...
Got device info: Google Pixel 2 Player (Android) @ 192.168.88.11:37847
Synchronizing files...
Building and running...
Built with 4 messages.
(1,1): error: Position 8:13. No property, bindable property, or event found for 'ToolbarPlacement', or mismatching type between value and property.
(1,1): error: Position 8:13. No property, bindable property, or event found for 'ToolbarPlacement', or mismatching type between value and property.
(1,1): error: Dependent project Spolujizda.csproj failed to build, using old version.
C:\dev\csharp\spolujizda\Spolujizda\Spolujizda.Android\MainActivity.cs(1,1): error: The type or namespace name 'App' could not be found (are you missing a using directive or an assembly reference?)
Failed to debug your app.`

**Comment by PureWeen** [comment]
LivePlayer is not supported by this team (and probably not supported anymore). closing.

**Comment by x0r00** [comment]
> LivePlayer is not supported by this team (and probably not supported anymore). closing.

Compiled apk not working to.
