### ISSUE TITLE
Gesture not firing for custom renderer on iOS

### ISSUE THREAD

**Issue by mfkl** [xamarin/Xamarin.Forms#4885]
### Description

Given a gesture recognizer on a `View` _with_ custom renderer, the gesture is not firing events on iOS.

This code

```
<ContentPage.Content>
        <AbsoluteLayout HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
            <vlc:VideoView x:Name="videoView" MediaPlayer="{Binding MediaPlayer}" AbsoluteLayout.LayoutBounds="0,0,1,1" AbsoluteLayout.LayoutFlags="All">
                <vlc:VideoView.GestureRecognizers>
                    <PanGestureRecognizer PanUpdated="PanGestureRecognizer_PanUpdated"/>
                </vlc:VideoView.GestureRecognizers>
            </vlc:VideoView>
            <Label Text="{Binding Message}" AbsoluteLayout.LayoutBounds=".5,1,1,.1" AbsoluteLayout.LayoutFlags="All" FontSize="20" LineBreakMode="WordWrap" TextColor="White" />
        </AbsoluteLayout>
    </ContentPage.Content>
```

Works fine on Android, while `PanGestureRecognizer_PanUpdated` is never raised on iOS.

Using an `Image` instead of the `VideoView` (custom renderer) works as expected on iOS.
I don't think a custom renderered View needs any particular setup to make gesture recognizers work. So I'm confused as to why it works on Android and not on iOS.

### Steps to Reproduce

1. git clone https://github.com/mfkl/libvlcsharp-samples/
2. git checkout gestures
3. run Gestures.iOS and touch the screen

### Expected Behavior

Pan events fire.

### Actual Behavior

Pan events don't fire.

### Basic Information

- Version with issue: 3.3.0967583
- IDE: VS4Mac 7.7.2
- Platform Target Framework:
  - iOS:  12.2.1.12

Thanks for looking into it.

**Comment by PureWeen** [comment]
@mfkl  my guess is that your renderer is some how intercepting the touch events on the ios view and they aren't being passed up the chain in such a way that our Recognizers can intercept

I'm attaching a really simple sample I made with iOS and a custom renderer where the pan gesture recognizer is working

[CustomRendererGesture.zip](https://github.com/xamarin/Xamarin.Forms/files/2728476/CustomRendererGesture.zip)

Let me know if this seems incorrect and I can reopen

**Comment by mfkl** [comment]
> I'm attaching a really simple sample I made with iOS and a custom renderer where the pan gesture recognizer is working

Yes, like I mentioned with the `Image`, it works for simple views. For some reason it doesn't with more complex ones. 

My custom view receives events from native `UIPanGestureRecognizer` in non-Forms projects or custom renderers. But I want users to be able to use the Xamarin.Forms crossplatform gestures on my custom view. Any idea what could intercept those events?

I tried https://github.com/xamarin/Xamarin.Forms/pull/2669 since this looks very much related but still could not make it work.

**Comment by mfkl** [comment]
What could possibly prevents XF gesture recognizers from working if the native iOS gesture recognizer do work? 

Pinging @samhouts as you probably have an idea about these stuff.

**Comment by PureWeen** [comment]
> I don't think a custom renderered View needs any particular setup to make gesture recognizers work. 

This is the comment you made that I was testing against. The point of the repro was just to show that an empty custom renderer works with Gesture Recognizers so there's nothing you need to do to make it work. It was more just to emphasize that the particular renderer is doing something to interfere with the EventTracker on iOS

> What could possibly prevents XF gesture recognizers from working if the native iOS gesture recognizer do work

Can you create a repro with less dependencies and more source code that we can debug into? Or build your own nuget from the source code (https://github.com/xamarin/Xamarin.Forms/blob/master/.create-nuget.bat) and use that in your project to debug. That would let you debug into https://github.com/xamarin/Xamarin.Forms/blob/a7f23cf490aef6c33db9552dab0600347d097998/Xamarin.Forms.Platform.iOS/EventTracker.cs to see where your particular custom renderer is getting in the way

**Comment by mfkl** [comment]
Thanks @PureWeen for the info.

Here's a better repro https://github.com/mfkl/custom-renderer-repro-4885

I did create my own nuget and debugged my code with it. Looks like `ShouldReceivedTouch` returns `false` here https://github.com/xamarin/Xamarin.Forms/blob/a7f23cf490aef6c33db9552dab0600347d097998/Xamarin.Forms.Platform.iOS/EventTracker.cs#L588 which maybe explains why nothing is firing? Not sure if that's the normal flow or what's the cause yet.

**Comment by kingces95** [comment]
@mfkl we don't generally debug custom renderers as, well, that's not technically a bug in our code... Once you jump to custom renderers you kinda void the warranty. That said, we do try to help you configure your env so you can debug the issue and it looks like you've done that. By bisecting the execution paths of the working renderer with your custom renderer you should be able to discover where things diverge. If you do discover you need to change our code to fix the issue then we'll happily take a PR. Gonna close this issue but feel free to keep posting updates and we'll help when we have a sec.

**Comment by mfkl** [comment]
> Once you jump to custom renderers you kinda void the warranty.

I get that.

> we do try to help you configure your env so you can debug the issue and it looks like you've done that. 

I did. But when attempting to remove the `#if __MOBILE__` compilation directives for easier debugging, the following builds wouldn't get properly resolved by MSBuild in my sample project (same issue with clean tree now):

```
warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'Xamarin.Forms.Platform.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): 
warning MSB3246: Resolved file has a bad image, no metadata, or is otherwise inaccessible. Could not load file or assembly 'Xamarin.Forms.Platform.iOS.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format.
```

Tried building with both VS and CLI, Debug/Release, AnyCPU/iPhone Simulator... no change. So I'm unable to debug this further for now.

> I'm attaching a really simple sample I made with iOS and a custom renderer where the pan gesture recognizer is working

This works because you're using a `UILabel` in `ViewRenderer<Triage.SomeCustomView, UILabel>`. If instead you use a custom UIView `ViewRenderer<Triage.SomeCustomView, MyView>` like so
```
public class MyView : UIView { }
````
Then the pan gesture won't work. 
Setting the XF View black and wide is also helpful in this case 
```
var view = new SomeCustomView() { BackgroundColor = Color.Black, HorizontalOptions = LayoutOptions.FillAndExpand, VerticalOptions = LayoutOptions.FillAndExpand };
```

Repro updated: https://github.com/mfkl/custom-renderer-repro-4885

So in the case of a custom `UIView`, do I need any additional setup? I don't see anything I'd be missing from looking at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view

**Comment by mfkl** [comment]
Looks like iOS `UIView`s need to implement `IVisualElementRenderer` to enable Xamarin.Forms gestures in XF projects, otherwise

```
bool ShouldReceiveTouch(UIGestureRecognizer recognizer, UITouch touch)
{
    if (touch.View is IVisualElementRenderer)
    {
        return true;
    }
    ...
}
```
returns `false` and no gesture is fired. This is not consistent with Xamarin.Android behavior.
