### ISSUE TITLE
Updating the android SDK path doesn't effect at same time.

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#4889]
When I install Visual Studio 2017, it's install SDK in C drive. I have a SDK in D drive. The Android SDK installed by Xamarin doesn't have 8.0

so it's showing * after it. I open tools > option and change the path. It doesn't take effect at the same time. If I close the properties and open it again, it's making changes.

### Expected Behavior
Should stop showing * after 8.0 because d Drive SDK have 8.0 installed. 
### Actual Behavior
still showing *, need to open properties page again by close and open project properties.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@anirugu  I'm pretty sure I'm following your issue but can you take a quick screen shot of what you mean here

> so it's showing * after it. 
Just so I understand what "it" is

**Comment by anirugu** [comment]
Please check this screenshot 

![image](https://user-images.githubusercontent.com/35772421/50692554-53c48580-105a-11e9-8044-96781b6e2458.png)

**Comment by PureWeen** [comment]
@anirugu  thank you for reporting this. I've moved this issue to an internal ticket with the VS team. 
In the future if there are IDE problems like this you can log it through the feedback features of VS
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017

That will create an issue that you can also track through the developer community site.
