### ISSUE TITLE
Style.BaseClass

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#4895]
## Summary
Allow base classes in styles in addition to base styles and base resource keys.

## API Changes

```diff
[Xamarin.Forms.ContentProperty("Setters")]
public sealed class Style
{
+    public string BaseClass { get; set; }
}
```

## Intended Use Case
Currently style inheritance requires resource keys. However, #4894 is present. Style inheritance excludes the use of style classes. This aims to change that.

**Comment by PureWeen** [comment]
@Happypig375 why are you thinking this?
> Style inheritance excludes the use of style classes. This aims to change that.

If you look at our Page Gallery you'll notice it's using Classes and it's using resource keys for inheritance
https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/PagesGallery/PagesGallery/App.xaml#L12-L20

**Comment by PureWeen** [comment]
Nm @Happypig375  I see what you're saying

I still don't think adding *BaseClass* is the right way to go though and just fixing #4894 would be best

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
