### ISSUE TITLE
Run time Exception while removing the my custom control Element from main.xaml in Xamarin MAC platform

### ISSUE THREAD

**Issue by vivek00712** [xamarin/Xamarin.Forms#4896]
I create my Custom control window and use that custom control into my main.xaml file while closing that custom control window null reference exception fired for perficular MAC Platform only for other plafrom IOS, Android, and UWP it is working fine.

It is showing error message of Message "Object reference not set to an instance of an object" But the other exception that i found in my stack-trace is System.NotImplementedException:   The method or operation is not implemented.

After the exception my application get crashed

**This issue is occured after updation of All Xamarin dll, MAC OS, XCode, MAC Visual Studio and other updates.**

### **Stack Trace of my Error**

StackTrace | at (wrapper   managed-to-native)   AppKit.NSApplication.NSApplicationMain(int,string[])   at   AppKit.NSApplication.Main (System.String[] args) [0x00040] in   /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.12/src/   Xamarin.Mac/AppKit/NSApplication.cs:100          at   MyApplication.MainClass.Main (System.String[] args)    [0x00017] in   /MyApplication/Main.cs:11
-- | --
HResult | -2147467261
Message | "Object   reference not set to an instance of an object"
Static members       -Non-public members           _COMPlusExceptionCode | -532462766
Non-public members |  
IsTransient | System.NotImplementedException:   The method or operation is not implemented.
_Hresult | -2147467261
_className | "System.NullReferenceException"
_message | "Object   reference not set to an instance of an object"

### **Details of my System**

**=== Visual Studio Community 2017 for Mac ===**

Version 7.7.2 (build 21)
Installation UUID: c06e658b-fea2-4764-b696-bc443c0dda7f
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

**=== Mono Framework MDK ===**

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

**=== NuGet ===**

Version: 4.8.0.5385

**=== .NET Core ===**

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

**=== Xamarin.Profiler ===**

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

**=== Apple Developer Tools ===**

Xcode 10.1 (14460.46)
Build 10B61

**=== Xamarin.Mac ===**

Version: 5.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

**=== Xamarin.Android ===**

Version: 9.1.4.2 (Visual Studio Community)
Android SDK: /Users/cygnet/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 26.0.3

Java SDK: /Users/cygnet/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

**=== Android Device Manager ===**

Version: 7.7.1.0
Hash: 06ceaea1

**=== Xamarin Inspector ===**

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

**=== Xamarin.iOS ===**

Version: 12.2.1.12 (Visual Studio Community)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

**=== Build Information ===**

Release ID: 707020021
Git revision: f1fea53df9eb0bb5890a9563c0d7ea7b03922144
Build date: 2018-12-14 18:37:35+00
Build branch: release-7.7
Xamarin extensions: 9c5cea335e6a9ce4ccfde31c4aa06c25a3576085

**=== Operating System ===**

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
