### ISSUE TITLE
Text Align in Entity

### ISSUE THREAD

**Issue by Ershad95** [xamarin/Xamarin.Forms#4907]
### Description
The text alignment with the placeholder is not correct ... please check.
when text alignment Set to left ،placeHolder Set to right,Or when text alignment Set to Right ،placeholder Set to Left
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
@Ershad95 Please attach a zipped reproduction or at least some screen shots. Thanks!

**Comment by samhouts** [comment]
@Ershad95 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
