### ISSUE TITLE
Picker allows multiple dialogs to be open

### ISSUE THREAD

**Issue by tlaivo** [xamarin/Xamarin.Forms#4909]
### Description

When a picker in Android is rapidly tapped twice, two dialogs are opened. Answering the first dialog works ok, but answering to second one doesn't seem to do anything.

Below is an old bug, which was reported and fixed for AppCompat. Now same bug seems to exist when AppCompat is not used.

https://bugzilla.xamarin.com/show_bug.cgi?id=41717

### Steps to Reproduce

Bug can be reproduced with an emulator in Visual Studio and with a real device.

1. Have an Android app with a picker
2. Rapidly tap picker twice
3. Two dialogs are opened

### Expected Behavior

Only on dialog is opened.

### Actual Behavior

Two dialogs are opened.

### Basic Information

- Version with issue: release-2.5.1-sr4, happens also with latest release-3.4.0-sr1.2
- Last known good version: -
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - iOS:  -
  - Android: 8.1
  - UWP:  -
- Android Support Library Version: 27.0.2, happens also with latest 28.0.0
- Nuget Packages: -
- Affected Devices: Found with with Honor 9, Android v8

### Screenshots

-

### Reproduction Link

-

**Comment by minaairsupport** [comment]
why this issue not included in last release , its very important issue to fix as soon as possible
