### ISSUE TITLE
 Xamarin Forms CollectionView Image source not binding to file path. (Xamarin Forms Pre-release v 4.0.0.8055-pre1)

### ISSUE THREAD

**Issue by netdevjamie** [xamarin/Xamarin.Forms#4913]
### Description
If I have a simple image in the XAML:

<Image
                                    Source="{Binding ImageUrl}"
                                    Grid.Column="0"
                                    HorizontalOptions="EndAndExpand"
                                    VerticalOptions="CenterAndExpand" />

the file path binds properly. However, if I nest the Image element inside of a CollectionView the image no longer binds.

<CollectionView
                x:Name="CV"
                ItemsSource="{Binding ThumbnailPhotos}"
                VerticalOptions="Center"
                HorizontalOptions="Center">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout
                        Orientation="Vertical"
                        Span="2" />
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Frame
                            BorderColor="LightGray"
                            CornerRadius="3"
                            HasShadow="False">
                            <Grid>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition
                                        Width="Auto" />
                                </Grid.ColumnDefinitions>
                                <Grid.RowDefinitions>
                                    <RowDefinition
                                        Height="Auto" />
                                </Grid.RowDefinitions>
                                <Image
                                    Source="{Binding ImageUrl}"
                                    Grid.Column="0"
                                    HorizontalOptions="EndAndExpand"
                                    VerticalOptions="CenterAndExpand" />
                            </Grid>
                        </Frame>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

For testing purposes the ObservableCollection in my ViewModel looks like so:

 ThumbnailPhotos = new ObservableCollection<Thumbnail>
        {
            new Thumbnail(){ ImageUrl = "/Users/<myUser>/Library/Developer/CoreSimulator/Devices/68BF4E8E-DF6D-4459-B6AD-DCEDB270916B/data/Containers/Data/Application/0C205001-6DFD-4846-9E6D-415F772FCB58/Documents/Defect Photos/IMG_20190102_165617/IMG_20190102_165617.jpg" } ,
            new Thumbnail(){ ImageUrl = "/Users/<myUser>/Library/Developer/CoreSimulator/Devices/68BF4E8E-DF6D-4459-B6AD-DCEDB270916B/data/Containers/Data/Application/0C205001-6DFD-4846-9E6D-415F772FCB58/Documents/Defect Photos/IMG_20190102_165617/IMG_20190102_165617.jpg" } ,
            new Thumbnail(){ ImageUrl = "/Users/<myUser>/Library/Developer/CoreSimulator/Devices/68BF4E8E-DF6D-4459-B6AD-DCEDB270916B/data/Containers/Data/Application/0C205001-6DFD-4846-9E6D-415F772FCB58/Documents/Defect Photos/IMG_20190102_165617/IMG_20190102_165617.jpg" } ,
            new Thumbnail(){ ImageUrl = "/Users/<myUser>/Library/Developer/CoreSimulator/Devices/68BF4E8E-DF6D-4459-B6AD-DCEDB270916B/data/Containers/Data/Application/0C205001-6DFD-4846-9E6D-415F772FCB58/Documents/Defect Photos/IMG_20190102_165617/IMG_20190102_165617.jpg" } ,

        };

### Steps to Reproduce

1. Bind Image to local file source in CollectionView
2. Run and see that image is not diplayed

### Expected Behavior
Image is displayed.
### Actual Behavior
Image is not displayed
### Basic Information

- Version with issue: v 4.0.0.8055-pre1

**Comment by kingces95** [comment]
@netdevjamie would you mind attaching a reproduction?
