### ISSUE TITLE
Example of project for Windows, iOS, Android and MacOS targets

### ISSUE THREAD

**Issue by lordalcol** [xamarin/Xamarin.Forms#4918]
Is there an example with projects that build an application for all targets, including Mac OS X?

I have found examples for Windows, iOS and Android, and instructions for bringing it to Mac OS, but not a complete example. Is there a reason for not providing it? Thanks

**Comment by amirvenus** [comment]
I wonder why default project template on VS for Mac does not include macOS target. 

But would be nice to have a single project template targeting iOS, Android, macOS, UWP, WPF, Tizen and GTK.

**Comment by charlesroddie** [comment]
Yes would be good to have a clean repo somewhere with a blank Xamarin.Forms solution with all these projects.

**Comment by jfversluis** [comment]
I know this is not what you asked, but adding the macOS target is now in the Docs: https://docs.microsoft.com/xamarin/xamarin-forms/platform/other/mac and will be much easier for .NET MAUI. This won't be something we're going to add to Xamarin.Forms anymore :)

Thanks!
