### ISSUE TITLE
[Feedback] Xamarin Forms - Style does not work with custom controls in XAML

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4921]
### Description

<p>Trying to set a Style for a custom control does not work.  The usual technique is to set a TargetType, and in this case I am setting it to &quot;custom:Nameof customcontrol&quot; with the xmlns to a location.  However setting the control to this style for a BindableProperty through the x:key name as a StaticResource is not allowed and an Exception is thrown.

Please advise.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/420186/xamarin-forms-style-does-not-work-with-custom-cont.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761154">original linked feedback ticket</a>.

### Source

[761742](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761742)

**Comment by StephaneDelcroix** [comment]
Could you please attach a small project reproducing this problem? thanks

**Comment by samhouts** [comment]
I asked again on the developer community ticket. We'll give it another round before we close this for no response.

**Comment by WinBase** [comment]
I am having the same problem and tried the solution here but no luck

https://forums.xamarin.com/discussion/112670/style-on-custom-control-property-not-supported

**Comment by samhouts** [comment]
@WinBase Can you provide a sample project? Thanks!

**Comment by WinBase** [comment]
Hi Samantha

 

Thanks for the offer of help. I will be interested in hearing your findings

 

For me to send my project would make the email too big to send as I have lots of stuff added as links and its going to take me too long to dissasemble then re-assemble after so you get a fully compilable project, but ive attached the relevant files so  you can just cut and paste into your own test project.. its quite a simple example

 

Im a newbie at xamarin & C# (2 weeks only lol) but have 40 years IT programming experience including  12 of VB.NET, so some of the code may be a tad naïve and not be as perfect as it should as I’m still learning and plagiarising a lot of code ATM, so sorry if ive done anything obviously wrong, but ive spend hours trying to fix this issue without success and will appreciate your help. My project compiles and runs ok without grumbling but it’s just ignoring the new properties I added to my custom control: (IsNumeric, MaxLength, MinValue & MaxValue) when I use a style, and it doesn’t do this if I use the more verbose way indicated.

 

CustomEntry.cs is my modified Data entry class stored in a MyLibrary project, ATM I use it for ensuring data is valid for hrs, min and seconds – add it as a reference, I wont dump the text here

App.xaml contains my style that doesn’t work called CustomEntryHMSStyle

TimerPage.xaml is where I enter the values and the style fails

 

PS while im on, there’s also some sort of bug in the UWP version of the entry box when you make the width less than 64 – any ideas? If I only want to enter 2 characters I only want half that width, it looks sill making a huge wide box for a small number

 

Regards

 

Bob

 

Heres the snippets

 

App.xaml

 

<?xml version="1.0" encoding="utf-8" ?>

<Application xmlns="http://xamarin.com/schemas/2014/forms"

             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"

             xmlns:PluginLibrary="clr-namespace:MyPlugin.Library;assembly=MyPlugin.Library"

             x:Class="MyApp.App">

 

            

 

            <Style x:Key="CustomEntryHMSStyle" TargetType="PluginLibrary:CustomEntry">

                <Setter Property="WidthRequest" Value="30" />

                <Setter Property="Keyboard" Value="Numeric" />

                <Setter Property="IsNumeric" Value="True" />

                <Setter Property="MaxLength" Value="2" />

                <Setter Property="MinValue" Value="0" />

                <Setter Property="MaxValue" Value="59" />

                

            </Style>

 

Timer Page.xaml

 

<?xml version="1.0" encoding="utf-8" ?>

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"

             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"

             x:Class="MyApp.Views.TimerPage"

             xmlns:vm="clr-namespace:MyApp.ViewModels"

             xmlns:PluginLibrary="clr-namespace:MyPlugin.Library;assembly=MyPlugin.Library"

             Title="{Binding Title}">

    

 

            

 

            

 

             <StackLayout Grid.Row="0" Grid.Column="1" Orientation="Horizontal" VerticalOptions="Center" HorizontalOptions="Start" >

               <PluginLibrary:CustomEntry x:Name="HoursEntry" Style="{StaticResource CustomEntryHMSStyle}" Unfocused="Settings_Changed" MaxValue="23" />

               <Label Text=":" VerticalOptions="Center" Font="Bold"/>

               <PluginLibrary:CustomEntry x:Name="MinsEntry" Style="{StaticResource CustomEntryHMSStyle}" Unfocused="Settings_Changed" />

               <Label Text=":" VerticalOptions="CenterAndExpand" Font="Bold"/>

               <PluginLibrary:CustomEntry x:Name="SecsEntry" Style="{StaticResource CustomEntryHMSStyle}" Unfocused="Settings_Changed" />

            </StackLayout>

**Comment by samhouts** [comment]
@WinBase I tried to make a sample project based on what you provided here. It seems to work for me! If I enter 60 in any of the text boxes, it hits my custom exception and blows up...so it's respecting the MaxValue!

Can you take a look and see what you can do to make it show the behavior you're experiencing?

Thanks!

[Issue4921.zip](https://github.com/xamarin/Xamarin.Forms/files/3049452/Issue4921.zip)

**Comment by WinBase** [comment]
Hi Samantha

 

I will try build a complete sample project from scratch time permitting to prove the problem to you, but I’m a little snowed under ATM with fee paying work lol

 

Thanks Anyway

 

Bob

**Comment by samhouts** [comment]
Understood! We appreciate the effort. Thanks!

**Comment by samhouts** [comment]
@WinBase  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by luissete** [comment]
I had the same problem but fix it like this:
https://visualstudiomagazine.com/Articles/2017/10/01/Add-Custom-Controls.aspx?Page=2

public static readonly BindableProperty StartColorProperty = BindableProperty.CreateAttached("StartColor",typeof(Color), typeof(GradientColorStack), Color.Default);

public static readonly BindableProperty EndColorProperty = BindableProperty.CreateAttached("EndColor",typeof(Color), typeof(GradientColorStack), Color.Default);

public static readonly BindableProperty FrameRateProperty = BindableProperty.CreateAttached("FrameRate", typeof(int), typeof(GradientColorStack), 0);

and the solution was to change this:
public Color StartColor { get;set; }
 public Color EndColor { get; set; }
 public int FrameRate { get; set; }

for:

 public Color StartColor
        {
            get => (Color)base.GetValue(StartColorProperty);
            set => base.SetValue(StartColorProperty, value);
        }

        public Color EndColor
        {
            get => (Color)base.GetValue(EndColorProperty);
            set => base.SetValue(EndColorProperty, value);
        }

        public int FrameRate
        {
            get => (int)base.GetValue(FrameRateProperty);
            set => base.SetValue(FrameRateProperty, value);
        }
If you read the article you will see that you must binding directly to existing controls with Properties 
now i can write in AXML:
 <Style x:Key="GradientLinearColor"  TargetType="manageControlMobile:GradientColorStack">
                <Setter Property="StartColor"  Value="Red"/>
                <Setter Property="EndColor" Value="BLue"/>
                <Setter Property="FrameRate" Value="20" /> 
            </Style>
            

and other AXML:

<manageControlMobile:GradientColorStack x:Name="ColorStack" StartColor="Red" EndColor="Aqua"  FrameRate="25">
                    <Grid HorizontalOptions="FillAndExpand"
                VerticalOptions="FillAndExpand">

or 

<manageControlMobile:GradientColorStack x:Name="ColorStack" Style="{StaticResource GradientLinearColor}">
                    <Grid HorizontalOptions="FillAndExpand"

This sh... has taken me a whole day ...

**Comment by SagarPanwala** [comment]
@samhouts : This bug is not fixed properly. See the attached sample repo.
Style does not work with custom controls when created xaml for style resource.
[Issue4921.zip](https://github.com/xamarin/Xamarin.Forms/files/3614052/Issue4921.zip)

**Comment by StephaneDelcroix** [comment]
@SagarPanwala Thanks for the repro project.

I got your sample to work (compile, deploy, and successfully throw if the minutes field is more than 59) by changing

```xaml
    xmlns:Custom="clr-namespace:Issue4921.MyControl">
```

to

```xaml
    xmlns:Custom="clr-namespace:Issue4921.MyControl;assembly=Issue4921">
```

this only happens in case like yours, when the style file is pure xaml (with no code-behind). As we have no idea if your issue is the same as the original one (we were unable to reproduce or get a valid repro), I'm going to open a new one: #7531
