### ISSUE TITLE
[Feedback] Xamarin OnPlatform / Corner Radius issue

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4922]
### Description

<p>So in my App.xaml I have a bunch of resource values set in toder to make things look the same on android and ios

I have buttons and frames that are using a corner radius value, frames use float, buttons use int (problem 1 - all corner radius on all visual elements should use the same value type - I think a box view used a class Called CornerRadius - that's 3 different types that all do the same thing)

Since each platform rounds the corners differntly I need different values per platform to make them always look almost the same. 

&lt;OnPlatform x:Key=&quot;CornerRadiusValue_Buttons&quot; x:TypeArguments=&quot;x:Int32&quot; Android=&quot;40&quot; iOS=&quot;20&quot;/&gt;

I have this for button styles to reference so that i can easily change the values if I need to across all buttons.

but frames use float, PROBLEM 2 there is no x:TypeArguments for float, and double cannot be assigned to the frame. if I use 

&lt;OnPlatform x:Key=&quot;CornerRadiusValue_Frames&quot; x:TypeArguments=&quot;x:Double&quot; Android=&quot;40.0&quot; iOS=&quot;20.0&quot;/&gt;

and assign the corner radius value, it ignores the values.

I have currently set my frame like this
&lt;Setter Property=&quot;CornerRadius&quot;&gt;
                    &lt;Setter.Value&gt;
                        &lt;OnPlatform Android=&quot;40&quot; iOS=&quot;20&quot; /&gt;
                    &lt;/Setter.Value&gt;
                &lt;/Setter&gt;

which works but if I have multiple frame styles I will have to add this extra onplatform junk instead of just setting the value to my onplatform value.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/419913/xamarin-onplatform-corner-radius-issue.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/760852">original linked feedback ticket</a>.

### Source

[761741](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761741)

**Comment by StephaneDelcroix** [comment]
We're aware of the multiple API to achieve the same end result. We're trying to unify everything so it uses `CornerRadius` struct. We have enhancement tickets open for that.

As for the
>PROBLEM 2 there is no x:TypeArguments for float

the CLR Type corresponding to C# `float` is `Single`, so `x:Single` should work just fine.
