### ISSUE TITLE
[Feedback] Xamarin Forms Entry Focused event problem

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#4923]
### Description

<p>Hello, 

I have found out that the event &quot;Focused&quot; on the Entry control of Xamarin.Forms is being fired every time the cursor is blinking! 
This should not work like this I suppose. 
Let's see this code: 
 MyEntry.Focused += (object sender, FocusEventArgs e) =&gt;{};
This will be fired on every cursor blink...</p>
<a href="https://developercommunity.visualstudio.com/content/problem/419680/xamarin-forms-entry-focused-event-problem.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/760693">original linked feedback ticket</a>.

### Source

[761739](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/761739)

**Comment by hartez** [comment]
Can't seem to reproduce this - here's my attempt, but the event only seems to fire once. Am I missing something?

[_4923 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2738128/_4923.Repro.zip)

**Comment by adammeaney** [comment]
We diagnosed this on the forums a while back.

Guy had a DisplayAlert in his focused event. So once he closed the alert, it refocused the entry and popped up the alert again.

Told him that was his fault for strange coding, don't do that.
