### ISSUE TITLE
Add GridLengths

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#4925]
There are Star GridLengths and absolute GridLengths. `GridLength a` creates `a` units of absolute GridLengths. `GridLength (s, GridUnitType.Star)` creates `s` units of Star GridLengths.

GridLengths should be addable because:

- GridLengths are naturally a vector space.
- This allows construction of GridLengths combining absolute and Star units.

The Definition of GridLength should be:

```fsharp
type GridLength(absolute:float,stars:float) =
    member t.A = absolute
    member t.S = stars
    static member (+) (u:GridLength, v:GridLength) = GridLength(u.A+v.A,u.S+v.S)
    static member (*) (t:float, u:GridLength) = GridLength(t*u.A,t*u.S)
    static member (~-) (u:GridLength) = GridLength(-u.A,-u.S)
```
Measurement is then:
```fsharp
let measure(spaceAvailable:float, gridLengths:GridLength[]): float[] =
    let total = Array.sum gridLengths
    let starMeasure = (spaceAvailable - total.A) / total.S
    gridLengths |> Array.map (fun gl -> gl.A + gl.S * starMeasure)
```

GridLengths combining both dimensions and GridLengths where one dimension is negative are useful for balance. Examples:

![image](https://user-images.githubusercontent.com/19760720/50854106-10c92180-137c-11e9-9d08-88673bad1d7a.png)

This change would also simplify the current GridLength code.

**Comment by StephaneDelcroix** [comment]
feel fine to provide an implementation

**Comment by charlesroddie** [comment]
I won't have time to implement this in the next 3 months. So I will close now and reopen when I have time to work on it.
