### ISSUE TITLE
[Enhancement] NavigationRequested event with consistent behavior

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#4926]
## Summary

The existing Requested events in NavigationPage.cs all have different behavior
* Some functions update the internal Xamarin.Forms properties *before* the event is invoked, making it impossible to intercept and/or cancel the navigation
* Some function's don't await the assigned NavigationRequestedEventArgs.Task
* Some functions use the boolean result of NavigationRequestedEventArgs.Task to cancel the request

| Event | Invoked By | Before Navigation | Awaits | Uses Result |
| ----- | ---------- | ----------------- | ------ | ----------- |
| InsertPageBeforeRequested | InsertPageBefore() | Yes | **No** | **No** |
| PopRequested | RemoveAsyncInner() | Yes | Yes | Yes |
| PopToRootRequested | PopToRootAsyncInner() | **No** | Yes | **No** |
| PushRequested | PushAsyncInner() | **No** | Yes | **No** |
| RemovePageRequested | RemovePage() | Yes | **No** | **No** |

## API Changes

Add a single NavigationRequested event that's invoked, and who's Task is awaited, *before* any Xamarin.Forms or platform-specific updates take place.  Use the result of the awaited task to determine whether the navigation is allowed to continue.

## Intended Use Case

At the moment, if you want to intercept and/or cancel navigation, you must add that logic everywhere in your application before any of the 12 different navigation methods are called.

A single NavigationRequested event that's implemented consistently and re-uses the existing and already appropriately named NavigationRequestedEventArgs would make it possible to inject the necessary logic from a single location.

**Comment by danielmeza** [comment]
Now this is shipped with the 3.5 version but in the iOS NavigationRenderer the fast property is set to true, so it not await for the Task and there fore the logic is broke.
The fast property is set to true to avoid issues in this versión or is an error?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
