### ISSUE TITLE
Grid size incorrect when using with Image

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#4933]
## Grid size incorrect when using with Image

When Grid.VerticalOption is not fill to parent, and Grid has an Image view, Grid.Height is incorrect. 

Grid should use scaled image size as row height, but it use original image height.

for example like this
```
<Grid HorizontalOptions="FillAndExpand" VerticalOptions="Center" BackgroundColor="Maroon" RowSpacing="0" \>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <Image Source="logo.jpg" Grid.Row="0" />
    <Label Grid.Row="1" Text="test message" BackgroundColor="Blue" />
</Grid\>
```
* * *
There are reproduction steps and screenshots in Bugzilla. I am not the original author of the bug but would also like to see this fixed and don't see this bug in GitHub. I am on Xamarin.Forms 3.4.0 and it is still an issue.
 
Submitted by a community member on 2017-04-17 16:35 UTC on Bugzilla and has a Confirmed Status. 

_Reference: <https://bugzilla.xamarin.com/show_bug.cgi?id=55294>_

**Comment by blaylock95** [comment]
I have reproduced it and I confirm this is still the case. I will try to fix this. I'm new here on GitHub and I don't know what exactly is the workflow? Will someone change it's status to In progress?

**Comment by blaylock95** [comment]
for clarity: spruceDevelopment is my main account. I shouldn't use this one but accidentaly I did :P
