### ISSUE TITLE
Gravity property in TextView is not working when TextView is added and measured in custom FrameLayout in Xamarin Android

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [xamarin/Xamarin.Forms#4934]
### Description

My requirement is to set the text at the end/right in the TextView which is added and measured in Custom frame layout, when i set Gravity as Centre its not working, other Gravity options also not working. Gravity property is working when TextView is not manually measured in custom frame layout. Kindly find the sample and code snippet below,

**Code snippet:** 

 ```
public class CustomLayout : FrameLayout
{
    public CustomLayout(Context context) : base(context)
    {
    }

    protected override void OnLayout(bool changed, int left, int top, int right, int bottom)
    {
        this.GetChildAt(0).Layout(left, 20, right / 2, 200);
    }

    protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
    {
        base.OnMeasure(widthMeasureSpec, heightMeasureSpec);

        var width = MeasureSpec.GetSize(widthMeasureSpec);
        var height = MeasureSpec.GetSize(heightMeasureSpec);

        this.GetChildAt(0).Measure(width / 2, 200);
    }
}

protected override void OnCreate(Bundle savedInstanceState)
{
    base.OnCreate(savedInstanceState);

    var label = new TextView(this);
    label.Text = "Label";
    label.SetBackgroundColor(Color.Gray);
    label.Gravity = GravityFlags.Center;

    var customLayout = new CustomLayout(this);
    customLayout.AddView(label);

    SetContentView(customLayout);
}
```

**Sample:**
[Sample_Android.zip](https://github.com/xamarin/Xamarin.Forms/files/2741358/Sample_Android.zip)

### Screenshots
![textview](https://user-images.githubusercontent.com/39787321/50907316-10e52200-144d-11e9-9624-2531331b2cf6.png)

**Note:**
I have also checked in Latest Xamarin version (v3.4)

**Comment by blaylock95** [comment]
My first post here
I guess this issue has nothing to do with Xamarin.Forms. I think you should post it at Xamarin.Android project [xamarin/xamarin-android](https://github.com/xamarin/xamarin-android)

**Comment by samhouts** [comment]
This issue was moved to xamarin/xamarin-android#2602
