### ISSUE TITLE
[iOS] ImageButton is half transparent when pressed

### ISSUE THREAD

**Issue by KarolStosikPowel** [xamarin/Xamarin.Forms#4947]
### Description
On iOS, when ImageButton is in pressed state it's translucent. It should behave like on other platforms, and have a solid color.

My workaround (and probably fix):
Set UIButtonType to Custom
Set AdjustsImageWhenHighlighted to false

Code:
```
using Gemini.Changes.iOS.Renderers;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(ImageButton), typeof(CustomImageButtonRenderer))]
namespace Gemini.Changes.iOS.Renderers
{
    public class CustomImageButtonRenderer : ImageButtonRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<ImageButton> e)
        {
            if (Control == null)
            {
                SetNativeControl(UIButton.FromType(UIButtonType.Custom));
                Control.AdjustsImageWhenHighlighted = false;
            }

            base.OnElementChanged(e);
        }
    }
}
```

### Steps to Reproduce

1. Use any ImageButton (for  example from https://github.com/davidortinau/TheLittleThingsPlayground)
2. Press ImageButton on iOS
3. 

### Expected Behavior
Button should be smaller, but color should stay the same

### Actual Behavior
Button is half transparent

### Basic Information
- Version with issue: 3.4.0.1009999, 3.4.0.1009999
- Last known good version:
- IDE: Visual Studio 15.9.4
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices: iPhone

**Comment by kingces95** [comment]
Thanks! https://github.com/xamarin/Xamarin.Forms/pull/4953

**Comment by samhouts** [comment]
As of right now, we'll leave this behavior as is until we get more feedback that this is desired. I believe we would want to add this as a platform specific, as mentioned in https://github.com/xamarin/Xamarin.Forms/pull/4953#pullrequestreview-195781250, so you can easily switch between behaviors. Thanks!
