### ISSUE TITLE
[Material] Contained Button Spec

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4951]
# Material Contained Button Spec

https://material.io/design/components/buttons.html#contained-button

![image](https://user-images.githubusercontent.com/5375137/51337248-d1699780-1a43-11e9-831b-32ac18a30fe6.png)  ![image](https://user-images.githubusercontent.com/5375137/51337489-80a66e80-1a44-11e9-8eea-a97aecfa90f5.png)

This spec describes the expectation for the Contained Material Button and will be expected to meat the following goal for iOS and Android as outlined in the original Visual Spec #4435 

The expectation for this initial implementation will be to enable the developer to hit the base material spec as close as possible on iOS and Android. We will attempt to provide *Visually identical rendering* with the existing APIs but there are levels of customization where this may not be possible or where it may not come until a later date. 

### Expectations 

- **Visually Identical**
   The rendering should be such that the naked eye can’t tell the difference at a glance. _Not to be confused with “pixel perfect”_
- **Padding/Margins**
  The padding and margins should be the same.
- **Font**  
   The size is supposed to be the same and might just be the **minute font face differences**.
- **Border**  
  The border property of both platforms is **not really supported**, and has visual artifacts:  
  Android: <img src="https://user-images.githubusercontent.com/1096616/51282342-86bd3080-19ed-11e9-9a4f-abfe6c78f359.png" width="40" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; iOS: <img src="https://user-images.githubusercontent.com/1096616/51282345-86bd3080-19ed-11e9-8043-c795728115c3.png" width="30" />
  This issue is tracked at https://github.com/material-components/material-components-android/issues/129. It has been fixed in AndroidX, but not in the support libraries.  
  _As as result of this, #4967 **restricts the border to exactly 1dip**. This hides the problem for most cases, although if you look really closely at Android, the border still sticks out._
- **Text Wrapping**  
  Android does this fine and is a centered text [next to the image]. iOS buttons (both Material and default) do NOT support multilines and cannot wrap. There are hacks to change the mode (and it does wrap), but the button can't understand this and will have to be manually sized. This is compounded that it also does not support image positions other than left. The hacks (and I call it hacks as the layout is still technically incorrect) we do make it even harder to properly measure the text bounds.
- **Command**
  No change
- **Corner Radius**
  Should render identically on both platforms
- **ContentLayout**
  In the majority of cases Icon positioning will render correctly for (right, left,top, and bottom) if the text is keeping to Material expectations. Refer to the comments above about text once user starts to stray

# API
```XAML
<Button Visual="Material" />
```

```C#
new Button() { Visual = VisualMarker.Material }
```

# Difficulty : high

#### Screenshots

| Android | iOS |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/1096616/51290358-48833980-1a0c-11e9-97d5-5a4447edcd38.png" width="288px" /> | <img src="https://user-images.githubusercontent.com/1096616/51290496-a879e000-1a0c-11e9-8e2e-9686e5b5a777.png" width="262px" /> |
| <img src="https://user-images.githubusercontent.com/1096616/51290359-491bd000-1a0c-11e9-87ff-1fb3aa33d538.png" width="288px" /> | <img src="https://user-images.githubusercontent.com/1096616/51290497-a879e000-1a0c-11e9-8b3f-a8956415ef8a.png" width="262px" /> |
| <img src="https://user-images.githubusercontent.com/1096616/51290360-491bd000-1a0c-11e9-867b-fc034c508560.png" width="288px" /> | <img src="https://user-images.githubusercontent.com/1096616/51290499-a9127680-1a0c-11e9-82a5-55a8a2635e1f.png" width="262px" /> |

**Comment by charlesroddie** [comment]
> iOS and Android
+UWP
