### ISSUE TITLE
[iOS,Android] TabStop skips Stepper Control

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#4956]
### Description
When tabbing over a set of controls the Stepper control will get skipped on iOS and Android. This works fine on UWP

I tested this against the following PR https://github.com/xamarin/Xamarin.Forms/pull/3989

And when I tested there being able to tab with the keyboard stopped working all together

### Steps to Reproduce

1.  Run Issue3872
2. Tab Over controls
3.  You're able to tab to each one except it will skip the stepper

### Expected Behavior
the stepper should get selected

### Actual Behavior
the stepper is being skipped over

### Basic Information

- Version with issue: 3.5.0
- Last known good version: Most likely never worked
- IDE:
- Platform Target Frameworks: 
  - iOS:  12
  - Android: 9.0
- Android Support Library Version: 28

**Comment by paymicro** [comment]
iOS also skips tabbing on `Button`, `ProgressBar`, `Slider`, and `Switch` controls.

**Comment by rmarinho** [comment]
partially fixed by #5000
