### ISSUE TITLE
[Android, iOS] TimePicker does not remeasure its size when picking a new time  that is wider than the previously selected value

### ISSUE THREAD

**Issue by APopatanasov** [xamarin/Xamarin.Forms#4961]
### Description
When changing the Time of the TimePicker the control is not remeasured and its size remains the initially calculated one.
### Steps to Reproduce

1. Open the attached project.
2. Set the time to 12:50 AM
3. The Picker remains the same size.

### Expected Behavior
The  control should be remeasured and new size to applied in order to be able to see the whole time.
### Actual Behavior
The time could no be seen completely.
### Basic Information

- Version with issue: 3.4
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: 8.1 
### Screenshots
![android_timepicker_issue](https://user-images.githubusercontent.com/9336157/51031023-f2456f00-15a3-11e9-8087-b697f7d6060a.gif)

### Reproduction Link
[TimePicker_Measure.zip](https://github.com/xamarin/Xamarin.Forms/files/2749404/TimePicker_Measure.zip)

**Comment by kingces95** [comment]
Reproduces as described.

**Comment by samhouts** [comment]
closed by #4999
