### ISSUE TITLE
[Enhancement] remove sealed from Command<T>

### ISSUE THREAD

**Issue by johannes-schmitt** [xamarin/Xamarin.Forms#4965]
### Description
Currently Xamarin.Forms.Command<T> is sealed. So I cannot inherit from it to add my own functionality. Contrary to that, Xamarin.Forms is not sealed.

I don't see a reason why it should be sealed.

### Expected Behavior
this compiles fine:
```
public class MyCommand<T> : Xamarin.Forms.Command<T>
{
   // ...customization here
}
```

**Comment by StephaneDelcroix** [comment]
no reason not to, but you already can inherit from Command, or implement ICommand
