### ISSUE TITLE
Shell -  WebView Drag not working

### ISSUE THREAD

**Issue by jeontaejin** [xamarin/Xamarin.Forms#4966]
<WebView Source="http://map.google.com" />

Map drag not working

**Comment by kingces95** [comment]
Please provide a zipped reproduction. Please also expand on the reproduction steps and the actual and expected behavior.

**Comment by samhouts** [comment]
@jeontaejin  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
