### ISSUE TITLE
Editor with AutoSize should have an initial Height

### ISSUE THREAD

**Issue by stevehurcombe** [xamarin/Xamarin.Forms#4972]
## Summary
The Editor now has an AutoSize property. This would typically be used in a scenario where the user is expected to enter more than one line of text, . 

## Intended Use Case
When the AutoSize property is enabled it is desirable to set the initial size of the edit control to imply to the user that they can enter more than one line of text. 

## API Changes
There should either be a minimum height property, or the existing Height property could be considered to be the minimum.

**Comment by Aculeo** [comment]
I also found it rather confusing that setting `HeightRequest` disables auto sizing entirely. And much to my surprise `MinimumHeightRequest` didn't do what I expected either. I hope this will get addressed.

**Comment by marcelom56** [comment]
I agree with @Aculeo, I think the properties MinimumHeightRequest and AutoSize should work together.

**Comment by uday-lucky** [comment]
I think this feature should be available.. a minimum height request is able to set for the control and editor should resize as text inside increases.. otherwise, i dont see much difference between an editor and an entry

**Comment by anhhtbk** [comment]
> What about MaximumHeight? Maybe I want to show max. 5 lines and let the user scroll if there is too much text so that the Editor does not break the layout.

Like @acuntex, I am doing a chat app, and I need a limited height editor (multiple lines).

**Comment by xamiell** [comment]
Totally agree with @acuntex and @anhhtbk 
Is a waste of time make a custom renderer just for apply a MaximumHeight calculation to an Editor.

**Comment by leoholcman** [comment]
Create your own Editor with a MaxHeight property and add these following lines:

public class LEditor : Editor
    {
        public double MaxHeight { get; set; }

        protected override SizeRequest OnMeasure(double widthConstraint, double heightConstraint)
        {
            var sizeRequest = base.OnMeasure(widthConstraint, heightConstraint);

            var newHeight = sizeRequest.Request.Height;
            if (newHeight > MaxHeight)
                newHeight = MaxHeight;

            return new SizeRequest(new Size(sizeRequest.Request.Width, newHeight));
        }
    }

**Comment by maximusfatigue** [comment]
@leoholcman  thanks for sharing this, I still learning elements of xamarin, how do I implement this? in the page code behind? plus how to I call it in xaml?

**Comment by maximusfatigue** [comment]
Sorted,  create a .cs file,  import the custom .cs at the top of xaml.

**Comment by jfversluis** [comment]
Hey everyone! Sorry we couldn't make this happen for Xamarin.Forms. We have a couple of related issues that are now on the list for .NET MAUI. Hope we can add this there out of the box and eliminate your need for those custom controls/renderers :)

Thanks!
