### ISSUE TITLE
UWP Windows 10.1809 RichTextBlock ContextFlyout failed

### ISSUE THREAD

**Issue by tekmun** [xamarin/Xamarin.Forms#4975]
RichTextBlock ContextFlyout no longer shown

### Steps to Reproduce

1. Run BibleMoments app from Microsoft Store
2. On Windows 10.1803, double tap on any verse to select some text.  Then, long press displays Context Flyout.
3. On Windows 10.1809, double tap on any verse to select some text.  Then, long press **does not** display Context Flyout.

**Comment by rmarinho** [comment]
Can you please provide a small repo case using Xamarin.Forms , thanks

**Comment by tekmun** [comment]
Hi,

I have asked this question in the following stackoverflow.

https://stackoverflow.com/questions/52158362/uwp-disable-default-context-menu-but-show-text-selection-grippers

--------------------------------------

Cheong Tek Mun

Learnaholic Pte. Ltd.

(65) 92725050

www.learnaholic.com

* Out of learning, service overflows *

This email including any attachment may contain legally privileged or
confidential information. Any unauthorised use, retention, reproduction or
disclosure is prohibited and may attract civil and criminal penalties. If
you receive this email by mistake, please delete it and notify us
immediately.

Data Protection: Please observe known data protection rules when sending us
personal data by limiting the data to what is absolutely necessary for the
job, password-protecting all data files (sms me the password, never send
the password in your subsequent email) and promptly deleting emails that
contain data.

**Comment by tekmun** [comment]
The ContextMenuOpening event is as follow:
`    private void ContextMenuOpening(object sender, ContextMenuEventArgs e)
    {
      if (_label.ContextFlyout == null)
      {
        CloseFrame();
        _label.ContextFlyout = menuflyout;
      }
      e.Handled = true;
    }`
The e.Handled = true is meant to disable the default context and use the user-defined menuflyout instead.  It works in 10.1803 but not 10.1809.

**Comment by samhouts** [comment]
@tekmun Does this also happen with a plain UWP app without Xamarin?

**Comment by tekmun** [comment]
Dear all,

I wouldn't know whether it happens with plain UWP app because I only
develop on Xamarin.  Same code runs well in 1803 but not in 1809.

With regards,

--------------------------------------

Cheong Tek Mun

Learnaholic Pte. Ltd.

(65) 92725050

www.learnaholic.com

* Out of learning, service overflows *

This email including any attachment may contain legally privileged or
confidential information. Any unauthorised use, retention, reproduction or
disclosure is prohibited and may attract civil and criminal penalties. If
you receive this email by mistake, please delete it and notify us
immediately.

Data Protection: Please observe known data protection rules when sending us
personal data by limiting the data to what is absolutely necessary for the
job, password-protecting all data files (sms me the password, never send
the password in your subsequent email) and promptly deleting emails that
contain data.

**Comment by tekmun** [comment]
This issue happens in Edge browser as well.  I used to be able to press and hold to call out the flyout.  Now, it no longer working.

**Comment by samhouts** [comment]
@tekmun It looks like this bug is specific to UWP and how it interacts with Windows. Unfortunately, this team does not have insight into those issues. Please report this issue via the Windows Feedback Hub (https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub). Thanks!!
