### ISSUE TITLE
[iOS only] "Cannot access a disposed object". Object name: "ScrollViewRenderer"

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#4979]
### Description
In my iOS project, when testing on iOS 8.3 specifically I get a "Cannot access a disposed object". Object name: "ScrollViewRenderer" when Navigating from within the MasterPage.ListView.ItemSelected method to the selected HomePageMenuItem pages (with ScrollViews as content). So when selecting different pages in my slide out menu the app crashes.

I haven't seen this exception on other devices I have tested such as iPhone 5 with 10.3.3 installed only on a iPhone 6+ with iOS 8.3. 

Also this exception doesn't happen on Xamarin.Forms 2.5.1.527  but it happens in the latest stable version 3.4.0. I have reverted in order to get around it for now.

- Version with issue: Xamarin.Forms 3.4.0
- Last known good version: Xamarin.Forms 2.5.1.527
- IDE: VS2017
- Platform Target Frameworks: 
 - iOS:  Xamarin.iOS Version: 12.0.0.15 

- Affected Devices: iPhone 6+ with iOS 8.3

I know its similar to this issue: https://github.com/xamarin/Xamarin.Forms/issues/4833 but I don't get it on Android, and for me it crashes consistently, if not the second navigation then on the third navigation, it will crash.

**Comment by rmarinho** [comment]
Hi, do you have a sample we can look at? 

Also any particular reason you need iOS8 support? We are fading support for iOS8 as it dropped the 1% market share.

https://data.apteligent.com/ios/

**Comment by HelenMamalaki** [comment]
@rmarinho After further testing it only seems to be an issue on iOS 8 and I don't have any need to support iOS 8. So please close this issue; I thought it may be useful to report regardless in case some other poor soul was doing testing on an old device/OS. however unlikely.

**Comment by rmarinho** [comment]
Awesome thanks.

**Comment by rmarinho** [comment]
@iosdevcluster do you have a reproduction ?

**Comment by versus1985** [comment]
Would you like me to share any code to reproduce the error? Or what information do you need?

**Comment by rmarinho** [comment]
Yes please if you can post a small reproduction example app will be great. 

Thanks
