### ISSUE TITLE
[iOS] OnAppearing not firing when returning to app 

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#4986]
### Description

Manual test for 52318 does not match the test instructions. Specifically, the test says "Only the last page should alert" when the app is reactivated after hitting the Home button. But currently _no alert_ displays when reactivating the app.

We need to determine if this is a regression or simply incorrect test instructions.

Original bug: https://bugzilla.xamarin.com/show_bug.cgi?id=52318

### Steps to Reproduce

1. Open the Control Gallery.
2. Navigate to issue 52318
3. Follow the test instructions.

### Expected Behavior

Instructions match the behavior of the app.

### Actual Behavior

The app displays different behavior than the instructions.

### Basic Information

- Version with issue: 3.5.0
- Last known good version: 2.3.5, assuming the instructions are correct.

**Comment by hartez** [comment]
See also #1874.

**Comment by hartez** [comment]
Android also does not alert when the app is reactivated.

**Comment by adrianknight89** [comment]
iOS page events are messed up. Also see #4608.

**Comment by berndu** [comment]
This is a vote +1 to change here please something.

In my case following is happening. iOS 12.1.3 physical device, iPhone X.
Start your app, stay on master detail, detail page (top of stack). Press power button, OnResignActivation, OnSleep was called, DidEnterBackground is called on AppDelegate.

If you resume the device, pressing power button and unlock device. App is still in foreground.
OnActivated AppDelegate, OnResume App.Xaml.cs is called but not OnAppearing of master detail detail page. I guess _hasAppeared flag does prevent this or SendAppearing is never called.

So solution can be - SendDisappearing and SendAppearing should be triggered in OnSleep/OnResume respectively?

Xamarin forms version is - 3.4.0.1.029999.
(not to mention that android does call OnAppearing of the current visible master detail detail page)

**Comment by ganesanvelusamy** [comment]
+1

I'm also facing the same issue.

**Comment by jorgeperalta** [comment]
Is this problem solved? I'm experiencing the same issue with xamarin forms 4.1.0.673156. Please answer.

**Comment by JanWidm** [comment]
Still experiencing this Problem. Only in iOS 13. Newer versions of iOS work fine and all versions I tested in Android work fine too! Any help?

**Comment by larsduewel** [comment]
Still is a problem sadly.

**Comment by JanWidm** [comment]
@larsduewel Posted my question on xamarin forums, maybe this could help you https://forums.xamarin.com/discussion/174412/xamarin-forms-ios-13-onappearing-not-called-after-i-navigate-back-from-platform-specific-code#latest

**Comment by Savage1024** [comment]
+1

**Comment by Savage1024** [comment]
I found a workaround [https://kent-boogaart.com/blog/hacking-xamarin.forms-page.appearing-for-ios](url)

**Comment by UKDeveloper99** [comment]
Has this been fixed because I'm still not getting current page OnAppearing calls when app is resumed from background in iOS?

**Comment by mduchev** [comment]
@UKDeveloper99 Unfortunately, it is **still** not fixed, and by the movement on the subject, I don't think that it will be fixed anytime soon. At least there's a workaround, which isn't the prettiest, but at least it works - you can use App's OnResumt handler to invoke an event when the app goes to the foreground again.

**Comment by UKDeveloper99** [comment]
@mduchev Yeah I've done something to that effect. Thank you for the prompt reply!
