### ISSUE TITLE
Dismissing the Context Action Menu on iOS Prevents Tapping a ViewCell

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#4987]
### Description
After revealing, then dismissing, the Context Action Menu on iOS, the user is unable to tap the `ViewCell`

### Reproduction Video 
https://www.dropbox.com/s/rqwu2kyijn0swp5/iOS%20Context%20Menu%20Bug%20Repro.mov?dl=0

### Reproduction Code
https://github.com/brminnick/InvestmentDataSampleApp

### Expected Behavior
User should be able to tap the ViewCell after dismissing the Context Action Menu 

### Actual Behavior
Nothing happens when the user taps the ViewCell after dismissing the Context Action Menu

### Basic Information

- Version with issue: 3.4.0.1009999
- Last known good version: Unknown
- IDE: Visual Studio Mac v8.0 build 869
- Platform Target Frameworks: 
  - iOS:  12.1
- Nuget Packages: Xamarin.Forms v3.4.0.1009999

### Screenshots

https://www.dropbox.com/s/rqwu2kyijn0swp5/iOS%20Context%20Menu%20Bug%20Repro.mov?dl=0

### Reproduction Link

Video: https://www.dropbox.com/s/rqwu2kyijn0swp5/iOS%20Context%20Menu%20Bug%20Repro.mov?dl=0
Code: https://github.com/brminnick/InvestmentDataSampleApp

### Environment Information

=== Visual Studio Enterprise 2019 Preview for Mac ===

Version 8.0 Preview (8.0 build 869)
Installation UUID: 3e30d340-21f3-4344-a25d-43de831b73f6
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.7.0.5148

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.2.0-preview3-27014-02
	2.1.6
	2.1.2
	2.1.1
	2.0.6
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.100/Sdks
SDK Versions:
	2.2.100
	2.2.100-preview3-009430
	2.1.500
	2.1.302
	2.1.301
	2.1.101
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 8

=== Xamarin.Android ===

Version: 9.1.4.2 (Visual Studio Enterprise)
Android SDK: /Users/bramin/Library/Android/sdk
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/bramin/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.1
Hash: 99d7ff4
Branch: remotes/origin/d16-0-p2~1
Build date: 2018-12-03 21:56:10 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: 
Build date: 2018-12-05 12:06:09-0500

=== Xamarin.iOS ===

Version: 12.2.1.12 (Visual Studio Enterprise)
Hash: 65ec520f
Branch: d15-9
Build date: 2018-12-05 12:06:09-0500

=== Xamarin Designer ===

Version: 4.17.1.189
Hash: 0e3953bd9
Branch: remotes/origin/d16-0-p1
Build date: 2018-11-07 13:21:06 UTC

=== Build Information ===

Release ID: 800000869
Git revision: 3c7c96b41ce6b823bf58bb89bda695448ccc97f5
Build date: 2018-12-03 21:59:44+00
Build branch: release-8.0
Xamarin extensions: 87c82bbb37a91ff539738267c414f0d6db88392c

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by rmarinho** [comment]
Works fine on 3.3

**Comment by james1301** [comment]
Why has this been so slow to be fixed, is this not quite fundamental? Last known good version was: 3.4.0.1008975 as mentioned on #5064. Unable to use 3.5 now.

Any kind of workaround?

**Comment by karlingen** [comment]
@paymicro wow, good job!

**Comment by scastria** [comment]
@samhouts I am testing on XF 4.3.0 and this bug is still present

**Comment by samhouts** [comment]
@scastria Would you please open a new issue? Thanks!

**Comment by scastria** [comment]
I was incorrect.  It isn't still present but a new regression bug is which I already submitted.  #8243

**Comment by samhouts** [comment]
Got it! Thanks!!
