### ISSUE TITLE
NavigationPage in MasterDetails Master prevents TabbedPage from rendering correctly (Android)

### ISSUE THREAD

**Issue by skunz95** [xamarin/Xamarin.Forms#4989]
### Description

When using a NavigationPage in the MasterDetails Master while using a TabbedPage on its Detail, one of the TabItems gets rendered incorretly

### Steps to Reproduce

1. Create a new MasterDetail page
2. Set its Master to a ContentPage which is wrapped in a NavigationPage
3. Set its Detail to a TabbedPage with 3 tabs. Each tab is a ContentPage wrapped in a NavigationPage

Important: The TabbedPages toolbarPlacement have to be set to the bottom using following code
this.On<Android>().SetToolbarPlacement(.ToolbarPlacement.Bottom);

### Expected Behavior

A Master which can be navigated on using the INavigation interface.
3 Tabs (on the Detail) to navigate on using the INavitgation interface.

### Actual Behavior

Third TabItem is rendered incorretly. It seems like the Masters NavigationPage-NavigationBar is rendered here.

### Basic Information

- Version with issue: 3.4.0.1009999
- Last known good version: 3.1.0.637273
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.1 (Oreo)
- Nuget Packages: Xamarin.Forms
- Affected Devices: 
   - Tested on Samsung Galaxy Tab Active2 and Samsung Galaxy XConver 4

### Screenshots
![screenshot_20190115-093819 1](https://user-images.githubusercontent.com/46705833/51170452-c6313300-18ae-11e9-92e3-fbf9d1c95536.jpg)

### Reproduction Link
[XamDroidTest_BugReport.zip](https://github.com/xamarin/Xamarin.Forms/files/2758885/XamDroidTest_BugReport.zip)

**Comment by rmarinho** [comment]
Hi we don't really support NavigationPage  on the master , you should use it as Detail of your navigation.

You can read that here

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#creating-a-masterdetailpage

```
.... it's recommended that the master page of a MasterDetailPage should always be a ContentPage instance, and that the detail page should only be populated with TabbedPage, NavigationPage, and ContentPage instances. This will help to ensure a consistent user experience across all platforms.^
```
