### ISSUE TITLE
CollectionView doesn't resize on orientation change

### ISSUE THREAD

**Issue by mattclarkie** [xamarin/Xamarin.Forms#4992]
### Description
When the orientation of the device changes from Landscape to Portrait the CollectionView doesn't stretch to fit the bottom of the screen, instead the CollectionView keeps it's original height leaving white space at the bottom of the screen. If you start in Portrait all is fine, though it looks like the Collection View doesn't shrink it's height when switching to Landscape.

### Steps to Reproduce

1. Download the Collection View sample from https://github.com/pauldipietro/CollectionViewSample
2. Build and run the sample with the device in Landscape
3. Rotate the device to Portrait

### Expected Behavior

CollectionView will increase it's height to fill the screen

### Actual Behavior
CollectionView height remains unchanged leaving whitespace at the bottom of the screen

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.8055-pre1
- Last known good version: None
- IDE: Visual Studio 2017 15.8.5
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 28
- Nuget Packages: All in the Sample linked
- Affected Devices: Android Simulator - Oreo

### Screenshots
![image](https://user-images.githubusercontent.com/34274897/51177432-74d97180-18b7-11e9-909c-a070a22dfe86.png)
![image](https://user-images.githubusercontent.com/34274897/51177439-7c007f80-18b7-11e9-8377-29a11c3f01ee.png)

### Reproduction Link
https://github.com/pauldipietro/CollectionViewSample

**Comment by rmarinho** [comment]
When using the Grid it seems the Bounds of the NavigationPage aren't respected also

**Comment by hartez** [comment]
> When using the Grid it seems the Bounds of the NavigationPage aren't respected also

@rmarinho If that's the case please file a separate bug with details.

**Comment by hartez** [comment]
This problem only occurs if the CollectionView is in a Shell application; if I set the main page of the application to BasicListPage, the problem goes away.
