### ISSUE TITLE
Having an issue with bindable AutomationID wherein the AutomationID can only be set one time... would be good if there is a way to enable the AutomationIDs to be set multiple times.

### ISSUE THREAD

**Issue by mashake-mendoza** [xamarin/Xamarin.Forms#4998]
I am designing a cross-platform UI test for Xamarin Apps but I am having a problem on how to set a sequential AutomationID on a ListView because the Grids/Cells in the ListView are being recycled.

For example I have 7 items in my ListView, assuming that 5 of the items are displayed in the screen when I load the page and I have to scrolldown to view the other 2, the other 2 grids are recycled from the first 5 items and the AutomationIDs for those grids are already set

*Expected AutomationIDs
ListTitle1
ListTitle2
ListTitle3
ListTitle4
ListTitle5
ListTitle6
ListTitle7

*Actual AutomationIDs
ListTitle1
ListTitle2
ListTitle3
ListTitle4
ListTitle5
ListTitle1
ListTitle2

Possible Solutions:
1. Since AutomationIDs are now bindable, should also allow the ability to set AutomationIDs multiple times
2. Have a way to disable ListView cells/grids recycling

- Version with issue: 3.4.0.1008975

**Comment by jfversluis** [comment]
> Since AutomationIDs are now bindable, should also allow the ability to set AutomationIDs multiple times

As far as I know, this is a restriction at OS level, that is why it can't be done from Xamarin.Forms

**Comment by mashake-mendoza** [comment]
I've seen the issue #3845, according to the replies ... the restriction was based from UITest that doesn't re-evaluate the tree. I am currently using XamarinUITest and Appium for automation, I am not sure if Appium is doing the same thing.

**Comment by rmarinho** [comment]
This was fixed.

https://github.com/xamarin/Xamarin.Forms/pull/3879

**Comment by ChrisJAult** [comment]
Is this fixed and if so what version? I'm having the exact same issue with 3.5.0.169047

**Comment by jeremy-bridges** [comment]
We seem to be having the issue as well. We're using 3.6.0.344457.
