### ISSUE TITLE
IOS - Set Has navigation page prevents navigation working

### ISSUE THREAD

**Issue by etu31327** [xamarin/Xamarin.Forms#5002]
When Setting NavigationPage.SetHasNavigationBar to false,

the navigation bar is not visible as expected but the navigation is disable on iOS (but still working on Android).

Is that possible to only hides navigation Bar element but keeping navigation activated?

The purpose is to be able to create a custom navigation bar (which is working on Android)

Thank you in advance for you help.

**Comment by rmarinho** [comment]
Hi navigation should always work, `SetHasNavigationBar`  only hides the navigation bar.

Thanks
