### ISSUE TITLE
Text entry focus throws exception with custom NSWindow Delegate

### ISSUE THREAD

**Issue by aodpi** [xamarin/Xamarin.Forms#5004]
### Description
Having a custom `NSWindow` delegate and then calling `Focus` on a `Entry` throws an Invalid operation exception. I strongly believe this issue was introduced with [PR#3011](https://github.com/xamarin/Xamarin.Forms/pull/3011) since the call stack goes to this line:

[link to line](https://github.com/jvansickle/Xamarin.Forms/blob/5af0ed392ac6dfe9cf19e01ad0852bae2e86ab07/Xamarin.Forms.Platform.MacOS/Renderers/EntryRenderer.cs#L32)

### Steps to Reproduce

1. Assign a custom delegate to NSWindow
2. Call `Focus()` method on a `Entry`

### Expected Behavior
The `Entry` should become focused
### Actual Behavior
App crashes with `InvalidOperationException`

### Basic Information

- Version with issue:
- Last known good version: 3.1.0
- IDE: Visual Studio for Mac 7.2.2 (build 21)
- Platform Target Frameworks: 
  - Xamarin.Mac 5.2.1.12 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 3.4.0.1008975
- Affected Devices:

### Screenshots

![screen shot 2019-01-17 at 18 28 12](https://user-images.githubusercontent.com/6562956/51333090-b1f35e80-1a85-11e9-9852-925c27a32c9c.png)

**Comment by rmarinho** [comment]
Do you mind  shows us the code setting the delegate for NSWindow? 

Maybe a small repo? 

Thanks

**Comment by DennisWelu** [comment]
Yup, verified in XF 3.4.169047. Basically can drop an Entry anywhere and clicking into it causes the crash. If I remove my custom WindowDelegate (assigned in AppDelegate.cs) then it all works fine. So in other words, don't do this:

`Window.Delegate = new MyWindowDelegate();`

**Comment by DennisWelu** [comment]
For my case, I was only using a custom WindowDelegate in order to override WindowShouldClose. But there's an object predicate that can be set on the Window instead and this works around the issue. e.g. `Window.WindowShouldClose = MyWindowShouldCloseMethod`. Looks like there's a predicate for ShouldZoom also.

**Comment by jfversluis** [comment]
Older issue and for macOS so the changes of this being fixed are pretty low. If anyone still wants to work on this I welcome any and all PRs, but we won't be working on this unfortunately. Thanks everyone!
