### ISSUE TITLE
Please support XamarinMediaManager for active development

### ISSUE THREAD

**Issue by scxp** [xamarin/Xamarin.Forms#5006]
I want to use the MediaManager plugin as showcased on your official blog. https://blog.xamarin.com/play-audio-and-video-with-the-mediamanager-plugin-for-xamarin/.

I can’t use this library for Xamarin Forms as it does not have .Net Standard support. Unfortunately, this project is not actively being maintained either. It’s very disheartening to read your blog only to find out the library is of no use. The people who maintain the project are asking for compensation to continue making improvements. I’d like Microsoft to either provide a cross-platform video plugin or support this library. @davidortinau

**Comment by kvpt** [comment]
A similar functionality is currently being integrated in Xamarin.Froms, see PR #3482.

**Comment by davidortinau** [comment]
@scxp we promote many open source community projects and contributions on our blog, and will continue to do so. This is in part with the hopes of driving help and support to them. XamarinMediaManager is MIT licensed and I suspect @martijn00 would welcome PRs and assistance maintaining it. 

As @kvpt points out, we have a PR that introduces MediaElement and we are looking forward to bringing that into Xamarin.Forms. At this time I cannot say how soon we will get that merged and released. Please show your interest and input on that PR so we can understand better if it will meet your needs.
