### ISSUE TITLE
[Material,WIP] Switch Spec

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5017]
# Material Switch Spec

https://github.com/material-components/material-components-ios/tree/develop/components/Switch
https://material.io/design/platform-guidance/cross-platform-adaptation.html#cross-platform-guidelines

> Android
Use Material switches, checkboxes, and radio buttons. 

> iOS
Native platform switches may be used as they have matching functionality and appearance as Material switches.

#### What Material expects
![image](https://user-images.githubusercontent.com/5375137/51400805-882e4c00-1b06-11e9-9ae5-676aa88eb54d.png)

#### Current implementation compared
![image](https://user-images.githubusercontent.com/5375137/51400113-d0e50580-1b04-11e9-87b6-f8483e667eaa.png)

### Expectations 

- **Visually Identical**

# API
```XAML
<Switch Visual="Material" />
```

```C#
new Switch() { Visual = VisualMarker.Material }
```

# Difficulty : high

**Comment by jfversluis** [comment]
With the current state of Material I guess this is not very useful anymore :)
