### ISSUE TITLE
[Feedback] xamarin OpenGLView gesturerecognizers events doesn't fire

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5024]
### Description

<p>I have a multiPlatform XamarinForms Vs2017 project (.NET standard, Android &amp; WPF).

I'm using a DependencyService due to a custom OpenGL 3D library.
I can set up OpenGLView correctly but i can't figure out how can track gestures.

Both GestureRecognizers applied to OpenGLView and its parent doesn't work as expected : events doesn't fire.
I'm trying with Frame=&gt;OpenGlView but the problem seems to be the OpenGlView .

The question is: 

has OpenGLView (WPF) the ability to handle touch events like any other Xamarin standard component (&quot;gesturerecognizers&quot;)?
If not, is there any workaround like this that does not works? (Https://forums.xamarin.com/discussion/26807/openglview-touch-event)

 Sources: http://davidemercanti.altervista.org/VEV/SydavHtml.zip
Images: https://i.stack.imgur.com/MVQgB.png</p>
<a href="https://developercommunity.visualstudio.com/content/problem/429539/xamarin-openglview-gesturerecognizers-events-doesn.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770218">original linked feedback ticket</a>.

### Source

[772675](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/772675)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
