### ISSUE TITLE
[Enhancement] Transparent Button and ImageButton on Android

### ISSUE THREAD

**Issue by acidbless** [xamarin/Xamarin.Forms#5029]
## Summary
For some reason setting the Color.Transparent as a background color for ImageButton and Button removes the ripple effect on the Android.

## API Changes
Not sure.

## Intended Use Case
I have difficulties to make ImageButton and Button truly transparent without losing the Ripple effect on the Android platform. Setting the background of the button as Color.Transparent makes its as a non "clickable", which creates the impression of its inoperability. Setting the value IsOpaque = "False" does not affect anything.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
