### ISSUE TITLE
[Enhancement] UWP-  Extend Page and Controls with RequiresPointer element

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#5032]
## Summary

UWP on xbox one has 2 options mouse pointer or game pad. by default xamarin has mouse pointer like for desktops. It can be changed for entire application setting up inside app.xaml.cs but if we want to change it per control today, it is not possible with xamarin. it will be nice to have UWP specific change like we have for Android and IOS for some other things.

Basically documetnation describes [here ](https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#activating-mouse-mode-on-a-control)

**Activating mouse mode on a control**
When the user engages a control with RequiresPointer="WhenEngaged", mouse mode is activated on the control until the user disengages it. The following code snippet demonstrates a simple MapControl that activates mouse mode when engaged:

XML

 
```
<Page>
    <Grid>
        <MapControl IsEngagementRequired="true"
                    RequiresPointer="WhenEngaged"/>
    </Grid>
</Page>
 
```

same for entire page as described in the documentation

**Activating mouse mode on a page**
When a page has the property RequiresPointer="WhenFocused", mouse mode will be activated for the whole page when it gets focus. The following code snippet demonstrates giving a page this property:

```
<Page RequiresPointer="WhenFocused">
    ...
</Page>
```
 
## Intended Use Case

That should give us better control and native look for Xbox apps. for example, listview supports both Mouse pointer and game pad but MapControl supports only mouse pointer.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
