### ISSUE TITLE
[Enhancement] Shell should support path parameter

### ISSUE THREAD

**Issue by danielmeza** [xamarin/Xamarin.Forms#5033]
## Summary
The new shell feacture is awesome to get started and solve many problems in the current navigation system, it currently implement navigation throw uri and support for query parameter but we some uri had path parameter, it will be awesome if we can support path parameters in the navigation, this way we can recicle the existing url from our web apps. 

So we can have the current template app://xamarin.com/my-app/services/{id}  we should support also middle path parameters like   app://xamarin.com/my-app/services/{id}/detail/{detalId} 

Parent: #2415

**Comment by MaxFmi** [comment]
That would be awesome. I just wanted to create another Enhancement ticket for supporting parameters for intermediate pages like 
- "/page1/page2{parameter}/page3" or 
- "/page1/page2?paramName=paramValue/page3" or 
- something better that I cannot imagine right now :-)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
