### ISSUE TITLE
Xamarin.Forms 4.0 Pre2 iOS CollectionView.EmptyView not showing

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5035]
### Steps to Reproduce

1. Create a project with Xamarin.Forms 4.0 Pre2
2. Add a page with an empty CollectionView with a label in the CollectionView.EmptyView
3. Test on iOS

### Expected Behavior
Show a default content

### Actual Behavior
Information not showing

### Basic Information

- Version with issue: 4.0 Pre2
- Last known good version: never
- IDE: VS 2017 Windows
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices: iPad

**Comment by samhouts** [comment]
This wasn't yet implemented in pre2. It'll be in pre3. Thank you!
