### ISSUE TITLE
[Spec] Use the Fluent API for initialization

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#5037]
# Fluent Initialization

What if we were to add a "Fluent API" for initialization of Xamarin.Forms? Instead of calling several `Init` methods that are not very intuitive or discoverable, we can use a fluent mechanism.

# API

## interface `IFormsInit`

This is the base interface that most extensions are from. This technically does not require any members, but could have in the future.

## interface `IFormsBeforeInit`

This is the base interface that the pre-init extensions run from. This technically does not require any members, but could have in the future.

## class `Forms`

```csharp
// existing class
public static class Forms {
    // change return type of Init
    public static IFormsInit Init() {
        // the existing code;

        // we don't event need to instantiate anything
        // but we can also create a private implementation if we want
        return null;
    }

    // new method
    public static IFormsBeforeInit BeforeInit() {
        // we don't event need to instantiate anything
        // but we can also create a private implementation if we want
        return null;
    }

    // new method
    public static IFormsBeforeInit WithFlags(this IFormsBeforeInit beforeInit, params string[] flags) {
        Forms.SetFlags(flags);
        return beforeInit;
    }

    // new method
    public static IFormsInit Init(this IFormsBeforeInit beforeInit) {
        // call the existing init
        var init = Init();

        // return it so the fluent can continue
        return init;
    }
}
```

## class `FormsMaps`

This code applies to third parties as well.

```csharp
// existing class
public static class FormsMaps {
    // new member
    public static IFormsInit WithMaps(this IFormsInit init, string mapKey) {
        // just call existing member
        FormsMaps.Init(mapKey);

        return init;
    }
}
```
 
# Scenarios

The existing code is a bit tedious:

```csharp
Forms.Init();
FormsMaps.Init("MAP_API_KEY");
FormsMaterial.Init(MaterialVersion.Year2017);
ImageCircleRenderer.Init();
```

Each of those types will be in different namespaces and I have to go look up documentation to find them. But with a fluent API

```csharp
Forms.Init()
    .WithMaps("MAP_API_KEY")
    .WithMaterial(MaterialVersion.Year2017)
    .WithImageCircle();
```

For most cases that would be fine, but we could extend this to be even more useful for things to happen BEFORE Init (such as `Forms.SetFlags("Experimental_SomeFlag")`):

```csharp
Forms.BeforeInit()
    .WithFlags("Experimental_SomeFlag")
    .Init()
    .WithMaps("MAP_API_KEY")
    .WithMaterial(MaterialVersion.Year2017)
    .WithImageCircle();
```

# Backward Compatibility

The idea behind this is that the fluent API does not require any changes to existing libraries and is totally opt-in.

# Difficulty : medium

**Comment by MisterJimson** [comment]
Super cool, borrows the style from ASP Net Core, where it works very well in my opinion.

**Comment by hartez** [comment]
Alternatively:

Let's not make users have to know about things like "pre" and "post" init. Just let them do something like: 

```
Forms.WithMaps("MAP_API_KEY")
	.WithFlags("Experimental_SomeFlag")
	.WithMaterial(MaterialVersion.Year2017)
	.WithImageCircle()
	.Init();
```

IFormsInit could look like this:

```
interface IFormsInit {
	void PreInit(Action action);
	void PostInit(Action action);
	
	void Init();
}
```

The implementation could simply be something like:

```
class FormsInit : IFormsInit {
	List<Action> _pre = new List<Action>();
	List<Action> _post = new List<Action>();
	
	void PreInit(Action action){
		_pre.Add(action);
	}
	
	void PostInit(Action action){
		_post.Add(action);
	}
	
	Init(){
		foreach(var initAction in _pre) { initAction(); }
		Forms.Init();
		foreach(var initAction in _post) { initAction(); }
	}
}
```

So Maps looks something like:

```
public static class FormsMaps {
    public static IFormsInit WithMaps(this IFormsInit init, string mapKey) {
        init.PostInit(() => FormsMaps.Init(mapKey));
        return init;
    }
}
```

In Forms, flags looks like:

```
public static IFormsInit WithFlags(this IFormsInit init, params string[] flags) {
        init.PreInit(() => Forms.SetFlags(flags));
        return init;
    }
```

Whoever's creating each extension method decides _when_ it happens in relation to `Forms.Init()`, and the end users never have to know or care; it just works.

**Comment by KSemenenko** [comment]
I will create pr

**Comment by jfversluis** [comment]
Super cool idea! Let's add this in .NET MAUI! Oh wait, it's already there! WOOHOO! 

Closing this for Xamarin.Forms :)
