### ISSUE TITLE
Xamarin.Forms previewer fails with shared project that doesn't follow specific naming pattern

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5038]
### Description
Currently the previewer expects a specific naming convention when associating a shared project and a platform project

```
<Project>.Android
<Project>.projitems
```

If the shared project has a name like
```
<Project>.Xamarin.projitems 
```

Than the previewer is unable to figure out what project to associate the shared project with.

Shared projects are being deprecated so I'm not sure how fixing this will get prioritized

### Original Description

I have a Xamarin.Forms Android project that uses a shared project for XAML and code-behind. I recently discovered the existence of the Xamarin.Forms XAML Previewer. Unfortunately, it does not appear to work with my project. The error displayed is the following:

"An android application project must reference a project containing this xaml file in order to render in the previewer"

Since the shared project is, well, shared, there's no way to reference it from the Android project.

The app works well otherwise, and has been shipping to the Google Play Store for some time now.

Any ideas on how to troubleshoot this? Thanks.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: Latest
- Last known good version: Unknown
- IDE: VS 15.9.5
- Platform Target Frameworks: 
  - Android: Latest
- Android Support Library Version: Latest
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/218865/51576055-91eae300-1e69-11e9-9470-a7050565fd2b.png)

### Reproduction Link

> VS bug [#775811](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/775811)

**Comment by mfeingol** [comment]
Any ideas on what might be causing this? I'd be happy to add you to my Azure DevOps project if you'd like.

**Comment by drewgillies** [comment]
@mfeingol I'd be interested to see whether this issue continues to reproduce with the latest VS 2019 preview. Please try it and see if we've fixed this one (I believe we have). If not, we'll take a deeper look.

**Comment by drewgillies** [comment]
Just repro'd this myself. As you were.

**Comment by mfeingol** [comment]
Confirmed it still repros in 2019 RC as well. :-)

**Comment by TimBarham** [comment]
> Since the shared project is, well, shared, there's no way to reference it from the Android project.
So, it is "referenced" from the Android project via including the shared project's `projitems` file in the Android project. For example:
```
<Import Project="..\BlankApp\BlankApp.projitems" Label="Shared" />
```
Perhaps not ideal wording for that error message for the shared project scenario, but regardless, it should work out of the box, and it is an issue if it does.

**Comment by mfeingol** [comment]
@TimBarham: you're right, my Android project has a `Label="Shared"` reference. However, the XF previewer doesn't work out of the box.

**Comment by arvindrajachourasiya** [comment]
Same issue I am facing....killing my time

**Comment by PureWeen** [comment]
@mfeingol can you try again on the latest vs 2019?

I tested with the following shared project
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/3244184/Archive.zip)


And for me that's showing up on vsmac and vs2019 now

**Comment by mfeingol** [comment]
@PureWeen: works with your sample projects. Still doesn't work with my own projects.

Want me to add you to my Azure DevOps project?

**Comment by PureWeen** [comment]
Yea!

**Comment by mfeingol** [comment]
You're in.

**Comment by mfeingol** [comment]
@PureWeen: let me know if you have any problems accessing the [project](https://dev.azure.com/sideroads/Sideroads) or reproducing the issue.

**Comment by samhouts** [comment]
@PureWeen ping!

**Comment by PureWeen** [comment]
It looks like I have access

I'm pulling down the project now and I'll let you know what I find.

Apologies for the delay

**Comment by mfeingol** [comment]
No worries. You can ping me internally if you have questions.

**Comment by PureWeen** [comment]
@mfeingol I updated the description with how to work around the issue.

**Comment by drewgillies** [comment]
Thanks for the issue. I'm doing a sweep of Xamarin.Forms previewer issues to close them as we're focusing on areas with greater impact for now. We will keep the issue on file, however, for future reference. Thanks again!
