### ISSUE TITLE
UIPickerView TextColor is not change when picker is loaded into view initially but color changes after a swipe inside Picker view in Xamarin.Forms.iOS

### ISSUE THREAD

**Issue by akarthikraja18** [xamarin/Xamarin.Forms#5039]
### Description
We are using UIPickerView in Xamarin.Forms.iOS. The Model for PickerView is set using UIPickerViewModel which is string list. I have changed Picker Text color using SetValueForKeyPath method. When Picker is loaded into view Picker's Text Color remains black there was no change in color, but if I made a swipe up and down on picker, color changed.

### Steps to Reproduce

1. Run the PickerRendererSample
2. Note TextColor is not changed(Given color is red) 
3. Scroll picker view up and then down, You can see the changes in color.

### Expected Behavior
UIPickerView TextColor should be changed when we assign a new color to it.

### Actual Behavior
I have changed the Text color and Background color for picker. Background color is changed as expected but text color is remains same no change is done.

### Basic Information
- Version with issue: Xamarin.Forms version 3.1.0.697729

- IDE: VS 2017
- Platform Target Frameworks:  NETStandard.Library(2.0.3)

- Nuget Packages: Xamarin.Forms(3.1.0.697729)
- Affected Devices:
iPhone 8 iOS 12.1 simulator
iPhone XS Max iOS 12.1 simulator 

### Screenshots
Picker with text color black(actual color is red)

![image](https://user-images.githubusercontent.com/41435300/51593554-6d017900-1f18-11e9-9efb-c97caab278ed.png)

After a scroll in picker color is changed

![image](https://user-images.githubusercontent.com/41435300/51593610-9cb08100-1f18-11e9-859d-334bc1c64765.png)

### Reproduction Link
Kindly find my sample
[PickerRenderer.zip](https://github.com/xamarin/Xamarin.Forms/files/2786389/PickerRenderer.zip)

**Comment by samhouts** [comment]
I'm afraid this isn't an issue with Xamarin.Forms. If you place your renderer code into a Xamarin.iOS project, you'll see the same behavior. I presume that you may need to set the text color later in the lifecycle. You may want to submit your question on StackOverflow for assistance. Thank you!

**Comment by akarthikraja18** [comment]
I have used UIPickerView that comes from Xamarin.Forms.iOS, please suggest a solution from your side. This is a issue with Xamarin.
