### ISSUE TITLE
[Enhancement] Alternate ways of creating Style or Setter to reduce verbosity

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5040]
## Summary

I found writing a Style with Setter for every property can be tedious even with all the XAML autocomplete features, especially when you have several properties to write:

`  <Setter Property="Foreground" Value="Red" />`

Proposals (both or just one of the following would help):

### 1. Target "template"
Support creating a Style out of an element "template" (not an actual DataTemplate though):

```
<Style TargetType="Label" x:Key="LabelStyle">
     <Label Foreground="Red"> 
</Style
```

In code this could be something like getting a method with the target instance and set properties on it:

```
var myStyle = new Style((label) => {
   label.Foreground = Colors.Red;
 });

```
The method is called by framework when the Style needs to be applied. I wonder if it wouldn't actually make applying styles faster, because today, with Setters, framework has hold an array of Setters and to iterate through them to apply the Style on the target.

#### How it would work with Setters?

Maybe allow to set it along with setters:

```
<Style TargetType="Label" x:Key="LabelStyle">
     <Label Foreground="Red"> 
      <Setter FontWeight="Bold"> 
</Style

```

Maybe someone has a better idea than this... 

### 2. Shorter Setter XAML syntax

Have a new XAML syntax for Setter:

`<Setter>Foreground,Red</Setter>`

This will work only for properties of value types, it won't work for the ControlTemplate property for example.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
