### ISSUE TITLE
Grid Layout with embedded Stack layout crash

### ISSUE THREAD

**Issue by kodejack** [xamarin/Xamarin.Forms#5042]
### Description
We are facing the same issue as discussed in the old forums   
[Xamarin forum](https://forums.xamarin.com/discussion/88367/nullreferenceexception-on-grid-calculateautocells-only-xf-ios)

Essentially we have a view that we are using as popover view, it has a Grid Layout with Embedded stack layout. This crashes with a null reference exception.

### Steps to Reproduce

1. Create a Grid layout with an embedded stack layout, app crashes when navigating to this view

### Expected Behavior
The view should render

### Actual Behavior
The app crashes

### Basic Information

- Version with issue: v3.4.0
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS: 11.3-12.1.1
  - Android: 6->8.1
- Affected Devices: iPad

[log.txt](https://github.com/xamarin/Xamarin.Forms/files/2787315/log.txt)

**Comment by samhouts** [comment]
[Issue5042.zip](https://github.com/xamarin/Xamarin.Forms/files/2793723/Issue5042.zip)

Unfortunately, I'm still unable to reproduce this. Can you take a look at the attached project and see if you can modify it such that it causes the crash? Thanks!

**Comment by samhouts** [comment]
@kodejack  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
