### ISSUE TITLE
[Enhancement] Cancel Event on Xamarin.forms.Button

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#5043]
### Description
For Now Button got 3 events: Clicked Pressed Released.
But there is no Cancel Touch Event on Button.
We could add it.

### Steps to Reproduce

1. Create such layout ScrollView-> StackLayout -> Button
2. The stacklayout need to be higher than the ScrollView 
3. Click on the Button, then move. 
At this moment the Touch event is cancel on Android and iOS but the event isn't traced back to xamarin forms.

### Expected implementation Xamarin.Forms
Add the cancel EventHandler and the method SendCancel in Xamarin.Forms.Button.
Add also the line in IButtonElement and IButtonController
Xamarin.Forms.Button.cs
```
        public event EventHandler Cancel;

	[EditorBrowsable(EditorBrowsableState.Never)]
	public void SendCancel() => ButtonElement.ElementCancel(this, this);

	[EditorBrowsable(EditorBrowsableState.Never)]
	void IButtonElement.PropagateUpCancel() => Cancel?.Invoke(this, EventArgs.Empty);
```
IButtonController.cs
```
void SendCancel();
```
IButtonElement.cs.cs
```
void PropagateUpCancel();
```

### Expected implementation IOS
Send Cancel Event when TouchCancel in iOS ButtonRenderer
```
        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);

            if (Control != null && e.NewElement is Button view)
            {
                Control.TouchCancel += SendCancel;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (Control != null)
            {
                  Control.TouchCancel -= SendCancel;
            }

            base.Dispose(disposing);
        }

        void SendCancel(object sender, EventArgs e)
        {
            ((IButtonController)Element)?.SendCancel();
        }
```

### Expected implementation Android
Send Cancel Event when MotionEventActions.Cancel in Android ButtonRenderer
```        
        public override bool OnTouchEvent(MotionEvent e)
        {
            if (e.Action == MotionEventActions.Cancel)
            {
                SendCancel();
            }
            return base.OnTouchEvent(e);
        }

        public override bool OnInterceptTouchEvent(MotionEvent ev)
        {
            if (ev.ActionMasked == MotionEventActions.Cancel)
            {
                SendCancel();
            }
            return false;
        }

        void SendCancel()
        {
            ((IButtonController)Element)?.SendCancel();
        }
```

Are you interesting in?
Let me know.
Regards,

**Comment by Phenek** [comment]
#3523  Kind of the same.

Regards,

**Comment by Phenek** [comment]
Okay I will manage to to it on iOS and Android, first

**Comment by maexsp** [comment]
Good proposal Phenek. We discovered the same issue.

**Comment by Phenek** [comment]
> Good proposal Phenek. We discovered the same issue.

You can find here the workaround => #3523

Regards,

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
