### ISSUE TITLE
Button CornerRadius doesn't work in explicit style when implicit style exists

### ISSUE THREAD

**Issue by jsiemens** [xamarin/Xamarin.Forms#5046]
### Description

Applies to Windows UWP only.

When you have
* an implicit style on a Button
* an explicit style on a Button containing a CornerRadius set to anything

Then, the CornerRadius gets set to a value of 5, ignoring the value that is set in the explicit style.

### Steps to Reproduce

Add some code to a page with both an implicit button style (no key), and an explicit button stlye (has a key).

Add a button that references the explicit style.

Sample code:

```
    <ContentPage.Resources>
        <Style TargetType="Button">
            <!--<Setter Property="CornerRadius" Value="0"></Setter>-->
            <Setter Property="BackgroundColor" Value="Blue"></Setter>
            <Setter Property="TextColor" Value="White"></Setter>
        </Style>
        
        <Style x:Key="ButtonStyle" TargetType="Button">
            <Setter Property="CornerRadius" Value="0"></Setter>
            <Setter Property="BackgroundColor" Value="Blue"></Setter>
            <Setter Property="TextColor" Value="Yellow"></Setter>
        </Style>
    </ContentPage.Resources>
    
    <StackLayout>
        <!-- Place new controls here -->
        <Label Text="Welcome to Xamarin.Forms!" 
           HorizontalOptions="Center" />
        
        <Button Text="Hello World" Style="{StaticResource ButtonStyle}"></Button>
    </StackLayout>
```

### Expected Behavior

The CornerRadius from the button's explicit style is used. In the example above, the CornerRadius should be 0.

### Actual Behavior

The CornerRadius from the button's explicit style is not used. In the example above, the CornerRadius is 5.

### Basic Information

- Version with issue: 3.4.0.1008975, 3.4.0.1009999, 3.5.0.62956-pre2
- Last known good version: 3.3.0.912540
- IDE: Visual Studio 2018 15.9.4
- Platform Target Frameworks: 
  - UWP:  16299
- Nuget Packages: Just Xamarin.Forms

### Screenshots

![cornerradius](https://user-images.githubusercontent.com/6842499/51632317-db880c00-1f03-11e9-9fae-bd01917c8bab.png)

**Comment by Mikescher** [comment]
I can reproduce this bug in the current Xamarin.Forms version (4.1.0.555618) for android and iOS (no idea about UWP, I don't have a WindowsPhone). 

Someone should probable add the p/Android and p/iOS labels
