### ISSUE TITLE
[Enhancement] Use the Community Toolkit TabView for UWP

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#5048]
## Summary

The UWP Community Toolkit has a beautiful TabView control that has infinite power. Yet, we are stuck in the dark ages.
Look at this beauty: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview

## API Changes

Hopefully, nothing has to change, but maybe we can create a flag, or maybe a platform specific that can say "use the new tabs, please!"

## Intended Use Case

Just look at this and you will know why:

![TabView](https://docs.microsoft.com/en-us/windows/communitytoolkit/resources/images/controls/tabview/overview.gif)

**Comment by jfversluis** [comment]
That looks mighty fine! Sadly Forms will be stuck in the dark ages in this regard... Let's do better for .NET MAUI! 💥
