### ISSUE TITLE
[Enhancement] Use the Community Toolkit for UWP

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#5049]
## Summary

The UWP Community Toolkit has so many nice controls, maybe we can have a look at what they are using and use them instead - or as alternatives:
https://docs.microsoft.com/en-us/windows/communitytoolkit/

Same with the Windows UI library:
https://github.com/Microsoft/microsoft-ui-xaml

Stacks of new controls to play with!

Related to #5048 

## API Changes

Hopefully, nothing changes from the code point of view, but we will probably need new renderers and some switches to toggle the new bits.

## Intended Use Case

UWP has moved on to great things, and we still are restricted to the base set. Android has the support libraries. iOS has all the effort in UIKit. UWP feels unloved and under-utilised.

**Comment by krdmllr** [comment]
I think this would solve some problems
* We could use UniformGrid for the CollectionView and fix #7842. 
* It adds an easy way to add shadows for #7839

**Comment by jfversluis** [comment]
Everyone should use this! I think for now things are the way they are... We'll see how things grow up for .NET MAUI
