### ISSUE TITLE
SimpleValueTargetProvider does not expose ParentObjects property.

### ISSUE THREAD

**Issue by jamiewest** [xamarin/Xamarin.Forms#5052]
I am following along with the [Creating XAML Markup Extensions docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/markup-extensions/creating#service-providers) and in the Service Providers section it mentions the `SimpleValueTargetProvider.ParentObjects` property. This property is not accessible because the [IProvideParentValues](https://github.com/xamarin/Xamarin.Forms/blob/fb498947d43b77e693750b23b76b0eb0dda97b33/Xamarin.Forms.Core/IProvideParentValues.cs#L5-L8) interface that `SimpleValueTargetProvider` inherits is `internal`. 

For some reason VS2017 intellisense exposes the property during debugging but it wont let you code with it. This `ParentObects` property would be super helpful. How can I access this?

**Comment by StephaneDelcroix** [comment]
You shouldn't use `SimpleValueTargetProvider` and expect that type to be returned whenever you request an `IProvideValueTarget`. The serviceProvider returned can depend on the context, and wether or not XamlC is enabled.

The point of `ParentObjects` is to implement `IReferenceProvider`, you might find what you need over there. We do not have plans to open `ParentObjects` as generating it is quite expensive, and we're still trying to see if we can avoid producing it.

hope it helps

**Comment by jamiewest** [comment]
The docs should be updated to not reference this then. 

I reviewed ‘IReferenceProvider’ and this won’t help me. I need to be able to identify the parent hierarchy of a ‘TargetObject’ from within an ‘IMarkupExtension’. I need access to all the types so I can search for the one I want based on the type’e inheritance, not the name. Any ideas?

**Comment by dansiegel** [comment]
@StephaneDelcroix I'd have to concur I have some scenarios as well where I need to evaluate the parent objects... it would really be great to open this API up
