### ISSUE TITLE
IntelliSense error XF VS2017 

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#5053]
### Description
I have `ListView `in xaml with `x:Name` name is `myList` it is showing error(red lines) in `ContentPage` (.cs)

Xaml file code

```
<StackLayout>
            <ListView x:Name="mylist">
            </ListView>
        </StackLayout>

```
ContentPage code

`mylist.ItemsSource = Items;`
### Steps to Reproduce

1. Create xamarin forms project.
2.  Add above code
3. 

### Basic Information

Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-60000-00001-AA519
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-60000-00001-AA519
Microsoft Visual C++ 2017

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.779 (d15-8@ff915e800)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.12 (d7ff6f39c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.118 (4217ee9)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots
![listerror2](https://user-images.githubusercontent.com/19743421/51676101-a232c780-1ffb-11e9-9546-d4395688278a.png)

### Reproduction Link
Link for more information

https://stackoverflow.com/questions/54329681/listview-is-available-only-for-android-error

**Comment by samhouts** [comment]
Does it work after you have built the solution?

**Comment by samhouts** [comment]
@arvindrajachourasiya And after you execute, does the Intellisense behave correctly, or do you still see the red underlines?

**Comment by arvindrajachourasiya** [comment]
@samhouts -  Intellisense behave same, red lines not going away. I  can always see 1 error in Error Window. Thank you.

**Comment by amirvenus** [comment]
Do you have Resharper installed? I had the exact same problem when using Resharper 2017 and it went away when I disabled/updated it.

**Comment by arvindrajachourasiya** [comment]
@amirvenus - No, I haven't installed Resharper.

**Comment by samhouts** [comment]
@arvindrajachourasiya Please attach your project so we can investigate further. Thank you!

**Comment by samhouts** [comment]
@arvindrajachourasiya Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
