### ISSUE TITLE
ContentPage BackgroundColor ignored in Forms 3.5.0.94564-pre3

### ISSUE THREAD

**Issue by irongut** [xamarin/Xamarin.Forms#5057]
### Description

ContentPage BackgroundColor is ignored in Forms 3.5.0.94564-pre3 causing the colour of a Xamarin.Android activity to show through (MainActivity or a splash activity). This is happening on device and emulator.

### Steps to Reproduce

1. Create a new Forms app.
2. Upgrade Forms nuget to v3.5-pre3. 
3. Upgrade Android.Support nugets to 28.0.0.1. (probably not necessary)
3. Set the BackgroundColor in MainPage.xaml to a non-white colour.
4. Run the app.

### Expected Behavior

MainPage uses the background colour specified in its XAML.

### Actual Behavior

MainPage has a white background (the colour of MainActivity).

### Basic Information

- Version with issue: 3.5.0.94564-pre3
- Last known good version: 3.5.0.62956-pre2
- IDE: VS 2017 v15.9.5
- Platform Target Frameworks:
  - Android: 8.1 + 9.0 (both tested)
- Android Support Library Version: 28.0.0.1 (also seen with 28.0.0)
- Affected Devices: Galaxy S6 Edge (Android 7.0) + Android Emulator

### Screenshots

Expected Behaviour: 
![expectedbehaviour-35pre3](https://user-images.githubusercontent.com/27953302/51717764-27d56800-203a-11e9-83bd-215cf645d295.png)

Actual Behaviour: 
![actualbehaviour-35pre2](https://user-images.githubusercontent.com/27953302/51717768-2b68ef00-203a-11e9-973a-0a3f83897949.png)

### Reproduction Link

[irongut/35pre3BGColor](https://github.com/irongut/35pre3BGColor)

**Comment by samhouts** [comment]
maybe related to #4916?

**Comment by Sergiojoel9877** [comment]
Same here..
