### ISSUE TITLE
[Android] Slider Value property does not work correctly with a specific min/max value

### ISSUE THREAD

**Issue by tlaivo** [xamarin/Xamarin.Forms#5058]
### Description

Define an Android slider with the following property values:
Minimum: 0
Maximum: 999
Implement a Step property with a value of 1.
Implement a ValueChanged event handler. Whenever slider Value property gets updated, round it to the closest integer value based on Step property.
So the slider value range is 0, 1, 2, ... 997, 998, 999.

When Value is set between 0 - 500 or to 999, everything works.
When Value is set to greater than 500 and less than 999, a rounding bug in Xamarin SliderRenderer causes the value to round down until it reaches 500.

Problem is caused by Value property implementation in SliderRenderer.cs:
double Value
{
    get { return _min + (_max - _min) * (Control.Progress / 1000.0); }
    set { Control.Progress = (int)((value - _min) / (_max - _min) * 1000.0); }
}
set sets Control.Progress based on given value. double value is changed to integer value (round may happen).
get returns the value based on the value of Control.Progress.
So there happens a rounding error (double -> integer -> double), which causes get to return a wrong value and causes to invalid behaviour.
With the given Minimum and Maximum value, get returns always a value which is less than what was set (if value was set between 501 and 998).

Instead of returning value based on Control.Progress, SliderRenderer should return the value based on an internal field. I have implemented the following workaround and it works.

private double _value;
private int _progress;
double Value
{
    get
    {
        if (Control.Progress != _progress)
        {
            _value = _min + (_max - _min) * (Control.Progress / 1000.0);
            _progress = Control.Progress;
            return  _value;
        }
        else
        {
            return _value;
        }
    }
    set
    {
        _value = value;
        _progress = (int)((value - _min) / (_max - _min) * 1000.0);
        Control.Progress = _progress;
    }
}

### Steps to Reproduce

Please see the description for details.

### Expected Behavior

It should be possible to set values between 501 - 998

### Actual Behavior

Only values  0 - 500 and 999 can be set.

### Basic Information

- Version with issue: Version with issue: release-2.5.1-sr4, bug seems to exist also with latest release-3.4.0-sr1.2
- Last known good version: -
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - iOS:  -
  - Android: 8.1
  - UWP:  -
- Android Support Library Version: 27.0.2
- Nuget Packages: -
- Affected Devices: All Android devices

**Comment by hartez** [comment]
[_5058 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4161938/_5058.Repro.zip)

It looks like we just need to toggle `_isTrackingChange` to `false` before updating `Control.Progress` in the `Value` setter, then turn it back on.

**Comment by tlaivo** [comment]
I have originally reported this error. I just updated my application to use release 4.8.0 Service Release 4 and it seems this problem does not exist anymore.

**Comment by hartez** [comment]
> I have originally reported this error. I just updated my application to use release 4.8.0 Service Release 4 and it seems this problem does not exist anymore.

@tlaivo Thanks for the heads-up - it looks like this was fixed in 4.5 and we forgot to update this issue.
