### ISSUE TITLE
Unable to debug Xamarin.Forms.Platforms.Android anymore

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5060]
### Description

When debugging the Gallery app, my VS2017 is unable anymore to step into any breakpoint I set in the Xamarin.Forms.Platforms.Android project. It stopped working in the last week.
I tried to rebuild, clean, delete all 'obj' and 'bin' folders under the Xamarin.Forms root folder, even cloned Xamarin.Forms repo into a fresh directory, it didn't work.

What it works:
- When debugging the Gallery app, it steps into breakpoints on Xamarin.Forms.Core. 
- When debugging the Gallery app on iOS or UWP, it steps into breakpoints I set in Xamarin.Forms.Platform.UWP/Xamarin.Forms.Platform.iOS.
- If I open one of my Xamarin.Forms apps, it steps into a breakpoint set in any code in the MyApp.Android project.

**Comment by PureWeen** [comment]
Yea this is a known issue with Xamarin Android and the linker. For now turn off linking on the Android ControlGallery project and then rebuild. After that break points should start working again. 

It'll be resolved in VS2019

**Comment by andreinitescu** [comment]
Thanks, I wasted a lot of time on this. 
You mention "this is known issue with linker", it might be but like I said, this used to work fine before recently, and I didn't do any changes on the project. I'm confused how could it stopped working.

**Comment by PureWeen** [comment]
It broke with one of the Visual Studio updates :-/ 

The breakpoints work the first time but then when you make a change to something and it compiles them again the updated files for debugging aren't getting synced up correctly
