### ISSUE TITLE
Keyboard FactoryMethod not know

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5062]
### Expected Behavior
Add Arguments for the entry keyboard

### Actual Behavior

2 error messages:

Erreur	XLS0507	Le type 'Keyboard' n'est pas utilisable en tant qu'élément objet, car il n'est pas public ou ne définit pas de constructeur sans paramètre public, ni de convertisseur de type.	Oracio	LoginPage.xaml	28	

Erreur	XLS1102	L'attribut 'FactoryMethod' de l'espace de noms XAML n'est pas défini.	Oracio	LoginPage.xaml	28	

### Basic Information

- Version with issue: 4.0 Pre3
- Last known good version:
- IDE: Visual Studio Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![keyboard_error](https://user-images.githubusercontent.com/22298309/51763258-6dde0a80-20d2-11e9-818e-c60da61f56f0.png)

### Reproduction Link
Used my code:

            <ScrollView Grid.Row="1" Grid.Column="0">
                <Frame VerticalOptions="Center" HorizontalOptions="FillAndExpand" Margin="100, 0, 50, 50">
                    <StackLayout>
                        <Entry Placeholder="Identifiant" IsTextPredictionEnabled="False" Text="{Binding LoginEntry}" >
                            <Entry.Keyboard>
                                <Keyboard x:FactoryMethod="Create">
                                    <x:Arguments>
                                        <KeyboardFlags>None</KeyboardFlags>
                                    </x:Arguments>
                                </Keyboard>
                            </Entry.Keyboard>
                        </Entry>
                        <Entry Placeholder="Mot de passe" IsPassword="True" />
                        <Button Text="connexion" />
                    </StackLayout>
                </Frame>
            </ScrollView>

**Comment by Moltroon** [comment]
Miss click. Sorry, can you delete ? I recreate.

**Comment by Moltroon** [comment]
Okay. I do not understand. It does not work for 1 hour. I make a ticket. I rebuild. It works ... Sorry for the inconvenience. You can delete.

**Comment by ThatBlokeCalledJay** [comment]
I'm getting exactly this issue in vs2019 Pro

![image](https://user-images.githubusercontent.com/9808053/55656322-6af84800-57ee-11e9-9162-95ea7f9a99ff.png)

**Comment by DamianSuess** [comment]
Just a heads up, the code does work. However, the ``Error List`` displays it as an error.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Position 77:17. An element with the name "Form" already exists in this NameScope		C:\Dev\ProjectName\Views\LoginPage.xaml	77	
```

XAML snip from LoginPage.xaml
```xml
            <Entry Text="{Binding UserName}"
                   IsEnabled="{Binding IsLoginEnabled}"
                   IsSpellCheckEnabled="False"
                   MaxLength="10"
                   Placeholder="UserName"
                   PlaceholderColor="#C5C5C5"
                   ReturnType="Next"
                   TextColor="{OnPlatform Android=#FFFFFF}">
              <Entry.Keyboard>
                <Keyboard x:FactoryMethod="Create">
                  <x:Arguments>
                    <KeyboardFlags>None</KeyboardFlags>
                  </x:Arguments>
                </Keyboard>
              </Entry.Keyboard>
            </Entry>
```

**Comment by nzcoward** [comment]
This is still an issue, even with the 'bug fix' in VS 2019 16.5 (I am running 16.9.4).

An initial build is ok, however the hot reload builds break (eventually - not sure of the frequency). This prevents further hot-reloading until the offending code is commented out. Then the builds will work again.

Have used both directly on the control and as a dynamic resource from a resource dictionary.

**Comment by Juansero29** [comment]
I'm experiencing the same problem as @nzcoward, can't use hot reload when while having this code in the page:

```xml
<Entry.Keyboard>
                    <Keyboard x:FactoryMethod="Create">
                        <x:Arguments>
                            <KeyboardFlags>CapitalizeSentence</KeyboardFlags>
                        </x:Arguments>
                    </Keyboard>
</Entry.Keyboard>
```

This needs to be reopened

**Comment by marcojak** [comment]
> I'm experiencing the same problem as @nzcoward, can't use hot reload when while having this code in the page:
> 
> ```
> <Entry.Keyboard>
>                     <Keyboard x:FactoryMethod="Create">
>                         <x:Arguments>
>                             <KeyboardFlags>CapitalizeSentence</KeyboardFlags>
>                         </x:Arguments>
>                     </Keyboard>
> </Entry.Keyboard>
> ```
> 
> This needs to be reopened

Same problem here

**Comment by igorgue** [comment]
Please reopen this issue I'm experimenting the same problem, it breaks hot reload.
