### ISSUE TITLE
[Enhancement] Add Xamarin.Forms.Platform.ASP.NET

### ISSUE THREAD

**Issue by redradist** [xamarin/Xamarin.Forms#5069]
## Summary
Xamarin makes a great progress with supporting a lot of platforms as _Xamarin.Forms.Platform.**Android**, Xamarin.Forms.Platform.**iOS**, Xamarin.Forms.Platform.**MacOS**, Xamarin.Forms.Platform.**UWP**, Xamarin.Forms.Platform.**GTK** ..._
To make it completely multi-platforms we need one additional platform - Web
My suggestion is to add **ASP.NET** (_Xamarin.Forms.Platform.**ASP.NET**_ or _Xamarin.Forms.Platform.**Web**_) as additional platform for **Xamarin.Forms** as was done in [Ooui](https://github.com/praeclarum/Ooui) UI Library

**Comment by charlesroddie** [comment]
Should close this as duplicate of https://github.com/xamarin/Xamarin.Forms/issues/1895 .

**Comment by redradist** [comment]
Guys, what is about this feature ?
Seems like it is possible to do as [Uno Platform](https://github.com/unoplatform/uno) has shown !!

Will we ever see Xamarin for ASP.NET based on WASM ?

**Comment by BradChase2011** [comment]
It appears some work is being done to bring webgl and html controls over to C#...

https://github.com/WaveEngine/WebGL.NET

The ways to interact with the browser will need some hooks, either a custom ui library running through webgl, canvas, or some hooks to the dom(html controls).

**Comment by samhouts** [comment]
Duplicate of #1895
