### ISSUE TITLE
Xamarin Forms Android Resource Designer Errors

### ISSUE THREAD

**Issue by aherrick** [xamarin/Xamarin.Forms#5070]
Xamarin Forms 4.0 preview 3
Visual Studio 2017 15.9.6

I'm seeing the following "errors". However I'm still able to compile/run the application. 

I've tried deleting/rebuilding bin/obj but they keep coming back. How do I eliminate?

![image](https://user-images.githubusercontent.com/586671/51788810-4ded2c00-2150-11e9-9dd0-03bdd8dc45e9.png)

**Comment by samhouts** [comment]
Did this only start after updating to pre3? If you downgrade again, does it stop? Thanks!

**Comment by aherrick** [comment]
Hey this was happening with pre1 as well. I was hoping upgrading to pre3 would fix but same result. It's a pretty stock Forms Android project and I'm the latest v28.0.0.1 nugets too.

Any suggestions?

**Comment by samhouts** [comment]
Can you attach your project so we can investigate further? Thanks!

**Comment by aherrick** [comment]
Sorry it's a closed source Forms solution. Anymore debugging or info I can give without the Source? would just the Xamarin.Android project itself work (has no real business logic)?

**Comment by samhouts** [comment]
@aherrick Hmm, maybe. Please share what you can, and let's see if it helps. In the meantime, has this issue persisted with pre5? Thanks!

**Comment by samhouts** [comment]
@aherrick  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by candidodmv** [comment]
Hi @samhouts  i'm getting the same error here.

**Comment by PureWeen** [comment]
- delete obj/bin
- convert to package reference
- check csproj files of all projects for conflicting versions
- delete the contents of Resource.designer.cs and rebuild android project

**Comment by candidodmv** [comment]
On the fly @PureWeen . Thanks

**Comment by nakulashok** [comment]
@PureWeen Thanks, it worked for me.

**Comment by johnshardman** [comment]
I have the same problem. Deleting obj/bin, converting to package reference, deleting contents of Resource.designer.cs all made no difference.

See https://forums.xamarin.com/discussion/159080/how-to-resolve-errors-in-resource-designer-cs-when-building-for-android
