### ISSUE TITLE
[iOS,FontImageSource] Shell tab icons don't tint

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5071]
### Description

I can use FontImageSource to set tab icons, but they aren't accepting the iOS tint color as expected. In this example, the center tab is a PNG and the others are font glyphs. I suspect we need to do something to treat this image format as a template.

https://www.screencast.com/t/C8YY4PYBO2

### Basic Information

- Version with issue: 4.0.1.102444-nightly
Parent: #2415

**Comment by kingces95** [comment]
Please attach the reproduction.

**Comment by davidortinau** [comment]
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2805364/Archive.zip)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/52012465-b43ebb00-247e-11e9-9f05-6d4a26d2a1cb.png)

**Comment by kingces95** [comment]
I can reproduce the iOS issue. Can you reproduce this Android crash?

**Comment by davidortinau** [comment]
@kingces95 I've not seen that crash.

**Comment by PureWeen** [comment]
https://stackoverflow.com/questions/32643596/i-upgraded-android-from-targetsdk-22-to-23-and-im-getting-a-nosuchmethoderror

I think this can happen if you're using an attribute on a resource that's only compatible up to a certain API as well

**Comment by kingces95** [comment]
There we go...
![image](https://user-images.githubusercontent.com/4120386/52014811-9d9b6280-2484-11e9-844c-1966a6a605a8.png)

**Comment by kingces95** [comment]
@StephaneDelcroix Yeah, looks like API 22 no like shell. The above exception reproduces on API 22 emulator.

**Comment by BYES-PA** [comment]
The same issue exists on Android, not for the Tab icons, but for the Flyout and SearchHandler Icons.
