### ISSUE TITLE
Black page when no ShellContent.Content.BackgroundColor

### ISSUE THREAD

**Issue by jdluzen** [xamarin/Xamarin.Forms#5073]
### Description
When no background is set on the ShellContent.Content, the below screenshot happens.
### Steps to Reproduce

1. Make a default Shell app, not setting the background anywhere.

### Expected Behavior
A default Shell experience with a black or white page with no after effects with flyout.

### Actual Behavior
A black screen, reminiscent of yee olden XP.
### Basic Information

- Version with issue:
- Last known good version: This is the first time I've tried a Shell app
- IDE: VS 2017
- Platform Target Frameworks:
  - Android: 9, 8.1
- Nuget Packages: Xamarin.Forms: 4.0.0.94569-pre3
- Affected Devices: All emulators I've tried

### Screenshots

After closing flyout, which did look fine.
![image](https://user-images.githubusercontent.com/160958/51794849-bff15f80-21a8-11e9-8772-eef78daf0170.png)

**Comment by varyamereon** [comment]
I'm experiencing this too, it wasn't present in 4.0.0.62955-pre2. My only solution is to set the BackgroundColor of the first element on the Page (eg. Grid). Setting the BackgroundColor of the ContentPage itself does not resolve this issue for me.

**Comment by kingces95** [comment]
Could you please attach your reproduction?

**Comment by samhouts** [comment]
I bet #5066 will resolve this one, too.

**Comment by kingces95** [comment]
5066 Didn't fix it for me. But here is a repro. 
[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2814689/Archive.zip)

**Comment by andreinitescu** [comment]
@kingces95 Thanks for providing the repro. I took some time to test this, I confirm it's fixed by #5057 🎈

![image](https://user-images.githubusercontent.com/743918/52109972-d9ab0080-2607-11e9-8b8a-ce50fe9740a2.png)
