### ISSUE TITLE
Implicit style is not applied to derived types

### ISSUE THREAD

**Issue by Mirinael** [xamarin/Xamarin.Forms#5077]
### Description
Since my update from 3.4 to 4.0, every project I have suffer the same issue : no implicit style is applied to TargetElement subclasses.

Looks like ApplyToDerivedTypes is broken.

### Steps to Reproduce

1. Create a subclass of an element (let's say, Label and SubLabel)
2. Create a style for the parent class in XAML (TextColor="Chocolate")
3. Precise ApplyToDerivedTypes="True"

### Expected Behavior
The TextColor property should be applied to both Label and SubLabel.

### Actual Behavior
The TextColor property is only applied to Label.

### Basic Information
- Version with issue: 
    - 4.0.0.94569-pre3
    - 4.0.0.62955-pre2
- Last known good version: 3.4.0.1008975
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  didn't test
  - Android: 
    - target : 9.0
    - minimal : 5.1
  - UWP:  Nope
- Android Support Library Version: ?
- Nuget Packages: (common between my projects)
    - Xamarin.Forms
    - FFImageLoading
    - Xamarin.Essentials
    - RestSharp
    - Newtonsoft.Json
- Affected Devices:

### Screenshots
I don't have the time to produce a working example to take screens, and I'm not allowed to put screens of my apps.

### Reproduction Link
Same here.

**Comment by Mirinael** [comment]
For some reasons I am unable to produce a working example. The behavior is normal in my sample project. I'll investigate a bit more.

**Comment by AntRemo** [comment]
@Mirinael I just ran into this issue where secondary implicit styles removes the parent implicit style. 😞

**Comment by StephaneDelcroix** [comment]
I wrote a unit test for this

```csharp
[Test]
//https://github.com/xamarin/Xamarin.Forms/issues/5077
public void ImplicitStyleAppliedToDerived()
{
	var labelStyle = new Style(typeof(Label)) {
		ApplyToDerivedTypes = true,
		Setters = {
			new Setter { Property = Label.TextColorProperty, Value = Color.Red},
			new Setter { Property = Label.FontSizeProperty, Value = 10}
		}
	};

	var sublabelStyle = new Style(typeof(SubLabel)) {
		Setters = {
			new Setter { Property = VisualElement.BackgroundColorProperty, Value = Color.HotPink},
			new Setter { Property = Label.FontSizeProperty, Value = 20}
		}
	};


	//implicit styles with applyToDerived should apply to subclass
	var sublabel = new SubLabel();
	var layout = new StackLayout {
		Resources = new ResourceDictionary { labelStyle},
		Children = { sublabel}
	};
	Assert.That(sublabel.TextColor, Is.EqualTo(Color.Red));
	Assert.That(sublabel.FontSize, Is.EqualTo(10d));

	//both implicit styles are applied to derived
	sublabel = new SubLabel();
	layout = new StackLayout
	{
		Resources = new ResourceDictionary { labelStyle, sublabelStyle },
		Children = { sublabel }
	};
	Assert.That(sublabel.TextColor, Is.EqualTo(Color.Red));
	Assert.That(sublabel.BackgroundColor, Is.EqualTo(Color.HotPink));
	Assert.That(sublabel.FontSize, Is.EqualTo(20d));
}
```

and it's green on the `master` branch so it looks all right to me. So I'm going to close this bug. Feel free to reopen it if you can isolate the issue on the latest version.

Thanks

**Comment by NageshMaddala** [comment]
@StephaneDelcroix I ran the above unit test and it got failed with below error:

` Message: 
      Expected: [Color: A=1, R=1, G=0, B=0, Hue=1, Saturation=1, Luminosity=0.5]
      But was:  [Color: A=-1, R=-1, G=-1, B=-1, Hue=-1, Saturation=-1, Luminosity=-1]`

Looks like it's broken with the latest code or I'm doing something wrong. 
I'm on:
Xamarin.Forms - 5.0.0.2012
Xamarin.Forms.Mocks - 4.7.0.1
NUnit - 3.12.0
Please let me know the version where you are running the above test. Thank you.
