### ISSUE TITLE
ArgumentNullException when using ContentView

### ISSUE THREAD

**Issue by rsatter** [xamarin/Xamarin.Forms#5081]
### Description
If you set the content of the ShellContent tag to be a ContentView the InitializeComponent method throws an ArgumentNullException. An exception is the correct behavior as the content should be ContentPage, not ContentView. However, the exception is incorrect. It should through an exception complaining about the type of content.

### Steps to Reproduce

1. Create a new shell application
2. Have content point to a ContentView
3. Run Application

### Expected Behavior
Throw exception stating that ContentView is not a supported content type.

### Actual Behavior
Throws an ArgumentNullException

### Basic Information

- Version with issue: 4.0.0.94569-pre3
- Last known good version:
- IDE: Visual Studio for Mac v8.0 Preview (8.0 build 869)
- Platform Target Frameworks: 
  - iOS:  all versions
  - Android: all versions

### Reproduction Link

https://github.com/rsatter/bailassistant
Parent: #2415

**Comment by rmarinho** [comment]
@rsatter better? https://github.com/xamarin/Xamarin.Forms/commit/310c195dc41acb5ee675145ceea8e972f0ba38c2

**Comment by rsatter** [comment]
This will be way better. It will be easy to resolve the issue.
