### ISSUE TITLE
ListView.BeginRefresh does more than indicated

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#5083]
The [ListView.BeginRefresh](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview.beginrefresh) docs make it seem like it is just a synonym for setting `IsRefreshing` true, but if you look at the code, that's not the case.

At a higher level, the design and usage goal of having `BeginRefresh`, `EndRefresh`, and a settable `IsRefreshing` is not clearly documented. It seems that the API could be simplified by removing `BeginRefresh` and `EndRefresh`.

**Comment by samhouts** [comment]
For backwards compatibility reasons, we will not remove any API. Thanks!

**Comment by breyed** [comment]
I don't think this issue should be closed. Even though the cleanup of removing overlapping members isn't worth a breaking change, the API can still be improved by marking one of the approaches as obsolete and documenting the nuanced differences between the two. As it is, it's not clear what the best way to use the API is.
