### ISSUE TITLE
Using FontAttributes property crashes application since version 3.3.0.912540

### ISSUE THREAD

**Issue by s091704** [xamarin/Xamarin.Forms#5085]
### Description
On Android when using the FontAttributes property of a button the application crashes. Downgrading Xamarin Forms fixes it so it's a bug only since version 3.3.0.912540
### Steps to Reproduce

1. Start a new Xamarin Forms project with at least Android.
2. Add a button to a xaml file.
3. Add the property FontAttributes to the button.
4. Start application
5. Crash

### Expected Behavior
no crash
### Actual Behavior
crash
### Basic Information

- Version with issue: 3.3.0.912540
- Last known good version: 3.2.0.871581
- IDE: Microsoft Visual Studio
- Platform Target Frameworks: 
  - Android:$
- Nuget Packages: Xamarin Forms
- Affected Devices: Android

**Comment by andreinitescu** [comment]
@s091704 Update to latest stable 3.4.0.1029999 and it works OK

![image](https://user-images.githubusercontent.com/743918/51902707-48e3e300-23c3-11e9-9f8b-d41a583e1b02.png)

**Comment by s091704** [comment]
@andreinitescu  that's when it started to happen...
just follow the reproduction steps(cost you about 1 min to test.

**Comment by andreinitescu** [comment]
@s091704 I did follow your reproduction steps and it works

![image](https://user-images.githubusercontent.com/743918/51903873-ed672480-23c5-11e9-86f4-354f3fae2931.png)

![image](https://user-images.githubusercontent.com/743918/51903882-f3f59c00-23c5-11e9-969a-76ec202f222a.png)

**Comment by StephaneDelcroix** [comment]
I second @andreinitescu here
> If it still doesn't work for you with latest, you should provide a reproduction project

**Comment by samhouts** [comment]
@s091704  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
