### ISSUE TITLE
32Bit x86 XF UWP RAM limit 1GB

### ISSUE THREAD

**Issue by toronf** [xamarin/Xamarin.Forms#5091]
### Description
Xamarin Forms UWP app crashes when 1GB ram limitation is reached, when build in 32Bit mode (Platform target x86) -> System.OutOfMemoryException. 64Bit XF applications, of course, does not have this limitation. 
But also the limitation with 32Bit native UWP applications is even more than double the XF UWP limitation.
Doesn't matter weather this ram is really in use by the application or just allocated. Also verified with process explorer (private bytes and working set).

**32 Bit XF app** reaches out of memory by hitting the **1GB limit**. 
Same application built in 64bit mode is able to allocate more than 8GB of ram (might be much more, just tested up to 8GB).
**32Bit native UWP** application reaching limit by around **2/2.5GB**

### Steps to Reproduce

1. create a simple XF application that does some memory intensive operation (e.g. running buffer.Add(new byte[10 * 1024 * 1024]); within a loop) and build UWP with 32bit.

2. build the same application in 64bit mode.

3. build a native UWP application with same operation in 32Bit mode.

### Expected Behavior
same limitation as native 32Bit UWP application (reaching out of memory at around 2/2.5 GB ram usage).

### Actual Behavior
32 Bit XF application reaches **out of memory** by hitting the 1GB limitation.

### Basic Information
- Version with issue: tested with 2.5.x and 3.3
- IDE: VS 2017
- Platform Target Frameworks: 
  - UWP:  17134
- Affected Devices: tested with W10 1703 (16GB RAM), 1803 (4GB RAM), both i5 6Gen CPU

**Comment by kingces95** [comment]
Can we motivate this issue a bit more from the perspective of a UI productivity framework? Are people hitting this limit while developing actual apps?

**Comment by nbevans** [comment]
Is there a stack trace from where in XF raised this OOM exception?

**Comment by dasMulli** [comment]
(dev working in the same company as @toronf )

> Are people hitting this limit while developing actual apps?

That's why @toronf opened this issue. Some computer vision related tasks along with high resolution image processing create a spike in memory usage that crashes the application. Unfortunately some native dependencies force them to target 32 bit.

> Can we motivate this issue a bit more from the perspective of a UI productivity framework?

The interesting part is that the limit seems to be lower when using Xamarin.Forms instead of raw UWP.
Is this known / by design? is there a way to configure this?

**Comment by toronf** [comment]
any news?

**Comment by toronf** [comment]
We've found a workaround, even if it's not fully satisfying. 
It's possible to use EDITBIN with LARGEADDRESSAWARE to modify the executable after installing the application. 
https://docs.microsoft.com/en-us/cpp/build/reference/editbin-options?view=vs-2017 

Still unclear why this limit does not exist for native UWP applications.

**Comment by samhouts** [comment]
That's odd, for sure. We'll have to investigate. Thanks for the update!

**Comment by jfversluis** [comment]
Old and obscure problem with a workaround. Let's hope its better by now and/or for .NET MAUI. Closing for now!
