### ISSUE TITLE
WPF restore with .net core 3

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#5092]
Xamarin.Forms WPF is restored with .Net Framework 4.6.1 rather then .netcoreapp3.0.

Steps to reproduce:

1. install .net core 3.0
2. execute dotnet new wpf
3. add xamarin forms and xamarin forms wpf packages.

AR:
warning:
wpf package is restiored with .net framework 4.6.1

ER:
no warning

**Comment by kingces95** [comment]
Can you please provide more detailed steps for the reproduction? Which download link are you using, what command lines are you issuing, and what IDE are you using to add XF?

**Comment by PureWeen** [comment]
Xamarin.Forms wpf only builds currently with a net461 target

We would need to create a compatible netcoreapp3 target first in order for it to restore as netcoreapp3

**Comment by krdmllr** [comment]
Is this something you are already looking into? I could take a look otherwise although I don't know how usefull this is as long as dotnet core 3 is still in preview.

**Comment by VladislavAntonyuk** [comment]
Current version is preview 7. There will be 9 previews. 
From Microsoft blog: NET Core 3.0 Preview 7 is supported by Microsoft and can be used in production.

**Comment by krdmllr** [comment]
I was able to create a compiling version and successfully tested it in a WPF/.NET Core 3 and WPF/.NET Framework project
![image](https://user-images.githubusercontent.com/11095003/62417642-13130600-b655-11e9-8c63-975fce6ddbb8.png)

I created a PR https://github.com/xamarin/Xamarin.Forms/pull/7063
