### ISSUE TITLE
[Enhancement] Editor.CursorPosition

### ISSUE THREAD

**Issue by stevehurcombe** [xamarin/Xamarin.Forms#5093]
## Summary
I want the user to be able to edit long notes and it's useful to have 'home' and 'end' navigation shortcuts, a la Google Chrome browser, this is because the scroll cursor and scroll position can be difficult to control when moving around a long note. 

I would also be able to 'insert something at the current cursor position'.

## API Changes
See https://github.com/xamarin/Xamarin.Forms/issues/1667 for Entry.

**Comment by jcmanke** [comment]
I would recommend moving it from `Entry` to the base class `InputView` rather than duplication. (#4477)

**Comment by jcmanke** [comment]
Calling dibs because I want a t-shirt.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
