### ISSUE TITLE
[Android] TabStop impossible to choose material entry

### ISSUE THREAD

**Issue by paymicro** [xamarin/Xamarin.Forms#5102]
### Description

When pressing tab key focus receive layout of material entry without changing text.
I think this maybe fixes if add interface `IDontGetFocus` to `MaterialFormsTextInputLayout` 

### Steps to Reproduce

1.  open `Entry Material Demos`
2.  select first `entry`
3.  try to switch to the next `entry` using the tab key

### Expected Behavior

Second `entry` selected. And available writing text.

### Actual Behavior

Second layout of `entry` selected. And writing text is not available

### Screenshots

![screenshot_14](https://user-images.githubusercontent.com/27482193/52055420-66a27b00-2570-11e9-8d06-63b9970fa03e.png)

**Comment by jcmanke** [comment]
I think the fix to this is to reimplement `ITabStop` on the `MaterialEntryRenderer` to return `EditText` instead of `Control`.
