### ISSUE TITLE
[Android Material] Ripple effect on material entry

### ISSUE THREAD

**Issue by paymicro** [xamarin/Xamarin.Forms#5103]
### Description

Material entry should't show ripple effect.
Related issue #5102

### Steps to Reproduce

1. open `Entry Material Demos`
2. select first entry
3. try to switch to the next `entry` using the tab key
4. click/tap on second entry.

### Expected Behavior

Material entry should't show ripple effect.

### Actual Behavior

Material entry show ripple effect on center of control.

### Basic Information

- Version with issue: `master`

### Screenshots

![screenshot_15](https://user-images.githubusercontent.com/27482193/52055816-838b7e00-2571-11e9-91ef-0c2e10ae0cd9.png)

**Comment by Miiite** [comment]
@samhouts I just tried to reproduce the issue using the scenario described initially, and I can't (on branch master).
I think this issue should be closed / marked as fixed.

**Comment by PureWeen** [comment]
@paymicro what device/api did you test this on?

**Comment by paymicro** [comment]
@PureWeen android emulator on Windows / api 27
I couldn't reproduce the issue now. Apparently already fixed.
