### ISSUE TITLE
 [Enhancement] Disable scrolling in ScrollView

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#5105]
## Summary
I would like to be able to turn off scrolling in ScrollView.
If you disable the scroll, then the control does not respond to gestures, passing them inside.

## API Changes
```cs
ScrollView.Scrolling = ScrollingMode.Enabled;
ScrollView.Scrolling = ScrollingMode.Disabled;
```

## Intended Use Case
For example, when my phone is in vertical mode, then vertically scroll the entire page,
and if horizontally, only half of the page is vertically scrolled.

**Comment by charlesroddie** [comment]
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/2680
