### ISSUE TITLE
[Enhancement] Add IsVisible to TableSectio

### ISSUE THREAD

**Issue by salgiza** [xamarin/Xamarin.Forms#5106]
I think the subject says it all. The idea is to be able to do something like:

        <TableView Intent="Settings">
            <TableRoot>
                <TableSection Title="Basic Settings">
                     <SwitchCell Text="Option That Requires Extra Config" On="{Binding MyOptionSelected}"/>
                </TableSection>   
                <TableSection Title="Extra config for MyOption" IsVisible="{Binding MyOptionSelected}">
                     
                </TableSection>   
            </TableRoot>
        </TableView>

In the previous example, the second TableSection would only be visible if the SwitchCell on the first table section is selected.

My experience is that this is actually quite a common requirement, and you can find several question regarding this feature both in the Xamarin and StackOverflow forums, but I haven't seen any tickets already opened regarding it.

**Comment by jrahma** [comment]
Hope this will be implemented soon

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
