### ISSUE TITLE
TableSection's Title property binding does not react to changes

### ISSUE THREAD

**Issue by PenguinPero** [xamarin/Xamarin.Forms#5109]
### Description
TableSection's Title property binding applies binding only once, like OneTime even when Mode=TwoWay is set
I am implementing language selection in runtime, so it is important for me to change this title through binding

### Steps to Reproduce

1. Create a TableView with TableSection
2. Create VM with `TestTitle` property with `INotifyPropertyChanged`
2. Bind `<TableSection Title="{Binding TestTitle, Mode=TwoWay}">`
3. Change `TestTitle` in ViewModel (at least to two different values, works with initial value)

### Expected Behavior
TableSection's Title should change

### Actual Behavior
TableSection's Title does not change

### Basic Information

- Version with issue: 3.4.0.1009999

**Comment by kingces95** [comment]
Works for me. Adding `Mode=TwoWay` also works. Please attach a repro if your scenario is different. 
[App78.zip](https://github.com/xamarin/Xamarin.Forms/files/2830247/App78.zip)

**Comment by PenguinPero** [comment]
I apologise it was an error from my side, I set the `TableView.Root` property to `TableSection` object :)
Closing the issue
