### ISSUE TITLE
[Feedback] [VS2019 Preview 2] Xamarin.Forms Shell template outputs "Xamarin.Essentials.dll.mdb does not exist" error

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5113]
### Description

<p>VSF_TYPE_MARKDOWNCreating a new Shell app with the provided template and attempting to build returns the following error within the Android platform project:

`The file &quot;C:\Program Files (x86)\Xamarin\NuGet\xamarin.essentials\1.0.0\lib\monoandroid81\Xamarin.Essentials.dll.mdb&quot; does not exist	`

Steps (at least locally) are simple, in creating a new Xamarin.Forms Shell app and attempt to build and run it, and the error appears in output. This may be due to a local issue, but was encountered in a new project.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/439612/vs2019-preview-2-xamarinforms-shell-template-outpu.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/780780">original linked feedback ticket</a>.

### Source

[784675](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/784675)

**Comment by PureWeen** [comment]
For anyone that runs into this issue if you install version 1.0.1 of essentials it'll get rid of the error

**Comment by davi1td** [comment]
Not working for me with 1.0.1 of essentials, Upgraded all packages to latest preview versions running on VS 2019 preview 2.2

**Comment by davi1td** [comment]
Only file there are Xamarin.Essentials.dll|pdb|xml
Downgraded to 1.0 and back to 1.0.1 no luck

**Comment by perepechin** [comment]
Guys, 
Please try to run VS 2019 as administrator. I had the same issue, but when I started my VS 2019 as administrator I was able to build the solution without any issues and Xamarin.Essentials.dll.mdb was successfully created in C:\Program Files (x86)\Xamarin\NuGet\xamarin.essentials\1.0.0\lib\monoandroid81
