### ISSUE TITLE
Xamarin.forms Mac - image inside relative layout does not display

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#5114]
### Description
Xamarin.forms Mac - image inside relative layout does not display
### Steps to Reproduce

1. Create a Xamarin forms iOS and .Mac app
2. Add relative layout
3. Add image and use constraints to set the image width and height
4. Add BoxView and use the same constraints to set the image width and height of box view
### Expected Behavior
Image will show and resize based on the constraints set

### Actual Behavior
Image won't show unless width of image and height set manually 

### Basic Information

- Version with issue: Xamarin forms 3.4
- Last known good version: never worked
- IDE: Visual studio for Mac
- Platform Target Frameworks: IOS and MAC

- Nuget Packages:
- Affected Devices:

past this XAML into your page - then run - make sure project is setup For Xamarin.forms.mac per this article:
https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/

XAML to repro:
 <ContentPage.Content> 
        <StackLayout>
        <Image Source="Rectangle.png"
                    HorizontalOptions="Center"
                    VerticalOptions="CenterAndExpand" WidthRequest="100" HeightRequest="100" />

             <RelativeLayout> 
             
         
         <BoxView BackgroundColor="Transparent" x:Name="Artboard1" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, 
                 Property=Height,Factor=0,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, 
                Property=Width,Factor=0,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToParent,Property=Width,Factor=1,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToParent,Property=Height,Factor=1,Constant=0}" /> 
         <BoxView BackgroundColor="Transparent" x:Name="Group" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, 
                 Property=Height,Factor=0.09040178,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, 
                Property=Width,Factor=0.1183575,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToParent,Property=Width,Factor=0.763285,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToParent,Property=Height,Factor=0.7912946,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="StackLayout" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                 Property=Height,Factor=0.2919605,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                Property=Width,Factor=0.1898734,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Width,Factor=0.9651899,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Height,Factor=0.1650212,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="Rectangle1" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                 Property=Height,Factor=0.4992948,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                Property=Width,Factor=0.1550633,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Width,Factor=0.4525316,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Height,Factor=0.1734838,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="Group2" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                 Property=Height,Factor=0.7983075,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                Property=Width,Factor=0.4462025,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Width,Factor=0.5158228,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Height,Factor=0.3159379,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="StackLayout5" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                 Property=Height,Factor=2.84375,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                Property=Width,Factor=0.9018405,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Width,Factor=0.9631902,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Height,Factor=0.2946429,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="Rectangle4" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                 Property=Height,Factor=3.214286,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                Property=Width,Factor=0.8650306,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Width,Factor=0.4539877,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Height,Factor=0.3125,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="Rectangle3" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                 Property=Height,Factor=2.526786,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group2, 
                Property=Width,Factor=1.07362,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Width,Factor=0.4907975,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group2,Property=Height,Factor=0.2857143,Constant=0}" /> 
         <BoxView BackgroundColor="Red" x:Name="Rectangle2" 
             RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                 Property=Height,Factor=0.1142454,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                Property=Width,Factor=0.3607595,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Width,Factor=0.4936709,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Height,Factor=0.1607898,Constant=0}" />
                 <Image Source="Rectangle.png"
                    HorizontalOptions="Center"
                    VerticalOptions="CenterAndExpand" WidthRequest="100" HeightRequest="100"   RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                 Property=Height,Factor=0.2919605,Constant=0}" 
             RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView, ElementName=Group, 
                Property=Width,Factor=0.1898734,Constant=0}" 
             RelativeLayout.WidthConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Width,Factor=0.9651899,Constant=0}" 
             RelativeLayout.HeightConstraint="{ConstraintExpression 
                 Type=RelativeToView, ElementName=Group,Property=Height,Factor=0.1650212,Constant=0}"/>
        </RelativeLayout> 
        </StackLayout>
       
    </ContentPage.Content>

**Comment by AndreiMisiukevich** [comment]
The same issue (?) not sure https://github.com/xamarin/Xamarin.Forms/issues/5204

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
