### ISSUE TITLE
[Enhancement] Translating Font details from Sketch / Invision etc

### ISSUE THREAD

**Issue by programmation** [xamarin/Xamarin.Forms#5122]
## Summary
Many App developers collaborate with a designer who uses something like Sketch to create designs. The design tools often allow fonts to be specified by "Weight" instead of just "Bold / Plain". There are many weights and some design tools have custom solutions to translate from a given weight into a font file, e.g. Invision: https://support.invisionapp.com/hc/en-us/articles/115003217203-How-does-Inspect-determine-the-font-weight-displayed-in-my-prototype-.

## API Changes

Enhance the `Font` class to include "Weight" property that functions alongside the existing "Bold / Plain" options to provide more variety. For System fonts, iOS has a simple API that works well. For non-system fonts, use a table similar to the Invision table to select a font file where it exists or fall back to "Bold / Plain" if there's no matching file.

Ideally we should be able to specify the font weight as either a number (100, 200, 300 up to 900 a la Invision) or the corresponding text name of the weight (Thin, ExtraLight, Light etc up to Heavy). A simple type conversion would be sufficient, similar to the existing Large, Small etc font sizes.

It almost makes more sense to me to have `Font` properties be attached properties in the XAML rather than direct properties of `Label`, `Editor` and `Entry`. This would enable the font API in Forms to evolve without impacting those objects each time there's a change.

## Intended Use Case
This proposal provides greater compatibility between the design language that designers use and the implementation detail the developers need. We currently have very limited font options in Forms and this proposal should eliminate the font frustration on both sides of the app development process.

**Comment by KSemenenko** [comment]
I'm working on LetterSpacing #4855

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
