### ISSUE TITLE
Xamarin automation ID binding doesn't work for controls within controls

### ISSUE THREAD

**Issue by Project4MobileDev** [xamarin/Xamarin.Forms#5128]
### Description
Since upgrading to Xamarin 3.4 we've starting using binding for our automation IDs following the fix so that automation IDs can use binding. This works well for controls on a xaml page binding to the viewmodel of that page but it seems that the automation ID binding doesn't work for controls that are used inside custom controls. Meaning if the automation ID of a control using within the xaml of the custom control is bound to a bindable property of the custom control then the automation ID doesn't appear to be set in a repl tree.

**Comment by samhouts** [comment]
Can you provide a sample project that shows this issue? Thanks!

**Comment by samhouts** [comment]
@Project4MobileDev Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Project4MobileDev** [comment]
I've created an example project but it won't let me upload the zip file because it's bigger than 10Mb. This link has the file but the link will only exist for ten days.
https://free.mailbigfile.com/93cef36299e3109fc580202171c57c76/listFiles.php

I think I might have already found the solution to the problem I'm having in this thread though, let me know if this is correct.
https://forums.xamarin.com/discussion/36883/binding-not-firing-in-some-cases

**Comment by ahmedalejo** [comment]
@Project4MobileDev in terms of size. you could create a github repo and point to it instead.
