### ISSUE TITLE
[Feedback] CS8618 errors in Code Behind

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5133]
### Description

<p>VSF_TYPE_MARKDOWNIn Visual Studio 2019, using C# 8 with Nullable Reference Types enabled, any objects declared with x:Name in a Xamarin XAML page throw the following error in Code Behind:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8618	Non-nullable field 'GoalProgressBar' is uninitialized.	DrinkFreeDays	C:\Code\DrinkFreeDays\DrinkFreeDays\DrinkFreeDays\Views\ProgressPage.xaml.cs	16	Active</p>
<a href="https://developercommunity.visualstudio.com/content/problem/438123/cs8618-errors-in-code-behind-2.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779491">original linked feedback ticket</a>.

### Source

[785543](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785543)

**Comment by samhouts** [comment]
Please attach a reproduction project that shows this issue. Thanks!

**Comment by varyamereon** [comment]
This appears to have been fixed in VS2019 Preview 4.0

**Comment by samhouts** [comment]
Thanks!!!
