### ISSUE TITLE
[Feedback] Xamarin Forms Page.DisplayActionSheet Doesn't Resize on UWP

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5134]
### Description

<p>I'm using the 
public Task&lt;string&gt; DisplayActionSheet(string title, string cancel, string destruction, params string[] buttons) method in the Xamarin.Forms.Page class. On Android and iOS the buttons and text either wrap, or resize correctly. However, on UWP, the text gets cut off if the button text is too long.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/439439/xamarin-forms-pagedisplayactionsheet-doesnt-resize.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/780285">original linked feedback ticket</a>.

### Source

[785542](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785542)

**Comment by cgollubske** [comment]
Figured out that the if the title is too long it doesn't wrap correctly as well. It wraps to two lines and cuts off the rest.
