### ISSUE TITLE
Documentation for source code structure and adding reference for each library

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#5140]
It is pretty complicated if one wants to use source code instead of nuget as reference in his solution. There are 20+ projects and if you aren't familiar with those, it is hard to know which project is for what and which project to reference on which project as reference. It will be nice to have short explanation about each project about what its for and on which project should be referenced. Basically dependencies. It can be some kind of table like [this ](https://help.syncfusion.com/xamarin/introduction/control-dependencies#sflistview)one. So we have better overview how to build our projects with source code.
  
# Difficulty : [low]

**Comment by jfversluis** [comment]
Great suggestion! I want to be more mindful with .NET MAUI on how we can make clear what the moving parts are, how they work together and how people from the community can participate. I don't think it makes much sense to still do that for Forms, but if you have any ideas around this please let me know on the .NET MAUI repo.
