### ISSUE TITLE
[Enhancement] WPF: webView update

### ISSUE THREAD

**Issue by merco** [xamarin/Xamarin.Forms#5141]
upgrade the webView on WPF (from windows 7 to windows 10) to support HTML5 based browser.
The current version seems to  be based on I.E. 6...
Why not cefSharp ?

**Comment by maxim-saplin** [comment]
Similar issues: https://github.com/xamarin/Xamarin.Forms/issues/10719

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
