### ISSUE TITLE
Null Control.AttributedText in LabelRenderer.cs crashes XF 3.4/3.5

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5149]
### Description
When a Control.AttributedText is null in LabelRenderer.cs/UpdateTextDecorations() XF 3.4/3.5 crashes
### Steps to Reproduce

1.  Set to null
2.  Crashes
3. 

### Expected Behavior
Not crash
### Actual Behavior
Crash
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  Any
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/112916/52363841-9500da00-29f8-11e9-8333-2a0b56d65ae8.png)

**Comment by andreinitescu** [comment]
This has same cause of #5003, both are fixed by my PR #5013
