### ISSUE TITLE
Bindable layout does not pass container for OnSelectTemplate

### ISSUE THREAD

**Issue by geskill** [xamarin/Xamarin.Forms#5156]
### Description
In line 184 null is passed to SelectTemplate as container value:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BindableLayout.cs#L184

Possible ways to fix:
1.
```
		View CreateItemView(object item, int index, Layout<View> layout)
		{
			return CreateItemView(item, index, _itemTemplate ?? _itemTemplateSelector?.SelectTemplate(item, layout));
		}
```
And pass layout accordingly...

2.
```
		View CreateItemView(object item, int index)
		{
			Layout<View> layout;
			if (!_layoutWeakReference.TryGetTarget(out layout))
			{
				return;
			}
			return CreateItemView(item, index, _itemTemplate ?? _itemTemplateSelector?.SelectTemplate(item, layout));
		}
```

### Steps to Reproduce

1. Create custom ItemTemplateSelector implementing OnSelectTemplate.
2. Create Stacklayout with BindableLayout and assign ItemTemplateSelector.
3. Add debugger breakpoint in OnSelectTemplate.

### Expected Behavior
Container in OnSelectTemplate should have reference to the view i.e. Stacklayout or Flexlayout 

### Actual Behavior
Container in OnSelectTemplate is null

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by andreinitescu** [comment]
Fixed by #5158
