### ISSUE TITLE
Image and text alignment / spacing is incorrect

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#5160]
@pikausp wrote on https://github.com/xamarin/Xamarin.Forms/pull/4967#issuecomment-461441806:

Hey, 

first of all, thanks for the PR! [#4967] I installed the latest preview and there are some things that are not behaving correctly (or so I believe at least).

1) The horizontal alignment of the image when `ImagePosition` is `Top` is now broken on iOS

**Before** https://i.imgur.com/yPJvFup.png
**After** https://i.imgur.com/0BiNAdL.png

I cannot verify this on a physical device right now, so I do hope it's not just a weird emulator bug.

2) There is still artificial spacing between the text and the image on Androids (iOS works as expected). There are slight changes in the spacing/sizing between versions, but none of them demonstrates the desired behavior.

**4.0-pre4 + Material Visual** https://i.imgur.com/HHxXmS5.png
**4.0-pre4 + Without Visual** https://i.imgur.com/EYefWcN.png
**3.5-rc1   + Material Visual** https://i.imgur.com/O6ioHCM.png
**3.5-rc1   + Without Visual** https://i.imgur.com/dRBNy7J.png

A workaround is to set negative spacing in `ContentLayout` i.e `ContentLayout="Top, -40"`.

**Comment by mattleibow** [comment]
I am having a look at this and I just want to mention that the Material and non-Material should not be exactly the same. We have taken the opportunity with Material to fix several layout/calculation errors that would otherwise be a breaking change for the existing visual. The aim of Material is that the values set would result in (almost) exactly the same result on both iOS and Android.

**Comment by pikausp** [comment]
@mattleibow I am aware the look is not supposed to be identical, just wanted to provide as much information as possible.

**Comment by mattleibow** [comment]
Ah, thanks! Just creating a sample app now to see what I can get.

**Comment by pikausp** [comment]
Unless I missed something only the iOS layout issues were fixed. Should I create a separate issue for the Android spacing problems? https://i.imgur.com/27QerB4.png

**Comment by samhouts** [comment]
@pikausp Yes, please! That'll help us track it better. Thanks!
