### ISSUE TITLE
  .create-nuget.bat creates corrupted nuget package

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#5165]
It is not possible to create local nuget package using .create-nuget.bat. Nuget package is created indeed but once it is installed, it doesnt work. it is obviously corrupted. I get errors as below

`9.9.5\lib\MonoAndroid90\FormsViewGroup.dll ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll)
`
![image](https://user-images.githubusercontent.com/10422347/52459007-f1800880-2b62-11e9-9bec-dee0bac77e8f.png)

**Comment by PureWeen** [comment]
we will probably use cake going forward for this one if you want to try it out here
https://github.com/xamarin/Xamarin.Forms/tree/cake

Here's some details on running
https://github.com/xamarin/Xamarin.Forms/pull/5074


if you want to try creating a nuget from that branch

**Comment by kingces95** [comment]
Yeah, that's not the official way to create nuget packages. The official way is tied up in our CI system. That bat file exists so I can test reproductions and provide directions for customers to test fixes. I fix it as I go.. If you send a reproduction of what you're doing I'll fix it for you but it'll prob break the next time things change.

At the end of the day, all it does is build stuff and calls nuget pack. The options specify what to subset of the product to build. Everything not built is stubbed with empty files that will throw exceptions if they're loaded.
