### ISSUE TITLE
[Core] Incorrect increments in Stepper

### ISSUE THREAD

**Issue by paymicro** [xamarin/Xamarin.Forms#5168]
### Description

Stepper control with a small increment may sets incorrect value.

### Steps to Reproduce

1. run Control Gallery > Stepper Gallery Legasy
2. click 3 times on latest `+` button
3. click 3 times on `-` button

### Expected Behavior

Value should be the same as it was originally = 0

### Actual Behavior

Value = 1.38777878078145E-17

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![screenshot_21](https://user-images.githubusercontent.com/27482193/52468181-f495eb80-2b98-11e9-8704-26fafb25d4e0.png)

**Comment by CliffAgius** [comment]
I have picked this picked this one up as I need it fixed for a project.  I have a solution working but need to just format and submit the PR now.
