### ISSUE TITLE
[Enhancement] Change NavigationPage back button color on Android

### ISSUE THREAD

**Issue by bares43** [xamarin/Xamarin.Forms#5177]
## Summary
I cannot change NavigationPage back button color on Android. On iOS color of back button is the same as color of text - so I can change it using BarTextColor property. This is not working on Android and I believe that this should behave the same. For now the only solution is to use custom renderer.

I think that it should be changed somewhere here https://github.com/xamarin/Xamarin.Forms/blob/7cc9a282bdeb76405c793574ebe0d096072f4228/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L935 but I'm unable do it myself.

**Comment by xyfoo** [comment]
Hi @ravinderjangra , any update on the PR?

**Comment by ravinderjangra** [comment]
hey @xyfoo, I checked the PR and it's labelled `inactive`. I think @samhouts can give an update on that.

**Comment by samhouts** [comment]
It's under review. Thanks!
