### ISSUE TITLE
Building 3.5.0 fails on MonoAndroid81

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5178]
### Description
running **.create-nuget.bat droidios** after Visual Studio 2017 does a full Solution build (any cpu) on **3.5.0** results in the error:

> 
> 'msbuild' is not recognized as an internal or external command,
> operable program or batch file.
> 'msbuild' is not recognized as an internal or external command,
> operable program or batch file.
> Attempting to build package from 'Xamarin.Forms.nuspec'.
> Could not find a part of the path 'e:\GitHub\Xamarin.Forms\Xamarin.Forms.Platform.Android\bin\debug\MonoAndroid81'.

**Doing the same under 3.4.0 works fine and a nuget package is made that works.**

### Steps to Reproduce

1. Delete all repo folders locally
2. Use the GitHub client to get the latest
3. Switch to 3.5.0 branch
4. Open VS2017 => Xamarin.Forms.sln
5. Switch to Any CPU, build the solution
6. Run **.create-nuget.bat droidios**

### Expected Behavior

A nuget package created

### Actual Behavior
> 'msbuild' is not recognized as an internal or external command,
> operable program or batch file.
> 'msbuild' is not recognized as an internal or external command,
> operable program or batch file.
> Attempting to build package from 'Xamarin.Forms.nuspec'.
> Could not find a part of the path 'e:\GitHub\Xamarin.Forms\Xamarin.Forms.Platform.Android\bin\debug\MonoAndroid81'.

### Basic Information

Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise
 
 
Add New File   3.5.134
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.60913.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

 

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CreateUnitTestBoilerplateCommand Extension   1.0
CreateUnitTestBoilerplateCommand Visual Studio Extension Detailed Info

CSS Tools   1.1.23
Provides additional features to the CSS editor in Visual Studio.

Editor Enhancements   1.0.30
Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

File Nesting   2.6.85
Automatically nest files based on file name and enables developers to nest and unnest any file manually

GitHub.VisualStudio   2.7.1.6591
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

HTML Tools   1.0.3
Productivity tools for the HTML editor

IntelliCode Extension   1.0
IntelliCode Extension

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

JetBrains ReSharper Ultimate 2018.3.2   Build 183.0.20190124.112722
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Markdown Editor   1.12.236
A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.1.218
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

OzCode   1.0
Your road to Magical Debugging. http://www.oz-code.com

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

Package Installer   2.0.103
Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

Package Security Alerts   1.0.22
Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

Project File Tools   1.0.1
Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61901.03220
Microsoft SQL Server Data Tools

 
TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

 

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Web Compiler   1.12.394
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2017   2.0.44
The easiest way to set up Visual Studio for the ultimate web development experience. Requires Visual Studio 2017 Update 8 or newer

Xamarin   4.12.3.79 (d15-9@260fa6a34)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Live Reload   0.3.27 (remotes/origin/dev@207abf7)
Provides live reload capabilities for Xamarin XAML.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Screenshots

 
![image](https://user-images.githubusercontent.com/112916/52509286-6deb0980-2bac-11e9-96bc-c815686b0e9f.png)

**Comment by jamesmontemagno** [comment]
I think now that our path is just 81 and not MonoAndroid81

**Comment by PureWeen** [comment]
Duplicate of 
https://github.com/xamarin/Xamarin.Forms/issues/5165

We needed to multitarget Android and I thought Chris had updated that bat file for it but seems it's still not quite working

Once VS Mac has more built in multi targeting support we can make it less awkward

You can also do this from the commandline to build a nuget
```
msbuild Xamarin.Forms.sln  /p:CreateAllAndroidTargets=true
H:\Tools\nuget.exe pack .nuspec\Xamarin.Forms.nuspec -properties configuration=debug;platform=anycpu -Version 9.9.9-something
```

I have a PR for a cake script which should make this more resilient in the future
https://github.com/xamarin/Xamarin.Forms/pull/5074
