### ISSUE TITLE
[Android] ListView grouping broken with 3.5.0

### ISSUE THREAD

**Issue by Urmeli0815** [xamarin/Xamarin.Forms#5184]
### Description
I have a ListView with grouping enabled. After updating to Xamarin.Forms 3.5.0 the groups & the entries within the groups get mixed up as soon as you start to scroll.

### Steps to Reproduce

1. Have a page with a ListView with IsGroupEnabled="true"
2. Bind entries to ListView
3. Start scrolling the list

### Expected Behavior
ListView keeps order of groups and the entries within each group

### Actual Behavior
Groups and the entries within get mixed up. When a misplaced entry is selected it gets its correct value.

### Basic Information

- Version with issue: Xamarin.Forms 3.5.0.129452
- Last known good version: Xamarin.Forms 3.4.0.1029999
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 28.0.0.1

### Screenshots

Screenshot from a small test project. The ListView is bound to a list of 20 groups where every group contains 5 entries.
![grafik](https://user-images.githubusercontent.com/7428276/52519908-0d6ad380-2c63-11e9-8a34-1df2b962babf.png)

Here a recording which also displays the behaviour when selecting an item.
[Recording.zip](https://github.com/xamarin/Xamarin.Forms/files/2848696/Recording.zip)

### Reproduction Link

Source to test project:
[ListViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/2847731/ListViewBug.zip)

**Comment by samhouts** [comment]
Looks like it happens without grouping, too. See #5200

**Comment by kingces95** [comment]
> commit bf0733129dda78349c14d7cb6ae39cd61ebe2288 (HEAD)
Author: Pavel Yakovlev <v-payako@microsoft.com>
Date:   Tue Jan 29 06:29:18 2019 +0300
    [Android] fixes issue content set after an await is not visible (#4861)
    * [Android] fixes issue content set after an await is not visible
    * [Android] refactoring. Fixes frame inside frame does not resize after visibility changed.
    * - add on-screen description to 1332 test
    * - add 1760 uitest uses StackLayout
    * fix autotest

**Comment by samhouts** [comment]
fixed by #5245
