### ISSUE TITLE
[UWP] Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasImageSource'.

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#5188]
### Description
Application is crashing on UWP with following exception when updated to latest Xamarin Forms 
Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasImageSource'
Not reproducible on Android

### Steps to Reproduce

Run my application with updated Xamarin Forms, yeah i know that not good steps to reproduce but don't know how to create reproducible sample.

### Basic Information

- Version with issue: 4.0.1.102444
- Last known good version: XF 3.4
- IDE: VS 2015
- Platform Target Frameworks:
  - Android: 8.1
  - UWP:  6.2.2
- Android Support Library Version:
- Nuget Packages:
- Affected Devices: Windows 10 Laptop

### Screenshots

![image](https://user-images.githubusercontent.com/3065454/52525255-2006fc00-2ca7-11e9-8f53-feb919cb4d81.png)

### Reproduction Link

I was not able to reproduce it.

**Comment by samhouts** [comment]
Try adding a reference to the Win2D.uwp nuget package. Thanks!

**Comment by toomasz** [comment]
@samhouts Thanks for the tip, i have installed that package but now im getting another exception:

```
{System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Xamarin.Forms.Platform.UWP.TaskExtensions.<>c.<WatchForError>b__2_1(Object e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()}
```

Not sure if thats releated

**Comment by samhouts** [comment]
@toomasz What version of UWP are you targetting?

**Comment by toomasz** [comment]
@samhouts 6.2.2, but Im not sure. Take a look at my nuget:

![image](https://user-images.githubusercontent.com/3065454/52742874-10562300-2fd9-11e9-8587-f8bb37048240.png)

**Comment by samhouts** [comment]
@toomasz Right click on the UWP project and go to Properties, and look at the application tab. What does it say you're targetting? 
![image](https://user-images.githubusercontent.com/7827070/52743381-b92b6080-2f8e-11e9-973f-2c7d58cb3505.png)

**Comment by toomasz** [comment]
@samhouts  Then I'm targetting Windows 10 Fall Creators Update (10.0; Build 16299) as well

**Comment by dansiegel** [comment]
@samhouts I'm actually running into this same issue as well on a project using the latest 3.6 preview. I'm targeting 17134 with a min version 16299.

When I install the Win2D.uwp package I get the following exception.

```
The "Win2DIsPlatformTooOld" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at InlineCode.Win2DIsPlatformTooOld.Execute() in c:\Users\DanSiegel\AppData\Local\Temp\sdnq0j0q.0.cs:line 71
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AwesomeApp.UWP	C:\Users\DanSiegel\.nuget\packages\win2d.uwp\1.23.0\build\Win2D.common.targets	33	
```

**Comment by Gravemind2401** [comment]
I just had this issue after updating from XF 3.5 SR1 to XF 3.6 RC4.
The Win2D package was not installed automatically as part of updating to XF 3.6, is this expected?
After installing the Win2D nuget package I found that it targets UWP 17134 so I also had to update my targets in the project file.
Like @toomasz I was also targeting UWP 16299, but changing the target to 17763 (min version set to 17134) this resolved the issue.

**Comment by tualatin** [comment]
I upgrade Xamarin.Forms 3.5.xx to 3.6.xx since I get the same error message for my UWP project.

**Comment by MagicAndre1981** [comment]
I have the same issue:

![image](https://user-images.githubusercontent.com/8274816/53865905-940b9a00-3ff0-11e9-8f5d-c0d6ab881b06.png)

So the NuGet update to [Xamarin.Forms 3.6.0.220655](https://github.com/xamarin/Xamarin.Forms/issues/5468) was a mistake?

**Comment by MagicAndre1981** [comment]
@toomasz @dansiegel change MinVersion to 17134 or add `<DisableWin2DPlatformCheck>true</DisableWin2DPlatformCheck>` to your csproj.

I had the same issue. 

@samhouts was the Xamarin.Forms 3.6.0.220655 release a mistake?

**Comment by MagicAndre1981** [comment]
I've added the Win2D.uwp nuget package and the app still runs on Build 16299 with <DisableWin2DPlatformCheck>true</DisableWin2DPlatformCheck> added to csproj to skip the 17134 minimum version.

**Comment by msc4266** [comment]
Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasImageSource'.
Same issue here, introduced with XForms 3.6. - doesn't work.
Going back to XForms 3.5.0.169047, clean solution, build, fine.
It is realted to ImageSourceExtension{
```
   string resourceName = thisAssembly.GetName().Name + "." + this.Source;
            var imageSource = ImageSource.FromResource(resourceName); 
```
used in a blank app:
 ```
<ContentPage.Content>
        <StackLayout>
            <Label Text="Welcome to Xamarin.Forms!"/>
            <Image Source="{blank:ImageResource logo.png}"></Image>
        </StackLayout>
    </ContentPage.Content>
```

**Comment by anders9ustafsson** [comment]
@Gravemind2401 @MagicAndre1981 An alternative to ignoring the Windows SDK version check is to install an earlier version of the *win2d.uwp* package. 1.22.0 does not require Windows SDK to be at build 17134 or higher.

**Comment by AlexF12004Roma** [comment]
Same Error Here, crash in 3.6 not in 3.5.
Image Source seems the problem

**Comment by MagicAndre1981** [comment]
@AlexF12004Roma 

install [win2d.uwp](https://www.nuget.org/packages/Win2D.uwp/1.23.0) package and add

`<DisableWin2DPlatformCheck>true</DisableWin2DPlatformCheck>` to your csproj.

**Comment by amirvenus** [comment]
I had to install the nuger package and chage my target version. 
I hope this issue is addresses asap.

**Comment by hinojosachapel** [comment]
Here is another one suffering the same issue. In my case, installing win2d.uwp without doing anything else, solved it. Target version: 1809. Min version: Fall Creators Update.

**Comment by mnasers** [comment]
We also experienced this issue when updating to V3.6. Installing win2d.uwp V1.22 seems to have resolved the issue.

**Comment by nickrandolph** [comment]
If Win2D.uwp is a dependency, why is it not added as a UWP dependency for XF? 
@davidortinau this is the type of issue I keep pointing out to you and the XF team. And I'm commenting because I ran into exact same issue after upgrading my OSS project to v3.6; had to google the answer; and now disappointed that this issue is closed.
There are a bunch of status changes but no post back here as to why this couldn't be fixed in v3.6?

**Comment by samhouts** [comment]
@nickrandolph It will be fixed in 3.6.0 SR1. https://github.com/xamarin/Xamarin.Forms/pull/5475 resolves the issue, and it's targeting the 3.6.0 branch. Thanks!

**Comment by nickrandolph** [comment]
@samhouts thanks for that - it's really useful when closing issues like this if the team could be clearer about why it's closed. Following the change of status above it's really hard to see that this issue had actually been resolved for both v4 and v3.6 as the last status change was in relation to v4. I'd completely missed the reference to #5475 as it was much earlier in the history.

**Comment by dotMorten** [comment]
Also why was this dependency added? There's no precedence like this for adding 3rd party dependencies here and forcing it on everyone.

**Comment by samhouts** [comment]
@nickrandolph It says

**Comment by samhouts** [comment]
@dotMorten It's not 3rd party. It's Microsoft. https://www.nuget.org/packages/Win2D.uwp ;)

It was added to support FontImageSource on UWP. https://github.com/xamarin/Xamarin.Forms/pull/4817

**Comment by nickrandolph** [comment]
@samhouts it wasn't originally clear from the commit as the branch history wasn't obvious. It's clear now that the SR release has gone out. Thanks for the quick fix on this one.

**Comment by MagicAndre1981** [comment]
@nickrandolph it is now fixed with [Xamarin.Forms 3.6.0.264807 (3.6.0 Service Release 1)](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/3.6/3.6.0-sr1#tuesday-march-19-2019---xamarinforms-360264807-360-service-release-1)

**Comment by dotMorten** [comment]
This dependency breaks ARM64 support, as that isn't part of the Win2D package.

**Comment by MagicAndre1981** [comment]
I still notice one small thing. When I capture .net ETW data for provider `Microsoft-Windows-DotNETRuntime` with Exception keyword, I see a `System.IO.FileNotFoundException` `"Could not load file or assembly 'Microsoft.Graphics.Canvas, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden."` but the app works and I see the `Microsoft.Graphics.Canvas.dll` next to the app in deployment folder (%localappdata%\DeploymentFiles\APPNAMEVS.Debug_x86USERNAME).


Line # | Provider Name | Task Name | Process | Opcode Name | Time (s) | Stack | Event Name | Cpu | Id | ThreadId | Field 1 | Field 2 | Field 3 | Field 4 | Field 5 | Field 6 | Field 7 | Field 8 | Field 9 | Field 10 | Field 11 | Field 12 | Field 13 | Field 14 | Field 15 | Field 16 | Count | Time (s)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 |   |   |   |   | 87,724657700 | [Root] |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
8 |   |   |   |   | 87,724657700 | ntdll.dll!_RtlUserThreadStart |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
9 |   |   |   |   | 87,724657700 | ntdll.dll!__RtlUserThreadStart |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
10 |   |   |   |   | 87,724657700 | kernel32.dll!BaseThreadInitThunk |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
11 |   |   |   |   | 87,724657700 | SHCore.dll!_WrapperThreadProc |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
12 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!<lambda_a740d69e4550265529206848c8e72a27>::<lambda_invoker_stdcall> |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
13 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationViewAgileContainer::WaitForViewReady |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
14 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!Event::WaitAndProcessEvents |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
15 |   |   |   |   | 87,724657700 | Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessages |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
16 |   |   |   |   | 87,724657700 | Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
17 |   |   |   |   | 87,724657700 | Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
18 |   |   |   |   | 87,724657700 | combase.dll!ModernSTAWaitContext::HandlePriorityEventsFromMessagePump |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
19 |   |   |   |   | 87,724657700 | combase.dll!ModernSTAState::HandleMessage |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
20 |   |   |   |   | 87,724657700 | combase.dll!ThreadDispatch |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
21 |   |   |   |   | 87,724657700 | combase.dll!ComInvokeWithLockAndIPID |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
22 |   |   |   |   | 87,724657700 | combase.dll!AppInvoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
23 |   |   |   |   | 87,724657700 | combase.dll!ASTAInvokeInApartment |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
24 |   |   |   |   | 87,724657700 | combase.dll!ServerCall::ContextInvoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
25 |   |   |   |   | 87,724657700 | combase.dll!DefaultStubInvoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
26 |   |   |   |   | 87,724657700 | combase.dll!ObjectMethodExceptionHandlingAction<<lambda_ee1df801181086a03fa4f8f75bd5617f> > |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
27 |   |   |   |   | 87,724657700 | rpcrt4.dll!CStdStubBuffer_Invoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
28 |   |   |   |   | 87,724657700 | combase.dll!CStdStubBuffer_Invoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
29 |   |   |   |   | 87,724657700 | rpcrt4.dll!NdrStubCall2 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
30 |   |   |   |   | 87,724657700 | rpcrt4.dll!Invoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
31 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Activate |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
32 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!Microsoft::WRL::EventSource<Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>,Microsoft::WRL::InvokeModeOptions<-2> >::DoInvoke<<lambda_5b8ed61dc30875efd1faa9507c79d8c2> > |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
33 |   |   |   |   | 87,724657700 | twinapi.appcore.dll!Microsoft::WRL::InvokeTraits<-2>::InvokeDelegates<<lambda_5b8ed61dc30875efd1faa9507c79d8c2>,Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *> > |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
34 |   |   |   |   | 87,724657700 | Windows.UI.Xaml.dll!Microsoft::WRL::Details::DelegateArgTraits<long (__stdcall Windows::Foundation::ITypedEventHandler_impl<Windows::Foundation::Internal::AggregateType<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Core::ICoreApplicationView *>,Windows::ApplicationModel::Activation::IActivatedEventArgs *>::*)(Windows::ApplicationModel::Core::ICoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *)>::DelegateInvokeHelper<Windows::Foundation::ITypedEventHandler<Windows::ApplicationModel::Core::CoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>,<lambda_8cb6a44a772cf529a3569069a4a24e7d>,-1,Windows::ApplicationModel::Core::ICoreApplicationView *,Windows::ApplicationModel::Activation::IActivatedEventArgs *>::Invoke |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
35 |   |   |   |   | 87,724657700 | Windows.UI.Xaml.dll!DirectUI::FrameworkView::OnActivated |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
36 |   |   |   |   | 87,724657700 | Windows.UI.Xaml.dll!DirectUI::FrameworkApplicationGenerated::OnLaunchedProtected |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
37 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
38 |   |   |   |   | 87,724657700 | coreclr.dll!COMToCLRDispatchHelper |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
39 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
40 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
41 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
42 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
43 |   |   |   |   | 87,724657700 | ?!? |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
44 |   |   |   |   | 87,724657700 | System.Private.CoreLib.dll!System.Reflection.Assembly.Load(System.Reflection.AssemblyName)$##60031CF |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
45 |   |   |   |   | 87,724657700 | System.Private.CoreLib.dll!System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, IntPtr)$##6003428 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
46 |   |   |   |   | 87,724657700 | coreclr.dll!AssemblyNative::Load |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
47 |   |   |   |   | 87,724657700 | coreclr.dll!UnwindAndContinueRethrowHelperAfterCatch |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
48 |   |   |   |   | 87,724657700 | coreclr.dll!RaiseTheExceptionInternalOnly |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
49 |   |   |   |   | 87,724657700 | ntdll.dll!KiUserExceptionDispatcher |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
50 |   |   |   |   | 87,724657700 | ntdll.dll!ExecuteHandler@20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
51 |   |   |   |   | 87,724657700 | ntdll.dll!ExecuteHandler2@20 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
52 |   |   |   |   | 87,724657700 | coreclr.dll!COMPlusFrameHandlerRevCom |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
53 |   |   |   |   | 87,724657700 | coreclr.dll!COMPlusFrameHandler |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
54 |   |   |   |   | 87,724657700 | coreclr.dll!CPFH_FirstPassHandler |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
55 |   |   |   |   | 87,724657700 | coreclr.dll!CPFH_RealFirstPassHandler |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
56 |   |   |   |   | 87,724657700 | coreclr.dll!LookForHandler |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
57 |   |   |   |   | 87,724657700 | coreclr.dll!Thread::StackWalkFrames |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
58 |   |   |   |   | 87,724657700 | coreclr.dll!Thread::StackWalkFramesEx |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
59 |   |   |   |   | 87,724657700 | coreclr.dll!COMPlusThrowCallback |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
60 |   |   |   |   | 87,724657700 | coreclr.dll!ETW::ExceptionLog::ExceptionThrown |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
61 |   |   |   |   | 87,724657700 | coreclr.dll!McTemplateCoU0zzpqhh |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
62 |   |   |   |   | 87,724657700 | coreclr.dll!McGenEventWriteUM |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
63 |   |   |   |   | 87,724657700 | ntdll.dll!EtwEventWrite |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
64 |   |   |   |   | 87,724657700 | ntdll.dll!EtwpEventWriteFull |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  
65 |   |   |   |   | 87,724657700 | ntdll.dll!ZwTraceEvent |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1 |  



Anyone else here who uses ETW to trace UWP apps and has this too?
