### ISSUE TITLE
[Android] Bindeable FlexLayout in a ListView not visible in some cells on 3.5.0.129452

### ISSUE THREAD

**Issue by irongut** [xamarin/Xamarin.Forms#5190]
### Description

My app has a screen that contains a ListView, in the list cells I'm using a new Bindable FlexLayout to display a variable number of strings. Using Forms v3.5.0.62956-pre2 this was working but using v3.5.0.129452 the FlexLayout is sometimes not visible on Android. The ItemSource does have content and space is left for the FlexLayout but it is not visible. FlexLayouts in different cells will appear / dissappear as the ListView is scrolled.

A variable number of items bound to the FlexLayout is important, the bug does not happen if there are always the same number of items.

I've enabled FastRenderers in the sample project because my app has it enabled. I don't know if that is a contributing factor.

I've also tested this on UWP and it worked as expected. I can't test iOS.

### Steps to Reproduce

1. Create a new Forms project and update to v3.5.0.129452.
2. Add a ListView to MainPage with cells that contain a FlexLayout bound to a collection.
3. Populate the list with items that have a vaiable number of items in the FlexLayout's collection.
4. Run the app on Android and scroll the ListView up and down.

### Expected Behavior

All the cells in the ListView show a variable number of strings contained in a FlexLayout.

### Actual Behavior

On Android some ListView cells do not display the strings. Which cells display strings is random and changes as the ListView is scrolled.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.5.0.62956-pre2 (not tested with pre3)
- IDE: VS 2017 v15.9.6
- Platform Target Frameworks:
  - Android: Min 4.4, Target 9.0
  - UWP:  16299
- Android Support Library Version: 28.0.0.1
- Affected Devices: Galaxy S6 Edge (Android 7.0) + Android Emulator

### Screenshots

![screenshot_20190210-000628](https://user-images.githubusercontent.com/27953302/52527917-c44d6a80-2cc8-11e9-96e4-83ea7bfd4626.png)

### Reproduction Link

[irongut/XF35BindFlexLayoutIssue](https://github.com/irongut/XF35BindFlexLayoutIssue)

**Comment by KSemenenko** [comment]
Are you using optimizations for ListView? Like RecycleElementAnd DataTemplate?

**Comment by irongut** [comment]
@KSemenenko A quick look at the sample project would have answered those questions...

I'm not using RecycleElement. In my app my lists are small and RecycleElement causes a pop-in like effect with svg images in the cells.

I am using DataTemplates but this should not be an issue, the exact same code was working on 3.5-pre2.

**Comment by irongut** [comment]
Upgrading to the v3.5.0.169047 service release has fixed this issue. Both the test app for this issue & my actual app are now working as expected. :)
