### ISSUE TITLE
TableView Height

### ISSUE THREAD

**Issue by zopagaduanjr** [xamarin/Xamarin.Forms#5193]
### Description
I've set my TableView Height = 230;
I got System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by samhouts** [comment]
Hi @zopagaduanjr ! Please use the complete issue template when submitting a bug report. Can you please attach a sample project that shows this issue? Thanks!

**Comment by samhouts** [comment]
@zopagaduanjr  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
