### ISSUE TITLE
[Android] The instruction pointer of the currently executing method is not on the recorded stack

### ISSUE THREAD

**Issue by henryyue2010** [xamarin/Xamarin.Forms#5195]
### Description

I got an error when clearing the binding ObservableCollection (run myCollection.Clear()) in page's OnAppearing() method.
The following error is thrown. It stops the following process to update the ObservableCollection. And the listview which binding the collection is not updated.

Thread finished: <Thread Pool> #29[0xb6ff3bec] The instruction pointer of the currently executing method(Xamarin.Forms.BindableObject:ApplyBindings (bool,bool)) is not on the recorded stack. This is likely due to a runtime bug. 

### Steps to Reproduce

1. The first time when the ListView is rendered, no errors. Items are added to the ObservableCollection.
2. Navigate to other pages, then go back the page.  
3. The ListView is loaded again. And the above error appears.

### Expected Behavior
The collection's clear method can run without errors. 

### Actual Behavior
Error thrown.
Thread finished: <Thread Pool> #29[0xb6ff3bec] The instruction pointer of the currently executing method(Xamarin.Forms.BindableObject:ApplyBindings (bool,bool)) is not on the recorded stack. This is likely due to a runtime bug. 

### Basic Information
Microsoft Visual Studio Enterprise 2017 
Version 15.9.4
VisualStudio.15.Release/15.9.4+28307.222
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)

NuGet Package Manager   4.6.0

TypeScript Tools   15.9.20918.2001
TypeScript Tools for Microsoft Visual Studio

Xamarin   4.12.3.77 (d15-9@e3f40b477)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.13 (45a16efd4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.4.2 (HEAD/8255f42fc)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Xamarin.Forms: 3.3

Target Framework: Android 8.1

**Comment by henryyue2010** [comment]
it seems the issue can be fixed by updating XF to latest version of 3.5.

**Comment by samhouts** [comment]
@henryyue2010 Glad to hear the latest version fixed this for you! If you continue to have issues, please let us know. Thank you!
