### ISSUE TITLE
TableSection not reacting to changes when using default TableView.Root

### ISSUE THREAD

**Issue by TimLariviere** [xamarin/Xamarin.Forms#5197]
### Description

When creating a `TableView` by code, the `Root` property is already populated with a `TableRoot`.
If we reuse this `TableRoot` to add a `TableSection` with an inner `TextCell`, they all appear correctly on the UI.
But when we apply updates (like changing the text) of both the section's title and cell's text, only the cell is updated on the UI.
The section is not, while it has the correct value in its Title property.

This is not the case if we instantiate our own `TableRoot` (like we do in XAML).

Confirmed on iOS, Android and macOS.
UWP does not have this bug, but has another one.

### Steps to Reproduce

1. Create a new Xamarin.Forms app
2. Set the following content in MainPage.xaml

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TableSectionTitleIssue"
             x:Class="TableSectionTitleIssue.MainPage">

    <StackLayout>
        <Label Text="Bad" />
        <TableView x:Name="TableViewBad" Intent="Form" />
        <Label Text="Good" />
        <TableView x:Name="TableViewGood" Intent="Form" />
        <Button x:Name="Increment" Text="Increment" />
    </StackLayout>

</ContentPage>
```

3. Set the following in MainPage.xaml.cs
```csharp
using System;
using Xamarin.Forms;

namespace TableSectionTitleIssue
{
    public partial class MainPage : ContentPage
    {
        public int _count = 0;
        private TableSection _sectionBad;
        private TableSection _sectionGood;
        private TextCell _cellBad;
        private TextCell _cellGood;

        public MainPage()
        {
            InitializeComponent();

            _sectionBad = new TableSection("0");
            _sectionGood = new TableSection("0");
            _cellBad = new TextCell { Text = "0" };
            _cellGood = new TextCell { Text = "0" };

            _sectionBad.Add(_cellBad);
            TableViewBad.Root.Add(_sectionBad);

            _sectionGood.Add(_cellGood);
            TableViewGood.Root = new TableRoot { _sectionGood };

            Increment.Clicked += Increment_Clicked;
        }

        private void Increment_Clicked(object sender, EventArgs e)
        {
            _count++;

            _sectionBad.Title = _count.ToString();
            _sectionGood.Title = _count.ToString();

            _cellBad.Text = _count.ToString();
            _cellGood.Text = _count.ToString();
        }
    }
}
```

### Expected Behavior

The UI updates correctly, even when using the TableRoot created internally by Xamarin.Forms.

### Actual Behavior

Only the TextCell is updating on the UI.

### Basic Information

- Version with issue: At least 3.4.0.1008975, up to 3.5.0.129452
- Platform Target Frameworks: Android, iOS and macOS (UWP is not affected. Haven't tested others)
  - iOS:  12.0
  - Android: 8.1
  - UWP:  16299

### Screenshots

![actual behavior](https://user-images.githubusercontent.com/1197905/52438589-b1049880-2b2a-11e9-811b-80db8c340744.gif)

### Reproduction Link

https://github.com/TimLariviere/XFIssueRepros/tree/master/TableSectionTitleIssue

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
