### ISSUE TITLE
Cannot scroll webpage in WebView element on Xamarin Shell

### ISSUE THREAD

**Issue by Soul-Master** [xamarin/Xamarin.Forms#5205]
### Steps to Reproduce

1. Pull Gastropods project from Github
https://github.com/davidortinau/Gastropods.git
2. Update Xamarin Form to latest prerelease version ()
3. Replace content of `MainPage.xaml` page with single WebView element

`<WebView Source="https://www.youtube.com/" ></WebView>`

4. Build & Debug
5. After loaded, try to scroll YouTube page

### Expected Behavior
YouTube webpage should be scrolled.

### Actual Behavior
Nothing happened after scrolling.
### Basic Information

- Version with issue: 4.0.0.135214-pre4, 4.0.0.8055-pre1
- Last known good version: -
- IDE: VS 2017 15.9.6
- Platform Target Frameworks: 
  - Android: Android Pie (9.0)
- Nuget Packages:
- Affected Devices: Samsung S7 Edge (Android 8.0)
Parent: #2415

**Comment by pauldipietro** [comment]
Reproducible by modifying a Shell template in VS2019 preview.

**Comment by jannikscho** [comment]
Hello,

The problem also occurs in my project with WebView and Maps (Xamarin.Forms.GoogleMaps).
I could solve it easily by a custom ContentView. 

See below...

Shared-Project:

Create a custom ContentView:
` public class GesturelessContentView : ContentView
    {
    }`

In Xaml add the WebView to this ContentView:

`<controls:GesturelessContentView x:Name="view" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
        <WebView x:Name="webView" Source="{Binding Source}" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
    </controls:GesturelessContentView>`

Android-Project:
Create a custom ViewRenderer for this ContentView and override the "DispatchTouchEvent":

`public override bool DispatchTouchEvent(MotionEvent e)
{
            /* Switching between touch-events
            switch (e.Action)
            {
                case MotionEventActions.Down:
                case MotionEventActions.Move:
                case MotionEventActions.Up:
                    this.Parent.RequestDisallowInterceptTouchEvent(true);
                    break;
            }*/
            // For all touch-events
            this.Parent.RequestDisallowInterceptTouchEvent(true);
            return base.DispatchTouchEvent(e);
}`

my case it works as expected.

**Comment by g4mb10r** [comment]
I have this issue as well.  Please fix.

**Comment by philousb** [comment]
Hello,

Having the same issue in 4.0.0 pre 9. Will this be fixed soon ?

**Comment by jannikscho** [comment]
The problem is still there. Tested with preview 9.

**Comment by samhouts** [comment]
As a workaround, you can create a custom renderer for your `WebView` and add the following override:

```csharp
		public override bool DispatchTouchEvent(MotionEvent e)
		{
			Parent.RequestDisallowInterceptTouchEvent(true);
			return base.DispatchTouchEvent(e);
		}
```

**Comment by philousb** [comment]
It worked for me.
thx.

**Comment by wagenheimer** [comment]
> As a workaround, you can create a custom renderer for your `WebView` and add the following override:
> 
> ```cs
> 		public override bool DispatchTouchEvent(MotionEvent e)
> 		{
> 			Parent.RequestDisallowInterceptTouchEvent(true);
> 			return base.DispatchTouchEvent(e);
> 		}
> ```

Could you please explain how can I do this?

**Comment by philousb** [comment]
You have to create a custom renderer for the webview (Android, iOS)

1. create a custom webview
`using System;
using System.Collections.Generic;
using System.Text;
using Xamarin.Forms;

namespace MyNamespace
{
    public class MyWebView : WebView
    {
    }
}`

2. For each project create a custom renderer
`using Android.Content;
using Android.Views;

using Xamarin.Forms.Platform.Android;
using Xamarin.Forms;

using MyNamespace;
using MyNamespace.Droid;

[assembly: ExportRenderer(typeof(MyWebView), typeof(MyWebViewRenderer))]
namespace MyNamespace.Droid
{
    class MyWebViewRenderer : WebViewRenderer
    {
        public MyWebViewRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<WebView> e)
        {
            base.OnElementChanged(e);
        }

        public override bool DispatchTouchEvent(MotionEvent e)
        {
            Parent.RequestDisallowInterceptTouchEvent(true);
            return base.DispatchTouchEvent(e);
        }
    }
}`

**Comment by dgerding** [comment]
This is still not working for me.  I get the same "no scrolling" behavior in standard WebView and when using Xam.Plugin.Web.  This seems like a pretty big bug since webviews are common.  Help :) ?

**Comment by samhouts** [comment]
#6310

**Comment by MSiccDev** [comment]
I can confirm that the workaround works (at least for Android). Even though I would prefer it to work out of the box...

**Comment by samhouts** [comment]
closed by #7032

**Comment by jonhudson12** [comment]
@philousb - you sir deserve a medal. Works perfect. Ty!

**Comment by blndr83** [comment]
I have tested the custom renderer implementation of philousb. When i rotate the phone in landscape mode scrolling don't work always. tested on a Huawei p20 pro with android 9

**Comment by blndr83** [comment]
I have tried philousb custom webview renderer on a contentpage with a scrollview inside the scrollview a grid and in the grid at the 3 Row a webview. Without the custom renderer scrolling works only in landscape mode. With the custom renderer it works only when it is not in landscape mode. When i remove the scrollview it works with standard webview in both modes. Tested on a Huawei p20 pro with android 9

**Comment by MauriceMatekCode** [comment]
Hey there - my name is Maurice.

Weirdly this whole thing doesn't seem to work for me. 
I use the pdfjs-Library to display a local pdf-file in a WebView on Android. I am using Xamarin-Forms-Shell.

I am also using an instance of WebView with a CustomRenderer linked to it as mentioned in this thread before. Inside the Custom Renderer for Android I have the following code to fix the scrolling bug:

`        public override bool DispatchTouchEvent(MotionEvent e)
        {
            Parent.RequestDisallowInterceptTouchEvent(true);
            return base.DispatchTouchEvent(e);
        }
`

the problem is: scrolling still does not work. Sometimes although, when using two fingers and scrolling fast it zooms a little and scrolls a bit. 

I really don't know what I could do about that. Which is quite frustrating.

Thanks for any help
Maurice

**Comment by MauriceMatekCode** [comment]
> Hey there - my name is Maurice.
> 
> Weirdly this whole thing doesn't seem to work for me.
> I use the pdfjs-Library to display a local pdf-file in a WebView on Android. I am using Xamarin-Forms-Shell.
> 
> I am also using an instance of WebView with a CustomRenderer linked to it as mentioned in this thread before. Inside the Custom Renderer for Android I have the following code to fix the scrolling bug:
> 
> ` public override bool DispatchTouchEvent(MotionEvent e) { Parent.RequestDisallowInterceptTouchEvent(true); return base.DispatchTouchEvent(e); }`
> 
> the problem is: scrolling still does not work. Sometimes although, when using two fingers and scrolling fast it zooms a little and scrolls a bit.
> 
> I really don't know what I could do about that. Which is quite frustrating.
> 
> Thanks for any help
> Maurice

I was able to fix the issue by using Xamarin.Forms 5.0 and the newest prerelease of pdfjs.

Thanks anyway ^^

**Comment by scott-hooper-hordernit** [comment]
> You have to create a custom renderer for the webview (Android, iOS)
> 
> 1. create a custom webview
> 
> ```cs
> using System;
> using System.Collections.Generic;
> using System.Text;
> using Xamarin.Forms;
> 
> namespace MyNamespace
> {
>     public class MyWebView : WebView
>     {
>     }
> }
> ```
> 
> 1. For each project create a custom renderer
> 
> ```cs
> using Android.Content;
> using Android.Views;
> 
> using Xamarin.Forms.Platform.Android;
> using Xamarin.Forms;
> 
> using MyNamespace;
> using MyNamespace.Droid;
> 
> [assembly: ExportRenderer(typeof(MyWebView), typeof(MyWebViewRenderer))]
> namespace MyNamespace.Droid
> {
>     class MyWebViewRenderer : WebViewRenderer
>     {
>         public MyWebViewRenderer(Context context) : base(context)
>         {
>         }
> 
>         protected override void OnElementChanged(ElementChangedEventArgs<WebView> e)
>         {
>             base.OnElementChanged(e);
>         }
> 
>         public override bool DispatchTouchEvent(MotionEvent e)
>         {
>             Parent.RequestDisallowInterceptTouchEvent(true);
>             return base.DispatchTouchEvent(e);
>         }
>     }
> }
> ```

Did you have an iOS version of this custom renderer? I don't think iOS handles touch events like this.
