### ISSUE TITLE
[Shell,iOS] Tab unselected color incorrectly mapped

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5208]
### Description

This sets the tab item color:
```
<Setter Property="Shell.ShellUnselectedColor" Value="Red" />
```

This does not:

```
<Setter Property="Shell.ShellTabBarUnselectedColor" Value="#999999"/>
```

### Expected Behavior

`ShellTabBarUnselectedColor` sets my tab unselected color, not `ShellUnselectedColor`.

### Basic Information

- Version with issue: 4.0.1 Nightly

### Screenshots

<img width="1128" alt="screenshot 2019-02-11 20 41 22" src="https://user-images.githubusercontent.com/41873/52607999-195ebd00-2e3e-11e9-922b-91fa2d9ef011.png">

Parent: #2415

**Comment by davidortinau** [comment]
Looks like the `ShellUnselectedColor` overrides `ShellTabBarUnselectedColor`. I don't see why that  would be the case if I specified the latter.

<img width="479" alt="screenshot 2019-02-11 20 48 39" src="https://user-images.githubusercontent.com/41873/52608156-99852280-2e3e-11e9-838b-88965f56178c.png">

**Comment by rmarinho** [comment]
this seems be fixed @davidortinau , can you confirm? 
```
<Style x:Key="BaseStyle" TargetType="Element">
		<Setter Property="Shell.ShellBackgroundColor" Value="#455A64" />
		<Setter Property="Shell.ShellForegroundColor" Value="White" />
		<Setter Property="Shell.ShellTitleColor" Value="White" />
		<Setter Property="Shell.ShellDisabledColor" Value="#B4FFFFFF" />
		<Setter Property="Shell.ShellUnselectedColor" Value="#95FFFFFF" />
</Style>
<Style x:Key="GreenShell" TargetType="Element" BasedOn="{StaticResource BaseStyle}">
	    <Setter Property="Shell.ShellBackgroundColor" Value="#689F39" />
            <Setter Property="Shell.ShellTabBarUnselectedColor" Value="Red" />
            <Setter Property="Shell.ShellTabBarTitleColor" Value="Blue" />
</Style>
```
![Simulator Screen Shot - iPhone XS Max - 2019-03-29 at 18 03 33](https://user-images.githubusercontent.com/1235097/55253355-06b51180-524d-11e9-8002-e60175859019.png)

**Comment by rmarinho** [comment]
Should be fixed on pre8.
