### ISSUE TITLE
iOS - SIGABRT: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

### ISSUE THREAD

**Issue by imuller** [xamarin/Xamarin.Forms#5214]
### Description
When building in release mode on a real device the app crashes on specific tasks. For example when opening a new page. This is not on all devices and only in release mode with linker behavior set to "Link Framework SDKs Only".

### Steps to Reproduce

1. Xamarin.Forms project for iOS with link behavior set to "Link Framework SDKs Only"
2. When opening a screen the app crashes

### Expected Behavior
App not crashing

### Actual Behavior
App crashes with error: SIGABRT: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.4.0.1029999
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  12.1.4
- Nuget Packages: netstandard
- Affected Devices: iPad Mini, iPad Pro

**Comment by imuller** [comment]
Workaround downgrade to Xamarin.Forms 3.4.0.1029999

**Comment by imuller** [comment]
Got some more information:

When using converters in xaml views the app crashes with this error. For example i have  a converter like this:

`public class InverseBoolConverter : IValueConverter, IMarkupExtension
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return !((bool)value);
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            return value;
        }

        public object ProvideValue(IServiceProvider serviceProvider)
        {
            return this;
        }
    }`

Calling this converter from my view like this:

` xmlns:converters="clr-namespace:Helpers.Converters"`

` IsEnabled="{Binding Confirmed, Converter={converters:InverseBoolConverter}}"`

Then the app crashes. When i remove only the "IsEnabled=....." with the converter inside, the app won't crash.

**Comment by imuller** [comment]
Found a solution for the problem. It was still existing on Xamarin.Forms 3.6.
I had to use the "Resources" inside my XAML pages to prevent a crash on a few devices. This crash did not occur on all iOS devices.

After adding this code to my XAML pages the crash was gone.

`<ContentPage.Resources>
        <ResourceDictionary>
            <converters:InverseBoolConverter x:Key="InverseBoolConverter" />
        </ResourceDictionary>
    </ContentPage.Resources>`

For calling the converters i needed to use this line of code for example:

`{Binding IsVisible, Converter={StaticResource InverseBoolConverter}}`

**Comment by idzikovski** [comment]
I still encountered this issue in Xamarin.Forms versions higher than 5. Seems to me that the linker is not perfect and sometimes it omits some stuff that is actually used.. I solved this by skipping the "netstandard" assembly for linking by using the custom mtouch arguments ex:

```
<MtouchExtraArgs>--linkskip=netstandard</MtouchExtraArgs>
```
