### ISSUE TITLE
[iOS] Can't override PopViewController in custom NavigationRenderer

### ISSUE THREAD

**Issue by lviolin** [xamarin/Xamarin.Forms#5215]
### Description
Extending Xamarin.Forms/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs to override PopViewController has no effect.

PopViewController method is overridden in NavigationRenderer itself, but the calling method OnPopViewAsync uses the one in the parent class:
poppedViewController = **base**.PopViewController(animated);

### Steps to Reproduce
1. extend NavigationRenderer in the iOS project
2. override PushViewController and PopViewController methods
3. while PushViewController works good, PopViewController never triggers in the derived class (nor in NavigationRenderer itself)

### Expected Behavior
PopViewController method overridden in the derived class gets called

### Actual Behavior
PopViewController method overriden never gets called

### Basic Information

- Version with issue: 3.4, 3.5
- Last known good version: Unknown
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices: all

**Comment by samhouts** [comment]
@lviolin Can you provide a sample project that shows exactly what you're trying to do? Thank you!

**Comment by samhouts** [comment]
@lviolin  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
