### ISSUE TITLE
ListView Items MacOS Rendered in increasingly disparate heights

### ISSUE THREAD

**Issue by Xamtastic** [xamarin/Xamarin.Forms#5217]
### Description
Rendering items in ListView in Master-Detail pattern under MacOS yields spurious results.

(I accept that MacOS is still in preview as per here: https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status#status )
### Steps to Reproduce
There are two circumstances that I have observed problems:

1. Wiring the Default Master-Detail Xamarin Forms template solution to a MacOS head project
2. Creating my own datasource and utilising a DataTemplateSelector, in a Master-Detail pattern solution.

### Expected Behavior

1. For the first case, the ListView on the Default Master-Detail page works in iOS and Android and should work on MacOS.
2. For the second case, I'd expect the ListView's DataTemplateSelector to cause the individual items to be rendered according to their size.

### Actual Behavior

1. For the first case the ListView renders on MacOS in an even format however the top item is rendered too high and consequently half of the first list item is obscured by the top bar. You can see this in the image here: https://forums.xamarin.com/discussion/comment/364255
2. For the second case, items are rendered with an increasing gap, you can see this in the image below, I have coloured the DataTemplates so that you can easily see which is which.

### Basic Information

- Version with issue:

Xamarin Forms 3.4.0.1009999 in the following Environment: 

=== Visual Studio Community 2017 for Mac ===

Version 7.7.4 (build 1)
Installation UUID: 8ce29ded-598c-460c-935b-d4823d293212
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

=== Mono Framework MDK ===

Runtime:
	Mono 5.16.0.221 (2018-06/b63e5378e38) (64-bit)
	Package version: 516000221

=== NuGet ===

Version: 4.8.0.5385

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.503/Sdks
SDK Versions:
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: 
Build date: 2019-01-11 13:08:10-0500

=== Xamarin.iOS ===

Version: 12.2.1.13 (Visual Studio Community)
Hash: a4332c90
Branch: d15-9
Build date: 2019-01-11 13:08:09-0500

=== Xamarin.Android ===

Version: 9.1.5.1 (Visual Studio Community)
Android SDK: /Users/BathSpaCentral/Library/Android/sdk
	Supported Android versions:
		2.3 (API level 10)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 25.0.3

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/BathSpaCentral/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
openjdk version "1.8.0-9"
OpenJDK Runtime Environment (build 1.8.0-9-microsoft-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 7.7.5.0
Hash: 06ceaea1

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 707040001
Git revision: 2a4679454f31c8bb887cfd181ea133c9149d3cad
Build date: 2019-01-30 16:18:21+00
Build branch: release-7.7.4
Xamarin extensions: c8b4305fd4c60b9c25947072eb150fdc3a5aa2b5

=== Operating System ===

Mac OS X 10.14.2
Darwin 18.2.0 Darwin Kernel Version 18.2.0
    Mon Nov 12 20:24:46 PST 2018
    root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

NuGet Package Management Extensions 0.12.6

- Last known good version:
Not known as it is still in preview
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
 - MacOS, see above
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

MacOS Application created by Visual Studio

### Screenshots

![screenshot 2019-02-12 at 15 56 42](https://user-images.githubusercontent.com/12683146/52648746-eb7d8500-2ede-11e9-9210-000bbfd8e173.png)

### Reproduction Link

Data Templates in App.xaml

```
            <DataTemplate x:Key="ListImageUrlDataTemplate">
                <ViewCell>
                  <controls:ListImageControl  Item="{Binding }" />
                </ViewCell>
            </DataTemplate>   
            
            <DataTemplate x:Key="ListH1DataTemplate">
                <ViewCell>
                    <StackLayout Margin="10,0,10,0" BackgroundColor="Fuchsia">
                            <Label Text="{Binding Data.H1, Converter={StaticResource ListH1JsonConverter}}" FontSize="Large" VerticalOptions="Center" HorizontalOptions="Start" FontAttributes="Bold" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>
            </DataTemplate>  

            <DataTemplate x:Key="ListH2DataTemplate">
                <ViewCell>
                    <StackLayout  Margin="10,0,10,0" BackgroundColor="Lime">
                        <Label Text="{Binding Data.H2}" FontSize="Medium" VerticalOptions="Center" HorizontalOptions="Start" FontAttributes="Bold" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>                
            </DataTemplate>  

            <DataTemplate x:Key="ListH3DataTemplate">
                <ViewCell>
                    <StackLayout Margin="10,0,10,10" BackgroundColor="Navy">                       
                        <Label Text="{Binding Data.H3}" FontSize="Small" VerticalOptions="Center" HorizontalOptions="Start" FontAttributes="Bold" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>
            </DataTemplate>  

            <DataTemplate x:Key="ListParagraphDataTemplate">
                <ViewCell>
                    <StackLayout Margin="10,0,10,10" BackgroundColor="Purple">
                        <Label Text="{Binding Data.Paragraph}" FontSize="Small" VerticalOptions="Center" HorizontalOptions="Start" FontAttributes="None" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>
            </DataTemplate>  

            <DataTemplate x:Key="ListBrochureDataTemplate">
                <ViewCell>
                    <StackLayout Margin="10,20,10,10" BackgroundColor="Yellow">
                        <Label Grid.Column="1" Text="Share Brochure" TextColor="Blue" FontSize="Small" VerticalOptions="Center" HorizontalOptions="End" FontAttributes="None" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>
            </DataTemplate>  
            
            <DataTemplate x:Key="ListBullet1DataTemplate">
                <ViewCell>
                    <StackLayout Margin="20,5,10,5" BackgroundColor="Olive">
                        <Label Text="{Binding Data.Bullet1}" TextColor="Black" FontSize="Small" VerticalOptions="Center" HorizontalOptions="Start" FontAttributes="None" LineBreakMode="WordWrap" />
                    </StackLayout>
                </ViewCell>
            </DataTemplate>              
            
            <datatemplateselectors:JsonListDataTemplateSelector 
                x:Key="JsonListDataTemplateSelector" 
                ListImageUrlDataTemplate="{StaticResource ListImageUrlDataTemplate}"    
                ListH1DataTemplate="{StaticResource ListH1DataTemplate}"
                ListH2DataTemplate="{StaticResource ListH2DataTemplate}"
                ListH3DataTemplate="{StaticResource ListH3DataTemplate}"
                ListParagraphDataTemplate="{StaticResource ListParagraphDataTemplate}"
                ListBrochureDataTemplate="{StaticResource ListBrochureDataTemplate}"
                ListBullet1DataTemplate="{StaticResource ListBullet1DataTemplate}"                      
                />  
```

And the ListView itself is here:

```
        <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="Teal">
            <ListView
              x:Name="FAQListView"
              ItemsSource="{Binding FaqModel.Items}"
              SelectedItem="{Binding SelectedItem}"
              BackgroundColor="{StaticResource White}"
              ItemTemplate="{StaticResource JsonListDataTemplateSelector}"
              SeparatorVisibility="None"
              HasUnevenRows="true"
              CachingStrategy="RecycleElement"
              VerticalOptions="FillAndExpand"
            />
        </Grid>
```

and the DataTemplateSelector is here:

```
    public class JsonListDataTemplateSelector : DataTemplateSelector
    {
        public DataTemplate ListImageUrlDataTemplate { get; set; }
        public DataTemplate ListH1DataTemplate { get; set; }
        public DataTemplate ListH2DataTemplate { get; set; }
        public DataTemplate ListH3DataTemplate { get; set; }
        public DataTemplate ListParagraphDataTemplate { get; set; }
        public DataTemplate ListBrochureDataTemplate { get; set; }
        public DataTemplate ListBullet1DataTemplate { get; set; }

        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            var row = (ListItem)item;

            DataTemplate response = null;

            switch (row.ListItemType)
            {
                case "ImageUrl":
                    response = ListImageUrlDataTemplate;
                    break;
                case "H1":
                    response = ListH1DataTemplate;
                    break;
                case "H2":
                    response = ListH2DataTemplate;
                    break;
                case "H3":
                    response = ListH3DataTemplate;
                    break;
                case "Paragraph":
                    response = ListParagraphDataTemplate;
                    break;
                case "Pdf":
                    response = ListBrochureDataTemplate;
                    break;
                case "Bullet1":
                    response = ListBullet1DataTemplate;
                    break;
                default:
                    break;
            }

            return response;
        }
    }
```

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
