### ISSUE TITLE
Attribute "closeIcon" has already been defined

### ISSUE THREAD

**Issue by daveclarke** [xamarin/Xamarin.Forms#5224]
### Description
When upgrading to Xamarin.Forms 3.5 (which installs dependency Xamarin.Android.Support.* 28.0.0.1) can no longer build Droid project

### Steps to Reproduce

1. Upgrade Droid project to Xamarin.Forms 3.5
2. Rebuild project
3. Build fails with 3 errors in values.xml: Attribute "closeIcon" ("icon", "iconTint") has already been defined

### Expected Behavior
Project successfully builds following upgrade

### Actual Behavior
Project fails to build with errors

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: 3.4.0.1008975
- IDE: Visual Studio for Mac 7.7.4
- Platform Target Frameworks: 
  - iOS:  
  - Android: SDK Platform 28 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@daveclarke Can you make sure that you've cleaned your project (maybe delete the bin/obj folders) and try again? If that fails, could you send us a reproduction? Thanks!

**Comment by daveclarke** [comment]
@samhouts (& @pauldipietro) thanks for following up so promptly. Yes I had deleted all the bin/obj folders. After looking at the build output in more detail I found that I was using an old version of the Android SDK Build Tools. Installing the latest version of the build tools resolved the issue for me.

**Comment by samhouts** [comment]
Hooray! Thank you for letting us know. If you have any further issues, we're here to help!

**Comment by rawsonl** [comment]
I am getting this exact error.  I didn't have the build tools installed at all.  I installed them.

Then the next error was this:

"java.exe exited with code 2"

I utilized this article and enabled multi-dex on to fix the error.  
https://forums.xamarin.com/discussion/97803/getting-error-java-exe-exited-with-code-2
