### ISSUE TITLE
Keyboard hides when changing focus from one entry to next entry

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5228]
### Description
When I tap an entry I get the on screen keyboard, when I tap the enter button, I have added a "Completed" event, to focus the next entry.
### Expected Behavior
When the next entry gets focused the keyboard should be visible on screen
### Actual Behavior
The keyboard is hidden.
### Basic Information

- Version with issue: 3.4.0.1009999
- Last known good version:
- IDE: Visual Studio Community 2017 version 15.9.6,  NetFramework version 4.7.03056
- Platform Target Frameworks: 

  - UWP:  Windows 10, version 1803 (10.0; Build 17134)

- Nuget Packages:
- Affected Devices:

### Reproduction Link

```
<ContentPage >
        <StackLayout Orientation="Vertical">
            <StackLayout>
                <Label Text="Entry 1" />
                <Entry x:Name="Entry1"
                   Completed="Entry1_Completed" />

        </StackLayout>
            <StackLayout>
            <Label Text="Entry 2" />
                <Entry x:Name="Entry2" />
            </StackLayout>
        </StackLayout>
</ContentPage>
```

.cs code : 
```
private void Entry1_Completed(object sender, EventArgs e)
        {
            Entry2.Focus();
        }

```

**Comment by samhouts** [comment]
closed by #6706
