### ISSUE TITLE
Xamarin.Forms 3.5 BindableLayout not working

### ISSUE THREAD

**Issue by sumithicom** [xamarin/Xamarin.Forms#5229]
### Description
Hi Team,

I was trying to do a little demo of **Every Layout is Bindable** [https://blog.xamarin.com/5-things-youll-love-xamarin-forms-3-5/](url)

 So I created a basic project with XF3.5.0.129452(Latest Stable).

I tried to Bind ItemSource of BindableLayout inside StackLayout as shown in this post 

[https://javiersuarezruiz.wordpress.com/2019/02/01/xamarin-forms-utilizando-bindable-layouts/](url)

 But it is not working for me as shown in the above article.  

Please have a look into the attached project.
Thanks in Advance.

### Steps to Reproduce

1. Run the attached project

### Expected Behavior
BindableLayout should work in StackLayout as shown in article and add should add view horizontaly in StackLayout 
### Actual Behavior
No view is added in StackLayout
### Basic Information

- Version with issue: Xamarin.Forms 3.5.0.129452
- Last known good version: NA
- IDE: Visual Studio 2017 (15.9.3)
- Platform Target Frameworks: 
  - iOS: 10
  - Android: 9 Pie

### Screenshots

![image](https://user-images.githubusercontent.com/38970443/52703618-c3585980-2fa4-11e9-8fbc-3103baca3373.png)

### Reproduction Link
[Xamarin3Point5.zip](https://github.com/xamarin/Xamarin.Forms/files/2859822/Xamarin3Point5.zip)

**Comment by andreinitescu** [comment]
In MainPage you have binding commented out:

```
        //this.BindingContext = new MainPageViewModal();
```

Also, your `MainPageViewModal` has friends `Friends` as a field instead of property.

At the end of my blog post https://blog.xamarin.com/5-things-youll-love-xamarin-forms-3-5/ you can see a working sample with BindableLayouts.

**Comment by sumithicom** [comment]
Well I have binding in XAML itself.

And I am such a idiot, Yes it was not a property that is why it was not binding.

Thanks
