### ISSUE TITLE
Imagebutton is not working

### ISSUE THREAD

**Issue by febilp** [xamarin/Xamarin.Forms#5230]
- 

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 3.5.0.129452
- Affected Devices:

**Comment by samhouts** [comment]
@febilp Please use the entire issue template. Can you tell us what is not working? Can you provide a sample project? Thank you

**Comment by samhouts** [comment]
@febilp  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
