### ISSUE TITLE
Top Padding not working on iOS when it is set alone.

### ISSUE THREAD

**Issue by ZekariasNegash** [xamarin/Xamarin.Forms#5239]
### Description
Xamarin.Forms content page top padding is not working if it is set alone. That is if the other padding values are zero the top padding will not work. Setting one of the other values to a non zero value together with the top padding, the top padding will work.

### Steps to Reproduce

1. Create new Xamarin.Forms application
2. Delete the main page and add a new code only main page of type content page.
3. Create a label
Label label = new Label { Text = "Hello Xamarin World!" };
4. Set the page padding
Padding = new Thickness(0, 20, 0, 0);
5. set the label as the content property of the page
Content = label;

### Expected Behavior
The label should have been displayed 20 units below the iOS status bar

### Actual Behavior
The label is overlapping with the iOS status bar

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: I don't remeber (but I guess it was working fine on the earlier version of 3.2.0.871581
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
- Nuget Packages: NetStandardLibrary 2.0.3
- Affected Devices: 

### Screenshots
![image](https://user-images.githubusercontent.com/8667389/52732876-4f34aa80-2fd2-11e9-9eb6-a3626e62709f.png)

**Comment by heiser** [comment]
I'm encountering this issue as well

**Comment by Anamon** [comment]
Can you try setting only a top padding value, but setting it to a value of 19 or 21?
I have encountered this issue, but it happens only if the value is exactly 20. Other values work fine.

**Comment by ZekariasNegash** [comment]
I have found a solution to this. Instead of setting the padding in the constructor of the page,  set the property in the OnAppearing method by overriding it. That will do the trick.

**Comment by maxbromo** [comment]
I think this should be reopened as the stuff posted above is only a workaround, the actual bug still exists in XF 3.6.0.344457 for top padding = 20.

**Comment by raindeer** [comment]
this is still an issue in 4.4.0.991757

**Comment by jefffhaynes** [comment]
Xamarin, workarounds do not mean you don't have to fix stuff.  I swear, some of the bugs that get closed in here...

**Comment by samhouts** [comment]
Hi! We closed this issue because we believed it was resolved in #6457. We don't typically see comments on closed issues unless we are specifically pinged. If you're still experiencing this problem, please file a new issue. Thanks!

**Comment by jefffhaynes** [comment]
Sounds like it probably wasn't fixed (I believe I'm having a related issue) but regardless if you could link fixes to the issues that would be helpful.  Thanks!

**Comment by samhouts** [comment]
We didn't close it the first time. That was the issue author. :)

**Comment by jefffhaynes** [comment]
Sure enough.  Sorry, my mistake.
