### ISSUE TITLE
Compiled Bindings with Picker.ItemDisplayBinding

### ISSUE THREAD

**Issue by tbrushwyler** [xamarin/Xamarin.Forms#5240]
### Description
When using [Compiled Bindings](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings), there is a compilation error when setting the `Picker.ItemDisplayBinding` property using the `Binding` markup extension.

I want to be able to set the data type of a visual element to enable compiled bindings and then set the `Picker.ItemDisplayBinding` property on one of its ancestors without causing build errors.

### Steps to Reproduce

1. Open the reproduction solution ([zip](https://github.com/tbrushwyler/XF_CompiledBindings_Picker/archive/master.zip), [git](https://github.com/tbrushwyler/XF_CompiledBindings_Picker)).
2. Build the solution

### Expected Behavior
The solution builds and I can run the app and see three pickers on the page (one should display the result of `.ToString()` and the other two should display the `Name` property).
### Actual Behavior
There is a build error: 
```
XF_CompiledBindings_Picker/XF_CompiledBindings_Picker/MainPage.xaml(49,49): Error: Position 15:49. Binding: Property 'Name' not found on 'XF_CompiledBindings_Picker.MainPageViewModel' (XF_CompiledBindings_Picker)
```
### Basic Information

- Version with issue: Xamarin.Forms 3.5.0.129452 (also tested against 4.0.0.135213-pre4)
- Last known good version: none
- IDE: 7.7.4
- Platform Target Frameworks:
  - iOS:  12.2.1.15
  - Android: 9.1.8.0
- Nuget Packages: Xamarin.Forms 3.5.0.129452

**Comment by StephaneDelcroix** [comment]
`ItemDisplayBinding` is kinda special, as it uses the same syntax as setting a binding, but instead sets a property

**Comment by tranb3r** [comment]
@StephaneDelcroix 
This issue was opened 5 months ago, and so far no progress has been done.
Do you think it could be reprioritized ?

**Comment by StephaneDelcroix** [comment]
x:DataType="{Null}" in your sample should be x:DataType="{x:Null}" or it will fail with 4.1

**Comment by tranb3r** [comment]
Yes the sample is wrong, obviously it's x:DataType="{x:Null}".
However, I think we agree this "{x:Null}" datatype is just an ugly workaround.
The real question is: can you fix the issue preventing the sample to build when x:DataType is not set to {x:Null} ?
