### ISSUE TITLE
[Enhancement] Add Xamarin.Forms.Preserve attribute

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5244]
## Summary

Classes and members that are not specifically referenced in code are subject to be stripped out by the iOS and Android linkers. Xamarin.Forms has a helper attribute that we use to decorate classes that need to be preserved. This is currently part of our internal namespace. We may want to expose this in the public namespace instead so customers and vendors can take advantage of it, too.

## API Changes

Deprecate 

https://github.com/xamarin/Xamarin.Forms/blob/5ff89a2ffb160d15dede5d1c955cc7feebfde3d2/Xamarin.Forms.Core/Internals/PreserveAttribute.cs#L8

 and make a public version.

## Intended Use Case

One good example: https://docs.microsoft.com/xamarin/xamarin-forms/xaml/custom-namespace-schemas

**Comment by mattleibow** [comment]
One possible issue is with a file that has both usings:

```csharp
using Xamarin.Forms;
using Xamarin.Forms.Internals;
```

The compiler will give an error, but we could argue that most devs should not hit this as the internals namespace is not something that is commonly used - if at all by the average dev.

**Comment by StephaneDelcroix** [comment]
The namespace for the PreserveAttribute does not matter at all. The attribute is only looked for by name. meaning that users can define their own, in their own namespace.

I understand he intention of simplifying the life of developers by providing a public `Preserve` attribute, but the Preservation is bound to the linker which is not Xamarin.Forms.

I'd champion defining a public PreserveAttribute somewhere else, maybe in X.Essentials (//cc @jamesmontemagno )

**Comment by jamesmontemagno** [comment]
Yes, we could easily put it in Xamarin.Essentials. That may be a better way of doing it. I assume this is just something that needs to go into the .NET standard version since iOS/Android already have it?

**Comment by dotMorten** [comment]
> . I assume this is just something that needs to go into the .NET standard version since 
iOS/Android already have it?

The one Android has can't be used at the assembly level.

> We could easily put it in Xamarin.Essentials. That may be a better way of doing it.

I don't like moving this to essentials. It prevents it from being used by class libraries without taking a dependency on an unnecessary component. This is a platform feature, and should be in the platform.

**Comment by jfversluis** [comment]
Don't think this is anything we'll be doing for Forms anymore. Lets double-check for .NET MAUI, if still needed at all.
