### ISSUE TITLE
Xamarin.Forms 3.5.0.129452 ScrollView Orientation="Both" crashes on Android

### ISSUE THREAD

**Issue by mikebikerider** [xamarin/Xamarin.Forms#5247]
### Description
A content page with a ScrollView Orientation.Both will crash on Android when the ScrollView area is swiped.
Orientation="Horizontal" and Orientation="Vertical" work as expected. 
Same XAML runs fine under iOS.
Reverting Android Xamarin.Forms back to build 3.4.0.1029999 cures the issue.
  
### Steps to Reproduce

1. Create a minimalistic Android project with one content page with a ScrollView Orientation="Both".
2. Compile and run on a device.
3. Swipe or touch the ScrollView area.

### Expected Behavior
Should scroll the content in either direction, as it did in prior builds. Should not crash the app.
### Actual Behavior
Crashes every time I swipe.
I encountered the issue while preparing new production builds of 3 different apps. It took me 10 min to put together and run a test app to reproduce the issue.

![screenshot_20190213-200734](https://user-images.githubusercontent.com/19241066/52755790-1e05ab80-2fcd-11e9-8052-2f4dc20fdb47.jpg)
![screenshot_20190213-200900_samsung experience home](https://user-images.githubusercontent.com/19241066/52755791-1e9e4200-2fcd-11e9-85f3-a74faf375bc7.jpg)

### Basic Information

- Version with issue: Xamarin.Forms 3.5.0.129452
- Last known good version: Xamarin.Forms 3.4.0.1029999
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
 Xamarin.Forms 3.5.0.129452
Xamarin.Android.Support.Support.v4 2.8.0.0.1
 Xamarin.Android.Suppport.v7.App.Compat 2.8.0.0.1
Xamarin.Android.Support.v7.CardView 2.8.0.0.1
Xamarin.Android.Support.v7.MediaRouter 2.8.0.0.1
NetStandard.Library 2.0.3
- Affected Devices: Android

**Comment by tranb3r** [comment]
I'm also facing this regression in XF3.5.

Here is the stacktrace:
System.InvalidCastException: Specified cast is not valid.
  at Xamarin.Forms.Platform.Android.AHorizontalScrollView.OnTouchEvent (Android.Views.MotionEvent ev) [0x00064] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\AHorizontalScrollView.cs:55
  at Android.Views.View.n_OnTouchEvent_Landroid_view_MotionEvent_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_e) [0x00011] in <95d915721ad748108ff096dce8f8f32c>:0
  at (wrapper dynamic-method) System.Object.22(intptr,intptr,intptr)
