### ISSUE TITLE
HttpClient hangs when using gzip AutomaticDecompression without disposing HttpResponseMessages

### ISSUE THREAD

**Issue by valentinba** [xamarin/Xamarin.Forms#5249]
### Description

When using the System.Net.Http.HttpClient with a HttpClientHandler configured with gzip AutomaticDecompression, the client hangs after about 10 requests on iOS and Android.

Identical code succeeds in UWP and in a .NET console application.

On Android and iOS, disposing the HTTPResponseMessage via a using statement fixes the issue. This does not appear necessary in UWP or .NET proper.

Removing the AutomaticDecompression option also fixes the issue.

### Steps to Reproduce

1. Run the attached Client application in the Android emulator or iOS simulator in debug mode
2. Click the "Start (without using)" button
3. The label in the center of the screen will display the request number and response length
4. The application hangs after the 10th request, eventually breaking with a timeout exception.
5. Restart the application
6. Click on the "Start (with using)" button
7. Note how all 20 requests appear to complete successfully
8. Try the above steps in UWP and note how all 20 request finish even without disposing the response messages
9. Try the above steps with the attached .NET ConsoleTest application and note how all 20 request finish

### Expected Behavior

The client should not hang / timeout after 10 requests.

### Actual Behavior

The client hangs after 10 requests, unless one disposes the HTTP request message objects.

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: Tried 2.5.0, still had the issue
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.2.1.15
  - Android: 8.1
  - UWP:  16299

### Screenshots

N/A

### Reproduction Link

[ConsoleTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2863241/ConsoleTest.zip)
[Client.zip](https://github.com/xamarin/Xamarin.Forms/files/2863242/Client.zip)

**Comment by valentinba** [comment]
It occurs to me that this bug belongs in some other repo, perhaps Mono? Any chance you could point me in the right direction?

**Comment by samhouts** [comment]
This issue was moved to mono/monodevelop#7251
