### ISSUE TITLE
iOS: Color of Editor Placeholder is different than Entry

### ISSUE THREAD

**Issue by sebastianfilke** [xamarin/Xamarin.Forms#5252]
### Description
The Color of the Editor Placeholder is different than the placeholder Color of the entry element. It's more dark.
### Steps to Reproduce
Trivial.
### Expected Behavior
Looks the same.
### Actual Behavior
Not the same.
### Basic Information

- Version with issue: 3.4.0.1029999
- Last known good version: -
- IDE: Visual Studio: 15.9.6

### Screenshots

![image](https://user-images.githubusercontent.com/10894484/52779183-f1db4080-3047-11e9-87e7-880783bc3799.png)

**Comment by andreinitescu** [comment]
fixed by #5259
