### ISSUE TITLE
iOS: Placeholder does not disappear when entering text in Editor inside ScrollView

### ISSUE THREAD

**Issue by sebastianfilke** [xamarin/Xamarin.Forms#5253]
### Description
The placeholder should disappear if a text is entered in the editor.
### Steps to Reproduce
Place Editor inside ScrollView.
### Expected Behavior
The Placeholder disappears if a text is entered and appears if the text is null or empty.
### Actual Behavior
The Placeholder and the text overlaps.
### Basic Information

- Version with issue: 3.4.0.1029999
- Last known good version: -
- IDE: Visual Studio: 15.9.6

### Screenshots

![image](https://user-images.githubusercontent.com/10894484/52779540-abd2ac80-3048-11e9-891a-910618386081.png)

**Comment by pauldipietro** [comment]
This doesn't seem to reproduce on the latest 4.0-pre in an iPad sim. Can you confirm if you still experience the issue, and if the layout is as simple as an Editor in the ScrollView, or provide a reproduction if the newer releases don't fix it?

**Comment by samhouts** [comment]
@sebastianfilke Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
