### ISSUE TITLE
Binding new property of control

### ISSUE THREAD

**Issue by raV720** [xamarin/Xamarin.Forms#5256]
### Description

Property with **new** keyword is not visible for binding (XAML) engine when building project. Binding engine still uses property from base class. Causes error while build when types of properties are different.

### Steps to Reproduce

1. Derive from Entry and create new control MyEntry
2. Create new property **Completed** but with type **ICommand** and with **new** keyword
3. Use new control in XAML and bind **Completed** property to viewmodel property.
4. Build causes error:
```
Cannot assign property "Completed": Property does not exist, or is not assignable, or mismatching type between value and property ->
    at Xamarin.Forms.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
```

### Expected Behavior
No error while build. Binding engine should use new property instead property from base type.
### Basic Information

- Version with issue: 3.3.0.967583
- IDE: Visual Studio 2017, 15.9.3

**Comment by GalaxiaGuy** [comment]
I would guess it is because `TrySetProperty` only considers the first property it finds with the correct name: https://github.com/xamarin/Xamarin.Forms/blob/15c6f561e6d51071b7b3cdd9e92d2cbf16edaf2b/Xamarin.Forms.Xaml/ApplyPropertiesVisitor.cs#L552

Interestingly, there is an overload of this method that looks like it tries to do the right thing, but only if `NETSTANDARD1_0` is set, and throws an exception otherwise:

```csharp
#if NETSTANDARD1_0
			try {
				propertyInfo = elementType.GetRuntimeProperty(localName);
			} catch (AmbiguousMatchException) {
				// Get most derived instance of property
				foreach (var property in elementType.GetRuntimeProperties().Where(prop => prop.Name == localName)) {
					if (propertyInfo == null || propertyInfo.DeclaringType.IsAssignableFrom(property.DeclaringType))
						propertyInfo = property;
				}
			}
#else
			while (elementType != null && propertyInfo == null) {
				try {
					propertyInfo = elementType.GetProperty(localName, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.DeclaredOnly);
				} catch (AmbiguousMatchException e) {
					throw new XamlParseException($"Multiple properties with name '{elementType}.{localName}' found.", lineInfo, innerException: e);
				}
				elementType = elementType.BaseType;
			}
#endif
```

**Comment by StephaneDelcroix** [comment]
The Command you're looking for exists in Entry, and is called `ReturnCommand`. You can bind to it.

Nonetheless, I tried to reproduce your issue, with the following Xaml"
```xaml
<ContentPage
        xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        xmlns:local="using:Xamarin.Forms.Xaml.UnitTests"
        x:Class="Xamarin.Forms.Xaml.UnitTests.Gh5256">
    <local:Gh5256Entry x:Name="entry" Completed="{Binding CompletedCommand}" />
</ContentPage>
```

and the following test:
```csharp
using System.Windows.Input;
using NUnit.Framework;
using Xamarin.Forms.Core.UnitTests;

namespace Xamarin.Forms.Xaml.UnitTests
{
	public class Gh5256Entry : Entry
	{
		public Gh5256Entry()
		{
			base.Completed += (o,e) => this.Completed?.Execute(o);
		}
		public static readonly BindableProperty CompletedProperty =
			BindableProperty.Create("Completed", typeof(ICommand), typeof(Gh5256Entry), default(ICommand));

		public new ICommand Completed {
			get => (ICommand)GetValue(CompletedProperty);
			set => SetValue(CompletedProperty, value);
		}
	}

	[XamlCompilation(XamlCompilationOptions.Skip)]
	public partial class Gh5256 : ContentPage
	{
		public Gh5256() => InitializeComponent();
		public Gh5256(bool useCompiledXaml)
		{
			//this stub will be replaced at compile time
		}

		[TestFixture]
		class Tests
		{
			[SetUp] public void Setup() => Device.PlatformServices = new MockPlatformServices();
			[TearDown] public void TearDown() => Device.PlatformServices = null;

			[Test]
			public void EventOverriding([Values(false, true)]bool useCompiledXaml)
			{
				var layout = new Gh5256(useCompiledXaml) { BindingContext = new { CompletedCommand = new Command(() => Assert.Pass()) } };
				Gh5256Entry entry = layout.entry;
				entry.SendCompleted();
				Assert.Fail();
			}
		}

	}
}
```

and it works well, with XamlC turned off (your case).

My guess is that you created a `new` Completed regular property, not a bindable one, and regular properties can not be bound to.

I'm keeping this issue open while I investigate the InvalidCastException thrown by XamlC

**Comment by StephaneDelcroix** [comment]
I forgot to mention that redefining a member (`Completed`) from an event to a property is really bad design, and serious abuse of the intent of the `new` keyword.

**Comment by raV720** [comment]
I agree with abusing `new` keyword. But this is another story.

I forgot to mention I have enabled xaml compilation. The problem still exists when xaml compilation is enabled. And it does not matter if it is BindableProperty or not. After disabling xaml compilation everything is OK.
