### ISSUE TITLE
Label Binding to missing property on iOS

### ISSUE THREAD

**Issue by kuzub** [xamarin/Xamarin.Forms#5258]
### Steps to Reproduce
 Label Text="{Binding **MissingProperty**}" TextDecorations="Underline"  - error
 Label Text="{Binding **MissingProperty**}"   - no error

### Expected Behavior
No Crash App

### Actual Behavior
Crash App

SIGABRT: Value cannot be null. Parameter name: other

Foundation.NSMutableAttributedString..ctor (Foundation.NSAttributedString other) <0x1055e01a0 + 0x0009c> in <5782a71edfb44eafb4f946b787faeb4a#8eb8e7cab91ea3c1e99e1212fa5332c3>:0
LabelRenderer.UpdateTextDecorations ()
LabelRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)

### Basic Information

- Version with issue: 3.5.0.129452
- Last known good version: -
- IDE: Visual Studio 2017 for Mac version 7.7.4
- Platform Target Frameworks:
  - iOS:  12.1
- Nuget Packages: Xamarin.Forms 3.5.0.129452
- Affected Devices:
  IOS Simulator, iPhone 8

### Reproduction Link
https://github.com/kuzub/LabelWithMissingBindingProperty

**Comment by andreinitescu** [comment]
Possible fix is #5013
