### ISSUE TITLE
[Enhancement]Make Route, RouteScheme and RouteHost bindable on Shell

### ISSUE THREAD

**Issue by MSiccDev** [xamarin/Xamarin.Forms#5266]
## Summary
Route (all shell levels), RouteScheme and RouteHost should be bindable properties.

## API Changes
none

## Intended Use Case
Binding in MVVM
Parent: #2415

**Comment by HobDev** [comment]
@samhouts  As Route, RouteScheme and RouteHost are no longer public API's could this issue be closed.

**Comment by samhouts** [comment]
Good idea! Thanks!
