### ISSUE TITLE
[Enhancement] Shell should support login pattern more easily

### ISSUE THREAD

**Issue by southrock70** [xamarin/Xamarin.Forms#5272]
## Summary
The new shell is a super good addition to Xamarin Forms, thanks!
But if you want to show a modal login page before or during navigation in the Shell hierarchy you need to revert to the "old" techniques (OnAppearing or Switching Navigation Stack or custom navigation framework). The new URI navigation is not doing this easily either (correct me if I'm wrong)

## API Changes
In order to achieve this it would be good to "design" the login/modal behavior just like you defined the shell with an .xaml file.
And have methods/properties supporting the behavior for the login/modal.
Enable this and have a DataTemplate pointing to the actual page to show (Content Page)
Properties to handle BackButton.
Metods to show the page and close it.

## Intended Use Case
When ever you want to show a Modal Page in the Shell navigation structure. For example before showing the full Shell Experience you want your users to login/signup on a modal page before showing anything else. Be able to control the opening/closing of the page also. 
Parent: #2415

## Current way to do this 

```XAML

<!-- When the user is on this Login Page they won't see a flyout menu-->
<TabBar Route="LoginPage">
    <local:LoginPage/>
</TabBar>

<!-- When the user is here they won't be able to get back to the Login Page-->
<FlyoutItem Route="LoggedIn">
     <UserPages/>
</FlyoutItem>
<FlyoutItem>
     <UserPages/>
</FlyoutItem>
```

```C#

public class LoginPage
{
     void LoginUser()
      {
          Shell.Current.GotoAsync("\\LoggedIn");
      }
}
```

**Comment by PureWeen** [comment]
Closing and moving discussion to here #8528
