### ISSUE TITLE
Missing constructor on VisualElementTracker on version 3.5

### ISSUE THREAD

**Issue by dirivero** [xamarin/Xamarin.Forms#5278]
### Description

In version 3.5 the VisualElementTracker constructor got a 2nd optional parameter that is making libraries compiled against previous version of Xamarin.Forms to fail. This is an example of an iOS renderer that is a UIViewController:

```
System.MissingMethodException: Method not found: void Xamarin.Forms.Platform.iOS.VisualElementTracker..ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)
  at at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper(intptr,intptr)
  at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.2.1.13/src/Xamarin.iOS/UIKit/UIViewController.g.cs:2983
  ...
```

Would it be possible to add a separated 2nd constructor with 2 parameters instead of having one with an optional parameter keeping the same semantics? 

### Basic Information

- Version with issue: 3.5
- Last known good version: 3.4

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/4522/files#r237728027
