### ISSUE TITLE
Wrong ParentViewController in PageRenderer

### ISSUE THREAD

**Issue by bradlak** [xamarin/Xamarin.Forms#5285]
### Steps to Reproduce

1.  Create the following hierarchy NavigationPage (TabbedPage ( 4 Pages))
2. Create PageRenderer and TabbedPageRenderer
3. In ViewWillAppear in PageRenderer for Page which is inside TabbedPage check ParentViewController

### Expected Behaviour
ParentViewController is UITabBarController -> true

### Actual Behaviour
ParentViewController is UITabBarController -> true
ParentViewController is UINavigationController -> true

### Basic Information

- Version with issue: 3.2.0.871581
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.1
- Affected Devices: iPhone 6s simulator

**Comment by samhouts** [comment]
@bradlak Would you be able to attach a sample project that exhibits this issue? Thank you!

**Comment by samhouts** [comment]
@bradlak Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
