### ISSUE TITLE
Can't import .net standard NuGet

### ISSUE THREAD

**Issue by jackbond** [xamarin/Xamarin.Forms#5294]
Steps to reproduce

1) Create new Xamarin forms project
2) Add ZXing.Net.Bindings.Magick NuGet package

Results in build error...

Can not resolve reference: `zxing`, referenced by `ZXing.Magick`. Please add a NuGet package or assembly reference for `zxing`, or remove the reference to `ZXing.Magick`.

Version: 3.4.0.1008975

**Comment by samhouts** [comment]
@jackbond Can you please attach your sample project? Thank you!

**Comment by jackbond** [comment]
[repro.zip](https://github.com/xamarin/Xamarin.Forms/files/2887680/repro.zip)

There ya go. Thanks.

**Comment by micjahn** [comment]
The error is related to the target platform of your project and the available assemblies in the nuget package of ZXing.Net. The project "XamarinIssue" is targeted against ".NET Standard 2.0". The nuget package manager finds the closest match with the .net standard 2.0 version of ZXing.Net. Everything works until now. The next is the project "XamarinIssue.Android". It is targeted against Android. The closest match of ZXing.Net is the monoandroid build. And here comes the error. The monoandroid build of ZXing.Net can not be used with the .Net Standard 2.0 build of ZXing.Net.Bindings.Magick.

I have no idea how to fix the nuget package. At the moment I only have a workaround.
Please rename the directory "%USERPROFILE%\.nuget\packages\zxing.net\0.16.4\lib\MonoAndroid" to "%USERPROFILE%\.nuget\packages\zxing.net\0.16.4\lib\MonoAndroidX".

**Comment by samhouts** [comment]
@Redth Do we have any guidelines somewhere for how third party nugets should set up their targeting in situations like this?

**Comment by jackbond** [comment]
Would it be possible to do Zxing.Net 0.17.0 which only targeted .netstandard 2.0? Going through the list of currently supported frameworks, I think it roughly breaks down like this...

Silverlight: dead (truly a shame)
.NET Framework: 4.7 up would still be supported
MonoAndroid: Xamarin is pretty much .netstandard 2.0 compatible isn't it?
.NET standard: < 2.0 Are people still targeting anything less?

Realistically any of the frameworks left behind could still use packages < 0.17.0 :)

**Comment by PureWeen** [comment]
@micjahn 

So I'm pretty sure what needs to be done would be
- Name the folder *MonoAndroid10*
- rename the dlls to *zxing.dll*  from *zxing.monoandroid.dll* to match the name of the dlls in the netstandard library that way the dll can just bait and switch in 

And I would change this
https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/zxing.monoandroid.csproj#L35

to portable

![image](https://user-images.githubusercontent.com/5375137/53674064-ab413500-3c48-11e9-8182-20d70a3c78e3.png)
