### ISSUE TITLE
Static WebView

### ISSUE THREAD

**Issue by tsvetkovsa** [xamarin/Xamarin.Forms#5295]
I can not create a static webview, I need to keep the map active for my application.
I also created a similar topic on this forum, but I received no answer.
https://forums.xamarin.com/discussion/145615/how-create-static-webview

**Comment by tsvetkovsa** [comment]
Each time the part of the webview that is in the android re-creates the native control, so if you use the C# webview in the xamamarine layer and it is static, this does not help, the content reloads every time.

**Comment by andreinitescu** [comment]
Can you describe a bit the scenarios where you want a "static" WebView to exist?
What do you mean by "static" anyway? Keep the instance alive between screens in your app? I am not sure, is that a good idea? 
Some more info could help.

**Comment by tsvetkovsa** [comment]
Yes, I need keep WebView control instance alive between screens, because i have heavy page with webgl, which is long to load when opened (about 8 seconds) and I need this page on every page.

"I don't think "bug" label describes your ticket well." I agree, but I do not know what the ticket is about.

For more details , i writed here: https://forums.xamarin.com/discussion/145615/how-create-static-webview

Thank you.

**Comment by andreinitescu** [comment]
Are you sure that on native, if you remove a WebView control from its parent, and then when you put it back. the WebView doesn't reload its web content?

**Comment by tsvetkovsa** [comment]
There is an implementation on pure android without taking into account the xamarin where such a mechanism works. webview is created in the fragment and throughout the entire software is inserted into different pages. How to implement in xamarin forms I have no ideas

**Comment by tsvetkovsa** [comment]
Specification: My page does not load for a long time, but the initialization and construction of the 3d scene takes a long time in the webview.

**Comment by andreinitescu** [comment]
@tsvetkovsa Keeping the WebView around doesn't sound good idea to me. It requires some management so you don't end having a crash because you have two pages in the navigation stack using same instance!

If you really want it, I guess you could try it. One way I think could be with the native view feature: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/code
But again, you have to be careful with the instance across pages...

**Comment by AntonEmelyancev** [comment]
@tsvetkovsa 
I have come to quite similar solution while being optimizing newsfeed with content as video players (which is 'heavy' component). I came up with following solution (Android-only though):
-Forms View for my control
-Android Renderer with all needed logic and empty native control (lets say ViewGroup)
-**static** instance of real native control (video player in my case) which has to be initialized only one time
On 'play' request:
1. Unwire static player from the previous renderer.
2. populate content of empty native control with static player instance.
3. Wire player to the new renderer.
Though such kind of solution requires a lot of micromanagement like event sub/unsub, managing to remove view from previous parent,etc I've got really smooth scrolling experience (while having multiple instances of player int the ListView resulted in significant glitches (especially on certain devices). So similar approach may work for you.

**Comment by tsvetkovsa** [comment]
@AntonEmelyancev , How can i do static webview (native control) via renderer webview? 
Here my example renderer webview: https://forums.xamarin.com/discussion/145615/how-create-static-webview#latest

If it's possible for you, u can explain in russian for me or show your example

**Comment by samhouts** [comment]
Hi! If you're still looking for assistance, try https://forums.xamarin.com/categories/xamarin-forms. Thanks!
