### ISSUE TITLE
OnAppearing not wait the view

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5301]
### Description
When I raise code instructions on the OnAppearing, the view is showing after they instructions.

### Steps to Reproduce

Use Solution joined at this report

### Expected Behavior
Show the page with the "Start text" in the label, wait 2 seconds and change text for the "End text"

### Actual Behavior
Wait 2 seconds and show page with the "End text"

### Basic Information

- Version with issue: Xamarin.Forms pre 3
- Last known good version: don't know
- IDE: Visual Studio Windows
- Platform Target Frameworks: 
  - Android: Just have test with Android 26
- Nuget Packages: Default Xamarin Forms pre 3 packages
- Affected Devices: Asus tablet

### Reproduction Link

[OnAppearingError.zip](https://github.com/xamarin/Xamarin.Forms/files/2876427/OnAppearingError.zip)

**Comment by geskill** [comment]
Did you try this:
```csharp
        protected override async void OnAppearing() {
            base.OnAppearing();
            await Task.Delay( 1000 );
            this.view_model.LabelText = "End text";
        }
```

**Comment by Moltroon** [comment]
With async it work good. Thanks.
