### ISSUE TITLE
Xamarin.Forms.Platform.Android does not exist after Xamarin update to 3.5

### ISSUE THREAD

**Issue by Agredo** [xamarin/Xamarin.Forms#5302]
### Description
Currently it is not possible for me to build the Android project after update from Xamarin.Forms 3.4 to Xamarin.Forms 3.5. 

### Steps to Reproduce

Update Xamarin.Forms from 2.5 or 3.4 to 3.5

### Expected Behavior
Building should work after updating.

### Actual Behavior
Errors during build:
![image](https://user-images.githubusercontent.com/16531090/52979212-e8016680-33d4-11e9-85d7-f5eecb8e1779.png)

### Basic Information
- Version with issue: 3.5
- Last known good version: 3.4
- IDE: Visual Studio 15.9.7

![image](https://user-images.githubusercontent.com/16531090/52979316-4b8b9400-33d5-11e9-819a-710f6b6e452a.png)

### Reproduction Link
https://stackoverflow.com/questions/54591881/xamarin-forms-platform-android-does-not-exist-after-xamarin-update-from-2-5-to-3

**Comment by samhouts** [comment]
@Agredo Can you please attach the project that is having this issue? Thanks!

**Comment by Agredo** [comment]
Sorry I cant upload this project. I searched for this Issue and found on Stackoverflow other people with this problem (attached Link).

I will try today to reproduce it with a sample project.

**Comment by samhouts** [comment]
@Agredo Did you have any luck reproducing this issue? Thanks!

**Comment by samhouts** [comment]
@Agredo  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by sekmenhuseyin** [comment]
Hi,

we have the same problem on our project.
We upgraded from xamarin.forms v3.0 to v3.5 and now I get an error saying "The type or namespace 'Android' does not exists in 'Xamarin.Froms.Platform'"
![image](https://user-images.githubusercontent.com/1363876/56411041-05916600-6288-11e9-9917-b06f28105b4c.png)

![image](https://user-images.githubusercontent.com/1363876/56411049-0f1ace00-6288-11e9-96c0-3f2c6c1b34ba.png)

**Comment by s-bhavin-shah** [comment]
Any solution for this issue?

**Comment by xiashao1980** [comment]
Jaymin is right. You must make sure that the version of the installed Xamarin.Android should be as same as the version that you have added to the current project.

For example, if you have installed v27.0.2.1 of Xamarin.Android, you can not upgrade your project to v28.0.0.1 only. You should upgrade the component(Xamarin.Android) which is installed with Visual Studio first.

**Comment by dush88c** [comment]
> You must make sure that the version of the installed Xamarin.Android should be as same as the version that you have added to the current project.
> 
> For example, if you have installed v27.0.2.1 of Xamarin.Android, you can not upgrade your project to v28.0.0.1 only. You should upgrade the component(Xamarin.Android) which is installed with Visual Studio first.

How can I update or upgrade the Xamarin.Android in  VS2017 ?
