### ISSUE TITLE
Map navigation does not work when using Shell

### ISSUE THREAD

**Issue by alex-relov** [xamarin/Xamarin.Forms#5306]
### Description
Map navigation does not work on Android when using Shell
### Steps to Reproduce

1. Clone repository https://github.com/alex-relov/xamarin.froms.maps.shell
2. Add maps key to MyApp on android solution

### Basic Information

- Version with issue:3.5.0.129452
- Last known good version:-
- IDE: VS 2017 15.9.5
- Platform Target Frameworks: 
  - Android:  
- Android Support Library Version: 27.0.2.1
- Nuget Packages: xamarin.forms.maps 3.5.0.129452
- Affected Devices: Android Emulator  api 28

### Reproduction Link

https://github.com/alex-relov/xamarin.froms.maps.shell
Parent: #2415

**Comment by pauldipietro** [comment]
I can reproduce this against the latest 4.0-pre4, but the navigation (scrolling the map around) technically works, but only slightly and is otherwise inconsistent and choppy.

**Comment by Nixon-Joseph** [comment]
I've run into this myself. There doesn't seem to be any benefit in container structure (in case of gesture hijacking). Seems to allow horizontal panning so long as gesture remains within about 20dp from original Y gesture position, any vertical deviation past that seems to cut off the gesture entirely. To me that seems to point at it thinking we're attempting to scroll.

**Comment by andysinclair** [comment]
I've just experienced this issue today and can easily reproduce with a simple Shell app with an embedded Xamarin Forms Map.
Panning/Zooming the map on Android is not usable.
Is there any update as to when this might be fixed? Thanks.

**Comment by alex-relov** [comment]
> I've just experienced this issue today and can easily reproduce with a simple Shell app with an embedded Xamarin Forms Map.
> Panning/Zooming the map on Android is not usable.
> Is there any update as to when this might be fixed? Thanks.

To the release should fix, for now the task in the status To do

**Comment by mivewi** [comment]
I'm really looking forward to the fix. If any got a workaround, please share.

**Comment by andysinclair** [comment]
I am also keen to find a workaround, assuming a fix will not be available soon. Anybody got any ideas?

**Comment by mivewi** [comment]
I see that there are 216 todos and 2 is currently in progress and one of them is this case, so it should be done soon.

**Comment by karlsson-mvm** [comment]
As a workaround you can create a custom renderer for the Map (like suggested by samhouts https://github.com/xamarin/Xamarin.Forms/issues/5205):

[assembly: ExportRenderer(typeof(CustomMap), typeof(CustomMapRenderer))]
.....
  public override bool DispatchTouchEvent(MotionEvent e)
        {
            Parent.RequestDisallowInterceptTouchEvent(true);
            return base.DispatchTouchEvent(e);
        }

**Comment by samhouts** [comment]
#6310

**Comment by muriloe** [comment]
@samhouts 
I saw that this issue is about to be resolved for this sprint, is there any release date to resolve this issue? I'm using xamarin.forms.googlemaps and renderer not worked for me.

Thanks.

**Comment by samhouts** [comment]
closed by #7032
