### ISSUE TITLE
[Enhancement] Remove Xamarin.Forms.Build from repository

### ISSUE THREAD

**Issue by akihikodaki** [xamarin/Xamarin.Forms#5308]
## Summary
Git submodule `Xamarin.Forms.Build` is not publicly accessible and prevents recursive cloning. It would be nice if the submodule is removed.

## API Changes

None

## Intended Use Case
This affects when adding Xamarin.Forms as a Git submodule.

**Comment by samhouts** [comment]
closed by #6068
