### ISSUE TITLE
[Feedback] Unable to put imageview and textview on same line or gridview cell

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5314]
### Description

<p>I created the following XML:

 &lt;LinearLayout
     android:layout_width=&quot;match_parent&quot;
     android:layout_height=&quot;wrap_content&quot;
     android:orientation=&quot;horizontal&quot; &gt;

     &lt;ImageView
         android:layout_width=&quot;wrap_content&quot;
         android:layout_height=&quot;wrap_content&quot;
         android:layout_weight=&quot;0.5&quot;
         ...
         /&gt;

     &lt;TextView
         android:layout_width=&quot;wrap_content&quot;
         android:layout_height=&quot;wrap_content&quot;
         android:layout_marginLeft=&quot;10dp&quot;
         android:layout_weight=&quot;0.5&quot;
         android:text=&quot;Test2&quot; /&gt;
&lt;/LinearLayout&gt;

In the designer the imageview does not appear.  When complied and run the imageview is not there but there are no compile errors.  When I change the imageview to a textview instead, they both appear, change it back to imageview and it disappears again.  I tried with a tablerow layout as well, exact same result.

I also attempted to include a textview and an imageview in the same gridview cell.  I used the following Imageadapter code:

    class ImageAdapter : BaseAdapter
    {
        public DataSet participants;
        public User MyUser;
        private readonly Context context;

    
    public ImageAdapter(Context c)
        {
            context = c;
        }

        public override int Count
        {
            get { return participants.Tables[0].Rows.Count; }
        }

        public override Java.Lang.Object GetItem(int position)
        {
            return  null;
        }

        public override long GetItemId(int position)
        {
            return 0;
        }
        //public override View GetView(int position, View convertView, ViewGroup parent)
        //{
        //    ImageView imageView;

        //    if (convertView == null)
        //    {
        //        // if it's not recycled, initialize some attributes
        //        imageView = new ImageView(context);
        //        imageView.LayoutParameters = new AbsListView.LayoutParams(340, 340);
        //        imageView.SetScaleType(ImageView.ScaleType.CenterCrop);
        //        imageView.SetPadding(8, 8, 8, 8);
        //    }
        //    else
        //    {
        //        imageView = (ImageView)convertView;
        //    }
        //    string playerid = participants.Tables[0].Rows[position][0].ToString();
        //    com.organizemyleague.www.PhotoManagerLogon myService = new com.organizemyleague.www.PhotoManagerLogon();
        //    DataSet MyPhotoDataSet = myService.GetPhoto(MyUser.Username, MyUser.Password, playerid);
        //    byte[] imageBytes = (byte[])MyPhotoDataSet.Tables[0].Rows[0][0];
        //    Bitmap bitmap = BitmapFactory.DecodeByteArray(imageBytes, 0, imageBytes.Length);
        //    imageView.SetImageBitmap(bitmap);
        //    return imageView;
        //}
        public override View GetView(int position, View convertView, ViewGroup parent)
        {
            // ImageView myimageView;
            View view;

            if (convertView == null)
            {
                // if it's not recycled, initialize some attributes

                view = LayoutInflater.From(parent.Context).Inflate(Resource.Layout.Cellview, parent, false);

            }
            else
            {
                view = convertView;
            }

            // var textview = new TextView(context);
            var myimageView = view.FindViewById&lt;ImageView&gt;(Resource.Id.my_image_vieww);
            var textview = view.FindViewById&lt;TextView&gt;(Resource.Id.my_text_view);

            // imageView = new ImageView(context);
            myimageView.LayoutParameters = new LinearLayout.LayoutParams(340, 340);
            myimageView.SetScaleType(ImageView.ScaleType.CenterCrop);
            myimageView.SetPadding(8, 8, 8, 8);

            string playerid = participants.Tables[0].Rows[position][0].ToString();
            com.organizemyleague.www.PhotoManagerLogon myService = new com.organizemyleague.www.PhotoManagerLogon();
            DataSet MyPhotoDataSet = myService.GetPhoto(MyUser.Username, MyUser.Password, playerid);
            byte[] imageBytes = (byte[])MyPhotoDataSet.Tables[0].Rows[0][0];
            Bitmap bitmap = BitmapFactory.DecodeByteArray(imageBytes, 0, imageBytes.Length);
            myimageView.SetImageBitmap(bitmap);
            if (textview != null)
            {
                textview.Text = participants.Tables[0].Rows[position][1].ToString();
            }
            return myimageView;
        }
    }

The first time through the GetView method, converView is null and I am able to accress both the textview and the imageview when the XML is inflated.  On the second pass I am unable to access the textview.  I tested for a null textview so I could see if at least the first image would display with a textview.  The code compiled and ran, but all that was displayed were the images.  The XML is:

&lt;LinearLayout xmlns:android=&quot;http://schemas.android.com/apk/res/android&quot;
    xmlns:app=&quot;http://schemas.android.com/apk/res-auto&quot;
    xmlns:tools=&quot;http://schemas.android.com/tools&quot;
    android:orientation=&quot;vertical&quot;
    android:layout_width=&quot;match_parent&quot;
    android:layout_height=&quot;wrap_content&quot;&gt;
  &lt;ImageView
      android:layout_width=&quot;match_parent&quot;
      android:layout_height=&quot;250dp&quot;
      android:scaleType=&quot;centerCrop&quot;
      android:id=&quot;@+id/my_image_vieww&quot; /&gt;
  &lt;TextView
      android:textAppearance=&quot;?android:attr/textAppearanceLarge&quot;
      android:layout_width=&quot;match_parent&quot;
      android:layout_height=&quot;wrap_content&quot;
      android:id=&quot;@+id/my_text_view&quot; /&gt;
&lt;/LinearLayout&gt;

The failure of both of these suggest to me that a imageview and textview cannot be displayed together.  This I believe to be a bug.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/456378/unable-to-put-imageview-and-textview-on-same-line.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/791478">original linked feedback ticket</a>.

### Source

[796211](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796211)

**Comment by pauldipietro** [comment]
Looks like it's a Xamarin.Android issue that was misfiled?
