### ISSUE TITLE
[Feedback] Updated Xamarin.Forms Nuget, Built -> 2000+ build errors

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5315]
### Description

<p>Updated Xamarin.Forms Nuget, Built -&gt; 2000+ build errors, cleaned and all built successfully.

Mainly an issue as it is a false negative for devs.</p>
<a href="https://developercommunity.visualstudio.com/content/problem/458389/updated-xamarinforms-nuget-built-2000-build-errors.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/793311">original linked feedback ticket</a>.

### Source

[796209](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796209)

**Comment by pauldipietro** [comment]
We will need more information about the sorts of build errors occurring. Probably something involving VS rather than XF itself.

**Comment by samhouts** [comment]
@alexkblount Is this consistently reproducible? Can you show us what errors you see?

Thanks!

**Comment by samhouts** [comment]
@alexkblount  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
