### ISSUE TITLE
[Feedback] SkiaSharp and WPF

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5316]
### Description

<p>I'm using skiasharp in a XF multiplatform application (xamarin forms)

A basic android example with 

 &lt;forms:SKCanvasView x:Name=&quot;cview&quot;  EnableTouchEvents=&quot;True&quot; Touch=&quot;SKCanvasView_Touch&quot; PaintSurface=&quot;SKCanvasView_PaintSurface&quot; WidthRequest=&quot;100&quot; HeightRequest=&quot;100&quot; BackgroundColor=&quot;Accent&quot;&gt;&lt;/forms:SKCanvasView&gt;

in a .net stadard library is running without problems.

With WPF i can't see anything.

Is forms:SKCanvasView supported in WPF Xamarin forms?</p>
<a href="https://developercommunity.visualstudio.com/content/problem/437153/skiasharp-and-wpf.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779019">original linked feedback ticket</a>.

### Source

[796225](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796225)

**Comment by pauldipietro** [comment]
[This issue](https://github.com/mono/SkiaSharp/issues/486) on the SkiaSharp repo is relevant.
