### ISSUE TITLE
Add BarBackgroundColor parameter for the Shell Element.

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#5327]
## Summary
Add BarBackgroundColor parameter for the Shell Element same NavigationPage parameter.

Thanks.

**Comment by HobDev** [comment]
@MaxenceSAUNIER Shell have TabBarBackgroundColor if I understand your requirement clearly.
Thanks

**Comment by jfversluis** [comment]
I think this is indeed already possible?
