### ISSUE TITLE
[XamlC] Error should be thrown when x:DataType="{x:Type XXX}" is specified in XAMLC

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#5330]
### Description

When DataType is specified like: x:DataType="{x:Type vm:SomeViewModel}" compilation succeeds and project runs but element doesn't benefit from xamlc compilation

### Steps to Reproduce

Add  x:DataType="{x:Type vm:SomeViewModel}" to any element

### Expected Behavior

Project build should fail with some error complaining about x:DataType format

### Actual Behavior

Procect build succeeds
### Basic Information

- Version with issue: 4.4
- Last known good version: none
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: 7.1

### Screenshots

![image](https://user-images.githubusercontent.com/3065454/53125728-ebc0f480-355e-11e9-961f-26faa5fecf18.png)

**Comment by StephaneDelcroix** [comment]
x:DataType expects a type literal, not a type object. We can see if it's possible to support this behavior in the future.

**Comment by tmt242001** [comment]
Issue still exist in Xamarin .Forms 3.6, if built in release mode.

**Comment by StephaneDelcroix** [comment]
@tmt242001 the PR isn't even merged yet
