### ISSUE TITLE
Entry border collapsed when change color dynamically

### ISSUE THREAD

**Issue by KarthikRajaAKR** [xamarin/Xamarin.Forms#5333]
### Description
Here I am using an entry where initially I'm setting a background color and using entry renderer I have given a color for Tint. But in runtime while changing the background color I'm mapping the color to renderer's background color, hence the tint color set to the renderer's(EditText's) background color automatically. Hence in dynamic ,the Tint is not visible while tintcolor overlaps along with background color. 
### Steps to Reproduce

1. Run a sample with entry and change tint color using renderer.
2. Change background color of renderer and not from forms.
3.The background color is seen the color which we given for tint.

### Expected Behavior
The background color and tint color should be shown as given.

### Actual Behavior
The tint color set to the background color of edit text(renderer)

### Basic Information

- Version with issue: Xamarin.Forms : 3.1.0.697729
- IDE: Visual studio 2017

### Screenshots

I have given blue color to border but it remains as gray in initial loading

![image](https://user-images.githubusercontent.com/41435300/53147805-adfbb480-35ce-11e9-99c6-77a683ce8307.png)

Changed color in run time border collapsed.

![image](https://user-images.githubusercontent.com/41435300/53147841-c7046580-35ce-11e9-9a68-233d5292df1e.png)

### Reproduction Link

Please provide a suggestion on above issue, If the above case is achievable then please provide a sample.
Thank you in advance.

**Comment by pauldipietro** [comment]
It seems you intended to attach a reproduction, but forgot to do so.

**Comment by akarthikraja18** [comment]
I don't have simple reproduction sample, I explained the needed behavior. Do you really need reproduction link?

**Comment by AjitKRuin** [comment]
[Uploading TintColorIssue.zip…]
Hi @pauldipietro.I have attached the issue reproducing sample please check it.

**Comment by samhouts** [comment]
Are you using a custom renderer to do change the border color?

**Comment by akarthikraja18** [comment]
I have used Entry renderer of Xamarin version 2.5.1.527436

**Comment by samhouts** [comment]
@akarthikraja18 Can you try uploading your sample again? It didn't seem to work. Thanks!

**Comment by samhouts** [comment]
@KarthikRajaAKR @AjitKRuin  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
