### ISSUE TITLE
PlatformEffects not working with ToolbarItem - OnAttached method not called

### ISSUE THREAD

**Issue by jashan07** [xamarin/Xamarin.Forms#5337]
### Description
When attaching an effect to the toolbaritem, the OnAttached method in either iOS or Android doesn't get called. The very same effect does work for other views such as label.
### Steps to Reproduce
create the effect class
   ```
 public static class ChangeFontEffect
    {
        public static readonly BindableProperty FontProperty = BindableProperty.CreateAttached("Font",
            typeof(string),
            typeof(ChangeToolbarFontEffect),
            null, propertyChanged: OnFontChanged);

        private static void OnFontChanged(BindableObject bindable, object oldValue, object newValue)
        {
            if(bindable is Label labelControl)
            {
                if (!labelControl.Effects.Any((e) => e is ChangeToolbarFontEffect))
                    labelControl.Effects.Add(new ChangeToolbarFontEffect());
            }
            else if(bindable is ToolbarItem toolbarItem)
            {
                if (bindable is ToolbarItem)
                    if (!toolbarItem.Effects.Any((e) => e is ChangeToolbarFontEffect))
                        toolbarItem.Effects.Add(new ChangeToolbarFontEffect());
            }
            return;
        }

        public static string GetFont(BindableObject view)
        {
            return (string)view.GetValue(FontProperty);
        }

        public static void SetFont(BindableObject view, string value)
        {
            view.SetValue(FontProperty, value);
        }

        class ChangeToolbarFontEffect : RoutingEffect
        {
            public ChangeToolbarFontEffect() : base("CustomEffectTest.ChangeToolbarFontEffect") { }
        }
    }

```

Add effect to ToolbarItem in XAML
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:effects="clr-namespace:CustomEffectTest.Effects"
             x:Class="CustomEffectTest.MainPage">
    <ContentPage.ToolbarItems>
        <ToolbarItem Text="ﭗ" effects:ChangeFontEffect.Font="Material Design Icons"></ToolbarItem>
    </ContentPage.ToolbarItems>
    <Switch effects:ChangeFontEffect.Font="Material Design Icons"></Switch>
</ContentPage>

```
Create the platform specific class
```
[assembly: ResolutionGroupName("CustomEffectTest")]
[assembly: ExportEffect(typeof(ChangeToolbarFontEffect), "ChangeToolbarFontEffect")]
namespace CustomEffectTest.Droid
{
    class ChangeToolbarFontEffect : PlatformEffect
    {
        protected override void OnAttached()
        {
            try
            {
                control = Control as TextView;
                Typeface font = Typeface.CreateFromAsset(Forms.Context.ApplicationContext.Assets,        ChangeFontEffect.GetFont(Element));
                control.Typeface = font;
            }
            catch(Exception e)
            {
            }
        }

        protected override void OnDetached()
        {
        }
  }
}
```
### Expected Behavior
When the toolbaritem is created, depending on iOS of the device, the OnAttached method in the platform specific class should be called. 
### Actual Behavior
The OnAttached method is never called, not even with an exception.
### Basic Information

- Version with issue:
- Last known good version: visual studio (15.9.1), .Net Framework (4.7.03056) and Xamarin.Forms (3.3.0.967583) also tested with Xamarin.Forms(3.5.0.169047)
- IDE: Visual studio (15.9.1)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP: - 
- Android Support Library Version: 27.0.2.1
- Nuget Packages: 
1.  NETStandard.Library (2.0.3)
2.  Xamarin.Android.Support.Design (27.0.2.1)
3.  Xamarin.Android.Support.V4 (27.0.2.1) 
4.  Xamarin.Android.Support.v7.AppCompat (27.0.2.1)
5. Xamarin.Android.Support.v7.CardView (27.0.2.1)
6. Xamarin.Android.Support.v7.MediaRouter (27.0.2.1.)
7. Xamarin.Forms (3.3.0.967583)
- Affected Devices:

### Reproduction Link
https://github.com/jashan07/CustomEffectTest

**Comment by samhouts** [comment]
Interesting! `ToolbarItems` are a special type of control. They don't really use the same type of renderers that the other controls use, so the effects aren't automatically attached. This will take some investigation to see if we can support this. I'll mark it as an enhancement. Thanks!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
