### ISSUE TITLE
 Xamarin.UWP app usually hangs when using narrator

### ISSUE THREAD

**Issue by licanhua** [xamarin/Xamarin.Forms#5340]
### Description
Because we have wrong automation implementation for ListViewRenderer in Xamarin.Forms.Platform.UAP, it caused infinite loop in XAML framework. The problem is introduced by `new ListViewAutomationPeer(List)`.

Concerned code is Xamarin.Forms.Platform.UAP/ListViewRenderer.cs
```
protected override AutomationPeer OnCreateAutomationPeer() { 
    return List == null ? new FrameworkElementAutomationPeer(this) : 
                    new ListViewAutomationPeer(List); 
}
```

If we have a Xamarin application and create a LIstView, The xaml tree is like this:
ListViewRender
    ListView

When ListView AUtomationPeer ask for its parent, it points back to itself.
ListView AutomationPeer -> ListViewRender AutomationPeer -> ListView AutomationPeer -> ListViewRender AutomationPeer.

### Steps to Reproduce
It's tracked by internal [Bug 20500989](https://microsoft.visualstudio.com/OS/_workitems/edit/20500989)

### Actual Behavior
app has no response

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by NavaneethS** [comment]
I also face the same issue. With the Narrator open, if we click any of the ListView elements the app hangs and never responds. Although it is not consistent. The sample is attached. 

[ListViewNarrator.zip](https://github.com/xamarin/Xamarin.Forms/files/3153061/ListViewNarrator.zip)
