### ISSUE TITLE
Xamarin.Forms Nuget Update on Xamarin App

### ISSUE THREAD

**Issue by dotfig** [xamarin/Xamarin.Forms#5341]
### Description
I am having issues when upgrading to the newest version of Xamarin.Forms nuget package in my Xamarin mobile app

### Expected Behavior
Run successfully in Debug mode

### Actual Behavior
My build is failing during runtime in InitializeComponent(). I am getting a System.Reflection.TargetException at ````global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(LoginPage));````

### Basic Information
- Version with issue: Xamarin.Forms 3.5.0.169047
- Last known good version: 3.2.0.871581
- IDE: Visual Studio
- Platform Target Frameworks:
  - Android: 5.1

**Comment by pauldipietro** [comment]
Can you try to upload a reproduction if a full clean/rebuild/restart of VS doesn't resolve the issue?

**Comment by dotfig** [comment]
### Reproduction:
1. Plug in my Android device
2. Run my application in debug mode
3. Error pops up

Could it be something with the way my xaml is set up?

**Comment by dotfig** [comment]
@pauldipietro It seems like I am having issues with Xamarin.Forms Entry. When I comment this Entry out, it runs with no error but when I leave it how it is, it fails
````
<StackLayout Orientation="Horizontal">
     <Label Text="Login:" HeightRequest="35" VerticalOptions="Center" WidthRequest="100" HorizontalOptions="Start" />
     <Entry x:Name="txtUsername" Text="{Binding txtUsername, Mode=TwoWay}" WidthRequest="200" HorizontalOptions="Center" />
</StackLayout>
````

I personally do not see why this is happening. Any ideas?

**Comment by dotfig** [comment]
### Update
I was able to find a work around for this problem that I am having. I changed my code to the following:
````
<StackLayout Orientation="Horizontal">
     <Label Text="Login:" HeightRequest="35" VerticalOptions="Center" WidthRequest="100" HorizontalOptions="Start" />
     <Editor x:Name="txtUsername" Text="{Binding txtUsername, Mode=TwoWay}" WidthRequest="200" HorizontalOptions="Center" />
</StackLayout>
````
I was able to run this in debug mode on my Android device. However, I would still rather use ``<Entry/>`` because I have a lot of screens that I would need to change in order for all functions of my app to work.

**Comment by samhouts** [comment]
@dotfig Try enabling XamlCompilation (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xamlc). It might help you find the error. Thanks!
