### ISSUE TITLE
[MacOs] Menu not shown

### ISSUE THREAD

**Issue by SergejDK** [xamarin/Xamarin.Forms#5344]
### Description
When I call the `SetMenu(BindableObject object, Menu menu)` in the App.cs file nothing is shown. 
Seems like this: https://github.com/xamarin/Xamarin.Forms/issues/2659

### Steps to Reproduce

1. Create a Xamarin.Forms.MacOs project
2. Create a Menu var in App.cs
3. Call SetMenu like this: `SetMenu(this, menu)`

### Expected Behavior
Menubar is shown.

### Actual Behavior
Menubar is not shown

### Basic Information

- Version with issue: Xamarin.Forms 3.5
- Last known good version: not known
- IDE: Visual Studio for Mac Community (7.7.4)
- Affected Devices: Mac (MacOs Mojave 10.14.3)

### Reproduction Link

https://github.com/SergejDK/XFMenuReproduction

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
