### ISSUE TITLE
[Enhancement] Add more data to TapGestureRecognizer.Tapped event

### ISSUE THREAD

**Issue by SebastianKruseWago** [xamarin/Xamarin.Forms#5347]
It would be far better to have the some informations about where the tap happens in the TapGestureRecognizer.Tapped event. Raising this event without any information is in some situations enough but in some you really want to know where the tap happens.

**Comment by toomasz** [comment]
Need that enhancement as well. It's necessary when working with SkiaSharp

**Comment by PureWeen** [comment]
Closed in favor of
https://github.com/xamarin/Xamarin.Forms/issues/3479
