### ISSUE TITLE
Xamarin Forms NetworkChange Events Don't Fire in iOS

### ISSUE THREAD

**Issue by comfr3ak** [xamarin/Xamarin.Forms#5348]
### Description

When using the NetworkChange class and connecting to the NetworkAddressChanged and NetworkAvailabilityChanged events, the events only fire immediately after they are connected. 

Then if you disconnect Wifi or do something that should cause them to fire again, they never fire. 

https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkchange?view=netframework-4.7.2

### Steps to Reproduce

1. Connect to NetworkChange.NetworkAddressChanged and NetworkChange.NetworkAvailabilityChanged events to event handlers
2. Disconnect iOS wifi or change to another accesspoint
3. Events never fire to tell you the address changed or the availability changed

### Expected Behavior

In Windows UWP and Android, the events fire whenever the wifi connection changes to indicate the wiifi disconnected so the ip changes to 0.0.0.0 and then it fires again when the wifi reconnects and notifies you that the network address has changed to a new ip. 

### Actual Behavior

When using the NetworkChange class in Xamarin Forms on iOS, the events fire once after they are connected to event handlers. Then they never fire again no matter what changes with the iOS wifi or network settings. 

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version:
- IDE: VS 2017 15.9.1
- Platform Target Frameworks: iOS 
  - iOS: 12.1 
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPad and iPhone

### Reproduction Link

// Subscribe to NetworkChange events
NetworkChange.NetworkAddressChanged += new NetworkAddressChangedEventHandler(m_OnNetwork_AddressChanged);
NetworkChange.NetworkAvailabilityChanged += m_OnNetwork_NetworkAvailabilityChanged;

private void m_OnNetwork_AddressChanged(object sender, EventArgs e)
{
	// Only fires once on iOS regardless of network change activity	
}			

private void m_OnNetwork_NetworkAvailabilityChanged(object sender, NetworkAvailabilityEventArgs _Event)
{
	// Only fires once on iOS regardless of network change activity
}

**Comment by samhouts** [comment]
@comfr3ak Can you please attach a sample project that shows this issue? Thanks!

**Comment by samhouts** [comment]
@comfr3ak  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
