### ISSUE TITLE
XP 3.6.0 Pre 2 TextDecorations.Strikethrough crashes app

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5351]
ios only

Setting the StrikeThrough on a label in a ListView crashed app in scrolling

### Steps to Reproduce

Create a simple custom control:

```
public class StrikethroughLabel : Label
    {
	 
	    public StrikethroughLabel()
	    {
			 
	    }

        public static readonly BindableProperty IsStrikethroughProperty = BindableProperty.Create(
            propertyName: "IsStrikethrough",
            returnType: typeof(bool),
            declaringType: typeof(StrikethroughLabel),
            defaultValue: false,
            defaultBindingMode: BindingMode.OneWay,
            propertyChanged: StrikethroughChanged);

        public bool IsStrikethrough
        {
            get { return (bool)GetValue(IsStrikethroughProperty); }
            set { SetValue(IsStrikethroughProperty, value); }
        }

        private static void StrikethroughChanged(BindableObject bindable, object oldValue, object newValue)
        {
            if (bindable is StrikethroughLabel c)
            {
                if (c?.Text != null && c.Text.Length > 0)
                {
                    if (newValue is true)
                    {
                        c.TextDecorations = TextDecorations.Strikethrough;
                    }
                    else
                    {
                        c.TextDecorations = TextDecorations.None;
                    }
                }
            }
        }
    }
```

Add this to a List view that is long enough to scroll. Bind the model so that the Lbale has a strike through. Scroll up and down a lot and the app will crash

### Expected Behavior
Not crash
### Actual Behavior
Crash
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2017 Newest
- Platform Target Frameworks: 
  - iOS:  Newest
  - Android: WORKS IN ANDROID
   
 

LOG ATTACHED

[Crash Log.txt](https://github.com/xamarin/Xamarin.Forms/files/2895818/Crash.Log.txt)

**Comment by pauldipietro** [comment]
Probably the same as #5326

**Comment by ianvink** [comment]
No. different. The Label has text and appears with strike, BUT, it through an error when you scroll the cell out then back into the view.

**Comment by pauldipietro** [comment]
I was referring to the root cause potentially being the same because they both involve a strikethrough being used in some fashion causing a crash on iOS. Referring to the other issue probably makes it easier to track as well.
