### ISSUE TITLE
[CollectionView] Updating the ItemsLayout type should refresh the layout

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#5354]
More a work task than a bug due to the ongoing development of `CollectionView` (but we'll just categorize it as a bug for now), it should update its layout when switching the `ItemsLayout` types from a `ListItemsLayout` to `GridItemsLayout`. A good example of where this would be used is in a UI where the user is allowed to toggle between those layouts, such as in a retail app. 

This is supposedly semi-functional on iOS but wasn't personally tried. Android doesn't update the layout.

### Steps to Reproduce

1. Use a CollectionView with one of the two layout types
2. Switch to the other layout type in app (such as via a button tap)

### Expected Behavior
The CollectionView updates its layout to the new type.

### Actual Behavior
The CollectionView does not update its layout until leaving and reentering the page (such as with tabs).

**Comment by taublast** [comment]
Another possible usage is to switch the number of columns when the device is rotated.. Much needed.

**Comment by EmilAlipiev** [comment]
Is it not possible to have this for UWP also?
