### ISSUE TITLE
Android: Remove legacy code, all checks and code related to unsupported API level

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5357]
### Android: Remove legacy code

XF supports Android 4.4 (Level 19) and up. There's now a bunch of legacy code checking if API Level is greater than versions less than Android 4.4 and based on the result, there's different logic and APIs called. I think all that can be removed, making code a bit cleaner.

**Comment by andreinitescu** [comment]
I can help with this if I get a green light.

**Comment by samhouts** [comment]
We do not plan to implement new features that will be supported on API 19, but we also do not plan to break anyone using API 19 if we don't have to. This is a good task for the future when we have no customers that rely on older APIs, but we'll have to defer it for now. Thank you!
