### ISSUE TITLE
The Footer in ListView always has some space even setting the ContentView's IsVisible to false

### ISSUE THREAD

**Issue by henryyue2010** [xamarin/Xamarin.Forms#5359]
### Description

I need to show/hide the footer in a ListView. But after setting the Footer's ContentView IsVisible to false,
there is still empty space in the place of footer.

I saw it was a bug in https://bugzilla.xamarin.com/show_bug.cgi?id=51961, but the workaround in the post doesn't work.

Is the bug fixed or any one knows solution?

### Steps to Reproduce

1. Create a ListView with a Footer
2. Binding the IsVisible property of the ContentView in FooterTemplate to a variable
3. Set the binding value to false

### Expected Behavior
The footer is completely hidden

### Actual Behavior
The content is hidden, but there is empty space in the place of Footer

### Basic Information

- Version with issue:

Xamarin.Forms: 3.5
Target Framework: Android 8.1

**Comment by PureWeen** [comment]
@henryyue2010 

I feel like this is something that would go into enhancements as this is the behavior on ios and android. Changing it to so the space disappears would be a breaking change

Can you try something like this?
I did a few small tests with this and it looks like this reclaims the space. 

if below doesn't work then can you attach a repro of your scenario and we can see if there's a workaround or if there is actually a bug?

```
		public bool FooterVisible { get; set; }
		object footer = null;
		object header = null;
		private void Hide_Clicked(object sender, EventArgs e)
		{
			FooterVisible = !FooterVisible;

			footer = listView.Footer ?? footer;
			header = listView.Header ?? header;

			if(FooterVisible)
			{
				listView.Footer = footer;
				listView.Header = header;
			}
			else
			{
				listView.Footer = null;
				listView.Header = null;
			}
		}
```

**Comment by samhouts** [comment]
@henryyue2010  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
