### ISSUE TITLE
A global exception handler for Xamarin Forms

### ISSUE THREAD

**Issue by MrClan** [xamarin/Xamarin.Forms#5368]
### Feature Request
A global exception handler for Xamarin Forms. Primary objective is to avoid the app from crashing at unexpected scenarios. The app may or may not choose to kill itself inside this handler.

**Comment by amirvenus** [comment]
It would be nice to have this feature as even when placing codes inside try catch blocks, sometime an exception is thrown but when I set a breakpoint, it says the exception is null!

I don't know whether that's a Visual Studio bug or XF's fault.

**Comment by KSemenenko** [comment]
Try using [AppCenter](https://appcenter.ms/) Often errors happen not only in the .net environment, but also in the device itself.

**Comment by jfversluis** [comment]
> Primary objective is to avoid the app from crashing at unexpected scenarios

I don't think this is possible, at least not for iOS. From the [Apple documentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Exceptions/Concepts/UncaughtExceptions.html):

> If an exception is not caught, it is intercepted by a function called the uncaught exception handler. The uncaught exception handler always causes the program to exit but may perform some task before this happens.

**Comment by MrClan** [comment]
@jfversluis like mentioned in the link you posted:

> You can set a custom function as the uncaught exception handler using the NSSetUncaughtExceptionHandler function; you can obtain the current uncaught exception handler with the NSGetUncaughtExceptionHandler function.

An event exposed from XF that simply subscribes to such platform specific exception handler can be a starting point.

**Comment by qq1688** [comment]
I found AppCenter can't catch all the exceptions, still search something can globally catch all the crash for Xamarin.Forms...

**Comment by xamiell** [comment]
That will be very useful

**Comment by jfversluis** [comment]
Hey everyone! Thanks for your interest in this! This won't make its way into Xamarin.Forms anymore as we're only adding bugfixes, stability fixes and things necessary to support new OS versions that are coming out. It's clear that there is a good number of people that are interested in this so I added it to the list of things to consider for .NET MAUI.

Feel free to open a detailed feature request there in the meantime.

Thank you!
