### ISSUE TITLE
iOS Visual not work in 4.0Pre4 and Pre5

### ISSUE THREAD

**Issue by rubenglam** [xamarin/Xamarin.Forms#5370]
### Description

Material doesn't work in iOS (iPad). I'm using Xamarin Forms 4.0Pre5 (in Xamarin.Forms 4.0Pre3 works fine). Android works fine.

### Steps to Reproduce

1. Create a entry or button with Visual="Material"

### Expected Behavior

Entry and buttons with material design.

### Actual Behavior

Entry and buttons basic style.

### Basic Information

- Version with issue: Xamarin.Forms 4.0Pre5 and 4.0Pre4
- Last known good version: 4.0Pre3
- IDE: Visual Studio 2017 15.9.5
- Platform Target Frameworks: 
  - iOS: 12.1  
  - Android: API 28 (9.0)   
- Android Support Library Version: API 28.0.0.1
- Affected Devices: iPad Air 12.1

### Screenshots

Xamarin.Forms 4.0Pre3
---------------------------

![img_20190225_123751](https://user-images.githubusercontent.com/39260220/53335926-16170700-38fd-11e9-8c9b-bb4af83319f5.jpg)

Xamarin.Forms 4.0Pre5
---------------------------

![img_20190225_125100](https://user-images.githubusercontent.com/39260220/53335936-1d3e1500-38fd-11e9-8f59-9480613cab4f.jpg)

### Project

https://github.com/rubenglam/Xamarin.Forms-5370

**Comment by samhouts** [comment]
@rubenglam Can you uninstall the Xamarin.Forms packages and reinstall them? I think a dependency was missed in the update. Let me know if that works. If not, please attach your sample project. Thanks!

**Comment by rubenglam** [comment]
I have created a new project for show the issue.
Project: https://github.com/rubenglam/Xamarin.Forms-5370

**Comment by PureWeen** [comment]
@rubenglam  we still need to get better documentation on this together but you need to install this
https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/4.0.0.169046-pre5

And call FormsMaterial.Init from the appdelegate on ios
