### ISSUE TITLE
[Enhancement] Print 

### ISSUE THREAD

**Issue by amirvenus** [xamarin/Xamarin.Forms#5371]
Printing a document directly from an app is arguably an essential part of modern apps (especially the corporate apps).

While it is possible to implement printing using DI on each platform, I recently had a project targeting UWP, WPF, macOS, iOS and Android.

I had to spend a lot of time implementing Print functionality on each platform and still, it's buggy on UWP and couldn't figure out a way to do it on macOS so I ended up using Device.OpenUri to open the document in a browser which basically means distracting the user by leaving the app.

I suggest that Xamarin Print should offer two features as the bare minimum:

1. Discovering available printers (on the network, bluetooth, attached to the device, etc.)
2. Printing a document by sending it directly to the printer albeit allowing the user to interact with native print dialogs of each platform (i.e choosing Colour, number of pages and copies, etc.)

**Comment by pauldipietro** [comment]
I think this might be a better candidate for Xamarin.Essentials, and I see that you filed an [enhancement](https://github.com/xamarin/Essentials/issues/718) there as well.

**Comment by amirvenus** [comment]
> I think this might be a better candidate for Xamarin.Essentials, and I see that you filed an [enhancement](https://github.com/xamarin/Essentials/issues/718) there as well.

Yes I thought it could be part of the Essentials as well but then Essentials mostly focuses on iOS, Android and UWP and considering that Print would deem to have a higher priority to be available for WPF, UWP, macOS and GTK (as these are the platforms most Print-necessary applications are developed for), I thought I might post it on the main XF repo as well so that hopefully it will find its way on the Roadmap and made available across all platforms.

**Comment by jfversluis** [comment]
I agree this is not something that should be part of Xamarin.Forms/.NET MAUI but something related. At the very least, we won't be adding this to Forms anymore. Thanks for the suggestion!
