### ISSUE TITLE
[Enhancement] UWP: MasterDetailPage.MasterBehavior="SplitOnLandscape" should be responsive on UWP based on window size.

### ISSUE THREAD

**Issue by JeroMiya** [xamarin/Xamarin.Forms#5374]
## Summary
On UWP, when MasterDetailPage.MasterBehavior is set to SplitOnLandscape or SplitOnPortrait, the current behavior is to initially display the master as a popover when the application starts, then when the user interacts with the app, the popover disappears and afterwards the behavior is the same as Popover. This isn't useful.

What I'd like to see is the master behavior to automatically behave like Split when the window is wide enough, then responsively switch to Popover with a hamburger menu when the window is resized to a certain threshold (possibly we could specify the threshold, but that would be an API change. Without an API change, just pick a reasonable threshold or base it off the width of the master view?).

## API Changes

No API changes. Well, maybe, you could add API to specify the window width thresholds to switch from Split to Popover behavior. Otherwise just pick a reasonable default threshold, and then no API changes would be necessary.

## Intended Use Case
Use case is a responsive desktop application that automatically splits the master/detail views when the window is wide enough, or responsively collapses to a popover behavior when the window is smaller.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
