### ISSUE TITLE
Unfocus System.ObjectDisposedException: Cannot access a disposed object

### ISSUE THREAD

**Issue by transis2** [xamarin/Xamarin.Forms#5376]
### Description

Since xamarin forms 3.5 I'm having this error when call .Unfocus()

### Steps to Reproduce

1. navigate to "about" in hamburguer menu
2. navigate to "browse" in hamburguer menu
3. click "add" 
4. click "cancel"
5. boom

### Expected Behavior
the keyboard unfocus was set to this element

### Actual Behavior
System.ObjectDisposedException: Cannot access a disposed object

### Basic Information

- Version with issue: 4.0 pre5
- Last known good version: 3.4
- IDE: Visual Studio 2017 Professional

### Reproduction Link

https://github.com/transis2/EntryCrash/blob/master/UnfocusEntryCrash.7z

**Comment by transis2** [comment]
PS: Not solved with version 3.6.0.220655

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @transis2 

I am getting same exception while calling unfocus() method of entry in forms version 3.6 stable, 
Exception details are attached 

![image](https://user-images.githubusercontent.com/42173947/54269992-6c926f80-45a4-11e9-980c-bc7b00ceb1d5.png).

So Can you let us know when this issue will get fixed? Please provide approximate time line.

**Comment by transis2** [comment]
Hi @DeepikaBalaSubramaniyan

I don't work at Microsoft, so I can't give you the time line.

I just know that it was assigned to @PureWeen in the Sprint 150 https://github.com/xamarin/Xamarin.Forms/projects/32#card-18683261

**Comment by transis2** [comment]
Miss Ballmer time where developers matters. Nutella has fired almost all developers to cut costs and looks like there's only one men @PureWeen working to fix all issues...

**Comment by transis2** [comment]
Solved with 3.6.0.293080 and 4.0.0.304370-pre8 

Thanks to @PureWeen and @samhouts
