### ISSUE TITLE
Grouped ListView Header is empty under RELEASE configuration

### ISSUE THREAD

**Issue by FrankChen021** [xamarin/Xamarin.Forms#5377]
### Description

when an object returned by GroupBy function provided by Linq is binded to a grouped list view, the header is invisible under release configuration, but is visible under DEBUG mode.

as for customized data structure which can be binded to a grouped view, there's no such bug. I attached a sample project to reproduce this bug, and there're two grouped list view in a page, the first demonstrates the bug.

### Steps to Reproduce
1.  add a grouped list view to a page
2.  use GroupBy function provided by LINQ to get a grouped data structure
3.  bind the data generated by step 2 to the list view
4. change the build configuration to RELEASE

### Expected Behavior
the header is empty under RELEASE configuration, BUT it works well under DEBUG configuration

### Actual Behavior
the header should be shown

### Basic Information

- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS Version: 12.2.1.15 (Visual Studio Community)
  - Android: SDK 9.1.7.0 
- Nuget Packages: Xamarin.Forms 2.5.1.527436 and 3.4.0.1008975, these two versions have this bug. I think that versions between these two all have this bug

- Affected Devices:

Android， iOS
There's no such bug on UWP platform

### Screenshots

**Android**
![2](https://user-images.githubusercontent.com/6525742/53354254-5e681080-3961-11e9-97d6-dd577c29b23f.jpg)
![3](https://user-images.githubusercontent.com/6525742/53354264-60ca6a80-3961-11e9-8b4e-24f131422428.jpg)

**iOS**
![1](https://user-images.githubusercontent.com/6525742/53354267-632cc480-3961-11e9-9413-80c4590c5171.jpg)

![4](https://user-images.githubusercontent.com/6525742/53354430-b6067c00-3961-11e9-9b48-c463b3f40ab1.jpg)

Reproduction Link

[tempApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2901569/tempApp.zip)

**Comment by KSemenenko** [comment]
What are your Linker settings?

**Comment by FrankChen021** [comment]
@KSemenenko the settings are the default ones. I guess this bug
is related to the IGrouping data structure

**Comment by samhouts** [comment]
See if excluding the `IGrouping` type and/or `System.Linq` namespace from the linker will help. Thanks! https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker

**Comment by FrankChen021** [comment]
hi @samhouts , it does work. Thanks a lot. The linker configuration I'm using for both iOS and Android is:

```
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="System.Core">
    <namespace fullname="System.Linq" />
  </assembly>
</linker>
```

**Comment by jhonata0302** [comment]
> hi @samhouts , it does work. Thanks a lot. The linker configuration I'm using for both iOS and Android is:
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <linker>
>   <assembly fullname="System.Core">
>     <namespace fullname="System.Linq" />
>   </assembly>
> </linker>
> ```

thx 

Create a xml file in the root of the IOS or Android project, name can be any, but I called it "LinkDescription.xml".
Right click the file, properties, in Build Action, select LinkDescription.
Write this in the file.
