### ISSUE TITLE
[Feedback] XAMLC Compiler does not seem to catch many syntax errors

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5378]
### Description

Noticing today that the XAMLC compiler isnt catching even simple mistakes.
```xaml
Margin="2,3,4,"
``` 

causes no-line number errors (file is named)
```xaml
<TapGestureRecognizer Tapped="{Binding ThisIsTappedCommand}" />
```

causes a cascade of code behind errors without giving any pointers to the line causing the problem

<a href="https://developercommunity.visualstudio.com/content/problem/465568/xamlc-compiler-does-not-seem-to-catch-many-syntax.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798099">original linked feedback ticket</a>.

### Source

[801790](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801790)

**Comment by StephaneDelcroix** [comment]
error in
```xaml
Margin="2,3,4,"
```

is correctly reported at compile time, with XamlC on.
> Xamarin.Forms.Xaml.XamlParseException : Position 6:12. Cannot convert "1,2,3," into Xamarin.Forms.Thickness

at runtime, it could be enhanced
> System.InvalidOperationException : Cannot convert "1,2,3," into Xamarin.Forms.Thickness

(no position info)

**Comment by StephaneDelcroix** [comment]
I have a fix that wraps runtime type converter exceptions into a XPE

> Xamarin.Forms.Xaml.XamlParseException : Position 6:12. Type conversion failed
  ----> System.InvalidOperationException : Cannot convert "1,2,3," into Xamarin.Forms.Thickness

**Comment by StephaneDelcroix** [comment]
error in binding to event for the following xaml:
```xaml
<Button Clicked="{Binding FooBar}" />
```

with XamlC on:
> Xamarin.Forms.Xaml.XamlParseException : Position 3:13. No property, bindable property, or event found for 'Clicked', or mismatching type between value and property.

runtime:
> Xamarin.Forms.Xaml.XamlParseException : Position 3:13. Property Clicked is not found or does not have an accessible getter

**Comment by StephaneDelcroix** [comment]
this is the best I can do with the info provided

**Comment by StephaneDelcroix** [comment]
#6771 makes binding to even valid
