### ISSUE TITLE
[Enhancement] Small layout performance improvements

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5385]
## Summary

I noticed that in Layout.cs the `LogicalChildrenInternal` getter is actually a method:

		internal override ReadOnlyCollection<Element> LogicalChildrenInternal
		{
			get { return _logicalChildren ?? (_logicalChildren = new ReadOnlyCollection<Element>(InternalChildren)); }
		}

I'm not sure if `LogicalChildrenInternal` gets inlined. Even if it does, there's still a check every time it runs.

There are methods which read the property several times, one example is `Layout.UpdateChildrenLayout()` (see [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Layout.cs#L237)). Doing a quick search by `LogicalChildrenInternal` within the method, shows it reads `LogicalChildrenInternal` property many times, and sometimes within a loop.

## Changes

Maybe just read property once within the method at the beginning and then use it everywhere:

```
var logicalChildrenInternal = LogicalChildrenInternal;
```

or just set the backing field in c-tor and use it:

```
Layout()
{
    _logicalChildren = new ReadOnlyCollection<Element>(InternalChildren);
}

internal override ReadOnlyCollection<Element> LogicalChildrenInternal => _logicalChildren;
```

Also, I think the backing field (which is private) should be readonly:

		ReadOnlyCollection<Element> _logicalChildren;

If you agree with these changes I can help with implementing them.

**Comment by StephaneDelcroix** [comment]
Thanks @andreinitescu for this suggestion.

First, this property is `virtual`, something that a field can't be. Second, it's accessible from outside of the type, so it'd be a bad pattern to have a `public` field. Third, even if it might be technically a perf improvement, that improvement is not significant enough to be registered (we're speaking of nanosecond scale).

So, all in all, the flexibility, the versatility of the Property is more desirable than an hypothetical perf improvement.

For the future, if you want to do perf improvements (they're more than welcome), here's what you should do:
- Profile your code and measure, repeat.
- Find the most expensive calls (everything not in the top 5 doesn't probably matter)
- propose a fix
- remeasure, 20 times
