### ISSUE TITLE
Animations don't work on Samsung Galaxy J7 Pro?

### ISSUE THREAD

**Issue by mshwf** [xamarin/Xamarin.Forms#5392]
### Description
I have created some animations, simple animations, but they don't work on my mobile phone, they work on every other device/ emulator.
### Steps to Reproduce

1.  create a simple animation (using Animation class, or the extension methods).
2. run it on Samsung Galaxy J7 Pro (Android 8.1.0)

### Expected Behavior
Animations work.
### Actual Behavior
Animation doesn't work, but instead, there's a blink motion between the start and the end value of the property being animated.
### Basic Information
- Version with issue: 3.5
- Last known good version: Not known (always happens)
- IDE: VS 15.9.7
- Platform Target Frameworks: 

  - Android: 8.1.0

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung Galaxy J7 Pro

**Comment by samhouts** [comment]
@mshwf Can you attach a sample project showing the animations that you're attempting? Thanks!

**Comment by mshwf** [comment]
@samhouts here's the [sample project](https://github.com/mshwf/AnimationSample)
and this is the project running on Samsung Galaxy J7 Pro: https://i.stack.imgur.com/TCD0A.gif

**Comment by hyurii** [comment]
Hi,
Try to turn of save battery mode, it should work then.
BR
KG

**Comment by mshwf** [comment]
@hyurii thanks, this is the real reason of blocking the animation!
