### ISSUE TITLE
DisplayActionSheet is Inconsistent with Other Xamarin Platforms

### ISSUE THREAD

**Issue by mandel-macaque** [xamarin/Xamarin.Forms#5401]
_From @AceCoderLaura on February 27, 2019 4:5_

### Steps to Reproduce

1. Create a page in a PCL Xamarin library
2. Call Xamarin.Forms.Page.DisplayActionSheet("a", "b", "c")
3. Tap away from the dialog on iOS and you'll get **"b"**
4. Tap away from the dialog on Android and you'll get **null**

### Expected Behavior

It is expected that the behaviour is consistent between platforms.

### Actual Behavior

The actual behaviour is not consistent between platforms.

### Environment

```
JetBrains Rider 2018.3.3
Build #RD-183.5619.41, built on February 9, 2019
Licensed to Laura Bailey
Subscription is active until August 13, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

### Build Logs

[JetBrainsLog.ReSharperBuild_2019_02_27_04_01_14_2971.log](https://github.com/xamarin/xamarin-macios/files/2908521/JetBrainsLog.ReSharperBuild_2019_02_27_04_01_14_2971.log)

_Copied from original issue: xamarin/xamarin-macios#5675_

**Comment by mandel-macaque** [comment]
Hello, this is the repository dedicated at the iOS bindings but not the forms. Which is what you are talking about. I will move the issue to the correct project.

**Comment by samhouts** [comment]
@AceCoderLaura I assume that the most desirable behavior in this situation is to return null. Is that what you'd expect? Thanks!

**Comment by samhouts** [comment]
@AceCoderLaura  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
