### ISSUE TITLE
[VS2019 Preview 3] Build errors not showing in Error list

### ISSUE THREAD

**Issue by melucas** [xamarin/Xamarin.Forms#5403]
### Description
When building an iOS Xamarin Forms project and their is an error in the build process, the error list, for example, will show 0 of 1 Error.

### Steps to Reproduce
1. Create a new Xamarin Forms project
2. Build the project to make sure it works.  Add an error.
3. Compile the project again and switch to the ErrorList

### Expected Behavior
Should see the errors listed in the ErrorList

### Actual Behavior
Errors are not shown in the ErrorList and you have to dig into the Output build log to find the issue

### Basic Information
- Version with issue: VS 2019 v 16.0.0 Preview 3.0
- Last known good version: VS 2017
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/1330087/53504509-168bdb00-3a80-11e9-92b5-451b4c19a9f9.png)

![image](https://user-images.githubusercontent.com/1330087/53504693-679bcf00-3a80-11e9-9564-3b4bccf26af9.png)

**Comment by samhouts** [comment]
@melucas Can you please submit this issue as feedback within Visual Studio itself? I think that will direct the problem to the proper team. Thanks!

**Comment by melucas** [comment]
@samhouts Done.  Thank you
