### ISSUE TITLE
[Enhancement]build support for Xamarin.Forms in Visual studio for Mac 2019

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5409]
## Summary
Lots of Xamarin.Forms developers use Mac for development. We Mac users also want to read, debug and contirbute to Xamarin.Forms repo. But as of now it is only possible with Visual Studio for Windows. 

## API Changes

This may need work on both Visual studio for Mac and Xamarin.Forms .

## Intended Use Case
Not all Xamarin.Forms developer have two development machines. They either use Mac or Windows. If Xamarin.Forms development is possible on both platforms lots of people will able to contribute.

**Comment by StephaneDelcroix** [comment]
please provide more info. I'm using VSMac2019 without any problem

**Comment by HobDev** [comment]
@StephaneDelcroix I'm also using VSMac2019 for Xamarin.Forms app development. But I want to contribute to the Xamarin.Forms repo on GitHub. But it is not possible to debug and build Xamarin.Forms on VSMac2019.

**Comment by StephaneDelcroix** [comment]
doing it everyday, and as we speak. what's the problem

**Comment by HobDev** [comment]
But the [readme](https://github.com/xamarin/Xamarin.Forms/blob/master/README.md) on Xamarin.Forms repo says it is only possible with VS2017. Would you mind explaining how to debug Xamarin.Forms on VSMac2019.

**Comment by HobDev** [comment]
@StephaneDelcroix As per your understanding the information in [readme](https://github.com/xamarin/Xamarin.Forms/blob/master/README.md) is not correct. Please update the correct info and open a pull request. This is needed immediately so that the visitors get correct info.

**Comment by HobDev** [comment]
I also requested this feature in developercommunity website. The view the feature request go [here](https://developercommunity.visualstudio.com/idea/472323/build-support-for-xamarinforms-in-visual-studio-fo.html)
