### ISSUE TITLE
Xamarin.Forms UWP Navigation bar Disappear while press back button to MasterDetailPage 

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#5412]
MasterDetailPage is the root page.
Press button from master page's button ,Navigate to Setting Page is done.
Press the back button on the top of the window , Navigate to Mainpage(MasterDetailPage).
Navigation bar Disappear
(I had been set `<NavigationPage.HasNavigationBar>true</NavigationPage.HasNavigationBar>` in detail page)

Sample code here:
[TopBarSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2914278/TopBarSample.zip)

**Comment by mrlacey** [comment]
This appears to be an issue when the detail page does not have a `Title` set.
The repro project can be made to work the correct way by setting a title in `TitlePage.xaml`
e.g.
```
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            Title="index"
             x:Class="TopBarSample.IndexPage">
```

[The docs say](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#creating-the-master-page) that "the MasterDetailPage.Master page must have its Title property set, or an exception will occur" but I can't find any mention of needing to set the Title for content pages. 
It must be set and not be whitespace for this to work.

This is not specifically about the back button and more about the lack of title. 
I'm happy to continue investigating and currently looking at how to set up an appropriate UITest to recreate this.

I'm working on the assumption that the NavigationBar should always be visible in the scenario defined and that being hidden when no Title is set is an error.

**Comment by mrlacey** [comment]
As an alternative workaround, if you don't want to set the tile on the page that is loaded as the Detail, you can set the title on the MasterDetailPage. It's only if neither of these has a title that the described behavior is shown.
If you want these to not show a title you can always set the title to a non-visible character, such as "Title="&#x200B;"`
