### ISSUE TITLE
Animation tasks do not complete when Animator duration scale is set to off in developer options

### ISSUE THREAD

**Issue by TomDeVlaminck-vdkspaarbank** [xamarin/Xamarin.Forms#5421]
### Steps to Reproduce

1. Set Animator duration scale to off in developer settings on an Android device.
2. Call any animation -> var animationTask = label.FadeTo(1)
3. await the resulting task

### Expected Behavior
Animation completes instantly, Task immediately completes.
### Actual Behavior
Animation does not occur, Task never completes. Tested with Xamarin Forms 3.5.0.169047

This caused our production app to completely break on several Android devices. due to fading of a loading screen never completing. Apparently many of our users turn Animator duration scale off to improve the speed of their device.

This bug is simular to this fixed issue https://github.com/xamarin/Xamarin.Forms/issues/1556

### Basic Information

- Version with issue: 3.5.0.169047
- Platform Target Frameworks: 
  - Android: Android 9.0 
- Affected Devices: most android devices

**Comment by AntRemo** [comment]
@TomDeVlaminck-vdkspaarbank 
I too was dealing with this, I have animations enabled and disabled code paths. 

I wish there was a way to override this setting in X.Forms and not use the OS setting, but I haven't figured out a way around it.

**Comment by AntRemo** [comment]
@TomDeVlaminck-vdkspaarbank 

If you desire, I was able to force the animator duration scale to 1 when it is set to 0 by following the approach undocumented here:
https://arpytoth.com/2016/12/20/android-objectanimator-independent-of-global-animator-duration/ 

He states that this is an undocumented method, but I have not experienced any production errors using this approach.

I ultimately wanted to show animations, regardless of the users settings as it my animations are very short and infrequent but provide a much richer experience and conversion.

Here is my C# version


public void OverrideAnimationDurationAsNeeded()
  
      {
            var resolver = global::Android.App.Application.Context.ContentResolver;
            var scaleName = global::Android.Provider.Settings.Global.AnimatorDurationScale;
            var scale = global::Android.Provider.Settings.Global.GetFloat(resolver, scaleName, 0);

            if (scale > 0)
                return;

            try
            {
                var classForName = JNIEnv.FindClass("android/animation/ValueAnimator");
                var methodId = JNIEnv.GetStaticMethodID(classForName, "setDurationScale", "(F)V");

                JNIEnv.CallStaticVoidMethod(classForName, methodId, new JValue(1f));

                Ticker.SetDefault(Device.PlatformServices.CreateTicker());
            }
            catch (Exception ex)
            {
                // Log Error
            }
        }

I then call this at the end of my App.xaml.cs OnStart and OnResume methods.

Please note I am still disabling animations for low power state, as and [AndroidTicker](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AndroidTicker.cs) disabled itself when in low power state. Lastly, this approach depends on the current implementation of the AndroidTicker and could break in the future if changed. So be sure to monitor changes to this logic if you decide to use this approach.

**Comment by zoli13** [comment]
Issue confirmed, this totally breaks the app if user switches animation off.

**Comment by Huaba93** [comment]
We have the same problem. 

There are several reasons why animations can be disabled. 2 that are known to us:
1. developer settings
2. on some devices through the power saving mode

This is really critical, as @zoli13  said ` this totally breaks the app if user switches animation off.`

Why doesn't anyone take care of it?

**Comment by thisisthekap** [comment]
Fixed the issue in #7092.

**Comment by samhouts** [comment]
closed by #7092
