### ISSUE TITLE
Xamarin form page preview in VS2019 not working when using shell

### ISSUE THREAD

**Issue by nickwood2009** [xamarin/Xamarin.Forms#5435]
Using VS2019 (preview 2.0)
 with xamarin.forms v4.0.0.169046-pre5
viewing Android and using Shell
When using the page preview I get render errors (see screen)
its hard to read and I cant copy out the error content, or extend the frame to view, but it seems to be related to the flags set for "Shell_Experimental" in the MainActivity.cs in the Android project:

global::Xamarin.Forms.Forms.SetFlags("Shell_Experimental", "Visual_Experimental", "CollectionView_Experimental", "FastRenderers_Experimental");
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);

Is there a solution for this because rapid dev will suffer greatly without it?
![untitled](https://user-images.githubusercontent.com/1969372/53706847-060ca380-3e78-11e9-970c-b42bf7fb7e86.png)

> VS bug [#807897](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/807897)
Parent: #2415

**Comment by samhouts** [comment]
@nickwood2009 Thanks for the report! This particular error message was resolved in P3, but it was unfortunately replaced by new ones. We're working on the problem!

**Comment by samhouts** [comment]
closed by #5955
