### ISSUE TITLE
[Enhancement] Improve error reporting on XAML with error

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5439]
## Summary

In App.xaml, I have the following custom target type "local:MyControl" with the "local" prefix I forgot to declare:
```
<?xml version="1.0" encoding="utf-8" ?>
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyApp.App">
    <Application.Resources>
        <ResourceDictionary>
            <Style TargetType="local:MyControl">
                <Setter Property="ControlTemplate">
                    <ControlTemplate>
                        <StackLayout Orientation="Horizontal" />
                    </ControlTemplate>
                </Setter>
            </Style>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

When trying to compile, the error looks generic:

![image](https://user-images.githubusercontent.com/743918/53728504-94ceef80-3e7b-11e9-9300-450d5e24a084.png)

The build output doesn't help either:

> 1>  Compiling Xaml, assembly: obj\Debug\netstandard2.0\MyApp.dll
> 1>  App.xaml : error : Object reference not set to an instance of an object.
> 1>Done building target "XamlC" in project "MyApp.csproj" -- FAILED.

It would be very helpful to immediately know what's the actual problem.

This is obviously a simple example, in a bigger project after some work is done, it's more confusing to try track down the actual issue.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
