### ISSUE TITLE
Xamarin.forms 4.0.0.169046-pre5  ScrollView "Orientation=both" crashes on Android and iOS

### ISSUE THREAD

**Issue by Refka-Benmahmoud** [xamarin/Xamarin.Forms#5441]
### Description
In ContentPage, ScrollView with property "Orientation=both" crashes the application in xamarin.forms 4.0.0.169046-pre5.

-- Platform Target Frameworks: 
-iOS
-Android
-not tested on UWP

**Comment by jcmanke** [comment]
Duplicate of #5247 fixed by #5383

**Comment by samhouts** [comment]
Duplicate of #5247
