### ISSUE TITLE
[Enhancement Shell] - Allow setting OffscreenPageLimit for Android

### ISSUE THREAD

**Issue by KyleTraynor** [xamarin/Xamarin.Forms#5444]
## Summary
In Shell, when having top tabs, in android it does not cache the pages and reloads them when swapping between tabs. It would be great to be able to set the OffscreenPageLimit for android
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.androidspecific.tabbedpage.offscreenpagelimit?view=xamarin-forms
Parent: #2415

**Comment by KyleTraynor** [comment]
I cant seem to figure out how to add a shell label to this issue..?

**Comment by PureWeen** [comment]
@KyleTraynor @michaelstonis for this issue do you specifically want `OffscreenPageLimit` or would a property that just lets you toggle the renderer retention behavior be desired? 

Currently on Shell when you navigate between Flyout items it also destroys the entire renderer hierarchy and then recreates it as you navigate so this feels like the same type of issue there.

Something like

```C#
public enum RendererLifeSpan
{
     Default, DisposeWhenInActive,KeepForever
}
```

**Comment by michaelstonis** [comment]
I feel like maintaining them is more inline with what I would expect for what is typically a top-level control through. This is consistent with the behavior of iOS (although, I am not sure how flyout items are disposed in iOS, but my feeling is that their are retained).

I realize that this could cause some renderer/memory friction for Android though. In that is the case, perhaps keeping a MRU cache or setting the offscreen limit to be _reasonably_ high would resolve the issue. I feel like having an offscreen limit of 5 is pretty high, but probably not too high for most use cases.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
