### ISSUE TITLE
[Enhancement, Maps, UWP] Use a native control for Pins on UWP

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#5445]
## Summary

On UWP, a Pin is rendered as a ContentControl with a big ugly vector image. This is in contrast to the other Windows platforms, which both use native map pin controls (PushPin on WPF, GMapImageMarker on GTK). 

## API Changes

Instead of the current PushPin control, use a native control such as MapIcon on UWP.

## Screenshots
Current UWP Pin: 
![Current UWP Pin](https://user-images.githubusercontent.com/6132629/53759137-3e66ae80-3e85-11e9-80b9-ee59eda30867.png)

Current WPF Pin:
![Current WPF Pin](https://user-images.githubusercontent.com/6132629/53759172-4f172480-3e85-11e9-8cbb-3eaaf4ddba6d.png)

Proposed UWP Pin using MapIcon:
![Proposed UWP Pin](https://user-images.githubusercontent.com/6132629/53759191-58a08c80-3e85-11e9-8474-73a718d4b075.png)

**Comment by jfversluis** [comment]
Wow! How did we pick that icon? 😅  I'm afraid we won't be changing it for Forms anymore, but let's make sure we do better for .NET MAUI!
