### ISSUE TITLE
[Android]FrameRenderer is creating new FrameDrawable every time BackgroundColor changes without disposing

### ISSUE THREAD

**Issue by sstragier** [xamarin/Xamarin.Forms#5446]
### Description
When the BackgroundColor or CornerRadius properties of a Frame are changed, the FrameRenderer (not the FastRenderer), creates a new instance of the FrameDrawable without disposing the previous instance.

For my project, we have multiple frames that have blinking background colors and over a couple minutes, the blinking visibly slows down, and if left long enough, the app crashes. Because the FrameDrawable isn't being disposed, the Bitmap is still using memory and the listener for the Frame's property changes is still listening and still drawing the background to the bitmap.

### Steps to Reproduce

1. Ensure the Android Activity is not AppCompat
     - AppCompat is using the FastRenderer which doesn't have this issue
2. Add a couple frames to a page
3. Set a timer to fire every 250ms and to change the background color every time it fires

### Expected Behavior
The frames should keep blinking at the same frequency (every 250ms)

### Actual Behavior
After a couple minutes, the blinking of the frames slows down. The Android Choreographer will start to log that the UI thread is doing too much and that frames are being skipped. Eventually the app will crash due to running out of memory

### Basic Information

- Version with issue: 3.4.0 through 3.5.0
- Last known good version: 3.3.0.912540 (it seems this issue was introduced with pull request #3933)
- IDE: Visual Studio 2017 (15.9.5)
- Platform Target Frameworks:
  - Android: 8.1
- Affected Devices: Emulator

### Reproduction Link
[App.zip](https://github.com/xamarin/Xamarin.Forms/files/2928346/App.zip)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/53994856-7cf3a780-40d7-11e9-92c1-e0b14bf859c6.png)
