### ISSUE TITLE
GTK: MasterDetailPage Master page black section when navigation in detail

### ISSUE THREAD

**Issue by PaulMDemers** [xamarin/Xamarin.Forms#5447]
### Description
I created a basic GTK Forms application, added a minimal MasterDetailPage and when the Detail page is a navigationpage a section appears black in the master page, when the navigationpage is removed, it's resolved.

### Steps to Reproduce

1. Code is attached
2. Remove NavigationPage around ContentView to see issue resolve

### Expected Behavior
Top section of Master page shouldn't be black.

### Actual Behavior
Top section is black

### Basic Information

- Version with issue: 3.5
- Last known good version:
- IDE: MonoDevelop
- Platform Target Frameworks:
  - GTK

### Screenshots

![screenshot from 2019-03-04 17-06-49](https://user-images.githubusercontent.com/959461/53766165-1d5f8700-3ea0-11e9-8406-ecc39074c351.png)

### Reproduction Link

[gtkXF.zip](https://github.com/xamarin/Xamarin.Forms/files/2928383/gtkXF.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
