### ISSUE TITLE
ItemSizingStrategy MeasureAllItems does not work for iOS

### ISSUE THREAD

**Issue by Dresel** [xamarin/Xamarin.Forms#5455]
### Description

I was playing around with the `CollectionView` on iOS and was facing problems with uneven row height. I saw there was an `ItemSizingStrategy` introduced lately, but it's still behaving weird though.

### Steps to Reproduce

1. Open the `DataTemplateGallery` CollectionViewGallery
2. Switch to `MeasureAllItems` to get the following result

<img src="https://user-images.githubusercontent.com/1769090/53488499-c49e8180-3a8e-11e9-9bf1-52fd4e1ff4c1.PNG" width="300">

4. Swiping to right and coming back shows the following result

<img src="https://user-images.githubusercontent.com/1769090/53488498-c49e8180-3a8e-11e9-9b22-1a5967a03ee1.PNG" width="300">

### Expected Behavior

Items should have the same height / width when setting `ItemSizingStrategy` to `MeasureAllItems`

### Actual Behavior

See above

### Basic Information

- Version with issue: master branch (50dbbcf5)
- Last known good version: -
- Platform Target Frameworks: 
  - iOS:  12.1
- Affected Devices: iPhone 6 (iOS 12.1.4)

**Comment by kingces95** [comment]
Reproduces as described.

**Comment by Dresel** [comment]
Is there any known work around (except setting height manually)? At the moment it's really useless with variable dynamic content.

**Comment by adrianknight89** [comment]
Agreed. This needs to be given priority, imo.

**Comment by timahrentlov** [comment]
I can't get any dynamic sizing to work on android with Pre 8.

**Comment by timahrentlov** [comment]
With regards to ItemSizingStrategy, is https://gist.github.com/hartez/7d0edd4182dbc7de65cebc6c67f72e14/revisions current? 

It is mentioned here (https://devblogs.microsoft.com/xamarin/xamarin-forms-4-0-feature-preview-an-entirely-new-point-of-collectionview/) as a way to keep track of this component.

I spent some time today trying to use CollectionView on android, and found out that ItemSizingStrategy does not work. A more prominent display of status would have saved me some grief. And time.

**Comment by pfedotovsky** [comment]
> Items should have the same height/width when setting ItemSizingStrategy to MeasureAllItems

Is it correct? According to the spec, MeasureFirstItem should produce the same height/width, while MeasureAllItems should measure all items individually.

**Comment by adrianknight89** [comment]
Netiher `MeasureFirstItem` nor `MeasureAllItems` seems to be working. 

`MeasureFirstItem` measures the first item and everything else is given the same dimension. The problem is if you scroll back and forth slowly, items on the left side of the screen change their size,

`MeasureAllItems` allocates real estate as large as the largest item in each column. That's why the blue box is centered in the middle. Also, there is some stutter in the scrolling. #7152

**Comment by velocitysystems** [comment]
@hartez @samhouts This seems like a significant gap in the `CollectionView` spec.
Just wondering if there is any official word on when this will be supported?

**Comment by samhouts** [comment]
This is on the backlog. I don't currently have an estimate of when we may begin work on this item. Thank you for your patience!

**Comment by danoliver1** [comment]
@hartez @samhouts is there any update on the progress of this issue? Is there a workaround?
CollectionView looks to solve performance issues we're having with ListView but this issue is a complete blocker for us.

**Comment by quentinR0bert** [comment]
Hi, did we have some news about this issue ?

**Comment by ChaseFlorell** [comment]
@PureWeen @samhouts is this shipped in the latest 4.6 stable that was just shipped yesterday?
I updated my app, and this is what I see.
![Simulator Screen Shot - iPhone 11 - 2020-04-30 at 13 25 25](https://user-images.githubusercontent.com/471626/80755650-1228db00-8ae6-11ea-8b93-c2a79d7dc5b7.png)

Once I scroll the view a little bit, then everything collapses correctly
![Simulator Screen Shot - iPhone 11 - 2020-04-30 at 13 25 57](https://user-images.githubusercontent.com/471626/80755705-253bab00-8ae6-11ea-8444-63ac67a699a2.png)

This is my xaml

```xaml
<RefreshView Command="{Binding RefreshCommand}"
             IsRefreshing="{Binding IsRefreshing}">
    <CollectionView x:Name="list"
                    BackgroundColor="Transparent"
                    ItemsSource="{Binding VisibleDataObjectCollection}"
                    ItemsUpdatingScrollMode="KeepScrollOffset"
                    ItemSizingStrategy="MeasureAllItems"
                    RemainingItemsThresholdReachedCommand="{Binding LoadNextPageCommand}"
                    RemainingItemsThreshold="{StaticResource RemainingItemsThreshold}"
                    SelectionMode="Single"
                    SelectionChangedCommand="{Binding ShowDetailsCommand}"
                    SelectionChangedCommandParameter="{Binding SelectedItem, Source={RelativeSource Self}}">
        <CollectionView.Behaviors>
            <behaviors:ClearSelectedItemAfterSelectionBehavior />
        </CollectionView.Behaviors>
        <CollectionView.ItemTemplate>
            <templateSelectors:FieldListItemSelector x:DataType="models:FieldCropYearListModel">
                <templateSelectors:FieldListItemSelector.FieldWithCropTemplate>
                    <DataTemplate>
                        <StackLayout Style="{StaticResource RepeaterStack}">
                            <controlTemplates:TwoRowListItemTemplate VerticalOptions="Fill"
                                                                     HorizontalOptions="Fill"
                                                                     PrimaryText="{Binding FieldName}"
                                                                     SecondaryText="{Binding CropDescription}"
                                                                     Color="{Binding SeedColour, Converter={StaticResource ColorConverter},ConverterParameter={StaticResource White}}" />
                            <BoxView Style="{StaticResource HorizontalDivider}" />
                        </StackLayout>
                    </DataTemplate>
                </templateSelectors:FieldListItemSelector.FieldWithCropTemplate>
                <templateSelectors:FieldListItemSelector.FieldWithoutCropTemplate>
                    <DataTemplate>
                        <StackLayout Style="{StaticResource RepeaterStack}">
                            <controlTemplates:SingleRowListItemTemplate VerticalOptions="Fill"
                                                                        HorizontalOptions="Fill"
                                                                        Text="{Binding FieldName}" />
                            <BoxView Style="{StaticResource HorizontalDivider}" />
                        </StackLayout>
                    </DataTemplate>
                </templateSelectors:FieldListItemSelector.FieldWithoutCropTemplate>
            </templateSelectors:FieldListItemSelector>
        </CollectionView.ItemTemplate>
        <CollectionView.EmptyView>
            <controlTemplates:EmptyDataTemplate Text="{x:Static resx:AppResources.FieldsPage_ListEmptyMessage}" />
        </CollectionView.EmptyView>
        <CollectionView.Header>
            <ContentView Padding="3" />
        </CollectionView.Header>
        <CollectionView.Footer>
            <StackLayout Padding="6, 16">
                <Button Text="{x:Static resx:AppResources.ActivityListPage_ClearFilter}"
                        Style="{StaticResource TextOnlyButton}"
                        IsVisible="{Binding HasFiltersApplied}"
                        Command="{Binding ClearFiltersCommand}" />

                <ActivityIndicator HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   Color="{StaticResource PrussianBlue}"
                                   IsRunning="{Binding IsLoadingPage}"
                                   IsVisible="{Binding IsLoadingPage}" />
            </StackLayout>
        </CollectionView.Footer>
    </CollectionView>
</RefreshView>
```

**Comment by samhouts** [comment]
@ChaseFlorell Can you please open a new issue? Thanks!

**Comment by ChaseFlorell** [comment]
@samhouts this appears to be the exact same issue. However, I won't be opening a new issue as I'm on my last ONE hour of this contract and I will not have any ability to do follow-up.

Maybe someone else on the team wants to follow up.
@Alex-Wang08, @kelci2017

**Comment by KMWenyon** [comment]
Any updates on this?

**Comment by phimu** [comment]
Still no news here?

**Comment by EnglishDave** [comment]
This is still broken on iOS. Even with  ItemSizingStrategy="MeasureAllItems", it only measures the first item and then applies that height to every row.

Examp,e XAML below that exhibits this issue:

        <CollectionView
                Grid.Row="1" 
                Grid.Column="0" 
                Grid.ColumnSpan="3"
                ItemsSource="{Binding ChangeOrderItems}"
                SelectionMode="None"
                ItemSizingStrategy="MeasureAllItems"
                >
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid
                            ColumnSpacing="30"
                            >
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition Width="*"/>
                                <ColumnDefinition Width="*"/>
                                <ColumnDefinition Width="*"/>
                            </Grid.ColumnDefinitions>
                            <Grid.RowDefinitions>
                                <RowDefinition Height="Auto"/>
                            </Grid.RowDefinitions>
                            <Label
                                Grid.Column="0"
                                Grid.Row="0"
                                Text="{Binding Original}"
                                TextColor="{x:Static core:Colors.TitleTextColor}" />
                            <Label
                                Grid.Column="1"
                                Grid.Row="0"
                                Text="{Binding Current}"
                                TextColor="{x:Static core:Colors.TitleTextColor}" />
                            <Label
                                Grid.Column="2"
                                Grid.Row="0" 
                                Text="{Binding Change}"
                                TextColor="{x:Static core:Colors.TitleTextColor}" />
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
