### ISSUE TITLE
[Android] ScrollView crashes when setting ScrollbarFadingEnabled to false in Custom Renderer

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5461]
### Description

If an Android View sets *ScrollbarFadingEnabled* to false then the drawable on a ScrollView won't get initialized which will cause a crash during Draw

From what I can tell looking at the android source two scenarios will initialize the scrollbars on a view

1) if the view is inflated with scrollbars set to anything but NONE
https://android.googlesource.com/platform/frameworks/base/+/a175a5b/core/java/android/view/View.java#2956
2) if the user calls awakenScrollBars
https://android.googlesource.com/platform/frameworks/base/+/a175a5b/core/java/android/view/View.java#8384

Since we don't inflate the views with attributes we need to call awakenScrollBars so the drawable initializes

I've found that in some cases this crash will happen without a Custom Renderer but I haven't been able to reproduce that scenario in our Control Gallery. 

This issue didn't happen when we inherited from ScrollView and not NestedScrollView. NestedScrollView is a totally different implementation than ScrollView so my guess is that the loading behavior or how those drawables are used changed

### Steps to Reproduce

1. Create a Custom Renderer that inherits from ScrollViewRenderer
2.  set ScrollbarFadingEnabled in the constructor or in the override of OnElementChanged
3. App will now crash when using that scrollview

### Expected Behavior
Shouldn't crash

### Actual Behavior
Crashes

### Basic Information

- Version with issue: 3.5+
- Last known good version: 3.4

**Comment by samhouts** [comment]
closed by #5562

**Comment by DopaFiend** [comment]
This is still a problem by the way.
