### ISSUE TITLE
[Enhancement] Provide List View Add editable entry item, auto focus Entry

### ISSUE THREAD

**Issue by robinne** [xamarin/Xamarin.Forms#5467]
## Summary
Upon adding a new object to a bound ListView (add to underlying list of objects in ViewModel), allow a programmatic way to focus the first (typically only) entry field in the new row. Users are used to new entry fields automatically being focused and ready to type. Similar to iOS "Reminders" where the list is editable. But in this case, a command has added a new entry to the end of the list.

## API Changes
idea:
Add an event to listview when a new item has been added to item source. (ChildAdded does not appear to be an event for this as it does not fire).

Add the ability to access the UI elements that make up the DataTemplate - . e.g.
listView[lastindex].FindByName("entryField").Focus();
or
listView.LastDataTemplate().FindByName("entryField").Focus();

Some way to get at the entry field in the last row to focus it. Knowing that "entryField" is not unique in the list and we need to get access to the specific row's data template. Perhaps without using an x:name.

## Intended Use Case
This would be used in a list with an "Add" menu item. User would remain on the list page and automatically scrolled to the bottom, entered into the entry field, keyboard displayed and not covering entry field. The only piece missing, that I can see, is the ability to find the last data template and focus it's entry field.

Ideally this would be a feature of the list, without having to handle it. But, would at least like better access to the UI elements. Apologies if this already exists, or is done another way.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
