### ISSUE TITLE
Changelog for Xamarin.Forms 3.6.0.220655 is missing

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#5468]
### Description

The changelog for the nuget update Xamarin.Forms 3.6.0.220655 is missing.

### Steps to Reproduce

1. open Xamarin.Forms project with installed Xamarin.Forms 3.5.0.169047
2. open "Manage NuGet packages"
3. go to Updates and you see Xamarin.Forms 3.6.0.220655

but on release notes page I only see the [pre2 documentation with lower version number](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/3.6/3.6.0-pre2)

### Expected Behavior

See a link to documentation of the 3.6 update

### Actual Behavior

There is no link to documentation of the 3.6 update

![image](https://user-images.githubusercontent.com/8274816/53863185-c5cd3280-3fe9-11e9-9fc9-ad39a0c47f18.png)

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/53862992-4fc8cb80-3fe9-11e9-8bc4-19d85700e609.png)

![image](https://user-images.githubusercontent.com/8274816/53862973-417aaf80-3fe9-11e9-8729-ec162fcbc064.png)

**Comment by MagicAndre1981** [comment]
Is it safe to update to this version or was this a publish mistake? If this is an official release when can we expect the changelog?

**Comment by MagicAndre1981** [comment]
I just tried the version and now get a [System.TypeLoadException: 'Could not find Windows Runtime type 'Microsoft.Graphics.Canvas.UI.Xaml.CanvasImageSource'.'](https://github.com/xamarin/Xamarin.Forms/issues/5188)

**Comment by jsmarcus** [comment]
@MagicAndre1981 I believe you will need to add a reference to Win2D.uwp

**Comment by MagicAndre1981** [comment]
@jsmarcus yes, I did this. 

But the package should list this dependency and automatically add it to the project. I don't see this:

```
<group targetFramework="UAP10.0">
        <dependency id="NETStandard.Library" version="2.0.1" />
        <dependency id="Microsoft.NETCore.UniversalWindowsPlatform" version="6.0.12" />
      </group>
```

**Comment by jsmarcus** [comment]
Agreed. Just wanted to make sure it wasn't gating for you.

**Comment by samhouts** [comment]
The publish was not a mistake. There is sometimes a delay publishing the release notes. The issue that you're hitting is listed as a known issue, however. Not to worry, we will be releasing additional patches shortly. Thanks!

**Comment by samhouts** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/3.6/3.6.0

**Comment by MagicAndre1981** [comment]
@samhouts changelog for [3.6.0.293080](https://www.nuget.org/packages/Xamarin.Forms/3.6.0.293080) is again missing 

![image](https://user-images.githubusercontent.com/8274816/55583941-5f8c1a80-5723-11e9-8766-9d62a472abcb.png)

**Comment by MagicAndre1981** [comment]
@samhouts 

ok, changelog is finally online:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/3.6/3.6.0-sr2#wednesday-april-3-2019---xamarinforms-360293080-360-service-release-2

**Comment by samhouts** [comment]
@MagicAndre1981 Thanks! There is sometimes a delay in getting the release notes published, but if you have doubts, you can check https://github.com/xamarin/Xamarin.Forms/releases. Those are usually done right away.

**Comment by MagicAndre1981** [comment]
@samhouts

ok, thanks, great tip. I subscribed to the Releases and look for changelog there.
