### ISSUE TITLE
ApplinkEntry Thumbnail required after upgrading to 3.5/3.6

### ISSUE THREAD

**Issue by veryhumble** [xamarin/Xamarin.Forms#5470]
### Description
After upgrading from Xamarin.Forms 3.4 to Version 3.5 or 3.6 I get the following Exception after trying to Register an AppLinkEntry using `Application.Current.AppLinks.RegisterLink` on iOS.

`InvalidOperationException: Thumbnail must be set to a valid source`

### Steps to Reproduce

1. Register AppLinks with a valid AppLinkEntry
2. Start App
3. Exception is thrown saying Thumbnail is required

### Actual Behavior
I see that Code was changed between [Version 3.4](https://github.com/xamarin/Xamarin.Forms/blob/release-3.4.0-sr2/Xamarin.Forms.Platform.iOS/iOSAppLinks.cs) and [3.6](https://github.com/xamarin/Xamarin.Forms/blob/release-3.6.0-rc4/Xamarin.Forms.Platform.iOS/iOSAppLinks.cs)
Before it was valid to have the `Thumbnail` Property not set, now it's mandatory. While I can certainly provide an ImageSource for example using `ImageSource.FromFile("icon_app.png");` . The requirement is still a change. 
 
### Basic Information

- Version with issue: 3.6.0
- Last known good version: 3.4.0 SR2
- IDE: VisualStudio 8.0 Preview
- Platform Target Frameworks: 
  - iOS:  12.1

Update:
I missed the fact that I used "FromResource" instead of "FromFile" to load the ImageSource, I leave this open, because the Title still and description qualifies.

**Comment by kingces95** [comment]
Change is breaking.

**Comment by samhouts** [comment]
Caused by #4733
