### ISSUE TITLE
Accessibility: On iOS Forms should use DynamicType

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/Xamarin.Forms#5474]
On iOS, Forms should use dynamic type by default, which would provide the different sizes and weights for fonts and should respond to font size changes when instructed by the operating system.

This is necessary for users that need larger font sizes for accessibility reasons, but also would make Forms work better and consistently with the rest of the OS and applications.

Resources:
https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically

Anecdotally, Marco Arment reports that for his own app over 40% of his users do not use the default font size:

https://twitter.com/marcoarment/status/1099295178651783169?s=21

**Comment by hartez** [comment]
We provide accessible text support (cross-platform) via [Device Styles](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/device). On iOS, this is implemented via Dynamic Type. 

However, the set of DeviceStyles is out-of-date. The most obvious omission is `largeTitle`, (added in iOS 11, I believe), but there are probably more. 

I believe our DeviceStyles on Android are similarly out-of-date.
