### ISSUE TITLE
[iOS] The BackgroundColor property for an Entry element is not supported

### ISSUE THREAD

**Issue by lanarchyste** [xamarin/Xamarin.Forms#5489]
### Description

On iOS, when displaying a view, if my XAML has an Entry with a BackgroundColor, it is not supported

On Android, the BackgroundColor property works

### Steps to Reproduce

```
<Entry Text="Home Phone"
             AutomationId="HomePhone"
             BackgroundColor="Red"
             Keyboard="Telephone" />
```

### Expected Behavior

When the Entry element is displayed, the background color used is the color setted by the BackgroundColor property

### Actual Behavior

Despite a different background color, when the Entry element is displayed, the background color is always white

### Basic Information

- Version with issue: 3.6.0.220655
- Last known good version: 3.1.0.583944
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  12.0
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Affected Devices: all iOS devices

**Comment by kingces95** [comment]
Well, works on master... so, the fix is coming!

**Comment by lanarchyste** [comment]
Hi,

I tried Xamarin.Forms 3.6.0.264807 and I still have a issue with the background color on iOS

**Comment by samhouts** [comment]
@lanarchyste Can you please try with 4.0.0-pre10? Thanks!

**Comment by jfversluis** [comment]
I also confirmed that this seems to be working with the latest source
