### ISSUE TITLE
Map Pin Click only works on Android on XF and Maps 3.6

### ISSUE THREAD

**Issue by NeilIrvingMacc** [xamarin/Xamarin.Forms#5490]
### Description
Upgraded to XF 3.6 and Maps 3.6 today all mapping working fine BUT on anything put Android if click on the map pins the click event does not fire or bubble does not come up, this previously worked

### Steps to Reproduce

1. Add a map
2. Add a pin with a click event
3. Click pin, click does not fire

### Expected Behavior
It should work on ALL platforms
### Actual Behavior
Only works on Android
### Basic Information

- Version with issue: 3.6
- Last known good version:3.1 for me
- IDE:
- Platform Target Frameworks: 
  - iOS: 12.1
  - Android: 7.1
  - UWP:  17000 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by andreinitescu** [comment]
@NeilIrvingMacc I don't think this is a regression. On Android, Clicked event was never sent when you clicked the marker, but when you click the balloon (it's called info window Android)

@samhouts I'd like to work on this. 
Is it OK if we change on Android from sending the click event when marker is clicked and not when the info window is clicked?

**Comment by samhouts** [comment]
@andreinitescu Can we make it an option? Maybe a platform specific

**Comment by jcmanke** [comment]
@andreinitescu 
>Is it OK if we change on Android from sending the click event when marker is clicked and not when the info window is clicked?

As a Maps user/contributor I think that would constitute a breaking change, but I would be 100% behind deprecating the existing Clicked event and adding MarkerClicked and InfoWindowClicked events. I actually have that code already written for Android and iOS in my custom renderers and would be happy to pull request it in.

**Comment by andreinitescu** [comment]
@samhouts I'm having a hard time believing anybody is using Clicked event on Android, given that it's actually being fired when you click on the balloon and not on the pin...

**Comment by andreinitescu** [comment]
My suggestion is to actually fix this for Android. I think on iOS and UWP it works as expected, Clicked is sent when you click the Pin.

**Comment by jcmanke** [comment]
iOS also fires it on the info window (annotation view) click, UWP fires on the pin click because there is no info window.

**Comment by samhouts** [comment]
The goal is a consistent experience on all platforms without breaking any existing behavior. I'm sure many developers have worked around the inconsistency, so we have to make sure we don't break any workarounds they have used or come to expect. We're happy to see a collaboration of ideas here! Thank you!!

**Comment by andreinitescu** [comment]
Nobody uses the Clicked event because it just doesn't do what it promises to do.
The documention is wrong: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps.pin.clicked?view=xamarin-forms

> Event that is raised when the pin is clicked

@jcmanke is right, on iOS it's also raised when you click the popup ...

@samhouts Waiting for your input...

**Comment by samhouts** [comment]
Yeah, we meant to discuss that a while ago (https://github.com/xamarin/Xamarin.Forms/issues/2509). I think the idea of adding new events for `MarkerClicked` itself sounds great. I'll point this to the team and see if they have any comments. Thanks!

**Comment by NeilIrvingMacc** [comment]
For info when I click / tap the pin on iOS and UWP the click event is not fired it needs to work on all 3 platforms
