### ISSUE TITLE
Help with complex logic in Webview

### ISSUE THREAD

**Issue by BrunoFreitasgit** [xamarin/Xamarin.Forms#5492]
I'm having trouble getting the following logic to work with a webview. For context, I'm using a custom https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview version. So I'm using JavascriptInterface.

So the flow is this:
1) Instantiate a webview, registering an Action callback called `login`.
2) When page finished loading, I inject a js file. Inside the file, there is a method called `login`. This is the function I want it to run on C#. 
3) When I click on a specific button on the webview, it triggers the file I injected. So my C# login function is executed.
4) Now, I need to return the function return value back to the javascript, where it stopped the execution.

I found several ways to return a value from a javascript function back to C#, but not the opposite. This case is tricky because I'm injecting js that need to run in C# and return back the result to js.

Any help would be appreciated. I can provide some code, I just didn't because I don't want to make a long post

**Comment by samhouts** [comment]
Hi! If you're still looking for assistance, try https://forums.xamarin.com/categories/xamarin-forms. Thanks!
