### ISSUE TITLE
CarouselView TapGesture not working when ItemsSource is set

### ISSUE THREAD

**Issue by ColdThor** [xamarin/Xamarin.Forms#5493]
I noticed some people are having troubles with adding TapGestureRecognizer to the carousel. I debuged my own problem to the fact that the TapGestureRecognizer works if the ItemsSource is null / not set.

My XAML:

            <cv:CarouselViewControl x:Name="carousel"
    
                ShowArrows="false"
                ShowIndicators="true"
                PositionSelected="Handle_PositionSelected"
                Scrolled="Handle_Scrolled"
                Orientation="Horizontal">

                <cv:CarouselViewControl.Behaviors>
                    
                    <behaviors:AutoscrollCarouselBehavior Delay="4000"/>
                </cv:CarouselViewControl.Behaviors>

                

                <cv:CarouselViewControl.GestureRecognizers>
                 <TapGestureRecognizer 
                 Tapped="OnButtonTapped" 
                 NumberOfTapsRequired="1">
                 </TapGestureRecognizer>
                </cv:CarouselViewControl.GestureRecognizers>

            </cv:CarouselViewControl>
        </StackLayout>
The CS behind the XAML:

        InitializeComponent();
        carousel.IsVisible = true;
        carousel.HeightRequest = 150;
        carousel.WidthRequest = 300;
        BindingContext = _vm = new SlideShowViewModel();
        carousel.ItemsSource = _vm.MyItemsSource;  
The BindingContext is unchanged from Demo.

Since I am using the Carousel to display banners I need them to be clickable but cant see a way to do so. Read the related threads but nothing worked.

**Comment by samhouts** [comment]
@ColdThor What CarouselView are you using? A third-party one, or the one in preview? Thanks!

**Comment by ColdThor** [comment]
I am using https://github.com/alexrainman/CarouselView, which was later migrated to Xamarin.Forms

**Comment by samhouts** [comment]
We did not end up migrating that to Xamarin.Forms. We decided to build a different CarouselView into Xamarin.Forms, and it is currently in preview. Sorry for the confusion! You will need to post this issue on Alex's repo. Thanks for the report!
