### ISSUE TITLE
Maps Binding - Possible typo in the bindable property

### ISSUE THREAD

**Issue by djcparker** [xamarin/Xamarin.Forms#5498]
I was looking to see how the template binding was done in #4269  and noticed this line of code :

https://github.com/xamarin/Xamarin.Forms/blob/138791927206ef6c2f64243f8b991ee768ef4193/Xamarin.Forms.Maps/Map.cs#L21

Should this not have been nameof(ItemsSource):

`		public static readonly BindableProperty ItemsSourceProperty = BindableProperty.Create(nameof(ItemsSource), typeof(IEnumerable), typeof(Map), default(IEnumerable),`

**Comment by andreinitescu** [comment]
@djcparker Thanks for reporting this, see #5499

**Comment by kingces95** [comment]
Fixed!

**Comment by samhouts** [comment]
(not merged yet, reopening 😄 )

**Comment by samhouts** [comment]
closed by #5499
