### ISSUE TITLE
Binding on Shell.FlyoutHeaderTemplate not work

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5501]
### Description
If you add a Binding parameter in your Shell.FlyoutHeaderTemplate definition, the Binding not working. If you add Binding at an other place on the code, it working good.

### Steps to Reproduce

1. Add shell
2. Create ViewModel and add BindingContext
3. Create a FlyoutHeaderTemplate  and add Binding

### Expected Behavior
Add content of the Binding

### Actual Behavior
Label is empty

### Basic Information

- Version with issue: 4.0pre-5
- IDE: Windows Visual Studio
- Platform Target Frameworks: 
  - Android: 7
- Affected Devices: ASUS

**Comment by kingces95** [comment]
Could you please attach a zipped reproduction?

**Comment by Moltroon** [comment]
[FlyoutHeaderIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2951524/FlyoutHeaderIssue.zip)

Thanks
