### ISSUE TITLE
Setting DatePicker MinimumDate unexpectedly changes DatePicker Date property

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5505]
### Description

Same issue as https://github.com/xamarin/Xamarin.Forms/issues/4413, but now I have a repro. I'd reopen 4413 if I could.

### Steps to Reproduce

1. Set up a DatePicker in XAML, bind Date to D and MinimumDate to MD
2. Set MD=X and D=Y where Y > X
3. Observe that D is set to X

### Expected Behavior

MinimumDate should only influence Date when less then Date.

### Actual Behavior

Date is reset to MinimumDate even when greater than Date.

### Basic Information

- Version with issue: 3.6.0.220655
- Last known good version: unknown
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://github.com/mfeingol/repros/tree/master/Xamarin.Forms-5505-MinimumDateIssues

**Comment by mfeingol** [comment]
This is still an issue with 4.0.0.482894.

**Comment by mrutter** [comment]
I have the same issue here, with XF 3.6.0.344457.

Moreover I observed that the behavior is influenced by the order used to set the two properties.
In my ViewModel, if I first set D and then MD, D is correctly binded and everything works.
Instead, if I first set MD and then D, D is incorrect.

I hope that someone can solve this (critical) issue.

Thank you.
-m

**Comment by CliffAgius** [comment]
@samhouts can you show me as picking this one up please I think I can see the issue.

**Comment by mfeingol** [comment]
Can confirm the repro app no longer exhibits the problem, so this looks to have been fixed somewhere along the way to 4.3.0.947036.

I'll attempt to remove workaround in my production app tonight, and will close the issue if successful.

**Comment by mfeingol** [comment]
And confirmed.
