### ISSUE TITLE
Compiled Binding does not support Indexer properties

### ISSUE THREAD

**Issue by omghb** [xamarin/Xamarin.Forms#5510]
Visual Studio 2017: 15.9.7
Xamarin.Forms: 3.6.0.220655

Compiled Binding does not support Indexer properties. But it works when Bindings are not compiled.

```
Binding="{Binding Person.Errors[FirstName]}"
```

By using Compiled Bindings I get the following build error:
```
1>Views\NewPersonView.xaml(18,53): error : Position 18:53. Binding: Unsupported indexer index type: TKey
```

**Comment by StephaneDelcroix** [comment]
I'm quite sure I fixed something related to that lately. could you please attach a small repro project, or tell us about the `x:DataType` you're using, and your VM ?

thanks

**Comment by omghb** [comment]
The Person class is my VM. It is set as BindingContext into the View. Here is the related code:

```C#
namespace XamarinTestApp.Applications.DataModels
{
    public class Person : Model
    {
        private Dictionary<string, string> errors;

        public Dictionary<string, string> Errors
        {
            get => errors;
            private set => SetProperty(ref errors, value);
        }
    ...
```

```XML
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="XamarinTestApp.Presentation.Views.NewPersonView"
             xmlns:dm="clr-namespace:XamarinTestApp.Applications.DataModels;assembly=XamarinTestApp.Applications"
             Title="New Person" x:DataType="dm:Person">
...
             <Entry Placeholder="First Name" Text="{Binding FirstName}" FontSize="Small">
                <Entry.Triggers>
                    <DataTrigger TargetType="Entry" Binding="{Binding Errors[FirstName]}" Value="{x:Null}">
                        <Setter Property="TextColor" Value="Red" />
                    </DataTrigger>
                </Entry.Triggers>
            </Entry>
```

**Comment by kingces95** [comment]
@omghb Could you please attached a zipped solution created from the XF template project?

**Comment by omghb** [comment]
@kingces95 I have published a solution for reproduction on GitHub: [https://github.com/omghb/XamarinBindingIssue](https://github.com/omghb/XamarinBindingIssue)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/55269906-b6ce4e80-523c-11e9-855a-07a7ced8a4a0.png)

**Comment by StephaneDelcroix** [comment]
I can repro this in latest 4.0.0, but not in our unit tests :/
