### ISSUE TITLE
XF 3.6 fails to compile in Azure Devops cloud build

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5511]
Using Azure DevOps, use the Hosted build agent and get Azure to build a XF 3.6 project. 

[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error : error XA5101: Missing Android NDK toolchains directory '\toolchains'. Please install the Android NDK.

Logs attached

### Steps to Reproduce

1.  Ask Azure Devops to build a XF 3.6 using Android 9 / SUpport 28.0.01
2.  Fails
3. 

### Expected Behavior
Works
### Actual Behavior
Azure DevOps fails with:

[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2730,3): Error : error XA5101: Missing Android NDK toolchains directory '\toolchains'. Please install the Android NDK.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Azure DevOps
- Platform Target Frameworks: 
  - Android:  9 with 28.0.0.1 Support librarys
  
 

### Screenshots

![2019-03-11 09_34_18-20190311 3 Android](https://user-images.githubusercontent.com/112916/54140455-e2e67480-43e0-11e9-9f4a-555f816f7f2a.png)

[log_9_1375.zip](https://github.com/xamarin/Xamarin.Forms/files/2953182/log_9_1375.zip)

**Comment by ianvink** [comment]
Reverting to XF 3.4 works fine in Azure DevOps.

I tried the Azure Agents: ("Hosted" and "Hosted for VS 2017")

**Comment by PureWeen** [comment]
@ianvink  can I see your build log for when it succeeds? Do you have AOT enabled in both cases when you tested XF 3.4 and XF 3.6?

**Comment by PureWeen** [comment]
@ianvink  not sure if this is the same issue you're seeing
https://github.com/xamarin/xamarin-android/issues/2673

There's a workaround in there you can try as well

**Comment by ianvink** [comment]
AOT is disabled.  I can wait for VS 2019, I can build on another box for now.

**Comment by ianvink** [comment]
[log_9_1382.zip](https://github.com/xamarin/Xamarin.Forms/files/2954428/log_9_1382.zip)

**Comment by ianvink** [comment]
Here's the failing log from Azure DevOps
[log_9_1384.zip](https://github.com/xamarin/Xamarin.Forms/files/2954432/log_9_1384.zip)

**Comment by samhouts** [comment]
This is being monitored on https://github.com/xamarin/xamarin-android/issues/2694. I'll close this one for now. Thanks!
