### ISSUE TITLE
Xamarin.Forms: OnTouchEvent() is not getting fired inside PageRenderer for Android. How do i identify Touch for My App.

### ISSUE THREAD

**Issue by ashishm29** [xamarin/Xamarin.Forms#5514]
### Description:
I want to identify when user touches the screen.
So i have override OnTouchEvent() which is available in PageRenderer.
But this method is not getting called when user touches screen.

### Steps to Reproduce

1. Create Xamarin.Forms app, add PageRenderer for Android Project.
2. Override  OnTouchEvent().
3. Run Application.

### Expected Behavior
- OnTouchEvent() should get called when user touches screen.

### Actual Behavior
- OnTouchEvent() method is not getting called.

### Basic Information

XF Version : 3.0.0.482510
Microsoft Visual Studio Enterprise 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050
Microsoft .NET Framework
Version 4.7.03056

### Sample code

using Android.Content;
using Android.Views;
using RW.xPOS.Droid.Renderers;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportRenderer(typeof(ContentPage), typeof(CustomPageRenderer))]
namespace RW.xPOS.Droid.Renderers
{
    class CustomPageRenderer : PageRenderer
    {
        public CustomPageRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Page> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement == null)
                return;

            var height = e.NewElement.Height;
        }

        public override void SetOnTouchListener(IOnTouchListener l)
        {
            base.SetOnTouchListener(l);
        }

        public override bool OnTouchEvent(MotionEvent e)
        {
            return base.OnTouchEvent(e);
        }

        
    }
}

**Comment by samhouts** [comment]
[Issue5514.zip](https://github.com/xamarin/Xamarin.Forms/files/2985869/Issue5514.zip)

I put a breakpoint in `OnTouchEvent` and it hit. Can you confirm? Thanks!

**Comment by ashishm29** [comment]
Hello @samhouts ,

Thank you for reply.
I have checked your project OnTouchEvent is working fine in your project but not working in my Project.

Only difference in both of our project is that your XF Application is created in  ".Net Standard" and my application that i was created is in "Portable".

So can you please check it in Portable Project.

Regards,
Ashish Mali.

**Comment by samhouts** [comment]
@ashishm29 Hmm, I'm not sure why that would make a difference.

PCLs were deprecated more than a year ago. If you'd like to submit your reproduction project to me using a PCL, I'd be happy to take a look at it, but I don't have Visual Studio 2015 installed to create one. 

We strongly recommend that you upgrade to a netstandard library if at all possible. Thanks!

**Comment by samhouts** [comment]
@ashishm29  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
