### ISSUE TITLE
[Enhancement] XmlnsDefinitionAttribute (and XmlnsPrefix) for platform specific namespaces

### ISSUE THREAD

**Issue by StephaneDelcroix** [xamarin/Xamarin.Forms#5515]
## Summary
we should provide XmlnsDefinitionAttributes for platform specifics

## API Changes

/

## Intended Use Case

/

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
