### ISSUE TITLE
Visual="Material" making the iOS Button Text to Upper Case

### ISSUE THREAD

**Issue by rkshnair** [xamarin/Xamarin.Forms#5516]
### Description
`<Button Text="Material Button" Visual="Material"/>`

is changing the iOS button text also to upper. Is there any property present to make the button text smaller / configurable?

### Steps to Reproduce
create button with material option
`<Button Text="Material Button" Visual="Material"/>`

### Expected Behavior

Is should display the same text i have given "Material Button"

### Actual Behavior

It is displaying ""MATERIAL BUTTON"

### Basic Information

- Version with issue: 3.6.x

**Comment by paymicro** [comment]
This behavior is according to the [spec material design](https://material.io/design/components/buttons.html#anatomy). 

> By default Material uses capitalized button text labels

But most likely a setting will be added to disable `uppercaseTitle`

**Comment by rkshnair** [comment]
@paymicro I agree!!!! But if we can expose a property for this feature. It will be an add on advantage. Since control with All CAP doesn't look that great. :)

**Comment by maexsp** [comment]
A setting to diable UPPERCASE would be helpfull! For Android it works also if setting the Android styles.xml to <item name="android:textAllCaps">false</item>    but in iOS, UWP, WPF it has no effect. Please improve this.

**Comment by GalaxiaGuy** [comment]
This should probably be part of https://github.com/xamarin/Xamarin.Forms/issues/5005.

**Comment by Shashidhar014** [comment]
I used CustomRenderer to to resolve this issue, you can inherit MaterialButtonRenderer and set Control.UppercaseTitle = false

**Comment by davidortinau** [comment]
This issue doesn't apply only to the Material Design renderers for Visual. Basic Android Material will do this also.

How about we default to Material but allow the developer to express specific expectations in a style? 

I don't think this should be the material attached properties alone.

Looking at UWP It appears you would use a text converter to drive this behavior. In web/css you use `text-transform`. I think the latter covers all the bases. The former alone would require implicitly overriding what the renderer default was, in this case all uppercase.

```xaml
<Button Text="Button" TextTransform="Lowercase"/>
```

Other values:
* none (default)
* capitalize - first of each word is uppercase
* uppercase (material defaul)
* lowercase

@PureWeen @samhouts

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
