### ISSUE TITLE
Frame Tap Gesture not working when using Visual="Material" in iOS

### ISSUE THREAD

**Issue by sahadevgupta** [xamarin/Xamarin.Forms#5518]
I have updated my Xamarin Forms to 3.6. I've set Frame visual to material but the tap gesture is not working in iOS. I've tried using command and Tapped event as well but nothing works out. If i remove the visual from frame then everything works fine. I've added "Xamarin.Forms.Visual.Material" nuget package in iOS and had intialized it in AppDelegate.cs file after adding this package, the frame tap event is not working.

### Steps to Reproduce

create frame with material option and add tap gesture to it.
```
<Frame Visual="Material">
          <Frame.GestureRecognizers>
                     <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped" />
          </Frame.GestureRecognizers>
</Frame>
```

### Expected Behavior
Tap Event should fire.
### Actual Behavior
Tap Event does not fire.
### Basic Information

- Version with issue: 3.6.0.220655
- Last known good version: 3.5

### Sample File :
[FormsApp.zip](https://github.com/xamarin/Xamarin.Forms/files/2956619/FormsApp.zip)

**Comment by hamid-shaikh** [comment]
I am also facing same behavior. Please check

**Comment by skadookkunnan** [comment]
We are also facing this issue. Please consider this in the future release for fixes.

**Comment by PawelHaracz** [comment]
Any update with this? I had the same problem, when I removed  visual=Material, it started working

**Comment by gogetenk** [comment]
I also have this problem and have to do this workaround : 

`Visual="{OnPlatform Default=Material, iOS=Default}"`

Is that bug going to be fixed soon ?

**Comment by nathan1658** [comment]
I also have this problem on iOS, here is my workaround:
`    <Grid
        HeightRequest="100"
        WidthRequest="100"
        HorizontalOptions="FillAndExpand"
     
        VerticalOptions="FillAndExpand">

        <Frame
          Visual="Material"
           >
      contents....
        </Frame>
        <Frame Padding="0"
               HasShadow="False"
               Visual="Default"
               x:Name="touchFrame"
               Margin="0"
               Opacity=""
               VerticalOptions="FillAndExpand"
               HorizontalOptions="FillAndExpand"
               BackgroundColor="Transparent" />
    </Grid>`


And add TapGestureRecognizer on touchFrame, the idea is cover the material frame with a transparent default frame on it.

**Comment by BuddyLReno** [comment]
Would love to see this fixed. Currently working on an app with a lot of card-like elements that I am having to apply @nathan1658's fix to.

**Comment by Nessitro** [comment]
This is happening to me as well, I would love to see this issue fixed so I don't have to use workarounds

**Comment by odapplications** [comment]
Still not working. All other tap gestures are working with my app but one within a frame. Will try the work around. But please fix this so I can add my gestures with xaml and not code behind.

**Comment by dpuckett** [comment]
This case has become a circular reference of Closed cases that cite each other as the true case and themselves been closed. 
This bug is still happening and causing issues!

Please re-open this bug and fix the problem. @PureWeen
