### ISSUE TITLE
Binding IsVisible property on a Frame-element gives NULLReferenceException in IOS

### ISSUE THREAD

**Issue by ahjwessel** [xamarin/Xamarin.Forms#5519]
### Description
Binding IsVisible of a Frame inside a Listview ItemTemplate makes NullReferenceException. It happens with Xamarin.Forms 3.6.220655, but not with Xamarin.Forms 3.4.0.1029999

### Steps to Reproduce

1. Make a Listview
2. Inside the ItemTemplate have a grid with several children.
3. One of the children is a Frame
4. Bind the IsVisible property to a property of the Item in the ItemSource of the Listview
5. Make some code to let this item property switch between true and false.
6. Startup the application in Android. No problem here!
7. Startup the application in IOS. You will get a NullReferenceException

### Expected Behavior
Just make the Frame visible and invisible depending on the value of the item property.

### Actual Behavior
Gives a NullReferenceException.

### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forms 3.4.0.1029999
- IDE: Visual Studio 2017 for Windows
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: 8.1

**Comment by samhouts** [comment]
@ahjwessel I was unable to reproduce this issue. Is it still affecting you? If so, can you please look at the reproduction and modify it such that it demonstrates the behavior? Thanks!

[Issue5519.zip](https://github.com/xamarin/Xamarin.Forms/files/3673502/Issue5519.zip)

**Comment by samhouts** [comment]
@ahjwessel  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
