### ISSUE TITLE
Content Page inside ShellContent renders page under tabs and header on iOS

### ISSUE THREAD

**Issue by k-ljung** [xamarin/Xamarin.Forms#5525]
### Description
When adding a Content Page as ShellContent page, the page renders under tabs and header on iOS, on Android is renders as expected.

### Steps to Reproduce
1. Create new Xamarin.Forms project and update to 4.0.0.169046-pre5 package
2. Create a shell page AppShell.xaml
3. Add two ShellContent sections and reference GroupPage.xaml
4. Add GroupPage.xaml

#### AppShell.xaml
```
<?xml version="1.0" encoding="UTF-8"?>
<Shell 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:local="clr-namespace:WeAreVoice.Mobile" 
    RouteScheme="app" 
    RouteHost="microsoft.com"
    Route="newapp" 
    FlyoutBehavior="Disabled"
    x:Class="WeAreVoice.Mobile.AppShell">
    <ShellItem> 
        <ShellSection Title="Feed">
          <ShellContent>
            <local:GroupPage />
          </ShellContent>
        </ShellSection>

        <ShellSection Title="Groups">
             <ShellContent>
                <local:GroupPage />
             </ShellContent>
        </ShellSection>
  </ShellItem>
</Shell>
```
#### GroupPage.xaml
```
<?xml version="1.0" encoding="UTF-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" x:Class="WeAreVoice.Mobile.GroupPage"
             Title="Groups">
    <ContentPage.Content>
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="110" />
                <RowDefinition Height="*" />
                <RowDefinition Height="110" />
            </Grid.RowDefinitions>
            <BoxView
                BackgroundColor="Red"
                Grid.Row="0"
                Grid.Column="0" />
            <BoxView
                BackgroundColor="Blue"
                Grid.Row="1"
                Grid.Column="0" />
            <BoxView
                BackgroundColor="Green"
                Grid.Row="2"
                Grid.Column="0" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

### Expected Behavior
![shell_1](https://user-images.githubusercontent.com/9248053/54231272-867e7480-4508-11e9-9736-3259cab09b84.png)

### Actual Behavior
![shell_2](https://user-images.githubusercontent.com/9248053/54231295-91390980-4508-11e9-8766-400117f3724c.png)

### iOS vs Android
<img width="1024" alt="Screenshot 2019-03-12 at 20 22 49" src="https://user-images.githubusercontent.com/9248053/54231352-a877f700-4508-11e9-82bd-658c8dc71612.png">

### Basic Information

- Version with issue: 4.0.0.169046-pre5
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  8.0 - 12
  - Android: 8.1

**Comment by samhouts** [comment]
see https://github.com/xamarin/Xamarin.Forms/issues/4840#issuecomment-470220382
