### ISSUE TITLE
[Shell] TitleView does not work in Xamarin.Forms 4 

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5530]
### Description
I am using Shell for Navigation. When I set TitleView in ContentPage it does not work with Shell. 
### Steps to Reproduce

1. Create new project with Shell as Navigation pattern and add a content page to it
2. Now set NavigationPage.TitleView property of ContentPage.
3. Deploy the app to device or emulator

### Expected Behavior
The TitleView should work as with any NavigationPage
### Actual Behavior
The TitleView is not rendering
### Basic Information

- Version with issue: Xamarin.Forms (4.0.0.169046-pre5)
- Last known good version: The TitleView work if I do not use Shell
- IDE: Visual Studio for Mac preview Version 8.0 (8.0 build 2624)
- Platform Target Frameworks: 
  - iOS:  Deployment Target 8.0
  - Android: Target Android version: Android 8.1 (API level 27)
  - UWP:  NA
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[TitleViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/2961792/TitleViewSample.zip)

**Comment by samhouts** [comment]
@HobDev you need to use `Shell.TitleView` when you're using Shell. Thanks!

**Comment by HobDev** [comment]
I don't able to figure this out on my own. Thank you.

**Comment by jrahma** [comment]
@samhouts my shell never worked too. 

I am trying it on Android Emulator and Honor 10 Lite device.. Both having the same problem

Here is a sample project

[ShellTitle.zip](https://github.com/xamarin/Xamarin.Forms/files/3660295/ShellTitle.zip)
