### ISSUE TITLE
[Enhancement] Open Source the Xamarin Templates

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#5531]
## Summary

The Xamarin Forms Templates are actually great examples of how to create and share templates across Mac and Windows. While the exact plugins for the IDE's may need to remain closed source, it would be great to make the templates themselves open sourced. 

This would also make it easier to track/fix issues with templates such as resources that are included but no longer relevant, or broken assets such as icon in the iOS storyboard for the Forms template.

cc: @pierceboggan @jimmgarrido

**Comment by kzu** [comment]
Wholeheartedly agree.

**Comment by dansiegel** [comment]
I'm sure it was the Sam-bot... but @samhouts how exactly would you like me to help on this if it's up for grabs and you want help....

**Comment by samhouts** [comment]
Hmmmm yes, this was the sambot that marked it, and there's obviously not much you can do in terms of code to get these open sourced. But this was a great reminder that it's something we should consider. Right, @davidortinau ? :)

**Comment by jfversluis** [comment]
Don't think this will happen for Forms anymore. And for .NET MAUI they are out in the open? (Hooray!) So guess we can close this one. Thanks for the suggestion as always Dan!
