### ISSUE TITLE
CollectionView: Swapping EmptyViews has no effect

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5535]
### Description

Swapping EmptyViews in a `CollectionView` has no effect.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the `EmptyViewSwapPage`.
3. Filter the `CollectionView` so no data is displayed.
4. Toggle the `Switch`.

### Expected Behavior

EmptyView changes.

### Actual Behavior

EmptyView doesn't change. No amount of toggling/pre-toggling (before filtering) has any effect. On Android, a crash occurs (`IllegalStateException`).

### Basic Information

- Version with issue: 4.0-pre5
- Last known good version: N/A
- IDE: VSMac 7.8.2.
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: 8.1

### Screenshots

An `IllegalStateException` occurs on Android:

![Screen Shot 2019-03-13 at 14 34 54](https://user-images.githubusercontent.com/8092460/54293574-1d4e3e00-45a8-11e9-81cc-47c40e7214c5.png)

### Reproduction Link

[CollectionViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/2962320/CollectionViewDemos.zip)

**Comment by hartez** [comment]
> Version with issue: 4.0-pre5
Works on iOS if you update to the latest stable (3.6.0.220655) - the fix is in https://github.com/xamarin/Xamarin.Forms/pull/5353

Looks like the IllegalStateException is still happening on Android even with the latest, though.

**Comment by davidbritch** [comment]
Confirmed that this is working on iOS in 4.0-pre6.
