### ISSUE TITLE
[Shell] Search Entry only appears in the NavigationBar

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5536]
### Description

I want to use the SearchHandler, but my Search bar should appear at the top of the page content, below the TitleView. 

I also want to control if it scrolls with the content or remains fixed with the TitleView.

SearchHandler currently provides:
* SearchBoxVisiblity.Collapsable
* SearchBoxVisiblity.Expanded
* SearchBoxVisiblity.Hidden

I think "Visibility" is inconsistent with other things like `FlyoutBehavior`. Should be called Behavior.

Also, if Behavior is more complex like the `BackButtonBehavior` which is commands and icons and more, then in this case could it handle position and scroll behavior?

### Expected Behavior

![image](https://user-images.githubusercontent.com/41873/54293294-b582fd80-457d-11e9-8d64-958178a900ef.png)

### Actual Behavior

Note the absense of the TitleView, which is in the XAML I created.

![image](https://user-images.githubusercontent.com/41873/54293602-46f26f80-457e-11e9-86f1-c368a29e77c7.png)

**Comment by Akinnagbe** [comment]
Please when will this feature be available, to be able to place the searchHandler anywhere on the Xaml page.
Thumbs to you guys

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
