### ISSUE TITLE
Font glyphs don't consistently work

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5543]
### Description

I have Labels and ImageButtons using Font icons. They appear and then don't. See video.

https://www.screencast.com/t/m0zxJeFw4e0M

### Expected Behavior

Font renders consistently.

### Actual Behavior

It's hit or miss.

### Basic Information

- Version with issue: 3.6
  - Android: 9.0
  
### Screenshots

You can see Previewer rendering one of the icons:

https://www.screencast.com/t/m0zxJeFw4e0M
![image](https://user-images.githubusercontent.com/41873/54321730-4aa6e600-45c0-11e9-9d31-55131ba59ca4.png)

### Reproduction Link

https://github.com/davidortinau/VisualChallenge/blob/davidortinau/msnews/VisualChallenge/VisualChallenge/Views/InterestTile.xaml

**Comment by samhouts** [comment]
@davidortinau Only Android? Emulator, previewer, or device?

**Comment by davidortinau** [comment]
Android emulator. Not sure about Android device. iOS looks ok on device and sim. @samhouts

**Comment by davidortinau** [comment]
Tested on 4.8-pre2 and this is fine now. I think it's been fixed for a while.

<img width="515" alt="Screen Shot 2020-07-23 at 9 15 10 PM" src="https://user-images.githubusercontent.com/41873/88355287-9c6d8d80-cd29-11ea-9b07-99c44e547f49.png">
