### ISSUE TITLE
[Material, iOS] Frame on iOS isn't respecting the corner radius

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5544]
### Description

```
<Frame Margin="20" 
               HeightRequest="200"
               Padding="0"
               CornerRadius="0"
               >
```

Results in sharp corners with a default Frame, but with a rounded corner using `Visual="Material"` on iOS. Android appears consistent.

### Expected Behavior

Radius works throughout.

### Actual Behavior

Material renderer isn't getting it done.

### Basic Information

- Version with issue: 3.6.0

### Screenshots

<img width="527" alt="Screenshot 2019-03-13 19 02 22" src="https://user-images.githubusercontent.com/41873/54322399-0701ab80-45c3-11e9-948d-79efad5b245a.png">
<img width="478" alt="Screenshot 2019-03-13 19 00 26" src="https://user-images.githubusercontent.com/41873/54322400-0701ab80-45c3-11e9-9b8e-e0b4db8f5a14.png">

### Reproduction Link

[Archive.zip](https://github.com/xamarin/Xamarin.Forms/files/2964118/Archive.zip)

**Comment by samhouts** [comment]
closed by #6099
