### ISSUE TITLE
Previewer don't have status bar, navigation bar and Tab bar.

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5548]
### Description
The previewer does not preview Status bar, Navigation bar and Tab bar.
### Steps to Reproduce

1. Create or open an existing Xamarin.forms app
2. Click Preview button on top right side
3. The previewer will show the content of the page. But it will not show Status Bar, Navigation Bar and Tab Bar.

### Expected Behavior
Status Bar, Navigation Bar and Tab bar should be shown on previewer
### Actual Behavior
The status Bar, Navigation Bar and Tab bar is not rendered on previewer
### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.232914-pre6
- Last known good version: NA
- IDE:Visual Studio for Mac Preview
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

> VS bug [#820174](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/820174)

**Comment by drewgillies** [comment]
This is a great suggestion, and we'll track it as a feature request rather than a bug, to be prioritized against other feature work for the previewer. As such I will close it here.

**Comment by phil-harmoniq** [comment]
Could you please post a link to where this is being tracked? This is currently frustrating me while working on my navigation bar since I have to rebuild and relaunch the emulator just to preview a minor change.
