### ISSUE TITLE
How to use listview inside scrollview

### ISSUE THREAD

**Issue by landl0526** [xamarin/Xamarin.Forms#5551]
In my application there is one scrollview which is covered whole page so in landscape mode page can be scrolling properly and I have one listview at bottom of the screen. But, due to scrollview my listview is not working properly. If I removed my main scrollview then listview is working as expected but in landscape mode page is not scrolling. So is there any way to overcome this scenario?

ps: The list view can be scrolled on iOS but it doesn't work on Android. I want to know why it comes to different effects.

**Comment by geskill** [comment]
https://stackoverflow.com/questions/6210895/listview-inside-scrollview-is-not-scrolling-on-android/6211286#6211286

**Comment by Evolutionlab** [comment]
This is not a bug, its by design :)
Even the official documentation tell su to avoid that:
https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/listview/performance

You can try to solve this with a custom renderer, something like this:

`    protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.ListView> e)
    {
        base.OnElementChanged(e);

        if (e.NewElement != null)
        {
            var listView = this.Control as Android.Widget.ListView;
            listView.NestedScrollingEnabled = true;               
        }            
    }`

but i'm not sure if it works

**Comment by samhouts** [comment]
@landl0526 What version of Xamarin.Forms are you using? Can you please attach a sample project? @Evolutionlab is correct that this is not a recommended design for many reasons. It's possible, however, that some scenarios will work better in later versions of Forms, as we have started to implement some of the APIs that support nested scrolling in 3.5+.

**Comment by samhouts** [comment]
@landl0526  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
