### ISSUE TITLE
CollectionView: iOS selection color glitch

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5563]
### Description

There's a selected item color glitch on a small number of items in my `CollectionView` on iOS. It doesn't occur on Android.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the VerticalListSelectionColorPage. This page changes the color of selected items via a `VisualState`.
3. Select the Japanese Macaque (or Proboscis Monkey, or Red-shaked Douc).

### Expected Behavior

Selected item is light sky blue.

### Actual Behavior

Selected item is largely light sky blue, but with a grey bar at the bottom.

### Basic Information

- Version with issue: 4.0-pre6
- Last known good version: N/A
- IDE: VSMac 7.8.2
- Platform Target Frameworks: 
  - iOS:  12.1

### Screenshots

Good selection:

![Simulator Screen Shot - iPhone X - 2019-03-14 at 16 51 49](https://user-images.githubusercontent.com/8092460/54376241-8bfbcc00-467a-11e9-9ed0-3f5563c249b5.png)

Problematic selection:

![Simulator Screen Shot - iPhone X - 2019-03-14 at 16 51 52](https://user-images.githubusercontent.com/8092460/54376254-9027e980-467a-11e9-8416-4878c1523cc4.png)

### Reproduction Link

[CollectionViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/2967548/CollectionViewDemos.zip)

**Comment by hartez** [comment]
This is fixed in 4.2.0.
