### ISSUE TITLE
Xamarin.Forms PlatformParameter does not contain a constructor that takes 2 arguments

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#5569]
## Summary
ADAL Xamarin.Forms PlatformParameter does not contain a constructor that takes 2 arguments

## API Changes

Call `AcquireTokenAsync(...)`, which accepts the `IPlatformParameters `object and invokes the authentication flow that's necessary to return a token to the app.

e.g.

I am doing a mobile app using ADAL for authentication. I am using VS 2017 Xamarmin.Forms and trageting .Net standard 2.0 for the project. But got the error for the following code. I did some research than found out that PlatformParameters constructor is not supported by .NetCore since .NetCore does not support UI yet. But .Net Standard should support. Is there any solution or workaround? Thank you in advance.

     ...
    AuthenticationResult authResult = null;
    try
    {
        AuthenticationContext authContext = new AuthenticationContext(authority);
        authResult = await authContext.AcquireTokenAsync(graphResourceUri, clientId, returnUri, parent);
    }
    catch (Exception ee)
    {
        results.Add(new User { error = ee.Message });
        return results;
    }
...

`AcquireTokenAsync ` now does not contain two parameters in this method.

## Intended Use Case
Maybe this need custom webservice to make it.

**Comment by samhouts** [comment]
You may need to try the implementation that uses DependencyServices instead: https://blog.xamarin.com/put-adal-xamarin-forms/

**Comment by john-heaven** [comment]
Thanks @samhouts ,I will try it!
