### ISSUE TITLE
Label Data Trigger doesn't work when Formatted Text

### ISSUE THREAD

**Issue by khadeeja-alif** [xamarin/Xamarin.Forms#5570]
### Description
I try to Change properties on Data Trigger for my Label. I have given FormattedText with two Spans. The trigger setter property change doesn't happen. If I remove Formatted Text and set Text directly. It works fine.

### Steps to Reproduce
This is my xaml
`<Label FontSize="14" FontFamily="{StaticResource BoldFont}">
                                                           <Label.Triggers>
                                                                <DataTrigger TargetType="Label"
                                                                             Binding="{Binding Source={x:Reference discountAmount},Path=IsVisible}"
                                                                             Value="true">
                                                                    <Setter Property="FontSize" Value="12"/>
                                                                    <Setter Property="FontFamily" Value="{StaticResource RegularFont}"/>
                                                                </DataTrigger>
                                                            </Label.Triggers>
                                                        <Label.FormattedText>
                                                            <FormattedString>
                                                                <Span Text="{Binding Currency,Mode=OneWay}"/>
                                                                <Span Text="{Binding Price,Mode=OneWay,StringFormat=' {0:N2}'}" />
                                                            </FormattedString>
                                                        </Label.FormattedText>
                                                        </Label>`
### Expected Behavior

For the setter properties to change if Value true on DataTrigger.

### Actual Behavior

DataTrigger doesn't work.  The label properties remain the same.

### Basic Information

- Version with issue: Xamarin Forms 3.2.0.839982
- Last known good version:
- IDE: Visual Studio for Mac (Community) 7.8.2(build 1)
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: 9.0
- Affected Devices: Both iOS & Android

**Comment by samhouts** [comment]
@khadeeja-alif Can you please attach a sample project that demonstrates this problem? Thank you!

**Comment by samhouts** [comment]
@khadeeja-alif  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
