### ISSUE TITLE
Set the style of NavigationBar on Android does not work in Xamarin.forms

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#5571]
### Steps to Reproduce

1. I have a Xamarin.Forms app. I would like to remove/hide the back arrow in my navigation bars but keep the title. I was able to do it in iOS using the following code inside my NavigationPageRenderer:

```
UINavigationBar.Appearance.BackIndicatorImage = new UIImage();
UINavigationBar.Appearance.BackIndicatorTransitionMaskImage = new UIImage();
```

2. Is there any equivalent code for this in Android that I could use inside my renderer or in the MainActivity? I tried this.ActionBar.SetDisplayHomeAsUpEnabled(false); inside my MainActivity but the ActionBar always returns null. Below is my my MainActivity code:
```
public class MainActivity : FormsAppCompatActivity
{
    protected override void OnCreate(Bundle bundle)
    {
       TabLayoutResource = Resource.Layout.Tabbar;
       ToolbarResource = Resource.Layout.Toolbar;

       base.OnCreate(bundle);

       global::Xamarin.Forms.Forms.Init(this, bundle);
       LoadApplication(new App());
       if (Window != null)
       {
          Window.SetStatusBarColor(Android.Graphics.Color.Transparent);
       }

       this.ActionBar.SetDisplayHomeAsUpEnabled(false);

     }
}

```

3. Although the issue had been solved .I also want to know if it is a bug. 
 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android 8.1

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![YwNqK](https://user-images.githubusercontent.com/47239772/54409814-a63db480-4723-11e9-9d73-92d3fd9f0c9d.jpg)

### Reproduction Link

https://stackoverflow.com/questions/54984918/removing-navigation-back-arrow-in-xamarin-android

**Comment by samhouts** [comment]
I wouldn't really call this a bug, but it is definitely an annoying limitation. I think that the solution provided in the StackOverflow link is actually a pretty great way to handle the situation without resorting to a custom renderer. If you find that this doesn't work for you, let me know, and we'll reopen this as a possible enhancement. Otherwise, I'll close this and hopefully it helps someone else resolve a similar problem. Thanks!
