### ISSUE TITLE
Previewer doesn't show embedded images

### ISSUE THREAD

**Issue by jessiezh0320** [xamarin/Xamarin.Forms#5573]
### Steps to Reproduce

1. I have a xamarin form app, and in the  xaml layout file,which embedd a  image, but  the previewer often do not display the image effect. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

> VS bug [#823584](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/823584)

**Comment by samhouts** [comment]
@jessiezh0320 Do you see the same behavior with both the Android and iOS previews? Can you attach a sample project? Thanks!

**Comment by drewgillies** [comment]
This is fixed in 16.0.
