### ISSUE TITLE
Firebase deeplink throwing an error in iOS

### ISSUE THREAD

**Issue by Scy15** [xamarin/Xamarin.Forms#5576]
Issue:- 
On a Xamarin.Forms App, deeplink is redirecting to default page in iOS most of the times.

Versions:-
Xamarin.Firebase.iOS.Analytics:- 4.0.5.1 (updated to 5.5.0)
Xamarin.Firebase.iOS.InstanceID:- 2.0.8 (updated to 3.4.0)
Xamarin.Firebase.iOS.Core:- 4.0.13.1(updated to 5.2.0)
Xamarin.Firebase.iOS.DynamicLinks:- 2.3.1.1 (updated to 3.0.2.1)
Xamarin.Forms:- 3.2.0.871581

Steps to reproduce:-
Tap on a deeplink in iOS. Every second or third time, deeplink is empty and throws an error in iOS. the same deeplink in Android works fine always.

Platform:-
[] .NET version = 2.1
[] mono version = 5.16

Expected behaviour:- 
It should be redirected to the corresponding page and not throw an error.

**Comment by samhouts** [comment]
@Scy15 Can you please attach a sample project or show how you're creating the deep links? Thanks!

**Comment by Scy15** [comment]
Please find below the code snippet I am using.

NSUserActivity userActivity;
NSUrl webpageUrl = userActivity.WebPageUrl;
var resolveUniversalLink = DynamicLinks.SharedInstance.HandleUniversalLink(webpageUrl, (dynamicLink, error) =>
               {
                   if (error != null)
                   {
                       Logger.Log("AppDelegate ", "could not resolve universal link for the DynamicLink: " + dynamicLink + " Error: " + error, Utilities.AppLogLevel.ERROR);
                   }
                   else
                   {
                       //Business logic implemented here
                   }
               });

**Comment by samhouts** [comment]
@rmarinho Thoughts?

**Comment by kingces95** [comment]
@Scy15 Could you attach a zipped reproduction starting from the XF template project?

**Comment by Scy15** [comment]
Could you please try the above mentioned code snippet on a sample project?

**Comment by kingces95** [comment]
Could you please insert that snippet into a sample project, zip, and attach it to the bug? Thanks.

**Comment by samhouts** [comment]
@Scy15 That snippet is not enough for us to reproduce the issue.  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
