### ISSUE TITLE
CollectionView XAML API suggestion

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5577]
### Description

I love `CollectionView`. Particularly the ability to specify different layouts. However, I'd like to see it be easier to specify layouts from XAML. This isn't a bug, more a suggestion.

By default `CollectionView` produces a vertical list layout:

```
<CollectionView ItemsSource="{Binding Monkeys}" />
```

If we want to change that to a horizontal list, we have to do the following:

```
<CollectionView ItemsSource="{Binding Monkeys}"
                            ItemsLayout="{x:Static ListItemsLayout.HorizontalList}">
```

Personally, I think specifying the `ItemsLayout` above like that is a bit ugly.

A vertical grid is:

```
        <CollectionView ItemsSource="{Binding Monkeys}">
            <CollectionView.ItemsLayout>
               <GridItemsLayout Orientation="Vertical"
                                Span="2" />
            </CollectionView.ItemsLayout>
```

A horizontal grid is:

```
        <CollectionView ItemsSource="{Binding Monkeys}">
            <CollectionView.ItemsLayout>
               <GridItemsLayout Orientation="Horizontal"
                                Span="4" />
```

My suggestions/questions are:

1. `ListItemsLayout` defines static `VerticalList` and `HorizontalList` members that can be consumed from XAML. While I think this leads to ugly XAML, should `GridItemsLayout` define some static members for common grid layouts?
1. Is a better solution to implement a type converter so users can do something like `ItemsLayout="HorizontalList"` or `ItemsLayout="VerticalList"`? Personally, I like this idea.
1. Extending above, should users be able to do something like `ItemsLayout="HorizontalGrid, 2"` or `ItemsLayout="VerticalGrid, 3"`? Not convinced about this, but thought I'd raise it anyway.

**Comment by StephaneDelcroix** [comment]
I agree with implementing a TypeConverter

**Comment by adrianknight89** [comment]
@davidbritch I like both 2 and 3, but what if we want to set horizontal and vertical item spacing too? How would that work? Are we going to keep adding more to 3? Also, in discussing this, we should account for the staggered layout that should be supported in the future.
