### ISSUE TITLE
[Enhancement] Customize AppBarButton in CommandBar for UWP

### ISSUE THREAD

**Issue by maxsieben** [xamarin/Xamarin.Forms#5580]
## Summary
After browsing the internet I did not find a way to customize the UWP CommandBar. Something like changing font size for the AppBarButton is not possible.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
