### ISSUE TITLE
Failed to update Xamarin Forms

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#5590]
Hi,

I am trying to update Xamarin Forms in my Android project in Visual Studio for Windows bet keep getting errors and I am unable to update any of the Nugets.

What's the problem?

Restoring packages for C:\Users\User\source\repos\Jeccd\Jeccd\Jeccd\Jeccd.csproj...
NU1202: Package Xamarin.Android.Support.Compat 27.0.2.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Android.Support.Compat 27.0.2.1 supports: monoandroid81 (MonoAndroid,Version=v8.1)
Restoring packages for C:\Users\User\source\repos\Jeccd\Jeccd\Jeccd.UWP\Jeccd.UWP.csproj...
  GET https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/index.json
  OK https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json 960ms
  GET https://api.nuget.org/v3-flatcontainer/netstandard.library/2.0.1/netstandard.library.2.0.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/netstandard.library/2.0.1/netstandard.library.2.0.1.nupkg 849ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/index.json 1957ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/6.1.5/microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/6.1.5/microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 864ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json 935ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.1.1.0.nupkg
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/2.0.0/microsoft.netcore.platforms.2.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.1.1.0.nupkg 937ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/index.json 884ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/2.1.8/microsoft.net.native.compiler.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/index.json 1846ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/2.0.0/microsoft.netcore.platforms.2.0.0.nupkg 1815ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/2.1.2/microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/2.1.8/microsoft.net.native.compiler.2.1.8.nupkg 1716ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/2.1.2/microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg 864ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/index.json 872ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/index.json 1752ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg 1727ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/index.json 5509ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg 4606ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/index.json 2006ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/index.json 2970ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg 1857ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg 2982ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.Compiler.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg 47ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg 88212ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/index.json 885ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 138ms
Failed to download package 'runtime.win10-x86.Microsoft.Net.Native.Compiler.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg 47ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/index.json 1027ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 916ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 1408ms
Failed to download package 'runtime.win10-x86.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 46ms
Failed to download package 'runtime.win10-x86.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 923ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 42ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
Installing runtime.win10-arm.Microsoft.Net.Native.SharedLibrary 2.1.8.
Installing runtime.win10-x86.Microsoft.Net.Native.SharedLibrary 2.1.8.
Installing runtime.win10-arm.Microsoft.Net.Native.Compiler 2.1.8.
Installing runtime.win10-x86.Microsoft.Net.Native.Compiler 2.1.8.
Installing runtime.win10-x64.Microsoft.Net.UWPCoreRuntimeSdk 2.1.2.
Installing runtime.win10-x86.Microsoft.Net.UWPCoreRuntimeSdk 2.1.2.
Installing runtime.win10-arm.Microsoft.Net.UWPCoreRuntimeSdk 2.1.2.
Installing Microsoft.NETCore.Platforms 1.1.0.
Installing Microsoft.Net.Native.Compiler 2.1.8.
Installing Microsoft.Net.UWPCoreRuntimeSdk 2.1.2.
Installing Microsoft.NETCore.Platforms 2.0.0.
Installing NETStandard.Library 2.0.1.
Installing Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/index.json 927ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-arm.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/index.json 1098ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/index.json 1806ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/index.json 1929ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x64.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/index.json 2912ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/index.json 2996ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x86.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-arm.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 2913ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-arm-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 2893ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x64.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 5983ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x86.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 8149ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x64-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 37586ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform/6.1.5/runtime.win10-x86-aot.microsoft.netcore.universalwindowsplatform.6.1.5.nupkg 69197ms
Installing runtime.win10-x86-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
Installing runtime.win10-x86.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
Installing runtime.win10-x64-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
Installing runtime.win10-x64.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
Installing runtime.win10-arm-aot.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
Installing runtime.win10-arm.Microsoft.NETCore.UniversalWindowsPlatform 6.1.5.
NU1605: Detected package downgrade: Xamarin.Forms from 3.6.0.220655 to 3.4.0.1008975. Reference the package directly from the project to select a different version. 
 Jeccd.UWP -> Jeccd -> Xamarin.Forms (>= 3.6.0.220655) 
 Jeccd.UWP -> Xamarin.Forms (>= 3.4.0.1008975)
Restoring packages for C:\Users\User\source\repos\Jeccd\Jeccd\Jeccd.UWP\Jeccd.UWP.csproj...
  CACHE https://api.nuget.org/v3-flatcontainer/netstandard.library/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/netstandard.library/2.0.1/netstandard.library.2.0.1.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.1.1.0.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.universalwindowsplatform/6.1.5/microsoft.netcore.universalwindowsplatform.6.1.5.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.native.compiler/2.1.8/microsoft.net.native.compiler.2.1.8.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.net.uwpcoreruntimesdk/2.1.2/microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-arm.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x64.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/index.json
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk/2.1.2/runtime.win10-x86.microsoft.net.uwpcoreruntimesdk.2.1.2.nupkg
  CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.platforms/2.0.0/microsoft.netcore.platforms.2.0.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg 892ms
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.compiler/2.1.8/runtime.win10-x86.microsoft.net.native.compiler.2.1.8.nupkg 893ms
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 892ms
  CACHE https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/index.json
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 931ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 116ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg 900ms
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-arm.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
Failed to download package 'runtime.win10-x86.Microsoft.Net.Native.SharedLibrary.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg'.
The download of 'https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg' timed out because no data was received for 60000ms.
  Exception of type 'System.TimeoutException' was thrown.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 961ms

**Comment by samhouts** [comment]
@jrahma It looks like you may need to try uninstalling the Xamarin.Forms and all of the Xamarin.Android.Support libraries. Then install Xamarin.Forms and let it install the proper versions. Your project seems like it may have gotten into a strange state. Make sure you are compiling with the latest Android version, too. Thanks!

**Comment by tofutim** [comment]
I ran into this today:
`Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.Compiler.2.1.8'`
Maybe there is something wrong with the package. It hits the problem trying to update Xamarin.Forms for UWP
```
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x86.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x86.microsoft.net.native.sharedlibrary.2.1.8.nupkg 49ms
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x64.microsoft.net.native.sharedlibrary.2.1.8.nupkg
Failed to download package 'runtime.win10-arm.Microsoft.Net.Native.Compiler.2.1.8' from 'https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg'.
The HTTP request to 'GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/2.1.8/runtime.win10-arm.microsoft.net.native.compiler.2.1.8.nupkg' has timed out after 100000ms.
  GET https://api.nuget.org/v3-flatcontainer/runtime.win10-arm.microsoft.net.native.compiler/index.json
  OK https://api.nuget.org/v3-flatcontainer/runtime.win10-x64.microsoft.net.native.sharedlibrary/2.1.8/runtime.win10-x64.microsoft.net.native.sharedlibrary.2.1.8.nupkg 187ms
```
tries a few times holding up everything and then finally gives up...
