### ISSUE TITLE
ListView ItemAppearing

### ISSUE THREAD

**Issue by allessandrosj** [xamarin/Xamarin.Forms#5592]
ListView ItemAppearing does not work correctly in uwp, the same way it works on android and ios, example code.
private void ListaEmpresaList_ItemAppearing(object sender, ItemVisibilityEventArgs e)
        {
            try
            {
                var binding = (ListaEmpresaViewModel)BindingContext;
                if (binding.ListaEmpresa is IList Items && e.Item == Items[Items.Count - 1])
                {
                    binding.OnBuscasEmpresas();
                }
            }
            catch (Exception ex)
            {
                App.Current.MainPage.DisplayAlert("", " Ops.. Não foi possível realizar operação" + " " + ex.Message, "OK");
            }
        }

**Comment by samhouts** [comment]
@allessandrosj Can you please attach a sample project that demonstrates the issue? Thanks!

**Comment by samhouts** [comment]
@allessandrosj  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
