### ISSUE TITLE
EOF Error (error: 0xe800000e) on upgrade to XF 3.6

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5594]
I upgraded an older XF 2.3 app to 3.6. It runs great in the iOS simulator, but when we try to deploy to a device for testing, Visual Studio 2017, we get the deployment error:

I have tried deleting the mtbs cache folder on the Mac builder.

### Description
Launch failed. The app 'Bahai.iOS' could not be launched on 'IaniPhone8'. Error: error MT1006: Could not install the application '/Users/vink/Library/Caches/Xamarin/mtbs/builds/Bahai.iOS/aa8ac11c4d3123fe16fd02ac07105205/bin/iPhone/Debug/device-builds/iphone10.4-12.1.4/BahaiiOS.app' on the device 'IaniPhone8': EOF Error (error: 0xe800000e).. Please check the logs for more details.
The app has been terminated.
 

### Steps to Reproduce

1.   I have a build I can share, I'd need an email to send it to.
2. 
3. 

### Expected Behavior
Work
### Actual Behavior
Not work
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017, newest.
- Platform Target Frameworks: 
  - iOS:    12.1
 

### Reproduction Link

I can email a version that causes the issue.

[2019-03-17_12-20-13.11628.Ide.log](https://github.com/xamarin/Xamarin.Forms/files/2975637/2019-03-17_12-20-13.11628.Ide.log)

**Comment by samhouts** [comment]
@ianvink Go ahead and send it to me (sahou). This seems interesting!

Thanks!

**Comment by ianvink** [comment]
I verified my provisioning profiles are good, cleaned bin/obj, tried on both VS Mac and VS 2017. same EOF error.

So then I tried deleting my provisioning profile and re-creating.

Now it works.
