### ISSUE TITLE
Xamarin Forms label - Span size change not working for iOS

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#5607]
I have added 2 texts in a label as spans. but that 2 spans has been assigned different font sizes.
When the app runs, it shows those 2 tests in 2 sizes in Android fine.
But, when run on iOS, both texts are showing in same size.

Here is my code.
`
<Label  Grid.Row="0" Grid.Column="4" Grid.RowSpan="2" Text="{Binding MaxPointsHiddenGlobal}"
                           Style="{DynamicResource CaptionLabelLargePoint}">
                        <Label.FormattedText>
                            <FormattedString>
                                <Span Text="{Binding Price, Mode=OneWay}" FontSize="{DynamicResource XXLargeFont}"/>
                                <Span Text="RS" FontSize="{DynamicResource LargeFont}">
                                </Span>
                            </FormattedString>
                        </Label.FormattedText>
                    </Label>
`

**CaptionLabelLargePoint = font size 18
XXLargeFont = fontsize 30**

Please solve this issue because we have to deliver the app soon with this modification.

**Comment by samhouts** [comment]
@kgbuddhima Can you please attach a sample project that shows this issue? Thanks!

**Comment by samhouts** [comment]
@kgbuddhima  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by GioviQ** [comment]
FormattedText on iOS not working in my case too.
