### ISSUE TITLE
[macOS] NRE when navigating around automation galleries

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5612]
### Description
macOS on the master branch is crashing with various NRE's when you navigate around accessibility galleries. 

Might be related to 
https://github.com/xamarin/Xamarin.Forms/issues/5434

#### 1 
- Control Gallery
- Accessibility
- back button
- crash

#### 2
- Control Gallery
- AutomationID Gallery
- Test1
- POP
- crash

### Expected Behavior
neither case above should crash

### Actual Behavior
both cases above crash with an NRE

### Basic Information

- Version with issue: master

**Comment by AndreiMisiukevich** [comment]
no crashes for now

**Comment by arctouch-oberdanbitencourt** [comment]
Hey @samhouts I took the liberty to create a PR before asking to work on this. 😬
