### ISSUE TITLE
iOS: OpenUri for URL with whitespace. Double Percent-Encoding

### ISSUE THREAD

**Issue by wcoder** [xamarin/Xamarin.Forms#5615]
### Description

When I open URI with whitespace, I get the wrong result URL (double Percent-Encoding).

### Steps to Reproduce

1. Create simple Xamarin.Forms app
2. Call `Device.OpenUri(new Uri("https://www.google.by/search?q=xamarin forms"));`
3. Launch on iOS

### Expected Behavior

Opened browser page for `https://www.google.by/search?q=xamarin%20forms` or  `https://www.google.by/search?q=xamarin+forms`

### Actual Behavior

Was opened the wrong URL: `https://www.google.by/search?q=xamarin%2520forms`

Double Percent-Encoding ( %25 = % => %20  )

### Basic Information

- Version with issue: Latest
- IDE: VS4Mac
- Platform Target Frameworks: 
  - iOS:  12.2.1.15
  - Android: 9.1.8.0
- Affected Devices: All iOS devices

### Solution

Replace:
https://github.com/xamarin/Xamarin.Forms/blob/d196f6c46b18b13fec03b7a5faa08060692f0b51/Xamarin.Forms.Platform.iOS/Forms.cs#L263-L268

To this:

```cs
var url = new NSUrl(uri.AbsoluteUri); 

var app = UIApplication.SharedApplication;  

if (app.CanOpenUrl(url)) 
{ 
    app.OpenUrl(url); 
} 
```

Worked for:
- mailto:
- tel:
- links

### Reproduction Sample

```cs
Device.OpenUri(new Uri("https://www.google.by/search?q=xamarin forms"));
```

### Related issues

#1651

**Comment by jfversluis** [comment]
With #6844 merged this API will soon be deprecated. I suggest you migrate to Xamarin.Essentials that has better APIs for this. Thank you!
