### ISSUE TITLE
DatePicker  does not support choose date and time at same time

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#5618]
## Summary
I can not use standard date picker and another standard time picker separately from Xamarin Forms. I need to create custom solution (one view - simple choose both date and time).

Finally,I solved it by use Custom Renderer.However ,I think it should be available in Forms.Just like 
in Xamarin.iOS.

**Comment by ColdstarJoey** [comment]
So you want to use a picker to select the Date and Time together ? You could still use a datepicker and a timepicker then combine them into a string in the .cs but make them look the same control but putting them close together, I can show you a demo if you like?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
