### ISSUE TITLE
CollectionView SelectedItem Color

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5622]
### Description
When no BackgroundColor is set to ItemTemplate, the SelectedItem shows a Orange background color, when you set a BackgroundColor in ItemTemplate, then SelectedItem has the same color than the rest of the items and you could not Identify the SelectedItem.
It would be appreciated also being able to set the BackgroundColor / BorderColor of selectedItem instead of just a orange color.
### Steps to Reproduce

Having this XAML
```
<ContentPage>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition Width="auto" />
            </Grid.ColumnDefinitions>
            <CollectionView Grid.Column="0" 
                            SelectionMode="Single"
                            SelectedItem="{Binding SelectedItem, Mode=TwoWay}"
                            ItemsSource="{Binding ObservableCollectionTest}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" />
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid BackgroundColor="Wheat">
                            <Label Text="{Binding}"></Label>
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
                
            </CollectionView>
            <Label Grid.Column="1"
                   Text="{Binding SelectedItem}" />
        </Grid>
    </ContentPage>
```
With this data in the Model
```
public static string SelectedItemPropertyName() { return nameof(SelectedItem); }
        private string _SelectedItem;
        public string SelectedItem
        {
            get
            {
                return _SelectedItem;
            }
            set
            {
                _SelectedItem = value;
                RaisePropertyChanged();
            }
        }
        public static string ObservableCollectionTestPropertyName() { return nameof(ObservableCollectionTest); }
        private ObservableCollection<string> _ObservableCollectionTest = new ObservableCollection<string>(new List<string>() { "Test1", "test2", "test3" } );
        public ObservableCollection<string> ObservableCollectionTest
        {
            get
            {
                return _ObservableCollectionTest;
            }
            set
            {
                _ObservableCollectionTest = value;
                RaisePropertyChanged();
            }
        }
SelectedItem = ObservableCollectionTest[1];
```
### Expected Behavior
SelectedItem having a different background color or at least a border color
### Actual Behavior
It looks like the rest of the items
### Basic Information

- Version with issue: 4.0.0.232914-pre6

- IDE: Visual Studio Community 2017 version 15.9.9
- Platform Target Frameworks: 
  - Android: 8.1

**Comment by hartez** [comment]
The orange color is actually the value for [`state_activated`](https://developer.android.com/reference/android/graphics/drawable/StateListDrawable.html#attr_android:state_activated) in your Android app's theme. So not everyone will see orange; that's just the AppCompat default. This is the fallback value if nothing else has been specified. 

When an item in the CollectionView is selected, the VisualState for the root Forms element of the item is changed to `Selected`. You can use the VisualStateManager to manage what a selected item looks like. For an example of this, take a look at the [SelectionModeGallery in Control Gallery](https://github.com/xamarin/Xamarin.Forms/blob/4.0.0/Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/SelectionGalleries/SelectionModeGallery.xaml#L8). On that page, the background color for the selected item is being set to `LightSkyBlue`. Any other Forms property can also be set; for instance, try adding `<Setter Property="Scale" Value="1.5" />` to the `<VisualState.Setters>` tag.

At the moment, this is somewhat limited; you can really only modify the root element in your ItemTemplate. We plan to address this by implementing https://github.com/xamarin/Xamarin.Forms/issues/4924 which will allow targeting child elements.

**Comment by adrianknight89** [comment]
@hartez Is there a reason to keep this issue open? Looks like #4924 is all that's needed. @psp589 What you're asking is only two properties. What if other people want more? Personally, I'm against adding new properties. We should leverage VSM. You could also add properties to your model and manage UI state from there though this may require a bit more work than you were thinking.

**Comment by psp589** [comment]
@adrianknight89  Well, I agree with you regarding the addition of only two properties. Maybe what could be added is a SelectedItemTemplate, where you could specify the whole look of a selected item, like some controls, like Synfusion listview , provide. 
The issue could be solved using the Visual State Manager, but something eassier than that, to something very usual (almost mandatory) the need of changing the look of a selected item would be much appreciated.

**Comment by MSiccDev** [comment]
Leaving this crump here for others that may face the same issue. I am using the VSM to set the background of my SelectedItem and the BorderColor of its Frame. The color I use is opaque, so I had the orange-colored default visible as well. If you want to get rid of that but keep your VSM, just add this line to your app theme/xml:

`<item name="android:colorActivatedHighlight">@android:color/transparent</item>`

[The ViewHolder code of CollectionView](https://github.com/xamarin/Xamarin.Forms/blob/b5ade7639f2657253a3f9ed8b336d6073f6cb4b1/Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs#L78) picks this color up and creates a new DrawableStateList with that color (which defaults to the above-mentioned orange in AppCompat). This way, there is no need for customized code.

**Comment by Phenek** [comment]
Hello,
When I have a Border as custom ItemTemplate with CornerRadius, 
I can see the orange background behind the Border.

As default it would be great to set it as transparent.
I mean, it's pretty anoying each time I am creating a new App, 
I am like:  "Well, again this orange background... What is the line again, let's google it.." 
Each time since 2011
