### ISSUE TITLE
CollectionView with Incremental Collection (RemainingItemsThreshold)

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5623]
### Description
I don't see any way of working with an incremental collection because I dont kwow when should I call LoadMoreItems method, with a ListView there is an ItemAppearing event, in there you could figure it out when you're reaching the last items so you could load more, in a scrollview we have scrolled event, so you could figure it out when you're reaching the bottom of the list so you could load more items, but with CollectionView I dont see the way to do it.

- Version with issue: 4.0.0.232914-pre6
- IDE: Visual Studio Community 2017 version 15.9.9
- Platform Target Frameworks: 

  - Android: 8.1
  - UWP:  Windows 10 version 1803 Build 17134

**Comment by adrianknight89** [comment]
There is a proposed feature for this: RemainingItemsThreshold

https://github.com/xamarin/Xamarin.Forms/issues/3172

**Comment by jfversluis** [comment]
With merging #5754 I’m going to close this for now. Should’ve happened automatically, but didn’t ¯\_(ツ)_/¯
