### ISSUE TITLE
CollectionView SelectionMode SelectionMode="Multiple" Not working

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5625]
### Description
I can't get to work the selection multiple in CollectionView, I can't select more than one item, also I didn't see a SelectedItems property, only SelectedItem
### Steps to Reproduce

Having this XAML
```
<ContentPage>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition />
                <ColumnDefinition Width="auto" />
            </Grid.ColumnDefinitions>
            <CollectionView Grid.Column="0" 
                            SelectionMode="Multiple"
                            SelectedItems="{Binding SelectedItems, Mode=TwoWay}"
                            ItemsSource="{Binding ObservableCollectionTest}">
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" />
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid>
                            <Label Text="{Binding}"></Label>
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
                
            </CollectionView>
            <StackLayout Orientation="Vertical" Grid.Column="1">
                  <Label Text="SelectedItems" />
                   <ListView ItemsSource="{Binding SelectedItems}"
                          WidthRequest="400"
                          BackgroundColor="Green"
                          HorizontalOptions="Center">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell>
                                <Grid>
                                    <Label Text="{Binding}"></Label>
                                </Grid>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>    
                </ListView>
            </StackLayout>
        </Grid>
    </ContentPage>
```
With this data in the Model
```
public static string SelectedItemsPropertyName() { return nameof(SelectedItems); }
        private ObservableCollection<string>_SelectedItems;
        public ObservableCollection<string>SelectedItems
        {
            get
            {
                return _SelectedItems;
            }
            set
            {
                _SelectedItems = value;
                RaisePropertyChanged();
            }
        }
        public static string ObservableCollectionTestPropertyName() { return nameof(ObservableCollectionTest); }
        private ObservableCollection<string> _ObservableCollectionTest = new ObservableCollection<string>(new List<string>() { "Test1", "test2", "test3" } );
        public ObservableCollection<string> ObservableCollectionTest
        {
            get
            {
                return _ObservableCollectionTest;
            }
            set
            {
                _ObservableCollectionTest = value;
                RaisePropertyChanged();
            }
        }
SelectedItem = ObservableCollectionTest[1];

```

### Expected Behavior
Could select more than 1 item
### Actual Behavior
is not possible
### Basic Information

- Version with issue: 4.0.0.232914-pre6 ( not working neither in  4.0.0-pre8)
- IDE: Visual Studio Community 2017 version 15.9.9
- Platform Target Frameworks: 
  - Android: 8.1
  - UWP:  Windows 10 version 1803 Build 17134

**Comment by adrianknight89** [comment]
#5352

**Comment by psp589** [comment]
#5352 says Android and IOS, what with UWP ?

**Comment by adrianknight89** [comment]
Not sure if @hartez is still updating https://gist.github.com/hartez/7d0edd4182dbc7de65cebc6c67f72e14, but I think the change was implemented only for Android and iOS for now.

**Comment by samhouts** [comment]
This should be in 4.0.0-pre8. Thanks!

**Comment by psp589** [comment]
@samhouts  I've just tried 4.0.0-pre8 and it is still not working, and there is no selectedItems property available. Could this issue be re-opened?

**Comment by samhouts** [comment]
@psp589 We're currently focusing on implementing all features for Android and iOS before moving on to UWP. 

We'll take a look at Android and see what's missing. Thanks!

**Comment by psp589** [comment]
@samhouts  I'm working with both  Android and UWP, should I add then different issues when reporting ? one for Android and one for UWP ? Should I add for this issue, a different one for UWP ?

**Comment by samhouts** [comment]
@psp589 No need to report separate issues. Things that are not implemented in UWP yet will be tracked on the main ticket. Thanks!

**Comment by samhouts** [comment]
@psp589 To make this easier to reproduce, can you please attach a small project that demonstrates this issue? Thanks!

**Comment by psp589** [comment]
@samhouts  see https://github.com/psp589/XamarinFormsIssuesReproduction, last section marked as "Issue #5625"

**Comment by pikausp** [comment]
To expand on this issue

- The `PropertyChanged` gets called
- The binding source is not updated

What helped me was creating a simple bridge behavior that proxied `SelectedItems` by cloning value of the source `SelectedItems` property. 

I believe the issue here is that the instance of the `SelectionList` remains the same for the lifetime of the view and so the bindings are not updated. Since there is a manual call to `OnPropertyChanged`
https://github.com/xamarin/Xamarin.Forms/blob/b20afe467fbac5769011801e1b7998d395e08610/Xamarin.Forms.Core/Items/SelectableItemsView.cs#L73
https://github.com/xamarin/Xamarin.Forms/blob/b20afe467fbac5769011801e1b7998d395e08610/Xamarin.Forms.Core/Items/SelectionList.cs#L31
the `PropertyChanged` is indeed invoked, but that does not trigger the system to update bindings.

**Comment by humhei** [comment]
![image](https://user-images.githubusercontent.com/25994449/59960862-a22ee900-9501-11e9-858d-ef1402180975.png)
* `Set vm selection to List`
* `Clear VM seletion and items 1 and 2`

Nothing will happened


PR #6629 should fixed this issue!

**Comment by francipvb** [comment]
Hello,

Can someone take a look on this again? I'm stuck trying to get this working on android. I have the screen reader enabled.

Cheers,

**Comment by hartez** [comment]
@francipvb Since this was closed so long ago and since you're using a screen reader, I would suggest opening a new issue.

**Comment by cdavidyoung** [comment]
Well, this explains why two way binding is not working in Multiple (at least in Android that I am testing in).  I guess I am going to have to implement my own Multiple using Single.  Why is this issue closed if it hasn't been fixed?

**Comment by luisyoroslav** [comment]
> So even though two way binding is not working in Multiple I have been able to get multiple selection to work in my MVVM app. The trick is to declare and instantiate the list that is bound to SelectedItems with a type of object and cast it later:
> 
> ```
>     ObservableCollection<object> selectedWaypoints;
>     public ObservableCollection<object> SelectedWaypoints
>     {
>         get => selectedWaypoints;
>         set
>         { // note that this is never called
>            _userDialogs.Toast($"SelectedWaypoints: {value?.Count}", System.TimeSpan.FromSeconds(1));
>            selectedWaypoints = value;
>            RaisePropertyChanged(() => SelectedWaypoints);
>         }
>     }
> ```
> 
> In constructor:
> 
> ```
>         SelectedWaypoints = new ObservableCollection<object>();
> ```
> 
> bound to SelectionChangedCommand - cast to target class messageItem:
> 
> ```
>     public MvxCommand ItemSelectedCommand => new MvxCommand((() =>
>     {
>        if (SelectedWaypoints.Count> 0)
>           _userDialogs.Toast($"ItemSelectedCommand: {SelectedWaypoints?.Count} {((messageItem)SelectedWaypoints?[SelectedWaypoints.Count-1]).Title}", System.TimeSpan.FromSeconds(1));
>        else
>           _userDialogs.Toast($"ItemSelectedCommand: {SelectedWaypoints?.Count}", System.TimeSpan.FromSeconds(1));
>     }));
> ```

Works like a charm, thanks
