### ISSUE TITLE
Frame.CornerRadius is not respected by iOS when Editor is inside

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5626]
### Description
Frame.CornerRadius does not work in iOS when an `Editor` is inside Frame.
### Steps to Reproduce

1. Add a Editor inside a Frame in ContentPage in Shell
2. Set CornerRadius on Frame
3. Deploy the app

### Expected Behavior
Frame with rounded corners
### Actual Behavior
The Frame don't have rounded corners
### Basic Information

- Version with issue: Xamarin.Forms 4 pre-6
- Last known good version:NA
- IDE:Visual Studio for Mac preview
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://send.firefox.com/download/3b9346c9bb/#3krIL6-Gw1niPFMzWincdw

**Comment by shanranm** [comment]
Already fixed? Unable to reproduce with 4.1, 4.2 and 4.3-pre1

**Comment by henriqueu96** [comment]
I couldn't reproduce either

**Comment by marcofolio** [comment]
Indeed unable to reproduce, specifically tested with Shell as well.

**Comment by shanranm** [comment]
@HobDev @samhouts someone want to close it?

**Comment by HobDev** [comment]
Fixed! verified .
