### ISSUE TITLE
[Material,iOS] The App with Grid inside ScrollView hangs on iOS 

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5627]
### Description
I have a Grid as main layout in the contentpage. If I put this main grid in Scroll View the app hangs (does not show any thing) on iOs.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: Xamarin.forms 4 pre-6
- Last known good version:
- IDE:Visual Studio for Mac preview
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://send.firefox.com/download/3b9346c9bb/#3krIL6-Gw1niPFMzWincdw

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/5628#issuecomment-475799286

**Comment by HobDev** [comment]
[#5628 (comment)](https://github.com/xamarin/Xamarin.Forms/issues/5628#issuecomment-475958782)
