### ISSUE TITLE
[Material,iOS] unable to set HorizontalOption or VerticalOption in Grid

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5628]
### Description
I have Grid as my main Layout in contentPage. If I set HorizontalOptions or VerticalOptions with Visual="Material" the app does not work on iOS
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: xamarin.forms pre-6
- Last known good version:
- IDE:Visual Studio for Mac preview
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://send.firefox.com/download/3b9346c9bb/#3krIL6-Gw1niPFMzWincdw

**Comment by PureWeen** [comment]
@HobDev can you update to pre7 and let me know if it works?

I've also attached my test run against pre7 which looks to run ok

[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/2998447/Test.zip)

**Comment by PureWeen** [comment]
@HobDev also the app looks pretty interesting!! Thank you for reporting issues and keep us updated on how your use of shell and visual goes!!


https://twitter.com/paul_dipietro
https://twitter.com/davidortinau
https://twitter.com/PureWeen

**Comment by HobDev** [comment]
@PureWeen I run the attached project. I also tested on my app project. With Xamarin.Forms-pre7 the I can set HorizontalOptions and VerticalOptions on Grid. I can also make ScrollView the main layout.  Thankyou

**Comment by HobDev** [comment]
About Shell I can say it will make developers more productive. Developing complex apps will be lots easier with Shell. Visual will give more options about design.
