### ISSUE TITLE
[Enhancement] selectable on label, maxline on label without textwrap

### ISSUE THREAD

**Issue by 632575987** [xamarin/Xamarin.Forms#5632]
1.  Is there a way to ***make the label control can be selectable***. like some text on iOS, the text can be selectable ***and then copy,paste options appears***, but I can't find the property on the label to set this effect.

2. 【 label & editor 】 Usually I want to ***display a long and multilines text on the phone screen instead of textwrap***, If the text is out of the screen, I want to scroll left and right to view it. please provide a property just like NoWrapInMultiLine.(currently I find that NoWrap is not working when I set the maxlines and NoWrap at the same time)

I love Xamarin.forms.❤

**Comment by troyanas** [comment]
Also depending on text length, it is not working with TailTruncation type also.

**Comment by James3UK** [comment]
I was quite surprised to see that it wasn't easily possible to allow copying of text on label fields.
surely this is something that should be built in. It seems there are a few examples of custom renderers but this is something very basic that many users will want.
Links to examples:
https://github.com/HeikkiDev/XFSelectableLabel
https://github.com/chetanrawat04/CustomLabelRenderer
https://medium.com/@HeikkiDev/selectable-label-on-xamarin-forms-9b050267bf8e
https://medium.com/@anna.domashych/selectable-read-only-multiline-text-field-in-xamarin-forms-69d09276d580
https://stackoverflow.com/questions/48165549/select-text-and-copy-from-label-xamarin-forms
