### ISSUE TITLE
[Shell] Padding not working with Android translucent status bar

### ISSUE THREAD

**Issue by claunia** [xamarin/Xamarin.Forms#5635]
### Description
Setting padding in Xamarin Shell does not work to prevent the navigation bar to be drawn below Android's status bar.

### Steps to Reproduce

1. In MainActivity add:
```
this.Window.AddFlags(WindowManagerFlags.TranslucentStatus);
```
2. In AppShell.xaml add:
```
     <Shell.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <On Platform="Android">0, 24, 0, 0</On>
            <On Platform="iOS">0, 20, 0, 0</On>
        </OnPlatform>
    </Shell.Padding>
```

### Expected Behavior
Shell page title and back button appears below status bar.

### Actual Behavior
Shell page title is rendered below status bar. 

### Basic Information

- Version with issue: 3.6.0.220655
- Last known good version: None
- IDE: VS2019
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices: Android emulator

### Screenshots

![image](https://user-images.githubusercontent.com/1234569/54702275-741ac100-4b2e-11e9-90d2-c6ff1c0cf338.png)

**Comment by samhouts** [comment]
@claunia For some reason, I can no longer reproduce this behavior, even on 3.6.0. Can you please try the latest 4.0.0 prerelease and see if this is still an issue for you? If so, can you please attach a sample project? Thanks!

**Comment by samhouts** [comment]
@claunia  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by claunia** [comment]
@samhouts I was pretty sure I did answer I could not reproduce it anymore after updating Xamarin.Forms. Thanks.
