### ISSUE TITLE
[Feedback] Xamarin Forms Shared project UWP menu disappears with no way to go back or show the menu again.

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#5637]
### Description

<p><p>I implemented MasterDetailPage into my app, but on Windows 10 the behavior seems a bit weird. When the app starts, the menu is showing as expected. But when I click an item, it disappears with no way to go back or show the menu again.</p>
<p>This has been reported before some 19months ago and isn’t something new.</p>
<p><a target=_blank href="https://stackoverflow.com/questions/45640159/xamarin-masterdetailpage-menu-on-uwp">https://stackoverflow.com/questions/45640159/xamarin-masterdetailpage-menu-on-uwp</a></p>
<p>Easy to reproduce  with a MasterDetailPage set MasterBehavior = MasterBehavior.Popover</p>
<ol>
<li>
<p>Detail = …some new page;<br>
IsPresented = false;</p>
</li>
<li>
<p>. …menu is now gone forever in UWP?</p>
</li>
</ol>
</p>
<a href="https://developercommunity.visualstudio.com/content/problem/489958/xamarin-forms-shared-project-uwp-menu-disappears-w.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/820675">original linked feedback ticket</a>.

### Source

[823510](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/823510)

**Comment by mrlacey** [comment]
This looks connected to #5412 

Regarding the linked StackOverflow link. The sample app no longer shows this behavior but has other issues.
