### ISSUE TITLE
[Material,Android]: Setting focus to Entry inside ListView crashes the app

### ISSUE THREAD

**Issue by tmt242001** [xamarin/Xamarin.Forms#5641]
### Description
When using Xamarin.Forms Material.

If there is a Entry inside ListView, Setting focus to the Entry will crash the app.
### Steps to Reproduce

1. Run the attach app
2. Set focus to "Inside List View" Entry

### Expected Behavior

Not to crash.

### Actual Behavior

App crash.

### Basic Information

- Version with issue: 3.6.0.264807

- Last known good version: It works when you set Visual="Material" to Visual="Default"
- IDE:
- Platform Target Frameworks: 
  - Android
- Nuget Packages: https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/

### Error

Unhandled Exception:

System.InvalidCastException: Specified cast is not valid. occurred

### Reproduction Link

[ListViewEntryIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2989939/ListViewEntryIssue.zip)

**Comment by mrbelk** [comment]
I'm experiencing a similar problem.

**Comment by PureWeen** [comment]
@mrbelk  this will be fixed in the next SR

**Comment by tmt242001** [comment]
Fixed in 3.6.0.293080
