### ISSUE TITLE
[Material,Android] Button Overlay Issue

### ISSUE THREAD

**Issue by thudugala** [xamarin/Xamarin.Forms#5642]
### Description
When using Xamarin.Forms Material.

If controls are overlay on top of Button there are not visible.

### Steps to Reproduce

1. Run the attach app

### Expected Behavior

See the Left and Right Label on top of Button

### Actual Behavior

Cannot see the Left and Right Label on top of Button

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: It works when you set Visual="Material" to Visual="Default"
- Platform Target Frameworks: 
  - Android: 
- Nuget Packages:  https://www.nuget.org/packages/Xamarin.Forms.Visual.Material/

### Screenshots

Visual="Material"
![image](https://user-images.githubusercontent.com/4112014/54718394-46ca2380-4bbf-11e9-95c3-a8091a97cb16.png)

Visual="Default"
![image](https://user-images.githubusercontent.com/4112014/54718295-108ca400-4bbf-11e9-95b4-219deff6e7f1.png)

### Reproduction Link

[ButtonOverlayIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/2990085/ButtonOverlayIssue.zip)

**Comment by PureWeen** [comment]
Hmm this is an interesting one. 

https://stackoverflow.com/questions/28105551/wrong-render-order-for-button-when-material-theme-is-applied

I tested setting stateListAnimator to null and that fixes the z indexes but I need to research a bit more about the best way to fix this.

**Comment by neville-nazerane** [comment]
This seems important as overlaying Material buttons can be used to overlay images and create buttons with icons in them. There doesn't have a good alternative as of now. Other solutions such as using a stacklayout require relatively a lot of steps and are still not the same as a button.

**Comment by PureWeen** [comment]
@neville-nazerane one fix that should work would be to use the android platform specific and set the elevation on the labels to something high. That should cause the labels to rise above

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.androidspecific.visualelement.setelevation?view=xamarin-forms

**Comment by PureWeen** [comment]
As a note this one is partially fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/6271

the main side effect that exists is once you click on the button then the labels disappear under the button. The material renderer has a dynamic elevation so the elevation increases when it's clicked
