### ISSUE TITLE
[Enhancement] Xamarin.Forms :Android Swipe to previous page like Telegram in IOS

### ISSUE THREAD

**Issue by 851265601** [xamarin/Xamarin.Forms#5643]
## Summary

I can achieved that swipe to previous page like following link in IOS.
https://i.stack.imgur.com/wAWKk.gif

But it cannot be achieved(same as in IOS, swipe to previous page follow fingertips ) in android following link.
https://i.stack.imgur.com/kStAP.gif

Following is my code.
In IOS:
     
    [assembly: ExportRenderer(typeof(HIPSTO.Controls.CustomContentPage), 
        typeof(HIPSTO.iOS.Platform.Renderers.IOSPageRenderer))]     
    namespace HIPSTO.iOS.Platform.Renderers 
    {
       public class IOSPageRenderer : PageRenderer        
       {         
          public override void ViewWillAppear(bool animated)            
         {              
            base.ViewWillAppear(animated);

            ViewController.NavigationController.InteractivePopGestureRecognizer.Enabled = true;
            ViewController.NavigationController.InteractivePopGestureRecognizer.Delegate = new UIKit.UIGestureRecognizerDelegate();
          }
       }
    }

In Android.
        
       [assembly: ExportRenderer(typeof(SwipePageDemo.Controls.TransitionNavigationPage), 
        typeof(TransitionNavigationPageRenderer))]
        namespace SwipePageDemo.Droid.Renderers
       {
       public class TransitionNavigationPageRenderer : NavigationPageRenderer
       {
        public TransitionNavigationPageRenderer(Context context) : base(context)
       {
        }
        protected override void SetupPageTransition(Android.Support.V4.App.FragmentTransaction transaction, bool isPush)
       {

                if (isPush)
                {

                }
                else
                {
                    transaction.SetCustomAnimations(Resource.Animation.enter_left, Resource.Animation.exit_right,
                                                    Resource.Animation.enter_right, Resource.Animation.exit_left);
                }

      }
     }
     }

**Comment by jfversluis** [comment]
Not sure what is being meant here, sorry. But it's quite old so I expect it not to be relevant anymore. If you still have issues please open something new, thanks!
