### ISSUE TITLE
Populating a CollectionView with data error with System.TypeInitializationException: The type initializer for 'Xamarin.Forms.ItemsView' threw an exception.

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#5644]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview#populating-a-collectionview-with-data

### Description

When I add the Xaml code of CollectionView to my project, I find that it can't run, and I will report the following **_error: System.TypeInitializationException: The type initializer for 'Xamarin.Forms.ItemsView' threw an exception._**

### Steps to Reproduce

1. Create a new forms app, update xamarin forms to Xamarin.Forms 4.0-pre7
2. Add code in Xaml:
```
 <StackLayout>
        <!-- Place new controls here -->
        <Label Text="Welcome to Xamarin.Forms!" 
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" />
        <CollectionView>
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Baboon</x:String>
                    <x:String>Capuchin Monkey</x:String>
                    <x:String>Blue Monkey</x:String>
                    <x:String>Squirrel Monkey</x:String>
                    <x:String>Golden Lion Tamarin</x:String>
                    <x:String>Howler Monkey</x:String>
                    <x:String>Japanese Macaque</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
        </CollectionView>
    </StackLayout>
```
3.  Run project ,then happen this error:

**System.TypeInitializationException: The type initializer for 'Xamarin.Forms.ItemsView' threw an exception.**

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS-2017-15.9.8
- Platform Target Frameworks: 
  - iOS:  IOS 12.1
  - Android: Android 8.1  
- Android Support Library Version: API 27
- Nuget Packages:Xamarin.Forms 4.0-pre7
- Affected Devices: IPhoneX / AndroidEmulator

### Screenshots

![image](https://user-images.githubusercontent.com/7145819/54731683-9c57fd80-4bca-11e9-8dec-8faab68e8054.png)

### Reproduction Link

https://www.dropbox.com/s/6ocl8e3g4azluxw/AppForms3.rar?dl=0

> VS bug [#824637](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/824637)

**Comment by samhouts** [comment]
Please add `Forms.SetFlags("CollectionView_Experimental");` to your AppDelegate and MainActivity, as described in the paragraph above section you linked to in the documentation. Thanks!
