### ISSUE TITLE
[Shell,FlyoutIcon]  iOS does not show FlyoutIcon and FlyoutIcon ImageSource does not work

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5646]
### Description
The FlyoutIcon on iOS is not visible. On the other hand setting FlyoutIcon to ImageSource does not work on Android as well as iOS.
### Steps to Reproduce

1. Create new App with Shell and Flyout enabled
2. Deploy the app. Android will show default FlyoutIcon. Whereas iOS don't have any FlyoutIcon.
3. Set FlyoutIcon to Image Source. Still the Android will have default FlyoutIcon and iOS will not have FlyoutIcon.

### Expected Behavior
FlyoutIcon on both Android and iOS and FlyoutIcon ImageSource should work
### Actual Behavior
FlyoutIcon not shown on iOS and ImageSource is not working
### Basic Information

- Version with issue: Xamarin.Forms-pre7
- Last known good version:
- IDE: Visual Studio for Mac preview 
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2991094/BugTest.zip)

**Comment by HobDev** [comment]
Strangely the ImageSource on FlyoutIcon is being set on `ShellItem`on Android platform. 

<img width="350" alt="Screenshot 2019-03-21 at 9 54 41 PM" src="https://user-images.githubusercontent.com/9531864/54767974-444de500-4c24-11e9-8c17-26a23cd889b0.png">

**Comment by HobDev** [comment]
And the same issue with iOS.

![Simulator Screen Shot - iPhone 8 Plus - 2019-03-22 at 10 20 43](https://user-images.githubusercontent.com/9531864/54801574-7ba4ac00-4c8d-11e9-8650-b24f4d5471ac.png)

**Comment by rmarinho** [comment]
You should set up with the file extension "Hamburger.png" , the missing iOS is other issue will be solve don #5567

**Comment by HobDev** [comment]
@rmarinho The ImageSource on FlyoutIcon is being set on ShellItem on  Android and iOS. You can test by yourself by running the attached project.

**Comment by HobDev** [comment]
I also uploaded screenshots about the behaviour.

**Comment by rmarinho** [comment]
@HobDev if I change from "Hamburger" to "Hamburger.png" I can see it on android don't you ?

**Comment by HobDev** [comment]
@rmarinho I changed the `Hamburger` to `Hamburger.png`. But it still set ShellItem Icon. Click on default hambuger icon on android. You will see that the `Hamburger.png` is set on first shellItem.

**Comment by HobDev** [comment]
same with iOS.

**Comment by HobDev** [comment]
@rmarinho The issue should be re-opened. As the Hamburger.png is set on ShellItem. It should have been set on the slider.

**Comment by rmarinho** [comment]
I will look at it again.

**Comment by HobDev** [comment]
@rmarinho With latest update the FlyoutIcon is now shown on both Android and iOS. The Custom Icon can also be set. Although the custom icon on iOS is smaller. But that is a different issue. Please close the issue if you find suitable.
