### ISSUE TITLE
[Enhancement] Setup CI to install nugets into different projects and run basic tests to verify compatibility

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5656]
## Summary
We've added sets of ABI comparison checks to our CI so that we can validate breaking changes between releases but it would still be a good idea to have an automated process that installs a nuget and then runs a basic set of UI tests against said app.

For example it can
- pull down smart hotel 360
- install latest nugets
- click through a few basic buttons
- This should also run all of these projects with proguard and/or the new r8/d8 settings to ensure all proguard and multidex rules are working

If we had something like this in place then our ABI break with IVisualElementRenderer would have been caught a few months ago.

Ideally we can also expand this out to test default apps from 3rd parties. We can run this same set of tests against a baseline Telerik, SyncFusion, FFImageLoading, CarouselView, etc..

The cake scripts we added recently make it fairly easy to install new nugets either through the CLI or just by doing a basic string replace on the csproj files

## Intended Use Case
Verify unexpected ABI or other breaks that will cause hardship to 3rd party libraries

**Comment by jfversluis** [comment]
Old and no clue what this is about anymore. Let's close it.
