### ISSUE TITLE
[Enhancement] Editor.AutoSize should take into account a "multi line" Placeholder

### ISSUE THREAD

**Issue by SymboLinker** [xamarin/Xamarin.Forms#5659]
Editor.AutoSize should take into account a "multi line" Placeholder, which includes the case that the text of the Placeholder is wrapped. A related issue is "Editor with AutoSize should have an initial Height #4972".

**Comment by rickclephas** [comment]
Adding the following to a custom renderer on iOS makes sure the editor height is at least as high as the placeholder:
```C#
public override CGSize SizeThatFits(CGSize size)
{
    var baseSize = base.SizeThatFits(size);
    // Get size for placeholder
     var placeholderLabel = _placeholderLabel;
    if (placeholderLabel == null) return baseSize;
    var placeholderSize = placeholderLabel.SizeThatFits(size);
            
    // Add the horizontal and vertical spacing around the placeholder 
    var edgeInsets = TextView.TextContainerInset;
    var lineFragmentPadding = TextView.TextContainer.LineFragmentPadding;
    placeholderSize.Width += lineFragmentPadding * 2;
    placeholderSize.Height += edgeInsets.Top + edgeInsets.Bottom;
            
    // Return the largest size
    return new CGSize(Math.Max(baseSize.Width, placeholderSize.Width), Math.Max(baseSize.Height, placeholderSize.Height));
}
```

We used the following code the get the placeholder label:
```C#
_placeholderLabel = Control.Subviews.FirstOrDefault(view => view is UILabel);
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
