### ISSUE TITLE
[Shell,Flyout] First Flyout Item is always selected and highlighted on startup

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5662]
### Description
The First Flyout Item is always selected and highlighted on App Startup. Even if the first page is set to a tab. This screen shot is when the Flyout item is the first  page on startup.

<img width="350" alt="Screenshot 2019-03-22 at 10 59 47 AM" src="https://user-images.githubusercontent.com/9531864/54802980-967a1f00-4c93-11e9-9547-6de094c66acb.png">

This one is when the first page on startup is a tab.

<img width="350" alt="Screenshot 2019-03-22 at 10 49 14 AM" src="https://user-images.githubusercontent.com/9531864/54802992-ac87df80-4c93-11e9-95d4-43376eb4db97.png">

### Basic Information

- Version with issue:Xamarin.Forms-pre7
- Last known good version: NA
- IDE:Visual Studio for Mac Preview

- Affected Devices: iOS and Android

### Reproduction Link

[BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/2995133/BugTest.zip)

**Comment by samhouts** [comment]
still an issue in pre10

**Comment by HobDev** [comment]
@samhouts @PureWeen Yes this is still an issue. There is always a gray highlighted area in flyout even if the tabs are active. Please compare the above images with sample.

**Comment by HobDev** [comment]
The First FlyoutItem is always selected and highlighted when tab is active. It is there to hold the title of TabBar. It was empty because I didn't specify the title of TabBar in my repro project.
