### ISSUE TITLE
NavigationPage.SetTitleView not working in WPF

### ISSUE THREAD

**Issue by nitishmani** [xamarin/Xamarin.Forms#5664]
### Description
When I try to add a custom view on the title, it is working across all the platforms except WPF
### Steps to Reproduce

1. Add a WPF project to the Xamarin.Forms project, and add all the required Xamarin forms dependencies
2. Add a view in the title of a navigation page as below 
NavigationPage.SetTitleView(this, new Button(){Text = "NewButton"});
3. Run the sample

### Expected Behavior
It should show the button on the title bar along with the text "NewButton"
### Actual Behavior
It is showing the default title and not showing the new added Button in the title view
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - WPF:  3.6.0.264807
- Nuget Packages: Xamarin.Forms.Platforms.WPF 3.6.0.264807
- Affected Devices:
Windows 10
[TitleView_IssueWPF.zip](https://github.com/xamarin/Xamarin.Forms/files/2995284/TitleView_IssueWPF.zip)

**Comment by nitishmani** [comment]
Is there any specific timeline for the fix of this bug? and when can i get the fix?

**Comment by thedjnova** [comment]
Im going to take a look at this, will report back soon as can :)

**Comment by nitishmani2100** [comment]
Any update on this?

**Comment by nitishmani** [comment]
Any update on the availability of the fix? I am waiting for this for a looooooooooooooooooooong time

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/3868
