### ISSUE TITLE
Target Framework Version is currently v8.1 and must be greater than or equal to v9.0 in order to use Material on Android.

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5681]
### Description
Android v9.0 not detected

### Steps to Reproduce

1. Create a new solution
2. Update packages
3. Add Material config to MainActivity

### Basic Information

- Version with issue: 4.0 pre-7
- IDE: Visual Studio Windows 2017
- Platform Target Frameworks: 
  - Android: 7.0
- Android Support Library Version: 9.0
- Nuget Packages:
  - LiveXAML 2.1.70
  - NETStandard.Library 2.0.3
  - Newtonsoft.Json 12.0.1
  - Xamarin.Android.Support.Annotations 28.0.0.1
  - Xamarin.Android.Support.Compat 28.0.0.1
  - Xamarin.Android.Support.Core.UI 28.0.0.1
  - Xamarin.Android.Support.Core.Utils 28.0.0.1
  - Xamarin.Android.Support.CustomTabs 28.0.0.1
  - Xamarin.Android.Support.Design 28.0.0.1
  - Xamarin.Android.Support.Fragment 28.0.0.1
  - Xamarin.Android.Support.Media.Compat 28.0.0.1
  - Xamarin.Android.Support.Transition 28.0.0.1
  - Xamarin.Android.Support.v4 28.0.0.1
  - Xamarin.Android.Support.v7.AppCompat 28.0.0.1
  - Xamarin.Android.Support.v7.CardView 28.0.0.1
  - Xamarin.Android.Support.v7.MediaRouter 28.0.0.1
  - Xamarin.Android.Support.v7.RecyclerView 28.0.0.1
  - Xamarin.Controls.SignaturePad.Forms 3.0.0
  - Xamarin.Essentials 1.1.0
  - Xamarin.Forms 4.0.0.250467-pre7
  - Xamarin.Forms.Visual.Material 4.0.0.250467-pre7
- Affected Devices:

**Comment by Moltroon** [comment]
[MaterialError.zip](https://github.com/xamarin/Xamarin.Forms/files/3004388/MaterialError.zip)

**Comment by PureWeen** [comment]
@Moltroon you need to update the android project so the Target Android version is set to Android 9.0

I opened your project and it's still set to 8.1
Right click the android project and go into the android properties there and you can set it to 9.0

![image](https://user-images.githubusercontent.com/5375137/54936927-1e0c9b80-4ee9-11e9-8c27-6535cd06340b.png)

**Comment by devjaime** [comment]
I found a small problem in vs2019, the target platform of Android 9.0 did not show it. I opened the same configuration in vs2017 and if you show it to me (for those who are working with material desing visual material vs2019, I share it in case someone else is in it).
![visualstudio2017](https://user-images.githubusercontent.com/26843824/56552879-a1f28b80-655a-11e9-9f65-7b5d82ab0b31.png)
![visualstudio2019](https://user-images.githubusercontent.com/26843824/56552888-a5861280-655a-11e9-8a8f-959fc5db11aa.png)
