### ISSUE TITLE
WPF: ViewCell content width does not update on ListView width change

### ISSUE THREAD

**Issue by domyd** [xamarin/Xamarin.Forms#5682]
### Description
If the `ListView` width changes on WPF (e.g. on resizing the window), the `ViewCell`'s content is not resized to match the new width. The `ViewCell` itself seems to resize just fine (based on the hover effect), however the content does not.

### Steps to Reproduce
1. Create a new Xamarin WPF application
2. Add a `ListView` as a root of a `Page` and give it some strings to display
3. Set an `ItemTemplate` like such:
    ```xml
    <DataTemplate>
        <ViewCell>
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto" />
                    <ColumnDefinition Width="*" />
                    <ColumnDefinition Width="Auto" />
                </Grid.ColumnDefinitions>
    
                <Label Grid.Column="0" Text="X" />
    
                <Label
                    Grid.Column="1"
                    HorizontalOptions="Center"
                    Text="{Binding}" />
    
                <Label Grid.Column="2" Text="X" />
            </Grid>
        </ViewCell>
    </DataTemplate>
    ```
4. Observe as the Xs (representing the boundaries of the content view) don't behave as expected.

### Expected Behavior
The `ViewCell`'s content should resize whenever the `ListView`'s width changes, such that the Xs stay near the window borders.

### Actual Behavior
The `ViewCell`'s content does not resize, resulting in the content staying the same size and either being clipped if the window shrinks, or staying centered if the window widens.

### Basic Information

- Version with issue: Latest stable (3.6.0) as well as latest prerelease (4.0.0.250467-pre7)
- IDE: Visual Studio 15.9.9
- Platform Target Frameworks: 
  - WPF:  .NET Framework 4.7.2

### Screenshots

Starting point:
![image](https://user-images.githubusercontent.com/5590413/54939425-dd347700-4f28-11e9-9080-2c21a97e12d3.png)

Widened window:
![image](https://user-images.githubusercontent.com/5590413/54939456-ef161a00-4f28-11e9-8bf4-b35b910c3dc6.png)

Shrunk window:
![image](https://user-images.githubusercontent.com/5590413/54939469-f89f8200-4f28-11e9-975e-ae91e56b67dd.png)

### Reproduction Link
[ViewCellResize.WPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3004586/ViewCellResize.WPF.zip)

**Comment by jaytilly** [comment]
Added a PR for this if anyone can take a look https://github.com/xamarin/Xamarin.Forms/pull/6179

**Comment by Xamarin2019** [comment]
#9029
