### ISSUE TITLE
Animation tasks do not complete when Animations are removed in Accessibility Settings.

### ISSUE THREAD

**Issue by trolloks** [xamarin/Xamarin.Forms#5686]
### Steps to Reproduce

1. On a Android 9.0 device, go to Settings -> Accessibility -> Remove animations
2. Call any animation - var animationTask = label.FadeTo(1)
3. await the resulting task

### Expected Behavior

Animation completes instantly, Task immediately completes.

### Actual Behavior

Animation does not occur, Task never completes. 

When battery saver is enabled, the complete instantly and works as intended.

### Basic Information

- Version with issue: 3.6.0.264807
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by ejluttmann** [comment]
Thanks for reporting this.  Users of my app are experiencing the same thing, application actually hangs because the animation task never completes if Remove animations is enabled.

**Comment by hartez** [comment]
This is fixed in 4.4.0.

**Comment by janne-hmp** [comment]
This still remains the problem in with using Xamarin in Visual Studio 2022 17.5.5.
