### ISSUE TITLE
Listview SelectionMode=None only works in Android

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#5687]
### Steps to Reproduce

Listview SelectionMode=None - not working in iOS platform

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  iOS 11.4

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
Please provide a zipped reproduction with descriptions of the actual and expected behavior. Thanks.

**Comment by samhouts** [comment]
@luczha  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
