### ISSUE TITLE
Map's Pin Equals makes two Pins equal when they really arent'

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#5690]
## Summary

Not sure if this is a bug or an enhancement... While working on #5689 I came across an issue.

Pin has Equals() implementation based on equality of Label, Position, Type and Address. This means if there are two Pins with same values, they are considered equal. 
See https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps/Pin.cs#L90
So if we have two Pins with same Label, Position, Type and Address, trying to remove 2nd Pin will end up removing first Pin.
Looking at the commit history this is how it's been working since the beginning.
I don't see why Equals() is necessary.

**Comment by kingces95** [comment]
Hm. Sadly, this would be breaking. Is it worth it? Is there a work around? Just maintain your own hashtable perhaps?

**Comment by andreinitescu** [comment]
@kingces95 I doubt it would be actually breaking any apps. 

If someone has an app where two pins have same GPS position (and same label, type, address) and the pins are removed, the developer is either not aware of a potential issue in his own app, or has implemented a workaround for it. 
I can't see how an app could break because it expects than when it deletes the 2nd pin in the Pin collection, the first Pin is deleted. If developer relies on that it's a very strange/wrong behavior.

So I think it's definitely worth to change it and not leave it like this.

**Comment by PureWeen** [comment]
Did you witness the double removal behavior @andreinitescu on multiple platforms?

Looking at the implementations it looks like with android and iOS since it uses the marker id it'll remove correctly

https://github.com/xamarin/Xamarin.Forms/blob/2c48f4aba6ca75b7735cfda4f30d7a637f4ce54c/Xamarin.Forms.Maps.Android/MapRenderer.cs#L280
https://github.com/xamarin/Xamarin.Forms/blob/2c48f4aba6ca75b7735cfda4f30d7a637f4ce54c/Xamarin.Forms.Maps.iOS/MapRenderer.cs#L403


UWP looks like it'll use the Equals behavior though :-/ 
https://github.com/xamarin/Xamarin.Forms/blob/2c48f4aba6ca75b7735cfda4f30d7a637f4ce54c/Xamarin.Forms.Maps.UWP/MapRenderer.cs#L146

1) I'm curious if the behavior you indicated only happens on UWP. If so it'd be worth fixing to bring things in line
2) should we use MarkerId for equals?

And it would still be a breaking change. It's hard to know if people are using that equals behavior for some reason.

**Comment by andreinitescu** [comment]
> Looking at the implementations it looks like with android and iOS since it uses the marker id it'll remove correctly

Yes, you're correct, the native pins are removed correctly. But the issue is at the Forms level, and it's with the Pin element, when it's removed from the Pins property of the Map. 

For example, suppose we have pinA and pinB, and both have the same Pin properties which Equals uses (Label, Position, Type and Address):

```
Map map = ...;
map.Pins.Add(pinA);  
map.Pins.Add(pinB);
map.Pins.Remove(pinB);  // this will remove pinA instead of pinB
```

This is because IList.Remove uses Equals.
https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.remove?view=netframework-4.8

So while the native Map removes the correct native pin with the id stored by pinA, but that's not the pin we wanted removed, it's pinB.

>  It's hard to know if people are using that equals behavior for some reason.

I think the situation is the other way around. Either many people are just not aware (yet) of this bug in XF or, in practice, nobody adds two pins with same Label, Position, Type and Address. And if the users of these apps really add two pins with same properties, it will end up with the wrong Pin being removed. Depending on how the Pin is used in the business logic of these apps, it will end up with really bad results if the implementation relies on removing using the Pins collection (imagine an app which where there's important meta data associated with the Pin id, and the wrong pin gets deleted).

**Comment by andreinitescu** [comment]
I don't understand why Equals uses those properties. It should at most use only the MarkerId property.

A separate issue: I don't understand why the MarkerId setter is public. It's actually set by the renderers:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps.Android/MapRenderer.cs#L249

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.maps.pin.markerid?view=xamarin-forms
The EditorBrowsableState.Never is not enough.

**Comment by PureWeen** [comment]
> I don't understand why Equals uses those properties. 

Neither do I really. I checked our old private repository where these changes were made and there's not really any historical data there. It was just committed to master back in like version 1.2 👎 

Maybe @samhouts  or @hartez have better historical context on this one then I do. 


Maybe this is the desired outcome?
```
Map map = ...;
map.Pins.Add(pinA);  
map.Pins.Add(pinB);
map.Pins.Remove(pinB);  // this will remove pinA instead of pinB
```

That those pins are meant to be treated as the same thing so removing one and not the other doesn't really matter? 

There is also this point about mutability of the hash
https://github.com/xamarin/Xamarin.Forms/issues/6352

**Comment by jfversluis** [comment]
We won't be doing this for Forms anymore, marking this for .NET MAUI
