### ISSUE TITLE
CollectionView crashes on Android 5.1.1 when selecting item

### ISSUE THREAD

**Issue by petermajor** [xamarin/Xamarin.Forms#5693]
### Description

When selection mode is set to "Single" tapping on any item in the collection view crashes on Android API 21 and 22.

This is due to the following line of code:
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/CollectionView/SelectableViewHolder.cs#L65

The check for setting the background checks for API 21 or above, but the "setForeground" call is only available in Android API 23+ as described in the documetation for View.setForground:
https://developer.android.com/reference/android/view/View#setForeground(android.graphics.drawable.Drawable)

Here is the stack trace:

`
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NoSuchMethodError: no non-static method "Landroid/view/ViewGroup;.setForeground(Landroid/graphics/drawable/Drawable;)V"
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.GetMethodID (Java.Interop.JniObjectReference type, System.String name, System.String signature) [0x0005b] in <405ad2ab226e4e74ba67db96baf95129>:0 
[MonoDroid]   at Java.Interop.JniType.GetInstanceMethod (System.String name, System.String signature) [0x0000c] in <405ad2ab226e4e74ba67db96baf95129>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.GetMethodInfo (System.String encodedMember) [0x00031] in <405ad2ab226e4e74ba67db96baf95129>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00045] in <405ad2ab226e4e74ba67db96baf95129>:0 
[MonoDroid]   at Android.Views.View.set_Foreground (Android.Graphics.Drawables.Drawable value) [0x00031] in <3faca578033c421aa590cc3addd3b6d8>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableViewHolder.EnsureSelectionStates () [0x0001c] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableViewHolder.cs:65 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableViewHolder.set_IsSelected (System.Boolean value) [0x0000f] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableViewHolder.cs:30 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableItemsViewRenderer.MarkItemSelected (System.Object selectedItem) [0x00023] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewRenderer.cs:56 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableItemsViewRenderer.UpdateNativeSelection () [0x0003d] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewRenderer.cs:79 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableItemsViewRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs changedProperty) [0x00015] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewRenderer.cs:23 
[MonoDroid]   at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
[MonoDroid]   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:173 
[MonoDroid]   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:339 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:622 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x00179] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0003d] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:572 
[MonoDroid]   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:122 
[MonoDroid]   at Xamarin.Forms.SelectableItemsView.set_SelectedItem (System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Items\SelectableItemsView.cs:26 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableItemsViewAdapter.UpdateFormsSelection (System.Int32 adapterPosition) [0x00021] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewAdapter.cs:83 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableItemsViewAdapter.SelectableOnClicked (System.Object sender, System.Int32 adapterPosition) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableItemsViewAdapter.cs:70 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableViewHolder.OnViewHolderClicked (System.Int32 adapterPosition) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableViewHolder.cs:51 
[MonoDroid]   at Xamarin.Forms.Platform.Android.SelectableViewHolder.OnClick (Android.Views.View view) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\SelectableViewHolder.cs:40 
[MonoDroid]   at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_v) [0x00011] in <3faca578033c421aa590cc3addd3b6d8>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.43(intptr,intptr,intptr)
`

### Steps to Reproduce

Requirements:
App using CollectionView
SelectionMode set to "Single"
Running on Android API 21 or 22

1. Tap on a collection view row to select it.

### Expected Behavior
Tapping a row should select that row and draw the selection background

### Actual Behavior
On Android API 23 and above, this works as expected.
On Andorid API 21 and 21, tapping on a row will cause the app to crash.

### Basic Information

- Version with issue: 3.6.0 (but from read the source, I think this bug also exists in 4.0.0)
- Last known good version: none
- IDE: visual studio for mac
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 8.1
  - UWP:  n/a
- Android Support Library Version: 27.0.2.1
- Nuget Packages:
- Affected Devices: API 21, 22

**Comment by pinoelefante** [comment]
still here with xamarin.forms 4.0.0.425677

**Comment by hartez** [comment]
Yep, it's working in pre-Lollipop now, but it's broken in Lollipop.

**Comment by RonnyBansemer** [comment]
I'm having this issue on Api Level 22. Is there a workaround until it's fixed?
