### ISSUE TITLE
[shell, ios] ShellTabBarBackgroundColor not styling as expected

### ISSUE THREAD

**Issue by SoniaCH** [xamarin/Xamarin.Forms#5696]
### Description
I dont get the background of the tab changed like in android
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
when using this code :
![andrrr](https://user-images.githubusercontent.com/15122204/55066509-3d88fd00-507e-11e9-8894-f5a9a6bb1c39.JPG)

it 's supposed to change the background of the bottom bar to bleuviolet .

### Actual Behavior
 it works in android  the bottom bar change color but in ios it doesn't.
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.1
  - Android: 8.1,7.1 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:Ios devices

### Screenshots

here is the actual result in android:
![shellandroid](https://user-images.githubusercontent.com/15122204/55009690-4973b100-4fe3-11e9-9114-05f640a72b9c.JPG)

but here is the result in ios:
![shellIos](https://user-images.githubusercontent.com/15122204/55009740-5c868100-4fe3-11e9-8944-ba97c4b6eba1.JPG)

### Reproduction Link
this is a test project that i did for the shell
https://github.com/SoniaCH/ShelltestApp/tree/master/ShelltestApp/ShelltestApp

**Comment by samhouts** [comment]
Fixed by #5075. Try the latest version of 3.6.0 or 4.0.0. Thanks!
