### ISSUE TITLE
[Shell, iOS] StackLayout containing CollectionView results in incorrect layout

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5697]
### Description

When my `ShellContent` contains a root `StackLayout`, whose direct child is a `CollectionView`, the first visible item in the `CollectionView` is the bottom half of the second item:

```
    <StackLayout Margin="20">
        <CollectionView ItemsSource="{Binding Elephants}"
                        ItemTemplate="{StaticResource AnimalTemplate}"
                        SelectionMode="Single"
                        SelectionChanged="OnCollectionViewSelectionChanged" />  
    </StackLayout>
```

However, the layout is fine if the `StackLayout` is removed:

```
        <CollectionView ItemsSource="{Binding Elephants}"
                        ItemTemplate="{StaticResource AnimalTemplate}"
                        SelectionMode="Single"
                        SelectionChanged="OnCollectionViewSelectionChanged" />  
```

Note: this is an iOS only problem. The layout is fine on Android.

### Steps to Reproduce

1. Run the attached sample on iOS.
2. Browse to the Elephants tab.

### Expected Behavior

The data in the `CollectionView` is laid out correctly.

### Actual Behavior

The first visible item in the `CollectionView` is the bottom half of the second item.

### Basic Information

- Version with issue: 4.0-pre7
- Last known good version: N/A
- IDE: VSMac 7.8.3
- Platform Target Frameworks: 
  - iOS:  12.1

### Screenshots

Incorrect layout - `CollectionView` inside `StackLayout`:

![Simulator Screen Shot - iPhone X - 2019-03-26 at 16 42 37](https://user-images.githubusercontent.com/8092460/55016460-b9376b00-4fe6-11e9-8dd5-1df9b16a96cb.png)

Correct layout - `CollectionView` as root element of `ContentPage`:

![Simulator Screen Shot - iPhone X - 2019-03-26 at 16 50 00](https://user-images.githubusercontent.com/8092460/55016848-7fb32f80-4fe7-11e9-8d05-729f85b0679e.png)

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3009267/Xaminals.zip)

**Comment by samhouts** [comment]
Pretty sure this was resolved by #5990. It is no longer an issue in pre10.
