### ISSUE TITLE
ListView System.NullReferenceException

### ISSUE THREAD

**Issue by Carbaholic** [xamarin/Xamarin.Forms#5700]
### Description

This only occurs on Android

I have a listview on a page in my app that is producing a System.NullReferenceException. This happens when its page is not at the top of the navigation stack. 

Stack trace: 

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at Xamarin.Forms.Platform.Android.ListViewRenderer+Container.OnMeasure (System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00032] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewRenderer.cs:513 
[MonoDroid]   at Android.Views.View.n_OnMeasure_II (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 widthMeasureSpec, System.Int32 heightMeasureSpec) [0x00009] in <3faca578033c421aa590cc3addd3b6d8>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.29(intptr,intptr,int,int)

### Steps to Reproduce

Narrowing this down to a repro; just wanted to get it up there.  

### Expected Behavior
I did not expect a null reference exception

### Actual Behavior
a null reference exception

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - Android: not sure how to answer this? I support multiple platforms and it seems to happen on all of them

### Reproduction Link

Working on it

**Comment by kingces95** [comment]
Please let us know when you have a zipped reproduction. Thanks.

**Comment by Carbaholic** [comment]
I'm having a hard time reproducing this; is there a way I could debug the xamarin.forms source code? Is there a verbose debugging option I can turn on to get more info?

**Comment by Carbaholic** [comment]
Haven't been able to reproduce so I'm looking at the source. this is the function that crashes: 

`			protected override void OnMeasure(int widthMeasureSpec, int heightMeasureSpec)
			{
				if (_child == null)
				{
					SetMeasuredDimension(0, 0);
					return;
				}

				VisualElement element = _child.Element;

				Context ctx = Context;

				var width = (int)ctx.FromPixels(MeasureSpecFactory.GetSize(widthMeasureSpec));

				SizeRequest request = _child.Element.Measure(width, double.PositiveInfinity, MeasureFlags.IncludeMargins);
				Xamarin.Forms.Layout.LayoutChildIntoBoundingRegion(_child.Element, new Rectangle(0, 0, width, request.Request.Height));

				int widthSpec = MeasureSpecFactory.MakeMeasureSpec((int)ctx.ToPixels(width), MeasureSpecMode.Exactly);
				int heightSpec = MeasureSpecFactory.MakeMeasureSpec((int)ctx.ToPixels(request.Request.Height), MeasureSpecMode.Exactly);

				_child.View.Measure(widthMeasureSpec, heightMeasureSpec);
				SetMeasuredDimension(widthSpec, heightSpec);
			}`

**Comment by kingces95** [comment]
The project is open source and has instructions per platform for how to build it. There is an unofficial bat file `.create-nuget` that you could use to build the nuget or just create ur own unit test. If u use the bat file, `set nuget_dir=` path to `nuget.exe`.

**Comment by Carbaholic** [comment]
I tried following the build tutorial but it's for windows and I'm on a mac. Is there a tutorial for building the nuget package with visual studio for mac?

**Comment by Carbaholic** [comment]
upgraded to the latest 4.0 release and the bug seems to have gone away.

**Comment by Carbaholic** [comment]
And it's back, I'll keep working on a repro

**Comment by samhouts** [comment]
Thanks, we'll keep watching for it. :)

**Comment by Carbaholic** [comment]
Still can't reproduce but I am narrowing it down.

This happens if the OnMeasure method is called on a listview on a page that has been popped from the navigation stack. I'm not sure why that method is called on a page that is no longer on the navigation stack. I even set the page to null after popping it and it the onMeasure method is still called.

**Comment by Carbaholic** [comment]
Changed from Navigation.remove to popping the page and the same problem persists.
