### ISSUE TITLE
 'InitializeComponent' does not exist in the current context

### ISSUE THREAD

**Issue by zhulin802** [xamarin/Xamarin.Forms#5701]
### Description
  I created a new project (Xamarin.Forms, blank, shared project) and run the application i got error code The name 'InitializeComponent' does not exist in the current context
### Steps to Reproduce
Run the project
### Expected Behavior
build succeed
### Actual Behavior
build fails and throw the error
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017 on Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
https://stackoverflow.com/questions/55198660/xamaria-form-initializecomponent-does-not-exist-in-this-context

**Comment by kingces95** [comment]
The template project is working for me. Please attach a zipped reproduction.

**Comment by samhouts** [comment]
@zhulin802  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
