### ISSUE TITLE
CarouselView.EmptyView not work

### ISSUE THREAD

**Issue by yelinzh** [xamarin/Xamarin.Forms#5702]
## Description
 I implemented the new carousel view of pre-release. It works fine excepted the CarouselView.EmptyView. I'd like to show a label or something else when carousel view is empty.But it doesn't work.
```
<CarouselView ...>
     ...
    <CarouselView.EmptyView>
        <StackLayout>
            <Label Text="No people exist!"/>
        </StackLayout>
    </CarouselView.EmptyView>
    ...
</CarouselView>
```

## Expected Behavior
I'd like to show a label or something else when carousel view is empty.

## Actual Behavior
CarouselView.EmptyView doesn't work.

## Basic Information
<ur>
<li>Version with issue: 4.0.0.8055-pre1</li>
<li>IDE: VS 15.9.9</li>
<ur>

**Comment by kingces95** [comment]
Could you please attach a zip of your reproduction? Thanks.

**Comment by samhouts** [comment]
@yelinzh CarouselView is in very early preview and is not fully implemented yet. Please follow #5044 for updates. Thanks!
