### ISSUE TITLE
Android EditText Ellipsize not working

### ISSUE THREAD

**Issue by pieterlr** [xamarin/Xamarin.Forms#5703]
### Description
I have a picker with an item that has text too long for the picker control. I would like this to ellipse at the end. However when I set Control.Ellipsize = TruncateAt.End; in the renderer, the ellipse does not display.

Please find attached a test app.

### Steps to Reproduce

1. Select the first option in the picker (an item with text longer than the control)

### Expected Behavior
Ellipse is added at the end of the line in the picker control.

### Actual Behavior
The text is just cut off - no ellipse.

### Basic Information

- Version with issue: Xamarin 3.4.0.109*
- IDE: Visual Studio 2017 Pro
- Platform Target Frameworks: 
  - Android: Min Api 21, target 27

### Screenshots
![image](https://user-images.githubusercontent.com/13809018/55062571-e8012000-507e-11e9-952f-0d6de2d00729.png)

### Test App
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3012306/App1.zip)

**Comment by kingces95** [comment]
Doesn't ellipse. Doesn't load on iOS.

**Comment by hartez** [comment]
You can accomplish this by changing your renderer's OnElementChanged override from 

```
protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
{
    base.OnElementChanged(e);

    Control.SetMaxLines(1);
    Control.SetLines(1);
    Control.Ellipsize = TruncateAt.End;
    Control.SetSingleLine(true);
}
```

to

```
protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
{
    base.OnElementChanged(e);

    Control.KeyListener = null;            
    Control.Ellipsize = TruncateAt.End;
}
```

The only downside is that you won't be able to select/copy the text in the Picker's EditText.

**Comment by amirvenus** [comment]
> 

Is there any other solution that does not have that downside, @hartez ?
