### ISSUE TITLE
[Shell] SearchHandler BindingContext not inherited from page

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5705]
### Description

I know how to use the `SearchHandler` built into Shell (sub-class, override `OnQueryChanged` etc.). However, `SearchHandler` also supports commanding, which should permit the usage scenario of binding to ViewModel properties. While I can bind to a ViewModel ICommand, this is only possible if I set the `SearchHandler.BindingContext` directly. Leaving the BindingContext unset results in the Command binding not resolving. I'd expect the SearchHandler to inherit the BindingContext from the page it's on.

`FilterCommand` unresolved:

```
    <Shell.SearchHandler>
        <SearchHandler x:Name="searchHandler"
                       Placeholder="Enter search term"
                       Command="{Binding FilterCommand}"
                       CommandParameter="{Binding Source={x:Reference searchHandler}, Path=Query}" />
    </Shell.SearchHandler>
```

`FilterCommand` resolved:
```
    <Shell.SearchHandler>
        <SearchHandler x:Name="searchHandler"
                       Placeholder="Enter search term"
                       BindingContext="{Binding Source={x:Reference self}, Path=BindingContext}"
                       Command="{Binding FilterCommand}"
                       CommandParameter="{Binding Source={x:Reference searchHandler}, Path=Query}" />
    </Shell.SearchHandler>
```
### Steps to Reproduce

1. Run the attached sample.
2. Browse to the Bears page (bottom tab).
3. Enter a search term in the SearchHandler and hit return.

### Expected Behavior

BearsViewModel.FilterCommand is resolved, and the FilterItems method gets executed.

### Actual Behavior

BearsViewModel.FilterCommand remains unresolved.

### Basic Information

- Version with issue: 4.0-pre7
- Last known good version: N/A
- IDE: VSMac 7.8.3

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3012825/Xaminals.zip)

**Comment by pavanalluri007** [comment]
@davidbritch  is there a way to acheive the same functionality on keyup ?
