### ISSUE TITLE
[Shell] SearchHandler.Query property value isn't passed via CommandParameter

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5706]
### Description

The Shell spec says that the `SearchHandler.Query` property is "The current string in the search box.". When examining this property in an OnQueryChanged override, it's correctly set.

However, I'd like to pass the Query property value as the CommandParameter, to an ICommand in my ViewModel, to implement searching there. However, a null value is always passed:

```
    <Shell.SearchHandler>
        <SearchHandler x:Name="searchHandler"
                       Placeholder="Enter search term"
                       BindingContext="{Binding Source={x:Reference self}, Path=BindingContext}"
                       Command="{Binding FilterCommand}"
                       CommandParameter="{Binding Source={x:Reference searchHandler}, Path=Query}" />
    </Shell.SearchHandler>
```

Note: Obviously I'd need to bind the ItemsSource property to see some results.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the Bears page (bottom tab).
3. Enter a search term (and hit return).

### Expected Behavior

BearsViewModel.FilterItems() should receive the value of the Query property, as an argument.

### Actual Behavior

BearsViewModel.FilterItems() receive a null value as an argument.

### Basic Information

- Version with issue: 4.0-pre7
- Last known good version: N/A
- IDE: VSMac 7.8.3

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3012891/Xaminals.zip)

**Comment by StephaneDelcroix** [comment]
🤦‍♂️ CommandParameterProperty default binding mode is onetime. you can fix your sample by setting `Mode=OneWay`

I'm still gonna change all it to OneWay
