### ISSUE TITLE
[Shell] MenuItem BindingContext not inherited from Shell

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5707]
### Description

My Shell file contains a MenuItem that executes an ICommand. However, despite the BindingContext being set in the code-behind, HelpCommand isn't resolved:

```
    <Shell.MenuItems>
        <MenuItem Text="Help"
                  Icon="help.png"
                  Command="{Binding HelpCommand}"
                  CommandParameter="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell" />
    </Shell.MenuItems>
```

However, if I set the MenuItem.BindingContext property manually, HelpCommand is resolved:

```
    <Shell.MenuItems>
        <MenuItem Text="Help"
                  Icon="help.png"
                  BindingContext="{x:Reference self}"
                  Command="{Binding HelpCommand}"
                  CommandParameter="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell" />
    </Shell.MenuItems>
```
### Steps to Reproduce

1. Run the attached sample.
2. Expose the flyout.
3. Click Help.

### Expected Behavior

HelpCommand, in AppShell.xaml.cs is executed.

### Actual Behavior

HelpCommand, in AppShell.xaml.cs, isn't executed (unless the BindingContext is set manually on the MenuItem).

### Basic Information

- Version with issue: 4.0-pre7
- Last known good version: N/A
- IDE: VSMac 7.8.3

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3012915/Xaminals.zip)

**Comment by kingces95** [comment]
Reproduces as described

**Comment by samhouts** [comment]
still an issue in pre10

**Comment by spelltwister** [comment]
This is still an issue for me.  I'm using Xamarin.Forms package 4.5.0.617.  Setting the binding context in constructor did not work, but doing it in the xaml does.
// does not work
public AppShell()
{
            InitializeComponent();
            this.BindingContext = this;
}
// does work
    <MenuItem Text="Logout"
              BindingContext="{Binding Source={RelativeSource Self}}"
              Command="{Binding ExecuteLogout}" />

The {x:Reference Self} also did **not** work from the above repro steps.

**Comment by Heshanp** [comment]
Seems this issue is back again. XF version 4.5.0.617.
**AppShell.xaml**
<MenuItem Text="Privacy policy"  Command="{Binding AboutCommand}" />

**AppShell.xaml.cs**

**public static ICommand AboutCommand => new Command (ShowAbout);**

public AppShell()
        {
            InitializeComponent();
            RegisterRoutes();
            **BindingContext = this;**
        }
Menu item does not resolve the command.

**Comment by kencherasaro** [comment]
In the XAML definition x:Name="Shell", and in the MenuItem definition BindingContext="{x:Reference Shell}".  This worked for me.

**Comment by balintn22** [comment]
I'm on Xamarin forms 5, VS 2020.
For me the method from [Heshanp](https://github.com/Heshanp) worked/ish: set BindingContext from codebehind constructor.

However, when I click the menuitem, the flyout remains open. Looks kinda funny, with the target page (after navigation from the menuitme tap) showing up behind...
