### ISSUE TITLE
OnIdiom returns Phone instead of Tablet on Android 9 tablet (x86)

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#5708]
### Description

When I use OnIdiom to detect Tablet from Phone I get an unexpected behavior on Android tablet. It gets detected as Phone:

### Steps to Reproduce

Inser this code in XAML page:

```
<Label>
    <Label.Text>
        <OnIdiom x:TypeArguments="x:String">
            <OnIdiom.Phone>Hello from a phone app</OnIdiom.Phone>
            <OnIdiom.Tablet>Hello from a tablet app</OnIdiom.Tablet>
            <OnIdiom.Desktop>Hello from a desktop app</OnIdiom.Desktop>
          </OnIdiom>
    </Label.Text>
</Label>
```

### Expected Behavior

I see "Hello from a tablet app"

### Actual Behavior

I see "Hello from a phone app"

![image](https://user-images.githubusercontent.com/8274816/55076105-dcb8ef00-5094-11e9-8538-e4b8eae99012.png)

### Basic Information

- Version with issue: 3.6.0.264807 (3.6.0 Service Release 1)
- Last known good version: n/a
- IDE: VS2017 15.9.10
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 8.1
  - UWP:  n/a
- Android Support Library Version: 4.28.0.0.1
- Nuget Packages: 3.6.0.264807 
- Affected Devices: Toshiba Encore 8 (8" Intel Baytrail Tablet sold with Windows 8.1, upgraded to Windows 10 and dual booted Android 9 x86 Pie (Bliss x86, Patch Level 2019-03-05)

### Screenshots

![image](https://user-images.githubusercontent.com/8274816/55076323-6963ad00-5095-11e9-8968-e2a57de36a8e.png)

### Reproduction Link

add XAML code from above to a new project and run app on Android Tablet.

**Comment by MagicAndre1981** [comment]
In Xamarin.Forms.Platform.Android\Forms.cs I see this:

```
int minWidthDp = activity.Resources.Configuration.SmallestScreenWidthDp;
Device.SetIdiom(minWidthDp >= TabletCrossover ? TargetIdiom.Tablet : TargetIdiom.Phone);
```

What is this `SmallestScreenWidthDp` ?

**Comment by MagicAndre1981** [comment]
ok, [Xamarin.Essentials also had the issue](https://github.com/xamarin/Essentials/issues/668) and [fixed it](https://github.com/xamarin/Essentials/pull/670).

Should we use Xamarin.Essentials now for detection? or will this code be synced?

**Comment by kingces95** [comment]
There's not hard and fast rule about what is a phone vs a tablet. So there will always be heuristic logic involved. So if Essentials works for, you go with that. If we change this now, then our huristic may break those for whom it's working.

**Comment by MagicAndre1981** [comment]
@kingces95 Essentials also shows phone.
