### ISSUE TITLE
Layout issue with Entry

### ISSUE THREAD

**Issue by divi1411** [xamarin/Xamarin.Forms#5711]
### Description
We are creating a custom control which has a hierarchy TemplatedView --> StackLayout --> Grid --> Entry. We are adding a row with height zero above the row (Auto height) with Entry. While doing this, the height of the custom view is not rendered properly when the Entry is added with text in load time. Hence to avoid this, we are setting string.Empty for Entry text in OnElementChanged() and updating the actual text and setting padding for native TextBox in TextBox loaded event in custom renderer. 

When this custom view is added as “FlexLayout --> ScrollView --> Grid --> CustomTemplatedView”, Entry text not displayed in UWP until we resize the window.

### Expected Behavior

Entry text should be displayed

### Screenshots

https://github.com/divi1411/TextInputLayout/raw/master/Screenshot/Screenshot.png

### Reproduction Link

https://github.com/divi1411/TextInputLayout.git

**Comment by Iyyappanmani** [comment]
Hi @samhouts @XamarinQA 

Any update on this issue.

**Comment by divi1411** [comment]
Hi @samhouts ,
Any update on this issue?

**Comment by samhouts** [comment]
@divi1411 This is on the backlog. I don't currently have an estimate of when we may begin work on this item. Thank you for your patience!
