### ISSUE TITLE
[Enhancement] Add Scrolled event to CollectionView

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#5716]
## Description
CollectionView aims to be more flexible by provide us the ability to know when CollectionView has been scrolled.

Many people have been asking for such an event, and a quick web search for 'xamarin forms listview scroll event' shows it. to make parallax headers, make some views dis/appearing when scroll up/down or other stuff using the scroll event.

### API Event
| API | Description |
| ------------- | ------------- |
| Scrolled  | Occurs when user interact with the CollectionView|

## Implementation
this is exact same signature of ScrollView.Scrolled event .

```public event EventHandler<Xamarin.Forms.ScrolledEventArgs> Scrolled;```

## Backward Compatibility
New feature, so it does not have any impact.

## Difficulty
Hmmm...
CollectionView inherit from ScrollView, it should not be a big deal.

**Comment by adrianknight89** [comment]
Not sure if the native views allows this due to inherit virtualization, but it'd be great to report some kind of distance delta when scrolling occurs so we can scroll other views (like a header view) according to that delta.

**Comment by adrianknight89** [comment]
#5754 adds a `RecyclerViewScrollListener` to Android's `ItemsViewRenderer` and can be used to send scroll events.

**Comment by adrianknight89** [comment]
#4654

**Comment by Phenek** [comment]
It would be awesome if the ScrolledEventArgs,
could provide us some GestureStatus Similar to PanUpdatedEventArgs.StatusType Property

```public enum GestureStatus``` 

| Enum | Int |Description|
| ------------- | ------------- |------------- |
|Canceled | 3 | The gesture was canceled|
|Completed | 2 | The gesture completed|
|Running | 1 | The gesture is still being recognized|
|Started | 0 | The gesture started|

**Comment by adrianknight89** [comment]
@Phenek We might need to create a different event for this. `ScrolledEventArgs` is getting crowded with multiple properties already and provides numerical data. State data can be provided by another event, in my opinion.

**Comment by jfversluis** [comment]
With merging #5754 I’m going to close this for now. The basic `Scrolled` event is there, if there is anything you are still missing please open a new issue with the specific information for that. And let us know what you think of the current implementation when it’s released, thanks!

**Comment by EmilAlipiev** [comment]
is there already anything related to ScrollState here? or should we create another issue? 

we need to have something like ScrollStateChanged with ScrollStateChangedEventArgs 
which has ScrollState with Fling, Idle, Cancelled, Completed etc.

**Comment by Phenek** [comment]
@EmilAlipiev look here #11059
