### ISSUE TITLE
[Enhancement] Add additional documentation to Material to help 3rd party libraries know what to expect from renderers

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5718]
## Summary
Material visual changes a lot of control types and the Android Context itself. Having a single place where people can see the difference between the base controls and the material controls when using material renderers would be very helpful. 

For example on Android the Context gets wrapped with a ContextThemeWrapper so if a 3rd party library has just assumed that the Context == Activity it will crash when using Material Visual

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
