### ISSUE TITLE
Selectable CollectionView iOS bug if content template contain frame

### ISSUE THREAD

**Issue by Moltroon** [xamarin/Xamarin.Forms#5719]
### Description
On iOS, you can't select an element if is in a Frame in a CollectionView. You need to select the margin to select the element.

### Steps to Reproduce

1. test on android and iOS my example

### Expected Behavior
Clic on an element select this.

### Actual Behavior
You need to click on the margin of the element too select him.

### Basic Information

- Version with issue: 4.0 pre7
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: no error

### Reproduction Link

[SelectedCollectionItemBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3014129/SelectedCollectionItemBug.zip)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/55270699-3f9db800-5246-11e9-8968-4942d9a59160.png)
Hm, throws on launch. App looks reasonable. Other iOS apps launched today... so...

**Comment by samhouts** [comment]
That error was #5677.

**Comment by samhouts** [comment]
@Moltroon I updated your sample from pre7 to pre8 to resolve the error message that @kingces saw. I am able to tap anywhere within the element, and it selects the row. Can you please confirm that you're still experiencing this issue? Perhaps it was fixed in pre8. Thanks!

**Comment by Moltroon** [comment]
I can't test for the moment. I need an FFImage update for pre8 compatibility in my principal project. 
I trust you. Otherwise, I would restart the ticket.
