### ISSUE TITLE
[CollectionView] Functionality issues on iOS when using certain layout(s)

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#5721]
_Cross-reference from a [PR](https://github.com/pauldipietro/CollectionViewChallenge/pull/1) on the CollectionView Challenge_

(Bug title can be refined as needed; this is just to get a report filed)

### Description
Using the layout provided on the PR/feedback, scrolling with the CollectionView on iOS is corrupted and some blank spacing occurs.

### Steps to Reproduce

1. Run the fork from @bcaceiro at https://github.com/bcaceiro/CollectionViewChallenge
2. Observe the CollectionView when scrolling

### Expected Behavior
Corruption/spacing doesn't occur and functions as it should, much like on Android

### Actual Behavior
The aforementioned behavior occurs.

### Basic Information

- Version with issue: 4.0.0-pre7

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/2139254/55024243-5f3ea180-4ff6-11e9-8e80-2aa4ffc4500a.png)
![Screenshot2](https://user-images.githubusercontent.com/2139254/55024480-d96f2600-4ff6-11e9-8cc8-7fa8e44fc399.png)

### Reproduction Link

https://github.com/bcaceiro/CollectionViewChallenge

**Comment by b-straub** [comment]
I can not see this issue fixed by commit 583be22d5ce7dc9a6b980adb8fec8b9077a7a314.
Using 4.0.1.383393-nightly this issue persists. Did I miss something? 
From my experience UICollectionView self sizing cells are a nightmare. For UIListView those can be made working well using autolayout and constraints only.
