### ISSUE TITLE
XF 3.6 Cast Error onFocus Android

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#5725]
X.F 3.6, tried on both NuGet 3.6 and the latest build from GitHub built locally. 
Log attached **Android only**

### Description

**Android only**

1. Add a {Bound} Entry to a page with text in the model.
2. Entry renders fine
3. Tap into the control 
4. OnFocus throws Invalid Cast error on at :

_Xamarin.Forms.Platform.Android.ViewRenderer`2[TView,TNativeView].Android.Views.View.IOnFocusChangeListener.OnFocusChange (Android.Views.View v, System.Boolean hasFocus) [0x0006c] in D:\a\1\s\Xamarin.Forms.Platform.Android\ViewRenderer.cs:111_ 

 

### Expected Behavior
Not Crash
### Actual Behavior
Crash

### Basic Information

- IDE: VS 2017

  - Android: 9

[Xamarin.Forms.Material.Android.MaterialFormsTextInputLayoutBase.OnFocusChange.txt](https://github.com/xamarin/Xamarin.Forms/files/3015335/Xamarin.Forms.Material.Android.MaterialFormsTextInputLayoutBase.OnFocusChange.txt)

**Comment by PureWeen** [comment]
@ianvink this should be fixed with the next SR of 3.6

Just to make sure I'm testing your scenario correctly this is how I tested


```XAML
<ContentPage.Content>
        <StackLayout>
            <Entry Text="{Binding EntryText, Mode=TwoWay}"  />
        </StackLayout>
    </ContentPage.Content>
```

```C#
	public partial class App
	{
		void InitializeMainPage()
		{
			MainPage = new MainPage();
			MainPage.BindingContext = new Model();
		}
	}

	public class Model
	{
		public string EntryText { get; set; } = "I am some text";
	}
```

**Comment by ianvink** [comment]
I have a repo, I need an email to send it to as it is confidential

**Comment by antborari** [comment]
Excuse me, now I have the same problem. I have one Editor and when I do Onfocus outside Editor throws an exception. Send me with the solution please.. to abaristu@gmail.com
