### ISSUE TITLE
ListView RefreshControlColor initial

### ISSUE THREAD

**Issue by Suplanus** [xamarin/Xamarin.Forms#5728]
### Description
The initial color of ListView RefreshControlColor on loading first time is not the set color.

### Steps to Reproduce
i set the global color for this ActivityIndicators in App.xaml:

```xml
<Style TargetType="ListView">
    <Setter Property="RefreshControlColor" Value="{StaticResource NavigationPrimary}" />
</Style>

<Style TargetType="ActivityIndicator">
    <Setter Property="Color" Value="{StaticResource NavigationPrimary}" />
</Style>
```

### Expected Behavior
The color should be shown on first loading.

### Actual Behavior
A default color is visible at first loading.

### Basic Information

- Version with issue: 3.6.0
- Last known good version: -
- IDE: VS for Mac & Windows
- Platform Target Frameworks:
  - Tested on iOS: 11.1

### Screenshots

Inital loading:
![1](https://user-images.githubusercontent.com/2002916/55146258-80ada380-5144-11e9-808a-373730a921f2.jpg)

Refresh from user (pull to refresh):
![2](https://user-images.githubusercontent.com/2002916/55146265-830ffd80-5144-11e9-97ac-02dd137f0b32.jpg)

### Reproduction Link

In the forum i [posted](https://forums.xamarin.com/discussion/comment/368887#Comment_368887) a project to reproduce.

**Comment by kingces95** [comment]
Sorry, I don't find the string `{StaticResource NavigationPrimary}` in the project. Could you zip and attach the project to the issue? The linked repro has a blue indicator that stays blue.

**Comment by Suplanus** [comment]
`{StaticResource NavigationPrimary}` is in `App.xaml` Line `6`.
I attached the project and a video where you can see it. I made the color red for the video.
- [ListViewBusyIndicator_Video.zip](https://github.com/xamarin/Xamarin.Forms/files/3028008/ListViewBusyIndicator_Video.zip)
- [ListViewBusyIndicator.zip](https://github.com/xamarin/Xamarin.Forms/files/3028004/ListViewBusyIndicator.zip)

**Comment by brminnick** [comment]
@samhouts Here's another reproduction sample:

https://github.com/brminnick/PullToRefreshColorRepro

![](https://user-images.githubusercontent.com/13558917/56069815-a12b4f80-5d39-11e9-94b5-8998bde4d78b.gif)

**Comment by alanag13** [comment]
This is actually a long-standing bug in iOS and is demonstrated in these:
https://github.com/davbeck/RefreshTintFail/
https://github.com/uruly/RefreshControlTintColorDemo
