### ISSUE TITLE
InvalidOperationException when using PushAsync

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#5731]
Hi,

I am using Syncfusion TabView on my MainPage.

in my App starting the page like this:

`MainPage = new NavigationPage(new MainPage());`

then from the MainPage I am opening Signin as Popup like this:

`Navigation.PushModalAsync(new Signin());`

Until here all ok...

However, on the Sign in page I have a button to go to Sign up and I am trying to open the Sign up like this:

`Navigation.PushAsync(new NavigationPage(new Signup()));`

or like this:

`Navigation.PushModalAsync(new Signup());`

but keep getting this error:

> Unhandled Exception:
> 
> System.InvalidOperationException: <Timeout exceeded getting exception details> occurred
> 
>

**Comment by kingces95** [comment]
Could you please zip and attach a small reproduction to the bug? Thanks!

**Comment by samhouts** [comment]
@jrahma  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
