### ISSUE TITLE
[iOS] Unable to build Xamarin.Forms solution

### ISSUE THREAD

**Issue by ghost** [xamarin/Xamarin.Forms#5738]
I'd like to take a look at the source code and submit a PR, but I'm having difficulty building ControlGallery.iOS.

I'm confused that VS is comparing .net 4.7 to xamarinios10. Seems like a comparison of apples and oranges. How do I get rid of this issue?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\m\Xamarin.Forms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win-x64. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\m\Xamarin.Forms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7). Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\m\Xamarin.Forms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win-x86. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\m\Xamarin.Forms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1
```

**Comment by kingces95** [comment]
Hm, I've not seen that. That's gonna be hard to debug as it's hard to reproduce your build env locally. I'd google and see what you can find and maybe try different VS versions. That said, we do need to better isolate our build env so users who want to submit PRs encounter less friction.

**Comment by puppetSpace** [comment]
I got the same errors.
Using visual studio 2019 RC 4.

I would also like to start contributing, but these errors are stopping me from even building something

**Comment by samhouts** [comment]
@scxp @puppetSpace That error message is really more of a warning. You should be able to build anyway. Make sure you've cleaned your solution, deleted bin/obj folders, and set your errors to just Build Only, not Build+Intellisense.

**Comment by adrianknight89** [comment]
I saw this same issue last night after clean installing Windows 10 + VS 2019. I'll try @samhouts's suggestion today.

**Comment by adrianknight89** [comment]
@samhouts Setting errors to `Build Only` seems to get rid of (or at least hide ) the issues reported here, but I'm seeing another one. Looks like all of `Xamarin.Forms.Material.[Platform]` dlls are missing. Do you know how to re-create them?

**Comment by samhouts** [comment]
@PureWeen Something to be aware of ^^

**Comment by PureWeen** [comment]
@adrianknight89  what am I missing? Those are part of the SLN

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.sln#L183

I did a twitch stream this morning where I pulled a fresh copy and opened with VS 2019 stable
https://www.twitch.tv/videos/406524117?t=00h15m32s

You'll see in the stream I have all the same errors listed and I'm able to run everything

I didn't have to do anything special for it to run.
What am I missing?

**Comment by puppetSpace** [comment]
> @scxp @puppetSpace That error message is really more of a warning. You should be able to build anyway. Make sure you've cleaned your solution, deleted bin/obj folders, and set your errors to just Build Only, not Build+Intellisense.

Worked for me. Thx.

**Comment by puppetSpace** [comment]
@adrianknight89 I had the same issue. The projects were in the folder, but not in de solution. Then I saw that I had opened ".Xamarin.Forms.sln" and not "Xamarin.Forms.sln" (without the dot). Then everything worked fine.

**Comment by adrianknight89** [comment]
@puppetSpace Good catch! I'd opened the same sln as well, so I'm guessing I had the same problem.

**Comment by PureWeen** [comment]
@kingces95 do you/we still use the *.Xamarin.Forms.sln* variations?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
