### ISSUE TITLE
MessageCenter lead to an error of DisplayAlert

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#5741]
### Description
I want to show a alert in a page and write code:
`await DisplayAlert('title','my message','OK');`
It crashed with :Specified cast is not valid
I guess it because there is a MessageCenter in my page.

### Expected Behavior
Is it a bug?

- Version with issue:The very new version of preview.
- Last known good version:
- IDE:Visual Studio for Mac Community 8.0 build 2972

**Comment by kingces95** [comment]
Could you please zip up and attach a small reproduction? Thanks!

**Comment by samhouts** [comment]
@mcguu  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
