### ISSUE TITLE
[Shell] Navigation - events vs overrides

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5745]
### Description

`Shell` has `Navigating` and `Navigated` events, to which event handlers can be set. It also has `OnNavigating` and `OnNavigated` overrides. Are both required?

**Comment by jfversluis** [comment]
Yes.

**Comment by jfversluis** [comment]
Maybe?

**Comment by jfversluis** [comment]
Who knows! But we won't be changing this for Forms. Thanks Dave! 😄
