### ISSUE TITLE
[Shell, iOS] Layout issue when navigating from page with top & bottom tabs

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5746]
### Description

There's a layout issue when navigating from a page that has top & bottom tabs, to another page. It looks like the space from the top tab bar is still reserved.

Note: this issue is only on iOS. Android is fine.

### Steps to Reproduce

1. Run the attached sample, on iOS.
2. On the Cats page, open the Flyout and click the Random menu item. A random page will be navigated to. 

### Expected Behavior

The random page is navigated to, and laid out without the additional space at the top of the page.

### Actual Behavior

The random page is navigated to, but has additional space at the top of the page (as if the space from the top tab bar is still reserved).

### Basic Information

- Version with issue: 4.0-pre7
- Last known good version: N/A
- IDE: VSMac 7.8.3
- Platform Target Frameworks: 
  - iOS:  12.1

### Screenshots

Here's the page with bad layout, as per the scenario above:

![Simulator Screen Shot - iPhone X - 2019-03-29 at 09 40 20](https://user-images.githubusercontent.com/8092460/55223995-625cac00-5207-11e9-95b2-96179894da1a.png)

Here's the same page, when navigated to from the Elephants page:

![Simulator Screen Shot - iPhone X - 2019-03-29 at 09 44 22](https://user-images.githubusercontent.com/8092460/55224015-6be61400-5207-11e9-92dd-804fb21897b0.png)

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3021998/Xaminals.zip)

**Comment by kingces95** [comment]
Extra space.

**Comment by samhouts** [comment]
this is no longer an issue in pre10 🎉
