### ISSUE TITLE
Disable horizontal scroll in the custom listview in android

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#5749]
### Description
We have created custom listview with horizontal scroll and try to stop scrollview view scrolling by using the scrollView.IsEnabled property. But it does not work for android.

You have internally give support to implement the custom horizontal scroll.

**ScrollViewRenderer --> AHorizontalScrollView**

In the AHorizontalScrollView file you have override the OnTouch method as per the scroll view renderer. but wont handle the parent scrollview property (InputTransparent, IsEnabled).

But you have included the same in the ScrollViewRenderer.

So, Can you please include those changes in the AHorizontalScrollView also which would helpful for us. 

 Please find the code reference below ::

OnInterceptTouchEvent 
`public override bool OnInterceptTouchEvent(MotionEvent ev)

        {

            if (_renderer.Element.InputTransparent)

                return false;
        }`

OnTouchEvent.
`public override bool OnTouchEvent(MotionEvent ev)

        {

            if (!_renderer.Element.IsEnabled)

                return false;
        }`

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
Could you please zip and attach a small reproduction to the issue? Thanks!

**Comment by RawoofSharief** [comment]
I have attached the simple SfListView sample and AHorizontalScrollView.cs file. Kindly merge the changes in your source.
[DisableScrollIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3052708/DisableScrollIssue.zip)

**Comment by techduggu** [comment]
I'd like to take this up. Currently analyzing it to create specification and then will raise a PR.

**Comment by techduggu** [comment]
@RawoofSharief Can you share the reproduction of this issue without using Syncfusion ListView control? I'd like to fix this issue but for unit testing purpose, I'd need a custom listview with horizontal scroll. Thanks!

**Comment by techduggu** [comment]
@RawoofSharief Never mind. It took a while for me to understand your SF control and I've created a similar control (custom ListView with horizontal scroll) for unit testing purpose of this issue. The test results are positive so far and I will be raising a PR soon.
