### ISSUE TITLE
Custom Font Throws Error When Viewing Xaml Preview on Android

### ISSUE THREAD

**Issue by kspearrin** [xamarin/Xamarin.Forms#5751]
### Description

Original issues that were all closed for some reason:

- https://bugzilla.xamarin.com/show_bug.cgi?id=57417
- https://github.com/xamarin/Xamarin.Forms/issues/3687
- PR with fix: https://github.com/xamarin/Xamarin.Forms/pull/3767

The problem remains.

### Steps to Reproduce

1. Use a custom font
2. Try Xaml preview for android

### Expected Behavior

No error

### Actual Behavior

Fails to render with null reference exception

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: unknown
- IDE: VS 2017 15.9.10
- Platform Target Frameworks:
  - Android: 9
- Android Support Library Version: 28
- Nuget Packages: Forms 3.6.0.264807
- Affected Devices: Android

### Screenshots

![image](https://user-images.githubusercontent.com/1190944/55236009-4d7f1900-5205-11e9-9d6d-3e8ee0692866.png)

![image](https://user-images.githubusercontent.com/1190944/55236051-6a1b5100-5205-11e9-9344-57a62a1f986e.png)

### Reproduction Link

See original issues

> VS bug [#832383](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/832383)

**Comment by garuma** [comment]
@kspearrin hey Kyle, we fixed this issue a different way in the end, for it to work you need to use the newly released Visual Studio 2019.
