### ISSUE TITLE
Previewer is using dark theme

### ISSUE THREAD

**Issue by kspearrin** [xamarin/Xamarin.Forms#5752]
### Description

Same issue that was covered in the forums here:
https://forums.xamarin.com/discussion/126436/previewer-background-colour-or-style-setting

> Hi, when I use the Xamarin Forms Previewer in Visual Studio 2017 (15.6.7) my app is shown in 'dark' mode or style i.e. has a black background, text is white (or light gray) yet when I run the app on my phone again using VS the background is white, text dark.
>
> Is there some setting I need to change to make the previewer the same as my phone?
>
> Note this is the Android preview.

Says it was fixed in 15.8. The problem remains in 15.9.10.

### Steps to Reproduce

1. View page in forms previewer

### Expected Behavior

Use a light colored theme like when deloying the app to an actual device.

### Actual Behavior

Observe dark background, white text, etc

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: unknown
- IDE: VS 2017 15.9.10
- Platform Target Frameworks:
  - Android: 9
- Android Support Library Version: 28
- Nuget Packages: Forms 3.6.0.264807
- Affected Devices: Android

### Screenshots

![image](https://user-images.githubusercontent.com/1190944/55238077-fe87b280-5209-11e9-834f-7751e303b495.png)

> VS bug [#832395](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/832395)

**Comment by drewgillies** [comment]
This is fixed in 16.0.
