### ISSUE TITLE
[Frame, CollectionView, Android]The Label.Text is invisible on Android if DataTemplate have frame as layout

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5765]
### Description
I have developed a xaml page for an app. It have CollectionView. When I have Frame as Layout in DataTemplate of CollectionView The Label.Text field on Android is invisible. Whereas when I put the Frame in StackLayout the Text becomes visible.
### Steps to Reproduce
Remove the parent StackLayout  from child FrameLayout in CollectionView DataTemplate using my sample.

### Basic Information

- Version with issue:Xamarin.Forms- pre7
- IDE:VSMac 2019 preview

- Affected Devices: Android

### Reproduction Link

[MyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3025610/MyApp.zip)

**Comment by assanesuzy** [comment]
This is still not working on iOS
