### ISSUE TITLE
Compiled bindings can cause (handled) NullReferenceExceptions

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#5770]
### Description

Compiled bindings should check for null members instead of dereferencing them, throwing exceptions, then handling those exceptions. I can't imagine that improves perf vs. a codepath that doesn't throw exceptions.

### Steps to Reproduce

1. Set up a binding against a member of a member. E.g. `<Label TextColor="{Binding MyContentViewModel.TextColor}"  Text="{Binding MyContentViewModel.Text}" />`
2. Assign that member using another binding. E.g. `<local:MyContentView MyContentViewModel="{Binding MainContentViewModel}" />`
3. Enable compiled bindings. E.g.  `x:DataType="local:MyContentView"`

### Expected Behavior

Compiled bindings should not throw exceptions during initialization, just like non-compiled bindings.

### Actual Behavior

NullReferenceExceptions are thrown (and handled) during page initialization, which is extremely annoying when running an app in the debugger.

```
>	0x0 in XamarinFormsSample.ContentViewModel.get_TextColor at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample\MainPage.xaml.cs:35,34	C#
 	0x24 in XamarinFormsSample.MyContentView.<InitializeComponent>typedBindingsM__3	C#
 	0x81 in Xamarin.Forms.Internals.TypedBinding<XamarinFormsSample.MyContentView,Xamarin.Forms.Color>.ApplyCore at D:\a\1\s\Xamarin.Forms.Core\TypedBinding.cs:208,7	C#
 	0x5D in Xamarin.Forms.Internals.TypedBinding<XamarinFormsSample.MyContentView,Xamarin.Forms.Color>.Apply at D:\a\1\s\Xamarin.Forms.Core\TypedBinding.cs:135,4	C#
 	0x51 in Xamarin.Forms.BindableObject.ApplyBindings at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:453,5	C#
 	0xA in Xamarin.Forms.BindableObject.BindingContextPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:472,4	C#
 	0x12E in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:624,5	C#
 	0x182 in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:422,5	C#
 	0x51 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:572,4	C#
 	0x5 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:122,4	C#
 	0x7 in Xamarin.Forms.BindableObject.set_BindingContext at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:26,10	C#
 	0x16 in XamarinFormsSample.MyContentView..ctor at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample\MyContentView.xaml.cs:20,13	C#
 	0x66 in XamarinFormsSample.MainPage.InitializeComponent at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample.Android\obj\Debug\81\MainPage.xaml.g.cs:23,9	C#
 	0x9 in XamarinFormsSample.MainPage..ctor at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample\MainPage.xaml.cs:21,13	C#
 	0x10 in XamarinFormsSample.App..ctor at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample\App.xaml.cs:14,13	C#
 	0x28 in XamarinFormsSample.Droid.MainActivity.OnCreate at C:\Users\mfeingol\source\Repos\XamarinFormsSample\XamarinFormsSample\XamarinFormsSample.Android\MainActivity.cs:23,13	C#
```

### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 8.1

### Reproduction Link

[XamarinFormsSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3027330/XamarinFormsSample.zip)

**Comment by StephaneDelcroix** [comment]
your sample is overly complex, but I get the idea.

same goes for KeyNotFoundEx, IndexOutOfRangeEx and ArgumentOutOfRangeEx when accessing indexers

**Comment by StephaneDelcroix** [comment]
it happens only on `TextColor`, not on `Text`, looks like a typical value vs reference type... in case of ref types, we check for null before dereferencing...

**Comment by StephaneDelcroix** [comment]
> same goes for KeyNotFoundEx, IndexOutOfRangeEx and ArgumentOutOfRangeEx when accessing indexers

forget this, there's no API to check if an indexer contains a value

**Comment by mfeingol** [comment]
> your sample is overly complex

Yeah, sorry about that. I was trying (unsuccessfully) to reproduce a different crash bug with compiled bindings and grouped listviews, and decided to file this one separately.

Thanks for fixing this!
