### ISSUE TITLE
Picker ItemSource can accept an Enum Object

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#5772]
### Description
Hello,

I have create an Enum Picker to used enum in pickers.
I don't understand why my first pick on the Picker not raised the property changed. In Xamarin.Forms 3.4 it working good.

I attach the example at this post.
### Steps to Reproduce

1. Use my example zip
2. Select just one time for they 2 picker
3. Standart picker have working but not my picker
4. Change version to 3.4 and it working

### Expected Behavior
TwoWay return the value to the ViewModel

### Actual Behavior
We need to select an element two time to have the value on the viewmodel

### Basic Information

- Version with issue: > 3.4
- Last known good version: 3.4
- IDE: Visual Studio 2017 Windows 
- Platform Target Frameworks:
  - iOS:  No test
  - Android: 7
  - UWP:  No test
- Android Support Library Version: 24
- Nuget Packages: cf. joined example
- Affected Devices: ASUS Zend tablet

### Reproduction Link
[TwoWayEnumPicker.zip](https://github.com/xamarin/Xamarin.Forms/files/3028304/TwoWayEnumPicker.zip)

Thanks

**Comment by kingces95** [comment]
Are you able to reproduce this without using a custom renderer. Custom renderers "void the warranty" so to speak. If not, could you explain the feature you'd like us to add so you wouldn't need to use a custom renderer?

**Comment by Moltroon** [comment]
Are you able to reproduce this without using a custom renderer? No.
My idea is to create a Picker in which an ItemSource can accept an Enum Object.

**Comment by kingces95** [comment]
Ah. Yes, that's a reasonable feature request! We'll file this as an enhancement. In the mean time, the work around is to marshal to and from the enum.. Instead of a custom renderer, if you are able to get the existing renderer to work, we'd be happy to review the PR -- that's often the fastest way to get features going.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
