### ISSUE TITLE
[iOS] Listview does not update background color properly

### ISSUE THREAD

**Issue by Xyotic** [xamarin/Xamarin.Forms#5777]
### Description
ListViews on iOS does not update its background color properly if is is populated with elements
It only changes the color  after all elements
### Steps to Reproduce

1.  Create ListView and populate with items
2.  Set the background color with a dynamic resource (BackgroundColor="{DynamicResource myDynamicColor}"
3. Update myDynamicColor while ListView is presented

### Expected Behavior
Changes background color of ListView like Android

### Actual Behavior
It only changes the color  after all elements

### Basic Information
- Version with issue: 3.6.0.264807

**Comment by samhouts** [comment]
@Xyotic Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@Xyotic  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by DDHSchmidt** [comment]
I vote to reopen this. Just confirmed on the latest 5.0 release that this bug is still alive and kicking :/

**Comment by lauxjpn** [comment]
This is still an issue. A viable workaround is to use a `SolidColorBrush` for the `Background` property, instead of a `Color` for the `BackgroundColor` property.
