### ISSUE TITLE
Scrollviews scroll to fixed point when clicked

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#5779]
We find that scrollviews often scroll to a fixed position when clicked/touched.

3.6.0.135200-pre1 and later are affected. 3.5.0.274416 are not.

This happens on UWP and iOS. Android untested.

Unfortunately we have not reduced this to a small repro yet.

Could anyone advise on what commits are in 3.6.0.135200-pre1 and not in 3.5.0.274416 so we can investigate?

**Comment by charlesroddie** [comment]
Thanks @samhouts 
This is a duplicate of https://github.com/xamarin/Xamarin.Forms/issues/5652.

**Comment by samhouts** [comment]
Duplicate of #5652
