### ISSUE TITLE
LineBreakMode does not work with FormattedText on Android

### ISSUE THREAD

**Issue by martelart** [xamarin/Xamarin.Forms#5780]
### Description
Label with FormattedText does not apply LineBreakMode, causes Java.Lang.IndexOutOfBoundsException
### Steps to Reproduce

1. Create Label
2. Add FormattedText with multiple Spans
3. Configure Attributes for Spans

### Expected Behavior
LineBreakMode works properly as it is on iOS 
e.g. text fits on a line properly with Tailtrunction
### Actual Behavior
Getting Exception 
### Basic Information

- Version with issue: 3.6.0.264807
- Last known good version: -
- IDE: Visual Studio Mac
- Platform Target Frameworks:
  - iOS:  12.2
  - Android: API 26

- Android Support Library Version: -

### Screenshots
-

### Reproduction Link
-

**Comment by samhouts** [comment]
[Issue5780.zip](https://github.com/xamarin/Xamarin.Forms/files/3075565/Issue5780.zip)
 I was unable to reproduce this issue. Can you please attach your test project or alter the attached project to demonstrate the issue? Thanks!

**Comment by scxp** [comment]
I remember getting IndexOutOfBoundsException when one of the spans had nothing but a newline though this issue might be different.

**Comment by martelart** [comment]
> [Issue5780.zip](https://github.com/xamarin/Xamarin.Forms/files/3075565/Issue5780.zip)
> I was unable to reproduce this issue. Can you please attach your test project or alter the attached project to demonstrate the issue? Thanks!

I get the Exception in a specific project, cant reproduce in other ones, this one also. I will continue to look for exact error. We can close issue.
