### ISSUE TITLE
[CollectionView,Frame] Margin on Frame is not respected in CollectionView

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#5782]
### Description
The Margin on Frame is not respected in CollectionView. This is when the Frame is the MainLayout of DataTemplate. If the Fame is put inside StackLayout the Margins are respected.

### Steps to Reproduce
Remove parent StackLayout from Frame in CollectionView DataTemplate from the repro project. 

### Basic Information

- Version with issue: Xamarin.Forms-pre7
- IDE:Visual Studio for Mac 2019 preview

- Affected Devices:iOS and Android

### Reproduction Link

[MyApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3033578/MyApp.zip)

**Comment by samhouts** [comment]
I think this is likely an issue with Frame, not CollectionView specifically. See related issue: https://developercommunity.visualstudio.com/content/problem/516733/frame-inside-a-bindablelayout-does-not-handle-marg.html

**Comment by HobDev** [comment]
Pehaps it may be the same issue. But isn't it belongs to Xamarin.Forms and not to the Visual studio?

**Comment by samhouts** [comment]
It does; you reported it in the correct place. Thanks!
