### ISSUE TITLE
Cant render images in Android that have file names with a '-' in them.

### ISSUE THREAD

**Issue by pizzahead24** [xamarin/Xamarin.Forms#5788]
### Description
My project is trying to display third party url images that we have no control over what they are named. The file name of a lot of them contain a hyphen in them. I have tried using both Xamarins Image component along with FFImageLoading and can confirm for some reason Xamarin Android cannot display these images with hyphens in them. Works fine in UWP and iOS. All images without the hyphen work.
### Steps to Reproduce

1. Get an image url with a hyphen in it.
2. Try to show the image with FFImageLoader or Image component
3. Notice it wont display.

### Expected Behavior
Url images with a file name that has a hyphen in it should work in Android.
### Actual Behavior
Url images with hyphen in the name do not work in Android

SAMPLE PROJECT

https://github.com/pizzahead24/xamarin-droidImageBug

**Comment by pizzahead24** [comment]
https://stackoverflow.com/questions/35755089/xamarin-forms-image-not-showing

**Comment by samhouts** [comment]
@pizzahead24 Can you please provide a small sample project? I know that we probably are unable to really resolve this issue for local images, due to Android limitations, but I feel like there should be some workaround for Urls. Thanks!

**Comment by pizzahead24** [comment]
@samhouts https://github.com/pizzahead24/xamarin-droidImageBug

**Comment by samhouts** [comment]
Hmm, so it's not the dashes. You can load this image, for example: `https://www.wikihow.com/images/thumb/5/51/Make-a-Dash-in-Microsoft-Word-on-Android-Step-4.jpg/aid8915250-v4-728px-Make-a-Dash-in-Microsoft-Word-on-Android-Step-4.jpg`

Your image fails before it even gets to the image loading bit. We're unable to even get your image as a stream. Here's what we get:

```
[0:] Image Loading: Error getting stream for https://listener.ecp123.com/medication_data/pill/images/68382-0106-01_NLMIMAGE10_32489964.jpg: System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (Authentication failed, see inner exception.) ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

That seems like it's related to how mono handles certificates (see https://www.mono-project.com/docs/faq/security/). 

Are you able to access images from the same source when they do *not* contain hyphens?

/cc @marek-safar in case he has any insight

Thanks!

**Comment by pizzahead24** [comment]
@samhouts Very interesting. Good job on that find. I havent tried images from that source without dashes since all of them contain dashes and we cant control them. I will look more into the certificate thing.

**Comment by pizzahead24** [comment]
@samhouts Whats also interesting, is the dash images from the listener.ecp123 server that wont work seem to work fine on web browsers on Android. Just seems to be Xamarin Android

**Comment by pizzahead24** [comment]
Adding 
System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };

In the MainActivity seemed to fix those images not showing, but is this ok to do?

**Comment by samhouts** [comment]
@pizzahead24 I can't speak to the security of returning true in all cases. You're potentially allowing unsecured access to sites with bad or missing certificates; however, if you are controlling the sites that you access and you trust them, then that may be a non-issue. There are resources online that describe best practices for the certificate management. You might be able to find guidance on the Xamarin forums or StackOverflow. And yes, this appears to be unique to mono. :)

Thanks!!
