### ISSUE TITLE
[Enhancement] Scheme/uri based asset mapping for accessing photos, files, etc...

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5789]
## Summary
Provide a syntax that can be provide different types of image sources to an *ImageSource*. This will allow users to load images from sources like sdcards, embeddedresources, PhotoKit, Android Gallery, etc.. in a cross platform way.

This is possibly belongs more inside Essentials but an agreed upon Uri structure could be shared by XF and Essentials allowing both to consume this type of data.

This will also be useful in conjunction with
https://github.com/xamarin/Essentials/issues/177
https://github.com/xamarin/Xamarin.Forms/pull/4915

## API Changes

```C#
// this will be used to describe different assets that can be loaded from a device
public class Asset
{
     public string Name
     public string Identifier
}
```

Add schemes that will indicate the source for an asset
```C#
public enum AssetScheme
{
     photo,embedded,storage
}
```

## Intended Use Case
Currently to use embedded resources users are required to write a markup extension. We could provide a scheme to access embedded resources

```xaml
<Image Source="embedded://AssemblyName/image.png" />
```

When utilizing something from the android gallery or need a way to represent a PHAsset on iOS. 
```xaml
ImageSource source = "photo://<Identifier>";
```

### Additional implementations
Ways to query for assets. A user could use this scheme plus some query parameters to query for photos or files

**Comment by jfversluis** [comment]
Looks cool for .NET MAUI, still? Closing it for Forms!
