### ISSUE TITLE
[Visual] Entry control page does not load in release

### ISSUE THREAD

**Issue by xXdRaGoNrIdDeRXx** [xamarin/Xamarin.Forms#5799]
### Description
If there is an entry control on the page with Visual="Material" the page will not load in Release mode on android

### Steps to Reproduce

1.  Open TheLittleThingsPlayground
2. Change MainActivity.cs code
From
``` C#
  global::Xamarin.Forms.Forms.SetFlags( "FastRenderers_Experimental", "Shell_Experimental");
  global::Xamarin.Forms.Forms.Init(this, bundle);
  LoadApplication(new App());
```
To 
``` C#
  global::Xamarin.Forms.Forms.SetFlags( "FastRenderers_Experimental" );//, "Shell_Experimental");
  global::Xamarin.Forms.Forms.Init(this, bundle);
  Xamarin.Forms.FormsMaterial.Init( this, bundle );
  LoadApplication(new App());
```

2.  start the app in release mode
3.  Go to entries page

### Expected Behavior
Entries page loads normally

### Actual Behavior
Entries page shows only a black screen

### Basic Information

- Version with issue: XF 3.6.0.220655
- Last known good version: N/A
- IDE: Visual Studio 2017 15.9.10
- Platform Target Frameworks:
  - Android: 9.0
- Affected Devices:
All Android

This is not exclusive to TheLittleThingsPlayground, but is a good example project to illustrate the issue

**Comment by samhouts** [comment]
Hmm, I was unable to reproduce the behavior you described. It launched in release mode just fine. I did have to keep the `Shell_Experimental` flag, since the app uses Shell. Otherwise, no issue! Do you have another project that shows this behavior, or more information that might help reproduce the issue? Thanks!

**Comment by xXdRaGoNrIdDeRXx** [comment]
hmmm, after creating a new basic android project i cannot reproduce either unfortunately I cannot upload the project where it is having the issue (NDA with my employer), but the premise is I have a fairly complex login screen that gets pushed modelly when the app starts and if i have any entry control on the page with material visual the app hangs and stays a black screen. I will play around with my project and see what is causing this.

**Comment by xXdRaGoNrIdDeRXx** [comment]
I managed to catch the crash while manually loading the page with a button.
[Visual crash.txt](https://github.com/xamarin/Xamarin.Forms/files/3080013/Visual.crash.txt)

**Comment by PureWeen** [comment]
What API device are you running on? I'm guessing you have multidex enabled? What happens if you disable multidex for release and enable proguard instead?

**Comment by xXdRaGoNrIdDeRXx** [comment]
Proguard and Multidex are on due to the size of my app i require Multidex, and im using latest API 9.0

**Comment by PureWeen** [comment]
@xXdRaGoNrIdDeRXx I'm chatting with the android team but it looks like an android tooling quirk if you have proguard + multidex enabled

If you add a proguard file with 
```
-keep class android.support.multidex.MultiDexApplication { *; }
```

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#example-proguard-configurations

that should fix the error for you
