### ISSUE TITLE
TextDecorations Strikethrough not called for FormattedText in iOS

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/Xamarin.Forms#5801]
### Description
If you set a Label with only a FormattedText value and set TextDecorations to Strikethrough. The text won't be stroke.

### Expected Behavior
The text will be stroke.

### Actual Behavior
The text is not stroke

### Basic Information

- Version with issue: 3.6.0.264807
- IDE: Visual Studio Mac
- Affected Devices: iOS

### More Informations

If we look the LabelRenderer for iOS we will see that in the OnElementPropertyChanged Method, if the changed property is the Text we call UpdateText and UpdateTextDecoration. But if the changed property is the FormatedText we only call UpdateText.

[iOS Renderer
](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs#L189)

**Comment by quentinR0bert** [comment]
Any news about it ???

**Comment by aimore** [comment]
@samhouts just tested on Xamarin.Forms 4.3.0.991211 
and setting Strikethrough to TextDecorations did not work on iOS

**Comment by ianvink** [comment]
@samhouts I can confirm also that updating to 4.3.0.991211 results on iOS not showing the strike through decoration, in our case in a cell of a ListView

**Comment by samhouts** [comment]
Yes, we're aware of a different root cause reported in #8272, and we have a fix in progress. Sorry for the inconvenience!

**Comment by daspuruanexinet** [comment]
This issue still appearing in XF v 4.5.0.725. Any news or workarounds?
