### ISSUE TITLE
[CollectionView] ItemsLayout property types do not show in IntelliSense

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#5802]
### Description
Per [feedback](https://github.com/davidortinau/VisualChallenge/pull/9) from @mattleibow, the `ItemsLayout` property options for `CollectionView` does not appear in IntelliSense, making it difficult to discover.

>There was no IntelliSense for the `ItemsLayout` property, and had to clunk around and then realised it was a TYPE, not an enum. I had to revert to the docs just to understand how to use the list.

### Steps to Reproduce

1. Attempt to set the `ItemsLayout` property CollectionView in a Xamarin.Forms project.
2. Note that options of `ListItemsLayout` or `GridItemsLayout` don't show up.

### Expected Behavior

The `ItemsLayout` options are easily discoverable.

### Actual Behavior

They are not easily discoverable.

### Basic Information

- Version with issue: 4.0.0-pre8
- Last known good version: N/A
- IDE: VS2019
- Platform Target Frameworks: Any
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:

**Comment by pierceboggan** [comment]
Could we add a XAML sample here so I could validate?

**Comment by hartez** [comment]
So as of 4.2.0, there _is_ Intellisense for the pre-defined list layout types:

![ItemsLayout_Intellisense](https://user-images.githubusercontent.com/538025/63640294-a2f80e80-c65b-11e9-8a20-87d792a1b62d.jpg)

For anything else, the layouts need to be defined in their own element, e.g.:

```
<CollectionView>
    <CollectionView.ItemsLayout>
        <GridItemsLayout Span="2" Orientation="Horizontal"></GridItemsLayout>
    </CollectionView.ItemsLayout>
</CollectionView>
```

So I'm not sure what avenues we have for improvement there. `GridItemsLayout` and `ListItemsLayout` both show up among the Intellisense options within `<CollectionView.ItemsLayout>`.

**Comment by adrianknight89** [comment]
@hartez As of 4.4.0.1160-nightly, there is no intellisense for `ItemsLayout`. Could this have anything to do with #7519?

@StephaneDelcroix Is there a way to hide `ItemsLayout` from XAML unless it's nested as in `<CollectionView.ItemsLayout>`? I find the current pre-defined `HorizontalList` / `VerticalList` values rather limiting.

**Comment by Uttam115** [comment]
@pauldipietro  I am facing the same issue as you faced in below url. Same Clinical record is accessible in Xcode project but in Xamarin forms, I am getting same exception as yours. Can you please tell how did you solve this ?
[https://github.com/xamarin/xamarin-macios/issues/4788](url)

**Comment by jsuarezruiz** [comment]
Actually, this is working. Feel free to reopen the issue or a new one if have issues.
