### ISSUE TITLE
Cannot drag more than one widget onto a RelativeLayout in Xamarin Android designer.

### ISSUE THREAD

**Issue by 851265601** [xamarin/Xamarin.Forms#5805]
### Description
When editing an .xml layout in the Xamarin Android designer, it is not possible to drag more than one widget onto a RelativeLayout.

### Steps to Reproduce

1.Create a new Xamarin Android App project in Visual Studio.
2.Navigate to the "Resources/layout/activity_main.axml".
3.Try to add two buttons to the Design. Trying to add the second one will show the "not allowed" symbol in place of the cursor.

### Expected Behavior
we could drag more than one widget onto a RelativeLayout.
### Actual Behavior
it is not possible to drag more than one widget onto a RelativeLayout.
### Basic Information

- Version with issue:VS 2017 and VS 2019

**Comment by samhouts** [comment]
If you are still experiencing this issue, please report it from the send feedback option within Visual Studio. Thank you!
