### ISSUE TITLE
Anonymous MessageCenter messages aren't heard anymore

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#5809]
### Description
Generally a MessageCenter message subscription it for a message sent from a specific class.
But it can also be anonymous in the sense that any class can `.Send` a message and any class will hear it.

For example:
Subscribe:
 `            MessagingCenter.Subscribe<string>(this,"ISENGINEON",OnEngineOnChanged);//Subscribe without caring who is sending the message. `

Send: 
`             MessagingCenter.Send("ISENGINEON", true.ToString());//Shared layer view models subscribe and react`

You see it discussed with successful results back in Jan of 2018
https://stackoverflow.com/questions/48047444/xamarin-android-how-do-i-pass-an-event-from-mainactivity-to-viewmodel-on-forms

Yet... Now, it seem to no longer work.  I'm testing in VS2019 with both 3.6.x stable and 4.0-pre

The subscribe takes place... the send takes place... The subscriber however never hears the message and thus never executes the handler method.

### Steps to Reproduce

1.  Any simple Xamarin app.  "Welcome to Xamarin Forms" is fine.  Add a button on the page
```xml
                    <Button
                        x:Name="Test"
                        Clicked="Test_OnClicked"
                        Text="Test" />
```
2.  Add a handler for the button in the code behind
```csharp
        private void Test_OnClicked(object sender, EventArgs e)
        {
            Console.WriteLine("INFORMATION: Test Button Clicked.");
             MessagingCenter.Send("ISENGINEON", true.ToString());//Shared layer view models subscribe and react
       }
```
3.  Add a subscriber anywhere you like.  I use the constructor of a view model
```csharp
            MessagingCenter.Subscribe<string>(this,"ISENGINEON",OnEngineOnChanged);//Subscribe without caring who is sending the message. This is how we can hear from Android project without being able to reference MainActivity or a Broadcast receiver.
```
4. Add the handler from the subscription
```csharp
        private void OnEngineOnChanged(string obj)
        {
            Console.WriteLine("INFORMATION> Well heck, it worked");
        }
```
5. Run the app
6. Add breakpoints as desired for confirmation

### Expected Behavior
When you click the button the message is sent - That is confirmed with breakpoints.
The subscriber should then run the assigned handler.

### Actual Behavior
The handler is never executed.  Indicating the subscriber never hears the message.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by tlhintoq** [comment]
Further input from the community found a solution: You have to specify the type `Application` and `Application.Current`.
https://forums.xamarin.com/discussion/comment/370364#Comment_370364

So the previously working syntax seems broken in 2019 - there is a way around it.

Android Broadcast listener:
`MessagingCenter.Send(Xamarin.Forms.Application.Current,"ISENGINEON", result.ToString());`
Shared layer view model
`MessagingCenter.Subscribe<Application,string>(this,"ISENGINEON",OnEngineOnChanged);`

**Comment by kingces95** [comment]
@tlhintoq Would you mind attaching a zipped reproduction of the issue? That really helps us triage. I'll cook one up if need be after triage of other issues with attached reproductions if you don't have the reduction handy.

**Comment by samhouts** [comment]
@tlhintoq  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
