### ISSUE TITLE
Can't overwrite styles when using CSS

### ISSUE THREAD

**Issue by SuperCorks** [xamarin/Xamarin.Forms#5812]
### Description
Overwriting a style or a style class using CSS at different levels of the view hierarchy doesn't work.

For example, importing a stylesheet (e.g. `label { background-color: blue; }`) in MainPage.xaml won't overwrite the same style (e.g. `label { background-color: yellow; }`) if it's been imported in App.xaml.

CSS styles defined in App.xaml should be overwritten by styles defined in the page's resources. And styles defined in the page's resources should be overwritten by the ones defined in its subviews. That's just common sens to me... and that's also how styles defined in xaml using the `<style>` tag work.

### Steps to Reproduce

1. Create a new project
2. Create 2 css files with the same style but different values (e.g. `label { background-color: blue; }` and `label { background-color: yellow; }`) 
3. Import one of them in App.xaml
4. Import the other one in MainPage.xaml
5. Run project

### Expected Behavior
The style imported in MainPage.xaml should prevail.

### Actual Behavior
The style imported in App.xaml is used.

### Basic Information

- Version with issue: latest stable version
- Affected Devices: iOS and Android

### Reproduction Link

You can find a sample project attached to this issue.
[CSSInheritance.zip](https://github.com/xamarin/Xamarin.Forms/files/3044618/CSSInheritance.zip)

**Comment by SuperCorks** [comment]
The same problem happens to css files added to resource dictionaries one after the other. Say you have the following code:

```csharp
public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            this.Resources.Add(styleSheet1);
            this.Resources.Add(styleSheet2);
        }

    // ....
```

Then the styles from `styleSheet2` don't overwrite the ones from `styleSheet1`.

**Comment by SuperCorks** [comment]
And finally, same thing with importing them using the xaml extension.

```xml
<Application xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MyApp">
    <Application.Resources>

            <StyleSheet Source="/Style1.css" />
            <StyleSheet Source="/Style2.css" />

    </Application.Resources>
</Application>
```

The styles in `Style1.css` don't get overwritten by the ones in `Style2.css`.

**Comment by samhouts** [comment]
Inheritance and specificity are currently unsupported scenarios (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/), but we would be happy to consider this for an enhancement. Thank you!

**Comment by SuperCorks** [comment]
@samhouts, I see what you're saying. Thank you. Just so I'm clear however, I'm not talking about inheritance or specificity if:
- by **inheritance** you mean having a subview inherit its parent's property value (e.g. a label inheriting its parent layout's `FontSize`)
- by **specificity** you mean the css line `label.with-class { ... }` overwrites a less specific `label { ... }` instruction

Here, I really think it's a bug because the same instruction
- `label { background-color: blue }` defined in the App's resource dictionary using css
- `label { background-color: yellow }` defined in a page's resource dictionary using css

is not overwritten by the css in the lower scope of the view hierarchy. Actually it's the opposite and it's really confusing.

**Comment by csteeg** [comment]
@samhouts I do think the original reported issue is a bug IMHO.
When looking at the code in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Element_StyleSheets.cs when the Parent property is set on element, it gathers all parent stylesheets, but then applies them in reverse order (so the App's stylesheet is applied last, thus overriding the local stylesheet if both properties are set like background-color in the example).
I think the fix would be simple, just loop through the stylesheets from 0 to Count-1 on line 54 instead of from Count-1 to 0
