### ISSUE TITLE
ImageButton

### ISSUE THREAD

**Issue by cherrybbb** [xamarin/Xamarin.Forms#5817]
### Description
I am trying to create an ImageButton that uses a different image for the normal (unpressed) state and the state where the user is actively pressing the button. I found an article that uses a VisualStateGroup to change the appearance of the button based on the state:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/imagebutton#imagebutton-visual-states

I am able to successfully use this to change the image. However, if I set a different image for the 'Pressed' state, when I click on the button, it does change to the new image as expected, but when I release the button it's visual state continues to display the pressed image and does not return to the 'Normal' state until I click somewhere else in the window.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: works
  - UWP:  not work
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://stackoverflow.com/questions/55466773/xamarin-imagebutton-states

**Comment by samhouts** [comment]
@cherrybbb Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@cherrybbb  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
