### ISSUE TITLE
Disposed objects are not handled properly in android scrollview renderer.

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#5820]
## Summary

Disposed objects are not handled properly in android scrollview renderer.

## Intended Use Case
We have used custom listview (SfListView). We have select and scrolling the listview item asynchronously and while navigating back from the page it will leads to crash **ObjectDisposedException**.

This issue is due to you have used delay timer in the OnScrollToRequested method.  When we leave the page while scrolling the listview disposed object exception occurs. 

We have fixed the issue by handling the disposed boolean property in the OnScrollToRequested  method. Please find the code snippet below.

     private async void OnScrollToRequested(object sender, ScrollToRequestedEventArgs e)
        {
            // 99.99% of the time simply queuing to the end of the execution queue should handle this case.
            // However it is possible to end a layout cycle and STILL be layout requested. We want to
            // back off until all are done, even if they trigger layout storms over and over. So we back off
            // for 10ms tops then move on.
            var cycle = 0;
            while (IsLayoutRequested)
            {
                await Task.Delay(TimeSpan.FromMilliseconds(1));

                if (_disposed)
                    return;
                cycle++;
                if (cycle >= 10)
                    break;
            }
        }

Can you kindly merge the above fix in your source to avoid this type of exception in future.

**Comment by samhouts** [comment]
@RawoofSharief Would you like to submit a pull request for this? Thanks!

**Comment by RawoofSharief** [comment]
@samhouts  Yes, We would suggest to move these code in your source. Thanks!.

**Comment by syncsiva** [comment]
@samhouts  Created merge request.
https://github.com/syncsiva/Xamarin.Forms/pull/1
