### ISSUE TITLE
[Enhancement] ShellItem Raised Center View Support

### ISSUE THREAD

**Issue by ChasakisD** [xamarin/Xamarin.Forms#5825]
## Summary
Raised Center View is a view that is above Bottom Tabs. This will provide the functionality for creating such things:  
![image](https://user-images.githubusercontent.com/23040695/55650524-99762300-57ee-11e9-8742-1704c78492f4.png)

## API Changes

In the Shell, some attached properties are needed
```cs
public static readonly BindableProperty RaisedCenterTemplateProperty;

public static DataTemplate GetRaisedCenterTemplate(BindableObject view);
public static void SetRaisedCenterTemplate(BindableObject view, DataTemplate value);
```

On both Android and iOS my approach was to create a stub menu item in center and prevent the user from clicking it. On android get the BottomNavigationMenuItem from the BottomNavigationView and set the Focusable and Clickable properties to false and on iOS we could use the ShouldSelectViewController delegate;

In order to properly work the raised center view, the BottomTabLayout.axml should change to:
```xml
<FrameLayout>
    <The current LinearLayout>
    <Our center view>
</FrameLayout>
```

On iOS the approach will be equivalent to Android.

I have implemented the RaisedCenterView with the current TabbedPage, but with Shell the implementation will be much easier. That was my approach on a application recently. I will be very happy to discuss more about it.

Glad to work for a PR if this request become approved!

## Intended Use Case
Raised Center view is very useful for apps with a need of a big call-to-action/master button.

**Comment by stfnilsson** [comment]
I have struggle to implement this in the Shell, managed in iOS but not yet in Droid. I’m using SkiaSharp. ChasakisD: Can you please share the code for the RaisedCenterView?

**Comment by ChasakisD** [comment]
Unable to share code right now. Going to make a demo app using the raised center with the TabbedPage. Implementing the raised center with shell should be the same. When the demo is published I'll ping you

**Comment by WouterStraver** [comment]
How is the progress for this feature? :-D

**Comment by TheBaileyBrew** [comment]
@ChasakisD any chance of that demo coming around soon? - This sort of implementation is EXACTLY what I'm looking for in my app. I've tried Sharpnado, but it doesn't work the way I need since it uses ContentView instead of ContentPage for the implementation.

**Comment by ScarletKuro** [comment]
This would be a really useful functionality in shell and also would allow to drop Sharpnado.Tabs. Because I also don't like that you can use only the ContentView for the tabs

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
