### ISSUE TITLE
[Enhancement] EntryCellTableViewCell should be public

### ISSUE THREAD

**Issue by acupajoe** [xamarin/Xamarin.Forms#5830]
## Summary
I'd like to be able to access the `TextView` from within the `EntryCellRenderer` but it is currently inaccessible due to its protection level. 

Currently access is only available via a hack `UITextField textField = (UITextField)cell.ContentView.Subviews [0];` as demonstrated [here](https://stackoverflow.com/a/27436813/3629438).

## API Changes

Change `class EntryCellTableViewCell : CellTableViewCell` to `public class EntryCellTableViewCell : CellTableViewCell`

[Code Reference](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Cells/EntryCellRenderer.cs#L128)

## Intended Use Case
Allow for further customization from platform specific renderers.

```
public override UITableViewCell GetCell(Cell item, UITableViewCell reusableCell, UITableView tv)
 {
            EntryTableViewCell cell = item as EntryTableViewCell;
            // cell.TextField.thingstocallhere
            return cell;
 }
```

**Comment by acupajoe** [comment]
@samhouts thanks for responding! Entry cells allow you to set the text color of descriptive text but not the placeholder color or value text color. I needed a custom renderer for it and had to use the _hacky_ version (seen in OP) to do so. Ideally this would be exposed in the Forms API, but this seemed like an easier fix!

**Comment by samhouts** [comment]
@acupajoe That makes sense! Would you have found using a `ViewCell` with an `Entry` as a suitable solution, as well? Thanks!

**Comment by acupajoe** [comment]
@samhouts It would, you'd have to combine it into a `StackLayout` with a `Label` and `Entry` for the same functionality, but yes that would work!

**Comment by techduggu** [comment]
Hi Team (@samhouts / @jfversluis ),

I'd like to pick this up. Do we see any issues with making EntryCellTableViewCell as public (in-case discussed internally) ?

Thanks!

**Comment by jfversluis** [comment]
Not sure what @samhouts opinion on this might be, but as the `CollectionView` is becoming stable and should be preferred over `ListView` and `TableView` I'm not sure if we should spend much time in this area and make changes to stimulate the usage of these controls.

**Comment by iupchris10** [comment]
@samhouts 
Another reason to possibly make this class public - I need to set the AccessibilityIdentifier on the text field, so my UI Test can tap the entry. I could use a ViewCell but was trying to stick with EntryCell for the performance benefit.

**Comment by techduggu** [comment]
@samhouts / @jfversluis : What do you suggest for the above use-case? I guess it makes sense to make it public so the existing users/apps (which are not using CollectionView and I guess there are many of them) can still get benefit from it. I'd like to pick this up unless if there's any better way?
Thanks!

**Comment by samhouts** [comment]
@techduggu Go ahead! I see no issue with doing this.
