### ISSUE TITLE
CollectionView doesn't reset visual selection state

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5832]
### Description

Perhaps related to other open issues on CollectionView selection. I have 2 way binding for SelectedItem, and when I clear out the model in the binding context, the row/item is still displaying as selected. I can select it over and over and it'll set and reset.

### Steps to Reproduce

https://www.screencast.com/t/6hiEZMHqc

### Expected Behavior

When I set the selected item to null, the visual selection on the ItemTemplate reverts to the default view.

### Actual Behavior

It remains selected.

### Basic Information

- Version with issue: 4.0-pre8
iOS

### Reproduction Link

https://github.com/davidortinau/wpbf/blob/master/WhitePaperBible/Views/PapersPage.xaml#L17

https://github.com/davidortinau/wpbf/blob/master/WhitePaperBible/ViewModels/PapersViewModel.cs#L65

**Comment by davidbritch** [comment]
For what it's worth, I've also seen this problem (on iOS). Even when I clear `SelectedItem` through code, the visual selection isn't cleared.

**Comment by PaulSinnema** [comment]
This problem persists on UWP. Setting SelectedItem = null does not change the SelectedItem to null but the old value remains after the set is done.
