### ISSUE TITLE
Forms.SetFlags not available for WPF

### ISSUE THREAD

**Issue by alataffective** [xamarin/Xamarin.Forms#5833]
Forms.SetFlags does not appear to be available in Xamarin.Forms.Platform.WPF.4.0.0.304370. Is it just too early to support this?

**Comment by samhouts** [comment]
@alataffective There are no experimental features implemented yet for `Forms.SetFlags`. What flag are you looking to enable? Thanks!

**Comment by alataffective** [comment]
I wanted to try CollectionView. Looking forward to having a view that can bind to a child collection like WPF ItemsControl.

**Comment by samhouts** [comment]
@alataffective At this time, WPF is community-supported. I hope to see CollectionView on WPF, too! 🤞  

/cc @mohachouch

**Comment by alataffective** [comment]
I'm grateful for the work being done to support WPF on Xamarin. I've been able to do a lot of what I wanted to.
