### ISSUE TITLE
Find clicked position of list item in  collectionview Xamarin form

### ISSUE THREAD

**Issue by ajaykeshri** [xamarin/Xamarin.Forms#5835]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

> VS bug [#842222](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/842222)

**Comment by drewgillies** [comment]
Thank you for the issue, Ajay--we'd like some more clarity, please. Please provide detailed steps to reproduce the problem.

**Comment by samhouts** [comment]
@ajaykeshri  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
