### ISSUE TITLE
OnAppearing not getting invoked

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#5836]
Hi,

I have the following **OnAppearing** in my Signup page..

```
protected override async void OnAppearing()
{
        .............
        .............
        .............
}

```
From HomePage, the user clicks add and if the user is not signed in then t will start the Signin ContentPage like this:

```
Navigation.PushModalAsync(new NavigationPage(new Signin())
{
    BarBackgroundColor = Color.White,
    BarTextColor = Color.Black
});

```
From the Signin Page the user clicks on the Signup button which will start the Signup ContentPage like this:

```
Navigation.PushModalAsync(new NavigationPage(new Signup())
{
    BarBackgroundColor = Color.White,
    BarTextColor = Color.Black
});

```
so then anything I keep in the OnAppearing will NOT be invoked even just a simple:

`await DisplayAlert("Signup", "OnAppearing should start", "OK");`

I am using Xamarin Forms 3.6.0.293080

Kindly help..

Thanks,
Jassim

**Comment by samhouts** [comment]
@jrahma Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jrahma** [comment]
I got this resolved by changing it to:

```
Navigation.PushModalAsync(new NavigationPage(new Signin())
{
    BarBackgroundColor = Color.White,
    BarTextColor = Color.Black
});
```

to:

`Navigation.PushModalAsync(new Signin());`

I don't know why is that but it solved my problem.
