### ISSUE TITLE
CollectionView SelectionMode SelectionMode="Multiple" Not working ( #5625 Not Solved) 

### ISSUE THREAD

**Issue by psp589** [xamarin/Xamarin.Forms#5844]
### Description
The issue #5625  was closed but it is not fixed.
In UWP I can't still select more than one item.
In Android I can, but the two way binding is not working (it works in mode= "single" but not in "Multiple") so in the UI I can see more than 1 item selected but it doesnt get reflected in the viewmodel.

**Comment by samhouts** [comment]
Duplicate of #5625
