### ISSUE TITLE
[Android] InputTransparent="true" doesn't work if ScrollView Orientation="Horizontal"

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#5845]
### Description
if InputTransparent, then scroll view should NOT Intercept the TouchEvent.
which impl https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs#L157
however, for HorizontalScrollView, it still Intercept the touch event.
this is because missing 
**`			if (_renderer.Element.InputTransparent)`
`				return false;`**
in AHorizontalScrollView
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/AHorizontalScrollView.cs#L20

btw, and the ScrollViewRenderer (NestedScrollView) should not Intercept the TouchEvent if Orientation is "Horizontal"? because AHorizontalScrollView will process Horizontal Scroll
**`			if (Element.InputTransparent || _view.Orientation == ScrollOrientation.Horizontal)`
`				return false;`**
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ScrollViewRenderer.cs#L157

### Expected Behavior
HorizontalScrollView scrolled, when ScrollView.InputTransparent = "true"

### Actual Behavior
HorizontalScrollView should not scroll, if ScrollView.InputTransparent = "true"

**Comment by samhouts** [comment]
@bill2004158 Thank you for the report! Would you be interested in building a test case for this problem and submitting a PR to resolve it?

**Comment by samhouts** [comment]
@bill2004158  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Mustafa-ah** [comment]
I am facing this issue any workaround, please?
