### ISSUE TITLE
TitleView not showing when PushModalAsync

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#5846]
I tried the TitleView in a PushModalAsync but nothing is shown.

My MainPage has:

```
NavigationPage.SetHasNavigationBar(this, false);
NavigationPage.SetBackButtonTitle(this, "");

```

which is needed for the MainPage but why it should affect the Modal pages although I set the:

`NavigationPage.SetHasNavigationBar(this, false);`

In the Modal page?

Below is my XAML and I am showing the page using:

`Navigation.PushModalAsync(new Signin());
`
My contractor:

```
public Signin ()
{
    InitializeComponent ();

    NavigationPage.SetHasNavigationBar(this, false);
}

```
My XAML:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:SyncfusionInputLayout="clr-namespace:Syncfusion.XForms.TextInputLayout;assembly=Syncfusion.Core.XForms"
             xmlns:SyncfusionBusyIndicator="clr-namespace:Syncfusion.SfBusyIndicator.XForms;assembly=Syncfusion.SfBusyIndicator.XForms"
             Padding="25"
             x:Class="Zeera.Signin">
    <NavigationPage.TitleView>
        <StackLayout Orientation="Horizontal">
            <Label Text="Sign in" HorizontalOptions="Start" VerticalOptions="CenterAndExpand" />
            <Image x:Name="ImageSigninTitleBarClose" Source="close.png" HorizontalOptions="End" VerticalOptions="CenterAndExpand">
                <Image.GestureRecognizers>
                    <TapGestureRecognizer Tapped="ImageSigninTitleBarCloseTapped" NumberOfTapsRequired="1" />
                </Image.GestureRecognizers>
            </Image>
        </StackLayout>
    </NavigationPage.TitleView>
    <ContentPage.Content>
    </ContentPage.Content>
</ContentPage>
```

**Comment by samhouts** [comment]
@jcmanke @adammeaney @tdoell What do you mean by 👎 ?

**Comment by jcmanke** [comment]
He's doing everything in his power to not show a title bar, then asking why it isn't showing up. It's not a valid bug.

**Comment by tdoell** [comment]
By applying this method
```
NavigationPage.SetHasNavigationBar(this, false);
```

he is explicitly saying don't show my navigation bar and then is wondering why his `TitleView` not showing up.

I agree with @jcmanke that this should not be posted as an issue/bug.

**Comment by adammeaney** [comment]
And he has a forum post where he hasn't even waited a day to discuss the issue.

Basically, its not a real issue, and raising it here was the wrong decision, and it does not belong on the Github issues.

If it was a constructive post asking to have a TitleView feature to exist even without a Navigation Page, that would be worth discussing potentially. But this is just not what is happening here.

The Github issues are about actual issues with how Forms works, not for asking how to use Forms.

[https://forums.xamarin.com/discussion/153290/modal-popup-not-showing-navigation-bar#latest](url)

**Comment by samhouts** [comment]
Great! I just wanted to make sure that your thumbs down didn't mean, "Boo, why doesn't this work, Forms needs to fix this!" 😆 Thanks for the clarification!!

@jrahma it looks like you have your answer on the forum. If you have additional context you'd like to add here, let us know! Otherwise, I'll go ahead and close this. Thanks!

**Comment by jrahma** [comment]
but that is not satisfying answer :( lol

I believe that TitleView should work for normal page as well as Modal popup because you cannot imaging any page without a title, at lease mostly...

That's why I' hope to make this as a feature request to provide the TitleView even for the modal popup and even if the Main page was set not to show the title bar because developers might need to show the bar for all pages except the main page especially if the main page was a tabview page.
