### ISSUE TITLE
[Android] MainActivity.OnBackPressed() System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by AdamBowler** [xamarin/Xamarin.Forms#5857]
### Description
Navigation stack seems to be lost while app is Sleeping causing a blank screen to appear when resumed and upon the back button being pressed the error `System.InvalidOperationException: Sequence contains no elements` occurring.

### Steps to Reproduce

1. Open a Xamarin.forms app
2. Put it on background
3. Resume the app

### Expected Behavior
App should resume as expected

### Actual Behavior
Blank screen appears and pressing back button causes app crash

### Basic Information

- Version with issue: 3.4.0.1009999
- Last known good version: 2.3.4.247
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 5.0. 6.0, 6.0.1, 7.0, 7.1.1, 8.0.0, 8.1.0, 9. It appears to be for every version of Android we support.
  - UWP:  N/A
- Android Support Library Version: 5.0 onwards
- Nuget Packages:
- Affected Devices: All

### Screenshots
![image](https://user-images.githubusercontent.com/17048266/55795305-5d2d1600-5abf-11e9-92d2-a3ad316f5de5.png)

**Comment by samhouts** [comment]
@AdamBowler  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@AdamBowler  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by AdamBowler** [comment]
@samhouts sorry only just seen this, @PaulsonMac I raised this when nopbody replied on the other issue here https://github.com/xamarin/Xamarin.Forms/issues/4715

**Comment by PaulsonMac** [comment]
Hi Adam, I don't have a sample app..
