### ISSUE TITLE
[Shell] Single page app throws exception

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#5858]
### Description

The Shell spec says it's possible to create a single page Shell app as follows:

```
<Shell xmlns="http://xamarin.com/schemas/2014/forms"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:views="clr-namespace:Xaminals.Views"
       x:Class="Xaminals.AppShell"
       FlyoutBehavior="Disabled">
    <views:CatsPage />
</Shell>
```

However, this throws a `NullReferenceException` on Android, and a `InvalidOperationException` on iOS.

### Steps to Reproduce

1. Run the attached sample.

### Expected Behavior

Single page app is displayed.

### Actual Behavior

`NullReferenceException` on Android, and a `InvalidOperationException` on iOS.

### Basic Information

- Version with issue: 4.0-pre8
- Last known good version: N/A
- IDE: VSMac 8.0
- Platform Target Frameworks: 
  - iOS: 12.1
  - Android: API 27 

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3058722/Xaminals.zip)

**Comment by samhouts** [comment]
This no longer errors on pre9. Thanks!
