### ISSUE TITLE
The Right To Left flow direction doesn't change the text flow direction in Entry and Editor

### ISSUE THREAD

**Issue by ArunSivaR** [xamarin/Xamarin.Forms#5860]
**Description**
The text flow direction behavior of entry and editor differs in Android and UWP, in a sample if we set the flow direction as Right to Left the editor and entry text doesn't changed in UWP and Android and if we force the editor and entry to change the flow direction by set the flow direction for editor and entry the flow direction changes in Android but doesn't work on UWP

**Basic Information**

Tested Version: 3.4.0.1029999

**Replication Procedure**
1.	Run the attached sample [EditorSample](https://drive.google.com/file/d/14C5eD28RmgYIezfiMeLWo0ufXSe16sJg/view?usp=sharing)
2.	In the sample we have added an Entry and Editor inside Grid,
3.	And we have given the flow direction as Right to Left for the page and the elements
4.	But the given text doesn’t display in the given flow direction in UWP
5.	It always displayed in Left to Right flow direction.

**Comment by samhouts** [comment]
@ArunSivaR Thanks! This is a known limitation.

**Comment by mrlacey** [comment]
I'm not really sure about this being a "known limitation" as the FlowDirection isn't being set correctly when compared with using equivalent native control and settings. Even though Windows automatically adjusts for OS level language settings and the text that is entered, it is still possible to force RTL.
The easiest way to tell if the rendered `Entry` control thinks it's in RTL mode is to set focus and see where the delete button is placed inside the control. If in RTL mode the button will be on the left (as below.) This is what a native single line `TextBox` does.

![image](https://user-images.githubusercontent.com/189547/59044612-5da31c80-8876-11e9-988e-e765715cd2e2.png)


I'm working on a proper fix and will look at Editor in more detail too.

**Comment by KarthikRajaAKR** [comment]
HI Team,

We are also facing issue with RTL in iOS while using Entry. We have gone through the limitation page and found that RTL in Entry will work only with device Locale. So we have tested the same by changing Device Locale to Arabic still Entry Text aligned at  Left. We are using EntryRenderer to create custom controls. Is there any other limitations on this with Entry in iOS.

Thanks.
