### ISSUE TITLE
Button image is not centered

### ISSUE THREAD

**Issue by CoffeePerry** [xamarin/Xamarin.Forms#5861]
### Description
I found a problem in Button's image centering when Application.MainPage property is set to a NavigationPage: image will be positioned on the left in the button, instead of in the center.

In App.xaml.cs, using:
MainPage = new NavigationPage(new HomePage());

Instead of:
MainPage = new HomePage();

In HomePage's buttons, images will be on the left instead of the center.

P.S.: I found this problem only in Android.

### Steps to Reproduce

1. In App.xaml.cs, use:
    MainPage = new NavigationPage(new HomePage());

### Expected Behavior

In HomePage, buttons images are on the center.

### Actual Behavior

In HomePage, buttons images are on the left.

### Basic Information

- Version with issue: Xamarin.Forms 3.6.0.264807
- Last known good version: Xamarin.Forms 3.4.0.1029999
- IDE: Microsoft Visual Studio Community 2019 16.0.0
- Platform Target Frameworks: 
  - iOS: 12.1 - I have NOT found this problem.
  - Android: Android Oreo 8.1 - API 27 - I have found this problem.
  - UWP:  I have not tried yet. 
- Android Support Library Version: 28.0.0.1
- Nuget Packages: Xamarin.Forms (3.6.0.264807); Xamarin.Essentials (1.0.1)

### Screenshots

![image](https://user-images.githubusercontent.com/39993316/55806463-90cc6800-5ae0-11e9-8fec-1ad3b54ea84f.png)

**Comment by samhouts** [comment]
@mattleibow I guess we didn't fix 'em all 😆 (referring to #4967)

**Comment by APopatanasov** [comment]
Is a fix expected to be applied soon? My image verification tests have failed because of this issue. 😄

**Comment by CoffeePerry** [comment]
A way to get around this problem is using ImageButton intead of Buttton, for now.

**Comment by APopatanasov** [comment]
@CoffeePerry Thanks for the workaround. I have tested it and it works. For now I will use it.  Still, I hope as the issue was introduced with one of the latest official releases to be addressed and fixed soon. Thanks again.

**Comment by CoffeePerry** [comment]
@APopatanasov You're welcome

**Comment by CoffeePerry** [comment]
You solved, thanks!
