### ISSUE TITLE
[Enhancement] binding VisualStateManager.CurrentState

### ISSUE THREAD

**Issue by candidodmv** [xamarin/Xamarin.Forms#5864]
## Summary

Basically a way to control the current state based on a Bindable Property

## API Changes

N/A

## Intended Use Case

Maybe the idea is not applicable, but basically would be a way to set the current VisualState of a View based of a current value of your bindable context. 

imagine a list of items which state would be :
* read
* new
* not applicable 
* ...

each of these states has any rules, that would be applicable by the value of the item.

**Comment by KSemenenko** [comment]
i'm going to do it

**Comment by hartez** [comment]
What's the point of this proposed enhancement? What problem are you trying to solve with it?

**Comment by candidodmv** [comment]
Hello @hartez It seams that was rejected as you can se in the related PR made by @KSemenenko above.

This proposal can be achived by StateTrigger, so became unecessary.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers#state-trigger
