### ISSUE TITLE
VisualElement.Unfocus does not work on WPF

### ISSUE THREAD

**Issue by alataffective** [xamarin/Xamarin.Forms#5868]
### Description
VisualElement.Unfocus() does not appear to work on WPF, at least Entry.Unfocus() does not work.

### Steps to Reproduce

1. Create a Xamarin.Forms WPF project
2. Create an Entry
3. Create a timer that calls Entry.Unfocus() after say 3 seconds
4. Start the app, click the Entry, wait for the timer to elapse

### Expected Behavior
After the timer has elapsed, the Entry no longer has focus.

### Actual Behavior
The Entry continues to have focus.

### Basic Information
- Version with issue:
3.4.0.1008975

**Comment by samhouts** [comment]
@alataffective Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by alataffective** [comment]
Sure, example here: https://github.com/alataffective/Xamarin-VisualElement.Unfocus-not-working-on-WPF

**Comment by alataffective** [comment]
There are other differences between the behaviour of WPF and UWP.

1. Focus does not get removed from the Entry when clicking elsewhere in the window.
2. In UWP, Entry has initial focus, WPF not.

Let me know if you need a bug raising for these (especially 1).

**Comment by samhouts** [comment]
closed by #7883
