### ISSUE TITLE
"error": "InvalidRegistration"  FCM - Xamarin.Forms

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#5871]
### Description
I am developing FCM notifications with Xamarin.Forms using [FCM Notifications Plugin](https://github.com/CrossGeeks/FirebasePushNotificationPlugin). In iOS project I am collecting token. When sending notifications using Postman to the same token getting error 

> { "multicast_id": 8631208504861228784, "success": 0, "failure": 1, "canonical_ids": 0, "results": [ { "error": "InvalidRegistration" } ] }

I have added valid _GoogleService-Info.plist_ file with _BuldleResource_ Built Action. This is code of **`AppDelegate`** class

Note: I am sending notification to real device iPhone 5. Which connected to MAC machine and debugging from VS2017(PC).

```
[Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            LoadApplication(new App());

            FirebasePushNotificationManager.Initialize(options, new NotificationUserCategory[]
            {
                new NotificationUserCategory("message",new List<NotificationUserAction> {
                    new NotificationUserAction("Reply","Reply",NotificationActionType.Foreground)
                }),
                new NotificationUserCategory("request",new List<NotificationUserAction> {
                    new NotificationUserAction("Accept","Accept"),
                    new NotificationUserAction("Reject","Reject",NotificationActionType.Destructive)
                })
            });
            return base.FinishedLaunching(app, options);
        }

        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            var token = deviceToken.ToString();
            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken.ToString());
            Console.WriteLine("This is token: "+deviceToken);

            var DeviceToken = deviceToken.Description;
            if (!string.IsNullOrWhiteSpace(DeviceToken))
            {
                DeviceToken = DeviceToken.Trim('<').Trim('>');
            }

            NSUserDefaults.StandardUserDefaults.SetString(DeviceToken, "PushDeviceToken");

        }
        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        // To receive notifications in foregroung on iOS 9 and below.
        // To receive notifications in background in any iOS version

        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine(userInfo);
            completionHandler(UIBackgroundFetchResult.NewData);
        }
    }
```

The above code I have got from here
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/samples/FirebasePushSample/FirebasePushSample.iOS/AppDelegate.cs

### Steps to Reproduce

1. Create Xamarin.Forms project and install [push notification nuget](https://github.com/CrossGeeks/FirebasePushNotificationPlugin)
2.  Add valid _GoogleService-Info.plist_ file in iOS project
3. Write above code in AppDelegate class and send notification from Posman to generated token.

### Expected Behavior
Notification should deliver to device
### Actual Behavior
Notifications not delivering
### Basic Information
- IDE:
Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.208
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.79 (d15-9@260fa6a34)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.5.0 (HEAD/4b951a3e7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

- Platform Target Frameworks: 
  - iOS:  
Xamarin.iOS and Xamarin.Mac SDK   12.2.1.12 (65ec520)

- Affected Devices: iPhone 5.

### Reproduction Link

For more visit this 

https://stackoverflow.com/questions/55594820/ios-device-token-generating-in-strange-format/

**Comment by samhouts** [comment]
@arvindrajachourasiya Hi! I doubt this is related to Xamarin.Forms. It looks like you have some promising feedback on the StackOverflow post. You may also want to try the Xamarin Forums. I see you've already reported an issue on https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/229, so I think you'll find an answer somewhere! Thanks!!

**Comment by arvindrajachourasiya** [comment]
@samhouts - Thank you. Actually this errors I am getting in Xamarin.Forms project. So I thought to Submit here. 
And I have given Stackvoerflow link for the sake of more information.  If according to you it's not related to Xamarin.Forms please move it to Xamarin.iOS because I need solution to this issue as already I have wasted 2 3 days on it. Thank you

**Comment by arvindrajachourasiya** [comment]
Hello please open this issue @samhouts
