### ISSUE TITLE
[Android] Child view state gets changed when navigate from 5th tab to 1st tab

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#5873]
### Description
We have added treeview inside tabbed page's first content. Before navigating to tab, am expanding the treeview. If i naviagte ampng 4 tabs, Treeview state maintained as same as i expanded. If i navigate to 5th tab and return back to 1st tab, my treeview gets collapsed.
This happens only in android.

### Steps to Reproduce

1. Run the sample.
2. Expand treeview in 1st tab. 
3. Switch view to 5th tab
4.Return back to 1st tab

### Expected Behavior

Treeview should display as expanded when return back from 5th tab

### Actual Behavior

Treeview gets collapsed when return back from 5th tab

### Basic Information

- Version with issue: 3.6.220655
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
    - Android: 8.1
- Android Support Library Version: 27.0.2.1

### Screenshots

Before navigating to tab 5:
![image](https://user-images.githubusercontent.com/44390143/55877401-88932c00-5bb7-11e9-956b-fec09878f533.png)

After returning back from tab 5:
![image](https://user-images.githubusercontent.com/44390143/55877338-69949a00-5bb7-11e9-932f-1af9093a9af6.png)

### Reproduction Link

http://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-1199286686

**Comment by GalaxiaGuy** [comment]
I believe it is because the default `OffscreenPageLimit` for the tab bar on Android is 3, so once you get to a fourth offscreen page, the earliest is destroyed (and recreated when you need it).

You should be able to override it with the following XAML:

```xml
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
    android:TabbedPage. OffscreenPageLimit="4">
```

or C#
```csharp
using Xamarin.Forms.PlatformConfiguration.AndroidSpecific;

tabbedPage.On<Xamarin.Forms.PlatformConfiguration.Android>().SetOffscreenPageLimit(4);
```

**Comment by samhouts** [comment]
@GnanaPriyaNamasivayam Yep, @GalaxiaGuy is correct! Thanks!!
