### ISSUE TITLE
[Bug] ListView.ScrollTo causes an exception in iOS 10

### ISSUE THREAD

**Issue by 1saeedsalehi** [xamarin/Xamarin.Forms#5874]
### Description
ListView.ScrollTo method does not seem to work in iOS version 10.3 or lower, but it works fine in current versions of iOS

### Steps to Reproduce

1. Bind the list view to an empty ObservableCollection 
2. add an item to list
3. call `ScrollTo(object item, ScrollToPosition position, bool animated)` method while `OnBindingContextChanged` method occurred

### Expected Behavior
Scroll to end of the list view

### Actual Behavior
an unhandled exception is thrown
```
Unhandled Exception:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSRangeException Reason: -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:]: row (0) beyond bounds (0) for section (0).
Native stack trace:
	0   CoreFoundation                      0x0000000119775b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011a5c8141 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001197de625 +[NSException raise:format:] + 197
	3   UIKit                               0x0000000115acb68a -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:] + 1679
	4   UIKit                               0x0000000115acc2b9 -[UITableView scrollToRowAtIndexPath:atScrollPosition:animated:] + 39
	5   XeposWaiterApp.iOS                  0x000000010e0b5839 xamarin_dyn_objc_msgSend + 217
	6   ???                                 0x000000013a495128 0x0 + 5272850728
```

### Basic Information

- Version with issue:  Xamarin Forms 3.6.0.293080
- IDE: Visual Studio 2019 (16.0.1)
- Platform Target Frameworks: 
  - iOS:  10.3
- Affected Devices: Simulator iPad Air 2 - iOS 10.3

**Comment by samhouts** [comment]
@1saeedsalehi Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@1saeedsalehi  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by GagandeepSingh510** [comment]
what is the fix for this ? I got the same issue in my application.

**Comment by bill2004158** [comment]
yes, I have got same error:

Received unhandled ObjectiveC exception: NSRangeException -[UITableView _contentOffsetForScrollingToRowAtIndexPath:atScrollPosition:]: row (0) beyond bounds (0) for section (0).

**Comment by dejanbasic** [comment]
I get this, when trying to scroll an empty list:

`SIGABRT: Objective-C exception thrown. Name: NSRangeException Reason: Attempted to scroll the table view to an out-of-bounds row (0) when there are only 0 rows in section 0...`
