### ISSUE TITLE
[Bug]  Tab index not resetting on iPAD

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5879]
### Description
https://github.com/xamarin/Xamarin.Forms/pull/3989#issuecomment-477360686

### Steps to Reproduce

1.  run control gallery
2. Accessibility Tab Index
3. on an iPad if you swipe to the end it stops on "14" and won't go any further. @samhouts tested this on a device and on the device it works fine

### Expected Behavior
Expectations are that iOS/Android will incorrectly read the master page contents first (#4220), then BONG that you're at the end of the elements; wait a second, and then it will allow you to start from the beginning again.

### Actual Behavior
iPad is not allowing you to start from the beginning

### Basic Information

- Version with issue: 4.0 pre9
- Platform Target Frameworks: 
  - iOS:  12
- Affected Devices: IPAD

**Comment by samhouts** [comment]
@PureWeen Would you mind testing again with https://github.com/xamarin/Xamarin.Forms/files/4248008/Xamarin.Forms.4.4.0.993247.nupkg.zip? Thanks!
