### ISSUE TITLE
[macOS] NRE when disposing an Entry

### ISSUE THREAD

**Issue by slakul** [xamarin/Xamarin.Forms#5881]
### Description

Disposing an Entry throws NullReferenceException. Below is the stack trace. The bug is in EntryRenderer.OnElementChanged method which calls EntryRenderer.CreateControl after Element has been set to null.

	Xamarin.Forms.Platform.MacOS.EntryRenderer.CreateControl() in 
	Xamarin.Forms.Platform.MacOS.EntryRenderer.OnElementChanged(Xamarin.Forms.Platform.MacOS.ElementChangedEventArgs<Xamarin.Forms.Entry> e) in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.Entry>.SetElement( Parameters) in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.Entry>.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.ViewRenderer<Xamarin.Forms.Entry,AppKit.NSTextField>.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.EntryRenderer.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose(bool disposing) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.Dispose() in 
	Xamarin.Forms.Platform.MacOS.VisualElementRenderer<Xamarin.Forms.VisualElement>.Dispose(bool disposing) in 
	Foundation.NSObject.Dispose() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSObject2.cs:147
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView view) in 
	Xamarin.Forms.Platform.MacOS.VisualElementPackager.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView sender, Xamarin.Forms.ElementEventArgs e) in 
	Xamarin.Forms.Element.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView child) in 
	Xamarin.Forms.VisualElement.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView child) in 
	Xamarin.Forms.Layout<Xamarin.Forms.View>.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView child) in 
	Logotec.AppStudio.Client.Layouts.SmartGrid.OnChildRemoved(Logotec.AppStudio.Client.Views.DynamicView child) in /Users/Slawomir/Projects/AppStudio2018/Logotec.AppStudio.Client/Layouts/SmartGrid.cs:133
	Xamarin.Forms.Layout.OnInternalRemoved(Logotec.AppStudio.Client.Views.DynamicView view) in 
	Xamarin.Forms.Layout.InternalChildrenOnCollectionChanged(System.Collections.ObjectModel.ObservableCollection<Xamarin.Forms.Element> sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e) in 
	System.Collections.ObjectModel.ObservableCollection<Xamarin.Forms.Element>.OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedEventArgs e) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263
	System.Collections.ObjectModel.ObservableCollection<Xamarin.Forms.Element>.OnCollectionChanged(System.Collections.Specialized.NotifyCollectionChangedAction action, Logotec.AppStudio.Client.Views.DynamicView item, int index) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:338
	System.Collections.ObjectModel.ObservableCollection<Xamarin.Forms.Element>.RemoveItem(int index) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:182
	System.Collections.ObjectModel.Collection<Xamarin.Forms.Element>.Remove(Logotec.AppStudio.Client.Views.DynamicView item) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:130
	Xamarin.Forms.ObservableWrapper<Xamarin.Forms.Element,Xamarin.Forms.View>.Clear() in 
	Logotec.AppStudio.Client.Pages.DataItemPage.DataItemPageState.BuildViewAsync() in /Users/Slawomir/Projects/AppStudio2018/Logotec.AppStudio.Client/Pages/DataItemPage.xaml.cs:188
	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Logotec.AppStudio.Client.Pages.DataItemPage.DataItemPageState.<BuildViewAsync>d__30>(Logotec.AppStudio.Client.Pages.DataItemPage.DataItemPageState stateMachine) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
	Logotec.AppStudio.Client.Pages.DataItemPage.DataItemPageState.BuildViewAsync() in 
	Logotec.AppStudio.Threading.DelayedTaskAggregator.<>c__DisplayClass19_0.<-cctor<-cctor>g__LocalRunAsync|1>d() in /Users/Slawomir/Projects/AppStudio2018/Logotec.AppStudio/Threading/DelayedTaskAggregator.cs:183
	System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Logotec.AppStudio.Threading.DelayedTaskAggregator.<>c__DisplayClass19_0.<<-cctor>g__LocalRunAsync|1>d>(Logotec.AppStudio.Threading.DelayedTaskAggregator.<>c__DisplayClass19_0 stateMachine) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:316
	Logotec.AppStudio.Threading.DelayedTaskAggregator.() in 
	Logotec.AppStudio.Threading.SmartDispatcher.<>c__DisplayClass9_0.<BeginInvoke<BeginInvoke>g__Action|0>d() in /Users/Slawomir/Projects/AppStudio2018/Logotec.AppStudio/Threading/SmartDispatcher.cs:94
	System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<Logotec.AppStudio.Threading.SmartDispatcher.<>c__DisplayClass9_0.<<BeginInvoke>g__Action|0>d>(Logotec.AppStudio.Threading.SmartDispatcher.<>c__DisplayClass9_0 stateMachine) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:84
	Logotec.AppStudio.Threading.SmartDispatcher.() in 
	Logotec.AppStudio.Platform.Extensions.Dispatcher.() in /Users/Slawomir/Projects/AppStudio2018/Logotec.AppStudio.Platform/Extensions/Dispatcher.cs:58
	Foundation.NSAsyncActionDispatcher.Apply() in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/Foundation/NSAction.cs:152
	AppKit.NSApplication.NSApplicationMain() in 
	AppKit.NSApplication.Main(string[] args) in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.2.1.16/src/Xamarin.Mac/AppKit/NSApplication.cs:100
	LogotecAppStudio.macOS.MainClass.Main(string[] args) in /Users/Slawomir/Projects/AppStudio2018/LogotecAppStudio/LogotecAppStudio.macOS/Main.cs:11

### Steps to Reproduce

1. Place an Entry in a Grid or in any Layout<View> control
2. Remove the Entry from the control
3. Application is killed

### Expected Behavior

There should not be thrown any exception.

### Actual Behavior

NullReferenceException is thrown.

### Basic Information

- Version with issue: 4.0.1.268567-nightly
- Last known good version:
- IDE: Visual Studio for Mac 7.8.3
- Platform Target Frameworks: 
  - macOS:  5.2.1.16
- Affected Devices: macOS Mojave (10.14.4)

**Comment by samhouts** [comment]
@slakul Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by slakul** [comment]
I attached the sample project. Just run and click "Clear" button.
[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3066392/TestApp.zip)
