### ISSUE TITLE
[Bug] PowerSaveModeBroadcastReceiver: Specified cast is not valid

### ISSUE THREAD

**Issue by asgarddesigns** [xamarin/Xamarin.Forms#5884]
### Description
We are getting a consistent crash when plugging/unplugging a few Android devices.

This has been tested on a few different devices internally (most notably a Samsung S5 & pixel 2 XL) as well as reports in the wild.

### Steps to Reproduce

1. plug an android device into your computer so it starts charging
2. unplug

### Expected Behavior
nothing visible should happen (app should get power save alerts)

### Actual Behavior
App crashes

### Basic Information

- Version with issue: release-3.6.0-sr2 and later
- Last known good version:
- IDE: Rider/VS for mac
- Platform Target Frameworks: 
  - Android: 9.0 
- Android Support Library Version: 28.0.0
- Nuget Packages:
- Affected Devices:
  - Google Pixel 2 XL
  - Google Pixel 2
  - samsung SM-G9200
  - ZTE ZTE Blade V580
  - Google Pixel 3
  - Google Pixel 3 XL
  - HTC HTC 2PZM3
  - LGE LGMP260
  - LGE LG-TP450
  - samsung SM-G973F
  - Sony E5533

**Comment by AntRemo** [comment]
Hi @asgarddesigns 

Was this previously working for you? 
Do you have a call stack available?

Thanks

**Comment by samhouts** [comment]
@AntRemo  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by asgarddesigns** [comment]
Oh sorry, thought I'd attached the stack trace 😞 
```
Xamarin.Forms.Platform.Android.PowerSaveModeBroadcastReceiver.OnReceive(Android.Content.Context context, Android.Content.Intent intent) in Xamarin.Forms.Platform.Android.PowerSaveModeBroadcastReceiver.cs:0
Android.Content.BroadcastReceiver.n_OnReceive_Landroid_content_Context_Landroid_content_Intent_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_context, System.IntPtr native_intent) in Android.Content.BroadcastReceiver.cs:0
```
It looks like the problematic line is 

`((AndroidTicker)Ticker.Default).CheckPowerSaveModeStatus();`

Could the ticker be a different instance in Forms maybe?

**Comment by samhouts** [comment]
@asgarddesigns Thanks for the call stack! Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by asgarddesigns** [comment]
@samhouts Sorry, I don't really have time for that as I'm about to go on holiday. I can probably try when I'm back...

**Comment by samhouts** [comment]
Okay, we'll keep looking for it. Thanks!

**Comment by samhouts** [comment]
@asgarddesigns  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
