### ISSUE TITLE
[Bug] ListView HasUnevenRows is not working in iOS 10

### ISSUE THREAD

**Issue by msangtarash** [xamarin/Xamarin.Forms#5888]
### Description
HasUnevenRows doesn't work in iOS version 10.3 while Xamarin forms version is the latest (3.6.0.293080) ,but it works fine in other versions of iOS and Xamarin forms.

### Steps to Reproduce
1. Add a listView 
2. Set HasUnevenRows to true
3. Size of row cells in listView doesn't change automatically.

```
       <ListView  
            HasUnevenRows="True">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout>
                            <Label Text="Hi" />
                            <Label Text="bye" />
                            <Label Text="Open" />
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
            <ListView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>mono</x:String>
                    <x:String>monodroid</x:String>
                </x:Array>
            </ListView.ItemsSource>
        </ListView>
```
### Basic Information

- Version with issue: Xamarin Forms 3.6.0.293080
- IDE: Visual Studio 2019 (16.0.1)
- Platform Target Frameworks :
                 iOS: 10.3

### Reproduction Link 
[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3068521/Sample.zip)

**Comment by samhouts** [comment]
Well, the missing padding is also a little weird. Here's 3.6.0 SR1:
![image](https://user-images.githubusercontent.com/7827070/56005600-16d5e380-5c86-11e9-9b90-011456b4e2b5.png)
And 3.6.0 SR2:
![image](https://user-images.githubusercontent.com/7827070/56005654-63b9ba00-5c86-11e9-9dbe-abecaf8da576.png)

**Comment by brandonyoung** [comment]
Downgrading to Xamarin.Forms 3.6.0.220655 resolved the issue.  Anything higher still had the issue.

**Comment by melimion** [comment]
@samhouts, issue is in this line https://github.com/xamarin/Xamarin.Forms/blob/aa6d3f3a4a6796ffe106f2e6e88f0e7cccc28d3a/Xamarin.Forms.Platform.iOS/Renderers/ListViewRenderer.cs#L823

can be fixed by changing to 

>if (estimatedRowheight>0 || estimatedRowheight == 0 && IsiOS11OrNewer)
