### ISSUE TITLE
[macOS] Control with VerticalOption=Start is sticked to bottom

### ISSUE THREAD

**Issue by slakul** [xamarin/Xamarin.Forms#5890]
### Description

A control with VerticalOption=Start has wrong behaviour during resize. When I change the height of the main window, then items are moved as they were sticked to the bottom of the window. When I change the width of the window, then the position of controls is recalculated and everything looks good.

### Steps to Reproduce

1. Run the attached sample
2. Change the main window height (do not change width)
3. Items are moved, but should be sticked to the top of the window

### Expected Behavior

Items should be sticked to the top of the window.

### Actual Behavior

Items are moved.

### Basic Information

- Version with issue: 4.0.1.268567-nightly
- Last known good version:
- IDE: Visual Studio for Mac 7.8.3
- Platform Target Frameworks: 
  - macOS: 5.2.1.16
- Affected Devices: macOS Mojave (10.14.4)

### Screenshots

After start
![start](https://user-images.githubusercontent.com/14055723/55960908-09146400-5c6e-11e9-81c9-96f293a854fa.png)

After height change
![height_plus](https://user-images.githubusercontent.com/14055723/55960914-0d408180-5c6e-11e9-937d-7740b6994caa.png)
![height_minus](https://user-images.githubusercontent.com/14055723/55960922-10d40880-5c6e-11e9-89fb-f9728a4aacaf.png)

After width change items position is recalculated
![height_minus_width_change](https://user-images.githubusercontent.com/14055723/55960934-13cef900-5c6e-11e9-86b4-bf0a4336d357.png)

### Reproduction Link

[TestAppVerticalOptionStartBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3068807/TestAppVerticalOptionStartBug.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
