### ISSUE TITLE
[Enhancement] Official PageContainerView

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#5891]
## Summary
A view that can embed ContentPages, conceptually similar to iOS's view controller containment.

I've seen this implemented a few times:
https://github.com/TomSoderling/PageContainerView/blob/master/Library/PageContainerView.Plugin/PageContainerView.cs
https://github.com/TomSoderling/PageContainerView/blob/master/Library/PageContainerView.Plugin/PageContainerView.cs

but I think this is fundamental enough to warrant an officially supported implementation.

## API Changes

```csharp
namespace Xamarin.Forms
{
	public class PageContainerView : View
	{
		public static readonly BindableProperty ContentProperty = BindableProperty.Create(nameof(Content), typeof(ContentPage), typeof(PageViewContainer));

		public Page Content
                {
			get => (ContentPage)GetValue(ContentProperty);
			set => SetValue(value);
		}
	}
}
```

## Intended Use Case

This would allow creating things like a custom TabbedPage or a split view page without resorting to a platform specific implementation.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
