### ISSUE TITLE
[Bug] Android crash with SIGSEGV after VS 2019 update

### ISSUE THREAD

**Issue by georgeinva2004** [xamarin/Xamarin.Forms#5903]
### Description
I have a Xamarin Forms Android app which works fine under VS 2017, but crashes with a SIGSEGV after updating to Visual Studio 2019.  Unfortunately, it's not really possible to tell where in the code the crash is happening and all I have is a crash report from the debugger.  
### Steps to Reproduce
The app and the backend environment are way to complicated to do a "small repo" to demonstrate the issue.   The crash info is included below.

### Expected Behavior
No crash

### Actual Behavior
Random crashes with the following dump
04-12 14:33:07.962 I/zygote64(19787): Explicit concurrent copying GC freed 318(61KB) AllocSpace objects, 0(0B) LOS objects, 77% free, 1746KB/7MB, paused 647us total 35.814ms
04-12 14:33:07.965 D/Mono    (19787): GC_TAR_BRIDGE bridges 193 objects 206 opaque 19 colors 193 colors-bridged 193 colors-visible 193 xref 2 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.20ms tarjan 0.26ms scc-setup 0.24ms gather-xref 0.01ms xref-setup 0.00ms cleanup 0.10ms
04-12 14:33:07.965 D/Mono    (19787): GC_BRIDGE: Complete, was running for 40.95ms
04-12 14:33:07.965 D/Mono    (19787): GC_MAJOR: (LOS overflow) time 28.57ms, stw 31.27ms los size: 1024K in use: 109K

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
04-12 14:33:07.965 D/Mono    (19787): GC_MAJOR_SWEEP: major size: 4384K in use: 3043K

=================================================================
04-12 14:33:07.986 E/mono-rt (19787): /proc/self/maps:
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x75510af494):0x75510af484  60 0b 00 35 88 66 40 f9 08 01 00 b4 0a 01 40 79  `..5.f@.......@y
0x75510af494  a9 be 80 b9 5f 01 09 6b 8b 00 04-12 14:33:07.987 E/mono-rt (19787): 12c00000-52c00000 rw-p 00000000 00:01 22937                              /dev/ashmem/dalvik-main space (region space)_1024_1024 (deleted)

04-12 14:33:07.987 E/mono-rt (19787): 70a23000-70a3a000 rw-p 00000000 fe:01 458856                             /data/dalvik-cache/arm64/system@framework@boot.art
00 54 08 0d 09 8b  ...._..k...T....
0x75510af4a4  16 05 40 f9 d6 0a 00 b5 7f 02 00 b9 e6 67 ff 97  ..@..........g..
0x75510af4b4  e0 03 15 aa 2e 59 fe 97 96 66 40 f9 f6 01 00 b4  .....Y...f@.....

No native Android stacktrace (see debuggerd output).

=================================================================
	Managed Stacktrace:
=================================================================
domain required for stack walk=================================================================
04-12 14:33:07.987 E/mono-rt (19787): 70a3a000-70cbc000 rw-p 00000000 fe:01 458857                             /data/dalvik-cache/arm64/system@framework@boot-core-oj.art
04-12 14:33:07.987 E/mono-rt (19787): 70cbc000-70dc2000 rw-p 00000000 fe:01 458888                             /data/dalvik-cache/arm64/system@framework@boot-core-libart.art
04-12 14:33:07.987 E/mono-rt (19787): 70dc2000-70df7000 rw-p 00000000 fe:01 458895                             /data/dalvik-cache/arm64/system@framework@boot-conscrypt.art
04-12 14:33:07.987 E/mono-rt (19787): 70df7000-70e34000 rw-p 00000000 fe:01 459233                             /data/dalvik-cache/arm64/system@framework@boot-okhttp.art

04-12 14:33:07.988 E/mono-rt (19787): 70e34000-70e38000 rw-p 00000000 fe:01 459235                             /data/dalvik-cache/arm64/system@framework@boot-legacy-test.art
04-12 14:33:07.988 E/mono-rt (19787): 70e38000-70e7b000 rw-p 00000000 fe:01 459238                             /data/dalvik-cache/arm64/system@framework@boot-bouncycastle.art
04-12 14:33:07.988 E/mono-rt (19787): 70e7b000-70eb6000 rw-p 00000000 fe:01 459239                             /data/dalvik-cache/arm64/system@framework@boot-ext.art
04-12 14:33:07.988 E/mono-rt (19787): 70eb6000-717dd000 rw-p 00000000 fe:01 459243                             /data/dalvik-cache/arm64/system@framework@boot-framework.art
04-12 14:33:07.988 E/mono-rt (19787): 717dd000-71892000 rw-p 00000000 fe:01 459254                             /data/dalvik-cache/arm64/system@framework@boot-telephony-common.art
04-12 14:33:07.988 E/mono-rt (19787): 71892000-7189b000 rw-p 00000000 fe:01 459255                             /data/dalvik-cache/arm64/system@framework@boot-voip-common.art
04-12 14:33:07.988 E/mono-rt (19787): 7189b000-718a3000 rw-p 00000000 fe:01 459257                             /data/dalvik-cache/arm64/system@framework@boot-ims-common.art
04-12 14:33:07.989 E/mono-rt (19787): 718a3000-718c7000 rw-p 00000000 fe:01 459260                             /data/dalvik-cache/arm64/system@framework@boot-apache-xml.art
04-12 14:33:07.989 E/mono-rt (19787): 718c7000-718f3000 rw-p 00000000 fe:01 459263                             /data/dalvik-cache/arm64/system@framework@boot-org.apache.http.legacy.boot.art
04-12 14:33:07.989 E/mono-rt (19787): 718f3000-718f8000 rw-p 00000000 fe:01 459264                             /data/dalvik-cache/arm64/system@framework@boot-smartbondingservice.art
04-12 14:33:07.989 E/mono-rt (19787): 718f8000-718ff000 rw-p 00000000 fe:01 459269                             /data/dalvik-cache/arm64/system@framework@boot-sprengine.art
04-12 14:33:07.989 E/mono-rt (19787): 718ff000-71900000 rw-p 00000000 fe:01 459270                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.base-V1.0-java.art
04-12 14:33:07.990 E/mono-rt (19787): 71900000-71903000 rw-p 00000000 fe:01 459273                             /data/dalvik-cache/arm64/system@framework@boot-android.hidl.manager-V1.0-java.art
04-12 14:33:07.990 E/mono-rt (19787): 71903000-7190d000 rw-p 00000000 fe:01 459274                             /data/dalvik-cache/arm64/system@framework@boot-timakeystore.art
04-12 14:33:07.990 E/mono-rt (19787): 7190d000-71916000 rw-p 00000000 fe:01 459279                             /data/dalvik-cache/arm64/system@framework@boot-fipstimakeystore.art
04-12 14:33:07.990 E/mono-rt (19787): 71916000-71917000 rw-p 00000000 fe:01 459281                             /data/dalvik-cache/arm64/system@framework@boot-ucmopensslenginehelper.art
04-12 14:33:07.993 E/mono-rt (19787): 71917000-7191b000 rw-p 00000000 fe:01 459287                             /data/dalvik-cache/arm64/system@framework@boot-esecomm.art
04-12 14:33:07.993 E/mono-rt (19787): 7191b000-7191c000 rw-p 00000000 fe:01 459298                             /data/dalvik-cache/arm64/system@framework@boot-SemAudioThumbnail.art
04-12 14:33:07.994 E/mono-rt (19787): 7191c000-71956000 rw-p 00000000 fe:01 459316                             /data/dalvik-cache/arm64/system@framework@boot-knoxsdk.art
04-12 14:33:08.015 F/libc    (19787): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xbc in tid 19897 (pool-1-thread-1)

### Basic Information

- Version with issue:  VS 2019 16.0.1, Xamarin 16.0.0.515, Xamarin Android SDK 9.2.0.5, Xamarin Forms 3.6.0.293080
- Last known good version: VS 2017 15.9.11, Xamarin 4.12.3.83, Xamarin Android SDK 9.1.7.0, Xamarin Forms 3.6.0.293080
- IDE:  Visual Studio 2019
- Platform Target Frameworks: 
 
  - Android: 9.0  
 
- Android Support Library Version: 28.0.0.1 
- Nuget Packages:  NetStandard.Library, PCLStorage, Plugin.FirebasePushNotificaiton, RG.Plugins.Popup, RSSDP, SharpSerializer, SyncFusion (various packages V17.1.0.40), Toass.Forms.Plugin, Xamarin.Essentials, Xlabs.Forms

- Affected Devices:
Samsung S7
Android Emulator

**Comment by psirigiano** [comment]
We are getting the same exact thing... had to down grade back to 2017.

**Comment by Drutol** [comment]
Same here, not Forms app so I think that's something deeper in Xamarin.Android, had to revert to VS2017.

**Comment by georgeinva2004** [comment]
This was fixed when [https://github.com/xamarin/xamarin-android/issues/2920](url) was fixed.  Thank-you!!!!
