### ISSUE TITLE
[Bug] Unexpected Shell Route exception message needed

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#5909]
This exception is not acceptable, I think it shouldn't throw UnImplementedException because we preserve that for method implementation. It must throw Exception with clear message. It confused me  so I was like: GoToAsync is not implemented yet or what!? While the whole issue is about wrong routing.

https://github.com/xamarin/Xamarin.Forms/blob/105ded935340895273e184169c4c1dd4c23b5d81/Xamarin.Forms.Core/Shell/Shell.cs#L412

**Comment by PureWeen** [comment]
@MhAllan  a lot of this has been rewritten with the next 4.0 pre9 that's coming out.

Could you by chance provide a repro of the exception you are hitting above though? I'd like to make sure whatever scenario you are running into is accounted for

**Comment by MhAllan** [comment]
@PureWeen, All good, the Shell has lots of issues so I am waiting the next release and updated documentation.

**Comment by PureWeen** [comment]
@MhAllan can you by chance just provide your XAML for your shell, any routes you've registered, and the type of route you are trying to perform that are causing the exception?

**Comment by samhouts** [comment]
@MhAllan  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
