### ISSUE TITLE
Completed, Closed, etc for PushModalAsync

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#5913]
Hi,

It will be great if you add new events for PushModalAsync which wil be fired when the popup was closed, completed, error, etc.. just like the JQuery as an example..

Here is an example:

Navigation.PushModalAsync(new Signin()).Completed(
{
      run code when completed successfully...
}.Closed(
{
     run code when just closed (cancelled button)..
}

Thanks,
Jassim

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
