### ISSUE TITLE
[Enhancement] Shell ItemTemplate preserved Highlight parameter

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#5939]
## Summary
If we defined a DataTemplate for they ShellItems, we lost the Highlight with the isChecked parameter.

## API Changes
Not lost this behavior.

## Intended Use Case
To continue to show the current active page

**Comment by davidortinau** [comment]
Related to #4509

**Comment by Moltroon** [comment]
Perfect ! Thanks !
Good luck for the integration.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
