### ISSUE TITLE
[Bug, Previewer] Previewer will crash if it reaches any code casting Context to Activity

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#5943]
### Description

Any code that tries to do the following will crash with an invalid cast exception
```C#
(Activity)Context
```

Code like this will always return null

```C#
if(Context as Activity == null)
throw new Exception();
```

Will crash the previewer. In SR2 we replaced all these casts with an extension method that will always return null but it will still hit the second case in a few scenarios.

### Possible Alternatives

1) in the GetActivity code https://github.com/xamarin/Xamarin.Forms/blob/723f2de43980bf66989f4e7d40d12ad00b63d06a/Xamarin.Forms.Platform.Android/ContextExtensions.cs#L97 we instead return an interface. This way we can just create a mock of the Activity and what apis are code is calling so that it's able to continue to function

2) Is there a way to wrap the `com.android.layoutlib.bridge.android.BridgeContext` type that comes from the android designer with an Activity and then proxy the calls that need to be proxied back to the Bridge  Context. This would allow 3rd party libraries that need to cast to an activity to also continue functioning

**Comment by PureWeen** [comment]
pinging @garuma  and @TimBarham  in case they have any additional suggestions

**Comment by samhouts** [comment]
@PureWeen I think you hit all of these in #5955, yeah?
