### ISSUE TITLE
[Android] Picker dismissed with hardware back or click outside the modal cannot be re-opened 

### ISSUE THREAD

**Issue by ext-mayfran1** [xamarin/Xamarin.Forms#5945]
### Description
Pickers that are unfocused using hardware back button or by clicking outside the modal cannot be re-opened.

### Steps to Reproduce

1.  Open a picker
2.  Dismiss it using hardware back or by clicking outside the modal
3. Re-focus the Picker

### Expected Behavior
Modal re-opens

### Actual Behavior
The picker shows the "focused" visuals, but the modal does not open

### Project displaying issue
https://github.com/ext-mayfran1/XFPickerIssue

### Basic Information

- Version with issue: 3.6.0.293080
- Platform Target Frameworks: 
  - Android: 8.1, 9

Bug was introduced with https://github.com/xamarin/Xamarin.Forms/pull/4911
The dismiss event only hides the dialog, whereas the the NegativeButton actually kills it.
The added null check added to the OnClick therefore triggers if the dialog was dismissed.

**Comment by samhouts** [comment]
@ext-mayfran1 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ext-mayfran1** [comment]
Basic project showcasing the issue added

**Comment by PureWeen** [comment]
@ext-mayfran1 this looks like it's only an issue with nonappcompat

Can you switch to using appcompat?
https://montemagno.com/material-design-theming-for-xamarinforms-android/

**Comment by ext-mayfran1** [comment]
> @ext-mayfran1 this looks like it's only an issue with nonappcompat
> 
> Can you switch to using appcompat?
> https://montemagno.com/material-design-theming-for-xamarinforms-android/

We tried the non-appcompat version, but it causes quite a few issues in our app (many visual elements no longer working as expected), and the picker's look and feel is quite different...
