### ISSUE TITLE
CSS defined in App does not affect TitleView [Bug] 

### ISSUE THREAD

**Issue by SuperCorks** [xamarin/Xamarin.Forms#5956]
### Description
Styles defined in a CSS file and added to the `App`'s resource dictionary don't get applied to `TitleView` content.

### Steps to Reproduce

1. Create a simple css file (e.g. `#ViewTitle { color: white; }`
2. Add it to the `App`'s resources.
2. Add a `TitleView` to a page.
3. Style its content with the css.

### Expected Behavior
The styles added to the `App`'s resource dictionary should apply to the content of the `TitleView` in the css should apply to the elements of the title view.

### Actual Behavior
It don't
### Basic Information

- Version with issue: 3.6.x

### Reproduction Link
Here is a simple project:
[App1.zip (sorry no sln)](https://github.com/xamarin/Xamarin.Forms/files/3096351/App1.zip)

**Comment by SuperCorks** [comment]
This might be true of normal styles too. Haven't tested that.

**Comment by PureWeen** [comment]
If the style is defined on the content page is loads fine but ones defined in app.xaml don't work

I bet this same issue exists for the views loaded as part of shell as well (SearchHandler and FlyoutHeaderProperty)

**Comment by joemicmc** [comment]
This is still an issue in 5.0.0.2337 using the original steps to reproduce
