### ISSUE TITLE
[Xamarin.Forms][Android] Pressing Volume up/down hardware buttons on pickers opens them

### ISSUE THREAD

**Issue by boudomi1** [xamarin/Xamarin.Forms#5960]
### Description
When opening a picker one time, then dismissing it, pressing on hardware buttons for volume up or down, for example, will make the picker re-appear.

### Steps to Reproduce

1. Open the provided sample application
2. Tap on the picker to open it
3. Dismiss the picker
4. Press the volume up or the volume down button

### Expected Behavior
The volume adjusts

### Actual Behavior
The picker re-appears

### Basic Information

- Version with issue: 3.6.0.344457
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 7.1, 8.1, 9.0
- Android Support Library Version: None
- Nuget Packages: Xamarin.Forms, NETStandard.Library
- Affected Devices: Tested on 
    -Nexus 5 emulator (Running under android 7.1 and 9.0)
    -Zebra TC70X android device (Running under android 7.1 and 8.1)
    -OnePlus 3
Possibly all devices

### Reproduction Link
Barebone application with only Xamarin.Forms installed. A single page application with only a picker on the page:
https://drive.google.com/file/d/11OQQuKQL3vztjtSmpWBhqw5vH0e5ftzb/view?usp=sharing

**Comment by samhouts** [comment]
Interesting. That's not one of the keycodes we're looking for to trigger it. I wonder if it's an accessibility feature. The volume keys work again as expected when you remove focus from the picker.

https://github.com/xamarin/Xamarin.Forms/blob/533e13019129b298f775308cf1ef79655bc97a7a/Xamarin.Forms.Platform.Android/PickerManager.cs#L14

**Comment by StephaneDelcroix** [comment]
(closing manually as I forgot to reference the issue # in the squash commit message)
