### ISSUE TITLE
[Bug] Routing Not working, NotImplemented exception thrown

### ISSUE THREAD

**Issue by yadavvineet** [xamarin/Xamarin.Forms#5967]
I have followed standard instructions shown at
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell?tabs=android#navigation
and many other blogs which are on same lines. 
i have the following xaml head
```
<Shell xmlns="http://xamarin.com/schemas/2014/forms" 
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
       xmlns:local="clr-namespace:VinTest.Views"
       xmlns:infrastructure="clr-namespace:VinTest.Infrastructure;assembly=VinTest"
       RouteHost="vineetyadav.com"
       RouteScheme="app"
       Route="vintest"
       FlyoutBehavior="Flyout"
       Title="VinTest"
       x:Class="VinTest.AppShell"
       Navigating="AppShell_OnNavigating"
       x:Name="MainShell">
```

I added another page, Lets Say LanguageSelectorPage which is out of normal flow of page.
Added following route in App.xaml.cs
`Routing.RegisterRoute("changelanguage", typeof(LanguageSelectorPage));`

now from one of the menu i have the following command setup
```
ChangeLanguageCommand = new Command(() =>
            {
                (Application.Current.MainPage as newShell)?.GoToAsync(
                    $"app:///changelanguage", true);
                //MessagingCenter.Send(this, GlobalConstants.Commands.ChangeLanguageCommand,"");
            });
```

Also tried using the full name **app://vineetyadav.com/vintest/changelanguage** and **app://vineetyadav.com/changelanguage** but no resort

The **problem** is routing is not working. I tried to debug from original sources from Xamarin.forms (master) and the it seems that the in the following code:
![image](https://user-images.githubusercontent.com/7949851/56461457-20bbbd00-63d1-11e9-8f79-92711501a2b1.png)
problem occurs at code at line 106.While my shell route comes out to be vintest, the expectedShellRoute come out to be "AppShell1". This is returned from code
```
  public static string GetRoute(Element obj)
        {
            return (string)obj.GetValue(RouteProperty);
        }
```
I am not sure what the problem is, but because of this, i am not able to use the simple routing that is registered with Route.Register. 
Additionally if you dont use sources and use from the nuget package directly as well, in the line below, if i use await, i get the same notImplementedException thrown directly as well. 
```
ChangeLanguageCommand = new Command(async () =>
            {
                await (Application.Current.MainPage as newShell)?.GoToAsync(
                    $"app:///changelanguage", true);
                //MessagingCenter.Send(this, GlobalConstants.Commands.ChangeLanguageCommand,"");
            });
```

Can you please look into and assist.

I have updated all packages and on latest versions.

**Comment by PureWeen** [comment]
@yadavvineet can you try "changelanguage"

I have a repo here based on 4.0 pre9 
https://github.com/PureWeen/Gastropods

Where the global register route is working

**Comment by yadavvineet** [comment]
> @yadavvineet can you try "changelanguage"
> 
> I have a repo here based on 4.0 pre9
> https://github.com/PureWeen/Gastropods
> 
> Where the global register route is working

I need to check your repo, but for me even changing that does'nt work.
![image](https://user-images.githubusercontent.com/7949851/56473110-26260f80-6484-11e9-8b07-a6d84a5f288d.png)

I am on currently Xamarin.Forms v3.6.0.344457. 
@PureWeen you mentioned 4.0 pre9. Do you think that could be a problem, This is because i am referring the GA

**Comment by yadavvineet** [comment]
Ok, I updated to pre-release and the behavior is correct over there, can seemlessly route to different pages. Thanks for hint @PureWeen 

So this must be a bug for GA 3.6.x. If this is already included for next GA, probably can be closed.
