### ISSUE TITLE
[Bug] [Android] NullReferenceExcepion in Dispose of SwitchRenderer when creating derived custom renderer

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#5970]
### Description

https://github.com/xamarin/Xamarin.Forms/blob/998dc3534c7df17e4bda1a709c8f2f81039a2429/Xamarin.Forms.Platform.Android/Renderers/SwitchRenderer.cs#L59

No null check here, therfore when calling base.Dispose from custom renderer derived from SwitchRenderer NullReferenceException occurs.

- Version with issue: 3.6.0 SR3
- Last known good version: 3.6.0 SR2
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: 9.2
- Android Support Library Version: 28.0.0.1

**Comment by PureWeen** [comment]
@toomasz out of curiosity why are you inheriting from the non appcompat renderer?

This is the better renderer to use
https://github.com/xamarin/Xamarin.Forms/blob/998dc3534c7df17e4bda1a709c8f2f81039a2429/Xamarin.Forms.Platform.Android/AppCompat/SwitchRenderer.cs
