### ISSUE TITLE
Shell layout different between iOS 10 and later versions 

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#5971]
### Description

Layout with relation to the navigation area differs between versions.

### Steps to Reproduce

1. Run test 4684 in Control Gallery on iOS 10.
2. Run test 4684 in Control Gallery on iOS >10.

### Expected Behavior

Same layout.

### Actual Behavior

Parts of the content are not visible on iOS 10.

### Basic Information

- Version with issue: 4.0.0

### Screenshots

iOS 10:
![ios10](https://user-images.githubusercontent.com/538025/56478025-06cdb900-6469-11e9-9bdf-3e051774c6aa.png)

iOS 11:
![ios11](https://user-images.githubusercontent.com/538025/56478027-0df4c700-6469-11e9-8831-8273b51a5254.png)

**Comment by samhouts** [comment]
closed by #5990
