### ISSUE TITLE
[FeatureRequest] Resource not available via code when it's inside a MergedDicitionary

### ISSUE THREAD

**Issue by NickeManarin** [xamarin/Xamarin.Forms#5976]
### Description
It's not possible (at least I could not find any way of doing that) to get resources from a `MergedDictionary` via code.
In WPF we can use FindResource()/TryFindResource() to get resources from the app via code.

### Steps to Reproduce

1. Create a `ResourceDictionary` file like this one:

```
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                    xmlns:s="clr-namespace:System;assembly=netstandard">

    <Color x:Key="Color.Background">#301536</Color>
</ResourceDictionary>
```
2. Add the reference to the `App.xaml` like this:

`<ResourceDictionary Source="Resources/Colors/Dark.xaml"/>`

3. Try to access the resource:
`var color Application.Current.Resources.FirstOrDefault(f => f.Key == "Color.Background").Value as Color?;`

Also, when accessing `Application.Current.Resources.MergedDictionaries`, all merged dictionaries are empty, like the resources inside are not being detected.

If I try to access them using the dynamic resource notation, it works normally:

`{DynamicResource Color.Background}`

**Comment by pikausp** [comment]
`Application.Current.Resources.TryGetValue("ResourceKey", out var value)` works in my project.

**Comment by NickeManarin** [comment]
You are right, thanks.
I ended up creating a simple helper method:

    internal static Color TryGetColor(string key, Color fallback)
    {
        Application.Current.Resources.TryGetValue(key, out var color);

        return color as Color? ?? fallback;
    }

**Comment by ymebrugts** [comment]
For any type of resource use: 
```
    public static T TryGetResourceByName<T>(string resourceName) where T : class
        {
            Application.Current.Resources.TryGetValue(resourceName, out var value);
            return value as T;
        }
```

And then use:
```       var iconStyle = Helpers.TryGetResourceByName<Style>("MaterialIcons");```

**Comment by agat366** [comment]
Not quite perfect approach, but at least it works.
Thanks!

**Comment by AdrianoRochedo** [comment]
Very obscure !!
Please normilize this because  Application.Current.Resources[resourceName] should work in all cases !!
