### ISSUE TITLE
[GTK] Xamarin doesn't free memory

### ISSUE THREAD

**Issue by dario279** [xamarin/Xamarin.Forms#5977]
### Steps to Reproduce

1. Open project and launch

### Expected Behavior

Garbage collector should free memory after pop a page.

### Actual Behavior

Garbage collection doesn't free memory after pop a page.

### Basic Information

- Version with issue: All versions
- Platform Target Frameworks: 
GTK
[TestHMI.zip](https://github.com/xamarin/Xamarin.Forms/files/3105917/TestHMI.zip)

**Comment by knocte** [comment]
Originally reported in https://github.com/mono/gtk-sharp/issues/269

**Comment by amirvenus** [comment]
AFAIK, you cannot forcibly tell GC to collect your garbage. GC.Collect may or may not collection what we expect it to. But, I do see that there is a clear behavioural difference in GTK and iOS when calling GC.Collect after popping a page.

**Comment by knocte** [comment]
As explained in the original report (mono/gtk-sharp#269) this might be related to not releasing delegates from event handlers (so not related to GC actually).

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
