### ISSUE TITLE
[Bug] Shell Bottom Bar horizontal border 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#5988]
### Description

There is no styling option provided to set a shadow and/or top border on the bottom tab bar.

Most of the xamples on material.io are with a dark background, but here we see the white background treatment and can clearly see a border and shadow:

![image](https://user-images.githubusercontent.com/41873/56630145-da0ad480-6615-11e9-99e9-690913cf57c3.png)

https://material.io/design/components/bottom-navigation.html#implementation

https://material.io/develop/android/components/bottom-navigation-view/

This may be the wrong implementation, but going through the docs for bottom bar to the code link, you see this:

https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/bottomnavigation/BottomNavigationView.java#L672

### Expected Behavior

I can have a border and shadow.

### Actual Behavior

A white background results in no separation from the content of a white page.

### Basic Information

- Version with issue: 4.0-pre9

### Screenshots

![image](https://user-images.githubusercontent.com/41873/56630357-c4e27580-6616-11e9-9838-366b55aca6da.png)

### Reproduction Link

https://github.com/davidortinau/Straxa

**Comment by KhuongNtrd** [comment]
Cause' by always setting background for BottomNavigationView to ColorChangeRevealDrawable even when set Shell.TabBarBackgroundColor=White for all TabItem

[https://github.com/xamarin/Xamarin.Forms/blob/4.0.0/Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs#L64](https://github.com/xamarin/Xamarin.Forms/blob/4.0.0/Xamarin.Forms.Platform.Android/Renderers/ShellBottomNavViewAppearanceTracker.cs#L64)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
