### ISSUE TITLE
[Bug] Entry.TextChanged is fired when BindingContext changes

### ISSUE THREAD

**Issue by bruzkovsky** [xamarin/Xamarin.Forms#5993]
### Description

We were having troubles with our Entry controls, in that they would be cleared out of nowhere. Investigating further, we found that there was a TextChanged firing with an empty string when the BindingContext changed - which happens inside a ListView with cell reuse - , thus deleting the data. Also when trying the TwoWay binding mode, the value in the ViewModel will be set to an empty string.

The attached sample reproduces that the TextChanged and TwoWay binding is fired when changing the BindingContext. Why it sometimes fired with an empty string, we were not able to reproduce.

### Steps to Reproduce

1. Run the attached sample
2. Try the different buttons, to set the Text property or change the BindingContext
3. The TextChanged and setter of TwoWay binding will be fired when changing the BindingContext

### Expected Behavior
Setter will not fire, as the value is already coming from the ViewModel

### Actual Behavior
Setter fires, updating the value on the view model just because it was set as BindingContext

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[EntryTextChanged.zip](https://github.com/xamarin/Xamarin.Forms/files/3112126/EntryTextChanged.zip)

**Comment by PureWeen** [comment]
@bruzkovsky If I'm understanding the sample correctly the Text setter and property changed call is happening because it's using an object constructor to set the Text
```C#
 _vm.EntryViewModel = new EntryViewModel(_vm) { Text = "Text was set with new view model"};
```

Which is the same thing as doing

```C#
 _vm.EntryViewModel = new EntryViewModel(_vm) ;
_vm.EntryViewModel.Text = "Text was set with new view model";
```

If I change your code  to set the text via the constructor
```C#
   _vm.EntryViewModel = new EntryViewModel(_vm, "Text was set with new view model");

        public EntryViewModel(PageViewModel parentViewModel, string text = null)
        {
            _parentViewModel = parentViewModel;
            _text = text;
        }
```


Then  the Text setter doesn't fire when the binding context is changed
