### ISSUE TITLE
[Enhancement] Create header and footer for CollectionView

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#5998]
Creating this ticket for discussion on the header and footer implementation. Last night, I managed to create the header for iOS but ran into some difficulty. While the header for linear layout and vertical grid layout works, I got an exception thrown for horizontal grid layout (which I can't figure out why at the moment), which brings me to my next questions.

- Should there be support for supplementary views for the horizontal grid?
    - If so, are they laid out vertically or horizontally?

**Vertical**

![scroll](https://user-images.githubusercontent.com/16855542/56669311-909ea180-6676-11e9-8a04-69aa6125e597.png)

**Horizontal**

![scroll2](https://user-images.githubusercontent.com/16855542/56669784-4c5fd100-6677-11e9-894c-79b4fd6ba4da.png)

- How does Forms hope to achieve a UI pattern similar to [this](https://www.thorntech.com/2015/08/want-your-swift-app-to-scroll-in-two-directions-like-netflix-heres-how/)? The first thing that comes to my mind is to use a `CarouselView` as a `CollectionView` item, but is it okay to nest two `UICollectionViewController` instances?
- Will there be support for individual section headers?
- Should header and footer properties be part of `CollectionView` or `ItemsView`?

**_More on bullet point 1:_**

The first image doesn't make sense to me while we can achieve the second one with a combination of linear layout and `CarouselView`. So, going back to the first question, do we really want to support supplementary views for the horizontal grid?

**Comment by jcmanke** [comment]
If this were to be implemented, it should definitely be the first way.

**Comment by bmacombe** [comment]
I don't think you need the header/footer on horizontal...assuming the header/footer are fixed and always shown.  If they scroll in and out of view with the content items that could be different though.

**Comment by MhAllan** [comment]
No need, people can do that with TemplateSelector.

**Comment by adrianknight89** [comment]
@MhAllan You mean no need for the header and footer? I'm not sure if there is a way to make the cells sticky. Plus, I'd rather leverage existing native methods than create custom logic to do the same thing.

**Comment by ChasakisD** [comment]
The most common scenario where you cannot implement with DataTemplateSelector is when you have a vertical CollectionView with 2 columns and you want to add a header. With DataTemplateSelector every DataTemplate controls half of the width of the view. So for example adding a label using the selector will only expand through 1 column. Adding Header and Footer to the CollectionView should be considered a must!

**Comment by samhouts** [comment]
closed by #7237, #7094, #6948
