### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by elmarkos23** [xamarin/Xamarin.Forms#6001]
### Description
El master Menu no se renderiza y deja una pantalla en blaco, cuando se abre la aplicación nuevamente en la versión de android con la api 28

### Steps to Reproduce

1. instalar y abrir la app
2. cerra la app completamente
3. abrir nuevamente ya no se visualiza le master menu

### Expected Behavior
Que se visualice el menu maestro

### Actual Behavior
Muestra pantalla en blanco no genera catch

### Basic Information

- Version with issue: android api 28
- Last known good version: android api 27
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  SDK 12
  - Android: SDK 28
  - UWP:  no aplica
- Android Support Library Version: 
- Nuget Packages: ninguno
- Affected Devices: Samsung Galaxy S9, S9+

### Screenshots
Queda en blanco la pantalla y no se puede navegar, pantalla en blanco total

### Google Translate

Description

The master Menu is not rendered and leaves a blank screen, when the application is opened again in the android version with the api 28
Steps to Play

    install and open the app
    close the app completely
    open again the master menu is no longer displayed

Expected Behavior

That the master menu is displayed
Current Behavior

Blank screen shows no catch

Screenshots

The screen is blank and can not be navigated, total blank screen

**Comment by PureWeen** [comment]
@elmarkos23 can you attach a repro please? I tested this with a very simple master page

```

MainPage = new MasterDetailPage()
			{
				Detail = new NavigationPage(new ContentPage()) { Title = "Detail" },
				Master = new ContentPage() { Title = "Master" },
				Title = "Master",
				
			};
```

And then closed and re-opened the app on API 28
it worked fine for me

**Comment by elmarkos23** [comment]
Funciona en API 28 pero en los dispositivos Galaxy S9 no funciona, solo la primera vez y si se cierre y nuevamente se abre se queda en blanco.

`public ObservableCollection<MenuMenuItem> MenuItems { get; set; }
            
            public MenuMasterViewModel()
            {
                MenuItems = new ObservableCollection<MenuMenuItem>(new[]
                {
                    new MenuMenuItem { Id = 0, Title = "Inicio", Image="home.png" },
                    new MenuMenuItem { Id = 1, Title = "Mi Perfil" , Image="login.png"},
                    new MenuMenuItem { Id = 2, Title = "Califica tu Experiencia" , Image="califica_experiencia.png"},
                    new MenuMenuItem { Id = 3, Title = "Referir Contactos" , Image="referir_contactos.png"},
                    new MenuMenuItem { Id = 4,Title = "Cerrar Sesión" , Image="logout.png"}, 
                });
            }
            
            #region INotifyPropertyChanged Implementation
            public event PropertyChangedEventHandler PropertyChanged;
            void OnPropertyChanged([CallerMemberName] string propertyName = "")
            {
                if (PropertyChanged == null)
                    return;

                PropertyChanged.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
            #endregion`

**Comment by kingces95** [comment]
Can you please attach a `reproduction.zip` that contains `reproduction.sln`?

**Comment by samhouts** [comment]
@elmarkos23  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
