### ISSUE TITLE
[Enhancement] Add Color.ToHexString

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#6003]
## Summary

Add ToHexString method on the Color to make it easier to convert a Xamarin Forms Color back to a Hex String.  

## API Changes

```cs
public string GetHexString()
    {
        var red = (int)(R * 255);
        var green = (int)(G * 255);
        var blue = (int)(B * 255);
        var alpha = (int)(A * 255);
        var hex = $"#{alpha:X2}{red:X2}{green:X2}{blue:X2}";

        return hex;
    }
```

## Intended Use Case

anywhere that it makes sense to create a native color from hex string.

**Comment by PureWeen** [comment]
Code for this exists in the GTK project and ColorPicker
reusing or centralizing that code is probably useful when implementing this

**Comment by adrianknight89** [comment]
We have `FromHex()`. To align with this, the new method should be named `ToHex()` instead of `ToHexString()`.

**Comment by mzhukovs** [comment]
Would this go into Xamarin Essentials (i.e. [Color Converters](https://docs.microsoft.com/en-us/xamarin/essentials/color-converters?context=xamarin/xamarin-forms)) or Xamarin Forms directly?
