### ISSUE TITLE
[Enhancement, Android] Change ActionBarDrawerToggle in platform to be v7 not v4

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6004]
## Summary

Currently we can't set the drawable on ActionBarDrawerToggle to anything because the v4 version of it doesn't have an api for setting the drawable

https://github.com/xamarin/Xamarin.Forms/pull/4915/files#diff-adb24726a0c58c74e3fc99113a27e2dcR785

If we convert it to the v7 one then we can set the drawable

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
