### ISSUE TITLE
[Bug] CollectionView HorizontalList Not working without StackLayout Orientation

### ISSUE THREAD

**Issue by prasannapattam** [xamarin/Xamarin.Forms#6006]
### Description
I am showing a horizontal list using CollectionView. I want to show an array of strings in the horizontal list. I am using the below code and it is not showing any data in the code. For StackLayout, if I add Orientation="Horizontal", then I can see the horizontal list.

### Steps to Reproduce

1. Below is the code which is not outputting any data when the StackLayout Orientation is not mentioned

`            <CollectionView ItemsLayout="{x:Static ListItemsLayout.HorizontalList}">

                <CollectionView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>Overview</x:String>
                        <x:String>Personal Info</x:String>
                        <x:String>Timeline</x:String>
                    </x:Array>
                </CollectionView.ItemsSource>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout> 
                            <Label Text="{Binding .}"></Label>
                        </StackLayout>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
`

### Expected Behavior
No output

### Actual Behavior
Horizontal list of input strings

### Basic Information

- Version with issue:
- Last known good version: 4.0.0.304370-pre8
- IDE: VS 2019

**Comment by PureWeen** [comment]
I tested this on the latest 4.0.0 branch and it appears to be working.

Can you try on pre9?
If it doesn't work there then we will have a pre10 out soon that you can test on

![image](https://user-images.githubusercontent.com/5375137/56843197-c1d7c700-685a-11e9-8804-fe17bb51946a.png)
