### ISSUE TITLE
[Bug] Shadows not appearing on Android

### ISSUE THREAD

**Issue by azuken** [xamarin/Xamarin.Forms#6008]
### Description

All controls with `HasShadow` property aren't showing anymore shadow (Frame and Floating Action Button). Worked with 

### Steps to Reproduce

1. Use control with `HasShadow` property on Android

### Expected Behavior

Have shadow on the bottom of control

### Actual Behavior

No shadow

### Basic Information

- Version with issue: 3.6.0.344457
- Last known good version: 3.6.0.293080
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:  12
  - Android: 9
- Android Support Library Version: 28

### Screenshots

https://imgur.com/QJfE5EN

**Comment by PureWeen** [comment]
@azuken can you attach a sample please? Also we don't have a FAB so I'm curious what you are using

I tested with the following source code

```xaml
  <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="200"></RowDefinition>
                <RowDefinition Height="200"></RowDefinition>
                <RowDefinition Height="*"></RowDefinition>
            </Grid.RowDefinitions>
            <Frame Margin="20"  HeightRequest="200" WidthRequest="200" HasShadow="False" OutlineColor="Red" HorizontalOptions="Center">
                <Label Text="false" TextColor="Accent" />
            </Frame>
            <Frame Margin="20" Grid.Row="1" HeightRequest="200" WidthRequest="200"  HasShadow="True" OutlineColor="Red" HorizontalOptions="Center">
                <Label Text="true" TextColor="Accent" />
            </Frame>
        </Grid>
```

Or can you test the latest 4.0 pre9 to see if it looks ok for you on there?

**Comment by azuken** [comment]
https://imgur.com/a/fuCTXZV 

Here is a screenshot example of the problem.

We have fixed Floating Action Button shadow, it was because of `android:hardwareAccelerated` parameter in manifest. But Frame element is always without shadow

**Comment by samhouts** [comment]
@azuken  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by azuken** [comment]
I've created a new project with @PureWeen  code sample, Xamarins Forms 3.6.0.264807, shadow is working.
Same with 3.6.0.344457.

Is there any parameter in configuration that can affect this effect ?

**Comment by azuken** [comment]
After re-testing our actual development build, frame shadows appears again. It was `android:hardwareAccelerated` parameter. Sorry for the inconvenience.

**Comment by PureWeen** [comment]
No inconvenience! Thank you for reporting and following up with us.
