### ISSUE TITLE
[Enhancement] Ability to justify text for Label

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#6009]
## Summary
Word offers 4 options to align text, but Forms has 3.

![Capture](https://user-images.githubusercontent.com/16855542/56742367-35ce7e00-673a-11e9-91e6-29fbdeb7f9f6.PNG)

> When you justify text, space is added between words so that both edges of each line are aligned with both margins. The last line in the paragraph is aligned left.

It'd be great to have the ability to justify align text.

## API Changes

Possibly adding `TextAlignment.Justify`, but this would also be present for vertical alignment. If justify doesn't make sense for vertical alignment, we can perhaps introduce a platform specific or throw an exception when `Justify` is selected. I'm leaning towards the latter to not complicate how PS and existing alignment options work, but not sure what the team thinks.

**Comment by PureWeen** [comment]
It looks like iOS support this and Android recently added support

https://developer.android.com/reference/android/widget/TextView#setJustificationMode(int)

Ideally this would just be as simple as setting those :-)

**Comment by MathewLC** [comment]
Will this become availuable? It's seems like it's waiting for @PureWeen review it. @samhouts, which version will this become available? I found a scenario in my app that will need it.

**Comment by MathewLC** [comment]
@samhouts, it seems like this is stopped, can I work on this?

**Comment by Seuleuzeuh** [comment]
@MathewLC i've made a PR #7489 with a simple implementation, without response for now. 
You can comment mine, or we can discuss here for a better way to do it ? And obtain a validation of the team for the implementation @samhouts @PureWeen  ?

**Comment by MathewLC** [comment]
@Seuleuzeuh I though that it was inactive. But let's work together. What dou you think about rebasing it to keep up to date with master and after that, change the target branch to the last one(rigth now 4.4.0)? After that we can pin the team to go on with the review and tests.

**Comment by MathewLC** [comment]
Maybe it make more sense rebase to the last branch already.

**Comment by asadullahqmr** [comment]
A cool little hack I found to get justified text to display in your apps is to use HTML. This can be done in Forms through Web View like so:

In XAML:
`<WebView
                    HeightRequest="200"
                    Margin="10,5"
                    Source="{Binding AboutMeSource}"/>`

In ViewModel:
`AboutMeSource = new HtmlWebViewSource
            {
                Html = "<html>" +
                    "<body  style=\"text-align: justify;\">" +
                    String.Format("<p>{0}</p>", User.AboutMe) +
                    "</body>" +
                    "</html>"
            };`

It's important to note that setting the horizontal and vertical options to fill and expand for the web view doesn't actually allow the web view to be displayed. That's why you need to set the height request.

If you need a dynamic height request, then just bind to the text's length and use a converter to determine how much height you need to fit all of the label.

**Comment by MathewLC** [comment]
Really good tip. Maybe we can use the label itself to display HTML now that we have this functionality.

**Comment by jrahma** [comment]
This is important especially for Arabic language +1

**Comment by ymebrugts** [comment]
We are on 4.7 right now yet this was tagged for 4.6? When can we expect to use this?

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
