### ISSUE TITLE
[Android]  New ImageSource needs to intelligently invalidate Elements

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6010]
### Description
https://github.com/xamarin/Xamarin.Forms/pull/4915/commits/665961b0785d42edb8c1bb089a4fa7d9992306f3

The intent of  the invalidation was to handle scenarios where images are being loaded post layout but as is it's causing the layout to thrash. A basic page with a few images was calling invalidatemeasure about 900 times with these invalidation vs the normal 8 without those.

Commenting the code out will probably mean that in certain cases when loading images from the web they currently won't layout correctly or if the image is too slow to load

**Comment by samhouts** [comment]
closed by #6062
