### ISSUE TITLE
[Bug] (Shell, Android) Shell.Current.GoToAsync 2 levels from root causes root page so flicker in at transition

### ISSUE THREAD

**Issue by mrbrl** [xamarin/Xamarin.Forms#6016]
### Description
Xamarin.Form Shell on Android
navigating between 2 pages registered with Routing.RegisterRoute causes the root page to appear during navigation transition.

 
 Shell.Current.GoToAsync 2 levels from root causes root page so flicker in at transition
### Steps to Reproduce

1. 
[Straxa-master.zip](https://github.com/xamarin/Xamarin.Forms/files/3120099/Straxa-master.zip)

2. Register 2 routes for pages (page1 and page2) that are not defined on the shell.xaml structure , with Routing.RegisterRoute

3. from shell root page, Shell.Current.GoToAsync to registered route/page 1 - navigation is ok

4. from page1 , Shell.Current.GoToAsync to registered route/page 2

5. from page2, navigate back

### Expected Behavior
4. navigate to page 2 smoothly
5. navigates to page 1 

### Actual Behavior
4. root page appears for an instant, then page 2 appears
5. navigates to root page

### Basic Information

- Version with issue: xamarin.forms 4.0.0.346134-pre9
- Last known good version: n/a ( the stack implementation on pre9 differs from pre8 as it does not exist, but up to root (null) / current page

- IDE: visual studio 2019 16.0.1 (win)
- Platform Target Frameworks: 
  - iOS: n/a
  - Android: any
  - UWP:  n/a
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

see attached project to reproduce with information in-code

**Comment by PureWeen** [comment]
@mrbrl  good find I checked a fix in here

https://github.com/xamarin/Xamarin.Forms/pull/6025

though I'm not sure if what I fixed addresses what you want to do

When you call
```C#
await Shell.Current.GoToAsync($"end");
```

are you hoping that gets added to the stack? or that it removes
```
await Shell.Current.GoToAsync($"detail?id={item.Id}");
```

first and then adds "end" ?

**Comment by mrbrl** [comment]
@PureWeen 
re:  When you call 'await Shell.Current.GoToAsync($"end");' are you hoping that gets added to the stack? or that it removes.
I hope to get it added to the stack so we'll have a stack with 3 items: root, page1, page2 (and keep on adding as we navigate further).

shell.xaml definition could accept along the line of the below to allow tracking to an infinite combination of navigation, tabs, and why not flyouts while we are at it...

<FlyoutItem FlyoutIcon="iconXamarin.png" Title="Home" Style="{StaticResource SecondaryShell}">
        <ShellContent Route="level0" ContentTemplate="{DataTemplate local:Level0Page}"> 
            <ShellContent Route="level1" ContentTemplate="{DataTemplate local:Level1Page}"> 
                 <ShellContent Route="level2" ContentTemplate="{DataTemplate local:Level2Page}"> 
                    <ShellContent Route="level3" ContentTemplate="{DataTemplate local:Level3Page}"/>
                </ShellContent>
            </ShellContent>
        </ShellContent>
    </FlyoutItem>

<FlyoutItem Route="tabsandwich" Title="Tab Sandwich" FlyoutIcon="iconXamarin.png" Style="{StaticResource TertiaryShell}">
        <Tab Route="tab1" Title="tab2" Icon="iconXamarin.png">
            <ShellContent Route="level0" ContentTemplate="{DataTemplate local:Level0Page}"> 
                <ShellContent Route="level1" ContentTemplate="{DataTemplate local:Level1Page}"> 
                    <ShellContent Route="level2" ContentTemplate="{DataTemplate local:Level2Page}"> 
                        <Tab Route="tab1onLevel2" Title="tab2" Icon="iconXamarin.png">
                            <ShellContent Route="level3" ContentTemplate="{DataTemplate local:Level3Page}"/>
                        </Tab>
                        <Tab Route="tab1onLevel2" Title="tab1" Icon="iconXamarin.png">
                            <ShellContent Route="tab1onLevel2_Level0" ContentTemplate="{DataTemplate local:Level3Page}">
                                <ShellContent Route="level1" ContentTemplate="{DataTemplate local:Level1Page}"/> 
                            </ShellContent>
                        </Tab>
                         <Tab Route="tab2onLevel2" Title="tab2" Icon="iconXamarin.png">
                            <ShellContent Route="tab2onLevel2_Level0" ContentTemplate="{DataTemplate local:Level3Page}">
                            </ShellContent>
                        </Tab>
                    </ShellContent>
                </ShellContent>
            </ShellContent>
        </Tab>
        <Tab Route="tab2" Title="tab2" Icon="iconXamarin.png">
            <ShellContent Route="updates" Title="Updates" Icon="iconXamarin.png" ContentTemplate="{DataTemplate local:UpdatesPage}" />
        </Tab>
    </FlyoutItem>

**Comment by PureWeen** [comment]
> I hope to get it added to the stack so we'll have a stack with 3 items: root, page1, page2 (and keep on adding as we navigate further).

Awesome that's how it will work after my PR for this gets checked in

> shell.xaml definition could accept along the line of the below to allow tracking to an infinite combination of navigation, tabs, and why not flyouts while we are at it...

It will eventually. Currently routes can't get stacked but they will be able to soon

> This would completely remove the need for route registration in code, as long as all the possible combinations are being defined within that map. and that would help shell make sense of what to do in all cases.

Yes!!! We want to allow people to register all of this in the XAML if they need to and not have to worry about global routes if they don't want to
