### ISSUE TITLE
[Info] Understand XF release cycle

### ISSUE THREAD

**Issue by matteopiccioni** [xamarin/Xamarin.Forms#6018]
Hello,
I'd like to understand how works release cycle for this project.
For my need I am using x.f. 4.0-pre9 and when I meet a bug I'd like to know when the next release is planned.

For example, now I see in [Project](https://github.com/xamarin/Xamarin.Forms/projects) tab that there is:
- Sprint 152 2019-04-20 to 2019-05-10
- vNext+1 (master)
- vNext (4.0.0)
- vCurrent (3.6.0)
...

Of course:
 - vCurrent is the current release...
 - vNext (4.0.0) is the current preview version (4.0-pre9)

My question:
What is 'Sprint 152 2019-04-20 to 2019-05-10' ? It means that  between 2019-04-20 and 2019-05-10 will be released a new version ? 
Witch version...4.0 Beta 10 or 3.60 service release 4?

vNext+1 will be the next vNext as soon as 4.0.0 will be released?

Thanks!

**Comment by PureWeen** [comment]
> What is 'Sprint 152 2019-04-20 to 2019-05-10' ? 

The sprint is how we figure out how much work to schedule. So we just look at engineers available and then assign a set of tasks during the sprint. We typically try to do an official release every two sprints. So we spend one sprint getting a release to PRE then it can saturate for another sprint before we release

> vNext+1 will be the next vNext as soon as 4.0.0 will be released?

Right so once we officially release 4.0.0 then vNext+1 will become 4.1.0 and vNext+1 will become 4.2.0
