### ISSUE TITLE
[Bug] [macOS] [iOS] ListView does not handle transparent backgrounds correctly

### ISSUE THREAD

**Issue by GalaxiaGuy** [xamarin/Xamarin.Forms#6021]
### Description

**macOS** - ListView does not support transparent background (or any alpha less than 1). It appears as if an extra white background is behind it.

**macOS, iOS** - Additionally, cells seems to have their background set to the background of the background of the ListView by default, again causing problems when alpha is less than 0.

### Steps to Reproduce

Create a`LlistView` with a background color that has an alpha less than 1, with something behind that is not white:

```csharp
    public class MainPage : ContentPage
    {
        public MainPage()
        {
            BackgroundColor = Color.Red;
            Content = new ListView
            {
                Margin = new Thickness(20),
                BackgroundColor = Color.FromRgba(0, 0, 1, 0.5), 
                ItemsSource = new string[] { "Row 1", "Row 2", "Row 3" }
            };
        }
    }
```

### Expected Behavior

Whatever is behind the `ListView` is visible.

### Actual Behavior

The `ListView` appears to have an additional white background.

### Basic Information

- Version with issue: 3.6.0.344457

### Additional Information

I tried to recreate this in the `DynamicViewGallery` (by adding an additional control for changing the page background color) and could not get it to happen for some reason.

Despite that, I think the problem may be the background of the `NSScrollView` the `NSTableView` wrapped in.

### Screenshots

![](https://github.com/GalaxiaGuy/xamarin-forms-macos-listview/raw/master/screenshots/macos.png)
![](https://github.com/GalaxiaGuy/xamarin-forms-macos-listview/raw/master/screenshots/ios.png)
![](https://github.com/GalaxiaGuy/xamarin-forms-macos-listview/raw/master/screenshots/android.png)

### Reproduction Link

https://github.com/GalaxiaGuy/xamarin-forms-macos-listview
https://github.com/GalaxiaGuy/xamarin-forms-macos-listview/archive/master.zip

**Comment by jcmanke** [comment]
Seems related to #5503

**Comment by GalaxiaGuy** [comment]
Following the discussion here:
https://github.com/xamarin/Xamarin.Forms/pull/4002

It seems the iOS cell background behavior was left this way intentionally.

**Comment by kingces95** [comment]
@GalaxiaGuy Does #4002 resolve this issue? Looks like you can use a platform specific to set a default background color. Changing the default would break someone so to make the background transparent we ask the developer to be explicit.

**Comment by GalaxiaGuy** [comment]
#4002 fixes the cell background color on iOS. Something similar will be needed for macOS.

It doesn't affect the ListView background color on macOS.

My PR #6005 attempts to address the background color on macOS, without touching anything on iOS, or the cells on either platform.
