### ISSUE TITLE
[Enhancement] VAST Compliant MediaPlayer Needed

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#6035]
Need MediaPlayer that can work with VAST ads. Something other than Azure Media Player because that is a javascript for Azure only.

**Comment by pauldipietro** [comment]
Let's keep this functionality request in #1692 rather than a separate issue.

**Comment by egeneblaza** [comment]
Hi may ask is there a video player that is vast comaptible for xamarin forms?
