### ISSUE TITLE
Issue using template with ShellContent

### ISSUE THREAD

**Issue by xeg12** [xamarin/Xamarin.Forms#6037]
I have a Shell with several ShellSections.
One has 3 ShellContents each with the same Page but with different flags passed in on create to provide different selections ("All", "Selected" and "Unselected").

If I add a new item using a separate page, I want to refresh the 3 ShellContent pages on returning from the NewItem page.

Since changing to use a ContentTemplate for performance reasons there is no ShellContent.Content so no way to pass a message to the pages.

I cannot set a global flag to say "refresh" as there appears to be no event which will always fire on returning from the NewItem page (Appearing only seems to fire once).
I cannot use the Navigated event in the shell as there appears to be no way to access the ShellContent.Content from there.

This needs a solution as I can see this being a common issue.

I am on the latest Xamarin Forms 4 preview as of 28/4/2019

**Comment by kingces95** [comment]
Could you please attached a zipped solution file reproduction? Thanks.

**Comment by samhouts** [comment]
@xeg12  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
