### ISSUE TITLE
[Enhancement] Added visual state hovered to Image buttons.

### ISSUE THREAD

**Issue by dberroa** [xamarin/Xamarin.Forms#6041]
## Summary
I would like my image button to scale up and change color when hovered over in xamarin forms. As of now, we only have a pressed and normal state. For UWP, I'm thinking this occurs when moving the mouse over. In android and iOS, it can occur when pressing and holding the button and then the user can either lift the finger on the button to trigger or slide off to cancel. This is normal behavior with native image buttons.

## API Changes

Adding a visual state to the image button.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
