### ISSUE TITLE
[Enhancement] Launch/Splash Screen in Xamarin.Forms

### ISSUE THREAD

**Issue by dfoulk** [xamarin/Xamarin.Forms#6042]
## Summary
I understand why we currently have to create launch/splash screens in the native projects. However- I would still love for the brilliant folks behind Xamarin to solution a Xamarin.Forms launch/splash screen API that doesn't require us to implement these screens manually on each platform.

## API Changes

I believe this would require an update to the Xamarin.Forms project template in Visual Studio. Perhaps this new template could include *Resources/LaunchScreen.storyboard* in the iOS project and *LaunchScreenActivity.cs* in the Android project that could be modified via a *LaunchScreen.xaml* file in the Xamarin.Forms library/project?

I really don't know the answer to this as it is a difficult implementation to design considering that if a XForms user does not wish to use a launch/splash screen- these changes may not be welcomed/wanted/needed.

**Example LaunchScreenPage.xaml**
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<LaunchScreenPage xmlns="http://xamarin.com/schemas/2014/forms"
                                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                                  x:Class="MyApp.LaunchScreen"
                                  BackgroundColor="Indigo">
    <StackLayout VerticalOptions="Center"
                           HorizontalOptions="Center"
                           Spacing="15">
        <Image Source="foo-logo.png" />
        <Label Text="Foo App" />
    </StackLayout>
</LaunchScreenPage>
```

Instead of including the native files by default; you could provide something similar to what UWP does in this documentation:
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/add-a-splash-screen

## Intended Use Case
This feature would be used by many of us to create splash screens for our apps more easily. The level of customization doesn't need to be anything special. Even if we could add an image (that would be centered on the screen) and define the background color of the screen- we'd be happy.

Currently, adding splash screens requires Xamarin (native) knowledge that many Xamarin.Forms users do not possess. Plus, last time I looked, there were no up-to-date topics in the documentation (that worked) to show us how to add these screens.

Thank you for your time and consideration. I know it's a big ask- but this would be an awesome addition that would meet the needs of the majority of our needs (I think).

**Comment by jrahma** [comment]
Yeah this will be great but I will add an option to add Video and Animated GIF to the LaunchScreenPage

**Comment by varyamereon** [comment]
Now that the ability to edit storyboards in the Windows version of Visual Studio has been removed, something like this would be particularly important as otherwise there is no way of creating a Launch Screen on iOS with using Visual Studio on the Mac.

**Comment by jfversluis** [comment]
There are already improvements for the splash screen in .NET MAUI so please go check that out. If you would like to see more there, please open proposals on that repository. For Xamarin.Forms nothing much will be added/improved in this area anymore.

Thanks!
