### ISSUE TITLE
[Feedback] I think this is a Xamarin XAML BUG. Custom XAML converter doesn't work with more that one implemented interface.

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#6043]
### Description

<p>I have a custom converter for Xamarin XAML in a Xamarin Forms IOS application.  It implements IValueConverter and works fine. However, if I have it implement another interface in addition to IValueConverter, the converter is not executed anymore. There are no errors thrown, it just ignores the converter all together (hence breakpoints in the converter are never hit). 

More:  The other interface in this case is IMarkupExtension. It's a converter and a markup extension (that's another story, this is about is it a bug). 
            Once I remove the IMarkupExtension interface declaration, it works fine. This is reproducible.

So, should a converter stop working if it implements additional interfaces other than IValueConverter?</p>
<a href="https://developercommunity.visualstudio.com/content/problem/545319/i-think-this-is-a-xamarin-xaml-bug-custom-xaml-con.html">View on Developer Community</a>
<br>To find diagnostic information, see the <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/855028">original linked feedback ticket</a>.

### Source

[859221](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/859221)

**Comment by jcmanke** [comment]
See also: [Xamarin Forums thread](https://forums.xamarin.com/discussion/155696/bug-i-think-this-is-a-xamarin-xaml-bug-tell-me-what-you-think)

**Comment by kingces95** [comment]
@jcmanke Do you still have your reproduction handy? If so could you attach it? Else we'll recreate after looping through issues with attached reproductions. Thanks for fielding the question!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
