### ISSUE TITLE
[Bug] Xamarin.GTK Opacity and semi-transparent colors does not work

### ISSUE THREAD

**Issue by jinek** [xamarin/Xamarin.Forms#6045]
### Description
Setting opacity to 0.1 on any xamarin.forms element does not have effect.
Setting not "FF" byte in any color attribute of xamarin.forms element does not have effect
- Version with issue: 4.0.0.346134
- IDE: JetBrains Rider
- Platform Target Frameworks: GTK sharp 2.12.0.0
- Nuget Packages: Xamarin.Forms, Xamarin.Forms.GTK

### Screenshots
![image](https://user-images.githubusercontent.com/10516222/56926007-f94fa900-6ad0-11e9-9d41-3728cb5a988f.png)

**Comment by GalaxiaGuy** [comment]
I believe it is not supported in GTK 2:
https://github.com/mono/xwt/issues/386

**Comment by jinek** [comment]
> 
> 
> I believe it is not supported in GTK 2:
> [mono/xwt#386](https://github.com/mono/xwt/issues/386)

May be makes sense to consider using this fork https://github.com/GtkSharp/GtkSharp which supports GTK3
