### ISSUE TITLE
[Android] CollectionView items retain ripple effect even when unselectable

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#6051]
### Description

Only affects APIs of Lollipop and up.

Once a CollectionView item has been selected, it retains the ripple tap effect even when selection is no longer enabled.

### Steps to Reproduce

1. In Control Gallery, navigate to CollectionView Gallery -> Selection Galleries -> Selection Mode
2. Change to SelectionMode "Single"
3. Select an item
4. Change to SelectionMode "None". The item should be de-selected.
5. Tap on the previously selected item. 
6. Tap on another item that was never selected.

### Expected Behavior

Tapping on the previously selected item should have the same effect as tapping on an item which was never selected.

### Actual Behavior

The previously selected item will retain the ripple effect.

### Basic Information

- Version with issue: 4.0.0

### Screenshots

![leftover_ripple_effect](https://user-images.githubusercontent.com/538025/56971825-2d55b900-6b27-11e9-987a-7b92856121af.GIF)

**Comment by adrianknight89** [comment]
If you scroll down and back up, then tapping on the previously selected item will lose the ripple effect.

**Comment by samhouts** [comment]
closed by #7615
