### ISSUE TITLE
[Enhancement] DataTemplateSelector for single content control

### ISSUE THREAD

**Issue by elcosmelco** [xamarin/Xamarin.Forms#6052]
## Summary
Right now DataTemplateSelectors are supported for Listviews, but in UWP I often use a DataTemplateSelector on a ContentControl to create a detail view for items that have varying types and properties. It would be nice if there was something similar for Xamarin Forms out of the box.

## API Changes
I do not feel qualified to suggest anything here. 

## Intended Use Case
Reasonably self-explanatory I think?

**Comment by bmacombe** [comment]
@elcosmelco  this is pretty easy to build yourself if you need that functionality.  Below is an example.  I'm pretty sure I just stole how it worked from the ListView source

@davidortinau @pauldipietro @samhouts Any objections to a PR for a similiar control to be added to the core framework?  I'm thinking review the current code for ListView and CollectionView for how they handle data templates and selectors and either replicate it or see if it can be extracted into a shared helper?

~~~c#
public class ASItemControl : ContentView
    {
        public DataTemplate ItemTemplate
        {
            get => (DataTemplate) GetValue(ItemTemplateProperty);
            set => SetValue(ItemTemplateProperty, value);
        }
        public static readonly BindableProperty ItemTemplateProperty = BindableProperty.Create(nameof(ItemTemplate), typeof(DataTemplate), typeof(ASItemControl), propertyChanged: ItemTemplateChanged);

        public object Item
        {
            get => (object) GetValue(ItemProperty);
            set => SetValue(ItemProperty, value);
        }
        public static readonly BindableProperty ItemProperty = BindableProperty.Create(nameof(Item), typeof(object), typeof(ASItemControl), null, propertyChanged: SourceChanged);

        private static void ItemTemplateChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var control = bindable as ASItemControl;
            control.BuildItem();
        }

        private static void SourceChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var control = bindable as ASItemControl;
            control.BuildItem();
        }

        public bool HideOnNullContent { get; set; } = false;

        protected void BuildItem()
        {
            if( Item == null )
            {
                Content = null;
                return;
            }

            //Create the content
            try
            {
                Content = CreateTemplateForItem(Item, ItemTemplate, false);
            }
            catch
            {
                Content = null;
            }
            finally
            {
                if( HideOnNullContent )
                    IsVisible = Content != null;
            }
        }

        public static View CreateTemplateForItem(object item, DataTemplate itemTemplate, bool createDefaultIfNoTemplate = true)
        {
            //Check to see if we have a template selector or just a template
            var templateToUse = itemTemplate is DataTemplateSelector templateSelector ? templateSelector.SelectTemplate(item, null) : itemTemplate;

            //If we still don't have a template, create a label
            if (templateToUse == null)
                return createDefaultIfNoTemplate ? new Label() {Text = item.ToString()} : null;

            //Create the content
            //If a view wasn't created, we can't use it, exit
            if ( !(templateToUse.CreateContent() is View view)  ) return new Label() { Text = item.ToString() }; ;

            //Set the binding
            view.BindingContext = item;

            return view;
        }
    }

**Comment by jcmanke** [comment]
Perhaps an `ControlTemplateSelector` class and property that would be added to `TemplatedView` and `TemplatedPage`?

**Comment by bmacombe** [comment]
Yeah, I haven't dug into TemplatedView or Page much, but that could work.  I was thinking create a draft PR and then put it out there for review and suggestions.  Just want to make sure the team is on board with the feature before investing much time into it.

**Comment by andreinitescu** [comment]
I had a similar request here #4127 many months back

**Comment by bmacombe** [comment]
@andreinitescu I remember that issue now.  I wonder if we leave ContentView alone and just create a sub class it might be more acceptable.  I agree that any developer with a WPF background will likely miss this control and that seems to be the main target audience for Forms.

 @StephaneDelcroix Would you mind expanding on why the Forms team isn't interested in adding a contact such as this?

**Comment by mdonogma** [comment]
what's happening with this? Need a better way to create custom controls using xaml in xamarin forms.

**Comment by elcosmelco** [comment]
FYI, to work around this without making a new control I use `BindableLayout` where the `ItemsSource` has a converter that makes a list of 1 item out of my bound property. The `BindableLayout `has a `ItemTemplateSelector`. I feel dirty every time I use it though (which is pretty often)

It looks like this:
`<StackLayout BindableLayout.ItemsSource="{Binding SelectedItem, Converter={StaticResource ToListOfOne}}" BindableLayout.ItemTemplateSelector="{StaticResource MenuItemTemplateSelector}"/>`

**Comment by maexsp** [comment]
Same interest here. Please put it onto the Roadmap.

**Comment by AdamDiament** [comment]
I'm very keen for this, it will save me a fair amount of code duplication, and will help with the tension between wanting to write maintainable code vs performant. My use case is this basically:

```
<StackLayout>
    <CommonElement1></CommonElement1>
    <UncommonElementNeedingADataTemplateSelector></UncommonElementNeedingADataTemplateSelector>
    <CommonElement2></CommonElement3>
    <CommonElementx...></CommonElementx...>
</StackLayout>
```

I know that I could use a content template to achieve this, but working with binding context inside the content template is a real verbosity headache that I would rather avoid. I could also utilize the "IsVisible" property and have multiple uncommon elements in the layout, and only show one based on a binding. With the is visible approach all my Value convertors and bindings still get evaluated which I don't want to take the performance / maintenance hit for.

Another idea could be a concept similar to "ng-if" in the angular world - whereby instead of isvisible there would be a way to completely remove an element at run time from the Xaml tree structure based on a binding, rather than just hiding it and still having to evaluate all its properties / bindings even whilst invisible.

**Comment by AdamDiament** [comment]
For potential implementors, @bmacombe 's implementation works darn well.

**Comment by fbd-ss** [comment]
+10 for bmacombe's solution, such an essential item, i would have thought this would have been introduced ahead of the upgraded list view.

**Comment by bmacombe** [comment]
I'll try to get a pr into the community toolkit with it.  I doubt forms will add at this point with Maui.

**Comment by jfversluis** [comment]
@bmacombe I realize this is loooong time ago! We definitely welcome it in the .NET MAUI Community Toolkit and from there see if we can bring it to .NET MAUI.

We have an issue open on the .NET MAUI repo, we will use everything here as input for that when time comes. If this still something you'd like to see, make sure to upvote it in the linked issue right above here.

This won't be happening for Forms anymore. Thanks!
