### ISSUE TITLE
[macOS, iOS] Label with multiline text shows single line after LineBreakMode change

### ISSUE THREAD

**Issue by slakul** [xamarin/Xamarin.Forms#6055]
### Description

A Label is able to show multiline text, but sometimes it shows only the first line of the text.

In macOS when LineBreakMode is changed from the initial value NoWrap to WordWrap, then the Label shows the first line of the text. When the initial value of LineBreakMode is WordWrap, then changing its value to NoWrap and back does not change its appearance.

In iOS when LineBreakMode initial value is NoWrap, then the Label shows the first line of the text. Changing its value to NoWrap and back does not change its appearance.

The attached sample application reproduces the issue. There are two Labels with multiline text. Click "Change" to change the value of LineBreakMode of the Labels.

### Steps to Reproduce

1. Run the attached sample
2. Click "Change" many times
3. The first label changes in macOS and is always truncated in iOS

### Expected Behavior

A Label should not change.

### Actual Behavior

A Label changes.

### Basic Information

- Version with issue: 4.0.1.383393-nightly (macOS), 3.6.0.344457 (iOS)
- Last known good version:
- IDE: Visual Studio for Mac 8.0.4
- Platform Target Frameworks: 
  - Xamarin.iOS:  12.8
  - Xamarin.Mac: 5.8
- Nuget Packages:
- Affected Devices: macOS Mojave (10.14.4), iPhone XR (12.2 - simulator)

### Screenshots

![bugLabel1](https://user-images.githubusercontent.com/14055723/56993433-bd821580-6b9c-11e9-8ee0-cc445ebc8f15.png)

![bugLabel2](https://user-images.githubusercontent.com/14055723/56993435-c1159c80-6b9c-11e9-893a-c0d2ba87892e.png)

![bugLabel-iOS](https://user-images.githubusercontent.com/14055723/56993438-c2df6000-6b9c-11e9-8499-fd0034bfd1aa.png)

### Reproduction Link

[TestAppLabel.zip](https://github.com/xamarin/Xamarin.Forms/files/3133147/TestAppLabel.zip)

**Comment by kingces95** [comment]
Verified. Changing wrapping has no effect on iOS.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
