### ISSUE TITLE
WebGL Content from file:// urls not supported in iOS

### ISSUE THREAD

**Issue by chaosifier** [xamarin/Xamarin.Forms#6058]
### Description
There seems to be no way to enable WebGL content support from offline file in current version of Xamarin.IOS. 

In android, I was able to bypass the restriction by enabling AllowFileAccessFromFileURLs and AllowUniversalAccessFromFileURLs as suggested in a stackoverflow post. But for iOS, there seems to be no such APIs or resources.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
