### ISSUE TITLE
[Android] UI Test 4597 fails on API 19

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#6061]
### Description

The UI test for issue #4597 does not pass on API 19 devices.

### Steps to Reproduce

1. Open Control Gallery
2. Navigate to Issue 4597
3. Follow the on-screen instructions

### Expected Behavior

All of the images disappear.

### Actual Behavior

One of the images does not disappear.

### Basic Information

- Version with issue: 4.0.0

### Screenshots

![2019-05-01_12-41-22](https://user-images.githubusercontent.com/538025/57035110-7e8ca800-6c0e-11e9-93c0-cdcd63079310.png)

**Comment by PureWeen** [comment]
this will be fixed by this branch

https://github.com/xamarin/Xamarin.Forms/tree/image_load_fixes

**Comment by samhouts** [comment]
closed by  #6062
