### ISSUE TITLE
[Enhancement] Visual Material - Nice if Visual property could be set from ControlTemplate

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#6063]
## Summary
`Visual="Material"` has to be set in the XAML of each page or view.  That's very repetitive and a lot of scrubbing when making changes. Not to mention flies in the face of using `ControlTemplate`s to define all the common look & feel aspects of a page for example.

## API Changes

It would be nice if we could set the `VIsual` property in a `ControlTemplate` so all pages/views using that template automatically inherit the use of `Material` instead of having to scrub through countless existing views or having to add one more "don't forget" to the todo list when making more views/pages.

**Comment by jcmanke** [comment]
I thought it could be inherited? So if you set it on your Application everything that can be Material will be.

**Comment by tlhintoq** [comment]
@jcmanke 
If that's the case the documentation doesn't reflect that, nor tell you how to do it at an application level.  The docs only show/say that it has to be set _on each view_. And I tried with a `ControlTemplate` but the property isn't valid at that level.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual#consume-material-renderers
> Consume the material renderers by **setting the Visual property to Material on any pages that should adopt the Material Design rules**. For more information, see Consume material renderers.

**Comment by jcmanke** [comment]
From that link:

> Applications can opt into using the material renderers by setting the `VisualElement.Visual` property on a page, layout, or view, to `Material`
> The `Visual` property is defined in the `VisualElement` class, with views inheriting the `Visual` property value from their parents. Therefore, setting the `Visual` property on a `ContentPage` ensures that any supported views in the page will use that Visual.

So I was partially incorrect, you can't set it on the Application (because it doesn't inherit from VisualElement) but if you set it on your MainPage presumably it would inherit all the way down.

**Comment by tlhintoq** [comment]
@jcmanke 
> but if you set it on your MainPage presumably it would inherit all the way down.

Ok.  But what if you have 100 pages?  You have to go add it to all of them?  Then the boss says 
> We don't like it after all, so turn it off
Now you have to go back through all the pages and remove it?  (find/replace would probably handle that)
Expanding on that... You can only use this in Android 9.  So if you have templates for Android 9 they can use this... And releases on earlier OSes wouldn't have it.  And a selector based on the OS.  Otherwise... you have to... what... add it to 100 pages when deploying to OS 9... then take it out every time you compile for Android 8?  Surely that can't be the expectation upon every developer wanting to adopt this. (And I won't call you Shirley)

So it still seems like something that should be able to be put in a `ContentTemplate` for your pages.   Then its added/removed from one place to work on all pages using that template.  Isn't that sort of the idea of a `ContentTemplate`?  As well as not having to manually set up every page with the same repetitive markup?  Or am I missing something?

**Comment by jcmanke** [comment]
I would probably implement it with an implicit style:

	<Application>
		<Application.Resources>
			<Style
				ApplyToDerivedTypes="True"
				TargetType="Page">
				<Setter Property="Visual" Value="Material"/>
			</Style>
		</Application.Resources>
	<Application>

Very easy to remove, or change the Visual to a new one if/when one is added.

Or when I say set it on the MainPage, I mean this:

	Application.Current.MainPage = new NavigationPage(new StartPage())
	{
		Visual = VisualMarker.Material
	};

Every page in the NavigationStack will have that NavigationPage as its Parent, so those pages would inherit the Material visual and all of their content in turn. Remove that one property setter and once again, the removal would be applied to all children pages.

> You can only use this in Android 9. So if you have templates for Android 9 they can use this... And releases on earlier OSes wouldn't have it. And a selector based on the OS.

Like most things in Android, Material Design in backwards compatible. You must have the TargetSdkVersion set to 9.0 or higher, but it will work on devices running at least Android 5.0 (probably actually even lower, but that's the lowest version I target on my apps).

**Comment by tlhintoq** [comment]
@jcmanke 

> Or when I say set it on the MainPage, I mean this:
> ```csharp
> Application.Current.MainPage = new NavigationPage(new StartPage())
> {
>     Visual = VisualMarker.Material
> };
> ```
> Every page in the NavigationStack will have that NavigationPage as its Parent, so those pages would inherit the Material visual 

Oh.... Ooohhhh.... I never actually realized that the `NavigationPage` became the `Parent` to all the other pages pushed.  In my mind `NavigationPage` was always a _mechanism_ and not a UI element with children.  But now I see it... yeah... hindsight is always 20:20 as they say.  **Thanks for that boot-to-the-head of concept recognition**.

That's really nice, because that allows for use of pre-processor directives for deployments on different OS versions etc.  That's really terrific.

I hope you consider writing an addendum to that documentation I linked earlier.  I'm sure I'm not the only person who would benefit from being shown the right way to implement it app-wide - and not have 10,000 people all banging on 100 XAML pages because of poor documentation.

**Comment by TheBaileyBrew** [comment]
Why not just create a base page that's devoid of just about everything, then base all your 100+ pages on the base?

This is my BasePage:

    <ContentPage
    x:Class="App.Pages.BasePage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
    ios:Page.UseSafeArea="true"
    Visual="Material">
    <ContentPage.Content />
</ContentPage>

Then instead of using ContentPage on all the other pages, I use BasePage passed in as an xmlns class to build all my other pages, thus inheriting Material (and anything else I set) on all my inheriting from the base. I have 47 pages, and each one has Material appearance with this method... Just a thought.

**Comment by tlhintoq** [comment]
I'm a big fan of inheritance and base classes and I push it on my tutorial site.
But I don't have the final say in the work environment.  They don't want want to use custom base classes for the pages and controls, in part because it breaks all the visual designing tools and previewers out there.  As soon as you're trying to preview  `MyCustomPage:MyPageBase` it all goes pearshaped.

It is a property - and as such it should be available from the control template.

**Comment by jfversluis** [comment]
Hey all, thanks for the idea and input here! I'm afraid this won't be happening for Xamarin.Forms anymore. Thank you!
