### ISSUE TITLE
What is the point of the PinType enum?

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#6065]
```
public enum PinType
{
	Generic,
	Place,
	SavedPin,
	SearchResult
}
```

This enum has been in Xamarin.Forms.Maps forever, but does absolutely nothing. It is not so much as referenced in any of the MapRenderer classes on any platform. I understand Xamarin's hesitance to remove public things, but if it has never been used for anything maybe it would be okay here. Are there any known third-party packages that extend Xamarin.Forms.Maps and use the PinType enum for something?

**Comment by kingces95** [comment]
Prob just vestigial code from before the dawn of Microsoft. I doubt we'd remove it just because it's public and all it could do would be to break someone. We could/should mark it obsolete.

**Comment by CliffAgius** [comment]
Happy to do this but whats the verdict?

Remove or Mark Obsolete?

I'm thinking Mark for now and maybe remove later.

**Comment by jcmanke** [comment]
Like @kingces95 said, mark obsolete. Nothing public ever seems to actually be removed from Xamarin.Forms.

Alternatively, we could ascribe it some function, like changing the pin color based on the enum value. That's what I did when I first started writing custom map renderers.

**Comment by jfversluis** [comment]
I don't think we're going to do anything about this anymore. I think it does a visual thing on iOS or at least it did. At this point for Xamarin.Forms, we're not going to touch it anymore. Thanks!
