### ISSUE TITLE
[Enhancement] Flex Layout Base Line Alignment

### ISSUE THREAD

**Issue by dlebee** [xamarin/Xamarin.Forms#6071]
## Summary

To align text with different fonts using FlexLayout in xamarin isn't possible due to the lack of base line option.

![image](https://user-images.githubusercontent.com/36390643/57075072-5b640600-6cab-11e9-909a-0e348edb25fa.png)

In the CSS Specification there is something called align-items: baseline; which aligns the text at the baseline of the font regardless of their font-size.

## API Changes

In the Assembly Xamarin.Forms.Core.dll add BaseLine to the enum FlexAlignItems.

This would make it possible to align text like so:

![image](https://user-images.githubusercontent.com/36390643/57075342-25735180-6cac-11e9-9a1c-9661e181a9c7.png)

How its done in HTML/CSS

```html
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

<STYLE>
	p {
		margin: 0 0;
	}
</STYLE>

<div style="display: flex; flex-direction: row; align-items: baseline;">
	<span style="font-size: 100px; font-family: 'Roboto'; background: gray; line-height: auto; font-width: 200px;">AAA</span>
	<span style="font-size: 50px; font-family: 'Roboto'; background: blue; line-height: auto; font-width: 75px;">Bris mechanique</span>
</div>
```

## Intended Use Case

Aligning text properly at the base line without hacking flex layouts.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
