### ISSUE TITLE
[Bug] CollectionView (iOS) using horizontal grid does not display last column of uneven item count

### ISSUE THREAD

**Issue by tetowill** [xamarin/Xamarin.Forms#6077]
### Description

If you set CollectionView to a horizontal grid layout with multiple rows (span) and define a width for your items the last column gets dropped if it's not a full column. So if the last column doesn't have an item for each row it will not be displayed. If you set the CollectionView orientation to vertical this is not an issue, the last uneven row will be displayed.

I found that setting ItemSizingStrategy to MeasureFirstItem fixes this issue and the last column of uneven items will then show. Also, if you do not set a width for your items then the last uneven row will show. 

I tested this in iOS and Android in Xamarin.Forms 4.0.0.346134-pre9 and only see this bug in iOS.

### Steps to Reproduce

1. Set up a CollectionView with Orientation set to Horizontal and Span set to more than 1.
2. Set up the ItemTemplate and define a width for each item.
3. Set the ItemsSource with a number of items that will give you an uneven final column. In the attached example project the Span is set to 3 and the ItemsSource is a collection of 14 items which leaves the final column at 2 items instead of 3 for a full column.

### Expected Behavior

The last column of items with a set width in a CollectionView using a horizontal grid layout should display regardless of the number of items in that column.

### Actual Behavior

The last column of items with a set width in a CollectionView using a horizontal grid layout does not display if the items to not full all the rows.

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.346134-pre9
- Last known good version:
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 8.1.0 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.0.0.346134-pre9
- Affected Devices: Tested on iOS Xr and 6s Simulator, and Android Nexus 6P

### Reproduction Link

[CollectionViewHorizontalGridBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3139506/CollectionViewHorizontalGridBug.zip)

**Comment by seansparkman** [comment]
I can confirm this issue as well.

**Comment by kingces95** [comment]
Using VS I get...  `2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5045,5): error MSB3541: Files has invalid value "C:\Users\Chris\Downloads\CollectionViewHorizontalGridBug\CollectionViewHorizontalGridBug\CollectionViewHorizontalGridBug.Android\obj\Debug\81\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.`

**Comment by kingces95** [comment]
Hm. On master I can see the last column. Is this the expected behavior? Maybe we fixed this.

![Image from iOS](https://user-images.githubusercontent.com/4120386/57116518-617cd580-6cf1-11e9-9706-92a95d5b8012.jpg)

**Comment by tetowill** [comment]
@kingces95, seeing that last column is the expected behavior, but that photo looks like an Android device. I only noticed this bug on iOS. When I test on Android I also see the last column, but in the iOS simulator I that last column does not show.

**Comment by seansparkman** [comment]
![2019-05-03_12-13-32-PM](https://user-images.githubusercontent.com/991351/57154077-934b7600-6d9d-11e9-8526-1e8f7cb651c6.png)

**Comment by tetowill** [comment]
Figured I may as well mention this again as well. The last column will show in iOS if you set `ItemSizingStrategy` to `MeasureFirstItem`, but when it's left to default or set to `MeasureAllItems` the last uneven column does not display.

**Comment by Jiang-Junjie** [comment]
Chaning to `MeasureFirstItem`, it works!
