### ISSUE TITLE
[Android] rework Image Renderer to use new image loading code used by buttons

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6091]
### Description

Code introduced by #4915 should replace the code in `ImageViewExtensions` for loading bitmap images. 

There are a lot of UI Tests you can use to test this with but Bugzilla51173 is a good one to vet that it all works ok after changes

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
