### ISSUE TITLE
[Bug, Shell] RouteHost with capital letter throws exception

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6093]
### Description
I am not sure whether this is a bug or feature request. I spend lots of time on fixing a bug. It turns out that the RouteHost name in my project has capital letters. The error message is:

**System.InvalidOperation Exception has been thrown
Shell CurrentItem should not be null**

The error message is not at all helpful in pointing to the code causing the error. It will be helpful if the xaml editor shows the error during write time. Or compiler point to the actual code in error message at compile time.
Otherwise there could be a way to allow the developers to define RouteHost in any Case.

### Basic Information

- Version with issue: Xamarin.Forms-pre10
- IDE: Visual Studio for Mac

- Affected Devices:iOS and Android

**Comment by PureWeen** [comment]
We're going to just remove RouteHost for now from Shell as it serves no functional purpose currently 

https://github.com/xamarin/Xamarin.Forms/pull/6081
