### ISSUE TITLE
[Bug, Shell] Allow users to always show the Flyout Icon even if they have a page stack

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6095]
### Description
Navigation from Flyout hides FlyoutIcon and replace it with a back button

### Steps to Reproduce

 In the Repro Project select one of the flyoutitems. Than navigate from it by clicking on a listview item or clicking on  add button of the toolbar. 

### Expected Behavior
The Back Button should be placed beside FlyoutIcon. The Bottom TabBar should remain visible.  What I want is to show TabBar and FlyoutIcon throughtout the every screen of the app. This makes navigation easy for the user.
Developer can explicitly hide TabBar and FlyoutIcon by navigation to new NavigationPage. 
### Actual Behavior
The Back Button replaces FlyoutIcon and Bottom TabBar is hidden.
### Basic Information

- Version with issue:Xamarin.Forms- pre10
- IDE:Visual Studio for Mac

- Affected Devices:iOS and Android

### Reproduction Link
[NavigationRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3145401/NavigationRepro.zip)

**Comment by PureWeen** [comment]
@HobDev when you click add they all disappear because the ADD button is doing a Modal push
```

            await Navigation.PushModalAsync(new NavigationPage(new NewItemPage()));
```

if you change that to just do a push then you will still have tabs and a backbutton.

As far as
```
The Back Button should be placed beside FlyoutIcon.
```

I'll mark this issue as an enhancement. I could see the ability to add multiple header bar icons and via that enabling this behavior

**Comment by alanag13** [comment]
@PureWeen FWIW, I expected disabling the back button with `BackButtonBehavior.IsEnabled` to do this, if you're still thinking about implementation details of this. I could try to put down a PR if that approach sounds good to you.

**Comment by PureWeen** [comment]
@alanag13 yes! Here are some related issues as well with BackButtonBehavior

https://github.com/xamarin/Xamarin.Forms/issues/5744
https://github.com/xamarin/Xamarin.Forms/issues/6307

One thing I'm still not clear on is why the original design opted to have a "BackButtonBehavior" and it's not just all attached properties?  Regardless :-) 

Setting something on the BackButtonBehavior should only effect that one thing you changed it shouldn't demolish all of the functionality 

Effectively there's like the "DefaultBackButtonBehavior" which should just get merged into the BackButtonBehavior the user creates.

Anything the user didn't specify a value for should just use default behavior. 

Right now this is all very problematic so if you have some thoughts for a PR that would be awesome!!

**Comment by PureWeen** [comment]
@alanag13 have you started on this work by chance?

**Comment by alanag13** [comment]
Hey @PureWeen, not quite yet but still happy to. I currently have 2 PRs open here that I need to address feedback on, and will probably have 2 more by the end of the day that address some bug fixes I needed for a project I'm working on, but I can look at this after all that.

**Comment by PureWeen** [comment]
@alanag13 No rush! I was going to try and get something together for the BackButton this week but just wanted to make sure you hadn't invested time into it yet.

**Comment by AdamDiament** [comment]
I think I have a similar problem - I'm navigating to a page not represented in the visual heirarchy using a command:

`await Shell.Current.GoToAsync($"/CustomerDetail?customer={jsonCustomer}")`
From a parent page called "Jobs" which is represented in the visual heirarchy as a flyout item.

The route for CustomerDetail is not in a flyout option but instead is registered in the constructor of my shell subclass mainpage like this

 `Routing.RegisterRoute("CustomerDetail", typeof(CustomerDetailPage));`

The customerdetail page loads fine from the command but I see a back button when I go there, not the flyout. Additionally when I exit the customerdetail page via the flyout (by swiping from the left to show it ) and go to another page, then open the flyout again and click the flyout item for Jobs, I am sent back to the customer detail page, not the jobs page. What I want is to always see the flyout icon on all pages. Effectively to register a global route that will not create a navigation stack, but without being forced to show it as an option in my flyout menu - is this possible?

**Comment by AdamDiament** [comment]
I have a workaround for now if you're interested, it's not pretty but it works. Add to the constructor of your page.
`            Shell.SetBackButtonBehavior(this, new BackButtonBehavior
            {
                IconOverride = "Threebar.png",
                IsEnabled = false,
                Command = new Command(() =>
                {
                    for (var index = 0; index < Shell.Current.Navigation.NavigationStack.Count; index++)
                    {
                        Shell.Current.Navigation.PopAsync();
                    }

                    Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;
                })
            });

![ThreeBar](https://user-images.githubusercontent.com/6513834/63719755-562c5780-c856-11e9-9b2b-b3186620effb.png)

`

**Comment by bizmonger** [comment]
I'm running into the same issue. My flyout icon just isn't reflecting actual navigation.
```

            Routing.RegisterRoute(nameof(HomePage)           , typeof(HomePage));
            Routing.RegisterRoute(nameof(DeliveryRequestPage), typeof(DeliveryRequestPage));
            Routing.RegisterRoute(nameof(RegistrationPage)   , typeof(RegistrationPage));
            Routing.RegisterRoute(nameof(WelcomeApplicant)   , typeof(WelcomeApplicant));

            Routing.RegisterRoute(nameof(ErrorPage)          , typeof(ErrorPage));

            Navigating += (s, _) => {

                var sender = s as Shell;
                var item   = sender.CurrentItem;

                if (item.Title != "Home")
                     FlyoutIcon = "Back.png";

                else FlyoutIcon = "HamburgerMenu.png";
            };
```

**Comment by AdamDiament** [comment]
Hi @PureWeen is the feature idea to be able to see both the back arrow and the menu icon at the same time still planned for development? It would be really useful in my app. Thanks!

**Comment by GnanaPriyaNamasivayam** [comment]
@samhouts ,

In my case, i need to show FlyoutItems only when i tap HamburgerIcon but not through swiping left to right. Do you have any solution for this for Android & iOS

**Comment by Jakar510** [comment]
When I try to replace the icon, as a temporary fix, the new icon isn't rendered, and it solid white.

`Xamarin.Forms.Shell.SetBackButtonBehavior(page, new BackButtonBehavior()
			{
				IconOverride = "browse",

				Command = new Command(() =>
					{
						Xamarin.Forms.Shell.Current.FlyoutIsPresented = true;
					})
			} );`

**Comment by ymebrugts** [comment]
I would like to use this as well. I'd like to use GoToAsync() with the flyoutmenu still visible and maybe even with the backbutton visible as well.

**Comment by demoh2019** [comment]
+1

**Comment by demoh2019** [comment]
> У меня есть обходной путь, если вам интересно, это некрасиво, но работает. Добавьте в конструктор своей страницы.
> 
> ```
> Shell.SetBackButtonBehavior(this, new BackButtonBehavior
>             {
>                 IconOverride = "Threebar.png",
>                 IsEnabled = false,
>                 Command = new Command(() =>
>                 {
>                     for (var index = 0; index < Shell.Current.Navigation.NavigationStack.Count; index++)
>                     {
>                         Shell.Current.Navigation.PopAsync();
>                     }
> 
>                     Shell.Current.FlyoutIsPresented = !Shell.Current.FlyoutIsPresented;
>                 })
>             });
> ```
> 
> ![ThreeBar](https://user-images.githubusercontent.com/6513834/63719755-562c5780-c856-11e9-9b2b-b3186620effb.png)

swipe doesn't work after clicking

**Comment by pabloat81** [comment]
> Hi @PureWeen is the feature idea to be able to see both the back arrow and the menu icon at the same time still planned for development? It would be really useful in my app. Thanks!

HI. I see this is old. I am new to xamarin. I need to be able to do a back and have the flyout menú button visible. I cant see anywhere how to do this. Is posible now?

**Comment by ymebrugts** [comment]
> > Hi @PureWeen is the feature idea to be able to see both the back arrow and the menu icon at the same time still planned for development? It would be really useful in my app. Thanks!
> 
> HI. I see this is old. I am new to xamarin. I need to be able to do a back and have the flyout menú button visible. I cant see anywhere how to do this. Is posible now?

Yes this is possible. 

Example xaml: 

```
<ToolbarItem Text="" x:Name="Menu" Clicked="Menu_Clicked">
    <ToolbarItem.IconImageSource>
        <FontImageSource
            FontFamily="{StaticResource MaterialFont}"
            Glyph="{StaticResource Hamburger}"
            Size="32"
            
            />
    </ToolbarItem.IconImageSource>
</ToolbarItem>
```

Example code behind (although you should really do this with proper MVVM commands 


```
        private void Menu_Clicked(object sender, EventArgs e)
        {
            Shell.Current.FlyoutIsPresented = true;
        }
```

The material font should be loaded into the app before. To start out I'd suggest making it a text button first saying "MENU" so that you can add the hamburger icon after it works.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
