### ISSUE TITLE
[Material]: `Xamarin.Forms.Material.Android` is missing from the Android Solution 

### ISSUE THREAD

**Issue by dotMorten** [xamarin/Xamarin.Forms#6097]
### Description
The `Xamarin.Forms.Material.Android` is missing from the Android specific solution:
https://github.com/xamarin/Xamarin.Forms/blob/master/.Xamarin.Forms.Android.sln
This causes the build to fail to build because it can't find it.

### Steps to Reproduce

1. Open `Xamarin.Forms.Material.Android.sln` from a clean build
2. Build
3. Observe build error

### Expected Behavior
Newly cloned repo builds on first try

### Actual Behavior
Build output:
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Forms.Material, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018: File name: 'Xamarin.Forms.Material.dll'
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1350,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

### Basic Information

- Version with issue: Master branch
- Last known good version: ?
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
Yeah, we don't really use the sln files that start with `.`. I'll ping @kingces95 to see if he wants to update or delete those. For now, I suggest avoiding those and use the full sln file. Thanks!

**Comment by dotMorten** [comment]
These projects are really useful for quickly building when you're just focused on a single platform and don't want to worry about having all the dependencies needed to build the entire stack. So I'd prefer you fix them rather than delete them.

Also perhaps wait on closing the issue once they have been fixed or deleted?

**Comment by samhouts** [comment]
@dotMorten They are useful! However, they get out of date very quickly. However, VS 2019 has a great option that we recommend you try: https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019 (thanks @StephaneDelcroix for pointing it out to me!)
