### ISSUE TITLE
Rework LogicalChildren on Element to better represent visual vs logical children

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6106]
### Description
Titleview was the first version of this but Shell introduced a lot of cases where you will attach a View to an element and it should inherit a lot of features of being a child to that element (css, binding, etc..) but the child should not be drawn by the element

This PR 
https://github.com/xamarin/Xamarin.Forms/pull/6082

Starts the idea but only gets it about 80 percent there

ShellSection also uses this concept
https://github.com/xamarin/Xamarin.Forms/blob/383fc0d6b71bf5ea807257a0191b66d8899f44aa/Xamarin.Forms.Core/Shell/ShellSection.cs#L173

By differentiating between Items (visual children) and LogicalChildren (things that are just part of a section)

But this idea needs to be better standardized across the framework.

The other advantage here is that it will allow control developers an easy hook point to implement the same behavior. They can attach logical elements to pages or elements and our Framework will auto propagate css, binding, etc.. to those without actually trying to render them

**Comment by jfversluis** [comment]
I think this has seen some effort in .NET MAUI, let's focus on this there!
