### ISSUE TITLE
[Bug] Autofocus is not available in the Xamarin forms 

### ISSUE THREAD

**Issue by psatheesh18** [xamarin/Xamarin.Forms#6111]
### Description
Xamarin IOS has autofocus which is achieved by using the UIaccessibility.PostNotification .But Xamarin Forms has no such like to achieve the autofocus .

### Steps to Reproduce

1. N/A

### Expected Behavior
Autofocus the UI Element or any for xamarin Forms

### Actual Behavior
It is available in the xamarin IOS but not available in the xamarin forms .
### Basic Information

- Version with issue:  All versions
- Last known good version: N/A
- IDE: Visual Studio 15.9.1
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android:N/A  
  - UWP: N/A  
- Android Support Library Version: 
- Nuget Packages: N/A
- Affected Devices: N/A

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by samhouts** [comment]
@psatheesh18 in 4.0.0-pre9, we introduced Accessibility TabIndex (#3989), which lets you set the order in which elements should receive focus by setting TabIndex. Does this work for your purposes? Thanks!

**Comment by samhouts** [comment]
@psatheesh18  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
