### ISSUE TITLE
[Bug] Dynamically not able to set accessibility text using AutomationProperties.SetName

### ISSUE THREAD

**Issue by psatheesh18** [xamarin/Xamarin.Forms#6114]
### Description
Automation.setname not working for dynamically adding the new text for accessibility

### Steps to Reproduce

1. Setting the automation.setname dynamically for the same UIelement. 
2. Run the sample file 
3. Once it deployed to the device or emulator press the button it will show the error i have mentioned

### Expected Behavior
Dynamically automationproperties.setname to be changed for android in xamarin forms.
### Actual Behavior
AutomationId can be set only once. I have tried with setting up the AutomationProperties.SetName but it was not working ,So i have tried with device specified using switch case .So i need to use automationid for android device to setup accessibility .
### Basic Information
I need to change the accessibility text randomly to provide accessibility in the android .
- Version with issue:  Xamarin.Forms 2.3.3 and above
- Last known good version: 
- IDE: Visual Studio 15.9.9
- Platform Target Frameworks: 
  - iOS: Nil 
  - Android: All versions 
  - UWP: Nil  
- Android Support Library Version: 
- Nuget Packages:Xamarin.Forms 2.3 and above
- Affected Devices: All Android devices

### Screenshots
![image](https://user-images.githubusercontent.com/36506007/56019516-77b2f980-5d22-11e9-961d-1f5315779c72.png)

### Reproduction Link

[sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3152191/sample.zip)

**Comment by samhouts** [comment]
@psatheesh18 Your sample worked for me. On launch, the Button reads "Sample. Button. Sample. Double tap to activate." Then I double-tapped to trigger the Click command. Then I tapped again on the button, and it reads "Clicked. Button. SampleClicked. Double tap to activate." Is that not what you experience? Thanks!

**Comment by samhouts** [comment]
@psatheesh18  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
