### ISSUE TITLE
[Enhancement] Support multiple Shells in a single app

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#6120]
## Summary

See #6073 and #5928 for scenarios where customers are attempting to use multiple Shells in a single app.

Opening this issue to collect further use cases that will support this effort.

**Comment by aktxyz** [comment]
I have been using 2 shells and it seems to be working fine ... is there some lurking issue here that I may run into?  
- shell1 - unlogged in area, tab bar options specific to pre-login features
- shell2 - logged in area, tab bar options specific to logged in features

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
