### ISSUE TITLE
[Enhancement] LineBreak

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#6122]
## Summary
https://github.com/xamarin/Xamarin.Forms/pull/5136, but fully implemented.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
