### ISSUE TITLE
[Bug] Change of BackgroundImage PropertyType from string to FileImageSource causes Build Errors in Rg.Plugins.Popup

### ISSUE THREAD

**Issue by inforithmics** [xamarin/Xamarin.Forms#6123]
### Description

In Preview Release 4.0.0 Pre 10 the BackgroundImage was changed from string to FileImageSource (and was obsoleted).

https://github.com/xamarin/Xamarin.Forms/releases/tag/beta-4.0.0-pre10.1

Checkin
https://github.com/xamarin/Xamarin.Forms/pull/4915

Now the Release Compilation fails on iOs with following message:

(_CompileToNative target) -> 
  MTOUCH : error MT2101: Can't resolve the reference 'System.String Xamarin.Forms.Page::get_BackgroundImage()', referenced from the method 'System.Void Rg.Plugins.Popup.Animations.Base.FadeBackgroundAnimation::Preparing(Xamarin.Forms.View,Rg.Plugins.Popup.Pages.PopupPage)' in 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. 

It means it doesn't find the BackgroundImage with the string PropertyType.

### Steps to Reproduce

1.  Make new Xamarin project.
2.  Add Rg.Plugins.Popup nuget package
3.  Add following linker file (To simulate usage).

<linker>

```
    <assembly fullname="Rg.Plugins.Popup">
      <namespace fullname="Rg.Plugins.Popup.Animations.Base" />
      <type fullname="Rg.Plugins.Popup.Animations.Base.*" />
    </assembly>
```

4. Compile in Release Mode

### Expected Behavior
It does compile

### Actual Behavior
It doesn't Compile

### Basic Information

- Version with issue: 4.0.0 Pre Release 10
- Last known good version: 4.0.0 Pre Release 9
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.2
- Nuget Packages: Rg.Plugins.Popup 1.1.5.188

### Reproduction Link
[App30.zip](https://github.com/xamarin/Xamarin.Forms/files/3155959/App30.zip)

**Comment by PureWeen** [comment]
this was an oversight on our part and will be fixed here
 https://github.com/xamarin/Xamarin.Forms/pull/6133

before the 4.0 official release

**Comment by dansiegel** [comment]
It was a known issue that this was going to break downstream packages. That is why the change was a breaking change... the answer is not to revert but for Rg Plugins to update.

**Comment by samhouts** [comment]
@dansiegel We try very hard not to break ABI compatibility. We made the property obsolete to give libraries time to evolve without hard crashes for their end users. Changing the property type was definitely an accident. 😅
