### ISSUE TITLE
[Bug] CollectionView doesn't reflect changes in an ObservableCollection itself

### ISSUE THREAD

**Issue by b-straub** [xamarin/Xamarin.Forms#6126]
### Description

CollectionView doesn't  reflect changes for the ObservableCollection itself, whereas changes in the content are reflected.

### Steps to Reproduce

Run the attached sample project from either iOS simulator or device. 
Tap on a row, CollectionView does update.
Tap on clear, CollectionView doesn't update.

Both the items and the collection are implementing the INotifyPropertyChanged interface.

- Version with issue:
4.0.0 Pre Release 10
- IDE:
VS Mac
- Platform Target Frameworks:
  - iOS:  12.2
- Nuget Packages:
4.0.0 Pre Release 10
- Affected Devices:
All

### Reproduction Link

[CollectionViewChallenge](https://github.com/b-straub/CollectionViewChallenge)

**Comment by hartez** [comment]
This is fixed by PR #6089.
