### ISSUE TITLE
[Bug] CollectionView doesn't reset the selection color

### ISSUE THREAD

**Issue by b-straub** [xamarin/Xamarin.Forms#6128]
### Description

CollectionView doesn't  reflect changes for the SelectedItem. Setting SelectedItem = null should clear the selection color.

### Steps to Reproduce

Run the attached sample project from either iOS simulator or device. 
Tap on a row, CollectionView does update but the code "SelectedItem = null" has not effect.

- Version with issue:
4.0.0 Pre Release 10
- IDE:
VS Mac
- Platform Target Frameworks:
  - iOS:  12.2
- Nuget Packages:
4.0.0 Pre Release 10
- Affected Devices:
All

### Screenshots

![IMG_0042](https://user-images.githubusercontent.com/7459002/57370935-a9887600-7191-11e9-8d10-09aafc3a8364.jpg)

### Reproduction Link

[CollectionViewChallenge](https://github.com/b-straub/CollectionViewChallenge)

**Comment by hartez** [comment]
Fixed by PR #6085.
