### ISSUE TITLE
[Bug] Proguard is being skipped for debug configuration.

### ISSUE THREAD

**Issue by awattar** [xamarin/Xamarin.Forms#6129]
### Description

Proguard step is being skipped for debug configuration but works for release for the same settings.

### Steps to Reproduce

1. Create forms app.
2. Add proguard config and set project proguard setting for both debug and release configs.
3. Build in debeg and release.

### Expected Behavior

Proguard step works for both debug and release.

### Actual Behavior

Proguard step is being skipped due to false condition:

`  Task "Proguard" skipped, due to false condition; ( '$(AndroidLinkTool)' == 'proguard' And '$(_ProguardProjectConfiguration)' != '' ) was evaluated as ( 'proguard' == 'proguard' And '' != '' ).`

It works for the same app for Release config with the same settings.

```
  Using "Proguard" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Build.Tasks.dll".
  Task "Proguard"
    Environment Variables passed to tool:
...
    ProGuard, version 5.3.2
```

### Basic Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.0.5 (build 9)
Installation UUID: fc295dbb-ea60-45ea-a7bd-051b091fe655
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Enterprise)
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mwesolowski/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-04-05 16:58:56 UTC

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Enterprise)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800050009
Git revision: d9d7eed60cb59740ba55c04bfe9c39ac57014c12
Build date: 2019-04-26 10:08:19+00
Build branch: master
Xamarin extensions: 5efedb990d786142d3b54351c01ce867af7b7680

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

**Comment by samhouts** [comment]
@awattar What version of Xamarin.Forms are you using? Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by awattar** [comment]
Just create new Forms project add empty proguard rules file with proper build action, check proguard config in the project configuration then build for debug.

[ProguardTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3235984/ProguardTest.zip)

**Comment by PureWeen** [comment]
@awattar I don't really understand your attached sample

1) I don't see any proguard rules in there
2) Proguard only runs if you have the linker enabled https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard?tabs=windows#enabling-proguard so if you just check the "Proguard" box for debug then proguard won't run. 

you don't really want to run proguard in debug mode because it doesn't really offer you anything of value there unless you just want to test if it works

**Comment by awattar** [comment]
1. There are no proguard rules as this is only minified sample and rules doesn't matter.
2. It's OK if it works only in Release "by design" - in this case, build message could be improved.

It does matter as enabling proguard delays running into multidex like in my case. Now I have proguard enabled and no multidex in release while disabled proguard and enabled multidex in debug. That makes app configs different and can make debugging more difficult.

**Comment by awattar** [comment]
@PureWeen working on VS Mac 8.1.4 and 8.2 preview proguard rules are now applied for debug config. Was this intentional?

There is also an issue with disabling proguard from VS UI - when switching Code shrinker to None it is still marked as true in csrpoj (Debug config).

`<EnableProguard>true</EnableProguard>`
