### ISSUE TITLE
[Bug] DatePicker / TimePicker Unfocused Event Fired When Focused

### ISSUE THREAD

**Issue by lcm98** [xamarin/Xamarin.Forms#6138]
### Description

Android 9.0 (Pie) - API 28 only.

When the dialog for either the DatePicker or TimePicker is opened, the unfocused event from that picker is fired. 

In this particular case, I am using the unfocused event of the DatePicker to focus on the TimePicker. The result is actually that as soon as the DatePicker calendar opens, the unfocused event instantly fires which then opens the TimePicker Clock overlayed on-top of the calendar.

This seems related to #5159 , except instead of the issue being that the dialog won't open at all, it opens and immediately fires the Unfocused event.

### Steps to Reproduce

1. Have handler attached to Unfocused Event of DatePicker or TimePicker
2. Focus DatePicker or TimePicker via Code

### Expected Behavior

Unfocused event is fired when dialog is closed.

### Actual Behavior

Unfocused event fires as soon as dialog opens

### Basic Information

- Version with issue: Xamarin Forms v3.6.0.344457
- Last known good version: Unknown - Believe related to Android 9 Version
- IDE: VS 2017 v15.9.11
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by lcm98** [comment]
With further testing, this issue seems to be isolated to when the DatePicker is initially focused via code (datePicker.Focus()) as opposed to clicking the visual element

**Comment by samhouts** [comment]
@lcm98 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by lcm98** [comment]
Yeah I'll try to find the time this week to put something together

**Comment by samhouts** [comment]
Thanks! We'll keep looking for it.

**Comment by samhouts** [comment]
@lcm98   Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
