### ISSUE TITLE
[Spec] Shell Hierarchical navigation 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#6139]
# Shell Hierarchical Navigation

Provide a way to express hierarchical (drill down) navigation in Shell.

# API Suggestions

## Provide a type of definitive structure
```XAML
<DrillDownNavigation>
    <ShellContent ContentTemplate="{}">
        <ShellContent ContentTemplate="{}">
            <ShellContent ContentTemplate="{}">
                <ShellContent ContentTemplate="{}"/>
            </ShellContent>
        </ShellContent>
    </ShellContent>
</DrillDownNavigation>
```

And navigate via `Forward` and `Back` methods off of `Shell.Current.Navigation`.

## Just allow nesting of anything into Shell Content by default
https://github.com/xamarin/Xamarin.Forms/issues/6016#issuecomment-487335322
```XAML
<FlyoutItem Route="tabsandwich" Title="Tab Sandwich" FlyoutIcon="iconXamarin.png" Style="{StaticResource TertiaryShell}">
        <Tab Route="tab1" Title="tab2" Icon="iconXamarin.png">
            <ShellContent Route="level0" ContentTemplate="{DataTemplate local:Level0Page}"> 
                <ShellContent Route="level1" ContentTemplate="{DataTemplate local:Level1Page}"> 
                    <ShellContent Route="level2" ContentTemplate="{DataTemplate local:Level2Page}"> 
                        <Tab Route="tab1onLevel2" Title="tab2" Icon="iconXamarin.png">
                            <ShellContent Route="level3" ContentTemplate="{DataTemplate local:Level3Page}"/>
                        </Tab>
                        <Tab Route="tab1onLevel2" Title="tab1" Icon="iconXamarin.png">
                            <ShellContent Route="tab1onLevel2_Level0" ContentTemplate="{DataTemplate local:Level3Page}">
                                <ShellContent Route="level1" ContentTemplate="{DataTemplate local:Level1Page}"/> 
                            </ShellContent>
                        </Tab>
                         <Tab Route="tab2onLevel2" Title="tab2" Icon="iconXamarin.png">
                            <ShellContent Route="tab2onLevel2_Level0" ContentTemplate="{DataTemplate local:Level3Page}">
                            </ShellContent>
                        </Tab>
                    </ShellContent>
                </ShellContent>
            </ShellContent>
        </Tab>
        <Tab Route="tab2" Title="tab2" Icon="iconXamarin.png">
            <ShellContent Route="updates" Title="Updates" Icon="iconXamarin.png" ContentTemplate="{DataTemplate local:UpdatesPage}" />
        </Tab>
    </FlyoutItem>
```

# Scenarios

Consider an app like the Azure portal, it has deeply nested navigation routes.

Example: `Home > All resources > davidortinau - Blobs > Share`

Consider an app like iOS General Settings. It's a  list to a list to a list to details, and other variations of drill down.

Yes this can be achieved by managing your own `PushAsync` style navigation, but it would be desirable to manage this in Shell as well.

**Comment by HeroSpha** [comment]
Yes, was looking for something like this, im working on an app with profiles -> profile -> Settings
                                                                                                                                           ->Media
                                                                                                                                           ->Other
The issue im currently experiencing with PushAsync is when i push a tabbed page with a Collection, the display gets distorted, the second page doesnt show property.

**Comment by PureWeen** [comment]
@davidortinau I think figuring this one out for a generalized structure for defining the hierarchical nature of an application is useful. Opposed to having a specific DrillDown structure. 

I find that a lot of people are wanting to define the XAML like 

```XAML
<ShellContent route="listpage>
     <ShellContent route="detailspage>
```

What are your thoughts on just letting people specify whatever like the example given here
https://github.com/xamarin/Xamarin.Forms/issues/6016#issuecomment-487335322

We want users to be able to have a navigation stack of more complex shell pages so this would be a way to achieve this

We could even let people template it a bit and add the ability to add parameters?

```XAML
<ShellContent route="listpage>
     <NavigationItem ItemTemplate={details}/>
                <RouteParameters>
                      <Parameter Key="Id" Value="{Binding Id}" />
```


NavigationItem could also just be all templated inside ContentTemplate as well so the XAML stays cleaner

```XAML
<ShellContent route="listpage" ShellContentTemplate="{ContentTEmplate DetailsNavigationItem}">
```

**Comment by ampslive** [comment]
> Yes, was looking for something like this, im working on an app with profiles -> profile -> Settings
> ->Media
> ->Other
> The issue im currently experiencing with PushAsync is when i push a tabbed page with a Collection, the display gets distorted, the second page doesnt show properly.

Yea have come across the same issue while using a TabbedPage as the "Details" page

**Comment by TheBaileyBrew** [comment]
This has huge practical applications to the app I'm writing. I have dozens of pages that are grouped into a few major categories, and then sub-grouped like this:

ITEM
 -> Search
 -> Details
     -> Availability
     -> Authorizations
 -> New Items
 -> Discontinued

ORDERS
 -> Search
     -> History List
     -> Detail for Selection
 -> Current
     -> Detail for Selection 


I'd want my major categories to be a static Tabbar, then from within a dashboard page, I can navigate to any of the pages and have the nested views display in the top bar.

**Comment by PureWeen** [comment]
Closing and moving discussion to here https://github.com/xamarin/Xamarin.Forms/issues/8528
