### ISSUE TITLE
WCF service methods not connected with Xamarin.Forms app (Android, iOS)

### ISSUE THREAD

**Issue by Mushtaq123** [xamarin/Xamarin.Forms#6140]
Hi,
I have created a WCF service and called the same from Xamarin Cross-Platform with Dot Net Standard 2 (UWP, iOS, Android), an app using Connected Service approach.

I checked this service approach in UWP and it works fine. But in Android and iOS project, the service is not connected.

Connected service call 
```
IMobileservice mobileservice = new MobileserviceClient();
try
{
       ValidateCredentials validateCredentials = await mobileservice.ValidateLoginCredentialsAsync(_param);
       label.Text = validateCredentials.p_UserGroupCodeDesc;
}
catch (Exception ex)
{

}
```
Android runtime error after clicked button :

> Unhandled Exception:
> 
> System.ServiceModel.FaultException`1[[System.ServiceModel.ExceptionDetail, System.ServiceModel, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: Error in deserializing body of request message for operation 'GetData'. OperationFormatter encountered an invalid Message body. Expected to find node type 'Element' with name 'GetData' and namespace 'http://tempuri.org/'. Found node type 'Element' with name 'GetDataAsync' and namespace 'http://tempuri.org/'
> 

iOS runtime error after clicked button :

> Unhandled Exception:
> 
> System.InvalidOperationException: MonoTouch does not support dynamic proxy code generation. Override this method or its caller to return specific client proxy instance

Funny thing is UWP work fine and return method string just fine.
This is my first experience to consume WCF in xamarin.forms and I feel maybe I do something wrong.

**Comment by carlos-ferreira** [comment]
I don't think it's a Xamarin bug.

This can help you: 

- https://stackoverflow.com/questions/51887706/proxy-class-override-method-for-ios-mono-error-in-xamarin-forms

- https://github.com/dotnet/wcf/issues/2940

**Comment by samhouts** [comment]
@Mushtaq123 Yes, please see the resources mentioned by @carlos-ferreira (thanks!!). If you still encounter problems, feel free to reopen this issue and attach a small project demonstrating the problem. Thanks!
