### ISSUE TITLE
[Enhancement] Padding for Entry And Editor

### ISSUE THREAD

**Issue by albilaga** [xamarin/Xamarin.Forms#6141]
## Summary
Add Property Padding for Entry and Editor. The padding property should work like Button Padding. 
## API Changes

Property added in Editor and Entry should be

```
public Thickness Padding
        {
            get => (Thickness)GetValue(PaddingProperty);
            set => SetValue(PaddingProperty, value);
        }

        public static readonly BindableProperty PaddingProperty =
            BindableProperty.Create(nameof(Padding), typeof(Thickness), typeof(Editor),default(Thickness));
```
and then can be used in Android Renderer like

`Control.SetPadding((int)GetPxFromDip((float)_Element.Padding.Left ), (int)((float)_Element.Padding.Top ), (int)((float)_Element.Padding.Right), (int)((float)_Element.Padding.Bottom ));`

and in iOS can be used like

`Control.TextContainerInset = new UIKit.UIEdgeInsets((nfloat)element.Padding.Top, (nfloat)element.Padding.Left, (nfloat)element.Padding.Bottom, (nfloat)element.Padding.Right);`

The problem in iOS is with placeholder label in Editor. As I saw in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/EditorRenderer.cs _placeholderLabel is a label with constraint set in there. It make not possible to set placeholder padding from custom renderer (or I don't know how to. Please let me know if that possible)

## Intended Use Case
The use case in here is in our design we usually have custom padding set for our entry and editor.

**Comment by thedjnova** [comment]
From what I'm aware you can set the padding for a UITextField on iOS by sub-classing and overriding its textRectForBounds, editingRectForBounds, placeholderRectForBounds, and rectForBounds equivalents within Xamarin.iOS.

So creation of a UITextFieldExtended (or suitable named class) would be needed which exposes a way to change what those methods return when padding is changed.

**Comment by albilaga** [comment]
Yes for Entry which using UITextField that is possible. But for Editor which in iOS using UITextView that is not possible. Also in Editor, Xamarin Forms use private placeholderLabel which position set using constraint which can't be set from custom renderer AFAIK

**Comment by jrahma** [comment]
@samhouts Also please add Label's Padding because currently we have to put it inside a padded ContentView

**Comment by samhouts** [comment]
@jrahma Label padding is already in 4.3.0. https://github.com/xamarin/Xamarin.Forms/pull/6299 Thanks!

**Comment by albilaga** [comment]
Anyone working on this? I maybe can start working on this in weekend. I already have some implementations on my project working but it is for 4.1. I'll check if it is working for v4.3

**Comment by EdoardoCinelli1991** [comment]
Solved? Workaround?
![Capture](https://user-images.githubusercontent.com/55441590/71721819-e131e580-2e26-11ea-85c9-8a65f52282b3.PNG)

**Comment by stefancvetkovic** [comment]
is there any news on this?

**Comment by EdoardoCinelli1991** [comment]
No fix sorry Inviato da Posta per Windows 10 Da: Stefan CvetkovicInviato: mercoledì 11 marzo 2020 16:54A: xamarin/Xamarin.FormsCc: EdoardoCinelli1991; CommentOggetto: Re: [xamarin/Xamarin.Forms] [Enhancement] Padding for Entry And Editor (#6141) is there any news on this?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by titoleru** [comment]
This seems like a fairly easy fix to implement, any news when will be uploaded?

**Comment by kerbooo** [comment]
Hello is there any update?

**Comment by SimuNews** [comment]
Any update or workaround?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
