### ISSUE TITLE
[Bug] Maps

### ISSUE THREAD

**Issue by MisterioRee** [xamarin/Xamarin.Forms#6143]
### Description
Using Xamarin.Forms.Maps Nuget Plugin is crashing Application (Android) and dose not display anything on IOS, 

### Steps to Reproduce
1. ShellApp -> ContentPage 
 <maps:Map IsShowingUser="True"         
                     MapType="Street" 
                     HeightRequest="300"/>

### Expected Behavior
Java.Lang.NoClassDefFoundError: <Timeout exceeded getting exception details>
App Crashed
### Actual Behavior
Display Geo Maps
### Basic Information
- Version with issue:  Form.Maps Plugin: 3.6.0.344457, Forms 4.0.0.394984-pre10
- Last known good version: 3.6.0.344457
- IDE: Visual Studio [Windows]
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms.Maps
- Affected Devices: Android/IOS

### Screenshots
![Bug Report Screen Shot](https://user-images.githubusercontent.com/18234947/57443472-2c2b3700-725f-11e9-99b7-2eeb281b2a28.png)
 
05-09 13:32:41.501 E/AndroidRuntime(17813): FATAL EXCEPTION: Thread-14
05-09 13:32:41.501 E/AndroidRuntime(17813): Process: com.companyname.OPFalafel, PID: 17813
05-09 13:32:41.501 E/AndroidRuntime(17813): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):3)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):3)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):15)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):6)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):23)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@16091081@16.0.91 (100400-244116403):8)
05-09 13:32:41.501 E/AndroidRuntime(17813): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000030/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000030/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64]]
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at ac.loadClass(:com.google.android.gms.dynamite_dynamiteloader@16091081@16.0.91 (100400-244116403):4)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-09 13:32:41.501 E/AndroidRuntime(17813): 	... 6 more
Thread started:  #8
Unhandled Exception:

Java.Lang.NoClassDefFoundError: <Timeout exceeded getting exception details>

05-09 13:32:42.949 W/DynamiteModule(17813): Local module descriptor class for com.google.android.gms.googlecertificates not found.
05-09 13:32:42.957 I/DynamiteModule(17813): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4
05-09 13:32:42.957 I/DynamiteModule(17813): Selected remote version of com.google.android.gms.googlecertificates, version >= 4
05-09 13:32:42.962 W/yname.OPFalafe(17813): Unsupported class loader
05-09 13:32:43.096 W/yname.OPFalafe(17813): Verification of void q.c() took 112.470ms

**Comment by thedjnova** [comment]
Maps 3.x with Forms 4.x think thats the problem right there, have you tried updating Maps to 4.x?

**Comment by samhouts** [comment]
@MisterioRee Please make sure your Maps nuget version matches your Forms nuget package. If you still have this issue once you have matched versions, please feel free to reopen this issue and attach a small project demonstrating the problem. Thanks!

**Comment by MisterioRee** [comment]
Yeah the 4.x version is working now Thanks.

**Comment by gsgou** [comment]
@samhouts  i am having exactly the smae issue on Xamarin.Forms 4.4.0.991864.
The maps nuget matches the Forms nuget. I ll tr to find a stable in 4.4
