### ISSUE TITLE
[Bug] [UWP] MasterDetail Page menu with footer doesn't render correctly

### ISSUE THREAD

**Issue by Raystorm7** [xamarin/Xamarin.Forms#6144]
### Description
Hi all!
I have a MasterDetail Page with a menu that have an header and a footer.

This is the structure of the menu:

`<grid>` as header
`<listview>` as menu list
`<grid>` as footer

Only on UWP the footer isn't render correctly the first time.
I need to open, close then reopen the menu to show the footer correctly.

### Expected Behavior
The footer should be rendered correctly also the first time.

### Screenshots
[Here](https://ufile.io/hyyhcdfo)

### Reproduction Link
[Here](https://ufile.io/xqeuibgs)

**Comment by bmacombe** [comment]
#3886 will fix this...but I don't think it's in a release yet.

**Comment by bmacombe** [comment]
Actually #5338 is the PR...3886 was the initial issue.

**Comment by samhouts** [comment]
closed by #5338
