### ISSUE TITLE
[Enhancement] Remove [EditorBrowsable(EditorBrowsableState.Never)], also OnXXX should be protected

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#6145]
The private event handlers and hiding the events from VS editor has no benefit except making it difficult to create subclasses like renderers. For example, I am getting null reference exception on UWP when using WebView.Eval or EvalJavascriptAsync (when using MainThread and no js is called when I don't use it) and I wanted to know what is going wrong by overriding the renderer but it took me time to know why VS is not showing anything to override or listen to, the element events are hidden from the editor, and the event handler of the renderer is private!

**Comment by adammeaney** [comment]
Its not like the attribute does anything.

<code>new ToolbarItem().IsEnabled = true;</code> still works, even though it is marked as EditorBrowable.Never and intellisense doesn't find it.

**Comment by samhouts** [comment]
@MhAllan We don't intend to remove `[EditorBrowsable(EditorBrowsableState.Never)]`. We put those in intentionally to keep the IntelliSense manageable, and also to indicate that the API is internal and subject to change. As for promoting `private` methods to `protected` or `public`, we are more than happy to evaluate those on a case by case basis. If you'd like to submit a request for any API to be exposed, please be specific and give us your use cases. Thanks!!
