### ISSUE TITLE
VS 2019 Locks up with XF [Bug] 

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#6147]
1. Open VS 2019 in Windows 10
2. Create a new iOS Xamarin Forms app. Hello World.
3. Set it to debug run in the simulator, but on windows.
4. The app is running.
5. Let Windows 10 auto lock by timing out. This is important, it must auto lock after inactivity
6. Unlock Windows by entering your password

VS 2019 is now unresponsive and can only be closed by Task Manager Kill
 
### Basic Information
 
- IDE: VS 2019, but also 2017
- Platform Target Frameworks: 
  - iOS:  any in the last 6 months

**Comment by ianvink** [comment]
Note that when I unlock Windows 10 I see this at the bottom of the VS 2019:

![image](https://user-images.githubusercontent.com/112916/57482341-3cd8ae80-7259-11e9-9998-1d688f561eee.png)

**Comment by samhouts** [comment]
@ianvink Please report this via feedback within Visual Studio. Thanks!
