### ISSUE TITLE
[UWP] ListView displays null values black

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#6154]
### Description

in UWP null items are displayed black instead of transparent (like in iOS and Android)

### Steps to Reproduce

`mListView.ItemsSource = new List<YourClass>() { new YourClass(), null, null };`

1st row is fine, the two other rows are black (instead of transparent)

### Basic Information

- Version with issue: Xamarin Forms 3.6
- Last known good version: 3.4

**Comment by samhouts** [comment]
@mknotzer Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mknotzer** [comment]
Attached a small demo project. Only on UWP the null row is black

``xListView.ItemsSource = new List<string>() { "A", "B", null, "C" };``

**Comment by samhouts** [comment]
@mknotzer I don't see an attachment. Did it fail to upload? Thanks!

**Comment by mknotzer** [comment]
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3201223/App1.zip)
My apologies
