### ISSUE TITLE
Question: AutomationId may only be set one time - Bug or Feature?

### ISSUE THREAD

**Issue by aspnetde** [xamarin/Xamarin.Forms#6157]
Using [Fabulous](https://github.com/fsprojects/Fabulous) on top of Xamarin.Forms I just ran into that issue described [here](https://github.com/fsprojects/Fabulous/issues/403). 

tl;dr: It seems by the nature of Fabulous it tries to re-use an existing element's instance and by setting `AutomationId` ([source](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Element.cs#L55)) fo a second time it's running into the `InvalidOperationException` thrown in the setter here.

The history doesn't tell much, so I don't know why that exception there is thrown in the first place. Could someone investigate what's the reasoning behind this?

Best case would be to remove the guard and make the whole thing compatible with Fabulous.

**Comment by samhouts** [comment]
@aspnetde AutomationId was created for the Xamarin UITest framework. If I remember correctly, it is not possible for UITest to pick up changes to AutomationId. It reads (or at least read) the tree in once and only once. To prevent confusion, we instituted the guard on AutomationId. It's possible that this is no longer a problem, and we should reevaluate it. This has come up in #5899 and #4998, and I'm sure many other places, as well. It looks like Fabulous is fixing your immediate issue, so we'll set this into our enhancements triage backlog for further discussion. Thanks!

**Comment by jeremy-bridges** [comment]
We seem to be having the issue as well. We're using 3.6.0.344457.

We set the binding using XAML. Something like this:

AutomationId="{Binding AutomationName}"

We use ReactiveUI as the app's MVVM framework.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
