### ISSUE TITLE
[Enhancement] Make Send methods virtual for application lifecycle

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#6159]
## Summary

Right now there are hidden methods in the Application class for invoking lifecycle events (i.e. Start, Resume, Sleep). Frameworks may need to tie into these events which means overriding the On{Event} method. While this works it also means that any downstream users have to explicitly know to call the base.On{Event}.

## API Changes

Current API

```cs
[EditorBrowsable(EditorBrowsableState.Never)]
public void SendResume()
{
    Current = this;
    OnResume();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public void SendSleep()
{
    OnSleep();
    SavePropertiesAsFireAndForget();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public Task SendSleepAsync()
{
    OnSleep();
    return SavePropertiesAsync();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public void SendStart()
{
    OnStart();
}
```

Proposed

```cs
[EditorBrowsable(EditorBrowsableState.Never)]
public virtual void SendResume()
{
    Current = this;
    OnResume();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public virtual void SendSleep()
{
    OnSleep();
    SavePropertiesAsFireAndForget();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public virtual Task SendSleepAsync()
{
    OnSleep();
    return SavePropertiesAsync();
}

[EditorBrowsable(EditorBrowsableState.Never)]
public virtual void SendStart()
{
    OnStart();
}
```

## Intended Use Case

Allow frameworks such as Prism that provide a custom base Application class to inject their lifecycle events without requiring users to have to know to call base.On{Event}, while continuing to hide the API's from intellisense so they aren't misused.

**Comment by samhouts** [comment]
We need to implement this in line with how we plan to implement #2210--add new events that can be hooked into before/after these events.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
