### ISSUE TITLE
[Bug] Changing the Shell Flyout Header after it's already rendered doesn't work

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6161]
### Description
If you try to change the Shell .FlyoutHeader after the app is already running it won't work. On iOS it just becomes blank

### Steps to Reproduce

1. start shell app
2. use a button or similar so you can trigger a change to flyout header
3. click the button

### Expected Behavior
flyoutheader should re-render

### Actual Behavior
it does not.

**Comment by wesoos** [comment]
This is also the case if you have the binding context of the shell set, and some elements in the header bound.  Like the text of a label.  The whole shell flyout will be blank on iOS...

**Comment by Eilon** [comment]
Just ran into this. On Android (emulator) you can only set `Shell.FlyoutHeader` before the `Shell` is first used in the live tree. After that you can set `FlyoutHeader` all you want, but it is ignored. `Shell` correctly raises the `ChildRemoved` and `ChildAdded` events (with the correct `EventArgs`!), but there is no visual change in the UI.

**Comment by samhouts** [comment]
closed by #10079
