### ISSUE TITLE
Specify calendar type in DatePicker control.

### ISSUE THREAD

**Issue by B-Esmaili** [xamarin/Xamarin.Forms#6162]
Is there any way to specify calendar type of DatePicker just like `CalendarIdentifier` in UWP applications?if yes how to specify calendar type if not do you have any plan to support it in future resales?
EDIT:
Additionally why `PersianCalendar` is not in the (CalendarIdentifier Enum) list whereas it exists in .NET calendar list?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
