### ISSUE TITLE
[Bug] Grid/AnyOther inside CarouselView is ignoring WidthRequest and HeightRequest inside content page

### ISSUE THREAD

**Issue by MisterioRee** [xamarin/Xamarin.Forms#6175]
### Description
 <CarouselView x:Name="carousel" ItemsSource="{Binding Zoos}" HeightRequest="200" VerticalOptions="FillAndExpand">
                <CarouselView.ItemTemplate>
                    <DataTemplate>                         
                            <Image  Source="..."  WidthRequest="500" Aspect="AspectFill"/> 
                    </DataTemplate>
                </CarouselView.ItemTemplate>
### Steps to Reproduce

1. WidthRequest="" is monitory inside CarouselView  or setting Grid's Column Width to absolute value

### Expected Behavior

        <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
           </Grid.ColumnDefinitions>
Or 

VerticalOptions="FillAndExpand"
HorizontalOptions="FillAndExpand"

Should work out

### Actual Behavior
Display Blank 

### Basic Information
xamarin.Forms 4.0.0.394984-pre10

- Version with issue:
  4.0.0.394984-pre10
- Last known good version:
 NULL
- IDE:
 VS 19 For Windows
- Platform Target Frameworks: 
  - iOS:  
  - Android:  

- Nuget Packages:
  https://github.com/sthewissen/Xamarin.Forms.PancakeView
  Xamarin.Forms.maps

- Affected Devices:
All

**Comment by samhouts** [comment]
@MisterioRee  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by MisterioRee** [comment]
Hi @samhouts  Thank you for quick response, 
there is no issue in Shell, as i have tested again in a new Test Application its working fine, problem was with my  <Grid.ColumnDefinitions>
 

` 
    <ScrollView>
        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <Grid.RowDefinitions>
                <RowDefinition Height="*"/>
                <RowDefinition Height="3*"/>
            </Grid.RowDefinitions>

            <StackLayout Grid.Row="0">
                <CarouselView x:Name="carousel" ItemsSource="{Binding Zoos}" >
                    <CarouselView.ItemTemplate>
                        <DataTemplate>
                            <StackLayout>
                                <Image Source="{Binding ImageUrl}" Aspect="AspectFill"/>
                                <Label Text="{Binding Name}" VerticalOptions="CenterAndExpand" />
                            </StackLayout>
                        </DataTemplate>
                    </CarouselView.ItemTemplate>
                </CarouselView>
            </StackLayout>

            <StackLayout Grid.Row="1">
                
            </StackLayout>

        </Grid>
        
    </ScrollView>`
