### ISSUE TITLE
[Bug] Invalid TabBar.Items access in iOS ShellItemRenderer

### ISSUE THREAD

**Issue by Dresel** [xamarin/Xamarin.Forms#6184]
### Description

iOS ShellItemRenderer accesses [TabBar.Items](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs#L259) to enable / disable items. If there are more shell sections than maxTabs, it could lead to an index out of range exception because they are aggregated in a single "show more" item.

### Steps to Reproduce

1. Create shell project
2. Create additional shell sections
3. Set shell section to IsEnabled false to trigger array access
4. Start app

```xml
<!-- Your Pages -->
<ShellItem>
    <ShellSection Title="Browse" Icon="tab_feed.png">
        <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
    </ShellSection>
    <ShellSection Title="About" Icon="tab_about.png">
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
    </ShellSection>
    <ShellSection Title="Browse" Icon="tab_feed.png">
        <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
    </ShellSection>
    <ShellSection Title="About" Icon="tab_about.png">
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
    </ShellSection>
    <ShellSection Title="Browse" Icon="tab_feed.png">
        <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
    </ShellSection>
    <ShellSection Title="About" Icon="tab_about.png">
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
    </ShellSection>
    <ShellSection Title="Browse" Icon="tab_feed.png">
        <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
    </ShellSection>
    <ShellSection Title="About" Icon="tab_about.png" IsEnabled="False">
        <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
    </ShellSection>
</ShellItem>
```

### Expected Behavior

No exception. You might also have to fiddle with the `UIMoreNavigationController` to disable particular items there.

### Actual Behavior

Exception.

**Comment by samhouts** [comment]
@Dresel  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Dresel** [comment]
[Repo6184.zip](https://github.com/xamarin/Xamarin.Forms/files/3199819/Repo6184.zip)

As mentioned, crashes [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs#L259).

**Comment by pictos** [comment]
This still happens, so @samhouts can I work on this issue?

**Comment by PureWeen** [comment]
@pictos Yes!!
