### ISSUE TITLE
[Enhancement] Add StepValue to Slider

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6185]
## Summary
In certain scenarios the slider value is required in  steps. So StepValue can cover this. 

## API Changes
Add new Property : StepValue

## Intended Use Case
In one of my projects the slider Value needs to be increased by 50 with every drag step. Lots of time a whole number is required in value.

**Comment by toomasz** [comment]
Good idea, I also needed it so i had to create custom renderer :(

**Comment by HobDev** [comment]
I manage to get stepvalue functionality by adding some code in the code behind:
```
public void OnSliderValueChanged(object sender, ValueChangedEventArgs e)
      {
                    var newStep = Math.Round(e.NewValue / 50);
                   slider.Value = newStep * 50;
            }
        }
```
Thus the slider add 50 with every step.

**Comment by charlesroddie** [comment]
Duplicate of https://github.com/xamarin/Xamarin.Forms/issues/3351

**Comment by jfversluis** [comment]
Duplicate of #3351
