### ISSUE TITLE
[Bug] Grid with ColumnDefinitions with Unexpected Behavior

### ISSUE THREAD

**Issue by viniciuslln** [xamarin/Xamarin.Forms#6193]
### Description
In the code informed, the grid height the grid is rendered incorrectly when I add ColumnDefinitions (second image attached )

### Steps to Reproduce
Add
```
<Grid.ColumnDefinitions>
    <ColumnDefinition Width="Auto" />
     <ColumnDefinition Width="*" />
</Grid.ColumnDefinitions>
```
in the Grid.

### Expected Behavior
Height grid adjust content size

### Actual Behavior
Grid has incorrect height

### Basic Information

- Version with issue: 
4.0.0.394984-pre10
- Last known good version: 
null
- IDE:
 VS 19 For Windows
- Platform Target Frameworks: 
  - iOS:  
Not tested
  - Android:  
9.0
- Android Support Library Version: 
- Affected Devices:
All
### Screenshots
- Without ColumnDefinition 
<img src="https://i.imgur.com/J2gMSVf.png"/>
- With ColumnDefinition 
<img src="https://i.imgur.com/3kk6HZj.png"/>

### Reproduction Link
https://gist.github.com/viniciuslln/1876c1f0c4a9f23dc9a3e40b5bc58bb4

**Comment by kingces95** [comment]
@viniciuslln would you mind attaching a zipped reproduction complete with the images/resources etc so we can reproduce the images you posted? Or just replace the images with BoxViews.

**Comment by samhouts** [comment]
@viniciuslln  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
