### ISSUE TITLE
Native crash when using Syncfusion SfListView with Xamarin.Forms v3.6.0.344457 

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#6203]
On resuming with the following bug report, our clients ref [Forum](https://www.syncfusion.com/forums/144527/sflistview-issue-typeloadexception-parent-class-vtable-failed-to-initialize-sflistview-issue) are facing the similar issue in Xamarin.Forms v3.6.0.344457 too. 

https://github.com/xamarin/Xamarin.Forms/issues/5288

Can you please check whether the fix for the reported issue is included in the mentioned version too?

Please revert us asap.

Regards,
Dinesh Babu Yadav (Syncfusion Support Team)

**Comment by PureWeen** [comment]
@DineshBabuYadav have you verified with that customer that they are on the latest version of SfLIstView? 

Here is the highlighted version that is compatible
https://github.com/xamarin/Xamarin.Forms/issues/5288#issuecomment-481219047

If the latest version of Syncfusion + XF 3.6.0.344457 causes a crash on android then can you provide a sample demonstrating the crash please?

**Comment by DineshBabuYadav** [comment]
@PureWeen , we are validating with customer to share the sample to replicate the issue. Since, with our sample, we are unable to replicate the issue in the reported version. So, please wait until the customer revert us.

SfListView version : 17.1.0.47
Xamarin Forms version : 3.6.0.344457
Android version : 9.0
Device Model : Mi A1

**Comment by samhouts** [comment]
Thanks, @DineshBabuYadav, we will wait for your reply.

**Comment by DineshBabuYadav** [comment]
@samhouts , thanks

**Comment by OccamsTacKnife** [comment]
I was having the same issue with these versions of Xamarin Forms and SfListView. There were some other SyncFusion controls in my project that hadn't updated. Updating all SyncFusion packages to version 17.1.0.47 resolved my issue.

**Comment by samhouts** [comment]
Thanks @OccamsTacKnife!

**Comment by samhouts** [comment]
@DineshBabuYadav  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
