### ISSUE TITLE
Please implement Toast message for Android, iOS and Windows from Shared project

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#6206]
## Summary

I need build in Toast message from Xamarin.Forms. I don't want to use 3rd party packages.

**Comment by Sergiojoel9877** [comment]
Why you don't make your own implementation using the built-in Dependency Service?, its quite easy.

**Comment by HobDev** [comment]
@Sergiojoel9877 Can you point to any resource for a guidance to implement this functionality.

**Comment by galadril** [comment]
@HobDev @arvindrajachourasiya There are quite some tutorials on this topic, for example:
https://www.c-sharpcorner.com/article/xamarin/

> This article demonstrates how to make Toast Message or local message using Dependency Service in Xamarin.Forms applications.

**Comment by jrahma** [comment]
It will be great to have it from Xamarin Forms like this:

<Toast
    Width=""
    Height=""
    Animation="{Fade, SlideFromTop, SlideFromBottom, Zoom}"
    DisappearAfter="{Time-In-Seconds, Otherwise will not disappear until click}"
    BackGroundColor="Yellow"
    TextColor="Black"
    CornerRadius="25"
    Position="{Top, Bottom}"
/>

that's what I can think of now before sleeping :)

**Comment by galadril** [comment]
Maybe even add Action options.. so you can have a button on the toast/snackbar with an action command like this;

![afbeelding](https://user-images.githubusercontent.com/14561640/62270225-c6051900-b435-11e9-89cd-b3bf9c76760c.png)


![afbeelding](https://user-images.githubusercontent.com/14561640/62270237-ce5d5400-b435-11e9-946f-8149d2469f8c.png)


![afbeelding](https://user-images.githubusercontent.com/14561640/62270245-d6b58f00-b435-11e9-9450-0d61b433d255.png)

**Comment by rmarinho** [comment]
This is being worked on https://github.com/xamarin/XamarinCommunityToolkit as the SnackBar control
