### ISSUE TITLE
Please include ALL release notes in stable releases

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#6208]
In the first stable release of a version, it would be great to have all of the release notes for that version, not just changes made since the last pre-release. In order to figure out how much changed between 3.6.0 and 4.0.0 I have to read through 11 sets of release notes with the current setup.

**Comment by jcmanke** [comment]
This was meant in regards to the GitHub release notes, release notes at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/ seem to be what I'm after.

**Comment by samhouts** [comment]
@jcmanke We used to include the link to the complete release notes! We'll do that again (see https://github.com/xamarin/Xamarin.Forms/releases/tag/release-4.0.0-sr2). Thanks!
