### ISSUE TITLE
The child views in the Xamarin Forms View converted to Native UIView could not be auto resized

### ISSUE THREAD

**Issue by priyaJR** [xamarin/Xamarin.Forms#6215]
### Description
The child views could not be auto resized when converted from Xamarin Forms View to Xamarin.iOS(Stackpanel contains an image and button). 
Actual issue is while converting the custom view from Xamarin forms to nativeiOS. That is, in our case we are rendering the view alone in Xamarin Forms and we need to convert the view into UIView along with its bound values and subviews in the  customview. 
http://michaelridland.com/xamarin/creating-native-view-xamarin-forms-viewpage/

### Steps to Reproduce

1. Add a cutomview with button and a Label in a stackpanel
2. Convert the view to native UIView
3. While resing the native view the subviews were not resized.

### Expected Behavior
When the customview is resized the subviews inside the customviews has also to be resized accordingly

### Actual Behavior
The subviews are not resized when the customview is resized.

### Basic Information

- Version with issue: 3.10.697729
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12
  - Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@priyaJR  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@priyaJR  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
