### ISSUE TITLE
Version 4.0.0.425677not on NuGet?

### ISSUE THREAD

**Issue by SebastianKruseWago** [xamarin/Xamarin.Forms#6216]
The latest listed release of 4.0.0.425677 here: https://github.com/xamarin/Xamarin.Forms/releases is not listed on NuGet. Was it pulled due to an issue or is it just missing on the NuGet page?

**Comment by jcmanke** [comment]
It appears to have been unlisted if you put the version number on the URL: https://www.nuget.org/packages/Xamarin.Forms/4.0.0.425677

**Comment by StephaneDelcroix** [comment]
This is all as it was intended. thanks for paying attention
