### ISSUE TITLE
[Enhancement][Shell] Icon only Shell Bottom Tab Bar.

### ISSUE THREAD

**Issue by davidzhaotopedge** [xamarin/Xamarin.Forms#6220]
## Summary
Should provide a xaml attribute, e.g. DisplayTextOnly, in Shell/TabBar top and bottom. To either display button text or not. The height of Tab Bar should be changed accordingly.

## Current behavior
We can set Tab text to empty, but no text in flyout menu, and height of bottom Tab bar not changed, some space below Icon

**Comment by Mephisztoe** [comment]
I vote for this. Also, when collapsed the user should be able to easily have the app show the tabs' titles again. UWP solves this by adding an ellipsis button (…). Visit [this page](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/app-bars) to see how this works.

**Comment by xamarindevelopervietnam** [comment]
++

**Comment by pfedotovsky** [comment]
There's a workaround for Android with custom renderers. The key is to set 

__bottomView.LabelVisibilityMode = LabelVisibilityMode.LabelVisibilityAuto;_ or
__bottomView.LabelVisibilityMode = LabelVisibilityMode.LabelVisibilityUnlabeled;_

```
using Android.OS;
using Android.Support.Design.BottomNavigation;
using Android.Support.Design.Widget;
using Android.Views;
using Xamarin.Forms.Platform.Android;

namespace App.Droid
{
    public class AndroidShellItemRenderer : ShellItemRenderer
    {
        BottomNavigationView _bottomView;

        public AndroidShellItemRenderer(IShellContext shellContext) : base(shellContext)
        {
        }

        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            var outerlayout = base.OnCreateView(inflater, container, savedInstanceState);

            _bottomView = outerlayout.FindViewById<BottomNavigationView>(Resource.Id.bottomtab_tabbar);
            _bottomView.LabelVisibilityMode = LabelVisibilityMode.LabelVisibilityAuto;

            return outerlayout;
        }
    }
}
```

To use this renderer, you need to create custom ShellRenderer as well:

```
using System;
using Android.Content;
using Conference.Droid;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportRenderer(typeof(Shell), typeof(AndroidShellRenderer))]
namespace App.Droid
{
    public class AndroidShellRenderer : ShellRenderer
    {
        public AndroidShellRenderer(Context context)
            : base(context)
        {
        }

        protected override IShellItemRenderer CreateShellItemRenderer(ShellItem shellItem)
        {
            return new AndroidShellItemRenderer(this);
        }
    }
}
```

**Comment by Amine-Smahi** [comment]
Is this fixed ?

**Comment by chelabitarik** [comment]
10 months later .... Fixed yet ?

**Comment by andre-motta** [comment]
Is there any prevision for this specific fix?

**Comment by pictos** [comment]
I think we can just verify if some tab has Title property, if it doesn't have we can set the `LabelVisibilityMode` property to `LabelVisibilityUnlabeled`. I did some tests here on Android and works fine. On iOS looks like we don´t need to do anything.

**Comment by booooooogdan** [comment]
Can we see this feature in near future?

**Comment by jfversluis** [comment]
We won't be doing this for Forms anymore. Maybe we can make it work in the Community Toolkit, but I think the best chance of seeing this will be in .NET MAUI. This issue has been labeled accordingly, but feel free to open a feature request on the .NET MAUI repo if you're still interested in this. Thank you!
