### ISSUE TITLE
[Bug] Memory leak in Xamarin forms if Android Activity is killed but process is not

### ISSUE THREAD

**Issue by Greg-Freeman** [xamarin/Xamarin.Forms#6221]
### Description
There is an issue that I believe is related to [this](https://forums.xamarin.com/discussion/90940/improve-how-forms-handles-activity-restarts-on-android) which causes leaking memory. But I have found another scenario where this seems to be pretty bad. It is related to objects not being destroyed when a main activity is stopped but the owning process is not.

### Steps to Reproduce

1. Create a Xamarin forms app
2. Create a foreground service for android
3. Deploy the app as debug and make sure the service starts
4. Open recent apps and swipe the app to kill it. The Visual Studio debugger remains connected and the process doesn't die, but the Main Activity seems to be killed as well as the service (it's no longer in developer options -> running services)
5. Reopen the app. Upon reopening the app, the Main Activity goes through its full creation (OnCreate() is called), recreating a new instances of the Forms App class. Therefore it creates the main form again. Any objects created in that form are now duplicates, but the first were never destroyed. This can be shown by adding an object to the form with a static field that is an integer counter that is incremented in the class' constructor.

See attached project for repro.

The service is merely an easy way I've found to reproduce this issue consistently. We started throwing an exception any time we saw an object created twice, and logging those reports to HockeyApp. There are times an app, even without a service, seems to have its activity go out of memory but the process not be killed off. Upon reopening, the exception is thrown.

### Expected Behavior
Lifetime of the forms should be coupled to the lifetime of the main activity, or have some way to get a reference to forms still in memory when the main activity is recreated if they exist.
### Actual Behavior
Forms seem to hang around in memory when the main activity is killed but the process is not
### Basic Information

- Version with issue: 

- Last known good version: N/A
- IDE: Visual Studio 15.9.11
- Platform Target Frameworks: 
  - Android: 9.0 Pie

- Nuget Packages:
- Affected Devices: S8, probably others

### Reproduction Link

[Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/3194495/Bug.zip)

**Comment by Greg-Freeman** [comment]
This link was supposed to be there in my first sentence: https://forums.xamarin.com/discussion/90940/improve-how-forms-handles-activity-restarts-on-android

**Comment by Greg-Freeman** [comment]
I realized there was a possibility that the attached code in the bug report doesn't directly equate to a memory leak. It's possible that created objects were garbage collected, but the static variable still existed and retained its value. So, to better demonstrate the problem, I have attached some code that starts a task which prints a guid to the console. Notice after reopening the app, there are now two guids being printed, but we have now created a second instance of the main page. We know this because the tasks are started in the constructor of the page object.

[Bug (2).zip](https://github.com/xamarin/Xamarin.Forms/files/3195256/Bug.2.zip)

**Comment by PureWeen** [comment]
@Greg-Freeman I don't quite understand your example

```
            return Task.Run(() =>
            {
                while (true) { Debug.WriteLine($"running process {guid.ToString()}"); Task.Delay(1000); }
            });
```

is going to run forever. Nothing is going to stop that task from running outside of a complete process termination. If the app is tombstoned (backgrounded and not terminated) the app process will still keep running that thread indefinitely. 

The only way for that while(true) loop to terminate is for you to signal to it that it needs to terminate this isn't something the GC is going to do for you.

Closing for now but if I'm missing something let me know and we can reopen
