### ISSUE TITLE
RowDefinition & ColumnDefinition Padding

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6223]
Hi,

It will be great if you add Padding to:

1. RowDefinition
2. ColumnDefinition

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by GalaxiaGuy** [comment]
Would you expect this to be one dimensional or two dimensional? i.e., would vertical padding be valid on a column?

**Comment by adrianknight89** [comment]
If I remember correctly, WPF does not have this feature. Why not add margin and padding to the row/column element? Adding these properties directly to RowDefinition and ColumnDefinition will only make the code unnecessarily more complex to maintain.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
