### ISSUE TITLE
RowDefinition & ColumnDefinition BackgroundColor

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6224]
Hi,

It will be great if you add BackgroundColor to:

RowDefinition
ColumnDefinition

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by StephaneDelcroix** [comment]
Thanks for your suggestion. Unfortunately this proposal doesn't fit with the conceptual model of layout, and implementing it on great would create a shear that, in the end, might destroy space and time as we know them.
