### ISSUE TITLE
AppearingAnimation & DisappearingAnimation

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6225]
Hi,

Please add the following to the ContentView and ContentPage:

AppearingAnimation: Show the ContentPage and the ContentView with animation, eg. FadeIn, SlideLeft, SlideTop, etc..

DisappearingAnimation: close the ContentPage and the ContentView with animation, eg. FadeIn, SlideLeft, SlideTop, etc..

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
