### ISSUE TITLE
[Bug] Syncfusion.Xamarin.SfPdfViewer 17.1.0.47 nuget package gives error in iOS

### ISSUE THREAD

**Issue by RongonC** [xamarin/Xamarin.Forms#6228]
### Description

Error description -Could not compile the file(s) '/Users/username/Library/Caches/Xamarin/mtbs/builds/Project.iOS/dbe92220a462dc43fa3b5c385de162c4/obj/iPhone/Debug/mtouch-cache/armv7/Syncfusion.Pdf.Portable.dll.s'. Please file a bug report at http://bugzilla.xamarin.com

Project - Project.iOS

Note that the same feature is working perfectly in Android and I have already included these lines:
Syncfusion.SfPdfViewer.XForms.iOS.SfPdfDocumentViewRenderer.Init();
 Syncfusion.SfRangeSlider.XForms.iOS.SfRangeSliderRenderer.Init();

in the AppDelegate.cs file in the iOS project, still I get the above mentioned error

### Steps to Reproduce

1.  Install the Syncfusion.Xamarin.SfPdfViewer nuget package in the main project, Android project and iOS project

2. Add these lines in the AppDelegate.cs in the iOS project:
Syncfusion.SfPdfViewer.XForms.iOS.SfPdfDocumentViewRenderer.Init();
Syncfusion.SfRangeSlider.XForms.iOS.SfRangeSliderRenderer.Init();

3.  Place the control and write the logic to display the PDF

### Expected Behavior
PDF should be displayed

### Actual Behavior
DLL error in iOS: 
Could not compile the file(s) '/Users/username/Library/Caches/Xamarin/mtbs/builds/Project.iOS/dbe92220a462dc43fa3b5c385de162c4/obj/iPhone/Debug/mtouch-cache/armv7/Syncfusion.Pdf.Portable.dll.s'. Please file a bug report at http://bugzilla.xamarin.com

### Basic Information

- Version with issue: 17.1.0.47
- Last known good version:
- IDE: Visual Studio 2017

- Nuget Packages: Syncfusion.Xamarin.SfPdfViewer
- Affected Devices: iOS

**Comment by samhouts** [comment]
@RongonC  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by GuidoNeele** [comment]
Are you remote building on your Mac? Had the same issue when building iOS project from VS on Windows. Building on the Mac itself did work for me.

**Comment by samhouts** [comment]
@GuidoNeele  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by GuidoNeele** [comment]
Tried to reproduce it but couldn't. Tested with v17.1.0.47 and V17.1.0.51 of SfPdfViewer but both times it worked like expected. Did however install some updates to Xamarin.iOS which might have solved the issue. Performed the tests with Xamarin.iOS Version 12.4.0.64 and 12.8.0.2 (Visual Studio Community). Both worked.

**Comment by samhouts** [comment]
@GuidoNeele Thanks for the update! 

@RongonC Can you confirm that updating Xamarin.iOS does or does not resolve your issue? Thanks!

**Comment by samhouts** [comment]
@RongonC  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
