### ISSUE TITLE
[Bug] Preferences loosing data when debuging on Android

### ISSUE THREAD

**Issue by aocipriano** [xamarin/Xamarin.Forms#6229]
### Description
Data saved on preferences using Xamarin Essentials is not preserved after start debug session even when the option "Preserve application data cache on device between deploys" is marked.

### Steps to Reproduce

1. I´m using this code to save data in Preferences:
  Preferences.Set("configuration", JsonConvert.SerializeObject(configuration));
2. Start debug session on a real device.
3. Save data into Preferences. When I close the app and reopen it, the data is still saved in Preferences, but if I modify anything in code and start another debug session, the data is lost.

### Basic Information

- Version with issue: 
   Xamarin Forms: 3.6.0.344457
   Xamarin Essentials: 1.1.0
- IDE: Visual Studio Community 2017 (15.9.12)
- Platform Target Frameworks: 
  - Android: API Level 28
- Nuget Packages:
   Xamarin Forms: 3.6.0.344457
   Xamarin Essentials: 1.1.0
- Affected Devices:
 Asus Zenfone 3

**Comment by jamesmontemagno** [comment]
Wasn't able to reproduce this at all. Works great for me on my device. 
[App29.zip](https://github.com/xamarin/Xamarin.Forms/files/3213512/App29.zip)

**Comment by jamesmontemagno** [comment]
All Xamarin.Essentials issues should be over at http://github.com/xamarin/essentials

**Comment by aocipriano** [comment]
Hi @jamesmontemagno 
I noticed that it happens when I disconnect my device from USB and connect it again.
So VS uninstalls the app and installs it again, that´s why my preferences data is lost.
I had same problem using Application.Current.Properties class instead of Xamarin Essentials Preferences class.

**Comment by jamesmontemagno** [comment]
Yeah, if the app is uninstalled then it would be lost. So working as expected there. Seems like it shouldn't uninstall your app though, can you click the report a problem and report it through Visual Studio please after you reproduce it.
