### ISSUE TITLE
ListView in StackLayout collapses when adding RowHeight in WPF and Mac

### ISSUE THREAD

**Issue by alataffective** [xamarin/Xamarin.Forms#6234]
### Description
When adding RowHeight to a ListView contained in a StackPanel, the ListView collapses vertically.

### Steps to Reproduce

1. Create the following XAML
```
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="XamarinExample.MainPage"
    >
    <StackLayout>
        <StackLayout>
            <ListView ItemsSource="{Binding Things}">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <ViewCell>
                            <Label Text="{Binding Name}" />
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
        </StackLayout>
        <StackLayout Orientation="Horizontal">
            <Button Text="One Button"></Button>
            <Button Text="Two Button"></Button>
        </StackLayout>
    </StackLayout>
</ContentPage>
```

2. Run the application. The ListView expands vertically to fill the available space.
3. Add a RowHeight value to the ListView, e.g.
```
...
            <ListView ItemsSource="{Binding Things}" RowHeight="20">
...
```

### Expected Behavior
The ListView rows have a height corresponding to the RowHeight value but the layout is unchanged.

### Actual Behavior
The ListView collapses vertically.

### Basic Information

- Version with issue: 4.0.0.394984-pre10
- Platform Target Frameworks: WPF, Mac

### Screenshots
Without RowHeight
![Without RowHeight](https://user-images.githubusercontent.com/18467932/58089521-e0f91880-7bbc-11e9-8b37-6e4fc33fbe5a.png)

With RowHeight
![With RowHeight](https://user-images.githubusercontent.com/18467932/58089532-e8202680-7bbc-11e9-8243-37e99b50f880.png)

### Reproduction Link
https://github.com/alataffective/ListView-in-StackLayout-collapses-when-adding-RowHeight

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
