### ISSUE TITLE
[Bug] Keyboard remains visible after tapping on picker control

### ISSUE THREAD

**Issue by rhouweling** [xamarin/Xamarin.Forms#6235]
### Description
When the keyboard is visible because an Entry is focused, tapping on a Picker results in the keyboard remaining open. This confuses users because after selecting an item in the pickers, the picker selection popup is closed with the keyboard still open. When starting to type, the picker options open again.

### Steps to Reproduce

1. Tap on an Entry, the keyboard appears
2. Tap on a Picker, the keyboard is still visible in the background
3. Select a Picker item, the popup with picker items closes and the keyboard is visible while the Picker control is focused

### Expected Behavior
The keyboard closes when focusing a Picker control

### Actual Behavior
The keyboard remains open when focusing a Picker control

### Basic Information

- Version with issue: Any version starting from 3.3.0.912540 up to 3.6.0.344457. 
- Last known good version: 3.2.0.871581
- IDE: VS2017 15.9.11
- Platform Target Frameworks: 
  - Android: 8.1, 9.0

- Android Support Library Version: See attached project
- Nuget Packages: See attached project
- Affected Devices: Android

### Reproduction Link

See uploaded project
[ReproApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3202194/ReproApp.zip)

**Comment by ddillmancode** [comment]
This issue still exists with Android 7.1 and 8.0 as tested from both of my Android devices. We are currently working on a project where the user can enter information into an entry field and a picker. If the user selects an entry field and then selects a picker  (without pressing the done/check mark on the entry field keyboard), the entry field keyboard remains open with the picker open. Is it possible to implement the same fix for 8.1 and 9.0 to these older versions as well? Thank you.
