### ISSUE TITLE
Shell's Hamburger button not show in ios platform

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#6236]
After set `FlyoutBehavior="Flyout"`

Android platform has the hamburger button at left top.
iOS platform didn't has the hamburger button

![android](https://user-images.githubusercontent.com/16309962/58091971-8b912b80-7bfd-11e9-85de-13bf2d817098.jpg)
![ios](https://user-images.githubusercontent.com/16309962/58091973-8b912b80-7bfd-11e9-80ff-08ac62fb7e88.jpg)

**Comment by jingliancui** [comment]
And my ios test simulator is iPhone 5s 12.2

**Comment by samhouts** [comment]
@jingliancui Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jingliancui** [comment]
@samhouts Hi,glad to tell you that this bug is shown within Xamarin.forms 3.6.
After update to the latest vs version today ,the Xamarin.forms project template was update to the release version 4.0 ,and the issue was fixed.
