### ISSUE TITLE
ListView items don't show when NSTableView.SelectionDidChange handler added

### ISSUE THREAD

**Issue by alataffective** [xamarin/Xamarin.Forms#6237]
### Description
When adding a SelectionDidChange event handler to the NSTableView returned by ListViewRenderer.NativeTableView, the list items no longer display.

### Steps to Reproduce

1. Create a Xamarin.Forms application with a MacOS head.
2. Add a ListView and populate with items.
3. Run the application and see the items displayed.
4. Create a ListView effect.
5. In the MacOS implementation of the effect, add the following
```
    protected override void OnAttached()
    {
        var nativeTableView = ((ListViewRenderer)Container).NativeTableView;
        nativeTableView.SelectionDidChange += (sender, e) => { }; 
    }
```

### Expected Behavior
No change.

### Actual Behavior
The list items are no longer shown.

### Basic Information
- Version with issue: 4.0.0.394984-pre10
- Platform Target Frameworks: MacOS

### Screenshots
Without event handler
![Screenshot 2019-05-21 at 12 44 00](https://user-images.githubusercontent.com/18467932/58093435-6af9af00-7bc6-11e9-8c20-56dd6772fb1c.png)

With event handler
![Screenshot 2019-05-21 at 12 45 02](https://user-images.githubusercontent.com/18467932/58093450-73ea8080-7bc6-11e9-96b6-517ec37299d0.png)

### Reproduction Link
https://github.com/alataffective/ListView-items-don-t-show-when-NSTableView.SelectionDidChange-handler-added

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
