### ISSUE TITLE
ShellItem not show correct within Shell in ios

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#6238]
my test simulator is iPhone 5s 12.2,
The top of the shellitem is Occlusioned ,but It's fine in android platform
as the image shown below :
![ios](https://user-images.githubusercontent.com/16309962/58094027-4e7b6800-7c02-11e9-8606-ca67df6722d9.jpg)
![ios2](https://user-images.githubusercontent.com/16309962/58094029-4e7b6800-7c02-11e9-9999-1a4ce470daf2.jpg)

**Comment by samhouts** [comment]
@jingliancui Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jingliancui** [comment]
@samhouts Hi,glad to tell you that this bug is shown within Xamarin.forms 3.6.
After update to the latest vs version today ,the Xamarin.forms project template was update to the release version 4.0 ,and the issue was fixed.

**Comment by jingliancui** [comment]
Than found that the newest version project shell template code (Xamarin.forms4) have the issue in the ios platform as below images, android is fine but ios not good :

![android1](https://user-images.githubusercontent.com/16309962/58160401-f8b1c900-7cb0-11e9-8d0a-d471113a6412.jpg)
![android2](https://user-images.githubusercontent.com/16309962/58160424-08c9a880-7cb1-11e9-8621-8fca4de7eb04.jpg)
![ios1](https://user-images.githubusercontent.com/16309962/58160451-18e18800-7cb1-11e9-979c-95867fcbaa5d.jpg)
![ios2](https://user-images.githubusercontent.com/16309962/58160481-25fe7700-7cb1-11e9-99bb-92137e129e3b.jpg)

step:
1. create shell project use vs 2019 latest version (it should be use Xamarin.forms 4)
2. Chanage `Tabbar`  to `ShellItem`  at AppShell.xaml (this will show the hamburger button correctly)
3. run application 
4. click any item of the fist page shown.
5. found the ui show in ios not complete but android is complete.

**Comment by jmeyerworms** [comment]
hello , i have the same issue with xamarin forms 4.0 and prev 3.6 .  i use the same template .
android simulator it looks fine but with ios real device it looks wrong.
my test device is a ios 7 .

**i have 2 images uploaded to compare.
ios the small image directly from device vs android simulator.**

![1](https://user-images.githubusercontent.com/33936487/58214611-b0b59500-7cf6-11e9-9764-c836684b5631.png)
![2](https://user-images.githubusercontent.com/33936487/58214613-b0b59500-7cf6-11e9-9aa4-039b57d2b90b.png)

**Comment by HobDev** [comment]
@jingliancui @pauldipietro @samhouts @jmeyerworms 

I resolved this issue by adding two lines of xaml code in the ContentPage.

`xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
              ios:Page.UseSafeArea="true"`

**Comment by HobDev** [comment]
The copy of the concerned page is this:

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
              xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core" 
              ios:Page.UseSafeArea="true" 
             x:Class="sample.Views.ItemDetailPage" 
             Title="{Binding Title}">`

**Comment by jingliancui** [comment]
@HobDev Wow,It's work! Thanks.
And Now I have another question about the "footer" of the tabs.
Or I close these issue and open a new issue?
Is it have any solution to hide the tabs when I navigate to another page.
for example :
After click any item in first page ,then hide tabs in the second page,as image shown
![ios1](https://user-images.githubusercontent.com/16309962/58230201-3cb2d580-7d66-11e9-891b-89bd2ed709a3.jpg)

**Comment by HobDev** [comment]
@jingliancui 
Add the following line in any ContentPage where you want to hide the TabBar:
`Shell.TabBarIsVisible="false" `

**Comment by jingliancui** [comment]
It's done.Thansk again and hope document publish asap 👍 👍 

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="DestinyPerson.Views.ItemDetailPage"
             xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"
             ios:Page.UseSafeArea="true"
             Title="{Binding Title}">

    <Shell.TabBarIsVisible>false</Shell.TabBarIsVisible>

...........

```

![ios1](https://user-images.githubusercontent.com/16309962/58231412-89e47680-7d69-11e9-8692-53b2dbce7737.jpg)
