### ISSUE TITLE
Real time updates are not working in Bindable Layout

### ISSUE THREAD

**Issue by Sangeetha-Raju** [xamarin/Xamarin.Forms#6240]
**Real time updates are not working in Bindable Layout**

### Description
Real time updates like Move and Insert are not working in Bindable Layout

### Steps to Reproduce
**Issue 1**
1. Run the attached sample
2. Click the Insert button, the item added in the last instead of the provided index.
**Issue 2**
1. Run the attached sample
2. Click the Move button, the item doesn't move to the corresponding index.

### Expected Behavior
**Issue 1**
The item should insert in the corresponding index.
**Issue 2**
If we move the item from 3 to 1st index, the items should arrange in the order of (1,4,2,3,5).
Also, if we move the item from 1 to 3rd index, the items should arrange in the order of (1,3,4,2,5) 

### Actual Behavior
**Issue 1**
The item inserted in the last index instead of corresponding index.
**Issue 2**
If we move the item from 3 to 1st index, the items arranged in the order of (1,4,3,5,2).
Also, if we move the item from 1 to 3rd index, the items arranged in the order of (1,4,3,2,5) 

### Basic Information
Issue occurs in all the platforms.

### Screenshots
Move from 3 to 1st index
![Move](https://user-images.githubusercontent.com/46016770/58101631-a2378280-7bfd-11e9-83c7-a7d29c9cb126.png)

Insert at 0th index
![Insert](https://user-images.githubusercontent.com/46016770/58101632-a2378280-7bfd-11e9-977d-575a1b15d860.png)

### Reproduction Link
[BindableLayout.zip](https://github.com/xamarin/Xamarin.Forms/files/3202885/BindableLayout.zip)

**Comment by andreinitescu** [comment]
This is fixed in the latest released v4.

**Comment by lukeid123** [comment]
If anyone happens to come across this issue where Bindable Layout using a StackLayout is not updating correctly when moving, removing, adding elements when IsVisible = false, call ForceLayout() when you set IsVisible = true.
