### ISSUE TITLE
In Xamarin.Forms TabbedPage icon and text overlap when ToolBarPlacement is set to Bottom

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6242]
Created a TabbedPage by selecting it from the Add-&gt;New Item menu in my Xamarin.Forms app. Changed the color and added some pages. It displays right when ToolBarPlacement is set to Default or Top but setting it to Bottom the text and the icon overlap. Tried to use some blank ContentPage as children to check if the problem was in my pages but it's not. Even setting the ToolBarPlacement in xaml didn't work out as the bar displays at the bottom but the overlap still persists. .xaml, .xaml.cs and screenshot attached.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/573471/in-xamarinforms-tabbedpage-icon-and-text-overlap-w.html
VSTS ticketId: 895504_
_These are the original issue comments:_

xxenrico97x on 5/18/2019, 05:40 AM (3 days ago): Files are attached but private to Microsoft. There's an album containing the screenshot:  https://imgur.com/a/12BfrLm 
Visual Studio Feedback System on 5/19/2019, 06:44 PM (39 hours ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by EnricoBarbieri1997** [comment]
https://we.tl/t-RFkXwr0mss
That was the project having the issue but in the last 3 days, a new update came out and fixed it. That's the zip with the version having the problem in case you need it to fix it in that exact version.

**Comment by samhouts** [comment]
@EnricoBarbieri1997 Thanks! Let us know if you find any other issues!!
