### ISSUE TITLE
Android NavigationBar is gone

### ISSUE THREAD

**Issue by muhammetsahin** [xamarin/Xamarin.Forms#6248]
### Description
Hi there,
 i updated Xamarin.Forms 4 then navigationbar is gone android. ios works

### Expected Behavior
Show navigation bar

### Actual Behavior
Gone navigation bar
### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version:
- IDE: Visual studio 2019 16.0.4
- Platform Target Frameworks: 
 
  - Android:  9
  

### Screenshots

it worked xamarin.forms 3.6.x
![image](https://user-images.githubusercontent.com/2045788/58129801-47b11d00-7c23-11e9-82c4-74a4e49e92cf.png)

But now looking like this:
![image](https://user-images.githubusercontent.com/2045788/58129822-54ce0c00-7c23-11e9-9e98-1ae65ed8870b.png)

I did not change anything except xamarin.forms 

Any idea?

Thanks.

**Comment by samhouts** [comment]
@muhammetsahin Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by muhammetsahin** [comment]
Ok it is not bug i tihnk my fault i did wrong my tabbed page xaml.

Here is my main page xaml.

![image](https://user-images.githubusercontent.com/2045788/58156097-0437cc80-7c7e-11e9-9fc6-27c7d56ad6fb.png)

And then i changed this.
![image](https://user-images.githubusercontent.com/2045788/58156135-19acf680-7c7e-11e9-8eaa-1241effecf3b.png)


Build and run here is result:
![image](https://user-images.githubusercontent.com/2045788/58156175-30534d80-7c7e-11e9-8ab8-a42819c53daa.png)


Thanks. 

I think this issue can close.
