### ISSUE TITLE
[Enhancement] Improve exception message on bindable layout when you use the wrong type as a template

### ISSUE THREAD

**Issue by wadebaird** [xamarin/Xamarin.Forms#6249]
### Description
I added the code below to the standard Master / Details Project created by VS to test out an issue I was seeing with BindableLayout and I encountered an InvalidCastException the BindableLayoutController.CreateViewItem

### Steps to Reproduce

1. Create a Master / Details Xamarin.Forms project within VS
2. Replace the ItemsPage Content with this:
`<StackLayout x:Name="ItemsStackView"
                BindableLayout.ItemsSource="{Binding Items}"
                VerticalOptions="FillAndExpand">
            <BindableLayout.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <StackLayout Padding="10">
                            <StackLayout>
                                <Label Text="{Binding Text}" 
                                        LineBreakMode="NoWrap" 
                                        Style="{DynamicResource ListItemTextStyle}" 
                                        FontSize="16" />
                            </StackLayout>
                            <StackLayout x:Name="ItemDetail" IsVisible="False">
                                <Label Text="{Binding Description}" 
                                        LineBreakMode="NoWrap"
                                        Style="{DynamicResource ListItemDetailTextStyle}"
                                        FontSize="13" />
                            </StackLayout>
                        </StackLayout>
                    </ViewCell>
                </DataTemplate>
            </BindableLayout.ItemTemplate>
        </StackLayout>`
3. Load the form on an iOS device, exception occurs in Loading the items.

### Expected Behavior
Forms loads with a bindable StackLayout

### Actual Behavior
InvalidCastException occurs with this call stack:
 	0x9 in Xamarin.Forms.BindableLayoutController.CreateItemView at D:\a\1\s\Xamarin.Forms.Core\BindableLayout.cs:191,5	C#
 	0x20 in Xamarin.Forms.BindableLayoutController.CreateItemView at D:\a\1\s\Xamarin.Forms.Core\BindableLayout.cs:184,4	C#
 	0x19 in Xamarin.Forms.BindableLayoutController. at D:\a\1\s\Xamarin.Forms.Core\BindableLayout.cs:210,33	C#
 	0x84 in Xamarin.Forms.Internals.NotifyCollectionChangedEventArgsExtensions.Apply at D:\a\1\s\Xamarin.Forms.Core\Internals\NotifyCollectionChangedEventArgsExtensions.cs:39,7	C#
 	0x46 in Xamarin.Forms.BindableLayoutController.ItemsSourceCollectionChanged at D:\a\1\s\Xamarin.Forms.Core\BindableLayout.cs:209,4	C#
 	0x1B in System.Collections.ObjectModel.ObservableCollection<App1.Models.Item>.OnCollectionChanged at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:263,21	C#
 	0x9 in System.Collections.ObjectModel.ObservableCollection<App1.Models.Item>.OnCollectionChanged at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:338,13	C#
 	0x23 in System.Collections.ObjectModel.ObservableCollection<App1.Models.Item>.InsertItem at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/src/Xamarin.iOS/external/corefx/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs:196,13	C#
 	0x23 in System.Collections.ObjectModel.Collection<App1.Models.Item>.Add at /Library/Frameworks/Xamarin.iOS.framework/Versions/12.8.0.2/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/ObjectModel/Collection.cs:73,13	C#
>	0x100 in App1.ViewModels.ItemsViewModel.ExecuteLoadItemsCommand at C:\Users\zbjj9h\source\repos\App1\App1\App1\ViewModels\ItemsViewModel.cs:45,21	C#

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: ??
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 8.1
  - UWP:  N/A 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by wadebaird** [comment]
Found out the root of the issue is having the ViewCell in the <DataTemplate> I would expect this to either work or raise a compile time error.

Thanks.

**Comment by PureWeen** [comment]
ViewCell is very specific to a ListView

The BindableLayout works with layouts so if you just remove the surrounding ViewCell and just use the StackLayout then you shouldn't have any issues

I've changed this issue over to an enhancement as the behavior is expected but how it fails could be improved upon

**Comment by wadebaird** [comment]
There is no way an InvalidCastException coming from the .Net framework is expected behavior.  The user would have no idea to remove the ViewCell with this type of behavior.

This is an unprofessionally worded response.

**Comment by wadebaird** [comment]
As I stated above I understand that the ViewCell was not appropriate here, however, an InvalidCastException coming from the .Net framework can hardly be stated as expected behavior.

There should be a compilation error preventing this from happening as well as a runtime check not allowing this scenario to be created programmatically as well.  I personally would not consider this an enhancement as it is clearing a bug in the system, but do with it as you must.

**Comment by andreinitescu** [comment]
I gave some thought to this and I don't think it's worth adding a check whether the casting to View is going to work. I'm always for adding debug messages which spares our time and effort, but this isn't a good case.

1. It's unfortunate that the "ViewCell" name makes us think of a "View". "ViewCell" is actually an Element, it's not a View.  
  All the built-in layouts StackLayout, Grid, FlexLayout etc. are all derived from `Layout<View>`, so it's not reasonable to expect a ViewCell to work with BindableLayout. It's like expecting a ControlTemplate to work in place of a DataTemplate, they're just different things.

2.  I was also bitten many times by the fact we can't simply reuse a DataTemplate both in a layout and in a ListView. **I wish ListView could accepted a DataTemplate as ItemTemplate without the need to have ViewCell in the root.**

3. ViewCell and ListView are a thing of a past with CollectionView, for many reasons.
