### ISSUE TITLE
Not able to include shell control 

### ISSUE THREAD

**Issue by jashif** [xamarin/Xamarin.Forms#6251]
Hi

I tried the latest forms package in a new forms project . when tried to include shell control and added shellcontent as child . It still says it accept shellitem as its child. while building getting compile error also.

Tried to run the tailwind traders app. 

Error from visual studio 

Error	XLS0503	A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'.	TailwindTraders.Mobile	TheShell.xaml	69	

![image](https://user-images.githubusercontent.com/1052953/58163650-a195ff00-7c84-11e9-9769-46b9bd0c31cb.png)

**Comment by samhouts** [comment]
Duplicate of #3864
