### ISSUE TITLE
[Bug] Flyout of Shell not work with Tabbar

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#6252]
step:
vs 2019  create a shell project ,it will be use the Xamarin.forms 4.0 package.
then 
Set FlyoutBehavior="Flyout"  at shell
run the application.
hamburger button not show ,if use mouse simulate gesture , flyout still does not show.

and modify above code 
```
<TabBar>
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
</TabBar>
```

To this:
```
<ShellItem>
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
</ShellItem>
```

Flyout work fine.

Didn't know if is a bug between tabbar and flyout

**Comment by HobDev** [comment]
@jingliancui  @pauldipietro  @kingces95 
This is a expected behaviour in shell. Read **Notable Changes**  shell  at [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.0/4.0.0](url)
It would be better to change this bug report to feature request

**Comment by jingliancui** [comment]
@HobDev Got it,thanks, and I will close this issue ,hoping the document complete asap publish to docs.microsoft.com
