### ISSUE TITLE
[Bug] [Android] ContextActions icon not working

### ISSUE THREAD

**Issue by melimion** [xamarin/Xamarin.Forms#6258]
### Description
Icons are not displayed for ContextActions on Android

Looks like issue was introduced in https://github.com/xamarin/Xamarin.Forms/pull/6062

### Steps to Reproduce

1. Run control gallery app from Xamarin.Forms solution
2. Find "ContextActions List Gallery" page and open it
3. Hold any item to open context actionmenu
4. No icon

### Expected Behavior
Calculator icon displayed for first item

### Actual Behavior
No icon displayed

### Basic Information

- Version with issue: 4.0 release
- Last known good version: 4.0-pre10

**Comment by melimion** [comment]
Here ApplyDrawableAsync called with renderer=null https://github.com/xamarin/Xamarin.Forms/blob/48885e0331e3b6427eaf64724cbbac54bce88c68/Xamarin.Forms.Platform.Android/ResourceManager.cs#L124

and here renderer is checked for null
https://github.com/xamarin/Xamarin.Forms/blob/48885e0331e3b6427eaf64724cbbac54bce88c68/Xamarin.Forms.Platform.Android/ResourceManager.cs#L136

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/58216901-f98c3000-7c9b-11e9-971e-b6c7b380879c.png)

**Comment by pauldiston** [comment]
Just to be clear, is this the same issue where Toolbar Item images are no longer displaying, just text?

**Comment by PureWeen** [comment]
@pauldiston it should be but I'll make sure to test that scenario as well just to be sure! Thanks for reminding me

**Comment by PureWeen** [comment]
Actually @pauldiston looking at the issue here https://github.com/xamarin/Xamarin.Forms/issues/6296 the problem there is not using appcompat

If you're using non appcompat and you still use the old Icon field then the images should still show up

**Comment by pauldiston** [comment]
> @pauldiston looking at the issue here #6296 the problem there is not using appcompat
> 
> If you're using non appcompat and you still use the old Icon field then the images should still show up

@PureWeen Just for info, I was using the old Icon field however the images were not showing up, which prompted my investigation into why, which lead me to these two issue logs.

**Comment by DescoFieldEdge** [comment]
> @pauldiston looking at the issue here #6296 the problem there is not using appcompat
> 
> If you're using non appcompat and you still use the old Icon field then the images should still show up

I'm using the old Icon field with non appcompat and image is not showing for the ToolBarItem.
