### ISSUE TITLE
[Bug] FlyoutBehavior not working Xamarin 4 release

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#6261]
### Description
After update pre10 to release Xamarin 4, the shell not used  my FlyoutBehavior="Locked" parameter.

### Expected Behavior
Use FlyoutBehavior="Locked"

### Actual Behavior
Use the default value every time

### Basic Information

- Version with issue: Xamarin.Forms 4.0
- Last known good version: Xamarin.Forms pre10
- Android: 27

**Comment by Hasanajouz** [comment]
Yes even if you set it to "Disabled" it will not work
As i noticed till now
if you use
FlyoutItem as your shell then you will have a side menu
if you use 
TabBar you will not have it.

**Comment by jfversluis** [comment]
Verified in the linked issue that this doesn't work on iOS as well as Android

**Comment by MSiccDev** [comment]
Is there any workaround I can implement in the meantime? I have two apps that are impacted (one update, one new).

**Comment by MaxenceSAUNIER** [comment]
My impacted project is still in development, so, I haven't search any workaround for the moment for my part.

**Comment by MSiccDev** [comment]
In my case, this one prevents me to upload an update to the Google Play Store... :/

**Comment by Onotseike** [comment]
> Yes even if you set it to "Disabled" it will not work
> As i noticed till now
> if you use
> FlyoutItem as your shell then you will have a side menu
> if you use
> TabBar you will not have it.

I am currently using the TabBar and I still have the Flyout

**Comment by v2vehooi** [comment]
may i know this issue solve already ? even as at today, when i create tab bar using xamarin form shell. i'll still get the hamburger menu on the top navigation bar although i already add : Flyoutbehavior to disabled.
Please help. thank you

**Comment by jfversluis** [comment]
@v2vehooi thank you for asking.

I see the PR for this is merged into 4.2.0 so it should be part of the 4.2 service released which should be released soon

**Comment by coffeecoded** [comment]
Is working as expected in the latest update. Tested on Android.

**Comment by AmirImam** [comment]
Still not working on android on Xamarin.Forms 4.2.0.709249

**Comment by PureWeen** [comment]
@AmirImam it's fixed on the latest version *4.2.0.815419*

**Comment by aloptrbl** [comment]
same here the FlyoutBehavior Disabled not working!

**Comment by jfversluis** [comment]
@aloptrbl can you confirm the Xamarin.Forms version you are using? If it is still not working in the latest 4.2 package please open a new issue with all the required information and reproduction project.

**Comment by lambo-murcielago** [comment]
@jfversluis the FlyoutBehavior disabled is not working for me on android. I have tried it with Xamarin.Forms version 4.2.0.848062, 4.2.0.709249. @PureWeen I tried it with 4.2.0.815419 also.

**Comment by jfversluis** [comment]
Thanks for letting us know @lambo-murcielago. As mentioned in my comment, would it be possible to open a new issue where you provide all the info and a reproduction project for us to look at?

Thanks!

**Comment by Amine-Smahi** [comment]
Still same problem , come on guys

**Comment by Basti82b** [comment]
See #7576

**Comment by ColeXm** [comment]
Test on XF 4.4.0.991537 and 4.2.0.815419(both on iOS and Android )  , still not works .

**Comment by SebastianSossna** [comment]
You rather disable the behavoir by setting it disabled for the FlyoutItem, than for the Shellcontent. Like this:
```
<FlyoutItem IsVisible="False" Shell.FlyoutBehavior="Disabled">
        <ShellContent Route="LoadingPage"
                  ContentTemplate="{DataTemplate local:LoadingPage}"/>
</FlyoutItem>
```
