### ISSUE TITLE
ListView selected item not easily visible on Mac

### ISSUE THREAD

**Issue by alataffective** [xamarin/Xamarin.Forms#6263]
### Description
When selecting a ListView item on Mac only a thin blue border is seen. 

### Steps to Reproduce
1. In a Xamarin.Forms that targets macOS, create a ListView, e.g.
```
 <ListView ItemsSource="{Binding Names}" />
```
2. Run the application on a Mac.
3. Select an item in the list.

### Expected Behavior
The background color of the selected item changes to blue.

### Actual Behavior
Only a very thin blue border is visible.

### Basic Information

- Version with issue: 4.0.0.394984-pre10
- Platform Target Frameworks: macOS

### Screenshots
![Screenshot 2019-05-22 at 15 40 50](https://user-images.githubusercontent.com/18467932/58183877-00b93b00-7ca8-11e9-899e-12152e0b55f1.png)

### Additional Information
If setting the background color to transparent, the expected selection background color is then visible.
e.g. 
```
<ListView ItemsSource="{Binding Names}" BackgroundColor="Transparent"/>
```
![Screenshot 2019-05-22 at 15 44 54](https://user-images.githubusercontent.com/18467932/58184214-95bc3400-7ca8-11e9-84c7-8fb0923a66dd.png)

However, this is problematic as it is not possible to set the color of the list independently of the window color provided by the OS theme.

![Screenshot 2019-05-22 at 15 47 59](https://user-images.githubusercontent.com/18467932/58184436-ff3c4280-7ca8-11e9-89ea-8d53d1c191cd.png)

Even wrapping the ListView in a Grid or StackLayout with an explicitly set background color seems unable to overlay the color set by the theme.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
