### ISSUE TITLE
[Bug] ContentPage.ControlTemplate not working in Xamarin WPF 

### ISSUE THREAD

**Issue by lekia** [xamarin/Xamarin.Forms#6264]
### Description
According to Microsoft Docs, a ControlTemplate can be assigned to a ContentPage rather than a ContentView.
I assigned the ControlTemplate to a ContentPage. It worked without any issue in UWP, but when I deployed to WPF, the ControlTemplate was totally ignored. Everything in the ControlTemplate did not appear in the view tree, but the Content appeared even without a ContentPresenter, as if I had not set a ControlTemplate.
A ContentView with ControlTemplate worked fine in WPF, however. But I think a ContentView in a ContentPage is not a good practice due to performance.

### Steps to Reproduce

1. Set something to the ControlTemplate property of a ContentPage.
2. Deploy to WPF.

### Expected Behavior
Show everything in the ControlTemplate like what it does when deploys to UWP.

### Actual Behavior
Setting the ControlTemplate property of a ContentPage is the same as not to.

### Basic Information

- Version with issue: 4.0.0.346134-pre9
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - WPF:  .NET Framework 4.7.2
- Nuget Packages:
- Affected Devices:

**Comment by kingces95** [comment]
Could you kindly attach a zipped solution file with a project that reproduces the unexpected behavior? Thanks.

**Comment by lekia** [comment]
[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3219019/TestApp.zip)
As you could see in the sample, I simply put the ControlTemplate contains only a single text but nothing else (including ContentPresenters) to a ContentPage, and put a text and a button to the Content of the ContentPage.
Usually we will not see anything in the Content but only text in the ControlTemplate, as UWP project does. But when deploy the WPF project, you will not see the text in the ControlTemplate but the Content which includes a button, as if the ControlTemplate had not been set.
It works fine in the Workaround Page for both the UWP and the WPF project, where I put the ControlTemplate to a ContentView rather than a ContentPage.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
