### ISSUE TITLE
[Bug] [Shell] XF4.0 official AppShell BaseStyle targets ShellItem Instead of TabBar 

### ISSUE THREAD

**Issue by Hasanajouz** [xamarin/Xamarin.Forms#6265]
### Description
BaseStyle should target TabBar instead of  ShellItem
 
### Steps to Reproduce

1. Create new xamarin forms shell project
2. Open AppShell.xaml
3. Line 28: you will fine TargetType="ShellItem"

### Expected Behavior
Line 28: TargetType="TabBar"

**Comment by PureWeen** [comment]
@Hasanajouz thank you for logging an issue for this one! We've updated the templates and they will be fixed in an upcoming release of VS
