### ISSUE TITLE
[Bug] Setting a picker BackgroundColor through XAML binding or programmatically in code behind crashes app

### ISSUE THREAD

**Issue by norton287** [xamarin/Xamarin.Forms#6267]
### Description
After upgrading nuget to Xamarin.Forms 4.0.0.425677, code that worked previously on Android now causes the app to crash.  Setting the BackgroundColor of a picker through XAML binding or through code behind causes the app to crash.  It works fine in my iOS and UWP projects and bizarrely works fine on the Android Pie simulator.  The crash occurs on my Samsung Galaxy S9+ on API 28.
 
### Steps to Reproduce

1.  Create an XAML picker bound to a list, set the BackGroundColor binding to a field in the item list or programmatically set the BackgroundColor through the code behind.
2. Install to a real Samsung S9+ running API 28

3.  When activating the picker which changes the background color the crash will happen

### Expected Behavior
On selection in the picker list the backgroundcolor should change to the appropriate bound color.

### Actual Behavior

When selecting an item from the picker list upon attempting to set the picker backgroundcolor the app crashes

### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forms 4.0.0.394984-pre10
- IDE: Visual Studio 2019 Enterprise
- Platform Target Frameworks: 8.0 to 9.0
  - iOS:  
  - Android: 9
  - UWP:   
- Android Support Library Version: v4 28.0.0.1
- Nuget Packages:

Id                                  Versions                                 ProjectName                                                                                                                    
--                                  --------                                 -----------                                                                                                                    
Newtonsoft.Json                     {12.0.2}                                 GroceryList                                                                                                                    
Plugin.Permissions                  {4.0.4-beta}                             GroceryList                                                                                                                    
System.Security.Cryptography.Cng    {4.6.0-preview5.19224.8}                 GroceryList                                                                                                                    
Toasts.Forms.Plugin                 {3.3.2}                                  GroceryList                                                                                                                    
DLToolkit.Forms.Controls.FlowLis... {2.0.11}                                 GroceryList                                                                                                                    
Microsoft.Azure.Mobile.Client.SQ... {4.1.2-prerelease.481290}                GroceryList                                                                                                                    
Microsoft.Azure.Mobile.Client       {4.1.2-prerelease.481290}                GroceryList                                                                                                                    
Xam.Plugin.Media                    {4.2.0-beta}                             GroceryList                                                                                                                    
Xamarin.Essentials                  {1.1.0}                                  GroceryList                                                                                                                    
NETStandard.Library                 {2.0.3}                                  GroceryList                                                                                                                    
Xamarin.Forms                       {4.0.0.425677}                           GroceryList                                                                                                                    
DLToolkit.Forms.Controls.FlowLis... {2.0.11}                                 GroceryList.UWP                                                                                                                
Microsoft.Azure.Mobile.Client       {4.1.2-prerelease.481290}                GroceryList.UWP                                                                                                                
Microsoft.Azure.Mobile.Client.SQ... {4.1.2-prerelease.481290}                GroceryList.UWP                                                                                                                
Microsoft.NETCore.UniversalWindo... {6.2.8}                                  GroceryList.UWP                                                                                                                
NETStandard.Library                 {2.0.3}                                  GroceryList.UWP                                                                                                                
Newtonsoft.Json                     {12.0.2}                                 GroceryList.UWP                                                                                                                
System.Security.Cryptography.Cng    {4.6.0-preview5.19224.8}                 GroceryList.UWP                                                                                                                
Toasts.Forms.Plugin                 {3.3.2}                                  GroceryList.UWP                                                                                                                
Xamarin.Essentials                  {1.1.0}                                  GroceryList.UWP                                                                                                                
Xamarin.Forms                       {4.0.0.425677}                           GroceryList.UWP                                                                                                                
DLToolkit.Forms.Controls.FlowLis... {2.0.11}                                 GroceryList.iOS                                                                                                                
Microsoft.Azure.Mobile.Client       {4.1.2-prerelease.481290}                GroceryList.iOS                                                                                                                
Microsoft.Azure.Mobile.Client.SQ... {4.1.2-prerelease.481290}                GroceryList.iOS                                                                                                                
NETStandard.Library                 {2.0.3}                                  GroceryList.iOS                                                                                                                
Newtonsoft.Json                     {12.0.2}                                 GroceryList.iOS                                                                                                                
Plugin.Permissions                  {4.0.4-beta}                             GroceryList.iOS                                                                                                                
System.Security.Cryptography.Cng    {4.6.0-preview5.19224.8}                 GroceryList.iOS                                                                                                                
Toasts.Forms.Plugin                 {3.3.2}                                  GroceryList.iOS                                                                                                                
Xam.Plugin.Media                    {4.2.0-beta}                             GroceryList.iOS                                                                                                                
Xamarin.Essentials                  {1.1.0}                                  GroceryList.iOS                                                                                                                
Xamarin.Forms                       {4.0.0.425677}                           GroceryList.iOS                                                                                                                
DLToolkit.Forms.Controls.FlowLis... {2.0.11}                                 GroceryList.Android                                                                                                            
Microsoft.Azure.Mobile.Client       {4.1.2-prerelease.481290}                GroceryList.Android                                                                                                            
Microsoft.Azure.Mobile.Client.SQ... {4.1.2-prerelease.481290}                GroceryList.Android                                                                                                            
NETStandard.Library                 {2.0.3}                                  GroceryList.Android                                                                                                            
Newtonsoft.Json                     {12.0.2}                                 GroceryList.Android                                                                                                            
Plugin.CurrentActivity              {2.1.0.4}                                GroceryList.Android                                                                                                            
Plugin.Permissions                  {4.0.4-beta}                             GroceryList.Android                                                                                                            
Toasts.Forms.Plugin                 {3.3.2}                                  GroceryList.Android                                                                                                            
Xam.Plugin.Media                    {4.2.0-beta}                             GroceryList.Android                                                                                                            
Xamarin.Android.Support.Compat      {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Android.Support.CustomTabs  {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Essentials                  {1.1.0}                                  GroceryList.Android                                                                                                            
Xamarin.Forms                       {4.0.0.425677}                           GroceryList.Android                                                                                                            
Xamarin.Android.Support.Design      {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Android.Support.v7.AppCo... {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Android.Support.v4          {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Android.Support.v7.CardView {28.0.0.1}                               GroceryList.Android                                                                                                            
Xamarin.Android.Support.v7.Media... {28.0.0.1}                               GroceryList.Android   
[Subscriptions.zip](https://github.com/xamarin/Xamarin.Forms/files/3208488/Subscriptions.zip)

- Affected Devices: Samsung S9+

### Reproduction Link

Is a private project can add someone to it to clone the repo if needed

**Comment by norton287** [comment]
Just borrowed a phone, a Samsung SM-J727A on API 27 running Oreo 8.1 and the crash does not occur on selection change and color being applied.

**Comment by norton287** [comment]
Just checking further, I installed the latest Visual Studio Mac on my hackintosh with the following setup:

=== Visual Studio Community 2019 for Mac ===

Version 8.0.7 (build 3)
Installation UUID: f666c8dd-e30a-439e-817b-e51fea14463c
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK Versions:
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/jnorton/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.3
SDK Build Tools Version: 29.0.0 rc3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jnorton/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-16 16:08:28 UTC

=== Xamarin Designer ===

Version: 4.17.4.418
Hash: 3d086e814
Branch: remotes/origin/d16-0
Build date: 2019-04-01 09:20:10 UTC

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Community)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800070003
Git revision: 249c1092cf2a8264e6f0d1cbacd5f23b9a3b6dcc
Build date: 2019-05-20 17:07:22+00
Build branch: release-8.0
Xamarin extensions: e2fe31d63a4522ed7c7c099980656d468e7465ba

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

And I can build and install it to my Samsung S9+ and it works perfect, no crash at all.  It is definitely something on the windows side of xamarin.

**Comment by samhouts** [comment]
@norton287  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by norton287** [comment]
Here is a link to the repo with the test apps @samhouts.

[https://github.com/norton287/ColorPickerTest](https://github.com/norton287/ColorPickerTest)

**Comment by rmarinho** [comment]
Hi @norton287 i was trying your sample, and i can't get it work in it's state on 3.6. When i click the picker it crashes. Is this code working ?

thanks

**Comment by norton287** [comment]
It is working when compiled through Visual Studio Mac and it was fine prior to the last release of XF

**Comment by norton287** [comment]
@rmarinho Get from repo, I fixed an error in the property for Colors and it is working

**Comment by norton287** [comment]
@rmarinho It is broken on API 28 with Samsung S9+ compiled with Visual Studio 2019 Enterprise on Windows 10.  But if it is compiled with Visual Studio Mac and installed to S9+ it works as expected.

**Comment by rmarinho** [comment]
Other device with API28 on Windows 10 works ?

**Comment by norton287** [comment]
@rmarinho Not sure only other physical device I have is on Oreo 8.1 API 27

**Comment by norton287** [comment]
@rmarinho It works on UWP and iOS and on my Oreo 8.1 API 27 device

**Comment by norton287** [comment]
@rmarinho Updated to Visual Studio Enterprise 2019 Preview 2 16.2.0 for Windows and it is able to compile and the app runs as expected on my S9+.

Tried from Visual Studio Enterprise 16.1.3 for Windows again and the app crashes on picker backgroundcolor set still on my S9+.

What changes went into Preview 2 16.2.0 in regards to xamarin?

**Comment by samhouts** [comment]
It sounds like this must have been a bug in Xamarin.Android, then. @brendanzagaeski Does this sound familiar?

**Comment by norton287** [comment]
I get the same crash output as this reported here:  [https://developercommunity.visualstudio.com/content/problem/580820/xamarin-problem-following-update-to-vs2019-161.html](https://developercommunity.visualstudio.com/content/problem/580820/xamarin-problem-following-update-to-vs2019-161.html)

It has been fixed in todays update I believe have not tested it yet.

**Comment by brendanzagaeski** [comment]
Thanks for the report and the test case! I can confirm that the project from this issue does indeed have the same native backtrace as <https://developercommunity.visualstudio.com/content/problem/580820/xamarin-problem-following-update-to-vs2019-161.html> and that the project no longer crashes in Visual Studio 2019 version 16.1.4 and higher (with Xamarin.Android SDK version 9.3.0.23 and higher), so I will close this Xamarin.Forms issue as well.

For reference, here's the top of the native backtrace with symbols that I got from the https://github.com/norton287/ColorPickerTest test case:

```
  * frame #0: 0x0000007126cf5da8 libart.so`art_sigsegv_fault
    frame #1: 0x0000007126cf62b4 libart.so`art::FaultManager::HandleFault(int, siginfo*, void*) + 356
    frame #2: 0x00000058b5382b5c app_process64`___lldb_unnamed_symbol20$$app_process64 + 572
    frame #3: 0x00000071acbdd870 [vdso]
    frame #4: 0x00000071100d6658 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x0000000000000000) at mini-runtime.h:390
    frame #5: 0x00000071100d6650 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #6: 0x00000071100d6658 libmonosgen-2.0.d.so`mono_handle_exception_internal [inlined] jinfo_get_method(ji=0x000000710a77b970) at mini-runtime.h:390
    frame #7: 0x00000071100d6650 libmonosgen-2.0.d.so`mono_handle_exception_internal(ctx=<unavailable>, obj=<unavailable>, resume=0, out_ji=<unavailable>) at mini-exceptions.c:2701
    frame #8: 0x00000071100d62d0 libmonosgen-2.0.d.so`mono_handle_exception(ctx=<unavailable>, obj=<unavailable>) at mini-exceptions.c:2988
    frame #9: 0x000000711010e034 libmonosgen-2.0.d.so`mono_arm_throw_exception(arg=<unavailable>, pc=<unavailable>, int_regs=0x0000007fcd27fee0, fp_regs=0x0000007fcd27ffe0, corlib=<unavailable>, rethrow=0) at exceptions-arm64.c:410
```
