### ISSUE TITLE
[Bug] MenuItem cannot be added to Shell

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#6273]
### Description

The documentation says that MenuItem can be added to Shell. However, doing so produces an XLS0503 error, "A value of type 'MenuItem' cannot be added to a collection or dictionary of type 'IList'.'

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: None
- IDE: 16.1.0

Also reported with the documentation: https://github.com/MicrosoftDocs/xamarin-docs/issues/1711

**Comment by PureWeen** [comment]
@BioTurboNick  this is just an intellisense error that's being worked on

https://github.com/xamarin/Xamarin.Forms/issues/3864

It builds and runs without any issues
