### ISSUE TITLE
Defined Bindable property(say ListView's Selecteditem's)value is not reflected to PCL element when changed programmatically in OnNavigatingTo method

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#6275]
### Description
SelectedItem value is not reflected in UI when changed in OnNavigatingTo method. 

Can you please confirm us whether its is a issue or behavior. If behavior, then please provide detail information about its behavior and why it occurs.

### Steps to Reproduce

1.Run the sample.
2. Check in OnNavigatingTo method, SelctedItem value is defined.
3. But in UI selection background color is not appeared for the programmatically SelectedItem

### Expected Behavior
BackgroundColor should appear for the Programmatically SelectedItem.

### Actual Behavior
BackgroundColor does not appear for the Programmatically SelectedItem.

### Basic Information

- Version with issue: 3.6
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

http://www.syncfusion.com/downloads/support/directtrac/general/ze/ListViewPrism-219641795

Regards,
Gnana Priya N(Syncfusion Team)

**Comment by DineshBabuYadav** [comment]
@samhouts , Can you please update on this?

**Comment by jfversluis** [comment]
Is this on a specific platform or API level for Android? Running your sample seems to work just fine. Here is what I'm seeing: https://1drv.ms/v/s!Anrk6U9nRknzgvh_ZWtBoLBzeqGAbg?e=ODvKMC

**Comment by samhouts** [comment]
@GnanaPriyaNamasivayam  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
