### ISSUE TITLE
[Bug] Crash on page reorientation if it contains Buttons with ImageSource (Android)

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#6276]
### Description
When rotating the Android device, certain layouts trigger what appears to be an infinite loop of resizing events, resulting in the app crashing.
If you change certain layout properties, the app doesn't crash anymore.

### Steps to Reproduce

1. Start the app and get to a page with an affected layout
2. Rotate the device

### Expected Behavior
The app resizes itself to fit the new device orientation.

### Actual Behavior
The app is killed by the OS.

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version:
- IDE: VS 15.9.11
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages:
- Affected Devices: n/a

### Reproduction Link

The issue is simply reproduced by viewing a page with content such as:
```
<ContentPage x:Class="ButtonImageCrash.MainPage"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ButtonImageCrash">

    <Button Text="1" VerticalOptions="Center" Visual="Material">
        <Button.ImageSource>
            <FontImageSource FontFamily="Roboto"
                             Glyph="A"
                             Size="30"
                             Color="White" />
        </Button.ImageSource>
    </Button>
</ContentPage>
```

Remarks:
- If you change the button's VerticalOptions to Fill instead of Center, the app will not crash on rotation.
- If you remove the button ImageSource, the app will not crash on rotation, regardless of the other layout options.
- this could be related to https://github.com/xamarin/Xamarin.Forms/issues/6260 ?

**Comment by MitchBomcanhao** [comment]
As an added note, if you use the legacy renderer (removing visual=material and adding global::Xamarin.Forms.Forms.SetFlags("UseLegacyRenderers"); to your activity), the app will not crash on rotate.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/6260
