### ISSUE TITLE
[Bug][Android] Impossible to focus Picker View more than once

### ISSUE THREAD

**Issue by Asnanon** [xamarin/Xamarin.Forms#6278]
### Description

Trying to focus a Picker View with Focus() after it loses focus is not possible, without focusing another Picker Type View (Picker, DatePicker, TimePicker) first.
This Problem is only reproducable on Android, iOS works as expected.

### Steps to Reproduce

1. Call Focus() from codebehind.
2. Los focus in the app.
3. Call Focus() from codebehind.

### Expected Behavior

Regaining focus of the view.

### Actual Behavior

Focus not being regained.

### Basic Information

- Version with issue:
- IDE: Visual Studio 2017 15.9.12
- Platform Target Frameworks: 
  - Android: 8.1

### Reproduction Link
[Reproduction.zip](https://github.com/xamarin/Xamarin.Forms/files/3211254/Reproduction.zip)

**Comment by larsduewel** [comment]
Is there a workaround for that?

**Comment by Piusn** [comment]
This issue has been fixed in the latest Xamarin forms. I have attached a working sample here

**Comment by hartez** [comment]
@Piusn Thank you - looks like you are correct, it does work.
