### ISSUE TITLE
Unable to bind a Complex property value to Label TextProperty

### ISSUE THREAD

**Issue by DeepikaBalaSubramaniyan** [xamarin/Xamarin.Forms#6281]
### Description
I have one model property which is not direct data type,  This model property type was one class which is named as Complex property, I tried to bind the text from this ComplexProperty to Label Text property, But label was loaded with empty text, 

ComplexProperty:
public ComplexOrderInfo ComplexOrderInfo
        {
            get
            {
                return _complexOrderInfo;
            }
            set
            {
                this._complexOrderInfo = value;
                RaisePropertyChanged("ComplexOrderInfo");
            }
        }  
I have set the value for direct property and complex proeprty as like blow
**this.OrderID = 111111;
this.ComplexOrderInfo = new ComplexOrderInfo() { ItemSize = 1, Count = 2 };**
Here ComplexOrderInfo is another class which has  two inner properties which is direct primitive data type.

In Xaml page I have two label, and I have set this direct and complexProperty value for these two label like below,
![image](https://user-images.githubusercontent.com/42173947/58255542-d5f3e300-7d8a-11e9-9106-b418b3c6b714.png)
First label loaded the text with OrderID value, But second label was not loaded with ComplexOrderInfo text,

Please Note , I know I can bind the text from this complex properties Inner property like below:
![image](https://user-images.githubusercontent.com/42173947/58255605-00de3700-7d8b-11e9-8152-a774549f2e63.png)

But I wants to assign the text either from this ToString override() which is from ComplexOrderInfo class, if ToString() is not given just I want sample name has to be assign the label text, But not worked as expected.

>  public override string ToString()
        {
            if (ItemSize > 0 && Count > 0)
                return "ItemSize is " + ItemSize.ToString() + " Count is " + Count.ToString();
> }

- In the above explained same scenario, WPF (Windows presentation foundation)platform, I can bind the text from CompleProperty to TextBlock view textproperty, there label has loaded with the text from ToString() override, when ToString() was not overrided label has a text of sampleName.PropertyName,

- Same was expected in Xamarin. 

- So kindly let us know Is there any way to bind a text from ComplexProperty, Or If I miss anything to add to bind the text from ComplexProperty which will be more helpful to me.

For your reference have attached the Xamarin UWP output View and WPF output View.
Xamarin 
![image](https://user-images.githubusercontent.com/42173947/58257649-ec9c3900-7d8e-11e9-831d-72039ea783a8.png)

Xamarin sample http://www.syncfusion.com/downloads/support/directtrac/general/ze/LabelFrameWork_(2)-1626753561

WPF:
![image](https://user-images.githubusercontent.com/42173947/58257165-02f5c500-7d8e-11e9-91f5-a389a97fd092.png)

WPF sample:  http://www.syncfusion.com/downloads/support/directtrac/general/ze/WPF-175566568

### Steps to Reproduce

1.  Run the attached sample
2.  See second label text was loaded with empty text which is binded with CompleProperty

### Expected Behavior
Label should loaded with CompleProperty value.

### Actual Behavior
Label has not loaded with CompleProperty value, Which was loaded as empty text.

### Basic Information

- Version with issue: 4.0 latest
- Last known good version:NA
- IDE:
- Platform Target Frameworks: Android, IOS, UWP

- Nuget Packages: 4.0
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/42173947/58257649-ec9c3900-7d8e-11e9-831d-72039ea783a8.png)

### Reproduction sample Link
Xamarin http://www.syncfusion.com/downloads/support/directtrac/general/ze/LabelFrameWork_(2)-1626753561

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @XamarinQA 

We have been waiting for your update whether are you confirmed this was an issue or any work around will be there to bind a text of Label from complex property ?

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @pauldipietro 

Any update on this issue ?

**Comment by samhouts** [comment]
@StephaneDelcroix Do you have a workaround for this? Thanks!

**Comment by jfversluis** [comment]
My hunch was the problem is not in showing the complex object, but more that the size of the Label is for some reason not calculated correctly. If you change the XAML to this: `<Label x:Name="label2" BackgroundColor="SkyBlue" Text="{Binding ComplexOrderInfo, StringFormat='Value: {0}'}"></Label>` you will see it show up. 

So either put in something like this, or find a way to trigger a layout cycle at the right point. Still I would like to get @StephaneDelcroix's opinion on whether this is an actual bug we need to look into.

**Comment by vimal1994** [comment]
Hi @samhouts , @StephaneDelcroix ,

We are facing more such use cases from our customers and we are at a stand still with this issue. So could you please try and fix this **ASAP**. Thanks !

**Comment by StephaneDelcroix** [comment]
BindableObject does not invokes ToString(), but invokes an implicit cast to string if one is present. This is why @jfversluis workaround works, and it has nothing to do with layout invalidation.

**Comment by DeepikaBalaSubramaniyan** [comment]
Hi @samhouts 

Can we conclude that reported issue has fixed, If yes please let us know at which upcoming nuget package fix will get reflect ? Or you are stating that it was a behavior ?

**Comment by samhouts** [comment]
@DeepikaBalaSubramaniyan This has been fixed and will be released in 4.4. This was a behavior change, so we are not comfortable backporting it to earlier versions. Thanks!

**Comment by DeepikaBalaSubramaniyan** [comment]
@samhouts 
Happy to hear this. Thanks for your response.
