### ISSUE TITLE
Text on button loses center alignment on changing of IsEnabled after updating XF to 4.0.0.425677 

### ISSUE THREAD

**Issue by rkshnair** [xamarin/Xamarin.Forms#6282]
I am changing the style of a button using Visual States along with its IsEnabled Property as given below. It was woking fine without any issue till I update the latest Xamarin Forms package.

I am facing this issue only in **Android** 

```
<Button Grid.Row="0"
            Grid.Column="1"
             Style="{StaticResource StandardButtonStyle}"
             IsEnabled="{Binding ItemCardVisible}"
            Text="Issue Button">
            <VisualStateManager.VisualStateGroups>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal">
                        <VisualState.Setters>
                            <Setter Property="Style"
                                Value="{StaticResource StandardButtonStyle}" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Disabled">
                        <VisualState.Setters>
                            <Setter Property="Style"
                                Value="{StaticResource DisabledButtonStyle}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateManager.VisualStateGroups>
        </Button>`
```

When I start loading the page the button is in **Disabled state**.  Once I get the API response I will make the button Enabled. This time, the button text alignment automatically changes to left align. 

Style I am using

```
`<Application.Resources>
        <x:Int32 x:Key="CornerRadius">3</x:Int32>
        <Color x:Key="WhiteColor">#FFFFFF</Color>
        <Color x:Key="PrimaryDarkColor">#444444</Color>
        <Color x:Key="SecondaryTextColor">#666666</Color>
        <Color x:Key="ContentBGColor">#e6e6e6</Color>
        <!--  Standard Button Style  -->
        <Style x:Key="StandardButtonStyle"
            TargetType="Button">
            <Setter Property="CornerRadius"
                Value="{StaticResource CornerRadius}" />
            <Setter Property="TextColor"
                Value="{StaticResource WhiteColor}" />
            <Setter Property="BackgroundColor"
                Value="{StaticResource PrimaryDarkColor}" />
            <Setter Property="BorderColor"
                Value="{StaticResource PrimaryDarkColor}" />
            <Setter Property="FontSize"
                Value="Medium" />
        </Style>
        <!--  Button disabled style  -->
        <Style x:Key="DisabledButtonStyle"
            TargetType="Button">
            <Setter Property="TextColor"
                Value="{StaticResource SecondaryTextColor}" />
            <Setter Property="BackgroundColor"
                Value="{StaticResource ContentBGColor}" />
            <Setter Property="BorderWidth"
                Value="1" />
            <Setter Property="BorderColor"
                Value="{StaticResource SecondaryTextColor}" />
            <Setter Property="FontSize"
                Value="Medium" />
        </Style>
    </Application.Resources>
```

Also I have noticed that creating a default renderer fixes the issue.

```
[assembly: ExportRenderer(typeof(Button), typeof(CustomButtonRenderer))]
namespace MyApp.Droid.Renderers
{
    public class CustomButtonRenderer : ButtonRenderer
    {
        #region .ctor
        public CustomButtonRenderer(Context context) : base(context)
        {

        }
        #endregion
    }

```
I am using set Flag as 

` Forms.SetFlags("UseLegacyRenderers");`

**Comment by PureWeen** [comment]
@rkshnair if you don't use `Forms.SetFlags("UseLegacyRenderers");`

Do you still see the same issue?

**Comment by rkshnair** [comment]
If i remove this I am getting some issues in Entry control related to Focus and sometime it even freezes my app. If my understanding is correct XF 4 on wards they have added fast renderers by default, which in turn causing some issues to my app. Not sure its a bug or not.

**Comment by PureWeen** [comment]
[debug(1).zip](https://github.com/xamarin/Xamarin.Forms/files/3215452/debug.1.zip)
@rkshnair  can you test with the attached nuget? If you're still seeing focus/crash issues with this attached nuget can you please log an issue so we can make sure the fast renderers are fixed and working for you

**Comment by rkshnair** [comment]
The issue is still there with the given nuget package as well.

**Comment by PureWeen** [comment]
@rkshnair which issue?

The one referred to by the ticket? or

> If i remove this I am getting some issues in Entry control related to Focus and sometime it even freezes my app.

**Comment by rkshnair** [comment]
Yes the same issue referred in the ticket.

**Comment by PureWeen** [comment]
@rkshnair With the attached Nuget

>  if you don't use Forms.SetFlags("UseLegacyRenderers");

Does that fix the issue?

**Comment by PureWeen** [comment]
@paymicro do you think this PR is related?

https://github.com/xamarin/Xamarin.Forms/pull/6115/files

**Comment by rkshnair** [comment]
Not sure..

**Comment by paymicro** [comment]
@rkshnair Could you check the reproduction this issue with this test package?
https://github.com/paymicro/Xamarin.Forms/blob/paymicro-patch-1/.nuspec/Xamarin.Forms.9.9.5.nupkg

**Comment by rkshnair** [comment]
@paymicro The issue is still there.  With the latest package you provided.
