### ISSUE TITLE
[Bug] ObjectDisposedException in Android WebView.EvaluateJavascriptAsync

### ISSUE THREAD

**Issue by kwaclaw** [xamarin/Xamarin.Forms#6286]
### Description
WebView control exists on a ContentPage. EvaluateJavascriptAsync is called in Navigated event.
works fine first time. But Navigating away and back to the ContentPage triggers  *multiple* ObjectDisposedExceptions (for the Android webview) in EvaluateJavascriptAsync, even though the Navigated event happens only once.  The number of triggered exceptions depends on the number of navigations to the ContentPage.

### Steps to Reproduce

Use Custom renderer, navigate to and from page with web view. Call EvaluateJavascriptAsync in Navigated event.

### Possible reason and fix:

Looking at the source I can see that for Android, WebViewRenderer.Dispose() does not clear the ElementController.EvaluateJavaScriptRequested event handler. I can see that that is an omission because the OnElementChanged handler does indeed clear the EvaluateJavaScriptRequested  event for the old element.

*Fix*: Using a custom renderer (for Android) , clear the ElementController.EvaluateJavaScriptRequested event by overriding the custom renderer's Dispose() method. It is necessary to use reflection to do that.

### Basic Information

- Version with issue: 3.6
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
   - Android: 28

**Comment by kwaclaw** [comment]
Adding example of fix for benefit of others:
```
    public class CustomRenderer: WebViewRenderer {
        public CustomRenderer(Context context) : base(context) {
           //
        }

        // leaving out implementation details

        protected override void Dispose(bool disposing) {
            // HACK to work around an issue in WebViewRenderer where Dispose does not clear an event handler
            if (disposing && Element != null) {
                // we happen to know the name of the private method used for the handler - this will break if the name changes
                var handler = (EvaluateJavaScriptDelegate)Delegate.CreateDelegate(typeof(EvaluateJavaScriptDelegate), this, "OnEvaluateJavaScriptRequested");
                Element.EvaluateJavaScriptRequested -= handler;
            }
            base.Dispose(disposing);
        }
    }
```

**Comment by samhouts** [comment]
@kwaclaw Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by kwaclaw** [comment]
It may take a while before I get to it. in the meantime my explanation of
the fix should be a good indicator of what the issue is.

**Comment by samhouts** [comment]
@kwaclaw I was unable to reproduce the crash. However, I've opened a PR to add the unhook as you suggested. Thanks!
