### ISSUE TITLE
[Enhancement] Make sure all Shell renderers use the register service

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#6289]
## Summary

On iOS ShellFlyoutRenderer can't be register by the user to be replaced. 
 
## Intended Use Case
It's easy for users to write there own renderes for the several parts that compose the Shell if they need too.

**Comment by PureWeen** [comment]
One thing to consider here is that having a single ShellRenderer helps a lot for discoverability of what you can override. Plus there might be different overrides per platform.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
