### ISSUE TITLE
[Spec] Shell Flyout Content Template

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#6293]
# Flyout Content Template

Allow developers to provide a template for the entire flyout.

* Should be able to describe the whole layout
* Developer responsible for header and footer. Any provided templates would not be applied.

```
<Shell.FlyoutTemplate>
    <DataTemplate>
        <Grid>
            <ContentView>
                <Label Text="My Header"/>
            </ContentView>
            
            <ListView ItemsSource="{Binding Items}">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <Grid>
                            <Image Source="{Binding Icon}"/>
                            <Label Text="{Binding Title}"/>
                        </Grid>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>

            <ContentView>
                <Label Text="My Footer"/>
            </ContentView>
        </Grid>
    </DataTemplate>
</Shell.FlyoutTemplate>
```

# API

Shell.FlyoutTemplate

# Difficulty : Awesome

**Comment by PureWeen** [comment]
@davidortinau I feel like for this scenario we wouldn't use `HeaderContentPresenter` and `FooterContentPresenter`

In this scenario we would just allow users to define everything with one template.

If they want to supply there own template for the items then probably just create a 
`<Shell.FlyoutItemsTemplate>`

It seems excessive to make them specify those presenters

**Comment by davidortinau** [comment]
Yeah, I suppose that's true. Probably not worth trying to integrated in the header/footer templates if providing a template for the whole flyout.

**Comment by domagojmedo** [comment]
Is there a plan to have this in any of the next versions?

**Comment by lrfahmi** [comment]
Can every item have an effect (such as a ripple effect)?
