### ISSUE TITLE
[Bug] Xaminals flickers weirdly on some devices

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6294]
### Description
https://twitter.com/sinkingstar/status/1131588731855618049?s=21

### Steps to Reproduce

1.  clone Xamarin samples
2. run xaminals
3. click on anything in the list

### Expected Behavior

smooth transition
### Actual Behavior

annoying black flicker

### Basic Information

- Affected Devices: Samsung s9 and Samsung note
I haven't observed this behavior on simulators at all

**Comment by syedhoque89** [comment]
Thanks for raising it!!!

**Comment by angelru** [comment]
Any updates?

**Comment by angelru** [comment]
Any updates? The same issue in Android 9: Xiaomi mi6

**Comment by angelru** [comment]
@samhouts the same problem remains with version 4.3

**Comment by ragnar474** [comment]
Same problem here on Samsung S9+, althought only with Shell.Current.Navigation.PopAsync(true).

Problem not appearing in Emulator (with Google Pixel Android 7.0).

**Comment by angelru** [comment]
Any updates?

**Comment by samhouts** [comment]
closed by  #10158
