### ISSUE TITLE
[Bug] Flyout Header is taking too much space than its content on iOS

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6295]
### Description
I added some content to the Header of Flyout. It looks good on Android. But on iOS it it taking lots of more space than required.

### Steps to Reproduce
Run the repro project and open the flyout. 

### Expected Behavior
The Header size should be adjusted according to the size of the content it have. 

### Basic Information

- Version with issue: Xamarin.Forms-4
- IDE:VSMac 2019
- Affected Devices:iOS

### Screenshots
![iOS](https://user-images.githubusercontent.com/9531864/58303290-12682300-7e0d-11e9-9749-9d9adebd653b.png)

![Android](https://user-images.githubusercontent.com/9531864/58303296-1bf18b00-7e0d-11e9-9da7-1a7fc1a9d213.png)

### Reproduction Link

[HeaderSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3215134/HeaderSample.zip)

**Comment by HobDev** [comment]
Interestingly in single StackLayout with name and phone number the issue does not arise. But the top StackLayout is required for showing image.

**Comment by HobDev** [comment]
In one of my projects I am using Grid for HeaderTemplate. If Grid have Rows only the Header size is OK. But if I declare Columns too the size of the Header increased a lot on iOS.

**Comment by PureWeen** [comment]
This is fixed on the latest version of forms

If that seems inaccurate let me know and we can reopen
