### ISSUE TITLE
[Bug] toolbaritem icon not showing in Android with 4.0

### ISSUE THREAD

**Issue by rasel-tr** [xamarin/Xamarin.Forms#6296]
### Description

I upgraded my forms project to forms 4.0 and my toolbar items turned to text in android platform.  I changed the Icon property to IconImageSource and tried to load the images from embedded resource and from file but doesn't work. iOS is fine with embedded resource. Getting this exception:

`Error: Unhandled Exception System.Exception: TaskSchedulerOnUnobservedTaskException ---> System.ArgumentNullException: Value cannot be null. Parameter name: renderer at Xamarin.Forms.Platform.Android.ResourceManager.ApplyDrawableAsync (Xamarin.Forms.Platform.Android.IVisualElementRenderer renderer, Xamarin.Forms.BindableObject bindable, Xamarin.Forms.BindableProperty imageSourceProperty, Android.Content.Context context, System.Action`1[T] onSet, System.Action`1[T] onLoading, System.Threading.CancellationToken cancellationToken) [0x0003b] in D:\a\1\s\Xamarin.Forms.Platform.Android\ResourceManager.cs:136 at Xamarin.Forms.Platform.Android.ResourceManager.ApplyDrawableAsync (Android.Content.Context context, Xamarin.Forms.BindableObject bindable, Xamarin.Forms.BindableProperty imageSourceProperty, System.Action`1[T] onSet, System.Action`1[T] onLoading, System.Threading.CancellationToken cancellationToken) [0x0003a] in D:\a\1\s\Xamarin.Forms.Platform.Android\ResourceManager.cs:238 `

- Version with issue: 4.0.0.425677
- Last known good version: 3.6.0.293080
- IDE: Visual Studio for Windows v16.1.0
- Platform Target Frameworks: 
  - iOS:  12.10.0.153
  - Android: 9.3.0.22
- Android Support Library Version: 47.0.0

**Comment by PureWeen** [comment]
@rasel-tr can you attach a repro please? I did some basic tests with toolbar items and I wasn't able to reproduce that exception

**Comment by rasel-tr** [comment]
@PureWeen , thanks for the quick reply. I'm attaching a striped version of my solution
[app.zip](https://github.com/xamarin/Xamarin.Forms/files/3215904/app.zip)

**Comment by PureWeen** [comment]
[TekEkranMin.zip](https://github.com/xamarin/Xamarin.Forms/files/3218089/TekEkranMin.zip)

@rasel-tr your included sample needed a little bit of modification to get running. I've included it. Once I had it up and running though it started up fine

I converted it over to package reference

Can you download this attachment and let me know how I can run it to see the crash you are seeing?

**Comment by rasel-tr** [comment]
@PureWeen , thank you for this extra conversion effort. When I run this solution on my phone with debug configuration, the app opens on the phone without crashing but showing toolbaritems' texts instead of the icons. This is my problem. See the below screenshot:
![toolbaritem](https://user-images.githubusercontent.com/6556734/58350365-58090800-7e6e-11e9-9f5c-7d17dfb4fa0f.jpg)

**Comment by PureWeen** [comment]
@rasel-tr 

- I'm not super clear what you're saying worked in 3.6 but not 4.0. I tested reverting your solution to 3.6 but at that point ToolBarItem only takes a fileimagesource not embedded. So were you using a drawable before and now you're using embedded?
- Also you aren't using an appcompat theme which isn't using any of our appcompat renderes. The new ImageSource changes aren't going to work if you are using a non appcompat theme.

i would recommend changing your app over to app compat (if possible)

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat-material-design

Which should resolve most of your issues

I'm going to close this for now but I'll reopen based on your responses

**Comment by melimion** [comment]
https://github.com/PureWeen, I think issue same as here:

https://github.com/xamarin/Xamarin.Forms/issues/6258

**Comment by pauldiston** [comment]
I have run into this problem as well where my ToolbarItem images are not displaying, and only showing text. I am not entirely sure of the resolution to this problem.

Please can someone share the solution to this?

**Comment by rasel-tr** [comment]
@pauldiston changing my MainActivity inherited from FormsAppCompatActivity solved my problem

**Comment by pauldiston** [comment]
@rasel-tr I have switched my MainActivity to inherit from FormsAppCompatActivity rather than FormsApplicationActivity, however upon running my app now, an exception is raised "You need to use a Theme.AppCompat theme (or descendant) with this activity.".

I presume I will need to follow the steps in the following to get this working :-
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat-material-design

**Comment by PureWeen** [comment]
@paulbatum correct!!

You need to set your applications theme to use something that inherits from appcompat

**Comment by pauldiston** [comment]
@PureWeen Thank you very much for reply. I have now got past this issue however have now run into another issue regarding the OnOptionsItemSelected not firing.
As a side note, would you be able to tell me the benefits of moving from FormsApplicationActivity to FormsAppCompatActivity as this seems to have raised a number of issues, I am unsure of the advantages to switching.

**Comment by malgre** [comment]
I also have this problem, which only appeared with Xamarin.Forms 4.  It's true that the problem disappears if you change to appcompat, but I wish to continue using the Holo.Light theme for now and don't believe I should need to change the behaviour of my app to work around a breaking change in Forms.
