### ISSUE TITLE
[Bug] Listview with custom viewcell renders wrongly after XF4.0 update

### ISSUE THREAD

**Issue by simon10says** [xamarin/Xamarin.Forms#6297]
### Description
I have a listview set to `RecycleElement`  with a `Grid` with 2 columns as the `ItemTemplate`. The 2nd column's width is set as `Auto`.  With Xamarin.Forms 3.6.0.344457, the 2nd column  (in yellow) renders correctly as shown below:
![36](https://user-images.githubusercontent.com/32186165/58310851-355cfc00-7e3a-11e9-997b-67aa8219b05d.jpg)

But, after update to 4.0.0.425677, the 2nd column is all messed up as shown below:
![4](https://user-images.githubusercontent.com/32186165/58310948-735a2000-7e3a-11e9-8601-f6ab3dd45c3e.jpg)

### Steps to Reproduce

1.  Open the attached repo app
2.  Launch the android app
3.  Scroll the listview all the way down

### Expected Behavior
The 2nd column in yellow show be rendered correctly

### Actual Behavior
The 2nd column in yellow is truncated

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version:3.6.0.344457
- IDE: Visual Studio 2019 version 16.1.0
- Android: 9.0

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3215663/App1.zip)

**Comment by MitchBomcanhao** [comment]
I've similar issues on my project. Reorienting the device will calculate the layouts appropriately, but scrolling the list will start showing incorrect alignments and content being trimmed even though there is plenty of space for it.

**Comment by jalbertSyncroTech** [comment]
Just reporting that I'm seeing this as well on Android with X.F 4.0: in a scroll-able menu with text of varying lengths it seems to be truncating text for new items with longer text to whatever the width was of the text in the cell it's recycling.

**Comment by rkshnair** [comment]
XF 4.0 is not stable it seems. There are lot of issues with Android Fast renderers. I am facing issues with  ListView, EditText, ScrollView etc. 

iOS seems to be working fine. After the update my app started miss behaving completely.

**Comment by jalbertSyncroTech** [comment]
@rkshnair Just a note that I also tested with fast renders disabled using the "UseLegacyRenderers" flag, and the ListView scroll text truncation issue still happens.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers#backwards-compatibility

**Comment by PureWeen** [comment]
I doubt this one is related to the fast renderers

**Comment by PureWeen** [comment]
@paymicro do you think this PR is related?

https://github.com/xamarin/Xamarin.Forms/pull/6115/files

**Comment by paymicro** [comment]
@PureWeen this issue a bit related on PR #6115.

**Comment by jalbertSyncroTech** [comment]
Any updates on the status of this issue?  Since 4.0.0-sr1 was just released and I don't see this referenced in the release notes, can we expect this in a 4.0.0-sr2?

**Comment by cjpartin** [comment]
I have the same issue, when any recycling caching strategy is active and you scroll in a listview with enough elements that some may come off screen, any alignment they have is removed upon scrolling up.

**Comment by TomBruyneel** [comment]
Same problems occur in collectionviews. As soon as views are recycled the alignments are all out wack

**Comment by simon10says** [comment]
@samhouts , @paymicro , any update on this?

**Comment by samhouts** [comment]
We're getting all the tests passing, and then we'll merge the fix! Thanks for your patience.

**Comment by samhouts** [comment]
closed by #6390

**Comment by fernandovm** [comment]
Dear, I still have problems using `CachingStrategy="RecycleElement"` with Xamarin Forms version 4.2.0.848062:

![image](https://user-images.githubusercontent.com/441113/66498182-0c10d580-ea94-11e9-8093-de9be52cc0aa.png)

:((

**Comment by amr-moomen** [comment]
I have the same problem when scroll down and scroll up again labels randomly truncates with screen shots below
Xamarin Forms version 4.2.0.848062:
![scroll](https://user-images.githubusercontent.com/56504816/66714464-88b6f300-edb7-11e9-8b04-72df0421c701.png)
