### ISSUE TITLE
[Bug] widen pit of success for dispose pattern implementations and cleanup currently incorrect ones

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6305]
### Description

Dispose should follow the following execution path everywhere
https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#implementing-the-dispose-pattern-for-a-derived-class
```C#
	protected override void Dispose(bool disposing) => DisposeMe(this, () =>
		{
			if (Control != null)
			{
				Control.Checked -= OnNativeChecked;
				Control.Unchecked -= OnNativeChecked;
			}
		}, disposing, ref _isDisposed, base.Dispose);


		static void DisposeMe(IDisposable disposable, Action disposeAction, bool disposing, ref bool _isdisposed, Action<bool> baseDispose)
		{
			if (_isdisposed)
				return;

			_isdisposed = true;
			if (disposing)
				disposeAction();

			baseDispose(disposing);
		}
```

### Call Dispose(false) from finalizer on base class
https://docs.microsoft.com/en-us/dotnet/api/system.idisposable?view=netframework-4.8#examples

#### Helper Method
Create a reusable extension method that correlates to the pattern
```C#
static void DisposeMe(this IDisposable, Action disposeAction, disposing, ref _isdisposed)
```

*Reasons not to do it this way?*
I'm not sure the overhead of closures and lambda functions or if that's even something to consider. 

Also I wouldn't just apply this everywhere. We can just apply this to areas that are broken and then as the ball rolls forward just use the reusable method

#### Analyzer
Setup an analyzer that will check for dispose patterns so that we don't incur extra allocations by using a function

**Comment by hartez** [comment]
You're missing the `if(disposing){}` in your pattern example.

**Comment by hartez** [comment]
So with your extension method, what would a `Dispose(bool disposing)` override look like?

**Comment by PureWeen** [comment]
@hartez updated example

**Comment by hartez** [comment]
> For things that inherit from ViewRenderer we could also add a helpful base method

I'm wary of this option, because then we run into possible issues with the order in which implementors call `base.DisposeRenderer()`. I think I prefer confining all disposal code to one place.

**Comment by hartez** [comment]
> Reasons not to do it this way?

I think we'd be looking at a little bit of a performance hit, because it has to allocate a closure. And we'd be giving the GC more work to do. 

I suppose the question is whether it's worth the extra hit to prevent us from incorrectly implementing Dispose. I feel like we could probably do that with a combination of reviews and maybe a Roslyn analyzer.

**Comment by PureWeen** [comment]
I like the `Roslyn analyzer.` approach 
Seems like that should exist already :-) Edited the options and title a bit more

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/6467
