### ISSUE TITLE
[Bug] [Shell] [Android] Setting BackButtonBehavior IsEnabled to False causes an exception when loading page

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#6307]
### Description
Setting BackButtonBehavior IsEnabled to False causes an exception when loading page on Android
### Steps to Reproduce

1. Download the Xaminals test app or similar app using Shell
2. Add the following lines to one of the animal detail pages such as BearDetailPage.xaml
```
    <Shell.BackButtonBehavior >
        <BackButtonBehavior IsEnabled="False" />
    </Shell.BackButtonBehavior>
```
3. Run the app and attempt to navigate to the page

### Expected Behavior
The page should actually load and not throw an exception.
If this property is designed to mimic the behavior of 				`NavigationPage.SetHasBackButton(nextPage, false);` then the hamburger should replace the back arrow and tapping on the hamburger should open the flyout.

### Actual Behavior
Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object. occurred

### Basic Information

- Version with issue: 4.0.0
- Last known good version:
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android:  9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Pixel XL

**Comment by samhouts** [comment]
[Issue6307.zip](https://github.com/xamarin/Xamarin.Forms/files/3234961/Issue6307.zip)

Tap on an item in the list to try to navigate to the page. CRASH!

```
System.ArgumentNullException: Value cannot be null.
Parameter name: obj
```

**Comment by PureWeen** [comment]
No longer an issue on 4.2+
