### ISSUE TITLE
[Enhancement] Ability to access folders via simple enumeration

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#6314]
## Summary
I have time to time a requirment to write to the sd card and or downloads folder why can we not just simply have a folder enum like

## API Changes
At present I am using the following to copy db to a folder personal but the below options are not avaialbe to me 

    public async Task<Boolean> copydb()
    {
            DatabasePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "FuelStockApp9.db");

            if (!File.Exists(DatabasePath))

            {

                using (var assetStream = await Xamarin.Essentials.FileSystem.OpenAppPackageFileAsync("FuelStockApp9.db"))
                using (var fileStream = new FileStream(DatabasePath, FileMode.Create, FileAccess.Write))
                {
                    assetStream.CopyTo(fileStream);
                }
            }
             database = new SQLiteAsyncConnection(DatabasePath);
    }

e.g.
Public Enum Folders{
Downloads =1,
SDCard =2,
etc etc 

}

**Comment by adrianknight89** [comment]
Wondering if this should be part of the Essentials package. @jamesmontemagno

**Comment by jamesmontemagno** [comment]
That would be something part of Xamarin.Essentials. We already have App and Data directory:

https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?context=xamarin%2Fxamarin-forms&tabs=android

I don't think we would do more than that though as it gives you access to everything today. However, we are open to ideas and implementation details to be proposed over at http://github.com/xamarin/essentails

**Comment by davidbuckleyni** [comment]
Hi @jamesmontemagno  Love your shows by the way. The thing I find hard is getting my db from those folders for quick testing unless you new a way I can copy the db to the downloads folder using xamrian forms ?.

I am creating a cross-platform stock transfer and scanning app using xamrian forms for a major medical group in Belfast here.

I cant use azure cause of their budget on the orignal project so stuck with wcf and good old sqllite.

And its always nice to be able to pull off from the device or place the db on the sdcard for easy access.
