### ISSUE TITLE
ListView behave strange after updating XF to 4.0 in Android

### ISSUE THREAD

**Issue by soooraj** [xamarin/Xamarin.Forms#6315]
After updating XF package to 4.0.0.425677 my list view cells are not loading.

If there are 300 + items in the List View, It simply loads empty cell while scrolling. 

Also the  the latest version of the XF 4.0.0.425677 is not stable at all. Especially for Android. I am facing issue with the following controls. 

ListView - Not loading properly and the scrolling is not smooth. (Even some time crashes)
Entry - UI flashes and jumps when we focus the entry.
Button - Button Text / Image contents changes it orientation while we change the IsEnable property. 
Navigation Bar - Navigation Bar go empty if we are using Custom Navigation Bar.

@jamesmontemagno - Performance of Xamarin Forms in Android is pathetic with version (4.0.0.425677). I wondering why Microsoft is bundling this sought of buggy packages with major release. 

I tried both Fast & Legacy renderes but end up with same issues. 

I reverted my code back to 3.6.0.344457 . 

Please fix this issues and release some stable build. Otherwise we guys will be in trouble

**Comment by adrianknight89** [comment]
@soooraj I know for a fact that v4 was shipped while this regression was reported: #5838, which prevents me from upgrading my NuGet. As you indicate, there may be other issues with ListView on Android.

**Comment by samhouts** [comment]
@soooraj  Can you please attach a small project that demonstrates this issue? Also, it would be helpful if you could submit separate issues for each problem that you're experiencing. Thanks!

@adrianknight89 Ah, I failed to label that one properly, so it slipped under the radar. Thanks for bringing it back to my attention!

**Comment by PureWeen** [comment]
I'm guessing all lot of what you list will be fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/6274

You can test the Nuget here
https://github.com/xamarin/Xamarin.Forms/issues/6260#issuecomment-495490890

as far as the custom navigation bar

> Navigation Bar go empty if we are using Custom Navigation Bar.

Not sure on that one. If you have a repro of that it would be useful

**Comment by samhouts** [comment]
@soooraj Please test with the latest service release. Are you still experiencing this issue? Thanks!

**Comment by soooraj** [comment]
ListView issue is still there. If you populate the ListView with some 100 items and perform some scroll on it and remove one item from ListView. It will generate empty cells.

**Comment by samhouts** [comment]
@soooraj  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by berserk91** [comment]
We are having the same issue as well, and we are noticed a huge performance lost in 4.1 version (after 3.6).
If we add new item on the list, it will generate empty cells too. After we scrolling the elements are appears again. So maybe some kind of redrawing problem. 
@samhouts now i don't have time for the sample project but you can notice easily.

**Comment by samhouts** [comment]
@berserk91 @soooraj We just released another service release with some more fixes specifically for Android and ListViews. Can you please try 4.1.0.618606 and let us know if you see improvement?

Thanks!

**Comment by berserk91** [comment]
@samhouts  @soooraj  I checked in the latest version (4.1.0.618606) and it's fixed. Performance is better than 4.1.0.581479.  Compared with 3.6 its not noticeable.
Great work!

**Comment by samhouts** [comment]
Hooray! Thanks for letting us know. :)

**Comment by soooraj** [comment]
Sorry for the delay in response. I was on vacation. 

Yes!!!! I would like to confirm that it is working fine now.
