### ISSUE TITLE
Flyout item can not be hidden

### ISSUE THREAD

**Issue by huyjack178** [xamarin/Xamarin.Forms#6316]
![image](https://user-images.githubusercontent.com/11793001/58400831-692c6180-8086-11e9-8c95-e0f2ba096c80.png)
![image](https://user-images.githubusercontent.com/11793001/58400846-70ec0600-8086-11e9-99ce-1678b11b4bf9.png)
I don't want to show "Home" item in Flyout. Can I do this?

**Comment by PureWeen** [comment]
@huyjack178 is this what you're looking for?

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#flyout-behavior

**Comment by greendesigned** [comment]
I am trying to achieve a similar thing - I want to hide a number of items in the fly-out navigation menu. I just want to be able to navigate to the route using code Shell.Current.GoToAsync('/somewhere').
<ShellContent route="somewhere" HiddenFromMenu="true"...>...</ShellContent>
