### ISSUE TITLE
Button click event always fire even when a button is hidden below an entry

### ISSUE THREAD

**Issue by StanleyBroo** [xamarin/Xamarin.Forms#6319]
### Steps to Reproduce

1. Add a grid, add a button (fill the whole background with the button), add on top an editor center the editor so the button is behind it.
2. add click event to the button
3. Run the the xamarin forms app target Android 9.0
4.Click the editor textfield --->click event button fires?, why?

### Basic Information

- Version with issue:  Xamarin forms 4.0.0.425677
- Last known good version: 3.6.0.344457
- IDE: VS2019

**Comment by samhouts** [comment]
@StanleyBroo  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@StanleyBroo  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
