### ISSUE TITLE
[Bug] Rotated Xamarin.Forms.ScrollView 

### ISSUE THREAD

**Issue by shumkis** [xamarin/Xamarin.Forms#6321]
### Description
When 180 degree rotation is added to scrollview. It fails to scroll properly if it contains several media files (pictures, gifs, etc.)

### Basic Information
- Version with issue: 4.0.0.425677
- Platform: Android 9.0

**Comment by samhouts** [comment]
@shumkis  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@shumkis  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
