### ISSUE TITLE
[Bug] Picker default color not work

### ISSUE THREAD

**Issue by MaxenceSAUNIER** [xamarin/Xamarin.Forms#6322]
### Description
Picker.TitleColor = Color.Default();
OR
Picker.TitleColor =  (Color)Picker.TitleColorProperty.DefaultValue

Not return the default color for the Picker object

### Basic Information

- Version with issue: Xamarin.Forms pre-10

**Comment by samhouts** [comment]
@MaxenceSAUNIER  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@MaxenceSAUNIER  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by MaxenceSAUNIER** [comment]
I could not test the latest version of Xamarin.Forms because of other bugs. For the moment I display a message instead of putting the picker in red.
At worst, close and I'll open another ticket when I have availability to reproduce the problem.
Thanking you.
