### ISSUE TITLE
[Enhancement] SeparatorColor for BindableLayout

### ISSUE THREAD

**Issue by RedasP** [xamarin/Xamarin.Forms#6330]
## Summary

Could you introduce separator color feature for BindableLayout?

## API Changes

I would expect this feature to have the same API as ListView.SeparatorColor

## Intended Use Case

A separator would help making BindableLayout rows look more isolated

**Comment by andreinitescu** [comment]
BindableLayout is not for that, use a ListView/CollectionView

**Comment by iCodeSometime** [comment]
I'd like to point out that BindableLayout does have advantages over ListView/CollectionView in some situations - mainly it only takes up the amount of space it needs to, without any extra work. I think adding separators can only make it more useful.. I don't see any disadvantages to supporting this.

This should be a pretty simple change, is there still interest in a contribution for this?

**Comment by masterchen** [comment]
Or，  anyone  can give a  short example on how to define  the separator in itemtemplate ?

**Comment by pictos** [comment]
>  anyone can give a short example on how to define the separator in itemtemplate ?

@masterchen you can do a `BoxView` with `Height = 1`.

**Comment by masterchen** [comment]
good solution,thansk @pictos

**Comment by yousufctec** [comment]
> > anyone can give a short example on how to define the separator in itemtemplate ?
> 
> @masterchen you can do a `BoxView` with `Height = 1`.

But how do you ignore the last Boxview item to be ignored.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by 2Xpro-pop** [comment]
> > > anyone can give a short example on how to define the separator in itemtemplate ?
> > 
> > @masterchen you can do a `BoxView` with `Height = 1`.
> 
> But how do you ignore the last Boxview item to be ignored?

Without code behind, it's impossible.
