### ISSUE TITLE
[Bug] iOS effect no longer works after upgrading to XF 4.0 since UIView.Bounds has no size in PlatformEffect.OnAttached()

### ISSUE THREAD

**Issue by chrisstaley** [xamarin/Xamarin.Forms#6334]
### Description
I created an effect to add a gradient background to a UI element that no longer works in iOS after upgrading to XF 4.0 (the effect continued to work on Android). The cause of the issue is that the `UIView.Bounds` property started returning a `CGRect` with no size in the `PlatformEffect.OnAttached()` method.

I am working around this issue by rolling back to XF 3.6.

### Steps to Reproduce

1. Create an iOS `PlatformEffect` and apply it to a `ContentPage`.
2. Set breakpoint in `OnAttached()` method.

### Expected Behavior
`Container.Bounds` should have the same size as the `ContentPage`.

### Actual Behavior
`Container.Bounds` has no size (i.e. height and width are both 0).

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: 3.6.0.344457
- IDE: VisualStudio

**Comment by rmarinho** [comment]
@chrisstaley can you try as a workaround see if this will help:

```
public class GradientEffect : PlatformEffect
	{
		protected override void OnAttached()
		{
			InsertGradient();
		}

		void InsertGradient()
		{
			var page = Element as ContentPage;
			var childLabel = page?.Content as Label;
			if (childLabel != null && Container.Bounds.Width == 0)
			{
				return;
			}

			childLabel.Text = Issue6334.Success;

			var sColor = page.BackgroundColor.ToCGColor();
			var eColor = page.BackgroundColor.AddLuminosity(0.5).ToCGColor();

			Container.Layer.InsertSublayer(new CAGradientLayer
			{
				Frame = Container.Bounds,
				Colors = new CGColor[] { sColor, eColor }
			}, 0);
		}

		protected override void OnElementPropertyChanged(PropertyChangedEventArgs args)
		{
			base.OnElementPropertyChanged(args);
			if (args.PropertyName == Page.WidthProperty.PropertyName)
			{
				InsertGradient();
			}
		}

		protected override void OnDetached()
		{
		}
	}
```

The change is related with when we attach the effect (when the Renderer and NativeView is created) , and when Layout happens. 

I have a fix that I m testing, but will discuss this with the team.

**Comment by chrisstaley** [comment]
@rmarinho That is not working for me. Even when `InsertGradient()` is called via the invocation in `OnElementPropertyChanged()`, `Container.Bounds.Width` is still 0.

For reference, I tested using XF 4.0.0.482894 in an iPhone X iOS 12.2 simulator.
