### ISSUE TITLE
Русский шрифт-Russian font

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6337]
<p>При использовании русского текста на кнопках (xamarin) при сборке проекта появляется ошибка **Error parsing XML: not well-formatted (invalid token)**</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/567764/русскии-шрифт.html
VSTS ticketId: 892537_
_These are the original issue comments:_

Wendy Wang [MSFT] on 5/14/2019, 07:19 PM (13 days ago): <p>Translated from Bing:</p><p>When using Russian text on buttons (xamarin), error parsing XML: Not well-formatted (invalid token) appears when you build the project</p><p><strong></strong><u></u><sub></sub><sup></sup></p>

Visual Studio Feedback System on 5/14/2019, 11:54 PM (13 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 5/20/2019, 11:19 AM (8 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

José Gallardo Salazar [MSFT] on 5/28/2019, 06:02 AM (6 hours ago): <p>Hi Petr,</p><p>We have directed your feedback to the Xamarin.Forms engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p><p>Thank you</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
