### ISSUE TITLE
[Enhancement] Tap and hold gesture

### ISSUE THREAD

**Issue by haavamoa** [xamarin/Xamarin.Forms#6338]
## Summary
Today I implemented my own Tap and hold effect in order to tap and hold an item in a list to trigger a `ICommand`. I was wondering if you could make this a part of the shared Xamarin.Forms code. (like the other gestures we have available) (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/)

Here is my implementation :
haavamoa/TeamTimer@1fa625a

Read; I had to create a `TapOrTapAndHold` Effect to not remove ordinary tapping.

## API Changes
Gestures has to be extended with a new tap and hold gesture. 

## Intended Use Case
The developer needs a easy way to tap and hold to run a command. This is a common way of interacting with different items in a view.

**Comment by PureWeen** [comment]
@haavamoa we have a spec for this behavior here
https://github.com/xamarin/Xamarin.Forms/issues/3480

I've referenced your body of work there so we can possibly use some of it with the Long Press implementation

**Comment by haavamoa** [comment]
Allright, thank you for the quick reply!
