### ISSUE TITLE
[Enhancement]  Allow NavigationDelegate on iOS WKWebView renderer

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#6340]
## Summary
Provide a way to specify a `NavigationDelegate` on `WKWebView`

A common scenario for developers is use our Webview to visit a login page on the localhost backend. On iOS this is very hard since the restrictions applied by Apple, even the settings on the .plist don't help using the WebView. 
Developers might want to override other methods of the `UIDelegate` or `NavigationDelegate`  in the custom renderer, we should make it easier, right now it depends on private properties to work correctly.

## API Changes

```
public virtual WKNavigationDelegate CreateNavigationDelegate(IWKWebViewRenderer renderer);

public virtual WKUIDelegate CreateUIDelegate();

public interface IWKWebViewRenderer
{
	void UpdateCanGoBackForward();
	WebView WebView { get; }
	void UpdateUrlSource(string urlSource);
	string Url { get; }
	WebNavigationEvent LastNavigationEvent { get; }
	WKNavigationDelegate CreateNavigationDelegate(IWKWebViewRenderer renderer);
	WKUIDelegate CreateUIDelegate(IWKWebViewRenderer renderer);
}
```

## Intended Use Case

```
[assembly: ExportRenderer(typeof(WebView), typeof(MyWebVieRenderer))]

public class MyWebVieRenderer : CustomWkWebViewRenderer
{
	public override WKNavigationDelegate CreateNavigationDelegate(IWKWebViewRenderer renderer)
	{
		return new CustomWebViewNavigationDelegate(renderer);
	}
}
```

**Comment by Mikilll94** [comment]
On Android we can do something like this:

```
    public class CustomWebViewRenderer : WebViewRenderer
    {
        Context _context;
        public CustomWebViewRenderer(Context context) : base(context)
        {
            _context = context;
        }

        protected override WebViewClient GetWebViewClient()
        {
            return base.GetWebViewClient();
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Xamarin.Forms.WebView> e)
        {
            base.OnElementChanged(e);

            if (e.NewElement != null)
            {
                Control.SetWebViewClient(GetWebViewClient());

                // customize webview without breaking navigation events

                Control.Settings.UserAgentString = "custom user agent";
            }
        }

    }
```

On iOS we can create similar method  called```GetNavigationDelegate```. This way we would be able to customize WKWebView without breaking navigation events.

@jfversluis @samhouts

**Comment by SuperCorks** [comment]
I completely agree with this. Is anyone working on it right now? I could take it on.

**Comment by SuperCorks** [comment]
What I would do is just expose the `CustomWKNavigationDelegate` as a non-sealed public class so that other devs can decide to extend it or replace it altogether. Probably rename it to something like `FormsWKNavigationDelegate` and allow devs to override its methods and call `base(..)` or not.

**Comment by SuperCorks** [comment]
@samhouts maybe you'll be more responsive? What if we expose the `CustomWKNavigationDelegate` so developers can inherit it?

**Comment by JaapMosselman** [comment]
Just encountered this problem today. Whould be nice is this whould be simplified. 
Making `CustomWKNavigationDelegate` simply public alone is not intuitive I think. The NavigationDelegate property should get that type also instead of the interface, so that user are required to inherit `CustemWKNavigationDelegate` correctly.

For the time being, I have solved this way. A bit simplier than copying the whole renderer code.

```
    public class MysWebViewRenderer : WkWebViewRenderer
    {
        public MysWebViewRenderer() : base()
        {
        }
        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            if (e.OldElement == null)
            {
                this.NavigationDelegate = new MysWKNavigationDelegate(this.NavigationDelegate);
            }
        }

        private class MysWKNavigationDelegate : WKNavigationDelegate
        {
	    private readonly IWKNavigationDelegate _defaultDelegate;
            private IDownloadService _downloadService;

            private IDownloadService DownloadService => _downloadService ?? (_downloadService = ServiceContainer.Resolve<IDownloadService>());

            public MysWKNavigationDelegate(IWKNavigationDelegate defaultDelegate)
            {
                if (defaultDelegate == null)
                    throw new ArgumentNullException(nameof(defaultDelegate));
		_defaultDelegate = defaultDelegate;
            }

            // Be sure to implement ALL methods with are implemented by the CustomWebViewNavigationDelete, which is a private class, so we can't override it simply
            // https://github.com/xamarin/Xamarin.Forms/blob/4.6.0/Xamarin.Forms.Platform.iOS/Renderers/WkWebViewRenderer.cs

            public override void DidFailNavigation(WKWebView webView, WKNavigation navigation, NSError error)
            {
                _defaultDelegate.DidFailNavigation(webView, navigation, error);
            }

            public override void DidFinishNavigation(WKWebView webView, WKNavigation navigation)
            {
                _defaultDelegate.DidFinishNavigation(webView, navigation);
            }

            public override void DidStartProvisionalNavigation(WKWebView webView, WKNavigation navigation)
            {
                _defaultDelegate.DidStartProvisionalNavigation(webView, navigation);
            }

            public async override void DecidePolicy(WKWebView webView, WKNavigationAction navigationAction, Action<WKNavigationActionPolicy> decisionHandler)
            {
                var url = navigationAction.Request.Url;
                if (string.Compare(url.Scheme, "data", true) == 0)
                {
                    decisionHandler(WKNavigationActionPolicy.Cancel);
                    await DownloadService.SaveDownloadedAsync(url.AbsoluteString);
                }
                else
                    _defaultDelegate.DecidePolicy(webView, navigationAction, decisionHandler);
            }
        }
    }

```

**Comment by SuperCorks** [comment]
Yeah I tried that, but for some reason calling methods on the default delegate was throwing linker errors on my side.

**Comment by SuperCorks** [comment]
Also, I don't think it's a good idea to force developers to inherit a base class. I think the interface should remain.

**Comment by jfversluis** [comment]
Unfortunately this will no longer make its way into Xamarin.Forms. I think that we take this into account for .NET MAUI already, but I'll be sure to add a label here so we double-check that. Thanks everyone for your input on this!

**Comment by Alfort-G** [comment]
I concur being able to use the default NavigationDelegate and being able to override certain methods would be very useful. For example, a functionality that I am missing from the standard WebView is to be able to get an error code or some details when there is a navigation failure. I understand the only way at the moment is to create your own NavigationDelegate, with the risk of not being aligned with the official and better supported Xamarin Forms implementation one. If this is going to move to .NET MAUI, please consider the option of exposing some failure error codes as a standard.
