### ISSUE TITLE
Xamarin MasterDetailPage tap to dismiss does not work on tablets

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6348]
Using Xamarin.Forms 3.1.0.583944, I create a MasterDetailPage using the PopOver behavior. The page works as expected on Android and iOS phones. However, on Android tablets I am unable to tap off of the page to dismiss the menu - I have to slide the page away using the gesture.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/363514/xamarin-masterdetailpage-tap-to-dismiss-does-not-w.html
VSTS ticketId: 712470_
_These are the original issue comments:_

Samantha Houts [MSFT] on 11/2/2018, 02:00 PM (208 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Does the issue persist if you update to 4.0.0? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Saturn** [comment]
I have found that it only dismisses when you tap the far right side of the screen. The dimmed area in between (prominent on tablet) will not dismiss the menu when tapped.
