### ISSUE TITLE
Xamarin forms (3.3.0.912540) on Android - Custom PickerRenderer Control.Click stops working on first user's click

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6349]
On Android - Custom PickerRenderer Control.Click stops working on first user's click.<br><br>After updating nuget packages from Xamarin forms 3.2 to 3.3.0.912540.<br><br>The Xamarin Forms Picker dialog for Android has been changed by updated nugets (the UI design is kind of looking more the same how it looks on iOS). So there has been changes to Picker.<br><br>We are using a Custom PickerRenderer<br>-to add a custom dropdown icon and some styling and this works and looks same as before.<br>-to use our own picker modal we have added our Control.Click += Control_Click; event listener which previously opened our custom dialog.<br><br>Now what happens is that: <br>The first time user taps/clicks on the CustomPicker Xamarin opens the OTB Android Picker dialog (and not our custom like it did before nuget updates). And If the user selects/closes the OTB dialog and taps/clicks the CustomPicker second time; now our Control_Click event is fired and our custom picker dialog is shown.<br>Also the OTB picker dialog that opens up.. does not open smoothly; the screen flickers while the otb dialog is first rendered on top of the screen and resized/moved to the center of the screen.<br><br>So to recap what happens with our custompicker:<br>-First picker tap does not open our custom picker dialog, but the OTB dialog opens up and screen flickers while it opens.<br>-Second picker tap does open our custom dialog and all looks ok.<br><br>What we expect should happen:<br>Like it worked before. Our custompicker is tapped and only our custom dialog opens.<br><br><br>We can reproduce this issue with all our Android real test devices and emulators (API 16 - 27). And all our developers and testers.<br><br>Provided code here to better understand what is going on. the custom renderer is quite simple.<br><br>in PCL project our custompicker:<br>..public class CustomPicker : Picker<br>    {<br>        public static readonly BindableProperty ImageProperty =<br>            BindableProperty.Create(nameof(Image), typeof(string), typeof(CustomPicker), string.Empty);<br><br>        public CustomPicker()<br>        {<br>            <br>        }<br><br>        public string Image<br>        {<br>            get { return (string)GetValue(ImageProperty); }<br>            set { SetValue(ImageProperty, value); }<br>        }<br>    }<br>..<br><br>in our ..Android project the customrenderer:<br><br>using MyApp.CustomUIControls;<br>using MyApp.Android.Dependency;<br>using Xamarin.Forms;<br>using Xamarin.Forms.Platform.Android;<br>using Android.Content;<br>using Android.Graphics;<br>using Android.Graphics.Drawables;<br>using Android.Views;<br>using System;<br>using Android.Widget;<br>using Android.App;<br>using Android.Text;<br>using System.Reflection;<br><br>[assembly: ExportRenderer(typeof(CustomPicker), typeof(CustomPickerRenderer))]<br><br>namespace MyApp.Android.Dependency<br>{<br>    public class CustomPickerRenderer : PickerRenderer<br>    {<br>        CustomPicker element;<br>        private AlertDialog _dialog;<br><br>        public CustomPickerRenderer(Context context) : base(context)<br>        {<br><br>        }<br><br>        protected override void OnElementChanged(ElementChangedEventArgs&lt;Picker&gt; e)<br>        {<br>            object aa = e.NewElement.Behaviors;<br>            base.OnElementChanged(e);            <br><br>            element = (CustomPicker)Element;<br><br>            if (Control == null || Element == null || string.IsNullOrEmpty(element.Image)) return;<br>            <br>            Control.Background = AddPickerStyles(element.Image);<br>            Control.TextSize = 14f;<br>            Control.SetTextColor(global::Android.Graphics.Color.Rgb(0, 0, 0));<br>            Control.SetHintTextColor(global::Android.Graphics.Color.Rgb(199, 199, 204));<br>            Control.InputType = InputTypes.TextFlagNoSuggestions; // Disable spell checking. <br>            //Override OTB selection dialog..  <br>            Control.Click += Control_Click;<br>        }<br><br>        public LayerDrawable AddPickerStyles(string imagePath)<br>        {<br>            //custom picker background styling, shadow/borders/icon..<br>        }<br><br>        private BitmapDrawable GetDrawable(string imagePath)<br>        {<br>            //custom dropdown icon code..<br>        }<br>        protected override void Dispose(bool disposing)<br>        {<br>            Control.Click -= Control_Click;<br>            base.Dispose(disposing);<br>        }<br><br>        private void Control_Click(object sender, EventArgs e)<br>        {<br>            //custom dialog code..<br><br>	    //This does not fire on first user's tap/click anymore!!<br>        }<br>    }<br>}<br><br><br><br>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/371834/xamarin-forms-330912540-on-android-custom-pickerre.html
VSTS ticketId: 721012_
_These are the original issue comments:_

Samantha Houts [MSFT] on 11/2/2018, 01:59 PM (208 days ago): <p>We appreciate you taking the time to report this problem. We are currently prioritizing problems that are impacting a broad set of our customers, so we may not be able to investigate this one immediately. We know this problem is important to you, so we will continue to monitor it.</p>

Peter Kofod on 12/16/2018, 10:50 PM (163 days ago): <p>After updating from version 3.2 to the latest version 3.4 of xamarin forms we experience the same problem</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Does the issue persist if you update to 4.0.0? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
