### ISSUE TITLE
Xamarin Xamarin.Forms.Maps.Pin GetHashCode makes use of mutable fields

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6352]
<p>The implementation of Pin.GetHashCode is:</p><pre>public override int GetHashCode()
{
    unchecked
    {
        int hashCode = Label?.GetHashCode() ?? 0;
        hashCode = (hashCode * 397) ^ Position.GetHashCode();
        hashCode = (hashCode * 397) ^ (int)Type;
        hashCode = (hashCode * 397) ^ (Address?.GetHashCode() ?? 0);
        return hashCode;
    }
}
</pre><p>The problem with this is that Position, Label and Address are all mutable fields. This means that the hash function doesn't work when these fields change.</p><p>https://docs.microsoft.com/en-us/dotnet/api/system.object.gethashcode?redirectedfrom=MSDN&amp;view=netframework-4.7.2#notes-to-inheritors</p><p>I don't know why you've done this, but it looks like a mistake to me.</p>

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/507712/xamarin-xamarinformsmapspin-gethashcode-makes-use.html
VSTS ticketId: 830189_
_These are the original issue comments:_

Visual Studio Feedback System on 3/27/2019, 06:33 PM (62 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Visual Studio Feedback System on 4/1/2019, 01:13 PM (58 days ago): <p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We'll keep you posted on any updates to this feedback.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by andreinitescu** [comment]
The same as this one I opened two months ago: https://github.com/xamarin/Xamarin.Forms/issues/5690
If you could just let me know if it's OK to remove `Equals`, I could submit a PR.

**Comment by PureWeen** [comment]
per @andreinitescu 's note I'm closing this one
