### ISSUE TITLE
[Bug] Xamarin Forms 4 regression: ListView display glitches

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#6355]
### Description

Set up a grouped listview where tapping a group title toggles the presence/absence of content in the group. If you tap on groups enough, you'll start seeing glitches in how the ListView displays its content, like random whitespace replacing collapsed group titles.

This same scenario works fine with XF 3.6.0 with the FastRenderers_Experimental flag enabled.

I should add that this isn't just glitches. With a larger sample data set than the repro below, I was able to verify that TapGestureRecognizer.Tapped events were being delivered for different group model instances than the ones being tapped, implying that the groups being displayed were entirely out of sync with the XF4 ListView's internal state.

### Steps to Reproduce

Use the project referenced below. Tap around on the dates (titles) until you observe the kinds of glitches present in the screenshot below. And apologies for the ugliness and complexity of the repro.

### Expected Behavior

No visual glitches.

![Screenshot_1559188488](https://user-images.githubusercontent.com/218865/58607737-a09d3880-8255-11e9-9633-ee5ec27c4d07.png)

### Actual Behavior

Glitches

![Screenshot_1559188421](https://user-images.githubusercontent.com/218865/58607541-e4dc0900-8254-11e9-94b9-5a76906c3b88.png)

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: 3.6.0
- IDE: VS 2019 16.1.1
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices:

### Screenshots

See above.

### Reproduction Link

https://github.com/mfeingol/repros/tree/master/ListViewIssuesXF4

**Comment by paymicro** [comment]
Hi @mfeingol Could you try [test nuget package?](https://github.com/paymicro/Xamarin.Forms/raw/16834f7662459b493ae36413f29b159af6d57b46/.nuspec/Xamarin.Forms.9.9.4.nupkg)

**Comment by mfeingol** [comment]
@paymicro: I tested this morning with your 9.9.4 package and I believe it fixes the problem. Kudos.

**Comment by mfeingol** [comment]
A note... this isn't fixed in 4.0.0.482894.

**Comment by LeoJHarris** [comment]
Yes we are seeing the same issue in CollectionView and also ListView, Views are disappearing and not reappearing.

**Comment by jennablackwell** [comment]
This is happening to me as well.  Items in the listview when you scroll will sometimes disappear.

**Comment by mfeingol** [comment]
@paymicro: any luck getting a fix into an official XF4 release?

**Comment by toomasz** [comment]
Hopefully this can be fixed soon

**Comment by samhouts** [comment]
closed by #6390
