### ISSUE TITLE
Components inside Table view is not focusable

### ISSUE THREAD

**Issue by RabhiaBehamK** [xamarin/Xamarin.Forms#6356]
### Description

Components inside Table view ViewCell is not getting focussed.

### Code Snippet

<TableView Intent="Form"> <TableView.Root> <TableSection Title="Getting Started"> <ViewCell > <StackLayout Orientation="Horizontal"> <native:customEdit IsEnabled="true" HorizontalOptions="FillAndExpand" /> <Entry Text="Select"/> </StackLayout> </ViewCell> </TableSection> </TableView.Root> </TableView>

### Steps to Reproduce

1. Any Custom control in the TableView ViewCell
2. Get Focus to the control.
3. Focus is lost and it becomes non-editable.

### Expected Behavior

Control should get the focus and it should be editable.

### Actual Behavior

Control is not getting focussed.

### Basic Information

- Version with issue: 3.0.0.482510
- Platform Target Frameworks:  Xamarin.Forms Android.
  - Android: 8.1
- Affected Devices: Nexus Device.

**Comment by samhouts** [comment]
@RabhiaBehamK  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by RabhiaBehamK** [comment]
[CustomEntry.zip](https://github.com/xamarin/Xamarin.Forms/files/3271011/CustomEntry.zip)

**Comment by RabhiaBehamK** [comment]
Hi @samhouts, I have attached the sample project that reproduces the issue. Thanks!

**Comment by samhouts** [comment]
@RabhiaBehamK I don't believe this is related to Xamarin.Forms. The error message in the debug log is 

```
TextView does not support text selection. Selection cancelled.
```

This is from Android. Try searching for that error message for help. If we have any ideas, we'll let you know. Thanks!

**Comment by jfversluis** [comment]
I have briefly looked int this @RabhiaBehamK. As @samhouts already mentioned, it's not related to Xamarin.Forms. It's not even related to Xamarin at all. Apparently it's a bug in Android as you can see here: https://issuetracker.google.com/issues/37095917. Is have been open for a long time.

I've tried to come up with a workaround for you to use but I couldn't get it to work in the time I had, sorry :( if you find anything, please let us know so maybe others can benefit as well.
