### ISSUE TITLE
[Bug][Forms] How to bind to a JObject in XAML

### ISSUE THREAD

**Issue by landl0526** [xamarin/Xamarin.Forms#6364]
### Description

I don't want to predefine a model class to represent a json string. I want to bind to the JObject directly.
Here is my json string:
```
string jsonStr = @"{
                        section: 
                        { 
                        title: ""Login"",
                        body: ""This is your body!""
                        },
                    }";
```
And I have set the page's binding context to this json object:
```
var jsonObject = JsonConvert.DeserializeObject(jsonStr);
BindingContext = jsonObject;
```
Then I used the binding in my XAML like:
`<Label HorizontalTextAlignment="Center" Text="{Binding Path=[section][body]}" />`
But it failed with showing nothing.
However, if I consumed it like:
```
<Label HorizontalTextAlignment="Center"
               BindingContext="{Binding Path=[section]}"
               Text="{Binding Path=[title]}" />
```
It displayed correctly. It seems binding only recognizes the first primary level. But I want it to digger further to get the information if I have a complicated json string.

I wonder whether this is a bug or designed by default.

### Expected Behavior

I want to use binding like: Path=[section][body][...]

### Actual Behavior

It only recognized the first level.

### Basic Information

- Version with issue: 4.0.0425677
- Last known good version: Unknown
- IDE: VS for Windows
- Platform Target Frameworks:  All platforms.

### Screenshots

![Capture](https://user-images.githubusercontent.com/38024956/58677673-7f406780-838f-11e9-874b-a2b1bec34eea.PNG)

**Comment by jcmanke** [comment]
>I don't want to predefine a model class to represent a json string. 
Why not?

**Comment by samhouts** [comment]
@landl0526 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by landl0526** [comment]
@samhouts Here is a sample.
[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3246289/Sample.zip)

**Comment by KSemenenko** [comment]
and so it was possible to do?

**Comment by jfversluis** [comment]
It works if you simply add a dot between the properties as you would with "normal" properties.

I changed the line that should show the body to this`<Label HorizontalTextAlignment="Center" Text="{Binding Path=[section].[body]}" />` note the dot between `[section]` and `[body]` and now it shows up.

![image](https://user-images.githubusercontent.com/939291/59413470-e3b3eb80-8dbf-11e9-8820-5bc60d873640.png)

Could you please confirm you see this as well? :) If everything is OK now you can close this issue, thank you!

**Comment by landl0526** [comment]
@jfversluis Ah, glad to know that. Thank you.
