### ISSUE TITLE
[Bug] FontImageSource does not work on UWP

### ISSUE THREAD

**Issue by jbe2277** [xamarin/Xamarin.Forms#6367]
### Description
Using the FontImageSource in UWP does not work. I have used the tutorial of James Montemagno to include Material Design Icons as Font: https://montemagno.com/using-font-icons-in-xamarin-forms-goodbye-images-hello-fonts/

UWP: This works:
```XML
<Label FontFamily="{StaticResource MaterialFontFamily}" Text="&#xf59f;"/>
```

UWP: This does not work:
```XML
<ToolbarItem Command="{Binding LaunchWebBrowserCommand}" Text="Browser">
  <ToolbarItem.IconImageSource>
    <FontImageSource Glyph="&#xf59f;" FontFamily="{StaticResource MaterialFontFamily}"/>
  </ToolbarItem.IconImageSource>
</ToolbarItem>
```

- On Android both variants work as expected. 
- On UWP I tried to use other elements (e.g. Page) as well but the IconImageSource property seems not to be working as expected.

### Basic Information

- Version with issue: 4.0.0.425677
- Platform Target Frameworks:
  - UWP:  17763

**Comment by samhouts** [comment]
@jbe2277 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jbe2277** [comment]
The issue was on my side. I forgot to set the `FontImageSource.Color` property. The default color is White which was fine for Android but it does not work well with the white background of UWP.
