### ISSUE TITLE
[Bug] CollectionView - Label Bindings LayoutOptions rendering

### ISSUE THREAD

**Issue by bcaceiro** [xamarin/Xamarin.Forms#6369]
### Description
When using CollectionView, with a label with HorizontalOptions = Center, after scrolling up and down, the label "disappears", or gets cut, this happens when setting Bindings on a Label. If we set the Text directly, it seems the issue does not reproduce. 

### Steps to Reproduce

1.  Create CollectionView
2. Add Label with VerticalOptions=Center
3. Scroll up and down slow or fast

### Expected Behavior
Label should mantain its position and display correctly
### Actual Behavior
Label disappears or gets cut
### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: --
- IDE: Visual Studio Mac 2019 and Visual Studio 2019
- Platform Target Frameworks:
      - Android: 8.1
- Android Support Library Version: v28.0.1
- Nuget Packages: Basic Nugets from a fresh project - Essentials. Xamarin.Forms, Support Libraries
- Affected Devices:
Samsung Galaxy S9, Emulator, Huawei P20 Lite, etc.
### Screenshots
![image](https://user-images.githubusercontent.com/2139254/58697989-46ee5880-8392-11e9-821f-4fdcaa5f3e72.png)

Repro Vídeo: 
https://streamable.com/45rog

### Reproduction Link
See project -> https://github.com/bcaceiro/XamarinTests
Click on CollectionView bindings, scroll up and down, see numbers disappearing.

**Comment by adrianknight89** [comment]
@bcaceiro I ran your repro with 4.4.0.1174-nightly and did not see the issue. Can you confirm this ticket is no longer valid? If so, @samhouts can close it.

**Comment by samhouts** [comment]
I confirm that this no longer occurs on 4.3.0-pre3. Thanks!
