### ISSUE TITLE
[Bug] [CustomRenderer] [iOS] View.Bounds all 0 OnElementChanged

### ISSUE THREAD

**Issue by TMagnum1974** [xamarin/Xamarin.Forms#6372]
### Description
Custom Renderer for a grandient background stopped working when upgrading to Xamarin Forms 4.x.x (from 3.6.x). View.Bounds width, height all 0

### Steps to Reproduce

1. Create custom iOS renderer deriving from PageRenderer class
2. Add override to OnElementChanged
3. Add code to render a grandient background

```
base.OnElementChanged(e);

            if (e.OldElement == null) // perform initial setup
            {
                var page = e.NewElement as GradientContentPage;

                var gradientLayer = new CAGradientLayer
                {
                    Frame = View.Bounds,
                    Colors = new CGColor[] { page.StartColor.ToCGColor(), page.EndColor.ToCGColor() }
                };

                View.Layer.InsertSublayer(gradientLayer, 0);
            }

```
### Expected Behavior
View.Bounds hat the actual width and height of the view. Adding a new CAGradientLayer used View.Bounds and had the current view's size.

### Actual Behavior
View.Bounds are all 0 (width, height) and thus the new Layer is not displayed (means: it's width and height are both 0)

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: 3.6.x
- IDE: Visual Studio for Mac 8.8.8 (build 2)
- Platform Target Frameworks: 
  - iOS:  12.2
- Nuget Packages: FFImageLoading
- Affected Devices: iPhone

**Comment by samhouts** [comment]
releated to #6334
