### ISSUE TITLE
[Bug] [iOS] Shell Displays TabBar when only one ShellContent Present

### ISSUE THREAD

**Issue by Robtom5** [xamarin/Xamarin.Forms#6373]
### Description
Navigation to the first flyout item in shell from a page registered as a global route causes a tabbar to appear on iOS.

### Steps to Reproduce

1. Create a shell with two flyout items, each with one tab and one shell content
2. Register a global route to a page (pageA)
3. Navigate to pageA
4. From within pageA, call Shell.Current.Navigation.PopAsync and navigate to the first item in the Shell.Current.GoToAsync("flyoutitem1/tab1")

### Expected Behavior
The content for tab1 displays as expected with no tab bar

### Actual Behavior
The content for tab1 displays as expected but with a tabbar with a single item. This display does not follow any calls to SetTabBarVisible in the constructor or the OnAppearing for the page. This tab bar does not disappear when navigating to global routes from this page. However it does disappear if a different flyout item is selected and then the user navigates back to the first flyout item.

### Basic Information

- Version with issue: 4.0.0.471375
- Last known good version: ---
- IDE: Visual Studio Enterprise 2019
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![error](https://user-images.githubusercontent.com/9417090/58716747-9d26c000-83c1-11e9-922d-efa05d7f4db4.png)

**Comment by samhouts** [comment]
@Robtom5  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Robtom5** [comment]
I've uploaded a demo application to here https://github.com/Robtom5/XamarinBugDemo-6373

The bug is visible when used with an ios 12.2 simulator on an iPhone X

**Comment by jfversluis** [comment]
Not sure if it's an exact duplicate but at least seems related to #6485. Seems like the initial landing through a `GoToAsync` call doesn't take into account the value for `TabBarIsVisible`.

**Comment by samhouts** [comment]
closed by #10448
