### ISSUE TITLE
No longer able to compile after upgrading to XF 4.0.0 Service Release 1

### ISSUE THREAD

**Issue by pasteusernamehere** [xamarin/Xamarin.Forms#6375]
After upgrading to XF 4.0.0 SR1 I can no longer compile my solution.

Error |   | Position 5:14. Missing a public static GetAutowireViewModel or a public instance property getter for the attached property "Prism.Mvvm.ViewModelLocator.AutowireViewModelProperty" | TestCase | C:\Users\Administrator\Documents\Code\TestCase\TestCase\TestCase\Views\TestPage.xaml   

### Steps to Reproduce

1. Using VS2019 create a new XF app.
2. Update XF to latest service release.
3. Add Prism.DryIoc.Forms to projects.
4. Add a new Prism ContentPage using the template pack.
5. Compile the solution.

### Expected Behavior
Clean compile

### Actual Behavior
Compile failure

Error |   | Position 5:14. Missing a public static GetAutowireViewModel or a public instance property getter for the attached property "Prism.Mvvm.ViewModelLocator.AutowireViewModelProperty" | TestCase | C:\Users\Administrator\Documents\Code\TestCase\TestCase\TestCase\Views\TestPage.xaml  

### Basic Information

- Version with issue: XF 4.0.0.471375 Prism.DryIoc.Forms 7.1.0.431
- Last known good version: XF 4.0.0.425677 Prism.DryIoc.Forms 7.1.0.431
- IDE: VS2019

**Comment by ValonK** [comment]
I have exactly the same issue without using Prism, with the following errors 

`No property, bindable property, or event found for 'BackgroundColor', or mismatching type between value and property.	`

`No property, bindable property, or event found for 'ItemTemplate', or mismatching type between value and property`

` No property, bindable property, or event found for 'Content', or mismatching type between value and property`

IDE: VS2019
XF: 4.0.0.471375

**Comment by samhouts** [comment]
@ValonK I think you need to clean and rebuild your solution. If that does not work, can you please attach a project reproducing the problem? Are you using Shell? Thanks

**Comment by ValonK** [comment]
@samhouts I have cleaned, deleted obj+bin, cleared nuget cache... nothing seems to work. No I'm not using Shell, yeah sure I will upload a sample later

**Comment by pasteusernamehere** [comment]
Test case attached.  Cleaning solution does not resolve this issue.

[TestCase.zip](https://github.com/xamarin/Xamarin.Forms/files/3242576/TestCase.zip)

**Comment by bcaceiro** [comment]
This also applies to the package PancakeView - missing CornerRadiusProperty, Not sure If I need to open a new issue for this.

**Comment by samhouts** [comment]
Thanks for the reports! We're pretty sure we know what's going on, and yes, these all have the same root cause. We'll be releasing a fix as soon as we can.

**Comment by xamarindevelopervietnam** [comment]
same problem, clean up, deleted bin and obj folder then rebuild but still can't compile project

**Comment by samhouts** [comment]
Thanks for the report! We've decided to pull SR1 from NuGet, so we recommend rolling back to the previous stable version of 4.0.0 for the time being. SR2 is being prepared as we speak! Sorry for the inconvenience, and thank you for your patience!!

**Comment by xamarindevelopervietnam** [comment]
great to hear that @samhouts

**Comment by samhouts** [comment]
SR2 is now live on NuGet. Thanks again for the quick reports! Let us know if you find any other issues.

**Comment by xamarindevelopervietnam** [comment]
awesome!

**Comment by bcaceiro** [comment]
Where can we find the release notes? Can't find it in docs, or the release tabs here in Github
