### ISSUE TITLE
[Enhancement] Add Markup Extension for FontImageSource

### ISSUE THREAD

**Issue by ahoefling** [xamarin/Xamarin.Forms#6376]
## Summary
`Xamarin.Forms.FontImageSource` was completed for v3.6.0 in issue #3189. The original issues discusses creating a markup extension to easily use this new feature in any XAML property that is of type `ImageSource`.

**It appears to have never been implemented**

## API Changes
Simplify the verbose usage of `FontImagesource`

```xaml
<ImageButton>
    <ImageButton.Source>
        <FontImageSource
            FontFamily="{StaticResource MyFontFamily}"
            Glyph="{StaticResource SmileFace}"
            Color="{StaticResource PrimaryColor}" />
    </Image.Source>
</ImageButton>
```

```xaml
<Image Source="{FontImage FontFamily={StaticResource MyFontFamily}, Glyph={StaticResource SmileFace}, Color={StaticResource White}" />
```

# Intended Use Case
For a trivial `Image` this isn't that useful but the power of this markup extension is when another Element has a property of type `ImageSource`. Consider the following real-world example in the new Xamarin.Forms Shell Spec

```xaml
<TabBar>
    <Tab Title="Hello">
        <Tab.Icon>
            <FontImageSource 
                FontFamily="{StaticResource MyFontFamily}"
                Glyph="{StaticResource SmileFace}"
                Color="White" />
        </Tab.Icon>
        <ShellContent ContentTemplate="{DataTemplate views:HelloPage}" />
    </Tab>
    <Tab Title="World">
        <Tab.Icon>
            <FontImageSource 
                FontFamily="{StaticResource MyFontFamily}"
                Glyph="{StaticResource FrownFace}"
                Color="White" />
        </Tab.Icon>
        <ShellContent ContentTemplate="{DataTemplate views:BoxesPage}" />
    </Tab>
</TabBar>
```

After we implement the markup extension the verbose XAML can be simplified removing 6 lines of code with each usage.

```xaml
<TabBar>
    <Tab Title="Hello" Icon="{FontImage FontFamily={StaticResource MyFontFamily}, Glyph={StaticResource SmileFace}, Color={StaticResource White}">
        <ShellContent ContentTemplate="{DataTemplate views:HelloPage}" />
    </Tab>
    <Tab Title="World" Icon="{FontImage FontFamily={StaticResource MyFontFamily}, Glyph={StaticResource FrownFace}, Color={StaticResource White}">
        <ShellContent ContentTemplate="{DataTemplate views:BoxesPage}" />
    </Tab>
</TabBar>
```

**Comment by ahoefling** [comment]
I have the code for this and I am willing to contribute it to the platform once approved. Feel free to assign it to me when we get there and I can submit a PR

**Comment by toomasz** [comment]
Great idea, could you share markup extension code?

**Comment by ahoefling** [comment]
@samhouts I have the change as described working in a fork with test coverage. I am ready to submit the PR, should I go ahead and submit the PR now or wait for API discusion?

**Comment by samhouts** [comment]
@ahoefling Go for it! Thanks!!!
