### ISSUE TITLE
[Enhancement] New input event types that are only invoked on actual user input.

### ISSUE THREAD

**Issue by JeroMiya** [xamarin/Xamarin.Forms#6377]
## Summary
Events like `Picker.SelectedIndexChanged` et. al. often get invoked from non-user-input. For instance, there is an extraneous `Picker.SelectedIndexChanged` event somewhere during view instantiation. We need versions of these events that ONLY fire on actual user input and not on databinding changes/etc...

## API Changes

Not sure what the best naming convention should be, but maybe something like this:

```XAML
    <Picker SelectedItem="{Binding SelectedThing}" 
                 UserSelectedItem="Picker_UserSelectedItem"
                 SelectedIndexChanged="Picker_SelectedIndexChanged" />
```

And the code-behind:
```CSharp
        // have to run the view once to figure out how many extraneous callbacks we're going to
        // get that we need to ignore.
        private int indexChangedIgnoreCounter = 1; 
        private void Picker_SelectedIndexChanged(object sender, EventArgs e)
        {
            if(ignoreCounter > 0) { ignoreCounter--; return; }
            // This gets called once without the user interacting with the control
            // AND whenever the user selects an item
        }

        private void Picker_UserSelectedItem(object sender, EventArgs e)
        {
            // This ONLY gets called when the actual user selects a new item in the Picker
        }

```

## Intended Use Case
Often user interaction with one input control, such as a Picker, should result in a change in other parts of the page. For example, if there is a `Picker` and an `Entry`, and you want changes to the `Picker` control to clear out the `Entry`, but you DON'T want extraneous event callbacks from, say, the data-binding system or component initialization to cause the text of the `Entry` to be cleared, only user input.

Currently, the only way I've been able to accomplish this is by counting the number of extraneous events I get during view instantiation, create a counter variable that counts down each time the "IndexChanged" or other event callback is called, but otherwise ignore the event until the counter reaches zero. Obviously this is quite the hack for something that seems like it should be simple and built-in.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
