### ISSUE TITLE
[Bug] [iOS] content page in tabbed page not showing inside shell tab

### ISSUE THREAD

**Issue by yifanlow1991** [xamarin/Xamarin.Forms#6384]
### Description
Content inside tabbed page showing black/blank page when place a tabbed page inside shell tabbar or after Shell is navigate to another Tabbed page. 
### Steps to Reproduce

1. Create a shell with bottom tabbar items.
2. Place a tabbed page for one of the tab content or navigate to a tabbed page from shell.

### Expected Behavior
The tabbed page's content is expected to be displayed.

### Actual Behavior
The tabbed page's content display as black content.

### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version:
- IDE: Visual Studio Community 2017 (15.9.6) 
- Platform Target Frameworks: 
  - iOS: 12.2  
- Nuget Packages: Basic Nugets from a fresh project

### Screenshots

Screenshots from simulator
![2019-06-03_02-33-17-PM](https://user-images.githubusercontent.com/28820562/58780780-9475fa00-860c-11e9-9a4d-b012a1237fd5.png)
![2019-06-03_02-33-30-PM](https://user-images.githubusercontent.com/28820562/58780810-aa83ba80-860c-11e9-980b-6f6ae8d6710d.png)

### Reproduction Link

[TabbedPageBlankContent.zip](https://github.com/xamarin/Xamarin.Forms/files/3246157/TabbedPageBlankContent.zip)

**Comment by wesoos** [comment]
Hello, is  there an ETA on this fix?

**Comment by agusibrahim** [comment]
same here. i want to create top tabbed on some page, i use tabbedpage just show black screen

**Comment by wesoos** [comment]
ETA?  This is a significant issue don't you think?

**Comment by marcosmusk** [comment]
Any position about this issue?

**Comment by wesoos** [comment]
Any word on this?

**Comment by wesoos** [comment]
Hello?  Any word on this?  I can't imagine a reason why this bug would not be worked on immediately...

**Comment by wesoos** [comment]
@samhouts Please provide an update

**Comment by samhouts** [comment]
This is on the backlog. I do not currently have an estimate of when we may begin working on it. Thanks for your patience!

**Comment by dfandler** [comment]
Is there a workaround for this problem ? I could use shell Tabs, but then i loose the swipe controlling from tabbed pages, and with tab visibility disabled, there is no option to navigate through the tabs anymore.

**Comment by batfink1234** [comment]
When navigating to a tabbed page using pushasync inside the shell I get a black page like everyone else but if you use pushmodalasync it shows but obviously doesn't have a navigation bar, bit of a hack for the time being until the issue is solved.

**Comment by carl-neng** [comment]
Yes, I have problem like this. What we can I do?

**Comment by burrowj** [comment]
Issue for me too.  Will go back to pre Shell.  The only reason I'm doing this is because there seems to be no support in Shell for deep hierarchy tabs where i can easily change the tab items based on the current page.  Am i wrong here?

**Comment by khurumkkj** [comment]
I would suggest that you create your own renderer and and overide the 
ViewDidLayoutSubviews

The below code has fixed it. Change namespaces accordingly

`using System;
using DSRApp.iOS.Renderers;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;


[assembly: ExportRenderer(typeof(TabbedPage),typeof(XTabbedRenderer))]
namespace DSRApp.iOS.Renderers
{
    public class XTabbedRenderer: TabbedRenderer
    {
        Page Page => Element as Page;

        public XTabbedRenderer()
        {
        }

        public override void ViewDidLayoutSubviews()
        {
            base.ViewDidLayoutSubviews();
            if (Element == null)
                return;

            if (Element.Parent is BaseShellItem)
                Element.Layout(View.Bounds.ToRectangle());

            if (!Element.Bounds.IsEmpty)
            {
                View.Frame = new System.Drawing.RectangleF((float)Element.X, (float)Element.Y, (float)Element.Width, (float)Element.Height);
            }

            var frame = View.Frame;
            var tabBarFrame = TabBar.Frame;
            Page.ContainerArea = new Rectangle(0, 0, frame.Width, frame.Height - tabBarFrame.Height);

            
        }

    }
}
`

**Comment by PTEC3D50** [comment]
> I would suggest that you create your own renderer and and overide the
> ViewDidLayoutSubviews
> 
> The below code has fixed it. Change namespaces accordingly
> 
> `using System;
> using DSRApp.iOS.Renderers;
> using Xamarin.Forms;
> using Xamarin.Forms.Platform.iOS;
> 
> [assembly: ExportRenderer(typeof(TabbedPage),typeof(XTabbedRenderer))]
> namespace DSRApp.iOS.Renderers
> {
> public class XTabbedRenderer: TabbedRenderer
> {
> Page Page => Element as Page;
> 
> ```
>     public XTabbedRenderer()
>     {
>     }
> 
>     public override void ViewDidLayoutSubviews()
>     {
>         base.ViewDidLayoutSubviews();
>         if (Element == null)
>             return;
> 
>         if (Element.Parent is BaseShellItem)
>             Element.Layout(View.Bounds.ToRectangle());
> 
>         if (!Element.Bounds.IsEmpty)
>         {
>             View.Frame = new System.Drawing.RectangleF((float)Element.X, (float)Element.Y, (float)Element.Width, (float)Element.Height);
>         }
> 
>         var frame = View.Frame;
>         var tabBarFrame = TabBar.Frame;
>         Page.ContainerArea = new Rectangle(0, 0, frame.Width, frame.Height - tabBarFrame.Height);
> 
>         
>     }
> 
> }
> ```
> 
> }
> `

It's work great for us !! Thanks !

**Comment by xamarindevelopervietnam** [comment]
Guys, should use Shell for Production?

**Comment by mohsen-mohamed** [comment]
i have the same problem
on XF 4.8.0.1821
and 5.0.0.2012
