### ISSUE TITLE
Support x:Arguments and x:FactoryMethod in XAML intelisense

### ISSUE THREAD

**Issue by jsuvanto** [xamarin/Xamarin.Forms#6388]
### Description

Visual Studio displays an error when specifying CollectionView.ListItemsLayout in XAML. Project still builds and item layout seems to work properly.

### Steps to Reproduce

1. Create a new Xamarin.Forms project
2. Add these lines to MainPage.xaml:
```
<CollectionView>
  <CollectionView.ItemsLayout>
    <ListItemsLayout SnapPointsAlignment="Center" SnapPointsType="Mandatory">
      <x:Arguments>
        <ItemsLayoutOrientation>Horizontal</ItemsLayoutOrientation>
      </x:Arguments>
    </ListItemsLayout>
  </CollectionView.ItemsLayout>
</CollectionView>
```

### Expected Behavior
No errors.

### Actual Behavior
The following error is shown in the error list:
> Error XLS0507: Type 'ListItemsLayout' is not usable as an object element because it is not public or does not define a public parameterless constructor or a type converter.

### Basic Information

- Version with issue: 4.0.0.425677
- IDE: Visual Studio 2019 (16.1.1)

**Comment by jfversluis** [comment]
Also happens in VS4Mac 

![image](https://user-images.githubusercontent.com/939291/59437749-6ce41600-8df2-11e9-9006-7a108e6a5c6d.png)

**Comment by mgoertz-msft** [comment]
Adding [Parameter("Orientation")] like you did in #6516 should be enough. I don't have a NuGet package with that change but when I debug through this and pretend that the ctor has this parameter attribute with that value then the rest of the code works as expected and I do not get the error.

**Comment by StephaneDelcroix** [comment]
@mgoertz-msft y, [Parameter] works around it, but shouldn't intelisense support `x:Arguments` ?

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix  That's actually the first time that I have seen `x:Arguments`. There is zero support for this construct in the language service at this point. Adding [Parameter] will allow the following syntax w/o errors:

```
<ListItemsLayout SnapPointsAlignment="Center" SnapPointsType="Mandatory" Orientation="Horizontal">
    <!--<x:Arguments>
        <ItemsLayoutOrientation>Horizontal</ItemsLayoutOrientation>
    </x:Arguments>-->
</ListItemsLayout>
```

How common is `x:Arguments`?

**Comment by StephaneDelcroix** [comment]
> @StephaneDelcroix That's actually the first time that I have seen x:Arguments

This explain that :)

It's not that common on our code base, as we have `[Parameter]` to avoid that atrocious syntax, but I expect it's quite common on user code when they instantiate ViewModels from Xaml.

Do I have to assume there's no support for x:FactoryMethod either, as the two gets together usually ?

**Comment by mgoertz-msft** [comment]
Correct, that's another first for me since neither one exists in WPF or UWP.  :)

I you think that's going to become a problem then we may need to add something to the backlog.

cc @pierceboggan 
Could someone also add Maddy and Ashley. I don't have their GitHub user names.

**Comment by StephaneDelcroix** [comment]
I think it's supported in WPF. it's definitely not invented here :)

> Could someone also add Maddy and Ashley

@maddyleger1

**Comment by mgoertz-msft** [comment]
Ah, it's from [XAML 2009](https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/x-arguments-directive), which the last time I checked is not supported to build WPF or UWP UI.

**Comment by mgoertz-msft** [comment]
And [here ](https://docs.microsoft.com/en-us/dotnet/framework/xaml-services/built-in-types-for-common-xaml-language-primitives)is why we never supported it:

> WPF Support
In WPF, you can use XAML 2009 features but only for XAML that is not markup-compiled. Markup-compiled XAML for WPF and the BAML form of XAML do not currently support the XAML 2009 keywords and features.

>A scenario where you can use XAML 2009 features together with WPF is if you author loose XAML and you then load that XAML into a WPF runtime and object graph with XamlReader.Load. The WPF System.Windows.Markup.XamlReader and its Load can process XAML 2009 language keywords and features into a valid object graph representation.

**Comment by StephaneDelcroix** [comment]
so it _was_ supported

**Comment by jsuvanto** [comment]
`x:Arguments` is used in this example: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/scrolling#snap-points

**Comment by jsuvanto** [comment]
If one removes `x:Arguments`, the error message is still the same, but the popup gives some more information: "No default constructor found".
![image](https://user-images.githubusercontent.com/31312451/59751577-773a6000-9289-11e9-9069-73e3275f802c.png)

**Comment by mgoertz-msft** [comment]
Are you using a Xamarin Forms NuGet package that has the fix for #6516 included?

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix The WPF and UWP markup compilers never supported XAML 2009 and that's why we never supported it either. When we started to support Xamarin we did some work though to support the built-in 2009 types and also x:Reference -- and now I finally realized where that one came from :)

**Comment by jsuvanto** [comment]
@mgoertz-msft No I'm not. Where can I get that package? The latest pre-release available in NuGet.org is from June 13th and the fix is newer.

#6516 appears to introduce the `Orientation` argument as a parameter, so that orientation can be set without the hassle of using `x:Arguments`, which is certainly a useful addition. However, as far as I can tell, this bug has nothing to do with `x:Arguments`, but recognizing the `ListItemsLayout` element instead. 

As I said, having removed the `x:Arguments` tags still causes the error message to be produced. This code produces the error as well:

```
<CollectionView>
  <CollectionView.ItemsLayout>
    <ListItemsLayout SnapPointsAlignment="Center" SnapPointsType="Mandatory"/>
  </CollectionView.ItemsLayout>
</CollectionView>
```

Based on the error message, I assume there needs to be a parameterless constructor for ListItemsLayout. 

Perhaps setting a default value to the only parameter would work, too. That is, change from:
`public ListItemsLayout([Parameter("Orientation")] ItemsLayoutOrientation orientation) : base(orientation)`
to:
`public ListItemsLayout([Parameter("Orientation")] ItemsLayoutOrientation orientation = ItemsLayoutOrientation.Vertical) : base(orientation)`

For what it's worth, I tested this with 4.1.0.496342-pre2, and behaviour is identical to original bug report.

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix may be able to answer the question for how to get a NuGet package that contains the change from #6516.

The addition of the [Parameter("Ortientation")] attribute is all that's needed to tell our IntelliSense engine that ListItemsLayout can be instantiated with that constructor and it should no longer produce an error message.

**Comment by StephaneDelcroix** [comment]
oh, that's easy. click on the PR, click on the merge commit, find out all the branches and tags in which this commit is included (at this time, only master)

**Comment by jsuvanto** [comment]
@mgoertz-msft thank you for the explanation. @StephaneDelcroix thank you for the instructions.

**Comment by StephaneDelcroix** [comment]
ping @mgoertz-msft. Any azdo ticket on which we would be able to track the support of x:Arguments and x:FactoryMethod ?

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix This is currently tracked through this feedback ticket:
https://developercommunity.visualstudio.com/content/problem/705562/intellisense-doest-recognize-xfactorymethod-attrib.html

**Comment by mgoertz-msft** [comment]
And I'm working on it.  ;-)

**Comment by samhouts** [comment]
Looks like this was implemented in March. Thanks!
