### ISSUE TITLE
Shell with MainPage

### ISSUE THREAD

**Issue by TonyLugg** [xamarin/Xamarin.Forms#6397]
## Summary
Need more menu choices than Flyout and Bottom Toolbar.

## API Changes

While Flyout will work fine for many apps, we still need a MainPage (home) approach for ours.  The shell should allow a "main page" approach where buttons on the main page are the main menu for the app.  Since our app is very state sensitive, jumping to other parts of the app from a Flyout is detrimental.  We could stick with Push/Pop, but would like to embrace the URL navigation.

## Intended Use Case
Per above.

**Comment by PureWeen** [comment]
@TonyLugg If I'm understanding you correctly you want to achieve the idea of registering in globalroutes but with something you can define in the XAML?

**Comment by TonyLugg** [comment]
Yes, I think that would be good.  Similar to Flyout but a page-based menu that is always visible on the home page.

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by PureWeen** [comment]
One of the projects for Shell being actively developed on are segues

https://github.com/xamarin/Xamarin.Forms/issues/4594

which would allow the type of navigation you are wanting.

**Comment by TonyLugg** [comment]
Or perhaps continue to use buttons and call Shell.CurrentShell.GoToAsync....

**Comment by PureWeen** [comment]
@TonyLugg could you use MenuItem with commands to push the pages? 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#menu-items

**Comment by TonyLugg** [comment]
If it doesn't need a Flyout menu I could, I suppose.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
