### ISSUE TITLE
Xamarin.Forms WPF is broken with higher version than 4.0.0.425677 [Bug] 

### ISSUE THREAD

**Issue by maexsp** [xamarin/Xamarin.Forms#6399]
Xamarin.Forms iOS, Android, UWP and WPF worked well with Xamarin.Forms v 4.0.0.425677. But after updating to any higher version of nuget Xamarin.Forms.Platform.WPF + Xamarin.Forms (E.g. 4.0.0.482894, June 3 2019) than WPF application starts with black screen, without any exception or any debug output error.

- Version with issue: v 4.0.0.482894
- Last known good version: v 4.0.0.425677
- IDE: VS2017

**Comment by ZeProgFactory** [comment]
I've the same issue on Windows 10 pro 1809 .

### Reproduction Link
https://github.com/ZeProgFactory/XFTestPlatformes

**Comment by consoleit** [comment]
Same error. Just updated to 4.0.0.482894 from 4.0.0.425677. Got a black screen. Navigation and page creation happens but nothing showing in the screen. Windows 10 + VS2019

**Comment by KevinJalais** [comment]
Same error with package Xamarin.Forms.Platform.Wpf v4.0.0.482894.
Windows 10 + VS2019.

Downgrading only this package to v4.0.0.425677.
No need to downgrade other Xamarin.Forms package.
