### ISSUE TITLE
[Xamarin Forms Android] How to remove navigation bar shadow?

### ISSUE THREAD

**Issue by habella** [xamarin/Xamarin.Forms#6400]
## Summary
How to remove the bottom shadow from the navigation bar in Android

## Basic Information
Version with issue: Xamarin Forms 4.0

Platform Target Frameworks:
Android: API 24

**Comment by jfversluis** [comment]
Hey @habella thank you for your question. Did you find an answer yet?

I am not sure of which navigation bar you mean. Could you maybe provide some sample code or a screenshot?

Also, although we are of course happy to help, you might have more luck trying on [StackOverflow](https://stackoverflow.com/questions/tagged/xamarin.forms) or the [forums](https://forums.xamarin.com/).

**Comment by habella** [comment]
Hey @jfversluis  I have attached an image describing my problem.

![Sin título](https://user-images.githubusercontent.com/6698728/59834502-67358580-9348-11e9-844c-cb6e7f496811.png)

Thank you.

**Comment by samhouts** [comment]
@habella  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@habella  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by habella** [comment]
Hello sorry for the delay, an example can be shown in one of the official examples, Xaminals, in iOS does not show the shadow below the navigationBar but in Android has the shadow.

URL Example: [https://docs.microsoft.com/es-es/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/ ](url)
