### ISSUE TITLE
Xamarin.Forms UWP Picker collapses on opening Dropdown menu [Bug] 

### ISSUE THREAD

**Issue by maexsp** [xamarin/Xamarin.Forms#6403]
![picker_uwp](https://user-images.githubusercontent.com/15746917/58880478-40d0e280-86d8-11e9-9163-e31f52f656d3.gif)
In UWP Apps the Picker control does collapse the entire control when opening the Dropdown menu. This results in a jumping layout, especially if any other controls in same flexible layout hierarchy. 
Important side note: The title must be set and should be smaller than the size of the picker item strings. Also the picker color property must be set (which anyway has a default value).

### Steps to Reproduce
1.  Use a Picker control, define 2 or more string items, do NOT set WidthRequest or MinimumWidthRequest
2.  Run the App, open the Picker Dropdown menu 
3.  --> entire Pickers (behind the Dropdown menu) collapses.
4. After closing or selecting a item the Pickers gets visible again.

### Expected Behavior
The Picker should stay visible with its actual width and height until a other item is selected or the Dropdown menu is otherwise closed somehow.

- Version with issue: Xamarin.Forms UWP, 4.0.0.471375 and 4.0.0.482894
- IDE: VS2017

Workaround: Set a WidthRequest and/or MinimumWidthRequest.

Sample Code:
```
                    <FlexLayout Direction="Row" Wrap="Wrap" JustifyContent="Start" AlignItems="Start" AlignContent="Start">
                        <Picker VerticalOptions="Center" Margin="0" 
                                TextColor="Blue" Title="Test"
                                SelectedIndex="2" SelectedItem="{Binding SelectedDevice}">
                            <Picker.Items>
                                <x:String>Device A</x:String>
                                <x:String>Custom Device B</x:String>
                                <x:String>Latest Prototype C</x:String>
                            </Picker.Items>
                        </Picker>
                        <Entry Placeholder="Serial no" VerticalOptions="Center" Text="Serial" FontSize="16" WidthRequest="100" MinimumWidthRequest="100" MaxLength="6" Keyboard="Text"/>
                        <Button Text="Add device" VerticalOptions="Center" FontSize="16" Padding="0" BorderWidth="0"/>
                    </FlexLayout>
```

**Comment by samhouts** [comment]
@maexsp  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by maexsp** [comment]
@samhouts  Repro project for UWP picker issue can be found here: https://github.com/maexsp/XamarinBase.git 
It also happens if no title is set at all. Also happens to Visual="Material" design.
This is a major bug in my opinion.

**Comment by bmacombe** [comment]
I've run across this myself and will investigate.  I did do a standard UWP project and see the same behavior so this isn't a forms bug, but a standard UWP combo box behavior.
