### ISSUE TITLE
[Enhancement] Performance Tips and Tricks

### ISSUE THREAD

**Issue by bcaceiro** [xamarin/Xamarin.Forms#6406]
## Summary
There should be an updated version of the Performance Tips and must do's in Xamarin Forms mobile applications. This is extremely important for developers. The Official Documentation (see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance) is from 2017, and I'm guessing, over these years, there may be new tips, or old ones deprecated.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
