### ISSUE TITLE
[Bug] [WPF] BoxView not correctly restored

### ISSUE THREAD

**Issue by ZeProgFactory** [xamarin/Xamarin.Forms#6408]
### Description
`BoxView` is not correctly restored after `Navigation.PushAsync(); … Navigation.PopAsync();` .   
    
This problem could be related to  #4788, but in the present case the results doesn't change weather you set `Color` or  `BackgroundColor`  .

### Steps to Reproduce
1.  Create a basic app with 2 pages.
2.  Main page with a `Grid` containing a `BoxView` and a `Button` on top.
3.  Navigate to second page.
4. Navigate back to the main page and the `BoxView` disappeared from the main page.

### Expected Behavior
Unchanged Main page (BoxView).
Animated GIF:  
![Expected](https://user-images.githubusercontent.com/17034030/58895945-543e7680-86f5-11e9-9331-b395d42947d5.gif)

### Actual Behavior
BoxView is missing on Main page.
Animated GIF:  
![Actuel](https://user-images.githubusercontent.com/17034030/58895957-5f91a200-86f5-11e9-996e-926ed09cd964.gif)

### Reproduction Link
[XF-Bug-WPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3253483/XF-Bug-WPF.zip)

**Comment by ChaseMarsh** [comment]
I ran into the same problem (WPF only). I discovered that UpdateNativeWidget (which calls UpdateSize) in the BoxViewRenderer does not get called when navigating back. This points to an issue at or upstream from ViewRenderer.Tracker (VisualElementTracker) most likely.

A quick fix is to copy the BoxViewRenderer into your project and put the UpdateSize call in OnElementChanged.
