### ISSUE TITLE
[Bug] Shell Flyout FlyoutItem Title Text Vanishes On Scroll [Android]

### ISSUE THREAD

**Issue by TheBaileyBrew** [xamarin/Xamarin.Forms#6410]
### Description
When I place multiple FlyoutItems in Shell, all text appears at first, but after scrolling some Flyouts offscreen and back onscreen the text partially vanishes (or truncates with a - ).

### Steps to Reproduce

1. Create Shell project on VS2019
2. Edit AppShell.XAML to include two unique DataTemplates in Shell.Resources
3. Create a DataTemplateSelector that checks for a variable to determine which of the FlyoutItems match a particular attribute (for example: Route.StartsWith("Flyout")) and then return a DataTemplate:

        public class NavigationFlyoutTemplateSelector : DataTemplateSelector
        {
            public DataTemplate NavigationHeaderTemplate { get; set; }
            public DataTemplate NavigationItemTemplate { get; set; }

            protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
            {
                return ((FlyoutItem)item).Route.StartsWith("Flyout") ? NavigationHeaderTemplate : NavigationItemTemplate;
            }
        }

4. Modify AppShell.XAML to set the DataTemplateSelector as the ItemTemplate:

        ItemTemplate="{StaticResource navigationFlyoutTemplateSelector}"

5. Modify AppShell.XAML's Shell.Resources to utilize the DataSelector:

        <controls:NavigationFlyoutTemplateSelector
                x:Key="navigationFlyoutTemplateSelector"
                NavigationHeaderTemplate="{StaticResource navigationHeaderTemplate}"
                NavigationItemTemplate="{StaticResource navigationItemTemplate}" />

6. In AppShell.CS build all FlyoutItems dynamically, some should have no Route, others should have a Route declared.

        internal class NavigationItem {
            public string Title { get; set; }
            public DataTemplate Template { get; set; }
            public string Route { get; set; }
        }

        //List with one item with NO ROUTE (This acts as the header)
        public List<NavigationItem> NavigationItemHeader { get; set; } = new List<NavigationItem>
        {
            new NavigationItem
            {
                Title = "Items"
            }
        };
        
        //List with several items with ROUTE (This acts as the clickable flyout items)
        public List<NavigationItem> NavigationItemList { get; set; } = new List<NavigationItem>
        {
            new NavigationItem{
                Title = "New Items",
                Route = "NEWITEMS",
                Template = new DataTemplate(typeof(ItemSearchPage))},
            new NavigationItem{
                Title = "Discontinued Items",
                Route = "DISCITEMS",
                Template = new DataTemplate(typeof(ItemSearchPage))},
            new NavigationItem{
                Title = "Outs",
                Route = "OUTS",
                Template = new DataTemplate(typeof(ItemSearchPage))},
         }

        public AppShell() {
            
            //Build Header
            NavigationItemHeader.Select(x => new FlyoutItem
            {
                Title = x.Title,

            }).ForEach(Items.Add);

            //Build Items Remaining
            NavigationItemList.Select(x => new FlyoutItem
            {
                Title = x.Title,
                Route = x.Route,
                Items =
                {
                    new ShellContent
                    {
                        Title = x.Title,
                        Route = x.Route,
                        ContentTemplate = x.Template
                    }
                }
            }).ForEach(Items.Add);

            //REPEAT Build Header and Builde Items Remaining  2 or 3 times to generate multiple headers and groupings

            //Disable Header Clickability to stop NULL crash
            foreach(var flyoutItem in Items)
            {
                if (flyoutItem.Route.ToString().StartsWithIgnoreCase("Flyout"))
                {
                    Debug.WriteLine("Flyout Menu to Disable is: " + flyoutItem.Title);
                    flyoutItem.IsEnabled = false;
                }
            }

### Expected Behavior
All text would remain complete upon scroll.

### Actual Behavior
Some text truncates, but not all - and as more scrolling happens, more text disappears from different Flyout items

### Basic Information

- Version with issue: Xamarin.Forms v 4.0.0.482894
- Last known good version: NA
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  NA
  - Android: PIe (API 28, Android 9.0) 
  - UWP:  NA 
- Android Support Library Version:  v28.0.0.1
- Nuget Packages:
- Affected Devices: All Android

### Screenshots
![Display_As_Expected_Initial_Creation](https://user-images.githubusercontent.com/35344621/58905921-da988f80-86d8-11e9-9972-19a10f33f762.jpg)
![Display_Text_Partially_Removed_On_Return_To_Top](https://user-images.githubusercontent.com/35344621/58905922-da988f80-86d8-11e9-850f-cf2df395dd39.jpg)
![Display_Text_Removed_On_First_Scroll_Down_And_Back](https://user-images.githubusercontent.com/35344621/58905923-da988f80-86d8-11e9-9240-759dbdb9454a.jpg)
![Display_Text_Removed_On_Scroll_To_Bottom](https://user-images.githubusercontent.com/35344621/58905924-db312600-86d8-11e9-8b13-6838ea10d4a4.jpg)

### Reproduction Link

...Willing to screen share with someone since code is proprietary and I can't share it publicly.

**Comment by samhouts** [comment]
@PureWeen This looks like the "cells" in that list are not getting remeasured. Can you confirm?

**Comment by jsuarezruiz** [comment]
I cannot reproduce it without using DataTemplateSelector. May be related.

**Comment by TheBaileyBrew** [comment]
@jsuarezruiz - I have been noticing a few other instances in code where I'm missing content in CollectionViews where I'm implementing other DataTempateSelectors --- so i think you're likely right on the money with your observation of that being the related issue.

**Comment by PureWeen** [comment]
@jsuarezruiz  @TheBaileyBrew 

I realize it's been a minute but do you have a reproduction by chance? I've been trying to make this happen locally and the titles are working for me

Are you still seeing this behavior on the latest releases of XF @TheBaileyBrew ?

**Comment by PureWeen** [comment]
Closing for now 

Recycling has been disabled for the flyout because it doesn't benefit from recycling and AFAICT it all works fine now give the use cases above
