### ISSUE TITLE
Sign in with Apple ID

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6430]
Hi,

With the new Sign in with Apple ID coming with iOS 13, I hope this will be added to Xamarin Forms as a separate XF Nuget Package to help using this feature

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by samhouts** [comment]
Part of #6483

As you say, I'm not sure that we would add this to Xamarin.Forms core. 

This is a great candidate for Xamarin.Auth and/or Xamarin.Essentials. /cc @Redth

**Comment by rmarinho** [comment]
This should just be added to Xamarin.Auth

**Comment by EmilAlipiev** [comment]
It makes no sense in xamarin.forms as it is google only. Also make no sense on xamarin.auth. not everyone is using xamarin.auth. it should be separate package like facebook or google logins and anyone wants to use xamarin.auth can integrate together easily. Xamarin.auth is a secure storage primarily has nothing to do with logins and use akavache instead

**Comment by Redth** [comment]
We are looking at our options here and seeing how it might fit into Xamarin.Essentials :)

**Comment by andreas-gabriel** [comment]
What do you think, when it will be implemented?

**Comment by Redth** [comment]
There's a complete sample up now: https://github.com/xamarin/xamarin-forms-samples/tree/master/SignInWithApple

This should show you how to use Apple Sign In with Xamarin.Forms.  

Going forward we are looking into approaches with Xamarin.Essentials to help make this easier, however for non-iOS13 platforms some server side logic is required to handle the authentication process properly, so there's no simple nuget package solution here.
