### ISSUE TITLE
[Bug] [WPF] Grid + ListView -> first row height not correct

### ISSUE THREAD

**Issue by ZeProgFactory** [xamarin/Xamarin.Forms#6436]
### Description
If you put a `ListView` in a `Grid` the first `RowHeight` is to small unless you specify a correct default value.

### Steps to Reproduce
```
   <Grid>
      <ListView ItemsSource="{Binding Items}" Margin="50" >
         <ListView.ItemTemplate>
            <DataTemplate>
               <ViewCell>
                  <Grid>
                     <Label HorizontalOptions="Center" Text="{Binding}" />
                  </Grid>
               </ViewCell>
            </DataTemplate>
         </ListView.ItemTemplate>
      </ListView>
   </Grid>
```

### Expected Behavior
![2019-06-06 (2)](https://user-images.githubusercontent.com/17034030/59047525-54b94780-8884-11e9-9fee-b611b6d625da.png)

### Actual Behavior
![2019-06-06 (1)](https://user-images.githubusercontent.com/17034030/59047468-3c492d00-8884-11e9-92fd-156a43be6487.png)

### Basic Information

- Version with issue:
- Last known good version: ?
- IDE: Microsoft Visual Studio Professional 2019 Version 16.1.2
- Nuget Packages: XF 4.0.0.482894

### Reproduction Link
[ViewCellSize.WPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3262448/ViewCellSize.WPF.zip)

**Comment by jdcarrillo** [comment]
> ### Description
> If you put a `ListView` in a `Grid` the first `RowHeight` is to small unless you specify a correct default value.
> 
> ### Steps to Reproduce
> ```
>    <Grid>
>       <ListView ItemsSource="{Binding Items}" Margin="50" >
>          <ListView.ItemTemplate>
>             <DataTemplate>
>                <ViewCell>
>                   <Grid>
>                      <Label HorizontalOptions="Center" Text="{Binding}" />
>                   </Grid>
>                </ViewCell>
>             </DataTemplate>
>          </ListView.ItemTemplate>
>       </ListView>
>    </Grid>
> ```
> 
> ### Expected Behavior
> ![2019-06-06 (2)](https://user-images.githubusercontent.com/17034030/59047525-54b94780-8884-11e9-9fee-b611b6d625da.png)
> 
> ### Actual Behavior
> ![2019-06-06 (1)](https://user-images.githubusercontent.com/17034030/59047468-3c492d00-8884-11e9-92fd-156a43be6487.png)
> 
> ### Basic Information
> * Version with issue:
> * Last known good version: ?
> * IDE: Microsoft Visual Studio Professional 2019 Version 16.1.2
> * Nuget Packages: XF 4.0.0.482894
> 
> ### Reproduction Link
> [ViewCellSize.WPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3262448/ViewCellSize.WPF.zip)

It is not displaying the information in the list correctly. Version: 4.0.0.482894 (latest stable)
![image](https://user-images.githubusercontent.com/5039921/59061348-edda6500-8868-11e9-984f-8dd3f356e044.png)

**Comment by jdcarrillo** [comment]
It is not displaying the information in the list correctly. Version: 4.0.0.482894 (latest stable)
![image](https://user-images.githubusercontent.com/5039921/59061461-34c85a80-8869-11e9-879a-a5e89fd6fc16.png)

**Comment by JoseluDAM2000** [comment]
Looks like a similar bug is happening to me often on [`p/iOS 🍎`](https://github.com/xamarin/Xamarin.Forms/labels/p%2FiOS%20%F0%9F%8D%8E) and some times on [`p/Android`](https://github.com/xamarin/Xamarin.Forms/labels/p%2FAndroid)

**Comment by JoseluDAM2000** [comment]
Here is an example of the error in iOS.

![imagen](https://user-images.githubusercontent.com/22506382/60507639-e91e9a80-9cc8-11e9-9c8b-d066ddadd7fa.png)

**Comment by JoseluDAM2000** [comment]
Some kind of similar behavior happens to me on a stack layout too. #6770

**Comment by cmarqueztecnosylva** [comment]
Hi.

After update to Xamarin 4, i have the same problem with my app, empty space on the list. 
Someone know when Microsoft will fix this bug??? because i have a big problem with my client, and return to the 3.5 version is a big problem for me now.

Thanks for your responses.

**Comment by yashyn** [comment]
There is another strange behavior similar to the issue.

Layout is the same:
ListView -> Grid -> Label 

When Label has too long value for Grid cell it wraps but ListView row height doesn't change to fit wrapped value. So wrapped value seemed truncated
