### ISSUE TITLE
[Enhancement] Give the possibility to choose how many tabs should be displayed in the Xamarin.Shell tabbar 

### ISSUE THREAD

**Issue by effpath999** [xamarin/Xamarin.Forms#6438]
## Summary
Actually, the tabbar in Xamarin.Shell displays up to five tabs before resorting to the More menu.
I think five tabs are quite a lot, especially considering that the tabbar isn't optimized to show only icons (if you omit the text, the icons are aligned at the top and some empty space remains at the bottom): five string of text could make the tabbar very crowded, especially in some languages.

## API Changes
I think the developer should be able to choose how many tabs have to been visible in the tabbar, leaving the other for the "More" menu.
Something like the Order property of the ToolbarItems could be used, to indicate if a tab should be displayed directly in the tabbar or in the menu.

## Intended Use Case
If you have five tabs with relatively long description the tabbar becomes very crowded. The proposed change would make the tabbar more aesthetically pleasant and more clear to the user.

**Comment by rscholey** [comment]
+1

**Comment by chriswitt2** [comment]
+1

**Comment by jfversluis** [comment]
Hey everyone! Thanks for this suggestion! This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
