### ISSUE TITLE
[Enhancement] Add IsVisible to MenuItem

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#6440]
## Summary

It should be possible to make MenuItems invisible if necessary, by providing a public IsVisible bindable property.

## API Changes

Add an IsVisible property to MenulItem. When set to true, the item is displayed in ContextActions, and when set to false it is hidden. The property should be bindable.

## Intended Use Case

Items in a ListView may differ from each other and may wish to present different context actions to the user.

**Comment by Raystorm7** [comment]
Hi,
any news on this?

The `IsVisible` for `FlyoutItem` was added but not for `MenuItem`.

In our application we have multiple menus composed of `FlyoutItem` and `MenuItem` but we can't hide the `MenuItem` because of the missing bindable property.

Thank you.

**Comment by GeorgeVelikov** [comment]
We are on the same boat as @Raystorm7. Any update on this?

**Comment by DonaldArcher** [comment]
Had the same issue, here is my solution. I created a style, and set that to hidden. Then I update my MenuItem in the backend, depending what is needed.

Style
`<Style
            ApplyToDerivedTypes="True"
            Class="MenuItemLayoutStyleHidden"
            TargetType="Layout">
            <Setter Property="IsVisible" Value="False" />
        </Style>`

Menu Item
`<MenuItem
    x:Name="btnLogout"
    Clicked="btnLogoutClick"
    IconImageSource="icon_about.png"
    StyleClass="MenuItemLayoutStyle"
    Text="Logout" />`

Backend Code
`
if (user.isLoggedIn) 
        {
            btnLogout.@class.Clear();
            btnLogout.@class.Add("MenuItemLayoutStyle");
        }
        else
        {
            btnLogout.@class.Clear();
            btnLogout.@class.Add("MenuItemLayoutStyleHidden");
        }
`

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by npostma** [comment]
I am having this 'issue' also. Wanted it to use it for a workarround. Because a FlyOutItem with IsEnbled="False" does not react to
```
<VisualState x:Name="Disabled">
     <VisualState.Setters>
         <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackground}" />
         <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource SecondaryFaintedText}" />
     </VisualState.Setters>
</VisualState>
 ```
                            
So i wanted to swap menu items (With disabled style and no action) for a flyout item.
