### ISSUE TITLE
Issue on Navigating back Master Details Page in Xamarin forms MVVM prism using unity

### ISSUE THREAD

**Issue by sahadevgupta** [xamarin/Xamarin.Forms#6441]
Hi, I've attached a small project in which I'm currently facing the issue.
I've one Page it navigates to MasterDetail Page. MasterDetail Consist a Page1 in detail , there is one button which navigates to page2. Now when I navigate back then it navigates to Page1 but the MasterDetail Page is not available now..

### Expected Behavior
On navigating back the page should be within masterdetail page.

### Actual Behavior
On navigating back the page is not  within masterdetail page.

### Basic Information

- Version with issue: 3.6.0.220655

[MasterDetail_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/3264530/MasterDetail_Issue.zip)

**Comment by samhouts** [comment]
@sahadevgupta Do you see the same issue on Android or iOS? Thanks!

**Comment by sahadevgupta** [comment]
@samhouts I haven't tested for Android and iOS. So don't know whether this issues occurs there or not.
But I've got the workaround for this issue in UWP.

The problem was with the title property of masterdetail page. If I set the title of master detail page
then everything works fine..

Hope this workaround would help to overcome this problem. :)

**Comment by rmarinho** [comment]
Hi, can you try to reproduce this issue without using the Prism Library?

**Comment by samhouts** [comment]
@sahadevgupta  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
