### ISSUE TITLE
[Bug] ListView has broken layout

### ISSUE THREAD

**Issue by td1311** [xamarin/Xamarin.Forms#6442]
### Description
On iOS: ListViews with complex layout has broken layout and missing text
### Steps to Reproduce

1. Create ListView with complex layout
2. Change data in ListView
3. Items in ListView has agliment error
4. Change data in ListView again
5. ListView's Items has missing text
6. Scroll ListView
7. ListView's Items display correctly

### Expected Behavior
The ListView display correctly
### Actual Behavior
It doesn't
### Basic Information

- Version with issue: Xamarin Forms 3.6.0.344457
- Last known good version:
- IDE: Visual Studio 2017(15.9.4)
- Platform Target Frameworks: 
  - iOS:  12.2

### Screenshots

![ezgif-2-02f560780c3f](https://user-images.githubusercontent.com/41880710/59092660-55adb000-893c-11e9-8d9a-d09c3973f9ae.gif)

### Reproduction Link

[ListViewBug20190607.zip](https://github.com/xamarin/Xamarin.Forms/files/3265211/ListViewBug20190607.zip)

**Comment by samhouts** [comment]
@td1311 Set your `CachingStrategy` to `RecycleElement`. Thanks!
