### ISSUE TITLE
[Bug] [Shell] ShellContent.BindingContext not inherited

### ISSUE THREAD

**Issue by ArgusMagnus** [xamarin/Xamarin.Forms#6444]
### Description

The BindingContext for `ShellContent` objects are not inherited from the `Page`/`ShellSection`.

### Steps to Reproduce

MainPage with `BindingContext = new MainVM();` and Layout like:

    
    <TabBar>
        <Tab Icon="{bmex:Icon home}">
            <ShellContent Title="{Binding Page1VM.Title}">
                <ShellContent.ContentTemplate>
                    <DataTemplate>
                        <local:Page1 BindingContext="{Binding Page1VM}"/>
                    </DataTemplate>
                </ShellContent.ContentTemplate>
            </ShellContent>
        </Tab>
    </TabBar>

	[Preserve(AllMembers = true)]
	sealed class MainVM : NotifyPropertyChanged, IViewModel
	{
		public Page1VM Page1VM { get; } = new Page1VM();
	}

    
    <ContentPage.Content>
        <StackLayout>
            <Label Text="{Binding Text}" />
            <Label Text="abasdfsdf"/>
        </StackLayout>
    </ContentPage.Content>

	[Preserve(AllMembers = true)]
	sealed class Page1VM : NotifyPropertyChanged
	{
		public string Title => "Page1 Title";
		public Command TestCommand { get; }
		public IEnumerable<string> Items { get; } = Enumerable.Range(1, 100).Select(x => $"Item {x}");

		public Page1VM()
		{
			TestCommand = new Command(Test);
		}

		void Test()
		{
			System.Diagnostics.Debug.WriteLine("Page1VM.TestCommand executed");
		}
	}

### Expected Behavior

The BindingContext is inherited from the parent element (`ShellSection`).

### Actual Behavior

The BindingContext is `null`.

### Basic Information

- Version with issue: XF 4.0.0.482894
- Last known good version:
- IDE: VS 2019 (16.1.2) Windows
- Platform Target Frameworks:
  - iOS:  11.3
  - Android: 9
- Affected Devices: Samsung S6, iPhone 6s

**Comment by samhouts** [comment]
@ArgusMagnus  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ArgusMagnus** [comment]
@samhouts https://1drv.ms/u/s!AnmEVu7lvXuCbuanbmb-hYSPq1A?e=nJn6cS

**Comment by Dresel** [comment]
Is this up for grabs or is already someone working on it?

I would propose a similar approach like [Grid](https://github.com/xamarin/Xamarin.Forms/blob/210df5f775b2aa682b2c823f1d854d8290e46e27/Xamarin.Forms.Core/Grid.cs#L257).

In Shell, when modifying [Items](https://github.com/xamarin/Xamarin.Forms/blob/adc1f5e064db9bc978e0fbc99ae22b99d7785e4f/Xamarin.Forms.Core/Shell/Shell.cs#L580) or setting the [BindingContext](https://github.com/xamarin/Xamarin.Forms/blob/adc1f5e064db9bc978e0fbc99ae22b99d7785e4f/Xamarin.Forms.Core/Shell/Shell.cs#L691) call `SetInheritedBindingContext` for all `Shell.Items`.

`ShellItems` should call `SetInheritedBindingContext` on `BindingContext` changes for `ShellSections`, `ShellSections` should do the same for `ShellContents` and `ShellContent` should set the BindingContext for pages.

Anything I forgot? I would go for a PR if it's not already in progress by someone else.

**Comment by samhouts** [comment]
closed by #6730
