### ISSUE TITLE
Binding Selected record to Picker

### ISSUE THREAD

**Issue by arvindrajachourasiya** [xamarin/Xamarin.Forms#6445]
### Description

On ViewModel loading I am binding default record to Picker. When initializing Picker using `new `keyword Picker selection isn't working

```
public override void OnNavigatedTo(INavigationParameters parameters)
{
	base.OnNavigatedTo(parameters);
	var objL = parameters.GetValue<LeaveManagement>("LeaveItem");
	SelectedLeaveType = new SpinnerBind { Value = objL.LeaveTypeId, Name = objL.LeaveTypeCD };
	//SelectedLeaveType = LeaveType.Where(i => i.Value == objL.LeaveTypeId).FirstOrDefault();           
}
```
But when getting selected `SelectedLeaveType `from Source data it is working See code below. Why so?

```
public override void OnNavigatedTo(INavigationParameters parameters)
{
	base.OnNavigatedTo(parameters);
	var objL = parameters.GetValue<LeaveManagement>("LeaveItem");	
	SelectedLeaveType = LeaveType.Where(i => i.Value == objL.LeaveTypeId).FirstOrDefault();           
}
```

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@arvindrajachourasiya  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@arvindrajachourasiya  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
