### ISSUE TITLE
[Bug] [CollectionView] ListItemsLayout throw TypeInitializerException

### ISSUE THREAD

**Issue by ArgusMagnus** [xamarin/Xamarin.Forms#6446]
### Description

Using the `CollectionView` with `ListItemsLayout.VerticalList` like documented [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout) throws a `TypeInitializerException` for `ListItemsLayout`.

### Steps to Reproduce

Create a minimal Xamarin.Forms application

    
    <ContentPage.Content>
        <CollectionView ItemsSource="{Binding Items}" ItemsLayout="{x:Static ListItemsLayout.VerticalList}" />
    </ContentPage.Content>

### Basic Information

- Version with issue: XF 4.0.0.482894
- Last known good version:
- IDE: VS 2019 (16.1.2) Windows
- Platform Target Frameworks:
  - iOS:  11.3
  - Android: 9
- Affected Devices: Samsung S6, iPhone 6s

**Comment by ArgusMagnus** [comment]
If I remove the `ItemsLayout` assignment (and thus use the default) I get: `System.TypeInitializationException: The type initializer for 'Xamarin.Forms.ItemsView' threw an exception`

**Comment by samhouts** [comment]
Thanks you for the report.

CollectionView is available in Xamarin.Forms 4.0. However, it is currently experimental and can only be used by adding the following line of code to your AppDelegate class on iOS, or to your MainActivity class on Android, before calling Forms.Init:

``` csharp
Forms.SetFlags("CollectionView_Experimental");
```

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction
