### ISSUE TITLE
[Bug] Navigation slow when using FormsAppCompatActivity and/or XF 4.0

### ISSUE THREAD

**Issue by pauldiston** [xamarin/Xamarin.Forms#6448]
### Description
Inside our application we navigate to a TabbedPage which works very well on XF 3.6 using FormsApplicationActivity. As I would like to upgrade to XF 4.0, I have had to switch over to use FormsAppCompatActivity due to issues with Toolbar Item Images not displaying. I then notice a navigation to a TabbedPage is now not very smooth, with the page title changing and after a second or so the page content shows. With XF 3.6 and FormsApplicationActivity, the whole page appears after a second or so with everything intact.

### Steps to Reproduce

1. Change our application to use FormsAppCompatActivity and/or XF 4.0
2. Experience issues

### Expected Behavior
Smooth navigation

### Actual Behavior
Not smooth navigation

### Basic Information

- Version with issue: 4.0 with FormsAppCompatActivity 
- Last known good version: 3.6 with FormsApplicationActivity
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 9.1.7.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Samsung S8

**Comment by pauldiston** [comment]
This seems to be an issue with the use of FormsAppCompatActivity and not to do with the version of XF.

Why are there issues with using FormsAppCompatActivity such as the OnOptionsItemSelected method no longer firing and then inconjunction with XF 4.0, an issue with displaying toolbar item images?

**Comment by samhouts** [comment]
@pauldiston  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@pauldiston  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by pauldiston** [comment]
@samhouts Having put off the switch from FormsApplicationActivity to FormsAppCompatActivity due to this issue and others (Toolbar Item issues, etc), hence the 30 days inactivity this has now come about again and has been reported by our test team. Also, as I put off the switch I wasn't tracking this issue as closely as I should of and am only now seeing the request for additional information. As this is happening in our 6 year old Xamarin Forms application which was working much better using FormsApplicationActivity than it is now using FormsAppCompatActivity, how can it be recommended that I use FormsAppCompatActivity when it has caused so many issues and has degraded the quality of our application.

**Comment by pauldiston** [comment]
@samhouts I wonder whether some of the issues surrounding this issue (https://github.com/xamarin/Xamarin.Forms/issues/2562) might be causing my navigation slow issue.

It does seem quite slow to set the MainPage, although things aren't as bad as issue 2562 where a blank screen is shown, the slowness after setting the MainPage is noticeable, hence my original issue.

**Comment by samhouts** [comment]
@pauldiston Any chance you have a reproduction project you can share now? Thanks!

**Comment by pauldiston** [comment]
@samhouts I am struggling to reproduce this in a test project however I have come up with a possible workaround by deferring the creation of my pages main UI until after the base.OnAppearing event has fired which allows for the Page title to be shown and then the main UI a few milliseconds afterwards. This gives the impression that there isn't a slow down in the rendering of the page. I don't know if this approach might give some clue to whether the loading of mildly complex UI has a possible issue or whether page creation works differently between FormsApplicationActivity and FormsAppCompatActivity. Again this is related to setting the MainPage of the application and is not seen when navigating in the usual way.

**Comment by samhouts** [comment]
@pauldiston Are you doing anything else in the OnAppearing? How complex is the MainPage? Is it loading data or just rendering elements?

**Comment by samhouts** [comment]
@pauldiston Any update on this? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
