### ISSUE TITLE
[Shell] Unable to capture "Cancel" event of Search Handler 

### ISSUE THREAD

**Issue by aherrick** [xamarin/Xamarin.Forms#6449]
Using Shell I'm programatically showing my Search Handler when tapping a Nav Bar icon. I'm also setting focus so it instantly becomes searchable. That's working great.

```
                var search = Shell.GetSearchHandler(this);

                if (search.SearchBoxVisibility == SearchBoxVisibility.Expanded)
                {
                    search.SearchBoxVisibility = SearchBoxVisibility.Hidden;
                }
                else
                {
                    search.SearchBoxVisibility = SearchBoxVisibility.Expanded;
                    search.Focus();
                }
```

What I need is a way to capture when "Cancel" is tapped so I can then programatically hide the search bar. Something like:

```
     protected override void OnCancelButtonClicked()
            {
            }
```

Is there not a way to do this?

**Comment by samhouts** [comment]
@aherrick It looks like that's something we should add. Thanks!

**Comment by aherrick** [comment]
FYI this is the effect I'm going for. Tapping the "Filter" icon in the top Nav produces the search/filter box. Pressing "Cancel" removes the box. Video below :)

https://streamable.com/dv6zk

**Comment by aherrick** [comment]
hi @samhouts! any updates here or is there another way (via render perhaps) that I could accomplish this? Thanks!

**Comment by aherrick** [comment]
Hi all! Looking for any kind of update here? Could a work around be accomplished?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
