### ISSUE TITLE
[Bug] XAML Parsing Issues if the root namespace is not `http://xamarin.com/schemas/2014/forms`

### ISSUE THREAD

**Issue by legistek** [xamarin/Xamarin.Forms#6452]
### Description

`DataTemplate` and `ControlTemplate` are not recognized as templates unless the root XML namespace is `http://xamarin.com/schemas/2014/forms`

### Steps to Reproduce

```
<?xml version="1.0" encoding="utf-8" ?>
<xf:ContentPage xmlns="anything"
                xmlns:xf="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.Core"
                xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                x:Class="TestApp.Page1">
    <xf:ContentPage.Content>
        <xf:StackLayout>
            <xf:ListView>
                <xf:ListView.ItemTemplate>
                    <xf:DataTemplate>
                        <xf:Label Text="Templated label"/>
                    </xf:DataTemplate>
                </xf:ListView.ItemTemplate>
            </xf:ListView>
        </xf:StackLayout>
    </xf:ContentPage.Content>
</xf:ContentPage>
```

### Expected Behavior
The `xf:DataTemplate` node should parse correctly and be recognized as a template.

### Actual Behavior

The parser doesn't recognize the `xf:DataTemplate` node as an actual template and tries to assign it direct content, thus it won't compile. 

### Basic Information

- Version with issue: Latest
- Last known good version: N/A
- IDE: VS2017
- Platform Target Frameworks: All
- Android Support Library Version: N/A
- Nuget Packages: Latest
- Affected Devices: All

### Other Info

See `XamlParser.cs` line 106 which looks for the hard-coded strings `DataTemplate` or `ControlTemplate` and also requires the root ns to be `http://xamarin.com/schemas/2014/forms`. If it finds these it sets a `CreateContent` property on the node. Everything else looks for this `CreateContent` property on the node to determine whether to treat it as a template or actual content.

I am willing to attempt a fix if it would be accepted. Thanks!

Update-
Intellisense isssues noted lower in the thread.
Also note this affects `Style`s and `Trigger`s and markup extensions. The fix will address all of these.

**Comment by samhouts** [comment]
@legistek Thanks for the report! We'd be happy to accept a PR fixing this!

**Comment by legistek** [comment]
Great, I'll give it a shot.
I presume that the behavior we want is that anything should be handled as a template if it resolves to class derived from `Xamarin.Forms.ElementTemplate' - regardless whether that's via the default ns or a prefix.

**Comment by legistek** [comment]
Almost have this fixed but one thing is stumping me: Intellisense.
If the main ns isn't `http://xamarin.com/schemas/2014/forms` Intellisense goes haywire. I can't for the life of me figure out why. I searched for all references to that URL as well as the `XFUri` constant and can't figure out why that would impact Intellisense. Any ideas? Is that just hard coded into Visual Studio maybe?

**Comment by StephaneDelcroix** [comment]
> Almost have this fixed
Great. Waiting for the PR.

> but one thing is stumping me: Intellisense
/cc @mgoertz-msft: are we aware of any intelisense issue if the default xmlns is not XF ?

**Comment by legistek** [comment]
[NSTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3286352/NSTest.zip)

Here are some more specific and reproducible examples (all this is being done from the release version of XF from Nuget):

In one project (`ControlLib`) I have `CustomLabel.cs`:

```
using Xamarin.Forms;

[assembly: XmlnsDefinition("http://customxaml.com", "ControlLib")]
[assembly: XmlnsDefinition("http://customxaml.com", "Xamarin.Forms", AssemblyName = "Xamarin.Forms.Core")]
[assembly: XmlnsDefinition("http://customxaml.com", "Xamarin.Forms.Xaml", AssemblyName = "Xamarin.Forms.Xaml")]
[assembly: XmlnsDefinition("http://xamarin.com/schemas/2014/forms", "ControlLib")]

namespace ControlLib
{
	public class CustomLabel : Label
	{
	}

	public class Library
	{
		public static void Init()
		{
		}
	}
}
```

Then in a second project, two `ContentPage`s:

**Main Page**
```
<xfurl:ContentPage xmlns="http://customxaml.com"
                   xmlns:ccurl="http://customxaml.com"
                   xmlns:ccclr="clr-namespace:ControlLib;assembly=ControlLib"
                   xmlns:xfurl="http://xamarin.com/schemas/2014/forms"
                   xmlns:xfclr="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.Core"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:d="http://xamarin.com/schemas/2014/forms/design"
                   xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                   mc:Ignorable="d"
                   x:Class="XamarinTest.MainPage">
    <xfurl:StackLayout>                     <!-- (1) Intellisense sees -->
        <Label Text="Hmm"/>                 <!-- (2) Intellisense doesn't see -->
        <CustomLabel Text="Ugh"/>           <!-- (3) Intellisense doesn't see -->
        <ccurl:CustomLabel Text="Foo"/>     <!-- (4) Intellisense doesn't see -->
        <ccclr:CustomLabel Text="Bar"/>     <!-- (5) Intellisense sees -->
        <ccurl:Label Text="Yay"/>           <!-- (6) Intellisense doesn't see -->
        <xfclr:Label x:Name="_label"        
                     Text="Welcome to Xamarin.Forms!" 
                     HorizontalOptions="Center"
                     VerticalOptions="CenterAndExpand" />  <!-- (7) Intellisense sees -->        
    </xfurl:StackLayout>
</xfurl:ContentPage>
```

**Second Page**
```
<?xml version="1.0" encoding="utf-8" ?>
<xfurl:ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                   xmlns:ccurl="http://customxaml.com"
                   xmlns:ccclr="clr-namespace:ControlLib;assembly=ControlLib"
                   xmlns:xfurl="http://xamarin.com/schemas/2014/forms"
                   xmlns:xfclr="clr-namespace:Xamarin.Forms;assembly=Xamarin.Forms.Core"
                   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                   xmlns:d="http://xamarin.com/schemas/2014/forms/design"
                   xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
                   mc:Ignorable="d"
                   x:Class="XamarinTest.SecondPage">
    <xfurl:StackLayout>                     <!-- (1) Intellisense sees -->
        <Label Text="Hmm"/>                 <!-- (2) Intellisense sees -->
        <CustomLabel Text="Ugh"/>           <!-- (3) Intellisense sees -->
        <ccurl:CustomLabel Text="Foo"/>     <!-- (4) Intellisense sees -->
        <ccclr:CustomLabel Text="Bar"/>     <!-- (5) Intellisense sees -->
        <ccurl:Label Text="Yay"/>           <!-- (6) Intellisense doesn't see -->
        <xfclr:Label x:Name="_label"        
                     Text="Welcome to Xamarin.Forms!" 
                     HorizontalOptions="Center"
                     VerticalOptions="CenterAndExpand" />  <!-- (7) Intellisense sees -->        
    </xfurl:StackLayout>
</xfurl:ContentPage>
```

Both compile and run perfectly fine but as you can see neither is handled quite correctly by Intellisense. Notable issues:
- In `MainPage` (1) is fine, but (4) is not. So the XFUrl is definitely getting special treatment still even despite not being the main NS. However, in `SecondPage` where the XFUrl is the main NS, other URLs (such as (4)) are fine. So not only does XFUrl get special treatment but its presence as the main NS is somehow required for any other URL NS's to be recognized by Intellisense.
- In `SecondPage`, the line `xmlns:d="http://xamarin.com/schemas/2014/forms/design"` is lit up as recognized by Intellisense. In `MainPage` it's lightened out. Odd because I have no design-mode properties in these examples Unsure if this is relevant.
- In neither case does (6) get recognized by Intellisense. Note I included `Xamarin.Forms` in my `XmlnsDefinitionAttribute` for `http://customxaml.com`, so it should work and indeed compiles and runs fine. 
- The CLR-namespaces are always fine in both examples. This only seems to affect URL-based namespaces.

I looked for references to `XFUri` throughout the solution and I've ruled out all but a couple of instances that could be causing this:
- `Xamarin.Forms.Xaml.RemoveDuplicateDesignNodes` - `public void Visit(ElementNode node, INode parentNode)` - uses `XFUri` and `XFDesignUri` to handle design-mode properties. Not sure why that would affect this though because I'm not using any design-mode properties in these examples. But it could be related to the second bullet above?
- `Xamarin.Forms.Xaml.Design.AttributeTableBuilder` - `public AttributeTableBuilder()` - this looks like it is for the XAML designer / preview but unsure if this has anything to do with Intellisense.
- `Xamarin.Forms.Core.Design.AttributeTableBuilder` - `public AttributeTableBuilder ()` - same.

I'm afraid I don't know much about how Intellisense is parsing editor content. For instance is it using the same `Xamarin.Forms.Xaml` assembly that the project is linked to or is there a separate assembly somewhere used by Visual Studio that is not necessarily updated when XF itself or uses an entirely different XAML parser? Bottom line - if XamlC, XamlG, and the runtime parser are all fine with this markup, why wouldn't Intellisense be?

**Comment by legistek** [comment]
[NStest2.zip](https://github.com/xamarin/Xamarin.Forms/files/3286707/NStest2.zip)

One more quick update. Just for kicks I tried seeing what Intellisense would do if XF wasn't even added to the project at all. I even defined an `Xamarin.Forms.XmlnsDefinitionAttribute` and `Xamarin.Forms.ContentPropertyAttribute` from scratch in a separate project. 

```
using System;
using Library;
using Xamarin.Forms;

[assembly: XmlnsDefinition("http://library", "Library")]

namespace Xamarin.Forms
{
	public sealed class ContentPropertyAttribute : Attribute
	{
		public ContentPropertyAttribute()
		{
		}

		public ContentPropertyAttribute(string name)
		{
			this.Name = name;
		}

		public string Name { get; set; }
	}

	[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
	public sealed class XmlnsDefinitionAttribute : Attribute
	{
		public string XmlNamespace { get; }
		public string ClrNamespace { get; }
		public string AssemblyName { get; set; }

		public XmlnsDefinitionAttribute(string xmlNamespace, string clrNamespace)
		{
			ClrNamespace = clrNamespace ?? throw new ArgumentNullException(nameof(xmlNamespace));
			XmlNamespace = xmlNamespace ?? throw new ArgumentNullException(nameof(clrNamespace));
		}
	}
}

namespace Library
{
	[ContentProperty(nameof(Content))]
	public class MyControl
	{
		public object Content { get; set; }

		public string Name { get; set; }
	}

	public class Library
	{
		public static void Init()
		{
		}
	}		
}
```

The XAML in the other project:
```
<ccurl:MyControl    xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:ccurl="http://library"
                    xmlns:clr="clr-namespace:System;assembly=netstandard"
                    xmlns:cc="clr-namespace:Library;assembly=Library"
                    Name="Me">
    <clr:String>Hello!</clr:String>
</ccurl:MyControl>
```

Intellisense is perfectly happy with it. But if I get rid of `xmlns="http://xamarin.com/schemas/2014/forms"` then it doesn't like it.

Since my project is not actually referencing XF, this must be in a VSIX or part of Visual Studio and it must be looking specifically for `xmlns="http://xamarin.com/schemas/2014/forms` to trigger special behavior.

Fixing this may be outside the scope of this repository. Is the XF Intellisense extension (assuming that's what it is) even open sourced?

**Comment by legistek** [comment]
Except for Intellisense - which I'm all but certain is out of my hands - I have this all working in [my branch](https://github.com/legistek/Xamarin.Forms/tree/gh6452-template-xaml-parsing). Not just for `DataTemplate` and `ControlTemplate` but also for triggers, styles, and a bunch of other things that were checking for Xfuri during parsing. I can PR now and worry about Intellisense later - what do you think?

**Comment by mgoertz-msft** [comment]
@legistek As you noticed, the default namespace is what drives the IntelliSense engine's choice of what platform it is dealing with (Xamarin Forms vs. WPF or UWP). We have built support for these three platforms and the behavior can be quite different for each platform.

If you remove the XF default namespace then we no longer know that we should choose the XF platform for this XAML file and fallback to a very basic default platform, which provides only extremely limited IntelliSense support.

BTW, try using the System.Windows.Markup.ContentPropertyAttribute from System.Xaml instead of rolling your own because that's the only one we respect at this point.

**Comment by legistek** [comment]
Hi @mgoertz-msft - interesting! Thanks for that explanation. Surprisingly, though, Intellisense is perfectly happy without the WPF URI and only a `clr-namespace` reference to `PresentationFramework`. The following presents no problems:

```
<wpf:UserControl x:Class="TestApp.WPF.UserControl1"
             xmlns:wpf="clr-namespace:System.Windows.Controls;assembly=PresentationFramework"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <wpf:Grid>
        <wpf:Button />
    </wpf:Grid>
</wpf:UserControl>
```

**Comment by mgoertz-msft** [comment]
Well, it's a little more complicated than I explained. For WPF and UWP we actually get the information through the project system but Xamarin Forms can be used in a variety of project systems. To make matters worse, with shared projects it can even appear in a UWP project so we needed a way to distinguish UWP XAML from XF XAML. And that's why we chose the default namespace to identify XF XAML files.

I hope that explains it a little better.

**Comment by legistek** [comment]
Aha, yes I figured there was something else going on. :) All makes sense.

So bottom line is I can (almost entirely) eliminate hard-coded dependence on Xfuri when it comes to XAML parsing and compilation, and I can PR that right now. Intellisense will have to be left for another time.

**Comment by legistek** [comment]
Just going through some old items here and re-remembered this.

I did wind up coding a branch that fixes the root problem, but since it completely breaks Intellisense (which basically makes writing XAML next-to-impossible), which is not something we can really fix, I don't know if it's worth PRing since it's a pretty large [changeset](https://github.com/xamarin/Xamarin.Forms/compare/master...legistek:gh6452-template-xaml-parsing). Any opinions?

**Comment by StephaneDelcroix** [comment]
I'm working on a branch that will eventually fixes this

**Comment by legistek** [comment]
Oh, cool. Well feel free to take anything I did in [this branch](https://github.com/xamarin/Xamarin.Forms/compare/master...legistek:gh6452-template-xaml-parsing) if it might be useful. Like I said I got it working with arbitrary Url's, just no Intellisense.

**Comment by legistek** [comment]
Hi @StephaneDelcroix wondering if you ever wound up fixing this like you mentioned. 

I gave up on this once it was clear that even if it were fixed it would break Intellisense, But with MAUI I thought it might be worth revisiting since everything appears to be on the table.

**Comment by jfversluis** [comment]
As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
