### ISSUE TITLE
XAML Previewer not properly rendering RelativeLayout

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6456]
VSF_TYPE_MARKDOWNThe XamlSamples has a RelativeLayout sample that runs fine on emulator, but doesn't render properly in the Previewer.

https://developer.xamarin.com/samples/xamarin-forms/XamlSamples/

And different devices in the dropdown show differing results.

See images attached.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/444898/xaml-previewer-not-properly-rendering-relativelayo.html
VSTS ticketId: 785635_
_These are the original issue comments:_

Visual Studio Feedback System on 2/22/2019, 07:56 AM (105 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

Visual Studio Feedback System on 2/22/2019, 08:02 AM (105 days ago): <p>A fix for this issue has been internally implemented and is being prepared for release. We'll update you once it becomes available for download.</p>

Visual Studio Feedback System on 6/4/2019, 10:06 PM (2 days ago): <p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
@davidortinau Good news! This seems to work now (VS 2019 16.2.0 Preview 1).
