### ISSUE TITLE
[Bug] [Android] SetTitleIcon does not display the icon in the title bar

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#6458]
### Description
With Forms 3.6.0, using NavigationPage.SetTitleIcon would display that drawable in the title bar.  with forms 4.0.0, the drawable is not displayed, instead the icon.png is

### Steps to Reproduce

1. Run the attached project.  Note the image in the title bar
2. Install Forms 4.0.0
3. Run the project again.  Note the image is not visible, the Xamarin icon is.
4. Changing the code from  SetTitleIcon to SetTitleIconImageSource in TargetedMessagePage.xaml.cs has no effect.

### Expected Behavior
4.0 should display the same image that 3.6 displayed

### Actual Behavior
The image is not displayed

### Basic Information

- Version with issue: 4.0.0
- Last known good version: 3.6
- IDE: VS 2017 & VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Android 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
Version 3.6.0:
![TitleImage](https://user-images.githubusercontent.com/1641428/59128520-4462a480-8938-11e9-9c2e-aa6c981639cd.png)

Version 4.0.0:
![NoTitleImage](https://user-images.githubusercontent.com/1641428/59128327-c0a8b800-8937-11e9-843e-8c99a0dc2f35.png)

### Reproduction Link
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3267316/HeaderTest.zip)

**Comment by rmarinho** [comment]
@ceblanda any special reason why you can't use AppCompact ? Seems the error doesn't happen on `FormsAppCompatActivity`

**Comment by ceblanda** [comment]
Yes, https://github.com/xamarin/Xamarin.Forms/issues/2577 & https://github.com/xamarin/Xamarin.Forms/issues/6307, also . TitleView images aren't resizing to fit the container. If I give them a width or height request they will, but just defining the container and setting the aspect doesn't.

**Comment by samhouts** [comment]
closed by #6437
