### ISSUE TITLE
[Bug] Incorrect exception message

### ISSUE THREAD

**Issue by mattleibow** [xamarin/Xamarin.Forms#6464]
### Description

An incorrect exception message is provided when a control's event handler does not exist in the code behind when skipping xaml compilation.

### Steps to Reproduce

1. Create a new Xamarin.Forms app
2. Create a custom control with an event in a new assembly
3. Use that custom control in XAML without XAML Compilation, but don't add the handler
4. Observe a correct `XamlParseException`, but the message says the type is not found at runtime
5a. Implement the event hander method - all is well
5b. Enable XAML Compilation - observe correct compiler error

### Expected Behavior
The runtime exception should say the event handler is not found.

### Actual Behavior
The runtime throws an exception saying the whole type is missing.

### Basic Information

- Version with issue:
- Last known good version: not sure
- IDE: VS 2019 16.2 preview 3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- NuGet Packages: 4.0.0.482894
- Affected Devices:

**Comment by samhouts** [comment]
@mattleibow  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@mattleibow  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
