### ISSUE TITLE
[Bug] Android: Button Layout gallery page shows image outside the button

### ISSUE THREAD

**Issue by andreinitescu** [xamarin/Xamarin.Forms#6469]
### Description

On Android, the Button Layout gallery page shows image outside the button

![image](https://user-images.githubusercontent.com/743918/59156785-9ecf4280-8aa9-11e9-8a17-0a468aa225b1.png)

### Discussion

As discussed a bit with Shane, I understand that this comes from the fact that it sets zero padding, which makes sense.  But why is it drawing it outside the Button, shouldn't the image be right on the border, not outside?

For the issue with setting zero when gallery page starts, I have a commit which fixes this:
https://github.com/andreinitescu/Xamarin.Forms/commit/d796e95d9d2706d280137c4ebb9690449a478426
With this change, when page starts, it looks like this:

![image](https://user-images.githubusercontent.com/743918/59156835-9b888680-8aaa-11e9-9397-40746643e5c8.png)

Let me know if this is OK and I can make a PR.

**Comment by samhouts** [comment]
@andreinitescu Your changes to the gallery look good, but I agree--I doubt developers expect the Image to be rendered outside the bounds of the image background color. Buttons on Android are complex, though, and we'll need to take care to test all the various scenarios (e.g., with background color, without background color, with border, without border, with the legacy padding, without legacy padding, etc.)

**Comment by andreinitescu** [comment]
@samhouts Should I make a PR with the fix for the gallery page?
