### ISSUE TITLE
Border and CornerRadius are not respected in UWP when button is disabled

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#6474]
### Steps to Reproduce

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="UWPDisabledButton.MainPage">

    <StackLayout>
        <Button CornerRadius="10" BorderWidth="5" BorderColor="Red" Text="Button" />
        <Button CornerRadius="10" BorderWidth="5" BorderColor="Red" Text="Button" IsEnabled="False"/>
    </StackLayout>

</ContentPage>
```

### Expected Behavior
Button border and rounded corners can be seen when disabled.

### Actual Behavior + Screenshot
![image](https://user-images.githubusercontent.com/19922066/59185893-2a2cfe80-8ba4-11e9-8e22-af3c95a162e7.png)
(Hover above normal button)
![image](https://user-images.githubusercontent.com/19922066/59185771-dc17fb00-8ba3-11e9-84e6-f78b5c5c34fd.png)

<details>
<summary>Basic information</summary>
Windows 10 version 1803

Microsoft Visual Studio Community 2019
Version 16.1.1
VisualStudio.16.Release/16.1.1+28922.388
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA419
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

C# Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Unity   4.1.1.0
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.542 (d16-1@68b985244)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.22 (HEAD/8e7764fdf)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3cb36842fc4
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Xamarin.iOS and Xamarin.Mac SDK   12.10.0.153 (750a879)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by samhouts** [comment]
@Happypig375  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Happypig375** [comment]
[UWPDisabledButton.zip](https://github.com/xamarin/Xamarin.Forms/files/3275704/UWPDisabledButton.zip)

**Comment by bmacombe** [comment]
I believe the issue here is that prior to Win 10 1809, the button control did not support corner radius.  The radius was only being set on the content control hosted by the button.  So when the background of the button changed when not enabled, it expands beyond the content control.

To test I changed the Win 10 targets to 1809 and set the corner radius property of the button as well as the content control and the desired results where achieved.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.cornerradius#Windows_UI_Xaml_Controls_Control_CornerRadius

![image](https://user-images.githubusercontent.com/15127788/66845642-0274eb00-ef36-11e9-8eb7-126403707c38.png)

@samhouts  @PureWeen I know there was some discussion around which version of Win 10 to target and/or using WinUI directly.  What do you advise in this situation?  I don't want to submit a PR that will change the targeted version of Windows or I could do it as a draft PR that can wait until XF targets a min version is 1809 or higher.

Thanks
