### ISSUE TITLE
[Bug - Android] Carousel view items do not fill

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#6475]
### Description
Tested out this sample on Android:
https://github.com/pauldipietro/CollectionViewSample/issues

Following this blog post:
https://devblogs.microsoft.com/xamarin/xamarin-forms-4-0-feature-preview-an-entirely-new-point-of-collectionview/

I downloaded the sample and updated to xamarin forms V4.0.0.482894

and clicked the CarouselView tab and each item is not filling the page as shown in this gif:

https://devblogs.microsoft.com/wp-content/uploads/sites/44/2019/03/carousel.gif

Instead each carousel item is measured as the smallest it can be

### Steps to Reproduce

1.  open sample on android and click carousel tab
2.  see carousel items are not filling carousel page like gif
3. 

### Expected Behavior
carousel items should look like the gif

**Comment by samhouts** [comment]
@JKennedy24 Thank you for the report. CarouselView is still in very early stages. We'll be sure to address this when we continue work on it.

**Comment by LeoJHarris** [comment]
Up voting this issue. Hoping to see this resolved soon.

**Comment by JKennedy24** [comment]
I've been waiting since the original release of the carousel view in 2016 for a working xamarin.forms carousel view.

I'm currently using https://github.com/alexrainman/CarouselView but even this has its downfalls
- dont think its virtualising
- no infinite scrolling

**Comment by LeoJHarris** [comment]
@JKennedy24 The carouselView you mentioned doesnt work with XF 3.5 or later see: https://github.com/alexrainman/CarouselView/issues/489 This issue is blocking for us, and although the issue was closed a fix was never released. 

We will continue to wait on the Carousel View provided by XF. CarouselView is a must have compont in alot of apps we develop and we hope to see a stable and flexible CarouselView avalaible soon.

**Comment by rmarinho** [comment]
Hi, can you still replicate the issue? 

Can you remove the layout on the CarouselPage? I think this was a old sample not using the correct linear layout.

**Comment by JKennedy24** [comment]
taking the Layout of the page works perfectly

Thanks!
