### ISSUE TITLE
[Enhancement] Add ItemSelected/QueryChanged/QueryConfirmed events to SearchHandler

### ISSUE THREAD

**Issue by TimLariviere** [xamarin/Xamarin.Forms#6481]
## Summary
SearchHandler has a few overridable methods to change the behavior when some user interactions happen, like when a user types something or select a result item.

But these overridable methods (OnItemSelected, OnQueryChanged, OnQueryConfirmed) don't have real event equivalents that we can subscribe to.

This is not great for external frameworks, like Fabulous, where inheriting+overriding might not be an option.

## API Changes

Add 3 new events based on their `On*` method equivalents on the SearchHandler class:

- QueryChanged
- QueryConfirmed
- ItemSelected

## Intended Use Case

Today, we're required to inherit from SearchHandler to be able to react to those "events".

For example, I had to create a new control which exposes these methods in Fabulous. (though they're not exposed as events here)
```fsharp
/// A custom SearchHandler which exposes the overridable methods OnQueryChanged, OnQueryConfirmed and OnItemSelected as events
type CustomSearchHandler() =
    inherit SearchHandler(ItemTemplate=DataTemplate(typeof<ContentViewElement>))

    member val QueryChanged = ignore with get, set
    member val QueryConfirmed = ignore with get, set
    member val ItemSelected: obj -> unit = ignore with get, set

    override this.OnQueryChanged(oldValue, newValue) = this.QueryChanged (oldValue, newValue)
    override this.OnQueryConfirmed() = this.QueryConfirmed ()
    override this.OnItemSelected(item) = this.ItemSelected item
```

It would be great to not have to do this.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
