### ISSUE TITLE
[xcode11-support] WWDC 2019 Areas for Research

### ISSUE THREAD

**Issue by chamons** [xamarin/Xamarin.Forms#6483]
The macios team took some notes on areas Xamarin.Forms could be impacted by Xcode 11:

- New system colors and materials (Semantic Colors and materials)
- Support for light/dark theme
- Support for “cards” to present modal pages - we might need a way of telling full-screen presentation from the new cards default.
- Asking system font by name can fail
- SF Symbols
- Blur backgrounds?
- Support vibrancy?
- Trait collection changes 
- Avoid deprecated styles like uiactivityindicatorview on iOS > 12
- Use of the new Sheet idioms, and set proper defaults for camera and other full-screen view controllers
- Forms can now have popup menu - UIContextMenu
- Support for scenes - multiple windows on ipad

**Comment by chamons** [comment]
Two major areas I did not highlight were:

- Sign in with Apple
- Multi-window UIKit API

**Comment by samhouts** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/7145

**Comment by samhouts** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/7147

**Comment by jfversluis** [comment]
We're a couple of WWDCs in the future now! Closing this one.
