### ISSUE TITLE
[Bug] Shell TabBarIsVisible Ignored

### ISSUE THREAD

**Issue by seansparkman** [xamarin/Xamarin.Forms#6485]
### Description

The TabBar should not be visible on "On Boarding" screen.

### Steps to Reproduce

1. Create a new on boarding ContentPage
2. Set the Shell.TabBarIsVisible to False
3. Set the Shell.NavBarIsVisible to False
3. Register the new ContentPage as a Route with Routing.RegisterRoute in the constructor of the AppShell.xaml.cs
4. Call GoToAsync in the constructor

### Expected Behavior

The TabBar and the NavBar should not be visible.

### Actual Behavior

NavBar does not show up but the TabBar does.  Navigating to subsequent pages seem to work just fine.

### Basic Information

- Version with issue: 4.0.0.482894
- Last known good version: N/A
- IDE: Visual Studio 2019 for Windows 16.1.2
- Platform Target Frameworks: 
  - iOS:  12.10.0.153
  - Android: N/A
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: Just what comes with the template
- Affected Devices:

### Screenshots

![Screenshot with tabbar showing](https://raw.githubusercontent.com/seansparkman/ShellNavigationExample/master/2019-06-10_11-47-18-PM.png)

### Reproduction Link

https://github.com/seansparkman/ShellNavigationExample
https://github.com/seansparkman/ShellNavigationExample/blob/master/ShellNavigationRegistration/ShellNavigationRegistration/Views/OnBoarding.xaml#L8-L9

**Comment by jfversluis** [comment]
It seems to have something to do with the `GoToAsync` call because when you set the page directly as the main page `MainPage = new OnBoarding();` it seems to work fine.

**Comment by MarcoParreira** [comment]
This still happens on iOS
