### ISSUE TITLE
[Bug] CollectionView is Selectable on UWP even with SelectionMode=None

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#6489]
### Description
Created a simple selection view with SelectionMode= none and run on uwp.. items are still selectable

### Steps to Reproduce

1.  Create simple selectionview with selectionmode = none and run on uwp
2.  see items are still selectable
3. 

### Expected Behavior
items are not selectable

### Actual Behavior
items are selectable

**Comment by jfversluis** [comment]
@JKennedy24 would you mind setting up a small reproduction project and attach it?

**Comment by JKennedy24** [comment]
If you add a UWP start project to this sample:
https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/Xaminals)

That would replicate it. I'm guessing nobody's tested collectionviews on uwp

**Comment by jfversluis** [comment]
Couldn't add it to Xaminals since Shell is not supported for UWP. Created a small little reproduction project myself.

It seems indeed this functionality is not working for UWP.

[issue6489.zip](https://github.com/xamarin/Xamarin.Forms/files/3290428/issue6489.zip)

**Comment by hartez** [comment]
#6629 will fix this.
