### ISSUE TITLE
[Bug] Mouse-over effect does not deactivate after tap in WPF

### ISSUE THREAD

**Issue by jrahnpdv** [xamarin/Xamarin.Forms#6490]
### Description

When using multiple buttons with an image as content, and you replace this image dynamically upon clicking, the mouse-over effect does not deactivate in some cases when used in touchscreen mode.

### Steps to Reproduce

1. Add at least two buttons in a WPF form, replace the content image in the click handler.
2. Launch the app in touchscreen mode
3. Tap the buttons until one doesn't lose its hover-effect.

### Expected Behavior

The hover-effect should disappear at the latest when tapping another button.

### Actual Behavior

Hover-effect persists and multiple buttons are highlighted.

### Basic Information

- Version with issue:
3.4.0.1008975, 4.0.0.425677, 4.0.0.482894 not tested due to blackscreen bug
- Last known good version:
Unknown
- IDE:
Visual Studio 2019
- Platform Target Frameworks:
  - WPF:
- Nuget Packages:
   * NETStandard.Library v2.0.3
   * Xamarin.Forms v4.0.0.425677
- Affected Devices:
Surface Devices in touch mode

### Screenshots

Windows Step Recorder File is attached (Look around halfway through).
[BUG_Selection.zip](https://github.com/xamarin/Xamarin.Forms/files/3275743/BUG_Selection.zip)

### Reproduction Link
https://github.com/jrahnpdv/Xamarin-Bug-Reproduction.git

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
