### ISSUE TITLE
[Bug] Some Font Image are cropped on iOS

### ISSUE THREAD

**Issue by Luca7993** [xamarin/Xamarin.Forms#6491]
### Description
I'm using fontawesome 5 free solid to display some images.
A few of these images are cropped when I use FontImageSource on a button or toolbaritem.
I think the problem is on images where width is greater than height, for example fa-cloud [https://fontawesome.com/icons/cloud?style=solid](url)

### Steps to Reproduce

1. Add a button on any layout with a fontimagesource with fa-cloud icon ("\uf0c2")

### Expected Behavior
The image should not be cropped

### Actual Behavior
The image is cropped

### Basic Information

- Version with issue: last 4.0
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.2
 
### Screenshots
First image is cropped on the right.
![image](https://user-images.githubusercontent.com/1061695/59260652-4f6d4b80-8c3c-11e9-81e3-25bf9944fd2a.png)

### Reproduction Link
https://github.com/Luca7993/FontImageIosProblem

**Comment by jfversluis** [comment]
Does this also happen on Android or just iOS?

**Comment by Luca7993** [comment]
Only on ios

Il 11 giu 2019 1:03 PM, Gerald Versluis <notifications@github.com> ha scritto:

Does this also happen on Android or just iOS?

**Comment by DevEddy** [comment]
Any news or tip how to try to create a custom renderer for FontImageSource?

Thanks,
Eddy

**Comment by jfversluis** [comment]
@squinn7 if you could create a separate issue for UWP that would be great, that way we can track progress on both platforms. You can refer to this one. If you would also be so kind to attach a sample project that shows this behavior you will be my personal hero.

**Comment by maexsp** [comment]
Same problem here. We create our own custom Font.otf file with custom branded vector icons by our UX designer. Icons are cropped on iOS only but only those which are in width larger than in heigth or if height is larger than width. On Android and on UWP looks fine.

**Comment by jfversluis** [comment]
Opened a PR with a fix for this!

**Comment by jingliancui** [comment]
It's seem like it still not be fixed in v4.2 like this https://github.com/xamarin/Xamarin.Forms/issues/7017

**Comment by jfversluis** [comment]
It might not have made it into the last release. New versions of the Xamarin.Forms packages should be released soon, please retest with those when they come.
