### ISSUE TITLE
[Bug] x:DataType="SomeType" breaks Intellisense

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms#6493]
### Description
When using `x:DataType="SomeType"` in DataTemplate definition, it breaks Intellisense, so that I don't see properties from SomeType listed when trying to bind inside the DataTemplate. In addition, I'm also getting a warning that such property is not found in SomeType.

On the other hand, when I use `x:DataType="{x:Type SomeType}"` then I see all properties from SomeType listed when writing a Binding expression inside the DataTemplate. No warnings.

### Steps to Reproduce

1. Create a DataTemplate and set `x:DataType` to `"SomeType"`
2. Try to bind to a property from SomeType inside DataTemplate

### Expected Behavior
I should see all properties from SomeType listed in Intellisense.

### Actual Behavior
No properties from SomeType listed + I get a warning that given property is not found in SomeType.

**Comment by StephaneDelcroix** [comment]
x:DataType expects a string literal, not a `{x:Type}` markup extension

/cc @mgoertz-msft

**Comment by StephaneDelcroix** [comment]
related to #6492

**Comment by viktorszekeress** [comment]
When I use string literal, it will break Intellisense, as described above.

**Comment by toomasz** [comment]
x:DataType="{x:Type SomeType}" is not supported in Forms Xaml, i XamlC compiler should complain about it:

https://github.com/xamarin/Xamarin.Forms/pull/5335

**Comment by viktorszekeress** [comment]
Again guys, I'm okay with using only string literal, but it breaks IntelliSense for me. 
What will be done about that?

**Comment by toomasz** [comment]
@viktorszekeress Yes, intellisense should work for string literals. Could you attach small project that demonstrates the issue?

**Comment by viktorszekeress** [comment]
Sorry, it turns out to be only Resharper issue. If I use VS IntelliSense, it does find the properties from SomeType.

**Comment by samhouts** [comment]
@viktorszekeress Can you clarify the status of this issue now? Do you have a solution? Thanks!

**Comment by viktorszekeress** [comment]
@samhouts Hi, yes, after all it turned out to be related to Resharper. Regarding not-accepting {x:Type} expression in XF - I don't think it's a good idea. Why not making language more similar to XAML in WPF, WP8, UWP?

**Comment by viktorszekeress** [comment]
After updating to XF 4.1, my app no longer builds, as I'm not able to use {x:Null} for x:DataType, within a DataTemplate. 
Not cool.

See #6648

**Comment by tranb3r** [comment]
> Sorry, it turns out to be only Resharper issue. If I use VS IntelliSense, it does find the properties from SomeType.

@viktorszekeress 
I've turned off Resharper, but VS still does not find the properties. 
Is there something else to do in order to make VS intellisense process the type properly ?

**Comment by viktorszekeress** [comment]
Just make sure that VS IntelliSense is set in R# settings for XAML files. I think I needed to restart VS anyway, then it started working.

**Comment by tranb3r** [comment]
> @tranb3r
> Just make sure that VS IntelliSense is set in R# settings for XAML files. I think I needed to restart VS anyway, then it started working.

Thanks... however, it does not work for me, no matter what I do :(

**Comment by samhouts** [comment]
@tranb3r If the intellisense continues to be an issue for you, please report it via Visual Studio's send feedback. Thanks!
