### ISSUE TITLE
[Material,Frame] iOS Border is thinner than Android 

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#6495]
### Description

> Frame on iOS - The Border color is thin when compared to Android. [susairajs]

https://github.com/davidortinau/VisualChallenge/pull/37

**Comment by rmarinho** [comment]
Not sure if Material guidelines are the same in both platforms

**Comment by SatyaRamprasad** [comment]
Hi @davidortinau  @rmarinho @PureWeen 
Can anyone please share the work around for this issue?
Thanks in advance :)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
