### ISSUE TITLE
[Bug] Navigating away from CollectionView and coming back leaves weird old items 

### ISSUE THREAD

**Issue by TimLariviere** [xamarin/Xamarin.Forms#6507]
### Description

On iOS, when using a CollectionView in Shell, navigating away from it with `Shell.GoToAsync()` and going back makes the old items appear stacked together, while the new items are displayed correctly.

### Steps to Reproduce

1. Clone the Xaminals sample (https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/Xaminals)
2. Debug the iOS project
3. Check that the CollectionView of cats appears correctly
4. Open the flyout menu
5. Tap "About"
6. Repoen the flyout menu
7. Tap "Domestic"
8. Notice that the CollectionView now displays 2 lists of cats, one correct and one stack together on one line

### Expected Behavior

The CollectionView should appear correctly on both cases

### Actual Behavior

The CollectionView appears incorrectly

### Basic Information

- Version with issue: 4.0.0.425677
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - iOS:  12.2

### Screenshots

<img src="https://user-images.githubusercontent.com/6429007/59377134-e11aad00-8d51-11e9-9f90-7f26e754b03a.png" alt="Simulator Screen Shot - iPhone Xʀ - 2019-06-12 at 20 30 54" height="500" />

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/Xaminals/

**Comment by Robtom5** [comment]
This looks similar to #5831 

I've also seen this issue but the list that appears bunched up also didn't register any ontapped interaction

**Comment by alanag13** [comment]
I've only tested this against my own project that was exibiting this issue, but it may help : https://github.com/xamarin/Xamarin.Forms/issues/5831#issuecomment-506594233

**Comment by anotherlab** [comment]
I'm seeing the same problem.  If I go from a page with a CollectionView to one that has a map (other pages do not seem to trigger the problem) and then back again, the last item from the CollectionView is displayed a second time, on top of the CollectionView and does not recognize any taps or gestures.

**Comment by jsuarezruiz** [comment]
It seems to be the same as https://github.com/xamarin/Xamarin.Forms/issues/5831 or be related.

**Comment by codebreakerlegend2019** [comment]
I Already Fix it on my Case I Used the Nightly Builds 

Here: https://github.com/alanag13/Xamarin.Forms/tree/fix-collectionview

You can browse there on how to Work on it both Mac or Windows version of VS 2019 or lower

And NOTE: Upon Updating your Xamarin.Forms to 4.5 with Nightly Make Sure you also Download the Xamarin.Visual.Material JUST IN CASE YOU USED That on your Projects But if not You're Good To Go :) 


Thanks for this Community My Problems Have been Solved Perfectly :) Power!!! <3 <3 <3

**Comment by mastermoe01** [comment]
I have the same issue! in what release will this get fixed?

**Comment by jsuarezruiz** [comment]
@mastermoe01  In case you want to validate, the fix should be in the Nightly package and the fix was made in this PR: https://github.com/xamarin/Xamarin.Forms/pull/8189

**Comment by hartez** [comment]
Closing this, it was fixed by #8189. If I'm wrong about that, ping me here and I'll reopen it.
