### ISSUE TITLE
Converting project to Android 9 code behind references returning null for text boxes.

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#6508]
I upgraded my project to Andriod 9 as have a google pixel for testing however when I press enter on a control im not getting the binding values passed back to the code behind is there a silly reason for this or has something changed to cause this. I am using Xamrian forms.

Say I physically text the txtUserName.Text ="Test1"; i am getting null when i check for it ? I should add i upgraded to Xamrian 4.0.0.482894 as well

**Comment by jfversluis** [comment]
Thank you for your issue @davidbuckleyni. Is there any possible way to reproduce this in a sample project? Also, would it be possible to use the default issue template so we can get some more information on what you were doing exactly? You can find it [here](https://github.com/xamarin/Xamarin.Forms/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by samhouts** [comment]
@davidbuckleyni  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
