### ISSUE TITLE
[Bug] Greylisted API's 

### ISSUE THREAD

**Issue by b12kab** [xamarin/Xamarin.Forms#6509]
### Description
After upgrading from API 27 to API 28 the below 5 show up in the Google Play store as: "The following APIs are greylisted and Google can’t guarantee that they will work on existing versions of Android. Some may be already be restricted for your target SDK"

- API Landroid/graphics/drawable/DrawableContainer;->getOpticalInsets()Landroid/graphics/Insets;
- API Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
- API Landroid/text/SpannableStringInternal;->length()I
- API Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z
- API Landroid/view/animation/Animation;->mListener:Landroid/view/animation/Animation$AnimationListener;

### Basic Information
- Version with issue: Android API 28
- Last known good version: Android API 27
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android:  
Xamarin.Android
Version: 9.2.3.0 (Visual Studio Community)
Android SDK: /Users/keith/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 29.0.0

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

Microsoft Mobile OpenJDK
Java SDK: /Users/keith/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-28 18:18:20 UTC

- Nuget Packages:
**(Project)**
Behaviors.Forms (1.4.0)
CardsView (2.1.3)
FluentValidation (8.1.0)
sqlite-net-pcl (1.5.231)
Xamarin.Build.Download (0.4.12-preview3)
Xamarin.Essentials (1.1.0)
Xamarin.Forms (4.0.0.482894)
**(Project.Android)**
Behaviors.Forms (1.4.0)
CardsView (2.1.3)
FluentValidation (8.1.0)
sqlite-net-pcl (1.5.231)
Xamarin.Build.Download (0.4.12-preview3)
Xamarin.Essentials (1.1.0)
Xamarin.Forms (4.0.0.482894)
Plugin.CurrentActivity (2.0.1.4)
Xamarin.Android.Crashlytics (2.9.4.1)
Xamarin.Android.Crashlytics.Anwsers (1.4.2)
Xamarin.Android.Crashlytics.Beta (1.2.9)
Xamarin.Android.Crashlytics.Core (2.6.3)
Xamarin.Android.Fabric (1.4.3)
Xamarin.Android.Support.Annotations (28.0.0.1)
Xamarin.Android.Support.Compat (28.0.0.1)
Xamarin.Android.Support.Core.UI (28.0.0.1)
Xamarin.Android.Support.Core.Utils (28.0.0.1)
Xamarin.Android.Support.Design (28.0.0.1)
Xamarin.Android.Support.Fragment (28.0.0.1)
Xamarin.Android.Support.Design (28.0.0.1)
Xamarin.Android.Support.v4 (28.0.0.1)
Xamarin.Android.Support.v7.AppCompat (28.0.0.1)
Xamarin.Android.Support.v7.CardView (28.0.0.1)
Xamarin.Android.Support.v7.MediaRouter (28.0.0.1)
Xamarin.Firebase.Analytics (60.1142.1)
Xamarin.Firebase.Analytics.Impl (60.1142.1)
Xamarin.Firebase.Core (60.1142.1)

**Comment by samhouts** [comment]
Thanks! This will require some investigation.

**Comment by PureWeen** [comment]
@b12kab We're keeping track of these APIs over here

https://github.com/xamarin/Xamarin.Forms/issues/4118

It's a bit of a weird situation with google because a lot of these cases are issues on the google side

https://stackoverflow.com/a/53736775
https://stackoverflow.com/a/59435170

Also, these APIs jump lists every so often for example

> API Landroid/graphics/drawable/DrawableContainer;->getOpticalInsets()Landroid/graphics/Insets;

Was white listed in API 29
