### ISSUE TITLE
new CheckBox control does not change look when IsEnabled = false

### ISSUE THREAD

**Issue by philipag** [xamarin/Xamarin.Forms#6514]
## Summary
When IsEnabled = false, the checkbox should be faded out (or some other platform specific change in look).  This is standard behavior on most platforms.  Current this property has no effect.

## API Changes

No API change needed since IsEnabled property already exists.

**Comment by vniehues** [comment]
Are there any news on this? Im facing the same issue.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
