### ISSUE TITLE
FlexLayout preview doesn't match simulator

### ISSUE THREAD

**Issue by BenBtg** [xamarin/Xamarin.Forms#6520]
### Description
FlexLayout is rendered very differently in previewer to simulator. 
Issue with margins or padding in real app causing content to be cropped in header.
May be caused by nav header which is not rendered in previewer
### Steps to Reproduce
<NavigationPage.TitleView>
        <Label Text="PRODUCTS" Style="{StaticResource NavBarTitleStyle}"/>  
    </NavigationPage.TitleView>  
    
    <FlexLayout Direction="Column">
        <FlexLayout Margin="20,17,10,25" FlexLayout.Basis="100">
            <StackLayout>
                <Label Style="{StaticResource HomeHeaderStyle}" FontFamily="{StaticResource GothamBook}" FontSize="26" WidthRequest="200">Home</Label>
                <Label Text="1200 WILLOW GROVE RD" FontSize="10" FontFamily="{StaticResource GothamMedium}" Margin="0,5" />
            </StackLayout>
            <BoxView FlexLayout.Grow="1" />
            <controls:SvgIcon ResourceId="Konnect.Assets.Weather.MostlySunny.svg" WidthRequest="28" HeightRequest="28" FlexLayout.AlignSelf="End" />
            <Label FontFamily="{StaticResource GothamBook}" FontSize="14" FlexLayout.AlignSelf="End" Margin="6,0,16,6"> 62°F</Label>
        </FlexLayout>
        <CollectionView ItemsSource="{Binding Products}" Margin="4,4,10,10" FlexLayout.Grow="1">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" Span="2" />
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid Padding="6,6,0,0" HeightRequest="175">
                        <Grid.RowDefinitions>
                            <RowDefinition Height="20" />
                            <RowDefinition Height="*" />
                            <RowDefinition Height="30" />
                            <RowDefinition Height="1.5" />
                        </Grid.RowDefinitions>
                        <BoxView Grid.RowSpan="4" Color="White" />
                        <BoxView CornerRadius="2.5" Color="{StaticResource AccentBlue}" HorizontalOptions="Start" VerticalOptions="Start" WidthRequest="5" HeightRequest="5" Margin="15,15,0,0" />
                        <controls:SvgIcon Grid.Row="1" IconFilePath="{Binding Image}" Margin="5" />
                        <Label Grid.Row="2" Text="{Binding Name}" FontSize="Micro" HorizontalTextAlignment="Center" FontFamily="{StaticResource GothamMedium}" />
                        <BoxView Grid.Row="3" Color="{StaticResource AccentBlue}" />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
            <CollectionView.Effects>
                <effects:HideScrollBarEffect/>
            </CollectionView.Effects>
        </CollectionView>
    </FlexLayout>

### Expected Behavior
Page in Previewer should look like same page in Simulator
### Actual Behavior
Header is cropped as shown in screen shot
### Basic Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.0.9 (build 5)
Installation UUID: 79e70a6f-aad4-4956-9bfb-f73029ce75fc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.9
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Enterprise)
Android SDK: /Users/benbtg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ac37ccd385
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/benbtg/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.9
1.8.0-9
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-05-28 18:18:20 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.8.0.0 (Visual Studio Enterprise)
Hash: 0aa84521
Branch: d16-0
Build date: 2019-04-02 16:01:19-0400

=== Xamarin.iOS ===

Version: 12.8.0.2 (Visual Studio Enterprise)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

=== Xamarin Designer ===

Version: 4.17.4.420
Hash: 0a2420845
Branch: remotes/origin/d16-0
Build date: 2019-05-23 23:40:02 UTC

=== Build Information ===

Release ID: 800090005
Git revision: 72a44477dd706608c2300a568f71e5769f89f7ef
Build date: 2019-05-29 15:19:54+00
Build branch: release-8.0
Xamarin extensions: 3e94aa3836143b8f5a5b9151b61a80e2fd278d62

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.3.2
MFractor 3.8.4

### Screenshots

<img width="1418" alt="Screenshot 2019-06-13 at 19 53 27" src="https://user-images.githubusercontent.com/70525/59459709-54392780-8e15-11e9-9c0c-f993777b85f5.png">

### Reproduction Link

I can provide link to private repo internally if needed

> VS bug [#918087](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918087)

**Comment by drewgillies** [comment]
Thanks for the issue. I'm doing a sweep of Xamarin.Forms previewer issues to close them as we're focusing on areas with greater impact for now. We will keep the issue on file, however, for future reference. Thanks again!
