### ISSUE TITLE
[Enhancement] Entry view that does not show soft keyboard once focused

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms#6523]
## Summary
For anyone using external barcode scanners this is well known pain having softkeyboard popup each time you programmatically focus on an Entry field using Entry.Focus().

Lots of apps out there have requirement to use external barcode scanners connected through USB or bluetooth that act as a keyboard so HID scanners.  Unlike with serial scanners, here scanner acts as keyboard and every time you programmatically focus on Entry, soft keyboard pops up.  One way around is to use serial scanners but that means you have to program platform specific rather than platform agnostic (Xamarin.Forms).  It also means that for Apple devices you have to have special scanners which is not an options for many vendors.

Another example where this would be useful is if we write our own pin pad or keyboard with our own buttons.  Tapping on these, puts corresponding character into an Entry field that has focus.  In this case also, showing softkeyboard makes no sense.

It would be nice to have a view like Entry that allows preventing soft keyboard from showing up once Focus is called programatically on it.  This would remove lots of overhead and complex functionality called all over the place to hide soft keyboard using various hacks all over the web which introduce even more issues and spaghetti code.

## API Changes

Here are few ideas how this could be implemented:

1. Having an Entry that distinguishes btw OnTap and Focus allowing to show up softkeyboard in OnTap but not show it in call to Focus, or
2. Having new Keyboard setting like Entry.Keyboard = none.  This would allow scanning into a hidden or not hiden Entry field without triggering softkeyboard pop up, or
3. Having brand new Entry view that simply does not show softkeyboard regardless, or
4. Having something else that would simply allow user to not show softkeyboard when Focus is called pro-grammatically, or
5. ...

## Intended Use Case
My app is running on Android, iOS, or UWP device and is written in Xamarin.Forms.  The reason we went with this is that we want to share as much code as possible between all 3 head projects and **need this on Android, iOS, and UWP**. 

The app allows restaurants to connect an external barcode scanner (ZXing is not an option as camera is slow compared to external barcode scanner) either through Bluetooth or USB cable if device is mounted to a housing with USB interface.  

It is a HID connection so scanner is viewed as a keyboard which has great advantages over serial or SDK based scanners, to name just few:

1. it works for any scanner, 
2. requires no platform specific coding, 
3. requires no SDK, 
4. since it works on all scanners, no need for multiple SDKs, EMDKs etc
5. requires no need to maintain, update etc all these SDKs
6. requires no MFI certification with Apple devices 
7. requires no platform specific developers as same code from Xamarin.Forms library is used on all 3 platforms
8. ...

But the disadvantage is that you have to scan into an Entry (a text input style of a control) which is capable of detecting Enter key as a trigger point for processing the scanned barcode (another advantage is that all external barcode scanner come with this preconfigured so no need to even configure Enter key on end of a barcode scan).  If you dont scan into an text input style view like Entry, the scanned barcode is lost, so scan has to go into a text input type of a view such as Entry view.

So, Entry is great to scan into but in order to do so, you have to focus it by calling Focus() method somewhere in the code.  However, that brings very annoying issues where softkeyboard keeps popping up on each focus and hidding lots of screen.  Another problem is that we dont want softkeyboard as we are scanning into it, not typing into it.  For typing, we can always provide another Entry field that shows soft keyboard.  

We try to go around this problem and have our scanning Entry field hidden, call in code Focus() to focus it (so we can scan into it), and then call some sort of platform specific hack implementation to hide soft keyboard.  This gets to complex but it does not solve the problem since it shows - then hides soft keyboard instead of not showing it at all.  In addition, you have to write platform specific code on all 3 platforms to hide keyboard which we want to avoid for reasons already mentioned.  Another problem is that you now have to call that logic all over the place creating spaghetti code.  And this leads to serious mess, multiple calls to it from different locations, Focus() and HideKeyboard() competing with each other etc etc.

It would be very helpful to have some kind of Entry view in Xamarin.Forms allowing to either not show soft keyboard at all or choose to show it only on tap but not on programmatic call to Focus().  Or some other way as long as we can prevent softkeyboard from showing up.

**Comment by wangyankun33** [comment]
Can you implement this function?

**Comment by jfversluis** [comment]
Thanks for asking @wangyankun33, we're still considering this proposal. As soon as we have anything to report, you will find it on this page.

Meanwhile, if you have any details on how you might have implemented it today that would be super helpful!

**Comment by wangyankun33** [comment]
> Thanks for asking @wangyankun33, we're still considering this proposal. As soon as we have anything to report, you will find it on this page.
> 
> Meanwhile, if you have any details on how you might have implemented it today that would be super helpful!
I am also actively looking for ways to achieve this, but there is no progress yet.

**Comment by wangyankun33** [comment]
> Thanks for asking @wangyankun33, we're still considering this proposal. As soon as we have anything to report, you will find it on this page.
> 
> Meanwhile, if you have any details on how you might have implemented it today that would be super helpful!

I am also actively looking for ways to achieve this, but there is no progress yet.

**Comment by DoubleDBE** [comment]
I'd like this functionality as well. We're facing the same issues.

**Comment by edconsi** [comment]
han podido solucionar esto?

**Comment by espsousa** [comment]
Any news on this? Facing exact same issues as @dinobu described.

**Comment by MattVon** [comment]
Can you not just create a listener (will most likely have to be per platform) whereby you listen for an event, and then send it to the ViewModel (if you're using MVVM), and the use data binding to populate the entry?

That's what I'm doing for Zebra device (albeit the barcode scanner is apart of the device), but the logic is the same. No need to make it complicated when you can just use data binding.

**Comment by ktn8** [comment]
@MattVon Hey, I've recently been running into the same exact problems mentioned on this page. I was wondering if you could go into detail a bit on your implementation.

You mentioned using events, which makes sense, but how exactly are you triggering the event with a barcode scanner? As far as I'm aware, my bluetooth barcode scanner only acts as a way to input text into an entry field and then automatically submit at the end of the input (HID Mode). I'm restricted to this because my environment primarily uses iOS devices and I don't believe it's possible to use scanners in a different mode on the iOS platform.

Are you using a different type of scanning method or specific environment in order to successfully trigger the event? (SSP vs HID)?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
