### ISSUE TITLE
Can't change appearance of ShellTabLayout Android

### ISSUE THREAD

**Issue by jaspervanmegroot** [xamarin/Xamarin.Forms#6529]
### Description
Can't change the tablayout appearance in Android because its inaccessible due to its protection level. ShellTabLayoutAppearanceTracker is internal.

### Steps to Reproduce

1. Create custom renderer for a Shell
2. Override the AppearanceTracker 
`   protected override IShellTabLayoutAppearanceTracker CreateTabLayoutAppearanceTracker(ShellSection shellSection)
        {
            //return MyShellTabbarAppearanceTracker(this, shellSection);
        }`
3. Create a custom class for the AppearanceTracker and override ShellTabLayoutAppearanceTracker 

### Screenshots

![Knipsel](https://user-images.githubusercontent.com/19607572/59492521-6fde1580-8e89-11e9-8ef2-491544a655b1.PNG)

**Comment by jfversluis** [comment]
The concept of creating  custom renderer for Shell is a bit different, please check this section in the Docs: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/customrenderers#create-a-custom-renderer-class

It seems you are looking for the `CreateTabLayoutAppearanceTracker`. Does this help?

**Comment by jaspervanmegroot** [comment]
Yes, I am using the docs and do the same as ToolbarAppearanceTracker

`   public class MyShellRenderer : ShellRenderer
    {
        public MyShellRenderer(Context context) : base(context)
        {
        }

        protected override IShellToolbarAppearanceTracker CreateToolbarAppearanceTracker()
        {
            return new MyShellToolbarAppearanceTracker(this);
        }
    }`

` public class MyShellToolbarAppearanceTracker : ShellToolbarAppearanceTracker
    {
        public MyShellToolbarAppearanceTracker(IShellContext context) : base(context)
        {
        }

        public override void SetAppearance(Toolbar toolbar, IShellToolbarTracker toolbarTracker, ShellAppearance appearance)
        {
            base.SetAppearance(toolbar, toolbarTracker, appearance);
            toolbar.SetBackgroundResource(Resource.Drawable.monkey);
        }
    }`

**Comment by jfversluis** [comment]
Seems you're right! I've opened a PR for it

**Comment by jaspervanmegroot** [comment]
@samhouts Is it possible to hide the tabbar labels in the SetAppearnce method?
