### ISSUE TITLE
[Bug] FontImageSource cutted off

### ISSUE THREAD

**Issue by DevEddy** [xamarin/Xamarin.Forms#6541]
### Description
The icons with different height / width are cutted off on iOS. 
Android is working fine.
UWP not tested yet.

### Steps to Reproduce

1. Run the reproduction project

### Expected Behavior
Icon is shown correctly

### Actual Behavior
Icon is cutted off

### Basic Information

- Version with issue: 4.0.0.497661
- IDE: Visual Studio Community 2019 for Mac Version 8.1 (build 2742)
- Platform Target Frameworks: 
  - iOS:  8.0
- Affected Devices: iOS

### Screenshots
iOS:
![image](https://user-images.githubusercontent.com/7648336/59550333-b0ad5b80-8f69-11e9-912c-191d3680bcc7.png)

### Reproduction Link
https://github.com/DevEddy/FontImageSourceCuttedOff

**Comment by rmarinho** [comment]
I wonder if this is related with the font family, using your sample i tried with

```
<ContentPage.IconImageSource>
        <FontImageSource FontFamily="Ionicons"
                                 Glyph="&#xf2d1;"
                                 Size="100"
                                 Color="Green" />
    </ContentPage.IconImageSource>

    <StackLayout VerticalOptions="CenterAndExpand">
        <!--  Place new controls here  -->
        <Label Text="Welcome to Xamarin.Forms!"
               HorizontalOptions="Center"
               VerticalOptions="Center" />
        <Image>
            <Image.Source>
                <FontImageSource FontFamily="{StaticResource FontAwesomeFont}"
                                 Glyph="&#xf121;"
                                 Size="100"
                                 Color="Green" />
            </Image.Source>
        </Image>
         <Image>
            <Image.Source>
                <FontImageSource FontFamily="Ionicons"
                                 Glyph="&#xf2d1;"
                                 Size="100"
                                 Color="Green" />
            </Image.Source>
        </Image>
    </StackLayout>
```

![Simulator Screen Shot - iPhone Xʀ - 2019-06-18 at 16 49 34](https://user-images.githubusercontent.com/1235097/59699236-270bc100-91e9-11e9-9105-2fe8bde39b99.png)
![Simulator Screen Shot - iPhone Xs - 2019-06-18 at 16 25 08](https://user-images.githubusercontent.com/1235097/59699237-27a45780-91e9-11e9-9ce7-440a48b4fb4f.png)


Can you try other fonts and see if it's just FontAwesoem giving issues? thanks

**Comment by DevEddy** [comment]
I will do that, but it also should work with FontAwesome. 
On Android it works fine, so why it should be a font problem? 

-- Eddy

**Comment by rmarinho** [comment]
duplicated #6491
