### ISSUE TITLE
[Bug] Shell QueryProperty Parameter Ignored when Navigating to existing subpage

### ISSUE THREAD

**Issue by James3UK** [xamarin/Xamarin.Forms#6543]
### Description
When navigating to an already existing page with a new Uri the parameter in the uri is ignored. 
Tested on Android, I am unable to test on IOS currently. This issue does not occur when the main tabs are navigated to with parameters, only pages below those.

### Steps to Reproduce

1. Add a QueryProperty to a viewmodel
   `    [QueryProperty("TypeID", "id")]
    public class MonkeysPageViewModel : ViewModelBase
	{
        private string _typeId;
        public string TypeID
        {
            get
            {
                return _typeId;
            }
            set
            {
                _typeId = value;
                OnPropertyChanged();
                int mID;
                if (Int32.TryParse(TypeID, out mID))
                {
                    SelectedMonkey = Monkeys[mID];
                }
            }
        }`
2. Register the route as a "Relative Route" of another Shell tab
`Routing.RegisterRoute("monkeys/details", typeof(MonkeysPage2));`
3. Navigate with a Parameter
`await Shell.Current.GoToAsync("//monkeys/details?id=1");`
4. Using the bottom tab navigation open a different tab (Page1)
5. Navigate again with a different parameter
`await Shell.Current.GoToAsync("//monkeys/details?id=2");`

### Expected Behavior
New parameter is passed to ViewModel

### Actual Behavior
Parameter is ignored

### Basic Information

- Version with issue: 4.0.0.497661
- Last known good version: n/a
- IDE: VS 2019 for Windows v16.1.3
- Platform Target Frameworks: 
  - Android: 28
- Affected Devices: Only tested on Android emulator and device

### Reproduction Link

[MonkeyAppPicker.zip](https://github.com/xamarin/Xamarin.Forms/files/3293415/MonkeyAppPicker.zip)

**Comment by jpveldtman** [comment]
I am facing this exact same issue with iOS using Xamarin Forms 4.3.0.947036, On Android it is working fine

**Comment by aloptrbl** [comment]
does it solved? i have issue pass params and assign in variable. Hope get ASAP feedback.
