### ISSUE TITLE
[Bug] Android IOnTouchListener not work well with Shell

### ISSUE THREAD

**Issue by devinZhou102** [xamarin/Xamarin.Forms#6545]
### Description
the method OnTouch in IOnTouchListener not work well with Shell.
MotionEvent is set to MotionEventActions.Cancel while user still touching the veiw

### Steps to Reproduce

1.  Custom a view and implements IOnTouchListener
2.  place the custom view in page
3.  place the page in Shell 

### Expected Behavior

When MainPage = AppShell(); 
the touch event should work well, while user touch the view.

### Actual Behavior
MotionEvent is set to MotionEventActions.Cancel while user still touching the veiw
### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forns 4.0.0.497661
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by devinZhou102** [comment]
[TouchCancel.zip](https://github.com/xamarin/Xamarin.Forms/files/3293978/TouchCancel.zip)

**Comment by samhouts** [comment]
same root cause as #6310

**Comment by samhouts** [comment]
closed by #7032
