### ISSUE TITLE
[Android] Entry Completed event doesn't fire when settings the ImeOptions default to Next in Xamarin Android

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [xamarin/Xamarin.Forms#6549]
### Description
Entry Completed event doesn't fire in Android but it working in iOS when settings the ImeOptions as Next.

Code snippet:
 Control.ImeOptions = Android.Views.InputMethods.ImeAction.Next;

### Steps to Reproduce

1. Create the Entry in PCL project.
2. Set the ImeOptions as Next in Entry CustomRenderer
3. Completed event not fired when pressing the Next option.

**Comment by samhouts** [comment]
@SanthiyaArulsamy  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by SanthiyaArulsamy** [comment]
Sorry for the late update. Here i set the ImeOptions of Entry as Next in Android platform.

[Entry_CompeletedEvent.zip](https://github.com/xamarin/Xamarin.Forms/files/3321133/Entry_CompeletedEvent.zip)

**Comment by jcmanke** [comment]
Why aren't you setting the `Entry.ReturnType` property?

**Comment by samhouts** [comment]
@SanthiyaArulsamy As @jcmanke says, please use `ReturnType="Next"` on your `Entry`. I've confirmed that it will fire the `Completed` event. Thanks!
