### ISSUE TITLE
Unable to change the Target Android version and dialog appears always hidden

### ISSUE THREAD

**Issue by rscholey** [xamarin/Xamarin.Forms#6552]
Xamarin 4.0.0.497661

Clicking in the Target Android version doesn't bring down the dropdown list.  Somehow by restarting I managed to do it and set it to Version 9 but seems like the value was not updated in my csproj.  The dialog that appears when I click the button to the right always appears behind and I cannot see all the words in the dialog as in the attached screen print. 

<img width="414" alt="Screen Shot 2019-06-17 at 8 27 48 PM" src="https://user-images.githubusercontent.com/39233783/59604465-d9d31500-913e-11e9-9411-3421e8427210.png">

<img width="916" alt="Screen Shot 2019-06-17 at 8 28 09 PM" src="https://user-images.githubusercontent.com/39233783/59604466-d9d31500-913e-11e9-919a-293a40fb9416.png">

<img width="353" alt="ver" src="https://user-images.githubusercontent.com/39233783/59604629-4bab5e80-913f-11e9-94c4-150987ef6d8b.png">

**Comment by rscholey** [comment]
Tried this on another project of mine and I have the same problem where none of the dropdowns are working and I can't change min version or target.  Only way to do this will be to go into csproj and manually edit.

**Comment by rmarinho** [comment]
Hi this doesn't t seem  related with Xamarin.Forms itself. It might be this issue related with fullscreen
https://github.com/mono/monodevelop/pull/7923
