### ISSUE TITLE
Carousel View Xamarin Forms 4.0 crashed in iOS

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#6553]
### Description
I tried to use Xamarin Form 4.0 carousel view and for some reason when I test the app the carousel view page is crashing constantly on IOS platform.The version of Xamarin.forms is 4.0.0. 471375

And the following is the error log

" at (wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)\n at Xamarin.Forms.Internals.Registrar1[TRegistrable].GetHandler (System.Type type, System.Type visualType) [0x0002b] in D:\a\1\s\Xamarin.Forms.Core\Registrar.cs:56 \n at Xamarin.Forms.Internals.Registrar1[TRegistrable].GetHandlerForObject[TOut] (System.Object obj) [0x0002c] in D:\\a\\1\\s\\Xamarin.Forms.Core\\Registrar.cs:92 \n at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00005] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003d] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementRenderer1[TElement].SetElement (TElement element) [0x000de] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementRenderer1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003d] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLoad () [0x0008f] in <240545b21a4d479f84df8c4c71149e11>:0 \n at (wrapper managed-to-native) ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper(intptr,intptr)\n at UIKit.UIViewController.get_View () [0x0002a] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.150/src/Xamarin.iOS/UIKit/UIViewController.g.cs:3037 \n at Xamarin.Forms.Platform.iOS.PageRenderer.get_NativeView () [0x00008] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.PageRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0003d] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.ShellSectionRootRenderer.LoadRenderers () [0x00028] in <240545b21a4d479f84df8c4c71149e11>:0 \n at Xamarin.Forms.Platform.iOS.ShellSectionRootRenderer.ViewDidLoad () [0x00035] in <240545b21a4d479f84df8c4c71149e11>:0 \n at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.150/src/Xamarin.iOS/UIKit/UIApplication.cs:86 \n at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.10.0.150/src/Xamarin.iOS/UIKit/UIApplication.cs:65 \n at CollectionViewSample.iOS.Application.Main (System.String[] args) [0x00001] in /Users/mhr/Downloads/CollectionViewSample-master/CollectionViewSample/CollectionViewSample.iOS/Main.cs:17 "

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://forums.xamarin.com/discussion/156971/carousel-view-xamarin-forms-4-0 .

**Comment by rmarinho** [comment]
We haven't finished the work on CarouselView you can follow #4996

**Comment by akaruthethil-nlg** [comment]
@samhouts When this fix is expected? This is a critical fix as it affects the iOS part of the Carousel View.

**Comment by samhouts** [comment]
This was closed by #6686 and should be released as part of the latest 4.1.0 service release and 4.2.0-pre1. Thanks!
