### ISSUE TITLE
[Bug] Button.CornerRadius doesn't work on WPF

### ISSUE THREAD

**Issue by johannesegger** [xamarin/Xamarin.Forms#6556]
### Description
Setting `CornerRadius` on a `Button` doesn't do anything - the button is always rendered with sharp corners.

### Basic Information

- Version with issue: 4.0.0.497661
- Last known good version: -
- IDE: VSCode
- Platform Target Frameworks: 
  - WPF: 4.0.0.497661 
- Affected Devices: Laptop with Windows 10 x64

**Comment by twelvesix** [comment]
I am having the same issue.
