### ISSUE TITLE
[Bug] FontImageSource not working with MenuItem in Shell

### ISSUE THREAD

**Issue by anotherlab** [xamarin/Xamarin.Forms#6559]
### Description
Image does not show up for MenuItem in Shell when using FontImageSource
### Steps to Reproduce

1. Run the code in the reproduction link

or

1. Create new app using Shell
2. Add an icon font (see James Montemagno's [article](https://montemagno.com/using-font-icons-in-xamarin-forms-goodbye-images-hello-fonts/) as a reference)
3. Add a MenuItem to the Shell in XAML (code behind not tested)
3. Add a FontImageSource using the icon font to the MenuItem.IconImageSource

### Expected Behavior
You should see the specified icon image with the MenuItem text

### Actual Behavior
Empty space where the icon should be

### Basic Information

- Version with issue: 4.0.0.497661, 4.1.0.496342-pre2
- Last known good version: Unknown
- IDE: Visual Studio 2019 (Windows) 16.0.4
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: 9.0
  - UWP:  N?A
- Android Support Library Version: 28.0.0.1, also seen with 27.0.2.1
- Nuget Packages:  
  - Xamarin.Forms , 4.1.0.496342-pre2
  - Xamarin.Essentials, 1.1.0
 - Affected Devices: Android & iOS

### Screenshots
![](https://github.com/anotherlab/fontimagesourcemissinginmenuitem/blob/master/screenshots/menuitem%201.png?raw=true)

### Reproduction Link
[https://github.com/anotherlab/FontImageSourceMissingInMenuItem](https://github.com/anotherlab/FontImageSourceMissingInMenuItem)

**Comment by kennethbernstrom** [comment]
Is this related to my issue?

Firstly, i absolutely love XF 4!! Although i stumbled upon an issue regarding the FontImageSource in Shell FlyoutItem. It works totally fine when setting the FontAwesome icon in the Tab.Icon. But if i also want the same icon to display in the Flyout menu i have to have the FlyoutItem property FlyoutDisplayOptions set to "AsMultipleItems". If i set it to "AsSingleItem" the FontAwesome icon is a no show! :/

I have tried using a ItemTemplate as well, but the result is the same.
