### ISSUE TITLE
[Enhancement] Shell with TabBars which isn't in Flyout

### ISSUE THREAD

**Issue by Mohsnb** [xamarin/Xamarin.Forms#6565]
## Summary
Please add to possible to hide TabBars from Flyout items. What's the point of having a tab bar and exact same pages in the flyout hamburger menu? It's bad from UX view. And every XF example has it.

e.g.

```
<TabBar ShowInFlyout="false"/>
    <Tab .../>
    <Tab .../>
</TabBar>
```

thanks.

**Comment by PureWeen** [comment]
I think this was logged when there was a bug with TabBar because TabBars don't show up in the Flyout 

@Mohsnb please let me know if I'm misunderstanding your request
