### ISSUE TITLE
There is different behavior of page title at navigation bar of navigation page on use of titleview.

### ISSUE THREAD

**Issue by Awinesh** [xamarin/Xamarin.Forms#6574]
There is different behavior of page title at navigation bar of navigation page on use of titleview.
Page title is showing at navigation bar on UWP but it is not visible on Android device.

Step to reproduced:
Create multi platform project with master detail page.
Use titleview in a xaml of content page, set a title of this page.
Run UWP project. It will show title of page at navigation bar.
Run Android project. It will not show title of page at navigation bar.

### Expected Behavior
Do not show title at all platform or it will show for all platform.

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017
-Xamarin form: 4.1.0.483098-pre1

**Comment by samhouts** [comment]
@Awinesh  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Awinesh** [comment]
[SampleSearchbar.zip](https://github.com/xamarin/Xamarin.Forms/files/3377491/SampleSearchbar.zip)
i added a sample code.
You will see title on UWP but it it not showing in Android.

**Comment by samhouts** [comment]
@Awinesh This is expected behavior. Please see this note on the original TitleView PR:

>Since BackTitle, Title, TitleIcon, and TitleView all occupy the same space on the navigation bar, you can expect that there will be conflicts and limited space to support all of these properties at the same time. This will vary by platform and screen size. You may find that you can better achieve your desired design by using just TitleView instead of attempting to use a combination of properties. (#2586)

Thanks!
