### ISSUE TITLE
[Bug] iOS Keyboard.Numeric: On iPhone it is not possible to enter the minus sign.

### ISSUE THREAD

**Issue by omghb** [xamarin/Xamarin.Forms#6580]
### Description
I have set the Keyboard to the Numeric Keyboard for some Entry controls.
```XML
<Entry Keyboard="Numeric" ...
```

Wrong: The iPhone does not provide the minus sign in the numeric keyboard. 
Correct: The iPad behaves correct and shows a more complete numeric keyboard.

### Recommended fix:
https://github.com/xamarin/Xamarin.Forms/blob/6a2d2fb6f239fd62b0177b1bf770d8c5fc45c25a/Xamarin.Forms.Platform.iOS/Extensions/Extensions.cs#L35

Replace `DecimalPad` with `NumbersAndPunctuation`. With this setting the numeric keyboard is the same on iPad and iPhone.

### Workaround: Custom renderer

```C#
internal class MyEntryRenderer : EntryRenderer
{
    protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
    {
        base.OnElementChanged(e);
        if (Control == null) return;
        if (e.NewElement.Keyboard == Keyboard.Numeric)
        {
            Control.KeyboardType = UIKeyboardType.NumbersAndPunctuation;
        }
    }
}
```

### Context

- Version with issue: Xamarin.Forms 4.0.0.497661
- Platform Target Frameworks:
  - iOS: (SDK Version: Default) - VS2017 15.9.11
- Affected Devices:
  - iPhone

**Comment by samhouts** [comment]
@omghb This would be a breaking change, but we could add a platform specific option for it. Would you like to try to submit a PR? Thanks!

**Comment by samhouts** [comment]
Actually, since we're talking about doing this on both platforms (https://github.com/xamarin/Xamarin.Forms/issues/6579), it could be a new core property.

**Comment by omghb** [comment]
@samhouts 
- The issue #6579 sounds similar to this one but I believe that they are different when looking at the details.
- `Keyboard.Numeric` is inconsistent on iOS and Android
  - iOS: The [UIKeyboardType.DecimalPad](https://developer.apple.com/documentation/uikit/uikeyboardtype) is used which does **not** provide the sign key (minus) on the **iPhone**.
  - Android: NumberFlagSigned and NumberFlagDecimal are set. Thus, the sign key is included. https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.Android/Renderers/KeyboardExtensions.cs#L24
- My proposal should not be a breaking change as it replaces the reduced numeric keyboard layout with the more complete numeric keyboard layout on iOS. It affects only the iPhone as the iPad always uses the more complete numeric keyboard layout.
- Unfortunately, I do not have the time to develop a PR.

**Comment by yurkinh** [comment]
@samhouts  I have fix suggested by @omghb . Can I make PR or it's still under consideration?

**Comment by samhouts** [comment]
@yurkinh Please do. Thank you! :)

**Comment by bruzkovsky** [comment]
For anyone coming here looking for a fix, I wrote an Effect for this:

https://gist.github.com/bruzkovsky/62a669e460c8bc9b7770767e8742d992

It also adds a "Done" button to the right to close the keyboard.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
