### ISSUE TITLE
[Bug, iOS] Shell current tab action not update "Shell.CurrentState.Location"

### ISSUE THREAD

**Issue by Mabson** [xamarin/Xamarin.Forms#6581]
### Description
 When navigated to a detail route, we can pop detail page clicked on current tab option but Shell.CurrentState.Location not update, if navigate again in the same detail route it`s not possible.

### Steps to Reproduce

1. Clone Xanimals Sample.
2. Build on iOS
3. Click in Bears, Choose a bear , click again on Bears option on tabbed bar the page pop, if choose another bear not work anymore.

### Expected Behavior
If back in tabbed bar, updates the Shell.CurrentState.Location to "//animals/bears"
ShellNavigatingEventArgs.ShellNavigationSource == ShellNavigationSource.Pop

### Actual Behavior
If back in tabbed bar Shell.CurrentState.Location stay "//animals/bears/beardetails"
ShellNavigatingEventArgs.ShellNavigationSource == ShellNavigationSource.ShellSectionChanged

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.497.661

**Comment by rmarinho** [comment]
It actual a detail that iOS allows to click on "Bears" and it navigates back and Android doesn't.

**Comment by PureWeen** [comment]
Fixed

If you're still seeing this on 4.5 let me know and I can reopen
