### ISSUE TITLE
[Bug]  Editor Landscape Crash

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#6585]
Run repro, when in landscape, focus on the editor then hit the next button. The App crashes.

Android Only.

- Version with issue: Xamarin.Forms 4.0.0.497661
- IDE: Visual Studio 2019 16.1.3
- Android Support Library Version: 28.0.0.1

Tested on Simulator running Android 9 along with Galaxy S9 Plus

![crashgif](https://user-images.githubusercontent.com/29727003/59772060-fa1be480-92a2-11e9-8ea5-8b6ed8c2cd04.gif)

[EditorCrash.zip](https://github.com/xamarin/Xamarin.Forms/files/3306440/EditorCrash.zip)

06-19 14:42:39.547 E/AndroidRuntime(30121): java.lang.IllegalStateException: focus search returned a view that wasn't able to take focus!
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.widget.TextView.onKeyUp(TextView.java:8834)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.KeyEvent.dispatch(KeyEvent.java:3374)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.View.dispatchKeyEvent(View.java:13304)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v4.widget.NestedScrollView.dispatchKeyEvent(NestedScrollView.java:592)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1912)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:686)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1859)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.app.Activity.dispatchKeyEvent(Activity.java:3446)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:564)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6012)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5867)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5498)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5555)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8364)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8297)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8258)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4957)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.os.Looper.loop(Looper.java:214)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at android.app.ActivityThread.main(ActivityThread.java:6981)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at java.lang.reflect.Method.invoke(Native Method)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-19 14:42:39.547 E/AndroidRuntime(30121): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Unhandled Exception:

Java.Lang.IllegalStateException: <Timeout exceeded getting exception details>

**Comment by rmarinho** [comment]
This is fixed on 4.1.0.496342-pre2, i updated the sample and i don't have no crash, i do See "Done" instead of Next now
