### ISSUE TITLE
Android Crash - ObjectDisposedException Rendering Shadow with FramerRenderer

### ISSUE THREAD

**Issue by uptondev** [xamarin/Xamarin.Forms#6587]
### Description

I've developed a custom control that holds thumbnail images and horizontally scrolls. Once an image is tapped, the image becomes the "SelectedPage" and the full image is shown. Only in Android (and on both real and simulated devices) the app crashes if you go back and forth between 2 or more images a few times.

```
System.ObjectDisposedException
Cannot access a disposed object. Object name: 'Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer'.
------------------------
  at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <9ed4c1a7b8844cdcb5330cc881c1cd6a>:0 
  at Android.Support.V7.Widget.CardView.set_CardElevation (System.Single value) [0x00022] in <db49a6a89fc24f5db24db2da15164cc0>:0 
  at Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer.UpdateShadow () [0x00033] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\FrameRenderer.cs:272 
  at Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0002a] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\FrameRenderer.cs:230 

```
The thumbnails have a frame for highlighting the selection which I believe is what is failing. Please let me know if I am doing something incorrectly?

[Here is a full stack trace.](https://github.com/uptondev/ReproduceFRCrash/blob/master/CrashStackTrace.txt)

### Steps to Reproduce

1. Run the app
2. Click the Add button
3. Pick an image from the device image gallery
4. Repeat a few times to add more images
5. Tap the thumbnails back-n-forth to make it crash

### Expected Behavior
The application should show the full image in the preview and properly highlight the selected thumbnail with a border and shadow without crashing. 

### Actual Behavior
The application crashes with error.

### Basic Information

- Version with issue: Xamarin 4.0.0.497661
- Last known good version: Failed on Xamarin 3 so I upgraded to 4.0.0.497661 and it is still failing
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - Android: 9.0 (pie) Minimum API Level 21, Target API Level 28

- Android Support Library Version: Xamarin.Android. Support. v7
- Nuget Packages: (See test project)
- Affected Devices: Any Android
- I have LargeHeap = true in AssemplyInfo.cs
- Experimental Garbage collector is turned off in project properties
- Debug mode: Linker set to SDK libs only
- Under Android Build > Advanced: Java Heap Size = 4GB

### Reproduction Link

[Here is a full test project for reproducing the problem.](https://github.com/uptondev/ReproduceFRCrash)

Thanks for any assistance you can provide.

**Comment by uptondev** [comment]
Hmm... I don't get the error if I do not scale the images. In Android scaling is necessary or we run out of memory. In the test project I replaced `return ScaleToFitWidth(_path, Width);` with `return ImageSource.FromFile(_path); `to use the FULL SIZE image and it works.

Here is my code for scaling the images in case you see anything wrong:

```
/// <summary>
/// Scale and maintain bitmap aspect ratio given a desired width into an ImageSource
/// </summary>
/// <example>imgSrc = ImageService.ScaleToFitWidth(bitmapFilePath, 100);</example>
/// <param name="path">path to image file</param>
/// <param name="width">desired width of resulting image</param>
/// <returns>ImageSource</returns>
public static ImageSource ScaleToFitWidth(string path, int width)
{
    Bitmap b = BitmapFactory.DecodeFile(path);
    Bitmap bMap = ScaleToFitWidth(b, width);

    return ImageSource.FromStream(() =>
    {
        MemoryStream ms = new MemoryStream();
        bMap.Compress(Bitmap.CompressFormat.Png, 100, ms);
        ms.Seek(0L, SeekOrigin.Begin);
        return ms;
    });
}

/// <summary>
/// On a bitmap, scale and maintain aspect ratio given a desired width
/// </summary>
/// <example>Bitmap bmp = ImageService.scaleToFitWidth(bitmap, 100);</example>
/// <param name="b">source bitmap to scale</param>
/// <param name="width">desired width of resulting bitmap</param>
/// <returns></returns>
public static Bitmap ScaleToFitWidth(Bitmap b, int width)
{
    float factor = width / (float)b.Width;
    return Bitmap.CreateScaledBitmap(b, width, (int)(b.Height * factor), true);
}
```

**Comment by uptondev** [comment]
More: This is NOT related to image scaling. It still fails using full size images (i had to add 6 more images before crash).

However I am seeing the following in Application Output just before (and only before) the crash.  Its like my cached ImageSources are being GC'd or something:
```

[zygote] Explicit concurrent copying GC freed 10519(607KB) AllocSpace objects, 0(0B) LOS objects, 51% free, 1422KB/2MB, paused 589us total 5.716ms
[Mono] GC_TAR_BRIDGE bridges 852 objects 20761 opaque 6801 colors 589 colors-bridged 581 colors-visible 581 xref 74 cache-hit 0 cache-semihit 0 cache-miss 8 setup 0.03ms tarjan 2.90ms scc-setup 0.08ms gather-xref 0.01ms xref-setup 0.01ms cleanup 0.13ms
[Mono] GC_BRIDGE: Complete, was running for 30.31ms
[Mono] GC_MINOR: (Nursery full) time 13.38ms, stw 14.70ms promoted 1586K major size: 2496K in use: 1776K los size: 1024K in use: 460K
[zygote] NativeAlloc concurrent copying GC freed 2637(127KB) AllocSpace objects, 1(20KB) LOS objects, 52% free, 1410KB/2MB, paused 23.968ms total 111.790ms
[zygote] Checksum mismatch for dex base.apk
[zygote] Checksum mismatch for dex base.apk
```

**Comment by uptondev** [comment]
FYI, I tried swiping out the GC BRIDGE for the old one as [detailed here](https://docs.microsoft.com/en-us/xamarin/android/internals/garbage-collection#GC_Bridge_Options).  It had no effect.

**Comment by kvpt** [comment]
From the stacktrace it's caused by the OnElementPropertyChanged handler.
It is unsubscribed after the dispose of the element. The PR #6467 is supposed to correct this one too.
You can try this package which contains the corrections to confirm if it solve your issue or not.
[Xamarin.Forms.4.1.0.zip](https://github.com/xamarin/Xamarin.Forms/files/3311773/Xamarin.Forms.4.1.0.zip) (The nupkg is inside the zip)

**Comment by uptondev** [comment]
Unfortunately it is still failing with Xamarin 4.1.0. After the upgrade I did a "power" clean (manually deleted bin, obj folders, uninstalled app on simulators, restarted etc) and I am getting the same error message.  Thanks though..

**Comment by kvpt** [comment]
Ok thanks you for testing, it's means the issue is more complex than I thought.
I will try your reproduction sample to see if I reproduce it.

**Comment by uptondev** [comment]
Appreciate it. I noticed when I test it, I click back-n-forth between thumbnails, I pause for a bit, the GC steps in and runs (I see msg in output anyway), and then, on next click, I see the crash. Fails every single time.

**Comment by kvpt** [comment]
I reproduce the issue with your sample.
It's very strange, the Control seem to be disposed but his Dispose has never been called.
I will make more tests.

**Comment by uptondev** [comment]
Weird that CardElevation seems to get assigned to itself on line 270 in https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs

...and _defaultElevation doesn't get used.

**Comment by kvpt** [comment]
Ok, the problem is your HorizontalScrollList control.
As you do not use custom renderer, you don't have access to the underlying renderer, so you cannot dispose it and this cause a leak.
So two ways to solve this :
- Implement native custom renderer for this scenario (But i think it's better to wait for the collection view).
- Forcing the dispose with a custom renderer (This can work but it'is a more like a hack and dont solve the real problem, but can be used before collection view is stable enough)

The custom renderer for the solution two.
You can see that it is specific to the control you wrap in yout list, so it's very limited.

```csharp
[assembly: ExportRenderer(typeof(Frame), typeof(CustomFrameRenderer))]
namespace TestHScroll.Droid.Renderers
{
    public class CustomFrameRenderer : FrameRenderer
    {
        protected override void OnDetachedFromWindow()
        {
            base.OnDetachedFromWindow();

            Dispose(true);
        }
    }
}
```

**Comment by uptondev** [comment]
I used your code plus a constructor to get rid of the warning and now I see no border, no shadow, and the thumbs render about 70% of the time. Otherwise there is a blank spot where the thumb should be.

```
using System;
using Android.Content;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using TestHScroll.Droid.Renderers;

[assembly: ExportRenderer(typeof(Frame), typeof(CustomFrameRenderer))]
namespace TestHScroll.Droid.Renderers
{
    public class CustomFrameRenderer : FrameRenderer
    {
        public CustomFrameRenderer(Context context) :
            base(context)
        {
        }

        protected override void OnDetachedFromWindow()
        {
            base.OnDetachedFromWindow();
            Dispose(true);
        }
    }
}

```

**Comment by uptondev** [comment]
...but no more crash :) Thanks. I'm guessing I'll need to try your option #1 (complete renderer) since I need the shadows or some sort of selection indicator. Not sure how that is my control's fault but thank you for the workaround

**Comment by uptondev** [comment]
If my custom renderer is derived from AppCompat.FrameRenderer, then the shadow and border come back. But thumbs still occasionally do not render and a debug message (not from my code - maybe Xam4.1.0?) says "Image loading: Image load cancelled"
