### ISSUE TITLE
[Bug] [UWP] ComboBox IsEditable=true Prevents Mouse from Opening DropDown List

### ISSUE THREAD

**Issue by BK886** [xamarin/Xamarin.Forms#6589]
### Description
Created custom control to create an editable UWP ComboBox by setting the ComboBox IsEditable property to true. Tried to click on the DropDown arrow but the DropDown did not open. Hovering over the DropDown arrow did not change its state. All worked as expected with IsEditable is false.

```
  public class NativeEditableComboBoxRenderer : ViewRenderer<NativeEditableComboBox, ComboBox>
  {
OnElementChanged(ElementChangedEventArgs<NativeEditableComboBox> e)
    {
      base.OnElementChanged(e);

      if (Control == null && e.NewElement != null)
      {
        var comboBox = new ComboBox();
        
        // Note: Setting IsEditable prevents mouse from opening drop-down.
        comboBox.IsEditable = true;

        comboBox.Items.Add("Blue");
        comboBox.Items.Add("Green");
        comboBox.Items.Add("Red");
        comboBox.Items.Add("Yellow");

        SetNativeControl(comboBox);
      }
    }
```
### Steps to Reproduce

1. Create NativeEditableComboBoxRenderer : ViewRenderer<NativeEditableComboBox, ComboBox> with a ComboBox as the native control. Set its IsEditable property to true. Populate its Items, as shown above.
2. Create corresponding NativeEditableComboBox.
3. Add NativeEditableComboBox to a test page.
4. Run test app.
5. Use mouse to open the DropDown.
6. Try typing into expected editable area.

### Expected Behavior
1. DropDown opens.
2. Text box is editable.

### Actual Behavior
1. Mouse hover over DropDown arrow does not highlight arrow.
2. Mouse click does not open DropDown.
3. Text box area is not editable.
4. Using up and down arrow keys does open DropDown.

### Basic Information
- Requires Windows 10, version 1809 (10.0; Build 17763)
- Version with issue: 3.6.0.344457
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  17763 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@BK886  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by BK886** [comment]
@samhouts I created a stand-alone test app on a different development system and the editable ComboBox works as expected. Also retried in our app and it also works as expected on other development systems. Something with my original test PC is causing the reported issue. You may close this issue.
