### ISSUE TITLE
[Bug] XF 4.0 "No property, bindable property, or event found"

### ISSUE THREAD

**Issue by bnserig** [xamarin/Xamarin.Forms#6600]
### Description
I can't compile my solution when I upgrade to Xamarin Forms 4.0. It is caused by a custom control I created with a bindable property of type Xamarin.Forms.Easing.
I appears only when I use it in XAML. There is no problem when I use it in code.

### Steps to Reproduce

1. Create a new Xamarin Forms app with Visual Studio 2019
2. Create a bindable property of type Xamarin.Forms.Easing in a custom control
3. Use this custom control in XAML
4. Upgrade to Xamarin Forms 4
5. Compile

### Expected Behavior
It should compile

### Actual Behavior
Compile failed
error : Position 14:17. No property, bindable property, or event found for 'ProgressEasing', or mismatching type between value and property.

### Basic Information

- Version with issue: Xamarin Forms 4.0.0.497661
- Last known good version: last Xamarin Forms 3.6.0.344457
- IDE: Visual Studio 2019 16.1.3

### Code
```
public class AnimatedProgressBar : ProgressBar {
...
  public static BindableProperty ProgressEasingProperty = BindableProperty.CreateAttached(nameof(ProgressEasing), typeof(Easing), typeof(AnimatedProgressBar), Easing.SinIn);

  public Easing ProgressEasing {
    get => (Easing)GetValue(ProgressEasingProperty);
    set => SetValue(ProgressEasingProperty, value);
  }
...
}
```

```
<local:AnimatedProgressBar
  x:Name="progressBar"
  ProgressAnimation="True"
  ProgressAnimationTime="500"
  ProgressColor="Red"
  ProgressEasing="BounceOut"
  VerticalOptions="Center"
  WidthRequest="300" />
```

**Comment by samhouts** [comment]
@bnserig  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by bnserig** [comment]
[TestCase.zip](https://github.com/xamarin/Xamarin.Forms/files/3313197/TestCase.zip)

**Comment by samhouts** [comment]
It looks like we added better error reporting when a XAML type doesn't have a matching converter (#5104). It may have compiled before this, but I wonder if it actually worked as intended. It works in code because there's an implicit operator on Easing, but XAML needs more guidance. :) 

It looks like we never created a converter for Easing, since animation is a tricky thing to define in XAML. Have you tried created a type converter yet? There's a great guide on https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters.

**Comment by bnserig** [comment]
Hi @samhouts,
How can I associate a converter on a value ? Do you have an example ?

I tested with a object binded in my viewmodel, it works perfectly without converter.

**Comment by samhouts** [comment]
@bnserig Can you show me the code you tried that isn't working? Thanks!

**Comment by bnserig** [comment]
@samhouts It's in the project I attached previously (TestCase.zip)
I don't know how to associate a converter with a static value in XAML.

**Comment by bnserig** [comment]
Any news about this bug ?

**Comment by PureWeen** [comment]
@bnserig try creating a TypeConverter


https://forums.xamarin.com/discussion/37325/how-to-create-a-size-property-for-a-custom-control-that-is-configurable-in-xaml

**Comment by Maxima078** [comment]
Why don't you just bind it to the value you want? Exemple for `BounceOut`:

`ProgressEasing={Binding Source={x:Static Easing.BounceOut}}`

**Comment by bnserig** [comment]
@Maxima078 I have the same error.

@PureWeen Works great with a TypeConverter. Thanks.
