### ISSUE TITLE
[Enhancement] Checked/Toggle- and UnChecked/UnToggled Commands for CheckBox och Switch

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#6606]
## Summary
Add support to use Commands with CheckBox and Switch.

### CheckBox
**Properties to add:** 

- CheckedCommand:ICommand
- UnCheckedCommand:ICommand
- CheckedCommandParameter:object

**Fields to add:** 
- CheckedCommandProperty:BindableProperty
- UnCheckedCommandProperty:BindableProperty
- CheckedCommandParameterProperty:BindableProperty

### Switch
**Properties to add:** 
- ToggledCommand:ICommand
- UnToggledCommand:ICommand
- ToggleCommandParameter:object

**Fields to add:** 
- ToggledCommandProperty:BindableProperty
- UnToggledCommandProperty:BindableProperty
- ToggledCommandParameterProperty:BindableProperty

## Intended Use Case
I got the idea for this when I created a list with filter values and I wanted an easy way to handle toggle and untoggled in my ViewModel without having to create a property for each filter value. This also makes it easier if you have a dynamic list of values.

I needed it for Switch, but both Switch and CheckBox have similar use case so I think it is relevant to implement this for both of them.

Below is an example of how it can be used:

**The View**
```xml
<Grid>
     <Grid.RowDefinitions>
          <RowDefinition Height="Auto" />
          <RowDefinition Height="Auto" />
          <RowDefinition Height="Auto" />
          <RowDefinition Height="Auto" />
     </Grid.RowDefinitions>

     <Label  Text="Audi" />
     <Switch HorizontalOptions="End" ToggledCommandParameter="audi" ToggledCommand="{Binding AddFilterValue}" UnToggledCommand="{Binding RemoveFilterValue}" />

      <Label Grid.Row="1" Text="BMW" />
     <Switch Grid.Row="1" HorizontalOptions="End" ToggledCommandParameter="bmw" ToggledCommand="{Binding AddFilterValue}" UnToggledCommand="{Binding RemoveFilterValue}" />

     <Label Grid.Row="2" Text="Mercedes" />
     <Switch Grid.Row="2" HorizontalOptions="End" ToggledCommandParameter="mercedes" ToggledCommand="{Binding AddFilterValue}" UnToggledCommand="{Binding RemoveFilterValue}"/>

     <Label Grid.Row="3" Text="Porsche" />
     <Switch Grid.Row="3" HorizontalOptions="End" ToggledCommandParameter="porsche" ToggledCommand="{Binding AddFilterValue}" UnToggledCommand="{Binding RemoveFilterValue}" />
</Grid>
```
**The ViewModel**
```csharp
private List<string> brandFilter = new List<string>();

public ICommand AddFilterValue => new Command<string>((parameter) => brandFilter.Add(parameter));

public ICommand RemoveFilterValue => new Command<string>((parameter) => brandFilter.Remove(parameter));
```

**Comment by dhindrik** [comment]
I have got some questions when I have discussed this with other developers in our user group in Sweden. And one questions is why we can't just have one command properties instead of two. The answer to that is that I want to pass the key, in my example about the brand of the car, if we want to have both the parameter value and the value of IsToggled/IsChecked we have to create a separate type for that, I think that is ok  if we create our own custom control in our own project, but in Xamarin.Forms Core it is not ok because it will differ how command parameters works in general. 

I also got a suggestion to add an InitialValue property as well. But if we do so we will have to create a property to bind it to for each checkbox/switch or create a ViewModel for each item. If we have a similar case like in my example above. If we already have those properties we can instead just bind to IsChecked/IsToggled and add logic to the set method.

**Comment by dhindrik** [comment]
I also did the first draft of an implementation, https://github.com/dhindrik/Xamarin.Forms/commit/b886f03607c5848745e24ae377ed08d45c573c96

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
