### ISSUE TITLE
[XForms] AutomationID not shown correctly in the inspect.exe 

### ISSUE THREAD

**Issue by Yuvaraj-007** [xamarin/Xamarin.Forms#6607]
### Description
AutomationID not getting set correctly in the SfListView control only in the inspect.exe application and shown correctly in the output screen.

### Steps to Reproduce

1. Run the Sample.
2. Click the each item to check the AutomationID on the inspect.exe app.
3. Note : In the same check same item AutomationID shows correctly in the output screen.

### Expected Behavior
Correctly shown the AutomationID in the inspect.exe

### Actual Behavior
Wrongly shown the AutomationID in the inspect.exe

### Basic Information

- Version with issue: XF - 3.6
- Last known good version: No
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  10.0.18362.0
- Nuget Packages: latest 3.6
- Affected Devices: UWP

### Reproduction Link
Sample  link - https://www.syncfusion.com/downloads/support/directtrac/general/ze/Automation283091339

### Comments
Using below path to run the inspect.exe tool
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86

**Comment by samhouts** [comment]
@Yuvaraj-007 This does work with the Xamarin.Forms ListView, so I am not sure how to help you. It looks like you're not passing something through properly in your ListView. Thanks!
[Issue6607_2.zip](https://github.com/xamarin/Xamarin.Forms/files/3375526/Issue6607_2.zip)
