### ISSUE TITLE
[Bug] Make building easier on Windows by setting PowerShell execution policy

### ISSUE THREAD

**Issue by Eilon** [xamarin/Xamarin.Forms#6617]
### Description

Executing arbitrary PowerShell files typically results in an error.

By adding a `CMD` file that calls the PowerShell file, it can be executed with an execution policy that allows it to be run. This is what other repos such as ASP.NET Core do: [`build.cmd`](https://github.com/aspnet/AspNetCore/blob/master/build.cmd) launches PowerShell with an execution policy that can run [`build.ps1`](https://github.com/aspnet/AspNetCore/blob/master/build.ps1).

### Steps to Reproduce

1. Clone repo on Windows machine
2. Try to run `./build.ps1`

### Expected Behavior

It should build.

### Actual Behavior

You get an error:

```
PS C:\GitHub\Xamarin.Forms> .\build.ps1
.\build.ps1 : File C:\GitHub\Xamarin.Forms\build.ps1 cannot be loaded. The file C:\GitHub\Xamarin.Forms\build.ps1 is
not digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\build.ps1
+ ~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

### Basic Information

N/A

**Comment by samhouts** [comment]
closed by #6755
