### ISSUE TITLE
[iOS] Crash when creating a CollectionView inside a CollectionView

### ISSUE THREAD

**Issue by MrMayTwenty** [xamarin/Xamarin.Forms#6620]
### Description
Creating a CollectionView within a CollectionView crashes on iOS

### Steps to Reproduce

1. Create a xaml page with a CollectionView inside a CollectionView
2. Create a class for the child containing sample properties
3.  Create a class for the parent containing sample properties and a list of the child class
4.  Populate the data using Binding
5. Run the app

### Expected Behavior
Page is created and CollectionView parent is populated along side the CollectionView child

### Actual Behavior
App freezes and throws a message on the application output
*** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3698.103.12/UICollectionView.m:6165

### Basic Information

- Version with issue: Xamarin.Forms 4.0.0.497661
- Last known good version:
- IDE: Visual Studio Mac 2019
- Platform Target Frameworks: 
  - iOS:  12.2

**Comment by samhouts** [comment]
@MrMayTwenty  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by adrianknight89** [comment]
What's the use case for nesting CollectionView inside another? We do need to make sure nesting a CarouselView works though.

**Comment by istern** [comment]
If you have a horizontal list (collectionview) with a  vertical list (collectionview) for each entry is something I could see used. 
I'm also getting an error for this setup.

**Comment by samhouts** [comment]
@istern  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by istern** [comment]
@samhouts sure https://github.com/istern/CollectionViewBug?files=1  it might not be the most efficient way but I shows the bug

**Comment by americofreitasjr** [comment]
Just to corroborate with @MrMayTwenty, I'm having a similar problem. Android ok, but in IOS with error.

**Comment by Elashi** [comment]
I am having the same problem a horizontal collection view inside a vertical collection view. It works in Android but it does not work in iOS.  Nothing is displayed.

**Comment by ftpps** [comment]
I have a similar problem when ListView is hosted in CarouselView via DataTemplate on iOS. any suggestion?

**Comment by StevenGranados** [comment]
This isn't fixed in 4.2.0. If you try out the repro in the following:
https://github.com/xamarin/Xamarin.Forms/issues/7006
it still crashes on adding a new item.

**Comment by StevenGranados** [comment]
Also not fixed in the nightly.

**Comment by StevenGranados** [comment]
> Also not fixed in the nightly.

But works in the 4.4.0 nightly now. :)

**Comment by EvoPulseGaming** [comment]
Sort of the same, using 4.4.0.991210-pre2 on ios 9.3.5
Resolved pending breakpoint at 'NewWorkOrder.xaml.cs:99,1' to void EvoTracker.Pages.NewWorkOrderPage.<>c__DisplayClass12_0.<Picker_id_property_SelectedIndexChanged>b__0 () [0x00001].
2019-11-17 03:13:18.802 EvoTracker.iOS[203:8301] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UICollectionView.m:4625

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x1bd15e1 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_dump_native_crash_info
	0x1bc9c4b - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_handle_native_crash
	0x1bd45ab - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_sigsegv_signal_handler_debug
	0x210ea077 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1 - Unknown
	0x1bc843f - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : unwinder_unwind_frame
	0x1bc9387 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_handle_exception_internal
	0x1bc8637 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_handle_exception
	0x1bc083b - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_arm_throw_exception
	0x4e6ba8 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : throw_exception
	0x538534 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : ObjCRuntime_Runtime_throw_ns_exception_intptr
	0x5ea458 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : wrapper_native_to_managed_ObjCRuntime_Runtime_throw_ns_exception_intptr
	0x1cd2944 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : xamarin_throw_ns_exception
	0x1cd5918 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : _ZL17exception_handlerP11NSException
	0x213bbc57 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>
	0x20b5709f - /usr/lib/libobjc.A.dylib : <redacted>
	0x20b48e17 - /usr/lib/libc++abi.dylib : <redacted>
	0x20b488f9 - /usr/lib/libc++abi.dylib : __cxa_increment_exception_refcount
	0x20b56f5f - /usr/lib/libobjc.A.dylib : objc_exception_rethrow
	0x212cb2af - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x212cb015 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunInMode
	0x228bbac9 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x2599f189 - /System/Library/Frameworks/UIKit.framework/UIKit : UIApplicationMain
	0x5e8d5c - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr
	0x554688 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : UIKit_UIApplication_Main_string___intptr_intptr
	0x55460c - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : UIKit_UIApplication_Main_string___string_string
	0x127308 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : EvoTracker_iOS_Application_Main_string__
	0x4a9de8 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr
	0x1bd7ad3 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_jit_runtime_invoke
	0x1c4eceb - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_runtime_invoke_checked
	0x1c52c33 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_runtime_exec_main_checked
	0x1bc05a9 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : mono_jit_exec
	0x1ce78fc - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : xamarin_main
	0x1271e1 - /var/containers/Bundle/Application/1CC0232E-C4B6-4CF9-BE87-6BC18F70C880/EvoTracker.iOS.app/EvoTracker.iOS : main
	0x20f73873 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1bc7752):0x1bc7742  1c bf da f8 0c 10 88 42 06 d0 b1 6b 81 42 22 bf  .......B...k.B".
0x1bc7752  00 68 20 f0 03 00 28 60 d8 f8 04 00 
18 b1 c1 7d  .h ...(`.......}
0x1bc7762  11 f0 12 0f 3c d0 d8 f8 00 30 00 22 d7 f8 0c a0  ....<....0."....
0x1bc7772  b3 fa 83 f0 41 09 00 20 02 2b 34 46 02 bf 00 23  ....A.. .+4F...#

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
=================================================================
The app has been terminated.

**Comment by EvoPulseGaming** [comment]
I was forced to use the 4.4.0 pre2 due to a bug with release version of android, and at the moment this outdated 32bit armv7 device is my testing device.
