### ISSUE TITLE
[Enhancement] Device.OpenUri to return result value of OS dependent call

### ISSUE THREAD

**Issue by ish-1313** [xamarin/Xamarin.Forms#6621]
## Summary
Currently Device.OpenUri is void. it will be nice if it returns the result value of underline call

## Intended Use Case
below is the code which tries to open FB app with the link to facebook page or group and if fails, then open link in browser . 

`  try
            {
                Device.OpenUri(fb);
            }
            catch
            {
                Device.OpenUri(u);
            }`

on android, trying to use unsupported protocol will fire an exception , but on IOS, openURL will return false if URL cant be opened and you can't distinguish was URL opened or not . in other native ios project  i use

`  if (!   [[UIApplication sharedApplication] openURL:[NSURL URLWithString:deeplink]])
     {
         [[UIApplication sharedApplication] openURL:[NSURL URLWithString:fbpage]];
     }`

it will be nice if in Xamarin.Forms.Platform.iOS/Forms.cs
public void OpenUriAction(Uri uri) would change to bool (or object) to get return value from 
UIApplication.SharedApplication.OpenUrl(url);

**Comment by andreinitescu** [comment]
@ish-1313 I had a similar issue and I had to create my own service. I made a PR for this.

**Comment by jfversluis** [comment]
Because #6844 probably will be merged soon this won’t have any use anymore. Therefore closing this one. You probably want to look into the Open Browser functionality of Xamarin Essentials: https://docs.microsoft.com/en-us/xamarin/essentials/open-browser
