### ISSUE TITLE
Custom controls with skiasharp do no get rendered in Android Previewer

### ISSUE THREAD

**Issue by BenBtg** [xamarin/Xamarin.Forms#6624]
### Description
Custom controls with skiasharp do no get rendered in Android Previewer

### Steps to Reproduce

1. Create a Forms App
2. Create a custom control and that draws its content with SkiaSharp
3. Add custom control to a page
4. View in previewer

### Expected Behavior
Custom control is and it's drawn content appears in Android Previewer
### Actual Behavior
Custom control is not rendered in Android previewer.
Appears fine on iOS previewer.

### Basic Information

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.1.1 (build 27)
Installation UUID: 7534b1b8-af1c-4acd-b8ed-2e97f685e56a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.4
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.2.203/Sdks
SDK Versions:
	2.2.203
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Enterprise)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Enterprise)
Commit: HEAD/d0b48056f
Android SDK: /Users/benbtg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/benbtg/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 801010027
Git revision: ce34f6838e6457d0e7d5991a1a693415e6fcae07
Build date: 2019-06-19 19:52:58+00
Build branch: release-8.1
Xamarin extensions: 5104b76623e0df8e5f763f87d170279c0b788e89

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.HotReload 1.0.0.2774591

### Screenshots

<img width="1151" alt="Screenshot 2019-06-21 at 12 28 56" src="https://user-images.githubusercontent.com/70525/59919774-450f3680-9420-11e9-8ed3-d9d924ba5c80.png">
<img width="1160" alt="Screenshot 2019-06-20 at 20 52 40" src="https://user-images.githubusercontent.com/70525/59919804-57897000-9420-11e9-8b47-6ec56e7a0205.png">

### Reproduction Link

> VS bug [#935547](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935547)

**Comment by samhouts** [comment]
@BenBtg  Can you please attach a small project that demonstrates this issue? Does this happen both before and after a build? Thanks!

**Comment by jamesmontemagno** [comment]
This is a known limitation: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/render-custom-controls#skiasharp-controls

**Comment by samhouts** [comment]
Thanks, @jamesmontemagno ! I'll go ahead and close this.
