### ISSUE TITLE
[Bug] CarouselView ScrollToRequested Event - Item is always Null

### ISSUE THREAD

**Issue by ahoefling** [xamarin/Xamarin.Forms#6626]
### Description
The CarouselView has an event `ScrollToRequested` which fires when the `ScrollTo()` method is invoked or the user swipes on the CarouselView. This event is useful for retrieving information such as the selected item.

To provide context here is the event args for this event:
```c#
class ScrollToRequestEventArgs : EventArgs
{
    public ScrollToMode Mode { get; }
    public ScrollToPosition ScrollToPosition { get; }
    public bool IsAnimated { get; }
    public int Index { get; }
    public int GroupIndex { get; }
    public object Item { get; }
    public object Group { get; }
}
```

### Steps to Reproduce

1. Create a CarouselView
2. Add event listener for `ScrollToRequested`
3. Invoke `ScrollTo()` on the control

### Expected Behavior

* `Item` contains the newly selected current item

### Actual Behavior

* `Item` is null

### Event Listener Snippet
```c#
private void OnScrollTo(object sender, ScrollToRequestEventArgs e)
{
    // e.Item is null when it should contain an instance of the
    // selected item
}
```

### Basic Information

- Version with issue: 4.0.0.471375
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  Not Tested
  - Android: API 28
  - UWP:  Not Tested
- Android Support Library Version: 28.0.0.1
- Nuget Packages: N/A
- Affected Devices: 

### Screenshots
Not Applicable

### Reproduction Link
Can provide if requested

**Comment by samhouts** [comment]
@ahoefling  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ahoefling** [comment]
I haven't had chance to put together a sample project, but I will get back to this and create one

**Comment by samhouts** [comment]
@ahoefling Thanks! We'll look for it.

**Comment by samhouts** [comment]
@ahoefling  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
