### ISSUE TITLE
[Bug] CarouselView ScrollToRequested Event - Index is base 1 and not base 0

### ISSUE THREAD

**Issue by ahoefling** [xamarin/Xamarin.Forms#6627]
### Description
The CarouselView has an event `ScrollToRequested` which fires when the `ScrollTo()` method is invoked or the user swipes on the `CarouselView`. This event is useful for retrieving information such as the selected index.

Typically when working arrays or any type of collection the index or counter is handled as base 0. This means the first item in the collection is 0 and the last item is the length of the collection minus 1. 

When inspecting the `EventArgs` on the `ScrollToRequested` event the index is base 1 meaning if I have 2 items in my collection the last item is 2 when I would expect it to be 1.

I am not sure if this is by design and if it is, I would recommend we document the Index on the `ScrollToRequestedEventArgs`

### Steps to Reproduce

1.  Create CarouselView
2.  Add Event Listener for `ScrollToRequested`
3.  Invoke `ScrollTo()` on the control

### Expected Behavior

* The `Index` contains the position in the collection at base 0. For example if there are 3 items in the collection and we are at the 2nd item the `Index` should be `1`.

### Actual Behavior

* The `Index` contains the position in the collection at base 1. For example if there are 3 items in the collections and we are at the 2nd item the `Index` is `2`.

### Basic Information

- Version with issue: 4.0.0.471375
- Last known good version: Not Applicable
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  Not Tested
  - Android: API 28
  - UWP:  Not Tested
- Android Support Library Version: 28.0.0.1
- Nuget Packages: Not Applicable
- Affected Devices:

### Screenshots
Not Applicable

### Reproduction Link
Can provide one if requested

**Comment by samhouts** [comment]
@ahoefling  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ahoefling** [comment]
I haven't had chance to put together a sample project, but I will get back to this and create one

**Comment by samhouts** [comment]
@ahoefling Thanks! We'll look for it.

**Comment by samhouts** [comment]
@ahoefling  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
