### ISSUE TITLE
[Enhancement] Change CollectionView SelectionMode to 4 modes

### ISSUE THREAD

**Issue by humhei** [xamarin/Xamarin.Forms#6630]
## Summary
Currently CollectionView SelectionMode has three states
{None,
 Single,
 Multiple
} 

UWP have four selection mode state
{
 None,
Single
Multiple,
Extend,
}
![image](https://user-images.githubusercontent.com/25994449/59890094-e935b500-9401-11e9-8880-f7a20a404245.png)

![image](https://user-images.githubusercontent.com/25994449/59890104-fbafee80-9401-11e9-93cd-bfd714f13b9c.png)

I think Four state in Android and IOS are also useful
Just take a look at the File explorer
![image](https://user-images.githubusercontent.com/25994449/59890457-8ba26800-9403-11e9-95ff-bb81dee57716.png)

## API Changes

{None,
 Single,
 Multiple
} 
To 
{
 None,
Single
Multiple,
Extended,
}

## My willing
I am happy to implent this feature in UWP side.
Will keep IOS and Android not supported

**Comment by hartez** [comment]
`ListViewSelectionMode.Extended` requires that a modifier key be pressed; it only makes sense for devices with a keyboard attached. 

I can imagine how this might work for an Android or iOS device with a keyboard attached, but I'm wondering how many people would use it.

**Comment by humhei** [comment]
Yes.
Closed it.
