### ISSUE TITLE
Live / Hot Reload

### ISSUE THREAD

**Issue by john-larson** [xamarin/Xamarin.Forms#6633]
Are there any **"SHORT TERM"** plans to implement a live reload (aka hot reload) feature for Xamarin.Forms that is comparable to what Flutter or React Native does? Including reloading of both Xaml and C# code of course (just xaml would not be sufficient). Long development cycle is a major problem for mobile application development and if this is not in your short term roadmap , it will certainly affect my decision of choosing this platform.

P.S. Is there a place where current/potential users of your platform can vote on feature requests? It might help you greatly in guiding your efforts towards what the community expects from you.

**Comment by pauldipietro** [comment]
We are continuously listening to user feedback regarding the development loop when using Xamarin.Forms, and investigations are always ongoing. Issues here are more or less strictly focused on the Xamarin.Forms SDK, and I would suggest using the feedback tool in VS or [Developer Community](https://developercommunity.visualstudio.com/) for suggesting features. You can also email me at paul.dipietro@microsoft.com with any further feedback about Xamarin.Forms. Thanks!

**Comment by john-larson** [comment]
@pauldipietro Thanks for the guidance. 
Here is the link to the request I created in case someone stopped by this thread: https://developercommunity.visualstudio.com/idea/618119/xamarinforms-live-hot-reload.html

**Comment by john-larson** [comment]
Xamarin team announced that they are working on the hot reload of Xaml and are in the preview stage. So the request for Xaml and C# hot reload has been split into two separate requests:

https://developercommunity.visualstudio.com/idea/618119/xamarinforms-live-hot-reload.html --> status has been changed to "Completed-Preview" and Pierce Boggan of MS stated that they will soon be sharing a roadmap for the final release, which will also be available on the official VS Roadmap page (https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap).

https://developercommunity.visualstudio.com/idea/650684/c-hot-reload-xamarin.html --> This is the new request created specifically for the hot reload of C#. You can vote for this one in order to help them prioritize the request.
