### ISSUE TITLE
[Enhancement] Ability to use design time data at runtime

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#6639]
## Summary
I would like to be able to use [design time data](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/design-time-data) at runtime of my application. My rationale is that I usually start my application with no backend services, no data, and just mock dummy data in the UI. I can use the previewer today to see it inside the IDE, but when I run the application I can't use this data and I would have to drop off the d: on all of the fields to get it to work. This is doable, but as soon as I start putting in real data into the app I still want to use the design data and I would prefer to not to have to swap things over again.
The reason I would like this is because I desire to be able to ship a prototype off to clients. 

## API Changes
There are two ways to go about this... 

1.) Let developers set: DesignMode.IsDesignModeEnabled = true;  in the main constructor for the app
2.) Create an API to do it on a per page/control basis. 

## Intended Use Case
See design time data at runtime.

**Comment by adamhill** [comment]
My caveat is that I would _like_ to override this somehow on a per container / control / field basis.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
