### ISSUE TITLE
Picker Dialog - System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PaulsonMac** [xamarin/Xamarin.Forms#6642]
### Steps to Reproduce
Click the custom picker and navigate to another page using navigation tabs before the pop-up dialog is opened, crashes the app
(OR) Open the dialog and let the app go background and then return to the app

### Stack Trace
```
IPickerRenderer.OnClick>b__1 (System.Object s, Android.Content.DialogClickEventArgs a)
IDialogInterfaceOnClickListenerImplementor.OnClick (Android.Content.IDialogInterface dialog, System.Int32 which)
IDialogInterfaceOnClickListenerInvoker.n_OnClick_Landroid_content_DialogInterface_I (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_dialog, System.Int32 which)
(wrapper dynamic-method) System.Object.150(intptr,intptr,intptr,int)
```

### Basic Information

- Version with issue: Xamarin.Forms 3.4.0.1029999
- IDE: VS Communit 2017 v15.9.11
- Platform Target Frameworks:
  - Android: Android 9.0
- Android Support Library Version: Xamarin.Android.Support.v7.AppCompat (v27.0.2.1) and Xamarin.Android.Support.v4 (v27.0.2.1)
- Affected Devices: Many different devices

### Another Reference

https://stackoverflow.com/questions/51218563/xamarin-forms-droid-custom-pickers-dialog-causing-exception-object-referenc

### One kind request

Crash Issue is with the live app, kindly assist asap. Thanks

**Comment by PaulsonMac** [comment]
Is there any workaround for this fix..?

**Comment by kvpt** [comment]
Do you use FormsApplicationActivity or FormsAppCompatActivity ?

Also, can you provide a reproduction exemple ?

**Comment by PaulsonMac** [comment]
Hi kevin, I'm using FormsAppCompatActivity. I think now I'm not in a state to provide the repo. But I'll try anyways. If possible, can you repro with a dummy project with the following steps:

**Comment by PaulsonMac** [comment]
Please check my EDIT

**Comment by kvpt** [comment]
My basic reproduction doesn't seem to have this issue.
![case1](https://user-images.githubusercontent.com/1446221/60016367-4d68ab00-9686-11e9-803b-538663ca69da.gif)
![case2](https://user-images.githubusercontent.com/1446221/60016368-4d68ab00-9686-11e9-8432-25edd2bbee75.gif)

Code of the page :
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Issues.App.MainPage">
    <ContentPage Title="Tab1">
        <Picker Title="Test">
            <Picker.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>1</x:String>
                    <x:String>2</x:String>
                    <x:String>3</x:String>
                    <x:String>4</x:String>
                    <x:String>5</x:String>
                </x:Array>
            </Picker.ItemsSource>
        </Picker>
    </ContentPage>
    <ContentPage Title="Tab2">
        <Label Text="Empty" />
    </ContentPage>
    <ContentPage Title="Tab3">
        <Label Text="Empty" />
    </ContentPage>
</TabbedPage>
```

Also I use Xamarin Forms 3.6.0 in my repro app.
Is there a reason you use the 3.4.0 version ?

**Comment by PaulsonMac** [comment]
Thanks for checking Kevin..!
Did you choose any options in that popup, when the background page is not the page that has this picker..?? Because when I dismissed the dialog by clicking outside the dialog window, I didnt get a crash, but the new navigated page just appeared..!!

**Comment by andreinitescu** [comment]
@PaulsonMac Can I suggest you attach a reproduction sample app?

**Comment by PaulsonMac** [comment]
Hi @AndreiMisiukevich, I'm very sorry, I couldnt do this right now, held up with another important work.

**Comment by PaulsonMac** [comment]
My stack trace on debugging this crash issue showed line 133 on Android PickerRenderer. I think the problem seems to be with the Context that should have a null check..!

**Comment by kvpt** [comment]
It'es very strange, you say you use Xamarin Forms 3.4.0 and AppCompat.

So it' s this line : https://github.com/xamarin/Xamarin.Forms/blob/f5dce54a7f969a4602928c53806e74f20ed65402/Xamarin.Forms.Platform.Android/AppCompat/PickerRenderer.cs#L133

But it seems that you use the legacy renderer, here :
https://github.com/xamarin/Xamarin.Forms/blob/f5dce54a7f969a4602928c53806e74f20ed65402/Xamarin.Forms.Platform.Android/Renderers/PickerRenderer.cs#L133

And in this case it's the ElementController which is null.

Do you use a custom renderer for this picker ?

**Comment by PaulsonMac** [comment]
Yes, I use a custom renderer.. But may be I saw the wrong PickerRenderer file. But all details are correct

**Comment by kvpt** [comment]
Ok, so I think the problem is that you inherit the wrong renderer and use the legacy one instead of the AppCompat one.
Can you provide the custom renderer code ?

**Comment by PaulsonMac** [comment]
```
using XYZProjectName.Controls;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using XYZProjectName.Droid.Renderers;
using Color = Android.Graphics.Color;
using System;
using Android.Content;
using Android.Graphics;
using Android.OS;

[assembly: ExportRenderer(typeof(BindablePicker), typeof(CustomPickerRenderer))]
namespace XYZProjectName.Droid.Renderers
{
    class CustomPickerRenderer : PickerRenderer
    {
        BindablePicker element;

        public CustomPickerRenderer(Context context) : base(context)
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            try
            {
                base.OnElementChanged(e);

                element = (BindablePicker)Element;

                if (Control != null)
                {
                    if (element != null)
                    {
                            //Set dropdown underline color
                            if (Build.VERSION.SdkInt >= BuildVersionCodes.Lollipop)
                                Control.BackgroundTintList = Android.Content.Res.ColorStateList.ValueOf(Color.Transparent);
                            else
                                Control.Background.SetColorFilter(Color.Transparent, PorterDuff.Mode.SrcAtop);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```

**Comment by kvpt** [comment]
Try to replace the using
**Xamarin.Forms.Platform.Android** 
by 
**Xamarin.Forms.Platform.Android.AppCompat**

**Comment by PaulsonMac** [comment]
Sorry.. but I think changing this won't help - See the below link that was referenced in the SO link I mentioned in this issue - https://stackoverflow.com/questions/51218563/xamarin-forms-droid-custom-pickers-dialog-causing-exception-object-referenc

**Comment by PaulsonMac** [comment]
I'm using FormsAppCompatActivity only as I told earlier

**Comment by PaulsonMac** [comment]
```
Try to replace the using
Xamarin.Forms.Platform.Android
by
Xamarin.Forms.Platform.Android.AppCompat
```

So, can I use this now, will this cause any other problems for my project solution..?

**Comment by kvpt** [comment]
You use FormsAppCompatActivity so the implicit renderer used are AppCompat by default.
But if you reference explicitly a legacy renderer, it the renderer that will be used.
The AppCompat renderer version is the version to use if you use AppCompat backend in all case.

**Comment by PaulsonMac** [comment]
Ok, thanks very much for your support, I'll try modifying that and get back to you soon. 👍

**Comment by PaulsonMac** [comment]
Kevin, I modified the renderer to AppCompat... but I'm not comfortable with the picker style, it displays a lot of options - I have many items in the picker. Can I have non-appcompat version and still have this issue resolved..?

**Comment by PaulsonMac** [comment]
But I think this issue is not occurring in AppCompat renderer

**Comment by kvpt** [comment]
I don't think that mixing AppCompat and Legacy version of renderers is recommended, even if it's supported.
For the style unfortunately I don't think the dialog can be modified.
From the code I see that both AlertDialog and the OnClick is private and not virtual.
So your only solution if you really want a custom style is to copy paste directly the source code of the renderer in your solution.

**Comment by samhouts** [comment]
@PaulsonMac 

[Issue6642.zip](https://github.com/xamarin/Xamarin.Forms/files/3341042/Issue6642.zip)

I also cannot reproduce a crash. Can you please modify the attached reproduction such that it exhibits the behavior? Thanks!

**Comment by PaulsonMac** [comment]
@samhouts , I'll try for sure. Thanks !

**Comment by PaulsonMac** [comment]
I switched to App Compat picker
