### ISSUE TITLE
[Enhancement] CollectionView GroupFooterTemplate

### ISSUE THREAD

**Issue by eclipsed4utoo** [xamarin/Xamarin.Forms#6643]
## Summary
The ListView currently has a HeaderTemplate, FooterTemplate, and a GroupHeaderTemplate. Why shouldn't it also have a GroupFooterTemplate? There is a at least one specific use-case for a group footer.

## API Changes

Adding ListView.GroupFooterTemplate that pretty much matches the GroupHeaderTemplate.

## Intended Use Case
In most chat applications, when the chat between two accounts is opened, the application will typically need to go to the most recent messages. In a Xamarin.Forms application, this requires our applications to scroll to the bottom when the screen loads. That may not be much of a problem when there are a few messages, but if there is 100, then it's bad UX to scroll that far.

To get around this, most native applications will invert the list view 180 degrees, then sort the data from newest to oldest. This puts the newest messages at the "top" of the listview, which since it's inverted, is actually at the bottom of the screen. This means NO SCROLLING is required.

This is one of the few limitations that Xamarin.Forms has that is not completely understood as to why it was left out.

**Comment by pauldipietro** [comment]
A GroupFooterTemplate is part of the CollectionView spec (#3172) and our focus is on that at this time as it is a successor to the ListView.
