### ISSUE TITLE
[Bug] CollectionView won't animate item remove if EmptyViewTemplate is provided

### ISSUE THREAD

**Issue by fabcall** [xamarin/Xamarin.Forms#6644]
### Description
When one removes an item from a CollectionView, the referenced item gracefully fades and a nice transition is performed, instead of the item being abruptly removed. This is a really nice improvement over the old ListView. However, if an EmptyViewTemplate is provided, the animation doesn't work at all.

### Steps to Reproduce

1. Create a CollectionView.
2. Populate it with some data.
2. Create a method to remove an item from the collection. 
3. Provide a EmptyViewTemplate to CollectionView. I've used a DataTemplateSelector (since I have a template for No Data and another template for No Results, if filtering is applied).
4. Fire the method to remove any item from the collection.

### Expected Behavior
It should work exactly if no EmptyViewTemplate were provided, e.g., the removing should be preceded by a smooth animation.

### Actual Behavior
The animation doesn't occur. The item is abruptely removed from the view.

**Comment by samhouts** [comment]
@fabcall Is this for iOS, Android, or both? What version of Xamarin.Forms?  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by fabcall** [comment]
@samhouts 
This is for Android (haven't tested for iOS. Device is a Samsung Galaxy S9. I've tested with latest stable (4.0.0.497661) and latest 4.1 pre-2.

The attached example contains two CollectionViews, both consuming the same ObservableCollection. The first with EmptyViewDataTemplate, the second with none.

![20190625_100947](https://user-images.githubusercontent.com/43019077/60101267-d5f05580-9731-11e9-9ece-77c003446453.gif)

[Issue6644.zip](https://github.com/xamarin/Xamarin.Forms/files/3325354/Issue6644.zip)

**Comment by andreinitescu** [comment]
Should be fixed by #6840

**Comment by fabcall** [comment]
Thanks for the feedback, @andreinitescu . I have identified another strange behavior with CollectionView/EmptyView in Android when using WindowSoftInputModeAdjust.Resize. Basically, this is whats happens:

1) Navigate to the page containing the Searchbar and the CollectionView with EmptyView.
2) CollectionView is filled with items.
3) Focus on Searchbar, keyboard pops in the screen.
4) Type something to trigger the EmptyView.
5) The EmptyView is initially correctly rendered, filling the remaining screen height.
6) Hide the keyboard.
7) The EmptyView should be resized (since the keyboard is now gone), but it isn't.

Do you think #6480 solves the matter? I can place another issue if required.

**Comment by andreinitescu** [comment]
@fabcall I don't think I get any wrong behavior, here's how it looks for me:

![image](https://user-images.githubusercontent.com/743918/60983241-4c03d780-a342-11e9-8676-0fb85a82d21a.png)

What's your expected behavior?

**Comment by fabcall** [comment]
@andreinitescu, this is the behavior I'm getting as of now:

![ezgif-1-99074b2b1444](https://user-images.githubusercontent.com/43019077/60986633-4bede280-a316-11e9-9086-5350bc17bc36.gif)

When the keyboard appears, the empty view fills the screen accordingly. However, when the keyboard is dismissed, one would expect the empty view to be resized. And actually, it seems to be, since when the Searchbar is focused again, the empty view seems to be hidden under the keyboard.

**Comment by andreinitescu** [comment]
Do you have one or two CollectionViews? If there are two it make sense why's to so.
I removed the 2nd CollectionView from your sample, and it works OK:

![image](https://user-images.githubusercontent.com/743918/60988501-66db4980-a34c-11e9-84e0-abfcfb435daf.png)

If you have only one CollectionView, open a new issue but I strongly suggest you create a reproduction sample.

**Comment by fabcall** [comment]
It's only one CollectionView (the sample here is just for demonstration purposes). I'm opening a new issue right now!
