### ISSUE TITLE
[Bug] CollectionView will not display as menu

### ISSUE THREAD

**Issue by sandman202** [xamarin/Xamarin.Forms#6645]
### Description
I have a menu page which uses ListView. I changed it to CollectionView and the menu page no longer displays.

### Steps to Reproduce

1. Create MasterDetail solution
2. To demonstrate the 2 different menus, in MainPage.xaml.cs add code to allow you to change between ListViewMainuPage and CollectionViewMenuPage.
`public MainPage()
{
            InitializeComponent();
             Master = menuPage = new ListViewMenuPage();
            //Master = menuPage = new CollectionViewMenuPage();
        }`
3. ListViewMenuPage.xaml
`<StackLayout BackgroundColor="White">
        <ListView x:Name="menuOptions" SeparatorColor="Silver" Margin="0,15,0,0">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell Height="50">
                        <Grid Padding="25,15,10,10">
                            <Label Text="{Binding Title}"/>
                        </Grid>
                    </ViewCell>
                </DataTemplate>    
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>`

and the code behind

`public partial class ListViewMenuPage : ContentPage
    {
        public ListViewMenuPage()
        {
            InitializeComponent();
            menuOptions.ItemsSource = new List<MainMenuItem> {
                new MainMenuItem { Title = "How It Works", PageType = typeof(HowItWorksPage) },
                new MainMenuItem { Title = "Settings", PageType = typeof(SettingsPage) }
            };
        }
    }`
4. CollectionViewMenuPage.xaml
`<StackLayout BackgroundColor="White">
        <CollectionView x:Name="menuOptions" Margin="0,15,0,0">
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <StackLayout Padding="25,15,10,10">
                        <Label Text="{Binding Title}"/>
                    </StackLayout>
                </DataTemplate>    
            </CollectionView.ItemTemplate>
        </CollectionView>
    </StackLayout>`

and the code behind

`public partial class CollectionViewMenuPage : ContentPage
    {
        public CollectionViewMenuPage()
        {
            InitializeComponent();
            menuOptions.ItemsSource = new List<MainMenuItem> {
                new MainMenuItem { Title = "How It Works", PageType = typeof(HowItWorksPage) },
                new MainMenuItem { Title = "Settings", PageType = typeof(SettingsPage) }
            };
        }
    }`

### Expected Behavior
I would expect the menu to display very similar between ListView and CollectionView.

### Actual Behavior
When I switch between ListView to CollectionView, the menu page does not display.

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

Not able to upload screenshots.

**Comment by samhouts** [comment]
@sandman202 Is this for Android, iOS, or both? What version of Xamarin.Forms? Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sandman202** [comment]
Sorry for not supplying you with the information. I was distracted at work when I submitted.

This is working for Android, but not iOS.
Xamarin.Forms: 4.0.0.497661

You are going to have to tell me how to submit the compressed project that is 142 MB.

**Comment by fabcall** [comment]
@sandman202 , you can delete all bin/obj folders, this will dramatically reduce the size (probably to few MB).

**Comment by sandman202** [comment]
I'll upload the example once I'm able to explain to the security team what I'm doing. I'm being blocked from uploading files.

**Comment by samhouts** [comment]
@sandman202 Thanks! We'll keep looking for it!

**Comment by sandman202** [comment]
It should be attached now.


[CollectionViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3340262/CollectionViewTest.zip)

**Comment by sandman202** [comment]
Why was this closed? I don't recall closing it.

**Comment by hartez** [comment]
See also #6834 - I believe these are the same problem.

@sandman202 If you're looking for a possible temporary workaround until we fix this bug. removing the `StackLayout` from `CollectionViewMenuPage` (so the `CollectionView` is the only content) seems to fix the problem.

**Comment by samhouts** [comment]
closed by #6912
