### ISSUE TITLE
[Bug] x:DataType do NOT accept markup extensions

### ISSUE THREAD

**Issue by lekia** [xamarin/Xamarin.Forms#6648]
### Description
After updating to latest preview 4.1.0.496342-pre2 from 4.0.0.425677, x:DataType do not allow anything but string, which means {x:Null} is not allowed either. I have to disable compile binding here since the target type is a generic one.

### Steps to Reproduce

1. Simply set an x:DataType to anything with markup.

### Expected Behavior
Building without errors.

### Actual Behavior
Complaining "x:DataType expects a string literal".

### Basic Information

- Version with issue: 4.1.0.496342-pre2
- Last known good version: 4.0.0.425677
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - UWP:  17763
  - WPF .Net Framework 4.7.2
- Nuget Packages: Xamarin.Forms

### Screenshots
![Annotation 2019-06-25 121951](https://user-images.githubusercontent.com/11898314/60069448-6be1ab80-9745-11e9-8315-db44f10e7bd8.jpg)

**Comment by GalaxiaGuy** [comment]
This was presumably introduced here:
https://github.com/xamarin/Xamarin.Forms/pull/5335

**Comment by lekia** [comment]
> This was presumably introduced here:
> #5335

However, according to [Microsoft Docs introducing to Compiled Binding](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings):
>  Alternatively, the x:DataType attribute can be re-defined at any point in a view hierarchy to null using the x:Null markup extension.

So {x:Null} is a valid value for x:DataType.

**Comment by GalaxiaGuy** [comment]
I agree. I wasn't saying the change was correct. The intention was to block `{x:Type SomeType}`. I'm now curious whether any other value might be reasonable besides a string or `{x:Null}`.

**Comment by samhouts** [comment]
@lekia  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by tranb3r** [comment]
Same issue for me when upgrading to XF4.1 (`x:DataType expects a string literal`).

This happens when I'm re-defining the data-type, using `x:DataType="{x:Null}"`.
Strangely, I'm also having errors with a few valid data types: `<DataTemplate x:DataType="{x:Type models:MyModel}">`

**Comment by viktorszekeress** [comment]
This is a non-sense. Is there a reason, why you switched to not accepting {x:Type} markup extension? We use it in all other XAML platforms (WPF, WP8, UWP), do you know?

Well regarding {x:Null} issue:
It occurs ONLY if you try to redefine x:DataType inside a DataTemplate:

```
    <StackLayout BindingContext="{Binding ViewModel, Source={x:Reference Root}}">
        <ListView>
            <ListView.ItemTemplate>
                <DataTemplate x:DataType="app3:ViewModel">
                    <!--  Try to disable compiled binding  -->
                    <Label x:DataType="{x:Null}" Text="{Binding Test}" />
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>
```

Please switch back to accepting {x:Type} as x:DataType.

**Comment by davidbritch** [comment]
@samhouts 

I'm also seeing this issue. This change has broken a sample/doc, when we've specifically called out the ability to mix compiled bindings with classic bindings by setting `x:DataType="{x:Null}"`.

**Comment by davidbritch** [comment]
Sample project demoing this error:

[DataBindingDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3349912/DataBindingDemos.zip)

**Comment by samhouts** [comment]
Got it! Thanks!
