### ISSUE TITLE
[Enhancement] BuildProperty for BindableLayout

### ISSUE THREAD

**Issue by Lelelo1** [xamarin/Xamarin.Forms#6649]
## Summary
Expose a `Func<object, DataTemplate> Build` property in `BindableLayout` - So one does not need to use `DataTemplateSelectors`.

## API Changes

In [`BindableLayout`](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BindableLayout.cs) add: 

```
public static readonly BindableProperty BuildProperty =
    BindableProperty.CreateAttached("Build", typeof(Func<object, DataTemplate>), typeof(Layout<View>), default(Func<object, DataTemplate>),
        propertyChanged: (b, o, n) => { GetBindableLayoutController(b).Build = (Func<object, DataTemplate>)n; });
```
Get and Set methods

```
public static void SetBuild(BindableObject b, Func<object, DataTemplate> value)
{
    b.SetValue(BuildProperty, value); 
}

public static Func<object, DataTemplate> GetBuild(BindableObject b)
{
    return (Func<object, DataTemplate>)b.GetValue(BuildProperty);
}
```
In OnControllerChanged add `newC.Build = GetBuild(b);`

---

Inside `BindableLayoutController`, add  corresponding `Func<object, DataTemplate> Build` property.

And in `CreateItemView` the following:
```
View CreateItemView(object item, Layout<View> layout)
{ 
    return CreateItemView(item, _itemTemplate ?? _itemTemplateSelector?.SelectTemplate(item, layout) ?? build?.invoke(item)); // <---
}

```

## Intended Use Case

In the code behind of my page I can have the following:

```
BindableLayout.SetBuild(stackLayout,
    (item) =>
    {
        var model = item as string;
        switch(model)
        {
            case "First":
                return special;
            default:
                return standard;
        }
    });
              
```
Where `special` and `standard` are DataTemplates defined in xaml of the same page. (Instead of needing to have a class extending [DataTemplateSelector)](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector)

**Comment by andreinitescu** [comment]
>  So one does not need to use DataTemplateSelectors.

What's the issue with using DataTemplateSelector? It's basically what you're asking, it's a function taking the item as a parameter and returns a DataTemplate instance. 
Do you have a specific scenario where it doesn't work well for you?

**Comment by andreinitescu** [comment]
@Lelelo1 I think what you want is to be able to create a `DataTemplateSelector` without adding a class and implementing `DataTemplateSelector`. Which makes sense.
I did a PR for this, please see #6650. What do you think?

**Comment by Lelelo1** [comment]
I am not completely sure how the rendering works in `ListView` and `CollectionView` with DataTemplate. But when it comes `BindableLayout` it seems very redundant. It could take a `VisualElement` instead and expose `Func<object, VisualElement>` - it would be much more intuitive. However [this](https://github.com/xamarin/Xamarin.Forms/issues/6476) problem would prevent that from being possible.

If `BindableLayout` has to use `DataTemplate`, #6659 would be good to have. And it would also be usable for `ListView` and `CollectionView`.

**Comment by andreinitescu** [comment]
> It could take a VisualElement instead and expose Func<object, VisualElement> - it would be much more intuitive

What you're describing is what DataTemplate does. DataTemplate already takes a Func<> in c-tor. I wish DataTemplateSelector wasn't abstract and instead had the `SelectedContent` virtual, so it could take a Func instance in c-tor too.

> However this problem would prevent that from being possible.

I place a comment on that issue you opened, take a look, there's actually no problem.

> If BindableLayout has to use DataTemplate, #6650 would be good to have. And would also work for ListView and CollectionView.

Yes, the DefaultDataTemplateSelector from #6650 would work. Note that what's interesting about implementing DataTemplateSelector with your own subclass is that it gives you a simple way to have a place where you encapsulate the DataTemplate instances. If you are passing the DefaulDataTemplateSelector the Func, where do you keep your DataTemplate instances? I guess it depends.

**Comment by Lelelo1** [comment]
I don't see the point of wrapping the `VisualElement` with `DataTemplate`. If the role of the `DataTemplate` is to create new instances - it would be better for `BindableLayout` to have a internal DataTemplate that does that:

```
View ItemForView(object item)
{
    var newInstance = dataTemplate.createContentFrom(build.invoke(item)); // <--notice From
    return newInstance;
}
```

Notice the `DataTemplate` redundancy:

```
<ContentPage.Resources>
    <ResourceDictionary>
        <DataTemplate x:Name="custom1">
            <StackLyout>
                <Label Text="custom"/>
            </StackLyout>
        </DataTemplate>
        <DataTemplate x:Name="custom2">
            <StackLyout>
                <Label Text="custom"/>
            </StackLyout>
        </DataTemplate>
        <DataTemplate x:Name="default">
            <StackLyout>
                <Label Text="default"/>
            </StackLyout>
        </DataTemplate>
    </ResourceDictionary>
  </ContentPage.Resources>
```
cleaner and shorter -->

```
  <ContentPage.Resources>
    <ResourceDictionary>
        <StackLyout x:Name="custom1">
            <Label Text="custom"/>
        </StackLyout>
        <StackLyout x:Name="custom2">
            <Label Text="custom"/>
        </StackLyout>
        <StackLyout x:Name="default">
            <Label Text="default"/>
        </StackLyout>
    </ResourceDictionary>
  </ContentPage.Resources>
```

 Also, If `DataTemplate` simply is a placeholder for a func - it is better to use a func for simplicity.

> If you are passing the DefaulDataTemplateSelector a Func, where do you keep your DataTemplate instances?

Using `DefaultDataTemplateSelector` would mean that you don't need to store them anywhere - but can be used directly:

```
  public MyPage()
  {
    var defaultData = new DefaultDataTemlateSelector((item, collectionView)) =>
    {
        switch(item)
        {
            case 1:
                return custom1;
            case 2:
                return custom2;
            default:
                return default;
        }
    });
    collectionView.ItemTemplate = defaultData;
  }
```

How it would be used completely in xaml I don't know.

**Comment by andreinitescu** [comment]
> I don't see the point of wrapping the VisualElement with DataTemplate. If the role of the DataTemplate is to create new instances - it would be better for BindableLayout to have a internal DataTemplate that does that:

You initially asked about DataTemplateSelector, not DataTemplate, and you only mentioned about C#, not XAML. In C# code it's very easy to create a DataTemplate from a func, the DataTemplate has a c-tor which accepts a func.

**Comment by Lelelo1** [comment]
> > I don't see the point of wrapping the VisualElement with DataTemplate. If the role of the DataTemplate is to create new instances - it would be better for BindableLayout to have a internal DataTemplate that does that:
> 
> In C# code it's very easy to create a DataTemplate from a func, the DataTemplate has a c-tor which accepts a func. Based on the description of the ticket, my impression was you are working with C# not XAML.

I am working with both.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
