### ISSUE TITLE
[Bug] Setting ControlTemplate on ContentPage from an implicit style results in blank content

### ISSUE THREAD

**Issue by rbev** [xamarin/Xamarin.Forms#6657]
### Description

When setting a control template on ContentPage using an implicitly applied style the ContentPresenter appears blank.

The attached reproduction sample exhibits a completely blank ContentPresenter, however in my larger solution the result I get is slightly more subtle - The content presenter seems to work but Xaml bindings elements stop working. Originally noticed the issue due to similar symptoms described in #2146.
[ControlTemplateBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/3328300/ControlTemplateBinding.zip)

### Steps to Reproduce

1. Create a style that applies to your ContentPage type (without an x:Key declaration)
2. Apply a control template using the style

### Expected Behavior

The content of the page is visible in place of the <ContentPresenter> element

### Actual Behavior

Blank space

### Basic Information

- Version with issue: 3.6+ (including 4.0.0.497661)
- Last known good version: none
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0 
  - UWP:   
- Android Support Library Version: 28.0.0.1 
- Nuget Packages:
- Affected Devices: Samsung Galaxy Tab Active 2 (Android 8.1, Sumsung Experience 9.5)

### Reproduction Link

[ControlTemplateBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/3328305/ControlTemplateBinding.zip)

**Comment by andreinitescu** [comment]
@rbe thanks for reporting, nasty one, fix is coming #6657

**Comment by rbev** [comment]
Thanks for the quick turnaround
