### ISSUE TITLE
[Enhancement] Please stop locking so many things behind internal

### ISSUE THREAD

**Issue by malware-dev** [xamarin/Xamarin.Forms#6658]
I keep hitting roadblocks because so many things I need are locked behind internal access. It feels so very wrong to have to duplicate code you already have written, just because one particular required method is not overrideable or accessible.

Case in point: TemplatedView.OnContentTemplateChanged.

**Comment by andreinitescu** [comment]
@malware-dev (interesting username btw), does TemplatedView.OnApplyTemplate introduced by #1620 helps? What's your scenario?

I think it makes sense to at least have a way to know when Content changed (which can be independent of template), this can be useful. I think there should be a virtual OnContentChanged

**Comment by dansiegel** [comment]
@malware-dev (dangerous name to have btw)… it's actually a lot better that many API's used internally start out as internal. If you have specific API's that you would like to see made public, by all means open an issue with the API you would like to see made public and how/why it would be helpful. I know the team is very open to opening up API's when/where it makes good sense.

**Comment by malware-dev** [comment]
@andreinitescu I wanted to _override_ the original behavior in ContentView, to extend its behavior to work more like the ContentControl. In this case OnApplyTemplate won't help me - but thank you for your response and suggestion anyway, it is appreciated.

@dansiegel I disagree, strongly. It's a PITA when APIs are pointlessly internal, especially in APIs like this one. In this case it's literally an empty function of the traditional property change pattern so there's no reason. I've been programming for a rather long time, and I don't like it when APIs get in the way when I try to do my job :D Thankfully, most don't.

Don't judge people by their nicknames. After all, it's just that - a nickname, nothing else, and you have no way of knowing the history behind it. _This_ one has nothing to do with actual malware in any way or form ;) The "-dev" is simply because I didn't want a number on the end.

**Comment by hartez** [comment]
@malware-dev If you have a specific API you'd like opened up, please open an issue for it.

**Comment by malware-dev** [comment]
@hartez I was asking for TemplatedView.OnContentTemplateChanged at this particular point 😄

**Comment by andreinitescu** [comment]
Like I mentioned above, having `TemplatedView.OnContentTemplateChanged` overridable seems a very valid to have. I don't understand why this was closed.

@malware-dev Either open another ticket or just update the description and title of the issue with very specific info, i.e. "Have TemplatedView.OnContentTemplateChanged` overridable`
