### ISSUE TITLE
[Enhancement] IsValid property for ImageSource

### ISSUE THREAD

**Issue by SuNNjek** [xamarin/Xamarin.Forms#6660]
## Summary
It'd be nice to have a property on the ImageSource class that indicates whether the source is valid. If the image failed to load (e.g. if the file of a FileImageSource doesn't exist or the URL of an UriImageSource returns a 404) this property would be set to true to indicate the failure.

## API Changes
The ImageSource class would get another property called IsValid/IsFailed/etc.

```csharp
class ImageSource
{
    public bool IsValid { get; }
}
```

## Intended Use Case
This property would enable the display of fallback images in case the intended image can not be loaded.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
