### ISSUE TITLE
[Bug] [UWP] OnMeasure does not get called until moving the mouse

### ISSUE THREAD

**Issue by DuncWatts** [xamarin/Xamarin.Forms#6662]
### Description
I am loading a set of data which triggers the UI to update by calling InvalidateLayout.  Instead of then calling OnMeasure on the same control it appears to stall until I move the mouse or tap on the screen on a touch screen device.  The CPU remains at zero for this time period.

This is less obvious on devices using mouse as you tend to use the mouse as you navigate around however is causing issues testing on touchscreen devices as you have to tap on the screen to trigger the display of data.

This does not occur on iOS or Android builds.

### Expected Behavior
Calling InvalidateLayout triggers a layout pass.

### Actual Behavior
Layout pass doesn't occur until mouse moves

### Basic Information

- Version with issue: 4.0.0.497661
- Last known good version: None
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - UWP:  16299

**Comment by samhouts** [comment]
@DuncWatts  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@DuncWatts  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
