### ISSUE TITLE
[Bug] (3.3->3.5 Regression) GTK: when navigating back to previous page, not all contents are rendered

### ISSUE THREAD

**Issue by knocte** [xamarin/Xamarin.Forms#6663]
### Description

When having a configuration with a NavigationPage that gets pushed forward, and later backwards, the original contents of the first page are not all shown.

### Steps to Reproduce

1. clone https://github.com/knocte/gwallet
2. checkout branch `bugreport/gtk-navgoback`
3. compile gtk project (in Mac, just open in VS and compile; in Linux do `./configure.sh && make`)
4. run gtk project, you see
<img width="398" alt="init and expected results" src="https://user-images.githubusercontent.com/331303/60195463-b78f7480-986d-11e9-844a-e33a9ccf9b43.png">
5. click on "BAR" to go forward one page, you'll see
<img width="400" alt="b" src="https://user-images.githubusercontent.com/331303/60195511-c9711780-986d-11e9-9090-61c6f4f84c3f.png">
6. click on the left arrow to go back

### Actual Behavior
You go back to the initial page but only "FOO" is seen, not "BAR":
<img width="400" alt="back, current results" src="https://user-images.githubusercontent.com/331303/60195892-92e7cc80-986e-11e9-831f-834b92e5b4e1.png">

### Expected Behavior
You should see "FOO" and "BAR" again, like the first screenshot.
(In fact if you go back to XamarinForms 3.0 instead of 3.6, by reverting the last commit of this branch b84f801e986873ef43faec77d5cb61d193cc4ab2 , then the bug is not present. Therefore, this is a regression that happened somewhere between 3.0 and 3.6.)

### Basic Information

- Version with issue: 3.5.0.274416 and 3.6.0.344457 and newer ones
- Last known good version: 3.0.0.446417 (3.4.0.1039999 seems to be working too)
- IDE: VS4Mac
- Platform Target Frameworks:
  - GTK: on macOS or Ubuntu 18.04
- Nuget Packages: see versions above
- Affected Devices: PC & Mac

### Screenshots

See screenshots in the steps to reproduce.

### Reproduction Link

See steps to reproduce.

**Comment by knocte** [comment]
@mfkl hey Martin, remember that the testcase didn't cover 100% of the issue? I've done a new testcase, branch called `bugreport/gtk-navgoback2` instead of `bugreport/gtk-navgoback`: https://gitlab.com/knocte/geewallet/commits/bugreport/gtk-navgoback2

**Comment by mfkl** [comment]
This regression was introduced in `3.4.0.1008975`. The previous version `3.3.0.967583` does not exhibit the problem.

With 3.4 and your repro, GTK outputs
```
(geewallet:7640): Gtk-WARNING **: 16:01:59.320: Attempting to add a widget with type __gtksharp_12_Xamarin_Forms_Platform_GTK_Renderers_LayoutRenderer to a container of type __gtksharp_16_Xamarin_Forms_Platform_GTK_Controls_CustomFrame, but the widget is already inside a container of type __gtksharp_16_Xamarin_Forms_Platform_GTK_Controls_CustomFrame, the GTK+ FAQ at http://library.gnome.org/devel/gtk-faq/stable/ explains how to reparent a widget.
```

And the navigation bar does not seem to be drawn properly in 3.4. 

https://github.com/xamarin/Xamarin.Forms/pull/4112 looks like it may be part of the cause of regression, but reverting it doesn't quite fix it either.
