### ISSUE TITLE
[Enhancement] Global background for Shell and/or ShellSections

### ISSUE THREAD

**Issue by JonathanBordeleau** [xamarin/Xamarin.Forms#6664]
## Summary
It would be nice to have a way to set a global _BackgroundColor_ or _BackgroundImage_ for a Shell app when there is a recurring image/color throughout the project.

## API Changes
In order to facilitate the new feature, a _GlobalBackgroundImageSource_ or _GlobalBackgroundColor_ property is added to the _Shell_ and _ShellSection_ classes. Also, a _IsBackgroundTransparent_ property is added to the _ContentPage_ class.

**Case 1 :** Global background image/color throughout the Shell app 

    <Shell
        x:Class="Shell.AppShell"
        xmlns="http://xamarin.com/schemas/2014/forms"
        GlobalBackgroundImageSource="xamarin_logo.png">

**Case 2 :** Global background image/color throughout a ShellSection

    <ShellItem>
        <ShellSection Title="About " GlobalBackgroundImageSource="xaml.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage1}" />
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage2}" />
        </ShellSection>
    </TabBar>

**ContentPage**

    <ContentPage
        x:Class="Shell.Views.AboutPage"
        xmlns="http://xamarin.com/schemas/2014/forms"
        xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
        IsBackgroundTransparent="True">

## Intended Use Case
This would be useful when an app uses the same _BackgroundImage_ or _BackgroundColor_ throughout most the _ContentPages_. This way, the pages's content would be the only thing that's changing when using the second level tab navigation and it would work almost exactly as a _Carousel_.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
