### ISSUE TITLE
[Enhancement] entry binded to numeric to pass zero to binded object when cleared

### ISSUE THREAD

**Issue by ish-1313** [xamarin/Xamarin.Forms#6665]
## Summary
it will be convenient if entry field binded to numeric returns zero if emptied (may be optionally)

## API Changes

currently entry field binded to numeric just didn't updates binded object if cleared. so, binded object contains the last value it held before entry field was cleared.
it is possible to work around this situation with ivalueconverter (or events), but it will be very convenient if entry field pass zero in such situation (or, optional default value in case conversion to numeric fails).

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
