### ISSUE TITLE
[Bug] [Android] Listview does not fully paint element when scrolling quickly using RecylceElement

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#6670]
### Description
When using RecycleElement as the CachingStrategy, scrolling quickly through a 2+ page list view 
results in items not being fully painted.

I have listed this as Android only since I can not test it on iOS, the view does not scroll.

### Steps to Reproduce

1. Run the attached test app.  Note that all the elements start with "Test Message" and a number
2. Scroll to the bottom of the list and back to the top relatively quickly
3. Note that some of the items no longer display the number
4. Tap on an item to see it's details.  Tap back to return to the list view.  Note that some of the items no longer display the number, and it may be different items.
5. In the code, edit NotificationListPage.xaml and remove the CachingStragegy line, #44.  Repeat the above steps.  Note that the initial scrolling takes longer, but the numbers are never left off an item

### Expected Behavior
The items should fully paint

### Basic Information

- Version with issue: 4.1.0 pre-2
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/1641428/60210273-82adfe00-982a-11e9-9c56-c85a59bfd7e3.png)

![image](https://user-images.githubusercontent.com/1641428/60210314-9a858200-982a-11e9-9186-32a5e6eb7be0.png)

![image](https://user-images.githubusercontent.com/1641428/60210346-ab35f800-982a-11e9-819f-c727d71acc88.png)

### Reproduction Link
[HeaderTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3331708/HeaderTest.zip)

**Comment by samhouts** [comment]
closed by #6390

**Comment by fpiribauer** [comment]
Under XF 4.0.0.618610 the repro project seems to still have the same issue.
