### ISSUE TITLE
Tab error on macOS (Xamarin.forms)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6671]
VSF_TYPE_MARKDOWNOn macOS (MacBook Pro 17&quot; mid 2010) I have a problem with TabStop.

When I press the Tab key the focus jumps 2 indexes forward. I have attached screen captures of the behavior on macOS (ScreenCapture_macOS.mp4) and Windows 10 (ScreenCapture_Windows_10.mp4).

As you can see the tab stops work fine on windows 10 but on macOS it always jumps 2 indexes forward.

MainPage.xaml is attached also.

Best regards,
Eigil

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/591450/tab-error-on-macos-xamarinforms.html
VSTS ticketId: 903999_
_These are the original issue comments:_

Visual Studio Feedback System on 6/2/2019, 07:06 PM (23 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Samantha Houts [MSFT] on 6/5/2019, 01:44 PM (20 days ago): <p>Thank you for the report! I don't see any attachments. Can you please attach a small project that demonstrates this issue? Thanks!</p>

_These are the original issue solutions:_
(no solutions)

**Comment by samhouts** [comment]
Note: repro project is attached to private ticket. Thanks!

**Comment by AndreiMisiukevich** [comment]
it might be fixed via my PR

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
