### ISSUE TITLE
[UWP] Navigation bar renderers differently after 16299

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6672]
VSF_TYPE_MARKDOWNThe navigation bar (toolbar) does not render properly for UWP SDK  greater than 16299.

To reproduce, create a Xamarin.Forms project and select MasterDetail project.

1. Add icon to the Add button ToolbarItem.

2. In UWP project property page, set Target Version  and Min Version to Set Windows 10 Fall Creators Update (10.0; Build 16299).

3. Compile and deploy.  The app properly renders Hamburger Icon, Add Icon and Ellipsis Icon.

4. Change Target Version  to Windows 10 Fall, Version 1809 (10.0; Build 17763).

5. Compile and deploy,  The app improperly renders Hamburger Icon, Add Icon and Ellipsis Icon.  The Icons do not fill the entire height og the navigation bar.  Problem also occurs when using Version 1903 - Build 18362.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/606864/xamarin-toolbar.html
VSTS ticketId: 918114_
_These are the original issue comments:_

Visual Studio Feedback System on 6/14/2019, 00:29 AM (12 days ago): <p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

Samantha Houts [MSFT] on 6/19/2019, 07:40 PM (6 days ago): <p> Can you please attach a small project that demonstrates this issue? Thanks!</p>

Pierre Valade on 6/19/2019, 08:04 PM (6 days ago): Project attached.
Pierre Valade on 6/19/2019, 08:01 PM (6 days ago): How do I attach a project?
Pierre Valade on 6/24/2019, 10:26 PM (39 hours ago): Do you need more info?  Were you able to reproduce?
_These are the original issue solutions:_
(no solutions)

**Comment by jsuarezruiz** [comment]
@pierrevalade  Can you please attach a small project that demonstrates this issue?

**Comment by pierrevalade** [comment]
sorry it's not me

**Comment by pvalade57** [comment]
Bu it is me.   This was sent to 2 Pierre Valade.   I am pvalade57.
[TestAppSolution.zip](https://github.com/xamarin/Xamarin.Forms/files/3412119/TestAppSolution.zip)

Project attached.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/5661
