### ISSUE TITLE
Arabic in StringFormat is ruined

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6673]
Hi,

If you see the attached image you'll notice the format is ruined

Look at brackets for example

This happens only when I add arabic text in the StringFormat

![arabic](https://user-images.githubusercontent.com/6236241/60213922-8ca91e80-9875-11e9-8787-d460058df020.png)

**Comment by samhouts** [comment]
@jrahma  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jrahma** [comment]
Hi Sam,

Sample project is attached

[FormatString.zip](https://github.com/xamarin/Xamarin.Forms/files/3360399/FormatString.zip)

Thanks,
Jassim

**Comment by jsuarezruiz** [comment]
@jrahma Do you have the weird behavior during runtime of while writing code in VS4Mac?

Currently, using the latest VS4Mac stable version (8.1.5 build 9) I see the following result:
<img width="546" alt="Captura de pantalla 2019-07-18 a las 13 38 37" src="https://user-images.githubusercontent.com/6755973/61454621-abc13a80-a961-11e9-9d5c-83d390955314.png">

What version of VS4Mac do you use?

**Comment by jrahma** [comment]
@jsuarezruiz @samhouts 

I moved from Mac to Windows. In Windows it looks better, at least it's readable although it still has a problem.

I am using Visual Studio 2019 for Windows Version 16.1.6

Regarding the Arabic text you showed, it's completely wrong and unreadable (Junk characters)

you can try my name as an example:

Here is the name in Text for you to copy-paste it:

جاسم

and this is how the name should look as an image:

![image](https://user-images.githubusercontent.com/6236241/61540469-bb6a7d00-aa4e-11e9-8a8d-f91437bd5790.png)

This is the StringFormat shows the correct name in StringFormat (again I am using Windows here):

![image](https://user-images.githubusercontent.com/6236241/61540659-1c925080-aa4f-11e9-8b59-adfe392813ef.png)


but when I add {0} to the StringFormatyou can see that the bracket has jumped to wrong place:

![image](https://user-images.githubusercontent.com/6236241/61540852-8ad71300-aa4f-11e9-93eb-d54780af4785.png)


not sure about the Visual Studio for Mac because I already moved to Windows but it should be the same exactly.

**Comment by PureWeen** [comment]
@jrahma can you log this issue using the feedback feature on VS? 

https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

This way it can get to the correct team and it will also log details about your setup to the ticket which will help them identify the issue quicker

**Comment by jrahma** [comment]
This is still not fixed...

**Comment by jrahma** [comment]
@samhouts this is still not fixed..

**Comment by samhouts** [comment]
@jrahma Did you submit a ticket through Visual Studio? If you have a link, I can check on the status. Thanks!

**Comment by jrahma** [comment]
@samhouts yes I did Sam

[https://developercommunity.visualstudio.com/content/problem/664348/arabic-in-stringformat-is-ruined.html](https://developercommunity.visualstudio.com/content/problem/664348/arabic-in-stringformat-is-ruined.html)
