### ISSUE TITLE
[Enhancement] Support Virtual InitializeComponent

### ISSUE THREAD

**Issue by dansiegel** [xamarin/Xamarin.Forms#6676]
## Summary

Currently InitializeComponent is generated by the XAML tasks during build. The problem with this is that it cannot be called except by user code making it harder to rely on.

## API Changes

Minimum: update the build tasks to recognize if there is a virtual InitializeComponent in a base class and override it also making sure to add some run once logic.

Preferred: add a virtual InitializeComponent in the Application class and update the build task accordingly.

## Intended Use Case

Shift the requirement to call InitializeComponent from the User's code to either Xamarin.Forms itself or a Framework. This would then ensure that anything which may be declared in XAML has been initialized for the User's code. This also means that Frameworks which extend the Application class such as Prism could add custom properties that may be set in XAML and would then be available as the framework is initializing.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
