### ISSUE TITLE
[Bug]  WebView UWP not displaying (BugZilla: 57451)

### ISSUE THREAD

**Issue by ChristianKleineidam** [xamarin/Xamarin.Forms#6679]
In production the WebView that I'm using to display the terms and condition when my app starts randomly doesn't show up. I opened a [StackOverflow question ](https://stackoverflow.com/questions/56770456/xamarin-webview-sometimes-doesnt-show-in-uwp?noredirect=1#comment100125670_56770456)for the issue. 

Later I found an existing bug report with comes with a reproduce-able sample on your old BugZilla: https://xamarin.github.io/bugzilla-archives/57/57451/bug.html

I'm a bit surprised to see a bug of a basic function like the WebView with local files being open for 2 years. Given that when I currently search for 57451 on this Github I found no issue, I opened this bug report to draw more attention.

**Comment by CannoliSquid** [comment]
I started having an issue similar to this after updating to Windows 10 1809 (Build 17763). Tried rolling code back, changing code, upgrading and downgrading Xamarin.Forms and Embed.io .
My UWP project was loading the WebView perfectly fine prior to the Windows update and now it will not load the WebView at all (although I can see it in the Live Visual Tree with all of the properties looking valid). Basic websites will appear in the webview ( http://www.google.com as the source works perfectly fine, but local files just stopped working).

**Comment by CannoliSquid** [comment]
Are there any updates on this issue?

**Comment by artemious7** [comment]
I have the same problem. I have 2 PCs: one has quite low performance, and the issue manifests most of the times there. The other one has very good performance, and most of the times it shows fine. But quite often even here the first time I try to show local HTML in the app, it doesn't show. Subsequent tries are more successful. After I restart the app the situation repeats (sometimes it shows the content fine for the first time, and sometimes it shows it only from second try).
