### ISSUE TITLE
[Bug] App crash when use HttpCLient with AndroidClientHandler

### ISSUE THREAD

**Issue by babman92** [xamarin/Xamarin.Forms#6680]
### Description
* I want to use native Http call
* I use AndroidClientHandler with HttpClient but app crash
* Code below:
![image](https://user-images.githubusercontent.com/5634873/60256068-0d5e2e00-98fb-11e9-94a4-138dbb27d281.png)

### Steps to Reproduce

1. Create Xamarin.Form project
2. Create DataClient.cs in Shared project
3. Init AndroidClientHandler (import Mono.Android.dll and using Xamarin.Android.Net;)
4. Init HttpClient with AndroidClientHandler above
5. Run app and call API

### Expected Behavior
App call API correctly
### Actual Behavior
App crash when call API
### Basic Information

- Version with issue:
- Last known good version: Xamarin.Forms v4.0.0.425677
- IDE: Visual Studio 2019 on Windows 10
- Platform Target Frameworks: 
  - Android: Compile using Android 9.0
![image](https://user-images.githubusercontent.com/5634873/60256359-8f4e5700-98fb-11e9-8763-5508798409c5.png)
- Affected Devices: Emulator (8.0 (Oreo) - API 26)

### Screenshots, Logs
06-27 16:53:05.314 D/Mono    ( 9766): DllImport searching in: '__Internal' ('(null)').
06-27 16:53:05.314 D/Mono    ( 9766): Searching for 'java_interop_jnienv_call_float_method_a'.
06-27 16:53:05.314 D/Mono    ( 9766): Probing 'java_interop_jnienv_call_float_method_a'.
06-27 16:53:05.314 D/Mono    ( 9766): Found as 'java_interop_jnienv_call_float_method_a'.
06-27 16:53:05.394 D/Mono    ( 9766): Loading reference 6 of /storage/emulated/0/Android/data/com.companyname.HttpClientDemo/files/.__override__/HttpClientDemo.dll asmctx DEFAULT, looking for System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
06-27 16:53:05.395 D/Mono    ( 9766): Image addref System.Net.Http[0x8f0fbd40] (asmctx DEFAULT) -> System.Net.Http.dll[0x8f153e00]: 2
06-27 16:53:05.395 D/Mono    ( 9766): Prepared to set up assembly 'System.Net.Http' (System.Net.Http.dll)
06-27 16:53:05.395 D/Mono    ( 9766): Assembly System.Net.Http[0x8f0fbd40] added to domain RootDomain, ref_count=1
06-27 16:53:05.395 D/Mono    ( 9766): AOT: image 'System.Net.Http.dll.so' not found: dlopen failed: library "System.Net.Http.dll.so" not found
06-27 16:53:05.395 D/Mono    ( 9766): AOT: image '/Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/System.Net.Http.dll.so' not found: dlopen failed: library "/Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/sdks/out/android-x86-release/lib/mono/aot-cache/x86/System.Net.Http.dll.so" not found
06-27 16:53:05.395 D/Mono    ( 9766): Config attempting to parse: 'System.Net.Http.dll.config'.
06-27 16:53:05.395 D/Mono    ( 9766): Config attempting to parse: '/Users/builder/jenkins/workspace/xamarin-android-d16-1/xamarin-android/external/mono/sdks/out/android-x86-release/etc/mono/assemblies/System.Net.Http/System.Net.Http.config'.
06-27 16:53:05.395 D/Mono    ( 9766): Assembly Ref addref HttpClientDemo[0xa390ef60] -> System.Net.Http[0x8f0fbd40]: 2
06-27 16:53:05.396 D/Mono    ( 9766): Loading reference 0 of System.Net.Http.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
06-27 16:53:05.396 D/Mono    ( 9766): Assembly Ref addref System.Net.Http[0x8f0fbd40] -> mscorlib[0xa390e720]: 56
06-27 16:53:05.396 D/Mono    ( 9766): Loading reference 2 of /storage/emulated/0/Android/data/com.companyname.HttpClientDemo/files/.__override__/HttpClientDemo.dll asmctx DEFAULT, looking for Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
06-27 16:53:05.396 D/Mono    ( 9766): Assembly Ref addref HttpClientDemo[0xa390ef60] -> Mono.Android[0xa3844680]: 46
06-27 16:53:05.396 D/Mono    ( 9766): Loading reference 1 of Mono.Android.dll asmctx DEFAULT, looking for System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
06-27 16:53:05.396 D/Mono    ( 9766): Assembly Ref addref Mono.Android[0xa3844680] -> System.Net.Http[0x8f0fbd40]: 3
Loaded assembly: System.Net.Http.dll [External]
06-27 16:53:05.411 D/Mono    ( 9766): Loading reference 1 of System.Net.Http.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
06-27 16:53:05.411 D/Mono    ( 9766): Assembly Ref addref System.Net.Http[0x8f0fbd40] -> System[0xa3844980]: 7
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'HttpClientDemo.DataClient' threw an exception.

06-27 16:53:09.860 D/Mono    ( 9766): DllImport attempting to load: '/system/lib/liblog.so'.
06-27 16:53:09.861 D/Mono    ( 9766): DllImport loaded library '/system/lib/liblog.so'.
06-27 16:53:09.861 D/Mono    ( 9766): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
06-27 16:53:09.861 D/Mono    ( 9766): Searching for '__android_log_print'.
06-27 16:53:09.861 D/Mono    ( 9766): Probing '__android_log_print'.
06-27 16:53:09.861 D/Mono    ( 9766): Found as '__android_log_print'.
06-27 16:53:09.869 I/MonoDroid( 9766): UNHANDLED EXCEPTION:
06-27 16:53:09.877 I/MonoDroid( 9766): System.TypeInitializationException: The type initializer for 'HttpClientDemo.DataClient' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
06-27 16:53:09.877 I/MonoDroid( 9766): Parameter name: handler
06-27 16:53:09.877 I/MonoDroid( 9766):   at System.Net.Http.HttpMessageInvoker..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00009] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:09.877 I/MonoDroid( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:09.877 I/MonoDroid( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:09.878 I/MonoDroid( 9766):   at HttpClientDemo.DataClient..ctor () [0x00033] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:27 
06-27 16:53:09.878 I/MonoDroid( 9766):   at HttpClientDemo.DataClient..cctor () [0x00000] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:13 
06-27 16:53:09.878 I/MonoDroid( 9766):    --- End of inner exception stack trace ---
06-27 16:53:09.878 I/MonoDroid( 9766):   at HttpClientDemo.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x0000f] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\MainPage.xaml.cs:28 
06-27 16:53:09.878 I/MonoDroid( 9766):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
06-27 16:53:09.878 I/MonoDroid( 9766):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <a6696dd5fce04f5480364911ef1529f2>:0 
06-27 16:53:09.878 I/MonoDroid( 9766):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a6696dd5fce04f5480364911ef1529f2>:0 
06-27 16:53:09.878 I/MonoDroid( 9766):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <a6696dd5fce04f5480364911ef1529f2>:0 
06-27 16:53:09.878 I/MonoDroid( 9766):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr)
06-27 16:53:09.895 W/zygote  ( 9766): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
06-27 16:53:09.908 D/Mono    ( 9766): DllImport searching in: '__Internal' ('(null)').
06-27 16:53:09.908 D/Mono    ( 9766): Searching for 'java_interop_jnienv_throw'.
06-27 16:53:09.908 D/Mono    ( 9766): Probing 'java_interop_jnienv_throw'.
06-27 16:53:09.908 D/Mono    ( 9766): Found as 'java_interop_jnienv_throw'.
Unhandled Exception:

System.TypeInitializationException: The type initializer for 'HttpClientDemo.DataClient' threw an exception.

06-27 16:53:12.253 E/mono    ( 9766): 
06-27 16:53:12.253 E/mono    ( 9766): Unhandled Exception:
06-27 16:53:12.253 E/mono    ( 9766): System.TypeInitializationException: The type initializer for 'HttpClientDemo.DataClient' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
06-27 16:53:12.253 E/mono    ( 9766): Parameter name: handler
06-27 16:53:12.253 E/mono    ( 9766):   at System.Net.Http.HttpMessageInvoker..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00009] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono    ( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono    ( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono    ( 9766):   at HttpClientDemo.DataClient..ctor () [0x00033] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:27 
06-27 16:53:12.253 E/mono    ( 9766):   at HttpClientDemo.DataClient..cctor () [0x00000] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:13 
06-27 16:53:12.253 E/mono    ( 9766):    --- End of inner exception stack trace ---
06-27 16:53:12.253 E/mono    ( 9766):   at HttpClientDemo.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x0000f] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\MainPage.xaml.cs:28 
06-27 16:53:12.253 E/mono    ( 9766):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr)
06-27 16:53:12.253 E/mono    ( 9766):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr)
06-27 16:53:12.253 E/mono-rt ( 9766): [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'HttpClientDemo.DataClient' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
06-27 16:53:12.253 E/mono-rt ( 9766): Parameter name: handler
06-27 16:53:12.253 E/mono-rt ( 9766):   at System.Net.Http.HttpMessageInvoker..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00009] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono-rt ( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler, System.Boolean disposeHandler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono-rt ( 9766):   at System.Net.Http.HttpClient..ctor (System.Net.Http.HttpMessageHandler handler) [0x00000] in <162fad71ed6e4a3cb7598d196d170e1b>:0 
06-27 16:53:12.253 E/mono-rt ( 9766):   at HttpClientDemo.DataClient..ctor () [0x00033] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:27 
06-27 16:53:12.253 E/mono-rt ( 9766):   at HttpClientDemo.DataClient..cctor () [0x00000] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\DataClient.cs:13 
06-27 16:53:12.253 E/mono-rt ( 9766):    --- End of inner exception stack trace ---
06-27 16:53:12.253 E/mono-rt ( 9766):   at HttpClientDemo.MainPage.Button_Clicked (System.Object sender, System.EventArgs e) [0x0000f] in D:\Projects\SonyDemos\HttpClientDemo\HttpClientDemo\HttpClientDemo\MainPage.xaml.cs:28 
06-27 16:53:12.253 E/mono-rt ( 9766):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr)
06-27 16:53:12.253 E/mono-rt ( 9766):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.49(intptr,intptr)
06-27 16:53:12.253 D/        ( 9766): HostConnection::get() New Host Connection established 0xa5f1f540, tid 9766

### Reproduction Link

https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows

**Comment by babman92** [comment]
I'm so sorry about that, this bug is my failure. Please ignore it.

**Comment by quintonv** [comment]
> I'm so sorry about that, this bug is my failure. Please ignore it.

What was the fix? When I look at your code I see nothing wrong.

I am receiving something similar and thought this thread could help me.

**Comment by babman92** [comment]
@quintonv I'm sorry, I can't remember exactly that error but it was my logic error.

**Comment by quintonv** [comment]
> @quintonv I'm sorry, I can't remember exactly that error but it was my logic error.

Thanks for the reply. I eventually figured mine out.

OnAppearing I was doign an sync http call, for some reason it would just throw a null reference in the http get on the first call. Once the app has been open and I load it again it just worked. So strange, but I moved it to VM constructor now instead of appearing method
