### ISSUE TITLE
[Enhancement] gesture in tabbar of shell on android

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#6684]
It's seem like shell's tabbar on android could not be use the gesture swipe like tabbedpage .
Is it will be implement in the future?

**Comment by PTEC3D50** [comment]
Hello,
It's not an "Enhancement", it's an issue, that was the behavior in Xamarin.Forms 4.1 and this is KO in Xamarin.Forms 4.2

Would you like me to create an other issue ?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
