### ISSUE TITLE
Issues with Xamarin Forms 4 using CollectionView in UWP project

### ISSUE THREAD

**Issue by sahadevgupta** [xamarin/Xamarin.Forms#6685]
Hello I'm facing some tricky bugs while trying to use the new CollectionView feature implemented in Xamarin Forms 4.
When i'm initializing the Datatemplate the entrie screen turn out white but if If I remove all the DataTemplate from CollectionView.ItemTemplate, just leaving it blank like this

`CollectionView.ItemsLayout>

</CollectionView.ItemsLayout>
<CollectionView.ItemTemplate>

            </CollectionView.ItemTemplate>
        </CollectionView>`

### Steps to Reproduce

1. create collectionview and use DataTemplate
`
<CollectionView.ItemsLayout>

</CollectionView.ItemsLayout>
<CollectionView.ItemTemplate>
<DataTemplate>
// some layout
</DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
` 

### Expected Behavior
Layout inside the DataTemplate should be visible

### Actual Behavior
Screen turns white

### Basic Information

- Version with issue: lastest stable version

**Comment by samhouts** [comment]
@sahadevgupta  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@sahadevgupta  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
