### ISSUE TITLE
[Bug] [WPF] ViewRenderer does not work properly with FrameworkElement derived native controls 

### ISSUE THREAD

**Issue by ChaseMarsh** [xamarin/Xamarin.Forms#6693]
### Description
The ViewRenderer contains _wcontrol field that uses 'as' to attempt casting Control to a System.Windows.Controls.Control and uses it to update IsEnabled, Focus, TabStop, TabIndex, and UpdateBackground. For custom controls that derive from FrameworkElement (like SkiaSharp's SKElement), _wcontrol will be null and therefore prevent IsEnabled, Focus, TabStop, TabIndex, and UpdateBackground from functioning.
### Steps to Reproduce

1. Create a custom Xamarin.Forms control 
2. Create a custom renderer for that control with a WPF custom control that derives from FrameworkElement
2. Set IsEnabled to false in Xamarin.Forms (for example) 
3. Notice the native control is not disabled.

### Expected Behavior
Native control is disabled (for example)

### Actual Behavior
Xamarin.Forms IsEnabled property is set to false, but the native control is still enabled

### Basic Information

- Version with issue: Xamarin.Forms v4.1.0.496342-pre2
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - WPF:   v4.1.0.496342-pre2

**Comment by ChaseMarsh** [comment]
Hi @samhouts, I have a fix for this and would like to create a PR. It is my first PR, so I need help with that rigmarole. I have a local branch that I'm unable to push to remote.

**Comment by samhouts** [comment]
@ChaseMarsh Wonderful! You will want to create a fork instead of cloning the repository. Then create a new branch on your fork. Put your changes on that new branch, and then submit a pull request from there. That should do it! Thanks!!
