### ISSUE TITLE
[Bug] [OSX] Latest VS for Mac needs net standard

### ISSUE THREAD

**Issue by GuardianCherubimJohn** [xamarin/Xamarin.Forms#6696]
### Description
After updating to latest VS for Mac (8.1.3 build 19) I get the following when building a MacOS project that uses a custom renderer, which uses the export attribute. It still works fine on IOS projects, just not on MacOS projects. It's a show stopper because I can't use custom renderers right now on OSX projects.  

`Error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. (CS0012)`

I tried adding NETStandard.library as a NuGet package manually, and also adding the following to the .csproj: 

```
<ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.Mac')) ">
   <Reference Include="netstandard" />
</ItemGroup>
```

However, neither worked.

### Steps to Reproduce
1. Load up a previously working MacOS project, or try to add a new one with a custom renderer that uses the export attribute.

### Expected Behavior
Compiles

### Actual Behavior
Doesn't compile

**Comment by samhouts** [comment]
@GuardianCherubimJohn When you look at your csprof file, do you happen to see something like this (version may vary) where the folder doesn't actually exist?
```
<ImportProject="..\..\packages\Xamarin.Forms.2.5.1.527436\build\netstandard1.0\Xamarin.Forms.props"Condition="Exists('..\..\packages\Xamarin.Forms.2.5.1.527436\build\netstandard1.0\Xamarin.Forms.props')"/>
```

When you add `<Reference Include="netstandard" />` to your macOS.csproj without the condition, does it work?

Finally, did you happen to convert your PCL to netstandard manually?

Thanks!

**Comment by GuardianCherubimJohn** [comment]
It was adding `<Reference Include="netstandard" />` that fixed it. There was no PCL to netstandard conversion afaik. Added this out of concern for others updating VS.

**Comment by samhouts** [comment]
@GuardianCherubimJohn Do I understand correctly that your problem is now resolved? Thanks!

**Comment by GuardianCherubimJohn** [comment]
Yes it is now it can be closed.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jgold6** [comment]
I am not sure this bug should be closed yet. 

I see the same issue was reported on the [forums](https://forums.xamarin.com/discussion/comment/382781#Comment_382781) when trying to add a `DependencyService`. I know mac support is in preview, but it seems to me that either the preview docs should be updated to note the need to add the `<Reference Include="netstandard" />` element to the mac .csproj file so that others don't run into the same issue. Or if CustomRenderers and DependencyService is not meant to be supported on Mac yet, then [this doc](https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status) should be updated to reflect that.

**Comment by GuardianCherubimJohn** [comment]
I agree, it at least needs to be documented for others, since it seems to be popping up in more than one place lately. The reference should already be included I would think without needing to edit the csproj, since we’re talking about .NET Standard here.

Side Note: the second docs page that jgold6 mentioned needs ImageButton status as it looks like it hasn’t been implemented yet on OSX last time I checked.

**Comment by PureWeen** [comment]
@GuardianCherubimJohn are you still having this issue with 8.2?

Also I'm thinking this issue is already being addressed here
https://github.com/xamarin/xamarin-macios/pull/6667

If 8.2 doesn't fix and that PR isn't related let me know and we'll get this ticket moved over to the macios GitHub

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/xamarin-macios/issues/6552
