### ISSUE TITLE
[Bug] ICommand not hit inside the DataTemplate

### ISSUE THREAD

**Issue by SanthiyaArulsamy** [xamarin/Xamarin.Forms#6699]
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by andreinitescu** [comment]
You gave no description, no reproduction steps and didn't attach any sample, so high chances are it will get closed soon.

**Comment by SanthiyaArulsamy** [comment]
Please close this
