### ISSUE TITLE
[Enhancement] Port the WkWebViewRenderer from iOS to MacOS

### ISSUE THREAD

**Issue by pellet** [xamarin/Xamarin.Forms#6709]
## Summary
The current webview renderer for macOS being used is legacy and can be replaced with the current iOS WKWebviewRenderer.  Not much code needs to be different for the iOS implementation and it will provide developers with an improved API.

## API Changes
The WKWebviewRenderer can be made default and the legacy webview can be made deprecated/opt-in.

**Comment by candidodmv** [comment]
Official Apple Notes:

_"The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020."_

[https://developer.apple.com/news/?id=12232019b](https://developer.apple.com/news/?id=12232019b)

**Comment by pellet** [comment]
I've got something working in my app if you guys want it to start with, I mostly reworked the iOS implementation to get it compiling for macos.

**Comment by Hurricane31337** [comment]
> 

Do you still have the code? I'd love to migrate to WkWebView on macOS this could be a great start.

**Comment by pellet** [comment]
I last touched in mid 2019, i don't remember what I was last working on, but I think I was trying to make it work with injecting javascript into pages.  Here it is anyway, hope it comes of some help :) https://gist.github.com/1e89dd55e0797425dea242ab428795dc

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
