### ISSUE TITLE
Xamarin Forms iOS - Portuguese Brazil folder

### ISSUE THREAD

**Issue by sarav78** [xamarin/Xamarin.Forms#6717]
Hello starting from Xamarin Forms 4.0, if we add resource file for Portuguese Brazil language
![Capture](https://user-images.githubusercontent.com/15906420/60393473-a8156300-9adb-11e9-805b-e5f9a1dfdd63.PNG)
 culture as "Resources.pt-BR.resx", upon compilation the framework creates folder in lowercase "pt-br", rather in uppercase "pt-BR", hence the resources for specific culture are ignored by iOS. it is happening only in iOS. Is there any fix available?

**Comment by sarav78** [comment]
is there any update or workaround on this

**Comment by samhouts** [comment]
@sarav78 Please submit this issue from Visual Studio using the Send Feedback option. Thanks!
