### ISSUE TITLE
[Bug] ListView blank cells when CachingStrategy="RetainElement" on Android

### ISSUE THREAD

**Issue by dmariogatto** [xamarin/Xamarin.Forms#6721]
### Description

When ListView `CachingStrategy="RetainElement"` some cells appear blank in Android when scrolling. Tested in iOS but seems fine. Using `RecycleElement` works as expected.

### Steps to Reproduce

1. Create ListView
2. Set CachingStrategy="RetainElement"
3. Start scrolling

### Basic Information

- Version with issue: 4.0.0.540366 
- Last known good version: 3.6.0.539721
- Affected Devices: tested and found issue with Android Pie, Nougat & Marshmallow

### Screenshots

![Blank view cells](https://raw.githubusercontent.com/dmariogatto/xf4-retainelement/master/screenshots/android.png)

### Reproduction Link

https://github.com/dmariogatto/xf4-retainelement

**Comment by leo-mck** [comment]
I am having this exact problem. I have multiple templates and use a `DataTemplateSelector` to show the correct one and `RecycleElement` and `RecycleElementAndDataTemplate` while correct the problem of the content not appearing, mess up with the layout of some templates. On 3.6 `RetainElement` and `RecycleElementAndDataTemplate` work as expected.

**Comment by samhouts** [comment]
closed by #6390

**Comment by mdmota** [comment]
Why did it close?????

**Comment by mdmota** [comment]
After upgrading XF to 4.3.0 and replacing listivew with collectionView, the problem continues
https://github.com/xamarin/Xamarin.Forms/issues/8199#issuecomment-545937143

**Comment by mdmota** [comment]
Closed in which version?
