### ISSUE TITLE
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. occurred #713[Bug] 

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6722]
Hi,

I am trying below code to Pick a Photo but getting this error on the MessagingCenter.Send line:

> Unhandled Exception:
> 
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. occurred
> 

**** The TakePhotoAsync MessagingCenter.Send is working perfectly without error..

Here is the code:

```
async void ImageKidPhotoTapped(object sender, System.EventArgs e)
{
    string action = await DisplayActionSheet("كيف تريد تحديث الصورة؟", "إلغاء", null, "الكاميرا", "الألبوم");

    if (action == "الكاميرا")
    {
        await CrossMedia.Current.Initialize();

        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
        {
            await DisplayAlert("No Camera", ":( No camera available.", "OK");
            return;
        }

        var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
        {
            AllowCropping = true,
            SaveToAlbum = false,
            Directory = "JafariaImages",
            Name = "StudentPhoto.png"
        });

        if (file == null) return;

        MyKidPhoto.Source = ImageSource.FromStream(() =>
        {
            var stream = file.GetStream();
            return stream;
        });

        new_photo = file;

        MessagingCenter.Send<object>(this, "UpdateStudentPhoto");
    }
    else if (action == "الألبوم")
    {
        if (!CrossMedia.Current.IsPickPhotoSupported)
        {
            await DisplayAlert("Photos Not Supported", ":( Permission not granted to photos.", "OK");
            return;
        }

        var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
        {
            PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
        });


        if (file == null)
            return;

        MyKidPhoto.Source = ImageSource.FromStream(() =>
        {
            var stream = file.GetStream();
            file.Dispose();
            return stream;
        });

        new_photo = file;

        // HERE is my Error Thrown;
         MessagingCenter.Send<object>(this, "UpdateStudentPhoto");
    }
}

```
Thanks,
[Jassim](https://www.softnames.com)

**Comment by knocte** [comment]
> getting this error on the MessagingCenter.Send line:

Please paste the entire exception, include all stack traces and all innerExceptions, not just the first line. (This is usually achieved by printing `ex.ToString()`)

**Comment by jrahma** [comment]
```
try
{
    MessagingCenter.Send<object>(this, "UpdateStudentPhoto");
}
catch (Exception ex)
{
    Console.Write(ex.ToString());
}

```


> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.Exception Thrown is: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ObjectDisposedException: Cannot access a disposed object.
>   at Plugin.Media.Abstractions.MediaFile.GetStream () [0x00008] in <5939e997f291496f805023da28f3a447>:0 
> 
> 07-02 14:45:47.817 I/mono-stdout(20121):   at Plugin.Media.Abstractions.MediaFile.GetStream () [0x00008] in <5939e997f291496f805023da28f3a447>:0 
> 07-02 14:45:47.817 I/mono-stdout(20121):   at Al_Sadiq.Kid.<.ctor>b__13_0 (System.Object sender) [0x00080] in C:\Users\jrahm\Source\Repos\Al_Sadiq\Al_Sadiq\Al_Sadiq\Kid.xaml.cs:142 
>   at Al_Sadiq.Kid.<.ctor>b__13_0 (System.Object sender) [0x00080] in C:\Users\jrahm\Source\Repos\Al_Sadiq\Al_Sadiq\Al_Sadiq\Kid.xaml.cs:142 
>   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
>    --- End of inner exception stack trace ---
>   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
>   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
>   at Xamarin.Forms.MessagingCenter+Subsc
> 07-02 14:45:47.817 I/mono-stdout(20121):   at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)ription.InvokeCallback (System.Object sender, System.Object args) [0x00064] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:94 
>   at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:217 
>   at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender] (TSender sender, System.String message) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:127 
>   at Xamarin.Forms.MessagingCenter.Send[TSender] (TSender sender, System.String message) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:120 
> 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0003b] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
> 07-02 14:45:47.818 I/mono-stdout(20121):    --- End of inner exception stack trace ---
> 07-02 14:45:47.818 I/mono-stdout(20121):   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00054] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <3a61d48d66dd458fa0b64990b6c8f8cc>:0 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at Xamarin.Forms.MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args) [0x00064] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:94 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at Xamarin.Forms.MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args) [0x0006b] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:217 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Send[TSender] (TSender sender, System.String message) [0x00013] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:127 
> 07-02 14:45:47.818 I/mono-stdout(20121):   at Xamarin.Forms.MessagingCenter.Send[TSender] (TSender sender, System.String message) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\MessagingCenter.cs:120 
> 07-02 14:45:47.826 W/libEGL  (20121): EGLNativeWindowType 0x7c96d7e010 disconnect failed
> 07-02 14:45:47.826 D/OpenGLRenderer(20121): endAllActiveAnimators on 0x7c91257200 (RippleDrawable) with handle 0x7c9542af60
> 07-02 14:45:47.846 V/InputMethodManager(20121): Reporting focus gain, without startInput
>

**Comment by kvpt** [comment]
From your stacktrace the exception is caused by your file.Dispose.

```cs
MyKidPhoto.Source = ImageSource.FromStream(() =>
{
      var stream = file.GetStream();
      file.Dispose(); // <- here
      return stream;
});
```

If you dispose your file, the stream associated with the file will also be disposed.

**Comment by samhouts** [comment]
@jrahma Given the stacktrace, this exception is from either part of your code (see @kvpt 's comment) or part of the Plugin's code. Thank you!
