### ISSUE TITLE
[Bug] [WPF] Images size and position

### ISSUE THREAD

**Issue by ZeProgFactory** [xamarin/Xamarin.Forms#6723]
### Description
Image sizes and positions not always correctly in WPF.

### Steps to Reproduce
If you place an image directly in a page
```
<ContentPage … >
   <Image x:Name="image" HorizontalOptions="Center" VerticalOptions="Center" />
</ContentPage>
```

### Expected Behavior
As in UWP the image should be placed in the center of the page and the size should not vary in function of the page size.

### Actual Behavior
The image is placed on the left side of the page, and if you resize the page, the image will resize in function of the page height.

### Basic Information
- Versions with issue:  Xamarin.Forms (Xamarin.Forms.Platform.WPF)  4.0.0.540366, 3.6.0.539721
- IDE: VS 2019

### Screenshots
![image](https://user-images.githubusercontent.com/17034030/60403657-6ef2f680-9ba0-11e9-8e47-3b76e98ee712.png)

### Reproduction Link
https://github.com/ZeProgFactory/XFTestWPF_Image

**Comment by jsuarezruiz** [comment]
I have done some tests. If the image is children of a Layout (for example, a Grid), the position is correct. If it is directly the content of the page (without using a Layout), in WPF it is not positioned correctly.
In UWP it works correctly in both cases.

**Comment by NebulaSleuth** [comment]
I am having issues even when inside a grid and the Image is set to AspectFit

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
