### ISSUE TITLE
[Bug, SearchHandler] OnFocused is never hit

### ISSUE THREAD

**Issue by ArgusMagnus** [xamarin/Xamarin.Forms#6725]
### Description
`OnFocused` is never hit.

### Steps to Reproduce

1. Add a `SearchHandler` to a page
2. Set a breakpoint in SearchHandler.OnFocused.
3. Interact with the search box, and observe that your breakpoint is never hit.

### Basic Information

- Version with issue: Latest
- IDE: VS on Windows (latest)
- Platform Target Frameworks: 
  - iOS:  latest
  - Android: latest

**Comment by samhouts** [comment]
@ArgusMagnus  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@ArgusMagnus  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ArgusMagnus** [comment]
This issue is still affecting me. To reproduce follow the steps in **Steps to Reproduce** in my initial post.
