### ISSUE TITLE
[Bug] System.NotSupportedException in Xamarin.Forms.Platform.Android.FormsAppCompatActivity constructor

### ISSUE THREAD

**Issue by rayita** [xamarin/Xamarin.Forms#6729]
### Description

We got several crash reports from one of our production applicationa (vía AppCenter) with a System.NotSupportedException inside Xamarin.Forms.Platform.Android.FormsAppCompatActivity constructor

### Steps to Reproduce

We are unable to reproduce issued in lab.
Crash reports are from several Android devices all of them with Android 7.0 or Android 8.0.0

### Basic Information

- Version with issue: Xamarin.Forms 3.6.0.344457
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: Android 9.0
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: Several

### Crash Data

Xamarin Exception Stack:
System.NotSupportedException: Could not activate JNI Handle 0x7fed1d4640 (key_handle 0x90d1640) of Java type 'md5762378f8c09d74edb7a4b466868be751/MainActivity' as managed type 'MyApp.Droid.MainActivity'.
  at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) <0x71238e35d4 + 0x004e8> in <997c8ee633674b33850b8b9a1f60abeb>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.2(intptr,intptr,intptr,intptr,intptr,intptr)
--- End of inner exception stack trace ---
  System.NullReferenceException: Object reference not set to an instance of an object
    at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) <0x712429be34 + 0x001cc> in <b2c4c6afbe1d4c5c944b7013191760f3>:0
    at System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) <0x712429b16c + 0x00017> in <b2c4c6afbe1d4c5c944b7013191760f3>:0
    at Xamarin.Forms.MessagingCenter.InnerSubscribe (System.Object subscriber, System.String message, System.Type senderType, System.Type argType, System.Object target, System.Reflection.MethodInfo methodInfo, Xamarin.Forms.MessagingCenter+Filter filter) <0x7123f331fc + 0x0018b> in <209f66ed8fe04cb6a815feb8c3b62471>:0
    at Xamarin.Forms.MessagingCenter.Xamarin.Forms.IMessagingCenter.Subscribe[TSender,TArgs] (System.Object subscriber, System.String message, System.Action`2[T1,T2] callback, TSender source) [0x0005a] in <209f66ed8fe04cb6a815feb8c3b62471>:0
    at Xamarin.Forms.MessagingCenter.Subscribe[TSender,TArgs] (System.Object subscriber, System.String message, System.Action`2[T1,T2] callback, TSender source) [0x00005] in <209f66ed8fe04cb6a815feb8c3b62471>:0
    at Xamarin.Forms.Platform.Android.PopupManager+PopupRequestHelper..ctor (Android.App.Activity context) <0x712325e8c4 + 0x0009b> in <55d887a826354427bbccdfd44b6f9211>:0
    at Xamarin.Forms.Platform.Android.PopupManager.Subscribe (Android.App.Activity context) <0x712325e500 + 0x000d3> in <55d887a826354427bbccdfd44b6f9211>:0
    at Xamarin.Forms.Platform.Android.FormsAppCompatActivity..ctor () <0x71232521f0 + 0x0001b> in <55d887a826354427bbccdfd44b6f9211>:0
    at MyApp.Droid.MainActivityBase..ctor (System.Int32 tabBar, System.Int32 toolbar) <0x71203b44ac + 0x00017> in <4bd218e774274b6b98f0a33b91005349>:0
    at MyApp.Droid.MainActivity..ctor () <0x71203a2f30 + 0x0001b> in <4bd218e774274b6b98f0a33b91005349>:0
    at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.34(intptr,object[])
    at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) <0x71238e35d4 + 0x00257> in <997c8ee633674b33850b8b9a1f60abeb>:0

Thread 1:
0   dalvik.system.VMStack.getThreadStackTrace(VMStack.java:-2)
1   java.lang.Thread.getStackTrace(Thread.java:1556)
2   java.lang.Thread.getAllStackTraces(Thread.java:1606)
3   com.microsoft.appcenter.crashes.Crashes.saveUncaughtException(Crashes.java:949)
4   com.microsoft.appcenter.crashes.WrapperSdkExceptionManager.saveWrapperException(WrapperSdkExceptionManager.java:55)
5   mono.android.TypeManager.n_activate(TypeManager.java:-2)
6   mono.android.TypeManager.Activate(TypeManager.java:7)
7   md5762378f8c09d74edb7a4b466868be751.MainActivity.<init>(MainActivity.java:22)
8   java.lang.Class.newInstance(Class.java:-2)
9   android.app.Instrumentation.newActivity(Instrumentation.java:1178)
10  android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3191)
11  android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
12  android.app.ActivityThread.-wrap12
13  android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
14  android.os.Handler.dispatchMessage(Handler.java:108)
15  android.os.Looper.loop(Looper.java:166)
16  android.app.ActivityThread.main(ActivityThread.java:7529)
17  java.lang.reflect.Method.invoke(Method.java:-2)
18  com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
19  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

Thread 1004:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:178)
2   java.lang.Daemons$Daemon.run(Daemons.java:103)
3   java.lang.Thread.run(Thread.java:784)

Thread 1005:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:235)
5   java.lang.Daemons$Daemon.run(Daemons.java:103)
6   java.lang.Thread.run(Thread.java:784)

Thread 1006:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:386)
2   java.lang.Thread.sleep(Thread.java:327)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:345)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:371)
5   java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:284)
6   java.lang.Daemons$Daemon.run(Daemons.java:103)
7   java.lang.Thread.run(Thread.java:784)

Thread 1011:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1017:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:422)
2   com.google.android.gms.internal.zzccv.run

Thread 1018:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1020:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1168)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.poll(ScheduledThreadPoolExecutor.java:1147)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1086)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:784)

Thread 1021:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1022:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:379)
2   android.os.Looper.loop(Looper.java:144)
3   android.os.HandlerThread.run(HandlerThread.java:65)

Thread 1030:
0   java.lang.Object.wait(Object.java:-2)
1   aeg.a(:com.google.android.gms.dynamite_dynamitemodulesc@17785051@17.7.85 (040408-253824076):13)
2   adq.run(:com.google.android.gms.dynamite_dynamitemodulesc@17785051@17.7.85 (040408-253824076):6)
3   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
4   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
5   java.lang.Thread.run(Thread.java:784)

Thread 1031:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2161)
2   sun.misc.Unsafe.park(Unsafe.java:358)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:230)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2101)
5   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1132)
6   java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1113)
7   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1087)
8   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1147)
9   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10  java.lang.Thread.run(Thread.java:784)

Thread 1032:
0   md51a703375952c0e445ec325871c18eea0.FcmMessagingService.n_onMessageReceived(FcmMessagingService.java:-2)
1   md51a703375952c0e445ec325871c18eea0.FcmMessagingService.onMessageReceived(FcmMessagingService.java:29)
2   com.google.firebase.messaging.FirebaseMessagingService.handleIntent
3   com.google.firebase.iid.zzg.run
4   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
5   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
6   java.lang.Thread.run(Thread.java:784)

**Comment by samhouts** [comment]
@rayita I see you're unable to reproduce. Please let us know if that changes! Thanks!

**Comment by samhouts** [comment]
@rayita  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
