### ISSUE TITLE
[Enhancement] Picker image support

### ISSUE THREAD

**Issue by SFSteve** [xamarin/Xamarin.Forms#6733]
## Summary
The ability to add images to picker lines would be great. Android (and iOS?) already do this natively but Forms handles images way better.

Something along the lines of:
&lt;Picker ItemsSource="ListObject" ItemDisplayBinding="ItemName" ImageDisplayBinding="ItemImage"/&gt;

## Intended Use Case
When selecting a language, a flag for the country. Or an icon to show whether a printer is online when choosing which one to send a print job to.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
