### ISSUE TITLE
[iOS] Consider using IndexPath.Item instead of IndexPath.Row in CollectionView implementation

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#6737]
I've seen various places where accessing CollectionView items are done via the `Row` property, but the correct property to check is `Item`. For more information, see https://stackoverflow.com/questions/14765730/nsindexpath-item-vs-nsindexpath-row.

**Comment by hartez** [comment]
Waiting for #6590 to get merged (which will fix most of these), then I'll clean up the last 3 instances.
