### ISSUE TITLE
Cannot able to set shell as navigation page (Android) , its working fine on iOS

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/Xamarin.Forms#6743]
### Description
I am not able to set shell as navigation page on android just try to write MainPage = new NavigationPage(new AppShell()); The shell opens as blank page  when I set shell as navigation page on android , But on iOS it works fine. when I set MainPage = new AppShell(); Everything works fine. I want my custom navigation to pushpage when click on some button on shell . I think it's a bug since it's working  fine on iOS.  I need to set shell as a navigation page to change status bar dynamically else it will not work also . When I user GoTOAsync to navigate page the bottom bar on shell do not hide I want to hide that when user navigate from shell to other page .

But that's not the question we should be able to set shell as navigation page since other can have different requirement rather then using shell inbuilt navigation 

### Steps to Reproduce

1. MainPage = new NavigationPage(new AppShell());  on your App.cs
2. 
3. 

### Expected Behavior
Shell should open fine
### Actual Behavior
Shell open as blank page on android

**Comment by samhouts** [comment]
@sarthak199526  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sarthak199526** [comment]
Ya sure

**Comment by sarthak199526** [comment]
Hi rather then repo just replace MainPage = new AppShell(); to MainPage = new NavigationPage(new AppShell()); on App.cs of official shell sample(Xaminals) on Microsoft documentation site
Here's the repo link https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals/

After replacement of website just Try to run the project on android you will find the bug .

**Comment by sarthak199526** [comment]
[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3358247/Xaminals.zip)

**Comment by sarthak199526** [comment]
Just Run the above project on android I have changes only one line of code on app.cs

**Comment by sarthak199526** [comment]
Any update on this issue. I need to fix my navigation ASAP

**Comment by elmerls** [comment]
So what happened with this 'issue'? im having the same problem

**Comment by saurabh1993-05** [comment]
Facing same problem please confirm whether this is a real issue or we are doing something wrong.

**Comment by jsuarezruiz** [comment]
Duplicate with #6697

**Comment by jsuarezruiz** [comment]
If the error comes from trying to change a Shell to a NavigationPage, look at this related issue: https://github.com/xamarin/Xamarin.Forms/issues/6697
