### ISSUE TITLE
How can we change device status bar color in shell when when we have Shell.NavBarIsVisible="false"

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/Xamarin.Forms#6746]
How can we change device status bar color in shell when when we have Shell.NavBarIsVisible="false" since in this case Shell.BackgroundColor property does not effect on status color but it change the device status bar color according to shell background color when Shell.NavBarIsVisible="true" is set .

**Comment by Phenek** [comment]
For me I am unable to have a transparent status bar, it's always colorised..

**Comment by kgouraw** [comment]
Please try to use UIStatusBarStyle in iOS AppDelegate, it worked for me. Ex:
uiApplication.SetStatusBarStyle(UIStatusBarStyle.DarkContent, true)

**Comment by toverux** [comment]
I'm here because I was seeking for an equivalent of `iOs:NavigationPage.IsNavigationBarTranslucent="True"` for Xamarin Shell.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
