### ISSUE TITLE
[Bug] Reduced font sizes with Xamarin.Forms 4.1.0.555618

### ISSUE THREAD

**Issue by TonyC5** [xamarin/Xamarin.Forms#6749]
### Description
After upgrading from Xamarin.Forms 4.0.0.540366 to 4.1.0.555618, the font sizes of my app Labels have reduced.  It appears that where I have specified FontSize="Medium", the displayed font size is FontSize="Small"

### Steps to Reproduce

1. Upgrade Xamarin.Forms 4.0.0.540366 to 4.1.0.555618
2. Rebuild App and deploy to iOS device
3. Run app and observe reduced label font sizes

### Expected Behavior
Expected to upgrade without a change in font sizes

### Actual Behavior
Upgrade of Xamarin.Forms changed label font sizes

### Basic Information
Visual Studio Community for Mac 2019 Version 8.1.3 (build 19)

- Version with issue: Xamarin.Forms 4.1.0.555618
- Last known good version: Xamarin.Forms 4.0.0.540366
- IDE: Visual Studio Community for Mac 2019 Version 8.1.3 (build 19)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![Font-4 0 0 540366](https://user-images.githubusercontent.com/28421182/60521072-8f13da00-9cb4-11e9-8a63-1f3d4b82412d.jpg)
![Font-4 1 0 555618](https://user-images.githubusercontent.com/28421182/60521073-8f13da00-9cb4-11e9-81ad-b7eaa8dab3ab.jpg)

**Comment by chasingwatts** [comment]
Having same issue after deployment w/ v4.1.0.555618.  FYI

**Comment by jfversluis** [comment]
I can't seem to reproduce it with a File > New app with just the "Welcome to Xamarin.Forms!" text. So maybe some other layout elements come into play here? Would it be possible to provide a sample repro app where we would just need to update to 4.1 to see the issue show up?

**Comment by TonyC5** [comment]
@jfversluis - My dev environment is not configured to build/deploy the XamlSample for iOS (I'm doing my testing on an actual iPhone 4s (iOS 9.3.5) since it's the oldest platform I support.  I will take the time if necessary to configure for dev environment for the sample, but first, could you try modifying MainPage.xaml by adding FontSize="Medium" as follows:

    <Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="Center" VerticalOptions="CenterAndExpand" FontSize="Medium" />

**Comment by geskill** [comment]
I experienced the same problem and found that is related to the new accessibility feature. Follow the link to enable the old behavior: https://docs.microsoft.com/de-de/xamarin/xamarin-forms/platform/ios/named-font-size-scaling

**Comment by TonyC5** [comment]
@geskill - Thank you for posting your solution - that makes sense.

@jfversluis - Does @geskill's post provide the information that you need to restore the default behavior of Xamarin.Forms?  Our production environment is running Xamarin.Forms 3.6 until this is resolved.  Thank you.

**Comment by samhouts** [comment]
@TonyC5 This was a breaking change that we introduced to allow better accessibility for end users. Accessibility must always be our default. We introduced the platform specific option that @geskill mentioned in https://github.com/xamarin/Xamarin.Forms/issues/6749#issuecomment-509272279 to allow you to revert to the original behavior if necessary, so that is our recommendation at this time. We apologize for the inconvenience, but we hope it is not a blocker for you. The platform specific is at the application level, so you need only set it once.

Thank you!

**Comment by TonyC5** [comment]
@samhouts - That sounds like a solution that restores the original appearance of our app; however I don't want our app to lose the accessbility functionality that you've worked so hard to release with X.F 4.  Is the "correct" fix for us to increase the named font size in our app (e.g. from Medium to Large), thereby allowing the font to be controlled by iOS accessibility?  I'd appreciate your advice about the best way for us to modify our app for X.F 4.  Thank you.

**Comment by samhouts** [comment]
@TonyC5 Yes, that would be my recommendation. Please let us know how that goes! Thanks!!
