### ISSUE TITLE
Bottom tab bar moves above when comes back from any page which have Shell.TabBarIsVisible="false"

### ISSUE THREAD

**Issue by sarthak199526** [xamarin/Xamarin.Forms#6750]
I found a annoying issue I have two pages one in which I have bottom tabs and another page with Shell.TabBarIsVisible="false" when I use GoToAsync to navigate to page which have Shell.TabBarIsVisible="false" till now every thing is fine navbar become disable . Problem arise when I go back to page which have bottom tab bar when that page appear tabbar moves upward from it's original place and after a second it's goes back to position when it should be when page appear . I have created a video you can check that 

Video Link :  https://drive.google.com/open?id=19qlZmkQLZKRaGBGDV0rb3q7doZanlxqr

**Comment by samhouts** [comment]
@sarthak199526  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sarthak199526** [comment]
Ya sure

**Comment by sarthak199526** [comment]
[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3358308/Xaminals.zip)

**Comment by sarthak199526** [comment]
1. Run the above project on iOS
2. Click on random menu item on flyout
3. And then got back using top navigation bar
You will find bottom bar took a little bit more time to comes to it original position then it should
On android it is little bit fine though I tested on nokia 6.1 plus which has 4gb ram it might also take time on other low ends android device for now just check on iOS you will find it

**Comment by jsuarezruiz** [comment]
@sarthak199526 Thanks for the repro sample. I've been thoroughly testing it on iOS. I see clearly the problem that you expose in the video but not in the sample.

![issue6750-01](https://user-images.githubusercontent.com/6755973/61371563-4c95f400-a895-11e9-868e-36c4a83d5f25.gif)

Could you give some feedback? (version, emulator, etc). Thanks in advance!

**Comment by sarthak199526** [comment]
In my sample Click on random menuItem it is a second last item in Flyout and then go back using navigation bar . Currently you are clicking on the FlyoutItem please click on second last menuItem which has text Random . Also Pleas use my attached sample

**Comment by sarthak199526** [comment]
@jsuarezruiz  are you able to replicate the issue when you follow my above suggested steps ?

**Comment by jsuarezruiz** [comment]
I can not reproduce it :worried:
I am using your example and following your steps (tap on random menu item and navigate back).
![issue6750-03](https://user-images.githubusercontent.com/6755973/61452478-1a02fe80-a95c-11e9-8d14-f1207de2da63.gif)

**Comment by sarthak199526** [comment]
These any on back looks new have you updated xamarin forms package I am not why it's not replicating now I will try on my app and let you know if issue fixed

**Comment by ChasakisD** [comment]
@jsuarezruiz A weird behavior is happening on Android an not on iOS and I think that may be related to this issue. When from a Tab you navigate to another page with TabBarIsVisible set to false and then you navigate back, you are actually seeing the following steps:

1. TabBar went invisible
2. Navigate to
3. Navigate back
4. TabBar went visible. 

I am attaching a video in order to make myself clear for what is happening on Android.

[Reproduction video](https://stdntpartners-my.sharepoint.com/:v:/g/personal/dionysis_chasakis_studentpartner_com/EYYWjMVOEUdPqfKakVbQKx0BpsbZqv4IVITIJzbS_doPWw?e=c46ihy)
