### ISSUE TITLE
Cannot create NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(sessionIdentifier)

### ISSUE THREAD

**Issue by KMWenyon** [xamarin/Xamarin.Forms#6751]
### Description
While trying to create an AVAssetDownloadUrlSession with a custom AVAssetDownloadDelegate (to handle NTLM authentication challenge to view video from a secure or protected corporate resource behind firewall), creating a NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(sessionIdentifier);  returns null. 

### Steps to Reproduce
Please see the following code:
string mediaIdentifier = _mediaItemToPlay?.MediaId ?? Guid.NewGuid().ToString();
string sessionIdentifier = Xamarin.Essentials.AppInfo.PackageName + "." + mediaIdentifier;

_cgAVAssetDownloadDelegate = MyCustomAVAssetDownloadDelegate();

NSUrlSessionConfiguration _nsUrlBackgroundSessionConfiguration = NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(sessionIdentifier);
*** Code fails here _nsUrlBackgroundSessionConfiguration is null ***

_avAssetDownloadUrlSession = AVAssetDownloadUrlSession.CreateSession(_nsUrlBackgroundSessionConfiguration, _cgAVAssetDownloadDelegate, NSOperationQueue.MainQueue);

### Expected Behavior
Call to NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(sessionIdentifier) is expected to return a valid backgroundSessionConfiguration.

### Actual Behavior
Call to NSUrlSessionConfiguration.CreateBackgroundSessionConfiguration(sessionIdentifier)  returns null.

### Basic Information
- Mac OS X: 10.14.5, Darwin 18.6.0 Darwin Kernel Version 18.6.0
- Version with issue: VS for MAC 8.1.3 (build 19)
- Last known good version: None
- IDE: VS for MAC 8.1.3 (build 19)
- NetStandard.Library: 2.0.3
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS: 12.10.0.157, Deployment Target 10.3 thru 12.2
  - Android: Xamarin.Android: 9.3.0.23, Deployment Target Min: 4.4 (19) - 9.0 (28)
  - UWP: .NetCore Runtime Version: 2.1.11, SDK Version: 2.1.700   
- Android Support Library Version: SDK Tools Version: 26.1.1, SDK Platform Tools Version: 29.0.1, SDK Build Tools Version: 28.0.3, Java SDK: microsoft_dist_openjdk_1.8.0.25
- Apple Developer Tools: Xcode 10.2.1 (14490.122)
- Nuget Packages: 
    Newsoft.Json v12.0.2
    Xamarin.Build.Download v0.4.11
    Xamarin.Forms v4.0.0.540366
    Xamarin.Forms.Visual.Material v4.0.0.540366
    Xamarin.Essentials v1.1.0
    Xamarin.iOS.MaterialComponents v72.2.0.1
- Affected Devices: All iOS devices iPhone and iPad

**Comment by alanag13** [comment]
This looks like it should probably be filed under https://github.com/xamarin/xamarin-macios

**Comment by KMWenyon** [comment]
Should I re-file it or can you change in your side?

**Comment by alanag13** [comment]
@KMWenyon I'm not a Xamarin team member, sorry, was just trying to steer you in the right direction. You should re-file over there.

As an aside, whenever your problem is with iOS or Android classes directly (like NSUrlSession), the problem is probably on that platform's Xamarin implementation side and not with Xamarin.Forms.

**Comment by KMWenyon** [comment]
File new issues under Xamarin-macios #6478
https://github.com/xamarin/xamarin-macios/issues/6478
