### ISSUE TITLE
[Enhancement] Add CarouselView ItemChanged Event

### ISSUE THREAD

**Issue by ahoefling** [xamarin/Xamarin.Forms#6756]
## Summary
Created as follow up from PR #5754 and the spec is very similar to #4654

The `CarouselView` is a specified type of `CollectionView` that contains 1 row horizontal scrollable items. Currently the API provides a `ScrollTo()` method which provides a very useful API for updating the current position of the `CarouselView`. However, the API does not provide any events that can notify the shared code that the `CarouselView` was updated.

The goal of this enhancement is to add a new event that can attach listeners in shared code and be notified when the user performs a swipe action on the `CarouselView`. This effectively closes the gap in the API and allows the code to both force the current item to update and listen for when it updates.

## API Changes
In the shared code add a new event that will be used for notifying when an item has changed

```c#
public class CarouselView : ItemsView
{
    public event EventHandler<SelectedItemChangedEventArgs> ItemChanged;
}
```

I have documented out how this could be applied to `ItemsView` https://github.com/xamarin/Xamarin.Forms/pull/5754#discussion_r296432557. After discussion, I believe this to be best for the `CarouselView` and similar steps apply. 

### Android Implementation
The Android Implementation will rely on code very similar to #5754. That PR handles calculations that determine the center most item in a `CollectionView`. This implementation can leverage that same code and determine when the center item has changed and then fire the event in the shared code.

### iOS Implementation
I haven't researched how the iOS implementation will work, but there are thoughts in #4654

## Intended Use Case
Consider this scenario:
You have an app with a `CarouselView` of 10 items:

```
[0] [1] [2] [3] [4] [5] [6] [7] [8] [9]
```

Currently the screen is rendering item 
```
[4]
```

The user swipes the screen and final item rendered is

```
[1]
```

The result should be an event that can notify the shared code that the selected item has changed which may update other items on the page.

### Description
Consider an app where the rest of the screen is dependent on the currently selected item in the `CarouselView`. A mechanism to update when the user swipes will be very helpful.

# Implementation Notes
I have taken this spec and implemented it in a current project for **android** only. The API works very nicely in the shared code to receive events when the user performs a swipe action on the `CarouselView`.

Follow up items could be adding properties for 
* SelectedItem
* SelectedIndex

but those items are not part of this proposal

**Comment by kingces95** [comment]
I cooked one up a long time ago that had these events https://www.nuget.org/packages/Xamarin.Forms.CarouselView/2.3.0-pre2

The UITest may still be useful...

**Comment by rmarinho** [comment]
Hi, we have that 

```
public event EventHandler<CurrentItemChangedEventArgs> CurrentItemChanged;
``` 

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Items/CarouselView.cs#L201
