### ISSUE TITLE
[UWP] TabbedPage title padding broken in 4.0

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#6757]
### Description

Padding around the TextBlock displaying the child pages' Titles in a UWP TabbedPage was lost in 4.0.0.

### Steps to Reproduce

1. Create new project in VS2019 from Xamarin.Forms Tabbed template (make sure to check UWP box)
2. Run on UWP and see that there is some padding around the page title text
3. Upgrade to Xamarin.Forms 4.0.0-pre10 or higher
4. Run and see that padding is gone.

### Expected Behavior

Consistent padding between versions

### Actual Behavior

Padding is gone

### Basic Information

- Version with issue: 4.0.0-pre10 -> 4.1.0
- Last known good version: 3.6.0-sr4
  - Stable: 3.6.0-sr4
  - Pre-release: 4.0.0-pre9
- IDE: Visual Studio Entreprise 2019, version 16.0.3
- Platform Target Frameworks: 
  - UWP: Target 17763, Minimum 16299

### Screenshots
Before (3.6.0)
![](https://user-images.githubusercontent.com/6132629/60547081-6f94a580-9ce4-11e9-85b7-65055dc193e9.png)
![Technician3 6](https://user-images.githubusercontent.com/6132629/60547518-8c7da880-9ce5-11e9-9cc2-58c81f1745ce.png)

After (4.0.0)
![](https://user-images.githubusercontent.com/6132629/60547104-80451b80-9ce4-11e9-9f63-d3d185bab1b7.png)
![Technician4 1](https://user-images.githubusercontent.com/6132629/60547522-90112f80-9ce5-11e9-9868-fd33fac3562b.png)

### Reproduction Link

[UWPTabTitlePadding.zip](https://github.com/xamarin/Xamarin.Forms/files/3352354/UWPTabTitlePadding.zip)

**Comment by MitchBomcanhao** [comment]
I get that sort of issue when using tab icons, the labels get squashed to the bottom.
As it looks terribe, I'm disabling tab icons for UWP by adding this platform specific bit to each tabbedpage.
```
xmlns:windows="clr-namespace:Xamarin.Forms.PlatformConfiguration.WindowsSpecific;assembly=Xamarin.Forms.Core"
windows:TabbedPage.HeaderIconsEnabled="false"
```

**Comment by jcmanke** [comment]
@MitchBomcanhao Thanks, using that platform specific makes it look like it did before.
