### ISSUE TITLE
CollectionView Scrolling causing some Views to Disappear

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/Xamarin.Forms#6767]
When calling the ScrollTo method on CollectionView some views seem to dissapear - only tested on android. This seems to be random and doesnt occur all the time.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019 Community Version 16.1.5
- Platform Target Frameworks: 
  - iOS:  Untested
  - Android: compile v9.0 
  - UWP:  Untested.
- Xamarin Forms Version: 4.1.0.555618

### Screenshots

I scroll down and up then click the 'Click to scroll' to call the ScrollTo method which scrolls right down and youl notice that some views in the last item dont display correctly and also scrolling back up the first row also.

![ezgif com-add-text](https://user-images.githubusercontent.com/5468757/60581526-1c514e80-9ddb-11e9-9217-518b545b33fc.gif)

### Reproduction Link

[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3354325/Sample.zip)

**Comment by kvpt** [comment]
I confirm the issue.
This seems to only occur when in landscape.
And is can be trigerred by manuel scroll too.

My guess is that the issue was the same as #6355 or #5838.
So I cherry picked the change in PR #6390 and after that impossible to reproduce it.
So it's confirm that it's not directly a collection view problem but a layout recycling problem, and that it's fixed by #6390.

**Comment by sarthak199526** [comment]
I am also facing this issue when can we have an update to fix this issue it's really slowing down my app release thanks

**Comment by fabcall** [comment]
I can confirm it's not restricted to landscape, I had the same problem with horizontal CollectionView.

**Comment by rarelyleemallon** [comment]
Happens on the CarouselView also for Labels within the data template, tested with manual scrolling. views can re-appear once scrolled back too.

**Comment by samhouts** [comment]
closed by #6390
