### ISSUE TITLE
[Enhancement]  Switch Text Property

### ISSUE THREAD

**Issue by DaraOladapo** [xamarin/Xamarin.Forms#6768]
## Summary
The switch control should have a Text property alongside all possible customizations of a Label control

## API Changes

Currently this is how I implement my switch with information.
` <StackLayout Orientation="Horizontal">`
                          `<Switch x:Name="SendConfirmationEmailCheck" />`
                            `<Label Text="Send me a confirmation email" Style="{DynamicResource EntryLabelStyle}" />`
                        `</StackLayout>`

It would be nice to have something like
`<Switch x:Name="SendConfirmationEmailCheck" Text="Send me a confirmation email" TextStyle="{DynamicResource EntryLabelStyle}"/>`

 In C#, the declaration would be something like 
`var SendConfirmationEmailCheck=new Switch(){Text="Send me a confirmation email"};`

## Intended Use Case

- Setting text properties to switch at declaration without having to use more controls
- Setting style to the text property either from XAML or C#

**Comment by MitchBomcanhao** [comment]
eg UWP has two properties for the switch text, with On and Off values. Might as well use a similar pattern here.

**Comment by oyebodeoridota** [comment]
I agree. There needs to be an On and Off text property.

**Comment by davidbuckleyni** [comment]
Plus one for this also should be easier to changed the color and height and width of the switch.

**Comment by StephaneDelcroix** [comment]
I understand the need here, but here's what bothers me:
- support in platforms for this control is not uniform
- the layout preferences (where to put the label and the switch relatively to each other) aren't set, and will depend from user to user.

So I don't see us providing a control, backed with platform renderers for this. Instead, I think this should be implemented using `TemplatedView`, aggregating a Label and a switch. This way, the layout will be modifiable by switching the ControlTemplate.

**Comment by djordje200179** [comment]
Any progress?

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
