### ISSUE TITLE
[Bug] Listview Image unreliable load when source is Stream on Android XF4.1.0.555618

### ISSUE THREAD

**Issue by veletron2** [xamarin/Xamarin.Forms#6769]
### Description

Images in Listview loaded from Stream rather than via URL don't load reliably on Android XF4.0.x and 4.1.x was fine on 3.6.x. The Listbox is in an rg.plugins.popup page, but I do not believe this is related.

On iOS, 4.1.x,4.0.x and 3.6.x load images just fine.

**_Update: Just looked at my own screen shots, its not just the images that have failed to load, some of the text has also failed to load, this simply comes from a database. For instance, 'Watching' should be 'Watching Television', 'Cutting' should be 'Cutting Grass'. The full text appears properly as soon as I drop back to XF 3.6.0.539721_**

### Steps to Reproduce

1. Create a list control that includes a different image on each row
2. Load the images from a Stream rather than from a URL
3. Fast scroll up/down note that the images for some rows randomly fail to load (different rows each time)
4) Happens on Listview, CollectionView and MultiSelectListView

N-Off of these in a list backs the list control:

```
[Table("PatientActivities")]
    public class DbTableDefPatientActivity
    {
        /// <summary>
        /// The ActivityId - this value comes from Sentinel, and is used in the patient event response
        /// Is is a straight ID, not a MASK as only one PatientActivity may be selected
        /// </summary>
        [PrimaryKey, AutoIncrement]
        //todo - Remove the Datebase tag above - in production this info will come from Sentinel - it would also be changed to UInt32
        public UInt16 ActivityId { get; set; }

        public String Title { get; set; }

        public String Description { get; set; }

        /// <summary>
        /// The ID of the icon to use with this activity
        /// </summary>
        public ActivityIcons_e eActivityIcon { get; set; }

        /// <summary>
        /// Gets the ImageSource for the specified ActivityIconId
        /// </summary>
        public ImageSource ActivityImage => ImageSource.FromStream(() => PatientActivityIcons.GetImageStream(eActivityIcon));
    }
```

Images loaded thus:

```
static readonly string _rootResource = "Proteus.Shared.ProteusComms.LibProteusEnumsAndTypes.MobileApps.PatientApp.SymptomActivityIcons.ActivityIcons."; 
public static Stream GetImageStream(ActivityIcons_e activity)
        {
            var assembly = Assembly.GetExecutingAssembly();
            switch (activity)
            {
                case ActivityIcons_e.IconCooking:
                   return assembly.GetManifestResourceStream($"{_rootResource}Cooking.png");
//.......
}
}
```

### Expected Behavior

All images should load for every row, even is this delays the scrolling

### Actual Behavior

Some images fail to load, this is random and might be linked to load times. Images hosted in a separate .net2.0 Std Class Lib shared between Android,iOS and non-UWP windows. This is the reason for using Streams rather than Xamarin.Forms.ImageSource directly.

### Basic Information

- Version with issue: 4.0.x and 4.1.x
- Last known good version: 3.6.0.539721
- IDE: VS2017
- Platform Target Frameworks: 
  - iOS:  Works
  - Android:  Fails
- Android Support Library Version: Xamarin.Android,Support.V4, Xamarin.Android.Support.V7
- Nuget Packages: Xamarin.Forms.MultiSelectListView, PropertyChanged.Fody
- Affected Devices: Samsung S7, Note 8, Nexus 5.

### Screenshots

![Screenshot_20190703-101400](https://user-images.githubusercontent.com/34792184/60583514-fc8e3c00-9d82-11e9-82d8-50421552c909.png)
![Screenshot_20190703-101344](https://user-images.githubusercontent.com/34792184/60583515-fd26d280-9d82-11e9-9304-91411ad078f1.png)

### Reproduction Link

http://scratch.veletron.com/XFBugRepro.zip

Should be clear enough, see the readme, fast scroll and witness icons missing on XF4.1 while icons all draw correctly on XF3.6

**Comment by kingces95** [comment]
Well, if there's some way you could create a reduced reproduction we'd appreciate that. Otherwise we'll triage the bugs with reproductions first and then loop back around to see if we can concoct one for this case..

**Comment by veletron2** [comment]
Hi

Simple repeater for this issue may be downloaded from here: http://scratch.veletron.com/XFBugRepro.zip

Nigel

**Comment by PureWeen** [comment]
@veletron2 I wasn't able to reproduce your issue

![2019-07-26_15-21-31](https://user-images.githubusercontent.com/5375137/61982217-40a6e200-afb9-11e9-87ed-e87330a7d6d4.gif)


Can you give me more specifics on your device? 

Also can you try the latest 4.2 pre release? There are a few fixes in there around layouts

**Comment by veletron2** [comment]
Hi. On the contrary  your video shows the issue I have reported occuring very clearly!

No icons should be missing, on your video, an icon is commonly missing. 

My test devices are unfortunately mostly Samsung. S7, s8, note 8, A7 and a OnePlus3T

Nigel

**Comment by veletron2** [comment]
On holiday currently. Can try pre release on my return.

**Comment by PureWeen** [comment]
@veletron2 the icons are missing because the view cells are being recycled so when I fast scroll what you're seeing is that the view cell is being recycled to a different BindingContext and not loading by the time it scrolls past.

On native iOS if you use a view holder pattern with images you'll see the same effect as the same NativeCells are reused as the list scrolls by. 

But when I stop scrolling and the view cells settle the images always load. I'm never left with a ViewCell that doesn't have an image or cut off text

**Comment by veletron2** [comment]
Fair enough, but not the case on Samsung devices with 4.x - the viewcell does not draw no matter how long it is left for. Also, neither the scrolling issue not the undrawn icon issue exist with XF3.6. Looks like I will have to find another way to do it as staying on XF3.6 forever is not a way forward, and the failure to draw all icons while scrolling just makes for a very unprofessional looking app - also not acceptable.

**Comment by samhouts** [comment]
@veletron2 Please also try the latest service release for 4.0.0 and/or 4.1.0 released on Wednesday. Thanks!

**Comment by veletron2** [comment]
Hi

Just back to work after my holidays, updated XF to the new V4.1.0.673156 and the issue re the icons not loading from the Stream appears to be resolved.

Thanks!
