### ISSUE TITLE
[Bug] [iOS] Screen displacement when use a picker

### ISSUE THREAD

**Issue by JoseluDAM2000** [xamarin/Xamarin.Forms#6770]
### Description

The Absolute Layout displace to the top when i change the focus between components.

### Steps to Reproduce

1. Select the picker.
2. Select the Entry without exiting the picker selection.
3. Repeat.

### Expected Behavior
Just change the focus.

### Actual Behavior
The Absolute Layout displace.

### Basic Information

- Version with issue: 3.5, 4.0
- Last known good version: ?
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  16.1.0.545
- Affected Devices: iPhone Xs, iPhone 5s.

### Screenshots

![imagen](https://user-images.githubusercontent.com/22506382/60584991-f0a87700-9d8e-11e9-94e8-f834af0018f8.png)

**Comment by samhouts** [comment]
@JoseluDAM2000  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by JoseluDAM2000** [comment]
Hello @samhouts !
Next week i upload a small project.
A greeting!

**Comment by JoseluDAM2000** [comment]
Forgive it... 
The bug was caused by an [old plugin](https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/KeyboardOverlap) that a coworker included into the project.
I'm really sorry I made you waste your time.

My best regards!
