### ISSUE TITLE
[Bug] Issue2354 failing occasionally and the Presidents aren't loading

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6773]
### Description

Issue2354 - Needs to add a WaitForElement call at the top so that it knows when the test has loaded and it needs to wait for one of the images to have actually loaded

iOS - Images are only loading when you click on the cell
Android - Images aren't loading at all

### Steps to Reproduce
1. Run Issue2354

### Expected Behavior
All the presidents should load

### Actual Behavior
iOS - they only load when you click on the cell
Android - they don't load

### Basic Information

- Version with issue: 4.0
- Last known good version: Not sure. I know this test used to work. I tested 3.5 and it's still not working there either

- Platform Target Frameworks: 
  - iOS:  
  - Android:

**Comment by rmarinho** [comment]
Fixed by #7755 7755
