### ISSUE TITLE
[Bug] Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)

### ISSUE THREAD

**Issue by ghuntley** [xamarin/Xamarin.Forms#6777]
### Description

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	O:\Xamarin.Forms.v4x\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win-x64. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	O:\Xamarin.Forms.v4x\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7). Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	O:\Xamarin.Forms.v4x\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win-x86. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	O:\Xamarin.Forms.v4x\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	
```

### Steps to Reproduce

1. git clone https://github.com/xamarin/Xamarin.Forms
2. open `Xamarin.Forms.sln` (not the dotversion) in vs2019 (latest stable) or vs2017 (latest stable)
3. 💥 

### Expected Behavior

- Builds from CLI successfully. `msbuild /restore Xamarin.Forms.sln`
- Builds in VSWIN successfully.

### Actual Behavior

- Builds from CLI successfully. `msbuild /restore Xamarin.Forms.sln`
- Does not build in VSWIN successfully.

### Basic Information

<details>
<summary>Details</summary>

Microsoft Visual Studio Enterprise 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA222
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.1.19129.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

FormatDocumentOnSave   1.0
Enables auto formatting of the code when you save a file. Visual Studio supports auto formatting of the code with the CTRL+E,D or CTRL+E,F key shortcuts but with this extension the command 'Format Document' is executed on Save.

You can find the source here: https://github.com/Elders/VSE-FormatDocumentOnSave

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.5
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   16.0.28818.01
Microsoft Office Developer Tools for Visual Studio

OzCodePackage Extension   1.0
OzCodePackage Visual Studio Extension Detailed Info

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.1.19129.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.1.19129.1
Conda support for Python projects.

Python - Django support   16.1.19129.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.1.19129.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.1.19129.1
Profiling support for Python projects.

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   15.0.28917.181
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.28917
Visual C++ for Linux Development

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

Visual Studio Tools for Unity   4.1.1.0
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

### Screenshots

![image](https://user-images.githubusercontent.com/127353/60642820-79e5a980-9e74-11e9-948a-16bec0bfca52.png)

### Reproduction Link

Found a similar issue which was closed without resolution.

https://github.com/xamarin/Xamarin.Forms/issues/5738

**Comment by jfversluis** [comment]
Copying @PureWeen's comment from Gitter to here:

> I don't think those errors are related to it not building. Those are known error messages that are annoying but the don't break the build. What does the build output say the error is?

I've just tried to reproduce and I do see the same behavior, which shouldn't happen, but it doesn't prevent me from running or building?

**Comment by ghuntley** [comment]
- If `Xamarin.Forms.Core.iOS.UITests` is loaded in the solution then the iOS gallery application will not compile inside VSWIN. Unloading `Xamarin.Forms.Core.iOS.UITests` enables the gallery to compile, deploy and execute.
- Compiling the solution via msbuild devenv works always.

note: moments ago (as in after this github issue was raised) I formatted my computer and am in the progress of rebuilding it up. Anything I report from this point on wards reflects a clean/fresh slate/"brand new computer".

**Comment by ghuntley** [comment]
@PureWeen / @jfversluis 

- Fresh install of Windows 10, VS2017 stable and VS2019 stable.
- Brand new clone of master.

![image](https://user-images.githubusercontent.com/127353/60668812-2d1fc400-9eb0-11e9-9c14-cc95d17ddb5e.png)

<details>
<summary>Details</summary>

Microsoft Visual Studio Enterprise 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA184
Microsoft Visual C++ 2019

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.1.429.50124
Azure Functions and Web Jobs Tools

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.10424.1 Commit Hash:c3ce0ae0b29c0b3a755ffc12f8a685fe7ddd3600
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

</details>

**Comment by jfversluis** [comment]
To be absolutely clear we see the same thing: https://1drv.ms/v/s!Anrk6U9nRknzgvkvdxmdqW2TL8fSlw

You might want to skip the waiting times for a bit... 😉  You can see I have the errors as well, `Xamarin.Forms.Core.iOS.UITests` is loaded and it still builds and runs. Don't get me wrong, the errors shouldn't be there, be it doesn't seem to prevent me from doing anything.

**Comment by PureWeen** [comment]
can you post the build output?

**Comment by redradist** [comment]
I also have the same issue:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	G:\Projects\Programing\Xamarin\Xamarin.Forms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1

**Comment by PureWeen** [comment]
The error is just annoying and not fatal

Please go vote for it over here though!!

https://developercommunity.visualstudio.com/content/problem/398463/default-xamarin-ui-test-template-causes-nu1201-err.html

**Comment by jfversluis** [comment]
Since there is no response I’m going to assume you’ve found a way. If not, please reopen.

**Comment by davidbuckleyni** [comment]
`LOL @jfversluis  ur going hate me I just found this issue today @samhouts was there ever a resolution for it. I have attached the logs for u guys ill try and unload the tests

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Xamarin.Forms.ControlGallery.iOS is not compatible with net47 (.NETFramework,Version=v4.7) / win-x86. Project Xamarin.Forms.ControlGallery.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	Xamarin.Forms.Core.iOS.UITests	C:\GitHub\XamrainForms\Xamarin.Forms.Core.iOS.UITests\Xamarin.Forms.Core.iOS.UITests.csproj	1	
[BuildLogs.zip](https://github.com/xamarin/Xamarin.Forms/files/4601474/BuildLogs.zip)
`
