### ISSUE TITLE
[Enhancement] WPF "Preview" state?

### ISSUE THREAD

**Issue by sude22** [xamarin/Xamarin.Forms#6778]
## Summary
I would like to know when Xamarin.Forms.WPF will leave the "Preview" state?

**Comment by jfversluis** [comment]
Hi @sude22 thanks for your question!

Unfortunately, I do not have any concrete information about this to share at this time. If this changes we will advertise this through our official channels. In the meantime, you are of course more than welcome to contribute yourself :)

**Comment by sude22** [comment]
Hi @jfversluis ,
thanks for that info. We are just discussing in our team if it could be an option to switch our project from UWP to WPF. But if WPF is not to be declared "stable" in the near future, we don't have to think about it further. Besides that, the component suite we are using doesn't seem to support WPF either.... Bad luck :(

**Comment by jfversluis** [comment]
Sorry about that! Good luck with your project!
