### ISSUE TITLE
Data Annotation validation from .net Standard Class Library

### ISSUE THREAD

**Issue by PKYADAV** [xamarin/Xamarin.Forms#6782]
Hi Team,

Can we use .net Standard Class Library Custom DataAnnotation in Xamarin.Forms for validation?

**.net Standard Class Library**

[DbRequired]
[Display(Name = "USER NAME", Prompt = "ENTER USER NAME")]
public string User_Name
{
get { return GetValue(() => User_Name); }
set { SetValue(() => User_Name, value); }
}

    [Display(Name = "PASSWORD", Prompt = "ENTER PASSWORD")]
    [DataType(DataType.Password)]
    [DbRequired]
    public string User_Password
    {
        get { return GetValue(() => User_Password); }
        set { SetValue(() => User_Password, value); }
    }

Please help us to use and validate from class library.

**Comment by jfversluis** [comment]
Hey @PKYADAV thank you for your question!

From a first glance, I don't see why it shouldn't be possible to use it like that. We would love to help you but, with the issues we are more focussing on the actual bugs and features of Xamarin itself. I think you would have more luck getting an answer on the [Xamarin forums](http://forums.xamarin.com) or [StackOverflow](https://stackoverflow.com/questions/tagged/xamarin.forms).

**Comment by PKYADAV** [comment]
Hi @jfversluis Thanks for your suggestion and quick response.
