### ISSUE TITLE
[Bug] [Shell] [iOS] ShellItem.CurrentItem not set when selecting shell section aggregated in more tab

### ISSUE THREAD

**Issue by Dresel** [xamarin/Xamarin.Forms#6784]
### Description

There is this known [issue](https://stackoverflow.com/questions/5803352/didselectviewcontroller-not-getting-called-when-in-more-section) with UITabBarController where didSelectViewController does not trigger for items aggregated in more tab.

`ShellItemRenderer` is relying on [this](https://github.com/xamarin/Xamarin.Forms/blob/78385f9fc1fc56dc88bd98e73bf9c8f2f2d0a90a/Xamarin.Forms.Platform.iOS/Renderers/ShellItemRenderer.cs#L67) to set the `CurrentItem` of the `ShellItem`. For the above reason `ShellItem.CurrentItem` is not set when selecting shell section aggregated in more tab.

#### With debugger

1. Set breakpoint in `ShellItemRenderer.SelectedViewController`
2. Open StoreShell from ControlsGallery
3. Click on Books (aggregated in more tab)
4. Verify breakpoint not getting hit

#### Visually

1. Open StoreShell from ControlsGallery
2. Click on Books (aggregated in more tab)
3. Verify that BooksShell style is not applied (Shell.Background should change to #039BE6) because `CurrentItem` will not get set

### Expected Behavior

`ShellItem.CurrentItem` should be set when selecting shell section aggregated in more tab

### Actual Behavior

`ShellItem.CurrentItem` is not set when selecting shell section aggregated in more tab

### Basic Information

- Platform Target Frameworks:
  - iOS

**Comment by samhouts** [comment]
closed by #6786
