### ISSUE TITLE
[Enhancement] Adjust TabBar images for ShellSection without title

### ISSUE THREAD

**Issue by Depechie** [xamarin/Xamarin.Forms#6788]
## Summary
Allow tab items without a title when configuring Shell. So defining a ShellSection with Title = "".
This works, but will not adjust the images vertically in the tab.

**Note**
Not sure if what the best course of action will be, because the title will also be used for the flyout menu I guess... so setting it to empty is maybe not ideal. Add extra property HideTabTitle?

## API Changes

No real API changes, only take into consideration Title property of ShellSection can be null/empty.
If so adjust the images in the tab so that they are placed in the center vertically.

I 'think' the changes are needed here:
https://github.com/xamarin/Xamarin.Forms/blob/da8d36df9a9406f21b72b10d10802d24de520b49/Xamarin.Forms.Platform.iOS/Renderers/ShellSectionRenderer.cs#L316
https://github.com/xamarin/Xamarin.Forms/blob/da8d36df9a9406f21b72b10d10802d24de520b49/Xamarin.Forms.Platform.Android/Renderers/ShellItemRenderer.cs#L170

## Intended Use Case
Have app UI with only icons for tabs

**Comment by jfversluis** [comment]
Looks like a duplicate of #6220?

**Comment by Depechie** [comment]
@jfversluis my bad! I searched for ShellSection and did not find #6220 ... sorry for the duplicate.
