### ISSUE TITLE
[Bug] [WPF] Button padding doesn't work

### ISSUE THREAD

**Issue by ZeProgFactory** [xamarin/Xamarin.Forms#6790]
# Description
When adding `Padding` to a Button we expect space around the caption of the button.  In WPF  it doesn't work.

### Steps to Reproduce
```
        <Button Text="Welcome to Xamarin.Forms!" 
           HorizontalOptions="Center" CornerRadius="10"
           VerticalOptions="CenterAndExpand" Padding="40,0,40,0" />
```

### Expected Behavior
Space around the caption of the button.

### Actual Behavior
`Padding` has no effect.

### Basic Information
Xamarin.Forms 4.1.0.555618

**Comment by jfversluis** [comment]
I think for UWP this was never implemented.
