### ISSUE TITLE
[Bug] AppShell TabBar TabIndex property not changing

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/Xamarin.Forms#6792]
### Description
The TabIndex property on AppShell TabBar is not changing.
1) Inherited TabBar OnTabIndexPropertyChanged doesn't fire when selecting a new tab
2) Binding TabIndex to a viewmodel property doesn't change the bound value

### Steps to Reproduce

1.  clone repo https://github.com/InquisitorJax/Xamarin-Forms-Shell
2. Run app and change tabs

### Expected Behavior
- expecting breakpoints / code to run on the AppShellViewModel.CurrentTabIndex, as well as AppTabBar.OnTabIndexPropertyChanged method

### Actual Behavior
neither code hooks are fired.

### Basic Information

Latest Xamarin & VS & XF nuget
- Version with issue:
- Last known good version:
- IDE: VS 2019

**Comment by jsuarezruiz** [comment]
TabIndex is a property available in VisualElement and ShellItem used to indicate the order in which Element instances receive focus when the user navigates through controls by pressing the Tab key. The default value of the property is 0, and it can be set to any int value.
Also, very useful with ScreenReaders, etc. More info: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/keyboard

I think you're interested in using the CurrentItem property: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.shellitem.currentitem?view=xamarin-forms

If you are interested in working with indexes, you could do it:
`int index = Items.IndexOf(CurrentItem);
`

**Comment by InquisitorJax** [comment]
lol - talk about naming confusion. Thanks Javier!

**Comment by jsuarezruiz** [comment]
Do not worry!. Pleased to be able to help. ;)
