### ISSUE TITLE
[Bug] Device.Info.ScaledScreenSize Gives 0 Width and Height in iOS

### ISSUE THREAD

**Issue by muhaym** [xamarin/Xamarin.Forms#6799]
### Description
The internal Xamarin.Forms function `Device.Info.ScaledScreenSize` Gives 0 Width and Height in iOS with Xamarin.Forms 4.x releases.

### Steps to Reproduce

1. Create a Blank Xamarin Forms Project
2. after InitializeComponent, call var x=Device.Info.ScaledScreenSize;

### Expected Behavior
x.Width and x.Height should be actual size from the screen

### Actual Behavior
x.Width and x.Height is 0

### Basic Information

- Version with issue: XF 4.1.0.555618, 4.0+ Version
- Last known good version: 3.6.0.539721

**Comment by muhaym** [comment]
Problems faced with https://github.com/Binwell/FastGrid/issues/7

**Comment by samhouts** [comment]
closed by #6912

**Comment by Lakshminatarajan** [comment]
Hi @samhouts ,
I have the same issue on the macOS platform with XF 4.X. https://github.com/xamarin/Xamarin.Forms/issues/8559
