### ISSUE TITLE
[Bug] Shell Flyout - Weird line at the bottom of the items

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#6801]
### Description

There is a strange line at the end of the FlyoutItems / MenuItems. I'm not sure if this is a bug or if it can be disabled somehow? It just looks wrong there (the line at the end of the master menu, not the iOS gesture bar in the center). Also it seems like the items are cut off there instead of scrolling endless (to avoid overlapping with the iOS bar?). 

![Simulator Screen Shot - iPhone Xʀ - 2019-07-06 at 18 59 04](https://user-images.githubusercontent.com/25636075/60759203-47c57a80-a021-11e9-8f87-29cbdaeb6d6a.png)

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Change the tabbed page to flyout 
3. Add the items multiple times

### Expected Behavior

It should be at least be configureable if we want the items to go all the way down. Or maybe place a custom footer there? It should respect the SafeArea tho so it needs some kind of scrolling offset. 

### Actual Behavior

Looks strange.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: -
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/6572

**Comment by samhouts** [comment]
closed by #6572

**Comment by HobDev** [comment]
@samhouts  @PureWeen  This issue is still present in latest xamarin.forms 4.3.0.991211. I unwanted line is present below the flyoutitems in iOS.

**Comment by samhouts** [comment]
@HobDev Can you please open a new issue? Thanks!

**Comment by HobDev** [comment]
@samhouts  opened new issue #8881
