### ISSUE TITLE
[Bug] Shell SearchHandler - Cancel is visible by default?

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#6802]
### Description

The cancel button from the search bar is visible by default (without focus to the search control). This is not the native behaviour. 

![Simulator Screen Shot - iPhone Xʀ - 2019-07-06 at 18 58 58](https://user-images.githubusercontent.com/25636075/60759219-ae4a9880-a021-11e9-927d-b4ac4ddf6064.png)

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Add a seaerch handler

### Expected Behavior

The cancel button should only be visible when the search bar has content or the focus.

### Actual Behavior

Cancel button is visible when the app starts.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: -
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

**Comment by Bronson15** [comment]
Have this in our application too. Hopefully will be fixed soon as it makes the UI look not so great.

**Comment by hartez** [comment]
[_6802 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3388131/_6802.Repro.zip)
