### ISSUE TITLE
[Bug] ListView does ignore left/right SafeArea even if it is the root control (Shell problem?)

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#6803]
### Description

ListView, even when set to the root element of a page, ignores the SafeArea for left and right.

Also the ListView is now cut off at the bottom??

![Bildschirmfoto 2019-07-06 um 19 22 12](https://user-images.githubusercontent.com/25636075/60759308-62005800-a023-11e9-925c-954ce407cfc9.png)

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Move the ListView from the StackLayout to the ContentPage.Content directly (only in this case it has worked before)

### Expected Behavior

The ListView, at least when it is the root control of a page, should respect the SafeArea margins like it has done in 3.6. 

### Actual Behavior

Looks broken.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: 3.6.0
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

**Comment by PureWeen** [comment]
This should be fixed with 4.2.0

https://github.com/xamarin/Xamarin.Forms/pull/6457

I'm going to close this for now. If the issue still appears with 4.2.0 please let me know and we can reopen
