### ISSUE TITLE
[Bug] Shell SearchHandler - Search text getting lost on execute search

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#6804]
### Description

When using the Xamarin.Forms Shell template and upgrade to Xamarin.Forms 4.1 (I did not test with 4.0 yet), the SearchHandler is removing the search term on enter/search execution. 

![SearchHandlerBug](https://user-images.githubusercontent.com/25636075/60759349-14381f80-a024-11e9-8525-44f9fe86ab5f.gif)

### Steps to Reproduce

1. Create a fresh Xamarin.Forms Shell project
2. Add a search handler

### Expected Behavior

It should keep the searched term.

### Actual Behavior

It losts the content.

### Basic Information

- Version with issue: 4.1.0
- Last known good version: -
- IDE: VS2019 and VS for Mac
- Platform Target Frameworks: 
  - iOS:  Tested with iOS 12 Simulator

### Screenshots

Already added above in the description.

### Reproduction Link

Reproduction can be done with the VS template within a minute.

**Comment by Bronson15** [comment]
Issue is here on 4.0 as well.

**Comment by hartez** [comment]
Repro (took 5 minutes):
[_6804 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3388291/_6804.Repro.zip)

Happens on iOS and Android.

**Comment by ReDERO** [comment]
This is really annoying. Please, fix this problem.

**Comment by pfedotovsky** [comment]
Any workarounds till the issue is fixed?

**Comment by GeorgeVelikov** [comment]
This doesn't seem to be fixed for iOS because as soon as I lose focus (manually call _searchController.Active = false) the text is removed again.

Furthermore, xamarin forms 4.5 disables the ui for ios when the search controller is active, not allowing me to scroll any of the results or interact with them.

**Comment by dmariogatto** [comment]
@GeorgeVelikov 
Setting the `Active` property on a `UISearchController` to false will clear its search text. This is the native behaviour on iOS and what was removed in #8101.

I am able to scroll a list while the search controller is active in 4.5. Would you be able to provide a sample solution and possibly create a separate issue?
