### ISSUE TITLE
[Bug] GTK Navigation is broken

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#6805]
Steps to reproduce.
On master page and detail page add a button to the navigation bar
navigate from master page to detail page. Navigation bar is displayed (as expected)
Click on the back button and navigate again to the detail page
AR: Navigation bar is not displayed
ER: Navigation bar is displayed

Screen shots #4409 
XF: latest preview

**Comment by jsuarezruiz** [comment]
@VladislavAntonyuk Could you attach a small repro sample?.

**Comment by VladislavAntonyuk** [comment]
Looks like the issue is fixed.
