### ISSUE TITLE
GetTemplateChild  for DataTemplate

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6806]
Hi,

Please provide an easier and clean way to access child items inside the DataTemplate using the **GetTemplateChild** ..

For example:

```
<DataTemplate x:Key="HomePageSortTemplate">
    <ContentView BackgroundColor="White" x:Name="HomePageContentView">
        <StackLayout>
            <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Padding="15">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>

		<Label x:Name="myLabel" Grid.Row="0" Text="This is my Label" />
            </Grid>
        </StackLayout>
    </ContentView>
</DataTemplate>

```
and then if I want to read the or set the value of the Label:

```
Label _myLabel;
_myLabel = GetTemplateChild("myLabel");

// Set the Value;
_myLabel.Text = "This is the New Text";

// Read the Value;
DisplayAlert("Value", _myLabel.Text, "OK");

```

Thanks,
[Jassim](https://www.softnames.com)

**Comment by samhouts** [comment]
@jrahma Are you referring to #6747?

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
