### ISSUE TITLE
Videoplayer bug in Xamarin.forms

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#6808]
I am working on xamarin.forms and VideoPlayer (coming from native) is work fine when you use in ListView > ViewCell

When I implemented it using contentView and try to check on both platform it's work only on IOS not on android.

Is someone have got solution for this bug, I check the forum and find that similar thing has been reported earlier https://forums.xamarin.com/discussion/148872/xamarin-forms-android-videoview-bug

If I implemented it using Listview > Viewcell work in both IOS and Android but when it's in ScrollView > Grid it's failed to work on Android, work fine in IOS.

**Comment by samhouts** [comment]
@anirugu  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by anirugu** [comment]
@samhouts  Thanks Samantha for reply.   I will give you a demo asap.

**Comment by samhouts** [comment]
Thanks! We'll look for it.

**Comment by anirugu** [comment]
@samhouts I can't share the code since it's copyright property of my organisation. any idea to fix this issue ?

**Comment by samhouts** [comment]
I'm afraid that we don't have enough information to provide guidance at this time.

**Comment by anirugu** [comment]
I have send you some demo code at your xamarin email address. See if you got it.

**Comment by samhouts** [comment]
@anirugu I don't see anything. Please try sahou at microsoft dot com. Thanks!

**Comment by anirugu** [comment]
@samhouts  just send you the mail. Please check.

**Comment by samhouts** [comment]
Got it! Thanks!

**Comment by samhouts** [comment]
@anirugu Your report says that this doesn't work in Android in certain layouts, but the sample code you sent is for UWP.

**Comment by anirugu** [comment]
That code is for Android and IOS. We are not doing work for UWP. It's work fine on IOS but failed to run on Android. I have sent you another mail, please check.

**Comment by PureWeen** [comment]
@samhouts ping

Forward me the project and I can take a look :-)

**Comment by samhouts** [comment]
@PureWeen Were you able to get anything from the repro I forwarded? Thanks!

**Comment by anirugu** [comment]
@PureWeen Shane,  I got your mail last week. I don't have the right to give access to people. You need to try it internally if it can possible.

**Comment by PureWeen** [comment]
@anirugu can you email me a link to the code so I can see if I can access the repository?

**Comment by anirugu** [comment]
just drop a mail with detail

**Comment by PureWeen** [comment]
I'm going to close this issue for the time being.

Once I have access and see the issue I'll reopen with more specifics
