### ISSUE TITLE
[Enhancement] Picker Right side Icon and item template!

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#6809]
Can you please add feature to change the right side icon of a picker.
And also to add an item template for drop down view icons ( Syncfusion already has this feature. but it is a paid control).

![Screenshot_1562480625](https://user-images.githubusercontent.com/14989528/60764895-5fe3db00-a0af-11e9-991d-44443be36754.png)

I created this kind of UI using a grid. 

but its easy if you can provide us a great component.

**Comment by kgbuddhima** [comment]
https://github.com/kgbuddhima/SampleApps/blob/master/App1/App1/App1/PickerForDatesSample.xaml

Here is the code of the UI.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
