### ISSUE TITLE
Animation in Android Navigation[Bug] 

### ISSUE THREAD

**Issue by AhmedKhattab95** [xamarin/Xamarin.Forms#6811]
### Description
in new Xamarin Froms 4.0 release tried shell and the navigation in it from page to detail page work fine and very smooth in old navigation of Xamarin Froms  the navigation between content pages not work fine and not smooth even if I set it true to enable animation
### Steps to Reproduce

1. make  a content page and details page
2.  try to navigate with animation like one in shell

### Expected Behavior
do smooth animation more than this
### Actual Behavior
animation always off
### Basic Information

- Version with issue: 4.0
- Last known good version: 4.0
- IDE: Visual studio 2019 enterprise edition

**Comment by jfversluis** [comment]
Hey @AhmedKhattab95 thank you for your issue!

Just to be sure we mean the same thing: you have been using Shell and you like the animation between different pages. Using "regular" Forms without Shell you're not seeing these animations. But it's not that you did see the animations before, right? It's just that you would also like to have them in Forms when you're not using Shell?

**Comment by jsuarezruiz** [comment]
I think he refers to the navigation between ContentPages in Xamarin.Forms 4 is not smooth. Can be @AhmedKhattab95? On the other hand, could you attach a sample where we can see and reproduce the problem?.

**Comment by AhmedKhattab95** [comment]
@jfversluis  yes exactly

**Comment by daniel-refahi** [comment]
I have the same issue, 
My first page is a ContentPage and I'm using 

     `await Navigation.PushAsync(new ConfigurationView(),true); `

to navigate to the next page and my second page is also ContentPage

I used a black project so it's not using any of the default templates. The animation is fine on ios but on android it just jumps to the next page without animation

**Comment by PureWeen** [comment]
I wouldn't call this one a bug. The difference here is that Shell uses a ViewPager for doing navigation whereas non shell forms just swaps out the fragments.

So what you are seeing on shell is the swiping animation for shell vs the Fragment Transaction animation

There are a number of issues already open addressing the need to add more transitions
https://github.com/xamarin/Xamarin.Forms/search?q=transition&type=Issues

so I'm going to close this one for now
