### ISSUE TITLE
implement itemAppearing event in CollectionView

### ISSUE THREAD

**Issue by AhmedKhattab95** [xamarin/Xamarin.Forms#6812]
## Summary
want to implement item appearing event in collection view to enable work with pagination with collection view .

**Comment by adrianknight89** [comment]
#5754

**Comment by jfversluis** [comment]
With merging #5754 I’m going to close this for now. Should’ve happened automatically, but didn’t ¯\_(ツ)_/¯

**Comment by kasimier-vireq** [comment]
The event ItemAppearing was never implemented, was it?
