### ISSUE TITLE
[Bug] CollectionView MeasureFirstItem throws Java.Lang.NoClassDefFoundError on Android 4.4.2

### ISSUE THREAD

**Issue by aubiyko** [xamarin/Xamarin.Forms#6815]
### Description
CollectionView with ItemSizingStrategy="MeasureFirstItem" throws Java.Lang.NoClassDefFoundError: android/util/Size on Android 4.4.2.

I suspect that issue is [current implementation](https://github.com/xamarin/Xamarin.Forms/blob/24648e8059cd1e7d07b985688862d9221a58c25c/Xamarin.Forms.Platform.Android/CollectionView/ItemContentView.cs#L4) is using [Android.Util.Size](https://developer.android.com/reference/android/util/Size), which is available in API Level 21.

Attached [exception stack trace](https://github.com/xamarin/Xamarin.Forms/files/3367292/exception.txt) and [logcat](https://github.com/xamarin/Xamarin.Forms/files/3367293/logcat.txt).

### Steps to Reproduce
1. Lower demo minimum SDK version to target 19;
2. Update to Xamarin.Forms 4.1.0.555618.
2. Adapt demo to changes introduced by new version ("{x:Static ListItemsLayout.HorizontalList}" to "HorizontalList")
3. Run Variable size items;
4. Change ItemsSizingStrategy to MeasureFirstItem.

### Expected Behavior
No exception.

### Actual Behavior
[Crashes](https://github.com/xamarin/Xamarin.Forms/files/3367292/exception.txt).

### Basic Information
- Version with issue: 4.1.0.555618
- Last known good version: unknown
- IDE: MS VS Community 16.1.5
- Platform Target Frameworks:
  - Android: min 19, target 28
- Nuget Packages:
  - NETStandard.Library 2.0.3
  - Xamarin.Forms 4.1.0.555618
- Affected Devices: Samsung SM-C101

### Reproduction Link
https://developer.xamarin.com/samples/xamarin-forms/UserInterface/CollectionViewDemos/

**Comment by samhouts** [comment]
@aubiyko Thanks for the report! Do you have a target audience that uses <API21? 

/cc @pauldipietro

**Comment by aubiyko** [comment]
@samhouts Besides that testing device, we have an important client with API 19.
