### ISSUE TITLE
[Bug] Shell FlyoutItem Title Binding and MenuItem Text Binding values not updated

### ISSUE THREAD

**Issue by Basti82b** [xamarin/Xamarin.Forms#6818]
### Steps to Reproduce

1. Bind the Title Property of a FlyoutItem to a Property in a ViewModel that implements INotifyPropertyChanged.
2. Change the value of that property at runtime.

### Expected Behavior

The title of the FlyoutItem changes immediately.

### Actual Behavior

The inital binding value is shown.

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0.555618
- Platform Target Frameworks:
  - Android: 9.0

**Comment by PureWeen** [comment]
For performance reasons the bindings are all OneTime by default so you need to set it to OneWay and then it'll update

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Shell/BaseShellItem.cs#L36

**Comment by Basti82b** [comment]
@PureWeen
Even if I change the Binding Mode in XAML it doesn't update the Title.

`Title="{Binding Text, Mode=OneWay}"`

Do I need implement my own ShellItem?

**Comment by Basti82b** [comment]
@PureWeen Thank you! It works!

**Comment by spasas** [comment]
I think this bug was open with two distinct issues. It has been rightly closed for the FlyoutItem but the Mode still does not resolve the MenuItem and its Text dependency property.

As Chris pointed out, the issue is still unresolved for the MenuItem since it was OneWay in the first place.
