### ISSUE TITLE
[Bug] viewport unit doesn't work for HybridWebView

### ISSUE THREAD

**Issue by maxisam** [xamarin/Xamarin.Forms#6819]
### Sample

https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/HybridWebView

### Description

if I add a div at https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/HybridWebView/Droid/Assets/Content/index.html

like 

```html
<div class="test" style="height: 50vh; background-color: green;">this is a test</div>
```

The viewport unit doesn't work.

I also tried adding the following line in index.html

```html
<meta name="viewport" content="width =device-width,initial-scale=1, maximum-scale=1">
```

and it doesn't work either.

I think it is because there is no viewport for this webview. I wonder if there is a way to make it work.

Thanks!

### Information

- IDE and IDE version: vs2019
- Platform with the issue: 
  - Android: 8.0
- Device or simulator/emulator: simulator

**Comment by maxisam** [comment]
Here is the demo repo https://github.com/Sam-Lin-MillersLab/HybridWebViewExample

**Comment by StephaneDelcroix** [comment]
Thanks for the report

the HybridWebView is a sample on how to create a custom renderer, not a fully fledged control we support or distribute.

**Comment by maxisam** [comment]
Wait, so that's it? You guys don't wanna figure out what is wrong?

**Comment by dsum27** [comment]
I agree with @maxisam. There isn't a problem with HybridWebView it's a problem with rendering the custom webview. The view is as simple as can be. Does the `Android.Webkit.WebView` have limitations with CSS styling? Thanks for that example @maxisam. I have found you can fix this issue by adding 
`_WebView.LayoutParameters = new global::Android.Widget.RelativeLayout.LayoutParams(LayoutParams.MatchParent, LayoutParams.MatchParent);` inside the HybridWebView

**Comment by StephaneDelcroix** [comment]
If you can produce a repro using the normal WebView, please reopen the ticket
