### ISSUE TITLE
[Bug] Unable to send data between contentpages in Shell

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#6829]
### Description
I am using shell in a project where I need to send data between contentpages. But the navigation stops when I add data. The pages navigate between each other when there is no data.

### Steps to Reproduce

Run the repro project and try to send data between pages.
### Expected Behavior
One page should pass data to another.
### Actual Behavior
The pages does not navigate with data.
### Basic Information

- Version with issue: Xamarin.Forms-4.1.0
- IDE:VSMac 2019

- Affected Devices: Android and iOS

### Reproduction Link
[ShellData.zip](https://github.com/xamarin/Xamarin.Forms/files/3373191/ShellData.zip)

**Comment by StephaneDelcroix** [comment]
so, you're saying that the navigation doesn't work as soon you start using QueryAttributes ?

**Comment by StephaneDelcroix** [comment]
I can reproduce this. I wonder what's going on in this particular case...

**Comment by PawelHaracz** [comment]
Any progress?

**Comment by PureWeen** [comment]
@HobDev a couple things with the sample

1) none of the gotoasync's are awaited so navigation is never actually triggering
2) If you change the global routes to 
```

            Routing.RegisterRoute("secondpage", typeof(SecondPage));
            Routing.RegisterRoute("data", typeof(FirstPage));
```

Then navigate like this
```

            await Shell.Current.GoToAsync($"secondpage?wish=Hi");
```

it works fine

@PawelHaracz if you're having issues can you log an issue with a repro please?
