### ISSUE TITLE
[Android] ListView item UI contents are corrupted

### ISSUE THREAD

**Issue by sk1llsh0t** [xamarin/Xamarin.Forms#6830]
###Description
In 4.1(and 4.0), ListView label contents on Android are getting cropped and don't display correct information. I have tried using RecycleElements as the caching strategy and it doesn't help. This problem existed in initial versions of 3.6. I reported the issue at the time and a fix was put into  3.6.0.344457. I was actually trying to go back to see if i could find my original bug but I could not. I'll continue to look.

When 4.0 was released, the fix was not merged into this release so i have been stuck on 3.6.0.344457.

### Steps to Reproduce

1. Populate a listview items with multiple columns,  labels and images
2. scroll down a little ways and the corruption issue appears

### Expected Behavior
Labels should display correctly with correct information

### Actual Behavior
Labels don't display correct information and are cropped so they don't show the entire contents

- Version with issue: 4.1.0.555618
- Last known good version: 3.6.0.344457
- IDE: VS2017
- Platform Target Frameworks: 
  - Android: 9.0 
- Nuget Packages:
- Affected Devices: All

### Screenshots
The starting numbers shouldn't be all 1's and the rest of the first label is chopped off.

![Capture](https://user-images.githubusercontent.com/8394807/60897951-d2cb8e00-a236-11e9-96f0-4f732deb7677.PNG)

**Comment by samhouts** [comment]
This is almost certainly the same as the bugs fixed by #6390. So we can be sure,  can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Legenda374** [comment]
I got the same problem, here is my question on [stackoverflow](https://stackoverflow.com/questions/56969200/onpropertychanged-sometimes-does-not-update-ui-in-listview-only-after-scroll-or), I recorded a [video ](https://youtu.be/u-a1cWKywKI) you can watch it
And I also do not have this problem on 3.6.0.344457, but 4.1.0.555618 gives me problem

**Comment by Legenda374** [comment]
> This is almost certainly the same as the bugs fixed by #6390. So we can be sure, can you please attach a small project that demonstrates this issue? Thanks!

I got the same problem, here is my question on stackoverflow, I recorded a video you can watch it
And I also do not have this problem on 3.6.0.344457, but 4.1.0.555618 gives me problem

**Comment by LeoJHarris** [comment]
This is a much needed fix. We are also stuck on Xamarin 3.6. and wont update XF until this issue is resolved.

**Comment by Legenda374** [comment]
I added a project, you need to press the button several times and to scroll listview. It repeats.
https://github.com/Legenda374/XamarinBug.git

**Comment by samhouts** [comment]
closed by #6390
