### ISSUE TITLE
[Bug] Stacklayout, Flexlayout does not fit in Grid

### ISSUE THREAD

**Issue by redradist** [xamarin/Xamarin.Forms#6833]
### Description
**_StackLayout_**, **_Flexlayout_** does not fit into Grid ...
But what is more interesting that **_WrapLayout_** from https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/custom works perfectly

More detail you can find on **_Xamarin.Forms_** Forum https://forums.xamarin.com/discussion/161113/item-of-grid-does-not-fit-in-cell

### Steps to Reproduce
Implement something **_Grid_** something like this:
```xaml
<Grid
    VerticalOptions="FillAndExpand"
    x:Name="Grid"
    RowSpacing="15"
    ColumnSpacing="15">
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="50" />
        <ColumnDefinition Width="50" />
        <ColumnDefinition Width="50" />
    </Grid.ColumnDefinitions>

    <Grid.RowDefinitions>
        <RowDefinition Height="100" />
        <RowDefinition Height="100" />
        <RowDefinition Height="100" />
    </Grid.RowDefinitions>

    <StackLayout
        VerticalOptions="FillAndExpand"
        HorizontalOptions="FillAndExpand"
        Grid.Row="0"
        Grid.Column="0">
        <Image
            WidthRequest="50"
            HeightRequest="50"
            Source="{utilsme:ImageResource MyApp.Forms.Resources.Images.my_image.png}"/>
        <Label
            Text="Home 0"
            HeightRequest="10"
            VerticalOptions="CenterAndExpand" 
            HorizontalOptions="CenterAndExpand" />
    </StackLayout>
    <!-- Other items -->
</Grid>
```

### Expected Behavior
**_StackLayout_**, **_Flexlayout_** or other complex Layout should fit into **_Grid Cell_**

### Actual Behavior
**_StackLayout_**, **_Flexlayout_** do not fit into **_Grid Cell_**

### Basic Information
Xamarin.Forms 4.1.0.581479

### Screenshots
[Grid Issue](https://us.v-cdn.net/5019960/uploads/editor/z2/lg15c6ccwetv.jpg)

### Minimal Test Example
[MinimalTestExample.zip](https://github.com/xamarin/Xamarin.Forms/files/3379229/MinimalTestExample.zip)

**Comment by samhouts** [comment]
@redradist  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by redradist** [comment]
> 
> 
> @redradist Can you please attach a small project that demonstrates this issue? Thanks!

I have added demonstration project

**Comment by jsuarezruiz** [comment]
Thanks for the sample!. I did some tests with it. The results are:
<img width="1369" alt="Captura de pantalla 2019-07-17 a las 12 58 38" src="https://user-images.githubusercontent.com/6755973/61370452-b95bbf00-a892-11e9-8885-55aa6577c9da.png">

I have used StackLayout and FlexLayout in each cell and it seems that fits well (50x100 and 15 as spacing). In the case of the StackLayout, is stacking the elements as expected. I'm probably missing something, could you give us more details?.

If you want a similar result to the WrapPanel I think maybe the FlexLayout fits you well. Here you can find a sample creating a Image Gallery wrapping images using the FlexLayout: https://github.com/jsuarezruiz/BindableLayoutPlayground

**Comment by redradist** [comment]
> 
> 
> Thanks for the sample!. I did some tests with it. The results are:
> <img alt="Captura de pantalla 2019-07-17 a las 12 58 38" width="1369" src="https://user-images.githubusercontent.com/6755973/61370452-b95bbf00-a892-11e9-8885-55aa6577c9da.png">
> 
> I have used StackLayout and FlexLayout in each cell and it seems that fits well (50x100 and 15 as spacing). In the case of the StackLayout, is stacking the elements as expected. I'm probably missing something, could you give us more details?.
> 
> If you want a similar result to the WrapPanel I think maybe the FlexLayout fits you well. Here you can find a sample creating a Image Gallery wrapping images using the FlexLayout: https://github.com/jsuarezruiz/BindableLayoutPlayground

I have found the issue !!
The issue was in custom **_HeightRequest_**:

```xaml
    HeightRequest="10"
```

When I removed **_HeightRequest_** it will be adjusted automatically:

![Fixed Issue](https://user-images.githubusercontent.com/6311799/61409038-1171e000-a8ea-11e9-9c7c-f6c31bc7dbf4.png)


Sorry for that ... (
Seems like the issue does not exists an it can be closed

**Comment by jsuarezruiz** [comment]
Ahh, I see!. No problem, happy to help. Thanks for the feedback.
I am going to close the Issue.
