### ISSUE TITLE
[Bug] OnPropertyChanged sometimes does not update UI in ListView, only after scroll or another activity

### ISSUE THREAD

**Issue by Legenda374** [xamarin/Xamarin.Forms#6841]
### Description

i have a problem, when i work with list items, listview does not redraw them if they area of visibility, reflected only after I've scrolled the element out of view and back, or I've tap on item, it appeared after the updated to Xamarin v4, when i used Xamarin v3 everything was good

### Ask on Stackoverflow

https://stackoverflow.com/questions/56969200

### Another problem

https://github.com/xamarin/Xamarin.Forms/issues/6830

### Steps to Reproduce

1. Populate a listview items with multiple columns, labels and images
2. Change View cells
3. Scroll down a little ways and the corruption issue appears

### Expected Behavior
Labels should display correctly with correct information

### Actual Behavior

Labels don't display correct information and are cropped so they don't show the entire contents

### Basic Information

- Version with issue: 4.1.0.555618
- Last known good version: 3.6.0.539721
- IDE: VS2017
- Platform Target Frameworks:
  - Android: 9.0

### Screenshots

Video: https://youtu.be/u-a1cWKywKI

### Reproduction Link

https://youtu.be/u-a1cWKywKI

**Comment by LeoJHarris** [comment]
This is a much needed fix! We are also stuck on Xamarin 3.6.

**Comment by samhouts** [comment]
This is another one likely to be resolved by #6390.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Legenda374** [comment]
I added a project, you need to press the button several times and to scroll listview. It repeats.
https://github.com/Legenda374/XamarinBug.git

**Comment by Legenda374** [comment]
Please reply to me so that you can repeat the bug

**Comment by samhouts** [comment]
closed by #6390
