### ISSUE TITLE
[Bug] [WPF] ViewCell in scrollable list view does not update width when restoring from maximized window

### ISSUE THREAD

**Issue by domyd** [xamarin/Xamarin.Forms#6842]
### Description

When restoring a WPF Window from maximized state, `ViewCell`s are not resized if they're in a scrollable (in the non-maximized state) `ListView`. The `Xamarin.Forms.Platform.WPF.CellControl.OnRenderSizeChanged` method, which gets called if I simply resize the window horizontally, does _not_ get called in this case.

If the `ListView` doesn't have a scrollbar in the non-maximized state, the `ViewCell` width gets updated as expected.

Related: #5682

### Steps to Reproduce

1. Build and run the attached repro application.
2. Make sure the displayed list view has a scroll bar.
3. Maximize the window
4. Restore the window back to its normal state and size. At this point you should see that the `ViewCell`s are still as wide as they were in the maximized state.
5. Scroll down, which should update the `ViewCell` to their correct size. (Horizontally resizing the window doesn't update the `ViewCell`, however ...)

### Expected Behavior
The `ViewCell`s should resize when the window size is restored from the maximized state, even if they're in a scrollable `ListView`.

### Actual Behavior
They aren't.

### Basic Information

- Version with issue: Stable (4.1.0.581479) as well as Nightly (4.3.0.936-nightly)
- IDE: Visual Studio 2019 v16.1.6
- Nuget Packages: None except Xamarin.Forms
- Affected Devices: Windows 10 v1903 (Build 18362.116)

### Screenshots

State after opening the app. The X's represent the left/right edges of the ViewCell, the test# text is centered.
![step1](https://user-images.githubusercontent.com/5590413/60968338-1b5d7700-a31d-11e9-9b45-31a24f77e31c.png)

Maximize:
![step2](https://user-images.githubusercontent.com/5590413/60968339-1bf60d80-a31d-11e9-9165-15871112d577.png)

Restore:
![step3](https://user-images.githubusercontent.com/5590413/60968341-1bf60d80-a31d-11e9-90d0-f307b2f01c03.png)

Scroll down:
![step4](https://user-images.githubusercontent.com/5590413/60968342-1bf60d80-a31d-11e9-895a-a9764b54bf9c.png)

### Reproduction Link

[ViewCellResize.WPF.zip](https://github.com/xamarin/Xamarin.Forms/files/3377358/ViewCellResize.WPF.zip)

**Comment by jsuarezruiz** [comment]
If the ListView before maximizing had scroll, when minimizing, the method [OnRenderSizeChanged](https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.onrendersizechanged?view=netframework-4.8) https://github.com/xamarin/Xamarin.Forms/blob/8d526f34a8ed6d97ddd0b40d068f630e1aab37d3/Xamarin.Forms.Platform.WPF/CellControl.cs#L88 is not called. In this case, the size of every cell is still the size from the maximized state.
