### ISSUE TITLE
How to set HelperText in Entry using Xamarin.Forms.Visual.Material? 

### ISSUE THREAD

**Issue by thiagomeloto** [xamarin/Xamarin.Forms#6845]
I've looked at the docs, but couldn't find a way to set inputs' HelperText with Visual Material. Is this supported? If not, are there plans to support it? 

PS.: I've opened the issue as a bug by mistake.

**Comment by jsuarezruiz** [comment]
About the HelperText:
<img width="794" alt="Captura de pantalla 2019-07-18 a las 17 10 02" src="https://user-images.githubusercontent.com/6755973/61469270-2b113700-a97f-11e9-9e6e-539e4eabcdb4.png">
It is not yet supported. The support will be added with the PR related to: https://github.com/xamarin/Xamarin.Forms/issues/5005
At the moment, you must use Custom Renderers to be able to use it.
