### ISSUE TITLE
Xamarin_iOS_UIKit_UIResponder_get_InputAssistantItem: unrecognized selector sent to instance 0x12df62320

### ISSUE THREAD

**Issue by mwasim** [xamarin/Xamarin.Forms#6847]
### Description
We're getting the following fatal exception (crash) on iOS. Although, it normally works fine, and rarely observed in the Firebase crash reports. (Just couple of crashes are observed so far). Yet the below Stack Trace info, and details below might be helpful to fix this bug.

Fatal Exception: NSInvalidArgumentException
-[Xamarin_Forms_Platform_iOS_ReadOnlyField inputAssistantItem]: unrecognized selector sent to instance 0x12df62320
Xamarin_iOS_UIKit_UIResponder_get_InputAssistantItem

Stack Trace Info:
at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) <0x100e62b8c + 0x0004c> in <8f1cf8fa8604454db31e175df104baa7#ebab313b0d534f92db6256e30317d142>:0 
 at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) <0x100e5f820 + 0x00007> in <8f1cf8fa8604454db31e175df104baa7#ebab313b0d534f92db6256e30317d142>:0 
 at (wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
 at (wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr)
 at UIKit.UIResponder.get_InputAssistantItem () <0x100ea2b40 + 0x0001b> in <8f1cf8fa8604454db31e175df104baa7#ebab313b0d534f92db6256e30317d142>:0 
 at `Xamarin.Forms.Platform.iOS.PickerRendererBase1[TControl].OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) <0x1012a4644 + 0x004c7> in <7402bf39df944a9ebf61606e5f9c45a4#ebab313b0d534f92db6256e30317d142>:0 

### Steps to Reproduce
There are no particular steps to reproduce the issue, and the issue occurs very rarely.

### Possible Bug (and Fix?)
Looking at the PickerRenderer class, looks like the below lines 84, and 85 are causing the exception because here the object `InputAssistantItem` is being accessed here.

[https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs#L84](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/PickerRenderer.cs#L84)

```
84: entry.InputAssistantItem.LeadingBarButtonGroups = null;
85: entry.InputAssistantItem.TrailingBarButtonGroups = null;
```

BTW, I've also mentioned the user's device info under "Affected Devices" section below. Is it possible as user is using an older version of iOS `8.3.0`, that's why this crash is being observed?

### Expected Behavior
This fatal exception should never be thrown on iOS devices.

### Basic Information

- Version with issue:
Xamarin.Forms version = 3.6.0.344457

- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  12.0

- Nuget Packages:
Xamarin.Forms version = 3.6.0.344457

- Affected Devices:
Model: iPad Mini 2
Orientation: Landscape
RAM free: 44.89 MB
Disk free: 477.58 MB
OS Version: 8.3.0 (12F69)
Orientation: Portrait

**Comment by samhouts** [comment]
Hard to tell for sure if your suggestion would resolve the problem without a reproduction, but we would be willing to try some defensive coding around that area. Would you like to submit a PR? Thanks!

**Comment by mwasim** [comment]
Thanks @samhouts! From the documentation (below Urls), I see, the "InputAssistantItem" is supported only in the iOS 9.0+. So, I think, the issue would be reproducible for the users using iPad with version less than 9.0+, for example, as it's observed in this particular crash report,

[https://developer.apple.com/documentation/uikit/uitextinputassistantitem](https://developer.apple.com/documentation/uikit/uitextinputassistantitem)
[https://docs.microsoft.com/en-us/dotnet/api/uikit.uiresponder.inputassistantitem?view=xamarin-ios-sdk-12](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiresponder.inputassistantitem?view=xamarin-ios-sdk-12)

So based on your suggestion, to fix this issue, can we push a PR with some defensive code change like below?

```
double.TryParse(UIDevice.CurrentDevice.SystemVersion, out var sysVersion);
const double inputAssistantItemMiniOSVersion = 9.0;

if (sysVersion >= inputAssistantItemMiniOSVersion)
{
	entry.InputAssistantItem.LeadingBarButtonGroups = null;
	entry.InputAssistantItem.TrailingBarButtonGroups = null;
}
```
