### ISSUE TITLE
[Enhancement] Shell Navigation with Models

### ISSUE THREAD

**Issue by LightAndrek** [xamarin/Xamarin.Forms#6848]
## Summary
Use a Model Class instead of using Query Property to pass data to a page.

## API Changes

In order to facilitate the new _Navigation_ api, an _object_ is added to the parameters of the _GoToAsync_ call.

    var model = new MyModel();
    await Shell.Current.GoToAsync("PAGE_URI", model); // call GoToAsync() using a Model Class

## Intended Use Case
This new feature could be useful for passing many complex data between pages, without having to pass all the data as strings.

**Comment by groege** [comment]
There should also be a virtual method on the target page we can override to get said model
i.e.: public virtual void OnParameter(object model) {}

**Comment by groege** [comment]
It would also be nice to have the option to pop a page and pass data as well.

**Comment by chrisstaley** [comment]
I would also love to see this in the native API, since I hate magic strings. I'm currently using my own thin wrapper around Shell navigation to do this. e.g.

```c#
await _shellNavigationService.GoToAsync(ShellRoute.ModifyLocation, new ModifyLocationRouteParameters {LocationID = locationID});
```

**Comment by groege** [comment]
Bump
Any progress on this?

**Comment by xperseguers** [comment]
How do you plan to (1) support something like that and (2) do that with models?

```
//animals/species?type=monkeys/profile?animal=gorilla
```

This is highly useful in the context of hierarchical data navigation, more detailed on 
https://forums.xamarin.com/discussion/174636/taking-advantage-of-shell-routing-with-hierarchical-data

**Comment by michaldivis** [comment]
Any progress on this?

**Comment by Adlorem** [comment]
Well xamarin shell should theoretically make life easier, but after googling the whole day how to pass model with additional parameters to page while navigating, it seems to be a nightmare. I really don't understand why to move from standard navigation to shell, unless you write basic apps.

**Comment by ymebrugts** [comment]
I have generic objects that are defined before the app is compiled. Each page has one of these to specify layout choices. I had to put it in a singleton. It works okayish.

**Comment by luismts** [comment]
Any update on this?

**Comment by AmSmart** [comment]
Would this come through in 5.0? @samhouts

**Comment by JFMG** [comment]
> How do you plan to (1) support something like that and (2) do that with models?
> 
> ```
> //animals/species?type=monkeys/profile?animal=gorilla
> ```
As the issue opener suggested already, I think to pass more complex data as another parameter in the GoToAsync Command is a good approach.

Now we have GoToAsync(string) but GoToAsync(string, object[]?) or GoToAsync(string, param object[]?) would be nice. You could still just use your text link. In this case the object would be null and developers will have to handle this. There are developers who don’t need deep linking and for them it would be a nice choice. And in other cases the deep linking must not work, if you need a complex parameter like a command that is created in a view model from another page. E.g. think of a modal page showing a Retry button and that retry button has to perform the command from the previous view model. So of course I never want to deep link to that page but I want to have the possibility to pass this command to the new view mode.

**Comment by jfversluis** [comment]
Hey everyone! I think it's clear that this is something a lot of people are excited about! 

Unfortunately, we won't be able to make this happen for Xamarin.Forms anymore. If it's still something you are interested in, make sure that there is an issue for it on the .NET MAUI repo. If not, feel free to open one (or maybe a discussion first) with all the (revised) details. I will also label this accordingly and see if I can bring it up as a potential new feature for an upcoming version.

Thank you everyone for being so involved!
