### ISSUE TITLE
[Bug] [CollectionView] [Xamarin.forms] item will be centered when there is only one item

### ISSUE THREAD

**Issue by micro1226** [xamarin/Xamarin.Forms#6851]
### Description
When i use collection view which span count is 3, it works fine except when itemSource has only one Item. the only one item displays in the center of the collectionView, but i hope it can displayed in the left.

### Steps to Reproduce

1. use CollectionView in Xamarin.forms
2. 
```
<CollectionView ItemsSource="{Binding ItemsSource}"
                HorizontalOptions="StartAndExpand"
                VerticalOptions="FillAndExpand">
    <CollectionView.ItemsLayout>
        <GridItemsLayout HorizontalItemSpacing="15"
                         Orientation="Vertical"
                         Span="3"
                         VerticalItemSpacing="15" />
    </CollectionView.ItemsLayout>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            // Template
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```
3. make ItemsSource have only one item

### Expected Behavior
CollectionView item shows in the left
### Actual Behavior
CollectionView item shows in the Center

### Basic Information

- Version with issue: 4.1.0.555618

### ScreenShot
![image](https://user-images.githubusercontent.com/10204912/61107010-63ad9e00-a4b1-11e9-92c5-5b1c600ad9a2.png)
![image](https://user-images.githubusercontent.com/10204912/61107021-690ae880-a4b1-11e9-9970-fb81e83b6fb6.png)

### Demonstrates
https://github.com/micro1226/CollectionDemoForXamarin.git

**Comment by samhouts** [comment]
@micro1226  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by micro1226** [comment]
> @micro1226 Can you please attach a small project that demonstrates this issue? Thanks!

Hi, i edit my issue. add ScreenShot and Demonstrates
Thanks

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample!. Verified. With more than one element (can be 2, 3, 4, etc.) the alignment is correct (aligned the left). With a single element appears centered.

**Comment by vtserej** [comment]
@jsuarezruiz any explanation on why it is switching between backlog and Todo

**Comment by adrianknight89** [comment]
This is like FlexLayout meets CollectionView. @micro1226 If your data source is small, you might want to stick to FlexLayout for this for now.

**Comment by follesoe** [comment]
Any updates on this or workarounds? Generating and hiding a faux element to ensure more than 1 element when on iOS?

**Comment by iamlawrencev** [comment]
Can confirm this bug. Seems to only affect iOS. I'm on 4.3.0.991221.

**Comment by micro1226** [comment]
> Any updates on this or workarounds? Generating and hiding a faux element to ensure more than 1 element when on iOS?

i used telerik listview to solve this problem temporarily

**Comment by vtserej** [comment]
3 and a half month and the bug in the same place.

**Comment by gioggio79** [comment]
Xamarin Forms 4.5.0.356 bug still here. 
Any news or update for this issue?

**Comment by JigarM** [comment]
Any workaround on this?

**Comment by gioggio79** [comment]
The only "workaround" I'll find is to add uno item with opacity=0 if I have only one item in my collection.

**Comment by NataliiaBidiuk** [comment]
Will you fix it in the future? This bug is common and needs to be fix.

**Comment by dhanaraj94** [comment]
Hi Team, 
Still I am facing the issue in latest version 4.6

**Comment by follesoe** [comment]
Same as @dhanaraj94, have updated my code to use the latest release but still see the same issue (single item groups getting centered). Also, I have now noticed issues with item sizing I do not have when not using grouping. I do not know if this is a new bug in 4.6 or an existing one that I have not noticed as I have not been using grouping. Will report that separately once confirmed.

**Comment by maksym-husiev** [comment]
The same as @follesoe  and @dhanaraj94

**Comment by tamasszadvari** [comment]
I'm still experiencing the issue with the latest Xamarin.Forms (version 4.8.0.1269). I have 2 columns and I use grouping also.

**Comment by doberman-ch** [comment]
I also have this issue. I'm using 2 columns with grouping (version 4.8.0.1451)

**Comment by hartez** [comment]
@tamasszadvari @doberman-ch The original issue didn't involve grouping - I think you might be experiencing a similar bug with a different cause. Can you open a new issue (with some info on your datasource, how you are grouping, your templates, and maybe some screenshots or a repro project)? 

Thanks.

**Comment by Waaheeda** [comment]
IS there any update ? facing same issue with XF 4.8 , only on iOS , android works fine

**Comment by hartez** [comment]
@Waaheeda are you experiencing this with a grouped collection, or a non-grouped collection?

**Comment by Waaheeda** [comment]
@hartez grouped collection only on iOS

**Comment by hartez** [comment]
Then please open a new issue and provide the relevant details (https://github.com/xamarin/Xamarin.Forms/issues/6851#issuecomment-704588474).

**Comment by rria-ranch-idea** [comment]
This still happens when you add a footer to your collectionview.
As soon as I add a footer, the cell aligns to the center instead of aligning to the left.

This triggers the bug to happen again, and the cell is center aligned:
```xaml
<CollectionView.Footer>
    <Label />
</CollectionView.Footer>
```

This does not trigger the bug, and the cell is left aligned:
```xaml
<CollectionView.Footer>
</CollectionView.Footer>
```

**Comment by jvlppm** [comment]
This still happens when you add a footer to your collectionview.
As soon as I add a footer, the cell aligns to the center instead of aligning to the left.

This triggers the bug to happen again, and the cell is center aligned:
```xaml
<CollectionView.Footer>
    <Label />
</CollectionView.Footer>
```

This does not trigger the bug, and the cell is left aligned:
```xaml
<CollectionView.Footer>
</CollectionView.Footer>
```

**Comment by Sassha5** [comment]
Almost 3 years passed since this issue was opened and I caught it in the same case as @jvlppm mentioned above. I was digging a lot through the source code and putting all the puzzles together. 
It looks like a known issue and there is a fix for it in the source code. (I'm not a Github guru so I don't know if I can link exact files and lines of code)

`
if (NeedsSingleItemHorizontalAlignmentAdjustment(layoutAttributesForRectElements))
{
	// If there's exactly one item in a vertically scrolling grid, for some reason UICollectionViewFlowLayout
	// tries to center it. This corrects that issue.
	var currentFrame = layoutAttributesForRectElements[0].Frame;
	var newFrame = new CGRect(CollectionView.Frame.Left + CollectionView.ContentInset.Right,
	currentFrame.Top, currentFrame.Width, currentFrame.Height);
	layoutAttributesForRectElements[0].Frame = newFrame;
}

bool NeedsSingleItemHorizontalAlignmentAdjustment(UICollectionViewLayoutAttributes[] layoutAttributesForRectElements) 
{
	if (ScrollDirection == UICollectionViewScrollDirection.Horizontal)
	{
		return false;
	}

	if (layoutAttributesForRectElements.Length != 1)
	{
		return false;
	}

	if (layoutAttributesForRectElements[0].Frame.Top != CollectionView.Frame.Top + CollectionView.ContentInset.Bottom)
	{
		return false;
	}

	return true;
}
`
The problem is in the last "if" statement and in the CollectionView.ContentInset.Bottom, which is not 0 anymore when there is a footer. I figured out a better workaround than posted above so I'm sharing it with anyone who might stumble upon this problem. 

`
[assembly: ExportRenderer(typeof(CardCollectionView), typeof(iOSCardCollectionViewRenderer))]
namespace Project.iOS.Renderers
{
    public class iOSCardCollectionViewRenderer : CollectionViewRenderer
    {
        protected override ItemsViewLayout SelectLayout()
        {
            return new CardViewLayout(Element.ItemsLayout as GridItemsLayout, Element.ItemSizingStrategy);
        }
    }

    public class CardViewLayout : GridViewLayout
    {
        public CardViewLayout(
            GridItemsLayout itemsLayout,
            ItemSizingStrategy itemSizingStrategy)
            : base(itemsLayout, itemSizingStrategy)
        {
        }

        public override UICollectionViewLayoutAttributes[] LayoutAttributesForElementsInRect(CGRect rect)
        {
            var layoutAttributesForRectElements = base.LayoutAttributesForElementsInRect(rect);

            if (layoutAttributesForRectElements.Length == 1)
            {
                var currentFrame = layoutAttributesForRectElements[0].Frame;
                var newFrame = new CGRect(CollectionView.Frame.Left + CollectionView.ContentInset.Right,
                currentFrame.Top, currentFrame.Width, currentFrame.Height);
                layoutAttributesForRectElements[0].Frame = newFrame;
            }

            return layoutAttributesForRectElements;
        }
    }
}
`

I have a subclass of CollectionView but I think you can achieve the same result overriding the standard CollectionView's renderer. But be aware that my subclass works only with GridItemsLayout, you'll need more code to expand it for any layout.

Note: I didn't test it thoroughly but it's only a slightly modified version of the fix which is already in the source code so I think it should be fine in most cases.

**Comment by follesoe** [comment]
@Sassha5 First of all, thanks for sharing your findings! I have the same issue, and will give your proposed solution a try.

Some GitHub tips:
- Navigate to the repository on GitHub, and hit the `t` button which brings up a command palette where you can quickly navigate/search for a particular file
- Select the file and you get an URL like: https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs
- To link to a specific line click the line number in the left column, like this (it will add a `#L26` for a link to line 26): https://github.com/xamarin/Xamarin.Forms/blob/5.0.0/Xamarin.Forms.Core/PlatformConfiguration/iOSSpecific/Entry.cs#L26
- Use triple back-ticks for to start a code block like this: ```, and close with three back ticks. You can even add a language identifier such as `csharp` directly after the three back ticks to indicate language

```csharp
public void Foo() {}
```

**Comment by Sassha5** [comment]
@follesoe Thanks for the tips, now it looks much better! I'm glad that I helped someone and hope it worked for you. I also think that we should reopen this issue because it still persists when there is any footer.

**Comment by Colinkl** [comment]
@Sassha5 Thank you! your code helped me very much!
