### ISSUE TITLE
[Enhancement] XamarinFormsVersion msbuild property 

### ISSUE THREAD

**Issue by chamons** [xamarin/Xamarin.Forms#6859]
## Summary

The customer here:
https://developercommunity.visualstudio.com/content/problem/640098/xamarin-base-build-
properties.html

requests an MSBuild property for XI and XF that is the current version for use/logging.

I've filed [this issue](https://github.com/xamarin/xamarin-macios/issues/6560) for iOS. 

## API Changes

A new XamarinFormsVersion MSBuild variable that contains the current version number. 

## Intended Use Case

Logging and use during msbuild (customer was not specific).

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
