### ISSUE TITLE
Xamarin Forms Shell doesn't seem to implement AutomationId

### ISSUE THREAD

**Issue by rscholey** [xamarin/Xamarin.Forms#6867]
Tested this in iOS.  As far as I can see there's no good way to perform a tap of a tab unless I use the Title (searching for "Settings" works).  I think the Shell Tab element needs to implement AutomationId.  

Forms version: 4.1.0.581479

Below is a sample of code:

    _app.WaitForElement(x => x.Marked("Set1"));
    _app.Tap(x => x.Marked("Set1"));

Xamarin.UITest is not able to locate the element with Id of "Set1" in any of these three locations in the XAML.

      <Tab AutomationId="Set1"
             Title="Settings" 
             Icon="tab_settings.png">
            <ShellContent 
                AutomationId="Set1"
                Route="SettingsTab" 
                Shell.NavBarIsVisible="false" >
                <views1:SettingsTabPage AutomationId="Set1" />
            </ShellContent>
        </Tab>

**Comment by samhouts** [comment]
@rscholey  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Also, please try 4.2.0-pre1 and see if that helps. Thanks!

**Comment by samhouts** [comment]
@rscholey  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
