### ISSUE TITLE
CollectionView doesn't resize on orientation change (Android) [Bug] 

### ISSUE THREAD

**Issue by SkeletonJohn** [xamarin/Xamarin.Forms#6869]
### Description
Collection view doesn't resize on orientation from Portrait to Landscape.

### Steps to Reproduce

1. Add CollectionView to a ContentPage (setting Horizontal and Vertical options to FillAndExpand)
2. Bind ItemsSource to a collection with items
3. Start in a simulator in Portrait
4. Rotate device to Landscape

### Expected Behavior
Contents of CollectionView resize to fill entire view

### Actual Behavior
Content doesn't resize leaving whitespace on the right.

### Basic Information

- Version with issue: 4.1.0.581479
- Last known good version: Unknown
- IDE: Visual Studio
- Platform Target Frameworks: 
    - Android: Android 9.0 Pie 
- Nuget Packages:
- Affected Devices:  Android Simulator - Oreo, Device Essential PH1, and others.

            <StackLayout Grid.Row="2" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Padding="10, 0, 10, 0">
                <CollectionView ItemsSource="{Binding SearchResults}" 
                                HorizontalOptions="FillAndExpand" 
                                VerticalOptions="FillAndExpand" 
                                SelectedItem="{Binding SelectedItem}"
                                SelectionMode="Single">
                    <CollectionView.Behaviors>
                        <behaviors:EventToCommandBehavior EventName="SelectionChanged" Command="{Binding SelectionChangedCommand}"/>
                    </CollectionView.Behaviors>
                    <CollectionView.ItemTemplate>
                        <DataTemplate>
                            <Grid HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="Auto"/>
                                    <RowDefinition Height="Auto"/>
                                    <RowDefinition Height="Auto"/>
                                </Grid.RowDefinitions>
                                <Label Grid.Row="0" Text="{Binding Date, StringFormat='{0:MMMM dd, yyyy}'}" FontAttributes="Bold" FontSize="14" HorizontalOptions="CenterAndExpand"/>
                                <htmlLabel:HtmlLabel Grid.Row="1" Text="{Binding Entry}" InputTransparent="True"/>
                                <BoxView Grid.Row="2" HeightRequest="1" HorizontalOptions="FillAndExpand" BackgroundColor="Black"/>
                            </Grid>
                            
                        </DataTemplate>
                    </CollectionView.ItemTemplate>
                </CollectionView>
              
            </StackLayout>

### Screenshots
![Screenshot_1563130033](https://user-images.githubusercontent.com/51512233/61188019-3dba0200-a647-11e9-90ef-ac7aa0ad38f9.png)

![Screenshot_1563130022](https://user-images.githubusercontent.com/51512233/61188022-49a5c400-a647-11e9-923e-c740e3649785.png)

**Comment by jsuarezruiz** [comment]
I will do some tests using HtmlLabel but using a Label instead, the CollectionView seems to adapt as it should.

<img width="490" alt="Captura de pantalla 2019-07-15 a las 19 01 12" src="https://user-images.githubusercontent.com/6755973/61234551-ab435c80-a733-11e9-9a18-041aa038ffba.png">
<img width="811" alt="Captura de pantalla 2019-07-15 a las 19 01 34" src="https://user-images.githubusercontent.com/6755973/61234553-abdbf300-a733-11e9-92fe-684e0d8f7628.png">

Attached a sample project.
[Test6869.zip](https://github.com/xamarin/Xamarin.Forms/files/3393349/Test6869.zip)
Feel free to modify the project if it does not match with your conditions.

**Comment by SkeletonJohn** [comment]
I've replaced the HtmlLabel with a standard Label and I'm still seeing the issue.  I'll work with your sample to see if I can recreate it there.

**Comment by SkeletonJohn** [comment]
My page is in a NavigationPage with NavigationPage.HasNavigationBar="False" to hide the Navigation Bar.  Once I added this to your sample, I'm getting the same behavior I'm seeing in my app.

![Screenshot_1563228472](https://user-images.githubusercontent.com/51512233/61252432-7f23dd80-a72b-11e9-88d7-6fcbbba4a086.png)

Updated Sample: 
[Test6869.zip](https://github.com/xamarin/Xamarin.Forms/files/3394387/Test6869.zip)

Thank you.

**Comment by SkeletonJohn** [comment]
Update - If I add the ItemsLayout back in as you had in your original sample it does work as expected.  So, it appears that if you have a NavigationPage with HasNavigationBar="False", then the GridItemsLayout is required.  Maybe this should be defaulted?

 <CollectionView.ItemsLayout>
                <GridItemsLayout
                    Orientation="Vertical" />
 </CollectionView.ItemsLayout>

**Comment by jsuarezruiz** [comment]
Verified. I have done more tests. Without setting the **ItemsLayout** property, we do a fallback to **ListViewLayout** (a vertical layout). Using a NavigationPage and changing the orientation does not calculate the new size correctly. Without the NavigationPage works as expected.
Thanks for the feedback!

**Comment by angelru** [comment]
The same issue here with XF 4.4

**Comment by laitauchocolat** [comment]
Same issue in a carouselView

**Comment by Xyotic** [comment]
Also happens to me an Androi AND iOS with XF 4.4.0.991537

**Comment by chaosifier** [comment]
One workaround that seems to work is to reset the ItemsLayout property on OnSizeAllocated event or orientation change event if you have one implemented.
```
 var bak = theCv.ItemsLayout;
 theCv.ItemsLayout = null;
 theCv.ItemsLayout = bak;
```

**Comment by Huaba93** [comment]
same problem using 4.6.0.529-pre3

**Comment by dinesh4official** [comment]
Hi @samhouts ,

In the latest version, still the reported issue occurs.

**Comment by gtrafford** [comment]
I'm having this same issue. But I've noticed it's only the case when I have ItemSizingStrategy set to MeasureFirstItem. It works as expected when set to MeasureAllItems.
