### ISSUE TITLE
[Enhancement] Frame - Shadow management

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#6873]
## Summary
Add the ability to control the shadow settings. position, blur.

## API Changes
``` cs
    var frame = new Frame();
    button.ShadowBlur= 0.4; // new API
    button.ShadowThickness= new Thickness(1,2,3,4); // new API
```

**Comment by jsuarezruiz** [comment]
Looks nice. Let me include some extra properties to allow to customize even more.
- **ShadowColor** (Color): Gets or sets the color of the shadow.
- **ShadowOpacity** (Double): Gets or sets the opacity of the shadow.

And then a question, **ShadowThickness** would be to set the Offset, right?

![OLeZM](https://user-images.githubusercontent.com/6755973/61213945-d5caf080-a706-11e9-8d9d-f6c78b579acc.png)

Maybe we can include a ShadowOffset (Offset) property with ShadowOffsetX (Double), ShadowOffsetY (Double) ones.

Just for reference, add a link to the UWP API: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/dropshadowpanel

**Comment by KSemenenko** [comment]
@jsuarezruiz ShadowOffset  will be great!

**Comment by requenaxii** [comment]
Sounds cool, I'm dealing with those properties right now via custom renderer without success for now... 

maybe could add **RoundCorners** property to apply `CornerRadius` property independently to have more flexibility.

**Comment by KSemenenko** [comment]
There are some problems, CardView (FastRenderer for Frame base on CardView) for android does not allow shadow control. What do you think, what to do in this case?

**Comment by samhouts** [comment]
This should be covered by https://github.com/xamarin/Xamarin.Forms/issues/7744
