### ISSUE TITLE
ListView -> ContextActions: Show icons on iOS

### ISSUE THREAD

**Issue by ClaudiaKr** [xamarin/Xamarin.Forms#6876]
### Description
Now that iOS supports context menu icons, please enable it in Xamarin.Forms. 

### Steps to Reproduce
Set the icon property for a menu item: <MenuItem Icon="bookmark" />

### Expected Behavior
The icon appears in the context menu
### Actual Behavior
Only text (if specified)  is shown in the context menu

**Comment by Wolfgang-h** [comment]
This feature is needed here, too.

**Comment by jsuarezruiz** [comment]
In iOS 13 and later, can use context menus to give access to additional functionality related to onscreen items. Now with some extra options like the icons.
<img width="326" alt="contextmenu" src="https://user-images.githubusercontent.com/6755973/61275879-2433ca00-a7af-11e9-99ea-f7a91457e49e.png">
It can be useful not only in the ListView, but also in other controls (CollectionView for example).

More info: https://developer.apple.com/design/human-interface-guidelines/ios/controls/context-menus/

**Comment by jsuarezruiz** [comment]
Related PR: https://github.com/xamarin/Xamarin.Forms/pull/6382

**Comment by SebastianKruseWago** [comment]
@jsuarezruiz Is this really the same? The linked PR is related to the context actions of a listview while your screenshots refers to 3D-Touch / Heptik Touch. As of right now this is not the same in native iOS development and neither should it become the same here. This is also not an iOS 13 features because it exists since the iPhone 6S (Peek & Pop).

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
