### ISSUE TITLE
[Enhancement] SkiaSharp Controls

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#6877]
## Summary
I think that the option to draw custom controls and visual elements with the help of SkiaSharp right in xaml in Xamarin.Forms was useful to everyone.
This is a good opportunity to do what Flutter does only in Xamarin.Forms.

## API Changes
``` xaml
<SkiaCanvas>
    <SkiaGrid>
        <SkiaRect Width="50" Height="50"/>
        <SkiaLabel Text="SomeText"/>
        <SkiaStack>
             <SkiaLabel Text="SomeText"/>
             <SkiaLabel Text="SomeText"/>
        </SkiaStack>
    </SkiaGrid>
</SkiaCanvas>

```

**Comment by andreinitescu** [comment]
I love SkiaSharp, but depending on the requirements, the size of SkiaSharp can be important (not sure, I think it's around 5MB?) I think @mattleibow has up to date info on this.

**Comment by jfversluis** [comment]
I think indeed the biggest concern with this is that we have to take on a dependency on SkiaSharp which is really not something we want to do.

**Comment by KSemenenko** [comment]
We can create separate library like Xamarin.Forms.Map @andreinitescu @jfversluis

**Comment by KSemenenko** [comment]
@andreinitescu I know how much you like SkiaSharp, can we make it more accessible for Xamarin.Forms?

**Comment by jsuarezruiz** [comment]
The idea reminds me this nice Matthew [project](https://github.com/mattleibow/SkiaSharpGraphics).

If we are talking about facilitate drawing something custom from XAML (shapes, gradients, etc.) it seems as a possible option (among other options). @jfversluis is right about the weight of the dependency, it should be a separate package (Xamarin.Forms.Drawing for example).

If the idea is to have the entire set of Xamarin.Forms controls with support in SkiaSharp, we have several important points here. 
From the outset, would not be in any case a new "backend" (Xamarin.Forms.Platform.Skia)?. And at this point we would have to solve several questions:
- How would be the default rendering?, simulating the native control in each case?, having several rendering options like Cupertino, Material, etc?
- It would be necessary to solve important topics that in native we have them well covered as the accessibility, etc.

With this second idea, I suppose it would be interesting to have other features like Page or View tags to choose between use native control or SkiaSharp, etc.

**Comment by KSemenenko** [comment]
@juliuszint Yes, I have been thinking about this for about a year.
I usually have a main problem: to draw some kind of custom object, like a shadow, a complex object of shapes. It's always readonly object. It may have a gesture recognition, or animation, but it does not allow to get the focus and enter some text. 

The hardest part is the Layout system. I would like to reuse logic from Grid, StakLayout, FlexLayour.
Therefore, Xamarin.Forms.Drawing would be very useful.
By the way, for example, a project that does this:
https://github.com/kevinbrunet/SkiaSharp.DiagramEngine

In the second part, I have 90 percent of projects that should look identical between all platforms.
I do not need native types of buttons, or input fields.
And in such a context, it would be super to have Xamarin.Forms.Platform.Skia which will allow me to do completely platform independent applications.
Here is an example of such a project:
https://github.com/AvaloniaUI/Avalonia

**Comment by yurkinh** [comment]
Here is a sample of SkiaSharp backend for one platform (ios) made by Alexey Strakh

https://github.com/alexeystrakh/Xamarin.Forms.Doodle

**Comment by redradist** [comment]
I also waiting when it will be possible to useSkiaSharp renderers instead of platforms, because it more flexible solution than native renderers ...

For example with SkiaSharp renderers it would be possible to use Xamarin.Forms component in the Web

**Comment by redradist** [comment]
Also I think it would be better to place these views in just in separate namespace like `Xamarin.Forms.Skia` or `Xamarin.Forms.Canvas` (with different renderer libraries, not only SkiaSharp)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. 

In this case you might want to check out the https://github.com/dotnet/Microsoft.Maui.Graphics.Controls project.

Thanks!
