### ISSUE TITLE
[Bug] ShellItem.Items.Clear() crashes when the ShellItem has bottom tabs

### ISSUE THREAD

**Issue by SFSteve** [xamarin/Xamarin.Forms#6878]
### Description
When using shell, if you want to programmatically clear and redraw the bottom tabs on a shell page, you can't use Items.Clear to get rid of all the existing ones because it crashes. Investigation suggests that this is because it's trying to set properties on a tab that is no longer there.

### Steps to Reproduce

1. Create a ShellItem in xaml that contains tabs.
2. In code, call Items.Clear() on your ShellItem.
3. A null exception will occur on line 83 of ShellBottomNavViewAppearanceTracker.SetBackgroundColor, presumably because menuView.GetChildAt(index) returns null, either because index is -1 or menuView has no children.

### Expected Behavior
The tabs are cleared and you're free to create new ones
### Actual Behavior
Exception and crash
### Basic Information

- Version with issue: 4.0.0.425677
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  Untested
  - Android: 9.0

**Comment by jsuarezruiz** [comment]
Do you have a sample where the problem happens?, could you attach it?. Thanks in advance!

**Comment by SFSteve** [comment]
https://github.com/SFSteve/Xamarin-Demos/tree/master/Xaminals

If you run that then go to the Random page from the flyout menu, you'll get the error.

**Comment by francis2** [comment]
If it helps, here is another test app to demonstrate the issue.

The crash happens at AppShell.xaml.cs line 29.

[PickerTestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3407225/PickerTestApp.zip)

**Comment by PureWeen** [comment]
Most likely the fix for this will be to just throw an exception that *Clear* isn't supported for Shell

If you clear all the items then Shell has no idea what to display. It's like setting the MainPage on the app to NULL

We have work being done for an IsVisible property which will be the way to change visibility of items. For now I would just add what you are wanting to add then remove what you are wanting to remove

**Comment by SFSteve** [comment]
An IsVisible flag would be ideal and solve the actual issue we're having, so it's good to know there's one on the way.

**Comment by samhouts** [comment]
closed by #8215

**Comment by minahenin** [comment]
are you going to fix it in IOS?
