### ISSUE TITLE
[Enhancement] Remove internal access modifier from Material

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#6881]
## Summary

Change the access modifier on several things in the Xamarin.Forms.Material package from internal to public.

## API Changes

Android
- `internal void MaterialFormsTextInputLayoutBase.SetHint(string hint, VisualElement element)`
- `internal void MaterialFormsTextInputLayoutBase.ApplyTheme(Color formsTextColor, Color formsPlaceHolderColor)`

iOS
- `internal interface IMaterialTextField`
- `internal static class MaterialTextManager`

## Intended Use Case

For making material renderers for custom controls, e.g. nullable DatePicker/TimePicker.

**Comment by samhouts** [comment]
@PureWeen Any objections?

**Comment by andreas-nesheim** [comment]
I'd like to jump on this, if it's still up for grabs.
