### ISSUE TITLE
[Bug] Unable to use Material Visual and EntityFrameworkCore.SqlLite together on Android

### ISSUE THREAD

**Issue by Corneliuskruger** [xamarin/Xamarin.Forms#6883]
### Description
Using Material Visual with EntityFrameworkcore.Sqlite.Design in the same project causes an Exception on Android

Unhandled Exception:

System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not resolve type with token 01000057 from typeref (expected class 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' in assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.1.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') occurred

### Steps to Reproduce

1. Create a new Xamarin.Forms project using the Shell template
2. Install and initialize Xamarin.Forms.Visual.Material
3. Add an entry to the ItemDetailPage.xaml file and set Visual=Material i.e. 
<Entry Text="{Binding Item.Description}" Placeholder="Description" Visual="Material" />
4. Test and confirm app is working.
5. Install Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.Sqlite.Design nugets.
6. Test and confirm Exception.
7. Remove Visual="Material" from Entry
8. Test and confirm app is working.

### Expected Behavior
No Execption is thrown when using Visual="Material" in an app that uses EntityFrameworkCore.Sqlite.

### Actual Behavior

Exception is thrown on Android when using Material visual in an app with EntityFrameworkCore.Sqlite Installed.

### Basic Information

- Version with issue: 4.1.0.581479
- Last known good version: Unknown
- IDE: Visual Studio 2019 (16.1.6)
- Platform Target Frameworks: 
  - iOS:  Seems to work on emulator
  - Android: 9.0
- Android Support Library Version: n/a
- Nuget Packages: Xamarin.Forms.Visual.Material, 
Microsoft.EntityFrameworkCore.Sqlite,
Microsoft.EntityFrameworkCore.Sqlite.Design

- Affected Devices: Google Pixel XL, Google Pixel 3 XL

### Reproduction Link

https://github.com/Corneliuskruger/Visual-Crash-Repo

**Comment by hartez** [comment]
@Corneliuskruger Out of curiosity, what are your linker settings in your Android project?

**Comment by Corneliuskruger** [comment]
@hartez it is set to "None". I think it is the default debug configuration for a new project.

**Comment by hartez** [comment]
> @hartez it is set to "None". I think it is the default debug configuration for a new project.

Okay. Just checking to make sure SQLite wasn't being linked out. Sounds like that's not the cause of this issue.

**Comment by Corneliuskruger** [comment]
> @hartez it is set to "None". I think it is the default debug configuration for a new project.
> 
> Okay. Just checking to make sure SQLite wasn't being linked out. Sounds like that's not the cause of this issue.

I don't think that should matter in this case, I am not even using SQLite in the view. The only change between working and not working is Visual="Material" in the xaml.

**Comment by Corneliuskruger** [comment]
I updated Xamarin.Forms to V4.2.0.608146-pre1 and it seems to have fixed the issue.
