### ISSUE TITLE
The error displaying ViewCell in Android.

### ISSUE THREAD

**Issue by monster74** [xamarin/Xamarin.Forms#6885]
### Description
Xaml cell:
`<?xml version="1.0" encoding="UTF-8"?>
<ViewCell xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AutoGRAPHMobile.DetailCell"
             xmlns:ffimageloading="clr-namespace:FFImageLoading.Forms;assembly=FFImageLoading.Forms"
             xmlns:xamarinLibrary="clr-namespace:XamarinLibrary;assembly=XamarinLibraryNS"
             BindingContextChanged="ViewCell_BindingContextChanged">
    <ViewCell.View>
        <StackLayout Orientation="Horizontal" Margin="1" Padding="2" BackgroundColor="#ffffffff">
            <Grid VerticalOptions="Center">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="34"/>
                </Grid.ColumnDefinitions>
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                </Grid.RowDefinitions>
                <ffimageloading:CachedImage x:Name="imageDetail" Source="{Binding imageDetailIcon}" IsVisible="{Binding VisibleDetailIcon}" WidthRequest="30" HeightRequest="30" HorizontalOptions="Center" Grid.Column="0" Grid.Row="0">
                </ffimageloading:CachedImage>
                <ffimageloading:CachedImage x:Name="imageSummary" Source="summary.png" IsVisible="{Binding VisibleSummary}" WidthRequest="26" HeightRequest="36" HorizontalOptions="Center" Grid.Column="0" Grid.Row="0">
                </ffimageloading:CachedImage>
                <Label x:Name="lIndex" Text="{Binding IndexDisplay}" IsVisible="{Binding VisibleIndex}" TextColor="Black" FontSize="18" LineBreakMode="TailTruncation" HorizontalOptions="Center" Grid.Column="0" Grid.Row="1">
                    <Label.FontFamily>
                        <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                    </Label.FontFamily>
                </Label>
            </Grid>
            <Grid HorizontalOptions="FillAndExpand">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="Auto" />
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="40"/>
                </Grid.ColumnDefinitions>
                <StackLayout x:Name="slLabel" Orientation="Vertical" VerticalOptions="Center" Grid.Column="0" Spacing="1">
                    <Label x:Name="l0" Text="slLabel" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation" HorizontalOptions="StartAndExpand">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="l1" Text="slLabel" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation" HorizontalOptions="StartAndExpand">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="l2" Text="slLabel" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation" HorizontalOptions="StartAndExpand">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="l3" Text="slLabel" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation" HorizontalOptions="StartAndExpand">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="l4" Text="slLabel" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation" HorizontalOptions="StartAndExpand">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                </StackLayout>
                <StackLayout x:Name="slValue" Orientation="Vertical" VerticalOptions="Center" Grid.Column="1" Spacing="1">
                    <Label x:Name="v0" Text="slValue" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="v1" Text="slValue" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="v2" Text="slValue" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="v3" Text="slValue" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                    <Label x:Name="v4" Text="slValue" TextColor="#000000" FontSize="14" LineBreakMode="TailTruncation">
                        <Label.FontFamily>
                            <OnPlatform x:TypeArguments="x:String" iOS="Roboto Condensed" Android="RobotoCondensed-SK-Regular.ttf#Roboto Condensed"/>
                        </Label.FontFamily>
                    </Label>
                </StackLayout>
                <xamarinLibrary:AnimatedButton x:Name="buttomToMap" ImageButton="SwipeTrackBlue.png" WidthRequest="40" ImageButtonHeight="30" ImageButtonWidth="30" Margin="0" HorizontalOptions="Center" VerticalOptions="Fill" Grid.Column="2"/>
            </Grid>
        </StackLayout>
    </ViewCell.View>
</ViewCell>`
In the ViewCell_BindingContextChanged event, the Texts are set in Labels of l0, l1, l2, l3, l4, v0, v1, v2, v3, v4.
Label lIndex does not scale correctly when scrolling through the list.
It helps only if in the ViewCell_BindingContextChanged event call ForceUpdateSize () ;.
Then the displaying of the cell becomes correct.
Please tell me what could be the problem?
This behavior began after updating to Xamarin.Forms 4.0.0.425677.
Before that, there were no such problems.
Further update did not decide the problem.
In iOS everything works fine, the problem occurs only in Android.
Xaml ListView:
`<ListView x:Name="listView" Refreshing="listView_Refreshing" IsPullToRefreshEnabled="True" Margin="0" HasUnevenRows="True" BackgroundColor="Transparent" CachingStrategy="RecycleElement" ItemTapped="listView_ItemTapped"  VerticalOptions="FillAndExpand" SeparatorVisibility="None" Grid.Row="2">
                        <ListView.ItemTemplate>
                            <DataTemplate>
                                <local:DetailCell/>
                            </DataTemplate>
                        </ListView.ItemTemplate>
                    </ListView>`

I send you a demo project. I'm testing on a smartphone. Android 4.4
Attached a few more screenshots with ForceUpdateSize(); and without ForceUpdateSize();

### Basic Information

- Version with issue: 4.1.0.581479
- Last known good version: 3.6.0.539721
- IDE: Visual Studio 2017 15.9.13
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 9.0
  - UWP:  16299
- Nuget Packages: Xamarin.FFImageLoading
- Affected Devices: Android 4.4, Android 6, Android 9

### Screenshots

[http://i.tk-chel.ru/anton/screenshot.zip](url)
### Reproduction Link

[http://i.tk-chel.ru/anton/AppDemo.zip](url)

**Comment by jsuarezruiz** [comment]
I have done several tests using the attached sample (thanks for adding me!). I reproduce the problem.
Some details:
- It only happens on Android.
- Without recycling cells does not happen.
- In Xamarin.Forms 3.6 it does not happen. I reproduce the problem from Xamarin.Forms 4.0 and 4.1 (I will review the related commits).
There are [more devs](https://twitter.com/Oridotaoyebode/status/1151070106514071553) with the same problem.

**Comment by jsuarezruiz** [comment]
Related to: https://github.com/xamarin/Xamarin.Forms/issues/6721

**Comment by monster74** [comment]
Thanks for your reply. I'll wait for the version with the fix.

**Comment by samhouts** [comment]
This should be fixed with the latest versions of 4.0.0 and 4.1.0 released on Wednesday. Thank you!

**Comment by monster74** [comment]
I checked the demo project on version 4.1.0.618606.
Everything also incorrectly displays the text of the index.
Only now the use of the ForceUpdateSize ();  function has also ceased to help
