### ISSUE TITLE
[Enhancement] Self Reference for XAML

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#6890]
## Summary
I suggest adding an extension for XAML **x:Self** or something like this, to get the link itself.

``` XAML
...
<Editor Text="{Binding BackgroundColor, Source={x:Self}" />
...
```

**Comment by KSemenenko** [comment]
it can also be the first parent x:Parent
``` xaml
...
<Editor Text="{Binding BackgroundColor, Source={x:Parent}" />
...
```

**Comment by jsuarezruiz** [comment]
I understand the situations that we are trying to improve here. It is an idea that reminds me to this other proposal: https://github.com/xamarin/Xamarin.Forms/issues/3847
In this case, the solution sought is to add something similar to what is available in UWP: https://docs.microsoft.com/en-us/dotnet/api/system.windows.data.relativesource?view=netframework-4.8

@StephaneDelcroix has implemented **RelativeSource binding modes for Self, TemplatedParent, and FindAncestor** https://github.com/xamarin/Xamarin.Forms/commit/fa853ff823272af4b307521d4b5774165d1c7e2c
Check it out, tell us your feedback about it ;)

**Comment by StephaneDelcroix** [comment]
@jsuarezruiz:

> @StephaneDelcroix has implemented RelativeSource binding modes for Self, TemplatedParent, and FindAncestor fa853ff

wow, wait, all credits goes to Peter Moore (@legistek)

**Comment by StephaneDelcroix** [comment]
@KSemenenko thanks for your proposition, but I'm going to close this for the following reasons:
- `Self` is not defined in the `x:` xmlns, so it would fail DTD validation (hopefully, no one does that on XAML),
- `Self` would meant the binding itself, a better name would be `Target`, and then you're setting the Target of the Binding as the Source of the Binding, and my head explodes (yes, RelativeSource has aching named `Self`, that's consistent with other RelativeSource implementation, but that doesn't make the name any better),
- this is already possible with `{RelativeSource}`, I think you'll find what you need there

**Comment by KSemenenko** [comment]
@juliuszint @StephaneDelcroix thanks, I will check it!

**Comment by andreinitescu** [comment]
@jsuarezruiz  Don't be afraid to give credit to contributors too, even if they're not part of the team 😁 Some of them worked very hard even if it's less apparent or recognized.

**Comment by StephaneDelcroix** [comment]
@andreinitescu: @jsuarezruiz just joined the team on Monday, he's not aware of the history, and only looked at the committer name (mine). No harm intended. We give credits were credits is due, and then some more. Thanks all fo r your contributions

**Comment by andreinitescu** [comment]
@jsuarezruiz @StephaneDelcroix Thank you. I need to apologize for my very stupid comment, it came out in a very wrong way, it wasn't my intention to say you're not giving credit! Thanks for the great work and framework.

**Comment by StephaneDelcroix** [comment]
@andreinitescu no need to apologize, and no need to delete your comment. IT was a very civil discussion and we appreciate that you pay attention to this level of details.

have a good day

**Comment by legistek** [comment]
Personally I say the bulk of the credit still belongs to the core team for building and maintaining this project for so long while being pulled in a thousand directions and still having time to vet and accept outside contributions. I on the other hand just work on the features I need for my own projects and would prefer to see them in the core branch because forking is a pain. So it's purely selfish. :D
