### ISSUE TITLE
Custom frame shadow achieved with custom renderer for iOS does not work anymore after changing the frame's visibility

### ISSUE THREAD

**Issue by sachssebastian-eop** [xamarin/Xamarin.Forms#6892]
**What is this issue about?**

On Android, the frame looks a whole lot more material and minimalistic. To achieve the same look on iOS, I created a custom renderer that recudes the shadow radius and opacity and sets up some other things. It works great and looks nice, but as soon as a frame's visibility is hidden and then shown again, the frame has it's default appeareance. Same thing goes for frames in a ListView after performing a refresh. It seems like renderers have no effect after the visibility has been changed.

**Steps to reproduce**:

1.) Create custom frame renderer for iOS:

> using CoreGraphics;
> using eopApp.iOS.Renderer;
> using UIKit;
> using Xamarin.Forms;
> using Xamarin.Forms.Platform.iOS;
> 
> [assembly: ExportRenderer(typeof(Frame), typeof(MaterialFrameRenderer))]
> namespace eopApp.iOS.Renderer
> {
>     public class MaterialFrameRenderer : FrameRenderer
>     {
>         public override void Draw(CGRect rect)
>         {
>             base.Draw(rect);
> 
>             Layer.ShadowRadius = 2f;
>             Layer.ShadowColor = UIColor.Gray.CGColor;
>             Layer.ShadowOffset = new CGSize(0, 1);
>             Layer.ShadowOpacity = 0.60f;
>             Layer.ShadowPath = UIBezierPath.FromRect(Layer.Bounds).CGPath;
>             Layer.MasksToBounds = false;
>         }
>     }
> }

2.) Add a frame to a view and set it's **IsVisible** property to false. Add a button as well that makes the frame visible again on tap.

3.) Before tapping the button, the frame looks like the frame in the first screenshot. After tapping the button, the frame looks like the frame in the second screenshot:

![before](https://user-images.githubusercontent.com/52791674/61108287-37c6f400-a482-11e9-9b93-0785b0102ee8.PNG)
![after](https://user-images.githubusercontent.com/52791674/61108286-37c6f400-a482-11e9-9eb0-1041fb4e23e9.PNG)

**Comment by samhouts** [comment]
@sachssebastian-eop  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by sachssebastian-eop** [comment]
@samhouts Here you are :)

[CustomFrameShadowGitHubTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3400575/CustomFrameShadowGitHubTest.zip)

**Comment by samhouts** [comment]
@sachssebastian-eop I tried the sample and followed the directions, but the Frame didn't change at all for me. I was using an iPhone XS Max with iOS 12. Were you testing a specific version of iOS? 

I also see that the project is using Xamarin.Forms 3.4.0. Is that the version you're experiencing the issue with? I Updated to 4.2.0-pre1 and didn't see any difference.

Have you looked at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual by any chance? I think you can achieve what you want in a much easier way.

**Comment by jsuarezruiz** [comment]
I have also tried the sample and followed the directions, but the Frame didn't change for me either.
![issue-frame](https://user-images.githubusercontent.com/6755973/61532788-420d6300-aa2b-11e9-9de1-601294b82da7.gif)
Tested with Xamarin.Forms 4.x (4.1 and 4.2 pre1).

**Comment by samhouts** [comment]
@sachssebastian-eop  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by sachssebastian-eop** [comment]
Hi all together,

Finally, I was able to check back on that error. I updated my test device to the current firmware, iOS 12.4.1, where it does not happen when refreshing the ListView, but rather sometimes when scrolling. In iOS 11, this still seems to be an error. I suspect an optimization in rendering in iOS 12 which causes the frame to render way faster than it did in iOS 11.2.5.
