### ISSUE TITLE
[Enhancement, SearchHandler] Add ClearOnConfirmed property

### ISSUE THREAD

**Issue by LightAndrek** [xamarin/Xamarin.Forms#6895]
## Summary
Add a new _BindableProperty_ called _ClearOnConfirmed_ which determines whether the query content should be deleted when the search is confirmed.

## API Changes

At this time, when the query is confirmed, the value of the query is deleted and the SearchHandler shows the placeholder. This change is used to add a new property that turns this automatic deletion behavior on or off.

    public static readonly BindableProperty ClearOnConfirmedProperty;
    public bool ClearOnConfirmed { get; set; }

## Intended Use Case
Show the contents of the search bar even when the search has been confirmed and completed.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
