### ISSUE TITLE
[Bug] [CollectionView] [UWP] CollectionView shows empty items when DataTemplateSelector is used on UWP

### ISSUE THREAD

**Issue by toomasz** [xamarin/Xamarin.Forms#6898]
### Description
CollectionView shows empty items when DataTemplateSelector is used. Happens only on UWP

### Steps to Reproduce

1. Run sample

### Expected Behavior
CollectionView shows views defined by templates returned by DataTemplateSelector
### Actual Behavior
CollectionView shows empty items

### Basic Information

- Version with issue: 4.1
- Last known good version: None
- IDE: VS2017
- Platform Target Frameworks: 
  - UWP:  17134

### Screenshots
![obraz](https://user-images.githubusercontent.com/3065454/61380494-be783880-a8a9-11e9-9b20-6a3e76ca72a7.png)

### Reproduction Link

[CollectionViewRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3402139/CollectionViewRepro.zip)

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample. I am able to reproduce the problem. Some details:
- The problem is reproduced in UWP. I have tried with Xamarin.Forms 4.x (4.0, 4.1 and 4.2 Preview).
- Using one of the templates directly works as expected.
- The OnSelectTemplate method from the DataTemplateSelector is not called on UWP!.

**Comment by toomasz** [comment]
@jsuarezruiz Thanks for checking, yes i noticed OnSelectTemplate is not called at all.
Btw, a/listview label is wrong. It should be a/collectionvview

**Comment by hartez** [comment]
Well, I wouldn't exactly call it a "bug", so much as a "thing we haven't implemented yet".

**Comment by hartez** [comment]
Okay, it's in progress: #6918

**Comment by toomasz** [comment]
@hartez Thanks!
