### ISSUE TITLE
[Bug] FontImage markup extension doesn't accept DynamicResources or bindings for several properties

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#6900]
### Description
When trying out the new FontImage markup extension, I can't use a DynamicResource for the Color property, as it results in a build failure. StaticResource works fine. Bindings to viewmodels or other UI elements also struggle.
Note: Using dynamic resources or bindings works fine with the explicit FontImageSource xaml objects, this is an issue only when using the new FontImage extension.

### Steps to Reproduce

1.  Use the FontImage Markup on an UI element like a button or toolbar item. example:
```
<ToolbarItem Command="{Binding RefreshCommand}"
                     IconImageSource="{FontImage FontFamily={StaticResource IconFontFamily},
                                                 Glyph={x:Static icons:Glyphs.refresh},
                                                 Size=25,
                                                 Color={DynamicResource YourDynamicResourceName}}"
                     Text="refresh" />
```

Additional info:
You also can't use bindings for the Glyph or the Color properties.
doing stuff like
> Glyph={Binding Icon, Mode=OneTime}
> Color={Binding Source={x:Reference AnotherButton}, Path=TextColor}

works fine on a FontImageSource but not when you use the FontImage extension.

2. Build the app

### Expected Behavior
It builds and runs.
### Actual Behavior
Build fails with 
"No property, bindable property, or event found for 'Color', or mismatching type between value and property."

### Basic Information

- Version with issue: 4.2.0.608146-pre1
- Last known good version: n/a
- IDE: VS2019 16.1.6
- Platform Target Frameworks: n/a

**Comment by MitchBomcanhao** [comment]
Additional info:
You also can't use bindings for the Glyph or the Color properties.
doing stuff like 
- Glyph={Binding Icon, Mode=OneTime}
- Color={Binding Source={x:Reference AnotherButton}, Path=TextColor}

works fine on a FontImageSource but not when you use the FontImage extension.

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample. I can reproduce the problem. As you mentioned, if the page is always instantiated before navigating:
```
Instance = new Subpage();
await Navigation.PushAsync(Instance);
```

Everything works fine.

If we add the verification to check if the page exists and reuse it, is where we have the issue.
```
if (Instance == null)
{
     Instance = new Subpage();
}
await Navigation.PushAsync(Instance);
```

**Comment by jsuarezruiz** [comment]
@MitchBomcanhao Could you attach a small sample where we can reproduce the problem?

**Comment by MitchBomcanhao** [comment]
Not sure why you'd need it, as it is pretty simple to repro.
Anyway, here it goes. It has a number of buttons with various types of properties being used for their FontImageSource. Those work fine.
For each variant of said button, there's the equivalent FontImage markup version, which has been commented out.
Feel free to uncomment them and see that the project no longer builds due to those DynamicResources and bindings.

[Bug6900_repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3405989/Bug6900_repro.zip)

here's the xaml just as a guide of what to expect:
```
<ContentPage x:Class="Bug6900.MainPage"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d">

    <ContentPage.Resources>
        <Color x:Key="ThisCanBeDynamicColor">#FFFF00FF</Color>
    </ContentPage.Resources>

    <StackLayout VerticalOptions="Center">

        <Label x:Name="GlyphReference" Text="B" TextColor="Green" />

        <!--  This will work, using very plain properties with the fontImage markup  -->
        <Button ImageSource="{FontImage FontFamily=Roboto, Glyph='A', Size=25, Color={StaticResource ThisCanBeDynamicColor}}" Text="button" />



        <!--  BOUND GLYPH  -->

        <!--  This works  -->
        <Button Text="Bound Glyph from ViewModel">
            <Button.ImageSource>
                <FontImageSource FontFamily="Roboto"
                                 Glyph="{Binding GlyphIcon}"
                                 Size="25"
                                 Color="{StaticResource ThisCanBeDynamicColor}" />
            </Button.ImageSource>
        </Button>
        <!--  This doesn't  -->
        <!--<Button ImageSource="{FontImage FontFamily=Roboto, Glyph={Binding GlyphIcon}, Size=25, Color={StaticResource ThisCanBeDynamicColor}}" Text="Bound Glyph from ViewModel" />-->



        <!--  DYNAMICRESOURCE COLOR  -->

        <!--  This works  -->
        <Button Text="DynamicResource Color">
            <Button.ImageSource>
                <FontImageSource FontFamily="Roboto"
                                 Glyph="C"
                                 Size="25"
                                 Color="{DynamicResource ThisCanBeDynamicColor}" />
            </Button.ImageSource>
        </Button>
        <!--  This doesn't  -->
        <!--<Button ImageSource="{FontImage FontFamily=Roboto, Glyph='A', Size=25, Color={DynamicResource ThisCanBeDynamicColor}}" Text="DynamicResource Color" />-->



        <!--  GLYPH BOUND FROM ANOTHER UI ELEMENT  -->

        <!--  This works  -->
        <Button Text="Bound Glyph from another control">
            <Button.ImageSource>
                <FontImageSource FontFamily="Roboto"
                                 Glyph="{Binding Source={x:Reference GlyphReference}, Path=Text}"
                                 Size="25"
                                 Color="{StaticResource ThisCanBeDynamicColor}" />
            </Button.ImageSource>
        </Button>
        <!--  This doesn't  -->
        <!--<Button ImageSource="{FontImage FontFamily=Roboto, Glyph={Binding Source={x:Reference GlyphReference}, Path=Text}, Size=25, Color={StaticResource ThisCanBeDynamicColor}}" Text="Bound Glyph from another control" />-->



        <!--  COLOR BOUND FROM ANOTHER UI ELEMENT  -->

        <!--  This works  -->
        <Button Text="Bound Color">
            <Button.ImageSource>
                <FontImageSource FontFamily="Roboto"
                                 Glyph="A"
                                 Size="25"
                                 Color="{Binding Source={x:Reference GlyphReference}, Path=TextColor}" />
            </Button.ImageSource>
        </Button>
        <!--  This doesn't  -->
        <!--<Button ImageSource="{FontImage FontFamily=Roboto, Glyph='A', Size=25, Color={Binding Source={x:Reference GlyphReference}, Path=TextColor}}" Text="Bound Color" />-->
    </StackLayout>
</ContentPage>
```

**Comment by jsuarezruiz** [comment]
Thanks for the repro sample. 
<img width="1913" alt="Captura de pantalla 2019-07-18 a las 13 18 07" src="https://user-images.githubusercontent.com/6755973/61454140-58022180-a960-11e9-91b5-ca58023104ca.png">
What happens here is the following:
- The Glyph is a property of FontImage markup extension.
- The extensions aren’t BindableObject, and the Glyph property is not BindableAttribute.

So, actually the Binding inside the extension is not supported. As you also use in the sample, using FontImageSource and receiving the desired context allows the use of Binding.

**Comment by StephaneDelcroix** [comment]
as @jsuarezruiz said, if you want to bind to properties of FontImageSource, use the element syntax, not the markup. Anyway, the markup extension is not that shorter...
