### ISSUE TITLE
[Bug] BindableLayout doesn't set Parent

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#6902]
### Description
When using a BindableLayout, it doesn't appear to set the Parent of an element.
### Steps to Reproduce

1. Add a couple of items to a BindableLayout
2. Set a breakpoint and inspect the `Parent` on the top level element
3. 

### Expected Behavior
Parent should not be null
### Actual Behavior
Parent is null
### Basic Information

- Version with issue: 4.1 stable
- Last known good version: n/a
- IDE: Rider
- Platform Target Frameworks: only tested on iOS

```xaml
<StackLayout ItemsSource="{Binding MyItemsSource}">
    <BindableLayout.ItemTemplate>
        <DataTemplate>
            <!-- Label.Parent will be null when it should be the StackLayout-->
            <Label Text="{Binding SomeLabelProperty}" />
        </DataTemplate>
    </BindableLayout.ItemTemplate>
</StackLayout>
```

**Comment by jsuarezruiz** [comment]
I've been doing some tests with Bindable Layouts and checking the parent of the child elements. I attach the created sample.
[Test6902.zip](https://github.com/xamarin/Xamarin.Forms/files/3405570/Test6902.zip)

In my tests the Parent property is set to the StackLayout that would be the correct result.
<img width="921" alt="Captura de pantalla 2019-07-18 a las 10 35 23" src="https://user-images.githubusercontent.com/6755973/61442663-5167b000-a948-11e9-899f-f9dffd718739.png">

 Could you review the sample and modify it to reproduce the problem?

**Comment by ChaseFlorell** [comment]
I'm going to make some time this weekend to come up with a repro. Our code base is NDA and far too large to share here.

**Comment by samhouts** [comment]
@ChaseFlorell Thanks! We'll look for it.

**Comment by ChaseFlorell** [comment]
Please use internal issue #119072524003269 by @jgold6

**Comment by ChaseFlorell** [comment]
Turns out my pseudo code was too minimal. The issue is that when a custom control defines `x:Name="self"` and the page that it's being displayed on also defines `x:Name="self"`.

Then the framework picks up the incorrect control and loses track of the binding context.

**Comment by jgold6** [comment]
#119072524003269 is the support case number. I filed work item 957727 for this issue.

**Comment by samhouts** [comment]
Got it! Thanks!!
