### ISSUE TITLE
Receiver not registered PowerSaveModeBroadcastReceiver

### ISSUE THREAD

**Issue by ao1010** [xamarin/Xamarin.Forms#6903]
### Description

I am getting a rare crash in Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnPause bacuause the Power Save Mode Broadcast Receiver that is being removed is not registered.

Add defensive code when unregistering the power receiver just to make sure that the receiver is actually registered.

### Steps to Reproduce

1. Pause the app. (Very hard to reproduce as it happens rarely)

### Expected Behavior

App pauses.

### Actual Behavior

App crashes

### Basic Information

- Version with issue: XF 3.6.0.344457
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks:
  - Android: 5.1.1
- Affected Devices: Samsung Active TAB 1

### Stack trace

java.lang.IllegalArgumentException: Receiver not registered: md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver@2c1a873a
android.app.LoadedApk.forgetReceiverDispatcher()LoadedApk.java:863
android.app.ContextImpl.unregisterReceiver()ContextImpl.java:2101
android.content.ContextWrapper.unregisterReceiver()ContextWrapper.java:529
md50adca6ceff4e9e85f78601686514349c.MainActivity.n_onPause(Native Method)
md50adca6ceff4e9e85f78601686514349c.MainActivity.onPause()MainActivity.java:54
android.app.Activity.performPause()Activity.java:6764
android.app.Instrumentation.callActivityOnPause()Instrumentation.java:1338
android.app.ActivityThread.performPauseActivity()ActivityThread.java:4393
android.app.ActivityThread.performPauseActivity()ActivityThread.java:4366
android.app.ActivityThread.handlePauseActivity()ActivityThread.java:4341
android.app.ActivityThread.access$1200()ActivityThread.java:218
android.app.ActivityThread$H.handleMessage()ActivityThread.java:1729
android.os.Handler.dispatchMessage()Handler.java:102
android.os.Looper.loop()Looper.java:145
android.app.ActivityThread.main()ActivityThread.java:6914
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke()Method.java:372
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1404
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1199
Xamarin caused by: Java.Lang.IllegalArgumentException: Receiver not registered: md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver@2c1a873a
Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)<9cb01525c8ce48268eb7a54e1b653d67>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<9cb01525c8ce48268eb7a54e1b653d67>:0
Android.Content.ContextWrapper.UnregisterReceiver(BroadcastReceiver receiver)<83e36ed05052486983583851de96589e>:0
Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnPause()<e6fe81c4055a4db5bd435b7d12d894e3>:0
CMS.Mobile.Droid.MainActivity.OnPause()<300088f2ef204a8b9c0414e96bfdc0d6>:0
Android.App.Activity.n_OnPause(IntPtr jnienv, IntPtr native__this)<83e36ed05052486983583851de96589e>:0
at (wrapper dynamic-method) System.Object.19(intptr,intptr)
--- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: Receiver not registered: md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver@2c1a873a
android.app.LoadedApk.forgetReceiverDispatcher()LoadedApk.java:863
android.app.ContextImpl.unregisterReceiver()ContextImpl.java:2101
android.content.ContextWrapper.unregisterReceiver()ContextWrapper.java:529
md50adca6ceff4e9e85f78601686514349c.MainActivity.n_onPause(Native Method)
md50adca6ceff4e9e85f78601686514349c.MainActivity.onPause()MainActivity.java:54
android.app.Activity.performPause()Activity.java:6764
android.app.Instrumentation.callActivityOnPause()Instrumentation.java:1338
android.app.ActivityThread.performPauseActivity()ActivityThread.java:4393
android.app.ActivityThread.performPauseActivity()ActivityThread.java:4366
android.app.ActivityThread.handlePauseActivity()ActivityThread.java:4341
android.app.ActivityThread.access$1200()ActivityThread.java:218
android.app.ActivityThread$H.handleMessage()ActivityThread.java:1729
android.os.Handler.dispatchMessage()Handler.java:102
android.os.Looper.loop()Looper.java:145
android.app.ActivityThread.main()ActivityThread.java:6914
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke()Method.java:372
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:1404
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:1199

**Comment by samhouts** [comment]
@ao1010 I understand that this is hard to reproduce, but do you have any idea what your app is doing that might be triggering this? Animations? Messaging? Anything? A sample project would be very helpful. Thanks!

**Comment by ao1010** [comment]
I have no idea what is occurring at the time, it is only happening once or twice a week in a released product so I only see the crash logs on Hockey App.

Looking at the Xamarin code that is crashing I believe some defensive coding could be added to prevent the app from crashing.

**Comment by PureWeen** [comment]
@ao1010 I could see us adding some defensive code

In your app are you doing anything special with the activity? Or is your *CMS.Mobile.Droid.MainActivity*  fairly default?

**Comment by kvpt** [comment]
This kind of issue is not always related to race condition, it can be the case here but it's not sure.
I have fixed a bug in one of my app where the wrong context was used, so the Unregister was called with another Context that the Register and so the Receiver was not registered on **this** `Context`.
In that case I have to use the Context from the Application and not the Context from the Activity, it can be the same here too.

**Comment by ao1010** [comment]
It could be a race condition, I am enabling NFC foreground dispatching which does cause a Pause and Resume to be called one after another each time a card is tapped on the NFC reader.


        protected override void OnResume()
        {
            base.OnResume();

            if (_nfcAdapter != null)
            {
                var intent = new Intent(this, GetType()).AddFlags(ActivityFlags.SingleTop);

                intent.PutExtra("IsForeground", true);

                _nfcAdapter.EnableForegroundDispatch
                (
                    this,
                    PendingIntent.GetActivity(this, 0, intent, 0),
                    new[] { new IntentFilter(NfcAdapter.ActionTechDiscovered), new IntentFilter(NfcAdapter.ActionTagDiscovered), new IntentFilter(NfcAdapter.ActionNdefDiscovered) },
                    new String[][] { new string[] { NFCTechs.Ndef }, new string[] { NFCTechs.MifareUltralight }, new string[] { NFCTechs.MifareClassic } }
                );
            }
        }

        protected override void OnPause()
        {
            base.OnPause();

            if (_nfcAdapter != null)
            {
                _nfcAdapter.DisableForegroundDispatch(this);
            }
        }

**Comment by gohulutech** [comment]
@ao1010 I'm having the same issue when the app enters a paused state. I can reproduce it by requesting the permissions for location. When the message is shown the app enters in the paused state and crashes. I tried adding a try/catch block in the method but the popup message for the location gets closed. Did you figure out why that was happening??

Java.Lang.IllegalArgumentException: Receiver not registered: md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver@a6561fa
  at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <a28ef992ef1c47dba4efa3bd75e0a265>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <a28ef992ef1c47dba4efa3bd75e0a265>:0 
  at Android.Content.ContextWrapper.UnregisterReceiver (Android.Content.BroadcastReceiver receiver) [0x00027] in /Users/builder/jenkins/workspace/xamarin-android-commercial/xamarin-android/src/Mono.Android/obj/Release/android-28/mcw/Android.Content.ContextWrapper.cs:3580 
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnPause () [0x0002c] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:242 
  at ClickClinician.Mobile.Droid.MainActivity.OnPause () [0x00002] in /Users/macbookair/Documents/CC/Mobile/ClickClinician_Mobile/ClickClinician.Mobile/ClickClinician.Mobile.Android/MainActivity.cs:78 
  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: Receiver not registered: md51558244f76c53b6aeda52c8a337f2c37.PowerSaveModeBroadcastReceiver@a6561fa
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1202)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1464)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
	at md564cb6e72e0a5c1a13842ee3c4e3030c9.MainActivity.n_onPause(Native Method)
	at md564cb6e72e0a5c1a13842ee3c4e3030c9.MainActivity.onPause(MainActivity.java:60)
	at android.app.Activity.performPause(Activity.java:7176)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1430)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3998)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3975)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3949)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3923)
	at android.app.ActivityThread.-wrap15(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6626)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by jonathanantoine** [comment]
I have the same issue, it looks related to this line : https://github.com/xamarin/Xamarin.Forms/blob/413eb2347a7b0ff9340e59474c2343b21528056d/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L304

**Comment by jfversluis** [comment]
@gohulutech sorry it took a while, but would you be able to put together a small project that shows it? I'm having some trouble reproducing it. I think I have a fix for it, but it would be great if I could verify that and not guess :)

**Comment by jfversluis** [comment]
The PR I had in mind to fix this has been merged into 4.3. If any or all of you could report if this is any better in the upcoming 4.3 or 4.4-pre version I would be very grateful! Thanks!

**Comment by samhouts** [comment]
closed by #8324
