### ISSUE TITLE
[Bug] XAML parser cannot parse nested markup extension as positional argument

### ISSUE THREAD

**Issue by akihikodaki** [xamarin/Xamarin.Forms#6905]
### Description
[MS-XAML-2009] page 80 and 81 says nested markup extension as positional argument should be evaluated. A fix is available at https://github.com/akihikodaki/Xamarin.Forms/commit/ab77b092d52bcf8c5081fb8aacb2a066bd201312, but depends on #5186, which is not merged yet.

### Steps to Reproduce

Run the test included in https://github.com/akihikodaki/Xamarin.Forms/commit/ab77b092d52bcf8c5081fb8aacb2a066bd201312.

### Expected Behavior

Example:

```
{N {M}}
```

According to the specification, `{M}` should be evaluated first, and the result should be passed to markup extension `N` as positional argument, which will be set or added to the content property of `N`.

### Actual Behavior

Xamarin.Forms passes literal string `M` to markup extension `N`.

### Basic Information

- Version with issue: 4.0.0 Service Release 3
- Last known good version: None
- IDE: Any
- Platform Target Frameworks: 
  - iOS:  Any 
  - Android: Any  
  - UWP:  Any  
- Android Support Library Version: Any 
- Nuget Packages: None
- Affected Devices: Any

### Screenshots

N/A

### Reproduction Link

https://github.com/akihikodaki/Xamarin.Forms/commit/ab77b092d52bcf8c5081fb8aacb2a066bd201312

**Comment by StephaneDelcroix** [comment]
I remember having a discussion about this a few weeks ago, we probably have a bug open for that
