### ISSUE TITLE
[Bug] iOS - ObservableCollection clear with CollectionView

### ISSUE THREAD

**Issue by MarMarIV** [xamarin/Xamarin.Forms#6906]
### Description
iOS - Clear ObservableCollection cause Exception
### Steps to Reproduce

    class VM<TEntity> : BaseVM {
        public ObservableCollection<TEntity> Data { get; }

        public VM()
        {
            Data = new ObservableCollection<TEntity>();
        }

        public void AddData(IEnumerable<TEntity> data) {
            Device.BeginInvokeOnMainThread(() => {
                                               Data.Clear();

                                               foreach (TEntity entity in data)
                                               {
                                                   Data.Add(entity);
                                               }
                                           });
        }
    }

### Actual Behavior
`Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (1) must be equal to the number of items contained in that section before the update (1), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).
Native stack trace:
	0   CoreFoundation                      0x00000001cf9a9294 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001ceb839f8 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001cf8c2988 <redacted> + 0
	3   Foundation                          0x00000001d0386188 <redacted> + 112
	4   UIKitCore                           0x00000001fbbb935c <redacted> + 12480
	5   UIKitCore                           0x00000001fbbb5f34 <redacted> + 536
	6   UIKitCore                           0x00000001fbbb5fc4 <redacted> + 68
	7   UIKit                               0x00000001efb363cc <redacted> + 48
	8   appName.iOS                       0x000000010752b240 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 47568320
	9   appName.iOS                       0x0000000106f2b378 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 41277176
	10  appName.iOS                       0x0000000107c3ce28 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 54981032
	11  appName.iOS                       0x0000000107c3c02c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 54977452
	12  appName.iOS                       0x0000000105cc73fc _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 21993340
	13  appName.iOS                       0x0000000105cc7610 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 21993872
	14  appName.iOS                       0x0000000105cc7040 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 21992384
	15  appName.iOS                       0x0000000104c6d15c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 4846812
	16  appName.iOS                       0x0000000107e73640 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 57301440
	17  appName.iOS                       0x0000000108707028 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 66294696
	18  appName.iOS                       0x0000000108709b8c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 66305804
	19  appName.iOS                       0x00000001070fa5c4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 43174212
	20  appName.iOS                       0x0000000105151968 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 9977064
	21  appName.iOS                       0x0000000108ea3d38 mono_pmip + 28996
	22  appName.iOS                       0x0000000108f48130 mono_pmip + 701756
	23  appName.iOS                       0x0000000108f4ba44 mono_pmip + 716368
	24  appName.iOS                       0x00000001047d226c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 17900
	25  appName.iOS                       0x00000001047fc678 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 190968
	26  Foundation                          0x00000001d042f894 <redacted> + 336
	27  CoreFoundation                      0x00000001cf93b018 <redacted> + 24
	28  CoreFoundation                      0x00000001cf93af98 <redacted> + 88
	29  CoreFoundation                      0x00000001cf93a880 <redacted> + 176
	30  CoreFoundation                      0x00000001cf9357bc <redacted> + 1004
	31  CoreFoundation                      0x00000001cf9350b0 CFRunLoopRunSpecific + 436
	32  GraphicsServices                    0x00000001d1b3579c GSEventRunModal + 104
	33  UIKitCore                           0x00000001fc2af978 UIApplicationMain + 212
	34  appName.iOS                       0x0000000107665dd4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 48857428
	35  appName.iOS                       0x0000000106f1864c _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 41200076
	36  appName.iOS                       0x0000000106f184d4 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 41199700
	37  appName.iOS                       0x0000000104889900 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 769152
	38  appName.iOS                       0x0000000105151968 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 9977064
	39  appName.iOS                       0x0000000108ea3d38 mono_pmip + 28996
	40  appName.iOS                       0x0000000108f48130 mono_pmip + 701756
	41  appName.iOS                       0x0000000108f4e330 mono_pmip + 726844
	42  appName.iOS                       0x0000000108e82668 _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 74140136
	43  appName.iOS                       0x0000000109041df8 xamarin_localized_string_format_9 + 27868
	44  appName.iOS                       0x00000001048897fc _ZN7plcrash2MS5async24dwarf_cfa_state_iteratorIyxE4nextEPjPNS1_28plcrash_dwarf_cfa_reg_rule_tEPy + 768892
	45  libdyld.dylib                       0x00000001cf3fa8e0 <redacted> + 4
`

### Basic Information

- Version with issue: 4.1.0.581479
- Platform Target Frameworks: 
  - iOS:  12.2

**Comment by jsuarezruiz** [comment]
@MarMarIV Could you attach a small sample to reproduce the problem?

**Comment by ArgusMagnus** [comment]
I encountered the same issue.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/6920
