### ISSUE TITLE
[UWP] xamarin.forms source code still using TargetPlatformVersion 16299

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#6909]
I've noticed that these source projects all use a very old SDK version as their target platform.
```
    <TargetPlatformVersion>10.0.16299.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
```
![image](https://user-images.githubusercontent.com/31066938/61452699-4c106280-a954-11e9-938b-53592d090fa2.png)

16299 is what, nearly 2 years old? Is this intentional or an oversight? Could it be the reason why some UWP controls are slightly broken when we use newer SDK versions in our projects?

**Comment by jsuarezruiz** [comment]
That version has been used to maintain support on some non-updated devices. Could you share more information about the  slightly broken UWP controls?

**Comment by jsuarezruiz** [comment]
Related PR: https://github.com/xamarin/Xamarin.Forms/pull/5981

**Comment by MitchBomcanhao** [comment]
The action bar at the top renders incorrectly if we use a later target sdk version. There's an issue for it here but I'm struggling to find it on my mobile.

**Comment by MitchBomcanhao** [comment]
Ah, it's issue #5661
