### ISSUE TITLE
[Bug] ShellContent ContentTemplate wrong template used

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Xamarin.Forms#6914]
### Description

I'm trying to create a page that has dynamic amount of top tabs with shell and pass data to each tab.
I modified AppShell.xaml.cs to create flyout and contents with DataTemplate to send data to view and then pass it to view model.
In view model I just assign the text property of the item to the passed value.

Could be I'm doing this the wrong way but I couldn't find anything about this online.

### Steps to Reproduce

Attached zip with solution

### Expected Behavior
We should see 3 top tabs with items matching the tab title

### Actual Behavior
First tab has items with text of second tab and after loading third tab, first tab has items from third tab.

### Basic Information

- Version with issue:  4.1.0.555618
- IDE: VS 16.2.0 Preview 4.0
- Affected Devices: Tested only on android

### Screenshots
![Screenshot_20190718-163620](https://user-images.githubusercontent.com/12157224/61466490-488fd200-a97a-11e9-8cd3-abe212768fa5.jpg)

### Reproduction Link

[XamarinBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3406994/XamarinBug.zip)

**Comment by domagojmedo** [comment]
This is still an issue in 4.2

**Comment by PureWeen** [comment]
@domagojmedo So I think there are a couple things going on here that's making it seem like it's the same template

If you simplify down the template to just bind to the _title value passed in 

```XAML

    <StackLayout>
        <Label Text="{Binding Title}"></Label>
    </StackLayout>
````
```C#

        public ItemsViewModel(string title)
        {
            Title = title;
```

You'll see they are different templates

In AppShell.xaml.cs I would instantiate the ItemsPage with a closure reference
```C#
foreach (var item in items)
            {
                var closureItem = item;
                flyoutItem.Items[0].Items.Add(new ShellContent
                {
                    Title = item,
                    ContentTemplate = new DataTemplate(() => new ItemsPage(closureItem))
                });
            }
```


In the itemsviewmodel this code here
```C#
 Items.Clear();
                var items = await DataStore.GetItemsAsync(true);
                foreach (var item in items)
                {
                    item.Text = _title;
                    Items.Add(item);
                }
```

Is retrieving the same instance of that data for each VM so basically the 3rd page is setting the title on all the elements that the first and second page are also using

If you create copies of the items to bind to each VM
```C#
 Items.Clear();
                var items = await DataStore.GetItemsAsync(true);
                foreach (var item in items)
                {
                    var newItem = new Item()
                    {
                         Id = item.Id,
                         Description = _title,
                         Text = _title
                    };
                    Items.Add(newItem);
                }
```

You'll see that you get different lists on each page
