### ISSUE TITLE
[ETA] Xamarin.Forms.Platform.WPF

### ISSUE THREAD

**Issue by LordMark88** [xamarin/Xamarin.Forms#6915]
Good afternoon, we would like to use Xamarin to develop a new cross-platform software but seems that Xamarin.Forms.Platform.WPF has few problems like not displaying items in the MasterDetailPage.

I know it's a preview, there is an ETA of when will be completed?

Thanks in advance,
Best regards

**Comment by jsuarezruiz** [comment]
The WPF backend is supported by the community and is still in Preview (there are several parts still to be implemented) https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support. But, if you have specific issues that you require, add them!. It will help to continue improving.

**Comment by samhouts** [comment]
@LordMark88 Please search for or create specific issues for anything that is not working. Thanks!
