### ISSUE TITLE
[Bug] [Shell] Top tabs OnAppearing not called with multiple tabs

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Xamarin.Forms#6916]
### Description

OnAppearing for top tabs in shell content is not called except for first tab. When load items call is moved to constructor everything works as expected

### Steps to Reproduce

Create new shell project and copy paste 
`  <ShellContent ContentTemplate="{DataTemplate local:ItemsPage}" Title="1" />`
line in AppShell.xaml

Also attached zip with solution

### Expected Behavior
We should see 3 top tabs with same items in each tab

### Actual Behavior
Only first tab has items in it

### Basic Information

- Version with issue:  4.1.0.555618
- IDE: VS 16.2.0 Preview 4.0
- Affected Devices: Tested only on android

### Reproduction Link

[XamarinBug2.zip](https://github.com/xamarin/Xamarin.Forms/files/3407069/XamarinBug2.zip)

**Comment by PureWeen** [comment]
This will be addressed in 4.2

When 4.2 pre comes out can you please test and let me know if it works for you

https://github.com/xamarin/Xamarin.Forms/pull/6527

**Comment by domagojmedo** [comment]
Will do. Is there an ETA for 4.2 pre?

**Comment by PureWeen** [comment]
It's going through the QA cycle now so as long as nothing too crazy comes up there it should be soon

**Comment by domagojmedo** [comment]
@PureWeen  Can confirm it works in 4.2 BUT

there is some weird twitch when moving to tab 2, no animation happens.
When moving from tab 2 to 3 it's animated.
When moving from tab 2 to 1 it's animated.
But when moving to tab 2 from 1 or 3 it just some weird flicker without animation.

You can reproduce it by using the attached zip and just update xamarin to 4.2
