### ISSUE TITLE
[Bug] CollectionView Horizontal Not Displaying Correctly on iOS

### ISSUE THREAD

**Issue by TheBaileyBrew** [xamarin/Xamarin.Forms#6917]
### Steps to Reproduce

1. Create a ContentPage with a CollectionView with ItemsLayout="HorizontalList"
2. Dynamically add items to the ObservableCollection
3. Attempt to scroll vertically

### Expected Behavior
On Android, the Collectionview works & animated as expected.
On iOS, the CollectionView should also display and scroll in the correct direction at first instance.

### Actual Behavior
On iOS, the CollectionView must be manipulated before the objects are displayed successfully

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual for Mac (8.1.5 - build 9)
- Platform Target Frameworks: 
  - iOS:  12.2

- Nuget Packages: Xamarin.Forms(4.1.0.581479), Xamarin.Essentials(1.2.0), Xamarin.Forms.Visual.Material(4.1.0.581479)

- Affected Devices:

### Screenshots
[Screen Recording Android v iOS](https://youtu.be/YYdspgRhhjQ)

**Comment by samhouts** [comment]
@TheBaileyBrew  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
