### ISSUE TITLE
(xamarin.forms) When resume page, labels text align is reset

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#6922]
When I come back page using Navigation.PopAsync(), labels text align is reset to HorizontalTextAlignment=&quot;Start&quot;(Resume page is same problem)

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/645655/xamarinforms-when-resume-page-labels-text-align-is.html
VSTS ticketId: 947675_
_These are the original issue comments:_

Visual Studio Feedback System on 7/16/2019, 02:54 AM (2 days ago): <markdown><p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>
</markdown>
_These are the original issue solutions:_
(no solutions)

**Comment by LeoJHarris** [comment]
I can verify we had this issue as well, with button labels aligning left on resume.

**Comment by jsuarezruiz** [comment]
I have been testing with the app suspension and with backward navigation. I have not reproduced the problem using Xamarin.Forms 4.1.

This is the sample that I used:
[Test6922.zip](https://github.com/xamarin/Xamarin.Forms/files/3410068/Test6922.zip)

Could you attach a small sample to reproduce the problem? If it can be, also information such as:
- Xamarin.Forms version used.
- Platform.
- Etc.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
