### ISSUE TITLE
[Enhancement] Xamarin.Forms.Shell allow hiding bottom tab bar and more flexible hierarchies

### ISSUE THREAD

**Issue by motoko89** [xamarin/Xamarin.Forms#6925]
## Summary
1. When users click on an item in the main page with bottom tab bar, the new page that's navigated to should be able to hide the bottom bar. Look at iOS News app
2. Please allow adding custom view below the bottom bar. e.g. ad view

**Comment by VladislavAntonyuk** [comment]
+1

**Comment by xamarindevelopervietnam** [comment]
+1

**Comment by xamarindevelopervietnam** [comment]
show/hide tab bar with animation

**Comment by rscholey** [comment]
+1

**Comment by saiyamjain143** [comment]
+1

**Comment by Hanzalah-Adalan** [comment]
+1 (show/hide with animation) please!

**Comment by MaxFmi** [comment]
Have the same issue. Only iOS

Steps to reproduce:
1) Hide TabBar on rootPage
2) navigate relative to another page where the tabBar is visble
3) Navigate back 
3.A) TabBar is visible -> bug // It works on Android but it's visable how the Tabbar is hiding when navigating back. Would be great when we wouldn't see the tabBar at all on  the first page

**Comment by vniehues** [comment]
Is there an update on this? 
The bug seems to go both ways:

When you navigate from a page with tabbar to a page where you set TabBarIsVisible=false and then go back, the tabbar re-appears but it's not taken into account layout-wise. 
Seems to only affect iOS.

**Comment by vniehues** [comment]
@todorspetkov we did not find any usable workaround so we redesigned the UI. It's really hard to use like this

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
