### ISSUE TITLE
[Enhancement] EmptyView for BindableLayout

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#6932]
## Summary

Add an EmptyView property to BindableLayout which, when set, displays if there are no other items in the layout.

This is basically a duplicate of the EmptyView feature on CollectionView.

## API Changes

In `BindableLayout`, add:

`public static readonly BindableProperty EmptyViewProperty =
BindableProperty.Create(nameof(EmptyView), typeof(object), typeof(Layout<View>), null);`

`public static readonly BindableProperty EmptyViewTemplateProperty =
BindableProperty.Create(nameof(EmptyViewTemplate), typeof(DataTemplate), typeof(Layout<View>), null);`

## Intended Use Case

In the following example, if `ItemsSource` contains any items, they will be displayed in the StackLayout and EmptyView will not be visible. If `ItemSource` contains no items, the EmptyView will be displayed as the sole element in the StackLayout.

```
<StackLayout BindableLayout.ItemsSource="{Binding ItemsSource}">
    <BindableLayout.EmptyView>
        <Label Text="No Results"/>
    </BindableLayout.EmptyView>
</StackLayout>
```

If EmptyViewTemplate is set, the template content will be displayed with EmptyView as the binding context for the template content.

If EmptyViewTemplate is _not_ set, the following rules apply:

- If the content of EmptyView is a simple string, that string is displayed as a Label. 
- If the content of EmptyView is a Forms element, that element is displayed. 
- Otherwise, the EmptyView object's `ToString(InvariantCulture)` representation is displayed as a Label.

**Comment by Eilon** [comment]
I am a Xamarin Forms user, and I approve this message.

**Comment by ChaseFlorell** [comment]
I was just coming here to ask for the same thing!

Right now we use this, and it's ugly and a pain.

```xaml
<StackLayout BindableLayout.ItemsSource="{Binding SomeList}">
    <!-- -->
</StackLayout>
<Label Text="No Results" IsVisible="{Binding SomeList, Converter={StaticResource HasValueConverter}}"
```
