### ISSUE TITLE
[Enhancement] Property Value Inheritance for Attached Bindable Properties

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#6933]
## Summary

We currently have two properties (FlowDirection and Visual) that have manual implementations of Binding Precedence via inheritance but the implementations are very manual. With Shell we have a lot of attached properties that need to propagate down through the visual/logical tree. 

The WPF documentation for Property Value Inheritance is here https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/property-value-inheritance

For the WPF implementation it's implemented only on the meta data of Attached Properties and then they will expose non attached properties as attached properties in order to tap into inheritance.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.flowdirection?view=netframework-4.8
> This property (Flow Direction) has a defined common language runtime (CLR) property accessor, so it functions as a dependency property. However, it is also registered as attached, so it can also function as an attached property. The attached registration is mainly so that property value inheritance is supported, but the property can also be used as a true attached property. 

## API Changes
```C#
class BindableProperty
{
     public bool Inherits { get; set; }
}

public static BindableProperty CreateAttached(bool inherits = false)
```
 
## Intended Use Case
When creating an Attached Property we can specify Inherits to be true which will cause the attached property to be set on all child elements in the visual/logical tree.

The precedence of this property can mirror WPF 
https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/ms743230(v=vs.100)#dependency-property-setting-precedence-list

It will take precedence over the default value specified on the meta data for the bindable property but that's it

**Comment by andreinitescu** [comment]
Why would this flag be needed? Shouldn't the property value inheritance actually work?

**Comment by mattleibow** [comment]
Just came across this limitation now. My binding context was not being propagated. And we have explicit code to do this in several types.

If this was automatic, then there will be less bugs, because `Image` only sets the property hen the binding context changes. Not when the Source changes. Not when the Source is removed. So this could be a potential memory leak as well.

**Comment by roubachof** [comment]
I have been burnt by the same issue while developing Shadows :)

**Comment by mattleibow** [comment]
Looking at WPF, it appears on the UI elements have a data context. This does solve a bunch of issues as we could directly look up parents and a UI element can never be reused.

But, then they have a different way to allow child items to get the parent's context.

**Comment by mattleibow** [comment]
I see things in WPF does a special thing for collections as well. For example, the Grid.RowDefinitions is this: https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Utility/GridContentElementCollection.tb#L600

Basically, attaching the row to the grid so data binding works. 

I am trying to get the context to pass from a view, to all the items of a collection.

**Comment by mattleibow** [comment]
So fiddling around in the WPF and Forms running apps, I spotted something interesting: WPF has a reference to the source in the actual binding: https://github.com/dotnet/wpf/blob/ae1790531c3b993b56eba8b1f0dd395a3ed7de75/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Data/BindingExpression.cs#L156

I have set up some XAML in WPF:

```xaml
<StackPanel>
    <TextBlock x:Name="first" Text="First" Height="100">
        <TextBlock.Background>
            <LinearGradientBrush>
                <LinearGradientBrush.GradientStops>
                    <GradientStopCollection>
                        <GradientStop Offset="0" Color="Red"></GradientStop>
                        <GradientStop Offset="{Binding Cool}" Color="Orange"></GradientStop>
                        <GradientStop Offset="1" Color="Yellow"></GradientStop>
                    </GradientStopCollection>
                </LinearGradientBrush.GradientStops>
            </LinearGradientBrush>
        </TextBlock.Background>
    </TextBlock>
    <Button Height="100" Background="{Binding Background, Source={x:Reference first}}" />
    <Frame x:Name="third" Height="100" DataContext="{Binding Source={x:Reference first}}" />
    <Slider Maximum="1" Minimum="0" Value="{Binding Cool}" />
</StackPanel>
```

and some C#:

```
public partial class MainWindow : Window, INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;
    private double cool = 0.5;

    public MainWindow()
    {
        InitializeComponent();
        DataContext = this;
    }

    public double Cool
    {
        get => cool;
        set
        {
            cool = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Cool)));
            GradientStopCollection stops = ((LinearGradientBrush)first.Background).GradientStops; // <- break here (A)
            third.Background = new LinearGradientBrush { GradientStops = stops };
        } // <- break here (B)
    }
}
```

When I add the break at (A), I see the `stops` object has an `InheritanceContext` of the `Window` which I set. And, the binding has an effective value of the window as well.

When I step to (B), the `InheritanceContext` context is null - which is expected since we have now changed things. But, the binding is a bit different - it has the same path as we set in the XAML, but now has a status of `PathError`. But, it still works as the actual binding still has a reference to the original source - the window.

```
(new System.Linq.SystemCore_EnumerableDebugView<System.Windows.Media.GradientStop>(stops).Items[1]).EffectiveValues[3].LocalValue
```

At (A):
```
{System.Windows.Data.BindingExpression}
    BindingGroup: null
    DataItem: {WpfApp9.MainWindow}
    HasError: false
    HasValidationError: false
    IsDirty: false
    ParentBinding: {System.Windows.Data.Binding}
    ParentBindingBase: {System.Windows.Data.Binding}
    ResolvedSource: {WpfApp9.MainWindow}
    ResolvedSourcePropertyName: "Cool"
    Status: Active
    Target: {#FFFFA500,0.5077319587628866}
    TargetProperty: {Offset}
    ValidationError: null
    ValidationErrors: null
```

At (B):

```
{System.Windows.Data.BindingExpression}
    BindingGroup: null
    DataItem: {WpfApp9.MainWindow}
    HasError: false
    HasValidationError: false
    IsDirty: false
    ParentBinding: {System.Windows.Data.Binding}
    ParentBindingBase: {System.Windows.Data.Binding}
    ResolvedSource: {WpfApp9.MainWindow}
    ResolvedSourcePropertyName: "Cool"
    Status: PathError
    Target: {#FFFFA500,0.5077319587628866}
    TargetProperty: {Offset}
    ValidationError: null
    ValidationErrors: null
```

**Comment by StephaneDelcroix** [comment]
👍

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
