### ISSUE TITLE
[Enhancement] Visual Material - ImageButton

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#6938]
## Summary
It would be nice to use Material on "ImageButton" so we get a better drop shadow and ripple effect on the button. The default one looks good, but Material looks better :)

## API Changes
Add Visual="Material" on ImageButton

## Intended Use Case
![image](https://user-images.githubusercontent.com/1676321/61567968-49863980-aa36-11e9-8744-5c27e4f98551.png)

here i was using a frame for the circle, but imagebutton works better, but misses out on the features I added in the request.

**Comment by jfversluis** [comment]
Won't be happening for Forms no more and seems Visual Material is not going to be in .NET MAUI so closing this one.
