### ISSUE TITLE
CarouselView View radomly doesnt render items properly on swiping.

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/Xamarin.Forms#6940]
Firstly want to say a big thanks to finally making CarouselView more real and usable in Xamarin Forms projects although a bug is occuring when swiping between Carousel Items causing some label/views to randonly dissapear or display weirdly. 

### Expected Behavior

Views should be displayed correctly and consisitently

### Actual Behavior

Swiping between carouselview items quickly causing views to misbehave and display unexpectly 

### Basic Information

- Version with issue: 4.2.0.608146-pre1
- Last known good version: NA
- IDE: Visual Studio 2019 Community 16.1.6
- Platform Target Frameworks:
  - iOS:  Untested
  - Android: 9.0
  - UWP:  NA
- Android Support Library Version: NA
- Nuget Packages:
- Affected Devices: Galaxy Tab A 5.1.1

### Screenshots

![ezgif com-optimize](https://user-images.githubusercontent.com/5468757/61586868-92bec080-abd1-11e9-9f60-92d32b16a23c.gif)

**Comment by jfversluis** [comment]
@LeoJHarris Thank you for the report. CarouselView is still in very early stages. We'll be sure to address this and keep you updated when we do!

**Comment by LeoJHarris** [comment]
@jfversluis great! Keep up the good work! Look forward to that ☺

**Comment by PureWeen** [comment]
@LeoJHarris can you attach a repro please?

@rmarinho are we aware of this issue yet?

**Comment by jfversluis** [comment]
We are aware of something like this. For now it seems to be an image not showing up. So anything more than that we’d like to know :)

**Comment by rmarinho** [comment]
HI @LeoJHarris can you provide a small repo of this issue? Is this only android or android and iOS? 

Thanks

**Comment by LeoJHarris** [comment]
@rmarinho possibly I can but I swapped out the XF carousel for another open source project. Oddly enough I could not replicate the issue in a sample sample project but had been encoutering the issue in another project (as per screenshot) I was working on.

When I get a chance Ill migrate back to XF carousel view to check if still causing issues in the original project.

**Comment by rmarinho** [comment]
Please reopen if you still have this issue when moving to XF carousel.
