### ISSUE TITLE
Shell.TitleView doesn't appear when specified on the Shell itself.

### ISSUE THREAD

**Issue by andriysavin** [xamarin/Xamarin.Forms#6941]
The [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/configuration#display-views-in-the-navigation-bar) state regarding `Shell.TitleView` attached property that:
> While this property can be set on a subclassed Shell object, ...

However, when I do exactly that nothing is displayed in the title. Specifying the same title view on a child content page works. Here is a sample code snipped:

```xaml
<Shell xmlns="http://xamarin.com/schemas/2014/forms"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:views="clr-namespace:ShellTitleViewBug"
       x:Class="ShellTitleViewBug.AppShell">
    <Shell.TitleView>
        <Label Text="Title View Label"
               HorizontalOptions="Center"
               VerticalOptions="Center" />
    </Shell.TitleView>
    <FlyoutItem Title="Flyout Item 1">
        <Tab Title="Tab 1">
            <ShellContent Title="Tab 1 Content">
                <views:Page1/>
            </ShellContent>
        </Tab>
    </FlyoutItem>
</Shell>
```
- IDE: VS 16.1.6
- Platform Target Frameworks: 
  - Android: 9.0 
- Xamarin.Forms 4.0 and 4.1
- Affected Devices: Emulator

Link to a sample project on OneDrive: [https://1drv.ms/u/s!AuaAKPMkiTEAxtYWoPPE9RWK6w6sLw](https://1drv.ms/u/s!AuaAKPMkiTEAxtYWoPPE9RWK6w6sLw)

Screenshots
![image](https://user-images.githubusercontent.com/12996633/61595119-e514d700-abfb-11e9-99e5-b82d6a9c6ac5.png)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/4650

**Comment by andriysavin** [comment]
@PureWeen well, even though the problem is described in that issue too, I find incorrect that it's called an "improvement" while it's obviously a bug, as the behavior doesn't much the documentation.
