### ISSUE TITLE
UI For Android Splash Screen

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#6942]
Hi,

Please add a UI in Visual Studio to create and update the static as well as [animated splash screen - #3729](https://github.com/xamarin/Xamarin.Forms/issues/3729) so developers don't need to write it manually but thay just need to select the static images, animated images or video and then Visual Studio will take care of it, just like the iOS Storyboards and Visual Assents as an example

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by PureWeen** [comment]
@jrahma that's more of a Visual Studio specific issue and not a Forms related issue.

Can you log your feedback here https://developercommunity.visualstudio.com/spaces/8/index.html. ?

or log the issue using the feedback tool inside VS
https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019
