### ISSUE TITLE
[Enhancement] Footer for Xamarin.Forms TableView

### ISSUE THREAD

**Issue by dansoutar-ptx** [xamarin/Xamarin.Forms#6943]
## Summary
As provided in Xamarin.iOS, it would be nice if there were 'footer' properties exposed with the Xamarin.Forms TableView, both on a grouping level and a table level.

## API Changes

In order to facilitate this change, a Footer property is added to the TableView class, and likewise a Footer or Description property is added to the TableCell class (or whatever the class is). These properties would be strings, since this is easier to bind with and anything else (such as a custom view or image) would almost certainly be better off in a separate view anyway. 

In xaml:

```xml
...
<TableView Intent="Settings">
  <TableSection Title="General">
    <SwitchCell Text="Some advanced setting that merits a short description"
                Footer="Short description".../>
  </TableSection>
  <!-- TableFooter could be a custom section? -->
  <TableFooter Text="{Binding AppVersion StringFormat='Copyright MyCompany Version {0}'}"/>
```
The defaults for these, predictably, would be empty strings.

## Intended Use Case

As suggested in the code example, a use-case for the former would be the ability to provide brief descriptions about a setting or multiple settings. A footer at the table level would be useful for providing any further informative text, or a natural place to put a version number or copyright (I'm guessing most app developers will run into this?).

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
