### ISSUE TITLE
Not able to work with most of repos on Github, any fix?

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#6952]
I am using VS for mac and latest stable and I am not able to compile and run project from github.

for example If I run RoxXamarinVideo and ExoPlayerXamarin in latest VS for mac both are failed.

Is there any solution regarding this or I am missing something here. Since I don't have other windows machine I can't confirm it's working on Windows or not.

Anyone have solution on this.

**Comment by StephaneDelcroix** [comment]
this looks like a VSMac issue, I do't see what we can do here...

**Comment by anirugu** [comment]
What is the sollution for these kind of issue, I am not able to use VS for mac for running project like these on Github.
