### ISSUE TITLE
Add property IsReadOnly to Switch control

### ISSUE THREAD

**Issue by PetrVobornik** [xamarin/Xamarin.Forms#6953]
Please add property IsReadOnly to Switch control

**Comment by andreinitescu** [comment]
Umm, IsEnabled doesn't work for you?

**Comment by PetrVobornik** [comment]
Yes, IsEnabled works fine, but when the Switch control is disabled, its design (colors) is changed.

**Comment by andreinitescu** [comment]
Maybe set IsInputTransparent=false?

But in my opinion, it looks weird to see a control which it looks like it's enabled, but it really isn't. There's a reason why disabled has a different look, to tell use the control doesn't accept input. An Entry is different, because entry has also a text input mode, and the IsReadOnly is meant to control that.

**Comment by PetrVobornik** [comment]
InputTransparent is good for touch environment, but in UWP I can focus the Switch by Tab key and switch it by pressing Space key.

In my settings form I need to distinguish when the whole settings is locked (I inform a user by an color information panel on the top) and when some controls are unavailable (disabled) because some other setting is switched off. For example I switch off "limit range" and the controls "form" and "to" are disabled. This enabled/disabled state is usefull in both states of settings form - locked and unlocked too.

**Comment by andreinitescu** [comment]
In addition to InputTransparent=false, maybe also catch the `GotFocus` event and if you know it shouldn't take input, move focus to another element. 

I don't think I understand exactly your scenario, but from an UX perspective, I still think that having a control which looks enabled but it really isn't, is not a good idea. My suggestion is to always use IsEnabled and for the "locked"/"not available" scenario, either also have a descriptive label or an overlay icon (a "lock" maybe?) over the disabled Switch. I think it would work much better.

**Comment by andreinitescu** [comment]
Also, another option to mimic the "readonly" state is you could try to switch back to enabled/disabled state

**Comment by PetrVobornik** [comment]
I cannot change the status back after switching because Switch has no "OnToggling" event. Only OnPropertyChanged is there, but there it cannot be changed because the visual change of the state of the item has not yet been completed and the change process is looping.
Transparent overlay is not effective for when the keyboard is connected because user can change focus by the Tab key.
I can capture GotFocus and set it to another element, but it can also be read-only and it also changes the behavior of the element itself. 
The IsReadOnly property, that each platform certainly has, would be the most elegant solution also for other usage scenarios.
To illustrate, I attach a screen of the settings form. But it's still not completed.

![BasicNumberSettings](https://user-images.githubusercontent.com/11021768/61715614-bf074800-ad5d-11e9-967e-786bf97659b2.png)

**Comment by andreinitescu** [comment]
> I can capture GotFocus and set it to another element, but it can also be read-only and it also changes the behavior of the element itself.

If none of the quick options work, you can just create your own renderer for Switch which overrides native look when control is disabled.

> The IsReadOnly property, that each platform certainly has

Not sure, what's the native equivalent of the property for UISwitch on iOS and SwitchCompat on Android?

Regarding your screenshot, why not display an overlay over the whole form and have the password text-box on top?

**Comment by PetrVobornik** [comment]
Yes, both is possible, but not clean. IsReadOnly is a basic feature which every editor should have.

**Comment by hartez** [comment]
> Yes, IsEnabled works fine, but when the Switch control is disabled, its design (colors) is changed.

You can change the colors for the disabled state with the Visual State Manager.

**Comment by PetrVobornik** [comment]
> You can change the colors for the disabled state with the Visual State Manager.

Yes, but sometimes I need to disable Switch with this color effect. And I not to want specify these colors absolutely, I prefer native colors.

**Comment by andreinitescu** [comment]
> I prefer native colors.

That's why I suggested you to use a renderer.

> I cannot change the status back after switching because Switch has no "OnToggling" event. Only OnPropertyChanged is there, but there it cannot be changed because the visual change of the state of the item has not yet been completed and the change process is looping.

There's the `Switch.Toggled` event. Why not just toggle back on the event handler? In your logic ignore the toggle changes when you know the password has not been entered and validated.

**Comment by PetrVobornik** [comment]
Render must be solved for each platform, I prefer to use only universal code.

If I add this code, the app freezes on binding
`void Switch_Toggled(object sender, ToggledEventArgs e) => IsToggled = !e.Value;`

I'm used to HTML, Delphi, Windows Forms, WPF etc. that each control has this property.

**Comment by andreinitescu** [comment]
> void Switch_Toggled(object sender, ToggledEventArgs e) => IsToggled = !e.Value;

Because you're recursively toggling it between the states :)

> I'm used to HTML, Delphi, Windows Forms, WPF etc. that each control has this property.

In both Windows Forms and WPF, the equivalent of the Switch is the CheckBox. CheckBox doesn't have a read-only property.

**Comment by PetrVobornik** [comment]
> void Switch_Toggled(object sender, ToggledEventArgs e) => IsToggled = !e.Value;
> Because you're recursively toggling it between the states :)

I know, that's your idea. But when I add this, it behaves the same way:

    bool internalChange = false;
    void Switch_Toggled(object sender, ToggledEventArgs e)
    {
        if (internalChange) return;
        internalChange = true;
        IsToggled = !e.Value;
        internalChange = false;
    }

> In both Windows Forms and WPF, the equivalent of the Switch is the CheckBox. CheckBox doesn't have a read-only property. In HTML, the readonly is equivalent to InputTransparent, but, as you mentioned, it's only meant to disable only touch. I can't comment on Delphi.

You're right, I'm sorry. Base component CheckBox has no ReadOnly property. I was using DevExpress components, where every editors including CheckBox and ToggleSwitch has IsReadOnly property from common parent BaseEdit.
In HTML an input check can be read-only standardly. In our web framework we create a toggle control which support it too. 
Standard features in many information systems is "Open record detail for read-only". And disabled style is not nice. Sometimes the form open type is also controlled based on permissions.

**Comment by GreenKn1ght** [comment]
I believe InputTransparent=true should set [IsTabStop](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.control.istabstop) for UWP and [IsTabStop](https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.controls.control.istabstop) for WPF to false out of the box.

**Comment by PetrVobornik** [comment]
> I believe InputTransparent=true should set IsTabStop for UWP and IsTabStop for WPF to false out of the box.

Unfortunately no, I tried it.

**Comment by PetrVobornik** [comment]
OK, IsTabStop property is here standardly. Until IsReadOnly property on Switch class will be officially, I can use this code:

    class SwitchRO : Switch
    {
        private bool isReadonly = false;
        public bool IsReadonly
        {
            get => isReadonly;
            set {
                isReadonly = value;
                InputTransparent = isReadonly;
                IsTabStop = !isReadonly;
                OnPropertyChanged(nameof(IsReadonly));
            }
        }
    }

**Comment by PetrVobornik** [comment]
And this code, if I need it as bindable property.

    class SwitchRO : Switch
    {

        public static BindableProperty IsReadOnlyProperty =
            BindableProperty.Create(nameof(IsReadOnly), typeof(bool), typeof(SwitchRO), false,
            defaultBindingMode: BindingMode.OneWay, propertyChanged: OnIsReadOnlyChanged);

        static void OnIsReadOnlyChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var switchRO = (SwitchRO)bindable;
            bool isReadOnly = (bool)newValue;

            switchRO.InputTransparent = isReadOnly;
            switchRO.IsTabStop = !isReadOnly;
        }

        public bool IsReadOnly
        {
            set { SetValue(IsReadOnlyProperty, value); }
            get { return (bool)GetValue(IsReadOnlyProperty); }
        }
    }

**Comment by PureWeen** [comment]
I can see the arguments for adding this though I don't know if it'll be high priority so I'm going to mark it up for grabs.

It looks like this is the easiest implementation as far as UWP is concerned

https://stackoverflow.com/a/2548913

**Comment by hartez** [comment]
After some discussion, the team has decided not to take on the additional maintenance and testing burden of this property. Aside from appearance, the IsReadOnly property is functionally identical to IsEnabled for the Switch. Some folks have suggested that they want the visual appearance of an enabled Switch while not actually allowing users to interact with it; we believe this is a niche use case and will not be supporting it. 

For folks who want this niche use case, there are several options:

- Create a custom renderer
- Set `IsEnabled` to `false` and customize the colors for the disabled state using the VSM
- Set `InputTransparent` to `true` and `IsTabStop` to `false`
