### ISSUE TITLE
[UWP] ListView.GroupHeaderTemplate applies a different FontSize on Label

### ISSUE THREAD

**Issue by Maxgamerboy1** [xamarin/Xamarin.Forms#6956]
### Description
When setting up a ListView with a custom GroupHeaderTemplate, and using the same template to define the ItemSourceTemplate, it produces some strange results when you haven't explicitly set a FontSize.

### Steps to Reproduce

1. Create a standard XF App
2. Add the following code into your MainPage...
```XAML
<ListView IsGroupingEnabled="True">
     <ListView.GroupHeaderTemplate>
         <DataTemplate>
               <ViewCell>
                   <Label Text="{Binding Header}" />
              </ViewCell>
         </DataTemplate>
    </ListView.GroupHeaderTemplate>
    <ListView.ItemTemplate>
        <DataTemplate>
             <ViewCell>
                 <Label Text="{Binding .}" />
             </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
3. Setup the ItemSource to be a list compatible with Grouping (e.g, as follows...)

``` C#
public class TempObj : List<string> {
    public TempObj(IEnumerable<string> content) : base(content) { }
    public string Header { get; set; }
}
```

```Xaml
<ListView.ItemsSource>
      <x:Array Type="{x:Type testapp:TestObj}">
               <testapp:TestObj>
                       <testapp:TestObj.Header>
                              <x:String>Header 1</x:String>
                       </testapp:TestObj.Header>
                       <x:Arguments>
                             <x:Array Type="{x:Type x:String}">
                                    <x:String>Content 1</x:String>
                                    <x:String>Content 2</x:String>
                                    <x:String>Content 3</x:String>
                               </x:Array>
                       </x:Arguments>
                </testapp:TestObj>
```

(sorry for poor formatting)

### Expected Behavior
FontSizes to be the same, as in the Android and iOS deployments.

### Actual Behavior
The FontSize of the GroupHeader's Label becomes larger than the ItemSource's Label

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version: n/a
- IDE: Visual Studio 2019 Enterprise 16.1.6
- Platform Target Frameworks: 
  - iOS: 12.10 
  - Android: 9.0.3  
  - UWP: 16299  
- Android Support Library Version: n/a 
- Nuget Packages: n/a
- Affected Devices: Windows 10 Devices

### Screenshots
![image](https://user-images.githubusercontent.com/25750702/61714073-e35d2780-ad51-11e9-82fa-b0cbacd77314.png)

**Comment by PureWeen** [comment]
@Maxgamerboy1 this is by design. The default style applied to the header on the list view has a larger font so that they are more pronounced. If you want them to have the same fontsize then you'll need to set the font yourself or use named styles https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/styles

**Comment by Maxgamerboy1** [comment]
You mention there's a default style that is applied, is it possible to override this?
