### ISSUE TITLE
[Bug] Device.StartTimer() won't fire on WPF if it is executed on Non UI thread

### ISSUE THREAD

**Issue by maxim-saplin** [xamarin/Xamarin.Forms#6957]
### Description
Device.StartTimer() won't fire the callback on WPF if it is executed on Non UI thread.

### Steps to Reproduce

1. In App.xaml.cs do Task.Run() and set up timer inside it (do it after MainPage is set)
2. Put breakpoint in timer callback
3. Run the app

### Expected Behavior

Callback gets called

### Actual Behavior

Callback isn't called

### Basic Information

- Version with issue: XF 4.1
- IDE: VS2019
- Platform Target Frameworks: .NET Framework 4.7.x, WPF

At _Xamarin.Forms/Xamarin.Forms.Platform.WPF/WPFPlatformServices.cs_ there's _public bool IsInvokeRequired_ but it doesn't seem to be used anywhere, including _public void StartTimer(TimeSpan interval, Func<bool> callback)_.

Workaround:

```
if (Device.RuntimePlatform == Device.WPF) 
  Device.BeginInvokeOnMainThread( () => Device.StartTimer(new TimeSpan(0, 0, 0, 0, refreshPeriodMs), callback));
```

**Comment by krdmllr** [comment]
Fixed it in #7958, you can find a good description of the problem here: https://stackoverflow.com/a/8423977 by @kentcb
