### ISSUE TITLE
[Bug] CollectionView multiple pre-selection throws ArgumentOutOfRangeException when SelectedItems is bound to an ObservableCollection initialized inside the constructor.

### ISSUE THREAD

**Issue by balazserd** [xamarin/Xamarin.Forms#6963]
### Description

Using the application that can be downloaded [here](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos/) (and is also linked [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/selection#multiple-pre-selection), on the official CollectionView documentation page)

When creating the ObservableCollection for the SelectedItems property via the 

`ObservableCollection<T>(IEnumerable<T> items)`

constructor, an error is shown when trying to bound the data to the CollectionView's SelectedItems property.

### Steps to Reproduce

Change the implementation of the constructor in ViewModels/MonkeysViewModel.cs from this: 

```
        public MonkeysViewModel()
        {
            source = new List<Monkey>();
            CreateMonkeyCollection();

            selectedMonkey = Monkeys.Skip(3).FirstOrDefault();
            MonkeySelectionChanged();

            SelectedMonkeys = new ObservableCollection<object>()
            {
                Monkeys[1], Monkeys[3], Monkeys[4]
            };
        }
```

to this:

```
        public MonkeysViewModel()
        {
            source = new List<Monkey>();
            CreateMonkeyCollection();

            selectedMonkey = Monkeys.Skip(3).FirstOrDefault();
            MonkeySelectionChanged();
            
            var monkeys = Monkeys.Select(m => new Monkey()
            {
                Details = m.Details,
                ImageUrl = m.ImageUrl,
                Location = m.Location,
                Name = m.Name
            });

            SelectedMonkeys = new ObservableCollection<object>(monkeys);
        }
```

### Expected Behavior

- Anything that matches in the list of SelectedMonkeys should highlight and anything that doesn't matches should effectively do nothing.
- Ordering should also be tested. If SelectedItems is set first and ItemSource second then it should select the items in SelectedItems. 

### Actual Behavior

ArgumentOutOfRangeException is thrown for an index property (VS for Mac throws errors on the Main function, so no idea where the issue is...)

### Basic Information

- Version with issue: latest public as of today (4.1.0)
- Last known good version: no idea.
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: no Android project
  - UWP:  no UWP project
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: device-independent issue, tried on multiple ones (from iPhone SE to iPad Pro).

**Comment by PureWeen** [comment]
@balazserd you're instantiating new monkeys 
```C#
            var monkeys = Monkeys.Select(m => new Monkey()
            {
                Details = m.Details,
                ImageUrl = m.ImageUrl,
                Location = m.Location,
                Name = m.Name
            });

            SelectedMonkeys = new ObservableCollection<object>(monkeys);
```

So it's not going to be able to associated your new list of monkeys with the monkey's bound to the ItemSource. You would need to select the Monkeys you want selected out of this list *Monkeys* or you could override GetEquals/GetHashCode on the monkey so that the system can know what it means for one monkey to equal another monkey

I'm checking what the expected behavior should be if you assign wrong items to SelectedItems though

**Comment by PureWeen** [comment]
@balazserd I updated the ticket with the desired behavior. The crash is not desired but the effect you should see is that nothing is selected

**Comment by balazserd** [comment]
Alright, thank you for the help and clarification. Good luck with fixing the real issue! :)

**Comment by adrianknight89** [comment]
@PureWeen Isn't it better to throw an exception instead of ignoring those new items that are not part of `ItemsSource`? I'd rather see an exception and fix the issue than try to figure out why the items are not showing up. I'm not sure what the exception says, but we can give a descriptive message.
