### ISSUE TITLE
Release Build crashes for stylesheet embedded resource: System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by crobarian** [xamarin/Xamarin.Forms#6974]
I have an embedded resource styles.css file in my .NET Standard project with the Build Action as Embedded resource and App.xaml code same as in MonkeyAppCSS sample code

When run UWP in Debug Configuration, works fine. When run in Release Configuration, crashes with "System.NullReferenceException: 'Object reference not set to an instance of an object.'" on:

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "0.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(App));
        }

### Steps to Reproduce

1. Download the MonkeyApp CSS sample code from https://developer.xamarin.com/samples/xamarin-forms/UserInterface/Styles/MonkeyAppCSS/ 
2. Open the solution and go to Manage NuGet Packages for the Solution and upgrade all Xamarin.Forms to any 4.1 version
3. Change Configuration from Debug to Release
4. Run the UWP project on a Local Machine and crashes on App.xaml.g.cs InitializeComponent

### Expected Behavior

UWP program should run normal

### Actual Behavior

Crashes on App.xaml.g.cs InitializeComponent

### Basic Information

- Version with issue:
- Last known good version: 4.0.0.618606
- IDE: Visual Studio 2019 Enterprise
- Platform Target Frameworks: 
  - iOS:  latest
  - Android: latest
  - UWP:  latest
- Nuget Packages:
- Affected Devices:
UWP, haven't tested on Android or iOS

**Comment by PureWeen** [comment]
@StephaneDelcroix  thoughts?

I know we've been changing some things with this code and HR

It looks like it's crashing on this line
https://github.com/xamarin/Xamarin.Forms/blob/577bc7b06f4eec3b4a78453c8d7efb743e26959e/Xamarin.Forms.Core/StyleSheets/StyleSheet.cs#L38

when trying to retrieve the style.css file so it looks like UWP is linking it out with release builds

**Comment by StephaneDelcroix** [comment]
so, the DependencyService returns null in release mode ?

**Comment by StephaneDelcroix** [comment]
I have a fix, about to send a PR. 

the workaround is to pass Xamarin.Forms.Xaml as extra assembly at Init() time
