### ISSUE TITLE
Label's Text doesn't update after changing value bound from DataTable collection

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#6975]
### Description
Greetings,

I am from Syncfusion. I am facing a highly notable issue while working with DataTable collections. My actual project is quite complicated, so I have replicated my issue in a very simple sample. I have a DataTable collection with 3 rows and 3 columns. I have a label element whose **BindingContext** is the first row from the DataTable. I have bound the value of 1st row's 2nd column to Label's **Text** property. 

Initially when view loaded everything works fine and the text value is obtained as expected. But while changing the value for the DataTable's 1st row's 2nd column object value, the text value doesn't get updated. Though the BindingContext for the Label has been altered appropriately. 

Can you please confirm whether this is the actual behavior or known issue at your end as soon as possible?
If possible, can you please provide us with any workaround to achieve our requirement as this has been a major lump for further development process?
 
### Steps to Reproduce

1. Run the attached sample.
2. Press the 'Click me' button.
3. See the BindingContext and Text value in the DisplayAlert box.

### Expected Behavior
The label's text value should be 'Seanopie' instead of 'Sean' after changing the table value.

### Actual Behavior
The label's text value remains 'Sean' after changing the table value.

### Basic Information

- Version with issue: Checked with v3.4 and above
- Last known good version: None
- Nuget Packages:XForms v3.4.0.1008975

### Reproduction Link

[DataTableIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3431520/DataTableIssue.zip)

**Comment by PureWeen** [comment]
@Muthukumaran-G how do the property changed notifications get raised for these structures?

I checked this
```C#
viewModel.Records.Rows[0] as INotifyPropertyChanged
```

But it doesn't Implement that interface

so when you are doing this
```C#
viewModel.Records.Rows[0]["Column2"] = "Seanopie";
```

What property notification is being triggered that is alerting the Label that it should update that property?

**Comment by Muthukumaran-G** [comment]
Hi @PureWeen ,

I haven't got any notification for change in Label's text value, though I have checked by hooking the RowChanged event as below in the attached sample.
`viewModel.Records.RowChanged += Records_RowChanged;
`
This RowChanged event triggers as expected when changing the row data. So when the row value is changed, label value should also be changed. 

Is there any options available to trigger the change in Label's text value?

**Comment by PureWeen** [comment]
@Muthukumaran-G 

> This RowChanged event triggers as expected when changing the row data. So when the row value is changed, label value should also be changed.

Why should the RowChanged event cause the Label to update? The label doesn't know anything about the row changed events that your code is generating.


In order for the label to know it needs to be updated the BindingContext needs to implement INotifyProperty changed. Otherwise you'll need trigger the update to the label yourself from RowChanged or do something like wrap the binding context

new PropertyChangedProxy(viewModel.Records.Rows[0])

class PropertyChangedProxy : INotifyPropertyChanged

and then fire a property changed notification on PropertyChangedProxy

**Comment by Muthukumaran-G** [comment]
@PureWeen ,

Almost lost hope in achieving the requirement. I would like to confirm that the BindingContext has been changed without any wrapping or INotifyPropertyChanged implemented after changing the model data. Although I have tried the above approaches but still the solution goes in vain. The only thing I can do right now is updating the text value by rebinding after BindingContext changed or directly setting the altered value to label's text. But this collapses the concept of binding. So can I conclude that it is not possible to bind the data table value to label's text?

If you have any alternative solution, can you please share with a simple sample?

Thanks :)

**Comment by PureWeen** [comment]
> So can I conclude that it is not possible to bind the data table value to label's text?

I don't understand this conclusion? You're binding the data table to the text but the value isn't updating because there isn't an INotifyPropertyChanged event firing that the BindableProperty can watch to know when the value changes. So the binding is working fine and shows up the first time.

**Comment by Muthukumaran-G** [comment]
@PureWeen ,  I need to use the DataTable collection directly without converting into ObservableCollection. Since the DataTable Rows doesn't implement any INotifyPropertyChanged, it is of no use to have a BindableProperty as it doesn't observe the PropertyChanging at runtime. So converting DataTable collection into ObservableCollection doesn't help to achieve my requirement.
