### ISSUE TITLE
[Android] Span gesture recognizer is not triggered when Label has padding

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#6992]
#6299 added `Padding` property to `Label`. If we add padding to a label and a span with its own gesture recognizer, Android cannot recognize taps when the user taps below the label text. Tapping above the label text seems to work (but only if you tap at the very top of the label's region as big as the height of the span). See repro. Not sure if this should be considered an enhancement or a bug. This issue was also mentioned in #6299.

The fix for this should make sure that **multiple spans** with a separate gesture recognizer for each work when label padding is present. The issue here is probably the same as an inaccuracy described in #4143. Regardless, the fix must be tested with label padding, hence the repro for testing purposes.

![Untitled](https://user-images.githubusercontent.com/16855542/61999150-bf1a8700-b080-11e9-8649-9970138b954e.png)

[App11.zip](https://github.com/xamarin/Xamarin.Forms/files/3438355/App11.zip)

**Comment by samhouts** [comment]
Hmm. I'll call it a bug.
