### ISSUE TITLE
Hamburger Icon on MasterDetail Xamarin Forms (Android) [Bug] 

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#6997]
### Description
I have an XF3.6 Application (I am working on Android project). I have a Master Detail Page with Navigation on Detail page.
I have set 			

`NavigationPage.SetHasBackButton(this, false);` on all pages.

With XF3.6 I have the root page with the hamburger menu and the second page only with the title (no hamburger menu, no back arrow)

With XF4.1 I have the root page with the hamburger menu and the second page with the hamburger menu

### Steps to Reproduce

1. Create a XF project with a MasterDetail
2.  Add To the DetailPage a NavigationPage
3. Add another page to the NavigationStack

### Expected Behavior
Not to have the hamburger menu on the second page
### Actual Behavior
I have the hamburger menu on the second page

### Basic Information

- Version with issue:
- Last known good version: XF3.6.0.539721 
- IDE: Visual Studio 2019 16.1.6
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Zebra TC51

### Screenshots

XF3.6.0.539721
The root page
![image](https://user-images.githubusercontent.com/5759350/62004881-3d336800-b12b-11e9-8350-9a338710b651.png)
The second page
![image](https://user-images.githubusercontent.com/5759350/62004864-ea59b080-b12a-11e9-8325-3d1e32fd2686.png)

XF4.1
The root page
![image](https://user-images.githubusercontent.com/5759350/62004919-d82c4200-b12b-11e9-9841-ce0664c61e32.png)

The second page
![image](https://user-images.githubusercontent.com/5759350/62004921-e24e4080-b12b-11e9-85ae-4af2672d3bca.png)

**Comment by jfversluis** [comment]
This is probably due to #2577. There has been a feature request at #6971 for a similar scenario. Could you please check if this is also you issue? If it is, for overview I think it’s best to close this one and keep your eye on #6971. Thanks!

**Comment by acaliaro** [comment]
Hi @jfversluis. I think it is something like https://github.com/xamarin/Xamarin.Forms/pull/6548
I suppose to be in the same situation explained in https://github.com/xamarin/Xamarin.Forms/pull/6548#issuecomment-514660283

So, I wait for #6971 

Bye
