### ISSUE TITLE
how to have a feature of screen sharing between users in xamarin apps similar to vs live share

### ISSUE THREAD

**Issue by rajamaheshwarsingh** [xamarin/Xamarin.Forms#7001]
how to have a feature of screen sharing between users in xamarin apps similar to vs live share

**Comment by samhouts** [comment]
@maddyleger1

**Comment by maddyleger1** [comment]
Do you mean within an app that you build? Like, we both have your app, and we are screen sharing?

Or, do you mean, while you are writing your Xamarin app you want to use Live Share?

**Comment by wynn5a** [comment]
@maddyleger1 Hello, I want to know how to achieve the goal like what you say, users have the same app can share screen to others, in Xamarin.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
