### ISSUE TITLE
[Bug] [iOS] Code changes in XAML not picked up when building for iOS

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#7008]
## Description

Code changes made in XAML are not picked up unless the XAML file is explicitly saved before building. The changes will be picked up on the next build though.

However, if a change to C# code is made also, then both changes are picked up. 

### Steps to Reproduce

1. Create a new template Blank Xam.Forms app
2. Set the iOS app as the startup project
3. Deploy to iOS device or simulator
4. Observe "Welcome to Xamarin.Forms!" is displayed.
5. Stop app.
6. Change the text for the Label in MainPage.xaml file. **Do not save the file**.
7. Deploy the app to iOS simulator or device.

### Expected Behavior
The changed text will be displayed.

### Actual Behavior
The original text is displayed.

## Notes
As noted, if the XAML file is explicitly saved before deploying, the code change is picked up, or if a C# file in the .NET Standard project is changed, then the changes in the XAML are picked up. 

Also, if you deploy again then the code change is picked up, including any new XAML code changes.

### Basic Information

- Version with issue: 4.1.0.555.618
- Last known good version: unknown
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  12.14.0.110
- Nuget Packages: Forms and Essentials

## Full IDE version info:

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.2 (build 1105)
Installation UUID: f86726f2-bd5d-4610-867e-44e82f306ca2
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.11
	2.1.10
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
	1.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.1
	1.0.0-preview2-003121
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Enterprise)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Designer ===

Version: 16.2.0.354
Hash: 5f80a14f8
Branch: remotes/origin/d16-2
Build date: 2019-07-11 17:28:26 UTC

=== Xamarin.Android ===

Version: 9.4.0.51 (Visual Studio Enterprise)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/jongoldberger/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jongoldberger/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802001105
Git revision: a187f6852ae62ba52b944b47e53702957edfcf7b
Build date: 2019-07-22 18:20:10+00
Build branch: release-8.2
Xamarin extensions: 34bd2378d8d707df25989727c23ce68d9a232a67

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by XXcharlosXX** [comment]
Same thing happened to me the other day.
I had a button displaying on a content page, the changes I was making in XAML was not reflected after I would build.
I even decided to remove the button from XAML entirely, and ran a build. The button still displayed. I captured vide of this issue but there is not a place to upload them here.

**Comment by samhouts** [comment]
@jgold6 VSMac only?

**Comment by jgold6** [comment]
@samhouts 

I did not test VS on Windows before, but I just did and it does seem this is VS for Mac only.

**Comment by StephaneDelcroix** [comment]
@jgold6 is this iOS only ??? that seems suspicious

**Comment by jgold6** [comment]
@StephaneDelcroix  

Yes, it seems it is iOS only. The issue did not occur with the XA app.

**Comment by aocipriano** [comment]
For me it´s happening on both XAML and cs files. All changes are not applied when I run debug into a iOS simulator. It only works if I clean the project and run debug again.

**Comment by samhouts** [comment]
See also https://developercommunity.visualstudio.com/content/problem/662159/modified-xamarin-forms-app-on-debug-ios-simulator.html

**Comment by drewgillies** [comment]
Well spotted, @samhouts --this looks like a dupe, so one of these should be closed.

**Comment by samhouts** [comment]
See also https://developercommunity.visualstudio.com/content/problem/692405/start-debugging-on-ios-project-sometimes-skips-com.html.

**Comment by amirvenus** [comment]
I think it is more of a VSM issue rather than Xamarin.Forms as I have noticed the same behaviour even when targetting Xamarin.Forms.macOS.

**Comment by samhouts** [comment]
This is being tracked in the VS for Mac project. I'll close this now. Thanks!

**Comment by CodeThinkingMachine** [comment]
Any solution so far for this ??

**Comment by Luk164** [comment]
I have the same issue but I am on VS 2019 on windows.
