### ISSUE TITLE
[Spec] HoverGestureRecognizer

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#7011]
# HoverGestureRecognizer

Add a `HoverGestureRecognizer` to your `View` to capture and act when a pointer (from a supported mouse or pen/stylus) enters or exits the `View`'s visible bounds.

# API

### Properties

| API | Description |
| ------------- | ------------- |
| System.Windows.Input.ICommand Command | Gets or sets the command to run. |
| object CommandParameter | Gets or sets the command parameter. |

### Events

| API | Description |
| ------------- | ------------- |
| Hovered | Method that is called when a view is hovered. |

### Properties

| API | Description |
| ------------- | ------------- |
| HoverState State | Gets or sets the command to run. |

### enum HoverState
| API | Description |
| -- | -- |
| Began | Pointer entered the view |
| Ended | Pointed exited the view |

 
# Scenarios

```xaml

<Button Text="Hover me!">
    <Button.GestureRecognizers>
        <HoverGestureRecognizer Command="{Binding SomethingShouldHappenCommand}" Hovered="OnHovered" />
    </Button.GestureRecognizers>
</Button>

```

```csharp

public class MyViewModel 
{
    public ICommand SomethingShouldHappenCommand()
    {
        ...
    }
}

public partial class MyPage
{
    public void OnHovered(object sender, HoveredEventArgs args)
    {
        switch (args.State)
        {
            case HoverState.Began:
                ...
                break;
            case HoverState.Ended:
                ...
                break;
        }
    }
} 

```

# Backward Compatibility

Please note that iOS will not support this gesture below iOS 13. It's unlikely that a suitable shim can be developed, since virtualized hover events in iOS <13 are just clicks. 

| OS | Min Version | Ref |
| --- | --- | --- |
| Android | API 14 | https://developer.android.com/reference/android/view/View.OnHoverListener |
| iOS | iOS 13 | https://developer.apple.com/documentation/uikit/uihovergesturerecognizer |
| macOS | macOS 10.12+ | 1. https://developer.apple.com/documentation/appkit/nsevent/eventtype/mouseentered 2. https://developer.apple.com/documentation/appkit/nsevent/eventtype/mouseexited | 
| UWP |  | 1. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerentered 2. https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerexited 3. https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj819808(v=win.10)#visual-states-for-pointer-related-user-interaction| 

# Difficulty : medium

**Comment by adammeaney** [comment]
I will say that the command feels pretty useless if you don't know if it is firing On Hover Begin or End.

Are you going to just fire it both times? Clarify in the spec when the command is called or give it some way to have an OnHoveredCommand and an OnHoverFinishedCommand. 

Otherwise I would assume that people are going to use EventToCommand behavior most of the time and ignore the hover command as it will fire at times they don't want.

**Comment by Bosch-Eli-Black** [comment]
I was just looking for something like this. It sounds like it would be very useful for changing an element's background color when the user hovers over it, for example :)

**Comment by AndreiMisiukevich** [comment]
> I was just looking for something like this. It sounds like it would be very useful for changing an element's background color when the user hovers over it, for example :)

Hi :) Good news. This feature is supported by XamarinCommunityToolkit TouchEffect

https://github.com/xamarin/XamarinCommunityToolkit
