### ISSUE TITLE
ContentPage & ContentView DarkMode

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7013]
Hi,

Please add a DarkMode property to the ContentPage and ContentView which should have the following values:

1. Enabled: Always enabled
2. Disabled: Always disabled
3. Auto: Auto [might depends on device or time of the day]

It can also have DarkModeBackgroundColor and DarkModeTextColor

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by StephaneDelcroix** [comment]
Thanks for your suggestion.

I don't see us supporting this on all platforms at this time as it requires updating all the controls for all the platforms, even the one that do not supports dark mode. and then, you probably won't be happy with our defaults anyway, and you'll need a way to switch the CSS stylesheet depending on some user setting.

So I recommend that you do just that, switch the style depending on your mode.
