### ISSUE TITLE
Image GIF support

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7014]
Hi,

Please add GIF support to the Image control to display animated GIF..

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by jfversluis** [comment]
Thanks for the issue! I will close this one and mark it as a duplicate since this was already on our radar and some discussion has already happened. I invite you to join the conversation there.

**Comment by jfversluis** [comment]
Duplicate of #1704
