### ISSUE TITLE
Image Watermark / Loading

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7016]
Hi,

Please add Image Watermark / Loading to the Image control so this image will be displayed until the requested images is loaded, otherwise [NoImage](https://github.com/xamarin/Xamarin.Forms/issues/7015) will be displayed.

Watermark or LoadingImage should support normal images as well as animated GIFs.

so the Image code will look like this:

`<Image Source="{Binding student_photo]" LoadingImage="Loading.gif" NoImage="DefaultNoPhoto.png" />
`

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by StephaneDelcroix** [comment]
Thanks for your suggestion.

I'm supporting the idea of a PlaceHolder, but not the idea of a general purpose layer serving as Watermarking/Loading animation, as it's not backed by all platforms and everyone would have to pay the price of having a second image, if not used.

So, I'm closing it for now. You might want to request it again if/when we end up adding a placeholder, we might change our minds by then
