### ISSUE TITLE
[Bug] some font image of .otf file appear not right on iOS

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#7017]
[FontSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3445464/FontSample.zip)

android is fine:
![android](https://user-images.githubusercontent.com/16309962/62106723-82e16380-b2d8-11e9-8f8a-f974c4839dde.jpg)

iOS is Incomplete display :
![iOS](https://user-images.githubusercontent.com/16309962/62106739-92f94300-b2d8-11e9-9a99-955cf8efdb3f.jpg)

**Comment by jfversluis** [comment]
Thank you for reporting @jingliancui. I do see there is another issue describing this problem already. I will close this one and you can follow the progress in the other issue. Thanks!

**Comment by jfversluis** [comment]
Duplicate of #6491

**Comment by jingliancui** [comment]
@samhouts this bug still not fix in 4.2

**Comment by jfversluis** [comment]
See my comment here: https://github.com/xamarin/Xamarin.Forms/issues/6491#issuecomment-541534617
