### ISSUE TITLE
[Bug] System.NullReferenceException when ListView ItemSource is changed

### ISSUE THREAD

**Issue by PrimoDev23** [xamarin/Xamarin.Forms#7018]
### Description
While developing an app in Xamarin.Forms, i figured out this strange issue with ListViews.
I have a List (containing the LogModel) which is used as the ItemSource of this ListView and I tried to delete one LogModel inside this List.
Always when I was scrolling to the bottom of the ListView the App is crashing with a system.NullreferenceException.
This probably happens because the ItemSource isn't reloaded on the ListView, so there is one Element less than before and the ListView still tries to load that Element even if its null.
Temporary solution for this is to set the ItemSource to null, updating the List and setting the ItemSource back to the List.
### Steps to Reproduce

`public class LogModel {
public string name { get; set; }
public string address { get; set; }
}`

1. Create a List<LogModel> and a ListView
2. Set the List as ItemSource for the Listview, create a DataTemplate in it with a a grid containing 2 columns
3. Place Labels inside the columns and set their text with {Binding name} and {Binding address}
4. After tapping an Element in the ListView remove 1 Item from the LogModel-List
5. Scroll to the bottom of the page and exception will be thrown

### Expected Behavior
ListView reloads bc ItemSource was changed

### Actual Behavior
ListView throws a NullReferenceException because its accessing an not existing List-Element

### Basic Information

- Version with issue: 4.12.3.83
- Last known good version: Probably no version bc this issue exists since some years
- IDE: Visual Studio 2017 on Windows 10
- Platform Target Frameworks: 
  - Android: 9.0 (Xamarin.Forms)

**Comment by ChaseFlorell** [comment]
Your viewmodel has a property, probably called `Logs`. Is it observable?

```csharp
public ObservableCollection<LogModel> Logs { get; } = new ObservableCollection<LogModel>();
```

**Comment by StephaneDelcroix** [comment]
please attach a simple reproduction case for this issue. Thanks

**Comment by samhouts** [comment]
@PrimoDev23  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
