### ISSUE TITLE
[Bug] [Shell] iOS Bottom tab back navigation breaks re navigation

### ISSUE THREAD

**Issue by dwightbennett** [xamarin/Xamarin.Forms#7024]
### Description
When using bottom tabs in shell, if I navigate to a new page and then navigate back by using the bottom tab bar, I cannot navigate back to the page I just barely navigated from. 
### Steps to Reproduce

1. Create an app with shell and set up 2 bottom tabs.
2. Push a new page onto the navigation stack using Shell's GoToAsync call
3. Navigate back by pressing the bottom tab bar button.
4. Attempt to re-navigate back to the page.

### Expected Behavior
I am able to navigate to the page I just navigated from.
### Actual Behavior
No navigation happens.
### Basic Information

- Version with issue: Forms 4.1
- Last known good version: none that I know of
- IDE: windows and mac
- Platform Target Frameworks: Latest

### Reproduction Link
[Repro Project](https://primusstudio-my.sharepoint.com/:u:/g/personal/dwight_bennett_primusstudios_com/EaytMu8B2WBOqVZBk46C40oBvxCKX--F3ABDTXtrPrEbfg?e=rErZaV)

This project is the basic shell template when making a new shell project. I changed the navigation to the item details to using a shell route instead of using the page INavigation property.
### Extra info
The issue is seen on iOS. On android, the tab in the bottom bar does not do anything.  In my opinion it should navigate back.  This is the behavior on other android apps with bottom nav bars (Target, YouTube, Spotify).  I can make a separate issue for android if you would like me to.

**Comment by jfversluis** [comment]
Verified that this is happening.

> On android, the tab in the bottom bar does not do anything. In my opinion it should navigate back. This is the behavior on other android apps with bottom nav bars (Target, YouTube, Spotify). I can make a separate issue for android if you would like me to.

@dwightbennett if you haven't done so, please do! It's easier to track both seperately

**Comment by dwightbennett** [comment]
@jfversluis I created the android issue here #7081

**Comment by PureWeen** [comment]
If you're still seeing this on 4.5 let me know and I'll reopen

**Comment by dwightbennett** [comment]
This is fixed.  Thank you!!!
