### ISSUE TITLE
[Bug]How to convert StreamImageSource.Stream to image in Xamarin.Forms

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#7026]
I'm covert the image as stream and set to the Xamarin.Forms.Image.Source, In button click, am trying to access the same image, but in code behind am getting the image as StreamImagesSource from that I can't able to access to get the stream.

Assembly _assembly = this.GetType().Assembly;
Stream stream = _assembly.GetManifestResourceStream("DataGrithWithImagePdfExport.Resources.Jk.png");
ImageSource source = ImageSource.FromStream(() => stream);

///Added the image to the ImageSource property in Model
Persons.Add(new Person() { Name = "John Smith", Photo = source });
Please helps me to overcome this issue. 
Thanks.

**Comment by StephaneDelcroix** [comment]
what you're doing looks correct, but it's possible that your stream gets disposed.

I ran through our tests and samples, and we do this in some places

```
ImageSource.FromStream(() => typeof(App).Assembly.GetManifestResourceStream("Xamarin.Forms.Controls.coffee.png"))
```

so it should work

**Comment by BalasubramaniSundaram** [comment]
Hi @StephaneDelcroix , 
     Thanks, We have already done this solution but it doesn't work in our case. In our case, we get the image source as a bit array from the database, so the image didn't physically present in the application. In that scenario, we couldn't able to use "Xamarin.Forms.Controls" it will through exception. 
We have tried a different step to achieve a solution but everything ends up big stumbling with couldn't able to convert "ImageStream" to "ImageSource" at the back end, as we set the image source as a stream.
