### ISSUE TITLE
[Bug][iOS] CarouselView last element is clipped

### ISSUE THREAD

**Issue by XXcharlosXX** [xamarin/Xamarin.Forms#7035]
### Description
This issue seems to be iOS specific.
I have created a carouselView with a horizontal orientation.
When i try to scroll to the last element, I go as far as I can and the last element is clipped.

<img width="440" alt="Screen Shot 2019-07-31 at 3" src="https://user-images.githubusercontent.com/40214085/62251688-6bbc7780-b3a5-11e9-87cf-1aabc283605b.png">

### Steps to Reproduce

1. Create a CarouselView with Horizontal Orientation
2. Add a few elements so some elements are located off screen
3. Try scrolling to the last element

### Expected Behavior
Should see the element in full view.
<img width="489" alt="Screen Shot 2019-07-31 at 3 11 49 PM" src="https://user-images.githubusercontent.com/40214085/62251804-c35ae300-b3a5-11e9-8727-e8e2e567efd5.png">
(IT WORKS ON ANDROID) not on iOS for some reason.
### Actual Behavior
As seen in the first image, the last element is slightly **clipped.**
### Basic Information

- Version with issue: 
Xamarin.Forms 4.1.0.618606

- Last known good version:
????

- IDE: 
VS for Mac (community) 8.2.1 (build 19)

- Platform Target Frameworks: 
  - iOS: 12.0+
  - Android: 5.0+

- Affected Devices:
iOS

### Screenshots
**ABOVE**
### Reproduction Link
**Ahh, sorry I cannot provide a link to the project due to security concerns.
below is the exact code used to create the CarouselView.**

<CarouselView
    Grid.Row="3"
    Grid.ColumnSpan= "4"
    x:Name= "CV"
    HeightRequest= "225"
    HorizontalOptions= "Center"
    VerticalOptions= "CenterAndExpand"
    Margin= "0" >
    < CarouselView.ItemsLayout >
        < GridItemsLayout
            Orientation= "Horizontal"
            HorizontalItemSpacing= "15"
            SnapPointsAlignment= "Center"
            SnapPointsType= "Mandatory" />
    </ CarouselView.ItemsLayout >
    < CarouselView.ItemTemplate >
        < DataTemplate >
            < Frame
                Padding= "0"
                Margin= "0"
                HeightRequest= "200"
                WidthRequest= "300"
                BorderColor= "LightGray"
                CornerRadius= "10"
                HasShadow= "False"
                IsClippedToBounds= "True" >
                < Grid
                    ColumnSpacing= "0"
                    RowSpacing= "0" >
                    < Grid.RowDefinitions >
                        < RowDefinition Height= "70*" />
                        < RowDefinition Height= "15*" />
                        < RowDefinition Height= "15*" />
                    </ Grid.RowDefinitions >
                    < Image
                        Grid.Row= "0"
                        Aspect= "Fill"
                        Source= "{Binding ImgUrl}" />
                    < Label
                        Grid.Row= "1"
                        Margin= "20,0,0,0"
                        FontSize= "Medium"
                        Text= "{Binding SubTitle}"
                        HorizontalOptions= "Start"
                        VerticalOptions= "End" />
                    < Label
                        Grid.Row= "2"
                        Margin= "20,0,0,0"
                        FontSize= "Large"
                        Text= "{Binding Title}"
                        HorizontalOptions= "Start"
                        VerticalOptions= "Start" />
                </ Grid >
            </ Frame >
        </ DataTemplate >
    </ CarouselView.ItemTemplate >
</ CarouselView >

**Comment by jfversluis** [comment]
I know you can't share the original code, but would it be possible to create a sample project that shows this behavior? This way we can determine if maybe some other layout elements might be effecting this.

Thanks!

**Comment by XXcharlosXX** [comment]
https://github.com/XXcharlosXX/CarouselViewIssue_iOS

Check this repo out.
Unfortunately, unable to even view the carousel view in iOS. But works flawlessly on Droid.

**Comment by XXcharlosXX** [comment]
Hello?

**Comment by jfversluis** [comment]
Sorry for the delay @XXcharlosXX. Running your GitHub project only shows me this

![Screenshot 2019-08-10 at 12 41 20](https://user-images.githubusercontent.com/939291/62820925-2f8ad300-bb6c-11e9-9688-eee2518bfdea.png)

**Comment by XXcharlosXX** [comment]
Yes, did you try running the project on android?
After you do that you will see the issue.

**Comment by jfversluis** [comment]
In your initial comment you said it works on Android but not for iOS?

**Comment by XXcharlosXX** [comment]
Yes, once you run it on android you will see it working perfectly. Which then begs the question, why does iOS not work?

**Comment by jfversluis** [comment]
OK, sorry. I'm getting a little confused here. The original issue was that the last item was clipped, but now your issue is that it is not working at all on iOS? :) 

I just thought you might have forgotten to include the image on iOS or something like that.

**Comment by XXcharlosXX** [comment]
A potential workaround that I will use if this issue is not fixed would be to just add a "ghost" element at the end on iOS and not on Android. Though that wouldn't be the best way, it would work.

**Comment by XXcharlosXX** [comment]
I am sorry if you are unable to diagnose the issue through the project I have shared. But one thing is for certain; There are still issues with CarouselView on iOS.

**Comment by jfversluis** [comment]
@XXcharlosXX it's not that I am not able to diagnose, I am not even sure what to look for right now 😄 

As mentioned, the original problem states that the last item on iOS is clipped. I would gladly look into that, but the reproduction project that you have provided does not show me anything. To be able to diagnose the clipped item problem I would need a project that shows that behavior.

If the not showing anything at all is also a bug according to you, we should probably also look into that. Sorry for the confusion but could you please clarify what it is you want us to look into and could you please provide reproduction projects for it?

Thanks!

**Comment by XXcharlosXX** [comment]
Yes, I am sorry. I haven't really put a lot of effort into this repro. Apologies for wasting anyones time. I will work on updating this project to accurately reflect the issue I have discovered. I appreciate your patience. I will post another comment once the project has been updated.

**Comment by XXcharlosXX** [comment]
Ok @jfversluis, I think I may have reproduced the issue fully. It seems all I needed to do was to update the nuget packages. If for some reason the iOS simulator shows the same thing as last time. Maybe check if there is a nuget package update available?
Please let me know if you encounter any issues. I appreciate the work you guys are doing to make this product the best it can be!
(bug example)
![Simulator Screen Shot - iPhone Xʀ - 2019-08-13 at 10 12 36](https://user-images.githubusercontent.com/40214085/62962043-e5476300-bdb2-11e9-9047-e9369c27f748.png)

**Comment by samhouts** [comment]
closed by #7158
