### ISSUE TITLE
 GestureRecognizers not working in UWP

### ISSUE THREAD

**Issue by XamarinTounsi** [xamarin/Xamarin.Forms#7038]
i have also activated Library Images in Package.appxmanifest
<Grid Grid.Row="1" BackgroundColor="{StaticResource GrayColor}">
                <ffimageloading:CachedImage     
                    Grid.Column="0"
                    Source="{Binding LogoUrl}"
                    CacheType="Disk"
                    CacheDuration="30"
                    DownsampleToViewSize="True"
                    Style="{StaticResource ItemImageStyle}">
                    <ffimageloading:CachedImage.LoadingPlaceholder>
                        <OnPlatform                       
                            x:TypeArguments="ImageSource"
                            iOS="loading"
                            Android="loading"
                            WinPhone="Images/loading.png"/>
                    </ffimageloading:CachedImage.LoadingPlaceholder>
                    <ffimageloading:CachedImage.ErrorPlaceholder>
                        <OnPlatform                       
                            x:TypeArguments="ImageSource"
                            iOS="noimage"
                            Android="noimage"
                            WinPhone="Images/noimage.png"/>
                    </ffimageloading:CachedImage.ErrorPlaceholder>
                </ffimageloading:CachedImage>
                <Image
                    Style="{StaticResource PickImageStyle}"
                    Source="{StaticResource PickImageIcon}" />
                <Grid.GestureRecognizers>
                    <TapGestureRecognizer
                        Command="{Binding PickImageCommand}"
                        NumberOfTapsRequired="1" />
                </Grid.GestureRecognizers>
            </Grid>

**Comment by samhouts** [comment]
@XamarinTounsi  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by XamarinTounsi** [comment]
Hello @samhouts, after some tests i  found the real issue, the GestureRecognizers work fine, but the problem is here, i can't access to my windows storage :/
public Command PickImageCommand { get; }
        private async Task PickImageAsync()
        {
            var result = await PhotoService.Instance.PickPhotoAsync();

            if (result != null)
            {
                Image = result;
                LogoUrl = result.Path;
            }
        }

Photoservice

public async Task<MediaFile> TakePhotoAsync()
        {
            try
            {
                MediaFile image = null;
                await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    return null;
                }

                var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
                if (cameraStatus != PermissionStatus.Granted)
                    await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera);

                var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    PhotoSize = PhotoSize.Medium,
                    AllowCropping = true,
                    CompressionQuality = 92
                });

                if (file != null)
                {
                    image = file;
                }

                return image;
            }
            catch (TaskCanceledException)
            {
                return null;
            }
        }

**Comment by XamarinTounsi** [comment]
Hello everyone, thanks for all support, i have found the issue, when i debugg in laptop the GestureRecognizers work fine and not in PC desktop :/ any solution please
