### ISSUE TITLE
The height of a label that word-wraps is not properly used when computing content height of a Grid cell

### ISSUE THREAD

**Issue by Maxgamerboy1** [xamarin/Xamarin.Forms#7042]
### Description
Followup on Bugzilla: https://xamarin.github.io/bugzilla-archives/21/21844/bug.html
The issue is marked as Resolved but I'm not sure if it has been released, see notes below.
When having a Grid and Row set to Auto, and a Label therein with LineBreakMode=WordWrap, the height of the row isn't recalculating based on its new height when the label word wraps.

### Steps to Reproduce
Please see the Bugzilla link

### Expected Behavior
The height of the row is adjusted to fit the Label

### Actual Behavior
The row clips the label's text

### Basic Information

- Version with issue: 3.5.0.169047
- Last known good version:
- IDE: Visual Studio 2019 Enterprise 16.3.0 Preview 1.0
- Platform Target Frameworks: 
  - iOS: 12.4 
  - Android: 9.0  
  - UWP: 16299  
- Android Support Library Version: 
- Nuget Packages: n/a
- Affected Devices: Sony Experia L1, Windows 10 devices, iPad 5th Gen

**Comment by StephaneDelcroix** [comment]
please attach a small sample updated to 4.1.0, thanks

**Comment by Maxgamerboy1** [comment]
please download from my drive account! https://drive.google.com/open?id=1IwQFva0sCs3q7tLfpZS6ctbqrkKnZoRm

**Comment by Maxgamerboy1** [comment]
This has also been talked about on the forums [here](https://forums.xamarin.com/discussion/17488/xamarin-forms-label-wont-word-wrap-inside-a-grid/ ). It was first spotted back in 2014 and eventually references #2137

**Comment by groege** [comment]
I've had this bug as well, would be nice to have this fixed at some point.

**Comment by PureWeen** [comment]
I'm going to close this one for now in favor of
https://github.com/xamarin/Xamarin.Forms/issues/2137

I removed the inactive label and marked it to be scheduled for an upcoming sprint
