### ISSUE TITLE
Add Picker.TextAlignment

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#7043]
## Summary
Picker shows text but there's no way to control its alignment.

## API Changes

```cs
var picker = new Picker();
picker.HorizontalTextAlignment = TextAlignment.Center;
```

## Intended Use Case
Modifying how a picker looks.

**Comment by groege** [comment]
I'd love to have this too.

**Comment by pictos** [comment]
@samhouts, Can I work on this?

**Comment by samhouts** [comment]
@pictos Sure!

**Comment by mohamadayash** [comment]
Updated to Xamarin.Forms 4.8 

![image](https://user-images.githubusercontent.com/11196273/89669442-200da980-d8e8-11ea-91b7-0be12ff1694d.png)

I've tried horizontal text alignment as follow : 
` <Picker x:Name="picker"
                    Grid.Row="6" HorizontalTextAlignment="Center"
                    Title="Select a monkey"
                    TitleColor="Red">
                <Picker.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>Baboon</x:String>
                        <x:String>Capuchin Monkey</x:String>
                        <x:String>Blue Monkey</x:String>
                        <x:String>Squirrel Monkey</x:String>
                        <x:String>Golden Lion Tamarin</x:String>
                        <x:String>Howler Monkey</x:String>
                        <x:String>Japanese Macaque</x:String>
                    </x:Array>
                </Picker.ItemsSource>
            </Picker>`
but I get this error , look likes it's not able to find the property 

![image](https://user-images.githubusercontent.com/11196273/89669393-08cebc00-d8e8-11ea-8ebe-2d51e3c461aa.png)

**Comment by TechGuyGeek** [comment]
Works great for me thanks picker.HorizontalTextAlignment = TextAlignment.Center;
