### ISSUE TITLE
Label Crash on XF 4.1 SR2

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [xamarin/Xamarin.Forms#7045]
### Description
08-01 13:00:12.876 I/MonoDroid( 3940): UNHANDLED EXCEPTION:
08-01 13:00:12.880 I/MonoDroid( 3940): Java.Lang.ArrayIndexOutOfBoundsException: dstBegin > dst.length. dstBegin=1892064288, dst.length=0
08-01 13:00:12.880 I/MonoDroid( 3940):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <23e57773773243b6853e76fc01957c33>:0 
08-01 13:00:12.880 I/MonoDroid( 3940):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0001f] in <23e57773773243b6853e76fc01957c33>:0 
08-01 13:00:12.880 I/MonoDroid( 3940):   at Android.Text.SpannableString.GetChars (System.Int32 start, System.Int32 end, System.Char[] dest, System.Int32 off) [0x0005f] in /Users/builder/jenkins/workspace/xamarin-android-commercial/xamarin-android/src/Mono.Android/obj/Release/android-29/mcw/Android.Text.SpannableString.cs:134 
08-01 13:00:12.880 I/MonoDroid( 3940):   at Xamarin.Forms.Platform.Android.TextViewExtensions.RecalculateSpanPositions (Android.Widget.TextView textView, Xamarin.Forms.Label element, Android.Text.SpannableString spannableString, Xamarin.Forms.SizeRequest finalSize) [0x000d0] in D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\TextViewExtensions.cs:109 
08-01 13:00:12.880 I/MonoDroid( 3940):   at Xamarin.Forms.Platform.Android.FastRenderers.LabelRenderer.OnLayout (System.Boolean changed, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom) [0x0000d] in D:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\LabelRenderer.cs:139 
08-01 13:00:12.880 I/MonoDroid( 3940):   at Android.Views.View.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 left, System.Int32 top, System.Int32 right, System.Int32 bottom) [0x00009] in /Users/builder/jenkins/workspace/xamarin-android-commercial/xamarin-android/src/Mono.Android/obj/Release/android-29/mcw/Android.Views.View.cs:17346 
08-01 13:00:12.880 I/MonoDroid( 3940):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.61(intptr,intptr,bool,int,int,int,int)
08-01 13:00:12.880 I/MonoDroid( 3940):   --- End of managed Java.Lang.ArrayIndexOutOfBoundsException stack trace ---
08-01 13:00:12.880 I/MonoDroid( 3940): java.lang.ArrayIndexOutOfBoundsException: dstBegin > dst.length. dstBegin=1892064288, dst.length=0
08-01 13:00:12.880 I/MonoDroid( 3940): 	at java.lang.String.getChars(String.java:802)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.text.SpannableStringInternal.getChars(SpannableStringInternal.java:174)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md5f92e0daf340890c9667469657ee2ece8.LabelRenderer.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md5f92e0daf340890c9667469657ee2ece8.LabelRenderer.onLayout(LabelRenderer.java:54)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.ViewRenderer_2.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.ViewRenderer_2.onLayout(ViewRenderer_2.java:47)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:81)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.PageRenderer.onLayout(PageRenderer.java:72)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md58432a647068b097f9637064b8985a5e0.NavigationPageRenderer.onLayout(NavigationPageRenderer.java:65)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:37)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.n_onLayout(Native Method)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at md51558244f76c53b6aeda52c8a337f2c37.PlatformRenderer.onLayout(PlatformRenderer.java:63)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.880 I/MonoDroid( 3940): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.View.layout(View.java:20672)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.Choreographer.doFrame(Choreographer.java:696)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.os.Handler.handleCallback(Handler.java:873)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.os.Looper.loop(Looper.java:193)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at android.app.ActivityThread.main(ActivityThread.java:6680)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at java.lang.reflect.Method.invoke(Native Method)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-01 13:00:12.881 I/MonoDroid( 3940): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Basic Information

- Version with issue: 4.1 SR2
- Last known good version:
- IDE: VS 16.2.0
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.1

**Comment by samhouts** [comment]
@xamarindevelopervietnam  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by xamarindevelopervietnam** [comment]
@samhouts I think problem come from Label FormattedText, if I use Label without FormattedText the app work and Label with FormattedText, I received above crash

**Comment by xamarindevelopervietnam** [comment]
FYI:
build tools: 29.0.1
target android version: Android Q (9.0.99) - Level 29
VS 16.2.0
XF: Stable 4.1 SR2
Device: Android Simulator (tested on 6.0 and 9.0)
@samhouts

**Comment by xamarindevelopervietnam** [comment]
any work around?

**Comment by PureWeen** [comment]
@xamarindevelopervietnam do you have a small reproduction you can attach for this? We've tested FormattedText and have a lot of UI Tests testing FormattedText and aren't seeing the issue you are referring to.

**Comment by xamarindevelopervietnam** [comment]
FYI: I downgraded <TargetFrameworkVersion>v9.0.99</TargetFrameworkVersion> to <TargetFrameworkVersion>v9.0</TargetFrameworkVersion> and it work. Build release the app with target 9.0.99 make the app crash very usually.

**Comment by PureWeen** [comment]
This does look like an issue with Android Q 

I've created an Android Q issue over here
https://github.com/xamarin/Xamarin.Forms/issues/7169

Where we are going to track testing and updating to Android Q

**Comment by PureWeen** [comment]
@xamarindevelopervietnam 9.0.99 is a beta version of Android Q

I tested Labels on v10 (which is part of vsmac 8.3 and vs 16.3) and it all works fine there.

**Comment by xamarindevelopervietnam** [comment]
noted @PureWeen
