### ISSUE TITLE
[Enhancement] CollectionView staggered layout

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#7046]
## Summary
A staggered collection layout is commonly used to show views with different sizes.

![image](https://user-images.githubusercontent.com/11095003/62325373-cf30cd00-b4ab-11e9-8070-e74f87e3f80c.png) 

## API Changes

Add the `StaggeredItemsLayout` as a layout option. Additionaly to the `ItemsLayout` properties, it requires a `Span` property (could be inherited from the GridLayout).

```
public class StaggeredItemsLayout : ItemsLayout
{
	public static readonly BindableProperty SpanProperty;
	public int Span { get; set; }
}
```

Additionally, it could be possible to have some items that stretch trough the full width or height like in this scenario
![image](https://user-images.githubusercontent.com/11095003/62325850-ede39380-b4ac-11e9-8aa2-1b42c8b30dc2.png)

This could be done via an attached property that is set on the view itself. 

```
public static class StaggeredCollectionLayout
{
	public static readonly BindableProperty IsFullSpanProperty =
		BindableProperty.Create("IsFullSpan", typeof(IList), typeof(View), false);
}

<ContentView StaggeredCollectionLayout.IsFullSpan="true" >
  ...
</ContentView>

```

## Intended Use Case

Used to show views with different sizes in a collection.

**Comment by adrianknight89** [comment]
If this is implemented, I'm guessing Android will use `StaggeredGridLayoutManager`. If so, please check [RecyclerViewScrollListener](https://github.com/xamarin/Xamarin.Forms/blob/88577eac76e5a20fe1415ed0e67ac3e3d97bdd21/Xamarin.Forms.Platform.Android/CollectionView/RecyclerViewScrollListener.cs#L36) so that visible item indexes can work with the new layout.

**Comment by krdmllr** [comment]
Android is quite easy, I did it here for Xappy https://github.com/krdmllr/Xappy/blob/9bb14318100fb1a662a4f4ec622cfb77c3cfe2cf/Xappy/Xappy.Android/Renderers/XappyCollectionViewRenderer.cs

I had problems with the full span elements because the xf android implementation is mostly internal, I opened an issue for that here https://github.com/xamarin/Xamarin.Forms/issues/6090

I tried to do the iOS implementation aswell but the CollectionView implementation kept changing and I decided to wait until it is stable.

**Comment by GalaxiaGuy** [comment]
I'd also be interested in a way to add custom layouts without having to subclass the whole renderer. i.e. have some way to register a `LayoutManager` with the default renderer that will then be checked for in `SelectLayoutManager`.

**Comment by xamarindevelopervietnam** [comment]
++

**Comment by AswinPG** [comment]
> Android is quite easy, I did it here for Xappy https://github.com/krdmllr/Xappy/blob/9bb14318100fb1a662a4f4ec622cfb77c3cfe2cf/Xappy/Xappy.Android/Renderers/XappyCollectionViewRenderer.cs
> 
> I had problems with the full span elements because the xf android implementation is mostly internal, I opened an issue for that here #6090
> 
> I tried to do the iOS implementation aswell but the CollectionView implementation kept changing and I decided to wait until it is stable.

Was the ios implementation a success ? Where can I start to learn how to implement it in ios ? In android it was pretty simple, Stuck with iOS

**Comment by praveennachi60** [comment]
Any one implemented the staggeredlayout in ios?

**Comment by Gckumar999** [comment]
To implement the staggeredlayout in ios, https://github.com/leoholcman/WCollectionView.Forms

I have implemented and it works great!

**Comment by praveennachi60** [comment]
> To implement the staggeredlayout in ios, https://github.com/leoholcman/WCollectionView.Forms
> 
> I have implemented and it works great!

That's Great. This is what I looking for..Thank you @Gckumar999 .
Its working as I expected.

**Comment by AswinPG** [comment]
How can we do infinite loading with it ?

**Comment by jfversluis** [comment]
Hey everyone! Thanks for the input here. As you might've already guessed this is not going to happen for Xamarin.Forms anymore. If you're still interested in this, make sure there is a feature request for this on the .NET MAUI repository. If there already is, make sure to upvote!

Thanks!
