### ISSUE TITLE
[Bug] Named Font Size (Header) is this correct? [Bug]

### ISSUE THREAD

**Issue by XXcharlosXX** [xamarin/Xamarin.Forms#7047]
### Description
Member | iOS | Android | UWP
Default | 16 | 14 | 14
Micro | 11 | 10 | 15.667
Small | 13 | 14 | 18.667
Medium | 16 | 17 | 22.667
Large | 20 | 22 | 32
Body | 17 | 16 | 14
Header | 17 | 96 | 46
Title | 28 | 24 | 24
Subtitle | 22 | 16 | 20
Caption | 12 | 12 | 12

on iOS a Header is the same size as the body... (17)
on Android Header is 96, which is huge.
Just curious was this overlooked or are these values intentional.
They do not look similar AT ALL on their respective devices.
### Steps to Reproduce

1. Create a label with the fontSize set to the named.Font.Size == "Header"
2. Build & Run on both iOS and Droid. The difference is drastic.
3. 

### Expected Behavior
Should look fairly similar
### Actual Behavior
Droid Label is MASSIVE vs the iOS. I think iOS needs to be a bit bigger.
### Basic Information

- Version with issue: Visual Studio
- Last known good version: ????
- IDE: Visual Studio (Mac and Windows)
- Platform Target Frameworks: 
  - iOS: 12.0+
  - Android: 5.0+ 
- Affected Devices:
iOS

### Screenshots

<img width="923" alt="Screen Shot 2019-08-01 at 3 25 08 PM" src="https://user-images.githubusercontent.com/40214085/62331361-932c4680-b470-11e9-9085-53e266a4cc8e.png">

### Reproduction Link
**XAML code to create issue**
Label Text="Header" FontSize="Header" HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand"

**Comment by jfversluis** [comment]
I think this originated from #6517 and #5985.

Looking at the official [Google Material typography](https://material.io/develop/android/theming/typography/), the size for Headline1 is in fact 96.

According to the [Human Interface Guidelines ](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/) from Apple, with the default settings the heading should there be 17.
