### ISSUE TITLE
[Bug] CheckBox Has Incosistent Paddings

### ISSUE THREAD

**Issue by hnabbasi** [xamarin/Xamarin.Forms#7048]
### Description
The CheckBox control has inconsistent padding/margin on iOS and UWP.

### Steps to Reproduce

1. Add a CheckBox to your view
2. Set `BackgroundColor` to `Color.Silver`
3. You will see the CheckBox not centered in the control.

XAML Content:
```xml
<StackLayout VerticalOptions="Center">
    <StackLayout Orientation="Horizontal" HorizontalOptions="Center">
        <CheckBox BackgroundColor="Silver"/>
        <Label Text="CheckBox" VerticalOptions="Center" />
    </StackLayout>
</StackLayout>
```

Sample Repo: 
[https://github.com/hnabbasi/XamarinFormsIssue7048](https://github.com/hnabbasi/XamarinFormsIssue7048)

### Expected Behavior
CheckBox appears in the middle of the control, with less padding preferably.

### Actual Behavior
CheckBox appears slightly left of the middle of the control.

### Basic Information

- Version with issue: 4.1.0.618606
- Last known good version:
- IDE: VS 2019 Windows & Mac
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: API 28
  - UWP: 10.0.17763.0
  - Affected Devices: Tested on all three simulators/emulator.

### Screenshots

<img src="https://user-images.githubusercontent.com/12173156/62385521-ece94b00-b51a-11e9-9a4f-16494b908273.png"/>

**Comment by jfversluis** [comment]
Would it be possible to provide a small sample project that shows this problem?

**Comment by hnabbasi** [comment]
Sure. Will add one today

**Comment by MitchBomcanhao** [comment]
Another part to this issue is that the spacing is inconsistent across platforms, so in order for things to look ok I've had to tinker with the margins on a per platform basis.

**Comment by PureWeen** [comment]
@MitchBomcanhao can you attach a repro as well or expand on what differences you've had to apply?

**Comment by hnabbasi** [comment]
@jfversluis @PureWeen … Done. Added repo that shows both issues.

**Comment by jcmanke** [comment]
I'm guessing this is the problem on UWP:
https://github.com/xamarin/Xamarin.Forms/blob/d56942c5bee0a7c56255febc8bbcc6bc33d5e1cb/Xamarin.Forms.Platform.UAP/FormsCheckBoxStyle.xaml#L17

**Comment by dinesh4official** [comment]
@samhouts , i am still facing the issue in **v4.4**. Please check with iOS iPhone 11 13.3 version

**Comment by gceaser** [comment]
I have an issue on UWP at least where the checkbox will not correctly center in its container.  This appears to be prominent when the checkbox has no text.  The beige are is the container, a syncfusion button control but the same behavior is experienced with a stacklayout.  You can see the checkbox is not centered.  

![image](https://user-images.githubusercontent.com/8093949/73954198-7e24ea00-48cf-11ea-90f3-c8c3c22182ed.png)

**Comment by Xyotic** [comment]
For UWP, set these in a custom renderer:

Control.Padding = new Windows.UI.Xaml.Thickness(0);
Control.MinWidth = 0;
Control.HorizontalAlignment = Windows.UI.Xaml.HorizontalAlignment.Center;

This fixes the issue for me and the checkbox will be centered.

**Comment by Xyotic** [comment]
My fix for iOS. Set this in a custom renderer:

Control.HorizontalAlignment = UIControlContentHorizontalAlignment.Center;
Control.ContentEdgeInsets = new UIEdgeInsets(0, 7, 0, 7);

Control.HorizontalAlignment will align it horizontal but you'll get some kind of padding/margin issue.
This seems to be caused by the ContentEdgeInsets beeing set to (0, 7, 0, 0)...

**Comment by Qythyx** [comment]
This was never fixed for iOS, can it be reopened or should I open a new bug?
