### ISSUE TITLE
[Bug] Cannot select Items from Picker in Xamarin UI Tests

### ISSUE THREAD

**Issue by kgbuddhima** [xamarin/Xamarin.Forms#7052]
### Description
We use Xamarin UI tests for our apps for Automated testing.
But we are having an issue when trying to select items except the default item(first item) from the picker
And also the picker items does not catch by App.Query(c=>c.Marked("pickersAutomationId"))
### Steps to Reproduce

1. app.Repel()
.
.. some steps...
.
2. App.Tap(c=>c.Marked("pickersAutomationId"))
3. App.Qyery(c=>c.Marked("pickersAutomationId"))

When Press App.PressEnter(),
it selects the default item as the selected item.

*** And also could not Scroll Down or Scroll Up through the picker view.

### Expected Behavior
Should be able to go through the items in the picker control
Should See available items when call App.Qyery(c=>c.Marked("pickersAutomationId"))

### Actual Behavior, it shouws only the element Id(s) of picker box,
when call App.Qyery(c=>c.Marked("pickersAutomationId"))
AppResult[] results = app.Query(c=>c.Marked("pickersAutomationId"))

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2017 Enterprise
- Platform Target Frameworks: 
  - Android: 8.1 and 9.0
- Android Support Library Version: v7
- Nuget Packages: Xamarin.Forms 4.0
- Affected Devices: Google Nexus 5, 8.1 Oreo,

**Comment by jfversluis** [comment]
Could you create a small project that shows your problem?

I think it's possible, I'd like to see your code/problem and see if I can add the solution for you.

**Comment by samhouts** [comment]
@kgbuddhima  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
