### ISSUE TITLE
[Bug] Rounded curve is not smooth even though AntiAlias is set. 

### ISSUE THREAD

**Issue by Manoj-leo** [xamarin/Xamarin.Forms#7054]
### Description

-  When drawing a rounded rectangle, not able to get smooth curve even though AntiAlias is set. 

### Steps to Reproduce

1.  Create  a custom content view
2.  Draw a rounded rectangle using canvas as a child of content view.
3.  We can notice the rounded curve which will be not smooth. 

### Output screenshot:

![Screenshot_20190801-123003 1](https://user-images.githubusercontent.com/52370616/62272099-e645cf80-b457-11e9-8cff-f7f71bc4cad3.jpg)

### Version Information

Xamarin Forms version - 4.1.0.618606

Sample:

[BdSample.zip](https://github.com/xamarin/xamarin-android/files/3455347/BdSample.zip)

**Comment by hartez** [comment]
Your drawing code is Android-specific. This is not a Xamarin.Forms issue - you should open an issue in the [Xamarin Android repository](https://github.com/xamarin/xamarin-android). They may be able to help you.
