### ISSUE TITLE
[Bug] NullReferenceException Closing Window During Animation

### ISSUE THREAD

**Issue by spencerbaer** [xamarin/Xamarin.Forms#7061]
### Description
On WPF, if the window is closed while an animation is running, then a NullReferenceException will be thrown.
### Steps to Reproduce

1. Start an animation using one of the ScaleTo, TranslateTo, etc. extensions.
2. Close the window while the animation is active

### Expected Behavior
The application exits without issue.
### Actual Behavior
A NullReferenceException is thrown:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Xamarin.Forms.Platform.WPF
  StackTrace:
   at Xamarin.Forms.Platform.WPF.WPFPlatformServices.BeginInvokeOnMainThread(Action action)
   at Xamarin.Forms.Internals.Ticker.Remove(Int32 handle)
   at Xamarin.Forms.Tweener.Finalize()

### Basic Information

- Version with issue: v4.1.0
- IDE: VS 2019 
- Platform Target Frameworks: 

  - WPF: .NET Framework 4.7.2

### Reproduction Link

[AnimationOnExitDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/3463903/AnimationOnExitDemo.zip)

Application has a long-running animation that activates when the window appears, so just close the window after it opens to reproduce the issue. UWP project is also included for comparison.

**Comment by jfversluis** [comment]
Tried the repro project and confirmed it happens. There is a UWP project in the repro which doesn't show this behavior.
