### ISSUE TITLE
DisplayAlert Title not respecting FlowDirection

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7065]
Hi,

When I set the page to RightToLeft's FlowDirection the title of the DisplayAlert still going to the LeftToRight

Please see below screenshot...

![Screenshot_20190805_062325](https://user-images.githubusercontent.com/6236241/62434566-c9f0ae00-b749-11e9-97b0-32a314753925.jpg)

Thanks,
[Jassim](https://www.softnames.com)

**Comment by jfversluis** [comment]
I can't seem to reproduce this locally. Could you maybe specify what version of Android you are seeing this? Does this also happen on iOS?

If at all possible could you show some code or maybe even a small sample repro project?

Thanks!

**Comment by jrahma** [comment]
it's weird! I created a new project and it shows it right but in my project it shows the title LTR..

And what is funny that it is ONLY the Title of the DisplayAlert not the content itself!

Although my new sample is just a copy paste from my existing code!

**Comment by jfversluis** [comment]
Do you have any custom renderers in place? Anything else that might affect this behavior? I had to set the "is RTL supported" property in the AndroidManifest.xml, is that set?

**Comment by jrahma** [comment]
Nope... No custom renderers

and the AndroidManifest has the RTL set

**Comment by jfversluis** [comment]
Strange. Is it possible your repro project has a newer Forms version than the app that has the actual problem?

**Comment by jrahma** [comment]
I Know, very strange! Nope, I have update Xamarin Forms on both to the latest

I have sent you a link with the app

**Comment by PureWeen** [comment]
@jrahma I'm wondering if it's due to something in your AndroidManifest.xml

Do you have rtl set there?
```xml
<application android:label="AndroidControlGallery" android:supportsRtl="true">
```

Also do you have bot the min and target sdks set?
```
<uses-sdk android:minSdkVersion="17" android:targetSdkVersion="28" />
```


Try setting *android:minSdkVersion* to 17 if you have it at a lower value

**Comment by jrahma** [comment]
here is my AndroidManifest.xml

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.alertrtl">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />
    <application android:label="AlertRTL.Android" android:supportsRtl="true"></application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

```

and attached is a simple app with the problem:

I noticed this problem happens when I set:

`android:supportsRtl="true"`


so should I set it or not if I am working on a localized RTL app?

[AlertRTL.zip](https://github.com/xamarin/Xamarin.Forms/files/3512452/AlertRTL.zip)


Thanks,
Jassim

**Comment by jfversluis** [comment]
OK, this is really weird. The bug actually happens whenever you _do_ set `android:supportsRtl="true"`. I've taken your reproduction project and when I set `android:supportsRtl="false"` it suddenly shows up the right way. While you would expect it to be the other way around.

**Comment by AbuSafi** [comment]
**DisplayAlert** and **DisplayActionSheet** orientation is controlled by the device locale, rather than the FlowDirection property.

Reference : https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left

**Comment by jrahma** [comment]
I still believe this can and this should be fixed

**Comment by ahmedElsayedSmarttech** [comment]
this is still an issue, i am using xamarin forms 4.7
