### ISSUE TITLE
WPF Material

### ISSUE THREAD

**Issue by Adamv21** [xamarin/Xamarin.Forms#7074]
Does it exist a WPF material package? If not are there any plans to make one?

**Comment by jfversluis** [comment]
Hey @Adamv21, great question!

WPF is supported by the community at this time. This means that we gladly look forward to any PRs and effort in that regard, but it is not on our own roadmap right now. Some more info is [here](https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support).

I have seem some work around Material in combination with WPF out there, but not specific to Xamarin.Forms. You're most welcome to contribute in that area. For now, I will close this issue. If I failed to answer a part of your question feel free to add a comment or reopen.
