### ISSUE TITLE
[Bug] InvalidCastException in Android.ScrollViewRenderer

### ISSUE THREAD

**Issue by CodeOfDarkness** [xamarin/Xamarin.Forms#7075]
### Description
I have a ContentPage in my PCL with three ListViews. All ListViews have the same DataTemplate, but different data. 
On iOS everything works. 
On Android the third ListView crashes when I scroll and throws a System.InvalidCastException, as you can see below.

### Stack Trace
at Xamarin.Forms.Platform.Android.ScrollViewRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00007] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:73 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.AddChild (Xamarin.Forms.VisualElement view, Xamarin.Forms.Platform.Android.IVisualElementRenderer oldRenderer, Xamarin.Forms.Platform.Android.RendererPool pool, System.Boolean sameChildren) [0x000f5] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:145 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement) [0x00139] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:334 
  at Xamarin.Forms.Platform.Android.VisualElementPackager.OnElementChanged (System.Object sender, Xamarin.Forms.Platform.Android.VisualElementChangedEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:58 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x0002f] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:340 
  at Xamarin.Forms.Platform.Android.Platform+DefaultRenderer.OnElementChanged (Xamarin.Forms.Platform.Android.ElementChangedEventArgs`1[TElement] e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Platform.cs:1229 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000c3] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:236 
  at Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.Android.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:127 
  at Xamarin.Forms.Platform.Android.ViewCellRenderer+ViewCellContainer.Update (Xamarin.Forms.ViewCell cell) [0x000f9] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\ViewCellRenderer.cs:167 
  at Xamarin.Forms.Platform.Android.ViewCellRenderer.GetCellCore (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x00027] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\ViewCellRenderer.cs:21 
  at Xamarin.Forms.Platform.Android.CellRenderer.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context) [0x00075] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellRenderer.cs:51 
  at Xamarin.Forms.Platform.Android.CellFactory.GetCell (Xamarin.Forms.Cell item, Android.Views.View convertView, Android.Views.ViewGroup parent, Android.Content.Context context, Xamarin.Forms.View view) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.Android\Cells\CellFactory.cs:20 
  at Xamarin.Forms.Platform.Android.ListViewAdapter.GetView (System.Int32 position, Android.Views.View convertView, Android.Views.ViewGroup parent) [0x00200] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ListViewAdapter.cs:299 
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_ (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position, System.IntPtr native_convertView, System.IntPtr native_parent) [0x0001a] in <b62c3fba3fe848f3bb323dbe33464223>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.94(intptr,intptr,int,intptr,intptr)

### Basic Information
- Version with issue: 4.1.0.618606
- IDE: Visual Studio Community
- Platform Target Frameworks:
  - Android: API 28
- Affected Devices: all

**Comment by jfversluis** [comment]
Hi @CodeOfDarkness, thanks for your report!

It sounds like you have a bit of .a complex layout going on there. Would it be possible to add a sample project that resembles your situation? That might make it a lot easier for us to track down what is going on here and hopefully resolve it soon.

Thanks!

**Comment by CodeOfDarkness** [comment]
It's difficult because my boss does not give me time for creating a sample project :/
But I can give you my XAML-File

`<?xml version="1.0" encoding="UTF-8"?>
<ContentPage 
    xmlns="http://xamarin.com/schemas/2014/forms" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
    xmlns:contextmenu="clr-namespace:ContextMenu;assembly=ContextMenu"
    xmlns:localviews="clr-namespace:bwm_xamarin.Views"
    x:Class="bwm_xamarin.Pages.TAPage"
    x:Name="pagebindingroot"
    Title="TA">

    <ContentPage.Icon>
        <OnPlatform x:TypeArguments="FileImageSource">
            <On Platform="iOS">ic_calendar.png</On>
        </OnPlatform>
    </ContentPage.Icon>
    
    <ContentPage.Resources>
        <ResourceDictionary>
            <Color x:Key="Primary">#2E8FCC</Color>
            <Color x:Key="TextOnPrimary">#FFFFFF</Color>
        </ResourceDictionary>
    </ContentPage.Resources>
    
    <ContentPage.Content>
        <FlexLayout Direction="Column">
            
            <StackLayout x:Name="LayoutNote" Orientation="Vertical" Spacing="0" FlexLayout.Basis="25%">
                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" BackgroundColor="{StaticResource Primary}" Padding="10">
                    <Label Text="Note for internal A" HorizontalTextAlignment="Center" VerticalOptions="Center" HorizontalOptions="FillAndExpand" TextColor="{StaticResource TextOnPrimary}" />
                    <ImageButton x:Name="ButtonEditNote" Source="ic_edit.png" Clicked="EditNoteButtonClicked" BackgroundColor="Transparent"/>
                </StackLayout>
                <ScrollView HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                    <Label x:Name="LabelNote" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"/>
                </ScrollView>
            </StackLayout>
            
            <StackLayout x:Name="LayoutT" Orientation="Vertical" Spacing="0" FlexLayout.Basis="25%">
                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" BackgroundColor="{StaticResource Primary}" Padding="10">
                    <Label Text="T" HorizontalTextAlignment="Center" VerticalOptions="Center" HorizontalOptions="FillAndExpand" TextColor="{StaticResource TextOnPrimary}" />
                    <ImageButton x:Name="ButtonEditT" WidthRequest="30" HeightRequest="30" Source="ic_edit.png" Clicked="EditTButtonClicked" BackgroundColor="Transparent"/>
                </StackLayout>
                
                <ListView x:Name="TListView" VerticalOptions="FillAndExpand" HasUnevenRows="true" Footer="" SelectionMode="None">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell IsEnabled="false">
                                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand" Padding="5">
                                    <Label Text="{Binding TName}" HorizontalOptions="FillAndExpand"/>
                                    <Label Text="(Optional)" TextColor="#AAAAAA" IsVisible="{Binding IsOptional}"/>
                                </StackLayout>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </StackLayout>
            
            <StackLayout x:Name="LayoutTer" Orientation="Vertical" Spacing="0" FlexLayout.Basis="50%" FlexLayout.Grow="0.75">
                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" BackgroundColor="{StaticResource Primary}" Padding="10">
                    <Label Text="WT" HorizontalTextAlignment="Center" VerticalOptions="Center" HorizontalOptions="FillAndExpand" TextColor="{StaticResource TextOnPrimary}" />
                    <ImageButton x:Name="ButtonAddTer" WidthRequest="30" HeightRequest="30" Source="ic_add.png" Clicked="AddTerButtonClicked" BackgroundColor="Transparent"/>
                </StackLayout>
                <ListView x:Name="WTListView" VerticalOptions="FillAndExpand" HasUnevenRows="true" Footer="" >
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <contextmenu:MoveToActionCell MovedCommand="{Binding Path=BindingContext.MoreCommand, Source={x:Reference Name=pagebindingroot}}">
                                <contextmenu:MoveToActionCell.Content>
                                    <ContentView WidthRequest="{Binding Source={x:Reference WTListView}, Path=Width}" BackgroundColor="White">
                                        <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand" Padding="5, 10, 5, 10">
                                            <StackLayout.GestureRecognizers>
                                                <TapGestureRecognizer Command="{Binding Path=BindingContext.SelectedTItemCommand, Source={x:Reference Name=pagebindingroot}}" CommandParameter="{Binding .}"/>
                                            </StackLayout.GestureRecognizers>
                                            <FlexLayout Direction="Column" HorizontalOptions="FillAndExpand" JustifyContent="SpaceEvenly">
                                                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                                                    <Image WidthRequest="20" HeightRequest="20" Source="ic_calendar_black.png" VerticalOptions="Center"/>
                                                    <Label Text="{Binding Datum}" VerticalOptions="Center"/>
                                                </StackLayout>
                                                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                                                    <Image WidthRequest="20" HeightRequest="20" Source="ic_time.png" VerticalOptions="Center"/>
                                                    <Label Text="{Binding Uhrzeit}" VerticalOptions="Center"/>
                                                </StackLayout>
                                                <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
                                                    <Image WidthRequest="20" HeightRequest="20" Source="ic_edit_black.png" VerticalOptions="Center"/>
                                                    <Label Text="{Binding Ersteller}" VerticalOptions="Center"/>
                                                </StackLayout>
                                            </FlexLayout>
                                            <FlexLayout Direction="Column" VerticalOptions="FillAndExpand" JustifyContent="SpaceEvenly" AlignContent="End">
                                                <StackLayout Orientation="Horizontal" IsVisible="{Binding HasFavoriten}">
                                                    <Label Text="{Binding Favoriten}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="End"/>
                                                    <Image Source="icon.png"/>
                                                </StackLayout>
                                                <StackLayout Orientation="Horizontal">
                                                    <Label Text="{Binding Zusagen}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="End"/>
                                                    <Image Source="icon.png"/>
                                                </StackLayout>
                                                <StackLayout Orientation="Horizontal">
                                                    <Label Text="{Binding OhneRueckmeldung}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="End"/>
                                                    <Image Source="icon.png"/>
                                                </StackLayout>
                                                <StackLayout Orientation="Horizontal">
                                                    <Label Text="{Binding Absagen}" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="End"/>
                                                    <Image Source="icon.png"/>
                                                </StackLayout>
                                            </FlexLayout>
                                        </StackLayout>
                                    </ContentView>
                                </contextmenu:MoveToActionCell.Content>
                                <contextmenu:MoveToActionCell.ContextTemplate>
                                    <DataTemplate>
                                        <StackLayout Padding="10, 0" BackgroundColor="{StaticResource Primary}">
                                            <Image WidthRequest="30" HeightRequest="30" HorizontalOptions="EndAndExpand" VerticalOptions="CenterAndExpand" Margin="0, 0, 15, 0" Source="ic_list_more.png"/>
                                        </StackLayout>
                                    </DataTemplate>
                                </contextmenu:MoveToActionCell.ContextTemplate>
                            </contextmenu:MoveToActionCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </StackLayout>
            
        </FlexLayout>
    </ContentPage.Content>
    
</ContentPage>`

**Comment by CodeOfDarkness** [comment]
It happens since I switched from SideContextMenuCell to MoveToActionCell in this library.
https://github.com/AndreiMisiukevich/ContextMenu

**Comment by CodeOfDarkness** [comment]
Please ignore my report, I misunderstood something in the usage of the ListView.
