### ISSUE TITLE
Xamarin.Forms.Xaml.XamlParseException with Bindings Reference in XF 4.2 Pre 3

### ISSUE THREAD

**Issue by pskofod** [xamarin/Xamarin.Forms#7097]
### Description
In xamarin forms 4.2 pre 3 I get this exception:
> Xamarin.Forms.Xaml.XamlParseException: 'Position 60:67. Can not find the object referenced by OrderList'

the exception is related to the binding to a reference. Like this line:
```xaml
     ColumnDefinition Width="{Binding Source={x:Reference Name=OrderList}, Path=BindingContext.IsLocationDeleteVisible, Converter={StaticResource VariableGridLengthConverter}, ConverterParameter=OrderColumn1}"
```
                                           
Commenting this line out I get the exception in other lines containing a reference.
It is working with XF 4.2 pre 2 and earlier (3.x).

### Basic Information

- Version with issue: https://github.com/xamarin/Xamarin.Forms/releases/tag/beta-4.2.0-pre3.1
- Last known good version: https://github.com/xamarin/Xamarin.Forms/releases/tag/beta-4.2.0-pre2
- IDE:
Microsoft Visual Studio Professional 2019
Version 16.2.1
VisualStudio.16.Release/16.2.1+29201.188
Microsoft .NET Framework
Version 4.7.03056

- Platform Target Frameworks: 
  - Android: 9.0 (Pie)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
Is part of a big project. Which is not applied here.

**Comment by jfversluis** [comment]
Thanks for the report @pskofod.

I see you can't add the whole project, but would it be possible to lift all the relevant code? Just this line doesn't tell us much. If you could put it in a project that would show this issue that would even be better.

Thanks!

**Comment by pskofod** [comment]
The whole xaml file is here:
<?xml version="1.0" encoding="utf-8" ?>
<basePages:BasePage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:basePages="clr-namespace:Brunata.Handterminal.Views.BasePages"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:c="clr-namespace:Brunata.Handterminal.Views.CustomControls"
             xmlns:effect="clr-namespace:Brunata.Handterminal.Views.Effects"
             xmlns:extensions="clr-namespace:Brunata.Handterminal.Views.Extensions"
             x:Class="Brunata.Handterminal.Views.GeneralFlow.OrderListPage"
             x:Name="OrderList">
    <ContentPage.Content>
        <StackLayout>
            <c:HeaderView ParentContext="{Binding BindingContext, Source={x:Reference OrderList}}"/>
            <c:BrunataTopTabView Command="{Binding OnTabChangedCommand}">
                <c:BrunataTopTabView.Tabs>
                    <c:Tab Text="{extensions:Translate BuildingOrderPage_Orders}" IsSelected="True"/>
                    <c:Tab Text="{extensions:Translate BuildingOrderPage_Buildings}"/>
                </c:BrunataTopTabView.Tabs>
            </c:BrunataTopTabView>
            <Grid VerticalOptions="FillAndExpand">
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="45"/>
                </Grid.ColumnDefinitions>
                <Grid VerticalOptions="FillAndExpand" Grid.Column="0" Grid.ColumnSpan="2">
                    <Grid.RowDefinitions>
                        <RowDefinition Height="6*"/>
                        <RowDefinition Height="4*"/>
                    </Grid.RowDefinitions>
                    <StackLayout Grid.Row="0" Grid.RowSpan="{Binding LocationOrderSpan}">
                        <c:SortableHeader SortCommand="{Binding OnLocationSortCommand}" Selection="{Binding LocationOrdersSortSelection}">
                            <c:SortableHeader.Columns>
                                <c:SortableColumn Width="75*" Text="{extensions:Translate General_BuildingNo}"/>
                                <c:SortableColumn Width="24" Text=""/>
                                <c:SortableColumn Width="138*" Text="{extensions:Translate General_Address}"/>
                                <c:SortableColumn Width="95*" Text="{extensions:Translate OrderlistPage_StartEnd}"/>
                                <c:SortableColumn Width="28" Text=""/>
                            </c:SortableHeader.Columns>
                        </c:SortableHeader>
                        <StackLayout IsVisible="{Binding IsLocationDeleteVisible}" Orientation="Horizontal" Margin="16, 5, 16, 5" HorizontalOptions="StartAndExpand" MinimumHeightRequest="27" MinimumWidthRequest="360">
                            <Image Source="{Binding LocationOrders, Converter={StaticResource toImageConverter}}">
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding LocationMarkUnmarkDeleteImagesCommand}"/>
                                </Image.GestureRecognizers>
                            </Image>
                            <Label Text="{extensions:Translate OrderlistPage_SelectAll}" Margin="5,0,0,0" HorizontalOptions="Start" VerticalOptions="Center"/>
                        </StackLayout>
                        <CollectionView x:Name="LocationListViewOrders"
                          ItemsSource="{Binding LocationOrders}"
                          VerticalOptions="FillAndExpand"
                           SelectionMode="None">
                            <CollectionView.ItemTemplate>
                                <DataTemplate>
                                    <Grid>
                                        <Grid Margin="16, 0, 16, 0">
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="40*"/>
                                                <RowDefinition Height="20*"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="{Binding Source={x:Reference Name=OrderList}, Path=BindingContext.IsLocationDeleteVisible, Converter={StaticResource VariableGridLengthConverter}, ConverterParameter=OrderColumn1}"/>
                                                <ColumnDefinition Width="{Binding Source={x:Reference Name=OrderList}, Path=BindingContext.IsLocationDeleteVisible, Converter={StaticResource VariableGridLengthConverter}, ConverterParameter=OrderColumn2}"/>
                                                <ColumnDefinition Width="24"/>
                                                <ColumnDefinition Width="138*"/>
                                                <ColumnDefinition Width="95*"/>
                                                <ColumnDefinition Width="28"/>
                                            </Grid.ColumnDefinitions>
                                            <Image  Grid.Row="0" Grid.Column="0"  HorizontalOptions="Start" VerticalOptions="StartAndExpand" Source="{Binding IsSetForDeletion, Converter={StaticResource toImageConverter}, ConverterParameter='CHECKBOX'}">
                                                <Image.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding Source={x:Reference LocationListViewOrders}, Path=BindingContext.LocationDeleteImageCommand}" CommandParameter="{Binding .}"/>
                                                </Image.GestureRecognizers>
                                            </Image>
                                            <Label Grid.Row="0" Grid.Column="1" Margin="3, 0, 0, 0" Text="{Binding BuildingNo}" HorizontalOptions="Start" VerticalOptions="StartAndExpand"/>
                                            <Image Grid.Row="0" Grid.Column="2"  HorizontalOptions="Start" VerticalOptions="StartAndExpand" Source="icon_note_grey.png" IsVisible="{Binding HasNote}">
                                                <Image.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding Source={x:Reference LocationListViewOrders}, Path=BindingContext.OnLocationNoteCommand}" CommandParameter="{Binding .}"/>
                                                </Image.GestureRecognizers>
                                            </Image>
                                            <StackLayout Grid.Row="0" Grid.Column="3"  Orientation="Vertical" VerticalOptions="StartAndExpand" >
                                                <Label Text="{Binding Address}" />
                                                <Label Text="{Binding PostcodeAndCity}" />
                                            </StackLayout>
                                            <StackLayout Grid.Row="0" Grid.Column="4" Orientation="Vertical" VerticalOptions="StartAndExpand">
                                                <Label Text="{Binding VisitStartDateLocal, Converter={StaticResource toStringConverter}, ConverterParameter='DATETIME'}" />
                                                <Label Text="{Binding VisitEndDateLocal, Converter={StaticResource toStringConverter}, ConverterParameter='DATETIME'}" />
                                            </StackLayout>
                                            <StackLayout Grid.Row="0" Grid.Column="5" Orientation="Horizontal" HorizontalOptions="CenterAndExpand" VerticalOptions="StartAndExpand" >
                                                <Image Source="icon_type_3_grey.png" IsVisible="{Binding IsHAOrder}" WidthRequest="24" HeightRequest="24"/>
                                                <Image Source="icon_type_2_grey.png" IsVisible="{Binding IsMOOrder}" WidthRequest="24" HeightRequest="24"/>
                                                <Image Source="icon_type_1_grey.png" IsVisible="{Binding IsFMOOrder}" WidthRequest="24" HeightRequest="24"/>
                                            </StackLayout>
                                            <Label Grid.Row="1" Grid.Column="1" Text="{Binding BrunataNoStr}" Style="{StaticResource small}" HorizontalOptions="Start" VerticalOptions="Center" />
                                            <Label Grid.Row="1" Grid.Column="3" Text="{Binding StatusStr}" Style="{StaticResource small}" HorizontalOptions="Start" VerticalOptions="Center" />
                                            <Label Grid.Row="1" Grid.Column="4" Text="{Binding AssigneeStr}" Style="{StaticResource small}" HorizontalOptions="Start" VerticalOptions="Center" />
                                        </Grid>
                                        
                                        <Label Opacity="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" 
                                                effect:LongPressedEffect.LongPressCommand="{Binding  Source={x:Reference LocationListViewOrders}, BindingContext.LocationLongTappedCommand}"  effect:LongPressedEffect.CommandParameter="{Binding .}"
                                                effect:LongPressedEffect.ClickCommand="{Binding  Source={x:Reference LocationListViewOrders}, BindingContext.LocationTappedCommand}">
                                            <Label.Effects>
                                                <effect:LongPressedEffect />
                                            </Label.Effects>
                                        </Label>
                                    </Grid>
                                </DataTemplate>
                            </CollectionView.ItemTemplate>
                        </CollectionView>
                    </StackLayout>
                    <StackLayout Grid.Row="1" IsVisible="{Binding BuildingOrdersAvailable}">
                        <Label Text="{extensions:Translate OrderlistPage_BuildingOrders}" Margin="0,5,0,0" HorizontalOptions="FillAndExpand" HorizontalTextAlignment="Center" Style="{StaticResource h4}" TextColor="{StaticResource brDarkGrey}" BackgroundColor="{StaticResource brBgColor}"/>
                        <c:SortableHeader SortCommand="{Binding OnBuildingSortCommand}" Selection="{Binding BuildingOrdersSortSelection}">
                            <c:SortableHeader.Columns>
                                <c:SortableColumn Width="75*" Text="{extensions:Translate General_BuildingNo}"/>
                                <c:SortableColumn Width="24" Text=""/>
                                <c:SortableColumn Width="138*" Text="{extensions:Translate General_Address}"/>
                                <c:SortableColumn Width="95*" Text="{extensions:Translate OrderlistPage_StartEnd}"/>
                                <c:SortableColumn Width="28" Text=""/>
                            </c:SortableHeader.Columns>
                        </c:SortableHeader>
                        <StackLayout IsVisible="{Binding IsBuildingDeleteVisible}" Orientation="Horizontal" Margin="16, 5, 16, 5" HorizontalOptions="StartAndExpand" MinimumHeightRequest="27" MinimumWidthRequest="360">
                            <Image Source="{Binding BuildingOrders, Converter={StaticResource toImageConverter}}">
                                <Image.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding BuildingMarkUnmarkDeleteImagesCommand}"/>
                                </Image.GestureRecognizers>
                            </Image>
                            <Label Text="{extensions:Translate OrderlistPage_SelectAll}" Margin="5,0,0,0" HorizontalOptions="Start" VerticalOptions="Center"/>
                        </StackLayout>
                        <CollectionView x:Name="ListViewBuildingOrders"
                          ItemsSource="{Binding BuildingOrders}"
                          VerticalOptions="Start">
                            <CollectionView.ItemTemplate>
                                <DataTemplate>
                                    <Grid>
                                        <Grid Margin="16, 0, 16, 0">
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="*"/>
                                                <RowDefinition Height="*"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="{Binding Source={x:Reference Name=OrderList}, Path=BindingContext.IsBuildingDeleteVisible, Converter={StaticResource VariableGridLengthConverter}, ConverterParameter=OrderColumn1}"/>
                                                <ColumnDefinition Width="{Binding Source={x:Reference Name=OrderList}, Path=BindingContext.IsBuildingDeleteVisible, Converter={StaticResource VariableGridLengthConverter}, ConverterParameter=OrderColumn2}"/>
                                                <ColumnDefinition Width="24"/>
                                                <ColumnDefinition Width="138*"/>
                                                <ColumnDefinition Width="95*"/>
                                                <ColumnDefinition Width="28"/>
                                            </Grid.ColumnDefinitions>
                                            <Image  Grid.Row="0" Grid.Column="0"  HorizontalOptions="Start" VerticalOptions="Start" Source="{Binding IsSetForDeletion, Converter={StaticResource toImageConverter}, ConverterParameter='CHECKBOX'}">
                                                <Image.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding Source={x:Reference ListViewBuildingOrders}, Path=BindingContext.BuildingDeleteImageCommand}" CommandParameter="{Binding .}"/>
                                                </Image.GestureRecognizers>
                                            </Image>
                                            <Label Grid.Row="0" Grid.Column="1" Margin="3, 0, 0, 0" Text="{Binding BuildingNo}" HorizontalOptions="Start" VerticalOptions="Start"/>
                                            <Image Grid.Row="0" Grid.Column="2"  HorizontalOptions="Start" VerticalOptions="Start" Source="icon_note_grey.png" IsVisible="{Binding HasNote}">
                                                <Image.GestureRecognizers>
                                                    <TapGestureRecognizer Command="{Binding Source={x:Reference ListViewBuildingOrders}, Path=BindingContext.OnBuildingNoteCommand}" CommandParameter="{Binding .}"/>
                                                </Image.GestureRecognizers>
                                            </Image>
                                            <StackLayout Grid.Row="0" Grid.Column="3"  Orientation="Vertical" VerticalOptions="Start" >
                                                <Label Text="{Binding BuildingStreet}" />
                                                <Label Text="{Binding BuildingPostalCode}" />
                                            </StackLayout>
                                            <StackLayout Grid.Row="0" Grid.Column="4" Orientation="Vertical" VerticalOptions="Start">
                                                <Label Text="{Binding VisitStartDateLocal, Converter={StaticResource toStringConverter}, ConverterParameter='DATETIME'}" />
                                                <Label Text="{Binding VisitEndDateLocal, Converter={StaticResource toStringConverter}, ConverterParameter='DATETIME'}" />
                                            </StackLayout>
                                            <StackLayout Grid.Row="0" Grid.Column="5" Orientation="Horizontal" HorizontalOptions="CenterAndExpand" VerticalOptions="Start" >
                                                <Image Source="icon_type_3_grey.png" IsVisible="{Binding IsHAOrder}" WidthRequest="24" HeightRequest="24"/>
                                                <Image Source="icon_type_2_grey.png" IsVisible="{Binding IsMOOrder}" WidthRequest="24" HeightRequest="24"/>
                                                <Image Source="icon_type_1_grey.png" IsVisible="{Binding IsFMOOrder}" WidthRequest="24" HeightRequest="24"/>
                                            </StackLayout>
                                            <Label Grid.Row="1" Grid.Column="3" Text="{Binding StatusStr}" Style="{StaticResource small}" HorizontalOptions="Start" VerticalOptions="Start" />
                                            <Label Grid.Row="1" Grid.Column="4" Text="{Binding AssigneeStr}"  Style="{StaticResource small}" HorizontalOptions="Start" VerticalOptions="Start" />
                                        </Grid>
                                        
                                        <Label Opacity="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" 
                                                   effect:LongPressedEffect.LongPressCommand="{Binding  Source={x:Reference ListViewBuildingOrders}, BindingContext.BuildingLongTappedCommand}"  effect:LongPressedEffect.CommandParameter="{Binding .}"
                                                   effect:LongPressedEffect.ClickCommand="{Binding  Source={x:Reference ListViewBuildingOrders}, BindingContext.BuildingTappedCommand}">
                                            <Label.Effects>
                                                <effect:LongPressedEffect />
                                            </Label.Effects>
                                        </Label>
                                    </Grid>
                                </DataTemplate>
                            </CollectionView.ItemTemplate>
                        </CollectionView>
                    </StackLayout>
                </Grid>
                <Button Image="icon_calendar_blue.png" Command="{Binding OnShiftToWeekViewCommand}" BackgroundColor="{StaticResource brBgColor}" VerticalOptions="Start" HorizontalOptions="End" Grid.Column="1" Margin="0" HeightRequest="35"/>
            </Grid>
            <ActivityIndicator IsRunning="{Binding Initializing}" IsVisible="{Binding Initializing}" Color="{StaticResource brBlue}" VerticalOptions="Center" MinimumHeightRequest="80" WidthRequest="48"/>
            <StackLayout IsVisible="{Binding IsAnyDeleteVisible, Converter={StaticResource toBoolConverter}, ConverterParameter='!'}" MinimumHeightRequest="80">
                <Grid ColumnSpacing="16" Margin="16,13,16,16">
                    <Button Command="{Binding LoadOrderCommand}" Text="{extensions:Translate OrderListPage_FetchOrders}" BackgroundColor="{StaticResource brBlue}" TextColor="{StaticResource brWhite}" HeightRequest="48"/>
                </Grid>
            </StackLayout>
            <StackLayout IsVisible="{Binding IsAnyDeleteVisible}" MinimumHeightRequest="80">
                <Grid ColumnSpacing="16" Margin="16,13,16,16">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>
                    <Button Grid.Column="0" Command="{Binding CancelDeleteOrdersCommand}" Text="{extensions:Translate General_Cancel}" BackgroundColor="{StaticResource brBlue}" TextColor="{StaticResource brWhite}" HeightRequest="48"/>
                    <Button Grid.Column="1" Command="{Binding DeleteOrdersCommand}" Text="{extensions:Translate OrderlistPage_DeleteOrC:\HT\Brunata.Handterminal\Views\GeneralFlow\OrderListPage.xaml.csders}" BackgroundColor="{StaticResource brRed}" TextColor="{StaticResource brWhite}" HeightRequest="48"/>
                </Grid>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>
</basePages:BasePage>

**Comment by jfversluis** [comment]
As far as I can tell this should be a similar structure to what you have in your XAML and it seems to work just fine. Could you please try this and add anything that I might have missed so it resembles your implementation better?

[Repro7097.zip](https://github.com/xamarin/Xamarin.Forms/files/3480600/Repro7097.zip)

**Comment by pskofod** [comment]
Hi Gerald.
Thanks for your fast answer. That's true in your setup it works. I also tried to make it even more similar to mine - and it still works.

One thing that is different for the two projects are the Nugets used. 
**In mine:**
    PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.1" 
    PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.1" 
    PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.1" 
    PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.1" 
    PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.1" 
**In yours is:**
    PackageReference Include="Xamarin.Android.Support.Core.Utils"      Version 28.0.0.1

I couldn't just change my project to Xamarin.Android.Support.Core.Utils it gave conflicts. But I tried to migrate to AndroidX, which works fine for Pre2 but still gives the same error for pre 3.

I'm uncertain of which step to take now.
Cheers
Peter

**Comment by PureWeen** [comment]
@pskofod 

- Can you try testing against the latest nightly?  https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

- If it's that specific XAML page causing issues can you
- Create a new Xamarin Forms project using the templates
- update to 4.2 pre 3
- Copy your XAML file into that
- Widdle down the extra parts of the XAML to recreate the issue?


I'm also pinging @StephaneDelcroix in case there's something that rings a bell with him and this issue

**Comment by PureWeen** [comment]
I whittled your sample down myself a bit and I'm able to compile the *OrderListPage* you created without any issue

I'm not able to run it in any useable way because of missing staticresources but even then I tried to remove all of them except what you referenced above and in that instance I was able to compile and run the application without any issues

**Comment by michaeldimoudis** [comment]
I have the same issue as @pskofod basically exact similar code is the culprit. Hope this is fixed soon :)

**Comment by StephaneDelcroix** [comment]
@michaeldimoudis please provide a reproduction project (self contained, a few xaml files only), and that'll speed up the process

**Comment by michaeldimoudis** [comment]
@StephaneDelcroix it's basically exactly the same code as the 2 zip files above, however I'll send another snippet of my issue. It crashes in other areas in my app with similar code too.
[crash issue 7097.xaml.zip](https://github.com/xamarin/Xamarin.Forms/files/3529299/crash.issue.7097.xaml.zip)

**Comment by timahrentlov** [comment]
Using 4.2 stable I'm getting an runtime exception whereby binding to x:Referenced elements on the same page is not found.

The error I'm getting is:
Xamarin.Forms.Xaml.XamlParseException
Position 54:10. Can not find the object referenced by `root`
for: 

Command="{Binding Source={x:Reference root}, Path=BindingContext.DeleteTimeCommand}"

where 'root' is the x:Name of the Page.

Downgrading to latest 4.1 solves the problem.

**Comment by MarMarIV** [comment]
I create small project with reproduced problem. Exception is thrown on Android and iOS. On UWP only blank items in CollectionView are displayed.

When i have only one page `MainPage : ContentPage`, it works. But when i add some inheritance to pages, exception is thrown (in example below)

[XamlBindingReferenceApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3532800/XamlBindingReferenceApp.zip)


Android exception:
`08-23 06:30:29.271 I/MonoDroid(22558): UNHANDLED EXCEPTION:
08-23 06:30:29.276 I/MonoDroid(22558): Xamarin.Forms.Xaml.XamlParseException: Position 28:29. Can not find the object referenced by `self`
08-23 06:30:29.276 I/MonoDroid(22558):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.50(intptr,intptr,intptr,int)
08-23 06:30:29.276 I/MonoDroid(22558):   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.50(intptr,intptr,intptr,int)
08-23 06:30:29.276 I/MonoDroid(22558):   at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a(intptr,intptr&,intptr,intptr,intptr,Java.Interop.JniArgumentValue*)
08-23 06:30:29.276 I/MonoDroid(22558):   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00073] in <23e57773773243b6853e76fc01957c33>:0 
08-23 06:30:29.276 I/MonoDroid(22558):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <23e57773773243b6853e76fc01957c33>:0 
08-23 06:30:29.276 I/MonoDroid(22558):   at Android.Support.V7.Widget.RecyclerView.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00079] in <7d32f6ecea2f48a59f0d551b445680b3>:0 
08-23 06:30:29.276 I/MonoDroid(22558):   at Xamarin.Forms.Platform.Android.ItemsViewRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\CollectionView\ItemsViewRenderer.cs:60 
08-23 06:30:29.276 I/MonoDroid(22558):   at Android.Support.V7.Widget.RecyclerView.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x00008] in <7d32f6ecea2f48a59f0d551b445680b3>:0 
08-23 06:30:29.276 I/MonoDroid(22558):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.42(intptr,intptr,bool,int,int,int,int)
**Xamarin.Forms.Xaml.XamlParseException:** 'Position 28:29. Can not find the object referenced by `self`'`


iOS exception:
`Xamarin.Forms.Xaml.XamlParseException: Position 28:29. Can not find the object referenced by `self`
  at Xamarin.Forms.Xaml.ReferenceExtension.ProvideValue (System.IServiceProvider serviceProvider) [0x000bf] in D:\a\1\s\Xamarin.Forms.Xaml\MarkupExtensions\ReferenceExtension.cs:42 
  at XamlBindingReferenceApp.MainPage+<InitializeComponent>_anonXamlCDataTemplate_1.LoadDataTemplate () [0x00204] in <c119108e167f478a8a3c1e853eae6a32>:0 
  at Xamarin.Forms.ElementTemplate.CreateContent () [0x00026] in D:\a\1\s\Xamarin.Forms.Core\ElementTemplate.cs:82 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.ApplyTemplateAndDataContext (Xamarin.Forms.Platform.iOS.TemplatedCell cell, Foundation.NSIndexPath indexPath) [0x00024] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:218 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.UpdateTemplatedCell (Xamarin.Forms.Platform.iOS.TemplatedCell cell, 
Foundation.NSIndexPath indexPath) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:191 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.GetCell (UIKit.UICollectionView collectionView, Foundation.NSIndexPath indexPath) [0x0003b] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:106 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.GetPrototype () [0x0005d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:305 
  at Xamarin.Forms.Platform.iOS.ItemsViewLayout.DetermineCellSize () [0x00025] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewLayout.cs:204 
  at Xamarin.Forms.Platform.iOS.ListViewLayout.ConstrainTo (CoreGraphics.CGSize size) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ListViewLayout.cs:16 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.ViewWillLayoutSubviews () [0x0000e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:151 
  at (wrapper
 managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at XamlBindingReferenceApp.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\MMarecek\source\repos\XamlBindingReferenceApp\XamlBindingReferenceApp\XamlBindingReferenceApp.iOS\Main.cs:17
2019-08-23 06:29:33.224301+0200 XamlBindingReferenceApp.iOS[48837:2120553] Unhandled managed exception: Position 28:29. Can not find the object referenced by `self` (Xamarin.Forms.Xaml.XamlParseException)
  at Xamarin.Forms.Xaml.ReferenceExtension.ProvideValue (System.IServ
iceProvider serviceProvider) [0x000bf] in D:\a\1\s\Xamarin.Forms.Xaml\MarkupExtensions\ReferenceExtension.cs:42 
  at XamlBindingReferenceApp.MainPage+<InitializeComponent>_anonXamlCDataTemplate_1.LoadDataTemplate () [0x00204] in <c119108e167f478a8a3c1e853eae6a32>:0 
  at Xamarin.Forms.ElementTemplate.CreateContent () [0x00026] in D:\a\1\s\Xamarin.Forms.Core\ElementTemplate.cs:82 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.ApplyTemplateAndDataContext (Xamarin.Forms.Platform.iOS.TemplatedCell cell, Foundation.NSIndexPath indexPath) [0x00024] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:218 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.UpdateTemplatedCell (Xamarin.Forms.Platform.iOS.TemplatedCell cell, Foundation.NSIndexPath indexPath) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:191 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.GetCell (UIKit.UICollectionView collectionView, Foundation.NSIndexPath indexPath) [0x000
3b] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:106 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.GetPrototype () [0x0005d] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:305 
  at Xamarin.Forms.Platform.iOS.ItemsViewLayout.DetermineCellSize () [0x00025] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewLayout.cs:204 
  at Xamarin.Forms.Platform.iOS.ListViewLayout.ConstrainTo (CoreGraphics.CGSize size) [0x0001e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ListViewLayout.cs:16 
  at Xamarin.Forms.Platform.iOS.ItemsViewController.ViewWillLayoutSubviews () [0x0000e] in D:\a\1\s\Xamarin.Forms.Platform.iOS\CollectionView\ItemsViewController.cs:151 
  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/sr
c/Xamarin.iOS/UIKit/UIApplication.cs:86 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.14.0.114/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
  at XamlBindingReferenceApp.iOS.Application.Main (System.String[] args) [0x00001] in C:\Users\MMarecek\source\repos\XamlBindingReferenceApp\XamlBindingReferenceApp\XamlBindingReferenceApp.iOS\Main.cs:17`

**Comment by StephaneDelcroix** [comment]
if this regression happened between -pre2 and -pre3, it's probably due to #7040

**Comment by psp589** [comment]
I have the same problem in Version="4.2.0.709249", was working on  Version="4.2.0.608146-pre1"
