### ISSUE TITLE
Entry not moving up when keyboard is shown

### ISSUE THREAD

**Issue by PaulAnderson02** [xamarin/Xamarin.Forms#7098]
### Description
In this sample Entry is loaded to a Syncfusion SfTabView and the Entry works fine with the first tab alone. The Entry added to other tabs has this issue. Entry gets behind the keyboard on other tabs in TabView

### Steps to Reproduce

1.  Run the sample.
2.  Switch to second tab.
3.  Tap the entry near to the bottom of the screen
4. Keyboard aapears above the Entry

### Expected Behavior

Entry should move above the keyboard

### Actual Behavior

Entry remains below the keyboard

### Basic Information

- Version with issue: All Xamarin Versions
- Last known good version: Nil
- IDE: VS 2017
- Platform Target Frameworks: 
  - Android: 6 and above
- Android Support Library Version: 25 and above

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3480810/App1.zip)

**Comment by jfversluis** [comment]
Hi @PaulAnderson02, thanks for the report.

Have you also tried with regular Forms controls? I see you are using SyncFusion controls which might be the cause of this and not so much Xamarin.Forms. Did you already check with them as well?

If I make a little reproduction sample with just tabs in Xamarin.Forms everything seems to work fine. Is there anything more that we can do to rule out this is not something cause by the plugins you have installed?

**Comment by PaulAnderson02** [comment]
Yes we tried. It occurs with Syncfusion SfTabView as it load only content views and it does not load pages. So adding two are three views and navigating the entry is not working correctly. Checked with the TabView source and how it is working for first tab alone.

**Comment by jfversluis** [comment]
Would it be possible to provide a reproduction without the SyncFusion controls then? Because I want to rule out that it has to do with that and I can't reproduce it with just Xamarin.Forms Controls.

Thanks!

**Comment by PaulAnderson02** [comment]
Sorry. But i dont find a similar architecture control in Xamarin.Forms controls to reproduce and only using SfTabView.

**Comment by jfversluis** [comment]
Ah sorry, I misunderstood your previous comment then. Did you already/also open a ticket with SyncFusion?

I'm not trying to pass this off as "not our problem" but I have the feeling that chances are that it is a bug on their side :)

**Comment by PaulAnderson02** [comment]
I have tried their side also and since it is working in one tab and not getting adjustted on other tabs with the same source code they not able to find the cause. May be debugging your side with entry and scroll may give any ideas

**Comment by PureWeen** [comment]
@PaulAnderson02 I think this is one we're still going to need to kick back to SyncFusion. If I take the content you've provided and nest them into our TabbedPage then it all works fine for me

```xaml
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="Xamarin.Forms.Sandbox.TabPage">
    <ContentPage Title="Tab 1">
        <StackLayout>
            <Entry Text="Entry 1" />
            <Entry Text="Entry 2" />
            <Entry Text="Entry 3" />
            <Entry Text="Entry 4" />
            <Entry Text="Entry 5" />
            <Entry Text="Entry 6" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <Editor AutoSize="TextChanges" Text="Editor" />
        </StackLayout>
    </ContentPage>
    <ContentPage Title="Tab 2">
        <StackLayout Margin="12">
            <Entry Text="Entry 1" />
            <Entry Text="Entry 2" />
            <Entry Text="Entry 3" />
            <Entry Text="Entry 4" />
            <Entry Text="Entry 5" />
            <Entry Text="Entry 6" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <Entry Text="Entry 7" />
            <!--  BUG: ENTRY does not move up with keyboard  -->
            <Editor AutoSize="TextChanges" Text="Editor" />
        </StackLayout>
    </ContentPage>  
</TabbedPage>
```

@DeepikaBalaSubramaniyan
