### ISSUE TITLE
How to display the Flyoutmenu from Right to Left

### ISSUE THREAD

**Issue by sylendra7** [xamarin/Xamarin.Forms#7099]
Creating Right to Left Flyoutmenu in Xamarin Forms 4.0

**Comment by jfversluis** [comment]
Hi @sylendra7, thanks for your question!

I don't think this is supported other than using our [RTL support](https://devblogs.microsoft.com/xamarin/right-to-left-localization-xamarin-forms/). There are some resources out there that might be better suited for this question like StackOverflow or the Xamarin forums.

If your intention was to propose this as a new feature, feel free to open this issue again or open a new one with a more extensive description on what you would expect of this feature.

Thanks!
