### ISSUE TITLE
Custom view is not aligned properly on resizing the native android view.[bug]

### ISSUE THREAD

**Issue by ashokkumar96** [xamarin/Xamarin.Forms#7103]
### Description

In our custom control, we are converting the Xamarin forms view to native Android view for providing custom view. We are facing alignment issue in resizing the converted native view. In our sample, we have been converting a Xamarin.forms view (i.e Frame with label as child, where label is aligned to the center of the frame) into Native view using Renderer. 

Whenever we change layout of the converted native view on a button click, **Frame is resized and aligned properly,relative to the change in layout value. However, label inside the Frame is not resized and aligned to the center of the Frame.** 

 We suspect that this is a frame work issue. Since we tried with the same layouts directly in xamarin forms and changed the layout in xamarin forms, Where Frame along with label, resized and aligned properly to the center of the Frame as expected.

Kindly find the sample below:

###Sample
[CustomView_Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3481196/CustomView_Sample.zip)

### Steps to Reproduce

1. Deploy the attached sample;
2. you can see the button and Rounded Frame with Label in center of it.
3. Click on the "ChangeLayout" button to reproduce the issue

### Expected Behavior

Label inside the Frame is not aligned to the center of the Frame, on resizing the native view.

### Actual Behavior
Label inside the Frame should aligned to the center of the Frame, on resizing the native view.

### Basic Information

-Version with issue: Xamarin 3.4
Platform Target Frameworks:
Android: 7.1
The issue is reproduced only in Xamarin.Forms Android platform.

### Screenshots
![Screenshot_20190808-161704 1](https://user-images.githubusercontent.com/49550346/62697433-4c9e9500-b9f8-11e9-851b-a1462710a4ca.png)

Could you please check with the above details and provide us with a possible solution for this.

**Comment by jfversluis** [comment]
Hey @ashokkumar96, thanks for your issue.

I'm not exactly sure what you mean here:

> We suspect that this is a frame work issue. Since we tried with the same layouts directly in xamarin forms and changed the layout in xamarin forms, Where Frame along with label, resized and aligned properly to the center of the Frame as expected.

Are you saying that when you do this with "pure" Xamarin.Forms and not dive into native views that this works?

My feeling is that when you start using native views directly you skip entire parts of Forms code that correctly update any child elements within that view. That is to be expected.

**Comment by ashokkumar96** [comment]
Hi @jfversluis ,
I can understand the point that you said in previous update, but we have been resizing the view (i.e view should be converted from Xamarin.Forms.View to Native View). Is there any possible solution to achieve this scenario?
Is the Renderer used for  "pure" Xamarin.Forms is same as that of  Renderer I have used for converting Xamarin.Forms.View into Native View?

**Comment by jfversluis** [comment]
For example [here](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/FastRenderers/FrameRenderer.cs#L197) in the Android FastRenderer for a Frame we go through all the children whenever the layout is updated to update the children accordingly. This code is not executed because you would be using an actual native view instead of going through Xamarin.Forms and its renderers. Because of that, you would have to account for that yourself now.

Does that make sense?

**Comment by samhouts** [comment]
@ashokkumar96  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ashokkumar96** [comment]
Hi @jfversluis ,
As the mentioned in your update, I could understand that converted Xamarin.Forms View cannot be resized accordingly as like normal Xamarin.Forms view.

Is there any possible solution that you could provide on your side to resize the converted Xamarin forms View as like Xamarin.Forms view resizing?
