### ISSUE TITLE
Frame HasShadow property not working in CollectionView

### ISSUE THREAD

**Issue by RawoofSharief** [xamarin/Xamarin.Forms#7115]
### Description
I have a **CollectionView which has a frame with HasShadow property,** the shadow is not applied and **Margin also not applied when using it in the ItemTemplate**. I have uses the latest **Xamarin.Forms 4.2.0.673161-pre3.**  

When the **same scenario is used in the Listview then it is working fine.** I have commented on the listview coding in the sample. Kindly check that also.

I have checked in android only. 

### Steps to Reproduce

1. Run the attached sample.
2. You can see that the shadow is not applied to the items.

### Expected Behavior

The shadow effect should be applied to the items.

### Actual Behavior

Shadow is not applied.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.673161-pre3.  
- Last known good version:
- IDE: VisualStudio 2017

### Screenshots

![Screenshot_20190809-122004](https://user-images.githubusercontent.com/39043330/62759873-321ff680-baa0-11e9-9ed0-276c46911834.png)

### Reproduction Link

[FrameIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3485105/FrameIssue.zip)

**Comment by jfversluis** [comment]
Hey @RawoofSharief 

I've taken a look at your code and it seems the shadow _is_ working, but you can't see it because of the way you built your layout. Try the following change in your code:

```
<DataTemplate>
                <StackLayout Padding="20">
                <Frame
                    BackgroundColor="White"
                    BorderColor="White"
                    CornerRadius="4"
                    HasShadow="True"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="FillAndExpand">
```

Notice how I took out the `Margin` on the `CollectionView` and added a `StackLayout` with a `Padding`. That way the `Frame` gets a chance to show as a whole instead of being clipped.

As you can see in your screenshot in the bottom right corner you can see a tiny bit of shadow peeping through.

Hope this helps. If not, please feel free to reopen the issue.

**Comment by RawoofSharief** [comment]
Hi @jfversluis ,

Given solution works, but which affects performance. Why should I use another layout to show the shadow effect?
It is working as expected when loading inside listview.

**Comment by jfversluis** [comment]
CollectionView != ListView. You can use them for the same purpose, but they do not necessarily behave the same. Apparently they do something different in terms of layout.

The solution I gave you is one of many, the only thing I wanted to make clear is that the shadow does work as intended, it's just hidden. There might be other options available that better suit your needs.

Hope this helps!

**Comment by eVakeel** [comment]
You don't have need to put an extra layout, you have to set your frame padding because due to wrong padding you can't be able to see shadow. @RawoofSharief .
Due to extra layouts obviously affects performance, scrolling and memory consuming issues.
