### ISSUE TITLE
[Bug] TranslateTo animation getting over container on iOS

### ISSUE THREAD

**Issue by Maxima078** [xamarin/Xamarin.Forms#7117]
### Description
On iOS VisualElement.TranslateTo move element over its container.
On Android the element is moved behind its container as expected.
### Steps to Reproduce

1. add an element inside a grid
2. apply a TranslateTo animation on this element

### Expected Behavior
Element should be moved behind the grid
### Actual Behavior
Element is moved in front of the grid
### Basic Information

- Version with issue: 4.1.0.673156

### Screenshots
iOS :
![image](https://user-images.githubusercontent.com/8363725/62767538-34c91e80-ba95-11e9-8f2b-732437217b27.png)

Android :
![Screenshot_2019-08-09-11-03-08-147_com xamarin basicanimation](https://user-images.githubusercontent.com/8363725/62767875-e2d4c880-ba95-11e9-9156-3e3aa5dd9e60.png)

### Reproduction Link
I modified the "basic animation" sample, you can try it in the "TRANSFORM ANIMATION" page.
[BasicAnimation.zip](https://github.com/xamarin/Xamarin.Forms/files/3485593/BasicAnimation.zip)

**Comment by jfversluis** [comment]
If you set the `IsClippedToBounds="True"` attribute on the Grid (with the green background) it shows the same bahavior on both platforms. This is just one of the things that has a different default value between Android and iOS I guess :)

I will close this for now, assuming that this was what you were looking for. If not, please reopen the issue.

**Comment by Maxima078** [comment]
Indeed you were right.

Thank  you
