### ISSUE TITLE
EntryTextColor doesn't change when IsEnabled set to false

### ISSUE THREAD

**Issue by KarthikRajaAKR** [xamarin/Xamarin.Forms#7119]
# Description
I am using Xamarin forms Entry, when I try to change TextColor of entry field it works fine but the same doesn't work when entry field is set IsEnabled to false.

Which is working fine in UWP platform and not working in Android and iOS.

Kindly share if there is any workaround to achieve my requirement.

### Steps to Reproduce

1. Run the sample attached below. 
2. In sample, note entry field IsEnabled is set to false and TextColor was mapped.
3. In view Entry TextColor not change it always displays in Gray.

### Expected Behavior
We want to change TextColor for entry in Disabled state.

### Actual Behavior
TextColor does not change as expected.

### Basic Information

- Version with issue: 3.4.0.1008975
- IDE: VS 2017
- Platform Target Frameworks: 
  - iOS:  11
  - Android: Android 8.1
  - UWP:  Working fine in UWP

### Screenshots
![image](https://user-images.githubusercontent.com/41435300/62770575-eded2000-bab8-11e9-9a68-cad1ee6fa715.png)

I have two entry field with same TextColor different IsEnabled. Disabled field color not mapped.

### Reproduction Link
[SampleProject.zip](https://github.com/xamarin/Xamarin.Forms/files/3485760/SampleProject.zip)

**Comment by jfversluis** [comment]
This is something that you could solve by using the [Visual State Manager](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager).

If you change you page to this, it works:

```
<StackLayout HorizontalOptions="CenterAndExpand"
                 VerticalOptions="Center">
        <Entry Text="Hello"
               IsEnabled="True"
               TextColor="Red"
               FontSize="Large" />
        <Entry Text="Hello"
               IsEnabled="False"
               TextColor="Red"
               FontSize="Large">
            <VisualStateManager.VisualStateGroups>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Disabled">
                        <VisualState.Setters>
                            <Setter Property="TextColor" Value="Red" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateManager.VisualStateGroups>
        </Entry>
    </StackLayout>
```

If this is not what you meant, please feel free to reopen this issue.

**Comment by KarthikRajaAKR** [comment]
Hi Team,

Is there any way to achieve the same in code behind.

Regards,
Karthik Raja A

**Comment by jfversluis** [comment]
Hi @KarthikRajaAKR 

You probably want to look at [this part of the documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager#defining-your-own-visual-states).

Although there is still some XAML on the top, you can also see how `GoToState` is called from code. That is something you can do as well for your own controls.

Good luck!

**Comment by Ganeshamoorthy10** [comment]
Hi @jfversluis,

In my scenario, I am not using Xaml part **Entry** is added in code behind only. I need to change Entry Text color when IsEnabled is False, also I need all the behaviors when IsEnabled is False like restriction of touch, focus and editing of entry.

`            var stackLayout = new StackLayout();`
`            stackLayout.Children.Add(new Entry()`            
`            {`
`                Text = "Hello",`
`                IsEnabled = false,`
`                TextColor = Color.Red,`
`            });`
`            this.Content = stackLayout;`

Could you please provide a solution for this?
