### ISSUE TITLE
[Question] Fullscreen element on device rotation

### ISSUE THREAD

**Issue by nativenolde** [xamarin/Xamarin.Forms#7120]
Is it possible to show a specific element "fullscreen" over the entire page when the device rotates?

Let's assume we have a form to record a order with some different elements, pickers, editors, etc, and at the end a signature pad. After recording all the required information, somebody has to sign the order... therefore the the device will be rotated, to have a "fullscreen" signature pad.

Thanks in advance for any assistance

**Comment by PureWeen** [comment]
@nativenolde There's no out of the box way to do what you're indicating. You would need to detect the device orientation change

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=windows#reacting-to-changes-in-orientation

And then based on that orientation change the display of your elements. For example, use an absolute layout to display the Sign Order element on top of everything.

That's the path I would first pursue for trying to achieve what you are describing. If you're still having issues I'd recommend putting together what you've tried so far and asking on StackOverflow.
