### ISSUE TITLE
[Enhancement] Add RemoveFromSuperview method to View class

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#7126]
## Summary
Simplify removing Views from screen

## API Changes

new method in View.cs

```csharp
        public void RemoveFromSuperview() {
            switch(Parent) {
            case ContentPage page:
                page.Content = null;
                break;
            case ContentView view:
                view.Content = null;
                break;
            case ScrollView scroll:
                scroll.Content = null;
                break;
            case Layout<View> layout:
                layout.Children.Remove(this);
                break;
            }
        }
```

## Intended Use Case
```x:Name="button"```
...

[BEFORE]
```csharp
(button.Parent as Layout<Children>)?.Children.Remove(button);
```
[AFTER]
```csharp
button.RemoveFromSuperview();
```

And if I decide to wrap button with ContentView my code won't change

**Comment by AndreiMisiukevich** [comment]
if this idea may live, i can prepare PR

**Comment by PureWeen** [comment]
@AndreiMisiukevich are there scenarios that are part of our existing code base that you would convert over to this new method? or is this something that's just useful for other developers? 

Just looking to expand on the use case a little bit before we decide to add something like this to the Core

**Comment by AndreiMisiukevich** [comment]
@PureWeen i consider it as something just useful for other developers.
Like this https://github.com/xamarin/Xamarin.Forms/blob/506acee89fdd4fae4022d0239f7138021adcfc4b/Xamarin.Forms.Platform.Android/ViewExtensions.cs#L21-L28

**Comment by AndreiMisiukevich** [comment]
@PureWeen or you think that making view invisible (IsVisible = false) is always better approach, than removing it from super view?

**Comment by AndreiMisiukevich** [comment]
I think it is not quite important to be added to the XF box
