### ISSUE TITLE
[Enhancement] Add platform specific property to set the iOS UITabBar Translucent property to false

### ISSUE THREAD

**Issue by mduchev** [xamarin/Xamarin.Forms#7135]
### Description
When we set the BackgroundImageSource to a page that is inside a TabbedPage, the tab's colors (background color and unselected color) are shifted a bit, meaning that the actual colors are not represented correctly. This happens only for iOS. On Android, the colors are fine.

### Steps to Reproduce
1. Open the solution DemoImageOpacityIssue
2. Run the project and make a screenshot of the MainPage. 
3. Inspect the screenshot and confirm that the colors are 1:1 with the ones that are set in code (The color is in MainPage.xaml and are #f7f7f7 for BarBackgroundColor property). 
4. Uncomment the 14th line in FirstPage.xaml.cs, which is simply setting a page background. 
5. Make a screenshot again and inspect the colors. 

Notes: 
The selection color, if we set any, doesn't change.
Also, it doesn't matter if the BackgroundImageSource propery is set from the xaml, or from the code-behind.
We are using the default deselected color, but any custom set color will be changed also.

### Expected Behavior
The second screenshot should have the exact same colors as in the first screenshot (as they are set in the code)

### Actual Behavior
The colors are not the ones that we set in code.
The colors should be #f7f7f7 for bar background and #a1a1a1 for unselected icon, but the actual colors, when we have a background image, are #f5f5f5 for bar background and #a0a0a0 for unselected icon.

### Basic Information

- Version with issue: Latest stable - 4.1.0.673156, but it also happens with the latest pre-release - 4.2.0.673161-pre3
- Last known good version: N/A
- IDE: Visual Studio Enterprise 2019 16.2.1 (windows)
- Platform Target Frameworks: 
  - iOS:  12.14.0.114
- Nuget Packages: N/A
- Affected Devices: Tested with iPhone 7 Plus and iPhone X, but it should happen on all iOS devices

### Screenshots
![normal](https://user-images.githubusercontent.com/8217099/62924680-4a05bc00-bdb9-11e9-810d-d07c4a2269de.PNG)
![shifted](https://user-images.githubusercontent.com/8217099/62924685-4d994300-bdb9-11e9-94b4-b179f7987dcd.PNG)

### Reproduction Link
[DemoImageOpacityIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3495912/DemoImageOpacityIssue.zip)

**Comment by PureWeen** [comment]
@mduchev I think what you're seeing here is the fact that the UITabBar is Translucent so you are seeing a blend of the background and the UITabBar itself

If you take your background image and remove the bottom half so none of it goes behind the UITabBar you'll see that the colors are now the same

One way you can workaround this is to use a custom renderer 

```C#

using DemoImageOpacityIssue.iOS;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(TabbedPage), typeof(CustomTabBarRenderer))]
namespace DemoImageOpacityIssue.iOS
{
    public class CustomTabBarRenderer : TabbedRenderer
    {


        public override void ViewWillLayoutSubviews()
        {
            base.ViewWillLayoutSubviews();
            TabBar.Translucent = false;
        }

    }
}
```

I've modified this Issue to adding a platform specific property to set Translucent from TabbedPafe for iOS
