### ISSUE TITLE
[Bug] Using Xcode 11 and latest previews to support iOS 13 dark mode causes ViewCell within TableView to have the wrong background color

### ISSUE THREAD

**Issue by SebastianKruseWago** [xamarin/Xamarin.Forms#7136]
### Description

When using Xcode 11, the latest Xamarin.iOS preview and the latest VS preview, ViewCell's still appear in white while the device is running in dark mode. That is not the expected behavior from the device and there is no way to set the background color of the cell. 

### Steps to Reproduce

1. Compile with Xcode 11 / Xamarin.iOS Preview
2. Use dark mode on the device

### Expected Behavior

Cells (and all other "native" controls) should appear in the proper theme of the OS.

### Actual Behavior

Everything stays default light theme. 

### Basic Information

- Version with issue: Preview
- Last known good version: None
- Platform Target Frameworks: 
  - iOS:  Preview for iOS 13

**Comment by jfversluis** [comment]
Hi @SebastianKruseWago thanks for reporting!

We have this new dark mode on the radar and are looking to support it.
As for the actual scenario you mentioned: you should be able to set the background on the ListView and work with that. In addition, you could set the ListView background to transparent and give your cells a background through a layout in there.

There is also a PR (#4867) for the background colors on cells which you might use when it's merged. 

Some options you might be able to use as a workaround while we work on the support.

**Comment by SebastianKruseWago** [comment]
@jfversluis In this case I use a TableView, because it is my settings page. Does it work the same as with ListViews? Any other list within my app uses FlowListView plugin with custom cells anyway.

**Comment by jfversluis** [comment]
The TableView should be pretty similar, so yes :)

**Comment by Sebastian1989101** [comment]
@jfversluis Using this method (setting the BackgroundColor) won't create the same result as it should. In the native TableView, the background is pure black (#000000) while each cell has a slight gray color (#1c1c1e). Setting it to the TableView in Forms would create a complete same color version. Also it would ruin the light theme because it would override the gray background and white cell background.

**Comment by jfversluis** [comment]
@Sebastian1989101 don't get me wrong, we should and we are implementing the necessary bits to support Dark Mode. I'm just trying to point out some alternatives that you could look into today.

**Comment by PureWeen** [comment]
I'm closing this for now

We have a set of internal specs that we are going to publish soon that will embody all the dark mode work to be done and will cover the issue described here

**Comment by rohitvipin** [comment]
The issue related to the table view seems not yet fixed. 
is there anything related to fixed that has been done on this?
