### ISSUE TITLE
[Bug] Unable to compile Xamarin forms project after upgrading VS2019

### ISSUE THREAD

**Issue by ajay-dhiman** [xamarin/Xamarin.Forms#7137]
**Error Message**:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not compile the file(s) '/Users/MyUserName/Library/Caches/Xamarin/mtbs/builds/AutomotiveLynk.Mobile.iOS/7ee54f39be4f4d961cdeaaeb4ab07215/obj/iPhone/Debug/mtouch-cache/armv7/ServiceStack.Text.dll.s'. Please file a bug report at http://bugzilla.xamarin.com	AutomotiveLynk.Mobile.iOS		

**Log File Attached :**	
[logs.txt](https://github.com/xamarin/Xamarin.Forms/files/3496171/logs.txt)

**IDE Info** :

Microsoft Visual Studio Professional 2017 
Version 15.9.14
VisualStudio.15.Release/15.9.14+28307.770
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Professional

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

ServiceStackVS   2.0.1
Templates and tools for use with the ServiceStack framework.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by PureWeen** [comment]
@ajay-dhiman can you attach a minimal sample please that compiles in VS 2017 but not VS 2019?

**Comment by ajay-dhiman** [comment]
Hi thanks for reply.

The sample projected is attached.

The issue is. This project is compiling properly on Mac (Vs2019) but not on Windows (Vs2019). IDE info is as followed.

Mac XCode v10.3 (10G8)

Microsoft Visual Studio Enterprise 2019
Version 16.2.2
VisualStudio.16.Release/16.2.2+29209.62
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.2.0.91 (d16-2@2983aebeb)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.2.0.375 (remotes/origin/d16-2@357d38ef4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.3.117 (59a59e8)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.4.1.0 (d16-2/ebd65c9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-02@e6f5369c2d2
    Java.Interop: xamarin/java.interop/d16-2@d64ada5
    LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

Xamarin.iOS and Xamarin.Mac SDK   12.14.0.114 (c669116)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.


[Grial-Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/3500281/Grial-Sample.zip)

**Comment by PureWeen** [comment]
@ajay-dhiman Can you remove the Grial dependencies and upload?  It looks like the issue is with ServiceStack so that should still reproduce the issue

**Comment by ajay-dhiman** [comment]
@PureWeen 

I tried with removing Grial dependency and the issue is still same. 

Here is the sample project attached.
[SampleApp1.zip](https://github.com/xamarin/Xamarin.Forms/files/3508861/SampleApp1.zip)

**Comment by ajay-dhiman** [comment]
Here is an observation as well. If i change the Architecture from (ARMv7 + ARM64) to ARM64 only then the project started compiling on Windows as well.

**Comment by PureWeen** [comment]
Hm I was able to compile *SampleApp1.zip* without any issues on VS 16.2.2 

Does this happen when you are trying to run the application ? Are you in Release configuration or Debug? 

Did you try removing your obj/bin directories on your project before trying to compile on vs2019 so that it's a fresh project?

**Comment by ajay-dhiman** [comment]
@PureWeen 
Yes this happens when i run the application on debug.

debug/release works perfect on emulator.
Release works on device but when i debug app on device then it throws the same exception.

Yes i tried all the ways of cleaning, removing obj/bin, reinstalling all the packages.

**Comment by ajay-dhiman** [comment]
@PureWeen 
Are you facing the same issue while debugging on device ?

**Comment by ajay-dhiman** [comment]
@PureWeen @samhouts 

There are new update from VS 

Microsoft Visual Studio Enterprise 2019
Version 16.2.3
VisualStudio.16.Release/16.2.3+29215.179

I update the VS and the issue is still same.

Any updates from you side ?

**Comment by PureWeen** [comment]
@ajay-dhiman 

> Here is an observation as well. If i change the Architecture from (ARMv7 + ARM64) to ARM64 only then the project started compiling on Windows as well.

I ran into this issue as well and I'm pretty sure this has to do with ServiceStack being too large. I changed the linker to Full and then was able to compile

> Are you facing the same issue while debugging on device ?

I was able to deploy your sample to an ipad just fine

Can you try setting the linker behavior to "Link All" and see if that fixes it for you?

**Comment by samhouts** [comment]
@ajay-dhiman  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
