### ISSUE TITLE
MenuItem with datatemplate white space render for iOS but work normally on Android

### ISSUE THREAD

**Issue by SoHighKH** [xamarin/Xamarin.Forms#7140]
### Description

I create a menuitem of separator by using code below:

```
<MenuItem>
    <Shell.MenuItemTemplate>
        <DataTemplate>
            <StackLayout HeightRequest="1">
                <BoxView HeightRequest="1" Color="LightGray" Margin="5,0,5,0"/>
            </StackLayout>
        </DataTemplate>
    </Shell.MenuItemTemplate>
</MenuItem>
```
I add above code in between creation of menu item to display separator kind of control. The way xamarin render the menu item is different from Android to iOS. Android make right render where iOS leave blank space below the separator.

![iOS](https://user-images.githubusercontent.com/37999499/62944776-fb374100-be0f-11e9-817b-307b377ebe4e.PNG)
iOS

![android](https://user-images.githubusercontent.com/37999499/62944793-068a6c80-be10-11e9-80a7-9b6cabbe88fc.jpg)
Android

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  latest
  - Android: latest
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@SoHighKH  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@SoHighKH  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
