### ISSUE TITLE
VisualElementExtensions.cs iOS is Internal. Can it be Public?

### ISSUE THREAD

**Issue by v-haroha** [xamarin/Xamarin.Forms#7142]
## Summary
VisualElementExtensions for iOS is set to Internal but on the other platforms it is Public. Can we change that?

## API Changes

internal static class VisualElementExtensions

e.g.

internal static class VisualElementExtensions to
public static class VisualElementExtensions

## Intended Use Case
I found that i wanted to use the GetRenderer Extension method but was unable to. Luckily the Plathform.GetRenderer(self) is public, but it would be nice if iOS matched Android/UWP.

**Comment by jsuarezruiz** [comment]
@v-haroha The PR is available https://github.com/xamarin/Xamarin.Forms/pull/7144
Thanks for the feedback!.

**Comment by v-haroha** [comment]
that is some quick turnaround, Thanks!
