### ISSUE TITLE
[Enhancement] ListView and Collection view - Scroll direction

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#7146]
It would be great if an event was thrown in the ListView and CollectionView when scrolling - which would indicate the direction of the scroll and possibly the delta from the last scroll. or the current scroll position.

``` cs
var list = new ListView();
list.Scrolled += (object sender, ScrolledEventArgs e) => {
    label.Text = "Position: " + e.ScrollX + " x " + e.ScrollY;
};
```

**Comment by PureWeen** [comment]
@KSemenenko CollectionView already has this

https://github.com/xamarin/Xamarin.Forms/blob/88577eac76e5a20fe1415ed0e67ac3e3d97bdd21/Xamarin.Forms.Core/Items/ItemsViewScrolledEventArgs.cs

And there's already an issue for the ListView part https://github.com/xamarin/Xamarin.Forms/issues/4323

**Comment by KSemenenko** [comment]
#7157
