### ISSUE TITLE
[Bug] Xamarin Shell Stops rendering Font Icons Properly in Certain Circumstances

### ISSUE THREAD

**Issue by DamienDoumer** [xamarin/Xamarin.Forms#7155]
#6772 # Description

Xamarin.Forms stops rendering font icons of the same font family as that of flyout icons.

### Steps to Reproduce

1. Add font icons to your Xamarin.Forms "Shell" app
2. Add font icons to any page in the app
3. At this stage, the font icons render normally if they were added properly
4. Add FlyoutItems and to these items, add FlyoutIcons "FontImageSource" with the same font family as that of the icons you added to your page in the previous step.

### Expected Behavior

The Font icons should render normally in the flyout item icons, and in the pages of your application or in controls.

### Actual Behavior

The flyout icons will not render in the pages of your app or in controls, but it you set the font family of the flyout icons to a font which is different from that of the icons in your page, the icons which couldn't render previously will start rendering again.

### Basic Information

- Version with issue: 4.0, 4.1
- Last known good version: Versions without the shell
- IDE: Visualstudio any version 
- Platform Target Frameworks: 
  - Android: 8.1, 9.0
- Nuget Packages: Xamarin.Forms 4.1.0.581479
- Affected Devices: Nexus 5X, Honor 9 Lite, Pixel XL

### Screenshots

![material_bug](https://user-images.githubusercontent.com/16731017/63002661-539d2b80-be6e-11e9-992e-cc236cb811e7.png)
![bootstrap_bug](https://user-images.githubusercontent.com/16731017/63002693-67e12880-be6e-11e9-85e5-c8bca6647a79.png)
![material_example](https://user-images.githubusercontent.com/16731017/63002741-821b0680-be6e-11e9-9cbd-d709c7e98c0d.png)

### Reproduction Link
I made a demo app with the reproduction of the bug included: https://github.com/DamienDoumer/XamarinFormsWebFontsRenderingBug

**Comment by wagenheimer** [comment]
I have the exact same problem! And I'm desperately trying to find a workaround for this! 

If I use it as a FontImage Markup everything works as expected. But I could not replace every label where I'm using FontAwesome with an Image. It needs to works correctly on labels all the time.

**Comment by jfversluis** [comment]
@DamienDoumer did you also try this on iOS? Does it also happen there? Or just Android?

**Comment by DamienDoumer** [comment]
No, it doesn't occur on iOS.
I tried and everything was fine.

Le ven. 16 août 2019 à 15:34, Gerald Versluis <notifications@github.com> a
écrit :

**Comment by jfversluis** [comment]
I've testing with the v4.2 stable package and the reproduction project now does not show this issue any longer. I will close this issue, @DamienDoumer if you see anything different, please feel free to comment and reopen.

Thanks!

**Comment by DamienDoumer** [comment]
@jfversluis  This issue doesn't appear on 4.2, I'll leave it closed. Thanks for the reminder.

**Comment by jfversluis** [comment]
@DamienDoumer glad that it's fixed! Happy developing!
