### ISSUE TITLE
[Bug] UWP SearchBar not visible if you set a WidthRequest property for another platform

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#7156]
### Description
The SearchBar control is not visible in UWP if you set something like a WidthRequest for another platform (iOS on my example). 

### Steps to Reproduce

1. Add the following content to any page:
```
    <StackLayout Padding="15" Spacing="20">

        <Label FontSize="Medium" Text="This is OK:" />
        <SearchBar />

        <Label FontSize="Medium" Text="This is broken:" />
        <SearchBar WidthRequest="{OnPlatform iOS=10}" />

        <Label FontSize="Medium" Text="This is also broken:" />
        <SearchBar>
            <SearchBar.WidthRequest>
                <OnPlatform x:TypeArguments="x:Double">
                    <On Platform="iOS" Value="10" />
                </OnPlatform>
            </SearchBar.WidthRequest>
        </SearchBar>
    </StackLayout>
```

### Expected Behavior
The three search bars are visible in the UWP app.

### Actual Behavior
Only the first one is visible.

### Basic Information
Change the affected search bars to have a UWP setting for WidthRequest. When you run the app, the search bars will be visible and will take up all available space. You can also go around the issue by setting a HeightRequest on the search bar.
```
    <StackLayout Padding="15" Spacing="20">

        <Label FontSize="Medium" Text="This is OK:" />
        <SearchBar />

        <Label FontSize="Medium" Text="This is OK with a workaround:" />
        <SearchBar WidthRequest="{OnPlatform iOS=10, UWP=10}" />

        <Label FontSize="Medium" Text="This is OK with another workaround:" />
        <SearchBar WidthRequest="{OnPlatform iOS=10}" HeightRequest="100" />

        <Label FontSize="Medium" Text="This is OK with a workaround :" />
        <SearchBar>
            <SearchBar.WidthRequest>
                <OnPlatform x:TypeArguments="x:Double">
                    <On Platform="iOS" Value="10" />
                    <On Platform="UWP" Value="10" />
                </OnPlatform>
            </SearchBar.WidthRequest>
        </SearchBar>
    </StackLayout>
```

- Version with issue: Every version I've tried from 3.5.0 up to 4.2.0 preview 3
- Last known good version: older versions didn't support OnPlatform
- IDE: VS 2019 16.2.1
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: n/a
  - UWP:  18362 

### Screenshots

![image](https://user-images.githubusercontent.com/31066938/63005048-a5948000-be73-11e9-9b9f-92183dffd64a.png)

With workaround:
![image](https://user-images.githubusercontent.com/31066938/63005472-8b0ed680-be74-11e9-862f-e8e7122a6d46.png)

### Reproduction Link
Just use the above code in any sample project.

**Comment by PureWeen** [comment]
It looks like when you use OnPlatform it will cause the rest of the platforms to get set to the default(T) of the bindable property. 

The other work around for this one would be to specify the BindableProperty default on the platform

```
<SearchBar WidthRequest="{OnPlatform iOS=10, Default=-1}" />
```

Which will cause it to act as it should if you didn't specify the WidthRequest for those other platforms

I'm not sure if this is by design or not but it seems like a bug

**Comment by StephaneDelcroix** [comment]
@PureWeen we can trace the root of the OnPlatform markup back to Device.OnPlatform on the very first version of Forms, and at that time we thought iOS would be a good default.

It's "by design", but I think it's clearly a bug. Fixing it will be a breaking change but we can take a risk there...

**Comment by StephaneDelcroix** [comment]
oh, it's not even a "default to iOS" in this case. it's a "use default(int) by default", where it should default to BP.DefaultValue
