### ISSUE TITLE
Shell Bottom Navigation Bar Rendering Issue

### ISSUE THREAD

**Issue by Nullstr1ng** [xamarin/Xamarin.Forms#7160]
### Description
A top portion of the Shell bottom navigation bar appears to be broken when deployed using VS2019 16.3 Preview 1.0 and 2.0. It also appears broken with deployed in VS2017, but only in RELEASE configuration.

I am not using any custom renderer, in face, I only have 3 buttons in it. 

Here's how it exactly looks in my actual device and in emulators. 

Xiaomi Redmi 5 Plus | Android 8.1 API 27 | VS2019 Prev 2 | Target Ver API 28
![image](https://user-images.githubusercontent.com/260633/63041322-2c8c3b80-befa-11e9-9f4c-2773cfd66988.png)
![image](https://user-images.githubusercontent.com/260633/63041348-3b72ee00-befa-11e9-8ab6-50d8539e8137.png)

Genymotion | Android 8.0 API 26 | VS2019 Prev 2 | Targer Ver API 28
![image](https://user-images.githubusercontent.com/260633/63041753-23e83500-befb-11e9-89ee-edd53771d897.png)
another example here
![image](https://user-images.githubusercontent.com/260633/63041784-38c4c880-befb-11e9-8784-28ff2864c038.png)
this is where I navigate to a page, TabBarIsVisible="False" and moving out from that page and that's how it looks like.

### Steps to Reproduce
1. Well probably have a Shell app with 3 buttons on bottom navigation bars, have some 3 pages.
2. Set the Compile using Android version to 9.0
3. Target Android Version to 9.0 API 28
4. Have some Android 8.1 API 27 phone.

### Expected Behavior
A clean slick bottom navigation bar.

### Actual Behavior
1. Sometimes flickering when just touching the bar
2. portion of that bar is broken.

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0618606
- Last known good version: n/a
- IDE: Visual Studio 2019 Prev 1 and 2
- Platform Target Frameworks: 
  - Android: Android 8.1
- Nuget Packages:
- Affected Devices:

### Screenshots
(check on top)

**Comment by Nullstr1ng** [comment]
ok here's the reproduction of the bug plus some findings with what's working and what's not.
https://github.com/Nullstr1ng/XamarinFormsRenderingIssue

hope this helps

**Comment by PureWeen** [comment]
@Nullstr1ng I noticed that if you set the BackgroundColor using a DynamicStyle it appears to work

```XAML
BackgroundColor="{DynamicResource DefaultButtonColor}"
```

Which doesn't seem like it should be a requirement for setting the BackgroundColor in this manner. 

I've assigned it to @StephaneDelcroix for now to get his impression
