### ISSUE TITLE
[Bug] improved observablecollection with system.reactive. a lot of collectionchanges. a reset is sent and listview scrolls to the top

### ISSUE THREAD

**Issue by BrayanKhosravian** [xamarin/Xamarin.Forms#7167]
### Description
when improving the observablecollection using system.reactive to trigger a reset event when a lot of changes happen to the list, the listview scrolls to the top in uwp and ios.
i think this issue is located in the listviewrenderers of uwp and ios.

When additional information is needed please ping me so i can explain the problem more clearly.

### Steps to Reproduce

1. clone the repository: https://github.com/BrayanKhosravian/Reset_causes_scrolltotop
2. set uwp as startup-project
3. run the app
4. press the button `AddRangeCommand`
5. scroll to the middle of the listview
6. press the button `AddRangeCommand` again
7. the listview scrolls to the top

### Expected Behavior
as a lot of items are being added to the collection, the listview should not scroll to the top even when a reset is triggered. this does not happen on android.

### Actual Behavior
when adding a lot of items and a reset event is triggered the listview scrolls to the top

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0673156
- Last known good version: -
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1  
  - UWP:  1809 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.1.0673156 and System.Reactive 4.1.6
- Affected Devices: 

### Screenshots
![scroll-to-top](https://user-images.githubusercontent.com/35541212/63105758-c1864780-bf81-11e9-827a-adf8a02812bd.gif)

### Reproduction Link
https://github.com/BrayanKhosravian/Reset_causes_scrolltotop

**Comment by PureWeen** [comment]
@BrayanKhosravian I only observed the issue you are talking about on UWP not iOS or Android

Have you tested this scenario with CollectionView by chance?

**Comment by BrayanKhosravian** [comment]
Thank you for the response.
Yes this works like charm on android. Well tbh i had an similar issue with ios but maybe the issue is caused by something else. I didnt test this repositor oon ios as i dont have a mac for testing. 

I didnt use collectionview at all. But i can create a seperate branch or project which uses the collectionview if it helps fixing the problem. 

Im trying to solve the issue e as well. I copied the listviewrenderer of uwp and im using it as renderer. I think the problem is located in the oncollectionchanged of the listviewrenderer which recreates the list when a reset is sent. 

Oh and what does the label e/4 mean? Is there a doc to read about the labels?

**Comment by BrayanKhosravian** [comment]
@bruzkovsky

**Comment by BrayanKhosravian** [comment]
i tried the test project using ios and it seems that it works.
maybe the bug i discovered in ios was caused by grouping. but thats just a guess and does not depend on this issue atm.

**Comment by BrayanKhosravian** [comment]
i spent a few hours because it was not able to hit breakpoints in `Xamarin.Forms.Internals.TemplatedItemsList` which is actually located in the folder `Xamarin.Forms.Core`.

i created a branch from the master with the issue and set up a view, vm, and the "ImprovedObservableCollection". it was not able to hit breakpoints in the class i mentioned above.
the breakpoints turned white while debugging. 

i tried to use vs clean+build and rebuild but that didnt help.
i solved the issue by running a power shell cmd which force deletes all bin+obj folders recursively.
the cmd: `Get-ChildItem .\ -include bin,obj -Recurse | foreach ($_) { remove-item $_.fullname -Force -Recurse }`

i think its a good thing to mention that as others may face the same issue.

**Comment by BrayanKhosravian** [comment]
as this would be my first contribution to xamarin.forms, i would like to get a feedback of the solutions which i try to implement before waisting too much time in something which would not get accepted.
sincerely.

what im trying right now to fix the issue:

- im trying to fix the issue by adding the newitems/olditems to the `NotifyCollectionChangedEventArgs` in Xamarin.Forms.Internals.TemplatedItemsList` when a reset is triggered in `Xamarin.Forms.Platform.UWP.ListViewRenderer.OnCollectionChanged`. from there i can just add the newitems/olditems to the `_collection` only when a `NotifyCollectionChangedAction.Reset` is triggered.

- plan-b be would be to solve the issue by implementig a feature like a `Collectionchanging` and get the items in `Xamarin.Forms.ITemplatedItemsList` and its concrete class.
So i could obtain the new items on collectionchanging in the `Xamarin.Forms.Platform.UWP.ListViewRenderer` and save them to a private filed and on collectionchanged i could add them to the `_collection`. (this may cuase some sync problems but im not sure and i hope that my first solution will work)


What i already tried to fix the issue:

- in `Xamarin.Forms.Platform.UWP.ListViewRenderer.OnCollectionChanged` i tried to create a diff with the listview obtained from the `sender` and the `_collection`. this seemed to work but caused another issue because of hash comparison. when the user would want to explicitly add the same item again to the listview it wont be added because of the hashes. so this is no solution.


[this is a workaround]
- i implemented a scrollto after the collection changed. but when its expensive to create a collection then the scrolling takes a while till it finishes. this means that i have to wait till the collection is created before i can scroll to the last visible item. thats a terrible workaround imo.

[this is a workaround]
- implemented a similar "scrollto" in a custom renderer but the result was the same. i just got the scrollviewer from the listview and used scrollto.

**Comment by samhouts** [comment]
closed by #7279

**Comment by BrayanKhosravian** [comment]
I have just noticed that this error is also present in the collectionview.
Had to test this because we might switch to the collectionview in the feature.

Should i create a new issue or should this be reopened or cloned?

**Comment by hartez** [comment]
@BrayanKhosravian New issue. Thanks!
