### ISSUE TITLE
[Enhancement] Label Autofit Font

### ISSUE THREAD

**Issue by Codelisk** [xamarin/Xamarin.Forms#7176]
## Summary
An autosize option to make the Label adjust its font for the available width.

e.g.

A simple boolean AutoFit would do the job.

    var label = new Label ();
    label.AutoFit = true; // new API

In Ios i already discovered there is an option called AdjustsFontSizeToFitWidth.
In Android I have also already seen the attribute autoSizeTextType. (Which may have only been available since Android 8 ?)

**Comment by GiampaoloGabba** [comment]
The Support Library 26.0 provides full support to the autosizing TextView feature on devices running Android 4.0 and up (API14): https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview.

So, if we are ok with this, is not a difficult task. However, If we want to support older android we need to do some calculations.

Btw considering that now Android is supporting officialy this feature, we shouldnt have a platform specific only for iOS: i propose to implement the Android native feature and integrate everything in the Label Renderers, getting rid of the platform specific.

I'm unsure if we need to support API<14, in this case users can attach an effect or create a custom renderer. Supporting this with custom code can degrade label performance (as seen with Effects/Custom Renderers spread over the internet)

**Comment by hudaIT** [comment]
> The Support Library 26.0 provides full support to the autosizing TextView feature on devices running Android 4.0 (API14) and higher: https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview.
> 
> So, if we are ok with this, is not a difficult task. However, If we want to support older android we need to do some calculations.
> 
> Btw considering that now Android is supporting officialy this feature, we shouldnt have a platform specific only for iOS: i propose to implement the Android native feature and integrate everything in the Label Renderers, getting rid of the platform specific.
> 
> I'm unsure if we need to support API<14, in this case users can attach an effect or create a custom renderer. Supporting this with custom code can degrade label performance (as seen with Effects/Custom Renderers spread over the internet)

Yes you made a very good point, especially considering the performance issues with autosize label provided out there for xamarin forms. These performance issues make them unusable for production use.

**Comment by GiampaoloGabba** [comment]
Also, in iOS don't forget to set the `minimumScaleFactor` property, to match  with the Android defaults (12sp) in order to have a consistent feature between platforms :)
Even Apple suggest to valorize this property: https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth

**Comment by xleon** [comment]
I made this in Android as suggested on top, but with the help of an Effect. It looks perfect and performance is awesome. The only consideration to have it working is that the `Label` needs to have a fixed `HeightRequest`. 

![image](https://user-images.githubusercontent.com/145087/89881702-23de4c00-dbc6-11ea-9606-389a856af13e.png)

**Comment by KSemenenko** [comment]
Any updates?

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
