### ISSUE TITLE
[Bug] Cannot update ToolbarItem text and icon

### ISSUE THREAD

**Issue by djwia** [xamarin/Xamarin.Forms#7181]
### Description
Cannot edit ToolbarItem Text and Icon in Shell ContentPage 4.1
### Steps to Reproduce

1. Created Shell application with ContentPage
2.  On OnAppearing and clicked events of the ToolbarItem, change the Text property
3. Text property won't change

### Expected Behavior
Text should be changed
### Actual Behavior
Text and Icons are not changed
### Basic Information
XF 4.1 Shell, Content Page, ToolbarItem

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by djwia** [comment]
```
    <ContentPage.ToolbarItems>
        <ToolbarItem x:Name="tbAdd" Text="Add" Clicked="AddItem_Clicked" />
    </ContentPage.ToolbarItems>

        async void AddItem_Clicked(object sender, EventArgs e)
        {
            tbAdd.Text = "clicked";
 }
```

**Comment by jfversluis** [comment]
Hey @djwia, thanks for the report!

Did you test this on iOS or Android? Maybe both?

It would be super awesome if you could add a project that reproduces this behavior.

**Comment by djwia** [comment]
I tested this on Android Emulator using my existing project and by creating a brand new Shell project. I will let you know if this happens on actual android device.

**Comment by djwia** [comment]
This happens on an actual Android device.

**Comment by jfversluis** [comment]
Does not happen on iOS. I do see this behavior on Android. Whenever you navigate to another page and go back you do see the change. Probably has something to do with a notify update/layout change call somewhere.

[Repro7181.zip](https://github.com/xamarin/Xamarin.Forms/files/3510718/Repro7181.zip)
