### ISSUE TITLE
[Bug] Button Focus not working on Android Platform in latest version, was working in 3.4

### ISSUE THREAD

**Issue by simonXarios** [xamarin/Xamarin.Forms#7186]
I am running a Xamarin Forms app on an Amazon Fire TV platform (Android).

I have recently upgraded from 3.4 to 4.1 as there are fixes in latest stable version which are needed in my app.

However, since upgrading I can no longer focus on a Button element programatically. **This is essential for my app because the platform doesn't register touch events.**

When running the .Focus() method on a button a false boolean is returned every time and my button state is not updated as expected,

May be related to #5616

- Version with issue: 4.1.0.673156
- Last known good version: 3.4.0.1009999
- Platform Target Frameworks:
  - Android:  
- Affected Devices: Amazon Fire TV Stick 4K

**Comment by samhouts** [comment]
@simonXarios  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@simonXarios  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
