### ISSUE TITLE
[UWP] - Button "Released" event is not fired when clicking on a button in a scroll view and scrolling

### ISSUE THREAD

**Issue by LucasLongarini** [xamarin/Xamarin.Forms#7191]
### Description
in UWP when a button is in a scroll view and you click on it, hold it and drag the scroll view, the "Released" event for the button is not fired

### Steps to Reproduce

1. Run in UWP
2. Place a button in a scroll view that is large enough to scroll.
3. Click on the button and hold.
4. While still holding the button, scroll in the scroll view.
5. After scrolling a bit, release the button

### Expected Behavior
The "Released" event should fire but the "Clicked" event should not
### Actual Behavior
The "Released' event is not fired
### Basic Information

- Version with issue: 3.6.0
- Last known good version: Unknown
- IDE:  Visual Studio 2019 16.2.2
- Platform Target Frameworks: 
  - UWP:  16299

**Comment by PureWeen** [comment]
@LucasLongarini why are you thinking Released should fire but not Clicked? Release corresponds to the physical touch on a button being removed from the button.

If you scroll the window, make sure to maintain the arrow over the button you were on when you started scrolling, and then let go then released and click events fire.
