### ISSUE TITLE
[Enhancement] [iOS] Create a Platform-Specific for ScrollView ContentInsetAdjustmentBehavior

### ISSUE THREAD

**Issue by GiampaoloGabba** [xamarin/Xamarin.Forms#7198]
## Summary
I find myself to constantly create custom renderers for scrollviews just to set the `ContentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentBehavior.Never`

It would be useful to have a PlatForm-Specific Property to address this and avoid custom renderers for 1 line of code :)

Also, this should fix #5098

## API Changes

Add a platform specific like:
`scrollView.On<iOS>().SetContentInsetAdjustmentBehavior(ContentInsetAdjustmentBehaviorMode.Never);`

Where `ContentInsetAdjustmentBehaviorMode` is an enum:

```
public enum ContentInsetAdjustmentBehaviorMode
{
	Always,
	Automatic,
	ScrollableAxes,
	Never,
}
```

## Intended Use Case
Provide a way to customize scrollview behaviour when needed (i found that on iphoneX* scrollview most of the times scroll when it shouldn't  (contentSize < scrollSize)

**Comment by Evolutionlab** [comment]
In case this proposal get accepted, i already have a pull request ready.

**Comment by GiampaoloGabba** [comment]
Have you considererd this request? I just started a new project and the first thing was the scrollview custom renderer just for this :)

**Comment by Edgaras91** [comment]
Is there a workaround to avoid custom renderer?
Is it possible to set a global style for all scrollView with this exclusive property? I don't mind if it's in C#.
Maybe with DependencyService?

**Comment by GiampaoloGabba** [comment]
@Edgaras91 you can use an effect instead of a  custom renderer.

Implementing this should fix also #5321 and #3932 as well as #5098 

Using a platform-specific is a good option and we dont risk to break existing code

**Comment by EmilAlipiev** [comment]
any progress on this? can we get that please?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
