### ISSUE TITLE
Page Orientation

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7202]
Hi,

Please add Orientation property for the Page so developers can set the orientation for a specific page to Landscape for example to show a video or image

Thanks,
[Jassim](https://www.softnames.com)

**Comment by MitchBomcanhao** [comment]
how would this handle resizable applications? the notion of portrait and landscape only really exists for full screen applications that run on mobile devices. How would this be mapped on non mobile devices, or devices where the application can run windowed?

**Comment by jrahma** [comment]
this will be on ContentPage 

How about ContentView?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
