### ISSUE TITLE
[Bug] TextViewCompat.SetAutoSizeTextTypeWithDefaults not work in android api version < 26

### ISSUE THREAD

**Issue by heebaek** [xamarin/Xamarin.Forms#7205]
### Description
Android TextView has auto font size feature. doc says TextViewCompat cover from API 14
But in Xamarin.Forms, this feature not working on API < 26.
I tested it with Xamarin.Android native and it has no problem.
So I think this problem bounded in Xamarin.Forms.

I tested it with 3 phones, api 28 (Xaomi Redmi note6), api 24(LG g4), api 21 (Samsung Galaxy Note3). 
api 28 device works well on both Xamarin.Forms and Xamarin.Android native.
api 24, api 21 devices only works on Xamarin.Android native.
 
Sample project contains both Xamarin.Forms version and Xamarin.Android native version.
so you can see easily this problem only occur in Xamarin.Forms with API < 26
 
### Steps to Reproduce

1. Make CusomLabel extends Label
2. In a CustomLabelRenderer call TextViewCompat.SetAutoSizeTextTypeWithDefaults
3. Label font size auto scaled only on API > = 26

### Expected Behavior
Xamarin.Forms 's auto font size also working good like a Xamarin.Android native platform.

### Actual Behavior
Only api >= 26 devices supported.

### Basic Information
- Version with issue: Xamarin.Forms(4.3.0.1032-nightly)

- IDE: Visual Studio For Mac

- Platform Target Frameworks: 
  - Android: 9.0
  Android Support Library Version: v4

### Screenshots
![Screenshot_2019-08-19-18-11-59 (1)](https://user-images.githubusercontent.com/12790588/63253929-be56c880-c2ad-11e9-97e1-53e942c8e0e6.png)

![Screenshot_2019-08-19-18-16-08-863_com bobaman autolabeltest](https://user-images.githubusercontent.com/12790588/63253939-c57dd680-c2ad-11e9-955a-3345a7342eb0.png)

### Reproduction Link
[AutoLabelTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3515054/AutoLabelTest.zip)

**Comment by jfversluis** [comment]
According to the documentation [here](https://developer.android.com/reference/android/support/v4/widget/TextViewCompat.html#setAutoSizeTextTypeWithDefaults(android.widget.TextView,%20int)) this is introduced in API 26? See also the screenshot below in the top right.

![image](https://user-images.githubusercontent.com/939291/63264481-745ceb00-c28b-11e9-8db9-b5dbe190d35b.png)

**Comment by felipebaltazar** [comment]
Like I've said [at this comment](https://github.com/xamarin/Xamarin.Forms/pull/7981#issuecomment-555805442), this behavior occurs because of LabelRender.View inherits from TextView and `TextViewCompat.SetAutoSizeTextTypeWithDefaults` needs to use (on api version < 26)  `Android.Support.V7.Widget.AppCompatTextView`.

**Comment by heebaek** [comment]
Thanks to #7981 , I can see the main problem was FormsTextView not inherited from AppCompatTextView.

but i am very worried about time to release #7981 

if you guys think FormsTextView : TextView is just a bug or have no any reason, please apply FormsTextView : AppCompatTextView first for a workaround. 

Please please.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
