### ISSUE TITLE
[Bug] tests fail on the master branch locally

### ISSUE THREAD

**Issue by BrayanKhosravian** [xamarin/Xamarin.Forms#7206]
### Description
I forked and cloned the repository and wanted to execute a unit test. It seems like somewhat 2000 uinttest are failing. 

### Steps to Reproduce

1. fork repo
2. clone repo
3. check out master
4. ctr + r, a => run all tests

### Expected Behavior
all test shoudl pass
### Actual Behavior
a lot of tests fail
### Basic Information

- Version with issue: Commit id = Commit 86650d41
- Last known good version: - 
- IDE: Visual studio 2019 and 2017
 
### Screenshots
![image](https://user-images.githubusercontent.com/35541212/63274712-8eed8f00-c2a0-11e9-8d12-f229ec533059.png)

**Comment by samhouts** [comment]
@BrayanKhosravian The tests that are in the `.UITests` categories are integration tests that need to be run on devices. They are not unit tests, and I don't recommend that you include them in your test run locally.

I can't see which tests are failing for you in the `.UnitTests` namespace. 

However, I can confirm that the rest of the tests are all passing on CI and locally for me.
