### ISSUE TITLE
[Bug] debug single uitest causes unhandled exception

### ISSUE THREAD

**Issue by BrayanKhosravian** [xamarin/Xamarin.Forms#7207]
### Description
I am working on the issue 7167 and i created a view, vm, a test case and fixed the problem actually. now i added a uitest to my namespace and while debugging i get an unhanded exception.
I made sure that all the sdks are installed. i also added manully 2 envirment variables which point to "ANDROID_HOME". I also installed the lates nunit test adapter.,

This is the error msg: 

`NUnit.Framework.InconclusiveException: 'App did not start for some reason: System.Exception: Android SDK not found. Please install it and if it is still not located, please set the ANDROID_HOME environment variable to point to the directory.

Searched locations: 
Windows Registry
(No path) - Not set. [ Source: ANDROID_HOME ]
   at Xamarin.UITest.Shared.Dependencies.AndroidSdkFinder.GetTools()
   at Xamarin.UITest.Shared.Android.DefaultAndroidFactory.BuildExecutor(IProcessRunner processRunner)
   at Xamarin.UITest.Android.AndroidApp..ctor(IAndroidAppConfiguration appConfiguration, IExecutor executor)
   at Xamarin.UITest.Configuration.AndroidAppConfigurator.StartApp(AppDataMode appDataMode)
   at Xamarin.Forms.Controls.AppSetup.InitializeAndroidApp() in C:\optiq\Xamarin.Forms\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\TestPages\TestPages.cs:line 63
   at Xamarin.Forms.Controls.AppSetup.InitializeApp() in C:\optiq\Xamarin.Forms\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\TestPages\TestPages.cs:line 40
   at Xamarin.Forms.Controls.AppSetup.Setup(Type pageType) in C:\optiq\Xamarin.Forms\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\TestPages\TestPages.cs:line 220'
`
### Steps to Reproduce

1. clone my forket xamarin forms repository https://github.com/BrayanKhosravian/Xamarin.Forms
2. switch branch to "issue_7167"
3. press ctrl + t to search for my class with the name "Issue7167.xaml.cs"
4. the vm, and all other components are located there. just execute my test in debug

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual studio 2019 16.2.2

### Screenshots
![image](https://user-images.githubusercontent.com/35541212/63281169-69ff1900-c2ac-11e9-81e6-d6fb05a91905.png)
![image](https://user-images.githubusercontent.com/35541212/63281191-74b9ae00-c2ac-11e9-9911-33f061963d9b.png)
![image](https://user-images.githubusercontent.com/35541212/63281210-7b482580-c2ac-11e9-8bbe-8c226b664ce4.png)
![image](https://user-images.githubusercontent.com/35541212/63281234-8e5af580-c2ac-11e9-9290-7eced109e768.png)

### Reproduction Link
https://github.com/BrayanKhosravian/Xamarin.Forms

**Comment by samhouts** [comment]
@BrayanKhosravian It sounds like you're trying to run the test on an emulator. Does it work if you start the Android emulator from the device manager before you run the test?

**Comment by BrayanKhosravian** [comment]
@samhouts thanks for your response. 
i tried to run the uitest also after running the emulator and this is the error im getting:
![image](https://user-images.githubusercontent.com/35541212/63435218-d0a84200-c426-11e9-879f-f9c8f8d99199.png)

What i already tried:
- updated from VS version 16.2.2 to 16.2.3 as it seems to fix the "Android sdk not found". it still didnt resolve my issue
- tried to execute the uitests when i was connected with my real phone

**Comment by BrayanKhosravian** [comment]
i fixed it finally.
![image](https://user-images.githubusercontent.com/35541212/63437249-7e692000-c42a-11e9-8170-4be893ca9ccf.png)

**Comment by BrayanKhosravian** [comment]
i created a pull request with the changes so that this error wouldnt happen to other devs
sincerely
