### ISSUE TITLE
[Enhancement] Make Frame.CornerRadius as CornerRadius (implement ICornerElement )  to be able to control radius per each corner

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#7208]
## Summary
Implement _ICornerElement_ interface as  in BoxView and make Frame.CornerRadius as CornerRadius to be able to control radius per each corner.
This can help make custom Frame shapes.

## API Changes
``` cs
public CornerRadius CornerRadius { get;set; }
```

**Comment by Mikilll94** [comment]
Any update on this?

**Comment by samhouts** [comment]
Duplicate of #1814
