### ISSUE TITLE
xamarin.forms label.text horizontaloption second line not trimming

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7217]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/692575/xamarinforms-labeltext-horizontaloption-second-lin.html)._

---
Just entered an example from a Xamarin book and the HorizontalOptions does not seem to work as expected.  Here is the code.

&lt;Label FontSize=&quot;20&quot; HorizontalOptions=&quot;CenterAndExpand&quot; HorizontalTextAlignment=&quot;Center&quot;&gt;
                &lt;Label.Text&gt;
                    This control is great for
                    displaying one or more
 
&lt;/Label.Text&gt;
            &lt;/Label&gt;

After &lt;Label.Text&gt; I hit return and typed the text.  At the end of the first line of text I hit return and the second line text lined up with the first line.  When displayed in an Android simulator the second line of text does not center.  It appears to be picking up the spaces before the second line as text.  If you delete the leading spaces so the text starts at the left of the screen it works OK.  I imagine you either need to ignore the leading spaces on following lines or place the cursor on the left edge when return is pressed?

Thanks.

---
#### Visual Studio Feedback System on 8/14/2019, 00:57 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kingces95** [comment]
Looks ok to me.
[App97.zip](https://github.com/xamarin/Xamarin.Forms/files/3532499/App97.zip)
![Screenshot_2019-08-22-18-45-30](https://user-images.githubusercontent.com/4120386/63561076-4c23f500-c4f4-11e9-98d3-a725c5771372.png)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
