### ISSUE TITLE
EventSetter

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#7221]
## Summary
WPF has it. It helps define events to be set inside a style.

## API Changes

https://docs.microsoft.com/en-us/dotnet/api/system.windows.eventsetter?view=netframework-4.8

## Intended Use Case
We can use `Setter` on `Command` instead of `EventSetter` on `Clicked`. But what about other events? For example, auto-sizing images that adjust their sizes by listening to `SizeChanged`? `Image` has `Aspect` but `Button` doesn't have it for `ImageSource`.

**Comment by StephaneDelcroix** [comment]
please provide a better description and better use cases for this. note that in the meantime, we support EventTriggers

**Comment by mattleibow** [comment]
I think the OP (like myself now) is asking for the ability to set event using styles. 

Just like the `<Setter Property="FontFamily" Value="Segoe Black" />` element, there is an `<EventSetter Event="Click" Handler="OnButtonClick" />`
