### ISSUE TITLE
[Bug] Cannot bind with TemplateBinding to Grid RowDefinition 

### ISSUE THREAD

**Issue by akatsukle** [xamarin/Xamarin.Forms#7223]
### Description

Using templateBinding on a RowDefinition's height property throws the following error:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
at Xamarin.Forms.TemplateBinding.Apply (System.Object newContext, Xamarin.Forms.BindableObject bindObj, Xamarin.Forms.BindableProperty targetProperty, System.Boolean fromBindingContextChanged) [0x0001f] in D:\\a\\1\\s\\Xamarin.Forms.Core\\TemplateBinding.cs:82
```

### Steps to Reproduce

1. Create a project with a simple ControlTemplate that contains a Grid
2. Verify it works properly
3. Try to bind RowDefinition's height property

### Expected Behavior

The value is bound correctly.

### Actual Behavior

An exception is thrown.

### Basic Information

- Version with issue: 3.6.0.539721, 4.1.0.555618
- Last known good version: None
- IDE: Visual Studio 2019

### Reproduction Code

[TestTemplateBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/3524465/TestTemplateBinding.zip)

The interesting part is below:

```
<Application.Resources>
    <ControlTemplate x:Key="TopBarPageTemplate">
        <Grid BackgroundColor="White" RowSpacing="0" ColumnSpacing="0">
            <Grid.RowDefinitions>
                <RowDefinition Height="46" />
                <RowDefinition Height="*" />
                <!--Comment and uncomment below to observe the bug-->
                <RowDefinition Height="46" />
                <!--<RowDefinition Height="{TemplateBinding BindingContext.BottomBarHeight}" />-->
            </Grid.RowDefinitions>

            <Label
                Grid.Row="0"
                Text="ControlTemplate Top"
            />

            <ContentPresenter
                Grid.Row="1"
                Padding="10, 0"
                VerticalOptions="FillAndExpand"
            />

            <Label
                Grid.Row="2"
                Text="ControlTemplate Bottom"
            />
        </Grid>
    </ControlTemplate>
</Application.Resources>
```

**Comment by akatsukle** [comment]
I forgot to mention, but using a TemplateBinding somewhere else works without any issues.

**Comment by kingces95** [comment]
Hm. Works for me on master. Simply loading the app should throw an exception, right?

**Comment by akatsukle** [comment]
No, you need to uncomment the template binding in App.xaml (iirc) to observe the exception.
In other word change
```
 <!--Comment and uncomment below to observe the bug-->
 <RowDefinition Height="46" />
 <!--<RowDefinition Height="{TemplateBinding BindingContext.BottomBarHeight}" />-->
```
to
```
 <!--Comment and uncomment below to observe the bug-->
 <!--<RowDefinition Height="46" />-->
 <RowDefinition Height="{TemplateBinding BindingContext.BottomBarHeight}" />
```

Sorry for the confusion, I wanted to provide a working sample that was easy to change into a non working sample.

**Comment by StephaneDelcroix** [comment]
currently, TemplateBinding only works on Element descendant, and not on all BindableObjects

**Comment by StephaneDelcroix** [comment]
As TemplateBinding is being deprecated in 4.3, in favor of Binding with RelativeSource (the `{TemplateBinding}` markup will stay, but will generated the a Binding instead of a TemplateBinding), it should no longer be an issue then. If it is, please reopen this issue
