### ISSUE TITLE
The error displaying ViewCell in Android.

### ISSUE THREAD

**Issue by monster74** [xamarin/Xamarin.Forms#7225]
Previous question:
https://github.com/xamarin/Xamarin.Forms/issues/6885

I checked the demo project on version 4.1.0.673156.
Everything also incorrectly displays the text of the index.
Only now the use of the ForceUpdateSize (); function has also ceased to help

**Comment by samhouts** [comment]
Use http://i.tk-chel.ru/anton/AppDemo.zip as repro

**Comment by monster74** [comment]
Yes, I check on this project: http://i.tk-chel.ru/anton/AppDemo.zip.  Checked on version 4.2.0.709249.  Also displayed incorrectly.

**Comment by rmarinho** [comment]
Hi @monster74 i tried the sample if i use ForceUpdateSize it all looks ok. 
Can you send me a screenshot? 

When i try this how it looks, isn't it correct?

![Screenshot_1567032893](https://user-images.githubusercontent.com/1235097/63898043-54e26280-c9ef-11e9-8d73-b6046303ba6f.png)
![Screenshot_1567032887](https://user-images.githubusercontent.com/1235097/63898044-54e26280-c9ef-11e9-8758-d540329c1992.png)

**Comment by monster74** [comment]
The screenshots that you sent me are correct.
I am testing on a device with android 4.4.
An incorrect display appears when scrolling through the list.
I send some screenshots with incorrect display of the index under the picture:

http://i.tk-chel.ru/anton/screen/Screenshot_2019-08-29-14-11-18.png
http://i.tk-chel.ru/anton/screen/Screenshot_2019-08-29-14-11-54.png
http://i.tk-chel.ru/anton/screen/Screenshot_2019-08-29-14-11-35.png

**Comment by rmarinho** [comment]
Are you using the ForceUpdateSize?

**Comment by monster74** [comment]
Yes.

**Comment by monster74** [comment]
Hello.
Please tell me if there is a result on my problem?
Today I checked on two devices with android 4.4 and android 9, on the version of Xamarin.Forms 4.2.0.815419. Everything also does not work.
I builded Visual Studio 2019 project.
