### ISSUE TITLE
[Bug] [iOS] CarouselPage child pages don't fire OnAppearing when child is not first (XF 4.1.0.555618)

### ISSUE THREAD

**Issue by JuanuMusic** [xamarin/Xamarin.Forms#7226]
### Description
The OnAppearing method is not getting executed on a Child page of a CarouselPage **_that is NOT the first item._**
This only happens on iOS. On Android works fine.

### Steps to Reproduce

1. Create a Carousel Page
2. Create 2 or more Child pages and add them to the carousel page children
3. Override the OnAppearing method of 2nd child page.
4. Execute and validate 

### Expected Behavior
The OnAppearing method should get called when the child page appears.

### Actual Behavior
The OnAppearing method is not getting called on pages that are not the first child.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS for MAC
- Platform Target Frameworks: 
  - Xamarin.Forms: 4.1.0.555618
  - iOS:  12.4
  - Android: Works Fine

**Comment by samhouts** [comment]
@JuanuMusic  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@JuanuMusic  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
