### ISSUE TITLE
Xamarin.Forms NetStandard 2.1?

### ISSUE THREAD

**Issue by arivoir** [xamarin/Xamarin.Forms#7227]
I've been observing some changes in preview packages that are breaking support for NetStandard 2.0 to only support NetStandard 2.1, as it is the case for EntityFrrameworkCore

https://github.com/aspnet/EntityFrameworkCore/issues/17178#issuecomment-522059701

In the above post is "confirmed" Xamarin.Forms will be supporting NetStandard 2.1.

- When?
- Will UWP also be supporting NetStandard 2.1? or it will be left as an obsolete platform?

I appreciate if you can help us understand what will be happening.

**Comment by charlesroddie** [comment]
My guess is that if XF required netstandard2.1 that could only be after .net5, and .net5 will cover all platforms.

**Comment by GalaxiaGuy** [comment]
Xamarin Forms will work on platforms that support NetStandard 2.1, but it seems unlikely that it will require it in the near future. So the key point for consuming 2.1 packages in XF app is whether the platforms themselves support it.

This document lists which version of the platforms will support 2.1:
https://github.com/dotnet/standard/issues/1330

The actual numbers seem out of date, but it at least confirms it should be coming soon.

The main dependency for Xamarin platforms is probably Mono, and it looks like that might already be in preview:
https://github.com/mono/mono/issues/11430

**Comment by samhouts** [comment]
We have no short term plans for this. Thanks!

**Comment by arivoir** [comment]
Thanks all for the updates. The Xamarin plans sound reasonable to me, but I don't understand the EntityFrameworkCore plans, as it would be dropping support for Xamarin.

I made the question in the other thread https://github.com/aspnet/EntityFrameworkCore/issues/17178#issuecomment-524560181
