### ISSUE TITLE
[Bug] License link could improve

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.Forms#7236]
### Description

This is a minor thing, but something I noticed during VSMac testing today. We should link to the license file differently in the Forms NuGet.

### Steps to Reproduce

Update the Forms NuGets, which display a prompt dialog so that the user can accept the license, and then click that link to view the license.
OR
Bring up the Manage NuGet Packages UI in VS / VSMac, show Installed packages there, then click on the license link to view the license.

### Actual Behavior

We launch this page in the browser:

![image](https://user-images.githubusercontent.com/245892/63477402-f3505000-c452-11e9-939f-8a179ce293b7.png)

### Expected Behavior

Other NuGet packages from Microsoft (the few I checked at least) link directly to the license in their GitHub repo here. That looks better as well as being more consistent.

And it seems suspect not showing the proper Microsoft copyright message nor including the copyright year. Legal may have a problem with that.

Also, what does SPDX identifier mean? That seems weird to show there (admittedly, that's a NuGet thing).

For all those reasons, it seems better to include the github license link (https://github.com/xamarin/Xamarin.Forms/blob/master/LICENSE) in the NuGet package, not the MIT SPDX identifier.

### Basic Information

- Version with issue: 4.2 (and all versions, I assume)
- IDE: VS Windows & Mac both

**Comment by jfversluis** [comment]
I think this has been improved in the meantime? If not, let me know
