### ISSUE TITLE
Version 4.2.0.709249 of Xamarin.Forms breaks FlyoutBehavior for Shell

### ISSUE THREAD

**Issue by BrienKing** [xamarin/Xamarin.Forms#7238]
### Description
After updating to 4.2.0.709249 of Xamarin.Forms the Flyout is shown even if you set FlyoutBehavior="Disabled" or you never use the Flyout.
### Steps to Reproduce

1.  Create a new Solution with the Xamarin.Forms Shell Application template.
2.  Make sure the Version is before 4.2.0.709249 (Version 4.1.0.709244 and older works fine)
3. Run the App, you'll see that it doesn't have the Flyout Menu.
4. Upgrade the Nuget Package to 4.2.0.709249
5. Run the App again and you'll see the Flyout Menu.  Nothing you do will make it go away.  You have to downgrade back to 4.1.0.709244 for it to work again.

### Expected Behavior
Flyout Menu should not be showing.

### Actual Behavior
Flyout Menu is showing.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version:4.1.0.709244
- IDE: VS2019 Enterprise
- Platform Target Frameworks: 
  - Android:  
- Affected Devices: Running on Emulator, haven't tested on a real device.

**Comment by MSiccDev** [comment]
Sadly, I have to confirm this one. Does not happen with XF 4.2.0.673161-pre3.

**Comment by PureWeen** [comment]
I'm fairly positive I know what broke this so we'll have a fix out soon

**Comment by jamesmontemagno** [comment]
Confirmed here as well :)

**Comment by v2vehooi** [comment]
may i know this issue solve already ? even as at today, when i create tab bar using xamarin form shell. i'll still get the hamburger menu on the top navigation bar although i already add : Flyoutbehavior to disabled.
Please help. thank you
