### ISSUE TITLE
[Bug] Android - Shell content layout hides page

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#7240]
I had a server error so GitHub lost my report. Shell header overlaps top of page.

Works in Forms 4.1.0.709244, broken in 4.2.0.709249.

![Screenshot_20190822-044413](https://user-images.githubusercontent.com/1438610/63501209-3f25e800-c499-11e9-8a45-cdbf242816ae.jpg)

![Screenshot_20190822-043556](https://user-images.githubusercontent.com/1438610/63501213-40571500-c499-11e9-94ac-8de985efd1e8.jpg)

**Comment by MSiccDev** [comment]
Sadly, I have to confirm this one. Does not happen with XF 4.2.0.673161-pre3.

**Comment by BioTurboNick** [comment]
Unfortunately I can't roll back as a workaround because I rely on pan gestures, which were broken in Shell before 4.2.

**Comment by BioTurboNick** [comment]
Unfortunately I can't roll back as a workaround because the pan gestures in Shell apps are broken in 4.2.0.673161-pre3 and previous.

**Comment by anthcool** [comment]
We have ran into this as well on the latest 4.2 stable release from yesterday.  Hope a fix is pushed soon...like later today if possible.

**Comment by anthcool** [comment]
We've decided to revert back to 4.1 for now.

**Comment by BioTurboNick** [comment]
How frequently are fixed pushed out? Just setting expectations.

**Comment by mjfreelancing** [comment]
This is critical for me. I can't roll back because of a defect with Device.InvokeOnMainThreadAsync() in previous versions that results in null reference exceptions. Hope there's a fix soon.

**Comment by samhouts** [comment]
closed by #7265. The service release will be available early next week! Thank you!
