### ISSUE TITLE
[Bug] [iOS] CollectionView header/footer on horizontal grid layout

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7246]
### Description

In a `CollectionView` with a horizontal grid layout, on Android the header appears to the left of the list, while the footer appears to the right of the list. This seems like the expected behavior for this layout.

Header on Android:

![Screenshot_1566486720](https://user-images.githubusercontent.com/8092460/63527377-e25a1a00-c4f8-11e9-9ddb-a56bc40d2318.png)

Footer on Android:

![Screenshot_1566486723](https://user-images.githubusercontent.com/8092460/63527385-e84ffb00-c4f8-11e9-966c-df81898bc942.png)

However, on iOS, for the same layout, the header appears at the top of the list while the footer appears at the bottom of the list. This isn't what I expected for this layout.

Header/footer on iOS:

![Simulator Screen Shot - iPhone X - 2019-08-22 at 16 11 23](https://user-images.githubusercontent.com/8092460/63527364-dc643900-c4f8-11e9-9d77-eaccb18417ff.png)

### Steps to Reproduce

1. Run the attached sample on iOS and browse to the "View header and footer (horizontal grid)" page.

### Expected Behavior

On iOS, header appears to the left of the list, while the footer appears to the right.

### Actual Behavior

Header appears above the list, while the footer appears below.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.709249
- Last known good version: N/A
- IDE: VSMac 8.2.4
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: API 28

### Reproduction Link

[CollectionViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3530821/CollectionViewDemos.zip)

**Comment by lomdar67** [comment]
Hi,

I know this has ben closed, but I strongly disagreed with the result. Why is a HEADER on the left side and not on top? Please make this at least a bindable property so we can select what layout we want top/bottom or left/right!
