### ISSUE TITLE
[Bug] Android Switch Slider wrong color?

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#7249]
### Description

After updating from 4.1.0 (first service release) to 4.2.0, the switch on Android has a strange behavior. If I switch them, the circle stays white which was not the case before and is not the case when I reload the page, see: https://i.imgur.com/sWVbdWX.png - All Orange Switches where on IsToggles while the page has loaded, the white ones just got toggled after the page loads. 

This bug is only happening for the Switch itself. It does not occur with SwitchCell controls. 

### Steps to Reproduce

1. Update to 4.2.0

### Expected Behavior

The Switch should not have different color. If this was an intended behvior change it should be equal accross all switches. 

### Actual Behavior

Different if the switch was loaded with a true value for IsToggled or if it was set after the page loads.

### Basic Information

- Version with issue:
- Last known good version: 4.1.0 (first service release)
- IDE:
- Platform Target Frameworks: 
  - Android: Latest stable
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@Sebastian1989101  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by galadril** [comment]
I have the same issue.. so the coloring of the icons are different for switches that are disabled or enabled with their initial state..

So open a page with:
- 1 switch enabled
- 1 switch disabled
- then enable the switch that was disabled.. 

It looks like this:
![afbeelding](https://user-images.githubusercontent.com/14561640/64846107-10201380-d60c-11e9-818e-356646b132cf.png)

And i would expect:
![afbeelding](https://user-images.githubusercontent.com/14561640/64846123-1a421200-d60c-11e9-9f35-ef818a207977.png)


let me see if i can quickly make a test repo for this.

**Comment by galadril** [comment]
Here is a simple Xamarin Forms 4.2 project, with just Android.
I've added two switches and a different default state

[SwitchTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3608972/SwitchTest.zip)

**Comment by samhouts** [comment]
Could be caused by #6798 or #6312
