### ISSUE TITLE
[Bug] Remove "To be added" from doc comments, for ReSharper users, etc.

### ISSUE THREAD

**Issue by BretJohnson** [xamarin/Xamarin.Forms#7252]
### Description

Many - maybe even most - Forms XML doc comments include `To be added` as placeholder text for doc comment elements that missing.

That placeholder text is actually added by some CI tooling.

Unfortunately, for users that have ReSharper installed, that text shows up in IntelliSense, for many/most properties.

Here are a couple examples:

![image](https://user-images.githubusercontent.com/245892/63554990-45ee4280-c50d-11e9-9fa7-bad94fa3ec00.png)

![image](https://user-images.githubusercontent.com/245892/63555064-8483fd00-c50d-11e9-9373-db4a33fee6d7.png)

For non-ReSharper users the placeholder text shows up rarely but still in some cases, like here:

![image](https://user-images.githubusercontent.com/245892/63555521-41c32480-c50f-11e9-9ae9-a529b7119401.png)

### Expected Behavior

We should fix this, one way or another, so that "To be added" never or rarely shows up as above and so that users have high quality doc available.

The two potential ways to fix it are:

Add more doc, with real text, to take the place of all the placeholders. That's what Craig suggests as the ideal fix and is what the docs team did before for all our doc.

Or we could fix it with some tooling changes to not generate this text. But changing that tooling brings up other issues (see Slack conversation for more context on that).

**Comment by samhouts** [comment]
@BretJohnson Thanks! I'm working on this, slowly but surely. :)

**Comment by jfversluis** [comment]
Oh man, I would love for this to be better. Unfortunately we couldn't make it happen for Forms. For .NET MAUI we're making sure to not repeat this mistake!
