### ISSUE TITLE
[Bug] UWP Switch Renderer throws exception when a custom renderer provides Color objects instead of Brush

### ISSUE THREAD

**Issue by bmacombe** [xamarin/Xamarin.Forms#7253]
### Description
After upgrading to 4.2.709249 previous working code that would change out the Application.Current.MainPage, like a login screen, causes UWP to hang, no exception, window does not respond to inputs.  

Update: Not related to the change of the main page, just coincidental that all the pages I tried had a custom switch.  In my custom UWP renderer I was creating a resource dictionary to provide color customization to the UWP switch.  In it I used Windows.UI.Color objects, which work as expected through XF 4.1.  4.2 added a switch enhancement to change the "thumb" color, which expected to be provided a Windows.UI.Xaml.Media.Brush object.  This caused an InvalidCastException upon load and a crash of the UWP app.

4.1.0.709244 works as expected.

### Steps to Reproduce

1. Change MainPage on UWP.

### Expected Behavior
Page Displays

### Actual Behavior
Page displays, but then app hangs in an unknown state that won't accept input.  Need to stop debugging or kill from task manager

### Basic Information

- Version with issue: 4.2.709249
- Last known good version: 4.1.0.709244
- IDE: VS2019 16.2.3

**Comment by bmacombe** [comment]
Of course a simple project doesn't seem to reproduce the issue.

**Comment by bmacombe** [comment]
{  "Type": "System.InvalidCastException",  "Message": "Specified cast is not valid.",  "StackTrace": null}

I was able to find that in my error reporting that appears to timestamp to the to the UWP app hanging.  Will not break with the VS debugger attached...at least not with just managed debugging.

**Comment by bmacombe** [comment]
Was able to get a little more detail, I do recall there be some changes to the UWP switch renderer to add support for more things.  I think I do have a custom renderer, so I'll investigate there.

System.InvalidCastException: Unable to cast object of type 'Windows.UI.Color' to type 'Windows.UI.Xaml.Media.Brush'.   at Xamarin.Forms.Platform.UWP.SwitchRenderer.UpdateThumbColor()   at Xamarin.Forms.Platform.UWP.SwitchRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)

**Comment by bmacombe** [comment]
I was just able to confirm it was my renderer, if I disable it I no longer receive the error.  So it's not related to the changing of the main page.  I can't remember where I dug up this code, but it was a while ago to turn off the on/off  on UWP and adjust it's color.  I'll see if I can update it.

`using System.ComponentModel;
using AS.Mobile.Common.UI;
using AS.Mobile.Common.UWP.CustomRenderers;
using Xamarin.Forms;
using Xamarin.Forms.Platform.UWP;
using ResourceDictionary = Windows.UI.Xaml.ResourceDictionary;

[assembly: ExportRenderer(typeof(ASSwitch), typeof(ASSwitchRenderer))]
namespace AS.Mobile.Common.UWP.CustomRenderers
{
	public class ASSwitchRenderer : SwitchRenderer
    {
        protected ASSwitch ASSwitch => Element as ASSwitch;
        protected CustomSwitchStyle CustomStyle { get; set; }

        protected override void OnElementChanged(ElementChangedEventArgs<Switch> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {

            }

            if (e.NewElement == null) return;

            //Remove the on and off content so the UWP switch aligns with the iOS and Android switch
            Control.OnContent = null;
            Control.OffContent = null;
            CustomStyle = new CustomSwitchStyle();
            Control.Resources = CustomStyle;

            //Update all sub class dependency props to update them if a style is applied
            OnElementPropertyChanged(this, new PropertyChangedEventArgs(nameof(ASSwitch.MasterForegroundColor)));
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            switch (e.PropertyName)
            {
                case nameof(ASSwitch.MasterForegroundColor):
                    CustomStyle.ToggleSwitchStrokeOn(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchStrokeOff(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchKnobFillOn(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchKnobFillOff(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchStrokeOnPointerOver(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchStrokeOffPointerOver(ASSwitch.MasterForegroundColor.ToUwpColor());

                    CustomStyle.ToggleSwitchKnobFillOffPointerOver(ASSwitch.MasterForegroundColor.ToUwpColor());
                    CustomStyle.ToggleSwitchKnobFillOnPointerOver(ASSwitch.MasterForegroundColor.ToUwpColor());
                    break;
            }

            base.OnElementPropertyChanged(sender, e);

        }

        protected class CustomSwitchStyle : ResourceDictionary
        {
            public void ToggleSwitchStrokeOn(Windows.UI.Color c) => this["ToggleSwitchStrokeOn"] = c;
            public void ToggleSwitchStrokeOff(Windows.UI.Color c) => this["ToggleSwitchStrokeOff"] = c;
            public void ToggleSwitchKnobFillOn(Windows.UI.Color c) => this["ToggleSwitchKnobFillOn"] = c;
            public void ToggleSwitchKnobFillOff(Windows.UI.Color c) => this["ToggleSwitchKnobFillOff"] = c;
            public void ToggleSwitchStrokeOnPointerOver(Windows.UI.Color c) => this["ToggleSwitchStrokeOnPointerOver"] = c;
            public void ToggleSwitchStrokeOffPointerOver(Windows.UI.Color c) => this["ToggleSwitchStrokeOffPointerOver"] = c;
            public void ToggleSwitchKnobFillOffPointerOver(Windows.UI.Color c) => this["ToggleSwitchKnobFillOffPointerOver"] = c;
            public void ToggleSwitchKnobFillOnPointerOver(Windows.UI.Color c) => this["ToggleSwitchKnobFillOnPointerOver"] = c;

        }
    }
}
`

**Comment by bmacombe** [comment]
I suspect this is related to #6312

if (_originalThumbOnBrush == null)
				_originalThumbOnBrush = (Brush)frame.Value;

**Comment by bmacombe** [comment]
I converted my renderer to supply brushes instead of colors and it works as expected.  Simple enough to fix on my end, but might be good to have the XF UWP Switch renderer handling just being passed a color as it seems UWP allows that.

`
protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            switch (e.PropertyName)
            {
                case nameof(ASSwitch.MasterForegroundColor):
                    CustomStyle.ToggleSwitchStrokeOn(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchStrokeOff(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchKnobFillOn(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchKnobFillOff(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchStrokeOnPointerOver(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchStrokeOffPointerOver(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));

                    CustomStyle.ToggleSwitchKnobFillOffPointerOver(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    CustomStyle.ToggleSwitchKnobFillOnPointerOver(new SolidColorBrush(ASSwitch.MasterForegroundColor.ToUwpColor()));
                    break;
            }

            base.OnElementPropertyChanged(sender, e);

        }

        protected class CustomSwitchStyle : ResourceDictionary
        {
            public void ToggleSwitchStrokeOn(Brush c) => this["ToggleSwitchStrokeOn"] = c;
            public void ToggleSwitchStrokeOff(Brush c) => this["ToggleSwitchStrokeOff"] = c;
            public void ToggleSwitchKnobFillOn(Brush c) => this["ToggleSwitchKnobFillOn"] = c;
            public void ToggleSwitchKnobFillOff(Brush c) => this["ToggleSwitchKnobFillOff"] = c;
            public void ToggleSwitchStrokeOnPointerOver(Brush c) => this["ToggleSwitchStrokeOnPointerOver"] = c;
            public void ToggleSwitchStrokeOffPointerOver(Brush c) => this["ToggleSwitchStrokeOffPointerOver"] = c;
            public void ToggleSwitchKnobFillOffPointerOver(Brush c) => this["ToggleSwitchKnobFillOffPointerOver"] = c;
            public void ToggleSwitchKnobFillOnPointerOver(Brush c) => this["ToggleSwitchKnobFillOnPointerOver"] = c;

        }
`

**Comment by kingces95** [comment]
Please provide a reproduction of the issue.

**Comment by bmacombe** [comment]
@kingces95 Reproduction attached as requested.  I included the version of the "ASSwitchRenderer" that causes the crash and left my updated version in the same file commented out. 

I also updated to the latest 4.3 pre and the error was still present.

Thanks!

[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/3662867/App3.zip)

**Comment by jsuarezruiz** [comment]
Thanks so much for the repro sample @bmacombe. We already have a related PR to fix the problem: https://github.com/xamarin/Xamarin.Forms/pull/7760
