### ISSUE TITLE
Cross Platform Backgrounding

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7261]
Hi,

It will be great if you add a cross platform backgrounding instead of depending on specific platform method

This includes PeriodicWorkRequest and other backgrounding ways for iOS, Android and UWP.

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by KSemenenko** [comment]
You can try https://github.com/shinyorg/shiny

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
