### ISSUE TITLE
[Bug] Images are not loaded: Update Xamarin.Forms 4.2

### ISSUE THREAD

**Issue by eincioch** [xamarin/Xamarin.Forms#7264]
## Description
The images are not loaded, in this latest version of Xamarin.Forms 4.2.

<Image
                    Source="https://www.ucv.edu.pe/assets/imgs/logo.png"
                    Aspect="AspectFit"/>

**Comment by samhouts** [comment]
@eincioch  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by eincioch** [comment]
I am attaching the requested Miss Samantha Houts

[AppBugLoadImage.zip](https://github.com/xamarin/Xamarin.Forms/files/3538353/AppBugLoadImage.zip)

**Comment by samhouts** [comment]
Duplicate of #7248
