### ISSUE TITLE
[Bug] Navigation.SetHasBackButton causes null reference error on Android

### ISSUE THREAD

**Issue by gseregeg** [xamarin/Xamarin.Forms#7269]
### Description
This issue occurs on XF 4.x but works fine on XF 3.x.  The "soft" back button appears on the Navigation bar on top left of the screen, and we used to hide that during data entry form on XF 3.x but it is now causing a null reference exception.

The back button appears when using Navigation Page and at least two pages are stacked using PushAsync.  See below on how this is reproduced.

### Steps to Reproduce

1. Create a Xamarin Forms project using Visual Studio 2019 Mobile App.  Select a Master-Detail template and click OK.
2. Open App.xaml.cs in the common library (PCL) 
3. Replace the line "MainPage= new MainPage()" with the following.
            var master = new MasterDetailPage()
            {
                Master = new Page() { Title = "Title", BackgroundColor = Color.Red },
                Detail = new Page() { BackgroundColor = Color.Yellow }
            };
            MainPage = new NavigationPage(master);

            var page = new Page() { BackgroundColor = Color.Green };
            Application.Current.MainPage.Navigation.PushAsync(page, false);
            NavigationPage.SetHasBackButton(page, false);

### Expected Behavior
A green background page with no back button should be displayed
### Actual Behavior
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Basic Information

- Version with issue:
- Last known good version: XF 3.x
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9 pie
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Xiao Mi 

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3537222/App1.zip)

**Comment by rmarinho** [comment]
Seems you are wrapping a `MasterDetailPage` on a `NavigationPage` that could work but it's not supported. 

You should set the Detail page to be a NavigationPage. 

Try this:

```
 var master = new MasterDetailPage()
 {
       Master = new Page() { Title = "Title", BackgroundColor = Color.Red },
       Detail = new NavigationPage(new Page() { BackgroundColor = Color.Yellow })
 };
 MainPage = master;
 var page = new Page() { BackgroundColor = Color.Green };
 master.Detail.Navigation.PushAsync(page, false);
 NavigationPage.SetHasBackButton(page, false);
```

**Comment by SudhersonV** [comment]
Hello, we have an ExtendedContentPage used by WebViewPage.xaml as below,
                           NavigationPage.SetHasBackButton(this, HasBackButton);  is not working after Xamarin upgrade, please suggest solution.

<v:ExtendedContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
		xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
		Title="{Binding Title}" HasBackButton="False">

public class ExtendedContentPage : ContentPage
{
         public bool HasBackButton
         {
             get { return (bool)GetValue(HasBackButtonProperty); }
             set { SetValue(HasBackButtonProperty, value); }
         }

        protected override void OnAppearing ()
	{
		base.OnAppearing ();
                 if (!HasBackButton && Device.RuntimePlatform == Device.Android)
                 {
                        NavigationPage.SetHasBackButton(this, HasBackButton);
                 }
      }
}

**Comment by gseregeg** [comment]
Hi,

I opted to intercept the back button and perform the necessary work instead of hiding it.  This also means that the back button operates differently in Android compared to iOS and UWP.  

Kind Regards,

Gusti


Please consider the environment before printing this e-mail
