### ISSUE TITLE
[Bug] `CarouselView.ScrollToRequested` event is not filled correctly.

### ISSUE THREAD

**Issue by nielsenko** [xamarin/Xamarin.Forms#7275]
### Description

`CarouselView.ScrollToRequested` event is not filled correctly.

### Steps to Reproduce

If a user calls `CarouselView.ScrollTo` with an object (ie. not an index), then the ensuing `Index` property on the raised `ScrollToRequested` event is not filled correctly (it is always zero).

### Basic Information

Reproduced on Xamarin.Forms  4.2.0.709249

**Comment by samhouts** [comment]
@nielsenko  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
