### ISSUE TITLE
[Bug] ViewExtensions.RotateTo not working with Xamarin.Forms 4.2

### ISSUE THREAD

**Issue by skorpyon1992** [xamarin/Xamarin.Forms#7278]
### Description

ViewExtensions.RotateTo does not work anymore on version 4.2.0709249.

### Steps to Reproduce

1. Create a project where you have an Image object in XAML code. Add an image to the android project in resources/drawable and add the name of the image as source in the XAML code.
2. Add a button in page and in its event handler try RotateTo on the image object; e.g.
                await ViewExtensions.RotateTo(image, 360, 800, Easing.Linear);
		await ViewExtensions.RotateTo(image, 0, 0);
3. Run project. You can directly run the projects from attachment (1 project with version 3.4 and one with version 4.2).

### Expected Behavior

Image should be rotated.

### Actual Behavior

Image does not rotate at all, even if code is executed.

### Basic Information

- Version with issue: 4.2.0709249
- Last known good version: 3.4.0.1008975
- IDE: Visual Studio 2017 Windows
- Platform Target Frameworks: 
  - iOS: 
  - Android: Android 8.1 and 9.0
  - UWP:  
- Nuget Packages: Xamarin.Forms
- Affected Devices: all

See attachment below for project samples.
[Desktop.zip](https://github.com/xamarin/Xamarin.Forms/files/3540215/Desktop.zip)

**Comment by bentmar** [comment]
Theres a bug with 4.2 that makes animations finish instantly. Rotating an image 360 degrees in 0ms would seem that it doesnt rotate. Try rotating 180 degrees :) if that works its probably not the rotation thats the issue but the animation of the rotation.

**Comment by skorpyon1992** [comment]
Hello I have also tried what you mentioned and I have the same behaviour (animation finishes instantly). Hope it will be fixed in the next version. Thank you!
