### ISSUE TITLE
[Bug] MainPage = new NavigationPage(); throws exception

### ISSUE THREAD

**Issue by jungjanos** [xamarin/Xamarin.Forms#7283]
### Description
After upgrading to Xamarin.Forms 4.2, when calling MainPage = new NavigationPage() at application start  with empty constructor an exception is thrown (sorry didnt take note, what type). If I pass a Page as argument to the NavigationPage constructor, no exception is thrown. 

### Steps to Reproduce

1. Update to Xamarin.Forms 4.2
2. Call: MainPage = new NavigationPage()

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: 4.1.0.673156
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: 9.0, x86 (emulator), arm64 (device)
- Nuget Packages:
CardsView" Version="2.1.7"
LazyCache" Version="2.0.1"
Microsoft.AspNetCore.WebUtilities" Version="2.2.0"
Newtonsoft.Json" Version="12.0.2"
Xamarin.FFImageLoading" Version="2.4.11.982"
Xamarin.FFImageLoading.Forms" Version="2.4.11.982"
Xamarin.Forms" Version="4.2.0.709249" 
YoutubeExplode" Version="4.7.9"

- Affected Devices: see above

### My workaround:
 original (now failing) code is commented out

            //MainPage = new NavigationPage();
            //if (!Settings.IsLoginPageDeactivationRequested)
            //{
            //    var loginPage = new LoginPage();
            //    await MainPage.Navigation.PushAsync(loginPage);
            //    MainPage.Navigation.InsertPageBefore(new MainTabbedPage(), loginPage);
            //}
            //else 
            //    await MainPage.Navigation.PushAsync(new MainTabbedPage());

workaround:

            if (!Settings.IsLoginPageDeactivationRequested)
            {
                var loginPage = new LoginPage();                
                MainPage = new NavigationPage(loginPage);
                MainPage.Navigation.InsertPageBefore(new MainTabbedPage(), loginPage);
            }
            else                           
                MainPage = new NavigationPage(new MainTabbedPage());

**Comment by jungjanos** [comment]
Exception is:
{System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <ff07eae8184a40a08e79049bbcb31a0e>:0 
  at System.Collections.ObjectModel.Collection`1[T].get_Item (System.Int32 index) [0x00000] in <ff07eae8184a40a08e79049bbcb31a0e>:0 
  at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.RegisterToolbar () [0x0004b] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:646 
  at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnAttachedToWindow () [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:299 
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <b62c3fba3fe848f3bb323dbe33464223>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.25(intptr,intptr)}

**Comment by rmarinho** [comment]
Hi, i was trying to get this failing but i couldn't i have attached a repo, can you try it and say what  i m doing wrong? 

Thanks 

[App9.zip](https://github.com/xamarin/Xamarin.Forms/files/3556461/App9.zip)

**Comment by jungjanos** [comment]
Hi Rui!

Sorry for the outage. 
I have downloaded your project and tried to reproduce it with no success: the crash I described above did not happen when compiling and running App9.

However I rechecked my repo and the problem is still present when upgrading to 4.2.0.709249 .
How do we proceede from here? Should I ZIP and upload my repo to a private shared storage, or should I give you access to my private repo on Bitbucket? (its not on GH)

BR
Janos

**Comment by jungjanos** [comment]
UPDATE
I think I have it: 

So I have modified your basic code just a little bit to mimic what I am doing in my App:

App constructor:
Here I just pass a loading placeholder in form of a ContentPage.
```
        public App()
        {
            InitializeComponent();
            MainPage = new ContentPage { Title = "Will I crash???" };
        }
```

I put some initialization code in my overriden async OnStart() method. And pass a new NavigationPage() to the App.MainPage property. The exception is thrown when the MainPage property is reassigned. So the line var nav = `new NavigationPage(); ` is fine. 
Note that in the bugreport I did the newing up and the reassignment in one step, here it is divided up into two steps for clarity.

```
        protected override async void OnStart()
        {
            await Task.Delay(3000);

            // Handle when your app starts

            var nav = new NavigationPage();            // this is fine
            MainPage = nav; // throws with XF 4.2, fine in my XF4.1 project!!

            await MainPage.Navigation.PushAsync(new ContentPage { Title = "Did I crash???" });
        }
```

I then tried the following lines in your project:

```
        protected override async void OnStart()
        {
            await Task.Delay(3000);

            // Handle when your app starts

            var nav = new NavigationPage();            // this is fine
            MainPage = null;  // throws !!
            MainPage = nav;

            await MainPage.Navigation.PushAsync(new ContentPage { Title = "Did I crash???" });
        }
```
I then went back to my XF 4.1 project and tried the above line (setting MainPage to null and only after then doing the reassignment to the newed up NavigationPage) In this case my XF 4.1 project throws.

So the problem seems to be that MainPage does not tolerate a reassignment when using XF 4.2 even if it is set to a valid Page.

**Comment by jsuarezruiz** [comment]
I have reviewed the @rmarinho sample updating it with your suggested changes. I can reproduce the problem using:

```
protected override async void OnStart()
{
            await Task.Delay(3000);

            // Handle when your app starts

            var nav = new NavigationPage();            // this is fine
            MainPage = null;  // throws !!
            MainPage = nav;

            await MainPage.Navigation.PushAsync(new ContentPage { Title = "Did I crash???" });
}
```
