### ISSUE TITLE
[Bug] Scrolling on a listview while focus is inside an entry field causes exception

### ISSUE THREAD

**Issue by kunalsympac** [xamarin/Xamarin.Forms#7284]
### Description
Attempting to scroll while focus is within an entry field (which is placed either in the listview header or as part of the listview bound data list) causes an exception once the entry field goes off the page.

I have only encountered this on a device running Android 6.0. Doesn't appear to happen on later versions (tested with 7.1 and 8.0).

### Steps to Reproduce
1. Create a listview with either an entry field as part of the data list or an entry field inside the listview header. Populate enough data so that the listview can be scrolled.
2. Run application. Set focus on an entry field within the listview (or the entry field inside the header).
3. Scroll until the entry that has focus goes off the page (you may have to scroll up and down a few times).

### Expected Behavior
Nothing should happen

### Actual Behavior
Exception occurs

### Basic Information

- Version with issue:  Xamarin 4.1.0.673156
- IDE: VS 2019
- Platform Target Frameworks:  Android 6.0

**Comment by kunalsympac** [comment]
Discussed others previously forums.xamarin.com/discussion/101486/listiview-scroll-entry-crash.

**Comment by rmarinho** [comment]
Hi, tried to reproduce but wasn't able, can you  please provide a reproduction  This was the test i tried.

```
var page = new ContentPage
{
	Content = new ListView
	{
		Header = new Entry { },
		ItemsSource = Enumerable.Range(0, 100)
					.Select(r => r)
					.ToList()
	}
};
```

**Comment by kunalsympac** [comment]
Hi @rmarinho, thanks for looking into this. I'm also having trouble replicating it on a new project, I'm wondering if it has anything to do with data binding or if there is something specific with the project on which the error is occurring. I'll keep trying and let you know when I can get it happening or otherwise.

**Comment by samhouts** [comment]
@kunalsympac Thanks! We'll keep looking for it.

**Comment by samhouts** [comment]
@kunalsympac  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
