### ISSUE TITLE
[Bug] All XAML-defined elements null in Page Constructors with 4.2.0.709249

### ISSUE THREAD

**Issue by SandraHicks** [xamarin/Xamarin.Forms#7286]
### Description
After updating to the latest Version of Xamarin Forms (4.2.0.709249) on Android and iOS, my App throws an exception at start. Investigating the issue showed that in the constructor call of my initial Page, all XAML-defined elements are null. The issue was fixed by downgrading the Xamarin Forms Nuget package.
This happens with multiple pages in my project, I have tried starting from several to exclude a mistake in the specific page. 

### Steps to Reproduce

1. Start Application, Load a new App. (either iOS or Android)
2. Set a MainPage in App.xaml.cs in the overridden OnStart.
3. In Constructor of set MainPage, make a call to an element specified in XAML of this page (e.g. set a Label).
4. Label is null, as any other element from the XAML.

### Expected Behavior
App launches as usual.

### Actual Behavior
Exception thrown in the constructor of the first loaded page when trying to access an element of the XAML code.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: 4.1.0.673156
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - Shared Code: .NET Standard 2.0, Library
  - iOS:  Deployment Target 9.0
  - Android: 9.0 Pie
- Affected Devices: all

**Comment by jamesjohnmcguire** [comment]
This doesn't happen all the time.  ListViews and images seem ok, at least, once in a while.  So, the default app template project seems to run fine out of the box.

But buttons and labels just are not found in the generated InitializeComponent method.

The following from a generated InitializeComponent returns null:
cancel = global::Xamarin.Forms.NameScopeExtensions.FindByName<global::Xamarin.Forms.Button>(this, "cancel");

**Comment by SandraHicks** [comment]
I also had this issue when I tried to access a RelativeLayout in the Constructor after the InititalizeComponent() call.

**Comment by rscholey** [comment]
I am also getting a problem after upgrade:

<t:ScrollableView xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Japanese;assembly=Japanese"
             xmlns:t="clr-namespace:Japanese.Templates"
             x:Class="Japanese.Views.Dictionary.DictionaryTabPage"
             BackgroundColor="{DynamicResource PageBackgroundColor}"
             PageTitle="Dictionary"
             x:Name="ThisPage">

The code cannot find the element named ThisPage

This is a serious problem that I can reproduce on four different machines.  Now unable to use this latest release.

**Comment by rscholey** [comment]
Note that unlike with James.  This particular problem happens all the time with me.

**Comment by nikhildpardasani** [comment]
Even I am facing a consistent crash with the latest XF NuGet package. This is frustrating. I have a planned release this week and now I am stuck with the only option left to downgrade the NuGet packages.

**Comment by rscholey** [comment]
The following code in the body of my XAML is not able to find the element named ThisPage in the constructor. This was working before update.

> <StackLayout x:Name="CategorySwitch"
>                                              BindableLayout.ItemsSource="{Binding CardSetWithWordCountForCreateSwitch}"
>                                              Spacing="0">
>                                     <BindableLayout.ItemTemplate>
>                                         <DataTemplate>
>                                             <t:BadgePlusGridTemplate Text1="{Binding Name}"
>                                                                      Text2="{Binding TotalHiddenCount}"
>                                                                      State="{Binding Toggled}"
>                                                                      Message="{Binding Message}"
>                                                                      RowId="{Binding Id}"
>                                                                      Separator="true"
>                                                                      TapCommand="{Binding Path=BindingContext.SelectCardSetCmd, Source={x:Reference Name=ThisPage}}"
>                                                                      Tap2Command="{Binding Path=BindingContext.OpenCardsPageCmd, Source={x:Reference Name=ThisPage}}" />
>                                         </DataTemplate>
>                                     </BindableLayout.ItemTemplate>
>                                 </StackLayout>

**Comment by rmarinho** [comment]
Hi @SandraHicks can tou provide a small repo please?

Thanks

**Comment by SandraHicks** [comment]
@rmarinho Sorry I do not have the time to do that.

**Comment by StephaneDelcroix** [comment]
If the issue being discussed here is: "When using recent XF, some fields are not correctly mapped to `x:Name`s", this is related to #7097. Even if it's not obvious, it's the second side of the same piece.

If my assumption about the issue being reported is right, I have a repro case for that, and I'm working on a fix.

We still _need_ a reproduction case for this issue, so we're sure we're addressing the right problem.

**Comment by StephaneDelcroix** [comment]
regression due to #7040

**Comment by StephaneDelcroix** [comment]
@SandraHicks please confirm that this happens when using controls deriving from other custom controls

**Comment by SandraHicks** [comment]
@StephaneDelcroix My page base class is derived from Xamarin.Forms.ContentPage.
The error occurs in classes derived from my page base class. Both the base class and the subclasses contain further custom controls like a custom button.

Nevertheless, except for my ContentPage subclass, there are no controls which are subclasses of my custom controls.

**Comment by jamesjohnmcguire** [comment]
Repo with Bug: https://github.com/jamesjohnmcguire/BugDemoXamlVar
Set a breakpoint at ItemsPage.xaml.cs at line 11.

Note this is almost exactly the same as the default app template, which doesn't exhibit the bug, because it has the following in AssemblyInfo.cs:

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]

In this repo above, this line is commented out.

I'm not sure when this attribute was added, but I suspect many existing applications (like mine), don't have this.

Hope this helps.

**Comment by eli191** [comment]
I am hitting this bug with `Xamarin.Forms.5.0.0.1829-pre6`
