### ISSUE TITLE
ViewCell tapped commands do not work

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7295]
### Description

I think this is a regression bug that happened a few months back, but I haven't had a chance to report it till now. Not sure if a similar Github issue exists. Wiring up a command for a cell does not work. I tested this on Android, but I think the issue exists for iOS as well.

### Steps to Reproduce

1. Run repro.
2. Tap any ListView cell.
3. Observe that the `Tapped` event gets executed, but the `Command` does not fire.
4. You may also temporarily disable the `Tapped` event and test `Command` only.

### Expected Behavior

The tapped command should fire.

### Actual Behavior

Command does not fire.

### Reproduction Link

[App150.zip](https://github.com/xamarin/Xamarin.Forms/files/3548770/App150.zip)

**Comment by samhouts** [comment]
@adrianknight89 You have your command defined on your ViewModel, but the items are bound to Model. So you're getting a binding problem:

```
Binding: 'GridTappedCommand' property not found on 'App150.MainPage+Model', target property: 'Xamarin.Forms.TapGestureRecognizer.Command'
```

If I move the command to the Model class, it works as expected.

**Comment by adrianknight89** [comment]
Thanks. I must have missed that. It should be part of the Model. I think the warning/error should be displayed to us though. Did you see it when you ran the repro alone or when it was attached to the Forms source code?

**Comment by samhouts** [comment]
I saw it on your repro. It popped up as a binding error in the Application Output. Those often get buried  depending on how verbose your debug settings are. We have ideas to make this better. /cc @StephaneDelcroix
