### ISSUE TITLE
How can I custom layout of Shell Tab Bottom ?

### ISSUE THREAD

**Issue by Thanghand** [xamarin/Xamarin.Forms#7296]
## Summary
How can I custom template of Shell Tab bottom ?

In shell application, 
![Screen Shot 2019-08-28 at 9 30 49 AM](https://user-images.githubusercontent.com/8011261/63821269-8ff47f80-c976-11e9-94c8-fc47159053c1.png)

I read all document of Shell, and I just see that we can only edit template for Shell FlyoutItem. I need to custom layout for item tab bar 

![Screen Shot 2019-08-28 at 9 34 44 AM](https://user-images.githubusercontent.com/8011261/63821447-4193b080-c977-11e9-96f7-ede791c685ce.png)

## Intended Use Case
Could you provide template that I can custom layout for item tab ?

**Comment by jfversluis** [comment]
This is a question more than anything else and it seems it's quite old by now. I hope you got this figured out!
