### ISSUE TITLE
[Bug] Unable to Build Source on MacOS

### ISSUE THREAD

**Issue by ahoefling** [xamarin/Xamarin.Forms#7297]
### Description
When building Xamarin.Forms specifically trying to build Xamarin.Forms.Platform.iOS from source I was running into several errors with the latest changes in the master branch.

-commit `c0a681e852ae360e5b40e27e3606d929166e1474`

The root cause appears to be a mono build issue as I am getting mono crashes. This is shown by the error message of the copy script where it can't copy the `Xamarin.Forms.Platform` assembly into the obj/debug directory. 

```
error MSB3030: Could not copy the file "obj/Debug/netstandard1.0/Xamarin.Forms.Platform.dll" because it was not found
```

After the errors there are several mono error files added to the local repository. I added these files in a zip at the bottom of the issue. This stuff goes beyond my expertise for how the Xamarin.Forms project is built and works with mono.
```
        new file:   Xamarin.Forms.Core/mono_crash.780ae7a6c.0.json
	new file:   Xamarin.Forms.Core/mono_crash.780ae7a6c.1.json
	new file:   Xamarin.Forms.Core/mono_crash.780ae7a6c.2.json
	new file:   Xamarin.Forms.Core/mono_crash.780ae7a6c.3.json
	new file:   Xamarin.Forms.Core/mono_crash.mem.12161.1.blob
	new file:   Xamarin.Forms.Core/mono_crash.mem.12254.1.blob
	new file:   Xamarin.Forms.Core/mono_crash.mem.13725.1.blob
	new file:   Xamarin.Forms.Core/mono_crash.mem.13837.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.10843b5c0.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.700004137000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.700004440000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.700004643000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.700004846000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12140.700005255000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12234.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12234.70000f674000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.12234.70000f877000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13723.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13817.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13817.700004d6e000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13817.700004f71000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13817.700005174000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13922.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13948.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13948.10aa0f5c0.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13948.70000ed6f000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13948.70000f57b000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.13989.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000d74e000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000da57000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000dc5a000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000de5d000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000e669000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14001.70000e86c000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14065.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.112d4a5c0.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000c2b5000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000c5be000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000cbc7000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000cdca000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000cfcd000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000d1d0000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14139.70000d3d3000.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14204.1.blob
	new file:   Xamarin.Forms.Platform/mono_crash.mem.14230.1.blob
```

### Things I tried
I tried a bunch of things that didn't work.

* Cleaning branch with `git clean -xdf`
* Deleting my entire local repository and re-cloning (including sub-modules)
* Following steps in main README.md exactly
* Executing the `./build.sh --target vsmac`
* Building from VSMac
  * Attempting to Debug/Launch the Control Gallery iOS project
  * Selecting Xamarin.Forms.Platform.csproj directly and building
  * Selecting Xamarin.Forms.Build.Tasks directly and building
* Building from command line
  * Building Xamarin.Forms.Build.Tasks directly
  * Building Xamarin.Forms.Platfrom directly

### What Worked
Instead of working with the latest and greatest code in the master branch I decided to checkout branch `4.2.0` and the build worked perfectly.

1. `git checkout 4.2.0`
2. `./build.sh --target vsmac`

Everything built and I was able to deploy

### Basic Information

- Version with issue: latest code at commit @ `c0a681e852ae360e5b40e27e3606d929166e1474`
- Last known good version: branch 4.2.0
- IDE: VSMac 8.2

I am thinking there was something introduced recently to the master code base that is causing issues building on macOS as branch 4.2.0 works as expected. I have attached build logs which may help in identifying the problem.

#### Mono Crash Logs
- [Mono_crash.zip](https://github.com/xamarin/Xamarin.Forms/files/3548919/Mono_crash.zip)

#### Useful Build Logs
- [msbuild-Xamarin.Forms.Platform.iOS.csproj.txt](https://github.com/xamarin/Xamarin.Forms/files/3548901/msbuild-Xamarin.Forms.Platform.iOS.csproj.txt)
- [msbuild-Xamarin.Forms.Platform.csproj.txt](https://github.com/xamarin/Xamarin.Forms/files/3548911/msbuild-Xamarin.Forms.Platform.csproj.txt)
- [msbuild-Xamarin.Forms.Build.Tasks.csproj.txt](https://github.com/xamarin/Xamarin.Forms/files/3548913/msbuild-Xamarin.Forms.Build.Tasks.csproj.txt)

**Comment by jfversluis** [comment]
Have you or could you maybe try on the 8.3 preview if that works?

**Comment by rmarinho** [comment]
Can you tell me what channel you are using in VS4mac ? Stable?

Can you post the info you see in  About Visual Studio -> Show Details

**Comment by radical** [comment]
I build the master branch with mono `6.0.0.327` from `2019-02` branch, and:

1. enable binary logger:
```
diff --git a/build.cake b/build.cake
index c52d4832b..8f0e6de10 100644
--- a/build.cake
+++ b/build.cake
@@ -195,6 +195,7 @@ MSBuildSettings GetMSBuildSettings()
     msbuildSettings.PlatformTarget = PlatformTarget.MSIL;
     msbuildSettings.MSBuildPlatform = (Cake.Common.Tools.MSBuild.MSBuildPlatform)1;
     msbuildSettings.Configuration = configuration;
+    msbuildSettings.EnableBinaryLogger();
     return msbuildSettings;

 }
```

2. `$ ./build.sh --target 
3. `$ msbuild /fl /flp:v=diag msbuild.binlog` - that generates a `msbuild.log`

Looking at that log, running `csc.exe` causes mono runtime to crash with https://gist.github.com/radical/314c384a5ab2209467d36e8a2f47ed85 .

```
...

* Assertion at aot-runtime.c:2564, condition `is_ok (error)' not met, function:decode_cached_class_info, Image out of date
...

	0x103c8a2a8 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_dump_native_crash_info
	0x103c24ac5 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_handle_native_crash
	0x7fff595f4b5d - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x4 - Unknown
	0x7fff594ae6a6 - /usr/lib/system/libsystem_c.dylib : abort
	0x103e918c7 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : monoeg_assert_abort
	0x103e732bf - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_log_write_logfile
	0x103e91c4e - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : monoeg_g_logv_nofree
	0x103e91dcf - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : monoeg_assertion_message
	0x103c09ded - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : decode_cached_class_info
	0x103c09ff0 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_aot_get_cached_class_info
	0x103d1937e - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_class_init_internal
	0x103b9a0e2 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_method_to_ir
	0x103b76b67 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mini_method_compile
	0x103b79c2c - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_jit_compile_method_inner
	0x103b7dc29 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_jit_compile_method_with_opt
	0x103c27914 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : common_call_trampoline
	0x103c27359 - /Library/Frameworks/Mono.framework/Versions/Current/Commands/mono : mono_magic_trampoline
	0x104022393 - Unknown
	0x1099e766b - Unknown

...
	  at <unknown> <0xffffffff>
	  at Microsoft.CodeAnalysis.Text.SourceText:From <0x001ba>
	  at Microsoft.CodeAnalysis.Text.EncodedStringText:Decode <0x00112>
	  at Microsoft.CodeAnalysis.Text.EncodedStringText:Create <0x000a2>
	  at Microsoft.CodeAnalysis.Text.EncodedStringText:Create <0x0006a>
	  at Microsoft.CodeAnalysis.CommonCompiler:TryReadFileContent <0x0017a>
	  at Microsoft.CodeAnalysis.CSharp.CSharpCompiler:ParseFile <0x000a6>
	  at <>c__DisplayClass8_0:<CreateCompilation>b__0 <0x00185>
	  at <>c__DisplayClass6_0`1:<WithCurrentUICulture>b__0 <0x0011f>
	  at <>c__DisplayClass19_0`1:<ForWorker>b__1 <0x0035e>
	  at Replica`1:ExecuteAction <0x00057>
	  at Replica:Execute <0x0007b>
	  at <>c:<.ctor>b__4_0 <0x00059>
	  at System.Threading.Tasks.Task:InnerInvoke <0x0008f>
	  at System.Threading.Tasks.Task:Execute <0x00037>
	  at System.Threading.Tasks.Task:ExecutionContextCallback <0x0005b>
	  at System.Threading.ExecutionContext:RunInternal <0x001a9>
	  at System.Threading.ExecutionContext:Run <0x00042>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x000f6>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000e8>
	  at System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem <0x00026>
	  at System.Threading.ThreadPoolWorkQueue:Dispatch <0x00279>
	  at System.Threading._ThreadPoolWaitCallback:PerformWaitCallback <0x0001c>
	  at <Module>:runtime_invoke_bool <0x000a5>

...
```

Deleting `/Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/4.5/Microsoft.CodeAnalysis.dll.dylib*` eliminates the crash, and the build succeeds.
I also tried this with the `2019-02` HEAD - `6.0.0.330`, but got the same results.

**Comment by radical** [comment]
This is `csc.exe` being run with `$ MONO_LOG_LEVEL=debug MONO_LOG_MASK=all mono --debug csc.exe ..` : https://gist.github.com/radical/3b9ca6497590b9327a79fb415903a5e2

**Comment by rmarinho** [comment]
We think this is a mono 6 issue.

**Comment by radical** [comment]
Bisecting the commits, we get `6.0.0.320` (test passes), `6.0.0.321` (failed to build on jenkins) and `6.0.0.322` fails the test case.
So, the offending commit should be - `b34d9e48f2184385f8af46086be7ea3848249fbe` or `0af2bb10d59b690253664a92b82abbb8d0eea8d6`.

Continuing with the message from the earlier comment - `....Unsafe doesn't match (expected 'B69B4731-65BE-4226-8B51-C633994B0D99', got 'BD600BA8-23B5-4D45-BA63-F24457FA3BE3')`,
looking at `$ strings /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/4.5/Microsoft.CodeAnalysis.dll.dylib`:

```
System.Runtime.CompilerServices.Unsafe
B69B4731-65BE-4226-8B51-C633994B0D99
```

^ this has the guid that was "expected".

- But the file on disk,
```
$ ikdasm /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/4.5/System.Runtime.CompilerServices.Unsafe.dll |grep MVID
// MVID: {BD600BA8-23B5-4D45-BA63-F24457FA3BE3}
```

.. has the "expected" GUID.

So, maybe the "bad" guid reference in `Microsoft.CodeAnalysis.dll.dylib` happened at build time.

- Looking at that the "good" assembly is what we have in `roslyn-binaries`.
- But we also build our own copy of `System.Runtime.CompilerServices.Unsafe.dll` from `.il` and that gets copied to the `net_4_x_-macos` and `build-macos` directories.
   - Why is this assembly built? Is that what we should be copying to the install prefix? Or if this is temporary, then maybe when `*CodeAnalysis.dll` is being aot'ed, it ends up
      referencing this built-from-il-assembly instead of the one from roslyn-binaries?

Building mono locally, to check the above:

```$ find . -name '*CodeAnalysis.dll.dylib'
./mcs/class/lib/net_4_x-macos/Microsoft.CodeAnalysis.dll.dylib.dSYM/Contents/Resources/DWARF/Microsoft.CodeAnalysis.dll.dylib
./mcs/class/lib/net_4_x-macos/Microsoft.CodeAnalysis.dll.dylib
./mcs/class/lib/build-macos/Microsoft.CodeAnalysis.dll.dylib.dSYM/Contents/Resources/DWARF/Microsoft.CodeAnalysis.dll.dylib
./mcs/class/lib/build-macos/Microsoft.CodeAnalysis.dll.dylib
```

- both these dylib files reference `System.Runtime.CompilerServices.Unsafe E4E7919C-A1EE-4658-996A-17C34D934842`

- And looking at what we have in:
```
$ ikdasm ./mcs/class/lib/net_4_x-macos/System.Runtime.CompilerServices.Unsafe.dll | grep MVID
// MVID: {E4E7919C-A1EE-4658-996A-17C34D934842}
```

^ - the same assembly that we generated is referenced here.

The installation ends up with the dylib with this reference, and a different `*Unsafe.dll` (from roslyn).

**Comment by vargaz** [comment]
How can I reproduce this ?

**Comment by radical** [comment]
@vargaz With mono `>=6.0.0.321` follow the 3 steps in  https://github.com/xamarin/Xamarin.Forms/issues/7297#issuecomment-525937316

**Comment by radical** [comment]
Once you hit the error, then for subsequent tests you can use just the full csc.exe invocation.

**Comment by ravinderjangra** [comment]
any workaround for solution for this. Unable to build XF from the code on macOS.

**Comment by rmarinho** [comment]
@ravinderjangra do you have stable channel updated ?

**Comment by ravinderjangra** [comment]
@rmarinho I am using `8.2.6 (build 26)`. it's latest stable.

**Comment by ravinderjangra** [comment]
Also the on build these files are generated
<img width="492" alt="Screenshot 2019-09-16 at 10 09 13 PM" src="https://user-images.githubusercontent.com/9795917/64976367-b4d17800-d8ce-11e9-8635-8245daf713fc.png">

**Comment by jfversluis** [comment]
@ravinderjangra It's more about the actual Mono version than about what version of VSMac in this case. I guess a workaround could be to install an additional Mono runtime but it might be a bit advanced, so not sure if that is something you want to look into :)

The generated files you are seeing are probably log files with additional diagnostic info whenever the build crashes.

**Comment by ravinderjangra** [comment]
hey @jfversluis, it'll be great if you point me to some reference for this. I'm fine with any additional installation/setup.

**Comment by knocte** [comment]
> @rmarinho I am using 8.2.6 (build 26). it's latest stable.

8.3.x is now in the stable channel, does anyone know if it helps with this?

**Comment by ravinderjangra** [comment]
hey @knocte, I tried it with latest VS for mac and it works fine.

**Comment by rmarinho** [comment]
Yap, if you are suing the latest sable it should work with mono
