### ISSUE TITLE
[Enhancement] Add CheckBox Text value

### ISSUE THREAD

**Issue by matibak** [xamarin/Xamarin.Forms#7299]
## Summary
Adding a text field to the checkbox would make it easy to set a label on it. Currently we need to add label separately and set them together in a `StackLayout`

## API Changes

        `<CheckBox x:Name="MyCheckBox"  Text="Option 1"/>`

## Intended Use Case
Adding a text field to checkbox would make it easy to set a label on it and it would save additional lines of code where we need to put both label and checkbox in `StackLayout`

**Comment by IngweLand** [comment]
Having CheckBox control without Text property is a strange implementation decision. Let's see what other platforms have:

Android - has it
iOS - does not have check box
UWP - has it
WPF - has it

Of course, we can write custom controls or custom renderers for many things... But then we could write same thing for current implementation of CheckBox...

**Comment by mohitatray** [comment]
Displaying text next to CheckBox is very easy with a StackLayout. But what I want is when the text is clicked, the CheckBox should check/uncheck (toggle). Not only it should toggle but also it should give the proper feel of clicking - when text is pressed, the checkbox background should change to the pressed background.

That is why I think text should be integrated in CheckBox. Something like a CheckBoxCell can also be implemented.

**Comment by tbrentlong** [comment]
I agree. This seems like pretty basic functionality; odd that it is missing.

**Comment by IgorKravchenko10** [comment]
This is useful property. And we almost have Text property in RadioButton. In my opinion this property will be useful in Switch too.

**Comment by jcmanke** [comment]
Maybe copy the approach from #11628 - Make Checkbox a TemplatedView that allows setting text or any other sort of content?

**Comment by hartez** [comment]
> Maybe copy the approach from #11628 - Make Checkbox a TemplatedView that allows setting text or any other sort of content?

If the approach in 11628 works out, that's likely what we'd end up doing. The main reason we didn't want to add a `Text` property for CheckBox was placement; if folks have the option of specifying a custom template and putting the Label wherever they want in relation to the CheckBox, that problem is solved.
