### ISSUE TITLE
[Bug] App crashes after updating to v4.2.0.709249

### ISSUE THREAD

**Issue by anpin** [xamarin/Xamarin.Forms#7301]
### Description
After updating to v4.2.0.709249 from v4.1.0.709244 the app is immediately crashing on startup with the following exception 
`
 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x20 in Android.Runtime.DynamicMethodNameCounter.9	C#
 	0x1 in Xamarin.Forms.Platform.Android.AppCompat.Platform.op_Implicit at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:491,4	C#
 	0x3B in Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:221,4	C#
 	0xA in Android.App.Activity.n_OnDestroy	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.9	C#

`
### Steps to Reproduce

1. Update Xamarin.Forms nuget package to v4.2.0.709249
2. Start an app
3. 

### Expected Behavior
App starts 

### Actual Behavior
App crashes
### Basic Information

- Version with issue:  v4.2.0.709249 f
- Last known good version: v4.1.0.709244 
- IDE: Visual Studio 2019 16.2.3
- Platform Target Frameworks: 
  - Android: 28
- Android Support Library Version:  28.0.0.1

**Comment by anpin** [comment]
someone [here](https://forums.xamarin.com/discussion/167659/xamarin-forms-4-2-incompatibility) is having the same problem

**Comment by rscholey** [comment]
Similar to this problem I am experiencing?

https://github.com/xamarin/Xamarin.Forms/issues/7286

Having to downgrade now.  This version is unusable for me

**Comment by bentmar** [comment]
Do you have a splashactivity?
is that activity a FormsAppCompatActivity?

if so, change it to a standard android AppCompatActivity

**Comment by WilliamWatterson86** [comment]
@bentmar - that seems to work for me too.  Is there any side effect of doing this do you think?

**Comment by rmarinho** [comment]
@anpin  @bentmar can you please provide a small repo so we can investigate further.

Thanks

**Comment by pengalo** [comment]
My issue is similar (related?), but instead of crashing on startup, it crashes when going back to the launcher:
Visual Studio 2019 on Windows 10, Google Pixel 2
1. In VS 2019, create new Mobile App (Xamarin.Forms) project
2. Pick Shell template with all defaults (defaults to Xamarin.Forms 4.1)
3. Run debug version on device (mine is a Pixel 2)
4. Click system back button to return to system launcher
5. App works fine and you can switch back to the app
6. Upgrade Xamarin.Forms NuGet to latest 4.2
7. Run again in debug
8. Click back like before
9. Now it gets null reference exception

**Comment by anpin** [comment]
App is not crashing with a new blank project with XF v4.2.0.709249, but if I'm adding a splash activity to the app it crashes with the same error right after MainActivity is shown
` 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C#
 	0x20 in Android.Runtime.DynamicMethodNameCounter.9	C#
 	0x1 in Xamarin.Forms.Platform.Android.AppCompat.Platform.op_Implicit at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:491,4	C#
 	0x3B in Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:221,4	C#
 	0xA in Android.App.Activity.n_OnDestroy	C#
 	0x11 in Android.Runtime.DynamicMethodNameCounter.9	C#
`
Sample project with error is in attach
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3556810/App1.zip)

**Comment by bentmar** [comment]
To pinpoint the issue it seems that calling on destroy in a FormsAppCompatActivity gives us a crash in latest XF. 

For all of you using splashacitivities use AppCompatActivity instead of the FormsAppCompatActivity.

@WilliamWatterson86 since youre probably not using anything Xamarin.Forms related in your splashactivity there will be no problem with this.

**Comment by SR84** [comment]
Same here: 

  at Java.Interop.JniPeerMembers/JniInstanceMethods.InvokeVirtualVoidMethod (string,Java.Interop.IJavaPeerable,Java.Interop.JniArgumentValue*) [0x0005f] in <a28ef992ef1c47dba4efa3bd75e0a265>:0
  at Android.App.Activity.OnDestroy () [0x00012] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy () [0x00060] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\**FormsAppCompatActivity.cs:228**
  at Android.App.Activity.n_OnDestroy (intptr,intptr) [0x0000a] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.24 (intptr,intptr) [0x00011] in <b62c3fba3fe848f3bb323dbe33464223>:0
  at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.24 (intptr,intptr) [0x00033] in <b62c3fba3fe848f3bb323dbe33464223>:0

**Comment by SR84** [comment]
@rmarinho 

> App is not crashing with a new blank project with XF v4.2.0.709249, but if I'm adding a splash activity to the app it crashes with the same error right after MainActivity is shown
> `	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C# 0x1 in System.Diagnostics.Debugger.Mono_UnhandledException	C# 0x20 in Android.Runtime.DynamicMethodNameCounter.9	C# 0x1 in Xamarin.Forms.Platform.Android.AppCompat.Platform.op_Implicit at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:491,4	C# 0x3B in Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:221,4	C# 0xA in Android.App.Activity.n_OnDestroy	C# 0x11 in Android.Runtime.DynamicMethodNameCounter.9	C#`
> Sample project with error is in attach
> [App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3556810/App1.zip)

**Comment by Phenek** [comment]
> someone [here](https://forums.xamarin.com/discussion/167659/xamarin-forms-4-2-incompatibility) is having the same problem

Yeah I got the same issue as @anpin during my SplashScreen OnDestroy() Activity

**Comment by DevEddy** [comment]
Same here

```csharp
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.Platform.op_Implicit (Xamarin.Forms.Platform.Android.AppCompat.Platform canvas) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:491 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy () [0x0002f] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:221 
[MonoDroid]   at Android.App.Activity.n_OnDestroy (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <14fc11fa46a741ab9dde75db7823aece>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.17(intptr,intptr)
```

**Comment by samhouts** [comment]
Probably caused by https://github.com/xamarin/Xamarin.Forms/pull/6467

**Comment by alessandrofrancesconi** [comment]
> 
> 
> I had the exact issue, fixed it by changing my splashactivity from FormsAppCompatActivity to AppCompatActivity

I've also solved this way

**Comment by kingces95** [comment]
#7706 Should fix this. If not, please re-open.
