### ISSUE TITLE
Proposal: Simplify Grid Column and Row Definitions

### ISSUE THREAD

**Issue by dotMorten** [xamarin/Xamarin.Forms#7302]
## Summary
WinUI is adding a simplified syntax to setting column and row definitions on Grid. Xamarin.Forms should add this too.

### Current syntax
```xml
<Grid>
    <Grid.ColumnDefinitions>
          <ColumnDefinition Width="1*" />
          <ColumnDefinition Width="2*" />
          <ColumnDefinition Width="Auto" />
          <ColumnDefinition Width="*" />
          <ColumnDefinition Width="300" />
    </Grid.ColumnDefinitions>
    <Grid.RowDefinitions>
          <RowDefinition Height="1*" />
          <RowDefinition Height="Auto" />
          <RowDefinition Height="25" />
          <RowDefinition Height= "14" />
          <RowDefinition Height="20" />
    </Grid.RowDefinitions>
</Grid>
```
### Proposed Syntax
The same functionality as above with the proposed succinct syntax is shown below:
```xml
<Grid ColumnDefinitions="1*, 2*, Auto, *, 300" RowDefinitions="1*, Auto, 25, 14, 20"/>
```
Full spec described here: https://github.com/microsoft/microsoft-ui-xaml/issues/673 (design is currently being finalized)

## API Changes
Follow the same specification implemented by WinUI (probably no new APIs, unless it needs a new type-converter)

## Intended Use Case
Developer productivity

**Comment by StephaneDelcroix** [comment]
already been proposed in #4997

**Comment by dotMorten** [comment]
@StephaneDelcroix That looks like a very different approach to me.

**Comment by Nullstr1ng** [comment]
![image](https://user-images.githubusercontent.com/260633/78550562-ded09480-7836-11ea-9889-d2a9461f28b1.png)
I just made an attached attribute for the mean time.

**Comment by SmartmanApps** [comment]
The given example is all in XAML - please remember to apply any simplified syntax to C# UI as well! Last stat I saw was about 25-33% of devs writing their UI in code.

**Comment by krdmllr** [comment]
While we are on it, we could replace "Auto" with a special character like &, _ , 🚗 or something.

`ColumnDefinitions="1*, 2*, Auto, *, 300"`
->
`ColumnDefinitions="1*, 2*, &, *, 300"`

A really minor thing but I always wanted something like that :p

**Comment by krdmllr** [comment]
> The given example is all in XAML - please remember to apply any simplified syntax to C# UI as well! Last stat I saw was about 25-33% of devs writing their UI in code.

An overload of the Columnd/RowDefinitions ctor, like: 

`... = new ColumnDefinitions("Auto", "1*", 150, "*")`

**Comment by dotMorten** [comment]
Again please consider suggesting that in the WinUI design spec linked above.  IMHO the specs should try and stay in sync so they don't unnecessarily diverge more than necessary

**Comment by dotMorten** [comment]
@krdmllr that overload wouldn't work as it would clash with the existing constructors. This implementation will most likely be done with a type converter, so you could just use that instead

**Comment by krdmllr** [comment]
@dotMorten yeah I think the `Auto` thing is something quite subjective. I just always found it odd that `*` existed but nothing was in place for `Auto`. 

Sorry, the correct class would be [ColumnDefinitionCollection](https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Core/ColumnDefinitionCollection.cs). Adding a constructor which calls the converter should work there, right?

**Comment by MichaelRumpler** [comment]
I'm 100% with @dotMorten here that the differences between UWP, WPF and Xamarin.Forms should be as small as possible. There should not be additional differences introduced. This would help a lot in learning a new XAML dialect.

If the Xamarin team could just decide whether to do this proposal or #4997 (which @StephaneDelcroix linked) then the community could implement it and add a PR.

**Comment by samhouts** [comment]
see #4997, too
