### ISSUE TITLE
[Bug] Calling Page.DisplayAlert results in java.lang.RuntimeException: thread has not called Looper.prepare()

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#7307]
### Description

I'm seeing crashes in AppCenter that appear to involve a call to Page.DisplayAlert ultimately resulting in a java.lang.RuntimeException that appears to be saying that the call wasn't made on the UI thread. Needless to say, from Xamarin Forms' perspective, the call is on the main UI thread.

If I'm misinterpreting this, please let me know.

### Steps to Reproduce

Unclear.

### Expected Behavior

UI events dispatched by Xamarin Forms are on the main thread.

### Actual Behavior

Stack traces from AppCenter:

```
JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters)
AlertDialog+Builder.Create ()
PopupManager+PopupRequestHelper.OnAlertRequested (Xamarin.Forms.Page sender, Xamarin.Forms.Internals.AlertArguments arguments)
(wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-15,10,main] that has not called Looper.prepare()
android.os.Handler.<init> Handler.java:205
android.os.Handler.<init> Handler.java:118
android.app.Dialog.<init> Dialog.java:129
android.app.AlertDialog.<init> AlertDialog.java:234
android.app.AlertDialog$Builder.create AlertDialog.java:1193

RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)
MethodBase.Invoke (System.Object obj, System.Object[] parameters)
MessagingCenter+Subscription.InvokeCallback (System.Object sender, System.Object args)
MessagingCenter.InnerSend (System.String message, System.Type senderType, System.Type argType, System.Object sender, System.Object args)
IMessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args)
MessagingCenter.Send[TSender,TArgs] (TSender sender, System.String message, TArgs args)
Page.DisplayAlert (System.String title, System.String message, System.String accept, System.String cancel)
Page.DisplayAlert (System.String title, System.String message, System.String cancel)
PageBase.SignInAsync ()
SettingsPage.SignIn_Clicked (System.Object sender, System.EventArgs e)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.39(intptr,intptr)
```

### Basic Information

- Version with issue: 4.1.0.673156
- Last known good version: N/A
- IDE:
- Platform Target Frameworks: 
  - Android: 8, 9
- Android Support Library Version: 71.1712.0

**Comment by matejvlk** [comment]
I am experiencing similar thred related issues. My application started crashing on exceptions like "Only the original thread that created a view hierarchy can touch its views.", "Must be called from main thread of fragment host", "Can't toast on a thread that has not called Looper.Prepare()". I found out, that this started happening after updating to Visual Studio 16.2.0 or higher (16.2.0, 16.2.1, 16.2.2, 16.2.3 has this issue). So right now, I am developing on Visual Studio 2017 (15.9.14) and it works fine. If anybody has an idea what changed in new VS or what to do next (wait for VS2019 fix, try to fix my app to work on VS2019, report the issue in VS, ...) please let me know :)

**Comment by mfeingol** [comment]
@matejvlk: do you have a simple repro, by any chance?

**Comment by rmarinho** [comment]
Can you please provide a small sample so we can investigate. 

Thanks

**Comment by samhouts** [comment]
@mfeingol  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by mfeingol** [comment]
Haven't seen a crash report on this lately, so hopefully it was either an outlier or something addressed in recent updates to XF.
