### ISSUE TITLE
[Bug] WebView.Reload does not work

### ISSUE THREAD

**Issue by matibak** [xamarin/Xamarin.Forms#7312]
### Description
When I set a new value of WebView's source and call Reload() method the page that was set initially gets refreshed.
### Steps to Reproduce

1. Set a new address to a WebView, e.g. `webView.Source = new UrlWebViewSource { Url = "https://www.youtube.com" };`
2. Reload it with `webView.Reload();`

### Expected Behavior
When I set a new value of WebView's source and call Reload() method the new page loads into WebView.
### Actual Behavior
When I set a new value of WebView's source and call Reload() method the page that was set initially gets refreshed.
### Basic Information

- Version with issue: 4.2.0.618605-pre2
- Last known good version: unknown
- IDE: Visual Studio Community 2019 for Mac (Preview) Version 8.3 Preview (8.3 build 1290)
- Platform Target Frameworks:
  - iOS:  12.1
  - Android: API 28
- Nuget Packages:
- Affected Devices: 

### Screenshots

![WebView Reload Bug](https://media.giphy.com/media/H6tQToKOunQ2AoNVBt/giphy.gif)

### Reproduction Link

[WebViewReloadBug](https://github.com/matibak/WebViewReloadBug)

**Comment by rmarinho** [comment]
Why are you calling Reload? just setting source  updates to the Youtube url no need to call `Reload`.

**Comment by postnik0706** [comment]
@rmarinho @samhouts OP was probably calling Reload() as an attempt to get Source assignment work. Nothing of that works, actually. The web page is not updated.

**Comment by postnik0706** [comment]
Scheduling Source property assignment with Dispatcher works - even though the original code was executing in the main thread. Below is what worked for me.

```
        private void NextButton_OnClicked(object sender, EventArgs e)
        {
            MainThread.BeginInvokeOnMainThread(() =>
               {
                   webView.Source = new UrlWebViewSource { Url = "https://www.youtube.com" };
               });
        }
```
