### ISSUE TITLE
[Bug] FontImageSource don't work on wpf

### ISSUE THREAD

**Issue by observer1** [xamarin/Xamarin.Forms#7320]
### Description
Using a FontImageSource on a project that is started with a WPF frontend the image or imagebutton control don't display the symbol
### Steps to Reproduce
Put an imagebutton control in a page and use a fontimagesource as the source of the image
### Expected Behavior
The symbol is displayed
### Actual Behavior
The symbol is not displayed
### Basic Information

- Version with issue:
4.2.0.709249
- Last known good version:
- IDE:
Visual studio 2019
- Platform Target Frameworks: 
WPF
- Android Support Library Version: 
NA
- Nuget Packages:
Xamarin.Forms
Xamarin.Forms.Platform.WPF
- Affected Devices:
Windows 10 PC 

### Reproduction Link
[Test.zip](https://github.com/xamarin/Xamarin.Forms/files/3557986/Test.zip)

**Comment by yurkinh** [comment]
FontImageSourceHandler was taken from  [XamarinPlayer](https://github.com/sakib1361/XamarinPlayer/blob/master/XamarinPlayer/XamarinPlayer.Wpf/Renderer/FontImageSourceRenderer.cs) made by @sakib1361
