### ISSUE TITLE
[Bug] Error Domain=NSURLErrorDomain Code=-1009 "Internet connection appears to be offline" when using device internet connection - ios- (xamarin forms 4.2)

### ISSUE THREAD

**Issue by elierlopez** [xamarin/Xamarin.Forms#7322]
### Description
 Error Domain=NSURLErrorDomain Code=-1009 "Internet connection appears to be offline" when using device internet connection (xamarin forms 4.2)
### Steps to Reproduce

1. Deployed my app to ios device using a wildcard provisioning profile created with my apple developer program subscription.

2. I ran the app with wifi turned off

3. I got Error Domain=NSURLErrorDomain Code=-1009 "Internet connection appears to be offline" when using device internet connection   

### Expected Behavior
It should to work and consume the device internet access as it did when using xamarin forms 3.4
The issue started happening after I upgraded to xamarin forms 4.1

### Basic Information

- Version with issue: X.F 4.1 and 4.2 
- Last known good version:
- IDE: Visual studio for mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by SebastianKruseWago** [comment]
I have reports in my 3 apps using XF 4.1 or 4.2 too, so I can confirm this issue. There are also other Network related errors poping up since 4.1 so I think they are all of the same source.

**Comment by samhouts** [comment]
@elierlopez  @SebastianKruseWago  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by elierlopez** [comment]
Hi @samhouts. Sorry for the long delay.

Unfortunatelly I am not able to share a project with the Provisioning profile I am using.
And around the code (httpclient  usage) I am using there is nothing special to share.

 it is a simple http get call like shown below:


        public async Task<string> GetAsync(string url)
        {
            string result = string.Empty;
            using (var client = new HttpClient())
            {
                client.Timeout = TimeSpan.FromSeconds(60);
                var response = await client.GetAsync(url);
                response.EnsureSuccessStatusCode();
                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    if (!string.IsNullOrWhiteSpace(content))
                        result = content;
                }

                return result;
            }
        }


The above method is passed with certain url and then the error occurs.
As per mentioned there is nothing special/tricky or sophisticated  in my code.
That's why I am sure something is wrong in XF lib 4.1, 4.2

**Comment by samhouts** [comment]
@elierlopez Also, you are welcome to share a basic project with no provisioning profile attached.

**Comment by elierlopez** [comment]
Hi @samhouts thanks for following up.
As per I previously reported this issue also in developer community, they resolved the issue

And yes it looks like it had to do with xamarin.ios and/or mono
In summary the issue should be solved from xamarin preview 7

Please  find more details in [this link](https://developercommunity.visualstudio.com/content/problem/718032/error-domainnsurlerrordomain-code-1009-internet-co.html)
