### ISSUE TITLE
[Bug] Xamarin Forms label - Span size change not working for iOS #5607

### ISSUE THREAD

**Issue by dgandhi17** [xamarin/Xamarin.Forms#7326]
### Steps to Reproduce
Create sample solution having label with spans with arabic or spanish language.

### Expected Behavior
Click should work

### Actual Behavior
Click is not working

### Basic Information

- Version with issue: 3.6
- Last known good version: Not working at all
- IDE: Visual Studio 2019/2017 Enterpise
- Platform Target Frameworks: 
  - iOS:  iOS all version

- Affected Devices: All iOS devices

**Comment by StephaneDelcroix** [comment]
please provide a reproduction project. Thanks

**Comment by dgandhi17** [comment]
@StephaneDelcroix Create sample app which has arabic locale support and it has label has with 2-3 spans. Than change language of device to arabic and open the app. check if span text are clickable or not

**Comment by samhouts** [comment]
@dgandhi17  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@dgandhi17  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
