### ISSUE TITLE
[Bug] Android Activity crashes when calling finish before Forms.Init

### ISSUE THREAD

**Issue by acvien1234** [xamarin/Xamarin.Forms#7331]
### Steps to Reproduce

1. On Android Activity after base.OnCreate, call Finish and return 

### Expected Behavior
It should not need to call Xamarin.Forms.Init because it does not to render Xamarin page. The reason we are doing this is sometimes we are passing extra parameter to indicate the step has finished without rendering. This used to work prior to Xamarin 4.0. After upgrading to 4.2, it does not work anymore.

### Actual Behavior
Android App crashes on dispose. 

System.NullReferenceException: Object reference not set to an instance of an object.
at Xamarin.Forms.Platform.Android.AppCompat.Platform.op_Implicit (Xamarin.Forms.Platform.Android.AppCompat.Platform canvas) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\Platform.cs:488 
08-30 21:17:42.294 I/MonoDroid(20609):   at Xamarin.Forms.Platform.Android.FormsAppCompatActivity.OnDestroy () [0x00025] in Xamarin.Forms.Platform.Android\AppCompat\FormsAppCompatActivity.cs:214 
at Android.App.Activity.n_OnDestroy (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <fc1f547b51c6476996598e4a1bf2fc5f>:0 
 at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.9(intptr,intptr)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Form version 4.2.0.618605
- Affected Devices:

[Bug7331.zip](https://github.com/xamarin/Xamarin.Forms/files/3561683/Bug7331.zip)

I was not able to compile Xamarin Forms to Nuget package. Here is the link with the potential fix. 
https://github.com/acvien1234/Xamarin.Forms.git

**Comment by slang25** [comment]
We have hit this after upgrading to 4.2.

A little more info here from local diagnosing, when `OnDestroy` is call in `FormsAppCompatActivity` and hits this line:
https://github.com/xamarin/Xamarin.Forms/blob/a6f285242582081d02c0e19724671a04afe8211e/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs#L221
`Platform` is `null`, so the implicit conversion throws a NRE.

**Comment by slang25** [comment]
There are others hitting this issue here: https://forums.xamarin.com/discussion/167659/xamarin-forms-4-2-incompatibility
