### ISSUE TITLE
[Bug] Material Visual and Frames break in Shell

### ISSUE THREAD

**Issue by loomtronic** [xamarin/Xamarin.Forms#7339]
### Description
When loading a page from the Flyout tab for the second time that has a Frame and is marked as Visual="Material", the app will crash 

### Steps to Reproduce

1.  Create a page using Shell, and in the flyout use a DataTemplate for the ContentTemplate (like ContentTemplate="{DataTemplate views:SomePage}") and set Visual="Material" in the page
2. Add a frame to the page
3. Open the app
4. Navigate to the page with the frame.
5. Navigate home
6. Navigate back to the page from the Flyout menu.  App will crash.
7. Remove the Visual="Material" tag
8. Load app again
9. Repeat steps for generating error, but it doesn't happen

### Expected Behavior
Page would load a second time
### Actual Behavior
App crashes with error System.ObjectDisposedException
  Message=Cannot access a disposed object.
Object name: 'MaterialFrameRenderer'.

### Basic Information

- Version with issue: 4.1.0+
- Last known good version: 3.5 (maybe)
- IDE: VS2019 16.2
- Platform Target Frameworks: 
  - iOS:  12.4
  - Android: Have not tried
  - UWP:  Have not tried

### Screenshots

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1706404/64069225-39977300-cbfa-11e9-8dea-cf625ec35ba6.png">

**Comment by samhouts** [comment]
@loomtronic  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by loomtronic** [comment]
I'll try but it's pretty much just an app with Shell and then creating a page and putting Visual="Material" at the top and adding a frame to the page and running.  Every page I have shell and a Frame in with Material enabled does this.

**Comment by edamreed** [comment]
Any idea when this fix will make it to the stable release?
