### ISSUE TITLE
[Bug] [UWP] In MasterDetail if DetailPage is NavigationPage TabbedPage the NavigationBar/Menu DISAPPEAR

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/Xamarin.Forms#7341]
### Description

I have an app wherein there is a MasterDetail page, and one of the Detail Pages is a Tabbed Page (wrapped in a Navigation Page). On iOS and Android, when I navigate to this Tabbed page, the NavigationBar and the Master hamburger menu are visible and accessible as expected. However, only on UWP, when I navigate to this TabbedPage, the NavigationBar and Master Menu disappear, and user is stuck there no longer able to access that menu to navigate to other pages.

### Steps to Reproduce

1. Create a MasterDetail Page and add to it a normal NavigationPage as well as a TabbedPage NavigationPage
2. Navigate to the TabbedPage when running on UWP
3. Observe the NavigationBar and Master Menu icon disappear

### Expected Behavior

NavigationBar and Master Menu hamburger icon in UWP are still visible when viewing the TabbedPage as a Detail page.

### Actual Behavior

NavigationBar and Master Menu hamburger icon in UWP disappear when viewing the TabbedPage as a Detail page.

### Basic Information

- Version with issue:
- Last known good version: unsure
- IDE: VS2019 Enterprise latest
- Platform Target Frameworks: 
  - iOS:  works on all
  - Android: works on all
  - UWP:  does NOT work on 1809 nor 1903

- Nuget Packages: Xamarin.Forms and Prism
- Affected Devices: UWP desktop

**Comment by samhouts** [comment]
@mzhukovs  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mzhukovs** [comment]
Through this exercise in recreation, I have determined that the culprit lies in setting MasterBehavior="Popover" on the MasterDetailPage. Here is a full sample:
[NavBarTabbedPageUWPissue.zip](https://github.com/xamarin/Xamarin.Forms/files/3574544/NavBarTabbedPageUWPissue.zip)

**Comment by Elashi** [comment]
I am having the same problem, also the backbutton disappeared

**Comment by mzhukovs** [comment]
@samhouts @davidortinau do you guys think this will be addressed soon? UWP seems to be getting left behind, which is sad because I believe many value this as one of the supported platforms - I hope that this is not the case, but some of the outstanding issues are fairly major (e.g. Shell support, or even something so common as this [issue](https://github.com/xamarin/Xamarin.Forms/issues/5661)). Please let me know when you get a chance and thanks regardless.

**Comment by mzhukovs** [comment]
Is this one in the pipeline?

**Comment by Sonic3R** [comment]
I have same issue, when will be included and in which version ?

**Comment by mzhukovs** [comment]
@jfversluis  thoughts? Forgive me for bugging you about it but I saw you helped close the other UWP issue that I referenced here with the nav button. Any insight would be much appreciated, even if it's just that this isn't a priority. Thanks in advance!

**Comment by jfversluis** [comment]
Hey @mzhukovs no worries! I'm here to help! :) I took some time to look into this, and I put together a small sample with plain Xamarin.Forms, the latest stable at this time. You can find it attached.

It looks like that just works, so maybe one of the other NuGets does something? 

[Repro7341.zip](https://github.com/xamarin/Xamarin.Forms/files/3967239/Repro7341.zip)

**Comment by mzhukovs** [comment]
@jfversluis thank you for looking into it. The plot thickens, I added **MasterBehavior="Popover"** to the MasterDetailPage as that seemed to be the thing that was causing it in my repro but doing so in yours still works.... perhaps then it is a Prism navigation-related issue. I will raise it there.

**Comment by jfversluis** [comment]
Thanks for the investigation. If there's anything more you need from us, please let us know!
