### ISSUE TITLE
Change Page to be an interface (eg IPage) in INavigation interface

### ISSUE THREAD

**Issue by nickrandolph** [xamarin/Xamarin.Forms#7344]
## Summary
Currently INavigation references the concrete Page class, making it hard to mock the INavigation interface as part of testing

## API Changes

Define new interface for Page class (eg IPage)
Change INavigation to use IPage in place of Page

## Intended Use Case
INavigation interface can be used by developers to invoke navigation within their ViewModel. However, this currently makes their ViewModel untestable since INavigation can't be mocked.

**Comment by samhouts** [comment]
This would be a breaking change. Is there another way we could accomplish this?

**Comment by nickrandolph** [comment]
yes and no
Yes, you _could_ introduce a different interface eg INavigationEx
No, you should **not** be the person to add unnecessary interfaces just because it's a breaking change. 
Tbh raising this as a feature was wrong, imho it's a bug and as such the fix should address the cause of the problem (ie INavigation was created with concrete types) instead of a patch fix (eg creating a different interface)

**Comment by jcmanke** [comment]
Why do you need to mock the Page that you're passing as a parameter into an INavigation method? What would an IPage interface even contain?

**Comment by nickrandolph** [comment]
Actually the need for IPage is more a function of being able to write code that is testable. Take my post at https://nicksnettravels.builttoroam.com/mvvm-navigation/ where I present a mechanism for navigating between pages based on view model events. Right now it's very tied to hard coded page instances but I'd like to be able to extract the logic so that it's more testable - this can't be done without the introduction of IPage.

In terms of the IPage interface  - for what I was doing I don't need any specific methods/properties in the interface, as my logic wasn't dependent on that. However, if you were going to update INavigation to use IPage, then you'd need to go through XF and look for all places where INavigation is used and then look at why it was necessary to rely on a concrete Page. This will probably define the initial candidate for the IPage interface.

**Comment by jfversluis** [comment]
Interfaces everywhere in .NET MAUI! ;)

Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
