### ISSUE TITLE
[Bug] Large Titles not working in iOS 13

### ISSUE THREAD

**Issue by steven-pearson** [xamarin/Xamarin.Forms#7350]
### Description

Take Xamarin.Forms sample, add the large titles to nav page, fails to show on iOS 13

https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/TabbedPageWithNavigationPage

1. Set the navigation page to prefer large titles
2. Set the schedulepage.xaml to have large, set the upcomingappointmentspage.xaml to never show large
3. Run on iOS 12 and iOS 13 to compare

iOS 13 should behave as 12 and show titles as expected

iOS 13 shows nothing in navigation bar. 

### Basic Information

- Version with issue: 4.2.0.709249+ios13
- Last known good version:4.2.0.709249+ios12
- IDE:vs4mac
- Platform Target Frameworks: 
  - iOS:  13
- Nuget Packages:
- Affected Devices:all ios

### Screenshots

Short video of issue
https://www.dropbox.com/s/0ptzu3ychwinnk8/nolargetitles.mov?dl=0

**Comment by dmarjoram** [comment]
This I believe is related to the new iOS 13 UINavigationBarAppearance including standardAppearance and scrollEdgeAppearance which are not supported properly by Xamarin Forms.

**Comment by Jeff-Bridges** [comment]
We've worked around this issue by doing the following in a custom renderer for NavigationPage:

			var barBackgroundColor = NavPage.BarBackgroundColor;
			NavigationBar.StandardAppearance.BackgroundColor = barBackgroundColor == Color.Default
				? UINavigationBar.Appearance.BarTintColor
				: barBackgroundColor.ToUIColor();

			NavigationBar.StandardAppearance.TitleTextAttributes = NavigationBar.TitleTextAttributes;
			NavigationBar.StandardAppearance.LargeTitleTextAttributes = NavigationBar.LargeTitleTextAttributes;

			NavigationBar.ScrollEdgeAppearance = NavigationBar.StandardAppearance;

**Comment by awaescher** [comment]
You saved my life, @Jeff-Bridges. Here's what the whole renderer looks like

```
using NAMESPACE.iOS.Renderers;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(NavigationPage), typeof(LargeHeaderFixingNavigationPageRenderer))]
namespace NAMESPACE.iOS.Renderers
{
    public class LargeHeaderFixingNavigationPageRenderer : NavigationRenderer
    {
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            if (Element is NavigationPage navigationPage)
            {
                var barBackgroundColor = navigationPage.BarBackgroundColor;

                NavigationBar.StandardAppearance.BackgroundColor = barBackgroundColor == Color.Default
                    ? UINavigationBar.Appearance.BarTintColor
                    : barBackgroundColor.ToUIColor();

                NavigationBar.StandardAppearance.TitleTextAttributes = NavigationBar.TitleTextAttributes;
                NavigationBar.StandardAppearance.LargeTitleTextAttributes = NavigationBar.LargeTitleTextAttributes;
                NavigationBar.ScrollEdgeAppearance = NavigationBar.StandardAppearance;
            }
        }
    }
}

```

**Comment by mnidhk** [comment]
Have the same issue with background color isn't working with Large Titles.
The workaround mentioned above works great.

But I just find out that the latest iOS 13.2 beta it restores the behavior like before.
On this beta, everything looks solved/ok with my unchanged apps
So maybe more an iOS13 bug instead of Xamarin?!

**Comment by adrianknight89** [comment]
> But I just find out that the latest iOS 13.2 beta it restores the behavior like before.
> On this beta, everything looks solved/ok with my unchanged apps
> So maybe more an iOS13 bug instead of Xamarin?!

My phone has gotten only 13.1.3 so far, and I can see the issue described here. So, if I understand you correctly, your published apps still use 12 and that's why they are working as expected?

**Comment by mnidhk** [comment]
Correct! So for apps, compiled with ios12, there is a patch by Apple automatically. New compiled apps with iOS 13 are still affected with this issue, also in beta 13.2.

**Comment by adrianknight89** [comment]
OK. I submitted a PR to fix this issue.
