### ISSUE TITLE
Toolbar Item not show when use tabbed page in shell

### ISSUE THREAD

**Issue by eramrit78** [xamarin/Xamarin.Forms#7351]
### Description
Hi I am try to add toolbar item in Tabbed Page under a one tab. but it not show. it show me blank area.

### Steps to Reproduce

```
> <ContentPage.ToolbarItems>
>         <ToolbarItem Text="Add" Clicked="ToolbarItem_Clicked" Order="Primary"  /> </ContentPage.ToolbarItems>
```

### Expected Behavior
It should be display toolbar item of right corner with title.
### Actual Behavior
Not hsow
### Basic Information

- Version with issue: 4.1, 4.2
- Last known good version: 
- IDE: Visual Studio 2019 CE
- Platform Target Frameworks: 
  - iOS:  IOS also
  - Android: Android  SDK 28
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

![Screenshot_1567427053](https://user-images.githubusercontent.com/48124576/64114764-748cd880-cdab-11e9-8066-5b6342a13aad.png)

**Comment by Depechie** [comment]
I think I face the same problem.
It occurs when bottom and top tabs are defined in the shell.
Added project to reproduce and a movie showing the effect.
It's still happening with XF 4.2.0.778463

[XamarinShellDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/3612560/XamarinShellDemo.zip)
[ShellTabs.mov.zip](https://github.com/xamarin/Xamarin.Forms/files/3612563/ShellTabs.mov.zip)

**Comment by eramrit78** [comment]
Face this issue in all projects which used shell 4.x

**Comment by hartez** [comment]
@eramrit78 I am having difficulty reproducing this problem. I have added a ToolbarItem to the About page in my sample project, and the button shows up. I have attached my project - can you tell me what I am missing?

[_7351 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3648866/_7351.Repro.zip)

**Comment by eramrit78** [comment]
Hi hartez, I m sent you the issued in attached project. there are 2 issues in this project.

1. Toolbar not work on tabbed page with shell.
2. Three dots not come if toolbar use more than one item in content and tabbed pages.

Thanks

[_7351.zip](https://github.com/xamarin/Xamarin.Forms/files/3649981/_7351.zip)

**Comment by Depechie** [comment]
@hartez did you try my sample? When you switch top tabs from the 1th to the 2nd on the first bottom tab, the toolbar item does no go away ( incorrect behaviour it is only defined on the ITEMS page not on the ABOUT page ).
Weird thing if you go back to the first top tab, the toolbar item will not reappear ( it should ). And going back to the 2nd top tab it comes on again ( again wrong ).

Or do you rather want met to file a new bug?
Tested again with XF 4.2.0.815419

**Comment by eramrit78** [comment]
Yes I m try your sample. and it give same issue under version 4.2.0.815419.

**Comment by eramrit78** [comment]
Now what you need. info already provided. with attached project. the issue come me in every project in version 4.x  with shell in tabbed page. sample attached.

Thanks

**Comment by eramrit78** [comment]
No resolve till now. face same issue in 4.3.0.99xxx xamarin forms.

**Comment by a-einstein** [comment]
Same problem, since applying the new Shell.
Instead of the icon, a blank of the same shape is displayed.

Used:
`ToolbarItems.Add(new ToolbarItem("R", "Refresh.png", async () => await Content.ViewModel.Refresh().ConfigureAwait(true), priority: 10));`

**Comment by eramrit78** [comment]
What status of this issue. we face issue in another app in 4.8 version. when can do developer with tabbed pages to use toolbar items with shell?

**Comment by a-einstein** [comment]
Update.

For me this problem suddenly disappeared when I replaced the icon.
Both were PNG files, I don't know what made the difference.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by maxkoshevoi** [comment]
@jfversluis isn't this issue a bug?
