### ISSUE TITLE
[Bug] SelectedItem on Android CollectionView has the wrong index when a HeaderView is added

### ISSUE THREAD

**Issue by gsgou** [xamarin/Xamarin.Forms#7352]
### Description

On Android only when a HeaderView is added the SelectedItem is an item with index +1
of the actually clicked item. If the HeaderView is removed works as expected.

### Steps to Reproduce

I will add a sample soon.

### Expected Behavior

On Android only when a HeaderView is added the SelectedItem is the item actually clicked.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: none as HeaderView is a new feature added recently
- IDE:
- Platform Target Frameworks: 
  - Android: 9
- Android Support Library Version: 28.0.0.1

### Reproduction Link

Will follow up

**Comment by gsgou** [comment]
Same as: https://github.com/xamarin/Xamarin.Forms/issues/7243

**Comment by jfversluis** [comment]
@gsgou thanks for the research! :)

The pre-release package with this fix should arrive pretty soon! Thanks for your patience!

**Comment by gsgou** [comment]
> @gsgou thanks for the research! :)
> 
> The pre-release package with this fix should arrive pretty soon! Thanks for your patience!

Thanks a lot for the quick Feedback.
I ll follow up as it is a major blocker to use HeaderView in a cross-platform way.
