### ISSUE TITLE
[Android] Setting ItemSpacing creates spacing for the last item in CollectionView

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7357]
### Steps to Reproduce

1. Run the repro.
2. Notice that `ItemSpacing` is set to 5.
3. Observe that the last item (item 49) has bottom spacing.

### Expected Behavior

On Android, `ItemSpacing` seems to be added to the bottom of each item, but it should truly be spacing between items. iOS doesn't have this issue.

_You should also test this with the grid layout. I haven't tested it, but we want to ensure horizontal and vertical item spacing work for all items in the last row (or column) of a grid collection._

### Actual Behavior

There is spacing below the last item.

### Basic Information

- Version with issue: 4.3.0.1106-nightly
- IDE: VS2019
- Affected Devices: Samsung S9

### Reproduction Link

[App105.zip](https://github.com/xamarin/Xamarin.Forms/files/3567262/App105.zip)

**Comment by samhouts** [comment]
closed by #7516
