### ISSUE TITLE
[SHELL] iOS - Can't increase the size of the bottom tab bar

### ISSUE THREAD

**Issue by paul-charlton** [xamarin/Xamarin.Forms#7358]
### Description
When using the Shell bottom tab bar and replacing the IShellTabBarAppearanceTracker of the ShellRenderer.CreateTabBarAppearanceTracker() I am trying to increase the size of the bottom tab bar.  Following similar advice for normal Xamarin.Forms I've tried altering the frame size but to no avail.

### Steps to Reproduce
AppShell.xalm:

```
    <TabBar Title="Testing">

        <Tab Title="View1">

            <ShellContent ContentTemplate="{DataTemplate test:TestView}" />

        </Tab>

        <Tab Title="View2">

            <ShellContent ContentTemplate="{DataTemplate test:TestView}" />

        </Tab>

    </TabBar>
```

Shell Renderer:

```
[assembly: ExportRenderer(typeof(Shell), typeof(ExtendedShellRenderer))]

namespace Renderers
{
    public class MyShellRenderer : ShellRenderer
    {
        protected override IShellTabBarAppearanceTracker CreateTabBarAppearanceTracker()
        {
            return new MyShellTabBarAppearanceTracker();
        }
    }
}
```

AppearanceTracker:

   
    public class MyShellTabBarAppearanceTracker : IShellTabBarAppearanceTracker
    {
        public virtual void SetAppearance(UITabBarController controller, ShellAppearance appearance)
        {
            ...
            var tabBar = controller.TabBar;
            tabBar.Frame = new CoreGraphics.CGRect(tabBar.Frame.X, tabBar.Frame.Y, tabBar.Frame.Width, tabBar.Frame.Height + 80);

            ...
        }

        public virtual void UpdateLayout(UITabBarController controller)
        {
        }

        #region IDisposable Support

        public void Dispose()
        {
            Dispose(true);
        }

        protected virtual void Dispose(bool disposing)
        {
        }

        #endregion IDisposable Support
    }

### Expected Behavior
The tab bar increases in size

### Actual Behavior
The tab bar stays the same size

### Basic Information

- Version with issue:
Xamarin.Forms 4.2.0.709249

- Last known good version:
n/a
- IDE:
VS2019 v16.2.3
- Platform Target Frameworks: 
  - iOS:  12.14.0.114 (c669116)

- Nuget Packages:
Xamarin.Forms 4.2.0.709249

- Affected Devices:
iOS Simulators

### Screenshots

No updated renderer:
![2019-09-03_07-28-35-AM](https://user-images.githubusercontent.com/12197609/64148922-75118780-ce1c-11e9-99ca-addf4e9d3bd9.png)

Height +=150:
![2019-09-03_07-26-24-AM](https://user-images.githubusercontent.com/12197609/64148841-48f60680-ce1c-11e9-9072-6daf0caad585.png)

**Comment by paul-charlton** [comment]
I think I've found the answer to my own query.

I've added an implementation of the ShellItemRenderer:

    public class ExtendedShellItemRenderer : ShellItemRenderer
    {
        public override void ViewWillLayoutSubviews()
        {
            base.ViewWillLayoutSubviews();
            TabBar.Frame = new CoreGraphics.CGRect(TabBar.Frame.X, TabBar.Frame.Y - 100d, TabBar.Frame.Width, 100d);
        }
    }

And created it in the ShellRenderer:

        protected override IShellItemRenderer CreateShellItemRenderer(ShellItem item)
        {
            return new ExtendedShellItemRenderer(this) { ShellItem = item };
        }

**Comment by PureWeen** [comment]
@paul-charlton since you found a solution I'm going to close this for now

We have a number of issues about customizing the TabBar which should take care of this once those get implemented
