### ISSUE TITLE
[Bug] XF Shell Binding not working

### ISSUE THREAD

**Issue by Pinox** [xamarin/Xamarin.Forms#7360]
I have a switch control in my XF Shell MenuItem but can't seem to bind the istoggled property to a field in my viewmodel.  It works perfectly in a contentpage but not in the shell.

plse see attached repo that replicates issue. =>  pressing the button will update the viewmodel , raise an event , shell and content page is binded to viewmodel.   Contentpage updates correctly , in shell flyout switch control don't update.  I see the same behaviour even using a flyoutheader.

Is this a bug or am I not suppose to bind a viewmodel to shell. Any pointers to make this work will be appreciated.

[Shell_Bug.zip](https://github.com/xamarin/Xamarin.Forms/files/3568289/Shell_Bug.zip)

**Comment by StephaneDelcroix** [comment]
this is why it doesn't work.

```xaml
IsToggled="{Binding SwitchEnabled, Mode=OneWay}"
```

 - `OneWay` is from Source to Target (VM to control)
 - `OneWayToSource` is from Target to Source
 - `TwoWay` is, well, 2 way

if you want your vm to update on toggle, you want OWTS, or 2W

**Comment by StephaneDelcroix** [comment]
I tried your project and I see what you mean

The important message in the log is 

> Binding: 'SwitchEnabled' property not found on 'Xamarin.Forms.MenuShellItem', target property: 'Xamarin.Forms.Switch.IsToggled'

I was able to work around the issue by changing the binding to 

```xaml
IsToggled="{Binding BindingContext.SwitchEnabled, Mode=OneWay}"
```

but I don't think it's right.

/cc @PureWeen

**Comment by Pinox** [comment]
thanks @StephaneDelcroix ,  i assumed it should work the same as the rest of XF.

**Comment by StephaneDelcroix** [comment]
@Pinox this is probably a bug, but use the workaround in the meantime

**Comment by PureWeen** [comment]
@Pinox @StephaneDelcroix 

The behavior is correct

The BindingContext on the template defaults to the MenuItem Control so the idea here is that when you provide a template you can just bind to the properties of the MenuItem itself for example this

```XAML
 <MenuItem Text="Switch">
        <Shell.MenuItemTemplate>
            <DataTemplate>
                <Label
                    Grid.Column="1"
                    Margin="10"
                    Text="{Binding Text}"
                    TextColor="black">
                </Label>
            </DataTemplate>
        </Shell.MenuItemTemplate>
    </MenuItem>
```

Here's the entire template we currently use to render those items

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#default-template-for-flyoutitems-and-menuitems
