### ISSUE TITLE
[Bug] Xamarin Shell iOS Navigation Bar Shadow missing

### ISSUE THREAD

**Issue by XXcharlosXX** [xamarin/Xamarin.Forms#7372]
### Description
[iOS] Xamarin Shell Navigation bar does not have a drop shadow.
It would be nice since on Droid, there is a drop shadow.
### Steps to Reproduce

1. Clone repo
2. Update Packages if necessary
3. Run project on both iOS and Android

### Expected Behavior
Nav bar should have shadow on iOS. Nav bar DOES have shadow on Android.
### Actual Behavior
Nav bar on iOS has no shadow
### Basic Information

- Version with issue:
4.2.0.709249
- Platform Target Frameworks: 
  - iOS:12.4
  - Android: 9
### Screenshots

![Simulator Screen Shot - iPhone Xʀ - 2019-09-03 at 10 38 17](https://user-images.githubusercontent.com/40214085/64195697-f9710400-ce36-11e9-8a9e-f76ec83bebd4.png)

### Reproduction Link

https://github.com/XXcharlosXX/ShellNavBarShadow

**Comment by PureWeen** [comment]
I'd recommend we add some shadow apis for the navigation bar

**Comment by PureWeen** [comment]
Closed by https://github.com/xamarin/Xamarin.Forms/pull/8408
