### ISSUE TITLE
[WPF] Implement Shell

### ISSUE THREAD

**Issue by zaratul77** [xamarin/Xamarin.Forms#7377]
### Description
Shell template not working in Platform.wpf
### Steps to Reproduce

1. Create new Xamarin project with shell template
2. Add Platform.wpf
3. run

### Expected Behavior
Display shell template
### Actual Behavior
Display empty frame
### Basic Information

- Version with issue: 4.2
- Last known good version: -
- IDE: Visual Studio 2019 Prof
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by gabrielfreire** [comment]
I'm having the same problem

**Comment by VladislavAntonyuk** [comment]
+UWP, macOS, GTK

**Comment by mohaaron** [comment]
I'm having this same problem. Has this been resolved?

**Comment by Ciders** [comment]
This is still unresolved. Any plans to fix it?

**Comment by VladislavAntonyuk** [comment]
I suppose it won’t be fix in Xamarin Forms. But may be in .NET MAUI

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
