### ISSUE TITLE
[Bug] IsRefreshing and RefreshCommand aren't working so well together

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7388]
### Description

I checked in a branch here where you can reproduce a couple issues
https://github.com/xamarin/Xamarin.Forms/commit/3c2d5ffee8d5b4f62683a721c441dfed22a9db26

### Steps to Reproduce

RefreshCommand doesn't fire if you set IsRefreshing

1. Set a break point inside the command assigned to RefreshView 
2. click *Toggle Refresh*
3. Break point is never hit

Setting IsRefreshing to False inside RefreshCommand doesn't do anything

1. Set a break point inside the command assigned to RefreshView 
2. trigger the refresh but swiping down 
3. Break point is hit
4. Notice that IsREfreshing here is set to False (it should be set to True)
5. Since it's set to false setting it to true doesn't do anything

### Reproduction Link
https://github.com/xamarin/Xamarin.Forms/compare/refreshview_fix

**Comment by jsuarezruiz** [comment]
Verified and sent a PR https://github.com/xamarin/Xamarin.Forms/pull/7398

**Comment by samhouts** [comment]
closed by #7398
