### ISSUE TITLE
[Enhancement] Increase XA Versions running UI Tests

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7390]
## Summary
- Setup CI files so the XA version is configurable. 

- Setup a pipeline on some interval that runs our master branch against the master branch of XA

- Setup general pipeline to run against the latest XA. This way our PRs and release builds will run against the latest stable XA.

- Update CI pipeline to VS 2019 so we can produce Android Q builds

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
