### ISSUE TITLE
[Bug] Editor Control in a NavigationPage's root ContentPage with Material Visual enabled, does NOT trigger TextChanged event

### ISSUE THREAD

**Issue by jayseaCODE** [xamarin/Xamarin.Forms#7391]
### Description
This applies to only `NavigationPage` initialized with a `ContentPage` that has its `Visual` property assigned to `Material`, and it contains an `Editor` control in its Content, and only happens during testing on a physical iOS device. It is working fine on a physical Android device, an Android simulator and an iOS simulator.

It probably helps to say I am working on a Apple MacBook, thus I am using Visual Studio for Mac.

### Steps to Reproduce

1. Create a new Solution -> A Blank Xamarin Forms App -> Targetting both Android and iOS, using the .NET Standard library as Shared Code.
2. Follow the steps to install [Xamarin.Forms.Visual.Material](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual) NuGet packages into the iOS and Android platforms projects.
3.  In App.xaml.cs, change 
`MainPage = new MainPage();` to
`MainPage = new NavigationPage(new MainPage());` 
4.  Next, follow the steps in [this Microsoft provided Editor Control tutorial](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/editor/?tabs=vswin&tutorial-step=2) and make changes to `MainPage.xaml` and `MainPage.xaml.cs`
5. In case you like to see the steps here, I have provided them below:
6. In `MainPage.xaml`, 
add `<Editor Placeholder="Enter multi-line text here"
                HeightRequest="200"
                TextChanged="OnEditorTextChanged"
                Completed="OnEditorCompleted" />`
 below the already provided
`<Label Text="Welcome to Xamarin.Forms!"
               HorizontalOptions="Center"
               VerticalOptions="CenterAndExpand" />`
7. In `MainPage.xaml.cs`,
add the two event handlers to your MainPage Class:
`void OnEditorTextChanged(object sender, TextChangedEventArgs e){
    string oldText = e.OldTextValue;
    string newText = e.NewTextValue;
}`
and
`void OnEditorCompleted(object sender, EventArgs e)
{
    string text = ((Editor)sender).Text;
}`
8. Put a breakpoint in both event handlers.
9. Build and debug this application to your iOS device.
10. On your iOS device, click on the Editor control, and use the soft keyboard to input text. You will realised that `OnEditorTextChanged(object sender, TextChangedEventArgs e)` does **NOT** get triggered. This works on a physical Android device, on iOS and Android simulators though.
11. When you click Done, `OnEditorCompleted(object sender, EventArgs e)` does get triggered, so this works fine.

### Expected Behavior
When debug building to a physical iOS device, `OnEditorTextChanged(object sender, TextChangedEventArgs e)`, **gets triggered** when you make text changes in the Editor control.

### Actual Behavior
When debug building to a physical iOS device, `OnEditorTextChanged(object sender, TextChangedEventArgs e)`, **does not get triggered** when you make text changes in the Editor control.

### Basic Information

- Version with issue: 
Xamarin Forms 4.2.0.709249 (Latest)
Xamarin Forms 4.1.0.555618
- Last known good version: 
- IDE: Visual Studio for Mac 
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 8.0
- Android Support Library Version: 28.0.0.1
- Nuget Packages: 
 Xamarin.Forms.Visual.Material 4.2.0.709249

- Affected Devices:

### Reproduction Link

[https://github.com/jayseaCODE/JoshNewApp3](https://github.com/jayseaCODE/JoshNewApp3)

**Comment by samhouts** [comment]
@jayseaCODE I verified that the event doesn't fire, but I was unable to find a version in which it did. Are you sure this was previously working with the Material Editor? Thanks!

**Comment by jayseaCODE** [comment]
@samhouts You might be right. It might not  have been supported with the Material Editor in the first place. I have not had any version working with Material before. How would you advise to label this defect?

**Comment by DeerSteak** [comment]
We're having problems with this as well, and also two-way binding on real iOS devices but not the simulator. For now we're manually reading the editor.Text property and updating the object prior to posting to our web services.

**Comment by Omarkth** [comment]
https://github.com/xamarin/xamarin-macios/issues/7235

**Comment by jayseaCODE** [comment]
Hey @Omarkth, it definitely is! Thanks for referencing it. Based on @PureWeen [comment ](https://github.com/xamarin/Xamarin.Forms/issues/5500#issuecomment-542839002)in #5500, there is a temporary local fix which I will attempt when I am at work. And it seems to me that fixing the underlying [xamarin/xamarin-macios#7235 bug](https://github.com/xamarin/xamarin-macios/issues/7235) will eventually fix this.

**Comment by PureWeen** [comment]
fixed by https://github.com/xamarin/Xamarin.Forms/pull/8011
