### ISSUE TITLE
[Bug] Shell: Setting Shell.BackgroundColor overrides all colors of TabBar

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#7396]
### Description
If you specify Shell.BackgroundColor (e.g. Green) without also specifying the TabBar-colors, all TabBar-colors are also green, so all you see is a green TabBar, no icons. If you also specify all Shell.TabBarXxxColors, then it works as expected. In the 'Xanimals'-sample app, this is done rightly with a style. If this isn't a bug, it should be better documented.
This is no problem if you don't specify a Shell.BackgroundColor.
Only tested on Android device.
### Steps to Reproduce

1. Take the 'Xanimals'-sample.
2. Remove the references to the styles in every ShellContent-section
3. Put BackgroundColor="Green" in '<Shell' header
4. Run and notice that the bottom TabBar is green and no icons are visible because they are also green.

### Expected Behavior
The colors should behave independently
### Actual Behavior
TabBar colors all have the same color as set by Shell.BackgroundColor, so no icons visible.
### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: ?
- IDE: Visual Studio 2019
- Android: 8.1.0

**Comment by felipebaltazar** [comment]
Hello!
Can i work in this issue?
