### ISSUE TITLE
[Bug] Forms 4.2 : CollectionView : Android : RTL

### ISSUE THREAD

**Issue by Elashi** [xamarin/Xamarin.Forms#7397]
### Description
I have a horizontal CollectionView inside a vertical CollectionView.  The horizontal CollectionView's direction was working perfectly RightToLeft in version 4.1 but when I upgraded to 4.2 , its direction now is flipped LeftToRight only in Android.

### Steps to Reproduce

1. In AppShell.xaml add property to Shell : FlowDirection="RightToLeft". I also added this property to inner CollectionView

2.  I have this block of code in MainActivity.cs as an attempt to make the default direction for the app as RTL and the language Arabic:
`            string cultureName = "ar";
            var locale = new Java.Util.Locale(cultureName);
            Java.Util.Locale.Default = locale;
            var config = new Android.Content.Res.Configuration();
            config.SetLocale(locale);
            config.SetLayoutDirection(locale);
            BaseContext.CreateConfigurationContext(config);
`
3.  In AppDelegate.cs , I have the following to force default RTL dirction:
`            var selector = new ObjCRuntime.Selector("setSemanticContentAttribute:");
            IntPtr_objc_msgSend(UIView.Appearance.Handle, selector.Handle, UISemanticContentAttribute.ForceRightToLeft);
`

### Expected Behavior
Inner CollectionView shows items displayed RightToLeft

### Actual Behavior
Inner CollectionView shows items displayed LeftToRight

### Basic Information

- Version with issue: 4.2
- Last known good version: 4.1
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  not applicable
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
Version 4.1
![ver 4 1](https://user-images.githubusercontent.com/12378171/64341246-9cb94900-cff0-11e9-85f1-0eab5ea82d8b.png)

Version 4.2
![ver 4 2](https://user-images.githubusercontent.com/12378171/64341291-b3f83680-cff0-11e9-8dc2-c5de98acd4d6.png)

If you notice, the hamburger icon also disappears.

**Comment by samhouts** [comment]
@Elashi  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Elashi** [comment]
@samhouts 
Finally I found the problem.  When I add this line : `android:supportsRtl="true"` to application node in AndroidManifest.xml , the CollectionView fails to display in the correct direction.
I attached a project anyways.
[RtlCollViewProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/3625867/RtlCollViewProblem.zip)

**Comment by hartez** [comment]
>  When I add this line : android:supportsRtl="true" to application node in AndroidManifest.xml , the CollectionView fails to display in the correct direction.

Well, that's ironic.

**Comment by PureWeen** [comment]
This might be similar to this issue here
https://github.com/xamarin/Xamarin.Forms/pull/3299/files#diff-c7572be28fab65e7fcb858929bbac2edR185

I'm guessing once you enable *android:supportsRtl* then Android is performing the RTL flip and we are doing the math to flip it again

Which is what we had to fix with Horizontal Scroll so that we just let the underlying platform do its thing without our help

**Comment by adrianknight89** [comment]
@Elashi So if you remove `android:supportsRtl="true"`, then RTL works for the inner CollectionView? If that's the case, @PureWeen might be right about the flip.

**Comment by Elashi** [comment]
@adrianknight89
Yes.  But note that this is not specific for inner or outer.  In the sample project attached, I just created one simple horizontal CollectionView with FlowDirection="RightToLeft" and this still applies.

**Comment by Elashi** [comment]
> > When I add this line : android:supportsRtl="true" to application node in AndroidManifest.xml , the CollectionView fails to display in the correct direction.
> 
> Well, that's ironic.

What is ironic is that the shell's Bottom Tab Bar and Menu Bar does not change regardless whether you changed the FlowDirection or the AndroidManifest.xml supportRtl to true.

**Comment by adrianknight89** [comment]
You said 4.1 worked, but I used 4.1 for `RtlCollViewProblem.zip` yet the issue was still there. I added your locale changes as well. Can you attach a working repro so we know which version worked the last?

**Comment by Elashi** [comment]
> You said 4.1 worked, but I used 4.1 for `RtlCollViewProblem.zip` yet the issue was still there. I added your locale changes as well. Can you attach a working repro so we know which version worked the last?

@adrianknight89 I spent on it few hours today to make 4.1 work but it did not.  This is very weird.  I cannot explain that !  But I am sure that I did not get the problem in 4.1  .  This might be some problem in VS 2019 ; in its rebuilding process.  I apologize for the inconvenience it caused.

**Comment by Elashi** [comment]
I need to keep the setting: ` android:supportsRtl="true"` to make the rest of my Android app right to left.  And I would like the CollectionView to behave as expected RightToLeft with this setting on.

I am interested in fixing this problem myself if it is not in progress yet. But I need some help to put me on the track.  I already spent four days trying to figure out how to build Xamarin.Forms project and I am still struggling.  Please help.

**Comment by Elashi** [comment]
@samhouts 
I succeeded to fix the bug.
I need some help to complete a PR.
I cloned Xamarin.Forms to my computer, branched out from master (commit 5d3d4f5456).  Then I committed my changes to the new branch.  But I did not merge it back to master.  Should I merge and then create a pull request?
I appreciate it if you can help me complete the steps.

**Comment by samhouts** [comment]
@Elashi Great news!

The best thing to do is to create a fork of Xamarin.Forms instead of a clone. Then create a branch from your fork based on the 4.2 branch. Apply your changes, and then submit your pull request from that branch. https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

Thanks!!

**Comment by samhouts** [comment]
Closed by #7809

**Comment by fakhravari** [comment]
badd bug

**Comment by darrabam** [comment]
> @samhouts
> Finally I found the problem. When I add this line : `android:supportsRtl="true"` to application node in AndroidManifest.xml , the CollectionView fails to display in the correct direction.
> I attached a project anyways.
> [RtlCollViewProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/3625867/RtlCollViewProblem.zip)

Thanks for sharing, this fixed my issue as well.
