### ISSUE TITLE
Application crashes with NullRefernceException while setting ReturnType as Next for the Entry in a DataTemplate

### ISSUE THREAD

**Issue by shivagurunathan** [xamarin/Xamarin.Forms#7399]
### Description

Application crashes with NullRefernceException while setting ReturnType as Next for the Entry in a DataTemplate

### Steps to Reproduce

1. Run the sample in Xamarin.Forms.iOS
2. Tap "Login"
3. Goto "Page2".
4. ListView has been loaded with Entry in each cell, edit the entry now tap the "Next" in the keyboard.

### Expected Behavior

Application should not be crashed.

### Actual Behavior

Application is crashed with NullReferenceException.

### Basic Information

- Version with issue: 4.1.0.709244
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

Sample link: https://www.syncfusion.com/downloads/support/directtrac/general/ze/App3shell826991867

**Comment by samhouts** [comment]
Probably caused by #2795
