### ISSUE TITLE
[Bug] XF bindings with data triggers are broken in various cases

### ISSUE THREAD

**Issue by LeadAssimilator** [xamarin/Xamarin.Forms#7402]
### Description
If you have a default property binding on a control and a data trigger that changes that same property to a constant or another binding, things don't work correctly when the triggers fire - the wrong/old value is used for the binding property value.  Similarly, having a default property constant set and trying to have more than one data trigger change that same property it to a binding property breaks as well.  

### Steps to Reproduce

Sampling of 2 failed cases from the attached application:

```xaml
<Label Text="{Binding Path=DerivedName, StringFormat='B {0} is default-1/2'}">
	<Label.Triggers>
		<DataTrigger TargetType="Label" Binding="{Binding Path=BaseNumber}" Value="0">
			<Setter Property="Text" Value="DTC ZERO is 0"/>
		</DataTrigger>
	</Label.Triggers>
</Label>

<Label Text="C ONE is default-1">
	<Label.Triggers>
		<DataTrigger TargetType="Label" Binding="{Binding Path=BaseNumber}" Value="0">
			<Setter Property="Text" Value="{Binding Path=DerivedName, StringFormat='DTB {0} is 0'}"/>
		</DataTrigger>
		<DataTrigger TargetType="Label" Binding="{Binding Path=BaseNumber}" Value="2">
			<Setter Property="Text" Value="{Binding Path=DerivedName, StringFormat='DTB {0} is 2'}"/>
		</DataTrigger>
	</Label.Triggers>
</Label>
```
```c-sharp
public string DerivedName
{
	get
	{
		switch (BaseNumber)
		{
			case 0:
				return "ZERO";
			case 1:
				return "ONE";
			case 2:
				return "TWO";
			default:
				return "NAN";
		}
	}
}

public int BaseNumber
{
	get { return baseNumber; }
	set
	{
		if (SetField(ref baseNumber, value))
			RaisePropertyChanged(nameof(DerivedName));
	}
}
```
Repeatedly change BaseNumber to 0, 1, 2 in any order/combination.

### Expected Behavior
The label text should have a matching number as a word and text in it which matches the BaseNumber that was set.

### Actual Behavior
The number as a word does not match the numeral.

### Basic Information

- Version with issue: 3.x - 4.x
- Last known good version: Never
- IDE: VS
- Platform Target Frameworks: All
  - iOS:  All
  - Android: All
  - UWP:  All 
- Android Support Library Version: All
- Nuget Packages: All
- Affected Devices: All

### Screenshots

![image](https://user-images.githubusercontent.com/7647346/64364570-23fec080-cfe1-11e9-9174-feee01618cb5.png)

### Reproduction Link

[XFBindingTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3580508/XFBindingTest.zip)

**Comment by StephaneDelcroix** [comment]
when unapplying a Setter if the DataTrigger condition becomes false, it resets the previous VALUE, not the previous BINDING, and this is what you get here.

It's probably ok to rely on a default value for when _no_ DataTrigger have been applied, but once one is applied, you should provide all of the possible values.

We're not considering this being a bug, and so I'm closing this. If you can not workaround, please open an enhancement ticket for restoring Bindings if they exists...

**Comment by LeadAssimilator** [comment]
Please reopen this issue.  There are actually mutliple issues here which interact.

Firstly, while it can be debated whether or not having trigger setter defaults be broken if not all conditions and setters are specified is a bug or not (why have that feature if it doesn't work in all cases?), it can't be debated that it is absolutely a bug of omission in documentation for not indicating the caveats.

Secondly, specifying all conditions and setters and not relying on defaults DOES NOT WORK.  While it wasn't explicitly shown in the sample app, it fails for the same reasons.  The issue is exactly what you mentioned - the setter restores the previous VALUE, and it does that if the current value matches the value it would have applied, or if it would apply a binding or dynamic resource.

This is fundamentally wrong for three reasons:
1. The value changed comparison fails if multiple setters set the same values leading to cleared/reset to default values.
2. The value changed comparison is bypassed for bindings, always causing restoration of the previous value and turning bindings into values.
3. UnApply occurs in the same order as Apply instead of reverse order, causing the wrong values to be restored.

Reasons 2 and 3 interact; consider the following:
A Label with two triggers TriggerA and TriggerB with conditions matching a binding of the same property for value A and B, both with setters setting the Text property to BindingA and BindingB respectively.  Now change the bound condition value from initial A to B, A, B, A at times t0 through t4.  There are two errors in this sequence.  

0. App launches causing TriggerA's Setter to Apply, not saving OriginalValueA.0 because it is default and setting BindingA, with TriggerB doing nothing.
1. Condition changes causing TriggerA's Setter to UnApply, clearing the value, TriggerB's Setter to Apply not saving OriginalValueB.1 because it is default and setting BindingB.
2. Condition changes causing TriggerA's setter to Apply, saving OriginalValueA.2 = ValueOf(BindingB).2, setting BindingA and TriggerB's Setter to UnApply clearing the value.
3. Condition changes causing TriggerA's Setter to UnApply, restoring OriginalValueA.2, TriggerB's Setter to Apply, saving OriginalValueB.3 = OriginalValueA.2 and setting BindingB.
4. Condition changes causing TriggerA's Setter to Apply, saving OriginalValueA.4 = OriginalValueB.3, setting BindingA and TriggerB's Setter to UnApply restoring OriginalValueB.3.

The first error is at t2 where the expected is Text = BindingA but the actual is Text = Initial or Default Value depending if Text was set initially.  And the second error is at t4 where again the expected is Text = BindingA, however it is Text = ValueOf(BindingB).2.  This is just completely wrong!

As you can see, whether or not you specify all conditions and setters only effects the behavior at t2 in the sequence.  It does not, and cannot workaround the broken logic in Setter that leads to wrong values at times based on the order in which conditions change!
