### ISSUE TITLE
[Enhancement] Shadow Effect

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#7403]
### Description
I need to control shadow offset for both platforms Android and iOS. It would be better for me to add shadows and offsets for BoxView, because I need to have only two rounded corners. But it would be ok if solution will be for Frame. 
- Platform Target Frameworks:
  - iOS
  - Android
 
### Screenshots

![image](https://user-images.githubusercontent.com/32664004/64371417-2a188f80-d029-11e9-91df-e8cd3671ee4e.png)

I need to create shadow effect like that.

**Comment by samhouts** [comment]
We'll address this as part of https://github.com/xamarin/Xamarin.Forms/issues/7744. Thanks!
