### ISSUE TITLE
Listview scroll not working in ios

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7408]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/700488/listview-scroll-not-working-in-ios.html)._

---
<p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/88903-code-samples.zip">code-samples.zip</a>After upgrading to Xamarin forms 4.1.0.673156 I start facing issue with my listview scroll.</p><p>The issue is basically that scroll is not scrolling over all the items, so I am not able to see the</p><p> the items at the bottom of the list.</p><p>  </p><p><strong>My scenario</strong>: I have a simple Tabbed page with three views inside.</p><p> One of them contains a list view that displays a list of items that I pull from a service, thru making</p><p> An asynchronous call:</p><p>  var lst = await projService.GetMyProjects();</p><p> XAML Code and C# is attached.</p><p> Any help is really welcome</p>

---
#### Visual Studio Feedback System on 8/20/2019, 01:52 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### reile18 on 8/20/2019, 07:42 AM: 

<p>A video demo with the issue can be found here: <strong><a target='_blank' href="https://drive.google.com/open?id=12qOv14AcNg8kWrG_PfcqWY21B3pcCpPq" target="_blank">Listview scroll issue</a></strong></p>

#### reile18 on 8/26/2019, 10:02 PM: 

(private comment, text removed)

---
#### reile18 solved on 8/29/2019, 10:09 PM, 0 votes: 

<p>I used default horizontal and vertical options and removed viewcell specific heighrequest, instead I used the desired height inside template</p>

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by acastr7** [comment]
I started getting reports of this happening in our app on iOS. I get the exact behavior as what is shown in the repo video.

We are defining our row hight like so:

```
<ListView.RowHeight>
    <OnIdiom
    x:TypeArguments="x:Int32"
    Phone="100"
    Tablet="120" />
</ListView.RowHeight>
```
This also doesn't seem to happen on simulators for us. We have only reproduced the issue on physical devices.

**Comment by samhouts** [comment]
@acastr7 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by karmacv** [comment]
I can confirm this issue too. I'm feeling bad doing all the workaround to keep Xamarin Forms Apps working. I upgraded from XF 3.4 to 4.3. `ViewCell` had a fixed height before the fix. Now the fixed height value is migrated to the child element `Grid` in attribute `HeightRequest`. Please fix it.

**Comment by JFMG** [comment]
@karmacv Please update XF to the latest stable version and use the CollectionView instead. This will solve your problem.

**Comment by karmacv** [comment]
@JFMG Thank you for the advice.

**Comment by bergpb** [comment]
I have the same problem, only in iOS devices and i try solution for **reile18** but not work for me.

**Comment by rameshdhungana** [comment]
@karmacv
 """Please update XF to the latest stable version and use the CollectionView instead. This will solve your problem. """
 
 But CollectionvView whole other issues on iOS. 
 1. Not all checkboxes get checked when on we implement select all feature
 2.  Icon does not appear for some items inside collectionview. 
 
The solution to these are listview but listview again has issue with scrolling while using swipeview. The never ending loop here.
