### ISSUE TITLE
[Bug] FontImageSource not vertically centered on UWP

### ISSUE THREAD

**Issue by jalbertSyncroTech** [xamarin/Xamarin.Forms#7414]
### Description

On UWP we're using a FontImageSource on an ImageButton, although this issue applies generally to any use of FontImageSource on UWP.

The UWP FontImageSourceHandler generates a square canvas to render the glyph onto, but when the glyph is vertically shorter than a square the glyph is aligned to the top of the canvas, which for ImageButton results in the glyph not being vertically centered on the button.

The handler should instead render to exactly the size of the glpyh so that the control's renderer can manage the placement and scaling, using something similar to what's described here on StackOverflow "How can I measure the Text Size in UWP Apps?" in the answer that begins with "Here is an alternative approach using Win2D" https://stackoverflow.com/questions/35969056/how-can-i-measure-the-text-size-in-uwp-apps/45937298#45937298.

### Steps to Reproduce

1. Create an ImageButton of a fixed square size and with a non-white background color, eg. HeightRequest=32, WidthRequest=32, and BackgroundColor=Blue
2. Assign it a FontIconSource with FontSize 32 and a glyph that is *not* fully square, eg. the Material Icon keyboard_arrow_down `&#xE313;` https://material.io/resources/icons/?search=arrow&icon=keyboard_arrow_down&style=baseline MaterialIcons-Regular.ttf https://github.com/google/material-design-icons/tree/master/iconfont

### Expected Behavior

The glyph should be both horizontally and vertically centered on the ImageButton.

### Actual Behavior

The glyph is horizontally centered, but is vertically aligned with the top of the ImageButton.

A line drawn through the middle of the glyph should match a line drawn through the middle of the ImageButton.

### Work Around

Adapted from the existing UAP FontImageSourceHandler:
https://github.com/xamarin/Xamarin.Forms/blob/37c22eb1cb64afc5d62b9386a50bb6090446a65a/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L16

Create a custom FontImageSourceHandler with code like the following for `LoadImageAsync()` and register it both using the assembly ExportImageSourceHandlerAttribute and by registering the assembly during `Xamarin.Forms.Forms.Init`

This uses `CanvasTextLayout` to measure and render the glyph and also uses VerticalAlignment Center like the existing handler code does for HorizontalAlignment.

```
var textFormat = new CanvasTextFormat
{
  FontFamily = fontSource.FontFamily,
  FontSize = (float)fontSource.Size,
  HorizontalAlignment = CanvasHorizontalAlignment.Center,
  VerticalAlignment = CanvasVerticalAlignment.Center,
  Options = CanvasDrawTextOptions.Default,
};

var device = CanvasDevice.GetSharedDevice();
var dpi = Math.Max(MinimumDpi, Windows.Graphics.Display.DisplayInformation.GetForCurrentView().LogicalDpi);

using (var layout = new CanvasTextLayout(device, fontSource.Glyph, textFormat, (float)fontSource.Size, (float)fontSource.Size))
{
  var canvasWidth = (float)layout.LayoutBounds.Width + 2;
  var canvasHeight = (float)layout.LayoutBounds.Height + 2;

  var canvasImageSource = new CanvasImageSource(device, canvasWidth, canvasHeight, dpi);
  using (var ds = canvasImageSource.CreateDrawingSession(Windows.UI.Colors.Transparent))
  {
	var iconColor = (fontSource.Color != Color.Default ? fontSource.Color : Color.White).ToWindowsColor();

	// offset by 1 as we added a 1 inset
	ds.DrawTextLayout(layout, 1f, 1f, iconColor);
  }

  task = Task.FromResult((Windows.UI.Xaml.Media.ImageSource)canvasImageSource);
}
```

### Basic Information

- Version with issue: 4.1.0.709244
- IDE: VS2019 v16.2.1
- Platform Target Frameworks:
  - UWP:  17763

### Screenshots

Before
![image](https://user-images.githubusercontent.com/10836879/64434057-bc527f00-d08d-11e9-899a-71f43a3c7bd4.png)

After
![image](https://user-images.githubusercontent.com/10836879/64434094-d4c29980-d08d-11e9-92dc-cc6885d60864.png)

### Reproduction Link

This should display a square blue button with a down arrow in the center.
The down arrow should be exactly in the center, but will be slightly vertically higher with X.F 4.1.0.709244.
Uncomment the ExportImageSourceHandler attribute in Renderers\FontImageSourceHandler.cs to test the Work Around.

[FontImageSourceAlignment.zip](https://github.com/xamarin/Xamarin.Forms/files/3585307/FontImageSourceAlignment.zip)

**Comment by samhouts** [comment]
@jalbertSyncroTech  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by jalbertSyncroTech** [comment]
@samhouts reproduction attached

**Comment by jalbertSyncroTech** [comment]
Upon further testing the Work Around still doesn't match the behavior on Android and will have the unintended side effect of making the FontImageSource larger when both the ImageButton and glyph are wider than they are tall.

The Android behavior is to measure the glyph's width and then to measure the font face's ascent and descent to get the total height, so that the final rendered bounds match the same bounds as a single character rendered on a line with other characters.

I think it's a simple fix of switching from `CanvasTextLayout.DrawBounds` to CanvasTextLayout.LayoutBounds' as illustrated here: https://microsoft.github.io/Win2D/html/P_Microsoft_Graphics_Canvas_Text_CanvasTextLayout_LayoutBounds.htm

I'm testing this now.

**Comment by chrisgull** [comment]
[FontImageSourceOffset.zip](https://github.com/xamarin/Xamarin.Forms/files/4855262/FontImageSourceOffset.zip)
I'm seeing this problem with current Xamarin Forms.
I have an Image element with a FontImageSource as source.
I'm using Segoe UI Symbol as embedded font, the glyph is #E179.
Android is perfectly centered, UWP is close to top left corner of the image area.
Attached is a simple reproduce project. 
I could not get embedded font to work on iOS at this time but it's working in my main project and looks good.

**Comment by mgierlasinski** [comment]
@chrisgull @samhouts Icon is still not centered horizontally, tested on Xamarin.Forms 4.8:

![image](https://user-images.githubusercontent.com/19707868/98904921-cf938280-24ba-11eb-8f05-44b7dd19c22e.png)

As a workaround I need to add small margin only on UWP.

**Comment by samhouts** [comment]
@mgierlasinski Can you please open a new issue? Thanks!!
