### ISSUE TITLE
[Bug] Crash In ShellSectionRootHeader with scrollable top tabs

### ISSUE THREAD

**Issue by larsoad** [xamarin/Xamarin.Forms#7416]
### Description

Similar (or possibly the same as #6610), the app crashes when selecting a tab from a ShellSectionRootHeader on iOS when the currently selected tab is outside the view (i.e from scrolling the tab bar)

### Steps to Reproduce

1. Make a Shell with top and bottom tabs that has enough top tabs so they don't all fit on screen at once.
2. Scroll the tab bar so the first (selected) tab is off the screen.
3. Select a different tab

### Expected Behavior

Go to the selected tab

### Actual Behavior

Crash (null reference exception). The crash happens in ShellSectionRootHeader.ItemDeselected because cell is null. Adding a chain of renderers to override ItemDeselected and checking that cell is not null before calling the base implementation does fix the problem so assumedly a null check is all that is needed.

### Basic Information

- Version with issue: 4.2

**Comment by samhouts** [comment]
@larsoad  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by larsoad** [comment]
Here is a small project created from the Shell template: [BugTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3591757/BugTest.zip)

Run it, scroll the tab bar so the selected tab is off screen, select a different tab, crash

**Comment by DandiAndy** [comment]
Once the crash is fixed, attempting to select a tab outside of the initial visible range sets the scroll position of the tab bar back to the start or the scroll-able range. i.e. The selected item is no longer visible.

To make it consistent with Android, the selection should scroll the selected tab to the center of the visible range.

**Comment by Nadeem-Hashmi** [comment]
Hi,
I am facing the same issue in IOS Top Tabs.
How to fix this?

**Comment by larsoad** [comment]
If you include this file (change extension to .cs): [FixedShellSectionRootHeader.txt](https://github.com/xamarin/Xamarin.Forms/files/3735200/FixedShellSectionRootHeader.txt) in your ios project it should at least keep your app from crashing but the tabs will still not scroll correctly.

The fix is simple (the null check on line 22) but getting it injected is a pain because you can't target the relevant renderer directly.
