### ISSUE TITLE
Issue:Unable to bind the boolean vlaue for label(IsVisible property).

### ISSUE THREAD

**Issue by Indumathi1195R** [xamarin/Xamarin.Forms#7418]
### Description
We have used the async await concept for fetching some data , which has to fetch the boolean value based on the some condition for our Calendar control with month cell template. It works fine in iOS and UWP platform. In android unable to bind the boolean value for IsVisible property of Label.

### Steps to Reproduce

1. Run the attached sample.
2. In MainViewModel we have set the FetchCalendarItemForDayAsync, FetchSomeApiDataAsync as async method, binding was not work(i.e based on the  some condition we have set value for visiblity(bool) ).

In the following code(in sample) make a method as normal, it working properly
internal async void FetchCalendarItemForDayAsync(CalendarItem ci, bool isCurrentMonth)
		{
			if (!isCurrentMonth)
			{
                return;
            }
			await FetchSomeApiDataAsync(ci);
		}

		private async Task FetchSomeApiDataAsync(CalendarItem ci)
		{
            //// added this Delay to get Data from below webservices, we got exception so commented.
            await Task.Delay(1000);
            ci.HoursWorked = TimeSpan.FromMinutes(120);
            ci.TaskHours = TimeSpan.FromMinutes(120);
            ci.HasHours = ci.HoursWorked.TotalMinutes > 0 || ci.TaskHours.TotalMinutes > 0;
        }
3. Make a method as normal and it works fine.

### Basic Information

Version with issue: 4.1.0.618606
IDE: Visual studio 2017
Platform Target Frameworks:

Android: Android 9.0

Android Support Library Version: NA
Affected Devices: Windows 10 Laptop
Android devices(Honor)

### Screenshots

NA

### Reproduction Link
[SampleCal_9c0981a7.zip](https://github.com/xamarin/Xamarin.Forms/files/3582537/SampleCal_9c0981a7.zip)

**Note: The issue occur in async method only, default it works fine.**

**Comment by StephaneDelcroix** [comment]
Bindings are applied on the thread on which the source property has been set. So set the bool value on the main (UI) thread, and you should be good (there are static InvokeOnMainThread helpers on the Device class)
