### ISSUE TITLE
How to interact DatePicker,Time picker and Number picker dialog through automation id support ?

### ISSUE THREAD

**Issue by Muniappan612** [xamarin/Xamarin.Forms#7422]
### Description
Our requirement is how to interact the DatePicker , TimePicker and NumberPicker dialog elements through automation id . We have tried in iOS platform the elements has been tapped in automation but in Android it does not work properly. 

### Steps to Reproduce
1.  Run the sample  in Android platform
2.  Try to select the Date in DatePicker and Time in TimePicker and Picker items through Automation.
3. The element do not selected .

### Expected Behavior
   The Framework DatePicker, TimePicker and Picker dialog items should be selected while run the automation . It is working fine in IOS platform.

### Actual Behavior
The Framework DatePicker, TimePicker and Picker dialog items   not selected through automation on android platform.
### Basic Information

-  Xamarin.Forms Version used: 3.0.0.482510

- Platform Target Frameworks: 
  - Android: 8.0
- Android Support Library Version: 27.0.2

### Screenshots
**DatePicker:**
We have tried to select the Date in DatePicker through Automation.
![Screen Shot 2019-09-06 at 5 19 48 PM](https://user-images.githubusercontent.com/46158936/64425839-93041400-d0ca-11e9-8813-2de1cf152731.png)

**Time Picker:**
![Screen Shot 2019-09-06 at 5 21 23 PM](https://user-images.githubusercontent.com/46158936/64425896-c8106680-d0ca-11e9-91aa-9111063ee328.png)

Picker:
![Screen Shot 2019-09-06 at 5 22 31 PM](https://user-images.githubusercontent.com/46158936/64425958-efffca00-d0ca-11e9-9b0b-e437cfa92c7a.png)

It doesn't work on Android platform , but in iOS works fine.

### Reproduction Link
[DateTimePickerAutomationId.zip](https://github.com/xamarin/Xamarin.Forms/files/3583810/DateTimePickerAutomationId.zip)

**Comment by hartez** [comment]
For Android, you'll have to invoke the `updateDate` method on the `datePicker`. Something like this:

```
var dateTime = new DateTime(1999, 1, 3);
app.WaitForElement(x => x.Class("DatePicker"));
app.Query(x => x.Class("DatePicker").Invoke("updateDate", dateTime.Year, dateTime.Month, dateTime.Day));
```

For more info, take a look at this article from @jfversluis : https://blog.verslu.is/xamarin/uitest/pick-date-time-xamarin-uitest/
