### ISSUE TITLE
[Bug] Flyout behavior "disabled" does not work

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#7424]
### Description

Setting flyout behavior to disabled does not work. The flyout still can be opened by the user.

The only difference is that flyout does not close automatically when it is set to disabled.

### Steps to Reproduce

1. Create a flyout and set its behavior to disabled.

### Expected Behavior

When flyout behavior is set to disabled user should not be able to open it.

### Actual Behavior

Flyout can be opened by the user.

### Basic Information

- Version with issue: 4.2
- Last known good version:
- IDE: Visual Studio 16.2.4

### Screenshots

![flyout_behavior_broken](https://user-images.githubusercontent.com/17653648/64447216-22192800-d0db-11e9-9563-153b6ccc566e.gif)

**Comment by VladislavAntonyuk** [comment]
+1

**Comment by PureWeen** [comment]
duplicate 

https://github.com/xamarin/Xamarin.Forms/issues/7238

@VladislavAntonyuk when the new SR for 4.2 comes out (hopefully next week) if you see the same bug with Locked can you open a new Issue?
