### ISSUE TITLE
RowDefinition's IsVisible

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7425]
Hi,

It will be great if you ad IsVisible o the RowDefinition instead of setting the Height to Zero

Thanks,
[Jassim](https://www.jassimrahma.net)

**Comment by adrianknight89** [comment]
See https://github.com/xamarin/Xamarin.Forms/issues/7427#issuecomment-529230723

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
