### ISSUE TITLE
RowDefinition's Margin

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7427]
Hi,

Please add Margin property to the RowDefinition to adjust the margin  of the RowDefinition without having to set for the inside controls.

Thanks,
[Jassim](https://www.softnames.com)

**Comment by adrianknight89** [comment]
What's wrong with setting the margin on the controls instead? Does WinUI offer this functionality? I'd say Forms XAML should closely follow WinUI and not diverge from it.

**Comment by jrahma** [comment]
Nothing wrong with WinUI but Xaamrin Forms is not a copy paste so I beieleve there is a pace for improvement

Just imagine you'll move the controls inside the Row up and down then you have to go and correct the margin for the controls

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
