### ISSUE TITLE
iOS linker not removing unused class if it inherits from UIView

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7429]
**Me** Does it make sense that any class inheriting from UIView doesn't get linked out even if it's never referenced?
    public class ALinkerTest : UIView
    {
    }

On android if I inherit from the native ViewGroup or View it'll get linked out

**iOS Team** yes, it has to do with NSObject (not all) subclasses

**Result** Linking out the UIWebView renderer is never going to happen

**Comment by whitneyschmidt** [comment]
Renderers are a Xamarin Forms concept so their linking behavior probably needs to be looked at by the Forms team first?

**Comment by chamons** [comment]
@samhouts ^?

**Comment by samhouts** [comment]
@whitneyschmidt @chamons Hey! Yeah, we _are_ the Forms team....so we were asking for some help investigating this issue. :)

**Comment by chamons** [comment]
I missed the fact that the reporter was Shawn (GH name did not match expectations).

I talked to him over slack, and he has a few things to check and then will slap it back to us. :)
