### ISSUE TITLE
[Bug/Question] Shell navigation 

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#7430]
1. Create ShellItem with ShellSections
```
<ShellItem Title="Home">
    <ShellSection Title="page1">
      <ShellContent ContentTemplate="{DataTemplate local:Page1}" />
    </ShellSection>
    <ShellSection Title="page2">
      <ShellContent ContentTemplate="{DataTemplate local:Page2}" />
    </ShellSection>
  </ShellItem>
```
2. Create Page3 and Register it in the root
```
Routing.RegisterRoute("page3", typeof(Page3));
```

3. Navigate to this page 
```
MyShellInstance.GoToAsync("page3");
or 
NavigationRoot.Navigation.PushAsync(new Page3());
```

Actual behavior:
tabs displayed in the bottom

Expected behavior:
Tabs are not displayed. It should look like ModalPage, but with the back button.

if the current behavior is expected, please let me know how to achieve my expected result?

**P.S. I have found a solution (set Shell.TabBarIsVisible="False" on Page3), but probably there are some other recommended approaches)**

**Comment by alanag13** [comment]
Use `PushModalAsync`.

**Comment by VladislavAntonyuk** [comment]
@alanag13 you mean add button with PopModalAsync on click?

**Comment by alanag13** [comment]
Yes, assuming you just want the modal to dismiss. You could of course have anything you want happen when it's tapped.

**Comment by PureWeen** [comment]
@VladislavAntonyuk 

What @alanag13 is suggesting or what you figured out is what I would suggest
