### ISSUE TITLE
[Bug] Debugger error when expanding a property view and problem when debugging async method

### ISSUE THREAD

**Issue by silviubogan** [xamarin/Xamarin.Forms#7432]
### Description

I am sorry I did not break this issue into pieces, but I am not sure how the error messages are related to each other. I hope this is not a security vulnerability

### Steps to Reproduce

1. Clone the repo at the end of this issue
2. Put the told breakpoint
3. Try to step in two times or step over that line (wait 5 seconds after launching the app on the device, then it will get you to that line)
4. The program reenters the run mode

5. Repeat the steps 1-3 and test this: everything I enter in the Immediate Window, including "1+1", results in reentering the run mode sometimes without any message or visible error. The error in the first screenshot (the big one) appeared when I was trying to expand a property view in the debugger with the Parallel Stacks window open. If I close the Parallel Stacks window:

    1. The Immediate Window works well in the same situation (the same LOC and moment in the program's progress) for `1+1` (shows `0x0002`).
    2. But I cannot step in or over the line `BackView.IsVisible = true;`, it behaves just like I am pressing the Continue button.

### Expected Behavior

To be able to step over that LOC. To not enter automatically in the run mode. The error message to not be necessary (not shown, and not needed).

### Actual Behavior

The error in the screenshot is shown.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 Community with latest updates
- Platform Target Frameworks: 
  - iOS:  
  - Android: minimum 5.0, target 9.0
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
  - Xamarin.Forms v4.1.0.709244
  - Xamarin.Essentials v1.2.0
- Affected Devices:
  - at least Samsung Galaxy S9 (SM-G960F)

### Screenshots

![2019-09-07_11-50-36 - Copie](https://user-images.githubusercontent.com/198924/64472592-74088f00-d169-11e9-86c5-0a2d30f1a985.png)

Another screenshot

![devenv_2019-09-07_12-43-07](https://user-images.githubusercontent.com/198924/64474992-200ba380-d185-11e9-873c-5442fa11228a.png)

Immediately after that, this:

![2 devenv_2019-09-07_12-43-43](https://user-images.githubusercontent.com/198924/64474999-3285dd00-d185-11e9-8465-cafc8bcec12d.png)

Then, after pressing Continue (pressing again shows this message again):

![3 devenv_2019-09-07_12-44-21](https://user-images.githubusercontent.com/198924/64475006-47fb0700-d185-11e9-9c24-effb881119f6.png)

After a period of time, in which I deleted some files and code to create a test case, I get this error when trying to step over that line:

![4 devenv_2019-09-07_13-14-05](https://user-images.githubusercontent.com/198924/64475008-52b59c00-d185-11e9-8af9-07c4392a2081.png)

### Reproduction Link

[This repo](https://github.com/silviubogan/xamarin-forms-debugger-bug-1) reproduces just a part of the issues presented above: when placing a breakpoint [on the line 133](https://github.com/silviubogan/xamarin-forms-debugger-bug-1/blob/f576eb5033bce897938e1536e768958434233085/MyTestApp/MyTestApp/FlipView.cs#L133) in the `FlipFromFrontToBack` async method inside `FlipView.cs`, when the breakpoint is first hit, and I press Step In or Step Over, the program enters the run mode again, just like if I press pressing Continue. Sometimes an error window appears similar to the last one inserted above.

I hope I helped somehow.

Thank you.

**Comment by samhouts** [comment]
@silviubogan Please report this issue directly from Visual Studio using Help >> Send Feedback. Thank you!
