### ISSUE TITLE
[Bug] Focused color of the TextBox is not working in UWP

### ISSUE THREAD

**Issue by LakshmiRadhaKrishnan** [xamarin/Xamarin.Forms#7434]
### Description

Focused color of the TextBox is not working in UWP.

### Steps to Reproduce

1. Create a TextBox sample in native UWP platform.
2. Hook the GotFocus and LostFocus event in the text box.
3. Set foreground color to the text box in both the event (GotFocus and LostFocus).
4. Check the Foreground color not changed while focusing, but foreground color changed while lost focus.

### Expected Behavior

Foreground color will change while focused and unfocused state.

### Actual Behavior

Foreground color not changed while focusing the text box.

### Basic Information

- Platform Target Frameworks: 
  UWP (Native).

**Comment by hartez** [comment]
@LakshmiRadhaKrishnan Are you seeing this in a Xamarin.Forms project running on UWP, or are you seeing this in a totally native UWP project?

**Comment by samhouts** [comment]
@LakshmiRadhaKrishnan  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
