### ISSUE TITLE
[Bug] [Android] NullReferenceException in Shell + Split screen

### ISSUE THREAD

**Issue by caramelopardalis** [xamarin/Xamarin.Forms#7435]
# Steps to Reproduce

1. Create a new shell project
2. Build and deploy the app
3. Show the recents screen
4. Long press the app icon
5. Tap Split screen

### Expected Behavior

The app into a splitted screen.

### Actual Behavior

NullReferenceException has occurred.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.709249
- IDE: Visual Studio 2019 Preview 16.3.0 Preview 3.0
- Platform Target Frameworks:
  - Android: 10
- Affected Devices: Android 10 Emulator

### Screenshots

https://www.youtube.com/watch?v=R8ASDZQHckY

### Log

[error.log](https://github.com/xamarin/Xamarin.Forms/files/3587479/error.log)

### Reproduction Link

[ShellSplitScreen.zip](https://github.com/xamarin/Xamarin.Forms/files/3587471/ShellSplitScreen.zip)

**Comment by kvpt** [comment]
It's a duplicate of the issue #6640.
Fixed by PR #6715.

**Comment by jfversluis** [comment]
Duplicate of #6640

**Comment by jfversluis** [comment]
Thanks for reporting the issue! There was already one open for it, please keep an eye on that one to track the status.
