### ISSUE TITLE
[Enhancement] CarouselView needs an autoplay/slideshow mode

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#7439]
## Summary

I'm replacing existing carousels in my apps and nearly all of them have a slideshow mode where they auto-advance after a duration. This is currently missing from the `CarouselView` implementation.

* User interaction should be able to pause or stop autoplay
* Items should continue seamlessly from the end of the carousel to the beginning in an infinite loop (ie not appear to rewind) unless we have different modes for how to treat this (yoyo, from beginning, infinite, random)

## API Changes

ItemDuration - int for ms to see one item
AutoPlay - bool to enable and disable it
Repeat - int to indicate number of times to play. 0 for infinite (default)
TransitionSpeed - int for ms indicating how quickly the transition should happen
TransitionEasing - Easing

```
<CarouselView x:Name="carouselView"
                          ItemDuration="4000"
                          TransitionSpeed="1000"
                          TransitionEasing="BounceIn"
                          ItemsSource="{Binding CarouselImages}">
                <CarouselView.ItemTemplate>
                    <DataTemplate>
                        <Image Aspect="AspectFill" />
                    </DataTemplate>
                </CarouselView.ItemTemplate>
            </CarouselView>
```

## Intended Use Case

Easily set my carousel to behave like a slideshow.

**Comment by firtreeroo** [comment]
It would also be great if the slideshow could be set to run in both "forward" and "reverse" directions.  Further, it would be very useful if the slideshow can be temporarily stopped and started by using a click-sequence.  And, yes, another request, please make the slideshow items be respond to pinch and zoom finger interactions, which will enable the carousel to be used for a graphical slideshow that is interactive with the user.  Thanks for considering these feature requests.

**Comment by samtun** [comment]
This would be super nice to have. We implemented auto-scroll using the Position binding ourselves but it feels not that robust. Also the app crashes when reloading the CarouselView when doing this so an official solution for this would be fantastic.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
