### ISSUE TITLE
[Bug] The CarouselView does not snap by default

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/Xamarin.Forms#7443]
### Description

By default, Carousel does not snap. 

### Steps to Reproduce

Create a **CarouselView** as follows:

```
<CarouselView 
     Position="0"
     CurrentItem="{Binding CurrentItem, Mode=TwoWay}"
     ItemsSource="{Binding Items}"
     ItemTemplate="{StaticResource ItemTemplate}">
</CarouselView>
```

By default, Carousel does not span. The problem is that, the default value of the **SnapPointsType** property is None. This is correct in the CollectionView but not in the CarouselView.

### Expected Behavior

By default, we have a Carousel that uses a ItemsLayout with horizontal orientation and with snap.

![expected-carousel-snap](https://user-images.githubusercontent.com/6755973/64519410-59aeec80-d2f4-11e9-9ba8-130c863fdc9b.gif)

### Actual Behavior

By default, Carousel does not snap. 

![carousel-snap-issue](https://user-images.githubusercontent.com/6755973/64519412-5b78b000-d2f4-11e9-8973-1c220d41a26c.gif)

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.778476-pre1
- Platform Target Frameworks: 
  - iOS
  - Android

**Comment by samhouts** [comment]
closed by  #7444
