### ISSUE TITLE
[Enhancement] Xamarin.Forms.Platform.WPF.ImageExtensions to public

### ISSUE THREAD

**Issue by neolithos** [xamarin/Xamarin.Forms#7445]
## Summary
It would be nice for wpf-implementations, that the helper `ToWindowsImageSourceAsync` is public.

## API Changes

```C#
	public static class ImageExtensions
	{
		public static Stretch ToStretch(this Aspect aspect) {}

		internal static WImageSource ToWindowsImageSource(this ImageSource source) {}

		public static async Task<WImageSource> ToWindowsImageSourceAsync(this ImageSource source, CancellationToken cancellationToken = default(CancellationToken)) {}
	}
```

ToWindowsImageSource should be deleted, because the use of this function can lead in dead locks.

## Intended Use Case
For custom control renders.

## Additon

Is a pull request welcome?

**Comment by samhouts** [comment]
@neolithos Yes! Thanks!!
