### ISSUE TITLE
[Question] How to disable rendering of Entry in full screen mode when the device is rotated?

### ISSUE THREAD

**Issue by Basti82b** [xamarin/Xamarin.Forms#7446]
When I focus an Entry in horizontal device oriantation it is shown in fullscreen with a "Done" button besides.

Is there a way to disable this feature?

### Basic Information

- Version with issue: 4.2.0.709249
- Platform Target Frameworks: 
  - Android: 9.0

### Screenshots

![Screenshot_1568028631](https://user-images.githubusercontent.com/49757194/64527408-22e1d200-d306-11e9-8a09-7e8fe2d22c49.png)

**Comment by hartez** [comment]
You can specify the IME options for your entry to prevent it from going full screen. Something like: 
`entry.On<Android>().SetImeOptions(ImeFlags.NoFullscreen);` 
in code. Or in XAML add:

`xmlns:androidSpecific="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"` 

in your `ContentPage` tag and then set the value in your Entry:
`<Entry androidSpecific:Entry.ImeOptions="NoFullscreen" />`

However, it seems that there's a bug with IME options right now; I've filed an issue (#7623). Hopefully we can get it resolved soon.

**Comment by Basti82b** [comment]
@hartez Thank you so much! I have never heard of the "IME options". Hopefully the bug will be fixed soon.
