### ISSUE TITLE
[Enhancement] BackgroundView for CollectionView

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7447]
## Summary
In some cases, we might be interested in adding a background view to `CollectionView`. Accordiing to iOS documentation, a `BackgroundView` is:

> The view (if any) in this property is positioned underneath all of the other content and sized automatically to fill the entire bounds of the collection view. The background view does not scroll with the collection view’s other content. The collection view maintains a strong reference to the background view object.

> This property is nil by default, which displays the background color of the collection view.

https://developer.apple.com/documentation/uikit/uicollectionview/1618074-backgroundview

## API Changes

BackgroundView -> object
BackgroundViewTemplate -> DataTemplate

By default, this property is null. When it is set to a value, then the `BackgroundColor` should not be shown (unless perhaps we support transparency of the `BackgroundView`).

## Intended Use Case
This is useful when we create a chat application like WhatsApp. :) There is another intended use case which is discussed at https://github.com/xamarin/Xamarin.Forms/issues/3172#issuecomment-529266125 and below.

**Comment by LeoJHarris** [comment]
Upvoting 👍

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
