### ISSUE TITLE
[Bug] unwanted convertion of DateTime in BindableProperty 

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7449]
### Description

I receive an endless loop because the DateTime gets converted between UTC and local time (Vienna UTC +2) back and forth.

23.09.2018 22:00 -> 23.09.2018 00:00

### Steps to Reproduce

`
public static readonly BindableProperty DateProperty =
	BindableProperty.Create("Date", typeof(DateTime), typeof(ReportDatePicker), default(DateTime),    
	propertyChanged: (bindable, oldValue, newValue) =>
	{
		((ReportDatePicker)bindable).Date = (DateTime)newValue;
	});

public DateTime Date
{
	get => (DateTime)GetValue(DateProperty);
	set => SetValue(DateProperty, value);
}

`

### Basic Information

- Version with issue: XF 4.2.0.709249
- Last known good version: XF 4.1.0.709244

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by issaaccbb** [comment]
We also have noticed this issue on our date and time pickers. The `oldValue` and `newValue` differ by our local timezone, which is causes the `propertyChanged` event to be fired continually.

@mknotzer did you ever find a solution?

**Comment by mknotzer** [comment]
Fortunately we only need the date part.

`bindable.Date = new DateTime(newValue.Year, newValue.Month, newValue.Day);`

@issaaccbb only a work around, no real solution

**Comment by issaaccbb** [comment]
@mknotzer We ended up with a similar solution `control.Date = newValue.Date` + some checks for empty. Hope they get this fixed soon, rather weird issue to run into after an upgrade

**Comment by samhouts** [comment]
@mknotzer @issaaccbb Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mknotzer** [comment]
@issaaccbb For some reasons I can't reproduce the bug any more, how about you?

**Comment by samhouts** [comment]
@issaaccbb Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@mknotzer @issaaccbb  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
