### ISSUE TITLE
XAML Binding is not behaving right after Xamarin.Forms 4.2 release

### ISSUE THREAD

**Issue by sakhnini** [xamarin/Xamarin.Forms#7450]
### Description
Even though the BindingContext is set and the OnPropertyChanged is called, the UI is updated only after the second change, the updated change is relevant to the previous, for example, if I bind a label text to X and change X value to A, nothing happens, when I change it again to B the displayed value changes to A, and when changing to C the display value will be B etc... 

This was solved when we downgraded to Xamarin.Forms 4.1

### Expected Behavior
When changing value of binded property, the binded field should be updated accordingly.

### Actual Behavior
The binded field is updated to the previous binded value.

### Basic Information

- Version with issue: 4.2
- Last known good version: 4.1
- IDE: Visual Studio 2017
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 9.0 
- Android Support Library Version: Xamarin.Android.Support.v4 28.0.0.1
- Nuget Packages: 
- Affected Devices: All

**Comment by samhouts** [comment]
@sakhnini  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
It sounds like this is the same as #7286.

**Comment by samhouts** [comment]
@sakhnini  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
