### ISSUE TITLE
[Enhancement] CollectionView - items sized to fit

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#7451]
## Summary
I'd like an option for items to be sized to expand to fill the area when the items would be too small.

## API Changes

Add property `bool FillArea`. When true, the control will split the view among the items evenly and fill the entire area. If the size of the items controlled by ItemSizingStrategy would be less than HeightRequest/WidthRequest of the item, the control would revert to normal layout behavior for that dimension.

## Intended Use Case
Example:
Imagine an application that contains one or more graphs, and a user can decide how many they want to show. The repeated pattern and variable number is best represented by a CollectionView-type control with an ItemsSource and DataTemplate. However, the user may only have one or two graphs, which are best displayed by filling the screen. With more graphs, they can shrink until a minimum size is reached, after which scrolling behavior can be used.

As of now, there is no easy way to achieve this that I am aware of.

Here's a mockup of what I mean:
![Mockup](https://user-images.githubusercontent.com/1438610/64576251-c0102b00-d345-11e9-80c1-a7f6b52b6821.png)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
