### ISSUE TITLE
[Bug] FindByName() not working in derived partial class

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7452]
`
public partial class MyTemplateClass : ContentView
{
var label = FindByName("xLabelInMyTemplateClass"); // ok
}

public partial class MyClass : MyTemplateClass
{
var label = FindByName("xLabelInMyClass"); // null
}
`

- Version with issue: 4.2.0
- Last known good version: 4.1.0

**Comment by samhouts** [comment]
@mknotzer  It sounds like this is the same as #7286. Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by StephaneDelcroix** [comment]
As @samhouts mentioned, this is a dupe and has been fixed. the fix will be part of the next 4.2.0-sr release.

That being said, you should use ControlTemplate instead of templating by base class
