### ISSUE TITLE
[Bug] CollectionView Header not displayed without Footer

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7453]
without a footer the header doesn't get displayed

- Version with issue: 4.2.0

**Comment by samhouts** [comment]
@mknotzer Please use the full template when reporting issues. Is this for Android? iOS? Both?

 Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by chrisstaley** [comment]
For me, the bug is only occurring on iOS. Android is working as expected. On iOS, the header does not show unless I also specify a footer.

**Comment by samhouts** [comment]
@chrisstaley Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by chrisstaley** [comment]
@samhouts Repro project, as requested.
[Issue7453.zip](https://github.com/xamarin/Xamarin.Forms/files/3602320/Issue7453.zip)

**Comment by adrianknight89** [comment]
@samhouts Can you add "done", "inreview", and "inprogress" labels to the issues so we can filter them out in the UI search? If there is an automated way to do this, it'd be even easier.

**Comment by samhouts** [comment]
closed by #7499

**Comment by samhouts** [comment]
@adrianknight89 There are now "in-progress" labels on issues with PRs. I'll see if there's a good way to add the in-review and done labels without being too spammy. :)

**Comment by adrianknight89** [comment]
@samhouts Awesome. :)
