### ISSUE TITLE
[Bug] CollectionView header not displayed properly (grid)

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7454]
this grid doesn't get displayed properly as header

`
	    <Grid Padding="5" WidthRequest="750" BackgroundColor="#CCCCCC">
	        <Grid.ColumnDefinitions>
	            <ColumnDefinition Width="150"/>
	            <ColumnDefinition Width="*"/>
	            <ColumnDefinition Width="125"/>
	            <ColumnDefinition Width="150"/>
	            <ColumnDefinition Width="150"/>
	        </Grid.ColumnDefinitions>

	        <Label Grid.Column="0" Style="{StaticResource LabelMediumStyle}" Text="Erstellung"/>
	        <Label Grid.Column="1" Style="{StaticResource LabelMediumStyle}" Text="Typ"/>
	        <Label Grid.Column="2" Style="{StaticResource LabelMediumStyle}" Text="Kategorie"/>
	        <Label Grid.Column="3" Style="{StaticResource LabelMediumStyle}" Text="Abgleich"/>
	        <Label Grid.Column="4" Style="{StaticResource LabelMediumStyle}" Text="Redo"/>
	    </Grid>
`

- Version with issue: 4.2.0

### Screenshots

![image](https://user-images.githubusercontent.com/13821046/64548299-a7e0e180-d32e-11e9-89e3-58a144efaee6.png)

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@mknotzer  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by mknotzer** [comment]
working now with XF 4.4.0
