### ISSUE TITLE
[Bug] CollectionView EmptyView not displayed correctly

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7455]
label should be centered
`			
<CollectionView.EmptyView><Label Text="Keine Daten vorhanden" Style="{StaticResource LabelMediumStyle}" HorizontalOptions="Center" HorizontalTextAlignment="Center" BackgroundColor="Lime"/>
</CollectionView.EmptyView>
`
- Version with issue: 4.2.0
![image](https://user-images.githubusercontent.com/13821046/64549208-8b45a900-d330-11e9-886d-fb4b8ca2f377.png)

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@mknotzer  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by mknotzer** [comment]
Working with XF 4.4.0
