### ISSUE TITLE
[Bug] Collection View EmptyView displayed behind instead of below Header

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#7457]
EmptyView is hidden behind Header/Footer

# Basic Information

`			<CollectionView.EmptyView>
				<Label Text="Keine Daten vorhanden" Style="{StaticResource LabelMediumStyle}" 
					   HorizontalOptions="Center" HorizontalTextAlignment="Center" 
					   BackgroundColor="Lime"/>
			</CollectionView.EmptyView>
`

- Version with issue: 4.2.0

![image](https://user-images.githubusercontent.com/13821046/64549470-0b6c0e80-d331-11e9-8357-96d45d24fe26.png)

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by adrianknight89** [comment]
@samhouts I noticed something similar. Go to CollectionView Galleries -> Observable Collection Galleries -> Add / Remove Items (Grid). The header is drawn on top of the first row of items.

This was tested on the 4.3.0 branch as of commit 3603550.

**Comment by EBusch** [comment]
I have seen a similar issue where an EmptyView and Footer will conflict. Attaching a simple reproduction.
[BreakMe.zip](https://github.com/xamarin/Xamarin.Forms/files/3781568/BreakMe.zip)

**Comment by simonemarra** [comment]
I've also noticed such bug on my application (XF 4.3.0). 

I expected the EmptyView to be placed instead of any ItemTemplate view, but the empty view is shown on top of the page, on the same position of HeaderTemplate.

If this CollectionView behaviour is expected, I suppose I have to duplicate my HeaderTemplate inside the EmptyView and hide the header template when ItemsSource is null (or empty), but I think it should not be the way it is supposed to work. A simple property for the header and footer templates to hide/show if ItemsSource is null or empty could be very helpful

**Comment by samhouts** [comment]
closed by #8415

**Comment by mknotzer** [comment]
The bug still exists in XF 4.4.0. Very easy to reproduce. Please reopen this issue.

**Comment by jonx** [comment]
Indeed, this is still not working in 4.4.

`            <CollectionView
                Footer="{Binding .}"
                ItemsSource="{Binding Invitations}"
                SelectionChangedCommand="{Binding OpenInvitationDetails}"
                SelectionChangedCommandParameter="{Binding SelectedItem, Source={x:Reference InvitationsCollectionView}}"
                SelectionMode="Single"
                VerticalOptions="Start">
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <common:LeafCollectionViewCell />
                    </DataTemplate>
                </CollectionView.ItemTemplate>
                <CollectionView.EmptyView>
                    <StackLayout
                        BackgroundColor="{StaticResource BasePageBackgroundColor}"
                        Spacing="0"
                        VerticalOptions="Center">
                        <Image
                            x:Name="CollectionViewEmpty"
                            Margin="0,44,0,0"
                            HeightRequest="104"
                            Source="ic_invitations_empty"
                            WidthRequest="104" />
                    </StackLayout>
                </CollectionView.EmptyView>
                <CollectionView.FooterTemplate>
                    <DataTemplate>
                        <StackLayout BackgroundColor="Transparent" VerticalOptions="Start">
                            <Label
                                Margin="0,24,0,0"
                                HorizontalOptions="Center"
                                HorizontalTextAlignment="Center"
                                Style="{StaticResource CopyLabel}"
                                Text="{Binding Information}"
                                WidthRequest="300" />
                            <Label
                                Margin="0,24,0,32"
                                HorizontalOptions="Center"
                                HorizontalTextAlignment="Center"
                                Style="{StaticResource CopyLabel}"
                                Text="{Binding InformationUsedInvitations}"
                                WidthRequest="300" />
                        </StackLayout>
                    </DataTemplate>
                </CollectionView.FooterTemplate>
            </CollectionView>`

On iOS, the footer is on top of the empty view and on Android the empty view is just ignored. In my case, the empty view should show an image.

![IMG_0071](https://user-images.githubusercontent.com/596119/72070062-eee4e080-32e8-11ea-8da5-fbaf9a642e07.PNG)
![Screenshot_20200109-133624](https://user-images.githubusercontent.com/596119/72070063-ef7d7700-32e8-11ea-8467-1f1e1b2f1f01.png)
