### ISSUE TITLE
[Bug] hamburger menu appear on the top navigation bar when FlyoutBehavior="Disabled"

### ISSUE THREAD

**Issue by CherryBu** [xamarin/Xamarin.Forms#7463]
Add this: FlyoutBehavior="Disabled" but, it's doesn't work, still hamburger menu appear on the top navigation bar at Xamarin.Forms 4.2

<TabBar >
        <Tab Title="Home" Icon="home.png" >
            <ShellContent ContentTemplate="{DataTemplate views:Home}"/>
        </Tab>

        <Tab Title="CashBack" Icon="cashback.png">
            <ShellContent ContentTemplate="{DataTemplate views:Cashback}"/>
        </Tab>

        <Tab Title="My Point" Icon="mypoint.png">
            <ShellContent Title="My Point"  ContentTemplate="{DataTemplate views:MyPoint}"/>
            <ShellContent Title="History" ContentTemplate="{DataTemplate point:PointHistory}"/>
        </Tab>

        <Tab Title="Me" Icon="me.png">
            <ShellContent ContentTemplate="{DataTemplate views:Me}"/>
        </Tab>
    </TabBar>

**Comment by samhouts** [comment]
@CherryBu  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@CherryBu  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by CherryBu** [comment]
> @CherryBu  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!


You can see the detailed info from this thread:https://stackoverflow.com/questions/57831703/how-to-show-title-name-on-top-navigation-bar-instead-of-hamburger-icon-in-xamari, now I try to reproduce this issue, it seems that it has been fixed.

**Comment by jfversluis** [comment]
Great to hear that it's fixed! Thanks for letting us know!
