### ISSUE TITLE
[Bug] The CarouselView does not render some elements

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/Xamarin.Forms#7466]
### Description

In **iOS** (I can not reproduce the same problem in Android), swipe from one element to another and returning to previously seen elements, sometimes you get an element without rendering.

<img width="409" alt="Captura de pantalla 2019-09-09 a las 17 38 55" src="https://user-images.githubusercontent.com/6755973/64613713-1da08800-d3d7-11e9-9d2d-e389e388cca8.png">

### Steps to Reproduce

1. Access this repository: https://github.com/jsuarezruiz/TravellingApp
2. Launch the sample on iOS.
3. Swipe between elements.

### Expected Behavior
All elements are always rendered.

### Actual Behavior
Sometimes I get elements without rendering (see screenshot).

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.778476-pre1

**Comment by hartez** [comment]
@jsuarezruiz I'm having trouble reproducing this - do you happen to know what version of iOS you saw this on?

**Comment by hartez** [comment]
Ah, never mind. I can reproduce it on iOS 11, but not 12.

**Comment by hartez** [comment]
Okay, when I update to a version which includes #7285 I can no longer reproduce this issue. I'm about 95% certain that PR fixes this issue. (It'd be 100, but this issue is not consistently reproducible.)

**Comment by jsuarezruiz** [comment]
I was testing using iOS 12. Will test again with https://github.com/xamarin/Xamarin.Forms/pull/7285.

**Comment by jsuarezruiz** [comment]
Hey @hartez seems that #7285 fixes the issue.
