### ISSUE TITLE
[Bug] The CarouselView does not allow scrolling until the last item

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/Xamarin.Forms#7467]
### Description

The CarouselView does not allow scrolling until the last item.
![scroll-last](https://user-images.githubusercontent.com/6755973/64614095-031ade80-d3d8-11e9-9057-1722b2489019.gif)

### Steps to Reproduce

1. Access this repository: https://github.com/jsuarezruiz/TravellingApp
2. Launch the sample on iOS.
3. Try to scroll until the last item.

### Expected Behavior
As happens in iOS, you can scroll to the last item.
![carousel-scroll-last-ios](https://user-images.githubusercontent.com/6755973/64614399-b71c6980-d3d8-11e9-97ec-ee3493394b7f.gif)

### Actual Behavior
The CarouselView does not allow scrolling until the last item.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.778476-pre1

**Comment by Danteou** [comment]
The same thing happens to me since I updated xamarin.forms to version 4.2.0778463

**Comment by rmarinho** [comment]
This should be fixed on the latest 4.4 stable
