### ISSUE TITLE
[Enhancement] Add "MinuteInterval" property for Android Renderer !

### ISSUE THREAD

**Issue by jm-parent** [xamarin/Xamarin.Forms#7479]
## Summary
Like as IOS , android needs an minute interval option.

## API Changes

Long time ago , we "search" in viewgroup to find NumberPicker , then we could force DisplayedValues.

  numberPicker.SetDisplayedValues(new String[] { "00", "15", "30", "45" });

Now , i only "find" RadialTimePicker , but nothing exposed in XF :(

## Intended Use Case

Expose TimePickerDialog.MinuteInterval ;)

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
