### ISSUE TITLE
[Bug] OnAppearing is not triggered in a content page part of shell hierarchy 

### ISSUE THREAD

**Issue by JanabiSoft** [xamarin/Xamarin.Forms#7487]
### Description
OnAppearing is not triggered in a content page part of Shell hierarchy when navigating back from another page using PopModalAsync(). 
tried in android only.
### Steps to Reproduce

1. in any page of Shell navigate to non registered page by PushModalAsync().
2. navigate back using PopModalAsync()
3. the OnAppearing is not firing

### Expected Behavior
OnAppearing() method should excute
### Actual Behavior
OnAppearing is not excuted.
### Basic Information

- Version with issue: 4.2
- Last known good version: 
- IDE: VS19, VS17
- Platform Target Frameworks: 
  
  - Android: 8.1 
  
- Android Support Library Version:

**Comment by samhouts** [comment]
@JanabiSoft  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
