### ISSUE TITLE
[Bug] [WPF]Custom renderer will not be called when fontsize is set in label or button.

### ISSUE THREAD

**Issue by christapps** [xamarin/Xamarin.Forms#7491]
`<Label FontSize="22"/>`

public class MyLabelRenderer : Xamarin.Forms.Platform.WPF.LabelRenderer
    {
        protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null)
            {
                if (Control != null)
                {
                    if (Control.FontFamily.ToString().Equals("Microsoft YaHei UI"))
                    {
                        Control.FontFamily = new System.Windows.Media.FontFamily("微软雅黑");
                    }
                }
            }
        }
    }
### Actual Behavior
MyLabelRenderer will never be called when fontsize is fixed.
### Basic Information

- Version with issue:4.2.0.778463

**Comment by mohachouch** [comment]
Hi @xxfaith,  I don't understand the problem you encountered. Font size is set in the label object at initialization so it does not call OnElementPropertyChanged. What is the default behavior on all platforms. Can you tell me more ?

**Comment by xxfaith** [comment]
@mohachouch I only use this renender for wpf because the default font family Microsoft YaHei UI is not exist on my computer.For test, you can change the code as follows.
`protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null)
            {
                if (Control != null)
                {
                    Control.Text = "text changed";
                }
            }
        }`
And you will see the text is not change where the font size is set to large.

**Comment by xxfaith** [comment]
https://github.com/xxfaith/test/blob/master/test.png

**Comment by xxfaith** [comment]
Font size is set on xaml and OnElementPropertyChanged is never called.The FontAttributes Property alse cause this problem.

**Comment by mohachouch** [comment]
I can not reproduce the bug. I have the right behavior on my computer.

![image](https://user-images.githubusercontent.com/25939826/65032152-e7b55380-d942-11e9-9dba-7a99f507187c.png)
