### ISSUE TITLE
[Bug] [GTK] Unable to hide the navigation bar completely

### ISSUE THREAD

**Issue by Nekliukov** [xamarin/Xamarin.Forms#7492]
Hiding of the navigation bar causes appearing of some empty space under the page. It looks like this navbar becomes transparent and docks at the bottom of the page. There are no problems on the other platforms, reproduces only in GTK

### Steps to Reproduce

1. Add navigation page
2. Hide navigation bar using `NavigationPage.HasNavigationBar = "false"` or in the cs code (does not matter how)
3. Start a new instance of the project and see empty space at the bottom of the page

### Expected Behavior
Navigation bar hides completely and doesn't affect the application design

### Actual Behavior
Navigation bar becomes transparent, docks to the bottom of the page and push all the content upper on itself height.

![image](https://user-images.githubusercontent.com/30673836/64798057-0bffe180-d58b-11e9-9c7d-88fe0fdf64e8.png)

### Reproduction Link
https://github.com/Nekliukov/Navbar-gtk-bug-application

**Comment by Nekliukov** [comment]
Thanks for the rapid feedback. Is it possible to know how much time do these types of issues take?

**Comment by topeterk** [comment]
Not sure if this fixes applies to all situations but up to now looks fine to me:
``` csharp
            // Workaround: Do not use NavigationBar on GTK platform
            if (Device.RuntimePlatform == "GTK")
                MainPage = new MainPage();
            else
                MainPage = new NavigationPage(new MainPage());
```
I just do not spawn the `NavigationPage` at all. Any Navigation calls are still working that are in my application.

Xamarin.Forms 5.0.0.2012
Xamarin.Forms.Platform.GTK 5.0.0.2012
OpenTK 3.0.1

**Comment by topeterk** [comment]
Ok I just used modal dialogs, when I used PushAsync instead of PushModalAsync this "fix" is no longer working as it still requires a Navigation Page...

```System.InvalidOperationException: PushAsync is not supported globally on GTK, please use a NavigationPage.```

Seems like I try to design everything with Modal pages 😐

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
