### ISSUE TITLE
{TemplateBinding}s in Span no longer works

### ISSUE THREAD

**Issue by Stedy59** [xamarin/Xamarin.Forms#7494]
### Description
Label FormattedString Span Text bindings no longer work

### Sample Code
	<Style x:Key="ForecastItem.v1" TargetType="forecastItems:ForecastItem">
		<Setter Property="ControlTemplate">
			<Setter.Value>
				<ControlTemplate>
					<Grid>
						<Label
							Margin="0,2,0,-2"
							FontFamily="{TemplateBinding FontFamily}"
							FontSize="16"
							HorizontalOptions="Center"
							Text="{TemplateBinding DayText}"
							VerticalOptions="Start" />
						<Label
							Margin="0,2,0,-2"
							FontFamily="{TemplateBinding FontFamily}"
							FontSize="20"
							HorizontalOptions="Center"
							VerticalOptions="End">
							<Label.FormattedText>
								<FormattedString>
									<Span Text="{TemplateBinding HiTempText}" />
									<Span Text="{TemplateBinding DividerText}" />
									<Span Text="{TemplateBinding LoTempText}" TextColor="#AAFFFFFF" />
								</FormattedString>
							</Label.FormattedText>
						</Label>
						<weatherImages:WeatherImageSmall
							Delay="{TemplateBinding Delay}"
							HeightRequest="80"
							HorizontalOptions="Center"
							ImageIcon="{TemplateBinding ImageIcon}"
							VerticalOptions="Center"
							WidthRequest="80" />
					</Grid>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>

### Expected Behavior
text shows on page
### Actual Behavior
no text shown for label with formatted text, other label shows text
### Basic Information

- Version with issue: 4.3.0.778476
- Last known good version: 4.2.0.709249
- IDE: Android
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by StephaneDelcroix** [comment]
👍 for using control template, but I don't see any ContentPresenter. (this comment is unrelated to the issue, I know)

**Comment by StephaneDelcroix** [comment]
most obvious culprits would be #4527 or #4375

**Comment by StephaneDelcroix** [comment]
I can repro this in a unit test. not related to Html

**Comment by Stedy59** [comment]
> 👍 for using control template, but I don't see any ContentPresenter. (this comment is unrelated to the issue, I know)

Stephanie,
The more I thought about your comment, I realized that I should share the complex implementation of the 3 layers of control templates...

The attached file has code snippets for each layer.

The MainPage.xaml "Widget" is set with the following code in the cs file...
**this.Widget.Style = this.Resources["Widget.v1"] as Style;**

which then sets the "ForecastBar" style and subsequent "ForecastItems" at which time the bound values are presented.

The reliance of the **TemplateApplied** events are crucial, as is the template bindings. 

This allows for the 20+ Widgets, 9 ForecastBars, and 5 ForecastItems to be mixed and matched in any combination.

Let me know if you need more information or assistance as I would gladly help!


[ControlTemplates.zip](https://github.com/xamarin/Xamarin.Forms/files/3621588/ControlTemplates.zip)

**Comment by Stedy59** [comment]
A visual of the implementation above...
![1566323419542](https://user-images.githubusercontent.com/46286656/65046873-699b8180-d92f-11e9-9b26-4c53e88cf6c6.png)
![1566323405305](https://user-images.githubusercontent.com/46286656/65046877-6c967200-d92f-11e9-89c5-9d414ab004d5.png)
![1566323311351](https://user-images.githubusercontent.com/46286656/65046983-98b1f300-d92f-11e9-817b-041af9deafc4.png)
