### ISSUE TITLE
SkiaSharp needs more resources

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#7498]
### SkiaSharp is critical to .Net UI

1. SkiaSharp is the cross-platform high-level graphics interface for .Net.
  a) Views can be written covering all platforms.
  b) Any future cross-platform UI development is likely to involve SkiaSharp. Avalonia depends on SkiaSharp. Suggestions for the future of Xamarin often [involve](https://xamarinhelp.com/saving-xamarin-forms/) [SkiaSharp](https://github.com/xamarin/Xamarin.Forms/issues/6877).
  c) [Many projects](https://github.com/mono/SkiaSharp/network/dependents?package_id=UGFja2FnZS0xNTY5NDAxODc%3D) are already dependent on it.
2. SkiaSharp enables XF controls to be written:
  a) Easily, with low maintenance and fewer bugs: just write once instead of once for each platform.
  b) In a platform independent way (which most users want).
  c) Covering all XF platforms. This makes XF platforms other than iOS/Android/UWP more viable.

### SkiaSharp has 0.5 maintainers

There is one maintainer who works half-time. That's completely out of proportion with the project's complexity and importance. He is very good but you cannot expect miracles.

The consequence is that while there are very promising developments in the codebase, nothing is released ([1](https://www.nuget.org/packages/SkiaSharp), [2](https://github.com/mono/SkiaSharp/issues/954), [3](https://github.com/mono/SkiaSharp.Extended/issues/68)), and community PRs are slow to merge ([4](https://github.com/mono/SkiaSharp.Extended/issues/85)).

### Please support SkiaSharp

- Please can @mattleibow work on this full time again? 
- Can someone else can join him with the right to merge PRs and release Nuget packages?
- Perhaps SkiaSharp should graduate from the [mono org](https://github.com/mono) to the [dotnet org](https://github.com/dotnet) as its importance extends to the whole of .Net UI? @terrajobst

@migueldeicaza @jamesmontemagno @davidortinau @samhouts

**Comment by StephaneDelcroix** [comment]
Thanks for giving some visibility to this problem. Unfortunately, that's not a code-defect or anything we can address so we'll have to close it
