### ISSUE TITLE
Update Xamarin.Forms.Platform.Android.FormsViewGroup to API level 26

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7507]
I get the below warning all the time. Also, when VS is clean installed, we need to install API 24 manually otherwise the Xamarin.Forms solution won't compile for Android. Is it possible to update FormsViewGroup to API 26?

> Google Play requires that new applications and updates must use a TargetFrameworkVersion of v8.0 (API level 26) or above. You are currently targeting v7.0 (API level 24).	Xamarin.Forms.Platform.Android.FormsViewGroup			

@PureWeen

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
