### ISSUE TITLE
[Enhancement] Rotate text within a label without rotating the container

### ISSUE THREAD

**Issue by BioTurboNick** [xamarin/Xamarin.Forms#7515]
## Summary

Allow text to rotate without rotating the bounding box.

Currently, using Rotation property:
![Screenshot_20190913-201839](https://user-images.githubusercontent.com/1438610/64901380-78034800-d666-11e9-9d39-3675b077c4fb.jpg)

## API Changes

Add `double TextRotation` to the Label class. This property will rotate the text without rotating the bounding box.

## Intended Use Case
Vertical text is a common formatting need. Using Rotate = 90 can achieve this in many circumstances. However, this method has an issue when the bounding box is small. If the space is tall and narrow, a user would typically want the text to fill that space. Instead, the current version rotates the label after layout, meaning the label is still constrained.

Thus, a property allowing the text to be rotated during layout instead of after would be quite useful. This also appears to be a common problem on Xamarin for years.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
