### ISSUE TITLE
[Bug] CarouselView SnapPointsAlignment and SnapPointsType doesn't work on iOS

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Xamarin.Forms#7517]
I use Xamarin.Forms 4.3.0.778476-pre1

With this ItemsLayout the CarouselView should be work like this 

```
<CarouselView.ItemsLayout>    
<GridItemsLayout  Orientation="Horizontal"  SnapPointsAlignment="Center" SnapPointsType="Mandatory"/>
</CarouselView.ItemsLayout>
```

![snap](https://user-images.githubusercontent.com/14372162/64905377-1e3f6400-d6e0-11e9-9508-440c11ed7fc5.gif)

But on my sample i get the following 

![Screen Recording 2019-09-14 at 11 01 51](https://user-images.githubusercontent.com/14372162/64905361-d8829b80-d6df-11e9-85fa-b84acb00b6c2.gif)

I use DataTemplateSelector for different views.

```
<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ShaXam" 
             xmlns:carouselStuff="clr-namespace:ShaXam.UIHelper"
             xmlns:views="clr-namespace:ShaXam.Views" 
             x:Class="ShaXam.MainPage">
    
        <ContentPage.Resources>
        <ResourceDictionary>
            <carouselStuff:CustomViewSelector x:Key="mySelector"/>
        </ResourceDictionary>
    </ContentPage.Resources>
    
   
        <CarouselView ItemsSource="{Binding AvaiableViews}"
                      ItemTemplate="{StaticResource mySelector}">
            <CarouselView.ItemsLayout>
                <GridItemsLayout 
                    Orientation="Horizontal" 
                    SnapPointsAlignment="Center" 
                    SnapPointsType="Mandatory"/>
            </CarouselView.ItemsLayout>
        </CarouselView>
   
</ContentPage>

```

```
    public partial class MainPage : ContentPage
    {

        public List<Type> AvaiableViews { get; set; } // Must have default value or be set before the BindingContext is set.
        private int _position;
        public int Position { get { return _position; } set { _position = value; OnPropertyChanged(); } }

        public MainPage()
        {
            InitializeComponent();

            On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);

            AvaiableViews = new List<Type>() { typeof(RecentView), typeof(ShaxamView), typeof(DiscoverView) };

            BindingContext = this;

        }
    }
```

```
    public class CustomViewSelector : DataTemplateSelector
    {
        private DataTemplate view1 = new DataTemplate(typeof(RecentView));
        private DataTemplate view2 = new DataTemplate(typeof(ShaxamView));
        private DataTemplate view3 = new DataTemplate(typeof(DiscoverView));

        protected override DataTemplate OnSelectTemplate(object item, BindableObject container)
        {
            // I don't use 'new' at every time as I do need to retain views status
            Type currentView = item as Type;

            if (currentView == typeof(RecentView))
                return view1;
            else if (currentView == typeof(ShaxamView))
                return view2;
            return view3;
        }
    }
```

The Android version is working good !!

**Comment by georgemichailou** [comment]
Here is my solution
https://github.com/georgemichailou/ShaXam

**Comment by jsuarezruiz** [comment]
Thanks for the sample @georgemichailou .
I've been testing and I've seen where us the problem. If you change the Layout from `GridItemsLayout` to `ListItemsLayout`:
![issue7517](https://user-images.githubusercontent.com/6755973/65312076-1117ee80-db92-11e9-9850-b86521043a5d.gif)

It works as expected. The Carousel only supports `ListItemsLayout`. In the next Xamarin.Forms version `ListItemsLayout` changes its name to **LinearItemsLayout** and it will also be the only Layout that can be used in the Carousel (for now).

**Comment by georgemichailou** [comment]
Thanks @jsuarezruiz for your time. 
I update my solution to the new Xamarin.Forms 4.3.0819712-pre2

I use LinearItemsLayout now,  but at the startup I get the following exception (android & ios)

![Screenshot 2019-09-21 at 14 12 05](https://user-images.githubusercontent.com/14372162/65372548-8959df00-dc7a-11e9-8d5c-4a8e0e6f14f1.png)

**Comment by jsuarezruiz** [comment]
Could you attach a repro sample?. I have updated the sample to 4.3.0819712-pre2 and I cannot reproduce the problem.

<img width="1675" alt="7517" src="https://user-images.githubusercontent.com/6755973/65408614-f8a01200-dde5-11e9-809e-b43bbf638ce5.png">

**Comment by georgemichailou** [comment]
Here it is . https://github.com/georgemichailou/ShaXam/commit/8cf89bd942bfdfc665cdc946f228179ba8b3141d

**Comment by jsuarezruiz** [comment]
I have tried your latest sample (using 4.3.0819712-pre2) and everything works fine. Could you do clean and rebuild and try it again?. @PureWeen can you try the latest sample from George?

**Comment by PureWeen** [comment]
@georgemichailou I had the same result as @jsuarezruiz 

Can you update to pre3 see how it works for you?

What device are you testing on specifically?

**Comment by georgemichailou** [comment]
@PureWeen with pre3 is working perfect !! Thanks to all !!
