### ISSUE TITLE
[Bug] Android CollectionView GridItemsLayout Span with Binding does not work anymore

### ISSUE THREAD

**Issue by hudaIT** [xamarin/Xamarin.Forms#7524]
### Description
CollectionView GridItemsLayout Span with Binding does not work anymore.

### Basic Information

- Version with issue: 4.4.0.1153-nightly
- Last known good version: 4.4.0.1142-nightly

**Comment by hartez** [comment]
Pretty sure this is the same problem as #7519. 
@hudaIT Are you setting up the binding in XAML?
