### ISSUE TITLE
[Bug] Carousel Position property doesn't change the position on page constructor - Android only

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Xamarin.Forms#7525]
I use Xamarin.Forms 4.3.0.778476-pre1

At the start i change the carousel position to 1 . I want my first item be the middle item from CarouselView. 

The Android doesn't change the position on MainPage constructor. The iOS is working good!!

```
        public MainPage()
        {
            InitializeComponent();

            On<Xamarin.Forms.PlatformConfiguration.iOS>().SetUseSafeArea(true);

            AvaiableViews = new List<Type>() { typeof(RecentView), typeof(ShaxamView), typeof(DiscoverView) };

            BindingContext = this;

            MainCarousel.Position = 1;
            
        }
```

Here is my demo
https://github.com/georgemichailou/ShaXam

**Comment by jsuarezruiz** [comment]
There is already a related PR: https://github.com/xamarin/Xamarin.Forms/pull/7592 :)

**Comment by georgemichailou** [comment]
Thanks for the quick response about this bug .
