### ISSUE TITLE
[Enhancement] Add Xam.Plugin.Media

### ISSUE THREAD

**Issue by alberk8** [xamarin/Xamarin.Forms#7533]
## Summary
I would be a great addition to the Essential if the Media Plugin could be included in coming version of Essential.  Camera and Photo are essential to most applications.  

https://github.com/jamesmontemagno/MediaPlugin

**Comment by jfversluis** [comment]
Hey @alberk8,

Thanks for the issue! Xamarin.Essentials is something separate from Xamarin.Forms though. 

You can find the Essentials repository here: https://github.com/xamarin/essentials.

I think there is already an issue that describes at least the taking a picture functionality here: https://github.com/xamarin/Essentials/issues/176 and picking a photo here: https://github.com/xamarin/Essentials/issues/177 

I'm going to close the issue on this repo, hopefully I've provided you with all the information you need to track the progress on the Essentials repository.
