### ISSUE TITLE
[Bug] Span Label with max lines and BreakMode breaks on large text with paragraph on Android.

### ISSUE THREAD

**Issue by MathewLC** [xamarin/Xamarin.Forms#7534]
Java.Lang.IndexOutOfBoundsException: 'measureLimit (842) is out of start (0) and limit (277) bounds

### Steps to Reproduce

1.  Paste a large text on Label Text Property with some paragraph. 
2. Set max lines="5" and BreakMode="TailTruncation" ans still don't break.
3. Put text on FormattedText Property inside Text on span and the follow exception will occur on android:
Java.Lang.IndexOutOfBoundsException: 'measureLimit (842) is out of start (0) and limit (277) bounds

### Expected Behavior
To be able to use max lines and break mode on larges text on span the same way I use in Label Text Property. 

### Actual Behavior
On Span Text Property, code breaks.

### Basic Information

- Version with issue: 4.2.0.778463
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
- Android: 9.0

[MainPage.zip](https://github.com/xamarin/Xamarin.Forms/files/3616065/MainPage.zip)

**Comment by samhouts** [comment]
@MathewLC  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by MathewLC** [comment]
[AppTeste.zip](https://github.com/xamarin/Xamarin.Forms/files/3620856/AppTeste.zip)
That it's, the code i've sended was part of this test project to reproduce the issue.

**Comment by MathewLC** [comment]
Looking into the issue I founnd out that the issue is related to the use of the character "\r \n" or just "\n" that identifies a paragraph. Folliwing the android doc, i found "The following code example applies a QuoteSpan to an entire paragraph. Note that if you attach the span to any positions other than the beginning and end of a paragraph, Android does not apply the style at all" - [https://developer.android.com/guide/topics/text/spans](doc). So how do you guys plan to resolve this? The method getPrimaryHorizontal is the one that is breaking the doing spans function. Should xamarin remove the paragraph from string as the android can apply just to paragraphers, or should make it's ow function to deal with the text direction and return the same value that getPrimaryHorizontal?

**Comment by MathewLC** [comment]
The problem is the same of #5669

**Comment by MathewLC** [comment]
Is these already released on some version of nuget package? Because when it do, the 9539 can be closed too. Please, let me know. @rmarinho @samhouts

**Comment by jfversluis** [comment]
This is now merged into master and should be in the nightly tomorrow. Let me know if it works and we can close the other issue too

**Comment by MathewLC** [comment]
Thank you @jfversluis, I'll keep an eye on nightly builds to test the solution when it's released.
