### ISSUE TITLE
[Bug] [UWP][4.3.0-pre1] Setting MainPage in OnStart() crashes app will null reference exception

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#7537]
### Description
On trying out the 4.3.0 pre1 packages, our app started crashing on launch, on UWP.
This is code that has been in production for a very long time on Android and iOS, and that had not caused issues on UWP internal builds up until this package.

### Steps to Reproduce
1. On a sample project, move the `MainPage = new MainPage();` line from the `App()` constructor into `override void OnStart()`
2. Launch the app.

### Expected Behavior
The app will launch as expected
### Actual Behavior
The app will crash with a null reference exception
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.WindowsBasePage.OnApplicationPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Xamarin.Forms.BindableObject.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Element.OnPropertyChanged(String propertyName)
   at Xamarin.Forms.Application.set_MainPage(Page val
```

### Basic Information

- Version with issue: 4.3.0.778476-pre1
- Last known good version: 4.2.0.778463
- IDE: VS2019 16.2.5
- Platform Target Frameworks: 
  - UWP:  18362

### Reproduction Link
```
 public partial class App : Application
    {
        public App()
        {
            InitializeComponent();
            //MainPage = new MainPage(); << moved this to OnStart()
        }

        protected override void OnStart()
        {
            // Handle when your app starts
            this.MainPage = new MainPage();
        }

        protected override void OnSleep()
        {
            // Handle when your app sleeps
        }

        protected override void OnResume()
        {
            // Handle when your app resumes
        }
    }
```

**Comment by jsuarezruiz** [comment]
Attached sample where the problem is reproduced.
[Issue7537.zip](https://github.com/xamarin/Xamarin.Forms/files/3671473/Issue7537.zip)
