### ISSUE TITLE
[Bug] [Shell] Bottom tab navigation doesn't animate between pages

### ISSUE THREAD

**Issue by paul-charlton** [xamarin/Xamarin.Forms#7539]
### Description
When you have a shell page with bottom navigation tabs and try to navigate between them they show the required page but without any animation.

### Steps to Reproduce

1. New project using Shell Template from VS2019
2. Run & click tabs

### Expected Behavior
An animation, similar to using PushAsync(page, true), or GoToAsync(page, true).

### Actual Behavior
No animation, as if PushAsync(page, false) was being used.

### Basic Information

- Version with issue:
XF 4.2.0.778463

- Last known good version:
n/a

- IDE:
VS2019 Pro 16.2.5

- Platform Target Frameworks:
  - iOS:  12.4
  - Android: Not tested
  - UWP:  Not tested

- Nuget Packages:
XF 4.2.0.778463

- Affected Devices:
iPhone6s simulator

### Reproduction Link

Just the standard vs2019 Shell template

**Comment by GiampaoloGabba** [comment]
I think this is more an Enhancement Request than a bug.
iOS does not provide animations when switching tabs (take, for example, the AppStore App.... or every other Apple App)

**Comment by paul-charlton** [comment]
Fair enough, don't have that much experience of using ios and first time developing with a tab bar.  It just didn't 'feel' right when switching tabs!

**Comment by dinesh4official** [comment]
@samhouts , is there any workaround to achieve this requirement until then?

**Comment by samhouts** [comment]
You may be able to achieve this with a custom renderer, but I don't have any code samples on hand.

This will be completed as part of #6033.

**Comment by samhouts** [comment]
Duplicate of #6033
