### ISSUE TITLE
[Bug] CollectionView Label binding context crashes app when scroll

### ISSUE THREAD

**Issue by mharrisonbit** [xamarin/Xamarin.Forms#7541]
### Description
In horizontal collection view if label is added and it has binding context on it and you scroll the app crashes. If the label has hard coded text on it the app runs just fine.
### Steps to Reproduce

1. create horizontal collection view with data template. Inside that there is a pancake view with two images overlaying each other. Below that is the label with text that has binding to the view model. I am limiting the items in the collection view to only 5 items.
2. run the app and when the images load scroll left and right(happens either scrolling rapidly or slowly) the UI freezes and then the app crashes.

### Expected Behavior
the app should show the text as it is different for all items and should scroll to end of list.
### Actual Behavior
the app crashes when scrolled both on iOS and on Droid.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio Mac Community
- Platform Target Frameworks: 
  - iOS:  deplyoment target is 8
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: live xaml, prism, firebase notifications, prism dryIOC, xamarin essentials, FFImageLoading, Pancake Views, xamarin forms google maps, xamarin forms visual material
- Affected Devices:
iOS and Android
### Reproduction Link

here is the collection view code that I am using.

[HomeView.txt](https://github.com/xamarin/Xamarin.Forms/files/3618064/HomeView.txt)
[CrashReport.txt](https://github.com/xamarin/Xamarin.Forms/files/3618044/CrashReport.txt)

**Comment by samhouts** [comment]
@mharrisonbit  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mharrisonbit** [comment]
I hope I just had a brain fart and overlooked something so feel free to let me know if I did. Here is a link to the sample repo. Thanks for help and checking into this. 
https://github.com/mharrisonbit/sampleCollection

**Comment by mharrisonbit** [comment]
I noticed today while working on the app I get the following in the application output.
[Unknown process name] CGPathAddLineToPoint: no current point.

**Comment by hartez** [comment]
@mharrisonbit I just cloned the sampleCollection repo, and it doesn't appear to have a CollectionView in it - is there maybe another commit to push?

**Comment by mharrisonbit** [comment]
@hartez sorry about that, check the repo now. I was in a hurry and didn't look.

**Comment by eiriklie** [comment]
The "[Unknown process name] CGPathAddLineToPoint: no current point." exception seems to come from PancakeView (as far as I can tell). I tried to remove the pancake Nuget, but the app still crashes when scrolling.

**Comment by mharrisonbit** [comment]
@eiriklie, I found that if I removed the label with the text bound to it that it will work fine but as soon as I add that back in it crashes. I have used the collection view before without any issue but I have never mixed images and text in it until now.

**Comment by hartez** [comment]
@mharrisonbit Definitely crashes on 4.2; I updated to the latest 4.3 prerelease and it scrolls without issue on both platforms.
