### ISSUE TITLE
[Bug] Xamarin Shell Crash on HW back button

### ISSUE THREAD

**Issue by alberk8** [xamarin/Xamarin.Forms#7544]
### Description
App crash on press the Android Hardware back button.  Home button does not crash so far.

### Steps to Reproduce

1.  Create a new Xamarin Shell from the Template VS 2019 6.2 or preivew
2. Compile in Debug and run on Emulator API 28 or Physical Phone API 22
3.  Press the Hardware back button (crash)
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

### Expected Behavior
No crash

### Actual Behavior
Crash

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS for windows 2019 6.2 and 6.3 preview
- Platform Target Frameworks: 
  - Android:  APi 22 and 28 tested 
 - Xamarin 4.2.xx all released version, version 4.1 is good.

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/7327
