### ISSUE TITLE
Xamarin forms 4.2 : After up-gradation, Collection view cells Disappears and Appears when adding items  

### ISSUE THREAD

**Issue by vijayMmenlo** [xamarin/Xamarin.Forms#7548]
### Description
Collection view cells Disappears and Appears when adding items to list. It's like showing blank white space and again adding items. 

We are inserting items in middle of the list and it is causing the issue for the first time.
### Expected Behavior
It needs to add smoothly without any existing cells drastic movements.
### Basic Information

- Version with issue: Xamarin forms 4.2
- Last known good version:
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  As of now, facing issue in iOS

### Screenshots

![Screen Shot 2019-09-17 at 12 33 51](https://user-images.githubusercontent.com/29198169/65018782-82179600-d947-11e9-9adb-6cad2b39f926.png)
![Screen Shot 2019-09-17 at 12 34 10](https://user-images.githubusercontent.com/29198169/65018783-82179600-d947-11e9-9f7d-de39f8b6b74f.png)

**Comment by samhouts** [comment]
@ Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@vijayMmenlo  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by vijayMmenlo** [comment]
This is client project & policy don't accept to share. I can share below details.
I have used **ContextViewCell** nuget package to implement **swipe with delete functionality**. Previously tried with listview with delete(Image), Others options but it is not showing images properly even after applied custom renderer. So we got solution with Collectionview to do so. But Collectionview is not behaving properly after inserting items in middle of the list.

Used below nuget package
https://www.nuget.org/packages/ContextViewCell/

Code for your reference:
<DataTemplate x:Key="addEmployeeTemplate">
                 <context:SideContextMenuView IsAutoCloseEnabled="true">
                    <context:SideContextMenuView.View>
                        <Frame HeightRequest="50"  HasShadow="false" WidthRequest="{Binding Source={x:Reference CollectionView}, Path=Width, Converter={StaticResource WidthConverter}, ConverterParameter='0'}">
                            <Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding Source={x:Reference BriefingAttendees}, Path=BindingContext.TappedCommand}" CommandParameter="{Binding .}" />
                            </Frame.GestureRecognizers>
                            <Grid Padding="0,0,0,0" RowSpacing="0">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="Auto" />
                                </Grid.RowDefinitions>
                                <Grid Padding="50,0,0,0">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="Auto" />
                                        <ColumnDefinition Width="*" />
                                    </Grid.ColumnDefinitions>
                                    <Image Source="AddContact" Grid.Column="0" HeightRequest="25" WidthRequest="25" VerticalOptions="Center" />
                                    <Label Grid.Column="1" Margin="1,0,0,0" Text="{Binding name}" TextColor="Black" VerticalOptions="Center" FontSize="16" />
                                </Grid>
                            </Grid>
                        </Frame>
                         </context:SideContextMenuView.View>
<context:SideContextMenuView.ContextTemplate>
                        <DataTemplate>
                            <Frame Margin="-10,0,0,0" Padding="0,0,0,0" IsClippedToBounds="true">
                                <StackLayout Orientation="Horizontal" Spacing="0">
                                    <Button Margin="0,0,0,0" BorderRadius="0" BackgroundColor="Gold" WidthRequest="50" HeightRequest="50" VerticalOptions="CenterAndExpand" HorizontalOptions="EndAndExpand" ImageSource="unfavorite"Command="{Binding Source={x:Reference PageName}, Path=BindingContext.Tap1Command}"
                                        CommandParameter="{Binding .}" />
                                    <Button ImageSource="delete.png" WidthRequest="50" BorderRadius="0" BackgroundColor="Red" HeightRequest="50" VerticalOptions="CenterAndExpand" HorizontalOptions="EndAndExpand" Command="{Binding Source={x:Reference PageName}, Path=BindingContext.Command}" CommandParameter="{Binding .}" />
                                </StackLayout>
                            </Frame>
                        </DataTemplate>
                    </context:SideContextMenuView.ContextTemplate>
                </context:SideContextMenuView>
            </DataTemplate>

Please help on this.

**Comment by DeanFaizal** [comment]
Hey @samhouts please find repro sample attached. Somehow it doesn't happen if I add an item right after creating the ObservableCollection.

[TestCollectionViewAdd.zip](https://github.com/xamarin/Xamarin.Forms/files/3627343/TestCollectionViewAdd.zip)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2334530/65165049-fddb1680-da0b-11e9-9caf-1b73c2e2ca7d.gif)

**Comment by andreabalducci** [comment]
Found same issue, if you need another repro:  https://github.com/andreabalducci/XamarinCollectionView/blob/b186e563ff8391dfb473e62e5a4c4587e8d4e9da/cvrepro/cvrepro/ListViewModel.cs#L46

**Comment by hartez** [comment]
#7472 is the same issue. Fixed by #7580.
