### ISSUE TITLE
[Enhancement] Hot Reload working with UWP

### ISSUE THREAD

**Issue by stevechadbourne** [xamarin/Xamarin.Forms#7560]
## Summary
Hot Reload does not work with UWP.

## API Changes
I'm not sure what API changes are required.

## Intended Use Case
A lot of us Xamarin Forms developers have to support UWP and actually use it as our platform of choice due to the fast dev cycle. Please add support for this platform.

**Comment by MagicAndre1981** [comment]
[This Reloader](https://github.com/AndreiMisiukevich/HotReload) supports UWP (but only remote debugging on 2nd device)

**Comment by maddyleger1** [comment]
Hi there!! We are tracking this on the Developer Community side of things - feel free to upvote and add your thoughts here: https://developercommunity.visualstudio.com/idea/661682/xaml-hot-reload-for-xamarinforms-on-uwp.html
