### ISSUE TITLE
ContentPage Appearing & Disappearing Transition 

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7561]
Hi,

It will be great if you add a transition for the PageContent’s OnAppearing and OnDisappearing so page can be opened with Fade, Slide from Top, bottom, right and left, etc

Thanks,
Jassim

**Comment by lavilaso** [comment]
They are already working on a specification for this [here](https://github.com/xamarin/Xamarin.Forms/issues/6033)

**Comment by lavilaso** [comment]
In the meantime you can try these options:
[AnimationNavigationPage](https://github.com/AlexandrNikulin/AnimationNavigationPage)
[Xamarin.Plugin.SharedTransitions](https://github.com/GiampaoloGabba/Xamarin.Plugin.SharedTransitions)

**Comment by samhouts** [comment]
Duplicate of #6033
