### ISSUE TITLE
Shell Navigation Back Button Title

### ISSUE THREAD

**Issue by wesoos** [xamarin/Xamarin.Forms#7573]
On iOS, it seems that NavigationPage.BackButtonTitle does not work.  The back button always shows some text, when I set the value to be empty.

Is their a work around or a different way?

**Comment by samhouts** [comment]
@wesoos  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@wesoos  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Jared-Aus** [comment]
This still seems to be an issue. What's the Shell equivalent of NavigationPage.BackButtonTitle="..."?

**Comment by AhmetCavus** [comment]
@Jared-As a workaround just set the title of the previous page to empty.

**Comment by muak** [comment]
@samhouts 

This issue hasn't been solved yet.
I create a Project with VS for Mac Shell template.
I add the ItemsPage.xaml the following:

```
NavigationPage.BackButtonTitle="Change"
```

But the detail page back button title is not changed.
I attached the small reproduce project.

Thanks.

![Simulator Screen Shot - iPhone 8 - 2020-05-31 at 15 33 37](https://user-images.githubusercontent.com/16084475/83346037-26b1fa80-a354-11ea-988a-eb74f9545534.png)


[ShellNavigationBackTitle.zip](https://github.com/xamarin/Xamarin.Forms/files/4707189/ShellNavigationBackTitle.zip)

**Comment by grierson** [comment]
Also having this issue, tried this and still not removing the Title of the previous page from the back button text. Could you reopen the ticket please?

`    <Shell.BackButtonBehavior>
        <BackButtonBehavior TextOverride=""></BackButtonBehavior>
    </Shell.BackButtonBehavior>`
