### ISSUE TITLE
[Bug] ScrollBar is not visible from Xamarin Forms v3.5.0.129452 in Android platform

### ISSUE THREAD

**Issue by DineshBabuYadav** [xamarin/Xamarin.Forms#7574]
### Description

I have added a list of `Label`'s in a `StackLayout` and added the `StackLayout` in the `ScrollView` and performed scrolling by gesture action. Until the Xamarin Forms **v3.4.0.1039999**, `ScrollBar` gets visible while scrolling the items. But after upgrading the Xamarin Forms **v3.5.0.129452 and above**, `ScrollBar` is not visible in **Android** platform while scrolling.

After further analyzing the Xamarin Source, found that due to the following pull request, it gets break i.e., **[Android] ScrollViewRenderer now inherits from NestedScrollView**.

https://github.com/xamarin/Xamarin.Forms/pull/4522 

### Steps to Reproduce

1. Run the attached sample in **Android** platform. 
2. Scroll the items in the view by gesture action.
3. Note that `ScrollBar` is not visible when `ScrollView` gets scrolled.

### Expected Behavior

`ScrollBar` need to be visible when the items are being scrolled in `ScrollView`.

### Actual Behavior

`ScrollBar` is not visible in view when items are being scrolled.

### Basic Information

- Version with issue: **XF v3.5.0.129452** and above.
- Last known good version: **XF v3.4.0.1039999**

### Screenshots
![XF v3 4 0 1039999](https://user-images.githubusercontent.com/20282188/65152300-4e229a80-da45-11e9-9791-fcb7a66a065e.png)
![XF v3 5 0 129452](https://user-images.githubusercontent.com/20282188/65152301-4ebb3100-da45-11e9-8470-f4cc995c6b43.png)

### Reproduction Link
[GettingStarted.zip](https://github.com/xamarin/Xamarin.Forms/files/3626593/GettingStarted.zip)

**Comment by DineshBabuYadav** [comment]
Additionally, We have already logged a bug report regarding **Horizontal and Vertical scrollbar as always visible for ScrollView** is not working issue in the below report.

https://github.com/xamarin/Xamarin.Forms/issues/1596

Can you please check this and revert us?

**Note: I work for Syncfusion**

**Comment by hartez** [comment]
`VerticalScrollBarVisibility="Always" doesn't seem to be working on Android _or_ iOS.

**Comment by syncsiva** [comment]
Hi Team, Can you update us on this issue?

**Comment by PureWeen** [comment]
@DineshBabuYadav if you try the latest nightly is this fixed?

I think this might be resolved by
https://github.com/xamarin/Xamarin.Forms/pull/8090

**Comment by thisismyself** [comment]
@PureWeen 
I am testing the XF 4.4.0.991210-pre2 right now. Issue seems to be resolved for my case. I have a ScrollView containing a Grid. Scrollbar appears when I start scrolling. Only tested on emulator, cannot use device this week.

Might be related: Scrolling in the CollectionView still does not show a scrollbar.

**Comment by PureWeen** [comment]
Closing for now @DineshBabuYadav let me know if you want me to reopen

**Comment by syncsiva** [comment]
@PureWeen  @samhouts  Thanks. The issue has been fixed with https://www.nuget.org/packages/Xamarin.Forms/4.4.0.991265
