### ISSUE TITLE
[Bug] FlyoutBehavior="Locked" Doesn't Work

### ISSUE THREAD

**Issue by DandiAndy** [xamarin/Xamarin.Forms#7576]
### Description

Attempting to lock the flyout doesn't work.

### Steps to Reproduce

1. Set the FlyoutBehavior to 'Locked'
2. Run the application

### Expected Behavior

The flyout can't be closed by the user, and that it doesn't overlap content.

### Actual Behavior

The flyout works as if FlyoutBehavior was set to 'Flyout'

### Basic Information

- Version with issue: Tested on both 4.3.0.778476-pre1 and 4.2.0.778463
- IDE: Visual Studio and Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  12.2
  - Android: 8.1
- Nuget Packages: NETStandard.Library, Xamarin.Essentials

### Reproduction Link

Note: FlyoutBehavior set on line 10 of AppShell.xaml.
https://github.com/DandiAndy/TabBarScrollingBugsXamarinShell

**Comment by DandiAndy** [comment]
I see that the ShellFlyoutRenderer has its PreferredDisplayMode set to PrimaryHidden on navigation, regardless of how the FlyoutBehavior is set.

Though it's a hack, for those who need to override the flyouts behaviour to be permanently open (for now) can use override the ShellFlyoutRenderer and use something like this:

```
public class MyShellFlyoutRenderer : TabletShellFlyoutRenderer
    {

        public override UISplitViewControllerDisplayMode PreferredDisplayMode
        {
            set => base.PreferredDisplayMode = UISplitViewControllerDisplayMode.AllVisible;
        }

        protected override void ToggleFlyout()
        {
            //base.ToggleFlyout();
        }

        protected override void OnFlyoutIsPresentedChanged()
        {
            //base.OnFlyoutIsPresentedChanged();
        }
    }
}
```

Note that I'm overriding the TabletShellFlyoutRenderer in my example though ( I wouldn't recommend leaving the flyout open on a phone anyway).

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/7725
