### ISSUE TITLE
[Bug] Android after version 4.2 hamburger color is always white (Kind of disappears)

### ISSUE THREAD

**Issue by Elashi** [xamarin/Xamarin.Forms#7577]
### Description
After upgrading to version 4.2 , when changing foreground color in AppShell.xaml , the hamburger color stays white (always).

### Steps to Reproduce
Change the color in AppShell.xaml as follows:
`                <Setter Property="Shell.ForegroundColor" Value="Black" />`

### Expected Behavior
The hamburger icon color should be black.

### Actual Behavior
The hamburger icon color is white.

- Version with issue: 4.2
- Last known good version: 4.1
- IDE: VS 2019

### Screenshots
![image](https://user-images.githubusercontent.com/12378171/65158805-bd938c80-da3b-11e9-9451-f16313bf6831.png)

### Sample project
[HiddenHamburger.zip](https://github.com/xamarin/Xamarin.Forms/files/3627006/HiddenHamburger.zip)

**Comment by CliffAgius** [comment]
Seeing the same here as a quick workaround I have made the Shell.FlyoutIcon="hamburger.png" in the blue that I need.  

This happened a while back on IOS hence I already had the png in my project and just needed to copy over to the Android resources.  Not ideal and a bit hacky but works while a fix is in progress.

**Comment by hartez** [comment]
`<Setter Property="Shell.TitleColor" Value="Black" />` is the property in question, but it definitely is no longer affecting the hamburger on 4.2.

**Comment by Elashi** [comment]
The problem is that my app's background is white.  So the hamburger icon is not visible and the back button is not visible.  Is this going to be fixed anytime soon?

**Comment by cfb11** [comment]
I have version 4.3 and Shell hamburger menu stills always white. This bug was already fixed?

**Comment by valentin-debris** [comment]
> I have version 4.3 and Shell hamburger menu stills always white. This bug was already fixed?

@cfb11, setting <Shell ... **ForegroundColor="Blue"**> makes the burger blue for me, on Xamarin.Forms 4.3 (updated today)

**Comment by cfb11** [comment]
> > I have version 4.3 and Shell hamburger menu stills always white. This bug was already fixed?
> 
> @cfb11, setting <Shell ... **ForegroundColor="Blue"**> makes the burger blue for me, on Xamarin.Forms 4.3 (updated today)

It works. Thanks,
However, if we have a toolbaritem it doesn't work on that. If we set the foregroundColor to color the 3 dots (secondary toolbaritem) will be hidden.

**Comment by Amine-Smahi** [comment]
How to fix this problem ?

**Comment by PureWeen** [comment]
@cfb11 @Amine-Smahi can you log a new issue?
