### ISSUE TITLE
[Bug] - Android - Cannot control back button using Navigation Page bindable property.

### ISSUE THREAD

**Issue by SudhersonV** [xamarin/Xamarin.Forms#7578]
Hello, 
      We have an ExtendedContentPage used by WebViewPage.xaml as below,
                           NavigationPage.SetHasBackButton(this, HasBackButton);  is not working after Xamarin upgrade, please suggest solution.

<v:ExtendedContentPage xmlns="http://xamarin.com/schemas/2014/forms" 
		xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
		Title="{Binding Title}" HasBackButton="False">

public class ExtendedContentPage : ContentPage
{

         public static readonly BindableProperty HasBackButtonProperty =
            BindableProperty.Create("HasBackButton", typeof(bool), typeof(ExtendedContentPage), true);

         public bool HasBackButton
         {
             get { return (bool)GetValue(HasBackButtonProperty); }
             set { SetValue(HasBackButtonProperty, value); }
         }

        protected override void OnAppearing ()
	{
		base.OnAppearing ();
                 if (!HasBackButton && Device.RuntimePlatform == Device.Android)
                 {
                        NavigationPage.SetHasBackButton(this, HasBackButton);
                 }
      }
}

### Steps to Reproduce

1. Create an extended Content page using Content page. The extended page should override the OnAppearing methods with the code provided above to control the backbutton
2. Add a bindable property to control the back button in Android
3. Use the extended content page in a sample xaml page and pass the flag to false.

### Expected Behavior
        The back button shouldn't visible
### Actual Behavior
        Back button is visible
### Basic Information

- Version with issue: Xamarin.Forms. 4.2
- Last known good version: Xamarin 2.0
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 9 , API 28
- Nuget Packages: NA
- Affected Devices: All devices

**Comment by samhouts** [comment]
@SudhersonV  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by SudhersonV** [comment]
Invalid bug reported.
