### ISSUE TITLE
[Bug] UWP Map not moving to location when map hidden then shown

### ISSUE THREAD

**Issue by stevechadbourne** [xamarin/Xamarin.Forms#7581]
### Description

The UWP map does not zoom and change location when it starts out hidden then is made visible. 

I attached a small test solution that shows the issue. It creates a new map, adds 2 pins and uses MoveToRegion to set the initial zoom level and position. The map has IsVisible set to false and a button then sets it to true.

If the map is visible initially, all works as expected.

Examining the source shows this line in the UWP map renderer that could be the culprit:

`await Control.TrySetViewBoundsAsync(boundingBox, null, animation);`

It may fail due to attempting an animation on a hidden control.

This works as expected on Android.

### Steps to Reproduce

1. Update code to add Bing map key in MainPage.xaml.cs in UWP project 
2. Build and run app on UWP
3. Click Toggle Map Visibility button

### Expected Behavior

Map has zoomed and moved to expected location

### Actual Behavior

Map remains fully zoomed out and located at 0, 0

### Basic Information

- Version with issue: 4.2.0.778463
- Last known good version: None
- IDE: Visual Studio 2019 Preview 4
- Platform Target Frameworks: 
  - iOS:  NA
  - Android: NA 
  - UWP:  16299
- Android Support Library Version: 
- Nuget Packages: Xamatin.Forms, Xamarin.Forms.Maps
- Affected Devices: Windows 10

### Screenshots
This shows the issue on Windows 10
![map_issue_1](https://user-images.githubusercontent.com/4307880/65215254-47049680-daf0-11e9-8ef2-ef5fb646ba87.png)

This shows correct behavior on Android
![map_issue_2](https://user-images.githubusercontent.com/4307880/65215324-80d59d00-daf0-11e9-92a8-2783e48c2646.png)

### Reproduction Link

Zip containing small project that replicates the issue
[FormsMapIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3629524/FormsMapIssue.zip)

**Comment by krdmllr** [comment]
I looked into this since I already did some work on the maps renderer recently :) 

> await Control.TrySetViewBoundsAsync(boundingBox, null, animation);
> 
> It may fail due to attempting an animation on a hidden control.

This is not the case, setting the animation to none does not fix it. But `TrySetViewBoundsAsync` has a return bool value which indicates if the move was successful. I opened a PR in which this value is stored and a new move is done on the next layout of the control. See #7960, I added your sample there aswell :)
