### ISSUE TITLE
Null Reference Exception thrown when set FontFamily for label in Xamarin Forms macOS

### ISSUE THREAD

**Issue by KarthikRaja26** [xamarin/Xamarin.Forms#7582]
### Description

We have applied "HelveticaNeue LT 55 Roman" font family for Xamarin Forms label. When we try to launch the sample in Xamarin Forms macOS, Null Reference Exception thrown only in Xamarin Forms macOS.

### Steps to Reproduce

1. Run the Attached sample
2. Now you can see the Null Reference Exception. 

### Expected Behavior
Null Reference Exception should not thrown and should apply "HelveticaNeue LT 55 Roman" font family to Label.
### Actual Behavior
Null Reference Exception thrown when Set Font Family to label.
### Basic Information

- Version with issue: Xamarin Forms 3.6.0.34447
- Last known good version: Xamarin Forms 3.2.0.871581
- IDE: Visual Studio
- Platform Target Frameworks: macOS

### Screenshots

![image](https://user-images.githubusercontent.com/46777511/65217276-342e9980-dad1-11e9-8ede-61e9cfcd43c1.png)

### Reproduction Link

[SampleBrowser.zip](https://github.com/xamarin/Xamarin.Forms/files/3629631/SampleBrowser.zip)

**Comment by StephaneDelcroix** [comment]
Please try with a more recent Forms build

**Comment by StephaneDelcroix** [comment]
happens on 4.2 too

**Comment by jfversluis** [comment]
Although it should not crash, this only happens whenever the font is not available on the machine. Are you absolutely sure that it is installed correctly and you have the Font Family name right?
