### ISSUE TITLE
[Bug] iOS13 iPhone X Images missing

### ISSUE THREAD

**Issue by overzealus** [xamarin/Xamarin.Forms#7601]
### Description
On iPhone X running iOS 13 (latest public release) some images are not displayed.
This bug doesn't happen on iPhone 7 Plus running the same iOS 13 and on previous iOS versions.
Image is defined in XAML:
<Image Source="view_details.png" HorizontalOptions="Center" x:Name="imgLiveDataTable"/>

When I try to load image from code:
imgLiveDataTable.Source = "view_details.png";
It doesn't help too. 

This bug doesn't happen on previous iOS versions and it doesn't happen on iPhone 7 Plus with iOS 13.
### Steps to Reproduce

1. Create Grid with several different images
2. Run it on iPhone X with iOS13

### Expected Behavior
All images should appear.
Screenshot from iPhone 7 Plus, running iOS13 (app is downloaded from the AppStore, so it's absolutely the same build):
https://1drv.ms/u/s!AntRP9CCzFJp19NVmhcZ3hNG3m4z7g

### Actual Behavior
Some imiages are missing,
Screenshot from iPhone X, running iOS13 (app is downloaded from the AppStore, so it's absolutely the same build): 
https://1drv.ms/u/s!AntRP9CCzFJp19NUkvNe2-9_p8RefA

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: unknown
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:  12.2

- Nuget Packages:
- Affected Devices: iPhone X (confirmed), may be other newer iPhones like XS and Xr.

**Comment by bcaceiro** [comment]
Not sure if related. But, I'm using FFimageLoading to load images, and in iOS, the performance is horrible in Xamarin.Forms v4.1+. already opened an issue in the FFimageLoading library, but no answer whatsoever.

**Comment by overzealus** [comment]
I have a confirmation from one of users, that this bug is fixed in iOS 13.1 beta 4.
But if there's any chance to find a workaround with iOS 13.0?

**Comment by samhouts** [comment]
@overzealus  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by xperseguers** [comment]
@bcaceiro Next time be sure to add the cross-link to FFimageLoading, this helps a lot: https://github.com/luberda-molinet/FFImageLoading/issues/1337

**Comment by samhouts** [comment]
iOS13.1 is released now. Are we good to close this issue? Thanks.

**Comment by overzealus** [comment]
Yes, with iOS 13.1 this bug is gone.
