### ISSUE TITLE
How to add a long list of multiple custom pins to the Pins IList?

### ISSUE THREAD

**Issue by LSparkzwz** [xamarin/Xamarin.Forms#7609]
I'm following the guide here:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin

Here you create a "customMap.CustomPins" list with a single "pin", then you manually add the single pin to "customMap.Pins" with "Add". What if I have a long list "customPins" of CustomPin though? How can I add all them to  "customMap.Pin"?
Doing "customMap.Pins = customPins;" doesn't work because it's readable only.
I can't use AddRange either because Pins is an IList.
Is the only way to cycle through the list with a foreach and run "Add" every time?

`
public MapPage ()
{
  ...
  var pin = new CustomPin { . . . };

  customMap.CustomPins = new List<CustomPin> { pin };
  customMap.Pins.Add (pin);
  customMap.MoveToRegion (MapSpan.FromCenterAndRadius (
    new Position (37.79752, -122.40183), Distance.FromMiles (1.0)));
}
`

**Comment by StephaneDelcroix** [comment]
Thanks for your question, but you'd have a better chance to get an answer on, say, StackOverflow. And you'll get a wider range of answers too.

my suggestion ? If you want AddRange, implement it as an extension method on IList, and you're done
