### ISSUE TITLE
[Bug] XAML inheriting "x:Name" causing XAMLPARSEEXCEPTION

### ISSUE THREAD

**Issue by tlhintoq** [xamarin/Xamarin.Forms#7610]
### Description
XAML is supposed to not be heritable.  While updating a working app from XF3.x to 4.2 we are finding that is no longer the case.
`PopupBase.xaml` - Base class for popups. Contains a {Grid} with `x:Name = "contentGrid"`
`AlertPopup : PopupBase` - A popup inherited from PopupBase so the CSharp code behind can inhert for common properties like background color and so on.
The derived `AlertPopup` also has a {Grid} with `x:Name = "contentGrid"`.  This is so the inherited code behind can affect the XAML {Grid} of any derived `Popup`.
**This was perfectly fine in 3.6.xxx**
However in 4.2 it generates a XAMLPARSEEXCEPTION.
As soon as you change the x:name of the inherited popup all is fine.
I found this by removing all the XAML from the inherited popup then placing some back, more back ... until it once again failed.  See attached image.

### Steps to Reproduce

1.  make a XAML view
2. Inherit from the XAML view
3.  Pick an element in the parent and give it an `x:name`
4. Give an element in the inherited view the same `x:name`

### Expected Behavior
Same as in 3.6 - It shouldn't be a problem because XAML shouldn't inherit even though the CSharp behind does.

### Actual Behavior
XamlParseException

### Basic Information

- Version with issue: 4.2
- Last known good version: 3.6
- IDE: VS2017

### Screenshots
![XAMLxName_bug](https://user-images.githubusercontent.com/11351506/65352733-56034b80-dbb9-11e9-8dc7-7b14046af66a.jpg)

**Comment by StephaneDelcroix** [comment]
> XAML is supposed to not be heritable

Indeed, so don't. and use ControlTemplate.

The new behavior is correct, though. both the base and the derived class contribute to the same instance, and you should be able to FindByName, on that instance, objects in any of the Xamls.

In addition to that, x:Name creates fields, and they are shared on the instance

The x:Reference should, ideally, only resolves through the current XAML, but that's not worth caring about as having duplicates throws an exception.

Again, you're 100% right, do not, never, inherits XAML controls
