### ISSUE TITLE
[Enhancement] Allow negative ItemSpacing for LinearItemsLayout

### ISSUE THREAD

**Issue by balazserd** [xamarin/Xamarin.Forms#7626]
## Summary
If negative ItemSpacing is allowed, overlapping can easily be solved between items in CollectionView.

## API Changes

On [this](https://github.com/xamarin/Xamarin.Forms/blob/69171055d6b218d24747cfe5b7beb200344f5317/Xamarin.Forms.Core/Items/ListItemsLayout.cs#L21) line, the validateValue property should not be defined as it is now. Allow negative values to be passed.

e.g.

```
public static readonly BindableProperty ItemSpacingProperty =
			BindableProperty.Create(nameof(ItemSpacing), typeof(double), typeof(LinearItemsLayout), default(double),
				validateValue: (bindable, value) => {
				    try {
				        Convert.ToDouble(value);
				        return true;
				    catch {
				        return false;
				    }
				});
```

## Intended Use Case
Allow partially overlapping items in a collectionview.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
