### ISSUE TITLE
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs .

### ISSUE THREAD

**Issue by Cloudtrackers** [xamarin/Xamarin.Forms#7627]
When i am submitting iOS build for review getting this error. i am not using UIWebView anywhere in my xamarin forms project.

**Comment by Cloudtrackers** [comment]
<img width="1394" alt="Screen Shot 2019-09-23 at 1 54 55 PM" src="https://user-images.githubusercontent.com/55684888/65417222-9c031e00-de0a-11e9-898a-b808c66ffd68.png">
It seems like compiler is not removing unwanted class files or libraries.

**Comment by MitchBomcanhao** [comment]
@Cloudtrackers see https://github.com/xamarin/Xamarin.Forms/issues/7323

**Comment by StephaneDelcroix** [comment]
dupe of #7323
