### ISSUE TITLE
[Enhancement] GoToVisualState for XAML

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#7632]
## Summary
Allow to use VisualState.GoTo in triggers

## API Changes
``` xaml
<DataTrigger.EnterActions>
    <GoToVisualState State="Focus" />
</DataTrigger.EnterActions>
```

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
