### ISSUE TITLE
Transition Animation is not smooth in Xamarin Forms WPF platform[Bug] 

### ISSUE THREAD

**Issue by PraveenKoildasan** [xamarin/Xamarin.Forms#7633]
### Description

When we translate some object from one point to another point using TranslateTo method, the transition animation is not smooth like other platforms. We have attached the video and sample for your reference. Please fix this issue with high priority and let us know the details.

### Steps to Reproduce

1. Run the sample in WPF platform.
2. Tap the thumb (Green Color)
3. Transition animation is not smooth.

### Expected Behavior

Smooth transition animation.

### Actual Behavior

Transition animation is not smooth.

### Basic Information

- Version with issue: .NET FrameWork 4.6.1
- Last known good version: 4.2.0.815419
- IDE:
- Platform Target Frameworks: 
 WPF - .NET FrameWork 4.6.1
- Nuget Packages:
- Affected Devices: WPF

### Screenshots

**Video File:**

[Video.zip](https://github.com/xamarin/Xamarin.Forms/files/3642061/Video.zip)

### Reproduction Link

https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample_(1)1752588931

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
