### ISSUE TITLE
[BUG]Imagesource that is generated by SvgImageSource is not compatible with all new xamarin forms features

### ISSUE THREAD

**Issue by GreggAtCarfac** [xamarin/Xamarin.Forms#7637]
### Description
I am using FFImageLoading to use SVG images.
If i add the imagesource from the SvgImageSource It does not work for all the new control features.

At first look it does not work with
ToolbarItem => IconImageSource
Button => ImageSource

Works with
Image
Imagebutton 

### Steps to Reproduce

Load Image with imagesource.fromfile and SvgImageSource.fromrecource and compare results.
Example provided for button below.

### Expected Behavior
Image should be shown
### Actual Behavior
Image dous not load for all components
### Basic Information

- Version with issue: 4.2.0.815419
- FFimageLoading: 2.4.11.982
- Last known good version: unknown
- Platform: PLC project
- IDE: Visual studio 2019

Xaml
![image](https://user-images.githubusercontent.com/55483910/65433483-6287de00-de1d-11e9-9d82-f5a8df7af56a.png)

Viewmodel
![image](https://user-images.githubusercontent.com/55483910/65433501-73385400-de1d-11e9-84a3-758b75a760e7.png)

**Comment by StephaneDelcroix** [comment]
Thanks for reporting this. Unfortunately, we do not provide or maintain SvgImageSource, and there's very little we can do here.
