### ISSUE TITLE
Is Xamarin.forms app 3.6 will work on iOS13

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#7643]
We are currently on Xamarin.forms 3.6 and we yesterday updated VS for Mac. I tried update the Xcode to 11 but it doesn't work. 

When I run my app on IOS 13 I didn't see anything in emulator and application output is blank also. The app was working fine earlier.

Will Xamarin.forms 3.6 work with IOS 13, or I need to downgrade Xcode to make my development move forward.

Thanks

**Comment by rmarinho** [comment]
Hi @anirugu Xamarin.Forms 3.6 supports iOS13, we just tested and had no issues. Make sure you are on the latest stable of Visual Studio for Mac. 

If you still have issues please open new bug with repo and more information about your setup.

**Comment by anirugu** [comment]
Did you read "When I run my app on IOS 13 I didn't see anything in emulator and application output is blank also. The app was working fine earlier."

How I can give details when the application output showing nothing?

**Comment by PureWeen** [comment]
@anirugu what version are you on?

The latest patch version of 3.6+ has a fix in it that forces modal to be fulscreen

If you're still having an issue can you attach a repro?

**Comment by PureWeen** [comment]
@anirugu 

@anirugu what version are you on?
The latest patch version of 3.6+ should all work on ios13

we fixed an issue with MDP not showing on Ios13

Can you attach a repro if you're still having issues?
