### ISSUE TITLE
where to download 8.2 Visual studio for Mac

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#7644]
the current release waste a lot of time of mine, Can anyone tell me how to get back old version.

**Comment by anirugu** [comment]
the release blog now redirect to devblog which means just search on google and waste more and more time. Anyone have any help to get it fixed. The current release is not going to work with xforms 3.6

**Comment by rmarinho** [comment]
Hi @anirugu Xamarin.Forms 3.6 supports iOS13, we just tested and had no issues. Make sure you are on the latest stable of Visual Studio for Mac. 

If you still have issues please open new bug with repo and more information about your setup.
