### ISSUE TITLE
[Bug] There is a loop that make it run out of memory on Android

### ISSUE THREAD

**Issue by tqngan1984** [xamarin/Xamarin.Forms#7645]
### Description

There is a loop that make View.updateDisplayListIfDirty and ViewGroup.recreateChildDisplayList are called recursively and caused run out of memory. This bug was found from Fabric trace stack.

### Basic Information

- Version with issue: 3.5.0
- Last known good version: Unknown
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

<img width="1122" alt="Screen Shot 2019-09-24 at 3 04 52 PM" src="https://user-images.githubusercontent.com/1107856/65493379-efde3780-dedc-11e9-9c71-a80f84e98cb8.png">

<img width="1104" alt="Screen Shot 2019-09-24 at 3 05 00 PM" src="https://user-images.githubusercontent.com/1107856/65493400-f8367280-dedc-11e9-9fec-358b90b2b3d9.png">

**Comment by hartez** [comment]
@tqngan1984 Can you please provide some more information? Steps to reproduce this bug, or a reproduction project which demonstrates it?

**Comment by tqngan1984** [comment]
Currently I can't reproduce this bug, it's found in Fabric and we are using an old Xamarin Forms version 3.5.0. If I found it, I will reply in this channel.

**Comment by samhouts** [comment]
@tqngan1984 Thanks, we'll keep looking for it.

**Comment by samhouts** [comment]
@tqngan1984  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
