### ISSUE TITLE
Layout Issue : LayoutOptions not working inside the AbsoluteLayout

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/Xamarin.Forms#7647]
### Description

In our custom control, we are providing the DataTemplate property for view customization support. But the template does not rendering properly.

If we set the HorizontalOptions or VerticalOptions inside the AbsoluteLayout then the empty view shown. else the template rendered properly.

### Steps to Reproduce

1. Run the attached sample
2. Click open button to open the view
3. DataTemplate does not rendered properly

### Expected Behavior

Custom View(DataTemplate) rendered properly

### Actual Behavior

Custom View(DataTemplate) rendered properly

### Basic Information

- Version with issue: All the version
- Last known good version: No

### Screenshots

**Expected:** 

![Expected Image](https://user-images.githubusercontent.com/44917578/65502440-71839480-dee0-11e9-93fd-bfb0d2647efa.png)

**Actual Output:**

![Ouput Image](https://user-images.githubusercontent.com/44917578/65502474-8102dd80-dee0-11e9-9e17-0b6d4ead9357.png)

### Reproduction Link

**Sample Link** : 
[CustomControl.zip](https://github.com/xamarin/Xamarin.Forms/files/3646592/CustomControl.zip)

### Code Snippet for converting Xamarin forms view to Native forms view
```
////  This is the code snippet for converting Xamarin forms view to Native forms view

view = (Xamarin.Forms.View)template.CreateContent();
var vRenderer = Convert(view, (Xamarin.Forms.VisualElement)formsView.Parent, nativeControl.Context);
var viewGroup = vRenderer.View;
vRenderer.Tracker.UpdateLayout();
var layoutParams = new ViewGroup.LayoutParams((int)size.Width, (int)size.Height);
viewGroup.LayoutParameters = layoutParams;
view.Layout(size);
viewGroup.Layout(0, 0, (int)view.Width, (int)view.Height);
view.Measure(double.PositiveInfinity, double.PositiveInfinity);
 
////  This is the code snippet for converting Xamarin forms view to IVisualElementRenderer

internal static IVisualElementRenderer Convert(Xamarin.Forms.View source, Xamarin.Forms.VisualElement valid, Context context)
{
var render = Platform.GetRenderer(source);
render = Platform.CreateRendererWithContext(source, context);
Platform.SetRenderer(source, render);
return render;
}
```

### In Sample

Set HorizontalOptions or VerticalOptions inside the AbsoluteLayout makes issue
eg.,
```
<AbsoluteLayout BackgroundColor="Transparent" 
                                        Margin="0" 
                                        Padding="1">
<Label FontSize="13"
                                   BackgroundColor="Blue"
                                   AbsoluteLayout.LayoutBounds="0.2,0.2,1,1" 
                                   AbsoluteLayout.LayoutFlags="All" 
                                   FontAttributes="None" 
                                   Text="Demo"  
                                   VerticalTextAlignment="Center" 
                                   HorizontalTextAlignment="Center" 
                                   HorizontalOptions="Center"
                                   VerticalOptions="Center"
                                   TextColor="Red" />
 </AbsoluteLayout>
```

If we does not set HorizontalOptions or VerticalOptions then it does not reproduced as mentioned in ExpectedImage
eg.,
```
<AbsoluteLayout BackgroundColor="Transparent" 
                                        Margin="0" 
                                        Padding="1">
<Label FontSize="13"
                                   BackgroundColor="Blue"
                                   AbsoluteLayout.LayoutBounds="0.2,0.2,1,1" 
                                   AbsoluteLayout.LayoutFlags="All" 
                                   FontAttributes="None" 
                                   Text="Demo"  
                                   VerticalTextAlignment="Center" 
                                   HorizontalTextAlignment="Center" 
                                   TextColor="Red" />
 </AbsoluteLayout>
```

**Comment by PureWeen** [comment]
@Sasikumar3595 I tested your project using XF 3.6 and all the boxes showed up fine there so it looks like this has been fixed inside future versions
