### ISSUE TITLE
[Enhancement] Update README.md as VSMac now support MultiTargeting

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#7648]
## Summary
Please update the README.md of the project. VSMac v8.3 support Multi Targeting. So it should be convenient for new users to know how to contribute from Mac by reading the README.

**Comment by jfversluis** [comment]
While I'd love people to still help out with Xamarin.Forms, I think we should put most of our efforts for this in .NET MAUI for now, thanks :)
