### ISSUE TITLE
[Enhancement] AutomationId for Android TabbedPage

### ISSUE THREAD

**Issue by drjaydenm** [xamarin/Xamarin.Forms#7649]
## Summary
It would be great to have support for AutomationId for tabs in the TabbedPage on Android. At the moment, iOS has this support working [out of the box](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/TabbedRenderer.cs#L429). It seems as if the Android support was simply never implemented.

## API Changes
No visible API changes, just the AutomationId being mapped to the tab as it does on iOS now.

## Intended Use Case
This is super helpful for doing automated UI tests as you need the AutomationId (ContentDescription on Android) or some other unique identifier to 'tap' the button. We have had to implement a custom TabbedPageRenderer to get this working for now.

**Comment by techduggu** [comment]
I've opened the above PR #8194  to support accessibility (`AutomationId`) for Top tabs in the TabbedPage on Android.

**Comment by MappingSteve** [comment]
@techduggu - would Tabs on a TabBar require a separate PR?  Similar issue for TabBar [reported at StackOverflow](https://stackoverflow.com/q/68600930/199364).

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/3996
