### ISSUE TITLE
Application crashing after update in Ios Simulator 13

### ISSUE THREAD

**Issue by anirugu** [xamarin/Xamarin.Forms#7652]
After today's update (VS for Mac), The app doesn't work in latest Xcode. it's crashing.

Nothing is showing in Application output tab. The application is crashing when running the app in simulator.

Any way to sort this out. Anyway to figure out what exactly is going wrong.

**Comment by StephaneDelcroix** [comment]
please provide more info, and eventually a repro.

**Comment by StephaneDelcroix** [comment]
also, you should probably report this to VSMac team
