### ISSUE TITLE
[Enhancement] span TapGestureRecognizer to work with arabic font!

### ISSUE THREAD

**Issue by msdYqb** [xamarin/Xamarin.Forms#7655]
## Summary
span TapGestureRecognizer is not working with Arabic font
when span with Arabic text is tapped in it its either goes to wrong span or nothing happened

## API Changes
example 

```
<Label Grid.Row="0" x:Name="allVerses" FlowDirection="RightToLeft" HorizontalTextAlignment="Center">
            </Label>
```
```
FormattedString formattedString = new FormattedString();
            var arabic = new List<myClass>
            {
                new myClass{Text = "بعض الكلمات بعض الكلمات بعض الكلمات بعض الكلمات", ID = 1 },
                new myClass{Text = "بعض الكلمات بعض الكلمات بعض الكلمات بعض الكلمات", ID = 2 },
                new myClass{Text = "بعض الكلمات بعض الكلمات بعض الكلمات بعض الكلمات بعض الكلمات بعض الكلمات", ID = 3 },
                new myClass{Text = "بعض الكلمات بعض الكلمات بعض الكلمات", ID = 4 },
            };
            foreach (var text in arabic)
            {
                Span verse = new Span();
                var gesture = new TapGestureRecognizer();
                gesture.Command = Command;
                gesture.CommandParameter = text.ID;
                verse.GestureRecognizers.Add(gesture);
                
                verse.Text = text.Text + " ";
                verse.FontSize = 44;
                verse.ClassId = text.ID.ToString();
                formattedString.Spans.Add(verse);
            }
            allVerses.FormattedText = formattedString;

public Command Command
        {
            get
            {
                return new Command((ID) =>
                {
                    allVerses.FormattedText.Spans.Where(s => s.ClassId == ID.ToString()).First().TextColor = Color.Red;
                });
            }
        }
```
## Intended Use Case
I want to be able to highlight selected span
![Screenshot_20190924-203650](https://user-images.githubusercontent.com/31849539/65537644-4a43bc00-df0e-11e9-8f87-58d0daecbd92.png)

**Comment by jfversluis** [comment]
Thanks for the issue @msdYqb.

I'm wondering if this is an actual enhancement or this is a bug that should just work. I'm leaning towards the last one. But in either case, I see you've posted some code already, would you be able to put it together in a sample project so we can see what is going on?

**Comment by hartez** [comment]
I agree with @jfversluis, the recognizers should work with RTL.

**Comment by hartez** [comment]
@msdYqb Are you seeing this problem on Android, iOS, or both?

**Comment by msdYqb** [comment]
on android and UWP

**Comment by msdYqb** [comment]
here is example project

thanks guys!
[ArabicFormattedStringExample.zip](https://github.com/xamarin/Xamarin.Forms/files/3648817/ArabicFormattedStringExample.zip)

**Comment by msdYqb** [comment]
sorry about project name it was to long!

project name fixed
[ArabicFS.zip](https://github.com/xamarin/Xamarin.Forms/files/3648853/ArabicFS.zip)

**Comment by StephaneDelcroix** [comment]
thanks

**Comment by PureWeen** [comment]
Looks like this is also an issue on iOS

it's very obvious that the position calculation just needs to be shifted to account for RTL.
When working on this let's look at a general way to express position when set to RTL so other code that needs to calculate location can reuse it

**Comment by Sauder91** [comment]
I'm seeing this as well on iOS when text wraps.  The hashtags in the image below should all be individually tappable, but only the first one works.  The same layout with different hash tags sometimes works; its hit or miss.  If there is only one it is always selectable though.  
<img width="182" alt="Screen Shot 2019-12-06 at 1 31 35 AM" src="https://user-images.githubusercontent.com/37815396/70304805-60041600-17c8-11ea-9061-55671544952e.png">
