### ISSUE TITLE
KeyNotFoundException when previewing custom view with generic base class

### ISSUE THREAD

**Issue by briman0094** [xamarin/Xamarin.Forms#7658]
### Description
I have a custom view which inherits from a generic base class, which itself inherits directly from `ContentView`. The view works fine when the app is built and run, but when loading the Forms Previewer in Visual Studio 2019, I get a `KeyNotFoundException` from the preview window:

![image](https://user-images.githubusercontent.com/816612/65548444-143c1300-dee1-11e9-94c5-6bda61a314a4.png)

### Steps to Reproduce

1. Clone my [Reproduction Repo](https://github.com/briman0094/XamarinFormsRepro20190924)
2. Open `FruitView.xaml` and switch to the "Preview" tab (I usually split the window between preview and XAML)

### Expected Behavior
The custom view should show in the previewer as it would show at runtime

### Actual Behavior
The previewer crashes with a KeyNotFoundException when loading the custom view XAML

### Basic Information

- Version with issue: v4.2.0.778463
- Last known good version: None
- IDE: Visual Studio 2019 v16.2.3
- Platform Target Frameworks: 
  - Android: SDK 28  
- Affected Devices: None (previewer issue)

### Screenshots

See above

### Reproduction Link

https://github.com/briman0094/XamarinFormsRepro20190924

> VS bug [#988258](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/988258)

**Comment by briman0094** [comment]
Interestingly enough, the previewer is working correctly for me even with a generic base class after updating my copy of Visual Studio to 16.3.0...

**Comment by TimBarham** [comment]
@briman0094 - can you clarify, based on your updated information, the exact steps I need to repro this? Thanks!

**Comment by briman0094** [comment]
@TimBarham you should be able to delete the `FruitView.xaml` and `FruitView.xaml.cs` files before opening Visual Studio, and then add them back while Studio is open and the solution is fully loaded. After adding them back, the previewer should show the error I'm experiencing. I can consistently reproduce the issue on any classes inheriting from the generic base class which are added while Studio is open.

I do think clearing the `bin`/`obj` folders or the `.vs` folder affects the reproducability, because I had recently cleaned those up right before noticing the previewer working correctly.

**Comment by TimBarham** [comment]
Ok, I've tried various combinations of starting without those files, adding them in, building and not building, but haven't been able to repro. Next step... @briman0094, could you clean out your Xamarin log folder (_Help_ / _Xamarin_ / _Open Logs_, and delete everything in there), repro the problem, then send me the resulting logs? There's some output in there that might be useful.

**Comment by drewgillies** [comment]
Thanks for the issue. I'm doing a sweep of Xamarin.Forms previewer issues to close them as we're focusing on areas with greater impact for now. We will keep the issue on file, however, for future reference. Thanks again!
