### ISSUE TITLE
[Bug][Android] Picker NullReferenceException on android api 19

### ISSUE THREAD

**Issue by samelas** [xamarin/Xamarin.Forms#7659]
### Description

NullReferenceException if you open the picker on android and use 2 fingers to tap an option and cancel at the same time

### Steps to Reproduce

1. Open Picker 
2. Simultaneously select an option and the cancel button
3. NullReferenceException occurs

### Expected Behavior

No crash

### Actual Behavior

App crashes with this exception: 
`IPickerRenderer.OnClick>b__0 (System.Object sender, System.EventArgs args) D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\PickerRenderer.cs:135
IDialogInterfaceOnDismissListenerImplementor.OnDismiss (Android.Content.IDialogInterface dialog) /Users/builder/jenkins/workspace/xamarin-android-commercial/xamarin-android/src/Mono.Android/obj/Release/android-28/mcw/Android.Content.IDialogInterface.cs:370
IDialogInterfaceOnDismissListenerInvoker.n_OnDismiss_Landroid_content_DialogInterface_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_dialog) /Users/builder/jenkins/workspace/xamarin-android-commercial/xamarin-android/src/Mono.Android/obj/Release/android-28/mcw/Android.Content.IDialogInterface.cs:335
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.159(intptr,intptr,intptr)`

### Basic Information

- Version with issue: Xamarin.Forms 4.1.0.778454 (4.1.0-sr5)
- Last known good version: Unknown
- IDE: Visual Studio Mac
- Platform Target Frameworks:
  - Android: Android 4.4.4
- Affected Devices: Galaxy Note3

=== Visual Studio Community 2019 for Mac ===

Version 8.2.1 (build 19)
Installation UUID: aef7da93-f2d0-4413-ad45-37e375ff03fc
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000311

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.311 (2019-02/494641b300c) (64-bit)
	Package version: 600000311

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.12
	2.1.9
	2.1.2
	2.0.5
	2.0.0
SDK: /usr/local/share/dotnet/sdk/2.1.701/Sdks
SDK Versions:
	2.1.701
	2.1.505
	2.1.302
	2.1.4
	2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 9.4.0.51 (Visual Studio Community)
Commit: xamarin-android/d16-2/9fa7775
Android SDK: /Users/sams/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.1
SDK Build Tools Version: 25.0.3

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/sams/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.58
Hash: d03e3ea
Branch: remotes/origin/d16-2~1
Build date: 2019-07-16 17:37:14 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:43-0400

=== Xamarin.iOS ===

Version: 12.14.0.110 (Visual Studio Community)
Hash: a8bcecce
Branch: d16-2
Build date: 2019-06-28 07:31:42-0400

=== Xamarin Designer ===

Version: 16.2.0.375
Hash: 357d38ef4
Branch: remotes/origin/d16-2
Build date: 2019-07-26 14:44:54 UTC

=== Build Information ===

Release ID: 802010019
Git revision: c7aee29ba7d2a827dbfe4901e4ad7249ce7e5bc7
Build date: 2019-07-29 20:22:23+00
Build branch: release-8.2
Xamarin extensions: c990de17e8456ead7fce80aff9dab01df769b2fd

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by StephaneDelcroix** [comment]
could you please attach a simple project that triggers the issue ? thanks

**Comment by samelas** [comment]
@StephaneDelcroix This xamarin forms sample will trigger the issue: https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-bindablepicker/ I'm only able to reproduce it on an old android device (Galaxy Note 3 - Android 4.4.4), and the timing has to be just right so the cell selection and cancel button are both highlighted (usually have to try a couple times to get it). The problem seems to be that the dismiss is triggered twice, the first one sets _dialog to null and the second one attempts to then Dispose the null dialog
`_dialog.DismissEvent += (sender, args) =>
{
(Element as IElementController)?.SetValueFromRenderer(VisualElement.IsFocusedPropertyKey, false);
_dialog.Dispose();
_dialog = null;
};`

**Comment by PureWeen** [comment]
@samelas Can you try on the most recent 4.2 or 4.3 pre version of forms?

I'm running that sample on 4.2 and it's not crashing for me

**Comment by samhouts** [comment]
@samelas  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
