### ISSUE TITLE
Xamarin Forms 4.2, app freezes OnResume (Android only)

### ISSUE THREAD

**Issue by SudhersonV** [xamarin/Xamarin.Forms#7661]
### Steps to Reproduce

1.  Launch app in Droid Emulator
2. Push app to back ground
3. Resume app after 5 seconds, the app should navigate to the first page, but frozen.

### Basic Information

- Version with issue: Xamarin Forms 4.2
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 
Xamarin.Android
Version: 9.4.1.0 (Visual Studio Professional)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/xxx/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3
- Nuget Packages: none

- Affected Devices: Android device and emulator -

### Screenshots
Please get the repo from here....
https://drive.google.com/file/d/1JvwbLWOqdHIEwxrE0XtV6S5ZcsfgiL4K/view?usp=sharing

### Reproduction Link

Please get the repo from here....
https://drive.google.com/file/d/1JvwbLWOqdHIEwxrE0XtV6S5ZcsfgiL4K/view?usp=sharing

**Comment by PureWeen** [comment]
I was able to reproduce the issue and I tested it against this PR
https://github.com/xamarin/Xamarin.Forms/pull/7776

which looks to have resolved the issue

**Comment by WilkoSki** [comment]
When is this scheduled for release? As it still seems to be present in 4.2.0.848062

**Comment by samosim** [comment]
This error is really annoying.  When can we expect that the error will be fixed?
