### ISSUE TITLE
[Bug] Snapping issues on CollectionView and CollectionView.ScrollTo() 

### ISSUE THREAD

**Issue by MrMayTwenty** [xamarin/Xamarin.Forms#7665]
### Description

I created a CollectionView with a list of images larger than the viewport.
Initially when you load the collectionview the list starts at the leftmost part of the image.
When you try to scroll using CollectionView.ScrollTo()
the scroll ends at the rightmost part of the image.

### Steps to Reproduce

1. Get images wider than the width of the device 
2. Add images to a list
3. Populate CollectionView using the list.
4. Try to trigger ScrollTo function

### Expected Behavior

Items in the list are centered

### Actual Behavior

Items starts to the left most part.
Item starts to the rightmost part when triggering scrollto()

**Comment by samhouts** [comment]
@MrMayTwenty  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@MrMayTwenty  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
