### ISSUE TITLE
Make SetupLayer on FrameRenderer virtual

### ISSUE THREAD

**Issue by rscholey** [xamarin/Xamarin.Forms#7667]
### Description

Same issue noticed by me when the background color of a frame is changed.  The effect is the same as was observed with the issue #6892

### Steps to Reproduce

I am using this renderer to change the frame shadow:

```
public class CustomFrameRenderer : FrameRenderer
    {
        public static void Initialize() { }
        protected override void OnElementChanged(ElementChangedEventArgs<Frame> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement == null) return;
            UpdateShadow();
  
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
            if (e.PropertyName == "ShadowColor" || e.PropertyName == "Elevation" || e.PropertyName == "LayerBackgroundColor")
            {
                UpdateShadow();
            }
        }

        void UpdateShadow()
        {
            var frame = (CustomFrame)Element;
            Layer.ShadowRadius = frame.Elevation;
            Layer.ShadowColor = frame.ShadowColor.ToCGColor();
            Layer.ShadowOffset = new CoreGraphics.CGSize(0.5, 0.5);
            Layer.ShadowOpacity = 0.5f;
            Layer.MasksToBounds = false;
        }
    }
```

### Expected Behavior

The frame shadow is expected to stay the same

### Actual Behavior

The frame shadow reverts to the default values

### Basic Information

Trying it out for the first time with Forms 4.2.0.778463

**Comment by nikhildpardasani** [comment]
Even I have the exact same issue. I have two different Custom Frames who use the same renderer. 
When the background colour of one changes the other's shadow colour goes to default.

**Comment by StephaneDelcroix** [comment]
please provide a valid, up-to-date, repro project.

**Comment by nikhildpardasani** [comment]
Hi, here is a repo project. This issue occurs only on the iOS Project. I have two frames on the MainPage, when we change themes(backgroundcolours), the shadow of the two frames are not changed correctly. 
Repo :- https://github.com/nikhildpardasani/FrameShadowDemo

**Comment by PureWeen** [comment]
It reverts because there's a call to SetupLayer that overwrites your changes

https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Platform.iOS/Renderers/FrameRenderer.cs#L25

If you match that property list or just call UpdateShadow everytime
```C#
protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);
            if (e.PropertyName == "ShadowColor" || e.PropertyName == "Elevation" || e.PropertyName == "LayerBackgroundColor")
            {
                UpdateShadow();
            }

            UpdateShadow();
        }
```

you'll see it doesn't revert.

UpdateLayer on the base class should be virtual though
