### ISSUE TITLE
[Bug] ContentPage.ControlTemplate gets not rendered in Wpf

### ISSUE THREAD

**Issue by neolithos** [xamarin/Xamarin.Forms#7671]
### Description

Only the `Content` property is rendered in the Wpf PageRenderer.

The solve this, it would be the best to render the first child. PR will follow.

### Steps to Reproduce

Add a control template to a `ContentPage`.

### Expected Behavior

The control template gets rendered.

### Actual Behavior

Only the `Content` gets rendered.

### Basic Information

This issue is only in Wpf present.

**Comment by StephaneDelcroix** [comment]
please provide a sample project. thanks

**Comment by neolithos** [comment]
Example plus my suggested solution is in the pull request 7672.
