### ISSUE TITLE
[Bug] Crash on CarouselView using ObservableCollection

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/Xamarin.Forms#7678]
### Description

Working with https://github.com/xamarin/Xamarin.Forms/pull/7650 I noticed a crash with CarouselView on iOS.

I have created a new sample (which I add to the Core Gallery at https://github.com/xamarin/Xamarin.Forms/pull/7677) to validate the different ways to work  with items in the Carousel on all platforms.

The result:

| Test | iOS | Android | UWP |
| - | :-: | :-: | :-: |
| **Binding to a new ObservableCollection filled with Items**										|	✓	|	x (only using threads)	|	✓	|
| **Binding to a ObservableCollection and add Items later**									|	x	|	✓	|	✓	|
| **Binding to a ObservableCollection and add Items later using Threads**									|	x	|	✓	|	✓	|

### Steps to Reproduce

Use the branch https://github.com/xamarin/Xamarin.Forms/tree/more-carousel-coresamples, launch CoreGallery and navigate to the CarouselView samples. Use the ObservableCollection sample and press the different buttons.
On iOS, the second and third option will crash.

### Expected Behavior
The CarouselView is updated without problems.

### Actual Behavior
Get a crash on iOS!.

### Screenshots
<img width="1286" alt="Captura de pantalla 2019-09-25 a las 18 04 50" src="https://user-images.githubusercontent.com/6755973/65618700-065cbf80-dfbf-11e9-8f69-f5e26e463488.png">

### Reproduction Link
https://github.com/xamarin/Xamarin.Forms/tree/more-carousel-coresamples

**Comment by rmarinho** [comment]
Is this just with CarouselView or with CollectionView also ?

**Comment by jsuarezruiz** [comment]
@rmarinho The problem on Android is related with the Carousel: https://github.com/xamarin/Xamarin.Forms/pull/7693
The iOS crash affects both, CarouselView and CollectionView.
