### ISSUE TITLE
[Bug] Xamarin.Forms Picker ItemDisplayBinding Not Working Properly if Property to Display is not String

### ISSUE THREAD

**Issue by dinobu** [xamarin/Xamarin.Forms#7681]
### Description
Xamarin.Forms Picker ItemDisplayBinding Not Working Properly if Property to Display is not String.

### Steps to Reproduce

1. Create a ContentView and add 2 Pickers (Picker CarName, Picker CarAge)
2. Create ViewModel with Car object having one string and one int property (i.e. Name, Age)
3. Create an IList<Car> of cars and populate it with few car objects
4. Bind CarName picker  ItemSource to list of Cars, SelectedItem to one of the cars from the list, ItemDisplayBinding to Name property from your view model
5. Bind CarAge picker ItemSource to list of Cars, SelectedItem to one of the cars from the list, ItemDisplayBinding to Age property from your view model
6. Run application and tap on picker displaying Name property (which is string) and the picker will expand to show all car names it contains

**PROBLEM: Now tap on the picker showing Age of cars (which is not string but integer).  Notice that you need to tap twice in order to expand this picker.**

### Expected Behavior
I would expect the picker to behave same regardless if the property it is displaying is string or not and to expand once I tap on it.  There should be no need to tap twice on it.

### Actual Behavior
If the property bound to ItemDisplayBinding is not string (in above example it is an int), taping on picker will not expand it until tapped 2nd time

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: Xamarin Forms 4
- Device: UWP

Here is the example of my picker

```
<StackLayout Orientation="Horizontal" 
  BackgroundColor="{StaticResource ConcreteGrayColor}" Margin="10">
    <controls:CustomPicker 
      ItemsSource="{Binding Seats}" 
      ItemDisplayBinding="{Binding Number}" 
      SelectedItem="{Binding SelectedCheckItem}"
      Style="{StaticResource MoveToSeatPickerStyle}"
      HorizontalOptions="StartAndExpand" 
      AutomationId="MoveToSeatPicker"/>
</StackLayout>
```

The above works well if Number property bound to ItemDisplayBinding is string.  If it is an Integer, I need to tap twice on the picker to expand it.

**Comment by samhouts** [comment]
@dinobu  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by WayaFlyfeather** [comment]
I tried to recreate this as a test case in a local branch off 4.30, please see attached .cs, in which I bind to pickers to a list of items with a string and an int property. One picker is showing the string property, and the other the int property (via ItemDisplayBinding).

I see no difference in behavior on UWP, whether the property bound is a string or an int. Both require a single click to open.

Two clicks may be necessary to open a picker, in case another picker is already open: then the first click is to close that picker. So, if you open the string picker, you need one click to close it again, and one to open the int picker. However, this is the same if you start by opening the int picker, then you need a click to close it, and one to open the string picker. So, the behavior is the same, and I assume, expected.

Anyway, I was not able to recreate the bug as described, in 4.3.0 / UWP.

[Issue7681.zip](https://github.com/xamarin/Xamarin.Forms/files/3760450/Issue7681.zip)

**Comment by dinobu** [comment]
> I tried to recreate this as a test case in a local branch off 4.30, please see attached .cs, in which I bind to pickers to a list of items with a string and an int property. One picker is showing the string property, and the other the int property (via ItemDisplayBinding).
> 
> I see no difference in behavior on UWP, whether the property bound is a string or an int. Both require a single click to open.
> 
> Two clicks may be necessary to open a picker, in case another picker is already open: then the first click is to close that picker. So, if you open the string picker, you need one click to close it again, and one to open the int picker. However, this is the same if you start by opening the int picker, then you need a click to close it, and one to open the string picker. So, the behavior is the same, and I assume, expected.
> 
> Anyway, I was not able to recreate the bug as described, in 4.3.0 / UWP.
> 
> [Issue7681.zip](https://github.com/xamarin/Xamarin.Forms/files/3760450/Issue7681.zip)

I also spend some time looking into this and I found that we internally call focus on an hidden Entry field.  So, I was wrong in above but what is still strange is that this focusing is only affecting UWP side.  No issue on Android or iOS.

**Comment by PureWeen** [comment]
@dinobu I tried to recreate this with your steps and wasn't able to.

It's been a while so I'm going to close this for now. 
If you can attach a repro then we can investigate and reopen
