### ISSUE TITLE
Uninstall app, pop-up description problem

### ISSUE THREAD

**Issue by wangyankun33** [xamarin/Xamarin.Forms#7687]
### Description
After I installed the app, when I pressed and unloaded, the popup window appeared and I wanted to remove the red part.
![1569461862(1)](https://user-images.githubusercontent.com/19883375/65653349-79aa1400-e047-11e9-973a-17ed0abf5fb1.png)

**Comment by StephaneDelcroix** [comment]
Sorry, I don't read Chinese (did I guessed right ?). This doesn't look like this is part of the Application, but a system-provided UI. You might be able to tweak that message by changing the android manifest.

As it doesn't look XF-related, I'm going to close this. You might have better chances by asking your question on, e.g., StackOverflow
