### ISSUE TITLE
[Bug] Flyout locked and missing hamburger menu icon

### ISSUE THREAD

**Issue by danlexo** [xamarin/Xamarin.Forms#7689]
### Description
Flyout gets locked after switching tabs in addition the hamburger menu is only shown for a split second
### Steps to Reproduce

1. Create new Shell project
2. Create 2 Content Pages, one with a list view that is populated from code-behind
3. Edit AppShell.xaml TabBar for the two pages and add single any page for the FlyoutItem
4. Start the app, drag out flyout from the corner to confirm it's there, tap on the second tab (for a split second the Hamburger menu icon appears), tap on the first tab and try to drag the flyout

### Expected Behavior
Hamburger icon to be shown,
Flyout to be shown when taping back and forwards on tabs

### Actual Behavior
See the attached gif
### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.815419 / 4.3.0.819712-pre2
- Last known good version: None
- IDE: Visual Studio 2019 16.3.1
- Platform Target Frameworks: 
  - Android: 8.1
- Affected Devices: Android Emulator / LG-250M

### Screenshots

![](https://i.imgur.com/omhhn28.gif)

**Comment by StephaneDelcroix** [comment]
please provide a reproduction project

**Comment by danlexo** [comment]
[reproduction project](https://github.com/danlexo/sandbox)

after starting a new project it seems most of my issues have been resolved 🤔

**Comment by robertsundstrom** [comment]
I have this problem in the latest version.

The hamburger icon is not visible at start. You can still swipe to open the menu.

I click into an item in the list.
Then, I click back, to go back to main list view.

The hamburger icon is shown.
