### ISSUE TITLE
[Bug] CollectionView selected index breaks when CollectionView has header

### ISSUE THREAD

**Issue by davidmclennan** [xamarin/Xamarin.Forms#7696]
### Description
A CollectionView with selection enabled and a header will offset the selection by 1. Pressing item 1 selects item 2. Pressing the last item crashes the app with **System.ArgumentOutOfRangeException:** 'Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index'

### Steps to Reproduce

1. Add CollectionView to ContentPage
2. Enable selection
3. Assign a header
4. Select items in the CollectionView

### Expected Behavior
Pressed item is selected item

### Actual Behavior
Selected item is item one past pressed item

### Basic Information

- Version with issue: XF 4.2.0.815419
- Last known good version: Don't know
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: Android: 9.0
- Android Support Library Version: 28.0.0.3
- Affected Devices: Android emulator, 9.0, x86

**Comment by samhouts** [comment]
@davidmclennan  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by davidmclennan** [comment]
@samhouts 
[CollectionViewRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3662153/CollectionViewRepro.zip)

**Comment by adrianknight89** [comment]
@davidmclennan I didn't see this issue on 4.4.0.1195-nightly. Can you confirm?

**Comment by jsuarezruiz** [comment]
@davidmclennan I can reproduce your problem on 4.2 but not in 4.3.
![issue7696](https://user-images.githubusercontent.com/6755973/66119368-cad27e80-e5d8-11e9-92d9-1caace78fb1d.gif)
[CollectionViewRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3685561/CollectionViewRepro.zip)
Could you test the attached sample?

**Comment by jsuarezruiz** [comment]
Tested and verified the issue.

**Comment by samhouts** [comment]
@davidmclennan  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
