### ISSUE TITLE
[Bug][iOS] CollectionView's rows start with wrong Height

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/Xamarin.Forms#7699]
### Description

When the rows of a CollectionView have different Heights, all rows with the same Height as the first one gets displayed wrong.

This should be somewhat simple to solve, as if the CollectionView is scrolled, all views get sized correctly.

Ok, this issue is a little weird, so I'm going to describe it better in the **Actual Behaviour**.

### Steps to Reproduce

1. Create a CollectionView.
2. Add different sized rows.
3. Add a row with the same size as the first one after other rows with different sizes.

### Expected Behavior

The size of all rows gets rendered correctly.

### Actual Behavior

1. The CollectionView has the two first rows with the same size (12), and they get displayed correctly.
2. Then there is a row with a different size (64), and it gets displayed correctly too.
3. Now, the fourth row goes back to the first's Height (12), but it gets displayed wrong.
4. Then there are two rows with different sizes (24 and 32) that get displayed correctly.
5. Finally, more 12pt sized rows that get displayed with the wrong size.

Going to the Second Page you can see that if there's a first row with a unique Height, the issue doesn't happen, as it only occurs in rows with the same size as the first one.

Observation: Changing the size of the third row in the MainPage also changes the sizes of all the 12pt sized rows after it.

### Basic Information

- Version with issue: Everyone (tested even with 4.4.0.1182-nightly)
- Last known good version: none (tested 4.1, 4.2, 4.3-pre2 and nightly)
- Platform Target Frameworks: 
  - iOS:  13.0

### Screenshots

**MainPage with issue:**
![MainPage with issue](https://user-images.githubusercontent.com/12024080/65706495-f85f7b00-e060-11e9-81d3-f3181c900ac2.png)

<br>

**MainPage after scroll:**

![MainPage after scroll](https://user-images.githubusercontent.com/12024080/65707275-96a01080-e062-11e9-92cc-a898f29214a3.png)

<br>

**SecondPage without issue (first row is unique):**

![SecondPage without issue (first row is unique)](https://user-images.githubusercontent.com/12024080/65706526-09a88780-e061-11e9-8bb8-caa40683c1cf.png)

### Reproduction Link

[CVIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3658848/CVIssue.zip)

**Comment by adrianknight89** [comment]
@luccasclezar When I click the Add button, the app crashes. Tested on XS with 4.4.0.1195-nightly. Can you confirm?

**Comment by luccasclezar** [comment]
@adrianknight89 I tested with 4.4.0.1195-nightly and it's still happening. The Add button doesn't crash the app for me, but the issue is not related to it. When you open the app it should display as the first screenshot I attached (with all 12 sized rows bigger than they should be).

The add button is meant for another issue I was testing that renders the CollectionView on the second tab invisible when changed before displaying the tab (sorry for keeping the button there).

I tested the repro project only on an iPhone 11 Pro Max simulator but I saw the issue for the first time on an physical iPhone 8 Plus.

**Comment by luccasclezar** [comment]
To confirm, I tested out on an iPhone 8 Plus running iOS 13.1. As you can see, the issue still occurs.

![IMG_CB64BCAA91D0-1](https://user-images.githubusercontent.com/12024080/65820034-a6525d00-e1fa-11e9-8c9b-389c054d1716.jpeg)

**Comment by adrianknight89** [comment]
@luccasclezar I think this may only be an iOS 13 issue. I tested this on iOS 12.4.1 with an XR device. No issues there.

**Comment by luccasclezar** [comment]
@adrianknight89 I can’t test right now on an iOS 12 device, so I can’t say for sure, but yeah, probably an iOS 13 issue.

I don’t know about the Add button crash though, it doesn’t happen on iOS 13. Maybe it’s related to #7700 but instead of failing silently and not rendering the CollectionView, it crashes on iOS 12.

**Comment by luccasclezar** [comment]
@adrianknight89 I tested on a iOS 12 simulator now and I can confirm it, there's no issue on the rows' sizes and the app crashes when Add is pressed.

**Comment by PureWeen** [comment]
I saw the crash when testing this one
https://github.com/xamarin/Xamarin.Forms/issues/7700

So these might all get fixed together

**Comment by AntonIOIOIO** [comment]
Has this been fixed? we cant move to collectionview because of this @samhouts

**Comment by samhouts** [comment]
@AntonIOIOIO Unfortunately, I still see this issue in 4.5.0.

**Comment by robertmiles3** [comment]
Putting my voice here as well. I tried to modernize and move to CollectionView instead of ListView, but this one is a big blocker.

**Comment by liveinvarun** [comment]
issue still exists in the latest version of forms @samhouts

**Comment by Russc0** [comment]
Still happening in latest Forms. Some rows start wrong height and then correct themselves as you scroll the list.

**Comment by WestVillageIdiot** [comment]
I'm having the same problem, using iOS 14.

**Comment by hartez** [comment]
This has been fixed in 5.0.0.193. 

(The actual fix may have been in the last release of 4.8.0, but I haven't tested that.)
