### ISSUE TITLE
[Bug][iOS] If CollectionView in other Tab gets changed before it's displayed, it stays invisible

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/Xamarin.Forms#7700]
### Description

As the title says, if you have a CollectionView in some other Tab (in a TabbedPage, of course), and change it (add or remove something) before displaying the page, the CollectionView doesn't get rendered when the page is displayed.

### Steps to Reproduce

1. Create a TabbedPage
2. Add a CollectionView to the second tab
3. Change the CollectionView from a Button on the first tab (add or remove an item from the ItemSource).
4. Go to the second tab.

<br>

On the repro project:

1. Launch
2. Click "Add"
3. Change to second tab.

### Expected Behavior

The CollectionView appears with the modifications made on the first tab.

### Actual Behavior

The CollectionView gets modified but it doesn't get rendered when the tab is displayed.

### Basic Information

- Version with issue: Everyone (including 4.4.0.1182-nightly)
- Last known good version: None
- Platform Target Frameworks: 
  - iOS: 13.0

### Screenshots

**Second tab if changed before being displayed:**

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-26 at 13 44 14](https://user-images.githubusercontent.com/12024080/65707904-d3203c00-e063-11e9-98c9-80bcbe7b321b.png)

<br>

**Second tab if displayed before being changed:**

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-26 at 13 44 45](https://user-images.githubusercontent.com/12024080/65707922-db787700-e063-11e9-833a-000b7adf52b1.png)

### Reproduction Link

[CVIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3658940/CVIssue.zip)

**Comment by hartez** [comment]
Fails to render on iOS 13, full-out crashes on 12 and lower.
