### ISSUE TITLE
[Bug] iOS Large SetPrefersLargeTitles(true) Uses Incorrect BarBackgroundColor

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#7701]
### Description

When using `NavigationPage.On<iOS>().SetPrefersLargeTitles(true)`, the incorrect `BarBackgroundColor` is displayed.

### Steps to Reproduce

Reproduction Sample: https://github.com/brminnick/iOSLargeTitleRepro

1. Download the [reproduction sample](https://github.com/brminnick/iOSLargeTitleRepro)
2. Open `iOSLargeTitleRepro.sln` 
3. Build/deploy to device/simulator running iOS 13

### Expected Behavior

The `NavigationPage.BarBackgroundColor` should be `Color.Green` (as set in `App.cs`).

Note that when the page is scrolled, and the Navigation Bar is reduced, the correct color is displayed.

### Actual Behavior

The `NavigationPage.BarBackgroundColor` is the default color.

Note that when the page is scrolled, and the Navigation Bar is reduced, the correct color is displayed.

### Basic Information

- Version with issue: I tested from v4.3.0.819712-pre2 back to Xamarin.Forms v3.5.0.274416 and confirmed the same issue persists (My hunch is that this is a breaking change introduced in iOS 13)
- Last known good version: None (My hunch is that this is a breaking change introduced in iOS 13)
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS v13.2.0.42

### Screenshots

![](https://user-images.githubusercontent.com/13558917/65711206-449ec100-e049-11e9-9ea8-7eecedff7d62.gif)

### Reproduction Link

https://github.com/brminnick/iOSLargeTitleRepro

**Comment by landrzz** [comment]
Possibly related to #7350

**Comment by brminnick** [comment]
I confirmed this workaround resolves the problem, as recommended here: https://github.com/xamarin/Xamarin.Forms/issues/7350#issuecomment-535905289

```csharp
using MyNamespace.iOS;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ExportRenderer(typeof(NavigationPage), typeof(LargeTitleNavigationRenderer))]
namespace MyNamespace.iOS
{
    public class LargeTitleNavigationRenderer : NavigationRenderer
    {
        public override void ViewWillAppear(bool animated)
        {
            base.ViewWillAppear(animated);

            var navigationPage = (NavigationPage)Element;
            var navigationPageBackgroundColor = navigationPage.BarBackgroundColor;

            NavigationBar.StandardAppearance.BackgroundColor = navigationPageBackgroundColor == Color.Default
                ? UINavigationBar.Appearance.BarTintColor
                : navigationPageBackgroundColor.ToUIColor();

            NavigationBar.StandardAppearance.TitleTextAttributes = NavigationBar.TitleTextAttributes;
            NavigationBar.StandardAppearance.LargeTitleTextAttributes = NavigationBar.LargeTitleTextAttributes;

            NavigationBar.ScrollEdgeAppearance = NavigationBar.StandardAppearance;
        }
    }
}
```
