### ISSUE TITLE
Shell possible memory leak

### ISSUE THREAD

**Issue by DaveEnar** [xamarin/Xamarin.Forms#7703]
### Description
Using Shell, whenever I navigate from a tab to a details page (that is registered to Shell Routes or using  Navigation.PushAsync), a new instance of that page is created. But, when I leave this page the finalizer is never called, it seems to be held in memory forever. This page is an empty ContentPage, I set Content = null after popping, and I even used a GC.Collect(1, GCCollectionMode.Forced, false), but nothing.

### Steps to Reproduce

1. Create a XF Shell application using VS 2019 Shell template
2. Add a finalizer to ItemDetailPage
3. Navigate to various Items

### Expected Behavior
The page that is pushed in stack should be disposed after popped.
### Actual Behavior
Finalizer is never called
### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: -
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  -
  - Android: 9.0

**Comment by samhouts** [comment]
@DaveEnar  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by DaveEnar** [comment]
[TestShell.zip](https://github.com/xamarin/Xamarin.Forms/files/3660167/TestShell.zip)

**Comment by PureWeen** [comment]
@DaveEnar So I think you have to be sure to trigger the GC once everything in the shell has resolved

As a test I modified your ItemDetailPage to do this to just be super sure everything connected to the page has been disposed and for me the finalizer gets called

That being said we also have some large efforts being put forward to help some clean up scenarios

https://github.com/xamarin/Xamarin.Forms/pull/7768

```C#
protected override void OnDisappearing()
        {
            base.OnDisappearing();

            BindingContext = null;
            Content = null;
            viewModel = null;

            Device.BeginInvokeOnMainThread(async () =>
            {
                await Task.Delay(2000);
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();

            });
        }

        ~ItemDetailPage()
        {
            var x = 1;
        }
```
