### ISSUE TITLE
[Enhancement] Expose text property for more button on bottom tab navigation and Shell

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7708]
## Summary
The more button on the bottom tab bar isn't currently configurable. We should expose a text property to make the text settable.

This property should be exposed on the Shell as well as a platform specific property on android.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
