### ISSUE TITLE
[Bug] On android, not showing keyboard when changing placeholder in entry focused event

### ISSUE THREAD

**Issue by erdugen** [xamarin/Xamarin.Forms#7709]
### Description
On Android, the keyboard does not appear when I change the PlaceHolder property of a in entry's focusing event. 
### Steps to Reproduce

Entry x:Name="entTest" Placeholder="blabla" Focused="focus_event" 

public void focus_event(object sender, FocusRequestArgs arg)
{
   entTest.Placeholder = null;
}
### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.815419
- Last known good version:
- IDE: VS for Mac 8.3
- Platform Target Frameworks: Android 10.0
- Android:
    Min      :  Andoid 5.0 api level 21
     Target : Android 10.0 api levelt 29

**Comment by samhouts** [comment]
@erdugen  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by erdugen** [comment]
[Issue7709.zip](https://github.com/xamarin/Xamarin.Forms/files/3669319/Issue7709.zip)
Click the test1 field first. You will see the keyboard appear on the screen. Then click on an empty area to hide the keyboard. Then click the test2 field. You will notice that the text field has focus but the keyboard does not appear on the screen. You will see that it works correctly when you click or focus with the button. I have multiple entries in my application and my android users have to click twice.

**Comment by PureWeen** [comment]
Probably related
https://github.com/xamarin/Xamarin.Forms/issues/2094
