### ISSUE TITLE
[Bug][iOS] Xaminals CollectionView items overlap on iOS

### ISSUE THREAD

**Issue by LamijaV** [xamarin/Xamarin.Forms#7714]
### Description
CollectionView on iPhone overlaps items after navigating to About page. It happens every time on iOS, never on Android. I tried removing the about page content and codebehing but issue persists. Also, the selection (highlight) remains on last selected item, even tho I navigate trough the app. I attached the screenshots.
### Steps to Reproduce

1. Open Xaminals sample
2. Go to About page
3. Return to any page with animals, all CollectionView items from the first tab and that shell are overlapped in the first row. The list of items is also visible and scrollable in the behind.

### Expected Behavior
For all items to be visible.
### Actual Behavior
All items visible in the background but also stacked in the first row over first item. Also, for last selected item not to be highlighted every time i navigate to the page with CollectionView.
### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.709249, Mono 4.13.12-pre, Xamarin.iOS 12.4.0.64
- Last known good version:   @#N/A
- IDE: VS Professional, 15.9.16
- Platform Target Frameworks: 
  - iOS:   SDK 12.2 (XCode 10.2)

- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/50732501/65770168-c9670900-e135-11e9-93a7-5685244f832a.png)
![image](https://user-images.githubusercontent.com/50732501/65770186-d4ba3480-e135-11e9-8b48-c4a0d8484098.png)
![image](https://user-images.githubusercontent.com/50732501/65770199-da177f00-e135-11e9-9e11-925926193010.png)

### Reproduction Link

Sample from:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/

**Comment by jsuarezruiz** [comment]
It seems to be the same as: https://github.com/xamarin/Xamarin.Forms/projects/46

**Comment by adrianknight89** [comment]
@jsuarezruiz I agree. This seems to be a duplicate.

**Comment by codemillmatt** [comment]
Also affecting `CarouselView` (which makes sense). 😄  I've only noticed it happening when navigating by the `Shell` flyout. Regular pushing onto the nav stack & then popping off does not cause it - even if reloading the `ItemsSource`. (xam.ios 13.8.1.1)

**Comment by jsuarezruiz** [comment]
The fix should be in the Nightly package and the fix was made in this PR: https://github.com/xamarin/Xamarin.Forms/pull/8189

**Comment by thisismyself** [comment]
@jsuarezruiz Thank you for this fix. Testing 4.4.0.991210-pre2 right now, at least in Simulator it works as expected (no access to physical device at the moment).

**Comment by samhouts** [comment]
closed by #8189
