### ISSUE TITLE
[Bug][Android] ScrollView.ScrollTo Entry scrolles it out of view

### ISSUE THREAD

**Issue by Basti82b** [xamarin/Xamarin.Forms#7715]
### Description

When I use ScrollView.ScrollTo with an Entry like following, it scrolles too far to top so that the Entry is out of view. Maybe that happens because the keyboard opens at the same time.

`ScrollView.ScrollToAsync(Entry, ScrollToPosition.Start, true);`

**Comment by samhouts** [comment]
@Basti82b Please use the entire issue template to report problems.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@Basti82b  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
