### ISSUE TITLE
[Bug] Unable to change Shell hamburher menu color (it is white always) on Android

### ISSUE THREAD

**Issue by IgorKravchenko10** [xamarin/Xamarin.Forms#7716]
### Steps to Reproduce

1. Update Xamarin.Forms to 4.2.0.709249 or higher.
2. Change Shell.ForegroundColor to another color instead of white and run project on **Android**.

### Expected Behavior
Hamburher menu color change with Shell.ForegroundColor.
### Actual Behavior
Hamburher menu color doesn't change with Shell.ForegroundColor from XF 4.2.0.709249.
### Basic Information

- Version with issue: 4.2.0.709249 or higher
- Last known good version: 4.1.0.778454
- IDE: VS 2019
- Platform Target Frameworks:
  - Android: 9 
- Nuget Packages: Xamarin.Forms 4.2.0.709249
- Affected Devices: Samsung Galaxy s8+ (android 9), Samsung A7 2016 (android 7).
- Screenshots:
[Photos.zip](https://github.com/xamarin/Xamarin.Forms/files/3662983/Photos.zip)
- Xaminals project where this bug was reproduced: 
[Animals.zip](https://github.com/xamarin/Xamarin.Forms/files/3663005/Animals.zip)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/7577
