### ISSUE TITLE
[Bug] [Android] CarouselView crashes when items cleared

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#7717]
# Description

CarouselView crashes when clearing the items. Looks like an issue in GetItemForPosition().

### Steps to Reproduce

1. Control Gallery, navigate to CarouselView Gallery -> CarouselView (Items)
2. Tap "Clear Items"

### Expected Behavior

Items cleared

### Actual Behavior

Crash

**Comment by techduggu** [comment]
@hartez I'm not able to reproduce it with latest Xamarin.Forms (master branch). On tap of "Clear Items", it clears the items and display an empty view.

![image](https://user-images.githubusercontent.com/17450941/67457592-bae71100-f651-11e9-8eea-be227c209e2b.png)

**Comment by rmarinho** [comment]
This is fixed on 4.4 stable .
