### ISSUE TITLE
[Bug] MasterDetailPage Hamburger Menu is cut off

### ISSUE THREAD

**Issue by schovan** [xamarin/Xamarin.Forms#7719]
### Description
Hamburger Menu is cut off

### Steps to Reproduce

1. Create new Mobile app (Xamarin.Forms)
2. Select Master - Detail Template and check Windows (UWP)
3. Build and Run UWP project

### Expected Behavior
Hamburger menu shouldn't be cut off

### Actual Behavior
Hamburger menu is cut off

### Basic Information

- Version with issue:
xamarin.forms 4.2.0.709249
- Last known good version:
xamarin.forms 4.1
- IDE:
vs2019
- Platform Target Frameworks: 
  - UWP:  18362

### Screenshots
![image](https://user-images.githubusercontent.com/16373322/65792007-288f4280-e163-11e9-8f00-8fab2361d868.png)

**Comment by charlesroddie** [comment]
Also getting this. I believe it has to do with UWP 18362. @FoggyFinder @Happypig375

**Comment by FoggyFinder** [comment]
UWP 17763 has the same issue.

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/5661

we set the SDK back to 16299 in the latest release which should fix this for now
