### ISSUE TITLE
Xamarin Forms App Crash

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#7721]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/745313/xamarin-forms-app-crash.html)._

---
Basic X.F. project crashing on startup during debugging of an Android app on the device.  Tested on Xamarin.Forms v 4.2 and 4.3 pre-release.

---
#### Visual Studio Feedback System on 9/25/2019, 03:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
