### ISSUE TITLE
[Bug] VS2019 does not show expected Xamarin controls in toolbox

### ISSUE THREAD

**Issue by TonyGravagno** [xamarin/Xamarin.Forms#7726]
### Description
It looks to me like there are Xamarin Forms controls missing from the VS2019 toolbox.

### Steps to Reproduce

1. Create a new Android project. 
2. Open content_main.xml (the toolbox should load somewhere in here)
3. Note some widgets are missing.
4. Close/restart solution and VS in attempt to refresh.

I have not deleted toolbox files or taken any other special steps to refresh/reset.
Checked "toolbox>choose items", there didn't seem to be any assemblies that should contain the missing conrols. I don't know if we're supposed to load toolbox items manually through choose-items, browsing to a file.

### Expected Behavior
I believe we should see the TableView, ActivityIndicator, and other controls documented in [Xamarin.Forms.toolbox.xml](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core.Design/toolbox/Xamarin.Forms.toolbox.xml)
### Actual Behavior
Toolbox shows "Form Widgets", not "Controls", no "Cells" category, and a subset of expected views.
### Basic Information

- Version with issue: Forms 4.2.0.815419
- Last known good version: Unknown
- IDE: VS2019 16.3.1
- Platform Target Frameworks:
  - Android:  9
- Android Support Library Version: 28.0.0.3
- Nuget Packages: (all v28.0.0.3, mostly added in attempt to find controls)
  - Xamarin.Android.Support.Design
  - Xamarin.Android.Support.v13
  - Xamarin.Essentials
  - Xamarin.Forms

### Screenshots
Product Versions:
![image](https://user-images.githubusercontent.com/499473/65810423-2cb96100-e15f-11e9-92fa-240ecffd16bd.png)
![image](https://user-images.githubusercontent.com/499473/65810600-29bf7000-e161-11e9-93e6-ae3ef746be13.png)
Available controls and layouts:
![image](https://user-images.githubusercontent.com/499473/65810447-6d18df00-e15f-11e9-854b-91d0579348fb.png)
![image](https://user-images.githubusercontent.com/499473/65810453-7efa8200-e15f-11e9-953a-6affcefe42bc.png)
Screenshot from [demo video](https://devblogs.microsoft.com/xamarin/using-new-xamarin-forms-controls-toolbox/) with expected controls:
![image](https://user-images.githubusercontent.com/499473/65810526-1e1f7980-e160-11e9-855b-eb0c6ff129ca.png)

**Comment by PureWeen** [comment]
@TonyGravagno can you send me the project you're creating? I'm not quite following your steps. From the sound of it you are creating a native xamarin android project not a Forms project

Looking at your screen shot those are all controls that map to Android controls not to Xamarin Forms controls

Can you try creating a cross platform Xamarin.Forms project? That should have the correct toolbox for you
