### ISSUE TITLE
[Enhancement] Match all the current TabPage style features into shell

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7730]
## Summary
Currently the tabs on Shell can't be styled as well as a TabPage. We need to add the ability to tint each tabs selected and unselected color.

## Implementation Details
Wait to implement until we discuss the best option. This might be implemented as part of a more customized custom control.  

If we end up just styling the native TabBar then make sure to reuse the tinting code that's part of the TabPageRenderer on each platform

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
