### ISSUE TITLE
[Bug] Corrputed apk Reported by Google Play Appeals

### ISSUE THREAD

**Issue by koosha72** [xamarin/Xamarin.Forms#7732]
### Description
As I updated to Visual Studio version 16.3.1 from 16.2 my release apk is marked as corrupted by google play protect appeals! I cannot send my app to google play protect appeals so there is a warning about unrecognized developer. 
### Steps to Reproduce

1. Create an Archive
2. Sign it
3. Send the resulting apk to Google Play Protect Appeals

### Expected Behavior
Google Play Protect Appeals reviews the application
### Actual Behavior
Google Play Protect Appeals says that the file is not an apk or it is corrupted
### Basic Information
I don't know if the problem is with xamarin or visual studio.
the application actually works on all devices without any problem. The only problem is Google Play Protect
- Version with issue:
- Last known good version:
- IDE: Visual Studio 16.3.1

**Comment by samhouts** [comment]
@koosha72 Please report this issue via Visual Studio. Thanks! https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019
