### ISSUE TITLE
[Bug] ListView.ItemTapped not working in UWP

### ISSUE THREAD

**Issue by greendimka** [xamarin/Xamarin.Forms#7734]
### Steps to Reproduce

1. Create an Xamarin.Forms project for UWP.
2. Add a ListView to a XAML page, bind it to some data.
3. Add event handler to ListView. (example: ItemTapped="lst_ItemTapped")
4. Run app and check the Xamarin.Forms.ItemTappedEventArgs, passed into event handler.
5. Item property of args object is null, but must be a tapped object.

### Expected Behavior
Item property of Xamarin.Forms.ItemTappedEventArgs points to a tapped object.
ItemIndex must be the same as the index of the tapped item.

### Actual Behavior
Item property of Xamarin.Forms.ItemTappedEventArgs is null
ItemIndex is -1

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: unknown
- IDE: VS2019 Community 16.3.1
- Platform Target Frameworks: 
  - UWP:  10.0.18362.0 
- Nuget Packages:
  - Microsoft.NETCore.UniversalWindowsPlatform 6.2.9
  - Xamarin.Forms 4.2.0.815419
  - Xamarin.Essentials 1.3.1 (probably not related)
- Affected Devices: Local machine

**Comment by greendimka** [comment]
Some investigations:
- If I fill ListView in ctor, that is: before view is activated - ItemTapped event works as expected.
- If I add items later (after view is active) - ItemTapped fails.

In short - items added to ListView after view has been activated - do not work as expected when tapped

**Comment by PureWeen** [comment]
@greendimka can you attach a repro? I'm not having the best of luck reproducing

**Comment by greendimka** [comment]
Sure, I will prepare it soon.

**Comment by greendimka** [comment]
Sorry, my mistake. I have created pure app, which would bind a ListView to an ObservableCollection.
And it does work as expected. Every time I add a new item and tap it - I receive an event with correct payload. So I also cannot reproduce it now.
I was sure it was related to UWP (since everything works in my production project on Android), but looks like UWP has nothing to do with it.

Sorry for wasting your time. I will test better next time. Thank you for your work! :)

**Comment by PureWeen** [comment]
@greendimka great to hear!! Thank you for getting back to me so quickly

**Comment by PureWeen** [comment]
This might possibly be an issue you're running into

https://github.com/xamarin/Xamarin.Forms/issues/5465
