### ISSUE TITLE
[Enhancement] TabBar button does not take me home

### ISSUE THREAD

**Issue by Elashi** [xamarin/Xamarin.Forms#7736]
### Description
The bottom TabBar button behaves differently on different platforms.  In iOS , if I click on the button the second time, it navigates back to the home page associated with the TabBar.  But, in Android, if I click on it the second time , it does not go anywhere.

The bug: iOS and Android should behave the same.  And I think iOS has the correct behavior.   
The feature: I wish there is some property to specify the preferred behavior of the second click of TabBar buttons.

### Steps to Reproduce
1. Just create any Xamarin Shell project
2. Click on "Browse", it will take you to a page that lists all available items.
3. Click any item in the list to navigate to it
4. Then click on "Browse" again.

### Expected Behavior
I expect it to go back to the main list of items that first appeared when I clicked on the TabBar button (i.e. Home of a TabBar button) (this is how it works in iOS) 

### Actual Behavior
In Android , the second click does not go anywhere.

### Basic Information

- Version with issue: 4.2
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13
  - Android: API 28
- Android Support Library Version:
- Nuget Packages: 28.0.0.1
- Affected Devices: Android

### Screenshots
The screenshot shows how it does not work on Android.  I will provide a recording for iOS if necessary.
![TabBarButton-android](https://user-images.githubusercontent.com/12378171/65835987-c31f8b00-e2f5-11e9-9aae-b94803c3ee4c.gif)

**Comment by PureWeen** [comment]
@Elashi This behavior is specific to the iOS TabBar and how it interacts with a UINavigationController so it's not something we would just copy over to Android.

The option here would be to add an API to the TabBar so that you could set this behavior and it would act like this on other platforms as well

I'm going to set this as an enhancement for now

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
