### ISSUE TITLE
[Enhancement] Shell ignores ToolbarItems from TabbedPage subpages

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#7739]
### Description

cf https://github.com/xamarin/Xamarin.Forms/issues/6127#issuecomment-536082200

In short, Shell does not discover and promote ToolbarItems from pages contained within a TabbedPage.

### Steps to Reproduce

1. Set up a shell
2. Set up a tabbed page with sub-pages
3. Add ToolbarItems to the sub-pages
4. Observe they don't show up in the shell

### Expected Behavior

TabbedPages should continue to work as they did in the past. Maybe.

### Actual Behavior

ToolbarItems are ignored.

### Basic Information

- Version with issue: 4.2.0.815419
- Last known good version: None
- IDE: VS
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

### Reproduction Link

Repro available on demand, but it's pretty easy to set up and verify.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
