### ISSUE TITLE
[Bug] Changing the ItemTemplate on CarouselView dynamically doesn't work

### ISSUE THREAD

**Issue by jsuarezruiz** [xamarin/Xamarin.Forms#7742]
### Description

If you change the ItemTemplate (programmatically) for a CollectionView, the template is not applied. 

### Steps to Reproduce

1. Open Xamarin.Forms Core Gallery.
2. Navigate to the Issue 7395.
3. Press a button to change programmatically the ItemTemplate.

### Expected Behavior
The CollectionView refresh every item with the new ItemTemplate.

### Actual Behavior
Nothing happens.

### Basic Information

- Version with issue: 4.3.0.819712-pre2
- Platform Target Frameworks: 
  - iOS

### Screenshots

![issue-template-cv-ios](https://user-images.githubusercontent.com/6755973/65859407-627d6600-e368-11e9-9852-c4ad55be0667.gif)

**Comment by samhouts** [comment]
closed by #7743
