### ISSUE TITLE
[Bug] iOS page background color is ignored when set in style.

### ISSUE THREAD

**Issue by greendimka** [xamarin/Xamarin.Forms#7745]
### Description
If page background color is set in style for TargetType="Page" then background color is ignored.
If page background color is set as a property of page - everything works fine.

### Steps to Reproduce

1. Create Xamarin.Forms app for iOS (add Android if you want to compare)
2. Create a style in App.xaml for page:
		&lt;Style TargetType="Page"&gt;
                &lt;Setter Property="BackgroundColor" Value="Orange" /&gt;
		&lt;/Style&gt;
3. Launch app on iPhone - page background color is white.

### Expected Behavior
Page background color should be the same as defined in style.

### Actual Behavior
Page background stays white.

### Basic Information

- Version with issue: 
- Last known good version: unknown
- IDE: VS Community 16.3.1
- Platform Target Frameworks: 
  - iOS:  13.0
- Nuget Packages: Xamarin.Forms 4.2.0.815419

**Comment by PureWeen** [comment]
@greendimka If you set *ApplyToDerivedTypes* to true

```XAML
<Style TargetType="Page" ApplyToDerivedTypes="True">
            <Setter Property="BackgroundColor" Value="Orange" />
        </Style>
```

Does that work?

I tested locally with this inside App.xaml and it worked for me
```xaml
 <Application.Resources>
        <Style TargetType="Page" ApplyToDerivedTypes="True">
            <Setter Property="BackgroundColor" Value="Orange" />
        </Style>
    </Application.Resources>
```
