### ISSUE TITLE
[Bug][Android] custom view with gradient takes full layout size in Xamarin.Forms

### ISSUE THREAD

**Issue by sheiksyedm** [xamarin/Xamarin.Forms#7748]
### Description
We've created a custom view renderer that overrides ViewRenderer and draws gradient paint. Used this custom view in Xamarin. Forms with the HeightRequest and WidthRequest settings. But it occupies complete size, regardless of the size indicated. But when draw the normal rect with solid color it will work properly. 

### Code 

```C#
[assembly: Xamarin.Forms.ExportRenderer(typeof(CustomView), typeof(Test_Xamarin.Droid.CustomViewRenderer))]
namespace Test_Xamarin.Droid
{
public class CustomViewRenderer : ViewRenderer
    {
        public CustomViewRenderer(Context context) : base(context)
        {
            this.SetWillNotDraw(false);
        }
        protected override void OnDraw(Canvas canvas)
        {
            var paint = new Android.Graphics.Paint();

            // Draw gradient paint 
            LinearGradient gradient = new LinearGradient(0, 0, this.Width, this.Height, Android.Graphics.Color.Red, Android.Graphics.Color.Green, Shader.TileMode.Clamp);
            paint.SetShader(gradient);
            canvas.DrawPaint(paint);

            // Draw solid color paint 
            //paint.Color = Android.Graphics.Color.Red;
            //canvas.DrawRect(new Rect(0, 0, this.Width, this.Height), paint);
            base.OnDraw(canvas);
        }
    }
}
```
### Xaml code 
```XAML
<Grid>
        <local:CustomView HeightRequest="200" WidthRequest="200" HorizontalOptions="Center" VerticalOptions="Center"  />
    </Grid>
```

### Expected Behavior

View should be render within specified size in layout. 

### Actual Behavior

View takes full size of layout. 

### Basic Information

- Xamarin.Forms Version : 4.2.0.709249 
- IDE: VS 2019 Enterprise version 16.3.1  
- Android: Android 9.0 (Pie)
- Android Support Library Version: 28.0.0.1
- Nuget Packages:
- Affected Devices: Samsung S8 plus

### Screenshots
![image](https://user-images.githubusercontent.com/23059975/65885976-245c6280-e3b9-11e9-875e-765aea3859b2.png)
![image](https://user-images.githubusercontent.com/23059975/65886020-35a56f00-e3b9-11e9-800a-e7ec38a70166.png)

### Reproduction Link

[Test_Sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/Test_Xamarin-1613472113)

**Comment by DoubleDBE** [comment]
I can confirm this, since Android Pie this issue occurs when using LinearGradient. A workaround is using GradientDrawable which works, but limits control over the start and endline of the gradient.

**Comment by PureWeen** [comment]
duplicate
https://github.com/xamarin/Xamarin.Forms/issues/3912

Though I don't feel like this is a XF issue.

If the way a *LinearGradient* gets drawn changed from api 27 to api 28 that's not a XF thing that's an android thing

That being said if you clipthebounds
```
 protected override void OnDraw(Canvas canvas)
        {
            this.ClipBounds = new Rect(0, 0, Width, Height);
```

It clips the drawing 

Or if you have the CustomView inherit from a layout (grid or stacklayout) then set IsClipToBounds on the layout it'll also clip it
