### ISSUE TITLE
TitleView's Background Color

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7754]
Hi,

Please add BackgroundColor to the TitleView for easy styling instead of forcing a stacklayout or grid if it's just a simple label or image to be placed in the TitleView

Thanks,
Jassim

**Comment by almirvuk** [comment]
I would be happy to implement and help with this one, but not sure where to start, as I can see the `TitleViewProperty` is an attached property of type `View `on the `NavigationPage`, is there any similar example of adding the new property on the attached property?

**Comment by pictos** [comment]
@almirvuk, are you thinking to set a `View.BackgroundColor` property using an Attached property?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
