### ISSUE TITLE
[Bug] CollectionView -> RemainingItemsThresholdReachedCommand freezes UI

### ISSUE THREAD

**Issue by SunnyMukherjee** [xamarin/Xamarin.Forms#7756]
### Description

I am attempting to use the Vertical CollectionView in place of the ListView and load data incrementally when the user scrolls to the last item because the ListView still has other unresolved issues.  I am following the guide in the link below:

[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/populate-data#load-data-incrementally](url)

However, the RemainingItemsThresholdReachedCommand is not working.  When using the new CollectionView in Vertical Orientation with the RemainingItemsThresholdReachedCommand bound to a command in a ViewModel class with RemainingItemsThreshold set to 0 and the user scrolls to the last item, the UI freezes in both Android and iOS.  I have tried to get it working even with the RemainingItemsThresholdReached property, but that does not work either.

I have attached a zip file with a test project to reproduce the issue.  This issue is present in both the stable release (4.2.0.815419) and the latest preview release (4.3.0.819712-pre2).  I have left the code to use the LinearItemsLayout in the CollectionView ItemsLayout in the preview version.

### Steps to Reproduce

1. Use the following example CollectionView in your XAML.

`<StackLayout>
        <CollectionView
            ItemSizingStrategy="MeasureAllItems"
            ItemsSource="{Binding Path=ListItems, Mode=TwoWay}"
            RemainingItemsThreshold="0"
            RemainingItemsThresholdReachedCommand="{Binding Path=RemainingItemsReachedCommand}"
            VerticalOptions="StartAndExpand">
            <CollectionView.ItemsLayout>
                <LinearItemsLayout ItemSpacing="2" Orientation="Vertical" />
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label
                        FontSize="Large"
                        HorizontalOptions="StartAndExpand"
                        Text="{Binding Path=.}" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </StackLayout>`

2. Set the following command in the ViewModel class to add items to the ObservableCollection.

`
private Command _remainingItemsReachedCommand;

        public Command RemainingItemsReachedCommand
        {
            get
            {
                return (_remainingItemsReachedCommand) ??
                    (
                        _remainingItemsReachedCommand = new Command
                        (
                            () =>
                            {
                                for(int x = ListItems.Count; x < ListItems.Count + 50; x++)
                                {
                                    ListItems.Add(x.ToString());
                                }
                            }
                        )
                    );
            }
        }

`

3. Run the project in either Android or iOS.

### Expected Behavior

I expect to see the new items that are loaded incrementally.

### Actual Behavior

UI freezes in both platforms.

### Basic Information

- Version with issue: Latest stable release (4.2.0.815419) and the latest preview release (4.3.0.819712-pre2)
- Last known good version: Unknown
- IDE: Visual Studio 2019 16.3.0
- Platform Target Frameworks: 
  - iOS:  
13.0
  - Android:  
9.0 and SDK Platform 28
  - UWP:   
Untested
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms, Xamarin.Essentials
- Affected Devices:

I have only tested this on the simulator and not an actual device.

Nexus5X
iPhone 11

### Reproduction Link

[TestXamarinForms_RemainingItems.zip](https://github.com/xamarin/Xamarin.Forms/files/3674130/TestXamarinForms_RemainingItems.zip)

**Comment by adrianknight89** [comment]
@SunnyMukherjee Please read the comments starting from https://github.com/xamarin/Xamarin.Forms/issues/3172#issuecomment-531923893.

**Comment by SunnyMukherjee** [comment]
Thanks for the pointing me to the separate discussion thread.

However, I was not able to get it to work.  I implemented the following changes below based on your and others' suggestions in the thread:

- Added SemaphoreSlim object to restrict access to only 1 thread at a time
- Added _isAdding boolean to restrict access in the RemainingItemsThresholdReachedCommand
- Added Try-Finally clause to release the SemaphoreSlim object and set the _isAdding boolean to false
- Added underlying ObservableRangeCollection
- Invoked the addition of new items on the UI thread

```
_remainingItemsReachedCommand = new Command
                        (
                            async () =>
                            {
                                if (!_isAdding)
                                {
                                    await _semaphoreSlim.WaitAsync();

                                    try
                                    {
                                        _isAdding = true;

                                        Device.BeginInvokeOnMainThread
                                        (
                                            () =>
                                            {
                                                for (int x = ListItems.Count; x < ListItems.Count + 50; x++)
                                                {
                                                    ListItems.Add(x.ToString());
                                                }
                                            }
                                        );
                                    }
                                    catch (Exception exception)
                                    {
                                        Debug.WriteLine(exception.Message);
                                    }
                                    finally
                                    {
                                        _semaphoreSlim.Release();
                                        _isAdding = false;
                                    }
                                }                                
                            }
                        )
```

The UI still freezes on both iOS and Android.  However, I am not seeing the endless loop in the Output window, so I know the semaphore is working.  I have attached the new code if anyone wants to reproduce it or try to fix it.

[TestXamarinForms_RemainingItems.zip](https://github.com/xamarin/Xamarin.Forms/files/3679120/TestXamarinForms_RemainingItems.zip)

**Comment by adrianknight89** [comment]
@SunnyMukherjee You're freezing your UI because of the for loop.

```
for (int x = ListItems.Count; x < ListItems.Count + 50; x++)
 {
        ListItems.Add(x.ToString());
}
```

You're not caching `ListItems.Count` in a local variable before the loop. The loop keeps increasing the list count as you add new items and never terminates.

Try this:

```
var count = ListItems.Count;
for (int x = count; x < count + 50; x++)
{
          ListItems.Add(x.ToString());
}
```

If this resolves your issue, please close the ticket. Tested on 4.4.0.1203-nightly.

@jsuarezruiz I don't know who is responsible for updating documentation, but it'd be great if the documentation on `RemainingItemsThreshold` included the work that needs to happen around locking. See this example and the discussion on https://github.com/xamarin/Xamarin.Forms/issues/3172#issuecomment-531923893.

**Comment by SunnyMukherjee** [comment]
@adrianknight89 Thanks for spotting that bug.  I guess that's what happens with late-night coding.  :)  I appreciate your help.  It resolved the issue for both iOS and Android on both the PreRelease and Stable versions.  I'll close the ticket.

@jsuarezruiz Yes, it would be helpful to document the locking logic for one thread to add to the CollectionView when triggering the RemainingItemsThresholdReached.
