### ISSUE TITLE
[iOS] EmptyView is not rendered in screen center 

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7758]
### Description

`EmptyView` is not centered in the middle of the screen when `CollectionView` has upper and lower siblings in its parent. Possibly related to #7251.

### Steps to Reproduce

1. Run the repro
2. Observe that the center of empty view content is not aligned with the red guide line
3. Comment out the black grids
4. Observe that `EmptyView` is centered properly

### Basic Information

- Version with issue: 4.4.0.1201-nightly
- Last known good version: N/A
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS: 12 
- Affected Devices: Tested on XS

### Reproduction Link

[App144.zip](https://github.com/xamarin/Xamarin.Forms/files/3674630/App144.zip)

**Comment by adrianknight89** [comment]
I briefly looked at this. I don't think there is anything wrong with EmptyView. The issue, at first glance, seems to be with CollectionView as it is measured to be the full screen size. Once the fix is provided, we can use the repro here as a test.

**Comment by jsuarezruiz** [comment]
Tested and verified the issue.

**Comment by rmarinho** [comment]
I don't see the issue in the latest versions. Please reopen if this still a issue.

![Simulator Screen Shot - iPhone 8 Plus - 2020-02-21 at 17 22 22](https://user-images.githubusercontent.com/1235097/75056359-c4cd3380-54ce-11ea-9f28-3a95a66d9432.png)
![Simulator Screen Shot - iPhone 11 - 2020-02-21 at 17 17 39](https://user-images.githubusercontent.com/1235097/75056362-c696f700-54ce-11ea-9b30-5753cb01eefc.png)
