### ISSUE TITLE
Inline C# code within XAML

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7761]
Hi,

It will be great if you add support for inline C# code within XAML similar to the x:Code in WPF or something like this:

`Tapped="{x:Code Navigation.PopAsync(); }"`

Thanks,
[Jassim](https://www.softnames.com)

**Comment by StephaneDelcroix** [comment]
that's not how x:Code is supposed to be used, and we do not have immediate plans to support x:Code
