### ISSUE TITLE
[CollectionView] Add ability to disable item animations

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#7763]
## Summary

Currently, if an item is added to `CollectionView`, the item is animated into its parent. There should be a way for us to toggle animations on and off. This could be achieved by setting `ItemAnimator` to null on `RecyclerView` (or configuring its properties) and using `UIView.performWithoutAnimation` during `UICollectionView` reloads.

## API Changes

```
public bool ItemChangeAnimationsEnabled {get; set;} = true;
// bindable property for ItemChangeAnimationsEnabled
```

**EDIT:** Changed proposed property name.

**Comment by bares43** [comment]
Is there any progress?

**Comment by YZahringer** [comment]
Could be a `5.0.0` candidate?

**Comment by RonnyBansemer** [comment]
Any news about that? This animation causes bad ui behavior when frequently adding elements to collection view on older (android) devices.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
