### ISSUE TITLE
Language property to Entry, Editor and others

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7765]
Hi,

Please add Language property to the Editor, Entry and all other possible controls so user can set the default language when using the keyboard

For example:

`<Editor Language="ar" />`

which will switch the keyboard to Arabic.. If Arabic keyboard is not installed then it will just show the default keyboard for the device, e.g. English

Thanks,
[Jassim](https://www.softnames.com)

**Comment by adrianknight89** [comment]
I don't think this is possible with default keyboards unless Xamarin provides a custom keyboard implementation. The only thing we could do is change the app locale, but that could affect so many other things like UI language and clock representation. Also, if an app forced users to use a specific language keyboard, then they can be thrown off by that.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
