### ISSUE TITLE
[Bug] Device.Idiom reports TargetIdiom.Phone for Amazon Fire TV Stick 4K

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#7772]
### Description

I try to optimize page layout for different kind of devices and would like to create a layout for Android TV users.

### Reproduction Link

Create a new App, add this to `MainPage.xaml` and run it on Amazon Fire TV Stick 4K

```
<Label TextColor="Red">
    <Label.Text>
        <OnIdiom x:TypeArguments="x:String">
            <OnIdiom.TV>Hello from a TV app</OnIdiom.TV>
            <OnIdiom.Phone>Hello from a phone app</OnIdiom.Phone>
            <OnIdiom.Tablet>Hello from a tablet app</OnIdiom.Tablet>
        </OnIdiom>
    </Label.Text>
</Label>
```
[OnIdiomDemoApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3680049/OnIdiomDemoApp.zip)

### Expected Behavior

I see: Hello from a TV app

### Actual Behavior

I see:  Hello from a phone app

### Steps to Reproduce

1. create a new XF App
2. [activate ADB on Fire TV Stick](https://developer.amazon.com/de/docs/fire-tv/connecting-adb-to-device.html#turnondebugging) 
3. run [adb connect IP:5555](https://developer.amazon.com/de/docs/fire-tv/connecting-adb-to-device.html#connectingadboptions) and deploy app from VS to Fire TV Stick

### Basic Information

- Version with issue: 4.2.0.778463
- Last known good version: n/a
- IDE: Visual Studio 2017 15.9.16
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8.1
  - UWP:   
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- **Affected Devices**: Amazon Fire TV Stick 4K and likely also all other Android TV devices

Here are some data from AIDA64 report:

```
<<< System >>>

Geräteart: TV
Hersteller: Amazon
Modell: AFTMM
Marke: Amazon
Board: mantis
Gerät: mantis
Hardware: mt8695
Platform: mt8695
Produkt: mantis

Geräte Besonderheiten: 

amazon.hardware.fire_tv
android.hardware.type.television
```

**Comment by MagicAndre1981** [comment]
ok, when I use `Xamarin.Essentials` the `DeviceInfo.Idiom` is set correctly to TV.

Now I need to figure out how to use the `DeviceInfo.Idiom` from `Xamarin.Essentials` in XAML instead of code.

**Comment by MagicAndre1981** [comment]
ok, here is the [problematic line](https://github.com/xamarin/Xamarin.Forms/blob/24fec62cdd8a140868ea3da4565cebb47e6654e4/Xamarin.Forms.Platform.Android/Forms.cs#L326)

Xamarin.Essentials uses [UiModeManager.FromContext and HasFlag to check if flags like TV are set](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs#L82). So XF also [misses valid types](https://developer.android.com/guide/topics/resources/providing-resources.html#UiModeQualifier) like Car, VR Headset, appliance and TV which triggers my issue here.

**Comment by MagicAndre1981** [comment]
ok, I used code parts of Xamarin.Essentials and my self compiled XF return now correct values. 

I tested it for my FireTV, Android phone and tablet. all return correct values. But what about copyright?

**Comment by jamesmontemagno** [comment]
They are both under MIT so you can bring the essentials code over. However I recommend always using essentials code ;)

**Comment by MagicAndre1981** [comment]
@jamesmontemagno thanks, I would like to use Essentials, but I can't find an XAML Markup extension in Essentials. I want to move everything into XAML to use XAML Hotreload for easier layout design.

**Comment by jamesmontemagno** [comment]
Ah, i see what you are saying is that you want to use OnIdiom in the code. that makes sense and should be fixed up in Forms here.
