### ISSUE TITLE
[Bug] [Android] Can not set Entry cursor position by tapping if ClearButtonVisibility=WhenEditing

### ISSUE THREAD

**Issue by janschoelchAtOK** [xamarin/Xamarin.Forms#7773]
### Description

In Xamarin.Forms Versions prior to V4.3, I was able to set the Cursor position within an Entry by tapping the location I want the cursor to be at.
Since the introduction of `ClearButtonVisibility` this behaviour has changed. If I set `ClearButtonVisibility=WhenEditing` on an entry, I can not change the cursor position by tapping anymore. This happens only if the soft keyboard is open.

### Steps to Reproduce

1. Run the attached solution, you should see two entries there.
2. Enter some random text into the first entry. Then tap anywhere within the entered text - the cursor should then jump to the selected Position accordingly.
3. Enter some random text into the second entry and try to relocate the cursor again. It does not work (the second Entry has `ClearButtonVisibility=WhenEditing` set)

### Expected Behavior

I should be able to set the cursor's position by tapping - even if `ClearButtonVisibility=WhenEditing` is set.

### Actual Behavior

I can only set the cursor's position by tapping if `ClearButtonVisibility=Never` is set (which is the default value).

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0-pre1+
- Last known good version: N/A (ClearButtonVisibility is only available on Version 4.3.0-pre1+)
- IDE: Tested on Visual Studio Professional 2019 (16.3.0)
- Platform Target Frameworks:
  - iOS:  13.1
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Xamarin.Forms & Xamarin.Forms.Visual.Material 4.3.0.819712-pre2
- Affected Devices: Tested on Huawei P Smart + (2018) with Android 8.1 installed

### Reproduction Link

[ClearButtonTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3680039/ClearButtonTest.zip)

**Comment by PureWeen** [comment]
@andreinitescu FYI

**Comment by samhouts** [comment]
closed by #8429
