### ISSUE TITLE
[Bug] CarouselView doesn't display string items without an ItemTemplate

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7779]
### Description

A `CarouselView` doesn't display string items without supplying an ItemTemplate to define the appearance of each item:

```
<CarouselView>
    <CarouselView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>Baboon</x:String>
            <x:String>Capuchin Monkey</x:String>
            <x:String>Blue Monkey</x:String>
            <x:String>Squirrel Monkey</x:String>
            <x:String>Golden Lion Tamarin</x:String>
            <x:String>Howler Monkey</x:String>
            <x:String>Japanese Macaque</x:String>
        </x:Array>
    </CarouselView.ItemsSource>
</CarouselView>
```

Conversely, a `CollectionView` does display string items without supplying an ItemTemplate.

### Steps to Reproduce

1. Run the above code.

### Expected Behavior

String items are displayed.

### Actual Behavior

Items aren't displayed.

### Basic Information

- Version with issue: 4.2-pre3
- IDE: VSMac

**Comment by jsuarezruiz** [comment]
Thanks for the feedback @davidbritch. I created a sample using CarouselView with strings and without DataTemplate and I get the following result:

<img width="1517" alt="Captura de pantalla 2019-10-03 a las 10 09 50" src="https://user-images.githubusercontent.com/6755973/66110025-2e06e580-e5c6-11e9-849b-125e3142ab0b.png">

Is there something I am not considering?. The sample used:
[Issue7779.zip](https://github.com/xamarin/Xamarin.Forms/files/3685052/Issue7779.zip)

**Comment by davidbritch** [comment]
@jsuarezruiz I agree that it's no longer an issue in 4.3-pre3. Apologies, my original report should have said it was an issue in 4.3-pre2 (instead of 4.2-pre3!)

**Comment by davidbritch** [comment]
@jsuarezruiz There is actually an issue here - your sample uses 4.3-pre3 in the .NET Standard lib, but 4.2 in the iOS project. If both projects use 4.3-pre3 it crashes completely. But that's a new issue, so I'm going to close this bug and file a new one.

**Comment by davidbritch** [comment]
New issue at https://github.com/xamarin/Xamarin.Forms/issues/7789
