### ISSUE TITLE
[Bug] CarouselView doesn't support RTL layout

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7780]
### Description

Unlike `CollectionView, `CarouselView` doesn't respect the `FlowDirection` being set to `RightToLeft` on the parent page.

### Steps to Reproduce

1. Set the `FlowDirection` property (on a page containing a `CarouselView`) to `RightToLeft`.

### Expected Behavior

The `CarouselView` respects the RTL flow direction, and is laid out accordingly.

### Actual Behavior

The `CarouselView` doesn't respect the RTL flow direction.

### Basic Information

- Version with issue: 4.3-pre2
- IDE: VSMac

**Comment by jsuarezruiz** [comment]
I attach a repro sample:
[Issue7780.zip](https://github.com/xamarin/Xamarin.Forms/files/3685090/Issue7780.zip)
It seems to work correctly on Android but **not on iOS**.

**Comment by abdu292** [comment]
@jsuarezruiz Still doesn't seem to be working on Android (yet to test on iOS)

Repro:
[CarouselRTLRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4874438/CarouselRTLRepro.zip)

Tested on 
Android 10 (API 29)
Xamarin.Forms : 4.7.0.1080

Thank you!

**Comment by jsuarezruiz** [comment]
Mnn, the fix was merged in 4.6 and should be in 4.7 too. Let me take a look.

**Comment by abdu292** [comment]
@jsuarezruiz Just was wondering if you got a chance to run the repro. Thanks a lot!

**Comment by samhouts** [comment]
closed by #10593

**Comment by abdu292** [comment]
Thanks @samhouts & @jsuarezruiz . I know this is not part of Xamarin.Forms 4.7 yet (repro project above). May I know which version this fix will be shipped with? Thanks again!
