### ISSUE TITLE
[Enhancement] iOS TabbedPage ToolbarPlacement Top

### ISSUE THREAD

**Issue by dannythomas13** [xamarin/Xamarin.Forms#7782]
Is it possible to include an option to place iOS tabs at the top? I have seen and used the option to place Android options at the bottom and would be great for iOS https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.androidspecific.toolbarplacement?view=xamarin-forms

**Comment by PureWeen** [comment]
iOS doesn't really have native support for Top Tabs
These are implemented on Shell but it's done by using a custom layout of UIViews

There's been talk about just creating a FormsTabBar that's all Forms components that we could do this with which would make this possible or we could reuse the shell implementation

**Comment by padmakant** [comment]
ill work on this

**Comment by JeremyBP** [comment]
There's naxam implementation of top tabbed page for iOS https://github.com/NAXAM/toptabbedpage-xamarin-forms
But it would be so cool if it could be used like it is for Android but with iOSSpecific

**Comment by ChaseFlorell** [comment]
Throwing my vote in too. 
I realize it's not "native" to iOS, but it seems like Forms is moving away from that anyways.

We could keep the android attached property for compatibility, but then add the same property directly to the current NavigationPage as net new.

```
this.ToolbarPlacement = "Default" (top for droid, bottom for touch,???UWP et al)
this.ToolbarPlacement = "Top | Bottom" for consistency across platforms.
```

Could even leverage the work already done in naxam

**Comment by xamiell** [comment]
@dannythomas13  that will be very nice for Cross consistency too

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
