### ISSUE TITLE
ImageCell not displaying image only on Android

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#7786]
### Description

Image and ImageCell could not load remote URL imageSource only on Android . On iOS it works fine . And I have set HttpClientImplementation to Managed and SSL/TLS to 1.2+ .

### in xaml

```
<ListView x:Name="listView">
   <ListView.ItemTemplate>
          <DataTemplate>
              <ImageCell Text="{Binding Name}" Detail="{Binding Status}" ImageSource="{Binding ImageUrl}" />
          </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

### in code behind

```
public class Contact
{
    public string Name { get; set; }
    public string Status { get; set; }
    public string ImageUrl { get; set; }
}
```

```
public partial class GreetPage : ContentPage
{
    public GreetPage()
    {
        On<iOS>().SetUseSafeArea(true);

        InitializeComponent();

        listView.ItemsSource = new List<Contact>
        {
            new Contact { Name="John", ImageUrl = "http://lorempixel.com/100/100/people/1" },
            new Contact { Name="Jack", ImageUrl = "http://lorempixel.com/100/100/people/2", Status="Hello guys" },
            new Contact { Name="Jill", ImageUrl = "http://lorempixel.com/100/100/people/3" }
        };
    }       
}
```

### Basic Information

- Version with issue:

Xamarin.Forms 4.1 and 4.2

### Reproduction Link

https://stackoverflow.com/questions/58213955/imagecell-not-displaying-image-only-on-android

**Comment by PureWeen** [comment]
@luczha I'm going to assume the response in there answers your question

https://stackoverflow.com/a/58215163


This
https://github.com/xamarin/Xamarin.Forms/issues/7751

Might also be your issue? but I'm guessing the response in the SO post covers your case
