### ISSUE TITLE
[Bug] CollectionView ItemsUpdatingScrollMode=KeepLastItemInView not working on iOS

### ISSUE THREAD

**Issue by StevenGranados** [xamarin/Xamarin.Forms#7788]
### Description
ItemsUpdatingScrollMode=KeepLastItemInView seems to not work on iOS but works fine on android.

### Steps to Reproduce

1. Open repro
2. Run on iOS 13 simulator 
3. Click add until items reach bottom of page
4. Observe that new items aren't scrolled to automatically.

### Expected Behavior
Items scrolled to if added on end.
### Actual Behavior
Items are added but collectionview isn't scrolled automatically.
### Basic Information

- Version with issue: 4.3.0.851321-pre3
- Last known good version: Doesn't work in 4.2 either
- IDE:Visual studio 2019 16.3.2
- Platform Target Frameworks: 
  - iOS:  13.0
- Android Support Library Version: 28.0.0.3
- Nuget Packages: No unusual ones
- Affected Devices:iPhone 8

### Reproduction Link
[CarouselViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3685323/CarouselViewTest.zip)

**Comment by PureWeen** [comment]
Behavior isn't iOS 13 specific

**Comment by modplug** [comment]
Any updates to this?

**Comment by stefanbogaard86** [comment]
Currently using a workaround with the ScrollTo method to scroll to the end of the CollectionView, but this has it's own problems (doesn't work well with items of different sizes). Anyone got a working workaround?

**Comment by Tommigun1980** [comment]
Please reopen. This doesn't work on iOS.

**Comment by MSicc** [comment]
it does also not work on XF 4.8.0.1560, and I am still suffering all the referenced issues as well.

**Comment by jessejiang0214** [comment]
Not working on Andorid also, with XF 4.8.0.1560
