### ISSUE TITLE
[Bug][iOS] CarouselView ScrollTo (by object) not working

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7798]
### Description

In CarouselView, on iOS, scrolling to an item by index works fine. Scrolling to an item by object does not work (in 4.3-pre3). Having said that, I *think* it worked in 4.3-pre2.

In my code, the correct `Monkey` object is retrieved, but the `ScrollTo` method isn't scrolling to it.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the scroll by object page.
3. Click the button.

### Expected Behavior

The Proboscis Monkey appears.

### Actual Behavior

The Capuchin Monkey appears.

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: I *think* it worked in 4.3-pre2
- IDE: VSMac 8.3.1
- Platform Target Frameworks:
  - iOS:  13

### Screenshots

Prior to clicking the button:

![Simulator Screen Shot - iPhone X - 2019-10-03 at 15 18 14](https://user-images.githubusercontent.com/8092460/66134974-17c24f00-e5f1-11e9-9857-09e33a7af326.png)

Post clicking the button:

![Simulator Screen Shot - iPhone X - 2019-10-03 at 15 18 16](https://user-images.githubusercontent.com/8092460/66134990-1db83000-e5f1-11e9-93ec-4d3dfe3bb175.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3686499/CarouselViewDemos.zip)

**Comment by rmarinho** [comment]
his issue have been fixed in the latest 4.4 stable.

**Comment by TonyLugg** [comment]
I'm using XF 4.8 and it still doesn't work properly.

**Comment by stivenbr** [comment]
BUG. Does not work in xamarin forms 4.8
