### ISSUE TITLE
[Bug][Android] CarouselView ScrollTo (by index) not working

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7800]
### Description

In CarouselView on Android, scrolling to an item by index doesn't work. On three runs of attempting to scroll to the same index, I got three different results (see screenshots). None of them are correct.

Note: the code in the attached sample takes the `ScrollToPosition` enumeration into account, but changing the code just to `carouselView.ScrollTo(6);` still produces the problem.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the scroll by index page.
3. Click the button.

### Expected Behavior

The Japanese Macaque is displayed.

### Actual Behavior

Different results each time! (see screenshots)

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VSMac 8.3.1
- Platform Target Frameworks: 
  - Android: API 28

### Screenshots

First run:

![Screenshot_1570113865](https://user-images.githubusercontent.com/8092460/66137815-8dc8b500-e5f5-11e9-8eb4-b26a31fad995.png)

Second run:

![Screenshot_1570113871](https://user-images.githubusercontent.com/8092460/66137826-928d6900-e5f5-11e9-9d1a-f027906fe88e.png)

Third run:

![Screenshot_1570113883](https://user-images.githubusercontent.com/8092460/66137845-9b7e3a80-e5f5-11e9-8e94-55d7cbe1c805.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3686670/CarouselViewDemos.zip)

**Comment by rmarinho** [comment]
This is fixed on 4.4 stable
