### ISSUE TITLE
[Bug][Android] CarouselView ScrollTo (by object) not working

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7801]
### Description

In CarouselView on Android, scrolling to an item by object doesn't work. It took three clicks to scroll to my object (see screenshots). 

In my code, the correct `Monkey` object is retrieved, but the `ScrollTo` method doesn't scroll to the correct monkey in one go.

Note: the code in the attached sample takes the ScrollToPosition enumeration into account, but changing the code just to `carouselView.ScrollTo(monkey);` still produces the problem.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the scroll by object page.
3. Click the button.

### Expected Behavior

The Proboscis Monkey appears.

### Actual Behavior

Different results on each button click (see screenshots).

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VS Mac 8.3.1.
- Platform Target Frameworks: 
  - Android: API 28

### Screenshots

Starting position:

![Screenshot_1570114668](https://user-images.githubusercontent.com/8092460/66139738-da61bf80-e5f8-11e9-8fd2-3649d26d5165.png)

First click:

![Screenshot_1570114671](https://user-images.githubusercontent.com/8092460/66139996-417f7400-e5f9-11e9-83ab-9c02ec763cb5.png)

Second click:

![Screenshot_1570114673](https://user-images.githubusercontent.com/8092460/66140039-53f9ad80-e5f9-11e9-8655-7924aed286bb.png)

Third click is the winner:

![Screenshot_1570114675](https://user-images.githubusercontent.com/8092460/66140050-5825cb00-e5f9-11e9-9f14-d1eea4e0ea69.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3686765/CarouselViewDemos.zip)

**Comment by rmarinho** [comment]
Fixed on 4.4 stable
