### ISSUE TITLE
[Bug] Changing ItemSizingStrategy has no effect on CarouselView

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7804]
### Description

Changing the ItemSizingStrategy has no effect on CarouselView item layout (whereas it does on CollectionView).

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the variable sized items page.
3. Change the ItemSizingStrategy value in the Picker.

### Expected Behavior

Item layout changes.

### Actual Behavior

Item layout doesn't change, regardless of the ItemSizingStrategy value.

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VS Mac 8.3.1
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android: API 28

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3686890/CarouselViewDemos.zip)

**Comment by PureWeen** [comment]
@rmarinho says this doesn't make sense for Carousel View

Discuss

**Comment by davidbritch** [comment]
I don't actually have a scenario that requires this - having different sized cards (items) can be achieved without requiring ItemSizingStrategy.

However, intellisense will display that ItemSizingStrategy can be set. So if it's to have no effect on a CarouselView, I guess we either need:

1. To block intellisense from displaying the property, if it's being set on a CarouselView (is that even possible?).
1. A comment in the intellisense remarks that it has no effect on a CarouselView.

**Comment by hartez** [comment]
ItemSizingStrategy should be moved up into StructuredItemsView.

**Comment by hartez** [comment]
This was addressed by #8588
