### ISSUE TITLE
ShellContent ContentTemplate

### ISSUE THREAD

**Issue by hponaganti** [xamarin/Xamarin.Forms#7805]
I'm trying to change the Shell Content Dynamically on a toolbar click. 

Created three datatemplates with three different pages
 <DataTemplate x:Key="page1Template">
            <views:Page1/>
        </DataTemplate>
        <DataTemplate x:Key="page2Template">
            <views:Page2/>
        </DataTemplate>
        <DataTemplate x:Key="page3Template">
            <views:Page3/>
        </DataTemplate>

And created converter to  return proper template based on ViewModel property Binding
       <local:TemplateSelectorConverter x:Key="tsConverter" Page1Template="{StaticResource page1Template}" Page2Template="{StaticResource page2Template}"  Page3Template="{StaticResource page3Template}"/>

    <ShellContent ContentTemplate="{Binding DefaultEventView,Converter={StaticResource tsConverter}}"    Title="Page1"  Route="AVIEW" Style="{StaticResource tabStyle}"/>

Even Though the DefaultEventView and the converter gets called and returns the proper template. The ShellContent is not getting updated

**Comment by PureWeen** [comment]
@hponaganti can you attach a small reproduction of your issue please?

**Comment by samhouts** [comment]
@hponaganti  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
