### ISSUE TITLE
App crashing when running in android kitkat 4.4.4

### ISSUE THREAD

**Issue by georgethms10** [xamarin/Xamarin.Forms#7812]
### Description

Create a new project in visual studio 8.2.5 [build 5]

1. Change the min api level to 19
2. Run the application in Kitkat 19 device 
3. Inside the OnCreate app crashes with File res/drawable/abc_vector_test.xml from drawable resource ID #0x7f070058

### Expected Behavior
Application should work with minimum api level kitkat
### Actual Behavior
Application crashes on startup
### Basic Information

- Version with issue:Xamarin.Android
Version: 9.4.1.0 (Visual Studio Community)
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 19
- Android Support Library Version: 28.0.3
- Nuget Packages: 
- Affected Devices: Kitkat devices

### Reproduction Link

No need just create a new project in vs and run in kitkat devcice

**Comment by GalaxiaGuy** [comment]
It sounds like this issue:

https://github.com/xamarin/xamarin-android/issues/3314

**Comment by PureWeen** [comment]
@GalaxiaGuy Thank you!!

Closing for now. It looks like 16.3 has a fix for thtis
https://github.com/xamarin/xamarin-android/issues/3314#issuecomment-534823495

@georgethms10 if this still isn't fixed for you please let me know

**Comment by georgethms10** [comment]
@PureWeen Yep the crash is resolved now. Thanks a lot
