### ISSUE TITLE
[Bug] Changing ItemsUpdatingScrollMode has no effect on CarouselView

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7817]
### Description

Changing the ItemsUpdatingScrollMode property has no effect on CarouselView scrolling (whereas it does on CollectionView).

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the "Scroll mode when adding items" page.
3. Change the ItemsUpdatingScrollMode value in the Picker.

### Expected Behavior

Scrolling behaviour changes, in line with the ItemsUpdatingScrollMode Picker value, as items are added to the CarouselView.

### Actual Behavior

Scrolling behavior doesn't change as items as added to the CarouselView.

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VSMac 8.3.1
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android: API 28

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3690245/CarouselViewDemos.zip)

**Comment by PureWeen** [comment]
Related
https://github.com/xamarin/Xamarin.Forms/issues/7788

**Comment by samhouts** [comment]
closed by #7872
