### ISSUE TITLE
CollectionView scroll several time and it hangs whole UI on iOS side. 

### ISSUE THREAD

**Issue by chetanshingala** [xamarin/Xamarin.Forms#7820]
### Description

Scroll CollectionView left to right & right to left several time and it hangs UI. Facing issue on iOS side only. I have used Xamarin forms latest stable version Xamarin.Forms(4.2.0.848062).I was using Xamarin.Forms(4.1.0.778454) firstly at that time it was working properly.

### Steps to Reproduce

Scroll CollectionView several time left-to-right and right-to-left and UI gets hang.

[Here is demo project Link](https://www.dropbox.com/s/q9uv9p74wzz9613/TestCollectionView.zip?dl=0)

[Here is issue video link](https://www.dropbox.com/s/509j3iy0z09tq3o/CollectionView-issue.mov?dl=0)

### Expected Behavior
CollectionView should not hang whole UI. 

### Actual Behavior
CollectionView hangs UI on scroll several time.

**Comment by adrianknight89** [comment]
I tested this on a physical device with 4.4.0.1206-nightly. No issues. I'm not sure if this is a simulator problem. @chetanshingala Can you test the version I tested to see if you're still having this problem?

**Comment by PureWeen** [comment]
@chetanshingala I'm seeing the same behavior as @adrianknight89 

I'm going to close this for now as this appears to be fixed
