### ISSUE TITLE
[Bug] ContentPage.Resources with no ResourceDictionary crashes the app

### ISSUE THREAD

**Issue by jameslavery** [xamarin/Xamarin.Forms#7821]
### Description
Creating <ContentPage.Resources> for a ContentPage without a <ResourceDictionary> element crashes the app when the Resources contains only a single IValueConverter.

### Steps to Reproduce

1. Create a simple Forms app with a XAML page and associated ViewModel
2. Create a ValueConverter - e.g. InverseBoolConverter.
3. Add the InverseBoolConverter to the ContentPage.Resources, with no ResourceDictionary
5. Refer to the InverseBoolConverter in the ContentPage XAML
6. Build and run the app. It will crash after the splash screen.

### Expected Behavior
The app works.

### Actual Behavior
The app crashes with the error:

> error: ResourceDictionaryBugDemo.InverseBoolConverter doesn't implement interface System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String,System.Object>>

### Basic Information

- Version with issue: Definitely 3.6.0.709228 and 4.2.0.848062 - probably all.
- Last known good version: Not known
- IDE: VS for Mac (but almost definitely VS for Windows too)
- Platform Target Frameworks: 
  - iOS:  8.0
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: N/a
- Nuget Packages: None apart from Xamarin.Forms
- Affected Devices: All!

### Probable Cause
There was an improvement  introduced with Xamarin.Forms 3.0 whereby there is no need for a <ResourceDictionary></ResourceDictionary> inside <ContentPage.Resources></ContentPage.Resources>

The system still seems to expect a single element inside <ContentPage.Resources> to implement IEnumerable (which a ResourceDictionary presumably does). The InverseBoolConverter does not implement IEnumerable, and so the app crashes.

Adding just one other element in the <ContentPage.Resources> tag fixes the problem.

### Reproduction Link
[ResourceDictionaryBugDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/3690500/ResourceDictionaryBugDemo.zip)

Solution attached.

**Comment by StephaneDelcroix** [comment]
this is really weird, we have test for that. But I can reproduce the issue

**Comment by StephaneDelcroix** [comment]
only happen with XamlC on

**Comment by StephaneDelcroix** [comment]
the failure happen because you converter implements IMarkupExtension, which is kind of an edge case

**Comment by jameslavery** [comment]
Interesting. I'll see if we can remove that.

Sent from my phone. Apologies for brevity and possible auto-correct quirks.

________________________________

**Comment by StephaneDelcroix** [comment]
If you insist on implementing IMarkupExtension, inherit from the generic one, otherwise the Xaml compiler has no way to figure out that the result of ProvideValue is not a ResourceDictionary (please don't do that either)

I do not consider this a bug, it's just that the usage can not be inferred from the syntax, and you should use the explicit syntax

**Comment by jameslavery** [comment]
Ok - good point. But what do you mean by "I wouldn't do that either."?
________________________________

**Comment by jameslavery** [comment]
Sorry, I meant "Please don't do that either"?
________________________________

**Comment by jameslavery** [comment]
> If you insist on implementing IMarkupExtension, inherit from the generic one, otherwise the Xaml compiler has no way to figure out that the result of ProvideValue is not a ResourceDictionary (please don't do that either)
> 
> I do not consider this a bug, it's just that the usage can not be inferred from the syntax, and you should use the explicit syntax

Thank you - I see what you mean. I need to review why we've decided to implement IMarkupExtension in some of our ValueConverters.

**Comment by nexussays** [comment]
I am able to consistently reproduce this in `4.4.0.991477` exactly as described. If you have a single item without a wrapping ` <ResourceDictionary>` it throws a very obscure and hard-to-trace error. Got bitten by this twice because it's not at all obvious.
