### ISSUE TITLE
[Bug] Frame corner radius.

### ISSUE THREAD

**Issue by AlexAba** [xamarin/Xamarin.Forms#7823]
### Description
After updating from v3.6.0.344457 to v4.2.0.848062 frame cease to cut corners of child elements.
### Steps to Reproduce

1. Create frame with any corner radius and NOT ZERO padding.
2. Create one more frame as a child of the first with any corner radius and ZERO `padding.`
3. Into the second frame insert boxview(can be any view)

### Expected Behavior
Child elements has cut corners.
### Actual Behavior
Child elements don't has cut corners

### Code for screenshot

    <StackLayout>
        <Frame CornerRadius="5" BackgroundColor="Red" Padding="10">
            <Frame CornerRadius="10" BackgroundColor="Blue" Padding="0">
                <BoxView BackgroundColor="Green" HeightRequest="100" WidthRequest="100"/>
            </Frame>
        </Frame>
    </StackLayout>

### Screenshots
![photo_2019-10-04_16-53-25](https://user-images.githubusercontent.com/32664004/66212973-88d43600-e6c7-11e9-839a-356f0ac7bbc4.jpg)

**Comment by samhouts** [comment]
@AlexAba  What platform do you see this on? Android? iOS? UWP? Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by AlexAba** [comment]
Android

**Comment by PureWeen** [comment]
It looks like this regressed when the ClipToBounds defaults shifted on Android
If you set the inner frame to *Frame IsClippedToBounds="True"* then it clips to the radius correctly

This should just be a matter of doing that automatically on the Frame when corner radius is set

**Comment by samhouts** [comment]
closed by #8032

**Comment by vinksharma** [comment]
Facing this issue again after upgrading to 4.7.0.968
