### ISSUE TITLE
[Bug][Android] CarouselView gets stuck in an infinite forwards/backwards scroll

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7826]
### Description

I've been exploring snap points on CarouselView. I managed to get them behaving as expected on iOS. However, Android is a different story. After forwards/backwards scrolling a CarouselView a number of times, it seems to get stuck in some kind of forwards/backwards infinite scroll. The result looks like an attempt at a rotoscoping animation.

In case there are any doubts about what I'm describing, I've attached a zipped Quicktime mov below. To generate it I just scrolled backwards/forwards in small increments until it went crazy (took around 10s).

The CarouselView in question is defined as:

```
        <CarouselView x:Name="carouselView"
                      ItemsSource="{Binding Monkeys}"
                      NumberOfSideItems="1">
```

If I remove setting NumberOfSideItems, the problem vanishes.

### Steps to Reproduce

1. Run the attached sample. 
2. Browse to the snap points page (on Android).
3. Scroll forwards/backwards a couple of times until CarouselView goes crazy.

It's difficult to give exact repo steps, but I've been able to repo this 100% of the time, in 10-20s. I'd just randomly scroll forwards/backwards until it'd get stuck in the infinite scroll.

### Expected Behavior

CarouselView scrolls backward/forwards as directed.

### Actual Behavior

CarouselView goes into a crazy infinite backwards/forwards scroll.

### Basic Information

- Version with issue: 4.3-pre2
- Last known good version: N/A
- IDE: VSMac 8.3.1
- Platform Target Frameworks:
  - Android: API 28

### Screenshots

Unzip the Quicktime mov to see it in action:

[carouselview.mov.zip](https://github.com/xamarin/Xamarin.Forms/files/3691030/carouselview.mov.zip)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3691059/CarouselViewDemos.zip)

**Comment by PureWeen** [comment]
I wasn't able to reproduce

@rmarinho @jsuarezruiz maybe you'll have better luck?

**Comment by davidbritch** [comment]
I just tried it again and was able to repro it in about 5s. I can always screen share with someone if required.

**Comment by jsuarezruiz** [comment]
I've tried in emulator and I don't get the same result as the video (infinite scroll). If swipe very fast then sometimes, for example swiping to the left, the items move to the wrong direction quickly (but not infinitely). Will test it in a device (probably is easier to reproduce).

**Comment by davidbritch** [comment]
A few more details:

IDE: VSMac 8.3.1 (build 18)
Emulator image: Pixel 2 XL Pie 9.0 - API 28 for x86 processor, 1GB RAM, 1440x2880 resolution
Android SDK Tools: 26.1.1
Android SDK Platform-Tools: 29.0.4
Android SDK Build Tools: 28.0.3 (maybe I should update to latest?)
Android Emulator: 29.2.1

**Comment by hartez** [comment]
I can repro it if I run it on my Galaxy S8 and rotate to landscape mode while the app is running. Sometimes it will immediately go into the loop, other times I have to scroll it a bit first.

**Comment by rmarinho** [comment]
I can't  reproduce this issue, can you update the latest XamarinForms 4.4 and try it out.

**Comment by davidbritch** [comment]
@rmarinho I'm no longer able to repro this. It only occurred when setting the `NumberOfSideItems` property, which has since been removed. So the issue can be closed now.
