### ISSUE TITLE
[Bug] After #7531 some XAML namespaces require assembly

### ISSUE THREAD

**Issue by VitalyKnyazev** [xamarin/Xamarin.Forms#7830]
### Description
Ironically after #7531 some XAML namespaces require assembly name otherwise the app just crashes.

### Steps to Reproduce
1.  Add a XAML element like Button and set its Text to a string property of a **static** class like 
"public static class ResourceStrings", for example Text="{x:Static resources:ResourceStrings.SomeText}"
2. Namespace xmlns:resources="clr-namespace:App.Core" worked ok before 4.3.0.851321-pre3
3. Now namespace like xmlns:resources="clr-namespace:App.Core;assembly=App.Portable" is necessary to avoid the crash.

### Expected Behavior
xmlns:resources="clr-namespace:App.Core" should be enough

### Actual Behavior
The app crashes unless assembly is specified
xmlns:resources="clr-namespace:AppCore;assembly=App.Portable"

### Basic Information
- Version with issue: 4.3.0.851321-pre3
- Last known good version: 4.3.0.819712-pre2
- IDE: VS2019 16.3.2
- Platform Target Frameworks:
  - iOS:  13.2.0.42
  - Android: 10.0.0.43

**Comment by PureWeen** [comment]
@StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
please provide a repro project as soon as you can. thanks

**Comment by VitalyKnyazev** [comment]
Hi @StephaneDelcroix 

Here is the project:
https://github.com/VitalyKnyazev/StaticCrash

It is a bit trickier than I thought:
-  x:Static must be within DataTemplate
-  XamlCompilation must be off

If you change 
xmlns:core="clr-namespace:StaticCrash"
to
xmlns:core="clr-namespace:StaticCrash;assembly=StaticCrash"
then it also works.

Off topic - is it worth turning off XAML compilation in DEBUG mode?

**Comment by StephaneDelcroix** [comment]
Thanks, will look at that.



> Off topic - is it worth turning off XAML compilation in DEBUG mode?

well, yes and no

yes:
- (1) it speeds up the dev cycle

no:
- (2) you'll miss a lot of error usually caught at compile-time with XamlC on
- (3) the application you're currently debugging is not the same that the one you'll release, and you have to make sure you're testing it in Release mode as well (this is always a good advice, btw)

To get the gain from (1), and keep the validation, we introduced a new flag that only does the validation part, but doesn't actually write the assembly back (#7407). This will be available in 4.3. We're still considering enabling that by default.
