### ISSUE TITLE
[Bug] Android AppShell TabBar translate "More" menu text

### ISSUE THREAD

**Issue by Riuujin** [xamarin/Xamarin.Forms#7849]
### Description
I am using AppShell with a tab bar to create a simple bottom tab menu. 
On Android when more tabs are created then fit within the view, it wraps the non fitting tabs in a menu.
However when the device is in a different language the text of this menu is still the English "More".

### Steps to Reproduce

1. Create an AppShell project
2. Add more tabs than fit on your android device
3. Set your device to a difference language then English
4. Run the app

### Expected Behavior
The text on the menu "More" is translated in the language of the device.

### Actual Behavior
The text on the menu is always "More" regardless of language.

### Basic Information

- Version with issue: Xamarin forms 4.2
- IDE: Visual studio (windows)
- Platform Target Frameworks: 
  - Android: 9.0

**Comment by jfversluis** [comment]
Hi @Riuujin, thanks for the report!

While it might seem like a simple task to create a repro ourselves, I would like to ask you to add one. We do this so we can validate that this happens and is not influenced by anything other that might be at play in your (probably bigger) codebase. Also, this way we can easily see what versions of XF you have installed exactly and some other things as well.

If it's not too much trouble, could you provide a reproduction? Thanks!

**Comment by Riuujin** [comment]
[7849.zip](https://github.com/xamarin/Xamarin.Forms/files/3697212/7849.zip)
Added a simple reproduction project (within the zip file)

**Comment by jfversluis** [comment]
Confirmed that this is happening. 

Seems to originate [here](https://github.com/xamarin/Xamarin.Forms/blob/b77de4d77da6d404a634eea32d88785d43ff3a3a/Xamarin.Forms.Platform.Tizen/Shell/ShellItemRenderer.cs#L344). It is simply set to a hard-coded string "More".

The same thing seems to happen with non-Shell Android apps [here](https://github.com/xamarin/Xamarin.Forms/blob/731134578efd362966f9ecc03fba310df4e13ae6/Xamarin.Forms.Platform.Android/Renderers/BottomNavigationViewUtils.cs#L82).

It seems Android does not have the automatic "overflow" mechanism as iOS has? Meaning that Android does not have a built in translation for this More text? So it seems the most obvious thing we can do here is to get the string from the resources so users can override it themselves?

**Comment by Riuujin** [comment]
That would solve the issue for my use case

**Comment by Riuujin** [comment]
Any update on this?

**Comment by jfversluis** [comment]
Opened a PR for this

**Comment by pnda489** [comment]
Hey any update or ETA on this?

**Comment by Riuujin** [comment]
Any ETA? I also see that a unit test has been running for a long time: 'XFDashboard / DROID-API19-FR started 8d 15h 22m 46s ago'

**Comment by jfversluis** [comment]
@Riuujin I see it's merged for 4.8 I think this should see the light somewhere halfway into August!

**Comment by lazareveugene** [comment]
hi, we checked 'MORE' button on Android and it looks good

but what about iOS ? it has same issue

**Comment by jfversluis** [comment]
Awesome! I think for iOS you just need to add the right supported languages in your `info.plist` and it should translate together with the UI language.

**Comment by lazareveugene** [comment]
yes found it )))

**Comment by ivanteles** [comment]
I updated my app to Xamarin 4.8 and it continues more.

**Comment by pnda489** [comment]
I can confirm @ivanteles , i upgraded to 4.8 and it is not working.

**Comment by ivanteles** [comment]
@pnda489 I am using "Portugues" as "Device Language"

**Comment by Riuujin** [comment]
I have added 'overflow_tab_title' to the strings.xml but i cannot get the new value to display. I tried it both in "values/strings.xml" and "values-nl/strings.xml" (and set the emulator to dutch language aswell) but i am seeing no change. Am I doing something wrong? See attachment.
[7849-with-strings_xml.zip](https://github.com/xamarin/Xamarin.Forms/files/5186991/7849-with-strings_xml.zip)

**Comment by valentasm1** [comment]
Solution add/update file in Android YourProject/Resources/values/strings.xml

```
<?xml version="1.0" encoding="UTF-8" ?>
<resources>
	<string name="overflow_tab_title">New Translation</string>
</resources>
```

**Comment by ivanteles** [comment]
@valentasm1 vlw
