### ISSUE TITLE
 filterassemblies task failed unexpectedly (Android Project )

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [xamarin/Xamarin.Forms#7852]
### When run my app in debug mode it deploy successfully but when in realease mode I have this error and app cannot deploy 

Target _AddAndroidCustomMetaData:
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018: The "FilterAssemblies" task failed unexpectedly.
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/seedersmarket/Desktop/Barek/Barek 2/Barek/Barek/bin/Debug/netstandard2.0/Barek.dll".
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0015e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:223 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/mcs/class/corlib/System.IO/FileStream.cs:91 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at System.IO.File.OpenRead (System.String path) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:266 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at Xamarin.Android.Tasks.FilterAssemblies.Execute () [0x0006f] in <fa231dc8d40d45fd86217b6055f9a563>:0 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/TaskExecutionHost/TaskExecutionHost.cs:574 
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(520,3): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/msbuild-15/src/Build/BackEnd/Components/RequestBuilder/TaskBuilder.cs:805 
Done building target "_AddAndroidCustomMetaData" in project "Barek.Android.csproj" -- FAILED.

Done building project "Barek.Android.csproj" -- FAILED.

Build FAILED.
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: Xamarin Forms Version 4.1.0.581479
- Last known good version: Xamarin Forms Version 3.3
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
    - Android: version 8

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Hey @AhmedAdelGadElkareeem, thank you for the report.

I think I notice a space in your filepath? You might want to avoid using that. Although it's still strange that it works in debug and not release. After doing some searching I came across this issue on the Xamarin.Android repo: https://github.com/xamarin/xamarin-android/issues/3423 seems like you might encounter that one.

Unfortunately, this is not a Xamarin.Forms specific error, I suggest you keep an eye on the above issue and maybe add your details there. I will be closing the issue here. If later turns out that it _does_ involve Xamarin.Forms, please feel free to reopen or open a new issue referencing this one.
