### ISSUE TITLE
[Bug] Shell BackButtonBehaviour TextOverride breaks back navigation

### ISSUE THREAD

**Issue by lrolleman** [xamarin/Xamarin.Forms#7856]
### Steps to Reproduce

1. Override text in a BackButtonBehaviour
ex. Shell.SetBackButtonBehavior(this, new BackButtonBehavior
            {
                TextOverride = "Test"
            });

### Expected Behavior
The Back button should now have the text "< Test"

### Actual Behavior
The Back button has the value "Text" (without the arrow) and opens the Flyout menu rather than navigate back

### Basic Information

- Version with issue: 4.2.0.778463
- Last known good version: Unknown
- IDE: Visual Studio Enterprise 2019
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.2.0.42

**Comment by jfversluis** [comment]
Confirmed that this is happening. Only on iOS, on Android it seems to go OK.

[Repro7856.zip](https://github.com/xamarin/Xamarin.Forms/files/3707109/Repro7856.zip)

**Comment by jfversluis** [comment]
Traced it back to `iOS.ShellPageRendererTracker.UpdateToolbarItems`. There is a lot going on there with trying to determine which button to show when the BackButtonBehavior is set.
