### ISSUE TITLE
[Bug] CarouselView setting Position has dif behavior than ScrollTo

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#7865]
# Description

`CitiesCarousel.Position = pos;` will change the position, but sometimes only by 1 whereas `CitiesCarousel.ScrollTo(pos, animate: false);` works as expected.

### Expected Behavior

Setting `Position` moves the CarouselView to that item index.

### Actual Behavior

It doesn't always, and usuallly only moves the index 1.

### Basic Information

- Version with issue: 4.3.0-pre3
- Platform Target Frameworks: 
  - iOS:  13

### Reproduction Link

https://github.com/davidortinau/WeatherColors/blob/position-bug/WeatherColors/WeatherColors/View/CityListPage.xaml.cs#L35

**Comment by jsuarezruiz** [comment]
This issue is the same as https://github.com/xamarin/Xamarin.Forms/issues/7798 and will be fixed with https://github.com/xamarin/Xamarin.Forms/pull/7857

**Comment by jfversluis** [comment]
Are you sure @jsuarezruiz ? Because #7798 says `ScrollTo()` isn't working, while @davidortinau is saying setting `.Position =` doesn't work and `ScrollTo()` _does_ work.

**Comment by jsuarezruiz** [comment]
Mnn, you are right. I will check it!.
