### ISSUE TITLE
[Enhancement] Add .NET Core 3 support to WPF package

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#7885]
The [Xamarin.Forms.Platform.WPF](https://www.nuget.org/packages/Xamarin.Forms.Platform.WPF/) NuGet package doesn't currently support .NET Core 3. It works, but it causes this warning at build time:

> Warning NU1701: Package 'Xamarin.Forms.Platform.WPF 4.3.0.851321-pre3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.0'. This package may not be fully compatible with your project.

As far as I can tell, it is compatible. The problem is just the warning. .NET Core 3 support is quite helpful since it allows use of the corrected dependency management in the new project style, which eliminates dependency like one similar to [this SQLite problem](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1085).

**Comment by jfversluis** [comment]
Hey @breyed thanks for bringing this up!

I think work on this has already been done in #7063, unfortunately, we can't add this yet because we are stuck to using VS2017 build agents for now.

Could you confirm this is what you mean by this change? Thanks

**Comment by breyed** [comment]
Yes, #7063 covers this request. I had only searched issues for an existing item; I didn't think to include PRs in the query. Thanks for pointing out the dup.
