### ISSUE TITLE
[Bug] [iOS] Label size doesn't change when text changed if LabelRenderer reused

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#7888]
### Explain

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/LabelRenderer.cs#L160

> 		protected override void OnElementChanged(ElementChangedEventArgs<Label> e)
>		{
>			_perfectSizeValid = false;
>
>			if (e.OldElement != null)
>			{
>				e.OldElement.PropertyChanging -= ElementPropertyChanging;
>			}
>
>			if (e.NewElement != null)
>			{
>				if (Control == null)
>				{
>					e.NewElement.PropertyChanging += ElementPropertyChanging;
>					SetNativeControl(CreateNativeControl());
>                     .... ....
>			}
>
>			base.OnElementChanged(e);
>		}
>
>		void ElementPropertyChanging(object sender, PropertyChangingEventArgs e)
>		{
>			if (s_perfectSizeSet.Contains(e.PropertyName))
>				_perfectSizeValid = false;
>		}

it only binding PropertyChanging when **Control == null**.
it means when reused this renderer, '_perfectSizeValid' is **NOT** reset when text changed.
as a result, even the text changed, but the size of label is not changed. 
if the empty string at beging (frame.width == 0), and the text will **NOT** shown after set some value!!!

**Comment by jfversluis** [comment]
Hi @bill2004158 thanks for reporting and already pointing out what seems to be the cause.

Would you mind providing us with all the information that has been requested as per the issue template and/or a sample reproduction project of what problem you are encountering?

This will help us determine what is going on exactly much better and faster and therefore hopefully a fix will be implemented sooner because of that.

Thanks!

**Comment by bill2004158** [comment]
@jfversluis , yes, I was trying to create a simple demo project.
however, I am not sure when LabelRenderer will be RE-used for new Label element.

I will try if I can reproduce it in simple demo project.

**Comment by bill2004158** [comment]
[TestLabel.zip](https://github.com/xamarin/Xamarin.Forms/files/3715835/TestLabel.zip)

@jfversluis , I have create a sample reproduction project.
when app start, it will append "." to the display text every 3s,
and you can see the size of lable will increase after text changed,

however, after you click restart button.
it will re-set ItemsSource for the list, 
and it will restart append "." every 3s.
however, the size of label is not changed!!!
