### ISSUE TITLE
[Bug] "Include Asp.net Core Web API project" does not take any effect

### ISSUE THREAD

**Issue by pstricks-fans** [xamarin/Xamarin.Forms#7889]
I created a brand new Xamarin.Form projects with Visual Studio 2019 Community Edition (the latest release 16.3.3).

Here is the step I did.

[![enter image description here][1]][1]

But the solution just contains 4 projects rather than what I expected is 5 projects.

[![enter image description here][2]][2] 

# Question

What causes this issue? I missed something?

  [1]: https://i.stack.imgur.com/Zr0ul.png
  [2]: https://i.stack.imgur.com/anPij.png

**Comment by jfversluis** [comment]
Hey @pstricks-fans, thanks for the report.

I can indeed see this happening on my internal preview version as well (16.4p2). The project _is_ created however on your filesystem. There should be a <projectname>.MobileAppService in the folder where you created the solution, can you confirm that?

You should be able to just add that to the solution manually for now.

**Comment by pstricks-fans** [comment]
@jfversluis : Thank you for responding. Confirmed. There is a folder in my solution for the Web Api.

**Comment by jfversluis** [comment]
I've forwarded the issue to the appropriate team. Hopefully it should be fixed soon :)

**Comment by samiozturk** [comment]
This was closed recently but i have just had the same exact issue. Any updates on a fix?

**Comment by jfversluis** [comment]
Unfortunately, no update yet. This is a templating/IDE issue rather than a Xamarin.Forms issue.

As mentioned earlier, the project is created, but it's not added to the solution. You can easily do that yourself. I understand it is not ideal, but shouldn't be too big an effort to work around.
