### ISSUE TITLE
Move builds to VS2019 build host

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#7894]
For #7063 and possibly more in the future we're going to start to use VS2019 build hosts to make sure we use the latest bits. Because of issues reported in #7602, where we see that NuGet packages created with VS2019 cause problems when used in VS2017, we can't move over to VS2019 build agents right now.

This issue is here to keep track of the progress of moving to VS2019 build hosts and will hold any discussion around that.

_Originally posted by @krdmllr in https://github.com/xamarin/Xamarin.Forms/pull/7063#issuecomment-539739597_

**Comment by samhouts** [comment]
This is actually done, and we did it without breaking 2017 compatibility.
