### ISSUE TITLE
Controls inside a TitleView loose Alignment 

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#7899]
### Description
I have a CustomControl. When I use this CustomControl inside a TitleView, the first time Controls are displayed correctly, then they loose the alignment (Label) or Size (ImageButton)
### Steps to Reproduce

1. 
<?xml version="1.0" encoding="UTF-8" ?>
<ContentView
    x:Class="SapMobility.CustomView.TitleView"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    x:Name="this"
    mc:Ignorable="d">

    <ContentView.Content>
        <Grid BackgroundColor="Black" HorizontalOptions="FillAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
            </Grid.RowDefinitions>

            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="40" />
                <ColumnDefinition Width="*" />
                <ColumnDefinition Width="40" />
            </Grid.ColumnDefinitions>

            <ImageButton
                Grid.Row="0"
                Grid.Column="0"
                BackgroundColor="Black"
                Command="{Binding ImageLeftCommand, Source={x:Reference this}}"
                HorizontalOptions="Center"
                IsVisible="{Binding ImageLeftIsVisible, Source={x:Reference this}}"
                Source="{Binding ImageLeftSource, Source={x:Reference this}}" />

            <Label
                Grid.Row="0"
                Grid.Column="1"
                FontSize="Medium"
                HorizontalTextAlignment="Center"
                Text="{Binding Text, Source={x:Reference this}}"
                TextColor="White"
                VerticalOptions="FillAndExpand"
                VerticalTextAlignment="Center" />

            <ImageButton
                Grid.Row="0"
                Grid.Column="2"
                BackgroundColor="Black"
                Command="{Binding ImageRightCommand, Source={x:Reference this}}"
                HorizontalOptions="Center"
                IsVisible="{Binding ImageRightIsVisible, Source={x:Reference this}}"
                Source="{Binding ImageRightSource, Source={x:Reference this}}" />
        </Grid>
    </ContentView.Content>
</ContentView>

This is the CustomControl I use
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace SapMobility.CustomView
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class TitleView : ContentView
    {

        public static readonly BindableProperty TextProperty = BindableProperty.Create(nameof(Text), typeof(string), typeof(TitleView));

        public static readonly BindableProperty ImageLeftSourceProperty = BindableProperty.Create(nameof(ImageLeftSource), typeof(string), typeof(TitleView));
        public static readonly BindableProperty ImageLeftIsVisibleProperty = BindableProperty.Create(nameof(ImageLeftIsVisible), typeof(bool), typeof(TitleView));
        public static readonly BindableProperty ImageLeftCommandProperty = BindableProperty.Create(nameof(ImageLeftCommand), typeof(Command), typeof(TitleView));

        public static readonly BindableProperty ImageRightSourceProperty = BindableProperty.Create(nameof(ImageRightSource), typeof(string), typeof(TitleView));
        public static readonly BindableProperty ImageRightIsVisibleProperty = BindableProperty.Create(nameof(ImageRightIsVisible), typeof(bool), typeof(TitleView));
        public static readonly BindableProperty ImageRightCommandProperty = BindableProperty.Create(nameof(ImageRightCommand), typeof(Command), typeof(TitleView));

        public string Text
        {
            get
            {
                return (string)GetValue(TextProperty);
            }
            set
            {
                SetValue(TextProperty, value);
            }
        }

        public string ImageLeftSource
        {
            get
            {
                return (string)GetValue(ImageLeftSourceProperty);
            }
            set
            {
                SetValue(ImageLeftSourceProperty, value);
            }
        }

        public string ImageRightSource
        {
            get
            {
                return (string)GetValue(ImageRightSourceProperty);
            }
            set
            {
                SetValue(ImageRightSourceProperty, value);
            }
        }

        public bool ImageLeftIsVisible
        {
            get
            {
                return (bool)GetValue(ImageLeftIsVisibleProperty);
            }
            set
            {
                SetValue(ImageLeftIsVisibleProperty, value);
            }
        }

        public bool ImageRightIsVisible
        {
            get
            {
                return (bool)GetValue(ImageRightIsVisibleProperty);
            }
            set
            {
                SetValue(ImageRightIsVisibleProperty, value);
            }
        }

        public Command ImageLeftCommand
        {
            get
            {
                return (Command)GetValue(ImageLeftCommandProperty);
            }
            set
            {
                SetValue(ImageLeftCommandProperty, value);
            }
        }

        public Command ImageRightCommand
        {
            get
            {
                return (Command)GetValue(ImageRightCommandProperty);
            }
            set
            {
                SetValue(ImageRightCommandProperty, value);
            }
        }

        public TitleView()
        {
            InitializeComponent();
        }
    }
}
```
These are the properties

2. 

This is how I can use the control
```
    <NavigationPage.TitleView>
        <customview:TitleView
            ImageRightCommand="{Binding CancelCommand}"
            ImageRightIsVisible="True"
            ImageRightSource="baseline_close_white_18dp"
            Text="{Binding Titolo}" />
    </NavigationPage.TitleView>
```

I add this control in some pages inside a NavigationStack. In the first page it seems it works ok but when I push a second page it start to works bad. Also with "pop" I have bad visualizations...

### Expected Behavior
This is correct
![image](https://user-images.githubusercontent.com/5759350/66482398-27cfa800-eaa3-11e9-835a-011a0387bb13.png)

![image](https://user-images.githubusercontent.com/5759350/66482445-3f0e9580-eaa3-11e9-9f32-44ffe13f02c0.png)

This is correct
### Actual Behavior

This is wrong
![image](https://user-images.githubusercontent.com/5759350/66482540-741ae800-eaa3-11e9-91ab-78da06956cf7.png)

and this
![image](https://user-images.githubusercontent.com/5759350/66483099-ae38b980-eaa4-11e9-8d1a-78fede756064.png)

and this
![image](https://user-images.githubusercontent.com/5759350/66482809-07ecb400-eaa4-11e9-98f1-b3d249823472.png)

### Basic Information

- Version with issue: 4.2.0.848062
- Last known good version: unknown
- IDE:
- Platform Target Frameworks: 
  - iOS: 
  - Android: 9.0
  - UWP:  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Zebra TC51

**Comment by jfversluis** [comment]
Thanks for reporting @acaliaro, would you be able to add a small reproduction project that shows this issue?

**Comment by acaliaro** [comment]
> Thanks for reporting @acaliaro, would you be able to add a small reproduction project that shows this issue?

I will try...

**Comment by acaliaro** [comment]
I don't know... now it seems to work. I have created a repo but I am not able to reproduce it, but even in the main project now it works ok. I will do some other tests, otherwise I will close the issue.
Bye

**Comment by jfversluis** [comment]
@acaliaro glad to hear it suddenly works. I'd like to change it around; I'll close it for now and whenever you find out why it didn't work and you can add a reproduction project you can reopen it :)

Thanks!
