### ISSUE TITLE
[Bug] CarouselView doesn't implement the defined visual states

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7904]
### Description

In the 4.3 branch, the CarouselView class defines the following visual states:

```
		public const string CurrentItemVisualState = "CurrentItem";
		public const string NextItemVisualState = "NextItem";
		public const string PreviousItemVisualState = "PreviousItem";
		public const string VisibleItemVisualState = "VisibleItem";
		public const string DefaultItemVisualState = "DefaultItem";
```

I spent a couple of hours trying to get the damn things to work and the only one I had success with was the DefaultItem state.

After staring at the code some more I discovered that only the DefaultItem state is implemented, and that's iOS only. The rest aren't implemented at all.

**Comment by jfversluis** [comment]
Whoops, sorry about that @davidbritch! It seems that is indeed not yet implemented...
