### ISSUE TITLE
[Shell, UWP] Cannot prevent flyout menu list from scrolling.

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#7913]
### Description

UWP Shell Implementation of https://github.com/xamarin/Xamarin.Forms/issues/4765

**Comment by MartinZikmund** [comment]
I can try to tackle this

**Comment by PureWeen** [comment]
@MartinZikmund apologies but I just saw your comment. If this is something you still want to work on go for it! Just let me know
