### ISSUE TITLE
[Bug] FontImageSource does not render UTF-32 glyphs from icon fonts

### ISSUE THREAD

**Issue by anotherlab** [xamarin/Xamarin.Forms#7915]
### Description
When using an icon font where the Unicode sequence for a glyph is UTF-32, the image does not render. 
### Steps to Reproduce

1. Create a new Xamarin.Forms app using the Blank template
2. Add a control to the main page that can use a FontImageSource
3. Add an icon font that includes glyphs that are identified with a UTF-32 string instead of a UTF-16 string.  Example used was Material Design Font
4. Set the FontImageSource to use a UTF-32 glyph, example used was "\u000f0143"

### Expected Behavior
The glyph for the specified string would be rendered

### Actual Behavior
No image and part of the UTF-32 text is output

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.848062
- Last known good version:
- IDE: Visual Studio 2019, version 16.3.3
- Platform Target Frameworks:
  - iOS:  Not tested
  - Android: Android 9, API 28
  - UWP:  Not tested
- Android Support Library Version: N/A
- Nuget Packages:
    Xamarin.Forms, Version 4.2.0.848062
   Xamarin.Essentials Version 1.3.1
- Affected Devices: Any

### Screenshots
![Missing icon shown](https://raw.githubusercontent.com/anotherlab/FontImageUtf32/master/screenshots/demo.png)

### Reproduction Link
[repo](https://github.com/anotherlab/FontImageUtf32)

[FontImageUtf32-master.zip](https://github.com/xamarin/Xamarin.Forms/files/3713088/FontImageUtf32-master.zip)

**Comment by jfversluis** [comment]
Thanks for reporting this @anotherlab! From a first glance looks like we only parse the first amount of characters, since there are a couple of the UTF-32 code are shown on screen.

Unfortunately, the link to the repro isn't accessible for me. Would you be able to attach it to this issue directly? That way we are also ensured to not lose it.

Thanks!

**Comment by anotherlab** [comment]
Whoops, cut and pate typo.  I updated the repo link, it goes to the same project now.

**Comment by jfversluis** [comment]
Apparently this is not something we can fix but a "limitation" of C#. See this [StackOverflow answer](https://stackoverflow.com/a/44758841/1506387) for example.

When I rewrite it to convert from UTF-32, it starts working

![Screenshot 2019-10-14 at 14 20 23](https://user-images.githubusercontent.com/939291/66750845-d69e2a80-ee8d-11e9-9b5c-8048a6c3ef6c.png)
