### ISSUE TITLE
[Bug] Can't prevent bounce in iOS

### ISSUE THREAD

**Issue by westermost** [xamarin/Xamarin.Forms#7917]
### Description
I trying to prevent bounce with webview in iOS but it not effects

[assembly: ExportRenderer(typeof(ScrollView), typeof(NoBounceScrollViewRenderer))]
public class NoBounceScrollViewRenderer : ScrollViewRenderer
{
 
    protected override void OnElementChanged(VisualElementChangedEventArgs e)
    {
        base.OnElementChanged(e);
        UpdateScrollView();
    }
 
    private void UpdateScrollView()
    {
        ContentInset = new UIKit.UIEdgeInsets(0, 0, 0, 0);
        if (UIDevice.CurrentDevice.CheckSystemVersion(11, 0))
            ContentInsetAdjustmentBehavior = UIKit.UIScrollViewContentInsetAdjustmentBehavior.Never;
        Bounces = false;
        ScrollIndicatorInsets = new UIKit.UIEdgeInsets(0, 0, 0, 0);
    }
}

**Comment by jfversluis** [comment]
Hi @westermost, would you mind adding a small reproduction project with this code so we can have a look?

On a side-note: while we don't mind having a look for you, these type of questions, you'll probably have a faster result if you ask it on the Xamarin Forums or a website like StackOverflow. 

Thanks!

**Comment by adrianknight89** [comment]
@westermost Are you wrapping a `WebView` with a `ScrollView`? Even if you prevent bouncing in `ScrollView`, you might see the inherent HTML scrollview bounce instead. In general, you shouldn't combine the two together. I agree that a repro should be attached.

**Comment by samhouts** [comment]
@westermost  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@westermost  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
