### ISSUE TITLE
[Bug] UWP: SwitchRenderer crashes with System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by justremotephone** [xamarin/Xamarin.Forms#7926]
After updating to Xamarin.Forms 4.2 our UWP app crashes while opening one of our pages where we have placed an Switch element.

The stack trace is:

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.UpdateThumbColor()
   at Xamarin.Forms.Platform.UWP.SwitchRenderer.OnControlLoaded(Object sender, RoutedEventArgs e)

I have done some further investigations and I have found that within the SwitchRenderer ther is some new code:
...
		void UpdateThumbColor()
		{
			if (Control == null)
				return;

			var grid = GetFirstDescendant<Windows.UI.Xaml.Controls.Grid>(this.Control);

			if (grid == null)
				return;

			ObjectKeyFrame frame = Windows.UI.Xaml.VisualStateManager.GetVisualStateGroups(grid)
				.First(g => g.Name == "CommonStates")
				.States.First(s => s.Name == "PointerOver")
				.Storyboard.Children.OfType<ObjectAnimationUsingKeyFrames>().First(
					t => Storyboard.GetTargetName(t) == "SwitchKnobOn" &&
						 Storyboard.GetTargetProperty(t) == "Fill")
				.KeyFrames.First();
.....

Here the StoryBoards for CommonStates->PointerOver are found but there does not exist a StoryBoard with "SwitchKnopOn and "Fill": so the .First extension fails.

I do not known why this is missing on my system or on the environment I am working on. But your code should be made robust against this problem. 

See your implementation of UpdateOnColor some lines above of your new UpdateThumbColor: The implementation of UpdateOnColor does not crash if some story boards are not found....

In general, your code us ugly! String constants.... used everywhere. Hopefully this will not break with further Windows releases....

I hope this helps
Regards,
Thomas.

**Comment by jfversluis** [comment]
Hi @justremotephone, thank you for the report!

I'm sorry to hear you have trouble using the latest version of Xamarin.Forms. It would greatly help us speed up the fix for this issue if you could add a reproduction project that shows this issue. Is that something you would be able to do?

Thanks!

**Comment by justremotephone** [comment]
Hello,

wow... you are fast! 

I am on Windows 10 1903 (18362.418). Unfortunately I can not give you a sample project because I have not tried if the problem can be reproduced for a small sample. 

But I have reviewed your fix and it should work!

If you really need some further details please ask, I would see If I could get more time for finding out some more information.

Thanks!

Regards,
Thomas.

**Comment by samhouts** [comment]
closed by #7932
