### ISSUE TITLE
[Bug] [UWP] Mouse wheel does not scroll in ScrollView with ScrollOrientation.Both

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#7927]
Scrolling via mouse wheel works in ScrollViews with `Orientation = ScrollOrientation.Vertical` but not with `Orientation = ScrollOrientation.Both`.

- Platform Target Frameworks:
  - iOS:  untested
  - Android: untested
  - UWP:  18362
- Xamarin.Forms version: 4.2.0.848062

@AxelUser

**Comment by jfversluis** [comment]
Hi @charlesroddie, thanks for this issue.

Would you mind adding a bit more to this? Preferably while using the issue template. 
The biggest question that comes to mind is; what would you want it to do? Just scroll vertical anyway? That would make sense. But I can't tell from your description.

**Comment by charlesroddie** [comment]
> The biggest question that comes to mind is; what would you want it to do? Just scroll vertical anyway? 

Yes expected behaviour is to scroll vertially when using the mouse wheel with ScrollOrientation.Both.

**Comment by jfversluis** [comment]
I've tried to reproduce this with a simple project, but I seem unable to. Scrolling seems to just work.

Could you maybe add a reproduction project showing this problem? Thanks!

**Comment by charlesroddie** [comment]
This appears to be our error, having stacked scrollviews by mistake.
@jfversluis Thanks for looking into this and sorry for taking your time.
