### ISSUE TITLE
[Bug] [UWP] [CollectionView] Navigating back within the SelectionChanged handler throws exception

### ISSUE THREAD

**Issue by tomstreet** [xamarin/Xamarin.Forms#7928]
### Description
When calling `Navigation.PopAsync()` from within the `SelectionChanged` event handler, the following NullReferenceException is thrown:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Platform.UWP.SelectableItemsViewRenderer.OnNativeSelectionChanged(Object sender, SelectionChangedEventArgs e)
```

Possibly related/similar to #3333?

Tested in iOS and Android and works as expected.

### Steps to Reproduce

1. Add a CollectionView to a page that navigates back in the `SelectionChanged` handler
2. Navigate to the page with the CollectionView on
2. Select an item in the CollectionView

### Expected Behavior
I expected this to just navigate back to the previous page.

### Actual Behavior
Boom! NullReferenceException!

### Basic Information
- Version with issue: all of 4.2.0.x and 4.3.0.x
- Last known good version: ??
- IDE: VS2019 v16.3.3
- Platform Target Frameworks: 
  - UWP:  17763

### Reproduction Link
[CollectionViewBackTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3712830/CollectionViewBackTest.zip)

**Comment by jfversluis** [comment]
Hey @tomstreet, looking at this issue it seems this is fixed for me when I update to 4.3-pre3. Could you confirm that is the case for you as well?

**Comment by tomstreet** [comment]
Oh yeh my bad - I was sure I tried it with 4.3-pre3 - works as expected.

**Comment by jfversluis** [comment]
Thanks!
