### ISSUE TITLE
Native Barcode Scanning Ios ,Andriod

### ISSUE THREAD

**Issue by davidbuckleyni** [xamarin/Xamarin.Forms#7934]
While there is the zxing libary it is no longer maintained and would be good if Xamrian had an internal method of barcode scanning.

You would need several view compenets such as 

iOS: Xamarin.Forms.ScannerView (UIView) - See Xamarin.Forms.ScannerViewController.cs View Controller for an example of how to use this view
iOS: Xamarin.Forms.AVCaptureScannerView (UIView) - This is API equivalent to Xamarin.Forms.ScannerView, but uses Apple's AVCaptureSession Metadata engine to scan the barcodes instead of 
Android: Xamarin.Forms.ZXingScannerFragment (Fragment) - See ZXingActivity.cs Activity 

Thee should also be the ability to add custom overlays to the scanner areas on all devices.
IE Custom Buttons.
Barcode Formats that should be supported:
Aztec
Code 128
Code 39
Code 93
EAN13
EAN8
PDF417
QR
UPC-E

Features
Xamarin.iOS
Xamarin.Android (Including Google Glass)

**Comment by dansiegel** [comment]
Is it that it’s no longer maintained or that it’s just stable? My thought is that it should generally be stable. 
cc: @Redth

**Comment by RhomGit** [comment]
Thread asking for a refresh release is here:
https://github.com/Redth/ZXing.Net.Mobile/issues/780

**Comment by jfversluis** [comment]
I think @Redth is busy with an overhaul of the barcode scanner plugin. The current one still has its use for sure, but also seems to have some quirks. Seeing that we might also be taking in the MediaElement for instance, it might be worth considering making this a first-party control as well.

**Comment by Redth** [comment]
I’m open to ideas. I started a major rewrite of it as it hasn’t aged so well and there’s a lot of things learned from the first implementation. I paused for now until camerax is stable from google and can be used to implement the camera bits on android. I’m open to ideas for turning it into a first party control.

**Comment by jfversluis** [comment]
I was already thinking of drafting up a spec around this. But maybe if you already have something or want to incorporate your learnings maybe that is something you could do? Or, I'm happy to do it, but if you could provide me with some input? I'll ping you on Slack to have a little chat about it.

**Comment by acaliaro** [comment]
I think should be very interesting trying to add other features like text recognition...

**Comment by davidbuckleyni** [comment]
Yes that would be great esp like of business cards and credit cards.

**Comment by lazmeister** [comment]
Would love to see this happen!

**Comment by davidbuckleyni** [comment]
@lazmeister  I agree zxing is a good library but needs maintained more if it was in as a standard in xarmain would make our lives easier. I had some issues such as double scanning that i managed to solve with delay scan property but would be good that it was fully documented etc.

**Comment by Robbert-jansen** [comment]
Yes please, the current version of ZXing has many issues, issues that make it almost impossible to use in my projects.

A first party alternative would be fantastic.

**Comment by davidbuckleyni** [comment]
Haven’t look at this in ages glad to see it’s getting allot of traction end of day barcode scanning are native functions and used for 100% of business apps if xammy did this we love them for ever I am original poster of above

**Comment by SmartmanApps** [comment]
I agree with @Robbert-jansen - I've been using ZXing, but it randomly crashes on Android (seems to be OK on UWP). Had discussion with @jfversluis but we didn't find a resolution. I'm keenly looking forward to ZXing rewrite, or preferably a 1st party solution.

**Comment by MattVon** [comment]
Zxing is a nightmare at times, would totally love native support in Xamarin. @SmartmanApps, what sort of crashes have you experienced?

**Comment by SmartmanApps** [comment]
Hey @MattVon thanks for asking. Usually after several scans the phone's camera would crash - not just my app, the camera app itself! The only way to get it working again was to reboot the phone. Obviously this can't go into a production app, which is why I'm so keen for a new/updated version. This happened on at least 2 different phones (but both running Marshmallow 6.0.1).

The first culprit was a message saying "X frames skipped. The UI thread is doing too much work",but long story short (e.g. playing around with scanning options), even though it sounds like an issue when under load (i.e. rapid scans), at least once it crashed on my very first scan, so not that, and there were other messages that could be the real culprit also, so the "X frames skipped" may or may not be a red herring. As I said, had some conversations with @jfversluis (since he did a stream about ZXing), but we never solved it, and then he told me @Redth was working on a new version, so I stuck it on the backburner and am awaiting that.

Donald.

**Comment by PaulVrugt** [comment]
It would be fantastic if this was created. We have been using Redth's ZXing implementation in our apps until now, since it is the only QR code implementation for XF that "sort of" works, but this code seems no longer to be maintained. We had to fork the project and make some changes to make it work at all, and some issues still exist.

**Comment by knocte** [comment]
> We had to fork the project and make some changes to make it work at all,

My team has also needed to fork the project because of upstream inactivity. However, all the fixes we are using have been proposed as PRs. Can you propose your changes as well as PRs to upstream at least to make them visible please?

> and some issues still exist.

Please also report issues that are not reported yet.

**Comment by PaulVrugt** [comment]
@knocte the fixes we did were actually already approved via pull request I made, but a version with the fixes was never released on Nuget. The issues we still run into are already existing open issues

**Comment by lazmeister** [comment]
@Redth Anyway to review those PRs for the time being? There are about 21 Open ones  https://github.com/Redth/ZXing.Net.Mobile/pulls

**Comment by ahmedalejo** [comment]
This is something for https://github.com/xamarin/Essentials instead

**Comment by lazmeister** [comment]
@ahmedalejo Agreed. Either way Xamarin needs this ability.

**Comment by davidbuckleyni** [comment]
Oh we got a feature label folks :-) that’s a good sign :-)

**Comment by davidbuckleyni** [comment]
That is not the same the project mentioned above is about taking photos not barcodes.

**Comment by davidbuckleyni** [comment]
We have had a feature label added folks that means it’s a strong possibility that this will now happen.

**Comment by Phenek** [comment]
Hello @davidbuckleyni,

Has you can see CameraView is already in progress.
When it will be done, we will be able to consume the live preview stream a in our code.
This would enable us to stream the data to barcode detectors, face recognizers, etc.

Did you get it? It will be this first pillar of your Barcode recognition!

Even more you should be able at first to use native bar code scanning with a custom renderer.
And return your result to Xamarin.Forms!

Regards,

**Comment by davidbuckleyni** [comment]
> Hello @davidbuckleyni,
> 
> 
> 
> Has you can see CameraView is already in progress.
> 
> When it will be done, we will be able to consume the live preview stream a in our code.
> 
> This would enable us to stream the data to barcode detectors, face recognizers, etc.
> 
> 
> 
> Did you get it? It will be this first pillar of your Barcode recognition!
> 
> 
> 
> Even more you should be able at first to use native bar code scanning with a custom renderer.
> 
> And return your result to Xamarin.Forms!
> 
> 
> 
> Regards,
> 
> 

That is not the point of this to have a custom render the scan works differently in zxing and provides specialists components for accessing the scan two totally different things

**Comment by Phenek** [comment]
Yep, I understand you want the final product.
Be patient, it will come thereafter

**Comment by sarthak1995-26** [comment]
https://www.leadtools.com/sdk/xamarin/camera they achieved this somehow.But kind of costly right now

**Comment by davidbuckleyni** [comment]
> This is something for https://github.com/xamarin/Essentials instead

Not really we don't want Xamarin Essentials to get bloated, not every app requires scanning abilities and that is what Xamarin Essentials trys to keep to things that all apps require.

**Comment by Softtinn** [comment]
Any more info on this?

**Comment by davidbuckleyni** [comment]
> This is something for https://github.com/xamarin/Essentials instead

Not really its more for community toolkit. Essentials is a quick library's that doesnt provide things like this more helpers

**Comment by davidbuckleyni** [comment]
It seems redth has made a new maui coMpatable reader folks.

**Comment by PaulVrugt** [comment]
@davidbuckleyni could you elaborate?

**Comment by jfversluis** [comment]
There is some work going on here: https://github.com/Redth/BigIslandBarcoding

I don't want to get anyones hopes up, but we might have a good place for it and we're currently working out the details :)

Having that said, I will close this one because this will definitely not go into Forms anymore and I doubt it will be in .NET MAUI as a first-party control. We're working on it :)
