### ISSUE TITLE
[Bug] Picker on iOS rendered as inputView, not inline like native default on iOS

### ISSUE THREAD

**Issue by sventropy** [xamarin/Xamarin.Forms#7935]
### Description

The `Picker` control in Xamarin.Forms is rendering as a TextBox, bringing up a picker keyboard on tap ([docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/)). When defining a Picker natively in iOS (either `Picker` in SwiftUI or `UIPickerView` in UIKit), the picker itself is rendered in-place in the view. This mismatch requires custom rendering to comply with the native platform behavior, knowing that Apple's Human Interface Guidelines allow both.

### Steps to Reproduce

1. Create an empty Xamarin.Forms project
2. Create a Picker control with a couple of items on the `MainPage`
3. Run application and compare rendered Picker with default iOS Picker

### Expected Behavior

The Picker is rendered at the bottom of the screen in a keyboard/popover view.

### Actual Behavior

The Picker should be rendered inline.

### Basic Information

- Version with issue: 4.2.0.848062
- Last known good version: /
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS: 13.1
- Affected Devices: IPhone 11

### Screenshots

Rendering using Xamarin.Forms:
![Simulator Screen Shot - iPhone 11 - 2019-10-10 at 23 14 51](https://user-images.githubusercontent.com/1979426/66607815-5dfd4c80-ebb5-11e9-946e-a4cd179ababb.png)

Rendering using iOS SDK (here SwiftUI, but its the same using `UIPickerView` in UIKit.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-10 at 23 14 59](https://user-images.githubusercontent.com/1979426/66607889-7d947500-ebb5-11e9-8675-8795b7590b58.png)

### Reproduction Link

https://github.com/sventropy/XamarinForms-Picker-UI-Repro

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
