### ISSUE TITLE
Add Tizen Platform when creating new Project

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7936]
Hi,

Please add Tizen project when creating new Xamarin Forms project where it asks to select iOS, Android and UWP

Because Tizen is also a platform and it's very popular so why do we need to do it through extensions?

It will be easier to add all platforms there and Visual Studio will do the rest

especially that setting Tizen as per this link 

[https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen](https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen)

is a pain and it will be great if Visual Studio can do it with just selecting the platform upo creating the project

this is the screen where Tizen should be:

![image](https://user-images.githubusercontent.com/6236241/66616758-21e0e080-ebe3-11e9-98f8-a3fd9ef37f67.png)

Thanks,
Jassim

**Comment by jfversluis** [comment]
Hi @jrahma, thank you for bringing this up!

While I do love your support for the Tizen platform, I'm not sure this will happen anytime soon. A you can see in the [platform support page](https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support) the platforms that are listed right now are the platforms that we as Microsoft support. The rest of the platforms are either supported through third-parties or the community. That is why you need to use a plugin or add project manually.

**Comment by rookiejava** [comment]
Hi @jrahma. thank you for your interest in Tizen.  Your interest and feedback is really great for us. :)

I totally agree with the issues you pointed out and we are internally preparing a brand new tizen project template extension for better experience. This extension will be published to the VisualStudio Marketplace. I'll announce as soon as we're ready. 

Thank you again.

**Comment by jrahma** [comment]
That's Great. Thank you

**Comment by jrahma** [comment]
@rookiejava That's Great. Thank you

**Comment by rookiejava** [comment]
Hey @jrahma, 

Thanks for the long wait. Today I am very happy to introduce you to our brand new template system. This is super easy and convenient to create Galaxy Watch app by using Xamarin.Forms. 

No more simple hello world template! No more google to find how to use Tizen device APIs!

Go check it out! 😉 
https://marketplace.visualstudio.com/items?itemName=tizen.Tailor
