### ISSUE TITLE
[Bug] [Shell] Android 10 App Crash When Changing Theme

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#7939]
### Description

When app is running and I am using Shell and i pull down the settings from the top of my Pixel 2XL and change theme to dark mode or to light mode then the app crashes

### Steps to Reproduce

^ File -> New Shell App
Change theme when running.

### Expected Behavior

Should change theme

### Actual Behavior

Crash :(

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019 16.3.3
- Platform Target Frameworks:
  - Android: 10 or 9
- Android Support Library Version: 28.0.0.3
- Nuget Packages: 4.2 (latest) and 4.3-pre3
- Affected Devices: Pixel 2XL

Crash Logs
https://gist.github.com/jamesmontemagno/ed5b3a3fbed541aa14a9003514e8ba57

I have confirmed that it only happens with shell. Other apps seem to be okay.

**Comment by jfversluis** [comment]
Confirmed this is happening, iOS is fine
