### ISSUE TITLE
[Enhancement] VisualElement.IsFocused make bindable

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#7944]
## Summary
I think that it would be nice to make VisualElement.IsFocused - Bindable. It’s very convenient from ViewModel to send focus to some text field, or to pick focus.

## API Changes

``` cs
VisualElement.IsFocused {get;set;}
```

**Comment by jfversluis** [comment]
Seems like the PR was already closed as the property was already bindable but read-only because of reasons... Thanks for the suggestion! If you'd still like to see something improved in this area, please open a feature request on the .NET MAUI repo!
