### ISSUE TITLE
[Bug] BackgroundImageSource property in ContentPage

### ISSUE THREAD

**Issue by eincioch** [xamarin/Xamarin.Forms#7952]
Add a png image, as a background on my page, with the BackgroundImageSource property->

![image](https://user-images.githubusercontent.com/12565944/66659089-6632a780-ec08-11e9-9866-a67ce0c830de.png)

### Description
And as you can see in the following attached image, it leaves a black margin, it does not extend throughout the page.

![capture20191010095931224](https://user-images.githubusercontent.com/12565944/66659290-d6412d80-ec08-11e9-8d4e-24111e53ce61.png)

### Steps to Reproduce

1. add, Background ImageSource property with png file.
2. It does not fill the entire bottom of the page.
3. does not exist, Image Aspect = "AspectFill"

### Expected Behavior
The expected behavior is that the png image covers the entire edge of the page.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.848062
- Last known good version:
- IDE: Visual Studio Enterprise 2019
- Nuget Packages: https://www.nuget.org/packages/Xamarin.Forms/4.2.0.848062

**Comment by jfversluis** [comment]
Hi @eincioch, I've tried to create a reproduction myself since you didn't add one. But I can't seem to be able to match this behavior.

Would you mind adding a reproduction project that shows this?

Thanks!

**Comment by eincioch** [comment]
the problem was because of the image I used, the company's marketing design, but it was already solved

**Comment by jfversluis** [comment]
Great to hear! Thank you for letting us know
