### ISSUE TITLE
[Bug] DisplayAlert should be DisplayAlertAsync

### ISSUE THREAD

**Issue by hassanhabib** [xamarin/Xamarin.Forms#7957]
Current code for DisplayAlert doesn't follow the language best practices.
Here's an example:
public Task<bool> DisplayAlert(string title, string message, string accept, string cancel)
		{
			if (string.IsNullOrEmpty(cancel))
				throw new ArgumentNullException("cancel");

			var args = new AlertArguments(title, message, accept, cancel);
			if (IsPlatformEnabled)
				MessagingCenter.Send(this, AlertSignalName, args);
			else
				_pendingActions.Add(() => MessagingCenter.Send(this, AlertSignalName, args));

			return args.Result.Task;
		}

Asynchronous methods should be trailed with Async.

**Comment by hartez** [comment]
You are correct that the name probably should have been `DisplayAlertAsync`. But the method is part of the public API; renaming it would be a breaking change. So I'm afraid we're stuck with `DisplayAlert` for the time being.

**Comment by adrianknight89** [comment]
I'm in favor of making existing methods obsolete and providing the new names, but this reminded me of an old request I made: https://github.com/xamarin/Xamarin.Forms/issues/2941

**Comment by hartez** [comment]
That's one option. The catch is that we'd look like we were following the pattern of "async methods have the async suffix and synchronous methods don't have a suffix"; but the method that _looks_ synchronous (`DisplayAlert`) is actually async. Which would also surprise new users. 

Maybe at some point in the future we'll have an opportunity to make a clean break or a whole new alert/dialog API, at which point we can better align our names with the conventions.

**Comment by samrgc** [comment]
It should not use a bug tag.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
