### ISSUE TITLE
[Bug] WPF frame padding, shadow missing

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#7963]
###Description

Frame on WPF is missing Shadow and Padding is not applied.
Similar to #7839 

### Steps to Reproduce

1. Create frame with some content
```
new Frame()
{
   HasShadow = true,
   Margin = 10,
   HeightRequest = 100,
   Content = new Label { Text = "Frame with shadow" }
}
```

### Expected Behavior

Shadow is visible, Content has the default padding of 20.

See android for reference:
![image](https://user-images.githubusercontent.com/11095003/66705089-a2f2c180-ed22-11e9-831f-9de8d41587c3.png)

### Actual Behavior

Shadow not visible, content does not have padding.
![image](https://user-images.githubusercontent.com/11095003/66705099-b3a33780-ed22-11e9-8b3c-b26fce524298.png)

### Basic Information

- Version with issue: 4.3.0
- Last known good version: none
- IDE: VS2019
- Platform Target Frameworks:  
  - WPF 
- Nuget Packages: build from source

### Screenshots

See actual behavior

### Reproduction Link

See steps to reproduce

**Comment by jfversluis** [comment]
Seems like this was never implemented, now there is a PR to do that!

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
