### ISSUE TITLE
[BUG] CollectionView group header location does not update when dynamically inserting items

### ISSUE THREAD

**Issue by PhilippCh** [xamarin/Xamarin.Forms#7965]
### Description
When creating items dynamically for a CollectionView with grouping enabled, the location of the headers does not update according to the list's sizes. The lists seem to properly position themselves, but the headers stay aligned at the top.

### Layout
```
<?xml version="1.0" encoding="utf-8"?>

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:views="clr-namespace:motiseed.Views;assembly=motiseed"
             mc:Ignorable="d"
             x:Class="motiseed.MainPage"
             x:Name="Page"
             BindingContext="{Binding TaskList, Source={StaticResource Locator}}">
    <StackLayout>
        <Entry Completed="OnAddTask" />
        <CollectionView x:Name="TaskList" IsGrouped="True">
            <CollectionView.GroupHeaderTemplate>
                <DataTemplate>
                    <ContentView>
                        <Label Text="{Binding Name}"
                               Margin="10, 10, 10, 10"
                               FontSize="Large"
                               FontAttributes="Bold" />
                    </ContentView>
                </DataTemplate>
            </CollectionView.GroupHeaderTemplate>
            <CollectionView.GroupFooterTemplate>
                <DataTemplate>
                    <Label Text="{Binding Name}" HeightRequest="0"/>
                </DataTemplate>
            </CollectionView.GroupFooterTemplate>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <StackLayout Orientation="Horizontal" HeightRequest="50">
                        <CheckBox BindingContext="{Binding .}" IsChecked="{Binding IsDone}}"
                                  CheckedChanged="OnTaskCompletionChanged" />
                        <Label Text="{Binding Name}" />
                    </StackLayout>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </StackLayout>
</ContentPage>
```

### Steps to Reproduce

1. Use the provided layout.
2. Add at least two groups (statically at startup) and multiple items to the collection dynamically.
3. Observe the behavior.

### Expected Behavior
Group headers should be properly positioned within the CollectionView.

### Actual Behavior
Group headers remain stacked at the top of the CollectionView.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: -
- IDE: Visual Studio for Mac or Visual Studio 2019 for Windows
- Platform Target Frameworks: 
  - iOS: 13.0
- Nuget Packages: No additional packages
- Affected Devices: Simulator and iPhone 8 with iOS 13.2

### Screenshots
https://imgur.com/JMKyGed
https://imgur.com/Jtg75vQ
https://imgur.com/lFMuyB4

**Comment by kingces95** [comment]
Would you mind attaching the reproduction solution/project to the bug. Thanks!

**Comment by samhouts** [comment]
@PhilippCh  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
