### ISSUE TITLE
[Bug] iOS Picker BackroundColor is ignored

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#7967]
### Description

Setting the BackgroundColor property on a picker control has no effect on iOS 13.

### Steps to Reproduce

1. Place a picker control 
2. Set the BackgroundColor property 

### Expected Behavior

BackgroundColor does change the actual background color

### Actual Behavior

System background color (depending on Dark mode or not) is used

### Basic Information

- Version with issue: 4.2
- Last known good version: -
- IDE: VS4Mac
- Platform Target Frameworks: 
  - iOS:  13

**Comment by jfversluis** [comment]
Hi @Sebastian1989101, thanks for the report!

Unfortunately, I don't see this happening. With or without Dark Mode enabled. See the screenshot below showing 4.2 latest installed and a picker with a red background.

![image](https://user-images.githubusercontent.com/939291/66733939-890bc880-ee61-11e9-95c7-ec8bee287c73.png)

I've added my reproduction project [here](https://github.com/xamarin/Xamarin.Forms/files/3723305/Repro7967.zip), could you please try that out and maybe incorporate that changes that make you see this issue and post that back?

Thanks!

**Comment by samhouts** [comment]
@Sebastian1989101  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
