### ISSUE TITLE
[Bug] "Go to definition" option does not work with MergedDictionaries

### ISSUE THREAD

**Issue by monetelli** [xamarin/Xamarin.Forms#7980]
### Description
I cannot use this option in my style library, it may be due to the implementation of "MergedDictionaries".

### Basic Information
- Version with issue: Xamarin.Forms 4.2.0.848062
- IDE: Visual Studio Enterprise 2019

### Screenshots
<img alt="react-native-gifted-chat" src="https://raw.githubusercontent.com/monetelli/XF_FoodApp/master/ImagesBug/BUG-GoToDefinition.gif" width="560" height="350" /></a>

### Reproduction Link
https://github.com/monetelli/XF_FoodApp

**Comment by mgoertz-msft** [comment]
Thanks. I created a bug for it in the VS repo: Bug 1001715: [xamarin/Xamarin.Forms] [Bug] "Go to definition" option does not work with MergedDictionaries (#7980)
