### ISSUE TITLE
NavigationPage.TitleView for PushModalAsync

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#7989]
Hi,

It will be great if you add **NavigationPage.TitleView** for PushModalAsync because Title is needed and required for any page, PushAsync or PushModalAsync

It doesn't make sense not to have the NavigationPage.TitleView for PushModalAsync and make user draw the title using Grid's Rows

Hope this will be available soon..

Thanks,
Jassim

**Comment by shanranm** [comment]
TitleView is attached property of NavigationPage. 
PushAsync also doesnt show TitleView if its not inside a NavigationPage.

**Comment by jrahma** [comment]
Every page should have an option to have or not to have a title and Modal pages are not exceptions no matter what is the reason for not having

HAving the developer to draw the title using Grids or Stacklayout shows that there is something missing in Xamarin Forms and there is a space for improvement

**Comment by shanranm** [comment]
I like it! Ideas' simple a page should handle it own title view!

**Comment by Thanghand** [comment]
You can wrap your page inside NavigationPage 
var page = new NavigationPage(new TestPage()); 
await Navigation.PushModalAsync(page);

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
