### ISSUE TITLE
[XAMARIN-FORMS-WPF] StackOverFlowException throws when added a custom Layout<View> as content of ScrollView

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#7990]
### Description
Greetings,

We at Syncfusion have started implementation for providing support in Xamarin.Forms WPF platform for our controls. We have noticed that when a simple custom Layout<View> is added as a content for ScrollView, it throws with StackOverFlowException, while the same structure works well and good in all other platforms. We have attached a simple sample showcasing the issue. Can you please provide us with any solution or workaround to overcome this issue as soon as possible?

### Steps to Reproduce

1. Run the attached sample in WPF platform.
Note that the app crashes with StackOverFlow exception.

### Expected Behavior
The app should not have any crashes and should render the view as expected.
### Actual Behavior
App crashes with StackOverFlow exception.
### Basic Information

- Version with issue: Latest
- Last known good version: None
- Platform Target Frameworks:
WPF

### Reproduction Link
[WPFIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3723057/WPFIssue.zip)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/66957420-eb033400-f001-11e9-8284-7a72242e7d07.png)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
