### ISSUE TITLE
[Bug] CollectionView.Scrolled event offset isn't correctly reset when items change

### ISSUE THREAD

**Issue by kimbirkelund** [xamarin/Xamarin.Forms#7993]
### Description

When changing the contents of the `CollectionView.ItemsSource` while scrolled down into the list, the `ItemsViewScrolledEventArgs.VerticalOffset` is correctly updated.

### Steps to Reproduce

1. Run attached project
2. Press the Fill button 
3. Scroll in the list (notice the VerticalOffset label updates to show position)
4. Press Empty button
5. Repeat from 2 at you leasure

### Expected Behavior

The value of VerticalOffset should be reset, when pressing Empty, to reflect that the view is no longer scrolled - or at least, as is the case on iOS, the value should be reset the next time scrolling is performed. I'd prefer the former.

### Actual Behavior

The value of VerticalOffset on Android keeps incrementing and never returns to 0. On iOS it returns to zero the next time scrolling is performed.

### Basic Information

- Version with issue: 4.3.0.851321-pre3
- Last known good version: none

### Screenshots

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/jXb4-M_4QlI/0.jpg)](https://www.youtube.com/watch?v=jXb4-M_4QlI)

### Reproduction Link

[App6.zip](https://github.com/xamarin/Xamarin.Forms/files/3723705/App6.zip)

**Comment by adrianknight89** [comment]
I knew this was going to come up at some point. :) See #8018.

**Comment by taublast** [comment]
I'm at forms 4.7 and after i refresh collectionView inside a RefreshView i can't never get scrollOffset 0 anymore, it gets a minimum Y offset of some random stuff around 6-9, might be due to refreshview... 
Anyone?..

**Comment by taublast** [comment]
Forms 4.7, collectionView gets correct VerticalOffset in OnScrolled event received, after i once refresh the collectionView being inside RefresfView it visually resets ok to zero, but the VerticalOffset in OnScrolled event received is not correct anymore, the minumum it gets is around 6-9. 
The position on screen is well 0, but this 0 is reported as a non-zero positive value, the internal calculation might be bugged.

**Comment by JariKuipers** [comment]
Forms 4.8, this issue is still the case on Android. ScrollTo() and changing the ItemSource cause incorrect offsets. Both for HorizontalOffset and VerticalOffset.

**Comment by tonyfonager** [comment]
And I can confirm on XF 5.0.0.1874 (Android) this is still an issue!

**Comment by Cfun1** [comment]
@PureWeen I can confirm the issue with wrong scroll offset still happening when adding and then removing the same items

**Comment by valentasm1** [comment]
I think it is related to https://github.com/xamarin/Xamarin.Forms/issues/10966
