### ISSUE TITLE
[Bug] CarouselView VisibleViews property is always null

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#7997]
### Description

In a `CarouselView` the `VisibleViews` property is always `null`. This is because there's no code in the 4.3 branch that ever sets the property.

**Comment by Saratsin** [comment]
I think problem is here: https://github.com/xamarin/Xamarin.Forms/blob/efb4779bc2dd119a87e375ee4a9f7efe94abba4f/Xamarin.Forms.Platform.Android/CollectionView/CarouselViewRenderer.cs#L285

I guess it should be reverted like this:
```
foreach (var itemView in newViews)
{
    if (_oldViews.Contains(itemView)
    {
    ....
```
Want side opinion can it be the issue
