### ISSUE TITLE
[Bug] CarouselView layout inconsistent across platforms for NumberOfSideItems=1

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8000]
### Description

I want to produce a CarouselView that (1) has multiple items on a page at once, and (2) left aligns on the page at all times. Here's my code:

```
        <CarouselView ItemsSource="{Binding Monkeys}"
                      NumberOfSideItems="1">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <StackLayout>
                        <Frame HasShadow="True"
                               BorderColor="DarkGray"
                               CornerRadius="5"
                               Margin="10">
                            <Image Source="{Binding ImageUrl}" 
                                   Aspect="AspectFill"
                                   HeightRequest="100"
                                   WidthRequest="100"/>
                        </Frame>
                    </StackLayout>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
```

Unfortunately this code produces different layouts on iOS and Android.

iOS:

First item is centre aligned by default, and there are two items on screen:

![Simulator Screen Shot - iPhone X - 2019-10-14 at 15 34 39](https://user-images.githubusercontent.com/8092460/66760777-ae68f880-ee9a-11e9-86ea-650cba5b08fa.png)

I guess iOS is reserving space for a left adjacent item that doesn't exist when the items are first drawn.

However, scrolling does move the items over to the left:

![Simulator Screen Shot - iPhone X - 2019-10-14 at 15 34 44](https://user-images.githubusercontent.com/8092460/66760823-c0e33200-ee9a-11e9-933e-2a65d0893427.png)

I've tried to cajole the initial layout to left align the first item, but not had any luck.

Android:

First item is left aligned by default, and there are three items on screen (despite NumberOfSideItems=1):

![Screenshot_1571063661](https://user-images.githubusercontent.com/8092460/66760704-89748580-ee9a-11e9-9057-617303f7832c.png)

I guess the issue boils down to whether item 0 should be special cased on iOS, as it appears to be on Android.

### Steps to Reproduce

1. Run the attached sample. 
2. Browse to the "Horizontal layout (multiple items)" page on each platform.

### Expected Behavior

Identical layouts on iOS + Android. I have mixed views on which layout is correct - I want the left alignment, but I also only want one side item and Android gives me two. I'm inclined to think that Android is correct as displaying adjacent items for item 0 is a special case.

### Actual Behavior

Different layouts on iOS + Android.

### Basic Information

- Version with issue: 4.3-pre3
- Last known good version: N/A
- IDE: VSMac 8.3.3
- Platform Target Frameworks: 
  - iOS: 13.1
  - Android: API 28

### Screenshots

Additional iOS screenshots

NumberOfSideItems=2

![Simulator Screen Shot - iPhone X - 2019-10-14 at 15 43 29](https://user-images.githubusercontent.com/8092460/66761056-2cc59a80-ee9b-11e9-99f1-9b0baf4385ec.png)

NumberOfSideItems=3

![Simulator Screen Shot - iPhone X - 2019-10-14 at 15 43 50](https://user-images.githubusercontent.com/8092460/66761065-30f1b800-ee9b-11e9-9863-8851359b63a5.png)

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3725002/CarouselViewDemos.zip)

**Comment by kingces95** [comment]
![image](https://user-images.githubusercontent.com/4120386/66963097-81d5ed80-f00e-11e9-9420-738557616b8d.png)

**Comment by rmarinho** [comment]
We removed the NumberOfSideItems Api
