### ISSUE TITLE
[Bug][Android] In Picture in Picture mode bindings stop syncing

### ISSUE THREAD

**Issue by martijnlentink** [xamarin/Xamarin.Forms#8003]
### Description
Enabling PIP-mode on Android causes bindings to stop syncing. This is probably because Xamarin considers the app backgrounded.

### Steps to Reproduce

1. Implement OnPictureInPictureModeChanged in FormsApplicationActivity
2. Create a binding, for example an automatically incremented number that binds to Label.Text
3. Enter PIP mode and observe that the binding stops syncing

### Expected Behavior
Bindings should keep working

### Actual Behavior
Syncing is stopped.

**Comment by kingces95** [comment]
Could you please attach a project/solution that reproduces the issue? Thanks!

**Comment by samhouts** [comment]
@martijnlentink  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by breenbob** [comment]
Have just experienced this same issue. I am using bindings to govern visibility of UI components in a teleconferencing app, so when we go into PIP mode the app should behave as if it is going full-screen and hide non-AV related components. This works in normal app flow when going full screen, but I am finding that once I go into picture in picture mode, the UI components bound to the Full screen boolean property are all visible, even though that value is true (it is run through a boolean negation converter). It behaves as if it is binding to a null value, as it doesn't even reflect the current value never mind future changes to the value - i.e. property change notifications.

**Comment by breenbob** [comment]
@Samhouts I should probably add that we are using the [CreateSupportFragment ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms#android)extension method to convert our Xamarin.Forms ContentPage to an Android Fragment. It would be difficult for me to create a repro project as the solution I'm working in is tied to a licensed 3rd party AV vendor and don't have an easy route to convert to something more generic, but will try.
