### ISSUE TITLE
Xamarin Forms - ListView Context Actions generate a crash on iOS when the list view is within a CellView of a TableView

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8006]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/771265/xamarin-forms-listview-context-actions-generate-a.html)._

---
I could reproduced the bug I found out on my application using the ListView Interactivity sample provide on Microsoft docs website.
From that sample, I just surrounded the listview with a TableView (HasUnevenRows=“True”), a TableRoot, a TableSection and a ViewCell (in interactiveListViewXaml.xaml).
Sample can be found here:
https://docs.microsoft.com/fr-fr/samples/xamarin/xamarin-forms-samples/userinterface-listview-interactivity/

---
#### ym-app on 10/10/2019, 03:42 AM: 

<p>The crash occurs tapping on a item after swiping another item of the list to see the context actions.</p>

#### Visual Studio Feedback System on 10/10/2019, 06:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kingces95** [comment]
Can you please attach the project/solution that you derived from the sample that reproduces the issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
