### ISSUE TITLE
[Bug] Removing Shell Item can cause Shell to try and set a MenuItem as the default visible item

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8008]
### Description

If you have a Shell structure that goes

- ShellItem 1
- MenuItem
- ShellItem 2

And you try to remove ShellItem 1 then Shell will act like "MenuItem" has been selected so that it can be set as the default page

### Expected Behavior
Shell Item 2 should become the default page

### Actual Behavior

MenuItem is clicked which usually triggers a command like a page push and then Shell crashes

### Reproduction Link
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/964986

**Comment by samhouts** [comment]
closed by #8009
