### ISSUE TITLE
[Bug] [Xaml] Compiled Binding - Value Cannot Be Null

### ISSUE THREAD

**Issue by brepetti** [xamarin/Xamarin.Forms#8012]
When trying to add compiled binding to existing project we keep getting "Value Cannot be Null, parameter name: type" in the Error List.  There is no other information so we cannot track down what is causing this.

I cannot replicate in a brand new project so we have no idea whats causing this.

Here is output in diagnostics mode:

Pages\HomeDashboardPage.xaml : error : Value cannot be null.
4>    Pages\HomeDashboardPage.xaml : error : Parameter name: type
4>       at Mono.Cecil.Mixin.CheckType(Object type)
4>       at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
4>       at Xamarin.Forms.Build.Tasks.ModuleDefinitionExtensions.ImportReference(ModuleDefinition module, ValueTuple`3 type)
4>       at Xamarin.Forms.Build.Tasks.SetPropertiesVisitor.<CompileBindingPath>d__30.MoveNext()
4>       at Xamarin.Forms.Build.Tasks.SetPropertiesVisitor.<ProvideValue>d__29.MoveNext()
4>       at Xamarin.Forms.Build.Tasks.ILProcessorExtensions.Append(ILProcessor processor, IEnumerable`1 instructions)
4>       at Xamarin.Forms.Build.Tasks.SetPropertiesVisitor.Visit(ElementNode node, INode parentNode)
4>       at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
4>       at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
4>       at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
4>       at Xamarin.Forms.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
4>       at Xamarin.Forms.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
4>       at Xamarin.Forms.Build.Tasks.XamlCTask.TryCoreCompile(MethodDefinition initComp, MethodDefinition initCompRuntime, ILRootNode rootnode, Exception& exception)
4>        Resource: MobileTek.Forms.Pages.HomePage.xaml

### Expected Behavior
Compiled Bindings should work or output more error information.

Latest Xamarin Forms.

If we can reproduce in Sample Project we will upload.  The current project is very large and we cannot upload.

**Comment by kingces95** [comment]
Can you please add a solution that reproduces this issue? Thanks!

**Comment by samhouts** [comment]
@brepetti  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
