### ISSUE TITLE
[Bug] Xamarin.Forms Similar to android function setNextFocus with Entry 

### ISSUE THREAD

**Issue by wangyankun33** [xamarin/Xamarin.Forms#8013]
### Description
I have a requirement to set the focus switching order of the entry.
### Steps to Reproduce

1. Create 3 entries, such as A, B, C
2. By setting A.setNextFocus(B), B.setNextFocus(C)
3. When A clicks enter, the focus will automatically switch to B, not triggered by the Completed event.

### Basic Information

- Xamarin.Forms version:4.2.0.618605-pre2
- IDE:Visual Studio Professional 2019 Preview

**Comment by jfversluis** [comment]
I think something like this might be added with the TabOrder?

However; thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
