### ISSUE TITLE
VerticalScrollBarVisibility=“Always” not working in Xamarin Android

### ISSUE THREAD

**Issue by john-heaven** [xamarin/Xamarin.Forms#8015]
### Description
I have a ScrollView in Xamarin Forms , when set `VerticalScrollBarVisibility` be `Always `  it doesn't work .Even though the content size is over the size of scrollview .

### Steps to Reproduce

1. Create a Xamarin Forms Apllication.
2. In xaml add ScrollView with a content view.
3. Run in Android simulator.

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="App15.MainPage">

        <!-- Place new controls here -->
    <ScrollView>
        <AbsoluteLayout HeightRequest="1000"
                        VerticalOptions="FillAndExpand">
            <Image Source="TeslaBackground.jpg"
                   AbsoluteLayout.LayoutBounds="0,0,1,1"
                   AbsoluteLayout.LayoutFlags="All"
                   Aspect="AspectFill" />
            <StackLayout Orientation="Horizontal"
                     AbsoluteLayout.LayoutFlags="All"
                     AbsoluteLayout.LayoutBounds=".5,1,.5,.1">
                <Button x:Name="btnSignIn"
                                        Text="Sign in" />
                <Button x:Name="btnCreateAccount"
                                        Text="Create Account" />
            </StackLayout>
        </AbsoluteLayout>
    </ScrollView>
</ContentPage>
```

### Actual Behavior

![untitled](https://user-images.githubusercontent.com/7145819/66808439-ce152500-ef5d-11e9-9cde-99440d5e7f90.gif)

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 16.3.4 2019 Enterprise
- XamarinForms: 4.2.0.848062
 - Android: 9.0

### Reproduction Link

So link : https://stackoverflow.com/questions/58386555/verticalscrollbarvisibility-always-not-working-in-xamarin

Reproduce sample Link：https://www.dropbox.com/s/fp6cdzaqlidea8g/App15.rar?dl=0

**Comment by GalaxiaGuy** [comment]
It appears the Android implementation just doesn't do everything necessary for `Always` to work.

Based on this:

https://stackoverflow.com/questions/5702502/how-to-always-show-scrollbar

Adding (the C# version of) `setScrollBarFadeDuration(0);` or `setScrollbarFadingEnabled(false);` to the renderer might do the trick.

**Comment by kingces95** [comment]
[App15.zip](https://github.com/xamarin/Xamarin.Forms/files/3736605/App15.zip)

**Comment by jfversluis** [comment]
Reopening this one in light of: #10447.

The change in #8090 caused all child elements to flash scrollbars which is not desired. I reverted that change and now we need to find a proper solution for this initial problem.
