### ISSUE TITLE
[Enhancement] Xamarin Forms - Shared PDF-Viewer

### ISSUE THREAD

**Issue by MickLesk** [xamarin/Xamarin.Forms#8016]
## Summary
A useful PDF viewer as shared code (Xamarin Forms) would be advantageous. Here I see an extreme weakness of Xamarin Forms. The PDF viewer (using the example: pdfJS from Mozilla) should be able to handle various basic functions, e.g. "Pinch-To-Zoom", "Rotate", "Notes", "Number of pages", "Search function" and a correct integration in iOS / WPF / Android / UWP. 
Example: https://mozilla.github.io/pdf.js/web/viewer.html

There is a good viewer in Xamarin, this one is from Syncfusion. (see attachment). It has exactly the right functionality, but is not shared but based on several Syncfusion project files. 
![2019-10-15 09_52_34-Review and print PDF with ASP NET Web Forms PDF Viewer _ Syncfusion – Opera](https://user-images.githubusercontent.com/47820557/66811643-bd4eba00-ef31-11e9-9dd0-01b7c033994c.png)

## API Changes

There are no real API changes as the PDF viewer is not yet available in Xamarin Forms. I think this should be an own NUGET package, e.g. Xamarin.Forms.PDF (similar to Xamarin.Forms.Maps) 
Example-Binding for pdfJS (https://i.imgur.com/i7O9Id3.png) 

## Intended Use Case
PDF viewers are always needed. No matter where. 
We use a lot of PDF's for our project, our problem is that we have completely different solutions for Android (pdfJS) and iOS, which don't have much of the same appearance. This can lead to bugs in iOS that do not occur in Android. So you work twice, because there are "2" different projects.

**Comment by MickLesk** [comment]
What is the state of development here? Otherwise we have to consider a complete new development.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
