### ISSUE TITLE
[Bug] Dialog theming issues with Android dark mode

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#8029]
### Description

When using an Android device that supports dark mode (i.e. Android 10) and styles inheriting from `Theme.AppCompat.DayNight`, the alert presented by `Page.DisplayAlert` has a white background instead of dark gray when the device is in dark mode, resulting in unreadable text. 

I believe this has something to do with the use of `Android.App.AlertDialog` rather than `Android.Support.V7.App.AlertDialog` in the implementation of `DisplayAlert`.

This also applies to other dialogs such as DatePickers.

### Steps to Reproduce

1. Define a theme in your Android project that inherits from `Theme.AppCompat.DayNight`
2. Make a dialog theme that inherits from `Theme.AppCompat.DayNight.Dialog.Alert`
3. Add the dialog style to the application theme like so: 
    `<item name="android:alertDialogTheme">@style/DayNightDialogTheme</item>`
4. Set the theme of your MainActivity to the application theme defined above.
5. Run the app on a device in dark mode and call DisplayAlert

### Expected Behavior

The dialog is styled according to the theme, with white text on a dark background.

### Actual Behavior

The dialog style is only partially applied, resulting in white text on a white background.

### Basic Information

- Version with issue: 4.2.0 (also tested on 4.20-sr3 and 4.3.0-pre3)
- Last known good version: Unknown, probably none
- IDE: Visual Studio Professional 2019, version 16.3.3
- Platform Target Frameworks: 
  - Android: 10.0 
- Android Support Library Version: 28.0.0.1 / 28.0.0.3
- Affected Devices: Pixel 3 Emulator with Android 10.0, Samsung Galaxy S10 with Android 9.0

### Screenshots

[Light Mode](https://user-images.githubusercontent.com/6132629/66854497-107f3780-ef47-11e9-9e84-5e83345b38ae.png)

[Dark Mode](https://user-images.githubusercontent.com/6132629/66854523-18d77280-ef47-11e9-9663-a10eaac05117.png)

[Dark Mode (Expected)](https://user-images.githubusercontent.com/6132629/66854547-21c84400-ef47-11e9-950a-16d059505f5d.png)

### Reproduction Link

[DisplayAlertTheming.zip](https://github.com/xamarin/Xamarin.Forms/files/3730660/DisplayAlertTheming.zip)

**Comment by kingces95** [comment]
Well, I can reproduce the light mode screenshot but even after enabling dark mode on the emulator everything still appears in light mode... is there some trick to enabling dark mode on the emulator?

![image](https://user-images.githubusercontent.com/4120386/67133157-51758700-f1a7-11e9-97d1-928f9f87973a.png)

**Comment by streviranus** [comment]
Is this in the latest nuget? I noticed with Android DatePicker the dark theme is showing also not displaying correctly. light theme is showing correctly
![Screenshot_20191227-151031](https://user-images.githubusercontent.com/8270323/71533057-441dfc80-28bc-11ea-9d1f-e0883cb23b5c.png)
![Screenshot_20191227-151204](https://user-images.githubusercontent.com/8270323/71533060-47b18380-28bc-11ea-9349-6cdab2624539.png)
