### ISSUE TITLE
Include XAML File

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#8036]
Hi,

Please add an option to include a file such as the <?php include ?> in PHP

This helps for example when you want to ave a Navigation.TitleView for several pages and you want to keep it in one file instead of copying pasting the same code in every page and later when you want to change you will have to go again and change in all

This can be something like this:

`<%Include MyTitle.xaml %>
`

This should include the xaml and its cs file too

Thanks,
Jassim

**Comment by StephaneDelcroix** [comment]
Thanks for this proposal. Unfortunately, this would break compatibility with the XAML language, and so we won't support it.

For your particular case, you probably should define a custom control for your TitleView, and reuse it. the syntax will be as short as what you expect
