### ISSUE TITLE
[Bug] [WPF]ImageButton with source from resource throw System.InvalidOperationException

### ISSUE THREAD

**Issue by pardont** [xamarin/Xamarin.Forms#8038]
[TestWpfImageButton.zip](https://github.com/xamarin/Xamarin.Forms/files/3734024/TestWpfImageButton.zip)

#8025 # Description
Set ImageButton.Source with ImageSource from resource in page constructor on WPF platform, System.InvalidOperationException will be throwed when page apprearing.

### Steps to Reproduce
1.  add ImageButton to page xaml
2.  set ImageButton.Source = ImageSource.FromResource("") in page constructor.
3.  run and show the page.

### Basic Information

- Xamarin.Forms: 4.3.0.851321-pre3
- Xamarin.Forms.Platform.WPF: 4.3.0.851321-pre3
- IDE: vs2017 or vs2019

**CODE：**
**xaml**
`<ImageButton x:Name="btnResx" />`

**cs**
`        public MainPage()
        {
            InitializeComponent();
            btnResx.Source = ImageSource.FromResource("TestWpfImageButton.cat.png");
        }`

Attached is the solution source code.

**Comment by kingces95** [comment]
I get a cat on master. Is launching the reproduction supposed to crash?
![image](https://user-images.githubusercontent.com/4120386/67133489-c5645f00-f1a8-11e9-967d-8c219526b687.png)

**Comment by pardont** [comment]
@kingces95  I test it with version 4.4.0.936621-pre1,  the exception always exist on WPF. 
![image](https://user-images.githubusercontent.com/2252587/68566333-017d9d80-0491-11ea-9bf1-b9bddb46be41.png)

**Comment by pardont** [comment]
@kingces95 please use this code to test.
[TestWpfImageButton.zip](https://github.com/xamarin/Xamarin.Forms/files/4034194/TestWpfImageButton.zip)

the exception screenshot:
![image](https://user-images.githubusercontent.com/2252587/71962006-8ab41500-3233-11ea-8b84-d43ad060a254.png)
