### ISSUE TITLE
[Bug] Images not shown correctly while using GTK#

### ISSUE THREAD

**Issue by anaselhajjaji** [xamarin/Xamarin.Forms#8042]
All the details are present on:
https://github.com/jsuarezruiz/xamarin-forms-gtk-movies-sample/issues/1

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
