### ISSUE TITLE
Java.Lang.IllegalArgumentException: View=DecorView@480ddcc[] not attached to window manager

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#8044]
### Description
An XF application crash on Android 
### Steps to Reproduce
unknown
### Expected Behavior
don't crash
### Actual Behavior
Package: com.xxx.xxx
Version Code: 64
Version Name: 2.0.0
Android: 7.1.2
Android Build: 01-01-49.00-NN-U12-STD
Manufacturer: Zebra Technologies
Model: TC51
CrashReporter Key: b292a407-28c7-4ba4-9acf-9ec3a7109266
Date: undefined

Xamarin Exception Stack:
Java.Lang.IllegalArgumentException: View=DecorView@480ddcc[] not attached to window manager
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <3f0c8575a93e422f814d9f2ff59c60f5>:0
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <3f0c8575a93e422f814d9f2ff59c60f5>:0
  at Android.App.Dialog.Dismiss () [0x0000a] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
  at AndroidHUD.AndHUD.<DismissCurrent>b__30_0 () [0x00019] in <6f7b3b50163b4d2cb9a7f3fb7dd92867>:0
  at AndroidHUD.AndHUD+<>c__DisplayClass30_0.<DismissCurrent>b__1 (System.Object state) [0x00000] in <6f7b3b50163b4d2cb9a7f3fb7dd92867>:0
  at Android.App.SyncContext+<>c__DisplayClass3_0.<Send>b__0 () [0x00000] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.38(intptr,intptr)
  at java.lang.IllegalArgumentException: View=DecorView@480ddcc[] not attached to window manager
  at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:473)
  at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:382)
  at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:126)
  at android.app.Dialog.dismissDialog(Dialog.java:370)
  at android.app.Dialog.dismiss(Dialog.java:353)
  at mono.java.lang.RunnableImplementor.n_run(Native Method)
  at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

Thread 566:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:150)
2   java.lang.Thread.run(Thread.java:761)

Thread 567:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Object.wait(Object.java:407)
2   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:188)
3   java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:209)
4   java.lang.Daemons$FinalizerDaemon.run(Daemons.java:204)
5   java.lang.Thread.run(Thread.java:761)

Thread 568:
0   java.lang.Thread.sleep(Thread.java:-2)
1   java.lang.Thread.sleep(Thread.java:371)
2   java.lang.Thread.sleep(Thread.java:313)
3   java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:314)
4   java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:336)
5   java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:253)
6   java.lang.Thread.run(Thread.java:761)

Thread 569:
0   dalvik.system.VMRuntime.runHeapTasks(VMRuntime.java:-2)
1   java.lang.Daemons$HeapTaskDaemon.run(Daemons.java:433)
2   java.lang.Thread.run(Thread.java:761)

Thread 578:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:136)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 581:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2127)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.park(LockSupport.java:161)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2035)
5   java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
9   java.lang.Thread.run(Thread.java:761)

Thread 582:
0   android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
1   android.os.MessageQueue.next(MessageQueue.java:323)
2   android.os.Looper.loop(Looper.java:136)
3   android.os.HandlerThread.run(HandlerThread.java:61)

Thread 584:
0   android.net.LocalSocketImpl.readba_native(LocalSocketImpl.java:-2)
1   android.net.LocalSocketImpl.-wrap1(LocalSocketImpl.java:-1)
2   android.net.LocalSocketImpl$SocketInputStream.read(LocalSocketImpl.java:110)
3   com.qti.tcmclient.DpmTcmClient$TcmReceiver.run(DpmTcmClient.java:140)
4   java.lang.Thread.run(Thread.java:761)

Thread 585:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:311)
2   com.android.okhttp.okio.AsyncTimeout.-wrap0(AsyncTimeout.java:-1)
3   com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)

Thread 1560:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2127)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1057)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
9   java.lang.Thread.run(Thread.java:761)

Thread 1561:
0   java.lang.Object.wait(Object.java:-2)
1   com.android.okhttp.ConnectionPool.performCleanup(ConnectionPool.java:307)
2   com.android.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(ConnectionPool.java:244)
3   com.android.okhttp.ConnectionPool.-wrap0(ConnectionPool.java:-1)
4   com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:98)
5   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
6   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
7   java.lang.Thread.run(Thread.java:761)

Thread 1562:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2127)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1057)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
9   java.lang.Thread.run(Thread.java:761)

Thread 1563:
0   java.lang.Object.wait(Object.java:-2)
1   java.lang.Thread.parkFor$(Thread.java:2127)
2   sun.misc.Unsafe.park(Unsafe.java:325)
3   java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
4   java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
5   java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:438)
6   java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1057)
7   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
8   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
9   java.lang.Thread.run(Thread.java:761)
### Basic Information
no info available, only crashes on AppCenter
- Version with issue:
- Last known good version: unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0
- Nuget Packages: XF 4.2.0.709249
- Affected Devices:
Zebra TC51 Android 7.1.2

**Comment by kingces95** [comment]
Could you please attach a solution that reproduces this issue? Thanks!

**Comment by acaliaro** [comment]
Sorry, it's a very large project  and I use a lot of controls. I have no idea where could be the problem. It's a project I have inherited from other developers.

Can you tell me some possible reasons that can cause this problem?

**Comment by samhouts** [comment]
@acaliaro Are you using modals?

**Comment by acaliaro** [comment]
Yes, there are some "pushmodal" in the code...

**Comment by PureWeen** [comment]
@acaliaro looking at your stack trace it doesn't seem like this is an issue coming from the Forms SDK

```
at Android.App.Dialog.Dismiss () [0x0000a] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
at AndroidHUD.AndHUD.b__30_0 () [0x00019] in <6f7b3b50163b4d2cb9a7f3fb7dd92867>:0
at AndroidHUD.AndHUD+<>c__DisplayClass30_0.b__1 (System.Object state) [0x00000] in <6f7b3b50163b4d2cb9a7f3fb7dd92867>:0
at Android.App.SyncContext+<>c__DisplayClass3_0.b__0 () [0x00000] in <63f6c3d513ec4ea5bd8cf6aba6672b75>:0
```

We only use dialogs with pickers. The Modals aren't implemented using Dialogs

I think you'll need to take this issue up with 
https://github.com/redth-org/AndHUD

@Redth do you have any thoughts on the stack trace?

**Comment by Redth** [comment]
It definitely seems like an AndHUD related issue and not Forms.  It looks perhaps like they are trying to dismiss an AndHUD dialog which has already been dismissed? or trying to do so off the UI thread? Or maybe there's some other unexpected dialog / window code going on at the same time in the app?  It's honestly very difficult to say without a repro.

**Comment by PureWeen** [comment]
@acaliaro can you see if this is happening

> It looks perhaps like they are trying to dismiss an AndHUD dialog which has already been dismissed? or trying to do so off the UI thread? Or maybe there's some other unexpected dialog / window code going on at the same time in the app?

And then if you're still having issues create an issue over here. If you can get a repro together that would be really helpful
https://github.com/redth-org/AndHUD

**Comment by acaliaro** [comment]
I don't use AndHUD directly. Maybe https://github.com/aritchie/userdialogs ??? It seems to use AndHUD for Android.

**Comment by sbs-Arockia-Jenitha** [comment]
I didnt use AndHUD. But we are using Acer.Userdialog to show the alert and confirmation. and also We have been using Alertdialog.Builder in Native code to pop the picker datas.

What is the cause of this issue?

**Comment by sbs-Arockia-Jenitha** [comment]
> I don't use AndHUD directly. Maybe https://github.com/aritchie/userdialogs ??? It seems to use AndHUD for Android.

I didnt use AndHUD. But we are using Acer.Userdialog to show the alert and confirmation. and also We have been using Alertdialog.Builder in Native code to pop the picker datas.

What is the cause of this issue?
