### ISSUE TITLE
[Bug] Forms.ListView CachingStrategy affects iOS Keyboard overlapping.

### ISSUE THREAD

**Issue by tiseidel** [xamarin/Xamarin.Forms#8045]
### Description
My basic Xamarin.Forms layout is as follows:

```
Grid
    **ListView**
    {
        ViewCells that contain **Entries** and some other stuff. 
    }
    Button | Button
```

With ListView.CachingStrategie = **RetainElement**, the ListView scrolls up to the element, so that it's not overlapped by the keyboard if a entry is selected. The RetainElement led to some other problems, so i wanted to go with RecyleElement.
But, with  ListView.CachingStrategie = **RecycleElement** the mechanism doesn't work on iOS. The Entry is hidden by the keyboard =(

### Steps to Reproduce

1.  Create a ListView inside a grid with items below and set the CachingStrategie to RecycleElement
2. Create custom ViewCells that contain a Entry.
3. Start the application and try to input text in a Entry that is on the bottom of the Page.

### Expected Behavior
The ListView is scrolled up, so that the Entry is visible (like it happens when the CachingStrategie is set to RetainElement)

### Actual Behavior
The Entry is hidden by the keyboard, the ListView doesn't change.

### Basic Information

- Version with issue: 4.2.0.848062
- Last known good version: -/-
- IDE: Visual Studio 
- Platform Target Frameworks: 
  - iOS:  12.14.0.114
- Nuget Packages: FFImageLoading (2.4.11.982) + SkiaSharp (1.68.0), Xamarin.Essentials (1.3.1)
- Affected Devices: iPad Air 2

**Comment by kingces95** [comment]
If you have a reproduction, could you please attach it? We can re-create it but if you've already got one then it saves us a bunch of time as the time to re-creating the repros really adds up for all the issues! Thanks.

**Comment by samhouts** [comment]
@tiseidel  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
