### ISSUE TITLE
[Bug] Listview on wpf takes takes a lot to clear when changing itemsource

### ISSUE THREAD

**Issue by observer1** [xamarin/Xamarin.Forms#8053]
### Description
Listview on WPF takes a lot to clear thounsands of items
### Steps to Reproduce

1. Create a listview and fill with thousands of items
2. Change the itemsource to a list of the same type but empty
3. It will take a lot of time

### Expected Behavior
The listview should clear instantly
### Actual Behavior
The listview takes a lot of time to clear
### Basic Information

- Version with issue:
4.4.0.1233-nightly
- Last known good version:
none
- IDE:
VS 2019
- Platform Target Frameworks: 
WPF
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms
Xamarin.Forms.Platform.WPF
- Affected Devices:
Windows 10 pc
### Reproduction Link

[Test - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/3737113/Test.-.Copy.zip)

**Comment by yurkinh** [comment]
I'm not sure that this is 100% correct solution but If in ListViewRender replace lines [286-290]
`foreach (var item in TemplatedItemsView.TemplatedItems)
               {
                    items.Add(item);
                }
                _listview.ItemsSource = items;`
with line
`_listview.ItemsSource = TemplatedItemsView.TemplatedItems;`
it will start working blazingly fast. This is is only for ungrouped data.
I have attached working solution with modified ListViewRendere
[TestList.zip](https://github.com/xamarin/Xamarin.Forms/files/4214603/TestList.zip)

**Comment by yurkinh** [comment]
In original sample, the problem is with unhooking events (It's called 20000 times for each of item). In UWP we don't have such issue : UnhookAndClear() method has not been called at all. 
![scr](https://user-images.githubusercontent.com/17849938/74668624-43b02c80-51ae-11ea-8bd8-7ef136be2af7.png)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
