### ISSUE TITLE
How detect pressed software button NavigationBack?

### ISSUE THREAD

**Issue by scriptBoris** [xamarin/Xamarin.Forms#8054]
No way how catch pressed software button NavigationBack.
![image](https://user-images.githubusercontent.com/29772096/66972894-a55d6e80-f0c8-11e9-805d-3684ba1a0c3d.png)

**Comment by VladislavAntonyuk** [comment]
you can override OnAppearing, OnDisappearing in code behind

**Comment by scriptBoris** [comment]
> you can override OnAppearing, OnDisappearing in code behind

Override OnAppearing and OnDisappearing - can not break action NavigationBack, when user taped button (software) Back.

**Comment by scriptBoris** [comment]
The question is still relevant.

**Comment by KSemenenko** [comment]
@scriptBoris you need override OnBackButtonPressed() in your page.

```  cs
protected override bool OnBackButtonPressed()
{
    //put your logic here
}
```
And you need to return true or false depending on whether you want to do the navigation back or not.

**Comment by VladislavAntonyuk** [comment]
@KSemenenko this code is not executed

**Comment by KSemenenko** [comment]
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.onbackbuttonpressed?view=xamarin-forms

@VladislavAntonyuk you can try next code, and put break point.

``` cs
protected override bool OnBackButtonPressed()
{
    return OnBackButtonPressed();
}
```
If you return true from then you will not go back to the previous page, unless you also call the base method in your override.

**Comment by VladislavAntonyuk** [comment]
@Ksemenenko if you press back button of android the code is executed, but the question is about arrow. See screenshot

**Comment by KSemenenko** [comment]
https://theconfuzedsourcecode.wordpress.com/2017/03/12/lets-override-navigation-bar-back-button-click-in-xamarin-forms/

**Comment by KSemenenko** [comment]
@VladislavAntonyuk I want to note that the text in question indicates exactly the button of the device, and not the arrow on the screen.

**Comment by KSemenenko** [comment]
@VladislavAntonyuk @scriptBoris  also if you check https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/FormsAppCompatActivity.cs then find that the code is already there and my code should work. What version of Xamarin.Forms are you using?

**Comment by scriptBoris** [comment]
> https://theconfuzedsourcecode.wordpress.com/2017/03/12/lets-override-navigation-bar-back-button-click-in-xamarin-forms/
> @VladislavAntonyuk

![image](https://user-images.githubusercontent.com/29772096/67446092-eeba3a80-f641-11e9-9d81-702ee9fe0c8b.png)
Xamarin Forms 4.1
MasterPage, MasterDetail - NavigationPage ...

**Comment by scriptBoris** [comment]
The problem is not solved. Help please!

**Comment by KSemenenko** [comment]
Seems it's a bug, I will look for a solution to the problem

**Comment by hartez** [comment]
There is no simple way to do this. As pointed out upthread, there are some hacks and tricks you can employ to do this (see: https://xamarinhelp.com/xamarin-forms-back-navigation-pitfalls/). 

If this is a feature you would like, I suggest opening a [feature request](https://github.com/xamarin/Xamarin.Forms/issues/new?assignees=&labels=proposal-open%2C+t%2Fenhancement+%E2%9E%95&template=feature_request.md&title=%5BEnhancement%5D+YOUR+IDEA%21).

**Comment by hartez** [comment]
@scriptBoris Another option would be to move your application to use Xamarin.Forms Shell - Shell has a Navigating event that you can intercept and cancel: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#navigation-events
