### ISSUE TITLE
[Bug] Listview takes a lot to fill on Gtk

### ISSUE THREAD

**Issue by observer1** [xamarin/Xamarin.Forms#8055]
### Description
On Gtk a listview with itemsource with thousands of items takes a lot to fill
### Steps to Reproduce

1. Fill a list with thousands of items
2. Set the listview itemssource to the list
3. It will take a lot to fill

### Expected Behavior
The listview should fill much faster
### Actual Behavior
The listview is filled progressively and very slow
### Basic Information

- Version with issue:
4.4.0.1233-nightly
- Last known good version:
N/A
- IDE:
VS 2019
- Platform Target Frameworks: 
WPF
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms
Xamarin.Forms.Platform.GTK
- Affected Devices:
Windows 10 PC
### Reproduction Link

[Test - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/3737174/Test.-.Copy.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
