### ISSUE TITLE
[Enhancement] Change ControlGallery shared issue project to .netstandard

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#8060]
## Summary
The ControlGallery shared issue project currently has the "Shared" project type. The problem with this is, that files are referenced explicitly which leads to merge conflicts when adding a new issue page.
![Screenshot_20191017-124708~2](https://user-images.githubusercontent.com/11095003/67002789-ebbcc880-f0dc-11e9-8403-f396060d432a.png)
Switching to netstandard with the new project sdk would include all files in the directory and avoid this issue.

**Comment by jfversluis** [comment]
Yeah that didn't happen.
