### ISSUE TITLE
Xamarin Forms Tabbed Paged Text Color Not Working

### ISSUE THREAD

**Issue by attrib75** [xamarin/Xamarin.Forms#8069]
### Description
Xamarin Forms Tabbed Paged Text Color Not Working for iOS and Android

### Steps to Reproduce

1. Create a tabbed page
2. Android : Set the BarTextColor property -OR-
Set the following in the Android Project Style.xml
  `<style name="Widget.AppTheme.TabLayout" parent="@style/Widget.Design.TabLayout">
    <item name="tabSelectedTextColor">#254B9C</item>
    <item name="tabTextColor">#666666</item>
  </style>`
3.  iOS:  Set the BarTextColor property -OR-
set the following in appdelegate:

               ` UITabBarItem.Appearance.SetTitleTextAttributes(
                new UITextAttributes()
                {
                    TextColor = UIColor.FromRGB(37, 75, 156)
                },
                UIControlState.Selected);

               // Color of the unselected tab icon & text:
               UITabBarItem.Appearance.SetTitleTextAttributes(
                new UITextAttributes()
                {
                    TextColor = UIColor.FromRGB(102, 102, 102)
                },
                UIControlState.Normal);`

### Expected Behavior
Selected and not selected bar text color appears as specified

### Actual Behavior
Android: not selected text color is white, selected text color shows as Gray instead of blue like I specified
iOS:  Selected text color works after setting in appdelegate 👍 
        Unselected text color is still white

### Basic Information

- Version with issue:  Xamarin Forms 4.2.0.848062
- Last known good version:  Xamarin Forms 3.2.0
- IDE: VS Community 16.3.2
- Platform Target Frameworks:  
  - iOS:   13
  - Android:  8.1
  - UWP:  None
- Android Support Library Version:  28
- Nuget Packages:
- Affected Devices: all

### Screenshots

![66702954-df96cc80-ecd2-11e9-87e0-db5b861693e8](https://user-images.githubusercontent.com/1398909/67019007-a212b480-f0c1-11e9-8e98-e8c8be12b51b.png)

**Comment by attrib75** [comment]
I updated this to include both android and ios

**Comment by kingces95** [comment]
Can you please attach a reproduction solution? Thanks!

**Comment by attrib75** [comment]
hi, how can I do so privately?  I can't share this in public.  thanks

**Comment by attrib75** [comment]
Also, since you've tagged it with 'needs repro' are you unable to reproduce this?

**Comment by attrib75** [comment]
Hello, just checking, what is the status on this?  Anything I can do or provide?

**Comment by jfversluis** [comment]
If you would be able to provide a reproduction project that would be great. I understand that you can't share your full project, but can you try to create a "File > New" Xamarin.Forms project and see if you can get this bug to show?

**Comment by attrib75** [comment]
For sure. I'll try to throw something together

**Comment by attrib75** [comment]
@jfversluis I went to reproduce the issue and I cannot.  Looks like something happened in my code :(

**Comment by jfversluis** [comment]
Hi @attrib75 one of the reasons we love reproductions so much :) 

At least we now ruled out one possible cause. I think a next step would be to pinpoint what is happening in your app and start adding some code to the reproduction and see at which point it starts to fail. When you have that you are likely to see if it is something within Xamarin.Forms that is not playing nicely with your code or maybe something else.

Whenever you have a successful reproduction we'll be happy to have a look!

**Comment by attrib75** [comment]
ok thank you.

**Comment by attrib75** [comment]
@jfversluis I uploaded a repo that serves dual purpose, demonstrating another issue.  I've managed to get it so that the tabbed page bar text color does not appear.  Its probably something I'm doing wrong

https://github.com/attrib75/XamIoSSearchBarColorBug

**Comment by hartez** [comment]
@attrib75 Have you tried setting the `SelectedTabColor` and `UnselectedTabColor` properties of your `TabbedPage`?

**Comment by attrib75** [comment]
Hi yes that's one of the first things I tried.

**Comment by hartez** [comment]
@attrib75 If I clone your repro project, remove the `BarTextColor="LightGray"` setting on the `TabbedPage`, and set the `SelectedTabColor="Red"` and  `UnselectedTabColor="Blue"`, the text and icons of the tabs are red when selected and blue when unselected. Which is what I would expect to happen. 

Does that work for you? What am I missing?

**Comment by attrib75** [comment]
Ok let me try to do this on my project and see if that works

**Comment by samhouts** [comment]
@attrib75 Thanks, we'll keep looking for it.

**Comment by attrib75** [comment]
For some reason that did not work.  Not sure what the difference is

**Comment by samhouts** [comment]
@attrib75 What device/emulator are you using to test this with?

**Comment by samhouts** [comment]
@attrib75  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
