### ISSUE TITLE
[Bug] Documentation about creating a NuGet is so out of date as to be useless

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#8070]
### Description
The documentation about creating a NuGet for Xamarin at
https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin
is so out of date that it does not match reality when using VS2017 or VS2019. I suspect it probably doesn't even when using VS2015 (but who would still be using that anyway???)

### Steps to Reproduce

1.  Open https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin
2.  Try following the instructions

### Expected Behavior
A NuGet would be created

### Actual Behavior
Tear hair out in frustration

### Basic Information

- Version with issue: https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin at downloaded on 17th October 2019
- Last known good version: It might have been good in 2015

### Reproduction Link

https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin

**Comment by michizhou** [comment]
@johnshardman If it's not too much trouble, I'd appreciate it if you or someone else can review my PR. I also want to make sure that my PR can count toward my hacktoberfest Xamarin contributions, since it does address a Xamarin.Forms issue despite being made from a non-Xamarin repo. Please let me know if additional changes to my PR are needed. Thank you.

**Comment by johnshardman** [comment]
@michizhou - I've posted on the XF forum asking a few people to review your proposed change. See https://forums.xamarin.com/discussion/comment/394588/#Comment_394588

If I get time later this week, I'll also review your change. I got my NuGet built in the end, but I can try to construct a sample one to see if the changes provide enough info.

**Comment by michizhou** [comment]
@johnshardman I just wanted to follow up with you about the review status of the changes in my PR for this issue. If you and others on the XF forum could look over them whenever you are able, I would greatly appreciate it. Feel free to keep me updated. Thank you.

**Comment by samhouts** [comment]
closed by NuGet/docs.microsoft.com-nuget#1758
