### ISSUE TITLE
Colored image in ToolbarItem for iOS and UWP

### ISSUE THREAD

**Issue by GovardhanNag** [xamarin/Xamarin.Forms#8071]
## Summary
Images added to the ToolbarItem appear to be different in iOS and UWP. But that is not the case in Android, it renders the image as it is.

The same design is expected in iOS and UWP. We don't accept this discrimination, either in all the platforms colored image should appear or colored image should be turned to black and white in Android.

To adjust to the same UI as that of Android in iOS and UWP, we have to follow some custom renderers or plugins. Instead of that, if Xamarin.Forms provide this feature, then it will be good to have unique cross platform development.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
