### ISSUE TITLE
[Bug] Shell - NavigationPage.SetHasNavigationBar does not hide NavigationBar

### ISSUE THREAD

**Issue by Elashi** [xamarin/Xamarin.Forms#8072]
### Description
`NavigationPage.HasNavigationBar="False"` does not hide/remove the Navigation Bar in Shell projects.

### Steps to Reproduce
Add `NavigationPage.HasNavigationBar="False"` to a ContentPage.

### Expected Behavior
The navigation bar should disappear from the page that has HasNavigationBar property assigned to false.

### Actual Behavior
The navigation bar does NOT disappear from the page that has HasNavigationBar property assigned to false.

### Basic Information

- Version with issue: 4.2.0
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  13.
  - Android: Android 8.0

### Screenshots
![image](https://user-images.githubusercontent.com/12378171/67028350-ce572100-f113-11e9-9273-2b45cd0184a3.png)

**Comment by samhouts** [comment]
@Elashi  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Elashi** [comment]
[HideNavBar.zip](https://github.com/xamarin/Xamarin.Forms/files/3742765/HideNavBar.zip)

**Comment by Elashi** [comment]
I found that we can Hide the navbar using `Shell.NavBarIsVisible="False"`
Seems like that `NavigationPage.SetHasNavigationBar` is not effective in Shell but while debugging the problem, I noticed that this property `NavigationPage.SetHasNavigationBar` is checked during pushing modal pages.  I think this is worth investigation.

I think this declares this issue resolved.
