### ISSUE TITLE
Android UITest query issues

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8075]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/780607/xamarin-forms-uitet-query-issues.html)._

---
We are having issues with UITest on Android following an upgrade of Xamarin Forms from 2.4 to 4.2. All tests pass against 2.4.
The issue surrounds querying Listviews, which is very unreliable. UiTest queries against Xamarin Forms listviews fail to return all present and visible elements.

This is preventing a significant proportion of our automated regression tests from completing.

**Example output of a test against XF 2.4:**

```
#### BASIC CELL QUERY = * marked:'PatientVisitListCell'
Query for Marked(&quot;PatientVisitListCell&quot;) gave 3 results.
### BASIC CELLS QUERY COUNT = 3
#### INDEXED CELL QUERY = * marked:'PatientVisitListCell' index:0
Query for Marked(&quot;PatientVisitListCell&quot;). Index(0) gave 1 results.
#### INDEXED RESULT = 1
#### INDEXED LOCAL VARIABLE CELL QUERY = * marked:'PatientVisitListCell' index:0
Query for Marked(&quot;PatientVisitListCell&quot;). Index(0) gave 1 results.
#### INDEXED RESULT = 1
#### INDEXED CELL QUERY = * marked:'PatientVisitListCell' index:1
Query for Marked(&quot;PatientVisitListCell&quot;). Index(1) gave 1 results.
```

**Example output of the same test against XF 4.2:**

```
#### BASIC CELL QUERY = * marked:'PatientVisitListCell'
Query for Marked(&quot;PatientVisitListCell&quot;) gave 3 results.
### BASIC CELLS QUERY COUNT = 3
#### INDEXED CELL QUERY = * marked:'PatientVisitListCell' index:0
Query for Marked(&quot;PatientVisitListCell&quot;). Index(0) gave 1 results.
#### INDEXED RESULT = 1
#### INDEXED LOCAL VARIABLE CELL QUERY = * marked:'PatientVisitListCell' index:0
Query for Marked(&quot;PatientVisitListCell&quot;). Index(0) gave 1 results.
#### INDEXED RESULT = 1
#### INDEXED CELL QUERY = * marked:'PatientVisitListCell' index:1
Query for Marked(&quot;PatientVisitListCell&quot;). Index(1) gave 0 results.
```

There are no other changes other than the Xamarin Forms version.

When complaring the repl output there is almost no difference:

Broken repl output example:

```
[ListViewRenderer &gt; ListViewRenderer_SwipeRefreshLayoutWithFixedNestedScrolling]
              [ListView] id: &quot;NoResourceEntry-67&quot;,  label: &quot;PatientVisitListView&quot;
                [ConditionalFocusLayout]
                  [ViewCellRenderer_ViewCellContainer]
                    [Platform_DefaultRenderer] label: &quot;PatientVisitListCell&quot;
                     [BannerBackgroundRenderer]
                      [Platform_DefaultRenderer]
                        [LabelRenderer]
                          [FormsTextView] id: &quot;NoResourceEntry-72&quot;,  label: &quot;PatientListCellLine1&quot;,  text: &quot;....
```

Working  repl output example:

```
[ListViewRenderer &gt; SwipeRefreshLayout]
            [ListView] id: &quot;NoResourceEntry-67&quot;,  label: &quot;PatientVisitListView&quot;
              [ConditionalFocusLayout]
                [ViewCellRenderer_ViewCellContainer]
                  [Platform_DefaultRenderer] label: &quot;PatientVisitListCell&quot;
                    [BannerBackgroundRenderer]
                    [Platform_DefaultRenderer]
                      [LabelRenderer]
                        [FormsTextView] id: &quot;NoResourceEntry-72&quot;,  label: &quot;PatientListCellLine1&quot;,  text: &quot;
```

---
#### Visual Studio Feedback System on 10/17/2019, 02:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by simon-potter78** [comment]
This issue was a result of the following forms issue:
https://github.com/xamarin/Xamarin.Forms/issues/3168
In this, the formattedText object bound to in the listview is a stored entity, which creates a feedback loop between the android renderer and the formattedstring object. in VS 2019 this is detected and the hundreds of errors a second are logged.
To resolve always return a new instance of formattedstring and its spans from the bound properties, thus the rendering completes correctly and prevents the render feedback loop that was breaking UiTest.
