### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by yshteinm** [xamarin/Xamarin.Forms#8078]
I suggested to add this to Xamarin.Essentials but @jamesmontemagno suggested that a good place for this will be Xamarin.Fomrs.

I know about FFImageLoading but it would be great if there was official support for SVG (or other vector format) in Forms. I would like to see support in Controls (like image button), background images (like inside Image View), if possible ToolBar, etc.
And if animated SVG is supported it will be even better

**Comment by paulb39** [comment]
This has been asked for many times before.
See https://github.com/xamarin/Xamarin.Forms/issues/1863

**Comment by yshteinm** [comment]
@paulb39 #1863 is closed. How that will help?

**Comment by paulb39** [comment]
@yshteinm, PureWeen said they aren't going to support it.

"I'm going to close this particular issue and recommend using 3rd party plugins for straight SVG files as this isn't something that the Core is going to support"

**Comment by goedware** [comment]
I support official support for SVG (or other vector format) in Forms. Vector images are important for our apps which we try to make adaptive to resolution/size etc. And I also know that there are plugins to provide us that feature, but it would be nice and handy to have it in the Core. Android also has it at it's core with Vector Drawables. And the official support about SVG can change of course, opinions often change when time passes  ;).

**Comment by jfversluis** [comment]
This should be much better in .NET MAUI :) please check out the new features there and add suggestions if you still would like to see more support for things. Thanks!
