### ISSUE TITLE
[XAMARIN-FORMS-WPF] View doesn't render when set IsClippedToBounds to true

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#8087]
### Description

Greetings,

We at Syncfusion have started implementation for providing support in Xamarin.Forms WPF platform for our controls. We have noticed that when set IsClippedToBounds to true for any layout control, it doesn't render in the View. For Example if the Grid is added as a child for StackLayout and when set IsClippedToBounds to true for Grid, it doesn't layout as like in UWP platform. We have ensured by specifying size requests and also tried LayoutOptions. We have attached a simple sample showcasing the issue. Can you please provide us with any solution or workaround to overcome this issue as soon as possible?

### Steps to Reproduce

1. Run the attached sample in WPF platform.

### Expected Behavior
The label should render as expected.

### Actual Behavior
The page is blank.

### Basic Information

- Version with issue: Latest
- Platform Target Frameworks: 
WPF

### Reproduction Link
[IsClippedToBoundsIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3744307/IsClippedToBoundsIssue.zip)

**Comment by mohachouch** [comment]
Hi @samhouts, bug verified. You can assign me on this issue.
