### ISSUE TITLE
[Spec]  DeviceInfo

### ISSUE THREAD

**Issue by rmarinho** [xamarin/Xamarin.Forms#8088]
# Deviceinfo

Expose an API with some DeviceInfo like StatusBarheight, SafeArea, Theme, Localization
# API

### Properties

StatusBarHeight
 
# Scenarios

## C# Example

# Backward Compatibility

Minimum API levels?
Breaking changes?
Unsupported platforms?

# Difficulty : [low/medium/high]

**Comment by Redth** [comment]
We are looking at adding some of these things, but it certainly makes sense to add more of them to Essentials.

**Comment by rmarinho** [comment]
Awesome.
