### ISSUE TITLE
[Enhancement] IsEnabled Property for TapGestureRecognizer!

### ISSUE THREAD

**Issue by hudaIT** [xamarin/Xamarin.Forms#8091]
## Summary
Would be amazing when we would have the possibility to Enable/Dissable an TapGestureRecognizer in Xaml with an Property ( IsEnabled )

## API Changes
In ViewModel => **bool UserRoleAvailable=true;**

<TapGestureRecognizer Command="{Binding MyCommand}" **IsEnabled="{Binding UserRoleAvailable}"** />

## Intended Use Case
Obvious

**Comment by hartez** [comment]
You are already using a bound `Command` - why not just check `UserRoleAvailable` in the `Command`'s `CanExecute` method? If `CanExecute` returns `false`, the bound `Command` will not run.

I'm attaching a quick example: 
[TapGestureCanExecute Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3745525/TapGestureCanExecute.Repro.zip)

**Comment by hudaIT** [comment]
Ahh right my fault. Thank you very much completely forgot that.
