### ISSUE TITLE
Entry did not moves upwards when keyboard is raised Inside Shell Android

### ISSUE THREAD

**Issue by Sarthak261995** [xamarin/Xamarin.Forms#8092]
Entry did not moves upwards when keyboard is raised Inside Shell In Android haven't tested on iOS Yet. 

Note it moves up as expected When Content page is not inside the shell.
I do not have Scroll view inside my page .

Xamarin Version : Latest

Below is the code I am using

            <Grid
                Padding="20,10,20,0"
                RowSpacing="10">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                    <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*" />
                </Grid.ColumnDefinitions>
                <ffimageloading:CachedImage
                    Grid.Row="0"
                    Grid.Column="0"
                    Margin="0,10,0,0"
                    Aspect="AspectFill"
                    DownsampleToViewSize="true"
                    FadeAnimationForCachedImages="True"
                    HeightRequest="120"
                    HorizontalOptions="Center"
                    Source="user_placeholder.png"
                    WidthRequest="120">
                    <ffimageloading:CachedImage.Transformations>
                        <fftransformations:CircleTransformation />
                    </ffimageloading:CachedImage.Transformations>
                </ffimageloading:CachedImage>
                <Entry
                    Grid.Row="1"
                    Grid.Column="0"
                    Placeholder="{language:Translate FirstNamePlaceholder}"
                    Style="{StaticResource DefaultMaterialEntryStyle}"
                    Text="{Binding FirstName}" />
                <Entry
                    Grid.Row="2"
                    Grid.Column="0"
                    Placeholder="{language:Translate LastNamePlaceholder}"
                    Style="{StaticResource DefaultMaterialEntryStyle}"
                    Text="{Binding LastName}" />
                <Entry
                    Grid.Row="3"
                    Grid.Column="0"
                    Placeholder="{language:Translate UsernameText}"
                    Style="{StaticResource DefaultMaterialEntryStyle}"
                    Text="{Binding UserName}" />
                <Entry
                    Grid.Row="4"
                    Grid.Column="0"
                    Placeholder="{language:Translate ExternalProviderEmailText}"
                    Style="{StaticResource DefaultMaterialEntryStyle}"
                    Text="{Binding Email}" />
            </Grid>

The same code moves entry up when page is not inside shell

**Comment by rmarinho** [comment]
Hi, you need to wrap your Grid on ScrollView and then it will work in both platforms, android and iOS and shell. 

Thanks
