### ISSUE TITLE
[Bug] macOS is using unusual button style

### ISSUE THREAD

**Issue by krdmllr** [xamarin/Xamarin.Forms#8093]
macOS provides different button styles, here is a nice writeup about it: https://mackuba.eu/2014/10/06/a-guide-to-nsbutton-styles/

You mostly see the NSRoundedBezelStyle in macOS, like in the settings app.
<img width="752" alt="grafik" src="https://user-images.githubusercontent.com/11095003/67129169-1d798080-f1fe-11e9-9301-5357a6de104c.png">

But Xamarin.Forms uses this style ( "0" which does not even exist in the enum somehow https://docs.microsoft.com/en-us/dotnet/api/appkit.nsbezelstyle?view=xamarin-mac-sdk-14)
<img width="690" alt="grafik" src="https://user-images.githubusercontent.com/11095003/67129652-857c9680-f1ff-11e9-86c1-7480fb676a81.png">

So I would suggest using the round style instead.
<img width="695" alt="grafik" src="https://user-images.githubusercontent.com/11095003/67129823-e6a46a00-f1ff-11e9-9d24-02a3d45ea4d2.png">

**Comment by chucker** [comment]
So the underlying 'bug' here appears to be in Xamarin.Mac, where a new `NSButton` _also_ exhibits this odd default style. However, over there, you typically wouldn't run into it, as you would instead create the button in Interface Builder.

As a starting point, I made a pull request, over at #9963. It looks correct to me, but I'm not very familiar with the Xamarin Forms code base.
