### ISSUE TITLE
[Enhancement] `Binding` as `ConverterParameter`

### ISSUE THREAD

**Issue by haavamoa** [xamarin/Xamarin.Forms#8099]
## Summary
Add support of `Binding` as `ConverterParameter` for `Converter`s. ~
~~This is something that is common when you come from the Windows desktop world, and something that exists in WPF.~~

## API Changes

In order for this to work I guess that the `Binding` class needs a `BindableProperty` called `ConverterParameterProperty` that the `ConverterParameter` property refere and send to its `Converter.Convert` method. 

## Intended Use Case
```xml
<Label Text="{Binding ., 
    Converter={Converters:LastItemInListConverter}
    ConverterParameter={Binding TheList}}" />
```

This usage probably makes no sense. I imagen my `BindingContext` to be a view model that is a part of a list (`TheList`). I want to print out a special text because my item is the last item of that list. This label might be a part of a `ItemTemplate` of a `CollectionView` that has its `ItemsSource` as `TheList`. 

My converter takes the `Value` input and check if that is the last item of an `IEnumerable` type of the `Parameter` input.

The point is that I need to send two `Binding`s to my converter, and I want to use the converter `value` and `parameter` for this. I want to use these two because they make sense. You have a value for your converter (which can be a binding) and you have to send a parameter.

## Comment

When I try to do this today, `parameter` will show up as a binding, and the value can not be used. 

I have seen numerous work arounds for this, and none of them looks any good to me. 
1. Creating a compelx value that has to be bound when using the converter. The converter parse it and uses it to convert. This is  ignoring the converter parameter. 
2. Creating an extra  `BindableProperty` to the converter, and ignoring the converter parameter.

**Comment by StephaneDelcroix** [comment]
For completeness, please add a link to the WPF documentation supporting that.

**Comment by haavamoa** [comment]
> For completeness, please add a link to the WPF documentation supporting that.

This made me doubt myself, as I did not find anything regarding this in the WPF documentation.
I created a private project with `dotnet core 3 wpf` and tried out my converter, with a bound parameter. This throws an exception telling me that I can not use dependency property of `ConveterParameter` becaus it is not of type dependency property.

So I have to say that this was something it was 100% sure about, but it did not exist in `WPF`. 👎 

After going through some old WPF code, I found out that I have used `MultiValueConveter` for this in `WPF`. I do send two items to the converter, one to be the item and the other to be the list. That way I can check if the item is the last item in the list. 
I do not think that this is the best solution, because the consumer of the converter has to know about the order. This would feel more natural to use a parameter along with the value, and that both can be bound to my view-model.

So, to be honest, if this could be implemented in `Xamarin.Forms`, the `Conveter`s can actually become a lot better than how we use them in `WPF`.

**Comment by StephaneDelcroix** [comment]
a MultiBinding is the way to go. If the parameter is bindable, you have to evaluate the binding when both the value or the parameter changes, which is actually a MultiBinding.

**Comment by haavamoa** [comment]
Sounds good @StephaneDelcroix .

Could you link me the documentation for `MultiBinding` ? I struggle to find this on the webs.

**Comment by StephaneDelcroix** [comment]
> Could you link me the documentation for MultiBinding

🤪 we don't have that yet

**Comment by Colima-97** [comment]
> Sounds good @StephaneDelcroix .
> 
> Could you link me the documentation for `MultiBinding` ? I struggle to find this on the webs.

This [article](https://xamgirl.com/understanding-multi-binding-in-xamarin-forms/) from [XamGirl](https://xamgirl.com/) guided me really well.

Hope it helps someone else!
