### ISSUE TITLE
[Bug] Random Disappearance and miss alignment in text while scrolling up and down when using "ListViewCachingStrategy: RecycleElement"

### ISSUE THREAD

**Issue by amr-moomen** [xamarin/Xamarin.Forms#8102]
### Description
when scrolling down and up again labels randomly truncated and miss alignment
but  when " <ListViewCachingStrategy>RecycleElement</ListViewCachingStrategy> " is commented the issue seems to be solved
### Steps to Reproduce

1. Add a ListView with ListViewCachingStrategy=RecycleElement.
2. Within ListView use a label. 
3. scroll down and up again.

### Expected Behavior

Labels are not truncated 
Labels are not miss aligned in case of using different languages (arabic and english)

### Actual Behavior

Labels are randomly truncated
miss aligned in case of using different languages (arabic and english)

### Basic Information
- Version with issue: 4.1.0.555618
- Last known good version: 2.3.4.247
- IDE: VS2019 16.2.5
- Affected Devices: Android 9.0 API 28

### Screenshots

![121](https://user-images.githubusercontent.com/56504816/67158385-aea04280-f337-11e9-9f93-60fab14895e7.PNG)

![123](https://user-images.githubusercontent.com/56504816/67157312-ce7d3980-f32a-11e9-9580-b5095c40dd12.png)

### Reproduction Link

https://github.com/amr-moomen/Listview-Bug.git

**Comment by hudaIT** [comment]
Same issue for me too. Additionally it seems to happen even more often when we use **StringFormat** for the text of the label.

**Comment by hartez** [comment]
This is fixed in 4.3.0.

**Comment by amr-moomen** [comment]
@hartez @samhouts 
it work well but when i add HasUnevenRows="True" to listview it still truncate and miss alignment the text

**Comment by amr-moomen** [comment]
and when used CollectionView it has the same problem 
https://github.com/xamarin/Xamarin.Forms/issues/8364
