### ISSUE TITLE
CollectionView - no way to remove the checkbox when in "multiple" selection mode

### ISSUE THREAD

**Issue by EvoPulseGaming** [xamarin/Xamarin.Forms#8110]
All your examples show collectionview with "multiple" selection mode, do not have check boxes. 

I noticed the examples are 4.1, did something change in 4.2? (even in 4.3.0.908675)

For the life of me, I cannot find a way to remove these checkboxes.

If I go through the Live Visual Tree, and select the ListViewItemPresenter, I can set
CheckMode to overylay, I can get the checkbox to go away, but then the highlighting is broken.

Either ways, I have no way to set this up the way your examples show.

Another thing, multi select is invisible on android in 4.3.0.908675 (no checkboxes, but no highlight either using grid layout)

**Comment by EvoPulseGaming** [comment]
So i'm noticing varying behavior depending on where its ran. On android I don't have check boxes, on UWP I do.

But even on UWP depending on how I setup my item template, I can see "disabled" checkboxes on the right in single mode....

I believe all of this should be unified under a single parameter, and the behavior should be universal.

**Comment by hartez** [comment]
The checkboxes are the default multiple selection mode for UWP. 

We could create a Platform Specific for UWP to remove the checkboxes.

**Comment by hartez** [comment]
Enhancement proposal: #8216
