### ISSUE TITLE
[Bug] GetCustomAttribute on inherited property throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by Steve887** [xamarin/Xamarin.Forms#8112]
### Description
I ran into an interesting situation trying to get Entity Framework working in my Xamarin application which I have narrowed down to what seems to be a bug internally. This may be the wrong place to post this as it may be better on the Mono, or AspNetCore repos so I will move if required.

The bug occurs when you call GetCustomAttribute on an inherited property's GetMethod ReturnParameter. This results in an `IndexOutOfRangeException`. However, if the same code is called from a `netcoreapp3.0` application it works as expected.

The exception occurs inside the internal `InternalParamGetCustomAttributes` method.

The setup for this reproduction comes from Entity Framework Core's [NonNullableConventionBase](https://github.com/aspnet/EntityFrameworkCore/blob/v3.0.0/src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs) which is called during Model setup, but Entity Framework is not required to reproduce.

    var works = typeof(Blog).GetProperty("Url").GetMethod.ReturnParameter.GetCustomAttribute(typeof(AttributeUsageAttribute));
    var worksAlso = typeof(Blog).GetProperty("Id").GetMethod.ReturnParameter.GetCustomAttribute(typeof(AttributeUsageAttribute));
    var fails = typeof(Blog).GetProperty("Author").GetMethod.ReturnParameter.GetCustomAttribute(typeof(AttributeUsageAttribute));

    public class Blog : BaseBlog
    {
        public int Id { get; set; }
        public string Url { get; set; }
    }

    public class BaseBlog
    {
        public string Author { get; set; }
    }

### Steps to Reproduce

1. Call `GetMethod.ReturnParameter.GetCustomAttribute` on an inherited property.

### Expected Behavior
The Custom Attribute is returned, or null if it doesn't exist.

### Actual Behavior
`System.IndexOutOfRangeException`

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: N/A
- IDE: Visual Studio 2019 16.3.5
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.1

### Screenshots

![image](https://user-images.githubusercontent.com/129719/67183978-0321eb80-f426-11e9-80af-186f945f8afc.png)

![image](https://user-images.githubusercontent.com/129719/67183995-0ddc8080-f426-11e9-987e-53639a8ec1e8.png)

### Reproduction Link

[IndexOutOfRangeException.zip](https://github.com/xamarin/Xamarin.Forms/files/3749458/IndexOutOfRangeException.zip)
Switch startup project between the Console app and Android app to see the issue.

**Comment by StephaneDelcroix** [comment]
Thanks for this report. Unfortunately, there's nothing we can do here, please open an issue to the appropriate project instead.

**Comment by Steve887** [comment]
Do you know which project would be most appropriate for this?

**Comment by mindphaser** [comment]
Got this issue today when tried to migrate EF Core from 2.2.6 to 3.0.0 in Xamarin Forms project.

**Comment by AdamJachocki** [comment]
Same here. Xamarin.Forms in .netstandard 2.1
Android application:

ctx.Database.Migrate() <-- throws IndexOutOfRangeException. Does this work anyway? Last output from debug:

11-08 10:59:02.887 D/Mono    ( 6252): Loading reference 0 of Microsoft.Extensions.Identity.Stores.dll asmctx DEFAULT, looking for Microsoft.Extensions.Identity.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
11-08 10:59:02.887 D/Mono    ( 6252): Assembly Ref addref Microsoft.Extensions.Identity.Stores[0xe76acd00] -> Microsoft.Extensions.Identity.Core[0xe76acca0]: 3
**System.IndexOutOfRangeException:** 'Index was outside the bounds of the array.'

**Comment by mgolois** [comment]
Having same issue. Can't query EF Core 3.0 entities in Xamarin Android

**Comment by hartez** [comment]
@mgolois Does the issue persist if you disable the linker?

**Comment by mgolois** [comment]
@hartez `Linking` is disabled by default on my project
