### ISSUE TITLE
[Bug] CarouselView.PositionChangedCommand not triggered on last item when CarouselView.PeekAreaInsets not zero

### ISSUE THREAD

**Issue by HalfWayVector** [xamarin/Xamarin.Forms#8118]
### Description
Method pointed by **_CarouselView.PositionChangedCommand_** attribute doesn't seem to be triggered on the last carousel item when **_CarouselView.PeekAreaInsets_** is not zero. It works as expected when value is zero.

### Steps to Reproduce

1. Access [this](https://github.com/HalfWayVector/CarouselViewBug) repository.
2. Launch the sample on Android.
3. Scroll to the last item (4th page).

### Expected Behavior
Page indicator at the bottom should show the text _"4 of 4"_

### Actual Behavior
Page indicator at the bottom shows the text _"3 of 4"_

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.1258-nightly
- IDE: Microsoft Visual Studio Community 2019
- Platform Target Frameworks: 
  - Android: Android 9.0 (API Level 28 - Pie)

**Comment by rmarinho** [comment]
This is fixed on 4.4.0.991757 stable
