### ISSUE TITLE
[Enhancement] Directional animations when using PushModalAsync

### ISSUE THREAD

**Issue by MarcKammermann** [xamarin/Xamarin.Forms#8120]
## Summary
It would be great if one could decide the direction of the page animation when pushing a page onto the stack. Right now it goes from bottom to top and it cant be changed at all. The boolean parameter could just be changed to a directional statement or a state of not animating at all.
In my opinion it doesnt make any sense at all to not be able to determine this parameter.

**Comment by hartez** [comment]
Closing this in favor of #8122.
