### ISSUE TITLE
[Enhancement] PushModalAsync: Page transition animations

### ISSUE THREAD

**Issue by MarcK95** [xamarin/Xamarin.Forms#8123]
## Summary
Would be very helpful if one could style the animation when pushing a page onto the stack.
Right now its animating from bottom to top and theres no possibility to change this at all.

## API Changes

The boolean parameter when performing the push could be changed to a directional statement or the state of no animation at all.

e.g.
<code>[...].PushModalAsync(new Page_A(), Left);</code>

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by lavilaso** [comment]
In [#6033](https://github.com/xamarin/Xamarin.Forms/issues/6033) they are working on an api specification for this.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
