### ISSUE TITLE
[Bug] CollectionView throws InvalidOperationException on UWP

### ISSUE THREAD

**Issue by pauldipietro** [xamarin/Xamarin.Forms#8125]
### Description

Found a startup crash that occurs as of the latest nightly when doing some testing (root cause could have been introduced prior). Downgraded to 4.3-pre3 and it's able to start as normal.

### Steps to Reproduce

1. Grab the WeatherColors repo (https://github.com/davidortinau/weathercolors)
2. Update to the latest nightly and run the project

### Expected Behavior

App starts as expected.

### Actual Behavior

App throws `System.InvalidOperationException: 'Cannot change ObservableCollection during a CollectionChanged **event.'**`

### Basic Information

- Version with issue: 4.4 nightly
- Last known good version: 4.3.0-pre3

### Reproduction Link

https://github.com/davidortinau/weathercolors

**Comment by jsuarezruiz** [comment]
Hey @pauldipietro. I have followed the steps but I cannot reproduce the problem in Xamarin.Forms 4.4 nightly.
The error is launching the App?, is there something I still have to do to reproduce it?.
<img width="708" alt="Captura de pantalla 2019-10-23 a las 14 17 58" src="https://user-images.githubusercontent.com/6755973/67391949-f6290780-f59f-11e9-8d05-bdb8788f9321.png">

**Comment by samhouts** [comment]
@pauldipietro  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
