### ISSUE TITLE
Investigate removing/changing all uses of Stack<T> and Queue<T>

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8126]
## Summary
These types were moved 
https://github.com/mono/mono/pull/11511

If you compile anything on mono after this move it will fail to run on anything running mono before the move

Which is what led to the following issue https://github.com/xamarin/Xamarin.Forms/issues/7602. VS 2019 includes the moved types whereas VS 2017 (and VS Mac versions pre 8.3)  don't. So in order to utilize newer VS 2019 build tools but still remain VS 2017 compatible we'll need to remove all uses of Stack<T> and Queue<T>

As far as we know these are the only types that have been moved so in theory if we remove all uses of these types then we can start building our libraries against VS 2019 images which will let us build against Xcode11, Android10, and newer UWP APIs

## What to test after this change
In a perfect world we could run our Control Gallery built with VS 2017 against a nuget built with VS 2019 so that our whole suite of UI tests can validate.

In a world where time isn't infinite we'll want to dogfood the nuget built with VS 2019 on VS 2017. Make sure templates work, any dog food applications we have, smarthotel, etc...

### Copy the source code of Queue<T> and Stack<T> to our own types

The code for both of these is pretty simple
https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Stack.cs

https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Queue.cs

### Queue and stack api can be written on top of list
I expect the perf to be good enough (given that List perf is really good)

**Comment by samhouts** [comment]
I think we should just copy the implementations from CoreFX (include links to the originals in the source files). Let's target 4.3 for this and see how it goes.

**Comment by krdmllr** [comment]
If this is resolved we can resolve this one https://github.com/xamarin/Xamarin.Forms/issues/7894 right?

**Comment by samhouts** [comment]
closed by #8403
