### ISSUE TITLE
[Bug] Adding children to iOS VisualElementPackager has O(N^2) performance and thrashes the native layer

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8129]
### Description

Every time a single child is added
https://github.com/xamarin/Xamarin.Forms/blob/e9eb9fe56094504e37e8a63691bfa4639876d60c/Xamarin.Forms.Platform.iOS/VisualElementPackager.cs#L48

EnsureChildrenOrder is called
https://github.com/xamarin/Xamarin.Forms/blob/e9eb9fe56094504e37e8a63691bfa4639876d60c/Xamarin.Forms.Platform.iOS/VisualElementPackager.cs#L108

Which then loops through all the logical  children again
https://github.com/xamarin/Xamarin.Forms/blob/e9eb9fe56094504e37e8a63691bfa4639876d60c/Xamarin.Forms.Platform.iOS/VisualElementPackager.cs#L132

to ensure the Z Index is correctly set.

The code should add all the children first and then process the child order (2N) or just process the child order as things are added for the first time (N) 

### Steps to Reproduce

Modify this test

https://github.com/xamarin/Xamarin.Forms/blob/9eb857571e6a6e7eeae20676df37a35c01bb1ea3/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/RefreshViewTests.cs#L34

So that it adds some large number of children (2000)

If you run the test on Android then Android renderers fine but if you try to run it on iOS the UI just locks while all the children are getting added

### Expected Behavior
A stacklayout with 2000 items shouldn't completely lock iOS. I realize adding 2000 items is a bit of an extreme edge case but the fact that Android renderers it fine and iOS completely locks up is indicative of an exponentially increasing performance issue

### Actual Behavior
A stacklayout with 2000 items completely locks iOS but not Android

### Basic Information

- Version with issue: master
- Last known good version: not sure
- IDE:
- Platform Target Frameworks: 
  - iOS:  All versions

**Comment by adrianknight89** [comment]
Lately, CollectionView wrapped by RefreshView is freezing on iOS (with only a few items) when I scroll to the bottom though it may be an entirely different issue. This is an interesting find. On first look, I definitely do not like Forms calling `BringSubviewToFront` for every child.

**Comment by shanranm** [comment]
Moved the ordering just after adding it the first time.
When a new Child is added we anyway are calling EnsureChildrenOrder, so shouldn't effect runtime changes.

**Comment by AlleSchonWeg** [comment]
Hi,

is there any workaround available or will the PR find its way in the next SR? 
c'mon
