### ISSUE TITLE
Strange keyboard behavior when using controls inside ListView Footer

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8132]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/780641/strange-keyboard-behavior-when-using-controls-insi.html)._

---
When putting multiple Entrys, Pickers, etc inside the Footer of a ListView, I get inconsistent behavior. Often, the keyboard I specify for the entry will initially appear, but then a different one will appear. Sometimes, when I click the Entry, the options for the picker will appear instead.

This behavior also only  occurs on some phones.

If I put the contents of the Footer outside of a listview, everything works just fine.

---
#### Visual Studio Feedback System on 10/17/2019, 07:24 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by LakeLobster** [comment]
I'm the person that submitted the visual studio bug report. I can provide additional details upon request.

Notably, I've found this issue on a Motorola Moto G4 (Android 7.0), as well as a Samsung Galaxy S7 (8.0). I have not experienced it on a Pixels 3 (android 9.0) 

If you have one of those phones, here is an example that seems to trigger the behavior.

If you build these two files into a bare-bones project, then click on the 'alpha' and 'beta' entries in the layout. You should find that the application does not respect the requested keyboard layouts.

When I run it in a 7.0 emulator, I get even weirder results, with both a keyboard and the picker options appearing.

MainPage.xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:XamKeyboardBugDebug"
             x:Class="XamKeyboardBugDebug.MainPage">
    <ListView ItemsSource="{Binding Stuff}" SelectionMode="None" HasUnevenRows="True" Margin="5">
        <ListView.Footer>
            <StackLayout Margin="0,15">
                <Label Text="Foobar:" FontSize="Medium" FontAttributes="Bold"/>
                <Grid>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto"/>
                        <ColumnDefinition Width="40"/>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="Auto" />
                    </Grid.ColumnDefinitions>

                    <Picker ItemsSource="{Binding Delta}" SelectedItem="{Binding Gamma}"  Grid.Column="1"  />
                    <Entry Placeholder="alpha" Text="{Binding Alpha}" Grid.Column="2" Keyboard="Plain" />
                    <Entry Placeholder="beta" Text="{Binding Beta}" Grid.Column="0" Keyboard="Numeric"/>
                </Grid>
            </StackLayout>
        </ListView.Footer>
    </ListView>
</ContentPage>
```

App.xaml.cs:

```
using System;
using System.Collections.ObjectModel;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
namespace XamKeyboardBugDebug
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();
            MainPage.BindingContext = new Thing();
        }       
    }

    public class Thing
    {
        public ObservableCollection<String> Stuff { get; set; } = new ObservableCollection<string>()
                                                                        {
                                                                            "Do", "Re", "Mi", "Fa"
                                                                        };

        public string Alpha { get; set; } = "";
        public string Beta { get; set; } = "";

        public string Gamma { get; set; } = "#";

        public string[] Delta { get; } = new string[]
                                         {
                                             "#","b","x","bb"
                                         };
    }
}
```

**Comment by hartez** [comment]
@LakeLobster What version of Xamarin.Forms are you testing with?

**Comment by LakeLobster** [comment]
@hartez looks like 4.1.0.581479 when I submitted the ticket.

I updated to the latest in nuget, 4.3.0.908675, and the problem persists on the MotoG phone. However, the problem has gone away on the emulator, and that seems to work normally. I'll see if I can update the example above to reproduce the error on the emulator in the next few days.

I've also found that the keyboard that does appear is always the first specified type in the xaml file. In the example above, if you re-order the two `Entry`s, the numeric keyboard will appear exclusively.

FWIW, if the plain keyboard appears instead of the numeric that I request, it does restrict entry to only the numbers.

**Comment by jfversluis** [comment]
#7141 might be related to this

**Comment by jfversluis** [comment]
Added repro. I've tried a couple of emulators (API 24, 27 and 29) and did not see this behavior with the latest stable Xamarin packages. Will try again on a physical device, or if someone else is willing to try in the meantime you are more than welcome

[Repro8132.zip](https://github.com/xamarin/Xamarin.Forms/files/3880094/Repro8132.zip)

**Comment by jfversluis** [comment]
I have tried this on a Samsung S10e (API 28) and a Xiaomi Redmi 4 (API 24) and the emulators I mentioned above and everything seems to work fine. @LakeLobster would you be able to confirm that you still see this behavior with the latest packages?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
