### ISSUE TITLE
Image display problem with Image tag in iOS XAML

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8133]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/757710/probleme-daffichage-dimage-avec-la-balise-image-da.html)._

---
Hello

I want to inform you of a bug I encountered, the image tag does not work on iOS, the images are external to the application. Downloaded from a server via the url of the image, in https.

here's an example I used: 
&lt;image&gt;
Image.source
UriImageSource Uri's URL link
&lt;/image.source&gt;
&lt;/image&gt;

Instead I used the FFImageLoading.forms plugin (which only works for iOS) to solve my problem.
Your documentation does not provide any explanation and lacks serious clarity, the solution was provided to me on the Forum of StackOverflow.

I seriously hope that this solution will be resolved.

Kind regards.

---
#### Visual Studio Feedback System on 10/2/2019, 08:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
