### ISSUE TITLE
Setting the Alpha of ContentPage's BackgroundColor is broken.

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8134]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/722708/setting-the-alpha-of-contentpages-backgroundcolor.html)._

---
#### What steps will reproduce the problem?
1. On a Shell Project
2. Add a *ContentPage* to your project
3. Change the *BackGroundColor* of the *ContentPage* to black and pick an **Alpha** of your choice
4. Add 2 buttons to another Page that opens the *ContentPage* above
5. Set one button to open the *ContentPage* using *PushAsync*, and the other using *PushModalAsync*. Set animation to *false* on both.

#### What is the expected output? What do you see instead?
I expect that when the *ContentPage* is opened with either of the buttons, that the *BackgroundColor* should obey the alpha settings and be transparent enough to see thorough to the contents of the previous page (the page below with the buttons), instead it does not obey the **Alpha** settings at all with *PushModalAsync*, and **sometimes** obey with *PushAsync*.

ps. If *Transparent* is used as the *BackgroundColor*, with *PushAsync*, it shows the content of the previous page, but with *PushModalAsync* it shows a white background and the previous page cannot be seen.

ps. Being able to set an *Alpha* for the background allows you to simulate a custom alert page easily. Like showing custom info in a box with controls needed (eg. Entry control) in the center of the screen and dim the rest of the page just enough with an *Alpha* to be able to see through to the previous page. Or maybe add a feature that shows a page as an alert instead of displaying it full screen.

---
#### Visual Studio Feedback System on 9/5/2019, 01:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 10/11/2019, 00:11 AM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
