### ISSUE TITLE
Intellisense cannot discover Orientation for LinearItemsLayout and GridItemsLayout

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/Xamarin.Forms#8139]
### Description

The `Orientation` property seems to be a constructor parameter unlike item spacing properties which are bindable. Intellisense (currently tested using ReSharper) cannot discover `Orientation`. The examples [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout) use `Orientation` as a markup attribute, and it is confusing to the user if Intellisense cannot find it.

Ref: #5802

### Expected Behavior
`Orientation` should be discoverable by Intellisense.

**Comment by adrianknight89** [comment]
@jsuarezruiz Does this also need the `a/collectionview` label added?

**Comment by davidortinau** [comment]
I'm seeing intellisense for Orientation. 

<img width="680" alt="Screen Shot 2020-12-06 at 10 20 09 PM" src="https://user-images.githubusercontent.com/41873/101309147-49483300-3811-11eb-9953-84258926ac44.png">
<img width="627" alt="Screen Shot 2020-12-06 at 10 19 43 PM" src="https://user-images.githubusercontent.com/41873/101309148-49e0c980-3811-11eb-968d-2fc944c2745e.png">
