### ISSUE TITLE
[Enhancement] Force localization for DatePicker

### ISSUE THREAD

**Issue by PrvnKmr** [xamarin/Xamarin.Forms#8141]
### Description
Localization doesn't work inside the DatePickerRenderer. I am trying to change the language within the app. I set the Locale inside the renderer, but the DatePicker still shows the title in English

### Steps to Reproduce

1. Add a custom date picker extending the DatePickerRenderer class in Android. 
2. Set the locale to "de-DE"
3. Tap on the date picker and verify the language inside the fragment.

### Expected Behavior
Every text should correspond to the Locale set. i.e, German in this case. 

### Actual Behavior
The title of the DatePicker is still in English

### Basic Information
I tried out many solutions found over the internet. Below is the final piece of code which I have to translate atleast portions of the Datepicker

```
public class CustomDatePIckerRendererDroid : DatePickerRenderer
    {
        private Context _context;
        public CustomDatePIckerRendererDroid(Context context): base(context)
        {
            _context = context;
        }

        protected override void OnElementChanged(ElementChangedEventArgs<DatePicker> e)
        {
            base.OnElementChanged(e);

            var ci = new System.Globalization.CultureInfo("de-DE");
            //System.Threading.Thread.CurrentThread.CurrentCulture = ci;
            //System.Threading.Thread.CurrentThread.CurrentUICulture = ci;

            Locale locale = new Locale(ci.TwoLetterISOLanguageName);
            Control.TextLocale = locale;

            Android.Content.Res.Configuration config = new Android.Content.Res.Configuration();
            config.Locale = locale;
            Locale.SetDefault(Locale.Category.Format, locale);

            Resources.Configuration.SetLocale(locale);
            Resources.Configuration.Locale = locale;
            _context.Resources.UpdateConfiguration(config, _context.Resources.DisplayMetrics);
        }
    }
```

- Version with issue:
- Last known good version:
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android:  8.1
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![Screenshot_2019-10-22-12-25-09-551_com companyname demotest](https://user-images.githubusercontent.com/44190025/67264383-927fdb00-f4c8-11e9-8f1b-c80ad7e30cb6.png)

**Comment by hartez** [comment]
You don't need to do any customization to get a localized DatePicker - just run on a device with the language set to de-DE and it will localize the control for you:

![Screenshot_20191027-162542](https://user-images.githubusercontent.com/538025/67642965-04945d80-f8d7-11e9-9d9c-8bd12b2b0f38.jpg)

Is there some reason you need to localize it manually?

**Comment by PrvnKmr** [comment]
Hi @hartez ,

The localization is fine when device locale is changed. But in my case, this is not enough.

The application provides user a provision where he can change the application language. In this case we would need to set the application locale without changing the device language. 

Thanks,

Praveen

**Comment by samhouts** [comment]
@PrvnKmr We don't currently have a way to force localization manually. I will mark this as an enhancement, and we'll review it. Thanks!

**Comment by gutierrezralph** [comment]
Please consider this feature as High importance because most of enterprise app were used globally and we can't force all the users to change their keyboard language.

**Comment by DeerSteak** [comment]
would also love to see this. I'm currently trying to sort this same thing out myself.

**Comment by hammondreg** [comment]
I must agree with DeerSteak and rapcgutz - if Xamarin is to be used as a 'global' Forms front-end, then it must have the ability to be totally and completely and utterly configured by the USER and not have a configuration imposed on them by the developers (and I include myself in that category as well as you kind, thoughtful and helpful Xamarin developers) nor by the device they just happen to be using.  This is 2021 after all!

**Comment by tlaivo** [comment]
Is there any schedule to get this fixed? There seems to be a similar problem with TimePicker in Android.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
