### ISSUE TITLE
[Bug] System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Android.Support.Design.Widget.BottomSheetDialog'.'

### ISSUE THREAD

**Issue by joeljaisi** [xamarin/Xamarin.Forms#8145]
With release 4.3 of Xamarin Forms, a bug has surfaced when using the Shell App template. When I have many pages in the ToolBar, about 4 tabs show at the bottom of the shell and the others will be under the 'More' ellipsis. If you open the ellisis and select a page, the app crashes with the error "System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Android.Support.Design.Widget.BottomSheetDialog'.'

### Steps to Reproduce

1. Create a Shell App in version 4.3.0.908675  or 4.2.0.910310 of forms
2. Add more ToolBar pages so that they overflow to show an ellipsis
3. run the app and try to navigate to a page in the ellipsis section

### Expected Behavior
Page should show as it does in earlier versions of the Xamarin Forms

### Actual Behavior
The App crashes with error

"System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'Android.Support.Design.Widget.BottomSheetDialog'.'

### Basic Information

- Version with issue: 4.2.0.910310 and 4.3.0.908675
- Last known good version:  4.2.0.848062
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
   - Android: 10 

- Android Support Library Version: 28
- Nuget Packages: 
- Affected Devices: All

**Comment by joeljaisi** [comment]
I updated to Xamarin.Forms 4.3.0.947036 and the issue is NOT fixed!
![Capture](https://user-images.githubusercontent.com/54362449/67835511-dab78280-faf2-11e9-9aad-60a13d5398a9.PNG)
!

**Comment by joeljaisi** [comment]
Seems the bug is not fixed as per Xamarin.Forms 4.3.0.947036

-----------------------------------------------------------------------------------------------

Regards



*Joel JaisiSoftware Engineer/Developer/Architect; ICT Consultant *MSE,
BBSCT, SMC,
SDC, MCT, MCSD, MCPD, MS, MCTS
Phone: +265 993 708 536 (Malawi)
              +263 772 566 069 (Zimbabwe)
Skype: joel.jaisi
Email:  jjaisi@gmail.com
Alt. Email: jjaisi@hotmail.com

-----------------------------------------------------------------------------------------------

**Comment by joeljaisi** [comment]
Hi @rmarinho  and @samhouts  and @jsuarezruiz This issue #8145 was hastily closed while the bug is not fixed. The problem still persist even after i updated my Xamarin.Forms to current stable version 4.3.0.947036. Please relook at it. The issue can still be reproduced with the steps in the issue report.

**Comment by hartez** [comment]
@joeljaisi The fix is in 4.3.0.991211 (released 4 days ago). Please update to that version and give it a try. If you still see it in that version, I will reopen this issue.

**Comment by joeljaisi** [comment]
I can confirm that this is fixed now, thanks.

Regards
Joel Jaisi

**Comment by DeliriumCode** [comment]
This bug is still not fixed...
I am seeing this on xamarin.forms 4.7.0.1142

To reproduce, on android, create a basic bottom tab based shell app with 6+ tabs, run the app and repeatedly click the more tab. I believe the issue is a double click of the more button that causes the app to crash. I am seeing this issue on live and have no special modifications its just a basic shell app with 7 tabs....
