### ISSUE TITLE
[Enhancement] Embedding XF-Open Xamarin Forms "Page" from Xamarin.Android

### ISSUE THREAD

**Issue by saamerm** [xamarin/Xamarin.Forms#8153]
## Summary
As you can see in the current Xamarin PageExtensions available for [Android][2] and [iOS][3], Xamarin allows you to convert any type of `Xamarin.Forms`(XF) `Page` to a native `ViewController` in iOS, but it only allows converting a XF `ContentPage` to a native `Fragment` in Android. 

The XF `Page` plays a major role when you are trying to implement an XF `NavigationPage` or `TabbedPage` allowing for a dashboard with tabs and subsequently being able to navigate between pages without having to go back into native code. So, currently I can handover complete control to XF on iOS, but on Android I can only use XF to display a single `ContentPage` with no control over navigation. 

My request is to extend the API to allow opening an XF `Page` from `Xamarin.Android`, rather than just a `ContentPage`.

## API Changes

This would require creating an overridden constructor in the `Xamarin.Forms.Platform.Android /AppCompat/PageExtensions.cs` file referenced above that would take a `Page` and instead of a `ContentPage`. I am not sure of the other changes this would require to make this happen in the `Xamarin.Forms.Platform.Android` project.

## Intended Use Case
This would be great for teams trying to use XF [Embedding][1] to convert projects from using `Xamarin.Native` to XF, for easier maintenance & implementation of features. 

**[Added Explanation](stackoverflow.com/posts/58508566):** You can open NavigationPages on [iOS, as you can see in this sample here][4] which allows using functions like `PushAsync` or `PopAsync`, by simply doing:
```
UIViewController user2 = new NavigationPage(new TestPage()).CreateViewController();
```
-------------------------------
So for [Android as seen here][5], currently we can only do this: ✅ 
```
Android.Support.V4.App.Fragment fragment = new TestPage().CreateSupportFragment(this);
```
and we need to create a way to do something like this: ❌ 
```
Android.Support.V4.App.Fragment fragment = new NavigationPage(new TestPage()).CreateSupportFragment(this);
```

*PS: Here's a [sample Github][6] that contains a playground created as a Spike. If someone knows of a work around, please let me know.*

  [1]: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms
  [2]: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/PageExtensions.cs#L75
  [3]: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/PageExtensions.cs#L8
  [6]: https://github.com/saamerm/XamarinFormsInsideXamarinNative
  [4]: https://github.com/saamerm/XamarinFormsInsideXamarinNative/blob/4e50edfb2cf38ecb31e505bb0e1a98d9bab614b1/BlankNativeApp/iOS/ViewController.cs#L24
  [5]: https://github.com/saamerm/XamarinFormsInsideXamarinNative/blob/4e50edfb2cf38ecb31e505bb0e1a98d9bab614b1/BlankNativeApp/Droid/FormsNavigationActivity.cs#L27

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by saamerm** [comment]
@jfversluis thank you! I added it as a request https://github.com/dotnet/maui/issues/9606
