### ISSUE TITLE
[Bug] [iOS] Label with HTML does not replace Umlaut characters properly

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#8156]
### Description

The HTML content is not correctly displayed because the label does not use UTF-8 (or escape the Umlaut characters like Ä, Ö, Ü, ä, ö, ü and ß) as I would expect it (because this display issue is not the case on the normal text input and neither is it on Android). 

### Steps to Reproduce

1. Place a Label with HTML content containing one or multiple of the mentioned characters

### Expected Behavior

Should display the text properly

### Actual Behavior

Error / placeholder / replacement characters are shown

### Basic Information

- Version with issue: 4.3
- Last known good version: -
- IDE: Latest stable VS for Mac Enterprise
- Platform Target Frameworks: 
  - iOS: Tested with iOS 13.1

### Screenshots

The translator section is a Label with HTML content. It was previously correctly formatted with white text, centered and no misplaced characters. I was using the [HtmlLabel](https://github.com/matteobortolazzo/HtmlLabelPlugin) plugin previously. 
![Simulator Screen Shot - iPhone 11 - 2019-10-22 at 21 39 30](https://user-images.githubusercontent.com/25636075/67324973-aa7d4c00-f514-11e9-9ffe-0044aa3b0bbd.png)

### Reproduction Link

Way too easy to reproduce to make a whole reproduction repo for it...

**Comment by hartez** [comment]
See also #8157, #8158, #8159

**Comment by hartez** [comment]
Repro:
[_8157 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3760181/_8157.Repro.zip)
