### ISSUE TITLE
[Bug] [iOS] Label with HTML does not use applied text color

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Xamarin.Forms#8157]
### Description

The HTML is always black on iOS even if TextColor is set to white.

### Steps to Reproduce

1. Place a Label with HTML content and a different text color

### Expected Behavior

Should display the text properly

### Actual Behavior

Always black text color

### Basic Information

- Version with issue: 4.3
- Last known good version: -
- IDE: Latest stable VS for Mac Enterprise
- Platform Target Frameworks: 
  - iOS: Tested with iOS 13.1

### Screenshots

The translator section is a Label with HTML content. It was previously correctly formatted with white text, centered and no misplaced characters. I was using the [HtmlLabel](https://github.com/matteobortolazzo/HtmlLabelPlugin) plugin previously. 
![Simulator Screen Shot - iPhone 11 - 2019-10-22 at 21 39 30](https://user-images.githubusercontent.com/25636075/67324973-aa7d4c00-f514-11e9-9ffe-0044aa3b0bbd.png)

### Reproduction Link

Way too easy to reproduce to make a whole reproduction repo for it...

**Comment by hartez** [comment]
See also #8159, #8158, #8156

**Comment by hartez** [comment]
Repro project:

[_8157 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3760179/_8157.Repro.zip)

**Comment by lester-fh** [comment]
I can confirm that html text with no other coloring embedded in the value still shows up with black TNR style of text on iOS where it respects at least TextColor on android.  as of 4.6.  Makes the TextType = HTML on a label really pretty worthless.

**Comment by IainCoSource** [comment]
It affects font size as well as colour. 

Xamrin.Forums: 4.6.0.800

**Comment by IainCoSource** [comment]
So bumped everything up to 4.8.0.1238-pre3 in the Monkey CSS App in Xamrin samples

` <Label TextType="Html" FontAttributes="Bold" FontSize="20" HorizontalTextAlignment="End" TextColor="Red" Text="4.8.0.1238-pre3" >`

![image](https://user-images.githubusercontent.com/49510009/89033369-ee6c6f80-d336-11ea-8c16-f64acdf0c174.png)

` <Label TextType="Html" FontAttributes="Bold" FontSize="20" HorizontalOptions="Center" TextColor="Red" Text="4.8.0.1238-pre3" >`
 
![image](https://user-images.githubusercontent.com/49510009/89033451-13f97900-d337-11ea-9347-e1ffc5774539.png)

**HorizontalTextAlignment** is still not working in either XAML attribute or CSS class.

CDATA works well inside the XAML tag and setting HTML from code works as well

**Comment by rachelkang** [comment]
It appears that most of these issues were fixed in XF 4.8
The only remaining issue appears to the the one relating to HorizontalTextAlignment, which will be fixed by #13197 

Tested against repro linked earlier in this thread https://github.com/xamarin/Xamarin.Forms/files/3760179/_8157.Repro.zip
