### ISSUE TITLE
 [Bug] On WPF ToolbarItem.IsEnabled = false does nothing

### ISSUE THREAD

**Issue by observer1** [xamarin/Xamarin.Forms#8161]
### Description
Changing the isEnabled property of a ToolbarItem in code to false does nothing
### Steps to Reproduce

1. 
Put a ToolbarItem in a page
2. 
Change the property isEnabled of the ToolbarItem in code

### Expected Behavior
The ToolbarItem should disable
### Actual Behavior
The ToolbarItem is enabled
### Basic Information

- Version with issue:
4.4.0.1265-nightly
- Last known good version:
- IDE:
VS 2019
- Platform Target Frameworks: 
WPF
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
The repro for this _might_ be in #8162.

**Comment by observer1** [comment]
Its a duplicated I send it by accident, should I close it?
