### ISSUE TITLE
[Bug] Changing the isEnabled property of a ToolbarItem in code to false does nothing

### ISSUE THREAD

**Issue by observer1** [xamarin/Xamarin.Forms#8162]
### Description
Changing the isEnabled property of a ToolbarItem in code to false does nothing
### Steps to Reproduce

1. 
Put a ToolbarItem in a page
2. 
Change the property isEnabled of the ToolbarItem in code

### Expected Behavior
The ToolbarItem should disable
### Actual Behavior
The ToolbarItem is enabled
### Basic Information

- Version with issue:
4.4.0.1265-nightly
- Last known good version:
- IDE:
VS 2019
- Platform Target Frameworks: 
WPF
- Android Support Library Version: 
- Nuget Packages:
Xamarin.Forms
Xamarin.Forms.Platform.WPF
- Affected Devices:
Windows 10 pc
### Reproduction Link
[Test - Copy.zip](https://github.com/xamarin/Xamarin.Forms/files/3759064/Test.-.Copy.zip)

**Comment by hartez** [comment]
@observer1 Is this an accidental double submission of #8161?

**Comment by observer1** [comment]
Yes its a duplicate

**Comment by samhouts** [comment]
Duplicate of #8161
