### ISSUE TITLE
[Bug] Shell - TitleColor Ignored First Time Through

### ISSUE THREAD

**Issue by codemillmatt** [xamarin/Xamarin.Forms#8171]
## Description

When building an iOS app with Shell and the Flyout menu - the `TitleColor` property is ignored for each page accessed through the `ShellContent` property - but only the first time.

The `TitleColor` works as expected the second time the page loads. 

This happens whether the `TitleColor` is set on the page, within `AppShell` or via a style.

### Steps to Reproduce

1. Create an `AppShell` with several `ShellContent` properties for different pages.
2. Have a dark `Shell.BackgroundColor` set for each of those pages (can be set in `AppShell`)
3. Have a light `Shell.TitleColor` set.
4. Run the app and navigate between the pages from the flyout.

### Expected Behavior

The title color is immediately present as set.

### Actual Behavior

The `TitleColor` is the default color the first time the page is accessed. Then the next time the page is accessed the `TitleColor` is as set.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.908675
- Last known good version: ??
- IDE: VS 16.4 Preview 2
- Platform Target Frameworks:
  - iOS:  13.8.1.1
  - Android: n/a
  - UWP:  n/a 
- Android Support Library Version: n/a
- Nuget Packages:
- Affected Devices: all iOS 13 devices I've tried so far - real & simulators

### Reproduction Link

https://github.com/codemillmatt/ignite-mobile

**Comment by hartez** [comment]
@codemillmatt I'm trying to see the issue in you repro project, but as far as I can tell the TitleColor is correct the first time each page is loaded. I think I must be misunderstanding the issue.

Can you attach a couple of screenshots with annotations showing what's incorrect with the TitleColor?

**Comment by codemillmatt** [comment]
I can't make it happen any more either @hartez ... trust me - it _was_ happening, but it's working now. 😄 I'm going to close this issue out. Thanks for taking a look at it.
