### ISSUE TITLE
[Bug Xamarin.UITest] Tap doesn't work with command

### ISSUE THREAD

**Issue by ThomasCurti** [xamarin/Xamarin.Forms#8172]
Hello,

On the first page of my app I have an Image with a TapGestureRecognizer with a GestureRecognizer that uses a Command with Commandparameter -- this command starts a RelayCommand. When I Tap the image it starts another view and it works well when I do that.
I use UITest to test my UI. I start it with my device directly plug on the computer. It starts well and the test is well initialized.
After that, I flash the image with app.flash("image_id") and it works well. However when I call the app.Tap("image_id") it doesn't show the View and end the test as "succesfull".

I tried to do exactly the same thing with a button that uses the "clicked" event to show the other view, it flashes the button then shows the view without any problem.

Whenever I use a command in a component to start somthing it doesn't work with the Tap.

### Steps to Reproduce

1. Create a **custom** component --Image or whatever -- and add a command on it
2. Create a RelayCommand that does something -- whatever you want -- when it is called
3. Start the UITest and call the Tap Command on the component.

### Expected Behavior
It should call the RelayCommand.

### Actual Behavior
I doesn't do anything

**Comment by samhouts** [comment]
@ThomasCurti  Can you please attach a small project that demonstrates this issue? Thanks!
