### ISSUE TITLE
[Bug] [iOS] Label with HTML does not render

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#8173]
# Description
The following html content render correctly on Android but doesn't render at all on iOS:

### Steps to Reproduce

1. Create a page with the following label:
`<Label Grid.Row="2" Text="{Binding HtmlContent}" TextType="Html" />`
2. Create a property on VM called HtmlContent and set it's value with the following html:
```html
<p><strong>Register Today!</strong></p>
<p>&nbsp;</p>
<p><strong>Visit HASC at Booth 4654</strong></p>
<p><strong>George R. Brown Convention Center</strong></p>
<p><strong>Houston, Texas&nbsp;</strong></p>
<p>&nbsp;</p>
<p><strong>FOR NON-NSC MEMBERS:&nbsp;&nbsp;<a href="https://www.xpressreg.net/register/nscx1018/attendee/lookup.asp?sc=&amp;aban=&amp;hkey=&amp;iq=&amp;vip=&amp;tm=&amp;mt=Nonmember">Register today</a>&nbsp;and enter <span style="color: #ff0000;">20hou185</span> to receive an exclusive discount off full registration</strong></p>
<p><strong>FOR NSC MEMBERS:&nbsp;&nbsp;<a href="https://www.xpressreg.net/register/nscx1018/attendee/lookup.asp?sc=&amp;aban=&amp;hkey=&amp;iq=&amp;vip=&amp;tm=&amp;mt=Member">Register today</a>&nbsp;and enter&nbsp;<span style="color: #ff0000;">20hou185</span>&nbsp;to receive an exclusive discount off&nbsp;full&nbsp;registration&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</strong></p>
```
3. Run on Android and on iOS. It works on Android but not on iOS

### Actual Behavior
When I first enter on the page that have the Label with TextType="Html" it doesn't render anything.
However if I send the application to the background and then to the foreground it renders the HTML.
### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version:
- IDE: VS 2019 16.3.6
- Platform Target Frameworks:
  - iOS:  13.1.3
  - Android: 9
- Affected Devices: iPad

**Comment by hartez** [comment]
I'm trying to reproduce this issue, but the HTML seems to render just fine on iOS. I've attached my repro project - is there a detail I'm missing?

[_8173 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3776380/_8173.Repro.zip)

**Comment by samhouts** [comment]
@ederbond  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by zehguilherme** [comment]
I have the same problem here.

It works on Android versions, but not on iOS.

IOS Version: **14.5**
Android versions: **7 to 11**

## XAML
```xaml
<Label Text="{Binding Message}"
            FontSize="Medium"
            TextType="Html"
            HorizontalTextAlignment="Start"
            Style="{StaticResource LabelStyle}"/>
```

## Shared Dependencies
![image](https://user-images.githubusercontent.com/36301054/118983316-ac0e3080-b952-11eb-9039-9cd3aec2d915.png)
