### ISSUE TITLE
[Bug] RegisterRoute is broken

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8175]
1. Create shell application
2. Add shell item and menu item
```xml
<ShellItem
        Title="Home"
        Route="home">
        <ShellSection Title="1" Route="route1">
            <ShellContent ContentTemplate="{DataTemplate MyPage2}" />
        </ShellSection>
        <ShellSection Title="2" Route="route2">
            <ShellContent ContentTemplate="{DataTemplate MyPage2}" />
        </ShellSection>
    </ShellItem>

    <MenuItem
        Text="3" 
        Routing.Route="route3" />
```

3. Route in shell item is registred as extected so I can navigate to //home/route2, but //route3 is not registered.

**Comment by samhouts** [comment]
@VladislavAntonyuk  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by VladislavAntonyuk** [comment]
[Issue8175.zip](https://github.com/xamarin/Xamarin.Forms/files/3767274/Issue8175.zip)

**Comment by hartez** [comment]
The destination Route3 refers to needs to be part of the Shell structure to be registered in XAML via the Route property. For other pages, you'll need to register the route in code: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#register-page-routes

For example, in your repro project, in the AppShell constructor, add
`Routing.RegisterRoute("newitem", typeof(NewItemPage));`

And then in your `MenuItem_OnClicked` handler you can call
`await Shell.Current.GoToAsync(new ShellNavigationState("newitem"));`
to navigate to the NewItemPage.

**Comment by VladislavAntonyuk** [comment]
@hartez could you please convert it into enhancement
