### ISSUE TITLE
[Bug] CSS Descendants with Base class selector do not match

### ISSUE THREAD

**Issue by cabal95** [xamarin/Xamarin.Forms#8183]
### Description

We found that when trying to use a descendant style selector where the child element has the `^` base selector, what should have matched did not.

```xaml
<StackLayout>
    <Label Text="test" />
</StackLayout>
```

In the above, the following selector will match: `stacklayout label`

However, this selector does not: `stacklayout ^label`

When I examined the parsed selector, the two selectors above generate vastly different trees. The bug _appears_ to be here:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/StyleSheets/Selector.cs#L85

I don't think the `^` character is supposed to be included there. In fact, when I remove it my selector starts working correctly and the existing unit tests continue to work.  I have this change tested along with a few additional test cases that I can submit as a PR if desired.

### Steps to Reproduce

1. Load sample project
2. Run

### Expected Behavior

All text in sample project should be matched by CSS selectors and turn blue.

### Actual Behavior

Some are missed.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version:
- IDE: Visual Studio 2019 Community
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![2019-10-23_02-34-11-PM](https://user-images.githubusercontent.com/1119863/67435992-39847580-f5a2-11e9-8d5c-2f4fc74576e7.png)

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3764604/App1.zip)

**Comment by samhouts** [comment]
closed by #9004
