### ISSUE TITLE
[Bug] HotReload doesnt work on tabbedpage with bottom icons

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#8188]
### Steps to Reproduce

1. create tabbed page with bottom icons on android
2. make change on tabbed page and hotreload loads the page in debug mode
3. bottom icons are multiplied every time page is reloaded by hot reload

### Expected Behavior
works
### Actual Behavior
if there 2 bottom icons, they are becoming 4, next reload 8.. every time multipled and eventually crashes
 
- Version with issue:
- Last known good version: dont know
- IDE:VS 2019 latest update
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: XF 4.2
- Affected Devices:

PS: i use freshmvvm to create tabbedpage but i assume that it is also same problem without freshmvvm

**Comment by maexsp** [comment]
I can confirm this bug. Also appears without freshmvvm. After hotreload all the tabs pages get duplicated on Android.

**Comment by StephaneDelcroix** [comment]
duplicate of #7741
