### ISSUE TITLE
[Bug] ScrollView at CollectionView at RefreshView always leads to Pull-To-Refresh

### ISSUE THREAD

**Issue by aubiyko** [xamarin/Xamarin.Forms#8198]
### Description

On Android, imagine having CollectionView with ScrollView as ItemTempate and have that inside RefreshView.
If you scroll down, release, then scroll up, Pull-To-Refresh gesture always fires despite list position.

### Steps to Reproduce

1. Use reproduction.
2. Scroll down a bit.
3. Scroll up.

### Expected Behavior

CollectionView scrolls up.

### Actual Behavior

RefreshView's Pull-To-Refresh is firing.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: -
- IDE: MS VS Community 16.3.6
- Platform Target Frameworks:
  - Android: 9.0 (Pie)
- Nuget Packages:
  - NETStandard.Library v2.0.3
  - Xamarin.Forms v4.3.0.908675
- Affected Devices:
  - Android Emulator

### Reproduction Link

[Repro](https://github.com/aubiyko/XFRefreshLayoutIssue)

**Comment by hartez** [comment]
Yeah, even if you make the ScrollViews in the ItemTemplate `Orientation="Horizontal"`, this happens.
