### ISSUE TITLE
[CollectionView] After calling a service, binding fields are broken

### ISSUE THREAD

**Issue by mdmota** [xamarin/Xamarin.Forms#8199]
### Description
I updated xf to 4.3.0 and replaced Listview with CollectionView.
When calling a service to load the list, binding fields break. See attached image.

I thought collectionview would solve these problems also found in listview. But it solved nothing.
### Steps to Reproduce

1. Update XF for 4.3.0
2. Switch Listview  to CollectionView
3. Call list through webservice and binding fields
* The problem only happens on android

### Basic Information

- Version with issue: XF 4.3.0 with collectionView
- Last known good version: XF 3.6.0 with Listview
- IDE: VS 2019 16.3.6
- Platform Target Frameworks: 
  - iOS:  13.4.0
  - Android: 10.0.3 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android only

**Comment by mdmota** [comment]
Screenshots
https://drive.google.com/file/d/1vScGU4230fM3crmuXjDZ6it97bHWDVG5/view?usp=sharing

**Comment by EvoPulseGaming** [comment]
If I understand this correctly I would like to add to this, (UWP) I have a picker that REST loads property data, which populates a collectionview of all the buildings on property. This works correctly only the first time. If I change the picker selection, the bound property does get updated but the collectionview UI side does not.

Another example, if I prepopulate the collectionview with d: items, these example items are stuck in the collection view when using the picker the first time.

There is one work around to this!
If I bind the collectionview item source, to a property, and set that properties getter to "someotherproperty.ToList()", this will work as many times as I like. (But then I have to manually call property changed)

It appears that whatever initially gets populated into the collection view gets stuck there.

**Comment by samhouts** [comment]
@mdmota  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by mdmota** [comment]
I partially solved it by creating a custom view that creates a label through code behind (this loses performance). But I await Microsoft's solution.
I cannot attach the project.

**Comment by hartez** [comment]
> When calling a service to load the list, binding fields break.

Is this a web service you are calling? What data type does it return? What are you using to build the web service?

**Comment by mdmota** [comment]
I am using flur to call a rest service.
Return a list that is displayed

**Comment by hartez** [comment]
@mdmota What is "flur"? I'm not familiar with that.

> Return a list that is displayed

A list of what? Is it a `List<T>`? If so, what is `T`?

**Comment by mdmota** [comment]
Flur is a library to facilitate calls to api rest.  https://flurl.io/ 
The service returns me a List<T> that is converted to an observable collection

**Comment by hartez** [comment]
@mdmota Can you just post the code? That might facilitate this.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
