### ISSUE TITLE
[Bug] CollectionView on iOS assumes INotifyCollectionChanged is an IList (causing null reference exception when assumption is wrong)

### ISSUE THREAD

**Issue by mediabounds** [xamarin/Xamarin.Forms#8200]
### Description
We are using collection view with an object that implements `IEnumerable` and `INotifyCollectionChanged`. Starting in Xamarin.Forms 4.3.0 (the official release), this has started causing a `NullReferenceException`. This behavior changed between 4.3.0-pre3 and the official release of 4.3.0.

The issue is in `ItemsSourceFactory` -- when it is creating the source for the collection view, it checks the type of the items source. If it implements `INotifyCollectionChanged`, it attempts to cast it to `IList`.
https://github.com/xamarin/Xamarin.Forms/blob/f9114b1306f2896cce07d358725f63ce6ab8cac5/Xamarin.Forms.Platform.iOS/CollectionView/ItemsSourceFactory.cs#L20

`IList` and `INotifyCollectionChanged` are not derived from each other, so this cast can fail. When it does, `ObservableItemSource` will be instantiated with a null item source. This causes a `NullReferenceException` in the constructor when it attempts to add an event listener to `CollectionChanged`:
https://github.com/xamarin/Xamarin.Forms/blob/f9114b1306f2896cce07d358725f63ce6ab8cac5/Xamarin.Forms.Platform.iOS/CollectionView/ObservableItemsSource.cs#L28

### Steps to Reproduce

1. Set `ItemsSource` on a collection view to an `IEnumerable` which also implements `INotifyCollectionChanged` (but not `IList`)

### Expected Behavior
The collection view would read in data from the source and render the view appropriately.

### Actual Behavior
The app crashes with a `NullReferenceException`

### Basic Information

- Version with issue: 4.3.0
- Last known good version: 4.3.0-pre3
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  iOS 13.1
  - Android: ??
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by kicsiede** [comment]
this is also a problem with Picker
