### ISSUE TITLE
[Bug] InitializeComponent and 'An element with the same key already exists...'

### ISSUE THREAD

**Issue by mdbill** [xamarin/Xamarin.Forms#8202]
Similar to [7833](https://github.com/xamarin/Xamarin.Forms/issues/7833).

If you call InitializeComponent a 2nd time (e.g. in OnAppearing), you get the runtime exception about 'same key already exists...'.

Now, before you say "Don't call InitializeComponent() twice," you should be aware that doing this is the (only?) workaround for a [very old Microsoft Ads bug](https://stackoverflow.com/questions/50037580/uwp-adcontrol-blank-after-popasync-in-xamarin-forms).

I've always felt that calling InitializeComponent() twice was bad practice, but it fixes ads in UWP.  I'd be happy to hear a different workaround for that issue, but it still seems you could make it so InitializeComponent doesn't crash.

- Version with issue: 4.3 and 4.2
- Last known good version: 4.1

**Comment by StephaneDelcroix** [comment]
let's get this out of the door first:

> Don't call InitializeComponent() twice

you said it, not me.

if you want this to work, set the Namescope of your view to null before invoking InitializeComponent a second time.

but mostly: don't call InitializeComponent() twice

I'm closing this as we probably won't fix this

**Comment by mdbill** [comment]
> if you want this to work, set the Namescope of your view to null before invoking InitializeComponent a second time.

Could you elaborate on this please? I'll post your solution to stackoverflow.

**Comment by ziyauddin** [comment]
@mdbill Any updates on how to use the namescope or any other workaround for using InitializeComponent twice?

**Comment by mdbill** [comment]
> Any updates on how to use the namescope or any other workaround for using InitializeComponent twice?

No one has offered a solution (here or elsewhere). I'm still stuck on 4.1

**Comment by mpnow** [comment]
> > >if you want this to work, set the Namescope of your view to null before invoking InitializeComponent a second time.

> >Any updates on how to use the namescope or any other workaround for using InitializeComponent twice?

> No one has offered a solution (here or elsewhere). I'm still stuck on 4.1

Here's the code to set the NameScope of the view to null:

`(view as BindableObject).SetValue(Xamarin.Forms.Internals.NameScope.NameScopeProperty, null);`

This is taken from https://github.com/xamarin/Xamarin.Forms/issues/7833#issuecomment-580228684
