### ISSUE TITLE
CollectionView fires SelectionChanged x (number of items selected +1) times, while incrementing SelectedItems from 0 to number of items each time

### ISSUE THREAD

**Issue by EvoPulseGaming** [xamarin/Xamarin.Forms#8203]
using latest pre-release

If I have 10 items and select 5 of those items, this is how often SelectionChanged event fires (when selecting the fifth item, you can imagine how this works the first four times):

1: 0 items in e.CurrentSelection
2: 1 items in e.CurrentSelection
3: 2 items in e.CurrentSelection
4: 3 items in e.CurrentSelection
5: 4 items in e.CurrentSelection
6: 5 items in e.CurrentSelection

Since I populate another collectionview using this, I generate 5+4+3+2+1 times my data, I basically waste 4+3+2+1+0 times the cpu time. (I also clear and add items based off this, so this is multiplicatively worse depending on how many sub items get generated)

Only #6 should fire.

**Comment by samhouts** [comment]
@EvoPulseGaming  Can you please attach a small project that demonstrates this issue? Which platform? Have you tried the stable release? Thanks!

**Comment by jsuarezruiz** [comment]
It seems that is a similar problem than: https://github.com/xamarin/Xamarin.Forms/issues/8184

**Comment by EvoPulseGaming** [comment]
Yes, I would say so, I use SelectedItems for my loop so never experienced
your crash.

**Comment by EvoPulseGaming** [comment]
I'm not sure about that, see comment I left in 8184

**Comment by matheusjulio96** [comment]
@EvoPulseGaming same here. I'm trying to check if the user can selected an item, but SelectionChanged behave like you described.

**Comment by matheusjulio96** [comment]
@samhouts here's an repro: [https://git.io/Jez3N](url). Select the items in CollectionView to see how many times the method is fired.
