### ISSUE TITLE
[Bug] Shell Flyout Items on UWP aren't showing the Title

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8207]
## Description

https://github.com/xamarin/Xamarin.Forms/pull/6015#issuecomment-546010203

Hi, thanks for the good work on this, been waiting for Shell on UWP for a while.

I just switched my xamarin forms app to enable shell on the UWP.
My menu is working on iOS and Android but on UWP renders as below
![image](https://user-images.githubusercontent.com/5575429/67507752-81c99380-f687-11e9-9229-75f5f927c0df.png)

I'm using this syntax:-
```
<FlyoutItem Title="Dashboard">
        <FlyoutItem.Icon>
            <FontImageSource Color="Black" Glyph="{x:Static fa:FAIcons.chart}" FontFamily="{StaticResource FontAwesomeSolid}" Size="30"/>
        </FlyoutItem.Icon>
        <Tab>
            <ShellContent Title="Charts" ContentTemplate="{DataTemplate views:ChartsPage}"/>
        </Tab>
</FlyoutItem>
```
Am I using something thats not supported?
All NuGet packages are updated to latest stable.

Thanks

### Steps to Reproduce

- Create Xamarin Forms Shell Template
- Add UWP platform
- you'll see the issue described above

### Expected Behavior
The flyout should show the text of each item not the object type

### Actual Behavior

Flyout just shows the object Type

### Basic Information

- Version with issue:
- Platform Target Frameworks: 
  - UWP:  16299

**Comment by Nioux** [comment]
Hi,

I have a similar issue with UWP in my project : 

![image](https://user-images.githubusercontent.com/8601237/67558770-e16f7f80-f717-11e9-8c09-941934981ed8.png)

`
    <ShellContent Title="Accueil" Route="home" ContentTemplate="{DataTemplate local:MainPage}" />
    <FlyoutItem Title="Personnages" Route="pceditor" Icon="battle_axe.png">
        <Tab Title="Personnages">
            <ShellContent Title="Race" ContentTemplate="{DataTemplate pc:RacePage}" />
            <ShellContent Title="Historique" ContentTemplate="{DataTemplate pc:BackgroundPage}" />
            <ShellContent Title="Classe" ContentTemplate="{DataTemplate pc:ClassPage}" />
            <ShellContent Title="Caractéristiques" ContentTemplate="{DataTemplate pc:AbilitiesPage}" />
            <ShellContent Title="Finalisation" ContentTemplate="{DataTemplate pc:FinalizePage}" />
        </Tab>
    </FlyoutItem>
    <ShellContent Title="Dés" Icon="d20.png" Route="dices" ContentTemplate="{DataTemplate local:DicesPage}" />
    <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <ShellContent Title="Bibliothèque" Route="library" Icon="spell_book.png">
            <ShellContent.ContentTemplate>
                <DataTemplate>
                    <library:ItemPage>
                        <x:Arguments>
                            <x:String>index.md</x:String>
                        </x:Arguments>
                    </library:ItemPage>
                </DataTemplate>
            </ShellContent.ContentTemplate>
        </ShellContent>
        <ShellContent Title="Favoris" Route="bookmarks" ContentTemplate="{DataTemplate library:BookmarksPage}" Icon="stars_stack.png" />
        <ShellContent Title="Recherche" Route="deepsearch" ContentTemplate="{DataTemplate library:DeepSearchPage}"  Icon="crystal_ball.png" />
    </FlyoutItem>
    <ShellContent Title="A propos de..." Route="about" Icon="wooden_sign.png" ContentTemplate="{DataTemplate local:AboutPage}" />
`

Complete source can be found there : 

[https://github.com/Nioux/AideDeJeu](https://github.com/Nioux/AideDeJeu)

Not sure if I use shell as expected, but it works like expected on Android.

(Great job anyway ;) )

Yan

**Comment by JogyBlack** [comment]
Had a similar issue, but after switching the target Windows version to 1809 (Build 17763), the Shell entries show correctly in the UWP app.
