### ISSUE TITLE
[Bug] [iOS] RightToLeft flow direction doesn't work with Label

### ISSUE THREAD

**Issue by efhayati** [xamarin/Xamarin.Forms#8210]
### Description
After upgrade to 4.3, the `Label `doesn't respect to RTL flow direction in iOS. 

### Steps to Reproduce

1. Set the `FlowDirection` property on `Label` (or on a page containing a `Label`) to `RightToLeft`.

### Expected Behavior
The `Label` should render text from Right

### Actual Behavior
The `Label` doesn't respect the RTL flow direction.

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.910310
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: 9.0

**Comment by samhouts** [comment]
Duplicate of #2447
