### ISSUE TITLE
[Enhancement] Platform Specific for UWP CollectionView to hide multi-select checkboxes

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#8216]
## Summary

By default, on UWP the underlying control for CollectionView displays checkboxes when in multiple-selection mode. It's possible that some folks want the default native behavior and some do not. So this proposal is to add a platform-specific property to hide the checkboxes.

## API Changes

Add:

```
public static readonly BindableProperty MultipleSelectionCheckboxesEnabledProperty = BindableProperty.Create ("MultipleSelectionCheckboxesEnabled", typeof (bool), typeof (Xamarin.Forms.SelectableItemsView), true);

Xamarin.Forms.PlatformConfiguration.WindowsSpecific.SelectableItemsView.GetMultipleSelectionCheckboxesEnabled();

Xamarin.Forms.PlatformConfiguration.WindowsSpecific.SelectableItemsView.SetMultipleSelectionCheckboxesEnabled();
```

## Intended Use Case

If a user does not want the checkboxes to be displayed, they simply need to set this property to false in XAML or code.

**Comment by EvoPulseGaming** [comment]
So maybe this is where we split in opinion. When I think "Xamarin" I think universal. I think behavior = the same everywhere.

But I noticed the  comment about "It's possible that some folks want the default native behavior"

So this enhancement while solving the particular issue, doesn't solve the issue in general. I expect the behavior to be the same across all platforms using Xamarin.... explicitly ignoring the native defaults when possible.....

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
