### ISSUE TITLE
[Bug] -UWP - Device.Idiom is not updated when flipping tablet mode state

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/Xamarin.Forms#8218]
### Description

When you use Device.Idiom to check if tablet mode is activated or not, the state detected at app start is cached and not updated when you change the tablet mode state via action center

### Steps to Reproduce

1.  create new XF app
2. add `protected override void OnSizeAllocated(double width, double height)` method and check with Device.Idiom for `Device.Idiom == TargetIdiom.Tablet` and `Device.Idiom == TargetIdiom.Desktop`
3. change [tablet mode via action center](https://support.microsoft.com/en-us/help/4027960/windows-10-turn-tablet-mode-on-or-off)

![image](https://user-images.githubusercontent.com/8274816/67546925-d6a7f100-f6fd-11e9-9391-9e9da5112d0c.png)

 and in `OnSizeAllocated` the Device.Idiom is still the same value like at app start.

### Actual Behavior

- start app in tablet mode: Device.Idiom is TargetIdiom.Tablet
- start app in desktop mode: Device.Idiom is TargetIdiom.Desktop

and the value never changes when you change tablet mode state.

### Expected Behavior

- start app in tablet mode: Device.Idiom is TargetIdiom.Tablet
- start app in desktop mode: Device.Idiom is TargetIdiom.Desktop

and the Device.Idiom value changes when you change tablet mode state

### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: N/A
- IDE: VS2017 15.9
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  UWP16299
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: all Windows 10 devices

### Reproduction Link

[DeviceInfoTargetIdiomDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/3770772/DeviceInfoTargetIdiomDemo.zip)

**Comment by MagicAndre1981** [comment]
The [Microsoft UWP docs](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.uiviewsettings) also uses size changed event because size changes when switching desktop/tablet mode.

So could do the checks

```
if (Windows.UI.ViewManagement.UIViewSettings.GetForCurrentView().UserInteractionMode == Windows.UI.ViewManagement.UserInteractionMode.Touch)
      Device.SetIdiom(TargetIdiom.Tablet);
else
     Device.SetIdiom(TargetIdiom.Desktop);
```

 in base `OnSizeAllocated` so that we can use the updated check in the override methods  🤔

**Comment by MagicAndre1981** [comment]
Any ideas where to update the Device.Idiom? @hartez

**Comment by hartez** [comment]
There's a non-obvious (doesn't show up in Intellisense) method `Device.SetIdiom()` for that. UWP sets it during `Forms.Init()`. _In theory_, you could update it at any time to Desktop or Tablet.

**Comment by MagicAndre1981** [comment]
I know that it is only called once. So we need to extract the detection in a new function. But do other platforms also have this change? What about the experimental desktop view in Android , which I can't test with my Pixel 3a, and what about WPF, here this also applies as you can run desktop applications when in tablet mode?

And such larger code change should be done from a person who contributes regularly to XF.

**Comment by MagicAndre1981** [comment]
@hartez 

what about Android and the Dual Screen devices? Can both screens have different resolutions? And what about the android desktop mode? My Pixel 3a has no Video over USB-C, so I can't test it.

So this change is likely across all platform implementations.

**Comment by MagicAndre1981** [comment]
@hartez

what about Windows 10X? [From the video](https://youtu.be/MHMLvelzWMU?t=560), I see that activating the keyboard changes style from tablet to desktop.

**Comment by MagicAndre1981** [comment]
nice there is now a PR linked to it. Will test it when it was merged
