### ISSUE TITLE
ListView item separators are not displayed in Xamarin.Forms UWP

### ISSUE THREAD

**Issue by Balasubramanian93** [xamarin/Xamarin.Forms#8219]
### Description
ListView item separators are not displayed in Xamarin.Forms UWP
### Steps to Reproduce

1. Add a ListView with items
2. Deploy the sample and you could see that the separator lines are not displayed.
3. 

### Expected Behavior
The separator line should be there for each item.

### Actual Behavior
The separator line is not there for each item.
### Basic Information

- Version with issue: All
- Last known good version: All
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  16299 and above
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:Desktop

### Screenshots

![image](https://user-images.githubusercontent.com/21172770/67552056-dcb2c780-f727-11e9-8983-dba2508100da.png)

**Comment by GalaxiaGuy** [comment]
As per the documentation, there are two settings for `SeparatorVisibility`:

**Comment by GalaxiaGuy** [comment]
As per the documentation, there are two settings for `SeparatorVisibility`: `None`, which hides them and `Default` which is do whatever the platform default is, which for Windows means no separators.

Changing that would probably be considered a breaking change. Adding a new option like `Show` could be an option.

**Comment by hartez** [comment]
@GalaxiaGuy is correct. If you really want separators on UWP, please open an enhancement/feature request. Alternatively, you could implement them in a custom renderer, or add them as part of your data template.
