### ISSUE TITLE
[Bug] When updating to Xamarin.Forms 4.3 xaml bindings to Dictionaries no longer work

### ISSUE THREAD

**Issue by norfus** [xamarin/Xamarin.Forms#8221]
### Description
When updating to Xamarin.Forms 4.3 xaml bindings to Dictionaries no longer work if XamlCompilationOptions.Compile is set, But in 4.2 it does

Setting [XamlCompilation(XamlCompilationOptions.Skip)] in 4.3 resolved the problem but is not ideal as it reduces performance

[TestCollectionVIew2.zip](https://github.com/xamarin/Xamarin.Forms/files/3771946/TestCollectionVIew2.zip)

### Steps to Reproduce
1. In Xaml have the following binding
```
<Label Text="{Binding Data[EntryOne]}"/>
<Label Text="{Binding Data[EntryTwo]}"/>
```
2. In code behind
```
public Dictionary<string, string> Data { get; } = new Dictionary<string,string>();
public ItemsViewModel()
{  
     Data.Add("EntryOne", "Text1");
     Data.Add("EntryTwo", "Text2");
}  
```
3. When trying to compile i get the following error:
"Object reference not set to an instance of an object"

### Expected Behavior
Dictionary bindings should be ignored when precompiling bindings and code should compile 
### Actual Behavior
Compile error
### Basic Information
- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.910310
- IDE: Visual Studio 2019
- Platform Target Frameworks:  SharedProject with .Net Standard 2.0
- Nuget Packages:
- Affected Devices:

**Comment by StephaneDelcroix** [comment]
could you please tell use the exact version you're testing ? thanks

**Comment by norfus** [comment]
Works in 4.2.0.910310, does not work in 4.3.0.908675, thanks for looking into it

**Comment by StephaneDelcroix** [comment]
Works fine with a quick test. looking at your project...

**Comment by StephaneDelcroix** [comment]
not sure why your project doesn't work, but I can't test as it's not a full app... please provide a complete reproduction link.

also, your view is 

```xaml
<Label Text="{Binding Data[EntryOne]}"/>
<Label Text="{Binding Data[EntryTwo]}"/>
```

but your VM is

```csharp
            Data.Add("Ett", "Olle");
            Data.Add("Tva", "Pelle");
```

**Comment by StephaneDelcroix** [comment]
#7837 regressed this.  working on it

**Comment by norfus** [comment]
Hello, sorry i did some last minute changes before uploading, i created a new sample(TestCollectionVIew2.zip) now with only this issue. Building the sample generates the error, and changing back to  4.2.0.910310 resolves it
