### ISSUE TITLE
[Bug] UWP Text in Editor is now vertically centered.

### ISSUE THREAD

**Issue by DuncWatts** [xamarin/Xamarin.Forms#8222]
### Description
Changes made to add ITextAlignmentElement have modified the FormsTextBoxStyle to add VerticalAlignment, however the matching properties have not been added to the Editor control that also uses this style.  This has changed the default vertical alignment used on the Editor control to Center with no way to override this from within the shared project.

https://github.com/xamarin/Xamarin.Forms/commit/6ee4ec697454c9a8268759dc61abf0bc5c8cc829#diff-9429d23ce5cafe390e252e1704e75598

https://github.com/xamarin/Xamarin.Forms/pull/6463

### Steps to Reproduce

1. Add an Editor control with a HeightRequest of 100
2. Run in UWP 

### Expected Behavior
Text is top aligned

### Actual Behavior
Text is center aligned.

### Basic Information

- Version with issue: 4.3
- Last known good version: 4.2
- IDE: VS2019
- Platform Target Frameworks: 
  - UWP:  18362

**Comment by bmacombe** [comment]
I've seen this behavior also after getting 4.3 nugets

**Comment by hartez** [comment]
[_8222 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3773605/_8222.Repro.zip)

**Comment by samhouts** [comment]
closed by #8280
