### ISSUE TITLE
[Bug] CarouselView not working in ios application

### ISSUE THREAD

**Issue by tp16190** [xamarin/Xamarin.Forms#8225]
**Description**
I had created mobile application using Xamarin.Forms(version 4.3.0.908675) and use MVVM pattern. I am using CarouselView in one of my page. as below 

`<CarouselView ItemsSource="{Binding SelectedProduct.ProductImages}" Position="{Binding SliderPosition}" PositionChangedCommand="{Binding PositionSelectedCommand}" PositionChangedCommandParameter="{Binding SliderPosition}">
                                        <CarouselView.ItemTemplate>
                                            <DataTemplate x:DataType="local:ProductImage">
                                                <Grid>
                                                    <Label Text="ProductImages" x:Name="productImage" IsVisible="False" />
                                                    <ffimageloading:CachedImage LoadingPlaceholder="img_loading.png" ErrorPlaceholder="img_error.png" DownsampleToViewSize="True" Source="{Binding FilePath, Converter={StaticResource ImagePathConverter},ConverterParameter={x:Reference productImage}}" Aspect="AspectFill" />
                                                    <StackLayout BackgroundColor="{StaticResource CarouselHeaderBackGroundColor}" Padding="10" VerticalOptions="EndAndExpand" IsVisible="{Binding Description, Converter={StaticResource StringToBoolConverter}}">
                                                        <Label TextColor="White" Text="{Binding Description}" FontSize="{StaticResource SmallFontSize}" HorizontalOptions="Center" VerticalOptions="EndAndExpand"/>
                                                    </StackLayout>
                                                </Grid>
                                            </DataTemplate>
                                        </CarouselView.ItemTemplate>
                                    </CarouselView>`

The page is working fine in android devices but not working in ios devices (Did testing in iPhone 7s iOS 12.2 and simulator iPhone X iOS 12.2).

**Expected Behavior**
CarouselView control must work in iOS devices

**Actual Behavior**
CarouselView control not working in iOS devices

**Basic Information**
Version with issue: Xamarin.Forms 4.3.0.908675
IDE: Microsoft Visual Studio Community 2017
Platform Target Frameworks:
Android: Android 9.0 (API Level 28 - Pie)
iOS: iOS 12.2

**Comment by hartez** [comment]
@tp16190 When you say "not working", what do you mean? Does it crash? Does the CarouselView fail to appear? Are the items displaying incorrectly, or not at all?

**Comment by tp16190** [comment]
"not working" means it is not displaying

**Comment by RhomGit** [comment]
I am seeing (or rather not seeing) this issue also.
App doesn't throw an error that I can see. The page loads correctly but the items themselves are not rendered (testing on physical device iPad 13.2.2).  It just has empty space. 
Xamarin.Forms v4.3.0.947036
Its working as expected on Android.

`                    <CarouselView PeekAreaInsets="200" Grid.Row="5" NumberOfSideItems="0" HeightRequest="180" ItemSizingStrategy="MeasureFirstItem"
                          IsVisible="{Binding FilesVisible}"
                          ItemsSource="{Binding Attachments}"   >
                        <CarouselView.ItemsLayout>
                            <LinearItemsLayout Orientation="Horizontal" ItemSpacing="20" SnapPointsType="Mandatory" SnapPointsAlignment="Center"  />
                        </CarouselView.ItemsLayout> `

**Comment by Elinareso** [comment]
Hi, I'm facing the same issue with an app that we just released to production. We are working on the iOS compilation, is there a workaround to fix this?

**Comment by adambarath** [comment]
(Interesing... carouselview works in my project properly.)

**Comment by mpghelli** [comment]
Hi.

I am with a similar problem. Xamarin render the page in iOS, but the bottom part of the carrousel form are only visible if i use the scroll bar. I am using EndAndExpand for verticalOptions. The problem only occur for IPhone X, XR and XS.



`<CarouselPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:prism="http://prismlibrary.com"
             xmlns:controls="clr-namespace:Montreal.Core.Controls;assembly=Montreal.Core"
              xmlns:instrucaoPage="clr-namespace:CPS.Originacao.Mobile.Views.Instrucao"
              prism:ViewModelLocator.AutowireViewModel="True"
             x:Class="CPS.Originacao.Mobile.Views.InstrucaoPage"
             x:Name="InstrucaoPageCarousel"
             NavigationPage.HasNavigationBar="False"> 

<ContentPage x:Name="Pagina1">
        <Grid Style="{StaticResource gridPrincipal}">
                <Grid.RowDefinitions>
                    <RowDefinition Height="{OnIdiom Phone='Auto', Tablet='*'}"/>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="*"/>
                </Grid.RowDefinitions>

                <Image Grid.Row="0" x:Name="imgCreditoImobiliario" Source="credito_Imobiliario_icon.png"/>

                <controls:MontrealBasicTitle Grid.Row="1" Margin="0,45,0,27" HorizontalTextAlignment="Center" TitleMarkupLanguage="[bold]Facilitamos o[/bold][paragraph/][bold]acesso à sua casa própria[/bold]"/>

                <controls:MontrealFieldLabel Grid.Row="2" Style="{StaticResource lblDescricao}" Text="Há 38 anos, a POUPEX disponibiliza linhas de crédito imobiliário com ótimas condições."/>

            <Grid Grid.Row="3" VerticalOptions="EndAndExpand">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>

                    <controls:MontrealRoundedButton Grid.Column="0" Style="{StaticResource bntPular}" Text="Pular" Command="{Binding PularCommand}"/>

                    <StackLayout Grid.Column="1" HorizontalOptions="CenterAndExpand" Orientation="Horizontal" >
                        <Image Source="active_slide_icon"/>
                        <Image Source="slide_icon"/>
                        <Image Source="slide_icon"/>
                    </StackLayout>

                <controls:MontrealRoundedButton Grid.Column="2" Style="{StaticResource bntProximo}" ImageSource="next_icon.png" CommandParameter="pagina2" Clicked="NextPage_Clicked"/>
                </Grid>
            </Grid>
    </ContentPage>
</CarouselPage>`

**Comment by jfversluis** [comment]
Hey @tp16190 and @RhomGit thanks for the info!

I see some XAML snippets, but none seem to be complete. Would it be possible to add a small reproduction project that shows this issue? That would help us a lot :) Thanks!

@mpghelli this seems to be a slightly different issue if you ask me. Since you are mentioning only devices with a notch, are you using the SafeAreaInsets? If you still think this is an issue, I think it's best to open a new issue for this one and add a reproduction project there. Thanks!

**Comment by mpghelli** [comment]
Hi

In my case i was able to correct this, using a customRenderer in iOS to disable CarouselPage scrolling and use stacklayou instead gridLayout:

`protected override void OnElementChanged(VisualElementChangedEventArgs e)

{

base.OnElementChanged(e);

        UIView view = this.NativeView;
        UIScrollView scrollView = (UIKit.UIScrollView)view.Subviews[0];
        scrollView.ShowsVerticalScrollIndicator = false;
        scrollView.ContentSize = new CoreGraphics.CGSize(scrollView.ContentSize.Width, scrollView.Frame.Size.Height);
        AutomaticallyAdjustsScrollViewInsets = false;
    }`

[https://forums.xamarin.com/discussion/123360/how-to-disable-carousel-page-scrolling-in-ios](https://forums.xamarin.com/discussion/123360/how-to-disable-carousel-page-scrolling-in-ios)

**Comment by RhomGit** [comment]
I have uploaded a basic repro here: https://github.com/RhomGit/XamarinRepros
Android works as expected, iOS 13 looks like below and doesn't work.

Note: this isn't an exact duplication of the issue above but I don't have more time to spend on this right now.

![2019-11-28_07-16-08-AM](https://user-images.githubusercontent.com/25700833/69765709-fd02f580-11af-11ea-95ce-c5dcfdab13db.png)

**Comment by jfversluis** [comment]
There is definitely some funny stuff going on here. Thanks for all the info everyone! If you discover some more or are able to provide more reproductions that will be super helpful!

**Comment by Robbert-jansen** [comment]
This happens when the CarouselView OR the parent view isn't visible whilst the page loads.

So with the below code it won't ever show up again. 
```
public PageConstructor()
{
    InitializeComponent();
    
    CarouselView.IsVisible = false
}
```

Putting it in the OnAppearing method  is fine however, as that is after the page is done loading, toggling it back on later makes it show up like it should.
```
protected override void OnAppearing()
{
    base.OnAppearing();

    CarouselView.IsVisible = false
}
```

**Comment by jtorvald** [comment]
@samhouts I still have this issue in 4.4.0.991265. Items are not showing until I scroll some items to the right. Those items on the right are visible and when I scroll back, the first items also get visible.
Was this supposed to be solved under iOS? If so, do you want me to create a new issue?

**Comment by vhugogarcia** [comment]
I'm also facing the same issue. The CarouselView renders OK for iOS simulator, but it is not for iOS real devices. 

Attached is a screenshot of the UI looks on a physical iOS device.
[https://ibb.co/4JXK7gf](url)

**Comment by Nusiko** [comment]
This also happens to me. The CarouselView is hidden at first and will be shown if the underlying ItemsSource is populated and another condition is met. The workaround was to show them first and hide them if necessary, but this leads to flickering ui. 
I'm on v4.4.0.991640.

**Comment by balazserd** [comment]
Same as @vhugogarcia. Works in simulator, doesn't appear at all in real iOS (13.4) device. I can still scroll it horizontally and see the selected index changes, but no view appears.

**Comment by AbuMandour** [comment]
any update?

**Comment by mpghelli** [comment]
In my case i was able to correct this, using a customRenderer in iOS to disable CarouselPage scrolling and use stacklayou instead gridLayout:

`protected override void OnElementChanged(VisualElementChangedEventArgs e)

{

base.OnElementChanged(e);

    UIView view = this.NativeView;
    UIScrollView scrollView = (UIKit.UIScrollView)view.Subviews[0];
    scrollView.ShowsVerticalScrollIndicator = false;
    scrollView.ContentSize = new CoreGraphics.CGSize(scrollView.ContentSize.Width, scrollView.Frame.Size.Height);
    AutomaticallyAdjustsScrollViewInsets = false;
}`
https://forums.xamarin.com/discussion/123360/how-to-disable-carousel-page-scrolling-in-ios
