### ISSUE TITLE
[Bug]Grouped CollectionView shows the item source object name in each group

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8228]
### Description
I am using Grouping with CollectionView. The Collection View shows the name of the itemssource object in the end of every group. The name of the object in this case happens to be ShellRepro.CategoryGroup.

- Version with issue:Xamarin.Forms-4.3.0.908675
- Affected Devices:iOS

### Screenshots
![CollectionView](https://user-images.githubusercontent.com/9531864/67574893-f7e9fb00-f758-11e9-884f-c866939a3077.png)

### Reproduction Link
[ShellRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3772267/ShellRepro.zip)

**Comment by GalaxiaGuy** [comment]
It seems to be the group footer. As a work around, adding

```xml
        <CollectionView.GroupFooterTemplate>
           <DataTemplate >
               <ContentView/>
           </DataTemplate>
        </CollectionView.GroupFooterTemplate>
```

Seems to make it go away.

**Comment by HobDev** [comment]
@GalaxiaGuy  Thank you for the workaround. I can use this until issue is resolved.

**Comment by Clancey** [comment]
Yes, there is a footer added automatically for grouped views. We should only show a footer if there is a footer template assigned.

**Comment by shanranm** [comment]
@Clancey This is intentionally put in. If there is no template provided, we have a default fallback template. It makes sense for `Items` to have a fallback template. But for header and footer we shouldn't show anything.

@hartez Any update on this?

**Comment by shanranm** [comment]
@hartez sorry for hijacking the issue, just thought I might take a look. Replaced the default supplementals with empty view.

**Comment by tranb3r** [comment]
Cannot reproduce with XF 5.0.0.2125.
@jfversluis I think you can close this issue.

**Comment by jfversluis** [comment]
@tranb3r did you try the attached repro and updated that to the latest XF5 version?

Thanks for testing this! <3

**Comment by tranb3r** [comment]
@jfversluis Yes. First I've tested the attached repro, and confirmed the bug. Then updated XF to the latest version: bug fixed.

**Comment by jfversluis** [comment]
Perfect, thank you so much for your time!
