### ISSUE TITLE
[Bug] [XAMARIN-FORMS-WPF] Forms ViewRenderer doesn't create render when child added in its Forms element

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#8229]
### Description

Greetings,

We at Syncfusion have started implementation for providing support in Xamarin.Forms WPF platform for our controls. We have created Native renderer for a forms element derived **ViewRenderer<FormsElement, NativeElement>**. We have found that when child added for those forms element, it doesn't create its renderer automatically as like in UWP platform. We have analyzed the source and found that renderer is created only for elements derived from **LayoutRenderer**. In LayoutRenderer, ChildAdded ChildRemoved events have been hooked but not in ViewRenderer, why is it so? Is there any ViewRenderer available for this usage? We have attached a simple sample showcasing the issue. You can check ViewRenderer difference between UWP and WPF platform. Can you please provide us with any solution or workaround to overcome this issue as soon as possible?
### Steps to Reproduce

1. Run the attached sample in WPF platform.

### Expected Behavior

While adding the child for ViewRenderer element, its renderer has to be created.

### Actual Behavior

ViewRenderer doesn't create native child elements.

### Basic Information

- Version with issue: Latest
- Last known good version: None
- IDE:
WPF

### Screenshots

Please see that you have hooked the events for [LayoutRenderer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Renderers/LayoutRenderer.cs)

![image](https://user-images.githubusercontent.com/26808947/67575806-f588a080-f75a-11e9-889b-61354172c1f9.png)

### Reproduction Link

[ViewRendererIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3772328/ViewRendererIssue.zip)

**Comment by Muthukumaran-G** [comment]
Hi @mohachouch / @samhouts  ,

Can you please let me know the progress of this issue ASAP?

Thanks.

**Comment by Muthukumaran-G** [comment]
Hi @pauldipietro / @hartez / @jsuarezruiz / @mohachouch / @samhouts ,

This is a major stum block for us and highly critical issue which needs to be taken care of immediately. Please provide us an alternative solution until then.

**Comment by mohachouch** [comment]
Hi @Muthukumaran-G 


The WPF backend has been designed differently.

Unlike the UWP backend, the WPF backend does not add a "Panel". All components are rendered in 1: 1.

For example :
A button gives a Panel and a Button in UWP but in WPF a button is rendered in just one button (without the panel).

All renderer are fast. The controls are not embedded into a panel.

Bellow the difference between WPF and UWP.

UWP:
![image](https://user-images.githubusercontent.com/25939826/67761095-e5b2da00-fa42-11e9-836b-e154ef6de432.png)

WPF:
![image](https://user-images.githubusercontent.com/25939826/67761138-f82d1380-fa42-11e9-8b74-dd59acef2922.png)

That's why only the LayoutRenderer class allows you to add children.

Could you tell me more about what you wish to do?

**Comment by Muthukumaran-G** [comment]
Hi @mohachouch ,

As you can see in the attached example, the elements derived from ViewRenderer doesn't create any native elements when child added in forms element. So we would like to know why this behavior is different when compared with UWP ViewRenderer. 

So to create native elements, I have to create a new native element in renderer and add the content to its child. Its becomes sluggish to create too many native view structure similar to Forms structure to bring the element in view.

Can you please refer the attached sample for better understanding?

Thanks.

**Comment by Muthukumaran-G** [comment]
> That's why only the LayoutRenderer class allows you to add children.

What if we want to create a custom native element to achieve custom requirements? How is it possible using LayoutRenderer?

For example:
We have a forms Layout<View> element in PCL and in renderer we need to have a ViewRenderer whose native element is FrameWorkElement. Is it possible without using ViewRenderer?

**Comment by mohachouch** [comment]
I do not understand the purpose of the example.

So we have VertualizingCellsControl that inherits from Layout <View>.

Layout <View> is renderer by LayoutRenderer in WPF which takes care of displaying on a panel the list of children according to the measurement phases of Xamarin Forms.

Can you give me a more detailed example of what you wish to do?

**Comment by Muthukumaran-G** [comment]
Hi @mohachouch ,

Please see the WPF renderer written for the VertualizingCellsControl in WPF project. I don't want VertualizingCellsControl to render from LayoutRenderer, so I have modified it to inherit from ViewRenderer to set custom native control which is FrameWorkElement. The child elements inside the  VertualizingCellsControl is also a native ViewRendererElement. Please refer the native project renderer class files.

Thanks.

**Comment by Muthukumaran-G** [comment]
Let me know how to create custom native elements using LayoutRenderer. If not please provide us a suitable solution to create custom native elements in WPF platform.

**Comment by mohachouch** [comment]
Do you want to make a custom control or a custom layout?

**Comment by Muthukumaran-G** [comment]
@mohachouch , custom control makes more sense.

**Comment by mohachouch** [comment]
In this case why the VertualizingCellsControl inherits from Layout

VertualizingCellsControl : Layout<View>

**Comment by Muthukumaran-G** [comment]
@mohachouch , Actually its **Layout <View>** , We have used it to arrange and layout multiple child items.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
