### ISSUE TITLE
[Bug] CollectionView Items does not update correctly when IsVisible Property Change

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8230]
### Description
I am using CollectionView as Accordion. A tap on header displays items in the selected group and hides the items of previously selected group. The second tap on same group header also hides the items of the selected group. But the update does not reflect correctly on CollectionView. Please see the ScreenShot below where all the items are not displayed correctly in selected group. Whereas all the items on the previously selected group are not hidden. 
This behaviour is very difficult to explain sometimes not a single item is displayed on click. I also didn't understand the pattern of selections which created this issue. I am just tapping through randomly selecting and unselecting both groups and able to reproduce.

### Basic Information

- Version with issue:Xamarin.Forms-4.3.0.908675
- Affected Devices:iOS and Android

### Screenshots
![IncorrectItems](https://user-images.githubusercontent.com/9531864/67575962-426c7700-f75b-11e9-91b3-64bebc179fe0.png)

### Reproduction Link
[ShellRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3772332/ShellRepro.zip)

**Comment by hartez** [comment]
This is fixed in 5.0.0.1931.
