### ISSUE TITLE
[Enhancement] Add FlexLayout ItemsLayout on CollectionView

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#8234]
## Summary

Supporting `FlexLayout` in the `CollectionView` would be useful to manage items of several sizes, responsive, aligned, wrapped, justified,...

Currently I use a `FlexLayout` with `BindableLayout` to get this kind of result, which is not possible with the `CollectionView`.

## API Changes

Create `FlexItemsLayout` with `FlexLayout` properties and support `FlexLayout` attached properties of `DataTemplate`.

## Intended Use Case
Example of a column list that is wrapped and responsive that is made with `FlexLayout` and that cannot currently be made with `CollectionView`:
![image](https://user-images.githubusercontent.com/4254116/67589695-5616de00-f759-11e9-9937-d414c7cb9acd.png)

````xaml
<ScrollView>
    <FlexLayout
        AlignContent="Start"
        AlignItems="Start"
        AlignSelf="Start"
        BindableLayout.ItemsSource="{Binding Items}"
        Direction="Row"
        JustifyContent="Start"
        Wrap="Wrap">
        <BindableLayout.ItemTemplate>
            <DataTemplate>
                <Grid
                    Margin="5"
                    Padding="10"
                    BackgroundColor="White"
                    ColumnSpacing="10"
                    FlexLayout.Basis="240"
                    FlexLayout.Grow="1"
                    FlexLayout.Shrink="0"
                    HorizontalOptions="FillAndExpand">

                    <Label Text="ITEM CONTENT" />
                </Grid>
            </DataTemplate>
        </BindableLayout.ItemTemplate>
    </FlexLayout>
</ScrollView>
````

This would become with `FlexItemsLayout` in a `CollectionView`:
````xaml
<CollectionView
    ItemsSource="{Binding Items}">
    <CollectionView.ItemsLayout>
        <FlexItemsLayout
            AlignContent="Start"
            AlignItems="Start"
            AlignSelf="Start"
            Direction="Row"
            JustifyContent="Start"
            Wrap="Wrap" />
    </CollectionView.ItemsLayout>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Grid
                Margin="5"
                Padding="10"
                BackgroundColor="White"
                ColumnSpacing="10"
                FlexLayout.Basis="240"
                FlexLayout.Grow="1"
                FlexLayout.Shrink="0"
                HorizontalOptions="FillAndExpand">

                <Label Text="ITEM CONTENT" />
            </Grid>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
````

The example is very simple, but the possibilities are multiple with `FlexLayout` support.

**Comment by oscarjaergren** [comment]
1+ this is a pretty good idea

**Comment by kubaizi** [comment]
1+ Realy helpful.

**Comment by mapanjwani** [comment]
+1

**Comment by uzairali001** [comment]
+1

**Comment by Sebastian1989101** [comment]
+1

**Comment by Kingram91** [comment]
+1  - hopefully this is something we can look forward to in Maui

**Comment by xamiell** [comment]
+1

**Comment by mhrastegary77** [comment]
@jfversluis @jsuarezruiz did you guys saw this? 👀 it's really one of those type of necessaries!

**Comment by jfversluis** [comment]
Thanks for the ping @mhrastegary77 

Unfortunately we're not going to add any new things to Xamarin.Forms anymore unless it somehow is really needed, so I'm afraid this is one of those things that won't be added anymore. It seems like this has some great response though so I will tag it for consideration in .NET MAUI, but feel free to open a feature request there with all the details about this and maybe new insights that you might have gotten in the meantime.

Thanks for the suggestion and the input everyone!

**Comment by Wolooo** [comment]
Hi there,

hope you're all doing well in these difficult times.

I'm a beginner in xamarin and i have to make a project and i was wondering why my visual studio doesn't recognize the `<FlexItemsLayout />` it underlines it green, asking me if I'm missing an import or something. I know it is explained at the top but i think my english is not good enough to understand what i need to do to solve this. Thanks in advance! Greetz from Belgium

**Comment by Sebastian1989101** [comment]
@Wolooo there is nothing like a FlexLayout yet. This is just a feature request. Also I would recommend to not use Xamarin controls and rather use some from other libraries. Espacially lists and collections are heavily bugged and problematic right now.

**Comment by Mateus-Castellar** [comment]
+1

**Comment by mabdollahiasl** [comment]
+1
