### ISSUE TITLE
[Bug] Custom renderer's OnElementChanged is not called when renderer is disposed

### ISSUE THREAD

**Issue by GarryPSmith** [xamarin/Xamarin.Forms#8239]
### Steps to Reproduce

1. Create a custom control with an event in the shared project.
2. Create a renderer in the Android project using a WebView as the native control.
3. In OnElementChanged() when a NewElement is passed in the ElementChangedEventArgs add a handler to the control's event.
4. When a OldElement is passed remove the event handler.
5. Use the custom control in a ContentPage.
6. Navigate away from the page and back to it.
7. Invoke the event on the custom control.

### Expected Behavior

The event handler is called correctly.

### Actual Behavior

Everything works fine until the page is navigated away from and back to. Invoking the event then results in an ObjectDisposedException against the control.
Placing a breakpoint on the OnElementChanged method in the renderer and adding an overridden Dispose method with a breakpoint shows that when the page is navigated away from the Dispose method is called but OnElementChanged is not called. When the page is navigated back to a new renderer instance is created and the OnElementChanged method is called with a NewElement referenced in the ElementChangedEventArgs so an additional event handler is attached.
When the event is invoked the handler for the old renderer instance is still trying to be called which is now disposed.

### Basic Information

- Version with issue: Xamarin Forms 4.3.0.908675
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: API 27

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/2520
