### ISSUE TITLE
[Bug] iOS Shell Menu hamburger disappears after return to main page

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8240]
1. Create Shell app using template
2. Push any page
3. press back button

Current behavior
hamburger and masteropage are missed

Note:
if you add tabbar and switch between tabs hamburger will appear

iOS 12.4
XF latest nightly build

**Comment by hartez** [comment]
@VladislavAntonyuk I'm trying to reproduce this issue, but I am not having any luck. Could you upload a minimal reproduction project or post your shell XAML and code? Thanks.

**Comment by VladislavAntonyuk** [comment]
probably it is related to https://github.com/xamarin/Xamarin.Forms/issues/8285, I will try to reproduce it

**Comment by samhouts** [comment]
@VladislavAntonyuk Any luck reproducing this issue? Thanks!

**Comment by VladislavAntonyuk** [comment]
@samhouts After update to the latest XF packages I can’t reproduce it on iOS simulator (I tried 12.4 and 13.2.2). I will try tomorrow on a real device and close the issue if it is not reproduced
