### ISSUE TITLE
[Bug] IsClippedToBounds value isn't working when we set via implicit style 

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#8249]
### Description

Hi Team,

We at Syncfusion develope data visualization controls for Xamarin, Please refer to the below link for a description about us.
UserGuide: https://help.syncfusion.com/xamarin/introduction/overview
FeatureTour: https://www.syncfusion.com/products/xamarin.

We have currently noticed an issue when setting the isClippedToBounds value through implicit style and other than IsClippedToBounds property the BackgroundColor and all other properties are working fine in implicit style.

For your understanding, I have created a simple sample, in that we have derived a CustomScrollView from the ScrollView in that we have overridden the property changed method and in that constructor have set the IsClippedToBounds property to true.  At the same time, in style, have set the  IsClippedToBounds as False. From the observation of flow first constructor will trigger first and IsCippedToBound property changed from default value false to true then style property notification get trigged and set the property have set in the style other than IsClippedBounds all property changed notification will get visually.

### Steps to Reproduce

1. Go to SimpleSfTabView.Xaml.cs-> CustomScrollView -> Place the breakpoint on constructor and property changed the method  
2. Please look on App. XAML I have set the style and initialized to scroll view 
3. Run the attached sample
4) PropertyChanged will trigger on setting the IsClippedToBounds value in the constructor but when we set through style we didn't get the notification for IsClippedToBounds value changing and there is no property change get triggered 

### Expected Behavior
IsClippedToBounds value should works when we set through the implicit stye 
### Actual Behavior
IsClippedToBounds value doesn't work when we set through the implicit stye 
### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2017
- Platform Target Frameworks: All Android device 
- NuGet Packages: Xamarin.Forms 4.2
- Affected Devices:

### Reproduction Link

Video link : [SfTabShowCase3.zip](https://github.com/xamarin/Xamarin.Forms/files/3774497/SfTabShowCase3.zip)
Sample link : [SfTabShowCase.zip](https://github.com/xamarin/Xamarin.Forms/files/3774498/SfTabShowCase.zip)

**Comment by hartez** [comment]
> in that constructor have set the IsClippedToBounds property to true.

You are setting an explicit value for `IsClippedToBounds` - this takes precedence over the value from the style. Comment out `this.IsClippedToBounds = true;` in your constructor, and you'll see `OnPropertyChanged` called for `IsClippedToBounds`.

**Comment by BalasubramaniSundaram** [comment]
Hi @hartez, 

My clear use-case is by default want to my control IsClippedToBounds be true, at some sort of condition I need to change my property value to false through implicit. whatever the situation property value should need change through explicit or implicit.

For example.
In my control by default, I had set the background as blue in the constructor. It's ok for one page, on another page I decided to change the background color of my control so I have written the implicit style and set it to my control. As per your flow, my implicit style won't work at the time of loading and changing at run time it will load with default value of blue only.

Please explain clearly?  

regards, 
@BalasubramaniSundaram

**Comment by BalasubramaniSundaram** [comment]
Hi @hartez 

Colud you please re-open this incident

Regards, 
Balasubramani Sundaram.

**Comment by Sivaraman761** [comment]
Hi @hartez 

we are also facing the issue. Can you please check this?

**Comment by hartez** [comment]
@BalasubramaniSundaram So you want your CustomScrollView to have an `IsClippedToBounds` setting of `true` by default, and in some cases you want to apply a Style which will change `IsClippedToBounds` to `false`? 

You can do this by creating an implicit style for the CustomScrollView type which sets `IsClippedToBounds` to `true`:

```
<Style TargetType="local:CustomScrollView">
    <Setter Property="IsClippedToBounds" x:DataType="x:Boolean" Value="True"/>
</Style>
```

And then an explicit style which you can apply when you want to change the value to `false`:

```
<Style TargetType="ScrollView" x:Key="ScrollViewStyle">
	<Setter Property="IsClippedToBounds" x:DataType="x:Boolean" Value="False"/>
</Style>
```

All CustomScrollView will have `IsClippedToBounds` set to `true` because of the implicit style; you don't have to set it in the constructor. And if you apply the explicit style (for example, by setting `Style="{x:StaticResource ScrollViewStyle}"`), `IsClippedToBounds` will be set to `false`.


Here is an updated version of your repro to demonstrate: 
[StyleExample.zip](https://github.com/xamarin/Xamarin.Forms/files/3779584/StyleExample.zip)

**Comment by BalasubramaniSundaram** [comment]
Hi @hartez , 
  
   Thanks for your help, but we are providing support for a custom control, for a purpose we have set the IsClippedToBounce as true in our control but the customer can change through explicit or implicit but based on their requirement. But whatever we did the change it is not working . Please help to overcoming this issue.

**Comment by Sivaraman761** [comment]
Hi @hartez 

Any update on this?

**Comment by hartez** [comment]
@BalasubramaniSundaram and @Sivaraman761 Without seeing your custom control code, I can't tell you what you are doing wrong. Can you post it here?
