### ISSUE TITLE
[Enhancement] Application.Current.MainPage.DisplaySnackbar

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8251]
## Summary
MainPage can display messages and prompts, which requires user interaction (press button).
Using toast or snackbar you can display user friendly notification without necessity to click any button. 

```Application.Current.MainPage.DisplaySnackbar(message, duration = 3000, actionButtonText=null, action=null);```

## API Changes

Add new method which will call native implementation:
- For Android I think it would be Snackbar (https://material.io/develop/android/components/snackbar/) or Toast (https://developer.android.com/guide/topics/ui/notifiers/toasts)
- For iOS something like this (https://www.cocoacontrols.com/controls/snackbar-ios)
- For UWP/macOS I vote for Notifications as a native way to display any info (but snackbar would also look very nice)
- WPF/GTK/Tizen - up to devs - I think snackbar would be easier implement

## Intended Use Case
Any kind of notifications ("Data is stored; File is deleted");

**Comment by xamarindevelopervietnam** [comment]
vote

**Comment by BurkusCat** [comment]
> For UWP/macOS I vote for Notifications as a native way to display any info (but snackbar would also look very nice)

Would a notification on UWP/Mac be the best equivalent? I think for most uses of a snackbar/toast, those kinds of messages appearing as full-blown notifications would be quite annoying. I think the user would expect the messages to appear in-app and automatically disappear like snackbars/toasts.

The WindowsCommunityToolkit has an InAppNotifications control: https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls/InAppNotification which is quite nice! It can be given a timing and can have actions.
![image](https://user-images.githubusercontent.com/7528322/93025605-0eaa7200-f5f7-11ea-8040-fe7470a1792c.png)

**Comment by VladislavAntonyuk** [comment]
I think we shouldn’t combine notifications and Snackbar.

**Comment by rmarinho** [comment]
This is being worked at https://github.com/xamarin/XamarinCommunityToolkit please follow up there
