### ISSUE TITLE
[Enhancement] Maps pin Add icon property

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8252]
## Summary
Using icon property I can set custom pin image, so I do not need to create custom MapRenderer

## API Changes

Add new property maps:Pin.Icon

## Intended Use Case
Mark different objects on map depend on the markerId

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
