### ISSUE TITLE
[Enhancement] [iOS] Make SearchTextField accessible from SearchBarRenderer

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#8256]
## Summary
(For context, see also #8255)

As of iOS 13, the UISearchBar's search text field is publicly available (https://developer.apple.com/documentation/uikit/uisearchbar/3175433-searchtextfield). Up to this point, Forms has accessed it via `Control.FindDescendantView<UITextField>()` to set the private `_textField` member in the `SearchBarRenderer`. 

Forms should be updated to use the new `searchTextField` property when targeting iOS 13+, and only use `FindDescendantView` for older versions (the new field is faster and more future-proof). 

Additionally, the private `_textField` member should be replaced with a protected member so folks who are implementing custom renderers have access across versions without having to implement their own version check. 

## API Changes

Add:

`protected UITextField Xamarin.Forms.Platform.iOS.SearchBarRenderer.SearchTextField`

## Intended Use Case
Provide a detailed example of where your proposal would be used and for what purpose.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
