### ISSUE TITLE
[Enhancement] Add On/Off VisualStates for Switch

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#8263]
## Summary

Provide On/Off VisualStates for the Switch control so that users can style them in the VisualStateManager.

## API Changes

None; this would simply require adding a changed handler for the `Switch.IsToggledProperty` and calling `ChangeVisualState()`; `ChangeVisualState` would need to be overridden for the Switch to set the appropriate state.

## Intended Use Case

Users may want to change the Switch ThumbColor or other properties (see #8258) based on the state of the Switch. This will allow them to do so.

**Comment by techduggu** [comment]
I'm working on this.

**Comment by mfeingol** [comment]
@techduggu: out of curiosity, is it possible to set up a VSM using a global style, so e.g. we can control thumb colors for all Switch instances in one place?

Thanks.
