### ISSUE TITLE
[Bug] Visual Editor expand line problem

### ISSUE THREAD

**Issue by uponpara** [xamarin/Xamarin.Forms#8267]
### Description
Visual Editor work fine on Android device, simulator and iOS simulator.
But on iOS device expand line have problem.

### Expected Behavior

Enter new line of Editor would expand and push down control another after Editor.

### Actual Behavior

Expand line under another control.

### Basic Information

- Version with issue: 4.3
- Last known good version: Just tested with lastest version.
- IDE: VS 2019.
- Platform Target Frameworks: 
  - iOS:  12

### Screenshots
![IMG_1719](https://user-images.githubusercontent.com/25874722/67670384-6079e780-f9a6-11e9-9b08-b32213b3d4ce.PNG)
### Reproduction Link

**Comment by hartez** [comment]
I have not been able to reproduce this yet - could you post a repro project or your page layout code/markup?

**Comment by uponpara** [comment]
> I have not been able to reproduce this yet - could you post a repro project or your page layout code/markup?

...
<Stacklayout>
<Frame BorderColor="Black">
            <StackLayout>
                <Entry Visual="Material" Placeholder="Entry" PlaceholderColor="Orange"/>
                <Entry Visual="Material" Placeholder="Entry" Keyboard="Numeric" PlaceholderColor="Orange"/>
                <Editor Visual="Material" Placeholder="Editor" PlaceholderColor="Orange" AutoSize="TextChanges"/>
            </StackLayout>
        </Frame>
        <Button Text="CLICK" Visual="Material" CornerRadius="20"/>
</Stacklayout>

Please, check with this code.

**Comment by uponpara** [comment]
> I have not been able to reproduce this yet - could you post a repro project or your page layout code/markup?
```
<StackLayout>
        <Frame BorderColor="Black">
            <StackLayout>
                <Entry Visual="Material" Placeholder="Entry" PlaceholderColor="Orange"/>
                <Entry Visual="Material" Placeholder="Entry" Keyboard="Numeric" PlaceholderColor="Orange"/>
                <Editor Visual="Material" Placeholder="Editor" PlaceholderColor="Orange" AutoSize="TextChanges"/>
            </StackLayout>
        </Frame>
        <Button Text="CLICK" Visual="Material" TextColor="Black"/>
</StackLayout>
```
Please, check with this code.

**Comment by hartez** [comment]
@uponpara I still cannot reproduce this issue with your layout. I'm attaching my repro project - can you take a look and let me know what I'm missing?

[_8267 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3806544/_8267.Repro.zip)

**Comment by uponpara** [comment]
Hi @hartez, my bad. I'm using Shell. 
Please check again.
![animated](https://user-images.githubusercontent.com/25874722/68173085-5d858500-ffac-11e9-8f1c-e8dd300df692.gif)

**Comment by aismaniotto** [comment]
I am facing the same problem here.

**Comment by aismaniotto** [comment]
The problem doesn't occourn anymore on last version of `Xamarin.Forms`.
