### ISSUE TITLE
[Bug] CollectionView exception when IsGrouped=true and null ItemSource

### ISSUE THREAD

**Issue by ykoorb** [xamarin/Xamarin.Forms#8269]
### Description
When using IsGrouped="true" on a CollectionView, an error is thrown when the datasource is null. Seems obvious now i write it down - but the control is more forgiving when IsGrouped="false". Also, although the exception mentions a null reference, it was tricky to track down the source when it occurred. A workaround is to set the ItemSource to an empty list rather than a null list.

### Steps to Reproduce

Using the CollectionView Demo as a base - https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/CollectionViewDemos 

1.  Change line 9 of GroupedAnimalsViewModel.cs to have a null value rather than a new List
2.  Run the app on Android (i haven't tried on any other platform)
3.  Click into one of the grouping example pages

### Expected Behavior
Show nothing

### Actual Behavior
Throws an exception

- Version with issue: 4.3
- IDE: VS2019

**Comment by roycornelissen** [comment]
Just observed the same thing in Android. iOS works fine.
