### ISSUE TITLE
Flyout icon not displaying after upgrading to version 4.3

### ISSUE THREAD

**Issue by JeanMarcMbouma** [xamarin/Xamarin.Forms#8285]
### Description
Flyout icon not displaying after upgrading to version 4.3
### Steps to Reproduce

1. Create a shell based application using Xamarin.Forms version 4.3
2. Launch the app
3. Set the Shell.FlyoutBehavior to Flyout explicitly and try again

### Expected Behavior
Flyout icon displays the hamburger icon by default.
### Actual Behavior
No icon is displayed
### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: 4.2.0.709249
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9.0 
- Nuget Packages: Xamarin.Forms v4.3.0.908675
- Affected Devices: All devices, simulator included.

**Comment by techduggu** [comment]
Team, I tested it with both 4.3.0 and master branch and I'm able to see Flyout icon (can't reproduce the issue). Is there any specific branch for 4.3.0.908675 ?

![image](https://user-images.githubusercontent.com/17450941/67846103-a78ee680-fb26-11e9-8780-1daf13e9121b.png)

**Comment by JeanMarcMbouma** [comment]
This is the before and after from AppCenter Tests

Before:
![image](https://user-images.githubusercontent.com/16613177/68071645-0baee600-fd85-11e9-941c-cf7e713f837c.png)


After:
![image](https://user-images.githubusercontent.com/16613177/68071651-22edd380-fd85-11e9-81c3-aea3185d590b.png)

**Comment by hartez** [comment]
[_8285 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3802362/_8285.Repro.zip)

**Comment by Altevir** [comment]
This is also happening using FlyoutIcon with Shell.ItemTemplate, after the update has stopped displaying the icons and still shows a line under the menu items.

IDE: Visual Studio Community 2019 v16.3.8
Nuget Packages: Xamarin.Forms v4.3.0.908675
Platform Target Frameworks:
Android: 9.0
iOS: All Versions
Affected Devices: All devices, simulator included.

![flyouticon_menu](https://user-images.githubusercontent.com/11803107/68301850-980c2200-007f-11ea-8b22-76c54ca46f41.JPG)

**Comment by PureWeen** [comment]
@hartez 's sample isn't valid for this issue

@Altevir 's against latest shows all the images
