### ISSUE TITLE
[Bug] UWP DataTemplate Picker inside CollectionView Xamarin v4.3.0

### ISSUE THREAD

**Issue by AndreiZachi** [xamarin/Xamarin.Forms#8289]
### Description
CollectionView - DataTemplate Picker in Xamarin v4.3.0 will not show values bound to observablecollection<observablecollection<string>> in UWP. Android and iOS work as expected . Only solution is to roll back to 4.2. Tested on multiple machines with the same result. 

### Steps to Reproduce

1. Create CollectionView with Picker as DataTemplate
2. Create ObservableCollection<ObservableCollection<string>> 
3. bind Collection view to ObservableCollection<ObservableCollection<string>>
4. bind picker to ObservableCollection<string>

### Expected Behavior
Items visibile in UWP, Android and iOS. 
### Actual Behavior
Items are visible ONLY in Android and iOS
### Basic Information

- Version with issue: 4.3.0
- Last known good version: 4.2.0
- IDE: Visual Studio 2019 v 16.3.5
- Platform Target Frameworks: 
  - iOS:  v13.1
  - Android: API 28 
  - UWP:  16299 -> 18... 

### Screenshots

![testAndroid](https://user-images.githubusercontent.com/41480414/67781880-ef970600-fa5f-11e9-8180-c0c82448fe37.JPG)
![testIOS](https://user-images.githubusercontent.com/41480414/67781881-ef970600-fa5f-11e9-97d7-1a6c347e5eb7.JPG)
![testUWP](https://user-images.githubusercontent.com/41480414/67781883-ef970600-fa5f-11e9-9032-cf9f848cbc62.JPG)

### Reproduction Link

https://bitbucket.org/AndreiZachiteanu/test/src/master/

**Comment by MagicAndre1981** [comment]
could be a [duplicate](https://github.com/xamarin/Xamarin.Forms/issues/8177).

**Comment by AndreiZachi** [comment]
It seems to affect the same control, but the scenario is different. He uses CollectionView and Picker as 2 separate controls, while I have the Picker as DataTemplate for the CollectionView. It seems to be the reason why he has items showing on initialise(), while mine is empty. I haven't gotten to the "Updating part".

**Comment by hartez** [comment]
Definitely not a duplicate of 8177 - just tried the fix for 8177 against this repro, and it's still not working.

**Comment by MagicAndre1981** [comment]
ok, thanks for testing it

**Comment by AndreiZachi** [comment]
Any changes?

**Comment by hartez** [comment]
This is fixed as of 5.0.0.1931 (possibly earlier, but that's the version I tested).
