### ISSUE TITLE
[Enhancement] Add SelectedBarTextColor and UnSelectBarTextColor to TabbedPage

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#8295]
Now TabbedPage has feature for changing the SelectedTabColor and UnSelectedTabColor and BarTextColor.
But Now I want a feature after select the tab , change the Selected tab color and Selected bar text color(other unselected bar text color keep default color ).But now no api for changing the color of selected bar text.

**Comment by techduggu** [comment]
This will possibly get implemented by https://github.com/xamarin/Xamarin.Forms/pull/7348

**Comment by jingliancui** [comment]
great

**Comment by samhouts** [comment]
Duplicate of #3281
