### ISSUE TITLE
[Bug]  Android picker and hardware back button

### ISSUE THREAD

**Issue by acaliaro** [xamarin/Xamarin.Forms#8309]
It seems #7311 is still alive

### Steps to Reproduce
We have two problems:
On a Zebra ET5X
1. open a picker tapping on it
2. press back button, the picker close
3. press again back button, the picker reopen

On a samsung galaxy tab active pro
1. open a picker tapping on it
2. press back button, the picker close and immediately reopen

### Expected Behavior
pressing back button, the picker close. pressing again the back button, the back should work as a back button. It seems a "focus problem"... maybe?
### Actual Behavior
as described...

### Basic Information

- Version with issue: XF 4.2.0.709249
- Last known good version: unknown
- IDE: VS2019 16.3.5
- Platform Target Frameworks: 
  - Android: 9.0
[XFPickerProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/3789988/XFPickerProblem.zip)

- Affected Devices:
samsung galaxy tab active pro
Zebra ET5X

**Comment by hartez** [comment]
This is fixed in 4.3.0.
