### ISSUE TITLE
xamarin form map customized marker issue on Android

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8315]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/798511/xamarin-form-map-customized-marker-issue-on-androi.html)._

---
<p>use the newest Xamarin.Forms and Xamarin.Forms.Maps (4.3.0.908675) to customized map marker/pin (via Visual Studio 2018 Enterprise Edition). It works very well on iOS devices. But it has the problem on Android phone at the some situation. Sometimes, the customized marker works well, but it doesn't work sometimes. The problem may be caused by the customPins' size which is retrieved by OnElementChanged (?). Sometimes it is null and sometimes it's number is less than the number of added markers. When it happens, the customPin can't be found from customPins. The partial source code is<br><br>        List&lt;CustomPin&gt; customPins;<br>        CustomPin customPin;<br>        public CustomMapRenderer(Context context) : base(context)<br>        {<br>            customPin = null;<br>        }<br><br>        protected override void OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs&lt;Map&gt; e)<br>        {<br>            base.OnElementChanged(e);<br><br>            if (e.OldElement != null)<br>            {<br>                NativeMap.InfoWindowClick -= OnInfoWindowClick;<br>            }<br><br>            if (e.NewElement != null)<br>            {<br>                var formsMap = (CustomMap)e.NewElement;<br>                customPins = formsMap.CustomPins;<br>                Control.GetMapAsync(this);<br>            }<br>        }<br><br>        protected override MarkerOptions CreateMarker(Pin pin)<br>        {<br>            var marker = new MarkerOptions();<br>            marker.SetPosition(new LatLng(pin.Position.Latitude, pin.Position.Longitude));<br>            marker.SetTitle(pin.Label);<br>            marker.SetSnippet(pin.Address);<br>            CustomPin cp = customPins.Find(x =&gt; x.MarkerId == pin.MarkerId);<br>            if (cp != null)<br>            {<br>              .......<br>            }<br>            else<br>            {<br>              ......<br>            }<br><br>            return marker;<br>        }</p><p>PS:</p><p>More detail description for the issue: When the app is started at the first time, enter the map page (must quit the app from an Android phone if it is running at the background). customPins has the exact the number of customized pins which I added (for example, I add 30 pins, every time when CreateMarker is called, the customPins.Count is 30). But if leave this map page and enter the page again (still only add 30 pins), the number of customPins is increased from 0, 1, 2, 3, ...., 29, etc. when CreateMarker is called at every time</p>

---
#### Visual Studio Feedback System on 10/30/2019, 01:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
We are trying to reproduce this issue, but so far we have not been able to. Could you please post a minimal reproduction project which demonstrates the issue? Thank you.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
