### ISSUE TITLE
[Bug]Error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, on Project Xamarin.IOS

### ISSUE THREAD

**Issue by lrauseo** [xamarin/Xamarin.Forms#8316]
Custom Renderer for Admob and App Does Not Build
Error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. (CS0012)

### Steps to Reproduce

1. Create Custom Renderer Xamarin.Forms for Admob
2. Build Xamarin.IOS
3. Error on Building

### Expected Behavior
Compile
### Actual Behavior
Error
### Basic Information

- Version with issue:  Visual Studio For Mac (8.3.5)
- Last known good version:
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:  Version: 12.3.1.28
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices: IOS Devices

### Screenshots
![Captura de Tela 2019-10-30 às 23 34 36](https://user-images.githubusercontent.com/14141594/67914222-3a06a880-fb6e-11e9-9681-7b1225a77aae.png)

**Comment by hartez** [comment]
@lrauseo Can you please post a minimal repro project? We're having difficulty reproducing this error. 

Thanks.

**Comment by lrauseo** [comment]
Hello, I do not know what I did. I completely uninstalled visual studio and xamarin and installed it again and apparently it's working
