### ISSUE TITLE
[Feature-requested-modal-page] Property to block swipe down modal page 

### ISSUE THREAD

**Issue by Thanghand** [xamarin/Xamarin.Forms#8317]
## Summary
In IOS 13, Apple introduce new style of modal page
![IIoCCm](https://user-images.githubusercontent.com/8011261/67913450-b1b0f380-fbbf-11e9-83de-0fc7ff277cb5.jpeg)
In Xamarin, we have a problem that when we swipe down the modal page. The NavigateToModalAsync of Navigation is not work any more. To solve this problem I have to treat them by removing page in modal stack, but it is not good. 
So I suggest Xamarin Forms should have 2 things to do:

1. Giving the property to block swipe down the modal page like this:

![Eas3G](https://user-images.githubusercontent.com/8011261/67913750-a3170c00-fbc0-11e9-9c0b-f30db0219b3d.gif)
 
2. Fix problem swipe down break navigation modal stack

## API Change:
`On<iOS>().SetHasBlockDismissModalPage(true);`

( Default is false )

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
