### ISSUE TITLE
[Bug] Picker dialog UI changes when using no-op custom renderer on Android

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#8318]
### Description

Picker dialog UI changes when using no-op custom renderer for picker. See screenshots below.

Let me know if you need a repro project, but the issue is pretty obvious. This isn't by design, is it?

### Steps to Reproduce

Add a .cs file with this code to your project, and add a picker with some options:

```
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;
using Android.Content;

[assembly: ExportRenderer(typeof(Picker), typeof(Repro.ReproPickerRenderer))]
namespace Repro
{
    public class ReproPickerRenderer : PickerRenderer
    {
        public ReproPickerRenderer(Context context) : base(context)
        {
        }
    }
}
```

### Expected Behavior

Without the custom renderer:

![expected](https://user-images.githubusercontent.com/218865/67919624-5d295c00-fb5e-11e9-953c-8463a6dbe0cb.png)

### Actual Behavior

With the no-op custom renderer:

![actual](https://user-images.githubusercontent.com/218865/67919633-60bce300-fb5e-11e9-9419-09aeb5c5ee17.png)

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: Unknown
- IDE: VS 2019 16.3.7
- Platform Target Frameworks: 
  - Android: 9.0
- Android Support Library Version: 28.0.0.3

**Comment by mfeingol** [comment]
Any ideas on this one?

**Comment by hartez** [comment]
There are multiple `PickerRenderer` classes in Forms; it looks like you're inheriting from the legacy (pre-AppCompat) one. You probably want this:

```
public class ReproPickerRenderer : Xamarin.Forms.Platform.Android.AppCompat.PickerRenderer
{
    public ReproPickerRenderer(Context context) : base(context)
    {
    }
}
```

**Comment by mfeingol** [comment]
Excellent point. Thank you!

(It works.)
