### ISSUE TITLE
carouselview stopped supporting right to left navigation between views

### ISSUE THREAD

**Issue by arickatz** [xamarin/Xamarin.Forms#8319]
### Steps to Reproduce

1. use carouselview in xaml page
2. set  FlowDirection="RightToLeft"
3. try to move on page

### Expected Behavior
scrolls from right to left
### Actual Behavior
only scrolls from left to right
### Basic Information

- Version with issue: 4.5.0.13...
- Last known good version: 4.5.0.1297
- IDE: VS 2019 MAC
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
Both UWP and iOS appear to ignore the FlowDirection when laying out the items in the carousel.

**Comment by hartez** [comment]
[_8319 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3796029/_8319.Repro.zip)

**Comment by davidortinau** [comment]
Related to or duplicate of #7780

**Comment by rmarinho** [comment]
Yes duplicated of #7780
