### ISSUE TITLE
[Bug] CollectionView ItemLayout Vertical Grid Ignore Flow Direction

### ISSUE THREAD

**Issue by Scarnet** [xamarin/Xamarin.Forms#8321]
### Description
When you set the ItemLayout property of the collection view to GridItemsLayout with orientation set to Vertical, the CollectionView ignores the FlowDirection if it was set to RightToLeft on Android (didn't have the chance to test this on iOS or UWP though) 
### Steps to Reproduce

1. Declare a collection view in XAML
2. Set the FlowDirection property to RightToLeft
3. Set the ItemLayout property to GridItemLayout while setting the Orientation property to Vertical

### Expected Behavior
The collection view should start rendering the items from right to left for each row
### Actual Behavior
The collection view renders items from left to right
### Basic Information

- Version with issue: 4.3.0.947036
- IDE: Visual Studio Community 2019 Preview (Windows)  version 16.3.0 Preview 4.0
- Platform Target Frameworks: 
  - Android: API 28
 - Android Support Library Version: 28.0.0.3

### Screenshots
![Screenshot_20191031-142402](https://user-images.githubusercontent.com/6840193/67946573-4d575980-fbea-11e9-9c99-3d3e529e7498.png)

### Reproduction Link
https://github.com/Scarnet/CollectionViewFlowBug

**Comment by hartez** [comment]
This is working, the example is missing the `android:supportsRtl="true"` setting in [AndroidManifest.xml](https://developer.android.com/guide/topics/manifest/application-element#supportsrtl). Add that value and the layout will be RTL as expected.
