### ISSUE TITLE
[Bug] HotReload with x:Name and change Control type crash

### ISSUE THREAD

**Issue by hudaIT** [xamarin/Xamarin.Forms#8322]
### Description
When I change the type of a control which has a x:Name attribut (for example from StackLayout to Grid), the app crashes because it can not resolve the type in the code behind (.xaml.g.cs file)

### Steps to Reproduce

1. Create a Grid with a x:Name Attribut "test"
2. Change the Grid from `<Grid x:Name="test"/>` to `<StackLayout x:Name="test"/>`

### Expected Behavior
Should behave the same as if there would not be a x:Name attribut
### Actual Behavior
App crashes
### Basic Information

- Version with issue: All versions
- Last known good version: None
- IDE:
- Platform Target Frameworks: Xamarin.Forms v4.5.0.1319-nightly

Tested on reald Android device

**Comment by hartez** [comment]
@hudaIT Is this happening on Android or iOS?

**Comment by hudaIT** [comment]
@hartez i only tested on Android

**Comment by hartez** [comment]
@hudaIT I tried this on Android and it worked fine for me - I could change the Grid to a StackLayout and the new control would load on the simulator.

When you say "App crashes" - do you mean the app you are debugging, or Visual Studio?

Also, are you seeing this with Visual Studio on Windows, or Mac?

**Comment by hudaIT** [comment]
@hartez okay i will look a little bit further into the issue whats causing it. Seems i was wrong assuming that the x:Name is causing it.

**Comment by hudaIT** [comment]
Duplicate of #8398

**Comment by hartez** [comment]
@hudaIT Are you seeing the symptoms described in 8398? Is Visual Studio stopping on an exception?

**Comment by hudaIT** [comment]
Tried evrything to reproduce the issue, however was not successful to do so. Therefore i am going to close this issue now.
