### ISSUE TITLE
[Bug] [Android][UWP] CollectionView: empty view doesn't show if collection view contains a header

### ISSUE THREAD

**Issue by bugaga6enika** [xamarin/Xamarin.Forms#8326]
### Description
In case you have a header in a collection view and an empty items source the empty view doesn't show on Android. It gets more confusing depending on an items source: if the items source is an empty collection then header is visible (the rest of the screen is just a blank page). But if the items source is null then the header is not visible anymore but an empty view is displayed.

### Expected Behavior
I assume that header should be visible with an empty view no matter if items source is null or an empty collection.  As it does currently on iOS. 

### Basic Information

- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: 9

- Nuget Packages: Xamarin.Forms 4.3.0.947036

### Screenshots

iOS
![image](https://user-images.githubusercontent.com/9405627/67955273-a1fed280-fbf2-11e9-92fd-fb36d6f79074.png)

Android

![image](https://user-images.githubusercontent.com/9405627/67955312-af1bc180-fbf2-11e9-8d9f-17c5ec6d9b5e.png)

[CollectionViewHeaderWithEmptyView.zip](https://github.com/xamarin/Xamarin.Forms/files/3794205/CollectionViewHeaderWithEmptyView.zip)

**Comment by hartez** [comment]
I suspect this also happens with Footer.

**Comment by bugaga6enika** [comment]
@hartez  Yes, same behaviour with the footer as well

**Comment by albertoha94** [comment]
I am also experiencing this issue in Android 10.
EmptyView is displayed **ONLY** after i removed Header and Footer, if i put any of those, the EmptyView disappears.
No header:
![screenshot-1572804897661](https://user-images.githubusercontent.com/14353851/68090313-f5159700-fe37-11e9-8b25-df6aca2ea327.jpg)

Header added:
![screenshot-1572806657073](https://user-images.githubusercontent.com/14353851/68090314-f5ae2d80-fe37-11e9-8e1f-739b050c1662.jpg)

**Comment by garyng** [comment]
This is indeed a _very confusing_ bug...

**Comment by samhouts** [comment]
closed by #8415
