### ISSUE TITLE
[Bug, Shell, iOS] ToolbarItem Order ignored

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#8327]
There was a bug for this on Android which is fixed, but as it turns out this also happens on iOS.

All details in linked issue below. Point of origin is ShellPageRendererTracker.UpdateToolbarItems. The `Order` property is not taken into account. Unfortunately, for iOS we are drawing our own secondary toolbar instead of simply setting a property on the menu item.

_Originally posted by @KoenMat in https://github.com/xamarin/Xamarin.Forms/issues/6127#issuecomment-548377334_

**Comment by jayhoogle** [comment]
I'm using XF 4.6.0.800 and still having this issue on iOS. Do you know if there's a fix coming?

**Comment by twelve-cgn** [comment]
@samhouts Using XF 5.0.0.2012 and also still having this issue on iOS.

**Comment by stephajn** [comment]
Experiencing this same issue using the latest version of Xamarin Forms. On Android it works as expected. I even compared my code with the code sample on GitHub and tried setting Priority as well. Made no difference. On an iOS device, the Order property is completely ignored. This issue should NOT be closed.

**Comment by ivanrlg** [comment]
Hello, I have the same problem with the last version of Xamarin, any workaround?
