### ISSUE TITLE
xamarin forms picker with ViewModel not showing list

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8337]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/790480/xamarin-forms-picker-with-viewmodel-not-showing-li.html)._

---
[regression] [worked-in:After update version 16.3.6]
If I update Xamarin.Forms on Nuget from v4.2.0.848062 to v4.3.0.908675 the picker controll not show the values list. The source is OK, and I Get the value with selectedindex on code behind, but I do not get choise the value on view side. See the pictures.

---
#### Visual Studio Feedback System on 10/23/2019, 11:55 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
What platforms are you seeing this problem on? UWP? Android? iOS? All of the above?

**Comment by hartez** [comment]
If this is just happening on UWP, it is likely another instance of #8177.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
