### ISSUE TITLE
[Bug] Grouped CollectionView Throws exception on iOS when Grouped data source is empty

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8344]
### Description
I am using CollectionView for displaying grouped data as accordion. But initially I want to keep the data source empty. When user click on Group header the data is added to the source collection. But in iOS clicking on the any header except the last one throws exception. The Android app works fine. The exception reads as:

Objective-C exception thrown.  Name: NSRangeException Reason: *** 
-[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array

The exception is not thrown if last group header is clicked. After clicking on last GroupHeader the app runs normally and any GroupHeader can be clicked without any error. 

### Basic Information

- Version with issue:Xamarin.Forms (4.3.0.947036)
- IDE:VSMac
- Affected Devices:iOS

[ShellRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3796782/ShellRepro.zip)

**Comment by HobDev** [comment]
This issue may be related with https://github.com/xamarin/Xamarin.Forms/pull/8273

**Comment by jsuarezruiz** [comment]
I have done some tests in the master branch, and it seems that #8273  fix this issue.
<img width="408" alt="Captura de pantalla 2019-11-05 a las 13 38 37" src="https://user-images.githubusercontent.com/6755973/68208720-1a3e0d00-ffd2-11e9-9389-77458e52da8a.png">

**Comment by samhouts** [comment]
Closed by #8273
