### ISSUE TITLE
[Bug] CollectionView ItemSpacing does not affect the Item spacing on iOS

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8345]
### Description
I am using Grouped CollectionView for displaying data. The specified ItemSpacing is 10. But the CollectionView Items does not have any space in between them on iOS. 

### Basic Information

- Version with issue:Xamarin.Forms (4.3.0.947036)
- IDE:VSMac
- Affected Devices:iOS

### Reproduction Link
[ShellRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3796844/ShellRepro.zip)

**Comment by hartez** [comment]
Android is applying item spacing to group headers (and presumably footers), iOS is not. Need to determine which is the correct behavior so we can make it consistent (and verify that UWP is consistent, too).

**Comment by HobDev** [comment]
As per my needs the itemspacing should be applied to the headers too. In the repro sample the item spacing is not  applying to group headers in iOS. It is also not applying to the item if it is expanded in iOS only.
