### ISSUE TITLE
[Enhancement] Pre-define DisplayPromptAsync

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#8346]
I really like the new DisplayPromptAsync. One feature it lacks is the ability to pre-define the value so you can use it to amend a line of text.

An example use case is if you have a list view of products and their descriptions. I want to be able to click on an item and amend the description using DisplayPromptAsync but having to type out the whole description again is frustrating.

Maybe adding a new optional property to DisplayPromptAsync would suffice.

**Comment by adrianknight89** [comment]
There was another suggestion recently to make the entry a Password field on demand. Adding it here for tracking.

**Comment by hartez** [comment]
> There was another suggestion recently to make the entry a Password field on demand. Adding it here for tracking.

Where was that suggested - is there a GitHub issue for that?

**Comment by adrianknight89** [comment]
It was commented under #6714.

**Comment by jfversluis** [comment]
Made a PR for this and created an issue for the password (and others) request here #8363
