### ISSUE TITLE
[Bug] Shell QueryProperty Parameter iOS Navigating previous value

### ISSUE THREAD

**Issue by jpveldtman** [xamarin/Xamarin.Forms#8347]
### Description
On iOS, when navigating to an already existing page with a new Uri the parameter in the uri is ignored the second time and process the previous thereafter.
Android is working as expected.
This is related to #6543 and #6695, but with a  bit of a different behaviour.

### Steps to Reproduce
From the sample project:
1. On the Origin tab, Press the button (Ex. Send - 18)
2. Passes the Query and automatically navigates to Check Tab, and the value is 18
3. Manually go back to Origin Tab, Query that will be sent has changed (Ex. Send - 67)
4. QueryParameter is not fired_ (When adding a breakpoint it does not trigger), Last value is still 18
5. Manually go back to Origin Tab, Query that will be sent has changed (Ex. Send - 54)
6. Even though 54 was sent, the value received on the page is 67

### Expected Behaviour
The Query should fire every time like on Android
### Actual Behaviour
The Query didn't fire the second time, and afterwards is one value behind
### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: Unknown/None
- IDE:VS 2019 for Windows v16.3.7
- Platform Target Frameworks: iOS 11+
 

### Reproduction Link
[QueryTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3798005/QueryTest.zip)

**Comment by PureWeen** [comment]
@jpveldtman can you test this on the latest 4.5 release?

I was able to reproduce your issue on 4.3 but wasn't able to on 4.5
