### ISSUE TITLE
[Enhancement] Add bindable property that indicates image was loaded in Image

### ISSUE THREAD

**Issue by IgorKravchenko10** [xamarin/Xamarin.Forms#8350]
## Summary
Hi! I am using UriImageSource. It works perfect but I want to create custom control with loading animation. For this I need to know that image was loaded. It will be perfect to change property **IsLoading** to **bindable** or create **event Loaded**.

## API Changes
**First way.**
Change **IsLoading** to **bindable property**, so in method **OnLoadingCompleted** set **IsLoading = false** when image loaded.

**Other way**
Add **event Loaded** to ImageSource, so in method **OnLoadingComleted** invoke this event.

## Intended Use Case
In my custom control I will have the ability to hear IsLoading property changing or event Loaded raised. By this way I will know when I can turn off loading animation.
Thanks.

**Comment by WayaFlyfeather** [comment]
According to [the docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.image.isloading?view=xamarin-forms#Xamarin_Forms_Image_IsLoading) IsLoading on Image should already be bindable? (Sorry if I misunderstood something…)

**Comment by IgorKravchenko10** [comment]
> According to [the docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.image.isloading?view=xamarin-forms#Xamarin_Forms_Image_IsLoading) IsLoading on Image should already be bindable? (Sorry if I misunderstood something…)

Sorry. It is my fault. I didn't saw this. So my proposal is redundant.
Thanks for response.
