### ISSUE TITLE
[Bug] HotReload doesn't reload pages with RelativeLayout 

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#8351]
### Description
HotReload doesn't reload pages with RelativeLayout.

(Possibly it's a related issue because my HR doesn't work with RelativeLayout as well https://github.com/AndreiMisiukevich/HotReload/issues/85)

### Steps to Reproduce

1. Enable HotReload
2. Add next xaml as the content of a content page
```xaml
...
            <RelativeLayout>
    <BoxView Color="Red" x:Name="redBox"
        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent,
            Property=Height,Factor=.15,Constant=0}"
        RelativeLayout.WidthConstraint="{ConstraintExpression
            Type=RelativeToParent,Property=Width,Factor=1,Constant=0}"
        RelativeLayout.HeightConstraint="{ConstraintExpression
            Type=RelativeToParent,Property=Height,Factor=.8,Constant=0}" />
    <BoxView Color="Blue"
        RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToView,
            ElementName=redBox,Property=Y,Factor=1,Constant=20}"
        RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToView,
            ElementName=redBox,Property=X,Factor=1,Constant=20}"
        RelativeLayout.WidthConstraint="{ConstraintExpression
            Type=RelativeToParent,Property=Width,Factor=.5,Constant=0}"
        RelativeLayout.HeightConstraint="{ConstraintExpression
            Type=RelativeToParent,Property=Height,Factor=.5,Constant=0}" />
</RelativeLayout>
...
```
3. Try to reload page

### Expected Behavior
Layout reloads correctly, content is visible

### Actual Behavior
Error during reloading and no content visible

### Basic Information

- Version with issue: None
- Last known good version: None
- IDE: VS For Mac
- Platform Target Frameworks
  - iOS: 13 xCode 11.0
- Nuget Packages: XF 4.2.0.*
- Affected Devices: Simulator

### Screenshots

<img src="https://media.giphy.com/media/QsTttXopYSJYAFerFb/giphy.gif" />

> VS bug [#1158394](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1158394)

**Comment by adammeaney** [comment]
Are there plans to address this at all? It seems rather odd that an entire layout is unsupported.
