### ISSUE TITLE
[Enhancement] RefreshView for WebView

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8355]
## Summary
It's great that you have added RefreshView. But according to documenation:

![image](https://user-images.githubusercontent.com/17653648/68069868-8fa5a580-fd66-11e9-8a49-476bad8e3d26.png)

The child of the RefreshView must be ScrollView, CollectionView, or ListView. What I wanted to do is "pull to refresh" functionality for a WebView. When the user pulls down, the WebView reloads the current page.

## API Changes

Now WebView can be a child of the RefreshView

```
<RefreshView IsRefreshing="{Binding IsRefreshing}"
             Command="{Binding RefreshCommand}">
   <WebView Source="https://github.com/xamarin/Xamarin.Forms"/>
</RefreshView>
```

**Comment by jsuarezruiz** [comment]
RefreshView supports WebView refresh. Could you try it with the latest Xamarin.Forms versions?
![refresview-webview](https://user-images.githubusercontent.com/6755973/76859738-2aa4a500-685a-11ea-9bff-09ca9c3765f9.gif)

**Comment by ManuAnalys** [comment]
Hello,
Any news about that ? I tryed with Xamarin 4.5 SR2 and 4.6 Pre 2 but it doesn't work.
We would like to do exactly the same, is there any workaround?

Tahnk you for your help

**Comment by Mikilll94** [comment]
@jsuarezruiz 
I confirm that RefreshView supports WebView refresh. I was testing on XF 4.5 SR3

@ManuAnalys 
Here is the sample project. For me, it is working:

[WebViewRefreshTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4434052/WebViewRefreshTest.zip)

**Comment by ManuAnalys** [comment]
Hello @Mikilll94,
Thank you for your help. It works with XF 4.5 SR3.

One more question : In our webview we have a Devexpress datagrid component with a vertical scrollbar. Do you have any idea to prevent pullToRefresh effect when user is trying do scroll in the datagrid ? Is there any solution ?

Thank you for your help.
