### ISSUE TITLE
[Bug] Some Font Icons are not rendering

### ISSUE THREAD

**Issue by AwsomeCode** [xamarin/Xamarin.Forms#8358]
### Description
I have added Material Font Icons to my project as per below link by @jamesmontemagno 
https://montemagno.com/using-font-icons-in-xamarin-forms-goodbye-images-hello-fonts/
To access these fonts I have create public static class which have code like below.

`
public const string Account = "\uf004";
`
`
public const string CardsDiamondOutline = "\u000f003f";
`

The one without starting string of "\u00f" is working fine
`
public const string Account = "\uf004";
`
![image](https://user-images.githubusercontent.com/11809653/68081918-93572c00-fe3b-11e9-9b95-cfd34c976a87.png)

The one with starting string "\u00f" having issue
`
public const string CardsDiamondOutline = "\u000f003f";
`
![image](https://user-images.githubusercontent.com/11809653/68081947-12e4fb00-fe3c-11e9-9d6c-d7b81cd022f6.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/11809653/68081965-622b2b80-fe3c-11e9-9e78-fe99870eb4ea.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/11809653/68081947-12e4fb00-fe3c-11e9-9d6c-d7b81cd022f6.png)

### Basic Information

- Version with issue: 4.2
- Last known good version:
- IDE: VS 16.3.7
- Platform Target Frameworks: 
  - iOS:  not tested on iOS
  - Android: 9.0
  - UWP:  1903

**Comment by WayaFlyfeather** [comment]
This is not due to Xamarin Forms, it is C# beahviour. If you need to escape a unicode surrogate use **\U** (uppercase u). See also [the c# language specification](https://msdn.microsoft.com/en-us/data/aa664669%28v=vs.85%29?f=255&MSPPError=-2147217396).

**Comment by hartez** [comment]
@WayaFlyfeather is correct, the code generation tool isn't handling the surrogate pairs correctly. 

If you're using Visual Studio, a quick fix is to run a Search and Replace on your generated static icon class; just turn on the Regular Expressions option and search for
`"\\u([0-9a-fA-F]{8})"`
and replace with
`"\\U$1"`

**Comment by AwsomeCode** [comment]
@WayaFlyfeather @hartez Thanks it’s working
