### ISSUE TITLE
[Bug] [Android] Graphical artifact when scrolling in CollectionView

### ISSUE THREAD

**Issue by kimbirkelund** [xamarin/Xamarin.Forms#8361]
### Description

I have a CollectionView with a bunch of items and when an item in scrolled into view, small graphical artifacts appear, that fade out after a second or so. It seems they only appear when the item is reused, or at least have been sufficiently out of view.

### Steps to Reproduce

Label in CollectionView in CollectionView:

```
 <CollectionView>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <CollectionView
                HeightRequest="16"
                SelectionMode="None"
                VerticalOptions="Start">
                <CollectionView.ItemsLayout>
                    <LinearItemsLayout ItemSpacing="5" Orientation="Horizontal" />
                </CollectionView.ItemsLayout>

                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Label
                            HorizontalTextAlignment="Center"
                            Text="{Binding .}"
                            VerticalTextAlignment="Center" />
                    </DataTemplate>
                </CollectionView.ItemTemplate>

                <CollectionView.ItemsSource>
                    <x:Array Type="{x:Type x:String}">
                        <x:String>foo</x:String>
                        <x:String>bar</x:String>
                        <x:String>baz</x:String>
                    </x:Array>
                </CollectionView.ItemsSource>
            </CollectionView>
        </DataTemplate>
    </CollectionView.ItemTemplate>

    <CollectionView.ItemsSource>
        <x:Array Type="{x:Type x:String}">
            <x:String>enough</x:String>
            <x:String>items</x:String>
            <x:String>to</x:String>
            <x:String>scroll</x:String>
        </x:Array>
    </CollectionView.ItemsSource>
</CollectionView>
```

### Basic Information

- Version with issue:
- Last known good version: latest 4.2 (I think)
- Platform Target Frameworks: 
  - Android: 9 .0
- Android Support Library Version: 28.0.0.3

### Screenshots

Look at the yellow tag being scrolled in. The little gray box that fades out, is not part of the design, and nothing in my markup should be able to generate something like that.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/pswVZHy9Xl8/0.jpg)](https://www.youtube.com/watch?v=pswVZHy9Xl8)

### Reproduction project

[App7.zip](https://github.com/xamarin/Xamarin.Forms/files/3803153/App7.zip)

(edit: Added proper reproduction steps and project)

**Comment by kimbirkelund** [comment]
I've been able to narrow it down. Simply having a `Label` with a `HeightRequest` directly or inside something that has a `HeightRequest` appears to trigger the issue.

**Comment by jsuarezruiz** [comment]
Seems to be related with https://github.com/xamarin/Xamarin.Forms/issues/8364

**Comment by Tum4ik** [comment]
I have the same problem.

**Comment by carlosernestolopez** [comment]
Pretty sure this affects the scrolling speed at least in collectionViews

**Comment by TopSkillDeveloper** [comment]
the error is still present. 4.4-sr2

**Comment by Aleksey7151** [comment]
It happens not only when scrolling in Collection view, but in simple scrollview when you are making some animations with UI elements, that are placed in scrollview.

**Comment by IlyaLehchylin** [comment]
Looks like the issue is in the `ScrollView`.

Changed the line in my source code from:

`Content = new ScrollView { Content = mainStackLayout };`

to:

`Content = mainStackLayout;`

and the flickering has gone.

The similar issue: #7281

**Comment by acaliaro** [comment]
Hi @hartez. There are some news about this problem? Thanks. Alessandro
