### ISSUE TITLE
[Enhancement] Add different input types for prompt

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#8363]
## Summary
We have now implemented a XamForms [native prompt](https://github.com/xamarin/Xamarin.Forms/issues/6713), and the ability to set the [prefilled value](https://github.com/xamarin/Xamarin.Forms/issues/8346), meanwhile some people have asked for [different input types](https://github.com/xamarin/Xamarin.Forms/pull/6714#issuecomment-544546925). I.e. password, but we can think of more like numeric or dates, etc. 

Since an issue wasn't opened for it yet, I'm opening it to track it properly.

## API Changes

It probably makes sense to introduce an enum to be able to facilitate more different input types. Note that I'm just making up a list now as I go. It would probably be best to implement different input types one by one in different PRs to validate their use first.

```
public enum PromptInputType
{
    Text,
    Password,
    Numeric,
    Date,
    Time
   // etc.
}
```

Then we should pass that to the `Page.DisplayPromptAsync` that is available today.

`public Task<string> DisplayPromptAsync(string title, string message, PromptInputType inputType, string accept = "OK", string cancel = "Cancel", string placeholder = null, int maxLength = -1, Keyboard keyboard = default(Keyboard), string initialValue = "")`

Notice that I added the `PromptInputType inputType,` in there.

Now in the implemented platforms we need to implement the actual representations of these input types.

## Intended Use Case
Have more specific prompts to the type of data that should be entered

**Comment by adrianknight89** [comment]
@jfversluis You already deprecated `DisplayPromptAsync` once to make room for `initialValue`. Will you have to deprecate this again for the input types? Also, we're already passing a keyboard type. Input types and keyboards should play well together.

Another thought: maybe providing `IsPassword` is enough while keyboard types dictate text types (e.g. numeric, date, email, etc.). This would be similar to `Entry`.

**Comment by jfversluis** [comment]
It's not ideal, certainly. Also, we might not have to deprecate this new one again if we choose to add just an overload with the input type as a new one next to the existing one. But that it yet to be decided.

That might not actually be such a bad idea. `Keyboard` seems to have all the thing on board that you might probably want except for password.

The only thing I'm thinking of then is: isn't that confusing? Then it's not very consistent. You set ALL the input types through the keyboard, but the password has to be set separately. Arguably password isn't an input type but more of a visual thing to mask your input.

**Comment by adrianknight89** [comment]
Correct. It's more of a visual mask than an input type. I'd follow the convention used for `Entry`. We could use both `IsPassword` and `Keyboard` with it. https://docs.microsoft.com/en-us/dotnet/api/Xamarin.Forms.Entry?view=xamarin-forms

**Comment by bmacombe** [comment]
Keep in mind that the Keyboard type doesn't mean much on most UWP devices unless they are being used in tablet mode.  So setting Keyboard to numeric on UWP won't typically give the user any indication it's supposed to be numbers only and it will still allow entry on non-numeric chars.

Given that just adding an IsPassword might do it.  If the use case requires more detailed validation like, date, e-mail, uri, etc that's probably best left to the developer to implement their own popup.

Another thought would be pass a validation delegate in the PromptArguments to be used to check the entered text and display an error prompt and prevent the "ok" action if an error is present.

**Comment by tomeverin** [comment]
This would be useful especially as easy way to present system date/time selector

**Comment by djordje200179** [comment]
Any progress?

**Comment by Link-SD** [comment]
Is there any progress on this issue?

**Comment by jfversluis** [comment]
Wow @jfversluis! This is SUCH a good proposal, and explained so well. Love it! Unfortunately, this won't be able to go into Forms anymore. I am so so sorry. But no worries! Be sure to open this on the .NET MAUI repo so we can have another look at maybe implementing it there!

**Comment by Jerome2606** [comment]
Can we put this feature up in the roadmap, this should be a change life of facility
