### ISSUE TITLE
[Enhancement] Optional button and textbox trigger/validation for Prompt

### ISSUE THREAD

**Issue by sasivishnu** [xamarin/Xamarin.Forms#8365]
## Summary
Thanks for Display Prompt feature in 4.3 version. Providing way to customize or use native (Android/iOS) available alert options will make this feature more powerful. @jfversluis opened enhancement ticket for having different input type textbox #8363. Along with that, if we can add below features, it will be nice.

1. Add ability to have only one button (remove "Cancel")
2. Way to do validation on textbox.
3. Support for "Done" keypad press to auto trigger positive action to save extra click action (UX)

## API Changes

Making "Cancel" button optional can be done without making API changes. If `empty string or null` is passed for "Cancel" button parameter, then we can remove that button from display. 

For validation, may be we can take Action/Func delegate as one of the parameter and attach that as validation on click of positive button? 

## Intended Use Case
Ability to set input mandatory will help avoid need to display alert to user that textbox value is mandatory and again prompt. "Cancel" button option is not needed always especially in-cases where value must be entered in textbox.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
