### ISSUE TITLE
[Bug] UWP CollectionView Floating Row and Toolbar clipped

### ISSUE THREAD

**Issue by cmonto** [xamarin/Xamarin.Forms#8366]
### Description
Two problems found in UWP:

1. During navigation from a page containing CollectionView to another and then coming back to the original page, CollectionView layout gets messed up with a strange floating row above other rows.
2. Toolbar (Commandbar) is clipped at the bottom by certain pixels.

### Steps to Reproduce
Run the attached Solution to reproduce.
1. By default you are in the Browse Page which has a CollectionView.
2. While hovering your mouse over the hamburger menu you will find the bottom is clipped across the toolbar width.
2. Click Hamburger Menu and select About. The About Page will open.
3. Click Hamburger Menu and select Browse. The Browse Page will open.
4. You will find a floating row at the top of the CollectionView which stays as you scroll.

### Expected Behavior
1) CollectionView should show only the items bound as it's Rows.
2) Toolbar should show all buttons and contents without clipping at the bottom

### Actual Behavior
1) CollectionView shows a floating row at the top.
2) Toolbar shows a clipping between 4-8 pixels at the bottom

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: NA
- IDE: VS 2017
- Platform Target Frameworks: 
  - UWP:  17763
- Nuget Packages: Regular packages as in the Solution.
- Affected Devices: Windows Desktop

### Screenshots

![ss](https://user-images.githubusercontent.com/16226539/68119823-bcee8100-ff29-11e9-84f6-f238161b6aac.png)

### Reproduction Link

[CVTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3803914/CVTest.zip)

**Comment by hartez** [comment]
This looks like another VisualElementTracker issue.

**Comment by anpin** [comment]
I'm experiencing the same issue on iOS with XF 4.3.0.947036. Please see attached GIF. This is not present on Android. 
![issue](https://user-images.githubusercontent.com/6060545/68239029-2f329480-0002-11ea-86cb-3dff8aa3ffc9.gif)

**Comment by anpin** [comment]
Is this fixed on iOS as well or I need to open another issue?

**Comment by jfversluis** [comment]
It looks like the iOS one was fixed here #8189

**Comment by anpin** [comment]
> It looks like the iOS one was fixed here #8189

Thank you very much!
