### ISSUE TITLE
UWP Appx package should read dependencies from local dependencies folder. 

### ISSUE THREAD

**Issue by Harwinder0501** [xamarin/Xamarin.Forms#8373]
Description

UWP Appx package not able to publish through SCCM Tool. Appx package downloading dependencies from internet But as per requirement it should dependencies from local dependencies folder.

Expected Behavior

UWP Appx package should read dependencies from local dependencies folder. 

Actual Behavior

UWP Appx package downloading dependencies from internet even dependency foler available in local

Basic Information

current using Version: Xamarin 3.0 
IDE: Visual Studio 2019
Platform Target Frameworks:
Windows 10 Fall Creators Update

**Comment by hartez** [comment]
@Harwinder0501 Have you tried this with a non-Xamarin.Forms UWP app? I suspect this is a UWP issue, and not a Xamarin.Forms one. 

You may have better luck at https://social.msdn.microsoft.com/forums/windowsapps

**Comment by samhouts** [comment]
@Harwinder0501  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
