### ISSUE TITLE
[Bug] CollectionView "Clear" Selection

### ISSUE THREAD

**Issue by AbdelrhmanHamedTawfik** [xamarin/Xamarin.Forms#8374]
### Description
I made a command to navigate to different page when i select any item on my collection view , when i press back button or the back button on the app my selection is still highlighted which means that my selected item is not cleared which also means that i can not select the same item again to navigate to the required page again 
### Steps to Reproduce

1. Create collection view
2. Add selectionchnagedcommand binindg
3. Add selectionchnagedcommandparameter 
4. Select an item on the list
5. Go back to list after the navigation is done

### Expected Behavior
my selection is cleared
### Actual Behavior
my selection is still selected
### Basic Information

- Version with issue: 4.3.0.908675
- Last known good version: NA
- IDE: Visual Studio 2019 version 16.2.5
- Platform Target Frameworks: 
  - Android: Android 8.1 API 27
- Nuget Packages: Xamarin.Forms

### Reproduction Link

https://github.com/AbdelrhmanHamedTawfik/CollectionView.git

**Comment by ghaith100994** [comment]
this is not a bug you should clear your selected item OnAppearing if it is not null

**Comment by AbdelrhmanHamedTawfik** [comment]
thank you very much i thought it clears the selection automatically
