### ISSUE TITLE
[Bug] Problems with DataTrigger

### ISSUE THREAD

**Issue by asusralis** [xamarin/Xamarin.Forms#8376]
### Description

I'm trying to change the text of a label based on the value of a property on my viewmodel.

### Steps to Reproduce

```
            <Label FontSize="Medium" Text="{Binding SelectedCompanyPreview.Name}">
                <Label.Style>
                    <Style TargetType="Label">
                        <Style.Triggers>
                            <DataTrigger
                                Binding="{Binding SelectedCompanyPreview}"
                                TargetType="Label"
                                Value="{x:Null}">
                                <Setter Property="Text" Value="Tap to choose a company." />
                            </DataTrigger>
                        </Style.Triggers>
                    </Style>
                </Label.Style>
                <Label.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding SearchCompanyCommand}" />
                </Label.GestureRecognizers>
            </Label>
```

```
private CompanyPreview _selectedCompanyPreview;

public CompanyPreview SelectedCompanyPreview
        {
            get => _selectedCompanyPreview;
            set => SetProperty(ref _selectedCompanyPreview, value);
        }
```

### Expected Behavior

The text starts with "Tap to choose a company" and changes to the company's name.

### Actual Behavior

The text will never be set to "Tap to choose a company" text.

### Basic Information

I also had the Setter inside the style like you do in WPF, but that wasn't working either. SelectedComapnayPreview starts off being null, but the text never changes to "Tap to choose a company" - it is always set on the binding. Once a company is selected the binding updates accordingly to its name, so the binding itself isn't the problem (unless there's a problem with {x:Null}).

I've scoured the web and it seems a lot of people have problems with DataTriggers. They're usually recommended to create a converter, but I really don't want to create a converter for every instance I would otherwise need a DataTrigger.

I've tried this in the past - binding to and from two different Text values - but it has never worked for me before.

- Version with issue:

- Last known good version: Never
- IDE: VS 2019
- Xamarin Forms 4.3.0.947036
- Affected Devices: Emulator, Device

**Comment by StephaneDelcroix** [comment]
the Style.Setter has a lower precedency than the Text Binding, and is overriden. you don't need a converter in this case, use the `TargetNullValue` or `FallbackValue` of your binding
