### ISSUE TITLE
App constructor called on every waking up on Android

### ISSUE THREAD

**Issue by MJRomka** [xamarin/Xamarin.Forms#8380]
Steps to reproduce:
1. Set breakpoint at App class constructor;
2. Open app;
3. Suspend app;
4. Wake up app - the constructor will be called (app re-creates).

Is it by design on Android? I don't see such behavior on iOS.
Attached simple blank project created by Visual Studio for Mac. 
[androidwakeup.zip](https://github.com/xamarin/Xamarin.Forms/files/3808934/androidwakeup.zip)

**Comment by VladislavAntonyuk** [comment]
I suppose it is called from OnCreate method in MainActivity in Android application. Set breakpoint to find who calls constructor

**Comment by MJRomka** [comment]
This is true, but my question is why OnCreate is called on waking up? I don't remember such behavior with earlier versions of Xamarin.Forms.
(I searched it in web, but didn't find an answer)

**Comment by VladislavAntonyuk** [comment]
probably it is behavior of Android, which cleans background tasks. you can save activity state: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/activity-lifecycle/saving-state

**Comment by VladislavAntonyuk** [comment]
![image](https://user-images.githubusercontent.com/33021114/68221131-a3187100-fff1-11e9-94da-db0321321e0e.png)

**Comment by MJRomka** [comment]
Indeed, it is documented here: https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/activity-lifecycle/#back-vs-home
Thank you @VladislavAntonyuk
