### ISSUE TITLE
[Bug] ListView RefreshCommand ActivityIndicator does disappear on Android if CanExecute is changed to false

### ISSUE THREAD

**Issue by kwintAl** [xamarin/Xamarin.Forms#8384]
### Description

A Command is used in a ToolbarItem.Command and in a ListView.RefreshCommand. The Command starts a Bluetooth discovery and **is disabled (CanExecute returns false) while the discovery is running**.

In case the command is executed via **ToolbarItem** the ActivityIndicator **appears** on screen.
In case the command is executed via **ListView.RefreshCommand**(PullToRefresh) the ActivityIndicator **disappears** when CanExecute is changed to false.  

It looks like [ListView.RefreshAllowed](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ListView.cs#L484) is set to false

> 		void OnCommandCanExecuteChanged(object sender, EventArgs eventArgs)
> 		{
> 			RefreshAllowed = RefreshCommand.CanExecute(null);
> 		}

and this causes [SwipeRefreshLayout.Enabled = false](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs#L410)

> 		void UpdateIsSwipeToRefreshEnabled()
> 		{
> 			if (_refresh != null)
> 				_refresh.Enabled = Element.IsPullToRefreshEnabled && (Element as IListViewController).RefreshAllowed;
> 		}

From [Xamarin documentation](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/user-interface/listview/interactivity#pull-to-refresh):

> When defining a RefreshCommand, the CanExecute method of the command can be specified to enable or disable the command.

Is that the desired behavior? If yes, why do I need additional properties IsPullToRefreshEnabled and IsRefreshing?

I think CanExecute should be checked to avoid executing a Command twice but the ActivityIndicator should not disappear. For this logic we have the **IsRefreshing** property.

My current workaround:

```c#

using System.ComponentModel;
using Mono.Device.Discovery.Example.Android;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ExportRenderer(typeof(ListView), typeof(ListRenderer))]
namespace Mono.Device.Discovery.Example.Android
{
	public class ListRenderer : ListViewRenderer
	{
		protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
		{
			
			if (e.PropertyName == nameof(ListView.RefreshAllowed))
			{
				return;
			}
			base.OnElementPropertyChanged(sender, e);
		}
	}
}

```

### Steps to Reproduce

1. Create a Command
2. PullToRefresh
3. Command should return CanExecute false
4. ActivityIndicator disappears

### Expected Behavior
ActivityIndicator is visible

### Actual Behavior
ActivityIndicator is not visible

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Rider 2019.2.3
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0 API 28   
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms 4.3.0.947036
- Affected Devices:

**Comment by hartez** [comment]
Yep. If CanExecute changes while the refresh indicator is up, the indicator disappears. Seems like it should wait until the Command is finished.

[_8384 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3817075/_8384.Repro.zip)
