### ISSUE TITLE
[Bug] artifact glitch on button in Shell that has a StaticResource style 

### ISSUE THREAD

**Issue by sturlath** [xamarin/Xamarin.Forms#8385]
### Description
If I apply a StaticResource Style to a button (in StackLayout within a Grid) in a Shell application I get a **square artifact** in the top left corner of the button.

### Steps to Reproduce
Take a look at [my repo](https://github.com/sturlath/ShellProblem), run the app and look at the [NewItemPage.xaml](https://github.com/sturlath/ShellProblem/blob/master/App2/App2/Views/NewItemPage.xaml) I have there.

### Expected Behavior
No strange artifact in a top corner of a button.

### Actual Behavior
Strange square artifact in the top left corner of my button.

### Basic Information
    IDE: Visual Studio (16.3.7 and 16.4-prev3)
    Platform Target Frameworks:
        Android: Just tried this on Android
    Android Support Library Version:
    Affected Devices: 
       Galaxy S7
       Model number: SM-G930F
       Android 8.0.0
       Samsung Experience version 9.0

### Screenshots

If run on a device (at least mine) you will see this glitch as in this gif.
![ArtifactGlitch](https://user-images.githubusercontent.com/2386572/68223120-19ae7200-ffe4-11e9-8981-50028e6a9bfc.gif)

### Reproduction Link

 [My repo](https://github.com/sturlath/ShellProblem) containing the problem.

**Comment by hartez** [comment]
I can definitely see it when I run on a Galaxy Tab S3.

**Comment by jfversluis** [comment]
Seeing #8714 this is not specific to the `StaticResource`

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/2096
