### ISSUE TITLE
[Enhancement] Request location permissions from Android MapRenderer

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#8387]
## Summary

On iOS and UWP, when `Map.IsShowingUser` is set to true, the appropriate permissions are requested if not already granted. For Android, #7282 added a check to see if permissions are granted but just logs a warning if they are missing.

Things to consider when implementing permission requests on Android:
* Assumption that the MapRenderer Context is an Activity
* Priority of CoarseLocation vs FineLocation permission, or just request both?
* Ensure the permission(s) is/are in the manifest
* Does Maps simply make the request, or also need to get the response?

## API Changes
Xamarin.Forms.Maps.Android/MapRenderer.cs:
```
void SetUserVisible()
{
	GoogleMap map = NativeMap;
	if (map == null)
	{
		return;
	}

	if (Map.IsShowingUser)
	{
		var coarseLocationPermission = ContextCompat.CheckSelfPermission(Context, Manifest.Permission.AccessCoarseLocation);
		var fineLocationPermission = ContextCompat.CheckSelfPermission(Context, Manifest.Permission.AccessFineLocation);

		if (coarseLocationPermission == Permission.Granted || fineLocationPermission == Permission.Granted)
		{
			map.MyLocationEnabled = map.UiSettings.MyLocationButtonEnabled = true;
		}
		else
		{
			// NEW CODE
			if (Context is Activity activity)
			{
				activity.RequestPermissions(
					new []{ Manifest.Permission.AccessCoarseLocation , Manifest.Permission.AccessFineLocation },
					12345);
			}
		}
	}
	else
	{
		map.MyLocationEnabled = map.UiSettings.MyLocationButtonEnabled = false;
	}
}
```

Alternatively, easy mode would be to add a dependency on Xamarin.Essentials and use their Permissions code.

## Intended Use Case

When you're using Maps and want to display the user location, but are not using location permissions elsewhere in the app - brings Android in line with iOS and UWP behavior.

**Comment by CartBlanche** [comment]
@samhouts I'm still seeing this warning 19 months later.  Has it been considered yet, over a year later?

**Comment by CartBlanche** [comment]
@jfversluis so will this or has this been added to MAUI??
