### ISSUE TITLE
[Bug] Grid Height Not Resizing To Image Height

### ISSUE THREAD

**Issue by bwoogie** [xamarin/Xamarin.Forms#8390]
### Description
Grid height sticks to unscaled image height when image is scaled.

### Steps to Reproduce
1. Create a grid, background color set for observation.
2. Add two column definitions with width set to *
3. Add two images, one with column set to 1

### Expected Behavior
Grid should resize to content's height. Background should not be visible above or below the images

### Actual Behavior
Images are vertically centered in the grid, with background color filling the space the image would normally take if not scaled

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version:
- IDE: Visual Studio Community 2019 16.1.5
- Platform Target Frameworks: 
  - iOS:  untested
  - Android: API v28. doesn't seem to be Android specific.
  - UWP:  untested

### Screenshots
![image](https://user-images.githubusercontent.com/10790567/68244910-76f1f580-ffdb-11e9-893d-d3b43cf77591.png)

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="GridHeight.Views.Page1">
    <ContentPage.Content>
        <ScrollView>
            <StackLayout>
                <Grid BackgroundColor="CornflowerBlue">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>
                    <Image Source="testsquare" />
                    <Image Source="testsquare" Grid.Column="1" />
                </Grid>
            </StackLayout>
        </ScrollView>
    </ContentPage.Content>
</ContentPage>`

**Comment by hartez** [comment]
It's not a bug, it's just how the layout algorithm works. The initial layout does its best to fit everything in, then the Aspect is applied based on the final size of the container (the Grid cell, in this case).

If you'd like to have less "letterboxing", you can set a HeightRequest for your images to give the layout engine some help in sizing things.
