### ISSUE TITLE
[Bug] On iOS 12-13 a garbage (artifact) displayed at top of CollectionView in Shell when navigating back to a page

### ISSUE THREAD

**Issue by timmi4sa** [xamarin/Xamarin.Forms#8393]
### Steps to Reproduce

1. Download Xaminals sample (our in-house application exhibits the same behavior) from https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals,
2. Open the solution in a recent Visual Studio for Mac (on Mojave or Catalina),
3. Select simulator for iOS 12.4, or 13.2 (any iPhone device, but we tried both iPhone 8 v12.4, and 11 v13.2),
4. Run the application without Debugging,
5. In the simulator (or actual device) click the "burger" menu and select the "About" option,
6. While on the About page please use the "burger" menu and select the "Domestic" option in order to return back to the previous page,

### Expected Behavior
The "Domestic" page should display a list of cats.

### Actual Behavior
The "Domestic" page displays a strange "combination" of All collection view items displayed "above" the top row (1st row) of the view obscuring the actual first row's data.

### Basic Information

- Version with issue: 4.1.x, 4.2.x, 4.3.0.947036 of xamarin.forms
- Last known good version: None
- IDE: Visual Studio for Mac v8.3.7
- Platform Target Frameworks: Xamarin Forms - iOS
  - iOS:  12.4, 13.2
  - Android: not applicable (works as expected)
- Nuget Packages: fails in all of the 4.1.x, 4.2.x, 4.3.0.947036 of xamarin.forms
- Affected Devices: iOS smartphones

### Screenshots

<img width="545" alt="Screen Shot 2019-11-05 at 4 03 46 PM" src="https://user-images.githubusercontent.com/4761646/68256803-f2f13b00-ffe5-11e9-984e-3d7a03b81c11.png">

### Reproduction Link
https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/Xaminals

**Comment by timmi4sa** [comment]
@samhouts Hi Samantha, we are still having issues with Shell, this one is an absolute show stopper!

**Comment by timmi4sa** [comment]
If the Xamarin example is poorly written (and hence is our in-house code) then please advise how to rework it to eliminate this.

**Comment by hartez** [comment]
This was fixed by PR #8189.
