### ISSUE TITLE
Picker control fails after XF 4.3

### ISSUE THREAD

**Issue by papiermache** [xamarin/Xamarin.Forms#8395]
just installed XF 4.3. Picker control now doesn't work:
1. a 'virtual label' is inserted above it, forcing it out of position (first image).
2. data binding not working, the picker is empty.

Restoring back to 4.2 and the picker works once again (second image).

![picker-after-4 3](https://user-images.githubusercontent.com/5385881/68258833-f72d5080-0005-11ea-9d32-149e2add273a.png)

![picker-using-4 2](https://user-images.githubusercontent.com/5385881/68258900-38bdfb80-0006-11ea-8422-48943ecc0426.png)

**Comment by Gmotagi** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/8177

**Comment by EmilAlipiev** [comment]
more than 1 month such big breaking change and not fixed yet :( why you keep ignoring uwp?

**Comment by hartez** [comment]
The binding issue was fixed in a service release of 4.3; the margin issue was fixed in 4.4.
