### ISSUE TITLE
[Bug] Issue #8145 still unresolved despite being hastily closed

### ISSUE THREAD

**Issue by joeljaisi** [xamarin/Xamarin.Forms#8396]
### Description
refer issue #8145 
### Steps to Reproduce

1. refer issue #8145 

### Expected Behavior
refer issue #8145 
### Actual Behavior
refer issue #8145 
### Basic Information
refer issue #8145

**Comment by hartez** [comment]
See https://github.com/xamarin/Xamarin.Forms/issues/8145#issuecomment-554804466

**Comment by joeljaisi** [comment]
I can confirm that the issue is now solved. Thanks.
