### ISSUE TITLE
[Enhancement] Allow everyone access to the WeakEventManager class

### ISSUE THREAD

**Issue by rwaldenfraedom** [xamarin/Xamarin.Forms#8405]
## Summary
I would like to use the WeakEventManager so that my event registrations don't hold on to object when they should have been removed.

## API Changes

change the class viability modifier from _**internal**_ to _**public**_ on the class Xamarin.Forms.WeakEventManager

e.g.

**internal** class Xamarin.Forms.WeakEventManager

to

**public** class Xamarin.Forms.WeakEventManager

## Intended Use Case
Allow object to be disposed if the only thing that still references then are event registrations

**Comment by brminnick** [comment]
@rwaldenfraedom I’ve implemented WeakEventManager in this library: https://github.com/brminnick/AsyncAwaitBestPractices#weakeventmanagert

This was inspired by Xamarin.Forms’ WeakEventManager, and I’ve expanded on it, adding support for `event Action`, `event Action<T>`, and `event Delegate`.

**Comment by rwaldenfraedom** [comment]
Thanks @brminnick for letting me know of your NuGet. At my company all third party libraries need to be reviewed and approved before been used. Having it as part of Xamarin would be preferable.

**Comment by brminnick** [comment]
@rwaldenfraedom The code is all open source and you’re welcome to copy/paste my implementation into your code base.

**Comment by Insire** [comment]
Any news on this? I'd like to rely on the official implementation, instead of copying pasting the code over.

**Comment by rwaldenfraedom** [comment]
YAY thanks @samhouts  @StephaneDelcroix
