### ISSUE TITLE
[Bug] CarouselView Java.Lang.IllegalStateException on Android in 4.4-pre1

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8417]
### Description

In 4.4-pre1 the app crashes on Android, when navigating backwards after displaying an empty view that's swapped out for data after 2 seconds (testing a loading simulation).

### Steps to Reproduce

1. Run the attached sample on Android.
2. Browse to the EmptyView string load simulation page.
3. Wait for the items to appear.
4. Hit the on screen back button.

### Expected Behavior

App returns to the menu page.

### Actual Behavior

App crashes with a `Java.Lang.IllegalStateException`.

![Screenshot 2019-11-07 at 14 55 39](https://user-images.githubusercontent.com/8092460/68399764-d0d6f480-016e-11ea-929b-63c2b6109b3f.png)

### Basic Information

- Version with issue: 4.4.0.936621-pre1
- Last known good version: N/A
- IDE: VSMac 8.3.7
- Platform Target Frameworks: 
  - Android: API 28

### Reproduction Link

[CarouselViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3820214/CarouselViewDemos.zip)

**Comment by tuncayalt** [comment]
Hi, is there a release time for this bug? I encountered it in v4.3.0.991211.
Thanks.

**Comment by samhouts** [comment]
closed by #8430

**Comment by samhouts** [comment]
@tuncayalt This is in the latest 4.4.0-prerelease. Thanks!
