### ISSUE TITLE
[Bug] ProgressBar should progress from right to left when the language of the device is an RTL language

### ISSUE THREAD

**Issue by effpath999** [xamarin/Xamarin.Forms#8419]
### Description
In Xamarin Forms, we can obtain a pretty decent RTL layout for users that have the language of their device set to an RTL language, thanks to `FlowDirection="{x:Static Device.FlowDirection}"` which is inherited from parent views. However, in the case of the ProgressBar this property is completely ignored, event if set on the ProgressBar itself, and the view always progress from left to right.
### Steps to Reproduce
1. Create a new Xamarin Forms project with the main page containing a ProgressBar.
2. Set the Progress property to .1.
3. Execute some code that increase the Progress property, e.g.:
 `await progressBar.ProgressTo (.8, 250, Easing.Linear);`
4. Run the app on a device with its language set to an RTL language, such as Hebrew or Arabic.

### Expected Behavior
When the `progressBar.ProgressTo` method is executed, the colored part of the progress bar should increase from right to left.
### Actual Behavior
When the `progressBar.ProgressTo` method is executed, the colored part of the progress bar increases from left to right.

### Basic Information
- Version with issue: Xamarin.Forms 4.2.0.910310
- Last known good version: unknown.

**Comment by hartez** [comment]
Seems to be working fine - here's a quick demo project that shows the ProgressBar with FlowDirection="RightToLeft" (on Android I also had to add `android:supportsRtl="true"` to the `application` tag in the manifest):

[_8419 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3822641/_8419.Repro.zip)

The bar loads from the right side on UWP, iOS, and Android. 

Is there a detail I might be missing?

**Comment by effpath999** [comment]
Hello @hartez , the solution you provided does work fine. However, I just tried to create a new Xamarin.Forms solution with VS 2019 version 16.3.7, with practically the same code, of course I also set `android:supportsRtl="true"` in the Android manifest, and it does not work!!! I'm running the two apps in the same Android emulator: your app works and mine doesn't. Same code, same packages. I cannot understand. As soon as possible I'm going to publish my non working solution, so if you or somebody else would like to take a look...

**Comment by effpath999** [comment]
Here is the repo: https://github.com/effpath999/ProgressBarRTLInXamarin

**Comment by hartez** [comment]
@effpath999 I think you need to move the "supportsRTL" attribute from "manifest" to "application". Does that help? (make sure to completely clean and rebuild)

**Comment by effpath999** [comment]
Wow! Finally! Thank you very much @hartez ! I never noticed the error because the vast majority of the interface worked reasonably well in RTL languages even without this fix!
