### ISSUE TITLE
[Bug] Error saving properties in UWP 

### ISSUE THREAD

**Issue by Boxer-Property** [xamarin/Xamarin.Forms#8420]
### Description
When saving properties in UWP `await Application.Current.SavePropertiesAsync();` an error is returned with Xamarin.Forms 4.3 ( any build ). THis does not exist with the last 4.2.0.910310

Error:
Element not found.

Element not found.

   at Windows.ApplicationModel.Core.CoreApplication.GetCurrentView()
   at Xamarin.Forms.Platform.UWP.Dispatcher..ctor()
   at Xamarin.Forms.Platform.UWP.DispatcherProvider.GetDispatcher(Object context)
   at Xamarin.Forms.DispatcherExtensions.GetDispatcher(BindableObject bindableObject)
   at Xamarin.Forms.Application.get_Dispatcher()
   at Xamarin.Forms.Application.<SavePropertiesAsync>d__68.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

### Steps to Reproduce

Only occurs on UWP projects
1.  Add Application.Current.Properties ( Occurs when saving a JSON Serialized object )
2. Save the properties as mentioned in the description
3. 

### Expected Behavior
The item should save without error

### Actual Behavior
Throws an exception shown above

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version:4.2.0.910310
- IDE:
- Platform Target Frameworks: 
  - iOS:   Works
  - Android: Works
  - UWP:  UAP,Version=10.0.17763.0
- Android Support Library Version: 
- Nuget Packages: Xamarin.Plugin. Connectivity, DeviceInfo, Iconize, Media
- Affected Devices:I'm Running Local Machine in VS 2019.

### Reproduction Link

I am working on getting a sample project to upload for an example.

**Comment by WayaFlyfeather** [comment]
I tried to recreate this in 4.3.0, but it apparently saved ok. I'm not sure I understand exactly how the property to be saved is constructed/saved in the bug, though. A sample would probably help a lot.

**Comment by Rod-Baseplan** [comment]
> I tried to recreate this in 4.3.0, but it apparently saved ok. I'm not sure I understand exactly how the property to be saved is constructed/saved in the bug, though. A sample would probably help a lot.

I think this is actually the following error:

https://github.com/xamarin/Xamarin.Forms/issues/8167

So try it form a background thread, you will get error.

**Comment by samhouts** [comment]
@Rod-Baseplan  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
