### ISSUE TITLE
[Bug] Shell.GoToAsync() Launches multiple copies of the same page

### ISSUE THREAD

**Issue by TheBaileyBrew** [xamarin/Xamarin.Forms#8423]
### Description
App adds multiple instances of route uri to Shell.Current.CurrentItem.Location when Shell.GoToAsync() is called from a page loaded via Shell.GoToAsync()

Route Hierarchy of the App
HOME
TAB ONE
  -- Sub Page One
     ---- Final Page
  -- Sub Page Two
  -- Sub Page Three
TAB TWO
  -- Sub Page Four
  -- Sub Page Five

### Steps to Reproduce

1. Create an app with App Shell defining 3 tabs in TabBar, all other pages should be defines with Routing.RegisterRoute("SubPageOne", typeof(SubPageOne));
2. From Main Page, Select TAB ONE
3. From TAB ONE, navigate to Sub Page One via Shell.GoToAsync();
4. From Sub Page One, navigate to Final Page via Shell.GoToAsync();
5. Press the back indicator in the NavBar to return to Sub Page One
6. From Sub Page One, navigate to Final Page again via Shell.GoToAsync();
7. Watch two pages load (forcing two back clicks to return)
8. Repeat steps 5 & 6, and each time an additional page will be loaded until you navigate all the way back to TAB ONE

### Expected Behavior
I would expect a single instance of the final route to be loaded and closed upon < back navigation

### Actual Behavior
Even after overriding BackButtonBehavior and trying to PopAsync(), page loads multiple times with each attempt to navigate to the page.

### Basic Information
When overriding BackButtonBehavior and using:
>> Debug.WriteLine("State: " + Shell.Current.CurrentState.Location);
this is the output based on my code structure
1st BACK -- State: //TabBar24/Tab17/TABONE/SubPageOne/FinalPage
2nd BACK -- State: //TabBar24/Tab17/TABONE/SubPageOne/FinalPage/FinalPage
3rd BACK -- State: //TabBar24/Tab17/TABONE/SubPageOne/FinalPage/FinalPage/FinalPage

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
https://www.youtube.com/watch?v=9Qki9l68R4U

**Comment by hartez** [comment]
@TheBaileyBrew Your video is marked private, so it's not giving us a lot to go on :)

Could you please post a minimal repro project, or at least the XAML for your Shell structure so we can reproduce this issue? Thanks.

**Comment by samhouts** [comment]
@TheBaileyBrew  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
