### ISSUE TITLE
[Bug] CollectionView slow to Renderer on iOS with a lot of variable cell heights

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8426]
### Description
CollectionView on iOS with a lot of variable sized cells takes much longer to render on iOS than on android

### Steps to Reproduce

1. run the included sample

### Expected Behavior
CollectionView should render immediately on iOS like it does on Android

### Actual Behavior
It takes a really long time to render on iOS

### Basic Information

- Version with issue: nightly
- IDE:
- Platform Target Frameworks:
  - iOS:  11.2.1

### Reproduction Link

[TemplateCV.zip](https://github.com/xamarin/Xamarin.Forms/files/3823265/TemplateCV.zip)

**Comment by vshapenko** [comment]
Hello! Is there any milestone available for this issue be fixed? Because it is really critical in real apps with large sets of data

**Comment by hartez** [comment]
This is fixed in 5.0.0.1931.
