### ISSUE TITLE
ios crash EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000000001a in Xamarin forms Application

### ISSUE THREAD

**Issue by Abdulbasha** [xamarin/Xamarin.Forms#8427]
Intermittently getting EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000000000001a which is causing app crash in IOS

- Version with issue: 4.1.0.555618
- Last known good version:-
- IDE: Visual Studio For Mac
- Platform Target Frameworks: 
  - iOS:  10.0

**Comment by hartez** [comment]
@Abdulbasha Is this happening in Release or Debug builds? Any indication of what your application is doing when this happens?

**Comment by Abdulbasha** [comment]
@hartez  sorry for late reply. The crash issue i am facing due to Grouped listview causing Memory leaks. When i play with Grouped Listview doing expand and Collapse and scrolling Up and Down, its keep increasing the Memory. 
 Here is the report for reference.
EXC_RESOURCE -> MyProject.iOS[983] exceeded mem limit: ActiveHard 1400 MB (fatal)

57813.239 memorystatus: killing_specific_process pid 983 [MyProject.iOS] (per-process-limit 10) - memorystatus_available_pages: 14110 

Process MyProject.iOS [983] killed by jetsam reason per-process-limit

**Comment by hartez** [comment]
@Abdulbasha Can you post your project so we can see how you are using the ListView and Grouping? That might give us a clue where our memory leak is. 

Or at least the markup?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
