### ISSUE TITLE
[Bug]  TableView is broken on master

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8442]
### Description
This PR broke table view

https://github.com/xamarin/Xamarin.Forms/pull/8100

### Steps to Reproduce

1. go to Bugzilla31333 and it will be blank

### Expected Behavior
it's should have a bunch of entries and editors on it

### Actual Behavior

it's empty

**Comment by PureWeen** [comment]
@Depechie  FYI

**Comment by Depechie** [comment]
Damn :/

**Comment by samhouts** [comment]
closed by #8453
