### ISSUE TITLE
[Bug] Shell.NavBarIsVisible="False" is not work

### ISSUE THREAD

**Issue by wa926talent** [xamarin/Xamarin.Forms#8444]
### Description
Shell.NavBarIsVisible="False" is not work
Xamarin.Forms 4.3.0.947036
Android 9.0
### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
@wa926talent How are you setting it? Can you post your XAML?

**Comment by GioviQ** [comment]
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             ...
             Shell.NavBarIsVisible="False"
             BackgroundColor="Black"
             Title="{Binding Title}">

not working on Samsung Galaxy S9 android 9 Xamarin.Forms 4.3.0.991211

Just created a project with Prism Blank App
