### ISSUE TITLE
[Bug][Android] CollectionView.EmptyView not displaying when IsGrouped="True"

### ISSUE THREAD

**Issue by albertoha94** [xamarin/Xamarin.Forms#8449]
### Steps to Reproduce

1. Create a `CollectionView` in XAML.
2. Set the `IsGrouped` property to true.
3. Set an EmptyView (Behaviour happens in both as a string or a view).
4. Test with or without data.

### Expected Behavior
When the list is empty, I should see the EmptyView in the screen.

### Actual Behavior
EmptyView is not displayed. The header appears with an empty list.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019 16.4 Preview 4.
- Platform Target Frameworks: 
  - iOS:  -
  - Android: 10.0
  - UWP: -
(I dont know if this happen in other platforms too.)

- Nuget Packages: Xamarin.Forms 4.3.0.947036

### Screenshots
This is how Page1 looks normally.
![original](https://user-images.githubusercontent.com/14353851/68535698-0d8c2280-030c-11ea-87c1-e8fe74a2723f.jpg)

Once I commented the data retrieve code, the header remained and the emptyview is nowhere to be seen.
![comment](https://user-images.githubusercontent.com/14353851/68535699-0f55e600-030c-11ea-8c9e-5f1e42ee57f8.jpg)

### Reproduction Link

Link to the forum where issue was found:
https://forums.xamarin.com/discussion/comment/394567

Project to use:
[TestDemo.zip](https://github.com/xamarin/Xamarin.Forms/files/3827781/TestDemo.zip)

**Comment by LeoJHarris** [comment]
I have a grouped collectionview, and I am experiencing same issue in latest XF there is a work around.

To get text to show regardless of IsGrouped I set EmptyView property on collectionview to empty string like this EmptyView="", then with the EmptyViewTemplate the text doesnt work if using a binding but works with hard coded text. This will fix the issue regardless of Grouped or not but I think this is a bug.

EmptyViewTemplate should not be dependant on EmptyView text i would have thought.

**Comment by shanranm** [comment]
Actually its drawing behind the header

**Comment by samhouts** [comment]
closed by #8415
