### ISSUE TITLE
[Bug] If I have more than three childs on Bottom into a Tabbed Page, only Active Page Text is visible

### ISSUE THREAD

**Issue by mkgitalia** [xamarin/Xamarin.Forms#8455]
### Description
I tried to show more than three page into a Tabbeb Page with android:TabbedPage.ToolbarPlacement="Bottom", but only Active page is visible on bottom

- Version with issue: 4.3.0.947036
- IDE: VS 201916.3.8
- Platform Target Frameworks: 
  - Android: 9.0

### Screenshots

![image](https://user-images.githubusercontent.com/3187597/68580264-4a742880-0476-11ea-84a1-42a1988a098f.png)

### Reproduction Link

[ProvaTabbed.zip](https://github.com/xamarin/Xamarin.Forms/files/3830868/ProvaTabbed.zip)

**Comment by MitchBomcanhao** [comment]
Isn't that the default behaviour?
read [https://montemagno.com/xamarin-forms-fully-customize-bottom-tabs-on-android-turn-off-shifting/ ](https://montemagno.com/xamarin-forms-fully-customize-bottom-tabs-on-android-turn-off-shifting/ )

**Comment by hartez** [comment]
Yes, this is the default behavior for Android. Your tabs are still there - tap on the spots where they should be and you'll see the tab change. If you add icons (set the `IconImageSource` property), the icons will show up even when the text is blank.
