### ISSUE TITLE
[Bug] Xamarin Forms iOS Button Click Event is not Firing when the keyboard is open

### ISSUE THREAD

**Issue by mikeparker104** [xamarin/Xamarin.Forms#8463]
### Description
When the iOS keyboard is displayed tapping on a Button control does not trigger the click event (or command).

### Steps to Reproduce

1. Create a new Xamarin.Forms project (with Android and iOS targets)
2. Add a Button and an Entry to the empty MainPage.xaml (ensure the Button will be close to the top so it is visible when the keyboard is presented)
3. Hook up the Button Click event in the code-behind then add a breakpoint
4. Run the app
5. Tap on the Entry to display the keyboard
6. Tap on the Button

### Expected Behavior
Keyboard is dismissed and the Button Click event (and Command) is triggered. Ideally, this behaviour would be configurable.

### Actual Behavior
Keyboard is dismissed, but the Button Click event (nor Command) is not triggered.

### Basic Information

- Version with issue: 4.3.0.947036
- Last known good version: ?
- IDE: Visual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  13.2
- Nuget Packages: Microsoft.AppCenter.Analytics, Microsoft.AppCenter.Crashes, Newtonsoft.Json, Xamarin.Essentials, Xamarin.Forms, Xamarin.IQKeyboardManager
- Affected Devices: All

### Further Detail (from community forum posts)

- [Xamarin Forms iOS Button Click Event is not Firing when the keyboard is open](https://forums.xamarin.com/discussion/comment/393455)
- [Xamarin Forms iOS Button Click Event is not firing when keyboard is open (XF 4.3.0)](https://forums.xamarin.com/discussion/172717/xamarin-forms-ios-button-click-event-is-not-firing-when-keyboard-is-open-xf-4-3-0)

**Comment by hartez** [comment]
@mikeparker104 This seems to be working just fine for me. I've attached my repro - is there a detail or step I'm missing? Tapping the button seems to fire the event and dismiss the keyboard.

[_8463 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3837118/_8463.Repro.zip)

**Comment by mikeparker104** [comment]
@hartez after further investigation, this appears to be related to the use of the IQKeyboardManager NuGet package and so not a Xamarin.Forms issue

**Comment by jameswestgate** [comment]
I believe this can also be caused when closing the keyboard causes the screen layout to change, moving the button away from where it was pressed and so a release (and therefore click) event is not fired. One solution is to use `Pressed` instead of `Clicked`
