### ISSUE TITLE
[Bug] ContentProperty for MarkupExtension treats x:Static as text

### ISSUE THREAD

**Issue by Dresel** [xamarin/Xamarin.Forms#8464]
### Description

I'm trying to implement the localization markup extension explained in the [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=windows#localizing-xaml).

I want to pass the identifier from a static resource:

```xml
<Label Text="{i18n:Translate {x:Static assets:Welcome.Text}}"></Label>
```

but this passes `{x:Static assets:Welcome.Text` as text - but it works if I specify Text explicitely:

```xml
<Label Text="{i18n:Translate Text={x:Static assets:Welcome.Text}}"></Label>
```

### Steps to Reproduce

1. Create a markup extension with ContentProperty
2. Try to pass a static value as default
3. Try to pass a static value explicitely

### Expected Behavior

The value from the static resource should be passed

### Actual Behavior

The markup string `{x:Static...` is passed

### Basic Information

- Version with issue: 4.3.0.947036

### Reproduction Link

[Repository](https://github.com/Dresel/MarkupExtension)

**Comment by akihikodaki** [comment]
This is duplicate of #6905.

**Comment by Dresel** [comment]
Right, wasn't able to find this via issue search.
