### ISSUE TITLE
[Bug] Label & Button TextProperty's CoerceValueDelegate not fired

### ISSUE THREAD

**Issue by Codentale** [xamarin/Xamarin.Forms#8466]
### Description
Use reflection to manually update/set the ```CoerceValue``` value of TextProperty, the delegate are not fired unless wrapped in BeginInvokeOnMainThread block
```c#
Label l = new Label();

BindableProperty.CoerceValueDelegate d = (s, a) => 
{
    string modified = "textY"; // simply modify the value if required
    return modified;
};
var property = Label.TextProperty;
var coerceValue = property.GetType().GetProperty("CoerceValue", BindingFlags.NonPublic | BindingFlags.Instance);
var oldDelegate = coerceValue?.GetValue(property) as BindableProperty.CoerceValueDelegate;
coerceValue?.SetValue(property, d);

l.Text = "1"; // Text property is set to textY thanks to CoerceValueDelegate!
```

```XAML
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Page1">
    <ContentPage.Content>
        <StackLayout>
            <Label Text="Welcome to Xamarin.Forms!"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
```
### Steps to Reproduce

1. set the delegate in App.OnStart
2. set MainPage to Page1

**working if**
1. wrap ```coerceValue?.SetValue(property, d);``` in BeginInvokeOnMainThread block
2. the label are updated correctly to "textY"

### Expected Behavior
the label in Page1 XAML "Welcome to Xamarin.Forms!" should changed to "textY"

### Actual Behavior
it remain "Welcome to Xamarin.Forms!"

### Basic Information

- Version with issue: 4.3.0.947036
- Platform Target Frameworks: 
  - iOS:  13.4.0.2

**Comment by hartez** [comment]
@Codentale This seems to work fine for me. I've attached my repro project - maybe I'm missing something?

[_8466 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3837030/_8466.Repro.zip)

Also - why would you want to do this?

**Comment by Codentale** [comment]
@hartez your repro work fine as well with me.

after some investigation, weird that if i include custom component from another project, then it will break all labels within the page. will further check on this finding for details.

> Also - why would you want to do this?  

I have lots old views that contains static label, and I want to change the text, it will take times to check through all views, so I try to create a lookup table and modify them on the fly when text are assigned to label.

**Comment by jfversluis** [comment]
@Codentale did you find anything about this?

If you did, could you please update here? If it's not relevant for you anymore (at this time) please feel free to close the issue. Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
