### ISSUE TITLE
[Bug] Source is not updating in ImageSource

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8468]
### Description
Image is not changed when changing "Source" in ImageSource

### Steps to Reproduce

1. Run the project
2. Click "home" icon
3. Nothing is happening. The "home" icon should change to "home_outline"

### Expected Behavior
The "home" icon should change to "home_outline"

### Actual Behavior
Nothing is happening

### Basic Information

- Version with issue: 4.2.0.709249
- IDE: Visual Studio 2019 16.3.8

### Reproduction Link

[App2.zip](https://github.com/xamarin/Xamarin.Forms/files/3836712/App2.zip)

**Comment by hartez** [comment]
Change 
`public class MainPageVM`
to
`public class MainPageVM : INotifyPropertyChanged`

**Comment by Mikilll94** [comment]
@hartez 
Thanks. Just a stupid mistake from my side... :)
