### ISSUE TITLE
[Tap Gesture and Custom Long Press Gesture do not work together on Android when used on an Image] 

### ISSUE THREAD

**Issue by Kikanye** [xamarin/Xamarin.Forms#8470]
### Description
I am trying to have an image which performs a command when **tapped** and a different command when it is **long pressed**. I am using a routing effect in my shared code and using platform specific code for iOS and for Android. My iOS code works, but for Android the code only works for the long press gesture . 

**Note that it works when I use an ImageButton instead of an Image.**

### Steps to Reproduce

1.  **XAML code:**
`                <Image x:Name="TapRight" Grid.Row="4" Grid.Column="2"  Source="right64" 
                   VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand"
                   IsEnabled="{Binding RightEnabled}"
                   Opacity="{Binding RightEnabled, Converter={StaticResource OpacityConverter}}"
                   effects:LongPressEffect.Command="{Binding LongPressGestureCommand}"
                   effects:LongPressEffect.CommandParameter="{x:Static common:NavType.Right}">
                <Image.GestureRecognizers>
                    <TapGestureRecognizer 
                        Command="{Binding TapGestureNavCommand}" 
                        NumberOfTapsRequired="1"
                        CommandParameter="{x:Static common:NavType.Right}"/>
                </Image.GestureRecognizers>
                <Image.Effects>
                        <effects:LongPressEffect></effects:LongPressEffect>
                </Image.Effects>
            </Image>`

2. **Code in Shared Project:**

```
using System.Windows.Input;
using Xamarin.Forms;

namespace MyApp.Effects
{

    public class LongPressEffect : RoutingEffect
    {
        public LongPressEffect() : base("Xamarin.LongPressEffect")
        {

        }

        public static readonly BindableProperty CommandProperty =
         BindableProperty.CreateAttached("Command",
             typeof(ICommand),
             typeof(LongPressEffect),
             (object)null,
             propertyChanged: OnCommandChanged);

        public static ICommand GetCommand(BindableObject view)
        {
            return (ICommand)view.GetValue(CommandProperty);
        }

        public static void SetCommand(BindableObject view, ICommand value)
        {
            view.SetValue(CommandProperty, value);
        }

        static void OnCommandChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var view = bindable as View;
            if (view == null)
            {
                return;
            }
            ICommand command = (ICommand)newValue;
            if (command != null)
            {
                view.SetValue(CommandProperty, command);
            }

        }

        public static readonly BindableProperty CommandParameterProperty =
            BindableProperty.CreateAttached("CommandParameter",
                typeof(object),
                typeof(LongPressEffect),
                (object)null,
                propertyChanged: OnCommandParameterChanged);

        public static object GetCommandParameter(BindableObject view)
        {
            return (object)view.GetValue(CommandParameterProperty);
        }

        public static void SetCommandParameter(BindableObject view, object value)
        {
            view.SetValue(CommandParameterProperty, value);
        }

        static void OnCommandParameterChanged(BindableObject bindable, object oldValue, object newValue)
        {
            var view = bindable as View;
            if (view == null)
            {
                return;
            }
            object commandParameter = (object)newValue;
            if (commandParameter != null)
            {
                view.SetValue(CommandParameterProperty, commandParameter);
            }
        }
    }
}
```

3.  **iOS code:**

```
using System;
using System.ComponentModel;
using MyApp.Effects;
using UIKit;
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly: ResolutionGroupName("Xamarin")]
[assembly:ExportEffect (typeof(MyApp.iOS.Effects.LongPressEffect), "LongPressEffect")]
namespace MyApp.iOS.Effects
{
    public class LongPressEffect : PlatformEffect
    {
        private readonly UILongPressGestureRecognizer _longPressGestureRecognizer;
        private bool _attached;
        public LongPressEffect()
        {
            _longPressGestureRecognizer = new UILongPressGestureRecognizer(HandleLongClick);
            _attached = false;

        }

        protected override void OnAttached()
        {
            if (!_attached)
            {
                Container.AddGestureRecognizer(_longPressGestureRecognizer);
                _attached = true;
            }
        }

        private void HandleLongClick()
        {
            if (_longPressGestureRecognizer.State == UIGestureRecognizerState.Ended)
                // Only execute when the press is ended.
            {
                var command = MyApp.Effects.LongPressEffect.GetCommand(Element);
                command?.Execute(MyApp.Effects.LongPressEffect.GetCommandParameter(Element));
            }
        }

        protected override void OnDetached()
        {
            if (_attached)
            {
                Container.RemoveGestureRecognizer(_longPressGestureRecognizer);
                _attached = false;
            }
        }

        protected override void OnElementPropertyChanged(PropertyChangedEventArgs args)
        {
            base.OnElementPropertyChanged(args);
        }
    }
}

```

4. **Android code:**

```
using System;
using System.ComponentModel;
using Xamarin.Forms;
using Xamarin.Forms.Platform.Android;

[assembly: ResolutionGroupName("Xamarin")]
[assembly: ExportEffect(typeof(MyApp.Droid.Effects.LongPressEffect), "LongPressEffect")]
namespace MyApp.Droid.Effects
{
    public class LongPressEffect: PlatformEffect
    {
        private bool _attached;
        public static void Initialize() { }
        public LongPressEffect()
        {
            _attached = false;

        }

        protected override void OnAttached()
        {
            Console.WriteLine("Invoking long click command...");
            //throw new NotImplementedException();
            if (!_attached) {
                if (Control != null)
                {
                    Control.LongClickable = true;
                    Control.LongClick += HandleLongClick;
                }
                _attached = true;
            }
        }

        private void HandleLongClick(object sender, Android.Views.View.LongClickEventArgs e) {
            Console.WriteLine("Invoking long click command...");
            var command = MyApp.Effects.LongPressEffect.GetCommand(Element);
            command?.Execute(MyApp.Effects.LongPressEffect.GetCommandParameter(Element));

        }

        protected override void OnDetached()
        {
            //throw new NotImplementedException();
            if (_attached) {
                if (Control != null) {
                    Control.LongClickable = true;
                    Control.LongClick -= HandleLongClick;
                }
                _attached = false;
            }
        }

        protected override void OnElementPropertyChanged(PropertyChangedEventArgs args)
        {
            base.OnElementPropertyChanged(args);
        }
    }
}

```

### Expected Behavior
The image should execute separate call separate commands when tapped and when long pressed.

### Actual Behavior
The image only responds to a long press gesture on Android, but both gestures work for iOS.

### Basic Information

- Version with issue: **Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)**
- IDE: **Visual Studio Community 2019 for Mac Version 8.3.1 (build 18)**
- Platform Target Frameworks: 
  - iOS:  **Xamarin.iOS**
  - Android: **Android 9.0**
- Affected Devices: **Android**

**Comment by KSemenenko** [comment]
Maybe will be solved in #7324

**Comment by PureWeen** [comment]
@Kikanye I would use a GestureListener instead of events here. When you use the event that's basically just adding a listener to the view which will intercept any additional gestures. This isn't really a Forms issues is more of an Android gesture orchestration thing

you can check our our LongPressGesture here that we use ViewCells

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs#L274

Gesture Listeners are nice because you just tell it what kind of touch is happening and it will interpret the data. When you use the events on the views themselves then sometimes they will swallow up what's happening and not let other gestures play along.

**Comment by Licantrop0** [comment]
@Kikanye did you find any workaround for this? I'm in the same boat with the items in a CollectionView the tap to select doesn't work if I add the LongPressEffect (and I can't use a swipeview because the layout has multiple columns).

**Comment by Kikanye** [comment]
@Licantrop0 I posted my work around [here](https://stackoverflow.com/questions/58698063/xamarin-android-tap-gesture-and-long-press-gesture-not-working-together/59199651#59199651). Hopefully that helps you some way.

**Comment by Licantrop0** [comment]
Thank you, I will use an imagebutton as well as workaround until the PR from @KSemenenko gets merged :)

**Comment by Kikanye** [comment]
> https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs#L274

This seems like a lot of work for something that is used quite frequently no?

**Comment by Kikanye** [comment]
> @Kikanye I would use a GestureListener instead of events here. When you use the event that's basically just adding a listener to the view which will intercept any additional gestures. This isn't really a Forms issues is more of an Android gesture orchestration thing
> 
> you can check our our LongPressGesture here that we use ViewCells
> 
> https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Cells/ViewCellRenderer.cs#L274
> 
> Gesture Listeners are nice because you just tell it what kind of touch is happening and it will interpret the data. When you use the events on the views themselves then sometimes they will swallow up what's happening and not let other gestures play along.

@PureWeen This seems like a lot of work for something that is used quite frequently no?

**Comment by DodoAtana** [comment]
Good afternoon guys, I was looking for a "onImageLogPressEvent" and I got here.
First of all I want thank you for sharing your code, I really appreciate it !
 My problem is that when I invoke the command it doesn't "start" because is missing the CommandParamenter, but in my situation I don't really need it. 
What should I do to make the Command invoke ?

**Comment by Kikanye** [comment]
@DodoAtana I believe Commands need to be executed with a parameter, you can just pass it a null, if it doesn't need a parameter to execute.

**Comment by DodoAtana** [comment]
Thank you for the answer, I pass null and it semms ok.
But I don' understand why it doesn't invoke the Command I define in the ViewModel,
It's only writing on the Console "Invoking long click command..." without excuting the code that is in the ViewModel :(

**Comment by Kikanye** [comment]
> @Kikanye Thank you for the answer, I pass null as parameter and it seems ok.
> But I don' understand why it doesn't invoke the Command I define in the ViewModel,
> When I press the ImageButton it's only writing on the Console "Invoking long click command..." without excuting the code that is in the ViewModel :(

@DodoAtana A little hard to help with this without seeing some code. I would suggest review your code and ensure that it is similar to the above. Also be sure to have a `propertyChanged` function for the command.

**Comment by smalgin** [comment]
Hi. 
I extended LongPressEffect example from here https://alexdunn.org/2017/12/27/xamarin-tip-xamarin-forms-long-press-effect/
with SLCommand & SLParameter and got both short and long presses working for my Label.
(Android only - I don't have iOC to test)

SLCommand & parameter are copy-pasted from the Command & CommandParameter attached properties (no other changes except names)

```

     protected override void OnAttached()
        {
            //because an effect can be detached immediately after attached (happens in listview), only attach the handler one time.
            if (!_attached)
            {
                if (Control != null)
                {
                    Control.LongClickable = true;
                    Control.LongClick += Control_LongClick;
                    Control.Clickable = true;
                    Control.Click += Control_Click;
                }
                else
                {
                    Container.LongClickable = true;
                    Container.LongClick += Control_LongClick;
                    Container.Clickable = true;
                    Container.Click += Control_Click;
                }
                _attached = true;
            }
        }

        private void Control_Click(object sender, EventArgs e)
        {
            Console.WriteLine("Invoking short click command");
            var command = LongPressedEffect.GetSLCommand(Element);
            command?.Execute(LongPressedEffect.GetSLCommandParameter(Element));
        }
```
