### ISSUE TITLE
[Bug] System.ObjectDisposedException: Cannot access a disposed object [Xamarin.Android]

### ISSUE THREAD

**Issue by BalasubramaniSundaram** [xamarin/Xamarin.Forms#8472]
### Description
Hi Team,

Current we have encountered the random issue we are facing in Xamarin.Android from the Android.Widget.TextView, Android.Widget.ProgressBar, Android.Views.GestureDetector when navigating to the page or rotator view to showcase our custom control view but the issue didn't consistently produce in our side and also in the simple sample.

In our production code, on deep and hard analysis, we found that when we are going to access the Derived view of Base view (Android.Widget.ProgressBar) but in that base property "Progress" gets automatically disposed of from the framework so at a time "ObjectDisposedException" gets throwing. 

We have tried to sort out in a simple sample but it didn't get reproduced so we get blocked here to move a further step to resolve this issue in our end.  We have shared the details of the exception call stack in different scenarios based on that whether any step to resolve this issue. please help to resolve the issue

![image](https://user-images.githubusercontent.com/45868997/68698725-8f4bac80-05a7-11ea-9674-89321c98f24b.png)

![image](https://user-images.githubusercontent.com/45868997/68698685-7b07af80-05a7-11ea-89de-b80a834e5a91.png)

![image](https://user-images.githubusercontent.com/45868997/68698711-86f37180-05a7-11ea-8945-5e9d62c7911c.png)

We have tried some sample with a custom view that sample also we have attached in the incident please refer the sample to known the flow of action.

Sample 
[GridFragmentSample.zip](https://github.com/xamarin/xamarin-android/files/3837615/GridFragmentSample.zip)

[DataGridDemo.zip](https://github.com/xamarin/xamarin-android/files/3837618/DataGridDemo.zip)

**Comment by PureWeen** [comment]
@BalasubramaniSundaram 

I'm wondering if this is related to this issue
https://github.com/xamarin/xamarin-android/issues/2049

Can you try the workaround outlined there to switch to a different GC implementation and see if that fixes for you?

**Comment by samhouts** [comment]
@BalasubramaniSundaram  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by gresolio** [comment]
Unfortunately, in very rare cases I am facing a similar issue on Android:
```
**System.ObjectDisposedException:** 'Cannot access a disposed object.
Object name: 'Android.Widget.ProgressBar'.'
```
It is very difficult to catch the reason for such rather mystical errors.
I hope I can create a simple sample so that the issue is consistently reproducible.
