### ISSUE TITLE
[Bug] CollectionView Snapping Offsets

### ISSUE THREAD

**Issue by veryhumble** [xamarin/Xamarin.Forms#8475]
### Description
I would like to customise the snapping behavior with an offset. Consider the following layout:

ListView
  Header
   CollectionView (horizontally scrollable)
  Items
   Some List Items

Until now i was using my own abstraction for a CollectionView based on RecyclerView and UICollectionView, but it does not support accessibility features like screenreader properly. So i am migrating my 3y old implementation to the built in CollectionView for features and easier maintenance.

### Expected Behavior
The issue I have is that in my layout i want the items in the CollectionView to snap with respect to the layout design like in the following screenshot.
![collectionview_before](https://user-images.githubusercontent.com/13156014/68753866-fc8e2a80-0605-11ea-8675-897dc9aa0362.png)

I was able to achieve this by setting `ContentInset` on the UICollectionView and `SetPadding` on the RecyclerView.

### Actual Behavior
Currently using the Xamarin.Forms CollectionView with ```  <LinearItemsLayout Orientation="Horizontal"
                             SnapPointsType="Mandatory"
                             SnapPointsAlignment="Start"
                             ItemSpacing="5" />``` produces the following result on scrolling. Which is not as intended in the design.

![collectionview_after](https://user-images.githubusercontent.com/13156014/68754020-41b25c80-0606-11ea-965e-e058a6638626.png)

### Basic Information

- Version with issue: 4.3.0.947036
- IDE: VisualStudio Mac
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 8.1

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
