### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: JNI CallStaticObjectMethodA called with pending exception java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Harwinder0501** [xamarin/Xamarin.Forms#8476]
Out Of Memory Exception occurring while navigating from one page to another.  

- Version with issue: 3.4.0.1008975
- IDE: Visual Studio 8.1
- Platform Target Frameworks: 
  - Android: SDK 8.1 API LEVEL 27
- Android Support Library Version: `
- Affected Devices: AMAZON 8(8th Generation) (API Level 25)

**Comment by hartez** [comment]
@Harwinder0501 We're going to need a little more context.

Are you seeing this error consistently? If so, can you post a repro project, or share the code/markup for the pages you're seeing this problem on? 

Have you tried updating to a later version of Forms to see if this error still occurs? If not, why not (is there some reason you need to stay on version 3.4)?

Are you seeing this only on real devices? By "AMAZON 8", I assume you mean an Amazon Fire HD 8; can you give us a more specific model number (there are 3 (maybe 4) models that are called "Fire HD 8").

**Comment by samhouts** [comment]
@Harwinder0501  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
