### ISSUE TITLE
[Bug] Force the orientation of page irrespective of device orientation 

### ISSUE THREAD

**Issue by jhaprasun** [xamarin/Xamarin.Forms#8478]
### Description
 I forced the page to display in portrait mode only.  It works great when I opened the app in portrait mode and the page is not rotating in landscape mode even though I rotated the device in landscape. But when keeping the device in landscape mode and now if I opened the app, the page is displaying in a landscape-- this is not correct on account of forced the page to open only in portrait mode.
### Steps to Reproduce
1. Forced the Xamarin.Forms page to display in portrait only.
2. Keep the device in portrait mode- open the app, the page is displaying in portrait mode only.  
This is correct. Now if you rotate the device in landscape, the page is not rotating in landscape and this is expected behavior.
3. Keeping the device in landscape mode- open the app, the same page is displaying in landscape mode. Which is not correct. Again if I rotate the device in portrait mode then the page is displaying in portrait mode but not possible to get this page back to in landscape mode even though rotate the device in landscape mode.

How to reproduce using source code?
---------------------------------------

1) Create Standard Library blank solution for iOS and Android project using Visual Studio 2019 for Mac.

2) In MainPage.xaml.cs Add below function
       protected override void OnAppearing()
        {
            base.OnAppearing();
            if (Device.Idiom == TargetIdiom.Phone)
            {
                MessagingCenter.Send(this, "PreventLandScape");
            }
        }

3. Inside iOS project in AppDelegate.cs add below functions and also declare private variable like    this 

      private bool disableAllOrientation = false;

        public AppDelegate()
        {
            MessagingCenter.Subscribe<MainPage>(this, "PreventLandScape", (sender) =>
            {
                this.disableAllOrientation = true;
            });
        }

       public override UIInterfaceOrientationMask GetSupportedInterfaceOrientations(UIApplication     application, UIWindow forWindow)
        {
            if (this.disableAllOrientation == true)
            {
                return UIInterfaceOrientationMask.Portrait;
            }

            return UIInterfaceOrientationMask.All;
        }

### Expected Behavior
Keeping the device in landscape mode, open the app- the page should display in portrait mode only.

### Basic Information
Xamarin.Forms[4.3..947036]

- Version with issue:
- Last known good version:
- IDE: Visual Studio Community 2019 for Mac
- Platform Target Frameworks: 
  - iOS: 13.4.0.2
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iOS and Android

**Comment by hartez** [comment]
By the time OnAppearing is called, the orientation mask has already been checked. You need to call that method earlier in the application lifecycle.

Move 
```
if (Device.Idiom == TargetIdiom.Phone)
{
	MessagingCenter.Send(this, "PreventLandScape");
}
```

into the constructor for App:
```
public App()
{
	InitializeComponent();

	if (Device.Idiom == TargetIdiom.Phone)
	{
		MessagingCenter.Send(this, "PreventLandScape");
	}

	MainPage = new MainPage();
}
```

**Comment by jhaprasun** [comment]
Hi Hartez,
Thanks for your quick response!!
It works like a charm in iOS. In Android, If we keep the device in Landscape mode and open the app, for a while it is displaying in landscape mode and then it appears in Portrait mode. I observed the same behavior earlier and now too. 

Steps to Reproduce in Android:
1.
public App()
{
	InitializeComponent();

	if (Device.Idiom == TargetIdiom.Phone)
	{
		MessagingCenter.Send(this, "PreventLandScape");
	}

	MainPage = new MainPage();
}
2.  public MainActivity()
{
          MessagingCenter.Subscribe<App>(this, Constants.PreventLandScape, sender =>
            {
                this.RequestedOrientation = ScreenOrientation.Portrait;
            });
}

**Comment by hartez** [comment]
@jhaprasun You should open a separate issue for Android - since this one is already closed, folks might not see new comments on it.
