### ISSUE TITLE
[Bug] [Android] SearchBar SearchCommand not called on clearing

### ISSUE THREAD

**Issue by Basti82b** [xamarin/Xamarin.Forms#8480]
### Description

When I enter text into the SearchBar, the command is called successfully (with Enter), but if I delete the text, either manually or with the X, the command is not called.

I use the SearchBar to filter entries of a ListView via a ViewModel.

Furthermore, I can't see a SearchButton in the SearchBar. I have to hit Enter.

### Steps to Reproduce

Look at SearchBarDemos (see Reproduction Link).

### Expected Behavior

SearchCommand is called on clearing too.

### Actual Behavior

SearchCommand is only called with Text in SearchBar and only with Enter.

### Basic Information

- Version with issue: Xamarin.Forms 4.2.0.815419
- Platform Target Frameworks: 
  - Android: 9.0

### Reproduction Link

https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/SearchBarDemos

**Comment by hartez** [comment]
> When I enter text into the SearchBar, the command is called successfully (with Enter), but if I delete the text, either manually or with the X, the command is not called.

This is the normal behavior. If you want to update the results as you change the text (including when you clear it with X), take a look at the "Realtime" examples in that project. 

> Furthermore, I can't see a SearchButton in the SearchBar. I have to hit Enter.

Again, this is normal native SearchBar behavior on Android (and iOS).

**Comment by aperel66** [comment]
Hi all, in case someone still needs this.
I have struggled with this problem also, but created a hack that works very well. You simply have to fool the SearchBar into thinking that it actually has text in it. The solution is HairSpace character "/u200A"

So here is the Custom Renderer for Android - SearchBarEx

    /// <summary>
    /// To Allow Empty text searches that is disabled for some reason on Android
    /// </summary>
    public class SearchBarExRendererDroid : SearchBarRenderer
    {
        const string HairSpace = "\u200A";
        public SearchBarExRendererDroid(Context context) : base(context)
        { }

        protected override void OnElementChanged(ElementChangedEventArgs<SearchBar> e)
        {
            //
            // Android by definition does not allow empty text search. To circumvent that
            // if text is empty we replace it with a HairSpace character and then trim it if necessary
            base.OnElementChanged(e);
            if (e.OldElement == null && Control != null)
            {
                Control.QueryTextChange += (sender, args) =>
                {
                    if (string.IsNullOrEmpty(args.NewText) && Element is SearchBarEx sbx)
                    {
                        if (sbx.AllowEmptyTextSearch)
                            sbx.Text = HairSpace;
                    }
                };
                Control.QueryTextSubmit += (sender, args) =>
                {
                    if (Element is SearchBarEx sbx)
                    {
                        string text = args.Query == null || !args.Query.StartsWith(HairSpace) ? args.Query : args.Query.Replace(HairSpace, string.Empty);
                        if (!string.IsNullOrEmpty(text) || sbx.AllowEmptyTextSearch)
                        {
                            sbx.Unfocus();
                            sbx.SearchButtonPressed?.Invoke(sbx, args.Query);
                        }
                    }
                };
            }
        }
    }

**Comment by aperel66** [comment]
By the way. I also changed SearchButtonPressed event handler to Action<SearchBarEx, string>

**Comment by aperel66** [comment]
For those interested in IOS renderer for the above problem:
    public class SearchBarExRendererIos : SearchBarRenderer
    {
        const string HairSpace = "\u200A";
        protected override void OnElementChanged(ElementChangedEventArgs<SearchBar> e)
        {
            base.OnElementChanged(e);
            if (e.OldElement == null && Control != null)
            {
                Control.TextChanged += (sender, args) =>
                {
                    if (string.IsNullOrEmpty(Control.Text) && Element is SearchBarEx sbx)
                    {
                        if (sbx.AllowEmptyTextSearch)
                            Control.Text = HairSpace;
                    }
                };

                Control.SearchButtonClicked += (sender, args) =>
                {
                    if (Element is SearchBarEx sbx)
                    {
                        string text = Control.Text == null || !Control.Text.StartsWith(HairSpace) ? Control.Text : Control.Text.Replace(HairSpace, string.Empty);
                        if (!string.IsNullOrEmpty(Control.Text) || sbx.AllowEmptyTextSearch)
                        {
                            sbx.Unfocus();
                            sbx.SearchButtonPressed?.Invoke(sbx, Control.Text);
                        }
                    }
                };
            }
        }

**Comment by Tolimanoff** [comment]
here is my solution

file.xaml.cs
```c#
private void searchBar_TextChanged(object sender, TextChangedEventArgs e)
{
    if (string.IsNullOrWhiteSpace(((SearchBar)sender).Text)) {

        var model = (MyViewModel)BindingContext;
        if (model.LoadItemsCommand.CanExecute(null))
            model.LoadItemsCommand.Execute(null);
    }
}
``` 
XAML
```html
<SearchBar TextChanged="searchBar_TextChanged" ...
``` 
viewModel
```c#
public ICommand LoadItemsCommand { get; }
public MyViewModel()
{
  LoadItemsCommand = new Command(async () => await ExecuteLoadItemsCommand());
}
async Task ExecuteLoadItemsCommand(string searchText = null)
{
  // ...request
}

```
