### ISSUE TITLE
[Enhancement] UI test Calabash.Start() call should provide a completion notification.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms#8481]
## Summary
My application requires connectivity to a hardware device via BLE or USB. We use Xamarin UI tests. But since we check for the device at startup, we can commonly run into [this issue](https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts), where we've asked for permissions before Calabash is finished loading and it can't dismiss the permissions dialog.

Adding a delay is inelegant. The only solution is to make it too long, which will slow down all of my tests. I would like something in Xamarin's interface to Calabash to provide a notification that Calabash is loaded. That way, I can configure my builds to hold off on hardware communication until then.

## API Changes

I'm not particularly picky. Due to where it occurs, making `Start()` return a Task probably wouldn't help because I won't use `await` that early. But I could make do and create some notification based on the task's completion. If you want to make an event or even a flag for me to poll that'd still be nicer than "hope the delay is long enough".

## Intended Use Case

This feature would make it more convenient to develop applications that:

* Need a permission at startup, such as a navigation app that needs GPS.
* Want to use Xamarin UI tests.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
