### ISSUE TITLE
Xamarin Forms Shell title bar menu items cannot update dynamicly 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8483]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/815827/xamarin-forms-shell-title-bar-menu-items-cannot-up.html)._

---
Unable to get menu items on title bar  to update dynamicaly without changing from one page to another

---
#### Visual Studio Feedback System on 11/12/2019, 00:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
How are you attempting to update them? Are you doing this via code, or with a binding?

**Comment by Sonic3R** [comment]
> How are you attempting to update them? Are you doing this via code, or with a binding?

Via binding, as is in project provided.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jefffhaynes** [comment]
This appears to apply to normal TitleViews as well.  Essentially, if you put a dynamic collection (e.g. a bindable StackLayout, CollectionView, etc.) in a TitleView, the collection will not update.
