### ISSUE TITLE
Xamarin Forms Shell flyout menu cannot update dynamicly 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8484]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/815826/xamarin-forms-shell-flyout-menu-cannot-update-dyna.html)._

---
Unable to update Shell Flyout menu dynamicaly after shell has been created.

---
#### Visual Studio Feedback System on 11/12/2019, 00:10 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
Can you post some code demonstrating what you are trying to do? Are you trying to update it from code, or via a binding?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
