### ISSUE TITLE
Wrong indication of bad XAML

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8485]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/815751/wrong-indication-of-bad-xaml.html)._

---
Following XAML in a Xamarin Forms page will show a red underline underneath the TabbedPage.ToolbarPlacement setting, although it is correct xaml.

&lt;controls:CustomTabbedPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot;
                           xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot;
                           xmlns:local=&quot;clr-namespace:BirdAtlas&quot;
                           xmlns:views=&quot;clr-namespace:BirdAtlas.Views&quot;
                           xmlns:controls=&quot;clr-namespace:BirdAtlas.Controls;assembly=BirdAtlas&quot;
                           xmlns:android=&quot;clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core&quot;
                           x:Class=&quot;BirdAtlas.Views.MainPage&quot;
                           android:TabbedPage.ToolbarPlacement=&quot;Bottom&quot;
                           android:TabbedPage.IsSwipePagingEnabled=&quot;false&quot;&gt;

---
#### Visual Studio Feedback System on 11/11/2019, 11:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
intellisense issue was also reported in #3945

**Comment by hartez** [comment]
This is a duplicate of #4738; specifically, it's the problem described in  https://github.com/xamarin/Xamarin.Forms/issues/4738#issuecomment-466134697.

**Comment by jfversluis** [comment]
Going to assume this is resolved by now
