### ISSUE TITLE
Xamarin UWP Picker Internationalization

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8486]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/814125/xamarin-uwp-picker-internationalization.html)._

---
The Xamarin picker control fails to display a collection consisting of items in multiple language fonts which the Android and iOS pickers are successful in doing. The picker is blank with no selectable items. The picker is being used to allow the user to select their language to subsequently be used as a parameter to control translation of other application pages.

---
#### Marc W. George on 11/10/2019, 05:11 PM: 

In creating a sample project, it appears that the picker does support multiple language fonts in UWP. However, it doesn&#39;t explain why in the dev app the same page used across the platforms, that when shown in UWP the picker is blank.
#### Visual Studio Feedback System on 11/10/2019, 11:43 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Marc W. George on 11/11/2019, 03:15 AM: 

It appears that the picker has to be filled during the page class initialization in UWP. I have a working page now. Atleast a note should be added to documentation for other developers.

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
> It appears that the picker has to be filled during the page class initialization in UWP. I have a working page now. Atleast a note should be added to documentation for other developers.

This is a regression that was introduce in 4.3; your original code should have worked, but the issue described in #8177 prevented it. We have a fix (#8356), and it will be in the next service release.
