### ISSUE TITLE
Xamarin Forms Visual Studio Shell Template Highlight More Shell Features

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8487]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/813242/xamarin-forms-visual-studio-shell-template-highlig.html)._

---
The Shell Template doesn't show off all the features of Shell... such as routing, navigation, etc.

---
#### Visual Studio Feedback System on 11/10/2019, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
The next release of Visual Studio will include shell templates that demonstrate every feature I could possibly add into a template :-)
