### ISSUE TITLE
[bug]customized map marker callout can't be hidden on Android

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8489]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804207/bugcustomized-map-marker-callout-cant-be-hidden-on.html)._

---
On all 4.3 versions of Xamarin.Forms and Xamarin.Forms.Map, the map marker's callout can't be hidden when to customize pin based on your official example on Android devices. Version 4.2.0848062 and the previous versions don't have this issue. Please fix it ASAP

---
#### Visual Studio Feedback System on 11/4/2019, 00:26 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
maybe related to #8315

**Comment by hartez** [comment]
Are you talking about this sample? https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

I just ran that sample on a device after updating to 4.3.0.947036, and tapping outside of the callout dismisses it. Is there a step I'm missing?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
