### ISSUE TITLE
xamarin forms android api 19 entry keyboard

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8490]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804115/xamarin-forms-android-api-19-entry-keyboard.html)._

---
Xamarin.Forms.Android api 19 Entry keyboard don't show up when you tap the entry.

Steps:
1. Create a new Xamarin.Forms Shell App
2. Change minimum android version to api 19
3. Add an Entry in the xaml 
4. Build and run on an api 19 device/emulator
5. Tap the entry.......... nothing happens.
6. ..... rapid fire tap...... still nothing.

- update to latest nuget packages... Xamarin.Forms v4.3.0.947036
- repeat the above steps... still nothing.

p.s. I like what you guys are doing with Shell. Awesome Job!!
p.s. I would like to learn Azure Devops but the credit card requirement is hindering that. Maybe MS could remove it for the free account?? ... would remove the barrior for us Caribbean people who are interested in this tech. :) or not... you know whatever.

---
#### Visual Studio Feedback System on 11/3/2019, 10:13 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
I am trying to reproduce this problem, but no luck so far. My repro project is attached.

When I tap on the Entry, the software keyboard pops up and allows me to enter text, as expected. If I enable the hardware keyboard, the software keyboard does not pop up (as expected) and I can enter text with the physical keyboard. Is there a detail I'm missing?

[_8490 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3844078/_8490.Repro.zip)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
