### ISSUE TITLE
CollectionView is creating multiple copies of its cells and headers

### ISSUE THREAD

**Issue by Clancey** [xamarin/Xamarin.Forms#8493]
#8445 # Description
When I use a collection view inside a master detail. the collection view replicates its views every time I navigate to it.

### Steps to Reproduce

1. Clone: https://github.com/Clancey/gMusic.Forms/tree/CollectionView
2. Navigate between Songs and Albums
3.  When you go back to Songs, you will see duplicate data

### Screenshots

<img width="437" alt="Screen Shot 2019-11-13 at 1 38 55 PM" src="https://user-images.githubusercontent.com/256046/68810580-f6567900-061a-11ea-89c4-217213515df7.png">

**Comment by hartez** [comment]
This is fixed by #8189, should be in 4.4.0-pre2.
