### ISSUE TITLE
When iOS device is switched to dark mode, some controls do not update [Bug] 

### ISSUE THREAD

**Issue by jbachelor** [xamarin/Xamarin.Forms#8495]
### Description
When attempting to make a Xamarin.Forms app support iOS light vs. dark mode, I discovered that an Image control will update to its correct version of an image, but the image contained in either a Button or ImageButton control will not update itself until one completely quits and then re-launches the app.

### Steps to Reproduce
NOTE:  I have created a simple demo app to demonstrate the issue [here](https://github.com/jbachelor/DarkModeTest).

1. Create a new Xamarin.Forms app.
2. Add an image to the iOS project that should change depending on whether the phone is in light mode or dark mode using Assets.xcassets 'Light Theme' and 'Dark Theme' tabs.
3. Display the image in either a Button or ImageButton control.
4. Run the app.
5. Switch to the iOS settings app and switch from light to dark mode (or vice-versa).
6. Return to the app and observe that the image has not changed to reflect the change in theme.

### Expected Behavior
Image contained in either a Button or ImageButton should update to the correct version based on the phone's theme setting.

### Actual Behavior
Image does not update on Button or ImageButton controls.

### Basic Information

- Version with issue:
  - Mono 6.4.0.208
  - Xamarin.iOS 13.6.0.12
- Last known good version: n/a
- IDE: Visual Studio 2019 version 8.3.8
- Platform Target Frameworks: 
  - iOS:  13.x

- Nuget Packages:
  - Xamarin.Essentials 1.3.1
  - Xamarin.Forms 4.3.0.991211
- Affected Devices:
  - Physical devices and simulators running iOS 13.

### Screenshots

The app is shown below, launched while the phone is in light mode:

<img width="584" alt="AppInLightModeAtLaunch" src="https://user-images.githubusercontent.com/19045/68818768-dafb6600-063a-11ea-8910-37d1bd24510e.png">

This screenshot is after I switched to the Settings app and selected Dark Mode, then switched back to this demo app. Notice that only the Image control has updated its image. The Button and ImageButton will not change unless you quit & restart the app:

<img width="584" alt="SwitchedToDarkMode" src="https://user-images.githubusercontent.com/19045/68818767-dafb6600-063a-11ea-8e94-3243e4b6d2ef.png">

### Reproduction Link

https://github.com/jbachelor/DarkModeTest

**Comment by jbachelor** [comment]
> Hey, I also have this issue.
> 
> Is there any workaround for this?

@Mikilll94 For now, I've replaced my ImageButtons with an Image control, and I'm using a TapGestureRecognizer in order to hook up commands. You lose the button animation you would normally get for free by using a Button or ImageButton, but I think it's preferable to not being able to see your icons at all (eg, white icon on a white background, or black on black).

**Comment by Mikilll94** [comment]
Please remove "unverified"

**Comment by hartez** [comment]
> @jfversluis Please remove "unverified"

@Mikilll94 The "unverifed" label gets removed once someone on the team can verify that it's a real, reproducible bug with an accurate description that hasn't already been fixed in an upcoming version of Forms.

**Comment by Mikilll94** [comment]
Is there any workaround for this?

**Comment by MSiccDev** [comment]
I had the same problems after iOS 13 became available. I ended up using an Effect that sets the tint of the image button (see here https://msicc.net/xfeffects-xamarin-forms-effect-to-change-the-tint-color-of-imagebuttons-image-new-series/). Additionally, I am handling Dark/Night mode in a similar way described here: https://devblogs.microsoft.com/xamarin/modernizing-ios-apps-dark-mode-xamarin/ .

**Comment by Mikilll94** [comment]
Could someone explain, where in code dark mode is handled for **Image** control?

**Comment by MSiccDev** [comment]
> Could someone explain, where in code dark mode is handled for **Image** control?

you can use nearly the same code I used for ImageButton in an Effect for tinting a XF image (until XF fully supports dark theme out of the box):

```
                if (this.Control is UIImageView imageView)
                {
                    var templatedImg = imageView.Image.ImageWithRenderingMode(UIImageRenderingMode.AlwaysTemplate);

                    imageView.TintColor = ImageTintEffectExtensions.GetTintColor(this.Element).ToUIColor();
                    imageView.Image = templatedImg;
                }
```

**Comment by Mikilll94** [comment]
@MSiccDev 
No, no, no... Your workaround is awesome :) I was not asking about your workaround but about Xamarin.Forms repo

**Comment by MSiccDev** [comment]
@Mikilll94 try the ImageRenderer in Xamarin.Forms.Platform.iOS/Renderers/ImageRenderer.cs as a starting point 😉

**Comment by tomerdomshlak** [comment]
Same happens here.
