### ISSUE TITLE
[Bug] Animated ScrollToAsync doesn't work in Xamarin-Forms-WPF

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#8499]
### Description

Greetings,

We at Syncfusion have started implementation for providing support in Xamarin.Forms WPF platform for our controls. We have noticed that when scrolled to a particular offset position through **ScrollToAsync** method, it doesnt scroll from the last offset position. This issue occurs when using **animated** scrolling. 

[Ex:ScrollView.ScrollToAsync(0,400,true)]. 

If the current offset value is 977, then the scroll should happen from the 977 to 400 offset value. But it starts from 167 as you can see in the below screenshot.

<img width="960" alt="Screenshot (18)" src="https://user-images.githubusercontent.com/26808947/68829124-d2a03b00-06cd-11ea-9a7e-825992e9a198.png">

Can you please provide us with any solution or workaround to overcome this issue as soon as possible?

### Steps to Reproduce

1. Run the attached sample in WPF platform.
2. Scroll to the end.
3. Click the button.

### Expected Behavior

Note that the view jumps to 167 offset value [you can see in the output window] from which the scrolling happens to the specified position.

### Actual Behavior

Scrolling should begin from the current offset value which is 977 and should end at specified offset value[400].

### Basic Information

- Version with issue: Latest - 4.4.0.991210-pre2
- Last known good version: None
- Platform Target Frameworks: WPF

### Reproduction Link

[ScrollToAsyncIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3844763/ScrollToAsyncIssue.zip)

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
