### ISSUE TITLE
[Enhancement]Mini MVVM built into Xamarin.Forms (Extensions for navigations and DI)

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#8500]
## Summary
We have methods NavigateTo, Shell.Current.GoToAsync
But what if we add extensions for navigation between the ViewModel and Pages.
``` cs
NavigateTo<T>()
Shell.Current.GoToAsync<T>()
```
When #8220 will be ready we can solve the issue of creating objects and dependencies via DI in Startup.cs

It will also be possible to make some interface to indicate the relationship of View and ViewModel

```cs
public class MyPage : ContentPage, IViewModel<MyPageViewModel>
{
}

public class MySecondViewModel : INotifyPropertyChanged, IView<MyPageSecondPage>
{
}
```

In general, such a mini MVVM built into Xamarin.Forms
What do you think?

**Comment by levelfivecoder** [comment]
Yes, why can't xamarin forms have a mini mvvm setup. And inbuilt viewmodel navigation.

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
