### ISSUE TITLE
[Bug] Map in a ShellContent

### ISSUE THREAD

**Issue by EliseJoffre** [xamarin/Xamarin.Forms#8507]
### Description
When the map page disappears it's "flickering" on Android
### Steps to Reproduce

1. Create a ShellContent with 4 pages 
2. In a page include a Map
3. Go to the map page and navigate in the app

- Version with issue:
- Last known good version: 4.3.0.991211
- IDE: Visual Studio Mac

**Comment by hartez** [comment]
@EliseJoffre I'm trying to reproduce the issue, but I'm having trouble. My repro project is attached - when I navigate to the Map tab and then leave, I'm not seeing any flicker. I also added a map to the ItemDetailPage - no flicker when leaving that page, either. Is there a detail I'm missing?

[_8507 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3847600/_8507.Repro.zip)

**Comment by EliseJoffre** [comment]
Did you use a customMap ? 

Elise Joffre

**Comment by EliseJoffre** [comment]
This is the video of the bug. 



Elise Joffre

**Comment by hartez** [comment]
> This is the video of the bug.

@EliseJoffre There's nothing attached - did you mean to attach a video?

**Comment by EliseJoffre** [comment]
Yes, i attach the video again. The format of this video is  .mov 
Elise Joffre

**Comment by EliseJoffre** [comment]
I can send also a project with the bug if you prefer !

Elise Joffre

**Comment by hartez** [comment]
@EliseJoffre A project would be amazing!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by csp04** [comment]
Hey. Do we have a fix on this? I'm also experiencing this in Xamarin.Forms 4.8+.

**Comment by EliseJoffre** [comment]
It is not fixed at all, I continue to use the map while it is flickering ... Hoping that with MAUI it won't do it anymore ..
