### ISSUE TITLE
[Double bug] UWP CollectionView.Scrolled not raised & unhandled exception on exit

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#8508]
### Description
UWP CollectionView.Scrolled not raised & unhandled exception on exit

### Steps to Reproduce
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="UWPCollectionViewScrolled.MainPage">
    <CollectionView Scrolled="CollectionView_Scrolled" x:Name="collectionView">
        <CollectionView.ItemsLayout>
            <LinearItemsLayout Orientation="Vertical" ItemSpacing="0" />
        </CollectionView.ItemsLayout>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding}" HorizontalOptions="FillAndExpand"/>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    </CollectionView>
</ContentPage>
```
```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace UWPCollectionViewScrolled
{
    // Learn more about making custom code visible in the Xamarin.Forms previewer
    // by visiting https://aka.ms/xamarinforms-previewer
    [DesignTimeVisible(false)]
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
            collectionView.ItemsSource = Enumerable.Range(1, 100);
        }

        private void CollectionView_Scrolled(object sender, ItemsViewScrolledEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("CollectionView_Scrolled: {0}", e.CenterItemIndex);
            System.Diagnostics.Debugger.Break();
        }
    }
}
```
1. Debug application
2. Scroll up and down
3. Close application

### Expected Behavior
1. Scrolled event is raised and debugger stops at the event handler.
2. Application does not generate an unhandled exception on exit.

### Actual Behavior
1. Scrolled event is not raised.
2. Application generates an unhandled exception on exit.

Exception has no stack trace when scrolling is not performed and immediately is closed when collectionView is visible.
Exception has following stack trace when scrolling is performed before closing:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.Forms.Application.SavePropertiesAsync()
   at Xamarin.Forms.Platform.UWP.WindowsBasePage.OnApplicationSuspending(Object sender, SuspendingEventArgs e)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

### Basic Information

- Version with issue: 4.3
- Last known good version: N/A
- IDE: VS16.3.9
- Platform Target Frameworks: 
  - UWP:  17134
- Nuget Packages: Default packages from template
- Affected Devices: My PC

### Screenshots

![image](https://user-images.githubusercontent.com/19922066/68869549-4f660000-0734-11ea-8711-17186abb5818.png)

### Reproduction Link

[UWPCollectionViewScrolled.zip](https://github.com/xamarin/Xamarin.Forms/files/3847166/UWPCollectionViewScrolled.zip)

**Comment by jlf0dev** [comment]
I would also like to say that i'm getting this same error when wrapping a listview in a refreshview and trying to scroll it. I can make a new bug if needed. I'm not sure if #8549 will fix this issue since it seems to only fix CollectionView.

**Comment by cmpalmer66** [comment]
This is apparently still an issue. I'm not seeing the Scrolled event firing on UWP, but it works on iOS.
