### ISSUE TITLE
[Bug] Grid bug

### ISSUE THREAD

**Issue by moreirawebmaster** [xamarin/Xamarin.Forms#8512]
Xamarin.forms 4.3

**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

11-14 17:44:18.146 D/Mono    ( 8792): DllImport attempting to load: '/system/lib/liblog.so'.
11-14 17:44:18.156 D/Mono    ( 8792): DllImport loaded library '/system/lib/liblog.so'.
11-14 17:44:18.156 D/Mono    ( 8792): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
11-14 17:44:18.156 D/Mono    ( 8792): Searching for '__android_log_print'.
11-14 17:44:18.157 D/Mono    ( 8792): Probing '__android_log_print'.
11-14 17:44:18.157 D/Mono    ( 8792): Found as '__android_log_print'.
11-14 17:44:18.168 I/MonoDroid( 8792): UNHANDLED EXCEPTION:
11-14 17:44:18.178 I/MonoDroid( 8792): System.NullReferenceException: Object reference not set to an instance of an object.
11-14 17:44:18.178 I/MonoDroid( 8792):   at Xamarin.Forms.Grid.NumberOfUnsetColumnWidth (Xamarin.Forms.BindableObject child) [0x00014] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:616 
11-14 17:44:18.178 I/MonoDroid( 8792):   at Xamarin.Forms.Grid.MeasuredStarredColumns (System.Double widthConstraint, System.Double heightConstraint) [0x0007b] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:449 
11-14 17:44:18.178 I/MonoDroid( 8792):   at Xamarin.Forms.Grid.MeasureAndContractStarredColumns (System.Double width, System.Double height, System.Double totalStarsWidth) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:377 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Grid.MeasureGrid (System.Double width, System.Double height, System.Boolean requestSize) [0x0010e] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:511 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Grid.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x0002a] in D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:60 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:762 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x00053] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:644 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:132 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags) [0x00054] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:702 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.ScrollView.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height) [0x000e1] in D:\a\1\s\Xamarin.Forms.Core\ScrollView.cs:236 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Layout.UpdateChildrenLayout () [0x00158] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Layout.OnSizeAllocated (System.Double width, System.Double height) [0x0000f] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.VisualElement.SizeAllocated (System.Double width, System.Double height) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:784 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Xamarin.Forms.Layout.ResolveLayoutChanges () [0x0005c] in D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <8c07a09624c14764b43f6b946a5a1f23>:0 
11-14 17:44:18.179 I/MonoDroid( 8792):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <8c07a09624c14764b43f6b946a5a1f23>:0 
11-14 17:44:18.179 I/MonoDroid( 8792):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.51(intptr,intptr)
11-14 17:44:18.189 D/Mono    ( 8792): Loading reference 4 of /storage/emulated/0/Android/data/br.com.vitreo.app_vitreo/files/.__override__/Xamarin.Android.Crashlytics.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
11-14 17:44:18.190 D/Mono    ( 8792): Assembly Ref addref Xamarin.Android.Crashlytics[0xd00b6ee0] -> System[0xcd3a02c0]: 26
11-14 17:44:18.195 D/Mono    ( 8792): Loading reference 5 of /storage/emulated/0/Android/data/br.com.vitreo.app_vitreo/files/.__override__/Xamarin.Android.Crashlytics.dll asmctx DEFAULT, looking for System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
11-14 17:44:18.195 D/Mono    ( 8792): Assembly Ref addref Xamarin.Android.Crashlytics[0xd00b6ee0] -> System.Core[0xcd3a08c0]: 16
11-14 17:44:18.236 W/art     ( 8792): JNI RegisterNativeMethods: attempt to register 0 native methods for md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoException
11-14 17:44:18.236 W/art     ( 8792): JNI RegisterNativeMethods: attempt to register 0 native methods for md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper
11-14 17:44:18.439 I/System.out( 8792): (HTTPLog)-Static: isSBSettingEnabled false
11-14 17:44:18.439 I/System.out( 8792): (HTTPLog)-Static: isSBSettingEnabled false
11-14 17:44:19.321 I/CrashlyticsCore( 8792): Crashlytics report upload complete: 5DCDAE2E0148-0001-2258-36BB6E526544
11-14 17:44:19.481 E/UncaughtException( 8792): 
11-14 17:44:19.481 E/UncaughtException( 8792): md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object.
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Grid.NumberOfUnsetColumnWidth(Xamarin.Forms.BindableObject child)[0x00014](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:616)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Grid.MeasuredStarredColumns(System.Double widthConstraint, System.Double heightConstraint)[0x0007b](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:449)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Grid.MeasureAndContractStarredColumns(System.Double width, System.Double height, System.Double totalStarsWidth)[0x00000](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:377)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Grid.MeasureGrid(System.Double width, System.Double height, System.Boolean requestSize)[0x0010e](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:511)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Grid.OnSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x0002a](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:60)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.VisualElement.OnMeasure(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:762)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.VisualElement.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00053](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:644)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Layout.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:132)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.VisualElement.Measure(System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)[0x00054](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:702)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.ScrollView.LayoutChildren(System.Double x, System.Double y, System.Double width, System.Double height)[0x000e1](D:\a\1\s\Xamarin.Forms.Core\ScrollView.cs:236)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Layout.UpdateChildrenLayout()[0x00158](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Layout.OnSizeAllocated(System.Double width, System.Double height)[0x0000f](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.VisualElement.SizeAllocated(System.Double width, System.Double height)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:784)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Xamarin.Forms.Layout.ResolveLayoutChanges()[0x0005c](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Java.Lang.Thread+RunnableImplementor.Run()[0x00008](Java/Lang/ThreadRunnableImplementor0x00008.cs:1)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at Java.Lang.IRunnableInvoker.n_Run(System.IntPtr jnienv, System.IntPtr native__this)[0x00009](Java/Lang/IRunnableInvoker0x00009.cs:1)
11-14 17:44:19.481 E/UncaughtException( 8792): 	at   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.51(intptr,intptr).(unknown.cs:1)
11-14 17:44:19.809 I/FirebaseCrash( 8792): Sending crashes
11-14 17:44:19.812 I/System.out( 8792): (HTTPLog)-Static: isSBSettingEnabled false
11-14 17:44:19.812 I/System.out( 8792): (HTTPLog)-Static: isSBSettingEnabled false
11-14 17:44:20.310 I/FirebaseCrash( 8792): Response code: 200
11-14 17:44:20.311 E/FirebaseCrash( 8792): Unable to parse Json response string to get message: No value for crashes
11-14 17:44:20.311 I/FirebaseCrash( 8792): Report sent with crash report id: 
**Crashlytics.MonoExceptionHelper:** 'Loading...'

11-14 17:44:22.433 E/AppCenterCrashes( 8792): Unhandled Exception from source=AppDomain
11-14 17:44:22.433 E/AppCenterCrashes( 8792): Crashlytics.MonoExceptionHelper: Exception of type 'Crashlytics.MonoExceptionHelper' was thrown.
11-14 17:44:22.433 E/AppCenterCrashes( 8792):   --- End of managed Crashlytics.MonoExceptionHelper stack trace ---
11-14 17:44:22.433 E/AppCenterCrashes( 8792): md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object.
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Grid.NumberOfUnsetColumnWidth(Xamarin.Forms.BindableObject child)[0x00014](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:616)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Grid.MeasuredStarredColumns(System.Double widthConstraint, System.Double heightConstraint)[0x0007b](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:449)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Grid.MeasureAndContractStarredColumns(System.Double width, System.Double height, System.Double totalStarsWidth)[0x00000](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:377)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Grid.MeasureGrid(System.Double width, System.Double height, System.Boolean requestSize)[0x0010e](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:511)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Grid.OnSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x0002a](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:60)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.VisualElement.OnMeasure(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:762)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.VisualElement.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00053](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:644)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Layout.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:132)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.VisualElement.Measure(System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)[0x00054](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:702)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.ScrollView.LayoutChildren(System.Double x, System.Double y, System.Double width, System.Double height)[0x000e1](D:\a\1\s\Xamarin.Forms.Core\ScrollView.cs:236)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Layout.UpdateChildrenLayout()[0x00158](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Layout.OnSizeAllocated(System.Double width, System.Double height)[0x0000f](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.VisualElement.SizeAllocated(System.Double width, System.Double height)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:784)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Xamarin.Forms.Layout.ResolveLayoutChanges()[0x0005c](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Java.Lang.Thread+RunnableImplementor.Run()[0x00008](Java/Lang/ThreadRunnableImplementor0x00008.cs:1)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at Java.Lang.IRunnableInvoker.n_Run(System.IntPtr jnienv, System.IntPtr native__this)[0x00009](Java/Lang/IRunnableInvoker0x00009.cs:1)
11-14 17:44:22.433 E/AppCenterCrashes( 8792): 	at   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.51(intptr,intptr).(unknown.cs:1)
11-14 17:44:22.440 D/Mono    ( 8792): Loading reference 5 of /storage/emulated/0/Android/data/br.com.vitreo.app_vitreo/files/.__override__/Microsoft.AppCenter.Crashes.dll asmctx DEFAULT, looking for System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
11-14 17:44:22.440 D/Mono    ( 8792): Assembly Ref addref Microsoft.AppCenter.Crashes[0xd00b5200] -> System.Core[0xcd3a08c0]: 17
11-14 17:44:22.470 E/AndroidRuntime( 8792): FATAL EXCEPTION: main
11-14 17:44:22.470 E/AndroidRuntime( 8792): Process: br.com.vitreo.app_vitreo, PID: 8792
11-14 17:44:22.470 E/AndroidRuntime( 8792): md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object.
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Grid.NumberOfUnsetColumnWidth(Xamarin.Forms.BindableObject child)[0x00014](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:616)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Grid.MeasuredStarredColumns(System.Double widthConstraint, System.Double heightConstraint)[0x0007b](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:449)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Grid.MeasureAndContractStarredColumns(System.Double width, System.Double height, System.Double totalStarsWidth)[0x00000](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:377)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Grid.MeasureGrid(System.Double width, System.Double height, System.Boolean requestSize)[0x0010e](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:511)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Grid.OnSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x0002a](D:\a\1\s\Xamarin.Forms.Core\GridCalc.cs:60)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.VisualElement.OnMeasure(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:762)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.VisualElement.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00053](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:644)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Layout.GetSizeRequest(System.Double widthConstraint, System.Double heightConstraint)[0x00000](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:132)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.VisualElement.Measure(System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)[0x00054](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:702)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.ScrollView.LayoutChildren(System.Double x, System.Double y, System.Double width, System.Double height)[0x000e1](D:\a\1\s\Xamarin.Forms.Core\ScrollView.cs:236)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Layout.UpdateChildrenLayout()[0x00158](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:266)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Layout.OnSizeAllocated(System.Double width, System.Double height)[0x0000f](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:224)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.VisualElement.SizeAllocated(System.Double width, System.Double height)[0x00000](D:\a\1\s\Xamarin.Forms.Core\VisualElement.cs:784)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Xamarin.Forms.Layout.ResolveLayoutChanges()[0x0005c](D:\a\1\s\Xamarin.Forms.Core\Layout.cs:392)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Java.Lang.Thread+RunnableImplementor.Run()[0x00008](Java/Lang/ThreadRunnableImplementor0x00008.cs:1)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at Java.Lang.IRunnableInvoker.n_Run(System.IntPtr jnienv, System.IntPtr native__this)[0x00009](Java/Lang/IRunnableInvoker0x00009.cs:1)
11-14 17:44:22.470 E/AndroidRuntime( 8792): 	at   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.51(intptr,intptr).(unknown.cs:1)

**Comment by PureWeen** [comment]
Probably related
https://github.com/xamarin/Xamarin.Forms/issues/6247
https://github.com/xamarin/Xamarin.Forms/issues/7420
