### ISSUE TITLE
[Enhancement] Search filter in Picker Control

### ISSUE THREAD

**Issue by Anil-R** [xamarin/Xamarin.Forms#8518]
**Summary**
When there are more number of items in displayed in picker dialog ,there should be ability to search and filter items in picker control dialog.

**API Changes**

e.g.
    var picker = new Picker();
    picker.HasSearch = true; // adds search option on alert dialog.
    picker.SearchTextHint = "Hint" // Displays hint text on Search Bar.
    picker.SearchTextChanged +=(s,e)=>
   {
      //filter items inside picker dialog.
   }

**Intended Use Case**

When items source of picker contains more number of items a search ability on top of picker options to filter and find required option to select more comfortably.

**Comment by jcmanke** [comment]
I like the idea, but I'm concerned about the visual implementation, especially on iOS. Since the UIPicker is set as the input accessory view (in place of a keyboard), what do you do while the keyboard is up to type into the search bar?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
