### ISSUE TITLE
[Enhancement] Expose the font size of TabbedPage's titles

### ISSUE THREAD

**Issue by ScarlettCode** [xamarin/Xamarin.Forms#8519]
## Summary
When creating a TabbedPage in order to change the font size of the tab titles you either need a custom renderer or to add a style into your native projects. Would be good to have that property exposed as a easier way to set this.

## API Changes

Either adding FontSize TabbedPage.Children element to set all the font sizes of the tabs or probably more consistent with how colours work adding UnselectedTabFontSize and SelectedTabFontSize to the TabbedPage element would give you the ability to change the size of the selected item too.

**Comment by BillyMartin1964** [comment]
Whatever was decide for this enhancement? It is much needed.

**Comment by justinasfour04** [comment]
@samhouts can we get an update?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
