### ISSUE TITLE
[Bug] CarouselView IsVisible=false than set to true not work on iOS

### ISSUE THREAD

**Issue by jingliancui** [xamarin/Xamarin.Forms#8521]
[CarouselViewSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3850511/CarouselViewSample.zip)
In this sample app,
The grid's IsVisible set to false at start,than click button to set to false.Content of CarouselView not show.
Then modify the xaml for setting the IsVisible to true ,and going to run the app ,that fine.
Then remove the grid control,the issue still happen at the isvisible of CarouselView

**Comment by jingliancui** [comment]
That can be mapped to the real scene:
At start , I hide the control use binding property, then change the property to visible=true .
This control not has this issue for android now.

**Comment by jingliancui** [comment]
Is there any one can give some issue fix tips or the control's logic for me , maybe I can take some time to deal with this issue.

**Comment by cmw9706** [comment]
Is there any update on when this will be fixed or a work around?

**Comment by rmarinho** [comment]
We merged on 4.5.0, btu didn't get the cut for the release, but will be in a service release for 4.5.0 soon.

If you need nuget for test you can try the artifacts here::
https://dev.azure.com/xamarin/public/_build/results?buildId=14557&view=artifacts&type=publishedArtifacts

**Comment by cmw9706** [comment]
So, I don't think we will be able to use the service release (per company policy). But I did just upgrade to 4.5 and now I am having this same issue with the Binding not updating on a Frame component? Does SetBinding() just not work anymore?
