### ISSUE TITLE
[Bug] After upgrading to 4.2.0.709249 TranslateTo animation is not working on Android

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8522]
### Description
After upgrading XF to 4.2.0.709249 **TranslateTo** animation is not working.

### Steps to Reproduce

1. Run this project on Android
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3850960/App1.zip)

2. Click button.
3. Button is moved immediately. There is no smooth animation.

### Expected Behavior
There should be smooth animation when button is moving.

### Actual Behavior
Button is moved immediately. There is no animation.

### Basic Information

- Version with issue: 4.2.0.709249
- Last known good version: 4.1.0.778454
- IDE: Visual Studio 2019 16.3.9

### Reproduction Link

I have uploaded project in "Steps to Reproduce"

**Comment by Mikilll94** [comment]
@jsuarezruiz 
Why have you added Android10 label? This bug happens on older Android devices also.

**Comment by Mikilll94** [comment]
After further investigation, I have discovered that **RotateTo** and **ScaleTo** animations are also not working on Android.

ALL ANIMATIONS ON ANDROID ARE NOT WORKING.

**Comment by Mikilll94** [comment]
@hartez @samhouts 
I discovered a very strange thing. I have cloned Xamarin.Forms repo and in **_Template.cs** I have added the following code:

```
using Xamarin.Forms.CustomAttributes;
using Xamarin.Forms.Internals;

#if UITEST
using Xamarin.Forms.Core.UITests;
using Xamarin.UITest;
using NUnit.Framework;
#endif

namespace Xamarin.Forms.Controls.Issues
{
#if UITEST
	[Category(UITestCategories.ManualReview)]
#endif
	[Preserve(AllMembers = true)]
	[Issue(IssueTracker.Github, 8522, "Animations not working", PlatformAffected.Android)]
	public class Issue1 : TestContentPage
	{
		protected override void Init()
		{
			var stackLayout = new StackLayout();
			var button = new Button()
			{
				VerticalOptions = LayoutOptions.CenterAndExpand,
				HorizontalOptions = LayoutOptions.Center,
				Text = "Click me"
			};
			button.Clicked += (sender, e) => { button.TranslateTo(150, 150, 2000); };
			stackLayout.Children.Add(button);
			Content = stackLayout;

			BindingContext = new ViewModelIssue1();
		}

#if UITEST
		[Test]
		public void Issue1Test() 
		{
			// Delete this and all other UITEST sections if there is no way to automate the test. Otherwise, be sure to rename the test and update the Category attribute on the class. Note that you can add multiple categories.
			RunningApp.Screenshot("I am at Issue1");
			RunningApp.WaitForElement(q => q.Marked("Issue1Label"));
			RunningApp.Screenshot("I see the Label");
		}
#endif
	}

	[Preserve(AllMembers = true)]
	public class ViewModelIssue1
	{
		public ViewModelIssue1()
		{

		}
	}

	[Preserve(AllMembers = true)]
	public class ModelIssue1
	{
		public ModelIssue1()
		{

		}
	}
}
```

And when I am running Android project in **Control Gallery** everything works fine. I am on the master branch. However, in my project which I have attached to this issue animations are not working. How is this possible? Could you check if you have the same strange behavior?

**Comment by Mikilll94** [comment]
@samhouts @hartez @jfversluis 
Hey, now I know everything!!! This issue was already fixed in #7298. Why is this still not released? This is a serious issue for developers which blocks updating XF to the newest version.

**Comment by samhouts** [comment]
Please update to 4.2.0.815419 or later and let us know if you're still experiencing the issue. Thanks!

**Comment by Mikilll94** [comment]
@samhouts 
Thanks, sorry for this confusion. I confirm that on 4.2.0.815419 and later animations are working fine.

This issue can be closed.

**Comment by jfversluis** [comment]
Thanks for the confirmation @Mikilll94 !
