### ISSUE TITLE
I am not able to write data into NfcV ISO15693 tag.

### ISSUE THREAD

**Issue by Rashmi-J-R** [xamarin/Xamarin.Forms#8523]
Hi,

I am trying to write data into NfcV ISO15693 tag using the below mentioned command,

    NfcV iso15693 = NfcV.Get(tag);

    byte[] arrByt = new byte[7];
                arrByt[0] = 0x02;
                arrByt[1] = 0x21;
                arrByt[2] = (byte) 10;
                arrByt[3] = 0x01;
                arrByt[4] = 0x02;
                arrByt[5] = 0x03;
                arrByt[6] = 0x04;

    iso15693.Connect();
    byte[] returnData = iso15693.Transceive(arrByt);
The above command will erase the data in the mentioned block ( Here in this example the 10th block), but it is not writing data into that block after erasing. When I read back I will get empty result in that block.

Please help me to fix this issue.

Thanks in advance.

**Comment by hartez** [comment]
I'm afraid this question is outside the scope of Xamarin.Forms. If you're looking for help with reading/writing NFC tags on Android, you should try asking your question in the [Xamarin.Android forums](https://forums.xamarin.com/categories/android).
