### ISSUE TITLE
[Enhancement] LongPressedCommand in CollectionView

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Forms#8525]
## Summary
I believe that most apps, when displaying a list, need to handle the LongPressed event.
Basically the same that Syncfusion did for their SfListView here: https://help.syncfusion.com/xamarin/listview/working-with-sflistview#itemholding-event

I wish there was also a TappedCommand, rather than using gesture recognizers on the DataTemplate.

## API Changes

I'd love to see a LongPressedCommand, or a HoldCommand:
```
<CollectionView ItemsSource="{Binding MyItems}" TappedCommand="{Binding ItemTappedCommand}" LongPressedCommand="{Binding ItemLongPressedCommand}">
...
</CollectionView>
```

## Intended Use Case
Very often you need to show a contextual menu when you long tap on an item in any list.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
