### ISSUE TITLE
[Bug] DisplayPromptAsync hangs app, doesn't display when called in page load

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#8526]
### Description
When DisplayPromptAsync is called during the initiation of a page, rather than through user interaction (like a button click), the prompt does not display and the app hangs.  If a DisplayAlert is added before the DisplayPromptAsync then both the alert and the prompt display properly.  This happens on both iOS and Android.

### Steps to Reproduce

1. Run the attached app.  It should display a prompt, but doesn't.  This app doesn't do anything else, but on my production app it hangs at this point.
2. Edit LoadingPage.cs and uncomment line 90, the DisplayAlert
3. Re-run the app.  Note that the app displays the alert and then the prompt.

### Expected Behavior
The prompt should display when the app starts / page loads.

### Actual Behavior
The prompt does not display.

### Basic Information

- Version with issue:
- Last known good version: none
- IDE: VS2019
- Platform Target Frameworks: 4.3 (all 3 versions)

### Reproduction Link

[Connection.zip](https://github.com/xamarin/Xamarin.Forms/files/3852617/Connection.zip)

**Comment by hartez** [comment]
Confirmed. This is happening because `DisplayPromptAsync` doesn't do the `IsPlatformEnabled` check like `DisplayAlert` and `DisplayActionSheet`.

**Comment by hartez** [comment]
@czuck As a workaround until we fix this, DisplayPromptAsync _will_ work if you wait until the Appearing event before calling it. So in your constructor, if you change
`Connect();` 
to
`Appearing += (sender, args) => Connect();`
it should display the prompt.

**Comment by czuck** [comment]
Thanks!

**Comment by shettysupreetha** [comment]
Facing this issue with MAUI. Display promptasync dialog  appears, after Display alert , but doesn't appear first
