### ISSUE TITLE
[Bug] Fix the Shell story when running on iPad in multi task mode

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8527]
### Description

Very similar to the issue here
https://github.com/xamarin/Xamarin.Forms/issues/2017#issuecomment-554466816

Along with this fix it'd be nice to expose a platform specific out so the user can be aware that an app has transitioned to "Collapsed mode" And then make decisions about layouts. 

If you compare the Apple News app vs the Notes app you'll see each one handles split view differently.

Apple News transitioned out of split view and only lets you see the DetailsViewController and then the Notes app transitions to a UINavigationController experience where the master is at the root of your stack. 

My thinking is that the Notes app should be the default but we should expose something out to let the user change to a different shell layout if they need to

### Steps to Reproduce
Run Control Gallery
switched to store shell

1. Move to 30 percent shell / 70 percent other
2. click something in menu that navigates
3. crashes

### Expected Behavior

It should navigate away from the Master ViewController to the details controller you clicked on. Compare the behavior to the Notes app.

### Actual Behavior

Currently it just crashes

**Comment by Jared-Aus** [comment]
My issue matches the title, but not necessarily the description. The simplest way to demonstrate that Shell is broken with iPad split screen is to create two new XF solutions in VS, one using the shell template and the other with the blank template. At a 50/50 split the blank template shows content and the shell template a white screen. It makes no difference if using XF 4.2, 4.3, or 4.4.0-pre2.
