### ISSUE TITLE
[Enhancement] Grid : ActualWidth and X properties for ColumnDefinition And ActualHeight and Y properties for RowDefinition

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#8538]
## Summary
It could be nice to have public getter of the Actual Width and Actual Height for a specific cell inside the Grid.
First for now it's not possible to know the Width and the Height of a specific Cell when GridUnitType is in Auto or Star Unit. We need to populate the cell with an empty filled View and get his Height and Width property.
Second it's impossible to know the X and Y position of View inside a Grid.

## API Changes
Actual Api :
`````
//ColumnDefinition Class
internal double ActualWidth { get; set; }

//RowDefinition Class
internal double ActualHeight { get; set; }
`````
Changed needed : 
`````
//ColumnDefinition Class
public double ActualWidth { get; internal set; }
public double X  { get; internal set; }

//RowDefinition Class
public double ActualHeight { get; internal set; }
public double Y  { get; internal set; }
`````

## Intended Use Case
It will help to locate a view inside a Grid.
Then Beautiful and specific animation could be done with these properties.

**Comment by GalaxiaGuy** [comment]
There is an internal property for ActualWidth/Height already that could possible be exposed with a public getter. X and Y would be harder though, since the definitions don't have access to the parent grid and therefore don't know about the other definitions. Methods on the grid could be made though.

**Comment by Phenek** [comment]
Hi @GalaxiaGuy,
Yep I understand that it could be harder to have  X and Y positions.
Never mind if ActualWidth/Height could be exposed with a public getter,
 it will be possible from the Grid to guess the X and Y position.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
