### ISSUE TITLE
[Bug] Cannot build Xamarin.Forms solution

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8540]
### Description
I have cloned Xamarin.Forms repo and I want to build Android project in **Control Gallery** folder. Unfortunately, build fails. Here are the errors:

![image](https://user-images.githubusercontent.com/17653648/69015622-0b723580-0996-11ea-9bc2-c86864c4a578.png)

### Expected Behavior
Xamarin.Forms repo should build successfully.

### Actual Behavior
Xamarin.Forms repo does not build. I don't know why.

### Basic Information

- IDE: Visual Studio 2019 16.3.9

I have installed all required ingredients for Visual Studio except UWP, because I don't want to run apps on UWP.

I will be very glad for any help!

**Comment by hartez** [comment]
@Mikilll94 Make sure you have followed all of the steps in the [Getting Started](https://github.com/xamarin/Xamarin.Forms#getting-started) section of the readme. Then please submit a list/screenshot of _build_ errors, and specify which platform you are attempting to build Control Gallery for (the screenshot suggests Android, but it helps to be specific). Please include information such as API level, solution configuration (DEBUG or RELEASE), target device/emulator.

**Comment by Mikilll94** [comment]
@hartez 
I checked **Getting Started** guide and the fault was on my side.

My Visual Studio installation was missing .NET Framework 4.7 SDK. I installed it and now everything works. Android project in Control Gallery launches without problems. This issue can be closed.

**Comment by jfversluis** [comment]
Glad that this is sorted @Mikilll94 waiting to see your PRs 😉
