### ISSUE TITLE
[Bug] [Shell] iOS - BackButtonBehavior Command property not used unless IconOverride or TextOverride properties are set

### ISSUE THREAD

**Issue by brunck** [xamarin/Xamarin.Forms#8546]
### Description
Not sure if this is by design, but if you set `Shell.BackButtonBehavior` on a page and only set the `Command` property and nothing else, the bound command is not invoked.

In other words, if you do this, the `BackCommand` is invoked upon back navigation:

    <ContentPage ...>    
        <Shell.BackButtonBehavior>
            <BackButtonBehavior Command="{Binding BackCommand}" IconOverride="back.png" />   
        </Shell.BackButtonBehavior>
     ...
    </ContentPage>

But if you set only the `Command` like this, whatever was specified in `BackCommand` is skipped:

    <ContentPage ...>    
        <Shell.BackButtonBehavior>
            <BackButtonBehavior Command="{Binding BackCommand}" />   
        </Shell.BackButtonBehavior>
        ...
    </ContentPage>

### Steps to Reproduce
Using the attached application:

0. Note that in `MonkeyDetailView` and `MonkeyDetailViewModel` a Command is wired to the `Shell.BackButtonBehavior.`
1. Navigate to `Monkeys` using the bottom tab.
2. Click on `Baboon.`
3. Click on the back button.

The custom command would cause a label to show on the page, instead of the default behavior of back navigation occurring. 

If you add an `IconOverride` (such as `IconOverride="back.png"`) or a `TextOverride` to the `Shell.BackButtonBehavior`, the `Command` behavior occurs.

### Expected Behavior
When only the `Command` property is specified in `Shell.BackButtonBehavior` the specified `Command` is invoked upon back navigation.

### Actual Behavior
The default back button behavior is used on back navigation.

### Basic Information

- Version with issue: 4.3
- Last known good version: unknown
- IDE: VS 2019 for Windows and VS for Mac 8.3
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.6.0.12

### Reproduction Link
[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3861026/Xaminals.zip)

**Comment by PureWeen** [comment]
> When only the Command property is specified in Shell.BackButtonBehavior the specified Command is invoked upon back navigation.

Bug

**Comment by brunck** [comment]
@PureWeen so if we specify just the Command, it should go ahead and use what you specified, even if you don't specify IconOverride or TextOverride?

**Comment by PureWeen** [comment]
@brunck yes

**Comment by brunck** [comment]
Added reproduction sample and steps.

**Comment by Raystorm7** [comment]
Any news on this?
Thank you :)

**Comment by jfversluis** [comment]
Confirmed that this happens, only on iOS.

This might be a tough one. When a custom text or icon is supplied, we swap out the default back button provided by iOS with a toolbar item, causing the command to be invoked. Whenever we don't have a custom text or icon, the regular iOS back button behavior is used and therefore the command is not invoked.

Originates somewhere around here: https://github.com/xamarin/Xamarin.Forms/blob/87d720c71ec1c8f8fea2daf2105ba4b6689d71f1/Xamarin.Forms.Platform.iOS/Renderers/ShellPageRendererTracker.cs#L220

**Comment by sachinkanadia** [comment]
Has this been resolved?

**Comment by brunck** [comment]
@sachinkanadia this is still open.

**Comment by sachinkanadia** [comment]
@brunck Thanks for the update & workaround.. I'll give it a go

**Comment by Raystorm7** [comment]
Hi, 
any news on this?

Thank you.

**Comment by PureWeen** [comment]
This should be fixed by https://github.com/xamarin/Xamarin.Forms/pull/8951

you can test in the latest 4.7 pre release or wait for the next stable 4.6
