### ISSUE TITLE
HasNavigationBar-False does not hide 

### ISSUE THREAD

**Issue by jantanis** [xamarin/Xamarin.Forms#8550]
### Description
A master detail page within a tabbed page on which the detail has a navigation page shows 2 navigation bars, that cannot be hidden.

### Steps to Reproduce
1. Create a MasterDetail page within a NavigationPage within a TabbedPage
2. Set HasNavigationBar=false on the masterdetailpage

### Expected Behavior
Shows only navigation bar of detail page.

### Actual Behavior
Shows two navigation bars

### Basic Information
- Version with issue: 4.2.0.778463
- Last known good version:
- IDE: 8.3.8 (8)
- Platform Target Frameworks:
  - iOS:  11.2
- Nuget Packages:
- Affected Devices: iOS simulator

### Screenshots
![Simulator Screen Shot - iPad Pro (12 9-inch) (2nd generation) - 2019-11-18 at 13 35 15](https://user-images.githubusercontent.com/11005949/69052832-4ca32d80-0a08-11ea-8929-92cb5f36f041.png)

### Reproduction Link
[MasterOfDetails.zip](https://github.com/xamarin/Xamarin.Forms/files/3858614/MasterOfDetails.zip)

**Comment by jfversluis** [comment]
From [the documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#creating-a-masterdetailpage):

> A `MasterDetailPage` is designed to be a root page, and using it as a child page in other page types could result in unexpected and inconsistent behavior. In addition, it's recommended that the master page of a `MasterDetailPage` should always be a `ContentPage` instance, and that the detail page should only be populated with `TabbedPage`, `NavigationPage`, and `ContentPage` instances. This will help to ensure a consistent user experience across all platforms.

These kinds of scenarios are not supported. I'm pretty sure the same goes for a `NavigationPage` and `TabbedPage`. You might want to rethink what you are trying to achieve and maybe design your application differently.

I will close this for now, hoping that I have informed you correctly and sufficiently. If you think different about this, please feel free to let us know :)

Thanks!
