### ISSUE TITLE
iOS, TabbedPage icons from FontImageSource showed but not grayed when icon is not selected[Bug] 

### ISSUE THREAD

**Issue by aperrone** [xamarin/Xamarin.Forms#8556]
### Description
I made an application based on a tabbed page; in iOS, I thought of using a FontImageSource to generate the icons to be displayed in the bottom bar.
The solution worked and the icons are correctly displayed; unfortunately they are never colored as disabled, ie they are never grayed out.

### Steps to Reproduce

1. Create a project Master/Detail for iOS
2. Change the icon source to a FontImageSource

` 

        <NavigationPage Title="my Title">
            <NavigationPage.IconImageSource>
                <OnPlatform x:TypeArguments="FontImageSource">
                    <On Platform="iOS">
                        <FontImageSource FontFamily="{StaticResource MaterialFontFamily}" Glyph="{StaticResource IconCancel}" Color="#FF000000" />
                    </On>
                </OnPlatform>
            </NavigationPage.IconImageSource>
            <x:Arguments>
                ...
            </x:Arguments>
        </NavigationPage>
`

### Expected Behavior

The selected icon become black. The other icons become grayed.

### Actual Behavior

All icons become black, selected page or not selected pages. No icons become grayed.

### Basic Information

- Platform Target Frameworks:
  - iOS:  13.2

### Screenshots

![image](https://user-images.githubusercontent.com/11210279/69097701-63bd3c00-0a57-11ea-9c65-7dd3309bc25b.png)

**Comment by MSiccDev** [comment]
I had a similar problem with my tabbed based icons (image assets, however). The only way to get rid of it was to explicitly specify the SelectedTabColor and UnSelectedTabColor (which was mentioned as “solution” in another issue). Long story short: I also expected the coloring to work out of the box.

**Comment by aperrone** [comment]
I tried but it doesn't work...

Xamarin riesce ogni giorno a stupirmi.

**Comment by samhouts** [comment]
@aperrone  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by pboisso** [comment]
Same behavior noticed here. Is there a fix coming in?

**Comment by moellerbj** [comment]
Similar behavior here. I assign the icons via FontImageSource and set both SelectedTabColor and UnselectedTabColor. Everything is displayed correctly in Android, under iOS only the text is set to UnselectedTabColor, not the icon. That always stays on SelectedTabColor.

**Comment by RadoslawKubas** [comment]
I have exactly same problem, when tab icons are from FontImageSource, selected / unselected colors are not set. Is there any solution (except using png icons) ?
