### ISSUE TITLE
[Bug] Grouped header with incorrect size when use GridItemsLayout with two columns on the CollectionView

### ISSUE THREAD

**Issue by ionixjunior** [xamarin/Xamarin.Forms#8557]
### Description

When create a grouped collection view and use GridItemLayout with two columns or more, the content width of the group is based on the first item of the collection view. An interesting thing is that background color of the group header fill entire screen. 

### Steps to Reproduce

1. Open the project at attachment and run in iOS simulator
2. See the content of the group section fill only the space of the first item

### Expected Behavior

The content of the group section fill entire screen (yellow area).

### Actual Behavior

The content of the group section fill only the size of the first item.

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.991211 (but occurs in the pre-release too)
- Last known good version: I don't know
- IDE: Visual Studio for Mac 8.3.9
- Platform Target Frameworks:
  - iOS:  Xamarin.iOS 13.6.0.12

This problem is happening in iOS only. Android is fine and UWP I don't tested.

### Screenshots

<img width="300" src="https://user-images.githubusercontent.com/519642/69101110-804c7a80-0a3d-11ea-824f-322c7dd8c19d.png" />

### Reproduction Link

[CollectionViewBugs.zip](https://github.com/xamarin/Xamarin.Forms/files/3861086/CollectionViewBugs.zip)

**Comment by arramex** [comment]
Hi there,

Is this fix available in a prerelease form by any chance?

Kind regards

**Comment by oguja** [comment]
Hi there,

Is this fix available in a prerelease form by any chance?

Kind regards
