### ISSUE TITLE
[Bug] [UWP] Random crash error Delegate to an instance method cannot have null 'this'.

### ISSUE THREAD

**Issue by Sonic3R** [xamarin/Xamarin.Forms#8564]
### Description
I have an application, enterrprise one which uses latest version of Xamarin.Forms 4.3.x and MvvmCross 6.4.1

In a view, I have list view and when tap on item, randomly I got excpetion (in `App.g.i.cs` file):

> Delegate to an instance method cannot have null 'this'.
> 
> Value does not fall within the expected range.
> 
> System.ArgumentException: Delegate to an instance method cannot have null 'this'.
>    at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
>    at Xamarin.Forms.Platform.UWP.TitleViewManager..ctor(ITitleViewRendererController titleViewRendererController)
>    at Xamarin.Forms.Platform.UWP.MasterDetailControl.OnApplyTemplate()
>    at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)

I don't see anything in Call Stack and I don't know who cause this error.

And from Event Viewer

> Faulting application name: MyApp.UWP.exe, version: 1.0.0.0, time stamp: 0x5d362223
> Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17134.1038, time stamp: 0xb71460d6
> Exception code: 0xc000027b
> Fault offset: 0x0084ff0c
> Faulting process id: 0x11dc
> Faulting application start time: 0x01d59ebdcb48f910
> Faulting application path: C:\...\MyApp.UWP.exe
> Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
> Report Id: 071c1a48-b765-4da4-a860-92f9150af6a0
> Faulting package full name: myApp_x86__gg6ky5nm9kyr
> Faulting package-relative application ID: App

### Steps to Reproduce

Very hard to reproduce, it happens sometimes. I don't know where error came from.

### Expected Behavior
No error should occur

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: 3.3.0.912540 with MvvmCross 5.0.6
- IDE: VS 2019 16.3
- Platform Target Frameworks: 
  - UWP:  17763
- Nuget Packages: Xamarin.Forms, MvvmCross
- Affected Devices: Windows

### Advice

Can you advice which section may occur the error  since it happens in Xamarin.Forms internal class ? Where to look at ?

**Comment by samhouts** [comment]
@Sonic3R  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Sonic3R** [comment]
Can;t attach my enterprise project where error occur...Seems that happens only on UWP but not on iOS.. Very hard to create new project with stuff from enterprise project

**Comment by PureWeen** [comment]
if you can email it to shneuvil at microsoft.com and it's easily runnable @Sonic3R

**Comment by Sonic3R** [comment]
I put here the project, finnaly I could reproduce issue. See atatched project.
[TestAppWithMvvmCross.zip](https://github.com/xamarin/Xamarin.Forms/files/3982428/TestAppWithMvvmCross.zip)

**Comment by samhouts** [comment]
I'm not sure if this is caused by MvvmCross or not, but I do see the crash, and I suspect we can at least prevent it. Requires further investigation.

 ```
  at Windows.UI.Xaml.Controls.Control.ApplyTemplate()
   at Xamarin.Forms.Platform.UWP.MasterDetailControl.Xamarin.Forms.Platform.UWP.IToolbarProvider.GetCommandBarAsync()
   at Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.Xamarin.Forms.Platform.UWP.IToolbarProvider.GetCommandBarAsync()
   at Xamarin.Forms.Platform.UWP.Platform.<UpdateToolbarItems>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Forms.Platform.UWP.Platform.<OnToolbarItemsChanged>d__43.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Comment by artemious7** [comment]
I'm having a very similar exception

**Comment by artemious7** [comment]
Exception message:
`Delegate to an instance method cannot have null 'this'.`

Exception stack trace:

   ```
в Windows.UI.Xaml.Controls.Control.ApplyTemplate()
   в Xamarin.Forms.Platform.UWP.MasterDetailControl.Xamarin.Forms.Platform.UWP.IToolbarProvider.GetCommandBarAsync()
   в Xamarin.Forms.Platform.UWP.MasterDetailPageRenderer.Xamarin.Forms.Platform.UWP.IToolbarProvider.GetCommandBarAsync()
   в Xamarin.Forms.Platform.UWP.Platform.<UpdateToolbarItems>d__47.MoveNext()
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Xamarin.Forms.Platform.UWP.Platform.<OnToolbarItemsChanged>d__43.MoveNext()
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   в System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

It happens [at this line](https://github.com/xamarin/Xamarin.Forms/blob/2f6c6ec42016ef26007980d7b1a73f102bd68f78/Xamarin.Forms.Platform.UAP/TitleViewManager.cs#L22)
			`_titleViewRendererController.TitleViewPresenter.Loaded += OnTitleViewPresenterLoaded;`

Adding a null-check solves the issue, I tested.

**Comment by artemious7** [comment]
@samhouts I think we can stop on "Done" :-D
