### ISSUE TITLE
[Bug] Setting MaxLines to zero will make labels invisible on some Android api levels

### ISSUE THREAD

**Issue by MitchBomcanhao** [xamarin/Xamarin.Forms#8565]
### Description
Setting a label's MaxLines property to zero should result in no maximum being set, as per the [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#display-a-specific-number-of-lines):

> When MaxLines is 0, the Label respects the value of the LineBreakMode property to either show just one line, possibly truncated, or all lines with all text.

I am however getting different results in different Android API levels.
- android 9 and 10 seem to display zero lines of text.
- older versions like 8 will display the label as expected.
- the Xamarin previewer in VS2019 16.3.9 also displays the issue.

### Steps to Reproduce

Create a page with the following content
```
    <StackLayout VerticalOptions="Center">
        <Label HorizontalOptions="Center" Text="The following label is fine:" />
        <Label HorizontalOptions="Center"
               LineBreakMode="CharacterWrap"
               MaxLines="1"
               Text="THIS IS VISIBLE"
               TextColor="Green" />
        <Label HorizontalOptions="Center" Text="The following label is broken if MaxLines is set to zero" />
        <Label HorizontalOptions="Center"
               LineBreakMode="CharacterWrap"
               MaxLines="0"
               Text="THIS SHOULD BE VISIBLE"
               TextColor="Red" />
    </StackLayout>
```

### Expected Behavior
All labels are visible.
### Actual Behavior
Last label is not visible on (at least) android 9 and 10, but it is present in the UI tree.

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: unknown
- IDE: VS2019 16.3.9
- Platform Target Frameworks: 
  - Android: 9.0 API 28

### Screenshots
Previewer screenshot:
![image](https://user-images.githubusercontent.com/31066938/69146137-14aeef80-0ac7-11ea-9681-3fc6fc8457c9.png)

android 10 screenshot
![image](https://user-images.githubusercontent.com/31066938/69146193-33ad8180-0ac7-11ea-93b4-c9d899c04f28.png)

android 8 screenshot
![image](https://user-images.githubusercontent.com/31066938/69147146-3f01ac80-0ac9-11ea-8f7e-2e45101bc989.png)

**Comment by StephaneDelcroix** [comment]
doc seems wrong, as the default value (no MaxLines), `MaxLinesProperty.DefaultValue` is `-1`

/cc @davidbritch

**Comment by davidbritch** [comment]
There's a mismatch between the [enhancement](https://github.com/xamarin/Xamarin.Forms/issues/1706) and the [PR](https://github.com/xamarin/Xamarin.Forms/pull/3318), but the PR does discuss changing the default from 0 to -1.

Therefore, the doc updates become:

1. What's listed for MaxLines==0 will become MaxLines==-1.
2. Add a new bullet for when MaxLines is 0 (no text displayed).

**Comment by MitchBomcanhao** [comment]
if the fix is updating the documentation, then we can assume that this bug is now reversed:
- using maxlines=0 still shows text on multiple platforms, when the documentation says it shouldn't.

**Comment by samhouts** [comment]
This was updated in the documentation. Thanks!
