### ISSUE TITLE
NavigationPage.TitleView height need to increase in UWP

### ISSUE THREAD

**Issue by gnani143** [xamarin/Xamarin.Forms#8566]
I have implemented NavigationPage.TitleView with custom flexlayout. it contains leftbutton items, titles and below sub titles, rightbutton items. when I connected external monitor I am increasing fontsize of titles so that it will visible properly. But TitleView height not increasing accordingly. I didn't find any property to increase TitleView height. 

### Steps to Reproduce

1. created customview with navigation items.
2. increased fontsize of titles
3. sub titles goes partially disabled due to Titleview height not increasing accordingly. 

### Expected Behavior
TitleView height should change based on customview properties

### Actual Behavior
TitleView Height not changing/not able to change

### Basic Information

- Version with issue: 3.6.0.344457
- Last known good version:
- IDE: Vitual studio 2019
- Platform Target Frameworks: 
  - UWP:  version 1809(build 17763)
- Nuget Packages: Yes
- Affected Devices: All

### Screenshots

![header issue](https://user-images.githubusercontent.com/5513079/69148101-8869f000-0af9-11ea-8f4f-e9ad2437c9cc.JPG)

**Comment by samhouts** [comment]
@gnani143  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
