### ISSUE TITLE
[Bug, iOS] Frame shadow layer not properly removed 

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#8567]
### Description

By the merge of #7518 there is now a bug where `Frame`s aren't properly removed. At leased when used in a `BindableLayout` with the shadow on. This is discovered [while reviewing](https://github.com/xamarin/Xamarin.Forms/pull/7686#pullrequestreview-312618972) the empty view implementation on the `BindableLayout`.

#### Investigation

I have tried to fix it, but can't quite get it right. When you add a `Dispose` to the `FrameRenderer` on iOS like this:

```
                protected override void Dispose(bool disposing)
		{
			if (_isDisposed)
				return;

			if (disposing && _shadowView != null)
			{
				_shadowView.RemoveFromSuperview();
				_shadowView.Dispose();
				_shadowView = null;
			}

			_isDisposed = true;
			
			base.Dispose(disposing);
		}
```

It seems a bit better, but not entirely fixed. See below on what that does to the behavior.

![Untitled](https://user-images.githubusercontent.com/939291/69150378-dfab9880-0ad8-11ea-813c-1f9f0099ad61.gif)

Notice how the first item is removed and the shadow disappears, but there still remains an artefact at the bottom. It almost seems like the boxes are removed in the opposite direction.

### Steps to Reproduce

1. Start Gallery app
2. Go to BindableLayout Gallery - Legacy
2 a. If the empty view PR (#7686) got merged in the meantime, remove the `HasShadow="false"` from the `Frame` on this page
3. Remove an item and observe that an empty yellow box stays behind

### Expected Behavior

Frame is entirely removed from the layout, no empty yellow box is shown

### Actual Behavior

The frame outline (yellow box) is still visible as an artefact on the screen

### Basic Information

- Version with issue: current master branch
- Last known good version: Before #7518
- Platform Target Frameworks:
  - iOS:  13.2.2 but all are affected

### Screenshots

![Broken](https://user-images.githubusercontent.com/1235097/68322870-21414a00-00bc-11ea-9cd4-28878727ef46.png)

**Comment by jfversluis** [comment]
I totally see this happening, thank you for your excellent report @jfversluis!

**Comment by samhouts** [comment]
@jfversluis Did you happen to fix this, by any chance? 😁

**Comment by jfversluis** [comment]
Well waddayaknow! I did! Assuming that the Frame fixes were merged and in master currently. Retested it and didn't see this problem anymore.
