### ISSUE TITLE
[Enhancement] Look into lowering our UWP minimum requirement to 10240

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8570]
## Summary
On the heels of getting this PR merged https://github.com/xamarin/Xamarin.Forms/pull/7079 should we go even lower!!

Justification here

https://github.com/xamarin/Xamarin.Forms/pull/7079#issuecomment-549256508

We use `LTSC` versions in the area of business/industrial applications such as kiosks, medical equipment, Point of Sales, advertising monitors, ...

`LTSC` versions are not automatically updated and are supported for 10 years. They do not contain Microsoft Store and applications installed by default. More details: https://techcommunity.microsoft.com/t5/Windows-IT-Pro-Blog/LTSC-What-is-it-and-when-should-it-be-used/ba-p/293181

In my opinion, the problem is not so much the support of `LTSC` versions, it's rather the backwards compatibility of `Xamarin.Forms` with the different versions of Windows 10. We can still target `iOS 7` or `Android 4.4` with the latest version of `Xamarin.Forms`, why we can't target a version of Windows 10 that was released less than 3 years ago (`Build 15063` released April 2017)? Why we can't target the first version released in 2015?

I think the main problem comes in the support of the `.NET Standard` versions in UWP applications, they require an update of Windows. Now there is the same problem with `.NET Standard 2.1`: https://github.com/dotnet/standard/issues/1567

With back support of `.NET Standard 1.4` it would again be possible to target the `Build 10240`, why not do it?

**Comment by YZahringer** [comment]
This will be fixed with `.NET 5.0` and new [WinRT APIs support](https://github.com/dotnet/runtime/issues/35318)? 
Support of `.NET 5.0` is planned in `Xamarin.Forms 5.0`?

**Comment by YZahringer** [comment]
Related #12112

**Comment by mhrastegary77** [comment]
Any news :((((

**Comment by jfversluis** [comment]
Hm I see my standard reply might not cut it here as this is not applicable to .NET MAUI I guess 😅 

But this won't be happening for Forms I think. Too much risk of breaking things here.
