### ISSUE TITLE
[Bug] can not set x:Name in a CarouselView

### ISSUE THREAD

**Issue by mcguu** [xamarin/Xamarin.Forms#8573]
**#[Bug] CarouselView bug.**
In a CarouselView 's DataTemplate if you add some Views and you sepecify it's x:Name. you can not access it in the cs file.
and outside the CarouselView it is accessible.

**### Steps to Reproduce**

1. Open a Project and Add a new page.
2. Add a CarouselView and add some Views in the Template.
3. Specify the x:Name of the Views you added.

### Expected Behavior
can use it in the cs file.
### Actual Behavior
it will tell you there is no "xxx" in the context.

**Comment by StephaneDelcroix** [comment]
`x:Name` defined in another namescope than the root one do not result in a field being created.

in the case of a DataTemplate, there are multiple instances living at the same time, so it doesn't make any sense to add a field to containing type
