### ISSUE TITLE
[Bug][Android] XF CollectionView with MandatorySingle SnapPoints seems to retains extraneous position state past the last element

### ISSUE THREAD

**Issue by tmijieux** [xamarin/Xamarin.Forms#8578]
### Description

I have a collection view with a horizontal LinearItemsLayout with MandatorySingle SnapPoints.
(I have setup my items to have 95% of screen width and full screen height so the layout looks a little like a fullscreen carousel view.)
If I swipe until i get to the last item and then continue to swipe in the same direction multiple times
and then try to swipe in the opposite direction to get to the "previous-to-last" item, the collection view stays on the last item. If I swipe back a few more times, it eventually gets back to the previous item.

### Steps to Reproduce
minimal reproduction app: https://github.com/tmijieux/XFCollectionViewBug
1. Launch the minimal-repro app.
2. Swipe (right to left) 2 times (get to the third(last) item from the initial position).
3. Swipe (right to left) 4 times. (you can replace 4 with any number > 0 you want)
4. Swipe back (left to tight).
5. Swipe back 4 more times (left to tight). (same amount of time than in step 3)

### Expected Behavior
The CollectionView focus on the second item after step 4.

### Actual Behavior
The CollectionView focus on the second item after step 5.

### Basic Information

The issue exists on android (we were not able to reproduce it on iOS)
It was not tested on other platforms except Android and iOS.

My guess is that some property/state variable stores the current position, and it is incremented when we try to go past the last element instead of staying the same. Then you have to decrement it to the previous position to actually get there.

- Version with issue: tested with latest Xamarin.Forms nuget (4.3.0.991211) and pre-release (4.4.0.991210-pre2)
- Last known good version: ?
- IDE: Visual Studio Community 16.3.9
- Platform Target Frameworks: 
  - Android:     Xamarin.Android 9.0
  - Android Support Library Version:  Xamarin.Android.Support.Core.Utils Version="28.0.0.3" 
- Nuget Packages: see [Xamarin Android csproj](https://github.com/tmijieux/XFCollectionViewBug/blob/master/XFCollectionViewBug/XFCollectionViewBug.Android/XFCollectionViewBug.Android.csproj#L56)
and [Xamarin Forms csproj](https://github.com/tmijieux/XFCollectionViewBug/blob/master/XFCollectionViewBug/XFCollectionViewBug/XFCollectionViewBug.csproj#L9)
- Affected Devices: the issues seems to happen on Android (emulator(pixel 2 pie 9.0 api 28) and my real device Samsung SM-J330FN (Android 8.0.0) )

### Reproduction Link

https://github.com/tmijieux/XFCollectionViewBug

**Comment by rmarinho** [comment]
This was fixed on #9700 you can get the fix on 4.5.0 sr1  (next week) or 4.6.0-pre1 (already up)
