### ISSUE TITLE
[Bug] Control Gallery macOS app damaged

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8580]
### Description
Unable to run ControlGallery on macOS (Catalina)

### Steps to Reproduce

1. Run Xamarin.Forms.ControlGallery.MacOS

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio for Mac 8.4 (2535)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/33021114/69244175-29fe4980-0bad-11ea-805e-186f2d10fa0d.png)

**Comment by jfversluis** [comment]
That's due to the new protections in Catalina. You can unblock it by running this in a Terminal window

`xattr -d -r com.apple.quarantine foldername`

`foldername` could be the root of the repo or just the root of the `Xamarin.Forms.ControlGallery.MacOS`

**Comment by VladislavAntonyuk** [comment]
@jfversluis it didn't help. I ran the command on Xamarin.Forms folder

**Comment by VladislavAntonyuk** [comment]
```
vladislav@Vladislavs-Mac Projects % xattr -d -r com.apple.quarantine Xamarin.Forms

**Comment by jfversluis** [comment]
Does it give you any output?

**Comment by VladislavAntonyuk** [comment]
the issue is solved by renaming Xamarin.Forms folder to Xamarin-Forms
