### ISSUE TITLE
Relativesource bindings and behaviors

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Xamarin.Forms#8584]
RelativeSource bindings don`t work with behaviors, so I am not able to do it inside controltemplate and bind to templated parent

**Comment by StephaneDelcroix** [comment]
please provide a sample code of what you're trying to achieve. thanks

/CC @legistek

**Comment by legistek** [comment]
Ditto. Also note that since `Behavior` doesn't derive from `Element` it has no `Parent` (technically we look for `RealParent`) and is not part of the visual tree, so `TemplatedParent`,  `FindAncestorBindingContext` and `FindAncestor` bindings would not work on them currently. (I guess we could support `Self` easily enough but the others would require more creativity.

**Comment by StephaneDelcroix** [comment]
@legistek has a good point here.

Behaviors can be reused (same instance applied multiple times at different laces, so it does not make sense to have relative binding working there.

**Comment by Alex-Dobrynin** [comment]
@legistek But somehow this works in WPF, and behaviors in WPF also have no 'Parent'. But Attached (associated) object has. So I can suggest to add check to relativesource binding, if "Behavior" then look parent in associated object or smth like this

**Comment by legistek** [comment]
Ah but XF's `Behavior` is different from WPF's. WPF's `Behavior` has a single `protected T AssociatedObject` property, so the `Behavior` instance is always associated with one object instance and what you suggest would work there.

But  XF's `Behavior` uses `protected Type AssociatedType { get; }`, i.e., the `Behavior` instance is associated with an object _type_. In other words, there's no 1:1 association between a `Behavior` instance and an `Element` in the visual tree and thus no general purpose solution here as far as I can see.
