### ISSUE TITLE
[Bug] Label underline not working on iOS

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8585]
### Description

Just create a label with **"TextDecorations="Underline"** .

i.e.
```
<Label Text="Welcome to Xamarin.Forms!" HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" TextDecorations="Underline"/>
```

Underline is visible only on Android. On iOS setting underline for a label has no effect.

### Expected Behavior
Underline should work on Android on iOS.

### Actual Behavior
Underline is only working on Android.

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: Visual Studio 2019 16.3.9

**Comment by jfversluis** [comment]
Duplicate of #8272
