### ISSUE TITLE
[Bug] Text alignment issues on button with text

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8589]
### Description

On Android when a button has set an Image, the text alignment is strange. It is shown on the screen below:

![image](https://user-images.githubusercontent.com/17653648/69266160-f16d6880-0bca-11ea-8383-380e27322a64.png)

As you can see the text is not centered.

It would be nice if there was also an ability to set the alignment of the text in the button. I.e. I want to have the ability to set the text sticked to the right side.

### Steps to Reproduce

1. Run the attached project on Android.
2. As you can see text is not centered inside the button.

### Expected Behavior

The text should be centered inside the button.

### Actual Behavior

The text is not centered inside the button.

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: 16.3.9

### Reproduction link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3870822/App1.zip)

**Comment by StephaneDelcroix** [comment]
the text is centered in the space left from the image. Imagine the padding on the right of the image present on the left as well...

**Comment by StephaneDelcroix** [comment]
you can have some control over the button Layout by setting the `ButtonContentLayout` property. I don't see any bug here, so I'm closing this. Feel free to discuss in case I'm missing something here.
