### ISSUE TITLE
[Bug] Android "fast deploy" can't recover from uninstall

### ISSUE THREAD

**Issue by XavierAP** [xamarin/Xamarin.Forms#8592]
### Description
"Fast deploy" fails if the app had been uninstalled from the device's side.

### Steps to Reproduce
1. Start with a Debug configuration. There may be many combinations between debug/release and several project deploy options (detailed at next point).
1. Enable (or leave enabled as default) project settings > Android options > packaging properties > "Use Shared Runtime"; "Use Fast Deployment (debug mode only)"; and "Use incremental Android packaging system".
1. Deploy an Android project to a device. One fresh from the VS wizard is [attached](https://github.com/xamarin/Xamarin.Forms/files/3870992/bug-android-fast_deploy-uninstalled.zip).
1. Uninstall deployed app manually from the device.
1. Optionally, deploy again: if no code changes, it is reported successful, but the app is not back in the device.
1. Try debugging; deployment fails, with error message: «ADB0000: Could not determine the installation path for package com.[companyname].[projectname]. `adb shell pm path com.companyname.test` returned ''.»

### Expected Behavior
- After trying deploying the second time (optional step), the build should realize the end result is not ok, because the app can't be found.
- When encountering the exception while debugging, the build should recover from it and try a regular slow deployment. Or at the very least, provide an error message that points to the possibility that disabling the "fast deploy" setting may solve the problem.

### Actual Behavior
As described,
- deployment reports success (at least in case of no code changes) even if the previously uninstalled app is not deployed; and
- debugging keeps failing

### Basic Information

Version with issue: 16.3.0.278
IDE: VS Community 2019 16.3.8
Reproduction: see attachment, or create blank project from template, and follow steps above.

**Comment by VladislavAntonyuk** [comment]
it is not the issue of Xamarin.Forms. it should be additional step in VS build/deploy pipeline which checks if app is installed on device

**Comment by XavierAP** [comment]
> it is not the issue of Xamarin.Forms. it should be additional step in VS build/deploy pipeline which checks if app is installed on device

Ah, sorry. Do you know the project where I can report it?

**Comment by XavierAP** [comment]
Reported to xamarin-android:
https://github.com/xamarin/xamarin-android/issues/3946
