### ISSUE TITLE
[Bug] FontImageSourse doesn't work on GTK

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Xamarin.Forms#8593]
### Description ###

Using a FontImageSource on a project that is started with a GTK frontend the image or imagebutton control don't display the symbol

### Steps to Reproduce ###

Put an imagebutton control in a page and use a fontimagesource as the source of the image

### Expected Behavior
The symbol is displayed

### Actual Behavior
The symbol is not displayed

### Basic Information
Version with issue:
4.2.0.709249
IDE:
Visual studio 2019
Platform Target Frameworks:
GTK

**Comment by VladislavAntonyuk** [comment]
Similar issue for macOS #8469

**Comment by jfversluis** [comment]
I think it was simply never implemented :) 

Are you going to make a PR for this just like the MacOS one?

**Comment by VladislavAntonyuk** [comment]
@jfversluis working on it, I am going to create a pull request in the evening

**Comment by jfversluis** [comment]
No worries! I didn’t want to rush you :)

Keep up the great work!
