### ISSUE TITLE
[Spec]  Add Loaded/Unloaded to VisualElement

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#8596]
# Loaded and Unloaded 

This is a subitem based on the following spec
https://github.com/xamarin/Xamarin.Forms/issues/2210

One of the main reasons we didn't merge
https://github.com/xamarin/Xamarin.Forms/pull/3214

Was due to a change in how we want the the Appearing/Appeared/Disappearing/Disappeared methods implemented.

Reviewing through the PR I feel like the work done there for *Loaded/Unloaded* is valid but we should double check if the events that are being used work for our intent. 

# API

## These are already part of the PR
 - event VisualElement.Loaded;
 - event VisualElement.Unloaded;

### Events to Platform Mappings
*Below is how these properties are currently implemented on @paymicro's PR*

If we vet that the event strategy he used is the one we want to stick with then we should pull out the Loaded/Unloaded parts of his PR and get it merged

- OnLoaded/ViewDidLoad doesn't technically mean visible or appeared on the screen it just means it's ready. GlobalLayout on android means visible so should loaded be fired a little earlier? Or does the concept achieved by Loaded still work? 

#### Android

| API | Description |
| ------------- | ------------- |
| [Loaded] | [ViewTreeObserver.GlobalLayout] |
| [Unloaded] | [OnViewDetachedFromWindow] |

#### iOS

| API | Description |
| ------------- | ------------- |
| [Loaded] | [MovedToWindow/ViewDidLoad] |
| [Unloaded] | [MovedToWindow/Dispose] |

#### UWP

| API | Description |
| ------------- | ------------- |
| [Loaded] | [OnLoaded] |
| [Unloaded] | [OnUnloaded] |

# Difficulty : medium

**Comment by bruzkovsky** [comment]
Great proposal! 👏

How will this behave for views inside a `CollectionView`? We are currently evaluating migrating from `ListView` and we need the cells' `OnAppearing` and `OnDisappearing` events. Would `Loaded` and `Unloaded` be called on items in a `CollectionView` when it is created, or recycled, or scrolled into/out of the view? Could there be a test case to ensure that it behaves consistently?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
