### ISSUE TITLE
DataTrigger changes to TextColor when using Visual="Material" doesn't work on Entry in IOS

### ISSUE THREAD

**Issue by burrowj** [xamarin/Xamarin.Forms#8597]
DataTrigger changes to TextColor when using Visual="Material" doesn't work on Entry

### Steps to Reproduce
`<Entry Text="{Binding EntryText}" Visual="Material">
            <Entry.Triggers>
                <DataTrigger TargetType="Entry" Binding="{Binding HasErrors}" Value="True">
                    <Setter Property="TextColor" Value="Red" />
                </DataTrigger>
                <DataTrigger TargetType="Entry" Binding="{Binding HasErrors}" Value="False">
                    <Setter Property="TextColor" Value="Black" />
                </DataTrigger>
            </Entry.Triggers>
</Entry>`

### Expected Behavior
Should change color to red when HasErrors changes from False to True

### Actual Behavior
Trigger does not change TextColor.  It does change all other properties and it works when Visual="Default"
### Basic Information

- Version with issue:
Xamarin Forms 4.3.0.991211
IOS 13.2

**Comment by samhouts** [comment]
@burrowj  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by burrowj** [comment]
[TextColor.zip](https://github.com/xamarin/Xamarin.Forms/files/3889510/TextColor.zip)

**Comment by jfversluis** [comment]
Confirmed that this shows. When you remove the `Visual="Material"` from the `Entry` it works as intended.

**Comment by burrowj** [comment]
Using this same project I provided I also found a bug on Android.  The background color of the Material Entry stays red and does not go back to its original color when triggered back to it's original state

**Comment by burrowj** [comment]
Sorry to clarify this.  Under the Material Theme, when you change the TextColor to red it shades the background color to a pink shade.  This shade does not return to its normal state when the data trigger returns TextColor to it's original state.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/5714

**Comment by burrowj** [comment]
Thanks for this
