### ISSUE TITLE
[Bug] [WPF] Scrolling in horizontal direction using ScrollToAsync method doesn't work

### ISSUE THREAD

**Issue by Muthukumaran-G** [xamarin/Xamarin.Forms#8598]
# Description

 We have noticed that **ScrollToAsync** method doesn't work for horizontal scrolling. We have attached a simple sample for your reference. In our sample we have a ScrollView whose ScrollOrientation is set a 'Both'. It has a scrollable content in horizontal direction. We have passed a new 'X' offset value in ScrollToAsync method using a button clicked event. It doesn't scroll to the specified position in both animated and animated mode. The same scenario works fine in UWP platform. 

Can you please provide us an workaround or suitable solution as soon as possible? 

### Steps to Reproduce

1. Run the attached sample in WPF platform.
2. Click the button.

### Expected Behavior

Note that the ScrollViewer doesn't scroll to the specified X position.
 
### Actual Behavior

The ScrollViewer should scroll to its specified X position.

### Basic Information

- Version with issue: Latest - 4.4.0.991210-pre2
- Last known good version: None
- Platform Target Frameworks: WPF

### Reproduction Link

[HorizontalScrollToAsyncIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3873212/HorizontalScrollToAsyncIssue.zip)

**Comment by gsgou** [comment]
I am noticing this also in Android and iOS.
