### ISSUE TITLE
Change Placeholder Color 

### ISSUE THREAD

**Issue by BalsamIbrahim** [xamarin/Xamarin.Forms#8601]
i want to change placeholder color from gray to black
i use TitleColor="Black" but not work
i don't know why not work it code
can you help me please
this all picker disabled

![Screenshot_20191121-102449](https://user-images.githubusercontent.com/34779906/69320156-49e34b00-0c49-11ea-877b-ff7e4346cc9c.jpg)

> VS bug [#1025907](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1025907)

**Comment by StephaneDelcroix** [comment]
I'm not sure I understand what you want. could you please attach a sample project reproducing the issue ?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
