### ISSUE TITLE
[Bug] [IOS] CollectionView scroll to start/center when width of cell change

### ISSUE THREAD

**Issue by MiloszPawlowski** [xamarin/Xamarin.Forms#8603]
Only iOS - CollectionView scroll to start/center when width of cell change (after tap for example) and when grid and when column width is set to auto. With constant width it works proper.

### Steps
1. Add Grid in DataTemplate in CollectionView
2. Set ItemsLayout as HorizontalList
3. Add one column with auto width
4. Add label to Grid in DataTemplate
5. Add about 10 items to ItemSource
6. Add behavior to change label font size after tap on item
7. Scroll to last item and tap on item. 
8. Item is selected, size of label change, but collection scroll to center of collection

### Expected Behavior
Scroll stay on selected item

### Actual Behavior
Scroll move to start/center of collection

### Basic Information

- Version with issue:
- IDE: Visual Studio 16.3.9
- iOS:  13.2.3
- Nuget Packages: Xamarin.Forms 4.4.0.991210-pre2
- Affected Devices: all iOS devices

### GIF
![ezgif-6-eb9e4792efc0](https://user-images.githubusercontent.com/28765833/69331013-51f4b800-0c54-11ea-9a85-7cc10f218456.gif)

**Comment by samhouts** [comment]
@MiloszPawlowski  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@MiloszPawlowski  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
