### ISSUE TITLE
[Bug] CollectionView header not adapting to change in height on iOS

### ISSUE THREAD

**Issue by jemunk** [xamarin/Xamarin.Forms#8605]
### Description
If the CollectionView header (not groupheader) has an StackLayout including an item which is having its IsVisible property changed to false. Then the header does not reduce its height. 
This is only for iOS. Android works perfect.

### Steps to Reproduce

```
<DataTemplate x:Key="Header">
	<StackLayout> 
		<ContentView IsVisible="{Binding ShowHeader}">
			<Label Text="My header" />
		</ContentView>
	</StackLayout>
</DataTemplate>

<CollectionView ItemsSource="{Binding Items}"
				ItemTemplate="{StaticResource myItemTemplateSelector}"
				HeaderTemplate="{StaticResource Header}"
				Header="{Binding .}">
</CollectionView>
```

### Basic Information

- Version with issue: XF 4.3 SR 2
- Platform Target Frameworks: 
  - iOS:  13.2

**Comment by samhouts** [comment]
@jemunk  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by Jayaram-ces** [comment]
I am facing the same issue on iOS. Android it works fine.

Sample : https://github.com/Jayaram-ces/CollectionViewHeaderTemplateHeightIssue

I am open to any workaround also. Please suggest a fix.

Thanks in advance.

**Comment by Jayaram-ces** [comment]
Created a new bug also.
