### ISSUE TITLE
[Bug] CarouselView PeekAreaInsets give an empty spaces - iOS only

### ISSUE THREAD

**Issue by georgemichailou** [xamarin/Xamarin.Forms#8615]
I working with the Xamarin Forms 4.3.0.991211.

I tried the CarouselView control but i get the following results if i use the PeekAreaInsets property.

```
        <CarouselView ItemsSource="{Binding Items}"
                      PeekAreaInsets="80">
           <CarouselView.ItemsLayout>
                <LinearItemsLayout 
                    Orientation="Horizontal" 
                    SnapPointsAlignment="Center" 
                    SnapPointsType="MandatorySingle"/>
            </CarouselView.ItemsLayout>
            <CarouselView.ItemTemplate>
                    <DataTemplate>
                        <StackLayout>
                            <ffimageloading:CachedImage
                                LoadingPlaceholder="placeholder.png"
                                RetryCount="2"
                                RetryDelay="250" 
                                HorizontalOptions="FillAndExpand"
                                VerticalOptions="FillAndExpand"
                                Source="{Binding}"
                                Aspect="AspectFill"/>
                        </StackLayout>
                    </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
```

I get an empty space before the first item.

![Screenshot 2019-11-21 at 21 21 34](https://user-images.githubusercontent.com/14372162/69370566-db34da80-0ca6-11ea-9077-b42188d7a266.png)

```
                <LinearItemsLayout 
                    Orientation="Vertical" 
                    SnapPointsAlignment="Center" 
                    SnapPointsType="MandatorySingle"/>
```

I get an empty space before the first item.

![Screenshot 2019-11-21 at 21 20 14](https://user-images.githubusercontent.com/14372162/69370571-dcfe9e00-0ca6-11ea-917a-05e56c28a836.png)

I don't get this spaces on Android !!!

Here is my repo  https://github.com/georgemichailou/Xamarin-Galleries
(it's horizontal and vertical gallery)

**Comment by PureWeen** [comment]
@jsuarezruiz  ?

**Comment by jsuarezruiz** [comment]
We have a different behavior when using `PeekAreaInsets` on Android and iOS.
In iOS we always position each element in the center. For that reason, we leave space to the left of the first element or to the right of the last in some cases.
On Android, `PeekAreaInsets` is not adding that space to the beginning or the end.

I have a branch where we apply the same Android behavior on iOS. However, after talking with @rmarinho we have will have the following behavior:
- I have applied changes in this PR https://github.com/xamarin/Xamarin.Forms/pull/8733 and the behavior in Android will be the same as in iOS. That is, in the CarouselView we always center the elements and therefore that spacing will be added depending on the value of `PeekAreaInsets`.
- Using CollectionView with Snap options you can achieve a similar result without always centering the elements.

**Comment by georgemichailou** [comment]
Ok , I understand the differences. But I believe that iOS must be the same as Android.  If i use the CarouselView, do always the elements have center alignment ?

**Comment by rmarinho** [comment]
@georgemichailou yes they will. @jsuarezruiz just made a fix to make sure the same behavior on both platforms. If you want them to go to the left instead of center you could use CollectionView with snap and set a width to the item. that's less than the viewport.

**Comment by JunkyXL86** [comment]
> @georgemichailou yes they will. @jsuarezruiz just made a fix to make sure the same behavior on both platforms. If you want them to go to the left instead of center you could use CollectionView with snap and set a width to the item. that's less than the viewport.

Sorry for reopening this but what is the point of the CarouselView when we should mimic the behavior using the CollectionView? 
Next, what is the point of the SnapPointsAlignment property if setting start/end does not have an effect for the first/last item?
