### ISSUE TITLE
[Bug] NuGet version conflict between Xamarin.Froms.Maps and Microsoft.AppCenter.Push

### ISSUE THREAD

**Issue by BRB2000** [xamarin/Xamarin.Forms#8633]
If you have a Xamarin Forms app, and add  the packages Xamarin.Froms.Maps and Microsoft.AppCenter.Push through NuGet, you get a version conflict regarding Xamarin.GooglePlayServices.Base.

`App.Android -> Microsoft.AppCenter.Push 2.6.1 -> Xamarin.Firebase.Messaging 71.1740.0 -> Xamarin.Firebase.Iid 71.1710.0 -> Xamarin.Firebase.Iid.Interop 71.1601.0 -> Xamarin.GooglePlayServices.Base (>= 71.1610.0) 
 App.Android -> App -> Xamarin.Forms.Maps 4.3.0.991211 -> Xamarin.GooglePlayServices.Maps 60.1142.1 -> Xamarin.GooglePlayServices.Base (= 60.1142.1).`

**Comment by StephaneDelcroix** [comment]
could you please attach a repro project ? thanks

**Comment by BRB2000** [comment]
[ReproNuGetVersionConflict.zip](https://github.com/xamarin/Xamarin.Forms/files/3886133/ReproNuGetVersionConflict.zip)

**Comment by BRB2000** [comment]
Please try to update the AppCenterPush NuGet on the .Droid project.

**Comment by dansiegel** [comment]
@StephaneDelcroix I've run into this myself... I believe the only thing that really has to be done here is for Xamarin.Forms.Maps on Android reference the newer GooglePlayServices package.

**Comment by jfversluis** [comment]
Opened a PR for this. You should easily get around this for now by installing the right GooglePlayStore package version by hand.

**Comment by peter-raehse** [comment]
> You should easily get around this for now by installing the right GooglePlayStore package version by hand.

@jfversluis Sorry that I have to ask: how can I do this the right way? If I remove Xamarin.Forms.Maps and update the Microsoft.AppCenter I can't install the recent version of Maps because of the version conflict and vice versa. Thanks!

**Comment by noxe** [comment]
Is there any Info when this will be available / in which version?
