### ISSUE TITLE
[Bug] Android animation issue when device animations are turned off

### ISSUE THREAD

**Issue by Russc0** [xamarin/Xamarin.Forms#8634]
### Description
Open device Android settings, open Developer Menu, turn off animations.
App animations (eg. view.TranslateTo(0,0)) causes app to freeze.
This also happens if you open Android settings and turn on "Reduce animations" on Samsung devices.

### Steps to Reproduce

1. Turn off animations in device Developer menu
2. Do any view animation such as .TranslateTo or .ScaleTo etc

### Expected Behavior
With animations turned off I would expect the animation to be skipped.

### Actual Behavior
App freezes

### Basic Information

- Version with issue: All
- Last known good version: Unknown
- IDE: VS 2019
- Platform Target Frameworks:
  - Android: 7 and 8
- Nuget Packages: Latest
- Affected Devices:
I suspect all Android devices. Definitely Samsung devices.

**Comment by jfversluis** [comment]
Thanks for reporting this @Russc0 

This looks an awful lot like #7500 can you confirm that? If so, would you mind closing this one and follow the progress there? Maybe update the issue with some of your own findings? Thanks!
