### ISSUE TITLE
[Bug] Android CollectionView exception

### ISSUE THREAD

**Issue by stesvis** [xamarin/Xamarin.Forms#8637]
### Description
I get an exception when I use `.Remove(item)` on the ItemsSource of a CollectionView.

### Steps to Reproduce

1. Create a CollectionView and bind the ItemsSource to a ObservableCollection `<CollectionView ItemsSource="{Binding Vehicles}">`
2. Programmatically remove an item from the collection `Vehicles.Remove(vehicleToRemove);`
3. It throws the exception

### Actual Behavior
System.ObjectDisposedException
  Message=Cannot access a disposed object.
Object name: 'Xamarin.Forms.Platform.Android.GroupableItemsViewAdapter`2[[Xamarin.Forms.GroupableItemsView, Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null],[Xamarin.Forms.Platform.Android.IGroupableItemsViewSource, Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]]'.

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: N/A
- IDE: VS 2019 for Windows
- Android: 9

**Comment by VladislavAntonyuk** [comment]
Make sure you call it on UI thread. The PR is in progress

**Comment by VladislavAntonyuk** [comment]
https://github.com/xamarin/Xamarin.Forms/pull/8568

**Comment by stesvis** [comment]
It still crashes on me like this:
`Device.BeginInvokeOnMainThread(() => Vehicles.Remove(vehicleToRemove));`

**Comment by samhouts** [comment]
@stesvis  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by stesvis** [comment]
Hello @samhouts  can you try the one I have attached?
After log in, go to the Inventory tab, click one of the camera icons and scan this barcode:
![pasted-image-0-1](https://user-images.githubusercontent.com/6062684/69837429-00c46580-120c-11ea-892a-3e170b683b9b.png)

[levitica-organeyes-scanner-6536d4cb0ca4.zip](https://github.com/xamarin/Xamarin.Forms/files/3903361/levitica-organeyes-scanner-6536d4cb0ca4.zip)

It crashes on:
```
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        // clear the list and only add the one found
                        InventoryItems.Clear();
                        InventoryItems.Add(item);
                    });
```

**Comment by dblookup** [comment]
Please try with version 4.3.0.991221 released two days ago. In my case, this solves the issue.

**Comment by PureWeen** [comment]
Can you let us know if what @dblookup says is correct @stesvis ? 

Can you test this with the latest 4.4 pre and/or nightly? https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

**Comment by samhouts** [comment]
@stesvis  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
