### ISSUE TITLE
[Bug] CarouselView inconsistent layout positioning

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#8638]
### Description

I have the following layout using the `PeekAreaInsets`:

```
<CarouselView 
            PeekAreaInsets="40"
            ItemsSource="{StaticResource Banners}" 
            Position="3">
            <CarouselView.ItemsLayout>
                <LinearItemsLayout Orientation="Horizontal"
                                   SnapPointsAlignment="Center"
                                   SnapPointsType="MandatorySingle"
                                   ItemSpacing="8"/>
            </CarouselView.ItemsLayout>
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <Image Source="{Binding .}"/>
                </DataTemplate>
            </CarouselView.ItemTemplate>
        </CarouselView>
```

### Expected Behavior

The centered item is always positioned in the center.

### Actual Behavior

On the first item and the last item, the layout differs. See images.

I get why the layout is doing this as there is no item to consume the 40 inset and so I only get an 8 padding (if I'm interpreting correctly). How can I achieve the consistent layout I want?

Slightly related, what I ACTUALLY want is an carousel that loops, and thus there would ALWAYS be a left and right, prev and next, image. I'll file another issue to track that.

### Basic Information

- Version with issue: 4.4.0-pre3
- Platform Target Frameworks: 
  - Android: 10

### Screenshots

Centered as expected:

![image](https://user-images.githubusercontent.com/41873/69501167-e0bd3b00-0ec7-11ea-8bc5-193d176c09b4.png)

First item, not centered. The margins on the left and right should be consistent with the above image. I expect the positioning to be consistent no matter what item I'm on. There should be 40 + 8 padding to the left.

![image](https://user-images.githubusercontent.com/41873/69501176-faf71900-0ec7-11ea-9c07-4c17a87c0c49.png)

Last item, not centered. Again, I expect consistent layout. There should be 40 + 8 padding to the right.

![image](https://user-images.githubusercontent.com/41873/69501189-17935100-0ec8-11ea-8ebf-d441a355800a.png)

### Reproduction Link

https://github.com/davidortinau/FlyMe/blob/bug/carousel_peek_layout/FlyMe/FlyMe/Views/MyFlightsPage.xaml#L18

**Comment by davidortinau** [comment]
Example from the original set of samples: 
![image](https://user-images.githubusercontent.com/41873/69503263-6f888280-0edd-11ea-8d11-2c1b57b53dc2.png)

**Comment by jfversluis** [comment]
Yep, agreed. Even if there is no looping it makes sense to keep the first and last item centered so they should have some padding/inset/whatever. Happens on both iOS and Android.
