### ISSUE TITLE
[Bug] CarouselView doesn't loop

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#8641]
### Description

CarouselView needs to support looping for infinite scrolling through the items source. 

### Expected Behavior

Whether swiping left or right, you can just keep going and going. This should work with peek insets, side items, etc. 

### Actual Behavior

Cannot loop. It requires writing looping hacks (duplicating items, and adjusting the position based on custom logic).

### Basic Information

- Version with issue: 4.4.0-pre2
- Platform Target Frameworks: 
  - Android: 10

### Screenshots

https://www.screencast.com/t/bRbkqTUI

**Comment by jfversluis** [comment]
Was part of the original spec #4996 but isn't implemented yet.

**Comment by vecalion** [comment]
I wonder if there are any updates on this item?

**Comment by rmarinho** [comment]
is we have the feature ready to be tested by the community :

if you want you can grab the nuget to test it here

https://dev.azure.com/xamarin/public/_build/results?buildId=21519&view=artifacts&type=publishedArtifacts

**Comment by ccsousa01** [comment]
Using 5.0.0.1558-pre3. Loop performs well on Android and completely freezes on iOS, at least v14.

**Comment by kunalkumavat** [comment]
To Solve above issue for looping in carouselview Simply Use Xamarin forms 5.0. After updating to the latest version your issue will be resolved automatically. I also did the Same.

Thank me Later :)
