### ISSUE TITLE
[Bug] Android CarouselView skipping over views

### ISSUE THREAD

**Issue by InquisitorJax** [xamarin/Xamarin.Forms#8643]
### Description
When binding to position in the view model, and swiping on android, the carousel view will sometimes skip over views when swiping

### Steps to Reproduce
1. Clone https://github.com/InquisitorJax/TravellingApp
2. Run the App on android, and activate the social tab
3. Swipe to 2nd image, then swipe back to first image.
4. Press the "move to 4" button - which activates the 4th image
5. Now attempt to swipe back to the 3rd image: the Carousel view skips everything and goes back to the first image

### Expected Behavior
The view should only swipe from the 4th to the 3rd image in step 5.

### Basic Information

- Version with issue: latest
- Last known good version:
- IDE: VS for Windows (latest)
- Platform Target Frameworks: 
  - Android: API 28

**Comment by jfversluis** [comment]
I don't see it go back all the way to the first image, but there is something funny going on.

If you look closely at this screen capture, you will see that when I scroll back after "move to 4" you will see a small link of the second item. It looks like the snapping is confused after you navigate to item 4.

![Untitled](https://user-images.githubusercontent.com/939291/69550159-d28c1f00-0f9a-11ea-9173-4fbcb7326e89.gif)

**Comment by rmarinho** [comment]
Hi @InquisitorJax this is fixed in the latest 4.5.0 release https://www.nuget.org/packages/Xamarin.Forms/4.5.0.495 

Thanks
