### ISSUE TITLE
[Bug] WebView in Platform.wpf

### ISSUE THREAD

**Issue by zaratul77** [xamarin/Xamarin.Forms#8650]
### Description

The function EvaluateJavaScriptAsync is not working for webview Control in WPF

### Steps to Reproduce

1. Create Webview
2. Use function var result = await WebView.EvaluateJavaScriptAsync("2+2") e.g. on ButtonClick;

### Expected Behavior
result = 4 (Works on Android)

### Actual Behavior
Is always null
### Basic Information

- Version with issue:  4.3.0
- Last known good version: -
- IDE:
- Platform Target Frameworks: 
  - WPF:  Error
  - Android: Working

**Comment by maxim-saplin** [comment]
Assuming WebView is eventually replaced with a newer version this issues might be resolved automatically. https://github.com/xamarin/Xamarin.Forms/issues/10719

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
