### ISSUE TITLE
Shell: If you have multiple links in your tree with the same navigation links on that will fail to resolve even if absolute pathed.

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/Xamarin.Forms#8651]
#8445 # Description
Right now the Shell control only allows a route to be defined once. There doesn't appear to be any way to define the same route twice because you want it accessible from your UI in multiple places. When you attempt to duplicate the same route, links from that route fail to work even if you use absolute paths.

### Steps to Reproduce

1. Create a shell app
2. Add the same route twice to the same page
3. Add a link on that page that goes to a second page with a route that you've registered manually.
4. Run and click link on page with the duplicate route. You'll get a "ambiguous route error" even though the page that it's linking to only has a single route. (interestingly the original doubled item has no problem resolving.

### Expected Behavior

The routing engine should dedupe and only add a route a second time if it's actually different and should throw an error if the same route is added with a different type.

### Actual Behavior

links on double routed page (same route definition defined multiple times) throw ambiguous route error but allow doubled route page.

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: Never
- IDE: VS.net 2019 16.3.10
- Platform Target Frameworks: All
- Android Support Library Version: 28.0.0.3
- Affected Devices: All

In general I should also be able to put an absolute path on sub items as well to override the automatic pathing so if I have:

FlyoutItem Route = "Dashboard"
          Tab Route = "//library"

It should make the route to the tab //libarry and override the relative pathing.  This should be true anywhere that // is used just like the same in HTML pages. Right now it either errors or forces the relative pathing on it anyhow.

Here's my structure:

FlyoutItem Route = "Dashboard" Title="Dashboard"
      Tab Route = "library" Title = "Library"

FlyoutItem Route = "Dashboard/library" Title="Library"

Then I have a manually added route to //library/lesson. If I am on //dashboard/library in this case i get the ambiguous route because apparently //library/lesson is in the route table twice.

Even if I change the manually added route to //lesson I'll still get the error. If I remove the manually added route, then I get a route not found error.

**Comment by samhouts** [comment]
@JohnGalt1717  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
