### ISSUE TITLE
Blank Space in TabbedPage Xamarin.iOS 13

### ISSUE THREAD

**Issue by pdamco** [xamarin/Xamarin.Forms#8659]
Blank Space is showing after installing Xamarin.iOS 13. This is working fine with Xamarin.iOS 12 till now.

Attached is the image.
![Screenshot 2019-11-25 at 11 25 50 PM](https://user-images.githubusercontent.com/40819488/69565717-90370200-0fdb-11ea-9cf1-90bec6f467af.png)

**Comment by pdamco** [comment]
Version with issue:

Last known good version: iOS 12 | Xamarin.iOS 12

IDE: VS Mac 8.3.10

Platform Target Frameworks:

iOS: 11.2
Android: 10
Nuget Packages: 3.4

Affected Devices: iOS

XF version is 3.4 but i have tryed to upgrad to 4.3 nothing happened same space is showing.
iOS version is 13
This is only on iOS not happening on Android.

**Comment by Char0394** [comment]
Hi, 
I'm having this same issue, any estimation of when it will be fixed?

**Comment by samhouts** [comment]
@pdamco @Char0394  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by KevinAnass** [comment]
does anyone solve this white space issue

**Comment by rickclephas** [comment]
@samhouts this issue hasn't been fixed. See #14239 for a sample and some "workarounds".
