### ISSUE TITLE
[Enhancement] Don't write to Application.Properties if nothing has changed

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#8661]
# Description

Forms will load the Application.Properties data from storage at application startup and will write it out when backgrounding/exiting. It will do this even if the application has never written any information to Application.Properties. 

This currently causes issues for multi-instance applications (see #8421) even if they do not use Application.Properties at all. And it adds extra overhead to backgrounding/exiting. We should be able to marked the properties as modified when they are written to, and avoid the extra overhead if they have not been changed.

Additionally, we should verify that we aren't loading the properties at all unless/until they are requested by the application.

While this won't fix #8421, it will prevent it from being a problem for users who don't make use of the Application.Properties feature.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
