### ISSUE TITLE
Activity indicator does not scale to bounds on iOS

### ISSUE THREAD

**Issue by Happypig375** [xamarin/Xamarin.Forms#8668]
### Description
https://stackoverflow.com/questions/52723072/resizing-activity-indicator-in-xamarin-forms
### Steps to Reproduce

Try to give an ActivityIndicator a large layout bounds, and discover that the indicator is still tiny.
```xaml
    <AbsoluteLayout>
        <ActivityIndicator HorizontalOptions="FillAndExpand"
                           VerticalOptions="FillAndExpand"
                           IsRunning="True"
                           Color="Red"
                           BackgroundColor="Blue"
                           AbsoluteLayout.LayoutBounds="100,100,300,300" />
    </AbsoluteLayout>
```
### Expected Behavior
At least supporting automatic scaling up like on Android.
### Actual Behavior
It seems sizing itself is not supported on the ActivityIndicator. 
### Basic Information

- Version with issue: 3.2, 4.3
- Last known good version: Idk
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS: 13

### Screenshots
![image](https://user-images.githubusercontent.com/19922066/69627201-2bd07d00-1085-11ea-853f-89efc7ad5f20.png)

### Reproduction Link
[Xamarin.zip](https://github.com/xamarin/Xamarin.Forms/files/3891676/Xamarin.zip)

**Comment by jfversluis** [comment]
Thank you for reporting this @Happypig375 and thank you so much for your great reproduction, much appreciated!

Unfortunately, the native counterpart `UIActivityIndicatorView` [cannot resize](https://stackoverflow.com/questions/56830645/how-to-increase-the-size-of-the-activity-indicator), that is probably why it wasn't implemented in Xamarin.Forms.

What you can do is set the `ActivityIndicator.Scale`, which is basically the solution that is mentioned in the StackOverflow answers from the link above and the StackOverflow question you linked in the description yourself.

Does that help you? Or, seeing that you are a contributor yourself, do you have any other suggestions on how we might solve this?

Thanks!

**Comment by Happypig375** [comment]
Will a new iOS-specific boolean property `ScaleToBounds` suffice?

**Comment by jfversluis** [comment]
So, that would be a boolean specific to iOS and the `ActivityIndicator`. When flipped on it will take up all the space until it hits the bounds? 

I think that sounds reasonable.
