### ISSUE TITLE
[Bug] An element with the name ... already exists in this NameScope

### ISSUE THREAD

**Issue by simspace-dev** [xamarin/Xamarin.Forms#8675]
I am experiencing this error consistently. My element is most definitely defined just once in the XAML and referenced twice in the code-behind. Even with this error, the app runs fine. 

This screenshot show the errors, the element definition (`myTestLabel`) and the search results for the string `myTestLabel` within the whole solution.    

![image](https://user-images.githubusercontent.com/4808756/69646793-09f7db80-102e-11ea-877f-afcbd3fc6dab.png)
 
Here's what I experienced, though not sure what it means yet ...

1.  I changed the elements `x:Name` from `MyTestLabel` to `dog` ... 
    **no error**.
2. I changed the elements `x:Name` from `dog` to `catt` ... 
    **no error**.
3. I changed the elements `x:Name` from `catt` back to `dog` and 
    **I get the error** `An element with the same key already exists in NameScope`.
4. I changed the elements `x:Name` from `dog` back to `catt` and 
    **I get the error** `An element with the same key already exists in NameScope`.
5. I save the project with the  elements `x:Name` as `catt` and I restart Visual Studio ... 
    **no error**. 

I am using Visual Studio 2019 for Mac and Xamarin.Forms v4.3.0.991211

**Comment by samhouts** [comment]
@simspace-dev  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by simspace-dev** [comment]
I'm learning Xamarin going through some MS tutorials online. 

You can clone the following repo to get the project I created which is where I am experiencing the issue described above:

https://github.com/simspace-dev/GridTutorial.git

**Comment by jfversluis** [comment]
Thanks @simspace-dev! Unfortunately I am not able to reproduce this behavior.

I pulled down the code, renamed the control a couple of times like you mentioned and then built the Android project but I don't see the error you are seeing. Am I overlooking something? What version of VSMac are you using?

**Comment by StephaneDelcroix** [comment]
this issue hapenned at some point in 4.1 or 4.2, but should be long solved in 4.3

@simspace-dev  please attach a project triggering the issue.

**Comment by simspace-dev** [comment]
> Thanks @simspace-dev! Unfortunately I am not able to reproduce this behavior.
> 
> I pulled down the code, renamed the control a couple of times like you mentioned and then built the Android project but I don't see the error you are seeing. Am I overlooking something? What version of VSMac are you using?

Strange. I can reproduce this every time. This is the VSMac version:
![image](https://user-images.githubusercontent.com/4808756/69990723-e9d38b00-150b-11ea-9b34-c27315f6a2b1.png)

**Comment by simspace-dev** [comment]
> this issue hapenned at some point in 4.1 or 4.2, but should be long solved in 4.3
> 
> @simspace-dev please attach a project triggering the issue.

The project is too large to attach. You can clone the following repo to get the project  where I am experiencing this issue: https://github.com/simspace-dev/GridTutorial.git

**Comment by PureWeen** [comment]
@simspace-dev  these are the steps to follow to trigger the error correct?
```
I changed the elements x:Name from MyTestLabel to dog ...
no error.
I changed the elements x:Name from dog to catt ...
no error.
I changed the elements x:Name from catt back to dog and
I get the error An element with the same key already exists in NameScope.
I changed the elements x:Name from dog back to catt and
I get the error An element with the same key already exists in NameScope.
I save the project with the elements x:Name as catt and I restart Visual Studio ...
no error.
```

I tested this on 8.4  (which is in public preview) and I didn't have any issues

Can you try 8.4 see if you have the same issue? If so can you attach a short gif just so we can make sure we're following the steps correctly?

**Comment by simspace-dev** [comment]
@PureWeen, I can give that a try. I will let you know how it works out.

**Comment by samhouts** [comment]
@simspace-dev Thanks, we'll wait to hear from you.

**Comment by samhouts** [comment]
@simspace-dev  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by thajb** [comment]
I have the same issue
