### ISSUE TITLE
OnPlatform doesn't work for iOS simulator

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8677]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/588658/onplatform-doesnt-work-for-ios-simulator.html)._

---
I'm following this Xamarin Microsoft Learn Tutorial: https://docs.microsoft.com/en-us/learn/modules/create-ui-in-xamarin-forms-apps-with-xaml/index

The code where the issue is reproducible is here:
https://github.com/MicrosoftDocs/mslearn-create-ui-in-xamarin-forms-apps-with-xaml/blob/master/src/exercise1/final/Phoneword/Phoneword/MainPage.xaml

The issue is that the OnPlatform attribute does not work for the iOS simulator (assuming it works for the real device, but haven't been able to check). It does work for the Design preview in Visual Studio though.

Example:
```
<ContentPage.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <On Platform="iOS">0,200,0,0</On>
        </OnPlatform>
</ContentPage.Padding>
```

On the iOS simulator, the padding is not adjusted (the views overlap the status bar at the top of the screen). In the Design preview, the padding is adjusted (the views show up in the middle of the screen).

Working on a PC using the remote simulator.

>Microsoft Visual Studio Community 2019
>Version 16.1.1
>VisualStudio.16.Release/16.1.1+28922.388
>Microsoft .NET Framework
>Version 4.7.03056

>Installed Version: Community

>Azure App Service Tools v3.0.0   16.1.429.50124
>Azure App Service Tools v3.0.0

>C# Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
>C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

>Common Azure Tools   1.10
>Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

>Extensibility Message Bus   1.1.77 (master@24013d5)
>Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

>IntelliCode Extension   1.0
>IntelliCode Visual Studio Extension Detailed Info

>JetBrains ReSharper Ultimate 2019.1.1   Build 191.0.20190501.122851
>JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

>Microsoft JVM Debugger   1.0
>Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

>Microsoft MI-Based Debugger   1.0
>Provides support for connecting Visual Studio to MI compatible debuggers

>Mono Debugging for Visual Studio   16.1.1 (2473f22)
>Support for debugging Mono processes with Visual Studio.

>NuGet Package Manager   5.1.0
>NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

>ProjectServicesPackage Extension   1.0
>ProjectServicesPackage Visual Studio Extension Detailed Info

>ResourcePackage Extension   1.0
>ResourcePackage Visual Studio Extension Detailed Info

>ResourcePackage Extension   1.0
>ResourcePackage Visual Studio Extension Detailed Info

>Visual Basic Tools   3.1.0-beta4-19266-03+9d80dea7fe1b14043b9b2ac4d0b59ed26f508742
>Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

>Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
>Microsoft Visual F# Tools 10.4 for F# 4.6

>Visual Studio Code Debug Adapter Host Package   1.0
>Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

>VisualStudio.Mac   1.0
>Mac Extension for Visual Studio

>Xamarin   16.1.0.542 (d16-1@68b985244)
>Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

>Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
>Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

>Xamarin Templates   16.2.112 (4db4af4)
>Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

>Xamarin.Android SDK   9.3.0.22 (HEAD/8e7764fdf)
>Xamarin.Android Reference Assemblies and MSBuild support.
>    Mono: mono/mono/2018-08@3cb36842fc4
>    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
>    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
>    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
>    ProGuard: xamarin/proguard/master@905836d
>    SQLite: xamarin/sqlite/3.27.1@8212a2d
>    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

>Xamarin.iOS and Xamarin.Mac SDK   12.10.0.153 (750a879)
>Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

---
#### Visual Studio Feedback System on 5/30/2019, 01:34 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
I don't seem to have any issues with this working. Am I missing something?

![image](https://user-images.githubusercontent.com/939291/69741563-90e6aa00-113b-11ea-8b8c-901c8327e0bf.png)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
