### ISSUE TITLE
Xamarin.Forms webview 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#8681]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/832179/xamarinforms-webview.html)._

---
Xamarin.Forms webview 

After the webview to reload the OnBackButtonPressed does not perform

---
#### Visual Studio Feedback System on 11/24/2019, 10:46 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Asked for additional info and a reproduction in the feedback ticket since I can't find a corresponding user on GitHub.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
