### ISSUE TITLE
[Bug] [UWP] NullReferenceException when call SavePropertiesAsync method off the main thread

### ISSUE THREAD

**Issue by TomOnd** [xamarin/Xamarin.Forms#8682]
### Description

NullReferenceException is thrown in method Xamarin.Forms.Application.SavePropertiesAsync when called off the main thread. 

Xamarin.Forms.Application.Dispatcher property is null because method Xamarin.Forms.Platform.UWP.DispatcherProvider.GetDispatcher(object) returns null. If statement on line 22 in this method is evaluated as false.

Possible fix could be to remove return statement on line 32 in Xamarin.Forms.Platform.UWP.DispatcherProvider.GetDispatcher(object) method. Not tested.

[UwpDispatcherNullReference.zip](https://github.com/xamarin/Xamarin.Forms/files/3893354/UwpDispatcherNullReference.zip)

### Steps to Reproduce

See attachment - UwpDispatcherNullReference.MainPage.OnAppearing method.

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: Different exception in 4.3.0.947036. See bug #8167

**Comment by jfversluis** [comment]
Confirmed that this is happening in the reproduction.

If we implement the fix like suggested in the comment it will lead to #8420 so that is not the (complete) solution.

**Comment by samhouts** [comment]
closed by #8696
