### ISSUE TITLE
[Bug]  Margin of Contentview like Grid, or Stacklayout doesnt work  inside RefreshView 

### ISSUE THREAD

**Issue by WaiseFass** [xamarin/Xamarin.Forms#8689]
### Description
If you create for example a Grid inside a Refresh View, the Margin dosent work in the right way.

Currently I have only tested it on Android.. I check it on iOS asap.
### Steps to Reproduce

1.  Create a RefreshView
2.  Add a Grid inside
3.  Set the margin to "10,0,0,0"

### Expected Behavior
The control should have a margin only on the left side.

### Actual Behavior
The control has a margin on the right side..

### Workaround (see screenshot):
 add second Control inside the RefreshView:
RefreshView
   Grid
           Grid Margin="10,0,0,0"
            /Grid
  /Grid
/RefreshView

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0 (API 28) 
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
"Xamarin.Forms" Version="4.3.0.908675"
"Xamarin.Essentials" Version="1.3.1"
- Affected Devices:

### Screenshots

![actualBehavior](https://user-images.githubusercontent.com/40561661/69715368-6f1fff80-1108-11ea-96a7-4c25564d9cb0.PNG)

![expectedBehavior](https://user-images.githubusercontent.com/40561661/69715358-6af3e200-1108-11ea-8869-0a215e778b9c.PNG)

### Reproduction Link
https://github.com/WaiseFass/RefreshViewDemo

**Comment by jfversluis** [comment]
If you would be able to provide that reproduction, that would be awesome!

**Comment by WaiseFass** [comment]
Here you can find the source code for this example: https://github.com/WaiseFass/RefreshViewDemo

**Comment by jfversluis** [comment]
Thanks for the reproduction! Much appreciated!

On iOS it seems to work, do you see that as well @WaiseFass ?

Might be related to #8617

**Comment by WaiseFass** [comment]
yes on iOS it works (tested  on iOS Simulator)
