### ISSUE TITLE
[Enhancement] .net Core 3+ support and xaml editor plugin for vs code

### ISSUE THREAD

**Issue by cambo2015** [xamarin/Xamarin.Forms#8690]
## Summary
Xamarin for .net core would be an amazing addition to the xamarin community. Other frameworks like avelonia could surpass xamarin. Xamarin already has a big community and one would not have to learn another framewok. Additionally, a xaml editor for vs code would be needed so one could create apps easily on linux. 

## API Changes
In order to compile to .net core 3+ , a compiler for .net core 3+  should be added, so one could use .net core 3 libraries such as ML.Net and CLI templates for .net core 3 on linux. 
An added bonus would be to make an xaml editor extension for vs code so the need for vs studio and windows would not be mandetory and thus making apps with linux easy, cheap and pain free. 

## Intended Use Case
Could make .net core 3 gui apps for Linux using ml.net ,etc.

**Comment by VladislavAntonyuk** [comment]
you can build for Linux using GTK

**Comment by trampster** [comment]
I have been using Eto.Forms to target GTK linux from vscode. However I also want to target Android and Eto.Forms Android support is still 'in progress'. So I started a Xamarin.Forms version of my app. Now I have two cross platform UI frameworks each targeting a single platform :(

vscode support for Xamarin.Forms would allow me to drop Eto.Forms and develop and test with Xamarin.Forms GTK on target.

**Comment by jfversluis** [comment]
Unfortunately this won't be happening for Forms anymore. With .NET MAUI we get some VS Code support, although the best experience will probably still be in "full" Visual Studio. I think there is some suggestion for VS Code support in the .NET MAUI repo discussions, please add your voice there :)
