### ISSUE TITLE
A11y: TabIndex is ignored for first element on page for VoiceOver

### ISSUE THREAD

**Issue by jantanis** [xamarin/Xamarin.Forms#8691]
### Description
When setting all TabIndexes on the page. The first element on the page receives VoiceOver focus. Not the one with the lowest TabIndex. (Will start on NavigationBar if it is present.)

### Steps to Reproduce
1. Open attached solution
2. Run
3. Enable VoiceOver

### Expected Behavior
Voiceover starts on the element with the lowest TabIndex.

### Actual Behavior
The element on top of the page receives VoiceOver focus.

### Basic Information
- Version with issue: 4.3.0.991211
- Last known good version: N/A
- IDE: VS MAC 8.3.10.2
- Platform Target Frameworks: 
  - iOS:  11.2
- Affected Devices: iOS

### Reproduction Link
[A11Y.zip](https://github.com/xamarin/Xamarin.Forms/files/3897211/A11Y.zip)

**Comment by PureWeen** [comment]
This issue has been asked about in a few different ways. I think the useful thing here would be a way to articulate where the focus starts and not necessarily just use TabIndex. This is also relevant when navigating forward and back from a page
