### ISSUE TITLE
[Bug] IndicatorView template resets when data updates

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#8693]
### Description

All is well when first using the IndicatorView, but when my CarouselView's ItemsSource is updated the IndicatorView template reverts to the default dots.

Right:
![image](https://user-images.githubusercontent.com/41873/69758943-82da5e80-1126-11ea-9124-ee8f04cd17dd.png)

Wrong:
![image](https://user-images.githubusercontent.com/41873/69758972-908fe400-1126-11ea-9966-112d26a8230b.png)

Template:
https://github.com/davidortinau/WeatherColors/blob/bug/indicator-template/WeatherColors/WeatherColors/View/CityListPage.xaml#L71

### Steps to Reproduce

1. Click on one of the continents in the collection at the bottom. This updates the datasource bound to the Carousel. 

https://github.com/davidortinau/WeatherColors/blob/bug/indicator-template/WeatherColors/WeatherColors/ViewModel/MultiWeatherViewModel.cs#L158

2. Note the indicator template changed.

### Expected Behavior

Templates remain the same

### Actual Behavior

Reverts to default template

### Basic Information

- Version with issue: 4.4.0.*
- Platform Target Frameworks: 
  - Android: 9

### Screenshots

https://www.screencast.com/t/bxqGvHDMm

### Reproduction Link

https://github.com/davidortinau/WeatherColors/tree/bug/indicator-template

**Comment by jfversluis** [comment]
Confirmed with latest nightly. Happens on both Android and iOS.
On iOS the indicators disappear as a whole

**Comment by samhouts** [comment]
closed by #8709
