### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by pellet** [xamarin/Xamarin.Forms#8698]
Bringing this open ticket over from the xamarin forum since it is still an issue and getting constant crashes on xamarin forms 3.5.
Previous discussion about the same issue was here:
https://forums.xamarin.com/discussion/90940

Steps to Reproduce
Swipe down top nav bar while app is open.
Use buttons to change song playing.
Go back into app.
Expected Behavior
Actual Behavior
Version Information
Log File

**Comment by pellet** [comment]
I managed to fix this three year old bug in our app by doing the following:

            var formsAppDelegate = compositionRoot.ResolveApp();
            LoadApplication(formsAppDelegate);
            formsAppDelegate.MainPage = formsAppDelegate.MasterDetailPage;
Previously we would assign the mainpage in the constructor of the app class however on second time around of the MainActivity being created the constructor would not get called and therefore the mainpage would not be reassigned, this would cause a MasterDetailPageRenderer crash or a white screen. Assigning/re-assigning the mainpage always in the onActivityCreated delegate fixed this issue. I recommend updating your documentation so that android will behave more reliably for xamarin forms users.

**Comment by jfversluis** [comment]
Hi @pellet thanks for bringing this under our attention again.

Am I understanding correctly that this is an issue for you in 3.5? Is this still an issue in more recent versions? Would you be able to provide some more info as requested in the bug template including a descriptive title and reproduction project?

Thanks!

**Comment by pellet** [comment]
I'll try adding more info.  The current documentation is wrong in regards to this as in the way to hook up xamarin forms from a mainactivity.  I will assume the issue still exists in the most recent version of xamarin forms, I am unable to upgrade yet as I ran into some issue relating to KitKat but I can try upgrading the app again soon.

**Comment by pellet** [comment]
The crux of the issue here is that by the documentation standard and general design of xamarin forms MainActivity.OnCreate is expected to be called once per app lifetime, hence putting the initialization code into there.  It will however can be called multiple times, therefore calling the boilerplate hooks a second time, the app constructor will not be ran the second time around and the mainpage will not be set, this is why I removed the code to set the mainpage from the app constructor and put it into the mainactivity, so that the view will be assigned correctly not just on the first time OnCreate is called for the MainActivity.

**Comment by jfversluis** [comment]
> I will assume the issue still exists in the most recent version of xamarin forms

What is that assumption based on? There is _a lot_ or work done between 3.5 and 4.4 that is almost upon us. I totally understand where you are coming from and I want to help you, but it's a bit hard without any actual reproduction against the latest code. I hope that is something you can understand.

Based on this information it's a bit hard for me to see what you mean and how to reproduce this myself. I'll be happy to have a look once you can provide us with all the details in the bug report template and in this case I think more important than ever: a reproduction case.

**Comment by pellet** [comment]
The assumption is based on the most recent sample code and documentation, mainactivity oncreate is still incorrectly thought of as something which is only called once per app launch which is completely incorrect, it's an android platform fact.
I'll check out the latest xamarin forms sample project and see if I can figure out a way to demonstrate the issue for you.

**Comment by pellet** [comment]
I can't recreate the issue unfortunately I think it's a complex issue to reproduce.  The crashes I was getting in my app were related to the masterdetailpage renderer.  I think the xamarin documentation is actually ok because it is assigning the mainpage each time oncreate is called, because it reinitializes and reconstructs the app object each time the mainactivity is created(whether this is necessary or not is getting off the point).  The issue with my app was the xamarin forms app object was being treated as a singleton instead of being reconstructed on each call to OnCreate and therefore not reassigning the mainpage.  I've attached a sample project to further demonstrate what was going wrong in my project: https://github.com/pellet/xamform-init-test .  I'm going to close this since I was wrong about the forms documentation, we are actually doing it different in our project.
