### ISSUE TITLE
[Bug]Shell Navigation structure with HomePage page as FirstPage

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8699]
### Description
I am developing an app where the design requires loading of HomePage as firstpage. The Homepage show hamburger Icon. But it is not part of Hamburger Navigation. Please see [Grofers App](https://play.google.com/store/apps/details?id=com.grofers.customerapp&hl=en_IN) for example. The user can navigate to any Hamburger menu item and come back to Home page again. I need to implement same with Shell. But I am totally lost whether it is possible to implement this with shell. If not please consider adding this feature. 

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.991211
- IDE:VSMac 2019
- Affected Devices:iOS and Android

### Reproduction Link

[MasterDetail.zip](https://github.com/xamarin/Xamarin.Forms/files/3900346/MasterDetail.zip)

**Comment by jfversluis** [comment]
Hi @HobDev thanks for your issue!

I'm not entirely sure if I understand you correctly. I see that you want to have some kind of home page that does not have an entry in the hamburger menu? How would people go back to that homepage after navigating away?

I don't think that scenario is currently supported unless I am mistaken (cc: @PureWeen), you might be able to benefit from this #7847 where you can hide a certain Shell item. Is that something you could use?

**Comment by HobDev** [comment]
Hi @jfversluis In repro sample you will see that Homepage is in the Navigation stack. User can go back to HomePage by pressing backbutton. It is same as [Grofers](https://play.google.com/store/apps/details?id=com.grofers.customerapp&hl=en_IN) app in the play store.
It is one of the requirements of the app design. If it is not supported please consider this a feature request.

**Comment by jfversluis** [comment]
Maybe I'm not understanding something but I don't see the homepage in the hamburger menu

![image](https://user-images.githubusercontent.com/939291/69830834-e1870180-1226-11ea-914b-156dbf9f068c.png)

Am I missing something here? :)

Also, if we want to consider this a feature request we are going to need a lot more detail on what you are trying to do here. The way I think I understand what you mean you should be able to go a long way with the PR I already linked

**Comment by HobDev** [comment]
@jfversluis Thanks for the support. Fortunately the solution is available in the shell. The app requires the HomePage to be the center of the app. I declare Homepage as Tab in the AppShell. I declare it before other items so that it become root page. 
Then I declare a bunch of Menu Items after the Tab. This is all I want. Now I can Navigate away from the Home page by clicking on the MenuItems. After navigating away I can come back to HomePage by clicking on BackButton. 
Finally I just need to set Shell.FlyoutBehavior="Flyout" on HomePage in order to access the MenuItems.
