### ISSUE TITLE
[Bug] [Android] CollectionView don't set BindingContext in Header

### ISSUE THREAD

**Issue by Denrage** [xamarin/Xamarin.Forms#8700]
### Description
When adding a header to the CollectionView the BindingContext does not get propagate to it on Android. On iOS everything is fine.

### Steps to Reproduce

1. Start reproduction project on Android and iOS

### Expected Behavior
The BindingContext will be set for the Element inside the header
### Actual Behavior
The BindingContext gets only set on iOS not Android
### Basic Information

- Version with issue: 4.4.0.991210-pre2 (Tested with 4.3.0.991211 too)
- Last known good version: -
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 9.0
- Nuget Packages: -
- Affected Devices: -

### Reproduction Link

[BindingContextCollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/3900744/BindingContextCollectionView.zip)

**Comment by jfversluis** [comment]
Happens on Android, not iOS. Also, `Footer` has the same issue.
