### ISSUE TITLE
A11y Android: The backbutton is pronounced "Button Unlabeled" when titles are set

### ISSUE THREAD

**Issue by McFlemchSoda** [xamarin/Xamarin.Forms#8701]
### Description 
Having a navigationpage and activating talkback on android pronounces the back button as "Button Unlabeled" while all titles are set. 

### Steps to Reproduce
1.  Open attached solution
2. Run on android
3. Enable talkback

### Expected Behavior
Read the title provided or read it as back button to previous page.

### Actual Behavior
Ignores all titles and reads "Button unlabeled"

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: N/A
- IDE: VS MAC 8.3.10.2
- Platform Target Frameworks:
  - Android: 8
- Affected Devices: Android

### Reproduction Link
[BackButtonBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3901815/BackButtonBug.zip)

**Comment by rachelkang** [comment]
Hi, @McFlemchSoda - this issue will be fixed in #13563 

Another thing to note, however: when setting the BackButtonTitle, it must be set on the previous page.
In your case, in setting the BackButtonTitle of the back button on the second page, you're actually referring to MainPage; therefore, in code, it must be set on MainPage as opposed to SecondPage. Hope this helps! :)

**Comment by McFlemchSoda** [comment]
Thank you for the update!
Will there be any documentation available for this specific case for other people to find? Because personally it doesn't seem intuitive to put it on the page the back button is referring to, but I do understand your explanation. 
Thanks again!

**Comment by rachelkang** [comment]
@McFlemchSoda no problem! and good point - I just [edited](https://github.com/xamarin/Xamarin.Forms-api-docs/pull/280) our API docs here so hopefully you'll see the changes reflected [here](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.setbackbuttontitle?view=xamarin-forms) soon. Let me know if you saw this method / property anywhere else that you think might also benefit from added documentation!
