### ISSUE TITLE
[Bug] Android: Entry with ClearButtonVisibility="WhileEditing" not editable if page is displayed a second time

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#8707]
### Description
If you have an entry on a page with ClearButtonVisibility="WhileEditing", you can only edit the entry the first time the page is displayed. If the page is displayed a second time, the entry doesn't work anymore.
You can easily see this in a shell-application. I modified the "Xanimals"-solution. In the about-page I created two entries, one with ClearButtonVisibility="WhileEditing" and the other with ClearButtonVisibility="Never"
Only tested on Android.

### Steps to Reproduce

1. Take the attached solution (modified "Xanimals")
2. Go to the About-page. You can edit both entries.
3. Go to any other page, and return to the About-page
4. Only the entry with "Never" works. The entry with "WhileEditing" is dead.

### Expected Behavior
Entry should work
### Actual Behavior
It doesn't 
### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version: unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

[Xaminals.zip](https://github.com/xamarin/Xamarin.Forms/files/3902381/Xaminals.zip)

**Comment by PureWeen** [comment]
@KoenMat this looks like it's been fixed

I tested the sample against our nightly builds
https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

And I'm not longer able to reproduce there
