### ISSUE TITLE
[Bug] SelectionChanged when SelectionChangedCommand handles navigation

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#8712]
### Description
I have a CollectionView where I use both a SelectionChangedCommand and the SelectionChanged event. 

```xaml
<CollectionView  x:Name="Tasks" ItemsSource="{Binding Items}" VerticalOptions="Fill" SelectionMode="Single"  SelectionChangedCommand="{Binding TaskSelected}" SelectionChangedCommandParameter="{Binding Source={RelativeSource Self}, Path=SelectedItem}">
```

I adding an event handler to SelectionChanged in an override of OnAppearing and removing it in an override of OnDisappearing.

```csharp
        protected override void OnAppearing()
        {
            base.OnAppearing();

            Cars.SelectionChanged += Cars_SelectionChanged;
        }

        protected override void OnDisappearing()
        {
            base.OnDisappearing();

            Cars.SelectionChanged -= Cars_SelectionChanged;
        }

        private void Cars_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if(Cars.SelectedItem == null)
            {
                Cars.SelectedItem = null;
            }
        }
```

### Expected Behavior
SelectionChanged event handler should run/triggered before OnDisappearing.

### Actual Behavior
OnDisappearing runs first and removes the event handler, because of that then event handler never runs. It only happens when I am using Shell.

### Basic Information

- Version with issue: 4.3.0.991211
- Last known good version:
- IDE: VIsual Studio for Mac 8.3.10 (build 2)
- Platform Target Frameworks: 
  - iOS:  13.6.0.12
  - Android: 10.0.6.2

### Reproduction repo
https://github.com/dhindrik/CollectionViewBugRepro

**Comment by jfversluis** [comment]
Hey @dhindrik thanks for the report!

I'm not entirely sure what you mean though, sorry! I do see the code for the `CollectionView`, but not the appearing or disappearing you mention.

Would you be able to add a reproduction project showing the issue here?

Thanks!

**Comment by dhindrik** [comment]
I have updated the original post with a repo link (https://github.com/dhindrik/CollectionViewBugRepro) and additional information.

When I created the reproduction project I noticed that it only behaves like this if I am using Shell.
First I used the "old" way with a NavigationPage, and then the event handler executed before the OnDisappearing override.

**Comment by jfversluis** [comment]
I'm sorry, but I still don't quite understand what you mean. The fact that you hook or unhook an event doesn't mean that it's suppose to trigger, right? 

I'm not sure what it supposed to happen or not :)

**Comment by dhindrik** [comment]
When using Shell the event handler is unregistered in OnDisappearing when I select an item in the collection view before it trigger the event handler. OnDisappearing runs because that I am doing a navigation in the view model. This will not happen if I not using Shell. And I want to unset the selected item so I can navigate back and still Be able to select the same item again.

Maybe things would different if I use Shell.Current.GoToAsync instead of pushing to the navigation stack. Haven't tried that, working with an old code base and replacing things in steps. But I think it should work with both ways to navigate.

**Comment by dhindrik** [comment]
Try to run the code and set breakpoint in both event handler and OnDisappearing and you will see what order things are executing.

**Comment by jfversluis** [comment]
Gotcha! Would you say this basically describes it #6486?

**Comment by dhindrik** [comment]
Not really, I have not noticed any problems with OnAppearing.

**Comment by PureWeen** [comment]
OnDisappearing and OnAppearing fire earlier with Shell so that the events are more consistent cross platform.  When just using a NavigationPage it's a bit arbitrary  when OnDisappearing fires based on context and platform

I would say the ordering here seems correct. You've initiated intent on the VM to navigate away so Shell says hey I'm going to be disappearing.

Based on your sample though I'd suggest two different things
1) Why do you need to unsubscribe from the event? If you subscribe to the event in the constructor or from XAML and then set SelectedItem to null then everything will be fine. 
2)  From your sample it looks like you're using SelectedItem to clear the selection. If you want to have tapping an item in CV navigate you but not highlight the item then I'd recommend using a TapGestureRecognizer

Something like this
```XAML
<ContentView Padding="20">
                    <ContentView.GestureRecognizers>
                        <TapGestureRecognizer 
                            NumberOfTapsRequired="1"
                            Command="{Binding Source={x:Reference Cars}, Path=BindingContext.ItemSelected}"
                            CommandParameter="{Binding}"
                            >
                            
                        </TapGestureRecognizer>
                    </ContentView.GestureRecognizers>
                  <Label Text="{Binding}" FontSize="Subtitle" />
              </ContentView>
```

**Comment by dhindrik** [comment]
So using a TapGestureRecognizer on each item will not affect performance?

**Comment by PureWeen** [comment]
@dhindrik I haven't explicitly tested it but it shouldn't

The implementation of CollectionView uses native level recycling for all the cells so even if you have a million items you only have tens of  Gestures
