### ISSUE TITLE
[Bug] Blank page when displaying the master page on Samsung device

### ISSUE THREAD

**Issue by lanarchyste** [xamarin/Xamarin.Forms#8716]
### Description

When displaying the master page, the screen displayed is white.
Currently, the issue appears only on the Samsung S9 phone with Android 9.0

Not having the phone concerned, I can not test the various corrections that can be proposed to me

### Steps to Reproduce

Here is an example of the code reproducing the error:

```
var navigationDetailPage = new NavigationPage(new PlanningView())
{
    BarTextColor = StyleHelper.BarTextColor,
    BarBackgroundColor = StyleHelper.BarNavigationColor
};

var masterDetailPage = new MasterDetailPage
 {
     IsGestureEnabled = Device.RuntimePlatform != Device.iOS,
     Detail = navigationDetailPage,
     Master = new MainMenuView()
 };

Application.Current.MainPage = masterDetailPage;
await Application.Current.MainPage.Navigation.PopToRootAsync(false);
```

### Expected Behavior

Display the content of the page indicated in the detail of the master page

### Actual Behavior

The page is white after displaying the master page

### Basic Information

- Version with issue:
- IDE: Visual Studio For Mac 8.3.10 Build 2
- Platform Target Frameworks: 
  - Android: Android 10.0 (Q)
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Xamarin.Forms 4.3.0.991211
- Affected Devices: Samsung Galaxy S9 (SM-G960F)

**Comment by jfversluis** [comment]
> Not having the phone concerned, I can not test the various corrections that can be proposed to me

If you don't mind me asking, then how do you know this happens? :) 
This exclusively happens on the Galaxy S9? Just one device? Or have you seen multiple? 

I hope you understand that this might be a hard issue to crack

**Comment by lanarchyste** [comment]
Hi,

We are marketing a mobile solution for android and ios (with xamarin), and one of our customers has indicated the issue of the blank page.

After analysis, we know that the application does not freeze and that it is at the time of the display of the master page that the blank page occurs.

At this time, we know that the bug only occurs on Galaxy S9 !

In the past, we have had other incompatibilities with the Samsung brand but have been resolved with updates.

I know that this particular case will be difficult to reproduce, so I am aware that it may be impossible to correct ... but I keep hope :)

**Comment by jfversluis** [comment]
@lanarchyste thanks for your understanding!

If it is possible, I don't know it you have a Galaxy device at your disposal, it would be awesome to have a reproduction project with just the code that is showing this behavior.

Thanks!

**Comment by samhouts** [comment]
@lanarchyste I have a Samsung Galaxy S9+, and I'm not seeing this issue.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@lanarchyste  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
