### ISSUE TITLE
[Bug] ListView with CacheStrategy have a strange behavior when rendered the cells in iOS.

### ISSUE THREAD

**Issue by tiagobpompeo** [xamarin/Xamarin.Forms#8717]
### Description

I am using List View to display my content within a Frame. As soon as the content is loaded it presents a content overlay not respecting the list settings, but when I scroll the list that automatically are adjusted. I am using CachingStrategy = "RecycleElement", HasUnevenRows = "True" and Frame Layout (card) in ViewCell.

### Steps to Reproduce

1. Just run the attached app

### Expected Behavior
Display cells without overlap and no scrolling to self adjust
### Actual Behavior
The cells are overlapping and breaking the expected view
### Basic Information

- Last known good version:
- IDE :Visual Studio for Mac  8.3.8
- Platform Target Frameworks:
  - iOS: 
- Nuget Packages: Xamarin.Forms 2.4.4.859
- Affected Devices: All with iOS.

### Screenshots

<img width="349" alt="Captura de Tela 2019-11-29 às 12 20 16" src="https://user-images.githubusercontent.com/24531205/69878855-c8bd3100-12a4-11ea-9435-a23b8d6a8609.png">

### Reproduction Link
https://github.com/tiagobpompeo/TopMovies

**Comment by jfversluis** [comment]
Thank you @tiagobpompeo !

The reproduction is much appreciated. I do however see that it's using an older version of Xamarin.Forms. Did you try this with a more recent version?

Also, when running the reproduction I don't see the list come up. Do I need to do anything for that?

**Comment by tiagobpompeo** [comment]
Hello, when I updated the Xamarin Forms Package, sounds like to be resolved the problem. So I Believe what in that case the problem was solved ,but I have another case to explain in another issue with problemas just in iOS, thanks !
