### ISSUE TITLE
XAMARIN Linker is removing assemblies that have XAML-only references.

### ISSUE THREAD

**Issue by DRAirey1** [xamarin/Xamarin.Forms#8722]
Using Visual Studio 2019 Community 16.3.10, Xamarin.Forms 4.3.0.991211.

I've got a Standard Library 2.0 project that produces XAML views.  It references XAML controls that I built in a separate library.
My program crashes at runtime with:

> Exception thrown: 'Xamarin.Forms.Xaml.XamlParseException' in Xamarin.Forms.Xaml.dll Position 35:34.

> Type trcontrols:EmbeddedImageSource not found in xmlns clr-namespace:ThetaRex.Forms.Controls;assembly=ThetaRex.Forms

The VS designer has no problem finding this reference and will even complain when it isn't there.  If I place a reference to the shared library in the initialization routine for the view, it works:

            public FolderView(FolderViewModel folderViewModel)
            {
                // Initialize the IDE maintained components.
                this.InitializeComponent();
    
                // Required to access this object in XAML.
                EmbeddedImageSource embeddedImageSource = new EmbeddedImageSource();

                // Provide a view model for the page.
                this.BindingContext = this.ViewModel = folderViewModel;
            }
    
    
But if I remove the line with the **EmbeddedImageSource** on it, I get the error again.  I've found other posts which suggest that the assembly is optimized out of the referenced libraries if there's only XAML reference.

This is a serious bug.  Please fix it and suggest a work-around that's better than an empty reference in the code-behind.

**Comment by StephaneDelcroix** [comment]
enabling XamlC should mitigate most of those issues. you probably should share a reproduction project. thanks

**Comment by DRAirey1** [comment]
What is  XamlC?  How do I enable it?

**Comment by PureWeen** [comment]
@DRAirey1 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xamlc

**Comment by DRAirey1** [comment]
I was unable to reproduce the problem. After creating a new solution and new projects, then copying all the source code over to the new directory structure, the problem went away. At this point, it would appear that some .csproj or .sln file was corrupted.
