### ISSUE TITLE
[Bug] Can't pass xamarin shell param into string variable

### ISSUE THREAD

**Issue by aloptrbl** [xamarin/Xamarin.Forms#8723]
[QueryProperty("Id", "id")]    

  string id = null;
        public string Id
        {
            set
            {
                idx.Text = Uri.UnescapeDataString(value);
                id = Uri.UnescapeDataString(value);
            }
        }

and then i called id in Debug.WriteLine but not return the exact value like idx.Text.

**Comment by VladislavAntonyuk** [comment]
What is your input parameters and what result do you get in the output?

**Comment by PureWeen** [comment]
@aloptrbl can you attach a repro please?

**Comment by samhouts** [comment]
@aloptrbl  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
