### ISSUE TITLE
[Bug] The Command for TapGestureRecognizer inside CollectionView is invoked but the CommandParameter does not Bind to current item.

### ISSUE THREAD

**Issue by nwikechisom** [xamarin/Xamarin.Forms#8727]
### Description

The Command for TapGestureRecognizer inside CollectionView is invoked but the CommandParameter does not Bind to current item. 

### Steps to Reproduce

1. Create a Frame or RelativeLayout TapGestureRecognizer inside a CollectionView
2. Bind Command  to command in viewmodel of the page and set CommandParameter to CurrentItem as below:
`<TapGestureRecognizer Command="{Binding Source={x:Reference Name=DashPage}, Path=BindingContext.TopupCommand}" CommandParameter="{Binding .}"/>`
3. Run app and tap frame or layout

### Expected Behavior

Command should invoke an action depending on item tapped

### Actual Behavior

Command is invoked but not receiving current item as param instead it receives first item as param

### Basic Information

- Version with issue: Xamarin.Forms 4.3.12.991211
- Last known good version:
- IDE: Visual Studio for Mac 2019
- Platform Target Frameworks: 
  - iOS:   10
  - Android:  9.0 (API 28)
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
@nwikechisom can you attach repro? 

I've done what you propose here a few times and it always goes great for me

Here's an example I did for someone
https://github.com/xamarin/Xamarin.Forms/issues/8712#issuecomment-560986251

**Comment by nwikechisom** [comment]
@PureWeen I would love to share the repo but unfortunately I cannot at this time because its a private project with too much financial information. I can share some snippets privately if that will help. I'm already late on delivery time

**Comment by nwikechisom** [comment]
What if I have a Label outside the CollectionView whose Text property should be bound to the current item in the CollectionView, how may I implement this?

**Comment by PureWeen** [comment]
> What if I have a Label outside the CollectionView whose Text property should be bound to the current item in the CollectionView, how may I implement this?

you can use view to view binding to bind the SelectedItems on CV to the Text property
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#view-to-view-bindings

And then you'd use a converter to pull what you need from the SelectedItems Array
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters

> I would love to share the repo but unfortunately I cannot at this time because its a private project with too much financial information. I can share some snippets privately if that will help. I'm already late on delivery time.

Can you start from a new xamarin.forms project and recreate?
There's not really much we'll be able to help with on this one without a repro as all my various binding tests have worked for this one.

**Comment by samhouts** [comment]
@nwikechisom  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jopmiddelkamp** [comment]
I just run into the same issue with `Xamarin.Forms` version `4.5.0.356`. Her is a snippet of a similar situation.
 
```
<ContentPage 
    ...
    x:Name="root">
    <CollectionView ItemsSource="{Binding WrappedRoundPointList}>
        <CollectionView.ItemTemplate>
            <DataTemplate>
                <Frame>
                    <Frame.GestureRecognizers>
                        <TapGestureRecognizer
                            Command="{Binding Source={x:Reference root}, Path=BindingContext.DataContext.ItemSelectedCommand}"
                            CommandParameter="{Binding .}" />
                   </Frame.GestureRecognizers>
                </Frame>
            </DataTemplate>
        </CollectionView.ItemTemplate>
    <CollectionView ItemsSource="{Binding WrappedRoundPointList}>
</ContentPage>
```
This will fire the `ItemSelectedCommand` but the command parameter that will be passed trough will be `null`.
