### ISSUE TITLE
[Enhancement] Avoid user interaction of pages during navigation.

### ISSUE THREAD

**Issue by asusralis** [xamarin/Xamarin.Forms#8730]
## Summary
As it currently is, while a page is being pushed onto a navigation stack the user can interact with the previous page up until the animation is complete. I don't think there is a single instance where this would be wanted, so it would be best to have something to block the screen when a page animation starts. 

## API Changes
Hopefully there would be no API changes.

## Intended Use Case
For example, allowing the user to interact with previous pages can lead to multiple pages being pushed onto the nav stack or controls to be modified. 

Because you would never want the user to interact with previous pages during an animation, requiring the management of changing a page's IsEnabled - or its controls - is perceived more as a bandage that every developer that uses Xamarin.Forms will have to apply at some point.

Using IsEnabled for something that should not be a problem in the first place should be avoided and reserved for more specific use cases.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
