### ISSUE TITLE
[Bug] XF Material + Prism: Frame doesn't fire EventToCommandBehavior on iOS.

### ISSUE THREAD

**Issue by Schinwinkwinsky** [xamarin/Xamarin.Forms#8736]
### Description
I´m trying to use the Forms Material Visual on a ListView that has Frames as its items. Before I set visual as Material, the app worked well. But, after, the command is not being fired on iOS.
### Steps to Reproduce

1. Create a ListView and a CustomView that has a Frame as dad container.
2. Set the ListView to use ths CustomView as its items.
3. Set the visual os CustomView as Material.
4. Set a ListView behavior to navigate to another page when its item was clicked.
4. Try to run on iOS.

### Expected Behavior
When the item of ListView was clicked, the app should navigate to another page.
### Actual Behavior
Nothing happens. But, if the CustomView's visual property was deleted, everything works well.

- IDE: Visual Studio Community 2019 16.3.8
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 8.1
- Nuget Packages: Xamarin Forms (4.3.0.991211), Prism DryIoc Forms (7.2.0.1422), Xamarin Forms Visual Material (4.3.0.991211).

### Reproduction Link

https://github.com/Schinwinkwinsky/XF_MaterialFrame

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/5518
