### ISSUE TITLE
[Bug] [Shell] [Android] ToolbarItem Enabled/Disabled behavior does not work for Shell apps

### ISSUE THREAD

**Issue by brunck** [xamarin/Xamarin.Forms#8741]
### Description
Changing a ToolbarItem's enabled/disabled state at runtime in a Shell app works on iOS, but not on Android.
This _does_ work properly in non-Shell Android applications using the same mechanism.

### Steps to Reproduce

1. Wire up a ToolbarItem on a page, binding to its Command property. Set the text (or an icon) for it.
2. Make a button that toggles the state of the ToolbarItem between enabled and disabled, via the Command's CanExecute functionality.
3. Add a label with its Text property bound to the ToolbarItem's IsEnabled property.
4. Toggling the state back and forth changes the state of the IsEnabled property, but the UI state of the ToolbarItem itself does not change.

Using the sample repro app, just run it. The main page has the button, label and ToolbarItem. Just click on the button to change the enabled/disabled state for the ToolbarItem.

### Expected Behavior
The ToolbarItem grays out when disabled and does not respond to clicks, and is not grayed out and is clickable when enabled. This works on iOS but not on Android.

### Actual Behavior
The UI state of the ToolbarItem does not change.

### Basic Information

- Version with issue: 4.4.0.991220-pre3 and earlier
- Last known good version: unknown. This works when not using Shell
- IDE: VS 2019 16.3.8
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 9.0
- Android Support Library Version: 28.0.0.3
- Affected Devices: all

### Reproduction Link
[TestShellToolbarEnableDisable.zip](https://github.com/xamarin/Xamarin.Forms/files/3923405/TestShellToolbarEnableDisable.zip)

**Comment by brunck** [comment]
Here is an issue file which could be useful as a starting point to repro this.

[Issue8741.zip](https://github.com/xamarin/Xamarin.Forms/files/3963226/Issue8741.zip)

**Comment by jamesmcmenamin** [comment]
@PureWeen Did we find out if this made the cut for next Release? If so we know the number on it yet?

**Comment by PureWeen** [comment]
@jamesmcmenamin Unfortunately it probably won't make it into the next 4.4 SR
But it should be in into the next next one

**Comment by jamesmcmenamin** [comment]
@PureWeen All good brotha man such a huge thank you for this one.
