### ISSUE TITLE
Setting IsVisible does not work after the first time [Bug] 

### ISSUE THREAD

**Issue by davepruitt** [xamarin/Xamarin.Forms#8742]
### Description

I have an Android app in which all I want to do is place a semitransparent gray overlay over the entire screen for about 500 ms any time the user taps the screen. To accomplish this, I created a grid with a gray background color, and then simply set its visibility to true or false accordingly.

The first time I set the "IsVisible" property, the change is reflected in the UI. Every time after that, however, the change is not reflected in the UI. The "IsVisible" propery seems to have no effect.

### Steps to Reproduce

[BugDemoApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3923927/BugDemoApp.zip)

1. Open the solution that I have attached and run it.
2. Once the program is running, tap on the screen. The semitransparent gray overlay appears. The proper behavior is for it to disappear after 500 ms, but it remains on the screen.
3. You can view in the code-behind (by setting breakpoints at the appropriate places) that the variable is being properly set and reset, but the UI is not reflecting the change to the variable's value.

### Expected Behavior

The gray overlay should appear for 500 ms, and then disappear. This should happen every time the screen is tapped.

### Actual Behavior

The gray overlay appears once and then never disappears.

### Basic Information

- Version with issue: Xamarin Forms 4.3.0.991221
- Last known good version: N/A
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android: Android API Level 28 - Pie
  - UWP:  Not tested
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Just Xamarin Forms and its dependencies
- Affected Devices: Nexus 5X running Android 7.1.1 and Samsung Galaxy Tab S4 running Android 9.0

**Comment by PureWeen** [comment]
The main issue with how you're doing this is that the Timer callbacks are executing off the main thread, so when you update the IsVisible property you'll need to marshal that back over to the UI Thread

If I change your code to
```C#
        private void Update_timer_Elapsed(object sender, ElapsedEventArgs e)
        {
            lock (overlay_lock)
            {
                if (OverlayGrid.IsVisible && DateTime.Now >= (last_overlay_display_time + overlay_duration))
                {
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        OverlayGrid.IsVisible = false;
                        OverlayGrid.ForceLayout();
                    });
                }
            }
        }
```

Then everything executes correctly.

The part here that might be a bug is that no exception is being thrown. 

Internally the Queue used to set the BindableProperty just keeps adding to the queue every time you click the button

```
Queue<SetValueArgs> delayQueue = context.DelayedSetters;
```

If I just throw a *await Task.Yield();* into the mix the I get the exception about cross thread access that I would be expecting.

I think the Timer is blocking the value from propagating

@StephaneDelcroix thoughts?

**Comment by samhouts** [comment]
@davepruitt I think https://github.com/xamarin/Xamarin.Forms/issues/8742#issuecomment-562359051 should answer your question. Let us know if it does not. Thanks!
