### ISSUE TITLE
[Bug][UWP] SearchBar does not respect FontSize on 4.3.0 

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#8743]
### Description

Setting a FontSize, either using a number or a NamedSize, does not have any effect on a SearchBar on UWP in version 4.3.0.

### Steps to Reproduce

1. Create a project with Xamarin.Forms 4.3.0.
2. Add a SearchBar to a page and set the FontSize.
3. Run the project.

### Expected Behavior

FontSize is applied.

### Actual Behavior

FontSize is not applied.

### Basic Information

- Version with issue: 4.3.0-pre2 and later
- Last known good version: 
  - Stable: 4.2.0.910310
  - Pre-release: 4.3.0-pre1
- IDE: Visual Studio Enterprise 2019, version 16.3.10
- Platform Target Frameworks: 
  - UWP:  16299

### Screenshots
4.2.0:
![SearchBarFontSize1](https://user-images.githubusercontent.com/6132629/70183050-abc09d80-16aa-11ea-8162-16ff61abdb5b.png)

4.3.0:
![SearchBarFontSize2](https://user-images.githubusercontent.com/6132629/70183056-af542480-16aa-11ea-9b49-8256d6057ed8.png)

### Reproduction Link

[SearchBarFontSize.zip](https://github.com/xamarin/Xamarin.Forms/files/3924030/SearchBarFontSize.zip)

**Comment by WayaFlyfeather** [comment]
I can confirm this, and have located the bug to [these lines](https://github.com/xamarin/Xamarin.Forms/blob/f51099c3823cd7433d1fa95c4cff9227b2a59629/Xamarin.Forms.Platform.UAP/Forms.cs#L37-L44), introduced in #7319 - here UWP resources are merged into the ResourceDictionary, overwriting the default style for the _AutoSuggestBox_ defined in [AutoSuggestStyle.xaml](https://github.com/xamarin/Xamarin.Forms/blob/b80d3aedc716018f0e213af666307aa6d14ddcc3/Xamarin.Forms.Platform.UAP/AutoSuggestStyle.xaml).

My suggested fix to avoid conflicts with the imported UWP-styles, is to inherit _AutoSuggestBox_ to a new class, _FormsAutoSuggestBox_, and then use a default style for this instead.

AFAICT _AutoSuggestBox_ is currently used in two elements: _SearchBar_  and _ShellSection_.

I'd be happy to make a PR for my suggested change, if it makes sense. But it might also be prudent to check if this merge of resources / styles has caused similar problems else where(?)

**Comment by WayaFlyfeather** [comment]
That suggestion won't work, however, as _AutoSuggestBox_ is sealed. Then the best is probably to use a key for the AutoSuggestBox-style, instead of depending on a default style.

**Comment by PureWeen** [comment]
@WayaFlyfeather please create a PR!!

**Comment by WayaFlyfeather** [comment]
> @WayaFlyfeather please create a PR!!

@PureWeen Done! :) #8773
