### ISSUE TITLE
[Bug] [IOS][Shell] App Crashes with ToolBarItem after returning from background, Push new page, then return to previous page.

### ISSUE THREAD

**Issue by TimBoccaleri** [xamarin/Xamarin.Forms#8748]
### Description
I'm using XF 4.3 with Shell. On IOS, my App crashes when I have a toolbar item and close or move my app to the background. When I return from the background and then navigation.PushAsync() to another page and come back to previous page the app crashes. If I use the Tabs to navigate everything is okay until I push to another page and come back. 

### Steps to Reproduce

1. Add a ToolbarItem to any page. like this:
```
   <ContentPage.ToolbarItems>
        <ToolbarItem
            x:Name="btnShowAlerts"
            Clicked="btnShowAlerts_Clicked"
            Icon="ic_notifications_black_24" />
    </ContentPage.ToolbarItems>
```
2. Move/Close the app into the background. (Don't kill the app)
3. Bring the app back to foreground.
4. Navigate to another page with await Navigation.PushAsync(...)
5. Touch the back Navigation button to return to the master page.
6. App now crashes with

> Cannot access a disposed object. Object name: 'PrimaryToolbarItem'.

 

### Expected Behavior
App should not crash. Xamarin seems to dispose of all toolbar items when moved to background.

### Actual Behavior
The app crashes with the following error:

> System.ObjectDisposedException Message=Cannot access a disposed object. Object name: 'PrimaryToolbarItem'.

### Basic Information

- Version with issue: Xamarin Forms 4+ with Shell
- Last known good version: Unknown
- IDE: Windows 10, VS 2019
- Platform Target Frameworks: 
  - iOS:  11, 12, 13+
  - Android: Not Tested
  - UWP:  Not Tested

**Comment by PureWeen** [comment]
@TimBoccaleri can you test this on 4.4 pre3?

If you still see the issue can you attach repro please? I tried to recreate what you outlined and it's not crashing for me

**Comment by TimBoccaleri** [comment]
It appears this is only happening in my production app. I apologize, I thought I tested this in another app but after testing a new test app today, I can not reproduce the issue. I will need to do some digging into my app to see what the root cause is. If I can reproduce the issue I will reopen. Thx.

**Comment by PureWeen** [comment]
Sounds good @TimBoccaleri !

If you have a full stack trace maybe that'll ring some bells
