### ISSUE TITLE
XF 4+ shell - Page loading error with more tab menu

### ISSUE THREAD

**Issue by TimBoccaleri** [xamarin/Xamarin.Forms#8749]
### Description
In XF 4+ with Shell on IOS. If you add 5+ items to the Tab Bar menu so that you get the More menu items to show. After opening a page from more menu, then try to navigate to another page with navigation.pushasync() that page will not load and the app will start doing strange things after that. (like the menu names will disappear when you go back to the menu) 

### Steps to Reproduce

1. In Appshell.xaml add Six ShellSections under the ShellItem tag. (This will give you the more tab)
2. On one of the pages that shows up on more navigation menu add a button that calls another page with the Navigation.PushAsync(new page())
3. Run the app 
4. Click the more tab
5. Select the page with button you added. 
6. Click the button and Navigate to the new page.
7. Page doesn't load and if you hit the back button the menu item text is now blank.

### Expected Behavior
I should be able to navigate from a page in the more tab menu to another page with out error.

Everything works fine when pages are before the more tab:
1. Move this page off of the more tab by making it the 1st or 2nd tab in your app.
2. Click on that page
3. Hit the button to push to new page,
4. Page loads just fine.

### Actual Behavior
The page does not load and app clear menu text from the more menu. 

### Basic Information

- Version with issue: 4+ with shell
- Last known good version: unknown
- IDE: Windows 10, VS 2019
- Platform Target Frameworks: 
  - iOS:  11, 12, 13+
  - Android: Not Tested

**Comment by PureWeen** [comment]
Hmm :-/ yea looks like anything under the more tab gets its navigationcontroller swapped out with an internal moreNavigationController on iOS

https://stackoverflow.com/questions/10402432/suppress-morenavigationcontroller-in-custom-uitabbarcontroller


So you have to push to that instead

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/7594
