### ISSUE TITLE
[Bug] Values of constants and variables are not represented correctly at runtime?!

### ISSUE THREAD

**Issue by z07713** [xamarin/Xamarin.Forms#8754]
### Description

(I really don't know how to write about this because english is not my first language but i'm going to try it through an example!) I have introduced a constant, gave it some value and built and deployed the Android App, then i stopped the debugging, commented out the constant and introduced an another one with same name, gave it a different value. Rebuilt and re-deployed the Android App and at runtime, the value of the constant was the first one, which i have commented out! This "feature" also "works" with variables, not only constants.

Cleaning the solution fixes the problem for the next build/deploy, after that it comes back!

### Steps to Reproduce

1. Introduce a contant/variable
2. Build and deploy the application
3. Stop debugging and alter the value of the contant/variable
4. Rebuild and re-deploy the application

### Expected Behavior

If value of constant/variable has been changed, the correct value shoud be represented at runtime

### Actual Behavior

If value of constant/variable has been changed, the previous value is represented at runtime

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019 16.4.0
- Platform Target Frameworks: 
  - iOS:  n/a
  - Android: 9.0
  - UWP:  n/a
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Xamarin.Forms 4.3.0.991211
- Affected Devices: Android Emulator, SGS8, SGS10

### Screenshots

[https://i.imgur.com/dc6Ru4U.png](https://i.imgur.com/dc6Ru4U.png)

**Comment by PureWeen** [comment]
@z07713 what version of Visual Studio are you on?

**Comment by z07713** [comment]
> @z07713 what version of Visual Studio are you on?
> 
> Also, if you try this with a new Xamarin.Forms project do you see the same thing?

@PureWeen I'm sorry, i failed to indicate the IDE, it is VS2019 16.4.0, i have updated the bugreport also.

About the bug, i have managed to reproduce it, however at first time it slipped my mind, that it is actually a netstandard class library that has methods that i call from the X.F shared project!

I tried this exactly in the shared project but there was no bug at all, however i made a brand new solution, added a netstandard library, called the method from the X.F shared project and the bug is there!

[https://i.imgur.com/pzakX7L.png](https://i.imgur.com/pzakX7L.png)

I'm sorry it seems it's going to be turn out not X.F related but i appreciate your help anyway!

**Comment by PureWeen** [comment]
@z07713 can you log this here https://developercommunity.visualstudio.com/spaces/8/index.html ? Or use the feedback tool inside Visual Studio? 

To be completely honest though :-/ If there is an issue here with shared projects I don't think it will get fixed. Shared projects have been deprecated and issues with them don't really get that much attention. It never hurts to log the bug but I think you'd be better served converting your shared project to netstandard or to a multi targeted project 
https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/

**Comment by z07713** [comment]
> @z07713 can you log this here https://developercommunity.visualstudio.com/spaces/8/index.html ? Or use the feedback tool inside Visual Studio?
> 
> To be completely honest though :-/ If there is an issue here with shared projects I don't think it will get fixed. Shared projects have been deprecated and issues with them don't really get that much attention. It never hurts to log the bug but I think you'd be better served converting your shared project to netstandard or to a multi targeted project
> https://montemagno.com/converting-xamarin-libraries-to-sdk-style-multi-targeted-projects/

@PureWeen I'm deeply sorry if i have indicated this wrong, but my shared project is indeed netstandard! I was talking about the project that the latest and greatest VS creates when i select a new X.F project. So i have the "shared" netstandard project (i'm sorry i don't know how to call is another way), the Android project, and a netstandard class library which is referenced from the "shared" netstandard project and that is where the "bug?" occures, i even have a freshly created repro of it, sorry if wasn't beeing clear :(

**Comment by PureWeen** [comment]
@z07713 I think my suggestion of where to log the issue still applies. I tested this locally and for me the debug changed. The android debugger team watches issues that are logged through the feedback tool and at dev community

- turn on verbose logging (tools => options => projects and solutions => build and run => Diagnostic)
- run your build where the const is correct
- grab the output
- run your build where the const is incorrect
- grab the output
- Now zip up your project (bin/obj included) and create a feedback ticket with the two outputs and the zipped project

It's unfortunate because the record feature of feedback currently doesn't read build outputs :-/ Hopefully that'll be included soon to simplify this process

**Comment by PureWeen** [comment]
@z07713 instead of build output you could instead grab the binlogs which are a bit easier to work with

Could you please follow these steps to provide additional build logs? 

1. Install the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension
2. In Visual Studio, choose the View > Other Windows > Build Logging menu item.
3. Click on the "play" button.
4. Reproduce the issue
5. Select all entries in the build logging tool window
6. Right-click them, Save Logs
7. Attach the resulting zip file to this issue.

You can inspect the logs too by installing the msbuildlog.com viewer tool.

**Comment by z07713** [comment]
> @z07713 instead of build output you could instead grab the binlogs which are a bit easier to work with
> 
> Could you please follow these steps to provide additional build logs?
> 
> 1. Install the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension
> 2. In Visual Studio, choose the View > Other Windows > Build Logging menu item.
> 3. Click on the "play" button.
> 4. Reproduce the issue
> 5. Select all entries in the build logging tool window
> 6. Right-click them, Save Logs
> 7. Attach the resulting zip file to this issue.
> 
> You can inspect the logs too by installing the msbuildlog.com viewer tool.

@PureWeen I'm sorry for the delay, i was on a little winter break but now i did everything you asked for, thank you again for paying attention to this!

This would be for your first request, i did it anyway: [build1](https://drive.google.com/open?id=1me3AoGvBYiCezKsQj7oRzV4HFLvnUEiu), [build2](https://drive.google.com/open?id=1o4Wh99rnWCu7uRuTX-0OqbZ0Tckd8TiG)

And for the second: [build_logging_1](https://drive.google.com/open?id=1vuCXkf-5FWTyKcuBLrj7eXS3P-KFr-Gt), [build_logging_2](https://drive.google.com/open?id=1FxVIB4ip3tDpVVWFzCpTfwer0oUobCFI)

I have uploaded a repro as well, just in case: [repro](https://drive.google.com/open?id=19apVlQS0TafFeBT16aCfzvtvCwcweVgS)
