### ISSUE TITLE
[Bug] Xamarin 4.3.0 SR3 fails to build with error MT2101: Can't resolve the reference 'System.Drawing.RectangleF'

### ISSUE THREAD

**Issue by Drise13** [xamarin/Xamarin.Forms#8765]
### Description
After upgrading to 4.3.0 SR3 on iOS, a build error occurs in both development and on AppCenter.

`MTOUCH : error MT2101: Can't resolve the reference 'System.Drawing.RectangleF System.Drawing.RectangleF::Empty', referenced from the method 'System.Void Xamarin.Forms.Platform.iOS.ActivityIndicatorRenderer::OnElementChanged(Xamarin.Forms.Platform.iOS.ElementChangedEventArgs1<Xamarin.Forms.ActivityIndicator>)' in 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`

Downgrading back to SR2 restores the ability to complete a build.

### Steps to Reproduce

1. Upgrade to 4.3.0 SR3
2. Build
3. Observe error

### Basic Information

- Version with issue: 4.3.0 SR3
- Last known good version: 4.3.0 SR2
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.2

**Comment by PureWeen** [comment]
@Drise13 What version of Visual Studio are you using?

**Comment by Drise13** [comment]
2017, v15.9.15

**Comment by MagicAndre1981** [comment]
@PureWeen 

When compiling with [VS2019, you need to add this entry to csproj](https://github.com/xamarin/xamarin-macios/issues/7249#issuecomment-543298089):

`<DisableExtraReferences>true</DisableExtraReferences>`

But some packages may still fail.

**Comment by simba3684** [comment]
i am using vs2017 and also have same error , is it a bug ? after upgrading to the latest Xamarin.Forms
