### ISSUE TITLE
[Bug][iOS] SwipeView SwipeBehaviorOnInvoked RemainOpen issue on iOS

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8767]
### Description

Setting the `SwipeBehaviorOnInvoked` property to `RemainOpen`, after multiple `SwipeView`s have been rendered, doesn't result in the correct behavior on `SwipeView`s on iOS.

### Steps to Reproduce

1. Run the attached sample on iOS.
2. Navigate to the SwipeView behavior page.
3. Alter the SwipeBehaviorOnInvoked Picker to RemainOpen.
4. Swipe the first SwipeView from the right.
5. Swipe the second SwipeView from the right.
6. In the first SwipeView, click Delete.
7. In the second SwipeView, click Favourite.

### Expected Behavior

The first SwipeView remains open and the second SwipeView remains open.

### Actual Behavior

I get different behavior on different runs. Sometimes the first SwipeView closes. Sometimes it doesn't. Sometimes the second SwipeView closes. Sometimes it doesn't. 

The behavior I've observed the most is that the first SwipeView closes (incorrect), while the second SwipeView doesn't (correct).

### Basic Information

- Version with issue: 4.4-pre3
- IDE: VSMac 8.3.10
- Platform Target Frameworks: 
  - iOS:  13.2

### Reproduction Link

[SwipeViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3928299/SwipeViewDemos.zip)

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by samhouts** [comment]
closed by #9664
