### ISSUE TITLE
[Bug] SwipeView in CollectionView selection

### ISSUE THREAD

**Issue by MarMarIV** [xamarin/Xamarin.Forms#8774]
Using SwipeView in CollectionView: SwipeView catch touch gesture and not propagate it to CollectionView so SelectionChanged is no invoked

When i try to evade with TapGestureRecognizer on SwipeView, then SwipeItem Command and TapGesture Command are invoked at same time. (Android only)

### Steps to Reproduce

1. Put SwipeView (with some SwipeItems) in CollectionView
2. Set CollectionView SelectionMode to Single and attach event SelectionChanged
3. After touching item, event SelectionChanged is not invoked

### Expected Behavior
On touch only on SwipeView, SwipeView should propagate touch event to CollectionView (+ Commands, ProperyBindings, ....)

### Example

[CollectionViewAndSwipeView.zip](https://github.com/xamarin/Xamarin.Forms/files/3930537/CollectionViewAndSwipeView.zip)

### Basic Information
- Version with issue: XF 4.4.0.991220-pre3
- IDE: VS 2019 16.4
- Platform Target Frameworks:
  - iOS:  Not working (iOS 13.2.3)
  - Android: Not working (SDK Android 9.0)
  - UWP:  On UWP SwipeView not works in CollectionView 
- Android Support Library Version: 28.0.0.3

**Comment by MarMarIV** [comment]
I prefere to working both of the uses that i describe, because i want use SwipeView without CollectionView and TapGesture detection/Command

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by angelru** [comment]
The same issue here.

**Comment by chinni-nag** [comment]
The same issue here. While i am  putting swipeview inside of List selecting an  item is not working and commands also not working. Any update on this Please let me know. Thanks.

**Comment by daves1992** [comment]
Same issue, I have a SwipeView on a collection but also want the tap to open a sub list.

**Comment by chinni-nag** [comment]
@daves1992  Did you solve the issue?
Please let me know . Thanks.
