### ISSUE TITLE
[Bug] Set ContentPage's Style with BackgroundColor in App resources doesn't work

### ISSUE THREAD

**Issue by yanshouwang** [xamarin/Xamarin.Forms#8776]
### Description
Set ContentPage's Style with BackgroundColor in App resources doesn't work
### Steps to Reproduce

1. Add ContentPage Style in App.Resource and set it's BackgroundColor with a color
2. Start the app, but the page's color doesn't change as excepted.

### Expected Behavior
Page's color should be the one we set in App.Resources's style.
### Actual Behavior
Page's color doesn't change.
### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 2019.16.4.0
- Platform Target Frameworks: 
  - iOS:  13.8.2.2
  - Android: 10.1.0.30
  - UWP: didn't test
- Android Support Library Version: 
- Nuget Packages:4.3.0.908675
- Affected Devices:

### Reproduction Link
[BUG.NET](https://github.com/yanshouwang/BUG.NET.git)

**Comment by PureWeen** [comment]
Because the ContentPage is deriving from ContentPage you have to set *ApplyToDerivedTypes="True"* and then it will work 

```XAML
        <Style TargetType="NavigationPage">
            <!-- Set these properties works fine -->
            <Setter Property="BarBackgroundColor" Value="HotPink"/>
            <Setter Property="BarTextColor" Value="White"/>
        </Style>
        <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
            <!-- Set BackgroundColor here doesn't work -->
            <Setter Property="BackgroundColor" Value="Purple"/>
        </Style>
```

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/implicit#apply-a-style-to-derived-types

**Comment by yanshouwang** [comment]
@PureWeen Thanks, helped me a lot
