### ISSUE TITLE
[Bug] SwipeView crash if Text not is set on SwipeItem

### ISSUE THREAD

**Issue by dhindrik** [xamarin/Xamarin.Forms#8777]
### Steps to Reproduce

1. Create a ColletionView
2. Add SwipeItems to the template
3. Add an IconImageSource to the SwipeItems
4. Swipe

### Expected Behavior
Only icons visible for SwipeItem

### Actual Behavior
When running it on iOS 13.2.2 simulator NullReferenceException when the user swipes.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.001220-pre3

### Reproduction repo
Left items only have an icon in this sample and it crashes. Right items are working.

https://github.com/dhindrik/SwipeViewIconCrash

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by davidbritch** [comment]
Note: while this occurs on iOS, on Android a `SwipeItem` that doesn't define the `Text` property is currently ok (no exception).

**Comment by davidbritch** [comment]
Maybe there's an argument for making `Text` compulsory on all platforms, otherwise it becomes possible to define blank `SwipeItem` objects on Android:

```
<SwipeItem  Invoked="OnFavoriteSwipeItemInvoked" />
```

**Comment by dhindrik** [comment]
I am really want to use it without text, just with with icons.
