### ISSUE TITLE
[Bug] SwipeViewItem handler invocation intermittent issue on iOS and Android

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8778]
### Description

When SwipeItems are revealed on iOS and Android (not tried UWP), clicking on them doesn't always invoke their handlers. Instead the SwipeItems close. However, this is an intermittent issue. Sometimes it works as planned. Other times it doesn't.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the SwipeView events page.
3. Swipe from the right on the Grid.
4. Click Favourite or Delete.

### Expected Behavior

An alert is displayed in response to either SwipeItem being revealed, followed by the SwipeItems closing.

### Actual Behavior

The SwipeItems close and the Grid is displayed again.

Note: this is an intermittent error. Sometimes it works as it should. Sometimes it doesn't. I can do a screen capture if required.

### Basic Information

- Version with issue: 4.4-pre3
- IDE: VSMac 8.3.10
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 

### Reproduction Link

[SwipeViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3932438/SwipeViewDemos.zip)

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by samhouts** [comment]
closed by #9664
