### ISSUE TITLE
[Bug][iOS][Android] Entry in custom SwipeItemView can't gain focus

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8779]
### Description

I've defined a custom SwipeItemView that contains an Entry. When the SwipeItemView is revealed, it's impossible to focus in the Entry. Attempting to do so closes the SwipeItemView.

I realise this may be unsupported behavior, but I need to know if it is.

Note: It's possible to give the Entry focus with the TAB key on iOS.

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the SwipeView custom SwipeItem.
3. Swipe from the right on "What's 2+2?".
4. Give focus to the Entry with the mouse/touch.

### Expected Behavior

The Entry gains focus and can receive input.

### Actual Behavior

The SwipeViewItem closes.

### Basic Information

- Version with issue: 4.4-pre3
- IDE: VSMac 8.3.10
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: API 28

### Reproduction Link

[SwipeViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3932438/SwipeViewDemos.zip)

**Comment by PureWeen** [comment]
@jsuarezruiz

**Comment by jsuarezruiz** [comment]
Should be fixed with https://github.com/xamarin/Xamarin.Forms/pull/8653
