### ISSUE TITLE
[Bug] Android permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE added even if they are not in manifest

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8780]
### Description
On Android permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE are added always even if they are not present in the manifest.

### Steps to Reproduce

1. Create a new project from the Xamarin.Forms Visual Studio blank template.
2. Run Android project
3. Go to `bin` folder and look for APK for your app. Open it via 7zip (or any other unzipper) and extract Android manifest.
4. As you can see in the manifest there are two permissions:

```
android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE
```

For production builds they are also added, although they are not present in the manifest.

### Expected Behavior
Android permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE should not be added if they are not present in the manifest.

### Actual Behavior
Android permissions READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE are added even if they are not present in the manifest.

### Basic Information

- Version with issue: 4.3.0.991221
- IDE: Visual Studio 16.3.9

**Comment by VladislavAntonyuk** [comment]
This permissions are set on Xamarin Android project properties

**Comment by PureWeen** [comment]
What @VladislavAntonyuk said

If you look at the AssemblyInfo.cs file there are two attributes added
```

// Add some common permissions, these can be removed if not needed
[assembly: UsesPermission(Android.Manifest.Permission.Internet)]
[assembly: UsesPermission(Android.Manifest.Permission.WriteExternalStorage)]
```

You can remove those.

Also if you're deploying with DEBUG I'm pretty sure that will add "Internet" and "ReadExternal" into the manifests for reasons of debug experience. I tested with a Xamarin Android Native and it added those same permissions. Then when I switched to release they were gone
