### ISSUE TITLE
[Bug][iOS] SwipeViewItem rendering issue on iOS

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8781]
### Description

I've defined a custom SwipeItemView that contains an Entry. However, on iOS the Entry is overdrawing the original text from SwipeView.Content.

### Steps to Reproduce

1. Run the attached sample on iOS.
2. Browse to the SwipeView custom SwipeItem page.
3. Swipe from the right on "What's 2+2?".

### Expected Behavior

The Entry is shown, with no overdraw of "What's 2+2?".

### Actual Behavior

The Entry is shown, with overdraw of "What's 2+2?".

### Basic Information

- Version with issue: 4.4-pre3
- IDE: VSMac 8.3.10
- Platform Target Frameworks: 
  - iOS:  13.2

### Screenshots

![Simulator Screen Shot - iPhone X - 2019-12-06 at 14 38 21](https://user-images.githubusercontent.com/8092460/70330911-5e713700-1836-11ea-8777-6e1d6778c04f.png)

To see it more clearly, I've removed the Margin from the StackLayout inside the SwipeItemView:

![Simulator Screen Shot - iPhone X - 2019-12-06 at 14 41 22](https://user-images.githubusercontent.com/8092460/70331010-8d87a880-1836-11ea-8998-72bd139e8c4d.png)

### Reproduction Link

[SwipeViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3932438/SwipeViewDemos.zip)

**Comment by PureWeen** [comment]
@jsuarezruiz
