### ISSUE TITLE
[Bug] Shell's MenuItemTemplate doesn't work with a DataTemplateSelector

### ISSUE THREAD

**Issue by mfeingol** [xamarin/Xamarin.Forms#8789]
### Description

The only way I can see to customize MenuItem instances in a Shell is to use Shell's MenuItemTemplate property. The most elegant way to introduce variation in a template is to use DataTemplateSelector.

Unfortunately, this doesn't work with MenuItemTemplate: it fails with an InvalidCastException.

### Steps to Reproduce

1. Set up a Shell
2. Set up a simple DataTemplateSelector
3. Set `MenuItemTemplate="{StaticResource MyMenuItemTemplateSelector}"`

### Expected Behavior

The DataTemplateSelector works as expected, as it does everywhere else.

### Actual Behavior

```
**System.InvalidCastException:** 'Specified cast is not valid.'

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#	Annotated Frame
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#	Annotated Frame
 	0x2D in Android.Runtime.DynamicMethodNameCounter.91	C#	Annotated Frame
 	0xC in Xamarin.Forms.Platform.Android.ShellFlyoutRecyclerAdapter.OnCreateViewHolder at d:\agent\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellFlyoutRecyclerAdapter.cs:151,4	C#	Annotated Frame
 	0x12 in Android.Support.V7.Widget.RecyclerView.Adapter.n_OnCreateViewHolder_Landroid_view_ViewGroup_I	C#	Annotated Frame
 	0x1D in Android.Runtime.DynamicMethodNameCounter.91	C#	Annotated Frame
 	0xFFFFFFFFFFFFFFFF in Java.Interop.NativeMethods.java_interop_jnienv_call_nonvirtual_void_method_a	C#	Annotated Frame
 	0x79 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod	C#	Annotated Frame
 	0x21 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod	C#	Annotated Frame
 	0x69 in Android.Views.ViewGroup.Layout	C#	Annotated Frame
 	0xA2 in Xamarin.Forms.Platform.Android.ShellRenderer.OnElementSizeChanged at d:\agent\1\s\Xamarin.Forms.Platform.Android\Renderers\ShellRenderer.cs:304,4	C#	Annotated Frame
```
### Basic Information

- Version with issue: 4.3.0.991221
- Last known good version: Unknown
- IDE: VS 2019 16.4.0
- Platform Target Frameworks: 
  - Android: 9.0

### Reproduction Link

I can provide one if it helps, but it's pretty easy to set up a repro.

**Comment by PureWeen** [comment]
@mfeingol I wasn't able to reproduce

- can you test this on the latest nightly https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds
- and/or include a repro?

I just used the instructions here to create a DataTemplateSelector https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector and it worked for me

That part of the code does the following cast
```
var content = (View)template.CreateContent();
```

So I'm thinking maybe you're using something that's not a View as the top level element in the template? Maybe you're using a ViewCell?

**Comment by mfeingol** [comment]
Excellent point. I had a viewcell wrapping my content, mostly as a reflex. Sorry about that. Working now.

**Comment by mfeingol** [comment]
@PureWeen: while we're on the topic, is there a good way to to implement `OnSelectTemplate` for `MenuItem` instances?

I ask because the object I'm offered in `OnSelectTemplate` is a `MenuShellItem` instance which has a `MenuItem` property... But because `MenuShellItem` is internal to Xamarin.Forms, the only path forward appears to be reflection. Unfortunately, there's nothing particularly identifying that makes it to the properties on the `ShellItem` base class.

Thanks.

**Comment by mfeingol** [comment]
It's also asymmetrical with `FlyoutItem` instances.  When `OnSelectTemplate` is called for those, the `item` provided is the FlyoutItem instance itself.

**Comment by PureWeen** [comment]
> It's also asymmetrical with FlyoutItem instances. When OnSelectTemplate is called for those, the item provided is the FlyoutItem instance itself.

Yea :-/ I'm not the biggest fan of how this all works. Plus you have to supply two different templates to customize those which I'm not a fan of.  You can use the same template in either place but still weird. I feel like we could just add Command to FlyoutItem and just make it all the same. 

> I ask because the object I'm offered in OnSelectTemplate is a MenuShellItem instance which has a MenuItem property... But because MenuShellItem is internal to Xamarin.Forms, the only path forward appears to be reflection. 

Agreed but out of curiosity what are you wanting access to on this? The base is a ShellItem and it's a BiindableObject so you can access all of that. 

For example you could do this to bind through to your ShellVM
```XAML
 <Shell.MenuItemTemplate>
        <DataTemplate>
            <Label Text="{Binding BindingContext.SomePropertyOnYourShellVM}"></Label>
        </DataTemplate>
    </Shell.MenuItemTemplate>
```

**Comment by mfeingol** [comment]
I have two different kinds of MenuItem entries, and I have a different templates for each. I'm using DataTemplateSelector to choose between them at runtime.

So when the times comes to choose... I'm given a `MenuShellItem` instance and it's not obvious how to decide which template I want to use. In practice, I'm reflecting to get the `MenuItem` property, and then saying `if (mi is MyMenuItemType1) return MyMenuItemType1Template;` and so on.

**Comment by PureWeen** [comment]
@mfeingol makes sense

I'll take a look at that here soon. 

On a side note the templates are attached properties so you can specify them per element. So if you have a custom MenuItem you could attach the template inside there instead of using a template selector

```C#
        public class CustomMenuItem : MenuItem
        {
            public CustomMenuItem()
            {
                Shell.SetMenuItemTemplate(this, new DataTemplate());
            }
        }
```

**Comment by mfeingol** [comment]
Thanks, that's good to know.

Unfortunately, the approach doesn't work too well with DataTemplates defined in XAML inside Shell.Resources (which seems like the natural place to put them).

This is because when MenuItem and FlyoutItem constructors are first called, Shell.Current is still set to null (as is this.Parent) so there's no terribly good way to access data templates from resources. Even using a manually created static instance doesn't work, because the Resources dictionary on the Shell instance hasn't been populated that early.
