### ISSUE TITLE
[Enhancement][iOS] Change Xamarin.Forms template to better handle default status bar style

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/Xamarin.Forms#8792]
## Summary
In a new Xamarin.Forms project the Info.plist for the iOS project does not contain a UIViewControllerBasedStatusBarAppearance entry (at least in VS for Mac). By [default](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html) when the property is not set it is internally set to true.

When a user uses Xamarin.Forms out of the box and they change the BarBackgroundColor of a NavigationPage the status bar color will not automatically update. The user has to edit the Info.plist and add 
```
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>
```

I believe a better out of the box experience is to have this value added to the Info.plist and set to false by default as most cases this makes status bar colors change automatically. If the user wishes to manually change UIStatusBarStyle via UIApplication.SharedApplication.StatusBarStyle then they will need to add this key manually themselves anyway.

The only use case when you want this to be true is if a user wishes to override all content renderers that are a subclass of a UIViewController to then track and implement their own PreferredStatusBarStyle method. At this point it should then be on those users to change the UIViewControllerBasedStatusBarAppearance to true.

## API Changes

None

## Intended Use Case
File > New Xamarin.Forms project.
Use any NavigationPage and set BarBackgroundColor to Black, BarTextColor to White. Currently the status bar will not automatically update and it will remain black.

For someone starting mobile development with Xamarin.Forms it may take a lot of searching to find this key and set it to false.

**Comment by jfversluis** [comment]
Thanks for the suggestion! I think for Forms for now we'll leave it as it is. It might be good to check out for .NET MAUI though and see if we can change that.
