### ISSUE TITLE
[Bug] CarouselView Position not firing on UWP

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#8802]
### Description
PositionSelected event as well as position binding is not fireing on UWP

### Steps to Reproduce

**CarouselView implementation:**
```
  public class DiaryCarouselXF : Xamarin.Forms.CarouselView, INotifyPropertyChanged
    {
        public DiaryCarouselXF()
        {
            //UWP
            //https://github.com/xamarin/Xamarin.Forms/issues/3293

            HorizontalScrollBarVisibility = ScrollBarVisibility.Never;
            VerticalScrollBarVisibility = ScrollBarVisibility.Never;


            //this.ItemSizingStrategy = ItemSizingStrategy.MeasureAllItems;// ItemSizingStrategy.MeasureFirstItem;

            IsScrollAnimated = false;

            this.ItemsLayout = new LinearItemsLayout(ItemsLayoutOrientation.Horizontal)
            {
                SnapPointsAlignment = SnapPointsAlignment.Center,
                SnapPointsType = SnapPointsType.MandatorySingle
            };

            PositionChanged += DiaryCarouselXF_PositionChanged;

            //this.ItemsLayout = new GridItemsLayout(ItemsLayoutOrientation.Horizontal)
            //{
            //    SnapPointsAlignment = SnapPointsAlignment.Center,
            //    SnapPointsType = SnapPointsType.Mandatory,
            //    Span = 1
            //};

        }

        private void DiaryCarouselXF_PositionChanged(object sender, PositionChangedEventArgs e)
        {
            var d = 2;
        }

        public static readonly BindableProperty IsLoadingProperty = BindableProperty.Create(nameof(IsLoading), typeof(bool), typeof(DiaryCarouselXF), false, defaultBindingMode: BindingMode.TwoWay);
        public bool IsLoading
        {
            get { return (bool)this.GetValue(IsLoadingProperty); }
            set
            {
                this.SetValue(IsLoadingProperty, value);
                RaisePropertyChanged();
            }
        }

        public new event PropertyChangedEventHandler PropertyChanged;

        // This method is called by the Set accessor of each property.
        // The CallerMemberName attribute that is applied to the optional propertyName
        // parameter causes the property name of the caller to be substituted as an argument.
        private void RaisePropertyChanged([CallerMemberName] String propertyName = "")
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    } 
```
**CarouselView View**

```
            <custom:DiaryCarouselXF x:DataType="DiaryVM:DiaryDayViewModel" ItemsSource="{Binding DiaryDays}" x:Name="DiaryCarousel" Position="{Binding DiaryPosition, Mode=TwoWay}" Grid.Row="0" IsVisible="{Binding IsLoading, Converter={StaticResource InverseBooleanConverter}}">
                <custom:DiaryCarouselXF.ItemTemplate>
                    <DataTemplate>
                        <BoxView BackgroundColor="Blue"/>

                    </DataTemplate>
                </custom:DiaryCarouselXF.ItemTemplate>
            </custom:DiaryCarouselXF>

```
Load the sample using latest XF and swipe any direction.

See the positionselected event and positionbinding does not work

### Expected Behavior
positionselected event to fire and position binding to work

### Actual Behavior
no updates

**Comment by samhouts** [comment]
@JKennedy24  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by JKennedy24** [comment]
Hi @samhouts 

Please find attached sample

steps to replicate:
1. open sample on uwp
2. click "List Carousel View"
3. swipe carousel item
[SfSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3972554/SfSample.zip)


See `PositionChangedEvent` in `DiaryCarouselXF.cs` not fireing
Also see Position property not updating in `ListCarouselViewModel.cs`
View is in `ListCarouselView.xaml`

**Comment by kingces95** [comment]
Could you please attach a zipped reproduction to the bug?

**Comment by kingces95** [comment]
Hm, I'm unable to swipe. When I click add an item I'm still unable to swipe.. Am I holding it wrong?

**Comment by JKennedy24** [comment]
@kingces95 Don't click the add item button - this adds a Syncfusion listview which blocks the carousel, ignore that for now

Just try and swipe the blue background

**Comment by hartez** [comment]
@JKennedy24 Please send a _minimal_ repro with all the extra stuff stripped out. Your repro should contain only the pages necessary to demonstrate the problem, and should be using plain old Xamarin.Forms controls so we can be sure the problem is in Forms.

**Comment by JKennedy24** [comment]
[CarouselVew.zip](https://github.com/xamarin/Xamarin.Forms/files/4044982/CarouselVew.zip)

I have attached a simple repo.

Very simple repo, Page containing a `CarouselView` with a `PositionChanged` event hooked up and bound to a `Position` property in the `ViewModel`

both `PositionChanged` and `Position` property throw a `NotImplementedException` but this exception is never thrown. showing these are not working correctly.

Steps to replicate:
1. open app on uwp
2. swipe pages using touch
3. no exception thrown

**Comment by JKennedy24** [comment]
may be fixed by https://github.com/xamarin/Xamarin.Forms/commit/4b213a51e7de25b9065a8c06f76b071986be4c4a

but because this hasn't been released yet I can't test

**Comment by JKennedy24** [comment]
Looks like this is fixed in `4.5.0 Pre Release 1`

I'd imagine by the changeset linked in the previous comment

**Comment by ImproveMe-it** [comment]
@JKennedy24 
Did you tried with a new Version? 
I tried with 4.5 pre-1 to pre-4 still no success.

**Comment by JKennedy24** [comment]
@ImproveMe-it when I tried it with `pre 1` I thought it seemed to work. Had to downgrade again for another issue so can't confirm

**Comment by EmilAlipiev** [comment]
it is still now working 4.5. there is a small improvement but very often it is just stop working. you need to click a few time fire position.
