### ISSUE TITLE
Xamarin.Forms.Init : expected class 'Xamarin.Forms.ActivationFlags'

### ISSUE THREAD

**Issue by ricavir11** [xamarin/Xamarin.Forms#8803]
## Description

Getting following exception on Android xamarin forms startup at on Forms.Init(this, bundle) : 
'
System.TypeLoadException: 'Could not resolve type with token 01000013 from typeref (expected class 'Xamarin.Forms.ActivationFlags' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')'
' 

This is an exception that occurs only on latest version of Visual Studio v16.4. No problem on v16.3.X

### Steps to Reproduce

1. Just start XF project with following tool versions

### Expected Behavior

App starts

### Actual Behavior

App fails at startup with exception :
System.TypeLoadException: 'Could not resolve type with token 01000013 from typeref (expected class 'Xamarin.Forms.ActivationFlags' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')'

### Basic Information

- Version with issue: XF 4.3.0.991211
- Last known good version: XF 4.3.0.991211
- IDE: VS v16.4
- Platform Target Frameworks: 
  - Android: 9.0 (Pie)

### Screenshots

![image](https://user-images.githubusercontent.com/25507232/70438666-9bd00180-1a8e-11ea-87a2-58cf987f7d63.png)

**Comment by ricavir11** [comment]
Did you had time to check this ? 
It is a blocking issue as I can't run Android project with latest VS update v16.4.1

**Comment by samhouts** [comment]
@ricavir11  Can you please attach a small project that demonstrates this issue? Can you verify that all of your projects were successfully updated to the same nuget version? Thanks!

**Comment by MrScottyTay** [comment]
I'm getting the same issue, I also can't update the following nuget packages either: Xamarin.GooglePlayServices.Location; Xamarin.Firebase.Core; Xamarin.Forms; Xamarin.Android.Support.Design; Xamarin.Android.Support.v7.AppCompat; Xamarin.Android.Support.v4; Xamarin.Android.Support.v7.CardView; Xamarin.Android.Support.v7.MediaRouter (which might be related).

**Comment by ricavir11** [comment]
@samhouts Unfortunately, I can't attach the project has it is owned by one of my customers. 
The same project is running well on previous VS version 16.3.X without changing any nuget package.

This issue is not happening on other Xamarin projects I work with.

This is why it would take too much time to start a new project from scratch and adding nuget package per nuget package manually testing each time if project runs.

**Comment by eincioch** [comment]
![image](https://user-images.githubusercontent.com/12565944/71124917-e26edb80-21b3-11ea-94e9-4645e7eb776b.png)

Any solution to this problem, which is taking time away from me

**Comment by hartez** [comment]
@eincioch That's an issue with a completely different class; please open a new GitHub issue.

**Comment by kingces95** [comment]
This is known breaking change. Please avoid using that overload of init for now. The gains made by using activation flags are not noticeable when used in isolation. Taken as a part of a broader collection of changes the sum is noticeable.

**Comment by ricavir11** [comment]
@kingces95 : did you had a look a the original issue ? https://github.com/xamarin/Xamarin.Forms/issues/8803#issue-534924762

I'm using standard init method to initialize Xamarin Forms.

I understood that it is a breaking change...but what is the workaround please ?

**Comment by ricavir11** [comment]
Still same issue after all nuget package update.
Another XF project with almost sames nuget package works like a charm !
The only difference is the use of Prism... Can it be linked ?

**Comment by ricavir11** [comment]
For those who have same issue, I finally found a workaround. Just change linking assembly option to "SDK only" :
![image](https://user-images.githubusercontent.com/25507232/71584728-52665580-2b14-11ea-9202-d31af75d42f9.png)

I still don't know why this is happening only on VS 16.4 on not on VS 16.3... this is a kind of "bottle into the sea" for Xamarin team ;)

**Comment by dos-ise** [comment]
> Just change linking assembly option to "SD

Thank you very much! This blocked me for Days!
