### ISSUE TITLE
[Bug] Android TabbedPage Swipe Gesture triggering wrong OnDisappearing

### ISSUE THREAD

**Issue by brepetti** [xamarin/Xamarin.Forms#8804]
### Description
When using TabbedPage and using the swipe gesture to switch pages, the wrong OnDisappearing method is called.

### Steps to Reproduce

1. Launch App
2. Use Swipe Gesture
3. OnDisappearing does not fire
4, Use Swipe Gesture
5. OnDisappearing fires but for current page

### Expected Behavior
OnDisappearing should fire on first swipe for the page that is actually disappearing. 

### Actual Behavior
OnDisappearing is not firing on the first swipe.  It will fire on the second swipe but for the wrong page.  When using the regular tab buttons everything works correctly.

### Basic Information

- Version with issue: 4.3
- Last known good version: ?
- IDE: VS 2019
- Platform Target Frameworks: 
   - Android:  

- Affected Devices: All Android

### Reproduction Link
[TabbedPageOnDisappearing.zip](https://github.com/xamarin/Xamarin.Forms/files/3940199/TabbedPageOnDisappearing.zip)

Sample Reproduction Attached.

**Comment by rmarinho** [comment]
Confirmed it still happens with nightly 4.5.0.74

**Comment by kingces95** [comment]
Yep. As described.

**Comment by Edgaras91** [comment]
The issue still exists on 4.6.0.847

**Comment by billvenhaus** [comment]
This is still an issue on 5.0.0.2196.  I submitted a pull request a little bit ago that fixes it #14879
