### ISSUE TITLE
[Bug] Shell IsTabStop not working

### ISSUE THREAD

**Issue by A-Kojic** [xamarin/Xamarin.Forms#8813]
### Description
Hide some Shell items from the TabBar but keep them visible in the FlyoutItem section.

### Steps to Reproduce

1. Create new Xamarin Forms project
2. Use the following shell code and set IsTabStop="False"
`<FlyoutItem Title="Menu" FlyoutDisplayOptions="AsMultipleItems">
    <Tab Title="Item 1" Icon="icon1.png">
        <ShellContent>
            <views:PageOne />
        </ShellContent>
    </Tab>
    <Tab Title="Item 2" Icon="icon2.png">
        <ShellContent>
            <views:PageTwo />
        </ShellContent>
    </Tab>
    <Tab Title="Item 3" Icon="icon3.png">
        <ShellContent>
            <views:PageThree />
        </ShellContent>
    </Tab>
    <Tab Title="Item 4" Icon="icon4.png">
        <ShellContent>
            <views:PageFour />
        </ShellContent>
    </Tab>
</FlyoutItem>`

### Expected Behavior
Show all items in FlyoutItem section and hide selected ones in TabBar section.

### Actual Behavior
All items are displayed in both FlyoutItem and TabBar sections.

### Basic Information

- Xamarin Forms: 4.3.0.991211
- IDE: VS 2019 Community
- Platform Target Frameworks: 
  - Android 8.1
  - Android 9.0

### Screenshots (expected behavior)
https://ibb.co/TmKP2Zc

https://ibb.co/0Ymdhyz

**Comment by kingces95** [comment]
Please attach a zipped reproduction solution.

**Comment by samhouts** [comment]
@A-Kojic  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
