### ISSUE TITLE
[Bug] UWP Shell cannot host CollectionView/CarouselView

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#8814]
### Steps to Reproduce

1. Create new Shell template
2. Add UWP project
3. Add `global::Xamarin.Forms.Forms.SetFlags("Shell_UWP_Experimental");`
3. Convert ListView to CollectionView
4. Run project on UWP

### Expected Behavior

CollectionView is displayed

### Actual Behavior

CollectionView is missing

### Basic Information

- Version with issue: 4.3.0
- Last known good version: none
- IDE: VS 15.5 P1
- Platform Target Frameworks: 
  - UWP:  16299+

### Reproduction Link

[Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/3942510/TestyMcTestikins.zip)

**Comment by leo-adm** [comment]
When I resize the window, the collectionview gets loaded

**Comment by holecekp** [comment]
This is also similar to #10977.

**Comment by bmacombe** [comment]
Wonder if #11394 will resolve this?  I'll try to test it.

**Comment by bmacombe** [comment]
@samhouts I've been trying to test this, but I think I need to build nugets and then use them against your repro project.  But I've been at a loss to to figure out how to build the nugets locally.  I've tried the .create-nuget.bat without success.  I know there were instructions somewhere to create your own nugets, but I'm not finding them.

Could you point me in the right direction or suggest another way to test?  I've tried @PureWeen s Sandbox, but I can't get the original repro to fail after I copy enough code into the sandbox to re-create, so I can't validate the fix.

Thanks!

**Comment by bmacombe** [comment]
I can confirm this is still broken on 4.7.0.1179

**Comment by bmacombe** [comment]
on 4.8.0.1187-pre2 I get this though...tried a couple of times to be sure

![image](https://user-images.githubusercontent.com/15127788/88747406-4c6d3d00-d114-11ea-9b8a-7fdc7713d01a.png)

**Comment by PureWeen** [comment]
> But I've been at a loss to to figure out how to build the nugets locally.

https://github.com/xamarin/Xamarin.Forms/wiki/How-to-Build-Xamarin.Forms-NuGet

**Comment by bmacombe** [comment]
@PureWeen Thanks for that link, worked great...I'll add that to my XF toolbox!

#11394 Does appear to resolve this issue also.

Before
![Before](https://user-images.githubusercontent.com/15127788/88822808-f6d37780-d189-11ea-9b9b-0e96e9366fb5.gif)

After
![After](https://user-images.githubusercontent.com/15127788/88822820-fc30c200-d189-11ea-8f4f-a40faf97055a.gif)
