### ISSUE TITLE
[Bug] CollectionView System.ObjectDisposedException on SelectionChange

### ISSUE THREAD

**Issue by heebaek** [xamarin/Xamarin.Forms#8816]
### Description
On SelectionChanged Event(or Command) in CollectionView, if i change ViewModel 
sometimes they throw ObjectDisposedException. 

But I spent a lot of time to make a simple reproduce steps, I hope you can see the same exception.
(in my side, this repro steps  throw exception 100% )
 
attached sample project is default sample to-do app, i just changed ListView to CollectionView and add a simple selection changed event handler. 

I can't see the exception if i use just Xamarin.Forms 4.2.0.709249(this is default version of new Shell Forms app template).
but i see the exception in a latest stable, pre, nightly build. 
 
### Steps to Reproduce
1. Select first item from browse tab. 
2. go to about tab.
3. return to browse tab, select second item.
4. go to about tab.
5. return to browse tab, select third item.
6. go to about tab.
7. return to browse tab, select fourth item.

if you can't see the exception, please repeat this step until the last item.

### Expected Behavior
no exception throw.
### Actual Behavior
exception throw
### Basic Information
ios version has no problem.

### Reproduction Link

[selectbug.zip](https://github.com/xamarin/Xamarin.Forms/files/3943159/selectbug.zip)

**Comment by heebaek** [comment]
can not reproduce after XF 4.4

**Comment by kingces95** [comment]
Does appear to be fixed on latest builds. Please close if you confirm that to be the case./
