### ISSUE TITLE
[Bug] Animations of downloaded gifs are not playing on Android

### ISSUE THREAD

**Issue by hulluP** [xamarin/Xamarin.Forms#8821]
### Description
when gif is downloaded from internet and saved to filesystem and the property IsAnimationPlaying is set to true the application dumps with 
Error loading image: Android.Content.Res.Resources+NotFoundException: Resource ID #0x0
### Steps to Reproduce

1. clone git https://github.com/hulluP/AnimatedGifForms
2. run on Android device or simulator
3. app will dump once button is pressed and animation does not play. This works on iOS

### Expected Behavior
Animation plays like it does for the same gif when it is loaded from resources like the git https://github.com/jfversluis/AnimatedGifForms

### Actual Behavior
does not play animation
### Basic Information

- Version with issue: 4.4.09 pre3
- Last known good version: never worked
- IDE: Mac OS visual studio
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 7.1

- Android Support Library Version:
- Nuget Packages: xamarin.forms
- Affected Devices:

### Screenshots

<img width="1203" alt="Screenshot 2019-12-10 at 09 19 24" src="https://user-images.githubusercontent.com/46395952/70508249-64189680-1b2e-11ea-9d67-0eafbaf8c745.png">

**Comment by samhouts** [comment]
closed by #8865
