### ISSUE TITLE
[Bug] [iOS] Setting Title and Icon doesn't work properly together 

### ISSUE THREAD

**Issue by MathewLC** [xamarin/Xamarin.Forms#8829]
### Description
And I set both NavigationPage.TitleIconImageSource and ContentPage.Title, Icon overlay somehow the Title property. Trying set IconImageSource from ContentPage doesn't work either. I don't know exactly if this is how it should be or if is an Issue but I didn't find anything about this on the docs that explain why it happens.

### Expected Behavior
Work just like android and appear both properties.

### Actual Behavior
In iOS, ContentePage Title it's "overlayed".

### Basic Information

- Version with issue: Xamarin.Forms 4.3.0.991221
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  10 (Teste with simulators with iOS 11 and iOS 13.2)
  - Android: 10

### Screenshots
![image](https://user-images.githubusercontent.com/37350787/70533723-654ec100-1b38-11ea-9bef-bc0d2457a75d.png)
![image](https://user-images.githubusercontent.com/37350787/70534041-fde54100-1b38-11ea-9018-98f936c9f1fb.png)

### Reproduction Link
[iOSTitleIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3945058/iOSTitleIssue.zip)

**Comment by samhouts** [comment]
From #2586:

> Since BackTitle, Title, TitleIcon, and TitleView all occupy the same space on the navigation bar, you can expect that there will be conflicts and limited space to support all of these properties at the same time. This will vary by platform and screen size. You may find that you can better achieve your desired design by using just TitleView instead of attempting to use a combination of properties.
