### ISSUE TITLE
[Bug] The "Padding" property in the "Labels" generates an error in the UWP debug.

### ISSUE THREAD

**Issue by danielmonettelli** [xamarin/Xamarin.Forms#8834]
### Description
When adding the property "Padding" in the Label generates an error in the debugging of UWP, to solve this problem change it with the property of "Margin"

- Affected Devices:
UWP

### Reproduction Link
https://github.com/monetelli/XF_XFLabsPart1

**Comment by kingces95** [comment]
Please add an actual and expected behavior with reproduction steps.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
