### ISSUE TITLE
[Bug] ClearButtonVisibility.Never does not take effect on UWP

### ISSUE THREAD

**Issue by johnshardman** [xamarin/Xamarin.Forms#8836]
### Description

On UWP, specifying ClearButtonVisibility.Never on an Entry has no effect - the clear button still appears when the Entry gets focus.

Normally, I would not be too fussed by this, but if a page has a vertical stack of Entry Views, where each has HorizontalTextAlignment set to Center, tabbing between the Entry Views results in the Text in the Entry getting the focus jumping sideways, and the Text in the Entry losing focusing jumping the other direction. The Text of the Entry with focus will be misaligned with all of the other Entry Views.

It's a minor thing, but it should either be fixed, or the documentation at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#displaying-a-clear-button updated to say that this behavior happens and that it is by design.

### Steps to Reproduce

1. Build a vertical stack of Entry Views, with HorizontalTextAlignment set to Center, and ClearButtonVisibility set to Never. Populate each Entry with the same text.
2. Tab between the Entry Views.

For the Children of the vertical stack, I use:

                        new Entry
                        {
                            Placeholder = "Micro - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Micro, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 3,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Small - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Small, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 4,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Medium - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Medium, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 5,
                            IsTabStop = true,
                        },
                        new Entry
                        {
                            Placeholder = "Large - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Large, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 6,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Default - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Default, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 7,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Header - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Header, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 8,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Title - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Title, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 9,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Subtitle - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Subtitle, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 10,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Body - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Body, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 11,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },
                        new Entry
                        {
                            Placeholder = "Caption - fg",
                            FontSize = Device.GetNamedSize(NamedSize.Caption, typeof(Entry)),
                            HorizontalTextAlignment = TextAlignment.Center,
                            VerticalTextAlignment = TextAlignment.Center,
                            TabIndex = 12,
                            IsTabStop = true,
                            ClearButtonVisibility = ClearButtonVisibility.Never,
                            Text = "fg",
                        },

### Expected Behavior

The Clear button should not appear on any of the Entry Views

### Actual Behavior

The Clear button appears on the Entry View that has focus

### Basic Information

- Version with issue: 4.3.0.991211
- IDE: VS2019
- Platform Target Frameworks: 
  - UWP:  18362

### Screenshots

<img width="368" alt="HorizontallyCenteredEntryViewsUWP" src="https://user-images.githubusercontent.com/17166516/70560939-740d9600-1b81-11ea-8e2e-5e7722c1abaa.png">

**Comment by kingces95** [comment]
Could you please attach a zipped reproduction solution? Will circle back but having reproductions attached really helps us get through our volume of bugs.
