### ISSUE TITLE
[Bug] IndicatorView -> Doesn't Go to Last Indicator When PeekAreaInsets is Set

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#8841]
### Description

When we use PeekAreaInsets the indicator view never goes to the final dot. If it is set to 0 then it will work.

### Steps to Reproduce

1. Create a horizontal carouselview and set PeekAreaInsets
2. Add Indicator below it
3.  Try to scroll through (5 items in my case)

### Expected Behavior

Should reach last item in indicator

### Actual Behavior
so close, but doesn't get it.

### Basic Information

- Version with issue: 4.4.0-pre3
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: Android Q
  - UWP:  <Not tested
- Android Support Library Version: 28.0.0.3

### Screenshots

![image](https://user-images.githubusercontent.com/1676321/70582965-24bf6980-1b71-11ea-8a61-76abc02ac4c4.png)

### Reproduction Link

https://github.com/jamesmontemagno/Hanselman.Forms/tree/featured-items

**Comment by jsuarezruiz** [comment]
I think this issue may have been fixed with: https://github.com/xamarin/Xamarin.Forms/pull/8733/files#diff-7cc613c3265bf51dcffa3c09e16292efR85

I have done some tests.
![indicator-position-issue](https://user-images.githubusercontent.com/6755973/70716968-acca7e00-1ced-11ea-99bf-eadf2d364746.gif)

**Comment by jamesmontemagno** [comment]
Lovely! If there is a pacakge I can try it on my hanselman.forms app.

**Comment by kingces95** [comment]
Ok?

**Comment by rmarinho** [comment]
Couldn't get HanselForms to run locally :/ 

@jamesmontemagno can you try these packages.

https://dev.azure.com/xamarin/public/_build/results?buildId=11201&view=artifacts&type=publishedArtifacts

[Uploading debug.zip…]()

**Comment by rmarinho** [comment]
[nuget.zip](https://github.com/xamarin/Xamarin.Forms/files/3968137/nuget.zip)

**Comment by rmarinho** [comment]
this should be fixed . Please reopen if it's not.
