### ISSUE TITLE
WebAssembly platform fails in Xamarin.forms solution

### ISSUE THREAD

**Issue by urodolf** [xamarin/Xamarin.Forms#8853]
### Description
Creating a new project of Uno Platform into a Xamarin Forms solution following the steps of the url
https://github.com/unoplatform/Uno.Xamarin.Forms.Platform

The UWP platform runs correctly but it cannot compile the Wasm project. 
First there is an error from a ILoggerFactory because it does not implement the AddConsole(LogLevel.Trace), then I downgrade the package Microsoft.Extensions.Logging.Console to version 2.2.0.
Now the error is in the Linker beacuse failed to resolve Xamarin.Forms.Platform.UWP.CarouselViewRenderer
### Steps to Reproduce

1. Creates a Xamarin.Forms solution.
2. Add Uno platform project.
3. Update all nuget references to the last version.
4. Downgrade the nuget of Microsoft.Extensions.Logging.Console to version 2.2.0.

### Basic Information
- Xamarin:
    Xamarin.Forms Version 4.4.0.991220-pre3
    Xamarin Essentials Version 1.3.1
- Platform Target Frameworks: 
  - Uno Platform: 
    Uno.WasmBootstrap version 1.1.0-dev.391
    Uno.Wasm.Bootstrap.Cli version 1.0.0-dev.302
    Uno.Xamarin.Forms.Platform version 4.3.0-uno.141
    Uno.UI versin 2.1.0-dev.192
    Microsoft.Extensions.Logging.Filter version 1.1.2
    Microsoft.Extensions.Logging.Console version 2.20
 - UWP Platform:
    Microsoft.NetCore.UniversalWindowsPlatform version 6.2.9
    TargetPlatformVersion = TargetPlatformMinVersion = 10.0.16299.0

**Comment by kingces95** [comment]
Uno?

**Comment by PureWeen** [comment]
@urodolf this is most likely caused by API changes and UNO will need to regenerate some code in order for this to work

@jeromelaban

**Comment by jeromelaban** [comment]
Indeed, Uno does not yet target 4.4, but we'll be following the updates.

@urodolf please [open an issue here](https://github.com/unoplatform/uno/issues/new/choose), we'll help you sort this out.
