### ISSUE TITLE
[Bug] iOS ImageButton has wrong size when used vector source

### ISSUE THREAD

**Issue by kuzub** [xamarin/Xamarin.Forms#8862]
### Description
After upgrade to XF 4.4.0.991265 on iOS Image button with vector image source has wrong size

### Steps to Reproduce

1. Create new project with Xamarin.Forms 4.2.0.709249
2. Add ImageButton with vector image source (pdf)
3. Upgrade to Xamarin.Forms 4.4.0.991265

### Expected Behavior

Image button will have same size as image with same source

### Actual Behavior

Image button will have NOT same size as image with same source

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 4.3.0.991221
- IDE: Visual Studio Community 2019 for Mac Version 8.3.11 (build 1)
- Platform Target Frameworks: iOS
  - iOS:  13.3
- Nuget Packages:
    Xamarin.Forms 4.4.0.991265
    Xamarin.Essentials 1.3.1

### Screenshots

![iOS XF 4 2](https://user-images.githubusercontent.com/2078011/70698365-fc9a4c80-1ccf-11ea-9adb-ad462b39ac91.png)

![iOS XF 4 4](https://user-images.githubusercontent.com/2078011/70698394-0e7bef80-1cd0-11ea-8f69-033453a84e13.png)

### Reproduction Link

https://github.com/kuzub/ImageButtonIssue

**Comment by sermetk** [comment]
@kuzub did you try on renderer:
               ```
Control.HorizontalAlignment = UIControlContentHorizontalAlignment.Center;
Control.VerticalAlignment = UIControlContentVerticalAlignment.Center;
```

**Comment by kingces95** [comment]
Reproduces as described.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9054
