### ISSUE TITLE
[Bug] CollectionView with HTML Labels Freeze the Screen on Rotation

### ISSUE THREAD

**Issue by KinaUna** [xamarin/Xamarin.Forms#8870]
### Description
Labels with TextType=HTML in a CollectionView freezes the screen on rotation.
The application becomes unresponsive, but no errors appear.

### Steps to Reproduce

1. Create a Page with a CollectionView with ItemTemplate containing a Label that uses TextType=HTML
2. Launch/Debug the iOS application.
3. Go to the page and then rotate the screen.

### Expected Behavior
The page should rotate and resize the page and contents.

### Actual Behavior
The page freezes. No errors are showing, and it is not responding to any input.
Occasionally it will rotate correctly once, but most of the time it freezes as soon as the rotation begins.

If you push a modal on top of the page, rotate, and then pop the modal it appears rotated and responsive.
Overriding OnSizeAllocated and clearing the items in ItemsSource or replacing them, before calling base.OnSizeAllocated(width, height), also works.

This happens with iOS only.
Android and UWP (resize window) works as expected.
It also works as expected with TextType=Text or if the CollectionView is replaced with a ListView.

Clear the 
### Basic Information

- Version with issue: 4.3, 4.4
- Last known good version:
- IDE: Visual Studio 2019 (version 16.4.1)
- Platform Target Frameworks: 
  - iOS:  13.3 (Physical device), 13.2 (Emulator), 12.4 (Emulator)
 

### Reproduction Link

https://github.com/KinaUna/HtmlLabelFreeze

**Comment by kingces95** [comment]
After rotation, expected scroll to persist after releasing touch. Actually scrolls back to where list started. So it kinda bounces. Rotating back froze the app.
