### ISSUE TITLE
[Enhancement] Extend TappedGestureRecognizer Tapped Event with Data

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/Xamarin.Forms#8876]
## Summary
Today, Tapped is just a generic EventHandler. It doesn't pass any data to the event. If you are using this inside of a CollectionView you often need data like the bound object. So passing in something such as a EventParameter would be really nice.

We can do this with commands today:

```csharp
Command="{Binding Source={RelativeSource AncestorType={x:Type vm:FlightResultsViewModel}}, Path=GoToDetailsCommand}" CommandParameter="{Binding .}"/>
```

Maybe combinded with https://github.com/xamarin/Xamarin.Forms/issues/5347 we could get nice EventHandler

## API Changes

Update to a TappedEventHandler with some properties?

Not sure an open to ideas.

## Intended Use Case
match functionality of a command

**Comment by KSemenenko** [comment]
#7324 Will there be enough data?

**Comment by jamesmontemagno** [comment]
I would want to pass some data in like the data item that the user is tapping. So if i had the element it was on i could grab the binding context for instance, however passing in some arbitrary data would be ideal like a "person" for instance.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
