### ISSUE TITLE
[Bug] Shell Flyout - Weird line at the bottom of the items in iOS

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#8881]
### Description
There is an unwanted line below the MenuItems or FlyoutItems in Shell. 

### Steps to Reproduce

1. Run the repro project with MenuItems and flyoutItems one by one.

### Basic Information

- Version with issue:4.4.0.991265
- IDE:VSMac
- Affected Devices:iOS

### Reproduction Link
[FlyoutBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3960396/FlyoutBug.zip)

**Comment by kingces95** [comment]
Could you please attach screenshot with an annotation of the unwanted line?

**Comment by HobDev** [comment]
The arrow is pointing towards unwanted line

![Simulator Screen Shot - iPhone 11 - 2019-12-14 at 20 11 42](https://user-images.githubusercontent.com/9531864/70850249-4771bb00-1eae-11ea-8a2e-bd548bcc9435.png)

**Comment by samhouts** [comment]
closed by #9429
