### ISSUE TITLE
[Enhancement] Can we have a property to set the Outline/Border Color of the Fixed IndicatorView shape.

### ISSUE THREAD

**Issue by AnthonyNjuguna** [xamarin/Xamarin.Forms#8882]
## Summary
Can we add a property to allow a user to set/change the outline/border color of the IndicatorView's shape. 

## API Changes

Add a new property - IndicatorBorderColorProperty

In order to facilitate the new IndicatorView api, a color is added to the IndicatorView class.

    var indicatorView = new IndicatorView ();
    indicatorView.BorderColor = Color.Blue; // new API

## Intended Use Case
Use case would be having all circle indicators have an outline color eg. Purple and when the view is swiped the circle is "filled" in.

![Screenshot 2019-12-13 at 12 58 17](https://user-images.githubusercontent.com/2676560/70802009-40f91b80-1da8-11ea-8988-409838328a23.png)

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
