### ISSUE TITLE
Burger Color Menu

### ISSUE THREAD

**Issue by msvcomgt** [xamarin/Xamarin.Forms#8890]
I have followed the instructions of the Android documentation of a Shell Renderer to be able to set a color image of the Shell hamburger menu, but I do not see how to do this in ios, the code I use is the following and I would like to replicate it in iOS If you could help me, I would appreciate it

`
namespace Banrural.Droid.Controls
{
    public class BanruralShellRenderer : ShellRenderer
    {
        public BanruralShellRenderer(Context context) : base(context)
        {
        }

        protected override IShellToolbarAppearanceTracker CreateToolbarAppearanceTracker()
        {
            return new MyShellToolbarAppearanceTracker();
        }

        internal class MyShellToolbarAppearanceTracker : IShellToolbarAppearanceTracker
        {

            public void Dispose()
            {
                
            }

            public void ResetAppearance(Toolbar toolbar, IShellToolbarTracker toolbarTracker)
            {
                toolbar.SetNavigationIcon(Resource.Drawable.menu);
            }

            public void SetAppearance(Toolbar toolbar, IShellToolbarTracker toolbarTracker, ShellAppearance appearance)
            {
                toolbar.SetNavigationIcon(Resource.Drawable.menu);
            }
        }

    }
}
`

**Comment by samhouts** [comment]
@PureWeen Are we missing an extension point?

**Comment by PureWeen** [comment]
@codvel89 are you just trying to set your own image? or are you trying to tint the Hamburger icon?

You should be able to use
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#back-button-behavior

Or use this
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#flyout-icon

Or use 
*Shell.ForegroundColor=""*

To set the tintcolor

If none of that works let me know and I can hopefully point you to the right place in the renderer to work with

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
