### ISSUE TITLE
[Bug] [Android] Picker inside CollectionView.Header not binding data.

### ISSUE THREAD

**Issue by albertoha94** [xamarin/Xamarin.Forms#8894]
### Description
It seems that if you place a Picker inside the header of a CollectionView.
The binding for its itemsSource doesn't work correctly.

### Steps to Reproduce

1.Create a CollectionView inside your page.
2.Add a Picker.
3.Set its data via a binding with MVVM.

### Expected Behavior
The picker should bind with the data and display it.

### Actual Behavior
There is no data set inside the Picker INSIDE the CollectionView.
Data does appear when its outside.

### Basic Information

- Version with issue: From 4.3.0.819712-pre2 to 4.5.0.56-nightly.
- Last known good version: -
- IDE: Visual Studio Community 2019 Preview 16.4.0 Preview 2.0
       Visual Studio Community 2019 16.3.8
       
- Platform Target Frameworks: 
  - iOS:  13.6.12
  - Android: 9.0
  - UWP:  Windows 10, Version 1903 (10.0; Build 18362)
- Android Support Library Version: -
- Nuget Packages:
	Xamarin.Forms 4.5.0.56-nightly
- Affected Devices: tested on a real device AND an emulator and the issue persisted on both.

### Screenshots
iOS:
![ios](https://user-images.githubusercontent.com/14353851/70858506-dee40780-1ec8-11ea-8c88-adbc43d44220.png)
UWP:
![uwp](https://user-images.githubusercontent.com/14353851/70858507-df7c9e00-1ec8-11ea-9dea-aee1303e3b62.png)
Android:
![android](https://user-images.githubusercontent.com/14353851/70858508-df7c9e00-1ec8-11ea-922d-0ffaea24aa48.png)

### Reproduction Link
I made a small project with this issue.
All the tests I made where done in this project.
[PickerInCollectionView.zip](https://github.com/xamarin/Xamarin.Forms/files/3964634/PickerInCollectionView.zip)

**Comment by AdamDiament** [comment]
Just to say, I am having this same issue, I have made a repro that reproduces the exact behaviour which I've attached for reference.

I found it by searching for a similar issue I'm having where I am able to populate the picker items and select one, from a picker inside a collectionview, but then when you scroll down and back up again the selection gets unset. 

However I am unable to reproduce this second bug in a test repro so it may be something to do with my personal settings - but just so it's reported!

[PickerRerpo.zip](https://github.com/xamarin/Xamarin.Forms/files/3987162/PickerRerpo.zip)

**Comment by ramilbgd** [comment]
Hello. I have the same problem in an android app. In HeaderView from CollectionView  does not work out binding properties from a ViewModel. But if this property is inside the collection that we specify in ItemSource CollectionView, then in that case the data is displayed. There are no such problems in the iOS application

**Comment by hartez** [comment]
@AdamDiament I think you are seeing a different problem than @albertoha94 - you should open a separate GitHub issue.

**Comment by bio90** [comment]
I'm not sure if it's a bug or not but you need to specify the context to which you bind in order for it to work.

An example from your code:

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="PickerInCollectionView.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:vm="clr-namespace:PickerInCollectionView.ViewModels"
    x:Name="myPage"
    x:DataType="vm:MainViewModel"
    mc:Ignorable="d">

    <StackLayout>
        
        <Label
            HorizontalOptions="Center"
            Text="Picker outisde of collection"
            VerticalOptions="CenterAndExpand" />
        <Picker
            Title="outside collection"
            ItemDisplayBinding="{Binding Name}"
            ItemsSource="{Binding GameVersions}"
            SelectedItem="{Binding GameVersionSelected}" />
        <Label
            HorizontalOptions="Center"
            Text="Picker inside of collection"
            VerticalOptions="CenterAndExpand" />
        <CollectionView>
            <CollectionView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Baboon</x:String>
                    <x:String>Capuchin Monkey</x:String>
                    <x:String>Blue Monkey</x:String>
                    <x:String>Squirrel Monkey</x:String>
                    <x:String>Golden Lion Tamarin</x:String>
                    <x:String>Howler Monkey</x:String>
                    <x:String>Japanese Macaque</x:String>
                </x:Array>
            </CollectionView.ItemsSource>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Label Text="{Binding .}" />
                </DataTemplate>
            </CollectionView.ItemTemplate>
            <CollectionView.Header>
                <Picker
                    Title="Inside collection"
                    ItemDisplayBinding="{Binding Name}"
                    ItemsSource="{Binding Source={x:Reference myPage}, Path=BindingContext.GameVersions}"
                    SelectedItem="{Binding Source={x:Reference myPage}, Path=BindingContext.GameVersionSelected}" />
            </CollectionView.Header>
        </CollectionView>
    </StackLayout>

</ContentPage>
`

The key here are the x:Name="myPage" on the entire page and then i specified the binding source like so "ItemsSource="{Binding Source={x:Reference myPage}, Path=BindingContext.GameVersions}"

**Comment by modplug** [comment]
I'm having the same issue trying to bind data to a slider, button, label in my header. Seems like the bindingcontext of the CollectionView isn't being passed on to the CollectionView.Header

**Comment by NicoaraBogdan** [comment]
Still having a binding issue on windows. On page initialization I load data in a observableCollection, in xaml I have collectionView that has a picker and I bind to it a property but it sets the property value to null. In my model I added on the propertys setter a null check but the value is still not displayed


```
Task.Run(async () =>
        {
            var res = await jobsService.GetJobs(this.IdClient);

            MainThread.BeginInvokeOnMainThread(() =>
            {
                this.Jobs.AddRange(res);
            });

            this.InitialJobs = res.Select(x => new JobDto(x)).ToList();
        });
```

```<CollectionView ItemsSource="{Binding Jobs}" SelectionMode="Single">
            <CollectionView.ItemsLayout>
                <GridItemsLayout Orientation="Vertical" VerticalItemSpacing="10"/>
            </CollectionView.ItemsLayout>
            <CollectionView.ItemTemplate>
                <DataTemplate x:DataType="data:JobDto">
                    <Grid ColumnDefinitions="*, *, *, *, *" ColumnSpacing="10" VerticalOptions="Center">
                        <ndtp:NullableDateTimePicker HorizontalOptions="Center" VerticalOptions="Center" NullableDateTime="{Binding PropousedFor}"/>
                        
                        <Picker 
                            Grid.Column="1"
                            WidthRequest="150"
                            ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type vm:ClientsJobsViewModel}}, Path=Services}"
                            SelectedItem="{Binding ServiciuPrestat}"/>
```

**Comment by NicoaraBogdan** [comment]
Ok found a workaround. You can define the item source in xaml and then it works as expected

```
   <Picker 
                            Grid.Column="1"
                            WidthRequest="150"
                            SelectedItem="{Binding ServiciuPrestat}">
                            <Picker.ItemsSource>
                                <x:Array Type="{x:Type x:String}">
                                    <x:String>Deratizare</x:String>
                                    <x:String>Dezinfectie</x:String>
                                    <x:String>Dezinsectie</x:String>
                                </x:Array>
                            </Picker.ItemsSource>
                        </Picker>
```
