### ISSUE TITLE
Xamarin.Forms.Platform.MacOS

### ISSUE THREAD

**Issue by ubhaya** [xamarin/Xamarin.Forms#8895]
### Description
I have created a Cocoa App and IOS App using xamarin forms with  [two dotnet standard library](https://github.com/damienaicheh/XFDownloadProject.git) which link here. IOS app works fine but Cocoa app throws null exception in Forms.Init() Method. I can upload the projet files but i cannot figure out the way.

- Version with issue: 4.4.0.991265
- IDE: Visual Studio for Mac

**Comment by jfversluis** [comment]
You can zip the reproduction project and drag that zip file into the box where you write the comment :)

**Comment by ubhaya** [comment]
File uploaded
[XFDownloadProject.zip](https://github.com/xamarin/Xamarin.Forms/files/3964881/XFDownloadProject.zip)

**Comment by rmarinho** [comment]
This seems something with sigining and entitlements. Are you runing with a valid sigining identity ?

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
