### ISSUE TITLE
Clearing CollectionView IsGrouped="True" crashes application iOS & UWP

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/Xamarin.Forms#8899]
### Description

Clearing CollectionView with IsGrouped="True" crashes iOS, works fine on android.

Unhandled exception being raised:

```csharp
System.ArgumentOutOfRangeException: 'Index was out of range.
Must be non-negative and less than the size of the collection.
Parameter name: index'
```

### Steps to Reproduce

In my case (see reporoduction)

1. Select a option from the picker in the navigationbar that will clear current list, then sets a new filtered grouped to collectionview again.

### Expected Behavior

App not to crash

### Actual Behavior

App crashes.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: Unknown
- IDE: visual studio 2019 community
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android:  
  - UWP:  9.0 
- Android Support Library Version: NA
- Nuget Packages: NA
- Affected Devices: Emulator iPad 5th Generation 10.3.

### Screenshots

**THIS IS HOW IT IS WORKING FINE ON ANDROID **

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5468757/70869527-cff87480-1ff0-11ea-8924-e24d740e72be.gif)

**THIS IS HOW IT IS WORKING NOT FINE ON IOS - GIF ENDS WHEN THE APP CRASHES**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5468757/70870162-c3761b00-1ff4-11ea-81a8-6a4b68191ff7.gif)

### Reproduction Link

Code behind simply clears the colllectionview and adds new collection of items when picker selected. Crashes on clear or when adding new items.

[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3965518/TestApp.zip)

**Comment by hartez** [comment]
@LeoJHarris I'm trying to verify your repro project, but the iOS project doesn't build. Says it can't find `Assets.xcassets/LaunchImage.launchimage/Contents.json` when building. Are there possibly some files missing?

**Comment by LeoJHarris** [comment]
@hartez sorry probably are. Ill double check the sample repo

**Comment by samhouts** [comment]
@LeoJHarris Thanks! We'll wait for an update from your side.

**Comment by LeoJHarris** [comment]
@samhouts Just getting the chance to revisit this now.

**Comment by LeoJHarris** [comment]
Can you check the new repo now attached? 

[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4061845/TestApp.zip)

Was just missing the launch images asset catalog folder which I have added now.

**Comment by hartez** [comment]
Turns out this crashes on UWP as well. ಠ_ಠ
