### ISSUE TITLE
[Bug] UWP Properties don't persist

### ISSUE THREAD

**Issue by Jalroka** [xamarin/Xamarin.Forms#8901]
### Description
On UWP Properties doesn't persist unless the app is shut down normally, exceptions, restarting the computer can trigger this.  This is especially problematic on windows Iot core as only a single application can be set as the head application and even writing code to allow the app to reboot the computer or restart the app won't trigger the long term persistance.  After app restart the persisted values are not there.
### Steps to Reproduce

1.         private string LoadWarehouseFromSettings()
        {
            object value;
            this.Properties.TryGetValue(warehousekey, out value);
            return value as string ?? "";
        }

        public void PersistWarehouse(string warehouse)
        {
            if (this.Properties.ContainsKey(warehousekey))
            {
                this.Properties.Clear();
            }
            this.Properties.Add(warehousekey, warehouse);
        }
2. 
3. 

### Expected Behavior
To have persisted values after application restart.
### Actual Behavior
Persisted values are not there if app didn't shut down normally.
### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: none
- IDE: VS Enterprise 2019
- Platform Target Frameworks: 
  - UWP:  The version of the UWP SDK you are compiling against, e.g. 16299
- Nuget Packages:
- Affected Devices: Iot Core Raspberry Pi 3

**Comment by WayaFlyfeather** [comment]
You can use [Application.SavePropertiesAsync()](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.savepropertiesasync?view=xamarin-forms) after setting the properties, to make sure they are persisted, even if a crash happens before the values would otherwise be saved.

**Comment by hartez** [comment]
@Jalroka 

@WayaFlyfeather is correct; if you need to be sure that your properties will survive a device restart or other unexpected event, you'll need to call the SavePropertiesAsync method after you've updated them.  In your case, calling it at the end of `PersistWarehouse` is probably the answer.
