### ISSUE TITLE
[BUG][iOS] CarouselView Layout on orientation change

### ISSUE THREAD

**Issue by Martin080793** [xamarin/Xamarin.Forms#8902]
#8025 # Description
The CarouselView doesn't relayout when changing the device orientation.
### Steps to Reproduce

1. Run Project
2. Tilt your Device to landscape/portrait mode

### Expected Behavior
The View should adjust to the new heights/widths, like on Android.
### Actual Behavior
The View doesn't relayout. Some parts become invisible or look 
### Basic Information

- Nuget Packages: 4.4.0.991265
- Last known good version: /
- IDE: Visual Studio 2019 Pro 16.4.1
- Platform Target Frameworks: 
  - iOS:  13.8.3

- Affected Devices: iPhone/iPad

### Screenshots
![IMG_0025](https://user-images.githubusercontent.com/19857832/70898074-3a5ee400-1ff4-11ea-94d6-966307da748f.PNG)
![IMG_0026](https://user-images.githubusercontent.com/19857832/70898088-421e8880-1ff4-11ea-9193-5cac0819555a.PNG)

### Reproduction Link
[CarouselBug.zip](https://github.com/xamarin/Xamarin.Forms/files/3967397/CarouselBug.zip)

**Comment by rmarinho** [comment]
@hartez think this one is more related with CollectionView, imo we need to set Constrains again when the BoundsSize change . 

Any thoughts on this?

**Comment by hartez** [comment]
@rmarinho I think you're right. ItemsView is supposed to re-compute the constraints on a bounds change, so it looks like there's a bug. I think I saw another issue filed specifically about CollectionView.

I'll take a look at it.

**Comment by Martin080793** [comment]
This only works if the CarouselView is a direct child of ContentPage.Content.
If you put the CarouselView in a Grid/StackLayout the issue persists.

**Comment by Martin080793** [comment]
When i'm on "User 2" of the sample and go to landscape i looks like this:

![IMG_0028](https://user-images.githubusercontent.com/19857832/72974023-9c1e2500-3dce-11ea-9adb-85cd9e448818.PNG)

**Comment by luccasclezar** [comment]
I have a CarouselView inside a Grid (with an IndicatorView) and as @Martin080793 said, this issue persists.

I tested with 4.4.0 Service Release 3 and 4.6.0.274-nightly.

**Comment by rickytribbia** [comment]
I have a CarouselView inside a Grid with IndicatorView too and I report the same issue.

**Comment by rickytribbia** [comment]
@luccasclezar and @Martin080793 Have you tried to remove the carousel (or the grid itself) from the `ContentPage.Content` and re-apply after the rotation? I'm trying but with no success, for now.
Have you found any other solution or workaround?

**Comment by rmarinho** [comment]
Yap, sorry guys, working on a new fix. #9654

**Comment by phuccut** [comment]
@rmarinho Sorry but this bug still reproduce on version 4.5.0.356.
I have added CarouselView into Grid and it's not resize when orientation changed.
Please check again.

**Comment by nate123456** [comment]
I'm having this problem as well in iOS. It seems that setting the CarouselView as the ContentPage.Content is the only scenario that actually enables the CarouselView to correctly adjust when rotation occurs.

**Comment by rmarinho** [comment]
@phuccut  and @nate123456  can you try 4.6.0.379-pre1

**Comment by rmarinho** [comment]
It didn't hit the 4.5.0 stabel version, but will be in the 4.5.0-sr1 that will push maybe today. But the 4.6.0 pre1 should have that fix.

**Comment by nate123456** [comment]
I downloaded Xamarin.Forms.4.6.0.379-pre1 and tried my CarouselView setup and it does appear to be working much better. I did notice a few issues though.

When rotating on iOS, I noticed that, for a moment during the rotation, I could sometimes see a portion of the next item in the CarouselView. Perhaps this is just the expected experience on iOS and scrollable views.

I also noticed that when I rotated my iOS device, for a moment during the rotation, my CarouselView is not shown (I can see its parent grid), then the CarouselView reappears. It's almost as if the CarouselView is removed from the grid then added again. The end result is a sort of flashing effect when rotating. I can reduce how visually impactful it is by making the background of the grid a more similar color to the contents of the CarouselView, but it's not ideal. This does not occur with other elements on the page, only with the CarouselView. This issue did not occur on Android.

**Comment by nate123456** [comment]
I made an issue for that flashing issue [here](https://github.com/xamarin/Xamarin.Forms/issues/9860).

**Comment by albilaga** [comment]
I am still having this issue on Xamarin.Forms 5.0.0.2012 on spesific carousel view.
My workaround right now is to use custom renderer for carouselview in iOS and reload data on `CollectionView` when orientation change like this

```cs
public class CustomCarouselViewRenderer : CarouselViewRenderer
{
        private double _width;

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs changedProperty)
        {
            base.OnElementPropertyChanged(sender, changedProperty);
            if (changedProperty.PropertyName != VisualElement.WidthProperty.PropertyName ||
                _width <= 0 ||
                Element.Width <= 0 ||
                // ReSharper disable once CompareOfFloatsByEqualityOperator
                Element.Width == _width)
            {
                _width = Element.Width;
                return;
            }

            Controller.CollectionView.ReloadData();
        }
}
```

**Comment by abhimanyusinghal** [comment]
Is there any update on this Issue? This is a major blocker in effectively using CarouselView

**Comment by tienhoangt** [comment]
thank you @albilaga. Its work for me.

**Comment by pareshhirapara** [comment]
As info, the workaround suggested by @albilaga does works but forces a reload of the data in the collection view.  We have a webview inside a carouselview and orientation change forces the page being viewed to get reloaded which resets the scroll, form, etc.  This works on Android but on iOS orientation change makes the carouselview (and the webview) unusable.

**Comment by hofipetr** [comment]
Thank you @albilaga. Your solution was great help for me.
I just replaced
`Controller.CollectionView.ReloadData();`
with
`Controller.CollectionView.CollectionViewLayout.InvalidateLayout();`

In my project, ReloadData sometimes switched order of visible UICollectionViewCells, but CarouselView didn't update model binding correctly. As a result, CarouselView was showing wrong content after rotation. Using InvalidateLayout works better.
