### ISSUE TITLE
[Bug] Shell: OnAppearing / OnDisappearing not triggered after return from modal page

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#8904]
### Description
In a shell-app-"page", if you navigate to a "modalPage" and go back to "page", OnAppearing is not triggered on "page". Worse, if you then navigate away from "page" to another page, OnDisappearing is not triggered either. After coming back to "page", Appearing works again. For "modalPage", OnAppearing and OnDisappearing works fine.
I took a blank shell-app and added OnDisappearing to ItemsPage.xaml.cs. See attached project.

### Steps to Reproduce

1. Take attached project and put breakpoints (or Debug.Writeline) on OnAppearing and OnDisappearing
2. On the "Browse-page", click "ADD" (go to modal "NewItemPage") => OnDisappearing (OK)
3. Click "CANCEL" (back to "browse-page") => OnAppearing should be triggered, but doesn't
4. Click "About" (navigating away from "browse-page") => OnDisappearing should be triggered, but doesn't
5. Click "Browse" => OnAppearing triggered (OK)

### Expected Behavior
See above
### Actual Behavior
See above
### Basic Information

- Version with issue: tested with 4.3.0.908675 and 4.4.0.991210
- Last known good version: ?
- IDE: Visual studio 16.4.1
- Platform Target Frameworks: 
  - iOS:  not tested
  - Android: 9
  - UWP:  not tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link
[OnAppearingIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/3967568/OnAppearingIssue.zip)

**Comment by rmarinho** [comment]
This could be addressed on work based on #6919

**Comment by rmarinho** [comment]
This is only a issue on Android, works fine on iOS

**Comment by SneWs** [comment]
This is a real PITA for us as we are building a fairly big application where we have (from the looks of it) gone and used Shell. Any ETA on this?

**Comment by jpmirfcb** [comment]
> This is a real PITA for us as we are building a fairly big application where we have (from the looks of it, made a mistake) going with and using Shell. Any ETA on this?

Or any workaround?

**Comment by samhouts** [comment]
closed by #10048
