### ISSUE TITLE
[Bug]  Xamarin storyboard not loading on Mac or windows

### ISSUE THREAD

**Issue by slushpuppy** [xamarin/Xamarin.Forms#8907]
### Description

Storyboard doesn't load on Windows or on Mac. Both are updated to the latest version and I am using xcode 11.3. Creating a new storyboard/new project results in the same issue. Storyboard works using xcode designer however

>     [2019-12-16 05:26:14.4] INFO: Beginning the boostrap process for DCC708A8-E3FF-4F7E-8D3E-30D5041F5AF2 (iPad mini 4, iOS SDK 13.3 at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot)
> 
>     [2019-12-16 05:26:14.4] PERF: - Waited 1ms to clean up
> 
>     [2019-12-16 05:26:14.4] PERF: - Waited 2ms for device to finish creating
> 
>     [2019-12-16 05:26:16.3] PERF: - Booting time: 1907ms
> 
>     [2019-12-16 05:26:16.4] WARN: Framebuffer unavailable; Xcode 10+ requires Library.Disposition.Local
> 
>     [2019-12-16 05:26:16.4] PERF: - Registering services: 11ms
> 
>     [2019-12-16 05:26:29.2] ERROR: Could not find SimulatorBridge after spawning it... bailing out.
> 
>     [2019-12-16 05:26:29.3] ERROR: Service port lookup had failed with: Error Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to lookup service com.apple.iphonesimulator.bridge.2348: 0x3" UserInfo={NSLocalizedDescription=Unable to lookup service com.apple.iphonesimulator.bridge.2348: 0x3, NSUnderlyingError=0x7ff884722c50 {Error Domain=NSPOSIXErrorDomain Code=3 "No such process"}}
> 
>     [2019-12-16 05:26:29.3] INFO: An unexpected error happened trying to start the designer. Attempting to erase our device. System.InvalidOperationException: Simulator services were not available after booting the simulator. Perhaps it has crashed. at MonoTouch.Hosting.FullSession.LookupServices () [0x0009b] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Hosting.FullSession.Start () [0x00312] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x000c7] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:289 [2019-12-16 05:26:29.3] ERROR: An exception occurred while launching, forcibly restarting the session. [2019-12-16 05:26:30.9] PERF: Total time for shutting down: 1571ms
> 
>     [2019-12-16 05:26:33.2] INFO: Successfully killed the entire session [2019-12-16 05:26:33.2] ERROR: EnsureSession (counter 2): System.AggregateException: One or more errors occurred. (One or more errors occurred. (Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown.)) (Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown.) ---> MonoTouch.Design.Client.InvalidSessionException: Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown. ---> Foundation.NSErrorException: Error Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to erase contents and settings in current state: Booted" UserInfo={NSLocalizedDescription=Unable to erase contents and settings in current state: Booted} at MonoTouch.Hosting.Device.ResetContentAndSettings () [0x0001d] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x000ff] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:298 --- End of inner exception stack trace --- at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x001e8] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:323 at MonoTouch.Design.Client.ServerProcessConnection.SendRequestCore (MonoTouch.Design.CommandRequest request, System.Boolean throwIfNotRunning) [0x00057] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:282 at MonoTouch.Design.Client.ServerProcessConnection.SendRequest (MonoTouch.Design.CommandRequest req, System.Boolean throwIfNotRunning) [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:230 at MonoTouch.Design.Client.ServerProcessConnection.SendRequest[TResponse] (MonoTouch.Design.CommandRequest req, System.Boolean throwIfNotRunning) [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:252 at MonoTouch.Design.Client.ServerProcessConnection.CreateSession () [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:111 at MonoTouch.Design.Client.ServerProcessConnection.b__28_0 () [0x00000] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:116 at System.Threading.Tasks.Task1[TResult].InnerInvoke () [0x0000f] in
>       /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534
>       at System.Threading.Tasks.Task.Execute () [0x00000] in
>       /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319
>       --- End of inner exception stack trace ---
>       ---> (Inner Exception #0) MonoTouch.Design.Client.InvalidSessionException: Exception of type
>       'MonoTouch.Design.Client.InvalidSessionException' was thrown. --->
>       Foundation.NSErrorException: Error
>       Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to erase
>       contents and settings in current state: Booted"
>       UserInfo={NSLocalizedDescription=Unable to erase contents and settings
>       in current state: Booted}   at
>       MonoTouch.Hosting.Device.ResetContentAndSettings () [0x0001d] in
>       <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0    at
>       MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning
>       (System.Boolean throwIfNotRunning) [0x000ff] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:298
>       --- End of inner exception stack trace ---   at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning
>       (System.Boolean throwIfNotRunning) [0x001e8] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:323
>       at MonoTouch.Design.Client.ServerProcessConnection.SendRequestCore
>       (MonoTouch.Design.CommandRequest request, System.Boolean
>       throwIfNotRunning) [0x00057] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:282
>       at MonoTouch.Design.Client.ServerProcessConnection.SendRequest
>       (MonoTouch.Design.CommandRequest req, System.Boolean
>       throwIfNotRunning) [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:230
>       at
>       MonoTouch.Design.Client.ServerProcessConnection.SendRequest[TResponse]
>       (MonoTouch.Design.CommandRequest req, System.Boolean
>       throwIfNotRunning) [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:252
>       at MonoTouch.Design.Client.ServerProcessConnection.CreateSession ()
>       [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:111
>       at
>       MonoTouch.Design.Client.ServerProcessConnection.<CreateSessionAsync>b__28_0
>       () [0x00000] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:116
>       at System.Threading.Tasks.Task1[TResult].InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 <---
> 
>     [2019-12-16 05:26:33.2] INFO: Invalidating all connections [2019-12-16 05:26:33.2] INFO: Beginning the boostrap process for DCC708A8-E3FF-4F7E-8D3E-30D5041F5AF2 (iPad mini 4, iOS SDK 13.3 at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot)
> 
>     [2019-12-16 05:26:33.2] PERF: - Waited 1ms to clean up
> 
>     [2019-12-16 05:26:33.2] PERF: - Waited 3ms for device to finish creating
> 
>     [2019-12-16 05:26:34.9] PERF: - Booting time: 1694ms
> 
>     [2019-12-16 05:26:35.1] WARN: Framebuffer unavailable; Xcode 10+ requires Library.Disposition.Local
> 
>     [2019-12-16 05:26:35.1] PERF: - Registering services: 11ms
> 
>     [2019-12-16 05:26:46.5] ERROR: Could not find SimulatorBridge after spawning it... bailing out.
> 
>     [2019-12-16 05:26:46.6] ERROR: Service port lookup had failed with: Error Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to lookup service com.apple.iphonesimulator.bridge.2348: 0x3" UserInfo={NSLocalizedDescription=Unable to lookup service com.apple.iphonesimulator.bridge.2348: 0x3, NSUnderlyingError=0x7ff8868146e0 {Error Domain=NSPOSIXErrorDomain Code=3 "No such process"}}
> 
>     [2019-12-16 05:26:46.6] INFO: An unexpected error happened trying to start the designer. Attempting to erase our device. System.InvalidOperationException: Simulator services were not available after booting the simulator. Perhaps it has crashed. at MonoTouch.Hosting.FullSession.LookupServices () [0x0009b] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Hosting.FullSession.Start () [0x00312] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x000c7] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:289 [2019-12-16 05:26:46.6] ERROR: An exception occurred while launching, forcibly restarting the session. [2019-12-16 05:26:48.4] PERF: Total time for shutting down: 1812ms
> 
>     [2019-12-16 05:26:50.7] INFO: Successfully killed the entire session [2019-12-16 05:26:50.7] ERROR: EnsureSession (counter 3): System.AggregateException: One or more errors occurred. (One or more errors occurred. (Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown.)) (Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown.) ---> MonoTouch.Design.Client.InvalidSessionException: Exception of type 'MonoTouch.Design.Client.InvalidSessionException' was thrown. ---> Foundation.NSErrorException: Error Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to erase contents and settings in current state: Booted" UserInfo={NSLocalizedDescription=Unable to erase contents and settings in current state: Booted} at MonoTouch.Hosting.Device.ResetContentAndSettings () [0x0001d] in <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0 at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x000ff] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:298 --- End of inner exception stack trace --- at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning (System.Boolean throwIfNotRunning) [0x001e8] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:323 at MonoTouch.Design.Client.ServerProcessConnection.SendRequestCore (MonoTouch.Design.CommandRequest request, System.Boolean throwIfNotRunning) [0x00057] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:282 at MonoTouch.Design.Client.ServerProcessConnection.SendRequest (MonoTouch.Design.CommandRequest req, System.Boolean throwIfNotRunning) [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:230 at MonoTouch.Design.Client.ServerProcessConnection.SendRequest[TResponse] (MonoTouch.Design.CommandRequest req, System.Boolean throwIfNotRunning) [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:252 at MonoTouch.Design.Client.ServerProcessConnection.CreateSession () [0x00001] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:111 at MonoTouch.Design.Client.ServerProcessConnection.b__28_0 () [0x00000] in /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:116 at System.Threading.Tasks.Task1[TResult].InnerInvoke () [0x0000f] in
>       /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534
>       at System.Threading.Tasks.Task.Execute () [0x00000] in
>       /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319
>       --- End of inner exception stack trace ---
>       ---> (Inner Exception #0) MonoTouch.Design.Client.InvalidSessionException: Exception of type
>       'MonoTouch.Design.Client.InvalidSessionException' was thrown. --->
>       Foundation.NSErrorException: Error
>       Domain=com.apple.CoreSimulator.SimError Code=165 "Unable to erase
>       contents and settings in current state: Booted"
>       UserInfo={NSLocalizedDescription=Unable to erase contents and settings
>       in current state: Booted}   at
>       MonoTouch.Hosting.Device.ResetContentAndSettings () [0x0001d] in
>       <04dc5ca6c35a46aa8bc6e6cd7c986dae>:0    at
>       MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning
>       (System.Boolean throwIfNotRunning) [0x000ff] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:298
>       --- End of inner exception stack trace ---   at MonoTouch.Design.Client.Mac.MacServerProcessConnection.EnsureServerRunning
>       (System.Boolean throwIfNotRunning) [0x001e8] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client.Mac/MacServerProcessConnection.cs:323
>       at MonoTouch.Design.Client.ServerProcessConnection.SendRequestCore
>       (MonoTouch.Design.CommandRequest request, System.Boolean
>       throwIfNotRunning) [0x00057] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:282
>       at MonoTouch.Design.Client.ServerProcessConnection.SendRequest
>       (MonoTouch.Design.CommandRequest req, System.Boolean
>       throwIfNotRunning) [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:230
>       at
>       MonoTouch.Design.Client.ServerProcessConnection.SendRequest[TResponse]
>       (MonoTouch.Design.CommandRequest req, System.Boolean
>       throwIfNotRunning) [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:252
>       at MonoTouch.Design.Client.ServerProcessConnection.CreateSession ()
>       [0x00001] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:111
>       at
>       MonoTouch.Design.Client.Ser

verProcessConnection.<CreateSessionAsync>b__28_0
>       () [0x00000] in
>       /Users/runner/runners/2.160.0/work/1/s/Xamarin.Designer.iOS/MonoTouch.Design.Client/Connection/ServerProcessConnection.cs:116
>       at System.Threading.Tasks.Task1[TResult].InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 <---

### Steps to Reproduce

1. Open/create a project
2.  Open storyboard 

### Basic Information

- Version with issue:
- Last known good version: 11.1 
- IDE:
- Platform Target Frameworks: 
  - iOS: Xamarin.IOS  13.8.3
  -  Mac version 8.3.11 Mono: 6.6.0.155

### Reproduction Link

[CoreSimulator.zip](https://github.com/xamarin/Xamarin.Forms/files/3968239/CoreSimulator.zip)

**Comment by samhouts** [comment]
@slushpuppy Please report this from inside visual studio. Thanks!

**Comment by ocallaghan-kevin** [comment]
Any solution to this??
