### ISSUE TITLE
[Bug] IndicatorView isn't centered by default on Android

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8911]
### Description

An `IndicatorView` that doesn't specify any `HorizontalOptions` is centered by default on iOS, but is left aligned on Android. This is only a papercut, but it's irritating having to specify `HorizontalOptions` just for one platform.

### Steps to Reproduce

1. Run the attached sample on iOS and Android.
2. Browse to the Basic IndicatorView page.

### Expected Behavior

IndicatorView is centered by default on both platforms.

### Actual Behavior

IndicatorView is centered on iOS, but left aligned on Android.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version:
- IDE: VSMac 8.3.11
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: API 28

### Screenshots

iOS:

![Simulator Screen Shot - iPhone X - 2019-12-16 at 15 03 26](https://user-images.githubusercontent.com/8092460/70918219-afdbac00-2016-11ea-8923-8ab6d44476ac.png)

Android:

![Screenshot_1576508644](https://user-images.githubusercontent.com/8092460/70918237-b4a06000-2016-11ea-8717-620a8cb1f7a1.png)

### Reproduction Link

[IndicatorViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3968694/IndicatorViewDemos.zip)

**Comment by samhouts** [comment]
It's also not center-aligned for UWP. :)

**Comment by BurkusCat** [comment]
@samhouts Should this be reopened to fix UWP?
