### ISSUE TITLE
[Bug] Indicator.MaximumVisible property has no effect

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8912]
### Description

An `IndicatorView` that sets the `MaximumVisible` property doesn't have `MaximumVisible` indicators. For example, the below code should result in 6 indicators, but it doesn't.

```
        <IndicatorView ItemsSourceBy="carouselView"
                       MaximumVisible="6"
                       Margin="0,0,0,40"
                       IndicatorColor="LightGray"
                       SelectedIndicatorColor="DarkGray"
                       HorizontalOptions="Center" />
```

### Steps to Reproduce

1. Run the attached sample.
2. Browse to the Basic IndicatorView page.

### Expected Behavior

IndicatorView with 6 indicators visible.

### Actual Behavior

IndicatorView with 17 indicators (17 items in the collection).

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version:
- IDE: VSMac 8.3.11
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: API 28

### Screenshots

iOS:

![Simulator Screen Shot - iPhone X - 2019-12-16 at 15 03 26](https://user-images.githubusercontent.com/8092460/70918911-ce8e7280-2017-11ea-84ee-a1dcab2c85c7.png)

Android:

![Screenshot_1576509429](https://user-images.githubusercontent.com/8092460/70918904-cb938200-2017-11ea-803f-9636fc624517.png)

### Reproduction Link

[IndicatorViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3968726/IndicatorViewDemos.zip)

**Comment by quentinR0bert** [comment]
I have the same bug but the strange thing is that :
- If i set a value in XAML and use the HotReload of VSMac it work the first time.
- If i change the value in run time it doesn't work
