### ISSUE TITLE
[Bug][Android] Changing IndicatorView.IndicatorsShape at runtime has no effect 

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#8914]
### Description

On Android, changing `IndicatorView.IndicatorsShape` at runtime doesn't result in the shape of the indicators changing (until you change one of the indicator colours).

### Steps to Reproduce

1. Run the attached sample on Android.
2. Browse to the Configurable IndicatorView page.
3. Change the IndicatorShape Picker to Square.

### Expected Behavior

IndicatorView has square indicators.

### Actual Behavior

IndicatorView indicators remain circular.

Note: changing one of the colour Pickers will result in the IndicatorShape Picker selection being respected.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version:
- IDE: VSMac 8.3.11
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: API 28

### Screenshots

![Screenshot_1576510801](https://user-images.githubusercontent.com/8092460/70920401-70af5a00-201a-11ea-9461-1a7f878b3f6b.png)

### Reproduction Link

[IndicatorViewDemos.zip](https://github.com/xamarin/Xamarin.Forms/files/3968829/IndicatorViewDemos.zip)

**Comment by rmarinho** [comment]
This is fixed on 4.4.0 stable
