### ISSUE TITLE
[Bug] ObservableCollection throws NSInternalInconsistencyException

### ISSUE THREAD

**Issue by JohnLivermore** [xamarin/Xamarin.Forms#8931]
### Description

I have a simple project [download code here](https://github.com/JohnLivermore/SampleXamarinApp/tree/iosObservableCollectionIssue), that throws a NSInternalInconsistencyException when MainPage loads.  I am seeing this on the iPhone 8 iOS 11.0 emulator.  The 13.x emulators don't have this issue (nor does my phone).  However, for 11.0 it throws.

### Steps to Reproduce

1. Download/run the repo for the **iPhone 8 iOS 11.0** emulator.
2. The app will crash upon starting up.

### Expected Behavior
No exceptions and the list displays.

### Actual Behavior
![image](https://user-images.githubusercontent.com/1489667/71009662-342e3d80-20b0-11ea-95b1-f3fd0a907fd9.png)

### Basic Information

- Version with issue:  XF 4.4
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 

### Reproduction Link

https://github.com/JohnLivermore/SampleXamarinApp/tree/iosObservableCollectionIssue

**Comment by rmarinho** [comment]
Your sample was using 4.3, if you update to 4.4 and used simulator iphone 8 11.4 and i don't see the crash. 

can you confirm that you are using 4.4.0.991265

thanks

**Comment by Jared-Aus** [comment]
I get this error with 4.4.0.991477 and iOS 13.3. For me it's the same issue as #8948

**Comment by samhouts** [comment]
I confirm that this exact issue is no longer present on 4.4.0. @Jared-Aus, we will follow up with your issue on #8948. Thanks!
