### ISSUE TITLE
[Bug] Binding broken for Dictionary subclasses

### ISSUE THREAD

**Issue by MisterAcoustic** [xamarin/Xamarin.Forms#8936]
### Description
Databinding to a dictionary subclass no longer works

### Steps to Reproduce

1. Create a custom dictionary by subclassing Dictionary<string, object>, and add data, e.g. CustomDictionary.Add("MyField". "MyData")

2. Bind an Entry to a dictionary entry by setting the binding as
Text="{Binding CustomDictionary[MyField]}". Note that when binding occurs, the log shows an entry like: [0:] Binding: 'MyField' property not found on 'CustomDictionary', target property: 'Entry.Text'

3. Note that the value initially appears in the field, but when the field value is updated, the entry in the custom dictionary is not. If instead of the custom dictionary subclass, you directly use a Dictionary<string, object>, the dictionary is updated as expected. Lastly, our code worked in Xamarin Forms 3, but I cannot remember the exact version we used last.

### Expected Behavior
The value in the custom dictionary should be updated when the bound Entry field value is updated.

### Actual Behavior
The dictionary entry is not updated when the Entry value changes.

### Basic Information

- Version with issue:
- Last known good version: Xamarin Forms 3 (can't recall exact minor version)
- IDE: Visual Studio 2019
- Platform Target Frameworks: N/A
- Nuget Packages:  N/A
- Affected Devices:  N/A

### Reproduction Link

[BindingTest2.zip](https://github.com/xamarin/Xamarin.Forms/files/3974819/BindingTest2.zip)

**Comment by StephaneDelcroix** [comment]
#7837 regressed this. working on it

**Comment by StephaneDelcroix** [comment]
the indexer was working one way but sending a message the other way as it was binding to the Item property of IReadonlyDictionary`2, and not on Dictionary`2
