### ISSUE TITLE
[Bug][Android] Visual.Default and Visual.Material Button with image should behave in same way

### ISSUE THREAD

**Issue by kcrg** [xamarin/Xamarin.Forms#8939]
### Steps to Reproduce
1. Add two buttons with image, one with Visual="Material".

### Expected Behavior
Image in buttons behave in the same way.

### Actual Behavior
Image in button inconsistent behave.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: idk
- IDE: Visual Studio 2019 16.4
- Platform Target Frameworks:
  - iOS:  13
  - Android: 10
- Nuget Packages: 4.4.0.991265
- Affected Devices: Android, iOS is good

### Screenshots
![Screenshot_2019-12-17-20-22-50-325_com companyname imagebuttonrepo](https://user-images.githubusercontent.com/7996711/71028671-10014980-210e-11ea-9cd4-46d43d5e5575.jpg)

### Reproduction Link
[ButtonWithImageRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3975142/ButtonWithImageRepro.zip)

**Comment by PureWeen** [comment]
@kcrg We can't really change how either of these display by default

Non material: we can't change how this looks because it would be a breaking change. In a perfect world this should look like the material one

Material: This is the expectation of how it should look when it's using material design
