### ISSUE TITLE
RefreshView color not being honoured first time loading/programatically

### ISSUE THREAD

**Issue by LeoJHarris** [xamarin/Xamarin.Forms#8940]
# Description

When page first loading and refreshview is programatically called the refreshview is not the color defined in the refreshview, when pull to refresh is made by user the correct refreshview color is shown

### Steps to Reproduce

1. Load a page where refreshview is being called i.e. init a collectionview and show refreshview.
2. then pull to refresh and color is correctly defined color on refreshview.

### Expected Behavior

The color of the refreshview should be that defines on the refreshview

### Actual Behavior

the initial color of the refreshview is not honoured, only subsequent pull to refresh from user has correct pull to refresh color.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: NA
- IDE: Visual studio 2019 (windows) community 16.4.2
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 9.0
  - UWP:  NA
- Android Support Library Version: NA
- Nuget Packages: 
- Affected Devices: iPad (4th generation) v10.3.3

### Screenshots

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/5468757/71041581-53030180-218e-11ea-9b7f-d7be2857b687.gif)

### Reproduction Link

**In the reproduction the refreshview color is defined white but for first time refreshing it displays black**

[TestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/3975826/TestApp.zip)

**Comment by DottorPagliaccius** [comment]
I still have this issue with XF 4.7.0.1080

**Comment by LeoJHarris** [comment]
Can confirm issue still exists...

**Comment by DottorPagliaccius** [comment]
Still present, but only on emulator

**Comment by Daniel0b1b** [comment]
> Still present, but only on emulator

Still present, in 5.0.0.1874 on ios device

**Comment by Hackmodford** [comment]
I'm pretty convinced this is an iOS bug. The first time it activates via code it doesn't have the correct color even in native.

**Comment by JayMansel** [comment]
What version of iOS is everyone running on? Same issue here, XF version 5.0.0.2337, iOS version 15.1
