### ISSUE TITLE
Cannot run application on Android[Bug] 

### ISSUE THREAD

**Issue by WaiseFass** [xamarin/Xamarin.Forms#8945]
### Description

Yesterday I updated all my nuget packages and the visual studio version and now I cannot run the application on an android device (real device/simulator). I always receive an error that the Xamarin.Forms.Core.dll is being used by another process. This error occurs also if I close visual studio, delete .vs, bin, obj folders and reopen visual studio. 
If I want to debug my application I have to close vs, open a empty vs instance, clear nuget cache and reopen the project. After this workaround I can debug the application once... After the first run, the error occurs again...

I tried to create a new blank xamarin.forms application (with and without the latest xamarin.forms version) but the same error occurred...

I already repaired visual studio and removed all nuget folders.. 

I don't know if it is a xamarin.forms error or a visual studio error.. So I don't know if this is the right area of this issue, but it occurs only with this xamarin.forms.core.dll.... 

### Steps to Reproduce

1. Create/open a project
2. Try to debug on a device/simualtor
3. stop the debugger and try to debug again.

### Expected Behavior
the application starts on the device and you can debug your application

### Actual Behavior
an error occured and the application crashes
### Basic Information

- Version with issue:
- Last known good version: 16.5.0 Preview 1.0
- IDE: Visual Studio 19 Preview
- Platform Target Frameworks: 
  - Android: 9
- Nuget Packages:
xamarin.forms: 4.4.0.991265
xamarin.essentials: 1.3.1

### Screenshots
![Capture](https://user-images.githubusercontent.com/40561661/71069806-c3535800-2179-11ea-950b-45968bf557ee.PNG)

**Comment by VladislavAntonyuk** [comment]
you can find which process uses Xamarin.Forms.Core.dll and kill it. probably it is another instance of MSBuild. 
You can also try to set another nuget package storage folder in Nuget.config.

**Comment by WaiseFass** [comment]
But I don't want to create a new folder after a debug run... And it is also annoying to check every time what process blocks the dll.. And I tried to kill the process, but in this case Visual Studio was also killed.. And the process explorer shows only one process which is using this dll and thats si the vs process from my project
![image](https://user-images.githubusercontent.com/40561661/71084513-be9c9d00-2195-11ea-986a-23cbc0d2ef7f.png)

**Comment by rmarinho** [comment]
We aren't able to reproduce this issue,  What version of VisualStudio are you using?

Can you add a zip with the project you are using?

Thanks

**Comment by WaiseFass** [comment]
Currently I use Visual Studio 2019 16.5.0 Preview 1.0 (latest version).
This error also occures if I use a new, empty solution like https://github.com/WaiseFass/DemoForVsError

**Comment by hudaIT** [comment]
Exactly same issue for me

**Comment by rmarinho** [comment]
I tried with the Visual Studio 2019 16.5.0 Preview 1.0 , file new project, debug it works, udpate packages to 4.4 and it still works.

**Comment by VladislavAntonyuk** [comment]
I think it is a local issue with the environment. As I suggested change NuGet directory

**Comment by WaiseFass** [comment]
@vladimir-kotikov I tried to change the NuGet directory, but I have still the same error...

**Comment by VladislavAntonyuk** [comment]
Do you have another environment where the issue is reproduced

**Comment by WaiseFass** [comment]
Yes. I have this issue on two different working spaces. Both running with Windows 10 and the same version of visual studio...

**Comment by WaiseFass** [comment]
I reinstalled visual studio, removed all nuget caches and tried it again and everything worked well until I changed something in xaml in debug mode with hot reload. After those changes the error message occurs again... So I guess there is a dependency between this error and xaml hot reload...

**Comment by leo-mck** [comment]
I am having the exact same problem, it happens only on VS2019 Preview 16.5 Preview 1.  It seems to be a VS problem: https://developercommunity.visualstudio.com/content/problem/846153/the-connection-with-the-debugger-has-been-lost-the-1.html

**Comment by ahmetcoskn** [comment]
I got same error.  After reset VS sometimes debugger work but in the second or later I got this error. 
devenv.exe was opened this file.
