### ISSUE TITLE
[Bug] Android Inconsistent CarouselView behaviour between stable and preview version

### ISSUE THREAD

**Issue by ravinderjangra** [xamarin/Xamarin.Forms#8947]
The CarouselView on Android is not rendering the same way between XF v4.4-pre3 and XF v4.4-stable.

### Steps to Reproduce

1. Setup some carousel view
2. Run with XF 4.4-pre3
3. Upgrade XF to v4.4-stable

### Expected Behavior

There should not be much different when the CarouselView is rendered.

### Actual Behavior

The CarouselView code doesn't generate the same result. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks:
  - Android: 9
- Nuget Packages:
- Affected Devices:

### Screenshots

**With 4.4-pre3**

![Screenshot_1576665617](https://user-images.githubusercontent.com/9795917/71079791-edc10780-21b1-11ea-9179-cb0e46e36049.png)

**With 4.4-stable**
![Screenshot_1576665740](https://user-images.githubusercontent.com/9795917/71079739-d3872980-21b1-11ea-93ed-ffc45f7cdd82.png)

### Reproduction Link

You can try running the app from this branch: https://github.com/ravinderjangra/safe-network-app-mobile/tree/login-create-account. 
Just launch the app to see the difference either upgrade the XF package or revert the commit.

**Comment by rmarinho** [comment]
Since CarouselView is under the Exprimental flag it's normal that are some changes on the control, this case we fixed a issue with the Peek Area insets, and we made the behavior to between consistent between Android and iOS, where the item will be centered on the viewport.

I made  a couple of changes that seems to fix your use case. but if you need a behavior like you had before where items start on the left side (without inset) you should try move to  Horizontal CollectionView.

```
<CarouselView.PeekAreaInsets>
              <OnPlatform x:TypeArguments="Thickness">
                   <On Platform="iOS" Value="0, 0, 100, 0" />
                   <On Platform="Android" Value="0, 0, 100, 0" />
                </OnPlatform>
</CarouselView.PeekAreaInsets>
<CarouselView.ItemsLayout>
               <LinearItemsLayout Orientation="Horizontal"
                                       ItemSpacing="15"
                                       SnapPointsType="Mandatory"
                                       SnapPointsAlignment="Center" />
</CarouselView.ItemsLayout>
```

**Comment by ravinderjangra** [comment]
Thanks @rmarinho, this makes sense. I understand the control is still under development. I raised the issue to confirm if it's intended change or a real bug with the implementation. 

I will definitely move to the collection view for this case. Also, I noticed even with the new version the items are coming from the left corner on iOS which is again inconsistent between the platforms.

**Comment by rmarinho** [comment]
@ravinderjangra yap i noticed that too, for iOS seems we need to specify like this

```
  <On Platform="iOS" Value="100, 0, 100, 0" />`
```

but i think we should open a new issue about this
