### ISSUE TITLE
[Bug] NullRefrenceException in ContextActionsCell.OnCellPropertyChanged

### ISSUE THREAD

**Issue by breyed** [xamarin/Xamarin.Forms#8957]
When the event handler for ViewCell.BindingContextChanged calls Clear on the ViewCell's ContextActions collection, ContextActionsCell.OnCellPropertyChanged throws a NullReferenceException.

### Steps to Reproduce

1. Create a ListView (with default caching strategy).

2. Set its ItemTemplate to a DataTemplate with a ViewCell that handles ViewCell.BindingContextChanged, with the event handler looking like this:

``` c#
void HandleViewCellBindingContextChanged(object sender, EventArgs e)
{
   var cell = (ViewCell)sender;
   cell.ContextActions.Clear();
   cell.ContextActions.Add(new MenuItem { Text = "Foo" });
}
```

### Actual Behavior

iOS crashes with "SIGABRT: Object reference not set to an instance of an object" and this call stack:
```
ContextActionsCell.OnCellPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e)
(wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
BindableObject.OnPropertyChanged (System.String propertyName)
Element.OnPropertyChanged (System.String propertyName)
Cell.OnContextActionsChanged (System.Object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
ObservableCollection`1[T].OnCollectionChanged (System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
```

### Basic Information

- Version with issue: 4.3.0.851321-pre3
- Last known good version:
- Platform Target Frameworks: 
  - iOS: 13.1.2
- Affected Devices: iPhone XR

**Comment by rmarinho** [comment]
Hi @breyed i tried to reproduce the issue but i wasn't able to, can you help me.

Here's the repo i used:

[App21.zip](https://github.com/xamarin/Xamarin.Forms/files/3988170/App21.zip)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
