### ISSUE TITLE
[Bug] IndicatorView not updating to current page when CarouselView is bound to custom DataType

### ISSUE THREAD

**Issue by missy-bowles** [xamarin/Xamarin.Forms#8958]
### Description
I have a CarouselView which binds to a list of objects that are a local data type using a DataTemplate, and an IndicatorView sourced by the carousel. The indicator shows the correct number of pages but the current page indicator does not update as I swipe through the carousel. If the carousel is instead bound to a list of strings it does work. Occurs on Android and iOS.

### Expected Behavior
IndicatorView should indicate the correct current page

### Actual Behavior
IndicatorView indicates you are still on the first page while swiping through the carousel. 

### Basic Information

- Version with issue: Xamarin Forms 4.4.0
- Platform Target Frameworks: 
  - iOS:  13.0
  - Android: 9.0 

### Reproduction Link
[CarouselBugsRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/3980437/CarouselBugsRepro.zip)

**Comment by carlosforero** [comment]
I have the same issue.

**Comment by jhf** [comment]
We have the same problem using IndicatorView - @samhouts What does the "e/4 :clock4:" label means with regards the when this issue will be looked at?
Does it mean that all of  e/1 e/2 and e3 tags have priority? Or is it the order in https://github.com/xamarin/Xamarin.Forms/projects/19#card-31128636 that decides when it will be looked at?

**Comment by maxbaki** [comment]
I have same bug when binding items from modelview

`<CarouselView x:Name="TheCarousel" Margin="20,20,20,0" 
                                              Position="{Binding BusinessCard.BusinessCardTemplateId, Mode=TwoWay}"
                                              ItemsSource="{Binding Items}" 
                                              VerticalOptions="FillAndExpand"
                                              HeightRequest="2000"
                                              HorizontalOptions="FillAndExpand"
                                              ItemTemplate="{StaticResource templateSelector}"
                                              PeekAreaInsets="20"
                                              >
                                        <CarouselView.ItemsLayout>
                                        <LinearItemsLayout Orientation="Horizontal"
                                            ItemSpacing="20" />
                                        </CarouselView.ItemsLayout>
                                    </CarouselView>
                            <IndicatorView 
                              IndicatorColor="{DynamicResource FormColor}"
                              SelectedIndicatorColor="{DynamicResource GradientStartAccentColor}"
                              IndicatorSize="10" HorizontalOptions="Center"
                              IndicatorView.ItemsSourceBy="TheCarousel"/>`

**Comment by woemike** [comment]
Any updates on this? Thank you!

**Comment by bytewin** [comment]
I have the same issue.

**Comment by samhouts** [comment]
We're working through all these blockers as quickly as we can. 

the e/ tags are our estimate of effort, not priority. :)

**Comment by oveg** [comment]
Any plans on when this ticket will be moved to In Progress?

**Comment by oveg** [comment]
Any updates? Thank you.

**Comment by oveg** [comment]
Any updates? Thank you.
