### ISSUE TITLE
CarouselView - Adding an item to the beginning of the bound ItemSource causes the carousel to skip sometimes [Bug] 

### ISSUE THREAD

**Issue by mjmostachetti** [xamarin/Xamarin.Forms#8964]
### Description

I am attempting to traverse a list backwards(swiping right) through a carousel view. Once I reach the 1st index in a list of 5 items, I dynamically add a new item to the itemsource. It works for a few swipes but after a while the CarouselView will unintentionally skip a view.

I do not have this problem when I start from the beginning of a list and add items dynamically to the end of the itemsource.

### Steps to Reproduce

1.  Initialize a carousel view with 5 items.
2.  Set the currentPosition to the 4th index - ie the last item in the list
3. Swipe right until you reach the 1st index.
4.  Upon firing CurrentItemChangedCommand and the new index is at position 1, add a new item to the itemsource at position 0.
5. Continue to swipe right until you see it skip a view.

### Expected Behavior

Dynamically add items to the 0 index multiple times without experiencing a jump in the navigation.

### Actual Behavior

Skips a view sometimes - For example, going backwards from 100 -> 90, the CarouselView will sometimes skip from 96 to 94.

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 9
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mjmostachetti** [comment]
I can repro this here on the same android device - https://github.com/mjmostachetti/Xamarin.Forms/tree/bug/android-navigate-backwards-glitch

I did not see this issue with the ios simulator.

**Comment by rmarinho** [comment]
Works fine on iOS , but i do see the issue on Android

**Comment by inkysquid** [comment]
There's a comment in RecyclerViewScrollListener's OnScrolled() method that might be relevant:

```
// TODO: These offsets will be incorrect upon row size or count change.
// They are currently provided in place of LayoutManager's default offset calculation
// because it does not report accurate values in the presence of uneven rows.
// See https://stackoverflow.com/questions/27507715/android-how-to-get-the-current-x-offset-of-recyclerview
```

**Comment by mjmostachetti** [comment]
Any plans to fix this in the near future?
