### ISSUE TITLE
[Bug] Share.RequestAsync does not work properly on iPad

### ISSUE THREAD

**Issue by x0penghui** [xamarin/Xamarin.Forms#8966]
### Description
Share.RequestAsync does not work properly on iPad
### Steps to Reproduce

```c#
 await Share.RequestAsync(new ShareTextRequest
            {
                Text = "test"
            });
```

### Basic Information

- Version with issue: Xamarin.Forms (4.3.0.991221)
- IDE: Microsoft Visual Studio Community 2019  16.4.1
- Platform Target Frameworks: 
  - iOS:  7.0
- Affected Devices: ipad, ipad pro

**Comment by rmarinho** [comment]
Hi, this doesn't seem a bug related with our Product. 

thanks
