### ISSUE TITLE
[Bug] Ambiguous behavior of a TapGestureRecognizer inside Span

### ISSUE THREAD

**Issue by ElieNahas** [xamarin/Xamarin.Forms#8972]
### Description
I have a Label where I am appending FormattedText to it. The FormattedText contains multiple spans. Some of the spans are clickable using TapGestureRecognizer. When in portrait mode the event is fired once the item is clicked. When the orientation changes, the design adapts to the new orientation but the click listener event is not re-adjusted to the new position, instead the event is being fired on old pixels of the screen already defined before the orientation. Knowing that I have update Xamarin.Forms from 3.6.0.709228 to 4.4.0.991265 hoping that the issue will be fixed but unfortunately I had the same problem.

### Steps to Reproduce

1. Create a screen with a label
2. Append dynamically multiple spans. One of the spans should have click event listener.
3. Rotate the screen. Then click on the previous word. The event won't fire. 

### Expected Behavior
The event listener position should be re-adapted based on the orientation and the TapGestureRecognizer should listen to the span assigned to it.

### Actual Behavior
The first screenshot attached represents the normal behavior of the click event and the position where it should be clicked. Whilst the second screenshot, we can see the design re-adapted to the orientation changes but the click event is not being fired on the appropriate word, instead it is being fired on the arrow.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: N/A
- IDE: Visual Studio for Mac 8.3.9
- Platform Target Frameworks: 
  - iOS:  13.1
  - Android: Untested
  - UWP:  N/A 
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: iOS

### Screenshots

<img width="285" alt="Normal" src="https://user-images.githubusercontent.com/19953015/71192291-acebf000-2290-11ea-8632-686824f974ed.png">
<img width="285" alt="Problem" src="https://user-images.githubusercontent.com/19953015/71192292-acebf000-2290-11ea-92e4-781cd2e1e6d2.png">

**Comment by hartez** [comment]
I suspect the changes to EventTracker in #8975 will fix this.

**Comment by samhouts** [comment]
@ElieNahas Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ElieNahas** [comment]
Hello @samhouts ,

Kindly find attached the requested sample project.

Kindly note that I have tested the same UI on iOS and Android. But the problem seems to be only on iOS when rotating the device.

Thank you!

[TEST.zip](https://github.com/xamarin/Xamarin.Forms/files/4015538/TEST.zip)

**Comment by hartez** [comment]
Just tested the sample project against 4.6.0.144-nightly and the tap gesture works after rotation. So the fix for this will be in a stable release soon.
