### ISSUE TITLE
[Bug] SwipeView - no animation when revealing CollectionView items 

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8973]
### Description
There is no animation when revealing CollectionView items. It is shown in the attached GIF. Look at the trash icon - it is not smoothly animating from the right. It is just popping out of nowhere.

The text on the left is nicely animating - but the trash icon NOT

### Steps to Reproduce

1. Run this project (I was running it on Android)
[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/3984651/App3.zip)

2. Swipe any CollectionView item to the left
3. As you can the trash icon is popping out of nowhere. There is no smooth animation.

### Expected Behavior
The reveal animation should be smooth

### Actual Behavior
There is no animation when revealing swipe items

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: 16.4.1
- Platform Target Frameworks: 
  - Android: 9.0 (Pie)
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots

![swipe_no_animation](https://user-images.githubusercontent.com/17653648/71192922-7c548800-2289-11ea-99bc-8c6bb46a9c27.gif)

**Comment by jsuarezruiz** [comment]
Add a background color to the content of the SwipeView and you will get the effect of the animation.

![issue8973](https://user-images.githubusercontent.com/6755973/71256767-11ab5700-2332-11ea-91b0-aa131b7e08fe.gif)

**Comment by Mikilll94** [comment]
@jsuarezruiz 
Thanks for the workaround

**Comment by jsuarezruiz** [comment]
You are welcome. And the PR with the fix is here: https://github.com/xamarin/Xamarin.Forms/pull/8987
