### ISSUE TITLE
[Enhancement] [SwipeView] Allow tolerance and swipe length to be set for the swipe action

### ISSUE THREAD

**Issue by czuck** [xamarin/Xamarin.Forms#8974]
## Summary
Using swipe in Execute mode on a device is difficult because the swipe needs to be very level and move the item half way across the screen.  I'd like to be able to set the tolerance larger so the action doesn't need to be so level, and set the swipe length so the action does not need to be as long. 

![image](https://user-images.githubusercontent.com/1641428/71194477-d2510d80-2240-11ea-8960-82462ded36aa.png)

## API Changes
Add to SwipeItems
- Tolerance 
- SwipeLength 

## Intended Use Case
Displaying a list of messages, swiping one way marks the item seen, the other way marks it unseen.  A user may want to do this on a number of messages quickly.  The current swipe length and tolerance make it difficult to do this.
When I implemented my own version using the PullAndSwipe gesture, I used a abs(TotalY) of <20 and a abs(TotalX) >= 100 to indicate a horizontal swipe.  I found that did not interfere with the pull-to-refresh action but was easy to initiate.

**Comment by jsuarezruiz** [comment]
Currently the SwipeView internally uses a value to define the SwipeThreshold. Is a value that indicates SwipeView gets stick when the offset is greater than 80% of the value. 
The proposal is interesting. It would be to have a BindableProperty SwipeT.
So, we could define a **SwipeThreshold** BindableProperty to cover these cases.

**Comment by JeroenTrivec** [comment]
I can see how this Threshold property would be useful in Execute mode, but it is of no practical use in Reveal mode (it either partially or fully hides swipe items or adds a bunch of empty space). I was kind of hoping the (currently fixed at 60%) OpenSwipeThresholdPercentage would become configurable instead. That way, swipes can be made easier (or harder, I guess) in both modes without compromising Reveal mode's main function.
