### ISSUE TITLE
[Enhancement] Vertical orientation for IndicatorView

### ISSUE THREAD

**Issue by andreas-nesheim** [xamarin/Xamarin.Forms#8977]
## Summary
It would be nice to select a vertical orientation for the new IndicatorView. As of now it is horizontal and stuck at the bottom of the page. 

## API Changes

A new bindable property named "Orientation" should be added to the IndicatorView.

    var indicatorView = new IndicatorView();
    indicatorView.Orientation = IndicatorViewOrientation.Vertical; // new API

For Android I tested the possibility of this with a custom renderer. Setting the LinearLayout.Orientation = Orientation.Vertical had some results, but I also had to set the HeightRequest in XAML to make sure the results actually worked.

## Intended Use Case
This would open up for having the IndicatorView f.ex. fixed to the right or left side of the page and would make more sense for vertical scrolling of a CarouselView. 

I'm picturing something like this (results of fiddling with a custom renderer):

![indicatorview-vertical-scaled](https://user-images.githubusercontent.com/11583629/71204040-79649200-229f-11ea-91c5-8bbd5594ca8d.gif)

**Comment by JunkyXL86** [comment]
Will this be a thing for MAUI?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
