### ISSUE TITLE
[Enhancement] Positioning for IndicatorView

### ISSUE THREAD

**Issue by andreas-nesheim** [xamarin/Xamarin.Forms#8978]
## Summary
It would be nice to be able to position the IndicatorView more freely. As of now it is fixed at the bottom of the page. Some examples of where it would be nice to be able to position the IndicatorView:
- Inside the CarouselView which it is connected to (top, bottom, left, right)
- Top, bottom, left or right of the current page

The left and right alignments would require the implementation of #8977.

## API Changes

A new bindable property "IndicatorAlignment" should be added to IndicatorView.

    var indicatorView = new IndicatorView();
    indicatorView.IndicatorAlignment = IndicatorAlignment.PageTop; // new API

The new property should be an enum, with suggested options below:

`public enum IndicatorAlignment 
{
PageTop,
PageBottom,
PageLeft,
PageRight,
CarouselTop,
CarouselBottom,
CarouselLeft,
CarouselRight
};`

## Intended Use Case
There are cases where it makes more sense to have the indicator inside of the carousel it is connected to instead of at the bottom of the page. It would also make sense to be able to align it to the right (or left) of the page, given that a vertical orientation is available for the IndicatorView.

**Comment by rmarinho** [comment]
Sorry but I don't understand, you can position the IndicatorView where you want is not fixed to be on the bottom of the page. 
Since is it's own control, you can basically use our layouts to position it anywhere.

**Comment by andreas-nesheim** [comment]
My mistake, the examples in the documentation led me to believe that the IndicatorView always was fixed at the bottom. I see now that I can easily place the IndicatorView where I want. Apologies.

**Comment by drjhkom** [comment]
> My mistake, the examples in the documentation led me to believe that the IndicatorView always was fixed at the bottom. I see now that I can easily place the IndicatorView where I want. Apologies.

I'm new to Xamarin, and would have really liked to have seen how you can "easily place the IndicatorView where I want"!
