### ISSUE TITLE
[Bug] Android - DatePicker causes exception when trying to display native date picker

### ISSUE THREAD

**Issue by ChristianTBaker** [xamarin/Xamarin.Forms#8979]
### Description
Note: DatePicker functioned normally on iOS

When trying to use DatePicker for a Xamarin Forms application, the following exception was raised:

Android.Views.WindowManagerBadTokenException: 'Unable to add window -- token null is not valid; is your activity running?'

### Steps to Reproduce
Note: Using MvvmCross framework
1. Place a DatePicker into your page per the Microsoft documentation 
2.  Run the application on simulator or device
3. Tap on the DatePicker

### Expected Behavior
A popup with the native android datepicker should be displayed.

### Actual Behavior
The aforementioned exception is raised and the app crashes.

### Basic Information

- Version with issue: 16.3.10
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: 9.0 
- Android Support Library Version: 
- Nuget Packages: 
 -
- Affected Devices:  Ran on Moto G7 and Pixel Simulator

### Solution
1. Create an android custom DatePicker renderer,.
2. Bring in all the code for  Xamarin.Forms/Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs
and code required DatePickerRenderer.cs for into you're renderer.
3.  In CreateDatePickerDialog(int year, int month, int day), Change the context from the renderer's Context to this.RootView.Context

### Bug Location
Line 121 of Xamarin.Forms/Xamarin.Forms.Platform.Android/Renderers/DatePickerRenderer.cs

**Comment by samhouts** [comment]
@ChristianTBaker Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@ChristianTBaker  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by zoli13** [comment]
We have exactly the same issue. Just updated mvvmcross to the latest, and since then, on DatePicker makes the App crash on Android. On iOS, it's OK, works fine.
This is our call where it crashes: `picker.Focus();`
The project is huge, so right now unable to provide small project to demo it.
However, @ChristianTBaker mentioned in step 3, what is the "fix" for this.
I am not sure if this is mvvmcross or xamarin issue though.

**Comment by zoli13** [comment]
Hi @ChristianTBaker ,
Could you provide your modified workaround renderer code please?
Could you find other "better" solution?
Which MvvmCross version do you use? We encounter it with 7.1.2 (+XF: 4.8.0.1269)

**Comment by AndriDev** [comment]
@zoli13 
@ChristianTBaker 


I think fixing with just custom renderer is some overkill, moreover it will fix DatePicker only, but potentially will not fix other some other controls, which also use incorrect Context of Forms. IMHO more correct place to fix should be in the beginning of MvxFormsAppCompatActivity<,,>.OnCreate. That is inside sources of MVVMCROSS, so we can override OnCreate and do following as workarond:
`public class MvxFormsApplicationActivity : MvxFormsAppCompatActivity<Setup, App, MyMvxFormsApp>, IMvxAndroidView, IMvxEventSourceActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            // Force fix activity to be not app instance
            // https://github.com/xamarin/Xamarin.Forms/issues/8979
            var activity = this;
            var resourceAssembly = System.Reflection.Assembly.GetCallingAssembly();
            Forms.Init(activity, null, resourceAssembly);
            base.OnCreate(bundle);
//... rest of your code here
      }
`
