### ISSUE TITLE
[Bug] SwipeView - bad responsiveness to touch

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8983]
### Description
Right now, in my opinion, SwipeView is not very useful, because it responds to touches very bad. I was testing on the emulator and on the real device, and many times the SwipeView control was not responding to touches which is very annoying. I have shown that on the GIF below.

Especially on the left side of the SwipeView content, the responsiveness is very bad.

On the real device, UX is worse than on the emulator.

Please also compare the SwipeView with the Gmail app. In the Gmail app, when I swipe the message it executes perfectly and it is much smoother than SwipeView.

I was testing only on Android.

### Steps to Reproduce

1. Open and run this project on Android on REAL DEVICE
[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/3988487/App3.zip)
2. Swipe some items in the list to the left.
3. As you can the UX is not good. Sometimes the swipe occurs, sometimes not. It is a very frustrating experience for the user.

### Expected Behavior
SwipeView should work seamlessly and give the best possible UX.

### Actual Behavior
The UX is bad. The swipe is sometimes executed and sometimes not.

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: Visual Studio 2019 16.4.1
- Platform Target Frameworks: 
  - Android: 9.0 (Pie)

### Screenshots

![swipe_bad_responsiveness](https://user-images.githubusercontent.com/17653648/71258459-82ed0900-2336-11ea-9f82-6f671ab030b7.gif)

**Comment by jsuarezruiz** [comment]
In the repro sample you have a SwipeItem defined in the RightItems. This means that the swipe is allowed from the right to the left. From the left to the right nothing should happen.
![issue8983](https://user-images.githubusercontent.com/6755973/71267031-e5033980-2349-11ea-96ed-3ad63e217d80.gif)
If you do not define elements in a specific direction, the swipe (touch) will not work (well, will do nothing).

If you swipe from left to right and quickly from right to left you open the SwipeView, there is a fix that can be related. It is related to swipe quickly in several directions https://github.com/xamarin/Xamarin.Forms/pull/8849

**Comment by Mikilll94** [comment]
@jsuarezruiz 
I know that in my case swipe is only allowed from right to left. I was only swiping in this direction.

The problem is that swiping is sometimes not triggered and this happens very often.

To show that better to you, in my project try to swipe from right to left all items in the list. Try to do it quickly.

Here are my results on the emulator:

![swipe_bad_responsiveness](https://user-images.githubusercontent.com/17653648/71268732-edf60a00-234d-11ea-9f9c-5b6745ea0b93.gif)

As you can see swipe was not triggered twice.

Then try again on a real device with your thumb. The results will be worse. In the current state, this control is not user-friendly.

**Comment by jsuarezruiz** [comment]
Thanks for the feedback, we will do tests and continue to improve the SwipeView.

**Comment by Mikilll94** [comment]
@jsuarezruiz 
Thanks for your response. In case of questions, feel free to ask :)

**Comment by dczaretsky** [comment]
Tested on iOS and I see the same issues. Responsiveness is very poor. The context menu won't stay open, and often closes immediately by itself. Swiping right-to-left requires that you start at the right side; starting from middle or left side will not open the context menu.
 
Please compare the UX on iOS to the native ListView ContextActions/MenuItem as an example of how the SwipeView should behave on both iOS and Android.

**Comment by JanettHolst290490** [comment]
I have the same issue. In the debug on Android I can see that a swipe gesture is detected. It is just not always picked up by the SwipeView. So I think the SwipeView is too sensitive.

**Comment by shao200** [comment]
I have the same question, how's it going now?

**Comment by RonnyBansemer** [comment]
@samhouts @jsuarezruiz Any info about this issue? It still happens in XF 4.5.0.356. 
For me it seems to be a problem in combination with CollectionView. Swiping from right to left only works when being very fast and straight. Seems that in other case CollectionView is catching and cancelling the swipe event. 
There is also a bug with icons of FontImageSource. Their ratio is not respected as shown below:
![image](https://user-images.githubusercontent.com/45567951/76464196-2d7c4180-63e5-11ea-983c-b17a3cddcaf4.png)

Tested using:
XF 4.5.0.356
Android 7.0
Huawei MediaPad T3

**Comment by jsuarezruiz** [comment]
@RonnyBansemer Thanks for the feedback. The issue related with the touch conflicts will be fixed with this PR  https://github.com/xamarin/Xamarin.Forms/pull/9664 while the issue calculating the size of the icon using a FontIcon on Android will be fixed with https://github.com/xamarin/Xamarin.Forms/pull/9955
I hope we can merge this fixes soon!.

**Comment by samhouts** [comment]
closed by #9664
