### ISSUE TITLE
[Enhancement] Make NavigationPage.OnBackButtonPressed() public

### ISSUE THREAD

**Issue by ederbond** [xamarin/Xamarin.Forms#8985]
## Summary
Turn this method to public so we can use Behaviors to subscribe to it instead of having to make every page to inherit from a custom navigation page.

public NavigationPage.OnBackButtonPressed()

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
