### ISSUE TITLE
[Bug] App freezes on iPadOS 13.3 when in split view mode (multi-tasking) and change between pages

### ISSUE THREAD

**Issue by bobwhitten** [xamarin/Xamarin.Forms#8988]
### Description
I have come across a very strange bug -- not sure if it in Xamarin.Forms or iOS itself.

My app switches between several pages derived from ContentPage. When I have my app and another app, for example the iOS "Pages" app on my iPad side-by-side (e.g., half screen), changing pages more than once can cause my app to freeze up (no interaction) and also background color goes to white.  But, if I move the slider to make it a 2/3 split (or 1/3, or full screen), it immediately works.

When my app is to the left in 2/3 screen mode, the result is a bit comical --  first half of my app is OK (the leftmost third of the screen), but other half (middle third of screen) refuses to allow interaction (and has white background). Weirdest thing -- if the buttons straddles the break, the left part works fine, the right does not. LOL.

I've tried this on an iPad with 12.4.1 and 10.3.2 and I do not see this behavior.

I was able to create a simple app that demonstrates this, which I am attaching. It is "shared code", which I have stripped down to only iOS, and made minimal changes to.  (I checked and see bug with .NET standard too.)   Also attached is a screen shot.

MY IMPRESSION:  This oddness was introduced with either iPadOS 13 or 13.2

### Steps to Reproduce

1. Build attached project, SplitViewFreezeSample.  Start App on an iPad with 13.2 or above.
2. Start a secod app, placing it to the right of this app.
3. On App, click "Next Page" button at bottom, then "Go Back to Main Page", then "Next Page" again.

### Expected Behavior
Switching between pages should work indefinitely, and does when not in split screen.

### Actual Behavior
All or portion of app does not display properly, and buttons do not work.

### Basic Information
- Version with issue:  XF Forms 4.4, 4.3
- iPadOS 13.3 running on iPad Air 2

- Last known good version:
- IDE:  VS PC 16.4.1
- Platform Target Frameworks: 
  - iOS:  8 & 13.2
- Nuget Packages: none
- Affected Devices: iPad

### Screenshots
![SplitViewFreezeSmall](https://user-images.githubusercontent.com/1907489/71269732-dcd4db00-2304-11ea-9452-e5b3163af043.PNG)

### Reproduction Link
[SplitViewFreezeSample.zip](https://github.com/xamarin/Xamarin.Forms/files/3989203/SplitViewFreezeSample.zip)

**Comment by bobwhitten** [comment]
Update:  Also see this behavior on iPad Pro (12.9 inch) 2nd Generation with iOS 13.3.

It would be great if someone could verify, or tell me what I'm doing wrong, or tell me how to avoid this.

This seems like yet another iOS 13 or 13.2+ thing.

**Comment by bobwhitten** [comment]
Hmmm... I was thinking someone would jump on this thing.  I have heard on Xamarin Forum that it is reproducible.

**Comment by samhouts** [comment]
@bobwhitten We  have a bit of a backlog of issues to triage after the holidays, but we're not ignoring any of them! Thanks!

**Comment by rmarinho** [comment]
Hi @bobwhitten I think the issue is retaining the page, do you do this by any particular reason? 

If I change to something like this it works fine.
```
private async void btnNextPage_Clicked(object sender, EventArgs args) {
	await Navigation.PushModalAsync( new SecondPage(), false);
}
````

**Comment by bobwhitten** [comment]
Thanks @rmarinho for working on this.  In my "real" app, the 2nd page is pretty complex, and re-creating it every time would be really tough.

Not surre it's the best, but at this point my app creates all pages at start, and switches between them with PushModalAsync.  

Any clue why this seems to work fine for most conditions except this split view mode?
