### ISSUE TITLE
[Bug] IndicatorView - ItemsSourceBy not showing up in Intellisense

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#8992]
### Description
For IndicatorView control, the **ItemsSourceBy** property is not shown up by Intellisense

![image](https://user-images.githubusercontent.com/17653648/71292802-6374d100-2374-11ea-8869-a5431af9e518.png)

Also, XAML Hot Reload does not work with IndicatorView. When you change something in XAML, the IndicatorView is disappearing because probably XAML Hot Reload thinks that ItemsSourceBy property does not exist.

### Steps to Reproduce

1. Try to create IndicatorView.
2. Try to add ItemsSourceBy property to the IndicatorView
3. As you can see the Intellisense is not working for this property.

### Expected Behavior
Intellisense should show ItemsSourceBy property for IndicatorView. And XAML Hot Reload should also work for this property.

### Actual Behavior
Intellisense does not show ItemsSourceBy property for IndicatorView and XAML Hot Reload is not working with this property.

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: Visual Studio 2019 16.4.2
- Platform Target Frameworks: 
  - Android: 9.0 (Pie)

**Comment by VladislavAntonyuk** [comment]
You have to use IndicatorView.ItemsSourceBy

**Comment by Mikilll94** [comment]
@VladislavAntonyuk 
Thanks, it works.

But the docs are showing something different.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/populate-data

![image](https://user-images.githubusercontent.com/17653648/71328207-a02afe80-2513-11ea-91d5-09e56aca0452.png)

**Comment by nosmirck** [comment]
So, how does it really work? I can't make it work in any way possible. Do you care to show how you bind the ItemsSourceBy to the CarouselView's name?

**Comment by sthewissen** [comment]
@nosmirck See this small gist, which works for me:

https://gist.github.com/sthewissen/890262e30bfa0a43c53204a988e6902a

**Comment by rmarinho** [comment]
We have moved this API, now you will use the CarouselView IndicatorView property to link both controls.

Work is here https://github.com/xamarin/Xamarin.Forms/pull/9332
