### ISSUE TITLE
[Bug] [Android] CollectionView item layout is not correct after rotate

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#8994]
### Description
When page under NavigationPage.
rotate from Portrait to Landscape
the item will not take whole width of the collction view. 
until content updated or user scrolled.

![Portrait](https://user-images.githubusercontent.com/211855/71263237-7b505300-237c-11ea-8752-ad107f31f81a.png)
![Landscape](https://user-images.githubusercontent.com/211855/71301559-5c34de00-23db-11ea-85f6-45c11115aa87.png)

### Basic Information

- Version with issue: 4.4.0.991265

### Reproduction Link

[TestCollectionView-android_layout_issue.zip](https://github.com/xamarin/Xamarin.Forms/files/3988545/TestCollectionView-android_layout_issue.zip)

**Comment by bill2004158** [comment]
I guess maybe related to
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L385

which called base.OnLayout() before set correct page ContainerArea.
so the collectionView item layout with wrong size in that call.
And, didn't get onLayout() called when call child.Layout() after set page ContainerArea.

**Comment by maexsp** [comment]
Still waiting for a fix. ListView is no alternative for CollectionView in our case -> To slow for scenarios where 100 items with different DataTemplates have to be loaded per second. Please fix this layout issue! 
Responsive design for table landscape/portrait mode is also not possible with this major bug.

**Comment by hartez** [comment]
This appears to have been fixed in 4.7, probably as a side effect of another bug fix.
