### ISSUE TITLE
[Bug] [iOS] CollectionView doesn't layout correct after rotate & update size

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#8996]
### Description
we need let CollectionView show items into 3 columns when Landscape,
and 2 columns when Portrait.
however, after rotate few times, the collection view doesn't layout the items correctly.

### Steps to Reproduce

1. run my demo app in iPad
2. rotate it some times.

### Basic Information

- Version with issue: 4.4.0.991265

### Possible Reason

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/CollectionView/ItemsViewLayout.cs#L156
>		public override bool ShouldInvalidateLayoutForBoundsChange(CGRect newBounds)
>		{
>			var shouldInvalidate = base.ShouldInvalidateLayoutForBoundsChange(newBounds);
>
>			if (shouldInvalidate)
>			{
>				UpdateConstraints(newBounds.Size);
>			}
>
>			return shouldInvalidate;
>		}

the callback method executed a bit late, which collection view's size already changed.
which updated UpdateConstraints with old value.

Suggestion:

>  -var shouldInvalidate = base.ShouldInvalidateLayoutForBoundsChange(CollectionView?.Bounds ?? newBounds);
> +var shouldInvalidate = base.ShouldInvalidateLayoutForBoundsChange(CollectionView?.Bounds ?? newBounds);

>  -UpdateConstraints(newBounds.Size);
> +UpdateConstraints(CollectionView?.Bounds ?? newBounds);

### Reproduction Link

[TestCollectionView-android_layout_issue.zip](https://github.com/xamarin/Xamarin.Forms/files/3988545/TestCollectionView-android_layout_issue.zip)

**Comment by samhouts** [comment]
closed by #10622
