### ISSUE TITLE
[Bug] Unable to open a new Page for the second time in Xamarin.Forms Shell Tabbar

### ISSUE THREAD

**Issue by nikhildpardasani** [xamarin/Xamarin.Forms#9006]
### Description
In Xamarin.Forms Shell Tabbar, one cannot navigate to the first page that is opened in a Tab.
Supposing you are on Tab1 of the Tabbar and that Tab has 3 pages under the hierarchy and you click on a button which navigates to Tab1/Page1. Now you Tap on Tab1 Icon on the Tabbar and you are navigated back on Tab1. Now if you click on the same button to navigate to  Tab1/Page1  you will not be navigated. Now if you kill the App and launch again and you click on a button which navigates to Tab1/Page2, you get navigated to Page2 and you come back by clicking at the Tab1 on the Tabbar and not the back Icon on the Navigation Bar, in this case you cannot navigate to Tab1/Page2 again ever unless you kill the App.

### Steps to Reproduce

1. Launch a Xamarin Forms Shell App and by default you are on Tab1.
2. Click on the button that says "Click here to go to Page 1A" and you are navigated to Tab1/Page1A.
3. Click on Tab1 icon at the Tabbar, you will be navigated back to Tab1.
4. Click on the button that says "Click here to go to Page 1A" and you will not be able to navigate to Tab1/Page1A.

### Expected Behavior

1. Launch a Xamarin Forms Shell App and by default you are on Tab1.
2. Click on the button that says "Click here to go to Page 1A" and you are navigated to Tab1/Page1A.
3. Click on Tab1 icon at the Tabbar, you will be navigated back to Tab1.
4. Click on the button that says "Click here to go to Page 1A" and you **should** navigate to Tab1/Page1A.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991265
- Last known good version: NA
- IDE: Visual Studio 
- Platform Target Frameworks: 
  - iOS:  

- Affected Devices:
All

### Screenshots
![ScreenRecording2019-12-23at41030](https://user-images.githubusercontent.com/51998596/71353478-2c363800-259f-11ea-8b0e-a5cf802bddfe.gif)

### Reproduction Link
Here is a link to the sample repo for you to verify.
https://github.com/nikhildpardasani/RoutingInShell

**Comment by rscholey** [comment]
I have the same problem and I see frequent crashes.  When I check the route I see that XF is generated incorrect routes.  Here is an example:

System.ArgumentException: unable to figure out route for: //TabBar12/Tab5/DictionaryTab/DictionaryTab/CardListPage/DictionaryTab/CardListPage Parameter name: uri

In this case the correct route should be:

//TabBar12/Tab5/DictionaryTab/CardListPage

This is a serious problem for me as it's effecting many users and right now I cannot see any solution.  

Please help and look into this as soon as possible

**Comment by rscholey** [comment]
I am experiencing the same problem.  The shell navigation seems to lose track of what it's doing.  In my case I see appcenter errors like this:

ShellUriHandler.GetNavigationRequest (Xamarin.Forms.Shell shell, System.Uri uri, System.Boolean enableRelativeShellRoutes)
System.ArgumentException: unable to figure out route for: //TabBar12/Tab5/DictionaryTab/**DictionaryTab/CardListPage/DictionaryTab**/CardListPage Parameter name: uri

Note the repeated strings in this uri for what should be the route:

//TabBar12/Tab5/DictionaryTab/CardListPage Parameter name: uri

**Comment by rscholey** [comment]
This issue is still coming up and being reported to me via appcenter.  For example here is another:

route
//TabBar12/Tab9/HelpTab/HelpTab/IntroductionPage/HelpTab/Concept

See all the repeated mentions of "HelpTab"

The routing internals appear to be very confused.   I realize this may not be a priority as others are not reporting it but also I have a quite complex shell app and from my conversations with other devs  most of them are not even using shell navigation.  I hope someone can look into this issue soon. 

{
  "length": 0,
  "offset": 0,
  "id": "d6e63703-1c72-4e9b-bfb6-c0396f545afa",
  "exception": {
    "type": "System.ArgumentException",
    "message": "unable to figure out route for: //TabBar12/Tab9/HelpTab/HelpTab/IntroductionPage/HelpTab/Concept\nParameter name: uri",
    "stackTrace": "  at Xamarin.Forms.ShellUriHandler.GetNavigationRequest (Xamarin.Forms.Shell shell, System.Uri uri, System.Boolean enableRelativeShellRoutes) <0x100a1fe00 + 0x00398> in <c9b8223b0229425ebbb1af0a521ee610#b033c4571e79ba3dba4f10c91e4b8190>:0 \n  at Xamarin.Forms.Shell.GoToAsync (Xamarin.Forms.ShellNavigationState state, System.Boolean animate, System.Boolean enableRelativeShellRoutes) <0x100a11bd0 + 0x000d7> in <c9b8223b0229425ebbb1af0a521ee610#b033c4571e79ba3dba4f10c91e4b8190>:0 \n  at Japanese.Helper.OpenPageAsync (System.String route) <0x1015c73a0 + 0x00197> in <460a5aefe005480680b03f394d540b43#b033c4571e79ba3dba4f10c91e4b8190>:0 ",
    "wrapperSdkName": "appcenter.xamarin"
  },
  "properties": {
    "exception": "System.ArgumentException: unable to figure out route for: //TabBar12/Tab9/HelpTab/HelpTab/IntroductionPage/HelpTab/Concept\nPa",
    "device Model": "iPhone7,2",
    "helper": "OpenPageAsync",
    "route": "//TabBar12/Tab9/HelpTab/HelpTab/IntroductionPage/HelpTab/Concept"
  },

**Comment by rscholey** [comment]
Hi @samhouts - would be great if this issue could get some priority to be checked out as right now it's a big issue with appcenter.ms showing the problem comes up multiple times for my users.  As its very easy to reproduce I can only assume that anyone else that uses the same code logic will in future face the same issue of the navigation route getting corrupted.

**Comment by samhouts** [comment]
closed by #9086

**Comment by stavroaudi** [comment]
Was this only fixed for iOS? I still get the issue on Android. 

Appcenter:

System.ArgumentException: unable to figure out route for: //dashboard/D_FAULT_AboutPage18 Parameter name: uri
O

Not sure where D_FAULT_AboutPage comes from nor the number (18) after it. I don't even use URI GoToAsync on my AboutPage.
