### ISSUE TITLE
[Bug] SwipeView inside SwipeView - not working

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9007]
### Description
When there is SwipeView inside another SwipeView, the internal SwipeView is not working. The swipe gestures are completely ignored.

This is my use case: I want to create a CollectionView with context actions, so I need to wrap every CollectionView item in a SwipeView. But I also want to have a customized pull to refresh functionality on a whole CollectionView. So I need to wrap the whole CollectionView in a SwipeView.

### Steps to Reproduce

1. Run this project
[CollectionViewTest.zip](https://github.com/xamarin/Xamarin.Forms/files/3996364/CollectionViewTest.zip)

2. Swipe down on a CollectionView -> SwipeView is working, the activity indicator is shown
3. Swipe right any CollectionView item -> SwipeView is not working. Nothing happens.

### Expected Behavior
Nested SwipeView inside another SwipeView should work.

### Actual Behavior
Nested SwipeView inside another SwipeView does not work at all.

### Basic Information

- Version with issue: 4.4.0.991265
- IDE: 16.4.2
- Platform Target Frameworks: 
  - Android: Pie (9.0)

**Comment by hartez** [comment]
> But I also want to have a customized pull to refresh functionality on a whole CollectionView. So I need to wrap the whole CollectionView in a SwipeView

Have you tried using a RefreshView for the refresh functionality?

**Comment by Mikilll94** [comment]
@hartez 
I know that there is a RefreshView, but I want to customize the refresh indicator. It is not shown in this example - this is just a simple presentation of a bug.

However, I think that SwipeView inside SwipeView should work. It is not stated in docs that you cannot nest SwipeViews.

**Comment by MichaelShapiro** [comment]
@Mikilll94 Sorry for bothering on such an old and closed post. I'm facing identical issue but with maui now. Have you even found a solution or alternate approach for this use case?
