### ISSUE TITLE
[Enhancement] Allow extend GroupableItemsViewAdapter

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#9012]
## Summary
We want to extend GroupableItemsViewAdapter for some extra feature.
however, it is internal class, is it possible make it public?

## API Changes

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/CollectionView/GroupableItemsViewAdapter.cs#L12

make the class public.

## Intended Use Case

allow developer to extend it for customize feature.

**Comment by samhouts** [comment]
closed by #10521
