### ISSUE TITLE
[Enhancement] Add iOS Specific Configuration UpdateMode for DatePicker, TimePicker

### ISSUE THREAD

**Issue by xamarindevelopervietnam** [xamarin/Xamarin.Forms#9015]
This feature is already available for Picker, pls apply for DatePicker and TimePicker.
Thanks you!

**Comment by xamarindevelopervietnam** [comment]
related to https://github.com/xamarin/Xamarin.Forms/commit/99c78edc8e2fa04ebb90af32d54974bd11d65f54

**Comment by jfversluis** [comment]
In the commit you linked I already see code for `TimePicker` and `DatePicker`. What exactly are you missing?

**Comment by xamarindevelopervietnam** [comment]
Thanks @jfversluis! That's exactyly what i want.

**Comment by xamarindevelopervietnam** [comment]
closing.
