### ISSUE TITLE
[Bug] CollectionView FooterView moves up to the HeaderView

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#9016]
The FooterView doesn't stay on the bottom

### Steps to Reproduce
Create a CollectionView with no items

### Expected Behavior
FooterView stays at the bottom

### Actual Behavior
FooterView moves up to the HeaderView

- Version with issue: XF 4.4.0

### Screenshots
![image](https://user-images.githubusercontent.com/13821046/71451060-8cc79f80-276e-11ea-9401-15f8fc7df725.png)

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@mknotzer  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
