### ISSUE TITLE
FFMPEG for XAMARIN FORMS CROSSPLATFORM (IOS and ANDROID)

### ISSUE THREAD

**Issue by premingiet** [xamarin/Xamarin.Forms#9018]
### Description
There is no ffmpeg support for xamarin forms. How to use ffmpeg for both android and ios from xamarin forms ? I have seen ffmpeg crossplatform for ios and android supported in react-native and also on flutter but i would like to use it from xamarin forms.

### Steps to Reproduce

No Xamarin forms package for ffmpeg to be used for ios and android xamarin forms app. Maybe nuget package would help

### Expected Behavior
Expected to use a nuget ffmpeg package for xamarin forms for both ios and android.

### Actual Behavior
Cant find any ffmpeg xamarin forms package

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: none
- Affected Devices: All ios and android devices

**Comment by xamarindevelopervietnam** [comment]
++

**Comment by TingtingAn** [comment]
+1

**Comment by johnn82** [comment]
I thing FFMPEG is not the way, due to a license problem when embedding it.

I think a better way would be the porting of these two libraries:

for iOS a nice import of  this would be nice!
https://github.com/rs/SDAVAssetExportSession

for Android a nice import of this would be nice! 
https://github.com/natario1/Transcoder

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
