### ISSUE TITLE
[Bug] [Android] Vertical Scroll Bars appear on Button inside ScrollView with custom Style 

### ISSUE THREAD

**Issue by kuzub** [xamarin/Xamarin.Forms#9019]
### Description
After upgrade to XF 4.4.0.991265 on Android 
Vertical Scroll Bars appear on Button inside ScrollView with custom Style (font)

### Steps to Reproduce

1. Create new project with Xamarin.Forms 4.2.0.709249
2. Add ScrollView with buttons and custom style with font
3. Upgrade to Xamarin.Forms 4.4.0.991265

### Expected Behavior
Buttons without vertical scroll bar inside

### Actual Behavior
Vertical Scroll Bars appear on Buttons (short time)

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 4.2.0.709249
- IDE: Visual Studio Community 2019 for Mac Version 8.3.11 (build 1)
- Platform Target Frameworks: 
  - Android: Android 9.0
- Android Support Library Version: Xamarin.Android.Support.Core.Utils 28.0.0.3
- Nuget Packages: Xamarin.Essentials 1.3.1
- Affected Devices: Samsung S8
### Screenshots

![issue](https://user-images.githubusercontent.com/2078011/71478382-fb047480-27f7-11ea-8002-dd96327766aa.gif)

![Screenshot_20191226-144209-2](https://user-images.githubusercontent.com/2078011/71477643-cc849a80-27f3-11ea-813c-19de1211c203.png)

### Reproduction Link

https://github.com/kuzub/ButtonWithScrollViewIssue

**Comment by kuzub** [comment]
If add empty ButtonRenderer -> Issue will fixed
    public class FixButtonIssueRenderer : ButtonRenderer
    {
        public FixButtonIssueRenderer(Context context) : base(context)
        {
        }
    }

**Comment by samhouts** [comment]
Seems to have happened between 4.3.0 and 4.4.0-pre1.

**Comment by dminta** [comment]
This bug was introduced with changes for issue #8090.

Temporary workaround:
* replace `ScrollView` with empty `CustomScrollView`:

> public class CustomScrollView : ScrollView
> {
> }

* create empty `CustomScrollViewRenderer` for Android:

> [assembly: ExportRenderer(typeof(CustomScrollView), typeof(CustomScrollViewRenderer))]
> 
> ...
> 
> public class CustomScrollViewRenderer : ScrollViewRenderer
> {
> }

It uses `Forms.Context` instead of `ContextThemeWrapper(context, Resource.Style.NestedScrollBarStyle)`.

**Comment by jonx** [comment]
I'm using a padding of -10 to work around that problem.
```
<Style x:Key="PrimaryButtonStyle" TargetType="Button">
        <Setter Property="Padding" Value="-10" />
</Style>
```
I was using some padding on Android already to deal with the fact that the text gets clipped when the size of the button is smaller then what is need to draw the text (Only on Android)

**Comment by TopSkillDeveloper** [comment]
> This bug was introduced with changes for issue #8090.
> 
> Temporary workaround

it helped, but not everywhere (but it's better than nothing). Used through the effects of disabling scrolling for labels

**Comment by FlavioGoncalves-Cayas** [comment]
Did the ScrollBars disappear completely?
