### ISSUE TITLE
[Spec]  Why don't we merge Xamarin forms with Uno

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#9026]
Just for discussion, Why not to merge Xamarin Forms with the new Uno project? or do it the way Uno is doing it, so we stop worrying about UI that works here but doesn't work there? The evolution of Xamarin Forms is very slow, until now we can't play a video from the internet! in fact, until now we can't customise tabbed page headers in all platforms easily. You always mention "Native controls" and I understand that for a navigation page and a map, but other than that it doesn't really matter.

**Comment by Happypig375** [comment]
You mean https://github.com/unoplatform/Uno.Xamarin.Forms.Platform?

**Comment by MhAllan** [comment]
@Happypig375 No, that one is porting Xam forms to browser, I am asking to relay on UWP and stop making Xamarin Forms controls with renderers.

**Comment by samhouts** [comment]
This is not on our roadmap, but you're welcome to discuss the pros and cons of such an approach here. Thanks!
