### ISSUE TITLE
[Bug] ClassNotFoundException when using snap points on API < 23

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#9030]
### Description
A `ClassNotFoundException` is thrown when using snap points in a `CollectionView` on Android versions < 6.0 (API 23).

This is due to [wiring](https://github.com/xamarin/Xamarin.Forms/blob/1de59c5e7ea5c3ee2dc7250f8ebd31eda9e650a7/Xamarin.Forms.Platform.Android/CollectionView/NongreedySnapHelper.cs#L22) into the View.ScrollChange event which is only available in API 23 and above. Refer to [Android API specification](https://developer.android.com/reference/android/view/View.OnScrollChangeListener).

Note: This event is also used in the [SwipeViewRenderer](https://github.com/xamarin/Xamarin.Forms/blob/d45bd2195063cd5064a003eedcef4caffbcea9a1/Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs#L160) likely leading to the same exception.

### Steps to Reproduce

1. Open the control samples app on an affected device.
2. Open the CollectionView gallery snap points page.

### Expected Behavior
The app should not crash.

### Actual Behavior
The app crashes with the following exception:

```
ava.Lang.ClassNotFoundException: Didn't find class "mono.android.view.View_OnScrollChangeListenerImplementor"

Android.Views.View+IOnScrollChangeListenerImplementor..ctor (System.Object sender) [0x00010] in <82e2c298095040ab99611f85aa135203>:0
View.__CreateIOnScrollChangeListenerImplementor ()
EventHelper.AddEventHandler[TInterface,TImplementor] (System.WeakReference& implementor, System.Func`1[TResult] creator, System.Action`1[T] setListener, System.Action`1[T] add)
View.add_ScrollChange (System.EventHandler`1[TEventArgs] value)
NongreedySnapHelper.AttachToRecyclerView (Android.Support.V7.Widget.RecyclerView recyclerView)
```

### Basic Information
- Version with issue: 4.4.0
- Affected Devices: Android devices < 6.0 (API 23).

### Screenshots
N/A

### Reproduction Link
N/A

**Comment by PureWeen** [comment]
@jsuarezruiz It looks like 

```
at Android.Views.View.set_ClipToOutline (System.Boolean value) [0x00018] in /Users/runner/runners/2.161.1/work/1/s/src/Mono.Android/obj/Release/android-28/mcw/Android.Views.View.cs:5351 
```

Is also an issue. You can reproduce by running any SwipeView samples on an API 19 device
