### ISSUE TITLE
[Bug] [Android] CollectionView EmptyView not visible when HeaderView exists

### ISSUE THREAD

**Issue by mknotzer** [xamarin/Xamarin.Forms#9032]
EmptyView not visible when HeaderView exists, working on iOS

- Version with issue: XF 4.2.0+

**Comment by velocitysystems** [comment]
@mknotzer I believe this is fixed by this PR https://github.com/xamarin/Xamarin.Forms/pull/8415 and will be available in the next release of 4.4.0.

**Comment by samhouts** [comment]
@mknotzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by dsdilpreet** [comment]
Hi @samhouts, 

I have tried on Xamarin Forms v4.4.0.991477 and see similar problem.

I have attached a sample of collection view. When I comment header and footer part of collection view, text inside empty view would get printed otherwise it does not get printed.

[collection_view_1.txt](https://github.com/xamarin/Xamarin.Forms/files/4057420/collection_view_1.txt)

This exact code was working for me in Xamarin Forms v4.0.0 but not working in version 4.0.0 sr2. When I say working, I mean empty view was getting printed even when header and footer was present before upgrading to sr2.

Let me know if that helps please.

**Comment by samhouts** [comment]
[Issue9032.zip](https://github.com/xamarin/Xamarin.Forms/files/4120379/Issue9032.zip)

It doesn't look like commenting out the Footer/Header does anything. However, it does look like removing the Style that's applied to the Label makes it appear. Is that what you see, too? Thanks!

**Comment by dsdilpreet** [comment]
Hi @samhouts ,

Thank you for trying out the sample.

Yes, you are correct, removing the style from label does seem to make a difference.

Also, for me, commenting and un-commenting the header and footer also makes a difference. See below.

![1](https://user-images.githubusercontent.com/11010830/73232549-76d35180-41e8-11ea-8c32-40c62384c712.PNG)
1) No style on label, no header and footer and empty view is printing.

![2](https://user-images.githubusercontent.com/11010830/73232583-966a7a00-41e8-11ea-8aa4-4266a7544212.PNG)
2) No style on label, header and footer present and no empty view

**Comment by dmitryshindin** [comment]
@dsdilpreet Possible workaround will be initializing the `ObservableCollection` Property.

Displays nothing with:
`public ObservableCollection<Grade> Grades { get; set; } `

Displays header, footer and empty state with:
```
public ObservableCollection<Grade> Grades { get; set; } =
new ObservableCollection<Grade>(new List<Grade> { });
```

**Comment by dsdilpreet** [comment]
Thanks @dmitryshindin , I will give it a try

**Comment by dsdilpreet** [comment]
@dmitryshindin , your workaround is working. Thanks again for your help.

**Comment by luismts** [comment]
+1

@dmitryshindin thanks for the workaround! You are cool

**Comment by jlucaspains** [comment]
I'm still seeing this issue in Xamarin 4.7.0.1142 and the workaround does not seem to work anymore. Any news about a fix for this issue?

**Comment by klogeaage** [comment]
Mee too, it seems not to work in latest 4.7. Please re-open.

**Comment by hartez** [comment]
This is now working in 5.0.0.
