### ISSUE TITLE
[Bug] System.TypeInitializationException being thrown when I manually uninstall the app and reinstall it on Android

### ISSUE THREAD

**Issue by thekeviv** [xamarin/Xamarin.Forms#9036]
### Description
Here's the stack trace

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Layout' threw an exception. ---> System.MissingFieldException: Field not found: int .Style.NestedScrollBarStyle Due to: Could not find field in class
12-28 07:53:30.701 E/mono-rt (11364):   at Android.Runtime.ResourceIdManager.UpdateIdValues () [0x00097] in <11f101b564894ca7af6c482ddc51c698>:0 
12-28 07:53:30.701 E/mono-rt (11364):   at Xamarin.Forms.Platform.Android.Resource+Layout..cctor () [0x0029e] in D:\a\1\s\Xamarin.Forms.Platform.Android\Resources\Resource.Designer.cs:3948 
12-28 07:53:30.701 E/mono-rt (11364):    --- End of inner exception stack trace ---
12-28 07:53:30.701 E/mono-rt (11364):   at (wrapper managed-to-native) System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(intptr)
12-28 07:53:30.701 E/mono-rt (11364):   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (System.RuntimeTypeHandle type) [0x00023] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:90 
12-28 07:53:30.701 E/mono-rt (11364):   at Xamarin.Forms.Platform.Android.Anticipator+<>c__DisplayClass9_0.<AnticipateClassConstruction>b__0 () [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\Anticipator.cs:77 
12-28 07:53:30.701 E/mono-rt (11364):   at Xamarin.Forms.Platform.Android.Anticipator.Loop (System.Object argument) [0x00018] in D:\a\1\s\Xamarin.Forms.Platform.Android\Anticipator.cs:51 
12-28 07:53:30.701 E/mono-rt (11364):   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00025] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/threading/thread.cs:78 
12-28 07:53:30.701 E/mono-rt (11364):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:968 
12-28 07:53:30.701 E/mono-rt (11364):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:910 
12-28 07:53:30.701 E/mono-rt (11364):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:899 
12-28 07:53:30.701 E/mono-rt (11364):   at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/threading/thread.cs:93 
### Steps to Reproduce

1. Create a new shell template Xamarin Forms project 
2. Run with the Android project as Startup project
3. Error thrown

### Expected Behavior
Apps runs without an error
### Actual Behavior
Error Thrown
### Basic Information
This doesn't always happen, it has been impacting me for a while now. It goes away when I do a clean. But appears every time I uninstall the app manually from the device and reinstall it again.
- Version with issue:16.4.2
- Last known good version:
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by PureWeen** [comment]
This doesn't seem like a Xamarin.Forms bug

@thekeviv are you still seeing this exception with the latest version of Visual Studio?

**Comment by thekeviv** [comment]
Hi, sry for the late reply. This was a weird issue which for me would require me to do a clean and a build again and everything would be fine and it would pop up again after a few builds. Hasn't happened in a while though..

**Comment by jfversluis** [comment]
Going to assume this is fixed
