### ISSUE TITLE
[Bug] Updating properties of Tabbed Page add item to Content Page

### ISSUE THREAD

**Issue by pereirafabiosantos1989** [xamarin/Xamarin.Forms#9037]
### Description
Hello!
 I created a TabbedPage.
When I update any property of this page, another content page is displayed in the phone.
I'm using XAML Hot Reload, building the app to a Android 9.0 phisical device and using adb tcpip to connect to the device.
### Steps to Reproduce
1. Create a TabbedPage with at least 2 ContentPage as child.
2. Update any property

### Expected Behavior
1. You'll see that these changes became more 2 child pages.

### Basic Information

- Version with issue: I'm using Xamarin.Forms 4.4.0.991265
- Last known good version:
- IDE: Visual Studio Community 2019
- Platform Target Frameworks: 
  - iOS:  It isn't in the project
  - Android: 9.0 
  - UWP:  It isn't in the project
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Phisical

**Comment by samhouts** [comment]
@pereirafabiosantos1989  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@pereirafabiosantos1989  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
