### ISSUE TITLE
[Bug] Android ListView Refresh Inidicator will not disappear some case.

### ISSUE THREAD

**Issue by bill2004158** [xamarin/Xamarin.Forms#9039]
### Description
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/ListViewRenderer.cs#L402

> 		void UpdateIsRefreshing(bool isInitialValue = false)
>		{
>			if (_refresh != null)
>			{
>				var isRefreshing = Element.IsRefreshing;
>				if (isRefreshing && isInitialValue)
>				{
>					_refresh.Refreshing = false;
>					_refresh.Post(() =>
>					{
>						if(_refresh.IsDisposed())
>							return;
>						
>						_refresh.Refreshing = true;
>					});
>				}
>				else
>					_refresh.Refreshing = isRefreshing;
>			}
>		}

it will set Refreshing to true in Post().
the problem is when execute that action, the Element.IsRefreshing maybe already set to false.

so why not:
>	-_refresh.Refreshing = true;
>	+_refresh.Refreshing = Element.IsRefreshing;

**Comment by samhouts** [comment]
@bill2004158  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@bill2004158  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
