### ISSUE TITLE
[Bug] - Gesture not working inside collectionview and listiview in xamarin 4.4.0

### ISSUE THREAD

**Issue by viveknegi51288** [xamarin/Xamarin.Forms#9040]
### Steps to Reproduce

1. Create a xamarin forms project
2. Add CollectionView or Listview , add 1 label and 1 image inside cell of both
3. Add tabgesture to label and image
4. Create command on viewmodel and call two different method (XYZ () - for label and abc() for image.
5. Debug the code. 
6. Method will not be called from any gesture.
[Example.zip](https://github.com/xamarin/Xamarin.Forms/files/4008008/Example.zip)

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
The gesture is working. It's your binding. Anything inside the `DataTemplate` is bound to the ItemsSource model. In this case, the binding context is a `LeaveSummary`, which does not have your command--the command is one level up on your View Model. 

You can see this in the debug output: 

```Binding: 'ImageButtonCommand' property not found on 'Example.ViewModels.LeaveSummary', target property: 'Xamarin.Forms.TapGestureRecognizer.Command'``` 

There are some solutions for this scenario on StackOverflow. https://stackoverflow.com/questions/40913439/xamarin-forms-button-command-binding-inside-a-listview

Thanks!
