### ISSUE TITLE
[Bug] CollectionView Items Layout is Not Updating on Item Binding Property Changed and Triggered in iOS

### ISSUE THREAD

**Issue by kumarc-123** [xamarin/Xamarin.Forms#9041]
###The new CollectionView items are not updating their layout correctly in iOS (Android is fine) on item's binding property changes. 

### Steps to Reproduce

1. Create a collection view with custom data bindings
2. Add a data template with at least more than one UI element(s) in each item. I have used the stack layout
3. Add a trigger to at least one UI element (preferable `IsVisible`) with item binding. Preferred property setter is `IsVisible`.
4. Make sure to add sufficient items to increase the content size. Twice or thrice or more the screen's height should be fine.
5. Scroll to the bottom of the collection view, so that it is already calculated the content size and item size of each item layout.
6. Now change the values of all / few items randomly. This will trigger the UI elements to be visible or change the UI elements binding triggers.
7. Scroll up and see the items laid out overlapping or reduced item sizes. You may also observe a few items not visible at all. This happened for grouped list for me.

```
<CollectionView ItemsSource="{Binding FieldList}"
                        ItemTemplate="{StaticResource FormFieldTemplateSelector}"
                        IsGrouped="True"
                        SelectionMode="None"
                        ItemSizingStrategy="MeasureAllItems"
                        VerticalOptions="StartAndExpand"
                        AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
                        AbsoluteLayout.LayoutFlags="All"
                        x:Name="CollectionView">

            <CollectionView.Margin>
                <OnIdiom x:TypeArguments="Thickness" Default="10, 10, 10, 80" Tablet="60, 10, 60, 120" />
            </CollectionView.Margin>

            <CollectionView.GroupFooterTemplate>
               <DataTemplate >
                   <ContentView HeightRequest="10"/>
               </DataTemplate>
            </CollectionView.GroupFooterTemplate>

            <CollectionView.GroupHeaderTemplate>
                <DataTemplate>
                    <templateViews:GroupHeaderView Command="{Binding BindingContext.SectionToggleCommand, Source={x:Reference Page}}"
                                                   CommandParameter="{Binding .}" />
                </DataTemplate>
            </CollectionView.GroupHeaderTemplate>

            <CollectionView.ItemsLayout>
                <LinearItemsLayout Orientation="Vertical" ItemSpacing="0" />
            </CollectionView.ItemsLayout>

        </CollectionView>

```
### Expected Behavior
The items should be laid out without affecting other items' layout on property change.
### Actual Behavior
The content size is not updating and items are overlapping with other items with few items not visible at all.
### Basic Information

- Version with issue: - Xamarin Forms 4.4.0.991265
- Last known good version:
- IDE: Visual Studio Mac 2019 v8.3.11 (build 1)
- Platform Target Frameworks: 
  - iOS:  - iOS 13.3
  - Android: SDK Platform API Leve; 29
  - UWP:  NA
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All iOS

**Comment by samhouts** [comment]
@kumarc-123  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@kumarc-123  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
