### ISSUE TITLE
[Bug] IOS Label text alignment in RTL

### ISSUE THREAD

**Issue by Cloudtrackers** [xamarin/Xamarin.Forms#9046]
### Description
In RTL , Label text alignment is left only in iOS, it's working fine in android.

### Steps to Reproduce
if the Label
1.  HorizontalOptions is "FillAndExpand"    
2. HorizontalTextAlignment is "Start" 
3. And FlowDirection is RTL

### Expected Behavior

Text alignment should be align from Right.

### Actual Behavior

Text is aligned left.

### Basic Information

- Version with issue:  Xamarin.Forms 4.4.0.991265
- Last known good version:   Xamarin.Forms 4.2.0.910310
- IDE:  Visual Studio Community 2019 for Mac
            Version 8.3.11 (build 1)
- Platform Target Frameworks: 
  - iOS:  iOS: 13.3
  - Android: Android: 9 
  
- Affected Devices: iOS Devices

### Screenshots
<img width="459" alt="Screen Shot 2019-12-30 at 8 59 11 AM" src="https://user-images.githubusercontent.com/55684888/71569190-cab62200-2ae6-11ea-92e1-3c6b60849c65.png">

**Comment by AmrAlSayed0** [comment]
Yes, I am also having this issue. It happens only when the label has Arabic text AND the device locale is a non-RTL locale like English AND the label has multi line text. Single line labels are correctly displayed on iOS.

**Comment by AmrAlSayed0** [comment]
Minimum reproduction repo.
If:
Device locale or App local is English (and probably any other LTR locale)
And
The Label HorizontalTextAlignment is Start
And
Label text is long enough to be multiple lines
this bug happens
[RtlLabelIosBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4009710/RtlLabelIosBug.zip)

**Comment by Cloudtrackers** [comment]
This bug happens after the released version of  Xamarin.Forms(4.2.0.910310).

**Comment by Cloudtrackers** [comment]
Now going to release  Xamarin Forms 4.5 (three breaking releases). still the bug is open.

**Comment by Cloudtrackers** [comment]
At the end of April 2020 apple development community going to stop accepting submissions of apps that use UIWebView APIs . in the Xamarin Forms 4.5 resolving this issue, but we can't upgrade to Xamarin Forms 4.5 because still this bug is open. Now the app developmental process is going to be source stopping stage. When can be expect the resolution ??

**Comment by yurkinh** [comment]
@Cloudtrackers @AmrAlSayed0  I have a solution.  I will do some more check and will submit PR today

 ![RTLFix](https://user-images.githubusercontent.com/17849938/75678227-d57f6580-5c95-11ea-9033-4d4fff9c8a18.gif)

**Comment by yurkinh** [comment]
@Cloudtrackers @AmrAlSayed0  Here is a workaround with custom label renderer while I'm preparing PR
[RtlLabelIosBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4275631/RtlLabelIosBug.zip)

**Comment by darrabam** [comment]
This bug is still there, I'm using Xamarin.Forms 4.5.0.530

**Comment by yurkinh** [comment]
@darrabam Fix has not been merged yet

**Comment by rmarinho** [comment]
This should be fixed!
