### ISSUE TITLE
Open the Xamarin.Forms.UWP app via command prompt.

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#9047]
### Description

To open the Xamarin.Forms.UWP app via command prompt. I have tried to open my Xamarin.Forms.UWP app using comment prompt, I have followed the mentioned instruction in the below link.  But the application does not Launched. But it’s working fine in Native UWP. I have attached the both Xamarin and native UWP project for your reference. Can please check this and help to open the Xamarin.Forms.UWP app in comment prompt?

https://www.c-sharpcorner.com/article/launch-uwp-app-via-commandline/

### Steps to Reproduce

1.  Run the attached sample.
2. And Open the Command prompt.
3. Enter the sample Name
4. See the Native UWP App is open, But the Xamarin.Forms.UWP App does not open.

### Expected Behavior
Xamarin.Forms.UWP App need to be Open

### Actual Behavior
Xamarin.Forms.UWP App does not open.
[Sample_XF_UWP.zip](https://github.com/xamarin/Xamarin.Forms/files/4009101/Sample_XF_UWP.zip)
[Native_UWP_App.zip](https://github.com/xamarin/Xamarin.Forms/files/4009102/Native_UWP_App.zip)

**Comment by hartez** [comment]
When you run a UAP app from the command line with this method, the `OnActivated` method is called, but `OnLaunched` is not. So you need to initialize Xamarin.Forms in your `OnActivated` method. Change

```
rootFrame.NavigationFailed += OnNavigationFailed;
// Place the frame in the current Window  
Window.Current.Content = rootFrame;
```

to

```
rootFrame.NavigationFailed += OnNavigationFailed;

Xamarin.Forms.Forms.Init(e);

// Place the frame in the current Window  
Window.Current.Content = rootFrame;
```

in your `OnActivated` override. The app will successfully launch from the command line.
