### ISSUE TITLE
[Bug] MTOUCH: Error MT2001: Could not link assemblies. 

### ISSUE THREAD

**Issue by Jayamanikandan96** [xamarin/Xamarin.Forms#9049]
### Steps to Reproduce

1. After installing Microcharts package.

### Expected Behavior
Need to install my app in iOS device.

### Actual Behavior
App not installing in iOS device.(Could not link assemblies)

### Basic Information

- Version with issue:Xamarin forms 4.2.0.709249
- Last known good version:
- IDE:Visual studio 8.3.11(build 11)
- Platform Target Frameworks: 
  - iOS: Deployment target 8.0
  - Android: Target android version (API level 28) 
  - UWP:   
- Android Support Library Version: 28.0.0.1
- Nuget Packages:Autofac,Microcharts,Microcharts forms,Newtonsoft.Json,Rg.Plugins.Popup,Xam.Plugin.Media,Xamarin.Essentials,Xamarin.FFImageLoading.Forms,Xamarin.FFImageLoading.Transformations,Xamarin.Forms,ZXing.Net.Mobile,ZXing.Net.Mobile.Forms.
- Affected Devices:

**Comment by PureWeen** [comment]
@Jayamanikandan96 can you attach a small repro please?

**Comment by samhouts** [comment]
@Jayamanikandan96  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
