### ISSUE TITLE
[Bug] View recycling in CollectionView does not work on UWP

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#9051]
### Description
View recycling in `CollectionView` does not work on UWP.
Also, all items views are activated on the initial load not just the items in the _viewport_.

### Steps to Reproduce

1. Open the attached sample project. Run on UWP.
2. Resize the application window to permit scrolling.
3. Scroll up and down in the list.

_Behavior on UWP_
![Screenshot 2019-12-30 at 9 51 50 am](https://user-images.githubusercontent.com/5580462/71586982-056d8980-2aea-11ea-87c9-8b8660854796.png)
- All items are eagerly activated on viewport. See comment from @hartez below, it appears with a significantly larger dataset not all items are initially loaded. **However, the behaviour on UWP differs from iOS and Android.**
- Templated items are never finalized, possible memory leak?
- **Incorrect - Recycling of item templates never occurs.**

_Behavior on iOS_
![Behavior on iOS](https://user-images.githubusercontent.com/5580462/71587007-1918f000-2aea-11ea-88a7-54438ea90433.gif)
- **Only item views in viewport** are activated on load.
- **Correct - Recycling of item templates occurs during scrolling up and down.**

### Expected Behavior
View activation and deactivation during recycling occurs and is logged to the console.

### Actual Behavior
View activation occurs, but views are _never_ recycled.

### Basic Information

- Version with issue: 4.4.0 (vLatest)
- Last known good version: N/A
- IDE: Microsoft Visual Studio 2019 Enterprise
- Platform Target Frameworks: 
  - UWP:  Windows 10 Build 1903

### Reproduction Link
Created a sample based on the CollectionView code samples found [here](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-collectionviewdemos/).
[ViewRecyclingSample.zip](https://github.com/xamarin/Xamarin.Forms/files/4010072/ViewRecyclingSample.zip)

**Comment by MitchBomcanhao** [comment]
out of curiosity  - doesn't the ListView do the exact same thing?
Maybe there's a similar implementation/limitation with the CollectionView.

**Comment by hartez** [comment]
> All item views are activated on load.

On this count you're mistaken - you're just not using a large enough dataset. To see what I mean, after the last `source.Add()` call in your MonkeyViewModel.cs, add this:

```
for (int n = 0; n < 200; n++) 
{
	source.Add(new Monkey() 
	{
		Name = $"Monkey{n}", 
		Location = "The mean streets of monkey town", 
		Details = "Not a real monkey", 
		ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Gelada-Pavian.jpg/320px-Gelada-Pavian.jpg"
	});
}
```

You'll see that all 200 of those new monkeys are not loaded initially; as you scroll, you'll see the bindings for them.

**Comment by hartez** [comment]
> Recycling never occurs.

On this, however, you are (sort of) right. Scrolling up and down, the Forms template items don't seem to be getting re-used; new ones are being created as needed. 

The underlying ListView _is_ recycling the item containers, but it's not recycling the contents at all. So this could definitely be more efficient; there's no need to re-create these templates every single time. Also, the templated items don't appear to be getting finalized, which suggests we've got a memory leak here.

**Comment by velocitysystems** [comment]
Thanks @hartez, I have updated the details of the ticket to reflect your comments.

**Comment by EmilAlipiev** [comment]
was that fixed in 4.7? or planned in next release? 
 I have just tested using 4.7 and collectionView with 350 items each has 2 pictures using ffimageloading.
Memory is keep increasing on scrolling down and up. It seems that recycling doesnt work at all. once. When I click the back button the page and pop the page, memory remains the same. Obviously a leak.
Exact the same Datatemplate, Just replaced with Syncfusion SfListview and Recycling works perfectly fine. Memory is not increasing dramatically on scrolling up down. When i pop the page, memory is restored back to the starting point. So yes it is still the case with 4.6 and 4.7.

So we have 2 issues here
1) recycling doesnt work
2) memory is not released on popping the page. Memory leak

**Comment by hartez** [comment]
> was that fixed in 4.7? or planned in next release?

@EmilAlipiev are you asking about PR #11043? That was merged a couple of days ago, should be in 4.8.

**Comment by EmilAlipiev** [comment]
@hartez later I found out that i have more dramatic issue with using SwipeView 
as I created a new issue https://github.com/xamarin/Xamarin.Forms/issues/11253

**Comment by velocitysystems** [comment]
Look forward to testing this!
