### ISSUE TITLE
[Bug] [UWP] Dynamic Item Sizing doesn't work in CollectionView on UWP

### ISSUE THREAD

**Issue by BurkusCat** [xamarin/Xamarin.Forms#9056]
### Description
On UWP, the CollectionView's items do not resize to content changing size. Items remain a fixed height whereas on Android items will shrink and expand to fit the content. https://gist.github.com/hartez/7d0edd4182dbc7de65cebc6c67f72e14

### Steps to Reproduce

1. Create a CollectionView, populate with multiple items, and have the data template have multiple rows of data
2. Hide one row of data by default
3. Dynamically toggle that row on and off using something like a button

### Expected Behavior
The item will expand/contract to show/hide the row.

### Actual Behavior
The row pushes/covers other content or doesn't show because the item remains a fixed height on UWP.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: N/A
- IDE: Visual Studio 2019 16.3.6
- Platform Target Frameworks:
  - iOS: N/A
  - Android: N/A
  - UWP: 16299
- Android Support Library Version: N/A
- Nuget Packages: N/A
- Affected Devices: N/A

### Screenshots
Genre can be toggled to show on the Android version but not the UWP version.
![uwp-not-resizing](https://user-images.githubusercontent.com/7528322/71634651-b91f6800-2c15-11ea-991c-6e6064e45fac.PNG)
![android-resizing](https://user-images.githubusercontent.com/7528322/71634652-b91f6800-2c15-11ea-949c-0da931a59a50.png)

### Reproduction Link
[DynamicItemSizingUWP.zip](https://github.com/xamarin/Xamarin.Forms/files/4013536/DynamicItemSizingUWP.zip)

**Comment by YZahringer** [comment]
Any news on that? A simple `Label` that changes text at runtime is not usable with `CollectionView` on `UWP`.

For the moment the workaround I found is to remove the item from the `Collection` and re-insert it to force redraw of element.

**Comment by DevEddy** [comment]
Same issue here...

**Comment by BurkusCat** [comment]
I think this issue can be closed. I updated my reproduction project to 4.7.0.1260 and the issue is fixed,

**Comment by YZahringer** [comment]
I confirm in XF 4.8, `CollectionView` item resize correctly on content visibility and size change 🎉
