### ISSUE TITLE
[Bug] RTL does not support Collection View on IOS 

### ISSUE THREAD

**Issue by amr-moomen** [xamarin/Xamarin.Forms#9060]
### Description
Collection View does not support RTL on IOS but work fine on android
### Steps to Reproduce

1. Create collection view 
2. change RTL of page to RightToLeft
3. observe the result

### Expected Behavior
IOS support RTL for collection view like android 
### Actual Behavior
IOS does not  support RTL for collection view 
### Basic Information

- Version with issue: all versions of IOS
- Last known good version: None
- IDE: Visual Studio 2019 Version 16.4.1
- Platform Target Frameworks: 
  - iOS:  all versions
  - Android: 9 
- Nuget Packages: Xamarin.Forms version 4.4.0.991265
- Affected Devices: iPhone 6 up to iPhone 11 pro.

### Screenshots

![iosRTL](https://user-images.githubusercontent.com/56504816/71658812-0999e100-2d4e-11ea-8103-11de9a19a5ea.gif)
![androidRTl](https://user-images.githubusercontent.com/56504816/71658817-10285880-2d4e-11ea-9f5e-447d9b7b16e1.gif)

### Reproduction Link
https://github.com/amr-moomen/RTLCollectionView

**Comment by umeshkamble** [comment]
Used Custom renderer to fix RTL

`[assembly: ExportRenderer(typeof(CollectionView), typeof(AMCollectionView))]
namespace rtlcollectionview.iOS
{
    public class AMCollectionView : CollectionViewRenderer
    {
        public AMCollectionView()
        {
        }

        protected override void OnElementChanged(ElementChangedEventArgs<GroupableItemsView> e)
        {
            base.OnElementChanged(e);
            if (Control == null)
                return;

            if (Control != null)
            {
                NSArray views = Control.ValueForKey(new NSString("_subviewCache")) as NSMutableArray;
                UICollectionView collectionView = views.GetItem<UICollectionView>(0);
                var indexPath = NSIndexPath.FromRowSection(1, 1);

                var lang = App.Current.Properties["Lang"];
                if (lang.Equals("ar"))
                {
                    collectionView.SemanticContentAttribute = UISemanticContentAttribute.ForceRightToLeft;
                }
                else
                {
                    collectionView.SemanticContentAttribute = UISemanticContentAttribute.ForceLeftToRight;
                }
                collectionView.ScrollToItem(indexPath, UICollectionViewScrollPosition.Left, false);
            }
        }
    }`
[RTLCollectionView-master-Solution .zip](https://github.com/xamarin/Xamarin.Forms/files/4728039/RTLCollectionView-master-Solution.zip)

**Comment by samhouts** [comment]
closed by #10593
