### ISSUE TITLE
[Bug] NSInternalInconsistencyException thrown in grouped CollectionView on iOS 10

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#9065]
### Description
An `NSInternalInconsistencyException` is thrown with a grouped `CollectionView` on iOS 10.
This may possibly be related to #7393.

### Steps to Reproduce
1. Open the attached sample project on an IOS 10 device.
2. The app will crash.

### Expected Behavior
The app does no crash on iOS 11 and above.
_Note: Behavior is untested on iOS9._

### Actual Behavior
The app crashes with the following exception:

`Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: layout attributes for supplementary item at index path (<NSIndexPath: 0x167248f0> {length = 2, path = 0 - 0}) changed from <UICollectionViewLayoutAttributes: 0x17825740> index path: (<NSIndexPath: 0x17825660> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 0 0);  to <UICollectionViewLayoutAttributes: 0x16724870> index path: (<NSIndexPath: 0x167248f0> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (0 0; 720 19.5); zIndex = 10;  without invalidating the layout`

### Basic Information
- Version with issue: 4.4.0
- Last known good version: N/A
- IDE: Microsoft Visual Studio 2019 Enterprise
- Platform Target Frameworks: 
  - iOS: 13.6.0.12
- Affected Devices: iPad iOS 10.3.3

### Reproduction Link
[CollectionViewCrashIOS10.zip](https://github.com/xamarin/Xamarin.Forms/files/4016595/CollectionViewCrashIOS10.zip)

**Comment by apwillies** [comment]
Trying to keep our iOS 10 clients alive... Thanks!

**Comment by hinterlandsupplyco** [comment]
Any update on this?

**Comment by velocitysystems** [comment]
@hartez @samhouts We’re currently blocked due to this bug, as grouped collection views are broken for iOS 10 users. Do you possibly have an ETA for this fix?

**Comment by velocitysystems** [comment]
@samhouts @hartez I can confirm this is still broken in the latest `master` and `4.4.0`/`4.5.0` branches. I tested on the iOS 10.3 simulator and the same crash occurred.

**Comment by velocitysystems** [comment]
Hi @hartez, I was just wondering if the XF team had any update on this? We're not really in a position to drop support for our iOS 10 users yet. Are there any plans to work on this any time soon? Thanks!

**Comment by velocitysystems** [comment]
Hi @samhouts. Just following up on this issue - If the XF team do not plan to resolve this issue, is iOS 10 effectively unsupported by XF going forward? Just keen to understand the direction of the team on this one as we still have a considerable iOS 10 user base. Thanks!

**Comment by samhouts** [comment]
We're not planning to drop support for iOS10 just yet. 

This is on the backlog. I don't currently have an estimate of when we may begin work on this item, but it is high priority. Thank you for your patience!

**Comment by velocitysystems** [comment]
@samhouts Thank you very much. Great to see some of the other iOS 10 issues getting traction in the current sprint. We're eagerly awaiting this fix!

**Comment by hartez** [comment]
This is fixed in 4.7 pre4.

**Comment by velocitysystems** [comment]
Fantastic, thanks @hartez - we can confirm this is fixed in our codebase upgrading to 4.7 pre4.
Great work!

**Comment by libin85** [comment]
Still happening on the latest stable release 4.7.0.1179

**Comment by samhouts** [comment]
@libin85 Can you please open a new issue? Thanks!
