### ISSUE TITLE
[Enhancement] CarouselView does not support pages of content

### ISSUE THREAD

**Issue by luismts** [xamarin/Xamarin.Forms#9069]
## Summary
Like the Xamarin.Forms [CarouselPage](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page#populate-a-carouselpage-with-a-page-collection), CarouselView needs that developers can add pages of content for specific items. 

## API Changes

In order to facilitate the new CarouselView property, a content property is added to the CarouselView class. The following XAML code example shows a CarouselView that displays three CarouselView instances: 

`
<**CarouselView**>

    <ContentPage>
        <StackLayout>
            <Label Text="Red" ... />
            <BoxView Color="Red" ... />
        </StackLayout
    </ContentPage>

    <ContentPage>
        ...
    </ContentPage>

    <ContentPage>
        ...
    </ContentPage>

</**CarouselView**>
`

This is done by a collection of child ContentPage (or other views) instances.

## Intended Use Case
Showing specific items in a carousel view allow developers to add different views for specific functionalities like an Onboarding process with some text and images, and at the end a different view with a button to start the app and links of privacy policy or agreements.

**Comment by VladislavAntonyuk** [comment]
Use ContentView instead of ContentPage

**Comment by Estevete** [comment]
How can we use ContentView instead of ContentPage if CarouselView does not support direct content @VladislavAntonyuk ?
```
    <CarouselView>
        <ContentView>
            <!-- My view -->
        </ContentView>
    </CarouselView>
```
With this code, error shows up:
- XLS0502: The type 'CarouselView' does not support direct content.

> Use ContentView instead of ContentPage

**Comment by VladislavAntonyuk** [comment]
```
<CarouselView>
			<CarouselView.ItemsSource>
				<x:Array Type="{x:Type ContentView}">
					<View1 />
					<View2 />
					<View3 />
				</x:Array>
			</CarouselView.ItemsSource>
			<CarouselView.ItemTemplate>
				<DataTemplate>
					<ContentView Content="{Binding .}" />
				</DataTemplate>
			</CarouselView.ItemTemplate>
		</CarouselView>

**Comment by Estevete** [comment]
Doing it your way, the next code only shows first element of the array. (Blue color, no possibility to swipe)
```
    <CarouselView>
        <CarouselView.ItemsSource>
            <x:Array Type="{x:Type ContentView}">
                <ContentView>
                    <StackLayout BackgroundColor="Blue" />
                </ContentView>
                <ContentView>
                    <StackLayout BackgroundColor="Red" />
                </ContentView>
            </x:Array>
        </CarouselView.ItemsSource>
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <ContentView Content="{Binding .}" />
            </DataTemplate>
        </CarouselView.ItemTemplate>
    </CarouselView>
```

**Comment by luismts** [comment]
> Doing it your way, the next code only shows first element of the array. (Blue color, no possibility to swipe)
> 
> ```
>     <CarouselView>
>         <CarouselView.ItemsSource>
>             <x:Array Type="{x:Type ContentView}">
>                 <ContentView>
>                     <StackLayout BackgroundColor="Blue" />
>                 </ContentView>
>                 <ContentView>
>                     <StackLayout BackgroundColor="Red" />
>                 </ContentView>
>             </x:Array>
>         </CarouselView.ItemsSource>
>         <CarouselView.ItemTemplate>
>             <DataTemplate>
>                 <ContentView Content="{Binding .}" />
>             </DataTemplate>
>         </CarouselView.ItemTemplate>
>     </CarouselView>
> ```
> 
> > UWP CarouselView issue. Working for iOS 👍

It's working on Android too 👍

**Comment by danjrauch** [comment]
Using the solution given by @VladislavAntonyuk, how can I pass the parent page's viewmodel to each of the views in the carousel?

**Comment by CarLoOSX** [comment]
working like a charm

**Comment by VladislavAntonyuk** [comment]
@danjrauch in your CodeBehind:
```
 foreach (ContentView view in NameOfCarouselView.ItemsSource)
            {
                view.BindingContext = BindingContext;
            }
```

**Comment by rmarinho** [comment]
We have a CarouselPage for that. 

Thanks

**Comment by fkbeys** [comment]
> ```
> <CarouselView>
> 			<CarouselView.ItemsSource>
> 				<x:Array Type="{x:Type ContentView}">
> 					<View1 />
> 					<View2 />
> 					<View3 />
> 				</x:Array>
> 			</CarouselView.ItemsSource>
> 			<CarouselView.ItemTemplate>
> 				<DataTemplate>
> 					<ContentView Content="{Binding .}" />
> 				</DataTemplate>
> 			</CarouselView.ItemTemplate>
> 		</CarouselView>
> ```

it works fine, but if i add a listview inside the view, it doesnt work. 
Xaml shows error =Value can not be null

**Comment by shadowfoxish** [comment]
For anyone who discovers this, you need to add Loop="False" to the CarouselView element to avoid the "Specified child already has a parent" error.
