### ISSUE TITLE
(Custom Picker) Control.Gravity = GravityFlags.Center adds an underline/cursor briefly [Bug] 

### ISSUE THREAD

**Issue by stavroaudi** [xamarin/Xamarin.Forms#9071]
### Description
There is no option to add HorizontalTextAlignment to a picker, so I added Control.Gravity = GravityFlags.Center to my picker's custom renderer. When I open the page containing the picker, a small underline appears in the middle of my picker for a second and then disappears. This didn't exist until I updated to XF 4.x 

### Steps to Reproduce

1. Add a custom picker to a new page (page B)
2. In the custom renderer, add:
```
 protected override void OnElementChanged(ElementChangedEventArgs<Picker> e)
        {
            base.OnElementChanged(e);

            if (Control != null)
            {
                Control.Gravity = GravityFlags.Center;
                GradientDrawable gd = new GradientDrawable();
                gd.SetStroke(0, Android.Graphics.Color.Transparent);
                Control.SetBackground(gd);
                Typeface font = Typeface.CreateFromAsset(Resources.Assets, "OpenSans-Regular.ttf");
                Control.SetTypeface(font, TypefaceStyle.Normal);
                Control.SetTextSize(Android.Util.ComplexUnitType.Sp, 13f);
            }
        }
```
3. Navigate from page A to page B and immediately see the picker. 

### Expected Behavior
Picker text is centered without any styles/underlines/cursors

### Actual Behavior
Picker text is centered but with an underline that appears very briefly before disappearing

### Basic Information

- Version with issue:
- Last known good version: 3.x
- IDE: Visual Studio Professional 2019 - Windows
- Platform Target Frameworks: 
  - Android: 9.0
- Affected Devices: Using physical Samsung Galaxy S8. 

### Screenshots

![qzhr5oaw6uge](https://user-images.githubusercontent.com/31539911/71718830-be9acf00-2e1c-11ea-995d-700fe3ec4925.jpeg)

**Comment by samhouts** [comment]
@stavroaudi  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by stavroaudi** [comment]
@samhouts will do so on Monday if that’s okay! :)

**Comment by samhouts** [comment]
@stavroaudi Absolutely! Thanks!

**Comment by stavroaudi** [comment]
Can I send my project to you privately? I cannot seem to reproduce the issue in a new project unfortunately.

**Comment by stavroaudi** [comment]
Found the culprit, and it doesn't make sense to me. I'm enclosing my content inside a ScrollView. The picker has the underline when the page appears. 

However, when I change ScrollView to StackLayout, the picker acts normally, without any underline!!

**Comment by samhouts** [comment]
@stavroaudi Does this reproduce in your new project? Are you able to attach that here? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by MiloszPawlowski** [comment]
I had the same bug. Also after change scrollview to stacklayout underline was not visible. There must be some problem with control sizing during rendering. Visible underline is a horizontal scrollbar.
Set Control.HorizontalScrollBarEnabled = false; fix the problem.

**Comment by FatmaGalal** [comment]
@MiloszPawlowski  both solutions doesn't work for me :(
