### ISSUE TITLE
Xamarin C# binding double nested collection to Switch IsToggledProperty in code

### ISSUE THREAD

**Issue by Sobek0** [xamarin/Xamarin.Forms#9074]
I want to bind Switch.IsToggledProperty to View Model's double nested collection property using option BindingMode.TwoWay. In one way binding from control to View Model it works well, but when I update the property in View Model control doesn't change value. View Model implements INotifyPropertyChanged.

Here is some most important code:

View Model's property(tried with 2 arrays, but still not works):

```
private Dictionary<int, Dictionary<string, UniversalSwitchViewModel>> _categoriesList;

    public Dictionary<int, Dictionary<string, UniversalSwitchViewModel>> CategoriesList
    {
        get
        {
            return _categoriesList;
        }
        set
        {
            SetProperty(ref _categoriesList, value);
        }
    }
```
    
Switch control which I want to bind:

```
var checkbox = new Switch { VerticalOptions = LayoutOptions.Center, HorizontalOptions = LayoutOptions.Center };
//it works well only from View to View Model's property            
checkbox.SetBinding(Switch.IsToggledProperty, $"{nameof(_pageViewModel.CategoriesList)}[{regionId}].Value[{categoryNameOf}].{nameof(UniversalSwitchViewModel.Value)}", BindingMode.TwoWay);
```

Example of change of data from code(View Model):

```
public void SetCategoriesOption(Dictionary<string, int> categories, int regionId)
    {
        foreach (var item in categories)
        {
            CategoriesList[regionId][item.Key].Value = true;
        }

        CategoriesList = CategoriesList;
        //this.OnPropertyChanged(nameof(CategoriesList)); to be 100% sure I tried to run OnPropertyChanged event manually, but ofc it doesn't change anything
    }
```

Similar example which works perfect:

```
private Dictionary<string, UniversalPickerViewModel> _selectedEnumsSettings;
    public Dictionary<string, UniversalPickerViewModel> SelectedEnumSettings
    {
        get
        {
            return _selectedEnumsSettings;
        }
        set
        {
            SetProperty(ref _selectedEnumsSettings, value);
        }
    }

checkbox.SetBinding(Switch.IsToggledProperty, $"{nameof(_pageViewModel.SelectedEnumSettings)}[{enumSettingKey}].{nameof(UniversalSwitchViewModel.Value)}", BindingMode.TwoWay);
edit: forgot about UniversalSwitchViewModel

public class UniversalSwitchViewModel
{
    public long Id { get; set; }
    public bool Value { get; set; }
}
```

To better reproduce: Here is How it CategoriesList works. CategoriesList is dictionary of dictionary of UniversalSwitchViewModel where first key stores id of region(I have multiple regions with multiple switch). CategoriesList[regionId] (example: CategoriesList[0]) provides us List of switches ViewModels where key is nameOf of each category downloaded from server(don't store in this place DisplayName). CategoriesList[regionId][categoryNameOf] (Example: CategoriesList[0][discount]) return UniversalSwitchViewModel which store switch value(bool) and id to update data on server and save settings on device.

Summarizing in this part of code I'm binding each category downloaded from server(or settings) to its view model in property where CategoriesList is a repository of switches's view models. regionId is current selected Region Id from picker, you can assume it's equal 0 and CategoriesList has dictionary CategoriesList[0]. categoryNameOf is category.NameOf where category is item from server's settings, you can assume if you bind CategoriesList[0][xyz] there is CategoriesList contains CategoriesList[0][xyz] which return you sample UniversalSwitchViewModel with Id = 0(can be any int) and Value = true(it's simpler to check is it works).

Last example: you can bind:

```
checkbox.SetBinding(Switch.IsToggledProperty, "CategoriesList[0].Value[xyz].Value", BindingMode.TwoWay);
```

and it works only as One Way Bidnding from View to View Model, so I assumed binding expression is good.

I will be glad for any suggestions.

edit: link with sample issue: https://github.com/Sobek0/BindingBugExampleXamarinForms

**Comment by PureWeen** [comment]
@Sobek0 you can't really bind to expressions like that 

- No where in your sample are you setting the bindingcontext of the page to your viewmodel
- I'd recommend taking a look at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts and then use that to create your checkboxes
