### ISSUE TITLE
[Bug] Using binding with converter and source doesn't work inside the DataTemplate

### ISSUE THREAD

**Issue by ivanicin** [xamarin/Xamarin.Forms#9077]
### Description
Using `Binding `with `Converter `and `Source `doesn't work inside the `DataTemplate`

### Steps to Reproduce

1. This is the code needed to reproduce the issue:
`<Label Text="{Binding BindingContext.MasterItem.Title, Source={x:Reference page}, Converter={StaticResource StringToUpperConverter}}"/>`

The `ContentPage` should have the `x:Name="page"`

### Expected Behavior
This should work

### Actual Behavior
This works without the converter, and when the converter is added its method is properly called and the proper value is returned, but nothing appears on the screen

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version:
- IDE: Microsoft Visual Studio Community 2019 Version 16.4.2
- Platform Target Frameworks: 
  - iOS:  
  - Android: 10.1.1.0
  - UWP:   
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@ivanicin  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ivanicin** [comment]
[BindingProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/4025982/BindingProblem.zip)

**Comment by samhouts** [comment]
@ivanicin It does work, but the `parameter` doesn't get passed through. If you stop checking whether the `parameter` is null, your converter will work. Thanks!
