### ISSUE TITLE
[Bug] Aspect  with FontImage not working on  ImageButton in iOS

### ISSUE THREAD

**Issue by jennablackwell** [xamarin/Xamarin.Forms#9078]
### Steps to Reproduce

1. Create an image button 
2. Set ImageButton.Source with FontImageSource inside (such as from MaterialDesignIcons)
3. Set Aspect to AspectFit

Example:
`  <ImageButton Aspect="AspectFit"  HorizontalOptions="End"  >
                                    <ImageButton.Source>
                                        <FontImageSource
                                                        FontFamily="{DynamicResource MaterialFontFamily}"
                                                        Glyph="{x:Static utils:IconFont.DotsHorizontal}"
                                                        Size="30"
                                                        Color="White" />
                                    </ImageButton.Source>
                                </ImageButton>`

### Expected Behavior
Font icon displays proper aspect

### Actual Behavior
icon is distorted on iOS.  Looks fine on Android.

### Basic Information

- Version with issue: Xamarin Forms 4.4
- Last known good version:  Maybe 4.3 ?  Not sure exactly but this started recently
- IDE: VS 2019
- Platform Target Frameworks: 
  - iOS:  Latest
  - Android: 10
  - UWP:   N/A
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iphone 6s

**Comment by rmarinho** [comment]
Seems to be a issue only with FontIcon

**Comment by samhouts** [comment]
probably duplicate or related to #9054

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9054
