### ISSUE TITLE
[Bug] Carousel items not shown on iOS (only after scrolling)

### ISSUE THREAD

**Issue by jtorvald** [xamarin/Xamarin.Forms#9080]
### Description
The first items in the carousel are not getting showed until you have enough items in the carousel and scrolled to the right and back. Demo solution attached.

Related to: https://github.com/xamarin/Xamarin.Forms/issues/8225

### Steps to Reproduce

1. Open example project and scroll to the carouselview in the about page.
2. Once scrolled to the right items on the left get visibile

### Expected Behavior

All items should be visible.

### Actual Behavior

First items in carousel view are not visible.

### Basic Information

- Version with issue: 4.4.0.991265

Visual Studio Community 2019 for Mac
Version 8.3.11 (build 1)
Installation UUID: c733a652-0961-4439-9bc1-20f83fd20d2a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

Mono Framework MDK
Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

NuGet
Version: 5.3.0.6192

.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.0.101/Sdks
SDK Versions:
	3.0.101
	3.0.100
	3.0.100-rc1-014190
	2.2.402
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.4
	2.0.0
	1.0.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.1
	3.0.0
	3.0.0-rc1-19456-20
	2.2.7
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.0.5
	2.0.0
	1.1.2
	1.0.5

Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode 11.3 (15712)
Build 11C29

Xamarin.Mac
Version: 6.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:07-0400

Xamarin.iOS
Version: 13.6.0.12 (Visual Studio Community)
Hash: e3c2b406d
Branch: xcode11.2
Build date: 2019-11-01 00:12:08-0400

Xamarin Designer
Version: 16.3.0.256
Hash: 8a223bfd7
Branch: remotes/origin/d16-3
Build date: 2019-11-01 21:02:02 UTC

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 803110001
Git revision: 6ee6ad2ec46ae5a08a1999ee4c815ac656a35b91
Build date: 2019-12-05 16:09:27+00
Build branch: release-8.3
Xamarin extensions: 56bd70ef2e327f71c615cfc29a47fd50685fadcb

Operating System
Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

### Screenshots
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-03 at 17 50 35](https://user-images.githubusercontent.com/1808131/71736613-caed4f00-2e51-11ea-84e6-a5573768d46f.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-03 at 17 50 41](https://user-images.githubusercontent.com/1808131/71736611-caed4f00-2e51-11ea-8f55-e3d35f91f654.png)

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-03 at 17 50 45](https://user-images.githubusercontent.com/1808131/71736610-ca54b880-2e51-11ea-9620-01e82c70423b.png)
![Simulator Screen Shot - iPhone 11 Pro - 2020-01-03 at 17 50 49](https://user-images.githubusercontent.com/1808131/71736609-ca54b880-2e51-11ea-9f60-179ab3c59f04.png)

![Simulator Screen Shot - iPhone 11 Pro - 2020-01-03 at 17 50 56](https://user-images.githubusercontent.com/1808131/71736608-ca54b880-2e51-11ea-8c5d-1e12d6897e45.png)

### Reproduction Link
[CarouselBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4020002/CarouselBug.zip)

**Comment by samhouts** [comment]
similar to #6940, #8956

**Comment by hartez** [comment]
This appears to be a ContentPresenter issue.
