### ISSUE TITLE
Proper support for SwipeView in ListView with Tap Command

### ISSUE THREAD

**Issue by dczaretsky** [xamarin/Xamarin.Forms#9089]
I have a ListView with each cell containing a SwipeView. In order to support a Tap command on each cell to open the item, I've added a GestureRecognizer, which seems to work. However, I only want the tap to open the item when the SwipeView's context menu is closed. When the context menu is opened, a tap should just close the context menu.  

Seemingly, the way to do this would be to have a boolean IsOpened that I can check in the OnTapped event, but SwipeView does not have support for this. I've tried to extend the SwipeView using the provided SwipeEnded event which is fired when the context menu is opened, but the CloseRequested event is only triggered when the Close() function is programmatically called, so there's no way to know when the context has been closed.

Alternatively, I would look for the Context view's offset or something that might show that it's open, but I can't seem to determine which parameters to utilize. 

I'm not sure if this is a bug or intended to work this way, but CloseRequested should fire when the context menu is closed programmatically or automatically. Further, having some boolean such as IsOpen to determine if the context menu is opened/closed would be helpful.

```xml
<ListView
    ItemsSource="{Binding Items}"
    SelectionMode="None"
    CachingStrategy="RecycleElement"
    RowHeight="110"
    HeightRequest="1000"
    BackgroundColor="White"
    IsPullToRefreshEnabled="True"
    Refreshing="OnRefresh">
    <ListView.ItemTemplate>
        <DataTemplate>
            <ViewCell>
                <SwipeView>                    
                    <SwipeView.GestureRecognizers>
                        <TapGestureRecognizer
                            Tapped="OnTapped"
                            NumberOfTapsRequired="1" />
                    </SwipeView.GestureRecognizers>                    
                    <SwipeView.RightItems>
                        <SwipeItems>
                            <SwipeItem
                                Text="Edit"
                                IconImageSource="edit_icon.png"
                                BackgroundColor="Green"
                                Invoked="OnEdit" />
                            <SwipeItem
                                Text="Delete"
                                IconImageSource="delete_icon.png"
                                BackgroundColor="Red"
                                Invoked="OnDelete" />
                        </SwipeItems>
                    </SwipeView.RightItems>
                    <SwipeView.Content>
                        :
                    </SwipeView.Content>
                </SwipeView>
            </ViewCell>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```

**Comment by samhouts** [comment]
@dczaretsky What platform are you experiencing this issue on?  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by dczaretsky** [comment]
I see it happening on both iOS and Android.  I was able to get around this partially by extending the SwipeView class and setting an open flag on the swipe start and swipe end events.

However, the other issue I'm facing is that any scroll movement in a ListView seems to trigger the context menu to close automatically, which makes the swipe UI very problematic. Is there any way to disable the scrolling when the context menu is open, or otherwise disable the closing of the context menu when scrolling occurs?

```
    public class SwipeViewExt : SwipeView
    {
        public bool IsOpened { get; set; }

        public SwipeViewExt()
        {
            this.CloseRequested += OnCloseRequested;
            this.SwipeEnded += OnSwipeEnded;
            this.SwipeStarted += OnSwipeStarted;
            this.SwipeChanging += OnSwipeChanging;
        }
        
        public EventHandler TappedHandler;
        public event EventHandler Tapped
        {
            add { TappedHandler += value; }
            remove { TappedHandler -= value; }
        }
        
        private async void OnCloseRequested(object sender, EventArgs e)
        {
            IsOpened = false;
        }

        private async void OnSwipeEnded(object sender, SwipeEndedEventArgs e)
        {
            IsOpened = true;
        }

        private async void OnSwipeStarted(object sender, SwipeStartedEventArgs e)
        {
        }

        private async void OnSwipeChanging(object sender, SwipeChangingEventArgs e)
        {
        }
    }
```

**Comment by samhouts** [comment]
It might be a good idea to add Closing/Opening events. I'll mark this as an enhancement.

We did discuss adding the ability to disable ListView scrolling in https://github.com/xamarin/Xamarin.Forms/issues/2680, but it is not yet implemented.

**Comment by PouryaNoufallah96** [comment]
SwipeView_OnCloseRequested is not working :( i want to set is open to false in close request but the event is not working . what should i do on auto close swipe ? is open value wont back to false  and my tap should  called multiple times

**Comment by PouryaNoufallah96** [comment]
> I see it happening on both iOS and Android. I was able to get around this partially by extending the SwipeView class and setting an open flag on the swipe start and swipe end events.
> 
> ```
>     public class SwipeViewExt : SwipeView
>     {
>         public bool IsOpened { get; set; }
> 
>         public SwipeViewExt()
>         {
>             this.CloseRequested += OnCloseRequested;
>             this.SwipeEnded += OnSwipeEnded;
>             this.SwipeStarted += OnSwipeStarted;
>             this.SwipeChanging += OnSwipeChanging;
>         }
>         
>         public EventHandler TappedHandler;
>         public event EventHandler Tapped
>         {
>             add { TappedHandler += value; }
>             remove { TappedHandler -= value; }
>         }
>         
>         private async void OnCloseRequested(object sender, EventArgs e)
>         {
>             IsOpened = false;
>         }
> 
>         private async void OnSwipeEnded(object sender, SwipeEndedEventArgs e)
>         {
>             IsOpened = true;
>         }
> 
>         private async void OnSwipeStarted(object sender, SwipeStartedEventArgs e)
>         {
>         }
> 
>         private async void OnSwipeChanging(object sender, SwipeChangingEventArgs e)
>         {
>         }
>     }
> ```
> 
> Then, I can add a check in the OnTapped event to see if the context menu was opened.
> 
> ```
>        private async void OnTapped(object sender, EventArgs e)
>         {
>             SwipeViewExt sv = sender as SwipeViewExt;
>             if (sv == null) return;
> 
>             if (sv.IsOpened)
>             {
>                 return;
>             }
>             :
>         }
> ```
> 
> However, the other issue I'm facing is that any scroll movement in a ListView seems to trigger the context menu to close automatically, which makes the swipe UI very problematic. Is there any way to disable the scrolling when the context menu is open, or otherwise disable the closing of the context menu when scrolling occurs?



> I see it happening on both iOS and Android. I was able to get around this partially by extending the SwipeView class and setting an open flag on the swipe start and swipe end events.
> 
> ```
>     public class SwipeViewExt : SwipeView
>     {
>         public bool IsOpened { get; set; }
> 
>         public SwipeViewExt()
>         {
>             this.CloseRequested += OnCloseRequested;
>             this.SwipeEnded += OnSwipeEnded;
>             this.SwipeStarted += OnSwipeStarted;
>             this.SwipeChanging += OnSwipeChanging;
>         }
>         
>         public EventHandler TappedHandler;
>         public event EventHandler Tapped
>         {
>             add { TappedHandler += value; }
>             remove { TappedHandler -= value; }
>         }
>         
>         private async void OnCloseRequested(object sender, EventArgs e)
>         {
>             IsOpened = false;
>         }
> 
>         private async void OnSwipeEnded(object sender, SwipeEndedEventArgs e)
>         {
>             IsOpened = true;
>         }
> 
>         private async void OnSwipeStarted(object sender, SwipeStartedEventArgs e)
>         {
>         }
> 
>         private async void OnSwipeChanging(object sender, SwipeChangingEventArgs e)
>         {
>         }
>     }
> ```
> 
> Then, I can add a check in the OnTapped event to see if the context menu was opened.
> 
> ```
>        private async void OnTapped(object sender, EventArgs e)
>         {
>             SwipeViewExt sv = sender as SwipeViewExt;
>             if (sv == null) return;
> 
>             if (sv.IsOpened)
>             {
>                 return;
>             }
>             :
>         }
> ```
> 
> However, the other issue I'm facing is that any scroll movement in a ListView seems to trigger the context menu to close automatically, which makes the swipe UI very problematic. Is there any way to disable the scrolling when the context menu is open, or otherwise disable the closing of the context menu when scrolling occurs?

sorry did you figure out something for this?

**Comment by dczaretsky** [comment]
I was able to  get around the issue of the menu closing automatically by disabling the scrolling entirely while swiping the menu. In my case, my SwipeViewExt was in a ListView, so there is an easy way to accomplish this.

Note that I also added when you open a menu, it should close any other open menu items. This more closely resembles the iOS behavior. I keep track of the last menu item opened in LastSwipeView, then close it (if exists) on swipe start.

Hope this helps.

```
namespace ViewModels
{
    public class SwipeViewExt : SwipeView
    {
        public static SwipeViewExt LastSwipeView { get; set; }
        public bool IsOpened { get; set; }

        public SwipeViewExt()
        {
            this.CloseRequested += OnCloseRequested;
            this.SwipeEnded += OnSwipeEnded;
            this.SwipeStarted += OnSwipeStarted;
            this.SwipeChanging += OnSwipeChanging;
        }
 
        private void OnCloseRequested(object sender, EventArgs e)
        {
            IsOpened = false;
        }

        private void OnSwipeEnded(object sender, SwipeEndedEventArgs e)
        {
            IsOpened = true;

            var p = sender as Element;
            while (p != null && !(p is ListViewExt)) p = p.Parent;

            // re-enable scrolling in the parent listview on swipe ended
            var lv = p as ListViewExt;
            if (lv == null) return;

            lv.IsScrollingEnable = true;
            LastSwipeView = this;
        }

        private void OnSwipeStarted(object sender, SwipeStartedEventArgs e)
        {
            var p = sender as Element;
            while ( p != null && !(p is ListViewExt) ) p = p.Parent;

            // disable scrolling in the parent listview on swipe start
            var lv = p as ListViewExt;
            if (lv == null) return;
            lv.IsScrollingEnable = false;

            // close any other opened menus
            if (LastSwipeView != null &&
                LastSwipeView != this &&
                LastSwipeView.IsOpened)
            {
                LastSwipeView.Close();
                LastSwipeView = null;
            }
        }

        private void OnSwipeChanging(object sender, SwipeChangingEventArgs e)
        {
        }
    }
}
```

**Comment by Kapusch** [comment]
>         private async void OnSwipeEnded(object sender, SwipeEndedEventArgs e)
>         {
>             IsOpened = true;
>         }

Hello @dczaretsky , please note that OnSwipeEnded event doesn't mean SwipeItem is Opened, it just means a Swipe gesture is "active", even to open or close a SwipeItem.
