### ISSUE TITLE
[Bug] UWP Memory Leak

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#9091]
### Description
Tracking down potential memory leaks on the UWP platform I noticed event handlers being left behind.

![image](https://user-images.githubusercontent.com/9284438/71831464-daaea280-30a0-11ea-8712-4a9f6765b0e6.png)

I looked at the code and noticed that events beind hooked up here: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L460

Are not being unhooked in dispose in the `VisualElementRenderer`

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L279

I think the fix would be 

to change this line: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L279

to:

			control.Loaded -= OnControlLoaded;
			control.GotFocus -= OnControlGotFocus;
			control.LostFocus -= OnControlLostFocus;

**Comment by PureWeen** [comment]
@JKennedy24 those events are unwired here

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L438


Which is called from here on the dispose method
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.UAP/VisualElementRenderer.cs#L284

Can you attach a repro demonstrating the leak?

**Comment by JKennedy24** [comment]
It seems my memory leak may not be caused by what I thought. I am going to go back to my code to analyze and re-open this issue if I manage to create a good sample
