### ISSUE TITLE
[Bug] Resetting MainPage fails on Android when device is asleep

### ISSUE THREAD

**Issue by mchipeta** [xamarin/Xamarin.Forms#9093]
### Description
If the code for resetting MainPage executes while an Android device is asleep, e.g.,

```Application.Current.MainPage = new SecondPage();```

in MainPage.xaml.cs in the attached samples, the new page is not shown when the device is woken up.

### Steps to Reproduce

1. Unzip and run the solution in [AndroidNavResetIssue4.1.0.555618.zip](https://github.com/xamarin/Xamarin.Forms/files/4027115/AndroidNavResetIssue4.1.0.555618.zip) or [AndroidNavResetIssue4.4.0.991265.zip](https://github.com/xamarin/Xamarin.Forms/files/4027117/AndroidNavResetIssue4.4.0.991265.zip).
2. When the countdown begins in MainPage, press the power button before it reaches 1 to put your Android device to sleep.
3. Wait for 10 seconds.
4. Press the power button to wake up your Android device.

### Expected Behavior
The app should show SecondPage. [AndroidNavResetIssue4.0.0.709238.zip](https://github.com/xamarin/Xamarin.Forms/files/4027118/AndroidNavResetIssue4.0.0.709238.zip) works as expected.
### Actual Behavior
The app still shows MainPage with the counter stuck at 1.
### Basic Information

- Version with issue: Xamarin.Forms 4.1.0.555618 or higher
- Last known good version: Xamarin.Forms 4.0.0.709238
- IDE: Visual Studio 16.4.2

- Platform Target Frameworks: 
  - iOS:  N/A
  - Android: 9 or 10
  - UWP:  N/A 
- Android Support Library Version: 
- Nuget Packages: Xamarin.Forms and it dependencies
- Affected Devices: Android

### Reproduction Link
[AndroidNavResetIssue4.1.0.555618.zip](https://github.com/xamarin/Xamarin.Forms/files/4027115/AndroidNavResetIssue4.1.0.555618.zip)

[AndroidNavResetIssue4.4.0.991265.zip](https://github.com/xamarin/Xamarin.Forms/files/4027117/AndroidNavResetIssue4.4.0.991265.zip)

[AndroidNavResetIssue4.0.0.709238.zip](https://github.com/xamarin/Xamarin.Forms/files/4027118/AndroidNavResetIssue4.0.0.709238.zip)

**Comment by PureWeen** [comment]
Regression caused by
https://github.com/xamarin/Xamarin.Forms/pull/5655


When resume happens the code needs to see if the main page was swapped out while it was asleep

@kvpt

**Comment by kvpt** [comment]
@PureWeen You mean #4707
I added a condition to completely ignore this case, this cause some race condition on resume which cause crash.
I was thinking that discard was safe, because it strange to modify a page when app is in background, but if it was used, it's a regression, perhaps it's better to queue it and wait that the app resume. A bit like you done in the PR #7316 with the dialog.
I will look at it.

**Comment by kingces95** [comment]
If you still have an issue please update this bug.
