### ISSUE TITLE
PushAsync not working after OnPageLoading (after OAuthLoginPresenter)

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9095]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/836610/pushasync-not-working-after-onpageloading-after-oa.html)._

---
I have an application that uses Google and Facebook Authentication.
It runs on UWP, iOS and Android.

On UWP, following a successful authentication, when the Main Page is re-launced (using the code below), everything on the page looks OK. but when I try to Navigate to the next page in response to a User request, nothing happens.

I am executing await Navigation.PushAsync(new Page());

I can see the new page added to the Navigation.NavigationStack.
But the page never appears. And its OnAppearing code is never executed.

This is true for both Google (which causes the OnActivated to be called, and Facebook which, for some reason, does not (but still restarts the app with the new login information showing).

protected override void OnActivated(IActivatedEventArgs args)
        {
            if (args. Kind == ActivationKind.Protocol && args is ProtocolActivatedEventArgs eventArgs)
            {
                var auth = AuthenticationState.Authenticator;
                if (auth != null)
                {
                    AuthenticationState.Authenticator.OnPageLoading(new Uri(eventArgs.Uri.AbsoluteUri));
                }

}
        }

---
#### Visual Studio Feedback System on 11/27/2019, 11:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 1/2/2020, 05:35 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.

---
#### Solomon Fried solved on 12/26/2019, 07:54 AM, 0 votes: 

<p>I tracked this issue to the fact that the control on which the button was located, was cached when the main page was enetered. For some reason, on Windows only, this caused click events to be handled by a non-visible, cached,  window when returning from a Google/Facebook login throught the OnActivated method. <br>I changed the code to always rebuild the Main page controls in the OnAppearing handler, and now the application works as expected. Still not clear why this is not an issue on IOS or Android. </p>

**Comment by samhouts** [comment]
@Redth Does this sound familiar to you?

**Comment by Redth** [comment]
@samhouts sorry, nope :(

**Comment by samhouts** [comment]
Original reporter:  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
