### ISSUE TITLE
Xamarin.Forms.Maps.Map.MapElements.Clear() seems effectless

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9096]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/855715/xamarinformsmapsmapmapelementsclear-seems-effectle.html)._

---
Xamarin.Forms 4.4.0.991265
Xamarin.Forms.Maps 4.4.0.991265
VS 16.4.1 and 16.5 Preview 1

Android project (Api 28):
In my first attempt for a Xamarin App with Maps I insert polygons into the MapElements collection on VisibleRegion changes. Before inserting new polygons I clear the MapElements collection but in the display the (old) polygons remain and are overlayed with the newly added ones. So I get memory problems after a short time.
Looks like clearing the MapElements collection (the Count changes to 0) does not remove the corresponding elemnts from the google map.

---
#### Visual Studio Feedback System on 12/13/2019, 02:30 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jcmanke** [comment]
This was fixed in #7401.

**Comment by owe-eorg** [comment]
This issue has not yet been fixed and I honestly don't know why. They still update xamarin.forms.maps but don't care for such an essential flaw.  Am I missing out on something?

**Comment by jfversluis** [comment]
@owe-eorg what isn't fixed according to you? As @jcmanke pointed out this might be fixed by the mentioned PR. Did you verify that this still doesn't work? And for what version?

**Comment by owe-eorg** [comment]
@jfversluis  I'm using a vs xamarin.forms project with the current xamarin.forms.maps nuget packet (4.5.0.657). 
`MAP_myMap.MapElements.Clear();` does not remove the Mapelements from the GUI. Only after reinitializing/ restarting the App, the MapElements are cleared from the GUI. It's mostlikely the very same issue.

**Comment by jfversluis** [comment]
I have just verified that this works in the current 4.6-pre4 package. 4.6 stable should be out in a few hours from now so keep your eye out for that.

Closing this one for now. If you find it not working in 4.6 please let me know
