### ISSUE TITLE
[Spec]  Shell/NavigationPage TitleView

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#9107]
# NavigationPage/Shell TitleView

Utilize our current LayoutOptions to indicate how you want a TitleView to layout on the screen. All work done here should be generalized so that it applies to Navigation.TitleView as well

These will have no effect as they only apply to cases where the parent is a stack layout
```
StartAndExpand
CenterAndExpand
EndAndExpand
FillAndExpand
```

Realistically users should only need to use Center and Fill

#### VerticalOptions
When used it will center the rendered view inside the given title view container so that the margin above and below the content appear equal

####  HorizontalOptions
Centered on the device screen. View will have a width equal to measured content

#### VerticalOptions
This is the current behavior. The Layout will just layout inside all available vertical space. In a perfect world if the measured height of the supplied layout exceeds the min height of the navigation bar then the navigation bar should be resized to match the height of the TitleView. If this is extremely difficult to get working we can look at doing that for a second PR.

####  HorizontalOptions
This will cause the title view to take up the entire width of the header on the device. So the titleview layout will overlap the backbutton, hamburger, etc...  We can detect this layout option and just not render toolbaritems/hamburger/etc..

#### VerticalOptions
View will measure vertically to the size of the content and will layout against the top edge of the allotted TitleView space.

####  HorizontalOptions
View will measure horizontally to the size of the content and will layout against the left edge of the allotted TitleView space. For example on iOS this will just cause the view to layout against the hamburger

#### VerticalOptions
View will measure vertically to the size of the content and will layout against the bottom edge of the allotted TitleView space.

####  HorizontalOptions
View will measure horizontally to the size of the content and will layout against the right edge of the allotted TitleView space. For example on iOS this will just cause the view to layout against the hamburger
Template level control of the entire experience.

## Additional Work to look at while implementing these changes
- Shell needs to allow the TitleView to be settable at all levels #4650
- If the measured height of the titleview exceeds the navigation bar min height than the navigationbar should resize to the measured content

## XAML Example

This will center the title vertically within the given titleview space and horizontally on the device screen
```xaml
<Shell.TitleView>
     <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
          <Label Text="Title"  />
     </StackLayout>
</Shell.TitleView>
```
***

# Difficulty :  medium

**Comment by jrahma** [comment]
The only issue I am facing is the Back Button area [Left side] which is not accessible by the TitleView as you can see in below image even with setting the a FillAndExpand StackLayout

![Screenshot_20200219_232222](https://user-images.githubusercontent.com/6236241/74867931-faf3a180-536e-11ea-8178-7163a91312f3.jpg)

When I say Left side you should also consider when the FlowDirection is RightToLeft then this area will be at the Right side.

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/9939

**Comment by jrahma** [comment]
@samhouts  Is this going to be available soon to fix the empty space in the left side?

**Comment by samhouts** [comment]
This is on the backlog. I don't currently have an estimate of when we may begin work on this item. Thank you for your patience!

**Comment by oscarjaergren** [comment]
1+ on this

**Comment by kirankumar4vr** [comment]
With Xamarin Forms 5.0.0.2012 update, I started observing that HorizontalOptions="End" or "EndAndExpand" are not working properly on iOS in the Shell title view. This looks fine on Android. Below are the screenshots of the shell title view with an image in stacklayout.
![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 30](https://user-images.githubusercontent.com/15024722/113593788-d2774700-9604-11eb-9e9f-7abc84989f69.png)
![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 25](https://user-images.githubusercontent.com/15024722/113593789-d30fdd80-9604-11eb-9580-30f1a3b1c99b.png)

Below is the Xaml
<Shell.TitleView>
        <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
            <Label Text="{Binding Title}" HorizontalOptions="Start"/>
            <Image Source="icon_feed.png" HorizontalOptions="EndAndExpand" Aspect="AspectFit" HeightRequest="40"/>
        </StackLayout>
    </Shell.TitleView>

this was working fine in Xamarin.Forms 4.0 Version. 

I tried multiple workarounds like using a grid, right margin, etc but none are working.

**Comment by gandhadsanjay** [comment]
> With Xamarin Forms 5.0.0.2012 update, I started observing that HorizontalOptions="End" or "EndAndExpand" are not working properly on iOS in the Shell title view. This looks fine on Android. Below are the screenshots of the shell title view with an image in stacklayout.
> ![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 30](https://user-images.githubusercontent.com/15024722/113594885-4403c500-9606-11eb-9474-715f9c8a7181.png)
> ![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 25](https://user-images.githubusercontent.com/15024722/113595068-81685280-9606-11eb-931c-d8b5176ca591.png)
> 
> Below is the Xaml
> 
> ```
> <Shell.TitleView>
>         <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
>             <Label Text="{Binding Title}" HorizontalOptions="Start"/>
>             <Image Source="icon_feed.png" HorizontalOptions="EndAndExpand" Aspect="AspectFit" HeightRequest="40"/>
>         </StackLayout>
>     </Shell.TitleView>
> ```
> 
> this was working fine in Xamarin.Forms 4.0 Version.
> I tried multiple workarounds like using a grid, right margin, etc but none are working.

**Comment by gandhadsanjay** [comment]
> > With Xamarin Forms 5.0.0.2012 update, I started observing that HorizontalOptions="End" or "EndAndExpand" are not working properly on iOS in the Shell title view. This looks fine on Android. Below are the screenshots of the shell title view with an image in stacklayout.
> > ![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 30](https://user-images.githubusercontent.com/15024722/113594885-4403c500-9606-11eb-9474-715f9c8a7181.png)
> > ![Simulator Screen Shot - iPhone 12 - 2021-04-05 at 11 44 25](https://user-images.githubusercontent.com/15024722/113595068-81685280-9606-11eb-931c-d8b5176ca591.png)
> > Below is the Xaml
> > ```
> > <Shell.TitleView>
> >         <StackLayout Orientation="Horizontal" HorizontalOptions="FillAndExpand">
> >             <Label Text="{Binding Title}" HorizontalOptions="Start"/>
> >             <Image Source="icon_feed.png" HorizontalOptions="EndAndExpand" Aspect="AspectFit" HeightRequest="40"/>
> >         </StackLayout>
> >     </Shell.TitleView>
> > ```
> > 
> > 
> > this was working fine in Xamarin.Forms 4.0 Version.
> > I tried multiple workarounds like using a grid, right margin, etc but none are working.

I was facing same problem, tried many things nothing worked and finally have downgrade XF to v5.0.0.1931

**Comment by shivendramca10** [comment]
Hi I am using Shell.TitleView for showing logo and Shell.SearchHandler for Searching but in Android App show Shell.SearchHandler and TitleView did not show can we set NavigationPage height that I will show Title View and Search.

**Comment by jfversluis** [comment]
Hey all, thank you for your input on this! I don't think there will be much changes in this area for Forms anymore. Keep your eye on .NET MAUI and see what is happening there. Maybe this is already better or make sure to open proposals there for things you're interested in. Thanks!
