### ISSUE TITLE
[Enhancement] [Xaml] Support binding to jagged array elements in xaml via index syntax

### ISSUE THREAD

**Issue by mzhukovs** [xamarin/Xamarin.Forms#9111]
## Summary
In WPF, let's say you have a `public int[][] NineBoxCounts { get; set; }`,
you could bind to a specific element in XAML via: `Text="{Binding NineBoxCounts[0][1]}"`

Unfortunately, in Xamarin XAML, this does not work. Only simple array binding works.

## Intended Use Case
Binding to jagged array elements

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
