### ISSUE TITLE
[Bug] ImageButton - bad tap animation on iOS after upgrading to 4.4.0.991265

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9112]
### Description
After upgrade to 4.4.0.991265, the animation is bad when tapping on ImageButton on iOS.

### Steps to Reproduce

1. Run this project
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4030831/App1.zip)

2. Click on ImageButton. The animation is nice.
3. Upgrade XF to 4.4
4. Run the project again
5. Click on ImageButton. Now the animation is bad.

### Expected Behavior
On iOS there should be nice animation when clicking on ImageButton like it was in XF 4.3

### Actual Behavior
On iOS, the animation is bad when clicking on ImageButton.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 4.3.0.991250
- IDE: Visual Studio 16.3.10
- Platform Target Frameworks: 
  - iOS:  8.0

### Screenshots

4.3.0 (nice animation)

![ios_tap_animation](https://user-images.githubusercontent.com/17653648/71898636-1bb6bd80-315a-11ea-9e0d-ec1f1ff2bf59.gif)

4.4.0 (bad animation)

![ios_tap_bad_animation](https://user-images.githubusercontent.com/17653648/71898644-1fe2db00-315a-11ea-90d7-1559186fc676.gif)

**Comment by Mikilll94** [comment]
@hartez @samhouts 
This has been broken in 4.4 and it is still not fixed in 4.4-sr4. Is is going to fixed in 4.4-sr5?

**Comment by Mikilll94** [comment]
@samhouts @jfversluis 
Please fix this 4.4-sr5

**Comment by jfversluis** [comment]
@Mikilll94 thank you for your interest in this bug! I'm not sure on the exact timeline for this, but we will be sure to get the fix to you as soon as possible. Thanks!

**Comment by Mikilll94** [comment]
@jfversluis 
So this is going to be fixed in 4.4-sr7?

**Comment by PureWeen** [comment]
@Mikilll94 is this still happening on the nightly?

**Comment by Mikilll94** [comment]
@PureWeen 
I was not checking nightly but this bug is still present in the latest stable XF 4.5.0.396

**Comment by PureWeen** [comment]
can you test nightly?

https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

**Comment by Mikilll94** [comment]
@PureWeen 
I have checked the latest nightly (4.7.0.461-nightly) and this bug is still present.

**Comment by samhouts** [comment]
closed by #10394
