### ISSUE TITLE
[Bug] Android buttons do not honor the Auto sizing

### ISSUE THREAD

**Issue by rs-memosoft** [xamarin/Xamarin.Forms#9113]
### Description

I've been seeing this problem for the last year with various version of XF but as it continues to frustrate my layouts I think it's time to open this up as an issue.

My problem is that on iOS buttons honor the Auto width and on Android they seem to ignore it. 

### Steps to Reproduce

Add one text label and 3 buttons to an XF pages as follows:

```
<Grid>
    <Grid.ColumnDefinitions>
        <ColumnDefinition x:Name="Column1" Width="*" />
        <ColumnDefinition x:Name="Column2" Width="auto" />
        <ColumnDefinition x:Name="Column3" Width="auto" />
        <ColumnDefinition x:Name="Column4" Width="auto" />
    </Grid.ColumnDefinitions>
    <Label  Grid.Column="0" Text=" " />
    <Button Grid.Column="1" Text="AB" />
    <Button Grid.Column="2" Text="ABCDEF"/>
    <Button Grid.Column="3" Text="A"/>
</Grid>
```

### Expected Behavior 

These are the iOS buttons.  There's no padding or borders but you can see they honor the width correctly.

![ibutton](https://user-images.githubusercontent.com/39233783/71900184-4162b780-3198-11ea-90a0-d7638e7c580c.png)

### Actual Behavior

These are the Android buttons.  They seem to ignore the Auto and all have the same width

![abutton](https://user-images.githubusercontent.com/39233783/71900194-46c00200-3198-11ea-9a33-fb233a8f50f3.jpeg)

### Basic Information

- Version with issue: All versions over at least the last year
- Last known good version: None

**Comment by hartez** [comment]
Reproduction - the behavior is the same on iOS and UWP; Android is the odd one out here:

[_9113 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4031383/_9113.Repro.zip)

**Comment by MitchBomcanhao** [comment]
I think that the buttons are just rendered using android's minimum button width, so they only have the same size because they don't need to be wider to accommodate the existing text. Add more text to one of them and it'll be wider than the others.

There might be some platform specific code you can use to reduce that minimum button width on android, but I an not familiar with it...

**Comment by viktorszekeress** [comment]
Tried styles.xml technnique and it worked, but I had to switch from `Android.ButtonRenderer` to `Android.AppCompat.ButtonRenderer` or `Android.FastRenderers.ButtonRenderer`.

I also tried `Control.SetMinWidth()` but didn't have any effect, even not on `Android.FastRenderers.ButtonRenderer`. Any explanation? To me it seems like that `"buttonStyle"` style always overrides the value.
