### ISSUE TITLE
[Bug] Footer is suddenly missing after updating Xamarin.Forms

### ISSUE THREAD

**Issue by SebastianKruseWago** [xamarin/Xamarin.Forms#9115]
### Description
As soon as I update Xamarin.Forms to 4.1.0.709244 or later, the Footer is no longer visible. I'm 100% sure this is not an issue of my code because it works with Xamarin.Forms 4.1.0.581479 and earlier exactly like this. 

### Steps to Reproduce

1. Add a footer to a ListView

### Expected Behavior
Footer is displayed.

### Actual Behavior
Footer is missing.

### Basic Information

- Version with issue :4.1.0.709244 and later
- Last known good version: 4.1.0.581479 and earlier

**Comment by hartez** [comment]
@SebastianKruseWago Is this happening on all platforms, or just one? How are you adding the footer to the ListView (C#, XAML)?

**Comment by Sebastian1989101** [comment]
It happens on iOS and Android as far as I can confirm (other Platforms not checked). 

In this code, the Header is working but the Footer is not after the mentioned upgrade to 4.1.0.709244 and later. Also tested with Daniel Luberda's FlowListView which is based on the Xamarin.Forms ListView control and it has the same issue if this information helps.
```
<ListView Grid.Row="1" x:Name="DataListView" SeparatorVisibility="None" HasUnevenRows="true"
                  ItemsSource="{Binding Data}" IsGroupingEnabled="False" BackgroundColor="{DynamicResource DarkBackgroundColor}"
                  ItemTemplate="{StaticResource EntryTemplate}" Header="{Binding Header}" Footer="{Binding Footer}">
    <ListView.HeaderTemplate>
        <DataTemplate>
            <Label Text="{Binding}" TextColor="{DynamicResource TextColor}" FontAttributes="Bold" Margin="10,20" HorizontalTextAlignment="Center" LineBreakMode="WordWrap" />
        </DataTemplate>
    </ListView.HeaderTemplate>
    <ListView.FooterTemplate>
        <DataTemplate>
            <Label Text="{Binding}" TextColor="{DynamicResource LightTextColor}" FontSize="Micro" Margin="{OnPlatform iOS=20 30 20 20, Default=20}" HorizontalTextAlignment="Center" LineBreakMode="WordWrap" />
        </DataTemplate>
    </ListView.FooterTemplate>
</ListView>
```

**Comment by samhouts** [comment]
[Issue9115.zip](https://github.com/xamarin/Xamarin.Forms/files/4125739/Issue9115.zip)

I'm unable to reproduce this. Can you please alter the attached project so that it demonstrates the problem? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
