### ISSUE TITLE
[Bug] Samsung phones do not honor the request to not show the bottom navigation bar

### ISSUE THREAD

**Issue by rscholey** [xamarin/Xamarin.Forms#9116]
### Description

Shell.NavBarIsVisible="false" does not work on Samsung phones with the 2019 Android OS.  

### Steps to Reproduce

1. Set Shell.NavBarIsVisible="false"

### Expected Behavior

The bottom navigation bar will be hidden like in the emulators

### Actual Behavior

The navigation bar appears.  Note that this picture doesn't show the three icons as the image was a bit bright for my camera but the icons for back etc do appear

![ZBSOo-2](https://user-images.githubusercontent.com/39233783/71913397-47659200-31b2-11ea-881d-1c505aa44427.jpg)

The phone used for this test was:

The Samsung Galaxy A70 and A70s are a series of Android phablets manufactured by Samsung Electronics as part of its fifth-generation Galaxy A series lineup. The phones come with Android 9 (Pie) with Samsung's proprietary One UI skin, 128 GB of internal storage, and a 4500 mAh battery.

**Comment by hartez** [comment]
@rscholey The image you attached is of the TabBar, not the NavBar. Are you seeing this with `Shell.TabBarIsVisible="False"`?

**Comment by rscholey** [comment]
Hello, My problem is with the white area at the bottom of the screen that has the Android back arrow, Square and vertical bars.  

When I follow your suggestion: Shell.TabBarIsVisible="False". then the area with the icons and the words Home, Dictionary, Deck etc are hidden

**Comment by rscholey** [comment]
I refer to this document:  

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/configuration

Sections:

Disable the navigation bar

This works on non Samsung phones and on the emulator.  But on Samsung phones it does not disable the navigation bar as in the picture shown in the doc.

**Comment by rscholey** [comment]
Note that there were changes made by Samsung:

https://eu.community.samsung.com/t5/Galaxy-S9-S9/Unable-to-hide-navigation-bar/td-p/901301

I believe one solution looks like this:

```
int uiOptions = (int)Window.DecorView.SystemUiVisibility;
uiOptions |= (int)SystemUiFlags.HideNavigation;
Window.DecorView.SystemUiVisibility = (StatusBarVisibility)uiOptions;
```

But this needs investigating

**Comment by gmwilhelm** [comment]
I think there i a missunderstanding. 
The NavBar is not the bar with the 3 android buttons. 
The NavBar is the bar at the top of your app with your app title, the back button, icons etc. 

So hiding the NavBar will hide the bar at the top of your app.

The TabBar contains your tabs at the bottom of your app.

Simply said: you cannot hide the android buttons.

**Comment by hartez** [comment]
@rscholey 

gmwilhelm is correct; that settting is for handling the visibility of the Forms navigation bar. It has nothing to do with the OS-level navigation on the phone. 

Forms does not provide any mechanism for hiding/showing the Android navigation bar; that's something you'd have to in your Android head project.

**Comment by samhouts** [comment]
See https://developer.android.com/training/system-ui/immersive.html for information about hiding system bars.

**Comment by EricOuellet2** [comment]
I followed rscholey solution and my App does not have the Android buttons bar.
