### ISSUE TITLE
[Bug] ImageButton's image stretching

### ISSUE THREAD

**Issue by sumeyyaarar** [xamarin/Xamarin.Forms#9119]
### Description
I have a problem with ImageButton on iOS (see attachment). Instead of fitting, image is stretching in Image Button . I think problem in the FormsButton class which is added with this commit:
d012853#diff-17042de9e1e45b58f4029bbce074127f

When I commented on this code:

`return new FormsButton();`

and compile with the the previous version code, it works as expected:

`return new UIButton(UIButtonType.System);
`
### Steps to Reproduce

1. Instantiate an Image Button
2. Set source of the Image Button

### Expected Behavior
ImageButton's image should remain fit.

### Actual Behavior
Image is stretching.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: 4.3.0.908975
- IDE: Visual Studio Mac 8.3.11
- Platform Target Frameworks:
  - iOS:  13.8
- Affected Devices: All iOS devices

### Screenshots

<table>
<tr>
<td>
<p>Expected</p>
<img src="https://user-images.githubusercontent.com/12747384/71923839-ea141580-319e-11ea-9e7f-fc853236e185.png" data-canonical-src="https://user-images.githubusercontent.com/12747384/71923839-ea141580-319e-11ea-9e7f-fc853236e185.png" width="250" height="500" />
</td>
<td>
<p>Actual</p>
<img src="https://user-images.githubusercontent.com/12747384/71923841-eaacac00-319e-11ea-8ea8-f2d8c78d123a.png" data-canonical-src="https://user-images.githubusercontent.com/12747384/71923841-eaacac00-319e-11ea-8ea8-f2d8c78d123a.png" width="250" height="500" />
</td>
</tr>
</table>

**Comment by hartez** [comment]
Seems to just ignore Aspect entirely on iOS;
[_9119 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4032410/_9119.Repro.zip)

**Comment by mdbill** [comment]
fyi, still broken in 4.0.991477

**Comment by kgouraw** [comment]
It should work like <Image ../> control, without specifying HeightRequest and WidthRequest, what it used to work till Xamarin 4.3.  Now, do we need to provide height and width?

**Comment by Sinkanakagug** [comment]
Still having a problem with this one, does anyone know if there are any plans to fix it?

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9054

@sumeyyaarar FormsButton is indeed the issue

Thank you for finding that!!

**Comment by davecalkins** [comment]
Seeing this problem in Xamarin.Forms v4.5.0.356.  Using a single row grid with 3 columns, cols 0 and 2 have a fixed size with ImageButton elements referencing square image files, col 1 (the middle) has a size "*" with a Label.  The images look fine on Android and UWP, but are stretched on iOS.

Tried the following

- aspect options in the ImageButton elements
- specifying same column and row sizes
- specifying width and height request

Can't seem to get anything to work and not stretch the images.  Found this and I think this is what I'm seeing.

**Comment by DottorPagliaccius** [comment]
same here, version is 4.4.0.991757

**Comment by eekamouse** [comment]
Posting here to mention the same and follow along. This is preventing us from upgrading to 4.5.... which we need to upgrade to eventually given that Apple will stop allowing app submissions prior to 4.5 (because of the UIWebView issue)

**Comment by munkii** [comment]
We've simply replaced our ImageButtons with a custom one

- No action in Android Renderer
- In iOS Renderer
 

```
var button = this.Control as UIButton;
button.HorizontalAlignment = UIControlContentHorizontalAlignment.Center;
button.VerticalAlignment = UIControlContentVerticalAlignment.Center;

```

Easy to apply, easy to remove when the bug is fixed and works reliably.

**Comment by kgouraw** [comment]
> We've simply replaced our ImageButtons with a custom one
> 
> * No action in Android Renderer
> * In iOS Renderer
> 
> ```
> var button = this.Control as UIButton;
> button.HorizontalAlignment = UIControlContentHorizontalAlignment.Center;
> button.VerticalAlignment = UIControlContentVerticalAlignment.Center;
> ```
> 
> Easy to apply, easy to remove when the bug is fixed and works reliably.

It can be fixed by putting WidthRequest and HeightRequest with ImageButton control but I'll try iOS Renderer too where we cannot define WidthRequest and HeightRequest. Thanks.

**Comment by munkii** [comment]
Has the bug been fixed and released?
