### ISSUE TITLE
[Bug] Immediate crash on startup with 4.4.0-sr1 on UWP

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/Xamarin.Forms#9134]
### Description
Immediate crash on startup with 4.4.0-sr1 on UWP.
This is due to the changes made in #8938.

### Steps to Reproduce

1. Create a new blank Xamarin.Forms project with a UWP target in Visual Studio.
2. Update to Xamarin.Forms 4.4.0-sr1.
3. Run the app.

### Expected Behavior
The app should not crash.

### Actual Behavior
The app crashes immediately on startup with the following exception:
`System.InvalidCastException: 'Unable to cast object of type 'System.Attribute[]' to type 'Xamarin.Forms.HandlerAttribute[]'.'
`

### Basic Information

- Version with issue: 4.4.0.991440 (4.4.0-sr1)
- Last known good version: 4.4.0.991265 (4.4.0-rc)
- IDE: Microsoft Visual Studio 2019 Enterprise
- Platform Target Frameworks: 
  - UWP:  Windows 10 Build 1903

**Comment by velocitysystems** [comment]
@samhouts @davidortinau This is a critical issue and results in an _immediate_ crash on startup.
There is no way to mitigate this crash with the release NuGet package.

**Comment by samhouts** [comment]
@velocitysystems Thanks! We've unlisted the update and we'll republish without this exception.

**Comment by jonathanpeppers** [comment]
This is really weird, if I build Xamarin.Forms and run the Control Gallery locally this works:

![image](https://user-images.githubusercontent.com/840039/72036607-efd22f80-3260-11ea-8f96-fe6a712f9a08.png)

Array covariance should work, this is weird...

**Comment by MagicAndre1981** [comment]
@samhouts don't close the issue until the fix is merged in 4.4 and released on nuget. I also ran into the issue

**Comment by MooVC** [comment]
This issue should be reopened as despite it being unlisted, it is still affecting any project I have that uses a wildcard to load the latest minor version of Xamarin.Forms.  Even when the cache is explicitly cleared, 4.4.0.991440 is being downloaded from NuGet, resulting in the observed crash.  A new version is needed to avoid this behavior.

**Comment by MagicAndre1981** [comment]
@samhouts ok, I see it is merged, can we get a 4.4 nightly to test it? 

It would be also better to create new labels ("fixed in codebase", "pending release", "released in version x.y.z" similar to VS dev community) and add them and close the issue only when fix is released and at this stage change status to closed and add released label

**Comment by samhouts** [comment]
@MagicAndre1981 SR2 should be on its way to NuGet within the next hour. 

Thanks for the suggestion about the labels. We'll take it under consideration. :)

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 SR2 should be on its way to NuGet within the next hour.
> 
> Thanks for the suggestion about the labels. We'll take it under consideration. :)

ok, the SR2 works now. And please add the new labels. To see which fix is in which release is extremely complicated.

**Comment by MitchBomcanhao** [comment]
I've just updated our project to 4.4.0-sr2 and getting a crash on launch when the app comes from the proper VSTS build. Local debug builds seem to work fine, so a bit puzzling

**Comment by jonathanpeppers** [comment]
> I've just updated our project to 4.4.0-sr2 and getting a crash on launch when the app comes from the proper VSTS build. Local debug builds seem to work fine, so a bit puzzling

@MitchBomcanhao I'm glad it's not just me that's puzzled!

**Comment by MagicAndre1981** [comment]
Which Visual Studio versions do you use? @MitchBomcanhao @jonathanpeppers 

I use Visual Studio 2017 and here I had the issue with SR1 and the SR2 works fine and the app runs fine.

**Comment by MitchBomcanhao** [comment]
I'm on 2019 (16.4.2) for both local machine and the remote build agent.

**Comment by velocitysystems** [comment]
Updating to SR2 resolved the issue for us.
No problem with debug or release builds from our CI pipeline for iOS, Droid or UWP.

**Comment by MitchBomcanhao** [comment]
I've noticed that a similar issue with Xamarin Tizen #9129 which mentions SkiaSharp, and we are using SkiaSharp 1.68.1.1 on our Xamarin app, so might be related.

**Comment by MitchBomcanhao** [comment]
The UWP app also crashes when I run locally on a Release configuration. Debug config works just fine.
Will attempt to make a repro project...
