### ISSUE TITLE
[Bug] ios:VisualElement.IsShadowEnabled is not working on ImageButton

### ISSUE THREAD

**Issue by ivanicin** [xamarin/Xamarin.Forms#9140]
### Description
ios:VisualElement.IsShadowEnabled is not working on ImageButton
### Steps to Reproduce

1. just add the ImageButton with ios:VisualElement.IsShadowEnabled="true"
2. 
3. 

### Expected Behavior
There should be a drop shadow on iOS, it works for the Button and there is no reason why it wouldn't work on ImageButton
### Actual Behavior
But it doesn't work
### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version:
- IDE: Microsoft Visual Studio Community 2019
Version 16.4.2
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by hartez** [comment]
[_9140 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4043251/_9140.Repro.zip)

Seems to be working the same for ImageButton and Button - what am I missing?

**Comment by ivanicin** [comment]
Just run your sample project and I am getting the same problem, so considering the code nothing more is needed, now considering the software and hardware I filled the form, but possibly you need some more so feel free to ask:

![Simulator Screen Shot - iPhone 11 - 2020-01-10 at 13 28 13](https://user-images.githubusercontent.com/20874207/72153141-56646400-33ad-11ea-8f12-a6c9ecee0176.png)

**Comment by PureWeen** [comment]
@ivanicin looking at @hartez 's sample what he's showing is that you need to specify more parameters to get the shadow not just *ios:VisualElement.IsShadowEnabled="true" *

In the sample he's show using these properties on each element and that the result is symmetrical
```XAML
   <Button Text="Hello" ios:VisualElement.IsShadowEnabled="true"
				ios:VisualElement.ShadowColor="Purple"
                 ios:VisualElement.ShadowOpacity="0.7"
                 ios:VisualElement.ShadowRadius="12" />
        <ImageButton Source="bell.png" ios:VisualElement.IsShadowEnabled="true"
					 ios:VisualElement.ShadowColor="Purple"
                 ios:VisualElement.ShadowOpacity="0.7"
                 ios:VisualElement.ShadowRadius="12" />

        <Button Text="Hello" ios:VisualElement.IsShadowEnabled="true" />
        <ImageButton Source="bell.png" ios:VisualElement.IsShadowEnabled="true" />
```


![image](https://user-images.githubusercontent.com/5375137/72180663-d63a0080-33a4-11ea-89e2-f17d89e9a4e7.png)


If this still seems incorrect can you provide a sample.

**Comment by samhouts** [comment]
@ivanicin  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
