### ISSUE TITLE
[Bug] macOS: Custom font

### ISSUE THREAD

**Issue by Suplanus** [xamarin/Xamarin.Forms#9141]
### Description
If I use a custom font likee `FontAwesome` the font is displayed in iOS, but not on macOS. I have to add the font to the macOS fonts in the system. Then it works... But thats not a workaround if you want to add the app to the macOS appstore.

### Steps to Reproduce

1. Add the font to the project
2. Create a label with it
3. Make the different `info.plist` entries in the projects

### Expected Behavior
Font should be displayed.

### Actual Behavior
Fallback to the name of the glyph.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991265

### Screenshots

iOS:
![image](https://user-images.githubusercontent.com/2002916/72075783-b21ee680-32f4-11ea-8a8b-93064c7fe14e.png)

macOS font in OS installed:
![image](https://user-images.githubusercontent.com/2002916/72075807-bc40e500-32f4-11ea-8066-0acfb84341e4.png)

macOS font in OS NOT installed:
![image](https://user-images.githubusercontent.com/2002916/72075815-c06d0280-32f4-11ea-9fcb-cd2eb46c04e1.png)

### Reproduction Link

I made a small project [here](https://github.com/Suplanus/Xamarin.Bugs/blob/af675b7ebdecd17dc6c302908c7bb6046b8f646d/src/Xamarin.Bugs/Issue9141.xaml#L14).

**Comment by VladislavAntonyuk** [comment]
```
<key>UIAppFonts</key>
	<array>
		<string>FontAwesome5Brands.otf</string>
		<string>FontAwesome5Regular.otf</string>
		<string>FontAwesome5Solid.otf</string>
	</array>

**Comment by Suplanus** [comment]
Sounds good.
What do you mean that the info.plist entry is wrong?
Is `Fonts provided by application` wrong? Should it be the same as iOS `UIAppFonts`?

**Comment by VladislavAntonyuk** [comment]
@Suplanus no, keys are different

**Comment by Suplanus** [comment]
Oh, a big thanks.
Found an example [here](https://github.com/xamarin/mac-samples/blob/9bd3c2674f6d989a37e108d8f0595d7106881f53/CustomFont/CustomFont/Info.plist#L33).
Is it necessary to add the `Fonts provided by application` key?
For me it look like all the fonts would be imported?

Big thanks for your help 💕

**Comment by VladislavAntonyuk** [comment]
Is it necessary to add the Fonts provided by application key? - No. 
all fonts in fonts folder will be used in app. You do not need to install it in system. 
Feel free to close a defect

**Comment by jfversluis** [comment]
Great to see this is resolved!

Thank you for your help @VladislavAntonyuk !

**Comment by Suplanus** [comment]
For completion:
The reported problem was with a label, and so it works.

@vladimir-kotikov BIG THANK YOU 💕
