### ISSUE TITLE
[Bug] IndicatorView is not working in Xamarin.Forms 4.4

### ISSUE THREAD

**Issue by luismts** [xamarin/Xamarin.Forms#9155]
### Description
The IndicatorView is not working in Xamarin.Forms 4.4. The app does not show the indicator and the app is getting a blank page (sometimes app crashes)

**Note**: Tested just on Android*

### Steps to Reproduce

Just add an IndicatorView as the documentation says. 

### Expected Behavior
Those indicators can be showed without errors

### Actual Behavior
The app does not show the indicator and the app is getting a blank page (sometimes app crashes)

### Basic Information

- Version with issue: Xamarin.Forms 4.4
- Last known good version: --
- IDE: Visual Studio 16.4.2
- Platform Target Frameworks: 
  - Android: 9.0 (API Level 28 - Pie)

**Comment by jfversluis** [comment]
Hey @luismts thanks for the report!

Unfortunately I'm not able to reproduce this. I have attached a reproduction. Could you check what that does for you? If you could add code to that to show the issue and post it back here, that would be great!

[Repro9155.zip](https://github.com/xamarin/Xamarin.Forms/files/4047518/Repro9155.zip)

**Comment by jfversluis** [comment]
Thinking about it... Did you set the experimental flag? See the `App.xaml.cs` in the reproduction.

**Comment by luismts** [comment]
Yep, It's working now. Didn't notice about the flag. Thanks!
