### ISSUE TITLE
Android FormsAppCompatActivity

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9156]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/878049/android-formsappcompatactivity.html)._

---
<p>When changed the activity from FormsApplicationActivity To FormsAppCompatActivity getting unhandled exception below is my OnCreate and style.xml and color.xml code. Please suggest what need to be changed.</p> <p>protected override void OnCreate(Bundle bundle)
        {
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) =&gt; true;
            base. OnCreate(bundle);
            //Android.Views.View view = this. Window.DecorView;
            //view. SetBackgroundColor(Android.Graphics.Color.Rgb(108, 39, 106));
            global::ZXing.Net.Mobile.Forms.Android.Platform.Init();
            global::ZXing.Net.Mobile.Forms.Android.ZXingScannerViewRenderer.Init();
            global::Xamarin.Forms.Forms.Init(this, bundle);
            Thread.CurrentThread.CurrentCulture = new CultureInfo(&quot;en-US&quot;);
            // Initializing the log4net
            // AtparLogInitializer.InitializeLog4net(global::AtParXFEnums.EnumApps.Init);
            XamarinUITestStyleIdInitialization();
            var prefs = Application.Context.GetSharedPreferences(&quot;FileCreate1&quot;, FileCreationMode.Private);
            Boolean isFirst = prefs. GetBoolean(&quot;isFirst&quot;, true);
            AtParDefns.gAbuildVersion = (int)Build.VERSION.SdkInt;
            AtParDefns.isFirstApp = isFirst;
            objcontext = this;
            //region for screen Height and Width
            var metrics = Resources.DisplayMetrics;
            var widthInDp = ConvertPixelsToDp(metrics. WidthPixels);
            var heightInDp = ConvertPixelsToDp(metrics. HeightPixels);
            AtParDefns.gScreenHeight = heightInDp;
            AtParDefns.gScreenWidth = widthInDp;
            if ((int)Build.VERSION.SdkInt &lt; 23)
            {
                Setdata();
            }
            else
            {
                if (isFirst)
                {
                    AtParDefns.Assets = this. Assets;
                    XfPopups.Init();
                    LoadApplication(new App());
                    lstPkgInfo = PackageManager.GetInstalledPackages(PackageInfoFlags.MetaData);
                }
                else
                {
                    Setdata();
                }
            }
        }</p><p class="">//Style.xml</p><p class="">&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
&lt;resources&gt;
  &lt;style name=&quot;Theme.Splash&quot; parent=&quot;android:Theme&quot;&gt;
    &lt;item name=&quot;android:windowBackground&quot;&gt;@drawable/splashscreen&lt;/item&gt;
    &lt;item name=&quot;android:windowNoTitle&quot;&gt;true&lt;/item&gt;
    &lt;item name=&quot;android:windowFullscreen&quot;&gt;true&lt;/item&gt;
    &lt;item name=&quot;android:windowActionBar&quot;&gt;true&lt;/item&gt;
    &lt;item name=&quot;android:windowIsTranslucent&quot;&gt;false&lt;/item&gt;
    &lt;item name=&quot;android:windowIsFloating&quot;&gt;false&lt;/item&gt;
    &lt;item name=&quot;android:backgroundDimEnabled&quot;&gt;true&lt;/item&gt;  
  &lt;/style&gt;
  &lt;style name=&quot;MainActivityBgColor&quot; parent=&quot;@android:style/Theme.Holo.Light&quot;&gt;
    &lt;!--&lt;item name=&quot;android:windowBackground&quot;&gt;@color/lightPurple&lt;/item&gt;--&gt;
    &lt;item name=&quot;android:textColor&quot;&gt;@color/black&lt;/item&gt;
    &lt;item name=&quot;android:textColorPrimary&quot;&gt;@color/green&lt;/item&gt;
    &lt;item name=&quot;android:colorPrimary&quot;&gt;@color/lightGreen&lt;/item&gt;
    &lt;item name=&quot;android:actionBarStyle&quot;&gt;@style/custom_actionBarItemBackground&lt;/item&gt;
    &lt;item name=&quot;android:spinnerStyle&quot;&gt;@style/custom_spinnerStyle&lt;/item&gt;
    &lt;item name=&quot;android:icon&quot;&gt;@android:color/transparent&lt;/item&gt;
  &lt;/style&gt;
  &lt;style name=&quot;custom_spinnerStyle&quot; parent=&quot;android:Widget.Holo.Spinner&quot;&gt;
    &lt;item name=&quot;android:background&quot;&gt;@color/white&lt;/item&gt;
    &lt;item name=&quot;android:popupBackground&quot;&gt;@color/lightGreen&lt;/item&gt;
    &lt;item name=&quot;android:dropDownSelector&quot;&gt;@color/lightGreen&lt;/item&gt;
  &lt;/style&gt;
  &lt;style name=&quot;custom_actionBarItemBackground&quot; parent=&quot;@android:style/Widget.Holo.ActionBar&quot;&gt;
    &lt;item name=&quot;android:background&quot;&gt;@drawable/actionbarborder&lt;/item&gt;
  &lt;/style&gt;
  &lt;style name=&quot;RobotoTextViewStyle&quot; parent=&quot;android:Widget.TextView&quot;&gt;
    &lt;item name=&quot;android:fontFamily&quot;&gt;sans-serif&lt;/item&gt;
  &lt;/style&gt;
&lt;/resources&gt;<br></p><p>//Color.xml</p><p>&lt;resources&gt;
  &lt;color name=&quot;green&quot;&gt;#999999&lt;/color&gt;
  &lt;color name=&quot;lightGreen&quot;&gt;#999999&lt;/color&gt;
  &lt;color name=&quot;white&quot;&gt;#FFFFFF&lt;/color&gt;
  &lt;color name=&quot;black&quot;&gt;#000000&lt;/color&gt;
  &lt;color name=&quot;syftBackgroundColor&quot;&gt;#4a4858&lt;/color&gt;
  &lt;color name=&quot;colorCursors&quot;&gt;#ffffff&lt;/color&gt;
&lt;/resources&gt;</p>

---
#### Visual Studio Feedback System on 1/7/2020, 10:10 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by kingces95** [comment]
Asked for a reproduction on the orig bug to be attached here.

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
