### ISSUE TITLE
[Bug] Failed to resolve Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer::UpdateMenuItemIcon

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Xamarin.Forms#9164]
### Description

When upgrading Xamarin.Forms from 4.4.0.991265 to 4.4.0.991477, my app does not build anymore on Android.
The root caused seems to be the removal of a protected method in Xamarin.Forms, that causes trouble to the linker in my build process (this method is used in the iconize plugin).
Why did you introduce such a breaking change in a service release ?
Could you please rollback this change (or at least document it properly) ?
Thank you

### Stack trace

...\Xamarin.Android.Common.targets(2060,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.Iconize.IconNavigationRenderer::UpdateMenuItemIcon(Android.Content.Context,Android.Views.IMenuItem,Xamarin.Forms.ToolbarItem)' in assembly: 'Plugin.Iconize.dll' 
---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer::UpdateMenuItemIcon(Android.Content.Context,Android.Views.IMenuItem,Xamarin.Forms.ToolbarItem)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue()
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    --- End of inner exception stack trace --- 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessQueue() 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process()
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Steps.MarkStep.Process(LinkContext context) 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context) 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Mono.Linker.Pipeline.Process(LinkContext context)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res) 
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
...\Xamarin.Android.Common.targets(2060,5): error XALNK7000:    at Xamarin.Android.Tasks.AndroidTask.Execute()

**Comment by samhouts** [comment]
closed by #9165

**Comment by jalbertSyncroTech** [comment]
This doesn't fix the behavior change that corresponded with the ABI breaking:

even though function now exists again, nothing is calling it, so anybody that needs to override UpdateMenuItemIcon() - previously the only way to customize Android NavigationPage Toolbar Icons - now doesn't have that hook available.

Instead, UpdateMenu() in NavigationPageRenderer needs to call a version of the new UpdateMenuItems() that can take a handler for the pdateMenuItemIcon() function, and then call it with the NavigationPageRenderer protected virtual method.
