### ISSUE TITLE
[Enhancement] Previewer/hot reload for UI defined in code

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/Xamarin.Forms#9166]
### Current status of preview/hot reloading

Currently there is a [XAML previewer](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows) and [XAML hot reload](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload). These don't apply to UI defined in .Net code and should be generalized to do that. (Generalized because a method of previewing UIs described in IL would apply to all .Net languages and also XAML.)

### Why UI in code?

UI in code is valuable because compared with XAML it allows type-safe properties, with no reliance on magic strings. It also allows UI with full flexibility: the ability to work with arbitrary data and use any computable functions to create UIs. Depending on the approach it may have additional advantages of strongly typed alternatives to bindings without the [need to register converters](https://github.com/verybadcat/CSharpMath/issues/36#issuecomment-485589062). These advantages are the inspiration for Xamarin.Forms UI libraries including [C# for markup](https://github.com/VincentH-Net/CSharpForMarkup) ([PR](https://github.com/xamarin/Xamarin.Forms/pull/8342)) and [Fabulous](https://github.com/fsprojects/Fabulous).

### Need for a preview/hot reloading

Lack of a previewer is the main disadvantage of UI in code and that situation should be improved. The things to be previewed must be discoverable, selectable in an IDE, and contain sample data. 

The thing being previewed must be an instance of an class inheriting from `Xamarin.Forms.VisualElement`. This deals with the issue of sample data since the user defines the instance and therefore any sample data to be used.

### Syntax and spec for previews

Hot reload is more complex so it may make sense to work on previews first.

C#:
```csharp
[PreviewFixture] // Xamarin.Forms.PreviewFixture mimicing NUnit syntax.
public class GreenFooLabel: Label
{
    public GreenFooLabel(string bar)
    {
        Text = "foo" + bar;
        TextColor = Color.Green;
    }

    [Preview] // only used for preview tooling
    public static GreenFooLabel Sample() // an object inheriting from VisualElement.
    {
        return new GreenFooLabel("bar"); // using sample data "bar"
    }
}
```

F#:
```fsharp
[<PreviewFixture>]
type GreenFooLabel(bar:string) =
    inherit Label(Text = "foo" + bar, TextColor = Color.Green)
    [<Preview>] 
    static member Sample = GreenFooLabel("bar")
```

As properties are altered, or any dependencies are changed, code is recompiled incrementally, or alternatively an interpreter is used, to allow fast updates of the previews.

**TBD:** should previews be specified at the point where Xamarin.Forms views are defined as above? This is very convenient, but will need to specify a platform and potentially a project where platform-initialization code including custom renderers are defined. Or should they be defined in platform-specific projects?

> VS bug [#1081348](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1081348)

**Comment by realvictorprm** [comment]
Good stuff, would be really nice to have that so my F# Apps can be hot reloaded too 😺

**Comment by pierceboggan** [comment]
Thanks for the feedback and valuable suggestion! For any tooling around Xamarin.Forms, Visual Studio Developer Community is the best place to leave your feedback (either bugs or suggestions).

We want our tools to be flexible to the authoring style that makes you most productive, including those that author their Xamarin.Forms UI in code. Check out our suggestion for C# hot reload, which is listed as "On Roadmap", and will support updates to UI code as well as business logic:
https://developercommunity.visualstudio.com/idea/650684/c-hot-reload-xamarin.html

I don't believe we have had any customer asks for F# hot reload, so feel free to log a suggestion on Developer Community to track interest on that:
https://developercommunity.visualstudio.com/content/idea/post.html?space=8
