### ISSUE TITLE
[Bug] DisplayPromptAsync not working

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9168]
### Description
**DisplayPromptAsync** is not working. Nothing happens. I was testing on Android.

### Steps to Reproduce

1. Run this project
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4049905/App1.zip)

2. Click the button.
3. Nothing happens

### Expected Behavior
Prompt dialog should be displayed.

### Actual Behavior
Nothing happens

### Basic Information

- Version with issue: 4.4.0.991477
- IDE: 16.4.2
- Platform Target Frameworks: 
  - Android: 9,0 (Pie)

**Comment by VladislavAntonyuk** [comment]
```
private async void Button_Clicked(object sender, EventArgs e)
        {
            string x = await DisplayPromptAsync("title", "message", "ok", "cancel", "placeholder");
        }

**Comment by Mikilll94** [comment]
@VladislavAntonyuk 
Ok. It seems like it is not working inside **Task.Run()**. Otherwise, it is working.

**Comment by hartez** [comment]
It's not working from `Task.Run` because `Task.Run` queues the work on the thread pool; `DisplayPromptAsync` needs to create a dialog, which has to be done from the UI thread. 

Is there some reason you're trying to call this from a thread?

**Comment by Mikilll94** [comment]
@hartez 
Yes. Just watch this fragment of this video https://youtu.be/xxifTwQaA0s?t=348

They have said that in order to avoid async void in the event method, the best to implement it, is to use **Task.Run()**

**Comment by hartez** [comment]
Well, that _is_ a way to avoid `async void`, but you're calling this from an event handler, which is the only situation where `async void` is considered correct. For example, see https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming

>To summarize this first guideline, you should prefer async Task to async void. Async Task methods enable easier error-handling, composability and testability. The exception to this guideline is asynchronous event handlers, which must return void.

So in the situation you're presenting, what @VladislavAntonyuk suggested upthread is what you should be doing. 

If you're really determined to use `Task.Run`, you're going to have to invoke `DisplayPromptAsync` on the UI thread, so your Action is going to have to use something like `Device.BeginInvokeOnMainThread` or `Device.InvokeOnMainThreadAsync`.

**Comment by ajtruckle** [comment]
I am confused about this.

I am trying (Xamarin Forms 5.x):

        async void AddPublisherButton_Clicked(System.Object sender, System.EventArgs e)
        {
            string result = await Application.Current.MainPage.DisplayPromptAsync("Add Publisher", "Name:");

            if(result != null)
            {
                // We need to prompt for a new Publisher and make sure it does not exist!
                _ViewModel.vrrData.ListPublishers.Add(result);
            }

        }

But the prompt does not display either. Note that my application MainPage is a TabbedPage.
