### ISSUE TITLE
[Bug] Shell Navigated event/override is a mess

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms#9169]
### Description
We have two options to respond to navigated execution in Shell:

1. To override `Shell.OnNavigated()` method
2. To subscribe to `Shell.Navigated` event

Let's have a hierarchy as follows:
**MainPage** -> **AlarmPage** -> **SoundsPage**
**SettingsPage**
**AboutPage**

While`OnNavigated()` is called right after navigating, when application starts, it's called twice with same arguments. Then it works as expected.
The second approach `Shell.Navigated` event doesn't work as expected at all. Event is not invoked after navigating to AlarmPage, nor SoundsPage. Instead, event is invoked after navigating back to MainPage from AlarmPage and SoundsPage. In that moment, event is invoked multiple times, for each navigation forward/backward.

### Steps to Reproduce

1. Run the app. Notice that `OnNavigated()` override is called twice, `Navigated` event is invoked once.
2. Navigate to **AlarmPage**. Notice that `OnNavigated()` override is called twice with same argument, but `Navigated` event is not invoked.
3. Navigate to **SoundsPage**. Notice that `OnNavigated()` override is called twice with same argument, but `Navigated` event is not invoked.
4. Navigate back to **AlarmPage**. `OnNavigated()` override is called once, `Navigated` event is not invoked.
5. Navigate back to **MainPage**. `OnNavigated()` is called once, but now `Navigated` event is called multiple times:
5.1. For navigation **MainPage** -> **AlarmPage**
5.2. For navigation **AlarmPage** -> **SoundsPage**
5.3. For **AlarmPage** <- **SoundsPage**
5.4. For **MainPage** <- **AlarmPage** 

### Expected Behavior
`Navigated` event and `OnNavigated()` method to be called once, right after navigation executed.

### Actual Behavior
`Navigated` event invocations are deferred, `OnNavigated()` method is called multiple times.

### Basic Information

- Version with issue: 4.4.0.991477
- IDE: 16.4.2

### Reproduction Link

[ShellNavigated.zip](https://github.com/xamarin/Xamarin.Forms/files/4050655/ShellNavigated.zip)

**Comment by samhouts** [comment]
closed by #10048
