### ISSUE TITLE
[Bug] DisplayPromptAsync overload hurts usability

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#9171]
The changes to DisplayPromptAsync in PR #8362 will be confusing and annoying for users. 

The message in the `Obsolete` attribute is _technically_ accurate, but it doesn't direct the user to the correct method to use. So at the very least, it should point out _which_ overload to use. 

But what's going to be even more grating for folks is that `DisplayPromptAsync` is now effectively unusable without the `initialValue` parameter. Specifying any combination of the optional parameters which _does not_ include `initialValue` will result in CS0121 (The call is ambiguous between the following methods or properties: 'method1' and 'method2'). You can no longer simply call `DisplayPromptAsync("title", "message");`.

We have a few options here:

1. Add the optional `initialValue` parameter to the original method, drop the new overload, and just accept the breaking change.

2. Remove the new overload of `DisplayPromptAsync`. Introduce a new class `Xamarin.Forms.PromptArguments : Xamarin.Forms.Internals.PromptArguments`. Add an overload to `DisplayPromptAsync` which takes a `Xamarin.Forms.PromptArguments`. If folks want to have an initial value, they need to call the version which uses `PromptArguments`.

**Comment by jfversluis** [comment]
Ugh. Yeah, this hasn't worked out for the best. But I think with how things are standing now, we will have a breaking change either way, no?

We will either introduce the `PromptArguments` and drop the new overload _or_ we will drop the obsolete `DisplayPromptAsync` and be left with just one that includes the `initialValue` parameter.

But in either case we will have to drop one of the methods to avoid the CS0121.

**Comment by jfversluis** [comment]
Choose to go with just removing the obsolete overloads without the extra parameter. That seems to make the most sense for the users upgrade scenario.

Whether users have adopted the new overload or not, because of the parameter being optional in both cases their code should not break.

**Comment by capricciobob** [comment]
Just upgrading and ran into the breaking change. It wasn't real obvious, but I did figure it out after a couple minutes. Glad I saw this thread!

**Comment by jfversluis** [comment]
Sorry about that @capricciobob! Hopefully we can get this in soon and save people some headaches
