### ISSUE TITLE
[Bug] iOS issue #8327 still not resolved despite fix #8889 in 4.4.0.991440

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#9174]
### Description
Issue #8327 is stated as fixed by #8889, see release notes for 4.4.0.991440 
But the problem is not solved. Toolbaritems are still added as primary, just like before this "fix".
Tested on simulator and device

### Basic Information

- Version with issue: 4.4.0.991440
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by samhouts** [comment]
@KoenMat  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by KoenMat** [comment]
[IssueShellToolbarSecondaryOrderIOS.zip](https://github.com/xamarin/Xamarin.Forms/files/4057865/IssueShellToolbarSecondaryOrderIOS.zip)
I created a new shell project and added two MenuItems in ItemsPage.xaml, with Order=Secondary.
Works on Android, but on iOS they appear in the primary menu.

**Comment by KoenMat** [comment]
Accidently pushed on "Close"

**Comment by PureWeen** [comment]
Duplicate
https://github.com/xamarin/Xamarin.Forms/issues/8422
