### ISSUE TITLE
[Bug] Android : Xamarin.Forms.Maps NativeMap events not fired since 4.3.0.908675

### ISSUE THREAD

**Issue by cbs-cbt** [xamarin/Xamarin.Forms#9176]
### Description
On Android project, Xamarin.Forms.Maps.MapRenderer provide "NativeMap" property pointing to the GoogleMap object. This NativeMap object provides several events the renderer can subscribe to.
Since version 4.3.0.908675, the events are not fired anymore.  

### Steps to Reproduce

1. Create a custom rendrerer for Xamarin.Forms.Maps according this documentation: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin (please focus on Android project)
2. Subscribe to any NativeMap event in overriden OnMapReady function in the map renderer (for example NativeMap.MarkerClick += NativeMap_MarkerClick;)
3. Put a break point on the "NativeMap_MarkerClick" function
4. Start debug Android project
5. The break point is never reached since version 4.3.0.908675
6. Downgrade Xamarin.Forms.Maps NuGet package to 4.2.0.910310 (latest working version)
7. Re-start debug Android project, this time the break point is reached

### Expected Behavior
Break point should be reached on any version

### Actual Behavior
Break point is not reached

### Basic Information

- Version with issue: since 4.3.0.908675
- Last known good version: 4.2.0.910310
- IDE: Visual Studio 2019
- Platform Target Frameworks:
  - Android: All versions 
- Nuget Packages: Xamarin.Forms.Maps
- Affected Devices: All

### Workaround

Downgrade to version 4.2.0.910310

**Comment by StephaneDelcroix** [comment]
please provide a reproduction project. this is important to us.

**Comment by jcmanke** [comment]
4.3.0 added the `Pin.MarkerClicked` event which uses `NativeMap.MarkerClicked` (see #6079). Possibly an issue with the event already having a handler?

**Comment by cbs-cbt** [comment]
> 
> 
> 4.3.0 added the `Pin.MarkerClicked` event which uses `NativeMap.MarkerClicked` (see #6079). Possibly an issue with the event already having a handler?

Thank you @jcmanke for pointing me to the right direction.

In my Map Android's CustomRenderer, I manually added the Markers, using `NativeMap.AddMarker(MarkerOptions)`

When Markers are created in that way, the marker fires no event when clicked.
Even `NativeMap.MarkerClick` won't work. This is perhaps because the event is already consumed by Xamarin.Forms.Maps object
