### ISSUE TITLE
[Bug] Calls to CleanUpWeakReferences causes Exceptions.

### ISSUE THREAD

**Issue by rlasker3** [xamarin/Xamarin.Forms#9183]
### Description
We recently updated to Xamarin Forms v4.4.0.991265 and after releasing our app we are getting a lot of crashes and exceptions recorded in AppCenter due to a null reference exception thrown from the CleanUpWeakReferences in the Styles class.

### Steps to Reproduce
I do not have any specific steps to reproduce. It is logged in AppCenter under various situations for both Android and iOS. Here are a few stack traces:

#########################
SyncView+<InitializeComponent>_anonXamlCDataTemplate_7.LoadDataTemplate ()
SIGABRT: Object reference not set to an instance of an object

Style+<>c.<CleanUpWeakReferences>b__47_0 (System.WeakReference`1[T] t)
List`1[T].RemoveAll (System.Predicate`1[T] match)
Style.CleanUpWeakReferences ()
IStyle.Apply (Xamarin.Forms.BindableObject bindable)
MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style)
MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value)
MergedStyle.OnImplicitStyleChanged ()
MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes)
Element.OnResourceChanged (Xamarin.Forms.BindableProperty property, System.Object value)
Element.OnSetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key, System.Boolean fromStyle)
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
MergedStyle.RegisterImplicitStyles ()
Xamarin.Forms.MergedStyle..ctor (System.Type targetType, Xamarin.Forms.BindableObject target) <0x10176e830 + 0x0010b> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.NavigableElement..ctor () <0x10179fe90 + 0x0006f> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.VisualElement..ctor () <0x1017eaab0 + 0x000ef> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.View..ctor () <0x1017e6120 + 0x0010b> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.Label..ctor () <0x10175b670 + 0x00017> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
SyncView+<InitializeComponent>_anonXamlCDataTemplate_7.LoadDataTemplate ()
ElementTemplate.CreateContent ()
DataTemplateExtensions.CreateContent (Xamarin.Forms.DataTemplate self, System.Object item, Xamarin.Forms.BindableObject container)
TemplatedItemsList`2[TView,TItem].ActivateContent (System.Int32 index, System.Object item)
ListViewRenderer+UnevenListViewDataSource.GetEstimatedRowHeight (UIKit.UITableView table)
ListViewRenderer+UnevenListViewDataSource.UpdateEstimatedRowHeight (UIKit.UITableView tableView)
ListViewRenderer+ListViewDataSource.DetermineEstimatedRowHeight ()
FormsUITableViewController.ViewWillLayoutSubviews ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

####################################
Style+<>c.<CleanUpWeakReferences>b__47_0 (System.WeakReference`1[T] t)
System.AggregateException: Object reference not set to an instance of an object

Xamarin.Forms
Style+<>c.<CleanUpWeakReferences>b__47_0 (System.WeakReference`1[T] t)
System.Collections.Generic
List`1[T].RemoveAll (System.Predicate`1[T] match)
Xamarin.Forms
Style.CleanUpWeakReferences ()
Xamarin.Forms.Style.Xamarin.Forms
IStyle.Apply (Xamarin.Forms.BindableObject bindable)
Xamarin.Forms
MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style)
Xamarin.Forms
MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value)
Xamarin.Forms
MergedStyle.OnImplicitStyleChanged ()
Xamarin.Forms
MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)
Xamarin.Forms
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
Xamarin.Forms
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
Xamarin.Forms
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes)
Xamarin.Forms
Element.OnResourceChanged (Xamarin.Forms.BindableProperty property, System.Object value)
Xamarin.Forms
Element.OnSetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
Xamarin.Forms
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key, System.Boolean fromStyle)
Xamarin.Forms
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
Xamarin.Forms
MergedStyle.RegisterImplicitStyles ()
Xamarin.Forms.MergedStyle
Xamarin.Forms.MergedStyle..ctor (System.Type targetType, Xamarin.Forms.BindableObject target) <0x10176e830 + 0x0010b> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.NavigableElement
Xamarin.Forms.NavigableElement..ctor () <0x10179fe90 + 0x0006f> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.VisualElement
Xamarin.Forms.VisualElement..ctor () <0x1017eaab0 + 0x000ef> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.View
Xamarin.Forms.View..ctor () <0x1017e6120 + 0x0010b> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Xamarin.Forms.Label
Xamarin.Forms.Label..ctor () <0x10175b670 + 0x00017> in <8e9ab226c9a54dbdb9366a1fb41e66e3#4db30f082bc5b31527f597def11308a6>:0
Inform.Forms.Views
SyncView+<InitializeComponent>_anonXamlCDataTemplate_7.LoadDataTemplate ()
Xamarin.Forms
ElementTemplate.CreateContent ()
Xamarin.Forms.Internals
DataTemplateExtensions.CreateContent (Xamarin.Forms.DataTemplate self, System.Object item, Xamarin.Forms.BindableObject container)
Xamarin.Forms.Internals
TemplatedItemsList`2[TView,TItem].ActivateContent (System.Int32 index, System.Object item)
Xamarin.Forms.Platform.iOS
ListViewRenderer+UnevenListViewDataSource.GetEstimatedRowHeight (UIKit.UITableView table)
Xamarin.Forms.Platform.iOS
ListViewRenderer+UnevenListViewDataSource.UpdateEstimatedRowHeight (UIKit.UITableView tableView)
Xamarin.Forms.Platform.iOS
ListViewRenderer+ListViewDataSource.DetermineEstimatedRowHeight ()
Xamarin.Forms.Platform.iOS
FormsUITableViewController.ViewWillLayoutSubviews ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIKit
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIKit
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Inform.Forms.iOS
Application.Main (System.String[] args)

#################################
ComponentLabel.GetRequiredAsteriskLabel ()
System.IndexOutOfRangeException: length < 0

System
Array.Clear (System.Array array, System.Int32 index, System.Int32 length)
System.Collections.Generic
List`1[T].RemoveAll (System.Predicate`1[T] match)
Xamarin.Forms
Style.CleanUpWeakReferences ()
Xamarin.Forms.Style.Xamarin.Forms
IStyle.Apply (Xamarin.Forms.BindableObject bindable)
Xamarin.Forms
MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style)
Xamarin.Forms
MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value)
Xamarin.Forms
MergedStyle.OnImplicitStyleChanged ()
Xamarin.Forms
MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)
Xamarin.Forms
BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent)
Xamarin.Forms
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes)
Xamarin.Forms
BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes)
Xamarin.Forms
Element.OnResourceChanged (Xamarin.Forms.BindableProperty property, System.Object value)
Xamarin.Forms
Element.OnSetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
Xamarin.Forms
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key, System.Boolean fromStyle)
Xamarin.Forms
BindableObject.SetDynamicResource (Xamarin.Forms.BindableProperty property, System.String key)
Xamarin.Forms
MergedStyle.RegisterImplicitStyles ()
Xamarin.Forms.MergedStyle
Xamarin.Forms.MergedStyle..ctor (System.Type targetType, Xamarin.Forms.BindableObject target) [0x0001f] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0
Xamarin.Forms.NavigableElement
Xamarin.Forms.NavigableElement..ctor () [0x00018] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0
Xamarin.Forms.VisualElement
Xamarin.Forms.VisualElement..ctor () [0x00059] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0
Xamarin.Forms.View
Xamarin.Forms.View..ctor () [0x0000b] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0
Xamarin.Forms.Label
Xamarin.Forms.Label..ctor () [0x00000] in <8e9ab226c9a54dbdb9366a1fb41e66e3>:0
Inform.Forms.Components
ComponentLabel.GetRequiredAsteriskLabel ()
Inform.Forms.Components.ComponentLabel
Inform.Forms.Components.ComponentLabel..ctor (System.String text, FFImageLoading.Svg.Forms.SvgCachedImage invalidImg, System.Collections.Generic.IList`1[T] styleClass, System.Boolean plainText, System.Boolean required, System.Boolean isInvalid, System.String color) [0x00142] in <ce23231aa8534d9c9920550315011bcb>:0
Inform.Forms.BaseClasses
ComponentBase.GetComponentLabel (System.String text, System.Boolean isPlainText, System.String color, System.Boolean bindingEnable, System.Collections.Generic.IList`1[T] style)
Inform.Forms.Components.FormComponents
NumericComponent+<InitializeAsync>d__11.MoveNext ()
Inform.Forms.Services
MobilePageService+<>c__DisplayClass36_4+<<LoadViewsAsync>b__5>d.MoveNext ()

### Basic Information

- Version with issue: v4.4.0.991265
- Last known good version: 
- IDE:
- Platform Target Frameworks: 
  - iOS:  13.6.0.12
  - Android: 10.0.6.2
- Nuget Packages:
- Affected Devices: Many

### Workaround
No known workaround

**Comment by rlasker3** [comment]
Is there any indication as to when this fix will be available for download. We are getting hundreds of these errors and I do not know what the consequences are in our app as we never saw this error during testing.

**Comment by samhouts** [comment]
The next service release containing this fix should be published before the end of next week. Thank you for your patience!

**Comment by rlasker-b2w** [comment]
@samhouts just got this exact same error with 4.4.0.991537 ... that was supposed to be the release to have fixed this issue correct?

Xamarin.Forms Style+<>c.<CleanUpWeakReferences>b__47_0 (System.WeakReference`1[T] t)
System.Collections.Generic List`1[T].RemoveAll (System.Predicate`1[T] match)
Xamarin.Forms Style.CleanUpWeakReferences ()
Xamarin.Forms.Style.Xamarin.Forms IStyle.Apply (Xamarin.Forms.BindableObject bindable)
Xamarin.Forms MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style)
Xamarin.Forms MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value)
Xamarin.Forms MergedStyle.OnImplicitStyleChanged ()
Xamarin.Forms MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)

**Comment by rlasker-b2w** [comment]
@samhouts ... I just got the exact same error in 4.4.0.991537. Wasn't that the SR that was supposed to fix this issue?

System.NullReferenceException: Object reference not set to an instance of an object

Xamarin.Forms Style+<>c.<CleanUpWeakReferences>b__47_0 (System.WeakReference`1[T] t)
System.Collections.Generic List`1[T].RemoveAll (System.Predicate`1[T] match)
Xamarin.Forms Style.CleanUpWeakReferences ()
Xamarin.Forms.Style.Xamarin.Forms IStyle.Apply (Xamarin.Forms.BindableObject bindable)
Xamarin.Forms MergedStyle.SetStyle (Xamarin.Forms.IStyle implicitStyle, System.Collections.Generic.IList`1[T] classStyles, Xamarin.Forms.IStyle style)
Xamarin.Forms MergedStyle.set_ImplicitStyle (Xamarin.Forms.IStyle value)
Xamarin.Forms MergedStyle.OnImplicitStyleChanged ()
Xamarin.Forms MergedStyle.<RegisterImplicitStyles>b__30_0 (Xamarin.Forms.BindableObject bindable, System.Object oldvalue, System.Object newvalue)

**Comment by rlasker-b2w** [comment]
It looks like the fix associated to this issue targeted the wrong class. The fix in [c87b733](https://github.com/xamarin/Xamarin.Forms/commit/c87b733b89011d538d83e56ea049a7917ad55ed5) is applied the [Xamarin.Forms.Core/Interactivity/AttachedCollection.cs](https://github.com/xamarin/Xamarin.Forms/blob/release-4.4.0-sr3/Xamarin.Forms.Core/Interactivity/AttachedCollection.cs#L138) file. But the stack trace in the error I submitted originates in the [Xamarin.Forms.Core/Style.cs](https://github.com/xamarin/Xamarin.Forms/blob/release-4.4.0-sr3/Xamarin.Forms.Core/Style.cs) class.
