### ISSUE TITLE
[Enhancement] Support for Visual Studio Code! at .net 5.0

### ISSUE THREAD

**Issue by danielmeza** [xamarin/Xamarin.Forms#9184]
Add support for **build**, **deploy** and **debug** using Visual Studio Code when targeting .net 5.0  

* **Build:**  
As the all Xamarin projects will be ported to the new SDK project style it will just work whit _dotnet build_ command. For iOS it should be a feature to connect the IDE to the build host. 

* **Deploy**  
The deploy process is more complex and will depend if the main implementation is made in the .targets file or as a Visual Studio extension I thing it will be a combination of both, but it will be easier if most of the work is writhe int he .targets files.

* **Debug**  
This should be easy to do since .net core support remote debugger, here we need to deploy also the vsdbg in order to connect to it and debug the app remotely.

This way we can develop apps on all platforms with a single IDE, other features like Archive, Deploy to production, UI Test running etc. can be added in the way. 

Remainder: this is for .net 5.0 and not for the current runtimes.

**Comment by jfversluis** [comment]
This won't be happening for Forms for sure. For .NET MAUI there will be some support, but the best experience will still be "full" Visual Studio. I think there is already some discussion or issue on the .NET MAUI repo about this. If you are still interested in this, make sure to make your voice heard there so we can gauge interest.

Thanks!
