### ISSUE TITLE
Java.Lang.IllegalArgumentException: 'order does not contain a valid category.' after Xamarin.Forms 4.4.0.991477

### ISSUE THREAD

**Issue by noxe** [xamarin/Xamarin.Forms#9185]
### Description
Hi,

i have updated my application to Xamarin.Forms 4.4.0 sr2 -  4.4.0.991477 - now the Android Application has an problem. I have a simple ContactPage where i set the IconImageSource to an FontImageSource. After the update i get following exception: 

Java.Lang.IllegalArgumentException: 'order does not contain a valid category.'

### Steps to Reproduce

This is my code:

App.Current.Resources.TryGetValue("FontAwesomeSolid", out object font);
var fontImageSource = new FontImageSource();
fontImageSource.Size = 24;
fontImageSource.FontFamily = (OnPlatform<string>)font;
fontImageSource.Glyph = FontAwesomeIcons.Filter;

toolbarItem.IconImageSource = fontImageSource;

### Actual Behavior

Java.Lang.IllegalArgumentException: 'order does not contain a valid category.'

 	0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal	C#
 	0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:120,4	C#
 	0x20 in Android.Runtime.DynamicMethodNameCounter.27	C#
 	0x12 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:157,13	C#
 	0x6E in Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod	C#
 	0x2C in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod	C#
 	0x70 in Android.Support.V7.View.Menu.MenuBuilder.Add	C#
 	0x4A in Xamarin.Forms.Platform.Android.ToolbarExtensions.UpdateMenuItems at D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\ToolbarExtensions.cs:43,6	C#
 	0x31 in Xamarin.Forms.Platform.Android.ToolbarExtensions.OnToolbarItemPropertyChanged at D:\a\1\s\Xamarin.Forms.Platform.Android\Extensions\ToolbarExtensions.cs:107,5	C#
 	0x35 in Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnToolbarItemPropertyChanged at D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:561,4	C#
 	0x12 in Xamarin.Forms.BindableObject.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:229,7	C#
 	0x2 in Xamarin.Forms.Element.OnPropertyChanged at D:\a\1\s\Xamarin.Forms.Core\Element.cs:353,4	C#
 	0x11B in Xamarin.Forms.BindableObject.SetValueActual at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:461,5	C#
 	0x17C in Xamarin.Forms.BindableObject.SetValueCore at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:397,5	C#
 	0x56 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:334,4	C#
 	0x5 in Xamarin.Forms.BindableObject.SetValue at D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:311,68	C#
 	0x7 in Xamarin.Forms.MenuItem.set_IconImageSource at D:\a\1\s\Xamarin.Forms.Core\MenuItem.cs:58,11	C#
>	0x4E in VenDoc.Views.ContactListViewPage.UpdateFont at 

### Basic Information

- Version with issue: 4.4.0.991477 (4.4.0 sr2)
- Last known good version: 4.4.0.991265 (4.4.0)
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0 
- Android Support Library Version: V7
- Nuget Packages:
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/158478/72275405-24ae0000-362e-11ea-883d-49711abb7633.png)

**Comment by PureWeen** [comment]
@noxe can you attach a reproduction? 

I'm trying to reproduce this issue but not having much luck

**Comment by noxe** [comment]
Sure - during preparing the repro i found that it is not related to the IconImageSource... Happens as soon as i add the syncfusion SfBackdropPage in combination with an navigationpage - so i dont know now if the problem is related to XF or Synfusion - sorry about this :(
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4061192/App1.zip)

**Comment by PureWeen** [comment]
@noxe  Thank you!!

I was thinking there was another actor here modifying the Menu that isn't playing well with the changes we made

**Comment by noxe** [comment]
thx for the Info - so i wait for more updates from you :)

**Comment by ianvink** [comment]
**Here's a simple repo:**

I'm getting the same issue after upgrading to 4.4.0.991477 on Android. I don't use SyncFusion.  Happens when I try to open modal navigation pages with ToolbarItems with Image Icon set like this:


			if (this.Navigation.ModalStack.IsEmpty())
			{
				await this.Navigation.PushModalAsync(
					new NavigationPage(
						new CreateEditNotePage(blah blah))
				);
			}

Page

	 <ContentPage.ToolbarItems>
		<ToolbarItem Name="Save" Order="Primary" Icon="tabbar_check.png" Text="Save" Priority="-1"
		             Command="{Binding CreateCommand}" AutomationProperties.Name="Create" />
		<ToolbarItem Name="Close" Order="Primary" Icon="tabbar_x.png" Text="Close" Priority="1"
		             Command="{Binding CloseCommand}" AutomationProperties.Name="Close" />
	</ContentPage.ToolbarItems>

If I remove the ToolbarItems, it works

**Comment by ianvink** [comment]
It seems to be around the Icon property as ToolbarItems with text only is fine.

**Comment by PureWeen** [comment]
Fixed here
https://github.com/xamarin/Xamarin.Forms/pull/9207

**Comment by ArihantBapna** [comment]
I'm having the same issue, but in my case it's whenever I try to make one of my pages a NavigationPage.
I have a Page which is a SfBackdropPage and every time I try doing:
`MainPage = new NavigationPage(new MyBackdropPage()); ` it gives me the same error
