### ISSUE TITLE
[Bug] [iOS] CollectionView EmptyView causes the application to crash

### ISSUE THREAD

**Issue by dsdilpreet** [xamarin/Xamarin.Forms#9196]
### Steps to Reproduce

1. When collection view empty template is added in attached code, application crashes on iOS but works fine in Android. When removed, the application does not crash.

### Expected Behavior
The application should not crash when empty view is present.

### Basic Information

- Version with issue: v4.4.0.991477
- Last known good version:
- IDE: Visual Studio 2019 v16.4.2
- Platform Target Frameworks: 
  - iOS:   iOS v13.3

### Screenshots
![image](https://user-images.githubusercontent.com/11010830/72314418-c4819180-36f3-11ea-8fc0-689871204368.png)

### Reproduction Link

See Attached file
[collection_view.txt](https://github.com/xamarin/Xamarin.Forms/files/4057348/collection_view.txt)

**Comment by hartez** [comment]
Still trying to figure out why this is crashing, but as a workaround try removing the `Padding` from the root `StackLayout` in your `EmptyView`.
