### ISSUE TITLE
[Bug] collectionview scrollbar visibility "default" on android.

### ISSUE THREAD

**Issue by heebaek** [xamarin/Xamarin.Forms#9197]
If i use VerticalScrollBarVisibility="Default" 
Scrollbar never appear. even when i scrolling.
i see this problem on android with latest stable release.

**Comment by StephaneDelcroix** [comment]
please provide more information:
- a sample project
- the version on which this used to work
- the broken version

thanks

**Comment by heebaek** [comment]
[scrollbar.zip](https://github.com/xamarin/Xamarin.Forms/files/4062504/scrollbar.zip)
i checked it with xamarin forms 4.3.0.908675, 4.4.0.991477
ios works fine but in android, never appear scrollbar.

**Comment by PureWeen** [comment]
@heebaek I'm pretty sure this is intentional

"Default" means just do whatever the platform default is.
On android that's to not show any scrollbars

If you set the scrollbars to `VerticalScrollBarVisibility="Always"`

Then they show up just fine
