### ISSUE TITLE
[Bug] Black screen after splashscreen

### ISSUE THREAD

**Issue by woemike** [xamarin/Xamarin.Forms#9199]
### Description
Sometimes, after splashscreen, a black screen of death is showing. The page loads behind this screen, however, you can't do anything, but to close the app. I have noticed that if you split the app with another app (multiview), the page which is supposed to appear is there and one can use the app without any problems.

Xamarin.Forms version 4.4.0.991477.

```csharp

  <!-- styles.xml main theme -->
  <style name="MainTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="windowNoTitle">true</item>
    <item name="windowActionBar">false</item>
    <item name="colorPrimary">#051623</item>
    <item name="colorPrimaryDark">#07263d</item>
    <item name="colorAccent">#cccbd8</item>
    <item name="windowActionModeOverlay">true</item>
    <item name="android:datePickerDialogTheme">@style/AppCompatDialogStyle</item>
  </style>

  <!-- styles.xml splash image -->
  <style name="splashscreen" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowBackground">@drawable/splash_background</item>
    <item name="android:windowNoTitle">true</item>
    <item name="android:windowIsTranslucent">false</item>
    <item name="android:windowIsFloating">false</item>
    <item name="android:backgroundDimEnabled">true</item>
  </style>

  <!-- MainActivity.cs -->
  [Activity(Label = "App Name", Icon = "@drawable/icon", Theme = "@style/splashscreen", MainLauncher = true...]


```

### Steps to Reproduce
Not easy to reproduce.

### Expected Behavior
After splashcreen, main page should appear and not a black screen.

### Actual Behavior
After splashcreen, main page should appear and not a black screen.

### Basic Information
- Version with issue: 4.4.0.991477
- Last known good version: -
- IDE: Microsoft Visual Studio Professional 2019, Version 16.4.2
- Platform Target Frameworks:
  - Android: 5.0, 7.1, 10.0
- Nuget Packages: Xamarin.Forms 4.4.0.991477
- Affected Devices: Samsung Galaxy S10, Samsung Galaxy S9, Various Samsung Tabs

### Workaround
No workaround.

**Comment by StephaneDelcroix** [comment]
this is... interesting

**Comment by AntRemo** [comment]
@woemike Do you have an animation at the start of your app? 

Just an Idea, my app starts with a fade-in animation and I used to experience this issue if the `AnimatorDurationScale` was set to 0.

I was able to get around it, but it required some changes.

**Comment by woemike** [comment]
Hello, @AntRemo. Thank you for the response. Yes, I do have an animation at the start. I have a workaround now: I am assigning an initial loading page to the start of the app acting as a transition between splashscreen and the actual content (main page) of my application. It is weird tho... I do not like this approach.

**Comment by ChetCromer** [comment]
@woemike Was your animation on the splash screen or a screen that immediately followed it?

Our app has this problem on SOME android devices but not all, and sometimes they even seem to correct themselves. Very bizzare. 

We have a static splash screen, but then our mainpage is a type of "please wait" with a spinning logo that displays while we attempt to connect to an internet server for configuration data. Was this your same scenario, and did inserting another filler page between the splash screen and the animated screen do it?

I suppose we could just take out the animation and say please wait and see if that resolves it, but I'd like to keep it if possible.

**Comment by Elinareso** [comment]
Hi, Is there a fix for this issue?, We are facing this problem in several devices and we actually do not know how to solve it.

**Comment by darrabam** [comment]
Maybe this is related, but my app was showing a black screen for a split second after the splash screen on some Android phones randomly. 
It turned out that this was triggered by the Dark mode activated on those phones. The solution was to disable dark mode by having this line as the first line in my MainActivity :: OnCreate method. 
`AppCompatDelegate.DefaultNightMode = AppCompatDelegate.ModeNightNo;`
