### ISSUE TITLE
[Bug] Xamarin Forms iOS CustomRenderer Entry PlaceHolder Padding Bottom

### ISSUE THREAD

**Issue by EdoardoCinelli** [xamarin/Xamarin.Forms#9208]
### Description
I have a project in xamarin forms and I'm working on the iOS build, I changed the font from the base one to Nexa. This led to change the size of the "g" and to create this problem that I am not able to solve. I have a custom renderer for the entries but I have not found any way on the net to correct the bottom padding. I have already tried many changes on the xaml of the page, on the custom renderer and on the style without solving the problem. I also read this but it didn't help me. Here I write my code to clarify the situation:

Style :

    <Style TargetType="cr:BorderlessEntry">
        <Setter Property="HeightRequest" Value="45"/>
        <Setter Property="TextColor" Value="Black"/>
        <Setter Property="PlaceholderColor" Value="Gray"/>
        <Setter Property="FontFamily" Value="{StaticResource NormalFont}"/>
    </Style>

    <Style x:Key="FrameEntry" TargetType="Frame">
        <Setter Property="BorderColor" Value="{StaticResource LightBlue}"/>
        <Setter Property="CornerRadius" Value="25"/>
        <Setter Property="Padding" Value="10,3,10,3"/>
        <Setter Property="Margin" Value="0"/>
    </Style>
Xaml Page:

<Frame Style="{StaticResource FrameEntry}">
    <cr:BorderlessEntry Placeholder="{x:Static res:AppResources.PLACE}" Text="{Binding Place}"/>
</Frame>
CS Custom Renderer:

   public class BorderlessEntryRenderer : EntryRenderer
    {
        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e);

            if (Control == null)
                return;

            Control.Layer.BorderWidth = 0;
            Control.BorderStyle = UITextBorderStyle.None;
            //Control.VerticalAlignment = UIControlContentVerticalAlignment.Fill;
            //Control.LeftView = new UIView(new CGRect(0, 0, 0, 0));
            //Control.LeftViewMode = UITextFieldViewMode.Always;
            //Control.RightView = new UIView(new CGRect(0, 0, 0, 0));
            //Control.RightViewMode = UITextFieldViewMode.Always;
        }
    }
Obviously if I try to write g inside the entry it is not cut!
### Screenshots
![m0qcjsqkfukv](https://user-images.githubusercontent.com/59912610/72420305-c6dcfd80-377e-11ea-87bd-bf5bf674c71a.png)
![8ox2lrswa3mr](https://user-images.githubusercontent.com/59912610/72420306-c6dcfd80-377e-11ea-9f68-92387ff42d69.png)

### Reproduction Link
https://drive.google.com/open?id=1J2FAbh_jjJ8JnURh_-C7jBXbr02xBBGD

https://stackoverflow.com/questions/59578779/xamarin-forms-ios-customrenderer-entry-placeholder-and-button-text-padding-botto

https://forums.xamarin.com/discussion/comment/400050#Comment_400050

**Comment by StephaneDelcroix** [comment]
thanks for this report. unfortunately we can not debug your own custom renderer, unless you're certain that there's an issue in the base class. in that case, feel free to send a pull-request.

**Comment by EdoardoCinelli** [comment]
The bug in the main class is : You can't use padding in the placeholder on iOS. If you want to change font you can't use Xamarin iOS.
