### ISSUE TITLE
DisplayAlert failure on Android since update to Xamarin.Forms 4.4.0.991477 or 4.4.991265

### ISSUE THREAD

**Issue by roman536** [xamarin/Xamarin.Forms#9214]
### Description
DisplayAlert crashes on Xamarin-Android (tested on 7.0 or 9.0)
since update to Xamarin.Forms 4.4.0.991477 or 4.4.991265 (Xamarin-UWP=OK).
Last OK for Xamarin-Android: 4.3.0.991250

### Steps to Reproduce

1. Clone or download provided repository sample (Reproduction Link).
Open sample with Visual Studio.
Set TestFirstMap.Android as StartUp Project.
Set Breakpoint on TestFirstMap.Shared - App.cs just before DisplayAlert.
There are 2 remotes differ in Xamarin.Forms version:
Crash_DisplayAlert - 4.4.0.991477
Proper_Message_DisplayAlert - 4.3.0.991250
2. To observe the failure set your branch to Crash_DisplayAlert remote.
The crash occurs on TestFirstMap.Android - MainActivity - OnCreate - LoadApplication.
3. To observe proper message set your branch to Proper_Message_DisplayAlert remote.
4. Run the app on Android device.

### Expected Behavior
Message using DisplayAlert without crash.

### Actual Behavior
Crash on DisplayAlert:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> Java.Lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

Sample code doesn't use Application Theme on Android.Manifest (empty).
### Basic Information

- Version with issue: 4.4.0.991477 or 4.4.991265
- Last known good version: 4.3.0.991250
- IDE: Microsoft Visual Studio Enterprise 2019 Version 16.4.3
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9.0 (Pie)  
  - UWP: Windows 10, version 1809   
- Android Support Library Version: API Level 28 (Pie) 
- Nuget Packages: (see sample repository)
- Affected Devices:
Smartphone Samsung A50 Android 9.0
Smartphone UleFone Power3s Android 7.1

### Screenshots
(none - debug sample)

### Reproduction Link
https://github.com/roman536/Xamarin-Eval-FirstMap.git

### Workaround
Back to Xamarin.Forms version 4.3.0.991250

**Comment by hartez** [comment]
The repro project is using `FormsApplicationActivity`; if I change it to use `FormsAppCompatActivity` (and add the missing styles), the alert displays without issue. So somehow we've broken alerts for legacy activities.

**Comment by softourS** [comment]
It still happens

**Comment by softourS** [comment]
Seriously, though. We need this functioning ASAP, please.

Thank you.

**Comment by roman536** [comment]
DisplayAlert works for me again on Android after update to Xamarin.Forms 4.4.0.991537 (published Thursday, January 23, 2020)

**Comment by mphill** [comment]
Proguard makes DisplayAlert force quit.  

I believe this is a duplicate of #9031 

Can anyone having this issue confirm turning off proguard fixes your issue?

**Comment by haiduong741** [comment]
> Proguard làm cho lực lượng DisplayAlert bỏ.
> 
> Tôi tin rằng đây là bản sao của [# 9031](https://github.com/xamarin/Xamarin.Forms/issues/9031)
> 
> Bất cứ ai có vấn đề này có thể xác nhận tắt proguard khắc phục vấn đề của bạn?

Turn off Proguard not worked. Only selected None in Linking but APK had been bigger size.
