### ISSUE TITLE
code behind grid layout - double height rows 

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9222]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/856906/code-behind-grid-layout-double-height-rows.html)._

---
I believe there is over thinking in the code behind regarding the Gridlength setting.

If the row definitions are set as follows:
            grid. RowDefinitions.Add(new RowDefinition { Height = new GridLength(2, GridUnitType.Star) });
            grid. RowDefinitions.Add(new RowDefinition { Height = new GridLength(2, GridUnitType.Star) });
            grid. RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Star) });

I get screenshot 1a.

If I set all the gridlengths  to 2, then I get screenshot 2a.

So if all the gridlengths  are set to the same, it assumes I mean 1 star, but if one is set differently it uses the entered values. 

Perhaps better to just use the values the coder enters. I need double height rows, and I now have to create a dummy row to get it to work.

---
#### Visual Studio Feedback System on 12/16/2019, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephaneDelcroix** [comment]
I'm sorry I don't understand your suggestion here. Feel free to rephrase, and ask for this ticket to be reopened.
