### ISSUE TITLE
When device time is set in the future, Xamarin.iOS apps crash on launch

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9223]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/881524/when-device-time-is-set-in-the-future-xamarinios-a.html)._

---
We can reproduce this with a brand new Xamarin.Forms app.
Use a device with the datetime automatically set to today and deploy the app to that device.
Manually set the device time to one year in the future or more
Launch the app - it immediately crashes.

---
#### Visual Studio Feedback System on 1/12/2020, 11:03 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by VladislavAntonyuk** [comment]
I think the issue with the Apple certificate, which is valid for 7 days.

**Comment by StephaneDelcroix** [comment]
please report that to Xamarin.iOS, but @VladislavAntonyuk guess seems right to me
