### ISSUE TITLE
Xaml intellisens is lost when using MergedDictionaries

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9224]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/884447/xaml-intellisens-is-lost-when-using-mergeddictiona.html)._

---
In Xamarin Forms, if you reference a global resource using StaticResouce you usually get intellisens:

<Button BakcgroundColor={StaticResource DictionoaryKey ... /> so the "DictionaryKey" will be autocompleted by VS.

But, when you organize your resource dictionaries in different files and merge them together, you lose intellisense so multiple files with merging feature is not usable as it introduces bigger problem than what it solves

---
#### Visual Studio Feedback System on 1/14/2020, 08:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MhAllan** [comment]
updates?

**Comment by mgoertz-msft** [comment]
@MhAllan Sorry about the lack of progress here. I have reopened the VS feedback ticket since this is about Visual Studio IntelliSense and not a Xamarin Forms runtime problem. Could you please attach a small repro project to the VS ticket that illustrates the problem? Thank you!

**Comment by MhAllan** [comment]
@mgoertz-msft I updated there. I am closing this

**Comment by mgoertz-msft** [comment]
@StephaneDelcroix, @samhouts, could one of you please close this? Thanks.
