### ISSUE TITLE
[Bug] [UWP] Entry.ClearButtonVisibility="Never" does nothing on UWP

### ISSUE THREAD

**Issue by JKennedy24** [xamarin/Xamarin.Forms#9229]
### Description
I have a Simple Entry like so:

`<Entry BackgroundColor="Blue" ClearButtonVisibility="Never"/>`

And if I click into the the entry box and type something in, the clear button is visible

Xamarin.Forms V4.4.0

### Expected Behavior

Clear button invisible

### Actual Behavior

Clear button is visible

**Comment by samhouts** [comment]
Duplicate of #8836
