### ISSUE TITLE
[Bug] Disabled RefreshView disables scrolling

### ISSUE THREAD

**Issue by Denrage** [xamarin/Xamarin.Forms#9232]
### Description
If you have a RefreshView with a ScrollViewer->StackPanel->Elements inside and "IsEnabled" on the RefreshView is set to "False" you can't scroll anymore on iOS. On Android everything works fine and the RefreshView don't try to refresh. This also happens if you have a command binded to the RefreshView and has the CanExecute set to false.
### Steps to Reproduce

1. Define RefreshView in XAML and put ScrollViewer with content in it
2. Set "IsEnabled" on the RefreshView on "False"
3. The content can't be scrolled anymore on iOS now

### Expected Behavior
The content can still be scrolled but you can't initiate the refresh
### Actual Behavior
The content can't be scrolled on iOS (nothing happens if you try to scroll)
### Basic Information

- Version with issue: 4.4.0.991477 and 4.5.0.142-pre1
- Last known good version: -
- IDE: Visual Studio 2019 Professional 16.3.9
- Platform Target Frameworks: 
- iOS: 13.2
- Android: 9.0
- UWP: -
- Android Support Library Version: 28.0.0.3
- Nuget Packages: -
- Affected Devices: -

### Reproduction Link
[RefreshViewReproduction.zip](https://github.com/xamarin/Xamarin.Forms/files/4071192/RefreshViewReproduction.zip)

### Workaround
Nothing found

**Comment by ChaseFlorell** [comment]
Not only can you not scroll, but you also cannot interact  (tap).
Set selection mode on a CollectionView and wrap it in a RefreshView. If you set `IsEnabled` to false, or `CanExecute()` returns false, you can no longer tap the items in the CollectionView.
