### ISSUE TITLE
[Bug] Button visual state "pressed" doesn't work on UWP

### ISSUE THREAD

**Issue by Estevete** [xamarin/Xamarin.Forms#9234]
### Description
Button visual state manager state `Pressed` does not work in UWP.
### Steps to Reproduce

1. Create a button with visual state manager with common states, including pressed, setting, for example, property TextColor to Red.
2. Launch in UWP and click (press) on the button
3. iOS and Android works, not UWP.

### Expected Behavior
Set the property to given value, as iOS & Android
### Actual Behavior
Doesn't set it
### Basic Information

- Version with issue: 4.4.0.991477
- Last known good version: -
- IDE: Visual Studio 2019 16.4.2
- Platform Target Frameworks: 
  - UWP:  18362 
- Affected Devices: Windows PC

**Comment by StephaneDelcroix** [comment]
could you please attach a repro project ? thanks
