### ISSUE TITLE
[Bug] macOS: First button

### ISSUE THREAD

**Issue by Suplanus** [xamarin/Xamarin.Forms#9241]
### Description
If the window is not activated a `Grid.Click` is not recognised.
`Button.Click` works.

### Steps to Reproduce
Make a Xamarin.Forms.Mac app and add this:
```xml
<Button
    HorizontalOptions="Center"
        BorderColor="Transparent"
    Text="Button"
        Clicked="Button_Clicked"
    VerticalOptions="StartAndExpand" >
</Button>
​
<Grid BackgroundColor="Transparent">
    <Grid.GestureRecognizers>
        <TapGestureRecognizer Tapped="Button_Clicked" />
    </Grid.GestureRecognizers>
    <Label
        HorizontalOptions="CenterAndExpand"
        Text="Grid"
        VerticalOptions="StartAndExpand" />
</Grid>
```

### Expected Behavior
Only need one click like with button.

### Actual Behavior
One click for activating window and a second to get the `Grid.Click` event.

### Basic Information

- Version with issue: 4.5 pre1

### Screenshots
![2020-01-17_07-56-21 (1)](https://user-images.githubusercontent.com/2002916/72612117-1e6c9c00-392c-11ea-8223-6495ca7c50a8.gif)

### Reproduction Link
I made a example [here](https://github.com/Suplanus/Xamarin.Bugs/blob/master/src/Xamarin.Bugs/Issue9241.xaml).

### Workaround
😢

**Comment by StephaneDelcroix** [comment]
the first click focuses the window, the second clicks the Gird. this is consistent with Mac behavior (e.g. safari)

**Comment by Suplanus** [comment]
OK.
Have you a hit for me how to workaround? The problem is that I have a Label which should be clickable at the first click.
