### ISSUE TITLE
[Bug] Unable to get SwipeView to work

### ISSUE THREAD

**Issue by JohnLivermore** [xamarin/Xamarin.Forms#9242]
### Description
In a simple CollectionView example, SwipeView is throwing an exception with Android.  Haven't tried iOS.

### Steps to Reproduce

1. Download the repo (https://github.com/JohnLivermore/SampleXamarinApp/tree/swipeview)
2. Run the repo

### Expected Behavior
SwipeView works

### Actual Behavior
Get an unhandled exception...

System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

### Basic Information

- Version with issue: 4.4
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
![image](https://user-images.githubusercontent.com/1489667/72618529-e4d26b80-3900-11ea-836a-edb217b7e0b0.png)

### Reproduction Link
https://github.com/JohnLivermore/SampleXamarinApp/tree/swipeview

**Comment by jsuarezruiz** [comment]
The SwipeView is in the Preview phase (we are working to improve it). To use it, you must opt-in by calling `Forms.SetFlags ("SwipeView_Experimental")` before calling `Forms.Init ()`.
![issue9242](https://user-images.githubusercontent.com/6755973/72623859-2802fd80-3946-11ea-994f-74508abf1130.gif)
The sample with the initialization change:
[Issue9242.zip](https://github.com/xamarin/Xamarin.Forms/files/4077469/Issue9242.zip)

**Comment by StephaneDelcroix** [comment]
thx for the answer @jsuarezruiz

**Comment by JohnLivermore** [comment]
Thanks for that.  I was setting the experimental flag, but not with the exact code you have.  I was using ...

            global::Xamarin.Forms.Device.SetFlags(new[] { "SwipeView_Experimental" });

However, now when I run I am getting this...

![image](https://user-images.githubusercontent.com/1489667/72630235-895fa800-3917-11ea-9907-7821a630dcce.png)

Is this because my device is older?  Here is what VS shows it to be...

![image](https://user-images.githubusercontent.com/1489667/72630256-95e40080-3917-11ea-8789-29a8c18b1cd8.png)

This is working in iOS however.  Just not Android (at least for my device).

**Comment by ignacioinnovo** [comment]
Dear Xamarin Forms Team,

If I use these two sentences (in this order) inside MainActivity:

global::Xamarin.Forms.Forms.SetFlags("CollectionView_Experimental");
global::Xamarin.Forms.Forms.SetFlags("SwipeView_Experimental");

I get an exception in Android with Xamarin Forms 4.5.0.495.

If I swap the order to this:

global::Xamarin.Forms.Forms.SetFlags("SwipeView_Experimental");
global::Xamarin.Forms.Forms.SetFlags("CollectionView_Experimental");

it works OK in a page where I have a CollectionView and a SwipeView.

**Comment by JohnLivermore** [comment]
I don't think CollectionView needs the CollectionView_Experimental any longer?

**Comment by samhouts** [comment]
@ignacioinnovo Please read https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags for more about experimental flags. If you call `SetFlags` more than once, you are actually overwriting the value you've previously set. Instead, you should call it once with all the flags you want enabled. And @JohnLivermore is correct. CollectionView is no longer experimental. Thanks!

**Comment by ignacioinnovo** [comment]
My mistake. I didn´t know that.
Thank you very much.
