### ISSUE TITLE
[Enhancement] Allow Shell Hamburger Icon to float ontop of page content

### ISSUE THREAD

**Issue by RyanGaudion** [xamarin/Xamarin.Forms#9243]
Be able to set Shell.NavBarIsVisible="False" but still have a nav-icon floating on top of content. Basically, push all content to the top of the screen and have a hamburger icon overlayed on top.

Refer to this question for more details:

https://stackoverflow.com/questions/59790108/xamarin-forms-shell-is-there-anyway-to-remove-the-navigation-bar-but-keep-the-ha

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
