### ISSUE TITLE
UWP ShellNavigating to Manually Registered Route Doesn't display

### ISSUE THREAD

**Issue by JohnGalt1717** [xamarin/Xamarin.Forms#9245]
### Description
If you create a UWP (I know beta) app and use Shell and in the App.xaml.cs register a route that isn't defined in the Shell markup and then navigate to that page, the page code (Constructor, onappearing etc) executes but it's never displayed in the UI.

### Steps to Reproduce

1. Create a shell app
2. Add UWP per the documentation
3. Add a custom route registration
3. Add a page in tabs and have a link on it to the custom route.

### Expected Behavior

Should display exactly like Android and iOS.

### Actual Behavior

Doesn't display.

### Basic Information

- Version with issue:  4.4.0.991477
- Last known good version: (none)
- IDE: VS.net 2019
- Platform Target Frameworks: 
  - UWP:   18362

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/8498
