### ISSUE TITLE
Binding Entry and Stepper to the same property can cause infinite loops and strange behavior.

### ISSUE THREAD

**Issue by SittenSpynne** [xamarin/Xamarin.Forms#9248]
### Description

If I bind a Stepper and an Entry to the same double property, they do not always seem to stay in sync and many strange behaviors occur.

### Steps to Reproduce

Representative XAML:

    <StackLayout>
        <Entry Text="{Binding DurationSeconds}" />
        <Label Text="{Binding DurationSeconds}" />
        <Stepper Minimum="1" Maximum="100" Increment="1" Value="{Binding DurationSeconds}" />
    </StackLayout>

Representative ViewModel:

    public class MainPageViewModel : INotifyPropertyChanged
    {

        private double _durationSeconds;
        public double DurationSeconds
        {
            get
            {
                return _durationSeconds;
            }
            set
            {
                if (value != _durationSeconds)
                {
                    _durationSeconds = value;
                    RaisePropertyChanged();
                }
            }
        }

        public MainPageViewModel()
        {
            DurationSeconds = 3;
        }

        private void RaisePropertyChanged([CallerMemberName]string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public event PropertyChangedEventHandler PropertyChanged;
    }

1. Start the application.
2. Tap the Entry and wait for the keyboard to appear.
3. Push backspace until the field is blank.
4. Type ".5".
5. The application freezes.

A handful of other quirks are described below under "actual behavior".

### Expected Behavior

I expect the value to be clamped up to 1 if I type a value less than 1, and clamped to 100 if I type a value greater than 100. 

### Actual Behavior

* Typing values greater than 100 such as 100.5 is allowed, and the values are not clamped. The stepper properly alters its button state properly. 
* Attempting to type a value like "0.5" usually properly clamps to 1. 
    * However, if you type ".", then use the arrows to add a 0 in front, then use the arrows to finish typing "0.5", the value will not clamp.
* If the first thing you type is ".5" after starting the app, an infinite loop begins:
    * It appears the Stepper tries to clamp the value to 1, but for some reason the Entry refuses to accept the new value and publishes ".5" as a newly-entered value. Then the Stepper and Entry fight over it forever.
* HOWEVER, if you type any amount of text, then clear it, then type .5, it "clamps" to 0.5. 
    * This is weird because in any other circumstance, typing "0" clamps up to 1.
    * In this state it seems typing any value below the minimum is allowed.

All of the above is true on multiple Android devices I've tried. On iOS, trying to type ".5" clamps to 0.5, which is still incorrect but better than crashing. But 100.5 won't clamp down to 100, although typing values like "300" will.

It feels like a bug, particularly the infinite loop since typing some amount of text will cause the behavior to change. 

### Basic Information

- Version with issue: Tested with Xamarin Forms 4.4.0.991477 and 4.2.0.848062.
- Last known good version: N/A
- IDE: Visual Studio for Mac 8.4.1 build 4
- Platform Target Frameworks: 
  - iOS:  11.3.1
  - Android: 9.0
  - UWP:  N/A
- Android Support Library Version: Whatever the default template includes
- Nuget Packages: N/A
- Affected Devices:

* Samsung Galaxy Tab Active 2
* Samsung Galaxy Tab 3
* Two prototype industrial Android devices I can't name
* iPhone 6

**Comment by VladislavAntonyuk** [comment]
Looks like we are executing OnPropertyChanged on binding even if new value is the same as the old value.

**Comment by StephaneDelcroix** [comment]
This is probably due to the use of double, and comparing them with `!=`. You should probably take some precision into account while comparing, see https://docs.microsoft.com/en-us/dotnet/api/system.double.equals?view=netframework-4.8 on how to do it.

I'm going to close this as the fix should end up in your VM implementation

**Comment by SittenSpynne** [comment]
I disagree and think you've been overeager to dismiss without trying it out.

I updated my code:

```
private double _durationSeconds;
public double DurationSeconds
{
    get
    {
        return _durationSeconds;
    }
    set
    {
        var diff = Math.Abs(value - _durationSeconds);
        Debug.WriteLine($"Trying {value}, diff is {diff}.");
        if (diff > 0.000001)
        {
            _durationSeconds = value;
            RaisePropertyChanged();
        }
    }
}
```

My result was a never-ending stream of:

```
Trying 0.5, diff is 0.5.
Trying 1, diff is 0.5. 
Trying 0.5, diff is 0.5.
...
```

I'll restate what seems to be happening: the Entry sets the property. The Stepper sees that and changes it back. For *some reason* in these circumstances, the Entry sees its text has changed and changes it *back* to .5, which starts the loop anew.

I further confirmed this by adding lines to print what the Entry thought its text was changing to. Things got weird there, but it might just be order of events mucking with me. It *looks like* what happens goes in this order:

* I type a character.
* The binding framework parses the text and tries to set the value 0.5.
* The Stepper sees the change, disagrees, and changes the value to 1.
* The Entry raises its TextChanged event, its current value is ".5".
* The Entry notices the first change event for DurationSeconds and updates its text to "0.5".
* The Entry notices the second change event for DurationSeconds and updates its text to "1".
* The Text change to "0.5" from a moment ago is noticed and the binding system sets the property.
* The Entry changes its text to "0.5".
* Things only get worse from here.

I'm solving this, for now, with some more complex code I hope to encapsulate into a component. It involves a VM with a Text and Value property and a behavior intended to "commit" the text to change the value only when the user either dismisses the keyboard or changes focus.

**Comment by SittenSpynne** [comment]
Actually I settled on a better solution, but I think the initial behavior is bizarre.

For this solution, I implemented the property to have "clamping" behavior, rather than letting the Stepper incidentally cause it. So now if you type ".5", the property is only set to 1, so both the stepper and the Entry end up seeing the same value and, more importantly, the Stepper only sees valid values.
