### ISSUE TITLE
[Bug] [UWP] FontImageSource Disappeares on UWP after screen lock for few seconds

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#9249]
### Description
The Image (and Button Image) that it's source is set to FontImageSource disappears on UWP after you lock the screen for few seconds (or just Ctrl + Alt + Del then Cancel after few seconds)

### Steps to Reproduce
1.  Create Xamarin forms app add UWP only, copy this code 
```Xaml
<Button Margin="10">
        <Button.ImageSource>
	    <FontImageSource FontFamily="Arial" Glyph="X"  Size="20"   Color="Blue"/>
	</Button.ImageSource>
</Button>
```
2. Ctrl + Alt + Del
3. Wait like 5 seconds (It is interesting that the issue will not appear if you cancel quickly)
4. Cancel 
5. You will see the images gone

### Expected Behavior
Images should still be showing

### Actual Behavior
Anything assigned to FontImageSource will disappear

### Basic Information
Latest everything
* It doesn't matter which UWP target it is.
* It doesn't matter if you use Image or Button or if you use custom fonts or not.

### Screenshots
![font-img-1](https://user-images.githubusercontent.com/13087546/72667252-e66d7200-3a6d-11ea-8116-ea8e6baf0130.PNG)
![font-img-2](https://user-images.githubusercontent.com/13087546/72667260-f6855180-3a6d-11ea-8ef0-311c581e59b1.PNG)

**Comment by kgrosche** [comment]
The problem is much bigger than i thought before.
I've created a sample APP using the master-detail template. In the about-page i placed a button as in the sample above. After resuming from standby, not only this button is not visible but everything else is also not visible. If i remove the button, everything world fine.
This problem needs a ** very urgent fix or workaround** for us, because we have a lot of customers who are affected by this issue!

**Comment by MhAllan** [comment]
@kgrosche I ended up creating my own button from a ContentView :( .. UWP is extremely buggy

**Comment by kgrosche** [comment]
@MhAllan i have the problem not only with button but with all those controls using Glyph. Our APP ist Multiplattform and its running well under iOS and Android. So today i have no idea what to do

**Comment by MhAllan** [comment]
@kgrosche hope they prioritise this issue next sprint .. XF is too slow evolution and seems still not production ready since 2014 .. 7 years already 😅

**Comment by BrayanKhosravian** [comment]
@bruzkovsky

**Comment by jdinnen** [comment]
I am still seeing this in 4.6.800

**Comment by DellaMoraWalter** [comment]
The problem doesn't seem to be solved.
In my project I updated Xamarin.Forms to version 4.7.0.1080, applying the "Steps to Reproduce" indicated by @MhAllan the buttons images disappear.

Before ctrl+alt+canc
![Buttons images before](https://user-images.githubusercontent.com/53078750/87307740-673b9100-c51a-11ea-9dfd-1500e4f0710a.PNG)

After ctrl-alt+canc and wait some seconds
![Buttons images after](https://user-images.githubusercontent.com/53078750/87307773-74588000-c51a-11ea-9bd3-66759d7e7151.PNG)

After mouse hover some images appear
![Buttons images after mouse hover](https://user-images.githubusercontent.com/53078750/87307798-81756f00-c51a-11ea-87d9-edfeed9cd9ae.PNG)

**Comment by MhAllan** [comment]
It is very disappointing that we do our best to make the issues clear and easy for you to reproduce and test, then you just come to close it without even test it!

**Comment by BrayanKhosravian** [comment]
@MhAllan this issue was closed automatically becaused i linked it to my pull request and it was merged. 
And i ofc tested this and it worked. 
We used a local nuget package with that fix and everything was fine for a month. I understand that you feel disappointed because i feel the same as i spend a whole day to fix this issue. But blaming the xf team or any contributor wont solve or refix this bug.
Maybe this is a regression issue?

**Comment by goh-chunlin** [comment]
This problem still exists even with Xamarin.Forms nightly build 5.0.1.2031.

Kindly re-open this issue.

**Comment by MhAllan** [comment]
@goh-chunlin open new one and link this thread is better for them to notice it

**Comment by codenexus2004** [comment]
Confirming on the 5.0.0.2012 release we still have the problem in our solution.  I'm fine to create a new issue if need be, but seems like it would be better to re-open.  I see it by minimizing or locking the screen.  Resize does fix it, but I'm not going to tell users "oh just resize it".  In our use-case it is a ToolbarItem with IconImageSource set to a FontImageSource set up using MaterialIcons.
