### ISSUE TITLE
The image does not change when the ImagesSource is updated[Bug][UWP]

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Xamarin.Forms#9251]
### Description
You can test the problem in the MainPage.xaml.cs file in our sample project.
https://github.com/BitooBit/BitooBitImageEditor
On Android and IOS, there is no such problem.

### Basic Information
- Platform Target Frameworks: 
  - UWP:

**Comment by WayaFlyfeather** [comment]
@dimonovdd Could you please describe in a bit more detail what the problem is, and how to make it happen? I tried running your sample project, but it wasn't immediately apparent to me what is supposed to happen/what I'm supposed to do to make it happen.

**Comment by dimonovdd** [comment]
@WayaFlyfeather I apologize. But the problem that bothered me was gone. I didn't change the code of my demo project, but I updated xamarin to the latest version.  I'm so sorry.

**Comment by WayaFlyfeather** [comment]
@dimonovdd Nothing to apologize for, glad to hear it worked out :)
