### ISSUE TITLE
[Bug] [Android] Adding SwipeView to a ListView causes graphical artifact 

### ISSUE THREAD

**Issue by bunstjan** [xamarin/Xamarin.Forms#9254]
### Description
Inserting SwipeViews to the front of a ListView causes the new items to be drawn over the previous item.

**Occurs on Android**.
**Does not occur on iOS.**

### Steps to Reproduce

1. Click "Add Item" button twice

### Expected Behavior

The previous item should be erased before drawing the new item at position 0. The previous item should then be drawn at position 1.

### Actual Behavior

The new item is drawn over the previous item at position 0. The previous item is also drawn at position 1.

### Basic Information

- Version with issue: 4.4.0.991477+451-sha.6fab98710-azdo.3372777
- Last known good version:
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  13.10.0.17
  - Android: 10.1.3.7
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android 9.0 API 28 emulator

### Screenshots

![Screenshot 2020-01-20 at 09 49 45](https://user-images.githubusercontent.com/44028736/72712118-ba83e680-3b6a-11ea-8e3e-cd8a4c07a3a1.png)
[SwipeViewBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4085276/SwipeViewBug.zip)

![Screenshot 2020-01-20 at 09 49 52](https://user-images.githubusercontent.com/44028736/72712135-bf489a80-3b6a-11ea-9ca6-019b95bb9c0f.png)

### Reproduction Link

https://github.com/bunstjan/swipeview-bug

**Comment by hartez** [comment]
This is fixed in 4.5.0.266-pre3.
