### ISSUE TITLE
[Bug] Picker: Oneway binding of SelectedItem never gets the value from source

### ISSUE THREAD

**Issue by Ulf-Ason** [xamarin/Xamarin.Forms#9256]
### Description
Using Oneway binding mode to bind SelectedItem of a Picker doesn't work. The source is not read and the Picker is showing the default text, i.e. the Title.
If changing binding mode to TwoWay the Picker will read the source and show the selected item.

### Steps to Reproduce

1. The page contain a Picker inside a Viewcell:
```
<Picker x:Name="XDevicePicker" Title="Select something"
                                        ItemsSource="{Binding XDeviceItems}"
                                        ItemDisplayBinding="{Binding Devicename}"
                                        SelectedItem="{Binding CurrentXSDeviceItem, Mode=OneWay}"/>
```
2. The sources is set in the ViewModels constructor
```
            XDeviceItems = new ObservableCollection<XDeviceItem>(XDeviceItem.GetAllItems());
            CurrentXDeviceItem = XDeviceManager.GetSelectedXDeviceItem;
```
3. 
The BindingContext of the ContentPage is set to the ViewModel inside OnAppearing()
 ```
protected override void OnAppearing()
        {
            base.OnAppearing();
            if (viewModel == null)
                BindingContext = viewModel = new XDeviceSettingsViewModel();
        }
```
### Expected Behavior
The Picker should read the value of the bounded source property and update the Picker GUI
### Actual Behavior.
The Picker never reads the source property.
### Basic Information

- Version with issue:
- IDE: VS2019 16.4.2
- Platform Target Frameworks: 
  - iOS:  Not tested
  - Android:8.1 (Oreo)
  - UWP:  Not tested

- Affected Devices (tested on): Samsung SM-G930F (8.0 Api 26) and Samsung SM T365 (5.1 Api22)

**Comment by samhouts** [comment]
@Ulf-Ason  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@Ulf-Ason  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by thhowl** [comment]
Any way to clean up these "no issue" posts, so they don't appear in searches?  (I realize I am just requesting help without offering any.)
