### ISSUE TITLE
[Bug] Unable to execute a POST request.

### ISSUE THREAD

**Issue by NaveedShaikh** [xamarin/Xamarin.Forms#9259]
### Description

I am receiving an error [Status: 404 Not Found] when I execute a POST request on Xamarin.Forms V4.4 and above. Moreover, the request executes successfully on Xamarin.Forms V4.3 and lower. Is there any extra piece that needs to be added to the header for v4.4?

### Steps to Reproduce

1.  Update to Xamarin.Forms 4.4
2. Execute a POST request.

### Expected Behavior

Returns true/false based on the credentials provided.

### Actual Behavior

Returns. 404

### Basic Information

- Version with issue: 4.4
- Last known good version: 4.3
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:   
- Nuget Packages:  Xamarin.Forms
- Affected Devices: iPhone

**Comment by VladislavAntonyuk** [comment]
404 is not found, is your endpoint valid?
Authentication error should be 401.

**Comment by NaveedShaikh** [comment]
The endpoints are valid. It works pretty fine on lower versions of X.F [4.3 and lower]. The authentication word didn't imply actual error but whilst logging in. Sorry for the confusion, I've updated the description to [Status: 404 Not Found].

**Comment by samhouts** [comment]
@NaveedShaikh  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@NaveedShaikh  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
