### ISSUE TITLE
[Bug] System.ObjectDisposedException in Android.FastRenderers.ImageRenderer

### ISSUE THREAD

**Issue by jurzer** [xamarin/Xamarin.Forms#9260]
I commented on a closed question, the problem is the same.
https://github.com/xamarin/Xamarin.Forms/issues/2164

I get the same error all the time. `ListView` with multiple rows. In the `DataTemplate` `ListView` nested another `ListView` with a `DataTemplate` which has an image, the image is loaded from the URL. Obviously, when you quickly scroll through the list, the images do not have time to load and the application crashes with this error.

I tested on an emulator and a real device. on the emulator, the error appeared on small lists, while the computer is heavily loaded and the emulator did not have enough resources for normal operation, that is, as if it is a weak smartphone.

The error occurs only when a `ListView` is nested in a `ListView` that has images in its template.

Xamarin Forms: 4.4.0.991265+398-sha.ee1eca51d-azdo.3306453
Platform Target Frameworks: Android 9.0
Android Support Library Version: 28.0.0.3
Affected Devices: Android 8.1

**Comment by jurzer** [comment]
I checked on another list with the same layout, but a small number of entries. If you close the page before the image appears, the app crashes with this error.

**Comment by samhouts** [comment]
@jurzer  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by PureWeen** [comment]
Fairly positive this is related to this issue

https://github.com/xamarin/Xamarin.Forms/issues/9136#issuecomment-572864811

Image/ImageButton still overrides InvalidateLayout for performance reasons so I couldn't just remove it there

We'll need to fix the dispose or figure out how to remove the InvalidateLayout overrides from Image and still not incur the cost of a layout

**Comment by samhouts** [comment]
@jurzer  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
