### ISSUE TITLE
[Visual] [Material]  Can't set TextColor and BackgroundColor for a disabled Material button

### ISSUE THREAD

**Issue by quentinR0bert** [xamarin/Xamarin.Forms#9261]
### Description
The color declarated in TextColor and BackgroundColor with a VisualStateManager doesn't is the colors seen
### Steps to Reproduce

1. Declare a Style for Buttons with a VisualStateManager and set some other colors for the background or the textColor
2. Set dynamically the button disabled 
3. The Color show is not the one declarated

### Basic Information

- Version with issue:4.4.0.991477

**Comment by samhouts** [comment]
@quentinR0bert  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by quentinR0bert** [comment]
Hi,
There is a sample with a default style setting the Background to Blue and the TextColor to White, with a VisualStateManager normally setting the background to Red and the TextColor to White. 

You will see that then we set the button disabled the background become kind of pink and the TextColor become Red.
[Forms44.zip](https://github.com/xamarin/Xamarin.Forms/files/4102651/Forms44.zip)

**Comment by samhouts** [comment]
closed by #9655

**Comment by quentinR0bert** [comment]
Hi !

Thanks for the fix, but the #9655 only fix for the TextColor and not the BackgroundColor
