### ISSUE TITLE
Keyboard Type with KeyboardFlag

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9267]
Hi,

Referring to this:

[https://forums.xamarin.com/discussion/comment/401067#Comment_401067](https://forums.xamarin.com/discussion/comment/401067#Comment_401067)

When you add Keyboard type with KeyboardFlag then Xamarin Forms will throw error

So what happens if you want Keyboard type as Email or URL with Suggestion keyboard flag as an example?

I suggest you make it something like this:

    <Entry.Keyboard Type="Email">
        <Keyboard x:FactoryMethod="Create">
            <x:Arguments>
                <KeyboardFlags>Suggestions</KeyboardFlags>
            </x:Arguments>
        </Keyboard>
    </Entry.Keyboard>

Thanks,
[Jassim](https://www.angelsemirates.com)

**Comment by jfversluis** [comment]
Hm not sure what this is about anymore sorry. Closing for now :)
