### ISSUE TITLE
[Bug] [Shell] Enable Binding of Items to Shell

### ISSUE THREAD

**Issue by Jabbah76** [xamarin/Xamarin.Forms#9268]
### Description
Currently shell items don't support bindings but we could add a layer here that attaches to a users source of items and then just keep the two in sync

### Original Description

I'm trying to set up a flyout menu in a viewmodel. This is successful in codebehind but not in the viewmodel.

Viewmodel binding is correctly set up using Windsor Castle. Other viewmodels in regular pages work fine.

### Steps to Reproduce

The code:

AppShell.xaml:

    <FlyoutItem x:Name="shellModules" 
                Title="Modules" 
                FlyoutDisplayOptions="AsMultipleItems" 
                Items="{Binding MenuItems}">
    </FlyoutItem>
</Shell>

The viewmodel:

```
public class AppShellViewModel
{
        public AppShellViewModel()
        {
            _menuItems = new ObservableCollection<ShellSection>();

            var section = new ShellSection
            {
                Title = "My title"
            };

            var content = new ShellContent
            {
                Content = new Pages.TempPage()
            };

            section.Items.Add(content);
            MenuItems.Add(section);
        }

        private ObservableCollection<ShellSection> _menuItems;

        public ObservableCollection<ShellSection> MenuItems
        {
            get => _menuItems;
            set
            {
                _menuItems = value;
                OnPropertyChanged("MenuItems");
            }
        }
}
```

### Expected Behavior

The Flyout menu is displayed with the menu items. Just like we would do this in codebehind using:
shellModules.Items.Add(section);

### Actual Behavior

See screenshot

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991265
- IDE: Visual Studio Mac
- Platform Target Frameworks:
  - Android: 9.0
- Android Support Library Version: 28.0.0.3

### Screenshots

![image](https://user-images.githubusercontent.com/58596571/72817807-b3440200-3c6a-11ea-9395-82987efcb73b.png)

### Workaround

Setting up the menu in code behind

**Comment by Jabbah76** [comment]
As an addition, binding to a simple text property works fine:

    <Shell.FlyoutHeader>
        <Grid HeightRequest="150">
            <Label Text="{Binding MyText}"
                   HorizontalTextAlignment="Center"
                   VerticalTextAlignment="Center" />
        </Grid>
    </Shell.FlyoutHeader>

```
public string MyText
{
    get => "My header!";
}
```

**Comment by PureWeen** [comment]
@Jabbah76 I edited your description a little bit and reshaped this as an enhancement. 

Currently Shell doesn't support binding to Items. If you would currently like to enable this behavior I would recommend using a converter and then via the converter you can sync the *Items* collections to your collections inside your VM

**Comment by idzikovski** [comment]
> @Jabbah76 I edited your description a little bit and reshaped this as an enhancement.
> 
> Currently Shell doesn't support binding to Items. If you would currently like to enable this behavior I would recommend using a converter and then via the converter you can sync the _Items_ collections to your collections inside your VM

Hello @PureWeen . Could you please elaborate a bit on how this converter would work. Or maybe just point me in the right direction please.

**Comment by nzcoward** [comment]
It's possible to bind *most* items in the shell. I'm still working through the first page binding without specifying the bindingcontext in the xaml, but the menu items are usable. The individual menu item templates bind to commands on their BindingContexts.

If you do not have a single ShellContent in the main content of the AppShell, the UI breaks completely, and adding FlyoutItem elements will override anything you've bound in Shell.FlyoutContent.

It requires playing with some styling, because there are some quirks.

```xaml
<Shell.FlyoutContent>
	<Grid BackgroundColor="{DynamicResource FlyoutBackgroundColor}">
		<CollectionView
			BindingContext="{Binding MainMenuViewModel}"
			ItemsSource="{Binding NavItems}"
			ItemTemplate="{StaticResource IconMenuItem}">
		</CollectionView>
	</Grid>
</Shell.FlyoutContent>

<ShellContent x:Name="BlankPage" Route="Landing" ContentTemplate="{DataTemplate local:BlankPage}"/>
```

**Comment by BaggioGiacomo** [comment]
I think they have fixed this! In your `appshell.xaml` you can add:
 ``` <Shell.BindingContext>
        <viewmodels:MainPageViewModel />
    </Shell.BindingContext> ```
By doing this you can bind methods that are in your ViewModel class using Commands.
⚠️ Remember to add `xmlns:viewmodels="clr-namespace:<SolutionName>.ViewModels"` ⚠️

**Comment by AbstractionsAs** [comment]
Hmm.. I'm looking to mix and match a few items in the flyout. Essentially, a list of dynamic items in the middle of the list of regular shellitems (.net MAUI).

This is not supported?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
