### ISSUE TITLE
SwipeItem Crash in iOS when Text = null

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#9271]
### Description
When the **Text** is not set in a **SwipteItem** and image bound to a **FontImageSource**, iOS will crash with a null exception.

Simply adding a **Text=" "** will work as a workaround

### Steps to Reproduce
    <SwipeItem      IconImageSource="{StaticResource TrashCanImage}"
                       BackgroundColor="{DynamicResource DeleteButtonColor}" />

**Using**

      <OnPlatform x:Key="ImageFontAwesomeFontFamily" x:TypeArguments="x:String"
                Android="fontawesome.ttf#Font Awesome 5 Pro"
                iOS="FontAwesome5Pro-Regular" />

       <FontImageSource 
         x:Key="TrashCanImage" 
         Size="34"
         FontFamily="{StaticResource ImageFontAwesomeFontFamily}"
         Glyph="{x:Static local:FontAwesomeFont.Trash}"/> 

### Expected Behavior
Works
### Actual Behavior
Crashes
### Basic Information
`"  at UIKit.UIStringDrawing.StringSize (Foundation.NSString This, UIKit.UIFont font) [0x00068] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIStringDrawing.g.cs:230 \n  at UIKit.UIStringDrawing.StringSize (System.String This, UIKit.UIFont font) [0x00007] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIKit/UIStringDrawing.cs:65 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.UpdateSwipeItemInsets (UIKit.UIButton button, System.Single spacing) [0x00067] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:393 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.CreateSwipeItem (Xamarin.Forms.SwipeItem formsSwipeItem) [0x00051] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:354 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.UpdateSwipeItems () [0x00103] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:311 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.ProcessTouchMove (CoreGraphics.CGPoint point) [0x00083] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:511 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.HandleTouchInteractions (Xamarin.Forms.GestureStatus status, CoreGraphics.CGPoint point) [0x00021] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:469 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.HandleTouchInteractions (Foundation.NSSet touches, Xamarin.Forms.GestureStatus gestureStatus) [0x0002a] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:458 \n  at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.TouchesMoved (Foundation.NSSet touches, UIKit.UIEvent evt) [0x00000] in D:\\a\\1\\s\\Xamarin.Forms.Platform.iOS\\Renderers\\SwipeViewRenderer.cs:208 \n  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)\n  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIKit/UIApplication.cs:86 \n  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIKit/UIApplication.cs:65 \n  at Max.iOS.Application.Main (System.String[] args) [0x00001] in C:\\x\\Mobile\\Max.iOS\\Main.cs:14 "`

- Version with issue:
  - iOS:  Newest
 

 
### Workaround
Add a blank to Text  (Text=" ")

**Comment by jsuarezruiz** [comment]
This issue should be fixed with https://github.com/xamarin/Xamarin.Forms/pull/8822
