### ISSUE TITLE
[Bug] Webview on iOS opens iframe in the browser automatically

### ISSUE THREAD

**Issue by srdmnc** [xamarin/Xamarin.Forms#9274]
### Description
The webview on iOS opens the iframe _(which is embedded in the page source)_ in the browser instead of showing it in the webview itself. 
### Steps to Reproduce

1. Add a WebView
2. Link a WebView to a webpage with iframes in it.
3. Run the app in an iOS device / simulator

### Expected Behavior
The webview will properly display the web page with the iframe on it.

### Actual Behavior
The webview opens a tab for each iframes in the browser.  The section where the iframe should be in the webpage is now blank.

### Basic Information

- Version with issue: 4.4.0.991477
- Last known good version:
- IDE: VSMac
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 9.0 
- Android Support Library Version: N/A
- Nuget Packages: none
- Affected Devices: iOS devices

**Comment by samhouts** [comment]
@srdmnc  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by srdmnc** [comment]
Hi @samhouts, upon review, we found that the bug was caused by a misplaced function inside our custom WebviewNavigated listener. I will close this now. Thank you for the replies.

**Comment by Yceali** [comment]
Hi I am having a same issue can you explain how did you resolve it @srdmnc
