### ISSUE TITLE
[Bug] On buttons, iOS adds ellipses when text is long but Android does not

### ISSUE THREAD

**Issue by rscholey** [xamarin/Xamarin.Forms#9275]
The text in Android button is not having ellipses added but in iOS these are added when the text is longer than can fit in a button

Android:

![Screenshot_20200121-082529_20200121_082544434](https://user-images.githubusercontent.com/39233783/72883771-e1474600-3d3f-11ea-965f-adc82d27a426.jpg)

iOS:

![iiiid](https://user-images.githubusercontent.com/39233783/72885498-07bab080-3d43-11ea-9375-509d68b8c871.png)

Noticed with XF 4.4.0.99 but I think it's been a problem for a long time.

**Comment by samhouts** [comment]
@rscholey Which behavior would you prefer? Would it be better if you could choose?

**Comment by rscholey** [comment]
I assume the behavior with the ... would be what's intended.  There are other issues I believe with padding of Android buttons.  Perhaps this is related or could be looked into at the same time. 

https://github.com/xamarin/Xamarin.Forms/issues/9122
https://github.com/xamarin/Xamarin.Forms/issues/9113

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/3106
