### ISSUE TITLE
Symbols are missing after Windows-Resume

### ISSUE THREAD

**Issue by kgrosche** [xamarin/Xamarin.Forms#9277]
I have a Multiplattform app in Xamarin.forms for iOS, Android and UWP. I'm using materialdesignicons-webfont.ttf for all my symbols. If the windows goes in standby mode and resume after that,  symbols wich are assigned as StaticResource or DynamicResource are missing.

`

<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:SymbolTest"
             x:Class="SymbolTest.MainPage">

    <ContentPage.Resources>
        <ResourceDictionary>
            <OnPlatform x:Key="MaterialFontFamily" x:TypeArguments="x:String">
                <On Platform="UWP" Value="Assets/Fonts/materialdesignicons-webfont.ttf#Material Design Icons" />
            </OnPlatform>
        </ResourceDictionary>
    </ContentPage.Resources>

    <StackLayout>
        <Label Text="&#xf844;"  HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" >
            <Label.FontFamily>
                <OnPlatform x:TypeArguments="x:String">
                    <On Platform="UWP" Value="Assets/Fonts/materialdesignicons-webfont.ttf#Material Design Icons" />
                </OnPlatform>
            </Label.FontFamily>
        </Label>

        <Button Grid.Column="1" x:Name="btnSearch" BackgroundColor="LightBlue" >
            <Button.ImageSource>
                <FontImageSource FontFamily="{StaticResource MaterialFontFamily}"  Size="36" Glyph="&#xf349;" Color="SlateGray" />
            </Button.ImageSource>
        </Button>

    </StackLayout>

</ContentPage>

`

The ButtonImage ist missing the Label.Text is not missing
### Expected Behavior

The Image on the Button should be existing after Resume

### Actual Behavior

The Image of Button is not existing after resume from standby. The image on the Label is existing.

### Basic Information

- Version with issue:
- Last known good version: unknown
- IDE: VisualStudio 2017 5.9.19
- Platform Target Frameworks: 
  - UWP:   
- Nuget Packages:
  - Xamarin.Forms: 4.4.0.991477
- Affected Devices:
  - all

**Comment by MitchBomcanhao** [comment]
possibly related to #9249 ?

**Comment by kgrosche** [comment]
yes, it's the same Problem as [#9249](https://github.com/xamarin/Xamarin.Forms/issues/9249)

**Comment by PureWeen** [comment]
Duplicate
