### ISSUE TITLE
[Bug] [Android] ToolbarItem icon not showing when loaded from embedded resource

### ISSUE THREAD

**Issue by pab6655** [xamarin/Xamarin.Forms#9278]
### Description
Icons of primary ToolbarItems are not shown anymore. The problem seems to occur only on android when the image is loaded from embedded resource. Its not permanent - there seems to be a low probability that it is shown correctly. 

### Steps to Reproduce
The attached reproduction project is the Xamarin Forms ToolbarItem demo where the image source was changed to load the image from embedded resource.

1. Launch the android app.
2. Open one of the demo pages
3. (optional) click the button multiple times. With a low probabilty the icon for the first ToolbarItem gets displayed otherwise only the text is shown.

### Expected Behavior
The icon gets displayed.

### Actual Behavior
Most of the time only the text is shown.

### Basic Information

- Version with issue: 4.4.0.991477
- Last known good version: 4.4.0.991265
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: Xamarin.Android SDK 10.1.3.7
- Android Support Library Version: 28.0.0.3
- Nuget Packages:
- Affected Devices:

### Screenshots
![20200122](https://user-images.githubusercontent.com/49695327/72892219-46864180-3d16-11ea-8f57-e7242eaddc1f.png)

### Reproduction Link
[Xamarin_Forms_ToolbarItem_Demos.zip](https://github.com/xamarin/Xamarin.Forms/files/4097036/Xamarin_Forms_ToolbarItem_Demos.zip)

**Comment by samhouts** [comment]
probably caused by #8889
