### ISSUE TITLE
[Bug] Unable to set ItemsLayout on CarouselView via a Style

### ISSUE THREAD

**Issue by mjfreelancing** [xamarin/Xamarin.Forms#9280]
### Description
I have two CarouselViews that are practically identical so I'm trying to create a Style. When taking this approach, the `ItemsLayout` property isn't applied. The only way I can get `ItemsLayout` to work is to explicitly define it on each CarouselView.

### Steps to Reproduce
Taking these definitions:
```
<ContentPage.Resources>
  <ResourceDictionary>
    <LinearItemsLayout
      x:Key="CarouselItemsLayout"
      ItemSpacing="15"
      Orientation="Horizontal" />
    <Style x:Key="CarouselStyle" TargetType="CarouselView">
      <Setter Property="PeekAreaInsets" Value="40" />
      <Setter Property="ItemsLayout" Value="{StaticResource CarouselItemsLayout}" />
    </Style>
  </ResourceDictionary>
</ContentPage.Resources>
```
And then creating the CarouselView like this does not apply the `ItemsLayout`
```
<CarouselView
  ItemsSource="{Binding LightItems}"
  Style="{StaticResource CarouselStyle}">
  <CarouselView.ItemTemplate>
    <DataTemplate>
      <Label Text="Sample text" />
    </DataTemplate>
  </CarouselView.ItemTemplate>
</CarouselView>
```
But this does work:
```
<CarouselView
  ItemsLayout="{StaticResource CarouselItemsLayout}"
  ItemsSource="{Binding LightItems}"
  Style="{StaticResource CarouselStyle}">
  <CarouselView.ItemTemplate>
    <DataTemplate>
      <Label Text="Sample text" />
    </DataTemplate>
  </CarouselView.ItemTemplate>
</CarouselView>
```

### Expected Behavior
I can't find any examples to determine if I'm doing it incorrectly, and I'm relatively new to XF and XAML, but I feel the `ItemSpacing` of 15 should be applied.

### Actual Behavior
The items within the CarouselView have no space between them.

### Basic Information
- Version with issue: 4.4.0.991477

### Screenshots
The top Carousel is incorrect. The bottom Carousel is as expected.
![image](https://user-images.githubusercontent.com/17043225/72902910-5dfa1480-3d80-11ea-9441-ed0103089c8c.png)

### Workaround
Explicitly set the `ItemsLayout` on each CarouselView.

**Comment by PureWeen** [comment]
@mjfreelancing ItemsLayout isn't a bindable property so it doesn't work with styles

I'm not sure the specific reason why it's not bindable

@rmarinho or @hartez can maybe speak to the choice there?

**Comment by rmarinho** [comment]
We are actually taling on removing the ItemsLayout thing and maybe just have the Orientation on CarouselView

**Comment by mjfreelancing** [comment]
@rmarinho so if ItemsLayout is removed, does that mean *everything* associated with it would also be on the CarouselView (I'm using ItemSpacing, SnapPointsAlignment, SnapPointsType). I don't mind this, it would certainly fit in better with my styles.
