### ISSUE TITLE
[Bug] Setting the Position on CarouselView works visually but then resets to previous value

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9281]
### Description

When you set the position on the CarouselView the CarouselView correctly forwards to the right place in the CarV but then the Position variable gets reset back to what it originally was

### Steps to Reproduce

1. run repro
2. click button
3. see labels

The repro just increments the position by 10 every time you click it. You'll notice the label that keeps track of the Position value resets back to zero and the label that increments every time PositionChanged is fired increments twice. It should only increment once

### Expected Behavior
PositionChanged  should only fire once when you set the position and the CarV.Position should retain whatever value you set it to

### Actual Behavior
PositionChanged fires twice and Position gets set to new value and then resets back to original value

### Basic Information

- Version with issue: 4.5 pre1

### Reproduction Link
[App15.zip](https://github.com/xamarin/Xamarin.Forms/files/4098524/App15.zip)

**Comment by rmarinho** [comment]
This is fixed on the latest release of 4.5-pre4
