### ISSUE TITLE
[Bug] When using a layout with a Corner Radius it's not possible to remove the orange background from a Selected CollectionView Element

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9282]
### Description

On Android if you clip the top level layout at all so the cell peaks through then you will see Orange or whatever ColorActivatedHighlight  is set to

### Steps to Reproduce

1. Run repro
2. click on rows

### Expected Behavior
I should have some cross platform mechanism to influence the background color of the Cell on Android without having to change the ColorActivatedHighlight value on Android

### Actual Behavior

Any row I click on has orange peaking out and I have to make a platform change to resolve

### Basic Information

- Version with issue: 4.5 pre1

### Screenshots
![image](https://user-images.githubusercontent.com/5375137/72916988-3c594880-3d00-11ea-93af-da363cbb89dd.png)

### Reproduction Link
[App15.zip](https://github.com/xamarin/Xamarin.Forms/files/4098744/App15.zip)

### Workaround

set ColorActivatedHighlight on the native android platform

**Comment by blieven1** [comment]
Same issue happens in iOS
