### ISSUE TITLE
[Spec]  [Shell] SearchBar background color customization

### ISSUE THREAD

**Issue by samhouts** [xamarin/Xamarin.Forms#9285]
# Shell SearchBar background color customization

See #6298, #6239. See https://forums.xamarin.com/discussion/comment/383797/#Comment_383797

Further spec TBD

# API

### Properties

| API | Description |
| ------------- | ------------- |
| [name] | Gets or sets [description]. |

### Events

| API | Description |
| ------------- | ------------- |
| [name] | [API documentation/description] |
 
# Scenarios

## C# Example
```csharp
var thing = new MyNewControl();
thing.BeAwesome = true;
thing.Color = Color.Cornsilk;
```

## XAML Example
```xaml
<MyNewControl x:Name="thing" BeAwesome="true" Color="Cornsilk" />
```

## CSS Example
```css
MyNewControl {
     color: Cornsilk;
}
```

# Backward Compatibility

Minimum API levels?
Breaking changes?
Unsupported platforms?

# Difficulty : [low/medium/high]

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
