### ISSUE TITLE
[Bug] CollectionView leaks when binding 

### ISSUE THREAD

**Issue by hulluP** [xamarin/Xamarin.Forms#9288]
### Description
When binding Collection view to a ObservableCollection the items of the collection stay in memory. See profiling see screenshot
Even removing the binding when the view disappears does not solve the issue. When the binding is not added the code does not introduce the memleak.
### Steps to Reproduce
1. clone the repo https://github.com/hulluP/CollectionViewTest/tree/MemLeakIssue branch memleak
2. open profiler
3. when app has started click on button "click" to launch the view with the collection view
4. click on back button to close view
5. repeat steps 3 and 4 multiple times
6. the profiler will show multiple items of the collectionViewTestX, ViewImage .... 

### Expected Behavior
when view closes all controls release their bindings and the objects can be collected by the GC

### Actual Behavior
when CollectionView gets popped it does not release the binding

### Basic Information

- Version with issue: Xamarin.Forms 4.4.09
- Last known good version: -
- IDE: Visual Studio Enterprise
- Platform Target Frameworks: iOS , Android
  - iOS:  13.3
  - Android: API28 
- Nuget Packages: Xamarin.Forms 4.4.09
- Affected Devices: iOS ,Android

### Screenshots
<img width="731" alt="Screenshot 2020-01-23 at 05 41 43" src="https://user-images.githubusercontent.com/46395952/72957608-754af900-3da4-11ea-8e71-ef935c7e6fb7.png">

### Reproduction Link

https://github.com/hulluP/CollectionViewTest/tree/MemLeakIssue

**Comment by PureWeen** [comment]
Possibly related

https://github.com/xamarin/Xamarin.Forms/issues/11819
