### ISSUE TITLE
[Bug] CollectionView cells overlapping on iOS

### ISSUE THREAD

**Issue by jopmiddelkamp** [xamarin/Xamarin.Forms#9289]
### Description
The collection view is rendering some cells over/under other cells on iOS 12.x. When scrolling the cells out of the screen and back it'll show the cells correctly.

### Steps to Reproduce
Clone the Git repo: https://github.com/Baseflow/collection-view-bug
1. Deploy the app;
2. Click the hamburger icon;
3. Click the about button in the menu.

In the sample the problem is solvable by adding the safe area to the navigation bar grid padding. But in our case it's not solving the problem.. So it's not a work around for us.. But at this moment we experience exactly the same behaviour in our project as in the reproduction GitHub repo link.

### Expected Behavior
Showing no cells over/under other cells.

### Actual Behavior
Showing some cells over/under other cells.

### Basic Information
- Version with issue: 4.4.0.991477
- Last known good version: N/A
- IDE: VS4Mac
- Platform Target Frameworks:
  - iOS:  12.x
- Nuget Packages:
  - Xamarin.Forms 4.4.0.991477
  - MvvmCross 6.4.2
  - MvvmCross.Forms 6.4.2
- Affected Devices:
  - iOS emulators using version 12.x

### Screenshots
![ScreenRecording2020-01-22at21470](https://user-images.githubusercontent.com/1774351/72958682-77c84580-3dda-11ea-8c42-761353180268.gif)

### Reproduction Link
https://github.com/Baseflow/collection-view-bug

### Workaround
N/A

**Comment by giusepe** [comment]
I'm having this same issue with Forms 4.4.0.991265

**Comment by winterdouglas** [comment]
Happens for me as well, Forms latest.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9000
