### ISSUE TITLE
[Bug] Unwanted border is drawn in Xamarin.Forms.iOS 

### ISSUE THREAD

**Issue by Sivaraman761** [xamarin/Xamarin.Forms#9290]
### Description

We have a use custom view for our project. We have extended the Forms view and write the custom view. At the time in Xamarin.Forms.iOS unwanted borders are drawn. But working fine in Forms. Android and Forms.UWP. We have reproduced this issue in a simple sample and attached the screenshots for your reference.

**Custom view structure:**

    public partial class CellEditTemplate : ContentPage
    {
        CustomGrid customgrid;
        HeaderView headerView;
        public CellEditTemplate()
        {
            InitializeComponent();
            customgrid = new CustomGrid();
            headerView = new HeaderView();

            for (int i = 1; i <= 5; i++)
            {
                Grid grid = new Grid();
                grid.RowDefinitions.Add(new RowDefinition { Height = new GridLength(1, GridUnitType.Auto) });
                grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Auto) });
                grid.Children.Add(new Label() { Text = "Label" }, 0, 0);
                grid.Children.Add(new Label() { Text = "Image" }, 0, 1);

                headerView.Children.Add(new ContentViewExt() { Content = grid });
            }
            customgrid.Children.Add(headerView);
            this.Content = customgrid;
        }
    }

    // Custom view Extend from Layout<View>. ContentViewExt is a child of this.
    public class HeaderView : Layout<View>
    {
        public HeaderView()
        {
        }

        protected override void LayoutChildren(double x, double y, double width, double height)
        {
            if (this.Children.Count > 0)
            {
                x = 0;
                for (int i = 0; i < this.Children.Count; i++)
                {
                    (this.Children[i] as ContentView).Layout(new Rectangle(x, y, this.Width / 5, 100));
                    (this.Children[i] as ContentView).BackgroundColor = Color.White;
                    x += this.Width / 5;
                }
            }
        }
    }

    // Custom contentView, we have write the Platform renderer for the view and override the Draw method and call base.

    public class ContentViewExt : ContentView
    {
        public ContentViewExt()
        {

        }
    }

    // Custom Grid is the base view. HeaderView is a child of this.

    public class CustomGrid : Grid
    {
        public CustomGrid()
        {

        }
    }

    [assembly: ExportRenderer(typeof(ContentViewExt), typeof(ContentViewExtRenderer))]
    namespace EditTemplate.iOS
    {
        // Write the platform renderer for the ContentViewExt and Override the Draw method.
        public class ContentViewExtRenderer : VisualElementRenderer<ContentViewExt> 
        {
            public override void Draw(CGRect rect)
            {
                base.Draw(rect);
            }
        }
    }

### Steps to Reproduce

1. Run the sample in Xamarin.Forms.iOS 
2. Simulator version 13.1 and Xcode version 11.1

### Expected Behavior
The unwanted border does not draw. 

### Actual Behavior
The unwanted border is drawn.

### Basic Information

1. Xamarin.Forms version 3.6.0.344457
2. Simulator version 13.1
3. Xcode version 11.1

### Screenshots

![With issue](https://user-images.githubusercontent.com/35529145/72962458-6848fc80-3dda-11ea-9c26-062848300b12.png)
![without issue](https://user-images.githubusercontent.com/35529145/72962459-68e19300-3dda-11ea-9b64-21a4fc10bb63.png)
### Reproduction Link

[Border issue.zip](https://github.com/xamarin/Xamarin.Forms/files/4101575/Border.issue.zip)

### Workaround

1. If I remove the Draw Override from platform renderer the border does not draw.
2. If I write the Platform renderer Extend form ViewRenderer inside of using VisualElementRenderer, the border does not draw.
3. if I set the  BackgroundColor as Transparent to ContentViewExt this issue does not Occurs.

**Comment by samhouts** [comment]
@Sivaraman761 Do you need to override Draw? We don't usually recommend that because it is intensive and subverts a lot of the native and Xamarin.Forms code.

**Comment by Sivaraman761** [comment]
Hi @samhouts  

Yes, we need to Override the Draw. Because here, we draw the border to the Datagrid. So we need to override the Draw.

**Comment by PureWeen** [comment]
@Sivaraman761  the border comes from the frame

You can turn off the shadow and set the border to transparent if you don't want it to show up

```C#
 frame.HasShadow = false;
                frame.BorderColor = Color.Transparent;
```

If I'm talking about the wrong border then can you include a screen shot with the above settings and what is still incorrect?

**Comment by Sivaraman761** [comment]
Hi @PureWeen 

I have checked your suggestion.  HasShadow and BorderColor this is a property for Xamarin.Form.Frame, but we do not use the Frame in our case. we have used the ContentView and write the platform renderer for that ContentView. So we cannot set that two property which is you suggest. Can you please check the attached sample.

Thanks & Regards,
Sivaraman S
