### ISSUE TITLE
[Bug] VideoPlayer shown in behind the parent view instead of Top in Xamarin Forms UWP. 

### ISSUE THREAD

**Issue by KarthikRaja26** [xamarin/Xamarin.Forms#9297]
### Description
We have added a Video Player to the child of the grid and added this grid to the child of native Popup. In that when I try to show the video player in full screen the video is shown behind the Popup instead of above.

### Steps to Reproduce

1. Run the attached sample
2. Now trigger the fullscreen button on Video Player.
3. Note Video Player is shown behind the popup.

### Expected Behavior
Video should be shown above the Popup.
### Actual Behavior
Video shown behind the popup.
### Basic Information

- Last known good version: Dont know
- Platform Target Frameworks:  
  - UWP:  
- NuGet Packages: Xamarin Forms Version  4.4.0.99147 
- Affected Devices: UWP 

### Screenshots

![image](https://user-images.githubusercontent.com/46777511/72987760-0fe12180-3e11-11ea-8794-6d85262cd28f.png)

### Reproduction Link
[PoupWithVideoPlayer.zip](https://github.com/xamarin/Xamarin.Forms/files/4103248/PoupWithVideoPlayer.zip)

### Workaround

No

**Comment by KarthikRaja26** [comment]
Any update on this ?

**Comment by PureWeen** [comment]
@KarthikRaja26 I don't think this is a Forms problem but more of how you are defining your views in UWP

All the view layering that you are describing is happening inside your Custom Renderer there isn't anything here where forms seems to be affecting that layout.

I would take this issue over to UWP forums or ask the makers of the video player you are using to see if they have any ideas.

If you have a way to show this being a forms specific problem then we can take a look
