### ISSUE TITLE
xamarin shell navigation flickering on backpress

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9300]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/882148/xamarin-shell-navigation-flickering-on-backpress.html)._

---
This is can be reproduced just by starting a new xamarin shell project. (just run the app without adding any code and you will notice it) 
It can also happen if you add shell to your exisiting xamarin project. 
flickering (black screen then page loads) happens when navigating back on pressing either the hardware button or on pressing software back button.
I also noticed that it happens on emulators.
This issue is less happening on new devices but with less black screen time, flickering is still there but less noticable on new devices.

current testing physical devices :
Samsung s7 edge
Samsung s9 

This issue does not affect iOS.

---
#### Visual Studio Feedback System on 1/13/2020, 01:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ahmedalejo** [comment]
This most notable on real devices.

**Comment by NadjibR** [comment]
I face the same issue on LG G5. It's pretty fast device with no performance problems.

Tested with the Xaminals example from Microsoft.

**Comment by malikberkane** [comment]
Having the same problem on a Pixel 3XL

**Comment by AndreasLichtsinn** [comment]
Same issue as this: https://github.com/xamarin/Xamarin.Forms/issues/8581

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/8581

**Comment by ahmedalejo** [comment]
One year anniversary of [Shell] navigation - flickering #5755
