### ISSUE TITLE
[Bug] ArgumentOutOfRangeException related to Xamarin.Forms.Internals.TemplatedItemsList

### ISSUE THREAD

**Issue by jonathanantoine** [xamarin/Xamarin.Forms#9302]
### Description
I have a lot of crashes related to this call stack in my Android app : 
```
(ArgumentOutOfRangeException) Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index
System.Collections.Generic.List`1[T].get_Item(System.Int32 index)<0x779ae76c30 + 0x00063> (List1T0x779ae76c300x00063.cs:1)
Cadenza.Collections.OrderedDictionary`2[TKey,TValue].get_Item(System.Int32 index)<0x779a34cad0 + 0x00053> (OrderedDictionary2TKeyTValue0x779a34cad00x00053.cs:1)
Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].GetGroup(System.Int32 index)<0x779a3b0cc0 + 0x0003f> (TemplatedItemsList2TViewTItem0x779a3b0cc00x0003f.cs:1)
Xamarin.Forms.Internals.TemplatedItemsList`2[TView,TItem].Xamarin.Forms.ITemplatedItemsList<TItem>.GetGroup(System.Int32 index)<0x779a3b0d10 + 0x0001b> (ITemplatedItemsListTItem0x779a3b0d100x0001b.cs:1)
Xamarin.Forms.Platform.Android.ListViewAdapter.get_Count()<0x779925dd40 + 0x000cb> (ListViewAdapter0x779925dd400x000cb.cs:1)
Android.Widget.BaseAdapter.n_GetCount(System.IntPtr jnienv, System.IntPtr native__this)[0x00009] (BaseAdapter0x00009.cs:1)
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.110(intptr,intptr). (unknown.cs:1)
```

### Steps to Reproduce

1. Create an Android App using a Listview

### Expected Behavior
No crash..
### Actual Behavior
Crashes

### Basic Information

- Version with issue: 4.4.0.991537
- Last known good version: n/A
- IDE: VS For Mac
- Platform Target Frameworks: 
  - Android: 10.0
- Android Support Library Version: 8.0.0.3
- Nuget Packages:
- Affected Devices: All kind of Android devices

**Comment by samhouts** [comment]
@jonathanantoine  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@jonathanantoine  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by xamarindev01** [comment]
@samhouts This is also happening for me for all the Android devices and its a random crash. I am using ListView with grouping enabled.
Please let me know if you need anymore info.

```
List`1[T].get_Item (System.Int32 index)
OrderedDictionary`2[TKey,TValue].get_Item (System.Int32 index)
TemplatedItemsList`2[TView,TItem].GetGroup (System.Int32 index)
ITemplatedItemsList<TItem>.GetGroup (System.Int32 index)
ListViewAdapter.get_Count ()
BaseAdapter.n_GetCount (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.89(intptr,intptr)
```

## Basic Information
Version with issue: 4.6.0.800
IDE: VS For Mac
Platform Target Frameworks: Android 10.0
Android: 10.0
Affected Devices: All kind of Android devices

**Comment by JigarM** [comment]
@jonathanantoine Did you find any solution for this issue?
