### ISSUE TITLE
[Bug] [iOS] Cannot un-reveal swipe view items on iOS / Inconsistent swipe view behaviour

### ISSUE THREAD

**Issue by dsdilpreet** [xamarin/Xamarin.Forms#9306]
### Steps to Reproduce

1. Create a swipe view using following code.
```
                <SwipeView>
                    <SwipeView.LeftItems>
                        <SwipeItems>
                            <SwipeItem Text="Favorite"
                       BackgroundColor="LightGreen" />
                            <SwipeItem Text="Delete"
                       BackgroundColor="LightPink" />
                        </SwipeItems>
                    </SwipeView.LeftItems>
                    <!-- Content -->
                    <Grid HeightRequest="60"
                        WidthRequest="300">
                        <Label Text="Swipe right"
                           HorizontalOptions="Center"
                           VerticalOptions="Center" />
                    </Grid>
                </SwipeView>
```
2.  Swipe Right on swipe view to reveal items. It should look this this.
![image](https://user-images.githubusercontent.com/11010830/73031951-78c4aa00-3ea2-11ea-8504-2ed0f0658aab.png)

3.  Swipe Left to un-reveal swipe items but it does not work on iOS. It works fine on Android.
![image](https://user-images.githubusercontent.com/11010830/73032034-bc1f1880-3ea2-11ea-8e59-64809827d132.png)

### Expected Behavior
In my opinion, Android implementation is better because user could accidentally swipe on an item. I think user should be allowed to put the swipe items away without clicking on them.

### Basic Information

- Version with issue: Xamarin Forms v4.5.0 pre 2
- Platform Target Frameworks: 
  - iOS:   13.3
  - Android:  Android 9 and 10

**Comment by samhouts** [comment]
closed by  #9664
