### ISSUE TITLE
[Bug] `OnAppearing` does not fire after a `UIModalPresentationStyle.FormSheet` Page is Dismissed

### ISSUE THREAD

**Issue by brminnick** [xamarin/Xamarin.Forms#9307]
### Description

On iOS, When a Modal Page using `UIModalPresentationStyle.FormSheet` is dismissed, `OnAppearing` does not fire on the previous page.

| Navigation Mode | `UIModalPresentationStyle` | Behavior After Page is Dismissed |
| ----------- | ---------------------------- | -------------------- |
| `Navigation.PushAsync` | N/A | ✅ `OnAppearing` Fires on Previous Page |
| `Navigation.PushModalAsync` | `UIModalPresentationStyle.FullScreen` | ✅ `OnAppearing` Fires on Previous Page |
| `Navigation.PushModalAsync` | `UIModalPresentationStyle.FormSheet` | 💥 `OnAppearing` Does Not Fire on Previous Page |

### Steps to Reproduce

1. Download/Clone this repo: https://github.com/brminnick/UIModalPresentationStyleFormSheetOnAppearingRepro
2. In Visual Studio, open `OnAppearingRepro.sln`
3. Build/deploy `OnAppearingRepro.iOS` to an iOS Simulator or Device
4. On the iOS app, confirm the following alert appears: `OnAppearing Fired`
5. On the iOS app, dismiss the alert
6. On the iOS app, click the `Push Page` Button to push a new `ContentPage` via `Navigation.PushAsync`
7. On the iOS app, click the `Back` button
8. On the iOS app, confirm the following alert appears: `OnAppearing Fired`
9. On the iOS app, dismiss the alert
10. On the iOS app, click the `Push Modal Full Screen Sheet Page` Button to push a new `ContentPage` using `UIModalPresentationStyle.FullScreen` via `Navigation.PushModalAsync`
11. On the iOS app, click the `Back` button
12. On the iOS app, confirm the following alert appears: `OnAppearing Fired`
13. On the iOS app, dismiss the alert
14. On the iOS app, click the `Push Modal Form Sheet Page` Button to push a new `ContentPage` using `UIModalPresentationStyle.FormSheet` via `Navigation.PushModalAsync`
15. On the iOS app, click the `Back` button
16. On the iOS app, confirm the following alert *does not* appear: `OnAppearing Fired`

### Expected Behavior

When a `UIModalPresentationStyle.FormSheet` page is dismissed, `OnAppearing` should fire on the previous page to match the behavior of `UIModalPresentationStyle.FullScreen`.

### Actual Behavior

When a `UIModalPresentationStyle.FormSheet` page is dismissed, `OnAppearing` does not fire on the previous page.

### Basic Information

- Version with issue: v4.4.0.991537
- Last known good version: N/A
- Platform Target Frameworks: 
  - iOS:  11.3.1

### Reproduction Link

https://github.com/brminnick/UIModalPresentationStyleFormSheetOnAppearingRepro/tree/master

### Screenshots

![](https://user-images.githubusercontent.com/13558917/73046661-59377c80-3eb6-11ea-916a-494469969d85.gif)

**Comment by Tommigun1980** [comment]
I think these kinds of bugs are the most important to fix, as they affect navigation as a whole and can be really tricky to hack around. Thanks.

**Comment by winterdouglas** [comment]
Came here just to +1 this.

**Comment by jejip** [comment]
+1

**Comment by samhouts** [comment]
closed by #7923
