### ISSUE TITLE
Application.Current.Properties gets deleted if saving an object that is not a string

### ISSUE THREAD

**Issue by flyhalabi** [xamarin/Xamarin.Forms#9313]
### Description
When setting a property, if it's not a string, once the app is being loaded again, all properties gets deleted.

### Steps to Reproduce

1. Save a few properties that are string.
2. Call SavePropertiesAsync().
3. Now save one property which is a class, any simple class with a few properties will do.
4. Call SavePropertiesAsync().
5. Close the app, restart it, all properties are gone.

### Expected Behavior
No properties should be deleted.

### Actual Behavior
All properties are deleted.

### Basic Information

- Version with issue: 4.5.0.142-pre1
- Last known good version: unknown
- IDE: VS 2019
- Platform Target Frameworks: 
  - Android: 9.0 pie

**Comment by WayaFlyfeather** [comment]
From the [remarks in the docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.properties?view=xamarin-forms#remarks):

> Values saved in the properties dictionary must be primitive types, such as integers or strings. Attempting to save reference types, or collections in particular, can fail silently.

Isn't that was is happening?

**Comment by flyhalabi** [comment]
> From the [remarks in the docs](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.application.properties?view=xamarin-forms#remarks):
> 
> > Values saved in the properties dictionary must be primitive types, such as integers or strings. Attempting to save reference types, or collections in particular, can fail silently.
> 
> Isn't that was is happening?

thank you, I have missed this part when I read the documents.

**Comment by chaoyebugao** [comment]
What the ....
