### ISSUE TITLE
[Bug Android] PanGesture with translation are not smooth on Android ( jerky )

### ISSUE THREAD

**Issue by Phenek** [xamarin/Xamarin.Forms#9316]
### Description
I got a strange interaction when using pan gesture on Android only.
It's jerky.. 

### Steps to Reproduce

1. Create a frame with a pan gesture on it 
2. Create a drag interaction by translating this frame during  the panGesture event
3. you can see jerky

### Expected Behavior
Like in iOS, the interaction must be smooth!
The translation should not affect the drag event properties.

### Actual Behavior
On Android it's jerky.
On iOS it's smooth.

### Reproduction Link
Here the reproduction project => [PanGestureNotSmooth.zip](https://github.com/xamarin/Xamarin.Forms/files/4109511/PanGestureNotSmooth.zip)

### Workaround
I did not find an efficient workaround for now.

### Basic Information
- Platform Target Frameworks: 
  - iOS:  LastOne!
  - Android: Android 9.0 (API Level 28)
- Nuget Packages: Xamarin.Forms 4.0+
- Affected Devices: Android

**Comment by samhouts** [comment]
@Phenek Android _really_ doesn't like it when you try to move the element on which the pan gesture is attached. This is why our documentation recommends creating a PanContainer element that wrap the element you want to move instead. https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/pan

Thanks!

**Comment by Phenek** [comment]
@samhouts Thanks for the tips!
Nice team 👍
