### ISSUE TITLE
[Enhancement] [Shell] Add static items to the flyout menu

### ISSUE THREAD

**Issue by Jabbah76** [xamarin/Xamarin.Forms#9323]
## Summary
Add static items to the flyout menu. These can be used, for example, as sub headers or other static stuff that don't function as a menu item. See the screenshot for an example

## Intended Use Case
![image](https://user-images.githubusercontent.com/58596571/73128394-13baa280-3fcf-11ea-8739-6a27e38ae408.png)

Something like

```
<ShellStaticContent>
    <DataTemplate>
        <Label Text="Header" />
    </DataTemplate>
</ShellStaticContent>
```

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
