### ISSUE TITLE
[Bug] RefreshView should delay effects of IsEnabled while a refresh is happening and iOS is handling IsEnabled false incorrectly

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9326]
### Description

In a lot of cases Commands will get marked as CanExecute false while they are executing. This confuses the refreshview as the refreshview disables or, in the iOS case, removes the view from the superview. 

IsEnabled should be ignored until after IsRefreshing toggles back. At which point IsEnabled should be processed after the Refresh Control is no longer visible. Ideally we can tap into something on the RefreshControl to know when it's no longer visible.

On iOS the code to disable doesn't seem correct. It purely removes the control from the superview which seems to causes issues with the UIScrollView scenario where it's just set ono the control. Setting it back on the control doesn't appear to add it back to the superview

### Steps to Reproduce

1.  https://github.com/RLittlesII/Reactive.Sandbox/tree/master/xamarin/forms/ReactiveUI.2299
2.  change to a XAML binding https://github.com/reactiveui/ReactiveUI/issues/2299#issuecomment-575558274

### Expected Behavior
Ii should be able to keep refreshing after the first refresh and the refresh control shouldn't be removed from the superview while refreshing

### Actual Behavior

RefreshControl is removed from the superview during refresh and even the IsEnabled toggles back the RefreshControl is never added back

### Basic Information

- Version with issue: 4.3

**Comment by winterdouglas** [comment]
For reference: I did some debugging in the sandbox sample linked to this issue along with the forms source code itself, did some changes to not set the `IsEnabled` back to false in the `RefreshView.cs` and it seemed to be working correctly (not a final fix, just did it for testing purposes, to understand what was going on).

https://github.com/reactiveui/ReactiveUI/issues/2299#issuecomment-581816538

**Comment by wrkettlitz** [comment]
I noticed if I call the [ChangeCanExecute](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.command.changecanexecute?view=xamarin-forms) method on the command, the command doesn't even run the canExecute delegate.

**Comment by Tommigun1980** [comment]
Any chance this could be fixed? It makes my app not function properly as it’s utilizing a RefreshView binding to a refresh command with a CanExexute. Thanks so much!

**Comment by ChaseFlorell** [comment]
Here's a repro
https://github.com/ChaseFlorell/xamarin-forms-9326

**Comment by ChaseFlorell** [comment]
@jsuarezruiz

**Comment by luismts** [comment]
+1 on android too

Any news about this?

**Comment by Tommigun1980** [comment]
> +1 on android too
> 
> Any news about this?

I hope this gets fixed soon as it breaks pull to refresh.
