### ISSUE TITLE
MenuItem.cs does not have a null check for command Execute Changed Method, causes object reference error and app crash

### ISSUE THREAD

**Issue by shahbaaz90** [xamarin/Xamarin.Forms#9328]
### Description
MenuItem.cs does not have a null check for command Execute Changed Method

### Steps to Reproduce

1. Wire up a command to Xamarin Toolbar item
2. wire up properties to observe CanExecute on command
3. 

### Expected Behavior
app doesnt crash because of the command null check

### Actual Behavior
app crashes because of the missing command null check on the can execute changed method in MenuItem.cs

https://github.com/xamarin/Xamarin.Forms/blob/cbccb71ccf80678fb283af1bae32ed05b1e6b3aa/Xamarin.Forms.Core/MenuItem.cs#L102

### Screenshots
<img width="1508" alt="Screenshot 2020-01-27 at 14 24 51" src="https://user-images.githubusercontent.com/9108018/73163047-f5f55680-4110-11ea-9d7e-9d1fc92f5c8c.png">

### Workaround
The only workaround to prevent crash was to stop monitoring CanExecute of the command.

**Comment by samhouts** [comment]
@shahbaaz90  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by shahbaaz90** [comment]
> @shahbaaz90 Can you please attach a small project that demonstrates this issue? Thanks!

Well, its not an issue that's very reproducible, but happens on rare occasions when the page view model gets destroyed via navigation before the CanExecuteChanged event is invoked. A race condition of sorts. 

So for e.g, if i enter a page with the CanExecute as False, and if it changes to True (and the page is destroyed at more or less the same time), the command gets set to null. 

I'll see if i can come up with a demo project

**Comment by samhouts** [comment]
@shahbaaz90 Thanks! We like to make sure we're not just masking a larger issue by adding a null check, so if we can reproduce it, that's ideal.

**Comment by jsuarezruiz** [comment]
This is already fixed:

`IsEnabledCore = Command?.CanExecute(CommandParameter) ?? true;`
