### ISSUE TITLE
SwipView Tap Event in Android

### ISSUE THREAD

**Issue by kaminipatel03** [xamarin/Xamarin.Forms#9336]
[App3.zip](https://github.com/xamarin/Xamarin.Forms/files/4121877/App3.zip)
I have Problem in  Invoked event in SwipView. When I tap One of Right Items Invoked event does not fire.

I am using Visual Studio 2019 . 

I have updated Xamarian.forms 4.5.0.187-pre2 but still having problem. Please give me suggestion it's an urgent.

here i have attached sample project.

**Comment by samhouts** [comment]
Duplicate of #9317
