### ISSUE TITLE
[Bug] FlexLayout.OnMeasure (System.Double widthConstraint, System.Double heightConstraint) System.NullReferenceException

### ISSUE THREAD

**Issue by Srikanth540-L** [xamarin/Xamarin.Forms#9340]
### Description
 We are facing random crash in Flex Layout  with null reference exception in the  xamarin forms version 4.4

### Expected Behavior
don't crash

### Actual Behavior
Crashes the app randomly but more frequently 
### Basic Information

- Version with issue:  Xamarin forms 4.4
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 9
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All Android devices

**STACK TRACE**

FlexLayout.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
StackLayout.CalculateNaiveLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, Xamarin.Forms.StackOrientation orientation, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint)
StackLayout.CalculateLayout (Xamarin.Forms.StackLayout+LayoutInformation layout, System.Double x, System.Double y, System.Double widthConstraint, System.Double heightConstraint, System.Boolean processExpanders)
StackLayout.OnSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.OnMeasure (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
Layout.GetSizeRequest (System.Double widthConstraint, System.Double heightConstraint)
VisualElement.Measure (System.Double widthConstraint, System.Double heightConstraint, Xamarin.Forms.MeasureFlags flags)
ScrollView.LayoutChildren (System.Double x, System.Double y, System.Double width, System.Double height)
Layout.UpdateChildrenLayout ()
Layout.OnSizeAllocated (System.Double width, System.Double height)
VisualElement.SizeAllocated (System.Double width, System.Double height)
Layout.ResolveLayoutChanges ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)

**Comment by samhouts** [comment]
@Srikanth540-L  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by Srikanth540-L** [comment]
![NewUIPhone](https://user-images.githubusercontent.com/59356252/73838659-32743100-483a-11ea-928a-e47b513618a9.jpg)

**Comment by samhouts** [comment]
@Srikanth540-L I'd love to be able to reproduce this, but I can't do that easily with the code snippet provided. Can you tell me if this is new in 4.4 and did not crash in a prior version? I see some opportunities for null checks in that method, but this seems indicative of a larger issue. Thanks!

**Comment by Srikanth540-L** [comment]
@samhouts  the flex layout for the filter is implemented after the xamarin forms update to 4.4, we are not sure about previous versions, the line where we are clearing RegisteredCategories it cannot be null since we are initializing constructor and I can tell you that there are no other places where it is set to null

**Comment by Srikanth540-L** [comment]
@samhouts  Is moving to collection view from flex layout is a better approach? 
To elaborate on the issue we tried switching to legacy renderers

**Comment by Srikanth540-L** [comment]
@samhouts  Is switching to collection view is a better approach? 
Any suggestions what might be  causing this crash and precautions to be taken to avoid such crashes would be very helpful. 
Thanks you!

**Comment by samhouts** [comment]
@Srikanth540-L We do know that there are some quirks with FlexLayout when used in combination with other Layouts. They do not always work well together. If you can think of a different way to do this complex layout, that might be a good way to go. In the meantime, we'll investigate the null references. Thanks!

**Comment by StephaneDelcroix** [comment]
I looked at the code, and there's a possibility, due to a race condition, that GetFlexItem returns null and causes the exception. @Srikanth540-L I could generate a nuget (based on 4.4 or 4.5) with the fix attempt if you're ok to try it

**Comment by Srikanth540-L** [comment]
@stefandevo  We have replaced flex layout with collectionview since then there is no such crash  has occurred, so we are good with it.
Thanks!
@Srikanth540-L

**Comment by Srikanth540-L** [comment]
@StephaneDelcroix   tested the nuget it's working fine , We haven't noticed any crash.So closing the issue.
Thanks!
@Srikanth540-L

**Comment by StephaneDelcroix** [comment]
reopening, as I haven't send the PR for the said nuget
