### ISSUE TITLE
[Bug] Animated Images disappear in listview after scrolling

### ISSUE THREAD

**Issue by hulluP** [xamarin/Xamarin.Forms#9341]
### Description
A listview containing several animated images looses the images in the cells when scrolling up and down. On Android the images stay and keep the animation.

### Steps to Reproduce

1. clone the repo https://github.com/hulluP/Animatedimage
2. click on List wait until animated images loaded and started playing
3. scroll up and down -> images will dissapear
4. Clicking on an cell will show the image again 

### Expected Behavior
images keep showing and keep the animation no matter if they are scrolled or not on both platforms

### Actual Behavior
images disappear on iOS

### Basic Information

- Version with issue: Xamrin.Forms 4.4.0.99
- Last known good version: -
- IDE: Visual Studio Mac
- Platform Target Frameworks: 
  - iOS:  iOS 13.3
  - Android: API 28
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Screenshots
before scrolling:
<img width="151" alt="Screenshot 2020-01-28 at 14 35 03" src="https://user-images.githubusercontent.com/46395952/73268584-7bddd400-41db-11ea-9460-1961303bd71c.png">
after scrolling:
<img width="168" alt="Screenshot 2020-01-28 at 14 35 20" src="https://user-images.githubusercontent.com/46395952/73268622-8d26e080-41db-11ea-966b-c5c92dc79a95.png">

### Reproduction Link

https://github.com/hulluP/Animatedimage

### Workaround
not starting the animation seems to allow scrolling the images.

**Comment by PureWeen** [comment]
@hulluP I tested your example with CollectionView and it looks like it works great over there if you want to switch
