### ISSUE TITLE
[Bug][Android] Handling visibility of a child in DataTemplate of a custom control not works properly.

### ISSUE THREAD

**Issue by gokulsaravanan** [xamarin/Xamarin.Forms#9354]
### Description
In our custom control, we are providing the DataTemplate property for view customization support.
When handling the visibility of a child through binding it does not work properly.

If we set the IsVisible to the view initially as 'True' it works fine when changing visibility a run time. But when visibility is 'false'  when control is loaded and changing its value at run time, doesn't works.

### Steps to Reproduce

1. Run the sample.
2. Click on the open button to navigate to the page, where the control is loaded.
3. Click the change visibility button to change the visibility of the grid, loaded inside the template.
4. You can see the changing visibility works for items to which the grid is visible at initial loading, but others, not works.

### Expected Behavior
The visibility of the item should change when changed.

### Actual Behavior
Grid is not visible when set IsVisible as true in button clicked event until you rotate the screen.

### Basic Information

- IDE: VS2019
- Platform Target Frameworks:
  - Android: 9.1
- Nuget Packages: Xamarin.Forms 3.6.0.344457

### Screenshots
Attached the issue reproducible video in the below attachment.

### Reproduction Link
[Visibility_Issue.zip](https://github.com/xamarin/Xamarin.Forms/files/4126249/Visibility_Issue.zip)

![IssueVideo](https://user-images.githubusercontent.com/46105032/73329679-899b6400-4284-11ea-9f3e-f93351cd426a.gif)

**Comment by PureWeen** [comment]
I changed over your custom layout to use a collectionview with data templates and it works fine there. So this is going to be something that's wrong with your custom layout code that's most likely not resizing the container when the grids visibility changes.  

When the grids visibility is zero it has no bounds and then when it changes it gets remeasured. I'm guessing the parent container isn't reacting to this

![595A86F0-B4B5-4D67-B240-CFB51012B1C7](https://user-images.githubusercontent.com/5375137/75081824-ee398f80-54cd-11ea-8a87-7636aec56611.GIF)
