### ISSUE TITLE
[Bug] System.ObjectDisposedException with Xamarin.Forms.Platform.Android.ScrollViewRenderer

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Xamarin.Forms#9355]
### Description

When moving away from a page containing a ScrollView, my xamarin.forms app crashes on android.
This regression appeared in version 4.5.0 (pre1 or pre2).

### Steps to Reproduce

1. Open a page containing a ScrollView
2. Close the page
3. App crashes

### Expected Behavior

No crash.

### Actual Behavior

Crash.

### Basic Information

- Version with issue: 4.5.0.187-pre2
- Last known good version: 4.4.0.991537
- IDE: Visual Studio 2019 16.5.0 preview 2.0
- Platform Target Frameworks: Android: 10

### Stacktrace

01-29 12:24:11.506 I/MonoDroid( 3196): System.ObjectDisposedException: Cannot  access a disposed object.
01-29 12:24:11.506 I/MonoDroid( 3196): Object name:  'Xamarin.Forms.Platform.Android.ScrollViewRenderer'.
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self)  [0x00029] in <ce53014a5d7d49af8f964173870eeb58>:0
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod  (System.String encodedMember, Java.Interop.IJavaPeerable self,  Java.Interop.JniArgumentValue* parameters) [0x00000] in  <ce53014a5d7d49af8f964173870eeb58>:0
01-29 12:24:11.506 I/MonoDroid( 3196):   at Android.Views.View.get_Parent ()  [0x0000a] in <af2d8533745a4fc89b63b4cbd77f3797>:0
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.ViewExtensions.RemoveFromParent  (Android.Views.View view) [0x00004] in  d:\a\1\s\Xamarin.Forms.Platform.Android\ViewExtensions.cs:30
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.RemoveChild  (Xamarin.Forms.VisualElement view) [0x00067] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:266
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.SetElement  (Xamarin.Forms.VisualElement oldElement, Xamarin.Forms.VisualElement newElement)  [0x000ab] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:313
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.Dispose (System.Boolean  disposing) [0x000a7] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:86
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.Dispose () [0x00000] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:61
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.Dispose (System.Boolean  disposing) [0x000ec] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:97
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementPackager.Dispose () [0x00000] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementPackager.cs:61
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.VisualElementRenderer`1[TElement].Dispose  (System.Boolean disposing) [0x00081] in  d:\a\1\s\Xamarin.Forms.Platform.Android\VisualElementRenderer.cs:301
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.PageRenderer.Dispose (System.Boolean disposing)  [0x00024] in  d:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\PageRenderer.cs:58
01-29 12:24:11.506 I/MonoDroid( 3196):   at Java.Lang.Object.Dispose ()  [0x00000] in <af2d8533745a4fc89b63b4cbd77f3797>:0
01-29 12:24:11.506 I/MonoDroid( 3196):   at  Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnDestroyView ()  [0x0003c] in  d:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\FragmentContainer.cs:88
01-29 12:24:11.506 I/MonoDroid( 3196):   at  AndroidX.Fragment.App.Fragment.n_OnDestroyView (System.IntPtr jnienv,  System.IntPtr native__this) [0x00008] in <6aa2e3945ca740f3ba1f2af2bd3af2a2>:0
01-29 12:24:11.506 I/MonoDroid( 3196):   at (wrapper dynamic-method)  Android.Runtime.DynamicMethodNameCounter.66(intptr,intptr)

**Comment by samhouts** [comment]
@tranb3r  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by tranb3r** [comment]
Here is a repro:
[TestScrollView.zip](https://github.com/xamarin/Xamarin.Forms/files/4129819/TestScrollView.zip)

The regression appears in 4.5.0-pre1. (no crash in 4.4.0.991437).

The crash only occurs when the scrollview's stacklayout parent has the CompressedLayout.IsHeadless="true" property set.
No crash if this property is removed.

**Comment by kvpt** [comment]
@tranb3r It's a regression caused by my PR #8745.
I encountered it in one of my app with a ScrollViewer in a master page, but I did not manage to reproduce it in a test case yet. I will try your's.
