### ISSUE TITLE
[Bug] UWP Xamarin Forms does not support dark theme

### ISSUE THREAD

**Issue by cansado2930** [xamarin/Xamarin.Forms#9362]
### Description
Out of box XF does not support Dark Mode,

### Steps to Reproduce

1.  Create a new masterl detail project
2.  Run on windows (Windows have to setted with dark mode)
3.  Menu, page and status bar is working with Ligth Theme instead dark theme

### Expected Behavior
page, menu and status bar should work with dark theme as it works on Android and iOS.

### Actual Behavior
page, menu and status bar are working with Ligth theme

### Basic Information

- Version with issue: Lasted
- Last known good version: none
- IDE: VS windows last public release 
- Platform Target Frameworks:
  - UWP:  For Fall Creator Update
- Nuget Packages: XF 4.4.0.991537

### Workaround
Whit the following code, I can force to work XF with dark theme.
```
foreach (var view in CoreApplication.Views)
        {
            await view.Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
            {
                if (Window.Current.Content is FrameworkElement frameworkElement)
                {
                    frameworkElement.RequestedTheme = Theme;
                }
            });
        }
```

If I can help in order to test or fix it, Tell me.

**Comment by VladislavAntonyuk** [comment]
You can use custom theme (use resource dictionary with your colors and styles)
```
            var titleBar = ApplicationView.GetForCurrentView().TitleBar;
            switch (theme)
            {
                case Theme.Light:
                    // Set active window colors
                    titleBar.ForegroundColor = Color.FromArgb(1, 25, 25, 25);
                    titleBar.BackgroundColor = Color.FromArgb(1, 220, 220, 220);
                    break;
                case Theme.Dark:
                    // Set active window colors
                    titleBar.ForegroundColor = Color.FromArgb(1, 230, 230, 230);
                    titleBar.BackgroundColor = Color.FromArgb(1, 35, 35, 35);
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(theme), theme, null);
            }

            titleBar.ButtonForegroundColor = titleBar.ForegroundColor;
            titleBar.ButtonBackgroundColor = titleBar.BackgroundColor;
            titleBar.ButtonHoverForegroundColor = titleBar.ForegroundColor;
            titleBar.ButtonHoverBackgroundColor = titleBar.BackgroundColor;
            titleBar.ButtonPressedForegroundColor = titleBar.ForegroundColor;
            titleBar.ButtonPressedBackgroundColor = titleBar.BackgroundColor;

            // Set inactive window colors
            titleBar.InactiveForegroundColor = titleBar.ForegroundColor;
            titleBar.InactiveBackgroundColor = titleBar.BackgroundColor;
            titleBar.ButtonInactiveForegroundColor = titleBar.ForegroundColor;
            titleBar.ButtonInactiveBackgroundColor = titleBar.BackgroundColor;

**Comment by cansado2930** [comment]
Thank @VladislavAntonyuk , it is useful for update the titlebar.

**Comment by anton-yashin** [comment]
If you want to switch theme using system settings in windows, then you must remove RequestedTheme="Light" from App.xaml at uwp project, then remove or comment out "Global styles" from App.xaml at shared library.

**Comment by PureWeen** [comment]
@jfversluis ?

**Comment by PureWeen** [comment]
We have the following spec

https://github.com/xamarin/Xamarin.Forms/issues/7304

Which I'm pretty sure is going to apply to all platforms but I'm poking @jfversluis so he can give clarification

**Comment by jfversluis** [comment]
I've added #9804 for a more complete, cross-platform story. Any feedback welcome!

**Comment by samhouts** [comment]
I'll close this in favor of #9804. Thanks!
