### ISSUE TITLE
[Bug] UWP project exception generated when Xamarin.Forms.Forms.Init(...) is called

### ISSUE THREAD

**Issue by sephius1999** [xamarin/Xamarin.Forms#9374]
### Description

I recently upgraded to VS2017 from VS2015.

I have a UWP project which I also upgraded to use Xamarin.Forms 4.3.0.991211

The UWP project also uses Microsoft.NETCore.UniversalWindowsPlatform 6.1.5

When I do a "Start with Debugging", the following exception is generated:

> System.BadImageFormatException
>   HResult=0x8007000B
>   Message=Duplicate type with name '<>PropertyChangedEventArgs' in assembly 'Test.Core, Version=2.1.40.0, Culture=neutral, PublicKeyToken=null'.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
>    at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
>    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes)
>    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
>    at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
>    at Xamarin.Forms.DependencyService.Initialize(Assembly[] assemblies)
>    at Xamarin.Forms.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags)
>    at Xamarin.Forms.Forms.Init(IActivatedEventArgs launchActivatedEventArgs, IEnumerable`1 rendererAssemblies)
>    at vWork.UWP.App.OnLaunched(LaunchActivatedEventArgs e) in C:\Test_SLN\Src\Test\Test.UWP\App.xaml.cs:line 159

The error occur at the call to **global::Xamarin.Forms.Forms.Init(e, assembliesToInclude);**

The error seems to be around a -- Duplicate type with name '<>PropertyChangedEventArgs' in assembly 'Test.Core

I have gone to Google and done some research but coming up empty.

Any help would be greatly appreciated.

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue: 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:  17763 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by VladislavAntonyuk** [comment]
Delete bin/obj folders, restore packages again. Rebuild

**Comment by samhouts** [comment]
@sephius1999 Does the suggestion in https://github.com/xamarin/Xamarin.Forms/issues/9374#issuecomment-580472183 work for you? Thanks!

**Comment by sephius1999** [comment]
I have clean, deleted bin/obj folders, recompile and I still get the same error.

I even restarted my computer just to make sure nothing was being cached.

Seems like my Test.Core project is referencing a different PropertyChangedEventArgs than the Test.UWP project that uses the Test.Core

PropertyChangedEventArgs is defined in the System.ObjectModel, if I'm not mistake.

Since System.ObjectModel is linked in during the compile process, I don't know how to verify the versions (since it is saying 'Duplicate type') being used by Test.Core vs Test.UWP

**Comment by samhouts** [comment]
@sephius1999 Please verify that you have the same version of Xamarin.Forms installed in all projects.

**Comment by sephius1999** [comment]
I figured it out.

My Fody version was the issue.

I tried to upgrade to Fody 4.2.1, but I had to go back to Fody 2.1.0.

Fody is triggering the error.
