### ISSUE TITLE
Keyboard Default Language

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9377]
Hi,

It will be great if you add a Language property to the Keyboard or KeyboardFlag in order to set the default language of edit controls such as Entry, Editir, etc where it will open the keyboard with the configured default language but user can change the language if he wants to.

Thanks,
[Jassim](https://www.emiratesangels.org/)

**Comment by VladislavAntonyuk** [comment]
What language to select if user doesn’t have such keyboard language?

**Comment by jrahma** [comment]
@VladislavAntonyuk  His default language..

For example, if I have both Arabic and English languages installed and I want my app to show the Arabic language as default for a specific Entry then I should just set the default for the Keyboard or set KeyboardFlag

If the Arabic language is installed then it will switch to Arabic in my app

If Arabic is not installed then it will just show English because it's the default language of my device

**Comment by VladislavAntonyuk** [comment]
> @VladislavAntonyuk His default language..
> 
> For example, if I have both Arabic and English languages installed and I want my app to show the Arabic language as default for a specific Entry then I should just set the default for the Keyboard or set KeyboardFlag
> 
> If the Arabic language is installed then it will switch to Arabic in my app
> 
> If Arabic is not installed then it will just show English because it's the default language of my device

What if you have English keyboard only, but you request a Chinese, which is not installed on your device?

**Comment by jrahma** [comment]
> > @VladislavAntonyuk His default language..
> > For example, if I have both Arabic and English languages installed and I want my app to show the Arabic language as default for a specific Entry then I should just set the default for the Keyboard or set KeyboardFlag
> > If the Arabic language is installed then it will switch to Arabic in my app
> > If Arabic is not installed then it will just show English because it's the default language of my device
> 
> What if you have English keyboard only, but you request a Chinese, which is not installed on your device?

Then it will return false and go to default language which is only installed, English in your case

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
