### ISSUE TITLE
[Bug] IValueConverter and Behavior conflict with each other causing an endless loop to occur

### ISSUE THREAD

**Issue by JohnLivermore** [xamarin/Xamarin.Forms#9380]
### Description
I have a simple XF solution that illustrates a problem I am having with a IValueConverter and a Behavior that conflict with each other causing an endless loop to occur.  I think it might be a bug in Forms, although I am not entirely sure at this point.

Here are the requirements I am trying to achieve in this scenario.

1.  The user must be able to enter an empty value for the int.
2.  The user is only allowed to enter an integer value.

For #1, I use a nullable int in the backend model.  If I were to use just an 'int', then the field would always end up with a '0' in it if it were cleared.  So, the IValueConverter implementation StringToIntConverter is used to convert the value from a string to an int, and if an empty string is passed, the property is set to null.

For #2, the Behavior IntegerValidationBehavior inspects each keystroke and eliminates any non-integer values including periods.  In addition, for this example, I only show the numeric keyboard.  However, it allows some non-integer characters like the period, so the IntegerValidationBehavior is needed.

For normal inputs it works great.  But if you start with a '0' and then enter another number, it goes haywire ending up in an endless loop.  I have verified this on various XF versions as well as both iOS and Android platforms.

Can someone verify this is a XF bug, or show me how to change the code to meet the requirements please?

### Steps to Reproduce

1. Run the demo as found in the github repo below
2. Enter '05' into the input box and app freezes in an endless loop

### Reproduction Link
[https://github.com/JohnLivermore/SampleXamarinApp/tree/endlessloop](https://github.com/JohnLivermore/SampleXamarinApp/tree/endlessloop)

**Comment by JohnLivermore** [comment]
I have this figured out.  It can be closed (it's not a XF bug).

**Comment by lavilaso** [comment]
> I have this figured out. It can be closed (it's not a XF bug).

How did you solve it?
I have a similar use case

**Comment by JohnLivermore** [comment]
@lavilaso I found my answer [here](https://stackoverflow.com/questions/60050005/xaml-ivalueconverter-and-behavior-conflict-with-each-other-causing-an-endless).  Scroll down to the accepted answer.

**Comment by lavilaso** [comment]
> @lavilaso encontré mi respuesta [aquí](https://stackoverflow.com/questions/60050005/xaml-ivalueconverter-and-behavior-conflict-with-each-other-causing-an-endless) . Desplácese hacia abajo hasta la respuesta aceptada.

Thanks!
