### ISSUE TITLE
[UWP] WebViewRenderer - it can be 2x faster

### ISSUE THREAD

**Issue by artemious7** [xamarin/Xamarin.Forms#9392]
## Summary
WebViewRenderer internally uses a second WebView, which is not always necessary.

## API Changes
None. Only internal modifications.

Rewrite [WebViewRenderer.LoadHtml()](https://github.com/xamarin/Xamarin.Forms/blob/8c3de6fb77bded99c8d1dcb40846ba85613c2a28/Xamarin.Forms.Platform.UAP/WebViewRenderer.cs#L26) method as follows:
```

        public void LoadHtml(string html, string baseUrl)
        {
            ....
            if (!html.Contains("<base href=", StringComparison.CurrentCultureIgnoreCase))
            {
                ...
                _internalWebView = new Windows.UI.Xaml.Controls.WebView();
                ...
                _internalWebView.NavigateToString(html);
            }
            // If there is already a base tag in html, no need to waste system resources for another WebView to determine if it is there
            else
            {
                Control.NavigateToString(html);
            }
        }
```

## Intended Use Case
Loading time for Xamarin.Forms WebView increases twice when using HtmlWebViewSource. But if the provided html already contains some `<base>` tag, using the second UWP WebView is just a waste of resources - CPU, disk, network and memory, because the WebView is quite a heavy thing. If we cannot remove it completely, let's at least minimize its use by checking for existence of this tag. I'm not sure what's the best way to do it. I understand checking for substring or even regular expressions are not the best way, because this substring `<base href=` may appear in some place other than in the `<header>` - it may be a js script, or maybe even part of the html body (for instance, if developer wants his WebView to show information about using the `<base>` html tag). But we can add a simple check if there is `<base href=` tag between `<head>`  and `</head>` tags. And additionally check if this substring is not inside some `<script>` tag. If there is this tag, then don't use the second WebView. If we couldn't find it, let the second WebView do the check for us.

Or, if this method is bad, then maybe we should add some property on HtmlWebViewSource that developers would use to let the framework know that his html already has `<base>` tag, and there's no need to check if it's there.

**Comment by samhouts** [comment]
Interesting! Maybe we could do this with a platform specific on WebView for UWP.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
