### ISSUE TITLE
[Bug] Dynamically switching content resets ListView or CollectionView

### ISSUE THREAD

**Issue by Alex-Dobrynin** [xamarin/Xamarin.Forms#9399]
I have custom control as ContentView as 'parent'. It has two private fields as ContentView which are not null. They contains: first - CollectionView with many items; second - ListView (custom TreeView as ListView) with many items. When i switching parent`s Content property between those two views, CollectionView and Listview are being reset completly (CollectionView resets scroll position, TreeView as ListView also resets scroll position and resets all expanded nodes in it).
Also I noticed this behavior with WebView - it resets zoom and scroll

    public class MyCustomView : ContentView
    {
        private ContentView _collectionViewContainer;
        private ContentView _treeViewContainer;

        public void ShowCollectionView()
        {
            this.Content = _collectionViewContainer;
        }

        public void ShowTreeView()
        {
            this.Content = _treeViewContainer;
        }
    }

- Version with issue: Latest
- Last known good version: none
- Tested on UWP, but have suspicion that it has same behavior on droid and ios

**Comment by PureWeen** [comment]
@Alex-Dobrynin can you please attach a repro ?

**Comment by samhouts** [comment]
@Alex-Dobrynin  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
