### ISSUE TITLE
[Bug] CarouselView is inconsistent across iOS and Android

### ISSUE THREAD

**Issue by beeradmoore** [xamarin/Xamarin.Forms#9400]
### Description

On first display of a CarouselView on iOS and Android some events don't fire. Additionally attempting to goto the next position on iOS is non functional.

### Steps to Reproduce

1. Launch attached repro on iOS and Android
2. Examine debug log
3. Tap next
4. Examine debug log

### Expected Behavior

On launch both `TutorialCarouselView_PositionChanged` and `TutorialCarouselView_CurrentItemChanged` both fire on iOS and Android. Tapping next will take you to slide 1 (index 1, slide number 2)

### Actual Behavior

Android: 
```
(Missing PositionChanged event on launch)
TutorialCarouselView_CurrentItemChanged: from  to DataObject 0
- Tap next
Attempting to goto slide 1
TutorialCarouselView_PositionChanged: from 0 to 1
TutorialCarouselView_CurrentItemChanged: from DataObject 0 to DataObject 1
- Tap next
Attempting to goto slide 2
TutorialCarouselView_PositionChanged: from 1 to 2
TutorialCarouselView_CurrentItemChanged: from DataObject 1 to DataObject 2
```

iOS:
```
(Missing both PositionChanged and CurrentItemChanged)
- Tap next
TutorialCarouselView_PositionChanged: from 0 to 1
TutorialCarouselView_PositionChanged: from 1 to 0
TutorialCarouselView_CurrentItemChanged: from  to DataObject 0
(CarouselView shakes, but navigates back to Position 0)
- Tap Next again
TutorialCarouselView_PositionChanged: from 0 to 1
TutorialCarouselView_CurrentItemChanged: from DataObject 0 to DataObject 1 
```
Android for the most part works, iOS initial navigation does not. It does some sort of shake and you can see it navigate back to slide 0. After this first set of issues the CarouselView navigates as expected.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991537, 4.5.0.187-pre2
- Last known good version: NA
- IDE: VS for Mac 8.4.3
- Platform Target Frameworks: 
  - iOS: 13.10.0.17 
  - Android: 10.1.3.7

### Screenshots

iOS:
![Screen Recording 2020-02-03 at 10 54 23 am](https://user-images.githubusercontent.com/904737/73617533-e5def900-4673-11ea-9edc-40909b7a5473.gif)

Android: 
![Screen Recording 2020-02-03 at 10 55 01 am](https://user-images.githubusercontent.com/904737/73617535-ec6d7080-4673-11ea-8e33-d122ac0e97ed.gif)

### Reproduction Link

[CollectionViewIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4145712/CollectionViewIssue.zip)

### Workaround

Calling `GoToSlide(0)` manually  in constructor does not appear to help.

**Comment by rmarinho** [comment]
Hi @beeradmoore so the intial PositionChanged will not fire because the default value is 0 , so no position change will fire since is the same.

About the initial TutorialCarouselView_CurrentItemChanged on IOS can you try this package see if it works for you.


[Xamarin.Forms.4.4.0.993023.zip](https://github.com/xamarin/Xamarin.Forms/files/4191817/Xamarin.Forms.4.4.0.993023.zip)

**Comment by rmarinho** [comment]
About clicking the item and go to the next one seems to work for me on iOS with that package too.

**Comment by rmarinho** [comment]
Please reopen if this is still a issue. 

Thanks
