### ISSUE TITLE
[Bug] User Control BindingContext not working inside BindableLayout DataTemplate unless wrapped inside a ContentView

### ISSUE THREAD

**Issue by jackv24** [xamarin/Xamarin.Forms#9403]
### Description
Using BindingContext to follow an MVVM pattern, when using a custom control with it's own BindingContext inside the DataTemplate of a BindableLayout, Bindings inside the custom control don't bind.

### Steps to Reproduce

1. Open repro solution
2. Build & run on Android (I can't test iOS)
3. Observe example of bindings not working in BindableLayout DataTemplate, but working when wrapped in ContentView

### Expected Behavior
Custom control BindingContext should be bound properly when used inside a BindableLayout, so it's Label displays "Working!"

### Actual Behavior
Nothing is bound, Label Text is empty

### Basic Information

- Version with issue: v4.3.0.908675 & v4.4.0.991537 (nightly) (tested both)
- Last known good version: None
- IDE: Visual Studio 2019 Version 16.4.4
- Platform Target Frameworks: .NET Standard 2.0
  - iOS:  N/A
  - Android: Android 9.0 (Pie)
  - UWP:  N/A
- Affected Devices: Tested with Pixel 2 Emulator (Android 9.0 Pie Api 28) & Samsung Galaxy S10e Device (Android 10)

### Screenshots

![image](https://user-images.githubusercontent.com/2323753/73643440-6f69e780-46c3-11ea-8cb6-66fa8786baed.png)

### Reproduction Link

[repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4147225/repro.zip)

### Workaround

Wrap control with a ContentView.

**Comment by PureWeen** [comment]
@jackv24 

The problem is that your Items are just strings. I think you need to change the observable collection to your view models

On the MainPageViewModel you're instantiating it as

```C#
Items = new ObservableCollection<string>
            {
                "Dummy String",
                "Dummy String"
            };
```

if you change it to
```C#
Items = new ObservableCollection<CustomViewModel>
            {
                new CustomViewModel(),
                new CustomViewModel()
            };
```

then it works

If you have binding issues search the output for the word "Binding" and it'll tell you what isn't working

or try out this new extension
https://marketplace.visualstudio.com/items?itemName=PeterSpa.XamlBinding

**Comment by Nefiv** [comment]
I don't think it should be closed. This proves that there is an inconsistent behavior. Principle of least astonishment applies.
