### ISSUE TITLE
In correct signature found - Xamarin Forms 4.4

### ISSUE THREAD

**Issue by ramalingeswarakki** [xamarin/Xamarin.Forms#9404]
After updating to forms 4.4, Image Tap, Label Tap, etc tap gesture recognizer 'Tapped Event Args' giving 'Event handle 'TapMethodName' with correct signature not found.

All these working absolutely fine till Forms 3.0 

![LibrariesAdd](https://user-images.githubusercontent.com/17778243/73643943-6c0e3600-469a-11ea-9fbd-e573be183380.PNG)

Please look at the other libraries / nuget packages, if you guys think any conflict happening with this

**Comment by samhouts** [comment]
@ramalingeswarakki  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ramalingeswarakki** [comment]
I can't create small project because its working in newly created project.

**Comment by ramalingeswarakki** [comment]
Actually the main issue is with image rendering;
1. My last version is 3.0 and i can able to display image using url
2. Suddenly it stopped working and image is not displaying
3. When I read few blogs, they suggested me to upgrade forms version
4. Then I updated forms version to 4.4, this tap and incorrect signature issues are occurring

Please help me out with this, was struck with this issue from past 10 days; I'm literally go ahead with single line of code

**Comment by ramalingeswarakki** [comment]
Hi @samhouts 

Thanks for your response.

Finally I found issue and I resolved too.

I have updated  'TappedEventArgs' to 'EventArgs' for tap gesture events in my application and after that it worked fine. I can able to see images .
