### ISSUE TITLE
[Bug] [Android] ItemSpacing in CollectionView for Infinitive loading is not working properly 

### ISSUE THREAD

**Issue by paradisehuman** [xamarin/Xamarin.Forms#9405]
### Description
Hello. 
ItemSpacing is not working properly in an infinitive loading scenario when ItemsThreshold command triggered. 

### Steps to Reproduce

1. Run the app
2. Try to scroll down items
3. Scroll up items.  

### Expected Behavior
When ItemsThreshold reached, ItemSpacing is applied to every item.
### Actual Behavior
When ItemsThreshold reached, ItemSpacing is not applied to some of them. After reversing scroll, everything is working as we expected.  
### Basic Information

Version with issue:
4.4.0.991537
Last known good version: -
IDE: Visual Studio 2019 16.4.2
Platform Target Frameworks:
iOS: -
Android: 9.0
Nuget Packages:-
Affected Devices: Android Emulator 

### Reproduction Link

[CollectionViewTestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/4147352/CollectionViewTestApp.zip)

**Comment by hartez** [comment]
This has been fixed in 5.0.0.
