### ISSUE TITLE
[Enhancement] Extend Entry to expose an event when Clear Button is clicked

### ISSUE THREAD

**Issue by RedasP** [xamarin/Xamarin.Forms#9406]
## Summary
Extend Entry to expose an event when Clear Button is clicked

## API Changes

A ClearButtonClicked event added to Entry. It could return a bool value. If false is returned, the text is not cleared, in the other case, clear the value

## Intended Use Case

- We would like to use the Clear Button click event to hide the Entry when it is triggered

- We would like to control if the text is actually cleared or not

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
