### ISSUE TITLE
[Bug] VS4Mac requires clean between each debug session for Xamarin.Mac app

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#9409]
### Description
VS4Mac requires clean between each debug session for Xamarin.Mac app

### Steps to Reproduce

1. Create a new Coca project on an existing iOS / Droid solution
2. Set as startup
3. Run
4. Make a change
5. Run

### Expected Behavior
The change made in step 4 should be visible

### Actual Behavior
The change is not compiled

### Basic Information

- Version with issue:
- Last known good version: NA
- IDE: VS4Mac
- Platform Target Frameworks: 
- Mac: 
=== Visual Studio Community 2019 for Mac ===

Version 8.4.3 (build 12)
Installation UUID: 9fec0fa8-0dd9-46e0-987d-23174d36ca8a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.0.101
	3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3 (15712)
Build 11C29

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/johnhair/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/johnhair/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804030012
Git revision: 92973d97d9db919d8cc6d422e9c0599cf9995c47
Build date: 2020-01-24 17:47:54+00
Build branch: release-8.4
Xamarin extensions: 72721c588982f09029f051a38f484feb4c804227

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

- Nuget Packages:
- Affected Devices:

### Workaround
Clean before every build. Pain in the ar$e but it works

**Comment by VladislavAntonyuk** [comment]
you do not need clean project, it is enough to build it. Also it should be VS issue, not XF

**Comment by samhouts** [comment]
@JohnHDev Please report this from the send feedback option in Visual Studio. Thanks!

**Comment by chamons** [comment]
There is a build log the customer sent me that they do not want public. Poke me to get the URL.

**Comment by chamons** [comment]
Sorry @JohnHDev for pointing you to the wrong location for your bug.
