### ISSUE TITLE
[Bug] Frame.CornerRadius on Xamarin.Mac is ignored

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#9416]
### Description
Frame.CornerRadius on Xamarin.Mac is ignored

### Steps to Reproduce

1. Create a Cocoa project in an existing XF solution and XF to it
2. Add a frame and set corner radius to 0
3. Run it

### Expected Behavior
Frame corner should not be curved

### Actual Behavior
Frame corner is curved

### Basic Information

- Version with issue:
XF 4.3

### Workaround
None

**Comment by GalaxiaGuy** [comment]
Looking a the history, this was only implemented for the first time in 4.4:
https://github.com/xamarin/Xamarin.Forms/pull/8168

**Comment by JohnH-FF** [comment]
@GalaxiaGuy thank you, I have updated to 4.4 (takes a deep breath) and all looks ok so far.

This issue can be closed.
