### ISSUE TITLE
XF 4.5 pre2 crashes on Swipe GetSwipeItemSize 

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#9417]
iOS App crashed when Swiping on CollectionView in XF 4.5 pre2

 
### Steps to Reproduce

1.  Install XF 4.5 pre2
2.  Use Xaml below
3. 

### Actual Behavior

>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.GetSwipeItemSize (Xamarin.Forms.ISwipeItem swipeItem) [0x0001a] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:884 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.GetSwipeThreshold (Xamarin.Forms.SwipeItems swipeItems) [0x0002c] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:828 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.GetSwipeThreshold () [0x00031] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:811 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.ValidateSwipeThreshold () [0x0000e] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:701 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.ProcessTouchUp () [0x0001d] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:539 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.HandleTouchInteractions (Xamarin.Forms.GestureStatus status, CoreGraphics.CGPoint point) [0x0002a] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:482 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.HandleTouchInteractions (Foundation.NSSet touches, Xamarin.Forms.GestureStatus gestureStatus) [0x0002a] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:467 
>   at Xamarin.Forms.Platform.iOS.SwipeViewRenderer.TouchesEnded (Foundation.NSSet touches, UIKit.UIEvent evt) [0x0001c] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\SwipeViewRenderer.cs:231 
>   at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIKit/UIApplication.cs:86 
>   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIKit/UIApplication.cs:65 
>   at Max.iOS.Application.Main (System.String[] args) [0x00001] in C:\x\Mobile\Max.iOS\Main.cs:14 
> 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks:  
  - iOS:   Latest
  
- Nuget Packages:
 
 
### Reproduction Link
 
             <CollectionView Grid.Row="1"
                            ItemsSource="{Binding AddressBookRelatedItems}"
                            androidSpecific:ListView.IsFastScrollEnabled="True"
                            VerticalOptions="FillAndExpand"
                            ItemSizingStrategy="MeasureAllItems">
                   <CollectionView.ItemTemplate>
                      <DataTemplate x:DataType="addressBook:AddressBookRelatedItem">
                             <SwipeView >
                                 <SwipeView.RightItems>
                                     <SwipeItems>
                                         <SwipeItem Command="{Binding Source={x:Reference MyPage}, Path=BindingContext.DeleteAddressBookRelatedTappedCommand}" 
                                                   CommandParameter="{Binding .}" 
                                                   Text="Delete" 
                                                   IconImageSource="{StaticResource TrashCanImage}"
                                                   BackgroundColor="{DynamicResource DeleteButtonColor}" />
                                    </SwipeItems>
                                </SwipeView.RightItems>

                                <SwipeView.LeftItems>
                                    <SwipeItems>
                                        <SwipeItem
                                            Command="{Binding Source={x:Reference MyPage}, Path=BindingContext.EditAddressBookRelatedTappedCommand}"
                                            CommandParameter="{Binding .}"
                                            Text="Edit"
                                            IconImageSource="{StaticResource EditImage}"
                                            BackgroundColor="{DynamicResource SaveButtonColor}" />
                                    </SwipeItems>
                                </SwipeView.LeftItems>

**Comment by samhouts** [comment]
[Issue9417.zip](https://github.com/xamarin/Xamarin.Forms/files/4150863/Issue9417.zip)

**Comment by ianvink** [comment]
4.5 pre4 still crashes with same null error reported initially.

**Comment by ianvink** [comment]
In the production version 4.5 this still crashes all iOS apps.

:(  Thanks for all your hard work guys. Big hugs all around.

**Comment by LuckyDucko** [comment]
Can confirm I have also come across this affected behaviour in Version 4.5.0.356, while it worked on 4.4
