### ISSUE TITLE
Grid's Border

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9420]
Hi,

Please add Border properties to the Grid so it can also act as a table

This includes BorderWidth and BorderColor

and it should be like this:

BorderWidth="1,2,1,2"

to apply a width for left, top, right and bottom

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by mohachouch** [comment]
I think we can hear this request at all layouts (Grid, StackLayout ...)

**Comment by saiyamshah143** [comment]
@mohachouch @jrahma In addition, if we can have corner radius to the layouts such as Grid, Stacklayout?

**Comment by samhouts** [comment]
Duplicate of #1695
