### ISSUE TITLE
[Bug] Not able to set talk back accessibility role for the tabs in the tabbed page .

### ISSUE THREAD

**Issue by Srikanth540-L** [xamarin/Xamarin.Forms#9421]
### Description
Not able to set talk back accessibility role for the tabs in the tabbed page 
 
We are not able set the accessibility role for the tabs in the tabbed page in our Xamarin Forms android app. We have tried with AutomationId, AutomationProperties.Name and AutomationProperties.HelpText but it didn’t work. 

For example a tabbed page with tabs **Profile** and **Learn**, assuming the accessibility focus is on Profile tab.
### Expected Behavior
the talk back should read it out as "Profile Tab, double tap to activate" 
### Actual Behavior
the talk back is reading it out as "Profile, double tap to activate" 
### Basic Information

- Version with issue:  Xamarin forms 4.4
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - iOS:  
  - Android: 8,9
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: All android devices

**Comment by Srikanth540-L** [comment]
[Xamarin_Forms___TabbedPage_with_NavigationPage.zip](https://github.com/xamarin/Xamarin.Forms/files/4158016/Xamarin_Forms___TabbedPage_with_NavigationPage.zip)

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/7649
