### ISSUE TITLE
[Spec]  DependencyTemplateExtension 

### ISSUE THREAD

**Issue by danielmeza** [xamarin/Xamarin.Forms#9425]
# DependencyTemplateExtension 
Now that shell become common for all the community and has a easy way to use lazy load of component using the TemplateExtension we can add a new markup extension that can resolve the instance of the related DataTemplate using the DependencyService.Resolve method, this way we can integrate any IoC container since we can change the default factory method used by the DependencyResolver.

# API
## DependencyTemplateExtension 
A markup extensions that receive the service "Type" to be resolved and use DependencyService.Resolve to create the service.

```csharp

[ContentProperty("TypeName")]
public class DpendencyTemplateExtension : IMarkupExtension<DataTemplate>, IMarkupExtension
{
     public string TypeName { get; set; }
   
     public DependencyFetchTarget FallbackTarget { get; set; }

     public DataTemplate ProvideValue(IServiceProvider serviceProvider);
     
     object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
}
``` 

### Properties

| API | Description |
| ------------- | ------------- |
| TypeName | Store the type mame to be resolved by the IXamlTypeResolver |

# Scenarios
Use in a Shell 
## XAML Example
```xaml
<ShellContent ContentTemplate="{DenpendencyTemplate local:AboutPage}" />
```

# Backward Compatibility

Minimum API levels: 4
Breaking changes: None
Unsupported platforms: none

# Difficulty : [low]

**Comment by danielmeza** [comment]
I expose the DependencyFetchTarget FallbackTarget con contron the service instantiation

**Comment by jfversluis** [comment]
This will not happen anymore for Xamarin.Forms. If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap or open an issue with a detailed feature request. Thanks!
