### ISSUE TITLE
[Bug] PanGesture and ScrollView together works different on iOS and Android

### ISSUE THREAD

**Issue by Illedan** [xamarin/Xamarin.Forms#9434]
### Description

PanGesture on a Layout inside a ScrollView doesn't feel good to use. Would be nice if we can disable Horizontal scrolling in the ScrollView and have it only in the PanGesture and visa versa. (as it would make sense to only scroll 1 item at a time in 1 direction.)

- iOS: PanGesture consumes the whole gesture and never lets ScrollView scroll

- Android: PanGesture works if you scroll perfectly in the direction of the disabled scroll, once you change direction again you have to release and start a new scroll.

- Android: When ScrollView takes control of the gesture, PanGesture never gets the `Completed` status..

- ScrollView with `HorizontalScrollBarVisibility="Never"` is not sending gestures to the PanGesture when there is a horizontal part of a gesture. 

### Steps to Reproduce

1. Create a ScrollView
2. Make some Layout and add a PanGesture to it
3. Add the Layout as a child to ScrollView
4. Feel the difference

### Expected Behavior

Equal behavior on both platforms. And hopefully a ScrollView which doesn't steal the gesture when one direction is disabled.

### Basic Information

- Version with issue: Latest
- Last known good version: Never
- IDE: Visual Studio Mac
- Platform Target Frameworks: Latest
  - iOS:  Latest
  - Android: Latest

### Screenshots

iOS:
![iOSGestureBug](https://user-images.githubusercontent.com/1519936/73831934-7a2d9500-4807-11ea-8b18-70b140066ad7.gif)

Android:
![AndroidGestureBug](https://user-images.githubusercontent.com/1519936/73831943-7ef24900-4807-11ea-838f-611f94756ae7.gif)

### Reproduction Link

https://github.com/Illedan/skiasharp-playground/tree/master/src/Skialoading/Repro/PanRepro

### Workaround

A possible solution would be to make a Custom Renderer for ScrollView and the Layouts which needs scroll and handle it specifically for this case, but I feel it should have a persistent behavior.

**Comment by PureWeen** [comment]
duplicate
https://github.com/xamarin/Xamarin.Forms/issues/1977
https://github.com/xamarin/Xamarin.Forms/issues/5151
