### ISSUE TITLE
[Bug] [iOS] --optimize=experimental-xforms-product-type additional mtouch argument causes app crash

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#9436]
### Description

Template app crashes when the --optimize=experimental-xforms-product-type additional mtouch argument is used along with the Link Framework SDKS linker option. 

This argument is used to avoid an Apple App Store warning about UIWebView. See:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809
and
https://github.com/xamarin/Xamarin.Forms/issues/7323

### Steps to Reproduce

1. Open Visual Studio 2019 or Visual Studio for Mac
2. Create a new template blank Xamarin.Forms app
3. Select Debug  configuration and an iPhone Simulator.
4. Set the iOS project as the Startup project.
5. Update the Xamarin.Forms to version 4.5.0.187-pre2 (which is the needed version to use the `--optimize=experimental-xforms-product-type` mtouch argument.
6. Open the iOS project properties -> iOS Build page
7. Add `--optimize=experimental-xforms-product-type` to the additional mtouch arguments field
8. Select "Link Framework SdKs Only" option for the Linker Behavior. 
9. Deploy the iOS app. 

### Expected Behavior
App launches and displays initial screen

### Actual Behavior
App crashes with following exception
```
2020-02-03 10:21:13.241644-1000 App1.iOS[61152:3467260] 
Unhandled Exception:
System.MissingMethodException: Default constructor not found for type Xamarin.Forms.Platform.iOS.LabelRenderer
```

### Basic Information

- Version with issue: 4.5.0.187-pre2
- Last known good version: Unknown
- IDE: VS 2019 or VS for Mac
- Platform Target Frameworks: 
  - iOS:  Xamarin.iOS 13.10.0.17 
- Nuget Packages: Xamarin.Essentials, Xamarin.Forms

### Workaround

The workaround is to not use this additional mtouch argument and tolerate the warning from the App Store. ~~However in April Apple will start rejecting apps that have the UIWebView in them rather than just a warning.~~

* Apple won't accept **new** application using `UIWebView` in April.
* Apple won't accept application **updates using** `UIWebView` in December.

**Comment by Sumit2668** [comment]
Without adding In the Additional mtouch arguments  

> --optimize=experimental-xforms-product-type

 in release mode, So we can publish on apple store?

**Comment by PureWeen** [comment]
@jgold6 if you get a chance can you test the artifacts here?

https://dev.azure.com/xamarin/public/_build/results?buildId=13952&view=results

Let me know if those work for you?

**Comment by jgold6** [comment]
@PureWeen 

Yes, that worked to resolve this specific issue with the missing Xamarin.Forms.Platform.iOS.LabelRenderer constructor.

**Comment by PureWeen** [comment]
@Sumit2668 it's a little hard to know how Apple's algorithm will official work but as far as we know

- Apple won't accept new application using UIWebView in April.
- Apple won't accept application updates using UIWebView in December.

Is what we know from what they've indicated. 

Once we know everything with the flag is working successfully then the flag will just remain enabled by default.

**Comment by samhouts** [comment]
closed by #9505

**Comment by pavanalluri007** [comment]
it is not working for me. I get "Default constructor not found for type Xamarin.Forms.Platform.iOS.ActivityIndicatorRenderer" and app crashes

**Comment by maxiking01** [comment]
I have the same problem as pavanalluri007.

**Comment by softsan** [comment]
I have same problem in my appcenter build.

**Comment by PureWeen** [comment]
@softsan create a separate issue with a repro please

We have a lot of active projects running with this setting and haven't seen any issues yet so I'm wondering if all your projects are on the latest and greatest of Xamarin.Forms?

Or maybe you've hit a case we haven't seen?
