### ISSUE TITLE
[Android] Compiler warnings when refer 3.6.0.344 project to 4.4.0.99 project . 

### ISSUE THREAD

**Issue by Sakthivel-sync** [xamarin/Xamarin.Forms#9437]
### Description

Compiler warnings in output window when refer 3.6.0.344 project to 4.4.0.99 version protects. Warning message like "Please check  your nuget package versions are compatible".

### Steps to Reproduce

1. Create one Xamarin.Forms project with version 3.6.0.344.
2. Create another project with 4.4.0.99
3.Refer 3.6.0.44 assembly to 4.4.0.99 projects in Android.
4. Build the projects.

### Expected Behavior
Warnings need to avoid.
### Actual Behavior
Warnings are shown  liek "Please check  your nuget package versions are compatible".
### Basic Information

Version with issue: 4.4.0.991
IDE: Visual Studio 2019.
Platform Target Frameworks: Android

### Screenshots

![Screenshot (72)](https://user-images.githubusercontent.com/59697151/73846525-ae767500-484a-11ea-9a91-524f586e0a03.png)

### Reproduction Link
https://www.syncfusion.com/downloads/support/directtrac/general/ze/XamarinEntry-1186558408.zip

**Comment by samhouts** [comment]
@Sakthivel-sync The Xamarin.Forms code doesn't appear to be generating these messages. Please report this via Visual Studio. Thanks!

**Comment by Sakthivel-sync** [comment]
The warnings are thrown only when we have different xamarin.Forms version and not occurring when having same version in the custom library and sample project

**Comment by Sakthivel-sync** [comment]
The warnings are thrown only when we have different xamarin.Forms version and not occurring when having same version in the custom library and sample project

**Comment by Sakthivel-sync** [comment]
@samhouts Can you please check and reopen the bug report

**Comment by samhouts** [comment]
@Sakthivel-sync We don't really support the scenario you're describing, which is why those error messages are thrown.
