### ISSUE TITLE
[Bug] Flyout remains open on FlyoutItem double click 

### ISSUE THREAD

**Issue by ldejana** [xamarin/Xamarin.Forms#9440]
### Description
Flyout remains open on FlyoutItem double click but FlyoutIsPresented is set to false.

### Steps to Reproduce

1. Create Flyout
2. Double tap on FlyoutItem

### Expected Behavior
Close Flyout on any click or set FlyoutIsPresented to true if it needs to remain open

### Actual Behavior
Flyout remains open and FlyoutIsPresented is set to false. However, navigation still works as expected in the background of Flyout.

### Basic Information

- Version with issue: 4.4.0.991477

- Platform Target Frameworks: 
  - Android: API 23, API 28

**Comment by samhouts** [comment]
@ldejana  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by ldejana** [comment]
[FlyoutDoubleClick.zip](https://github.com/xamarin/Xamarin.Forms/files/4165149/FlyoutDoubleClick.zip)

Here it is. The attached project uses the version 4.4.0.991640.

**Comment by samhouts** [comment]
closed by #9719
