### ISSUE TITLE
[Bug] MediaElement event handlers are hidden

### ISSUE THREAD

**Issue by davidortinau** [xamarin/Xamarin.Forms#9444]
### Description

Several needed handlers are hidden in VS. 

![image](https://user-images.githubusercontent.com/41873/73896633-29d72700-4849-11ea-80f7-e98fb3464627.png)

These or similar are needed to be able to effectively:
* create a progress bar using a `Slider` that updates while playing
* create a volume bar using a `Slider`
* create a mute toggle button
* display current time and duration time that updates while playing

Event handlers are fine. BindableProperties are even better!

**Comment by rmarinho** [comment]
Those are used for comunicate with the renderers no? Not to be used by users  if i understand.

right @peterfoot  ?

**Comment by peterfoot** [comment]
Those are for internal communication with the renderer. You can bind the Volume property to a slider.

**Comment by peterfoot** [comment]
Now I'm at my computer, here is a longer answer to your requests. Where possible bindable properties are used - Volume, State etc. Position is a special case, it is not automatically updated when media is playing so instead you would need to setup a timer and poll the property. The property changed event only fires at key moments such as play/pause/ended etc. This is the same as the UWP/WPF controls. If the renderer were to implement this it would be on a fixed interval which may not suit your requirements (updating the property every millisecond would be overkill for most uses).

**Comment by rmarinho** [comment]
Yap I agree. This is not a bug
