### ISSUE TITLE
[Enhanement] Enable RefreshView on UWP to work with the mouse

### ISSUE THREAD

**Issue by freever** [xamarin/Xamarin.Forms#9446]
### Description
Basic refresh view out of the box works on iOS and Android, but not on UWP

### Steps to Reproduce

1. Open attached solution
2. Run on ios and Android - pull to refresh reloads the page
3. Run on UWP - pulling in any direction has no effect

### Expected Behavior
The page should drag down with the mouse and reload the page on UWP

### Actual Behavior
Nothing happens

### Reproduction Link
[TestRefreshView.zip](https://github.com/xamarin/Xamarin.Forms/files/4163241/TestRefreshView.zip)

### Workaround
I have not found a workaround

**Comment by PureWeen** [comment]
I've changed this over to an enhancement. We're using the native WinUI RefreshView and that control only works with touch gestures not the mouse so we would need to extend it.

**Comment by cpraehaus** [comment]
Enabling mouse pointer for pull-to-refresh is not in the spirit of UWP: for a desktop user - its not obvious that pull-to-refresh is present and how he/she can activate it. Better to provide an additional button for desktop apps. But this is probably nothing we want/should add in XF natively. How to label/icon/position the refresh button - those aspects should be left up to the app. And the rest can already be achieved with XF ``RefreshView`` out-of-the-box - no need for change: you just need a RefreshCommand and plumbing together ``IsRefreshing`` with a proper "IsBusy/IsExecuting" property on your view model.

**Comment by varunvir** [comment]
I'am also facing same issue, even rendrers are also not working

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
