### ISSUE TITLE
[Bug] passing uri string as Parameter in Shell navigation removes slash from uri

### ISSUE THREAD

**Issue by begreal** [xamarin/Xamarin.Forms#9449]
# Description
When navigating to a new page using Shell navigation, passing a Uri as QueryParameter for the new Page removes one of the double slashes in the uri. so "https://..." turns into https:/...".

Here is the sample code:
```
public async void OnCatalogImageTapped(object sender, EventArgs e)
{
    var imageUri = "https://i.picsum.photos/id/545/800/600.jpg"
    await Shell.Current.GoToAsync($"CatalogImagePage?image={imageUri}");
}

[QueryProperty("Image", "image")]
public partial class CatalogImagePage : ContentPage
{
    private string _image;
    public string Image
    {
        get
        {
            return _image;
        }
        set
        {
            _image = Uri.UnescapeDataString(value);
            ImageControl.Source = ImageSource.FromUri(new Uri(_image));
        }
    }
}
```
The ImageSource.FromUri method crashes the app with a TargetInvocationException because no valid Uri is given as a parameter.
The Uri.UnescapeDataString method is not causing the removal of the slash, i checked it multiple times!

Shell is removing the slash while passing the string to the new Page.
Are there any suggestions or workarounds how i can solve this?

**Comment by samhouts** [comment]
@begreal  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by begreal** [comment]
I moved my way around this issue with encoding the url first, then decoding it later when the new Page consumes the parameter in the setter method of the corresponding Property.

Here is the code for it:
```
        public async void OnCatalogImageTapped(object sender, EventArgs e)
        {
                var imageUri = HttpUtility.UrlEncode("https://i.picsum.photos/id/545/800/600.jpg");
                await Shell.Current.GoToAsync($"CatalogImagePage?image={imageUri}");
        }

[QueryProperty("Image", "image")]
public partial class CatalogImagePage : ContentPage
{
    private string _image;
    public string Image
    {
        get
        {
            return _image;
        }
        set
        {
            ImageControl.Source = ImageSource.FromUri(new Uri(HttpUtility.UrlDecode(value)));
        }
    }
}
```

**Comment by begreal** [comment]
@samhouts :
Here is the sample code for the Bug

[ShellNavigationBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4169806/ShellNavigationBug.zip)
