### ISSUE TITLE
Polyline Geopath not initialized at run time  Xamarin.Forms.Map

### ISSUE THREAD

**Issue by USAMA-app** [xamarin/Xamarin.Forms#9450]
// Points are Google overview_polyline encoded that i decode via library 
 var CONVTPOINT = (from xp in Points
                                      select new Position(xp.Latitude, xp.Longitude)).ToList();
// Polyline Object 
  var d = new Polyline()
                    {
                        StrokeColor = Color.Black,
                        StrokeWidth = 12,
                        Geopath = CONVTPOINT
                    };

**Comment by jcmanke** [comment]
Polyline.Geopath is a get-only property. You can't set the property, you have to add your items to the existing list.

**Comment by USAMA-app** [comment]
thanks
