### ISSUE TITLE
[Bug] RelativeLayout Constraint can not go back to zero

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#9451]
Setting RelativeLayout WidthConstraint on a view to zero does not work
### Steps to Reproduce
```CSharp
RelativeLayout.SetWidthConstraint(view, Constraint.RelativeToParent(rl => rl.Width / 2));
await Task.Delay(3000);
double x = 0;
RelativeLayout.SetWidthConstraint(view, Constraint.Constant(x));
//RelativeLayout.SetWidthConstraint(view, Constraint.RelativeToParent(rl => x));
//RelativeLayout.SetWidthConstraint(view, Constraint.FromExpression(() => x));
```

### Expected Behavior
Width go back to zero and the view disappears
### Actual Behavior
The previous width is preserved even though we set it to zero

**Comment by samhouts** [comment]
@MhAllan  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by MhAllan** [comment]
[RelativeLayoutConstaintZero.zip](https://github.com/xamarin/Xamarin.Forms/files/4169639/RelativeLayoutConstaintZero.zip)

Here it is, a relative layout, if you tap on it, it will expand a frame child then shrink it (by setting the width) after 3 seconds and that will work unless you want to shrink it to zero.

**Comment by PureWeen** [comment]
Same behavior when tested on iOS

Haven't tested on Android but I'm assuming it's the same everywhere

**Comment by MhAllan** [comment]
@PureWeen I tested on Android. Test above was ok.

**Comment by MhAllan** [comment]
@PureWeen I tested on Android. No problem on it.
