### ISSUE TITLE
[Bug] ContentPage Contents Don't Update inside MasterDetailView on MacOS

### ISSUE THREAD

**Issue by jbrot** [xamarin/Xamarin.Forms#9455]
### Description

Using Xamarin Forms on MacOS, if you set MasterDetailView.Detail to a ContentPage, and then change ContentPage.Content, the ContentPage is rendered as empty until the window is resized (then it renders as normal).

### Expected Behavior

After changing ContentPage.Content to a new View, the new View should be displayed immediately.

### Actual Behavior

When ContentPage.Content is changed, the ContentPage is rendered blank until the window is resized.

### Basic Information

- Version with issue:
- IDE: Visual Studio for Mac 8.4.4
- Platform Target Frameworks:
  - Xamarin.Mac:  6.10.0.17
  - Xamarin.Forms: 4.4.0.991640

### Screenshots

Starting State: ![Starting State](https://raw.githubusercontent.com/jbrot/Xamarin-Bug-Reproc/master/Screenshots/Start.png)
After Changing Content (new contents aren't rendered): ![Buggy State](https://raw.githubusercontent.com/jbrot/Xamarin-Bug-Reproc/master/Screenshots/Actual.png)
Expected result (achieved by resizing window): ![Expected State](https://raw.githubusercontent.com/jbrot/Xamarin-Bug-Reproc/master/Screenshots/Expected.png)

### Reproduction Link

I've uploaded a minimal project to reproduce this bug to my GitHub: https://github.com/jbrot/Xamarin-Bug-Reproc.

The relevant files are:
 - https://github.com/jbrot/Xamarin-Bug-Reproc/blob/master/MinReproc/MainPage.xaml which defines the layout
- https://github.com/jbrot/Xamarin-Bug-Reproc/blob/master/MinReproc/MainPage.xaml.cs which 
updates ContentPage.Content.

### Workaround

This issue can be somewhat worked around by resizing the MasterDetailPage after updating ContentPage.Content. For instance, I'm using the following subclass of ContentPage:
```
    public class WorkaroundContentPage : ContentPage
    {
        public WorkaroundContentPage ()
        {
        }

        protected override void OnChildAdded (Element child)
        {
            base.OnChildAdded(child);

            // HACK: For some reason, after changing Content, the new content won't
            // render until we resize. So, we force an imperceptible resize to cause
            // it to show immediately.
            var mdv = Parent as MasterDetailPage;
            var delta = mdv.Y == 0 ? 1 : -1;
            mdv.Layout(new Rectangle(mdv.X, mdv.Y + delta, mdv.Width, mdv.Height - delta));
        }
    }
```

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
