### ISSUE TITLE
[Enhancement] SwipeView Pull To Close

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#9461]
Is there any reason why you can't swipe to close the SwipeView similar to the context actions on a ListView?

My normal reaction to wanting to close a a context action is to swipe the other way but instead I have to tap and It took me a while to work out that I actually had to do that.

**Comment by daves1992** [comment]
![SwipeView](https://user-images.githubusercontent.com/29727003/74038833-b2280a00-49b8-11ea-85ca-5d773646a1cd.png)

Oh and if you try and program around it you get some pretty humorous results!

                                <SwipeView.RightItems>
                                    <SwipeItem Text="Assign" IconImageSource="Tick.png" BackgroundColor="{Binding Settings.DefaultThemeColor}" Command="{Binding Path=BindingContext.AssignCommand, Source={x:Reference CPPickingAdmin}}" CommandParameter="{Binding .}"/>
                                </SwipeView.RightItems>
                                <SwipeView.LeftItems>
                                    <SwipeItem Text=""/>
                                </SwipeView.LeftItems>

**Comment by samhouts** [comment]
closed by #9664
