### ISSUE TITLE
[Bug] [iOS] Voiceover (iOS) accessibility tools read wrong value sometimes in ListView with uneven rows/

### ISSUE THREAD

**Issue by jgold6** [xamarin/Xamarin.Forms#9474]
### Description
Navigating through the items in a ListView with Voiceover (iOS) accessibility tool, the wrong item will sometimes be spoken in a ListView with uneven rows. 

### Steps to Reproduce

1. Open the attached test project.
2. Deploy to  iOS device (only devices have Voiceover feature)
3. On the device, open the Settings -> Accessibility page and turn on VoiceOver
     (you now have to single tap to select an item and double tap to "click" it, and to go back to home screen on a device with no home button, swipe up from the bottom slowly until you feel a haptic then let go)
4. Open the TestVoiceOverListView app on the device
5. Swipe right on the screen to navigate down the list item by item until you get to the end of the list.

### Expected Behavior
The Voiceover screen reader should read the title of each item in the list correctly.

### Actual Behavior
Somewhere around item 19 you should get some incorrect item names read, i.e. when Item 19 gets selected, the Voiceover says "Item 17". 

### Add'l Notes
Which items are read incorrectly varies, but on first run it seems to be consistently Item 19 and Item 20 that are read incorrectly. But this will vary if the row sizes change or if you jump to an item by tapping directly on it. That is why I seeded the random number generator that produces the random font size so that the rows will be uneven. By seeding it, I get the same numbers on each run for consistent results. If you change the seed number, or don't seed it, the exact items that are read incorrectly will change and sometimes issue will not occur. 

Also worth noting is that if I lessen the range of font/row sizes, then the issue seemingly occurs less frequently, until it disappears with fixed row sizes.  

### Basic Information

- Version with issue: 4.4.0.991640 and 4.5.0.266-pre3
- Last known good version: Unknown
- IDE: VS for Mac
- Platform Target Frameworks: 
  - iOS:  13.10.0.17
  - Nuget Packages: Xamarin.Essentials
- Affected Devices: iOS devices

### Reproduction Link

[TestVoiceOverListView.zip](https://github.com/xamarin/Xamarin.Forms/files/4172670/TestVoiceOverListView.zip)

### Workaround
I found a workaround which is to explicitly bind AutomationProperties.Name to the same value that the item title is binding to. Then I get the expected behavior.

**Comment by PureWeen** [comment]
Closing this issue
- @jgold6 indicated a workaround that can be applied to ListView
- Guidance going forward is to use CollectionView so we are focusing on fixing a11y issues with CollectionView currently and most likely won't make any additional changes to ListView

https://github.com/xamarin/Xamarin.Forms/issues/12252
