### ISSUE TITLE
[Bug] iOS Shell - ToolbarItems not updating when using TabBar

### ISSUE THREAD

**Issue by Hottemax** [xamarin/Xamarin.Forms#9483]
### Description

In a Shell application with nested Tabs, toolbar items are not updated correctly when navigating to Page in iOS. It works correctly on Android

### Steps to Reproduce

Public repository: https://gitlab.com/Hottemax/demotabbug

1. Start iOS application
2. Navigate to (bottom) Combined tab.
3. Toggling between "Browse" and "About" (top tabs) does not update the toolbar item (it only gets updated when you navigate away from the page (for example via the bottom tab), and then come back to it

- Created from Visual Studio default Xamarin.Forms shell project template.
- Merely added a third bottom tab and toolbar items to the Items/About pages.

- AppShell.xaml:
 ```
<TabBar>
        <Tab Title="Browse" Icon="tab_feed.png">
            <ShellContent Title="Browse" ContentTemplate="{DataTemplate local:ItemsPage}" />
        </Tab>
        <Tab Title="About" Icon="tab_about.png">
            <ShellContent ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
        <Tab Title="Combined">
            <ShellContent Title="Browse" ContentTemplate="{DataTemplate local:ItemsPage}" />
            <ShellContent Title="About" ContentTemplate="{DataTemplate local:AboutPage}" />
        </Tab>
    </TabBar>
```
- AboutPage.xaml:
```
<ContentPage.ToolbarItems>
        <ToolbarItem Text="AboutToolbarItem" />
 </ContentPage.ToolbarItems>
```

- ItemsPage.xaml:
```
<ContentPage.ToolbarItems>
        <ToolbarItem Text="ItemsToolbarItem" />
 </ContentPage.ToolbarItems>
```

### Expected Behavior

Toolbar item gets updated when navigating to tab.

### Actual Behavior

Toolbar item does not update (always delayed by one step).

### Basic Information

- Version with issue: latest (4.4.0.991640), latest pre-release (4.5.0.266-pre3)
- Last known good version: ?
- IDE: Visual Studio
- Platform Target Frameworks: 
  - iOS:  all
- Nuget Packages:
- Affected Devices:

### Reproduction Link

Public repository: https://gitlab.com/Hottemax/demotabbug

**Comment by samhouts** [comment]
closed by #9628
