### ISSUE TITLE
[Bug] Picker.ItemDisplayBinding not responding to INotifPropChanged

### ISSUE THREAD

**Issue by viktorszekeress** [xamarin/Xamarin.Forms#9484]
### Description
I have a Picker, which items are bound to a collection of viewmodels. Each viewmodel has `Text` property, which is displayed in UI. Thus, I set `Picker.ItemDisplayBinding` to `{Binding Text}`.

This works for the first time, `Picker` displays a value from `Text` property. The problem is, when I change `Text` property later - change is not reflected in the Picker, it still displays initial values. 

### Steps to Reproduce

1. Open the attached solution and run the app
2. Observe the texts in Picker (selected item and all items after clicking on Picker)
3. Click 'Randomize' button that will change `ItemViewModel.Text` for each item to some random number
4. Next texts are not reflected in UI

### Expected Behavior
Picker should update all texts (selected item + list of items) to new random numbers.

### Actual Behavior
Initial values are displayed.

### Basic Information

- Version with issue: 4.4.0.991640
- Platform Target Frameworks: 
  - tested only on Android

### Screenshots
![ItemDisplayBinding_01](https://user-images.githubusercontent.com/45604126/74088672-0aced400-4a99-11ea-9d41-d95d38cdeb27.jpg)

![ItemDisplayBinding_02](https://user-images.githubusercontent.com/45604126/74088675-102c1e80-4a99-11ea-8e7b-556be6ab8237.jpg)

![ItemDisplayBinding_03](https://user-images.githubusercontent.com/45604126/74088676-128e7880-4a99-11ea-9d72-ab232ce36ff9.jpg)

![ItemDisplayBinding_04](https://user-images.githubusercontent.com/45604126/74088679-1621ff80-4a99-11ea-89aa-432632775d91.jpg)

![ItemDisplayBinding_05](https://user-images.githubusercontent.com/45604126/74088686-2d60ed00-4a99-11ea-837f-bae13f2db321.jpg)

### Reproduction Link
[ItemDisplayBinding.zip](https://github.com/xamarin/Xamarin.Forms/files/4174659/ItemDisplayBinding.zip)

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/4077
