### ISSUE TITLE
[Enhancement] DependencyService.Register should accept custom objects

### ISSUE THREAD

**Issue by BlueRaja** [xamarin/Xamarin.Forms#9492]
## Summary
I'm amazed this has never been suggested (that I can find):  `DependencyService.Register` should have an overload the accepts a custom object

## API Changes
```
DependencyService.Register<IMyType>(someMyTypeInstance);
```

## Intended Use Case
This is essential for unit-testing any class which relies on `DependencyService` - you need to be able to mock the interface and inject it.

```
// Example using Moq
IMyType instance = new Mock<IMyType>();
DependencyService.Register<IMyType>(instance.Object);
```

Currently there's no workaround, you just need to use a different IoC container altogether if you want to write unit tests.

**Comment by ahoefling** [comment]
I was going to suggest this last night, my only suggestion to the proposal

## Suggestion to Spec
```c#
void RegisterInstance<T>(T instance);
```

## Usage
The usage will be the same as mentioned in the original post
```c#
IMyType myInstance = new MyType();
DependencyService.RegisterInstance<IMyType>(myInstance);
```

## Reason for Name Change
Many of the Dependency Injection libraries that are available in the .NET Ecosystem allows the code to register different types
- standard type registeration
- singleton registration
- instance registration

When you use an Instance registration the naming standard that is common among these libraries is `RegisterInstance`.

**Comment by VladislavAntonyuk** [comment]
What about instance lifetime? My proposal:
`
void Register<T>(T instance, Lifetime instanceLifetime);
`
Where Lifetime is enum: Singleton, Transient

**Comment by BlueRaja** [comment]
The `Lifetime` thing seems like a completely separate suggestion, since it also applies to the existing `Register` function. I'd suggest opening a separate ticket for that.

**Comment by ahoefling** [comment]
Personally I would prefer we wrap the DependencyService with the Microsoft.Extensions.DependencyInjection.Abstractions project. It allows the platform to extend how Dependency Injection works without changing anything. I understand that is a massive breaking change to remove the current API and really isn't part of this issue.

My recommendation comes from seeing it done this way in several popular Dependency Injection containers including the official library from Microsoft ([Microsoft.Extensions.DependencyInjection](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1)).

**Comment by brentpbc** [comment]
Does `DependencyService.RegisterSingleton<T> (T instance)` work as work around? I got here because I was trying to use the 1 class to implement multiple interfaces but I only wanted 1 instance of my Concrete class to be returned when retrieving the object through dependency injection.
e.g.:
```
var testService = new TestContcreteService() {
Name = "New Instance of test Concrete Service!"};
msg = $"My Name:\r\n {testService.Name}\r\n";
msg += $"Guid:\r\n {testService.MyGuid}\r\n";
DependencyService.RegisterSingleton<ITestServiceBase>(testService);
DependencyService.RegisterSingleton<ITestService1>(testService);
DependencyService.RegisterSingleton<ITestService2>(testService
ITestService1 testService1 = DependencyService.Get<ITestService1>();
msg += testService1.GetTestService1Message() + "\r\n";            
ITestService2 testService2 = DependencyService.Get<ITestService2>();
msg += testService2.GetTestService2Message() + "\r\n";
ITestServiceBase testBase = DependencyService.Get<ITestServiceBase>();
//var test = DependencyService.Resolve<ITestServiceBase>();
msg += testBase.GetTestBaseMessage();
System.Diagnostics.Debug.WriteLine(msg);
```

Classes and Interfaces:
```
public interface ITestServiceBase
    {
        string GetTestBaseMessage();
    }

public interface ITestService1 : ITestServiceBase
    {
        string GetTestService1Message();
    }

public interface ITestService2
    {
        string GetTestService2Message();
    }

public class TestContcreteService : ITestService1,ITestService2
    {
        public string Name = "Not set!";
        public Guid MyGuid {get; set;}
        public TestContcreteService()
        {
            MyGuid = Guid.NewGuid();
        }

        public string GetTestService1Message()
        {
            return $"Interface1Message:\r\n{MyGuid}";
        }

        public string GetTestService2Message()
        {
            return $"Interface2Message:\r\n{MyGuid}";
        }

        public string GetTestBaseMessage()
        {
            return $"GetTestBaseMessage:\r\n{MyGuid}";
        }       
    }
```

Output:
```
My Name:
 New Instance of test Concrete Service!
Guid:
 1bd345d7-f3c4-4963-8c47-76da655a4ce4
Interface1Message:
1bd345d7-f3c4-4963-8c47-76da655a4ce4
Interface2Message:
1bd345d7-f3c4-4963-8c47-76da655a4ce4
GetTestBaseMessage:
1bd345d7-f3c4-4963-8c47-76da655a4ce4
```

**Comment by jfversluis** [comment]
This won't be happening for Forms anymore and I think isn't really relevant for .NET MAUI as we want to use different DI things there. Thanks all for the suggestions and input!
