### ISSUE TITLE
[Bug] Xamarin.Forms.sln error parse for Xamarin.Forms.Platform.UAP.csproj

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/Xamarin.Forms#9493]
### Description
I can't build **Xamarin.Forms.sln** because - Xamarin.Forms.Platform.UAP is not loaded.

Error:
```
F:\GitHub\Xamarin.Forms\Xamarin.Forms.Platform.UAP\Xamarin.Forms.Platform.UAP.csproj : 
error  : The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  
C:\Users\Konstantin\.nuget\packages\microsoft.ui.xaml\2.1.190606001\build\Microsoft.UI.Xaml.props
```

### Steps to Reproduce

1. Open solution **Xamarin.Forms.sln**  in VS 2019
2. Check loaded projects.

**Comment by samhouts** [comment]
@KSemenenko Which branch? Try `git clean -fdx` before you build. Thanks!

**Comment by KSemenenko** [comment]
@samhouts this one https://github.com/xamarin/Xamarin.Forms/pull/8298
it was working, but I merged develop several times, and now it isn't :)
I will try  ``` git cleat ``` 
thanks

**Comment by KSemenenko** [comment]
all is ok :) @samhouts thanks!
