### ISSUE TITLE
[Bug] Shell Icons via FontImageSource not displaying in v4.5 pre3

### ISSUE THREAD

**Issue by mjfreelancing** [xamarin/Xamarin.Forms#9498]
### Description
Icons in shell flyout and bottom tabs are not displaying.

### Steps to Reproduce

1. Add FontImageSource icons to shell menu / tab
2. Observice not being displayed 

### Expected Behavior
The icons should be visible in the flyout as well as bottom tabs

### Actual Behavior
Icons are not visible

### Basic Information

- Version with issue: 4.5.0.266-pre3
- Last known good version: 4.4.0.991640 (I haven't tested other pre-releases)
- IDE: VS 2019, Windows 10
- Platform Target Frameworks: Have only tested Android

### Screenshots

**Output from v4.4**
![before1](https://user-images.githubusercontent.com/17043225/74151733-ed4c6680-4c60-11ea-8d49-2f8f50c815db.jpg)
![before2](https://user-images.githubusercontent.com/17043225/74151740-f2111a80-4c60-11ea-9855-dcd0de305cf6.jpg)

**Output from v4.5**
![after1](https://user-images.githubusercontent.com/17043225/74151900-4d430d00-4c61-11ea-96b6-d72f1fea2119.jpg)
![after2](https://user-images.githubusercontent.com/17043225/74151906-516f2a80-4c61-11ea-9d96-517f1401cb6a.jpg)

### Reproduction Link
[IconsNotVisible.zip](https://github.com/xamarin/Xamarin.Forms/files/4180859/IconsNotVisible.zip)

### Workaround
None

**Comment by mjfreelancing** [comment]
I just realized I added the sample at v4.4 to show it working - update to v4.5-pre3 to see the problem.

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/9371
