### ISSUE TITLE
[Bug] TapGesture on Xamarin.Mac XF is ignoring TranslationY

### ISSUE THREAD

**Issue by JohnHDev** [xamarin/Xamarin.Forms#9503]
### Description
When a view has a TranslationY value and a tap gesture, the area that responds to the tap gesture is the views original position, not where the view is actually displayed.

### Steps to Reproduce

1. Add a view to the top of a stack layout
2. Set the view TranslationY to 50
3. Add a tap gesture
4. Run the XF cocoa project
5. click the view

### Expected Behavior
Code in tap gesture triggered

### Actual Behavior
Code is not triggered until you click the top of the stack layout

### Basic Information

- Version with issue: 4.4.0..991537
- Last known good version:
- IDE: VS4Mac
- Platform Target Frameworks: 
Mac
- Nuget Packages:
- Affected Devices:

### Workaround
None!

**Comment by samhouts** [comment]
@JohnHDev  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@JohnHDev  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by JohnHDev** [comment]
Yes, it is still an issue. Please reopen and I will submit a repo for you.

**Comment by JohnHDev** [comment]
More information for you, TranslationY is ignored in Xamarin.Mac.
The reason it works for us is because we are using an animation, e.g:
`            _frame.TranslateTo(0, 20, 0); `

**Comment by JohnHDev** [comment]
Paste the following code into the constructor of a content page. Then run it on a mac, click on the tap half of the box view to see the tap gesture working. Tap on the bottom half of the box view and the tap gesture doesn't trigger. 

            ```
var box = new BoxView()
            {
                HorizontalOptions = LayoutOptions.Start,
                VerticalOptions = LayoutOptions.Start,
                HeightRequest = 100,
                WidthRequest = 100,
                BackgroundColor = Color.Blue,
                CornerRadius = 10
            };

            var gesture = new TapGestureRecognizer()
            {
                Command = new Command(() => Console.WriteLine("Tapped"))
            };

            box.GestureRecognizers.Add(gesture);
            box.TranslateTo(0, 50, 0);
            
            Content = box;
```
