### ISSUE TITLE
[Bug|iOS] Layout inside DataTemplate has 1px left margin

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#9507]
### Description
Whenever I add any kind of layout within a DataTemplate on a CollectionView, I end up with a 1px margin on the right side of the list.

### Steps to Reproduce

1. Add a CollectionView to a page
2. Set the datatemplate to the following
<img width="976" src="https://user-images.githubusercontent.com/471626/74203657-3979b580-4c25-11ea-8ffc-792d01162e7f.png">
3. Observe the gap  
<img width="957" src="https://user-images.githubusercontent.com/471626/74203843-d63c5300-4c25-11ea-9543-7016870ac591.png">
note: if you remove the View
<img width="957" src="https://user-images.githubusercontent.com/471626/74203684-531afd00-4c25-11ea-8be4-1ef91a644378.png">
Then the gap is gone
<img width="957" src="https://user-images.githubusercontent.com/471626/74203693-5adaa180-4c25-11ea-9daa-090de844fe45.png" />

### Expected Behavior
There should be no spacing on the left side of the collection items

### Actual Behavior
There is a 1px space between the edge of the items and the edge of the screen

### Basic Information

- Version with issue: `<PackageReference Include="Xamarin.Forms" Version="4.4.0.991537" />`
- Last known good version: ??
- IDE: Jetbrains Rider
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: n/a
  - UWP:  n/a
- Android Support Library Version: n/a
- Nuget Packages:
- Affected Devices: All iOS devices

**Comment by samhouts** [comment]
@ChaseFlorell  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by rmarinho** [comment]
Duplicated of #8961
