### ISSUE TITLE
[Bug] [ERROR] Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.UpdateToolbar () 

### ISSUE THREAD

**Issue by srdmnc** [xamarin/Xamarin.Forms#9509]
### Description
After updating my XF to 4.4 (which forced me to update my android support libraries to 28.0.0.3), my app began to have weird behaviors (i.e. missing back button in the navigation bar, cannot go back to the previous page) and it started to crash in some instances. Most of the crash occurs when page navigation is triggered.

Stacktrace
```xml
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.UpdateToolbar () [0x00078] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:980 
[mono-rt]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.SwitchContentAsync (Xamarin.Forms.Page page, System.Boolean animated, System.Boolean removed, System.Boolean popToRoot) [0x0017b] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:860 
[mono-rt]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPushAsync (Xamarin.Forms.Page view, System.Boolean animated) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:614 
[mono-rt]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.PushViewAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:161 
[mono-rt]   at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnPushed (System.Object sender, Xamarin.Forms.Internals.NavigationRequestedEventArgs e) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:619 
[mono-rt]   at Xamarin.Forms.NavigationPage.PushAsyncInner (Xamarin.Forms.Page page, System.Boolean animated) [0x00059] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:421 
[mono-rt]   at Xamarin.Forms.NavigationPage.PushAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x0014e] in D:\a\1\s\Xamarin.Forms.Core\NavigationPage.cs:242 
[mono-rt]  ---
[mono-rt]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.37(intptr,intptr)
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.DynamicMethodNameCounter.37(intptr,intptr)
```
### Steps to Reproduce

1. Update XF to version 4.4+
2. Update android support libraries 28.0.0.3
3. Run app

### Expected Behavior
App will work / run fine.
### Actual Behavior
App crashes at some instances.
### Basic Information

- Version with issue: v4.4.0.991640
- Last known good version: 4.1.0.581479
- IDE: Vs Community 2019
- Platform Target Frameworks: 
  - iOS:  
  - Android:   9
- Android Support Library Version:  28.0.0.3
- Affected Devices: All

**Comment by PureWeen** [comment]
@srdmnc can you specify the specific version of 4.4+ and attach a repro?

**Comment by srdmnc** [comment]
@PureWeen XF v4.4.0.991640, sorry I can't attach a repro.

**Comment by PureWeen** [comment]
Without a repro or additional context it's going to be really hard to figure out your issue.

Here's the line it failing on and it'll be kind of hard to ascertain why
https://github.com/xamarin/Xamarin.Forms/blob/release-4.4.0-sr3/Xamarin.Forms.Platform.Android/AppCompat/NavigationPageRenderer.cs#L860

**Comment by srdmnc** [comment]
Hi, I'm also getting this in error.
Could not resolve type with token 0100004c from typeref (expected class 
'Xamarin.Forms.Xaml.Diagnostics.VisualDiagnostics' in assembly 'Xamarin.Forms.Core, 
Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')
```

**Comment by PureWeen** [comment]
> Could not resolve type with token 0100004c 

That comes from your libraries being out of sync

1) make sure you have the same XF version installed into all projects
2) delete all your obj/bin directories and then try compiling the project again

**Comment by srdmnc** [comment]
I downgraded my XF to v4.1.0.581479 and everything works fine now. This is a dirty workaround and is definitely not a fix. I'll try to replicate this scenario in a sample repo and will update you on this. Thank you for your assistance!

**Comment by PureWeen** [comment]
@srdmnc if you can attach a verbose build log when using 4.4 or 4.5 pre4 that might reveal something useful

**Comment by jefhai** [comment]
> > Could not resolve type with token 0100004c
> 
> That comes from your libraries being out of sync
> 
> 1. make sure you have the same XF version installed into all projects
> 2. delete all your obj/bin directories and then try compiling the project again

Thanks- its not obvious this was the issue given the error message. Would be great if we can get an out of sync error instead of cryptic ones. Will be on my list of things to check when I see errors like this.

**Comment by samhouts** [comment]
@srdmnc  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
