### ISSUE TITLE
[Bugs] [iOS] WKWebView adds extra space when the cursor is placed in last line

### ISSUE THREAD

**Issue by dillibabun** [xamarin/Xamarin.Forms#9510]
### Description
We have a contenteditable div in a html and loaded to a WKWebView. When placing the cursor to the last line, extra space is added at the bottom of webview.
### Steps to Reproduce

1. Create a Forms App with Custom Webview renderers and use WKWebView for iOS.
2. Input HTML of WebView must have a content editable div.
3. Enter the text in Webview in runtime. Place the cursor in different position.

### Expected Behavior
Extra space should not be added.Focus must be placed above the keyboard.
### Actual Behavior
While placing a cursor in last line, extra space is added above the keyboard and webview is pushed up.
### Basic Information
- IDE:
- Platform Target Frameworks: 
  - iOS:  from 11.1 to latest.

### Screenshots
Please find the webview different behavior based on cursor position.
Cursor in middle:
![IMG_0646](https://user-images.githubusercontent.com/34679378/74213901-4ba93180-4cc1-11ea-8fb2-adcb20b820b1.jpg)

Cursor in last before line:
![IMG_0648](https://user-images.githubusercontent.com/34679378/74213898-4a780480-4cc1-11ea-8613-27a124b40317.jpg)

Cursor in last line:
![IMG_0647](https://user-images.githubusercontent.com/34679378/74213895-48ae4100-4cc1-11ea-90ea-4a3ef342d70d.jpg)

**Comment by samhouts** [comment]
@dillibabun  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@dillibabun  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
