### ISSUE TITLE
CollectionView not applying "selected" VisualState to pre-selected items (multi-select)

### ISSUE THREAD

**Issue by lilgrassin** [xamarin/Xamarin.Forms#9511]
### Description
When using a customized VisualState on a CollectionView, items that passed to the "SelectedItems" property initially receive the "normal" styling until any item is (de)selected. Only then do all selected items (including pre-selected) receive the "selected" styling.

### Steps to Reproduce

1. Create CollectionView with populated SelectedItemsProperty.
2. Apply VisualState custom styling to "selected" items (or to "normal" items)
3. Reload page
4. Select or deselect any item

### Expected Behavior
Pre-selected items in CollectionView receive "selected" state immediately on page loading.
(Re: GIF: pre-selected items should immediately appear blue, not grey)

### Actual Behavior
Pre-selected items receive "normal" state until a selection event occurs.
(Re: GIF: pre-selected items remain grey until (de)selection occurs)

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version: N/A
- IDE: Visual Studio Community for Mac 2019
- Platform Target Frameworks:
  - iOS:  13.10.0.17
- Nuget Packages:
  - Xamarin.Essentials: 1.3.1
  - sqlite-net-pcl: 1.6.292
  - SQLiteNetExtensions: 2.1.0
  - SQLiteNetExtensions.Async: 2.1.0
- Affected Devices:
  - iPhone 8 (simulator)

### Screenshots

![xambug](https://user-images.githubusercontent.com/11161002/74214336-022df780-4c6b-11ea-882e-6574bf2a2a47.gif)

#### In ViewModel
```
public class TagEntry
{
    public string Name { get; set; }
}

TagEntry tag1 = new TagEntry { Name = "tag1";}
TagEntry tag2 = new TagEntry { Name = "tag2";}
TagEntry tag3 = new TagEntry { Name = "tag3";}

ObservableCollection<string> Tags = new ObservableCollection<string>
{ 
    tag1,
    tag2,
    tag3
};
List<object> SelectedTags = new List<object>
{ 
    tag1,
    tag3
};
```

#### In page XAML
```
    <ContentPage.Resources>
        <Style TargetType="StackLayout">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal"/>
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="LightSkyBlue" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>
    <CollectionView Margin="20"
              SelectionMode="Multiple"
              ItemsSource="{Binding Tags}"
              SelectedItems="{Binding SelectedTags}">
        <CollectionView.ItemTemplate>
        <DataTemplate>
            <StackLayout Orientation="Horizontal">
                <Label Text="{Binding Name}"/>
            </StackLayout>
        </DataTemplate>
    </CollectionView.ItemTemplate>
    </CollectionView>
```

### Workaround

No workaround yet.

**Comment by samhouts** [comment]
@lilgrassin I think this is the same as #8997. Does that seem right?

**Comment by lilgrassin** [comment]
I don’t think so. #8997 appears to be an issue with activating the wrong (too many) items. My issue is that items that should be (items that are initially passed to SelectedItemsProperty before the page renders) are not initially activated until a change in state occurs. In my case, once the state is applied, the behaviour of the VSM is correct from then on.

**Comment by hartez** [comment]
This is also happening on UWP. Haven't checked Android yet.

**Comment by Jzrzmy** [comment]
I came across this issue in 4.5 on iOS, not on Android.

**Comment by crs2m5smith** [comment]
This bug does not happen on Android just iOS, has there been a work around for this yet? I see it is still open, will it be in a release soon?

**Comment by WingedDante** [comment]
I'm also experiencing this on iOS exclusively.  
Xamarin.Forms 4.5, collectionview preselected items,  iOS simulator.

**Comment by AbuMandour** [comment]
any update ?

**Comment by crs2m5smith** [comment]
None yet from Xamarin team. This one for us is not a huge show stopper or bug and we can work around it for now. Hopefully it is easy fix on their side and get it in next update or two.

**Comment by crs2m5smith** [comment]
Is there currently a work around for this issue?

**Comment by tristanmhmx** [comment]
This is still happening on XF 4.6.0.800. It happens on both Simulator and Device.

**Comment by sriganesh040194** [comment]
The same happens in XF 4.7 as well but just on iOS. Any workaround?

**Comment by varyamereon** [comment]
At first I thought there is no way to work around this as it relies completely on VisualStateManager. However I came up with this hacky solution..... I am using a MultiBinding that is bound to the object and via RelativeSource to the Collection within the ViewModel. Then a Converter that checks whether the item is in the collection. You also need to bind to a third dummy object that is updated every time the collection changes (I am using an int), this is necessary so that INotifyPropertyChange fires and updates the MultiBinding.

I can imagine this is not exactly efficient over large collections but mine is quite small and it works well until they fix this. I find bugs like this very annoying really as they are very high impact and hold back the progress of projects. Hoping for a fix!!

**Comment by AbuMandour** [comment]
> At first I thought there is no way to work around this as it relies completely on VisualStateManager. However I came up with this hacky solution..... I am using a MultiBinding that is bound to the object and via RelativeSource to the Collection within the ViewModel. Then a Converter that checks whether the item is in the collection. You also need to bind to a third dummy object that is updated every time the collection changes (I am using an int), this is necessary so that INotifyPropertyChange fires and updates the MultiBinding.
> 
> I can imagine this is not exactly efficient over large collections but mine is quite small and it works well until they fix this. I find bugs like this very annoying really as they are very high impact and hold back the progress of projects. Hoping for a fix!!

Could you share you fix code ?

**Comment by varyamereon** [comment]
Apologies for the formatting.

This is the XAML. I am using a Frame that changes BorderColor to show which items are selected.
```XAML
<Frame Padding="0"
              CornerRadius="0"
              HasShadow="False">

                        <Frame.BorderColor>

                            <MultiBinding Converter="{StaticResource SelectedItemConverter}"
                                                    Mode="OneWay">

                                <Binding Path="." /> // Bind to the individual item

                                <Binding Path="BindingContext.SelectedItems" // Bind to the collection in the ViewModel
                                                Source="{RelativeSource AncestorType={x:Type ContentPage}}" />

                                <Binding Path="BindingContext.DummyBindingUpdater" // Bind to a dummy property that fires INotifyPropertyChanged
                                                Source="{RelativeSource AncestorType={x:Type ContentPage}}" />

                            </MultiBinding>

                        </Frame.BorderColor>

</Frame>
```

This is the Converter
```C#
public class SelectedItemConverter : IMultiValueConverter
{
	public object Convert(object[] values, Type targetType, object parameter, CultureInfo culture)
	{
		if (values[0] is ItemType item && values[1] is ObservableRangeCollection<object> selectedItems)
		{
			if (selectedItems.Contains(item))
				return Color.Red;
		}

		return Color.Transparent;
	}

	public object[] ConvertBack(object value, Type[] targetTypes, object parameter, CultureInfo culture) => throw new NotImplementedException();
}
```

Finally in the ViewModel, you need an observable property to bind to, I am using an int called DummyBindingUpdater. Then after the collection is initialized you need this:
```C#
SelectedAerodromeTypes.CollectionChanged += delegate
{
	DummyBindingUpdater++;
};
```

Hope it helps, would be interested in other solutions.

**Comment by baskren** [comment]
FWIW, here is another work around that I found to be a bit easier to implement.  In the class you are using for your CollectionView's data template, add (or edit) the following code:

``` csharp
protected override void OnBindingContextChanged()
{
    UpdateSelected();
}

protected override void OnPropertyChanged([CallerMemberName] string propertyName = null)
{
    base.OnPropertyChanged(propertyName);
    if (propertyName == "Parent")
    {
        UpdateSelected();
    }
}

void UpdateSelected()
{
    if (BindingContext != null && Parent is CollectionView collectionView)
    {
        if (collectionView.SelectedItem.Equals(BindingContext) || collectionView.SelectedItems.Contains(BindingContext))
        {
            // the below works for iOS but ACTUALLY DOES THE OPPOSITE for Android.  Once again, Android.
            //VisualStateManager.GoToState(this, VisualStateManager.CommonStates.Selected);

            // to address the Android fail
            BackgroundColor = Color.LightGray;  // Color.LightGray is what I setup for the BackgroundColor in the Selected state
        }
    }
}
```

**Comment by baskren** [comment]
And, if the use of `BackgroundColor = Color.LightGray;` in the above snippet is not general enough, you can replace it with the following:

```csharp
 if (VisualStateManager.GetVisualStateGroups(this).FirstOrDefault(g=>g.Name == "CommonStates") is VisualStateGroup commonStates)
{
    if (commonStates.States.FirstOrDefault(s=>s.Name == VisualStateManager.CommonStates.Selected && s.TargetType == GetType()) is VisualState selectedState)
    {
        if (selectedState.Setters.FirstOrDefault(t => t.Property == BackgroundColorProperty) is Setter backgroundSetter)
            BackgroundColor = (Color)backgroundSetter.Value;
    }
}

```

**Comment by baskren** [comment]
Oops ... one more thing.  Both of the above were assuming that you have used VisualStateManager to setup a **CommonState.Selected** Setter for the BackgroundColor.  Sorry about that.

**Comment by MSicc** [comment]
There are quite a few issues open already regarding this problem.

The only way I got this working was to add an IsSelected property to my ItemViewModel and Two-Way bind it with a converter in my DataTemplate.

![image](https://user-images.githubusercontent.com/68176309/89095597-ead8f700-d3cf-11ea-855f-bf7c4d99e0a7.jpeg)

**Comment by maksym-husiev** [comment]
I have very similar issue. But in my case custom styles not applying to items after adding new portion of items to collection. And styles not applying only to first two visible (I have two items per row, sow it means that only items in first row has wrong behaviour) items of new portion.

**Comment by YZahringer** [comment]
My CollectionView behavior workaround:
````cs
public class SelectionStateCollectionViewBehavior : Behavior<CollectionView>
{
    private CollectionView AssociatedObject { get; set; }

    protected override void OnAttachedTo(CollectionView bindable)
    {
        AssociatedObject = bindable;
        bindable.ChildAdded += OnChildAdded;
        bindable.SelectionChanged += OnSelectionChanged;
        
        base.OnAttachedTo(bindable);
    }

    protected override void OnDetachingFrom(CollectionView bindable)
    {
        AssociatedObject = null;
        bindable.ChildAdded -= OnChildAdded;
        bindable.SelectionChanged -= OnSelectionChanged;

        base.OnDetachingFrom(bindable);
    }

    private void OnChildAdded(object sender, ElementEventArgs e)
    {
        if (AssociatedObject.SelectionMode == SelectionMode.Single)
        {
            var selectedItem = AssociatedObject.SelectedItem;
            if (selectedItem == null)
                return;

            if (e.Element?.BindingContext == selectedItem)
            {
                VisualStateManager.GoToState(e.Element as VisualElement, "Selected");
            }
        }
        else if (AssociatedObject.SelectionMode == SelectionMode.Multiple)
        {
            var selectedItems = AssociatedObject.SelectedItems;
            if (selectedItems == null || selectedItems.Count == 0)
                return;

            if (selectedItems.Contains(e.Element?.BindingContext))
            {
                VisualStateManager.GoToState(e.Element as VisualElement, "Selected");
            }
        }
    }

    private void OnSelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (e.PreviousSelection.Any() == false)
            return;

        foreach (var logicalChild in AssociatedObject.LogicalChildren)
        {
            if (e.PreviousSelection.Contains(logicalChild.BindingContext))
            {
                VisualStateManager.GoToState(logicalChild as VisualElement, "Normal");
            }
        }
    }
}
````

**Comment by adesypri** [comment]
In case everyone stumbles upon this, the issue is still reproducible in UWP (I did not check Android)

**Comment by LeoJHarris** [comment]
> My CollectionView behavior workaround:
> 
> ```cs
> public class SelectionStateCollectionViewBehavior : Behavior<CollectionView>
> {
>     private CollectionView AssociatedObject { get; set; }
> 
>     protected override void OnAttachedTo(CollectionView bindable)
>     {
>         AssociatedObject = bindable;
>         bindable.ChildAdded += OnChildAdded;
>         
>         base.OnAttachedTo(bindable);
>     }
> 
>     protected override void OnDetachingFrom(CollectionView bindable)
>     {
>         AssociatedObject = null;
>         bindable.ChildAdded -= OnChildAdded;
> 
>         base.OnDetachingFrom(bindable);
>     }
> 
>     private void OnChildAdded(object sender, ElementEventArgs e)
>     {
>         if (AssociatedObject.SelectionMode == SelectionMode.Single)
>         {
>             var selectedItem = AssociatedObject.SelectedItem;
>             if (selectedItem == null)
>                 return;
> 
>             if (e.Element?.BindingContext == selectedItem)
>             {
>                 VisualStateManager.GoToState(e.Element as VisualElement, "Selected");
>             }
>         }
>         else if (AssociatedObject.SelectionMode == SelectionMode.Multiple)
>         {
>             var selectedItems = AssociatedObject.SelectedItems;
>             if (selectedItems == null || selectedItems.Count == 0)
>                 return;
> 
>             if (selectedItems.Contains(e.Element?.BindingContext))
>             {
>                 VisualStateManager.GoToState(e.Element as VisualElement, "Selected");
>             }
>         }
>     }
> }
> ```

@YZahringer what happens if you select another item in the CollectionView after the page is loaded? Does it deselect the programmatically selected item? Unfortunately it doesn't for me.
