### ISSUE TITLE
[Bug] Can't use swipeview on UWP with a mouse

### ISSUE THREAD

**Issue by RyanGaudion** [xamarin/Xamarin.Forms#9515]
### Description
Swipeview works on touchscreen display with UWP put you can't open it with a mouse
### Steps to Reproduce

1. Create a swipview in Xamarin Forms
2. Run the project on UWP
3. Try to use a mouse to use the swipeview

### Expected Behavior
The swipeview opens to display whatever is underneath
### Actual Behavior
Nothing happens. The swipeview doesn't detect the mouse as a swipe

Is this how it's supposed to work? Can we add UWP mouse support?

**Comment by jsuarezruiz** [comment]
SwipeView in UWP makes use of the SwipeControl control available in WinUI https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swipecontrol
The behavior you describe is the expected and there are requests to make it compatible with mouse: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/1828

I will check SwipeControl to see if we can do something to make it compatible with mouse.

**Comment by jsuarezruiz** [comment]
I've changed this over to an enhancement. We're using the native WinUI SwipeControl and that control only works with touch gestures not the mouse so we would need to extend it.

**Comment by Rothanan** [comment]
Any news on this? I'm trying to manuelly open the swipe view in UWP, and it just doesn't work, no matter what I try.

**Comment by EmilAlipiev** [comment]
maybe we can use slidecontrol instead of swipe control like in the other issue mentioned. it is just deprecated but not removed.

**Comment by EmilAlipiev** [comment]
Is that actually working on a windows 10 touch based devices like surfaces? anyone tested it? Using simulator it doesn't seem to be working although i used the touch mode

**Comment by BurkusCat** [comment]
It works for me on a Windows 10 simulator using touch. Mouse support is a critical feature for it though.

**Comment by ivanrlg** [comment]
Any news on this?

**Comment by TamerIrdais** [comment]
Any update on this issue or time estimate when will it be supported?

**Comment by acaliaro** [comment]
end of 2022. nothing....

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
