### ISSUE TITLE
How to create a private one to one chat using xamarin forms

### ISSUE THREAD

**Issue by Mo-ha-mmed** [xamarin/Xamarin.Forms#9530]
How to create a private one to one chat using xamarin forms in 2020 ?

**Comment by hartez** [comment]
Are you asking whether Xamarin.Forms has a pre-built chat UI? It does not. You would need to build that out of other components. I would suggest using a CollectionView to display your messages and an Editor for entering them. You can find a very rudimentary example [here](https://github.com/hartez/XamEliza). Or take a look at [this article series](https://www.xamboy.com/2018/06/14/exploring-a-chat-ui-in-xamarin-forms-part-1/). 

If you are asking about "private" in the sense of "peer-to-peer" or "encrypted", that's not really within the scope of Forms. You could use Forms to build the client applications and UI, but the networking functionality is something you'd have to build yourself or look to a third party for.
