### ISSUE TITLE
PopModalAsync hides navigation bar on macOS

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9536]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/906251/popmodalasync-hides-navigation-bar-on-macos.html)._

---
When I push a page modally in my Forms app, I wrap the modal page in a NavigationPage so the modal page has a place for a title and toolbar buttons. This works quite well on iOS, UWP and Android. However on macOS, the navigation bar on the main page disappears after calling Navigation.PopModalAsync to remove the modal page.

To reproduce this behavior, create a two page app. On the main page add a button to initiate the modal push. Its action is: Navigation.PushModalAsync(new NavigationPage(new ModalPage())). This displays the modal page with its own navigation bar and toolbar buttons. However when issuing Navigation.PopModalAsync from the modal page, the navigation bar on the main page will disappear.

If the action instead is Navigation.PushModalAsync(new ModalPage(), true), the main page navigation bar no longer disappears after Navigation.PopModalAsync call.

Note also that the size of the window changes when the navigation bar is present or not. That is unexpected behavior.

See the attached project for an example demonstrating the inconsistency.

---
#### Visual Studio Feedback System on 2/4/2020, 07:05 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by samhouts** [comment]
Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by DancesWithDingo** [comment]
[MacOSFormsNavigation.zip](https://github.com/xamarin/Xamarin.Forms/files/4193055/MacOSFormsNavigation.zip)
Here's the example I submitted to the VS Feedback System.

**Comment by hot33331** [comment]
Working on this.

**Comment by hot33331** [comment]
The problem happens here in DisposeHelper.cs:
`if (view is VisualElement visualElement)
			{
				renderer = Platform.GetRenderer(visualElement);
				if (renderer != null)
				{
					if (renderer.ViewController != null)
					{
#if __MOBILE__
						var modalWrapper = renderer.ViewController.ParentViewController as ModalWrapper;
						if (modalWrapper != null)
							modalWrapper.Dispose();
#endif
					}

					renderer.NativeView.RemoveFromSuperview();
					renderer.Dispose();
				}
				view.ClearValue(Platform.RendererProperty);
			}`
In _MOBILE_ there seems to be something done differently for iOS that saves the day. If I remove the call to _DisposeModalAndChildRenderers_ from _ModalPageTracker_ alltogether, the navigation stays. But this is probably a bad idea.
