### ISSUE TITLE
[Bug] view coordinates are null on Android

### ISSUE THREAD

**Issue by Poli97** [xamarin/Xamarin.Forms#9541]
### Description
If I create a simple view, like a BoxView and I place it into an `AbsoluteLayout` with the proper `AbsoluteLayout.SetLayoutBounds` and `AbsoluteLayout.SetLayoutFlags`, then if I try to retrieve the box coordinates with `box.X; box.Y, box.Width, box.Height`, in iOS they are returned correctly, but in Android they result null, 0,0,-1,-1. 

### Steps to Reproduce

1.  Create a page with an AbsoluteLayout
2. Create a view (like a BoxView)
3. Place it in a certain position with `AbsoluteLayout.SetLayoutBounds` and `AbsoluteLayout.SetLayoutFlags`
4. Add it to the AbsoluteLayout, like `myabsolutelayout.Children.Add(myBox)`
5. Try to retreive the box coordinates, with like `Console.WriteLine($"Box coordinates: {box.X} {box.Y} {box.Width} {box.Height}");`
6. Test it with Android and iOS (I tried on Android physical device, Android emulator, iOS emulator)

### Expected Behavior
The message logged should contain the actual view coordinates, both in Android and in iOS.

### Actual Behavior
Only in iOS I can get the right coordinates, in Android they are returned as null, 0,0,-1,-1, even if I add a delay before getting them.

### Example Code
```C#

public partial class MainPage : ContentPage
{
    BoxView box;
    public MainPage()
    {
        InitializeComponent();

    }

    protected override void OnAppearing()
    {
        base.OnAppearing();

        box = new BoxView
        {
            BackgroundColor = Color.Red,
        };
        AbsoluteLayout.SetLayoutBounds(box, new Rectangle(0.6, 0.6, 0.25, 0.25));
        AbsoluteLayout.SetLayoutFlags(box, AbsoluteLayoutFlags.All);

        absolutelayout.Children.Add(box);
        //Task.Delay(3000);  //doesn't work even if I add a delay
        Console.WriteLine($"Box coordinates: {box.X} {box.Y} {box.Width} {box.Height}");
        //IN ANDROID (galaxy s9 emulator): "Box coordinates: 0 0 -1 -1"
        //IN IOS (iPhone 11 emulator): "Box coordinates: 186 403 104 224"

    }
}
```

**Comment by PureWeen** [comment]
@Poli97 
```C#
 //Task.Delay(3000);  //doesn't work even if I add a delay
```

isn't going to work because that's going to freeze your UI and nothing is going to happen. You would need to await it
```C#
await  Task.Delay(3000);  //doesn't work even if I add a delay
```

The layout timing on the various platforms is going to be a bit different.
If you want to know when the size on the box is set I would subscribe to the SizeChanged event on the box

```C#
        protected override void OnAppearing()
        {
            base.OnAppearing();

            var box = new BoxView
            {
                BackgroundColor = Color.Red,
            };
            box.SizeChanged += Box_SizeChanged;
            AbsoluteLayout.SetLayoutBounds(box, new Rectangle(0.6, 0.6, 0.25, 0.25));
            AbsoluteLayout.SetLayoutFlags(box, AbsoluteLayoutFlags.All);

            absolutelayout.Children.Add(box);
            //Task.Delay(3000);  //doesn't work even if I add a delay
            //IN ANDROID (galaxy s9 emulator): "Box coordinates: 0 0 -1 -1"
            //IN IOS (iPhone 11 emulator): "Box coordinates: 186 403 104 224"

        }

        private void Box_SizeChanged(object sender, EventArgs e)
        {
            var box = sender as BoxView;
            Console.WriteLine($"Box coordinates: {box.X} {box.Y} {box.Width} {box.Height}");
        }
```
