### ISSUE TITLE
[Bug] rounded buttons not round on iOS only Android

### ISSUE THREAD

**Issue by sturlath** [xamarin/Xamarin.Forms#9543]
### Description
My round buttons are not round on iOS but are on Android.

This code here produces different results on depending if I'm on iOS or Android.

```xml
<Button
            x:Name="Button1"
            d:Text="1"
            TextColor="White"
            WidthRequest="100"
            HeightRequest="100"
            CornerRadius="100"
            VerticalOptions="Center"
            HorizontalOptions="Center"
            BorderColor="Black"
            BorderWidth="5" />
```
### Steps to Reproduce

1. Put code above on a Xamarin.Form page
2. Build on Android and see it show round corners like image below
3. Build on iOS and see the strange form below.

To note then I'm using this [Pipeline Templates: Building and Deploying Uno Apps for iOS, Android and Windows](https://nicksnettravels.builttoroam.com/uno-pipeline-templates/) code [here](https://github.com/builttoroam/pipeline_templates/blob/master/azure/mobile/build-xamarin-ios.yml) to build this through to the AppCenter that then deploys it to my phone (I don't own a mac)

### Expected Behavior
Button should be round on iOS like it is on Andoroid

### Actual Behavior
Like the image below..

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 16.4.4
- Platform Target Frameworks: 
  - iOS:  SDK version default (?)
  - Android: 9.0

Tested on my IPhone 7 Plus model number NN4P2ZP/A 

### Screenshots
On Android its just fine
<img width="237" alt="AndroidCircleImageButton - Copy" src="https://user-images.githubusercontent.com/2386572/74354658-97d49e80-4db3-11ea-918f-aeb5b90ba24e.png">

But on iOS they are like this
![image](https://user-images.githubusercontent.com/2386572/74354574-7d022a00-4db3-11ea-8ce9-f341aa5ff873.png)

Am I doing something wrong? I can't find anything on this..

**Comment by StevenGranados** [comment]
The maths adds up wrong here. The corner radius should be 50 to get round buttons.

**Comment by sturlath** [comment]
Ok brilliant thanks @StevenGranados. It threw me off that it looked just fine on Android but not on iOS. Why is that?  But I'm going to close this as fixed.

**Comment by BillyMartin1964** [comment]
We're having the same problems. Is the CornerRadius a pixel or percentage?
