### ISSUE TITLE
[Bug] MacOS switching between details pages in MasterDetailPage causes Mac window to move up and down

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#9544]
### Description
On XF MacOS switching between details pages in MasterDetailPage causes Mac Windows to move up and down (Also the app header seems to contract and expand.).

### Steps to Reproduce

1. Create a blank XF apps with XF 4.4.0.991640 NuGet package
2. Add a template MasterDetailPage - Add a Coco Mac app
3. Deploy, switch between details pages. The app windows shift up and down. I am deploying on macOS Mojave v10.14.6

### Expected Behavior
The window to stay where it is, without moving.

### Actual Behavior
Mac app window shift up and down (by 1-2cm) every time you switch the detail page out. Also the header seems to contract and expand.

### Basic Information

- Version with issue: XF 4.4.0.991640 
- Last known good version: unknown
- IDE: VS for Mac 2019

### Reproduction Link
[AMDPMAC.zip](https://github.com/xamarin/Xamarin.Forms/files/4234427/AMDPMAC.zip)

**Comment by HelenMamalaki** [comment]
Hi, just realised it says in the documentation "A MasterDetailPage is designed to be a root page, and using it as a child page in other page types could result in unexpected and inconsistent behavior" which is prob the issue. However I am looking to split-screen in order to optimise extra space on Desktop and my App's top-level menu is a TabbedPage same as the layout in 
https://stackoverflow.com/questions/54430692/implement-a-master-detail-page-inside-a-tabbed-page-in-xamarin-forms-with-prism. I'm wondering if this is bad practise or just not supported?

**Comment by hot33331** [comment]
Might be related to https://github.com/xamarin/Xamarin.Forms/issues/9536

**Comment by HelenMamalaki** [comment]
@samhouts We parked Mac for some months and picked it up again using XF 5.0.0.1487-pre1 and this is not an issue anymore! (I haven't had a chance to confirm with the repo project but I assume it's not happening there either.)

**Comment by rachelkang** [comment]
@HelenMamalaki, awesome!! closing this issue now as it seems to be resolved :)
