### ISSUE TITLE
CollectionView strange behavior on iOS [iOS][Bug][CollectionView]

### ISSUE THREAD

**Issue by dimonovdd** [xamarin/Xamarin.Forms#9545]
### Description
The CollectionView has an unpleasant bug on iOS. On UWP and Android it hasn't been noticed. 

If the CollectionView has more than one columns and the bound collection contains one item, it is displayed in the center of the control, but not in the very left column as it happens on Android and UWP.
I have created a project to repeat this bug

### Reproduction Link
https://github.com/dimonovdd/CollectionViewBug.git

**Comment by hartez** [comment]
This was fixed in 4.6 by #10241
