### ISSUE TITLE
How to upload a file to the web backend with progress bar

### ISSUE THREAD

**Issue by Mo-ha-mmed** [xamarin/Xamarin.Forms#9547]
I want to upload a file to my ASP.NET core web api with a progress bar indicator.

How can you do that using Xamarin forms in 2020 ? Please help

**Comment by samhouts** [comment]
@Mo-ha-mmed This is a great question for [StackOverflow ](https://stackoverflow.com/) or the[ Xamarin Forums](https://forums.xamarin.com/). Thanks!
