### ISSUE TITLE
Type IndicatorView not found in xmlns http://xamarin.com/schemas/2014/forms

### ISSUE THREAD

**Issue by ncunning** [xamarin/Xamarin.Forms#9552]
### Description
Release Mode - Build fails with 

_"Type IndicatorView not found in xmlns http://xamarin.com/schemas/2014/forms"_

### Steps to Reproduce

1. Build Xamarin Forms Template 
2. Add Indicator View with experimental flag for Android
3. Build in Release mode

### Expected Behavior
Successful Build

### Actual Behavior
Build Failed with error
### Basic Information

- Version with issue: Xamarin Forms 4.4
- Last known good version:
- IDE: N/A
- Platform Target Frameworks: Android
 
  - Android: The version of the Android SDK you are compiling against, 7.1
 
- Nuget Packages:
- Affected Devices:

### Workaround

 Builds in release with linking disabled

**Comment by PureWeen** [comment]
@ncunning can you try with the latest pre4? or the latest nightly?
https://github.com/xamarin/Xamarin.Forms/wiki/Nightly-Builds

If that still doesn't work can you attach a repro? I tested an Indicators view in release mode and it's working fine for me

**Comment by samhouts** [comment]
@ncunning  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
