### ISSUE TITLE
[Bug][iOS] Applying an Effect to Frame adds a shadow 

### ISSUE THREAD

**Issue by MarcAlx** [xamarin/Xamarin.Forms#9555]
### Description

When applying an Effect to a `<Frame>` a shadow is applied on iOS.

### Steps to Reproduce

1. Add an effect to a Frame

```
<Frame.Effects>
     <controls:ElevationEffect/>
</Frame.Effects>
```

2. Launch on iOS
3. See the shadow applied (not expected)

### Expected Behavior

The effect is applied and no extra shadow is added

### Actual Behavior

The effect is applied and a shadow is added like if HasShadow = True

### Basic Information

- Version with issue:
- Last known good version: (Forms) 4.4.0.991640
- IDE: Visual Studio Mac 8.4.5 (19)
- Platform Target Frameworks: 4.5.0.142-pre1 +
  - iOS:  4.5.0.142-pre1 
  - Android: Doesn't not apply
  - UWP:  Not tested
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPhone 7 (iOS 13) (real device) also apply on simulator

### Screenshots

**Ok (4.4.0.991640)**

My custom effect is applied (a light shadow)

![OK](https://user-images.githubusercontent.com/6607139/74428674-bf7e4200-4e59-11ea-87f0-b7c87f36a9e5.png)

**Ko : (4.5.0.142-pre1 +)**

My custom effect is applied and a shadow is added

![ko](https://user-images.githubusercontent.com/6607139/74428669-bd1be800-4e59-11ea-98bb-9a5fa30fb94c.png)

### Workaround

Apply your effect as expected then force HasShadow value per platform

```
<Frame.HasShadow>
      <OnPlatform x:TypeArguments="x:Boolean">
             <On Platform="Android" Value="True" />
             <On Platform="iOS" Value="False" />
      </OnPlatform>
</Frame.HasShadow>
```

**Comment by MarcAlx** [comment]
After some toughts, the problem is that there's a different behavior between iOS and Android, which wasn't the case in 4.4

To me the question is: should adding an effect to a Frame should override the shadow ? 

PS Setting HasShadow to False on Android cause my effect (which creates a shadow) to not display.

**Comment by samhouts** [comment]
related to #9519

**Comment by lapoPaolacci** [comment]
Same bug if you use a custom renderer instead Effect

`
if (Element.HasShadow)
            {
                Layer.MasksToBounds = false;
                Layer.ShadowColor = UIColor.Black.CGColor;
                Layer.ShadowOffset = new CGSize(0, 5);
                Layer.ShadowRadius = 5;
                Layer.ShadowOpacity = 0.24f;
            }
`

**Comment by woodj5134** [comment]
Managed to workaround this by downgrading Xamarin.iOS to version 13.14.1.39

**Comment by lypefm** [comment]
I have the same problem, I use a customrenderer giving a setup and it doesn't work, but in another project with the previous xamarin forms it works

public override void Draw (CGRect rect)
         {
             base.Draw (rect);

             // Update shadow to match better material design standards of elevation
             Layer.ShadowRadius = 2f;
             Layer.ShadowColor = UIColor.Gray.CGColor;
             Layer.ShadowOffset = new CGSize (0, 1);
             Layer.ShadowOpacity = 0.60f;
             Layer.ShadowPath = UIBezierPath.FromRect (Layer.Bounds) .CGPath;
             Layer.MasksToBounds = false;
        }

**Comment by liveinvarun** [comment]
@samhouts Any update on this bug

**Comment by samhouts** [comment]
@liveinvarun Looks like we've merged the fix! This should be in a service release within the next week or so. Thanks for your patience!
