### ISSUE TITLE
[Bug][Android] The icon of the Button is not centered

### ISSUE THREAD

**Issue by AhmetCavus** [xamarin/Xamarin.Forms#9561]
### Description

In Android:

If an icon is set in the Xamarin Forms Button via ImageSource, it will be centered correctly without text. As soon as the text is set , the icon is positioned on the far left.
It does not matter if I use a vector drawable or a PNG. The behaviour occurs with both variants.

Here is the code in xaml:

`
        <Button
            HeightRequest="41"
            HorizontalOptions="FillAndExpand"
            ImageSource="cart_icon"
           Text="Add" />
`

This problem was already reported in older versions:
https://github.com/xamarin/Xamarin.Forms/issues/5861
#9227

### Steps to Reproduce

1. Place a Button control into a xaml page 
2. Set the ImageSource with a path of an icon
3. Finally, add a text in the button

### Expected Behavior
The icon is correctly centered before the text

### Actual Behavior
The icon is positioned on the far left

### Basic Information

- Version with issue: 4.4.0.991477
- IDE: Visual Studio Mac 8.4.3
- Platform Target Frameworks: 
  - Android: 10.0

### Screenshots

A screenshot from the issue:
![image](https://user-images.githubusercontent.com/34402666/74443906-4a6c3600-4e74-11ea-8766-d5d7f3e7459d.png)

**Comment by MhAllan** [comment]
#9227

**Comment by PureWeen** [comment]
I'm going to close this one in favor of https://github.com/xamarin/Xamarin.Forms/issues/9227

Currently we can't change the default way it displays on android but it should be fixable if the user configures.

if you use the Material Buttons with the Material Visual Renderers that centers correctly
