### ISSUE TITLE
[Bug] System.Security.Cryptography.RSA.ImportRSAPrivateKey not supported

### ISSUE THREAD

**Issue by marza91** [xamarin/Xamarin.Forms#9564]
### Description
Not sure if this should be considered a feature request or if it's supposed to work, so feel free to change it. I'm trying to load an RSA private key using the System.Security.Cryptography.RSA class and the "ImportRSAPrivateKey" method. I need to then load this into a X509Certificate2 certificate for a MQTT connection. My current workaround is to generate a pfx file on a PC, but I would like to be able to avoid that. Calling the mentioned method throws a System.PlatformNotSupportedException, "Operation is not supported on this platform."
This happens on both iOS and Android, not sure if this should be reported here or in those repositories.

### Steps to Reproduce

1. 
Run the following code:
```
MemoryStream memoryStream = new MemoryStream();

// Load rsa file into stream

var rsa = System.Security.Cryptography.RSA.Create();
rsa.ImportRSAPrivateKey(memoryStream.ToArray(), out _);
```

### Expected Behavior
RSA key is imported successfully

### Actual Behavior
System.PlatformNotSupportedException, "Operation is not supported on this platform."

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version:
- IDE: Microsoft Visual Studio Enterprise 2019 Version 16.4.4
- Platform Target Frameworks: 
  - iOS: 13.10.0.17 (5f802ef) 
  - Android: 10.1.3.7 (d16-4/d66aed0)  
  - UWP: Not tested  
- Android Support Library Version: 28.0.0.3 
- Nuget Packages:
- Affected Devices: iOS and Android

### Workaround

Converting to a pfx file on PC using openssl and then importing that using:
`var cert = new X509Certificate2(filebytes, string.Empty, X509KeyStorageFlags.Exportable);`

See this article on how to do the conversion: https://stackoverflow.com/questions/6307886/how-to-create-pfx-file-from-certificate-and-private-key

**Comment by chamons** [comment]
This issue was moved to mono/mono#18842
