### ISSUE TITLE
CollectionView Selected Item Highlight Colour

### ISSUE THREAD

**Issue by ColdstarJoey** [xamarin/Xamarin.Forms#9565]
Hi all,

how do I change the highlight color of the CollectionView selected item. everytime i press it, it is blue and i want it transparent

**Comment by Huaba93** [comment]
Do you need selection? How about  `SelectionMode="None"`

**Comment by hartez** [comment]
@ColdstarJoey Which platform(s) are you targeting?

**Comment by hartez** [comment]
@ColdstarJoey There are a few different ways you can do this; the easiest is to add a `Selected` VisualState to your ItemTemplate and set the background color there. 

I created [a repo which demonstrates this](https://github.com/hartez/SelectedItemStyling) (and a couple of other ways to set it).

**Comment by hartez** [comment]
And for the folks who don't feel like wading through my repo, here's the dead-simplest version of setting your ItemTemplate's background color to yellow when selected:

```
<CollectionView ItemsSource="{Binding Items}" SelectionMode="Single">
	<CollectionView.ItemTemplate>
		<DataTemplate>
			<Grid>
				<VisualStateManager.VisualStateGroups>
					<VisualStateGroup Name="CommonStates">
						<VisualState Name="Normal" />
						<VisualState Name="Selected">
							<VisualState.Setters>
								<Setter Property="BackgroundColor" Value="Yellow" />
							</VisualState.Setters>
						</VisualState>
					</VisualStateGroup>
				</VisualStateManager.VisualStateGroups>

				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
			</Grid>
		</DataTemplate>
	</CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by ColdstarJoey** [comment]
> 
> 
> Do you need selection? How about `SelectionMode="None"`

Yes due to you can't select anything on the collectionView without it

**Comment by ColdstarJoey** [comment]
> 
> 
> And for the folks who don't feel like wading through my repo, here's the dead-simplest version of setting your ItemTemplate's background color to yellow when selected:
> 
> ```
> <CollectionView ItemsSource="{Binding Items}" SelectionMode="Single">
> 	<CollectionView.ItemTemplate>
> 		<DataTemplate>
> 			<Grid>
> 				<VisualStateManager.VisualStateGroups>
> 					<VisualStateGroup Name="CommonStates">
> 						<VisualState Name="Normal" />
> 						<VisualState Name="Selected">
> 							<VisualState.Setters>
> 								<Setter Property="BackgroundColor" Value="Yellow" />
> 							</VisualState.Setters>
> 						</VisualState>
> 					</VisualStateGroup>
> 				</VisualStateManager.VisualStateGroups>
> 
> 				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
> 			</Grid>
> 		</DataTemplate>
> 	</CollectionView.ItemTemplate>
> </CollectionView>
> ```

I am working on Android Only. Is this for the selection of the CollectionView? it looks like it will change the background color of the grid. I need it to do the SelectedItem highlight color of the CollectionView

**Comment by AmrAlSayed0** [comment]
> And for the folks who don't feel like wading through my repo, here's the dead-simplest version of setting your ItemTemplate's background color to yellow when selected:
> 
> ```
> <CollectionView ItemsSource="{Binding Items}" SelectionMode="Single">
> 	<CollectionView.ItemTemplate>
> 		<DataTemplate>
> 			<Grid>
> 				<VisualStateManager.VisualStateGroups>
> 					<VisualStateGroup Name="CommonStates">
> 						<VisualState Name="Normal" />
> 						<VisualState Name="Selected">
> 							<VisualState.Setters>
> 								<Setter Property="BackgroundColor" Value="Yellow" />
> 							</VisualState.Setters>
> 						</VisualState>
> 					</VisualStateGroup>
> 				</VisualStateManager.VisualStateGroups>
> 
> 				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
> 			</Grid>
> 		</DataTemplate>
> 	</CollectionView.ItemTemplate>
> </CollectionView>
> ```

This works only when you want to actually set the background color for selected items, but if you want no background color at all (for example, taping an item would navigate to another page so no need to set color at all), setting the background color to transparent (ie. trying to clear it) would still show the orange selection color on Android. The way my view model is set up is listening to the SelectedItem property change and navigating when that happens.

There are 2 ways to solve that problem
1. Set the selected background color to the same color of the page's background.
2. Set SelectionMode to None and add Tap Recognizers in the item template.

I know it is easily fixable, but it would be so much better if we can customize this.

**Comment by hartez** [comment]
@AmrAlSayed0 You make a good point; I've created an issue to take a look at this problem: #9590.

**Comment by EmilAlipiev** [comment]
> And for the folks who don't feel like wading through my repo, here's the dead-simplest version of setting your ItemTemplate's background color to yellow when selected:
> 
> ```
> <CollectionView ItemsSource="{Binding Items}" SelectionMode="Single">
> 	<CollectionView.ItemTemplate>
> 		<DataTemplate>
> 			<Grid>
> 				<VisualStateManager.VisualStateGroups>
> 					<VisualStateGroup Name="CommonStates">
> 						<VisualState Name="Normal" />
> 						<VisualState Name="Selected">
> 							<VisualState.Setters>
> 								<Setter Property="BackgroundColor" Value="Yellow" />
> 							</VisualState.Setters>
> 						</VisualState>
> 					</VisualStateGroup>
> 				</VisualStateManager.VisualStateGroups>
> 
> 				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
> 			</Grid>
> 		</DataTemplate>
> 	</CollectionView.ItemTemplate>
> </CollectionView>
> ```

This doesnt work. if you select an item and select another item, both items are having Yellow backgroundcolor. It is not switching one from the other.

**Comment by denysvega** [comment]
@EmilAlipiev it seems you need to set `SelectionMode="Single"`.

**Comment by Seuleuzeuh** [comment]
@denysvega the SelectionMode="Single" is already set. 
@EmilAlipiev you have to set the BackgroundColor to the original in the VisualState Normal, for example 

```
<CollectionView ItemsSource="{Binding Items}" SelectionMode="Single">
	<CollectionView.ItemTemplate>
		<DataTemplate>
			<Grid>
				<VisualStateManager.VisualStateGroups>
					<VisualStateGroup Name="CommonStates">
						<VisualState Name="Normal" >
							<VisualState.Setters>
								<Setter Property="BackgroundColor" Value="White" />
							</VisualState.Setters>
						</VisualState>
						<VisualState Name="Selected">
							<VisualState.Setters>
								<Setter Property="BackgroundColor" Value="Yellow" />
							</VisualState.Setters>
						</VisualState>
					</VisualStateGroup>
				</VisualStateManager.VisualStateGroups>

				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
			</Grid>
		</DataTemplate>
	</CollectionView.ItemTemplate>
</CollectionView>
```

**Comment by SwingsetTheory** [comment]
For me setting the values to "transparent" actually creates a gray background when the item is selected.

**Comment by acaliaro** [comment]
> <CollectionView.ItemTemplate>
> 		<DataTemplate>
> 			<Grid>
> 				<VisualStateManager.VisualStateGroups>
> 					<VisualStateGroup Name="CommonStates">
> 						<VisualState Name="Normal" />
> 						<VisualState Name="Selected">
> 							<VisualState.Setters>
> 								<Setter Property="BackgroundColor" Value="Yellow" />
> 							</VisualState.Setters>
> 						</VisualState>
> 					</VisualStateGroup>
> 				</VisualStateManager.VisualStateGroups>
> 
> 				<Label x:Name="Title" Text="{Binding Title}" FontSize="Large"></Label>
> 			</Grid>
> 		</DataTemplate>
> 	</CollectionView.ItemTemplate>

What should I have to do if I want to change Grid BackgroundColor and also Label TextColor when the item is selected?

**Comment by hartez** [comment]
@acaliaro You can use the TargetName property to set values for other controls inside the grid: https://devblogs.microsoft.com/xamarin/visual-state-manager/#using-targetname-with-visual-state-manager

**Comment by acaliaro** [comment]
> @acaliaro You can use the TargetName property to set values for other controls inside the grid: https://devblogs.microsoft.com/xamarin/visual-state-manager/#using-targetname-with-visual-state-manager

Yes @hartez , that's the way. Thanks

**Comment by stavroaudi** [comment]
Any fix for this? I prefer not to add a tap gesture recognizer and want a transparent background on view selected. Plus I have a gradient background so unfortunately cannot set the color to the background color.

**Comment by Stratosf** [comment]
> Any fix for this? I prefer not to add a tap gesture recognizer and want a transparent background on view selected. Plus I have a gradient background so unfortunately cannot set the color to the background color.

I have the exact same issue and still searching for a work around!

**Comment by softlion** [comment]
see https://www.youtube.com/watch?v=Mfj4j-iThUs

**Comment by BillyMartin1964** [comment]
It seems that I can either have my selections highlighted or be able to tap them twice. Do you have a workaround?

**Comment by softlion** [comment]
you are confusing highlight with selection. You are speaking about selection color. This is not the transient highlight color or ripple animation that is displays only for a few milliseconds when tapping an item.

**Comment by BillyMartin1964** [comment]
It must be a few milliseconds, because I can't see the tap at all if I don't do the selected. Can I change the time of the shimmer? Or Maybe it isn't turned on? Really need your help. Users can't even know if they tapped anything for sure. Thanks so much.
