### ISSUE TITLE
[Bug] [UWP] Selected VisualState not set on CollectionView templated items

### ISSUE THREAD

**Issue by hartez** [xamarin/Xamarin.Forms#9578]
### Description

The Selected VisualState is not set on items when they are selected.

Only an issue on UWP; Android and iOS are working.

**Comment by hartez** [comment]
See also: #9279 and #9511

**Comment by feokuma** [comment]
I suspect that this issue is applies to items on ColletionView Header too. I found this issue search something about Entry on Header of ColletionView.

**Comment by samhouts** [comment]
closed by #10770
