### ISSUE TITLE
[Bug] iOS CarouselView size not changed if device orientation changed

### ISSUE THREAD

**Issue by KoenMat** [xamarin/Xamarin.Forms#9583]
### Description
See attached very basic sample. It has a carousel (3 items) that fills the page.
In iOS, if you rotate the device, the size of the carousel is not upated.
In Android this works as expected.
This really looks like #8902 that was solved by #9204 and released in 4.5.0-pre2.
Unfortunately it is NOT solved (at least not in this case).

### Steps to Reproduce

1. Run the sample
2. Rotate the device
3. Notice the problem

### Expected Behavior
The size of the carousel should adapt to fill the page after orientation change.
### Actual Behavior
Size is unchanged.
### Basic Information

- Version with issue: 4.5.0-pre4
- Last known good version: none
- IDE: Visual Studio 16.4.1
- Platform Target Frameworks: 
  - iOS:  12.3 / 13.3
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Simulator, iPhone 12.3, iPad 13.3

### Reproduction Link

[CarouselOrientationIssue.zip](https://github.com/xamarin/Xamarin.Forms/files/4203730/CarouselOrientationIssue.zip)

**Comment by Maxima078** [comment]
Same here #8902 is not solved.
