### ISSUE TITLE
[Bug] CollectionView scrolled event index arguments incorrect. 

### ISSUE THREAD

**Issue by Jamesmallon1** [xamarin/Xamarin.Forms#9586]
### Description
When the scrolled event is invoked for the CollectionView on Android the First, and center index's are the same when they should not be. 

### Steps to Reproduce

1. Add CollectionView to your view.
2. Attach a basic itemsource + template. (this can be anything)
3. Attach an event handler to the Scrolled event.
4. observer the arguments that are passed to your scrolled event handler

### Expected Behavior
The first and center item index's must actually represent the real values.

### Actual Behavior
All values are just the First.

### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991537
- Last known good version: N/A
- IDE: Rider 2019.3.1
- Platform Target Frameworks: 
  - Android: 9.0 (API 28)
- Android Support Library Version: 28.0.0.3
- Nuget Packages: Xam.Forms, Android specific nuget packages
- Affected Devices: All (Testing on Pixel 3a)

### Screenshots
This is not visual, however here is an image of the values of the event arguments.

<img width="377" alt="Screenshot 2020-02-14 at 11 30 03" src="https://user-images.githubusercontent.com/11695266/74527422-8dceaf00-4f1d-11ea-93a6-594bf12104f2.png">

### Workaround
Floor(LastIndex - Firstindex) / 2) + firstIndex

**Comment by samhouts** [comment]
@Jamesmallon1  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by samhouts** [comment]
@Jamesmallon1  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
