### ISSUE TITLE
[Enhancement] Make IndicatorView pass the current item for it's DataTemplate

### ISSUE THREAD

**Issue by patrickhacens** [xamarin/Xamarin.Forms#9597]
## Summary
Right now on 4.4.0.991640 when an IndicatorView's indicator template is invoked `null` is setted to it's `DataTemplate` `BindingContext` making it impossible to do a more customized configuration, I would like to either include the ItemSource used to create that indicator or another data that would be usefull to customize and Indicator

## API Changes
No API changes on the `IndicatorView`

### Possible solution 1
IndicatorView's DataTemplate receive the ItemSource used to generate it in it's BindingContext and can be used as such:
Consider that I will be using an string[] as ItemSources
```xaml
<IndicatorView
	Margin="20"
	ItemsSource="{Binding DataSource}" <!-- string[] { 1, 2, 3, 4} -->
	Position="{Binding Position, Source={Reference car}}"> <!-- binding to my CarouselView -->
	<IndicatorView.IndicatorTemplate>
		<DataTemplate>
			<StackLayout x:Name="container">
				<Frame
					Padding="0"
					WidthRequest="10"
					HeightRequest="10"
					CornerRadius="5">
					<Label
						Text="{Binding .}" />
				</Frame>
			</StackLayout>
		</DataTemplate>
	</IndicatorView.IndicatorTemplate>
</IndicatorView>
``` 
this would enable us to make a more complex indicator's as such
![image](https://user-images.githubusercontent.com/5077339/74566893-47944280-4f53-11ea-93d0-fc6421dd61ba.png)

### Possible solution 2
Better still would be if instead of automatically settings `BackgroundColors` of our top element as it's currently is would be to pass an intermediate class to represent this item's viewmodel as such:
```csharp
public class IndicatorViewModel
{
    public int Position { get; set; }
    public bool IsSelected { get; set; }
    public Color SelectedColor { get; set; } //maybe Selected Color and Color would be not necessary
    public Color Color { get; set; }
    public object Item { get; set; } //Current ItemSource
}
```
That would also enable us to do this more complex Indicator's and maybe more than before, not sure about speed and memory

**Comment by tabrms** [comment]
Guys, option to have a binding context available in DataTemplate in a form of a view or its viewmodel would be so cool. Please plan this to a sprint. Thank you.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
