### ISSUE TITLE
[Bug] DisplayPromptAsync not working UWP

### ISSUE THREAD

**Issue by mnxamdev** [xamarin/Xamarin.Forms#9599]
Description
DisplayPromptAsync is not working. Nothing happens. I was testing on UWP. I found this issue while working on my own app and looking for a solution I stumbled on #9168 . I've adjusted the sample app to not use Task.Run() and problem still persists. 

Steps to Reproduce
Run this project
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4206946/App1.zip)

Click the button.

Nothing happens

Expected Behavior
Prompt dialog should be displayed.

Actual Behavior
Nothing happens

Basic Information
Version with issue: 4.4.0.991477
IDE: 16.4.4

Platform Target Frameworks:
UWP: Windows 10

**Comment by bmacombe** [comment]
Something broke this since #8720 was merged, I'll take a look

**Comment by bmacombe** [comment]
it was merged into master...it probably didn't make it into 4.4

**Comment by bmacombe** [comment]
or 4.5 it looks like

**Comment by bmacombe** [comment]
yep, these changes are in Master...so looking like 4.6 at this point? @samhouts

**Comment by samhouts** [comment]
Yes, that's right. 4.6. :)

**Comment by AndyPresto** [comment]
We you sure a fix for this is in 4.6?

I can't see any mention in the [release notes ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.6/4.6.0-pre4)

**Comment by SymboLinker** [comment]
> 
> 
> We you sure a fix for this is in 4.6?
> 
> I can't see any mention in the [release notes ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.6/4.6.0-pre4)

I updated Xamarin.Forms from version 4.5.0.65 to 4.6.0.726 and indeed, UWP's DisplayPromptAsync really displays again :)

**Comment by webapps-rvcits** [comment]
@AndyPresto I beg to disagreed on your statement. The bug on UWP's DisplayPromptAsync is still existing from Xamarin.Forms 4.5.0.356 to 4.6.0.800

**Comment by mnxamdev** [comment]
We just tested this on Xamarin.Forms 4.6.800 and it seems to be working just fine:
![image](https://user-images.githubusercontent.com/46384868/83045816-bdf11800-a00b-11ea-87ea-63dc88658386.png)

**Comment by zgeorgiev** [comment]
I just updated package to Xamarin.Forms v.4.6.0.847 and DisplayPromptAsync still not working. I get the following exception:

The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key SystemControlPageBackgroundAltHighBrush [Line: 0 Position: 0]

**Comment by moqueur** [comment]
I have the same error on 4.7.0.1080

**Comment by bmacombe** [comment]
@zgeorgiev  @moqueur  I just tested the 6713 issue page (test page for display prompt) on Main, 4.8, 4.7 and 4.6 and can't replicate this issue.  I would create a new issue and attach a repro app.

**Comment by shpand** [comment]
Had the same issue. Just updating to Xamarin.Forms  >= v.4.6 did not solve the issue. To fix the error I had to also update Target Platform version from 10.0.16299 to 10.0.17763 (right click on UWP project -> Application -> Target Platform). Updating both dependencies solved the problem
