### ISSUE TITLE
Style Is Applied in Visual Studio Designer But Not In Emulator/Physical Mobile

### ISSUE THREAD

**Issue by hassanelsherbiny** [xamarin/Xamarin.Forms#9601]
I Have a style in App.xaml like following
`<ResourceDictionary>
            <OnPlatform x:TypeArguments="Thickness" x:Key="IOSPadding" iOS="0, 30, 0, 0"></OnPlatform>
            <Style TargetType="{x:Type ContentPage}">
                <Setter Property="Padding" Value="{StaticResource IOSPadding}"/>
                <Setter Property="BackgroundColor" Value="Red"/>
            </Style>
        </ResourceDictionary>`

in Visual Studio Designer Previewer It Works
 
![image](https://user-images.githubusercontent.com/20015837/74580913-b4d6c080-4fb1-11ea-979b-004a6732e2d7.png)

but In Emulator The Style Is Not Applied 
![image](https://user-images.githubusercontent.com/20015837/74580922-d768d980-4fb1-11ea-8263-b10848c56a8e.png)

The Same Issue Exist For Both Android And IOS

**Comment by samhouts** [comment]
@hassanelsherbiny  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by hassanelsherbiny** [comment]
here is test project and it behaves the same as described above
[TestStyle.zip](https://github.com/xamarin/Xamarin.Forms/files/4215675/TestStyle.zip)

**Comment by PureWeen** [comment]
@hassanelsherbiny in order for this to work in your app you have to set applies to derived types

```XAML
 <Style  TargetType="{x:Type ContentPage}" ApplyToDerivedTypes="True">
                <Setter Property="BackgroundColor" Value="Red"/>
            </Style>
```
