### ISSUE TITLE
MediaElement's CurrentStateChanged Missing

### ISSUE THREAD

**Issue by jrahma** [xamarin/Xamarin.Forms#9602]
Hi,

I am trying to use the MediaElement but I cannot get the CurrentStateChanged property in XAML not codebehind

Kindly advise,,,

Thanks,
[Jassim](https://www.emiratesangels.org)

**Comment by samhouts** [comment]
@jrahma Do you mean it doesn't appear in intellisense? Thanks!

**Comment by samhouts** [comment]
@jrahma  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by jrahma** [comment]
Sorry @samhouts  for late reply

Yes, I mean it doesn't show in the intellisense

and also getting:

**The property 'CurrentStateChanged' was not found in type 'MediaElement'.**

when I try to add it manually

**Comment by PureWeen** [comment]
@jrahma why are you thinking there should be a CurrentStateChanged event? 

CurrentState is a property so if you want to monitor if it changes than subscribe to PropertyChanged and look for something named *CurrentState"
