### ISSUE TITLE
[Bug] iOS CarouselView contents does not resize

### ISSUE THREAD

**Issue by alaneich** [xamarin/Xamarin.Forms#9609]
### Description
When the height of a horizontal CarouselView changes, the contents of the CarouselView does not change its height.  This results in the contents scrolling vertical besides the horizontal scrolling of the CarouselView.  Occurs with iOS.  Does not occur on Android.

### Steps to Reproduce

1. Using the Control Gallery app.  Go to the CarouselView Gallery -> CarouselView (Code, Horizontal)
2. Start swiping horizontal which causes the top controls to take more space making the CarouselView shorter.
3. One can now scroll in both the horizontal and vertical directions.

### Expected Behavior
The contents of the CarouselView should resize to reflect the new size of the CarouselView.

### Actual Behavior
On iOS, the contents does not resize but scrolls to show the hidden content.

### Basic Information

- Version with issue: 4.4.0.991640
- Last known good version:
- IDE: Visual Studio 15.9
- Platform Target Frameworks: 
  - iOS:  12.4

### Workaround

The override of ShouldInvalidateLayoutForBoundsChange() in Xamarin.Forms.Platform.iOS/CollectionView/CarouselViewLayout.cs appears to be the cause of the problem.  Creating a custom renderer with a custom CarouselViewLayout without this override fixes the problem.

**Comment by rmarinho** [comment]
do you have your sample for this?  can you try branch fix-9583 and see if you still see the issue?

**Comment by alaneich** [comment]
To duplicate this issue I was using the Control Gallery as described in this issue.  I was able to build it in Forms 4.4.0, but I’m having issues building 4.5.0.  I’m thinking Forms 4.5.0 needs Visual Studio 2019 to build and I’m still using Visual Studio 2017.
