### ISSUE TITLE
[Bug] [Android] RotationX/RotationY View size issue on high resolutions

### ISSUE THREAD

**Issue by AndreiMisiukevich** [xamarin/Xamarin.Forms#9620]
### Description
Hi folks, I posted an issue on twitter https://twitter.com/Andrik_Just4Fun/status/1225543371957121024
It's related to CubeView control (one of my open-source plugin)
There is a wrong RotationX/RotationY behavior on high resolutions on the Android platform.
- Video of the behavior at 3040x1440: [you can observe the bug here](https://i.imgur.com/ayCPMFd.mp4)
- Video of the behavior at 1520x720: [this is perfect](https://i.imgur.com/DsGHAQj.mp4)

### Steps to Reproduce
1. Download attached sample
2. Run iOS (see it works as expected)
3. Run Android (see the issue exists)

### Expected Behavior
Proper sizing of view when RotationX/RotationY used.

### Actual Behavior
Wrong sizing of view

### Basic Information
- Version with issue: Latest
- Last known good version: None
- IDE: Visual Studio for Mac
- Platform Target Frameworks: **Android**
- Affected Devices: Android devices and emulators with a high pixel density

### Screenshots
See iOS works as expected, but Android doesn't
![Feb-18-2020 13-52-29](https://user-images.githubusercontent.com/10124814/74729765-0b642900-5256-11ea-8f6e-b6dd77ea90dd.gif)

### Reproduction Link
[RotationXYBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4218774/RotationXYBug.zip)

### Workaround
None

### Dependent issue
- CubeView swiping bug on larger resolutions: https://github.com/AndreiMisiukevich/CardView/issues/326

**Comment by AndreiMisiukevich** [comment]
@samhouts do you need more info from my side?

**Comment by samhouts** [comment]
@AndreiMisiukevich  Nope, this is clear! Thank you!

**Comment by AndreiMisiukevich** [comment]
Hm, retested this issue. Now it even worsts for some reason.

1) Download the test project attached to the issue
2) Upgrade XF version to 5.0
3) Go through the test steps

**Comment by AndreiMisiukevich** [comment]
@samhouts 

Perhaps that's not a bug. Users just should set proper AnchorX and AnchorY

https://stackoverflow.com/a/35126831
