### ISSUE TITLE
[Bug] Camera preview on iOS is not working when is initially not visible

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9623]
### Description
I have did a little modification in sample code from here:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/customrenderers-view/

and I have added a button to change the visibility of camera preview control. On Android everything works fine:
![camera_view_android](https://user-images.githubusercontent.com/17653648/74751529-aae0e600-526d-11ea-8c09-d425a077882b.gif)

But on iOS the camera preview is not displayed. You can check this by lanching this project on a real iPhone device.
[Xamarin_Forms___View_Custom_Renderer.zip](https://github.com/xamarin/Xamarin.Forms/files/4220180/Xamarin_Forms___View_Custom_Renderer.zip)

This is because I have set the `CameraPreview` control to have `IsVisible` property to be initially false
```
<controls:CameraPreview x:Name="cameraPreview" IsVisible="False" Camera="Rear" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" />
```

If we remove `IsVisible="False"` it works fine.

### Steps to Reproduce

1. Launch the project which I have pasted above on a real iPhone device.
2. Click the "show" button to show the camera preview.
3. As you can see camera preview is not displayed.
4. Run the same project on Android.
5. Click the "show" button.
6. As you can see camera view is displayed fine 

### Expected Behavior
Camera preview should be displayed fine on both iOS and Android.

### Actual Behavior
Camera preview is displayed only on Android.

### Basic Information

- Version with issue: 4.4.0.991265
- Last known good version: none
- IDE: Visual Studio 2019 16.4.5
- Platform Target Frameworks: 
  - iOS:  11.0
  - Android: 9.0

**Comment by PureWeen** [comment]
@Mikilll94 looking at the sample I think it's incorrect for the frame on the previewLayer to be set during the draw.

If you go into UICameraPreview and set the frame inside LayoutSubviews

```C#
		public override void LayoutSubviews()
		{
			base.LayoutSubviews();

			if (previewLayer != null)
				previewLayer.Frame = Bounds;
		}
```

Then it works

You can also see this issue with our sample if you change the orientation
I modified our sample
https://github.com/xamarin/xamarin-forms-samples/pull/584

Great find @Mikilll94 !!!
