### ISSUE TITLE
[Bug] The bottom half of CollectionView is blank space

### ISSUE THREAD

**Issue by Yutacchisoft** [xamarin/Xamarin.Forms#9630]
### Description
Launch the app with device orientation landscape ,the lower half of the CollectionView became a blank space.. Blank space does not appear when launching the app with the device orientation in 
portrait mode.

### Steps to Reproduce

1. In `UISupportedInterfaceOrientations` of `info.plist`, set the value to only `UIInterfaceOrientationPortrait`.
2. In Xaml, put `CollectionView` inside `StackLayout`.
3. Launch the app with device orientation landscape.

### Expected Behavior
All blank spaces are used for displaying items in `CollectionView`.

### Actual Behavior
The item display area becomes very narrow due to the blank space occupying half of the `CollectionView`.

### Basic Information

- Version with issue: 4.4.0.991640+471-sha.c1bdf538e-azdo.3443599
- Last known good version: I don't know
- IDE: Microsoft Visual Studio Enterprise 2019 Version 16.4.5
- Platform Target Frameworks:  .NET Standard 2.0
  - iOS:   10.0
- Nuget Packages: 5.4.0
- Affected Devices: iPhone 5s 12.4 Simulator

### Screenshots

1. Launch the app with device orientation landscape ,the lower half of the CollectionView became a blank space.. 
![landscape](https://user-images.githubusercontent.com/37888418/74810257-55224180-5332-11ea-843b-5f9f01c5ffdf.png)

2. Blank space does not appear when launching the app with the device orientation in 
portrait mode.
![portrait](https://user-images.githubusercontent.com/37888418/74810261-58b5c880-5332-11ea-8bb9-e94d07e5b6f3.png)

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4223565/App1.zip)

### Workaround

Don't put CollectionView inside StackLayout.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/9583
