### ISSUE TITLE
[UWP] How to scroll in CollectionView ?

### ISSUE THREAD

**Issue by MireTH** [xamarin/Xamarin.Forms#9631]
Hello, I would like to know if it is possible to scroll in a collectionView on UWP without using the ScrollBar? That is to say with a Click and slide or with the mouse wheel?

**Comment by hartez** [comment]
@MireTH If you're running on a desktop, the mouse wheel _should_ be scrolling it. Is that not working for you?

I don't believe "click and slide" works on desktop, but if you're running on a tablet you can scroll by dragging your finger.

**Comment by MireTH** [comment]
@hartez I am on a desk but the mouse wheel does not work at all..., but on tablet / smartphone it's ok

**Comment by jsuarezruiz** [comment]
I've done tests and the mouse wheel works with a vertical CollectionView but not horizontally. A touch mouse works (Ex: Magic Mouse, etc.).

**Comment by saiyamshah143** [comment]
Will the Collectionview reachedcommand and reachedcommandthreshold work on UWP?
Because with listview it loads all items at once #2478

**Comment by EmilAlipiev** [comment]
I have fixed that but i cant PR now until they merge or reject my other PR because i created the PR from my master fork and i don't want to waste my time with all those cherrypicking etc. I hope this year my other PR will be reviewed so we i can PR this fix as well :D

**Comment by EmilAlipiev** [comment]
Here is the PR resolves the issue including test case https://github.com/xamarin/Xamarin.Forms/pull/11372
