### ISSUE TITLE
[Bug] Update Xamarin.Forms macOS support status

### ISSUE THREAD

**Issue by mnxamdev** [xamarin/Xamarin.Forms#9639]
### Description
In attempting to communicate with stakeholders regarding the current state of support/stability for Xamarin.Forms on macOS and the feasibility for building a production app for macOS using Xamarin.Forms, we noticed the document mentioned below is out of date and could not find a good source for information on the topic.
### Steps to Reproduce

1. Go to https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status
2. See that it hasn't been updated since May 31, 2018

### Expected Behavior
Status is updated with recent developments.

### Actual Behavior
See that it hasn't been updated since May 31, 2018

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - macOS: 10.15.3

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
