### ISSUE TITLE
the password entry flow direction (Right to left) is not working !!!

### ISSUE THREAD

**Issue by mhrastegary77** [xamarin/Xamarin.Forms#9640]

**Comment by samhouts** [comment]
@mhrastegary77 Please fill out the entire issue template.  Can you please attach a small project that demonstrates this issue? Thanks!

**Comment by yurkinh** [comment]
@mhrastegary77 @mhrastegary77  This is the same issue as  [#9684](https://github.com/xamarin/Xamarin.Forms/issues/9684)

**Comment by samhouts** [comment]
Duplicate of #9684
