### ISSUE TITLE
[Bug][Android] OrientationStateTrigger not triggering on orientation change

### ISSUE THREAD

**Issue by davidbritch** [xamarin/Xamarin.Forms#9651]
### Description

`OrientationStateTrigger` isn't triggering for an orientation change on Android.

The `Style` below should result in different page background colours being applied, dependent upon device orientation. It's working fine on iOS (simulator) but not on Android (emulator). Note that my `MainActivity` is configured for receiving orientation changes.

```
        <Style x:Key="OrientationStateTriggerPageStyle"
               TargetType="ContentPage">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup>
                        <VisualState x:Name="Portrait">
                            <VisualState.StateTriggers>
                                <OrientationStateTrigger Orientation="Portrait" />
                            </VisualState.StateTriggers>
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="Silver" />
                            </VisualState.Setters>
                        </VisualState>
                        <VisualState x:Name="Landscape">
                            <VisualState.StateTriggers>
                                <OrientationStateTrigger Orientation="Landscape" />
                            </VisualState.StateTriggers>
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="White" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
```

### Steps to Reproduce

1. Run the attached sample on Android.
2. Browse to the OrientationStateTrigger demo page.
3. Change the device orientation.

### Expected Behavior

Portrait orientation has a silver page background colour. Landscape orientation has a white page background colour.

### Actual Behavior

Both portrait and landscape orientations have a silver background colour.

### Basic Information

- Version with issue: 4.5-pre4
- IDE: VSMac 8.4.6
- Platform Target Frameworks: 
  - Android: API 28

### Screenshots

Portrait:

![Screenshot_1582210671](https://user-images.githubusercontent.com/8092460/74947654-13a59b00-53f3-11ea-8019-f98818e443fb.png)

Landscape:

![Screenshot_1582210675](https://user-images.githubusercontent.com/8092460/74947668-1902e580-53f3-11ea-8fdc-8ffaf8824968.png)

### Reproduction Link

[WorkingWithTriggers.zip](https://github.com/xamarin/Xamarin.Forms/files/4231422/WorkingWithTriggers.zip)

**Comment by jsuarezruiz** [comment]
@davidbritch I have tested the attached sample and it seems to work correctly. Could you check it? What emulator are you using?

![issue9651](https://user-images.githubusercontent.com/6755973/84492287-41666680-aca6-11ea-862e-a99763954022.gif)

**Comment by davidbritch** [comment]
I just tried it again (using the sample ZIP above) and I still have the same problem. It's a Pixel 2 XL API 28 emulator.

**Comment by maexsp** [comment]
@jsuarezruiz @samhouts This is still not working. 
Tested also on a physcial Android Samsung Tablet Tab Active 3, Android 11 -> not working.
MainActivity derives from FormsAppCompatActivity and ConfigurationChanges = ConfigChanges.Orientation is also set.
