### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Edwardfelix08** [xamarin/Xamarin.Forms#9665]
We are using Xamarin Form to develop and App, 
Which will connect to a Bot framework(V4) chat bot via the DirectLine channel. 
We are able to connect to the bot and do a conversation with the bot.
But we are using Adaptive Cards, Hero Cards in the bot conversation.

Is there any document around on how to display the Cards in the Xamarin forms App. 
All the document related to it are almost a couple of years older.
Is there and example we can refer too or any other document around it.
Any help will be appreciated.

Thanks 
Edward

**Comment by PureWeen** [comment]
@Edwardfelix08 there's no first party support that I know of. I haven't used the bot framework but I think for Forms you'd just need to translate the data to your own views.

I've pinged someone internally that's putting something together similar to what you're using to see if they know of any public samples
