### ISSUE TITLE
[Enhancement] [UWP] TabbedPage is a disaster

### ISSUE THREAD

**Issue by MhAllan** [xamarin/Xamarin.Forms#9668]
Tabbed page is not looking any good and it is like impossible to fix it with custom renderer

- Icons disappear when you lock the screen
- Headers (tabs) can't fill the width (They stick by each other at the corner in very funny way!) .. The default behavior should be like Android's tabbed page.
- Icon default size is terrible
- Can't remove the selected tab underline effect (which by the way almost make the title unreadable)
- FormsPivot control exposes HeaderTemplate as DataTemplate instead of ControlTemplate which prevented me from using any useful online UWP fix for the headers
- FormsPivot hides GetDescendantsByName method, so if you think to make use of source code at Github and try to do something with that method you fail.

**Comment by jsuarezruiz** [comment]
We want to improve the possibilities when working with Tabs in Xamarin.Forms. From the proposal some issues can be created that would help to improve the behavior of TabbedPage in UWP (Example: fix Icons disappear when you lock the screen).

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
