### ISSUE TITLE
Deprecated API Usage UIWebView issue in ios

### ISSUE THREAD

**Issue by kaminipatel03** [xamarin/Xamarin.Forms#9669]
I got this warning email whenever i upload ios app on app store. AS in my project i searched for UIWebView but not found anything related to it.

 I have followed below website and according to that 

https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/webview?tabs=macos#uiwebview-deprecation-and-app-store-rejection-itms-90809

 i have updated xamaria.forms , xamarian.ios version.

Xamaria.forms version: 4.5.0.266-pre3
Xamarian.IOS Version: 13.10.0.17

If i set supported architechture ARM64 then not able to upload on app store give me message like The size of your app's executable file '/Payload/' is 74170368 bytes for architecture 'arm64', which exceeds the maximum allowed size of 60 MB. 
and also got email Deprecated API Usage UIWebView

**Comment by PureWeen** [comment]
Duplicate https://github.com/xamarin/Xamarin.Forms/issues/7323#issuecomment-574866448
