### ISSUE TITLE
[Enhancement] Xamarin Does Not Feel Production Ready in Terms of A11y

### ISSUE THREAD

**Issue by ryl** [xamarin/Xamarin.Forms#9670]
## Summary
Hello Xamarin Team,

I'm writing this feature request to say that we are really struggling hard to make our application accessibility friendly using Xamarin 4.X, and feel that it is close to impossible to deliver a high quality accessible experience the way things currently stand.

There are a lot of A11y tickets out there, but its hard to tell from the outside looking in what kind of priority and energy is being dedicated to them. Could someone speak to the awareness of accessibility on the Xamarin team?

I feel like we are in a really hard space right now thanks to A11y. We want the other bug fixes coming into Xamarin 4, and we are especially excited about the CollectionView, but it feels like A11y is actually regressing rather than improving. Here just a few problems we are having:

* Tab order in VoiceOver and TalkBack is very unpredictable. This makes for a very bad screen reader experience, and we have to bend over backwards with custom renderers to work around it.
* AutomationId is incompatible with AutomationName, AutomationHelpText on Android
* Difficulty reaching navigation items

## Intended Use Case
- I don't want writing UI Tests and Accessibility to be mutually exclusive on any platform.
- I don't want to struggle with tab order and basic screen reader functionality.
- I would like to be able to provide A11y roles to elements as needed.
- I want to be able to set name and help text and actually have them read by screen readers on all platforms, on any component.

**Comment by pauldipietro** [comment]
Hi @ryl -- Accessibility is a continuous top priority for us. If you'd like to provide some more examples of your work or speak directly about what you're working on and see if there are any areas for improvement aside from what you've mentioned, you're welcome to reach out (my email is paul.dipietro@microsoft.com).

To leave the conversation here open, I'm sorry that it's difficult for you to distinguish the priority of accessibility related issues. Coincidentally, after some very recent discussions we added a dedicated [project board](https://github.com/xamarin/Xamarin.Forms/projects/61) for those issues to better show where they are in the pipeline. Do you find that useful, and/or do you have any other suggestions to improve upon this?

**Comment by ryl** [comment]
Yes, the board is very useful and I was excited to see it appear. Please consider this feature request as a motion of support for the Accessibility project that was just created.

I wanted to let your team know A11y has been a pain point for us recently. The tension between other bug fixes and A11y is at the forefront of our minds recently, especially with planned deployments looming ever closer on the horizon. We feel like we are having to make painful decisions between fixing one thing, but making A11y worse as a side effect.

Here are some specific issues & pull requests that are directly related to my original post and stand out to me right now:
- https://github.com/xamarin/Xamarin.Forms/issues/9191
- https://github.com/xamarin/Xamarin.Forms/pull/5237
- https://github.com/xamarin/Xamarin.Forms/issues/1529

All of these appear to be in the Accessibility project, which is exciting to see. Right now the tab order read out by TalkBack and VoiceOver is our biggest pain point, which appears in my first bullet point.

**Comment by samhouts** [comment]
@ryl We're working on Tab Order right now!
