### ISSUE TITLE
[Enhancement] Outlined entry like in MD2

### ISSUE THREAD

**Issue by Mikilll94** [xamarin/Xamarin.Forms#9671]
## Summary
In Material Design 2 there is an option to create an outlined entry like this:
![md2_entry](https://user-images.githubusercontent.com/17653648/75062056-4ed2c780-54e2-11ea-874f-ba52b2b59eb9.gif)

However, in Xamarin it is not possible to create such an entry. And doing this with custom renderers is very hard.

## API Changes

Many solutions are possible:
- add platform-specific on Android to enable outlined entries
- add border/outline prop to entry

## Intended Use Case
As a developer, I want to easily create an entry with an outline.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/5005

**Comment by saiyamshah143** [comment]
@Mikilll94 You can refer this link. Custom Renderer is not too hard to implement.
https://stackoverflow.com/questions/59132739/outlined-textbox-in-xamarin-forms
