### ISSUE TITLE
[Bug] [Material] DatePicker and TimePicker don't support Material Title

### ISSUE THREAD

**Issue by rbonestell** [xamarin/Xamarin.Forms#9674]
### Description

The Material DatePicker (and TimePicker) `Title` Property is not used as hint, placeholder, or label for the Material DatePicker.

It appears this has been resolved for the Picker control: https://github.com/xamarin/Xamarin.Forms/issues/5497#issuecomment-589815110

### Steps to Reproduce

1. Add a DatePicker (or TimePicker) to a Xamarin.Forms Page
2. Attempt to set a `Title` value for the newly added DatePicker, such as: `<DatePicker Title="Birth Date" />`
3. Note that the `Title` text is not displayed or utilized when the form is rendered.

### Expected Behavior
Like the existing Picker control behavior, the DatePicker and TimePicker should implement and present the Title text string as a form label for Material Design controls.

### Actual Behavior
The DatePicker and TimePicker do not utilize the `Title` text string at all, leaving the control with no Material placeholder or title.

### Basic Information

- Version with issue: 4.4.0.991640 (Xamarin.Forms and Xamarin.Forms.Visual.Material)
- Last known good version:
- IDE: Visual Studio for Mac v8.4.6 build 36
- Platform Target Frameworks: 
  - iOS:  13.2
  - Android: 9
  - UWP:  N/A
- Android Support Library Version: N/A
- Nuget Packages: 4.4.0.991640 (Xamarin.Forms and Xamarin.Forms.Visual.Material)
- Affected Devices: Android and iOS, broad range of devices.

### Screenshots
(Copying screenshot from issue #5497)
![image](https://user-images.githubusercontent.com/3430352/75069572-aeaf7b00-54ae-11ea-91aa-1b8663754640.png)

**Comment by PureWeen** [comment]
@JamesRoche beat you to it :-) https://github.com/xamarin/Xamarin.Forms/issues/9673

**Comment by sajanmittal** [comment]
These issues being closed without any fix?

**Comment by criapix** [comment]
No solution to this problem?? This turns the material theme unusable.

**Comment by rbonestell** [comment]
@sajanmittal @criapix It looks like this issue has been moved to the .NET MAUI project?
https://github.com/xamarin/Xamarin.Forms/issues/9673
