### ISSUE TITLE
[Enhancement] Support built-in back button on UWP NavigationView

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Xamarin.Forms#9685]
## Summary
The [AppViewBackButtonVisibility](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.appviewbackbuttonvisibility) is no longer recommended since version `1709`: [System back behavior for backward compatibilities](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#system-back-behavior-for-backward-compatibilities)

![image](https://user-images.githubusercontent.com/4254116/75115648-bd3d9400-5660-11ea-8809-350f5f98c4b2.png)

[UWP guidelines mentions](https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation#back-button) that the button should be placed on the top left. I think the `Back button` should be in the `NavigationBar`, like iOS and Android.

![image](https://user-images.githubusercontent.com/4254116/75115751-edd1fd80-5661-11ea-847b-65702f838230.png)

## API Changes

I propose to add a platform specific `AttachedProperty` to define the default place of the Back Button on UWP.
````cs
public static readonly BindableProperty BackButtonModeProperty = BindableProperty.CreateAttached("BackButtonMode", typeof(BackButtonMode), typeof(NavigationPage), BackButtonMode.NavigationView);

public enum BackButtonMode
{
    TitleView,
    NavigationView
}
````
Use [System.NavigationManager.ViewBackButtonVisibility](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.appviewbackbuttonvisibility) for `TitleView` mode and [NavigationView.IsBackButtonVisible](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.IsBackButtonVisible) for `NavigationView` mode.

## Intended Use Case
Support built-in back button of `NavigationView` on UWP.

**Comment by EmilAlipiev** [comment]
this is great but xamarin.forms doesnt implement navigationview at all. What we have as tabbedpage is pivot control. We need first a navigationview. am i missing something?
