### ISSUE TITLE
[Bug, CollectionView,iOS] Foundation.Monotouch Exception in Grouped CollectionView 

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#9686]
### Description
I have a Grouped CollectionView in one of my apps. I am using TapGestureRecognizer on CollectionViewHeader for showing and hiding the grouped items. The issue is that whenever I tap on any Header except the last one the Foundation.Monotouch Exception is being thrown on iOS. This does not happen if I tap on the last item first. After that tapping on any item does not throw the exception. 

### Basic Information

- Version with issue:Xamarin.Forms 4.4.0.991640
- Affected Devices:iOS

### Reproduction Link
[CollectionRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4241809/CollectionRepro.zip)

**Comment by jsuarezruiz** [comment]
Can reproduce the error  if start tapping from the first element. Starting from the last does not happen.
<img width="452" alt="Captura de pantalla 2020-02-25 a las 13 27 34" src="https://user-images.githubusercontent.com/6755973/75248552-a750e000-57d4-11ea-9a3c-d0183e58edca.png">
