### ISSUE TITLE
[Bug, CollectionView] Setting SelectedItem to null in ViewModel does not clear the selection in CollectionView

### ISSUE THREAD

**Issue by HobDev** [xamarin/Xamarin.Forms#9687]
### Description
In  the ViewModel I am setting the SelectedItem to null. But this does not clear the selection of the SelectedItem in View. The CollectionView is Grouped

### Basic Information

- Version with issue:Xamarin.Forms 4.4.0.991640

- Affected Devices:iOS and Android

### Reproduction Link

[CollectionRepro.zip](https://github.com/xamarin/Xamarin.Forms/files/4241836/CollectionRepro.zip)

**Comment by zstarkebaumcalico** [comment]
It looks like the selection event is not firing on the main thread. I was able to work around this issue by dispatching to the main thread:
``` C#
Device.BeginInvokeOnMainThread(() => CollectionView.SelectedItem = null);
```

**Comment by hartez** [comment]
This works in 5.0.0.1931. Not sure if it worked in earlier versions. There are a couple of problems with the repro project:

- The type declared for `SelectedItem` in `MainViewModel` is `HazardGroup` - it should be `Hazard`.
- The `Reactive` attribute decoration doesn't seem to work properly; if I remove that and implement `INotifyPropertyChanged` manually (including adding a backing member for `SelectedItem` and invoking `PropertyChange`), the example works fine. I don't know what Fody.Weavers is doing in the generated implementation of INPC, but if I had to guess there's something that prevents a property from being changed within its own PropertyChange handler (maybe for avoiding loops?).

Anyway, this either never was an issue, or it's no longer an issue as of 5.0.0.
