### ISSUE TITLE
[Bug] httpclient is permanently unresponsive

### ISSUE THREAD

**Issue by shouhujishu** [xamarin/Xamarin.Forms#9703]
### Description
xamarin.forms 
When using httpclient to access an address that does not exist on the port, it will cause an infinite stuck waiting timeout invalid.
### Steps to Reproduce

 System.Net.Http.HttpClient http = new System.Net.Http.HttpClient();
  http.Timeout = TimeSpan.FromMilliseconds(300);
  var N = await http.GetAsync("https://www.baidu.com:8000");

### Expected Behavior
Connection error
### Actual Behavior
(Task.run)Wait indefinitely and cause the main thread to become unresponsive
### Basic Information

- Version with issue: Xamarin   16.4.000.311 (d16-4@ddfd842)
- Last known good version:
- IDE:Microsoft Visual Studio Professional 2019版本 16.4.5
- Platform Target Frameworks: Android
  - Android: 9.0
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by VladislavAntonyuk** [comment]
I suppose it is an issue of http client rather than xamarin forms. 
I suggest you to use this method, so you can cancel request whenever you want: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=netframework-4.8#System_Net_Http_HttpClient_GetAsync_System_String_System_Threading_CancellationToken_

**Comment by shouhujishu** [comment]
> 我想这是http客户端而不是xamarin形式的问题。
> 我建议您使用此方法，以便您可以随时取消请求：[https](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=netframework-4.8#System_Net_Http_HttpClient_GetAsync_System_String_System_Threading_CancellationToken) : [//docs.microsoft.com/zh-cn/dotnet/api/system.net.http.httpclient.getasync?view=netframework-4.8 #System_Net_Http_HttpClient_GetAsync_System_String_System_Threading_CancellationToken](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getasync?view=netframework-4.8#System_Net_Http_HttpClient_GetAsync_System_String_System_Threading_CancellationToken) _

Sorry I don't know where to submit the problem. If I request the same under windows, an exception will be triggered and it will lose response under xamarin

**Comment by jsuarezruiz** [comment]
@shouhujishu You can report this to **Xamarin.Android** https://github.com/xamarin/xamarin-android/issues

**Comment by jsuarezruiz** [comment]
I am going to close the issue because is not directly related with Xamarin.Forms. Let me know if you need help moving the issue with Xamarin.Android!.
