### ISSUE TITLE
[Bug] Xamarin web view not dismissing on DismissViewController

### ISSUE THREAD

**Issue by tm-peyton-dent** [xamarin/Xamarin.Forms#9712]
We've been fighting for days attempting to get a Xamarin.Auth web view to close. We passed it into a renderer in iOS and can call DismissViewController but it doesn't seem to go away. And weirdly enough, it's saying the view is not being presented when investigating the object.

**Comment by jsuarezruiz** [comment]
@tm-peyton-dent The issue seem to be related with https://github.com/xamarin/Xamarin.Auth, could you open an issue there?.

On the other hand, Xamarin Essentials has included https://github.com/xamarin/Essentials/tree/develop/Xamarin.Essentials/WebAuthenticator Do you know it, have you tried it? Maybe it fits what you need.

**Comment by samhouts** [comment]
@tm-peyton-dent  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
