### ISSUE TITLE
[Enhancement] Request OnPlatform value support Bindable element!

### ISSUE THREAD

**Issue by huangjinshe** [xamarin/Xamarin.Forms#9716]
## Summary
**We need OnPlatform value Support bindable element, then more usefull for us.** 

## API Changes

**OnPlatform**

Currently Only working like this:

```
<OnPlatform x:TypeArguments="x:String" x:Key="NormalFont">
    <On Platform="Android" Value="MyFont.ttf#My Font" />
    <On Platform="UWP" Value="/Assets/MyFont.ttf#My Font" />
     <On Platform="iOS" Value="MyFont" />
</OnPlatform>
```

After Changin it:

```
<OnPlatform x:TypeArguments="x:String" x:Key="NormalFont">
    <On Platform="Android" Value="{Binding Android_Font}" />
    <On Platform="UWP" Value="{Binding UWP_Font}" />
     <On Platform="iOS" Value="{Binding iOS_Font}" />
</OnPlatform>
```

**Comment by huangjinshe** [comment]
1 years and not finish???

**Comment by huangjinshe** [comment]
After 2 years still not finish???

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
