### ISSUE TITLE
[Enhancement] Pivot & Panorama controls!

### ISSUE THREAD

**Issue by realzhaorong** [xamarin/Xamarin.Forms#9718]
![Panorama](https://blog.rectorsquid.com/wp-content/uploads/2013/07/image.png)

![Pivot](https://blog.rectorsquid.com/wp-content/uploads/2013/07/image1.png)

I used to be a developer on wp7/8, and I think the Pivot and Panorama controls provide a wonderful user experience, so I was wondering if you could bring them to Xamarin, this would be a great idea.

**Comment by jsuarezruiz** [comment]
Thanks for the feedback. Some doubts, are you interested in having the look & feek we had in Windows Phone?. The Pivot concept is similar to what you can have with Tabs.
The case of the Panorama is somewhat different. A Panorama consists of multiple panels (views) that each represent a page. At any one time, only one panorama item is visible alongside a small portion of the previous or next panorama item. Mnn, adding the possibility of having a cyclic CarouselView and using PeekAreaInsets you can achieve a similar result.
Feel free to add any details you consider!.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
