### ISSUE TITLE
[Bug] SwipeView in 4.5 works only first way swipped

### ISSUE THREAD

**Issue by ianvink** [xamarin/Xamarin.Forms#9734]
Using the 4.5 release .

Android

I have a swipe view inside a Collection.ItemTemplate. When you swipe left, then only left works from then on. If you go right, then only right works.

**see gif video attached**. I show that if I swipe a little you can see the left and right items appear. But if I fully swipe on way, then the other way is no longer accessable.

 
        <Grid RowSpacing="0" ColumnSpacing="0" VerticalOptions="FillAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="Auto" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>

            <common:LottieLoader Grid.Row="0"  IsVisible="{Binding IsBusyAddressBookRelatedItems}" />

            <common:NoResults Grid.Row="1"
                              FontAwesomeIcon="{x:Static local:FontAwesomeFont.HandshakeAlt}"
                              Line1="There are no related items. "
                              Line2=""
                              Command="{Binding RefreshCommand}"
                              IsVisible="{Binding HasNoAddressBookRelatedItems}" />

 
            <CollectionView Grid.Row="1"
                            x:Name="MyCollectionView"
                            ItemsSource="{Binding AddressBookRelatedItems}"
                            IsVisible="{Binding HasNoAddressBookRelatedItems, Converter={ StaticResource NegateBooleanConverter }}"
                            androidSpecific:ListView.IsFastScrollEnabled="True"
                            VerticalOptions="FillAndExpand"
                            ItemSizingStrategy="MeasureAllItems">
                <CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="addressBook:AddressBookRelatedItem">
                             <SwipeView > 
                                 <SwipeView.RightItems> 
                                     <SwipeItems> 
                                         <SwipeItem Command="{Binding Source={x:Reference MyPage}, Path=BindingContext.DeleteAddressBookRelatedTappedCommand}"  
                                                    CommandParameter="{Binding .}"  
                                                    Text="Delete"  
                                                    IconImageSource="{StaticResource TrashCanImage}" 
                                                    BackgroundColor="{DynamicResource DeleteButtonColor}" /> 
                                     </SwipeItems> 
                                 </SwipeView.RightItems> 
                             
                                 <SwipeView.LeftItems> 
                                     <SwipeItems> 
                                         <SwipeItem 
                                             Command="{Binding Source={x:Reference MyPage}, Path=BindingContext.EditAddressBookRelatedTappedCommand}" 
                                             CommandParameter="{Binding .}" 
                                             Text="Edit" 
                                             IconImageSource="{StaticResource EditImage}" 
                                             BackgroundColor="{DynamicResource SaveButtonColor}" /> 
                                     </SwipeItems> 
                                 </SwipeView.LeftItems> 

                            <gestures:Grid
                                TappedCommand="{Binding Source={RelativeSource AncestorType={x:Type detailModels:AddressBookDetailViewModel}},
                                Path=AddressBookRelatedTappedCommand}"
                                TappedCommandParameter="{Binding .}"
                                VerticalOptions="Start"
                                BackgroundColor="White">
                                
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="Auto" />
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>

                                <shared:CircleImage
                                    Grid.Column="0"
                                    Source="{Binding Image}"
                                    Style="{ StaticResource AvatarXSmall }"
                                    Aspect="AspectFill"
                                    HorizontalOptions="CenterAndExpand"
                                    Margin="10,13,0,0"
                                    VerticalOptions="Start" />

                                <StackLayout
                                    Grid.Column="1"
                                    VerticalOptions="StartAndExpand"
                                    Padding="10, 10, 10, 10"
                                    Spacing="3"
                                    Orientation="Vertical"
                                    HorizontalOptions="FillAndExpand">

                                    <Label
                                        Text="{Binding Title}"
                                        HorizontalOptions="Fill"
                                        LineBreakMode="TailTruncation"
                                        MaxLines="2"
                                        VerticalOptions="EndAndExpand"
                                        Style="{DynamicResource TextSize5ListView}" />

                                    <Label
                                        Text="{Binding SubTitle}"
                                        LineBreakMode="TailTruncation"
                                        MaxLines="2"
                                        IsVisible="{ Binding IsSubTitleVisible }"
                                        VerticalOptions="FillAndExpand"
                                        Style="{DynamicResource TextSize4ListView}"
                                        FontAttributes="Bold"
                                        HorizontalOptions="Start" />

                                    <Label
                                        Text="{Binding Relation}"
                                        IsVisible="{ Binding Relation, Converter={ StaticResource IsNotStringEmptyConverter} }"
                                        LineBreakMode="WordWrap"
                                        MaxLines="2"
                                        Style="{DynamicResource LabelNoteStyle}"
                                        VerticalOptions="FillAndExpand"
                                        HorizontalOptions="Start" />

                                </StackLayout>
                            </gestures:Grid>
                           </SwipeView>  
                    </DataTemplate>
                </CollectionView.ItemTemplate>
 
            </CollectionView>

            <Grid Grid.Row="1"
                  VerticalOptions="EndAndExpand"
                  HorizontalOptions="End">
                <common:FabPageButton x:Name="fabCreateButton" Command="{Binding AddAddressBookRelatedCommand}" />
            </Grid>

        </Grid>
     
    </ContentView.Content>
   </ContentView>

![animation](https://user-images.githubusercontent.com/112916/75399809-1fd99e80-58b2-11ea-8ff9-723881bffb3a.gif)

**Comment by jsuarezruiz** [comment]
@iainx Thanks for the feedback. This issue will be fixed by https://github.com/xamarin/Xamarin.Forms/pull/9664
I have included a sample to validate your case (well, same layout but replacing custom components like the custom Grid or the CircleImage) in the PR. 
![issue9734](https://user-images.githubusercontent.com/6755973/75441143-69cb8e80-595d-11ea-892f-86793bfd9c8d.gif)

**Comment by samhouts** [comment]
closed by #9464
