### ISSUE TITLE
[Bug] Shell.Current.Navigation.PopAsync(true) causing blink on Android

### ISSUE THREAD

**Issue by KevinHu-au** [xamarin/Xamarin.Forms#9736]
### Description
On Android device, when navigating back by calling Shell.Current.Navigation.PopAsync(true) with animation, it is causing quick blink on the device.
### Steps to Reproduce

1. Under a Xamarin.Forms Shell App, navigating From Page A to Page B by calling "Shell.Current.GoToAsync("PageB", true)". 
2. And pop the Page B from the navigation by calling "Shell.Current.Navigation.PopAsync(true)"
The first step (pusing the PageB into the navigation stack with animation) works fine for me on Android. 
### Expected Behavior
Should have a smooth navigation experience.
### Actual Behavior
The pop step gets blink on Android.
### Basic Information

- Version with issue: Xamarin.Forms 4.4.0.991265
- Last known good version: N/A
- IDE: Visual Studio for Mac community 8.4 (build 2657)
- Platform Target Frameworks: 
  - iOS:  10.0
  - Android: Android 10.0(Q)
  - UWP:  N/A
- Android Support Library Version: 
- Nuget Packages: 
- Affected Devices: Samsung Galaxy A20

### Screenshots
As it is a blink issue, I cannot provide screenshots.

**Comment by ahmedalejo** [comment]
I can confirm this and it duplicates the following issues:
#9300 xamarin shell navigation flickering on back press
#8581 [Bug] Shell application flickering on back navigation

**Comment by jsuarezruiz** [comment]
Seems to be the same as https://github.com/xamarin/Xamarin.Forms/issues/8581

**Comment by ahmedalejo** [comment]
### Workaround
disable animation
```csharp
Shell.Current.Navigation.PopAsync(animated: false)
```

**Comment by KevinHu-au** [comment]
I did take out of the animation by setting the animated to false.

**Comment by alex-relov** [comment]
please solve this problem. I can not put the application in production

**Comment by KevinHu-au** [comment]
I have also found the blink issue occurs for "Shell.Current.GoToAsync()" with animated 'true' and 'false'.

Please check my comment on https://github.com/xamarin/Xamarin.Forms/issues/8581.

**Comment by PureWeen** [comment]
duplicate https://github.com/xamarin/Xamarin.Forms/issues/8581

**Comment by ahmedalejo** [comment]
[Shell] navigation - flickering #5755
