### ISSUE TITLE
[Enhancement] SwipeViewItem parent is null, shouldn't be

### ISSUE THREAD

**Issue by tomeverin** [xamarin/Xamarin.Forms#9738]
## Summary
SwipeViewItem in SwipeView in the context of templated use in CollectionView has null parent. This means that RelativeSource binding fails to locate the ancestral BindingContext.... which would generally be the ViewModel.

This means that, in XAML implementation, the Command property for a SwipeViewItem is very difficult to set. 

## API Changes

Would be great if the following would work:
`<SwipeItemView Command="{Binding Source={RelativeSource AncestorType={x:Type myns:MyViewModel}}, Path=SwipeItemTapCommand}" CommandParameter="{Binding .}">`

## Intended Use Case
To bind ViewModel Command properties to the UI in the same way we would for other templated collection views

**Comment by jsuarezruiz** [comment]
Thanks for the feedback, the fix will be available with this PR: https://github.com/xamarin/Xamarin.Forms/pull/9743

Meanwhile, something like:
`Command="{Binding Source={x:Reference CollectionView}, Path=BindingContext.Command}"`
must work.

**Comment by tomeverin** [comment]
@jsuarezruiz Thanks!
