### ISSUE TITLE
[Bug] The attachable property itemsSourceBy was not found in Indicatorview

### ISSUE THREAD

**Issue by johnmackerras** [xamarin/Xamarin.Forms#9739]
The attachable property itemsSourceBy was not found in Indicatorview.
Release: 4.5.0.356

Issue fixed by reverting to previous release. I canl tfind anything indicating it was a concious descision to remove thiis or any alternative solution, so presuming this is an ommisison.

**Comment by VladislavAntonyuk** [comment]
It was removed https://github.com/xamarin/Xamarin.Forms/pull/9332/

Now you should set IndicatorView property in your CarouselView

**Comment by VladislavAntonyuk** [comment]
By the way documentation needs to be changed https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview

**Comment by jsuarezruiz** [comment]
The IndicatorView is in Experimental phase and we continue to improve. In this case, **ItemsSourceBy** has been replaced with the **IndicatorView** property in CarouselView. It is easier to link both views.
