### ISSUE TITLE
[Documentation] Guideline for debugging e testing ...

### ISSUE THREAD

**Issue by workgroupengineering** [xamarin/Xamarin.Forms#9747]
Create documents that give guidelines for:
- [ ] Debugging Xaml[C] parser and task
- [ ] Debugging Render
- [ ] Create UITest
- [ ] Create Integration Test XAML
- [ ] Create Integration Test Binding

**Comment by jfversluis** [comment]
Thanks for the suggestions! Please have a look at our Docs for a great variety of wonderful how-to guides! If you still feel anything is missing, please report it through there. Thanks!
