### ISSUE TITLE
[Bug] Slider broken in 4.5.0.356 on macOS

### ISSUE THREAD

**Issue by SeRgI1982** [xamarin/Xamarin.Forms#9748]
### Description
Slider is displayed but doesn't react on changed values by the user.
Changing value works as expected when change value by binded property in the viewModel.

### Steps to Reproduce

1. Put Slider in XAML, name it (slider), set min/max values (from 0 to 100),
2. Bind slider.Value with property in ViewModel (for ex. SliderValue) 
3. Bind Label.Text with slider.Value (Label.Text="{Binding Value, Source={x:Reference slider}}") 

### Expected Behavior
Label.Text will change his text according to current value of slider.
SliderValue in ViewModel will be notified when slider value in UI will change.

### Actual Behavior
Slider doesn't inform other objects about changing value.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: 4.4.0.991640

- IDE:
- Platform Target Frameworks: 
  - macOS:  10.15.3
- Affected Devices: macbook Pro

### Screenshots

![Screenshot 2020-02-27 at 12 57 19](https://user-images.githubusercontent.com/9572525/75444476-ca5dca00-5963-11ea-81ca-eb2c52817b06.png)

**Comment by jsuarezruiz** [comment]
I have created a repro sample and can reproduce the issue:
![issue9748](https://user-images.githubusercontent.com/6755973/75447967-a356c680-596a-11ea-8a39-6a31d05051bf.gif)

[issue9748.zip](https://github.com/xamarin/Xamarin.Forms/files/4261728/issue9748.zip)
