### ISSUE TITLE
System.MissingMethodException: 'Default constructor not found for type Xamarin.Forms.Platform.iOS.ShellRenderer'[Bug] 

### ISSUE THREAD

**Issue by SurojuUttej** [xamarin/Xamarin.Forms#9752]
### Description

Please Note: 1. Linker Behaviour - Link All" - Worked fine with Blank and getting issue with Shell.
                     2. Linker Behaviour - Don't Link" - Getting warning mail from Apple when trying to upload to test flight.
### Steps to Reproduce

1. Updating Xamarin Forms 4.5.0.356 with Shell in empty project .
2. IOS Properties >IOS build>Keep "Linker Behaviour - Link All" with Shell and UIWebView Depreciation solution.
3.So i tried with an empty shell application and its the
error :System.MissingMethodException: ‘Default constructor not found for type Xamarin.Forms.Platform.iOS.ShellRenderer’
4. And also i tried with blank application with UIWebView Depreciation Solution it’s Working fine.

I think some issue with shell, So please help me out from this, Thanks in advance.

### Reproduction Link

https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms - - with Xamrinforms Shell (4.5.0.356) and Linker Behaviour - Link All
1. When keeping "Linker Behaviour -Don't Link" as per document, the UIwebView issue was getting.

**Comment by PureWeen** [comment]
The error @jsuarezruiz is seeing is different than the error @SurojuUttej is seeing

With @jsuarezruiz 's error that's coming from the template. If you add a preserve attribute to the ItemsPage in the template then it should work for you

@SurojuUttej your error seems like your XF versions are possibly out of sync

Can you attach a repro that matches your exception? 

You could also try just setting your linker to Link SDK Only

It should still linkout the UIWebView

**Comment by SurojuUttej** [comment]
> The error @jsuarezruiz is seeing is different than the error @SurojuUttej is seeing
> 
> With @jsuarezruiz 's error that's coming from the template. If you add a preserve attribute to the ItemsPage in the template then it should work for you
> 
> @SurojuUttej your error seems like your XF versions are possibly out of sync
> 
> Can you attach a repro that matches your exception?
> 
> You could also try just setting your linker to Link SDK Only
> 
> It should still linkout the UIWebView

Hi @PureWeen  thanks for reply, its an issue with Shell project, please find the repo i have attached in this.

"You could also try just setting your linker to Link SDK Only" - i have tried but it did'nt worked for me its throwing a warning mail regarding UIwebview issue when am uploading to test flight, but app working fine.

And the issue i was posted yesterday was due to "linker to Link All " with an empty shell project.

Actually when am ruuning my Project its throwing the issue similar to @jsuarezruiz .
@jsuarezruiz once you can check with doing the same set-up of your project to an empty shell project for better understanding, and the below image was my issue maybe it can help you.
![image_2020_02_27T13_26_30_973Z](https://user-images.githubusercontent.com/43954414/75512038-2d0f9e00-5a16-11ea-9c23-9c2cedf9b857.png)



[UIWebViewXF.zip](https://github.com/xamarin/Xamarin.Forms/files/4265285/UIWebViewXF.zip)

**Comment by hartez** [comment]
I can't speak to the WebView stuff, but the attached project definitely crashes at startup when the Linker is set to 'all'.
