### ISSUE TITLE
[iOS] Set UITableView.AllowsSelection to match ListView.SelectionMode

### ISSUE THREAD

**Issue by jcmanke** [xamarin/Xamarin.Forms#9757]
## Summary

In the iOS ListViewRenderer, set Control.AllowsSelection to true or false according to the value of Element.SelectionMode.

This was suggested as the implementation of ListViewSelectionMode in #1801, but was not actually done in #2143.

## API Changes

In iOS ListViewRenderer:
```
void UpdateSelectionMode()
{
	if (Element.SelectionMode == ListViewSelectionMode.None)
	{
		// Add this line
		Control.AllowsSelection = false;

		Element.SelectedItem = null;
		var selectedIndexPath = Control.IndexPathForSelectedRow;
		if (selectedIndexPath != null)
			Control.DeselectRow(selectedIndexPath, false);
	}
	// Add this else statement
	else
	{
		Control.AllowsSelection = true;
	}
}
```

## Intended Use Case
Make the UITableView actually not selectable, instead of just deselecting whenever a selection is made. Would fix #3463 for iOS.

**Comment by jcmanke** [comment]
After doing a bit more research, it looks like this would disable the ItemTapped event, which would be an API change.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
