### ISSUE TITLE
[Bug] When FlyoutItem has more than 4 ShellContentPages, clicking all of the other shows a "more" page with last ShellContent items.

### ISSUE THREAD

**Issue by orlandommb** [xamarin/Xamarin.Forms#9758]
### Description
Navigating from Shell to TabbedPage shows a "more" page with las 3 Shell Flyout ShellContent items. In those last 3 flyout ShellContent items is the tabbedpage i want to navigate to.

### Steps to Reproduce

1. Create Shell Page and Tabbed Page
2. Add Tabbed Page To Shell Flyout Menu
3. Navigate to TabbedPage from Shell Flyout menu.

### Expected Behavior
Present the TabbedPage with children content pages.
### Actual Behavior
Presents a "More" page with last three ShellContent items from flyout menu.
### Basic Information

- Version with issue: Xamarin.Forms 4.5
- Last known good version:
- IDE: Visual Studio for MacOs
- Platform Target Frameworks: 
  - iOS:  13.3
  - Android: 9.0
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:
iOS Simulator
### Screenshots

<img width="451" alt="Captura de Pantalla 2020-02-27 a la(s) 9 41 39 a  m" src="https://user-images.githubusercontent.com/12052916/75469143-deee9200-5964-11ea-97a3-05a48b015e24.png">

<img width="465" alt="Captura de Pantalla 2020-02-27 a la(s) 9 43 18 a  m" src="https://user-images.githubusercontent.com/12052916/75469167-e746cd00-5964-11ea-90fe-6a82758ee533.png">

**Comment by orlandommb** [comment]
UPDATE - This happens with any content page set as ShellContent when un click all of the others.

**Comment by hartez** [comment]
@orlandommb I'm trying to reproduce the issue you're describing, but I'm not having any luck.

Here's my attempt:
[_9758 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4277971/_9758.Repro.zip)

Can you take a look and tell me if I've misunderstood the structure you describe?

**Comment by orlandommb** [comment]
this is my code for ShellPage:

<Shell xmlns="http://xamarin.com/schemas/2014/forms"
       xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
       xmlns:d="http://xamarin.com/schemas/2014/forms/design"
       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
       xmlns:local="clr-namespace:AlphaSoftPOSApp.View"
       mc:Ignorable="d"
       x:Class="AlphaSoftPOSApp.View.MainMenuPage"
       Shell.TabBarIsVisible="False"
       Shell.NavBarIsVisible="True"
       >

    <Shell.FlyoutHeaderTemplate>
        <DataTemplate>
            <local:FlyoutHeaderContentView/>
        </DataTemplate>
    </Shell.FlyoutHeaderTemplate>

    <FlyoutItem FlyoutDisplayOptions="AsMultipleItems"
                >
        
        
        <ShellContent Title="Impuestos"
                      Icon="dollarsymbol1.png"
                      ContentTemplate="{DataTemplate local:ImpuestosPage}" />
        <ShellContent Title="Configuracion"
                      Icon="smartphoneConfig.png"
                      ContentTemplate="{DataTemplate local:ConfiguracionPage}" />
        
        <ShellContent Title="Usuarios"
                      Icon="smartphoneConfig.png"
                      ContentTemplate="{DataTemplate local:UsuarioMenu}" />
        <ShellContent Title="Roles"
                      Icon="smartphoneConfig.png"
                      ContentTemplate="{DataTemplate local:RolesMenuPage}" />
        
    </FlyoutItem>


    <MenuItem IconImageSource="logout32x32.png" Text="Logout" Clicked="Btn_Logout_Clicked"/>

</Shell>

probably my code is the problem, let me change it real quick to see if the more page pops up again...

**Comment by orlandommb** [comment]
yup, it was definitely an issue with the flyout item displaying as multiple items... once a set up my shell page as yours with each page being inside of a flyout item it worked smooth, but is that how is supposed to behave a flyout item with display options as multiple items?

**Comment by jfversluis** [comment]
I'm sorry but I don't quite get your last question. Everything on Shell and the Flyout items is documented [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout).

If you believe there is still a bug, please feel free to add info here and reopen or open a new issue linking to this one.

Thanks!

**Comment by Mahesh199811** [comment]
Hey Any one knows how to remove the gap between the flyoutheader and the flyoutitem
