### ISSUE TITLE
[Bug] CollectionView - GridLayout - ExpandAndFill ??

### ISSUE THREAD

**Issue by rroesler** [xamarin/Xamarin.Forms#9766]
### Description

New (4.5) CollectionView is much better than the previous release, thanks.

In this new build, on iOS and Droid, the Collection View / Grid Layout / Span = n behaves as if the view is a Grid View and that each grid cell is set to Expand and Fill 

Previously, the the behaviour seemed to be Center (without expand or fill) 

Was this intentional ?  

### Steps to Reproduce

1. Collection View, Grid Layout, Span = 1 
2. Grouping turned on (not sure if this matters) 

### Expected Behavior

?? Not really sure.  Documentation implies Center or at least not expand and fill.   MeasureFirst or MeasureAll implies that each item (or each row when span > 1, would be independently sized.

### Actual Behavior

The the minor axes (i,e, width layout is set to vertical) the cells are set as if xxOptions=ExpandAndFill (i.e. HorizontalOptions=ExpandAndFill

### Basic Information

- Version with issue: Xmarain.Forms 4.5 
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

Use something like a BoxView or StackLayout or GridView (of one cell) to allow contents to float within the CollectionView cell

**Comment by rroesler** [comment]
Sorry, forgot to mention that HeightRequested and WidthRequested DataTemplate(d) element was ignore or overridden by the ColelctionView layout

**Comment by hartez** [comment]
@rroesler The current behavior is intentional.

**Comment by rroesler** [comment]
Thanks
