### ISSUE TITLE
[Bug] [iOS] NavigationBar resetting TextColor to black at every change of BarBackgroundColor

### ISSUE THREAD

**Issue by luccasclezar** [xamarin/Xamarin.Forms#9767]
### Description

Well, basically the PropertyChanged of BarBackgroundColor resets the NavigationBar's Appearance instead of modifying the current one. You can see this happening at this line:

https://github.com/xamarin/Xamarin.Forms/blob/6a23b8452e7833dbcbb20b2a6ca6699d33db695f/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L631

If this line is changed to: 

`var navigationBarAppearance = NavigationBar.StandardAppearance;`

The bug is gone.

I can't provide any repro projects as I'm experiencing this issue on a commercial app and couldn't reproduce the issue on a new project, but just looking at the line I linked it's possible to understand that the code should be like I said if nothing is meant to be overwritten.

I tested this modification with the said commercial app and it's working. 🙂

### Basic Information

- Version with issue: 4.5
- Platform Target Frameworks:
  - iOS:  13 (13.3.1)

### Workaround

On a new NavigationRenderer's PropertyChanged, copy the code of `UpdateBarBackgroundColor` (https://github.com/xamarin/Xamarin.Forms/blob/6a23b8452e7833dbcbb20b2a6ca6699d33db695f/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs#L618) and replace `new UINavigationBarAppearance()` to `NavigationBar.StandardAppearance` as I said in the description.

**Comment by vniehues** [comment]
I have the exact same issue. I use the app resources to theme my app based on the OS theme (android 10 & iOS 13) and while everything else changes perfectly, the NavigationBar is off. 
Switching the page and going back will result in the correct colors showing again.
