### ISSUE TITLE
[Bug] Xamarin Forms: "Value cannot be null. Parameter name: value"

### ISSUE THREAD

**Issue by IoTFier** [xamarin/Xamarin.Forms#9768]
### Description
My Xamarin Forms App crashes on iOS with the error Value cannot be null. Parameter name: value

### Steps to Reproduce
Can't repro ..

1.  Please see attached gist link with crash log - https://gist.github.com/IoTFier/0e52759e01748f21f96283e43e9da5a9

2.  Please see the attached image 

### Expected Behavior
iOS version of my Xamarin Forms App to work as it works on Android

### Actual Behavior
App Crashes

### Basic Information

- Version with issue: 13.3.1
- Last known good version:
- IDE: VS 16.4.5
- Platform Target Frameworks: 
  - iOS:  13.3
- Nuget Packages: XF v4.4 (latest stable)
- Affected Devices: iOS Phone Simulators

### Screenshots
![image](https://user-images.githubusercontent.com/26844611/75510623-37e41780-59b1-11ea-91a5-fd25707d9cb4.png)

### Workaround
Unknown

**Comment by IoTFier** [comment]
Hi @jsuarezruiz , @pauldipietro - any input on this issue ?
Thank you

**Comment by jsuarezruiz** [comment]
@IoTFier Could you attach a repro sample?.  Thanks for the logs. Reviewing the logs I see the following:

```
Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: value
  at UIKit.UIButton.set_Font (UIKit.UIFont value) [0x0000e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/UIButton.g.cs:859 
  at ButtonCircle.FormsPlugin.iOS.ButtonCircleRenderer.OnElementChanged (Xamarin.Forms.Platform.iOS.ElementChangedEventArgs`1[TElement] e) [0x00089] in <fbde11586d42451093d079a04c1c7b72>:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x00122] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:277 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in D:\a\1\s\Xamarin.Forms.Platform.iOS\VisualElementRenderer.cs:144 
  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) 
```

Are you using ButtonCircle https://github.com/wilsonvargas/ButtonCirclePlugin, right?. Something in the button seems to change and is null https://github.com/wilsonvargas/ButtonCirclePlugin/blob/master/src/ButtonCircle/ButtonCircle.FormsPlugin.iOS/ButtonCircleRenderer.cs#L54

**Comment by IoTFier** [comment]
Hi @jsuarezruiz, thank you for your input. The ttf file required from the 3rd party plugin was missing. @spouliot, had pointed me in that direction over weekend. Thank you @spouliot .

It will be nice if error message from XF was pointing to this issue instead of "Value cannot be null. Parameter name: value". At least highlighting which plugin is erroring out. That will help many development cycles to save time from debugging issues.

Thoughts ?

**Comment by hartez** [comment]
@IoTFier  Which plugin was causing the error?

**Comment by IoTFier** [comment]
@hartez , @samhouts - the plugin [ButtonCircle.FormsPlugin](https://github.com/wilsonvargas/ButtonCirclePlugin)  was causing the error.

In general a wishful expectation will be -

- at the XAML compile time, all 3rd party plugins / nuget packages will be scanned for required resource etc in the platform project. 
- for submitting a nuget / plugin a common set of certification like rules / document for nuget dependencies must be published that will help developer / consumer of those plugins / nuget packages to provide required input / resources
- absence of such document with required asset(s) / resources from those 3rd party nugets / plugins will stop VS from adding those nugets in Xamarin Forms solution [shared & platform projects]
- XAML compilation will flag out missing resources / assets listed and required by those 3rd party nugets / plugins

Thoughts ?

**Comment by IoTFier** [comment]
Hi @hartez , @samhouts - any thoughts ?

**Comment by jfversluis** [comment]
I think those are nice plans, but will require a lot of coordination, infrastructure and resources. So I don't think that will happen in the near future.

If I am reading this correctly the error was originating in a plugin so I am closing this one. If I am mistaken, please let me know

**Comment by IoTFier** [comment]
> I think those are nice plans, but will require a lot of coordination, infrastructure and resources. So I don't think that will happen in the near future. 


**I want to highlight that this does kill the productivity. So, I am not sure how such capabilities are prioritized to be at the back burner which is essential for Xamarin's adoption rate and for the increased efficiency of the app development.

The root cause can be 3rd party or the plugins development by the XF team in MS itself.
The error message makes no meaningful sense. So, not clear on how to interpret the conclusion of this not being relevant in the near future to keep and to increase the Xamarin Form's adoption ?

In which forum, does Xamarin Forms team can review such needs ?** 

> If I am reading this correctly the error was originating in a plugin so I am closing this one. If I am mistaken, please let me know
