### ISSUE TITLE
[Bug] [WPF] MasterDetailPage's Master page is blank on startup when not using MasterBehavior.Popover

### ISSUE THREAD

**Issue by domyd** [xamarin/Xamarin.Forms#9772]
### Description
When using a `MasterDetailPage` with any `MasterBehavior` other than `MasterBehavior.Popover` on WPF, the master page is blank on startup. Toggling it via the hamburger menu or resizing the application window will render it as expected.

### Steps to Reproduce

1. Create a new Xamarin.Forms application with WPF using the Master-Detail-Page template.
2. Update to Xamarin.Forms 4.5.0.356
3. Remove `MasterBehavior = MasterBehavior.Popover;` from the `MainPage`'s constructor
4. Start the WPF application.

### Expected Behavior
I can see two menu entries in the left navigation drawer.

### Actual Behavior
The navigation drawer is open, but nothing is visible and nothing can be clicked.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: 4.4.0.991757
- IDE: Visual Studio 2019 (16.4.5)
- Platform Target Frameworks: 
  - WPF: 4.7.2
- Nuget Packages: Only defaults
  - Xamarin.Forms 4.5.0.356
  - Xamarin.Forms.Platform.WPF 4.5.0.356 (WPF only)
  - Xamarin.Essentials 1.5.0
- Affected Devices: Windows 10 version 1909 (build 18363.535)

### Screenshots

On startup:
![image](https://user-images.githubusercontent.com/5590413/75548852-7a980500-5a2e-11ea-90a4-66390652d513.png)

After toggling through the hamburger menu:
![image](https://user-images.githubusercontent.com/5590413/75548819-6d7b1600-5a2e-11ea-9354-fc39eb0ec100.png)

### Reproduction Link

[MasterDetailBlankTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4267023/MasterDetailBlankTest.zip)

This is a freshly created Xamarin.Forms application, with the Android project removed and WPF added, updated to Xamarin.Forms 4.5. `MasterBehavior = MasterBehavior.Popover;` is removed from `MainPage`'s constructor (same as replacing it with `MasterBehavior.Default`).

Additionally,
```cs
IsPresented = false;
```
is replaced with 
```cs
if (MasterBehavior == MasterBehavior.Popover)
{
    IsPresented = false;
}
```

### Workaround

Put this in your `MasterDetailPage`'s constructor:
```cs
if (Device.RuntimePlatform == Device.WPF)
{
    // you will likely have to play around with the delays
    // and see what works best for your application
    Task.Delay(500).ContinueWith(async _ =>
    {
        // quickly (but not too quickly) toggle IsPresented to force the master page to render
        IsPresented = false;
        await Task.Delay(10);
        IsPresented = true;
    }, TaskScheduler.FromCurrentSynchronizationContext());
}
```

**Comment by melimion** [comment]
broken by https://github.com/xamarin/Xamarin.Forms/pull/8195

when I return Appearing method override, this issue disappears

@mohachouch

**Comment by Xamarin2019** [comment]
**Workaround 2** 
I faced the same problem, Workaround proposed above causes a short-term twitching of the side menu.
It looks like WPF incorrectly processes _ListView_ inside another container in this case _StackLayout_
If you delete _Stacklayout_ and leave only _ListView_ everything works!

**Example :**
`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="MasterDetailBlankTest.Views.MenuPage"
             Title="Menu">
             
    
        <ListView x:Name="ListViewMenu"
                    HasUnevenRows="True">
            <d:ListView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                </x:Array>
            </d:ListView.ItemsSource>
            <ListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Grid Padding="10">
                            <Label Text="{Binding Title}" d:Text="{Binding .}" FontSize="20"/>
                        </Grid>
                    </ViewCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    

</ContentPage>`

I hope will come in handy.
@domyd

**Comment by Xamarin2019** [comment]
And after upgrading Nuget Packages the NavigationBar will disappear. #13746
![image](https://user-images.githubusercontent.com/59281307/178737090-19eb3d2c-f812-418d-a6c0-b69f3999bd76.png)

To fix it, you can override the WindowBackgroundColor key in the resource dictionary. 

**For example, in the App.xaml file in a WPF project**
```
<Application x:Class="MasterDetailBlankTest.Wpf.App"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:local="clr-namespace:MasterDetailBlankTest.Wpf"
             xmlns:wpf="clr-namespace:Xamarin.Forms.Platform.WPF;assembly=Xamarin.Forms.Platform.WPF"
             StartupUri="MainWindow.xaml">
    <Application.Resources>
        <ResourceDictionary>
            <SolidColorBrush x:Key="WindowBackgroundColor" Color="#3498db" />
        </ResourceDictionary>
    </Application.Resources>

</Application>

```
![image](https://user-images.githubusercontent.com/59281307/178738507-e42eabe6-35d4-4859-977a-72af2439a886.png)

**Comment by Xamarin2019** [comment]
But it would be better, I think, to just delete **Background="{TemplateBinding TitleBarBackgroundColor}"** from line 57 of FormsWindow.xaml
![image](https://user-images.githubusercontent.com/59281307/178757938-b20c676c-36d1-4594-b8ca-941916cb9a5c.png)
@mohachouch

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
