### ISSUE TITLE
[Enhancement] IsIndeterminate property on Progressbar

### ISSUE THREAD

**Issue by ChaseFlorell** [xamarin/Xamarin.Forms#9776]
## Summary
It would be super helpful if we could have an `IsIndeterminate` property on the ProgressBar. Haveing this would allow us to switch between Determinate and Indeterminate progress.

## API Changes

```csharp
public static readonly BindableProperty IsIndeterminateProperty = BindableProperty.Create(nameof(IsIndeterminate),
    typeof(bool),
    typeof(ProgressBar),
    default(bool));

public bool IsIndeterminate
{
    get => (bool) GetValue(IsIndeterminateProperty);
    set => SetValue(IsIndeterminateProperty, value);
}
```

e.g.

In order switch between a determinate and indeterminate progress bar (please ignore the "buffered" example in the gif below)
![progress](https://user-images.githubusercontent.com/471626/75563209-d3e84000-59fe-11ea-9dc9-ccb11494abd0.gif)

```xaml
<ProgressBar IsIndeterminate="{Binding HasKnownProgress}" 
             Progress="{Binding KnownProgress}" />
```

## Intended Use Case
For our application, we do data sync with the server. The process is as follows

1. push local changes from the mobile device to the server (indeterminate)
2. ask the server if there are any changes (indeterminate)
3. receive a list of changed tables from the server, begin pulling changes table by table (determinate)

**Comment by ChaseFlorell** [comment]
it would appear as though [Android would make this super easy](https://developer.android.com/reference/android/widget/ProgressBar#indeterminate-progress). Simply remove the Progress from the ProgressBar when `IsIndeterminate = true;`

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
