### ISSUE TITLE
[Bug] "FormattedText" does not accept custom styles (Label)

### ISSUE THREAD

**Issue by eincioch** [xamarin/Xamarin.Forms#9779]
### Description
The "FormattedText" property, does not accept to apply custom styles, shows error when compiling.

### Steps to Reproduce

1. Create Xamarin.Forms project
2. Create custom styles
3. Use the "Text format" property

### Expected Behavior
You should apply the custom style applied.

### Actual Behavior
Does not apply the style, and shows error when compiling.

### Basic Information

- Version with issue: Xamarin Forms 4.4.0.991640
- IDE: Visual Studio Enterprise 2019 Version 16.4.5
- Nuget Packages: Xamarin.Forms
- Affected Devices: Emulador

### Screenshots

![image](https://user-images.githubusercontent.com/12565944/75591814-c195f280-5a4e-11ea-91fd-b71d4701317b.png)

![image](https://user-images.githubusercontent.com/12565944/75591740-81367480-5a4e-11ea-8c39-6c4276929914.png)

Bug
![image](https://user-images.githubusercontent.com/12565944/75591960-18033100-5a4f-11ea-8752-34fad77aaf46.png)

### Workaround
I have solved it, removing styles, and specifying each property that contains my custom style.

![image](https://user-images.githubusercontent.com/12565944/75592032-3bc67700-5a4f-11ea-865f-89eccf886144.png)

**Comment by mohachouch** [comment]
Hi, I think the target type is wrong. Try with TargetType={x:Type Span}

**Comment by hartez** [comment]
It's right there in the error message you've underlined - your style target type is Label, but you are applying the style to a Span.

Change the target type to Span and remove the properties (HorizontalOptions and Margin) which don't exist on Span, and you will see your style applied.

**Comment by eincioch** [comment]
Thank you for the correction!

![image](https://user-images.githubusercontent.com/12565944/75723776-f0100980-5caa-11ea-941c-69c7df953ced.png)
