### ISSUE TITLE
IsVisible=false isn't working with Frames on iOS

### ISSUE THREAD

**Issue by warwlf** [xamarin/Xamarin.Forms#9782]
### Description
Setting IsVisible=false on a Frame either in XAML or by code (or both) does not hide the frame.
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
The frame will be hidden
### Actual Behavior
The frame is visible
### Basic Information
This code has been working for over two years.  If I backout to 4.4, the issue is gone but exists with 4.5.

- Version with issue: Xamarin.forms 4.5 latest release
- Last known good version: Xamarin.forms 4.4.0.991757
- IDE: VS2019 Community lastest release
- Platform Target Frameworks: 
  - iOS:  13.10.0.17

- Nuget Packages:
- Affected Devices:

**Comment by jsuarezruiz** [comment]
I created a repro sample but I can't reproduce the problem.

[Issue9782.zip](https://github.com/xamarin/Xamarin.Forms/files/4275572/Issue9782.zip)

```
<StackLayout>
    <Label
        Text="Visible Frame"/>
    <Frame
        BackgroundColor="Red"/>
    <Label
        Text="Invisible Frame"/>
    <Frame
        IsVisible="False"
        BackgroundColor="Red"/>
</StackLayout>
```

<img width="336" alt="Captura de pantalla 2020-03-02 a las 14 18 43" src="https://user-images.githubusercontent.com/6755973/75679906-c813ac80-5c90-11ea-82b8-9a4d10c973ca.png">

Could you attach a repro sample?

**Comment by bobwhitten** [comment]
Yeah, just got bit by this.  Hoping that fix is real...

**Comment by GrumpyCockatiel** [comment]
Ugh same here... 
![Simulator Screen Shot - iPhone 8 - 2020-03-06 at 21 26 35](https://user-images.githubusercontent.com/17300872/76135935-7604bb00-5ff1-11ea-890e-998fe3056269.png)

**Comment by chinni-nag** [comment]
Hey all, Any update on this issue. Please let me know. Thanks.

**Comment by dzebas** [comment]
On Android IsVisible doesn't work with bindable property. If I set IsVisible = "True" in XAML it works, but if I set IsVisible="{Bindable ShowFrame}" then it doesn't.
