### ISSUE TITLE
[Bug] DatePicker begin to cause Exception in version 4.5.0-282-pre4 and above in some situations

### ISSUE THREAD

**Issue by SunshineSpring666** [xamarin/Xamarin.Forms#9783]
### Description
On version 4.5.0.282-pre4 and above (4.5.0 release), DatePicker raises an Argument Exception when the binded object's context is different from other attribute's context. All previous versions works fine. In my scenario, I need to bind an property (which is of type DateTime) of an object to the DatePicker's Date. In the meantime, I need to bind another property (type bool) to the DatePicker's IsVisible attribute. I specify the BindingContext explicitly but the exception still got raised. 

If I remove the IsVisible binding part, or install the Xamarin.Forms package prior to 4.5.0.266-pre3, the problem doesn't exist anymore. Please help resolve the bug. Thanks.

### Steps to Reproduce

1.  In a page's xaml, define <DatePicker  Date="{Binding Obj.DateToShow}" IsVisible="{Binding InEdit}"/> 
or
<DatePicker  Date="{Binding DateToShow}" BindingContext={Binding Obj} IsVisible="{Binding InEdit, Source={x:Reference this}}"/>   (where "this" is the x:Name of the ContentPage)
2.  In corresponding code-behind, define an object Obj with a DateTime property DateToShow.
3.  In corresponding code-behind, define a bool InEdit, which controls the DatePicker's visibility accordingly.

### Expected Behavior
DatePicker got shown with binded property.

### Actual Behavior
Navigating to the page causes following Exception ( IDE jumps to App.g.i.cs):
"System.ArgumentException: Argument Error.\r\n\r\nreference\r\n   at Windows.UI.Xaml.Media.VisualTreeHelper.GetChildrenCount(DependencyObject reference)\r\n   at Xamarin.Forms.Platform.UWP.FrameworkElementExtensions.GetFirstDescendant[T](DependencyObject element)\r\n   at Xamarin.Forms.Platform.UWP.DatePickerRenderer.WireUpFormsVsm()\r\n   at Xamarin.Forms.Platform.UWP.DatePickerRenderer.ControlOnLoaded(Object sender, RoutedEventArgs routedEventArgs)"

### Basic Information

- Version with issue: 4.5.0.282-pre4 & 4.5.0 release.
- Last known good version: 4.5.0.266-pre3.
- IDE: Visual Studio 2019.
- Platform Target Frameworks: 
   - UWP:  SDK 19551 
- Nuget Packages: Xamarin.Forms 4.5.0 release.
- Affected Devices: UWP

### Workaround
Tried to workaround the bug by putting the DatePicker in a Grid or StackLayout and bind the IsVisible of the layout, but this way doesn't work.
Please help with this bug in latest Xamarin package. Thanks a lot.

**Comment by WoMart** [comment]
You might have found that out already, but:
The problem occurs only on UWP and causes unhandled exception WHENEVER DatePicker's IsVisible is set to False. 
Simpler way to reproduce the problem:
1. Start a new project
2. Update Forms to 4.5
3. In MainPage.xaml replace Content with `<DatePicker IsVisible=False />`

This should cause the exception to get thrown almost immediately

**Comment by hartez** [comment]
@WoMart Thanks for the clarification!

[_9783 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4277690/_9783.Repro.zip)

**Comment by bobrien27** [comment]
Although the issue only occurs in UWP for me as well, I would like to add to the issue when using the default DatePicker as such in my project:  
"<DatePicker Format="M/dd/yyyy" />"
When used in an iOS simulator, the date picker has a standard lightgray border, with white background and black text. However when testing on a physical iPhone Xr, the DatePickers default to a black background with white text. If I attempt to change them they work, however the DatePickers lose the border and only the text appears in the UI.

**Comment by samhouts** [comment]
closed by #9820
