### ISSUE TITLE
[Enhancement] Need team finish the fix performance issue pull request!

### ISSUE THREAD

**Issue by huangjinshe** [xamarin/Xamarin.Forms#9788]
There is a pull request 3 years ago, about performance problems and some Bug about the design, but still not get handle by Xamarin.Forms team. I hope team continue with this feature. It will let Xamarin.Forms performance up to a high level!

[Fix Navigate/Switch to exist page performance and lost state problem in real phone](https://github.com/xamarin/Xamarin.Forms/pull/634)

More detail:[Xamarin.Forms performance still very bad after 3 years!](https://forums.xamarin.com/discussion/179253/xamarin-forms-performance-still-very-bad-after-3-years)

**Comment by VladislavAntonyuk** [comment]
Rather than putting all fixes in single PR, it would be better yo create separate fixes for each defect

**Comment by huangjinshe** [comment]
@VladislavAntonyuk , You say like that mean you're not even read all detail in my post carefully......This is not about multiple defect, it's about huge problem caused by design..... 

The PR is a solution for fixing all platforms performance problems(Also include some bug caused by design) by 1 easy way.

**Comment by VladislavAntonyuk** [comment]
Just reviewed your PR. Please reopen it, so we can discuss your improvements for current implementation, instead of technologies which were marked as obsolete

**Comment by huangjinshe** [comment]
@VladislavAntonyuk , I don't have that permission or power to reopen it. That's why I'm requesting a Xamarin.Forms official team to take the job (also it's been 3 years, the code too old for now I guess).

Also about this request, I still want to say something.


If we could Improve reuse controls for Xamarin.Forms,  Instead of always dispose and initial all things again and again (especially like Page or ContentView), there is huge improve in this Framework. We could just change TemplateBinding if we want to change the page.(We could let developer decide how handle it, create new one every time or reuse the already exists controls.

You didn't use it before, but if you just try what I said about , you would really think it's really a new world, and you can't leave with it ever.  If compared with the current framework, the new way is just like a heaven. trust me.

Also you can decrease unlimited memory leak problems(at least developoer has a temporarily solution before release the App right?) because you always reuse exists things. So that's just a way that 100% benefit without harm .

**Comment by charlesroddie** [comment]
@huangjinshe This is an old pr, rejected a long time ago, so I would forget about that pr. Your approach would appear to increase performance at the expense of memory usage and increased potential for leaks, so I would remove the memory arguments unless you can justify them.

**Comment by huangjinshe** [comment]
> .

@charlesroddie First of all, if you can using it by right way, it won't casue memory leaks, instead it would avoid memory leaks, as I said before in here you can only reusing some existsing stuff. why there will be a memory leaks? 

The feature must enable by developer themselves, so which mean developer know currently some control or page will not disposed immediately. Also I already using 3 years longer in UWP that feature, I can confirm it decrease memory leaks.

If we disgusting about memory leaks, let's analyze memory leaks about this project , see search about "memory leaks" in issues we will see:


[UWP CollectionView memory leak](https://github.com/xamarin/Xamarin.Forms/issues/8928)
[Android/UWP ListView Memory Leak](https://github.com/xamarin/Xamarin.Forms/issues/5451)


As we see in these bugs, problem source is that developer trying to open --- back --- open  --- back, and memory leaks..... Or like creating items for ListView and dispose and Create( no matter changing item source or clear or add....)....until find out memory leacks.... 
Not only about memory leaks, it also will fixing so much problem because current Xamarin.Forms design caused, like:

[[Android, iOS] NavigationPage.PopAsync() cause memory leak by still holding on popped Page](https://github.com/xamarin/Xamarin.Forms/issues/1429)
[Bug 60966 - Can't Navigate To The Same Page Twice](https://github.com/xamarin/Xamarin.Forms/issues/1897)

Look at these problems, You keep saying memory leaks, but there is already has memory leaks in Xamarin.Forms, many years ago had, now also has. Maybe we can avoid it by don't create new one, keep reuse old one.

Maybe even these because switch between exist pages:
[[UWP] ListView scroll issues](https://github.com/xamarin/Xamarin.Forms/pull/634)
[[Bug] Shell recreates a new custom renderer when tap back](https://github.com/xamarin/Xamarin.Forms/issues/9073)


So Xamarin.Forms most memory leaks problems always about: create and dispose resources. my proposal just for avoid them. even if developer has some serious memory problems, can fixing it temporarily by reuse resource let app continue released.

If there is Desktop software developer you will find out he is like to use singleton everywhere.  Why? because most of component in the software just need to create it first time, and use it forever. I just recommen that way, the different is developer decide which page or content view  or Templated View.

3 years ago I realize it's very fast after I changing the code let it support reuse, I also find out ListView slow to changing items ...also still memory leaks in it.  In my hole App only 3 ListView, but these need to change items frequently, it always increase my UWP memory.... Finally I just change all ListView way to TemplatedView(Thank's that time TemplatedView is a new feature just come up).  I always cache TemplatedView and take it when I want to use , also change BindingContext to keep it different.
Now I don't expect you guys bring this feature to every control, Just give it for All pages. Let the open page speed faster. see it first.

We don't need to unlimited create resource in our App, it will more easy memory leaks, so Accurate using this feature not increase memory, also can avoid memory leaks.

Of course you cound also add a method in it, for dispose resource by : 
```
Page.SetRetainsRenderer(true). // tell Xamarin.Forms don't dispose it.
Page.SetRetainsRenderer(false) // tell Xamarin.Forms can dispose it.
```

**Comment by jfversluis** [comment]
Thanks for all the concerns in here and your patience with this! I won't start a whole new discussion here, but please read in this issue for some context: #14205 

Right now we're doing everything we can to keep Xamarin.Forms maintained and as part of that I'm trying to go through the older issues/PRs and see what we need to do with that. For this one, I think it describes a big topic that will be a big focus for .NET MAUI. If there is some things that we can do here with minimal effort, we will, but the bigger effort for this will be in .NET MAUI.

Let me know if I can still help you with anything!
