### ISSUE TITLE
[Enhancement] improve integration capability of Xamarin Forms in Android native UI

### ISSUE THREAD

**Issue by nicolgit** [xamarin/Xamarin.Forms#9793]
## Summary
I am embedding in a Xamarin Android Native page, a xamarin forms element as described in: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms 
 
Everything works fine until the area have a fixed height. I was not able to resize the object to fit its content.
 
here the .axml fragment file that works…
```
<FrameLayout
                android:id="@+id/xamarin_forms_content"
                android:layout_width="fill_parent"
                android:layout_height="800dp"
                />
```
 
This one doesn’t work (nothing shown, probably the height remains zero)
```
<FrameLayout
                android:id="@+id/xamarin_forms_content"
                android:layout_width="fill_parent"
                android:layout_height="wrap_content"
                />
```
 
here the Xamarin form I want to embed:
 
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
            mc:Ignorable="d"
             x:Class="nicold.test.view.MainView"
             >
    <ContentPage.Content>
        <StackLayout Orientation="Vertical">
             <Label Text="lorem ipsut dixit" HorizontalOptions="CenterAndExpand"/>
             <Label Text="lorem ipsut dixit" HorizontalOptions="CenterAndExpand"/>
             <Label Text="lorem ipsut dixit" HorizontalOptions="CenterAndExpand"/>
             <Label Text="lorem ipsut dixit" HorizontalOptions="CenterAndExpand"/>
             <Label Text="lorem ipsut dixit" HorizontalOptions="CenterAndExpand"/>
       </StackLayout>
    </ContentPage.Content>
</ContentPage>
```

this make sense because a ContentPage is expected to be the whole screen/activity, and not a section of a page. 

## API Changes
Allows to integrate generic control in Android Native pages, and not only Content pages. This is very useful in simplfying adoption of xamarin forms on big and complex -non-xamarin-forms- applications-

## Intended Use Case
I have a xamarin app with native ui, and migrate everything can be difficult, so adopting here an there xamarin forms components/controls can facilitate the framework adoption.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
