### ISSUE TITLE
[Bug] [Shell] [iOS] Tabbar Disappears when using --optimize=experimental-xforms-product-type

### ISSUE THREAD

**Issue by dmariogatto** [xamarin/Xamarin.Forms#9794]
### Description

Using the new `--optimize=experimental-xforms-product-type` option in 4.5.0.356. Shell tab bar disappears on switching tabs when preceded by closing a page with `Shell.TabBarIsVisible` set to false. This seems to only occur when the back navigation is performed using the navigation bar, calling `Pop` manually doesn't seem to cause issue.

### Steps to Reproduce

1. Enable `--optimize=experimental-xforms-product-type` 
2. Shell with a tab bar
3. Register a route for a page in the Shell's constructor
4. Add `Shell.TabBarIsVisible="False"` to the page registered in the Shell's constructor
5. Navigate to the page from one of the tabs
6. Close the page using the navigation bar `Back` button
7. Tap on another tab -> the tab bar will disappear

### Expected Behavior

Tab bar should not disappear

### Actual Behavior

Tab bar disappears

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: Unknown
- IDE: Visual Studio 2019 Community 16.4.5
- Platform Target Frameworks:
  - iOS:  11.3.1

### Screenshots

![Using the navigation bar the tab bar disappears](https://user-images.githubusercontent.com/8588913/75669564-23fb2700-5ccb-11ea-89d2-f010b1a6bb7a.gif)

![Manually calling Pop and the tab bar sticks around](https://user-images.githubusercontent.com/8588913/75669608-35443380-5ccb-11ea-8e54-4b1a61683a63.gif)

### Reproduction Link

https://github.com/dmariogatto/xforms-shell-tabbar-issue

### Workaround

Don't use `--optimize=experimental-xforms-product-type` 😢

**Comment by GeorgeVelikov** [comment]
Can confirm this happens, must have spent an hour or so trying to figure it out.

**Comment by thisismyself** [comment]
I our Shell apps it damages the navigation stack on iOS. We could apply a dirty hot fix (manual popping to root when doing certain navigations).
Removing the `--optimize=experimental-xforms-product-type` is not an option, Apples UIWebView Deprecationg Deadline is near.

**Comment by samhouts** [comment]
closed by #10371
