### ISSUE TITLE
App not resuming when launched from another app

### ISSUE THREAD

**Issue by ravinderjangra** [xamarin/Xamarin.Forms#9796]
The app is not resuming but relaunching when the activity is started from any other app. Working fine till API 28. Only showing this behavior in API 29.

### Steps to Reproduce

1. Create two different XF projects
2. Add IntentFilter in one app 
2. Use StartActivity() to launch the first app from another app

### Expected Behavior
The app should resume when the startActivity is called

### Actual Behavior

The app is re-launched and `OnCreate()` is called instead of `OnResume()`

### Version Information

```
=== Visual Studio Community 2019 for Mac ===

Version 8.4.3 (build 12)
Installation UUID: 9e041719-18e8-4ed6-939d-5d2087509263
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.2.402
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.2.7
	2.1.15
	2.1.14
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/maidsafe/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/maidsafe/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Build Information ===

Release ID: 804030012
Git revision: 92973d97d9db919d8cc6d422e9c0599cf9995c47
Build date: 2020-01-24 17:47:54+00
Build branch: release-8.4
Xamarin extensions: 72721c588982f09029f051a38f484feb4c804227

=== Operating System ===

Mac OS X 10.15.2
Darwin 19.2.0 Darwin Kernel Version 19.2.0
    Sat Nov  9 03:47:04 PST 2019
    root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

MFractor 3.9.8
XAML Styler 2.0.1
StyleCop Support 1.1.0.1


```

**Comment by PureWeen** [comment]
@ravinderjangra I tested your app on an API 27 and API 29 device and they both act the same. The behavior I'm seeing is what I'd expect to happen. 

The default for launchMode is "Standard" 
https://developer.android.com/guide/topics/manifest/activity-element

> The "standard" and "singleTop" modes differ from each other in just one respect: Every time there's a new intent for a "standard" activity, a new instance of the class is created to respond to that intent. Each instance handles a single intent. Similarly, a new instance of a "singleTop" activity may also be created to handle a new intent. However, if the target task already has an existing instance of the activity at the top of its stack, that instance will receive the new intent (in an onNewIntent() call); a new instance is not created. In other circumstances — for example, if an existing instance of the "singleTop" activity is in the target task, but not at the top of the stack, or if it's at the top of a stack, but not in the target task — a new instance would be created and pushed on the stack.


if you want the app to only resume the already active activity you need to set LaunchMode to `SingleTop`

```C#
[Activity(
        Label = "CalledApp",
        Icon = "@mipmap/icon",
        Theme = "@style/MainTheme",
        MainLauncher = true,
        LaunchMode = LaunchMode.SingleTop,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    [IntentFilter(
```

I would be confused if the behavior was ever any different than what you're describing..

I read through the comments and I hope I'm not just restating something already talked about.

I'm going to close for now. If changing the LaunchMode to SingleTop doesn't fix for you then please let me know

**Comment by ravinderjangra** [comment]
Thanks @PureWeen. I have been using `LaunchMode.SingleTask` for a long time for this purpose and it seemed to work fine previously. Android doesn't really make it easy to understand and resolve the issue.

This is what I am currently using my code which doesn't let me resume the app. I have tries `LaunchMode.SingleTask` and `LaunchMode.SingleTop` but no change in the behavior.
**Called App**
```
[Activity(
        Label = "@string/app_name",
        Theme = "@style/MyTheme",
        MainLauncher = false,
        LaunchMode = LaunchMode.SingleTop,
        ScreenOrientation = ScreenOrientation.Portrait,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    [IntentFilter(
        new[] { Intent.ActionView },
        Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
        DataScheme = "safe-auth")]
```

**Caller App**
```
var intent = new Intent(Intent.ActionView, aUri);
intent.AddFlags(ActivityFlags.ClearTask);
intent.AddFlags(ActivityFlags.NewTask);
CrossCurrentActivity.Current.AppContext.StartActivity(intent);
```

**Comment by nickmartin1ee7** [comment]
I got my desired activity to foreground (MainActivity) with the Launch Action of `SingleTop` in my Activity and by using the `intent.SetFlags(ActivityFlags.ReorderToFront)` so that my activity was moved to the foreground.

I also used ActivityManager to locate the AppTasks containing my Activity's name and used that to StartActivity with a ActionView intent to that activity class.
