### ISSUE TITLE
Pass Text to Page.DisplayPromptAsync in Xamarin Forms

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9799]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/934687/pass-text-to-pagedisplaypromptasync-in-xamarin-for.html)._

---
i wanted a way to able to pass some text to the page. DisplayPromptAsync method in xamarin forms. i will like to show a prompt to the user with a prefiled answer, that he cant change if they wish to do so. as in i will like it to behave like an entry. Thanks

---
#### Visual Studio Feedback System on 3/1/2020, 04:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by hartez** [comment]
Update to version 4.5 of Forms and you can do this:

```
var answer = await DisplayPromptAsync("Title", "Message", accept: "Ok", cancel: "Cancel", 
placeholder: "Enter text", maxLength: 200, keyboard: Keyboard.Chat, initialValue: "Pre-filled answer");
System.Diagnostics.Debug.WriteLine($"Response was '{answer}'");
```
