### ISSUE TITLE
[Bug]  Tab.Items.Clear() crashes on 4.5.0.356.

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9801]
https://github.com/xamarin/Xamarin.Forms/pull/8215#issuecomment-593608161

Hi guys,

Tab.Items.Clear() crashes on 4.5.0.356.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Attached is a repro solution. Crash occurs in AppShell.xaml.cs line 28 on Tab.Items.Clear()

Thanks

PickerTestApp.zip

**Comment by francis2** [comment]
I forgot to specify this crashes only on iOS.

**Comment by francis2** [comment]
Hi,

I am trying 4.5.0.495 on the same test project I sent to report this issue (#8215), and it does not work with iOS. It appears something else broke in this release.

The "Empty" Shell  Tab is unreachable.

Works fine on Android. Fails on iOS. No errors in Visual studio--only the Tab fails to load properly in iOS.

Attached is a repro solution (same as in #8215).
[PickerTestApp (1).zip](https://github.com/xamarin/Xamarin.Forms/files/4395948/PickerTestApp.1.zip)

![image](https://user-images.githubusercontent.com/11061648/77800736-79fe8880-7045-11ea-9c5c-20bd6f61c26c.png)

**Comment by PureWeen** [comment]
@francis2 this should be fixed on the next releases

I tested your sample against nightly and it didn't crash for me

**Comment by francis2** [comment]
I'm sorry but I have to reopen this issue: the sample does not display the top tabs on iOS. It works fine in Android.

I just tried with Forms 4.5.0.530 and 4.6.0.529-pre3 and I get the same behavior.

If you comment out PickerTestApp/Views/AppShell.xaml.cs line 30 (resultsTab.Items.Clear()), then it works.

This is what's you're supposed to see:

![expected](https://user-images.githubusercontent.com/11061648/78272698-7d759200-74d3-11ea-8c9f-7b78e410c4df.JPG)

**Comment by francis2** [comment]
Hi,  

What should I do to get noticed? Create a new issue and link it to this one?

**Comment by PureWeen** [comment]
Dangit :-/ sorry about this one @francis2 

I've extended my platform UI tests to add top tabs and I'm seeing the issue on iOS

I'll have a PR up for this hopefully today

**Comment by francis2** [comment]
Hi guys, This now runs fine on 4.6.0.967, however I just tried 4.7.0.968 and it crashes. Did someone forget to merge into 4.7?

**Comment by PureWeen** [comment]
@francis2 

just using the same repro as here?

https://github.com/xamarin/Xamarin.Forms/issues/9801#issuecomment-605317541

**Comment by francis2** [comment]
Actually that repro works with 4.7. I'll have to do more tests next week. Could be Telerik controls.

**Comment by francis2** [comment]
I forgot about this one as I'm still using 4.6. So I re-tested today on 4.8:

The crash still occurs on line 25 in AppShell.xaml.cs -> secondTab.Items.Clear();

Xamarin.Forms 4.6.1073
Works as expected on both Android and iOS.

Xamarin.Forms 4.8.1269
Crashes on both OSes. 

Logs and repro attached.

[Android Debug Output.txt](https://github.com/xamarin/Xamarin.Forms/files/5076804/Android.Debug.Output.txt)
[iOS Debug Output.txt](https://github.com/xamarin/Xamarin.Forms/files/5076805/iOS.Debug.Output.txt)
[PickerTestApp.zip](https://github.com/xamarin/Xamarin.Forms/files/5076819/PickerTestApp.zip)

**Comment by francis2** [comment]
Pelase assign someone to look at this--it is broken
