### ISSUE TITLE
[Shell, UWP] Flyout Header permutations

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9803]
### Description

None of the Flyout Header APis are implement on UWP.

I'm wondering if this should be implemented alongside this
https://github.com/xamarin/Xamarin.Forms/issues/6293

The current thinking is to make the Flyout a BindableLayout but the UWP implementation is using native NavigationItems that just populate automatically so this would be a completely different implementation for UWP and not leveraging anything native

**Comment by chrisgull** [comment]
I'd be interesting in seeing this and other Shell aspects being truly cross platform. Thanks guys.

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/1626
