### ISSUE TITLE
[Bug] EmptyView does not respect VerticalOptions

### ISSUE THREAD

**Issue by lavilaso** [xamarin/Xamarin.Forms#9816]
**Description**

When creating a CollectionView or a CarouselView with an EmptyView the latter does not respect the values of the VerticalOptions property, curiously the value of the HorizontalOptions property if it is respected by EmptyView.

**Steps to Reproduce**

1. Create a page with a CollectionView or CarouselView that has an EmptyView with a StackLayout that contains a Label.
2. Set the VerticalOptions and HorizontalOptions properties to center for the Label.
3. Check how the HorizontalOptions property is respected and VerticalOptions is not.

**Version with issue:**

Xamarin.Forms 4.5.0.356

**Platform Affeted:**

Android
iOS: No tested
UWP: No tested

**Reproduction Link:**
[Repo](https://github.com/lavilaso/BugEmptyViewXamarin.Forms)

**Comment by hartez** [comment]
The layout you are using for your EmptyView:
```
<StackLayout>
	<Label Text="Test text" HorizontalOptions="Center" VerticalOptions="Center" />
</StackLayout>
```

produces the same results (text centered at the top of the page) when used in a ContentPage:

![Annotation 2020-03-03 174958](https://user-images.githubusercontent.com/538025/75833824-78f47700-5d77-11ea-94d0-799597f032ef.png)

For the layout you're looking for, I suggest this for your EmptyView content:

```
<StackLayout>
	<Label Text="Test text" HorizontalOptions="Center" VerticalOptions="CenterAndExpand"/>
</StackLayout>
```

![Annotation 2020-03-03 175254](https://user-images.githubusercontent.com/538025/75833958-e1dbef00-5d77-11ea-9dce-a22a570f9a47.png)

It's the same layout used by the "Blank" project template for Forms.
