### ISSUE TITLE
[Bug] Image Source only supports lowercase names Android

### ISSUE THREAD

**Issue by Boowman** [xamarin/Xamarin.Forms#9818]
### Description
I wanted to create an Image element and set the source to an image located in the drawable folder, yet the image is not being displayed. It works in VS Designer but not in the simulator or on a device.

### Steps to Reproduce

1. Add an image that has the name in CamelCase format e.g ChevronRight
2. Create an `<Image` element
3. Set the image source to `Source="ChevronRight"`
4. Build 
5. Try out

### Expected Behavior
The image should be visible on the activity

### Actual Behavior
Image is not visible on the device/simulator
### Basic Information

- Version with issue: 
- Last known good version: ??
- IDE: VS 2019
- Platform Target Frameworks: 29.0.4
  - Android:
      - Android 9.0
      - API 28
- Android Support Library Version: 28.0.0.3
- Nuget Packages: 
   - Xamarin.Android.<All> 28.0.0.3
   - Xamarin.Essentials 1.3.1
   - Xamarin.Forms 4.2.0.815419
- Affected Devices: Android Device (Pixel 2, OnePlus, Samsung S9)

### Workaround
When typing out the name of the file in `Source` it should all be lowercase
1. Add an image that has the name in CamelCase format e.g ChevronRight
2. Create an `<Image` element
3. Set the image source to `Source="chevronright"`
4. Build 
5. Try out

**Comment by hartez** [comment]
@Boowman I'm trying to reproduce this issue, but so far it seems to work just fine for me. I've attached my repro project - can you take a look at tell me if I'm missing something or misunderstanding the issue?

[_9818 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4282497/_9818.Repro.zip)

**Comment by Boowman** [comment]
> @Boowman I'm trying to reproduce this issue, but so far it seems to work just fine for me. I've attached my repro project - can you take a look at tell me if I'm missing something or misunderstanding the issue?
> 
> [_9818 Repro.zip](https://github.com/xamarin/Xamarin.Forms/files/4282497/_9818.Repro.zip)

That is correct, the only difference is that I didn't put in the extension, don't see how that could affect it. I will try the solution in a a bit and let you know if it works for me.

**Comment by Boowman** [comment]
Sorry for the long wait, it does work for me as well, I am just unsure why it does not work in my current project.

**Comment by Boowman** [comment]
I just looked at the `Application Output` and I saw this warning 
`Could not load image named: {0}: ChevronRight
FileImageSourceHandler: Could not find image or image file was invalid: File: ChevronRight`

**Comment by hartez** [comment]
Have you tried replacing the ChevronRight image file with a different one (but keeping the same name)? Maybe there's something Android doesn't like about that particular file.

**Comment by samhouts** [comment]
@Boowman  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
