### ISSUE TITLE
Add BindingContextChanging event to the BindableObject class

### ISSUE THREAD

**Issue by jaredballen** [xamarin/Xamarin.Forms#9825]
## Summary
BindableObject currently emits the BindingContextChanged event after the value of the BindingContext property has been changed. Other properties, of insistences of BindableObject emit PropertyChanging event and a PropertyChanged event. BindingContext should operate similarly.

## API Changes
Add a new public event to BindableObject called BindingContextChanging and add a new virtual method called OnBindingContextChanging.

## Intended Use Case
The intended use is to provide a BindableObject a last chance to set state / cleanup with its bound context before the context is changed.

EX: Given a particular gesture recognizer implementation that detects press, release, and cancel touch. Once a press is detected, if the binding context is changed, there is no way to send a cancellation to the previous binding context. This could leave the previous binding context in a potentially bad state.

**Comment by jcmanke** [comment]
"No way" isn't quite accurate. BindingContext is itself a bindable property, so you can listen for it in the PropertyChanging event/method.

That said I agree a BindingContextChanging event would be a good addition.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
