### ISSUE TITLE
[Bug] [UWP] Propagate CollectionView BindingContext to EmptyView

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [xamarin/Xamarin.Forms#9833]
### Description

At least on UWP, it looks like CollectionView's BindingContext isn't being propagated to `CollectionView.EmptyView`

### Steps to Reproduce

Here, the button's `Command` binding works:

```xaml
<CollectionView ItemsSource="{Binding Path=..., Mode=OneWay}">
	<CollectionView.Header>
		<Button Text="Click me" Command="{Binding MyCommand}" />
	</CollectionView.Header>
	...
</CollectionView>
```

But here, the button's `Command` binding ends up being null:

```xaml
<CollectionView ItemsSource="{Binding Path=..., Mode=OneWay}">
	<CollectionView.EmptyView>
		<Button Text="Click me" Command="{Binding MyCommand}" />
	</CollectionView.EmptyView>
	...
</CollectionView>
```

### Basic Information

- Version with issue: Xamarin.Forms 4.5
- IDE: VS 2019
- Platform Target Frameworks:
  - iOS:  Untested
  - Android: Untested
  - UWP:  Has issue

**Comment by malikberkane** [comment]
Having the same problem
