### ISSUE TITLE
[Bug, iOS] MobileIron causes issues with Editor

### ISSUE THREAD

**Issue by siem300** [xamarin/Xamarin.Forms#9835]
### Description
When MobileIron is used to wrap our app, the Editor Control crashes our app. The following exception is thrown:

"Event registration is overwriting existing delegate. Either just use events or your ouwn delegate: Foundation.NSObject UIKit.UITextView+_UITextViewDelegate"

This issue is only present on iOS.

### Steps to Reproduce

1. Wrap an app using MobileIron
2. The app only needs to contain an Editor
3. App crashes

### Expected Behavior
The app shows a view with an Editor

### Actual Behavior
The app crashes

### Basic Information

- Version with issue: 3.4.0.1008975, probably newer versions as well. We have no access to MobileIron here so newer versions of Xamarin Forms haven't been tested.
- Last known good version: Not sure
- IDE: Visual Studio
- Platform Target Frameworks:
  - iOS:  13.2
  - Android: NA
  - UWP: NA
- Android Support Library Version:
- Nuget Packages:
- Affected Devices: 

### Workaround
From the documentation of MobileIron 4.5.0, they mention that Xamarin.Forms Events on TextFields are not compatible. They suggest the following workaround for this issue:

`UIApplication.CheckForEventAndDelegateMismatches = false` 

Adding this piece of code could result in unforeseen consequences.

**Comment by hartez** [comment]
This is an issue on the MobileIron side; it's not something we can fix in Forms.
