### ISSUE TITLE
[Bug] [WPF] Entry has border

### ISSUE THREAD

**Issue by plamen-i** [xamarin/Xamarin.Forms#9837]
Entry is defined as follows (not relevant parts omitted):
<ContentPage ...
BackgroundColor="#010526">

                    <Label Grid.Row="1"
                           Grid.Column="0"
                           Grid.ColumnSpan="5"
                           HorizontalOptions="Center"
                           VerticalOptions="Start"
                           FontSize="11"
                           Text="Enter your PIN-code to enter as a cashier"
                           TextColor="White" />

                    <BoxView Grid.Row="2"
                             Grid.Column="0"
                             Grid.ColumnSpan="5"
                             Color="#0C2D83"
                             HorizontalOptions="Start"
                             WidthRequest="1" />

                    <BoxView Grid.Row="2"
                             Grid.Column="0"
                             Grid.ColumnSpan="5"
                             Color="#0C2D83"
                             VerticalOptions="Start"
                             HeightRequest="1" />

                    <BoxView Grid.Row="2"
                             Grid.Column="0"
                             Grid.ColumnSpan="5"
                             Color="#0C2D83"
                             HorizontalOptions="End"
                             WidthRequest="1" />

                    <BoxView Grid.Row="2"
                             Grid.Column="0"
                             Grid.ColumnSpan="5"
                             Color="#0C2D83"
                             VerticalOptions="End"
                             HeightRequest="1" />

                    <Entry Grid.Row="2"
                           Grid.Column="0"
                           Grid.ColumnSpan="5"
                           HorizontalOptions="Center"
                           FontSize="17"
                           IsPassword="True"
                           IsReadOnly="True"
                           Placeholder="Cashier PIN"
                           PlaceholderColor="White"
                           Text="{Binding CashierPIN}"
                           TextColor="White">
						<Entry.BackgroundColor>
							<OnPlatform x:TypeArguments="Color">
								<On Platform="WPF" Value="#010526" />
							</OnPlatform>
						</Entry.BackgroundColor>
					</Entry>
</ContentPage>

### Expected Behavior

Same layout in WPF as Android.

### Actual Behavior

Android:
![Android](https://user-images.githubusercontent.com/2354584/75877325-1e632580-5e20-11ea-8f8d-34998a2abe4a.png)

WPF:
![WPF](https://user-images.githubusercontent.com/2354584/75877346-29b65100-5e20-11ea-8d1b-1264d4b28575.png)

### Basic Information

- Version with issue: XF 4.7.0.387-nightly
- Last known good version: N/A
- IDE: Visual Studio 2019 version 16.4.5
- Platform Target Frameworks:
  - WPF: .NET Framework 4.6.1
- Android Support Library Version: N/A
- Affected Devices: Desktop

### Workaround

Not known

**Comment by yurkinh** [comment]
@plamen-i  Here is a workaround for this issue
```csharp
 public class MyEntryRenderer : EntryRenderer
    {

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            
            base.OnElementChanged(e);
           UpdateBorderColor();
        }

        void UpdateBorderColor()
        {
            if (Control == null)
            {
                return;
            }
            Control.BorderBrush = Brushes.Transparent;
        }
    }
```

**Comment by plamen-i** [comment]
Thanks, it works :-)

**Comment by BrayanKhosravian** [comment]
I don't understand how you made that screenshot as I tried to repro this and I always see a line below the entry on android.
I can also see the border of the entry when using Wpf but from my point of view there should be a visual difference between Label and Entry.
And that border is the visual difference on Wpf. 
This is how an Entry looks like natively.
I almost wanted to make a PR based on the workaround of @yurkinh.

Android:
![image](https://user-images.githubusercontent.com/35541212/97122589-41cc3f00-1727-11eb-836c-adefba80748c.png)

Wpf:
![image](https://user-images.githubusercontent.com/35541212/97122687-ffefc880-1727-11eb-8626-bf03ef1ea38b.png)

**Comment by plamen-i** [comment]
@BrayanKhosravian This can depend on Android version or some settings (Launcher etc.).

If I remember correctly screenshot is from Android 7.1 emulator.

**Comment by BrayanKhosravian** [comment]
Yes I can see that you were trying to hide the underline and added a custom box view for the border.

**Comment by jfversluis** [comment]
Taking into consideration the remaining lifetime of Xamarin.Forms, the platform this is about, the age of this issue and the traction this issue has seen I think it's unlikely that this will get fixed. If it is something that you still would like to have, please consider opening a PR. Thanks!
