### ISSUE TITLE
[Enhancement] Duplicate Android PlatformConfiguration SendDisappearingEventOnPause / SendAppearingEventOnResume for Tizen

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/Xamarin.Forms#9844]
## Summary
Below class can be applied to Tizen.net probably. For example, SendDisappearingEventOnPause and SendAppearingEventOnResume appears on Tizen as well and it is pretty useful if we can disable those as we can on Android.

https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/Xamarin.Forms.Core/PlatformConfiguration/AndroidSpecific/AppCompat/Application.cs

**Comment by rookiejava** [comment]
@EmilAlipiev Thank you for your suggestion for Tizen. I'll check what can we do.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
