### ISSUE TITLE
[Bug]  Entry values are not kept when switch tab if I use visual material in xamarin forms shell 

### ISSUE THREAD

**Issue by tal-athena** [xamarin/Xamarin.Forms#9848]
I am developing Xamarin forms shell app.
I want to use Visual Material.
but if I use this, entry values are not kept when switch tabs.

Expect result: entry values are kept when switch tabs
Actual result: 
entry values are changing as one of entry in that page
so, all entry values are set same.

Is there any way to resolve this bug?

**Comment by hartez** [comment]
Can you provide a small project which demonstrates this problem? I've tried adding an Entry control to each tab in a basic Shell project, and the values entered are retained when I switch tabs.

**Comment by tal-athena** [comment]
This problem happens while using Visual Material.
If you install Xamarin.Forms.Visual.Material and add the property Visual="Material" to Entry, then you will get those problems.

**Comment by PureWeen** [comment]
@tal-athena can you attach a repro? I've tested your scenario and it's all working fine for me

**Comment by samhouts** [comment]
@tal-athena Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
