### ISSUE TITLE
Customise RefreshView of ListView,CollectionView

### ISSUE THREAD

**Issue by sarthak1995-26** [xamarin/Xamarin.Forms#9849]
## Summary
ListView and Collection should provide a way to change PullToRefresh View. Like in a chat list if user do pull to refresh we wanted a user to show loading of older chat label or something similar.
ListView Can take a DataTemplate Similar like a HeaderTemplate

## API Changes

<ListView.RefeshViewTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Title}"
                              Detail="{Binding ShortName}"
                              TextColor="#f35e20"
                              DetailColor="#503026" />
                </DataTemplate>
</ListView.RefeshViewTemplate>

More Reference
https://forums.xamarin.com/discussion/153235/how-can-i-customize-the-refreshing-icon-for-a-pull-to-refresh-listview

**Comment by PureWeen** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/10264

**Comment by sarthak1995-26** [comment]
This would work nicely

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
