### ISSUE TITLE
[Bug] Build failed in Android with Forms 4.5 / 4.6 (UpdateIdValues()' in assembly: 'PROJECTNAME.Android.dll')

### ISSUE THREAD

**Issue by MickLesk** [xamarin/Xamarin.Forms#9852]
### Description
We have already been developing our app for some time. We started with Forms 3.3.0. Now we wanted to move our app from 4.4 to 4.5, but when we try to build RELEASE we get the following error.

Building in DEBUG mode is possible.

### Steps to Reproduce

1. Build the App in Release mode (or Archive...)
2.  Error occurs quite quickly

### Expected Behavior
- Building and archiving should be successful

### Actual Behavior
- Building and archiving terminates after a short time with a critical error in a DLL

### Basic Information

- Version with issue: 4.5.0.356 / 4.6-pre1
- Last known good version: 4.4.0.991757
- IDE: Visual Studio 2019 - 16.4.5
- Platform Target Frameworks: Xamarin.Forms
  - iOS:  Build successfully
  - Android: Android 10 (Galaxy S9+ / Xiaomi Mi9 + Mi9T) / Android 9 (Galaxy S8)
  - UWP:  ---
- Nuget Packages: XF 4.5.0.356

### Screenshots 
Mono.Linker.MarkException: Error processing method: 'System.Void PROJECTNAME.Droid.Resource::UpdateIdValues()' in assembly: 'PROJECTNAME.Android.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 Plugin.Media.Resource/Attribute::alpha
   bei Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   bei Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   bei Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Mono.Linker.Steps.MarkStep.ProcessQueue()
   bei Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   bei Mono.Linker.Steps.MarkStep.Process()
   bei Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   bei MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   bei Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   bei Mono.Linker.Pipeline.Process(LinkContext context)
   bei MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   bei Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   bei Xamarin.Android.Tasks.AndroidTask.Execute()	PROJECTNAME.Android			

### Workaround
I have not found a workaround

**Comment by Depechie** [comment]
Same issue, after migrating from 4.4 to 4.5

**Comment by StephaneDelcroix** [comment]
@jonpryor is this a xamarin-android issue ? please advise

**Comment by StephaneDelcroix** [comment]
@Depechie @MickLesk if you have a sample project that shows the issue, please share it. thx

**Comment by MickLesk** [comment]
> @jonpryor is this a xamarin-android issue ? please advise

Its only Xamarin.Android by my Project.
I dont have a Sample for you because our App is very big (logical)..

**Comment by PureWeen** [comment]
@Depechie do you have a repro?

If you just try a brand new project using the VS template do you get the same exception?

@MickLesk @Depechie 

If you link skip your Android head project dll does that fix?

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#linkskip

**Comment by Depechie** [comment]
@pureween I will see for a repo tomorrow !

**Comment by PureWeen** [comment]
@MickLesk @Depechie if you delete your bin/obj directories does that fix?

I just got this error on one of my projects and then deleted the obj/bin and it went away

**Comment by Depechie** [comment]
Hey @PureWeen no that did not fix it. Do note we are still on PCL 4.5 profile 111 instead .Net Standard.

**Comment by Depechie** [comment]
[SteemaTest.zip](https://github.com/xamarin/Xamarin.Forms/files/4342597/SteemaTest.zip)
Hey @StephaneDelcroix and @PureWeen here is a small repro with the external nuget package Steema Charting that is needed in our production application. With Android Release we get the same exception as mentioned in this issue report.

**Comment by MickLesk** [comment]
@PureWeen No, No, this is one of the first things I test when a NuGet package does not work. 

You can look @Depechie 's repro, i can reproduce the error too

**Comment by PureWeen** [comment]
@Depechie @MickLesk are you still seeing the same issue if you update to 16.5?

**Comment by Depechie** [comment]
hmm sorry @PureWeen only have 1 MacBook that is production so nothing else than 8.4.7 on it :/

**Comment by MickLesk** [comment]
@PureWeen 

I get now following error:
`Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Xamarin.Forms.Platform.Android.MediaElementRenderer' (defined in assembly 'Xamarin.Forms.Platform, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Forms.Platform.Android, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Xamarin.Forms.Platform.Android.MediaElementRenderer
   bei Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   bei MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributeArgument(CustomAttributeArgument argument)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributeArguments(CustomAttribute ca)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
   bei Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   bei MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributeArgument(CustomAttributeArgument argument)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributeArguments(CustomAttribute ca)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   bei Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
   bei Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   bei MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   bei Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   bei Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   bei Mono.Linker.Steps.MarkStep.Initialize()
   bei Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   bei MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   bei Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   bei Mono.Linker.Pipeline.Process(LinkContext context)
   bei MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args) in /Users/runner/runners/2.165.0/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs:Zeile 166.
   bei Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   bei Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   bei Xamarin.Android.Tasks.AndroidTask.Execute()	Datengut.Android			
`

**Comment by PureWeen** [comment]
Moved this issue over to Xamarin.Android
https://github.com/xamarin/xamarin-android/issues/4463
