### ISSUE TITLE
[Bug] Swiping Behaviour in ListView inside the ScrollView  is not working properly from version 4.0.0.618610

### ISSUE THREAD

**Issue by saiganeshls2504** [xamarin/Xamarin.Forms#9855]
### Description

Swiping Behaviour in ListView inside scrollView is not working properly from version 4.0.0.618610.

### Steps to Reproduce

1. Run the attach sample. 
2. Swipe the list in right side
3. swiping occurs in opposite direction

### Expected Behavior
Right swipe the list , Right side template will display

### Actual Behavior
swiping in opposite direction and DataTemplate of left Side not worked correctly

### Basic Information

- Version with issue: 4.0.0.618610
- Last known good version: 4.0.0.540366
- IDE: Visual Studio 2019

### Reproduction Link

[SfListViewDemo1.zip](https://github.com/xamarin/Xamarin.Forms/files/4293039/SfListViewDemo1.zip)

**Comment by hartez** [comment]
SFListView is a Syncfusion control; you should [open an issue there.](https://www.syncfusion.com/feedback/xamarin-forms)

**Comment by Chansardrake** [comment]
@hartez 
We have checked sample using Xamarin ListView with SwipeView and the same issue is reproduced. Video sample : [Video](https://www.syncfusion.com/downloads/support/directtrac/general/ze/XamarinListView_with_SwipeView-1327329483.zip)
Project : [ListViewSample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/ListViewSample515448153.zip)

**Comment by Chansardrake** [comment]
@hartez Could you please update on this?

**Comment by jayaleshwari** [comment]
@samhouts , Could you please update on this

**Comment by rmarinho** [comment]
Why do you need a ListView inside a ScrolLView? Any particular scenario ? The Listview already scrolls itself.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
