### ISSUE TITLE
Xamarin forms - Collection View Selected Item [Bug] 

### ISSUE THREAD

**Issue by ramalingeswarakki** [xamarin/Xamarin.Forms#9867]
### Description

Selected collection view item also selecting the 1st item of the list. But when it comes to selected items data, only selected items values are fetching not the 1st item of the list. But its visible as selected.

### Steps to Reproduce

1. Create collection view & bind data. 
2. Change the visual state manager selected item to any color
3. Select any item from list apart from 1st item, both 1st item and other item ( Which you selected ) are visible as selected

### Expected Behavior

only selected item should be visible as selected item

### Actual Behaviour

Selecting 1st item of list even-though not selected

### Basic Information

IDE - VS 2019 Professional - MAC
Forms 4.5.0.356
iOS Simulator iPhone 11 - 11.3 OS       
<img width="354" alt="Screenshot 2020-03-06 at 3 31 52 PM" src="https://user-images.githubusercontent.com/17778243/76073527-bc412680-5fbf-11ea-9210-3843003fece3.png">

In attached screenshot, I have not selected 'ResponseID'

Code Snippet :

<CollectionView BackgroundColor="White" IsGrouped="True" SelectionMode="Multiple" SelectedItem="{Binding Data.CritName, Mode=TwoWay}"  VerticalOptions="FillAndExpand" HorizontalOptions="StartAndExpand"  x:Name="listView" SelectionChanged="listView_SelectionChanged">
                <CollectionView.ItemTemplate>
                            <DataTemplate>
                                                     <StackLayout HeightRequest="40" Orientation="Horizontal" VerticalOptions="StartAndExpand" >
                         <Label LineBreakMode="WordWrap"  Margin="5,0,0,0" x:Name="CriteriaName" TextColor="Black"
                               VerticalOptions="Center" HorizontalOptions="StartAndExpand"
                       FontSize="Small" Text="{Binding Data.CritName}" VerticalTextAlignment="Center"/>           
                          </StackLayout>
                   
                            </DataTemplate>

                </CollectionView.ItemTemplate>
                <CollectionView.GroupHeaderTemplate>
                    <DataTemplate>
                      
                                                        <StackLayout Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
                                     BackgroundColor="#34445e">
                            <Label Margin="5,0,0,0" Text="{Binding Key}" FontSize="18" TextColor="White" VerticalTextAlignment="Center"
                                   VerticalOptions="CenterAndExpand" HorizontalOptions="FillAndExpand"/>
                        </StackLayout>

                    
                   </DataTemplate>
               </CollectionView.GroupHeaderTemplate>
           </CollectionView>

-----------------------------For selected color-----------------

 <ContentPage.Resources>
        <ResourceDictionary>
            <local:GroupHeaderConverter x:Key="TemplateConverter"/>
            <local:GroupHeaderBackgroundColorConverter x:Key="GroupHeaderConverter"/>
           
        </ResourceDictionary>
        <Style TargetType="StackLayout">
            <Setter Property="VisualStateManager.VisualStateGroups">
                <VisualStateGroupList>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal" />
                        <VisualState x:Name="Selected">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor"
                                        Value="#26abe4" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateGroupList>
            </Setter>
        </Style>
    </ContentPage.Resources>

Any help please

**Comment by hartez** [comment]
@ramalingeswarakki Can you provide a repro project which demonstrates the issue? Or at least post the rest of your CollectionView markup?

If you tap on 'Response ID', does it de-select, or does it remain selected? Do you have SelectedItems bound to a viewmodel property? Is 'Response ID' in the CollectionView's SelectedItems list?

**Comment by ramalingeswarakki** [comment]
> @ramalingeswarakki Can you provide a repro project which demonstrates the issue? Or at least post the rest of your CollectionView markup?
> 
> If you tap on 'Response ID', does it de-select, or does it remain selected? Do you have SelectedItems bound to a viewmodel property? Is 'Response ID' in the CollectionView's SelectedItems list?

It's deselecting 'responseID'

**Comment by ramalingeswarakki** [comment]
@hartez 

<CollectionView BackgroundColor="White" IsGrouped="True" SelectionMode="Multiple" VerticalOptions="FillAndExpand" HorizontalOptions="StartAndExpand"  x:Name="listView">
                <CollectionView.ItemTemplate>
                            <DataTemplate>
                                                     <StackLayout HeightRequest="40" Orientation="Horizontal" VerticalOptions="StartAndExpand" >
                         <Label LineBreakMode="WordWrap"  Margin="5,0,0,0" x:Name="CriteriaName" TextColor="Black"
                               VerticalOptions="Center" HorizontalOptions="StartAndExpand"
                       FontSize="Small" Text="{Binding Data.CritName}" VerticalTextAlignment="Center"/>           
                          </StackLayout>
                   
                            </DataTemplate>

                </CollectionView.ItemTemplate>
                <CollectionView.GroupHeaderTemplate>
                    <DataTemplate>
                      
                                                        <StackLayout Orientation="Vertical" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand"
                                     BackgroundColor="#34445e">
                            <Label Margin="5,0,0,0" Text="{Binding Key}" FontSize="18" TextColor="White" VerticalTextAlignment="Center"
                                   VerticalOptions="CenterAndExpand" HorizontalOptions="FillAndExpand"/>
                        </StackLayout>

                    
                   </DataTemplate>
               </CollectionView.GroupHeaderTemplate>
           </CollectionView>

**Comment by ramalingeswarakki** [comment]
I observed this issue when we enable "isGrouped=True". Any help?

**Comment by jsuarezruiz** [comment]
I have tried to reproduce the issue without success.

![issue9867](https://user-images.githubusercontent.com/6755973/79767302-718a2c80-8329-11ea-8d08-9bdaae8708a2.gif)

I am using a grouped CollectionView with a custom Selected VisualState. Could you attach a reproduction sample (zip), please?

**Comment by ramalingeswarakki** [comment]
@jsuarezruiz Could you please make 'Selection mode as multiple' and try.

**Comment by jsuarezruiz** [comment]
@ramalingeswarakki Sure. This is testing the same but using SelectionMode Multiple:
![cv-multiselection-state](https://user-images.githubusercontent.com/6755973/79834293-1bf76380-83ad-11ea-8b3a-46f73aa2f88e.gif)

Still cannot reproduce the issue. I am using Xamarin.Forms 4.6-pre4 (the samples is from Core Gallery https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Controls/GalleryPages/CollectionViewGalleries/GroupingGalleries/GroupingPlusSelection.xaml). not sure if I am missing something, could you help me to reproduce the issue?.

**Comment by samhouts** [comment]
@ramalingeswarakki Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by ramalingeswarakki** [comment]
It's still behaving like earlier after updating forms to 4.8.0.1560;

**Comment by hartez** [comment]
@ramalingeswarakki Can you post the markup for your CollectionView? That might help us understand what's different between your CollectionView and the ones we're testing with.

**Comment by ramalingeswarakki** [comment]
> @ramalingeswarakki Can you post the markup for your CollectionView? That might help us understand what's different between your CollectionView and the ones we're testing with.

Hi Hartez,

Now we don't have any issues with this. We changed binding methodology; So Please close this ticket
