### ISSUE TITLE
[Bug] Xamarin Android AOT Hybrid Compilation Invalid IL code

### ISSUE THREAD

**Issue by taublast** [xamarin/Xamarin.Forms#9876]
### Steps to Reproduce

1. Compile a release version for Android, using Hybrid AOT:

  ```
  <AotAssemblies>true</AotAssemblies>
    **<AndroidAotMode>Hybrid</AndroidAotMode>**
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <BundleAssemblies>false</BundleAssemblies>
    <AndroidDexTool>d8</AndroidDexTool>
<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
```

without Hybrid all above works fine.

https://github.com/taublast/DroidHybridAotBug

### Expected Behavior

Not to crash.

### Actual Behavior

Crashing with Invalid IL code when app tries to get a boolean value using DI. This first crashed when using xamarin.essentials preferences trying to read a boolean value. 
`
 var crash = Xamarin.Essentials.Preferences.Get("Anything", true);`

Changed to string, all went fine. Removed xamarin.essentials (this nuget is not to blame) then app crashed when my ILogger (not in this repro) tried to get a boolean value using DI. Conclusion: this is related to bool using DI.

Repro, use Release: https://github.com/taublast/DroidHybridAotBug

logs:
03-07 09:26:48.077: E/AndroidRuntime(26462): FATAL EXCEPTION: main
03-07 09:26:48.077: E/AndroidRuntime(26462): Process: com.companyname.aothybrid, PID: 26462
03-07 09:26:48.077: E/AndroidRuntime(26462): android.runtime.JavaProxyThrowable: System.InvalidProgramException: Invalid IL code in Xamarin.Essentials.Preferences:PlatformGet<bool> (string,bool,string): IL_0000: ret       
03-07 09:26:48.077: E/AndroidRuntime(26462):   at Xamarin.Essentials.Preferences.Get (System.String key, System.Boolean defaultValue, System.String sharedName) [0x00000] in <af88747156ed45cbb8f18520f965f302>:0 
03-07 09:26:48.077: E/AndroidRuntime(26462):   at Xamarin.Essentials.Preferences.Get (System.String key, System.Boolean defaultValue) [0x00000] in <af88747156ed45cbb8f18520f965f302>:0 
03-07 09:26:48.077: E/AndroidRuntime(26462):   at AotHybrid.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00029] in <a2766fa86ae14654b1c9ed6016e6eacf>:0 
03-07 09:26:48.077: E/AndroidRuntime(26462):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <3c7881444b054fd8ab4d2ab85ee43c60>:0 

### Basic Information
- Forms 4.3 in this example
- Nuget Packages: xamarin essentials in this example
- Affected Devices: tested on x86 and v7a
 
### Reproduction Link

https://github.com/taublast/DroidHybridAotBug

### Workaround

do not use bool in DI, do not use Hybrid AOT..  please no.

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-android/issues/4115
