### ISSUE TITLE
[Bug] [Android Platform] Xamarin.Forms.TabbedPage with 5 children page, changing page very slow from page index 5 to page index 4 with low performance phone.

### ISSUE THREAD

**Issue by haiduong741** [xamarin/Xamarin.Forms#9880]
### Description
If using strong phone, changing page maybe faster. But when my users using the low performance phone, it renderer very slow.

### Steps to Reproduce

1. Create a project with TabbedPage has 5 children page. 
2. In page index 4, create a content with many children is Label
3. Build and Run. Go to page index 5 and click to page index 4. Change page not smooth. It was delay renderer. 

### Expected Behavior
Changing current page faster from page index 5 to page index 4.
### Actual Behavior
Changing was delay. 
### Basic Information
Using a page has many Label it show slow on low performance phone. 

- Version with issue: Every version. 
- Last known good version: Not found
- Platform Target Frameworks: 
  - Android: All

### Screenshots
From About to Browser 4. This issue here
![image](https://user-images.githubusercontent.com/37478492/76150817-e9392a80-60e0-11ea-91c0-e049e1986c6b.png)

**Comment by haiduong741** [comment]
[Xam.App.Demo.zip](https://github.com/xamarin/Xamarin.Forms/files/4302415/Xam.App.Demo.zip)
A demo project here

**Comment by hartez** [comment]
In this [linked issue](https://github.com/xabre/xamarin-forms-tab-badge/issues/82) you mention that you have a TabbedPage with 5 ContentPages. The demo project you uploaded has a TabbedPage with 5 _NavigationPages_ - is that what you intended? Is that a design you are using in a real-world application? 

When you talk about a low-performance phone, what models are you targeting?

**Comment by haiduong741** [comment]
@hartez 
0. Download project here
[Xam.App.Demo.zip](https://github.com/xamarin/Xamarin.Forms/files/4459816/Xam.App.Demo.zip)
1. Create a emulator android same here:
![image](https://user-images.githubusercontent.com/37478492/78961193-dae49100-7b1a-11ea-9902-42daa75c612e.png)
2. Run app and click page index 5.
3. Return page index 4 or else.
=> Do you feel it slowly?

**Comment by jsuarezruiz** [comment]
@haiduong741 I have created an emulator with your suggested settings:
<img width="563" alt="Captura de pantalla 2020-04-21 a las 11 52 12" src="https://user-images.githubusercontent.com/6755973/79852175-9f717e80-83c6-11ea-9020-258c2a16a450.png">
And tested your repro sample:
![tab-perf-issue](https://user-images.githubusercontent.com/6755973/79852217-ad270400-83c6-11ea-95ef-131a0e0fef32.gif)
I don't notice any specific performance issues. I will test the same on an old Android device. Any suggestion?

**Comment by samhouts** [comment]
@haiduong741 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by icalderond** [comment]
i have same proble after to update to Xamarin Forms 5. My tabbed page update  the UI so slow

**Comment by cihancelik60** [comment]
No bug. 

<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="vt_kalafatlar.AppMain"
            xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
            android:TabbedPage.ToolbarPlacement="Bottom"
            android:TabbedPage.IsSmoothScrollEnabled="False"
            android:TabbedPage.IsSwipePagingEnabled="False"
            android:TabbedPage.OffscreenPageLimit="5"
            />

android:TabbedPage.OffscreenPageLimit="5" default 4 changing to 5 or 6

**Comment by cihancelik60** [comment]
xmlns:android="clr-namespace:Xamarin.Forms.PlatformConfiguration.AndroidSpecific;assembly=Xamarin.Forms.Core"
android:TabbedPage.OffscreenPageLimit="5"

default 4. Replace with 5 or 6.
