### ISSUE TITLE
[Enhancement] Add IsVisible to SwipeItem

### ISSUE THREAD

**Issue by ScarlettCode** [xamarin/Xamarin.Forms#9881]
## Summary

When using SwipeView there are situations where you might want to hide some of the swipe items. At the moment there is an IsEnabled (which does nothing) but I think hiding the actual item should be decided by an IsVisible property.

## API Changes

Add IsVisible to SwipeItem

**Comment by jsuarezruiz** [comment]
@ScarlettCode Thanks for the suggestion. You can find this suggestion implemented in https://github.com/xamarin/Xamarin.Forms/pull/9949

**Comment by ScarlettCode** [comment]
Magic! Thank you!
