### ISSUE TITLE
[Bug] Xamarin.Forms Shell.SearchHandler BackgroundColor not applied in iOS 13

### ISSUE THREAD

**Issue by luczha** [xamarin/Xamarin.Forms#9887]
### Description

I have used SearchHandler as following, but in iOS 13.3, the BackgroundColor property doesn't apply when Page is fist loaded. When I go to other page and come back to this page, it works .

```
<Shell.SearchHandler>
    <controls:MySearchHandler x:Name="searchHandler"
        BackgroundColor="#FFFFFF"
        ItemTemplate="{StaticResource MySearchResultItemTemplate}"
        ItemsSource="{Binding MySearchResultsCollection}"
        Placeholder="Search here"
        ShowsResults="true" 
        TextColor="#000000" >
    </controls:MySearchHandler>
</Shell.SearchHandler>
```

- Platform Target Frameworks: 
  - iOS:  13.3

### Screenshots

![c5ELi](https://user-images.githubusercontent.com/47239772/76179405-c8162e00-61f5-11ea-882b-b3c3753c8ef7.png)
![8XLOL](https://user-images.githubusercontent.com/47239772/76179408-c9475b00-61f5-11ea-9f73-73c3bcb6fca2.png)

**Comment by LarsNymand** [comment]
Seeing this too

**Comment by pierre01** [comment]
I have the exact same issue!

**Comment by Nelo-cool** [comment]
I have this issue too. One to one. iOS 14.2 and Xamarin.Forms: 4.8.0.1687

**Comment by OliverMartinson** [comment]
Same Issue here. iOS 14.4  and Xamarin 5.0.0.1931
And unfortunately I couldn't find a workaround

**Comment by goreckia** [comment]
I'm seeing this with iOS 14.5 and Xamarin 5.0.0.2012. #13804 has failed a couple of automated tests. How can we fix this issue?
