### ISSUE TITLE
[Bug] Binding in ListView doesn't work on the first row

### ISSUE THREAD

**Issue by RsZoli** [xamarin/Xamarin.Forms#9890]
# Description

I would like to display some frames in a ListView that has their HeightRequest binded to their Width, so they would be perfectly square on different resolutions!

I have tried with **HeightRequest="{Binding Source={RelativeSource Self}, Path=Width}"** at first, but that doesn't work initially, only after i scrolled the ListView and the frames are redrawed, but it is still hectic...

However, if i bind the frames Width to a property with **Width="{Binding FrameWidth, Mode=OneWayToSource}"** and bind the same property to their HeightRequest with **HeightRequest="{Binding FrameWidth}"** it is working perfectly, but not for the first row!

After scrolling the listview so the first row got redrawed, at id displays fine as well.

### Steps to Reproduce

1. Create a ListView, with frames as itemsource
2. Bind the frame's width to their heightrequest
3. Load the page and scroll the listview

### Expected Behavior

The first row should respect the bindig as well as the other rows

### Actual Behavior

The first row isn't respect the bindig

### Basic Information

- Version with issue: X.F 4.5.0.356
- Last known good version:
- IDE: VS 2019 16.4.5
- Platform Target Frameworks:
  - iOS:  n/a
  - Android: 10.0
  - UWP:  n/a
- Android Support Library Version:
- Nuget Packages:
- Affected Devices: Samsung Galaxy S8, S10

### Screenshots

[image](https://i.imgur.com/ySqFMOY.png)

### Workaround

The very same code works in a CollectionView, but the scrolling performance is unacceptable, so it would be great to use a ListView.

**Comment by StephaneDelcroix** [comment]
please attach a small project triggering this issue, thanks

**Comment by z07713** [comment]
@StephaneDelcroix [there you go](https://drive.google.com/open?id=1e4Q63l-HHZwkTFYxxDpIVuAHIajrTqlh)

Thank you for your attention!

**Comment by RsZoli** [comment]
@StephaneDelcroix any news on this? :(

**Comment by PureWeen** [comment]
@RsZoli what should I be seeing in your repro?

I'm just seeing a bunch of green boxes

**Comment by RsZoli** [comment]
@PureWeen Please notice the very first row of "boxes", they have 1px height!

I tried to indicate it on this [picture](https://i.imgur.com/f4We6Vx.png)

**Comment by PureWeen** [comment]
I tested this with CollectionView and same issue there... I'm guessing it's an issue with the headless grid

**Comment by RsZoli** [comment]
@PureWeen Thats strange! I don't have this particular issue with CollectionView, only the scrolling performace is so bad that i need to use ListView instead :(
