### ISSUE TITLE
Support WPF with Material Visual

### ISSUE THREAD

**Issue by z-tc** [xamarin/Xamarin.Forms#9893]
## Summary
Add support for WPF project in Xamarin Forms

## Intended Use Case
My team is considering using Xamarin Forms for our cross-platform application development( iOS, Android and WPF). Material is a must in our case, and I didn't see that WPF is supported by Material Visual. 
How can we overcome this obstacle? Is there any plan to support this?
Thanks

**Comment by VladislavAntonyuk** [comment]
WPF is supported by community, so feel free to create a PR

**Comment by GalaxiaGuy** [comment]
There is this, which might a good candidate for something to use: http://materialdesigninxaml.net/

It supports both UWP and WPF. It might be possible to implement both platforms using shared files (like some of iOS and macOS) but that might be more trouble than it's worth (which I feel is the case for some of the sharing in iOS and macOS).

**Comment by jfversluis** [comment]
This won't be happening for Xamarin.Forms anymore and Visual Material will probably not be part of .NET MAUI, at least not in its current form. Thank you for the suggestion!
