### ISSUE TITLE
Frame Hide not working in Ios android working fine.

### ISSUE THREAD

**Issue by chinni-nag** [xamarin/Xamarin.Forms#9894]
Frame hide and show is not working fine in Ios , Android working fine in after updating  xamarin forms version to 4.5.

### Steps to Reproduce

1. Implement the isvisible property to the frame
2. try to do false and true where ever you required
3. Observe the Frame is not hiding still its visible 

### Expected Behavior
Frame should not be  visible 
### Actual Behavior
Frame is visible
### Basic Information

- Version with issue:
- Last known good version: 4.4
- IDE:
- Platform Target Frameworks: 
  - iOS:  Iphone 6,7,8
  - Android: Working fine
  - UWP:  Not tested

- Nuget Packages:
- Affected Devices:

**Comment by Domik234** [comment]
Hello, this issue is already posted as #9892 and #9782. You can watch progress there. :)

**Comment by StephaneDelcroix** [comment]
duplicate to #9782

**Comment by chinni-nag** [comment]
@Domik234  The status is showing closed but problem still remains, That is the reason i raised again. Please let me know that issue is resolved or not. Thanks.
