### ISSUE TITLE
[Bug] StackLayout content exit the height.

### ISSUE THREAD

**Issue by Sasikumar3595** [xamarin/Xamarin.Forms#9895]
### Description

In the sample, we have grid split with three rows. background color for the three rows in grid as follows(Blue, Yellow and Transparent with red border). In second row height  in grid as 50 and it holds stacklayout(4 labels, each of label height as 20). The stacklayout children intercept with 3rd row of grid.

### Steps to Reproduce

1. Run the attached sample
2. See the reported issue
3. It only occurred on iOS

### Expected Behavior

- The Content of the stack layout does not intercept with out side of the stack layout

### Actual Behavior

- The Content of the stack layout intercept with out side of the stack layout

### Basic Information

- Issue reproduced in all the version

### Screenshots

![Simulator Screen Shot - iPhone 8 - 2020-03-09 at 17 48 15](https://user-images.githubusercontent.com/44917578/76212299-2c54e400-622e-11ea-91d3-058a9f7a2864.png)

Sample: 
[StackLayoutProblem.zip](https://github.com/xamarin/Xamarin.Forms/files/4306509/StackLayoutProblem.zip)

**Comment by StephaneDelcroix** [comment]
looks like you're forcing a size to small for the content. you might want to use IsClippedToBounds=true

if this doesn't solve your issue, please reopen

**Comment by Sasikumar3595** [comment]
@StephaneDelcroix  and @samhouts 

Any update on this?

**Comment by Sasikumar3595** [comment]
@StephaneDelcroix and @samhouts

Re-open the issue.
