### ISSUE TITLE
[Xamarin Forms]Open FlyLayoutView only by tapping HamburgerIcon not by Swipe!

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#9896]
## Summary
In my application, i need to show FlyoutItems only when i tap HamburgerIcon but not through swiping left to right. Do you have any solution for this for Android & iOS. Can you enable this option using any bool property.

## API Changes

Here, FlyoutLayout behaves differently for iPad & iPhone.
In iPhone - FlyLayout opens only on swiping from left dead of the screen but not on swiping middle or right of screen.
In iPad - FlyLayout opens on swiping anywhere in the shell page middle, left.
I can't use FlyLayoutBehavior as Locked in my MapViewScreen.
It will be helpful if you expose 2 different property or additional property in FlyLayout behavior to disable swipe open the  FlyLayout.

or kindly provide me any code solution to achieve this requirement using renderer of  Android & iOS platform to overcome this behavior.
It will be really helpful. Thanks in advance...

**Comment by StephaneDelcroix** [comment]
this is more a question than a bug report, use the forums, or stackoverflow, if you need help on your code. thanks

**Comment by GnanaPriyaNamasivayam** [comment]
@StephaneDelcroix ,

I already raised the forum report. 
FYI, https://forums.xamarin.com/discussion/comment/405592#Comment_405592

But mine is not a question or workaround in my code.

I asking to provide us **API support to hide Swipe behavior** of FlyLayout in Shell.

**Comment by ivoryguard** [comment]
I also need the API because Flyout swipe gesture blocks the dragging of my custom control.
The issue occurrs on iOS only - Flyout swipe gesture is not execut ed on Android and the drag of my custom control works well.
However, my custom control cannot be drag started to right direction. I have to start dragging to left direction at first in order to drag to right direction.

**Comment by StephaneDelcroix** [comment]
please open a feature request
