### ISSUE TITLE
[Bug] Android release mode deployment gets failed in Xamarin.Forms 4.4.0.991265 and above versions

### ISSUE THREAD

**Issue by RathanakumarSekar** [xamarin/Xamarin.Forms#9898]
### Description

Android release mode deployment gets failed in Xamarin.Forms 4.4.0.991265 and above versions

`[MonoDroid] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.RuntimeException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.RuntimeException: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AlertDialogLayout" on path: DexPathList[[zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/base.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.ar.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.armeabi_v7a.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.de.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.en.apk", zip file "/data/app/com.company.xamari`
### Steps to Reproduce

1. Run the attached sample in release mode.

You can see the reported issue.

### Expected Behavior

Application should work properly in release mode.

### Actual Behavior

Deployment gets failed due to the below error.

`[MonoDroid] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Java.Lang.RuntimeException: Binary XML file line #18: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.RuntimeException: Binary XML file line #18: Error inflating class android.support.v7.widget.AlertDialogLayout ---> Java.Lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.AlertDialogLayout" on path: DexPathList[[zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/base.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.ar.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.armeabi_v7a.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.de.apk", zip file "/data/app/com.company.xamarin.uikit-XUJbBZpcO5q-PZSNSnh9Kg==/split_config.en.apk", zip file "/data/app/com.company.xamari`

### Basic Information

- Version with issue:
Xamarin.Forms 4.4.0.991265 and above.

- Last known good version:
4.3
- IDE:
=== Visual Studio Community 2019 for Mac ===

Version 8.4.6 (build 36)
Installation UUID: 3278dcb1-c583-4703-b99c-ce40a899693c
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

Package version: 606000155

=== Mono Framework MDK ===

Runtime:
Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Version: 3.1.101
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
3.1.1
2.1.15

=== Xamarin.Profiler ===

Version: 1.6.13.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.3.1 (15715)
Build 11C504

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/syncfusion/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
7.0 (API level 24)
7.1 (API level 25)
8.0 (API level 26)
8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/syncfusion/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-13 18:30:48 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-02-13 18:31:08 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804060036
Git revision: 42d1ca78a76fba0d18b600f3bc001625088759a3
Build date: 2020-02-13 22:45:04+00
Build branch: release-8.4
Xamarin extensions: 42d1ca78a76fba0d18b600f3bc001625088759a3

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jan 23 06:52:12 PST 2020
    root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

- Android Support Library Version: 

```
<PackageReference Include="Xamarin.Android.Support.Animated.Vector.Drawable">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Annotations">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Compat">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Fragment">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Media.Compat">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.v7.RecyclerView">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Vector.Drawable">
      <Version>28.0.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.Support.Design" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.AppCompat" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v4" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.CardView" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.v7.MediaRouter" Version="28.0.0.1" />
    <PackageReference Include="Xamarin.Android.Support.CustomTabs" Version="28.0.0.1" />
```

- Nuget Packages:

- Affected Devices:

### Screenshots

 Android Build settings:
<img width="718" alt="Screenshot 2020-03-09 at 7 10 00 PM" src="https://user-images.githubusercontent.com/36629214/76218983-1ac60900-623b-11ea-94d3-4adb1c0414ce.png">
<img width="743" alt="Screenshot 2020-03-09 at 7 10 08 PM" src="https://user-images.githubusercontent.com/36629214/76218990-1e599000-623b-11ea-9626-7a7016fd854a.png">
<img width="747" alt="Screenshot 2020-03-09 at 7 10 16 PM" src="https://user-images.githubusercontent.com/36629214/76218993-1f8abd00-623b-11ea-8d5f-7d6392ad69fa.png">

### Reproduction Link

[Sample.zip](https://github.com/xamarin/Xamarin.Forms/files/4306962/Sample.zip)

**Comment by PureWeen** [comment]
should be fixed with latest release of 4.4+

https://github.com/xamarin/Xamarin.Forms/pull/9318
