### ISSUE TITLE
[Bug] Switch partially disappears leaving just the thumb/circle in dark mode on ANdroid

### ISSUE THREAD

**Issue by HelenMamalaki** [xamarin/Xamarin.Forms#9908]
![Screenshot](https://user-images.githubusercontent.com/4314194/76220244-0f5ce880-620f-11ea-956c-ebf8ec8615cd.png)

### Description
On Android, weather I use the default switch styling (i.e. no custom style) or I add my own style, the switch toggle track disappears when switching in dark mode leaving just the switch thumb behind (see screenshot). 

Thigs I've tried:
1. Adding a switch with no styling `<Switch />`
2. Setting the Switch properties `OnColor `and `ThumbColor`
3. Overriding global theme styles  `<item name="colorControlNormal">#E39696</item>` I found that setting the `colorForeground `works but it's so generic that that also changes the colours on dialogue box titles as well.
4. Overriding the switch in a custom renderer and using 
`this.Control.ThumbDrawable.SetColorFilter(Constants.AppBlue.ToAndroid(), Android.Graphics.PorterDuff.Mode.SrcAtop);`

### Steps to Reproduce

1. Add switch you your app xaml page, in settings turn on Dark mode on Android 10.

### Expected Behavior
I would expect the default grey toggle track to remain when switching to dark mode or some way to successfully customise it. 

### Actual Behavior
Grey toggle track disappears.

### Basic Information

- Version with issue: v4.3.947036
- Last known good version: unknown
- IDE: VS2019
Targeting Android 9 | 10

**Comment by jfversluis** [comment]
Hey @HelenMamalaki I have tried this with the latest 4.6 package and I can't seem to reproduce this (anymore). Would you be able to verify this? Thanks!

[Repro9908.zip](https://github.com/xamarin/Xamarin.Forms/files/4561328/Repro9908.zip)

**Comment by HelenMamalaki** [comment]
@jfversluis Thank you for the sample project! the issue seems with my Android styles for MainTheme.Base; one for parent="MainTheme.Base" and the other for parent="Theme.AppCpmpat.Light" when I changed "Light" -> "DayNight" as in you sample project it fixed the issue. Sorry for my late reply. Thanks again. :)
