### ISSUE TITLE
Xamarin Forms 4.5.0.282-pre4 crash on release mode

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9909]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/926523/xamarin-forms-450282-pre4-crash-on-release-mode.html)._

---
<p>I need to use Xamarin Forms 4.5 to address problem with UIWebView Deprecation on IOS.</p><p>  
</p><p>However, switching to Nuget package Xamarin Forms 4.5.0.282-pre4 makes my app crash on launching in release mode.</p><p>  
</p><p>It launches just fine in debug mode.</p><p>  
</p><p>It compiles fine in release mode.</p><p>  
</p><p>I switch nuget package back to the latest stable version 4.4, the app runs normally.</p><p>  
</p><p>Here is the exception stack.</p><p>  
</p><p>MonoTouch: Could not install sigaction override, unexpected sigaction implementation.</p><p> 
</p><p>2020-02-22 01:02:06.237091+0700 Phoebus.iOS[8568:291499] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=8568</p><p> 
</p><p>2020-02-22 01:02:06.237649+0700 Phoebus.iOS[8568:291499] SecTaskCopyDebugDescription: Phoebus.iOS[8568]/0#-1 LF=0</p><p> 
</p><p>2020-02-22 01:02:06.244373+0700 Phoebus.iOS[8568:291499] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=8568</p><p> 
</p><p>2020-02-22 01:02:06.244573+0700 Phoebus.iOS[8568:291499] SecTaskCopyDebugDescription: Phoebus.iOS[8568]/0#-1 LF=0</p><p>  
</p><p>=================================================================</p><p> 
</p><p>Native Crash Reporting</p><p> 
</p><p>=================================================================</p><p> 
</p><p>Got a SIGABRT while executing native code. This usually indicates</p><p> 
</p><p>a fatal error in the mono runtime or one of the native libraries </p><p> 
</p><p>used by your application.</p><p> 
</p><p>=================================================================</p><p>  
</p><p>=================================================================</p><p> 
</p><p>Native stacktrace:</p><p> 
</p><p>=================================================================</p><p> 
</p><p>0x10db494c5 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_dump_native_crash_info</p><p> 
</p><p>0x10db3dc95 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_handle_native_crash</p><p> 
</p><p>0x10db48a4b - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : sigabrt_signal_handler</p><p> 
</p><p>0x7fff5245b42d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_platform.dylib : _sigtramp</p><p> 
</p><p>0x7ffee21662e0 - Unknown</p><p> 
</p><p>0x7fff5234ba5c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort</p><p> 
</p><p>0x10dd60edf - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_unhandled_exception_handler.cold.1</p><p> 
</p><p>0x10dd57029 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_unhandled_exception_handler</p><p> 
</p><p>0x10dbfe7d7 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_invoke_unhandled_exception_hook</p><p> 
</p><p>0x10db3d849 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_handle_exception_internal</p><p> 
</p><p>0x10db3bcd9 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_handle_exception</p><p> 
</p><p>0x10dabfea9 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_amd64_throw_exception</p><p> 
</p><p>0x10e08a5b0 - Unknown</p><p> 
</p><p>0x10dd56e54 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_process_managed_exception</p><p> 
</p><p>0x10dd5d785 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_invoke_trampoline</p><p> 
</p><p>0x10dd5e994 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_arch_trampoline</p><p> 
</p><p>0x10dd5f35e - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_x86_64_common_trampoline</p><p> 
</p><p>0x7fff25781c30 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation : __NSThreadPerformPerform</p><p> 
</p><p>0x7fff23bd4471 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__</p><p> 
</p><p>0x7fff23bd439c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0</p><p> 
</p><p>0x7fff23bd3bcc - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0</p><p> 
</p><p>0x7fff23bce87f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun</p><p> 
</p><p>0x7fff23bce066 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific</p><p> 
</p><p>0x7fff384c0bb0 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal</p><p> 
</p><p>0x7fff48092d4d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain</p><p> 
</p><p>0x111380874 - Unknown</p><p> 
</p><p>0x1113806e3 - Unknown</p><p> 
</p><p>0x10f9dcc53 - Unknown</p><p> 
</p><p>0x10db530c9 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_jit_runtime_invoke</p><p> 
</p><p>0x10dc72b17 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_runtime_invoke_checked</p><p> 
</p><p>0x10dc780ac - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_runtime_exec_main_checked</p><p> 
</p><p>0x10dabfa12 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : mono_jit_exec</p><p> 
</p><p>0x10dd5e50d - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : xamarin_main</p><p> 
</p><p>0x10da96eb7 - /Users/tung/Library/Developer/CoreSimulator/Devices/EB052449-37D7-4484-A3D2-C860ADD6BF5F/data/Containers/Bundle/Application/B9CA75C7-A854-41C9-955B-BA654C8B6D69/Phoebus.iOS.app/Phoebus.iOS : main</p><p> 
</p><p>0x7fff5227ec25 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdyld.dylib : start</p><p> 
</p><p>0x1 - Unknown</p><p>  
</p><p>=================================================================</p><p> 
</p><p>Basic Fault Address Reporting</p><p> 
</p><p>=================================================================</p><p> 
</p><p>Memory around native instruction pointer (0x7fff523bc7fa):0x7fff523bc7ea  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....</p><p> 
</p><p>0x7fff523bc7fa  73 08 48 89 c7 e9 85 a2 ff ff c3 90 90 90 b8 53  s.H............S</p><p> 
</p><p>0x7fff523bc80a  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 6d a2  ...I....s.H...m.</p><p> 
</p><p>0x7fff523bc81a  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....</p><p>  
</p><p>=================================================================</p><p> 
</p><p>Managed Stacktrace:</p><p> 
</p><p>=================================================================</p><p> 
</p><p>=================================================================</p><p> 
</p><p>2020-02-22 01:02:06.815044+0700 Phoebus.iOS[8568:291499] Unhandled managed exception: Default constructor not found for type Xamarin.Forms.Platform.iOS.FrameRenderer (System.MissingMethodException)</p><p> 
</p><p>  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00076] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark&amp; stackMark) [0x00027] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at System.Activator.CreateInstance (System.Type type) [0x00000] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object source, System.Type visualType, System.Object[] args) [0x000bc] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type) [0x00008] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandler (System.Type type, System.Type visualType) [0x00025] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandlerForObject[TOut] (System.Object obj) [0x0004c] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00005] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000de] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLoad () [0x0008f] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>--- End of stack trace from previous location where exception was thrown ---</p><p>  
</p><p>  at (wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr)</p><p> 
</p><p>  at UIKit.UIViewController.get_View () [0x00036] in &lt;5c82eed61c284fd5b3c2844aba7bbcc4&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.PageRenderer.get_NativeView () [0x00008] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.PageRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x0003d] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.NavigationRenderer.CreateViewControllerForPage (Xamarin.Forms.Page page) [0x00008] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.NavigationRenderer.OnPushAsync (Xamarin.Forms.Page page, System.Boolean animated) [0x0001d] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at Xamarin.Forms.Platform.iOS.NavigationRenderer.&lt;ViewDidLoad&gt;b__46_0 (Xamarin.Forms.Page p) [0x00069] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 </p><p> 
</p><p>  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+&lt;&gt;c.&lt;ThrowAsync&gt;b__7_0 (System.Object state) [0x00000] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 </p><p> 
</p><p>  at Foundation.NSAsyncSynchronizationContextDispatcher.Apply () [0x00000] in &lt;5c82eed61c284fd5b3c2844aba7bbcc4&gt;:0 </p><p> 
</p><p>--- End of stack trace from previous location where exception was thrown ---</p><p>  
</p><p>  at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)</p><p> 
</p><p>  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in &lt;5c82eed61c284fd5b3c2844aba7bbcc4&gt;:0 </p><p> 
</p><p>  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in &lt;5c82eed61c284fd5b3c2844aba7bbcc4&gt;:0 </p><p> 
</p><p>  at Phoebus.iOS.Application.Main (System.String[] args) [0x00000] in &lt;8891ba5a9477405489338b4403607772&gt;:0</p><p>  </p>

---
#### Fiona Niu[MSFT] on 2/24/2020, 00:17 AM: 

<p>Thank you for your feedback! For us to investigate this further, could you please provide the below information?</p>
<ol>
<li>Logs from Help &gt; Open Log Directory (Please first clear logs, reproduce issue, then attach resulting logs.) They can also be obtained via Finder &gt; Go &gt; Go To Folder &gt; ~/Library/Logs/VisualStudio/8.0 .</li>
<li>Steps to reproduce and any related details that may be relevant</li>
<li>Full version details from Visual Studio &gt; About Visual Studio &gt; Show Details &gt; Copy Information [button]</li>
</ol>
<p>We look forward to hearing from you!</p>

#### tung on 2/24/2020, 08:49 PM: 

<p>Here is my full Visual Studio info:</p><p>Visual Studio Community 2019 for Mac
Version 8.4.6 (build 36)
Installation UUID: 67ad4112-8818-48b5-945b-7c89a80ad567
GTK+ 2.24.23 (Raleigh theme)
Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)
Package version: 606000155
Mono Framework MDK
Runtime:
Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
Package version: 606000155
Roslyn (Language Service)
3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d
NuGet
Version: 5.3.0.6192
.NET Core SDK
SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
3.1.101
3.1.100
3.0.101
3.0.100
2.1.505
2.1.302
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks
.NET Core Runtime
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
3.1.1
3.1.0
3.0.1
3.0.0
2.1.15
2.1.14
2.1.13
2.1.9
2.1.2
Xamarin.Profiler
Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
Updater
Version: 11
Apple Developer Tools
Xcode 11.3.1 (15715)
Build 11C504
Xamarin.Android
Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/tung/Library/Developer/Xamarin/android-sdk-macosx
Supported Android versions:
  None installed
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3
Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b
Microsoft Mobile OpenJDK
Java SDK: /Users/tung/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
Android SDK Manager
Version: 16.4.0.10
Hash: 2c49a7d
Branch: remotes/origin/d16-4
Build date: 2020-02-13 18:30:48 UTC
Android Device Manager
Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-02-13 18:31:08 UTC
Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1
Xamarin.Mac
Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500
Xamarin.iOS
Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500
Xamarin Designer
Version: 16.4.0.479
Hash: 074544417
Branch: remotes/origin/d16-4
Build date: 2020-01-22 22:50:22 UTC
Build Information
Release ID: 804060036
Git revision: 42d1ca78a76fba0d18b600f3bc001625088759a3
Build date: 2020-02-13 22:45:04+00
Build branch: release-8.4
Xamarin extensions: 42d1ca78a76fba0d18b600f3bc001625088759a3
Operating System
Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64</p>
</p>

#### Fiona Niu[MSFT] on 2/25/2020, 04:40 AM: 

<p>Thanks a lot for providing the information. We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### tung solved on 2/24/2020, 08:38 PM, 0 votes: 

<p>Hi,</p><p>I took steps you request to produce the log file as you requested. Pleas see attachment.</p><p>My steps to reproduce problem:</p><p>1. Remove Xamarin Forms Nuget 4.4 and install Xamarin Forms 4.5.0.282-pre4.</p><p>2. In the IOS Project Property select Release Mode and set  MTOUCH argument  to  --optimize=experimental-xforms-product-type.</p><p>3. Compile project successfully.</p><p>4. Run App in Release Mode for iPhone. App crash immediately.</p><p>Notes: </p><p>1. without  --optimize=experimental-xforms-product-type. The App launch normally.</p><p>2. The output shows: 2020-02-25 11:35:06.941356+0700 Phoebus.iOS[22772:1521074] Unhandled managed exception: Default constructor not found for type Xamarin.Forms.Platform.iOS.FrameRenderer (System.MissingMethodException)</p><p>I  guess that --optimze option link out some component related to Frame View on IOS platform.</p><p>Full stack trace:</p><p>=================================================================
Managed Stacktrace:
=================================================================
=================================================================
2020-02-25 11:35:06.941356+0700 Phoebus.iOS[22772:1521074] Unhandled managed exception: Default constructor not found for type Xamarin.Forms.Platform.iOS.FrameRenderer (System.MissingMethodException)
  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00076] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at System.Activator.CreateInstance (System.Type type) [0x00000] in &lt;7df0b59b3ac34c319d58e821ad54104a&gt;:0 
  at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type, System.Object source, System.Type visualType, System.Object[] args) [0x000bc] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 
  at Xamarin.Forms.Internals.DependencyResolver.ResolveOrCreate (System.Type type) [0x00008] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 
  at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandler (System.Type type, System.Type visualType) [0x00025] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 
  at Xamarin.Forms.Internals.Registrar`1[TRegistrable].GetHandlerForObject[TOut] (System.Object obj) [0x0004c] in &lt;9abbdf111c5f49ab8a7ccdff768f4d13&gt;:0 
  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00005] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].SetElement (TElement element) [0x000de] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1[TElement].Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement (Xamarin.Forms.VisualElement element) [0x00000] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.Platform.CreateRenderer (Xamarin.Forms.VisualElement element) [0x00014] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.OnChildAdded (Xamarin.Forms.VisualElement view) [0x0003e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.VisualElementPackager.Load () [0x0001e] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
  at Xamarin.Forms.Platform.iOS.PageRenderer.ViewDidLoad () [0x0008f] in &lt;71d76b1a3c5d41c6a44990871ccaac3c&gt;:0 
--- End of stack trace from previous location where exception was thrown ---</p><p><a target='_blank' href="https://developercommunity.visualstudio.com/storage/attachments/120159-ide2020-02-24-17-19-48.log">ide2020-02-24-17-19-48.log</a></p>

**Comment by jfversluis** [comment]
You should be able to overcome this issue by upgrading to the 4.5 stable package. If that doesn't help, please respond to this issue to reopen it or look at the other issues already available on this subject.

Thanks!
