### ISSUE TITLE
Problem With Carouselview Xamarin Forms

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9910]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/927416/problem-with-carouselview-xamarin-forms-1.html)._

---
I’ve use carouselview in my app. When I use PeekAreaInsets attribute, there is bug on platform android. The item not start from start left of page, it look like there is margin/padding on left carouselview. I used value 150 onplatform android, in iOS there is no problem/bug

---
#### Visual Studio Feedback System on 2/23/2020, 09:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Asked the author to report here and hopefully get a reproduction project and some more information.

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by JunkyXL86** [comment]
Today I've faced the same issue where the start item has a margin when you set the PeekAreaInsets. I made a small repro with sliders for the left and right PeekAreaInsets. It looks like only the horizontal and vertical thickness are being respected to make an inset, although I'm not quite sure how left/right thickness should behave.

As you can see, when using PeekAreaInsets, the first item fails. Any other consequent item is aligned to the left with the next item partially visible as you would expect.

Repro:
[CarouselViewIssues.zip](https://github.com/xamarin/Xamarin.Forms/files/7144467/CarouselViewIssues.zip)

Initial state:
![grafik](https://user-images.githubusercontent.com/3984217/132869969-6568a3c3-7fe7-48ed-b107-2142c0062fb7.png)

With PeekAreaInsets:
![grafik](https://user-images.githubusercontent.com/3984217/132869836-c290cfce-593a-4a8f-80ff-b63e3e1454c3.png)
