### ISSUE TITLE
SearchBar causes XAML visualization error

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9914]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/940678/searchbar-вызывает-ошибку-при-визуализации-xaml.html)._

---
Hello, passed the Xamarn Forms project, but ran into trouble when visualizing the page layout. When I add a SearchBar element to the XAML code, the error pops up in the vision box, "There was an exception to the control visualization."

---
#### vitaliy12j on 3/5/2020, 02:00 PM: 

Выяснилось, что данная проблема возникает после обновлении NuGet пакета Xamarin.Forms до версиии v4.5.0.356.<br>
#### Visual Studio Feedback System on 3/5/2020, 10:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jfversluis** [comment]
Asked the author to get in touch since I don't quite understand the issue. Waiting for that.

**Comment by vik12J** [comment]
this problem occurs after updating the NuGet package Xamarin.Forms to version v4.5.0.356

**Comment by jfversluis** [comment]
OK, then you mean the previewer? Would you have a screenshot or some kind of error message?

**Comment by samhouts** [comment]
Hmm, resurgence of https://github.com/xamarin/Xamarin.Forms/issues/4108?

**Comment by vik12J** [comment]
> OK, then you mean the previewer? Would you have a screenshot or some kind of error message?

![screenshot](https://user-images.githubusercontent.com/21186134/77096819-ee6f7100-6a20-11ea-8021-93df70016457.png)

**Comment by jfversluis** [comment]
Would you be able to copy the full text from that white box in the pop up here? That would be super helpful!

**Comment by vik12J** [comment]
> Would you be able to copy the full text from that white box in the pop up here? That would be super helpful!

Unfortunately, the text in this window is not highlighted and not copied, you can only scroll through the list and watch.

**Comment by jfversluis** [comment]
Really appreciate the effort @vik12J thank you so much!

**Comment by samhouts** [comment]
@vik12J If you update to the latest 4.5.0 release, does this issue still occur? Thanks!

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
