### ISSUE TITLE
ListView scroll to footer or header

### ISSUE THREAD

**Issue by nielscup** [xamarin/Xamarin.Forms#9919]
## Summary
The ListView ScrollTo() method allows you to programatically scroll to any item in the list. However, it does not allow you to scroll all the way down to show the footer.

## API Changes

Allow/implement:
`myListView.ScrollTo(myListView.Footer, ScrollToPosition.MakeVisible, true)`
`myListView.ScrollTo(myListView.Header, ScrollToPosition.MakeVisible, true)`

**Comment by cvazquez08** [comment]
This would be a great feature for ScrollTo!

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!

**Comment by nielscup** [comment]
Is MAUI stable enough for production apps already?
