### ISSUE TITLE
[Bug] [iOS] [Android] Grouped ListView issue

### ISSUE THREAD

**Issue by avorobjovs** [xamarin/Xamarin.Forms#9923]
### Description

One of the pages of our application contains a grouped ListView control. Items in each group are displayed with their own DataTemplate. DataTemplates are chosen by the DataTemplateSelector. Each item has a context menu item with command. After the context menu item is tapped, the related command is processed, some business logic is performed, and the item is moved to another group.

The MVVM approach is used in our code. Also, for this purpose, we use some additional third-party libraries. For example, the FreshMvvm framework and the PropertyChanged.Fody library.

In a page model, we use the GroupedList property that returns a grouped list of items. This property is used as a binding for the ListView.ItemsSource property.

When the business logic is performing and some properties of an item are changing, the
RaisePropertyChanged(nameof(this.GroupedList));
expression is executing to refresh GroupedList and rearrange items by groups.

In addition, some UI controls in DataTemplates are bound to some other properties of an item. For example, a visibility of the Information Button and the ActivityIndicator are bound to the IsLoading property of an item.

And the issue is that the latest moved item looks like disabled somehow. But it should not be according to code. But the Information Button is disabled and doesn't work and the item's context menu is also disabled and doesn't work.
And when the next item is moved between groups, it becomes disabled. But the previously disabled one becomes enabled.

This issue happens on both iOS and Android platforms.

### Basic Information

We use the Xamarin.Forms version 4.4.0.991757

When I debug the app from the Visual Studio, the following versions are used:

> Microsoft Visual Studio Enterprise 2019, Version 16.4.5
> Xamarin   16.4.000.313 (d16-4@793df40)
> Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
> Xamarin Templates   16.4.25 (579ee62)
> Xamarin.Android SDK   10.1.4.0 (d16-4/e44d1ae)
> Xamarin.Android Reference Assemblies and MSBuild support.
>     Mono: fd9f379
>     Java.Interop: xamarin/java.interop/d16-4@c4e569f
>     ProGuard: xamarin/proguard/master@905836d
>     SQLite: xamarin/sqlite/3.28.0@46204c4
>     Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b
> Xamarin.iOS and Xamarin.Mac SDK   13.10.0.21 (02c4b3b)

When I build the app on Azure DevOps on the Hosted MacOS build agent, the following versions are used:

> Mono version 6.6.0.155
> Xamarin.Android 10.1.3
> Xamarin.iOS 13.10.0.21
> Xcode 11.3.1

- Last known good version:
Xamarin.Forms 3.2.0.871581

### Reproduction Link

I created a small application that demonstrates this issue. The source code of this project is provided.

[XF44V2_demo_app_source_code.zip](https://github.com/xamarin/Xamarin.Forms/files/4313951/XF44V2_demo_app_source_code.zip)

Also, a screen recording with comments on both platforms is provided.

[XF44V2_Android_screen_recording.zip](https://github.com/xamarin/Xamarin.Forms/files/4313954/XF44V2_Android_screen_recording.zip)

[XF44V2_iOS_screen_recording.zip](https://github.com/xamarin/Xamarin.Forms/files/4314088/XF44V2_iOS_screen_recording.zip)

**Comment by PureWeen** [comment]
@avorobjovs my guess here is that there's a timing issue with the status of CanExecute and the ICommand.   The values you are using to calculate CanExecute aren't going to cause a property changed notification of IsnEnabled to occur so you have to fire the CanExecuteChanged event on the ICommand when the status of your function has changed

For example if I add this
```C#
            (item.InfoCommand as Command<ItemModel>).ChangeCanExecute();
```

After your faked business logic it all works fine.

That's why it's only ever the first item because when you move another item then everything re-evaluates
