### ISSUE TITLE
[Bug] [Android] InputMethodManager's IsAcceptingText persists as true on emulator

### ISSUE THREAD

**Issue by jsclay** [xamarin/Xamarin.Forms#9924]
### Description
We are implementing a keyboard notification system which will send a message when the soft keyboard appears and another message when it goes away. To achieve this on Android, we are listening for global layout changes. When a global layout change occurs, we check to see if it was the keyboard that caused the layout change.

This process relies on InputMethodManager.IsAcceptingText. On a global layout change, we check this property to see if Android is looking for an input. If true, we send a show keyboard notification. If false, we send a keyboard hide notification.

However, once IsAcceptingText becomes true, it never becomes false again on an emulator. It works properly on a physical tablet and sets IsAcceptingText to false once the softkeyboard closes.

Attempted fixes:
1. I have tried setting up an Entry and watching its focus events when clicking on and off it. It properly focuses when clicked, and unfocuses when something else is clicked. Focus does not seem to have an effect on IsAcceptingText.

2. I have tried disabling physical keyboard input to the emulator. No difference made.

3. I have tried creating another emulator. No difference made.

### Steps to Reproduce

1. Create a page with an Entry control.
2. Run the program on an Android Emulator.
3. Get the InputMethodService for the current activity and observe its IsAcceptingText before clicking the Entry. Notice that it is false.
4. Focus the Entry and observe InputMethodService.IsAcceptingText is now true.
5. Unfocus the Entry and observe InputMethodService.IsAcceptingText is still true.

### Expected Behavior
InputMethodManager.IsAcceptingText should only be true when something that can receive text is focused on an emulator.

### Actual Behavior
InputMethodManager.IsAcceptingText becomes true after an input control is focused, and remains true after the control is unfocused.

### Basic Information

- Version with issue: 
- IDE: VS Professional 2019 (16.4.2)
- Platform Target Framework: Android 9.0, API 28
- Nuget Packages:
   - Xamarin.Forms: 4.6.0.379-pre1
   - Xamarin.Essentials: 1.5.1
   - NETStandard.Library: 2.0.3
- Affected Emulator:
   - Android Tablet
   - Target: Android 9.0 (Google API)
   - API level: 28
   - ABI: x86
   - Resolution: 800x1280
   - Size: 10.1"

### Screenshots

Before focus
![EmulatorBeforeShow](https://user-images.githubusercontent.com/18075022/76347289-5e208600-62d4-11ea-8e1e-ee9f6f5e8e89.png)

During Focus
![EmulatorShow](https://user-images.githubusercontent.com/18075022/76347343-755f7380-62d4-11ea-902e-baf3719ccb7f.png)

After Unfocus
![EmulatorAfterShow](https://user-images.githubusercontent.com/18075022/76347357-7b555480-62d4-11ea-974c-2748ea9727e9.png)

### Reproduction Link

InputMethodManager.IsAcceptingText is being used in the KeyboardNotificationProvider class.

https://github.com/jsclay/EmulatorBug

**Comment by PureWeen** [comment]
https://github.com/xamarin/xamarin-android/issues/3403#issuecomment-516552976
