### ISSUE TITLE
[Bug] NSInternalInconsistencyException  when trying to run XamarinTV on iOS

### ISSUE THREAD

**Issue by PureWeen** [xamarin/Xamarin.Forms#9929]
### Description

![image](https://user-images.githubusercontent.com/5375137/76364797-60daa580-62eb-11ea-81f1-a9e20c2ab649.png)

### Steps to Reproduce

- clone the xamarin tv app https://github.com/xamarin/app-xamarintv/tree/ios
- checkout the ios branch
- run app

### Expected Behavior
Doesn't crash

### Actual Behavior

Crashes with Foundation.MonoTouchException: 'Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: negative sizes are not supported in the flow layout

### Basic Information

- Version with issue: 4.7.0.425-nightly

**Comment by TopSkillDeveloper** [comment]
The problem may be that you are filling in CollectionView not in the main thread. Try 
`await Device.InvokeOnMainThreadAsync(() => {  Fill In CollectionView Here  });`

**Comment by PureWeen** [comment]
@TopSkillDeveloper CV should be propagating all CV changes to the main thread itself

**Comment by TopSkillDeveloper** [comment]
> @TopSkillDeveloper CV should be propagating all CV changes to the main thread itself
that's what I'm talking about

**Comment by jfversluis** [comment]
Crashes as advertized
