### ISSUE TITLE
[Enhancement] Add Style to SwipeItem

### ISSUE THREAD

**Issue by daves1992** [xamarin/Xamarin.Forms#9936]
I would rather set the BackgroundColor for instance in a ResourceDictionary so I don't have to keep setting it.

Instead of:

```
                            <SwipeView.RightItems>
                                <SwipeItem Text="Assign" IconImageSource="Tick.png" BackgroundColor="{Binding Source={x:Static services:ServiceProvider.Theme}, Path=Current.ThemeColour}" Command="{Binding Path=BindingContext.AssignCommand, Source={x:Reference CPPickingAdmin}}" CommandParameter="{Binding .}"/>
                                <SwipeItem Text="Delete" IconImageSource="Cross.png" BackgroundColor="Red" Command="{Binding Path=BindingContext.AssignCommand, Source={x:Reference CPPickingAdmin}}" CommandParameter="{Binding .}"/>
                            </SwipeView.RightItems>
```

```
                            <SwipeView.RightItems>
                                <SwipeItem Text="Assign" IconImageSource="Tick.png" Style="{StaticResource defaultSwipeItem}" Command="{Binding Path=BindingContext.AssignCommand, Source={x:Reference CPPickingAdmin}}" CommandParameter="{Binding .}"/>
                                <SwipeItem Style="{StaticResource deleteSwipeItem}" Command="{Binding Path=BindingContext.DeleteCommand, Source={x:Reference CPPickingAdmin}}" CommandParameter="{Binding .}"/>
                            </SwipeView.RightItems>
```

**Comment by thomasgalliker** [comment]
@daves1992 I liked your idea until I found `SwipeItemView`. You can create your custom swipe item view and apply all kind of styles to it. Have a look at the doc: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/swipeview

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
