### ISSUE TITLE
[Bug] (NavigationRenderer) Pop Modal Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by moreirawebmaster** [xamarin/Xamarin.Forms#9938]
### Steps to Reproduce

1. Push multiples MODAL
2. BACK(pop)
3. Exception after

### Expected Behavior
pop modal corretly
### Actual Behavior
exception
### Basic Information

- Version with issue: 4.5
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Workaround

`{System.NullReferenceException: Object reference not set to an instance of an object  at Xamarin.Forms.Platform.iOS.NavigationRenderer+ParentingViewController.Dispose (System.Boolean disposing) [0x00006] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\NavigationRenderer.cs:1044   at Foundation.NSObject.Dispose () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.10.0.17/src/Xamarin.iOS/Foundation/NSObject2.cs:147   at Xamarin.Forms.Platform.iOS.NavigationRenderer+<>c__DisplayClass68_0.<RemoveViewControllers>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x00009] in d:\a\1\s\Xamarin.Forms.Platform.iOS\Renderers\NavigationRenderer.cs:608   at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:155   at System.Threading.Tasks.Task.Execute () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 }`

**Comment by PureWeen** [comment]
Possibly fixed by this PR

https://github.com/xamarin/Xamarin.Forms/pull/9877

**Comment by jfversluis** [comment]
@moreirawebmaster would you by any chance be able to verify if it is indeed fixed by that PR? In that case we can close this one :)

**Comment by samhouts** [comment]
@moreirawebmaster  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
