### ISSUE TITLE
[Bug] Dispose method not called when adding control inside the NavigationPage.TitleView

### ISSUE THREAD

**Issue by sheiksyedm** [xamarin/Xamarin.Forms#9939]
### Description
I have a custom control that unmanaged resources(unsubscribe the events, null the reference) are cleared by the overring Dispose() method of each platform renderer. Control objects are cleared from memory when doing page navigation or removed it from parents (because unmanaged resources are cleared by calling the Dispose method on each platform renderer). But when adding control in NavigationPage.TitleView and do the page navigation it won't clear from memory, because of Dispose method doesn't fire, hence unmanaged resource holds the control reference. 

### Steps to Reproduce

1. Run the attached sample 
2. Do the page navigation back and forth
3. Application gets the crash because the dispose method is not called in order to close the stream.  
4. Add the same control as the content of ContentPage instead of TitleView, it will be working fine. 

[Note: just created sample for reproduce issue in UWP, this is not actually scenarios]

### Expected Behavior
Dispose method is should be called so that unmanaged control resources should be cleared. 
### Actual Behavior
Dispose method is not to be called. 

### Basic Information
- IDE: VS2019 Enterprise 
- Nuget Packages: XF 4.3.0.908675

### Reproduction Link

https://github.com/sheiksyedm/TitleViewDemo

**Comment by jfversluis** [comment]
Thanks for taking the time to report this @sheiksyedm!

I don't quite get this part

> [Note: just created sample for reproduce issue in UWP, this is not actually scenarios]

The reproduction only shows UWP, right? But did you also check Android and iOS? Does the issue show there as well? Did you check?

**Comment by sheiksyedm** [comment]
Hi jfversluis, 

Yes, I've tried all three platforms (UWP, Android and iOS) and had a problem with UWP and iOS. In Android, the dispose method properly called when navigating away from the page.
