### ISSUE TITLE
[Bug] System.NullReferenceException at ResetSwipe Android

### ISSUE THREAD

**Issue by aimore** [xamarin/Xamarin.Forms#9942]
### Description
[MonoDroid] System.NullReferenceException: Object reference not sefandrt to an instance of an object.
### Steps to Reproduce

1. Swipe right to left item

### Expected Behavior

App should not crash

### Actual Behavior

App crashes
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://gist.github.com/aimore/314ff0c947ba44539c26a44c2e3c5aba

**Comment by jsuarezruiz** [comment]
@aimore Taking a look at the log seems to be problem closing the SwipeView on Android, but could you share which version are you using? To be able to do more tests, could you attach a repro sample?.

**Comment by aimore** [comment]
It is working after XF update
Will close this issue.
