### ISSUE TITLE
Xamarin Android TexView prevents scrolling in Android version above 8 (API 27)

### ISSUE THREAD

**Issue by Devaraj-Sekar** [xamarin/Xamarin.Forms#9944]
Xamarin Android TexView prevents scrolling in Android version above 8 (API 27)

### Description
Xamarin Android TexView prevents scrolling in Android version above 8 (API 27)

### Steps to Reproduce

1. Create a xamarin android sample with horizontal scroll view and multiple tabs in scroll view.
2. Added textview as a content of the fist tabview and now scroll the scrollviewer
3. Scroll will be automatically reset to 0,0 position - Occurs only in Android version above 8

### Expected Behavior

Scrolling should be proper

### Actual Behavior

Scrolling reset to 0,0 position

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: Android 8
  - Android: version above 8 , API level 27
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Android version 8 above samsung s8, s9/ google pixel

### Workaround
Searching for it, currently no workaround.

**Comment by Devaraj-Sekar** [comment]
Hi @pauldipietro ,

Similar to this issue - https://stackoverflow.com/questions/57456560/scroll-view-not-scrolling-on-api-level-26-and-further-but-working-on-below-api-l 

Regards,
Devaraj S

**Comment by Devaraj-Sekar** [comment]
Hi @samhouts ,

Please help on this issue or share your suggestion.

Regards,
Devara S

**Comment by jfversluis** [comment]
Hi @Devaraj-Sekar thanks for taking the time to report this.

I'm very sorry, but I don't quite understand how to reproduce this with your description. Would you be able to create a little sample project that shows this problem? That will help us identify the potential problem and hopefully resolve it for you quickly, thanks!

**Comment by samhouts** [comment]
@Devaraj-Sekar  Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
