### ISSUE TITLE
iOS SetDynamicResource not working properly with ListView background color on runtime.

### ISSUE THREAD

**Issue by gopalawasthi123** [xamarin/Xamarin.Forms#9945]
I have implemented the dark mode in my app after upgradation of Xamarin.Forms some of the elements do not change their color on run time . In my case all pages work fine except the page have listview the color is not changing on runtime.

### Steps to Reproduce

1. Open the app. 
2. Change the mode to dark. 
3. All the elements changes their color instead of the listview background color.

### Expected Behavior
ListView should change the background color on runtime.
### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: 2.5
- IDE:
- Platform Target Frameworks:  iOS
  - iOS:  13.4.02
  -
- Nuget Packages:
- Affected Devices: iphone 11 pro (simulator)

**Comment by StephaneDelcroix** [comment]
could you please attach a sample reproduction project ? thx

**Comment by gopalawasthi123** [comment]
Sorry can't do it right now.. but i will try to do it asap

**Comment by samhouts** [comment]
@gopalawasthi123 Okay, we'll wait to hear from you. Thanks!

**Comment by jfversluis** [comment]
@gopalawasthi123 if you could add a reproduction project that would be great. Also, make sure to test with the latest 4.6 version and see if this is still an issue.

Thanks!

**Comment by gopalawasthi123** [comment]
@jfversluis  I am closing this issue as in latest xamarin forms i am not able to reproduce it. Additionally as in the previous versions by giving the color to the cell solve the problem as a workaround. Thanks!
