### ISSUE TITLE
While Scrolling up and down the collectionview  getting Black dots on Screen

### ISSUE THREAD

**Issue by chinni-nag** [xamarin/Xamarin.Forms#9947]
While Scrolling up and down in collection view getting Black dots on the screen in Ios and Android as well

### Steps to Reproduce

1. Try to add collectionview
2. to do scroll up and down
3. you can observe the black color dots on the screen in Ios and android

### Expected Behavior
Should not come the black dots on the screen while scroll up and down
### Actual Behavior
 black dots visible on the screen while scroll up and down
### Basic Information

- Version with issue: 4.5
- Last known good version:
- IDE: Visual studio 
- Platform Target Frameworks: 
  - iOS:  
  - Android: Experienced in Samsung J6 9 version I think all versions of Android is happening same 
  
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:Experienced in Samsung J6 9 version I think all versions of Android is happening same

**Comment by StephaneDelcroix** [comment]
I don't understand what you're trying to report. Attaching a reproduction project, and some screenshots would definitely help.

**Comment by chinni-nag** [comment]
@StephaneDelcroix Please check the below video attached

**Comment by chinni-nag** [comment]
@StephaneDelcroix  Please check u r inbox i could not able to upload here showing high memory.

**Comment by luismts** [comment]
+1

**Comment by chinni-nag** [comment]
@StephaneDelcroix  Any update on this? Please let me know. Thanks in advance.

**Comment by PureWeen** [comment]
@luismts Can you attach a repro?

**Comment by samhouts** [comment]
@chinni-nag Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by hartez** [comment]
I think this is a duplicate of #8361
