### ISSUE TITLE
[Enhancement] Shell.Current.Navigation.PopAllModalPagesAsync

### ISSUE THREAD

**Issue by MaxFmi** [xamarin/Xamarin.Forms#9950]
## Summary
In a scenario where a second ModalPage (on top of the first one) is needed, it is not possible to pop all modal pages at once. Calling "Shell.Current.Navigation.PopModalAsync"will only pop the one ModalPage on top. It is not possible to pop both at once.

## API Changes
1) Start navigationStack: /rootPage/somePages/ModalPageA/ModalPageB
2) Shell.Current.Navigation.PopAllModalPagesAsync();
3) Final navigationStack: /rootPage/somePages

## Intended Use Case
Given a coffee machine where the user has the option to buy coffee beans.
First ModalPage: Select Coffee beans
Second ModalPage: Checkout / Press Buy --> navigate back to coffee machine overview after buy was pressed.

**Comment by Mikilll94** [comment]
This would be great because even if you loop all the pages in the NavigationStack and do PopModalAsync for every page, then it is looking bad. The transition is not smoothly from current page to the root page. Instead during the animation, all pages in the NavigationStack are shown for a while.

**Comment by PureWeen** [comment]
@MaxFmi can you test a variation of your request here in 5.0? 

Taking your example above if you do the following

- Start navigationStack: /rootPage/somePages/ModalPageA/ModalPageB
- `Shell.Current.GotoAsync("//rootPage/somePages")`

or you can also do
`Shell.Current.GotoAsync("../..")`


Which should yield the same results

**Comment by MaxFmi** [comment]
True that will work: Shell.Current.GotoAsync("//rootPage/somePages")
But to do so we would need to add additional logic to hold the absolute route that ends right before the first modal page. It's kind of holding a state. States make code more complex. It would be simpler to have a method that pops all modal pages at once.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
