### ISSUE TITLE
[Bug] Android 10 Setting ThumbColor on Switch causes a square block

### ISSUE THREAD

**Issue by Jason424242** [xamarin/Xamarin.Forms#9951]
### Description

Setting ThumbColor on Switch when targeting Android 10 and running on an Android 10 emulator causes a square block in place of the round switch.  

### Steps to Reproduce

1. Create a new project, update to the latest nuget packages, and set Android target to 10
2. Add  `<Switch ThumbColor="Green"/>` to MainPage.xaml
3. Run on an Android 10 emulator

### Expected Behavior

Round switch thumb

### Actual Behavior

Square switch thumb

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: Unknown
- IDE: Visual Studio 2019
- Platform Target Frameworks: 
  - Android: 10 
- Nuget Packages: Xamarin Forms 4.5.0.356, Xamarin Essentials 1.5.1
- Affected Devices:

### Screenshots

![Screenshot_1584030889](https://user-images.githubusercontent.com/62111760/76544202-0877e500-645e-11ea-9c81-056b3415ab7d.png)

**Comment by StephaneDelcroix** [comment]
thx. could you please add a small reproduction project ? thanks

**Comment by matteopiccioni** [comment]
I have the same problem

**Comment by tossingc** [comment]
@StephaneDelcroix I have attached a small sample project which reproduces the issue: [XFIssue9951.zip](https://github.com/xamarin/Xamarin.Forms/files/4390937/XFIssue9951.zip)

![image](https://user-images.githubusercontent.com/847707/77712071-b7f5a100-6fa0-11ea-8cb7-5b1913b2ac63.png)

NOTE: this also happens on physical devices - testing with a Pixel 3.

**_The issue is triggered by changing the compilation target from Android 9.0 to Android 10.0._**

**Comment by felipechavez** [comment]
Same problem here.
